### ISSUE TITLE
Provide detailed reference documentation for the new endpoint infrastructure

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10001]
Some things to document:

- `@Endpoint`
- `@JmxEndpointExtension`
- `@ReadOperation`
- `@Selector`
- `@WebEndpointExtension`
- `WebEndpointResponse`
- `@WriteOperation`
- Type conversion
- Web request predicates (GET for read, POST for write, produces, consumes, etc)
- Default response status for web operations (200, 404 for null with GET, 204 for null with POST, etc)
- Support for HTTP range requests to operations that return a `Resource` (WebFlux and Spring MVC only)
- `-parameters` is required to infer parameter names
- `@Nullable` for optional parameters

**Comment by shabino** [comment]
Please consider documenting `endpoints.<endpoint name>.cache.time-to-live` and that the value is expressed in millis.

**Comment by shabino** [comment]
See https://github.com/spring-projects/spring-boot/issues/11010 for a suggestion regarding `@Selector` parameter naming.

**Comment by snicoll** [comment]
> Please consider documenting endpoints.<endpoint name>.cache.time-to-live and that the value is expressed in millis. 

It is already [documented](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties). Also, your IDE should tell you that when you use that key in application.properties/yml

**Comment by philwebb** [comment]
We should add a small section in the reference docs to explain what the cache is for and how to configure it.

**Comment by snicoll** [comment]
There's a bunch of stuff already done as part of #10176. I'll review what's missing still.

**Comment by snicoll** [comment]
Also, let's make sure we document the dependency to `-parameters` (see https://github.com/spring-projects/spring-boot/issues/11010#issuecomment-344155006)

**Comment by manderson23** [comment]
In the documentation regarding unauthenticated access to actuator with the sample code you provide would it be useful to mention that csrf being enabled by default results in calls to POST end points being forbidden? This caught be out on upgrade from 1.5.x.

**Comment by snicoll** [comment]
@manderson23 see #11758
