### ISSUE TITLE
Request for Enhancement - JSTL support

### ISSUE THREAD

**Issue by k-tamura** [spring-projects/spring-boot#10006]
JSTL does not work on Spring Boot application although Spring Boot Dependencies includes:

	<dependency>
		<groupId>javax.servlet</groupId>
		<artifactId>jstl</artifactId>
		<version>${jstl.version}</version>
	</dependency>

See also: https://stackoverflow.com/questions/45667582/jstl-support-in-spring-boot

**Comment by snicoll** [comment]
There is no need to open a duplicate, let's keep the discussion on stackoverflow.
