### ISSUE TITLE
Support velocity engine 2.0 ?

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#10008]
http://velocity.apache.org/engine/2.0/changes.html

**Comment by lawlietfans** [comment]
i have the same question
![image](https://user-images.githubusercontent.com/8612867/29318614-7804130c-8203-11e7-84b1-e7ed86ba6dc2.png)

**Comment by snicoll** [comment]
Velocity support has been removed as of Spring Framework 5 and therefore our support as well (even deprecated in earlier version). As far as I can see there is no spring support in Velocity 2 so you may want to ask that to them first.
