### ISSUE TITLE
management endpoint giving authentication error when security.ignored set as /**

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-projects/spring-boot#10018]
We have set security.ignored = /** to skip security for our application endpoints but here when we are hitting management endpoint as /env it is giving below error as 

    {
    "timestamp": 1502877601150,
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource.",
    "path": "/env"
    }

we have overridden certain properties as per our requirement as

security.user.name
security.user.password
security.user.role
security.basic.realm
security.enable-csrf
security.sessions=STATELESS
management.security.roles
management.context-path=/ 

I could see that when we hit /env SecurityContextHolderAwareRequestFilter's doFilter()  method is not getting called which basically wraps servletRequest as

            chain.doFilter(this.requestFactory.create((HttpServletRequest) req,
				(HttpServletResponse) res), res);

so in MvcEndpointSecurityInterceptor's  isUserAllowedAccess() returning false. Here we do not want to skip security for management endpoints.

**Comment by mbhave** [comment]
@JagmohanSharma Is there a reason why you want to skip security entirely vs using the `security.basic.enabled=false`? This flag will turn off authentication for your application endpoints but leave the management endpoints secure.

**Comment by JagmohanSharma** [comment]
@mbhave actually we wanted it to be disabled entirely. as this application does not need to be secured from anyone. Will security.ignored = /** not work for management endpoints as do we need to make management.security.enabled = false explicitly to make this working in this case? Or security.basic.enabled is the only option to keep management endpoint secured and others unsecured.

**Comment by mbhave** [comment]
`security.ignored=/**` will skip the filter chain entirely for your user defined and management endpoints. This is not recommended since it will switch off some additional features that Spring security provides. It sounds like `security.basic.enabled` should do what you want. It will open your application endpoints to everyone while keeping management endpoint security intact.

**Comment by JagmohanSharma** [comment]
@mbhave Thank you so much for clarifying this. This really helps. :)
