### ISSUE TITLE
SpringBootTest with property 'spring.main.webApplicationType=reactive' breaks loading the configuration annotated with SpringBootApplication

### ISSUE THREAD

**Issue by zxkane** [spring-projects/spring-boot#10017]
I have a reactive application based on spring boot 2.0.0.M3.

The application was started by explicitly setting the application type as `REACTIVE`.
```java
public static void main(String[] args) {
		SpringApplication application = new SpringApplication(AgentApplication.class);
		application.setWebApplicationType(WebApplicationType.REACTIVE);
		application.run(args);
	}
```

If running test case annotated `SpringBootTest` with below property `spring.main.webApplicationType=reactive`,  the above configuration class annotated with `SpringBootApplication` is not processed by spring context `org.springframework.context.annotation.ConfigurationClassParser#processImports`.
```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
        ,properties = {"spring.main.webApplicationType=reactive"}
)
```

You can play with the demo project [here](https://github.com/zxkane/spring-boot-webflux-router-issue/tree/spring-boot-test-reactive).

**Comment by snicoll** [comment]
Spring Cloud starts a context to retrieve the configuration of the config server and for some reason that fails with that setup. I've removed the spring cloud bits from the build of this project and that tests works fine for me.

Please consider creating a minimal sample next time. Support of reactive in Spring Cloud is ongoing,  please reach out to them if you need more information.
