### ISSUE TITLE
Add a "test your own auto-configuration" section

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10011]
Now that we have a dedicated helper to test auto-configurations (`ApplicationContextRunner` and friends), it would be nice to document it in the reference documentation.

**Comment by marti1125** [comment]
Hello! @snicoll Is it too hard issue for a new contributor?

**Comment by snicoll** [comment]
Hey, I really can't say. Writing this documentation is mostly about writing down best practices and how to use the tools we use ourselves. If you've done that, contributions are always welcome and I am more than happy to guide you in the process. 

We also have [an ideal-for-contribution label](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) with issues we think are relevant for this.
