### ISSUE TITLE
FreeMarkerAutoConfiguration is missing  class presence checks

### ISSUE THREAD

**Issue by arminnaderi** [spring-projects/spring-boot#10027]
Spring Boot version: 2.0.0.M2

Adding WireMock as a dependency seems to be causing the web server to be configured during integration tests, and consequently accessing servlet jars which are not on the classpath.

I have attached a sample application. Please run the `RemoteWatchServiceTest` to reproduce the bug. The problem is solved using `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)` on every integration test class (OR removing the WireMock dependency), however this becomes very verbose when many tests are involved. I tried setting `spring.main.web-application-type=none` in `application-test.properties` however that is picked up too late according to @snicoll.

Intellij project below:

[wiremock-webserver-bug.zip](https://github.com/spring-projects/spring-boot/files/1230428/wiremock-webserver-bug.zip)

**Comment by snicoll** [comment]
Here is a project that reproduces the issue:
https://github.com/spring-projects/spring-boot-issues/tree/master/gh-10027

The web server is not starting, the Freemarker auto-configuration is kicking in because it is present and it misses some `@ConditionalOnClass` checks.
