### ISSUE TITLE
Document property -> security.oauth2.resource.jwk.key-set-uri

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#10022]
v1.5.2.RELEASE introduced `ResourceServerTokenServicesConfiguration.JwkTokenStoreConfiguration` which auto-configures a Spring Security OAuth `JwkTokenStore` if the property `security.oauth2.resource.jwk.key-set-uri` is available in the `Environment`.

A Spring Security OAuth user is [asking](https://github.com/spring-projects/spring-security-oauth/issues/1050#issuecomment-320781967) if there is a property available to allow for this auto-configuration to take effect and so I noticed that it has not been documented in the reference documentation.

Can you please document this property in the sections _28.1 OAuth2_ and _Appendix A. Common application properties_ so users are aware.

**Comment by snicoll** [comment]
The whole OAuth security properties are quite a mess to be honest. Things are mapped multiple times and the reason why those properties aren't fully documented. I'd be more in favour of adding something in the doc itself.

**Comment by snicoll** [comment]
@jgrandja I think it would be better to update [this section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-resource-server), would you agree?

We can dump the list of keys but as we map them to third parties object (something I hope we can finally fix in 2.x), I don't see much value in doing that.
