### ISSUE TITLE
Upgrade to Spring Integration 4.3.12

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#10034]
Spring Cloud Stream 1.3 has a dependency on SI 4.3.12; since it gets its versions via Spring Boot, we need to ensure 1.5.7 gets this version.

**Comment by snicoll** [comment]
@garyrussell SI 4.3.12 is not available on Maven central :(

**Comment by snicoll** [comment]
OK my bad, I misunderstood the issue description. It's not released yet and this issue is to make sure we wait for 4.3.12
