### ISSUE TITLE
spring-hateoas:0.23.0 with jackson:2.9.x

### ISSUE THREAD

**Issue by Pytry** [spring-projects/spring-boot#10035]
#### Example Project 

https://github.com/Pytry/jackson2halmodule-bug-spring-hateoas.git

#### Description of Bug

"org.springframework.hateoas:spring-hateoas:0.23.0" does not work properly with version "2.9.0+" of the "com.fasterxml.jackson.core" libraries.

The error happens because the Jackson2HalModule has a constructor that always passes null to one of the Jackson classes , which then always causes a NullPointerException to be thrown (line 613 in Jackson2HalModule).

#### Suggested Resolution

In Spring-boot 1.5.6+, please update the dependency version of spring-hateoas to 0.24.0.RELEASE or greater as soon as it is available, regardless of whether the Jackson.version is updated since some users may have to or want to use the 2.9.x versions before Spring2 is released.

**Comment by snicoll** [comment]
There is no need to open an issue for things that are already fixed. We have a semi-automated process for upgrading to new releases of our dependencies. We will pick up the Spring Data (including Spring Hateoas)  in due course.
