### ISSUE TITLE
Jackson XML serialization ignoring application.configuration properties when using jersey JAX-RS

### ISSUE THREAD

**Issue by dmbeer** [spring-projects/spring-boot#10044]
Hi I am using spring-boot 1.5.6 with spring-boot-starter-jersey with the following dependencies.

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-jersey</artifactId>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.dataformat</groupId>
	<artifactId>jackson-dataformat-xml</artifactId>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.jaxrs</groupId>
	<artifactId>jackson-jaxrs-xml-provider</artifactId>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.datatype</groupId>
	<artifactId>jackson-datatype-jsr310</artifactId>
</dependency>
```

When I try to serialize Java 8 `LocalDateTime` in XML I get an array output event tough I have the following property set in application.properties:

`spring.jackson.serialization.write_dates_as_timestamps=false`

This seems to work for JSON but not XML.

Attached is an example project.
[jersey-xml-javadate.zip](https://github.com/spring-projects/spring-boot/files/1235083/jersey-xml-javadate.zip)

**Comment by wilkinsona** [comment]
This is working as described in the javadoc for `JacksonXMLProvider` which you've registered in its default form. By default it uses an `XmlMapper` in its default configuration. If you want to use a custom `XmlMapper` you can configure it using the auto-configured `Jackson2ObjectMapperBuilder` and then pass it into the provider:

```java
public JerseyConfig(Jackson2ObjectMapperBuilder builder) {
    register(DateEndpoint.class);
    register(UserEndpoint.class);
    XmlMapper xmlMapper = new XmlMapper();
    builder.configure(xmlMapper);
    register(new JacksonXMLProvider(xmlMapper));
}
```

**Comment by dmbeer** [comment]
@wilkinsona Thanks for your reply. I managed to get this working in the end not useing the Jackson2ObjectMapper but by creating a class that implements ContextResolver<XmlMapper> and adding the various modules and properties like so:
```
@Provider
@Produces(MediaType.APPLICATION_XML)
public class JacksonXMLConfig implements ContextResolver<XmlMapper> {

    private static XmlMapper xmlMapper;

    public JacksonXMLConfig() {
        JacksonXmlModule xmlModule = new JacksonXmlModule();
        xmlModule.setDefaultUseWrapper(false);
        xmlMapper = new XmlMapper(xmlModule);
        xmlMapper.registerModule(new JavaTimeModule());
        xmlMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
        xmlMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }

    @Override
    public XmlMapper getContext(Class<?> aClass) {
        return xmlMapper;
    }
}
```

You then have to register the provider in the equivelent JerseyConfig, this is due to Jersey's class path scanning is broken. This become more evident when creating a resulting jar. I still think that configuring the Jackson XmlMapper is harder than it should be. The @Provider actually gets ignored by spring boot and jersey as they can't register and scan them.
