### ISSUE TITLE
Spring-data-jpa got wrong results

### ISSUE THREAD

**Issue by heiheiyuan** [spring-projects/spring-boot#10056]
Question

This is my code:
public interface GradeRepository extends JpaRepository<GgUserGrade,String> {

    @Query("select t.gradecode FROM GgUserGrade t where t.usercode = :userCode")
    List<String> findGrades(@Param("userCode") String userCode);

    List<GgUserGrade> findByUsercode(String userCode);

}
-------------------------------------------------------------------------
When I use method 2-----findByUsercode,I will get  result like this:
[
{companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
},
{
companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
},
{
companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
},
{
companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
},
{
companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
},
{
companycode: "3700",
usercode: "37000933",
gradecode: "002",
invaliddate: null,
creatorcode: null,
createtime: null,
updatercode: "admin",
updatetime: 1486950209000,
validind: "1",
remark: null,
flag: null
}
]
description:
The count of result is right,but each of result is same with others,actually,I expect to get result like this:

1	3700				002			admin	2017/2/13 9:43:29	37000933	1
2	3700				009			admin	2017/2/13 9:43:29	37000933	1
3	3700				010			admin	2017/2/13 9:43:29	37000933	1
4	3700				011			admin	2017/2/13 9:43:29	37000933	1
5	3700				014			admin	2017/2/13 9:43:29	37000933	1
6	3700				RPT			admin	2017/2/13 9:43:29	37000933	1
just count is right,but data are same.
Please help me,thank you so much!

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
