### ISSUE TITLE
EntityManagerFactoryBuilder cannot be used as advertised

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#10068]
The [reference documentation suggests](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-two-entity-managers) to use `EntityManagerFactoryBuilder` to setup `EntityManagerFactory` instances in case one has to configure multiple ones. Unfortunately, the code shown doesn't work as the `EMFB` bean is created by `JpaAutoConfiguration` which expects a singular `DataSource` instance in the first place. Manually excluding that configuration then results in the `EMFB` not being present and the invocation of the factory method failing.

Maybe the auto-configuration for `EMFB` can be moved to a separate class that is not dependent on a single `DataSource` instance?

Related tickets: #5542, #5541.

**Comment by snicoll** [comment]
It isn't that easy unfortunately.  The `EMFB` requires a `JpaVendorAdapter` and the latter uses the `DataSource` to determine the database in use. A bunch of other properties are also related to the platform itself. 

It is weird to provide such service as a bean and then make it work on a totally unrelated `DataSource`. The only reason it is a bean in the first place as far as I can see is to be able to tune it if necessary.

Back to the doc, it is incomplete as it doesn't tell you how to obtain that `EntityManagerFactoryBuilder`. Just adding an injection point suggests indeed that Spring Boot is going to provide one but I don't think that's a good idea. 

My suggestion at this point would be to clarify the doc. Thoughts?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
