### ISSUE TITLE
Add -test dependencies to starters

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#10062]
We are using both Spring Batch and Spring Security in our Spring Boot based application. For this we use the respective `spring-boot-starter-batch` and `spring-boot-starter-security`. We also have quite some tests and for this we use classes from `spring-batch-test` and `spring-security-test`. 

However these `*-test` dependencies aren't part of the respective starters. Would be nice that when adding a starter the test dependencies would also be included in the project.

**Comment by snicoll** [comment]
There is no way to do that I am afraid and we don't want to bring that by default in the `spring-boot-start-test`. We already include the security starter on start.spring.io when security is selected. We can imagine doing the same for batch, feel free to raise an issue there.

**Comment by raderio** [comment]
@snicoll you can add them to spring-boot-security-tests
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-security-tests/1.5.7.RELEASE

**Comment by snicoll** [comment]
Why would we do that? It is an internal module used for integration tests. You're not supposed to use that.

**Comment by raderio** [comment]
So, spring-boot-security-tests and spring-security-test are not related?
And we should mix boot and spring modules in build system?
