### ISSUE TITLE
Spring-boot 1.5.6: StringToInstantConverter throws a ConverterNotFoundException for an invalid date string

### ISSUE THREAD

**Issue by 66-24** [spring-projects/spring-boot#10065]
**Problem**
I have a custom [StringToInstantConverter](https://github.com/66-24/config_demo/blob/master/src/main/java/com/configuration/config_demo/StringToInstantConverter.java) registered using `@ConfigurationPropertiesBinding` that converts an ISO-8601 date string to a `java.util.Instant`.

For an invalid date string, the application throws a ConverterNotFoundException for the types String to Instant. 

I would have expected spring-boot to run the registered Converter and have the Converter throw an Exception about the invalid date string instead. The stacktrace seems very misleading given the root cause of the issue.

**Background**
I have documented the issue [here](https://stackoverflow.com/questions/45773307/spring-boot-1-5-6-converternotfoundexception-when-mapping-string-to-java-util-i):

The code to reproduce the issue is [here](https://github.com/66-24/config_demo) .
Changing the date string to an invalid date in [config_demo.xml](https://github.com/66-24/config_demo/blob/master/src/main/resources/demo_config.xml) will recreate the issue

**StackTrace**
```java
org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'demo' on field 'endDateTime': rejected value [20080915T155300Z]; codes [typeMismatch.demo.endDateTime,typeMismatch.endDateTime,typeMismatch.java.time.Instant,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [demo.endDateTime,endDateTime]; arguments []; default message [endDateTime]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.Instant' for property 'endDateTime'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.time.Instant]]
at org.springframework.boot.bind.PropertiesConfigurationFactory.checkForBindingErrors(PropertiesConfigurationFactory.java:359) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:276) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]  
spring-boot
```

**Comment by snicoll** [comment]
Your implementation doesn't validate the input String either and that simply throws an exception back to the converter. The `ConversionService` has multiple converters and if one fails, it'll try the next. 

Now the end exception could mention it tried to invoke a converter and that actually failed rather than the current message. This is part of the core framework so if you want to pursue, please raise [an issue on Jira](https://jira.spring.io/browse/SPR)
