### ISSUE TITLE
Some times,a jar is not loaded

### ISSUE THREAD

**Issue by lyfeng** [spring-projects/spring-boot#10070]
I use 1.4.3.RELEASE version,but some times,I found a jar is not loaded,and when the code executed,cause java.lang.ClassNotFoundException.Is it a bug of this version?

**Comment by bclozel** [comment]
Unfortunately, you're not giving us much to work with.
Note that this sounds a lot like a corrupt dependency cache. Try to run `mvn dependency:purge-local-repository` or to clear your Gradle cache, depending on the build tools you've chosen.

Please reopen this issue once you've got a complete stacktrace and a consistent way to reproduce this problem. A sample project (that you could attach here or create on github) is usually the best choice.

Thanks,
