### ISSUE TITLE
Possible wrong import from guava

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#10085]
In master for boot 2.x, it looks like `TestPropertyValues` has import from guava
```
import com.google.common.collect.Streams;

public static TestPropertyValues of(Iterable<String> pairs) {
		if (pairs == null) {
			return empty();
		}
		return of(Streams.stream(pairs));
	}
```
Maybe this was a mistake and meant to use something from jdk? Anyway, guava is evil and should not be there.

**Comment by dsyer** [comment]
In spring cloud we fail the build of any source files import guava. It's quite an easy mistake to make.
