### ISSUE TITLE
Extending docs regarding testResources

### ISSUE THREAD

**Issue by jwedel** [spring-projects/spring-boot#10088]
I followed the section "72.1.1 Automatic property expansion using Maven" mentioned here:

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html

I changed the pom as explained, ran my integration tests and application context startup failed because if the `@` in my configuration.

I took me a while to figure out, that because I was having a separate application.yml in `test/resources`, I needed another section in my pom:

```
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
```

I think it would be nice to include that as well or at least to mention the existence of `testResources` below the `resources` example.

**Comment by snicoll** [comment]
@jewdel I am not following. What took you a while to understand? That we don't filter test resources? The documentation has an explicit `src/main/resources` code snippet there.

**Comment by jwedel** [comment]
@snicoll I know, that for that explicit example, it's correct. However, in my actual application, I have a configuration in `src/test/resources` and I was using the `@some.var@` variable there. The application was starting, but the tests didn't run although I was using the same variable in both `application.yml` files.
I took me a while to find out that there is a separate section for `testResources`.

So my suggestion is, to have info section after the `<resources>` snipped that points the *if you want to replace variables in your test resources as well, you would need the `<testResources>`section as well.

**Comment by snicoll** [comment]
@jwedel thanks for the feedback. Explaining how Maven works is not the purpose of our ref guide. I have however clarified that only production resources are filtered by the parent in 3672251

**Comment by jwedel** [comment]
@snicoll perfect, thanks!
