### ISSUE TITLE
Auto-configure Freemarker for WebFlux applications

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#10094]
In Spring Boot 2.0.0.M3, `spring-boot-starter-freemarker` depends on `@AutoConfigureAfter(WebMvcAutoConfiguration.class)`, it should support `spring-webflux` based application.

**Comment by bclozel** [comment]
Could you describe the actual issue?
What have you tried? What behaviour did you expect? What did you get instead?

The `spring-boot-starter-freemarker` brings both freemarker and Spring MVC. So getting that starter will configure a Spring MVC application. So `@AutoConfigureAfter(WebMvcAutoConfiguration.class)` has nothing to do with this; it merely asks Spring Boot to process that auto-configuration after the Spring MVC one.

We don't have Freemarker support for Boot + WebFlux for now - maybe that's what you're actually looking for?

**Comment by hantsy** [comment]
@bclozel Yes, I want to freemarker (`spring-boot-starter-freemarker`) support for both WebMVC and  WebFlux. I have checked the source codes of `spring-webflux`, it includes a webflux based freemarker support.

Currently if we can start a `spring-webflux` and add `spring-boot-starter-freemarker`, it will add spring-webmvc, the firstly problem I found in my sample is the Webflux based security config was not affected.

**Comment by hantsy** [comment]
Currently in a webflux project, I have to configure freemarker myself.

https://github.com/hantsy/spring-reactive-sample/blob/master/boot-freemarker/src/main/java/com/example/demo/DemoApplication.java#L65-L79

**Comment by bclozel** [comment]
Several configuration keys in the `spring.freemarker` namespace aren't applicable right now, since the Freemarker support is not (yet?) on par in Spring Framework for both MVC and WebFlux:

```properties
# the reactive resolver does not inherit from an AbstractCachingViewResolver
spring.freemarker.cache=false # Enable template caching.
# the reactive resolver can be configured with a list of supported media types
spring.freemarker.content-type=text/html # Content-Type value.
# keys supported by o.s.web.servlet.view.AbstractTemplateViewResolver
spring.freemarker.allow-request-override=false # Set whether HttpServletRequest attributes are allowed to override (hide) controller generated model attributes of the same name.
spring.freemarker.allow-session-override=false # Set whether HttpSession attributes are allowed to override (hide) controller generated model attributes of the same name.
spring.freemarker.expose-request-attributes=false # Set whether all request attributes should be added to the model prior to merging with the template.
spring.freemarker.expose-session-attributes=false # Set whether all HttpSession attributes should be added to the model prior to merging with the template.
spring.freemarker.expose-spring-macro-helpers=true # Set whether to expose a RequestContext for use by Spring's macro library, under the name "springMacroRequestContext".
```

Properties that can be supported in WebFlux right now (or are common to MVC and WebFlux):

```properties
spring.freemarker.charset=UTF-8 # Template encoding.
spring.freemarker.check-template-location=true # Check that the templates location exists.
spring.freemarker.enabled=true # Enable MVC view resolution for this technology.
spring.freemarker.prefer-file-system-access=true # Prefer file system access for template loading. File system access enables hot detection of template changes.
spring.freemarker.prefix= # Prefix that gets prepended to view names when building a URL.
spring.freemarker.request-context-attribute= # Name of the RequestContext attribute for all views.
spring.freemarker.settings.*= # Well-known FreeMarker keys which will be passed to FreeMarker's Configuration.
spring.freemarker.suffix=.ftl # Suffix that gets appended to view names when building a URL.
spring.freemarker.template-loader-path=classpath:/templates/ # Comma-separated list of template paths.
spring.freemarker.view-names= # White list of view names that can be resolved.
```

We should decide if this is the intended situation in Spring Framework and do something about the configuration namespace in Boot, or if Spring Framework should also support these keys.
