### ISSUE TITLE
Move EndpointEnablementProvider and EndpointEnablement

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10099]
I think `EndpointEnablementProvider` and `EndpointEnablement` are just used for conditions. We can probably move package and make them package private.

**Comment by wilkinsona** [comment]
As things stand `EndpointEnablementProvider` is used by `EndpointProvider` so the current usage isn't limited to conditions.

**Comment by snicoll** [comment]
If `EndpointProvider` moved in the same package as the condition that would be possible. If that's not too weird, I think it'd be better for those two classes to be private (I meant it that way originally).

**Comment by philwebb** [comment]
I missed `EndpointProvider`. I'll take another look.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/10176 took care of this.
