### ISSUE TITLE
Actuator endpoints can no longer be mapped to the application namespace

### ISSUE THREAD

**Issue by whitneyh** [spring-projects/spring-boot#10103]
In version 2.0, the actuator endpoints have been moved to /application/foo. I see that there is a configuration property (management.context-path) that allows for the context path to be changed; however, if I change it to '/' in an attempt to restore 1.X behavior, I'm told that I have to change the management port. This breaks my environment. It would be great if there was a way to restore the 1.X behavior if desired.

**Comment by wilkinsona** [comment]
We're going to revert the change made for #9898. As that hasn't been released (it was made post 2.0 M3) we'll use that issue for tracking.
