### ISSUE TITLE
Bean methods for MVC endpoints are not consistently annotated with @ConditionalOnMissingBean

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#10105]
It would be nice if properties were sorted in the `EnvironmentEndpoint` and `EnvironmentMvcEndpoint`. This would greatly help humans when looking at the output of those two endpoints.

Could this feature be integral part of SpringBoot ?

We managed to create our own `SortedEnvironmentEndpoint` bean by subclassing the original version. Luckily, the original factory is already annotated with `@ConditionalOnMissingBean` so our own version is selected without any problem.

This is not the case however for the `EnvironmentMvcEndpoint. The factory is *not* annotated with `@ConditionalOnMissingBean`. The only option is therefore to rely on _overriding bean definition_ which requires proper ordering of the `@Configuration` classes. 

--> Could the EnvironmentMvcEndpoint be made `@ConditionalOnMissingBean` as well ?

_Tested on SpringBoot 1.5.6.RELEASE_

**Comment by wilkinsona** [comment]
As with https://github.com/spring-projects/spring-boot/issues/3761, my opinion is that sorting of this kind belongs on the client side. I certainly don't think it should be something that's done by default.

Looking at `EndpointWebMvcManagementContextConfiguration` we're a bit inconsistent in the use of `@ConditionalOnMissingBean`. `HealthMvcEndpoint` has it but none of the other MVC endpoints do. 2.0 has already addressed this so the question is if it's worth changing in 1.5.x.

**Comment by brenuart** [comment]
I understand your arguments against sorting on the server-side.

However, it would be nice if the other endpoints (all?) were annotated `@ConditionalOnMissingBean`. This would allow users to easily replace the default implementation with their own if they feel the need to do so.

Are you saying `2.0` provides such an easy way ?

**Comment by stepio** [comment]
Still this could be a very nice usability feature, which could be disabled with a dedicated property - to please those who prefer super-performance. Anyway such a sorting could not be too expensive and these "admin" endpoints does not seem performance-critical functionality.

**Comment by wilkinsona** [comment]
> Are you saying 2.0 provides such an easy way ?

Yes. In 2.0, the `EnvironmentEndpoint` is `@ConditionalOnMisingBean` and, thanks to the improved endpoint infrastructure, there's no MVC or web-specific adapter involved.

**Comment by brenuart** [comment]
Nice. I can wait until then if your team decides not to define all endpoints `@ConditionalOnMissingBean`.
