### ISSUE TITLE
How to enable PUT and DELETE in tomcat and jetty embedded

### ISSUE THREAD

**Issue by yukatan** [spring-projects/spring-boot#1010]
I'm developing a REST api with spring boot but I've problems with put and delete methods. I think is a server relates problem, but I could not find how to solve it.

**Comment by marklaff** [comment]
@yukatan katan - any way you can share the CSRF token solution?  I'm having a similar problem, but getting a 405 
```
$ curl -X PUT -v localhost:8081/components/vmax -d STARTING -H "Content-Type:text/plain"
*   Trying ::1...
* Connected to localhost (::1) port 8081 (#0)
> PUT /components/vmax HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type:text/plain
> Content-Length: 8
> 
* upload completely sent off: 8 out of 8 bytes
< HTTP/1.1 405 Request method 'PUT' not supported
< Date: Fri, 05 Feb 2016 15:36:33 GMT
< Allow: GET
< Content-Length: 0
< Server: Jetty(9.2.14.v20151106)
<
```
and it looks like the request is mapped correctly:
`2016-02-05 10:33:19.275  INFO 9604 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/components/{componentName}/state],methods=[PUT],consumes=[text/plain],produces=[application/json || text/plain]}" onto public java.lang.String com.vmturbo.components.ComponentController.putComponentStatus(java.lang.String,com.vmturbo.components.ComponentState)`

Here's the method:
```
    @RequestMapping(path = "/{componentName}/state",
            method = RequestMethod.PUT,
            consumes = {MediaType.TEXT_PLAIN_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.TEXT_PLAIN_VALUE})
    @ResponseBody
    public String putComponentStatus(@PathVariable String componentName,
                                   @RequestBody ComponentState newState) {
        IComponentManager.ComponentHandle componentHandle = componentManager.getComponent(componentName);
        switch(newState) {
            case STARTING:
                componentHandle.start();
                break;
            case STOPPING:
                componentHandle.stop();
                break;
            case PAUSED:
                componentHandle.pause();
                break;
            case RUNNING:
                componentHandle.resume();
                break;
        }
        return "";
    }
```

I've been searching all morning to no avail.

Thanks in advance, I know this is an old post.

**Comment by broadbear** [comment]
405 can mean your method is not mapped correctly. At first glance it looks like your request mapping is:

`
/components/{component name}/state
`

...while your curl statement sends a request to:

`
/components/vmax
`

You may also have a mapping to /components/{component name} and only a GET method defined.

Try to add 'state' to the path in your curl statement:

`
/components/vmax/state
`

...and see if that fixes the problem.

**Comment by marklaff** [comment]
@broadbear you're right, of course. Simple mistake on my part. I was copy/pasting an old curl request against a revised RequestMapping.
