### ISSUE TITLE
Adapt to and from Mono when exposing endpoint operations over HTTP

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10112]
When a blocking operation is exposed using WebFlux, the invocation of the operation must be adapted to return a Mono by dispatching it in a separate thread.

When a non-blocking operation (one that returns Mono) is exposed using Jersey, the operation must be adapted to return the Mono's result by blocking until it's available. Spring MVC provides native support for Mono so it does not require such an adapter.

**Comment by snicoll** [comment]
This code could be useful when invoking regular `HealthIndicator` as part of the `ReactiveHealthIndicator` infrastructure. I don't know if that makes sense to share it though.

**Comment by wilkinsona** [comment]
I suspect that it won't as there's not really that much of it. We can refactor it to make it common if it does make sense to do so.

**Comment by bclozel** [comment]
Good idea!
It will probably require something like `subscribeOn(Schedulers.elastic())` since those cases should not be CPU-bound, but IO-bound (unless some endpoints operations are performing expensive calculations?).

If we'd like to support more than `Mono` for those cases, we can always rely on a `ReactiveAdapterRegistry` instance for that (provided in spring-core).

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @bclozel. I tried using `subscribeOn` but couldn't get it to work for the cases where the endpoint returns `null`. I resorted to using `Mono.create` and calling completing the sink instead.

**Comment by philwebb** [comment]
@wilkinsona  I changed `bodyConverters` in `JerseyEndpointResourceFactory` to an immutable list and discovered it wasn't being used. Can you check that commit 9cb0a81e5025520ffaaa947d0b35ff4b6008640a is OK if you get a chance?

**Comment by wilkinsona** [comment]
Wow, two days back and apparently I already need another holiday 🙄 . Thanks for spotting that, it looks good to me.
