### ISSUE TITLE
Spring boot 5.0.0.RC3  doesn't work and end up with "No ServletContext" error on a Bean Instanciation

### ISSUE THREAD

**Issue by LouisSDev** [spring-projects/spring-boot#10115]
Hello, While migrating my application from Spring 4.3 latest release to Spring 5.0.0.RC3, I came through a strange problem. Altough I can run mvn test and obtain a BUILD SUCCESS on all of my hundred of tests, the Spring boot itself doesn't seems to work and while creating Spring context and trying to initiate some beans (RessourceHandlerMapping bean to be precise) gives this strange error stipulating that the ServletContext is not set and therefore the bean cannot be instanciated. I've post a detailed explanation on stackoverflow but didn't get any answer yet. So far I've tried using earlier releases, as well as BUILD-SNAPSHOT releases, I've also tried to activate the debug and that helped me to see what happened during the auto configuration of the process but this didn't helped me much as I was not aware of 95% of the classes named in this... I'm assuming the problem comes from my pom.xml that causes some dependency problem somewhere but I'm really not sure about anything as I am quite new to Spring.

Please find below the link to my stackoverflow post, thanks!

https://stackoverflow.com/questions/45944388/spring-5-0-0-m3-error-calling-applicationeventlistener-no-servletcontext-set

**Comment by snicoll** [comment]
Thanks for getting in touch, but we don't use the issue tracker for questions. Let's keep the conversation there.
