### ISSUE TITLE
Proxying static methods does not work OOB as of Spring Boot 2

### ISSUE THREAD

**Issue by balbler** [spring-projects/spring-boot#10110]
Dear Team,
as per the M1 release notes Spring Boot 2.0 has switched to using CGLib Proxies.
Since the CGLib proxies don't support proxying static methods, to me it seems breaks some implementation.
One Sample are all implementations that extend AbstractRememberMeServices from spring security (one example is jhipster, i also think this direct spring security implementation is affected https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.html)
The issues occurs around the onSuccess Method..

We were able to resolve the issue in our project by switching back to the JDK proxies.

What is the general suggestion around this from the spring boot team? Can this be fixed without globally turning of the CGLIb proxies? Or do i completely miss something

**Comment by balbler** [comment]
I have a small sample project based on the jhipster sample app if that helps

**Comment by snicoll** [comment]
A minimal sample is always helpful. Can you please share one without jhipster?

**Comment by snicoll** [comment]
See also https://github.com/spring-projects/spring-boot/issues/5423#issuecomment-290216052

**Comment by balbler** [comment]
@snicoll sorry, was very busy the last days. Will try to put one together without jhipster the next 2 days

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
