### ISSUE TITLE
Make base path configurable for WebFlux applications

### ISSUE THREAD

**Issue by bonigarcia** [spring-projects/spring-boot#10129]
So far (Spring Boot 1.5.4-RELEASE) I were using the configuration key `server.contextPath` of  `application.properties` to change the context path of a Spring Boot based web application, as follows:

    server.contextPath=/mypath

Unfortunately, this has stopped working when upgrading to Spring Boot 2.0.0-M3.

Is this a bug or this feature has changed in Spring Boot 2?

**Comment by wilkinsona** [comment]
Configuring the context path is servlet-specific. To reflect that fact and avoid confusion when using WebFlux, the configuration property was renamed to `server.servlet.context-path`. That should have been mentioned in the M1 release notes but it looked like we missed it.

**Comment by wilkinsona** [comment]
These are the changes that need to be described in the release notes: https://github.com/spring-projects/spring-boot/commit/12d883f6b9b022d305c7303871a44e4d6bd4fae4

**Comment by snicoll** [comment]
@bonigarcia which IIDE are you using. As of M4, it should show up in red

**Comment by wilkinsona** [comment]
I've updated the release notes to [describe the changes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#servlet-specific-server-properties). Thanks for bringing this to our attention, @bonigarcia.

**Comment by bonigarcia** [comment]
Thank you very much, using `server.servlet.context-path` my app is working again as expected.

@snicoll I am using Eclipse 4.7 (Oxygen), but without any specific Spring plugin (I think that way is impossible for the IDE to warn me about the problem)

Keep up the great work!

**Comment by danieldelatorre** [comment]
Hello guys,

I am using spring boot 2.0.0.M4/7 with the server.servlet.context-path=/mypath but it does not work. I have to put the url with the path to reach the rest endpoints. 
Could you help with this?

**Comment by danieldelatorre** [comment]
Hello guys,

I am using spring boot 2.0.0.M4/7 and I used the server.servlet.context-path=/mypath but it dpes not work. I can reach my rest endpoints using the url without the path.
Can you help me with this?

**Comment by danieldelatorre** [comment]
Also I want to add that I am using webflux, maybe webflux does not support that property.

**Comment by philwebb** [comment]
@danieldelatorre That property is only for servlet based deployments. I don't think we have an equivalent for webflux (do we @bclozel?).

**Comment by bclozel** [comment]
In Spring Framework, there are several ways to deal with context paths:

* deploying your WebFlux app as a war in a Servlet container and configure the Servlet to a particular context path. Spring Boot does not support WebFlux war deployment.
* Spring Framework provides a `ContextPathCompositeHandler` that allows delegating to multiple `HttpHandler` instances depending on the path. With `@EnableWebFlux`, you can provide both WebFlux annotation and WebFlux functional handlers and they'll be mapped accordingly.

While we could leverage that last bit and map the whole WebFlux application to a particular context, I don't see the real added value since we don't deploy to war nor map multiple `HttpHandler` instances. We'd just have everything mapped under one path.

**Comment by danieldelatorre** [comment]
ok thanks for the quick answer guys.
One last question if I add to the pom.xml the spring-boot-starter-webflux and the spring-boot-starter-web the annotation works. If I add both annotations how can my service can be impacted?

**Comment by danieldelatorre** [comment]
ok thanks for the quick answer guys.
One last question if I add to the pom.xml the spring-boot-starter-webflux and the spring-boot-starter-web the server.servlet.context-path works. If I add both references in the pom how can my service be impacted?

**Comment by bclozel** [comment]
If you add both starters, your application is a Spring MVC app. Note that as of Spring Framework 5, Spring MVC knows how to handle a few cases with `Flux` at the controller level.

**Comment by danieldelatorre** [comment]
But if my application is using Flux and Mono in the RestController, it will continue using non blocking calls right?

**Comment by bclozel** [comment]
Short answer - asynchronous: yes, non-blocking: no.
If you want the full story about why that is, we've just released the SpringOnePlatform talks and [one of them is super relevant to your question](https://content.pivotal.io/springone-platform-2017/servlet-or-reactive-stacks-the-choice-is-yours-oh-no-the-choice-is-mine-rossen-stoyanchev).

**Comment by danieldelatorre** [comment]
well thanks so much for your help guys

**Comment by remesh22** [comment]
server.servlet.context-path only works with below dependency:
               `<dependency>`
                        `<groupId>org.springframework.boot</groupId>`
			`<artifactId>spring-boot-starter-web</artifactId>`
		`</dependency>`
Since webflux is not supporting this property, i cannot provide context path for my tomcat webflux application. Because of this all my actuator endpoints are sitting at context root '/'. I don't want to deploy my application as a WAR file. Is there a way to support both my endpoints and actuator endpoints at the same context root rather than the default context root of '/' in webflux.

**Comment by adsanche** [comment]
Here's what I'm doing to set the context path with Reactive Tomcat:

```
@Configuration
public class TomcatReactiveWebServerConfig extends TomcatReactiveWebServerFactory {

    @Value("${server.context-path}")
    private String contextPath;

    /**
     * {@inheritDoc}
     */
    @Override
    protected void configureContext(final Context context) {

        super.configureContext(context);

        if (StringUtils.isNotBlank(this.contextPath)) {
            context.setPath(this.contextPath);
        }
    }
}
```

**Comment by bclozel** [comment]
@denisw Please ask questions on StackOverflow; if you believe this is a bug, you can create a new issue with a repro project we clone and run. Thanks!

**Comment by denisw** [comment]
Sorry, maybe I wasn't clear. I commented here because I believe this to be a use case that makes the context path feature useful even outside of servlets, and perhaps should not be dismissed as done in #14082.

**Comment by bclozel** [comment]
@denisw from your description, it doesn't sound like a context path feature but rather something like X-Forwarded-Path support.

**Comment by denisw** [comment]
@bclozel You are right, I was able to cover my use case by:

* Let the proxy add an `X-Forwarded-Predix: /api` header to requests
* Defining a [ForwardedHeaderTransformer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/server/adapter/ForwardedHeaderTransformer.html) bean named `forwardedHeaderTransformer`, which is automatically picked up by Webflux

**Comment by Numbernick** [comment]
So to be honest we have the same problem. Our infrastructure is homogenous with servlet and webflux components. Our guideline for our ingres is to route to a specific context path. Sure I can workarround this with annotating ALL my Controllers with this prefix. An equivalent mechanism for reactive would be a good help for migrating. (Also this option exists for webflux for the actuator endpoint -> management.endpoints.web.base-path)

**Comment by zhouchong90** [comment]
@denisw We have the same problem as you do using webflux with Kubernetes. Could you help to elaborate on your solution? Specifically how you configured the  ForwardedHeaderTransformer bean and how you added the X-Forwarded-Predix: /api header. I'd appreciate it if you could share your ingress yaml.

**Comment by philwebb** [comment]
Reopening so we can investigate how difficult this will be.

**Comment by pgerhard** [comment]
In order to use easily use Webflux in production we would also require this feature. All our backends are exposed to the outside world via a proxy and we route requests to the backends based on the requested URL. 
While it is possible to strip the prefix in the proxy, this results in the API endpoints changing between local development deployments and dev / staging / production deployments which needlessly complicates things for DevOps

**Comment by FearlessHyena** [comment]
Same here it would be really great to have this option

**Comment by pluttrell** [comment]
Is this a safe and reliable work around until this feature gets implemented?

```
@Bean
@ConditionalOnProperty("server.servlet.context-path")
@Order(Ordered.HIGHEST_PRECEDENCE)
public WebFilter contextPathWebFilter(ServerProperties serverProperties) {

  String contextPath = serverProperties.getServlet().getContextPath();

  return (exchange, chain) -> {

    ServerHttpRequest request = exchange.getRequest();
    String requestPath = request.getURI().getPath();

    if (requestPath.startsWith(contextPath + "/") || requestPath.equals(contextPath)) {

      return
          chain.filter(
              exchange.mutate()
                  .request(request.mutate().contextPath(contextPath).build())
                  .build()
          );

    } else {
      throw new ResponseStatusException(HttpStatus.NOT_FOUND);
    }

  };
    
}
```
Based on https://stackoverflow.com/a/50998253/1930325.

**Comment by pgerhard** [comment]
@pluttrell i did something very similar to yours and it worked fine until i started using spring security. my filter was being run the security chain had been finished processing which resulted in all sorts of funny errors. Most notably I ended up having issues with the redirection behaviour implemented by the security filter chain. 
Thats why I ended up including the filter at the very beginning of my security filter chain, instead of defining it as a "normal" filter bean

**Comment by springmarker** [comment]
We really need it.

**Comment by huodon** [comment]
We really need it 2.

**Comment by philwebb** [comment]
@springmarker @huodon Please use the "👍" reaction button on the initial comment if you're interested in the feature. Adding additional comments creates a lot of noise and makes it harder to follow the discussion.

**Comment by ankit-rai** [comment]
Is this feature released.

**Comment by Prigovor** [comment]
Hello. How to apply it to functional routers?

**Comment by bclozel** [comment]
@Prigovor it should apply to all WebFlux handlers. If this is not the case, please create a new issue with a project reproducing the problem. Thanks!

**Comment by Prigovor** [comment]
Thanks for instant reply. Will try to play with it else... ))

**Comment by codependent** [comment]
@bclozel Will there be a 2.2.7 version before 2.3.0? In that case could this be backported to the 2.2.x branch?

**Comment by wilkinsona** [comment]
@codependent Sorry, but we don't backport enhancements to maintenance branches. You'll have to wait for 2.3.0 (due next month) to pick this one up.

**Comment by lfcortes12** [comment]
@bclozel I've created https://github.com/spring-projects/spring-boot/issues/22510 because it did not work for me.

Thanks
