### ISSUE TITLE
Update documentation for liquibase namespace change

### ISSUE THREAD

**Issue by httpdigest** [spring-projects/spring-boot#10139]
Spring Version: 5.0.0.BUILD-SNAPSHOT
Spring Boot Version: 2.0.0.BUILD-SNAPSHOT

It seems that the liquibase.change-log property is not being recognized anymore in the current Spring Boot Snapshot (as of the creation date of this issue).

I am getting the error:
`Caused by: java.lang.IllegalStateException: Cannot find changelog location: class path resource [db/changelog/db.changelog-master.yaml] (please add changelog or check your Liquibase configuration)`

With Spring Boot version 2.0.0.M3 everything works smoothly and the correct liquibase changelog file is being used as defined in the application.yml using the property liquibase.change-log.

**Comment by snicoll** [comment]
Do you use an IDE? If so which one and which version? those properties should show up in red if it supports the error level metadata.

If you are using SNAPSHOTs please dig a bit before raising an issue: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M4-Release-Notes#database-migration

**Comment by httpdigest** [comment]
Thanks for the info!

**Comment by httpdigest** [comment]
I was looking only at the documentation: https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#howto-execute-liquibase-database-migrations-on-startup

**Comment by snicoll** [comment]
Thanks for the feedback. Let's use this issue to fix that piece of the doc.
