### ISSUE TITLE
optional=true dependencies should be excluded by spring-boot:repackage

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-boot#10137]
For example:

```
[INFO] |  +- org.apache.wicket:wicket-ioc:jar:8.0.0-M7:compile
[INFO] |  |  +- cglib:cglib:jar:3.2.5:compile
[INFO] |  |  |  \- org.apache.ant:ant:jar:1.9.6:compile <-- this is optional dependency of cglib
[INFO] |  |  |     \- org.apache.ant:ant-launcher:jar:1.9.6:compile
```

As of Boot 1.5.7, the ant.jar is packaged. The correct behavior is that optional dependencies should be excluded, unless specifically added by the project itself. From https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html:

> Optional dependencies - If project Y depends on project Z, the owner of project Y can mark project Z as an optional dependency, using the "optional" element. When project X depends on project Y, **X will depend only on Y and not on Y's optional dependency Z**. The owner of project X may then explicitly add a dependency on Z, at her option. (**It may be helpful to think of optional dependencies as "excluded by default.**")

Related to #649, #650, #8005

**Comment by wilkinsona** [comment]
CGLib's Ant dependency is not optional. Here's its declaration in CGLib 3.2.5's pom:

```
<dependency>
    <groupId>org.apache.ant</groupId>
    <artifactId>ant</artifactId>
</dependency>
```

It is marked as optional in CGLib dependency management in their parent, but that has no effect. That's standard Maven behaviour and has nothing to do with Spring Boot.

**Comment by ceefour** [comment]
Thanks @wilkinsona for clarification. That means repackage behavior is as intended and cglib pom is buggy.
