### ISSUE TITLE
Upgrade dependency exclusions and enforcer rules following upgrade to Tomcat 8.5.24 with Java EE API bundling changes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10133]
As of Tomcat 8.5.21, [Java EE APIs will no longer be bundled in the tomcat-embedded-core jar](https://bz.apache.org/bugzilla/show_bug.cgi?id=61439). Upgrading should give us control over exactly which versions of the APIs are used as well as allowing us to tighten up some rules about duplicates classes in our starters.

**Comment by wilkinsona** [comment]
We should be able to revert 5d67ae4d819e1a7bcc9ad13711d904c55882318c as part of fixing this.

**Comment by wilkinsona** [comment]
The upgrade itself as being tracked by #10395.

**Comment by wilkinsona** [comment]
This hasn't been fixed as proposed. The proposal was to "stop shipping JavaEE APIs and rather rely on official JAR(s)". Instead, `tomcat-embedded-core` now depends on (`tomcat-annotations-api`) that contains the following classes:

- `javax.annotation.Generated`
- `javax.annotation.ManagedBean`
- `javax.annotation.PostConstruct`
- `javax.annotation.PreDestroy`
- `javax.annotation.Priority`
- `javax.annotation.Resource$AuthenticationType`
- `javax.annotation.Resource`
- `javax.annotation.Resources`
- `javax.annotation.security.DeclareRoles`
- `javax.annotation.security.DenyAll`
- `javax.annotation.security.PermitAll`
- `javax.annotation.security.RolesAllowed`
- `javax.annotation.security.RunAs`
- `javax.annotation.sql.DataSourceDefinition`
- `javax.annotation.sql.DataSourceDefinitions`
- `javax.ejb.EJB`
- `javax.ejb.EJBs`
- `javax.persistence.PersistenceContext`
- `javax.persistence.PersistenceContextType`
- `javax.persistence.PersistenceContexts`
- `javax.persistence.PersistenceProperty`
- `javax.persistence.PersistenceUnit`
- `javax.persistence.PersistenceUnits`
- `javax.persistence.SynchronizationType`
- `javax.xml.ws.WebServiceRef`
- `javax.xml.ws.WebServiceRefs`

Unfortunately, this is too coarsely grained to be useful to us as it contains a combination of various different Java EE API jars.

@markt-asf Would it be possible to take another look at this so that Tomcat uses official Java EE spec jars rather than `tomcat-annotations-api`?

**Comment by markt-asf** [comment]
If you don't want the Tomcat dependency can you not exclude it and depend on the official Java EE JARs you prefer to depend on?

**Comment by wilkinsona** [comment]
@markt-asf How does Tomcat react to the absence of some of those classes? For example, the two EJB-related classes are a small subset of the classes in `javax.ejb:javax.ejb-api`. In a vanilla Boot app we don't care about EJBs so it would be nice if we could just exclude those classes altogether. The same goes for that JPA and JAX-WS classes too.

**Comment by markt-asf** [comment]
If the web application is marked as meta-data complete, it will be fine. If it isn't, the web application will fail to start. My working assumption is that that would be a problem.

I've re-opened the bugzilla issue and I've set what I think is a better solution. You'd still need to exclude the annotations-api.jar but issues with the other classes should go away.

**Comment by brenuart** [comment]
Can't we safely exclude `tomcat-annotations-api` from `tomcat-embed-core` dependencies ?

AFAIK, Tomcat doesn't need those classes to start. And as some mentioned in this post, most of these annotations are either not required by standard SpringBoot application, or are provided by other librairies and/or the JVM:
- Most `javax.annotation` are provided by the JVM
- `javax.persistence` comes with Hibernate (by means of another transitive dependency)
- `javax.ejb` is likely to be of no use in SpringBoot app
- `javax.xml.ws` is provided by the JVM
- `javax.annotation.security` - are they pulled by SpringSecurity ?

**Comment by wilkinsona** [comment]
> AFAIK, Tomcat doesn't need those classes to start.

It does per @markt-asf in his comment [above](https://github.com/spring-projects/spring-boot/issues/10133#issuecomment-333130697):

> If the web application is marked as meta-data complete, it will be fine. If it isn't, the web application will fail to start. My working assumption is that that would be a problem.

We don't do anything in Boot to mark the application as metadata complete but perhaps we should.

@markt-asf I looked at the Bugzilla issue and couldn't find the better solution. Can you point me to it please?

**Comment by markt-asf** [comment]
See https://bz.apache.org/bugzilla/show_bug.cgi?id=61439#c2
annotations-api.jar now only contains javax.annotations.* (i.e. Java Common Annotations API)
It is now possible to exclude that JAR and provide those classes from an alternative source if you wish (Tomcat does need those classes so they need to be provided from somwhere).
Tomcat no longer requires javax.ejb.*, javax.persistence.* or javax.xml.ws.* - it will use them if present but does not require them nor provide them.
