### ISSUE TITLE
AbstractFilterRegistrationBean should check isEnabled earlier

### ISSUE THREAD

**Issue by DerThanne** [spring-projects/spring-boot#10148]
in `org.springframework.boot.web.servlet.AbstractFilterRegistrationBean`, `onStartup` at first a check is done if a filter has been set.

But if i want to disable the filter, why should i create one (which can be an extensive process) and add it to the RegistrationBean, just to never use it.

Code in `onStartup` should be changed from

```
Filter filter = getFilter();
Assert.notNull(filter, "Filter must not be null");
String name = getOrDeduceName(filter);
if (!isEnabled()) { 
    this.logger.info("Filter " + name + " was not registered (disabled)");
    return;
}
```

To

```
if (!isEnabled()) {
    this.logger.info("Filter " + getOrDeduceName( null )+ " was not registered (disabled)");
    return;
}
Filter filter = getFilter();
Assert.notNull(filter, "Filter must not be null");
```

**Comment by Shadi-A** [comment]
Hello, I've created a pull request here that will fix this here:
https://github.com/spring-projects/spring-boot/pull/10152

**Comment by wilkinsona** [comment]
@DerThanne Can you explain how you're using the registration bean please?

Using filter registration bean to disable a filter is relatively unusual. As [described in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-disable-registration-of-a-servlet-or-filter), that's typically for disabling a filter that something else has already created and you'd inject it into the registration's bean method:

```java
@Bean
public FilterRegistrationBean registration(MyFilter filter) {
    FilterRegistrationBean registration = new FilterRegistrationBean(filter);
    registration.setEnabled(false);
    return registration;
}
```

If you're in a position to be create and register the filter, then I would just not do either if you did not want the filter to be registered.

**Comment by DerThanne** [comment]
Let's say that i have to deploy an application to different environments and in a specific environment I need a special filter to preprocess all my HTTP request. In my case I need OAuth security on my production environment and also on the test environment, but on my dev environment it is not useful. That's why i thought that setEnabled = false will just not register the filter. Because of the mentioned behaviour this is not possbible. 
I could use a NOOP Filter instead, but it simply does not feel right to register a piece of code of which you know will just do nothing but forward the request down the chain.
Here is my code that uses the FilterRegistrationBean. You can also see my workaround for the problem:

```
    @Bean
    public FilterRegistrationBean securityFilterRegistration() throws Exception {
    	boolean enabled = "true".equalsIgnoreCase( oAuthEnabled );
    	FilterRegistrationBean registration = new FilterRegistrationBean() {

			@Override
			public void onStartup(ServletContext servletContext) throws ServletException {
				if( !isEnabled() ) {
					LOG.info("Filter " + getOrDeduceName( null ) + " was not registered (disabled)");
					return;
				}
				super.onStartup(servletContext);
			}
    		
    	};  
    	
    	if( enabled ) {
	    	HttpClient client = HttpClientFactory.buildSSLVerificationDisabled();
	    	AuthorizationService service = new HttpClientAuthorizationService( client ).withOAuthTokenUrl( oAuthTokenUrl );
	    	APISecurityFilter filter = new APISecurityFilter( service );
	    	registration.setFilter( filter );
    	}

    	String[] mappings = StringUtils.split( oAuthMappings, ',' );
    	if( ArrayUtils.isEmpty( mappings ) ) {
    		throw new IllegalArgumentException( "APISecurityFilter not mapped to urls!" );
    	}
    	registration.addUrlPatterns( mappings );
    	registration.setName( "APISecurityFilter" );
    	registration.setEnabled( enabled );
    	return registration;
    }    
```

**Comment by wilkinsona** [comment]
@DerThanne Thanks.

You could simplify that logic by using `@ConditionalOnProperty` on the `@Bean` method for a property that maps to `oAuthEnabled`. Something like this:

```java
@Bean
@ConditionalOnProperty(prefix="com.example.security", name="oauth-enabled")
public FilterRegistrationBean securityFilterRegistration() throws Exception {
    HttpClient client = HttpClientFactory.buildSSLVerificationDisabled();
    AuthorizationService service = new HttpClientAuthorizationService( client ).withOAuthTokenUrl( oAuthTokenUrl );
    APISecurityFilter filter = new APISecurityFilter( service );
    FilterRegistrationBean registration = new FilterRegistrationBean(filter);
    String[] mappings = StringUtils.split( oAuthMappings, ',' );
    if( ArrayUtils.isEmpty( mappings ) ) {
        throw new IllegalArgumentException( "APISecurityFilter not mapped to urls!" );
    }
    registration.addUrlPatterns( mappings );
    registration.setName( "APISecurityFilter" );
    return registration;
}
```

With this approach `securityFilterRegistration` will never be called and the `FilterRegistrationBean` it creates will never be added to the application context.

In my opinion this approach is better than the proposed reordering of the logic in `FilterRegistrationBean` which will have an adverse effect on the info message that it logs.

**Comment by DerThanne** [comment]
Well, thanks Andy. Thats a need approach! In that case I am completely with you, that the change should not be made.
