### ISSUE TITLE
Null entry for LocalDateTime

### ISSUE THREAD

**Issue by marccollin** [spring-projects/spring-boot#10147]
With spring boot 2.0 and java 8, Jsr310Converters is automaticaly used when we have in the class path.

I have some field who are localdatetime.

In Db for these fields sometime value is null;

Jsr310Converters don't seem to support null value anymore.

Is there any annotation we need to put on localdate, localdatetime to avoid Jsr310Converters been called if the value is null or something like that to avoid null pointer exception?

**Comment by snicoll** [comment]
Assuming you are mentioning Spring Data's `Jsr310Converters` please create an issue in [their tracker](https://jira.spring.io/browse/DATACMNS)

Please provide the full stacktrace of that `NullPointerException`. A sample would be ideal.
