### ISSUE TITLE
ElasticsearchDataAutoConfiguration.elasticsearchTemplate does not back off when beans it needs are missing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10143]
Beans of two different types are required:

- `org.elasticsearch.client.Client`
- `org.springframework.data.elasticsearch.core.convert.ElasticsearchConverter`

If either of these is missing, the auto-configuration will fail rather than backing off.

**Comment by snicoll** [comment]
`ElasticsearchConverter` is provided by that very same auto-config so a condition on the `Client` should be enough.
