### ISSUE TITLE
Unable to kill process

### ISSUE THREAD

**Issue by ricardobsp** [spring-projects/spring-boot#10159]
https://github.com/spring-projects/spring-boot/blob/9242def4c0753278599614d22e07c076f5e246ec/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L91

This conditional is always 0 in my server (Amazon Linux 2012.03). As a consequence, I cannot stop the service because the script uses this conditional to check if the proccess has already stopped. After a timeout, I get a message "Unable to kill process <PID>", but the proccess has already been killed.

There is other ways to check if proccess is running? I think this method is not reliable, Maybe check if the PID exists in /proc?

**Comment by wilkinsona** [comment]
Sorry to question your analysis, but are you certain that `ps -p` for a PID that does not exist is returning `0`? We know from [comments on other issues](https://github.com/spring-projects/spring-boot/issues/4524#issuecomment-160148261) that the launch script has been used successfully on Amazon Linux.

**Comment by wilkinsona** [comment]
Also 2012.03 is five and a half years old now and even predates Spring Boot. Is there any reason why you can't use a more up-to-date version?

**Comment by ricardobsp** [comment]
Yes, I'm certain. But you're right, this version is too old. I tested on a instance with a more recent Amazon Linux (2017.03) and worked as expected. Thank you, I'll close this issue.
