### ISSUE TITLE
spring-boot-dependencies: declare org.synchronoss.cloud:nio-multipart-parser and its version (1.1.0)

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#10158]
Spring WebFlux is using org.synchronoss.cloud:nio-multipart-parser for multipart/form-data. Please see https://github.com/spring-projects/spring-framework/blob/master/spring-web/spring-web.gradle#L31 and https://github.com/spring-projects/spring-framework/blob/v5.0.0.RC3/build.gradle#L80.
It would be nice if you could provide it also in the BOM mechanism of Spring Boot.

**Comment by wilkinsona** [comment]
It's already there as it was added in [this commit](https://github.com/spring-projects/spring-boot/commit/8198b87538b4485511112c9b3996b244140207d9#diff-083b496f7d7090ebebfb261636fbe139). Please take a moment to check the latest milestone/snapshots before raising an issue.
