### ISSUE TITLE
Enable /info and /status by default

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#10161]
Recent changes in 2.0 snapshots have made Actuator endpoints an "opt-in" feature (you have to set a flag `endpoints.default.web.enabled`). It's good that there is a single flag (as well as the individual flags for each endpoint, carried over from 1.5), but the default value seems wrong. My understanding is that this was done to facilitate removing the "sensitive" flag which complicates security configuration. That concept (sensitivity) is still kind of embodied in the opinion we express by splitting /health into /health (secure) and /status (not secure), but we seem to have failed to follow through and express the opinion in a form that users will encounter by default.

So maybe a compromise would be to enable /status and /info by default but not the others? In 1.5 you had to set a flag to get unsecure versions of the other endpoints, but as soon as Spring Security was on the classpath, they were available but secure. That seems like the right defaults to me.

**Comment by wilkinsona** [comment]
Thinking about this issue has made us realise that the current `enabledByDefault` attribute on `@Endpoint` is probably broken. It's certainly confusing.

As things stand setting `enabledByDefault = true` when `endpoints.default.web.enabled` has been set to `false` leaves the endpoint disabled. Conversely, setting `enabledByDefault = false` when `endpoints.default.web.enabled` has been set to `true` does disable the endpoint.

We need to rework the behaviour to achieve three goals:

1. An endpoint can indicate that it should be disabled unless that specific endpoint is explicitly enabled
2. An endpoint can indicate that it should be enabled unless that specific endpoint is explicitly disabled
3. An endpoint can indicate that it doesn't have an opinion and its enablement should be controlled "globally"

The shutdown endpoint would use 1. The proposal in this issue would mean that the status and info endpoints use 2. All other endpoints would use 3.

I don't think we should allow an endpoint to offer different default enablement per exposure technology as the combination of configuration options would be too large. Instead, I think we should change `enabledByDefault` to use an `EndpointEnablement` enum with three values that map to the three goals listed above:

1. `NO`
2. `YES`
3. `NEUTRAL`

When an endpoint uses `NO` it will only be enabled if `endpoint.<name>.enabled`, `endpoint.<name>.jmx.enabled` or `endpoint.<name>.web.enabled` is `true`.

When an endpoint uses `YES` it will be enabled unless `endpoint.<name>.enabled`, `endpoint.<name>.jmx.enabled` or `endpoint.<name>.web.enabled` is `false`.

When an endpoint uses `NEUTRAL` it will be enabled if `endpoint.default.enabled`, `endpoint.default.jmx.enabled` or `endpoint.default.web.enabled` is `true` and `endpoint.<name>.enabled`, `endpoint.<name>.jmx.enabled` or `endpoint.<name>.web.enabled` has not been set to `false`.

**Comment by mbhave** [comment]
@wilkinsona for the security use-case, does an endpoint indicating that it's enabled automatically qualify as an insecure endpoint? Or did we discuss having something on the endpoint that indicates that it is sensitive?

**Comment by wilkinsona** [comment]
I think we were decided to go with a `sensitive` attribute on `@Endpoint` that would default to `true` and could be configured using `endpoint.<name>.sensitive`.

**Comment by snicoll** [comment]
We are. Is it part of this issue though ?

**Comment by wilkinsona** [comment]
No, I don't think so

**Comment by snicoll** [comment]
Cool. So we need an issue for that then?
