### ISSUE TITLE
JSON starter should include spring-web

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#10167]
The JSON starter currently pulls Jackson into the classpath but does not pull in `spring-web` which contains `Jackson2ObjectMapperBuilder` that's in turn required for auto-configuration of Jackson.

**Comment by olivergierke** [comment]
Related to #10166.

**Comment by snicoll** [comment]
Uh? What currently? Master does it as far as I am aware.

**Comment by wilkinsona** [comment]
Sorry, that's my mistake. @olivergierke and I were discussing this on Slack and I'd forgotten that we'd fixed this for M4.

Duplicate of #10031.
