### ISSUE TITLE
Try to drop EndpointExposure

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10176]
It might be possible to drop the `EndpointExposure` enum and replace it with a class. Currently it's somewhat limiting in that additional items can't be added easily.

We might be able to use `Class<? extends AnnotationEndpointDiscoverer>`.

**Comment by philwebb** [comment]
The enum really reflects reality. For example, we need to generate `*.jmx` and `*.web` property meta-data. We probably shouldn't try to over complicate things.

**Comment by philwebb** [comment]
Actually, now the package restructure is in I would like to reconsider our options. Something doesn't feel quite right about `EndpointExposure`, especially as it's really only used to limit a couple of endpoints.

The `jmx` and `web` meta-data might also be worth a revisit. Enabling on a per technology basis is adding complexity. Perhaps we can just get away with a single `enabled`?

**Comment by wilkinsona** [comment]
> Perhaps we can just get away with a single enabled?

The need for per-technology enablement is driven by the shutdown endpoint. For an app that doesn't need HTTP security, I think it's useful to be able to only expose the shutdown endpoint over JMX otherwise anyone with HTTP access to the app could shut it down.

**Comment by snicoll** [comment]
I second that and disagree with the complex argument. Things are located in a single class and the contract is isolated. I agree this particular class is a bit complex but that doesn't leak elsewhere.

**Comment by philwebb** [comment]
I'll try to spike something then we can make a decision.

**Comment by philwebb** [comment]
Still a way to go, but I've started experimenting [here](https://github.com/philwebb/spring-boot/tree/gh-10176).

Trying an annotation approach for both specializations and extensions:

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@EndpointExtension(filter = WebEndpointFilter.class) // Extension that only applies when the filter matches
public @interface EndpointWebExtension {

	@AliasFor(annotation = EndpointExtension.class)
	Class<?> endpoint();

}
```

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Endpoint
@FilteredEndpoint(WebEndpointFilter.class) // Endpoint only discovered when the filter matches
public @interface WebEndpoint {

	@AliasFor(annotation = Endpoint.class)
	String id();

	@AliasFor(annotation = Endpoint.class)
	boolean enableByDefault() default true;

}
```
