### ISSUE TITLE
Referencing an @ConfigurationProperties annotated bean from an @ConditionalOnExpression @Bean method prevents configuration bean from being processed by the ConfigurationPropertiesBindingPostProcessor

### ISSUE THREAD

**Issue by jkuipers** [spring-projects/spring-boot#10180]
I'm not sure if what I'm doing is supposed to work (in which case this is a bug report), or if this behavior is expected, but here we go.
In one of my projects I have a custom `@ConfigurationProperties` component-scanned bean which contains some names for RabbitMQ exchanges and queues. Depending on the configured value for a return address (used with an `@SendTo` annotation) I'd like to conditionally define an AMQP exchange. I thought I was being really clever when I wrote the following bean definition:

```java
    /**
     * Defines an {@link Exchange} if the ssp reply address contains a dedicated exchange name.
     * If the reply address contains a routing key as well, this will be a {@link TopicExchange},
     * otherwise a {@link FanoutExchange} is created.
     */
    @Bean
    @ConditionalOnExpression("@amqpProperties.sspReplyAddress.indexOf('/') > 0")
    Exchange sspReplyExchange() {
        String replyAddress = amqpProperties.getSspReplyAddress();
        int slash = replyAddress.indexOf('/');
        String exchangeName = replyAddress.substring(0, slash);
        if (replyAddress.endsWith("/")) { // no routing key
            return new FanoutExchange(exchangeName);
        }
        return new TopicExchange(exchangeName);
    }
```

However, it turns out that using an `@ConditionalExpression` whose SpEL expression references a configuration properties bean triggers some premature initialization of that bean: it will be created, but because it happens too soon it won't be handled by the `ConfigurationPropertiesBindingPostProcessor`. That means I'm never seeing my configured property values; not only here, but everywhere that I'm using the `amqpProperties` bean because the (unbound) singleton is stored in the singleton factory cache.

I've attached a small sample project to demonstrate the issue. I'm wondering if the observed behavior should be considered a bug in Spring Boot or an abuse of Spring Boot on my behalf ;)

[configpropstest.zip](https://github.com/spring-projects/spring-boot/files/1281417/configpropstest.zip)

**Comment by snicoll** [comment]
I'd certain consider it an abuse of `@ConditionalOnExpression`. IMO, such condition should be written in plain. It's a bit more code but at least you can test the code in isolation and provider an explicit reason when the condition does not match.

Using a bean as part of the conditions is a bit extreme (as conditions happen before beans are created) so there's a design problem in doing that. I am not sure if we could (or want) to fix the problem you are describing though. Let see what the rest of the team thinks.

**Comment by jkuipers** [comment]
I tend to agree with your comment. I was wondering though what the solution without a conditional bean would look like in this case. The idea is that I don't want an Exchange bean to be defined if the replyTo address indicates that no custom AMQP exchange is used. However, returning `null` from an `@Bean` method that declares to return an `Exchange` will result in a Spring bean that is `null`, in turn causing a NPE when the `RabbitAdmin` then tries to pre-declare all defines queues and exchanges. 

What other option would I have to conditionally define a Spring bean based on a configured property (that ideally I'd access through the `@ConfigurationProperties`-annotated bean) from a configuration class?

**Comment by snicoll** [comment]
> What other option would I have to conditionally define a Spring bean based on a configured property (that ideally I'd access through the @ConfigurationProperties-annotated bean) from a configuration class?

First, that's not what you're doing. There is `@ConditionalOnProperty` but that wouldn't work for that). You are writing custom logic so IMO you should write a condition. Right now you're just wrapping the logic in a String.

As for accessing the `@ConfigurationProperties` bean, if you tend to agree with my comment, then you shouldn't expect to be able to access it, right? Strictly speaking, I guess we should be able to make it work (though I am not convinced it is desirable to do so): see #2282

**Comment by jkuipers** [comment]
For my particular problem it seems much better to simply not rely on some conditional bean to ensure that in some situations the appropriate `Exchange` type is defined, but to write some code that checks the properties bean and then uses a `RabbitAdmin` bean to define an exchange if necessary somewhere during startup after the beans themselves have been defined.
In general it does seem a bit tricky that trying to do what I did will not result in any exception, but silently prevents Boot from binding your `@ConfigurationProperties` based on the environment. Maybe it's possible to at least detect this situation at startup and fail early?

**Comment by snicoll** [comment]
>  Maybe it's possible to at least detect this situation at startup and fail early?

That's the reason this issue is still open.

**Comment by philwebb** [comment]
Access beans in conditions is something you want to avoid at all costs. With something like this I'd suggest getting the value directly from the `Environment` and avoid trying to work with the properties bean.

You can always use the binder to temporarily bind to a throw away object. See [CacheCondition](https://github.com/spring-projects/spring-boot/blob/d221202828b542f5bf6cbbf99daf5a4b3a98753d/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/CacheCondition.java#L52) for an example.
