### ISSUE TITLE
properties content chinese messy code

### ISSUE THREAD

**Issue by lly835** [spring-projects/spring-boot#10199]
<img width="1000" alt="wx20170907-214717 2x" src="https://user-images.githubusercontent.com/2225913/30166678-94628ee6-9416-11e7-85ae-a4df186dc059.png">

<img width="787" alt="wx20170907-214646 2x" src="https://user-images.githubusercontent.com/2225913/30166670-8db51320-9416-11e7-972f-5bc0c89112d6.png">
look picture
<img width="850" alt="wx20170907-214545 2x" src="https://user-images.githubusercontent.com/2225913/30166635-796664dc-9416-11e7-9a49-db256617fa47.png">

**Comment by wilkinsona** [comment]
This is standard behaviour for a .properties file in Java. To include non-Ascii content you need to encode it using `native2ascii`.

**Comment by lly835** [comment]
change after，messy code
<img width="845" alt="qq20170908-104531 2x" src="https://user-images.githubusercontent.com/2225913/30193994-321b29b0-9483-11e7-8307-9a24b2f45b71.png">

**Comment by spencergibb** [comment]
That's an issue with Java, not Spring Boot as was mentioned.
