### ISSUE TITLE
PropertiesLauncher no longer working with packaging war

### ISSUE THREAD

**Issue by rradillen** [spring-projects/spring-boot#10234]
I have a project setup to use the PropertiesLauncher. I want to be able to provide external database drivers.

```xml
 <packaging>war</packaging>
...
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
            <configuration>
                <classifier>executable</classifier>
                <layout>ZIP</layout>
                <executable>true</executable>
                <mainClass>my.main.EntryPoint</mainClass>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Using spring boot 1.4.5 this works beautifully

Your classes get packaged in BOOT-INF/classes/WEB-INF/classes but the classloader finds them.

I upgrade to spring boot 1.5.6 now I have: java.lang.ClassNotFoundException.

I have a workaround: have an extra maven module with jar packaging and import that one in the war but it's plan Z. 

Since the behaviour changed between versions I suspect a bug.

**Comment by wilkinsona** [comment]
Sorry, I don't think I understand what you're doing.

> Since the behaviour changed between versions I suspect a bug

Not necessarily. You may have been relying on a bug in 1.4 that's been fixed in 1.5. `BOOT-INF/classes/WEB-INF/classes` is a very strangle class path location.

Can you please provide a small sample that illustrates the behaviour you have described?

**Comment by rradillen** [comment]
I created this sample https://github.com/rradillen/springbootsample

If you build it you get two artifacts one normal war and one exectuable. The normal war gets deployed in a tomcat with database drivers in the tomcat itself, not in the package. We want a similar setup for the executable war, as we don't know what database drivers it will be.

**Comment by wilkinsona** [comment]
Thanks for the sample. This does look like a regression. It works with 1.5.2.RELEASE but fails with 1.5.3.RELEASE.

**Comment by wilkinsona** [comment]
Of the changes made in 1.5.3, https://github.com/spring-projects/spring-boot/pull/8486 looks to be the most likely culprit for the change in behaviour.

**Comment by wilkinsona** [comment]
The layout of a war file repackaged using zip layout is rather strange. It's what's causing application classes to be packaged in `BOOT-INF/classes/WEB-INF/classes`. It also causes the jars of any dependencies to be duplicated in `BOOT-INF/lib` and `BOOT-INF/classes/WEB-INF/lib`. Things have always been this way as far as I can tell. I've opened #11092 to explore straightening that out.

The documented behaviour of `PropertiesLauncher` is that `BOOT-INF/classes` and jars in `BOOT-INF/lib` are added to the classpath by default. This means that classes in `BOOT-INF/classes/WEB-INF/classes` should not be loaded by default. In short, the behaviour in 1.5.3 is, arguably, correct given the strange layout that's being tracked by #11092.

The provided sample works with 1.5.8.RELEASE if the loader path is manually configured to include `BOOT-INF/classes/WEB-INF/classes`:

```
java -Dloader.path=BOOT-INF/classes/WEB-INF/classes -jar db-converter-api/target/db-converter-api-executable.war
```

Given the problem with zip layout repackaging of war files, and that `PropertiesLauncher` doesn't consider jars in `WEB-INF/lib` or `WEB-INF/classes`, I think it's safe to say that using `PropertiesLauncher` with a war hasn't really been considered before. I'm going to repurpose #11092 to track that enhancement.

Until that enhancement is in place and intentionally designed support for a war that uses `PropertiesLauncher` has been introduced, the use of the `loader.path` system properties described is the recommended solution to the problem described in this issue.

**Comment by rradillen** [comment]
The solution we eventually reached was to have a jar type artifact but additionally call the maven war plugin. This sidestepped the problem.

```xml
<project ...>
  <artifactId>...</artifactId>
  <packaging>jar</packaging>
  <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <classifier>executable</classifier>
                            <executable>true</executable>
                            <layout>ZIP</layout>
                            <mainClass>f.q.p.MainClass</mainClass>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>war</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <addDefaultImplementationEntries>false</addDefaultImplementationEntries>
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
       </plugins>
</build>

```
