### ISSUE TITLE
Elasticsearch auto-configuration may cause startup failure

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1023]
If Elasticsearch is on the classpath but Spring Data Elasticsearch is not, the auto-configuration kicks in and fails when it tries to load `org.springframework.data.elasticsearch.client.NodeClientFactoryBean`

**Comment by zhangqijia** [comment]
you can set `network.host` and `cluster.name` properties in config/elasticsearch.yml.
