### ISSUE TITLE
Set-Cookie header present even with STATELESS session management

### ISSUE THREAD

**Issue by muff1nman** [spring-projects/spring-boot#10241]
Spring boot version: 1.5.6.RELEASE

It appears that `Set-Cookie` is received on an initial 401 request with session management set to `SessionCreationPolicy.STATELESS`. Successful requests do not exhibit this problem. Debugging reveals that `STATELESS` session management ignored by `ExceptionTranslationFilter`.

Code base currently used is here: https://github.com/muff1nman/airsonic/tree/74cc46e70ca1181523e353cac77632c60db80a8c. More specifically, here is the relevant spring security configuration: https://github.com/muff1nman/airsonic/blob/74cc46e70ca1181523e353cac77632c60db80a8c/airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java

Request/response with unexpected `Set-Cookie` during 401:
```
$ curl -vvv  127.0.0.1:8080/airsonic/api
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /airsonic/api HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
> 
< HTTP/1.1 401 
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< WWW-Authenticate: Basic realm="Airsonic REST API"
< Set-Cookie: JSESSIONID=559AA20120DF12149D3FF0FB038C53F1;path=/airsonic;HttpOnly
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 11 Sep 2017 03:29:59 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
{"timestamp":1505100599702,"status":401,"error":"Unauthorized","message":"An Authentication object was not found in the SecurityContext","path":"/airsonic/api"}
```

Request/Response with good authentication correctly does not have `Set-Cookie`
```
$ curl -vvv -H 'Authorization: Basic YWRtaW46YWRtaW4=' 127.0.0.1:8080/airsonic/api
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /airsonic/api HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
> Authorization: Basic YWRtaW46YWRtaW4=
> 
< HTTP/1.1 204 
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 11 Sep 2017 03:30:01 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by wilkinsona** [comment]
@muff1nman Can you please explain why you think this is a Spring Boot problem rather than a Spring Security problem? `ExceptionTranslationFilter` is part of Spring Security and I don't believe Boot does anything to affect its behaviour here.

**Comment by muff1nman** [comment]
@wilkinsona I don't know that its a spring-boot problem or a spring security problem. If you want me to move this issue to the spring security repo, I'd be glad to.

**Comment by wilkinsona** [comment]
@muff1nman Yes, please. I think it should be investigated by the Spring Security team to begin with at least. We can re-open this issue if it turns out I'm wrong and Boot is at fault.
