### ISSUE TITLE
Drop support for Mockito 1.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10247]
Our support for Mockito 1.x in Boot 2.0 is a bit muddled at the moment. We still have `MockitoApi` and `Mockito1Api` and `Mockito2Api` but [this issue](https://github.com/spring-projects/spring-boot/issues/9904) removed the compatibility tests for Mockito 1.10 (and earlier 2.x releases). We either need to completely drop Mockito 1.x or reinstate some of those compatibility tests.

**Comment by philwebb** [comment]
I vote drop 1.x support.

**Comment by snicoll** [comment]
Ditto
