### ISSUE TITLE
 Add Jersey actuator sample

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10259]
We could do with a sample to ensure Jersey actuator support works as expected.

**Comment by wilkinsona** [comment]
IMO, we shouldn't be using samples to check that things work as expected. If we think it's useful showing how to use Jersey with Actuator then that's a good reason for a sample. We already have tests that verify the endpoint stuff works with Jersey.

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/issues/10258#issuecomment-328756552
