### ISSUE TITLE
Remove auto-configuration for MapSessionRepository

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10253]
See https://github.com/spring-projects/spring-boot/issues/9683#issuecomment-328537207

**Comment by snicoll** [comment]
@vpavic @rwinch A side effect of this is that it is no longer possible to let Spring Boot apply customizations on the filter (dispatcher types and order). As soon as you configure you own `SessionRepository` we back-off. I initially thought it was a mistake but looking at the code a bit more, I think that's the right thing to do.

I just want to double check that you are aware of that.

**Comment by wilkinsona** [comment]
I think we should auto-configure the filter even when a user provides their own `SessionRepository`. The Spring Boot defaults for the filter are the same a Session's defaults for the filter. Therefore, the auto-configuration of the filter effectively does nothing until you set a property that changes what it does. If I had customised the filter configuration (changing the dispatcher types, for example), I'd be rather surprised if I then added a session repository bean of my own and my filter configuration changed.

**Comment by rwinch** [comment]
@snicoll First, I agree that we should remove auto-configuration for `MapSessionRepository`. If a `HashMap` is used, then expired sessions that are never accessed are not cleaned up. If a user really wants in memory sessions, then they probably should just disable Spring Session and use the container's session support.

I'm not sure I understand why we cannot customize the filter. Can you elaborate on that? It seems that the filter's configuration could and would be separate of the repository and the two configurations would back off independently of one another.

**Comment by snicoll** [comment]
@rwinch I am just defining what the code does now. I agree it's unrelated and should probably be fixed. I've created #10254

**Comment by rwinch** [comment]
@snicoll Thanks for the clarification and creation of a new ticket :)
