### ISSUE TITLE
Add reactor actuator sample

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10258]
We could do with a sample to ensure that the endpoints work in a full application.

**Comment by wilkinsona** [comment]
IMO, we shouldn't be using samples to check that things work as expected. If we think it's useful showing how to use Reactor/WebFlux with Actuator then that's a good reason for a sample. We already have tests that verify the endpoint stuff works with WebFlux.

**Comment by philwebb** [comment]
I sort of agree, but I don't have confidence that we're really catching everything with our integration tests. I managed to miss `,/` from a line in `spring.factories` and the local tests all passed, but the actuator sample failed.

**Comment by florentbo** [comment]
I have  question about this sample. I clone Jersey actuator sample.
I replace it the parent version by 2.0.0.M3
But I get
Failed tests:
SampleJerseyApplicationTests.actuatorStatus:65 expected:<[200]> but was:<[404]>
Do I have to wait for the 2.0.0.M4 version?

**Comment by snicoll** [comment]
We don't use the tracker for questions. Please ask on Gitter or Stackoverflow. Also,
M4 is available.
