### ISSUE TITLE
Decide how to deal with Jolokia and security

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10264]
It's not an endpoint so the `EndpointRequest` builder won't cut it. Perhaps just manually defining the pattern is best?

**Comment by wilkinsona** [comment]
We should give some thought to securing third-party servlets that are registered in the management context as well. Spring Cloud is likely to have to move to this model for part of their Hystrix support (see #10257).

**Comment by mbhave** [comment]
maybe something for the h2 console too? there is a `spring.h2.console` path property so manually defining the pattern would duplicate it.

**Comment by snicoll** [comment]
Yes, H2 console and Jolokia are on the same boat (although one is an actuator concern and one is not there atm).

**Comment by philwebb** [comment]
@joshiste That's an interesting question. I think they should be. The problem is that both of these endpoints are MVC specific so it won't make sense to show them in a Jersey/WebFlux application.

**Comment by snicoll** [comment]
Perhaps we want to focus only on H2 console (that truly isn't an endpoint and shouldn't be)? We can migrate jolokia back to a controller once #10257 is implemented.

**Comment by philwebb** [comment]
The new `@EndpointController` is now an option for Jolokia but it isn't a very good one in my opinion since it won't work with Jersey. I think we need another type of endpoint that can be used to adapt Servlets and will work with both Spring MVC and Jersey.

**Comment by philwebb** [comment]
I'm not sure that I agree that the H2 console isn't/shouldn't be an endpoint. I suppose it's slightly unusual in that it provides a rich HTML page rather than JSON.

**Comment by snicoll** [comment]
I think adding the H2 console in this list is moving towards that anything  can be an endpoint and I don't think that's a good idea.

**Comment by philwebb** [comment]
Yeah, I think that's probably true in retrospect. Let's make this issue about Jolokia and create a new one for H2.

**Comment by philwebb** [comment]
Created #11704 for H2.
