### ISSUE TITLE
Extract configuration properties from spring-boot-actuator

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10263]
We have a few configuration property classes that should really be in `spring-boot-actuator-autoconfigure` rather than `spring-boot-actuator`.

**Comment by snicoll** [comment]
@philwebb I don't see any. There are 6 usages:

* 4 on `Endpoint` implementations
* `MetricExportProperties` is used by `MetricExporters`
* `TraceProperties` is used by `WebRequestTraceFilter`

**Comment by wilkinsona** [comment]
@snicoll Perhaps those are what @philwebb was referring to? Ideally, we wouldn't use `@ConfigurationProperties` at all in `spring-boot-actuator` and migrate the usage into `spring-boot-actuator-autoconfigure` some how.

**Comment by snicoll** [comment]
I see, that make sense.
