### ISSUE TITLE
Configure @DataJpaTest's Embedded Datasource URL 

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-boot#10271]
This is a "quality of life" request...

Here's my use case: I want my app configured for Postgres, but I want to run `@DataJpaTest` tests against HSQLDB using Postgres compatibility mode. I've figured out how to do this by annotating my tests like so
```
@RunWith(SpringRunner.class)
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
```

And adding the following to `src/test/resources/application.properties`:
```
spring.datasource.url=jdbc:hsqldb:mem:mydatabase;sql.syntax_pgs=true
```

The important tidbit is the `;sql.syntax_pgs=true` which turns on Postgres compatibility mode.

I would prefer to not have to add `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)` to every test or to make a custom annotation, and instead, would like a property that allows me to tweak my embedded test database's connection url, for example `spring.test.datasource.url=jdbc:hsqldb:mem:%s;sql.syntax_pgs=true`

Thanks!

**Comment by snicoll** [comment]
There is `spring.test.database.connection` so I guess `spring.test.database.url` is doable.

**Comment by SingleShot** [comment]
Of course, right after posting this I discovered this (in `src/test/resources/application.properties`) produces what I want without having to add annotations anywhere:
```
spring.datasource.url=jdbc:hsqldb:mem:mydatabase;sql.syntax_pgs=true
spring.test.database.replace=none
```

So... feel free to close this ticket as "won't fix" - thanks for considering it!

**Comment by snicoll** [comment]
There's that, right. I wouldn't use `application.properties` though, you're potentially shadowing the `application.properties` you might have in your production resources for that module. But that's a detail.

**Comment by geoffreywiseman** [comment]
Is this the only way to get the compatibility mode set up with H2?  My migrations fail since Spring Boot 2.2.1 because we set ENGINE=INNODB and the latest H2 apparently won't accept that without the compatibility mode turned on. We're using test database autoconfiguration, so I was hoping to find a way to set the compatibility mode without turning off the test database autoconfig, but ... that might not be possible?

**Comment by snicoll** [comment]
@geoffreywiseman please don't ask questions, in particular on closed issues. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by geoffreywiseman** [comment]
Sure -- I was asking a question about the content of *this issue*, but I can rephrase as a general question on SO.
