### ISSUE TITLE
Make run_user for the launch script configurable

### ISSUE THREAD

**Issue by obfischer** [spring-projects/spring-boot#10273]
The run user (`run_user`) used in the launch script should be configurable.

I have some services written with Spring Boot (1.5.6) as an executable jar with an embedded launch script. The jar is owed by the root user (`root:root`) therefore the service runs as root.

Therefore should the user the application is running under be configurable.

**Comment by snicoll** [comment]
Duplicate of #10275 - @obfischer no need to create an issue and a PR. A PR is enough, thanks!
