### ISSUE TITLE
Tidy up Actuator's additional configuration metadata

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10270]
There are some entries that shouldn't be there any more, for example:

```json
{
    "name": "endpoints.configprops.path",
    "type": "java.lang.String",
    "description": "Endpoint URL path."
}
```

**Comment by wilkinsona** [comment]
It'd be nice, but it's not essential, to get this into M4.

**Comment by snicoll** [comment]
I've written a tool that is supposed to catch this. I am quite surprised that I didn't see it in the report.

**Comment by snicoll** [comment]
@wilkinsona those are the error level metadata. There are present to indicate to the user that the property is no longer bound with a (hopefully) useful message.

**Comment by wilkinsona** [comment]
Oops. Sorry for the noise.
