### ISSUE TITLE
spring-boot-tools integration tests failing with Java 9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10274]
This used to work so something recent must have introduced a regression.

```
[INFO] Running post-build script: /Users/snicoll/workspace/pivotal/spring-boot/spring-boot-tools/spring-boot-loader/target/it/executable-props-lib/verify.groovy
[INFO]           executable-props-lib/pom.xml ..................... FAILED (3.8 s)
[INFO]   The post-build script did not succeed. Using -jar my.jar should load dependencies from separate jar and use the application.properties from the jar
Sep 12, 2017 10:07:38 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@394e1a0f: startup date [Tue Sep 12 22:07:38 CEST 2017]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/snicoll/workspace/pivotal/spring-boot/spring-boot-tools/spring-boot-loader/target/it/executable-props-lib/target/executable-props-lib-0.0.1.BUILD-SNAPSHOT-dependencies.jar!/BOOT-INF/lib/spring-core-5.0.0.RC4.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Hello Embedded Jar!
Sep 12, 2017 10:07:38 PM org.springframework.context.support.AbstractApplicationContext doClose
INFO: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@394e1a0f: startup date [Tue Sep 12 22:07:38 CEST 2017]; root of context hierarchy
. Expression: out.contains(Hello Embedded World!)
```

**Comment by netroby** [comment]
This problem still in 2.0.0.M6

**Comment by philwebb** [comment]
@netroby We have a JDK 9 build running on our CI server now and we've not seen the issue. This problem was specifically related to our build, so when you say "This problem still in 2.0.0.M6" do you mean you're trying to build M6 from a git tag, or something else?

**Comment by roshangade** [comment]
I am using Spring Boot(v2.0.0.M7)

System Information:
- Java version: 9.0.4+11
- Virtual Machine: Java HotSpot(TM) 64-Bit Server VM  9.0.4+11

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/roshan/.m2/repository/org/springframework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by snicoll** [comment]
@roshangade this issue is closed and we don't use the tracker for questions, please ask them on StackOverflow. Having said that, this warning, as you can see, originates from `spring-core`, see [this issue](https://jira.spring.io/browse/SPR-15859)
