### ISSUE TITLE
SpringIntegrationMetrics calls configurer.afterSingletonsInstantiated() directly

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10286]
The `SpringIntegrationMetrics` class currently calls `this.configurer.afterSingletonsInstantiated();` directly. We seem to be getting away with it, but probably by accident rather than design.

**Comment by mbhave** [comment]
`IntegrationManagementConfigurer` is registered before `SpringIntegrationMetrics` so `IntegrationManagementConfigurer#afterSingletonsInstantiated` will be called before `SpringIntegrationMetrics#afterSingletonsInstantiated`. Need to confirm with @jhoeller that the ordering is guaranteed.
