### ISSUE TITLE
issue with latest version : No bean named 'entityManagerFactory' available

### ISSUE THREAD

**Issue by sureshatta** [spring-projects/spring-boot#10281]
Here is the code that I am trying

https://github.com/sureshatta/stackOverflowExamples/tree/master/SpringBoot/MySQL

For the same code if I try with 

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.6.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

I run into an error https://stackoverflow.com/questions/46190317/spring-boot-mysql-with-jpa-no-bean-named-entitymanagerfactory-available

however if I  change the version 

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.1.RELEASE</version>
        </parent>

```

Everything fine and works. What I am missing here ?

**Comment by snicoll** [comment]
Thanks for sharing a sample but this application works for me, both with 1.3.1 and 1.5.6. Let's keep the conversation on stackoverflow
