### ISSUE TITLE
Ease extension of DataSourcePublicMetrics

### ISSUE THREAD

**Issue by mduesterhoeft** [spring-projects/spring-boot#10288]
I want to publish additional DataSource metrics that a Tomcat DataSource provides (number of idle connections, current pool size). 

Currently, this is very hard to do because the functionality in `DataSourcePublicMetrics` cannot be reused by subclasses.

I will come up with a proposal on how to improve this situation.

**Comment by wilkinsona** [comment]
Thanks for raising this. If you intend to immediately make a proposal in a pull request, there's no need to open an issue too. I'll close this one as a duplicate of the PR.

**Comment by wilkinsona** [comment]
Duplicate of #10289
