### ISSUE TITLE
Rework Micrometer export configuration properties classes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10292]
The various `*Properties` `@ConfigurationProperties` classes in `org.springframework.boot.actuate.autoconfigure.metrics.export.*` are rather atypical. All the properties are pushed down into a `Properties` object and are, therefore, stringly typed. There's a public `get(String key)` method but no discoverability for what the keys can be. There are also more strongly typed "getter" methods for the properties thank to default methods on the Micrometer interfaces that are implemented. These methods don't match the java bean conventions (no `get` prefix). We should revisit this code in Boot and in Micrometer with a view to being able to generate metadata for all of the supported properties and making things as strongly typed as possible.

/cc @jkschneider

**Comment by jkschneider** [comment]
@wilkinsona We addressed this last night as part of M4. This can be closed.
