### ISSUE TITLE
@ControllerAdvice behaving erratically in Spring Boot 2.0M3

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#10291]
I cross open the bug report initially created here https://jira.spring.io/browse/SPR-15861 because the Spring developers tells me that this could a spring boot issue.

----

I'm using messaging (websocket) classes with methods annotated with @MessageMapping, with Spring Boot 2.0M3 and I'm experiencing stability issues: my class marked with @ControllerAdvice sometimes is not handling the exceptions and they are instead propagated to the client.

I've also seen the problem where when one Exception is generated by controller A gets correctly handled by the @ControllerAdvice class, while when generated by controller B is not.

This seems to be related to the way the binary is built: some builds works fine, while some others exhibit the problem, so I would suppose that a different ordering of the jars inside the artifact causes the problem.

I'm not able to reproduce it at will right now, sometimes it works, sometimes not, I would like to leave this report open to track the problem and see if someone else runs in it too.

**Comment by snicoll** [comment]
There is an active discussion going on this issue, there's really no reason to cross-post.
