### ISSUE TITLE
spring-boot-starter 1.5.7 is not available on maven central

### ISSUE THREAD

**Issue by mld-ger** [spring-projects/spring-boot#10297]
Hi,

I just wanted to update to Spring boot 1.5.7 and noticed that spring-boot-starter.jar is not available on maven central. I get a 404 when fetching https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter/1.5.7.RELEASE/spring-boot-starter-1.5.7.RELEASE.jar

**Comment by snicoll** [comment]
Nothing we can do I am afraid. The network glitch has been reported to Sonatype and they're investigating.

(In short: the file is there in certain areas of the World, not in others).

There is an issue (that's private at the moment, I asked them to make it public): https://issues.sonatype.org/browse/MVNCENTRAL-2698
