### ISSUE TITLE
Shade JSON API in annotation-processor

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10307]
#9248 is now generating a warning if two competing JSON APIs are on the classpath.

As far as I can see, `spring-boot-configuration-processor` is the only component that pulls that in. An annotation processor is typically added via an "optional" dependency but, regardless, that JSON API becomes available to the project's classpath.

Two side effects:

* You may want to code against that API and then be surprised that your code doesn't work because the annotation processor is (and should not be) added as transitive
* If you add a JSON API (as you should) you automatically get a duplicate warning message and no way to fix it.

Also, the JSON api we use is not in dependency management so users can't even chose that if they don't have an opinion regarding the implementation.

**Comment by snicoll** [comment]
Actually JSONAssert also brings that API so I think we should at least provide dependency management for it. Otherwise, how are we supposed to get rid of the warning?

**Comment by philwebb** [comment]
I think we had this shaded at one point but it broke in the IDE.

**Comment by wilkinsona** [comment]
I'm not sure I understand the benefits of shading the API for the first problem. How will that stop a user from accidentally coding against it? We'd need something that's package-private to avoid that would we not?

**Comment by snicoll** [comment]
That's what I meant.

**Comment by philwebb** [comment]
We did a shade/relocate before. See 45d5b60f6dd92553ecd91bba8c0fc051ac6995e1

**Comment by philwebb** [comment]
@snicoll In fact I think this can be marked as duplicate?

**Comment by snicoll** [comment]
Not really. I said I would investigate and I did not. So I'd like to do that as shading is the right call for this IMO.

**Comment by snicoll** [comment]
Actually, I'd like to make this change in `1.5.x` still as, with the current arrangement, two JSON APIs can end up on the compile classpath if the project uses a different library (which is something that is likely to happen). This leads to concrete issues [such as this one](https://github.com/spring-cloud/spring-cloud-gcp/pull/276#issuecomment-352795555)

**Comment by philwebb** [comment]
@snicoll Did you ever get to the bottom of why the real shade plugin didn't work? It's a bit annoying to have the actual raw source included as it causes a bunch of compile time errors (mainly missing generics).
