### ISSUE TITLE
Support Maven war overlays in spring-boot:run

### ISSUE THREAD

**Issue by cthiebault** [spring-projects/spring-boot#1030]
Spring Boot maven plugin does not support war overlays.

See http://stackoverflow.com/questions/24025004/spring-boot-maven-war-overlay/24040465 for more details

**Comment by snicoll** [comment]
I am closing this one for now. Nothing has been done in that area and I doubt we ever will. Such transformation of the target artifact means that you can "right click and run". And if you can't do that, then `spring-boot:run` shouldn't either.

**Comment by karthilxg** [comment]
I ran into same issue while I tried to separate out services and ui code to a separate maven module.

https://github.com/jhipster/generator-jhipster/issues/2890

@cthiebault Did you find any alternate solutions for this issue?

**Comment by snicoll** [comment]
@karthilxg I already replied above and this issue is closed. We don't intend to support such use case for `spring-boot:run`. If you need to transform the war, use any of the available plugins to run a war file (cargo, tomcat plugin, jetty plugin, etc).
