### ISSUE TITLE
JmsMessagingTemplate is wrongly configured

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#10305]
The configuration for the `JmsMessagingTemplate` is wrong (at least in my opinion). For the `JmsTemplate` you can configure the `MessageConverter` and it will be used. However, that converter is not passed to the `JmsMessagingTemplate`, and therefore the default one is used.

Maybe this is an issue for spring-jms, but I think that it should be correctly configured. It is not complicated as well. One only needs to get the message converter that the `JmsTemplate` has.

I think that this would be the solution in the `MessagingTemplateConfiguration`:

```java
@Bean
@ConditionalOnMissingBean
@ConditionalOnSingleCandidate(JmsTemplate.class)
public JmsMessagingTemplate jmsMessagingTemplate(JmsTemplate jmsTemplate) {
    JmsMessagingTemplate messasgingTemplate = new JmsMessagingTemplate(jmsTemplate)
    if (jmsTemplate.getMessageConverter() != null) {
        messagingTemplate.setConverter(jmsTemplate.getMessageConverter();
    }
    return messagingTemplate;
}
```

**Comment by filiphr** [comment]
Btw. the RabbitMq messaging template is OK as it is correctly done within it :)

**Comment by snicoll** [comment]
That doesn't sound the right place to fix this. Please open a framework issue instead.

**Comment by filiphr** [comment]
Thanks for the quick response @snicoll, I was not sure where the correct place to do this was. For info (if someone else stumbles on this), I have opened [SPR-15965](https://jira.spring.io/browse/SPR-15965) in the framework
