### ISSUE TITLE
Unnecessary dependencies in fatjar

### ISSUE THREAD

**Issue by mariuszs** [spring-projects/spring-boot#10315]
Please, consider removing all dependencies in generated fatjar (maven version) using [Flatten Maven Plugin](http://www.mojohaus.org/flatten-maven-plugin/).

Flatten Maven Plugin should allow soon to remove all fatjar dependencies, more info: https://github.com/mojohaus/flatten-maven-plugin/pull/49#issuecomment-329721680

Sample usage:

```xml
<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>flatten-maven-plugin</artifactId>
   <configuration>
     <flattenMode>fatjar</flattenMode>
   </configuration>
</plugin>
```

**Comment by bclozel** [comment]
Could you elaborate a bit more on:

* what is this plugin achieving exactly and which use case we can address with that
* why can't you achieve that already with Spring Boot

**Comment by mariuszs** [comment]
Sorry, first use case in my mind is a situation, when you need to attach spring boot application as dependency to other project. For example, when you have microservice with contract definition (stubs) as dependency, then you need to **exclude** all  spring boot dependency, because they can pollute whole project.

Example: https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/consumer_with_restdocs/pom.xml#L52

```
		<dependency>
			<groupId>com.example</groupId>
			<artifactId>beer-api-producer-restdocs</artifactId>
			<classifier>stubs</classifier>
			<version>0.0.1-SNAPSHOT</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

Spring Boot application should not publish all this dependency inside `pom.xml`, because all this libraries are already inside jar. Additionally, development configuration (plugins etc) are not important for users of this application, so we should clean generated `pom.xml`. And this can be done with Flatten Plugin.

**Comment by snicoll** [comment]
@mariuszs that doesn't make much sense to me. fatjars are not meant to be used as a dependency (perhaps you're using an older version of Spring Boot?). There are final artifacts and repackage can be configured to generate the fatjar as an classifier (secondary artifact). In that case, you absolutely need the dependency information IMO.

I'd also argue that using the same project as a module and as an application is a bit of a smell (this isn't new, using a `war` as a dependency is pretty much the same thing).

**Comment by mariuszs** [comment]
Please take a look one more time at provided example. This is example from Spring Cloud Samples, attached artifact **is not** a spring boot application, this is a **stub** of this application: `beer-api-producer-restdocs-stubs.jar`. 

Spring Boot application with contract definition (stubs) has only one `pom.xml` for all classifiers. 

I don't get why published `pom.xml` should contains dependency in `pom.xml`.

**Comment by snicoll** [comment]
> Please take a look one more time at provided example. 

I did and it doesn't match your original description.

> Spring Boot application has only one pom.xml for all classifiers 

This has nothing to do with Spring Boot really. All Maven projects are built that way.

> I don't get why published fat-jar pom.xml should contains dependency in pom.xml

This is the standard behaviour. War artifacts are also final and are also defined that way. It looks like you are looking after a core feature in Maven that doesn't exist and I'd rather have that fixed at that level than here.

**Comment by mariuszs** [comment]
Yes, this is standard behaviour. Flatten Maven plugin resolves some issues related to published pom.xml, that differs from development pom.xml. This are new things. Of course users can simply use this plugin in spring boot application when is needed. I see two options for them:
* Add boot depedency and always manually exclude all transitive dependencies
* Use flatten-maven plugin and add boot dependency without additional configuration.

For simplicity, this plugin can be recommended for spring contract users, and maybe configured in generated pom.xml from start.spring.io, when spring contracts are enabled.

**Comment by snicoll** [comment]
I am not disputing any of that. That discussion should happen in the spring cloud contract issue tracker. I believe there are other less invasive options as well.
