### ISSUE TITLE
Spring Boot 2.0.0.M4 broke Spring Cloud Config server Finchley.M2

### ISSUE THREAD

**Issue by mpalourdio** [spring-projects/spring-boot#10311]
Hello,

After upgrading my spring configuration server (Finchley.M2) to Spring Boot 2.0.0.M4, my discovery server (same dependencies versions) can't connect anymore to the configuration server.

Here is the stack trace

``
017-09-15 21:00:57.625  INFO 9273 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.springframework.cloud.config.environment.Environment] and content type [text/html;charset=UTF-8]
``

Going to http://localhost:8888, in 2.0.0.M3 used to pop a basic auth form. Now, it displays an html form.

Please let me know if you need more details.

**Comment by spencergibb** [comment]
Spring Cloud hasn't upgraded to the milestone yet.  It may be a week or two

**Comment by mpalourdio** [comment]
Thanks for answering so fast ! I was just reading those security changes here https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0

Closing for now so. Thanks for all the awesome stuff :+1:
