### ISSUE TITLE
Handle multiple services with live-reload

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-boot#10321]
Spring-boot is quite often used in microservice architectures, which implies that you might need to start more than one during development on your local computer.

The LiveReload port seems to be fixed, so only the first service that is started gets the port and the remaining services just disable the server.

It would be very nice to have a way to handle this better in terms of the development experience, because checking netstat to see which service got the port and restarting services to give the correct service the port is tedious.

Possible solutions that come to my mind are for example:

- Do not start the live reload server and activate it via rest call to an actuator endpoint (behavior enabled via property to keep the old behavior as default) 
- Actuator endpoint to activate/deactivate port (This still leaves the task to determine the instance that got the port to the developer)
- make the livere-load port randomized and communicate the port to the tools via html tag (not sure about the tool support, but I think that rails does something similar)
- use spring cloud sync to trigger reloads when any of the connected servers has changes (would work for me, but not everyone uses spring-cloud/spring-bus)

Any thoughts?

**Comment by snicoll** [comment]
You can [configure Devtools to watch more than one directory](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart-additional-paths),  have you tried that?

**Comment by pcornelissen** [comment]
That won't help in case of multiple independent services. You would need to configure the location of the source of all other services :-/

One of the key aspects of the services is that they are independent and thus have their own git repo, are checked out to whatever directory fits best, etc.
So to create a config that hardcodes these directories seems to be a bad idea.

I am aware that my request may be a hard problem that won't be fixed/worked on, I just wanted to make sure you guys know that there is a need for something like that. 
(And I still have a little bit of hope that someday a solution will be available for that) ;-)

**Comment by snicoll** [comment]
I am not following. Reading your description, it looks like you are looking for a feature to get a unified developer experience and yet at the same time claim that those things are completely independent. If you are running them in your IDE together, they aren't.

You need to settle to something acceptable at some point and I believe that devtools has the current features to make that happen. As for the configuration side of things, yes it would be tedious but I would argue this is more of a tooling problem so I'd advise you to report that use case in the tracker of the IDE you are using. Adding a link here would be helpful.

**Comment by pcornelissen** [comment]
Well, I think I didn't get my point across very well :-)

To make the live reload feature more developer friendly in case of multiple running services, I'd like to propose something like this (in descending order of usefulness)

1. Something to turn on live reload on a running system for example via actuator endpoint and to remove the burden to find the service that currently "owns" it, a way to disable the livereload server on the livereload server port itself would be great. Then for example intelliJ could add this to the Spring-boot-UI and you could switch the service that performs the live reload with a click.
2. Randomized liveReload ports so that multiple services can have live reload running at the same time (needs check that the browser plugins can work with different ports)
3. Toggle to disable the live reload server to get rid of it when the server is not under active development in that moment + actuactor endpoint to turn it on/off on running services
4. Toggle to disable the live reload server to get rid of it when the server is not under active development in that moment
5. Spring-Bus based sync of changes so that the service that currently has the livereload server running can trigger the refresh

As I wrote adding the services to the the watch-dir is not feasible and IMHO too much work.
But of course I honor the decision to not follow that suggestion.

Keep up the good work, spring(-boot) is the best since sliced bread :-)

**Comment by snicoll** [comment]
Thanks for the feedback. I can't honestly see why any of that would be superior than a support in your IDE. The idea is not far fetched, all major IDEs have decent Spring Boot support so if you could describe a use case that the tool could support and report it that would be awesome.

>  you could switch the service that performs the live reload with a click.

Why? IMO it doesn't matter which service has the livereload server as long as it refreshes your browser once it detects a change (and the config option I gave can be configured by the IDE. I can see that happening with the new dashboard thing in IJ - STS has it for quite some time). You can also configure live reload [to work with a touch file](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart-triggerfile). Netbeans makes use of that.

2  is [not an option](http://livereload.com/tips/change-port-number-livereload-listens-on/)
> By default, LiveReload app listens on port 35729, and does not officially support changing the port number.

Moving the livereload server feels a bit too complicated to me. Can we explore the IDE route? If someone in the team disagrees we can reopen this one for sure :)

**Comment by pcornelissen** [comment]
https://youtrack.jetbrains.com/issue/IDEA-179138
