### ISSUE TITLE
Actuator endpoints disabled by default

### ISSUE THREAD

**Issue by arosini** [spring-projects/spring-boot#10331]
While updating my Spring Boot application to the latest build snapshot and I am seeing that none of the actuator endpoints are enabled by default. If I specify them to be enabled in application.properties, they show up.

Searched for an existing issue but couldn't find one...Apologies if this is intended.

**Comment by wilkinsona** [comment]
The status and info endpoints (`/application/status` and `/application/info` respectively) should be enabled by default. All other web endpoints must be enabled, either globally or individually. If that's not the behaviour you are seeing, please provide a sample that reproduces the problem.

**Comment by snicoll** [comment]
Also, if you are on the latest dev snapshot it would be worth reading the release notes before opening an issue. We're also on Gitter if you want to chat.

**Comment by arosini** [comment]
Ah I updated my snapshot and it seems to be working now. I must have had one that was before https://github.com/spring-projects/spring-boot/commit/40e6f004daf4f35d4af58c11f59eea71909e78b6.

Thanks, and the new actuator model makes a lot more sense to me.

**Comment by ryanthon** [comment]
> The status and info endpoints (/application/status and /application/info respectively)

@wilkinsona 
Is there a way to disable the "/application" endpoint? It seems to be enabled by default as well.

**Comment by wilkinsona** [comment]
It cannot be enabled or disabled individually. If you would like that to be possible, please open a new issue explaining why you want that level of control and we will consider it.

**Comment by ryanthon** [comment]
@wilkinsona 
Apologies for the double post with my question.
Just curious, is there a particular reason why that is the case? Or better yet, what is the purpose of that endpoint?

**Comment by wilkinsona** [comment]
The endpoint's purpose is to provide hypermedia (links) for all the enabled endpoints. From the [documentation](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoint-hypermedia):

> 49.3 Hypermedia for actuator web endpoints
> A “discovery page” is added with links to all the endpoints. The “discovery page” is available on `/application` by default.

If you'd like to discuss this further, please come and chat on [Gitter](https://gitter.im/spring-projects/spring-boot). GitHub issues aren't really the right place for this.
