### ISSUE TITLE
FreeMarker configuration and it's auto-configuration in non-MVC applications

### ISSUE THREAD

**Issue by Drizzt321** [spring-projects/spring-boot#10337]
I'm using FreeMarker as templating to send emails in a non-MVC application which does happen to use Jetty (and so qualifies as a Spring `@ConditionalOnWebApplication`). Despite me creating my own `FreeMarkerConfigurationFactoryBean freeMarkerConfiguration()` Bean configuration, `DefaultListableBeanFactory` is overriding that in favor of the `FreeMarkerAutoConfiguration.FreeMarkerWebConfiguration` auto-configuration.

Sadly there is essentially no official Spring documentation about using FreeMarker other than in an MVC application, and limited guides elsewhere. The best one I have found, that I'm basing most of my stuff off of, is [this tutorial](http://www.technicalkeeda.com/spring-tutorials/spring-4-sending-email-with-freemarker-template) which creates a FreeMarkerConfigurationFactoryBean bean as I'm doing.

Unfortunately, as pointed out above, since I'm using a Servlet engine, my application counts as `@ConditionalOnWebApplication` which triggers the FreeMarker auto-configuration to use a `FreeMarkerConfigurer` as it's configuration for FreeMarker templates and such. So, if I use `@EnableAutoConfiguration(exclude = {FreeMarkerAutoConfiguration.FreeMarkerWebConfiguration.class})` it avoids that and correctly configures using my `FreeMarkerConfigurationFactoryBean` Bean and finds my templates and everything is just fine.

I think some (any!) documentation in the main Spring docs is needed for non-MVC FreeMarker configuration, although this is perhaps not specifically a Spring-Boot issue. But it'd be great to change the `FreeMarkerWebConfiguration` to change the condition so only when `@EnableWebMvc` is set use it, instead of using `@ConditionalOnWebApplication` as it is currently.

Thoughts before I do the work and submit a PR?

**Comment by philwebb** [comment]
Is your application actually using Spring MVC? If not, then perhaps excluding the `spring-webmvc` jar might be the easiest fix. A PR that updates the documentation would be most welcome.

**Comment by Drizzt321** [comment]
Huh...apparently I AM using Spring MVC. Didn't realize `@RestController` was part of that side of things. I guess you can discount a fair amount of what I said above, I am using it so the FreeMarker auto-config is properly trying to auto-configure with the `FreeMarkerConfigurer` Bean that I'm supposed to have created. Go figure.

**Comment by philwebb** [comment]
OK, I'll close this one for now since it feel like it might be a specialized case, and not really warranting custom documentation.

**Comment by Drizzt321** [comment]
Sounds good, although it would be nice to have a bit more non-MVC documentation in the main docs, but that's not Spring-Boot.

**Comment by philwebb** [comment]
@Drizzt321 I'm sure the core team would be happy for a PR. Their issue tracker [is here](http://jira.spring.io).
