### ISSUE TITLE
Rename spring-boot-starter-redis to spring-boot-starter-data-redis

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1033]
_I doubt we want to do this at this stage of 1.1, and we may even want to wait till 2.0._

`spring-boot-starter-redis` is the only starter for a Spring Data project that doesn't have data in its name. For consistency, it should be called `spring-boot-starter-data-redis`

**Comment by snicoll** [comment]
Repository support is coming so maybe we could put this one back on the agenda? 1.4 maybe?
