### ISSUE TITLE
Fail fast if a nested condition uses a phase that's inappropriate for its members

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10347]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

In Spring, a condition defines some criteria that should match in order for a component to be registered. Certain conditions can be configured with a `ConfigurationPhase` which offers finer-grained control. There are two phases:
* `PARSE_CONFIGURATION` which implies that the `Condition` should be evaluated as a `@Configuration` class is being parsed
* `REGISTER_BEAN` which implies that the `Condition` should be evaluated when a non `@Configuration` bean is being added

In Spring Boot, nested conditions can be used to create composite conditions. For example, the `AllNestedConditions` will match only when all nested conditions match. 

## Problem

There's a possibility of misconfiguration with nested conditions if the nested condition uses a configuration phase that is inappropriate for it's members.          

## Solution

We should catch the misconfigured nested condition, i.e, when the enclosing condition has a `PARSE_CONFIGURATION` phase and a member condition has a `REGISTER_BEAN` phase. At this point, we should throw an `IllegalStateException`.

The code for getting the member conditions for a nested condition can be found [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/AbstractNestedCondition.java#L121).

A new test that asserts that an `IllegalStateException` is thrown would need to be added.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by onraz** [comment]
I would like to work on this issue, thanks!

**Comment by mbhave** [comment]
@onraz Sounds good! We'll look forward to your Pull Request.

**Comment by onraz** [comment]
Would be able to provide some example code (or a test case) of a nested condition that uses an inappropriate configuration phase for its members?

**Comment by wilkinsona** [comment]
@onraz An example is the use of `@ConditionalOn(Missing)Bean` on an inner-class within a nested condition that is using the parse configuration phase.

**Comment by onraz** [comment]
Thanks @wilkinsona for the example. The inverse is also problematic, i.e. when enclosing/nested condition is _register bean_ phase, but member bean declared as _parse configuration_ phase. It then implies the enclosing/nested condition and member conditions that are `ConfigurationCondition` must _match_. 
Does this mean a member condition that doesn't have a configuration phase associated won't be part of this enforcement (e.g. `ProfileCondition`)? It seems such condition can have implicit phase associated - based on target (e.g. condition on a nested `@Configuration` class). Should this change consider such scenarios?

**Comment by wilkinsona** [comment]
@onraz You have stated that the inverse is also problematic. Can you please explain why you believe that to be the case?

There is a danger in evaluating a register bean condition too early (in the parse configuration phase) as it may lead to false positives for ConditionalOnMissingBean and false negatives for ConditionalOnBean. I do not believe there is a danger for the inverse when a configuration phase condition is evaluated in the register bean phase.

**Comment by onraz** [comment]
That makes sense @wilkinsona, I was thinking in the inverse case it could lead to incorrect behavior if the  member condition evaluation needs to be deferred until register bean phase, due to enclosing phase. So the change would simply enforce member conditions don't have registration phase when enclosing condition is parse configuration.

**Comment by wilkinsona** [comment]
Yes, I believe that is all that’s necessary.

**Comment by onraz** [comment]
Pull Request: https://github.com/spring-projects/spring-boot/pull/15086

**Comment by philwebb** [comment]
Closing in favor of PR #15086. Thanks very much @onraz, we'll continue any discussion on the PR.

**Comment by onraz** [comment]
Thanks for the guidance and opportunity to contribute @philwebb, @wilkinsona & @mbhave. Really enjoyed working on the issue, if there is a way/filter to discover smaller issues, I'd love to contribute more in the future.
