### ISSUE TITLE
Consider registering an in memory `UserDetailsService` using properties

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#10349]
The `InMemoryUserDetailsManager` can create users based on comma-separated values. We can probably create the `UserDetailsService` bean based on the following property structure:

```
security.users.phil: password, USER
```

**Comment by snicoll** [comment]
I am not a huge fan of exploding the use of map-based binding in the core. Why don't we restore what we had before ? (One configurable user). 

IMO if we open that door we may get requests to further extend it.

**Comment by mbhave** [comment]
Could you elaborate a bit on why you wouldn't want the map-based binding? 
I think the idea was to simplify creating an InMemoryUserDetailsManager even if you have multiple users so if we go with making the user configurable, I'm not sure that we should limit it to one user.

**Comment by snicoll** [comment]
Simply that we shouldn't offer more than what we were offering in 1.x. 

I surely don't like the unstructured data of the value map. You can't get any smart validation in the IDE for that stuff and it feels out of place IMO.

**Comment by philwebb** [comment]
I'm a little torn with this one. The code to create the `InMemoryUserDetailsManager` is noisy:

```java
	@Bean
	public UserDetailsService userDetailsService() throws Exception {
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(
				User.withUsername("user").password("password").roles("USER").build());
		return manager;
	}
```

So it would be quite nice to offer a way to create in-memory users easily. Since `InMemoryUserDetailsManager` offers this constructor:

```java
	public InMemoryUserDetailsManager(Properties users) {
		Enumeration<?> names = users.propertyNames();
		UserAttributeEditor editor = new UserAttributeEditor();

		while (names.hasMoreElements()) {
			String name = (String) names.nextElement();
			editor.setAsText(users.getProperty(name));
			UserAttribute attr = (UserAttribute) editor.getValue();
			UserDetails user = new User(name, attr.getPassword(), attr.isEnabled(), true,
					true, true, attr.getAuthorities());
			createUser(user);
		}
	}
```

It does seem logical that we could keep the same format.

**Comment by philwebb** [comment]
Having said that, creating a custom user with a generated password might be a bit tricky with that format. Perhaps offering a way to create a single in-memory user easily would be enough.

**Comment by wilkinsona** [comment]
I guess I'm torn too. I agree with Stephane that we should avoid map-based binding. I also agree with Phil that the code to create an InMemoryUserDetailsManager is noisy. Given that InMemoryUserDetailsManger is "mainly intended for testing and demonstration purposes", the benefit of being able to externalise its configuration is somewhat reduced. You could just create your own bean in some test configuration instead. In summary, I don't think we should do anything in Boot. I think there would be some value in exploring a more concise API for building an `InMemoryUserDetailsManager` in Spring Security.

**Comment by philwebb** [comment]
I've raised https://github.com/spring-projects/spring-security/issues/4564
