### ISSUE TITLE
BackgroundPreinitializer can cause hang when context startup fails

### ISSUE THREAD

**Issue by ksperling** [spring-projects/spring-boot#10362]
I just observed a case of `BackgroundPreinitializer` causing a a test where the context failed to start to hang indefinitely.

Stack dump: https://gist.github.com/ksperling/b19382a5b9eef6fa0913b45cb9318367

From looking at the code it seems this might happen if a `ApplicationFailedEvent` is delivered without ever having received a `ApplicationEnvironmentPreparedEvent`. `preinitializationStarted` should be checked before calling `preinitializationComplete.await()`.

I am using Spring Boot 1.5.7.RELEASE

**Comment by ksperling** [comment]
In my specific case this is cased by a `EnvironmentPostProcessor` that fails to load due to a `NoClassDefFoundError`. `ApplicationEnvironmentPreparedEvent` is never fired.

**Comment by wilkinsona** [comment]
Oops. Thanks for the analysis.
