### ISSUE TITLE
Problem on start with starter-data-jpa and orm.xml on classpath

### ISSUE THREAD

**Issue by artaban** [spring-projects/spring-boot#10363]
I'm using Spring boot 2.0.0.M4 and trying to run bundled application with `orm.xml` on classpath (resources/META-INF/). I'm getting following error:
`java.lang.IllegalStateException: Duplicate XML entry for com.example.demo.model.Entity`

The error is thrown on `AnnotationMetadataSourceProcessorImpl.java:94)` and is caused by the fact, that the **orm.xml** file has been found twice:

* Origin(name=BOOT-INF/classes/META-INF/orm.xml,type=INPUT_STREAM)
* Origin(name=jar:file:../build/libs/test-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/META-INF/orm.xml,type=INPUT_STREAM)

Attaching the sample gradle project: [spring-orm-problem.zip](https://github.com/spring-projects/spring-boot/files/1317562/spring-orm-problem.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. As far as I can tell, this is a bug in Hibernate. It should be looking for files named `META-INF/orm.xml` at the root of the classpath. Instead, it's finding files named `META-INF/orm.xml` anywhere on the classpath. When you run a Boot fat jar both the root of the jar (allowing the launcher to be loaded) and the `BOOT-INF/classes` directory (allowing the application to be loaded) are classpath roots. Hibernate is finding `META-INF/orm.xml` from both of these roots when I believe it should only be finding it from the latter.

You can reproduce the problem without creating a bundled application if you copy your `orm.xml` file into `src/main/resources/foo/META-INF/orm.xml`. If you wish to pursue this, I would recommend raising it with the Hibernate team.
