### ISSUE TITLE
Env endpoint does not display canonical format

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10370]
The `EnvironmentEndpoint` does not use the new canonical format that the new binder API introduced. 

The goal in 2.0 is that the `env` endpoint shows the properties in a canonical format rather than what the user has provided in configuration or via a command line switch.

**Comment by snicoll** [comment]
@philwebb @mbhave I think I might have found a few corner areas where the new binding would need some more love (see 60af38f)

There are binding-specific concepts that are required outside of binding. This is the same as #10184 IMO. I had to extend `PropertySourcesPlaceholdersResolver`.

The `ConfigurationPropertySource` have an underlying `PropertySource` but no notion of name. Accessing the `underlyingSource` to get the name feels a bit weird to me.

The duplication of the `PropertySource` is quite confusing at first. We can see that the `Binder` both uses the canonical sources and the original sources which IMO is a bit of a smell because depending on where you are you may have canonical support or not.

But, IMO, the blocker is the public format for each key. Is there any way we can make that our canonical format (i.e. kebab-case)? If you checkout that branch and invoke the env endpoint, no key look like how they are advertized in our doc, in our metadata and in any IDE auto-completion. For instance:

```
"spring.jackson.serialization.writedatesastimestamps": {
          "value": "false",
          "origin": "class path resource [application.properties]:15:56"
}
```

**Comment by mbhave** [comment]
@snicoll I'm not sure if I agree that the env endpoint should display the uniform format rather than what the user has configured. Especially, since we're showing the origin with the line number etc, isn't it more obvious to track down the property in it's original form? 

> But, IMO, the blocker is the public format for each key. Is there any way we can make that our canonical format (i.e. kebab-case)?

I didn't follow this. I agree that `spring.jackson.serialization.writedatesastimestamps` is weird and should instead be `spring.jackson.serialization.write_dates_as_timestamps` which is what the original property is.

**Comment by snicoll** [comment]
The whole point of the harmonisation is to show what is actually happening. So if a property is wrong, the user should know about it. 

One way is to show our canonical format (kebab-case). Maybe there is other. 

But the key here is that If you ask for a property for a given key, it should t return only an exact match. Right now it does and that's wrong IMO

**Comment by philwebb** [comment]
IMO the `/env` endpoint should be about what's in `org.springframework.core.env.Environment`. I don't think it makes sense to change the way property names are displayed for that endpoint.

The canonical format is really a concept that only exists for retrieving data. It doesn't change the way that things are stored in the `Environment`.

**Comment by snicoll** [comment]
Unfortunately I dont think that's consistent. 

If you get all the environment that's debatable. If you get one particular entry however you expect relaxed binding to take place.

Concretely if you ask for "my.super-property" you should get the info for that property regardless of the supported format. So you need to go through the new infrastructure. And I don't see a way to get back the original property name. 

Having the env endpoint harmonised with kebab-case is my preference. At the very least endpoint per id should work regardless of the format. 

Thoughts ?

**Comment by philwebb** [comment]
Perhaps we should reconsider consider what we want that endpoint to actually show? In my opinion the `/env` endpoint should show raw environment information. I'm interested in all the property sources that are in the environment, and all the properties that they contain. If I call `/env/my.super-property` then I want that raw result that a call to `Environment.getProperty` would return.

Working out what `my.super-property` would return when used in a binding context feels like a different concern. Perhaps something that `/configprops` should show?

**Comment by snicoll** [comment]
That's exactly the point I am trying to make. If you call that and you've defined "my.super_property" somewhere then the environnement will return you the value but none of the PropertySource that hold the raw information will match. 

I actually created the issue while working on adding a "value" attribute to the json. In the case above the value is set but no property source in the json had any detailed info. 

Regardless of what we do, I think we should change something.

**Comment by philwebb** [comment]
I think we should remove all relaxed binding concepts from `/env` and make it a 1-1 mapping onto the Spring Environment. Let's see what the others think.

**Comment by snicoll** [comment]
With @philwebb's help, I managed to get my head around this one. The actual problem is that `/env` and `/env/{name}` do not represent similar things. The former is a full view on the environment and we should show what the user has actually typed. 

The latter is a view on a dedicated entry and it shouldn't matter how that entry is formatted but we can't really get back to the key. All that matters at this point is which property sources have contributed to the value and what the origins are.

So we need to change the output of `/env/{name}` and we already have an issue for that (#10178)
