### ISSUE TITLE
Allow Spring Kafka MessageConverter bean to be picked up by auto-configuration

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#10376]
It would be cool if Spring Boots auto-configuration for Kafka would pick up a bean of type `MessageConverter` to register it with the `ConcurrentKafkaListenerContainerFactory` Boot creates by default. That would come in handy to easily a converter that uses Jackson or other means to create strongly typed payloads for `@KafkaListener` methods.

**Comment by snicoll** [comment]
I like it and it's consistent with what we do with other messaging integration.

Paging @garyrussell to double check

**Comment by snicoll** [comment]
Closing in favour of PR #10380
