### ISSUE TITLE
SecurityMockMvcConfigurers not found tests libraries

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#10373]
I need SecurityMockMvcConfigurers class in tests.

```
mockMvc = MockMvcBuilders.webAppContextSetup(wac)
                .apply(SecurityMockMvcConfigurers.springSecurity())
                .build();
```

but I cant's find this in spring **boot** libraries
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/1.5.7.RELEASE
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-security-tests/1.5.7.RELEASE

I can find only in spring libraries
https://mvnrepository.com/artifact/org.springframework.security/spring-security-test/4.2.3.RELEASE

Please add _spring-security-test_ to _spring-boot-security-tests_.

**Comment by snicoll** [comment]
Duplicate of #10062
