### ISSUE TITLE
Bug in JPA added in spring-boot-starter-data-jpa

### ISSUE THREAD

**Issue by WHK102** [spring-projects/spring-boot#10386]
Have a recently bug in JPA: https://hibernate.atlassian.net/browse/HHH-11739 solutioned in lastest JPA version: https://mvnrepository.com/artifact/org.hibernate/hibernate-core/5.2.11.Final , i added the marven version in pom.xml (5.2.11.Fina) but make a conflict with jpa of spring boot starter data jpa. I using the lastest spring boot version (1.5.7.RELEASE) in pom.xml but have a same problem with quotes in definition columns: 

* https://stackoverflow.com/questions/46375086/howto-set-timestamp-type-of-a-column-using-jpa
* https://stackoverflow.com/questions/44363937/hibernate-5-0-12-wrong-column-definition-escape-with-mysql-5-7
* https://hibernate.atlassian.net/browse/HHH-11739

Need the fix of spring boot to continue develop my project please.

**Comment by philwebb** [comment]
The [following sample](https://github.com/spring-projects/spring-boot/blob/v1.5.7.RELEASE/spring-boot-samples/spring-boot-sample-hibernate52/pom.xml) shows how to switch to Hibernate 5.2. You should be able to change the POM to reference 5.2.11.

If that doesn't work for you, could you please provide a small sample application that shows the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
