### ISSUE TITLE
Reinstate deployment tests when building with Java 9

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10414]
Once Cargo 1.6.5 or 1.7.0 has been released (containing a fix for [CARGO-1441](https://codehaus-cargo.atlassian.net/browse/CARGO-1441)), we should try to reinstate the deployment tests when building with Java 9.

**Comment by mbhave** [comment]
@wilkinsona I think this is done?

**Comment by wilkinsona** [comment]
Looks like it still needs to be done to me. Cargo's configured in a [JDK 1.8 profile](https://github.com/spring-projects/spring-boot/blob/40fd8888b2641debebdbb133be285df9cb3b7177/spring-boot-tests/spring-boot-deployment-tests/spring-boot-deployment-test-tomcat/pom.xml#L50). New Cargo releases are available though so I don't think this is blocked any more.
