### ISSUE TITLE
Default Tomcat configuration should support IPv6 address

### ISSUE THREAD

**Issue by gbotka** [spring-projects/spring-boot#10419]
The default spring boot property for `server.tomcat.internal-proxies` only matching IPv4 addresses.  This regexp filter should be changed to whitelist IPv6 addresses also.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but Spring Boot's default is deliberately aligned with the default of Tomcat's Remote IP valve.

**Comment by candrews** [comment]
Reported to Tomcat at https://bz.apache.org/bugzilla/show_bug.cgi?id=62389 to adding the IPv6 loopback address.
