### ISSUE TITLE
Spring boot config server - ClassNotFoundException: org.springframework.boot.SpringApplication

### ISSUE THREAD

**Issue by msathe-tech** [spring-projects/spring-boot#10420]
Im trying to create a config server as per the documentation. I'm getting following error when I start the application - 
ClassNotFoundException: org.springframework.boot.SpringApplication

The code is available at -
https://github.com/msathe-tech/config-server

**Comment by philwebb** [comment]
Spring Config Server is developed as part of Spring Cloud. You can find the issue tracker [here](https://github.com/spring-cloud/spring-cloud-config/issues).

If I were to guess, I'd say you probably have a corrupt jar in your Maven repo. Try running `dependency:purge-local-repository` and then building the project again.

**Comment by msathe-tech** [comment]
I tried purge-local-repository. I'm getting following error when I tried mvn clean package

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[3,32] package org.springframew
ork.boot does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[4,46] package org.springframew
ork.boot.autoconfigure does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[8,2] cannot find symbol
  symbol: class SpringBootApplication
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[12,17] cannot find symbol
  symbol:   variable SpringApplication
  location: class com.config.configserver.ConfigServerApplication

**Comment by philwebb** [comment]
It looks like you've raised this issue again in #10421. Please follow the suggestions in https://github.com/spring-projects/spring-boot/issues/10421#issuecomment-331961487
