### ISSUE TITLE
package org.springframew ork.boot does not exist

### ISSUE THREAD

**Issue by msathe-tech** [spring-projects/spring-boot#10421]
I tried purge-local-repository. Code is available at - https://github.com/msathe-tech/config-server
I'm getting following error when I tried mvn clean package

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[3,32] package org.springframew
ork.boot does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[4,46] package org.springframew
ork.boot.autoconfigure does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[8,2] cannot find symbol
symbol: class SpringBootApplication
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[12,17] cannot find symbol
symbol: variable SpringApplication
location: class com.config.configserver.ConfigServerApplication

I tried purge-local-repository. Code is available at - https://github.com/msathe-tech/config-server
I'm getting following error when I tried mvn clean package

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[3,32] package org.springframew
ork.boot does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[4,46] package org.springframew
ork.boot.autoconfigure does not exist
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[8,2] cannot find symbol
symbol: class SpringBootApplication
[ERROR] /C:/stswork/workspace-sts-3.9.0.RELEASE/config-server/src/main/java/com/
config/configserver/ConfigServerApplication.java:[12,17] cannot find symbol
symbol: variable SpringApplication
location: class com.config.configserver.ConfigServerApplication

**Comment by wilkinsona** [comment]
Thanks for the sample. It works fine for me. I would guess that you have a problem with the Maven repository from which you're downloading the Spring Boot binaries. Perhaps you're behind a proxy which has cached a corrupted copy of the jar? There's nothing we can do here to help with your network / Maven repository problems unfortunately.
