### ISSUE TITLE
Very generic bean name "clock" in 2.0.0.M4

### ISSUE THREAD

**Issue by fprochazka** [spring-projects/spring-boot#10436]
Hi,
I've upgraded our app from `2.0.0.M3` to `2.0.0.M4` and it started reporting that bean of type `java.time.Clock` was not found and that I should define it. But I have it defined as shown in the following snippet and it worked correctly in `2.0.0.M3`

```
import java.time.Clock;

@Configuration
public class ServicesConfiguration
{
    @Bean
    public Clock clock()
    {
        return Clock.systemDefaultZone();
    }
}
```

It stopped working, because `org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleExportConfiguration` in `2.0.0.M4` defines bean with very generic name `clock` that replaced my definition. Took me a while to figure it out, but enabling debug logs of `org.springframework` helped.

I've already renamed my service, so it's not an issue for me anymore. But `clock` is a very generic name and I think it should be changed to something more specific.

**Comment by wilkinsona** [comment]
There are several other Micrometer configuration classes that declare a `Clock` bean named `clock`.

**Comment by fprochazka** [comment]
Thank you! :)
