### ISSUE TITLE
Drop auto-configured security for H2 console and DevTools remote start

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10435]
Knowing that the H2 console isn't enabled by default and 
following on from the simplification of security auto-configuration, trying to auto-configure its security no longer makes sense. We should drop it and users who choose to enable the console in an environment where security is required should secure it appropriately.

**Comment by mbhave** [comment]
`RemoteRestartWebSecurityConfigurer` in `RemoteDevToolsAutoConfiguration` can also go.

**Comment by heroInCommunity** [comment]
I still need to add header "X-Frame-Options: SAMEORIGIN" when using Spring Boot v2.0.0.RELEASE to make frames working (I see message "Sorry, Lynx not supported yet" as it is described in #7198).
Could you please confirm that fix was included in version 2.0.0.M5 ?

**Comment by wilkinsona** [comment]
@heroInCommunity Please see the [description of this issue](https://github.com/spring-projects/spring-boot/issues/10435#issue-261011295). What you have described is the expected behaviour and, if you really need to use the H2 console and have security enabled, you should configure it to meet your needs.

**Comment by heroInCommunity** [comment]
@wilkinsona , my fault, sorry for disturbing and thank you.
