### ISSUE TITLE
Investigate bindToCollectionWithNoDefaultConstructor

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10438]
Commit 4a740a16f3fe970e237c13fb18caa70970c08d9b change `CollectionBinder` to call 

```
bindIndexed(name, target, elementBinder, collection, ResolvableType.forClass(collectionType), elementType)
```

rather than 

```
bindIndexed(name, target, elementBinder, collection, target.getType(), elementType)`
```

This unfortunately means we loose any generic type information from `target.getType()`.

I've reworked the original commit but it now causes `CollectionBinderTests.bindToCollectionWithNoDefaultConstructor` to fail. This is because Spring's conversion service always tries to convert Collection -> Collection.

I'm not sure if we can or should do anything about this. Perhaps it's best just to make the binder always need a default constructor.

**Comment by snicoll** [comment]
> Perhaps it's best just to make the binder always need a default constructor.

Can you expand on what needs a default constructor please?

**Comment by mbhave** [comment]
@snicoll binding to a collection with no default constructor fails at the moment. For example, [this test](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/CollectionBinderTests.java#L323)

**Comment by snicoll** [comment]
Thanks. I think it's perfectly ok to require a default constructor for this.
