### ISSUE TITLE
Ability to configure auto-startup on a per @RabbitListener basis

### ISSUE THREAD

**Issue by dustinschultz** [spring-projects/spring-boot#10437]
This is a request for an Enhancement:

`@RabbitListener`'s are configured to auto start by default. It's possible to disable auto-start but it's an all-or-nothing change via the property: `spring.rabbitmq.listener.auto-startup=false`. 

The ability to configure on a per `@RabbitListener` basis whether or not it auto-starts would be a useful feature. It could be done via a Spring Boot property (e.g. `spring.rabbitmq.listener.<listener-name>.auto-startup=false`) in `RabbitProperties` with a `Map<String, Listener>`.

The only reasonably-clean (not really) way I could come up with was to configure a custom `containerFactory="rabbitContainerFactory"` on the `@RabbitListener` with an implementation like this:

```
@Bean
RabbitListenerContainerFactory<SimpleMessageListenerContainer> rabbitContainerFactory(ConnectionFactory rabbitConnectionFactory)
{
    SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory()
    {
        @Override
        protected void initializeContainer(final SimpleMessageListenerContainer instance)
        {
            super.initializeContainer(instance);
            instance.setAutoStartup(false);
        }
    };

    factory.setConnectionFactory(rabbitConnectionFactory);
    return factory;
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I think this really needs to be driven by an enhancement request against Spring AMQP. There then may be nothing for Boot to do. If it turns out there is something that we'd need to do, we can re-open this.

**Comment by dustinschultz** [comment]
Thanks - I'll bring it up via spring-amqp.
