### ISSUE TITLE
Make /metrics response compatible with ElasticSearch

### ISSUE THREAD

**Issue by punkstarman** [spring-projects/spring-boot#10449]
Currently if you try to use the new [MetricBeat HTTP module](https://www.elastic.co/guide/en/beats/metricbeat/6.0/metricbeat-module-http.html) to send metrics produced by Spring Boot Actuator's `/metrics` endpoint, you get a few errors. This is because a few metrics have summary keys (e.g. `mem`) and details keys (e.g. `mem.free`), and because ElasticSearch interprets JSON keys that contain dots as fields of embedded objects. So, for instance, ElasticSearch stores a scalar value in the `mem` field of the document and then tries to store another scalar in the `free` sub-field of the `mem` field, which is not allowed since `mem` is not an object but a scalar.

A [blog article](https://blog.mimacom.com/blog/2017/01/20/spring-microservices-monitoring-metrics-endpoint-and-elk/) explains the situation in more detail, and also demonstrates a rather complex solution.

It seems to me that adding a suffix such as `.total` to all metrics whose names are prefixes of other metrics would fix this, while making things clearer. For example, what does `mem` represent? A maximum, a total, the 95th percentile, ...?

**Comment by wilkinsona** [comment]
We can't change the keys in 1.5 as it would be a breaking change and the metrics endpoints has been completely overhauled in 2.0 as part of the move to Micrometer-based metrics. Can you please try with 2.0 and see if the names meet your needs? If they don't then we could look at making the `HierarchicalNameMapper` that's used by `MetricsEndpoint` configurable. Alternatively, you could write your own endpoint that meets the specific needs of the MetricBeat HTTP module.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by punkstarman** [comment]
I've been trying to evaluate Spring Boot Actuator 2.0.0.M4. It is obvious that one of the goals was catering to a wider range of use cases, and the price for that is more complexity.

From what I have seen of the `/application/metrics/{metric}` endpoints, most metrics keys are compatible with MetricBeat. One key that is a problem is in the `process.starttime` tag. Sending a `GET` request to `/application/metrics/process.starttime` yeilded the following JSON document during my tests:

```json
{
	"processStarttime.": [
		{
			"statistic": "Value",
			"value": 1.507705727859E9
		}
	]
}
```

The `processStarttime.` key ends with a period (`.`).

**Comment by wilkinsona** [comment]
The trailing `.` is odd and unexpected. It does not occur with the latest 2.0 snapshots where the response now has this form:

```
{
    "availableTags": [],
    "measurements": [
        {
            "statistic": "Value",
            "value": 1.507722975021e+18
        }
    ],
    "name": "process.starttime"
}
```

/cc @jkschneider

**Comment by jkschneider** [comment]
@wilkinsona @punkstarman My suggestion here is that we support MetricBeat as a registry implementation in Micrometer, where we can cater specifically to its expected exposition format rather than trying to shoehorn it into the /metrics endpoint. 

MetricBeat's periodic scraping is very similar to Prometheus' default mode of operation, where we expose an actuator endpoint with metrics in the format Prometheus expects.

To this end, see https://github.com/micrometer-metrics/micrometer/issues/154.

**Comment by wilkinsona** [comment]
Sounds good to me. Thanks, @jkschneider. I'll close this one in favour of  micrometer-metrics/micrometer#154 as changing the output of the metrics endpoint, as requested here, isn't what we want to do. Once the Micrometer issue has been addressed we can open a new Boot issue to make any changes in Boot that may be necessary.
