### ISSUE TITLE
Upgrade to a Liquibase version that's compatible with Java9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10442]
Liquibase does not work with Java9 yet. I've created [CORE-3114](https://liquibase.jira.com/browse/CORE-3114)

**Comment by candrews** [comment]
It appears they're making commits relevant to this issue: https://github.com/liquibase/liquibase/pull/688

And here's the PR that I believe would complete the fix: https://github.com/liquibase/liquibase/pull/740

🤞 they make a release with these fixes in it soon!

**Comment by snicoll** [comment]
Duplicate of #12140
