### ISSUE TITLE
Review if we need AuthenticationManagerConfigurationListener

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10446]
I can't remember why `AuthenticationManagerConfiguration.AuthenticationManagerConfigurationListener` was added but it seems like we might be able to remove it and just wire up `InMemoryUserDetailsManager` directly and make `setAuthenticationEventPublisher` a user problem if they wire up their own.

**Comment by wilkinsona** [comment]
It was added in [this commit](https://github.com/spring-projects/spring-boot/commit/9902f98a3d2514f2b7808a5de5dce0b0de6ed3e9) that fixed https://github.com/spring-projects/spring-boot/issues/1556. The configuration of the event publisher was added in [this commit](https://github.com/spring-projects/spring-boot/commit/5e3cc95ccff09b7d10e176ad355e1c029ecd9d97) but it's not immediately apparent why that was done as it's not mentioned in the commit comment or the related issue.

**Comment by philwebb** [comment]
Let's remove it in 2.0 and see who shouts. We can always restore it before GA.

**Comment by mbhave** [comment]
We used to create an `AuthenticationManager` bean. I guess now that we don’t do that and instead provide a `UserDetailsService` bean, removing the listener from auto-config should be fine. Users providing their own  `AuthenticationManager`, can setup their own listener.
