### ISSUE TITLE
Live reload does not work with Kotlin

### ISSUE THREAD

**Issue by jrempel1** [spring-projects/spring-boot#10462]
Environment:
Spring: 2.0.0.M4
spring-boot-devtools

Instructions to reproduce:
- Spring boot project with Kotlin
- Create sample controller file
- Start server with gradle bootRun
- Modify Kotlin file
- Observe output with curl http://localhost:8080
- Restart server
- Observe correct output with curl http://localhost:8080

On startup the following was output in logs:
23:58:06.610 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/Users/jrempel/IdeaProjects/weather/build/classes/kotlin/main/, file:/Users/jrempel/IdeaProjects/weather/build/resources/main/]

**Comment by wilkinsona** [comment]
What do you expect to compile the Kotlin file that you have modified? To where is it writing the resulting class file(s)?

**Comment by jrempel1** [comment]
@wilkinsona good question. investigating that inquiry further led to a resolution

Using the default configuration gradle compiles to build, intellij was compiling to out. Running gradle classes recompiled the code and restarted the server automatically as expected.
