### ISSUE TITLE
Rationalize check location behaviour for Flyway and Liquibase

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#10464]
Currently, by default Flyway has `checkLocation` property equals to `false` and Liquibase has `checkChangeLogLocation` with `true`. Do you think they should share the same behaviour about checking locations?

The reason behind this, I have worked in a [feature](https://github.com/eddumelendez/spring-boot/tree/liquibase_vendor_location) to support resolution for `{vendor}` in `LiquibaseAutoConfiguration` and I realized that `checkChangeLogLocation` was `true` which makes me disable the check location in my test.

May related to #10387 about support checking vendor location.

**Comment by wilkinsona** [comment]
Well spotted, @eddumelendez. I can see no reason for the default checking behaviour not to be consistent. It should probably be `true` in both cases. Flyway itself fails slightly later on if it doesn't find any migration scripts. @mbhave also suggested making the property names consistent (they could both be `checkLocation`).

**Comment by izeye** [comment]
Duplicate of #10807 ?

**Comment by eddumelendez** [comment]
Close because it was merged in https://github.com/spring-projects/spring-boot/commit/dcc6d8d6ffb257b454fc6b9986e09a8046808282
