### ISSUE TITLE
Make TomcatEmbeddedWebappClassLoader parallel capable

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10477]
With reference to [DATAMONGO-1792](https://jira.spring.io/browse/DATAMONGO-1792), the synchronization of `TomcatEmbeddedWebappClassLoader.loadClass(String, boolean)` is inefficient. Rather than making the method itself `synchronized` it should synchronize on the response from `(getClassLoadingLock(className)`. We should also verify that the JVM considers the class loader to be parallel capable (its superclass is registered as such).

**Comment by wilkinsona** [comment]
There's no benefit to making the change proposed above. The super class, `org.apache.catalina.loader.WebappClassLoader`, is not parallel capable so `TomcatEmbeddedWebappClassLoader` cannot be parallel capable.

**Comment by wilkinsona** [comment]
As pointed out in DATAMONGO-1792, we could subclass `ParallelWebAppClassLoader` instead. That would be a breaking change, though, is it could only happen in 2.0.

**Comment by wilkinsona** [comment]
Hmm, Tomcat 8.5 uses the parallel capable class loader by default so we're unintentionally out of line with Tomcat's defaults here. We could make this change in 1.5.x while avoiding the problem with the breaking change to the type hierarchy by introducing a new `TomcatEmbeddedParallelWebAppClassLoader` and using that by default. It would, however, still be a breaking change for anyone who was getting hold of the class loader and expecting it to be a `TomcatEmbeddedWebappClassLoader` or a `WebappClassLoader`.

**Comment by philwebb** [comment]
My vote would be 2.0, then backport if anyone really grumbles hard.
