### ISSUE TITLE
JolokiaMvcEndpoint.afterPropertiesSet() is called twice

### ISSUE THREAD

**Issue by ArloL** [spring-projects/spring-boot#10479]
I am opening this issue with reference to [SPR-16027](https://jira.spring.io/browse/SPR-16027). While debugging a ClassLoader leak when using spring-boot-actuator I noticed that ``JolokiaMvcEndpoint.afterPropertiesSet()`` is called twice. This results in two ``AgentServlet`` instances being created by ``ServletWrappingController.afterPropertiesSet()``.

These are the corresponding stack traces to the two calls:

![image](https://user-images.githubusercontent.com/195367/31072574-c372cfc4-a768-11e7-8bb3-fd562bb2d4a4.png)

![image](https://user-images.githubusercontent.com/195367/31072584-cd620536-a768-11e7-81a3-9094235f9df8.png)

**Comment by snicoll** [comment]
It is called twice because  `JolokiaMvcEndpoint` is a `@ConfigurationProperies` annotated type and @ArloL is using the rebincder feature of Spring Cloud.

**Comment by wilkinsona** [comment]
I'm surprised that `destroy` apparently isn't called between the two calls to `afterPropertiesSet`.

**Comment by wilkinsona** [comment]
I believe this is a bug in Spring Cloud. `ConfigurationPropertiesRebinder` [initializes the bean](https://github.com/spring-cloud/spring-cloud-commons/blob/942df8ed4508fe8876f2b655e401db73b79ae2f3/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java#L106-L107) without destroying it first. This breaks the any bean that implements `InitializingBean` and `DisposableBean` and assumes that initialisation and destruction will occur as pairs. I've opened https://github.com/spring-cloud/spring-cloud-commons/issues/268.
