### ISSUE TITLE
Spring Security Principal missing from 4xx responses

### ISSUE THREAD

**Issue by saschaszott** [spring-projects/spring-boot#1048]
Hi folks,

today I came across a strange behavior when using Spring Boot in conjunction with Spring Security and a custom error page setting.

My `WebApplicationConfiguration` class (which extends `WebMvcConfigurerAdapter`) defines a `EmbeddedServletContainerCustomizer` bean:

``` java
@Bean
public EmbeddedServletContainerCustomizer containerCustomizer() {
   return (container -> container.addErrorPages(
                new ErrorPage(HttpStatus.BAD_REQUEST, "/4x"),
                new ErrorPage(HttpStatus.UNAUTHORIZED, "/4xx"),
                new ErrorPage(HttpStatus.FORBIDDEN, "/4xx"),
                new ErrorPage(HttpStatus.NOT_FOUND, "/4xx"),
                new ErrorPage(HttpStatus.METHOD_NOT_ALLOWED, "/4xx"),
                new ErrorPage(HttpStatus.INTERNAL_SERVER_ERROR, "/5xx")));
}
```

The path `/4xx` (and `/5xx` as well) is handled by the following controller:

``` java
@Controller
public class ErrorPageController {

   private static final Logger LOG = Logger.getLogger(ErrorPageController.class.getName());

   @RequestMapping(value = { "/4xx", "/5xx" })
   public String handleError(HttpServletRequest request, ModelMap map) {
      String name = request.getUserPrincipal() != null ? request.getUserPrincipal().getName() : "NULL";
      LOG.warn("user name is " + name);

     …
   }
}
```

Within the controller method `handleError` I'm trying to get the name of the successfully authenticated user.

If I'm running the application (as a JAR file) with an embedded application server (Tomcat 7.0.52) the following output can be found in the log file

```
WARN [de.szott.mybootapp.web.controller.ErrorPageController.handleError:65] - user name is NULL
```

If I'm running the application (as a WAR file) in a standalone Tomcat (same version) the log file states

```
WARN [de.szott.mybootapp.web.controller.ErrorPageController.handleError:65] - user name is johndoe
```

Does anybody have a clue on how to fix this? Please note, that it's crucial for me to get the user name in the controller method since I want to output the name in the view (which is a Thymeleaf template in my case). Thanks!

**Comment by Quantas** [comment]
I also notice this behavior in Spring Boot 1.2.3 running an embedded Tomcat container.  Are there any workarounds? Or does anyone have any ideas for a code change that I could work quick?

**Comment by todoubaba** [comment]
Same problem in grails 3.0.1.

**Comment by php-coder** [comment]
>Are there any workarounds? Or does anyone have any ideas for a code change that I could work quick?

I'm not sure is this a bug or not, because it [described in documentation][1] (but there is no words about Sprig Security):


>N.B. if you register an ErrorPage with a path that will end up being handled by a Filter (e.g. as is common with some non-Spring web frameworks, like Jersey and Wicket), then the Filter has to be explicitly registered as an ERROR dispatcher (the default FilterRegistrationBean does not include the ERROR dispatcher type).

This is how I've fixed it for myself:

```java
// TODO: remove @Qualifier and inject by type
// See for details: https://github.com/spring-projects/spring-boot/issues/2774
@Bean
public FilterRegistrationBean getSpringSecurityFilterChainBindedToError(
                @Qualifier("springSecurityFilterChain") Filter springSecurityFilterChain) {

        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(springSecurityFilterChain);
        registration.setDispatcherTypes(EnumSet.allOf(DispatcherType.class));
        return registration;
}
```

[1]: http://docs.spring.io/spring-boot/docs/1.2.3.RELEASE/reference/htmlsingle/#boot-features-error-handling

**Comment by Quantas** [comment]
I would consider it a bug, but the workaround is alright, I suppose...

**Comment by rocketraman** [comment]
I have a similar issue -- I am using embedded Undertow and forward to an error controller via the `EmbeddedServletContainerCustomizer`. But I also have a custom filter defined in my Spring Security config that does token-based authentication.

Unfortunately, adding the workaround described in https://github.com/spring-projects/spring-boot/issues/1048#issuecomment-102456237 doesn't work for me: it causes my token filter to execute not only on the initial request but also on the dispatch to the error controller. If the problem that caused the error is with the token itself, this of course causes the error handler to fail with another exception.

I tried working around the above by adding an exception to the token filter that checks the request to see if it is an error dispatch, and forwarding the request normally if so. However, the request never gets to my error controller (I'm not sure where it is being handled).

**Comment by rocketraman** [comment]
This all seems very hackish. Rather than trying to maintain the security context for the error handler, I think in most cases, error handlers will simply want the original security context for logging and auditing. For such use cases, just passing the original security context through as an attribute from `DefaultErrorAttributes` would work well.

**Comment by cemo** [comment]
There were some discussion on this topic in #4505 and #4739. I believe that the default configuration should be changed.

Current Configuration:
 
```
static final EnumSet<DispatcherType> ASYNC_DISPATCHER_TYPES = EnumSet.of(
            DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST,
            DispatcherType.ASYNC);

    static final EnumSet<DispatcherType> NON_ASYNC_DISPATCHER_TYPES = EnumSet
            .of(DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST)

```

What I am proposing is that replacing `INCLUDE` with `ERROR`. This seems more sensible to me. Issues like this are suffering from default configurations. 

ping @philwebb

**Comment by olle** [comment]
Hi, I've been playing around with a small project to reproduce the issue - [https://github.com/olle/no-auth-for-you](https://github.com/olle/no-auth-for-you). Perhaps it might come in handy.

**Comment by sasiperi** [comment]
I would not think this as a bug per Spring docs: (like php-coder  mentioned above)
http://docs.spring.io/spring-boot/docs/1.2.3.RELEASE/reference/htmlsingle/#boot-features-error-handling.
Rather a feature. And the fix explained in the above docs worked like a Charm. It's able to pass in the Authentication in the SecurityContext and we can see Principal etc.. on error pages now.

**Comment by wilkinsona** [comment]
The security filter now runs by default on error dispatches: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#spring-security
