### ISSUE TITLE
Configuration meta data for custom data types

### ISSUE THREAD

**Issue by vavrfam** [spring-projects/spring-boot#10493]
Question
We have custom data types that works well in pretty much every scenario except when writing the custom property configuration to `spring-configuration-metadata.json`

In the following example `Seconds` is our custom data type , toString on this would return `66 D` per our logic. 

```    private Seconds days = Seconds.ofDays(66);```

when spring boot generates configuration meta-data, it is writing the value as `66`. 
Which is a problem, because our default unit is `Seconds`. 
How can I get this to write toString() version of` Seconds.ofDays(66)` ? 

Thank you!!

**Comment by snicoll** [comment]
It is a limitation of the annotation processor. The conversion service is able to convert your input value automatically if the data type has a constructor that takes a `String` value. If you don't have that I guess you had to write a `Converter` as well.

Regardless, `Seconds.ofDays(66)` is not a proper default value. It has to be the string representation of 66 days. So you should write that in your code (my best guess is that a proper default value for this could be `5702400`.

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you have more questions ask on StackOverflow or come talk to us on Gitter.
