### ISSUE TITLE
CommonOAuth2Provider default redirectUrl should reference registrationId

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#10505]
The following constant is defined in `CommonOAuth2Provider`:

`private static final String DEFAULT_REDIRECT_URL = "{scheme}://{serverName}:{serverPort}{contextPath}/oauth2/authorize/code/{clientAlias}`

`{clientAlias}` should be changed to `{registrationId}`

`private static final String DEFAULT_REDIRECT_URL = "{scheme}://{serverName}:{serverPort}{contextPath}/oauth2/authorize/code/{registrationId}`

**Comment by philwebb** [comment]
See also https://github.com/spring-projects/spring-security/issues/4597
