### ISSUE TITLE
BackgroundPreinitializer hangs if there is an ApplicationFailedEvent at startup

### ISSUE THREAD

**Issue by ipavkovic** [spring-projects/spring-boot#10509]
There is a race condition in org.springframework.boot.autoconfigure.BackgroundPreinitializer

Due to a thrown exception in our logging setup the method onApplicationEvent receives the following events:
- ApplicationStartedEvent
- ApplicationFailedEvent

The thread is put to sleep, the application hangs.

a possible fix is to change the line
`
				preinitializationComplete.await();
`
to
`
				if (preinitializationStarted.get()) {
					preinitializationComplete.await();
				}
`

**Comment by wilkinsona** [comment]
Duplicate of #10362
