### ISSUE TITLE
Get eclipse setup working with the new build structure

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10517]

**Comment by snicoll** [comment]
@philwebb do we still need to do this?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
