### ISSUE TITLE
Enable the metrics endpoint by default

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10525]
This was proposed in #10519 but I think it warrants separate consideration. The metrics endpoint in 1.5 was considered to be sensitive which, in the 2.0 model, maps to the endpoint not being enabled by default.

**Comment by snicoll** [comment]
Why would we change our opinion about this? This is sensitive data right?

**Comment by wilkinsona** [comment]
Right. Hence this issue rather than just changing it as part of the PR.

**Comment by wilkinsona** [comment]
@jkschneider is happy for the endpoint to be disabled by default.
