### ISSUE TITLE
Provide auto-configuration for exporting Micrometer metrics to StatsD

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10522]

**Comment by ryonday** [comment]
I am trying to use `yml` configuration for StatsD and Micrometer, but it appears to be discouraged to set host and port information? I am extremely confused here. In [additional-spring-configuration-metadata.json](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L1191) the statsd host, port and prefix configurations are marked as deprecated but there appears to be no replacement option anywhere that I can tell.

**Comment by snicoll** [comment]
@ryonday this issue is closed and we don't use the tracker for questions. If you have a question, please ask on StackOverflow or join us on Gitter.

**Comment by snicoll** [comment]
@ryonday actually, that's a left over from the deprecation work for 1.5 that clashes with new keys. I've created #11015
