### ISSUE TITLE
Allow @AutoConfigureWebTestClient to have a custom timeout

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10555]
Some of our current builds fail due to timeout issues. It would be nice to offer a way to customize the timeout.

**Comment by philwebb** [comment]
The `SampleSecureWebFluxApplicationTests` is one example of a test that often fails.

**Comment by philwebb** [comment]
I've pushed a fix in a9263998a179e6e4a7ea54440c12c712ce353ad8 but it's not currently applied due to #10556. I'll leave this one open until we decide what to do with #10556.

**Comment by snicoll** [comment]
@philwebb if you want this to be in 2.0 then #10556 should be as well IMO.

**Comment by wilkinsona** [comment]
The timeouts turned out to be due to a Reactor Netty bug so the immediate need for this has gone. We can consider adding something in the future if the needs arises again.
