### ISSUE TITLE
Potential Bug: data.sql imports twice

### ISSUE THREAD

**Issue by MatthewEdge** [spring-projects/spring-boot#10563]
Using the latest `1.5.7.RELEASE` the `data.sql` script seems to be executing twice

Steps to reproduce:

1. Spring Initializer -> Maven + Java 1.8 + Boot 1.5.7.RELEASE
    - Select `Web Services`, `JPA`, `H2`, and `ActiveMQ`
    - Generate
2. Add a `schema.sql` and a `data.sql`. Schema file is only create/alter table statements. Data file is one `CREATE VIEW` statement and a bunch of INSERT statements
3. Create two properties files: `application.properties` and `application-local.properties`
4. Add `@ActiveProfiles("local")` to the `contextLoads` test, run, and you should see the following output:

```
2017-10-09 10:18:23.485 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/schema.sql] 
2017-10-09 10:18:23.568 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/schema.sql] in 83 ms. 
2017-10-09 10:18:23.571 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/data.sql] 
2017-10-09 10:18:23.571 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/data.sql] 
2017-10-09 10:18:23.582 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/data.sql] in 10 ms. 
2017-10-09 10:18:23.583 INFO  --- o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/Users/medge/code/boot-jpa-debug/target/classes/data.sql] in 11 ms. 
```

The test will eventually fail because the CREATE VIEW statement is run twice. (the CREATE VIEW is in data.sql because we auto-generate schema.sql and the view is overwritten in that process)

Contents of properties files:

application.properties

```
# Database Configuration
spring.datasource.initialize=false
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
```

application-local.properties
```
## Datasource Config
spring.datasource.initialize=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

## JMS configuration
spring.activemq.broker-url=vm://localhost?broker.persistent=false&broker.useJmx=false&broker.useShutdownHook=false
spring.activemq.in-memory=true
spring.activemq.packages.trust-all=true
```

It also manifests data uniqueness problems if `continue-on-error=false` is used.

**Comment by philwebb** [comment]
@MatthewEdge Since you've probably already gone though the steps to reproduce locally, are you able to share that project on GitHub to save us some time?

**Comment by MatthewEdge** [comment]
Sure! I can upload that here shortly once I get back to my desk

**Comment by MatthewEdge** [comment]
I have uploaded the sample project [here](https://github.com/MatthewEdge/boot-jpa-test) and also made a rather strange discovery (and realized an omission from above):

We have the following configuration class in our non-Boot project:

```
@Configuration
public class AsynchronousSpringEventsConfig {

	@Bean(name = "applicationEventMulticaster")
	public ApplicationEventMulticaster simpleApplicationEventMulticaster() {
		SimpleApplicationEventMulticaster eventMulticaster = new SimpleApplicationEventMulticaster();
		eventMulticaster.setTaskExecutor(new SimpleAsyncTaskExecutor());
		return eventMulticaster;
	}
}
```

We added this to implement a pseudo-async-event-publisher service within our app. I realized I copied this class over by mistake, deleted it, and the duplicate `data.sql` issue went away. If I add it back the issue returns.

Thoughts?

**Comment by philwebb** [comment]
The logic to work out when to run the SQL scripts is quite involved. There are a number of different routes to get to it depending on if you're using hibernate or not. I guess we just never accounted for an asynchronous `ApplicationEventMulticaster`.

We're trying to refine some of this logic in 2.0, so if you can get away without the asynchronous multicaster that would be best for now.

**Comment by MatthewEdge** [comment]
We can re-eval. We were pushing for a Boot conversion for this project and this was the last item to dig through. Can probably look into an alternative to the `ApplicationEventMulticaster` if we get the go-ahead.

Thank you!

**Comment by philwebb** [comment]
Unfortunately we don't think the added complexity required to deal with an asynchronous multicaster is worth it. Our recommendation is to move to the regular `ApplicationEventMulticaster`.

**Comment by MatthewEdge** [comment]
Definitely understandable. Thanks for the response! Will post our workaround a but later in case others pop in with similar issues
