### ISSUE TITLE
Include error body on Bad HTTP error code on wrong logging level

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10568]
See issue #8798 and PR #8813 and [this comment](https://github.com/spring-projects/spring-boot/issues/8798#issuecomment-335147964):

>... the HTTP 400 response does not contain a body anymore which makes it impossible to understand the reason why the request has failed.
>
> IMO, the error response should contain a reason for the error, similar to the message of the initial HTTP 500 error.

**Comment by eddumelendez** [comment]
@philwebb should it be based on branch `1.5.x` or `master`?

**Comment by philwebb** [comment]
Closing in favor of PR #10588. Thanks again @eddumelendez !!

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/10618 to do something more general purpose in the web endpoint infrastructure for 2.0.
