### ISSUE TITLE
.properties loaded using system default encoding, instead of  ISO 8859-1

### ISSUE THREAD

**Issue by thiagohirata** [spring-projects/spring-boot#10564]
The `org.springframework.boot.env.OriginTrackedPropertiesLoader` class, used for loading `.properties` files as property sources, should initialize its `InputStreamReader` with the `ISO 8859-1` charset for reading this type of file, undoing the fix done for #5361.

**Comment by philwebb** [comment]
Closing in favor of PR #10565
