### ISSUE TITLE
Remove unused and misleading setters on ConfigurationPropertiesBindingPostProcessor

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10598]
`ConfigurationPropertiesBindingPostProcessor` currently has a number of setter methods that aren't used by Boot itself and that provide misleading indications of its capabilities. For example, `setPropertySources(Iterable<PropertySource>` suggests that the property sources can be set at any time. This, however, is not the case as calling the setter will only have an effect up until `afterPropertiesSet` is called.

The following setter methods should be removed to more accurately reflect the post-processor's capabilities and intended usage:

- `setOrder(int)`
- `setPropertySources(Iterable<PropertySource>`
- `setValidator(Validator)`
- `setConversionService(ConversionService)`

To give time for adaptation to these changes this issue will deprecate the setters and a separate issue will remove them prior to Boot 2.0 reaching the release candidate phase. See #10460 for a related issue where we're now moving towards Spring Cloud leaving `ConfigurationPropertiesBindingPostProcessor` alone and using a slightly enhanced `ConfigurationPropertiesBinder` and its own `@RefreshableConfigurationProperties` annotation instead.

**Comment by snicoll** [comment]
@wilkinsona I thought we finally opt for removing those setters right now. Have I misunderstood?

**Comment by wilkinsona** [comment]
You haven’t misunderstood so I’ve just retitled the issue. At the risk of stating the obvious, we shouldn’t remove anything till #10685 is complete.
