### ISSUE TITLE
Fix package tangles

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10592]
![screen shot 2017-10-10 at 9 57 31 pm](https://user-images.githubusercontent.com/519772/31422955-2b3c8700-ae06-11e7-8991-722bdb09c3e6.png)

**Comment by teriiehina** [comment]
hi @philwebb. Sorry as this is not a contributing comment, I would like to know if the image you posted was computer-generated ? if yes, which software did you use ?

**Comment by eddumelendez** [comment]
@teriiehina it is structure101 http://structure101.com/ I also did my research 😁

**Comment by teriiehina** [comment]
Thank you @eddumelendez  :+1:
