### ISSUE TITLE
Add configuration option for Tomcat's "useRelativeRedirects" property

### ISSUE THREAD

**Issue by dhay** [spring-projects/spring-boot#10597]
In Spring Boot 1.5.4, when using Tomcat 8.0.30 or later, the `TomcatEmbeddedServletContainerFactory` sets the Tomcat context property `useRelativeRedirects` to `false`.  I would like a configuration option (e.g. `server.tomcat.useRelativeRedirects=true`) to change this hard-coded default.

My scenario is this: I have a Spring boot application sitting behind a load balancer VIP. SSL is also terminated at the load balancer.  With relative redirects set to `false`, the URL sent back from a redirect has both the wrong host (i.e. the host name, not the VIP) as well as the wrong scheme (http instead of https).  

I know I can register `TomcatContextCustomizer`, but that seems like a lot of code for a single boolean value.

Thanks!

**Comment by jimbase16** [comment]
FWIW -- I got around this with:

```
@Configuration
public class TomcatConfiguration {
    @Bean
    public EmbeddedServletContainerFactory servletContainer() {
        return new RelativePathEmbeddedTomcat();
    }

    private class RelativePathEmbeddedTomcat extends TomcatEmbeddedServletContainerFactory {
        RelativePathEmbeddedTomcat() {
            super();
        }

        @Override
        protected void postProcessContext(Context context) {
            context.setUseRelativeRedirects(true);
        }
    }
}
```

You could always add a `@Value` binding if you wanted to make it configurable for the time being.

**Comment by dhay** [comment]
@jimbase16 , that's essentially what I ended up doing for now.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Seems reasonable, particularly as we already have a property for setMapperContextRootRedirectEnabled.
