### ISSUE TITLE
Add possibility to use JKS for RabbitMq SSL Keystore

### ISSUE THREAD

**Issue by roasher** [spring-projects/spring-boot#10600]
Following this one https://github.com/spring-projects/spring-amqp/issues/436 your colleagues have provided getter and setter to storeType.
But the point is that now there is no chance to set it other than create custom `ConnectionFactory` cause of `@ConditionalonMissingbean(ConnectionFactory.class)` in `RabbitAutoConfiguration` class.
It would be nice to have an ability to change it using properties file
smth like other ssl props: spring.rabbitmq.ssl.storeType

**Comment by wilkinsona** [comment]
Duplicate of #10251
