### ISSUE TITLE
Allow @WriteOperation endpoints to be invoked without a payload

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10602]
From @dsyer on Slack

> So `@joshlong` and I noticed this morning that Boot 2.0 `@WriteOperation` only consumes JSON (even though it's quite common to have POSTable endpoints that accept no inputs).
> I thought I had seem some code somewhere that convinced me they accepted form inputs as well. But I can't find that when I look in snapshots.
> E.g. you used to be able to `curl localhost:8080/shutdown -d {}`, but now you get a 415 "Unsupported Media Type" (from /application/shutdown obviously).

**Comment by dsyer** [comment]
Since the basic model for processing method parameters in a `@WriteOperation` is `name=value`, it seems like in the interests of continuity we should be able to support form-based input (and query params for servlet-based endpoints?) as well.

**Comment by wilkinsona** [comment]
I think this is already possible:

```
curl -X POST localhost:8080/application/shutdown
```

Does that not work? An endpoint that doesn't consume anything (for example a write with no parameters) [shouldn't have any consumes constraints in its mapping](https://github.com/spring-projects/spring-boot/blob/ff02d70ed4cdb6bd92168ef2ded27b94c2107a27/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/annotation/WebAnnotationEndpointDiscoverer.java#L177).

**Comment by dsyer** [comment]
It does work, thanks, although I'm not sure it's accurate to say there are no consumes constraints, because it sends a 415 if you send any content at all. Isn't that violating some form of Postel's Law (we should accept anything reasonable)?

There is also the question of the form-encoded name=value pairs as a feature that we removed in 2.0. Maybe we could add it back?

**Comment by philwebb** [comment]
> There is also the question of the form-encoded name=value pairs as a feature that we removed in 2.0. Maybe we could add it back?

I'd rather leave this out unless there's a really compelling use-case. Given that we're now supporting WebFlux, MVC and Jersey it's really best in my mind if we keep things as simple as possible.

**Comment by wilkinsona** [comment]
> Isn't that violating some form of Postel's Law (we should accept anything reasonable)?

I've never seen Postel's Law used as motivation for supporting different media types. In my experience it's typically used as an argument in favour of ignoring entries in a JSON payload or query parameters in a URL that aren't expected. I agree with that argument and that's how the endpoint infrastructure behaves today.

>> There is also the question of the form-encoded name=value pairs as a feature that we removed in 2.0. Maybe we could add it back?

> I'd rather leave this out unless there's a really compelling use-case. Given that we're now supporting > WebFlux, MVC and Jersey it's really best in my mind if we keep things as simple as possible.

Agreed. Adding back support for form-encoding would be undoing some of the work that we've done in 2.0 to provide a simpler and firmer foundation for future enhancements.

**Comment by wilkinsona** [comment]
POSTing to an endpoint with an empty body will be documented as part of #10001.
