### ISSUE TITLE
Webflux -Using @EnableWebFluxSecurity, the server blocks while trying to post big data at the second time

### ISSUE THREAD

**Issue by louisypchan** [spring-projects/spring-boot#10611]
I have created a class to implement AuthenticationEntryPoint to return a meaningful message if the request is not authencatied like below:

```java
    @Override
    public Mono<Void> commence(ServerWebExchange exchange, AuthenticationException e) {
        String result = String.format("{\"code\":\"%s\",\"message\": \"%s\"}", "401", e.getMessage());
        ServerHttpResponse response = exchange.getResponse();
        response.setStatusCode(HttpStatus.OK);
        response.getHeaders().set(HttpHeaders.CONTENT_TYPE, "application/json");
        return response.writeWith(Mono.just(response.bufferFactory().allocateBuffer().write(result.getBytes())));
    }
```

then I tried to post a data like below:

```
/9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iy...b9QUUTTBfc5n5v2RM9j6Y+L9lFE0xopeytJnxfst9DgNKnsoolrUjfS4eynoFpZQaNFFFztakMDQrhRRBIUUUQf/2Q==
```

First time, I got a json message to indicate the request was invalid, but when I tried to post same data again, the server(netty) seems to be blocked by something, hang there with no response,  but if I cancel the request and post again, then I got a right message as the first time.

**Comment by bclozel** [comment]
This is not clear to me.
Could you create a small sample application that demonstrate the issue?

**Comment by louisypchan** [comment]
@bclozel  I have made a sample application here:  https://github.com/louisypchan/issue-10611
try to post data I metioned before multiple times then you can reproduce the issue I described.

ps: if change to use undertow instead of netty, everyting seems alright.

**Comment by louisypchan** [comment]
I just put the test data into the project in case you can't get the fully data

**Comment by bclozel** [comment]
I can't reproduce the issue you're describing, as I'm always getting the 401 response when using a curl command like:

`curl --data-binary "@issue-10611/TestData.txt" http://localhost:8080/demo/spring`

Your sample is not minimal nor represent a valid use case in my opinion: you've copied/pasted Spring Security's `HttpSecurity` and your `CustomHttpBasicAuthenticationEntryPoint` always returns an error, no matter what the authentication process looks like.

Please reopen this issue with more details, as minimal as possible, and a consistent way to reproduce this.

Thanks!

**Comment by louisypchan** [comment]
@bclozel the sample is to simulate the case that trying to submit data multiple times even the request is not authenticated. Please try to use HTTP post (application/json) instead of posting data as binary format, I have reproduced the issue by Postman.

**Comment by louisypchan** [comment]
And I don't know how to reopen it...

**Comment by bclozel** [comment]
I've reproduced the issue in Postman, and looking at wireshark traces, we're writing the response in an improper way (not flushing properly or sending the last HTTP packet). The persistent connection is then in an inconsistent state, which explains the behavior you're describing.

Now looking at Spring Security's `ServerAuthenticationEntryPoint`, it looks like you're not supposed to write to the response there and handle it there. Most implementations of that interface are using  `Mono.fromRunnable` to add HTTP response headers.

This is of course early stages for Spring Security WebFlux, so I'm not sure about what's expected from implementations there. But it looks like what you're trying to do disconnects the handling of the response from the main pipeline, which leads to that inconsistent state.

I'll defer to @rwinch in case I missed something, but I'll keep this issue closed for now.

**Comment by louisypchan** [comment]
@bclozel  thanks, but it is weird that if I changed to use undertow instead of netty, the problem is solved

**Comment by rwinch** [comment]
I don't see any problems with the the `ServerAuthenticationEntryPoint` implementation.

I don't think this is related to Spring Security at all. I was able to reproduce the issue after removing Spring Security with an application that looks like:

```java
@SpringBootApplication
@EnableWebFlux
public class DemoApplication {
    public static void main(String ...args){
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

The first response is a 404 and the next hangs. If I submit another request using curl or httpie the request completes.

@louisypchan Can you [create a ticket in spring security](https://github.com/spring-projects/spring-security/issues/new) describing why you could not use the existing `HttpSecurity`?

**Comment by bclozel** [comment]
I've just created reactor/reactor-netty#186 to track that.
Thanks @rwinch and @louisypchan !
