### ISSUE TITLE
Try to remove the prepare build stage

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1062]
The build is a little problematic at the moment due to the extra prepare stage. See if we can remove it and always use the invoker plugin to run the samples.

We probably need to update file after jfrog/artifactory has updated the version but before anything is committed.

**Comment by snicoll** [comment]
@philwebb I can see a `prepare` profile but I we never had to use that. I assume it's invoked on the CI server for the release?

**Comment by philwebb** [comment]
Yes. It's used because the JFrog Artifactory plugin needs a Maven Reactor containing all the projects to update, but Maven doesn't support building a maven-plugin that is then used by other projects in the same reactor.

To work around the issue we do a "prepare" first to install the plugin in `~/.m2` then we can do a full build.

**Comment by philwebb** [comment]
I think we'll just live with this.
