### ISSUE TITLE
Create a separate module for generic conditions

### ISSUE THREAD

**Issue by pasfilip** [spring-projects/spring-boot#10628]
I'd like to propose to create a new module spring-boot-autoconfigure-core or perhaps spring-boot-condition or any other name you deem appropiate.
The idea would be to extract the non-provider specific conditions inside of package org.springframework.boot.autoconfigure.condition into this new module.

Specifically:

- OnBeanCondition
- OnClassCondition
- OnExpressionCondition
- OnJavaCondition
- OnJndiCondition
- OnPropertyCondition
- OnResourceCondition

Optionally:

- OnWebApplicationCondition

The reason for this change would be to enable projects not yet migrated to spring boot to make use of these features without adding all the provider specific conditions.

I'm not sure if this has been considered before or wether it was a conscious design decision to create one specific module without separating the reusable non-provider specific code from the provider specific code?

Ideally IMO would be to have these conditions included within the spring core framework since they seem to mainly depend on spring core features.
To this end I've also created a ticket in the spring core framework with a proposal to adopt these condtions.
The ticket contains further details about the motivation to do so as well as a proposal for migration.
See: https://jira.spring.io/browse/SPR-16065

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think there would be much benefit to creating a separate module purely for the conditions.

Most importantly, you can already use the conditions without using the rest of Spring Boot by depending on `spring-boot-autoconfigure` and using it as a library. The benefit of splitting out a separate module is then limited to a reduced jar size. That would only apply to a small number of users and is outweighed by the added complexity that it introduces. If jar size is of critical importance to you, tools such as JarJar will allow you to repackage a subset of a dependency.

Secondly, some of the conditions that you propose moving depend on the rest of Spring Boot. For example, all of the bean-related conditions build upon the ordering guarantees provided by auto-configuration.
