### ISSUE TITLE
The value of a manifest attribute must not be null (Key=Start-Class

### ISSUE THREAD

**Issue by bodiam** [spring-projects/spring-boot#10621]
kotlinVersion = '1.1.51'
springBootVersion = '2.0.0.M5'
javaVersion = '9'
gradleVersion = 4.2.1

**Bug report**

Running a ./gradlew clean build results in the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootJar'.
> The value of a manifest attribute must not be null (Key=Start-Class).
```

For a simple project to reproduce: https://github.com/bodiam/booklist

**Comment by bodiam** [comment]
I tried fixing it by adding

```
bootRun {
	main = 'com.booklist.backend.BackendApplication'
}
```

To the build.gradle file, but no effect.

**Comment by wilkinsona** [comment]
I think your main method is declared at the wrong level. I believe it should be:

```diff
diff --git a/src/main/kotlin/com/booklist/backend/BackendApplication.kt b/src/main/kotlin/com/booklist/backend/BackendApplication.kt
index f6efae2..bea523b 100644
--- a/src/main/kotlin/com/booklist/backend/BackendApplication.kt
+++ b/src/main/kotlin/com/booklist/backend/BackendApplication.kt
@@ -16,16 +16,15 @@ import javax.persistence.Id
 @SpringBootApplication
 class BackendApplication {

-    fun main(args: Array<String>) {
-        SpringApplication.run(BackendApplication::class.java, *args)
-    }
-
     @Bean
     fun startup(userService: UserService) = CommandLineRunner {
         userService.register("erik", "erik@gmail.com")
     }

+}

+fun main(args: Array<String>) {
+    SpringApplication.run(BackendApplication::class.java, *args)
 }

 @RestController
```

With this change in place I can build the fat jar and run it with `java -jar`.

And, just for the record, setting `main` on `bootRun` as it was the `bootJar` task that was failing.

**Comment by wilkinsona** [comment]
I should also have said that I defer to @sdeleuze for all things Kotlin, and the change I've proposed above brings things into line with [the main class in his Spring Boot Kotlin demo](https://github.com/sdeleuze/spring-boot-kotlin-demo/blob/2a3954d7ad022a0766aea0df22fb23b33ffb9baa/src/main/kotlin/hello/Application.kt).

**Comment by bodiam** [comment]
Hi @wilkinsona , thanks for that, you're right! I've checked it, just to be sure, with Josh' app here: https://github.com/joshlong/flux-flix-service/blob/master/kotlin/flux-flix-service/src/main/kotlin/com/example/fluxflixservice/FluxFlixServiceApplication.kt, and same. Cheers!

**Comment by sdeleuze** [comment]
Yeah that's the setup I recommend and that we use on our [examples](https://docs.spring.io/spring/docs/current/spring-framework-reference/kotlin.html#examples) and on [start.spring.io](https://start.spring.io/#!language=kotlin).

As an alternative, it is possible to declare the `main()` method inside the application class, but but you would have to use this no very nice syntax to make it a Java static method:

```
@SpringBootApplication
class BackendApplication {

    companion object {
        @JvmStatic fun main(args: Array<String>) {
            SpringApplication.run(BackendApplication::class.java, *args)
        }
    }

     @Bean
     fun startup(userService: UserService) = CommandLineRunner {
         userService.register("erik", "erik@gmail.com")
     }
}
```

So probably better to use top level `main()` method everywhere.

**Comment by bodiam** [comment]
Ah, thanks for that, I'll have a look at #10511 too.
