### ISSUE TITLE
SpringApplicationAdminJmxAutoConfiguration does not allow for additional MBeanExporters

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#10632]
Spring-boot version: 1.5.7.RELEASE

I have my own custom MBeanExporter - but when adding actuator it will become a conflict:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Constructor in org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration required a single bean, but 2 were found:
	- ucpMbeanExporter: defined by method 'ucpMbeanExporter' in class path resource [com/edb/fs/tac/jfr/srv/service/infra/jmx/JmxConfig.class]
	- endpointMBeanExporter: defined by method 'endpointMBeanExporter' in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointMBeanExportAutoConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

I think the actuator auto-config should use a qualifier or the likes, so that the conflict can be avoided. It should be possible (and is a quite common use-case) to define our own custom MBeanExporters in addition to the ones from boot.

Discussion on gitter: https://gitter.im/spring-projects/spring-boot?at=59e09941b20c642429f929d3

**Comment by wilkinsona** [comment]
`JndiDataSourceAutoConfiguration` has a similar problem as it too assumes that the context will contains at most one `MBeanExporter` beans.

**Comment by wilkinsona** [comment]
The `AnnotationMBeanExporter` that is auto-configured by `JmxAutoConfiguration` is marked `@Primary` so this problem will only occur in an application that provides its own non-primary `MBeanExporter` that switches off the auto-configured exporter. In other words, the problem can be avoided by following the advice in the failure analysis and marking `ucpMbeanExporter` as `@Primary`.
