### ISSUE TITLE
AbstractEmbeddedServletContainerFactory calculates wrong documentRoot in Windows when path has spaces

### ISSUE THREAD

**Issue by alibk0rd** [spring-projects/spring-boot#10649]
Environment:
Spring Boot: 1.5.6.RELEASE
Windows 10 (64-bit)

The application root is `C:\Program Files\app` (or the short form `C:\Progra~1\app`).
We have the following directory structure:
```
- .../app/
    |-WEB-INF/
         |-classes/...
         |-plugins/...
    |-static/<static web resources>
...
```
When the app root has no spaces in it, a call to `javax.servlet.ServletContext.getRealPath("/WEB_INF/plugins")` returns the desired result: `C:\<path-with-no-space>\app\WEB-INF\plugins`, but when there is a space in the path, like when under `Program Files`, instead we get:
`C:\Program Files\app\static\WEB-INF\plugins`, which is incorrect and results in a `FileNotFoundException`.

With some debugging, we've traced the problem to when Spring Boot calculates the `documentRoot` on start-up and sets Tomcat's `docBase`:
1. `org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory#getCodeSourceArchive` on line 199 converts the path to a URL which seems to result in the path's URL-encoding as `C:\Program%20Files\app\...`.
2. `org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory#getExplodedWarFileDocumentRoot(java.io.File)` on line 158 checks if the `codeSourceFile` path exists, which returns false, so then,
3. `org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory#getCommonDocumentRoot` checks for the existence of the folder `static`, which it finds, so it appends that to the app root path and returns `C:\Program Files\app\static` as the document root, which then results in the same call as before to `ServletContext.getRealPath()` to return `C:\Program Files\app\static\WEB-INF\plugins`, a path that does not exist.

Regardless of conventions, and whether our directory structure follows them, the behaviour should be consistent when there is a space in the path and when there is not.
I see the root of the problem as the URL-encoding of the path when there is a space, but I may be missing something here.

Please let me know if you need any more details.

**Comment by alibk0rd** [comment]
As a workaround, we managed to fix this by calculating and setting the `documentRoot` in the app via a custom `EmbeddedServletContainerConfiguration`:

```
@Configuration
public class EmbeddedServletContainerConfiguration {
...
    @Bean
    public TomcatEmbeddedServletContainerFactory embeddedServletContainerFactory() {
        TomcatEmbeddedServletContainerFactory tomcat = new TomcatEmbeddedServletContainerFactory() {
        ...
        }
        ...
        findDocumentRoot().ifPresent(tomcat::setDocumentRoot);
        ...
    }
...
    private static Optional<File> getCodeSourceFolder() {
        //ProtectionDomain.getCodeSource() is nullable, as are several of the mapped calls. This Optional
        //chain automatically breaks on nulls along the way, exactly what we want
        return ofNullable(EmbeddedServletContainerConfiguration.class.getProtectionDomain().getCodeSource())
                .map(CodeSource::getLocation)
                .map(url -> {
                    try {
                        // This will prevent URL-encoding of paths with spaces in them (e.g. on Windows), which
                        // results in a FileNotFoundException down the track.
                        return new File(url.toURI());
                    } catch (URISyntaxException e) {
                        log.warn("Failed to get CodeSource location as URI: " + url, e);
                        return null;
                    }
                });
    }
...
    private static Optional<File> findDocumentRoot() {
        return getCodeSourceFolder()
                .map(File::getParentFile)
                .filter(File::isDirectory)
                .map(file -> {
                    try {
                        return file.getCanonicalPath();
                    } catch (IOException e) {
                        String absolutePath = file.getAbsolutePath();
                        log.warn("Failed to get the canonical path for file. Returning 'absolutePath' instead: " + absolutePath, e);
                        return absolutePath;
                    }
                })
                .map(path -> {
                    int webInfPathIndex = path.indexOf(File.separatorChar + "WEB-INF" + File.separatorChar);
                    return webInfPathIndex >= 0 ? path.substring(0, webInfPathIndex) : path;
                })
                .map(File::new);
    }
```
Converting the `CodeSource` location `URL` to `URI` before getting the absolute/canonical path, seems to properly handle paths with spaces in them.

**Comment by wilkinsona** [comment]
@alibk0rd Thanks for the additional analysis. Would you like to turn what you've learned above into a pull request?

**Comment by alibk0rd** [comment]
I will hopefully have a PR for you sometime this week. :crossed_fingers:

**Comment by wilkinsona** [comment]
Great stuff. Thanks

**Comment by snicoll** [comment]
Closing in favour of PR #10706
