### ISSUE TITLE
provide guidance for folks using Java 9 who want to stay on 1.5x (for whatever reason)

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#10646]
Hi team,

i know the guidance says to use SO for questions but i figured this might have design implications so i wanted to ask here: can we provide guidance for users of Spring Boot 1.5x who want to use Java 9? 

We know that 2.0 will have some small breaking changes like the Actuator behavior and the OAuth integration. It's reasonable to expect that all of that stuff will be workable, again, soon, but in the meantime there might be people who can't upgrade but who want to use Java 9. I can't imagine we'd want to endorse or support such an upgrade, but could we at least document it? AFAIK, Oracle isn't officially support java 9 either (it's not an LTE). So, maybe the crossection of people who NEED OAuth and who NEED Java 9 and who DONT NEED ti know something is supported is very small but I wanted to ask you.

**Comment by wilkinsona** [comment]
We have no plans to support Java 9 on 1.5. It's not just a question of Boot itself supporting Java 9, but all the projects with which it integrates as well. Documenting what does and doesn't work, and what you need to do to get things into that state would be a huge undertaking. That huge undertaking would then increase our support burden as it would set the expectation that things should work with Java 9 when we know that it doesn't and that it isn't something that we want to support. Anyone who wants to live on the leading edge and use Java 9 can use 2.0 M5 or later.
