### ISSUE TITLE
Different way of using Annotation Processors in templates

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#10645]
This is a new issue coming from my suggestion in #10539 about using an alternative approach to defining annotation processors in dependencies.

The maven compiler plugin has [`annotationProcessorPaths`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths) where you can put the maven coordinates of the annotation processor and it will pull all the required things and you won't have them in your dependencies. The advantage of this is that users cannot inherit transitive dependencies from the annotation processors (which are mostly in the `provided` scope).

For Gradle there is the [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin) that does the same as the maven `annotationProcessorPaths`. They say that the `idea` and `eclipse` goal configure the IDEs appropriately (haven't tried it myself though). 

There is on downside in IntelliJ though. That is: [IDEA-150621](https://youtrack.jetbrains.com/issue/IDEA-150621). However, I think that you would have bigger chances to make Jetbrains pick up the issue and resolve it :).

Before actually implementing this and suggesting it to all the users there must be OOB support from all the IDEs with Maven and Gradle as build tools:

* IntelliJ
  * [ ] Maven - IntelliJ does not pick up the `annotationProcessorPaths`. Known issue is [IDEA-150621](https://youtrack.jetbrains.com/issue/IDEA-150621).
  * [x] Gradle - Using the `gradle-apt-plugin` with redirecting builds and it generates a correct 
* Eclipse / STS
  * [x] Maven - Support via [m2e-apt](https://marketplace.eclipse.org/content/m2e-apt) and it's `<m2e.apt.activation>jdt_apt</m2e.apt.activation>`
  * [ ] Gradle - Not entirely sure how the integration is done, but the `gradle-apt-plugin` might be enough
* Netbeans
  * [x] Maven - Netbeans redirects the build to Maven, so there is no issue
  * [ ] Gradle - Not entirely sure how the integration is done, but the `gradle-apt-plugin` might be enough

(I've marked the IDE / build tools combinations that I know work OOB, maybe you want to unmark them and validate them by yourself)

I think the biggest blocker is the IDEA Issue, which has recently been Triaged, but I have no idea what that means for the issue. Maybe with the involvement of Spring Boot it would get resolved faster.

The Netbeans and Eclipse builds with Gradle need to be tested, but I think that they would work OK. I don't know what is the normal way of working with Gradle in those IDEs.

For the IntelliJ and Gradle integration what is the expected OOB? Redirecting the build to the IDE or something else?

**Comment by snicoll** [comment]
Thanks for the very detailed analysis but it really out of our hands. I've raised the Maven issue with Jetbrains and we can reopen this one if there is any progress on making sure this work OOB in all IDEs.

**Comment by filiphr** [comment]
No problem @snicoll, I understand that OOB working is priority number 1. In case something changes with IntelliJ I am going to come back to this.

Thanks for looking into it

**Comment by filiphr** [comment]
Just for an information the Issue with Maven and IntelliJ ([IDEA-150621](https://youtrack.jetbrains.com/issue/IDEA-150621) has now been resolved and using `annotationProcessorPaths` works out of the box with IntelliJ and Maven now.
