### ISSUE TITLE
@WebFluxTest should support Jackson ObjectMapper's customization like chapter "75.3 Customize the Jackson ObjectMapper" 

### ISSUE THREAD

**Issue by redtankd** [spring-projects/spring-boot#10648]
The 3rd library I use provides a class with type of `com.fasterxml.jackson.databind.Module` . But @WebFluxTest don't scan beans of type `com.fasterxml.jackson.databind.Module`.

**Comment by redtankd** [comment]
I find a way

```
@TestConfiguration
    class Config {
        @Bean
        fun moneyModule() = MoneyModule() // It doesn't work in WebFluxTest

        @Bean // It works
        fun webFluxConfigurer() = object : WebFluxConfigurer {
            override fun configureHttpMessageCodecs(configurer: ServerCodecConfigurer) {
                val mapper: ObjectMapper = Jackson2ObjectMapperBuilder.json().build()
                mapper.registerModule(MoneyModule() as Module)
                configurer.defaultCodecs().jackson2JsonEncoder(Jackson2JsonEncoder(mapper))
                configurer.defaultCodecs().jackson2JsonDecoder(Jackson2JsonDecoder(mapper))
            }
        }
    }
```

**Comment by wilkinsona** [comment]
`@WebMvcTest` will, I believe, behave in the same way. There type exclude filters currently both include `JsonComponent`. We should consider adding `com.fasterxml.jackson.databind.Module` too.

**Comment by snicoll** [comment]
@wilkinsona again, that include/exclude applies to `@ComponentScan`. I am not  sure that registering a Jackson `Module` as a top-level component is frequent (most users would define a `@Bean` in a regular `@Configuration` class and, unfortunately, we have no way to scan that. 

I am ok to open the filter to scan extra types but I don't think that's going to  be very useful.

**Comment by wilkinsona** [comment]
Good point, @snicoll. Agreed on the extra types not being very useful. This should probably become a documentation issue.
