### ISSUE TITLE
/application Does Not Return actuator.v2 Media Type

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#10659]
Currently (2.0.0.M5) all actuator endpoints respond with an `application/vnd.spring-boot.actuator.v2+json` media type specified in the `Content-Type` header, except `/application` and presumably `/cloudfoundry`.  Given that this will be the only way for an application to tell which version of the actuators are in use, these endpoints should respond with the appropriate media type.

**Comment by ryanthon** [comment]
Does anyone know how to disable this endpoint ("/application") altogether?

**Comment by wilkinsona** [comment]
@ryanthon You've asked the same question on two closed issues. Please don't do that.
