### ISSUE TITLE
Cannot build individual project using the invoker plugin

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10667]
This command

```
./mvnw clean install -pl spring-boot-project/spring-boot-tools/spring-boot-maven-plugin
```

fails as follows:

```
INFO] [ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.0.0.BUILD-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.springframework.boot:spring-boot-maven-plugin:jar:2.0.0.BUILD-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-parent:pom:${revision} in file:///Users/snicoll/.m2/repository was cached in the local repository, resolution will not be reattempted until the update interval of local.central has elapsed or updates are forced -> [Help 1]
```

Some `${revison}` attribute is not resolved properly.

**Comment by snicoll** [comment]
@wilkinsona can you please expand why you removed the `regression` label?

@philwebb it would be nice if you could have a look to this one. It's really annoying when working on the maven plugin

**Comment by wilkinsona** [comment]
I don't consider it to be a regression because it doesn't affect users

**Comment by philwebb** [comment]
I think I hit a similar issue when trying to use the invoker plugin with the samples. It's related to the [Maven CI Friendly Versions](https://maven.apache.org/maven-ci-friendly.html). I think either the `@project.version@` property doesn't get expanded correctly, or it ends up referring to POM that isn't flattened.

With the samples I set `<cloneProjectsTo />` to get in-place running:

```xml
<plugin>
	<!-- We use invoker so that the spring-boot-maven-plugin can be used -->
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-invoker-plugin</artifactId>
	<!-- Downgrade due to https://issues.apache.org/jira/browse/MINVOKER-224 -->
	<version>2.0.0</version>
	<inherited>false</inherited>
	<configuration>
		<projectsDirectory>${main.basedir}/spring-boot-samples</projectsDirectory>
		<cloneProjectsTo />
		<skipInvocation>${skipTests}</skipInvocation>
		<streamLogs>true</streamLogs>
		<pomIncludes>
			<pomInclude>pom.xml</pomInclude>
		</pomIncludes>
	</configuration>
```

I'd need to dig a bit deeper to see what's going on with plugin invoker and why it works fine with a full build.
