### ISSUE TITLE
Validate Profiles on application startup

### ISSUE THREAD

**Issue by MALPI** [spring-projects/spring-boot#10665]
**As** a developer
**I want to** be able to identify wrong Strings used in `@Profile` during startup of my application
**in order to** fail fast.

We are using `@Profile` annotation to configure which `application.properties` is used. 

For example there are:

- `application.properties`
- `application-local.properties`  
- `application-prod.properties` 

So let's assume someone is configuring `@Profile("production")` which is not existing as properties file and/or Bean. 

So it would be nice if there would be the option to verify if `application-production.properties` is available at all during startup. And if this is not the case, let the application fail.

I hope it's clear what I mean.

**Comment by snicoll** [comment]
Thanks for the proposal but I don't think we should do this. There are various locations where such a file can be defined and you can enable a profile for a totally unrelated reason. For instance, you can control which `@Configuration` classes or `@Bean` definitions are loaded. Adding such a check would break perfectly legit use cases.

If you care about certain properties to be set, you can check for them on startup. The `/env` actuator endpoint also lists the property sources so you can inspect that.

**Comment by MALPI** [comment]
hi @snicoll, valid point. Still it would be nice to have a mechanism which validates that a used profile actually is available. I could also imagine to set available profiles in `application.properties` and verify against the ones used in annotations?

**Comment by snicoll** [comment]
@MALPI the profile has a broader scope as I've indicated in my comment so checking that a particular file exists and fail the build if that's not the case is not going to be a reusable feature. You can of course create a check of your own and tailor it to your use case.
