### ISSUE TITLE
Kafka auto-configuration does not support @SendTo

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#10669]
In order to support `@SendTo` (replies) in Kafka, the `KafkaTemplate` (if present) should be injected into the listener container factory...

```java
	@KafkaListener(topics = "rjugUpcase", groupId = "rjug")
	@SendTo("rjug")
	public String upcase(String in) {
		System.out.println("upcase: " + in);
		return in.toUpperCase();
	}
```

```
java.lang.IllegalStateException: a KafkaTemplate is required to support replies
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.kafka.config.MethodKafkaListenerEndpoint.createMessageListener(MethodKafkaListenerEndpoint.java:136) ~[spring-kafka-2.0.0.RELEASE.jar:2.0.0.RELEASE]
```

See `AbstractKafkaListenerContainerFactory.setReplyTemplate()`.

**Comment by SamD** [comment]
I'm still seeing this with 2.1.7.RELEASE

**Comment by snicoll** [comment]
@SamD `2.1.7.RELEASE` is a bit vague (there's no such Spring Boot version so I can only assume that's a Spring Kafka version. Support was added in Spring Boot as of Spring Boot `2.0.0.M6` (see the milestone information on the right). 

If you have more questions, please ask on StackOverflow or come chat with us on Gitter.
