### ISSUE TITLE
Add @ConditionalOnNotCloudPlatform

### ISSUE THREAD

**Issue by Flaw101** [spring-projects/spring-boot#10688]
Currently having to do some messy Conditional annotations, and profile checks to verify if we're not in deployed to PCF. 

Would like to invert the `@CondtionalOnCloudPlatform` annotation to check the values in the `CloudPlatform` enum if it's active and fail the Conditional if any are active.

**Comment by wilkinsona** [comment]
A little clunky, but you should be able to negate a single condition using `NoneNestedConditions`:

```java
class NotOnCloudFoundryCondition extends NoneNestedConditions {

    NotOnCloudFoundryCondition() {
        super(ConfigurationPhase.PARSE_CONFIGURATION);
    }

    @ConditionalOnCloudPlatform(CloudPlatform.CLOUD_FOUNDRY)
    static class CloudFoundryCondition {

    }

}

@Configuration
@Conditional(NotOnCloudFoundryCondition.class)
class ExampleConfiguration {

}
```

`ExampleConfiguration` will then be included when your application runs anywhere other than CloudFoundry.

I'm not yet convinced about adding first-class support for this. Can you describe your use case in a little more detail please?

**Comment by Flaw101** [comment]
Usual enterprise world annoyances. Needing to connect to use different AWS Beans to setup and connect to SNS/SQS (don't connect to development queues, need to setup proxy information for local etc.) depending on local development vs. deployed regions. Using profiles to achieve feels equally as clunky as they _could_ change without notice, or could be missed in a refactor.

The example is a neat solution.

**Comment by wilkinsona** [comment]
Thanks for the info. I wonder if the example may be neat enough. Let's see what the rest of the Boot team thinks.

**Comment by snicoll** [comment]
Personally, I'd go with `NotOnCloudFoundryCondition` (i.e. reusing the bits that we already offer to invert the condition).

**Comment by wilkinsona** [comment]
Ok, let's stick with using `NoneNestedConditions` as the recommend approach.
