### ISSUE TITLE
How @WebFluxTest is used to test functional endpoints?

### ISSUE THREAD

**Issue by redtankd** [spring-projects/spring-boot#10681]
@WebFluxTest will auto-configure the Spring WebFlux infrastructure and limit scanned beans to @Controller, @ControllerAdvice, @JsonComponent,and WebFluxConfigurer. So @WebFluxTest is impossible for functional endpoints now?

**Comment by wilkinsona** [comment]
@redtankd You've asked this on Gitter too. Let's keep the discussion in one place please. We can re-open this latter if necessary.

**Comment by lucasvalenteds** [comment]
[Here](https://gitter.im/spring-projects/spring-boot?at=59e726d4f7299e8f53007eb9) is the link to the discussion mentioned.
