### ISSUE TITLE
JSON date format in application config for jackson should be valid for JSR310 types

### ISSUE THREAD

**Issue by sbuettner** [spring-projects/spring-boot#10694]
Configuring a date format inside the `application.yml` file does not affect the serialization of JSR310 types like `ZonedDateTime` and its unclear why not:

```
spring:
  jackson:
    dateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
```

Currently its only possible by using the `@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ss.SSSZ")` annotation which requires an additional dependency and leads to repetition.

Is there a reason why the date format is not automatically registered for the respective types when `com.fasterxml.jackson.datatype.jackson-datatype-jsr310` is on the classpath?

**Comment by wilkinsona** [comment]
`spring.jackson.date-format` maps to `com.fasterxml.jackson.databind.ObjectMapper.setDateFormat(DateFormat)` which controls the serialisation of `java.util.Date`. We also use it to create a `com.fasterxml.jackson.datatype.joda.ser.DateTimeSerializer` with an appropriately configured `com.fasterxml.jackson.datatype.joda.cfg.JacksonJodaDateFormat` which takes care of formatting of Joda type. AFAIK, Jackson does not provide a similar way to globally configure the format of JSR 310 types. For example, `InstantSerializer` is final and only provides protected methods for creating an instance with a specific `java.time.format.DateTimeFormatter`. Furthermore, the javadoc for `JavaTimeModule` indicates that ISO-8601 format is used and makes no mention of this being customisable:

> Most java.time types are serialized as numbers (integers or decimals as appropriate) if the com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS feature is enabled, and otherwise are serialized in standard ISO-8601 string representation. ISO-8601 specifies formats for representing offset dates and times, zoned dates and times, local dates and times, periods, durations, zones, and more. All java.time types have built-in translation to and from ISO-8601 formats.

If you know of a way to configure this globally in Jackson that please let us know and we can re-open this issue and consider auto-configuring it

**Comment by sbuettner** [comment]
@wilkinsona Thanks for the quick response.

`LocalDateDeserializer`, `ZonedDateTimeSerializer` and other serializers from the `JavaTimeModule` seem to support `DateTimeFormatter` via public constructors.

**Comment by wilkinsona** [comment]
Unfortunately, that doesn't really help for a general purpose solution in Spring Boot as we can't configure the format for an `Instant`. If you know that you won't use `Instant` then you could consider a `SimpleModule` bean with customised versions of the various (de)serialisers that you care about registered with it. You may also want to raise an enhancement request with Jackson to make this configurable across all the Java Time types. With that in place, we could then look at doing something in Spring Boot.
