### ISSUE TITLE
Make Concourse CI PR builds visible to contributors

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#10693]
PR builds were moved to Concourse CI however only the overall build status is visible to contributors while details, including build log/output, are not.

**Comment by wilkinsona** [comment]
We'd like to do so, but we're currently blocked waiting to get CredHub set up on the Concourse CI infrastructure

**Comment by vadeg** [comment]
Are there any updates? It is very hard to develop features without understanding what failed in CD service.

**Comment by wilkinsona** [comment]
Not yet, no. We’ll comment on this issue as soon as we have any updates to share

**Comment by philwebb** [comment]
The `build` job is now public https://ci.spring.io/teams/spring-boot/pipelines/spring-boot
