### ISSUE TITLE
Updates for removal of spring-security-webflux

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#10692]
Spring Security moved code in spring-security-webflux into spring-security-web. Boot needs updated to account for this

See https://github.com/spring-projects/spring-security/issues/4662

**Comment by snicoll** [comment]
That probably means we could merge the two starters into one then as they're identical now. Flagging for team attention to see if I am missing something.

**Comment by wilkinsona** [comment]
I don't think you're missing anything, @snicoll.

**Comment by rwinch** [comment]
That sounds right. To rephrase - now if someone wants reactive security, they select "Security" and "Reactive Web"

**Comment by snicoll** [comment]
Yes

**Comment by mbhave** [comment]
Closed via 8600bd7
