### ISSUE TITLE
ClientRegistration.Builder constructor is private

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#10701]
Related [#4656](https://github.com/spring-projects/spring-security/issues/4656)

In `OAuth2ClientPropertiesRegistrationAdapter.getBuilder()`, the `ClientRegistration.Builder(registrationId)` constructor is called. This constructor is now private in the latest snapshot.

Please update to use `ClientRegistration.withRegistrationId(registrationId)`

**Comment by mbhave** [comment]
Closed via 8600bd7
