### ISSUE TITLE
ReplaceOperation can no longer be accessed outside from spring package

### ISSUE THREAD

**Issue by RyamBaCo** [spring-projects/spring-boot#10716]
Hello there,

in my Spring Boot application I'm using `org.springframework.data.rest.webmvc.json.patch.ReplaceOperation` for creating a custom PATCH-operation, e.g.

```
public static Patch convertRequestToPatch(ServletServerHttpRequest request) {
		ObjectMapper objectMapper = new ObjectMapper();
		try {
			InputStream inputStream = new IncomingRequest(request).getBody();
			JsonNode requestJson = objectMapper.readTree(inputStream);
			Iterator<Entry<String, JsonNode>> fields = requestJson.fields();
			List<PatchOperation> patchOperations = new ArrayList<>();
			while (fields.hasNext()) {
				Entry<String, JsonNode> entry = fields.next();
				patchOperations.add(new ReplaceOperation(entry.getKey(), entry.getValue().asText()));
			}

			return new Patch(patchOperations);
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}
	}
```

which was working like a charm till Spring Boot 1.5.7, but with the recent 1.5.8 release the build is failing with ` org.springframework.data.rest.webmvc.json.patch.ReplaceOperation is not public in org.springframework.data.rest.webmvc.json.patch; cannot be accessed from outside package`

Any reasons on why the ReplaceOperation is no longer public? Is there a new best practice for my task?

Best regards,
Christian

**Comment by snicoll** [comment]
`ReplaceOperation` is part of the Spring Data project. Please report the issue [in their tracker](https://jira.spring.io/browse/DATAREST/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)

**Comment by RyamBaCo** [comment]
Thanks for the Information, I reported the issue in the tracker of the Spring Data project.
