### ISSUE TITLE
Spring Boot Actuator - override management port with ./config/application.properties does not work

### ISSUE THREAD

**Issue by cleankod** [spring-projects/spring-boot#10710]
In the default project's `application.properties` I have a `management.port` property set to a value different than the main context's which means two embedded servlet contexts are starting on different ports. I need to allow the `management.port` overriding by the default Spring Boot's mechanisms which are not seem to be working correctly.

How to reproduce:
1. In `resources/application.properties` set the `management.port` property to some other value than the default Spring Boot's (for example `8081`).
2. Build the application.
3. In the same directory as JAR, create the `config/` directory with `application.properties` file. In this file add the property `management.port` with the value other than the default Spring Boot's and other than the one set in step 1, for example `8082`.
4. Start the application.

Result: The management servlet container starts on `8081`.
Expected result: The management servlet container should start on `8082`.

Passing the `management.port` as a JVM parameter works fine allowing to override the port:
```
java -Dmanagement.port=8082  -jar application.jar
```
Other `management` properties are working correctly (for example `management.context-path`). 

Spring Boot version: `1.5.4.RELEASE`.

**Comment by wilkinsona** [comment]
What version of Spring Boot are you using? From what directory are you starting the application?

**Comment by cleankod** [comment]
Added Spring Boot version. The directory from which the application i being run is the same as the one with `config/` dir. Besides, other configuration properties are being overridden correctly.

**Comment by wilkinsona** [comment]
It works for me with both 1.5.4.RELEASE and 1.5.7.RELEASE. If you'd like us to spend more time investigating, please provide us with a minimal sample and precise steps to reproduce the problem.
