### ISSUE TITLE
Clarify that `@ConfigurationProperties` are not meant to be extended

### ISSUE THREAD

**Issue by ArloL** [spring-projects/spring-boot#10713]
I am currently experimenting with custom properties classes and want extend an existing properties class:

````
public class CustomRabbitProperties extends RabbitProperties { }
````

Sadly the configuration processor does not create metadata for the nested classes in `RabbitProperties` (e.g. `RabbitProperties.Ssl`) for my extension. It works when I add a property to my extension with `@NestedConfigurationProperties`:

````
public class CustomOverrideRabbitProperties extends RabbitProperties {
	@NestedConfigurationProperty
	private Ssl ssl = new Ssl();
}
````

![image](https://user-images.githubusercontent.com/195367/31818092-e76521ca-b596-11e7-848a-d39d2bacc2d1.png)

I have created a [demo project](https://github.com/ArloL/spring-configuration-processor-metadata-bug-demo).

**Comment by snicoll** [comment]
Thanks for the sample.

Two things:

* Regardless of the issue, please do not extend from our `@ConfigurationProperties`, _especially_ with the same prefix.
* The annotation processor needs to have the source code to be able to extract things like default value and documentation. By extending a class that's outside of your compilation context, you won't get a consistent set of metadata (worse they'd be duplicated in your example).
* It makes the use of the prefix a bit funky, should all the properties of the parent exposed with the prefix of the child?

Can we take a step back and look at what you're trying to do instead?

**Comment by ArloL** [comment]
Thanks for the quick reply.

You're right my use case is a bit weird. In this case I am trying to add three properties to `RabbitProperties.Template` namely `exchange`, `routingKey` and `channelTransacted` to set the appropriate properties on the created `RabbitTemplate`. Of course this could just be added to the official configuration.

I was just wondering whether extending the official `@ConfigurationProperties` is a valid use case.

**Comment by snicoll** [comment]
It is not. Let me clarify that in the documentation.

**Comment by snicoll** [comment]
We've documented that `@ConfigurationProperties` are not public API in  #16704 so that includes extending from them. Looking at the current doc, I don't feel adding something more explicit is warranted.
