### ISSUE TITLE
spring-boot-maven-plugin:1.5.8.RELEASE build warning "The POM for commons-io:commons-io:jar:1.3.2 is invalid"

### ISSUE THREAD

**Issue by zendu** [spring-projects/spring-boot#10725]
I have a spring boot project where Spring Boot 1.5.8 POM is used as parent project. Project uses Spring Boot Maven plugin v1.5.8. Maven install command always generates POM warning for commons-io.

```
[INFO] --- spring-boot-maven-plugin:1.5.8.RELEASE:repackage (default) @ MyProject ---
[WARNING] The POM for commons-io:commons-io:jar:1.3.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

```

**Comment by snicoll** [comment]
That `commons-io` dependency is corrupted in your local repository (or something that rely on it). Please remove it so that Maven can download it again. If that doesn't work, provide a sample that reproduces the problem.
