### ISSUE TITLE
Entity Model [Json] Attribute is MySQL JSON column

### ISSUE THREAD

**Issue by alexbobpo** [spring-projects/spring-boot#10726]
hello!

see code:

1. JpaConverterJson.calss:

> @Converter
> public class JpaConverterJson implements AttributeConverter<Object,String> {
> 
>     private final static ObjectMapper objectMapper = new ObjectMapper();
> 
>     @Override
>     public String convertToDatabaseColumn(Object attribute) {
>         if (StringUtils.isEmpty(attribute)) return "{}";
>         try {
>             return objectMapper.writeValueAsString(attribute);
>         } catch (JsonProcessingException e) {
>             throw new HibernateException("unable to read object from result set", e);
>         }
>     }
> 
>     @Override
>     public Object convertToEntityAttribute(String dbData) {
>         if (StringUtils.isEmpty(dbData)) return new HashMap<>();
>         try {
>             return objectMapper.readValue(dbData, Map.class);
>         } catch (IOException e) {
>             throw new HibernateException("unable to read object from result set", e);
>         }
>     }
> }

2. Person Model:

> @Entity
> public class Person implements Serializable {
>     @ Id
>     private String username;
> 
>     @JsonIgnore
>     @Column(nullable = false)
>     private String password;
> 
>     @Column(nullable = false)
>     private boolean enabled = true;
> 
>     @Convert(converter = JpaConverterJson.class)
>     private Map<String, Object> extend;
> }

in spring boot  2.0.0.BUILD-SNAPSHOT

3. run Exception:

> 2017-10-21 09:36:05.544 ERROR 16888 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [json]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083) ~[spring-context-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:858) ~[spring-context-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> 	at com.alex.Application.main(Application.java:31) [out/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
> 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
> Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [json]
> 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:348) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.boot.internal.ClassLoaderAccessImpl.classForName(ClassLoaderAccessImpl.java:62) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:538) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.cfg.SetSimpleValueTypeSecondPass.doSecondPass(SetSimpleValueTypeSecondPass.java:25) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1621) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1579) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:278) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:858) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:885) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57) ~[spring-orm-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:358) ~[spring-orm-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:384) ~[spring-orm-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:373) ~[spring-orm-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1763) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700) ~[spring-beans-5.0.1.BUILD-SNAPSHOT.jar:5.0.1.BUILD-SNAPSHOT]
> 	... 21 common frames omitted
> Caused by: java.lang.ClassNotFoundException: Could not load requested class : json
> 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:336) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_144]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_144]
> 	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_144]
> 	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_144]
> 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:345) ~[hibernate-core-5.2.11.Final.jar:5.2.11.Final]
> 	... 35 common frames omitted

**Comment by snicoll** [comment]
Given the state of the stacktrace, this looks like an hibernate problem to me and you haven't really indicated why you believe this is a bug in Spring Boot. I'd ask first on StackOverflow.
