### ISSUE TITLE
Spring Boot 2.0.0.M5 no longer running app which worked using 1.5.7

### ISSUE THREAD

**Issue by 204608** [spring-projects/spring-boot#10746]
I'm having issues running an application which worked using Boot 1.5.7 but doesn't work using 2.0.0.M5.

It's a simple Rest app. The only changes required to make it run using 2.0.0.M5 were the build.gradle file and some persistence API stuff (which is not executed at this point). What I found was during debugging, the entry points (in FrontController) were never entered when the appropriate URL was used in the modified version, but functioned perfectly in the old one. 

I'm using JDK 1.8.0_144 on Windows 7.

I'm attaching the projects - the "common" one is needed for compilation but nothing else.

Let me know if you need any further information

[front_notworking.zip](https://github.com/spring-projects/spring-boot/files/1405527/front_notworking.zip)
[front_working.zip](https://github.com/spring-projects/spring-boot/files/1405528/front_working.zip)
[common.zip](https://github.com/spring-projects/spring-boot/files/1405529/common.zip)

**Comment by snicoll** [comment]
@204608 sorry but we can't justify spending time to setup postgres, amqp and other dependencies to start your project. Surely if those are unrelated you can provide _one_ zip that reproduces the issue you're seeing.

**Comment by 204608** [comment]
@snicoll I think I've worked out what it is. Is the "server.context-path" application parameter no longer valid? I just ran through some simpler test apps and they all worked. Then I noticed this is my configuration file, which is different to all of my other apps.

**Comment by snicoll** [comment]
@204608 please read the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#servlet-specific-server-properties) before opening an issue. Also your IDE should display that property in red as it has been renamed.
