### ISSUE TITLE
Logging config file not loaded correctly

### ISSUE THREAD

**Issue by yeta-io-ceo** [spring-projects/spring-boot#10745]
Hi,

I have a custom logging.config property value in my application which points to my own log4j xml file.

When I use spring boot 2.0 (the bug reproduced both on M5 and on snapshot versions), the configuration is not loaded properly and I see the standard log output style.

According to my own investigation, the method LoggingApplicationListener.initializeSystem is called twice. 

The first time it is called with the application environment that have all the properties including the proper logging.config value (come from`environment.getProperty("logging.config")`).

And moments later, it is called with kind of default application environment where the value is null. May be it's caused due integration to spring-cloud-config, I don't know. But because it's called with null value, then it calls initialisation code `system.initialize(initializationContext, (String)null, logFile);` and break the already initialised log system.

If at that moment I change using debugger the value from null to a proper path to my xml configuration, then it's loaded correctly.

Best,
Yeta

**Comment by wilkinsona** [comment]
Can you please provide a sample that reproduces the behaviour you have described without using any Spring Cloud dependencies?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by yeta-io-ceo** [comment]
The issue happens only when spring-cloud-config is used. Without it everything works perfectly.

**Comment by wilkinsona** [comment]
Thanks. Can you please raise a [Spring Cloud issue](https://github.com/spring-cloud/spring-cloud-commons) providing a small sample that reproduces the problem? We can re-open this issue if it turns out that a change in Spring Boot is required.

**Comment by yeta-io-ceo** [comment]
In latest build snapshots the problem does not exists anymore
