### ISSUE TITLE
Issue warnings in Maven when dependencies used in projects are behind versions used in Spring Boot

### ISSUE THREAD

**Issue by mouyang** [spring-projects/spring-boot#10742]
It would be useful to be made aware of this situation so that they can be addressed or reported on.

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

Maven doesn't really provide us with much of an opportunity to add extra warnings. You'd have to be using Spring Boot's Maven plugin for this to work, and even then I'm not sure that it would be easy or even possible for us to generate the warnings you're looking for accurately.

Assuming that it is possible to implement what you're looking for, we'd also need to provide a mechanism to suppress certain warnings. Without such a mechanism, a user who had deliberately downgraded a dependency would be warned about something that, for them, was just a nuisance. This starts to make the feature rather complicated, IMO.

Lastly, if you're using Boot's dependency management (and you'd have to be for this feature to really make sense), this is something that your IDE should already go a long way to helping with. For example, if I add the following to the `pom.xml` of a Spring Boot 1.5.8 application:

```xml
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.8.1</version>
</dependency>
```

Eclipse's Maven integration will add a warning to the version declaration that says "Overriding managed version 2.8.10 for jackson-databind".
