### ISSUE TITLE
Could not bind to a map whose key is an integer

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10751]
It looks like it is no longer possible to bind to a map if the key is an integer as it's trying to turn that into an index or something.

I've [added a sample app with one test failing](https://github.com/snicoll-scratches/test-map-with-numeric-key)

**Comment by mbhave** [comment]
Any key in the map that is numeric or starts with a number needs to be surrounded by `[]`. In this case, it will be `sample.foos.[1].name`. I wonder if we can remove the constraint on a`ConfigurationProperyName` that prevents any element in it from starting with a number.

**Comment by snicoll** [comment]
@mbhave if that's a limitation that is fine by me but IMO the exception message should change. Don't we have the intermediate path somewhere when binding? When we do we can figure out if the target type is a map maybe?

Right now the exception message actually removes the number from the key altogether. I guess that's another thing to check. 

I don't mind about the limitation if that makes binder more explicit but the exception message is currently quite misleading.

**Comment by mbhave** [comment]
When we create the `ConfigurationPropertyName`, we strip any invalid characters from it and store it in the canonical format. At that time we don't know what that property is going to get bound to. I can't think of a reason for stripping off the number from the key (if the key starts with a number).

**Comment by mbhave** [comment]
Changing it to a possible `enhancement` because the limitation was intended behavior.

**Comment by snicoll** [comment]
Got it. One possible improvement would be to keep the original String and use that in the exception message.

**Comment by philwebb** [comment]
I can't remember exactly why we wanted that restriction, but I'm sure we had a reason in mind. It might be to do with `SystemEnvironmentPropertyMapper`.

**Comment by mbhave** [comment]
Maybe it was because `sample.1.foo` is valid only if `sample` is a `Map` and when we create the `ConfigurationPropertyName`, we don't know what it's going to bind to. I think it might be better if we leave the number as is. If it fails to bind, the failure analysis will say `The elements [sample.foos.1.name] were left unbound`  instead of `No converter found capable of converting from type` which IMO is clearer.

**Comment by mbhave** [comment]
should we add this to RC2?

**Comment by snicoll** [comment]
It would be nice to improve the error message, yes.

**Comment by philwebb** [comment]
I think we should actually look at supporting this directly.

**Comment by mbhave** [comment]
@philwebb not totally sure what you mean. I've made a change that considers numeric characters in a `ConfigurationPropertyName` to be valid (even at the first index). I think that works unless you can think of a scenario where it wouldn't.

**Comment by philwebb** [comment]
@mbhave Yeah, that's what I meant. The comment "It would be nice to improve the error message, yes." made me think we were going to not fix the underlying problem.
