### ISSUE TITLE
MessageSourceAutoConfiguration does not consider @PropertySources

### ISSUE THREAD

**Issue by klu2** [spring-projects/spring-boot#1075]
I have a testcase that uses 

``` java
@PropertySource(value = "classpath:test.properties")
```

In this file I have:

``` java
spring.messages.basename=messages-base
```

And in message-base_en.properties I have some message keys that are used in the unit test, but the values cannot be found

I extracted all the required code into an own github repository: https://github.com/klu2/spring-boot-issues/

This is the test case:
https://github.com/klu2/spring-boot-issues/blob/master/autoconfigure/src/test/java/net/klu2/springboot/autoconfigure/MessageSourceAutoConfigurationTest.java

This testcase passes with spring boot 1.0.2, but it fails with spring boot 1.1.0 (you can easily check that by exchanging ext.springBootVersion in build.gradle

Most probably this commit is responsible for this issue: https://github.com/spring-projects/spring-boot/commit/0def7644c2eaefc73328f257d5f53bbf615de397 (#1019)

It works fine, if the messages are in message.properties, but not in message-base.properties. It seems that @PropertySource is not considered in the MessageSourceAutoConfiguration

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
