### ISSUE TITLE
Configuration Key Metadata: ability to specify regex for validating value

### ISSUE THREAD

**Issue by YannCebron** [spring-projects/spring-boot#10755]
Provide new provider-type "regex" in additional-spring-configuration-metadata.json with ability to specify:

- regex value must match
- human-readable error message to hint to valid value and/or sample

Sample:
```
  {
    "name": "spring.http.multipart.max-file-size",
    "providers": [
      {
        "name": "regex",
        "parameters": {
          "expression": "-?\\d+((k|K|m|M)(b|B))?",
          "message": "Sample: 1kB, 2MB"
        }
      }
    ]
  }
```

IntelliJ IDEA already has some "hardcoded" regex for known keys (see above).
There are some more where it seems useful (e.g. MVC "suffix" pattern validation, https://youtrack.jetbrains.com/issue/IDEA-181046)

**Comment by philwebb** [comment]
Although there are a few Stringly typed items that remain, I think we've mainly solved this issue by introducing richer types. For example, `max-file-size` is now `DataSize` type. I think maintaining a regex in the metadata will add quite a lot of maintenance on our side, so I don't think we should do this (at least for now).
