### ISSUE TITLE
Default value for "spring.mustache.suffix" not updated

### ISSUE THREAD

**Issue by YannCebron** [spring-projects/spring-boot#10752]
in `f2c63706daef6ddca05adc6771a761593b019524` suffix was changed from ".html" to ".mustache" but metadata in `spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json` still has old value

Original report: https://youtrack.jetbrains.com/issue/IDEA-181045

**Comment by snicoll** [comment]
Thganks @YannCebron - relates to #8997
