### ISSUE TITLE
Desirable Loose coupling of sanitizer from EnvironmentEndpoint

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-projects/spring-boot#10768]
In our application, we are creating EnvironmentEndpoint bean ourself as we need to override keysToSanitise.

We also want to refresh these keysToSanitise at run time when we have any update on encrypted property sources. So I tried to use @refreshscope with it. 

we can not use @refreshscope with any endpoint bean as HandlerMapping is done to map each Endpoints to URLs. And in AbstractHandlerMethodMapping's registerHandlerMethod() we have a check for uniqueness for handler mappings.
`assertUniqueMethodMapping(handlerMethod, mapping);`
But when we use RequestScope on endpoint bean, we get two entries here as for proxy bean as well. So we get IllegalStateException due to already existing mapping for`{[/env || /env.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}.`

when we put @refreshscope with EnvironmentEndpoint as it throws exception below:
`Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map ' org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter@3c18b48e' method public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke() to {[/env || /env.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}: There is already 'org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint@69e64aa8' bean method public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke() mapped.`

Below is my configuration:

     @Configuration
     @AutoConfigureBefore(EndpointAutoConfiguration.class)
     @EnableConfigurationProperties(EndpointProperties.class)
     public class EnvironmentEndpointAutoConfiguration {

     private static final String SANITIZE_KEY_PREFIX = ".*";

    @Bean
    @RefreshScope
    public EnvironmentEndpoint environmentEndpoint(ConfigurableEnvironment environment) {
       EnvironmentEndpoint environmentEndpoint = new EnvironmentEndpoint();
       final List<String> keysToSanitize = new ArrayList<>();
       MutablePropertySources propertySources = environment.getPropertySources();
    
   
        SystemEnvironmentPropertySource sampleSources = (SystemEnvironmentPropertySource) propertySources.get("sampleSources");
        for (String name : sampleSources.getPropertyNames()) {
            keysToSanitize.add(SANITIZE_KEY_PREFIX + name);
        }
    
      if (!keysToSanitize.isEmpty()) {
          keysToSanitize.addAll(defaultKeysToSanitize("password", "secret", "key", "token", 
          ".*credentials.*", "vcap_services"));
        environmentEndpoint.setKeysToSanitize(keysToSanitize.toArray(new 
        String[keysToSanitize.size()]));
        }
        return environmentEndpoint;
      }

      private List<String> defaultKeysToSanitize(String... keysToSanitize) {
         List<String> keysList = new ArrayList<>();
         for (int i = 0; i < keysToSanitize.length; i++) {
         keysList.add(keysToSanitize[i]);
      }
      return keysList;
    }
    }
we are using spring boot 1.5.7 release version. I see some enhancement in spring boot 2.0 but that seems not released yet.
We have external configuration using spring cloud consul to have refreshing of properties at runtime. So we also tried to listen for an EnvironmentChangeEvent and update the keys.

But we get environmentEndpoint as null in listener for an `EnvironmentChangeEvent`. and only through environmentEndpoint we can update the keys.
Can we loose coupled `Sanitizer` with `EnvironmentEndpoint` by creating bean through Configuration and provision to override that with `@ConditionalOnMissingBean`. So we can mark that as `@RefreshScope` instead of `EnvironmentEndpoint`.

**Comment by wilkinsona** [comment]
> But we get environmentEndpoint as null in listener for an EnvironmentChangeEvent

That doesn't sound right. If your listener is a bean (and that's what I'd expect in this case), an injected dependency shouldn't be null.

**Comment by JagmohanSharma** [comment]
Yes listener is a bean. Actually these property sources are processed through `ApplicationContextInitializer` which basically gets called at very startup bootstrap level. Even EndpointAutoConfiguration executed after this where currently we are creating `EnvironmentEndpoint ` bean. 

So when `EnvironmentChangeEvent ` get published from these `ApplicationContextInitializer`, we do not have bean available at that moment.

**Comment by wilkinsona** [comment]
If an `EnvironmentChangedEvent` is published before the `EnvironmentEndpoint` is created, you don't need to worry about updating its settings. They should be up-to-date when it's created and then you only need to worry about subsequent changes. If that approach doesn't work, please provide a minimal sample that illustrates the behaviour you have described.

**Comment by JagmohanSharma** [comment]
`EnvironmentEndpoint` constructor takes default keysToSanitize. but we need to pass our encrypted property keys as well here in this list of keysToSanitize. So we are going with option of creating environmentEndpoint bean.

And I checked that when we have any RefreshEvent where our context is reloaded. Then also we are getting EnvironmentEndpoint bean as null in these listeners of `EnvironmentChangedEvent `. 

I will upload a sample app with this configuration.

**Comment by JagmohanSharma** [comment]
Yes I checked we get this bean available on refreshEventListeners. 
But here issue arise for start up time, as if we go with `EndpointAutoConfiguration` default bean creation then we will not have our additional property keys in keysToSanitize. 

So solutions would be have seperate bean creation for `EnvironmentEndpoint ` and override keysToSanitize there and then use `EnvironmentChangeEvent` listeners to update this on further refresh events. right?

**Comment by wilkinsona** [comment]
Right. I believe that will work. If it does not, please comment and we can re-open this issue.
