### ISSUE TITLE
Fix Password Encoding for Default user

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#10762]
The code in [AuthenticationManagerConfiguration](https://github.com/spring-projects/spring-boot/blob/35c6b83fce86a83e4b2b9ec9fb5cbe0646eb23a5/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.java#L56-L62) assumes a `PasswordEncoder` of `NoOpPasswordEncoder` which was the default of Spring Security until recently. Now the default is `PasswordEncoderFactories.createDelegatingPasswordEncoder()`.

This is the un-tested version of the updates that should be made:

```java
public class AuthenticationManagerConfiguration {
	private static final Log logger = LogFactory
			.getLog(AuthenticationManagerConfiguration.class);
	@Autowired(required = false)
	private PasswordEncoder encoder = PasswordEncoderFactories.createDelegatingPasswordEncoder();
	@Bean
	public InMemoryUserDetailsManager inMemoryUserDetailsManager() throws Exception {
		String password = UUID.randomUUID().toString();
		logger.info(String.format("%n%nUsing default security password: %s%n", password));
		String encodedPassword = this.encoder.encode(password);
		return new InMemoryUserDetailsManager(
				User.withUsername("user").password(encodedPassword).roles().build());
	}

}
```

A similar change needs to be done in [ReactiveAuthenticationManagerConfiguration](https://github.com/spring-projects/spring-boot/blob/35c6b83fce86a83e4b2b9ec9fb5cbe0646eb23a5/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/reactive/ReactiveAuthenticationManagerConfiguration.java)

**Comment by wilkinsona** [comment]
Some of the samples declare their own `InMemoryUserDetailsManager` so they'll need to be updated too. Something like this I think:

```java
	@Bean
	public InMemoryUserDetailsManager inMemoryUserDetailsManager(
			ObjectProvider<PasswordEncoder> passwordEncoder) throws Exception {
		return new InMemoryUserDetailsManager(User.withUsername("user")
				.password(passwordEncoder
						.getIfAvailable(
								PasswordEncoderFactories::createDelegatingPasswordEncoder)
						.encode("password"))
				.roles("USER").build());
	}
```

**Comment by rwinch** [comment]
@wilkinsona Thanks. Since the sample knows there is no `PasswordEncoder` for those I'd recommend using 

```java
User.withDefaultPasswordEncoder().username('user").password("password").roles("USER").build()
```

**Comment by wilkinsona** [comment]
Thanks for the tip; that's a lot less code.

**Comment by wilkinsona** [comment]
Work in progress on getting this working again is [here](https://github.com/wilkinsona/spring-boot/tree/gh-10762). The Actuator custom security sample still fails with these changes so there's more to do, although I'm not quite sure what that is just yet.
