### ISSUE TITLE
Upgrade Spring-Boot to Selenium 3.6 and HtmlUnit 2.27/2.28

### ISSUE THREAD

**Issue by Ben1980** [spring-projects/spring-boot#10760]
Please upgrade to [Selenium 3.6](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.seleniumhq.selenium%22) and [HtmlUnit 2.27 or 2.28](https://search.maven.org/#artifactdetails%7Cnet.sourceforge.htmlunit%7Chtmlunit%7C2.27%7Cjar) if possible.
Selenium 2.53.1 is quite outdated and newer Selenium version does not work together with Spring-Boot if dependencies are not overridden.

**Comment by wilkinsona** [comment]
2.0 is already using Selenium 3.6 and HtmlUnit 2.27. 1.5.x cannot jump to a new major version of Selenium.

**Comment by wilkinsona** [comment]
Duplicate of #10491 and #9482.
