### ISSUE TITLE
SpringBoot v2.0.0.M5 Eureka Server problem

### ISSUE THREAD

**Issue by PiemonJ** [spring-projects/spring-boot#10777]
when i use springBoot v2.0.0.M5 ,i  always occur "Error creating bean with name 'requestMappingHandlerMapping'", and i havent turn on mvc,the dependency is only the <spring-cloud-starter-eureka-server>,without others.  but if i use SpringBoot v2.0.0.M3,this problem dont occur.
i dont find the  reason,if this a bug ,hope as soon as possible to solve.

and in the SpringBoot v2.0.0.M5,the annotation "@Value"  make some mistack some times.

wish Spring is better than better~~

**Comment by wilkinsona** [comment]
This is a Spring Cloud problem. It does not yet support Spring Boot 2.0.0.M5.
