### ISSUE TITLE
gradle plugin doesn't seem to prefix jars by group ID on conflict

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#10778]
Bug report

The new gradle plugin doesn't seem to prefix group ID on conflict on artifact name when packaging BOOT-INF/lib

---

Using start.spring.io, I create a gradle project with sleuth and zipkin selected for spring boot 2.0.0 SNAPSHOT

There are two zipkin jars which collide instead of prefixing the group ID:

```bash
$ jar -tvf ./build/libs/demo6-0.0.1-SNAPSHOT.jar |grep zipkin
  2221 Thu Oct 26 20:27:48 SGT 2017 BOOT-INF/lib/spring-cloud-starter-zipkin-2.0.0.BUILD-SNAPSHOT.jar
 41188 Thu Oct 26 20:27:48 SGT 2017 BOOT-INF/lib/spring-cloud-sleuth-zipkin-2.0.0.BUILD-SNAPSHOT.jar
 33698 Thu Oct 26 20:27:50 SGT 2017 BOOT-INF/lib/zipkin-reporter-1.1.2.jar
307701 Thu Oct 26 20:27:50 SGT 2017 BOOT-INF/lib/zipkin-2.2.1.jar
130788 Thu Oct 26 20:27:50 SGT 2017 BOOT-INF/lib/zipkin-2.2.1.jar
```

If you change to maven, the group ID is prefixed and avoids this conflict:
```bash
$ jar -tvf target/demo6-0.0.1-SNAPSHOT.jar|grep zipkin
  2221 Thu Oct 26 10:57:58 SGT 2017 BOOT-INF/lib/spring-cloud-starter-zipkin-2.0.0.BUILD-SNAPSHOT.jar
 41188 Thu Oct 26 10:56:16 SGT 2017 BOOT-INF/lib/spring-cloud-sleuth-zipkin-2.0.0.BUILD-SNAPSHOT.jar
307701 Sat Oct 14 05:59:50 SGT 2017 BOOT-INF/lib/io.zipkin.java-zipkin-2.2.1.jar
 33698 Sat Oct 14 14:34:44 SGT 2017 BOOT-INF/lib/zipkin-reporter-1.1.2.jar
130788 Sat Oct 14 05:59:34 SGT 2017 BOOT-INF/lib/io.zipkin.zipkin2-zipkin-2.2.1.jar
```

If you use gradle, but 1.5.9-SNAPSHOT of spring boot, it prefixes properly

```bash
$ jar -tvf ./build/libs/demo6-0.0.1-SNAPSHOT.jar |grep zipkin
  2190 Tue Oct 24 08:44:40 SGT 2017 BOOT-INF/lib/spring-cloud-starter-zipkin-1.3.0.RC1.jar
 41058 Tue Oct 24 08:42:58 SGT 2017 BOOT-INF/lib/spring-cloud-sleuth-zipkin-1.3.0.RC1.jar
307701 Sat Oct 14 05:59:50 SGT 2017 BOOT-INF/lib/io.zipkin.java-zipkin-2.2.1.jar
 33698 Sat Oct 14 14:34:44 SGT 2017 BOOT-INF/lib/zipkin-reporter-1.1.2.jar
130788 Sat Oct 14 05:59:34 SGT 2017 BOOT-INF/lib/io.zipkin.zipkin2-zipkin-2.2.1.jar
```

**Comment by wilkinsona** [comment]
This was only possible in 1.x as the Gradle plugin made the faulty assumption that every dependency packaged in a fat jar would have a group ID. That's not the case in Gradle so that assumption has been removed in the 2.0 plugin. This means that it's no possible for a fat jar or war to include dependencies from any location which Gradle supports. A downside is that it's no longer possible to include the group ID in the name of a jar in `BOOT-INF/lib`. However, it's worth noting that building a standard war file with Gradle will exhibit the same problem with the two Zipkin dependencies. If it's common from them to be used together, the ideal solution would be for one of them to be renamed.

In the meantime, the name clash in Zipkin's artifacts can be worked around by customising that task that creates the archive to rename the files. For example, the following will work if they've both been resolved from a Maven repository and stored in the corresponding location in Gradle's cache:

```groovy
bootJar {
	rootSpec.filesMatching('**/*.jar', { jar ->
		String groupId = jar.file.parentFile.parentFile.parentFile.parentFile.name
		jar.name = "$groupId-${jar.name}"
	})
}
```

You may also want to consider setting the task's duplicates strategy to catch problems like this in the future:

```groovy
bootJar {
	rootSpec.duplicatesStrategy = DuplicatesStrategy.FAIL
}
```

**Comment by adriancole** [comment]
Are you saying that gradle cannot access group id information where it exists anymore? If so, if you know the gradle issue that made this decision so I can escalate there? Zipkin is not the only project that has this issue.

**Comment by adriancole** [comment]
Basically I am trying to understand if you are technically limited by gradle (to access group ID where it exists even if some artifacts dont) or if this is a policy decision in this codebase. If the former, maybe I can help shine a light on this problem before it bites others (ex this can happen with okhttp too)

**Comment by adriancole** [comment]
@JakeWharton heads up!

**Comment by wilkinsona** [comment]
The Gradle way is to use a `FileCollection` to control the archive's contents. At that point all you have is a collection of files with no (easy?) way to map them back to the dependencies that may have been resolved from a Maven repository and would, therefore, have a group ID that could be used. See Gradle's own [War task for example](https://github.com/gradle/gradle/blob/6fa3e84fd93fe74dd1db0236cfb04f34cd9b08e2/subprojects/plugins/src/main/java/org/gradle/api/tasks/bundling/War.java#L57).

Given that our behaviour aligns with the behaviour of Gradle's own war task, I think we're limited by Gradle here. We might be able to jump through all sorts of hoops to create a mapping between a file in the collection and the dependency in the dependency graph but I think we'd be repeating one of the mistakes we made in 1.x if we tried to do so.

**Comment by adriancole** [comment]
In the mean time I will try a hack which is to misalign the versions of the two jars slightly. Maybe this will work for now..

**Comment by adriancole** [comment]
verified manually that misaligning the version number works. This'll do

**Comment by adriancole** [comment]
Anyway for closure, the tuple artifact-version will make this a rare clash. If only FS is available only thing I could think of in the last 24hrs is to crack open the jar and look at META-INF/maven/ to figure out the group Id.

for now, fine with the closed status as this is rare and there's a couple workarounds that don't require upstreams to rename their projects (simply skewing versions is something anyone can do)

**Comment by andy-fowler** [comment]
This issue just bit me when migrating to spring-boot-2.0.0.  We have several internal libraries which use the same artifactId & version and differ only in there groupId.  I got around it by adding for following snippet to the gradle build:

```
bootJar {
  rootSpec.filesMatching('**/*.jar', { jar ->
    jar.name = UUID.randomUUID().toString() + "-" + jar.name
  })
}
```

Seems to work fine.  Is there any downside to this solution ?
Alternative could be appending a file hash to the name which would at least result in a reproducible output.

If this type of solution is acceptable, could it be added to the spring boot gradle plugin ?

**Comment by adriancole** [comment]
not sure all the options not yet enumerated.. mainly you have to look at
the file somehow I think to resolve this. If you could, you could look at
java manifest module info or maven properties etc. Either place has
potentially disambiguating info in it, in a fashion determined by those
packaging the artifact. Again I think there's some question about
abstraction and possibly if feels to sneaky to try I guess?

**Comment by wilkinsona** [comment]
> Seems to work fine. Is there any downside to this solution ?
Alternative could be appending a file hash to the name which would at least result in a reproducible output.

As you've hinted, the downside is that your build won't be reproducible. A hash would address that downside.

> If this type of solution is acceptable, could it be added to the spring boot gradle plugin ?

I don't think so. One of the main goals of Boot 2.0's Gradle plugin was to align more closely with Gradle's way of doing things and to allow and encourage people to use those mechanisms when needed. If we built something into Boot to disambiguate the file names, people would want to be able to configure it. By the time we made it configurable, we'd be reinventing what Gradle can already do with `filesMatching`.

**Comment by rcusters** [comment]
We also encountered this issue during our upgrade. Why wasn't the groupId kept _when present_ to avoid breaking things?

**Comment by philwebb** [comment]
@rcusters See [this comment](https://github.com/spring-projects/spring-boot/issues/10778#issuecomment-339951574) above, specifically:

> The Gradle way is to use a FileCollection to control the archive's contents. At that point all you have is a collection of files with no (easy?) way to map them back to the dependencies

**Comment by adriancole** [comment]
checking the archive for a file pattern corresponding to the maven file added by default might help. on clash look for this https://github.com/spring-projects/spring-boot/issues/10778#issuecomment-339992328

it of course would be nicer if gradle could retain properties in its file collection, but I guess someone must have asked for this and got turned down
