### ISSUE TITLE
ApplicationPid can no longer write a file that doesn't exist

### ISSUE THREAD

**Issue by kiravspace** [spring-projects/spring-boot#10784]
In 1.5.x version, using `ApplicationPidFileWriter`, it was created automatically even if there is no pid file.
However, in 2.0.0 version, The `assertCanWrite` method in the` ApplicationPid` class causes an error if the pid file does not exist before running `SpringApplication`.
i think, the target of the `assertCanWrite` method should be the parent directory of the pid file, not the pid file.

**Comment by wilkinsona** [comment]
Thanks for the report. Looks like a regression in M4 introduced by the changes made for https://github.com/spring-projects/spring-boot/issues/9922. Checking the parent directory's a good suggestion, but I think we also need to check the pid file itself but only if it already exists, i.e. to check that it can be overwritten.

**Comment by kiravspace** [comment]
Thank you for answer.
But now, if you do not have a pid file, you will get an error.
It would be better to check the parent directory and raise an exception if the pid file exists.
The application's pid file must be unique. Also, I think that the pid file will be deleted when the application exits.
In other words, I think that the pid file already exists is wrong.
I also agree that if the pid file exists, it should be overwritten.
If so, how about checking only if the pid file exists in the `assertCanWrite` method?

**Comment by wilkinsona** [comment]
> If so, how about checking only if the pid file exists in the assertCanWrite method?

That's what I was proposing above.
