### ISSUE TITLE
Different Behavior `ConfigurationProperties`

### ISSUE THREAD

**Issue by zzt93** [spring-projects/spring-boot#10791]
When I try to bind yml config to a class using `ConfigurationProperties`, it has different behavior for `map` and `list` mapping.

Sample application.yml:
```java
a:
  l: ["i","a","b"]
  m:
    "b": 2
```
Sample mapping class:
```java
  private List<String> l = Lists.newArrayList("xx", "yy");
  private Map<String, Object> m = new HashMap<>();

  public YmlConfig() {
    m.put("a", 1);
  }

  public List<String> getL() {
    return l;
  }

  public void setL(List<String> l) {
    this.l = l; // size is 3, "i", "a", "b"
  }

  public Map<String, Object> getM() {
    return m;
  }

  public void setM(Map<String, Object> m) {
    this.m = m; // size is 2
  }
``` 
As we can see, both `list` and `map` have default values and configuration settings in yml. The `list` is cleared before add new settings, but `map` keeps the default value.

Full code can be found [here](https://github.com/zzt93/Daily-pracitce/blob/master/java/knowledge/schedule/src/main/java/com/example/demo/YmlConfig.java).

**Comment by wilkinsona** [comment]
Duplicates #9137
