### ISSUE TITLE
Add exception for invalid property value

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10794]
We have checks in various places that either use the value of a property to check something or validate that the value has an expected structure. Most of the time we throw a basic `IllegalArgumentException` or `IllegalStateException` for those.

Having one or more dedicated exceptions for such cases would allow us to provide more information and a relevant `FailureAnalyzer`.

We already have `ResourceNotFoundException` that should be merged in this hierarchy somehow (see also #7542). Perhaps `InvalidConfigurationPropertyNameException` could be as well under a generic `InvalidConfigurationPropertyException`

**Comment by philwebb** [comment]
Seems like a nice enhancement. I can't see any downsides.
