### ISSUE TITLE
Upgrade to Spring Data Kay SR1

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#10793]
Note, that this needs an upgrade of `neo4j-og.version` to 3.0.1 as well as it ships a binary incompatible change (exceptions moved to a sub-package). Without that upgrade Spring Data Neo4j based projects won't work OOTB.

**Comment by wilkinsona** [comment]
Duplicates #10759

**Comment by wilkinsona** [comment]
Also, see https://github.com/spring-projects/spring-boot/issues/10789 for the OGM upgrade.

**Comment by olivergierke** [comment]
Cool, thanks. I just ran into the incompatibility issue giving our examples a test run on our snapshots before triggering the release and wanted to avoid you guys running into the glitch unprepared :).
