### ISSUE TITLE
spring-boot-starter-cache does not allow TTL configuration for Redis cache

### ISSUE THREAD

**Issue by ryonday** [spring-projects/spring-boot#10795]
With current Spring Boot 2.0-SNAPSHOT using `spring-boot-starter-cache`, there is no possible fine-grained tuning for auto-created Redis caches. 

Other cache systems, such as Caffeine, have very fine-grained control over features like TTL.

Redis, although offering TTL, does not have similar options for the cache configuration.

**Comment by snicoll** [comment]
@ryonday Spring Boot does not provide the Redis implementation. The very fine-grained control you're mentioning isn't exposed by Spring Boot at all (it's a caffeine feature). Please raise this against the Spring Data Redis project

**Comment by maciejwalkowiak** [comment]
It seems like Spring Data Redis already provides fine grained control over TTL per cache name: https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/cache/RedisCacheConfiguration.html#entryTtl-java.time.Duration-

**Comment by ryonday** [comment]
I apologize for being unclear; the problem was mine, and I apologize if this truly is the wrong place for this issue, but my question was relevant to Spring Boot's caching auto configuration, provided via `spring-boot-autoconfigure`.

Looking at `org.springframework.boot.autoconfigure.cache.CacheProperties` I see that it has some form of fine-grained configuration for most cache types (line numbers are for the current `SNAPSHOT` as of this writing; the package for classes mentioned is `org.springframework.boot.autoconfigure.cache` unless otherwise noted):
* CouchBase:
    * You can supply an explicit expiration (`CacheProperties:143`, `CouchbaseCacheConfiguration:39`)
* Caffeine:
    * You can supply a String spec, which from digging I see allows an expiration (`CacheProperties:154`, `CaffeineCacheConfiguration:66`)

And so on. But Redis seems to be extremely bare bones by comparison:
* There is no Redis section in `CacheProperties` at all
* Let's look in `RedisCacheConfiguration`:
    * It invokes only the default implementation of `RedisCacheManager.builder()`
    * The builder actually has a wide variety of options
        * `.entryTtl(Duration)`
        * `prefixKeysWith(String)`
        * etc

This is especially sad because even though you can declare a `CacheManagerCustomizer`, but there is really no way to customize a `RedisCacheManager` in any sort of meaningful way, because you _cannot access the default configuration_ and (it seems?) the caches themselves have not yet been initialized, so you cannot change individual cache configurations.

Essentially, the issue here is that not only does auto configuration of a Redis cache not expose any options, you cannot change any configurations at all through a `CacheManagerCustomizer`. 

Ideally, the final state here could be one of:
* Exposing options through `CacheProperties` and making Redis a first-class caching citizen
* Allowing injection of `org.springframework.boot.autoconfigure.data.redis.RedisProperties`  (but this class does not allow definition of a TTL as this class is for connection params.
* Allowing injection of a `RedisCacheConfiguration` defined as a `@Bean` in a `@Configuration`. and using the `cacheDefaults` method to use it
* Allowing post-initialization configuration of caching parameters.

Again, I apologize for the terseness and uselessness of my initial issue. Everyone's time is valuable and I'm sorry to have wasted yours with throw-away, unclear text. Hopefully this makes the problem and possible solutions easier to digest. 

I'm happy to work on a PR for this if desired.

**Comment by snicoll** [comment]
@ryonday there is no fine-grained tuning per cache using `application.properties` (it is deliberate to avoid programming by properties):

* `Caffeine `: the `spec` is global for all caches
* `Couchbase`: the expiration applies for all caches

Having said that, we can expose default options in `CacheProperties` for Redis. 

Other cache libraries offer a fine-tuned mechanism using a dedicated configuration file and/or an SPI (`ehcache.xml`, the `JCache` API). I am in favour of improving the `Redis` support if such callback is necessary.

If you're willing to work on a PR I am happy to review it.

**Comment by ryonday** [comment]
I have a pull request open for this [here|https://github.com/spring-projects/spring-boot/pull/10944].

**Comment by snicoll** [comment]
Closing in favour of PR #10944
