### ISSUE TITLE
SpringApplication.run(Application.class, args) occured RuntimeException , yet didn't print the stacktrace

### ISSUE THREAD

**Issue by counterFish** [spring-projects/spring-boot#10808]
I customized mybatis sqlSessionFactory in xml which included pageHelper plugins that i didn't add to pom, so it caused ClassNotFound exception which called BeanCreationException. 
 &nbsp;&nbsp; However ,since 'run' method needn't try-catch which it can throw ,in my case , the exception was thrown without logging the stacktrace, Why? It turned out that I run springboot application and it stopped without error logs, unless i try-catch it and e.printStackTrace manually.
&nbsp;&nbsp;  Excuse me, I hava said more than  needed in stackoverflow https://stackoverflow.com/questions/46992428/springboot-failed-to-start-yet-no-exception-log-was-print-why

**Comment by snicoll** [comment]
Please don't cross post.

Also, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by counterFish** [comment]
So i can just wait..................

**Comment by counterFish** [comment]
1.5.8 didn't work for me
