### ISSUE TITLE
Converter beans are not registered with @WebMvcTest or @WebFluxTest

### ISSUE THREAD

**Issue by pchudzik** [spring-projects/spring-boot#10802]
Not sure if it is a bug or deliberate decision.

With class:

```java
@RequiredArgsConstructor
public class Id implements Serializable {
  private final UUID id;
}
```

To make it work as method parameter in `@Controller` I need to either implement `org.springframework.core.convert.converter.Converter<String, Id>` or create and register old plain `PropertyEditor` using `@InitBinder`.

It is very easy to implement Converter and annotate class with `@Component` or whatever but it will not be picked up automatically when writing integration tests using `@WebMvcTest`. To make it work with Converter I have to write custom annotations/import custom annotations/do some extra coding to make it work.

To make it working smoothly in tests I have to create `@ControllerAdvice` in which I have to `@InitBinder` and register custom property editor which I have to implement...

The question is: Maybe [WebMvcTypeExcludeFilter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTypeExcludeFilter.java) should have `Converter` in the `DEFAULT_INCLUDES` list? Is it missing component or deliberate decision not to include `Converters` when setting up the context for the `WebMvcTests`?

**Comment by snicoll** [comment]
Looks similar to #10648

**Comment by pchudzik** [comment]
workaround is to register converter using @ControllerAdvice annotation.

Like this:
```
@ControllerAdvice
class IdConverter implements Converter<String, Id> {
	@Override
	public Id convert(String source) {
		return new Id(source);
	}
}
```
