### ISSUE TITLE
The Spring Boot Gradle plugin behaves differently when used in a root project compared to a sub project.

### ISSUE THREAD

**Issue by opersson** [spring-projects/spring-boot#10823]
The Spring Boot Gradle plugin behaves differently when used in a root project compared to a sub project.

The use case is that we have a maven project that has io.spring.platform:platform-bom as parent. 
The maven project then extends the dependencyManagement by adding additional dependencies.
It also overrides the version of some of the dependencies that comes from spring.

This maven project is then imported as a mavenBom in a gradle project using the io.spring.dependency-management plugin.
The gradle project will build a spring-boot application, and therefore adds the plugin org.springframework.boot.

When the spring boot plugin is applied in a root gradle plugin the dependencies are the versions that were specified in the bom file, but when applied in a subproject the versions of the dependencies are the original versions as specified in Spring.

The expected behaviour is to have the versions specified by the mavenBom in both cases.

I've created some sample projects that illustrates the issue.
The maven bom project has org.springframework.boot:spring-boot-starter-parent as parent and overrides the versions of elasticsearch and commons-collections. Elasticsearch is a newer version and commons-collections is an older version.
The two gradle projects are small spring boot applications, gradle-root-project contains the source directly in the root project, while gradle-sub-project contains an identical application in a sub project.
Install the maven artifact to the local repo and then run the gradle applications with ./gradlew bootRun.
They will both print to the console the versions of elasticsearch and commons-collections that they have available.

[example.zip](https://github.com/spring-projects/spring-boot/files/1427592/example.zip)

**Comment by wilkinsona** [comment]
Thanks for the example. The difference in behaviour is due to ordering differences in the two projects. When multiple imported boms manage the same dependency, the dependency management in the last bom that was imported wins. In your sub-project arrangement, the Spring Boot plugin is being applied after the `allprojects` configuration has configured some dependency management. Applying the Spring Boot plugin implicitly imports its bom which then takes precedence over the dependency management that you configured earlier.

**Comment by opersson** [comment]
I am aware why it happens, but not why it has to be this way. The Spring Boot plugin is needed in order to build the Spring Boot applications, but why can it respect that there already is a differently configured dependency management if the dependencies it require are already available?
Or is there a way to build the applications without using the plugin?

There are several ways to work around the problem, but none that I've found that does not include duplicated configuration or overriding the dependency versions in multiple projects.

**Comment by wilkinsona** [comment]
> why can it respect that there already is a differently configured dependency management if the dependencies it require are already available?

That would only be possible if the imported bom was resolved at configuration time which will have a negative effect on build performance. We'd also have to somehow second guess what behaviour you wanted: override existing dependency management, replace it entirely, don't do anything, etc. I don't think it's possible to anything more than consider all of the imported boms in order. The dependency management plugin currently lets the last bom win. There's an open issue that may add some more options here:

 - https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/160

With that said, we have made some improvements in this area in Spring Boot 2.0's Gradle plugin. It will now only configure its dependency management in reaction to your own configuration explicitly applying the dependency management plugin. This provides you with more control over when Boot's dependency management is configured and should make it easier to get the ordering right.

> Or is there a way to build the applications without using the plugin?

Yes, that's possible. There required layout of an executable jar is [described in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#executable-jar). You could write your own Gradle task or plugin to produce an archive in the required layout if you wish.

**Comment by opersson** [comment]
Thanks for the answer.
Looking forward to 2.0, but unfortunately it won't make any difference in this case since we are already dependent on the dependency management plugin.
