### ISSUE TITLE
Actuator endpoint /refresh not working with boot 1.5.8

### ISSUE THREAD

**Issue by nitinkunal** [spring-projects/spring-boot#10829]
I am building a spring boot client using refresh scope on my bean to load property file changes on the fly from config server.
I am using spring boot 1.5.8 .
when i hit localhost:8080/refresh from client 
this is log message
2017-10-30 21:26:59.725  WARN 2072 --- [nio-8080-exec-8] o.s.web.servlet.PageNotFound             : Request method 'GET' not supported
NOTE: 
localhost:8080/health -- is working

**Comment by spencergibb** [comment]
/refresh is part of spring-cloud-commons, not spring-boot

**Comment by wilkinsona** [comment]
Thanks, @spencergibb.

**Comment by nitinkunal** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>myproject</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.8.RELEASE</version>
	</parent>


	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Dalston.SR4</spring-cloud.version>
	</properties>


	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>




	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>



	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by nitinkunal** [comment]
I have all the dependency in pom and have checked the avilability of spring-cloud-commons in the dependency tree.

**Comment by wilkinsona** [comment]
@nitinkunal You are commenting in the wrong place. As @spencergibb already pointed out, the refresh endpoint is part of Spring Cloud. Also, AFAIK, you need to be sending a `POST` request to it, not a `GET` request.

**Comment by spencergibb** [comment]
@wilkinsona is correct on both counts.

**Comment by nitinkunal** [comment]
Thanks both of you.Issue resolved .The request was POST as you mentioned it 
Have a great day

**Comment by huskyui** [comment]
@wilkinsona thanks
