### ISSUE TITLE
'jackson-annotations' dependency missing in Spring Boot BOM

### ISSUE THREAD

**Issue by evpaassen** [spring-projects/spring-boot#10825]
The documentation mentions the dependency `com.fasterxml.jackson.core : jackson-annotations` (version 2.8.0) to be included in the Spring Boot BOM, but it's looks like it is not. Furthermore, the version in the docs is out of sync with the other Jackson 2 components, which are at version 2.8.10. (The same issue exists when using Spring IO Platform.)

[jackson-annotations at Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.core%22%20AND%20a%3A%22jackson-annotations%22)

**Comment by wilkinsona** [comment]
It wouldn't be in the docs if it wasn't in the bom. The version is managed by Jackson's bom which Boot imports. It's 2.8.0 as the dependency doesn't change in maintenance releases of Jackson. See https://github.com/FasterXML/jackson-bom/issues/4.

**Comment by evpaassen** [comment]
Thanks for you reply. My bad, indeed. I entirely overlooked the fact that Jackson has a separate BOM which is being included. I'm sorry for your trouble.
