### ISSUE TITLE
third part project spring starter naming confusion

### ISSUE THREAD

**Issue by leo3877** [spring-projects/spring-boot#10821]
Question

I have a demo project, there are two modules: demo-a and demo-b, how to name starter?
 Is `demo-a-spring-boot-starter` and `demo-b-spring-boot-starter`
 or `demo-spring-boot-starter-a` and `demo-spring-boot-starter-b` ?

**Comment by wilkinsona** [comment]
We don't use GitHub issues for questions. In the future, please come and chat on Gitter for this sort of thing.

The starter's name should end with `-spring-boot-starter`. So, for your two examples:

- `demo-a-spring-boot-starter`
- `demo-b-spring-boot-starter`
