### ISSUE TITLE
Option to generate native app when using Java 9

### ISSUE THREAD

**Issue by TheKojuEffect** [spring-projects/spring-boot#10838]
Since Java 9 supports creating native apps using jlink, would it make sense to have an option to generate native app? Maybe by using spring-boot gradle/maven plugin.

**Comment by philwebb** [comment]
It's an interesting suggestion but I think it might involve quite a lot of work and take time away from core Spring Boot features that we could be developing. It looks like there is already a [Maven JLink Plugin](https://maven.apache.org/plugins/maven-jlink-plugin/index.html) in the works so perhaps once that is stable we could try to ensure it support Spring Boot fat jars.
