### ISSUE TITLE
Artifactory upload order is still inconsistent

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10832]
See https://github.com/spring-io/artifactory-resource/issues/4

**Comment by izeye** [comment]
This looks resolved in https://github.com/spring-io/artifactory-resource/issues/4

**Comment by wilkinsona** [comment]
It is, but we need a release of the resource and to update Boot to use that release. That should happen for M7 so we don’t release using a snapshot of the resource.
