### ISSUE TITLE
Drop LevelRemappingAppender

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10842]
spring-boot-features.adoc contains a note that is no longer the case.

**Comment by wilkinsona** [comment]
Now that we no longer remap Thymeleaf's logging levels, the remapping appender isn't really used. It's remaps `org.springframework.boot.actuate.endpoint.jmx` but that's a remnant of the old Actuator endpoint infrastructure and, as far as I can tell, is no longer necessary.

**Comment by caseyjmorton** [comment]
It would be nice if this was deprecated first, giving those of us who use this directly a little bit of warning.
