### ISSUE TITLE
spring.datasource.tomcat.* properties not picking up in case of multiple dataSources.

### ISSUE THREAD

**Issue by nikhil-sahu** [spring-projects/spring-boot#10845]
**application.properties:**

    spring.datasource.time-between-eviction-runs-millis=600000
    spring.datasource.remove-abandoned=true
    spring.datasource.remove-abandoned-timeout=900
    spring.datasource.log-abandoned=true
    spring.datasource.log-validation-errors=true

**Configuration File:**

    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    @EnableJpaRepositories(basePackages = {"***********"})
    public class StoreDbConfig {

        @Bean
        @Primary
        @ConfigurationProperties("spring.datasource")
        public DataSourceProperties storeDataSourceProperties() {
            return new DataSourceProperties();
        }

        @Bean
        @Primary
        public DataSource storeDataSource() {
            return storeDataSourceProperties().initializeDataSourceBuilder().build();
        }

        @Bean
        @Primary
        public LocalContainerEntityManagerFactoryBean storeEntityManagerFactory() {

            HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
            vendorAdapter.setGenerateDdl(true);
            vendorAdapter.setShowSql(false);
            vendorAdapter.setDatabase(Database.MYSQL);
            HibernateJpaDialect jpd = new HibernateJpaDialect();
            LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
            factory.setJpaDialect(jpd);
            factory.setJpaVendorAdapter(vendorAdapter);
            factory.setPackagesToScan("*********");
            factory.setDataSource(storeDataSource());
            Properties properties = new Properties();
            properties.setProperty("hibernate.naming.physical-strategy", "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl");
            factory.setJpaProperties(properties);
            return factory;
        }

        @Bean
        @Primary
        public PlatformTransactionManager storeTransactionManager(EntityManagerFactory storeEntityManagerFactory) {
            return new JpaTransactionManager(storeEntityManagerFactory);
        }

    }

I am currently on spring boot 1.5.7
There already exists a stackoverflow question which do not have any answer: https://stackoverflow.com/questions/45532532/spring-boot-doesnt-pick-spring-datasource-tomcat-while-programmatically-confi

**Comment by snicoll** [comment]
Please do not cross post. We can continue the discussion on SO.
