### ISSUE TITLE
Review and update Security features documentation to reflect simplified auto-configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10844]
I think some parts of [this section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security) of the reference documentation are now out of date. For example:

> To override the access rules without changing any other auto-configured features add a `@Bean` of type WebSecurityConfigurerAdapter with `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` and configure it to meet your needs.

And 

> To override the application access rules add a `@Bean` of type WebSecurityConfigurerAdapter and use `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` if you don’t want to override the actuator access rules, or `@Order(ManagementServerProperties.ACCESS_OVERRIDE_ORDER)` if you do want to override the actuator access rules.

**Comment by manderson23** [comment]
Section 28.2 on actuator security still seems to be out of date since it mentions `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` and `@Order(ManagementServerProperties.ACCESS_OVERRIDE_ORDER)`

**Comment by mbhave** [comment]
thanks @manderson23. I've added a note in #11383 to ensure this is taken care of as part of that issue.
