### ISSUE TITLE
GenericReactiveWebApplicationContext is not refreshable

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10852]
`GenericReactiveWebApplicationContext` does not extend `AbstractRefreshableConfigApplicationContext` where as `AnnotationConfigWebApplicationContext` does. We should probably align.

**Comment by snicoll** [comment]
Could that have some side effects with devtools?

**Comment by philwebb** [comment]
I don't think so because it recreates the context. Anyway, I think we should make the `GenericReactiveWebApplicationContext` refrehable, rather then drop that support from `AnnotationConfigWebApplicationContext`.

**Comment by philwebb** [comment]
Actually, I've clearly got a little confused here. The `GenericReactiveWebApplicationContext` class mirrors `GenericWebApplicationContext` which is not refreshable. I think we need a `AnnotationConfigReactiveWebServerApplicationContext` to mirror `AnnotationConfigServletWebServerApplicationContext`.
