### ISSUE TITLE
“spring-boot-sample-tomcat-jsp”  This example in the idea of running an error, suggesting that the lack of servlet-api package, in the pom file added after the error

### ISSUE THREAD

**Issue by qiankun30** [spring-projects/spring-boot#10859]
1.5.8 version. “spring-boot-sample-tomcat-jsp”  This example in the idea of running an error, suggesting that the lack of servlet-api package, in the pom file added after the error.

**Comment by snicoll** [comment]
This is a limitation of `IntelliJ IDEA`, see for instance [this thread](https://stackoverflow.com/questions/30453269/maven-provided-dependency-will-cause-noclassdeffounderror-in-intellij)
