### ISSUE TITLE
Enable various @*Scans through profiles

### ISSUE THREAD

**Issue by happybuddha** [spring-projects/spring-boot#10855]
Enhancement : 

Currently, there is no way for a developer using modular jars in a webapp to enable the various scans (component, entity, enablejparepo etc) based on the profiles that are active/included. 
Is there a way I can define these scanning properties in individual yaml files and spring boot pick them up from a yaml ? 

I am working on a project which requires various jars to be excluded in the exclude filters - already making the Application.java look very ugly and unreadable. 

My current dilemma in form of a question is on SO  : https://stackoverflow.com/q/47046492/1083581

**Comment by philwebb** [comment]
Let's keep the conversation on stackoverflow.com rather than having a cross-post.
