### ISSUE TITLE
id field stripping from returned json in responsebody

### ISSUE THREAD

**Issue by bizlytix** [spring-projects/spring-boot#1086]
After updating to the latest spring boot, it appears that objects with an 'Id" field have this field removed from the json in the response.

**Comment by wenerme** [comment]
Got the same issuse.
This works for me, thanks @wookayin 
```
    @Override
    protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config)
    {
        super.configureRepositoryRestConfiguration(config);
        config.exposeIdsFor(SMS.class, Note.class, ChatMessage.class, ZoneMessage.class);
    }
```

**Comment by ericop** [comment]
Instead I created an alias of `id` and used the Jackson annotation `@JsonProperty("id")` which seemed to do the trick for my situation.

```
import org.springframework.data.annotation.Id;
import com.fasterxml.jackson.annotation.JsonProperty;

 public class Calculation {

    @Id private String id;

    private String equation;
    private String result;

    @JsonProperty ("id")
    private String emberId;


    public String getEmberId() {
        return id;
    }
```

**Comment by bnegrao** [comment]
@wenerme thank you. I had the issue of the id and I fixed with your trick "repositoryRestConfiguration.exposeIdsFor(Person.class);"

**Comment by idc77** [comment]
Old topic but top in search results.

If you name the id field Id instead of id it's exposed.
I'm not sure this is documented anywhere.

**Comment by ZQQ-GH** [comment]
> I had the same problem, and this solution solved mine

**Comment by ZQQ-GH** [comment]
> Instead I created an alias of `id` and used the Jackson annotation `@JsonProperty("id")` which seemed to do the trick for my situation. I was using spring-boot-starter-data-mongodb, spring-boot-starter-data-rest, spring-boot-starter-web and spring-boot-starter-parent all on version 1.2.7.RELEASE .
> 
> ```
> import org.springframework.data.annotation.Id;
> import com.fasterxml.jackson.annotation.JsonProperty;
> 
>  public class Calculation {
> 
>     @Id private String id;
> 
>     private String equation;
>     private String result;
> 
>     @JsonProperty ("id")
>     private String emberId;
> 
> 
>     public String getEmberId() {
>         return id;
>     }
> ```

I had the same problem, and this solution solved mine
