### ISSUE TITLE
Fix typos in org.springframework.boot.test.context.assertj package

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#10865]
The following classes have a copy-n-paste typo of the form "used to decorate and existing".

- `AssertableWebApplicationContext`
- `AssertableReactiveWebApplicationContext`
- `AssertableApplicationContext`
- `ApplicationContextAssertProvider`

**Comment by wilkinsona** [comment]
Well spotted, @sbrannen. And thanks for the report.

**Comment by sbrannen** [comment]
no problem, and thanks for the turbo quick fix. 😉
