### ISSUE TITLE
Move org.springframework.boot.test.Assume to test-support

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#10866]
The new class `org.springframework.boot.test.Assume` refers to "JUnit" ambiguously.

Note, however, that `org.junit.AssumptionViolatedException` is specific to JUnit 4.

Thus, use of `org.springframework.boot.test.Assume` with JUnit Jupiter (or any other testing framework) would result in a _failed test_ instead of an _aborted test_.

Since JUnit Jupiter uses `org.opentest4j.TestAbortedException` from the OTA for failed assumptions, I highly recommend that `org.springframework.boot.test.Assume` refer **explicitly** to JUnit 4 so as to avoid any confusion.

**Comment by philwebb** [comment]
See #9530. I'm tempted to move this to `spring-boot-test-support` and keep it internal to us.

**Comment by sbrannen** [comment]
If you don't plan to support it within the community, then I agree that keeping it internal would be the best choice.

**Comment by sbrannen** [comment]
Plus, if you were to migrate those tests to JUnit Jupiter and run them with the `SpringExtension`, it then becomes super easy to implement that support via a custom composed annotation that is meta-annotated with `@EnabledIf( < SpEL expression > )` 😉
