### ISSUE TITLE
Update Production Ready Features documentation to reflect that endpoint IDs are no longer configurable

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10862]

**Comment by snicoll** [comment]
Isn't that, to some extend, a duplicate of #10001 ?

**Comment by wilkinsona** [comment]
Yeah, it could be. I wanted to make sure it wasn’t missed. This issue is for correcting existing documentation that’s now incorrect rather than adding new documentation.

**Comment by snicoll** [comment]
Fair enough, let's keep it
