### ISSUE TITLE
Drop ConfigurationPropertiesBinder as Cloud is no longer using it

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10867]
@dsyer would like us to wait till we're sure that all the kinks have been ironed out, but it looks like we can drop the public binder API and probably the associated public builder API too.

**Comment by wilkinsona** [comment]
It looks to me like things are now fine from a Spring Cloud perspective. @dsyer @spencergibb can you please confirm?

**Comment by dsyer** [comment]
Yes, all tickety boo, thanks.
