### ISSUE TITLE
Support environment properties that would have worked in 1.5

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10873]
The stricter environment variable property rules in 2.0 might catch people out and it would be really nice if we could warn users that a property that previously worked now will not.

One example of this is in Spring Cloud stream. They previously would set the varaible `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES`. In 2.0 this needs to be `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES`.

**Comment by philwebb** [comment]
I've absolutely no idea how we can do this. Perhaps we can update `ConfigurationPropertySource` so that if it gets called with `getConfigurationProperty("zknodes")` it checks to see if there are any matches excluding underscores and issues a warning.

**Comment by snicoll** [comment]
You mean `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES` right?

**Comment by philwebb** [comment]
Edited 🤦‍♂️

**Comment by philwebb** [comment]
Thinking some more about this I think it should be possible to support the `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES` style in addition to `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES`. I think we should still promote the first style in documentation etc.
