### ISSUE TITLE
Upgrade to Spring Data Ingalls SR9

### ISSUE THREAD

**Issue by dyorgio** [spring-projects/spring-boot#10885]
This bug is already reported here: https://jira.spring.io/browse/DATAJPA-1209
Just including to put on roadmap.

Upgrading hibernate (core and entity-manager) to 5.2.12 solves, but it brings another problems (Ehcache incompatibilities).

**Comment by asaarnak** [comment]
Also important fix, regarding querydsl custom repo: https://jira.spring.io/browse/DATAJPA-1205
