### ISSUE TITLE
Support HTTP/2 in Jetty with Conscrypt

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#10902]
As mentioned in [the official blog post](https://webtide.com/conscrypting-native-ssl-for-jetty/), Jetty now supports TLS with Concsrypt, without changing the boot classpath or using a Java agent.

The ALPN + HTTP/2 support for that should be shipped with Jetty 9.4.8, so we'll leverage that support for HTTP/2 support in Spring Boot.

See eclipse/jetty.project#215

**Comment by olamy** [comment]
Sounds perfect. let me know if you need an hand to help

**Comment by bclozel** [comment]
@olamy Haha, indeed - good catch.
By the way, any idea about when this version should be released? A rough estimate might help me schedule this issue for a particular Spring Boot release.

**Comment by olamy** [comment]
should be within the next 2 weeks.

**Comment by olamy** [comment]
@bclozel do you have a branch somewhere with your changes?

**Comment by olamy** [comment]
@bclozel  9.4.8.v20171121 has been released
