### ISSUE TITLE
Compile warning in IDEA as lacking of '@SupportedSourceVersion' in  the class 'AutoConfigureAnnotationProcessor'

### ISSUE THREAD

**Issue by jearton** [spring-projects/spring-boot#10929]
There is a compile warning in IDEA-2017.2.5 when I add dependency `spring-boot-autoconfigure-processor`. Then I found it would be fine if adding another annotation `SupportedSourceVersion(SourceVersion.latestSupported())` onto the class `AutoConfigureAnnotationProcessor`.

The warning message is following:

```
﻿Warning:java: No SupportedSourceVersion annotation found on org.springframework.boot.autoconfigureprocessor.AutoConfigureAnnotationProcessor, returning RELEASE_6.
```

**Comment by philwebb** [comment]
I'm not sure why IDEA-2017.2.5 is producing such a warning because I think that the annotation should be optional.

From the `@SupportedSourceVersion` Javadoc:

> The latest source version an annotation processor supports.  The `getSupportedSourceVersion` method can construct its result from the value of this annotation, as done by `AbstractProcessor.getSupportedSourceVersion()`.

For `AutoConfigureAnnotationProcessor` we override the `getSupportedSourceVersion` method:

```java
@Override
public SourceVersion getSupportedSourceVersion() {
	return SourceVersion.latestSupported();
}
```

I'd raise a bug with Jetbrains and ask them to also check for a `getSupportedSourceVersion` override.

**Comment by jearton** [comment]
I cannot find the getSupportedSourceVersion method with @Override annotation  in AutoConfigureAnnotationProcessor.

I used Spring-Boot 1.5.8.RELEASE. 

The warning message is from AbstractProcessor of jdk8. If sub class not annotate or override,  the message will be shown.

Following is the source code from jdk8.

```java
/**
 * If the processor class is annotated with {@link
 * SupportedSourceVersion}, return the source version in the
 * annotation.  If the class is not so annotated, {@link
 * SourceVersion#RELEASE_6} is returned.
 *
 * @return the latest source version supported by this processor
 */
public SourceVersion getSupportedSourceVersion() {
    SupportedSourceVersion ssv = this.getClass().getAnnotation(SupportedSourceVersion.class);
    SourceVersion sv = null;
    if (ssv == null) {
        sv = SourceVersion.RELEASE_6;
        if (isInitialized())
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING,
                                                     "No SupportedSourceVersion annotation " +
                                                     "found on " + this.getClass().getName() +
                                                     ", returning " + sv + ".");
    } else
        sv = ssv.value();
    return sv;
}
```

**Comment by snicoll** [comment]
> For AutoConfigureAnnotationProcessor we override the getSupportedSourceVersion method:

No we don't. Perhaps you were looking in `ConfigurationMetadataAnnotationProcessor`?
