### ISSUE TITLE
ReactiveRedisConnectionFactory's setDatabase cant useful in spring boot 2.0 m5

### ISSUE THREAD

**Issue by lilaizhencn** [spring-projects/spring-boot#10925]
LOOK MY CODE :

```java
 @Bean
    ReactiveRedisTemplate<String, String> reactiveRedisTemplate() {
        return new ReactiveRedisTemplate<>(reactiveRedisConnectionFactory(), RedisSerializationContext.string());
    }

    @Bean
    public ReactiveRedisConnectionFactory reactiveRedisConnectionFactory() {
        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();
        config.setHostName(redisHost);
        config.setPort(redisPort);
        config.setDatabase(15);
        LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(config);
        return lettuceConnectionFactory;
    }
```

and when i query key , it has into 0 database ,  15 database query null;

**Comment by wilkinsona** [comment]
It could be that your configuration isn't being used, or there could be a problem in Spring Data REST. I can't tell from what you've shared thus far. Can you please provide a small sample project that reproduces the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
