### ISSUE TITLE
Spring Boot Application JAR Package type with JSP Not working

### ISSUE THREAD

**Issue by krishna1c** [spring-projects/spring-boot#10935]
Hi,

We tried to implement Spring Boot Application with JAR type having JSP using the following example link

Spring Boot Version: 1.5.6

**https://github.com/spring-projects/spring-boot/tree/1.5.x/spring-boot-samples/spring-boot-sample-web-jsp**

In the above example we have changed the package generation to jar and then application stopped working with the following exception 

**There was an unexpected error (type=Not Found, status=404).**

Please let us know what is the issue.

Thanks,
Vamsikrishna P.

**Comment by wilkinsona** [comment]
Please see the [relevant section of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jsp-limitations).

**Comment by krishna1c** [comment]
Is it possible to use Spring Boot Classpath (loader.path) feature with the WAR package?

**Comment by wilkinsona** [comment]
It should do but there [may be a bug which is currently awaiting investigation](https://github.com/spring-projects/spring-boot/issues/10234).
