### ISSUE TITLE
Spring Boot 1.5.8 introduced dependency on newer Tomcat Native APR lib

### ISSUE THREAD

**Issue by jlar310** [spring-projects/spring-boot#10949]
We run our Boot apps in Docker, currently on image openjdk:8-jre-alpine, which at this time is based on Alpine 3.6.2.

But when bumping Spring Boot from version 1.5.7 to 1.5.8, we found that our apps would not start because our installed version of the tomcat-native library was 1.2.12 while the Boot startup logs mentioned that 1.2.14 was required.

The exact message is: 

An incompatible version [1.2.12] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]

A newer tomcat-native package is not presently available in Alpine 3.6 without manual installation. Not something I really want to do with a Dockerfile.

In any case, my point is this: Isn't this the sort of compatibility change that should be reserved for a major or minor version bump, not just a micro/patch version bump? I could not find Boot specific discussion on version number semantics, but it is my understanding that updates to micro or patch version numbers should not break compatibility.

Of course, it's probably hard to put that genie back in the bottle now, but I felt that something should be said about this particular change.

**Comment by wilkinsona** [comment]
Thank you for bringing this to our attention. Unfortunately, I don't think that there's anything that we can or should do about it.

Spring Boot 1.5.8 upgraded to Tomcat 8.5.23 from 8.5.20. This is a micro/patch version change in a new micro/patch version of Spring Boot. Tomcat 8.5.23 upgraded from tomcat-native 1.2.12 to 1.2.14. Again, this is a micro/patch version change in a new micro/patch version of Tomcat. This seems entirely reasonable to me as all of the version changes are micro/patch version changes.

If you disagree with the Tomcat team's policy of, on occasion, requiring a new micro/patch version of tomcat-native in a new micro/patch version of Tomcat then I would recommend that you raise it with them as it is out of our control. Staying on a older and potentially vulnerable version of Tomcat by default isn't a realistic option.

Spring Boot 1.5.8 should remain compatible with earlier versions of Tomcat 8.5.x as there have been no API changes. If you wish to do so you may downgrade the Tomcat version to satisfy the constraints of your deployment environment that requires you to use a specific micro/patch version of tomcat-native.
