### ISSUE TITLE
Improve Javadoc of ConditionalOnNotWebApplication

### ISSUE THREAD

**Issue by geoand** [spring-projects/spring-boot#10955]
Greetings,

While using `ConditionalOnNotWebApplication` for the first time, I checked out the source code in order to get a grasp on how it works. 
I was initially amazed at the fact that it uses the same exact `@Conditional` meta-annotation as `ConditionalOnWebApplication`, while the accompanying Javadoc provided no indications on how it's goal is actually performed.
Of course upon inspection of `OnWebApplicationCondition`, the details become clear, but I think that it would be an (admittedly minor) enhancement if some info was provided in the Javadoc of `ConditionalOnNotWebApplication`.

Thanks,
George

**Comment by snicoll** [comment]
> t I think that it would be an (admittedly minor) enhancement if some info was provided in the Javadoc of ConditionalOnNotWebApplication.

Sorry, I am not following. What info exactly?

**Comment by geoand** [comment]
I was thinking that it would be beneficial if the Javadoc would mention that this annotation works because of the fact that `OnWebApplicationCondition` inverts it's outcome when it's used by `ConditionalOnNotWebApplication` (as opposed to `ConditionalOnWebApplication`).

**Comment by geoand** [comment]
On another note, ultimately I think it would be cleaner to have an explicit `OnNotWebApplicationCondition` that would invert the result `OnWebApplicationCondition`, which in turn would not use `AnnotatedTypeMetadata` to alter it's behavior

**Comment by snicoll** [comment]
That's an implementation detail. Why do you want us to add that information to the public javadoc?

**Comment by geoand** [comment]
Although I am long time Spring Boot user this implementation detailed struck me as odd. So aside from changing the implementation as a mentioned above, I thought the Javadoc would be the easiest way to clarify the behavior.
I understand that lots of people will probably not go to the trouble to figure out why this works, so it might not make sense to fix the Javadoc. My point was just that as is (implementation and Javadoc), this annotation strikes it's user as odd :)

**Comment by snicoll** [comment]
Sorry but the public Javadoc is not meant to describe the internal implementation of `OnWebApplicationCondition`. The condition is not public so that remains an internal detail for us which IMO is perfectly fine.

**Comment by geoand** [comment]
Ok, understood.

Thank you for your time.
