### ISSUE TITLE
-Dspring.profiles.active ignored when mvn spring-boot:run

### ISSUE THREAD

**Issue by kryger** [spring-projects/spring-boot#1095]
Upgrading 1.0.2.RELEASE->1.1.0.RELEASE changed how passing profile to `mvn spring-boot:run` works, the `-Dspring.profiles.active` flag seems to be ignored. I created a simple project that reproduces the problem: https://github.com/kryger/bug-spring-maven-profiles

_(Note that `application.yml` defines port=3333, `application-production.yml` defines port=1111)_

**Steps to reproduce:**
1. Check out the project - it uses 1.1.0.RELEASE
2. `mvn spring-boot:run -Dspring.profiles.active=production` -> Tomcat starts on port 3333 (expected 1111)
3. Edit pom.xml and change `<version>` to `1.0.2.RELEASE`
4. `mvn spring-boot:run -Dspring.profiles.active=production` again -> Tomcat starts on port 1111

I had a look at 1.1.0.RELEASE's release notes but couldn't find anything that would explain this change - no idea if it's a bug or a feature :).

**Comment by lacivert** [comment]
@kryger I tried your way but I could not succeed. spring.profiles.active is not a maven/pom parameter. I think there must be another way to go on command line. Are you sure that it works? I think this issue should be opened.

By the way I am working with spring boot 1.2.5 release, maven 3, java 8u60

**Comment by lacivert** [comment]
Sorry for misunderstanding, my fault! It was about another thing but this one works:

    mvn spring-boot:run -Dspring.profiles.active="production"

**Comment by gregturn** [comment]
I have always liked "SPRING_PROFILES_ACTIVE=production mvn spring-boot:run". It's the way to pass lots of critical env variables to really any app, maven or whatever.

**Comment by clevertension** [comment]
@gregturn 
you method is work, thanks

**Comment by carloscorva** [comment]
It works using:
mvn spring-boot:run -Drun.profiles=default, primary, secondary

Please refer to: http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-profiles.html

**Comment by changjunjie** [comment]
this command works:
mvn spring-boot:run -Drun.profiles=profileName
Please refer to: http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-profiles.html

**Comment by timomeinen** [comment]
The following is ignored:
`mvn spring-boot:run -Drun.profiles=development`

However, using -Drun.jvmArguments works:
`mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=development"`

**Comment by wilkinsona** [comment]
That's the be expected if Maven forks a new JVM for the application. In your first example, the system property isn't being ignored, it's just being set in Maven's JVM rather than the application's JVM. The second example works as it ensures that the system property is passed to the JVM that's used to run the application.

**Comment by timomeinen** [comment]
Thanks @wilkinsona, that makes sense. But how does this fit to the [documentation](https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-profiles.html)? This is quite misleading:

> The profiles to enable can be specified on the command line as well, make sure to separate them with a comma, that is: mvn spring-boot:run -Drun.profiles=foo,bar

**Comment by snicoll** [comment]
@timomeinen what version of Spring Boot are you using? `run.profiles` is indeed a property of the plugin in `1.x`.

**Comment by wilkinsona** [comment]
Oops. Sorry. @snicoll has just pointed out that it's `run.profiles` which is a property of the plugin and it should pass it to the app, irrespective of which JVM it's running in so my comment doesn't apply in this case.

**Comment by snicoll** [comment]
@timomeinen alright so I think we need a sample that we can run that reproduces the behaviour you've described. Please create a separate issue with that.

**Comment by timomeinen** [comment]
Using 1.5.9.RELEASE. I will try to create a sample application.

**Comment by timomeinen** [comment]
The demo is working as expected. In my application just the logging is not working. This is because of my own configuration in logback-spring.xml as can be seen here: [#5611](https://github.com/spring-projects/spring-boot/issues/5611#issuecomment-338383711)

I am using Janino to get conditional processing in logback (because of the not working scan feature #5611): `<if condition='property("spring.profiles.active").contains("development")'>`

The problem is, that the Maven plugin won't set the `spring.profiles.active` System property. Is it possible for the plugin to forward this property as the system property `spring.profiles.active`?

That would also clarify the behaviour as given in the documentation for run.profiles:
> Convenience shortcut of specifying the 'spring.profiles.active' argument.

**Comment by snicoll** [comment]
> The problem is, that the Maven plugin won't set the spring.profiles.active System property.

It does set `spring.profiles.active` as a command-line argument (`--spring.profiles.active`). The javadoc is correct as it states "argument". It doesn't state system property there at all.

**Comment by wilkinsona** [comment]
@cyberoblivion What do you mean by "this"? No change was made as a result of this issue so there's nothing to have been merged. You should use `-Drun.profiles` to make sure that the profiles are set, irrespective of whether or not a new JVM is forked.

**Comment by cyberoblivion** [comment]
Oh sorry, yes -Drun.profiles does not seem to work in spring-boot-maven-plugin:2.0.0.RC2.
No active profiles are ever set in the RC2 version.

**Comment by wilkinsona** [comment]
My mistake, it should be `-Dspring-boot.run.profiles` in 2.0. See https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/examples/run-profiles.html for details.

**Comment by snicoll** [comment]
This is also covered in the migration guide on the wiki

**Comment by cyberoblivion** [comment]
That works thanks.

**Comment by hendisantika** [comment]
Thanks @gregturn!
Your command works for me.

**Comment by simbro** [comment]
@wilkinsona  syntax worked for me: https://github.com/spring-projects/spring-boot/issues/1095#issuecomment-369324316

**Comment by yashwanth2804** [comment]
> Sorry for misunderstanding, my fault! It was about another thing but this one works:
> 
> ```
> mvn spring-boot:run -Dspring.profiles.active="production"
> ```

This worked

**Comment by fireflyk** [comment]
I tried on spring boot 2. 
Two ways work
```
SPRING_PROFILES_ACTIVE=beta mvn spring-boot:run
```

```
mvn spring-boot:run -Dspring-boot.run.profiles=beta
```

**Comment by lovelock** [comment]
> I tried on spring boot 2.
> Two ways work
> 
> ```
> SPRING_PROFILES_ACTIVE=beta mvn spring-boot:run
> ```
> 
> ```
> mvn spring-boot:run -Dspring-boot.run.profiles=beta
> ```

Good conclusion!
However there is another question

```
mvn spring-boot:run -Djvm.Arguments="-Dspring.profiles.active=dev"
```
won't work for me (Springboot version 2.2.4.RELEASE), but when set it in IDEA, it works

![image](https://user-images.githubusercontent.com/2208731/77246568-c3c12a80-6c63-11ea-9f65-10de95ac6d9b.png)
![image](https://user-images.githubusercontent.com/2208731/77246579-e6ebda00-6c63-11ea-85f2-81e9b7c74022.png)

I wonder if it is just a property to tell IDEA to start append `-Dspring.profiles.active=dev` when starting it with `java`?

**Comment by snicoll** [comment]
`jvm.arguments` isn't a valid  command-line property, see [the maven plugin documentation](https://docs.spring.io/spring-boot/docs/2.2.4.RELEASE/maven-plugin/examples/run-system-properties.html). Please ask questions on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by bartieres** [comment]
For me this worked: `mvn spring-boot:run -Dspring-boot.run.profiles=hom`

**Comment by bglamadrid** [comment]
For Spring Boot 2 Under PowerShell, this only worked surrounding dots within quotes, for example  `mvn spring-boot:run "-Dspring-boot.run.profiles=default,local,h2,local-h2"`
Without these quotes, maven complains about unknown lifecycle phases.
And yes, `mvn spring-boot:run -Dspring-boot".run."profiles=default,local,h2,local-h2` works just the same but it's kinda counter-intuitive.
