### ISSUE TITLE
Mono<ServerResponse> always returns "text/event-stream" Content-Type from a WebFlux rest controller [2.0.0.M6]

### ISSUE THREAD

**Issue by Petitt88** [spring-projects/spring-boot#10957]
When returning a Mono<ServerResponse> from a @RestController, no matter which ServerResponseBuilder I use (notFound, ok, etc.) the response's Content-Type always becomes text-event-stream.

[Here](https://github.com/spring-projects/spring-boot/files/1455394/demo-webflux.zip) is an attached project to repro it. Just 3 super easy methods, this is how they look:
``` java
@GetMapping("/")
public Mono<ServerResponse> index() {
	// Content-Type will be text/event-stream
	return ServerResponse.notFound().build();
}

@GetMapping("/blocking")
public ServerResponse indexBlocking() {
	// Content-Type will be 404, good
	return ServerResponse.notFound().build().block();
}

@GetMapping("/person")
public Mono<ServerResponse> person() {
	// Content-Type will be text/event-stream
	return ServerResponse
			.ok()
			.contentType(MediaType.APPLICATION_JSON)
			.body(Mono.just(new Person()), Person.class);
}

[demo-webflux.zip](https://github.com/spring-projects/spring-boot/files/1455394/demo-webflux.zip)
```

**Comment by snicoll** [comment]
This is a Spring WebFlux feature so the Spring Framework issue tracker is a better place for reporting issues. Having said that, you are mixing the annotation-based model and the functional routing. The side effect is interesting and perhaps the framework team could consider changing something to make that more obvious. 

If you want to pursue this, I'd raise a [JIRA issue](https://jira.spring.io/browse/SPR).

**Comment by Petitt88** [comment]
Thank you @snicoll, I'll do that.
