### ISSUE TITLE
Logback <springProperty> are automatically added as top-level properties to the encoder when using logstash

### ISSUE THREAD

**Issue by sbuettner** [spring-projects/spring-boot#10962]
When adding a `<springProperty>` to my `logback-spring.xml` it seems like its always added to my logging output as a top-level property when using the `net.logstash.logback.encoder.LogstashEncoder`. 

Configured `<springProperty>`:
```
<springProperty scope="context" name="serviceName" source="spring.application.name" />
```

Logstash encoder configuration:
```
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <customFields>{"name": "${serviceName}"}</customFields>
</encoder>
```

Config above leads to duplicate rendering of the `<springProfile>` property `serviceName`:
```
{
"@timestamp":"2017-11-09T10:19:51.773+01:00",
"level":"INFO", ...
"serviceName":"myServiceName",
"name":"myServiceName"
}
```

The expected output would be:
```
{
"@timestamp":"2017-11-09T10:19:51.773+01:00",
"level":"INFO", ...
"name":"myServiceName"
}
```

**Comment by wilkinsona** [comment]
It's not clear to me why Logstash would render both `name` and `serviceName` or why `springProperty` would apparently be given special treatment. To help us diagnose what's going on, can you please provide a minimal sample that reproduces the problem?

**Comment by sbuettner** [comment]
@wilkinsona Sure, https://github.com/sbuettner/spring-boot-issue-10962-logback-property

**Comment by ztomic** [comment]
I've had same issue, solved with [setting includeContext to false](https://github.com/logstash/logstash-logback-encoder#context-fields).

**Comment by wilkinsona** [comment]
Thank you, @ztomic. That explains it.

**Comment by sbuettner** [comment]
Thx @wilkinsona @ztomic.
