### ISSUE TITLE
Clarification needed on springboot logging initializaation

### ISSUE THREAD

**Issue by adewumio** [spring-projects/spring-boot#10964]
**Section: 26.5 Custom log configuration** on https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html implies we don't have access to the ApplicationContext at logging initialization and yet

**Section 26.6.2 Environment properties** of same document says we can use entries from the Environment object in our logback config.  Do we have some reinitialization of logs happening once application context is completely created ?

**Comment by wilkinsona** [comment]
The environment is created and prepared before the application context.
