### ISSUE TITLE
Reference documentation for enabling endpoints is out of date

### ISSUE THREAD

**Issue by mibeumer** [spring-projects/spring-boot#10979]
Spring Boot actuator health Resource and many more does not work in 2.0.0 M6. Furthermore the IntelliJ Integration of the actuator endpoints are not working.
In Version 2.0.0 M1 it is working.

Only the following actuator resources are working:
http://localhost:8080/application/status
http://localhost:8080/application
http://localhost:8080/application/info

I have a normal spring boot application and added this in the pom.xml
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
```
I tried it in 2 projects.

Kind Regards
Michael

**Comment by mibeumer** [comment]
Okay, my fault. I must put the property endpoints.default.web.enabled=true to the application.properties.
It is here documentated: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

But it isn't jetzt in the generel guide yet: https://docs.spring.io/spring-boot/docs/2.0.0.M6/reference/htmlsingle/

**Comment by wilkinsona** [comment]
Thanks. It's a bit worse than that even. [This section](https://docs.spring.io/spring-boot/docs/2.0.0.M6/reference/htmlsingle/#production-ready-customizing-endpoints) of the documentation states that "by default, all endpoints except for shutdown are enabled" which is no longer true.

**Comment by wilkinsona** [comment]
We should wait for #10176 to be resolved before tackling this.

**Comment by philwebb** [comment]
Also #10970 and any `/heath` decision that we end up taking.

**Comment by snicoll** [comment]
This was already documented as part of #10176 and #10970 properly updated the section on `health`.
