### ISSUE TITLE
Http1.0 Connection:Keep-Alive doesn't work.

### ISSUE THREAD

**Issue by scguoi** [spring-projects/spring-boot#10988]
I have use apache http-client to send http 1.0 request for a embed tomcat spring-boot service. And I have put "Connection: Keep-Alive" in request header. But when embed tomcat spring-boot service return I found "Connection: close" in http headers.  But it works well when I deploy the Service into a tomcat. This problem is found in apache ab, when I use apache ab to run a bench mark for a spring-boot service. I have used -k param of apache ab to keep-alive but it doesn't work. If I deploy the Service into a tomcat , it will works well. I found that apache ab doesn't support http 1.x well (http://httpd.apache.org/docs/2.0/programs/ab.html). 

Here is some information I copyed from request and response.

Request:
POST /gateway http/1.0
Host: 127.0.0.1
Content-MD5: 95bfc7b803e7be6f703d6be1671bc15c
Content-Type: application/octet-stream
Content-Length: 266
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_51)
Accept-Encoding: gzip,deflate

Response:
HTTP/1.1 400 
Transfer-Encoding: chunked
Date: Mon, 13 Nov 2017 08:57:46 GMT
Connection: close

**Comment by wilkinsona** [comment]
I can't reproduce the behaviour you've described. Here's the output from curl making a request to a small sample that uses keep alive:

```
$ curl -v localhost:8080 -H "Connection: Keep-Alive"
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.46.0
> Accept: */*
> Connection: Keep-Alive
>
< HTTP/1.1 200
< Content-Type: text/html;charset=UTF-8
< Content-Language: en-GB
< Transfer-Encoding: chunked
< Date: Mon, 13 Nov 2017 09:39:32 GMT
<
<!DOCTYPE html>

<html lang="en">

<body>
	Date: 13-Nov-2017
	<br>
	Time: 09:39:32
	<br>
	Message: Hello, Andy
</body>

</html>
* Connection #0 to host localhost left intact
```

Can you please provide a small sample and step-by-step instructions that reproduce the problem?

**Comment by scguoi** [comment]
Please add --http1.0 param.
➜  ~ curl --http1.0 -v http://127.0.0.1:8080/time -H "Connection: Keep-Alive"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /time HTTP/1.0
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: Keep-Alive
>
< HTTP/1.1 200
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 13 Nov 2017 10:05:53 GMT
< Connection: close
<
* Closing connection 0
1510567553781%

**Comment by scguoi** [comment]
Please use --http1.0 param

`➜  ~ curl --http1.0 -v http://127.0.0.1:8080/time -H "Connection: Keep-Alive"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /time HTTP/1.0
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: Keep-Alive
>
< HTTP/1.1 200
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 13 Nov 2017 10:05:53 GMT
< Connection: close
<
* Closing connection 0
1510567553781%`

**Comment by scguoi** [comment]
please add --http1.0 to curl request.

```
curl --http1.0 -v http://127.0.0.1:8080/time -H "Connection: Keep-Alive"
* Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /time HTTP/1.0
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: Keep-Alive
>
< HTTP/1.1 200
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 13 Nov 2017 10:05:53 GMT
< Connection: close
<
* Closing connection 0
1510567553781%
```

**Comment by wilkinsona** [comment]
Thanks. I hadn't realised that the use HTTP 1.0 was required to reproduce the problem. However, this appears to be Tomcat's standard behaviour.

With HTTP 1.0, Tomcat's Http11Processor (which is used for both HTTP 1.0 and 1.1) will only keep the connection alive if the response has a known content length. With HTTP 1.1 it can keep the connection alive with an unknown content length by switching to chunked transfer encoding. Whether or not the connection is kept alive is controlled by the `contentDelimitation` flag in the [following code](https://svn.apache.org/viewvc/tomcat/tc8.5.x/tags/TOMCAT_8_5_23/java/org/apache/coyote/http11/Http11Processor.java?view=annotate#l1251):

```
long contentLength = response.getContentLengthLong();
        boolean connectionClosePresent = false;
        if (contentLength != -1) {
            headers.setValue("Content-Length").setLong(contentLength);
            outputBuffer.addActiveFilter
                (outputFilters[Constants.IDENTITY_FILTER]);
            contentDelimitation = true;
        } else {
            // If the response code supports an entity body and we're on
            // HTTP 1.1 then we chunk unless we have a Connection: close header
            connectionClosePresent = isConnectionClose(headers);
            if (entityBody && http11 && !connectionClosePresent) {
                outputBuffer.addActiveFilter
                    (outputFilters[Constants.CHUNKED_FILTER]);
                contentDelimitation = true;
                headers.addValue(Constants.TRANSFERENCODING).setString(Constants.CHUNKED);
            } else {
                outputBuffer.addActiveFilter
                    (outputFilters[Constants.IDENTITY_FILTER]);
            }
        }
```

For a response where the content length is known, the connection is kept alive as expected when using HTTP 1.0:

```
curl -v --http1.0 localhost:8080/test -H "Connection: Keep-Alive"
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /test HTTP/1.0
> Host: localhost:8080
> User-Agent: curl/7.46.0
> Accept: */*
> Connection: Keep-Alive
>
< HTTP/1.1 200
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 4
< Date: Mon, 13 Nov 2017 10:51:44 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
test
```

I you'd like to pursue this, we will need an example that shows HTTP 1.0 keep alive working with standalone Tomcat and not working with embedded Tomcat.
