### ISSUE TITLE
Spring Actuator not reading git.properties file

### ISSUE THREAD

**Issue by Puthiaraj1** [spring-projects/spring-boot#11007]
I am trying to implement spring actuator to fetch the git info. I can able to generate a git.properties file in default dir (build/resources/main). 
Below is my application.yml config:

```
management: 
  info:
    build:
      enabled: true
    git:
      mode: FULL
    defaults:
      enabled: true
```

**Comment by wilkinsona** [comment]
Can you please provide a sample that illustrates the problem?

**Comment by Puthiaraj1** [comment]
What do you need me to show you?

**Comment by wilkinsona** [comment]
A small sample that you believe is correctly configured to show git information in the `/info` endpoint but does not do so.

**Comment by Puthiaraj1** [comment]
/info is working for below class file 
@Component
public class ExampleInfoContributor implements InfoContributor {

    @Override
    public void contribute(Info.Builder builder) {
        builder.withDetail("example",
                Collections.singletonMap("key", "value"));
    }

}

But it is not reading values from git.properties. Other actuator end points are working fine.

**Comment by wilkinsona** [comment]
Ok. Can you please provide a complete project that shows that behaviour? A repository shared on GitHub would be ideal.

**Comment by Puthiaraj1** [comment]
I deployed the app into PCF and getting git info details. I dont know why it is not working in local.
