### ISSUE TITLE
"apply plugin: 'org.springframework.boot'" of 2.0.0.M6 stops dependencies between subprojects

### ISSUE THREAD

**Issue by acdcjunior** [spring-projects/spring-boot#11008]
This is a bug report:

- Version: **`2.0.0.M6`**
- Gradle: **`4.3.1`**
- Java **`1.8.0_152`**@windows

# Setup

A **Gradle Multi-Project build** with two subprojects (`sb-aaa`, `sb-bbb`) and subproject `sb-aaa` depending on `sb-bbb`.

# Problem

When we add `apply plugin: 'org.springframework.boot'` (of Spring-boot's 2.0.0.M6) to `sb-bbb`'s `build.gradle`, then `sb-aaa` stops "seeing" `sb-bbb`, and we get errors (below).

# How to reproduce

I created a sample project at https://github.com/acdcjunior/springboot2-gradle-subproject-bug.

    git clone https://github.com/acdcjunior/springboot2-gradle-subproject-bug.git .
    ./gradlew build

Error message:

    $ gradlew clean build
    
    > Task :sb-aaa:compileJava FAILED
    ...\sb-aaa\src\main\java\sb\bug\aaa\ClassAAA.java:3: error: package sb.bug.bbb does not exist
    import sb.bug.bbb.ClassBBB;
                     ^
    ...\sb-aaa\src\main\java\sb\bug\aaa\ClassAAA.java:7: error: cannot find symbol
        public ClassAAA(ClassBBB c) {
                        ^
      symbol:   class ClassBBB
      location: class ClassAAA
    2 errors
    
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':sb-aaa:compileJava'.
    > Compilation failed; see the compiler error output for details.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 2s
    4 actionable tasks: 4 executed

# Other notes

- This does not happen with Spring-Boot 1.5.X.
- Removing `apply plugin: 'org.springframework.boot'` makes the problem go away (try it out). But we need it to get the spring-boot dependencies versions (right?).

**Comment by philwebb** [comment]
Thanks for the sample project. I believe that the problem is you're applying the `org.springframework.boot` plugin to both modules. Usually it only makes sense to create a "fat jar" in the file that you actually ship. In your example I would expect `sb-bbb` to create a regular Jar.

If you really want to produce both "fat jars" and regular jars from the same build you [should look at this section of the reference docs](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#packaging-executable-and-normal). I suspect what you probably want to do though is just apply the `io.spring.dependency-management` plugin so that you get dependency management without the fat jar.

**Comment by acdcjunior** [comment]
@philwebb Thanks for the feedback. I had suspected that, but then simply removing `org.springframework.boot` didn't work.

I tried to research it more now and I seem to have figured the way out. Since the result (below) is just a mashup of what I found around (I didn't encounter any straight documentation or examples - just general, no-code, explanations like [this](https://spring.io/blog/2017/04/05/spring-boot-s-new-gradle-plugin#dependency-management); or [examples](https://github.com/spring-gradle-plugins/dependency-management-plugin#using-the-plugin) in where I had to specify `io.spring.dependency-management`'s version directly, which could mismatch spring-boot's), could you confirm this is the correct way?

After removing `apply plugin org.springframework.boot`, what I did different now is I also added the:

```
dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}
```

Here's the commit/diff: https://github.com/acdcjunior/springboot2-gradle-subproject-bug/commit/65281946f6c390894ea977fbfa4c7487f19a2ced, if helps.

If this is good, then this (github) issue will hopefully help others in the future.
