### ISSUE TITLE
Error Handling pre contextPath does not work as expected 

### ISSUE THREAD

**Issue by pandaadb** [spring-projects/spring-boot#11006]
Statement:

The error handling for 404 errors (or general error pages) seems to not be working. If a contextPath is set, all servlets are initialised with this context path and there is nothing handling URL requests for URLs that do not match the context path. 

Bug Report: 

I created a demo project using the spring boot intialiser with jersey: 

Versions: 

spring-boot-starter-jersey:1.5.8.RELEASE
spring-boot-starter-test:1.5.8.RELEASE

I created a simple setup that creates a REST Application such as this: 

```
@Component
public class ResourceConfig extends org.glassfish.jersey.server.ResourceConfig {

    public ResourceConfig() {
        register(HW.class);
    }
    
    
    @Path("test")
    public static class HW {
        
        @GET
        public String test() { 
            return "Hello test";
        }
    }
}
```

I set the context path to: 

`server.contextPath=/mainstay`

The server starts and it will now use the default error page registered with tomcat for any 404 after `localhost:8080/mainstay' and it will respond with a random 404 error for all other requests that do not match the prefix. 

On curl: 

Success: 

```
curl localhost:8080/mainstay/test -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /mainstay/test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 
< Content-Type: text/plain
< Content-Length: 10
< Date: Mon, 13 Nov 2017 13:57:45 GMT
< 
* Connection #0 to host localhost left intact
Hello test
```

Successful error case: 

```
curl localhost:8080/mainstay/test/does_not_exist -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /mainstay/test/does_not_exist HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 
< Content-Type: text/html;charset=utf-8
< Content-Language: en
< Content-Length: 1078
< Date: Mon, 13 Nov 2017 13:58:21 GMT
< 
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not Found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr clas* Connection #0 to host localhost left intact
s="line" /><h3>Apache Tomcat/8.5.23</h3></body></html>
```

Faulty error case that does not match the servlet contextpath: 

```
curl localhost:8080/test/does_not_exist -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test/does_not_exist HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 
< Content-Length: 0
< Date: Mon, 13 Nov 2017 13:58:54 GMT
< 
* Connection #0 to host localhost left intact
```

If I refactor my code and annotate the entire prefix into my jersey resource all works as expected, all requests get routed and the error handler's are called. It enables me to also send the exception and catch it with jersey's exception mappers to handle it. 

However I have not found a way to register a custom error handle for this case. 

I hope this makes sense. Please let me know if I can do anything else to add value to this issue. 

Regards,

Artur

**Comment by philwebb** [comment]
Could you please share the project that you created?

It's not entirely clear to me what you mean by "it will now use the default error page registered with tomcat for any 404 ... and it will respond with a random 404 error for all other requests".

**Comment by pandaadb** [comment]
Hi,

I am sorry, my descriptive capabilities have never been the best :) I should have added the example test right away: 

https://github.com/pandaadb/spring-boot-context-path-test

I added a test for this as well: 

test404DefaultInvoced - makes sure that the response has some html in it coming from tomcat which is the default error page 

test404DefaultInvocedWithoutContextPath - makes the same request but skips the context path of the server and gets a 404, but no html response, so no error page.

**Comment by pandaadb** [comment]
From the logs, I think this is also not really correct (or I am misunderstanding it): 

> 2017-11-14 10:06:12.828  INFO 25769 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
> 2017-11-14 10:06:12.829  INFO 25769 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
> 2017-11-14 10:06:12.829  INFO 25769 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'com.example.pdb.demo.ResourceConfig' to [/*]

This is not actually true. These Filters are mapped to `<servlet.contextPath>/*` instead I think. That might be why this is behaving strangely. 

When debugging that, I can see my context is: 

`StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[/mainstay]`

**Comment by philwebb** [comment]
OK, I see what you mean now. If you hit `localhost:8080/mainstay/test/does_not_exist` you get the Tomcat error but if you hit `localhost:8080/test/does_not_exist` you get a blank page. This appears to be Tomcat's default behavior so I'm not sure that there is much we can do about it.

When Tomcat finds the context it ultimately ends up the error code in [StandardHostValve.invoke()](https://github.com/apache/tomcat/blob/860a0e6dde5639dba70d53fa706b8dc65340c902/java/org/apache/catalina/core/StandardHostValve.java#L177). This renders the status page. If the context isn't found [CoyoteAdapter](https://github.com/apache/tomcat/blob/860a0e6dde5639dba70d53fa706b8dc65340c902/java/org/apache/catalina/connector/CoyoteAdapter.java#L592) ends up returning the 404 and it doesn't do any kind of rendering.

I'm don't know if a standalone Tomcat server also behaves this way. Perhaps they register some default context automatically to deal with this (@markt-asf might know).

@pandaadb perhaps you can leave the context path as it is and instead use servlet paths to get the URLs that you want?

**Comment by markt-asf** [comment]
Tomcat expects that a ROOT context is configured. It doesn't configure one automatically. The ability to configure global error pages (for this case and 500 errors that don't get as far as a Context) is a long-standing enhancement request. See https://bz.apache.org/bugzilla/show_bug.cgi?id=41007
There isn't an obvious implementation option for this enhancement which, combined with little user interest in the feature, is why, I suspect, it remains unimplemented.

**Comment by pandaadb** [comment]
Hi - good to know, thank you.

@philwebb yes you are right, I can leave the context path as root and all works as expected, it just forces me to add the context path to all other resource classes at the moment. The context path is quite convenient for AWS application load balancer routing which is why we added it in the first place.

**Comment by philwebb** [comment]
Closing in favor of the Tomcat issue https://bz.apache.org/bugzilla/show_bug.cgi?id=41007

**Comment by jzoe** [comment]
@philwebb 
Tomcat issue https://bz.apache.org/bugzilla/show_bug.cgi?id=41007 have been resolved. Are there any actions to fix this problem? 

![image](https://user-images.githubusercontent.com/11612990/60560369-05324280-9d82-11e9-8839-d7543d99d977.png)

**Comment by philwebb** [comment]
@jzoe You just need to be running Tomcat 9.0.6+. If you're using Spring Boot managed dependencies and are on the latest stable Spring Boot version (2.1.6) then you shouldn't need to do anything.

**Comment by jzoe** [comment]
@philwebb I'm using version 2.1.6 now, and I've met similar needs. I found this issue , when I try to search for help.

**Comment by philwebb** [comment]
@jzoe If you're seeing a similar problem with the latest Spring Boot version please open a new issue and attach a small sample that we can run. Perhaps there's a regression that we've missed.
