### ISSUE TITLE
ConversionService used for Actuator endpoints should be configurable

### ISSUE THREAD

**Issue by shabino** [spring-projects/spring-boot#11013]
Because the `EndpointAutoConfiguration` `endpointOperationParameterMapper()` method is not annotated by `@ConditionalOnMissingBean(ParameterMapper.class)`, I had to resort to redundantly creating my own `ConversionServiceParameterMapper` (with my own, customized conversion service) with the `@Primary` annotation. This solved my problem, but now my code includes this line from `ConversionServiceParameterMapper`: `IsoOffsetDateTimeConverter.registerConverter(conversionService);` This isn't great because I now must remember to check the code in `ConversionServiceParameterMapper` when upgrading to newer versions of Spring Boot to make sure I don't need to configure my own `ConversionService` differently due to internal changes.  And, it's slightly sloppy because there's an extra `ParameterMapper` created for no reason.

I'd like for there to be a clean way to customize the Actuator-specific `ConversionService` used as the `ParameterMapper`.

**Comment by snicoll** [comment]
@shabino thanks for the report. Can you share why you need a specific `ConversionService` for this? What is the use case?

**Comment by shabino** [comment]
We use interned value object wrappers for identifiers. They wrap the raw String representations. By adding my String -> ID converter (works via reflection for all of our identifier classes of this style), I get more strongly-typed method signatures in my Endpoint classes. Not a huge benefit -- just a nice-to-have.

**Comment by snicoll** [comment]
@shabino okay cool. I propose that we look for `Converter` and `GenerciConverter`  beans in the context and just add them to the `ConversionService`. Would that work for you?

**Comment by shabino** [comment]
This would solve my problem.

What would happen if someone has his own String -> Date converter in his context? I presume that IsoOffsetDateTimeConverter would win.

**Comment by arnokoehler** [comment]
Is there a setup for this available, for if I want to look in to this issue?

**Comment by shabino** [comment]
My issue was partially fixed in this commit which added the `@ConditionalOnMissingBean` annotation: https://github.com/spring-projects/spring-boot/commit/1d39feffeabf4b94e3f900b941b58e0443d5887a#diff-5b71e8f38ba31c03d127203b2f8c0172

I look forward to the PR from @chang-chao nonetheless :)

**Comment by philwebb** [comment]
Closing in favor of PR #16449
