### ISSUE TITLE
ConfigurationProperties - overriding array elements deletes entire list

### ISSUE THREAD

**Issue by SethSilverBeard** [spring-projects/spring-boot#11012]
It appears when using a List inside `@ConfigurationProperties` like `thing[0]=hello` and `thing[1]=seth`, overriding one element with an environment variable like `thing[0]=goodbye` wipes out all my old elements. Is there any workaround? Perhaps through some `setter` magic?

I see it's also mentioned at #9137 but the public docs have not been updated yet (see https://github.com/spring-projects/spring-boot/commit/40f4c8960235ddffbc221a77c0abe9f270f91dc5)

This has caused some serious issues for us as we created a custom [@Conditional for repeated properties](https://stackoverflow.com/a/41947940/2108807)  that checked required subproperties  (`service[x].name` and `service[x].version`), but that no longer works correctly if someone decides to override any single one of the elements in the entire list.

**Comment by snicoll** [comment]
What you describe works as advertized, good catch on the documentation update part.

**Comment by wizdata** [comment]
We should be able to override the element of the list depending upon the deployment environment.
