### ISSUE TITLE
Match trailing slash in actuator endpoints

### ISSUE THREAD

**Issue by pbetkier** [spring-projects/spring-boot#11024]
Hi folks, I'm preparing a migration from Spring Boot 1.x to 2.x at the company. I noticed that in 2.x actuator endpoints are no longer available under URLs with trailing slashes like they did in 1.x, i.e:

Spring Boot 1.x (1.5.2.RELEASE):
* `GET /info` gives the info response
* `GET /info/` gives the info response

Spring Boot 2.x (2.0.0.M5):
* `GET /application/info` gives the info response
* `GET /application/info/` **gives status 404**

This is a problem for me, because we have 400+ Spring Boot apps in production and I'm not able to easily track all the places in our infrastructure where requests with trailing slashes could occur. Did this behaviour change on purpose are is it an oversight?

Additional info from my investigation:

Looking up the sources I noticed that the 1.x version uses `org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping` which matches trailing slashes by default and is configurable. 2.x version uses `org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping` which hardcodes no trailing slash match when constructing `PatternsRequestCondition` internally. There seems to be no way to configure trailing slash matching. I guess registering a custom subclass of `WebMvcEndpointHandlerMapping` that would override `createRequestMappingInfo` could do the trick (haven't tested), but I'd rather avoid tweaking the framework too much and having to maintain it later.

**Comment by wilkinsona** [comment]
Thanks for the detailed report. Dropping support for a trailing `/` wasn't intentional and I see no reason why we can't reinstate it. We should also ensure that it works consistently across Spring MVC, WebFlux, and Jersey (all of which the Actuator now supports).
