### ISSUE TITLE
Setting management.context-path has no effect in 2.0.0.M6

### ISSUE THREAD

**Issue by Juliet-Unsilo** [spring-projects/spring-boot#11020]
As far as I can see, it is no possible to override the default management context path by setting the management.context-path property in 2.0.0.M6 - this is possible using 2.0.0.M5

I have created 2 bare-bones demo projects, the only difference between them being the spring boot version: 
old uses 2.0.0.M5 while new uses 2.0.0.M6

Both have the following 2 dependencies:
```
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.boot:spring-boot-starter-actuator')
}
```
And both have the same configuration:
application.yml:
```
management:
  context-path: /
```

In old the default /application is removed from the /status and /info endpoints, while this is not the case for new. 

After reading: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M6-Release-Notes
I have also tried:
```
management:
  server:
    context-path: /
```
Output for old:
> 2017-11-14 16:07:38.522  INFO 18947 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[**/status**],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
> 2017-11-14 16:07:38.523  INFO 18947 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[**/info**],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)

Output for new:

> 2017-11-14 16:10:35.417  INFO 19425 --- [ost-startStop-1] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[**/application/status**],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
> 2017-11-14 16:10:35.418  INFO 19425 --- [ost-startStop-1] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[**/application/info**],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
> 

[demo-old_working.zip](https://github.com/spring-projects/spring-boot/files/1471394/demo-old_working.zip)
[demo-new_not_working.zip](https://github.com/spring-projects/spring-boot/files/1471397/demo-new_not_working.zip)

**Comment by spencergibb** [comment]
according to the wiki page you linked `management.server.context-path` only works if `management.server.port` is set. 

You should use:

> you can also set the base path for the management endpoints with a new, separate property: `management.endpoints.web.base-path`

**Comment by Juliet-Unsilo** [comment]
Ok - that works - thanks
