### ISSUE TITLE
ContextIdApplicationContextInitializer doesn't produce unique IDs, breaking contract of ApplicationContext.getId()

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11023]
In addition to being required by the documented contract of `ApplicationContext.getId()`, being able to uniquely identify contexts is required for https://github.com/spring-projects/spring-boot/issues/11019. `ContextIdApplicationContextInitializer` currently generates duplicate IDs by default as it sets every context's ID to `application`.

**Comment by wilkinsona** [comment]
One option might be to prepend the ID of the parent, if any. However, that would only help for a linear hierarchy and two sibling contexts would still end up with the same ID.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/5265 is related to this. In that issue, @dsyer said:

> The context id defaults to something basically sensible IMO (and please don't change it)

I can agree that it's basically sensible, but it needs to be fine-tuned so that it meets the requirements for uniqueness. Being unique within the scope of a single JVM would be sufficient I think.

@dsyer any suggestions on how to achieve that without undermining the intent of your original implementation?

**Comment by dsyer** [comment]
Another comment from me on that issue:

> we should set it, and if so, then copying spring cloud (context) makes sense. It tries to do it in a way that will work for scaled up apps locally and in Cloud Foundry. The only issue is that spring boot doesn't have any special role for spring.application.name (except this) and that is the cornerstone of the spring cloud approach (name and port or name and instance id if available).

In yet another comment I pointed out that Spring Cloud bus uses the application id to address and filter messages, so any change we make hopefully can be made to not break that.

**Comment by wilkinsona** [comment]
For an ID that's unique per JVM, but consistent and predictable across JVMs, I think we can increment a static counter as contexts are created. The value of this counter can then be included in the identifier. Strictly speaking, using a static will give us uniqueness per class loader but I think that will be sufficient by default for our purposes. The application name could be included in the identifier, but values that may vary across instances (such as the index or server port) should not be included.

A couple of examples using `${spring.application.name}-${counter}`:

```
    application-1
         |
    application-2
         |
    application-3
```

```
          application-1
               |
     |-------------------|
application-2      application-3
```

Just to be clear, the value of the counter in the identifier would reflect the order of the contexts' creation, rather than the order that the contexts would be encountered when walking the graph. A such, both of the following examples would be possible:

```
          application-1
               |
     |-------------------|
application-2      application-4
     |
application-3
```

```
          application-1
               |
     |-------------------|
application-2      application-3
     |
application-4
```

As long as the order of context creation is consistent across instances of the application, the identifier of each context will also be consistent.

We could adopt a convention where the identifier reflects the topology of the hierarchy. For example, when creating the identifier for a child, the parent's identifier could be prepended. However,  I'm not sure that we should do so, unless we can make this structure something that is enforced rather than purely a convention.

To allow us to leave the current application context ID alone, the context identifier being proposed here could be made available as a bean with a well-known name. That would also provide us with an opportunity to use a rich type that could enforce the identifier's structure if we chose to do so, or could provide access to multiple identifiers such as the identifier being discussed here and a routing identifier which does differ per instance of the application.

**Comment by philwebb** [comment]
I imagine a lot of Boot apps just have a single context so perhaps we should only append the counter after the first one? e.g:

```
        application
               |
     |-------------------|
application-1      application-2
     |
application-3
```

**Comment by philwebb** [comment]
Also +1 to not having port or instance identifier in the context ID.

**Comment by wilkinsona** [comment]
A counter per depth sounds nice. The `ContextIdentifer` bean (or whatever it's called) in the parent could be responsible for creating IDs for its children and could be the place that holds the child count state. If there's no parent, we'd just create a new default `ContextIdentifier` for the root context.

**Comment by wilkinsona** [comment]
Was there any discussion of this topic at S1P? We need some input from the Cloud team (/cc @dsyer @spencergibb).

**Comment by dsyer** [comment]
Unique within a JVM and based on `${spring.application.name}` (with a sensible default) works for us, I think. IMO it shouldn't be any more unique than that (so we can support scoped proxies shared between scaled up app instances). We already migrated the Spring Cloud Bus to use it's own service id abstraction.
