### ISSUE TITLE
Consider to trim each item in comma-separated configurations

### ISSUE THREAD

**Issue by bitholic** [spring-projects/spring-boot#11029]
Recently, I have used `spring-boot-starter-data-redis` and configured its sentinel nodes like "xx.xx.xx.xx:xxxx, xx.xx.xx.xx:xxxx", unfortunately, the application started failed because of the space after the comma. Although the docs point out it is "comma-separated", using space after a comma is more customary, So I think it would be better to `trim()` those items in comma-separated configurations.

**Comment by philwebb** [comment]
The binder in 2.0 will automatically trim strings so switching to a `String[]` should be enough to fix this going forward.

**Comment by snicoll** [comment]
@philwebb Is there a reason why you've used an array for this? I think most properties would use a `List`.

**Comment by philwebb** [comment]
No specific reason, I just picked it at random. Will re-open to change it to a List.

**Comment by snicoll** [comment]
@philwebb I pushed  5728d96. If you change the description of a key, you have to update the appendix. I did look at #10870 and didn't see a change for the "Comma-separated` bits so I've restored it. If you feel differently we should probably write those rules down on the wiki (I don't mind either way).
