### ISSUE TITLE
Missing EnableOAuth2Sso

### ISSUE THREAD

**Issue by MartinX3** [spring-projects/spring-boot#11032]
I migrated from Spring Boot 1.5.6 to 2.0.0.M6

Intellij is telling me, that @EnableOAuth2Sso doesn't exist anymore.
Did I miss something?

That's my pom
```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.M6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>


      <!-- for OAuth 2.0 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>2.0.0.M6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>
```

**Comment by wilkinsona** [comment]
> Did I missing something?

Yes, the M5 release notes where the [changes to OAuth support are described](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M5-Release-Notes#oauth-20-support).

**Comment by MartinX3** [comment]
Thank you, it is missing in the Migration Guide. :)

**Comment by snicoll** [comment]
> it is missing in the Migration Guide. :)

Thanks, there is a note at the top of this document that states it is work in progress. There are plenty of things missing there atm.

**Comment by romeara** [comment]
The information on migrating is still missing - could someone who is aware of what the expected replacement configuration is comment here? This is one of the top results when searching for information on its removal, so I think it would be useful to anyone trying to update until the documentation linked above is updated. Thanks!

**Comment by snicoll** [comment]
@romeara why do you think it is missing? There is a [section in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#oauth2) with a [link to a reference guide](https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/) about that stuff

**Comment by romeara** [comment]
The reference guide you linked still talks about adding the EnableOAuth2Sso annotation, which is not present in the library in version 2.0.0, and the migration guide does not mention what to use instead

**Comment by snicoll** [comment]
> the EnableOAuth2Sso annotation, which is not present in the library in version 2.0.0

Actually, [It is](https://github.com/spring-projects/spring-security-oauth2-boot/blob/8c6b1512050f5413e8cfb0af37485d29ecfe2ebb/spring-security-oauth2-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/EnableOAuth2Sso.java#L48). If you have more questions ask on StackOverflow or join us on Gitter.
