### ISSUE TITLE
Automatically add /healthz when running in kubernetes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11041]
We might be able to detect kubernetes [by virtue of `/var/run/secrets/kubernetes.io/serviceaccount/namespace`](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) and use it to drive various conventions.

One obvious useful one would be to add a `/healthz` endpoint alias.

**Comment by wilkinsona** [comment]
As far as I can tell from [the docs](https://kubernetes.io/docs/api-reference/v1.8/#httpgetaction-v1-core) there’s no default for the path that is probed. I’m not sure that adding `/healthz` will have much benefit.

**Comment by markfisher** [comment]
There is no default endpoint for probes (but maybe conventions) cc @trisberg

The concern for boot apps being deployed to K8s is that they will very likely be using `/health` as the probe endpoint currently. When that endpoint path changes with the upgrade to 2.x, it will impact their deployment (e.g. entering a `CrashLoopBackOff` state if the probes fail within the allotted timeouts). So, I think the main thing we need is clear documentation, but we should consider anything else we could do to provide a smooth upgrade experience, such as:

1. a single-property to enable Boot 1.x compatibility mode for actuator endpoints
2. possibly logging a warning if requests are made to `/health` and there is no mapping for it?

**Comment by philwebb** [comment]
OK, adding `/healthz` doesn't give us much. I incorrectly assumed that was a default rather than just a suggestion. I'll close this one and we'll cover the documentation of `/health` in the migration guide.
