### ISSUE TITLE
DevToolsDataSourceAutoConfiguration fails when FactoryBean in Spring XML

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#11048]
I prepared example when adding devtools breaks application: https://github.com/michaldo/dev-tools-defect

`DevToolsDataSourceAutoConfiguration$DevToolsDataSourceCondition.getMatchOutcome` calls `context.getBeanFactory().getBeanNamesForType(DataSource.class);`

If `FactoryBean` is defined within Spring XML configuration, the factory is instantiated before placeholders `${}` are resolved, which can cause exceptions.

**Comment by philwebb** [comment]
I think we might have a lifecycle issue where properties are being resolved too early, but I'm not sure if we can fix it. You might be able to add `context:property-placeholder` to your XML.

Is there any reason you need to use XML in your application. The mix is slightly unusual for typical Boot apps.

You might find using `@Value("${name}")` to get the name directly in your Java code provides a workaround.

**Comment by michaldo** [comment]
I use XML in application due legacy configuration.
Workaround is working

**Comment by mkuhl** [comment]
I have the same problem here. Got to use XML die to large legacy issues, lots of factory beans,  the workaround to move all factory beans to javaconfig is not really feasible. 

So our workaround for now is not to use devtools... which is kind of a bummer since auto reload and live reload are sooo convenient..sigh..

**Comment by wilkinsona** [comment]
@mkuhl Have you tried adding `context:property-placeholder` to your XML as Phil suggested above?

**Comment by michaldo** [comment]
In my github application `context:property-placeholder` does not solve the issue.
My workaround is disable `DevToolsDataSourceAutoConfiguration`

**Comment by mkuhl** [comment]
Yes It did try `context:property-placeholder` but it did not change anything. BTW the problem is not specific to DataSource, it occurs with all factory beans (if they use directly or transitive property placeholders that is...)

**Comment by philwebb** [comment]
Sorry, we're going to have a hard time spending too much time on this since it's XML based configuration. Our recommendation is to move to Java config.

**Comment by ywangd** [comment]
Just hit this issue today. Took us a day to pin down the cause of it! 
Another workaround is to use SPEL instead of property placeholder, i.e. this works `#{ @environment.getProperty('name') }`. This is a better workaround for us since the change is minimal (compare to adding Java config).
