### ISSUE TITLE
Heapdump endpoint should not accessed 

### ISSUE THREAD

**Issue by javamonkey** [spring-projects/spring-boot#11046]
@philwebb
 
if property "management.server.port" is set 8080,everything is fine,here is output on console
~~~
Mapped "{[/application/loggers],methods=[GET],....
Mapped "{[/application/heapdump],methods=[GET],...
~~~

if property "management.server.port" is set 8081,a different port with web server,both loggers and heapdump can not accessed and was disabled .

pom.xml
~~~
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.M6</version>
</parent>
~~~

application.properties:

~~~
endpoints.default.web.enabled=true
management.security.enabled=false
management.server.port=8081  
~~~

this my project  to show this problem
https://github.com/javamonkey/springboot-2.0.0.M6-heapdump

**Comment by mbhave** [comment]
Loggers is accessible but heapdump doesn't seemed to be mapped.

**Comment by wilkinsona** [comment]
`loggers` is fine, but the `logfile` endpoint is not. The problem with both it and `heapdump` is that they're configured in a `@ManagementContextConfiguration` class so they move down into the child context when `management.server.port` is set and then the endpoint discovery fails to find them.

I believe we can just configure them in standard auto-configuration classes so they remain in the root context.

**Comment by javamonkey** [comment]
thanks @philwebb 
I get another error message when i update to 2.0.0.M7:

`
APPLICATION FAILED TO START


Description:

Configuration property name 'management.endpoint.hikariCP.cache.time-to-live' is not valid:

    Invalid characters: 'C', 'P'
    Bean: jmxMBeanExporter
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'management.endpoint.hikariCP.cache.time-to-live' so that it conforms to the canonical names requirements.
`
here is my pom.xml

	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
         <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
              <version>6.0.5</version>
        </dependency>

**Comment by wilkinsona** [comment]
@javamonkey That appears to be a separate issue. Also, Boot itself doesn’t have an endpoint for Hikari CP so I believe the problem must be in your application or one of its dependencies.

**Comment by snicoll** [comment]
@javamonkey it has already been reported #11107
