### ISSUE TITLE
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils

### ISSUE THREAD

**Issue by netroby** [spring-projects/spring-boot#11042]
JDK 9 run spring boot demo got error message:

```
2017-11-16 10:48:59.872  INFO 18066 --- [           main] .r.c.ReactiveWebServerApplicationContext : Refreshing org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext@72d1ad2e: startup date [Thu Nov 16 10:48:59 CST 2017]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/huzhifeng/tmp/demo/build/libs/demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-core-5.0.1.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by netroby** [comment]
I am using   2.0.0.M6

**Comment by netroby** [comment]
https://github.com/spring-projects/spring-boot/issues/10274 May not be fixed

**Comment by shakuzen** [comment]
It's not Spring Boot itself causing this. As the warning states (look for `spring-core-5.0.1.RELEASE.jar`), the access is from Spring core. It should be reported to the [Spring Framework issue tracker](https://jira.spring.io/browse/SPR) if it hasn't been reported there already.

**Comment by shakuzen** [comment]
It looks like it has been already reported and is being tracked as [SPR-15859](https://jira.spring.io/browse/SPR-15859)

**Comment by wilkinsona** [comment]
Thank you, @shakuzen

**Comment by ValentinBossi** [comment]
solve the problem by adding this dependency in the pom.xml:
<dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0</version>
</dependency>

**Comment by netroby** [comment]
Thanks  @ValentinBossi 
Really useful tips

**Comment by Wangsudo** [comment]
@ValentinBossi 
Why my project is not effective after adding this dependency

**Comment by ValentinBossi** [comment]
i dont know.
but go back to java 8 and remove that mentioned dependency. in most cases you dont need java 9.
