### ISSUE TITLE
Cookie is appended to Set-Cookie: JSESSIONID

### ISSUE THREAD

**Issue by ropoman** [spring-projects/spring-boot#11047]
Hi,

I set a cookie with HttpServletResponse.addCookie() and the resulting HTTP header does not look correct. It is simply appended to the session cookie line. I am using 1.5.6.RELEASE

Set-Cookie: JSESSIONID=1D815AAF7D67DA535F0D13369874BA9D; Path=/; HttpOnlymyCookieName=myCookieValue; Max-Age=2592000; Expires=Sat, 16-Dec-2017 12:50:59 GMT; Path=/

Is there a workaround? Need to go live with this today 

Thanks,
Roland

**Comment by wilkinsona** [comment]
Given that you're calling the Servlet API directly, this is most likely to be due to the behaviour of the Servlet container. Unfortunately, you haven't said which container you're using. Perhaps you can share a small example that reproduces the problem?

**Comment by ropoman** [comment]
I am using the embedded tomcat container. I get the same result header with JSESSIONID when I do this:
response.addHeader("Set-Cookie", "myCookieName=myCookieVal; Max-Age=2592000; Expires=Sat, 16-Dec-2017 12:44:21 GMT; Path=/");

**Comment by bclozel** [comment]
Could you please provide a complete sample for that?

I tried to reproduce that with a Spring Boot 2.0.0.M6 application and:

```java
@Controller
public class HelloController {

	@GetMapping("/")
	public void hello(HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		Cookie cookie = new Cookie("foo", "bar");
		response.addCookie(cookie);
		response.setStatus(200);
	}
}
```

This returns:

```
curl -I http://localhost:8080/
HTTP/1.1 200
Set-Cookie: JSESSIONID=12A3BD3A84B38F7119A2030E89A38490; Path=/; HttpOnly
Set-Cookie: foo=bar
Content-Length: 0
Date: Thu, 16 Nov 2017 14:01:59 GMT
```

**Comment by ropoman** [comment]
Thanks for helping. I was able to reproduce the problem with your example. It turns out the problem was only in the way Firefox developer tools displays the header lines :( and my real problem is somewhere else
I am really sorry I wasted your time.
