### ISSUE TITLE
Stop spurious warnings when using a pathing jar

### ISSUE THREAD

**Issue by thauk-copperleaf** [spring-projects/spring-boot#11057]
I'm new to Spring, on a team developing on Windows.

To work around issues on Windows and the command line limit of 32767 characters, the concept of a "pathing jar" was created. I first came across it at <http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/>. This also seems to be an integrated option in at least one IDE (IntelliJ).

However, when a pathing jar is used with Spring, it results in many spurious warnings about entries not existing, e.g. https://github.com/spring-projects/spring-boot/issues/10111

The relevant code is here in the master branch:

https://github.com/spring-projects/spring-boot/blob/35c6b83fce86a83e4b2b9ec9fb5cbe0646eb23a5/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/ChangeableUrls.java#L162-L185

The warnings happen because the code always tries to fixup each classpath entry, believing they always represent relative URLs. I would suggest that this check be changed slightly, to use [`File.isAbsolute()`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#isAbsolute()) to see if the entry is already an absolute path, when building the `referenced` URL.

Is that a change that makes sense to make, and would it be accepted?

**Comment by philwebb** [comment]
It looks like c27d678b814cbe62dcd0d3b462cb2d055f13948c changed some of the logic. @wilkinsona will adding the `File.isAbsolute()`  break the original fix?

**Comment by thauk-copperleaf** [comment]
@philwebb Yes, I think you're right :)

**Comment by wilkinsona** [comment]
> The warnings happen because the code always tries to fixup each classpath entry, believing they always represent relative URLs

That's not the case due to the fix that Phil linked to above. The fix also updated the tests to cover both absolute and relative paths.

>  will adding the File.isAbsolute() break the original fix?

AFAIK, it shouldn't be necessary.

@thauk-copperleaf What version of Boot are you using? I think this should work with 1.5.8 or 2.0.0.M5 or later. If you're already using such a version, please provide a sample that illustrates the problem.

**Comment by thauk-copperleaf** [comment]
@wilkinsona The line `URL referenced = new URL(jarUrl, entry);` does not handle relative paths; it is gluing the path to the jar to the entry without checking if the entry is already absolute.

**Comment by thauk-copperleaf** [comment]
We are using 1.5.6

**Comment by thauk-copperleaf** [comment]
@wilkinsona For the sake of completeness, the warnings still occur with 1.5.8.

**Comment by wilkinsona** [comment]
> it is gluing the path to the jar to the entry without checking if the entry is already absolute.

AFAIK, that constructor does not work as you have described. Please read the [relevant javadoc](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL-java.net.URL-java.lang.String-), particularly this paragraph on how the spec is treated:

```
If the authority component is present in the spec then the spec is treated as absolute and the spec authority and path will replace the context authority and path. If the authority component is absent in the spec then the authority of the new URL will be inherited from the context.
```

> For the sake of completeness, the warnings still occur with 1.5.8.

Thanks for trying 1.5.8. As I said above, please provide a sample that illustrates the problem.

**Comment by thauk-copperleaf** [comment]
```
task pathingJar(type: Jar) {
    appendix = 'pathing'
    doFirst {
        manifest {
            attributes "Class-Path": configurations.runtime.files.collect {
                it.toURL().toString().replaceFirst(/file:\/+/, '/')
            }.join(' ')
        }
    }
}

tasks.withType(org.springframework.boot.gradle.run.BootRunTask) {
    dependsOn pathingJar
    doFirst {
        classpath = files("$buildDir/classes/kotlin/main", "$buildDir/resources/main", pathingJar.archivePath)
    }
    ...
}
```

Example warning:
> Ignoring Class-Path entry /C:/Users/THauk/.gradle/caches/modules-2/files-2.1/stax/stax-api/1.0.1/49c100caf72d658aca8e58b
d74a4ba90fa2b0d70/stax-api-1.0.1.jar found in C:\Users\THauk\Documents\GitHub\somegithubuser\somegithubproject\build\libs\value
works-pathing.jar as C:\Users\THauk\Documents\GitHub\somegithubuser\somegithubproject\build\libs\C:\Users\THauk\.gradle\caches\
modules-2\files-2.1\stax\stax-api\1.0.1\49c100caf72d658aca8e58bd74a4ba90fa2b0d70\stax-api-1.0.1.jar does not exist

**Comment by wilkinsona** [comment]
Thanks. It looks to me like your pathing jar task is misconfigured as it’s not producing absolute URLs. Why are you stripping the `file://` prefix and replacing it with `/`?

For the record, we’re using the [same approach as OpenJDK does when dealing with this manifest attribute](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/misc/URLClassPath.java#l1019) so I believe our current approach is the correct one.

**Comment by thauk-copperleaf** [comment]
@wilkinsona Thanks for the replies this morning. :)

I originally tried not stripping the `file://` scheme, with 1.5.6, and it didn't help. I have a log from that run, but perhaps I ran it incorrectly. The log above is from a run with 1.5.8 and stripping the scheme.

Updating our build to 1.5.8 and _not_ stripping the scheme seems to work fine on Windows 7. I've just asked that coworkers test on the other 3 platforms we use to ensure our build is working.

**Comment by thauk-copperleaf** [comment]
Thanks for the help. Closing ticket and hoping that others who run into this problem find it with their favourite search engine :)
