### ISSUE TITLE
Make it easier to just use Spring Boot's dependency management with Gradle

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11059]
From @acdcjunior on Gitter:

> Thanks a lot!! About the user guides, yes, there are mentions to the spring-boot-dependencies, but there is no concrete example code, specially for Gradle (there's a partial one for Maven). For gradle, the gradle-plugin reference guide - which is linked from the user guide - says:

>> When you apply the `io.spring.dependency-management plugin`, Spring Boot’s plugin will automatically import the `spring-boot-dependencies` bom from the version of Spring Boot that you are using.

> Which could lead you to think that, if you want the dependencies but don't want the Spring Boot’s plugin, you should get `io.spring.dependency-management` by yourself.
Even when you know that, there's no exact code of how that would be. One can figure it out (as I tried to do), but the problem is that most of what you can find online, about how to use `io.spring.dependency-management` by itself, requires you to specify `io.spring.dependency-management`'s version directly. That would be undesirable, as I feel it could cause a version mismatch. In the end of the day I (think) I got it by adding `classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"` which seems to correctly import the proper compatible version of the `"io.spring.dependency-management"` plugin. I saw this nowhere, it was more of a lucky shot...

We should make it clear that the `spring-boot-gradle-plugin` has a transitive dependency on `dependency-management-plugin` so if you add a dependency on the former, you'll automatically get the latter on the build script's classpath with the version used by Boot. It can then be applied and configured as you normally would.

**Comment by wilkinsona** [comment]
We can go a step further and provide a constant for the bom's coordinates.

**Comment by acdcjunior** [comment]
@wilkinsona Thanks a lot for all your trouble!

**Comment by wilkinsona** [comment]
@acdcjunior Thank you for taking a look at the changes and for the valuable feedback that led to them.
