### ISSUE TITLE
/logfile endpoint not working

### ISSUE THREAD

**Issue by ashut0shpandey** [spring-projects/spring-boot#11056]
Error `404` on logfile endpoint when the spring boot application is deployed on Linux

I have asked this question on stackoverflow with no success here is the Link.
https://stackoverflow.com/questions/45970822/error-404-on-logfile-endpoint-when-the-spring-boot-application-is-deployed-on-li

And here is what I ask.

I have a simple spring boot application written for a REST API. I am trying to use logback for logs into a file. It works OK when the application is deployed within eclipse on my windows machine and I can see all my logs on `/logfile` endpoint. When I deploy the same application on a Linux box , the logfile is created and updated as expected however when I try to access the logfile over the browser,I get a `404` on the same endpoint(`/logfile`). Any help will be much appreciated 

My logback configuration is as below
```xml
   <?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <logger name="org.springframework.web" level="DEBUG" additivity="false">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FILE"/>
    </logger>
    <logger name="api.controllers" level="DEBUG" additivity="false">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FILE"/>
    </logger>
 </configuration>
```
My application.properties file looks like

```
server.contextPath=/api
#Configure Access Logs
server.tomcat.basedir=log
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)

#configure other log
logging.file=log/vixenapi.log 
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.logging=DEBUG
logging.level.org.hibernate=ERROR
#-------------------------------------

spring.jackson.serialization-inclusion=non_empty

#By Default include all properties. If a view property hasn't been set then it will be shown 
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true
```

**Comment by philwebb** [comment]
I've commented on the stack-overflow question. Lets keep the conversation there for now since we're not yet sure if this is a bug. If we find an issue in the code we can reopen this one.

**Comment by ashut0shpandey** [comment]
Thanks Phil for coming back to me. Please keep an eye on this one as it does look like a bug. I have done everything as per the documentation but to no avail. Thanks.

**Comment by ashut0shpandey** [comment]
[test_api.zip](https://github.com/spring-projects/spring-boot/files/1482233/test_api.zip)
I have attached a minimal but complete example
