### ISSUE TITLE
JOOQ DSLContext remains non-transactional after auto-configuration

### ISSUE THREAD

**Issue by alesbukovsky** [spring-projects/spring-boot#11052]
Noticed in Spring Boot **2.0.0.M6**.

With no additional configuration, the auto-wired JOOQ `DSLContext` still has `transactional` flag set to `false` and no transaction provider linked in after the application start.

It will become transactional if an explicit `PlatformTransactionManager` bean is provided:

```
@Configuration
@EnableTransactionManagement
public class AppConfig {

    @Autowired
    DataSource dataSource;

    @Bean
    public PlatformTransactionManager transactionManager() {
        return new DataSourceTransactionManager(dataSource);
    }
}
```

However, I have noticed that even without the explicit manager bean configuration above, an auto-wired `PlatformTransactionManager` within the same service will contain a reference. Apparently another auto-configuration creates it after all. Since transaction provider setup in the `JOOQAutoConfiguration` is declared as dependent on the `PlatformTransactionManager` bean existence, it seems like JOOQ auto-configuration runs too early to pick the manager's reference.

**Comment by philwebb** [comment]
Good spot. I think we need to add `@AutoConfigureAfter(TransactionAutoConfiguration.class)`
