### ISSUE TITLE
Cache busting not working in WebFlux + Thymeleaf project

### ISSUE THREAD

**Issue by filipblondeel** [spring-projects/spring-boot#11062]
I'm trying to get cache busting of static content working in a Spring Boot 2.0.0.M6 project using WebFlux and Thymeleaf. The resource resolution itself is working correctly: when I do HTTP GET to a static resource using the URL with its content hash I get the correct file. However, in the HTML rendered by Thymeleaf the original URLs to the resources have not been replaced with URLs containing the content hash.

My `application.properties` file contains these settings:
```
spring.resources.chain.enabled=true
spring.resources.chain.strategy.content.enabled=true
spring.resources.chain.strategy.content.paths=/**
```

The following Thymeleaf template:
```
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <link rel="icon" type="image/png" sizes="32x32" th:href="@{/assets/favicons/favicon-32x32.png}">
    <link rel="icon" type="image/png" sizes="16x16" th:href="@{/assets/favicons/favicon-16x16.png}">
    <link rel="manifest" th:href="@{/assets/favicons/manifest.json}">
    <link rel="shortcut icon" th:href="@{/assets/favicons/favicon.ico}">
</head>
<body>
</body>
</html>
```
renders the following HTML which contains the original urls, not the ones with a content hash
```
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="manifest" href="/assets/favicons/manifest.json">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
</head>
<body>
</body>
</html>
```

I guess it is because there is no WebFlux alternative for this part of the Thymeleaf MVC auto configuration since `ResourceUrlEncodingFilter` is a Servlet Filter.
```
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnEnabledResourceChain
    public ResourceUrlEncodingFilter resourceUrlEncodingFilter() {
          return new ResourceUrlEncodingFilter();
     }
```

**Comment by bclozel** [comment]
Spring Framework does not provide any infrastructure for that; here's a quote [from the reference documentation](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-config-static-resources):

> Unlike Spring MVC at present in WebFlux there is no way to transparely rewrite static resource URLs since the are no view technologies that can make use of a non-blocking chain of resolvers and transformers (e.g. resources on Amazon S3). When serving only local resources the workaround is to use ResourceUrlProvider directly (e.g. through a custom tag) and block for 0 seconds.

Could you open a new issue in the [Thymeleaf Spring project](https://github.com/thymeleaf/thymeleaf-spring/issues)? Maybe the Thymeleaf team has an idea about how to support that.

I'm closing this issue for now, as there's nothing we can do in Spring Boot at the moment.
