### ISSUE TITLE
Allow setting environment variables using the Maven plugin

### ISSUE THREAD

**Issue by ctron** [spring-projects/spring-boot#11065]
Spring Boot application can be run by using the maven plugin and the goal `spring-boot:run`. It is possible to pass in JVM arguments (which can be used for system properties), but it is not possible to set OS environment variables.

**Comment by snicoll** [comment]
@ctron can you share why you need to pass environment variables?

**Comment by ctron** [comment]
I do have a library which I use in combination with Apache Camel which requires to set an environment variable for enabling certain functionality.

**Comment by sachinladsonos** [comment]
+1 for this. This would help with dynamoDB local setup as it require setting up SQLLite native library system variable. It cannot find the native library from maven's repository, see her - https://bitbucket.org/almworks/sqlite4java/wiki/UsingWithMaven

**Comment by snicoll** [comment]
Closing in favour of PR #12800
