### ISSUE TITLE
Spring boot auto-configure transaction id prefix

### ISSUE THREAD

**Issue by nklmish** [spring-projects/spring-boot#11067]
As per [docs](https://docs.spring.io/spring-kafka/docs/2.0.1.RELEASE/reference/html/_reference.html#transactions), we need to provide `transactionIdPrefix` in order to enable transaction support. It will be nice if we can add a field like `transactionIdPrefix` in [Producer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L470) and use it in [DefaultKafkaProducerFactory](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L99) to support properties based configuration like `spring.kafka.producer.transaction-id-prefix` in `application.properties` . 
Current Situation:
ATM, we have to manually create a bean just to enable the transaction support. E.g. (the code below is in Kotlin, but we have to do the same thing in Java)
```
    @Bean
    fun kafkaProducerFactory(properties : KafkaProperties): ProducerFactory<*, *> {
        val defaultKafkaProducerFactory = DefaultKafkaProducerFactory<Any, Any>(properties.buildProducerProperties())
        defaultKafkaProducerFactory.setTransactionIdPrefix("txn-ingestor") // transaction-id can be application name or something in that line
        return defaultKafkaProducerFactory
    }

    @Bean
    fun transactionManager(producerFactory : ProducerFactory<*, *>) : KafkaTransactionManager<*, *> {
        return KafkaTransactionManager(producerFactory)
    }

```
I am using:
Spring-KafkaVersion 2.0.1.RELEASE
SpringBootVersion 2.0.0.M6

If it sounds good than I can submit a PR, more details here [spring-kafka-482](https://github.com/spring-projects/spring-kafka/issues/482)

**Comment by snicoll** [comment]
> If it sounds good than I can submit a PR

Looks reasonable. Thanks for offering to submit a PR, we'll wait for that then.

**Comment by nklmish** [comment]
Thanks, PR submitted

**Comment by philwebb** [comment]
Closing in favor of PR #11076. Thanks!
