### ISSUE TITLE
Allow more flexible Duration parsing

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11078]
Binding to `Duration` is currently cumbersome. It would be nice if we could parse simpler formats like `10s`, `10m` etc.

**Comment by philwebb** [comment]
Originally part of PR #11071 but we should have a consistent solution that's the same for all binding, not just micrometer.

**Comment by snicoll** [comment]
@philwebb this support is quite awesome. There are a bunch of places where we use a `long` to express a value in milliseconds. Would it be possible to support that as well? If we did somehow that would be a great migration path for users then: they could keep the raw value (e.g. `10000`) or migrate to the new format (`10s`).

**Comment by wilkinsona** [comment]
If the converter could treat no unit as milliseconds, perhaps we could then change a millisecond property that’s a long to be a Duration instead?

**Comment by snicoll** [comment]
That's the exact reason why I am asking for that support.

**Comment by philwebb** [comment]
Adding a no suffix == milliseconds should be easy and I like the idea of converting longs to `Duration`

**Comment by snicoll** [comment]
That's awesome. There are a couple of comments on the commit, reopening to make sure they're not missed.

**Comment by jkschneider** [comment]
This is fantastic folks. Results in beautiful config.

**Comment by b0c1** [comment]
What do you tihink about the HOCON (typesafe config) duration format?
https://github.com/lightbend/config/blob/eeb95825bf3763959ddd073d20b11045d2c01131/HOCON.md#duration-format

**Comment by philwebb** [comment]
@b0c1 Looks like they were way ahead of us :)  I like it, but I think I prefer to limit the number of choices for now. At least until someone complains that they'd rather type `10seconds` rather than `10s`.
