### ISSUE TITLE
Consider a better default for JSR-310 Jackson rendering

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#11079]
Although Boot makes it quite easy to render JSR-310 dates as ISO-8601 strings, it still requires flipping `spring.jackson.serialization.write-dates-as-timestamps` to `false` (see [this article](http://codeboje.de/jackson-java-8-datetime-handling/) for all steps needed).

Maybe 2.0 is the chance to flip the default to `false` in the first place, and align with the set of better defaults that Boot' Jackson has already implemented (e.g. ignoring unknown properties by default).

**Comment by MichaelZett** [comment]
Absolutely.

**Comment by wilkinsona** [comment]
This ties into #10976. Without the change proposed here, #10976 will only really achieve part of its goal. +1 from me for flipping the default for `write-dates-as-timestamps`.

**Comment by wtatum** [comment]
+1. I think this is definitely consistent with the "batteries" included idea of spring-boot default/auto config.
