### ISSUE TITLE
@SpringBootTest with EmbeddedWebApplicationContext does not correctly shutdown Tomcat

### ISSUE THREAD

**Issue by mdjnewman** [spring-projects/spring-boot#11072]
Given two test classes annotated with `@SpringBootTest(webEnvironment = DEFINED_PORT)` that have different properties configured using `@TestPropertySource`, the second test to run will always fail as the port is never released when the context is closed after the tests in the first class complete.

See https://github.com/mdjnewman/spring-boot-issues/tree/3a035fddd0891a93c23e4023e0e65e27ac267275/gh-11072 for a reproduction.

**Expected behaviour**: `DemoApplicationTests1` & `DemoApplicationTests2`, when they're both run via IDE and/or gradle, should pass.

**Actual behaviour**:

```
:test

com.example.demo.DemoApplicationTests2 > contextLoads FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException
2017-11-17 16:50:12.998  INFO 35367 --- [       Thread-6] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@761f1c16: startup date [Fri Nov 17 16:50:10 CST 2017]; root of context hierarchy

2 tests completed, 1 failed
:test FAILED
```

---
Spring Boot Version: 1.5.8.RELEASE
JVM: 1.8.0_141

**Comment by snicoll** [comment]
You indeed get two contexts when `TestPropertySource` is different but the contexts are cached so if you want to use a defined port with two different context you have to dispose one of them. See [`@DirtiesContext` for more details](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/testing.html#dirtiescontext).

**Comment by mdjnewman** [comment]
Thanks @snicoll , and sorry for the noise. I'll take a look at using `@DirtiesContext`.
