### ISSUE TITLE
Upgrade to Spring Session Data MongoDB 2.0.0.RC2

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#11083]
It would be nice if we could get `master` to build against snapshots in the meanwhile. This would also unblock #11055 and #11063.

**Comment by snicoll** [comment]
@vpavic `master` now builds against the snapshots. Any news about the bom? Thanks!

**Comment by vpavic** [comment]
Thanks!

Regarding the BOM, we should get @rwinch into discussion on that topic.

**Comment by vpavic** [comment]
Renaming to track the RC2 - see [#11082 (comment)](https://github.com/spring-projects/spring-boot/issues/11082#issuecomment-347340963).
