### ISSUE TITLE
spring data apply a web console for h2 database,but did not do any secure check about the user  input,this result in a xss attack

### ISSUE THREAD

**Issue by jenyJoba** [spring-projects/spring-boot#11081]
add the H2 dependency  to my Maven POM:
![image](https://user-images.githubusercontent.com/33446650/32999092-2688442a-cddb-11e7-8145-253cf7287fba.png)
enable the web console
![image](https://user-images.githubusercontent.com/33446650/32999127-3fb5e90c-cddb-11e7-8596-1ddf3580557c.png)

then in the web console,we put <jdbc:h2:~/img src="1" onerror="alert(1)"> in "jdbc url"  input box,and login,poping a alert message box.
it will also create a file in server,if the remote access to web console is enabled,it can be used to create eval file to attack the server.
(I can't upload the image because of limitted network in office,I hope the issue is described clearly)

**Comment by philwebb** [comment]
As [mentioned in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-sql-h2-console), the H2 console should not be used in production.

It's also part of H2 and we just expose it, we didn't develop it. If you want to raise an issue with them, their issue tracker is [here](https://github.com/h2database/h2database/issues).
