### ISSUE TITLE
Support war files in PropertiesLauncher and zip repackaging layout

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11092]
If you use zip layout to repackage a war file, you end up with jars duplicated across `BOOT-INF/lib` and `BOOT-INF/classes/WEB-INF/lib`. I would expect a zip layout war file to be almost identical to an executable war other than it's configured to use the properties launcher rather than the war launcher. This problem with the layout was discovered while investigating #10234.

A secondary problem is that, when layed out as expected, `PropertiesLauncher` will not add `WEB-INF/classes` or jars in `WEB-INF/lib` and `WEB-INF/lib-provided` to the class path.

**Comment by Pramodmk** [comment]
Any update on this enhancement ?

**Comment by wilkinsona** [comment]
Not right now, no. It's very low priority. For the vast majority apps, you don't need to use a war file and can use properties launcher with a jar file instead.

**Comment by rmns86** [comment]
I have the same problem, I'm surprised that it has not been decided yet!

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
