### ISSUE TITLE
Rename properties that have `-` in their prefix

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11090]
We've got a few like `spring.data.cassandra.reactive-repositories.enabled` that should be `spring.data.cassandra.reactiverepositories.enabled`

**Comment by lopez83** [comment]
@philwebb is this something I could work on?

**Comment by philwebb** [comment]
@lopez83 Thanks for the offer but it's a relatively small change that I'll get to today.

**Comment by bclozel** [comment]
I'd like to discuss a bit the case about `spring.resources.*` properties:

* `spring.resources.cache-period` is now `spring.resources.cache.period`
*  `spring.resources.cache-control.*` are now `spring.resources.cache.control.*`

`spring.resources.cache.period=60s` will make Spring Boot serve static resources with a `"Cache-Control: max-age=60` HTTP header. `spring.resources.cache.period=0` will write `"Cache-Control: no-store, no-cache` (don't cache).

You can achieve the same thing and more with `spring.resources.cache.control.max-age=60s`, etc.

Grouping similar properties under `spring.resources.cache` makes sense, but at the same time `spring.resources.cache.period` has a very different meaning (it won't write a `Cache-Period` header) and `spring.resources.cache.control` is a bit odd.

How about the following?

1. `spring.resources.cache-period` and `spring.resources.cachecontrol.*`
2. `spring.resources.cache.period` and `spring.resources.cache.cachecontrol.*`
3. `spring.resources.http.cache-period` and `spring.resources.http.cachecontrol.*`

**Comment by wilkinsona** [comment]
And I'd like to discuss `spring.data.cassandra.reactiverepositories.enabled`.

Until now, I hadn't noticed that we had these two properties:

- `spring.data.mongodb.reactiverepositories.enabled`
- `spring.data.mongodb.repositories.enabled`

I don't really like them, with out without a `-` in the prefix. It we don't foresee a need for other `spring.data.mongodb.reactiverepositories.*` and `spring.data.mongodb.repositories.*` properties, I wonder if we'd be better with a single property that lets you control the types of repositories that are enabled:

```
spring.data.mongodb.repositories.type=BLOCKING | REACTIVE | NONE
```

One thing that appeals to me about this is that it's more consistent with what we've done for `spring.main.web-application-type`.

**Comment by wilkinsona** [comment]
@bclozel I quite like suggestions 1 and 2, with a slight preference for 2. I'm less keen on 3.

**Comment by snicoll** [comment]
@wilkinsona A definitive +1 on the `type` idea (`reactiverepositories` is quite ugly).

@bclozel option 2 looks good to me.

**Comment by philwebb** [comment]
I'm happy with any of the suggested changes as long as we don't have a `-` in the prefix (it messes with binding if we're not careful).

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/11134 to track the possible change to the repositories properties.

**Comment by snicoll** [comment]
The property is still `CacheControl` so we'll generate `cache-control` not `cachecontrol`
