### ISSUE TITLE
Prevent an endpoint id that is incompatible with the new configuration format

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11107]
This [so thread](https://stackoverflow.com/questions/47430918/spring-boot-actuator-endpoint-id-with-spring-boot-2-0) exposes an interesting problem.

We should tune the meta-data generator to sanitize the id so that it doesn't generate wrong metadata for it.

**Comment by cbcgorilla** [comment]
I guess this issue comes from Spring-Boot 2.0.0.BUILD-SNAPSHOT with Spring Framework 5.0.2.BUILD-SNAPSHOT from Nov 20th, If I switch back to Spring-boot 2.0.0.M6+Spring Framework 5.0.1.RELEASE, it works well.
One more issue of this snapshot, only "status" and "info" endpoints can be mapped to the WebMvc, other framework endpoints and customized endpoints can not be mapped to the Webmvc rightly like "/application/status" and "/application/info". Can you help to check it?

**Comment by snicoll** [comment]
@cbcgorilla I have no idea why you believe this would work with M6, IMO that problem is there since the beginning of the new endpoint API.

As for the rest, we don't use the tracker for questions and this sounds completely unrelated. Please join us on Gitter or ask on StackOverflow.

**Comment by snicoll** [comment]
@philwebb regarding https://github.com/spring-projects/spring-boot/issues/11090#issuecomment-346739790 I'd like your thoughts about this. The endpoint id is part of the prefix when we generate the metadata. Perhaps you have something in mind to make sure it is consistent? (Or some code in the binder that does that?)

**Comment by snicoll** [comment]
@philwebb I am not sure that's a good idea. `myService` should be perfectly fine, that's what you'd do in a `@ConfigurationProperites` bean property anyway. The real problem is that we translate that to `myService` rather than `my-service`. If we did, all would be well. 

Thinking about this once more, we already have the code for this so I should just apply what we're doing for properties (silly me).

**Comment by jfgosselin** [comment]
@snicoll I ran into this issue in our migration from Spring Boot 1.5.x to 2.1.0. I'm confused by the answer,  is it possible to use a camel-cased if for the Endpoint or not ? If yes how ?

**Comment by snicoll** [comment]
@jfgosselin there is an example of such endpoint in the commit just above your comment. If you have more questions, please ask them on StackOverflow or come chat with us on Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
