### ISSUE TITLE
In application.properties file, false value is converted to null

### ISSUE THREAD

**Issue by wei-hai** [spring-projects/spring-boot#11106]
I use class Environment to get property value from file application.properties, when a property value is set to `true`, the return value is `true`, when the value is set to `false`, the return value is `null` instead of `false`, the expected value should be `false`

**Comment by philwebb** [comment]
Adding this to out simple test application with `foo=false` in the properties appears to work fine:

```java
	@Bean
	public String testBean(Environment env) {
		System.out.println(env.getProperty("foo", Boolean.class));
		return "test";
	}
```

Please could you provide a sample application that shows the problem?

**Comment by wei-hai** [comment]
Here is my application.properties file, the value of the last property `kamom.system-metrics.sigar-enabled` is `false` and when I read it using Environment the return value is `null`

```
# Kamon
kamon.influxdb.hostname=localhost
kamon.influxdb.port=8200
kamon.influxdb.max-packet-size=1024
kamon.influxdb.application-name=kamon-backend-service
kamon.influxdb.protocol=udp
kamon.influxdb.database=telegraf
kamon.metric.tick-interval=60 seconds
kamon.metric.default-collection-context-buffer-size=1000
kamom.system-metrics.sigar-enabled=false
```

**Comment by wilkinsona** [comment]
Thanks, but we really need a complete example. The code that’s reading the property is just as important as the file that’s setting it. Something that we can unzip or clone and then run without having to change or add anything is ideal.

**Comment by wei-hai** [comment]
false alarm, it was a typo in my properties file.
