### ISSUE TITLE
EndpointMBeanExportAutoConfiguration does not support setting the registrationPolicy for the EndpointMBeanExporter

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-boot#11104]
We have an implementation of `org.springframework.boot.actuate.endpoint.AbstractEndpoint` that we expose using an implementation of `org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter`.

The `EndpointMBeanExporter` is attempting to expose this instance of `AbstractEndpoint` as a JMX bean. But we've registered a MBean using into the same JMX path using the Annotations (since we have some custom operations) and so the `EndpointMBeanExporter` logs an error calling this out as a duplicate. While this is not breaking anything the error log is annoying is since it happens on every startup.

I believe the solution would be for `EndpointMBeanExportAutoConfiguration` to support setting the `registrationPolicy` on `EndpointMBeanExporter` and we can set it to ignore existing which will get rid of this error log.

**Comment by wilkinsona** [comment]
It sounds like your endpoint is really MVC-specific with some similar, JMX-specific functionality being provided use a different mechanism. If that's the case, I'd recommend that you subclass `AbstractMvcEndpoint` rather than `AbstractEndpoint`.

**Comment by sudr** [comment]
If we switch to having our endpoint extend AbstractMvcEndpoint instead of AbstractEndpoint then the EndpointMvcAdapter fails to compile since it requires an Endpoint implementation and AbstractMvcEndpoint doesn't implement the Endpoint interface.

**Comment by wilkinsona** [comment]
`EndpointMvcAdapter` is intended to adapt an `Endpoint` into an `MvcEndpoint`. If you subclass `AbstractMvcEndpoint`, your endpoint is already an `MvcEndpoint` so there's no need to adapt it.

**Comment by sudr** [comment]
Thanks. I see that now. We had it designed incorrectly. Please consider this a non-issue.
