### ISSUE TITLE
Can not control HttpClient's logging level

### ISSUE THREAD

**Issue by unlimitedsola** [spring-projects/spring-boot#11119]
`Netty`'s `LoggingHandler` gives pretty hex dump which is considerably useful
when trying to set logging level of `LoggingHandler` by configuring `application.yml` as below
```
logging:
  level:
    reactor.ipc.netty.http.client.HttpClient: debug
```
it doesn't work 

but if we set root level to DEBUG, the `LoggingHandler` prints hex dump as expected.
```
logging:
  level:
    root: debug
```

**Comment by wilkinsona** [comment]
This appears to be a bug in Reactor Netty. It [only adds the log handler if debug logging is enabled for `reactor.ipc.netty.channel.ContextHandler`](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/channel/ContextHandler.java#L435-L437). Can you please [raise a Reactor Netty issue](https://github.com/reactor/reactor-netty/issues) as there's nothing we can do about this in Spring Boot.

In the meantime, this configuration will give you roughly what you want:

```
logging.level.reactor.ipc.netty.channel.ContextHandler=debug
logging.level.reactor.ipc.netty.http.client.HttpClient=debug
```
