### ISSUE TITLE
Add Neo4jHealthIndicator to Auto-configured HealthIndicators documentation

### ISSUE THREAD

**Issue by espiegelberg** [spring-projects/spring-boot#11114]
The recently PR'd Neo4jHealthIndicator should be added to the "Auto-configured HealthIndicators" documentation.

PR to resolve this issue: https://github.com/spring-projects/spring-boot/pull/11115

**Comment by wilkinsona** [comment]
Duplicate of #11115.

Thanks, @espiegelberg. If you also intend to open a pull request, please feel free to just do that rather than opening an issue as well.
