### ISSUE TITLE
DevTools - Exception in thread "File Watcher"... when build failed

### ISSUE THREAD

**Issue by snoobvn** [spring-projects/spring-boot#11116]
Currently If the project failed to build, the devtools will stop working and throw an IllegalArgumentException exception like this:
![build](https://user-images.githubusercontent.com/6419729/33145855-90e54596-cff4-11e7-9429-6c2d98e25b00.png)

In these cases I must fix the problem and hard restart the application, how about DevTools just ignore the exception and keep the application running (maybe waiting for the matching folder to recreate and perform another restart)

**Comment by philwebb** [comment]
I don't think ignoring the exception is a good idea since it's usually an indication that something has gone seriously wrong. In this case I think the penalty of needing a restart is justified.

I'm happy to change my mind if someone wants to experiment and submit a pull-request.
