### ISSUE TITLE
Rework properties for enabling Spring Data repositories

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11134]
See https://github.com/spring-projects/spring-boot/issues/11090#issuecomment-346643871.

**Comment by snicoll** [comment]
The default value is `BOTH` by the way.

**Comment by wilkinsona** [comment]
Properties to consider:

- `spring.data.cassandra.reactiverepositories.enabled`
- `spring.data.cassandra.repositories.enabled`
- `spring.data.couchbase.reactiverepositories.enabled`
- `spring.data.couchbase.repositories.enabled`
- `spring.data.elasticsearch.repositories.enabled`
- `spring.data.jpa.repositories.enabled`
- `spring.data.ldap.repositories.enabled`
- `spring.data.mongodb.reactiverepositories.enabled`
- `spring.data.mongodb.repositories.enabled`
- `spring.data.neo4j.repositories.enabled`
- `spring.data.redis.repositories.enabled`
- `spring.data.solr.repositories.enabled`

The properties for Cassandra, MongoDB, and Couhbase prompted the change as having both `reactiverepositories.enabled` and `repositories.enable` is rather ugly. The proposal is to have a single property that can be used to enable reactive repositories, blocking repositories, or nothing. For example:

```
spring.data.cassandra.repositories.type=BLOCKING | NONE | REACTIVE | ALL
```

This raises the question of what to do with Elasticsearch, JPA, LDAP, Redis, and Solr. Should they have a `.type` property as well that can be `BLOCKING` or `NONE`? Or should they stick with `.enabled` for now?

**Comment by snicoll** [comment]
> This raises the question of what to do with Elasticsearch, JPA, LDAP, Redis, and Solr. 

`NONE` feels a weird choice when all you can do is select it or not. For that reason alone I'd be in favour to keep the `enabled` flag for those.

**Comment by mp911de** [comment]
FWIW: What about imperative instead of blocking?

**Comment by wilkinsona** [comment]
I like that, @mp911de. Thanks for the suggestion.
