### ISSUE TITLE
bootRepackage's jar rewriting defeats Gradle's up-to-date checks, causing unnecessary rebuilds

### ISSUE THREAD

**Issue by toolforger** [spring-projects/spring-boot#1113]
`bootRepackage` overwrites `build/libs/xxx.jar`, keeping the original jar as `build/libs/xxx.jar.original`.

On the next build, Gradle will find that `build/libs/xxx.jar` has been changed compared to what the previous run's `jar` task left, so it will assume that `build/libs/xxx.jar` needs to be regenerated.

Possible solutions that I can see:
1) Don't overwrite `build/libs/xxx.jar`, generate `build/libs/xxx.boot.jar`. (Please see #1112 for another issue that affects the naming code.)
2) Modify Gradle's `jar` task so that it generates the uber jar right off the bat.

**Comment by youribonnaffe** [comment]
If I understand correctly, is setting a classifier for `bootRepackage`the only way to get an (almost) incremental build with Gradle?
I tried with the spring-boot-sample-simple project with version 1.3.0-RELEASE and without 
````
bootRepackage {
        classifier = "full"
}
````
`jar` and `bootRepackage` tasks will always be executed.
Even with this setup, the task `findMainClass` is always executed.

**Comment by wilkinsona** [comment]
> If I understand correctly, is setting a classifier for bootRepackagethe only way to get an (almost) incremental build with Gradle?

Yes. Gradle re-runs that jar task as the repackage task has overwritten its output. You can see this by running your build with --info. For example:

```
Executing task ':jar' (up-to-date check took 0.031 secs) due to:
  Output file /Users/awilkinson/dev/spring/spring-boot/spring-boot-samples/spring-boot-sample-simple/build/libs/spring-boot-sample-simple-0.0.0.jar has changed.
```

Setting a classifier prevents this as it causes the repackage task to write the repackaged jar to a separate location. I'm not sure that requiring a classifier was the right way to solve the problem that was reported in this issue. Producing an entirely separate artifact may have been better. If you'd like us to revisit this, please open a new issue.

> Even with this setup, the task findMainClass is always executed.

`findMainClass` doesn't declare any outputs so Gradle always assumes that it's out of date and needs to be run. If you'd like that to be improved please open a new issue or, even better, a pull request.

**Comment by bademux** [comment]
Overriding original jar is pure evil, try to
```groovy
testCompile project(':my_spring_boot_application')
```
... and build can't find original sources.
 imho it was really bad decision, because it overrides default gradle behavior

**Comment by philwebb** [comment]
@bademux I don't think it's _"pure evil"_ or a _"really bad decision"_ and comments like this on a issues that's been closed a year aren't really constructive. Have you tried reading [this section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-an-additional-executable-jar) which describes how you can use a Spring Boot application as a dependency?

**Comment by bademux** [comment]
@philwebb changing default behavior of my building system isn't exactly what I expect from spring plugin. Thanks for the link.
