### ISSUE TITLE
Enhance WebMvcMetrics to meter HTTP response codes

### ISSUE THREAD

**Issue by alex859** [spring-projects/spring-boot#11130]
It would be useful to have not only Timer metrics for requests but also a meter for response statuses.

I am thinking at something like
```java
@GetMapping("/api/people")
@Timed
@HttpStatusMetered
public List<Person> listPeople() { ... }
```
with a new annotation (should it be added in micrometer?) and then some new methods in `WebMvcMetrics` to increment a counter.

If you think this can be useful, I would be happy to contribute.

Thank you.

**Comment by snicoll** [comment]
Thanks for sharing the idea but metrics are managed in the micrometer project now. Can you please create an issue [in their issue tracker](https://github.com/micrometer-metrics/micrometer)?
