### ISSUE TITLE
REST SERVICE DOCUMENTATION 

### ISSUE THREAD

**Issue by jhonToni** [spring-projects/spring-boot#11141]
I want to create a  `web service  REST` with` spring boot` and `oauth2`.
Which  books can i read for know more about this ?

**Comment by wilkinsona** [comment]
Sorry, but the issue tracker isn't the right place for questions like this. You might like to start by looking at https://spring.io/guides. Google will also turn up lots of suggestions for tutorials and books about Spring and Spring Boot.
