### ISSUE TITLE
Support DevTools condition evaluation delta across JVM restarts

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11140]
This is a follow on from #9115 to enhance the current implementation to persist the condition evaluation report so that a delta can be produced across restarts of the JVM. This would allow, for example, the changes in condition evaluation caused by adding or removing a dependency to be logged.

Persisting the condition evaluation report is somewhat challenging as the current types aren't particularly amenable to being stored on disk. Ideally, we'd want to be able to serialise and deserialise them using basic JDK classes rather than relying on Jackson or the like.

**Comment by mbhave** [comment]
This looks like a duplicate of #6743.

**Comment by wilkinsona** [comment]
Agreed.
