### ISSUE TITLE
Rename `UserDetailsRepositoryReactiveAuthenticationManager` to `UserDetailsServiceReactiveAuthenticationManager`

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#11163]
When updated [my sample codes](https://github.com/hantsy/spring-reactive-sample) to the latest Spring Boot 2.0.0.M6. I found there are lots of naming strategies are changed in Spring Security.

eg. `UserDetailsRepository` -> `ReactiveUserDetialsService`

I found naming of  `UserDetailsRepositoryReactiveAuthenticationManager` is still based on the old `UserDetailsRepository`, I think it is better to use `UserDetailsServiceReactiveAuthenticationManager` instead.

**Comment by wilkinsona** [comment]
`UserDetailsRepositoryReactiveAuthenticationManager` is part of Spring Security. If you'd like to pursue this, please raise a [Spring Security issue](https://github.com/spring-projects/spring-security).

**Comment by hantsy** [comment]
created https://github.com/spring-projects/spring-security/issues/4868
