### ISSUE TITLE
Defensively check if response is already committed in AbstractErrorWebExceptionHandler

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#11168]
In `AbstractErrorWebExceptionHandler`, we should check if the response has been committed already.

If it's been committed already, Spring Boot's error handling should skip handling it and log that error at the DEBUG level; chances are, such errors happen when clients disconnect from streaming responses so we should not log those at a higher level.

If not committed, the error handling should process that error.

Originally raised as [SPR-16231](https://jira.spring.io/browse/SPR-16231).

**Comment by rstoyanchev** [comment]
> skip handling it and log that error at the DEBUG level

If you skip handling and the error remains unhandled, it will reach `HttpWebHandlerAdapter` which will log it anyway. There is some further logic in there to avoid creating noise with "Broken pipe" type errors. So you could skip logging altogether, or alternatively treat it as a TRACE (or DEBUG) level, one line log messages to indicate response is already committed. Certainly void the full strack trace. 

There is an app attached to SPR-16231 that you can use to test the effect of the output.
