### ISSUE TITLE
Support the reactive Cloud Foundry Java client

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#11160]
Please provide an integration with the Reactive Cloud Foundry Java Client. It would be very nice to be able to add `spring-boot-starter-cloudfoundry` and specify a few properties so that I could then inject a `CloudfoundryOperations` and use it to drive CF. cc @nebhale

**Comment by philwebb** [comment]
I'm not convinced that using the Reactive Cloud Foundry Java Client is something that most users will need that often. What's the common use-case for the client? How difficult is it to configure currently?

**Comment by spencergibb** [comment]
Maybe in Spring Cloud Cloudfoundry?

**Comment by nebhale** [comment]
I'd say that our expected configuration looks a lot like [this](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/ExampleConfiguration.java#L61).  I'm not averse to us (the Java Client team) maintaining an auto-configuration and starter if that's the appropriate choice.

Other than the obvious desire for someone else to maintain things for me, I don't have a strong opinion either way.  Whatever makes the most sense and is the most idiomatic for Boot.

**Comment by spencergibb** [comment]
We currently have something like this for the old clien

https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/3aadc3579629e3d25360860e599d8ae16a28af23/spring-cloud-cloudfoundry-discovery/src/main/java/org/springframework/cloud/cloudfoundry/discovery/CloudFoundryDiscoveryClientConfiguration.java#L53

Seems like a decent spot to put it. Similar to fabric8 client for k8s in spring cloud k8s

**Comment by snicoll** [comment]
Thanks @spencergibb, this looks more natural to do that there. @joshlong can you please create an issue in the [spring-cloud-cloudfoundry project](https://github.com/spring-cloud/spring-cloud-cloudfoundry/issues) instead?
