### ISSUE TITLE
Fix typo in import - plexus-util

### ISSUE THREAD

**Issue by slachiewicz** [spring-projects/spring-boot#11188]
Fix typo in AbstractEmbeddedServletContainerIntegrationTests import of org.codehaus.plexus.util.StringUtils -> should be org.springframework.util.StringUtils

**Comment by snicoll** [comment]
@slachiewicz thanks. FYI there is no need to open an issue and a PR. A PR is enough.

**Comment by snicoll** [comment]
Duplicate of #11189
