### ISSUE TITLE
Websockets bug

### ISSUE THREAD

**Issue by cmargulhano** [spring-projects/spring-boot#11187]
I configured a websocket:

```
@Configuration
@EnableWebSocket
public class LightweightParkingStationWebSocketConfiguration implements WebSocketConfigurer {

	@Autowired
	private WebSocketMsgHandler webSocketMsgHandler;

	@Override
	public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
		registry.addHandler(webSocketMsgHandler, "/").setAllowedOrigins("*");
	}
}

```
Everything was working, but when I added a controller with a POST method, the microservice started to show this error:

`2017-11-28 15:07:23.843  WARN 15455 --- [  XNIO-2 task-2] o.s.web.servlet.PageNotFound             : Request method 'GET' not supported`

And when I try from a websocket client:

```
WebSocket connection to 'ws://192.168.10.200:9000/lightweight-parking-station' failed: Error during WebSocket handshake: Unexpected response code: 405
open @ index.js:15
(anonymous) @ index.js:95
handle @ jquery-1.4.3.min.js:63
n @ jquery-1.4.3.min.js:56
index.js:64 [Violation] 'error' handler took 5473ms
```

**Comment by wilkinsona** [comment]
It sounds like you have overlapping, and therefore misconfigured, mappings. Can you provide a sample that illustrates the behaviour you have described?

**Comment by cmargulhano** [comment]
This is my controller:

@RestController
public class DisplayController {

	@Autowired
	@Qualifier("LCD1602")
	private DisplayPeripheralService displayPeripheralService;

	@RequestMapping(name = "/v1/displays", method = POST)
	@ResponseStatus(code = HttpStatus.CREATED)
	public void display(@RequestBody DisplayVO display) throws Exception {
		String[] texts = new String[display.getTexts().size()];
		texts = display.getTexts().toArray(texts);
		displayPeripheralService.text(texts);
	}
}

I have another controller that implements the GET method and works perfectly, but when I add the POST method with this controller the 405 error appears.

**Comment by cmargulhano** [comment]
I think this guy is going through the same:
https://stackoverflow.com/questions/31570021/failed-to-create-websocket-connection-when-spring-security-is-on

**Comment by bclozel** [comment]
Your `@RequestMapping` declaration has a typo, you're setting the `name` attribute instead of the `path`. So this is probably being mapped to `"/"` by default.

**Comment by cmargulhano** [comment]
That's right, it worked. However, I think this should be documented or there should be a message in the Spring Boot console saying that the mapping is being replaced. Thanks a lot.

**Comment by wilkinsona** [comment]
The mapping isn't being replaced, rather the default is being used as you haven't configured it. That's the documented behaviour for the `@RequestMapping` annotation. I don't think we can log anything to the console as there's no way to differentiate between someone who's deliberately using the default, and someone who's made a mistake similar to yours.
