### ISSUE TITLE
gradle bootRun returns an error that the commandline is too long

### ISSUE THREAD

**Issue by frederichenry** [spring-projects/spring-boot#11197]
when running gradle bootRun I ran into  an error java.io.IOException: CreateProcess error=206, The filename or extension is too long because of a really long classpath dependencies.

I know that there is a workaround : http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/.

But isn't it possible to include this workaround in the gradle plugin for spring boot.  

Note: this happens only on windows.

**Comment by wilkinsona** [comment]
It's an interesting suggestion, thanks. It would certainly be possible to implement this in Boot's Gradle plugin, however I'm not sure that's the best place to do so. The `BootRun` task is a subclass of Gradle's `JavaExec`. If the functionality were added to `JavaExec`, all `JavaExec`-based tasks would benefit. Can you please raise a [Gradle issue](https://github.com/gradle/gradle) to discuss the possibility and link to it from here? If the proposal's declined by the Gradle team, then we can consider re-opening this issue and implementing something in Boot.
