### ISSUE TITLE
Boot loader does not correctly handle URL containing refer

### ISSUE THREAD

**Issue by pengpengli** [spring-projects/spring-boot#11198]
In this class "spring-boot/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/Handler.java", I found method "parseURL" No correct handling of URL containing refer. some times we may add #xxx or param like ?a=1 at end of url.

**Comment by bclozel** [comment]
Your description is not clear at all to me.

Could you improve this issue with:
* what are you trying to achieve
* provide a sample application that demonstrates the behaviour you're seeing
* explain what was the behaviour you expected

**Comment by pengpengli** [comment]
thank you, I wrote the following code, I hope to make it clear. 
it worked without using spring-boot-maven-plugin, and when we package it and run but can't get correct results  

    String helloWorld() throws Exception {
        URL url = getClass().getClassLoader().getResource("example.txt");
        InputStream in = url.openStream();
        byte[] buffer = new byte[1024];
        while ((in.read(buffer)) != -1) {
            System.out.print(new String(buffer));
        }
        in.close();

        String string = "";
        URL url1 = new URL(url, "#from_example.txt!/root");
        in = url1.openStream();
        while ((in.read(buffer)) != -1) {
            string = new String(buffer);
        }
        in.close();

        return string;
    }

**Comment by wilkinsona** [comment]
Sorry, but things still aren't really clear. As @bclozel requested above, can you please provide a sample application that demonstrates the behaviour you're seeing? I'm particularly interested in knowing what file in your jar you expect `new URL(url, "#from_example.txt!/root")` to access.

**Comment by pengpengli** [comment]
We can create a new web app using spring boot and 

1. Create a new class named Hello
@Controller
@EnableAutoConfiguration
public class Hello {
    @RequestMapping("/index")
    @ResponseBody
    String index() throws Exception {
        URL url = getClass().getClassLoader().getResource("example.txt");
        InputStream in = url.openStream();
        byte[] buffer = new byte[1024];
        while ((in.read(buffer)) != -1) {
            System.out.print(new String(buffer));
        }
        in.close();

        String string = "";

        URL url1 = new URL(url, "#from_example.txt!/root");
        in = url1.openStream();
        while ((in.read(buffer)) != -1) {
            string = new String(buffer);
        }
        in.close();

        return string;
    }
}

2. Use spring-boot-maven-plugin package the code to a jar

3. java -jar (step 2 ).jar

4. Open browser and input http://localhost:port/index

5. The issue will be display

Our app will scan all the packages and find some resources, we will record the resources from which 
 package useing the URL ref field like above code.

thanks

**Comment by wilkinsona** [comment]
Thanks, but that doesn't explain what you expect `new URL(url, "#from_example.txt!/root");` to do. 

Can you please provide a complete example (a repository on GitHub would be ideal) that demonstrates the behaviour that you expect to see and the behaviour that you're actually seeing? One or more tests in the sample with assertions would be ideal.

**Comment by pengpengli** [comment]
Thanks, Object URL provides us with this ability. We happen to take advantage of this feature, but the feature after using spring-boot-maven-plugin is gone,  it just feels that the original URL should be maintained.

**Comment by pengpengli** [comment]
Thanks again, this does not affect us, because our application does not use spring-boot-maven-plugin to package.
