### ISSUE TITLE
Add ping endpoint

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11191]
A general purpose ping endpoint that simply returns `200` could be useful.

**Comment by psycho-ir** [comment]
hi @philwebb, 
I would be happy to work on this enhancement.
Could you please provide a bit more context about this issue?

**Comment by wilkinsona** [comment]
I'm not sure about this one. The benefit over anonymously accessing the health indicator seems pretty small. I wonder if there's any commonly used infrastructure that would use both `/ping` and `/health` and make use of the possibly different status code that each would return?

**Comment by snicoll** [comment]
Didn't we create this issue due to the initial design of the `health` endpoint in 2.0? Now that this has been revisited and we have a proper strategy, I am not sure this issue makes more sense.
