### ISSUE TITLE
Support for Thymeleaf templates and static resources in Starter-like modules

### ISSUE THREAD

**Issue by igo** [spring-projects/spring-boot#112]
It would be great to be able to decompose webapp into Starter-like modules. These modules would contain not only java classes but also Thymeleaf templates and static resources. For example, Boot should be able to support creating reusable module called "starter-users" which contains model, services and controllers for user registration, login, management, etc... with all java classes, thymeleaf views and static files.

**Comment by jdbranham** [comment]
I had a similar thought, and was able to resolve the templates using a custom resolver. You can check out the project here -

https://github.com/savantly-net/sprout-spring-boot-starter

**Comment by bclozel** [comment]
I don't think this approach fits in the scope of this project nor that we should provide an opinion about that. I'm closing this issue now.

@jdbranham if you'd like this starter to be listed with other community-maintained starters here, [please follow the guidelines documented in our reference docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter) and then submit a new issue on this tracker.

**Comment by jdbranham** [comment]
Thanks @bclozel 
My project may be too opinionated now as I've expanded on the original scope, but thanks for the heads-up!
