### ISSUE TITLE
Application.properties not loading in expected order

### ISSUE THREAD

**Issue by jkratz55** [spring-projects/spring-boot#11209]
I am seeing behavior that seems counter intuitive to how at least I am expecting Spring Boot to handle loading of application.properties. In our environment we already have established Tomcat servers so we are required to deploy as WAR. We have application.properties file in /resources/config/ inside the WAR and there is an application.properties file on the classpath in Tomcat.

I'm expecting the application.properties on the Tomcat server which is higher on the classpath to overwrite the one bundled in the WAR but this is not happening. My application is failing to start because required properties are missing. If I delete the properties file in the WAR, then Spring boot is finding and using the one from Tomcat classpath.

Looking at this https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html I expect the external application.properties to override the application.properties inside the WAR.

Is this a limitation of using WAR instead of JAR or is this a bug in Spring Boot?

**Comment by wilkinsona** [comment]
By default, Tomcat prefers classes/resources in a war file to those available to the common or system class loaders. If you want to invert this behaviour, you need to configure Tomcat with `<Loader delegate="true"/>`. Please see [Tomcat's documentation](https://tomcat.apache.org/tomcat-8.5-doc/class-loader-howto.html) for more details.
