### ISSUE TITLE
Typo in docs for enabling/disabling jmx endpoints?

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#11204]
In $ https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-disable-jmx-endpoints it is mentioned:

If you do not want to expose endpoints over JMX, you can set the `endpoints.default.jmx.enabled` property to false, as shown in the following example:

`endpoints.default.jmx.enabled=false`

shouldn't this be `management.endpoints.jmx.enabled=true`?

**Comment by snicoll** [comment]
Indeed @marceloverdijk - Thanks a lot for the report!
