### ISSUE TITLE
Improve documentation for WebTestClient

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11203]
`WebTestClient` is a new api that can be used on a "mock server" (direct call to the controller) as well as running servers (integration tests). It also provides assertions and other utilities that make it a better choice than `TestRestTemplate`.

We should review the documentation to mention this and help users if they chose to migrate

Useful resources:

https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#webmvc-client
https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#webtestclient

**Comment by snicoll** [comment]
Let's wait for #11579.

**Comment by rstoyanchev** [comment]
The sample is good but there is only a brief "if you prefer you can use..." mention in the random port section. It would merit to a small section named `WebTestClient` I think to discuss it as an option for use in integration tests like [there is](https://github.com/spring-projects/spring-boot/blob/027e6baba53a83e385bc307925c654c55da346a8/spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#testresttemplate) for the `RestTestTemplate`. It would also allow creating links to such a section from elsewhere (even from extenrnal sources).

**Comment by snicoll** [comment]
@rstoyanchev the reason why I didn't add a dedicated section is that this feature is supposed to be covered in the Spring Framework reference guide (and it is). `TestRestTemplate` is ours and [in a section about Spring Boot utilities](https://github.com/spring-projects/spring-boot/blob/027e6baba53a83e385bc307925c654c55da346a8/spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#test-utilities) so I didn't want to imply that `WebTestClient` is Spring Boot specific as well.

Thoughts?

**Comment by rstoyanchev** [comment]
Ok I see. Taking another look, I can suggest a few opportunities...

[Auto-configured Spring MVC Tests](https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-mvc-tests), add paragraph for full end-to-end integration tests which is a natural question but can't be done with MockMvc alone.

[Auto-configured Spring WebFlux Tests](https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-webflux-tests), add extra explanation that WebTestClient can also do full end-to-end integration tests and maybe reference the section on the random port feature.

It seems like what's missing is a section on full end-to-end testing. Arguably [Working with Random Ports](https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-webflux-tests) is exactly that, but it could use being named more explicitly so. The section can explain it can be done with the WebTestClient, or with the TestRestTemplate if so inclined (note the subtle switch from "if you prefer, you can use the WebTestClient" to ".. or TestRestTemplate if so inclined"), i.e. clearly suggesting one over the other. After all WebTestClient (like the WebClient) can do everything better and it it also has a dedicated API for verifying responses.

The section on "Auto-configured Spring REST Docs Tests", should that have a new sub-section on doing the same with the WebTestClient which I think is now supported? Or is that separately tracked?

As for the TestRestTemplate section, I would prefix it with: it's provided but there is not much reason to prefer it over the WebTestClient. Potentially even consolidate with section on Random Port which I suggested to rename to "Full end-to-end testing", "Testing with a running server" or something similar.
