### ISSUE TITLE
ConverterNotFoundException for java.time.Duration when using YAML-based configuration

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-boot#11216]
After upgrading from M6 to M7 I get:

Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.session.timeout' to java.time.Duration
...
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Integer] to type [@org.springframework.boot.context.properties.bind.convert.DefaultDurationUnit java.time.Duration]

**Comment by wilkinsona** [comment]
Thanks for the bug report. This appears to be specific to YAML configuration where a value of, say, `60` is coerced to an `Integer` and the converter's expecting a String (which is what you always get from a properties file).

If you are using YAML, you can work around the problem by either specifying a unit for the duration or by wrapping the integer value in quotes:

```yaml
server:
  session:
    timeout: "60"
```

**Comment by igler** [comment]
There is also an error "Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.tomcat.background-processor-delay' to java.time.Duration" where I did not set "background-processor-delay" in my YAML file.

**Comment by wilkinsona** [comment]
@igler Interesting, thanks. I haven't seen that in working on this issue. Could you provide a small sample that reproduces that behaviour please?

**Comment by igler** [comment]
Found a solution by removing 'server.tomcat.background-processor-delay'. Finally found it in my YAML-file. Sorry for disturbing.
