### ISSUE TITLE
Acuator not working

### ISSUE THREAD

**Issue by mschoenb** [spring-projects/spring-boot#11217]
I'm using Spring Boot 2.0.0M7, Finchley.M2 (Finchley.M4 doesn't seem to work with Eureka because of version mismatch in one the the poms, which refers to a M5 version, Eureka classes can not be found with this version) and Java 9.

As soon as I include

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

in conjuction with

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>

(same seems to happen with the Eureka Client) in my project's pom.xml the application fails to start and complains that "requestMappingHandlerMapping" can not be created. It starts when I remove the eureka or the actuator dependency.

I've attached simple project, which shows the behaviour.

**Comment by mschoenb** [comment]
[MatEurekaServer.zip](https://github.com/spring-projects/spring-boot/files/1517659/MatEurekaServer.zip)

**Comment by wilkinsona** [comment]
Finchlely M2 isn't compatible with Boot M7, hence the failure that you're seeing. You should raise the Eureka problem that's stopping you from using M4 with the Spring Cloud team.
