### ISSUE TITLE
@ConfigurationProperties and YAML array notation

### ISSUE THREAD

**Issue by kvarbyte** [spring-projects/spring-boot#11229]
When creating a array in YAML using multi line as follows:

``` yaml
foo:
    - bar1
    - bar2
    - bar3
```
And having the following class to load the YAML properties:
``` java
@Configuration
@ConfigurationProperties
public class ApplicationProperties {
    private List<String> foo;
    
    public List<String> getFoo() {
        return foo;
    }
    
    public void setFoo(List<String> foo) {
        this.foo = foo;
    }
}
```

I would expect the `setFoo` to be called (which it does) with the values defined in my YAML. However these are always empty (`foo` argument is null). Once injecting the bean somewhere else it does have the values, so there seems to be some binding done later on.

However, when I make it a comma seperated list in the YAML:

``` yaml    
foo: bar1,bar2,bar3
```
`setFoo` gets called and the argument `foo` is filled with an array with the values `["bar1", "bar2", "bar3"]`.

Is this expected behaviour? I couldn't find anything in the documentation, unless I read over it. 

Tested with Spring boot version: 1.5.8.RELEASE.

**Comment by snicoll** [comment]
The first case is using the getter to populate the list for each element, the second case sets the array with the comma-separated values. That's how binding works.

>  I couldn't find anything in the documentation, unless I read over it.

What documentation are you expecting  exactly? You haven't really told us what the problem is.

**Comment by kvarbyte** [comment]
Thank you. I didn't know binding worked like this.

No problem anymore, was mostly wondering why it worked like this.
