### ISSUE TITLE
Upgrade to Hibernate 5.2.13

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11238]
When we do this, we should drop dependency management for javassist: #11225.

**Comment by rmsantana** [comment]
Latest release of Hibernate is version 5.2.12.Final, which is already set in the spring-boot-dependencies project.

[Hibernate 5.2 series](http://hibernate.org/orm/releases/5.2/)

**Comment by wilkinsona** [comment]
Thanks, but we already know that. We are awaiting the release of 5.2.13 as it contains a bug fix that we’re interested in. More details are available in the issue that’s linked to above.

**Comment by snicoll** [comment]
I've [asked if we'd get a Hibernate 5.2.13 release this month still and [it looks like it may be the case](https://twitter.com/vlad_mihalcea/status/948950710355456001).

**Comment by wilkinsona** [comment]
There's no sign of 5.2.13 with 13 issues still to be fixed and no release date yet. Pushing back to RC2.

**Comment by andrei-ivanov** [comment]
It's out :-)
