### ISSUE TITLE
Angular.js app cannot access Boot Actuator endpoints over CORS

### ISSUE THREAD

**Issue by amccubbin** [spring-projects/spring-boot#1124]
My defined endpoints seem to work fine through the simple CORS filter from 
http://spring.io/guides/gs/rest-service-cors/

However, when I try to access the actuator endpoints with my angularjs app in chrome (running through grunt) I get the following:

XMLHttpRequest cannot load http://localhost:9091/manage/health. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:9000' is therefore not allowed access. 

XMLHttpRequest cannot load http://localhost:9091/manage/metrics. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:9000' is therefore not allowed access. 

Completing a request for the endpoint in Chrome I get the appropriate response

{"status":"ok","database":"HSQL Database Engine","hello":1} 

I know that Chrome has some issues doing CORS on localhost for development due to security permissions, but some endpoints (those that I have defined) are accessible. There just seems to be issues accessing the actuator endpoints. 

Is there something  I need to change in my CORS filter or a property that needs to specified for the actuator endpoints?

**Comment by pompeyjoe** [comment]
I'm having this same issue and actually want my management endpoints on a different port.  Is there a way to configure the Access-Control-* headers for the actuator endpoints?
