### ISSUE TITLE
Endpoint ID "hikariCP" cause application failed start

### ISSUE THREAD

**Issue by javamonkey** [spring-projects/spring-boot#11247]
Spring Boot 2.0.0.M7:
`
@Endpoint(id = "hikariCP")
public class HikariCPEndpoint {
}
`
Appliclation faild start and show the error message:

`
Configuration property name 'management.endpoint.hikariCP.cache.time-to-live' is not valid:

    Invalid characters: 'C', 'P'
    Bean: jmxMBeanExporter
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'management.endpoint.hikariCP.cache.time-to-live' so that it conforms to the canonical names requirements.
`

i change id name to **"hikari"**,everything is ok.  also fine if i  change version to 2.0.0.M6.

it seems the method  "InvalidConfigurationPropertyNameException.throwIfHasInvalidChars " throw this exception

**Comment by snicoll** [comment]
I mentioned that it was already reported in the other issue you've raised. https://github.com/spring-projects/spring-boot/issues/11046#issuecomment-348770437
