### ISSUE TITLE
Consider additional kafka properties

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#11257]
There is at least one property `....consumer.idle-event-interval` (and likely more, e.g. `....consumer.no-poll-interval`) that would be useful to expose as Boot configuration properties.

Add these, and examine the current state of auto config against any new properties that may have been added since we last revised boot auto config.

__feel free to assign to me (I don't have permissions to assign)__

**Comment by snicoll** [comment]
@garyrussell if you intended a submit a  PR for this, there is no need for an issue. The PR is enough. Are you taking care of this?

**Comment by garyrussell** [comment]
Eventually, yes, before the RC.

I don't get the "we don't need an issue if there's going to be a PR" approach.

How do you guys track your TODO lists? Without a github assigned issue, I'd have to track this TODO, someplace else.

Wouldn't having an open issue with a target milestone give you a picture of what's needed to be completed before a milestone can be built?

**Comment by garyrussell** [comment]
Also, with an open issue, perhaps a community member might want to contribute a commit.

**Comment by snicoll** [comment]
I am not denying any of that. I was reacting to "feel free to assign to me". That lead me to think you will take care of it in which case there is no need for an issue. 

If you want a community member to pick this up, we can flag it ideal for contribution but we should expand the description a bit more first.

**Comment by garyrussell** [comment]
Yeah - it needs some research so it's probably easier if I do it. However, it's not high on my priority list (but I do want to get it in before the RC); hence this placeholder so I don't forget.

**Comment by snicoll** [comment]
@garyrussell do you think you'll be able to work on a PR in the coming weeks for this?

**Comment by garyrussell** [comment]
@snicoll Yes; my plan is to do so before Boot's RC1 - maybe even this week.

**Comment by snicoll** [comment]
Closing in favour of PR #11502
