### ISSUE TITLE
Spring Boot 2.0.0.M7 Social Config gone

### ISSUE THREAD

**Issue by philippeboyd** [spring-projects/spring-boot#11253]
Linked to PR https://github.com/spring-projects/spring-boot/pull/11117

What does it mean by `autoconfig has been absorbed into Spring Social itself`?
So I've removed my social starters and added the normal ones : 

```
compile(group: 'org.springframework.social', name: 'spring-social-facebook', version: '3.0.0.M3')
compile(group: 'org.springframework.social', name: 'spring-social-linkedin', version: '2.0.0.M3')
compile(group: 'org.springframework.social', name: 'spring-social-twitter', version: '2.0.0.M4')
```

But Autoconfig doesn't seem to work because I get

`Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.social.config.annotation.SocialConfiguration': Unsatisfied dependency expressed through method 'setSocialConfigurers' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.springframework.social.config.annotation.SocialConfigurer>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

I'm assuming the following properties no longer work...

```properties
spring.social.facebook.app-id=fb_app_id
spring.social.facebook.app-secret=fb_app_secret
spring.social.twitter.app-id=twitter_app_id
spring.social.twitter.app-secret=twitter_app_secret
spring.social.linkedin.app-id=linkedin_app_id
spring.social.linkedin.app-secret=linkedin_app_secret
```

@habuma mentionned that `autoconfig has been absorbed into Spring Social itself`. How do we auto configure them now?

**Comment by wilkinsona** [comment]
This is really a question for the Spring Social project. A Spring Boot issue isn't really the right place to discuss this as it won't culminate in any changes to Boot. In short, there are new `*-autoconfigure` modules in Spring Social snapshots that you will need to use. I believe, @habuma has a blog post planned once all the pieces are in place and, perhaps, new milestones have been released.

**Comment by philippeboyd** [comment]
Indeed I've just found those new modules you mentioned in https://repo.spring.io/libs-snapshot/org/springframework/social/

Adding the followings did the trick :

```
compile(group: 'org.springframework.social', name: 'spring-social-facebook-autoconfigure', version: '3.0.0.BUILD-SNAPSHOT')
compile(group: 'org.springframework.social', name: 'spring-social-linkedin-autoconfigure', version: '2.0.0.BUILD-SNAPSHOT')
compile(group: 'org.springframework.social', name: 'spring-social-twitter-autoconfigure', version: '2.0.0.BUILD-SNAPSHOT')
```

Thanks for pointing that out @wilkinsona :)
Cheers
