### ISSUE TITLE
@RefreshScope unnessesarily loads beans which are overidden in test

### ISSUE THREAD

**Issue by jschmied** [spring-projects/spring-boot#11259]
I have a @Configuration and a @TestConfiguration, both define the same bean.

I get in the log:
DefaultListableBeanFactory: Overriding bean definition for bean 'mongo' with a different definition: replacing ...

The Bean from @TestConfiguration is used in test.
The method annotated with @Bean is **not called** on @Configuration.
The method annotated with @Bean is **called** on @TestConfiguration.

When I activate @RefreshScope on first Bean the test is still working but:

The method annotated with @Bean is **called** on @Configuration.
The method annotated with @Bean is **called** on @TestConfiguration.

I would like to prevent initializing the bean in @Configuration for unit test since it needs external ressources.

I think a bean should be removed from refresh scope when the beandefinition is overridden by @TestConfiguration.

Instantiation happends in RefreshScope.start() -> this.context.getBean(name);

Overriding of beans happends: DefaultListableBeanFactory -> registerBeanDefinition()

Versions:
cloud-context 1.2.4
spring 4.3.7
boot 1.5.2

**Comment by wilkinsona** [comment]
Refresh scope is part of Spring Cloud. Please open a [Spring Cloud Commons](https://github.com/spring-cloud/spring-cloud-commons).
