### ISSUE TITLE
Consider adding @AutoconfigureTestMongo

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#11266]
Right now, if there is an embedded mongo on the classpath, adding a `spring.data.mongodb.url`, doesn't cause the application to use the one specified in the properties. We should consider doing something similar to JPA where the embedded database is used only in `@DataJpaTest` or if there is no other datasource specified.

**Comment by ayudovin** [comment]
@mbhave , as far as i understand you would like to configure something like `TestEntityManager` but for Mongo ?

**Comment by philwebb** [comment]
We're going to generally suggest test containers going forward.
