### ISSUE TITLE
Debugger does not attach and breakpoints not hit when using Maven in 2.0.0.M7 and Netbeans

### ISSUE THREAD

**Issue by Snymant** [spring-projects/spring-boot#11269]
This is possibly related to #10872 when using gradle.

Issue: Debugger does not attach when using springboot maven plugin on springboot starter 2.0.0.M7
Works when using 2.0.0.M2, when changing spring-boot-starter-parent version to 2.0.0.M3 or up debugger no longer attaches.

Steps to reproduce:
Create new spring initializer project with version 2.0.0.M7
Set breakpoint on main SpringApplication.run
Debug project in Netbeans - application starts without hitting breakpoint.
Change version in pom.xml to 2.0.0.M2
Debug project in Netbeans - application starts and hits breakpoint.

**Comment by wilkinsona** [comment]
> Debug project in Netbeans

How are you doing this? Are you debugging the application via Netbeans' Maven integration or by directly running the application's main method?

**Comment by Snymant** [comment]
Debugging via Netbeans Maven integration.
When doing right-click > debug file the debugger attaches correctly

**Comment by wilkinsona** [comment]
My guess is that Spring Boot's Maven plugin is forking a new JVM and NetBeans is attempting to debug the JVM running the Maven build, rather than the JVM running the application. If so, this will need to be handled as a Netbeans enhancement request.  It's only a guess as you haven't described in sufficient detail how to reproduce the behaviour that you're seeing.

Can you please provide a minimal sample and step-by-step instructions to reproduce the problem?

**Comment by Snymant** [comment]
Ok while preparing a demo I created a project with both the spring initializer website (https://start.spring.io/) and via the Netbeans Spring plugin
Issue is the Netbeans Spring Plugin creates nbactions.xml that passes additional flags to debugger which seems to cause the issue. 
```xml
        <properties>
            <run.jvmArguments>-Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=${jpda.address} -noverify -XX:TieredStopAtLevel=1 </run.jvmArguments>
            <run.mainClass>za.co.bronkode.SpringMavenDebugApplication</run.mainClass>
            <Env.SPRING_OUTPUT_ANSI_ENABLED>always</Env.SPRING_OUTPUT_ANSI_ENABLED>
            <jpda.listen>true</jpda.listen>
        </properties>
```

Removing the nbactions.xml file resolves issue.
