### ISSUE TITLE
Can't git clone the project

### ISSUE THREAD

**Issue by freezehe** [spring-projects/spring-boot#11270]
hi,I have a problem.I can't git clone the code on my windows,the error is  "unable to create file spring-boot-project/spring-boot-tools/spring-boot-g                                 radle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/Dependenc                                 yManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFai                                 lsToResolve.gradle: Filename too long",
so please help me.thanks

**Comment by wilkinsona** [comment]
Duplicate of #10953
