### ISSUE TITLE
Fix package tangle in Cloudfoundry management context configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11273]
<img width="226" alt="screen shot 2017-12-06 at 14 37 35" src="https://user-images.githubusercontent.com/914682/33666825-0aad0942-da93-11e7-8304-6f7601efc419.png">

**Comment by wilkinsona** [comment]
We should also review the use of `@AutoConfigureBefore` and `@AutoConfigureAfter` as they won't, AFAIK, have the desired effect on a `@ManagementContextConfiguration` class.

**Comment by mbhave** [comment]
@wilkinsona good catch on the package tangle. could you explain why the `@AutoConfigureBefore`, `@AutoConfigureAfter` won't work?

**Comment by wilkinsona** [comment]
IIRC, they're only considered by the auto-configuration import selector and not by the management context configuration import selector. That makes sense as the management context configuration classes are loaded separately to auto-configuration classes.

**Comment by mbhave** [comment]
thanks. I'm still a little unsure because the classes that it was using `@AutoConfigureBefore` and `@AutoConfigureAfter` on were under `@EnableAutoConfiguration` and not `ManagementContextConfiguration`. In any case, fixing the package tangle might remove it.

**Comment by wilkinsona** [comment]
Sorry, on closer inspection I realise now that the class in question (was `CloudFoundryHealthWebEndpointManagementContextConfiguration`, now `CloudFoundryHealthWebEndpointAutoConfiguration`) is an auto-configuration class rather than a management context configuration class. Therefore, the use of `@AutoConfigureBefore` and `@AutoConfigureAfter` is not a problem.
