### ISSUE TITLE
Configure Checkstyle to tighten up import restrictions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11271]
We should restrict the following:

- Commons Lang
- Commons Lang 3
- Guava

**Comment by dreis2211** [comment]
@wilkinsona Out of interest (and with the risk of asking a stupid question): What's the reasoning behind those restrictions?

**Comment by wilkinsona** [comment]
They are transitive dependencies of various libraries that Boot supports, but we don’t want to accidentally use them in Boot’s own code.

**Comment by dreis2211** [comment]
I see - thanks for the heads-up. Good to know for contributors.
