### ISSUE TITLE
Putting property comments on fields rather than getters/setters makes them unavailable in the generated JavaDocs APIs

### ISSUE THREAD

**Issue by behrangs-sportsbet** [spring-projects/spring-boot#11279]
At the moment, JavaDoc comments for configuration properties are placed on their field descriptions. For example:

https://github.com/spring-projects/spring-boot/blob/6d6abce55cd775299b5578192f62dbebdb987469/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L225-L229

Produces this empty JavaDoc:

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/kafka/KafkaProperties.Consumer.html#getAutoOffsetReset--

Either the comments need to be moved to the getters/setters or JavaDoc should be configured to include comments on these fields in the generated HTML files.

**Comment by snicoll** [comment]
> Either the comments need to be moved to the getters/setters or JavaDoc should be configured to include comments on these fields in the generated HTML files.

Why? Those objects are used for environment binding and are not meant to be used directly in application's code. The backed properties are documented both in your IDE and [in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by behrangs-sportsbet** [comment]
I think when someone searches for, say, `KafkaProperties` in Google (or [Dash](https://kapeli.com/dash), etc.) and opens its JavaDocs API page, it would be nicer if its properties were documented there too.

Also, when in IDEA, I sometimes want to see all the properties available for configuring a given Spring component and press `Command + B` on one of its properties in the `application.yml` file, and IDEA takes me to the source code for the setter for that property, but then I have to scroll to the field declarations section to see its comments.

So either the comments should be placed on the getter/setters or JavaDoc should be configured to generate field documentation for these category of classes. 

I guess this is a low priority change and others might think it is not necessary, but in my opinion, as these configuration property classes are commented on so well, it is a pity that the comments do not appear in their JavaDocs pages.

**Comment by snicoll** [comment]
We've discussed this one at our team meeting today. That  documentation is specific to configuration properties metadata  (that's why it is on the field and not the accessor) and we're not keen to expose that in the Javadoc API.
