### ISSUE TITLE
@Selector seems not working in M7

### ISSUE THREAD

**Issue by sebastienminne** [spring-projects/spring-boot#11274]
I'm trying to get a custom endpoint working on M7 release, here is the code 

```
@Component
@Endpoint(id = "mycache")
class WebCacheEndpoint {

	@ReadOperation
	public Map<String, Object> cache() {
		Info.Builder builder = new Info.Builder();
		builder.withDetail("blabla", "blabla");

		Info build = builder.build();
		return build.getDetails();
	}

	@ReadOperation
	public Map<String, Object> cache2(@Selector String test) {
		Info.Builder builder = new Info.Builder();
		builder.withDetail("blabla", test);

		Info build = builder.build();
		return build.getDetails();
	}
}
```

I can see routes in the logs : 
INFO 69597 --- [           main] .b.a.e.w.r.WebFluxEndpointHandlerMapping : Mapped "{[/mycache]
INFO 69597 --- [           main] .b.a.e.w.r.WebFluxEndpointHandlerMapping : Mapped "{[/mycache/{arg0}]

I get a response form /mycache but having a 400 bad request on /mycache/{arg0}

Could that be an issue on that version ?

**Comment by snicoll** [comment]
Are you sure you're running with m7? Arg0 means the parameter name wasn't found and that should lead to an exception. 

You need to compile with -parameters.

**Comment by sebastienminne** [comment]
Yes I'm running M7, can't see any exception. 

What do you mean to compile with -parameters ?

**Comment by snicoll** [comment]
Can you please share a sample that reproduces the problem?

**Comment by sebastienminne** [comment]
Here it is : https://github.com/sebastienminne/actuator-selector-issue

route /mycache is fine 
route /mycache/test is not

**Comment by snicoll** [comment]
Duplicates #10618 #10001

The endpoint infrastructure is using parameter names to infer the selector name. Your project  works if I run it with `mvn spring-boot:run` (because the flag is set automatically) and having it named `{arg0}` is an indication that the `-parameters` javac flag. I guess you're running this from your IDE and you should configure it to add `-parameters` as well.
