### ISSUE TITLE
CloudWatch metrics autoconfiguration

### ISSUE THREAD

**Issue by dkublik** [spring-projects/spring-boot#11275]
Hi,
from version 1.0.0-rc5 micrometer.io suppors CloudWatch metrics (my little contribution)
Thought it would be great to also have autoconfiguration for it.

**Comment by dkublik** [comment]
PR https://github.com/spring-projects/spring-boot/pull/11276

**Comment by snicoll** [comment]
@dkublik no need for an issue and a PR. Thanks!
