### ISSUE TITLE
spring-boot-starter-mqseries

### ISSUE THREAD

**Issue by abedwardsw** [spring-projects/spring-boot#11289]
Hi there, I want to contribute and create spring-boot-starter-mqseries module (I have most of the code already), however I wanted to first confirm that the maintainers would accept the contribution before I formalize and create the pull request.

Functionality:
 - Similar to spring-boot-starter-activemq it would provide a convenient way to autoconfigurethe jmsconnection factory object and related objects/pools in a standard/configurable way for IBM MQSeries connections.
 - as mqseries is not java, It wouldn't be trivial to have the ability to start a broker unless we want to add dependency on docker.  the docker mqseries container is quite good though https://hub.docker.com/r/ibmcom/mq/.   If you think this is a good idea we could add some ability to auto-start a docker container although I wasn't planning to do this.

Issue:
  I am bringing this up as I am not sure what we can do here.   The problem is that I need to depend on allclient-9.0.4.jar for compilation which can be downloaded freely from here: http://www-01.ibm.com/support/docview.wss?uid=swg24042176   however i am sure there are redistribution issues etc.     
  Due to this dependency, is it possible to still contribute spring-boot-starter-mqseries? Is there a better way to contribute these libraries which have proprietary dependencies?

**Comment by wilkinsona** [comment]
Thanks for the offer, @abedwardsw. Everything that Boot depends on needs to be available from Maven Central (other than snapshots or milestones). Unfortunately, that means that a dependency on something closed source is a show stopper I'm afraid.

You might want to make contact with @ebullient from IBM. She's leading an effort to provide auto-configuration for various parts of IBM's middleware portfolio.
