### ISSUE TITLE
spring-boot-autoconfigure-processor incorrectly process @ConditionalOnClass with an inner class value

### ISSUE THREAD

**Issue by jearton** [spring-projects/spring-boot#11282]
## Problem Detail: 
I'm using Spring Boot 1.5.9.RELEASE.  When spring-boot-autoconfigure-processor process  `@ConditionalOnClass` with an inner class value, there is no dollar sign in the generated text of inner class.

## Verify Steps:

1. Clone this repository: `https://github.com/jearton/spring-boot-autoconfigure-processor-issue.git`

2. Execute `cd spring-boot-autoconfigure-processor-issue && ./mvnw clean compile`

3. View the file `target/classes/META-INF/spring-autoconfigure-metadata.properties`, 
   you'll see the difference. First is dot, second is dollar. The second is correct.

**Comment by snicoll** [comment]
Thank you for the report and the sample, that's very useful!
