### ISSUE TITLE
Health details always shown when using custom management.server.port

### ISSUE THREAD

**Issue by philippeboyd** [spring-projects/spring-boot#11285]
When setting up a custom management port :

```properties
management.server.port=8088
```

The property `management.endpoint.health.show-details=false` is ignored. Health details is always shown.

Here's my test repository : https://github.com/philippeboyd/spring-boot-health-bug

**Comment by wilkinsona** [comment]
Thanks for the bug report and sample.

The root cause is that the web-specific extension for the health endpoint isn't being found. As a result, `show-details` has no effect and the status mapping also doesn't occur. The latter means that a status of `DOWN` still results in a 200 response:

```
http :8081/actuator/health
HTTP/1.1 200
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Thu, 07 Dec 2017 17:18:49 GMT
Transfer-Encoding: chunked

{
    "details": {
        "diskSpace": {
            "details": {
                "free": 107550699520,
                "threshold": 10485760,
                "total": 499046809600
            },
            "status": "UP"
        },
        "unhealthy": {
            "status": "DOWN"
        }
    },
    "status": "DOWN"
}
```
