### ISSUE TITLE
java -jar ... ,start failed, the lib directory contains.exe files cannot be started

### ISSUE THREAD

**Issue by guozhiqiangha** [spring-projects/spring-boot#11296]
hello,
When the project is a war pack, java-jar... start,   the lib directory contains.exe files cannot be started.Can't you have an exe file in lib when java-war started?

in cmd started failed
![image](https://user-images.githubusercontent.com/12888479/33770482-ab094d16-dc68-11e7-97c9-b6c015ab00b9.png)

in pcf started failed 
![image](https://user-images.githubusercontent.com/12888479/33770513-c94e3d18-dc68-11e7-8344-094a895ed38e.png)

**Comment by guozhiqiangha** [comment]
I use JSP , spring boot 1.4.5 ,the WEB-INF/lib directory contains  .exe file,  
build mvn package,
when  java -jar .war    start   fail

**Comment by guozhiqiangha** [comment]
how can i use .exe in lib

**Comment by wilkinsona** [comment]
WEB-INF/lib is expected to contain jar files, the contents of which are then added to the classpath. An exe file is not a jar so I don’t think it belongs in WEB-INF/lib. I would expect it to be packaged in WEB-INF/classes from where it can be loaded as a resource.
