### ISSUE TITLE
bootstrap.properties not working with @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)

### ISSUE THREAD

**Issue by FibreFoX** [spring-projects/spring-boot#11295]
Hi folks,

as I can not find anything regarding my scenario, this might be a bug in general.

Currently I'm developing some spring-boot-application which contains some library using some entry inside it's own `bootstrap.properties`, but it seems to not work while testing.

I've created some dummy project for re-creating my scenario (as I'm not allowed to give out my working project): https://github.com/FibreFoX/spring-boot-with-bootstrap-and-feign-testing-bug

I'm not sure if this is related to #4424 (or even the same problem).

Sorry if this is the wrong project for my problem

**Comment by snicoll** [comment]
`bootstrap.properties` is not managed in Spring Boot but it is a Spring Cloud concept. I'd ask on the #spring-cloud channel how you can mitigate this problem as I guess you shouldn't be the first one to ask.

**Comment by FibreFoX** [comment]
@snicoll thanks for the hint, but what "channel" do you mean?

**Comment by snicoll** [comment]
I am sorry, I meant the Gitter channel.
