### ISSUE TITLE
Not possible to test web controllers with Kotlin and webflux

### ISSUE THREAD

**Issue by ufoscout** [spring-projects/spring-boot#11293]
Hi all,

in a demo app with Kotlin, WebFlux and SpringBoot 2 M7 we are not able to test a simple "helloWorld" controller. We tried with both WebMvcTest and WebfluxTest annotations.

This test fails with a `java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurer` error:
```
@RunWith(SpringRunner::class)
@WebMvcTest(Controller::class)
class ControllerMVC_Test {

    @Autowired
    lateinit var mockMvc: MockMvc

    @Test
    fun testHelloWorldMVC() {
        mockMvc.perform(
                get("/mvc")
        ).andExpect(
                content().string(Controller.MESSAGE)
        )
    }
}
```

And this one does not compile due to [this issue](https://youtrack.jetbrains.com/issue/KT-5464) and [this one](https://jira.spring.io/browse/SPR-15692):
```
@RunWith(SpringRunner::class)
@WebFluxTest(Controller::class)
class ControllerWebFlux_Test {

    @Autowired
    lateinit var webTestClient: WebTestClient

    @Test
    fun testHelloWorldWebFlux() {
        webTestClient.get()
                .uri("/webflux")
                .exchange()
                .expectStatus().isAccepted()
                .expectBody<String>(Controller.MESSAGE)
    }
}
```

I wonder if it is feasible at this point to write a full application with spring-boot 2 and kotlin.
Here a small reproducer: https://github.com/ufoscout/spring-boot-2-reactive-kotlin

**Comment by snicoll** [comment]
> I wonder if it is feasible at this point to write a full application with spring-boot 2 and kotlin.

Yes, there's absolutely no problem with that. You are however using coroutines and that is super early stage at this point still. This issue looks like more of a question so I am going to close it as there is nothing in Spring Boot itself that is related to that. 

I am also paging @sdeleuze in case he wants to add something. We can reopen if it turns out something has to be done specifically here.

**Comment by sdeleuze** [comment]
Indeed Coroutine are not yet supported officially, even if [spring-koltin-coroutine](https://github.com/konrad-kaminski/spring-kotlin-coroutine) makes good progresses, and `WebTestClient` issue [is mentioned in Spring documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin-webtestclient-issue) and need to be fixed on Kotlin side, so I see nothing to fix here.

See [mixit](https://github.com/mixitconf/mixit) or [spring-kotlin-deepdive](https://github.com/sdeleuze/spring-kotlin-deepdive/tree/step4) if you want examples of Spring Boot 2 + Kotlin application examples.
