### ISSUE TITLE
Authorization Header is shown by Actuator trace endpoint

### ISSUE THREAD

**Issue by gronono** [spring-projects/spring-boot#11291]
Hello

The actuator's trace endpoint shows the Authorization request header. Everybody who can access this endpoint can view basic authentication credentials or can stole bearer token. It might be an security issue.

In our case, system administrators and developers have access to this endpoint. So if one of this people is malicious he/she can usurp any user's identity.

I made a workaround by providing my own implementation of TraceRepository. But it will be great if Spring Boot could handle this issue by itself.

Regards.

**Comment by mbhave** [comment]
@gronono The `WebRequestTraceFilter` trace filters out the authorization header unless it is explicitly included in `management.trace.include`. Can you provide a small sample that reproduces the issue?

**Comment by gronono** [comment]
@mbhave I did some tests. This issue is present in version 1.4.7 but it was fixed in version 1.5.0 or newer.

Thanks.

**Comment by gronono** [comment]
see #7974
