### ISSUE TITLE
Fail if endpoint include/exclude references endpoint that doesn't support technology

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11298]
For example fail if `management.endpoints.jmx.exposure.include=jolokia` because jolokia isn't available under JMX.

**Comment by snicoll** [comment]
I am not 100% sure that this is worth it. The current arrangement uses the `EndpointFilter` concept to provides a list of `Endpoints`. Yet, you need the list of endpoints to figure out if a value there is invalid. Implementing this feature would require a significant update of the internal for little benefit.

I suggest that we close this issue.

**Comment by wilkinsona** [comment]
Based on that analysis, +1 for closing this one.
