### ISSUE TITLE
No default implementation for org.springframework.boot.actuate.audit.AuditEventRepository in boot 2.0.0.M7

### ISSUE THREAD

**Issue by iferca** [spring-projects/spring-boot#11307]
Playing around with spring-boot version `2.0.0.M7` and migrating some existing services I found the service fails to initialize error`ing like this:

```
Parameter 2 of constructor in c.m.e.EventStore required a bean of type 'org.springframework.boot.actuate.audit.AuditEventRepository' that could not be found.
```

I solved it by creating an `InMemoryAuditEventRepository` bean. I had to do this only for the `2.0.0.M7` back in `1.5.9.RELEASE` that was not necessary.

**Comment by wilkinsona** [comment]
It should be auto-configured by `AuditAutoConfiguration` that’s part of `spring-boot-actuator-autoconfigure`. If you do not believe that is happening, please provide a sample that reproduces the behaviour you have described.

**Comment by iferca** [comment]
I'll close this issue since this was a dependency problem in my parent POM. Thanks for your help @wilkinsona
