### ISSUE TITLE
MetricsRestTemplateCustomizer registered twice -> creating thousands of metrics

### ISSUE THREAD

**Issue by dkublik** [spring-projects/spring-boot#11315]
MetricsRestTemplateCustomizer.customize() is called twice when creating RestTemplate:

1. Because it is registered by RestTemplateMetricsConfiguration
so it will be added to customizers list in RestTemplateBuilder,

RestTemplateBuilder.build()
	RestTemplateBuilder.configure()
		MetricsRestTemplateCustomizer.customize()

2. By MetricsInterceptorPostProcessor
AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization()
	RestTemplateMetricsConfiguration.MetricsInterceptorPostProcessor.postProcessAfterInitialization()
		MetricsRestTemplateCustomizer.customize()

MetricsRestTemplateCustomizer adds MetricsClientHttpRequestInterceptor (twice), which records metrics.
Metric tags are provided using urlTemplate stored in ThreadLocal -  as urls

schedulable-content?cdrId=45916843-3507-4382-9299-70820c162f47
schedulable-content?cdrIdd5c9cd30-2eb4-4331-8ba0-a9f957773c71

should produce same tag from template: schedulable-content?cdrId=${cdrId}

hovewer ThreadLocal is cleaned after first intercept, so for the second no urlTemplate is avaialable.
This results in creation of two metrics:
1. general - based on url template
2. single metric for every set of url parameters - which results in thousands of metrics making metrics unreadable.

In my local project without MetricsClientHttpRequestInterceptor everything works  as expected.

Every metric created twice:
<img width="679" alt="screen shot 2017-12-11 at 19 05 32" src="https://user-images.githubusercontent.com/5848865/33847557-3819bcc4-deab-11e7-832f-267a50855d41.png">

Thousands of metrics created as new metric is created for every distinct url param:
![screen shot 2017-12-11 at 19 24 38](https://user-images.githubusercontent.com/5848865/33847569-3d376210-deab-11e7-8996-4d04f98f340c.png)

**Comment by dkublik** [comment]
simple fix: https://github.com/spring-projects/spring-boot/pull/11316

**Comment by snicoll** [comment]
Closing in favour of PR #11316
