### ISSUE TITLE
MeterRegistryConfigurers should be applied to the MeterRegistry before it becomes injectable

### ISSUE THREAD

**Issue by alex859** [spring-projects/spring-boot#11317]
This is the same issue already fixed in [micrometer-spring-legacy](https://github.com/micrometer-metrics/micrometer/issues/158). 
When injecting a `MeterRegistry`, custom configurations have not been applied yet.

Those configurations should be applied when creating the default `MeterRegistry` in `MetricsAutoConfiguration`. 
I'll add a pull request for this.

**Comment by bclozel** [comment]
Duplicate of #11319
