### ISSUE TITLE
Running without a Web Container in SpringBoot 2.0.0 M7

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#11322]
According to the Spring Boot 2.0.0.M1 release notes:

> The webEnvironment flag (spring.main.web-environment) is now deprecated in favour of the WebApplicationType enum

What is the intended way for us to set this so that we don't run a web container? For example if we want to run and then exit when a `CommandLineRunner` is complete.

It appears that the `WebApplicationType` enum values are: `NONE`, `REACTIVE` and `SERVLET`, as such I've tried many variations on this config:
```
spring:
  main:
    web-environment: NONE
```
However all result in simply one uninformative line:
```
Process finished with exit code 1
```

Providing this config still works (in 2.0.0.M7 and 1.5.x):
```
spring:
  main:
    web-environment: false
```

**Comment by snicoll** [comment]
Are you using IDE support? It should tell you that the property is deprecated and what its replacement is (`spring.main.web-application-type`). This is also described [in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#web-environment).
