### ISSUE TITLE
Support for multiple jOOQ datasources

### ISSUE THREAD

**Issue by scranen** [spring-projects/spring-boot#11324]
I'm configuring a Spring Boot application that needs access to two separate jOOQ datasources (well, DSLContexts). The autoconfiguration does not support this (and it probably shouldn't), but could make this much easier if it would expose the `SpringTransactionProvider` and `JooqExceptionTranslator` classes; these are now package-private. Can we make these public, so they can be re-used in a multi-datasource setup?

**Comment by philwebb** [comment]
That seems like a sensible change to me. Will try to get it in 1.5.10.

**Comment by snicoll** [comment]
>  Can we make these public, so they can be re-used in a multi-datasource setup?

Can you show what that multi-datasource setup would look like? Perhaps there's a middle ground that we could do that make it a bit more easier than just making those two classes public.

**Comment by scranen** [comment]
We are currently just copying the behaviour of the `JooqAutoConfiguration`, but adding qualifiers like. It looks approximately like this (IRL the `DefaultConfiguration` we construct is in a shared library):
```java
@Bean
@Qualifier("datasource1")
@ConfigurationProperties("datasource1")
public DataSourceProperties dataSource1Properties() {
    return new DataSourceProperties();
}

@Bean
@Qualifier("datasource1")
@ConfigurationProperties("datasource1")
public DataSource dataSource1(@Qualifier("datasource1") DataSourceProperties properties) {
    return properties.initializeDataSourceBuilder().build();
}

@Bean
@Qualifier("datasource1")
public DSLContext dsl1(@Qualifier("datasource1") DataSource dataSource, PlatformTransactionManager txManager) {
    DefaultConfiguration config = new DefaultConfiguration();
    config.set(new DataSourceConnectionProvider(new TransactionAwareDataSourceProxy(dataSource)));
    config.set(new DefaultExecuteListenerProvider(new JooqExceptionTranslator()));
    config.set(new SpringTransactionProvider(txManager));
    return new DefaultDSLContext(config);
}
```
The manual construction of the `DataSource` from the `DataSourceProperties` is necessary for the autoconfigured health endpoint to pick up the datasource correctly. IIRC this had something to do with the fact that the Hikari datasource has a `jdbcUrl` property instead of `url`.

**Comment by snicoll** [comment]
>  IIRC this had something to do with the fact that the Hikari datasource has a jdbcUrl property instead of url.

Not really. As soon as you configure more than one `DataSource` you have to configure them since the auto-config backs off. There are  [a few samples in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources)

**Comment by ursjoss** [comment]
In one of my projects, I have an autoconfigured jOOQ datasource in one project module, and multiple manually configured jOOQ datasources in another module.

Until this afternoon, I thought I had tackled the proper configuration of the manual datasources. Inspired by this thread (thanks!), I was about to write some tests to verify I have the same attributes set in terms of execution listener and transaction manager as the autoconfigured datasource.

I was quite surprised that I had missed out quite a bit in my previuos configuration, lacking the transaction aware datasource proxy and the JooqExceptionTranslator completely. I also went down the road @scranen had described by copying the three package protected classes JooqExceptionTranslator, SpringTransactionProvider and SpringTransaction into my project, making the two former ones public.

So I'm really looking forward into what direction this ticket will point. Thanks to all involved elaboration on this.

**Comment by snicoll** [comment]
@ursjoss thanks for the feedback. In the future, we very much prefer you'd report an issue rather than copying  our code in your project. This is a chance for us to discover new cases and, hopefully, improve things.

**Comment by ursjoss** [comment]
@snicoll Sure, I did that just now, based on this discussion. As a temporary means until I can see where this is heading. So I guess the issue was already here before the copying... Or am I missing something?

**Comment by snicoll** [comment]
@ursjoss maybe I do. Unless you've copied those classes today, what I meant to say is that it would have been nice to report an issue when you realized you had to do that (basically what  @scranen did).

**Comment by ursjoss** [comment]
@snicoll Yes, I copied those classes this afternoon, after having read this thread up to and including your comment from 6 hours ago...

**Comment by ursjoss** [comment]
Excellent, thanks for spring-boot-1.5.10.Final resolving this issue.
