### ISSUE TITLE
Incorrect json serialization when field contains "isDirectory"

### ISSUE THREAD

**Issue by legezam** [spring-projects/spring-boot#11337]
Question / Bug report

Hello

I am using Spring boot 2.0M6 and M7 and run into a strange issue. (using from kotlin 1.2.0)

I have a simple result data class:
```
data class MyResponse(
        @JsonProperty("dididi")
        var dadada: String)
```
If i make this a result of a rest controller, i get the expected result:
```
{
    "dididi": "ResponseValue"
}
```

However, if i change the field to this:
```
data class MyResponse(
        @JsonProperty("dididi")
        var isDirectory: String)
```

The response becomes empty:
`{}`

I have tried both as data class and regular class. Also it seems it has something to do with "is" prefix, because the same happens with "isFile" property name.

Am I doing something wrong or this is a bug?

Thank you!

**Comment by bclozel** [comment]
This sounds a lot like a Kotlin and/or Jackson Kotlin Module issue.
Could you first check with the [Kotlin community](https://kotlinlang.org/community/) (on Slack or StackOverflow) and report back here if you find more signs that it's a Spring Boot issue?

We can't answer all questions about all supported technologies in Spring Boot.
Thanks!

**Comment by legezam** [comment]
Alright, will try to chase up with them.
For reference: https://discuss.kotlinlang.org/t/kotlin-doesnt-play-nicely-with-jackson-if-the-property-name-contains-is/5798
