### ISSUE TITLE
Consider tightening `AuditEventRepository` contract

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#11331]
[`AuditEventRepository`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/audit/AuditEventRepository.java) exposes 3 operations for retrieving `AuditEvent`s:

- `AuditEventRepository#find(java.util.Date)`
- `AuditEventRepository#find(java.lang.String, java.util.Date)`
- `AuditEventRepository#find(java.lang.String, java.util.Date, java.lang.String)`

All of these operations allow their parameters to be `null` which IMO isn't ideal, and is also somewhat confusing as all the retrieval options can actually be expressed using `AuditEventRepository#find(java.lang.String, java.util.Date, java.lang.String)`.

Perhaps `AuditEventRepository` contract could be tightened so that it wouldn't allow `null` parameters? This was actually proposed in #5854 as a part of improvements to `AuditEventRepository` however at the time the change wasn't feasible due to backward compatibility considerations. The upcoming 2.0 could be the chance to revisit this.

It's also worth noting that `auditevents` Endpoint already behaves inline with what's proposed above as it requires the presence of `after` parameter.

**Comment by snicoll** [comment]
@vpavic this request has my vote for the `after` parameter. I am not sure I find this so useful for the  `principal` or the `type`. Both are quite interesting when you're looking for any event after a certain date or a given event type after a certain date, but regardless of the principal.

I can see the endpoint requires all three to be set but I find the features above interesting.

What do you think?

**Comment by vpavic** [comment]
Thanks for the feedback @snicoll.

I agree that `after` parameter should definitely be required i.e. the `AuditEventRepository#find` in any form shouldn't allow it to be `null`.

Regarding the other two, `principal` and `type`, they are optional and it's only a question of how to express that the best way in `AuditEventRepository` API's `find` operations. My point is, if we for example have both `List<AuditEvent> find(String principal, Date after, String type)` 
 and `List<AuditEvent> find(String principal, Date after)` then the `type` parameter in the former shouldn't be nullable. OTOH if `List<AuditEvent> find(String principal, Date after, String type)` allows `type` to be nullable that makes the `List<AuditEvent> find(String principal, Date after)` redundant, as API should IMO be straightforward and without overlapping operations.

For the sake of simplicity I think there should only be a single `find` operation, that requires a non-null `after` parameter and allows nullable `principal` and `type` parameters. This is also how the endpoints have it through [`AuditEventsEndpointWebExtension`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/audit/AuditEventsEndpointWebExtension.java) and [`AuditEventsJmxEndpointExtension`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/audit/AuditEventsJmxEndpointExtension.java).

**Comment by wilkinsona** [comment]
FWIW, I find the `null` restriction on `after` to be rather arbitrary and, ultimately, a bit pointless. Rather than passing in `null` I could pass in something like `1900-01-01T00:00:00` and get the same effect.

**Comment by snicoll** [comment]
Thanks @wilkinsona. IMO that makes a compelling case for the status quo. I don't see much benefit in us aligning the contract of `AuditEventRepository` to what the endpoint uses concretely.

**Comment by wilkinsona** [comment]
If we agree that `after` can be null, I'm not sure that status quo is the ideal. I think we should consider either overloading the method with all possible combinations of the three parameters, or only offering a single find method that allows any of the parameters to be null.

**Comment by wilkinsona** [comment]
Label fight!

**Comment by vpavic** [comment]
Agreed with the Andy's comment from above.

I still think that `after` should be considered as being not nullable, since that way if user supplies something like `1900-01-01T00:00:00` it should be pretty obvious what was the intent vs passing in the `null` and potentially triggering a very expensive operation of fetching the contents of an entire `AuditEventRepository`.

**Comment by wilkinsona** [comment]
We've agreed to go with a single method that takes all three, possibly null parameters:

```
List<AuditEvent> find(String principal, Date after, String type)
```
