### ISSUE TITLE
AnnotationAwareOrderComparator doesn't recognize classes annotated with @AutoConfigureOrder

### ISSUE THREAD

**Issue by iadmin08** [spring-projects/spring-boot#11353]
I noticed that there is no comparator class that can handle `Ordered` , `PriorityOrdered` , `@Order` , and `@AutoConfigureOrder` implemented/annotated classes all at once. The framework does have classes that can handle permutations of this (`OrderComparator` or `AnnotationAwareOrderComparator` or `AutoConfigurationSorter`), but nothing that can handle all of them together. 

**For Example, Lets say that we have the following scenario:**

a bean of type myBean named m1 annotated with `@Order` with a order value of 5
a bean of type myBean named m2 annotated with `@AutoConfigureOrder` with a order value 10
a bean of type myBean named m3 that implements `Ordered` with a order value of 4
a bean of type myBean named m4 that implements `PriorityOrdered` with a order value of 4

I would like to see a comparator class that can handle all of these order types prioritizing the types in the following order `@AutoConfigureOrder` , `PriorityOrder` , `@Order` / `Ordered` 

That being the case, the above collection would yield the following sorted order:
m2, m4, m3, m1

Would it be possible to add a class within spring-boot that can properly order a collection beans annotated with each of the above possibilities? I think that this would prove to be a useful feature otherwise developers would end up writing custom code to order these.

**Comment by philwebb** [comment]
It's not clear to me why you would want to mix `@AutoConfigureOrder` with other order annotations. Auto-configuration classes have their own distinct ordering and are always applied after user-defined beans.

Can you provide some more details about what you are trying to achieve? Perhaps a small sample application would help.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
