### ISSUE TITLE
RandomAccessDataFile in Spring Boot loader should report inaccessible file

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#11350]
https://github.com/spring-projects/spring-boot/blob/132467787c51f429e9b889b0de0ac492a60cbdb6/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/data/RandomAccessDataFile.java#L62-L73

The constructor in `RandomAccessDataFile` rejects non-existing files without actually reporting the offending file. Seen in a stack trace caused by the [thin launcher](https://github.com/dsyer/spring-boot-thin-launcher):

<img width="614" alt="jar_fehler" src="https://user-images.githubusercontent.com/128577/33998475-e3dc5830-e0e7-11e7-9292-40a1bb9b8463.PNG">

**Comment by snicoll** [comment]
Closing in favour of PR #11401
