### ISSUE TITLE
spring boot spring.jpa.hibernate.naming.implicit-strategy setting in 1.5.9

### ISSUE THREAD

**Issue by icegood** [spring-projects/spring-boot#11370]
Hello there. I'm using version 1.5.9.RELEASE of spring boot. Accordingly to the [documentation
](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) the setting `spring.jpa.hibernate.naming.implicit-strategy` should work properly however I found that my custom implicit naming strategy is not worked under given setting within application start (i have both `spring.jpa.hibernate.ddl-auto=update` `spring.jpa.generate-ddl=true` to check this). 

However while debugging hibernate sources i found that property `spring.jpa.properties.hibernate.implicit_naming_strategy` is more appropriate and it works for me. Please, either adjust your parameter to a given one or change documentation.

**Comment by icegood** [comment]
Same problem with physical naming strategy. See also lines
=========
this.implicitNamingStrategy = (ImplicitNamingStrategy)strategySelector.resolveDefaultableStrategy(ImplicitNamingStrategy.class, configService.getSettings().get("hibernate.implicit_naming_strategy"), new Callable<ImplicitNamingStrategy>() {
        public ImplicitNamingStrategy call() throws Exception {
          return (ImplicitNamingStrategy)strategySelector.resolveDefaultableStrategy(ImplicitNamingStrategy.class, "default", ImplicitNamingStrategyJpaCompliantImpl.INSTANCE);
        }
      });
      this.physicalNamingStrategy = (PhysicalNamingStrategy)strategySelector.resolveDefaultableStrategy(PhysicalNamingStrategy.class, configService.getSettings().get("hibernate.physical_naming_strategy"), PhysicalNamingStrategyStandardImpl.INSTANCE);
=======
in MetadataBuilderImpl of hibernate.core-5.0.12

**Comment by bclozel** [comment]
Your description lacks context and I don't understand the current issue.
Could you create a reduced sample showing the problem and: describe what you're trying to achieve, what behaviour you expected, what behaviour you got instead?

You've obviously spent quite some time figuring out things and debugging, but we don't have that context (yet).

Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
