### ISSUE TITLE
Not able to use DropwizardMetricServices.

### ISSUE THREAD

**Issue by rajeshdalai** [spring-projects/spring-boot#11382]
I was using DropWizardMetricServices in spring-boot 1.4.1.RELEASE version. What is the alternative in spring-boot 2.0.0

**Comment by spencergibb** [comment]
See micrometer.io

**Comment by bclozel** [comment]
Spencer is right, please [take a look at our Micrometer support](https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/html/production-ready-metrics.html).

For further questions, please use StackOverflow.

**Comment by snicoll** [comment]
@rajadileepkolli we don't use the tracker for questions. Please ask on StackOverflow or join us on Gitter.
