### ISSUE TITLE
KafkaProperties relaxed binding and removal of unknown properties

### ISSUE THREAD

**Issue by zersetz-end** [spring-projects/spring-boot#11385]
The current implementation of KafkaProperties allows additional configuration properties through the properties member of type java.util.Properties. This unfortunately isn't handled by the relaxed configuration binding.

So for example if I try to set the kafka property "security.protocol" through an environment parameter (SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL) it results in a warning log message by kafka:

> 2017-12-20T13:43:29,395  WARN [main] [] [org.apache.kafka.clients.consumer.ConsumerConfig] : The configuration 'SECURITY_PROTOCOL' was supplied but isn't a known config.

And even worse the property isn't set unless I for example map the property in the application.yml.
```yaml
spring:
  kafka:
    properties:
      security:
        protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:SSL}
```
Although this still produces the warning message.

So I suggest that before creating ConsumerFactory/ProducerFactory the property keys are transformed to the lower case/dot separator notation as used by kafka and properties not defined in ConsumerConfig.names() and ProducerConfig.names() respectively are removed from the resulting map.

**Comment by mbhave** [comment]
This is very similar to #9902. Our recommendation is to use the approach suggested [here](https://github.com/spring-projects/spring-boot/issues/9902#issuecomment-318848482).

**Comment by zersetz-end** [comment]
Yes, but the suggested approach still causes the warning message as I mentioned above. And there's the difference that for the JavaMail API there isn't really a way to retrieve those additional properties programatically at runtime, which can be done for Kafka with the mentioned config methods (ConsumerConfig.names() and ProducerConfig.names()).
