### ISSUE TITLE
Excluding (auto) configuration by name is not working in @SpringBootTest

### ISSUE THREAD

**Issue by dusan-eremic** [spring-projects/spring-boot#11398]
Hi, 

Spring Boot 1.5.9
`@EnableAutoConfiguration(exclude = SomeConfig.class)`
is working as expected, however 

`@EnableAutoConfiguration(excludeName = {"com.myapp.SomeConfig"})`
or
`@EnableAutoConfiguration(excludeName = {"com.myapp.SomeConfig.class"})`
or
`@EnableAutoConfiguration(excludeName = {"SomeConfig"})`
or
`@EnableAutoConfiguration(excludeName = {"SomeConfig.class"})`

has no effect - `SomeConfig` does not get excluded.

**Comment by bclozel** [comment]
I can't reproduce that problem; I've used `@EnableAutoConfiguration(excludeName = "io.spring.demo.MyAutoConfiguration")`.

Could you confirm that:
* `SomeConfig` is really an auto-configuration class, i.e. it's annotated with `@Configuration` and declared in a `src/main/resources/META-INF/spring.factories` file?
* `SomeConfig` is not located in a package that's scanned by your application? (typically, any package located under the main Application class)

Can you provide a small repro project we can take a look at?

**Comment by dusan-eremic** [comment]
`SomeConfig` is annotated with `@Configuration` and it is declared inside `src/main/resources/META-INF/spring.factories`inside an external (maven) dependency.

**Comment by bclozel** [comment]
I've tried the following and the auto-configuration is ignored by Spring Boot:

```
@EnableAutoConfiguration(excludeName = "org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration")
```

There must be something more about the setup that we can't figure out by just sharing comments. Can you create a small repro project?

**Comment by dusan-eremic** [comment]
Thank you @bclozel.

I just realised that I forgot to mention that I'm running a SpringBootTest, not the app.

```
@SpringBootTest(webEnvironment = RANDOM_PORT, properties = "debug=true")
@ContextConfiguration(classes = RestTestContextConfig.class)
@RunWith(SpringRunner.class)
public abstract class BaseRestTest {

    @LocalServerPort
    protected int serverPort;
} 
```

```
@SpringBootConfiguration
@EnableAutoConfiguration(excludeName = "com.myapp.SomeConfig")
public class RestTestContextConfig {}
```

**Comment by bclozel** [comment]
You're not supposed to use `@ContextConfiguration` in your `@SpringBootTest` class.
I guess you had an issue with Boot finding the wrong main application class?

Please take a look at [the relevant part of the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-detecting-config) and reopen this issue when you've got a minimal sample that shows an issue.

Thanks!
