### ISSUE TITLE
Helpdesk Ticket 991

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11397]
See [Helpdesk Ticket 991](https://docs.google.com/a/pivotal.io/document/d/1lrjQsKYVDp6UwD9S8YjUqBoqCa0skcohNcZqKGb8ASY/edit?usp=sharing) for details.

**Comment by vpavic** [comment]
Just an observation on this issue and [Boot 1.5.10 release announcement](https://spring.io/blog/2018/01/31/spring-boot-1-5-10-available-now) - looking at 9b8cb9a I believe systemd isn't affected as it only uses `run` method from `launch.script` and actually handles the PID file by itself.
