### ISSUE TITLE
repo.spring.io returning 500 errors.

### ISSUE THREAD

**Issue by d4rk8l1tz** [spring-projects/spring-boot#11390]
Our builds are failing since pulling this artifact from the repo gives 500.
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}
http://repo.spring.io/plugins-release/org/gradle/api/plugins/gradle-tomcat-plugin/1.2.4/gradle-tomcat-plugin-1.2.4.jar

**Comment by jruiz-psl** [comment]
also getting the same, seems that everything behind your nginx is completely down

**Comment by PrakharSrivastav** [comment]
Getting "Received status code 502 from server: Bad Gateway". 
Builds fail

**Comment by wilkinsona** [comment]
Thanks, but this has nothing to do with the Spring Boot project. Please follow `@springops` on Twitter for updates.
