### ISSUE TITLE
Using @JsonTest with java.time Serializer and Deserializer

### ISSUE THREAD

**Issue by gabrielguimaraes** [spring-projects/spring-boot#11404]
Hi everyone,

I am using Spring Boot 1.5.9.RELEASE and I am trying to test json serializer and deserializer when using LocalDateTime for the pattern "yyyy-MM-dd HH:mm:ss".

The problem occurs when trying to Test using `@JsonTest` and to use the class JacksonTester<?>. Even adding the _Serializer_ and _Deserializer_ on my Application,java as a `@PostConstruct` it doesn't work when using JacksonTester<>.
So, even with this configuration I have changed the configuration directly on the Test class, adding the _Serializer_ and _Deserializer_ on the `@Before` method on my `@JsonTest` class but, again, without any results.

So, first I've added this to my Application class

```
	@Autowired 
	private Jackson2ObjectMapperBuilder builder;
	@Value("${spring.jackson.date-time.format:yyyy-MM-dd HH:mm:ss}") 
	private String pattern;

	@PostConstruct
	public void serializerAndDeserializerOfDateTime() {
		DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern(pattern);
		this.builder.serializers(new LocalDateTimeSerializer(dateTimeFormatter));
		this.builder.deserializers(new LocalDateTimeDeserializer(dateTimeFormatter));
	}
```

And my Test class was like this. Remember: I've added the `@Before` method in a second attempt.

```
@RunWith(SpringRunner.class)
@JsonTest
public class PipedriveDealUpdateTest {
	@Autowired
	JacksonTester<PipedriveDealUpdate> dealUpdateJson;
	@Autowired
	private Jackson2ObjectMapperBuilder builder;

	@Value("${spring.jackson.date-time.format:yyyy-MM-dd HH:mm:ss}")
	private String pattern;

        @Before
	public void setup() {
		DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern(pattern);
		LocalDateTimeSerializer localDateTimeSerializer = new LocalDateTimeSerializer(dateTimeFormatter);
		this.builder.serializers(localDateTimeSerializer);
		LocalDateTimeDeserializer localDateTimeDeserializer = new LocalDateTimeDeserializer(dateTimeFormatter);
		this.builder.deserializers(localDateTimeDeserializer);

		ObjectMapper objectMapper = this.builder.build();
		JacksonTester.initFields(this, objectMapper);

	@Test
	public void dealUpdateInformationOk() throws IOException {
		PipedriveDealUpdate pipedriveDealUpdate = dealUpdateJson.readObject(dealUpdate);
        }
```

And I've got this error: 
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.time.LocalDateTime from String "2017-12-22 13:10:33": Text '2017-12-22 13:10:33' could not be parsed at index 10
```

I've got correct result when using the ObjectMapper directly. If I get the ObjectMapper object through Jackson2ObjectMapperBuilder which was previous configured inside the `@Before` I can obtain the expected result using `objectMapper.writeValueAsString(pipedriveDealUpdate)`. 

The DTO classes are just with `LocalDateTime`, like:

```
@Data
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class DealUpdate {
	private Integer id;
	private LocalDateTime updateTime;
```

If this issue is not a Bug and just a misuse of `@JsonTest`, I would like to apologize. 

Cheers,

**Comment by snicoll** [comment]
So if I understood you properly, the builder doesn't have the (de)serializers defined in `serializerAndDeserializerOfDateTime` when used with `@JsonTest`. That code looks weird to me and it is impossible to know for sure without a project that we can run ourselves. 

There is `Jackson2ObjectMapperBuilderCustomizer` that looks a much better fit for this. As `@JsonTest` is only considering a subset of the context, can you please try defining a bean in your `@SpringBootApplication` (or `@SpringBootConfiguration` if you're using that)? If that  doesn't work, please share a project (or the link to a repo).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
