### ISSUE TITLE
Add Spring Boot - Activiti integration to http://start.spring.io/ ?

### ISSUE THREAD

**Issue by jbarrez** [spring-projects/spring-boot#1140]
@joshlong has recently contributed Spring Boot support to Activiti (http://activiti.org), see https://github.com/Activiti/Activiti/tree/master/modules/activiti-spring-boot

Activiti is a popular Java Business Process Management framework with excellent integration with Spring (originally contributed by @dsyer).

It would be cool if Activiti can be added to the list on start.spring.io. 

WDYT?

**Comment by snicoll** [comment]
See https://github.com/spring-io/initializr/issues/155
