### ISSUE TITLE
[Bug] sprint-boot-actuator-autoconfigure jar of 2.0.0.M7 is corrupted

### ISSUE THREAD

**Issue by balajeetm** [spring-projects/spring-boot#11419]
The Milestone 7's sprint-boot-actuator-autoconfigure.jar's apring.factories file seems to corrupted.
The application does not compile or start when this jar is used.

The compile errors are during javadoc creation:
EG. mvn clean install returns
org/springframework/boot/spring-boot-actuator-autoconfigure/2.0.0.M7/spring-boot-actuator-autoconfigure-2.0.0.M7.jar; invalid LOC header (bad signature)

Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/../bin/javadoc @options @packages

If the application is built skipping javadoc
mvn clean install -Dmaven.javadoc.skip=true, the application fails to start
java.lang.IllegalArgumentException: Unable to load factories from location [META-INF/spring.factories]
Caused by: java.util.zip.ZipException: invalid code lengths se

I confirmed that these issues do not exist in the snapshot.

Please release a new milestone version

**Comment by snicoll** [comment]
The jar you've downloaded from the remote repository got corrupted most probably. Remove it from your local maven cache and try again (`mvn dependency:purge-local-repository`). If that doesn't work, we can reopen once you've shared a sample that reproduces the problem you are describing.
