### ISSUE TITLE
Use the char variants of indexOf and lastIndexOf when applicable

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11416]
See https://github.com/spring-projects/spring-boot/pull/11373#issuecomment-352880873

**Comment by wilkinsona** [comment]
Looks like it would be good to be consistent, but it's not clear which variant (string or char) is better.

**Comment by bclozel** [comment]
I don't think we need to make a definitive choice on that; the easiest one to use on a case by case basis is probably the best choice. The benchmarks we've seen have two important assumptions 1) those statements are in the hot path of the application 2) no additional allocation to call those methods.

So twisting use cases to use one or another might be not useful (this code is not in a hot path) or counter-productive (we might have to cast/allocate stuff to call the "right" variant). So I think we should use whatever variant is the easiest given the `String` or `char` input data. The JVM should do the rest.

**Comment by wilkinsona** [comment]
@bclozel The closure of this issue doesn't match with what I thought we agreed when we discussed it. I thought we'd agreed to use indexOf(char) when we know we're dealing with a single char (for example because it's locally declared and hardcoded), and indexOf(String) in all other cases.

**Comment by snicoll** [comment]
That and don't we need to review all usages and apply that rule? We could use this issue for that.

**Comment by bclozel** [comment]
I guess the underlying rule is "whenever possible, don't use final Strings that are one char long and use char types instead". This might improve memory usage (but not necessarily in JDK9). The rest should follow naturally.

I wanted to close this issue because I thought this was something we'd do in our regular polish commits.

**Comment by GurinderSinghBrar** [comment]
I think that the same idea will need to be applied to the use of lastIndexOf().  I have noticed in the codebase, that the same issues as with indexOf() exist.
