### ISSUE TITLE
ServerProperties.Jetty.Accesslog doesn't need to create a TimeZone

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#11414]
If we cause the `TimeZone` class to be initialized, it has to read a file to look up all the time zones and do some computations on them. The data seem to be unused except for when the server is Jetty, so it seems like a waste. I haven't measured it but I suspect that creating a `TimeZone` instance unnecessarily is not super expensive, but it costs something, so it's probably worth cutting out of our code path if we can.

**Comment by wilkinsona** [comment]
I don't think this change will make any difference. Framework's `DateFormatter` class (which is used by `BinderConversionService`) will have already created a `TimeZone` for its `UTC` constant before `ServerProperties.Jetty.Accesslog` is loaded.
