### ISSUE TITLE
TestRestTemplate does not authorize properly

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-boot#11423]
Junit test:

```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Rollback
@Transactional
@ActiveProfiles("ut")
public class WorkOrderControllerTest {
    @Autowired
    private TestRestTemplate testRestTemplate;

    @Test
    @WithUserDetails(value="Tom", userDetailsServiceBeanName = "customizedUserDetailsService")
    public void testGetworkList() {
        URI uri = URI.create("/workorder/getworkList.html?pageNum=1&pageSize=10&status=all");
        ResponseEntity exchange = testRestTemplate.getForEntity(uri, String.class);
    }
}
```

I thought with `@WithUserDetails`, Tom would login propertly, I can see that customizedUserDetailsService bean correctly returns a SecurityUser. However, logic in the controller 
SecurityContextHolder.getContext().getAuthentication(); returns an "anonymous".

**Comment by snicoll** [comment]
`WithUserDetails` works with mocking context, not integration tests. If you have more questions, please ask them on StackOverflow or join us on Gitter.

**Comment by Jovons** [comment]
Rejected. I totally believe this is a bug! Now I used another method, the same result. object "strategy" is changed between setContext method and getContext. I would like to attach figures to show that strategy in SecurityContextHolder has changed, but GH does not surpport figures.
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
@ContextConfiguration
@WebAppConfiguration
public class XXTest {
    @Autowired
    private WebApplicationContext context;

    protected MockMvc mvc;

    @Before
    public void setup() {
        mvc = MockMvcBuilders.webAppContextSetup(context)
            .apply(SecurityMockMvcConfigurers.springSecurity()) // will perform all of the initial setup we need to integrate Spring Security with Spring MVC test.
            .build();
    }
	
	@Test
    public void testGetworkList() throws Exception {
        List<GrantedAuthority> list = new ArrayList<>();
        GrantedAuthority a = new SimpleGrantedAuthority("DASHBOARD");
        list.add(a);
        String uri = "/workorder/getworkList.html?pageNum=1&pageSize=10&status=all";
        ResultActions perform = mvc.perform(post(uri).with(csrf().asHeader()).with(user("Tom").roles("CP").authorities(list)));
        System.out.println();
    }
}
