### ISSUE TITLE
Kotlin 1.2 support by jackson-module-kotlin in spring boot 1.5.x

### ISSUE THREAD

**Issue by Romster** [spring-projects/spring-boot#11424]
Kotlin 1.2 was released on November 28, but we can't use it with provided versions of libraries.
From  [this topic](https://github.com/FasterXML/jackson-module-kotlin/issues/97 ) we can see that Kotlin 1.2 works fine with jackson-module-kotlin version 2.9.2.
So it would be great if jackson-modules' versions were updated to the latest ones.

**Comment by snicoll** [comment]
Sorry but we can't move to a new minor version of a dependency in a maintenance release. You are of course free to override the property yourself.
