### ISSUE TITLE
CloudFoundry endpoint extensions use EndpointExtension directly

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11428]
`CloudFoundryReactiveHealthEndpointWebExtension` and `CloudFoundryHealthEndpointWebExtension` uses `EndpointExtension` directly while its javadoc clearly states that it is a meta-annotation. 

Both those extensions are clearly web extensions but nothing in their declaration states that. This lead to [a recent polish](https://github.com/spring-projects/spring-boot/pull/11418) where @izeye and I had [an interesting discussion](https://github.com/spring-projects/spring-boot/pull/11418#discussion_r158599967).

**Comment by mbhave** [comment]
Can we have `WebEndpointExtension` expose a `Class<? extends EndpointFilter<WebOperation>>` filter?

**Comment by snicoll** [comment]
@mbhave see  https://github.com/spring-projects/spring-boot/pull/11418#discussion_r158682646 :)

**Comment by mbhave** [comment]
oh I was suggesting exposing the filter on `EndpointWebExtension ` as a `EndpointFilter<WebOperation>` and since it's a `WebOperation`, it wouldn't be able to take in a JMX filter.

**Comment by snicoll** [comment]
I think I'd prefer a `CloudFoundryEndpointWebExtension` annotation and meta-annotate that with what we have now.

**Comment by mbhave** [comment]
I think we did consider that when writing the Cloud Foundry extensions. Going this route will mean that the annotation is tied to the filter and if we need a new filter we need to add a new annotation. But if we don't anticipate any other kind of filtering on web endpoints, it should be fine.

**Comment by philwebb** [comment]
Reopening because I have a different fix as part of the Endoint refactor.
