### ISSUE TITLE
Initializing a reactive repository during initialization hangs.

### ISSUE THREAD

**Issue by martin-drozdik** [spring-projects/spring-boot#11438]
This is a problem related to Spring Boot 2.0.0.M7. When using Spring Boot with Webflux and Reactive Mongo it is not possible to manipulate the database in the initializer of a service. The application hangs.

The problem is described here:

https://stackoverflow.com/questions/47924911/why-does-subscribe-work-and-block-doesnt-in-spring-reactive-mongo

(please, let me know if I should copy the contents instead of link)

I also made a repository that has a fully executable example:

https://github.com/martin-drozdik/spring-mongo-bug-example

The branch `master` exhibits the problem and the branch `lazy` contains a workaround with lazy evaluation.

I will be very happy to provide more details, so don't hesitate to contact me.

**Comment by snicoll** [comment]
Please do not cross post, we can keep the conversation on SO for now and reopen if necessary here (though if it needs to be, I am quite convinced this would be a framework issue).
