### ISSUE TITLE
Annotation inside interface does not inject value

### ISSUE THREAD

**Issue by XPLOT1ON** [spring-projects/spring-boot#11430]
When I annotate inside an interface and then have a class implementing that interface (and annotate that class with `@Component` the value failed to be injected. However, If I move all annotation to the class. Everything works fine. This seems to affect `@PathVariable` `@RequestBody` as far as I know. I am using SpringBoot 1.5.9

 `InventoryController ` Interface
```
@RequestMapping("/inventory")
@RestController
public interface InventoryController {
    class CreateRequestBody {
        private String name;
        // Getter Setter omitter
    }

    @PostMapping
    Inventory create(@RequestBody CreateRequestBody createBody);

    @GetMapping("/{id}")
    Inventory findById(@PathVariable Integer id);
}
```

`InventoryControllerImpl` Controller Class
```
@Component
public class InventoryControllerImpl implements InventoryController {

    @Autowired
    private InventoryService inventoryService;

    @Override
    public Inventory create(CreateRequestBody createBody) {
        return inventoryService.createNewInventory(createBody.getName());
    }

    @Override
    public Inventory findById(Integer id) {
        System.out.println(id);
        return inventoryService.searchInventory(Long.valueOf(id));
    }
}
```

I can recall that this was working on my other spring boot project.

**Comment by bclozel** [comment]
It's currently not supported in Spring Framework - please see [SPR-11055](https://jira.spring.io/browse/SPR-11055).
