### ISSUE TITLE
Add Kafka health indicator

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-boot#11435]
Implement a Kafka health indicator. Something similar to `org.springframework.boot.actuate.amqp.RabbitHealthIndicator`.

**Comment by snicoll** [comment]
Would you mind contributing a PR?

**Comment by Jcamilorada** [comment]
@snicoll I would like to give a try. 

About help monitoring do you think we can use metric [producer metrics](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/core/KafkaTemplate.html#metrics--) or health scenario need to include produce and consume of health message?

**Comment by snicoll** [comment]
@Jcamilorada let's go with something  basic first ("is Kafka up?"). We can refine later. Thanks!

**Comment by snicoll** [comment]
Closing in favour of PR #11515

**Comment by garyrussell** [comment]
BTW, one observation - if the producer is configured to support transactions (`transactionIdPrefix`), the broker will not work if there are less than 3 instances running (maybe more - depending on broker configuration).

I think this would incorrectly report UP.
