### ISSUE TITLE
Supply an opposite annotation to @PriorityOrder

### ISSUE THREAD

**Issue by regevbr** [spring-projects/spring-boot#11442]
`@PriorityOrder` enables you to give order priority between beans regardless of their order value (in case only one of them is annotated with that)
This gives us the ability to make sure our order is always better than beans we have no control over their order value (ones with HIGHEST_PRECEDENCE)
There is a need for an opposite annotation that will give us the ability to make sure our order is always worst than beans we have no control over their order value (ones with default/LOWEST_PRECEDENCE)

The motivation for this feature comes from the following example scenario:
`EnvironmentChangeEvent` causes all `@ConfigurationProperties` to get rebinded (`org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder`) and I have a bean which is in charge of changing some of the properties after they are set. This bean currently listens to `ContextRefreshedEvent` and `EnvironmentChangeEvent` but I can't guarntee that my bean will handle the `EnvironmentChangeEvent` after the properties were changed due to the fact that the `ConfigurationPropertiesRebinder` class has no order and as such gets the LOWEST_PRECEDENCE which I can't override. The annotation I'm proposing here will let me do that.

There is a discussion about that feature in #3599 

This is a simple fix in the code of `org.springframework.core.OrderComparator.doCompare()`

**Comment by regevbr** [comment]
@ezraroi

**Comment by snicoll** [comment]
@regevbr Spring Framework issue are not handled here but [in a dedicated issue tracker](https://jira.spring.io/browse/SPR). Looking at the description, it is likely to be rejected so if I were you, I'd rather report that use case to Spring Cloud to see how the contract there can be improved.
