### ISSUE TITLE
Update maven plugin support  filter file inside dependecy jars, like maven-shade-plugin

### ISSUE THREAD

**Issue by chxiaowu** [spring-projects/spring-boot#11445]
maven-shade-plugin  can filter files inside thirdparty jars.      
it's useful, hope  spring boot maven plugin have this function.

              <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>

**Comment by snicoll** [comment]
It's not the same thing. The shade plugin produces a single jar and filtering is important. The Spring Boot maven plugin repackages existing jar file and should not modify them.

**Comment by ykartal** [comment]
@snicoll 
In our project original jar is 16 MB but repackaged (by spring-boot plugin) jar is 98 MB. All dependent jars are on classpath at production environment. As your teams suggestion, we exclude all jars one by one. Why do not plugin support regex or something like it, or just giving an includeSet.
