### ISSUE TITLE
ZooKeeper health indicator

### ISSUE THREAD

**Issue by vbeskrovnov** [spring-projects/spring-boot#11440]
Enhancement

Hi,
I use spring boot with ZooKeeper and I have to checking it status. I didn't find tools for ZooKeeper, but I found it for many other services in `org.springframework.boot.actuate`. So, what do you think about ZooKeeper health indicator like `org.springframework.boot.actuate.elasticsearch.ElasticsearchHealthIndicator` or others actuators?

**Comment by snicoll** [comment]
`ZooKeeper` is managed in Spring  Cloud. Please request such indicator in the [appropriate project](https://github.com/spring-cloud/spring-cloud-zookeeper)
