### ISSUE TITLE
/prometheus not works due org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation

### ISSUE THREAD

**Issue by nkonev** [spring-projects/spring-boot#11454]
I use Spring Boot 2.0.0.M7.
I call
```
curl -v -H "Accept: text/html" http://127.0.0.1:3010/prometheus
```
or
```
curl -v -H "Accept: text/html" http://127.0.0.1:3010/actuator/prometheus
```

And it responds 406
```
[nik@fedora ~]$ curl -v -H "Accept: text/html" http://127.0.0.1:3010/actuator/prometheus
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3010 (#0)
> GET /actuator/prometheus HTTP/1.1
> Host: 127.0.0.1:3010
> User-Agent: curl/7.51.0
> Accept: text/html
> 
< HTTP/1.1 406 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Set-Cookie: XSRF-TOKEN=5dd2889d-04ec-4661-b610-764fe9f487c2; Path=/
< Content-Length: 0
< Date: Sun, 31 Dec 2017 00:03:43 GMT
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

I catch `HttpMediaTypeNotAcceptableException: Could not find acceptable representation` on ServletInvocableHandlerMethod.java:123

## More explained reproducing
my project https://github.com/nkonev/blog
branch java9
commit 01919cc363df05d2996f6655558995806701c5a2

Start environment(db,  broker)
```
cd docker
docker-compose up -d
```

**Comment by snicoll** [comment]
@nkonev not sure what you expect but that [endpoint is not meant to serve a UI](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints) (prometheus actually does that).

**Comment by nkonev** [comment]
@snicoll 
Prometheus expects that it's exporters responds text/html, not application/json.
I catch error because Spring Boot doesn't have appropriate converter to text/html.

For example - see https://prometheus.io/docs/instrumenting/exposition_formats/
And by default my Spring Boot cannot response(but it generate same loong string, I checked) something like
```
# A histogram, which has a pretty complex representation in the text format:
# HELP http_request_duration_seconds A histogram of the request duration.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{le="0.05"} 24054
http_request_duration_seconds_bucket{le="0.1"} 33444
http_request_duration_seconds_bucket{le="0.2"} 100392
http_request_duration_seconds_bucket{le="0.5"} 129389
http_request_duration_seconds_bucket{le="1"} 133988
http_request_duration_seconds_bucket{le="+Inf"} 144320
http_request_duration_seconds_sum 53423
http_request_duration_seconds_count 144320
```

E. g. java prometheus generates appropriate Prometheus-adopt string, but it fails due there isn't apropriate converter

**Comment by snicoll** [comment]
I am confused. Your link states the following for `text/html`:

> The following three optional text formats are meant for human consumption only and are not understood by Prometheus. Their definition may therefore be somewhat loose. Client libraries may or may not support these formats. Tools should not rely on these formats.

**Comment by nkonev** [comment]
Sorry, I wrong.

It works
```
curl -H "Accept: text/plain" -v http://127.0.0.1:3010/actuator/prometheus
```

and http://127.0.0.1:3010/actuator/prometheus works in my browser
