### ISSUE TITLE
Please add an example for spring boot war which serves jsp views

### ISSUE THREAD

**Issue by jamesclark92** [spring-projects/spring-boot#11453]
An example that combines:

- https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-jsp
- https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-war

**Comment by spencergibb** [comment]
Isn't the jsp example already a war?

**Comment by jamesclark92** [comment]
So it is.
