### ISSUE TITLE
No way to disable/exclude ApplicationContextInitializers

### ISSUE THREAD

**Issue by dusan-eremic** [spring-projects/spring-boot#11457]
I'm trying to run a `@SpringBootTest` in a "clean" context without having `ApplicationContextInitializers` executed. The use case is that I need to use some dependencies but in tests I want to disable execution of all `ApplicationContextInitializers` defined in those dependencies.
The `SomeApplicationContextInitializer` is defined inside a spring.factories file in a compile-scope dependency like this:

```
org.springframework.context.ApplicationContextInitializer=\
com.xyx.someapp.SomeApplicationContextInitializer
```
 **Note**: The dependencies are not within my control, I can't change spring.factories

**Test class:**
```
@SpringBootTest(webEnvironment = RANDOM_PORT)
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = TestContext.class)
public class UsersControllerTest {}
```

**Test config:**
```
@ComponentScan(basePackages = {"com.eremic.myapp"})
@EntityScan("com.eremic.myapp.entity")
@EnableJpaRepositories("com.eremic.myapp.repository")
public class TestContext {}
```

I've already tired with `excludeFilters` `@ComponentScan.Filters`, but it has no effect on `ApplicationContextInitializers`.

So far the only way to prevent `SomeApplicationContextInitializer` from executing inside `@SpringBootTest` is to remove the maven dependency from the classpath in which the `SomeApplicationContextInitializer` is declared.

Is there any other way to exclude `ApplicationContextInitializer`s from `@SpringBootTest`?

**Comment by snicoll** [comment]
@dusan-eremic no you can't do that. The whole point of adding them in `spring.factories` is to ensure they are executed automatically. If that doesn't work for you, perhaps they shouldn't be registered that way (you can register them on the `SpringApplication` directly, in which case they won't be invoked in tests.

Also, please do not that, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow.

**Comment by dusan-eremic** [comment]
@snicoll Thank you for the reply. 

I think this should be enhancements that's why is posted here. 

What about use cases when I do not control a dependency but I have to use it as a part of my project? How I can test a "slice" of my application without having full context executed? 

Why are ApplicationContextInitializers different in that regard from auto-configurations?

**Comment by snicoll** [comment]
> I think this should be an enhancements that's why is posted here.

Before asking  for the enhancement, I'd question why such initializer has to be disabled at all. If it's registered in `spring.factories`, the purpose is to make sure it is always executed. If you find that's not working for you, I'd report that problem to that project you're relying on first.

Also, `ApplicationContextInitializer` is a Spring Framework feature. If you want to pursue this, you can create an issue in its [dedicated issue tracker](https://jira.spring.io/browse/SPR).

**Comment by dusan-eremic** [comment]
@snicoll Thank you for the link, I'll consider posting there too.

I get your point but I still think there should be a way to override that behaviour. I just don't think that is the best approach to get **any** code executed just by including a dependency without having **any** why to control that behaviour by the framework annotations.

**Comment by dusan-eremic** [comment]
Hi @snicoll 

based on @philwebb response here https://stackoverflow.com/a/48389724/2381316
can we reconsider re-opening this issue?

**Comment by philwebb** [comment]
To be clear, what I'm suggesting in the stackoverflow response is a very minimal change to `SpringBootTestContextBootstrapper` that allows you to do this if you want to. It will still involve jumping though some hoops and I don't really want to encourage regular users to do this.
