### ISSUE TITLE
Filenames too long on Windows

### ISSUE THREAD

**Issue by lukaseder** [spring-projects/spring-boot#11465]
When checking out Spring Boot on a windows machine into a path that I don't think is too uncommonly deeply nested:

```
lukas@DESKTOP-M9T2LD4 MINGW64 ~/workspace/dummy
$ pwd
/c/Users/lukas/workspace/dummy

lukas@DESKTOP-M9T2LD4 MINGW64 ~/workspace/dummy
$ git clone https://github.com/lukaseder/spring-boot
```

Then, I get the following errors:

```
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFailsToResolve.gradle (Filename too long)
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-additionalMetadataLocationsConfiguredWhenProcessorIsPresent.gradle (Filename too long)
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-additionalMetadataLocationsNotConfiguredWhenProcessorIsAbsent.gradle (Filename too long)
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-javaCompileTasksCanOverrideDefaultParametersCompilerFlag.gradle (Filename too long)
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-javaCompileTasksUseParametersAndAdditionalCompilerFlags.gradle (Filename too long)
```

I know this is [Spring](https://blog.jooq.org/2014/04/01/spring-api-bingo/) ;-), but perhaps, you could avoid these super long file names?

**Comment by michael-simons** [comment]
Duplicates #10953

**Comment by lukaseder** [comment]
OK, thanks. Will comment there...

**Comment by michael-simons** [comment]
Better see #10868. My bad.

**Comment by lukaseder** [comment]
Yeah, good to see that I'm not the only one running into this :)

**Comment by matohl** [comment]
This is still a problem, almost two years later. I am using latest Windows 10 and Git Bash.

**Comment by wilkinsona** [comment]
@matohl I shouldn't be. Have you followed [this recommendation](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows)?

**Comment by matohl** [comment]
Thanks @wilkinsona,  I did not see the recommendation before, it worked fine.

**Comment by kkolyan** [comment]
> @matohl It shouldn't be. Have you followed [this recommendation](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows)?

link doesn't contain solution anymore. could be found in history: https://github.com/spring-projects/spring-boot/commit/2c770217bbbd077b1caa3b6fea2d2c169e3a2e60

**Comment by wilkinsona** [comment]
Thanks, @kkolyan. It's moved to the wiki: https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code#cloning-the-git-repository-on-windows.
