### ISSUE TITLE
Autoconfigure spring.jooq.sql-dialect if not provided

### ISSUE THREAD

**Issue by lukaseder** [spring-projects/spring-boot#11464]
The spring boot manual specifies that a jOOQ `SQLDialect` needs to be configured:
https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/html/boot-features-sql.html#_customizing_jooq

From my experience supporting jOOQ / Spring Boot users, this often seems to be forgotten, in case of which Spring Boot seems to auto-configure the `SQLDialect.DEFAULT` dialect. That dialect might work for a few queries (because it mimicks SQL standard behaviour), but at some point, it breaks.

I'm not sure if picking `SQLDialect.DEFAULT` is a good idea in the first place. Perhaps, an exception could be raised, making that configuration mandatory from Spring Boot. Or, alternatively, because the data source is probably managed by Spring Boot as well, Spring Boot will know the dialect and can auto-configure it appropriately, if not explicitly specified by the user configuration through `spring.jooq.sql-dialect`. I think this would be really a great improvement for our common users.

Note, there's a mapping between jOOQ `SQLDialect` and Spring dialects available through `SQLDialect.thirdParty().springDbName()`, which references the same names as `org/springframework/jdbc/support/sql-error-codes.xml`

**Comment by michael-simons** [comment]
This will be in 2.0: https://github.com/spring-projects/spring-boot/pull/9355 

Implemented through [SqlDialectLookup](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/SqlDialectLookup.java) and [this properties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqProperties.java#L58).

**Comment by lukaseder** [comment]
Oh, very cool! Thanks for looking this up, @michael-simons !
