### ISSUE TITLE
Documentation of bind package removal?

### ISSUE THREAD

**Issue by rcollette** [spring-projects/spring-boot#11463]
I have a breaking change from 1.5.7.Release to 2.0.0.x where the class PropertySourceUtils is no longer there.  Specifically we are using PropertySourceUtils.getSubProperties.    However, I don't see any commit that removes the file/class nor do I see any 2.0.0.x release documentation that mentions the removal of this package.

**Comment by wilkinsona** [comment]
The code was part of Boot 1.5's relaxed binding support which has been [rewritten and simplified in 2.0](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0). There is no direct equivalent in 2.0 of the method that you were using.

**Comment by snicoll** [comment]
@rcollette there was a section in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#relaxed-binding) that  I just improved with an explicit reference to the page Andy mentioned.

**Comment by bric3** [comment]
If that helps, I replaced this code

```java
        RelaxedPropertyResolver resolver = new RelaxedPropertyResolver(context.getEnvironment());
        Map<String, Object> actualSubProperties = resolver.getSubProperties(name);
```

By binding directly to something like that, depending on the property structure you may need to adapt how the binder is ocnfigured : 

```java
        var subProperties = (Map<String, Map<String, String>>)
            Binder.get(context.getEnvironment())
                  .bind(ConfigurationPropertyName.of(name),
                        Bindable.of(ResolvableType.forClassWithGenerics(
                            Map.class,
                            ResolvableType.forClass(String.class),
                            ResolvableType.forClassWithGenerics(
                                Map.class,
                                String.class,
                                String.class))),
                        new IgnoreErrorsBindHandler())
                  .orElse(Collections.emptyMap());
```
