### ISSUE TITLE
NoClassDefFoundError  when  ManagementWebSecurityAutoConfiguration is enabled without RequestMatcher in classpath 

### ISSUE THREAD

**Issue by rokii** [spring-projects/spring-boot#11474]
Spring boot version : 1.5.8

ManagementWebSecurityAutoConfiguration in spring boot actuator can be enabled by @ConditionalOnClass({ EnableWebSecurity.class }). But this configuration bean has reference to RequestMatcher class.

In my project we have to only include spring security config and core. 
Then ManagementWebSecurityAutoConfiguration is activated but RequestMatcher from spring security web is missing which results in NoClassDefFoundError

**Comment by wilkinsona** [comment]
The problem can be reproduced with the following dependencies:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
