### ISSUE TITLE
Optimistic locking allows ReactiveMongoTemplate to modify immutable objects

### ISSUE THREAD

**Issue by martin-drozdik** [spring-projects/spring-boot#11471]
### Version

Spring Boot **2.0.0.M7** on Ubuntu 17.10 with OpenJDK 1.8

### Steps to reproduce

A minimal working example is here:

https://github.com/martin-drozdik/reactive-mongo-bug-demo

Given an immutable class:

```
data class Person
(
    val id: String,
    @Version val version: Long? = null
)
```

It is nevertheless possible to modify its instances, just by calling `ReactiveMongoTemplate::save`

```
@Component
class PersonHandler(val template: ReactiveMongoTemplate)
{
    fun initialize()
    {
        val jim = Person("Jim")
        require(jim.version == null)

        template.save<Person>(jim).block()
        require(jim.version == null) // This require will fail
        {
            "Immutable object has been modified"
        }
    }
}
```

If this is by design, it could be beneficial to add a warning, or just a simple mention in the documentation. Otherwise I find it counterintuitive that a `save` method could break a fundamental principle of the language.

**Comment by snicoll** [comment]
@martin-drozdik none of this is related to Spring Boot, please create an issue in the [Spring Data MongoDB](https://jira.spring.io/browse/DATAMONGO/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) issue tracker.
