### ISSUE TITLE
Use ApplicationContextRunner consistently

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#11473]
A lot of auto-config tests can be refactored to use the `ApplicationContextRunner`

**Comment by snicoll** [comment]
@mbhave agreed and I upgrade them whenever I work on a PR or a feature. I am not sure that a single issue for this is the right thing (it's a lot of work). Perhaps we should just agree on this rule and upgrade whenever we work on a feature?

**Comment by wilkinsona** [comment]
If we do it as part of touching a test class for another reason, I'd prefer that the migration to using `ApplicationContextRunner` is done in a separate commit.

**Comment by wilkinsona** [comment]
I should add that I'm pretty sure I'm guilty of not separating things in the past and I think that was a mistake.

**Comment by snicoll** [comment]
That's what I meant as well. I usually "polish" before working on the actual feature and then implement the feature with the migrated test

**Comment by mbhave** [comment]
ok, I'll close it and just keep that in mind.
