### ISSUE TITLE
server.ssl.client-auth property is not honoured when using Netty

### ISSUE THREAD

**Issue by gjohal** [spring-projects/spring-boot#11488]
Looks like for NettyReactiveWebServerFactory, SslServerCustomizer is not setting clientAuth in SslContextBuilder and configured server.ssl.client-auth property is not honored.

**Comment by wilkinsona** [comment]
Well spotted. Thank you.

We also seem to be missing tests for SSL with client auth for all three reactive web server factories. I think `AbstractReactiveWebServerFactoryTests` needs equivalents of the following tests from `AbstractServletWebServerFactoryTests`:

- `sslNeedsClientAuthenticationFailsWithoutClientCertificate`
- `sslNeedsClientAuthenticationSucceedsWithClientCertificate`
- `sslWantsClientAuthenticationSucceedsWithClientCertificate`
- `sslWantsClientAuthenticationSucceedsWithoutClientCertificate`
