### ISSUE TITLE
bomProperty does not work as it should in gradle.build files

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-boot#11505]
I have a multi module project and I am using Gradle as build tool, so I  cloned https://github.com/spring-guides/draft-gs-multi-module.git project as starting point.

In the template project the **io.spring.dependency-management** is used in library module and following statement is present in library module build file

```
  dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        }
    }
```
I wanted to upgrade one of the dependencies (Selenium), so I changed the statement to 

```
dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:1.5.9.RELEASE") {
            bomProperty 'selenium.version', '3.8.1'
        }
    }
}
```
but it didn't work.

But when I add `ext['selenium.version']='3.8.1'` to the build script, everything goes fine.

So it seems the `bomProperty` and `bomProperties` statements does not work as it promised.

**Comment by nrundle** [comment]
What was the output?  I cloned the repo just now and made the same change to add the bomProperty and it worked fine for me.

**Comment by wilkinsona** [comment]
It works fine for me too. @pashazadeh if you can reproduce the problem, please open a new issue in the [dependnecy management plugin’s repository](/spring-gradle-plugins/dependency-management-plugin) with a complete, minimal example that reproduces the behaviour you have described.
