### ISSUE TITLE
Spring Boot versions missing from jCenter

### ISSUE THREAD

**Issue by nrundle** [spring-projects/spring-boot#11507]
I have a gradle build that uses dynamic versions for spring-boot dependencies like "1.4.+"
On January 3rd, 2018, the continuous integration builds started failing to resolve spring dependencies, telling me the only versions available were "1.5.8.RELEASE" and "1.5.9.RELEASE"

I did some digging and found that spring-boot seems to be missing several of the older versions on jCenter.

For example, only version 1.5.9.RELEASE is available for spring-boot-parent from [jCenter](http://jcenter.bintray.com/org/springframework/boot/spring-boot-parent/)

And the [maven-metadata.xml](http://jcenter.bintray.com/org/springframework/boot/spring-boot-parent/maven-metadata.xml) file only lists 1.5.8.RELEASE and 1.5.9.RELEASE

However, all versions are available from the [spring-boot repository](https://bintray.com/spring/jars/org.springframework.boot#files/org%2Fspringframework%2Fboot%2Fspring-boot-parent) on bintray and the [maven-metadata.xml](https://bintray.com/spring/jars/download_file?file_path=org%2Fspringframework%2Fboot%2Fspring-boot-parent%2Fmaven-metadata.xml) in that repo lists all of the versions.

I took the opportunity to upgrade to the latest spring-boot release, but this could cause problems for other projects relying on jCenter and older versions of spring-boot.

**Comment by wilkinsona** [comment]
I've raised this with our infrastructure team and they will, I think, need to raise it with JFrog. There's nothing we can do in Spring Boot itself to resolve this problem so I'm going to close this issue. While you're awaiting a fix (and in general given the problems we see with JCenter), I'd recommend using Maven Central.
