### ISSUE TITLE
Consider automating `fly set-pipeline` using the concourse-pipeline-resource

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#11506]
https://github.com/concourse/concourse-pipeline-resource

**Comment by mbhave** [comment]
Reopening this as it might be good to not have to `fly set-pipeline` everytime we change the pipeline.yml

**Comment by mbhave** [comment]
Concourse added support for a `set-pipeline` step as an experimental feature. See discussion [here](https://github.com/concourse/concourse/discussions/5732).

**Comment by bclozel** [comment]
Our build has moved to GitHub actions in the meantime, see #39851
