### ISSUE TITLE
spring boot with spring-data-solr

### ISSUE THREAD

**Issue by JianminWu** [spring-projects/spring-boot#11513]
I use spring-data-solr,My interface extends SolrCrudRepository..but when I debug,I find is not SolrCrudRepository...It's SimpleJPARepository..so I can't add or query from solrServer..

` public interface StudentSolrRepository extends SolrCrudRepository<Student, Long>`

my application.yml

> server:
>   port: 8080
> spring:
>   datasource:
>     driver-class-name: com.mysql.jdbc.Driver
>     url: jdbc:mysql://localhost:3306/student
>     username: root
>     password: admin
>   jpa:
>     hibernate:
>       ddl-auto: update
>     show-sql: true
>   data:
>     solr:
>       host: http://192.168.25.128:8080/solr
my Controller
>  @Autowired
>     private StudentSolrRepository studentSolrRepository;
> 
>     @GetMapping("/querysolr")
>     public Object querySolr() {
>         PageRequest page = new PageRequest(0, 2);
>         Page<Student> students = studentSolrRepository.findAll(page);
>         return students;
>     }

> 
org.springframework.data.jpa.repository.support.SimpleJpaRepository@668156b0

THANKS !!!!

**Comment by wilkinsona** [comment]
@JianminWu To be able to help you, we need some more information. Please provide a complete, minimal example (something we can unzip or git clone) that we can run to reproduce the problem.

**Comment by JianminWu** [comment]
I have solved it. I try new a new modules without spring-data-jpa.. This's work...Maybe they have some clash..I guess.
Thanks a lot! @wilkinsona

**Comment by wilkinsona** [comment]
It should be possible to use Spring Data JPA and Spring Data Solr at the same time. If you provide the sample requested above, we can re-open this and spend some time investigating why that is apparently not working for you.
