### ISSUE TITLE
Incorrect type generated in the metadata with annotated getter

### ISSUE THREAD

**Issue by jearton** [spring-projects/spring-boot#11512]
It will generate the text as following:

```
    {
      "name": "foo",
      "sourceType": "x.y.Bar",
      "type": "(@javax.validation.Valid :: java.util.List<x.y.Biz>)"
    }
```

**Comment by snicoll** [comment]
@jearton sorry I am not following. Are you saying it should generate that? (It doesn't for me). If it does, please share a minimal sample that we can run that shows the problem you are describing.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
@artembilan has provided me [a sample](https://github.com/artembilan/metadata-test). Thanks Artem!

**Comment by snicoll** [comment]
Funnily enough, this is really related to the validation API version 2. It doesn't break with 1.1

**Comment by snicoll** [comment]
That fix doesn't work with Java9 for some reason.

**Comment by snicoll** [comment]
Writing the `toString` ourselves led to a regression with array types. I am feeling a bit nervous about making that change in `1.5.x` now.
