### ISSUE TITLE
Please add human readable version of date for `commit.time` and `build.time`

### ISSUE THREAD

**Issue by Hronom** [spring-projects/spring-boot#11522]
Some times our devs needs human readable version of date for `commit.time` and `build.time` in `/info`.
Can you please add it.

**Comment by snicoll** [comment]
@Hronom changing the phrasing of your question is not going to help you much. Please stop cross-posting and ask your question on StackOverflow. You can also join us on Gitter if you want to chat.

**Comment by Hronom** [comment]
@snicoll Hello please can you stop closing feature request?

**Comment by snicoll** [comment]
This feature is already implemented. All you have to do is configure Jackson to format the date accordingly.
