### ISSUE TITLE
Add 'server.remove-forward-headers' options

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#11525]
Enabling that option should create a `ForwardedHeaderFilter` option and remove Forwarded headers.

This is especially useful if your application is looking at Forwarded headers even though it's not protected by a proxy (adding/removing those headers already).

See Rossen's comment in https://github.com/spring-projects/spring-boot/issues/10900#issuecomment-355346004 for more background about this.

**Comment by rstoyanchev** [comment]
An additional question is whether this property should be set by default. Doing so would cause applications that actually need to use forwarded headers to fail but the cause would be fairly obvious. The benefit is that it leads down a safer path of explicitly opting. Note also that setting the flag by default has the potential and likely will cause regression in applications that currently rely on forwarded headers implicitly, i.e. by virtue of using `MvcUriComponentsBuilder` or `ServletUriComponentsBuilder` to create links.

**Comment by bclozel** [comment]
One thing bothers me, though. If that's really insecure and not obvious, why is that the default in Spring Framework? Shouldn't `ServletUriComponentsBuilder` and `MvcUriComponentsBuilder` be safe by default?

**Comment by rstoyanchev** [comment]
That's just it though, there is no way to toggle this on and off in the Spring Framework. The only option would be to remove the functionality from `UriComponentsBuilder` which we could do but it would require a period of deprecation followed by eventual removal.

**Comment by sangeetha5491** [comment]
Is this still an active issue that needs to be worked on?

**Comment by wilkinsona** [comment]
@sangeetha5491 Yes, although I don't think we know exactly what form that work should take just yet.

**Comment by bclozel** [comment]
Since [SPR-16668](https://jira.spring.io/browse/SPR-16668), Spring applications don't rely on forwaded headers by default. As explained in the [Spring Framework migration docs](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#forwarded-headers), you either need to enable the forwarded headers support at the server level (which is what Spring Boot provides) or configure a `ForwardedHeaderFilter`.

If we provide a `server.remove-forward-headers` that configures a `ForwardedHeaderFilter` to remove all related headers, then we'd have two problems:

1. This might confuse developers using the forwarded headers support at the server level with Spring Boot; I think the server support should operate before the Servlet filter, making that filter a no-op?
2. Removing such headers might not help anymore since nothing consumes them in Spring at that point

With that in mind, I think we should close this issue. If developers need to remove those headers for a specific reason, then creating a `ForwardedHeaderFilter` bean and configuring it is perfectly fine.

**Comment by bclozel** [comment]
The team discussed this issue and we think that this is not useful.
