### ISSUE TITLE
Add support for the Google AppEngine in CloudPlatform

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11531]
`spring-cloud-gcp` currently has an [app engine condition](https://github.com/spring-cloud/spring-cloud-gcp/blob/a896aa16e9eee3f97017ab32baa9f21851a387f1/spring-cloud-gcp-starters/spring-cloud-gcp-starter-core/src/main/java/org/springframework/cloud/gcp/core/AppEngineCondition.java#L36) that we could integrate out of the box in `CloudPlatform`.

**Comment by philwebb** [comment]
Seems sensible to me.

**Comment by meltsufin** [comment]
One complication here is that App Engine does not represent all of Google Cloud Platform. Currently, `CloudPlatform` seems more at the level of a cloud provider, than a specific compute environment within a Cloud. Also, we have to be more specific about the condition. The way it is used in `spring-cloud-gcp` is to detect App Engine Standard. There is also App Engine Flexible, GKE, and GCE. In short, this requires a bit more consideration.

**Comment by snicoll** [comment]
@meltsufin and do you need to detect those in a fine grain manner? If you do, then we're just going to close this one as it doesn't seem a great candidate then.

**Comment by meltsufin** [comment]
Possibly, yes. If you look how the condition is used in `spring-cloud-gcp`, it is just there for the Cloud SQL starter because the JDBC connection URL is slightly different for App Engine Standard, than for the rest of Google Cloud.
I'm OK with closing this one, but a general entry for Google Cloud in `CloudPlatform` makes sense though.

**Comment by snicoll** [comment]
> a general entry for Google Cloud in CloudPlatform makes sense though.

Can you submit a PR for that please?

**Comment by meltsufin** [comment]
On a second thought, I'm not sure if a general entry makes sense either. It's not that trivial. We can easily detect App Engine standard and flexible based on env vars, but for GCE and GKE, I believe we need to use the [Metadata Service](https://cloud.google.com/compute/docs/storing-retrieving-metadata). This would require an HTTP request, which is not in line with the other detection code in this class.
@saturnism @lesv

**Comment by snicoll** [comment]
@meltsufin I ended up with the same conclusion. Let's close this one for now, we can reopen or discuss on a PR. Thanks for the feedback!

**Comment by lesv** [comment]
Configuration on both GAE Std & Flex can be done with EnvVar's as well as the Metadata server.  For GAE Std, EnvVar's are preferred.
