### ISSUE TITLE
ConfigFileApplicationListener problem

### ISSUE THREAD

**Issue by zjzhiqian** [spring-projects/spring-boot#11532]
Enhancement

In previous version, when I specify  command-line argument `spring.config.location`, it also loads the default search location properties such as `classpath:/`, I set some profile non-sensitive properties at the `application.yml` and profile sensitive properties at `application-prod.yml` out of the jar ,the profile sensitive properties using `spring.config.location` argument to load 

in newest version , I saw the source code 
```java
private Set<String> getSearchLocations() {
	if (this.environment.containsProperty(CONFIG_LOCATION_PROPERTY)) {
		return getSearchLocations(CONFIG_LOCATION_PROPERTY);
	}
	Set<String> locations = getSearchLocations(
			CONFIG_ADDITIONAL_LOCATION_PROPERTY);
	locations.addAll(
			asResolvedSet(ConfigFileApplicationListener.this.searchLocations,
					DEFAULT_SEARCH_LOCATIONS));
	return locations;
}
```

it doesn't load the properties from default, it's inconvenient, I have to use comand-line value such as `--spring.config.location=/app/cds,classpath:/`, and someone may be trapped by the difference.

**Comment by philwebb** [comment]
See issue #10595 and commit 8eae37243367ad057b23179c08ea26003dca3c69.

@zjzhiqian I believe that using the new `spring.config.additional-location` property will do what you want. Have you tried that?
