### ISSUE TITLE
ResourceServerTokenServicesConfiguration re-inclusion\migration

### ISSUE THREAD

**Issue by mehmetsalgar** [spring-projects/spring-boot#11577]
Hi,

I was using the class 'org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration' for OAuth2 functionality during Spring 1.5.x actually I migrate it to 2.0.0.M2 also successfully but for one reason this class is removed from 'spring-boot-autoconfigure' at 2.0.0.M5 (I see it in release notes also) but as far as I can tell there is no alternative that is mentioned.

Can you please somehow migrate these auto-configuration somehow again to Spring Boot, manual configuration that I have to do is quite extensive and I want to do this only if I know no migration will take place.

Thx.

**Comment by snicoll** [comment]
Duplicate of https://github.com/spring-projects/spring-security-oauth/issues/1240
