### ISSUE TITLE
Update RouterFunction docs to reflect the way they're looked up

### ISSUE THREAD

**Issue by JWThewes** [spring-projects/spring-boot#11576]
I'm building a larger application using RouterFunctions. What I noticed relative quickly after starting is that I built a configuration class which is depended from nearly all the services in my application. This is definitely something we all want to avoid.
So I reached out to Stéphane Nicoll & Phil Webb and was told that I can easily split the RouterFunctions into several BeanDefinitions and they will be reconciliated for me during startup. (https://twitter.com/snicoll/status/950636452232167425)

This should be reflected in the docs so people don't start building massive Configuration Classes which depend on nearly everything.

**Comment by snicoll** [comment]
I've also review the core Spring Framework documentation and I think we should improve the Java configuration section. I've raised [SPR-16360](https://jira.spring.io/browse/SPR-16360)
