### ISSUE TITLE
Start BackgroundPreinitializer earlier

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11570]
We can actually start the `BackgroundPreinitializer` earlier than the current `EnvironmentPreparedEvent`.

**Comment by Knight219** [comment]
Looks that this enchancement broke some functionality. BackgroundPreinitializer runs early then application.properties is read which cause beans like MappingJackson2HttpMessageConverter ignores configurations (serialization/deserilization features)
