### ISSUE TITLE
Upgrade to micrometer 1.0.0-rc8

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11575]

**Comment by snicoll** [comment]
I've tried to upgrade to the latest snapshot but three tests are failing: 

`WebMvcFilterTests#timeMethod` and `WebMbvFilterTests#badClientRequest` are failing because Prometheus is not happy when we add an additional tag to a metric:

```
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [exception, method, status, uri]. The meter you are attempting to register has keys [exception, method, public, status, uri].

	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:356)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:343)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:158)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:153)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:639)
```

`DataDogPropertiesConfigAdapterTests#apiKeyInferUri` does not seem to pass the apikey anymore

```

java.lang.AssertionError: 
Expecting:
 <"https://app.datadoghq.com">
to contain:
 <"?api_key=my-key"> 
```

**Comment by jkschneider** [comment]
The first issue is described here https://github.com/micrometer-metrics/micrometer/issues/266

**Comment by jkschneider** [comment]
All this and more has been addressed in https://github.com/spring-projects/spring-boot/pull/11598. This can be closed.

**Comment by snicoll** [comment]
@jkschneider this issue is here to track the update to 1.0.0.

**Comment by srinivasvsk** [comment]
Just an fyi, i'm having errors with m7 and the latest rc7 of micrometer

https://github.com/micrometer-metrics/micrometer/issues/344

**Comment by jkschneider** [comment]
> Just an fyi, i'm having errors with m7 and the latest rc7 of micrometer

This is addressed in the latest Boot snapshot. Because `JmxMeterRegistry`'s signature changed, you won't be able to use Micrometer 1.0.0-rc.7 with Boot 2 M7.

**Comment by srinivasvsk** [comment]
ok sounds good, thanks
