### ISSUE TITLE
Create util to perform generic aware callbacks

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11584]
We have quite a few calls now that use generically typed listeners of the form:

```java
public interface SomeListener<T> {

    call(T arg);

}
```

The pattern to filter the listeners based on a resolvable type, make the call and deal with possible Lamda issues could be extracted.

Search the codebase for "Possibly a lambda-defined" to find the existing occurrences.

**Comment by snicoll** [comment]
That could be a core util in the framework.

**Comment by spencergibb** [comment]
Looks similar to https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html

**Comment by philwebb** [comment]
@spencergibb It would be more involved I think. I'd like to cut out the generic resolution and lambda `try..catch` dance that we keep repeating. See [this code](https://github.com/spring-projects/spring-boot/blob/d3c34ee3d1bfd3db4a98678c524e145ef9bca51c/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/transaction/TransactionManagerCustomizers.java#L47-L75) for an example.

**Comment by spencergibb** [comment]
:+1:

**Comment by philwebb** [comment]
One bonus of the extra tests is it seems to have found a problem when running on JDK 9. I think framework also has the same issue so I've raised [SPR-16435](https://jira.spring.io/browse/SPR-16435)
