### ISSUE TITLE
Enum configuration properties are converted to String when Spring Cloud on the path

### ISSUE THREAD

**Issue by sedooe** [spring-projects/spring-boot#11586]
Spring Boot version: 2.0.0.M7
Spring Cloud version: Finchley.M5

While playing with actuator's trace endpoint, I've noticed that `Include` options are ignored and even default ones aren't traced if `management.trace.include` explicitly set and Spring Cloud dependency  is used. (`spring-cloud-starter-sleuth` in my case)

Here is the [sample app](https://github.com/sedooe/spring-property-issue).
Navigate to `localhost:8080/actuator/trace`, make a few request and you'll see that request headers and response headers are not traced as expected.
Now, comment out the `spring-cloud-starter-sleuth` dependency, you'll start to see headers are traced.

If I'm not wrong this happens because of `ConfigurationPropertiesRebinder`. When properties rebinded, they somehow(?) converted into `String` and since they're not `Include` anymore, [this method](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/WebRequestTraceFilter.java#L258) always returns false thus none of the options put into trace map.

**Comment by snicoll** [comment]
As you've clearly found out yourself that Spring Cloud is somehow involved with this, please report that against the [Spring Cloud project](https://github.com/spring-cloud/spring-cloud-commons/). We can reopen here if some actions are required in Spring Boot.
