### ISSUE TITLE
Consider reviewing EndpointFilter

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11581]
At the moment `EndpointFilter` takes an `EndpointInfo` and a `EndpointDiscoverer`. The latter is odd as discovering the endpoints (again?) as part of the filtering shouldn't add a lot of value on the filtering of a particular item.

In practice, this argument is used to check the implementation type of the discoverer as way to identify the "nature" of the search:

```
class WebEndpointFilter implements EndpointFilter<WebOperation> {

	@Override
	public boolean match(EndpointInfo<WebOperation> info,
			EndpointDiscoverer<WebOperation> discoverer) {
		return (discoverer instanceof WebAnnotationEndpointDiscoverer);
	}

}
```

Rather than passing an object which seems unrelated, perhaps we could pass a "Scope" object of some kind that implementations can use to restrict themselves. The scope might be as magic as the `EndpointDiscoverer` though.
  
This is a bit related to #10257 as we might be interested by all "Web" endpoints regardless to the fact they are "regular" web endpoints or "custom" web endpoints. The discoverer won't be the same in that case.

**Comment by philwebb** [comment]
Perhaps just `Class<? extends EndpointDiscoverer>` would be enough of a signal that it's only the discoverer type that's of interest. Extracting both to a context would perhaps be even better.
