### ISSUE TITLE
Move "server.session.*" properties to "server.servlet.session"

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#11589]
`server.session.*` configuration properties seem to be tied to the Servlet specification. Spring WebFlux does support session management and most keys could be applied there, but that support really comes from WebFlux itself.

So two choices here:
* we keep `server.session.*` and apply to WebFlux as much as we can, even if the behavior in WebFlux will not necessarily follow the Servlet standard
* move `server.session.*` to `server.servlet.session.*` and optionally add a different set of keys in the WebFlux namespace.

**Comment by wilkinsona** [comment]
My gut feel is that there's sufficient divergence to warrant `server.servlet.session.*`. This is also somewhat related to #10699. I've started working on that in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-10699). Part of that work has moved `ServerProperties.Session` into the `spring-boot` module where I've currently got it in the `org.springframework.boot.web.servlet.server` package.
