### ISSUE TITLE
Gradle multi-project build dependencies of subprojects cannot be resolved

### ISSUE THREAD

**Issue by aemaem** [spring-projects/spring-boot#11594]
### Summary
When building a Gradle multi-project with Spring Boot 2.0.0.M7 the project cannot resolve the dependency of another project in the same root project.

### Sample
https://github.com/aemaem/spring-boot-gradle-multi-project
Branches:
- master --> Spring Boot 2.0.0.M7
- boot-1.5.9 --> Spring Boot 1.5.9.RELEASE

### Background
When running `./gradlew clean build` in the sample project the dependency of the demo-api project cannot be resolved. If the same configuration is configured with Spring Boot 1.5.9.REALEASE then the build works as expected.

#### Gradle Output
```
> Task :demo-app:compileJava
/home/mmair/Downloads/demo/demo-app/src/main/java/com/example/demo/DemoApplication.java:3: error: package com.example.demo.api does not exist
import com.example.demo.api.FooApi;
                           ^
/home/mmair/Downloads/demo/demo-app/src/main/java/com/example/demo/DemoApplication.java:13: error: cannot find symbol
        private FooApi foo;
                ^
  symbol:   class FooApi
  location: class DemoApplication
/home/mmair/Downloads/demo/demo-app/src/main/java/com/example/demo/FooService.java:3: error: package com.example.demo.api does not exist
import com.example.demo.api.FooApi;
                           ^
/home/mmair/Downloads/demo/demo-app/src/main/java/com/example/demo/FooService.java:7: error: cannot find symbol
public class FooService implements FooApi {
                                   ^
  symbol: class FooApi
/home/mmair/Downloads/demo/demo-app/src/main/java/com/example/demo/FooService.java:9: error: method does not override or implement a method from a supertype
    @Override
    ^
5 errors

FAILURE: Build failed with an exception.
```

#### Project structure is as follows:
```
demo
├── build.gradle
├── demo-api
│   ├── build.gradle
│   └── src
│       └── main
│           └── java
│               └── com
│                   └── example
│                       └── demo
│                           └── api
│                               └── FooApi.java
├── demo-app
│   ├── build.gradle
│   └── src
│       └── main
│           ├── java
│           │   └── com
│           │       └── example
│           │           └── demo
│           │               ├── DemoApplication.java
│           │               └── FooService.java
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
└── settings.gradle
```

**Comment by wilkinsona** [comment]
`demo-api` isn't a Spring Boot application so it should not really have the Spring Boot plugin applied to it. 

Having the Spring Boot plugin applied causes a problem as it is disabling `demo-api`'s `jar` task, the output of which is what `compile project(":demo-api")` adds to the classpath. You can resolve the problem by either only applying the Spring Boot plugin to projects that are Spring Boot applications or by enabling the `jar` task in the `demo-api` project.

> If the same configuration is configured with Spring Boot 1.5.9.REALEASE then the build works as expected.

Your configuration in your `boot-1.5.9` branch isn't the equivalent of the configuration in your `master` branch. Enabling and disabling `bootRepackage` isn't the same as enabling and disabling the `bootJar` task. As explained above you also need to re-enable the `jar` task. That said, narrowing down the projects to which you apply the Spring Boot plugin is the recommended approach, and one that will work in Boot 1.5 and 2.0.

Here's a diff for your `master` branch that illustrates how to only apply the Spring Boot plugin to the project that needs it. It also shows how to use Boot's dependency management in other projects (https://github.com/spring-projects/spring-boot/issues/11059).

```diff
diff --git a/build.gradle b/build.gradle
index 54e7f15..86ae66e 100644
--- a/build.gradle
+++ b/build.gradle
@@ -14,7 +14,6 @@ buildscript {

 subprojects {
        apply plugin: "java"
-       apply plugin: "org.springframework.boot"
        apply plugin: "io.spring.dependency-management"

        repositories {
@@ -23,6 +22,12 @@ subprojects {
                maven { url "https://repo.spring.io/milestone" }
        }

+       dependencyManagement {
+               imports {
+                       mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
+               }
+       }
+
        dependencies {
                compile "org.springframework.boot:spring-boot-starter"
                compile "org.springframework.boot:spring-boot-starter-actuator"
@@ -33,6 +38,4 @@ subprojects {

        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
-
-       bootJar.enabled = false
 }
\ No newline at end of file
diff --git a/demo-app/build.gradle b/demo-app/build.gradle
index 776bcdb..1e89e6f 100644
--- a/demo-app/build.gradle
+++ b/demo-app/build.gradle
@@ -1,5 +1,4 @@
-springBoot.mainClassName = "com.example.demo.app.DemoApplication"
-bootJar.enabled = true
+apply plugin: 'org.springframework.boot'

 dependencies {
     compile project(":demo-api")
```
