### ISSUE TITLE
AbstractHealthIndicator health marked final

### ISSUE THREAD

**Issue by acorcoran-daon** [spring-projects/spring-boot#11592]
Hi,

I am using spring boot actuator to rewrite health check functionality with in an existing product.

The existing product has the status: OK, WARN, ERROR...

I am unable to set custom values for UP / DOWN etc.

For custom health checks I extended Health.builder and overridden up, down etc to set a status of OK, ERROR etc as appropriate.

I would like to be able to extend existing Health Indicators such as DatasourceHealthIndicator so that I can use my own custom Health.Builder but without having to change any of the logic of the specific implementation of the AbstractHealthIndicator.

The issue I have is that the the health method is marked final:

```
	@Override
	public final Health health() 


```
leaving this method as not final leaves more flexibility for anyone who wants to customize health behavior.

**Comment by snicoll** [comment]
I don't think that extending our health indicator is the right approach to the problem. If I understand the problem, you want to translate the `UP` status to `OK`, the `DOWN` status to `ERROR`, etc. 

I find it odd that you are willing to comply with the JSON format of the `health` endpoint but you can't comply with the value of the status. Regardless, you can easily map `Health` to an object of your choice, with the format of your choice in a custom actuator endpoint.

How does that sound?

**Comment by acorcoran-daon** [comment]
@snicoll spring boot already caters for custom error codes: e.g.
management.health.status.order=ERROR, DOWN, OUT_OF_SERVICE, WARN, OK, UP

So for anyone who is using custom codes this supported by the 'aggregator', however one is unable to specify a code for the concept of UP, DOWN, OUT_OF_SERVICE etc ..

I will investigate the custom actuator endpoint, however simply removing the final from this method would provide a quick solution. Is there a reason this method is marked final?

**Comment by snicoll** [comment]
I got that @acorcoran-daon and I believe I've explained why I think the approach you are describing is the wrong one.

I still don't get why you can accommodate with the json format but not with the individual status value of the indicators (IMO if you are OK to parse our JSON format, then you should also be able to translate the status to whatever you like). 

> However simply removing the final from this method would provide a quick solution.
I don't believe that what you're trying to do is the right approach to the problem and you didn't give me any indication to change my mind.

**Comment by acorcoran-daon** [comment]
@snicoll the parsing is out of my control, its another system that is performing the parsing. It ignores everything but the status, just got lucky in how it parses ...

I will look into another actuator endpoint... happy to close for the moment in that case.
