### ISSUE TITLE
application.properties mismatch for deployed application

### ISSUE THREAD

**Issue by dusica23** [spring-projects/spring-boot#11603]
Spring boot version: 1.5.8.RELEASE
Apache Tomcat version: 9.0.1
Maven version: 3.3.9
Java version: 1.8.0_152

Steps to reproduce:
1. Create simple project with application.properties(on src/main/resources location)
2. Add property test.prop=InternalTestProperty
3. Load value using @Value annotation
4. Use thread which infinitely printout loaded value from step 3.
5. Deploy application as war to tomcat server and run it
Result: InternalTestPropery will be printed(which is okay)

6. Configure external application properties location as follows:
    6.1. Create application.properies in some location "/path/to/the/external/configuration"
    6.2. In created application.properties add property test.prop=ExternalTestProperty
    6.3. add next environment entry in tomcat web.xml
       <env-entry>
	  <env-entry-name>EXTERNAL_APPLICATION_PROPERTIES</env-entry-name>
	  <env-entry-value>/path/to/the/external/configuration/application.properties</env-entry-value>
	  <env-entry-type>java.lang.String</env-entry-type>
	</env-entry>
   6.4. In class which extends SpringBootServletInitializer, in "configure" method load external properties using JNDI (ie.
                                Context initCtx = new InitialContext();
				Context envCtx = (Context) initCtx.lookup("java:comp/env"); //$NON-NLS-1$
				applicationPropertiesFile = (String) envCtx.lookup("EXTERNAL_PROP");
)

7. Delete internal application property from src/main/resources location
8. Deploy new war in tomcat server (before this step, as precaution, I've deleted manually deployed application from step 5. and deleted target folder from application before running "mvn clean install" command)
9. Run newly deployed application
Result: thread is randomly printing out "InternalTestProp" and "ExternalTestProp".

Please, I'll appreciate any feedback about bug fix or any workaround for this problem, since publishing my application date is so near.
Do not hesitate to ask for more information.
Thanks in advance

**Comment by wilkinsona** [comment]
Can you please provide a complete sample (a zip or a git repository) that builds the application you have described? Without it, it will be very difficult for us to be sure that we're reproducing the problem that you are describing.

**Comment by dusica23** [comment]
Sorry,  but I can not upload application zip, since I'm not the owner(my company is and any code sharing is not allowed). I can provide You any needed information, but It looks like other components and configurations in the application does not influence this problem... This what I reported should be enough to reproduce. If there are obscure steps, tell me so I can post issue update.

**Comment by wilkinsona** [comment]
We don’t need your actual application, just a minimal sample that reproduces the behaviour you have described. That should include your Tomcat configuration changes, etc.

**Comment by dusica23** [comment]
Okay, I'll provide it as soon as possible. Thanks

**Comment by dusica23** [comment]
Hi, here is the sample(fdbcIssueProject.zip) and log file, changed tomcat config (springBootIssueFiles.zip). In this sample, log is different than I described(for this sample app first values were "Internal property definition" then "External property definition"; In my app values were printed out intermittently after all Spring boot log). I'll hope this can help, and I'm sorry if actually I've made some mistake.
Best regards,
Dusica
[springBootIssueFiles.zip](https://github.com/spring-projects/spring-boot/files/1642125/springBootIssueFiles.zip)
[fdbcIssueProject.zip](https://github.com/spring-projects/spring-boot/files/1642126/fdbcIssueProject.zip)

**Comment by wilkinsona** [comment]
The bug is in your app. The threads that you are starting aren't being stopped as part of the application being undeployed. As a result, they keep running using the values from the old deployment. You also get two threads from the new deployment outputting the new values.

Tomcat outputs two warnings indicating that threads have been leaked:

```
18-Jan-2018 14:18:09.205 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [First thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
 java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
 java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
 java.util.concurrent.Semaphore.acquire(Semaphore.java:467)
 org.issue.opened.worker.Worker.doWork(Worker.java:28)
 org.issue.opened.worker.Worker.lambda$new$0(Worker.java:17)
 org.issue.opened.worker.Worker$$Lambda$18/666363491.run(Unknown Source)
 java.lang.Thread.run(Thread.java:748)
18-Jan-2018 14:18:09.206 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Second thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 org.issue.opened.worker.Worker.doWork(Worker.java:31)
 org.issue.opened.worker.Worker.lambda$new$1(Worker.java:19)
 org.issue.opened.worker.Worker$$Lambda$19/1596642261.run(Unknown Source)
 java.lang.Thread.run(Thread.java:748)
```

**Comment by dusica23** [comment]
Thanks a lot for Your reply.
Best wishes.
