### ISSUE TITLE
Custom ConstraintValidator is called before @PreAuthorize user role check

### ISSUE THREAD

**Issue by atosahatos** [spring-projects/spring-boot#11610]
Hello Spring Boot Team,

**Custom ConstraintValidator code is executed before '@PreAuthorize' security check.**

I originally asked this as a question on SO: https://stackoverflow.com/questions/43740064/custom-constraintvalidator-is-called-even-if-user-role-not-listed-in-preauthori
but did not get any answer.

It occurs with Spring Boot 1.4.6.RELEASE and 1.5.9.RELEASE as well. (Haven't tried 1.4.7.RELEASE).

I would expect that security related checks (like user role) are executed before request body validation.
If this is the intended behavior can you please give explanation to understand?

**Comment by wilkinsona** [comment]
Duplicate of #10157.
