### ISSUE TITLE
spring-boot-configuration-processor - Missing documentation on groups

### ISSUE THREAD

**Issue by neonailol** [spring-projects/spring-boot#11616]
When generating metadata `spring-boot-configuration-processor` does not process description for top level configuration classes annotated as `@ConfigurationProperties`, thres the code

https://github.com/spring-projects/spring-boot/blob/8aaf95b792582df452330b56f78fa9c674283491/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/main/java/org/springframework/boot/configurationprocessor/ConfigurationMetadataAnnotationProcessor.java#L230-L235

it's perfectly legal to request javaDoc here, and store it in the description of the group

```java
 private void processAnnotatedTypeElement(String prefix, TypeElement element) { 
 	String type = this.typeUtils.getQualifiedName(element); 
        String description = this.typeUtils.getJavaDoc(element)
 	this.metadataCollector.add(ItemMetadata.newGroup(prefix, type, type, null, description)); 
 	processTypeElement(prefix, element, null); 
 }

**Comment by neonailol** [comment]
@snicoll In my case, i am processing the output `spring-configuration-metadata.json` to generate documentation for devops, and publish it on internal resource

for this is generic example of configuration

```java
/**
 * Configuration on internal scheduler
 */
@Data
@Component
@ConfigurationProperties("scheduler")
public class SchedulerProps {

    /**
     * Should we run operation on application start
     */
    private boolean runOnStartup;
}
```

i expect this kind of output

```json
{
  "hints": [],
  "groups": [
    {
      "sourceType": "xyz.SchedulerProps",
      "name": "scheduler",
      "type": "xyz.SchedulerProps",
      "description": "Configuration on internal scheduler"
    },
  ],
"properties": [
    {
      "sourceType": "xyz.SchedulerProps",
      "name": "run-on-startup",
      "type": "java.lang.Boolean",
      "description": "Should we run operation on application start"
    }
  ]
}
```

to generate markdown documentation, like this one

### scheduler - Configuration on internal scheduler
Property | Type | Description | Default
------------ | ------------- | ------------ | -------------
| scheduler.run-on-startup| Boolean | Should we run operation on application start | true

and last part to achieving this is getting JavaDoc of top level class `SchedulerProps`

**Comment by snicoll** [comment]
> and last part to achieving this is getting JavaDoc of top level class SchedulerProps

I don't think that's a good idea. The description of the group is _not_ the Javadoc of the top level class. You might be ready to make that sacrifice but we can't make that call in such a broad manner.

You can always complete metadata with manual entries. If you add a `src/main/resources/META-INF/additional-spring-configuration-metadata.json` with the following content, you'll get the expected result:

```json
{
  "groups": [
    {
      "name": "scheduler",
      "description": "Configuration of internal scheduler."
    }
  ]
}
```

**Comment by PeterWippermann** [comment]
> I don't think that's a good idea. The description of the group is not the Javadoc of the top level class.

@snicoll , I think your argument also might be a little too broad here. JavaDoc on a class annotated with `@ConfigurationProperties` is a great place to describe that root group. I don't see any conflicts here.

I stumbled upon this issue here because I'm looking for a way to describe sub-level groups. For that use case I'd like to propose describing these nested groups at the member field of the root group:
```java
/**
 * Description for the root group
 */
@ConfigurationProperties("scheduler")
public class RootProps {

    /**
     * Description for the nested group
     */
    private NestedProps startup;

    public class NestedProps {
    
        /**
         * Description for property
         */
        private boolean runOnStartup;
    }
}
```

**Comment by snicoll** [comment]
Thanks for the feedback but I do think there is a conflict as I’ve already explained. The documentation has some serious limitations that are acceptable on field javadoc as this is unusual to document private fields. Things are quite different for a public class and we don’t want to be in a situation to force users not to use javadoc tags for their public class documentation. 

In insight, the description of a group should probably not have been added. None of the clients I am aware is using that field.
