### ISSUE TITLE
Boot app fails to start when `summary` method is called on `io.micrometer.core.instrument.MeterRegistry`

### ISSUE THREAD

**Issue by tygern** [spring-projects/spring-boot#11617]
In this [sample application](https://github.com/tygern/actuator-issue) the call to [`io.micrometer.core.instrument.MeterRegistry.summary`](https://github.com/tygern/actuator-issue/blob/master/src/main/java/com/tygern/actuatorissue/Controller.java#L18) throws the following error:

```
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/AtomicDouble
```

See the full stacktrace in the attached [output.txt](https://github.com/spring-projects/spring-boot/files/1626901/output.txt) file.

To reproduce, clone the sample application repository and run `./gradlew bootRun` in the project root directory.

This runtime error is not thrown if there is a a runtime dependency on a Micrometer Registry (such as `io.micrometer:micrometer-registry-prometheus`). To see this, uncomment the [`micrometer-registry-prometheus` dependency](https://github.com/tygern/actuator-issue/blob/master/build.gradle#L31) in the sample project and run `./gradlew bootRun`. The application will start successfully and work as expected.

**Comment by wilkinsona** [comment]
This is caused by a bug in Micrometer that has [already been fixed](https://github.com/micrometer-metrics/micrometer/commit/9211b825f113b84e9ff9ab62550510f0f1cdf846#diff-e1b41568aa917192026d5b6cd52130f8).
