### ISSUE TITLE
Spring Data Rest's Repository Detection Strategy is Limited for Framework/Library builders

### ISSUE THREAD

**Issue by mpereira-dev** [spring-projects/spring-boot#11620]
As a framework developer I would like more fine grained control over the repositories that are exported. If I have repositories in module A and different repos in module B which depends on A then it is challenging to not also export module A's repositories in module B. I've found a hacky workaround with the current detection strategy mechanism but would prefer a white list / black list / regex match / custom detection strategy similar to what is available for ComponentScan / SpringBootApplication.

I would also like the ability to disable repository exporting all together without completely disabling the auto configuration in order to leverage Spring Data Rest to manually wire my own self describing API and take advantage of the IDE tooling.

Thanks

**Comment by olivergierke** [comment]
I guess that's more of a Spring Data REST question but you should be able to declare a `RepositoryRestConfigurerAdapter` and in `configureRepositoryRestConfiguration(…)`call `RepositoryRestConfiguration.setRepositoryDetectionStrategy(…)` to e.g. `ANNOTATED`. With that, only repositories annotated with `@RepositoryRestResource` are exposed by Spring Data REST.

Do you need more control over the default exposure? You also might wanna checkout [this ticket](https://jira.spring.io/browse/DATAREST-1176) which might be related.

**Comment by snicoll** [comment]
> I guess that's more of a Spring Data REST question

Thanks @olivergierke, I agree. Let's follow up on that issue and we can reopen if there is something   needs to be done here.

**Comment by mpereira-dev** [comment]
Thanks for the feed back, will look at the linked issue.
