### ISSUE TITLE
WebTestClient - unable to verify whether response header is missing as expected

### ISSUE THREAD

**Issue by mszarlinski** [spring-projects/spring-boot#11629]
Hi, I would like to verify whether response header is missing using `WebTestClient`, but apparently `HeaderAssertions` has no suitable method for that.

It would be nice to enhance `HeaderAssertions` API adding `doesNotContain(headerName)` method.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but `WebTestClient` is provided by Spring Framework. It’s issues are tracked in [JIRA](https://jira.spring.io/browse/SPR).

**Comment by mszarlinski** [comment]
Thanks for answer, how can I post an issue - should I create account or something? I would like to contribute.

**Comment by bclozel** [comment]
Already taken care of in https://jira.spring.io/browse/SPR-16285
