### ISSUE TITLE
Separate versionManagement from the Spring Boot Gradle plugin

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#1163]
Currently, in order to use the `versionManagement` behavior in Gradle, you [must apply](http://docs.spring.io/platform/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-using-spring-io-platform-gradle) the `spring-boot` plugin.  This is problematic because there are cases where `versionManagement` is useful for non-Spring Boot projects.

For example, in the [Java Test Applications](https://github.com/cloudfoundry/java-test-applications) we use a number of dependencies that would be covered by the Platform but I'm being forced to [define their versions manually](https://github.com/cloudfoundry/java-test-applications/blob/master/build.gradle) because the top-level project isn't a Spring Boot JAR/WAR.

I'd like it if the `versionManagement` behavior was separated into a second Gradle plugin (which can continue to be owned by Spring Boot), and then automatically included any time that the Spring Boot plugin is used.  This would allow me to use it without building a Spring Boot application, but the change would be completely seamless to existing users.

**Comment by wilkinsona** [comment]
This has been addressed in 1.3 by 2c3c62d71cee9d98d4b544af6e3b188e6173fbc8 (gh-2133) which replaced `versionManagement` with a separate dependency management plugin.
