### ISSUE TITLE
Spring boot starter web M7 pom hibernate validator wrong group id 

### ISSUE THREAD

**Issue by eltonyuen** [spring-projects/spring-boot#11631]
Depenency hibernate-validator`s group id in Spring boot starter web M7 pom currently is org.hibernate.validator , which should be modified to org.hibernate
[pom file link](https://github.com/spring-projects/spring-boot/blob/d3c34ee3d1bfd3db4a98678c524e145ef9bca51c/spring-boot-project/spring-boot-starters/spring-boot-starter-validation/pom.xml)

**Comment by eltonyuen** [comment]
hibernate-validator maven repository:
[version before 6.0.0](https://mvnrepository.com/artifact/org.hibernate/hibernate-validator)
[version after 6.0.0](https://mvnrepository.com/artifact/org.hibernate.validator/hibernate-validator)

**Comment by wilkinsona** [comment]
As your links show, it moved to `org.hibernate.validator` as part of the new major (6.0) version.
