### ISSUE TITLE
YAML Configuration Properties - Mulitline Strings

### ISSUE THREAD

**Issue by neoXfire** [spring-projects/spring-boot#11645]
Hi,

Are there plans to add support for block scalar multiline Strings as described [there](http://yaml-multiline.info/) and [there](http://yaml.org/spec/1.2/spec.html#id2793652) ?

Multiline strings look nicer than appending `\` character on each line for long strings stored into YAML configuration files (example: a complex SQL query template).
`\` character makes copy/pasting more complex for debugging.

Thanks in advance.

**Comment by wilkinsona** [comment]
AFAIK, multiline strings are already supported by SnakeYAML, the YAML library that Spring Boot uses. If you can't get them to work, please ask on StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
