### ISSUE TITLE
Log failed health checks from the HealthEndpoint

### ISSUE THREAD

**Issue by ezraroi** [spring-projects/spring-boot#11656]
It will be great to log to the logger all failed health checks every time the health endpoint is being called.
In our system, we get alerts on unhealthy services, but if we don't check the  health endpoint immediately, it is impossible to know the reason.

**Comment by snicoll** [comment]
@ezraroi there is a `WARN` log for every indicator since `1.5.4.RELEASE` (#9110), we have no intention to raise that to `ERROR`.
