### ISSUE TITLE
Unauthorized response with XMLHttpRequest header

### ISSUE THREAD

**Issue by rublin** [spring-projects/spring-boot#11651]
I use Spring Boot with Spring Security basic authentication. When i send request with wrong password, i'll receive normal error message in body:

```
{
    "timestamp": "2018-01-15T11:59:31.837+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/karbonator/api/v1/wallet"
}
```

![without_header](https://user-images.githubusercontent.com/19469828/35031117-5609bc44-fb6a-11e7-89f8-37423b4b594d.png)

But when i add additional header **X-Requested-With: XMLHttpRequest** to the request, i'll receive only status 401 and no body.

![with_header](https://user-images.githubusercontent.com/19469828/35031116-55e342f8-fb6a-11e7-8f97-fdfd303f631d.png)

Code sample is here: https://github.com/rublin/XMLHttpRequest

**Comment by bclozel** [comment]
I believe this is the expected behavior in Spring Security.
See spring-projects/spring-security#3887.
Please create a Spring Security issue if you think this is a bug.

Thanks!

**Comment by rublin** [comment]
Yep, i think so too. Created an issue in **Spring security** project .

**Comment by bclozel** [comment]
See spring-projects/spring-security#4968

**Comment by wilkinsona** [comment]
I've dug into this a bit more.

Without the `X-Requested-With: XMLHttpRequest` header, `DelegatingAuthenticationEntryPoint` doesn't find a matching entry point so it falls back to the default. This is `BasicAuthenticationEntryPoint.commence`. It calls `sendError` on the `HttpServletResponse`. This then results in the response being forwarded to Boot's custom error page that produces the expected JSON response body.

When the `X-Requested-With: XMLHttpRequest` header is sent, `DelegatingAuthenticationEntryPoint` finds a matching `HttpStatusEntryPoint`. It calls `response.setStatus` and, as it's not considered to be an error, an empty 401 response is returned.

This behaviour is out of Spring Boot's control so I am going to close this in favour of the Spring Security issue.
