### ISSUE TITLE
Support Kotlin 1.2.20

### ISSUE THREAD

**Issue by shenliuyang** [spring-projects/spring-boot#11663]
<code>
java.lang.NoClassDefFoundError: kotlin/reflect/jvm/internal/impl/load/kotlin/reflect/ReflectKotlinClass
at org.springframework.data.util.ReflectionUtils.isSupportedKotlinClass(ReflectionUtils.java:384)
</code>

**Comment by spencergibb** [comment]
duplicates #11661

**Comment by wilkinsona** [comment]
Thank you, @spencergibb. @shenliuyang Please take a moment to check for existing issues before opening a new one.
