### ISSUE TITLE
Defer logging system clean up till as late as possible in the root context's close processing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11676]
We currently clean up the logging system in response to the root context's `ContextClosedEvent`. That event is published quite early in the close processing, notably before the context's bean factory's beans are destroyed.

Following some discussion with @dsyer, we settled on the possibility of using a `DisposableBean` instead. Such beans are destroyed in the reverse of the order in which they were registered. If we can register one very early we should be able to clean up the logging system as one of the last things that happens during context close processing rather than one of the first.

**Comment by wilkinsona** [comment]
The need for this seems to have been built on the faulty assumption that cleaning up the logging system prevents log output from being produced. In my testing that is not the case. However, it was, apparently, the case when @dsyer was looking at this. I don't understand that as it's `beforeInitialize` that causes the dark period.

**Comment by dsyer** [comment]
Maybe it only affects devtools then? That’s where I encountered the problem.

**Comment by wilkinsona** [comment]
As far as I can tell, DevTools has no effect. If I modify Boot's DevTools sample to look like this:

```java
@SpringBootApplication
public class SampleDevToolsApplication implements DisposableBean {

	private Log logger = LogFactory.getLog(SampleDevToolsApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(SampleDevToolsApplication.class, args);
	}

	@Override
	public void destroy() throws Exception {
		this.logger.info("All done");
	}

}
```

Then each restart produces logging like this:

```
2018-01-19 11:15:21.246  INFO 73504 --- [      Thread-16] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@7ca25ce1: startup date [Fri Jan 19 11:15:13 GMT 2018]; root of context hierarchy
2018-01-19 11:15:21.247  INFO 73504 --- [      Thread-16] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-01-19 11:15:21.247  INFO 73504 --- [      Thread-16] s.devtools.SampleDevToolsApplication     : All done

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

2018-01-19 11:15:21.411  INFO 73504 --- [  restartedMain] s.devtools.SampleDevToolsApplication     : Starting SampleDevToolsApplication on aw-rmbp.local with PID 73504 (/Users/awilkinson/dev/spring/spring-boot/master/spring-boot-samples/spring-boot-sample-devtools/target/classes started by awilkinson in /Users/awilkinson/dev/spring/spring-boot/master/spring-boot-samples/spring-boot-sample-devtools)
```

What have I missed?

**Comment by dsyer** [comment]
Well, what I saw was that some of the logging from `DisposableBeans` was missing. It was never all the logging from all `DisposableBeans` that went missing. Spring Boot 2.0 with Erueka was a pretty reliable way to make it fail. Other samples (including Spring Cloud ones with the context hierarchy) behaved themselves.

**Comment by wilkinsona** [comment]
I don't understand how it could be anything other than all or nothing. There shouldn't be a race between threads at this point which is the only way I can think that it may be variable.

Can you please point me to minimal app that uses Eureka and exhibits the problem?

**Comment by dsyer** [comment]
Here's an app: https://github.com/scratches/disposable-bean. If you run the test it uses `@DirtiesContext` so you see a complete log of the shutdown process. If you run the app and edit `application.properties` to make devtools restart it, you don't see the same logs. I'm not sure if that's 100% the same as what I was looking at, but it's in the same ballpark.

P.S. it's better if you run Eureka locally (e.g. `spring cloud eureka`) so you don't have to look at logs about failing to connect.

**Comment by wilkinsona** [comment]
Thanks.

The problem appears to be in Spring Cloud. `spring-cloud-starter-netflix-eureka-client` has a transitive dependency on `commons-logging:commons-logging` which means that `ShutdownApplicationListener` logs to JUL. If I exclude that dependency I see `Benchmark app stopped` once for each restart.

**Comment by dsyer** [comment]
Excellent. Not sure I understand what changed in Boot 2 (Spring 5 logging dependencies probably, but that doesn't explain it all yet). I'll tweak it and see if that helps.

**Comment by wilkinsona** [comment]
On reflection, I'm not particularly happy with the `DisposableBean`-based solution. It requires the use of a separate `ApplicationContextInitializer` to get the registration in as early as possible. This splits the logic that manages the logging lifecycle across two separate classes for no immediately obvious reason.

Given that the current behaviour wasn't actually causing any problems I don't think we should change it as currently proposed. We can revisit this in the future if we come up with a better solution that still allows the lifecycle to be managed in one place.
