### ISSUE TITLE
Allow IDE to link to source code for hand-written configuration properties metadata

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#11699]
Example `endpoints.default.enabled`. The docs basically say that it enables endpoints (well duh). What does it actually do? How does it differ from `endpoints.web.default.enabled`? It's probably guarding a `@Conditional` somewhere. Maybe it would be useful to see where?

Part of this is features showing up in additional-spring-configuration-metadata.json (e.g. in spring-boot-actuator-autoconfigure), where the IDE (STS anyway) doesn't support linking to relevant source code. The metadata isn't there to create a link - these files are curated by hand, so I guess if there is a way for the IDE to link to something in source code it would be useful to add it.

See #10930

**Comment by philwebb** [comment]
I wonder how we can attack this without breaking existing IDE integration. We could obviously add a new "link" element, but it might be quite limited to just have a single link.

The other thing that really bothers me about this is keeping everything in sync. We'll definitely need something in the build that ensures we don't link to something in the docs that doesn't exist.

**Comment by philwebb** [comment]
I think there's probably too much work involved in implementing this for the value it will give. I also prefer the idea of documentation links rather than source code.
