### ISSUE TITLE
Loader Tools: unpacking a library alters its position in the classpath

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#11695]
The order of libraries on the runtime classpath should match the order they were initially added in the fat jar. 
The `Repackager` adds libraries in the following order:
1. unpack libraries
2. application classes
3. other libraries
4. loader classes

Marking a library as unpacked affects its position on the classpath - which is not expected.

See https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/Repackager.java#L252-L267
See https://github.com/spring-projects/spring-boot/issues/9128#issuecomment-358980565

**Comment by wilkinsona** [comment]
I've just reminded myself that the current ordering is deliberate (see https://github.com/spring-projects/spring-boot/issues/3444) for details. If we're going to fix this, we'll have to find a way to do so that doesn't introduce a regression.

**Comment by wilkinsona** [comment]
The Gradle plugin is unaffected by this problem. I've added a test to verify that's the case in https://github.com/spring-projects/spring-boot/commit/8f116f7e6fe789f4192de292984e926ecbea2a3d.
