### ISSUE TITLE
Loader Tools: application classes should appear before libraries on the runtime classpath

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#11696]
See https://github.com/spring-projects/spring-boot/issues/9128#issuecomment-358980565 (second paragraph) for the original discussion.

In short: the runtime classpath should have application classes from `BOOT-INF/classes` before libraries taken from `BOOT-INF/lib`. This would match the observed behaviour of Eclipse, Maven, Surefire, etc.

The current implementation of the `Repackager` respects that order but without any guarantee: it is more because of the current implementation rather than by specification. There is also no test case to assert this order is respected.

**Comment by wilkinsona** [comment]
The Gradle plugin was already doing the right thing for war files. Jar files have been aligned with war files in https://github.com/spring-projects/spring-boot/commit/8f116f7e6fe789f4192de292984e926ecbea2a3d.
