### ISSUE TITLE
App hangs when CONSOLE appender is missing in log4j configuration

### ISSUE THREAD

**Issue by meltsufin** [spring-projects/spring-boot#11700]
Repro [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/log-hangs/spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/main/resources/logback-spring.xml#L8).

Build the project from root first, then run the `spring-cloud-gcp-logging-sample` with `mvn spring-boot:run`.
You'll notice that the app hangs right after the logo output.
If you uncomment the console appender, the app starts up fine.

Also see: https://github.com/spring-cloud/spring-cloud-gcp/issues/315

**Comment by wilkinsona** [comment]
How have you determined that the app has hung? Are sure sure that it isn’t running happily but appears to have hung as there’s no console output?

**Comment by meltsufin** [comment]
You're totally right, we just figured out that after that point all logs are actually redirected to the `STACKDRIVER` logger rather than the console. That's why it appears hung, but it's not. Closing.
