### ISSUE TITLE
Consider supporting health check RFC

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11706]
See https://inadarei.github.io/rfc-healthcheck/

**Comment by philwebb** [comment]
The RFC doesn't seem to be getting much traction. I'll close this for now and we can reconsider if things change.

**Comment by Roni1993** [comment]
Just a curious question:
Is there another standard beside this RFC that is supported by Spring?
As far as i can tell the Actuator implementation is not implementing a specification.

**Comment by wilkinsona** [comment]
As far as we know there's no standard for health checking (the RFC linked above is only a draft).

**Comment by derekm** [comment]
An Internet-Draft RFC is a call for people like Spring and MicroProfile devs to get involved in specifying the standard and changing things to better suit everyone (such as specifying acceptable aliases to the "warn" state [which Actuator Health might have the answer to w.r.t. unmapped custom states mapping to UP]): https://inadarei.github.io/rfc-healthcheck/#rfc.section.3.1

Your involvement in a draft RFC will make the RFC align to your needs, which will help it gain traction!

The RFC definitely isn't perfect, and it needs Spring's input to avoid harmful decisions that prevent it from being a viable standard. (For example, I think this is harmful to a Java implementation: https://inadarei.github.io/rfc-healthcheck/#additional-keys -- this is alternative to Spring's inner `details` or MP Health's `data` objects.)

See "prolonged involvement" here: https://youtu.be/qJ77qGjdnek?t=210
