### ISSUE TITLE
Reloading properties files (or maybe the whole context)

### ISSUE THREAD

**Issue by dickerpulli** [spring-projects/spring-boot#1170]
Is it possible to reload i.e. the application.properties file while running the application with out restarting the JVM?

I tried to call refresh() on the EmbeddedWebApplicationContext, but this class is no able to refresh more than once.

**Comment by sunaina-ishi** [comment]
Is the feature implemented to support the functionality as stated above to a Controller (WebMVC), that receives a "refresh-request" and performs the refresh of the application context.?. I have the sam e requirements.

**Comment by dsyer** [comment]
You need the spring-cloud-context library. Adding it as a dependency, plus the spring-boot-actuator will activate a /refresh and a /restart endpoint (amongst other things).

**Comment by sunaina-ishi** [comment]
You prompt reply is highly appreciated. I have added the dependency and the endpoints "/refresh" is not behaving as expected. My context still referring to the old values. Do we need to have spring-cloud-config setup to make it work ?. 

Can u just give me some sample code to see how it works., It will be really helpful. Thanks

**Comment by sunaina-ishi** [comment]
It seems to make it work adding @RefreshScope to the appropriate bean is necessary. Is this mandatory. 
Suppose I am writing a SMPP implementation and its properties are bind with a bean in our @Configuration file. I would like to change one of the properties of smpp server. Now I cannot add @RefreshScope SMPP APi's bundled in jar. So will the properties take affect after invoking refresh.
Please suggest

**Comment by dsyer** [comment]
It depends. The `@RefreshScope` is needed for anything that needs to be re-initialized (as opposed to just rebound to the `Environment`). This should be clear from the Spring Cloud user guide.
