### ISSUE TITLE
 Decide how to deal with H2 console and security

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11704]
See #10264 for background.

**Comment by snicoll** [comment]
Perhaps we could rename `StaticResourceRequest` to something a bit more general and have a `h2Console` option that uses `spring.h2.console.path`?  The implementation should be straightforward considering  what we have done for the actuator.

**Comment by mbhave** [comment]
I think if we really want to provide an easy way to add back 1.5 like security for H2, we would need something more than the `RequestMatcher`. The `RequestMatcher` only prevents duplication of `spring.h2.console.path` in the custom `WebSecurityConfigurerAdapter` but default 1.5 security for H2 was much more [involved](https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/h2/H2ConsoleAutoConfiguration.java#L100). I wonder if we can provide a `SecurityConfigurer` instead.

**Comment by philwebb** [comment]
I didn't realize it did that much!

> I wonder if we can provide a SecurityConfigurer instead

I guess it depends how easy it is to mix that in with existing security concerns. One reason I like the new matchers is it's easy to plug them in at the correct place (not bean ordering etc). In the past Rob talked about using some static helper, perhaps this would be a good candidate for that?

**Comment by mbhave** [comment]
We're going to go with a `RequestMatcher`
