### ISSUE TITLE
Support embedding Tomcat 9

### ISSUE THREAD

**Issue by mrcasablr** [spring-projects/spring-boot#11749]
Tomcat 9.0.4 is now released as the first stable release. - http://mail-archives.apache.org/mod_mbox/www-announce/201801.mbox/

9.0.5 is available - http://mail-archives.apache.org/mod_mbox/www-announce/201802.mbox/browser

**Comment by wilkinsona** [comment]
While it’s described as stable, the release notes state that all of the public API is still subject to change. As far as I can tell, official Tomcat 9 support will have to wait for Boot 2.1.

**Comment by shakuzen** [comment]
> the release notes state that all of the public API is still subject to change.

Sharing in case others wonder (I did) where this is stated: http://tomcat.apache.org/tomcat-9.0-doc/RELEASE-NOTES.txt

**Comment by mrcasablr** [comment]
@wilkinsona based on the above link on API stability, would you still like to keep this for 2.1?

**Comment by shakuzen** [comment]
Just sharing that as of Tomcat 9.0.5, [9.0.x API Stability](https://tomcat.apache.org/tomcat-9.0-doc/RELEASE-NOTES.txt) matches [8.5.x API stability](https://tomcat.apache.org/tomcat-8.5-doc/RELEASE-NOTES.txt).

> \==============
> API Stability:
> \==============
> 
> The public interfaces for the following classes are fixed and will not be
> changed at all during the remaining lifetime of the 8.x series:
> \- All classes in the javax namespace
> 
> The public interfaces for the following classes may be added to in order to
> resolve bugs and/or add new features. No existing interface method will be
> removed or changed although it may be deprecated.
> \- org.apache.catalina.* (excluding sub-packages)

**Comment by sigzero** [comment]
Support of 8.X is EOL in June. I hope that's being tracked.

http://tomcat.apache.org/tomcat-80-eol.html

**Comment by wilkinsona** [comment]
It’s not 8.x, but 8.0.x. Boot 1.5 and 2.0 use 8.5.x so are unaffected by that EOL announcement.

**Comment by TYsewyn** [comment]
I tried to add Servlet 4.0 support, so both Tomcat 9 and Undertow 2 can be used as embedded servlet containers.
Currently there is a bug in Tomcat 9.0.5 which is applying compression in certain scenarios where we don't want it to happen.

See https://bz.apache.org/bugzilla/show_bug.cgi?id=62154

**Comment by cmoulliard** [comment]
Will Spring Boot 1.5.x support Tomcat 9 or only Spring Boot 2.1 @wilkinsona ?

**Comment by wilkinsona** [comment]
It will be new functionality so it will be in 2.1 only.

**Comment by wilkinsona** [comment]
We need Tomcat 9.0.9 so that we can pick up [this fix](https://github.com/apache/tomcat/commit/2b239e1ea0f3f8b5cdf01062a106ade9465756ec#diff-95185e588de3604778aaae00c0afdf10) for an earlier regression.

**Comment by vkennke** [comment]
FYI, Tomcat 9.0.10 was [released](http://tomcat.apache.org/tomcat-9.0-doc/changelog.html#Tomcat_9.0.10_(markt)).

**Comment by wilkinsona** [comment]
Thanks, @vkennke. We should hopefully be able to get this into 2.1 M1 now.
