### ISSUE TITLE
Liquibase Configuration prone to misuse.

### ISSUE THREAD

**Issue by DominicGunn** [spring-projects/spring-boot#11747]
Hey all.

Quick question regarding the current implementation of [LiquibaseAutoConfiguration](
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java). Though it is documented, it seems a little haphazard that failing to specify `liquibase.url` will cause a fallback of using the primary Datasource bean. 

As a user I would prefer if provided with a `liquibase.user` and `liquibase.password`, that those would be used against the default `datasource.url`, instead of Liquibase running with the primary `datasource.username` and `datasource.password` which can cause all sorts of issues in role based schemas.

Is there any strong feelings about the current implementation, or any information on why it was implemented this way? A quick Github search for `liquibase.user` shows tonnes of users, using this without implementing `liquibase.url`, and those that do are simply using the default `datasource.url`.

Interested to hear your thoughts.

**Comment by wilkinsona** [comment]
Support for Liquibase-specific url, user, and password was added in https://github.com/spring-projects/spring-boot/issues/1558. Unfortunately, there's no details in the issue or the associated commit that describes how the current behaviour was chosen. Given that the change was made over three years ago, I suspect it's unlikely that @dsyer will be able to remember.

The current behaviour with Flyway is similar. It requires both the `url` and the `user` to be set before it will use the `url`, `user`, and `password` to create a data source. That behaviour was added in https://github.com/spring-projects/spring-boot/issues/807.

On the face of it, I think it makes sense for the configuration of any of `url`, `user`, or `password` to trigger the creation of a custom data source, falling back to the primary data source's configuration for any Flyway or Liquibase-specific property that hasn't been configured. There's a slight risk, however, that this would be a breaking change for some if we started using a property that is currently being ignored. As such, any change probably belongs in 2.0 at the earliest and time's running out there.

An alternative would be to log a warning if a Flyway or Liquibase-specific property has been set and it's going to be ignored as the URL or whatever else is needed hasn't also been configured.

**Comment by DominicGunn** [comment]
Agree that this could be a potentially breaking change, but feel that it it's worth looking at as we approach 2.0. The code change seems relatively minor but would like to gage people's reactions before trying to move ahead with this.

For what it's worth, the approach you've suggested (making use of Flyway/Liquibase configuration if available, and primary datasource if not) makes the most sense and is something I'd try and push for, it feels like that makes the most sense and from what I've seen all over Github is how people assume this works anyway.

At the very least, I feel a strong warning that this is happening would be appropriate, it was only caught on our team pretty late and could've caused real problems for us if we were to have gone to production in that state. We should've probably caught this in the documentation for sure, but feel a warning would've strongly helped.

**Comment by philwebb** [comment]
I think it would make sense to trigger it on any of them. 2.0 would be a great time to make that change but we are up against the clock somewhat.

**Comment by DominicGunn** [comment]
What sort of time are we talking? I could take a crack at fixing this up if you guys are close to the wire.

**Comment by wilkinsona** [comment]
That would be much appreciated. RC1 is due a week today (30/1). If you do submit a PR, I can't promise that we'll find time to merge it before then but we'll try our best to do so.

**Comment by DominicGunn** [comment]
Taken a crack at [it](https://github.com/spring-projects/spring-boot/pull/11751). 

My first PR to the project, so let me know if I'm falling short on some of your typical standards/code style!

**Comment by philwebb** [comment]
Thanks @DominicGunn. Don't worry too much about the code style etc for your first contribution. We're happy to polish up commits when we merge them.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#11751).
