### ISSUE TITLE
WebFilters are not ordered explicitly

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11756]
We currently auto-configure two `WebFilter` beans:

- `WebFilterChainProxy` from Spring Security
- `MetricsWebFilter` for Micrometer

A third will shortly be added:

- `HttpTraceWebFilter` for actuator request-response exchange tracing

`WebFilterChainProxy` is ordered (-100) but `MetricsWebFilter` is not. As a result it picks up the default order (lowest precedence). We need to explicitly order all `WebFilter` beans so that their ordering is predictable and documented.

**Comment by snicoll** [comment]
Relates to something we've done recently (#11607).

**Comment by wilkinsona** [comment]
To match the MVC configuration, `MetricsWebFilter` should be `Ordered.HIGHEST_PRECEDENCE + 1` and `HttpTraceWebFilter` should be `Ordered.LOWEST_PRECEDENCE - 10`. I'll take care of the latter in #9980.

**Comment by wilkinsona** [comment]
We'll add a `FilterOrder` class or similar, that provides a home for all the orders and can be referenced by the servlet and reactive filter configuration code.

**Comment by wilkinsona** [comment]
The `FilterOrder` idea doesn't work as well as I'd hoped. We end up with a class that references numberous other components. As such, it feels like it knows too much. For example, it would require `spring-boot` to have an optional dependency on Spring Session so that it can reference the default order defined on `org.springframework.session.web.http.SessionRepositoryFilter`.
