### ISSUE TITLE
Use of Embedded LDAP with Spring Boot does not support multiple base DN

### ISSUE THREAD

**Issue by jatinvaidya** [spring-projects/spring-boot#11752]
**Environment:** 
Spring Boot 2.0.0.M7 with "com.unboundid:unboundid-ldapsdk:3.2.1"

**Background:**
A single LDAP directory server instance can have multiple "suffixes" (base) and usually does. For example, a single person can have TWO user entries in LDAP directory with each entry under a different suffix (base).

For example:

1. DN of user's entry in one suffix:
cn=john01,ou=users,**o=company,dc=com** 

2. DN of the same user's entry in another suffix:
uid=445566,ou=users,**dc=security**

_Note: The bases or suffixes are marked bold above._

**Problem:**
At this time, there is no way to load multiple suffixes (base) with the embedded ldap plugin with spring boot. This is even though the plugin itself (unboundid) **does support multiple suffixes** (base). 

[unboundid documentation](https://docs.ldap.com/ldap-sdk/docs/in-memory-directory-server.html)
> --baseDN {baseDN} -- Specifies the base DN to use for data in the server. This argument must be provided at least once, **but may be provided multiple times if more than one base DN should be used**. 

**Defect:**
The property **spring.ldap.embedded.base-dn** currently supports only one base though. Due to this it is not possible to work with the scenario described above.

**Comment by eddumelendez** [comment]
Currently working on this and I need help 😅 

If the following property is set `spring.ldap.embedded.base-dns:dc=spring,dc=org` then there are 2 elements in the array first `dc=spring` and second `dc=org`. But, the first baseDn is `dc=spring,dc=org`

are there any way to avoid that? 🤔 

Thanks in advance

**Comment by eddumelendez** [comment]
forgot I can do this `spring.ldap.embedded.base-dns[0]:dc=spring,dc=org`. I think it needs to be documented.

**Comment by philwebb** [comment]
Closing in favor of PR #11764
