### ISSUE TITLE
Document the use of --args to pass arguments to bootRun

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1176]
Double check how easy it is to pass arguments to a `bootRun` application and how profiles can be activated.

**Comment by pcssi** [comment]
+1

**Comment by wilkinsona** [comment]
We should use a project property, something like `bootRunArgs`, that can be used to pass in properties to `bootRun`. Similar to what [Grails does with `grailsArgs`](https://github.com/grails/grails-gradle-plugin):

```
gradle -PgrailsArgs='--inplace solr' grails-create-plugin
```

**Comment by rocboronat** [comment]
+1

**Comment by iNikem** [comment]
Why not just to pass all system properties to bootRun by default? Currently all our scripts have this:
```
bootRun {
  systemProperties = System.properties
}
```

**Comment by wilkinsona** [comment]
That is, and will continue to be, a perfectly reasonable option. However, I think it's a bit too much for a default.

**Comment by jklap** [comment]
Agreed

**Comment by wilkinsona** [comment]
I discussed this at the recent Gradle Summit with Ben Muschko at the recent Gradle Summit. That discussion led to [this Gradle issue](https://github.com/gradle/gradle/issues/2402). I think we should hold off doing anything in Boot until we can build on the official support that's coming.

Ben pointed me to the [Override Plugin](https://github.com/nebula-plugins/gradle-override-plugin) that he wrote for Netflix and suggested it may be of interest in the interim.

**Comment by ErnestOrt** [comment]
I've faced the same situation, and after some investigation I found this post which make my day:

https://fbflex.wordpress.com/2014/10/16/spring-boot-shannanigan-overriding-properties-via-the-command-line-when-using-gradle/

Basically sends **arguments as environment variables** since Spring Boot is able to pick them up:

Windows example: 

SET SERVER_PORT=9891 && gradlew.bat bootRun

Cheers!

**Comment by shalom938** [comment]
as environment variable they are not available as command line arguments to to ApplicationRunner

**Comment by madorb** [comment]
The updated plugin in spring boot 2.0 has broken my workaround for starting app with a profile selected at runtime: 

`task ci { doLast { bootRun.systemProperty 'spring.profiles.active', 'ci' } }` to launch with `gradle ci bootRun`

I can't for the life of me figure out how to accomplish this with the new plugin. Any suggestions?

**Comment by wilkinsona** [comment]
https://docs.spring.io/spring-boot/docs/2.0.0.M6/gradle-plugin/reference/html/#running-your-application

**Comment by madorb** [comment]
Thanks @wilkinsona - as an FYI this is what i ended up doing:

```
bootRun.ext.activeProfiles = 'prod'
bootRun {
    doFirst {
        jvmArgs = ["-Dspring.profiles.active=" + ext.activeProfiles]
    }
}
task ci { doFirst { bootRun.ext.activeProfiles = "ci" } }
task local { doFirst { bootRun.ext.activeProfiles = "local" } }
```

**Comment by asarkar** [comment]
@wilkinsona The M6 docs you linked to say:
> Two properties, args and jvmArgs, are also provided for configuring the arguments and JVM arguments that are used to run the application.

However, I couldn't find any examples of those properties' usage, neither could I find any reference to those in the [RC1 docs](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/htmlsingle/).

**Comment by wilkinsona** [comment]
As [anticipated](https://github.com/spring-projects/spring-boot/issues/1176#issuecomment-346160888) things changed in #10872. `BootRun` is a `JavaExec` subclass once again. This is reflected in the [RC1 documentation](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/gradle-plugin/reference/html/#running-your-application).

**Comment by behrangsa** [comment]
@wilkinsona I think this (and #832) should be reopened.

**Comment by wilkinsona** [comment]
@behrangsa This issue is still open and will address #832.

**Comment by jnizet** [comment]
Since gradle 4.9, it's possible to pass argument to a JavaExec task (which bootRun is) using the following syntax:

    ./gradlew bootRun --args 'arg1 arg2'

Note however that, on macOS with zsh at least, trying to use that syntax to pass a profile makes the build fail immediately:

    ./gradlew bootRun --args '--spring.profiles.active=prod'

However, simply adding a space before the`--` makes it work as expected

    ./gradlew bootRun --args ' --spring.profiles.active=prod'

This should hopefully help people like me who tried making that work for half an hour :-)

**Comment by wilkinsona** [comment]
Thank you, @jnizet. Bash also requires a space before the `--` to make it work if it's the first argument. I suspect that may be a bug in Gradle.

**Comment by wilkinsona** [comment]
It works without a space if you use `=`:

```
./gradlew bootRun --args='--spring.profiles.active=prod'
```

**Comment by wilkinsona** [comment]
I've opened https://github.com/gradle/gradle/issues/6644. We can probably proceed with documenting this and then updating the documentation if the Gradle issue is addressed.

**Comment by ErnestOrt** [comment]
I've solve it as follows, if anyone is interested:

https://github.com/ErnestOrt/Trampoline/blob/master/trampoline/src/main/java/org/ernest/applications/trampoline/utils/ScriptContentsProvider.java
