### ISSUE TITLE
export metrics to influxdb via line protocol

### ISSUE THREAD

**Issue by wei-hai** [spring-projects/spring-boot#11778]
it would be convenient to export production metrics inside endpoint `/metrics` to influxdb via line protocol, in the properties file it could support the following variables:
```
influxdb.host=localhost
influxdb.port=8086
influxdb.protocol=tcp or udp
influxdb.database=springboot
influxdb.measurement=counter
influxdb.interval=60s
```

**Comment by philwebb** [comment]
As of Boot 2.0 we will be relying on [Micrometer](https://micrometer.io/) for metrics functionality. I'd suggest raising an enhancement request on their [GitHub](https://github.com/micrometer-metrics/micrometer).
