### ISSUE TITLE
Revise the TestPropertyValues for convenience

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#11777]
Now to combine environment style and regular dot notation we have to perform two steps binding:
```
TestPropertyValues.of("S3_ACL_EXPRESSION:headers.acl")
		.applyTo(context.getEnvironment(), TestPropertyValues.Type.SYSTEM_ENVIRONMENT);

TestPropertyValues.of("s3.bucket:foo")
		.applyTo(context);
```

Reconsider this API for better fluent way or some other `Type` mode where we can combine properties as it was available before:
```
EnvironmentTestUtils.addEnvironment(context, "s3.bucket:foo", "S3_ACL_EXPRESSION:headers.acl");
```

**Comment by philwebb** [comment]
In hindsight, I think it's better to have distinct calls to add the different types. If we try and make the method too smart, it's likely to get confusing.
