### ISSUE TITLE
[actuator] No datasource metics show on /metrics

### ISSUE THREAD

**Issue by dpy1123** [spring-projects/spring-boot#11787]
I am using the default tomcat jdbc datasource with actuator on. 
But `datasource` in /metrics endpoint is always empty.
I wonder if the screenshot below is the reason.
thx~
![sb](https://user-images.githubusercontent.com/3691507/35429671-0b5eb1e8-02b0-11e8-845b-76ed868054a2.png)

**Comment by dpy1123** [comment]
Oh, it is javamelody who create a proxy for datasource. 
digging into javamelody now...

**Comment by wilkinsona** [comment]
Thanks for tracking this down to Java Melody's proxying. Given that's happening, I don't think this is a Spring Boot problem. If that turns out not to be the case we can reopen this issue.
