### ISSUE TITLE
Normalize micrometer client request URI tag to always contain a leading slash

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11798]
See https://github.com/micrometer-metrics/micrometer/issues/283

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/pull/11776/commits/ae9b1d3722db8e5f2be87c5ffd4861098bfa3f62

**Comment by philwebb** [comment]
@jkschneider There's extra stuff in https://github.com/spring-projects/spring-boot/commit/ae9b1d3722db8e5f2be87c5ffd4861098bfa3f62 so I'm not sure if there should be a new issue to cover that or not?

**Comment by jkschneider** [comment]
@philwebb I guess the "extra" stuff is removing `recordRequestPercentiles`? If we have a property-based meter filter, then this kind of property becomes unnecessary.
