### ISSUE TITLE
Rename trace to httptrace since it's now only for http

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#11806]
https://github.com/spring-cloud/spring-cloud-bus/blob/master/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/event/TraceListener.java

The bus had a custom trace that is now broken since maps are no longer used.

**Comment by wilkinsona** [comment]
I think you should roll your own repository and endpoint for this. The old repository and endpoint were too loosely typed to be easily consumable. It was particularly difficult for clients of the endpoint as previously there were almost no guarantees about what they’d receive and what to do with it.

**Comment by spencergibb** [comment]
Looks like we'll create our own. https://github.com/spring-cloud/spring-cloud-commons/issues/311

**Comment by spencergibb** [comment]
Any possibility of changing the name to match `trace -> httptrace`, since it's not generic anymore?

**Comment by vibhortayal** [comment]
How do we access the bus events trace? /actuator endpoint does not have "/trace" anymore and "/httptrace" does not show the bus events.

**Comment by snicoll** [comment]
@vibhortayal please do not discuss spring cloud bus issue here. There is a link to https://github.com/spring-cloud/spring-cloud-commons/issues/311 in  a comment above yours.
