### ISSUE TITLE
Decide how to deal with response when handling errors in RouterFunctionMetrics

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11807]
See [this original FIXME](https://github.com/spring-projects/spring-boot/blob/643cda480f28b7265177a58d4c40ec40923a7bb0/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/reactive/server/RouterFunctionMetrics.java#L133)

**Comment by wilkinsona** [comment]
This has become obsolete. `RouterFunctionMetrics` was deprecated in https://github.com/spring-projects/spring-boot/issues/12833 and subsequently removed.
