### ISSUE TITLE
MockMVC ResultMatchers.status().is(200) - method call needs to be escaped in kotlin

### ISSUE THREAD

**Issue by BastianVoigt** [spring-projects/spring-boot#11823]
Spring Boot Version: 2.0.0.M7

For better experience for Kotlin users, the MockMVC result matcher `status()` should not use the kotlin keyword `is` as a method name, because the method call needs to be escaped in backticks which is not very convenient.

**Comment by snicoll** [comment]
`MockMVC` is not  a Spring Boot feature. The issue tracker of Spring Framework is [here](https://jira.spring.io/browse/SPR)

**Comment by sdeleuze** [comment]
@BastianVoigt Indeed, please create such issue on Spring Framework side. `is` is usable in Kotlin with backticks, and an extension could provide an alternative for those who want to avoid backticks like we did for Spring Data.

**Comment by BastianVoigt** [comment]
Whatever you guys want :)
I just created https://jira.spring.io/browse/SPR-16429
