### ISSUE TITLE
Support spring-boot-cli in MinGW Windows environments

### ISSUE THREAD

**Issue by stadler** [spring-projects/spring-boot#11846]
## Problem Description
Currently the spring-boot-cli (1.5.9.RELEASE) bash script can deal with Cygwin and Darwin environments but not with MinGW (http://www.mingw.org/) environments. 
MinGW is minimalistic Unix Environment for Windows and is e.g. the default bash environment in the Cmder (http://cmder.net/) console emulator.

## Request
It would be great if the spring-boot-cli script would also run in MinGW environements.

## Current Behaviour
Current behaviour when trying to execute it is (sorry, it is a german environment):
```
$ spring version
Fehler: Hauptklasse org.springframework.boot.loader.JarLauncher konnte nicht gefunden oder geladen werden
$ uname
MINGW32_NT-6.1-WOW
```

## Expected Behaviour
```
$ spring version
Spring CLI v1.5.9.RELEASE
```

Note that in a Windows/cmd.exe environment it works fine.

**Comment by snicoll** [comment]
Closing in favour of PR #11848 

@stadler fyi, there is no need to create both an issue and a PR.
