### ISSUE TITLE
Quartz Scheduler - configurable SchedulerFactory

### ISSUE THREAD

**Issue by lazystone** [spring-projects/spring-boot#11847]
I was trying to integrate [quartz-mongodb](https://github.com/michaelklishin/quartz-mongodb) with Spring, but found that it's nearly impossible to do that without ugly hacks.

What I wanted is to provide a bean that implements org.quartz.SchedulerFactory which injects MongoClient, so I can create a scheduler which can store jobs in MongoDB.

The problem is in the implementation of `org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet`:
```java
// Create SchedulerFactory instance...
SchedulerFactory schedulerFactory = BeanUtils.instantiateClass(this.schedulerFactoryClass);
initSchedulerFactory(schedulerFactory);
```

Here it instantiates a factory using reflection(I think). Instead I would like to have conditional scheduler factory initialization - if there is a bean of org.quartz.SchedulerFactory, then use it, otherwise use the code above.

Or even better: StdSchedulerFactory can be created as conditional bean as well - if there is not any SchedulerFactory, then create default one.

In the worst case the code above can be moved to protected method so it's possible to override it.

**Comment by snicoll** [comment]
Thanks but that class is in Spring Framework. If you want to pursue the request for an API change there, please [create an issue in the Spring Framework issue tracker](https://jira.spring.io/browse/SPR)

**Comment by lazystone** [comment]
Created https://jira.spring.io/browse/SPR-16439
