### ISSUE TITLE
Documentation: Spring Boot 2.0.0 RC1 Release Notes are missing changes from issue#11589

### ISSUE THREAD

**Issue by Maarten-Damen** [spring-projects/spring-boot#11865]
Changes made in issue [#11589](https://github.com/spring-projects/spring-boot/issues/11589) are missing in the Release Notes for 2.0.0.RC1. I noticed since we retrieve the Cookie from the ServerProperties.Session which is moved from "ServerProperties.Session.Cookie " to "ServerProperties.Servlet.Session.Cookie".

Might be helpful for other to document this change.

**Comment by snicoll** [comment]
@Maarten-Damen we don't document individual properties like that and your IDE should tell you that those properties are wrong with even a hint for the replacement.

![image](https://user-images.githubusercontent.com/490484/35626153-1fdc34cc-0695-11e8-8d48-363a3e7e9f5b.png)

And the release notes have a [full list of config keys that have changed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Configuration-Changelog).

**Comment by wilkinsona** [comment]
While I don't think we should explicitly list every property, I think this change does warrant an entry in the release notes that describes the general `server.*` to `server.servlet.*` change. I've made that addition [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes#servlet-specific-server-configuration-properties).
