### ISSUE TITLE
server.address with an IP address can bind jetty to different IP address

### ISSUE THREAD

**Issue by henrjk** [spring-projects/spring-boot#11860]
We want to start a springboot/gradle rest server application configured to use jetty, so that it binds to a particular IP address using the `-Dserver.address` java parameter.

We are using spring boot 1.5.4  which pulls in jetty-server version 9.4.5.v20170502.

The spring boot integration code does a reverse lookup on the IP address configured with `server.address`. With the IP address 10.10.10.10 which this resolves in our context to the hostname.

When jetty server socket is bound the hostname is resolved to an IP address.
However if multiple network adapters are available this can be a different IP
address then what was specified with `server.address`. As a consequence the server is then not available on the specified IP address.

The fix seems straight forward. In `JettyEmbeddedServletContainerFactory.java` calls to getHostName() can be replaced with getHostString().
A side benefit is that this could increase startup time as reverse name resolution can be quite slow.

Do you see problems with this change?

I could contribute a PR for the 1.5.x branch. 
I have not yet investigated whether there is a similar issue in master.

**Comment by wilkinsona** [comment]
I can't see any problems with what you've proposed. A pull request would be most welcome. Thanks.

**Comment by henrjk** [comment]
In my fork I made the described change and running all unit test from `/spring-boot/src/test/java`  in Eclipse remains green.  Are there any other tests I should be running? 

A unit test which which validates that the host name from -Dserver.address will remain an IP string in the server connectors with a JettyServerCustomizer associated with the factory might be worthwhile. Do you have a suggestion on whether such a test should be provided and if so where to add this?  

Would this change require signing a CLA?

**Comment by wilkinsona** [comment]
Thanks for the update.

> Do you have a suggestion on whether such a test should be provided and if so where to add this?

Yes, a test would be good please. I'd add it to `JettyEmbeddedServletContainerFactoryTests` where you can use the `setAddress(InetAddress)` method on the factory. You should then be able to start the container, and retrieve the connector from the server to verify its host.

> Would this change require signing a CLA?

The change is non-trivial so, yes, signing the CLA will be required.

**Comment by henrjk** [comment]
To test the currently broken state my test code needs an IP address of the local machine which reverse name resolves without an UnknownHostException. 
The code for this involves looking at the network interfaces. However for better testing I would need to do this work outside of a VM where I currently working. This will probably not happen until Monday unless you would have code that does this already somewhere that I could use.

**Comment by wilkinsona** [comment]
@henrjk Can you use `InetAddress.getLocalHost().getHostAddress()`? That works for me on macOS and I can use that address to create an `InetAddress` and retrieve the host name.

If it won't work universally, or requires more complex code that enumerates the network interfaces, I am not sure that it's worth it.

**Comment by henrjk** [comment]
I thought this doesn't work as I have seen on 127.0.0.2 on Windows getHostName() run internally into an UnknownHostException and then simple use "127..0.0.2" which them masks the issue.

But it turns out that with 127.0.0.1 which is returned for the InetAddress.getLocalHost() I can actually verify the fix. So the PR should come sometimes later.

**Comment by henrjk** [comment]
The code changes for the PR were made against the 1.5.x branch. Perhaps I submitted that wrong.?

**Comment by wilkinsona** [comment]
Thanks, @henrjk. Don't worry about the branch. I can sort that as part of merging the changes.

**Comment by wilkinsona** [comment]
Closing in favour of PR #11889.

**Comment by henrjk** [comment]
@wilkinsona Thank you. Will this go into master as well? 
What is the approximate timing on 1.5.x releases?

**Comment by wilkinsona** [comment]
It's already in master. We've only just released 1.5.10 so there's no firm date for 1.5.11 yet.
