### ISSUE TITLE
Gradle multiproject build: @DataJpaTest does not find @SpringBootConfiguration/@SpringBootApplication on 2.0.0.RC1, but does on 1.5.10.RELEASE

### ISSUE THREAD

**Issue by acdcjunior** [spring-projects/spring-boot#11873]
**Version affected:**  `2.0.0.RC1` (`2.0.0.M7` also)

**Problem:** `@DataJpaTest` does not find `@SpringBootConfiguration`/`@SpringBootApplication` on `2.0.0.RC1`, but does on `1.5.10.RELEASE`.

**Scenario:** A multiproject gradle build, where the  `@DataJpaTest` is at a submodule that depends (runtime only) on the module that contains `@SpringBootApplication`. May seem strange, but it works well at `1.5.*`.

### How to reproduce:

- Clone https://github.com/acdcjunior/spring-boot2-gradle-subprojects-datajpa.git
- Run `gradlew build -i` and notice it doesn't work
- Comment/uncomment versions at [build.gradle](https://github.com/acdcjunior/spring-boot2-gradle-subprojects-datajpa/blob/master/build.gradle#L3) into `1.5.10.RELEASE`, run `gradlew build -i` again and notice it works as usual.

Error message (shown when version is `2.0.0.RC1`):

>     com.example.domain.stuff.MyEntityRepositoryTest > initializationError FAILED
>        java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test

**Comment by snicoll** [comment]
@acdcjunior that's a gradle build configuration problem. This test works just fine in my IDE. I don't know Gradle enough to have an opinion but I don't see how it is related to Spring Boot.

**Comment by acdcjunior** [comment]
I'm thinking it is related to Spring Boot because in `1.5.10.RELEASE` it works and in `2.0.0.RC1` it doesn't. Nothing changed about Gradle, just Spring Boot.

**Comment by wilkinsona** [comment]
The info output shows that you have the following on the classpath (along with several third-party jars):

- `sub-domain/build/classes/java/test`
- `sub-domain/build/resources/test`
- `sub-domain/build/classes/java/main`
- `sub-domain/build/resources/main`
- `sub-infra/build/libs/sub-infra.jar`
- `sub-web/build/libs/sub-web.jar`
- `sub-infra/build/classes/java/test`
- `sub-infra/build/resources/test`
- `sub-domain/build/libs/sub-domain.jar`

`MyApplication` is part of the `sub-infra` module and only its jar is on the class path. However, this jar doesn't exist.

The `sub-infra` module has the Spring Boot plugin applied to it which means that it isn't, by default, suitable for use as a dependency. Applying the Spring Boot plugin [disables the `jar` task](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#reacting-to-other-plugins-java) in favour of the `bootJar` task that builds your application's fat jar. This is why the jar isn't produced when you run `build`.

Ideally, you should avoid using a Spring Boot application as a dependency. However, if you need to do so, enable the `jar` task and [assign a classifier to either it or the `bootJar` task](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#packaging-executable-and-normal).
