### ISSUE TITLE
The addFormatters method of WebMvcAutoConfigurationAdapter does not working

### ISSUE THREAD

**Issue by lanmolsz** [spring-projects/spring-boot#11887]
The `addFormatters` method of `WebMvcConfigurer` is called by `DelegatingWebMvcConfiguration` and is called in the `mvcConversionService` method. But at this point the list of `WebMvcConfigurer` is not injected, so all `addFormatters` that override `WebMvcConfigurer` will not be called.

**Comment by wilkinsona** [comment]
@lanmolsz The code in question is part of Spring Framework. If you would like to pursue this, please open a [Spring Framework JIRA ticket](https://jira.spring.io/browse/SPR).
