### ISSUE TITLE
Make the exception message output from AbstractHealthIndicator settable via constructor

### ISSUE THREAD

**Issue by solidjb** [spring-projects/spring-boot#11880]
Enhancement:

Currently when an exception is caught in AbstractHealthIndicator it will log the string "Health check failed" and the thrown exception.  

In the case where we use a generic class to represent multiple health indicator instances, it would be useful for that message to be configurable so we can be sure exactly which instance is throwing the exception (especially if it isn't happening any longer, and we are looking at historical logs)

It seems that this would be easily accomplished by having a second constructor that takes an exception message and uses that when exceptions are logged.

**Comment by philwebb** [comment]
Thanks for the suggestion. As of 2.0 you'll be able to construct with a custom message or a `Function` that returns a message given the exception. I've also taken the opportunity to update messages in our own indicators.

**Comment by solidjb** [comment]
Thanks for jumping on that so quickly.

**Comment by solidjb** [comment]
Any chance for a backport to 1.x?

**Comment by philwebb** [comment]
I'd rather not I'm afraid. It feels like an enhancement and `Function` isn't available to use because we're Java 6 compatible in 1.5.
