### ISSUE TITLE
Document "Consider a better default for JSR-310 Jackson rendering"

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11898]
As mentioned [here](https://github.com/spring-projects/spring-boot/issues/11079#issuecomment-362846375) we might not have documented this yet. We should check the reference and release notes.

**Comment by wilkinsona** [comment]
It's now mentioned in the reference documentation and in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes#jackson).
