### ISSUE TITLE
Spring Boot 2.0 Media Type Mapping by extension  Not Found

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#11896]
Bug report
```java
@RequestMapping("sample")
public Map<String, String> sample() {
    return Collections.singletonMap("key", "value");
}
```
curl http://localhost:8080/sample.json
Spring 1.x 200 OK
Spring 2.0 404 Not Found
https://travis-ci.org/zhanhb/extension-test
https://github.com/zhanhb/extension-test

**Comment by philwebb** [comment]
We've changed the suffix path matching setting in RC1. See [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes#spring-mvc-path-matching-default-behavior-change) of the release notes and [this part of the reference docs](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-pathmatch).
