### ISSUE TITLE
spring.datasource.hikari.* properties in Spring Boot 2.0.0.RC1 prevents application from starting

### ISSUE THREAD

**Issue by pjverity** [spring-projects/spring-boot#11901]
Hi,

I see this problem in 2.0.0.RC1 but not in 2.0.0.M7. My application contains several `spring.datasource.hikari.*` properties. (`maximum-pool-size` or `schema` are examples that cause this problem)

This causes the application to fail to start with the exception:

```Caused by: java.lang.IllegalStateException: The configuration of the pool is sealed once started.  Use HikariConfigMXBean for runtime changes.```

It seems to be that the Datasource is configured on the initial refresh, and then again when this fires in `ConfigurationPropertiesRebinder`:

```java
@Override
public void onApplicationEvent(EnvironmentChangeEvent event) {
	rebind();
}
```

HikariCP V2.7.6 _seals_ the configuration preventing properties from being changed. It seems the above application event tries to 'reconfigure' the sealed datasource and throws the above exception, causing the application to fail to start.

The newer HikariCP dependency is introduced via `spring-boot-starter-jdbc` 2.0.0.RC1. The 2.0.0.M7 version pulls in HikariCP 2.7.4 which (on first glance) doesn't appear to seal the configuration in this way.

I can work around the issue for now by ensuring Hikari 2.7.4 appears first on the class path.

**Comment by wilkinsona** [comment]
Thanks for the report but `ConfigurationPropertiesRebinder` is part of [Spring Cloud Commons](https://github.com/spring-cloud/spring-cloud-commons).
