### ISSUE TITLE
2.x List jolokia endpoint in `/actuator`

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#11902]
The jolokia endpoint isn't listed in the `/actuator` index page. But imho it should be, also according to @philwebb in https://github.com/spring-projects/spring-boot/issues/10264#issuecomment-351173489

**Comment by philwebb** [comment]
This is related to #11701. We've discussed that issue but couldn't really see how to represent such a free form endpoint. @joshiste I assume this is for Spring Boot Admin? What kind of information would you need?

**Comment by joshiste** [comment]
> I assume this is for Spring Boot Admin? What kind of information would you need?

correct. At best the path but at least if jolokia is present... 
If there is no way to add this we need to fallback and probe the presence with HEAD requests...
