### ISSUE TITLE
Rename spring.mvc.path-match.* and spring.mvc.content-negotiation.* properties

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11913]
https://github.com/spring-projects/spring-boot/issues/11105 added some new properties that are grouped beneath `spring.mvc.path-match` and `spring.mvc.content-negotation`. We should rename them so that there's no need for the `-` characters.

`spring.mvc.pathmatch` and `spring.mvc.contentnegotation` are the easy (and most obvious) options, but perhaps there's something better?

**Comment by spencergibb** [comment]
@pkostrzewa look at the [ideal for contribution labeled issues](https://github.com/spring-projects/spring-boot/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+ideal-for-contribution%22)

**Comment by pkostrzewa** [comment]
@spencergibb thanks for suggestion, I've seen issues labeled with _ideal for contribution_ although there aren't many of them.

**Comment by spencergibb** [comment]
I count 25

**Comment by bclozel** [comment]
:+1: This is indeed an oversight on my part.
I can't find better alternatives, and those names refer to Spring MVC configuration types so in my opinion we'd better keep it that way.
