### ISSUE TITLE
Consider renaming actuator `expose` property

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11914]
Perhaps a bit late in the day for this but is `management.endpoints.web.expose` a confusing name? Should it be `management.endpoints.web.include` instead? Does the wildcard `*` value make sense.

**Comment by wilkinsona** [comment]
I think the `*` makes sense. `include` does have a nice symmetry with `exclude`, although it's perhaps not entirely clear what they're being included in. Perhaps `management.endpoints.web.exposure.include` and `management.endpoints.web.exposure.exclude` would be better?

**Comment by mbhave** [comment]
I think we had `expose` because we no longer have the security handler interceptors and "exposing" them seemed to bring attention to the fact that they might need some sort of security.

**Comment by snicoll** [comment]
I like Andy's proposal. Having expose in the name is quite important.

**Comment by DLJiangHui** [comment]
Why is this example [spring-boot-sample-actuator-log4j2] error in accessing the web page after launching the project is 404

**Comment by DLJiangHui** [comment]
In addition, under my local project, I can generate backup files for log, but not under Azure server. Does anyone know why?

**Comment by philwebb** [comment]
@DLJiangHui As mentioned in the [contributing guide](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to keep questions out of the issue tracker. Please ask questions on stackoverflow.com.
