### ISSUE TITLE
@TestPropertySource does not load .yml file properties

### ISSUE THREAD

**Issue by andreabreu-me** [spring-projects/spring-boot#11921]
I think this may be a bug. Using `@TestPropertySource(locations = "classpath:test.yml")` does not override any property.

**Comment by snicoll** [comment]
`@TestPropertySource` does not support  YAML. There was a request in Spring Framework to add that that was declined.

**Comment by andreabreu-me** [comment]
This take me some time to figure out what was happening. Maybe some additional info in documentation should be useful for others. Thanks @snicoll

**Comment by snicoll** [comment]
@andreabreu-me this is not a Spring Boot feature. If you want to pursue this, please [create  an issue in the Spring Framework tracker](https://jira.spring.io/browse/SPR).
