### ISSUE TITLE
Spring throws IllegalArgumentException, when http-Status 522 is returned

### ISSUE THREAD

**Issue by ChristianFinckler** [spring-projects/spring-boot#11923]
I am using a resttemplate to receive a http ressource.
The server returned a httpresponse with return code 522 Timeout.

In my code I do the following:
`java.lang.IllegalArgumentException: No matching constant for [522]
	at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:497)
	at org.springframework.http.ResponseEntity.getStatusCode(ResponseEntity.java:133)`
But getStatusCode throws an exception.

I think, either all missing http constants should be added or a special enum constant (unknown) should be added.
For all users it is very annoying to handle an exception in case of rarely used http status codes.

**Comment by wilkinsona** [comment]
RestTemplate and HttpStatus are part of Spring Framework and there's an [existing issue for this](https://jira.spring.io/browse/SPR-13856).
