### ISSUE TITLE
ApplicationContextRunner javadoc refers to a package protected class

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11929]
This leads to a [404 in generated javadoc](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/api/org/springframework/boot/test/context/runner/ApplicationContextRunner.html)

**Comment by wilkinsona** [comment]
It's a bit worse than just being a javadoc problem. `ApplicationContextRunner` extends `AbstractApplicationContextRunner` and the latter is package-private. IMO, a public class shouldn't have any package-private classes in its type hierarchy. I think we should make `AbstractApplicationContextRunner` public.
