### ISSUE TITLE
spring-retry with MockWebServiceServer error: 'webServiceTemplate' must not be null

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-boot#11920]
I'm using spring-boot 1.5.7.RELEASE and I'm having trouble when I have a mocked `WebServiceGatewaySupport` which has @Retryable annotations in the subclass of that class. When I call Mockito.verify() I get an UnfinishedVerificationException exception.

I find a workaround like #6828 and #5837
```
if (client instanceof Advised) {
	client = (MySubClassOfWebServiceGatewaySupport) ((Advised) client).getTargetSource().getTarget();
}
```

**Comment by wilkinsona** [comment]
Are you using `@MockBean` or creating the mock yourself? As noted in #6828, there's not much we can do if it's the latter. If it's the former, please provide a small sample that reproduces the problem and we can take a look.

**Comment by mhewedy** [comment]
I am using something similar to the example in the documentation [here](https://docs.spring.io/spring-ws/site/apidocs/org/springframework/ws/test/client/MockWebServiceServer.html)

Here's what I am doing:

```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = MyApp.class)
@Import(MyConfiguration.class)
public class MySubClassOfWebServiceGatewaySupportIntTest {

    @Autowired
    private MySubClassOfWebServiceGatewaySupport client;

    private MockWebServiceServer mockServer;

  
    @Before
    public void createServer() throws Exception {
        mockServer = MockWebServiceServer.createServer(client); // fails here with 'webServiceTemplate' must not be null
    }
	
	// ......
}

````

When I inspect the `client` object itself i got:
```
CGLIB$BOUND = false
CGLIB$CALLBACK_0 = {CglibAopProxy$DynamicAdvisedInterceptor@14886} 
CGLIB$CALLBACK_1 = {CglibAopProxy$StaticUnadvisedInterceptor@14887} 
CGLIB$CALLBACK_2 = {CglibAopProxy$SerializableNoOp@14888} 
CGLIB$CALLBACK_3 = {CglibAopProxy$StaticDispatcher@14889} 
CGLIB$CALLBACK_4 = {CglibAopProxy$AdvisedDispatcher@14890} 
CGLIB$CALLBACK_5 = {CglibAopProxy$EqualsInterceptor@14891} 
CGLIB$CALLBACK_6 = {CglibAopProxy$HashCodeInterceptor@14892} 
logger = null
webServiceTemplate = null
```

**Comment by wilkinsona** [comment]
Thanks, but that's not enough information for us to figure out what's going on here. For example, you mentioned Mockito in the title and original description but I can't see any sign of it being used in the code above. If you'd like us to spend some more time on this, please take the time to provide a small, complete sample that reproduces the problem.

**Comment by mhewedy** [comment]
Title updated, sorry it was copy-n-paste.

I'll work on a complete example and upload here.

**Comment by mhewedy** [comment]
Demo spring boot app to reproduce the issue
[demo.zip](https://github.com/spring-projects/spring-boot/files/1709066/demo.zip)

**Comment by wilkinsona** [comment]
Thanks. This isn't a Spring Boot problem. It's a problem with Spring Retry proxying `QuoteClient` due to its `@Retryable` method and `MockWebServiceServer.createServer` being unable to correctly consume that proxy. You can avoid the problem by unwrapping the proxy before passing it into `createServer`:

```
@Before
    public void before() {
        mockServer = MockWebServiceServer.createServer((QuoteClient)AopTestUtils.getUltimateTargetObject(quoteClient));
    }
```
