### ISSUE TITLE
Security for Webflux is quite hard to get started with

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#11928]
The user guide is a bit thin here - no examples or links to samples - so I found it quite hard to get started with configuring security in a reactive app. There is no reactive starter, so I guess all the features are included in the vanilla security starter? The sample in Spring Boot with security and webflux doesn't have any custom configuration, which is fine obviously, but didn't help me. I found a couple of samples in Spring Security and this section of the Spring Security user guide is useful (but not Boot specific): https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#explicit-webflux-security-configuration.

**Comment by mbhave** [comment]
We can update the sample to add custom security. @dsyer [This section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security-webflux) talks about WebFlux security. Is there something specific you'd liked to be mentioned there?

**Comment by dsyer** [comment]
Yes please. Just a little code snippet. Something to show wheee to start if you need to customize. Maybe a simple sample showing how to customize login for non-actuator endpoints. Also would be good to know explicitly which dependencies are needed.

**Comment by arun2dot0** [comment]
Extending the same concern here ,no documentation on  integrating with OpenID . Almost no documentation for integrating with reactive apps with nonblocking IO
