### ISSUE TITLE
Gradle build error when configuring springBoot.buildInfo.additionalProperties

### ISSUE THREAD

**Issue by merusso** [spring-projects/spring-boot#11933]
Version: Spring Boot 2.0.0.RC1
Error: Could not set unknown property 'additionalProperties' for task ':myproject:bootBuildInfo' of type org.springframework.boot.gradle.tasks.buildinfo.BuildInfo.

I'm trying to set build properties like so
```groovy
springBoot {
	buildInfo {
		additionalProperties = [
			'buildNumber': System.env.'BUILD_NUMBER' ?: 'UNKNOWN',
			'jobName': System.env.'JOB_NAME' ?: 'UNKNOWN'
		]
	}
}
```
...following the docs as described here: https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/htmlsingle/#howto-build-info

**Comment by philwebb** [comment]
Thanks. I think this is a documentation issue related to the Gradle plugin changes. Try:

```
springBoot {
	buildInfo {
		properties {
			additionalProperties = [
				....
			]
		}
	}
}
```

**Comment by merusso** [comment]
That got rid of the Gradle error, thanks!

**Comment by rajishakya** [comment]
The old way works now.
