### ISSUE TITLE
Updating from 2 M7 to 2 RC1 breaks Jackson deserialization

### ISSUE THREAD

**Issue by gamov** [spring-projects/spring-boot#11937]
Please see this sample project for reproducing the bug:
https://github.com/gamov/jackson-spring-boot-rc1-failure

#spring-boot

**Comment by wilkinsona** [comment]
Thanks for the sample. The change in behaviour is due to a change in Lombok 1.6.20. You can restore the previous behaviour by adding a `lombok.config` file in `src/main/java` with the following contents:

```
lombok.anyConstructor.suppressConstructorProperties=false
```
