### ISSUE TITLE
Generic information on @Bean method is not considered when binding

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11931]
Give the following:

```java
@Bean 
@ConfigurationProperties("foo")
public AGenericBean<String> aBeanToBind() {
    return new AGenericBean<>();
}
```

Our `ConfigurationPropertiesBindingPostProcessor` creates a `Bindable` from the bean instance and won't consider the method return type. If we instead created a `Bindable` from the result of `ConfigurationBeanFactoryMetaData.findFactoryMethod` we'd actually have the generic.

**Comment by philwebb** [comment]
See #11908

**Comment by pkostrzewa** [comment]
@philwebb is it something that I could try to do?

**Comment by philwebb** [comment]
@pkostrzewa Thanks for the offer, but we've already started on the related issue so we'll probably get to them both at the same time.
