### ISSUE TITLE
2.0.0 change

### ISSUE THREAD

**Issue by dingzhongfa** [spring-projects/spring-boot#11940]
Hello, can you tell me the new version of the change and upgrade guide? I found that this module changes particularly large.

**Comment by wilkinsona** [comment]
We have a [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) and extensive [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes).
