### ISSUE TITLE
spring boot doesn't work in tomcat container

### ISSUE THREAD

**Issue by mjason3** [spring-projects/spring-boot#1194]
Hi,

I can run the spring boot in embeded tomcat. but after deploying to a tomcat container, i encounter this issue:
Mon Jun 30 19:35:36 CST 2014
There was an unexpected error (type=Internal Server Error, status=500).
org.apache.jsp.WEB_002dINF.views.documentation_jsp

**Comment by mdjnewman** [comment]
I can confirm that the IntelliJ error happens for me when I try to run a `@SpringBootApplication` class directly (without using maven/gradle). It happens in both versions on IntelliJ.

It is fixed temporarily if you follow the instructions @xilin, but these changes are overridden anytime the Gradle project is reimported (and it's annoying to have to tell new devs to do this).

**Comment by JerseyGood** [comment]
@xilin It works like a charm~

**Comment by ccampo133** [comment]
Can confirm that @xilin's solution works. Seems like this is an IntelliJ problem. Does anybody know if theres a ticket opened with JetBrains?

**Comment by snicoll** [comment]
https://youtrack.jetbrains.com/issue/IDEA-137364

**Comment by asegarra** [comment]
Just wanted to say this happens in NetBeans also as it runs the main class using Maven exec plugin if you right click and select Run File.. My fix was to create a maven profile that adds these with default scope and select the profile as the netbeans run configuration.

**Comment by bigslip** [comment]
it may not be a intelij bug, just tried to change like this :+1: <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
			<scope>compile</scope>
		</dependency>
and, everything works

**Comment by snicoll** [comment]
well, of course. 

You are working around the bug: the link above states that IJ does not manage provided dependencies properly. If you switch them to compile you're no longer affected by the bug....

**Comment by frankcastro** [comment]
Xi Lin Thank you very much for solving the problem I was having.

Regards

**Comment by ceoaliongroo** [comment]
In my case  just change the scope to `compile` and generate 2 artifact one `war explode` with all the elements. And other `war archive` with the war exploded inside.

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-tomcat</artifactId>
	<scope>compile</scope>
</dependency>
```
