### ISSUE TITLE
Git info and build properties to be displayed in log

### ISSUE THREAD

**Issue by szantopeter** [spring-projects/spring-boot#11950]
Problem statement

Short living applications, like batch, command line, Cloud Data Flow have no other option to display their meta data than writing it to the log. Adding actuator could expose the JMX beans, but given that these applications are short living that is not an option

Proposal
As discussed here https://github.com/spring-projects/spring-boot/pull/11917 Actuator should be modified to be able to display this information. 

I am happy to send an (another) pull request for the actuator based solution

**Comment by rupert654** [comment]
I agree it would be helpful if Spring Boot logged at least the commit ID automatically.

We currently implement this with an ApplicationListener:

```java
public class GitLoggingListener implements ApplicationListener<ApplicationStartedEvent> {
  private final static Logger LOGGER = LoggerFactory.getLogger(GitLoggingListener.class);

  @Override
  public void onApplicationEvent(final ApplicationStartedEvent event) {
    try {
      GitProperties git = event.getApplicationContext().getBean(GitProperties.class);
      LOGGER.info("This application was built from git commit id: {}", git.getShortCommitId());
    } catch (NoSuchBeanDefinitionException e) {
      LOGGER.info("This application was not built in a git repository.");
    }
  }
}
```

**Comment by wilkinsona** [comment]
Thanks, @rupert654.

Given that this is a handful of lines of code, and that the requirements for what is logged and in exactly what format are likely to vary quite a bit, I think this is something that's best done in user code rather than Boot itself.

Let's see what the rest of the team think.

**Comment by snicoll** [comment]
I second that.

**Comment by szantopeter** [comment]
it makes sense, the question is in this case if it should be documented in other place like this github issue. E.g.: here
https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#boot-features-banner

or 

here https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#production-ready

**Comment by wilkinsona** [comment]
I don't think this warrants mentioning in the documentation. The documentation already mentions the [`GitProperties`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-application-info-git) and [`BuildProperties`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-application-info-build) beans. It also [describes the various events that are fired and how to listen to them](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-application-events-and-listeners).

I think it's reasonable to expect someone with your goal to piece things together as @rupert654 has done. Thanks anyway for the suggestion.
