### ISSUE TITLE
ServerHttpSecurity.authorizeExchange().pathMatchers(...) doesn't accept reactive EndpointRequest

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#11952]
Originally Reported via spring-projects/spring-security#5002

`HttpSecurity.authorizeRequests().requestMatchers(EndpointRequest.to(...))` works fine with `org.springframework.security.config.annotation.web.builders.HttpSecurity` and `org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest`.

However, `ServerHttpSecurity.authorizeExchange().pathMatchers(EndpointRequest.to(...))` doesn't work with `org.springframework.security.config.web.server.ServerHttpSecurity` and `org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest`.

**Comment by wilkinsona** [comment]
AFAIK, this isn't a bug. `org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest` will give you a `EndpointServerWebExchangeMatcher` that is intended for use with `ServerHttpSecurity.authorizeExchange().matchers()`.

**Comment by wilkinsona** [comment]
There are a couple of examples of the intended usage [in the WebFlux security sample](https://github.com/spring-projects/spring-boot/blob/efc3f888dab6b7bcf4e877726d2c302f6ff105d1/spring-boot-samples/spring-boot-sample-secure-webflux/src/test/java/sample/secure/webflux/SampleSecureWebFluxCustomSecurityTests.java#L101-L102).

**Comment by mrdapotts** [comment]
The problem is caused because there is a org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest;  and a org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest which have different arguments.

This type of daft issue might be avoid if people included the import list in their programs
