### ISSUE TITLE
ConfigurationProperties treat .yml files differently in test environment

### ISSUE THREAD

**Issue by pvpkiran** [spring-projects/spring-boot#11960]
I recently stumbled across an issue with ConfigurationProperties.  
 If I have a map declared in my `application.yml` file.   
```
someKey: someValue
someMap:
  key1: val1
  key2: val2
```

And in one of my configuration class I have 
```
@ConfigurationProperties
@Configuration
class Config {
 Sting someKey
  Map<String, String> someMap;
  // getter and setters
}
```

This works perfectly fine both someKey and someMap are properly injected.  
But the same thing doesn't work in tests, with application-test.yml. someKey is properly injected, but not the map.  

But If I use .properties file, it works perfectly fine even in tests.  
 The problem was discussed on SO
https://stackoverflow.com/questions/48643836/read-a-map-with-spring-configurationproperties-in-test

**Comment by snicoll** [comment]
@pvpkiran If you would like us to help you please share a sample that exhibits the problem rather than describing it like this.

**Comment by snicoll** [comment]
`@TestPropertySource` does not support yaml, let's follow up on your SO post.
