### ISSUE TITLE
Default orm.xml file no longer detected

### ISSUE THREAD

**Issue by zapppp** [spring-projects/spring-boot#11964]
Spring Boot 2.0.0.RC1 doesn't load orm.xml during unit testing, but it's loaded when application is started normally. With spring boot 1.5.9 everything worked fine.

Reason for the issue seems to be c2f649df54b5cf65f8ffe096a0d7808d91a4bbe4 which added LocalContainerEntityManagerFactoryBean.setMappingResources() call in EntityManagerFactoryBuilder causing eventually DefaultPersistenceUnitManager.buildDefaultPersistenceUnitInfo() to work differently than before.  

DefaultPersistenceUnitManager.setMappingResources() is called with a zero length array so this.mappingResources != null and that's why buildDefaultPersistenceUnitInfo() executes following lines: 

if (this.mappingResources != null) {
  for (String mappingFileName : this.mappingResources) {
    scannedUnit.addMappingFileName(mappingFileName);
  }
}

With spring boot 1.5.9 following else branch was executed and everything worked:
else {
   Resource ormXml = getOrmXmlForDefaultPersistenceUnit();
   ...
}

**Comment by snicoll** [comment]
> Spring Boot 2.0.0.RC1 doesn't load orm.xml during unit testing, but it's loaded when application is started normally. 

While I might understand where the regression is coming from, I don't see why the behaviour in a test or normal app should be different. Can you please share a sample that demonstrates the issue?

**Comment by zapppp** [comment]
Here is simple project for demonstration:
[ormxmltest.zip](https://github.com/spring-projects/spring-boot/files/1709988/ormxmltest.zip)

Spring Boot starts fine when running normally, but with unit test named native query is not found (orm.xml is not loaded).

**Comment by snicoll** [comment]
@zapppp thanks, that's very helpful.
