### ISSUE TITLE
Not working https://github.com/shrinkwrap/resolver shrinkwrap-resolver in spring-boot 1.5.10.RELEASE and JDK 1.9, 

### ISSUE THREAD

**Issue by Flax163** [spring-projects/spring-boot#11976]
Hello collegies, The Library ceased to function https://github.com/shrinkwrap/resolver in spring-boot (ForJoinPool) in JDK 9

project:
[spring-boot-maven-resolver.zip](https://github.com/spring-projects/spring-boot/files/1711076/spring-boot-maven-resolver.zip)

case:
1) unzip spring-boot-maven-resolver.7z
2) build project: mvn clean install
3) launch build jar: java -jar spring-boot-maven-resolver.jar

Stack Trace:

Caused by: java.lang.ClassNotFoundException: org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.jboss.shrinkwrap.resolver.api.Invokable.loadClass(Invokable.java:64)
	... 11 more

on JDK 8 all work

Something is wrong with classLoader
invoke Thread.currentThread().getContextClassLoader() in runAsync
 
JDK9
![jdk9-class-loader](https://user-images.githubusercontent.com/8758749/36029625-718124e8-0dbd-11e8-8692-7c6119861116.png)

JDK8
![jdk8-class-loader](https://user-images.githubusercontent.com/8758749/36029651-87c7a948-0dbd-11e8-912d-1d685149f915.png)

**Comment by wilkinsona** [comment]
Thanks for the sample, but this looks like standard behaviour for ForkJoinPool. By default it [uses the system class loader as its threads' context class loader](https://docs.oracle.com/javase/9/docs/api/index.html?java/util/concurrent/ForkJoinPool.html):

> If no thread factory is supplied via a system property, then the common pool uses a factory that uses the system class loader as the thread context class loader

Class loading and class loader structure is quite different in Java 9, hence the change in behaviour.

**Comment by Flax163** [comment]
Okay, Thanks.
