### ISSUE TITLE
Auto-configure a Micrometer Clock in a single auto-configuration class

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11977]
We currently configure a `Clock` in every proper backend's auto-configuration class as well as in `SimpleMetricsExportAutoConfiguration`. I think we should be able to simplify things a bit by auto-configuring it in one place.

/cc @jkschneider

**Comment by jkschneider** [comment]
I thought we had removed them all and placed one in `MetricsAutoConfiguration`. Perhaps that got lost somewhere in the RC1 merge?

**Comment by philwebb** [comment]
I changed it, then changed it back because of auto-configuration ordering issues and blind panic.

**Comment by wilkinsona** [comment]
I'm starting to see that as I tighten up some of the other conditions…

**Comment by wilkinsona** [comment]
I think I've straightened this out in https://github.com/spring-projects/spring-boot/commit/351e1ec4def4f01db808785ef4016178eac2b6d9. The approach is the following:

- ` MetricsAutoConfiguration` goes first and provides a `Clock`.
- The export auto-configurations all go after `MetricsAutoConfiguration` and consume the `Clock`.
- All "proper" export auto-configurations go before `SimpleMetricsExportAutoConfiguration` so that the simple registry is only used as a fallback.
- Anything that needs a registry goes after `SimpleMetricsExportAutoConfiguration`.

**Comment by philwebb** [comment]
Thanks @wilkinsona, I had a feeling things still weren't quite right with the auto-configurations.
