### ISSUE TITLE
Failsafe plugin does not add production code of the module to the classpath

### ISSUE THREAD

**Issue by mdeknowis** [spring-projects/spring-boot#11974]
We upgraded from spring boot 2.0.0.M4 to 2.0.0.RC1

We experience, that our integration tests are not longer working as before. All tests using the annotation `@RestClientTest` are failing with that error now:

```txt
[ERROR] initializationError(spring.test.simple.SimpleIT)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
```

So far it looks like, that only the integration tests are affected, but the normal unit tests are not.

We created a minimum project for M4 and RC1 to reproduce this issue:
* [sample.zip](https://github.com/spring-projects/spring-boot/files/1710424/sample.zip)

**Comment by snicoll** [comment]
I don't get why this happens between M4 and RC1, this is not a new problem, #6254

**Comment by snicoll** [comment]
Looks like the upgrade to a new failsafe plugin triggered it #9414

**Comment by snicoll** [comment]
@mdeknowis please configure the failsafe plugin to use `target/classes` or alternatively setup [a classifier for the repackaged archive](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/examples/repackage-classifier.html).

**Comment by mdeknowis** [comment]
Thanks! That works fine:

```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <additionalClasspathElements>
            <additionalClasspathElement>${project.build.outputDirectory}</additionalClasspathElement>
          </additionalClasspathElements>
        </configuration>
      </plugin>
```

But I can consider this as a workaround, can't I?

**Comment by snicoll** [comment]
Please look at  the commit (1772a15). As  of RC2 you can remove any override and it will work as before.
