### ISSUE TITLE
management.metrics.export.*.enabled properties have a strange effect

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11978]
As things stand, if you disable export using a `management.metrics.export.*.enabled` property, I think you'll be left with the registry configured and being passed metrics, but not actually publishing anything. Chatting with @jkschneider, he thinks it'd be better if the registry wasn't there at all because the auto-configuration backed off entirely.

**Comment by jkschneider** [comment]
> because the auto-configuration backed off entirely.

To clarify, if you disable a registry implementation's auto-configure with `spring.autoconfigure.exclude` after #11799, the registry is never configured. Hoping for the same from the `enabled` prop, a restoration of the previous `@ConditionalOnProperty` guard.

**Comment by philwebb** [comment]
I originally wanted to drop the `enabled` properties entirely and just rely on the usual auto-configure exclude mechanisms. Unfortunately that wasn't possible because the property is needed by micrometer itself.
