### ISSUE TITLE
Add Automatic-Module-Name to manifest

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11994]
Spring Framework does this but I don't think we do as yet.

**Comment by philwebb** [comment]
See [this framework commit](https://github.com/spring-projects/spring-framework/commit/80134d2e0cbb71255f6b04046b4d5be71548d00a)

**Comment by eddumelendez** [comment]
See [this commit in spring-data](https://github.com/spring-projects/spring-data-build/commit/89be042b60786cfbac99e6cd4a7114fef09822dc#diff-04dc5d029560773ac79faaf3da0fbb22)

**Comment by philwebb** [comment]
Thanks. I think I can use the regex helper to automate it.
