### ISSUE TITLE
BasicJsonParser parse string that only contains digit as long 

### ISSUE THREAD

**Issue by Narcissu5** [spring-projects/spring-boot#11992]
https://github.com/spring-projects/spring-boot/blob/5e0df39c660c41709a2baaefa5158c5845feef46/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/json/BasicJsonParser.java#L114

```java
BasicJsonParser parser = new BasicJsonParser();
Map<String, Object> map = parser.parseMap("{\"name\": \"11111\"}");
```
The entry is  String->Long

**Comment by philwebb** [comment]
Adding the following to `AbstractJsonParserTests` shows the problem.

```java
	@Test
	public void stringContainingNumber() {
		Map<String, Object> map = this.parser.parseMap("{\"foo\":\"123\"}");
		assertThat(map).hasSize(1);
		assertThat(map.get("foo")).isEqualTo("123");
	}
```

**Comment by snicoll** [comment]
The Javadoc of `BasicJsonParser` states

> Comes with some limitations with respect to the JSON specification (e.g. only supports String values),
