### ISSUE TITLE
Resource filtering default configuration and documentation is error prone

### ISSUE THREAD

**Issue by alanfranz** [spring-projects/spring-boot#1199]
I think there're a couple of issues with the default configuration of the maven-resources-plugin within **spring-boot-starter-parent**; I'll be glad to contribute a pull request (I suppose it'll land in 1.2 since it might be a non-retrocompatible change) if you think this makes sense.
- The maven-resources-plugin when using spring-boot-starter-parent sports the default configuration, which leads to a filtering of ${...} values that exist at compile time in resources; e.g. I had an issue where ${java.home} , which I was using in application.properties, was filtered with the build box variable rather than being filled at runtime (which is what I wanted).

Proposed solution: use a different default configuration for maven-resources-plugin, limiting the compile-time filtering delimiter to '@', something like

``` xml
<plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-resources-plugin</artifactId>
                 <version>2.6</version>
                 <configuration>
                     <encoding>UTF-8</encoding>
                     <delimiters>
                         <delimiter>@</delimiter>
                     </delimiters>
                     <useDefaultDelimiters>false</useDefaultDelimiters>
                 </configuration>
</plugin>      
```
- The default resources filtering in spring-boot-starter-parent only applies to _application.yml_ and _application.properties_. This can lead to unpredictable results when using profiles: application.properties would be filtered, while application-profile.properties would not.

Proposed solution: filter application-\* files as well.
- The documentation at [58.3](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-short-command-line-arguments) is a bit misleading, saying that

<pre>
If you have enabled maven filtering for the application.properties you may want to avoid using ${*} for the tokens to filter as it conflicts with those placeholders. You can either use @*@ (i.e. @maven.token@ instead of ${maven.token}) or you can configure the maven-resources-plugin to use other delimiters.
</pre>

The suggestion is fine (it's what I did in the implementation) but it would suggest that resources filtering is **not** enabled by default, while it is indeed.

Proposed solution: change the docs to reflect what actually happens when filtering.

Of course this whole issue could be solved by completely disabling resource filtering in spring-boot-starter-parent.

Let me know what you think about that.

**Comment by ericdahl** [comment]
This ticket and the docs suggest that `${*}` was disabled. It doesn't look to be the case. The `maven-resources-plugin` seems like it would have to also be configured with 
```xml
<useDefaultDelimiters>false</useDefaultDelimiters>
```
Without that setting, it seems that the plugin is adding the default delimiters (`${*}` and '`@`) to the defined delimiters (`@`). (Not what I'd expect the plugin to do..)

**Comment by wilkinsona** [comment]
@ericdahl It's not clear to me if you have found an actual problem or if you are talking theoretically. Note that Maven's docs state that the configuration we've specifies the "default filtering delimiters". If you have found an actual problem then please open a new issue (this one is closed), with a sample that reproduced it.

**Comment by ericdahl** [comment]
@wilkinsona 
It's more theoretical. The `${*}` delimiter still works so nothing is broken. It seems that it was intended to be removed (this issue mentions "breaking change" in reference to removing it). I can dig deeper and create an issue this weekend.

**Comment by ericdahl** [comment]
@wilkinsona 

I was going to write up a issue for this but https://github.com/spring-projects/spring-boot/issues/3092 already exists for this issue. 

There seems to be confusion about how the plugin works. The `<useDefaultDelimiters>false</useDefaultDelimiters>` is necessary to cause `${}` to be disabled. Without this, maven is processing variables at build-time that I'd rather have evaluated at run-time by Spring's property evaluation.

**Comment by neblina-software** [comment]
Im using with: 

application-dev.yml
spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/balerocms_enterprise?useUnicode=yes&characterEncoding=UTF-8
        databaseName:
        serverName:
        username: @db.user@

pom.xml
            <properties>
                <db.user>root</db.user>
            </properties>

Im using Java 8, and it says:

objc[1577]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Exception in thread "main" while scanning for the next token
found character @ '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 7, column 19:

Any comments?

**Comment by wilkinsona** [comment]
@neblina-software This issue's closed and you haven't provided enough information to diagnose the problem. If you believe you have found a bug please open a new issue describing the version of Spring Boot, Maven etc that you're using and how to recreate the problem.

**Comment by joshiste** [comment]
@neblina-software try setting `<addResources>false</addResoruces>` for the pring-boot-maven-plugin. See the hint in http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-application-info-automatic-expansion

**Comment by neblina-software** [comment]
I think its a bug, im going to create the issue.

The problem is, spring boot it's not creating and copying *.properties files to target/ folder.

It only create when execute:

$ mvn test

and not when executing:

$ mvn spring-boot:run -P prod

im using:

https://github.com/neblina-software/balerocms-enterprise
