### ISSUE TITLE
Allow extension of ConcurrentKafkaListenerContainerFactoryConfigurer

### ISSUE THREAD

**Issue by maciekpapiez** [spring-projects/spring-boot#12003]
I'm trying to extend the Spring Boot Kafka's auto-configuration (e.g. handling `spring.kafka.*` properties) by some custom settings, such as:
* my own `RetryTemplate`
* my own `ErrorHandler`

Ideally, such snippet would be possible:

```java
public class CustomKafkaConfigurer extends ConcurrentKafkaListenerContainerFactoryConfigurer {

    private final ErrorHandler errorHandler;

    private final RetryTemplate retryTemplate;

    public CustomKafkaConfigurer(KafkaProperties properties, ErrorHandler errorHandler, RetryTemplate retryTemplate) {
        setKafkaProperties(properties);
        this.errorHandler = errorHandler;
        this.retryTemplate = retryTemplate;
    }

    public void configure(ConcurrentKafkaListenerContainerFactory<Object, Object> listenerContainerFactory, ConsumerFactory<Object, Object> consumerFactory) {
        super.configure(listenerContainerFactory, consumerFactory);
        listenerContainerFactory.setRetryTemplate(retryTemplate);
        listenerContainerFactory.getContainerProperties().setErrorHandler(errorHandler);
    }

}
```

However, the `setKafkaProperties` method is package-private, which blocks the scenario above (unless one wants to make some dirty hacks).

My suggestions (choose one):
* change the setter method scope to `public`,
* create a `ConcurrentKafkaListenerContainerFactoryConfigurer` interface, the current class being one of its implementations (as suggested here: https://stackoverflow.com/questions/47862458/how-to-set-a-custom-consumer-task-executor-for-spring-kafka-when-using-auto-con#comment82773807_47870184),
* add some other plug-in point so that one can extend the auto-configuration (no necessarily modifying it).

**Comment by garyrussell** [comment]
I have a similar PR for customizing the RabbitMQ RetryTemplate: https://github.com/spring-projects/spring-boot/pull/11697

After discussion with @snicoll , I believe [he prefers a `...Customizer` infterface](https://github.com/spring-projects/spring-boot/pull/11683#discussion_r162587894), which is injected into the configurer (if present). The configurer then calls the customizer to perform further customization.

**Comment by philwebb** [comment]
@pkostrzewa Any issue tagged with `ideal-for-contribution` is fair game.

**Comment by philwebb** [comment]
Closing in favor of PR #12018
