### ISSUE TITLE
Favicon is not secured

### ISSUE THREAD

**Issue by mastersimon** [spring-projects/spring-boot#12002]
It seems like that the favicon (http://localhost:8080/favicon.ico) is not secured if you enable basic auth or oauth. With the default favicon, your service is exposing sensitive information to the outside of the world which you do not want to expose.

Temporary solution could be to disable the favicon if you have a pure backend application running by adding the following to your application.properties:

**spring.mvc.favicon.enabled=false**

**Comment by wilkinsona** [comment]
This behaviour is intentional and [documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security):

> The basic features you get out of the box in a web application are:
> …
> - Ignored (insecure) paths for common static resource locations (`/css/**`, `/js/**`, `/images/**`, `/webjars/**` and `**/favicon.ico`).
