### ISSUE TITLE
SpringApplicationEvent when application is stopping

### ISSUE THREAD

**Issue by LudovitVarga** [spring-projects/spring-boot#12024]
Scenario:
I have component that has start() and stop() methods. Start method should be called when application is fully started. Stop method should be called when application is going to stop, for example termination with SIGINT from terminal, but before context is stopped or closed.

In my case I have save() method with @EventListener(classes = ApplicationReadyEvent.class) annotation. Close() method is annotated by @PreDestroy. This is mixed approach and it does not looks good.

It is possible to create event that will be fired when application is stopping?

**Comment by wilkinsona** [comment]
We don't have complete control over the `ApplicationContext` implementation that a Spring Boot application uses so there isn't a hook point for us to publish a custom `SpringApplicationEvent` when the context is being closed. I think you should use Spring Framework's `ContextClosedEvent` for this purpose. It's published very early in context close processing, before beans are destroyed etc.
