### ISSUE TITLE
Support adding optional URL parameter in Spring Boot 2 EndPoints

### ISSUE THREAD

**Issue by doronl** [spring-projects/spring-boot#12020]
Hi,
  We wanted to use the new `@EndPoint` annotation but when we planned to add a `@ReadOperation` that excepts an optional parameter we found no solution in current implementation! 
1. The `@Selector` annotation extends the URL with another part. 
2. No annotation on the parameter makes the parameter mandatory and a call to the endpoint without it will be ignored!

We need something like `@RequestParam(required = false)`, or else we **can't use this all** as it is breaking the API contract .

Thanks

**Comment by wilkinsona** [comment]
You can use `@Nullable` on a parameter to make it optional. See the [audit events endpoint](https://github.com/spring-projects/spring-boot/blob/114ece56b8cae8928718118ba37b0eedb08c4ec7/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/audit/AuditEventsEndpoint.java#L44-L45) for an example.

#10001 if tracking the documentation of the new endpoint infrastructure.

**Comment by doronl** [comment]
OK, Thanks, that did the job.
