### ISSUE TITLE
Remove our Narayana auto-configuration in favor of their own support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12026]
We currently have auto-configuration and starters for three JTA implementations:

- Atomikos
- Bitronix
- Narayana

Looking at Maven Central download numbers for the starters and project creation on start.spring.io, I don't think their usage justifies the ongoing maintenance cost. This is particularly true for Narayana where the maintenance cost has been higher than for Atomikos and Bitronix.

In addition to the usage being low, relatively speaking it's dropping. In February 2017, 0.76% of projects generated on start.spring.io used one of the three JTA options. In January 2018, that'd dropped to 0.41%.

There has been some discussion in the past about Narayana's auto-configuration being maintained externally. That's largely been driven by different release cadences. The request by @gytis to make [these changes](https://github.com/spring-projects/spring-boot/pull/12000) in 1.5.x is the latest example of this.

2.0 is the ideal opportunity to drop the starters and auto-configuration. I think we should take it.

**Comment by snicoll** [comment]
Dropping JTA support from the core would remove quite a lot of complexity so that's a good thing but  I am afraid we're a bit  late to do this. How about acking the drop in 2.1? implementations that are willing to keep Spring Boot support can take the auto-configuration code (and starter) on their side.

**Comment by philwebb** [comment]
I agree with @snicoll that it's a bit late to drop support entirely in 2.0, especially as we'd really need to find a new home for the existing code.

**Comment by gytis** [comment]
I've moved the Narayana integration code to a separate project: https://github.com/snowdrop/spring-boot-narayana. I've split the starter into two as the JMS and JDBC wrappers were moved to a different package for Spring Boot 2.0. 
It is configured before the JTA configuration located in Spring Boot code base (https://github.com/snowdrop/spring-boot-narayana/blob/master/spring-boot-1-narayana-starter/src/main/java/me/snowdrop/boot/narayana/SpringBoot1NarayanaConfiguration.java#L69) so it can work without removing original transaction integrations.
If you guys agree, we could initially replace it in start.spring.io and eventually when it is convenient to you, you could remove the code too.

**Comment by snicoll** [comment]
@gytis thanks for sharing. I've opened [3 issues in that repo](https://github.com/snowdrop/spring-boot-narayana/issues), could you please have a look?

**Comment by gytis** [comment]
@snicoll thanks for your suggestions. I've refactored [narayana-spring-boot](https://github.com/snowdrop/narayana-spring-boot) based on your comments. 1.0.x branch is compatible with Spring Boot 1.5.x and 2.0.x branch (at the moment as master) is compatible with Spring Boot 2.0.x. I also did first release for each: 1.0.0 and 2.0.0.

**Comment by sgrillon14** [comment]
@gytis , version 2.1.1.RELEASE do not on Maven Central: https://search.maven.org/search?q=g:me.snowdrop%20AND%20a:narayana-spring-boot-starter

**Comment by snicoll** [comment]
@sgrillon14 please stop commenting on unrelated issues? The Narayana support has been moved outside of Spring Boot [as documented in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#narayana-jta-support).
