### ISSUE TITLE
Update Release notes for on Wiki to describe support for upcoming Java 10

### ISSUE THREAD

**Issue by kibbled** [spring-projects/spring-boot#12027]
Current documentation makes no reference to Java 10, it would be convenient if the release notes and documentation was updated to reference compatibility or support for Java 10 since it will probably be release around the same time as Spring Boot 2.0.

**Comment by wilkinsona** [comment]
Java 10 isn't officially supported at this time. I've pushed an update to the reference documentation to hopefully make it clearer that we support Java 8 and 9. It's also [mentioned](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#java-8-baseline) in the release notes.
