### ISSUE TITLE
Embedded Tomcat fails to start when configured to use SSL session tracking

### ISSUE THREAD

**Issue by mast76** [spring-projects/spring-boot#12058]
I have been experimenting with session tracking by SSL in a SpringBoot application, by using the application property **server.session.tracking-modes=ssl**.

See https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/common-application-properties.html

SSL is already working in the application. But when I set tracking mode to SSL, SpringBoot fails to start with an

    Caused by java.lang.IllegalArgumentException: The session tracking mode SSL requested for context  is not supported by that context

Step debugging reveals that populateSessionTrackingModes() in
https://github.com/apache/tomcat/blob/TOMCAT_9_0_5/java/org/apache/catalina/core/ApplicationContext.java has this code:

**ApplicationContext at line 1011**

    // SSL not enabled by default as it can only used on its own
    // Context > Host > Engine > Service
    Service s = ((Engine) context.getParent().getParent()).getService();
    Connector[] connectors = s.findConnectors();
    // Need at least one SSL enabled connector to use the SSL session ID.
    for (Connector connector : connectors) {
        if (Boolean.TRUE.equals(connector.getAttribute("SSLEnabled"))) {
           supportedSessionTrackingModes.add(SessionTrackingMode.SSL);
           break;
        }
    }

This code makes perfect sense not to allow SSL tracking without an SSL connector.

But initialize() in
https://github.com/joansmith/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/tomcat/TomcatEmbeddedServletContainer.java seems to break it by a single line of code:

**TomcatEmbeddedServletContainer at line 85**

    // Remove service connectors to that protocol binding doesn't happen yet
	removeServiceConnectors();

This code is run before the code in ApplicationContext, and it seems to explain why there are no connectors at all when the check for an SSL enabled connector is performed.

I believe this very well could be why session tracking by SSL fails.

**Comment by wilkinsona** [comment]
Thanks for the detailed report. I see that you've linked to Tomcat 9 source and Spring Boot doesn't support Tomcat 9. Does the problem also occur with 8.5?

**Comment by mast76** [comment]
Yes I first discovered the issue in Spring Boot 1.5.3 which uses tomcat-embed-core-8.5.15.jar
