### ISSUE TITLE
Proposition of a component-based UI framework

### ISSUE THREAD

**Issue by dsu** [spring-projects/spring-boot#12067]
I want to ask for an opinion about the concept of a lightweight component-based framework. It is meant to work in Spring Boot environment. Does it present any value to you?
[ Please check project's description and code on GitHub](https://github.com/dsu/SpringUi)

**Comment by wilkinsona** [comment]
Thanks for bringing the project to our attention, but a GitHub issue isn’t really the right place for this sort of thing. You may want to chat about it with the Spring Boot community [on Gitter](https://gitter.im/spring-projects/spring-boot). Good luck.
