### ISSUE TITLE
spring.datasource.hikari.* properties ignored in Spring Boot 2.0.0.RC1

### ISSUE THREAD

**Issue by christophe-f** [spring-projects/spring-boot#12063]
After upgrading to Spring Boot 2.0.0.RC1 from 1.5.10, the Hikari properties are ignored.

**Comment by snicoll** [comment]
@christophe-f you'll have to share a sample that reproduces the problem you  are describing. This behaviour is tested and I don't see how it would "ignore" them as you state.

**Comment by christophe-f** [comment]
This is the configuration:

spring:
  datasource:
    hikari:
      maximum-pool-size: 7

At startup the database gets 10 connections which is the default value.

**Comment by snicoll** [comment]
@christophe-f that's not a sample. Please share something that we can run, ideally showing the difference between `1.5.x` and `2.0.x`.

**Comment by christophe-f** [comment]
@snicoll My bad, after building a quick sample, it is working fine.

The issue is when the app is deployed on PWS. Using the spring.datasource properties works very well. Using the service bindings (in my case elephantsql) will ignore the properties. 

I have switched to the properties.

**Comment by snicoll** [comment]
If you're using Spring Cloud connector, you may want to report that issue so that it's fixed rather than switching to properties, ping @scottfrederick

**Comment by michael-simons** [comment]
I have the same problem with euregjug.eu on Pivotal CF. It's reproducible, but I am not sure wether I should open a ticket for the Java-Build-Pack or elsewhere.

**Comment by snicoll** [comment]
@michael-simons depends if you're using spring cloud services or not. But please report an issue and add a reference to this issue. Thanks!
