### ISSUE TITLE
Upgrade to Plexus Utils 3.0.24

### ISSUE THREAD

**Issue by fredsjones** [spring-projects/spring-boot#12065]
In our exploration of your project we found that it is currently using version 3.0.20 of plexus-utils which is vulnerable to Directory Traversal.

Recommendation:

Upgrade the version of plexus-utils in the pom.xml to version 3.0.24 or higher.

For additional details on this vulnerability you can visit the following websites:
Snyk: https://snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-31521

**Comment by wilkinsona** [comment]
Thanks. There's no harm in upgrading, but I don't think there's a vulnerability here. Plexus Utils is only used by Spring Boot's Maven plugin and it's only usage of it is a call to `CommandLineUtils.translateCommandline(String)`
