### ISSUE TITLE
Better systemd integration

### ISSUE THREAD

**Issue by jpmsilva** [spring-projects/spring-boot#12074]
I recently extracted a module from a toy project of mine that could perhaps benefit more people.
It is a Spring Boot starter to provide better integration with SystemD under Linux.
Services built on top of Spring Boot can better behave as units using the SystemD notify protocol.

My question is if you feel that there is interest in providing this as one of the built-in starters, in which case I would donate all the code and work on a pull request with more documentation, proper code style, tests and whatever else you think would be appropriate.

The code is unreleased at this point, but available in [GitHub](https://github.com/jpmsilva/jsystemd), should you like to review it.

Apologies beforehand if this is not the correct route to raise this, and feel free to close it if unwanted.

**Comment by candrews** [comment]
FWIW, I love this idea!

Small critique: it's "systemd" not "SystemD" - https://www.freedesktop.org/wiki/Software/systemd/

**Comment by wilkinsona** [comment]
Thanks for raising this, @jpmsilva. My initial reaction is that this looks excellent and useful. However, I am not sure that the Spring Boot team have sufficient knowledge of systemd to maintain this functionality. I know I certainly don't. Let's see what the rest of the team thinks, but it feels to me like this may be better maintained as a third-party starter as you are currently doing.

**Comment by philwebb** [comment]
Thanks for the suggestion @jpmsilva, but after some discussion we've decided that it would be best to continue this as an external project.

Our existing startup script support already causes quite a maintenance burden for us and we're worried that deeper integration with systemd will add to that. We'd be happy to add the project to the list of 3rd-party starters, and we're also happy to make any changes to the core if you need more integration hook points.

Thanks again for the suggestion and for developing the integration!
