### ISSUE TITLE
@ConditionalOnProperty not working on Stream Listener

### ISSUE THREAD

**Issue by dhruvpanwar95** [spring-projects/spring-boot#12076]
```
@ConfigurationProperties
public class OrderStreamConfiguration {
	private final Log logger = LogFactory.getLog(getClass());

          @ConditionalOnProperty(prefix="prop",name="active", matchIfMissing = true)
           @StreamListener(value = OrderProcessor.INPUT)
	   public void processOrder(Event event) {
       }
}
```

However,it is still listening if I set prop.active=false.If I move `@ConditionalOnProperty` to class,then it works fine.But I want multiple stream listeners in one class.So,I would need this property on `@StreamListener`.

**Comment by wilkinsona** [comment]
Conditions, including `@ConditionalOnProperty` only affect the registration of beans in the application context. Your `processOrder` method isn't defining a bean so `@ConditionalOnProperty` has no effect.

If you'd like property-based support for enabling and disabling stream listeners, you'll have to raise it with Spring Cloud Stream. FWIW, I don't think that `@ConditionalOnProperty` should be used.
