### ISSUE TITLE
Shouldn't SpringApplicationAdminMXBeanRegistrar.SpringApplicationAdmin.shutdown() delegate to SpringApplication.exit()?

### ISSUE THREAD

**Issue by klr8** [spring-projects/spring-boot#12072]
Currently SpringApplicationAdminMXBeanRegistrar.SpringApplicationAdmin.shutdown() simply does the following:
`SpringApplicationAdminMXBeanRegistrar.this.applicationContext.close();`

Wouldn't it be more consistent to instead delegate to SpringApplication.exit() like so:
`SpringApplication.exit(SpringApplicationAdminMXBeanRegistrar.this.applicationContext)`

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, we can't tell if it would be more consistent to call `SpringApplication.exit()` as that's something that's only done in user code. Calling close on the context, as we currently do, is consistent with what will happen if the application is closed via the shutdown hook in response to SIGTERM.

**Comment by klr8** [comment]
Okay. Thanks for the quick response!
