### ISSUE TITLE
Provide a 'parsable' details information about 'predicate' in handler mapping

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#12080]
Following on discussion here: https://github.com/spring-projects/spring-boot/issues/11864

The actuator returns information about handler mappings that contain information like the following:

```
            "predicate" : "{[/actuator/mappings],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}",
```

It is unclear what the predicate string's format is. It vaguely reminds of json but isn't parsable by a json parser. 

It would be good to 'explode' this information into a parsable json object under details in a similar way as was done for the 'handlerMethod' in #11864.

Maybe something like:

```
"predicateDetails": {
    "requestPath" : "/actuator/mappings",
    "requestMethods": [ "GET" ],
    "produces": [ "application/vnd.spring-boot.actuator.v2+json",  "application/json" ]
}
```

Feel free to rearange or rename these attributes to fit with your sense of esthetics.

We are mostly interested in extracting the 'requestPath' information from the predicate. But the requestMethods and content types seem also potentially useful.

It would be good if the predicate information was made available reliably and independent/irrespective of the different handler types (since it seems generally independent of how the request is being handled).

**Comment by philwebb** [comment]
That looks like the `toString` of `RequestMappingInfo`.

**Comment by philwebb** [comment]
I've put this on RC2 in the hope we can get to it. If we can't I'd rather drop the attribute altogether.

**Comment by kdvolder** [comment]
> If we can't I'd rather drop the attribute altogether.

Please don't. We are already using that information to extract the request path 'as best as we can' removing the attribute will break some STS functionality with Boot 2.0. Even slightly tweaking the format might break us as we use some hacky `String.indexOf('[')` to try and find the path in there.

I was thinking you just leave the existing attribute the way it is and add something 'parseable' under 'details' just like in #11864.

**Comment by kdvolder** [comment]
Note: There is also examples where predicate takes this form:

```
            "predicate" : "/**/favicon.ico"
```

Here it has a path only. But none of the other attributes. From our point of view it would be nice if the 'path' was allways there and the other infos like 'content types' and 'request method' where added optionally when applicable. (I know you dislike optional attributes, but given these two examples, it seems the most natural approach to me).

Note 2: I have also in the past seen examples where 'predicate' (though used to be found as a key if map then how it is now) had something lke this:

```
   "predicate": "/mappings || /mappings.json"
```

Haven't seen those examples in Boot 2.0 example projects, but I don't know if that's just because this is no longer possible, or because it is no longer present in initializer generated projects due to some internal restructurings in Boot 2.0.

Anyway, if stuff like 'one-path || other-path' is still possible then perhaps predicate details should make the path a list instead of a single string. So like this:

```
"predicateDetails": {
    "requestPaths" : [ "/actuator/mappings", "/actuator/mappings.json"],
    "requestMethods": [ "GET" ],
    "produces": [ "application/vnd.spring-boot.actuator.v2+json",  "application/json" ]
}
```

And the favicon example would be:

```
"predicateDetails": {
    "requestPaths" : ["/**/favicon.ico"],
}
```

**Comment by wilkinsona** [comment]
We have multiple types of predicates to deal with so we need something more specialised than `predicateDetails`.

Here's a (rather contrived) `@RequestMapping`:

```
@PostMapping(path = "/", consumes = { MediaType.APPLICATION_JSON_VALUE,
			"!application/xml" }, produces = MediaType.TEXT_PLAIN_VALUE, headers = "X-Custom=Foo", params = "a!=alpha")
```

And here are the resulting details:

```
"requestMappingConditions": {
    "consumes": [
        {
            "mediaType": "application/json",
            "negated": false
        },
        {
            "mediaType": "application/xml",
            "negated": true
        }
    ],
    "headers": [
        {
            "name": "X-Custom",
            "negated": false,
            "value": "Foo"
        }
    ],
    "methods": [
        "POST"
    ],
    "params": [
        {
            "name": "a",
            "negated": true,
            "value": "alpha"
        }
    ],
    "patterns": [
        "/"
    ],
    "produces": [
        {
            "mediaType": "text/plain",
            "negated": false
        }
    ]
}
```

This works, and will produce the same structure, with both MVC and WebFlux.

**Comment by kdvolder** [comment]
@wilkinsona That looks good. And it is a lot more info than we probably need at the moment, but it all looks potentially useful. 

 I assume that none of these attributes are 'optional', but they might be instead bound to `[]` if 'not applicable' ?

Allthough... if so I have to wonder what something like:

```
"methods" : [] 
```

... would mean. (One 'logical' interpretation is that it accepts no request methods, since the list of accepted types is empty).

**Comment by wilkinsona** [comment]
Every item shown in the example is always applicable. We're dealing specifically with `RequestMappingInfo` which, in both MVC and WebFlux, always has all of the conditions that we now describe. This is one of the benefits of making each piece of the details describe a specific thing.

What it means when one of the lists is empty is down to the behaviour of Spring MVC and WebFlux. For methods, both treat an empty list as meaning unconstrained and the mapping will handle requests with any method. I think all the others behave in the same way.
