### ISSUE TITLE
reactive.ServletServerHttpRequest in Tomcat embedded does not return getSslInfo

### ISSUE THREAD

**Issue by vogthenn** [spring-projects/spring-boot#12084]
Bug report

Spring-Boot 2.0.0 RC1

Module: spring-web

Configuration: Tomcat Embedded, with two-way-ssl enabled

class org.springframework.http.server.reactive.ServletServerHttpRequest, in method initSslInfo()

Instead of java.security.cert.X509Certificate it should read the attribute  javax.servlet.request.X509Certificate to return the certificate.  This is statet here https://tomcat.apache.org/tomcat-8.5-doc/servletapi/javax/servlet/ServletRequest.html and https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html

I think it's safe, just to rename this.

**Comment by bclozel** [comment]
This class belongs to Spring Framework. This is the Spring Boot issue tracker.

Could you open an issue on jira.spring.io?

**Comment by vogthenn** [comment]
Thanks, see https://jira.spring.io/browse/SPR-16507
