### ISSUE TITLE
Please bump artemis.version to 2.x

### ISSUE THREAD

**Issue by bigon** [spring-projects/spring-boot#12093]
Hi,

Are there any reasons that artemis.version is still set in 1.5.5 for spring-boot 1.x?

artemis-jms-client 1.5.5 is not working properly with jboss-amq 7.0.3 (message load balancing issues mainly)

**Comment by wilkinsona** [comment]
We've already upgrade to 2.x in master (Spring Boot 2.0). We can't jump to a new major version of Artemis in a minor or maintenance release of Spring Boot so 1.5.x will continue to use Artemis 1.5.x.
