### ISSUE TITLE
Add ApplicationConversionService and fix binder

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12095]
Our subverting of the `ConversionService` for the binder should be refactored. Specifically we should try to drop `PropertyEditorConverter` and align with what the framework does.

**Comment by snicoll** [comment]
ping @jhoeller

**Comment by philwebb** [comment]
The `BinderConversionService` in general is a bit of a mess since it does all this fallback stuff and wacks in extra converters. We also use it in `OAuth2ClientPropertiesRegistrationAdapter` and the endpoint `ConversionServiceParameterValueMapper` which is a bit odd. I'm trying to extract a `ApplicationConversionService` that is a bit like `DefaultFormattingConversionService` in the framework but with the extra convertors that we need.

**Comment by philwebb** [comment]
Reopening since to fix doc comments and possibly add another constructor.

**Comment by shakuzen** [comment]
Was the rename of `DefaultDurationUnit` back to `DurationUnit` intentional? It wasn't mentioned in the commit message or RC2 release notes.

**Comment by philwebb** [comment]
@shakuzen It was intentional, although missing it form the release notes was not. The new `ApplicationConverter` supports printing as well as parsing, so `@DurationUnit` seemed like a better name.
