### ISSUE TITLE
Need compatibility chart for Spring Boot Gradle plugin with Gradle version

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#12097]
Gradle 4 introduces a completely new model of dependency management, as documented [here](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph). It appears that Spring Boot Gradle plugin 1.5.3 doesn't correctly work with builds using the new Gradle configurations. Even though a dependency is specified in `implementation`, it needs to be duplicated in `runtime`, otherwise we get a `ClassNotFoundException` at runtime when running the uber jar. Also, using `runtimeOnly` instead of `runtime` causes similar `ClassNotFoundException`.

This ticket is to have a compatibility chart in the documentation showing what version of the Boot plugin is supposed to work with what versions of Gradle. Without that, it seems like a c*apshoot, where the plugin may or may not work depending on the project configuration.

**Comment by wilkinsona** [comment]
Spring Boot 1.5.x supports Gradle 2 (2.9 or later) and 3. This is already described in the [system requirements](https://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#getting-started-system-requirements). Spring Boot 2 [supports Gradle 4](https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#getting-started-system-requirements).

**Comment by asarkar** [comment]
@wilkinsona I'd missed that little note regarding Gradle. Can we have a nice table like the one for servlet containers?

**Comment by wilkinsona** [comment]
Yes, I guess we could add a table of the supported build systems and the versions we support.

**Comment by wakingrufus** [comment]
Spring boot 1.4.x does not work with gradle 4.x

**Comment by philwebb** [comment]
@wakingrufus Spring Boot 1.4 is end of life. Please upgrade to Spring Boot 2.0 if you can.

**Comment by philwebb** [comment]
@wakingrufus 1.5 is still supported if that's an easier option for you.

**Comment by wilkinsona** [comment]
Although please be aware that Boot 1.5 doesn’t officially support Gradle 4 either.

**Comment by edeesis** [comment]
I ran into this recently as well with regards to implementation dependencies.

My workaround was to set the Spring boot plugin's customConfiguration to runtimeClasspath - which includes implementation and runtime dependencies.

```
springBoot {
    customConfiguration = configurations.runtimeClasspath.name
}
```

**Comment by wilkinsona** [comment]
Closing in favour of PR #14002.

**Comment by arutsudar** [comment]
As per [Spring Docs](https://docs.spring.io/spring-boot/docs/), below is a table which shows which version of gradle or maven to use for the corresponding Spring Boot version.

Spring   Boot version | Maven version | Gradle version
-- | -- | --
2.2.x | 3.3+ | 5.x (4.10 is also supported but in a deprecated form)
2.1.x | 3.3+ | 4.4+
2.0.x | 3.2+ | 4.x
1.5.x | 3.2+ | 2.9 or 3.x
1.4.x | 3.2+ | 1.12 or 2.x
1.3.x | 3.2+ | 1.12 or 2.x
1.2.x | 3.2+ | 1.12 or 2.x
1.1.x | 3.0+ | 1.6+
1.0.x | 3.0+ | 1.6+
0.0.x | 3.0+ | 1.6+

**Comment by FyiurAmron** [comment]
FYI, Gradle 8.x requires Spring Boot at least 2.7.10 , as per official docs (in my case, `bootRun` disappeared for older version ;)
