### ISSUE TITLE
Trace Response has parameters field empty for POST Request?

### ISSUE THREAD

**Issue by gsamartian** [spring-projects/spring-boot#12099]
I am using **Spring boot 1.5.10.RELEASE.**

I am trying to view the trace of requests using actuator /trace endpoint.

For **GET** Requests, I see the parameters/query string rendered in **/trace** response.

But, for **POST** Requests, I see parameters field as empty in the response.

Is there any reason why POST Payload's are not being rendered. 

I am not sure if it is a supported feature or a bug.  If there is a way to render the POST Request Body, please let me know how I can achieve that.

If you need a project to reproduce the issue, please let me know and I can share the code I reproduced for this issue.

I apologize If this is not the right forum for these issues, please let me know. and will try to address the issue elsewhere.

**Comment by bclozel** [comment]
This is already supported through configuration properties:

```properties
management.trace.include=request-headers,response-headers,cookies,errors,parameters
```

See the [`TraceProperties`](https://github.com/spring-projects/spring-boot/blob/v1.5.10.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/TraceProperties.java) class for all possible values.

Note that doing some has a performance impact since Spring Boot needs to read incoming parameters to do that.

Duplicates #3948 and #2458

**Comment by gsamartian** [comment]
I am able to reproduce the issue even after adding the configuration properties you had provided in application configuration.


As per #3948 there are some new configuration properties which will be added like **payload** and **payload_response.**

I even tried to add **payload,payload_response** in both lower and upper cases to the application configuration for management.trace.include, but got error as invalid field configuration.

These fields are not even part of the enum in ,
https://github.com/spring-projects/spring-boot/blob/v1.5.10.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/TraceProperties.java

I have shared the project which reproduces this.
https://github.com/gsamartian/demo-service

The configurations I used are part of the application.yml and the error I obtained at startup is in errorlog.txt.

So, I feel either this is unsupported or it is a bug.

**Comment by bclozel** [comment]
Ouch, sorry @gsamartian. I thought your initial comment was about request parameters (as in form data).

Tracing the complete request payload is indeed unsupported, for [the reasons listed in this comment on the original PR](https://github.com/spring-projects/spring-boot/pull/3948#issuecomment-148185425). The `payload` and `payload_response` configuration options are not supported, so your repro project behaves as expected.

If you think the reasons listed for not supporting this are wrong, please comment here and explain how you think this could be achieved. We can then discuss this feature and give this a second look.

Thanks!
