### ISSUE TITLE
Add org.apache.httpcomponents:fluent-hc in spring-boot-dependencies pom.xml

### ISSUE THREAD

**Issue by sbraconnier** [spring-projects/spring-boot#12107]
I use Spring Boot dependencies management in my project, which uses some org.apache.httpcomponents denpendencies. Here's my proposal:

Since the org.apache.httpcomponents:httpclient dependency is provided by Spring Boot, it would be nice if the org.apache.httpcomponents:fluent-hc was provided too, since it uses the same version as httpclient (same as httpmime, which is provided by Spring Boot).

Thanks.

**Comment by bclozel** [comment]
It seems this dependency only provides a fluent API for using directly the Apache HttpClient.
Personally, I don't think we should add that dependency as we ship HttpClient dependencies mainly to be used with `RestTemplate` and not directly.

Looking at the linked issue, couldn't you just use the `httpclient.version` version in your dependency management? (I'm not sure I really get the whole context here, maybe @snicoll can help).

**Comment by sbraconnier** [comment]
I find it perfectly ok to use the httpclient.version in my project (a spring boot starter using http-client and fluent-hc). The thing is that I was unable to use the `httpclient.version` property in the dependency management configuration. I finally got it working this way:

```
dependencyManagement {
  imports {
    mavenBom 'org.springframework.boot:spring-boot-dependencies:1.5.10.RELEASE'
  }
  def httpclient_version = managedVersions['org.apache.httpcomponents:httpclient']
  dependencies {
    dependency "org.apache.httpcomponents:fluent-hc:$httpclient_version"
  }
}
```
Is there a better way to do this ? 

Whatever the answer is, this issue can be closed.

**Comment by wilkinsona** [comment]
We try to provide dependency management for all of the modules in a library that are tagged and released together. `fluent-ac` is [tagged and released alongside `httpclient`](https://svn.apache.org/repos/asf/httpcomponents/httpclient/tags/4.5.3/) so the dependency management that we currently provide is incomplete. We should add `fluent-ac`.

**Comment by snicoll** [comment]
@bclozel no particular context, one thing lead to another.
