### ISSUE TITLE
http://repo.spring.io/ is down

### ISSUE THREAD

**Issue by sedrakpc** [spring-projects/spring-boot#12105]

**Comment by wilkinsona** [comment]
Thanks, but isn’t something that the Spring Boot team can fix. Someone has [already told ops](https://twitter.com/ifrins/status/965183787742187520).

**Comment by sebasira** [comment]
Sorry to bother here. I know this team cannot fixed as said in the previous message but don't know where else to post it and I don't have a twitter account.

I'm getting 502 as well right now since several minutes ago

**Comment by snicoll** [comment]
@sebasira thank you but this has been reported several times already.

**Comment by wilkinsona** [comment]
Thanks, but there's no need to tell us. Pingdom monitors repo.spring.io for us so we're already aware of the outage.
