### ISSUE TITLE
X-Application-Context Header is not added to all responses

### ISSUE THREAD

**Issue by gbrehmer** [spring-projects/spring-boot#12119]
Because filter-order is not set, e.g. Spring Security filterchain is registered before the ApplicationContextHeaderFilter. If Access is not granted (HTTP 401), X-Application-Context-Header is missing.

**Comment by wilkinsona** [comment]
I'm pretty sure that this is by design so that a detail of the application isn't leaked to unauthorised users. If you want to override the order, you can create a `FilterRegistrationBean` for the auto-configured `ApplicationContextHeaderFilter` and set an order on it:

```java
@Bean
public FilterRegistrationBean applicationContextHeaderFilterRegistration(
		ApplicationContextHeaderFilter filter) {
	FilterRegistrationBean registration = new FilterRegistrationBean(filter);
	registration.setOrder(Ordered.HIGHEST_PRECEDENCE);
	return registration;
}
```

**Comment by gbrehmer** [comment]
Yes by design is possible, but what about resources (like static resources) which are typically available by anonymous access? In those cases the header is also set. We are using this header to provide clients the currently available API version (e.g. to force updates of mobile app clients).
