### ISSUE TITLE
Let configure plain Hibernate to Spring Boot completely just through the application.properties file

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#12123]
Hello

Consider the scenario about do a complete migration from `Spring Framework` to `Spring Boot` and having integration with _plain_ `Hibernate`. Thus a good amount of `@Repositories` working _directly_ with `SessionFactory` exists

Currently is not possible do all this migration to configure with just working with the `application.properties` file, is mandatory work around the following:

```
@Bean
public SessionFactory sessionFactory(EntityManagerFactory emf) {
    return emf.unwrap(SessionFactory.class);
}

@Bean
public PlatformTransactionManager transactionManager(SessionFactory sessionFactory){
    HibernateTransactionManager transactionManager = new HibernateTransactionManager();
    transactionManager.setSessionFactory(sessionFactory);
    return transactionManager;
}
```

and (it is ok)

```
spring.jpa.properties.hibernate.current_session_context_class = 
org.springframework.orm.hibernate5.SpringSessionContext
```

The _enhancement_ I am asking for is configure completely the integration of _plain_ `Hibernate` to `Spring Boot`  just through the `application.properties` file

Let me know your thoughts.

Thanks.

**Comment by philwebb** [comment]
Thanks for the suggestion but I don't think working directly with `SessionFactory` is good practice so it's not something I'd like to support out of the box.
