### ISSUE TITLE
Register ApplicationConversionService for container use

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12148]

**Comment by michael-wirth** [comment]
1+

**Comment by philwebb** [comment]
See also #6222 for issues that users have faced.

**Comment by eximius313** [comment]
Do I understand well, that without fixing this issue I can not use `Duration` in `@Value`  (https://github.com/spring-projects/spring-boot/issues/13237)?

**Comment by wilkinsona** [comment]
@eximius313 Correct.

**Comment by jarekCC** [comment]
I'm also affected by this problem (I`d like to use Duration in properties)

**Comment by eximius313** [comment]
@philwebb - why have you removed it from `2.1.0` milestone? :(

**Comment by snicoll** [comment]
@eximius313 please [read the description of each milestone](https://github.com/spring-projects/spring-boot/milestones), Phil did the exact opposite.

**Comment by eximius313** [comment]
@snicoll so `Backlog` and `Icebox` will be resolved before `2.1.0`?
