### ISSUE TITLE
Exception handlers not triggered sometimes

### ISSUE THREAD

**Issue by satb** [spring-projects/spring-boot#1216]
I have the full description on SO. I am not sure if I have to paste the whole thing here again...if you'd like that please let me know. In essence, I am finding it very difficult to handle exceptions using Spring Boot. 

http://stackoverflow.com/questions/24616700/spring-boot-controlleradvice-exceptionhandler-not-firing-with-put-and-patch-re

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.
