### ISSUE TITLE
Documentation update 54.2.11 StatsD

### ISSUE THREAD

**Issue by anthonyikeda** [spring-projects/spring-boot#12162]
Documentation reporting incorrect configuration values:
https://docs.spring.io/spring-boot/docs/2.0.0.RC2/reference/htmlsingle/#production-ready-metrics-export-statsd

    management.metrics.export.statsd.host=http://statsd.example.com
    management.metrics.export.statsd.port=9125

should drop the "http" from the host:

    management.metrics.export.statsd.host=statsd.example.com
    management.metrics.export.statsd.port=9125

Otherwise the application won't start.

**Comment by snicoll** [comment]
@anthonyikeda good catch, thank you very much!

**Comment by anthonyikeda** [comment]
@snicoll You’re welcome!
