### ISSUE TITLE
Changing between different servers (when using WebFlux) is not possible with 2.0.0.RC2

### ISSUE THREAD

**Issue by violetagg** [spring-projects/spring-boot#12176]
Hi,

[This project](https://github.com/bclozel/webflux-workshop/blob/master/trading-service/pom.xml)  uses Spring WebFlux and Tomcat as a server.

It is working as expected when running with Spring Boot 2.0.0.RC1 i.e. Tomcat server is used and started. When change the project to use Spring Boot 2.0.0.RC2 then Tomcat is not used anymore and Reactor Netty is used.

I tried with the other starters (Jetty/Undertow) it is the same regardless of the fact the there is starter defined in the pom.xml Reactor Netty is used instead of the concrete server.

**Comment by wilkinsona** [comment]
The import ordering in `ReactiveWebServerFactoryAutoConfiguration` is:

1. Netty
2. Tomcat
3. Jetty
4. Undertow

In RC1 it was:

1. Tomcat
2. Jetty
3. Undertow
4. Netty

**Comment by philwebb** [comment]
That was my mistake, I assumed because we use Netty by default that should be the first in line. We should double check the servlet version of that class and add a test for this.
