### ISSUE TITLE
Atomikos checkpoint-interval should use Duration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12181]
All relevant properties have switched to `Duration` but `spring.jta.atomikos.properties.checkpoint-interval` did not. Looks like an oversight.

**Comment by snicoll** [comment]
Actually, this is not an `duration`, the description in the appendix was wrongly updated to mention milliseconds though.

**Comment by GuyPardon** [comment]
Hi,

Not sure what is meant by duration, but the Atomikos checkpoint interval is _not_ a duration - it's a count of the number of log writes between consecutive checkpoints.

Just my 2 cents :-)

Best

**Comment by snicoll** [comment]
> Not sure what is meant by duration, but the Atomikos checkpoint interval is not a duration

@GuyPardon this issue is flagged with invalid and I wrote the same thing in a comment just above yours.
