### ISSUE TITLE
Support for properties based auto configuration of Hazelcase server and client 

### ISSUE THREAD

**Issue by kedar-joshi** [spring-projects/spring-boot#12185]
We currently have a setup where our application has one Spring Boot profile for each environment we deploy i.e. `common`, `dev`, `qa`, `pre-prod` and `prod`. Hazelcast configuration, however, doesn't change much between these environments except for IP addresses. 

Spring Boot currently supports Hazelcast auto configuration via `spring.hazelcast.config` property. But this approach requires a separate `hazelcast.xml` for each environment.

It would be very powerful if Spring Boot could auto configure Hazelcast server or client instances via `HazelcastProperties`. This would allow us to have common properties in `application-common.properties` and environment specific overrides in their corresponding profiles. 

Essentially, this would mean using following configuration for Hazelcast server and client -

```
spring.hazelcast.group-name = dev
spring.hazelcast.group-password = dev-pass
...
spring.hazelcast.network.interfaces-enabled = true
spring.hazelcast.network.interfaces = 10.10.1.*
spring.hazelcast.network.port = 5701
...
spring.hazelcast.network.multicast-enabled = true
```

**Comment by wilkinsona** [comment]
Are you proposing that we support using properties rather in place of hazelcast.xml? Even if that's technically possible, I am not keen on trying to replicate XML-based configuration with properties and then keeping that in sync with any new configuration options that Hazelcast introduces.

**Comment by kedar-joshi** [comment]
I am proposing to use properties as an alternative and will take effect if `hazelcast,xml` is not present. 

Although, I acknowledge that keeping the properties in sync will be a chore but I also think that it will avoid maintaining profile specific `hazelcast.xml`.

**Comment by snicoll** [comment]
FTR I am not keen to introduce such complexity in Spring Boot either.

**Comment by kedar-joshi** [comment]
Sounds reasonable. Thanks for considering, though.

**Comment by vpavic** [comment]
@kedar-joshi Since Boot also supports configuring Hazelcast by providing `Config` bean, you can easily create your own `@ConfigurationProperties` class that exposes Hazelcast properties of your interest, and use that properties class to configure Hazelcast's `Config` bean. That would eliminate the need for Hazelcast's XML configuration.
