### ISSUE TITLE
spring.messages.cache-duration does not define a DurationUnit

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12183]
The `cacheDuration` property has no default but we set it to `-1` in the auto-configuration if no value is specified. I guess having `-1ms` as the default value is a bit funky?

Right now we document `-1` in the appendix so we should make up our mind about this one. Either remove the default from the documentation or set it in the property. Since that default value is a bit special, I am tempted to remove it from the appendix.

**Comment by snicoll** [comment]
@philwebb I think that this property is missing `DurationUnit` right? It used to be seconds in `1.x`.

**Comment by philwebb** [comment]
@snicoll I may well have missed it during the migration.

**Comment by snicoll** [comment]
Looks like it, I've renamed the issue to expand its scope.
