### ISSUE TITLE
Provide way to customize ApplicationContext before refresh when using SpringApplication / SpringApplicationBuilder

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-boot#12184]
`SpringApplication` and `SpringApplicationBuilder` do not expose the application context prior to refresh. This hides the ability to set some options, for example `context.setAllowCircularReferences`. It would be useful to expose `SpringApplication:postProcessApplicationContext` in some way. For example:

```
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(MyApp.class)
                .postProcessApplicationContext( appContext-> {
                    //tweak app context as needed
                } );
    }
```

**Comment by philwebb** [comment]
Does `SpringApplication.addInitializers` work or is that too early?

**Comment by twicksell** [comment]
That actually would work just fine. Somehow all this time I've missed that interface existing. Sorry about that.

**Comment by snicoll** [comment]
I did too :) Alright, closing this one then.
