### ISSUE TITLE
Investigate using a failure analyser to provide better guidance for disabling target class proxying

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12197]
See https://github.com/spring-projects/spring-boot/issues/12194#issuecomment-368032610.

**Comment by mbhave** [comment]
> I've asked for a pointer on SPR-14322.

@wilkinsona Could you clarify what you meant by that, please?

**Comment by wilkinsona** [comment]
I think I linked to the wrong issue and actually meant [SPR-16352](https://github.com/spring-projects/spring-framework/issues/21075). Reading through that issue again, I don't think there's any that we could/should do here.
