### ISSUE TITLE
KafkaHealthIndicator and older brokers

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#12198]
Currently, when the broker doesn't support obtaining configuration (e.g. 0.10.2.0), the health indicator reports `Down`.

Consider skipping the `replicationFactor` check if the broker cannot provide that information.

See https://github.com/spring-projects/spring-boot/pull/11515#issuecomment-368044582

**Comment by snicoll** [comment]
Closing in favour of PR #12000
