### ISSUE TITLE
Migration guide refers to security blog post that has outdated information

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12191]
Our security infrastructure has been polished since M4. Our migration guide [refers to the blog post](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#security) but it provides outdated information now.

We should either update the blog post or stop referring to it I guess

/cc @aheritier

**Comment by snicoll** [comment]
I've reworked the [Security migration use cases] wiki page and I've removed the reference to the now outdated blog post. They were covering somewhat the same content, the wiki page being more complete so I think we're good now.

**Comment by aheritier** [comment]
@snicoll I don't find how to propose a fix to the wiki

you have a line which doesn't compile:

```
.requestMatchers(PathRequest.toStaticResources().atCommonLocations).permitAll()
```

It should be

```
.requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
```

**Comment by snicoll** [comment]
Thanks @aheritier, this is [fixed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0/_compare/80333851e11d08535eb7e63095cfd3d8393b2f94...a145ff3d57b2b66439b758bb98e6621a43e6c856)
