### ISSUE TITLE
Add HTTP/2 with netty section to docs

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12204]
For completeness we should add it [here](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/htmlsingle/#howto-configure-http2)

**Comment by bclozel** [comment]
It’s not supported yet in reactor Netty. Do you want to mention that in the docs?

**Comment by philwebb** [comment]
Oh, I was doing the release notes and I thought we had support for some reason. Perhaps I'm getting confused with SSL.

**Comment by bclozel** [comment]
Confirmed: it's not supported yet. I guess we can close that issue?

**Comment by wilkinsona** [comment]
I guess we can too.
