### ISSUE TITLE
How to use the class Health with RestTemplate

### ISSUE THREAD

**Issue by dickerpulli** [spring-projects/spring-boot#1222]
I tried to use the class Health (from actuators) as response type of Spring RestTempate's method `getForObject(String url, Class<AppHealth> responseType, Object... urlVariables)`.

The problem: An exception is thrown, because there is no default contructor for Health.

Is it possible to modify the class (Health) to work with the RestTemplate?

Or is there another simple way you can recommend to create objects out of JSON instead of using RestTemplate?

**Comment by SirWayne** [comment]
Is there now a custom deserializer?

**Comment by wilkinsona** [comment]
@SirWayne Not that I'm aware of; this issue is open

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by sasaunde** [comment]
I've hit this today - trying to standardise health check messages across the estate and can't customise Spring Boot messages

**Comment by wilkinsona** [comment]
@sasaunde Sorry, I can't see the connection between deserialisation of JSON to a `Health` instance and message customization. Could you please elaborate?
