### ISSUE TITLE
CPU Utilization over 100%

### ISSUE THREAD

**Issue by shagunbakliwal** [spring-projects/spring-boot#12221]
Hi, 
I migrated to spring boot 2.0.0 M6 and have been experiencing CPU utilization over 100%(~350%). This is on (Centos7) VM with 64GB RAM and 8 Cores CPU(running 10 other services on the same node with normal utilization). I have a basic REST service running(with a reactive endpoint post-migration).  The same service had relatively lower CPU use before migration. Please help.

**Comment by shagunbakliwal** [comment]
Thanks for the quick reply. Will upgrade to RC2 and let you know if the issue persists.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
