### ISSUE TITLE
WebClient metrics support

### ISSUE THREAD

**Issue by Delorien84** [spring-projects/spring-boot#12228]
It will be fine, to have metrics support for reactive `org.springframework.web.reactive.function.client.WebClient`. Currently there is support only for standard `RestTemplate`.

**Comment by jkschneider** [comment]
This depends on https://jira.spring.io/browse/SPR-16537. We currently don't have access to the parameterized URI to tag `WebClient` metrics with.

**Comment by jkschneider** [comment]
Nope, no longer blocked, but won't be picked up until Boot 2.1 I'm guessing.

**Comment by spencergibb** [comment]
It's in 5.0.5, so maybe 2.0.1?

**Comment by bjartek** [comment]
Was this in 2.0.2?

**Comment by michael-barker** [comment]
@bclozel Should this use the Reactor context to set the start time?  I believe this could result in incorrect timings when the sequence is re-subscribed to.  The specific scenario I'm thinking of is when using retries in Reactor.  When the sequence is retried the duration will be the sum of the previous durations.

**Comment by bclozel** [comment]
Good catch @michael-barker !
This is now fixed with an additional test and a slightly different approach - using the `Context` is right, but `doOnEach` considers all signals, including `onComplete` (and we don't want to record metrics for that signal, in this case).

**Comment by bjartek** [comment]
Thanks!

**Comment by lubinson** [comment]
is this in 2.1.1? I am using webclient but no http client requests found in prometheus.

**Comment by lubinson** [comment]
@wilkinsona Thanks, I just found this precondition. Previously I didn't use injected builder.
