### ISSUE TITLE
Failed to load different version of embedded Mongodb

### ISSUE THREAD

**Issue by cmario** [spring-projects/spring-boot#12230]
Hi,

specifying a different version of embedded mongodb "spring.mongodb.embedded.version=3.6.2" fails with the following error:

```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.6.2.tgz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_131]
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127) ~[de.flapdoodle.embed.process-2.0.2.jar:na]
	... 114 common frames omitted
```

I am using spring boot 2.0.0.RC2, see https://github.com/cmario/spring-boot-embedded-mongodb for an example.

Regards
Mario

**Comment by wilkinsona** [comment]
The URL that is used is determined by [Embedded MongoDB](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) so you'll need to raise the issue with them. In the meantime, you can override Embedded MongoDB's default download URL by declaring your own `IRuntimeConfig` bean [configured with a custom download URL](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-download-url).

**Comment by cmario** [comment]
Hi Andy,

thank you for the quick answer. Actually using directly Embedded MongoDB works fine for me, for example defining the following bean:
```
@Bean
public IMongodConfig embeddedMongoConfiguration() throws IOException {
     return new MongodConfigBuilder().version(Version.Main.V3_6)
             .net(new Net("127.0.0.1", 27017, Network.localhostIsIPv6())).build();
}
```
Regards
Mario

**Comment by wilkinsona** [comment]
If all you've set in `application.properties` is `spring.mongodb.embedded.version=3.6.2`, then that configuration will use a different URL. The features that are enabled effect the download URL (to ensure that the downloaded binary supports the required features). To use the same URL, you also need to set `spring.mongodb.embedded.features=use_only_ssl`. You may also need to provide additional features to get the runtime behaviour that you want.

**Comment by wilkinsona** [comment]
FWIW, I still think this is worth raising with the embedded Mongo project as the connection between features and the download URL is pretty unclear to me.
