### ISSUE TITLE
Use applicationName as a convention for the boot Distribution's baseName

### ISSUE THREAD

**Issue by DanielThomas** [spring-projects/spring-boot#12232]
Configuring the `applicationName` should result in the distribution directory changing, however setting `applicationName = 'foo'` in a project called `spring-boot` results in this structure:

	.
	├── build
	│   ├── bootScripts
	│   │   ├── foo
	│   │   └── foo.bat
	│   ├── install
	│   │   └── spring-boot-boot
	│   │       ├── bin
	│   │       │   ├── foo
	│   │       │   └── foo.bat
	│   │       └── lib
	│   │           └── spring-boot.jar
	│   ├── libs
	│   │   └── spring-boot.jar
	│   └── tmp
	│       └── bootJar
	│           └── MANIFEST.MF
	└── build.gradle

Note the `install/spring-boot-boot` directory, I'd expect `install/foo-boot` in this case. I can workaround the problem by using:

    project.afterEvaluate {
        project.distributions {
            boot {
                baseName = "${project.distributions.main.baseName}-boot"
            }
        }
    }

FWIW, this is what the `DistributionPlugin` does:

https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/distribution/plugins/DistributionPlugin.java#L81-L86

We ran into this while adding a Spring Boot application plugin variant to our ospackage plugin:

- https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v4.8.0
- https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy

**Comment by wilkinsona** [comment]
I guess there wouldn't be any harm in aligning with the [application plugin's behavior]( https://github.com/gradle/gradle/blob/3b74739a1fed8d1ba4c6d39712b0cf3e59a1d514/subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java#L69-L74) where it sets up a convention mapping for the distribution's base name.
