### ISSUE TITLE
spring-boot-starter-test not working with spring-boot-starter-parent 1.5.10.RELEASE

### ISSUE THREAD

**Issue by lfgcampos** [spring-projects/spring-boot#12231]
Hello,

I am migrating my project from `spring-boot-starter-parent` from `1.5.9.RELEASE` to `1.5.10.RELEASE` and I am facing this issue.
It is happening even if I create a simple project on http://start.spring.io with only `spring-boot-starter-web` and `spring-boot-starter-test` modules.

I suspect this is somehow a jar hell happening between the modules/libs but I am not sure and I have no idea how to start investigating that (help here would be appreciated).

I am working on/with:
- Windows 10 Pro 64-bit
- Eclipse Version: Oxygen.2 Release (4.7.2) Build id: 20171218-0600
- Apache Maven 3.5.0
- Java version "1.8.0_152"

![pom](https://user-images.githubusercontent.com/8443274/36693333-3fd0fb0e-1b3b-11e8-8a06-b59ab299f486.PNG)
![application](https://user-images.githubusercontent.com/8443274/36693332-3fa600a2-1b3b-11e8-93ee-808ad8c6a33d.PNG)

**Comment by wilkinsona** [comment]
Your `spring-test` jar is corrupted. Try deleting it from your Maven cache and building your project again.
