### ISSUE TITLE
Enhancement: give classloader precedence to BOOT_INF/classes over BOOT_INF/lib

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-projects/spring-boot#12263]
It is very hard to override/patch classes of dependencies right now. See https://dzone.com/articles/spring-boot-classloader-and-class-override for details.

If the /classes got precedence, it would suddenly get very easy. Is there a chance we get that?

**Comment by wilkinsona** [comment]
It's already available in 2.0 RC2. Duplicate of https://github.com/spring-projects/spring-boot/issues/11696.
