### ISSUE TITLE
management.metrics.export.tags-as-prefix property seems not to be honored in Spring Boot 2.0.0.RC2

### ISSUE THREAD

**Issue by mle-enso** [spring-projects/spring-boot#12262]
We're using Micrometer to report our metrics to Graphite with the following config…
```
management.metrics.export.graphite.host=<graphite-server.com>
management.metrics.export.graphite.port=2003
management.metrics.export.tags-as-prefix=our-service-name
management.metrics.export.graphite.protocol=Plaintext
management.metrics.export.graphite.step=PT1M
```
What we see is, that all the ```jvm*``` and other metrics are reported without the specified ```tags-as-prefix```.
We expect them to be reported as ```our-service-name.jvm*``` and so on.
Also adding a…
```
@Configuration
public class GraphitePrefixConfiguration {
	@Value("${management.metrics.export.tags-as-prefix}")
	private String graphitePrefix;

	@Bean
	public HierarchicalNameMapper hierarchicalNameMapper() {
		return new GraphiteHierarchicalNameMapper(graphitePrefix);
	}
}
```
…as mentioned here http://micrometer.io/docs/registry/graphite does not have any effect.
During further inspection we see that in ```com.codahale.metrics.graphite.GraphiteReporter.report(SortedMap<String, Gauge>, SortedMap<String, Counter>, SortedMap<String, Histogram>, SortedMap<String, Meter>, SortedMap<String, Timer>)``` the ```prefix``` field is always null.

**Comment by jkschneider** [comment]
@mle-enso Sorry that the docs on Micrometer's Graphite support haven't quite caught up to this feature. This property is intended to be paired with a common tag and is working as intended. See the full explanation [here](https://github.com/micrometer-metrics/micrometer/issues/477)

**Comment by snicoll** [comment]
Thanks for the clarification @jkschneider
