### ISSUE TITLE
Spring boot classloader hierarchy issue

### ISSUE THREAD

**Issue by sanityCheck10** [spring-projects/spring-boot#12265]
I have a spring boot jar file that does not seem to work. Here is the layout of the jar file:

```
example.jar
 |
 +-META-INF
 |  +-MANIFEST.MF
 +-org
 |  +-springframework
 |     +-boot
 |        +-loader
 |           +-<spring boot loader classes>
 +-BOOT-INF
    +-classes
    |  +-mycompany
    |     +-project
    |        +-A.class
    +-lib
       +-dependency1.jar
         +- B.class
       +-dependency2.jar
```
Class B in the lib needs to see Class A in BOOT-INF/classes but it cannot. How do I fix this problem? Is the class loader for lib at a higher level than the class loader for BOOT-INF? I could not find the specifics anywhere.

**Comment by wilkinsona** [comment]
Classes in BOOT-INF/classes and in jars in BOOT-INF/lib are loaded using the same class loader so I don’t understand why you are apparently having the problem that you have described. Can you please provide a small sample that reproduces the problem?

**Comment by sanityCheck10** [comment]
Never mind. We were using a URLClassLoader to load a class in the about situation and it was not working. But when we changed to the default class loader, it started working fine. This is no longer an issue. Thanks!
