### ISSUE TITLE
Lombok 1.6.20 breaks compile on save in NetBeans, last workin version is 1.6.18

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [spring-projects/spring-boot#12264]
Spring boot: 2.0.0.RC1, 2.0.0.RC2
Lobmok 1.6.20 prevents spring-boot dev tools from working as modified .java file does not compile to .class. Last known working version is 1.6.18.

Steps to reproduce.

- Create a demo with spring initiazr, add lombok as dependency ([lombok.zip](https://github.com/spring-projects/spring-boot/files/1764053/lombok.zip) is attached).
- Open resulting project in netbeans (8.1, 8.2)
- make sure [Compile on Save](http://wiki.netbeans.org/FaqCompileOnSave#Using_Compile_on_Save_in_Maven_Projects) is enabled
- build project (F11 will do)
- Check file sysytem, target/classes/com/example/lombok/LombokApplication.class should be there
- modify LombokApplication.java and save it
- target/classes/com/example/lombok/LombokApplication.class will disappear

Expected behaviour:

-target/classes/com/example/lombok/LombokApplication.class should change after .java file is modified

Workaround:

- override lombok dependency with vesion 1.6.18 

Links of interest:
https://github.com/rzwitserloot/lombok/issues/1592
https://github.com/rzwitserloot/lombok/issues/1577

Whole the issue may be indication of a bigger problem with lombok 1.6.20 and show itself in other cases except this NetBeans problem.

**Comment by wilkinsona** [comment]
Thanks for the report, but I think this needs to be resolved in Lombok or in NetBeans' Lombok integration. We haven't heard of any problems from users of other IDEs.
