### ISSUE TITLE
Upgrade to Junit 5.1

### ISSUE THREAD

**Issue by Cat7373** [spring-projects/spring-boot#12273]
https://github.com/junit-team/junit5/releases/tag/r5.1.0

**Comment by philwebb** [comment]
We've already upgraded the managed dependency](https://github.com/spring-projects/spring-boot/blob/c23b0e99f1f8b14f1237e88f8ca5071187e4ebe2/spring-boot-project/spring-boot-dependencies/pom.xml#L106) to 5.1.0.

**Comment by snicoll** [comment]
@Cat7373 we have a semi-automated process that takes care of dependencies upgrade so we neither need issues nor PRs for that sort of thing. Thank you.
