### ISSUE TITLE
Mistyped sentence on Spring-Boot-2.0-Migration-Guide wiki

### ISSUE THREAD

**Issue by jjangga0214** [spring-projects/spring-boot#12281]
I found a mistyped sentence on [Spring-Boot-2.0-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide). (It seems just a little mistake.)

The sentence

> `ApplicationReadyEvent` is sent after any application and command-line runners have been called.

should be removed. It's opposite from the fact - `ApplicationReadyEvent` is sent __BEFORE__ any application and command-line runners have been called- , and already mentioned on the prior sentence.

**Comment by wilkinsona** [comment]
Thanks, but I believe the migration guide is correct. The two sentences read as follows:

> `ApplicationStartedEvent` is sent after the context has been refreshed but before any application and command-line runners have been called. `ApplicationReadyEvent` is sent after any application and command-line runners have been called.

This is an accurate description of the current behaviour, as shown by the code in `SpringApplication` that triggers the event publication:

https://github.com/spring-projects/spring-boot/blob/299eca084cd537bfb48fea4a9f986d32b598c263/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L334-L341

`listeners.started(context)` published the started event. `listeners.running(context)` publishes the ready event.
