### ISSUE TITLE
Springboot 2.0 cannot  support relaxed names with ConditionalOnProperty?

### ISSUE THREAD

**Issue by aqlu** [spring-projects/spring-boot#12282]
This feature starts with 1.1.x, why 2.0 canceled it ?

issue: https://github.com/spring-projects/spring-boot/issues/835

commit: https://github.com/spring-projects/spring-boot/commit/4b51b6f9dfc9d59c3ccc8ad4b0b638ee68cda8fa

**Comment by wilkinsona** [comment]
It hasn't been cancelled. If you've encountered a problem that makes you believe that it has, please provide a small sample that reproduces the problem.

**Comment by aqlu** [comment]
In my case,  if add `spring.rocketmq.name-server=xxx` in `application.properties`, I can get a bean named `mqProducer` by application context on spring-boot v1.5.9, but can not get on 2.0.0-RC2.

```java
@Bean
@ConditionalOnProperty(prefix = "spring.rocketmq", value = "nameServer")
public DefaultMQProducer mqProducer(RocketMQProperties rocketMQProperties) {
    return new DefaultMQProducer(rocketMQProperties.getGroup());
}
```

You can see the source code : 
Property of `relaxedNames` has been removed in [ConditionalOnProperty](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java) , and the code for `RelaxedPropertyResolver` in  [OnPropertyCondition](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnPropertyCondition.java) is also removed.

**Comment by snicoll** [comment]
`@ConditionalOnProperty` should use the canonical case. That property must be written as:

```@ConditionalOnProperty(prefix = "spring.rocketmq", value = "name-server")```

**Comment by wilkinsona** [comment]
The need to use dashes is described in the javadoc for both 1.5 and 2.0 where it says:

```
 * Use the dashed notation to specify each property, that is all lower case with a "-"
 * to separate words (e.g. {@code my-long-property}).
```
