### ISSUE TITLE
BatchDatabaseInitializer does not drop batch tables.

### ISSUE THREAD

**Issue by jvmvik** [spring-projects/spring-boot#1229]
Hello

When Spring batch database is enabled, the batch tables are not cleanup after a restart. This behaviors is not consistent with Spring Batch core implementation.

Spring Batch will automatically try to drop then create the schema.

```
<jdbc:initialize-database data-source="dataSource" enabled="${batch.data.source.init}" ignore-failures="DROPS">
    <jdbc:script location="${batch.drop.script}"/>
    <jdbc:script location="${batch.schema.script}"/>
</jdbc:initialize-database>
```

Source: https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/resources/baseContext.xml

The current implementation of BatchDatabaseInitializer provided in Spring Boot does not drop the schema.
.
Source: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchDatabaseInitializer.java

For the sake of consistency, I would expect that the Batch tables are cleanup when

``` property
spring.jpa.hibernate.ddl-auto=create | create-drop
```

I have prepared a fix for that.
Victor

**Comment by snicoll** [comment]
I agree about the consistency argument. It's been a while and there's no cleanup in other initializers we provide.
