### ISSUE TITLE
Spring Boot does not honor externalized configuration for setting LoggingSystem

### ISSUE THREAD

**Issue by nwertzberger** [spring-projects/spring-boot#12299]
https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/boot-features-logging.html
Section 26.5

> Since logging is initialized before the `ApplicationContext` is created, it isn’t possible to control logging from `@PropertySources` in Spring `@Configuration` files. System properties and the conventional Spring Boot external configuration files work just fine.)

The only way to override logging system (and set it to none, in my case) appears to be the system property method.  Trying application.properties, or servlet context parameters don't work.

I checked out the code, and it makes sense, all that the `LoggingSystem` class does is pull from `System.getProperty()`.

**Comment by wilkinsona** [comment]
It's only described in terms of a system property:

> You can force Spring Boot to use a particular logging system using the `org.springframework.boot.logging.LoggingSystem` system property. The value should be the fully-qualified class name of a LoggingSystem implementation. You can also disable Spring Boot’s logging configuration entirely by using a value of `none`.

I guess there's room for some clarification though.
