### ISSUE TITLE
Add ability to stop a running Spring Batch Job from a running application

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-boot#12306]
The current recommended way to run a Spring Batch job is via a Spring Boot uber jar via `java -jar myJobApp.jar jobParameter1=foo jobParameter2=bar ...`.  This works well and is well adopted by the community.  However, the mechanism Spring Boot uses for launching Spring Batch jobs does not include a feature the `CommandLineJobRunner` from Spring Batch does (the "legacy" way of running a batch job via a jar file), that's the ability to stop a running job.  With that main class (https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/launch/support/CommandLineJobRunner.java), you can specify from the command line to stop a running job.  This will change the status of the job's JobExecution within the JobRepository to be STOPPING.  Spring Batch regularly checks this status and will react accordingly if it's found.  It would be nice to either have a new `CommandLineRunner` or new feature added to the `JobLauncherCommandLineRunner` to be able to stop a running job in this mechanism.

**Comment by mminella** [comment]
For the record, I'm willing to do the work, I just want to agree on an a desired approach before doing it.

**Comment by philwebb** [comment]
I don't have a strong feeling for the best way to solve this. It looks like `JobLauncherCommandLineRunner` was mainly written by @dsyer.

**Comment by mminella** [comment]
The easiest way would be for me to modify the `JobLauncherCommandLineRunner`, but that will, at a minimum, tweak it from it's original intent (launching jobs instead of anything else).

**Comment by philwebb** [comment]
I guess, but they do seem quite related. If we can make the change in a back-compatible way I'd say changing `JobLauncherCommandLineRunner` is the way to go.

**Comment by mminella** [comment]
I don't believe the new functionality would need to have any impact at all on the existing functionality so it would be backwards compatible.

**Comment by snicoll** [comment]
@mminella just to make sure I understand, that's going to start the app again with a flag whose purpose is to stop another instance of the app running a job? I am a bit confused by the arrangement there. What would the `main` method do in practice?

**Comment by mminella** [comment]
The "stop" is really just a database update.  Let's say the user is running `myJob` via a boot über jar.  They have one java process on a box somewhere running that job.  The idea here is to be able to take the same über jar and do `java -jar myJob.jar --batch.stop=myJob` and it will look in the `JobRepository` and mark any running `JobExecution`s associated with that job to `STOPPING`.  This is the same functionality that the Spring Batch `CommandLineJobRunner` has.  In essence, the `--batch.stop` parameter would override the one to launch jobs so the `JobLauncherCommandLineRunner` wouldn't run any jobs, it would just stop the ones requested and complete.

**Comment by snicoll** [comment]
Thanks, that confirms what I understood.

I don't think that's a viable option. Reusing the same application means that all that happens besides the job itself will run again. That doesn't sound a good idea for something so focused as stopping a job. 

I think we should research a different option for this.

**Comment by wilkinsona** [comment]
This feels like a bit like another variant of #6035.

**Comment by mminella** [comment]
@wilkinsona I agree.  The type of functionality is the same.

**Comment by philwebb** [comment]
We've closed #6035 because we don't want to add additional complexity to the code-base. I'm going to close this one as well and suggest that we create documentation issue to show how to do this programmatically.
