### ISSUE TITLE
Spring Boot 2.0.0 don't respect jar name has Spring Boot 1.5.10

### ISSUE THREAD

**Issue by marcomsousa** [spring-projects/spring-boot#12300]
Spring Boot v2.0.0.RELEASE (Gradle) don't respect the version in the name of jar build.
I have this:
```
jar {
	baseName = 'build'
	version = '1.0-SNAPSHOT'
}
```

**In Spring Boot 1.5.10**
```
gradlew build
Generate this file:  build\libs\build-1.0-SNAPSHOT.jar

```
**In Spring Boot 2.0.0**
```
gradlew build
Generate this file:  build\libs\build.jar
```

**Gradle Plugin 1.5.10**
org.springframework.boot:spring-boot-gradle-plugin:1.5.10.RELEASE
**Gradle Plugin 2.0.0**
org.springframework.boot:spring-boot-gradle-plugin:2.0.0.RELEASE

**Comment by wilkinsona** [comment]
In Spring Boot 2.0, it's the `bootJar` task that builds the fat jar. Please see the [reference documentation](https://docs.spring.io/spring-boot/docs/2.0.x/gradle-plugin/reference/html/#packaging-executable-and-normal) for details.
