### ISSUE TITLE
About Spring-boot-ampq .I have some suggestions

### ISSUE THREAD

**Issue by cky-thinker** [spring-projects/spring-boot#12311]
Recently, I needed to use spring-boot-amqp in my project, and I found some unreasonable places.
1.
@interface Exchange default value  is  durable=false, autoDelete=false
and the AbstractExchange default value is durable=true, autoDelete=false
if i run project by default ,it will throw exception
2.
I think it's more reasonable to explicitly specify the @interface Exchange#type instead of the default exchangetypes.direct, because you might forget to modify the type and make a mistake, it's not easy to find here, and it's normal to use the other type.

**Comment by wilkinsona** [comment]
Thanks, but these suggestion should be made to the [Spring AMQP project](https://github.com/spring-projects/spring-amqp).

**Comment by cky-thinker** [comment]
Thinks
