### ISSUE TITLE
No effect of -Drun.jvmArguments in Maven

### ISSUE THREAD

**Issue by amrfaissal** [spring-projects/spring-boot#12317]
After upgrading to Spring Boot 2.0.0.RELEASE, passing/overriding properties with `-Drun.jvmArguments="-Dmyproperty=value"` in Maven doesn't have any effect anymore.

For dev, I prefer to run my application using `mvn clean spring-boot:run -Drun.jvmArguments="-Dmyproperty=value"`.

 Am I missing something? Thanks.

**Comment by wilkinsona** [comment]
The argument is [named `spring-boot.run` in 2.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-boot-maven-plugin).

**Comment by amrfaissal** [comment]
Thanks!
