### ISSUE TITLE
spring boot 2.0 WebMvcConfigurer#addInterceptors apply all requests, including resource handler requests?

### ISSUE THREAD

**Issue by Saisimon** [spring-projects/spring-boot#12313]
Version : Spring Boot 2.0.0.RELEASE
According to the Spring Framework API documentation
> Note that interceptors registered here only apply to controllers and not to resource handler requests.

However, the test results are not the same as the documentation,all requests apply custom interceptors, including resource handler requests.here is [test demo](https://github.com/Saisimon/spring-boot2-demo)

**Comment by bclozel** [comment]
This is a documentation error in Spring Framework, as it's been changed in Spring Framework 5.0.1 with [SPR-16034](https://jira.spring.io/browse/SPR-16034) (motivated by #10335).

Could you create a [Spring Framework JIRA](https://jira.spring.io) issue for this, adding a link to that documentation section? Also, please explain there any problem that this behavior might be creating with your application.

Thanks!
