### ISSUE TITLE
`@AutoConfigureWebTestClient` breaks when SpringMVC is on the classpath

### ISSUE THREAD

**Issue by S1lentControl** [spring-projects/spring-boot#12318]
spring boot 2.0.0-RELEASE + spring-boot-starter-web-services 2.0.0.RELEASE
Tests with 

```
@RunWith(SpringRunner::class)
@SpringBootTest
@AutoConfigureWebTestClient
class DemoApplicationTests {...
```

Application not started after adding **spring-boot-starter-web-services** to dependencies

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.test.web.reactive.server.WebTestClient]: Factory method 'webTestClient' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'webHandler' available

**Comment by snicoll** [comment]
`@AutoConfigureWebTestClient` is to configure the reactive `WebClient` of Spring WebFlux. What is the link with web-services?

Can you please describe what you're trying to do?

**Comment by S1lentControl** [comment]
I have reactive application, and i need call external soap services

**Comment by S1lentControl** [comment]
I have reactive spring-boot 2 appication and i need call external soap web-services in my service layer.

**Comment by snicoll** [comment]
Sorry but that doesn't make much sense right now. Can you please share a sample that we can run that demonstrates what you are trying to do and the error you referenced in your original description?

**Comment by S1lentControl** [comment]
I solved the problem by excluding **spring-webmvc** 

```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-webmvc</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by snicoll** [comment]
@S1lentControl without a sample, we'll try to fix what we guess the problem is: the webflux and web-services starter in app with that test you shared.

Please don't use `spring-boot-starter-web-services` for a WS client. I agree it isn't super obvious, but this starter is meant to be used for a WS server. You can add the following to your build instead of the starter:

```
<dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-oxm</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.ws</groupId>
	<artifactId>spring-ws-core</artifactId>
</dependency>
```

We'll look at why `@AutoConfigureWebTestClient` fails when Spring MVC is on the classpath.

**Comment by S1lentControl** [comment]
Thanks for the answer. You correctly described the problem.
In the sample, a similar problem, but with **spring-restdocs-mockmvc 2.0.0**
https://github.com/S1lentControl/spring-reactive-with-mvc-faled-tests

**Comment by bclozel** [comment]
`WebTestClient` should only be configured for testing WebFlux applications in mock/integration modes. So we should probably guard that auto-configuration with an additional condition here on the web application type.

Note that there's an issue in the Spring Framework backlog about `WebTestClient` supporting `MockMvc` as well -  see [SPR-15081](https://jira.spring.io/browse/SPR-15081).

So this arrangement might change in the future if we decide to support that.

**Comment by snicoll** [comment]
unfortunately, #12366 wasn't properly fixed so I'll revert that (and this fix since it's relying on it) until we have a proper fix for the issue.
