### ISSUE TITLE
spring boot 2.0 do not support import @ControllerEndpoint from ManagementContextConfiguration ?

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#12312]
[endpointdemo.zip](https://github.com/spring-projects/spring-boot/files/1774420/endpointdemo.zip)

In demo `TestControllerEndpoint1` is ok, `TestControllerEndpoint2` do not work.

spring.factories:

```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  com.test.TestEndpoints1Configuration

org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration=\
  com.test.TestEndpoints2ManagementContextConfiguration
```

In spring boot 1.5 import endpoint controller bean from `ManagementContextConfiguration` is ok . 

In spring boot 2, user have to import form `EnableAutoConfiguration`?

**Comment by wilkinsona** [comment]
Both endpoint beans have the same name so one is overriding the other. There's a log message that states that this has happened:

```
2018-03-02 10:26:33.431  INFO 19174 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'testControllerEndpoint' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=com.test.TestEndpoints1Configuration; factoryMethodName=testControllerEndpoint; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/test/TestEndpoints1Configuration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=com.test.TestEndpoints2ManagementContextConfiguration; factoryMethodName=testControllerEndpoint; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/test/TestEndpoints2ManagementContextConfiguration.class]]
```

**Comment by hengyunabc** [comment]
@wilkinsona Very sorry, please try this new demo : 
[endpointdemo.zip](https://github.com/spring-projects/spring-boot/files/1774776/endpointdemo.zip)


### mvn spring-boot:run

```bash
$ curl http://localhost:8080/actuator/testendpoint1
testendpoint1
$ curl http://localhost:8080/actuator/testendpoint2
testendpoint2
```

### mvn spring-boot:run -Dmanagement.server.port=8081

```bash
$ curl http://localhost:8081/actuator/testendpoint1
testendpoint1
$ curl http://localhost:8081/actuator/testendpoint2
{"timestamp":"2018-03-02T10:54:21.248+0000","status":404,"error":"Not Found","message":"No message available","path":"/actuator/testendpoint2"}
```

---

When management context and application context are not the same, controller import from `ManagementContextConfiguration` do not work.

**Comment by wilkinsona** [comment]
Thanks, I can see the problem now. As of 2.0, there's no need to use `@ManagementContextConfiguration` to have your endpoint exposed uses the management port. We should update the documentation.

**Comment by wilkinsona** [comment]
We should probably also double-check that things are they way we want them to be now. I'd like `@ManagementContextConfiguration` to be, as much as possible, an implementation detail that users don't have to worry about. For that reason, I think the current arrangement is better than what we had in 1.5.

**Comment by hengyunabc** [comment]
@wilkinsona In spring boot 2, `management.port` change to  `management.server.port`, but under test the key is still `local.management.port`.

How to get ManagementContext in application context in spring boot 2? 
In spring boot 1.5 : `org.springframework.boot.actuate.autoconfigure.ManagementContextResolver`

**Comment by hengyunabc** [comment]
I wrote an endpoint for endpoints in spring boot 1.5 : 
[endpoint-for-endpoints.zip](https://github.com/spring-projects/spring-boot/files/1777324/endpoint-for-endpoints.zip)

* http://localhost:8081/endpoints/ return all endpoints infos:
* http://localhost:8081/endpoints/mappings return all endpoints mappings(contains `@RequestMapping`), which similar to `_links` in spring boot 2.

---

But `_links` in spring boot 2 only contain detailed url information with `@Selector`.  There are not mappings info about `@ControllerEndpoint`.

I try to write an endpoint for `@ControllerEndpoint`, but it don not work when management context and application context are not the same.

```java
@Endpoint(id = "controller")
public class ControllerEndpointEndpoint {

	@Autowired(required = false)
	ControllerEndpointHandlerMapping mapping;

	@ReadOperation
	public Map<String, Object> info() {
		Map<String, Object> result = new HashMap<String, Object>();
		if (mapping != null) {
			Map<?, HandlerMethod> methods = mapping.getHandlerMethods();
			for (Entry<?, HandlerMethod> method : methods.entrySet()) {
				Map<String, String> map = new LinkedHashMap<String, String>();
				map.put("method", method.getValue().toString());
				result.put(method.getKey().toString(), map);
			}
		}
		return result;
	}

}
```

**Comment by snicoll** [comment]
@hengyunabc we don't use the tracker for questions (so please ask them on StackOverflow or join us on Gitter). Also, this issue should be focused on the original description and not deviate on another topic. Thank you.

**Comment by hengyunabc** [comment]
@snicoll I did not describe the problem clearly. 

1. For security reasons, management port and server port are not the same in my applications.
2. I have an endpoint needs to get the management context, and then get mappings information for all endpoints: `endpoint-for-endpoints.zip`
3. Currently spring boot 2 does not support import `@ControllerEndpoint` from `ManagementContextConfiguration`, when management context and application context are not the same.
4. If use `EnableAutoConfiguration` to import `@ControllerEndpoint`, the endpoint bean will be created by application context, the endpoint bean can not get the management context
5. In spring boot 1.5 , `ManagementContextResolver` can get the management context
6. According to @wilkinsona, spring boot 2 no longer supports import @ControllerEndpoint from ManagementContextConfiguration

So, I think spring boot2 can consider supporting either of the following two

1. spring boot 2 `_links` show mappings information from `@ControllerEndpoint`
2. spring boot 2 support `ManagementContextResolver`, and then I can solve the problem by myself.

**Comment by wilkinsona** [comment]
> But _links in spring boot 2 only contain detailed url information with @Selector. There are not mappings info about @ControllerEndpoint.

That's not quite right. `_links` should include a single link to the root of the controller endpoint. We made the decision not to try to include any more link information as generating accurate HAL links, each with a meaningful `rel` for every possible type of request mapping would be virtually impossible.

If you want to write an endpoint that's aware of `ControllerEndpointHandlerMapping`, then you should write a component that's configured using `ManagementContextConfiguration` that retrieves your custom endpoint from the context (it'll either be in the same context or in the parent) and passes it the management context or whatever beans from the management context it needs.

**Comment by hengyunabc** [comment]
@wilkinsona Actually , I wrote a `ManagementApplicationcontextHolder` to solved my problem. 

But , according to the new doc: 8590079 , the following demo do not work, I do not understand the document correctly?

[endpointdemo.zip](https://github.com/spring-projects/spring-boot/files/1780697/endpointdemo.zip)


```java
@Endpoint(id = "myendpoint")
public class MyEndpoint {
	@ReadOperation
	public Map<String, Object> info() {
		Map<String, Object> result = new HashMap<String, Object>();
		result.put("abc", "xxx");
		return result;
	}
}
```

```java
@ManagementContextConfiguration
public class MyEndpointManagementContextConfiguration {
	@Bean
	MyEndpoint myEndpoint() {
		return new MyEndpoint();
	}
}
```

```
org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration=\
  com.test.MyEndpointManagementContextConfiguration
```

```
mvn spring-boot:run -Dmanagement.server.port=8081
```

**Comment by wilkinsona** [comment]
I already tried to answer that above:

> As of 2.0, there's no need to use @ManagementContextConfiguration to have your endpoint exposed using the management port.

Instead, you should declare your endpoint bean as you normally would in the main application context.
