### ISSUE TITLE
Spring boot 2 does not work with spring-mobile-device

### ISSUE THREAD

**Issue by armdev** [spring-projects/spring-boot#12334]
I tried to integrate Spring Boot 2 (netty and Finchley.M8 ) and spring-mobile-device,(
https://docs.spring.io/spring-mobile/docs/current/reference/html/device.html
) but now it is impossible because dependencies from Servlet API. 
Is spring-mobile-device will be updated up to Spring Boot2 ? Any alternative?
Similar problems with @enableswagger2.
Thanks

**Comment by wilkinsona** [comment]
Neither Spring Mobile nor Spring Fox is part of Spring Boot. You’ll have to ask the developers of those projects what their plans are for supporting WebFlux.

**Comment by armdev** [comment]
Ok, thanks
