### ISSUE TITLE
The reference guide introduces a deprecated method

### ISSUE THREAD

**Issue by jacobis** [spring-projects/spring-boot#12330]
Section 23.6 (https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/boot-features-spring-application.html#boot-features-web-environment)

> The algorithm used to determine a “web environment” is fairly simplistic (it is based on the presence of a few classes). If you need to override the default, you can use setWebEnvironment(boolean webEnvironment).
>
> It is also possible to take complete control of the ApplicationContext type that is used by calling setApplicationContextClass(…​).
> 
> Tip. It is often desirable to call setWebEnvironment(false) when using SpringApplication within a JUnit test.

The reference guide introduces that to use [`setWebEnvironment(boolean webEnvironment)`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L954) to override the default. However, this method has been deprecated since Spring Boot 2.0.0, and it is recommended to replace this method with [`setWebApplicationType(WebApplicationType webApplicationType)`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L965).

I think the guide should be updated accordingly.

**Comment by snicoll** [comment]
@jacobis good catch, thank you!

**Comment by breath-of-archangel** [comment]
Yes, spring boot 2.0
