### ISSUE TITLE
Spring boot 2.0 Web client block execution hold application

### ISSUE THREAD

**Issue by Pasha0093** [spring-projects/spring-boot#12338]
I move my application to use spring-boot 2.0.0.RELEASE, and logic with WebClient stop working.
```

String resp =  WebClient.create("https://stackoverflow.com/questions/7506392/how-to-create-android-facebook-key-hash").get().retrieve()
            .bodyToMono(String.class)
            .block();
log.info(resp);
```

When this code execute application just hold 
Important thing with 2.0.0.RC2 its working 
What it can be ? thanks

**Comment by wilkinsona** [comment]
The example works for me using the dependencies provided by Spring Boot 2.0.0.RELEASE. Note that none of the code involved in your example is part of Spring Boot. `WebClient` is part of Spring Framework and it builds upon Reactor Netty. If you'd like to pursue this, you should create a minimal example that reproduces the problem and open a Spring Framework or Reactor Netty issue as appropriate.
