### ISSUE TITLE
I want to collect all the metrics of HikariPool(HikariCP)

### ISSUE THREAD

**Issue by matsumana** [spring-projects/spring-boot#12347]
In Spring Boot 2.0, the default connection pool library has been changed to HikariCP.
But in HikariPool, only the `active` is exported so far.

- https://github.com/spring-projects/spring-boot/blob/v2.0.0.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/jdbc/DataSourcePoolMetrics.java#L72
- https://github.com/spring-projects/spring-boot/blob/v2.0.0.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/metadata/HikariDataSourcePoolMetadata.java#L39-L52

HikariPool has the following metrics, so I want to collect everything.

- https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.7.8/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L333-L359

Perhaps, it can be realized by customizing DataSourcePoolMetricsAutoConfiguration and DataSourcePoolMetrics by myself, but I wish Spring Boot to implement it standardly.

I checked this issue with micrometer + micrometer-registry-prometheus.

**Comment by wilkinsona** [comment]
Hikari has its own Micrometer integration which Spring Boot auto-configures. The names of those metrics are all prefixed with `hikaricp.connections` and tagged with the pool name.
