### ISSUE TITLE
Default application.properties ignored in 2.0.0

### ISSUE THREAD

**Issue by sakhno** [spring-projects/spring-boot#12343]
After updating to Spring Boot 2.0.0, if environment properties contains --spring.config.location=/file/path/application.properties, property files located in default places such as root classpath is ignored. 
As I understand docs, both files should be loaded and external file should override only duplicate 
properties, and it works this way in 1.5.6.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-location
