### ISSUE TITLE
Testing repositories with custom factory bean

### ISSUE THREAD

**Issue by heruan** [spring-projects/spring-boot#12349]
I need to test repositories which are created via a custom `JpaRepositoryFactoryBean`, but this seems not possible (or clear) with the testing suite provided by Spring Boot.

Documentation instructs to use `@DataJpaTest` which setups a safe testing environment for Spring Data repositories, but how can I specify a custom configuration?

Example project: https://github.com/heruan/spring-data-test

Following [this SO answer](https://stackoverflow.com/a/43706077/1006669) to a similar problem, I tried to specify a custom JPA configuration class via `@ContextConfiguration` and that seemed to work but eventually it fails with this exception:

```
UnsatisfiedDependencyException: Error creating bean with name 'myEntityRepository':
Unsatisfied dependency expressed through constructor parameter 1: Ambiguous argument
values for parameter of type [org.springframework.transaction.PlatformTransactionManager]
- did you specify the correct bean references as arguments?
```

as if it's unable to hook a transaction manager to the factory bean.

**Comment by heruan** [comment]
Worth noting Spring documentations states:

> Transactional support is provided to a test via a `PlatformTransactionManager` bean defined in the test’s application context.
— https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testing-tx

so maybe it's just a bean order issue e.g. the repository factory is constructed before the transaction manager is made available.

**Comment by wilkinsona** [comment]
Thanks for the sample. I haven't finished digging into exactly what's happening, but your injection of `PlatformTransactionManager` into your custom JPA repository factory bean means that you're relying on dependency autowiring into a factory bean which [can cause some weird issues](https://jira.spring.io/browse/SPR-9255).

**Comment by heruan** [comment]
That's interesting. The real use case of this is to return `Stream`s from repositories which will open transactions when they are actually consumed, so I need the `PlatformTransactionManager` on my custom repository implementation and the only way I've found to do this is to use a custom repository factory bean (and it works running the application normally, it just fails in tests). Of course, I'm open to other ways to provide the transaction manager to my repositories.

**Comment by heruan** [comment]
Could the cause of this be that `@DataJpaTest` contains `@AutoConfigureDataJpa` which activates this factory chain at [spring-boot-test-autoconfigure/src/main/resources/META-INF/spring.factories#L6](https://github.com/spring-projects/spring-boot/blob/d3c34ee3d1bfd3db4a98678c524e145ef9bca51c/spring-boot-project/spring-boot-test-autoconfigure/src/main/resources/META-INF/spring.factories#L6):

```
org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureDataJpa=\
org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,\
org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration,\
org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
```

where the `TransactionAutoConfiguration` has the lowest precedence, therefore not being available when creating repositories?

**Comment by wilkinsona** [comment]
Looking a bit more closely (and getting a bit out of my depth with Spring Data), I've just noticed the special handling of the transaction manager in `TransactionalRepositoryFactoryBeanSupport`, a super-class of your custom factory bean. It's configured with the transaction manager's name, and then passes that into `TransactionalRepositoryProxyPostProcessor` so that it can be used by `TransactionInterceptor`. It's interesting that it does it this way, rather than creating the interceptor with the `PlatformTransactionManager` instance directly. This is all pointing towards injecting the `PlatformTransactionManager` into your factory bean not being the right way to do this.

**Comment by heruan** [comment]
Whoa, great catch!

> This is all pointing towards injecting the `PlatformTransactionManager` into your factory bean not being the right way to do this.

Well, I'll investigate other ways to get the transaction manager on my repositories then. Of course I'm open to suggestions!

**Comment by wilkinsona** [comment]
I think I'd override the setters for the bean factory and the transaction manager name and then retrieve the transaction manager from the bean factory when it's needed. Something like this:

```diff
diff --git a/src/main/java/it/axians/spring/MyCustomJpaRepositoryFactoryBean.java b/src/main/java/it/axians/spring/MyCustomJpaRepositoryFactoryBean.java
index 2e1c6ef..050983d 100644
--- a/src/main/java/it/axians/spring/MyCustomJpaRepositoryFactoryBean.java
+++ b/src/main/java/it/axians/spring/MyCustomJpaRepositoryFactoryBean.java
@@ -2,6 +2,7 @@ package it.axians.spring;

 import javax.persistence.EntityManager;

+import org.springframework.beans.factory.BeanFactory;
 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.data.jpa.repository.support.JpaEntityInformation;
 import org.springframework.data.jpa.repository.support.JpaRepositoryFactory;
@@ -10,24 +11,37 @@ import org.springframework.data.jpa.repository.support.SimpleJpaRepository;
 import org.springframework.data.repository.core.RepositoryInformation;
 import org.springframework.data.repository.core.RepositoryMetadata;
 import org.springframework.data.repository.core.support.RepositoryFactorySupport;
+import org.springframework.data.repository.util.TxUtils;
 import org.springframework.transaction.PlatformTransactionManager;

 public class MyCustomJpaRepositoryFactoryBean<R extends JpaRepository<T, I>, T, I>
         extends JpaRepositoryFactoryBean<R, T, I> {

-    private PlatformTransactionManager transactionManager;
+       private String transactionManagerName = TxUtils.DEFAULT_TRANSACTION_MANAGER;

-    public MyCustomJpaRepositoryFactoryBean(Class<? extends R> repositoryInterface,
-            PlatformTransactionManager transactionManager) {
+       private BeanFactory beanFactory;
+
+    public MyCustomJpaRepositoryFactoryBean(Class<? extends R> repositoryInterface) {
         super(repositoryInterface);
-        this.transactionManager = transactionManager;
     }

-    @Override
+       @Override
+       public void setTransactionManager(String transactionManager) {
+               super.setTransactionManager(transactionManager);
+               this.transactionManagerName = transactionManager;
+       }
+
+       @Override
+       public void setBeanFactory(BeanFactory beanFactory) {
+               super.setBeanFactory(beanFactory);
+               this.beanFactory = beanFactory;
+       }
+
+       @Override
     protected RepositoryFactorySupport createRepositoryFactory(
             EntityManager entityManager) {
         return new MyCustomRepositoryFactory<>(entityManager,
-                this.transactionManager);
+                this.beanFactory.getBean(this.transactionManagerName, PlatformTransactionManager.class));
     }

     private static class MyCustomRepositoryFactory<T>
```

I'm going to close this one as I don't think there's a problem in Spring Boot. If you'd like some more guidance please feel free to come and chat on Gitter in the [Spring Boot](https://gitter.im/spring-projects/spring-boot) or [Spring Data](https://gitter.im/spring-projects/spring-data) rooms.
