### ISSUE TITLE
[Enhancement] Add auto-configured RestTemplate

### ISSUE THREAD

**Issue by cernadasjuan** [spring-projects/spring-boot#12351]
Hi,

It's possible to add a basic autoconfigured RestTemplate? In all my projects I am creating a RestTemplate bean doing:

```java

@Bean
public RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder) {
     return restTemplateBuilder.build();
}

```

I think that it is a common situation when we need to consume a simple rest api, and It will be very useful to avoid boilerplate code.

Thanks!

**Comment by wilkinsona** [comment]
Thanks for the suggestion but it was a deliberate choice to just auto-configure a builder rather than a RestTemplate itself. Please see https://github.com/spring-projects/spring-boot/issues/5507 some of the background.
