### ISSUE TITLE
Bug report about actuator /health endpoint

### ISSUE THREAD

**Issue by pcyan** [spring-projects/spring-boot#12359]
I try to use spring-boot-starter-actuator while my db connection is disable. 
When I try to access `health` endpoint, I didn't get any response or any output in log.
But other endpoint such as `logfile` is fine.
I think maybe there is a problem while `health` endpoint processing database connection.
And I hope I can get some feedback in log in this situation.

我在数据库连接有问题的时候使用了spring-boot-starter-actuator.
然后通过浏览器访问 `health`节点,发现浏览器没有任何返回,日志也没有打印东西.
但是其他节点例如`logfile`却是正常的
所以我觉得这里应该是`health`这个节点在处理数据库连接的时候有点问题
我希望遇到这种情况的时候能有日志反馈,让我知道`health`不能访问是因为这种原因

**Comment by pcyan** [comment]
@wilkinsona I found the problem.
When we have multi datasource config, one is working and other is not working, application will start as usual, and connection pool will try to connect the not working db.At this time I cannot get any reponse from `/health`.

Here is a [repo](https://github.com/pcyan/SpringBootDemo) contains two profile.
you can use it to reproduce the problem.

**Comment by philwebb** [comment]
@pcyan There's a lot of moving parts in that sample. Can you please explain exactly what steps we need to follow to replicate the issue? We don't have a local Oracle DB server.

**Comment by pcyan** [comment]
It's not about the other part or oracle.
1. we have 2 datasource config, make it work with druid connection pool.
2. the first datasource is connectable and the other is unable to connect.
3. run application. we cannot get any response from `/health` but other like `/logfile` is fine.

**Comment by snicoll** [comment]
@pcyan the purpose of a sample is that we can "just run it" to reproduce the issue. You could use an in-memory H2 database for the first datasource and some IP that won't connect for the other. If we have to do something manually to reproduce your problem, we're going to spend time with zero guarantee that we're actually helping you.

Could you please rework your sample so that we have full instructions (minimal if possible) to reproduce the problem?

**Comment by pcyan** [comment]
我觉得不需要浪费时间了

**Comment by snicoll** [comment]
Courtesy of Google translate:
> I do not think I need to waste time

I am sorry you feel that way but we can't justify spending time to help you if you can't spend the time to showcase the problem you are experiencing. If you change your mind and attach a sample we can run, we can reconsider.
