### ISSUE TITLE
Upgrading to Spring Boot 2.0 breaks @CrossOrigin

### ISSUE THREAD

**Issue by striderarun** [spring-projects/spring-boot#12356]
I have a Spring Boot REST application running on port 8080 with a front end Angular app running on port 4200. I was using @CrossOrigin annotation on my rest controller in order to make HTTP REST from Angular app running on 4200 to my backend Spring Boot server running on 8080.

After upgrading from Spring Boot 1.5.10 to 2.0, the cross origin annotation no longer works and calls from Angular app to Spring Boot app fail with 
"No 'Access-Control-Allow-Origin' header is present on the requested resource"

Does anyone face a similar issue?

**Comment by wilkinsona** [comment]
> Does anyone face a similar issue?

It’s very hard to say with the information you have provided. If you would like us to spend tile investigating please spend some time providing a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) of your problem.

**Comment by striderarun** [comment]
Looks like an incompatibility between the version of Angular http and Spring Boot 2.0. Closing this issue.

**Comment by bclozel** [comment]
@striderarun In case others face this problem as well, could you explain what you've found out about this incompatibility and maybe how to fix it?

**Comment by striderarun** [comment]
@bclozel Turns out that the actual cause was that I had set server.contextPath in my environment.properties. 
After building with Spring Boot 2.0, this property was invalid. So the angular app was making the wrong REST call. The 404 error was wrapped inside a CORS error which confused me.
