### ISSUE TITLE
Application fails to start when an environment variable named SERVER is present

### ISSUE THREAD

**Issue by phloww** [spring-projects/spring-boot#12357]
After Upgrading my Application from Boot 1.5.x to Boot 2.0.0 it refuses to start.
The error is: 

```
Failed to bind properties under 'server' to org.springframework.boot.autoconfigure.web.ServerProperties:

    Property: server
    Value: foobar
    Origin: class path resource [application.properties]:1:10
    Reason: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.boot.context.properties.ConfigurationProperties org.springframework.boot.autoconfigure.web.ServerProperties]`
```

How to reproduce: 

Create a Spring Boot 2.0.0 Project using Spring initializer.
Add the Property `SERVER = foobar` to application.properties

I have seen Issue #10945 beeing marked as closed, but the problem seems to be still out there? Or maybe i am doing something wrong, then help would be much appreciated

Sidenote: if property is renamed from `SERVER` to `SERVER.foo`, application starts without error.

**Comment by snicoll** [comment]
Thanks for the report. It looks like #10945 was re-introduced when we refactored the way binding works in recent milestones.

**Comment by snicoll** [comment]
This test in `ServerPropertiesTests` reproduces the issue:

```java
@Test
public void serverPropertyIsIgnored() throws Exception {
    bind("SERVER", "test");
}
```
