### ISSUE TITLE
Spring boot and websphere issue

### ISSUE THREAD

**Issue by sonampanchmiya** [spring-projects/spring-boot#12369]
We are using spring boot for the first time in our project. Attaching pom.xml for reference.

Issue: Spring boot application starts up fine. But if we do not access it for few days the application goes down and gives 404 error. Why is the application going down? In websphere application console the EAR status shows as started but no URL's of controller are accessible. Is it automatically unregistering the beans? I have not included Tomcat JAR's during runtime as we are running application in websphere. Is tomcat JAR manadatory? In pom.xml for tomcat jar scope provided is there to use it only during compile time.

[pom and jar list.zip](https://github.com/spring-projects/spring-boot/files/1786231/pom.and.jar.list.zip)

Below are the details of project:
1) Spring boot 1.5.9
2) Packaged as WAR
3) Websphere application server
4) Dependendant JARs are not directly included in WAR. Instead we created a shared library in websphere and mapped it to WAR to pick up JAR's at runtime. This reduces the WAR size. List of JAR's is attached in zip.

**Comment by wilkinsona** [comment]
There's nothing in Spring Boot that would cause it to unregister any beans or request mappings after a certain amount of time. Unfortunately, without some more information, it's impossible to diagnose what may be happening here. It's not even clear that it's a problem with Spring Boot and may actually be a problem in WebSphere. Have you contacted IBM support?

**Comment by sonampanchmiya** [comment]
There are other spring boot application on the server which are working fine. I compared the JAR's and Pom files as well with them which seems fine. On internet I saw links where many people faced issue that spring boot shuts down automatically.

**Comment by wilkinsona** [comment]
If there are other Spring Boot applications that are fine, it would suggest that it’s not a general Spring Boot problem. It may be a problem in your application, a problem in Spring Boot that’s specific to how your application is using it, or a problem with WebSphere that’s specific to this one application. You haven’t told us anything about your application so I’m not sure how you expect us to be able to help you.

If you’d like us to spend some more time on your problem you are going to have to spend some time showing why it’s a problem with Spring Boot.

**Comment by sonampanchmiya** [comment]
Right now I have enabled all org.springframework logs to monitor if something is going wrong. 

Before few days I saw same issue and observed this in logs:
Unregistering JMX-exposed beans on shutdown

We did not stop or restart the JVM but still this came in logs and later on started getting 404 error. But I thought this will be a temporary issue and redeployed application and continued with testing.

Our application is a webservice. Each service is a WAR inside an EAR. 1 EAR has 10 WAR's as there are 10 different web service. 
Please let me know if anything specific I must put in comments related to the application.

**Comment by wilkinsona** [comment]
> Unregistering JMX-exposed beans on shutdown

That log is output when the application context is closed. Spring Boot will not donthat itself so something else must have done so. Perhaps you have the shutdown endpoint enabled and something called it?

Debug logging for `org.springframework` should allow you to see what’s happening.

**Comment by sonampanchmiya** [comment]
endpoints.jmx.unique-names = true this is added in my property file as we have multiple spring boot application in same JVM. can this be causing the issue?

**Comment by wilkinsona** [comment]
No. Please provide the log output when the problem occurs and we can take things from there.

**Comment by sonampanchmiya** [comment]
We did deployment today. Attaching start up logs in zip. Also I found some old logs when application went down attached as validation.log in zip. Please let me know if something can be debugged from this. I can see some shutdownenpoint related logs but not sure if it is causing it.

Do we need 

[logs.zip](https://github.com/spring-projects/spring-boot/files/1793886/logs.zip)

**Comment by wilkinsona** [comment]
There's nothing in those logs that suggests there's a problem with Spring Boot.

`startup.log` appears to show part of the initialisation of an application. It does not show the application being closed.

`validation.log` shows 20 application contexts being closed:

```
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3ee14f96: startup date [Thu Feb 15 08:49:36 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@eeb1d996: startup date [Thu Feb 15 08:48:25 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3392cb4e: startup date [Thu Feb 15 08:47:14 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@bfa89fe: startup date [Thu Feb 15 08:46:02 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@e341aec: startup date [Thu Feb 15 08:44:49 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@b5c2468: startup date [Thu Feb 15 08:43:40 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:43[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@dc7a18d5: startup date [Thu Feb 15 08:42:42 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:44[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a7ff887e: startup date [Thu Feb 15 08:42:12 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:44[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2c2740b: startup date [Thu Feb 15 08:41:17 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 08:50:44[Default : 2] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7aa97d0d: startup date [Thu Feb 15 08:40:59 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@b7eef677: startup date [Thu Feb 15 09:28:11 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@47e9405c: startup date [Thu Feb 15 09:27:00 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@cdfecb65: startup date [Thu Feb 15 09:25:48 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@fcdba615: startup date [Thu Feb 15 09:24:37 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@9cb93d8: startup date [Thu Feb 15 09:23:25 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@97249fe5: startup date [Thu Feb 15 09:22:14 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:18[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@53490021: startup date [Thu Feb 15 09:21:16 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:19[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@ca6be618: startup date [Thu Feb 15 09:20:46 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:19[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@e30cf204: startup date [Thu Feb 15 09:19:52 EST 2018]; root of context hierarchy
[INFO ] 2018-02-15 09:29:19[Default : 5] INFO  AnnotationConfigEmbeddedWebApplicationContext:doClose:984-Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@f3fb8856: startup date [Thu Feb 15 09:19:33 EST 2018]; root of context hierarchy
```

All 20 appear to be normal and none of them matches the description of an application shutting down "if we do not access it for few days". In each case the application context was closed just a few minutes after it was started.

Without an accurate description of the problem, or any evidence that the problem has anything to do with Spring Boot, it's impossible for us to help you. As I said above, please provide the log output when the problem occurs. If you cannot do that, then we will have to close this issue as we simply can't afford to spend time reading through logs that don't capture the problem and exhibit behaviour that doesn't match the description that you've given us.

**Comment by sonampanchmiya** [comment]
Sorry for the inconvinience. Even I am struggling with getting actual data from logs to prove the issue.
But this is a pattern we observed 2-3 times. When we do not use the application for few days we start getting 404 error. 
You can close the issue as I do not have enough data to provide to you right away.  
 I am checking with both IBM and Spring boot team to resolve the issue. If I see something in logs to provide I will create another issue. Thanks for your help.

**Comment by wilkinsona** [comment]
Thanks, I'll close this one then. If you find something in the logs, please comment on this issue and we can re-open it. No need for another issue.
