### ISSUE TITLE
Thymeleaf view not resolved with WebFlux

### ISSUE THREAD

**Issue by rkudryashov** [spring-projects/spring-boot#12375]
I tried to create custom login page on Spring WebFlux, Spring Security and Thymeleaf. But by some reason 'login' view isn't resolved. I have created pull request that contains minimal example reproducing the problem: 
https://github.com/spring-projects/spring-boot-issues/pull/76
(https://github.com/rkudryashov/spring-boot-issues/tree/master/gh-12375) 
If you start application and then try to go to any url you will be redirected to localhost:8080/login and 'login' view will not be resolved.
I think problem appears because `org.springframework.web.reactive.result.view.ViewResolutionResultHandler#ViewResolutionResultHandler(java.util.List<org.springframework.web.reactive.result.view.ViewResolver>, org.springframework.web.reactive.accept.RequestedContentTypeResolver)` called before `org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration.ThymeleafWebMvcConfiguration.ThymeleafViewResolverConfiguration#thymeleafViewResolver`. And have no idea how to fix this.

**Comment by bclozel** [comment]
Thanks for the repro project @rkudryashov !
As [stated in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-webflux-auto-configuration), adding `@EnableWebFlux` to your app means you want to take full control over the WebFlux configuration.

In this case, removing that annotation solves the issue.

**Comment by rkudryashov** [comment]
@bclozel thanks for the quick feedback!
The solution is so simple that I don't understand how I didn't tried this.
