### ISSUE TITLE
JPA does not work as expected when use nativeQuery=true

### ISSUE THREAD

**Issue by codefordream2014** [spring-projects/spring-boot#12379]
My problem is the result order is not correct as expected when use nativeQuery=true.
I'm not sure whether this is a defect or not. 

you can download the source code in below repository and  run the test cases :
https://github.com/roberthunt/spring-data-native-query-projection

![image](https://user-images.githubusercontent.com/17540154/37083108-70b8e9d0-2229-11e8-9360-77c8526b3af8.png)

as displayed in the screenshot 
personSummay object should return {name: Bob,age:33}
but the actual is {name:33,age:Bob}    
  
below is the main source code screenshot:
1.PersonRepository.java
![image](https://user-images.githubusercontent.com/17540154/37083276-ffff4184-2229-11e8-904b-216faf7666be.png)
2.Person.java
![image](https://user-images.githubusercontent.com/17540154/37083328-28914af2-222a-11e8-95f8-38a5c555c5ab.png)
3.PersonSummary.java
![image](https://user-images.githubusercontent.com/17540154/37083361-3c103a66-222a-11e8-9b2c-3cdca16730c2.png)
4.application.properties
![image](https://user-images.githubusercontent.com/17540154/37083412-657b166e-222a-11e8-9b99-6bcff4732112.png)

**Comment by wilkinsona** [comment]
The repository that you have linked to is a year old and was created to demonstrate [a bug in Spring Data JPA] (https://jira.spring.io/browse/DATAJPA-980). It has been fixed in Spring Data Hopper SR 12, Spring Data Ingalls SR 8 (used by Spring Boot 1.5.x from 1.5.8 onwards), and Spring Data Kay (used by Spring Boot 2.0.0).

**Comment by wilkinsona** [comment]
You should open a Spring Data JPA issue with a sample of your own making that reproduces the problem using Spring Boot 1.5.10 and the latest version of Spring Data Ingalls.
