### ISSUE TITLE
Cookie Value and Redis Session Value is different after upgrade to Spring boot 2.0.0.1

### ISSUE THREAD

**Issue by sanjayagnani92** [spring-projects/spring-boot#12376]
Am basically using two different spring boot application one for handling authentication and other for authorization using Preauthorize annotation from the value stored in Redis Session Store.
spring-boot-starter-redis is used to externalize user sessions

Cookie Value generated in authentication process  is different than the value stored in redis Session.

**Comment by wilkinsona** [comment]
Spring Boot itself doesn’t deal with the Session cookie. As you’re using Redis as a session store, I assume you are using Spring Session. Please raise a [Spring Session issue](https://github.com/spring-session/issues), providing a sample that reproduces the problem.
