### ISSUE TITLE
Actuator health for DB doesn't work when using JSYPT encrypted password in application.properties

### ISSUE THREAD

**Issue by amitommishra** [spring-projects/spring-boot#12373]

**Comment by amitommishra** [comment]
**Build.gradle**
using com.github.ulisesbocchio:jasypt-spring-boot-starter

**in Application.properties:**
spring.datasource.password=ENC(encrypted_password)

when calling actuator health it is not working. It works when i use non encrypted password.

Looks like actuator is not taking care of decryption when Jsypt is used.

**Comment by wilkinsona** [comment]
Please read the [documentation](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/v1.17/README.md). You cannot place an encrypted property in `application.properties`.

**Comment by amitommishra** [comment]
**reference:**
http://www.jasypt.org/encrypting-configuration.html
https://stackoverflow.com/a/23859824/544918

Can you please help me understand it why we cannot use as i see it mentioned same way in jsypt site

**Comment by wilkinsona** [comment]
The documentation that I linked to above describes how to use `jasypt-spring-boot`. I've never used it before so I can only recommend that you read the documentation and use one of the two approaches that it describes (`@EnableEncryptableProperties` or customization of your application's `Environment`).
