### ISSUE TITLE
Spring Boot Reference Guide - 13.5 Starters - spring-boot-starter-jdbc infomation outdated

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-boot#12387]
Spring Boot Reference Guide, part 13.5 "Starters" still mentions Tomcat JDBC connection pool, but Tomcat JDBC was replaced by HikariCP in 2.0.0.

See: `spring-boot-starter-jdbc | Starter for using JDBC with the Tomcat JDBC connection pool` in
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-starter

It would be nice if this was fixed.

Thanks!

**Comment by snicoll** [comment]
@PascalSchumacher good catch, thank you!

**Comment by PascalSchumacher** [comment]
Thanks for fixing! :+1:
