### ISSUE TITLE
additionalProperty values should not be required when using the build-info goal of the spring-boot-maven-plugin

### ISSUE THREAD

**Issue by eztinkerdreams** [spring-projects/spring-boot#12382]
I would like to make an enhancement request. Currently when using the build-info goal of the spring-boot maven plugin, the plugin will generate an error if any of the 'additionalProperties' evaluate to null or empty strings. 

Can this behavior made optional, or just removed all together? I think it is perfectly acceptable to have a property in the file with no value. I've a use case for this in my build system.

**Comment by wilkinsona** [comment]
> the plugin will generate an error if any of the 'additionalProperties' evaluate to null or empty strings.

I believe you'll only get an error if the value is `null`. `null` values are rejected as Java's `Properties` class does not support `null` values. If we didn't fail-fast the diagnostics would be poor (see https://github.com/spring-projects/spring-boot/issues/6724).

Removing the failure with a `null` value would be a breaking change for anyone who is relying on it catching a problem with their build configuration. This would have to wait for 3.0. The alternative would be to add a configuration option to control the behaviour. We could coerce `null` to an empty value or we could remove the property altogether. This would add complexity and that would need to be justified.

What's your usecase for wanting to tolerate `null` values?

**Comment by eztinkerdreams** [comment]
@wilkinsona I'm using the [CI Friendly Versions Properties](https://maven.apache.org/maven-ci-friendly.html) of maven. I pass this in as an external argument in my CI pipeline. In the process of creating a 'release' I don't use changelist, so it gets passed in as empty. 

```
mvn spring-boot:build-info "-Dchangelist=${SOME_VAR}
```
I am able to work out a way to pass in an empty value. If I try to pass in escaped quotes, it doesn't error, but treats the value as literally two double quotes. So all other strings where I use this value get concatenated/formatted with two double quotes as the value.
For example, given my pom.xml is configured with this `<version>${revision}${sha1}${changelist}</version>`

```
mvn spring-boot:build-info -Dgit.commit.id.abbrev=abcde "-Dchangelist=\"\""
```
produces:
```
build.version=v1.1.8-abcde""
build.changelist=""
```

Obviously there are a variety of other ways for me to solve this, and I don't really need suggestions on how to code around this, there are probably dozens. 

What would be ideal is if I could configure the plugin to treat nulls as empty strings. i.e if a value is null, write it out as an empty property value, instead of throwing an error.

Pretty low priority, I can work around it.

```
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <executable>true</executable>
                    <additionalProperties>
                        <sha>${sha1}</sha>
                        <changelist>${changelist}</changelist>
                        <revision>${revision}</revision>
                        <revision.major>${revision.major}</revision.major>
                        <revision.minor>${revision.minor}</revision.minor>
                        <revision.patch>${revision.patch}</revision.patch>
                    </additionalProperties>
                </configuration>
            </plugin>
```

**Comment by wilkinsona** [comment]
Thanks for the explanation. If you can work around it, then I think that means that the additional complexity of the configuration option isn't warranted so I'm going to close this one for now at least. If it turns out that you can't work around it, then please let us know and we can reconsider.

**Comment by eztinkerdreams** [comment]
Workaround if anyone else runs into this issue... I think this should be configurable... But its probably obscure enough that no one else will need it. 
```
<properties> 
        <build-info.outputFile>${project.build.directory}/classes/META-INF/build-info.properties</build-info.outputFile> 
</properties>
```
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <executable>true</executable>
                    <additionalProperties>
                        <sha>${sha1}</sha>
                       <!-- Always write out the property with an empty string, so that replacer can find and fix it. -->
                        <changelist>""</changelist>
                        <revision>${revision}</revision>
                        <revision.major>${revision.major}</revision.major>
                        <revision.minor>${revision.minor}</revision.minor>
                        <revision.patch>${revision.patch}</revision.patch>
                    </additionalProperties>
                    <outputFile>${build-info.outputFile}</outputFile>
                </configuration>
                <executions>
                    <execution>
                        <!--
                            Generates the target/classes/META-INF/build-info.properties file
                            ref: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
                        -->
                        <id>generate-build-info</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
```
            <plugin>
                <groupId>com.google.code.maven-replacer-plugin</groupId>
                <artifactId>replacer</artifactId>
                <version>1.5.3</version>
                <executions>
                    <execution>
                        <id>replace-empty-changelist-value</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <regex>true</regex>
                            <regexFlags>
                                <regexFlag>MULTILINE</regexFlag>
                            </regexFlags>
                            <value>build.changelist=\"${changelist}\"</value>
                            <token>^build.changelist=\"\"$</token>
                            <includes>
                                    <include>${build-info.outputFile}</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Works with 
```
mvn spring-boot:build-info replacer:replace@replace-empty-changelist-value  -Dchangelist=
```
