### ISSUE TITLE
Property Override not Working For YML Files.

### ISSUE THREAD

**Issue by selmantayyar** [spring-projects/spring-boot#12388]
Spring Boot Version:**1.5.10**

When I try to override a property in application.yml file while executing some tests, application still uses the main property instead of the one in application-test.yml.

I created a simple project to reproduce the issue:
https://github.com/selmantayyar/SpringBootPropertyOverrideIssue

Please be aware that with *.properties file,issue does not exist.

**Comment by snicoll** [comment]
Thanks for the sample. `@PropertySource` and `TestPropertySource` do not support yaml files.

**Comment by selmantayyar** [comment]
Thanks for the prompt reply!
So can I assume that only way to override YAML is place application.yml under test/resources/config directory?

**Comment by snicoll** [comment]
No, `@SpringBootTest` has a `properties` attribute you can use to override individual properties.
