### ISSUE TITLE
Eclipse's "Terminate" `spring-boot:run` doesn't terminate Tomcat

### ISSUE THREAD

**Issue by raphinesse** [spring-projects/spring-boot#1239]
Execute `spring-boot:run` via an Eclipse maven build run configuration. Hit the "Terminate" button on Eclipse's "Console" view.

Expected: Maven and Spring application are stopped
Actual: Maven is stopped, but Tomcat still listens

Spring Boot 1.1.4.REALEASE
Eclipse Luna - Java EE
Windows 7

**Comment by odedpeer** [comment]
When you run the Spring Boot plugin you get hot deploy of code. When you run your application as a Java process you lose this capability

**Comment by snicoll** [comment]
This issue was closed over 6 months ago. If you want to get noticed, please make sure to comment on an opened issue (or create one of your own). I'd argue for the exact opposite actually so if you create an issue, please make sure to provide enough details about your setup.

**Comment by zteater** [comment]
dev-tools (in particular hot swapping) does not work when running as a application alone. There seems to be only 2 solutions. 1) on console terminate, manually terminate Java process for tomcat 2) execute mvn spring-boot:run in a terminal outside of eclipse.

**Comment by Vomitory1** [comment]
JUST CLOSE THE TERMINAL ON ECLIPSE---

 YOU COULD RUN ASS SRPING BOOT APP

**Comment by jordihs** [comment]
For reference of future visitors of this thread: to avoid forking the process and thus fully stopping spring boot from eclipse, open "run configurations", edit the maven launch you defined for your project, and under the "java options" tab, add -Dfork=false to the VM options list.

**Comment by gsugambit** [comment]
@jordihs I'm not sure why you aren't getting more praise here. Thanks for pointing this out as i was about ready to either 1) not use dev tools or 2) always run it outside of eclipses. Appreciate it a lot man

**Comment by gsugambit** [comment]
@jordihs actually it not really working lmfao

**Comment by wilkinsona** [comment]
@gsugambit Running the Maven goal from Eclipse is pointless. You should run your application’s main method directly instead (right-click, Run As -> Java Application).

**Comment by gsugambit** [comment]
@wilkinsona yeah i've switched to just running it from the command prompt. I also had issues with java home of the command prompt in eclipse, it's getting some ridiculously old one and it's not from the JAVA_HOME of my PC so I'm just using the command prompt from the OS so I still get the live reload functionality. I love that out of spring dev tools

**Comment by wilkinsona** [comment]
There’s no need to use a command prompt in or out of Eclipse. IMO, the easiest way to run a Spring Boot application during development is to run the main method directly in your IDE.

**Comment by gsugambit** [comment]
@wilkinsona if you do that you cannot take advantage of spring dev tools and live reload each time you save correct? You would have to relaunch the application each time?

**Comment by wilkinsona** [comment]
No. Both will work.
