### ISSUE TITLE
The issue still exists when I upgrade Spring Boot to 1.5.10.RELEASE for #12379

### ISSUE THREAD

**Issue by codefordream2014** [spring-projects/spring-boot#12396]
Hi,

the issue link : https://github.com/spring-projects/spring-boot/issues/12379

I still encounter the issue when I upgrade Spring Boot to 1.5.10.RELEASE in which version the bug should be fixed. But it works fine for 2.0.0.RELEASE. For my project I can not upgrade to spring boot 2.0. can you give me some advice?

**Comment by wilkinsona** [comment]
Duplicate of #12379.
