### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by danieldonev** [spring-projects/spring-boot#12397]
It would be really useful to have CHANGELOG.md file, where we can see summary of the changeling of each release.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We already provide comprehensive release notes for major and minor releases on the [wiki](https://github.com/spring-projects/spring-boot/wiki). For maintenance releases the milestone page on GitHub provides a list of every issue that was part of the release.
