### ISSUE TITLE
Links with periods in them are not working in the wiki

### ISSUE THREAD

**Issue by olithissen** [spring-projects/spring-boot#12401]
Relative links with periods in them don't appear to be working in the wiki:

- [This one works](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9)
- [This one doesn't](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes)

This isn't an isolated issue with the Spring Boot wiki as can be seen here:

- [My demo wiki](https://github.com/olithissen/wiki-link-issue/wiki)

Can someone confirm this behavior? Did Github change something in the way they deliver wiki content recently?

**Comment by snicoll** [comment]
I've just noticed that myself and there's not much we can do about Github's infrastructure but we can use this issue to follow-up.

**Comment by wilkinsona** [comment]
I've emailed GitHub support and asked them to investigate.

**Comment by wilkinsona** [comment]
Response from GitHub support:

> Sorry for the trouble this is causing! This is a known issue that our team are working on resolving as we speak. I'll follow up with you as soon as the fix is deployed.

**Comment by wilkinsona** [comment]
The issue's been fixed.
