### ISSUE TITLE
Offer a good way to load single YAML file

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12412]
Now that we have the new `Binder`, it might be nice if people could quickly load a single YAML file easily. Currently the best we have is:

```java
YamlPropertiesFactoryBean properties = new YamlPropertiesFactoryBean();
properties.setResources(new ClassPathResource("cities.yml"));
MapConfigurationPropertySource source = new MapConfigurationPropertySource(properties.getObject());
```

**Comment by spencergibb** [comment]
Spring Cloud uses `YamlPropertiesFactoryBean` at least once here: https://github.com/spring-cloud/spring-cloud-config/blob/b96ba4454d9517ab2c49fe0e9a3d033e396c0f69/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepository.java#L122

**Comment by philwebb** [comment]
The new `spring.config.import` support removes a lot of the need for this one.
