### ISSUE TITLE
BuildProperties.getTime() returns null since Spring Boot 2.0.0.RELEASE

### ISSUE THREAD

**Issue by ewasscher** [spring-projects/spring-boot#12420]
Since I upgraded one of my projects from Spring Boot 2.0.0.RC2 to 2.0.0.RELEASE BuildProperties.getTime() always returns null. As my application writes build and git information to the log at startup this breaks the maven build process.

After a little troubleshooting I noticed that the format of build.time in the build-info.properties changed from:

build.time=2018-03-09T09\:13\:03+0100 (in RC2)

to:

build.time=2018-03-09T08\:04\:05.602Z (in RELEASE)

Please notice the trailing Z (to indicate Zulu time I suppose),  which I suspect to break parsing of the build.time property by the BuildProperties bean.

**Comment by snicoll** [comment]
Might be related to #10976

**Comment by wilkinsona** [comment]
I suspect it's a regression caused by [this change](https://github.com/spring-projects/spring-boot/commit/fdb9a1ea8fa62932824474e1b2a0dc0211115e37).

**Comment by snicoll** [comment]
Could very well given that Maven-based projects [aren't affected](http://start.spring.io/actuator/info) apparently.

**Comment by ewasscher** [comment]
I did notice that BuildProperties.getTime() in RC2 automatically seems to parse build.time as local time even though no timezone information was available for the property. This will not return the correct result if the application is deployed in another timezone than in which it was built.

To be clear: I do consider the change to write Zulu time in build-info.properties a good thing, but of course, as long as the parsing is changed accordingly.

**Comment by wilkinsona** [comment]
I understand what's happening now. The info endpoint doesn't show the problem as it falls back to using `get("time")` when `getTime()` returns `null`. `getTime()` is returning `null` because it's failing to parse the instant that's be formatted to a string using `DateTimeFormatter.ISO_INSTANT`.

**Comment by wilkinsona** [comment]
@ewasscher You can work around the problem in 2.0.0 by calling `get("time")` and turning it into an `Instant` using `DateTimeFormatter.ISO_INSTANT.parse(value, Instant::from)`.

**Comment by wilkinsona** [comment]
The updated test fails on Java 9 and 10.
