### ISSUE TITLE
Error in Building project

### ISSUE THREAD

**Issue by Sagarpayne** [spring-projects/spring-boot#12426]
Hi all need your help!!
I have created new project from https://start.spring.io/ with 2.0.0.RELEASE as starter.
Tried to build the project using the maven wrapper (mvnw spring-boot:run )
Got below error! 
find my pom.xml below ,
Thank you in advance ,
Sagar

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>myapp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>myapp</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by Sagarpayne** [comment]
the old one was close , hence opened new one !!

**Comment by Sagarpayne** [comment]
Error  I am getting


E:\API\myapp>mvnw clean
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.example:myapp >--------------------------
[INFO] Building myapp 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ myapp ---
[INFO] Deleting E:\API\myapp\target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.521 s
[INFO] Finished at: 2018-03-10T13:12:51+05:30
[INFO] ------------------------------------------------------------------------

E:\API\myapp>mvnw spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.example:myapp >--------------------------
[INFO] Building myapp 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.0.0.RELEASE:run (default-cli) > test-compil
e @ myapp >>>
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ myapp ---

[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ myapp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to E:\API\myapp\target\classes
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-ao
p\5.0.4.RELEASE\spring-aop-5.0.4.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-jd
bc\5.0.4.RELEASE\spring-jdbc-5.0.4.RELEASE.jar; invalid LOC header (bad signature
)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\hibernate\hibernate-core\
5.2.14.Final\hibernate-core-5.2.14.Final.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\data\spri
ng-data-jpa\2.0.5.RELEASE\spring-data-jpa-2.0.5.RELEASE.jar; invalid LOC header (
bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\data\spri
ng-data-commons\2.0.5.RELEASE\spring-data-commons-2.0.5.RELEASE.jar; invalid LOC
header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-we
b\5.0.4.RELEASE\spring-web-5.0.4.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-we
bmvc\5.0.4.RELEASE\spring-webmvc-5.0.4.RELEASE.jar; invalid LOC header (bad signa
ture)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-ex
pression\5.0.4.RELEASE\spring-expression-5.0.4.RELEASE.jar; invalid LOC header (b
ad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-co
re\5.0.4.RELEASE\spring-core-5.0.4.RELEASE.jar; invalid LOC header (bad signature
)
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ m
yapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\API\myapp\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ myapp
---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to E:\API\myapp\target\test-classes
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-ao
p\5.0.4.RELEASE\spring-aop-5.0.4.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-jd
bc\5.0.4.RELEASE\spring-jdbc-5.0.4.RELEASE.jar; invalid LOC header (bad signature
)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\hibernate\hibernate-core\
5.2.14.Final\hibernate-core-5.2.14.Final.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\data\spri
ng-data-jpa\2.0.5.RELEASE\spring-data-jpa-2.0.5.RELEASE.jar; invalid LOC header (
bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\data\spri
ng-data-commons\2.0.5.RELEASE\spring-data-commons-2.0.5.RELEASE.jar; invalid LOC
header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-we
b\5.0.4.RELEASE\spring-web-5.0.4.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-we
bmvc\5.0.4.RELEASE\spring-webmvc-5.0.4.RELEASE.jar; invalid LOC header (bad signa
ture)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-ex
pression\5.0.4.RELEASE\spring-expression-5.0.4.RELEASE.jar; invalid LOC header (b
ad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\boot\spri
ng-boot-test\2.0.0.RELEASE\spring-boot-test-2.0.0.RELEASE.jar; invalid LOC header
 (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\boot\spri
ng-boot-test-autoconfigure\2.0.0.RELEASE\spring-boot-test-autoconfigure-2.0.0.REL
EASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Sagar\.m2\repository\org\springframework\spring-co
re\5.0.4.RELEASE\spring-core-5.0.4.RELEASE.jar; invalid LOC header (bad signature
)
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.0.0.RELEASE:run (default-cli) < test-compil
e @ myapp <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.0.0.RELEASE:run (default-cli) @ myapp ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.199 s
[INFO] Finished at: 2018-03-10T13:13:12+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:
2.0.0.RELEASE:run (default-cli) on project myapp: Execution default-cli of goal o
rg.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:run failed: A requ
ired class was missing while executing org.springframework.boot:spring-boot-maven
-plugin:2.0.0.RELEASE:run: org/springframework/asm/ClassVisitor
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.springframework.boot:spring-boot-maven-plugin:2.0.0
.RELEASE
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Sagar/.m2/repository/org/springframework/boot/sp
ring-boot-maven-plugin/2.0.0.RELEASE/spring-boot-maven-plugin-2.0.0.RELEASE.jar
[ERROR] urls[1] = file:/C:/Users/Sagar/.m2/repository/org/springframework/boot/sp
ring-boot-loader-tools/2.0.0.RELEASE/spring-boot-loader-tools-2.0.0.RELEASE.jar
[ERROR] urls[2] = file:/C:/Users/Sagar/.m2/repository/org/springframework/spring-
core/5.0.4.RELEASE/spring-core-5.0.4.RELEASE.jar
[ERROR] urls[3] = file:/C:/Users/Sagar/.m2/repository/org/springframework/spring-
jcl/5.0.4.RELEASE/spring-jcl-5.0.4.RELEASE.jar
[ERROR] urls[4] = file:/C:/Users/Sagar/.m2/repository/org/apache/commons/commons-
compress/1.14/commons-compress-1.14.jar
[ERROR] urls[5] = file:/C:/Users/Sagar/.m2/repository/org/apache/maven/maven-arch
iver/2.6/maven-archiver-2.6.jar
[ERROR] urls[6] = file:/C:/Users/Sagar/.m2/repository/org/apache/maven/shared/mav
en-shared-utils/0.7/maven-shared-utils-0.7.jar
[ERROR] urls[7] = file:/C:/Users/Sagar/.m2/repository/com/google/code/findbugs/js
r305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[8] = file:/C:/Users/Sagar/.m2/repository/org/codehaus/plexus/plexus-
interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[9] = file:/C:/Users/Sagar/.m2/repository/org/eclipse/aether/aether-u
til/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[10] = file:/C:/Users/Sagar/.m2/repository/javax/enterprise/cdi-api/1
.0/cdi-api-1.0.jar
[ERROR] urls[11] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/sisu/sisu-gui
ce/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[12] = file:/C:/Users/Sagar/.m2/repository/aopalliance/aopalliance/1.
0/aopalliance-1.0.jar
[ERROR] urls[13] = file:/C:/Users/Sagar/.m2/repository/org/eclipse/sisu/org.eclip
se.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
[ERROR] urls[14] = file:/C:/Users/Sagar/.m2/repository/org/codehaus/plexus/plexus
-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[15] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/plexus/plexus
-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[16] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/plexus/plexus
-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[17] = file:/C:/Users/Sagar/.m2/repository/org/apache/maven/shared/ma
ven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[18] = file:/C:/Users/Sagar/.m2/repository/org/apache/xbean/xbean-ref
lect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[19] = file:/C:/Users/Sagar/.m2/repository/log4j/log4j/1.2.12/log4j-1
.2.12.jar
[ERROR] urls[20] = file:/C:/Users/Sagar/.m2/repository/commons-logging/commons-lo
gging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[21] = file:/C:/Users/Sagar/.m2/repository/com/google/collections/goo
gle-collections/1.0/google-collections-1.0.jar
[ERROR] urls[22] = file:/C:/Users/Sagar/.m2/repository/junit/junit/4.12/junit-4.1
2.jar
[ERROR] urls[23] = file:/C:/Users/Sagar/.m2/repository/org/hamcrest/hamcrest-core
/1.3/hamcrest-core-1.3.jar
[ERROR] urls[24] = file:/C:/Users/Sagar/.m2/repository/org/codehaus/plexus/plexus
-archiver/2.8.1/plexus-archiver-2.8.1.jar
[ERROR] urls[25] = file:/C:/Users/Sagar/.m2/repository/org/codehaus/plexus/plexus
-io/2.3.2/plexus-io-2.3.2.jar
[ERROR] urls[26] = file:/C:/Users/Sagar/.m2/repository/org/codehaus/plexus/plexus
-utils/3.0.24/plexus-utils-3.0.24.jar
[ERROR] urls[27] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/plexus/plexus
-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[28] = file:/C:/Users/Sagar/.m2/repository/org/apache/maven/plugins/m
aven-shade-plugin/2.2/maven-shade-plugin-2.2.jar
[ERROR] urls[29] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/sisu/sisu-inj
ect-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[30] = file:/C:/Users/Sagar/.m2/repository/org/sonatype/sisu/sisu-gui
ce/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[31] = file:/C:/Users/Sagar/.m2/repository/asm/asm/3.3.1/asm-3.3.1.ja
r
[ERROR] urls[32] = file:/C:/Users/Sagar/.m2/repository/asm/asm-commons/3.3.1/asm-
commons-3.3.1.jar
[ERROR] urls[33] = file:/C:/Users/Sagar/.m2/repository/asm/asm-tree/3.3.1/asm-tre
e-3.3.1.jar
[ERROR] urls[34] = file:/C:/Users/Sagar/.m2/repository/org/jdom/jdom/1.1/jdom-1.1
.jar
[ERROR] urls[35] = file:/C:/Users/Sagar/.m2/repository/org/apache/maven/shared/ma
ven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[ERROR] urls[36] = file:/C:/Users/Sagar/.m2/repository/org/vafer/jdependency/0.7/
jdependency-0.7.jar
[ERROR] urls[37] = file:/C:/Users/Sagar/.m2/repository/commons-io/commons-io/1.3.
2/commons-io-1.3.2.jar
[ERROR] urls[38] = file:/C:/Users/Sagar/.m2/repository/asm/asm-analysis/3.2/asm-a
nalysis-3.2.jar
[ERROR] urls[39] = file:/C:/Users/Sagar/.m2/repository/asm/asm-util/3.2/asm-util-
3.2.jar
[ERROR] urls[40] = file:/C:/Users/Sagar/.m2/repository/com/google/guava/guava/11.
0.2/guava-11.0.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.springframework.asm.ClassVisitor
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switc
h.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read
 the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainer
Exception

E:\API\myapp>

**Comment by wilkinsona** [comment]
Errors like this:

```
error reading C:\Users\Sagar.m2\repository\org\springframework\spring-ao
p\5.0.4.RELEASE\spring-aop-5.0.4.RELEASE.jar; invalid LOC header (bad signature)
```

Mean that a jar file has been corrupted when it was downloaded. This is a general problem and has nothing to do with Spring Boot. You should be able to fix it by clearing your Maven cache and building your application again.
