### ISSUE TITLE
"Building the project(Build->Make Project)" changed to (Build->Build Project)

### ISSUE THREAD

**Issue by bobub** [spring-projects/spring-boot#12434]
in Spring Boot Reference, 20.2 Automatic Restart 
[Triggering a restart] ...  In IntelliJ IDEA, building the project (Build -> **Make Project**) has the same effect.
need to change
[Triggering a restart] ...  In IntelliJ IDEA, building the project (Build -> **Build Project**) has the same effect.

I use IntelliJ 2017.3.4 (Community Edition).
Thank you.

**Comment by snicoll** [comment]
@bobub good catch, thanks!
