### ISSUE TITLE
Adding 'mean', 'min' or 'percentiles' to Spring Boot 2 metrics?

### ISSUE THREAD

**Issue by gotson** [spring-projects/spring-boot#12433]
_Also posted on [StackOverflow](https://stackoverflow.com/questions/49166271/adding-mean-or-min-to-spring-boot-2-metrics_)

I am using the new **MicroMeter** metrics in **Spring Boot 2** version `2.0.0-RELEASE`.

When publishing metrics over the `/actuator/metrics/{metric.name}` endpoint, i get the following:

  For a `DistributionSummary` :

    "name": "sources.ingestion.rate",
        "measurements": [
            {
               "statistic": "COUNT",
                "value": 5
            },
            {
                "statistic": "TOTAL",
                "value": 72169.44162067816
            },
            {
                "statistic": "MAX",
                "value": 17870.68010661754
            }
        ],
        "availableTags": []
    }

  For a `Timer` :

    {
        "name": "sources.ingestion",
        "measurements": [
            {
                "statistic": "COUNT",
                "value": 5
            },
            {
                "statistic": "TOTAL_TIME",
                "value": 65.700878648
            },
            {
                "statistic": "MAX",
                "value": 22.661545322
            }
        ],
        "availableTags": []
    }

Is it possible to enrich the measurements to **add measures** like *mean*, *min*, or *percentiles* ?

For percentiles i tried using `.publishPercentiles(0.5, 0.95)`, but that doesn't reflect on the actuator endpoint.

**Comment by philwebb** [comment]
/cc @jkschneider.

Thanks for the suggestion, but you'll need to make it [on the micrometer issue tracker](https://github.com/micrometer-metrics/micrometer).

**Comment by gotson** [comment]
@philwebb could you enlighten me on which part exactly is for micrometer ?
My understanding is that Actuator is part of Spring Boot, along with its HTTP endpoints like `/actuator/metrics`, right ?

**Comment by snicoll** [comment]
`/actuator/metrics` is exposing the content of `MeterRegistry`. The API and the exporter to monitoring systems are part of a separate library, hence the request to create this request at [the appropriate place](https://github.com/micrometer-metrics/micrometer/).

**Comment by philwebb** [comment]
Yeah, sorry for the terseness of the original message. By baby started crying for a feed halfway though typing it :)

As @snicoll says, as of 2.0 we delegate all the metrics functionality to a new library called Micrometer and delegate our actuator endpoint to the data it provides. If they can add the feature, we can expose it.
