### ISSUE TITLE
The label of the DataSource metric exported by Spring Boot is different from the label exported by HikariCP

### ISSUE THREAD

**Issue by matsumana** [spring-projects/spring-boot#12431]
I'm using Spring Boot 2.0, micrometer and prometheus.

Please take a look the following metrics.

The label of the DataSource metric exported by Spring Boot is different from the label exported by HikariCP.
I'm not configure `spring.datasource.hikari.pool-name`
`HikariPool-1` is the default value.

Could you unify with the label exported by HikariCP?

```

Exported by Spring Boot

# HELP jdbc_connections_active  
# TYPE jdbc_connections_active gauge
jdbc_connections_active{name="dataSource",} 0.0

# HELP jdbc_connections_max  
# TYPE jdbc_connections_max gauge
jdbc_connections_max{name="dataSource",} 60.0

# HELP jdbc_connections_min  
# TYPE jdbc_connections_min gauge
jdbc_connections_min{name="dataSource",} 50.0


Exported by HikariCP

# HELP hikaricp_connections_active Active connections
# TYPE hikaricp_connections_active gauge
hikaricp_connections_active{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections Total connections
# TYPE hikaricp_connections gauge
hikaricp_connections{pool="HikariPool-1",} 33.0

# HELP hikaricp_connections_pending Pending threads
# TYPE hikaricp_connections_pending gauge
hikaricp_connections_pending{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections_idle Idle connections
# TYPE hikaricp_connections_idle gauge
hikaricp_connections_idle{pool="HikariPool-1",} 33.0

# HELP hikaricp_connections_timeout_total Connection timeout total count
# TYPE hikaricp_connections_timeout_total counter
hikaricp_connections_timeout_total{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections_creation_seconds Connection creation time
# TYPE hikaricp_connections_creation_seconds summary
hikaricp_connections_creation_seconds{pool="HikariPool-1",quantile="0.95",} 0.394264575
hikaricp_connections_creation_seconds_count{pool="HikariPool-1",} 32.0
hikaricp_connections_creation_seconds_sum{pool="HikariPool-1",} 8.058
hikaricp_connections_creation_seconds_max{pool="HikariPool-1",} 0.397

# HELP hikaricp_connections_acquire_seconds Connection acquire time
# TYPE hikaricp_connections_acquire_seconds summary
hikaricp_connections_acquire_seconds{pool="HikariPool-1",quantile="0.95",} 0.001048575
hikaricp_connections_acquire_seconds_count{pool="HikariPool-1",} 1.0
hikaricp_connections_acquire_seconds_sum{pool="HikariPool-1",} 0.001
hikaricp_connections_acquire_seconds_max{pool="HikariPool-1",} 0.001

# HELP hikaricp_connections_usage_seconds Connection usage time
# TYPE hikaricp_connections_usage_seconds summary
hikaricp_connections_usage_seconds{pool="HikariPool-1",quantile="0.95",} 1.216348159
hikaricp_connections_usage_seconds_count{pool="HikariPool-1",} 1.0
hikaricp_connections_usage_seconds_sum{pool="HikariPool-1",} 1.209
hikaricp_connections_usage_seconds_max{pool="HikariPool-1",} 1.209
```

**Comment by wilkinsona** [comment]
Can you explain why you consider this to be a problem? The first three are general purpose DataSource metrics using, IIRC, the bean name for the `name` tag. The others are HikariCP-specific metrics using the HikariCP-specific pool name for the HikariCP-specific `pool` tag.

**Comment by matsumana** [comment]
I'm collecting metrics using micrometer and micrometer-registry-prometheus in some Spring Boot applications and monitoring it on Prometheus and Grafana dashboard.
Grafana has a feature called [Templating](http://docs.grafana.org/reference/templating/), which is useful when viewing multiple applications on a single dashboard.

And I'd like to monitor as the following HikariCP's metrics on the Prometheus and Grafana dashboard.

- jdbc_connections_max
- jdbc_connections_min
- hikaricp_connections_active
- hikaricp_connections
- hikaricp_connections_pending
- hikaricp_connections_idle
- hikaricp_connections_timeout_total

However, I have to choose two pulldowns for now as follows.
so I'd like to improve it.

![](https://i.gyazo.com/34677947c25511e6d99a95f25e171fba.png)

Additionally, Also, although I want to raise an alert when the number of remaining pool in the connection pool decreases, I think that Prometheus alert rule is also difficult to write with the current label.

**Comment by wilkinsona** [comment]
Thanks for the extra information. I don't find that argument sufficiently compelling to change the way that the general data source metrics behave. Those metrics current use the same names and tags, irrespective of the connection pool that you're using. That would no longer be true if your proposal was implemented.

If you want to have metrics for max and min that are named and tagged similarly to Hikari's own metrics, you can inject a `MeterRegistry` and bind them yourself:

```java
public void bindHikariMaxAndMin(HikariDataSource dataSource,
        MeterRegistry meterRegistry) {
    Gauge.builder("hikaricp.connections.max", dataSource,
            HikariDataSource::getMaximumPoolSize).description("Maximum connections")
            .tags("pool", dataSource.getPoolName()).register(meterRegistry);
    Gauge.builder("hikaricp.connections.min", dataSource,
            HikariDataSource::getMinimumIdle).description("Minimum connections")
            .tags("pool", dataSource.getPoolName()).register(meterRegistry);
}
```

**Comment by matsumana** [comment]
Got it.
Thank you for the info.
