### ISSUE TITLE
Review use of application's ResourceConfig when Jersey-based Actuator is running on a separate port

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12443]
See https://github.com/spring-projects/spring-boot/issues/2025#issuecomment-372382451.

**Comment by Antoniossss** [comment]
Not only actutator but whole "default falback" to DispatcherServlet is not working at all.  When using Jersey starters, default servler implementation of current servlet container will be used, thus eg. serving static resources wont work "spring way". 

In my case it is org.apache.catalina.servlets.DefaultServlet rendering whole mvc fallback useless.

**Comment by wilkinsona** [comment]
@Antoniossss Sorry, but I don't understand the problem that you're trying to describe. It also appears to be unrelated to Jersey's `ResourceConfig` and the treatment of `@ApplicationPath`. If you believe you've found a bug related to Spring MVC's `DispatcherServlet`, please open a new issue with a small sample project that reproduces the behaviour you've described.

**Comment by wilkinsona** [comment]
We seem to be in good shape here. When the actuator's running on a separate port we always create an Actuator-specific `ResourceConfig` in the management context that's used for the endpoints. This isolates it from any path configuration in the app itself.
