### ISSUE TITLE
Add checkstyle so modifiers to comply with the Java Language Specification

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12446]
See #12432. Ideally we should have a way to stop these coming back.

**Comment by wilkinsona** [comment]
Didn’t #12432 already take care of that? See https://github.com/igor-suhorukov/spring-boot/blob/e71f444bda04ae303cf33087c6f9857f48658575/spring-boot-project/spring-boot-parent/src/checkstyle/checkstyle.xml#L132.

**Comment by philwebb** [comment]
I missed it. Nice.
