### ISSUE TITLE
PropertySourcesKey doesn't recognize a replaced property source with the same name

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#12451]
https://github.com/spring-cloud/spring-cloud-commons/issues/328
https://github.com/spring-cloud/spring-cloud-commons/issues/290

**Comment by philwebb** [comment]
Looking at `SpringConfigurationPropertySources.PropertySourceKey` I'm wondering if we can't just keep a weak reference to the original property source.

**Comment by spencergibb** [comment]
forcing the `SpringConfigurationPropertySources.onChange()` to always fire, fixed the issue. So fixing the key should work.

**Comment by JoostK** [comment]
Looking at the `shouldTrackChanges` testcase for `SpringConfigurationPropertySources` which seems a bit dodgy, given that it currently constructs a new `SpringConfigurationPropertySources` instead of verifying that the original has seen the changes.

**Comment by philwebb** [comment]
@JoostK It does indeed, thanks for highlighting it. We'll fix that at the same time.

**Comment by spencergibb** [comment]
Thanks Phil!

**Comment by philwebb** [comment]
@spencergibb Can you give cloud another go just to double check?

**Comment by spencergibb** [comment]
will do

**Comment by spencergibb** [comment]
@philwebb looks good.

**Comment by sanderino666** [comment]
@philwebb As mentioned in [328](https://github.com/spring-cloud/spring-cloud-commons/issues/328) I tested our project against 2.0.1.BUILD-SNAPSHOT and the issue is resolved. Thanks for fixing it!

**Comment by ismail-s** [comment]
@philwebb Hi Phil. Is there any chance of this fix getting backported into version 1.5?

**Comment by philwebb** [comment]
@ismail-s The bug was in the new `ConfigurationProprtySource` code introduced in 2.0. The problem shouldn't exist in 1.5.

**Comment by ismail-s** [comment]
@philwebb Thanks for the quick response. I've created spring-cloud/spring-cloud-config#1062 instead.
