### ISSUE TITLE
AuthenticationManagerConfiguration is missing in 2.0.RELEASE

### ISSUE THREAD

**Issue by ets2015** [spring-projects/spring-boot#12464]
when i am try to upgrade 2.0.0.RELEASE , the follow config :
`   @Override
    @Autowired
    public void setAuthenticationManager(AuthenticationManager authenticationManager) {
        super.setAuthenticationManager(authenticationManager);
    }`

has an error ,the AuthenticationManager can not be autowired ，but in before version like 1.5.10 it is ok  ,

finally i found AuthenticationManagerConfiguration class has been removed at 2.0.0.RELEASE ,
this class  in package org.springframework.boot.autoconfigure.security at old version ,

**Comment by wilkinsona** [comment]
This is covered in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#authenticationmanager-bean).
