### ISSUE TITLE
Wrong properties name on documentations

### ISSUE THREAD

**Issue by rvashishth** [spring-projects/spring-boot#12465]
Today i have trying to enable shutdown hook. And issue i faced for an hour was becoz of the wrong property name. To enable the shoutdown endpoint property name give is 

management.endpoint.shutdown.enabled=true

https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints-enabling-endpoints

While the one which worked for me is - 
endpoints.shutdown.enabled=true

That too after looking into the src codes. Now my query is 
 this property name is changed now and earlier it was same as mentioned in the reference docs?
 if properties are changes this way, how you are planning for lagecy framework support ?
 how i can contribute in editing the documentation ?

**Comment by spencergibb** [comment]
What version of spring boot are you using? Those links are for the 2.0.0 line.

**Comment by wilkinsona** [comment]
> this property name is changed now and earlier it was same as mentioned in the reference docs?

Yes. It changed in Spring Boot 2.0. `endpoints.shutdown.enabled` is the correct [and documented](https://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#production-ready-customizing-endpoints) property in Spring Boot 1.5. `management.endpoint.shutdown.enabled` is the correct [and documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints-enabling-endpoints) property in Spring Boot 2.

> if properties are changes this way, how you are planning for lagecy framework support ?

The migration guide [describes the mapping from old properties to new](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-keys-structure). You can use the [properties migrator](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#before-you-start) to help you to move from Boot 1.5 to 2.0.

> how i can contribute in editing the documentation ?

Thanks for the offer, but I don't believe any changes to the documentation are necessary as things are accurate for both 1.5 and 2.0.
