### ISSUE TITLE
Upgrading to 2.0.0.RELEASE from 1.5.10.RELEASE breaks logging behavior

### ISSUE THREAD

**Issue by jcarbad** [spring-projects/spring-boot#12479]
Originally, my app is working with 1.5.10.RELEASE alongside Groovy, and I make my logging using Groovy's  `@Log4j` annotation and everything works fine; the logging is made using the configurations set in the `application.properties`, file is correctly updated and no undesired messages are shown.  This is the configuration I'm originally using:
![image](https://user-images.githubusercontent.com/20905598/37412610-e08617d8-276a-11e8-9416-15f44adae366.png)

```
# Logging 
logging.file=application.log
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%X{correlationId}] %m%n%wEx
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : [%X{correlationId}] %m%n%wEx
```

When I try to  upgrade to the 2.0.0.RELEASE, the logging is broken, in the sense that neither the messages I want to log are shown, nor the log file is updated correctly. Besides, my console gets saturated with log messages from external libraries I'm using, as if it was in some sort of Debug mode.

Any idea what's going on? Might groovy annotations have conflicts with spring boot auto-configuration?

**Comment by jcarbad** [comment]
Example of broken logging with rubbish messages from external library:
![image](https://user-images.githubusercontent.com/20905598/37413181-0e6cd82a-276c-11e8-82bd-8eb4107cbebd.png)

**Comment by wilkinsona** [comment]
Is `@Log4j` backed by Log4j 1? If so, it's been [EOL since August 2015](https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces) and we removed Boot's Log4j 1 integration in 1.4 in response to this.

If you can provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) we can take a look but, unless the fix is straightforward or the problem isn't specific to Log4j 1, it will be difficult to justify spending too much time on it.

**Comment by snicoll** [comment]
> Is @Log4j backed by Log4j 1? 

Yes. There is also a `@Log4j2` support in Groovy. I've quickly tried to use it to see what happens but didn't manage to go very far. So a minimal sample is really required.

**Comment by PascalSchumacher** [comment]
`@log4j` is indeed backed by log4j1.x and requires log4j1.x on the classpath see https://github.com/apache/groovy/blob/master/src/main/groovy/groovy/util/logging/Log4j.java

**Comment by jcarbad** [comment]
While making the sample project, the behavior was exactly as you mentioned, by getting a compilation error when using the `@log4j`. The erratic behavior was due to and old library using log4j. By changing the annotation to `@Slf4j` everything worked again. 

Thanks a lot your help!
