### ISSUE TITLE
Conflict with existing bean called "conversionService" in Boot 2

### ISSUE THREAD

**Issue by cpoulsen-dezide** [spring-projects/spring-boot#12473]
I'm currently in the process of retrofitting an existing Spring 4 application with Boot 2. We have a bean named "conversionService" - This leads to startup errors as Boot complains that the bean is not of the expected type.

I renamed our bean and moved on, but it seems a bit weird that the name is "reserved" so I thought I'd raise the issue here.

Bean definition:
```
@Bean
public ConversionService conversionService()
{
    return new ConversionServiceImpl( );
}
```
Log snippet attached:
[conversion-service-error.log](https://github.com/spring-projects/spring-boot/files/1809913/conversion-service-error.log)

**Comment by snicoll** [comment]
@cpoulsen-dezide this is indeed on purpose and [documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion). There are other bean lookups by name and this is a fundamental service used by Spring Boot so it looks ok to me to do that.

**Comment by cpoulsen-dezide** [comment]
Fair enough, I have missed that in the docs. 

Though I would have expected that one should provide a bean implementing a certain (marker?) interface instead of relying on the bean name for configuring stuff like that.

**Comment by snicoll** [comment]
We load this bean very early in the application context startup, that's why have to do a lookup by key ( bean name). Not doing so would trigger early initializations.
