### ISSUE TITLE
Handling of Flux<String>

### ISSUE THREAD

**Issue by MarvGilb** [spring-projects/spring-boot#12476]
Hey,

I implemented a service based on _spring-boot:2.0.0.RC1_.
Some endpoints are only returning simple string ids, such as this method:
```Java
@GetMapping()
public Mono<ResponseEntity<Flux<String>>> findAll() {
    Flux<String> result = someService.findAllIds()
            .switchIfEmpty(Flux.error(new ResponseStatusException(HttpStatus.NO_CONTENT)));
    return Mono.just(ResponseEntity.ok(result));
}
```

With the RC1 version the strings were returned separately as individual strings. It did not depend on the accepted content-type. Both `application/json` and `application/stream+json` returned correct results.
-> `['id1','id2',...]`
or 
-> `'id1' 'id2' ...` (For the stream)

But using _spring-boot:2.0.0.RELEASE_, broke the behaviour and now the individual strings are returned as one single string. Regardless which accept header is set.
-> `'id1id2...'`

**Comment by bclozel** [comment]
Hi @MarvGilb,

This has been reported already as a Spring Framework issue; please refer to [SPR-16260](https://jira.spring.io/browse/SPR-16260).

Thanks for the report!
