### ISSUE TITLE
Explicitly set asyncSupported flag in [Tomcat|Jetty]ReactiveWebServerFactory

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-boot#12486]
Looking at the initialization code in Boot, the `TomcatHttpServletAdapter` and `JettyHttpServletAdapter` are explicitly mapped (under "/") but the asyncSupported flag is not explicitly set, instead relying on the `@WebServlet(asyncSupported=true)` annotation on those classes. 

We have https://jira.spring.io/browse/SPR-16591 in the Spring Framework and plan to remove the annotation, in favor of explicit programmatic configuration. It should be trivial to change the Boot code to set the flag explicitly. 

The alternative would be to to add a mapping of "/" to the annotation, but it would be typically overridden anyway in the places where those Servlet adapters are registered (i.e. Boot and also Spring Framework's `AbstractReactiveWebInitializer`). So for consistency I tend to prefer removing the annotation altogether.

Does that sound okay? If so we need to coordinate the release.

**Comment by philwebb** [comment]
@rstoyanchev Did you mean `TomcatHttpHandlerAdapter` and `JettyHttpHandlerAdapter`? If so it looks like we just need to change `TomcatReactiveWebServerFactory.prepareContext` `JettyReactiveWebServerFactory.createJettyServer` which should be a 5 min job.

**Comment by rstoyanchev** [comment]
Perfect, thanks.
