### ISSUE TITLE
spring-boot-dependencies 2.0.0.R references Hibernate 5.2.14, which has critical issues

### ISSUE THREAD

**Issue by trks1970** [spring-projects/spring-boot#12493]
spring-boot-dependencies 2.0.0.RELEASE references Hibernate 5.2.14, which has critical issues:
[HHH-12332](https://hibernate.atlassian.net/browse/HHH-12332)

Issue is solved in 5.2.15.

**Comment by wilkinsona** [comment]
Please take a moment to check if a change has already been made before raising an issue.

Duplicate of https://github.com/spring-projects/spring-boot/issues/12439.
