### ISSUE TITLE
Upgrade JDK 10-based CI to jdk-10-ea-46

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12515]

**Comment by wilkinsona** [comment]
Building the new image failed due to https://github.com/docker-library/official-images/issues/3835. It should work once https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/openjdk/67/ has finished. I think the best we can do is check periodically to see if the amd64 job's finished and trigger a new CI image build once it has.

**Comment by philwebb** [comment]
And I thought our build was slow 😱

**Comment by wilkinsona** [comment]
At the time of writing, the build we're waiting for is 78th in the queue for the amd64! It's [rather busy of late](https://doi-janky.infosiftr.net/computer/multiarch-amd64/load-statistics?type=hour).

**Comment by bclozel** [comment]
[build 67 failed](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/openjdk/67/console) 😢:

> Still waiting to schedule task
> Waiting for next available executor on multiarch-amd64
> [Pipeline] // node
> [Pipeline] End of Pipeline
> ERROR: Queue task was cancelled
> Finished: FAILURE

**Comment by philwebb** [comment]
I've raised https://github.com/docker-library/openjdk/issues/171 to see if a new build can be kicked off.

**Comment by wilkinsona** [comment]
The new build succeeded and our CI images [have been updated](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot/jobs/build-spring-boot-ci-images/builds/12).
