### ISSUE TITLE
Bind server.error.whitelabel.enabled to ErrorProperties

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#12516]
#12520 needs to access `server.error.whitelabel.enabled` as part of `ErrorProperties`, as a `@ConditionalOnProperty` can't be used in that case.

**Comment by snicoll** [comment]
the default value for the `include-stack-trace` parameter was removed as part of this commit (and shouldn't have).

**Comment by snicoll** [comment]
Restored in 78571f5  

@bclozel enum default values can't be extracted by the annotation processor so we have to do that ourselves if we want such default to show up in the metadata.
