### ISSUE TITLE
Move away from Couchbase's deprecated endpoint configuration methods

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12518]
We're using the following methods that are now deprecated:

- `com.couchbase.client.core.env.DefaultCoreEnvironment.Builder.kvEndpoints(int)`
- `com.couchbase.client.core.env.DefaultCoreEnvironment.Builder.queryEndpoints(int)`
- `com.couchbase.client.core.env.DefaultCoreEnvironment.Builder.viewEndpoints(int)`

Each has a recommend replacement. We should move to them, making any necessary adjustments to our configuration properties when we do so. We can probably do this in 2.0.1 if we keep the current properties, deprecating where necessary, and add any additional properties that the replacements in Couchbase need.

**Comment by qinnnyul** [comment]
@wilkinsona hey, I have one question about these replacements, some of them support more method parameters, e.g: QueryServiceConfig, it accepts minEndpoints and maxEndpoints. do we need to make adjustments to "CouchbaseProperties" to reflect this change?

**Comment by wilkinsona** [comment]
Yes. That’s why I said “making any necessary adjustments to our configuration properties when we do so” above.

**Comment by philwebb** [comment]
Closing in favor of PR #12655 (thanks @qinnnyul!)
