### ISSUE TITLE
Spring Boot Maven plugin 1.5.10 repackage ignoring jar.finalName property

### ISSUE THREAD

**Issue by georgeharley** [spring-projects/spring-boot#12521]
I'm using Spring Boot 1.5.10 and noticed that if the Maven package task is run with the `jar.finalName` property supplied to customise the name of the generated file then the resulting packaged Jar is named according to the `jar.finalName` value but the naming of the repackage/fat Jar appears to have ignored it. 
For example:
```
./mvnw -Djar.finalName=foo clean package
```
produces `target/foo.jar` and `target/myapp-0.0.1-SNAPSHOT.jar` but I would have expected it to produce `target/foo.jar.original` and `target/foo.jar`

I've created the following simple Spring Boot project that can be used to demonstrate the issue
https://github.com/georgeharley/boot-mvn-plugin-issue

**Comment by wilkinsona** [comment]
George and I discussed this earlier and it feels like a bug to me. What do you think, @snicoll?

**Comment by snicoll** [comment]
I am using [that feature in Spring Initializr](https://github.com/spring-io/initializr/blob/f480a6b4d2569820346a69c11499d61c58a2eced/initializr-service/pom.xml#L67). It feels very odd that the Spring Boot maven plugin would read properties from another plugin. 

That would make the case with the war plugin complex if it also exposed a property for this. In essence, I am saying I am not keen to support that (but happy to look for other options).

But first, @georgeharley, what is the reason why you can't use the proper `finalName` feature of the pom?

**Comment by wilkinsona** [comment]
Thanks, @snicoll. I’d overlooked the distinction between `jar.finalName` and `finalName`. I have a feeling that the latter may already do what @georgeharley wants.

**Comment by snicoll** [comment]
There is also a `finalName` property for [the repackager](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html) in case this needs to be configured. 

A single property can be created in a project and the plugins can be configured to use this so I don't think there is something required here. We can reopen if a compelling argument is provided.

**Comment by georgeharley** [comment]
@snicoll Thanks for looking at this. FWIW, I want to be able to set the name of final/repackaged Jar from the command line but without making any changes to the original POM file. So, while editing the POM file to add a `finalName` tag inside `build` works fine (like in the Initializr example you referenced), I'm unable to edit the POM and am finding it impossible(?) to use the command line to specify a value for the final Spring Boot Jar.

**Comment by wilkinsona** [comment]
@snicoll I'll explain what George is doing during this week's face-to-face. If `finalName` can't be set from the command line, then we might need to get our thinking caps on.

**Comment by philwebb** [comment]
I wonder if setting [@Package(build=false)](https://github.com/metaparticle-io/package/blob/25ad1084f70135d8387512a4923ecda45607c6f2/java/src/main/java/io/metaparticle/annotations/Package.java#L18) might work to disable the [mvn build](https://github.com/metaparticle-io/package/blob/25ad1084f70135d8387512a4923ecda45607c6f2/java/src/main/java/io/metaparticle/Metaparticle.java#L123) part.

**Comment by snicoll** [comment]
@georgeharley where is that `jar.finalName` property coming from? The `finalName` property of the jar plugin is read-only for 2 years now, see [MJAR-217](https://issues.apache.org/jira/browse/MJAR-217). Are you using an older version of the jar plugin by any chance?

**Comment by georgeharley** [comment]
@snicoll You are correct! Just checked the effective POM and my maven-jar-plugin was at version 2.6. After updating it to the latest level (3.0.2) the `-Djar.finalName` property no longer controls the name of the original/thin Jar :-( 
So it _sounds_ like it is not possible to control the name of either packaged Jar solely from the command line. Not the outcome I was hoping for but still very helpful to know. Thank you.

**Comment by georgeharley** [comment]
@philwebb Yep, I'm focusing more on trying to prevent the unnecessary packaging step altogether although currently setting `build=false` does a bit too much as it also skips building the image and publishing to the target cluster (if `publish=true`). I'm hoping that either a command line property or detecting that the running program is a Spring Boot application could be used to conditionally disable the packaging.

**Comment by snicoll** [comment]
I've created #12608 to take care of aligning our `finalName` property.
