### ISSUE TITLE
/actuator/refresh  Can't access

### ISSUE THREAD

**Issue by zhongzunfa** [spring-projects/spring-boot#12536]
I use spring boot2.0 + spring cloud Finchley M7 to create config-server and config-client， when I visit `/actuator/health` return info, but when I visit `/actuator/refresh` having error.

```json
{
    "timestamp": "2018-03-18T14:56:23.467+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/actuator/refresh"
}
```

![image](https://user-images.githubusercontent.com/14095698/37567340-9bebd588-2b00-11e8-94f3-f7b21ea792f2.png)

![image](https://user-images.githubusercontent.com/14095698/37567349-af72ba04-2b00-11e8-8715-5afb61a5db39.png)

**Comment by philwebb** [comment]
The refresh scope is part of Spring Cloud. There issue tracker is [here](https://github.com/spring-cloud/spring-cloud-commons/). It looks to me like you might be missing some security configuration.
