### ISSUE TITLE
'org.springframework.security.oauth:spring-security-oauth2' disappeared from 2.0.0 ? Need new example and update documentation.

### ISSUE THREAD

**Issue by ukimpact** [spring-projects/spring-boot#12537]
I am trying to follow one of first basic ten examples OAuth2 available for search for spring boot release 2.0.0, it is very confusing. Not to mention that 2 times-referenced '[sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login)' of auth2 is not standalone project so its gradle build file is not useful to me.

All tutorials include following library which is absent for version 2.0.0 mavenCentral?
`org.springframework.security.oauth:spring-security-oauth2`

https://spring.io/guides/tutorials/spring-boot-oauth2/ lists:

```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-security</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.security.oauth</groupId>
	<artifactId>spring-security-oauth2</artifactId>
</dependency>
```

I can't resolve oauth with 2.0.0 but can resolve with 1.5.10?

my gradle snippet:

```
repositories {
	mavenCentral()
}


buildscript {
    ext {
        kotlinVersion = '1.2.30'
        springBootVersion = '2.0.0.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
    }
}


dependencies {
    compile ('org.springframework.boot:spring-boot-starter-security')
    compile('org.springframework.boot:spring-boot-starter-cache')
    compile('org.springframework.boot:spring-boot-starter-thymeleaf')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-thymeleaf')
    compile('com.fasterxml.jackson.module:jackson-module-kotlin')
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compile("org.jetbrains.kotlin:kotlin-reflect")
    compile ('org.springframework.security.oauth:spring-security-oauth2') // only this one fails...
    runtime('org.springframework.boot:spring-boot-devtools')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

**Comment by ukimpact** [comment]
Was confused by client and 
compile ('org.springframework.security:spring-security-oauth2-client')

and OAuth2

compile ('org.springframework.security.oauth:spring-security-oauth2')

I think for basic integration with google I need new client lib, **I still can't resolve second one** though.

**Comment by wilkinsona** [comment]
I believe this is covered by the [relevant section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#oauth2) of the Boot 1.5 to 2.0 migration guide and the documentation to which it links.
