### ISSUE TITLE
TomcatStarter: consider logging the full stack trace

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#12547]
The `TomcatStarter` only logs the exception message; it's easier to debug problems if a full stack trace is provided.

```java
			this.startUpException = ex;
			// Prevent Tomcat from logging and re-throwing when we know we can
			// deal with it in the main thread, but log for information here.
			if (logger.isErrorEnabled()) {
				logger.error("Error starting Tomcat context. Exception: "
						+ ex.getClass().getName() + ". Message: " + ex.getMessage());
			}
```

Ref: https://github.com/spring-projects/spring-kafka/issues/606#issuecomment-374341361

**Comment by wilkinsona** [comment]
This is deliberate as the full stack trace should have been logged earlier by Tomcat. Someone reported a similar problem recently (https://github.com/spring-projects/spring-boot/issues/12154) but didn't provide details of how to produce a problem where Tomcat hadn't already logged the exception.

If you can provide one, @garyrussell, then we can hopefully figure out why that's happening.

**Comment by garyrussell** [comment]
Thanks @wilkinsona - I can't reproduce it; when I force the error to occur in the `TomcatStarter`, I get the full stack trace a few lines later: https://github.com/spring-projects/spring-kafka/issues/606#issuecomment-374371594

>where Tomcat hadn't already logged the exception.

I don't see Tomcat logging it, but boot does.

**Comment by wilkinsona** [comment]
> I don't see Tomcat logging it, but boot does.

Sorry, that's probably my faulty memory. I knew that something should log it, but suspect I misremembered what.

It's coming back to me a bit now thanks, in part, to the comment in the code. The exception happens on Tomcat's start up thread, but is also thrown on the main thread. It's there that it's handled and logged as shown in https://github.com/spring-projects/spring-kafka/issues/606#issuecomment-374371594.

I'm going to close this one for now. If https://github.com/spring-projects/spring-kafka/issues/606 reveals a scenario where the exception isn't logged then we can re-open.
