### ISSUE TITLE
Allow @ConfigurationProperties binding on interfaces

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1254]
It would be useful to allow configuration binding to work directly on fields if the user doesn't want to expose public setters.

**Comment by fromi** [comment]
I would be happy to be able to use @ConfigurationProperties with constructor injection, so I can create immutable and encapsulated classes.

**Comment by mwisnicki** [comment]
I, for one, would like to have it working with plain fields.

**Comment by mwisnicki** [comment]
Maybe use `transient` or `@Transient` to exclude properties from serialization/metadata ?

**Comment by mwisnicki** [comment]
BTW spring-boot documentation has an [example](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding) that shows binding to field which I guess is a mistake.

**Comment by philwebb** [comment]
@mwisnicki Good spot on the docs. I've raised #2813 to address this.

**Comment by michaeltecourt** [comment]
In order to have an "immutable" configuration properties object, I currently use a workaround with an interface, whose implementation is a "Java Bean" annotated with @ConfigurationProperties. Any shortcut would be appreciated. By the way, enabling field based injection would make a lot of sense, as the behavior would be more consistent with `@Value`. Having to add both getters/setters can be counter-intuitive the first time around.

**Comment by jordanjennings** [comment]
@michaeltecourt Thanks for the suggestion. Doing this in combination with Lombok's @Data annotation on the implementation class makes this fairly painless.

**Comment by snicoll** [comment]
@michaeltecourt that's not the same thing at all. With {{@Value}} you're giving the full id in a regular Spring Framework annotation (i.e. that you can put on field, setter or constructor argument). {{@ConfigurationProperties}} is a strongly-typed binder on a regular class. 

If we were enabling field access by default, all the fields of your class would be exposed which isn't what you want. The presence of accessors defines if it should be exposed or not. 

I think our best shot at it is to add a flag to enable this explicitly.

**Comment by michaeltecourt** [comment]
@snicoll By "all the fields of your class would be *exposed*" do you mean "injectable/bindable" ?

We mostly use `@ConfigurationProperties` like a bulk `@Value`.
The semantic and precise use cases might be different, but isn't the purpose the same? binding properties from the Spring context to Spring beans in a type-safe manner?

In the end, what I find slightly confusing as a user is that you can do this :

    /** Works on fields, constructor, etc */
    @Component
    class Props {
      @Value("${cfg.props.a}") String a;
      @Value("${cfg.props.b}") BigDecimal b;
     
      public Props(a, b) { this.a = a; this.b = b; }
      public String getA() { return this.a; }
      public BigDecimal getB() { return this.b; }
     }

and not this :

    @ConfigurationProperties("cfg.props")
    class Props {
      String a;
      BigDecimal b;
     
      public Props(a, b) { this.a = a; this.b = b; }
      public String getA() { return this.a; }
      public BigDecimal getB() { return this.b; }
      // SETTERS NEEDED
    }

**Comment by snicoll** [comment]
Yes, that is what I mean. 

I think we already covered why it is confusing (see my previous comment). I am not arguing we shouldn't do it, I am arguing it must be opt-in.

**Comment by michaeltecourt** [comment]
oh just realized `ConfigurationProperties` are also *exposed* through the `/configprops` actuator endpoint while "regular" properties are not. 

From a humble user standpoint, I know that Spring has implicit write access to my class attributes as soon as it's annotated with `@ConfigurationProperties`, I wouldn't mind if field binding became the default, with some kind of exclusion mechanism as described by @mwisnicki, like the vast majority of annotation based binding frameworks (JAXB, Jackson, JPA...).
I know the use case is different, as config properties are often directly injected to beans whose purpose is far more complex than holding values, so any additional option over getters+setters would be cool :)

    @ConfigurationProperties("cfg.props")
     class Props {

          /** requires accessors by default */
          String a; 

          /** Enable field access explicitely */
          @ConfigurationProperty BigDecimal b;

          /** Explicit exclusion ? */
          @Transient Integer c;
     }

@philwebb 's proxy based solution looks a lot like the "old" (not pejorative) property binder framework : http://pholser.github.io/property-binder/examples.html

**Comment by adjohnson916** [comment]
+1 I'd like a `@ConfigurationProperty` annotation valid on fields, which would accept an optional `value` specifying the property path.

**Comment by laxika** [comment]
+1 from me. Setters are entirely useless for my user case and still, I should provide them. Having an immutable configuration would be a lot better. I'm not exactly sure how it can by supported sadly but it would be a lot better.

**Comment by sta-szek** [comment]
:+1:  getters and setters on all my property classes... :cry:

**Comment by MHarris021** [comment]
+1

**Comment by victorherraiz** [comment]
I'd love to have that feature. Annotated constructor parameters should be another option, something like @JsonCreator annotation, to build actual inmutable objects.

**Comment by tgianos** [comment]
+1 Also like the idea of mimicking how Jackson uses ```@JsonCreator```

**Comment by krzyk** [comment]
This could be achieved by using java 8 `-parameters` so Spring would know which property should be set at which constructor argument.

**Comment by thinkbigthings** [comment]
+1 for immutable configuration.

**Comment by lpandzic** [comment]
You don't need '@JsonCreator' if you use [jackson-module-parameter-names](https://github.com/FasterXML/jackson-module-parameter-names), except in case of single param constructor which will most likely change in jackson 3.

Back to this issue, instead of using reflection to mutate fields, Spring should similarly use parameter names and types to construct @ConfigurationProperties marked class instances.

**Comment by wilkinsona** [comment]
The plan is:

 - Support binding to an interface that is annotated with `@ConfigurationProperties`
 - Automatically create a proxy that implements the interface and intercepts calls to the interface's getters. The interceptor will query the Environment for a property's value
 - Default values can be specified via an annotation (`@DefaultValue`) on the getter. The annotation will take a `String`. We can use the annotation processor to fail at compile time if the default cannot be coerced to the getters return type. We also considered using default methods, but the result is significantly more verbose.
 - Provide a mechanism for property retrieval to be dynamic or static. If it's static, the interceptor will query the environment the first time the method is called and cache the result. If it's dynamic, the interceptor will query the environment each time the method is called

**Comment by mwisnicki** [comment]
No chance of field binding? For POCs and microservices I usually prefer quick and dirty approach.

**Comment by wilkinsona** [comment]
> No chance of field binding? For POCs and microservices I usually prefer quick and dirty approach.

No, we don't think so. The main goal for this is to make it easier for a configuration properties class to be immutable. If we bound directly to fields, you'd still have to write the getter methods along with the fields which I think would be more code than writing an interface. The alternative would be to encourage people to make the fields public and access them directly and we don't want to do that.

**Comment by mwisnicki** [comment]
That's unfortunate. Making fields public and avoiding accessor methods is
exactly what I want when writing throwaway or minimalistic code.

**Comment by fromi** [comment]
@mwisnicki, you only have to write a constructor. Then, you can make all the fields public and final, which is perfectly clean for a data structure. You get immutable minimalist code.

**Comment by mwisnicki** [comment]
This actually means I have to repeat every property name 3 times.
Interface proxies are far better wrt. to DRY principle.

**Comment by victorherraiz** [comment]
How interfaces are going to deal with Java config?. When I want to have the same config estructure at several prefixes I normally use Java config with `@ConfigurationProperties` annotation at `@Bean`method.

**Comment by wilkinsona** [comment]
They won't. This change is going to be an addition to the existing support so you can continue to use your current approach with a POJO.

**Comment by victorherraiz** [comment]
could I extend the interface several times and annotate those to have several path with the same structure?

I prefer to have actual inmutable classes, but I must admit your solution is simpler and requiere less code.

**Comment by sdeleuze** [comment]
As discussed on [this comment](https://github.com/spring-projects/spring-boot/issues/8762#issuecomment-327844763) and previous ones, support for Kotlin interfaces with `val` properties is needed on Kotlin, and is even more critical if constructor-based POJO binding is not supported in Boot 2.0. I guess it could look like:

```kotlin
@ConfigurationProperties
interface Fooproperties {
    val firstName: String
    val bar: Bar
}
```

If I decompile this Kotlin interface to bytecode then convert it to Java I obtain:

```java
@ConfigurationProperties
@Metadata(
   mv = {1, 1, 7},
   bv = {1, 0, 2},
   k = 1,
   d1 = {"..."},
   d2 = {"..."}
)
public interface Fooproperties {
   @NotNull
   String getFirstName();

   @NotNull
   Bar getBar();
}
```
Which seems to be a good fit with what you expect to support on Java side.

**Comment by GertVil** [comment]
This is no longer planned for the near future?

**Comment by snicoll** [comment]
@GertVil this issue is assigned to the `Backlog`, please review what `Backlog` means on our [milestones page](https://github.com/spring-projects/spring-boot/milestones). 

`TL;DR` `2.1`.

**Comment by lievendoclo** [comment]
@snicoll, since the backlog is an ordered list, any chance on this issue rising a bit on the ladder? Otherwise I'm afraid we won't be seeing this in 2.1 either. The fact that there's still an important part of Spring Boot that requires setters is something that I'd love to see fixed sooner than later.

**Comment by philwebb** [comment]
I think we should hold off on this one until we see how immutable constructor based properties work out.

**Comment by philwebb** [comment]
We've decided not to investigate this for now for the reason mentioned above.

**Comment by thekalinga** [comment]
> immutable constructor based properties

Is there a problem with this?

**Comment by snicoll** [comment]
@thekalinga no, that's why we've decided to close this one. We recommend using immutable configuration properties and we feel interface binding is very similar and not worth investigating any further at this point.

**Comment by kiriakos** [comment]
@snicoll 
please help me understand this, if I read the [docs](https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config-constructor-binding) correctly theimmutable config props proposal is doing something like this:
```
@ConstructorBinding
@ConfigurationProperties("acme")
public class AcmeProperties {
    private final boolean enabled;
    public AcmeProperties(boolean enabled) {
        this.enabled = enabled;
    }
    public isEnabled(){
        return enabled;
    }
}
```
(simplified from example)
how does this compare to simply declaring
```
@ConfigurationProperties("acme")
public interface AcmeProperties {
    public isEnabled()
}
```
The one is imperative and wordy the other is a succinct declaration. Are there any non apparent drawbacks that I'm missing here?

Thanks

**Comment by philwebb** [comment]
> Are there any non apparent drawbacks that I'm missing here?

The drawbacks are not really technical but more to do with where we should invest our time. Our experience with immutable configuration properties has shown that there are quite a few things that we need to consider when changing the configuration properties model (and these are often quite time consuming). For example, one problem that's often overlooked is the generation of the meta-data file that's used to provide IDE support.

Closing this issue doesn't mean that interface based properties are something that we'll never consider. We may well decide to re-open this one again in the future. For now though, we think that it's best if we see how useful people find constructor binder and how many problems the new code causes.

**Comment by dragneelfps** [comment]
Can we reopen it as we already have support for constructor based immutable properties? (at least in Kotlin afaik)

**Comment by laxika** [comment]
@dragneelfps

You can already do this add the following annotation to your application class:

```java
@ConfigurationPropertiesScan(basePackages = "com.github.loa")
```

Then you can create a configuration properties class with final values like this:

```java
package com.github.loa.vault.configuration;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.ConstructorBinding;

/**
 * Holds the configuration properties to the vault.
 */
@Getter
@ConstructorBinding
@RequiredArgsConstructor
@ConfigurationProperties("loa.vault")
public class VaultConfigurationProperties {

    /**
     * The unique name of the vault. This name will be saved when archiving new documents and will be used to identify
     * the vault that holds a given document. Do not change this after creating the vault because the documents
     * previously archived by this vault are not going to be accessible.
     */
    private final String name;

    /**
     * If this vault should be able to modify documents (e.g. remove) after they are archived. If your vault is available
     * publicly on the internet then set this to false!
     */
    private final boolean modificationEnabled;

    /**
     * If this vault should archive new documents.
     */
    private final boolean archiving;

    /**
     * This version number will be saved to the database for every document that has been archived. It will be used
     * later on if it's necessary to run cleanup or fixing tasks that are specific to a given version.
     */
    private final int versionNumber;
}
```

**Comment by snicoll** [comment]
@dragneelfps if you're willing us to reconsider, you'd have to provide a bit more context and justification. Immutable configuration properties are available for both Java and Kotlin and [this comment](https://github.com/spring-projects/spring-boot/issues/1254#issuecomment-560573102) still stands.

**Comment by krzyk** [comment]
@dragneelfps You can also use records for that (or just pure immutable class like shown above). I'm not sure why you would prefer interface.

**Comment by dragneelfps** [comment]
So, I have this scenario where there is supposed to be some base config and its different child which may override and add new properties to that config, as follows
```yaml
http-base: &httpBase
  connect-timeout: 5s
  
connectors:
  clientA:
    <<: *httpBase
    clientId: foobar
```

One way to solve is using composition instead of inheritance, but lets talk about inheritance for a bit
One possible way would be:
```kotlin
open class Base { lateinit var connectTimeout: Duration }
class ClientA(val clientId: String): Base()
```
The issue with above would be that the property check will throw error at runtime instead of start time when connectTimeout is missing. Also, it makes connectTimeout mutable, which I do not want.

Second way would be:
```kotlin
open class Base(val connectTimeout: Duration)
class ClientA(val clientId: String, connectTimeout: Duration): Base(connectTimeout)
```
Now, I do not want to write connectTimeout redundantly in ClientX classes.
Same issue if I make Base an interface then it becomes
```kotlin
interface Base { val connectTImeout: Duration }
class ClientA(val clientId: String, override val connectTimeout: Duration): Base
```

Now, IMO, following would be best suited for this kind of usecase
```kotlin
interface Base { val connectTimeout: Duration }
interface Client { val clientId: String } : Base
```
It is clean and provides immutability and makes sense.

PS:
A solution with a composition approach would be something like
```kotlin
class Base(val connectTimeout: Duration)
class ClientA(val clientId: String, val baseConfig: Base)
```
This has its own quirks, but it seems best solution compared to other **currently possible** ones.

PS-2:
I would be more than happy if someone can suggest a cleaner solution other than the ones I mentioned.
