### ISSUE TITLE
Automate creation of releases notes on GitHub

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12552]
Once a release has been tagged, we can use the GitHub API to edit its associated release and add some automatically generated release notes. Those release notes can be generated by querying all of the issues fixed in the release and generating appropriate Markdown.

**Comment by superxp1412** [comment]
I'd like to pick this task.

**Comment by wilkinsona** [comment]
Thank you for the offer, @superxp1412, but we still have some decisions to make about the format and the like. If you're interested in contributing, we have a number of issues that are [labelled as ideal for contribution](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution). Thanks again.

**Comment by rajadilipkolli** [comment]
@wilkinsona : I see with 2.0.3.RELEASE Release notes are generated. So can we assume that this task is done?

**Comment by wilkinsona** [comment]
It's largely done. A final step could be to fully automate the generation by plugging it into our CI pipeline. I'm not sure what @mbhave has in mind.
