### ISSUE TITLE
When `server.port` is set in an external `application.properties` file, RANDOM_PORT & `@LocalServerPort` are not honored in `@SpringBootTest` classes

### ISSUE THREAD

**Issue by bvulaj** [spring-projects/spring-boot#12551]
The issue is as the title states. Maybe this is working as expected, but it was not intuitive for us.  To reproduce:

- Set `server.port=8080`, or any other value for the field, in an `application.properties` file bundled outside of the typical `/src/main/resources` location
- Create a `@SpringBootTest` with `webEnvironment = WebEnvironment.RANDOM_PORT`
- Inject `@LocalServerPort` into the test class
- Run the tests where `spring.config.location=` the location of your `application.properties` file
- The `@LocalServerPort` will be set to the value specified in the properties file, not the random port

**Comment by snicoll** [comment]
@bvulaj that looks weird to me and I couldn't reproduce the problem you've described. Please attach a sample that we can run (we very much prefer that rather than a list of things to do).

**Comment by bvulaj** [comment]
It actually seems like it was due to the `server.port` being set in the local `spring-boot-devtools.properties` - I will try and put together an example project.

**Comment by snicoll** [comment]
You're not supposed to set `server.port` there, please [check the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-globalsettings).
