### ISSUE TITLE
Can Spring Boot continue running after BeanCreationException?

### ISSUE THREAD

**Issue by bangph** [spring-projects/spring-boot#12558]
I've posted a question on stackoverflow as well https://stackoverflow.com/questions/49381817/can-spring-boot-continue-running-after-beancreationexception

I have a simple web application which needs to create a bean @Bean in a configuration class like this:

```
@Configuration
public class Config {
    @Bean
    public DataSource sourceDataSource() throws Exception {
        // Some code to connect to database which can throw a exception (e.g: Hibernate) and it cannot be catched in Main class.
    }
}
```

And a main class like this:
```
@SpringBootApplication
public class ApplicationMain {
    public static void main(String[] args) throws Exception {    
            SpringApplication.run(ApplicationMain.class, args);
    }        
}
```

If an exception is thrown inside sourceDataSource() the web application will stop because of BeanCreationException. Meanwhile, I just want Spring Boot web application can start and I can catch the error message from it (e.g: Failed to create bean because of Postgresql doesn't run) and later show to the users when they access normal URL, e.g: http://localhost:8080/test - it shows the error message instead of shows a working page).

I guess this question will be closed but please give answer to StackOverFlow.

**Comment by bangph** [comment]
I'm using Spring Boot version 1.5.2 btw.

**Comment by wilkinsona** [comment]
> I guess this question will be closed but please give answer to StackOverFlow.

Correct. As I guess you've already read, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Cross-posting like this just wastes people's time.
