### ISSUE TITLE
Null Beans not allowed anymore?

### ISSUE THREAD

**Issue by yglodt** [spring-projects/spring-boot#12563]
One of my applications intentionally sets a Bean of type com.pi4j.io.gpio.GpioController to `null` if it's not running on a Rapsberry Pi, which is in fact the case during development, and instantiates the Bean if I run it on the Pi.

This used to work fine up until Spring Boot 1.5.10.

After upgrading to 2.0.0 the application refuses to start.

Is this an intentional change in Bean handling?

This is the exception:

```
[ERROR] [20.03.18 19:50:15]   TomcatStarter.java:62   Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'httpSessionListener': Unsatisfied dependency expressed through field 'chartService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chartService': Unsatisfied dependency expressed through field 'impulseService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'impulseService': Unsatisfied dependency expressed through field 'sensorService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorService': Unsatisfied dependency expressed through field 'gpioController'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: **No qualifying bean of type 'com.pi4j.io.gpio.GpioController' available**: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field gpioController in com.mine.service.SensorService required a bean of type 'com.pi4j.io.gpio.GpioController' that could not be found.
```

**Comment by snicoll** [comment]
@yglodt it is an intentional change (in Spring Framework, not Spring Boot). There are several ways to adapt to that change and injecting a `null` bean isn't supported anymore.

In the future please ask questions on StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by yglodt** [comment]
@snicoll merci for the explanantions.

In fact there was already an SO-question but it remained unanswered:

https://stackoverflow.com/questions/49044770/change-in-how-spring-5-handles-null-beans

**Comment by snicoll** [comment]
@yglodt please do not cross-post. If there is an SO question and you feel it's left unnoticed, you can raise awareness on our Gitter channel. I've just answered
