### ISSUE TITLE
UUIDTypeDescriptor.ToBytesTransformer.INSTANCE.parse returns wrong value...

### ISSUE THREAD

**Issue by eztinkerdreams** [spring-projects/spring-boot#12564]
Please see [this](https://stackoverflow.com/questions/49397109/attributeconverter-converter-returns-wrong-value-for-uuid-from-postgres-database) question on StackOverflow for details. 

`UUIDTypeDescriptor.ToBytesTransformer.INSTANCE.parse("15bd728e-53ec-4bba-842b-4b1230989b87".getBytes());`
<img width="767" alt="screen shot 2018-03-20 at 8 16 20 pm" src="https://user-images.githubusercontent.com/7387907/37692537-f953445c-2c7e-11e8-9a7c-58e3479b0652.png">

This does not seem like the expected behavior?

**Comment by spencergibb** [comment]
Why do you think it is a boot problem? `UUIDTypeDescriptor` is from hibernate, correct?

**Comment by eztinkerdreams** [comment]
@spencergibb You are correct, sorry looks like that's a hibernate library.
