### ISSUE TITLE
use jdk10 to exec mvn spring-boot:run  error 

### ISSUE THREAD

**Issue by lilaizhencn** [spring-projects/spring-boot#12567]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.742 s
[INFO] Finished at: 2018-03-21T14:15:23+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project dfc-static: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]

**Comment by wilkinsona** [comment]
The problem appears to be occurring during compilation which is before your application is run. It is not clear why. Depending on your dependencies, Spring Boot May have nothing to do with the compilation of your app. Can you please provide a small sample that reproduces the failure?

**Comment by lilaizhencn** [comment]
hi, the problem has been found, caused by lombok dependence.


`<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.20</version>
</dependency>`

`➜  ~ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
`

mvn spring-boot:run  

`Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags`

**Comment by lilaizhencn** [comment]
hi, the problem has been found, caused by lombok dependence.


`<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.20</version>
</dependency>`

`➜  ~ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
`

mvn spring-boot:run  

`Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags`

**Comment by wilkinsona** [comment]
Thanks for letting us know.
