### ISSUE TITLE
Using Lombok causes devtools reloading is not working

### ISSUE THREAD

**Issue by anaq1** [spring-projects/spring-boot#12578]
Adding lombok dependency causes devtools reloading is not working correctly anymore. For example changed @RestController is after reload not mapped and any further changes are not detected anymore. It is working correctly in version 1.5.9, but not in 1.5.10 and 2.0.0. This issue is caused by incompatibility with lombok in new version in spring boot 1.5.10 (lombok managed version was changed to 1.16.20). 

Steps to reproduce:
1. Create a simple spring-boot (1.5.10 or 2.0.0) project with devtools.
2. Add lombok dependency (use managed version)
3. Add a restcontroller.
4. Run the project and change the restcontroller. In log you can see restcontroller is not mapped anymore. Also the URL is not reachable and all further changes are ignored (application is not realoaded).

Workaround:
Override managed lombok version to 1.16.18. Parent pom.xml:
```
<properties>
  ...
  <lombok.version>1.16.18</lombok.version>
</properties>
```

**Comment by wilkinsona** [comment]
Which IDE are you using? Could this be a duplicate of https://github.com/spring-projects/spring-boot/issues/12264?

**Comment by anaq1** [comment]
I'm using Netbeans. I think it is a duplicate, disappearing class file is a good explanation why the controller is not mapped after reload.
