### ISSUE TITLE
Autoconfiguration for embedded mongodb >=v3.6 fails due to missing feature

### ISSUE THREAD

**Issue by poikilotherm** [spring-projects/spring-boot#12575]
This is related to flapdoodle-oss/de.flapdoodle.embed.mongo/issues/223
Mentioning @snicoll, @wilkinsona as they seem to be most related to the affected features code.

## Environment:

* Spring Boot 2.0.0.RELEASE
* Spring Data MongoDB 2.0.5
* Flapdoodle 2.0.3
* `application.yaml`:
```
spring:
  mongodb:
    embedded:
      version: 3.6.3
```

## Bug description

While using the `application.yaml` described above, I was not able to use the embedded MongoDB. My integration tests failed with:
```
o.s.b.a.mongo.embedded.EmbeddedMongo     : Error parsing command line: unrecognised option '--nohttpinterface'
o.s.b.a.mongo.embedded.EmbeddedMongo     : try '/tmp/extract-5b9d0a8e-f9c7-4c8e-8aec-bf8f1e6b6cbcextractmongod --help' for more information
d.f.e.process.runtime.AbstractProcess    : failed to call onAfterProcessStart()
```
## Possible solution

After reporting the [bug at upstream](flapdoodle-oss/de.flapdoodle.embed.mongo/issues/223), I digged into the auto configuration found at  [`spring-boot/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java`](https://github.com/spring-projects/spring-boot/blob/v2.0.0.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java).

As @Loki-Afro suggested, the custom `ToStringFriendlyFeatureAwareVersion` is not respecting this [breaking change in the upstream MongoDB binaries](https://docs.mongodb.com/master/release-notes/3.6-compatibility/#http-interface-and-rest-api), as it does not add the `Feature` `NO_HTTP_INTERFACE_ARG` by itself. (compare to [Version.java#L207](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/ae3b4f29fb6dc68fc61a45a76103b831f74d22f1/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java#L207) at Flapdoodle)

After changing my `application.yaml` to
```
spring:
  mongodb:
    embedded:
      version: 3.6.3
      features: sync_delay,no_http_interface_arg
```
my tests start working again. Adding `no_http_interface_arg` enables the "anti-feature" mentioned by @Loki-Afro, see also [de.flapdoodle.embed.mongo/src/main/java/de/flapdoodle/embed/mongo/distribution/Feature.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/2f7f44b2cbce0d4bde635d980d112036c553a586/src/main/java/de/flapdoodle/embed/mongo/distribution/Feature.java#L33)

## Next steps

Please let me know if I shall create a fix plus test for this and open a PR or if you fix it yourself. 

Thanks in advance!

**Comment by Loki-Afro** [comment]
if I (member of flapdoodle embed mongo) can support here somehow, just let me know ;)

**Comment by philwebb** [comment]
@poikilotherm Thanks for the detailed analysis. I've targeted this to the 2.0.x backlog. If you do have any time to craft a PR that would be most welcome.

**Comment by poikilotherm** [comment]
Hi @philwebb,

while sorting out ways to resolve this issue, I stumbled over the [Javadoc of `ToStringFriendlyFeatureAwareVersion`](https://github.com/spring-projects/spring-boot/blob/97a71be9b8e2cf4b2fe0625896975865d6a8fdab/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java#L249).
```java
/**
 * A workaround for the lack of a {@code toString} implementation on
 * {@code GenericFeatureAwareVersion}.
 */
```
The Javadoc states the custom class was used because there has been no `toString()`, but this seems to be present nowadays. 

Would you feel comfortable replacing this entire (IMHO error-prone) construct using the [upstream `Versions.java`](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/2f7f44b2cbce0d4bde635d980d112036c553a586/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java) instead or in combination to retain backward compatibility? 

The helper-class has been introduced three years ago in [2c81907d5](https://github.com/spring-projects/spring-boot/commit/2c81907d588690bb623745c95f577a0c60a156f5), things seem to have changed now. As this is Spring Boot v2.0.0, maybe it would be ok to make such a huge and possibly breaking change?

@Loki-Afro any thoughts on this?

Cheers and happy easter!
Poikilotherm

**Comment by philwebb** [comment]
@poikilotherm It generally looks like `Versions might be a good thing to use if there's an exact match _and_ there are no feature properties defined.

I'm thinking we should probably change `EmbeddedMongoProperties` so that `features` is `null`. Then we could consider `null` to mean, use the defaults for that version. In the auto-configuration, if `features` is null we can iterate over the `Version` enum values to see if we can find a matching version. If we can we use the features from it.

The two things I'd like to keep if possible are:
* Someone can define a version number that's not in that enum (for example if they want a later mongo version)
* Someone can override the features properties if they want to change the defaults.

I think `GenericFeatureAwareVersion` still doesn't have a `toString` so I guess our `ToStringFriendlyFeatureAwareVersion` needs to remain.

**Comment by philwebb** [comment]
I've raised https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/240 to see if a `toString` can be added to `GenericFeatureAwareVersion`.

**Comment by snicoll** [comment]
The `toString` has been added.

**Comment by wilkinsona** [comment]
I think we may just need to backport a portion of [this change](https://github.com/spring-projects/spring-boot/commit/706945d2ce84e3e7700864be6c6344b63f0dfdbe).

**Comment by wilkinsona** [comment]
On second look, I think the Embedded Mongo change is only in 2.1.0+ so we may have already done all we can here.

**Comment by snicoll** [comment]
Closing per comment above.

**Comment by TajudeenBusari** [comment]
In spring boot 4.0.0-rc1, the database autoconfiguration for mongo db always default to test even when you set something like this:
data:
mongodb:
database: todosdb
uri: mongodb://tjtechy:apppass@localhost:27017/todosdb?authSource=todosdb. In my project, i had to use a config class to manually create the connection string. Has anyone experienced this?
