### ISSUE TITLE
Provide WebFluxRegistrations for configuring RequestMappingHandlerMapping and the like for Webflux

### ISSUE THREAD

**Issue by jntakpe** [spring-projects/spring-boot#12587]
Configuring RequestMappingHandlerMapping requires to implements WebFluxConfigurationSupport then I'm not able to use Spring Boot webflux autoconfiguration feature due to 
`@ConditionalOnMissingBean({ WebFluxConfigurationSupport.class })`
 on WebFluxAutoConfiguration
For instance in my case I want to add a custom request condition so I have to rewrite the whole WebFluxAutoConfiguration.
It will be great if we were able to automatically  add RequestCondition beans or RequestMappingHandlerMapping to Spring context

**Comment by bclozel** [comment]
Spring Boot provides a `WebMvcRegistrations` interface that you can use to register such components for Spring MVC apps. We could do the same for WebFlux applications.

**Comment by jntakpe** [comment]
@bclozel yes it would be great

**Comment by bclozel** [comment]
Closing in favour of gh-13997
