### ISSUE TITLE
logging.file.max-history is ignored when logging.file contains path

### ISSUE THREAD

**Issue by prewriter** [spring-projects/spring-boot#12596]
Consider the following `application.properties` (rest of project is start.spring.io starter in Spring Boot 2.0 with only web dependency, unchanged otherwise).
```
logging.file=foo/bar.log
logging.file.max-history=2
logging.file.max-size=1KB
```
Start and restart the app few times. The `foo` directory contains now more than 2 archived files with logs, and should contain up to 2.

It works almost correctly (not sure about the .tmp files) when you change the first line to `logging.file=foo.log`, so the problem is the path being there.

**Comment by wilkinsona** [comment]
This appears to be a known issue in Logback: https://jira.qos.ch/browse/LOGBACK-1338.
