### ISSUE TITLE
spring boot issue

### ISSUE THREAD

**Issue by samehsboui** [spring-projects/spring-boot#12595]
![image](https://user-images.githubusercontent.com/33513840/37777026-e41f414e-2de6-11e8-9520-7f464103d822.png)

![image](https://user-images.githubusercontent.com/33513840/37777057-fd435250-2de6-11e8-9d5b-421a28980acc.png)

voici hiérarchie de mon projet : 

![image](https://user-images.githubusercontent.com/33513840/37777097-10ed7f9c-2de7-11e8-9748-eb4d12be8120.png)

voici la classe main : 

![image](https://user-images.githubusercontent.com/33513840/37777164-33c290fc-2de7-11e8-8549-dde8d6bccf4d.png)

**Comment by snicoll** [comment]
You've got a corrupted dependency, run `mvn dependency:purge-local-repository` or check your local Maven cache for a corrupted jar.

Also, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), please ask such questions on StackOverflow as we prefer to use GitHub issues only for bugs and enhancements.

**Comment by samehsboui** [comment]
i tried to run   mvn dependency:purge-local-repository  and i got this :
