### ISSUE TITLE
Add reference to Sprout Platform starter

### ISSUE THREAD

**Issue by jdbranham** [spring-projects/spring-boot#12599]
I've created a spring boot starter that may be useful to some folks -

Specifically this library -
https://github.com/savantly-net/sprout-platform/tree/master/spring/sprout-spring-boot-starter

Used in the larger platform scope - 
https://github.com/savantly-net/sprout-platform

A legacy version of this library may be useful to developers not using Angular 2x+ 
It doesn't include many of the features that the full Sprout platform offers - 
https://github.com/savantly-net/sprout-spring-boot-starter

**Comment by jdbranham** [comment]
I didn't realize v2 was released, but I'll gladly update and test!

**Comment by snicoll** [comment]
Alright, let us know when you have something.

**Comment by jdbranham** [comment]
It required a few modifications around JPA, but now they are both compatible with Spring Boot 2.

**Comment by snicoll** [comment]
> they are both compatible with Spring Boot 2.

Great! Do you still need to push something because I haven't seen an update in the repo.

**Comment by jdbranham** [comment]
Thanks @snicoll 
I've just merged the changes from a development branch.
