### ISSUE TITLE
OAuth 2.0 Client Redirect URI Template TLS Termination

### ISSUE THREAD

**Issue by adenix** [spring-projects/spring-boot#12593]
## Expected Behavior

`{baseUrl}` should use TLS when the application is served with TLS
(e.x. `{baseUrl}/login/oauth2/code/{registrationId}`)

## Actual Behavior

TLS termination causes `baseUrl` to not use TLS

## Specifications
 
  - Java Version: `1.8.0_162`
  - Spring Boot Version: `2.0.0.RELEASE`
  - Spring Security Version: `5.0.3.RELEASE`

**Comment by mbhave** [comment]
@adenix It's not clear from the issue description why you think this is a Spring Boot issue. Spring Boot does not do any TLS termination.

If you would like us to spend some more time investigating, please spend some time to provide a minimal sample that reproduces the problem.

**Comment by adenix** [comment]
I submitted as a spring boot issue because `baseUrl` is something that either spring boot or spring is providing. If their is a setting that I can use to manually set the schema to `https` for the proper environments then that would be an acceptable solution.

Currently when security is constructing my return url it is using `http` and I just need all environments above local to use `https`.

**Comment by adenix** [comment]
Unless `baseUrl` is schema agnostic in which case I have a plan of action. Just need confirmation on that though.

**Comment by mbhave** [comment]
The `{baseUrl}` templating is handled by [Spring Security](https://github.com/spring-projects/spring-security). If you haven't configured a `redirect-uri-template` on the client registration, the default template used is `{baseUrl}/login/oauth2/code/{registrationId}`. The scheme used when resolving this template depends on the scheme of the incoming request. That being said, if you're seeing that that is not the case, you can raise an issue with [Spring Security](https://github.com/spring-projects/spring-security)
