### ISSUE TITLE
Spring Boot JPA Data with MySQL does not load schema.sql

### ISSUE THREAD

**Issue by RaviH** [spring-projects/spring-boot#12612]
**Question**:

I have attached an example project. When changing the spring boot version to 1.5.6.RELEASE the schema.sql is being executed as expected. But, when I change it to 2.0.0.RELEASE, schema.sql is no longer being executed.

Is their a new/another way to do this in Spring Boot 2.0?

Thanks,
Ravi Hasija

P.S: I created an issue with Spring Data JPA: https://jira.spring.io/browse/DATAJPA-1298 but was redirected here.

[spring-boot-mysql-error.zip](https://github.com/spring-projects/spring-boot/files/1843758/spring-boot-mysql-error.zip)

**Comment by snicoll** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues) and the issue template, we prefer to use GitHub issues only for bugs and enhancements.

The migration guide has [an explicit section about this](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#database-initialization).

Adding `spring.datasource.initialization-mode=always` to your project is enough.

Also, I know it's a sample but avoid field injecting things in your `@SpringBootApplication` as it might lead to early initialization issue.
