### ISSUE TITLE
spring. config.location  not work 

### ISSUE THREAD

**Issue by gudegg** [spring-projects/spring-boot#12644]
version:1.5.8.RELEASE
--spring.config.location=file:///G:/deploy/application-local.properties  --spring.profiles.active=local 
![qq 20180327154525](https://user-images.githubusercontent.com/13344666/37953591-e50e4080-31d5-11e8-9e51-186649e5fb21.png)
G:/deploy/application-local.properties The attribute below does not replace the attribute under resources.
2.0.0.RELEASE work well. It is a bug?

**Comment by wilkinsona** [comment]
In 1.5.x, `spring.config.location` is additive. We fixed that in 2.0 where it now replaces the default locations and `spring.config.additional-location` can be used to add a location.
