### ISSUE TITLE
Include non-optional query parameters in href of HAL endpoint links

### ISSUE THREAD

**Issue by sis-yoshiday** [spring-projects/spring-boot#12645]
When we enable `sessions` endpoint and access `/actuator`, then return endpoints json like below.
 
<img width="458" alt="da717ee6a83126ca020c7af23cd912d1" src="https://user-images.githubusercontent.com/4716527/37953074-c60f0d98-31dc-11e8-9ffe-a1937e800097.png">

But it seems wrong `sessions` endpoint's url.

`/actuator/sessions` can't be accessible, but `/actuator/sessions?username={username}`

**Comment by wilkinsona** [comment]
I'm not sure that I agree that it's wrong. The `/actuator/sessions` resource exists (you won't get a 404 response) so it is correctly identifying a resource. However, that resource does require that a `username` is provided, typically via a query parameter.

As far as I can see, the [HAL specification](http://stateless.co/hal_specification.html) is silent on whether non-optional query parameter should be included in the `href` of a templated link. Some Googling suggests it's a question that others have had in the past and there doesn't seem to be a definitive answer.

As things stand, the class that resolves the links to all of the endpoint operations has no knowledge of how the endpoints are invoked, the meaning of `@Nullable`, or how query parameters and the request body are used. The links resolver would have to become aware of all of these things to implement this. I'm not sure that the benefit is worth the additional coupling.

Let's see what the rest of the team thinks.

**Comment by sis-yoshiday** [comment]
@wilkinsona 
Thanks for explanation. I didn't notice this json format was based on HAL Specification.

**Comment by wilkinsona** [comment]
We've discussed this and decided not to implement anything due to HAL not be clear about query parameters and the coupling that would be necessary to fix it.
