### ISSUE TITLE
embeded ldap autocongiguration bug

### ISSUE THREAD

**Issue by kamkie** [spring-projects/spring-boot#12646]
[repo with bug](https://github.com/kamkie/spring-ldap-bug)

org.springframework.boot.autoconfigure.ldap.embedded.EmbeddedLdapAutoConfiguration#ldapContextSource is not setting `source.setBase`

this is set in autoconfiguration for not embeded ldap `org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration#ldapContextSource`

test showing bug `com.example.springldapbug.SpringLdapBugApplicationTests#useLdapRepository`
to trigger buf comment `@Import(LdapConfigurationWorkaround.class)`

bud is also present i spring boot 1.5 line

**Comment by wilkinsona** [comment]
Duplicate of #11693.
