### ISSUE TITLE
Appendix F. Dependency versions pulled two versions 

### ISSUE THREAD

**Issue by jnercy** [spring-projects/spring-boot#12653]
The following table provides details of all of the dependency versions that are provided by Spring Boot in its CLI (Command Line Interface), Maven dependency management, and Gradle plugin. When you declare a dependency on one of these artifacts without declaring a version, the version listed in the table is used. 
But i specified the version like this

```
           <dependency>
                <groupId>org.elasticsearch.client</groupId>
                <artifactId>transport</artifactId>
                <version>5.4.3</version>
            </dependency>
```

![image](https://user-images.githubusercontent.com/16145081/38004850-b3b32e10-3270-11e8-8bb2-e8921cb89698.png)
the Dependency has two version

**Comment by philwebb** [comment]
`org.elasticsearch:elasticsearch` is also a managed dependency. You either need to also override it, or you can set a property to cover both at the same time:

```xml
<properties>
    <elasticsearch.version>5.4.3</elasticsearch.version>
<properties>
```

See [this section of the docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven-parent-pom).
