### ISSUE TITLE
start.spring.io includes milestones for boot 2.0.0 without warning

### ISSUE THREAD

**Issue by irobertson** [spring-projects/spring-boot#12651]
On start.spring.io, if I ask to create a project using Spring Boot 2.0.0, I have the option of adding the Gateway dependency (part of Cloud Routing). The generated pom has the version set (via the spring-cloud.version property) to Finchley.M9.

I was under the impression that by asking for a starter project based off of an official release, I would only get officially released versions. It was only after I started digging into an issue that I realized I had been given a pom with milestone dependencies in it.

I would suggest some sort of indication on the page when a non-GA version dependency is selected while creating a project based off of a GA of spring-boot.

**Comment by philwebb** [comment]
I've raised at initializr issue at https://github.com/spring-io/initializr/issues/640

**Comment by irobertson** [comment]
Doh! I meant to submit this to the initializr project, but I must have used the wrong window. Thanks for the fix, and my apologies for the inconvenience.
