### ISSUE TITLE
IllegalStateException when using ServerEndpointExporter and running the project as a war in Jetty

### ISSUE THREAD

**Issue by Artur-** [spring-projects/spring-boot#12657]
Run into with Vaadin Flow when enabling JSR-356 websocket support for Spring Boot applications. The websocket endpoints are registered using `VaadinWebsocketEndpointExporter extends ServerEndpointExporter`. This works fine for the embedded case, i.e. launching the application class in Eclipse/IDEA but if you create a war file and deploy to Jetty, then it fails.

`ServerEndpointExporter` has an internal assertion in `afterPropertiesSet`, which fails because the Server Container is not available. 
```
Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
    at org.springframework.util.Assert.state(Assert.java:73)
    at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
...
```

You can see the problem if you do
```
git clone git@github.com:vaadin/flow.git
git checkout be6bb15a24ba2dcdb0a0f411bd34512ba3ddeaa2 # This is the current master without any workaround
cd flow
mvn install -DskipTests
```

as `flow-tests/test-spring-war` will fail with `IllegalStateException` 

Some more info in https://github.com/vaadin/flow/blob/be6bb15a24ba2dcdb0a0f411bd34512ba3ddeaa2/flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java#L38

**Comment by wilkinsona** [comment]
Thanks for the report, but I don't think this has anything to do with Spring Boot. We you're deploying to a container, Spring Boot has nothing to do with web socket configuration. I suspect this is either a problem in Spring Framework or in how your Jetty instance is configured. If this turns out not to be the case and your problem is caused by Spring Boot, please let us know and we can re-open this issue.

**Comment by Artur-** [comment]
Thanks, created https://jira.spring.io/browse/SPR-16655
