### ISSUE TITLE
WebClient could not post json body to server

### ISSUE THREAD

**Issue by zengzhifeng** [spring-projects/spring-boot#12656]
SpringBoot 2.0.0 Release

```java
val client = WebClient.create()
client.post().uri(url)
                .syncBody(payload)
                .retrieve()
                .bodyToMono<ApiResponse>()
                .doOnError {
                    logger.info("Failed to notify, reason: ${it.message}")
                }
                ...
```
for some web servers (java ,php, etc.), I got this kind of error:

Failed to notify, reason: ClientResponse has erroneous status code: **411 Length Required**

**Comment by bclozel** [comment]
Spring Framework's `WebClient` (and WebFlux servers) use a lot the `"Transfer-Encoding: chunked"` header, especially when they're streaming data - in those cases, the length of the body is consumed in a reactive way and the full body length is not known in advance. This is perfectly valid behavior according to the HTTP protocol, so I guess this is a limitation of the other web servers you're dealing with.

Note that in the next release, Spring Framework will relax that a bit and try to send the `"Content-Length"` header when possible. See [SPR-16542](https://jira.spring.io/browse/SPR-16542). You can try the latest Spring Boot `2.0.1.BUILD-SNAPSHOT` and see if this fixes your problem.

For other questions, please use StackOverflow.
Thanks!

**Comment by zengzhifeng** [comment]
Thanks @bclozel 

still no luck with Spring Boot 2.0.1.BUILD-SNAPSHOT.

it seems we have to fallback to the other HttpClient libs to deal with legacy web frameworks
