### ISSUE TITLE
PathMatchingResourcePatternResolver with strange behavior on search via pattern

### ISSUE THREAD

**Issue by betonetotbo** [spring-projects/spring-boot#12661]
**Spring-boot version:** 1.4.7.RELEASE

I'm trying to use the `PathMatchingResourcePatternResolver` to list some resources of an runtime-created `URLClassLoader`. The issue is about **listing sub-directories** in a specific package.

This is my case:

I have 2 JARs and 1 directory as the source of my class loader, like this:
```
/my-default.jar
    /reports
        /report-1
        /report-2
        /report-3
/my-customization.jar
    /product-x
        /reports
            /report-2     >>> customization of report-2 from my-default.jar
            /report-4-newone
/path/to/local/storage
    /reports
        /report-created-by-enduser
```
_NOTE: each `report` folder has 1 or more `.JRXML` files_

My URLClassLoader is create with this URLs:

```
URLClassLoader cl = new URLClassLoader(new URL[] { 
    new URL("file:/c:/path/to/local/storage"), 
    new URL("jar:file:/path/to/my-customization.jar!/product-x/"), 
    new URL("jar:file:/path/to/my-default.jar!/") 
});
```

Now I need to **list all sub directories** in classpath starting with `reports/` (for that I used the pattern `classpath:reports/*`):

```
PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver(cl);
Resource[] resources = resolver.getResources("classpath:reports/*");
```

This returns **wrong results** (only 1 result, as so with another pattern `classpath:/reports/*`): 

```
file:/c:/path/to/local/storage/reports/report-created-by-enduser
```
 
The expected result in URLs (pay attention on the classpath precedence) is:
```
file:/c:/path/to/local/storage/reports/report-created-by-enduser
jar:file:/path/to/my-customization.jar!/product-x/reports/report-2
jar:file:/path/to/my-customization.jar!/product-x/reports/report-4-newone
jar:file:/path/to/my-default.jar!/reports/report-1
jar:file:/path/to/my-default.jar!/reports/report-3
```

Here are other results by different patterns:

```
resolver.getResources("classpath:/reports/*")
= [ file:/c:/path/to/local/storage/reports/report-created-by-enduser ]

resolver.getResources("classpath:/reports/*/")
= [ ]

resolver.getResources("classpath:/reports/*/*")
= [ file:/c:/path/to/local/storage/reports/report-created-by-enduser ]

resolver.getResources("classpath:reports/**/*.jrxml")
= [ ]
```

Note, when I get the specific resource providing the full path it returns the correct resource:

```
resolver.getResources("classpath:/reports/report-2/report-2.jrxml")
= [ jar:file:/path/to/my-customization.jar!/product-x/reports/report-2/report-2.jrxml ]

resolver.getResources("classpath:/reports/report-1/report-1.jrxml")
= [ jar:file:/path/to/my-default.jar!/reports/report-1/report-1.jrxml ]
```

**Comment by wilkinsona** [comment]
Thanks for the detailed report, but `PathMatchingResourcePatternResolver` is part of Spring Framework. Its issue tracker is [here](https://jira.spring.io/browse/SPR).

**Comment by betonetotbo** [comment]
OK, thanks!

Issue created for Spring Framework https://jira.spring.io/browse/SPR-16659
