### ISSUE TITLE
MockBean name is not what is specified in the name attribute

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#12665]
```kotlin
@MockBean(name = "condition")
lateinit var condition: Condition
```

...
```
condition = {Condition$MockitoMock$1144144523@4738} "condition bean"
 mockitoInterceptor = {MockMethodInterceptor@4781} 
  handler = {InvocationNotifierHandler@4782} 
  mockCreationSettings = {CreationSettings@4783} 
   typeToMock = {Class@2702} "interface mypackage.condition.Condition"
   extraInterfaces = {HashSet@4785}  size = 0
   name = "condition bean"
   spiedInstance = null
   defaultAnswer = {Answers@4786} "RETURNS_DEFAULTS"
   mockName = {MockNameImpl@4787} "condition bean"
   ...
```

As shown above, the word " bean" is appended to the given `MockBean` name "condition" for no apparent reason. When `name` is not specified, it's ok for the framework to choose whatever name it can come up with; however, when `name` is specified, there is a reason that the user specified it, and it shouldn't be tampered with.

This has larger side effects such that dynamic properties that rely on the bean name can't be used for testing. In one use case, I use the bean name to dynamically override some properties at runtime, not unlike [Hystrix Configuration](https://github.com/Netflix/Hystrix/wiki/Configuration), and this bug prevents me from using `MockBean` for testing that feature.

**Comment by philwebb** [comment]
@asarkar The `name` attribute does change the bean name in the Spring Context and we don't mess with that. The output you've shown is the name used by Mockito, which we intentionally add "bean" to that to make it clear it was created by Spring Boot.

What problem are you actually seeing? Can you provide a sample application that shows it?

**Comment by asarkar** [comment]
@philwebb The problem is related to https://github.com/spring-projects/spring-boot/issues/12664. When the `name` attribute is used for dynamic binding, `prefix.<space> bean.property` is not acceptable as a valid property name to bind during testing. I'm not sure why anyone would be interested in knowing whether the mock was created by Spring or not, since the object reference exists for tracking anything anywhere in the JVM.
See https://github.com/asarkar/spring/blob/master/touchstone/src/main/kotlin/condition/ConditionsExecutor.kt#L35

**Comment by philwebb** [comment]
@asarkar I've not done much Kotlin so I'm having a hard time figuring out what's going on. Is the `qualifiedName` that [you're using](https://github.com/asarkar/spring/blob/master/touchstone/src/main/kotlin/condition/Condition.kt#L30) generated from the `toString()` of the mock or something? Perhaps the bean name would be a better choice as the binding prefix.

**Comment by asarkar** [comment]
[qualifiedName](https://github.com/asarkar/spring/blob/master/touchstone/src/main/kotlin/condition/Condition.kt#L29) implementation is a simple default method without knowledge of Spring context. I think it's unnecessary to couple it with Spring. The problem I'm trying to highlight is that most people would expect the `name` attribute of {{MockBean}} to be the bean name itself, and other than providing the forced hint that the mock was created by Spring, there doesn't seem to be a good reason to make it otherwise.

**Comment by philwebb** [comment]
I'm not sure most people are directly interacting with the mock name, unless they are in a debugger or looking at verification errors. Under the hood we're calling `MockSettings.name(...)` which has the following javadoc:

> Specifies mock name. Naming mocks can be helpful for debugging - the name is used in all verification errors. Beware that naming mocks is not a solution for complex code which uses too many mocks or collaborators. If you have too many mocks then refactor the code</b> so that it's easy to test/debug without necessity of naming mocks.

I definitely feel like the extra "bean" suffix helps with verification failures by sending a signal the the mock is for a bean.

I'm still a little confused how the `javaClass.simpleName` call in `qualifiedName` gets the name of the mock. It's probably a Kotlin thing that I'm just not understanding. Perhaps there's something else you can use? Or you could just strip off the " bean" part of the name.

**Comment by asarkar** [comment]
It’s hard to reason against “I think it’s useful for you, so you must have it, even though you never asked for it”. Thanks for your time.
