### ISSUE TITLE
Binding configuration properties dynamically is lot harder than it needs to be

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#12664]
I've a use case where I need to bind configuration properties based on a prefix determined at runtime.
```kotlin
interface Condition {
    companion object {
        const val PREFIX = "touchstone.condition"
    }

    enum class Phase {
        PRE, POST
    }

    fun run(chunkContext: ChunkContext): ExitStatus

    fun phase(): Phase = Phase.PRE

    fun order(): Int = 1

    fun shouldRun(): Boolean = true

    val qualifiedName: String
        get() = listOf(PREFIX, phase().name, javaClass.simpleName)
                .joinToString(separator = ".") { it.toLowerCase(Locale.ENGLISH) }
}
```

Each implementation of the above interface can override the values `order`and `shouldRun` using usual Boot configuration overrides. This is not unlike how [Hystrix Configurations](https://github.com/Netflix/Hystrix/wiki/Configuration) work; in other words, not unprecedented. However, doing this in practice is a lot harder than it needs to be, due to unnecessary package-level access of some classes in the framework, and in general lack of support for the Open/closed principal. Let's break it down:

1. `ConfigurationPropertiesBinder.bind(Bindable<?> target)` method is `public` and looks promising since creating a `Bindable` is not hard, but then it does
```java
Assert.state(annotation != null, "Missing @ConfigurationProperties on " + target);
```
which is a problem when dynamically creating a target. The annotation can be synthesized (more on that later), so it's not technically necessary for it to be specified at compile time.

2. Methods `getValidators` and `getBindHandler` called from `bind` are `private` scoped, so I had to copy-paste them with minor modifications.

3. `bind` creates a `Binder`, which uses quite a few classes with package-scoped constructor. Thus, in order to create a `Binder`, I'd to resort to the hack of putting the following class in `org.springframework.boot.context.properties` package. This is completely unnecessary.
```kotlin
class BinderFactory {
    companion object {
        private fun propertyEditorInitializer(ctx: ApplicationContext): Consumer<PropertyEditorRegistry>? {
            return if (ctx is ConfigurableApplicationContext) {
                Consumer {
                    ctx.beanFactory.copyRegisteredEditorsTo(it)
                }
            } else null
        }

        fun newBinder(ctx: ApplicationContext): Binder {
            val propertySources = PropertySourcesDeducer(ctx)
                    .propertySources
            return Binder(
                    ConfigurationPropertySources.from(propertySources),
                    PropertySourcesPlaceholdersResolver(propertySources),
                    ConversionServiceDeducer(ctx).conversionService,
                    propertyEditorInitializer(ctx)
            )
        }
    }
}
```

4. Having done all that, now I can write the following, apparently simple, code:
```kotlin
val annotation = synthesizeAnnotation(qn)
val target = bindable(annotation)
val handler = bindHandler(annotation)

BinderFactory.newBinder(ctx).bind(qn, target, handler)
qn to target.value.get()
```

where `synthesizeAnnotation` uses `AnnotationUtils.synthesizeAnnotation` to do what it claims. The rest of the private methods calls should be obvious from the context.

*Possible fix*:

1.  An overloaded version of `bind` accepting a `ConfigurationProperties annotation` should solve this problem while maintaining backward compatibility.
2. Creating a `BinderFactory` class (or a static factory method in `Binder`) will not require changing the package scope of the various constructors used by `Binder` for those who want to use it directly without going through `ConfigurationPropertiesBinder`.
3. I see no reason why `bindHandler` as shown below can't be a `public static` method.
```kotlin
private fun bindHandler(annotation: ConfigurationProperties): BindHandler {
    var handler = BindHandler.DEFAULT
    if (annotation.ignoreInvalidFields) {
        handler = IgnoreErrorsBindHandler(handler)
    }
    if (!annotation.ignoreUnknownFields) {
        val filter = UnboundElementsSourceFilter()
        handler = NoUnboundElementsBindHandler(handler, filter)
    }
    return handler
}
```

**Comment by asarkar** [comment]
After reading [this](https://spring.io/blog/2018/03/28/property-binding-in-spring-boot-2-0) post from @philwebb, I came up with a simpler way. I removed the `BindHandler` as I had no need for it.
```
val bindable = Bindable.of(ConditionProperties::class.java)
val properties = ConfigurationPropertySources.get(env)
qn to Binder(properties)
  .bind(qn, bindable)
  .orElse(ConditionProperties())
```

**Comment by asarkar** [comment]
@philwebb why was this closed, we didn't solve the issue with `BindHandler`?

**Comment by philwebb** [comment]
> I removed the BindHandler as I had no need for it.

I assumed the comment above meant you'd found a solution.

**Comment by philwebb** [comment]
I feel like you're abusing `ConfigurationPropertiesBinder`, it's intentionally an internal class and it's not designed to have dynamic prefixes. I think that you should work directly with the `Binder`.

**Comment by hexian** [comment]
我的spring boot版本是2.0.2， 我做了如下修改： 
修改的出发点是: 让@ConfigurationProperties中的数字支持数学表达式的计算，配置如下：
application-local.yml
# @ConfigurationProperties 本身不支持表达式解析,  通过 com.ducha.postprocessor.CustomerConfigurationPropertiesBindingPostProcessor 自定义来支持表达式 
customer:
  testInt3: (200*2+10)/5+${testInt}
  testDate: 21:26 2020-09-26
  weight: 5kg # 自定义类型转换器 com.ducha.convert.MyConvert 
  child1: 
    c1: (5+5)*3


import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.beans.factory.support.BeanDefinitionRegistry;
import org.springframework.beans.factory.support.GenericBeanDefinition;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringApplicationRunListener;
import org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata;
import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.Ordered;
import org.springframework.core.env.ConfigurableEnvironment;

import com.ducha.postprocessor.CustomerConfigurationPropertiesBindingPostProcessor;

public class MyEventPublishingRunListener implements SpringApplicationRunListener, Ordered  {

	private final SpringApplication application;
	
	private final String[] args;
	
	//private ExtendSimpleTypeConverter newTypeConverter = null;
	    
	public MyEventPublishingRunListener(SpringApplication application, String[] args) {
		 this.application = application;
	     this.args = args;
	}

	// 这种方式也可以, 更通用的方式是在: com.ducha.aware.MyBeanFactoryAware 中进行设置
	@Override
	public void contextPrepared(ConfigurableApplicationContext context) {
		/*
		// 在准备容器阶段替换掉默认的  TypeConverter
		ConfigurableListableBeanFactory beanFactory = context.getBeanFactory();
		TypeConverter typeConverter = beanFactory.getTypeConverter();
		// 支持从字符串到日期格式转换
		newTypeConverter = new ExtendSimpleTypeConverter(typeConverter, beanFactory);
		beanFactory.setTypeConverter(newTypeConverter);
		//beanFactory.setTypeConverter(typeConverter);
		 */
		
		// 参考自: org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar.registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry)
		//BeanDefinitionRegistry registry = (BeanDefinitionRegistry)context;
		ConfigurableListableBeanFactory beanFactory = context.getBeanFactory();
		BeanDefinitionRegistry registry = (BeanDefinitionRegistry) beanFactory;
		if (!registry.containsBeanDefinition(ConfigurationPropertiesBindingPostProcessor.BEAN_NAME)) {
			// 覆盖 ConfigurationPropertiesBindingPostProcessorRegistrar 的 registerBeanDefinitions 方法中的值
			registerConfigurationPropertiesBindingPostProcessor(registry);
			registerConfigurationBeanFactoryMetadata(registry);
		}
	}
	
	// 参考自: org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar.registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry)
	private void registerConfigurationPropertiesBindingPostProcessor(BeanDefinitionRegistry registry) {
		GenericBeanDefinition definition = new GenericBeanDefinition();
		// 替换成自己的类
		definition.setBeanClass(CustomerConfigurationPropertiesBindingPostProcessor.class);
		definition.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
		registry.registerBeanDefinition(ConfigurationPropertiesBindingPostProcessor.BEAN_NAME, definition);

	}
	
	// 参考自: org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar.registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry)
	private void registerConfigurationBeanFactoryMetadata(BeanDefinitionRegistry registry) {
		GenericBeanDefinition definition = new GenericBeanDefinition();
		definition.setBeanClass(ConfigurationBeanFactoryMetadata.class);
		definition.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
		registry.registerBeanDefinition(ConfigurationBeanFactoryMetadata.BEAN_NAME, definition);
	}
	
	@Override
	public int getOrder() {
		return 100;
	}

	@Override
	public void starting() {
		
	}

	@Override
	public void environmentPrepared(ConfigurableEnvironment environment) {
		// 可以在这里注入属性
	}

	@Override
	public void contextLoaded(ConfigurableApplicationContext context) {
		
	}

	@Override
	public void started(ConfigurableApplicationContext context) {
		
	}

	@Override
	public void running(ConfigurableApplicationContext context) {
		
	}

	@Override
	public void failed(ConfigurableApplicationContext context, Throwable exception) {
		
	}


}








import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.List;

import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.beans.factory.config.EmbeddedValueResolver;
import org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
import org.springframework.boot.context.properties.bind.BindContext;
import org.springframework.boot.context.properties.bind.BindHandler;
import org.springframework.boot.context.properties.bind.BindResult;
import org.springframework.boot.context.properties.bind.Bindable;
import org.springframework.boot.context.properties.bind.Binder;
import org.springframework.boot.context.properties.source.ConfigurationPropertyName;
import org.springframework.context.ApplicationContext;
import org.springframework.core.ResolvableType;
import org.springframework.core.annotation.AnnotationUtils;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.util.Assert;
import org.springframework.util.StringValueResolver;
import org.springframework.validation.Validator;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.context.support.GenericWebApplicationContext;

import com.ducha.annotation.Calculate;

/**
 * 
 * @author hexian 
 */
//@Component
//@Component(value="org.springframework.context.annotation.internalConfigurationAnnotationProcessor")
//org.springframework.context.annotation.AnnotationConfigUtils.registerAnnotationConfigProcessors(BeanDefinitionRegistry registry, @Nullable Object source)
//org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar 
public class CustomerConfigurationPropertiesBindingPostProcessor extends ConfigurationPropertiesBindingPostProcessor {

	private ConfigurationBeanFactoryMetadata beanFactoryMetadata;

	private ApplicationContext applicationContext;
	
	private ConfigurableEnvironment environment;
	
	private ConfigurableListableBeanFactory beanFactory;
	
	// configurationPropertiesBinder =====> org.springframework.boot.context.properties.ConfigurationPropertiesBinder
	private Object configurationPropertiesBinder;
	
	public CustomerConfigurationPropertiesBindingPostProcessor() {
		System.out.println("11111");
	}
	
	@Override
	public int getOrder() {
		// order的规则: order的值越小,优先级越高order如果不标注数字,默认最低优先级,因为其默认值是int最大值该注解等同于实现Ordered接口getOrder方法
		return super.getOrder() - 10;
	}

	@Override
	public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
		super.setApplicationContext(applicationContext);
		
		this.applicationContext = applicationContext;
		if(this.applicationContext instanceof GenericWebApplicationContext) {
			GenericWebApplicationContext content = (GenericWebApplicationContext)this.applicationContext;
			this.environment = content.getEnvironment();
			this.beanFactory = content.getBeanFactory();
		}
		
	}
	
	@Override
	public void afterPropertiesSet() throws Exception {
		super.afterPropertiesSet();
		
		try {
			this.beanFactoryMetadata = this.applicationContext.getBean(ConfigurationBeanFactoryMetadata.BEAN_NAME, ConfigurationBeanFactoryMetadata.class);
			Field field = ConfigurationPropertiesBindingPostProcessor.class.getDeclaredField("configurationPropertiesBinder");
			field.setAccessible(true);
			configurationPropertiesBinder = field.get(this);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
		ConfigurationProperties annotation = getAnnotation(bean, beanName, ConfigurationProperties.class);
		if (annotation != null) {
			// 调用父类的方法
			//super.postProcessBeforeInitialization(bean, beanName);
			// 使用自定义的方法代替 super.postProcessBeforeInitialization(bean, beanName);
			this.bind(bean, beanName, annotation);
		}
		
		return bean;
	}
	
	// 使用反射来调用
	@SuppressWarnings("unused")
	private void bind(Object bean, String beanName, ConfigurationProperties annotation) {
		try {
			String prefix = annotation.prefix();
			
			Bindable<?> target = getBindable(bean, beanName, annotation);
			BindHandler bindHandler = getBindHandler(annotation, target);
			BindHandler proxyBindHandler = new MyBindHandler(bindHandler, this.environment, this.beanFactory);
			Binder binder = getBinder();
			
			// 绑定属性到bean
			BindResult<?> bind = binder.bind(prefix, target, proxyBindHandler);
			//System.out.println(bind);
		} catch (Exception e) {
			e.printStackTrace();
		} 
	}
	
	private Binder getBinder() {
		Binder binder = null;
		try {
			Class<?> clazz = this.configurationPropertiesBinder.getClass(); 
			Method binderMethod = clazz.getDeclaredMethod("getBinder", new Class[] {});
			binderMethod.setAccessible(true);
			binder = (Binder)binderMethod.invoke(this.configurationPropertiesBinder, new Object[] {});
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return binder;
	}
	
	private BindHandler getBindHandler(ConfigurationProperties annotation, Bindable<?> target) {
		BindHandler bindHandler = null;
		try {
			List<Validator> validators = getValidators(target);
			Class<?> clazz = this.configurationPropertiesBinder.getClass(); 
			Method bindHandlerMethod = clazz.getDeclaredMethod("getBindHandler", new Class[] {ConfigurationProperties.class, List.class});
			bindHandlerMethod.setAccessible(true);
			bindHandler = (BindHandler)bindHandlerMethod.invoke(this.configurationPropertiesBinder, new Object[]{annotation, validators});
		} catch (Exception e) {
			e.printStackTrace();
		} 
		
		return bindHandler;
	}
	
	private Bindable<?> getBindable(Object bean, String beanName, ConfigurationProperties annotation){
		ResolvableType type = getBeanType(bean, beanName);
		Validated validated = getAnnotation(bean, beanName, Validated.class);
		Annotation[] annotations = (validated != null ? new Annotation[] { annotation, validated } : new Annotation[] { annotation });
		Bindable<?> target = Bindable.of(type).withExistingValue(bean).withAnnotations(annotations);
		// 断言
		Assert.state(annotation != null, () -> "Missing @ConfigurationProperties on " + target);
		
		return target;
	}
	
	@SuppressWarnings("unchecked")
	private List<Validator> getValidators(Bindable<?> target){
		List<Validator> validators = null;
		try {
			Class<?> clazz = this.configurationPropertiesBinder.getClass(); //Class.forName("org.springframework.boot.context.properties.ConfigurationPropertiesBinder");
			Method validatorsMethod = clazz.getDeclaredMethod("getValidators", new Class[] {Bindable.class});
			validatorsMethod.setAccessible(true);
			validators = (List<Validator>)validatorsMethod.invoke(this.configurationPropertiesBinder, new Object[] {target});
		} catch (Exception e) {
			e.printStackTrace();
		} 
		
		return validators;
	}
	
	private ResolvableType getBeanType(Object bean, String beanName) {
		Method factoryMethod = this.beanFactoryMetadata.findFactoryMethod(beanName);
		if (factoryMethod != null) {
			return ResolvableType.forMethodReturnType(factoryMethod);
		}
		ResolvableType forClass = ResolvableType.forClass(bean.getClass());
		
		return forClass;
	}

	private <A extends Annotation> A getAnnotation(Object bean, String beanName, Class<A> type) {
		A annotation = this.beanFactoryMetadata.findFactoryAnnotation(beanName, type);
		if (annotation == null) {
			annotation = AnnotationUtils.findAnnotation(bean.getClass(), type);
		}
		
		return annotation;
	}
	
}

/**
 * 
 * @author hexian
 * 代理
 */
class MyBindHandler implements BindHandler {
	
	private BindHandler bindHandler;
	
	private ConfigurableEnvironment environment;
	
	private ConfigurableListableBeanFactory beanFactory;
	
	MyBindHandler(BindHandler bindHandler, ConfigurableEnvironment environment, ConfigurableListableBeanFactory beanFactory){
		this.bindHandler = bindHandler;
		this.environment = environment;
		this.beanFactory = beanFactory;
	}
	
	@Override
	public Object onFailure(ConfigurationPropertyName name, Bindable<?> target, BindContext context, Exception error) throws Exception {
		Calculate calculate = (Calculate)target.getAnnotation(Calculate.class);
		if(calculate!=null) {
			// 属性值(解析前的表达式)
			String propVal = this.getProperty(name);
			//Object originVal = target.getValue().get();
			StringValueResolver resolver = new EmbeddedValueResolver(this.beanFactory);
			// 表达式解析后的字符串值
			String resolveValue = resolver.resolveStringValue(getExpresionValue(propVal));
			// 获取解析后的值(不需要解析了, Spring会调用转换器自己进行转换)
			//Integer parsedValue = Integer.valueOf(resolveValue);
			System.out.println("解析数学表达式: " + propVal + " =====> "+ resolveValue);
			
			// 中断操作
			return resolveValue;
		}
		
		// 调用原来的方法
		Object onFailure = this.bindHandler.onFailure(name, target, context, error);
		
		return onFailure;
	}

	@Override
	public boolean onStart(ConfigurationPropertyName name, Bindable<?> target, BindContext context) {
		boolean onStart = this.bindHandler.onStart(name, target, context);
		// 是否可以考虑在这个方法里面对 environment 的值进行修改然后再重新设置到 environment 中?
		
		return onStart;
	}

	// 只有当处理完后的返回值不为null时才会回调 onSuccess 方法
	@Override 
	public Object onSuccess(ConfigurationPropertyName name, Bindable<?> target, BindContext context, Object result) {
		// 调用原先的方法进行解析 
		Object onSuccess = this.bindHandler.onSuccess(name, target, context, result);
		
		return onSuccess;
	}

	@Override
	public void onFinish(ConfigurationPropertyName name, Bindable<?> target, BindContext context, Object result) throws Exception {
		this.bindHandler.onFinish(name, target, context, result);
	}
	
	private String getProperty(ConfigurationPropertyName name) {
		// 属性名称
		String propName = name.toString();
		// 属性值(解析前的表达式)
		String propVal = this.environment.getProperty(propName);
		
		return propVal;
	}
	
	private String getExpresionValue(Object value) {
		return "#{"+value.toString().trim()+"}";
	}
	
}
