### ISSUE TITLE
JacksonAutoConfiguration.FEATURE_DEFAULTS not reflected in property hint docs in properties editor.

### ISSUE THREAD

**Issue by jezovuk** [spring-projects/spring-boot#12675]
Since property hints/docs are generated based on property javadoc (when using `@ConfigurationProperties`), and `spring.jackson.*` properties target the `JacksonProperties` class, hint for serialization/deserialization features is inherited from enum members' javadoc in `com.fasterxml.jackson.databind.SerializationFeature / com.fasterxml.jackson.databind.DeserializationFeature`. These are, of course, not aware of default overrides in `JacksonAutoConfiguration` via `FEATURE_DEFAULTS`.

Encountered with Spring Boot 2.0.0.RELEASE.

I'm not sure what would be the good way around this, but at least some kind of mention/warning in documentation would be nice. Got me confused.

**Comment by snicoll** [comment]
That's interesting, thanks. If we went down the route of providing custom metadata for this, we should implement #9945 first.

**Comment by jezovuk** [comment]
I'm aware that hint comes from the javadoc. Just to be clear, I'm talking about property hints displayed in Spring Properties editor in Eclipse (when editing application.properties, with Spring IDE plug-in for Eclipse). However, if not explicitly specified, property `spring.jackson.serialization.write-dates-as-timestamps` will default to `false` (due to default specified in `JacksonAutoConfiguration`), while its hint states that this serialization feature defaults to `true` (hint is coming from Jackson's javadoc).

It seems that current hint is confusing (not the Jackson's javadoc by itself - it is correct as far as Jackson is concerned - but when used as Spring Boot property hint, since Spring Boot overrides the default). Updating the ref guide to explicitly state that hint is wrong in this case would be good enough, I guess.

**Comment by jezovuk** [comment]
![spring-boot-12675](https://user-images.githubusercontent.com/1548456/38372239-9a7a8b3a-38ee-11e8-83bf-ad404e1989da.png)

**Comment by snicoll** [comment]
OK that confirms my suspicion. 

>  while its hint states that this serialization feature defaults to true 

I just wanted to make sure that something outside of the Javadoc wasn't providing that information. So we're back to [my original comment](https://github.com/spring-projects/spring-boot/issues/12675#issuecomment-378639071). Based on your feedback @wilkinsona also raised https://github.com/spring-projects/spring-ide/issues/265

**Comment by jezovuk** [comment]
Yes, making it obvious that I'm seeing Jackson javadoc would have helped (along with the note in ref guide). As it is, I had to dig a bit through Spring Boot and Jackson sources to make sure what is the actual default value being used.

This issue can be closed as far as I'm concerned.

**Comment by snicoll** [comment]
Thanks for the feedback
