### ISSUE TITLE
Hibernate generated fields not populated in tests annotated with @DataJpaTest

### ISSUE THREAD

**Issue by GoGoris** [spring-projects/spring-boot#12679]
Using Spring Boot 2.0.0.RELEASE and Junit 5.1.0.

The annotationprocessor for `@GeneratorType` annotations does not seem to get loaded in tests annotated with `@DataJpaTest`.

I have a jpa object with a custom Hibernate ValueGenerator that generates a custom project code. 
This test fails when it is ran with the `@DataJpaTest` annotation because the field is not generated at insertion.

My Jpa object has the following field: 
```java
@Entity
public class Project {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID")
    private Long id;

    @GeneratorType(type = NummerGenerator.class, when = GenerationTime.INSERT)
    @Column(name = "CODE")
    private String code;

}
```

This is my testcase, it fails on the last assertion. So the id is generated correctly but the project code is not.
The test passes if I replace `@DataJpaTest` with `@SpringBootTest @AutoConfigureTestDatabase`.
```java
@ExtendWith(SpringExtension.class)
@DataJpaTest
public class ProjectRepositoryTest {
        @Autowired
	private ProjectRepository repository;

	@Test
	public void saveTest() {
		Project project = Project.builder().naam("test").build();
		project = repository.save(project);

		assertThat(project).isNotNull();
		assertThat(project.getId()).as("id").isGreaterThan(0L);
		assertThat(project.getCode()).as("Code after insertion").isEqualTo("PREFIX123");
	}
}
```

**Comment by snicoll** [comment]
@GoGoris I fail to see what `@SpringBootTest` would bring that `@DataJpaTest` doesn't. As far as I know the handling of `GeneratorType` is 100% in the hands of Hibernate.

Rather than pasting code that gives us an idea of what the problem might be, could you please share a project that we can run ourselves?

**Comment by GoGoris** [comment]
Here you go: https://github.com/GoGoris/hibernate-generatortype-datajpatest

I created 2 tests:
- ProjectRepositoryTest uses `@DataJpaTest` and fails
- SpringBootProjectRepositoryTest uses `@SpringBootTest @AutoConfigureTestDatabase` and succeeds.

**Comment by GoGoris** [comment]
I have found the issue by coincidence: Apparantly the value is not generated untill the data is flushed. 
The springboottest also fails if I put @Transactional on the testcase. If I then call respository.saveAndFlush, the test passes.

This means that this is not spring-boot related, as such this issue can be closed.
