### ISSUE TITLE
Embedded Artemis is missing default config for DLQ and ExpiryQueue

### ISSUE THREAD

**Issue by graben** [spring-projects/spring-boot#12678]
#3552 
@snicoll 

Artemis is warning all time if AddressSettings for DLQ and ExpiryQueue are not configured on embedded broker. IMHO there should be a general default settings for all managed destinations like Artemis default config.

```
2018-03-29 08:10:29.929  WARN 4080 --- [mpl$5@7cfd6d23)] org.apache.activemq.artemis.core.server  : AMQ222165: No Dead Letter Address configured for queue someQueue in AddressSettings
2018-03-29 08:10:29.929  WARN 4080 --- [mpl$5@7cfd6d23)] org.apache.activemq.artemis.core.server  : AMQ222166: No Expiry Address configured for queue someQueue in AddressSettings
```

**Comment by graben** [comment]
How to reproduce:
[usecase.zip](https://github.com/spring-projects/spring-boot/files/1859847/usecase.zip)

**Comment by graben** [comment]
I'm trying to pull a PR during /after Easter holidays.

**Comment by snicoll** [comment]
Thanks for the sample, I hadn't realized this was happening out of the box. This is weird that Artemis doesn't do that: perhaps we're misconfiguring it or there is something in Artemis that can be changed to improve the OOB experience.

**Comment by graben** [comment]
Well, the patch seems to be quite easy, actually four lines of code.

`
AddressSettings adr = new AddressSettings();
adr.setDeadLetterAddress(new SimpleString("DLQ"));
adr.setExpiryAddress(new SimpleString("ExpiryQueue"));
configuration.addAddressesSetting("#", adr);
`

**Comment by snicoll** [comment]
@graben I wonder why Artemis doesn't do that itself when it's embedded like that. IMO it's worth reporting to them. I'll take  care of that once I handle the issue

**Comment by graben** [comment]
@snicoll Good question maybe be cause address settings could be complex and highly individual. I finish the patch and do PR after testing a bit. OK?

**Comment by snicoll** [comment]
> address settings could be complex and highly individual

Your patch isn't and I don't think that's a concern when embedding the broker (to be clear, I meant Artemis could do this automatically in embedded mode).

> I finish the patch and do PR after testing a bit. OK?

Sure thing, thank you!

**Comment by graben** [comment]
I'm actually looking into Artemis code. It seems they normally still expects configuration files. That might be the cause why AddressSettings are empty by default in embedded broker.

**Comment by snicoll** [comment]
Closing in favour of #12680
