### ISSUE TITLE
Parsing unicode escapes in OriginTrackedPropertiesLoader is broken

### ISSUE THREAD

**Issue by komu** [spring-projects/spring-boot#12671]
`OriginTrackedPropertiesLoader` tries to parse `\uXXXX`-unicode escapes, but the parsing is broken, resulting garbled data:

https://github.com/spring-projects/spring-boot/blob/9dea19d83c07abfec16935759008b4559148676b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/OriginTrackedPropertiesLoader.java#L226-L235

Clearly `digit > -'0'` should be `digit >= '0'` and similarly for the other two branches.

**Comment by komu** [comment]
If I can get my fork to build cleanly without hassles, I'll add some tests to the PR.

**Comment by wilkinsona** [comment]
Thanks very much, @komu. I'll close this one in favour of #12672.
