### ISSUE TITLE
Upgrade maven invoker in spring-boot-samples-invoker

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12687]
The `cloneProjectsTo` issue is [fixed](https://issues.apache.org/jira/browse/MINVOKER-224) so when  3.1.0 is released we can remove the work-around.

**Comment by davidhgray** [comment]
what does "status: blocked" mean?  is it ok to commit and create pull requests for blocked issues?

**Comment by wilkinsona** [comment]
> what does "status: blocked" mean?

It means that no progress can be made on the issue due to something that's out of our control. In this case, we're waiting for Maven Invoker Plugin 3.0.2 to be released.

> is it ok to commit and create pull requests for blocked issues?

That will only be possible if the issue's actually no longer blocked and we haven't noticed and haven't removed the label.
