### ISSUE TITLE
Configuration for jackson to ignore unknown properties by default

### ISSUE THREAD

**Issue by leocwolter** [spring-projects/spring-boot#12684]
I would like to avoid adding the annotation `@JsonIgnoreProperties(ignoreUnknown = true)` on every class, is it possible to add a configuration for that purpose?

I was thinking of something like:

```
spring.jackson.default-property-ignore=ignore_unknown
```

**Comment by philwebb** [comment]
@leocwolter Can you use a `Jackson2ObjectMapperBuilderCustomizer` bean and call `mixIn(Object.class, MixinAnnotations.class`) to do this?

**Comment by philwebb** [comment]
Oh wait. I misread your initial comment. I think we set `ignoreUnknown` for unknown properties by default. Can you share a sample that shows what you're trying to do?

**Comment by philwebb** [comment]
See #1237. We do have `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` defaulting to `false` already.

**Comment by agogs** [comment]
You can use` spring.jackson.deserialization.fail-on-unknown-properties=false`

**Comment by vfonic** [comment]
@agogs does this ignore unknown properties or lets them through? I don't want the user to be able to submit whatever he wants. I want to explicitly accept only the properties I allow and ignore anything else. Is that possible?

**Comment by snicoll** [comment]
@vfonic please ask questions on StackOverflow.

**Comment by wilkinsona** [comment]
Prior to Hibernate 6 (which is not yet supported), I don't think Hibernate uses Jackson. To double-check, I prepped Hibernate's 5.6.9 tag and found no occurrences of `jackson`.

If you think there's something that Spring Boot should be configuring with the main `ObjectMapper`, please open a new issue and we can take a look. We'll need to know exactly where that `ObjectMapper` is being used. A small sample that reproduces the problem you're facing is the ideal way to show us.

**Comment by jlous** [comment]
Ok. I just saw a way of making hibernate use spring's objectmapper (https://stackoverflow.com/questions/66656772/use-jackson-objectmapper-configured-by-spring-boot-in-hibernate) so I assumed it used a similar one by default.

**Comment by wilkinsona** [comment]
The person who asked that question is using [Hibernate Types](https://github.com/vladmihalcea/hibernate-types), a library that builds on top of Hibernate. Boot knows nothing about it so it isn't something that we can configure automatically.
