### ISSUE TITLE
Difficulty to override "server.port" 

### ISSUE THREAD

**Issue by japonicius** [spring-projects/spring-boot#12690]
Just upgraded to `org.springframework.boot:spring-boot:2.0.0.RELEASE` and my bootRun server.port override stopped working. I've tried the command line as well `-Dserver.port=8989` but nothing I've done took effect.
```
bootRun {
    systemProperty('server.port', runPortNumber)
}
```

Thank you very much for your time!

**Comment by philwebb** [comment]
Can you please share a sample that shows the problem?

**Comment by japonicius** [comment]
My apologies, the issues was happened because I didn't manually import `org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration` on my configuration class, so my `bootRun` task wasn't been able to override the default server port.

I used the sample method that prints out all initialized beans to debug it!
```
    @Bean
    public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
        return args -> {
            System.out.println("Let's inspect the beans provided by Spring Boot:");

            String[] beanNames = ctx.getBeanDefinitionNames();
            Arrays.sort(beanNames);
            for (String beanName : beanNames) {
                System.out.println(beanName);
            }
        };
    }
```

Thank you @philwebb for checking it out!
