### ISSUE TITLE
No value present

### ISSUE THREAD

**Issue by Mahdihp** [spring-projects/spring-boot#12706]
`java.util.NoSuchElementException: No value present`
Not used Multi repository class in Controller

`@Autowired
    CommandRepository commandRepository;
    @Autowired
    UserDeviceRepository userDeviceRepository;`

im using Spring boot 2.0

**Comment by wilkinsona** [comment]
There’s nowhere near enough information here to diagnose the problem. If you would like us to spend time trying to help you, please spend some time describing the problem in the form of a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
