### ISSUE TITLE
Support for custom PropertyResolver for the ResourceBanner

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#12703]
Currently the resource banner has 4 Property Resolvers:

* The `Environment`
* The version resolver
* The ansi resolver
* The title resolver

As an author of Spring Boot starters I would like to provide a way to the users to use our custom properties in there. Custom in the sense the version of the library that they are using. Something like the Spring Boot version.

Is this something that is interesting to the Spring Boot team?

**Comment by wilkinsona** [comment]
Isn’t the environment sufficient? You could add your custom properties to it using an environment post-processor.

**Comment by filiphr** [comment]
That would work yes. Although that means that the user can override the property, or if I put the custom properties first they would always take precedence?

**Comment by snicoll** [comment]
@filiphr that happens regardless of us providing the feature you're asking. `EnvironmentPostProcessor` allows you to add a custom `PropertySource` anywhere. If you want that content to take precedence over X, put it before X. As I believe, `EnvironmentPostProcessor` is the way to go, I am going to close this issue. If you have more question, please join us on Gitter or ask on StackOverflow.
