### ISSUE TITLE
@Transactional cannot rollback the change in MySQL

### ISSUE THREAD

**Issue by SkyeBeFreeman** [spring-projects/spring-boot#12709]
I wrote a simple program that i want to see the result of transaction rollback like this:
```
@Transactional
public void insertTwo() throws Exception {
    girlRepository.save(new Girl(18, "B"));
    girlRepository.save(new Girl(18, "A"));
    throw new RuntimeException("e");
}
```
but there were still two new record what I added into MySQL database. It showed that the rollback happened in the spring-boot application but not in MySQL. The version of spring-boot is 2.0.0, btw. But then I tested with the h2 database. The rollback worked in h2 database. Then I tested when the version of spring-boot is 1.5.2 and used MySQL. The rollback worked in MySQL, too. I want to know why I used the same code but got diffrent answer.

**Comment by geo-m** [comment]
Try 
`@Transactional(rollbackOn = {Exception.class})`

And put the annotation on a `@Service` class method

**Comment by SkyeBeFreeman** [comment]
@geo-m still cannot rollback the new record in MySQL.
And it is "rollbackFor", not "rollbackOn", in spring-boot 2.0, btw : )

**Comment by geo-m** [comment]
>And it is "rollbackFor", not "rollbackOn", in spring-boot 2.0, btw : )
Using javax.transaction. Doubt it had anything to do with it working though, sorry

**Comment by SkyeBeFreeman** [comment]
@geo-m I tried javax.transaction annotation but it still cannot work : (

**Comment by murilolocatelli** [comment]
@SkyeBeFreeman Did you discover the problem? I had same problem when I updated spring boot to 2.0.0

**Comment by SkyeBeFreeman** [comment]
@murilolocatelli did you config the engine of mysql as InnoDB?

**Comment by murilolocatelli** [comment]
@SkyeBeFreeman yes, I am using InnoDB.

**Comment by Anky723** [comment]
@SkyeBeFreeman I have tried the above solution but it not working(Using 2.0.0 and MySQL5InnoDBDialect). I am trying to save data in multiple tables one by one. If any save fails the previous save is not rolled back.

**Comment by hoangld17** [comment]
I have tried all solution above, but I still fail!
