### ISSUE TITLE
Websockets with Webflux and Basic Authentication: Does not work together?

### ISSUE THREAD

**Issue by bollywood-coder** [spring-projects/spring-boot#12701]
**Problem Statement**
Spring does not authenticate the websocket handshake with spring security turned on.

**Dependencies**
- Spring Boot 2.0.0
- Spring Security 5.0.3
- Spring WebFlux 5.0.4

**Stackoverflow**
Please see my [stackoverflow](https://stackoverflow.com/questions/49545305/spring-webflux-websocket-security-basic-authentication) question for clarification with code.

**Bug or Feature?**
I have no idea if this is the indented behaviour or bug. If its intended behaviour I would eager to know how to configure it right. I have searched the [webflux docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-web-security) but could not find anything or elsewhere in the Internet.

**Minimum Working Example**
If you need a minimum working ready example on Github please let me know.

Thanks
Rene

**Comment by philwebb** [comment]
@bollywood-coder I'd certainly recommend adding a sample to your stack-overflow question. You're much more likely to get help if you do.

I'm not sure this is a Spring Boot issue (unless we're not configuring something correctly). It seems more likely that you've hit a limitation of WebFlux or Spring Security. I'll close this issue and we can keep the conversation on stackoverflow until we know if this is a bug or not and where it should be raised.

/cc @rstoyanchev @rwinch in case they've seen this before.

**Comment by rwinch** [comment]
There isn't support for WebSocket + WebFlux support yet. I created https://github.com/spring-projects/spring-security/issues/5188 to track this
