### ISSUE TITLE
Make embedded launch script usable for cygwin environment

### ISSUE THREAD

**Issue by graben** [spring-projects/spring-boot#12704]
It would be nice if developers can run/test executable jar files even on windows machines using cygwin. Many other vendors do support cygwin in there unix shell scripts for handling java applications.

**Comment by wilkinsona** [comment]
Does Cygwin support Sysvinit and/or Systemd? The benefit would be limited if it does not. Also, if changes are required to support Cygwin, testing an executable jar using Cygwin will be of limited value if it’s ultimately going to be used in another environment as the testing will only verify it works with Cygwin.

**Comment by graben** [comment]
Cygwin does support sysvinit. The change in the script should only affect the handling of path variables. It's just a kind of unix derivate.

**Comment by wilkinsona** [comment]
Thanks, @graben. No one on the Boot team is a Windows user so we're not best-placed to see what fixing this would require. Do you know what changes to the launch script would be necessary to make it compatible with Cygwin?

**Comment by graben** [comment]
My quick&dirty patch for testing was:
```
-arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar "$jarfile" $RUN_ARGS "$@")
+arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar `cygpath -w "$jarfile"` $RUN_ARGS "$@")
```
Such snippets has to be put around all variables considering files/paths.
Use `uname` command to find unix derivates if needed more specifix stuff:
e.g.
* CYGWIN*
* Darwin*
* Linux
* SunOS*

**Comment by wilkinsona** [comment]
Thanks. I'm not too keen on the added complexity of detecting Cygwin and calling `cygpath` if necessary. I would imagine that the use of the launch script on Windows using Cygwin is something of a niche and I'm not sure we can justify the additional, hard-to-test complexity. My feeling is that using your own custom launch script that meets your needs is the way to go here. Let's see what the rest of the team thinks.

**Comment by philwebb** [comment]
I'm going to agree with Andy on this one. The custom script will allow you to do what you need and I don't think we can justify the added build complexity we'd need to have confidence in the feature if we added it.
