### ISSUE TITLE
spring-boot2.0.0属性文件（.properties）中文乱码

### ISSUE THREAD

**Issue by leewill1120** [spring-projects/spring-boot#12716]
![image](https://user-images.githubusercontent.com/16256642/38191496-938c14b0-369b-11e8-8805-0cf7380703e5.png)

OriginTrackedPropertiesLoader.readUnicode()函数：
字符判断条件中有错误，前面多了一个负号 "-"
digit > -'0' && digit <= '9' 
digit > -'a' && digit <= 'f' 
digit > -'A' && digit <= 'F' 
导致unicode字符转换异常

**Comment by philwebb** [comment]
Google Translate:

OriginTrackedPropertiesLoader.readUnicode() function:
There is an error in the character judgment condition, preceded by a minus sign "-"
Digit > -'0' && digit <= '9'
Digit > -'a' && digit <= 'f'
Digit > -'A' && digit <= 'F'
Causes unicode character conversion exception

**Comment by philwebb** [comment]
Thanks for the report.

**Comment by philwebb** [comment]
See also #12671
