### ISSUE TITLE
Bean not being registered when declared in a superclass

### ISSUE THREAD

**Issue by ruifigueira** [spring-projects/spring-boot#12726]
While working on Spring Boot 2 support for [Togglz](https://github.com/togglz/togglz/pull/271), I found a weird situation that only occurs when all the following conditions are true:

* `@Bean` is declared in a non-`@Configuration` superclass
* There are at least two `@Configuration` classes that extend that superclass
* Those classes do not "re-declare" the bean (they don't override the method and re-expose it again as `@Bean`)
* To prevent the same bean from being declared twice, each subclass is annotated with exclusive `@Conditional` (that is, one and only of the configurations is loaded) and that condition must be processed in the `ConfigurationPhase.REGISTER_BEAN` phase

In these cases, one of the `@Configuration` classes will successfully load the bean when activated, but the other won't.

To make it clear, the following JUnit tests reflect this:

* `FooBarConfiguration` and `FooBarMissingConfiguration` both are subclasses of `FooBaseConfiguration`
* `FooBarConfiguration` is active when `Bar` bean is declared, `FooBarMissingConfiguration` is active when the same bean is missing
* `FooBaseConfiguration` declares a `Foo` bean
* When testing both scenarios (`Bar` existing and missing), one of them fails, which means that `Foo` was only loaded for one of the subclasses of `FooBaseConfiguration`
* I also added another test, where I explicitly override the `Foo` bean method in a `FooBaseConfiguration` subclass, and it also works properly

```java
package com.example.demo;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.*;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;

public class ConfigurationInheritanceTest {

  public static class Bar { }

  public static class BarConfiguration {
    @Bean
    public Bar bar() {
      return new Bar();
    }
  }

  public static class Foo {
    public String name;

    public Foo(String name) {
      this.name = name;
    }
  }

  public abstract static class FooBaseConfiguration {
    @Bean
    public Foo foo() {
      return new Foo(name());
    }
    protected abstract String name();
  }

  @Configuration
  @ConditionalOnBean(Bar.class)
  public static class FooBarConfiguration extends FooBaseConfiguration {
    @Override
    protected String name() {
      return "bar";
    }

  }

  @Configuration
  @ConditionalOnMissingBean(Bar.class)
  public static class FooBarMissingConfiguration extends FooBaseConfiguration {
    @Override
    protected String name() {
      return "no-bar";
    }
  }

  @Configuration
  @ConditionalOnMissingBean(Bar.class)
  public static class FooBarMissingOverridenBeanConfiguration extends FooBaseConfiguration {
    @Override
    protected String name() {
      return "no-bar-overriden-bean";
    }

    @Bean @Override
    public Foo foo() {
      return super.foo();
    }
  }

  @Test
  public void testInheritanceFooBar() {
    ApplicationContext context = load(BarConfiguration.class, FooBarConfiguration.class, FooBarMissingConfiguration.class);
    Foo foo = context.getBean(Foo.class);
    assertThat(foo).isNotNull();
    assertThat(foo.name).isEqualTo("bar");
  }

  @Test
  public void testInheritanceFooBarMissing() {
    ApplicationContext context = load(FooBarConfiguration.class, FooBarMissingConfiguration.class);
    Foo foo = context.getBean(Foo.class);
    assertThat(foo).isNotNull();
    assertThat(foo.name).isEqualTo("no-foobar");
  }

  @Test
  public void testInheritanceFooBarMissingOverridenBean() {
    ApplicationContext context = load(FooBarConfiguration.class, FooBarMissingOverridenBeanConfiguration.class);
    Foo foo = context.getBean(Foo.class);
    assertThat(foo).isNotNull();
    assertThat(foo.name).isEqualTo("no-bar-overriden-bean");
  }

  protected ApplicationContext load(Class<?>... confs) {
    AnnotationConfigWebApplicationContext context = new AnnotationConfigWebApplicationContext();
    context.register(confs);
    context.refresh();
    return context;
  }
}
```
I was able to track down the problem back to the `knownSuperclasses` map in [ConfigurationClassParser](https://github.com/spring-projects/spring-framework/blob/v5.0.4.RELEASE/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java#L323). It doesn't enter into that `if` body for the second subclass because `knownSuperclasses` already has the `FooBaseConfiguration` class from parsing the first class.

I'm opening the ticket here because this seems to be related with Spring Boot `@Conditional` annotations (more specifically, the ones that run in `ConfigurationPhase.REGISTER_BEAN` phase).

I also based my implementation on `JpaBaseConfiguration` and I suspect that you haven't experience the problem yourselves because there is only one implementation for it, which is `HibernateJpaConfiguration`.

**Comment by wilkinsona** [comment]
Thanks for the very detailed report. This is a known issue with Spring Framework. It’s being tracked by [SPR-16217](https://jira.spring.io/browse/SPR-16217).
