### ISSUE TITLE
Add Log4J2 configuration instructions for Gradle-based projects

### ISSUE THREAD

**Issue by behrangs-sportsbet** [spring-projects/spring-boot#12729]
Looks like Log4J2 configuration instructions for Gradle-based projects is not given in the [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html).

I usually exclude `spring-boot-starter-logging` from all my configurations using this code snippet:

```groovy
configurations {
    all {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}
```
and then explicitly add a dependency on `org.springframework.boot:spring-boot-starter-log4j2` to switch to Log4J2.

The docs should be updated with instructions outlining these steps.

I can create a PR with the changes, but is this the recommended approach to setup Spring Boot with Log4J2 in a Gradle-based project?

**Comment by snicoll** [comment]
@behrangs-sportsbet there is [a dedicated section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-log4j-for-logging) but, granted, only covers Maven. I am not entirely sure that what you've described is the recommended way with Gradle but I am sure @wilkinsona knows.

**Comment by wilkinsona** [comment]
I don't think there is a recommended way to do this with Gradle. There's more than one way to do it and which one is best is, largely, down to personal preference. That said, the approach shown above is probably the most robust way to do it so is probably the right one to document. Anyone who knows Gradle well enough to have a different preference will also know how to configure it.

**Comment by behrangs-sportsbet** [comment]
@wilkinsona will create a PR later today to amend the docs with the instructions.
