### ISSUE TITLE
Embedded Jetty Server failing due to missing ServletWebServerFactory bean

### ISSUE THREAD

**Issue by karlnicholas** [spring-projects/spring-boot#12749]
Bug report

Cannot create and start a simple spring-boot app using Jetty. I get the error:

> Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.

Using:

    @SpringBootApplication
    public class SdrhalApplication {
        public static void main(String[] args) {
            SpringApplication.run(SdrhalApplication.class, args);
        }
    }

and

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <artifactId>sdrhal</artifactId>
        <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>2.0.0.RELEASE</version>
        </parent>
        <dependencies>
            
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-tomcat</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-jetty</artifactId>
            </dependency>
        </dependencies>
    </project>

**Comment by bclozel** [comment]
How are you running your Spring Boot application (from the IDE, executable JAR, deploying as a WAR...)?
Why is your maven build not using the `spring-boot-maven-plugin` to package your application?

This might be an issue in your build configuration - does the same happen when you start with a project created with start.spring.io?

We do have integration tests covering that case, so there might be more to it.
Please create a [minimal, complete, verifiable example project](https://stackoverflow.com/help/mcve) we can take a look at.

**Comment by mbhave** [comment]
We have a [Jetty Sample](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-jetty/pom.xml) that works fine. It's hard to tell what's going on with your application. Please provide a simple, minimalistic sample that we can use to reproduce the issue.

**Comment by wilkinsona** [comment]
I'd guess that Maven corrupted one or more of Jetty's jars when it downloaded them. Deleting Jetty from the local Maven cache and rebuilding would confirm if that's the case.
