### ISSUE TITLE
Metrics from binders missing in CompositeMeterRegistry

### ISSUE THREAD

**Issue by pbetkier** [spring-projects/spring-boot#12743]
The following code behaves differently depending on whether you register a single or multiple instances of `MeterRegistry` in Spring context.

```java
@Component
class Test {
    Test(MeterRegistry registry) {
        if (registry.find("jvm.classes.loaded").gauge() != null) {
            // one MeterRegistry in context
        } else {
            // two or more MeterRegistry in context, forming a CompositeMeterRegistry
        }
    }
}
```

That's because meter binders, one of which registers `jvm.classes.loaded` gauge, bind to all meter registries except to `CompositeMeterRegistry`. So if you register multiple `MeterRegistry` beans, then each one will have the gauge, but the composite that gets injected does not.

Application code should not depend on such configuration detail as how many meter registries are configured. I also want to avoid writing `instanceof` conditions like in [collecting meter names in MetricsEndpoint](https://github.com/spring-projects/spring-boot/blob/6c61cbf5f76fda234c5c466cc1f6631b16860ecc/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/MetricsEndpoint.java#L67).

There used to be always a `CompositeMeterRegistry` in context, I understand that it was important to remove the overhead and create such registry only when necessary. But then I suggest `CompositeMeterRegistry` methods to delegate and merge results from all the underlying registries, e.g. `find` to search in all the registries. Having to use `instanceof` and manually iterate over underlying registries kind of kills the whole idea of the composite pattern.

What do you think?

**Comment by philwebb** [comment]
That feels like a bug `CompositeMeterRegistry` to me. I'd expect the composite not to have the gauge directly registered, but I would think that `find` should search the others and return the first. Hopefully @jkschneider can answer.

**Comment by jkschneider** [comment]
I think this is the [problem](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/MeterRegistryConfigurer.java#L62-L64).

**Comment by philwebb** [comment]
I think the initial reason for discarding `CompositeMeterRegistry` was the assumption that the composite itself wouldn't have state but would just be a view of other registries. A simple example of the type pattern from the framework is `org.springframework.util.CompositeIterator` (an `Iterator` composed of other `Iterators`).

The biggest problem that I can see with removing the `if` statement is it might make the customizers harder to use.

Thinking about some examples, what should happen with the following:

```java
MyRegistryOne one = ...
MyRegistryTwo two = ...
CompositeRegistry comp = new CompositeMeterRegistry(Arrays.asList(one,two));

gaugeA.register(one);
gaugeB.register(two);
gaugeC.register(comp);
```

I would probably expect `MyRegistryOne` to have `gaugeA` and `gaugeC` and `MyRegistryTwo` to have `gaugeB` and `gaugeC`. I'd also expect that calling `find` on `CompositeMeterRegistry` would work for `A`, `B` & `C`.

**Comment by jkschneider** [comment]
I don't think we can have composites searching for meters on their children. Searching on the composite effectively returns what was registered against the composite (which you can then assume will be on the children as well). 

After all, child meter registries may contain the same meter but incrementing at different rates.

![image](https://user-images.githubusercontent.com/1697736/38282499-0bb5f138-3776-11e8-9a45-6c1480114904.png)

This example is contrived of course, since the different streams would each be adding additional tags to `spring.integration.send` to make them distinct, but hopefully the idea is clear enough,

**Comment by jkschneider** [comment]
> I can see with removing the if statement is it might make the customizers harder to use.

I don't imagine the use of customizers changes at all. What problems do you see?

**Comment by philwebb** [comment]
Just that you need to be aware that `Customizer<MeterRegistrySubclass>` won't apply to the composite.

**Comment by jkschneider** [comment]
That hasn't changed though right?

**Comment by philwebb** [comment]
I guess not, my understanding was just wrong about the initial implementation.

**Comment by philwebb** [comment]
Closing in favor of PR #12762
