### ISSUE TITLE
Please update spring-boot-dependencies' HikariCP version

### ISSUE THREAD

**Issue by matsumana** [spring-projects/spring-boot#12759]
Spring Boot 2.0.0 depends on HikariCP 2.7.8 but there is a issue in HikariCP so we can't collect metrics for now.
The issue has been fixed in HikariCP 3.0.0
Please update spring-boot-dependencies' HikariCP version.

ref:
- [brettwooldridge/HikariCP - CHANGES](https://github.com/brettwooldridge/HikariCP/blob/a11d6a6b399b330218a0c3c9be586b28c4af23dc/CHANGES#L3-L32)

- https://github.com/brettwooldridge/HikariCP/pull/1108

**Comment by wilkinsona** [comment]
Thanks, but we can't upgrade to a new major version of Hikari in a maintenance version of Spring Boot. You can override the `hikaricp.version` property if you want to use a version other than the one provided by Boot. Hopefully there will be a Hikari 2.7.9 release that incorporates the fix. If there is, we will upgrade to it in due course.

/cc @brettwooldridge

**Comment by rajadilipkolli** [comment]
@wilkinsona Will this be upgraded to 3.0.0 when Spring boot 2.1 is released?

**Comment by philwebb** [comment]
@rajadileepkolli we'll upgrade to whatever the latest version of Hikari is at the time of the 2.1 release.

**Comment by brettwooldridge** [comment]
@wilkinsona @philwebb @rajadilipkolli @matsumana I have published a v2.7.9 artifact with only the Micrometer v1.0.0 changes that were included in v3.0.0 merged.

**Comment by philwebb** [comment]
Oh sweet. Thanks @brettwooldridge
