### ISSUE TITLE
RequestParam "required" attribute: If the attribute is removed, the parameter is still required.

### ISSUE THREAD

**Issue by elyograg** [spring-projects/spring-boot#12763]
I had incorrectly included `required=true` on `RequestParam` in a method for handling requests.  This caused some of my tests to fail.  So I completely removed the 'required' attribute from the appropriate parameters, and tried to build it again.  Tests continued to fail, indicating that the parameter I had "fixed" was required and wasn't present.  I verified several times that I was using the "gradlew clean" command, and that it was removing all of the class files on each build attempt.

To fix the problem, I had to re-add the attribute and explicitly set it to false.

Best guess is that somehow the spring infrastructure has information about my method signatures cached somewhere, and that removing the required attribute from the method did NOT update that cached information.

It's possible that this issue should be opened somewhere other than spring-boot, but if so, I do not know where.  I am using Spring Boot 2.0.0 for this project.

**Comment by philwebb** [comment]
The `@RequestParam` annotation is part of Spring Framework. Their issue tracker [is here](https://jira.spring.io/browse/SPR/) but I believe what you're describing is intentional.

From the Javadoc:

> Whether the parameter is required.
> Defaults to `true`, leading to an exception being thrown if the parameter is missing in the request. Switch this to `false` if you prefer a `null` value if the parameter is not present in the request.

**Comment by elyograg** [comment]
Sorry about the noise!  And thank you for the help discovering my error.

I didn't know the default was true.  Up until now I had been pulling parameters out of the HttpServletRequest on this particular method, and decided it was time to be a little more up to date.  I didn't consult any documentation, I just went with the understanding I already had from using RequestParam in other places.
