### ISSUE TITLE
Upgrade maven enforcer plugin to 3.0.0

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12769]
It's not released yet and we're currently on M1. I don't think we can downgrade at this point so we'll probably need to keep on the milestone :(

**Comment by dreis2211** [comment]
I guess this can be closed given that we're on Gradle now. There is only the dependency management left for it and no actual goal/configuration.

**Comment by snicoll** [comment]
Correct, thanks again @dreis2211!

**Comment by snicoll** [comment]
We can upgrade the build in `2.2.x` still but that should happen automatically via bomr.
