### ISSUE TITLE
Selecting any branch other than master results in 404

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#12768]
https://github.com/spring-projects/spring-boot/tree/1.5.x/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin

Selecting any branch other than `master` results in 404. Where may I find the previous versions?

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-boot/tree/1.5.x/spring-boot-tools/spring-boot-gradle-plugin

**Comment by asarkar** [comment]
Looks like a path segment `spring-boot-project` has been introduced in 2.0
