### ISSUE TITLE
Devtools restarts twice on Kotlin changes in IntelliJ IDEA

### ISSUE THREAD

**Issue by sgrimm-sg** [spring-projects/spring-boot#12760]
Environment:

Spring Boot 2.0.0.RELEASE with spring-boot-devtools
IntelliJ IDEA 2017.3
Kotlin 1.2.30
OS X 10.13.3

When I recompile a Kotlin source file from IntelliJ (using either the "Build Module" or "Recompile" menu items) my Spring Boot application restarts twice.

Setting a breakpoint in the `Restarter` class, I believe I see what the problem is: IntelliJ first removes the existing `.class` file, then runs the compiler which eventually writes the new `.class` file. The classpath watcher in Devtools sees the deletion and fires a `ClassPathChangedEvent` which triggers a restart. The restart happens quickly enough that the application starts up without the class in question. Then Devtools sees the class appear and triggers another restart.

**Comment by wilkinsona** [comment]
Unfortunately, there's nothing we can do about IDEA's behaviour. You should be able to avoid the problem by increasing the quiet period (time without any changes) that's required before a restart is triggered:

```
spring.devtools.restart.quiet-period=1000
```

**Comment by sgrimm-sg** [comment]
Thanks, that'll do the trick. Is the `quiet-period` setting documented anywhere? I looked for a setting like that before filing this issue, but didn't see it in the Spring Boot reference manual.

**Comment by wilkinsona** [comment]
Yes, it's listed in the [appendix](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties) where it says:

```
spring.devtools.restart.quiet-period=400ms # Amount of quiet time required without any classpath changes before a restart is triggered.
```
