### ISSUE TITLE
LogbackLoggingSystem always fails in getLoggerContext()

### ISSUE THREAD

**Issue by cradloff** [spring-projects/spring-boot#12777]
In method `getLoggerContext()` an `ILoggerFactory` is retrieved from `org.slf4j.impl.StaticLoggerBinder`. StaticLoggerBinder always returns an instance of `org.slf4j.impl.SimpleLoggerFactory`. This factory is then checked to be an instance of `ch.qos.logback.classic.LoggerContext` which always fails.

Spring Boot fails with the following message:

> java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from slf4j-simple-1.7.21.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory

Spring Boot Version: 1.5.9.RELEASE

**Comment by wilkinsona** [comment]
The message tells you what you need to do:

> remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from slf4j-simple-1.7.21.jar

**Comment by cradloff** [comment]
You're right, we had to replace slf4j-simple with logback-classic.

Thank you.
