### ISSUE TITLE
Table column SCHED_NAME is filled with scheduler bean name instead of property instanceName

### ISSUE THREAD

**Issue by instanceName** [spring-projects/spring-boot#12781]
Artifact: [spring-boot-starter-quartz](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-quartz/2.0.0.RELEASE)
Version: 2.0.0.RELEASE
Property: spring.quartz.properties.org.quartz.scheduler.instanceName
Tables: all quartz database tables
Column: SCHED_NAME
Project setup: database datasource, one trigger, one job, auto configured scheduler with bean name "quartzScheduler"
Actual value: scheduler bean name
Expected value: value of the property instanceName
Issue: table column SCHED_NAME is filled with scheduler bean name instead of property instanceName

**Comment by bclozel** [comment]
Could you completely rewrite this issue to:
* explain what you're trying to achieve
* give [a sample project that shows how you've tried to do it](https://stackoverflow.com/help/mcve) (something that we can git clone or download)
* explain the expected result and what you got instead

When we've come to the conclusion that this is a Spring Boot issue, then we can discuss the possible solutions to this problem.

Thanks!
