### ISSUE TITLE
When deployed as a war, a RuntimeException from a rest controller results in an HTML response rather than JSON

### ISSUE THREAD

**Issue by Javatar81** [spring-projects/spring-boot#12787]
After updating from Spring Boot 2.0.0.RELEASE to 2.0.1.RELEASE the default error handling for RuntimeExceptions in RestControllers behaves differently. In 2.0.0 they were returned as Json error objects whereas in 2.0.1. they are returned as plain text/html. This effect does not occur in standalone environment but when running a Spring boot application on Tomcat 8. 

Tomcat behaves like this when the Content-Type has not been set (defaults to text/html) in Servlet response. Maybe this is a bug in the default error handler Spring boot is using.

**Comment by wilkinsona** [comment]
I wonder if the fix for https://github.com/spring-projects/spring-boot/issues/11814 has caused this. Can you please provide a minimal application and details of the Tomcat configuration that are needed to reproduce the problem?

**Comment by Javatar81** [comment]
I've created a minimal application on Github which demonstrates the issue. Please follow the instructions in the readme. You will need Docker installed on your machine. 

https://github.com/Javatar81/spring-boot-examples/tree/master/spring-boot-error-handling

**Comment by wilkinsona** [comment]
Thanks for the sample. As I suspected, this appears to be a regression caused by the fix for #11814.

**Comment by Javatar81** [comment]
Will this fix also be part of Milestone 2.0.2?

**Comment by philwebb** [comment]
@Javatar81 Yes, we always forward merge the `1.5.x` branch to `2.0.x` so anything in 1.5.12 will also be in 2.0.2. In this case the merge commit is 8b1a101cb6082f8c1b96c96ab7943d568d23281d.
