### ISSUE TITLE
LogbackLoggingSystem fails to call clear on the `statusList` in `stopAndReset`

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-boot#12785]
Running on SpringBoot 1.3.3 (but this also exists in master), we have noticed that several of our services would get in a bad state after a refresh. This is related to #5669.

Due to a race condition in Logback when doing a Spring Cloud refresh, Logback would record an error and add it to the `statusList`. As part of the refresh, SpringBoot checks if logback reloaded properly by checking the status list. However if there are ever any errors, then SpringBoot throws an exception. That behavior is OK when the error occurs, but Spring also needs to call `clear()` on that list so that subsequent checks can succeed.

What we see is a server will get an error on reload, and then stays in a bad state because the previous failure never gets cleared.

Here is the line where the check happens:
https://github.com/spring-projects/spring-boot/blob/7d5e41f7dcb5a6edddfcd6742049342fb23c0000/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L164

I think the clear needs to occur in `stopAndReset`

**Comment by wilkinsona** [comment]
> but this also exists in master

Do you know that from seeing the problem on master, or purely by inspecting the code? I am asking as, since Spring Boot 1.4.4 (https://github.com/spring-projects/spring-boot/issues/7758), the errors have been cleared on clean up.

**Comment by checketts** [comment]
Sorry, just from inspecting the code. I have 2 services that routinely display this behavior and just upgraded one to SpringBoot 1.5.9 last week. I'll follow up with that team to see if the upgrade resolved it for them.

**Comment by checketts** [comment]
I just checked and they hadn't deployed the upgraded version to production yet. I've requested that they get that deployed and will follow up to see if they see stop seeing the errors. It might take a week for it to reoccur, but I'll update this ticket once I find out.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
