### ISSUE TITLE
Upgrade to Mockito 2.17+

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-boot#12789]
Mockito 2.17+ includes the MockitoExtension for JUnit5 (see: https://github.com/mockito/mockito/pull/1221), so please consider updating to this version.

Thanks!

Edit:
Mockito 2.18+ supports Java 11.

**Comment by clemstoquart** [comment]
Mockito 2.18.0 has been released https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md#2180

**Comment by PascalSchumacher** [comment]
I forgot to mention that the JUnit5 extension is in a separate module 'mockito-junit-jupiter', so maybe it is a good idea to add this to the dependency management?

**Comment by wilkinsona** [comment]
Closing in favour of #12890.
