### ISSUE TITLE
Add wait count (number of threads waiting for a connection) to DataSourcePoolMetadata and DataSourcePoolMetrics

### ISSUE THREAD

**Issue by lidkowiak** [spring-projects/spring-boot#12788]
Monitoring number of threads waiting for a connection to database is extremely helpful when diagnosing performance issue with relational database and tuning pool size.
I suggest adding wait count to DataSourcePoolMetadata and DataSourcePoolMetrics (eg. for org.apache.tomcat.jdbc.pool.DataSource::getWaitCount Tomcat JDBC pool).
![image](https://user-images.githubusercontent.com/7756916/38416894-99170748-3996-11e8-8b39-b26d7483c11d.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, I don't think we can add wait count to `DataSourcePoolMetadata` as it isn't  available for all three connections pools that we current support. It's available from Tomcat JDBC and Hikari. It's not, as far as I can tell, available from Commons DBCP 2. Perhaps I've missed something?

When using Hikari, the `hikaricp.connections.pending` metric already shows the number of threads that are waiting to get a connection.

**Comment by lidkowiak** [comment]
It is possible to retrieve wait count from https://commons.apache.org/proper/commons-dbcp/api-2.2.0/org/apache/commons/dbcp2/BasicDataSource.html#getConnectionPool(), but this method is protected.

**Comment by snicoll** [comment]
@lidkowiak I am not keen to add anything so specific in there. The purpose is to expose basic metadata that are common to each connection pool. The more specific we get, the more likely it is that a connection pool will not support that feature. 

There are dedicated connection pools metrics you can use for this. Hikari has a great coverage already.

**Comment by wilkinsona** [comment]
@lidkowiak Thanks for confirming that was can retrieve the number of waiting threads in a DBCP2 pool using public API. For that reason, I'm going to close this issue. I'd recommend that you stick with HikariCP (the default pool in Spring Boot 2.0) and the `hikaricp.connections.pending` that is provided out of the box.
