### ISSUE TITLE
Relaxed Binding section in documentation needs update

### ISSUE THREAD

**Issue by ranarula** [spring-projects/spring-boot#12782]
Table 24.1 in https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-relaxed-binding mentions incorrect use of prefixes for property names

Row 2 and 3 which are currently showing `acme.myProject.person.firstName`(camel case) and `acme.my_project.person.first_name`(snake case) should be `acme.my-project.person.first-name` and `acme.my-project.person.first-name` (kebab case) respectively based on the information in migration guide.

The table  also needs to be fixed in `2.0.1.RELEASE` and `current` version of the documentation. The `2.0.0.RELEASE` version of the document however has the correct info.

**Comment by mbhave** [comment]
@ranarula that was recently changed as part of #12750. Can you clarify the meaning of incorrect?

**Comment by snicoll** [comment]
@bclozel I wrote that and it is a misunderstanding on my end. Fixing the wiki now.

**Comment by snicoll** [comment]
@ranarula Thanks for reporting the issue. The migration guide has been updated as well to reflect what you should actually do. Prefixes in camel cases and snake cases are perfectly fine. Now that the two are in sync, I am closing this issue.
