### ISSUE TITLE
Option to change response of Actuators endpoint to XML format.

### ISSUE THREAD

**Issue by somnath157** [spring-projects/spring-boot#12792]
I want to use Spring Boot actuator to check my applications health status. it is working fine but the application is working on XML format so i wanted to change the response format of endpoints to XML but it is set to only return JSON format. i am having a big problem with that. so allow us to change response format.

**Comment by philwebb** [comment]
I wonder if adding `application/xml` to [this set](https://github.com/spring-projects/spring-boot/blob/2f5ab5036767db3d5eb2a0d51c6c11acb1155e21/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/WebEndpointAutoConfiguration.java#L68) would be enough. Obviously we'd also need tests.

**Comment by philwebb** [comment]
Good points @bclozel and they are making me think that adding actuator XML support might not be a good idea at all. @somnath157 Is there any reason why you can't use the existing JSON responses? Why do you need XML?

**Comment by wilkinsona** [comment]
FWIW, I am not in favour of supporting XML either. Beyond the issues that Brian's raised, we'd also pretty much double the amount of documentation that was required. Once we've provided XML, the next step would be a request for a schema. It's a slippery slope that we don't want to go down, IMO.

**Comment by philwebb** [comment]
Sorry @somnath157 but we don't think supporting XML for the actuator is a good idea. If you only want a health endpoint I'd suggest writing your own `@Controller` to expose what you need.
