### ISSUE TITLE
 springboot 2.0.1.RELEASE and hikaricp

### ISSUE THREAD

**Issue by amoswxz** [spring-projects/spring-boot#12797]
The `HikariDataSource` `dataSource` method in the `DataSourceConfiguration` class uses the annotation `@ConfigurationProperties(prefix = "spring.datasource.hikari")`
, but the annotation used by `DataSourceProperties` is `@ConfigurationProperties(prefix = "spring.datasource");`
If yml does not write `spring-datasource-url`, an error occurs. But `spring:datasource:hikari: jdbc-url` already provides url

**Comment by amoswxz** [comment]
![image](https://user-images.githubusercontent.com/34223541/38462200-41b64434-3b15-11e8-9d8d-3349951285c5.png)
![image](https://user-images.githubusercontent.com/34223541/38462204-48a6df2e-3b15-11e8-8a69-b2580af86a94.png)

**Comment by philwebb** [comment]
I'm not totally sure I'm understanding the issue as it's being reported. The `spring.datasource` properties are general purpose properties that apply to all datasource types. The `spring.datasource.hikari` properties are specific to Hikari.

If you specify `spring.datasource.url` in your yaml it should be applied to Hikari (see [this line of DataSourceBuilder](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DataSourceBuilder.java#L94)).

Can you please clarify the problem that you're seeing and ideally provide a small sample that replicates it?

**Comment by amoswxz** [comment]
Hikaricp provides the spring-datasource-jdbc-url, why use a spring-datasource-url, otherwise it will error
![image](https://user-images.githubusercontent.com/34223541/38463488-9f1b3814-3b2e-11e8-9c1f-db36402d2307.png) @philwebb

**Comment by philwebb** [comment]
I'm sorry. I'm still not following. What error are you seeing? Please provide a sample.

**Comment by amoswxz** [comment]
![image](https://user-images.githubusercontent.com/34223541/38463785-d2049b34-3b34-11e8-9f15-96d7500cdc31.png)
Do you think the url in the red box can be removed?
@philwebb

**Comment by amoswxz** [comment]
Sorry, I have expressed some problems。
Configure hikaricp in yaml:
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql:/xxxx/amos?autoReconnect=true&useSSL=false
      username:xxx
      password: xxx
      driver-class-name: com.mysql.jdbc.Driver
This configuration is wrong；Because of missing spring-datasource-url configuration

**Comment by bclozel** [comment]
Please share a minimal sample application that we can git clone or download, and that reproduces the issue you’re having. This is the most efficient way to move forward with this - more comments won’t really help I’m afraid.

Thanks!

**Comment by snicoll** [comment]
@amoswxz also, if that helps, `spring.datasource.hikari` are meant for advanced customizations of the pool. url, username/password, etc should be specified with `spring.datasource`. It looks like you are mixing the two (which you shouldn't). As Brian pointed out, we don't understand the problem you are reporting so please share a sample we can run that demonstrates it.

**Comment by amoswxz** [comment]
@snicoll I probably understand what you mean. Configure user name password, jdbc-url, should use spring-datasource, should not use spring-datasource-hikari to configure jdbc-url?

**Comment by snicoll** [comment]
If you are using the auto-configuration, then you should [read the related section in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connect-to-production-database) that states that,

> You should at least specify the URL by setting the spring.datasource.url property

The argument is that the standard options will still work even if you switch to a different connection pool. Your configuration above is incorrect as a central piece of the datasource is configured with a connection poll specific setting.

All in all, the connection-pool specific namespace is meant to configure advanced options. The url of the datasource is not an advanced option. There is no reason to start configuring things in two different places. If that's what you want, please create your own `DataSource` bean and do not use the auto-configuration.

**Comment by amoswxz** [comment]
thanks

**Comment by amoswxz** [comment]
What I don't understand is why this is the design. Spring-datasource-url already exists, why spring-datasource-hikaricp-url. Thank you @snicoll

**Comment by EmielSito** [comment]
> What I don't understand is why this is the design. Spring-datasource-url already exists, why spring-datasource-hikaricp-url


I'm not 100% sure but I believe it is because   Spring-datasource-url is the default usage.
and
if you use spring-datasource-hikaricp-url    it means you are going past the default usage and into advanced usage.     basically spring-datasource-hikaricp-url  will override Spring-datasource-url  because now you are configuring things yourself ( advanced mode) 

@snicoll   Thumbs up if this is the correct understanding ( in simple terms) ?

**Comment by snicoll** [comment]
It's a bit more complicated than that. `spring.datasource.hikari.*` is used to configure advanced settings of Hikari as you've mentioned and above all connection pool specific settings. 

`spring.datasource.*` is guaranteed to work with the connection pools that we support. So you set the url, password, etc there and depending on the supported connection pool on the classpath, we auto-configure it with that information.

Now the problem of the question @amoswxz was asking is that when we expose the settings for `HikariDataSource` we do expose the bean as a whole and we have no way to "remove" settings that are duplicate. It's a limitation and I agree it can be confusing.

**Comment by jianglin1008** [comment]
`@ConfigurationProperties(prefix = "spring.datasource.hikari")` working as expected?

**Comment by snicoll** [comment]
@jianglin1008 please ask questions on Stackoverflow.
