### ISSUE TITLE
Add gradle example in "How to customize dependency versions"

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12807]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions

**Comment by wilkinsona** [comment]
We already have an example in 1.5.x: https://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#howto-customize-dependency-versions.

In 2.0, the example's moved into the Gradle plugin's documentation: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#managing-dependencies-customizing

**Comment by philwebb** [comment]
Moving to 2.0.x so we can add a breadcrumb trail for people to find the Gradle section if they happen to start at the HowTo.

**Comment by rstoyanchev** [comment]
They appear to point to the same section (bookmark). What does "current" point to then? Also is the use of gradle.properties not recommended or preferred for some reason?
