### ISSUE TITLE
when i use jsp,i cant find error.jsp

### ISSUE THREAD

**Issue by wangzhihaolighter** [spring-projects/spring-boot#12802]
`pom.xml

```xml
<groupId>com.example.springframework.boot</groupId>
    <artifactId>jsp</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>jsp</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <!-- Compile -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- Provided -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

my project
![image](https://user-images.githubusercontent.com/27496404/38491173-b26e328c-3c1d-11e8-91d6-a906a04fc2ea.png)

my aplication.properties
```properties
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
```

when i use
``` java
return new ModelAndView("error");
```
i cant find WEB-INF/jsp/error.jsp
![image](https://user-images.githubusercontent.com/27496404/38491666-14534c5c-3c1f-11e8-9b08-b4490b321d8a.png)

when i use 
``` java
return new ModelAndView("/error");
```
i can find WEB-INF/jsp/error.jsp
![image](https://user-images.githubusercontent.com/27496404/38491536-b8479f30-3c1e-11e8-969f-d87d16e71b14.png)

in spring-boot source code `BasicErrorController` ,it use
```java
   @RequestMapping(
        produces = {"text/html"}
    )
    public ModelAndView errorHtml(HttpServletRequest request, HttpServletResponse response) {
        HttpStatus status = this.getStatus(request);
        Map<String, Object> model = Collections.unmodifiableMap(this.getErrorAttributes(request, this.isIncludeStackTrace(request, MediaType.TEXT_HTML)));
        response.setStatus(status.value());
        ModelAndView modelAndView = this.resolveErrorView(request, response, status, model);
        return modelAndView == null ? new ModelAndView("error", model) : modelAndView;
    }
```

i guess it is a problem

**Comment by wilkinsona** [comment]
Sorry, but it's not clear to me what the problem is from a few snippets of code? Can you please describe what you want to be able to do? Once we understand that, we'll be able to tell if your approach is wrong or if your approach is correct and you've found a bug.

**Comment by wangzhihaolighter** [comment]
when i use freemarker or thymeleaf,  make a request to an HTTP server
code throw any RuntimeException can be find templates/error.ftl or templates/error.html
application.properties don't have any configuration
but i use jsp ，i  create {src/main}/webapp/WEB-INF/jsp folder, application.properties  write
``` properties
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
```
i use this,can find WEB-INF/jsp/welcome.jsp
``` java
new ModelAndView("/welcome");
```
but i use this or throw any RuntimeException ,i cont find WEB-INF/jsp/error.jsp
```java
new ModelAndView("error");
```

**Comment by wilkinsona** [comment]
Both throwing a runtime exception and returning a `ModelAndView` pointing to `error` work for me with JSPs (I checked using a war file run with `java -jar`). If you'd like us to spend any more time investigating this, please spend some time producing a minimal example and step-by-step instructions that reproduce the behaviour you have described.

**Comment by wangzhihaolighter** [comment]
This is my learn demo project link[spring boot learn - jsp](https://github.com/wangzhihaolighter/spring-boot-learn/tree/master/02-web/jsp)
```basic
project folder
-src
  -main
    -java
    -resources
    -webapp
      -WEB-INF
        -jsp
          -error.jsp
          -error2.jsp
          -welcome.jsp
```

code
``` java
@GetMapping("/test/error")
    public String error() {
        //cant return error.jsp
        throw new RuntimeException("one error");
    }

    @GetMapping("/to/error")
    public ModelAndView toError() {
        //find WEB-INF/jsp/error.jsp
        //correct
        //return new ModelAndView("/error");

        //error
        //return new ModelAndView("error");

        //spring - BasicErrorController user new ModelAndView("error") cant find error.jsp

        //find WEB-INF/jsp/error2.jsp

        //correct
        //return new ModelAndView("error2");
        return new ModelAndView("/error2");
    }
```

so,i think BasicErrorController user new ModelAndView("error") error to find error.jsp

**Comment by wilkinsona** [comment]
Thanks, but that's not quite what I was looking for. I've been able to identify a problem, but I can't tell if it's the problem that you have as you haven't told me what steps to take to reproduce the problem you're seeing. Your sample still looks like an attempt to diagnose a problem rather than to simply reproduce it.

I've opened https://github.com/spring-projects/spring-boot/issues/12805 for the problem that I've been able to identify. Hopefully this is the same problem as you're seeing. If it's not, please provide the necessary information in this issue and we can re-open it and investigate further.
