### ISSUE TITLE
OOM exceptions and crashing since 2.0.1

### ISSUE THREAD

**Issue by jamespizzurro** [spring-projects/spring-boot#12804]
I just upgraded to 2.0.1-RELEASE from 2.0.0-RELEASE, and I'm seeing OOM exceptions and/or my Spring Boot application crashing altogether. I have not otherwise made any software or hardware changes to my server or the application itself since the upgrade from 2.0.0-RELEASE to 2.0.1-RELEASE, and I was not having these issues under 2.0.0-RELEASE or any version prior. I've always been using the Maven plugin to run my server as follows:

> sudo mvn spring-boot:run -Drun.jvmArguments="-Xmx14336m"

Note the maximum allocation of quite a lot of memory to the JVM. This is necessary as my application is very memory-intensive. It would seem that setting JVM arguments is no longer working properly or as I expected, as I'm seeing a lot of this in my Spring Boot logs:

> 2018-04-09 07:03:53.616 ERROR 6922 --- [https-openssl-nio-443-exec-245] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested$
> java.lang.OutOfMemoryError: Java heap space

I've been running under Java 9 since 2.0.0-RELEASE with no issues:

> java 9.0.4
> Java(TM) SE Runtime Environment (build 9.0.4+11)
> Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

For now, I've downgraded back to 2.0.0-RELEASE, and that appears to have resolved the OOM exceptions and crashing.

Has the preferred way of allocating more memory to Spring Boot or via the Maven plugin changed in 2.0.1? I was not able to find any information on this, but I apologize if this is described somewhere and I just missed it. Thanks in advance for any assistance.

**Comment by wilkinsona** [comment]
Thanks for the report, but it's impossible to diagnose a memory leak without some more information. A sample that reproduces the problem would be ideal. Failing that, a heap dump taken when the OutOfMemoryError occurs may help to pinpoint the problem.

While I'm here, a few observations about how you're running your app (that probably aren't the cause of the OOME):

- Running an app as root (using sudo) isn't recommended.
- `spring-boot:run` is only intended for use during development. It's not clear from the report if you're using it in other environments too.

**Comment by jamespizzurro** [comment]
I will attempt to throw together a quick Spring Boot application that allocates a lot of memory to reproduce the issue. Note however that I don't see this as a memory leak situation; I've closely monitored the memory usage of my application while it has stayed running for weeks and months on end prior to upgrading to 2.0.1-RELEASE from 2.0.0-RELEASE and saw nothing out of the ordinary. That's why I was inquiring as to any changes that might have been made related to memory allocation or JVM argument assignment or the Maven plugin for 2.0.1-RELEASE, as that's when this issue cropped up for me, and I have not made any other changes.

I was not aware that `spring-boot:run` was not meant to be used in production. I am indeed using it there.

**Comment by wilkinsona** [comment]
Thanks. We're not aware of any changes in Boot 2.0.1 that would have had any significant impact on memory usage.

> I was not aware that spring-boot:run was not meant to be used in production. I am indeed using it there.

I'd expect a typical production environment not to have Maven installed. A more typical process is to using `spring-boot:run` during development and to then build a `.jar` archive (`mvn package`) when you're ready to deploy. The `.jar` is copied to the production environment and run using `java -jar`.

When you run your application using `mvn spring-boot:run`, you'll either be running your application in the same JVM as Maven itself is running in, or Maven will be running in a separate JVM that has forked the JVM in which your application is running. In either case, you're wasting resources and exposing your production applications to problems, including security vulnerabilities, in Maven.

**Comment by philwebb** [comment]
One quick experiment you could try is temporarily downgrading the Spring Framework version (but don't run with that in production). Framework made some changes to annotation caching and I wonder if they've cause unexpected memory issues.

**Comment by jamespizzurro** [comment]
@wilkinsona Thanks for the additional info. I will look into doing things this way in production from here on out. Apologies for not being aware of this before.

@philwebb I've been running 2.0.0-RELEASE in production all day without issue after encountering the issues I described this morning with 2.0.1-RELEASE. Is there a suggested way to downgrade just Framework without downgrading Boot as a whole so I can try this?

**Comment by philwebb** [comment]
@jamespizzurro Set a `spring.version` property in your pom.xml to 5.0.4.RELEASE. See [this section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions) of the docs.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by virmundi** [comment]
Sorry I didn't get back to you on this. I couldn't figure out how Github tracked this. I didn't see the conversation.

I haven't had this issue since I upgraded to <spring.version>5.0.4.RELEASE</spring.version>.

**Comment by jamespizzurro** [comment]
Sorry, I forgot about this as well; been on Spring Boot 2.0.0 to avoid this issue. I will try the suggested workaround of <spring.version>5.0.4.RELEASE</spring.version> now though and see what happens. If I don't report back, it worked.

**Comment by snicoll** [comment]
> If I don't report back, it worked.

Please report back. If that works, then it's a regression in Spring Framework and we need to figure out what that is.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by jamespizzurro** [comment]
I don't mean to bump this again, but I just wanted to report back for anyone who might find this that this issue seems to be fixed as of at least 2.0.3. That's without any of the workarounds discussed above too.
