### ISSUE TITLE
Improve JNDI lookup to enable resourceRef by default

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-boot#12803]
Enhancement proposal:
I have Boot application packaged as WAR and deployed to external Tomcat instance.
Tomcat instance has multiple JMS `Resource`s (ConnectionFactory, queues, topics) created.
When I want to look up these resources through JNDI, I have to prepend configuration values with `java:comp/env/`
Can Boot's lookup capabilities be improved so that I don't have to do it and specify only names?

Boot version - 1.5.10-RELEASE

**Comment by philwebb** [comment]
> I have to prepend configuration values with java:comp/env/

Do you mean in your `application.properties` file? Can you provide a small sample that shows in more detail what you currently do and what you're suggesting as an alternative.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by pmihalcin** [comment]
I pushed sample [here](https://github.com/pmihalcin/spring-boot-jms-lookups-jndi). README contains guiding information. Sorry for the delay.

**Comment by snicoll** [comment]
@pmihalcin I guess a flag that uses that `createDefaultResourceRefLocator` for all JNDI lookup would be enough I suppose. The problem is that we don't have a central place to do that kind of things and there are places where it might make sense to use it and places where it wouldn't. I am not sure I really understand what the problem is.

Being explicit is good. What am I missing?

**Comment by pmihalcin** [comment]
@snicoll The thing is I have to specify `jms.ConnectionFactory` when I deploy to Weblogic and `java:comp/env/jms.ConnectionFactory` when I deploy to Tomcat. What I propose is to change only this line: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/JndiConnectionFactoryAutoConfiguration.java#L67.
To replace `new JndiLocatorDelegate()` with `JndiLocatorDelegate.createDefaultResourceRefLocator()`.
That way, both values above will be tried for lookup purposes.
So it's probably not necessary to expose `resourceRef` and make it central, changing the way JMS resources are looked up would be sufficient

**Comment by snicoll** [comment]
>  changing the way JMS resources are looked up would be sufficient

You lost me. The fact that JNDI resources are located in different areas is a server specific concern and not something Spring Boot should guess. There are application servers that expose JMS resources outside of `java:comp/env`. 

Are you expecting us to try without and then with or something?

**Comment by pmihalcin** [comment]
Yes.. try with and without.. it is already done here in https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/jndi/JndiLocatorSupport.java#L91:L115
if you set `resourceRef ` to true. It is set to true using `JndiLocatorDelegate.createDefaultResourceRefLocator()` and this can be used in Boot's `JndiConnectionFactoryAutoConfiguration`

**Comment by pmihalcin** [comment]
@snicoll What do you think?

**Comment by snicoll** [comment]
That makes sense, `JndiDataSourceLookup` is actually doing the same thing so we should do it as well for consistency for mail and JMS lookups. I've started to hack on something in a branch.
