### ISSUE TITLE
Investigate Togglz

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1281]
http://www.togglz.org/

**Comment by philwebb** [comment]
https://github.com/marceloverdijk/togglz-spring-boot/

**Comment by marceloverdijk** [comment]
@philwebb The Togglz integration in https://github.com/marceloverdijk/togglz-spring-boot/ is feature complete. It contains optimizations and bug fixes after user feedback.
The Togglz project is happy to include it as sub module to their project. I would prefer integrating it directly to Boot. What is your opinion?

**Comment by philwebb** [comment]
I've flagged this for team discussion, we'll talk about it on our next call. My gut instinct is that it might be better directly in Togglz since they already have Spring support (and it's less for us to maintain :smile:)

**Comment by marceloverdijk** [comment]
Ok, fair point regarding maintainance.
In the meantime I will already talk to Togglz team to make some progress integrating it there. If the team discussion will have a different outcome - which I don't expect :-) - we can easily switch where to put the code.

**Comment by philwebb** [comment]
We discussed it last week and we'd prefer to give it a little longer outside of Boot. Feature flags might be a fairly chunky topic, and currently we don't have a lot of experience with it in the team.

Let us know the outcome of your discussions with the Togglz team.

**Comment by marceloverdijk** [comment]
No problem. I've discussed this with Togglz team and it will be included in the next Togglz release (2.3.0). A 2.3.0.RC1 has already been released and published to get feedback.

**Comment by philwebb** [comment]
Sweet.
