### ISSUE TITLE
environmentWebEndpointExtension bean name used for two different classes

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-projects/spring-boot#12827]
`EnvironmentEndpointAutoConfiguration` has a bean with name `environmentWebEndpointExtension` of type `EnvironmentEndpointWebExtension` and `LifecycleMvcEndpointAutoConfiguration` also has bean with same name `environmentWebEndpointExtension` but of type `EnvironmentWebEndpointExtension` which seems right.

I think we should change the name for bean of type `EnvironmentEndpointWebExtension` or I am missing something here?

Below from LifecycleMvcEndpointAutoConfiguration:
```
@Configuration
    @ConditionalOnClass(EnvironmentEndpoint.class)
    @ConditionalOnWebApplication
    protected static class EndpointConfiguration {
        @Bean
        @ConditionalOnBean(EnvironmentEndpoint.class)
        @ConditionalOnEnabledEndpoint
        public EnvironmentWebEndpointExtension environmentWebEndpointExtension(
                EnvironmentManager environment) {
            return new EnvironmentWebEndpointExtension(environment);
        }
    }
```

Below from EnvironmentEndpointAutoConfiguration:

```
@Bean
	@ConditionalOnMissingBean
	@ConditionalOnEnabledEndpoint
	@ConditionalOnBean(EnvironmentEndpoint.class)
	public EnvironmentEndpointWebExtension environmentWebEndpointExtension(
			EnvironmentEndpoint environmentEndpoint) {
		return new EnvironmentEndpointWebExtension(environmentEndpoint);
	}
```

**Comment by JagmohanSharma** [comment]
Pull request requesting for this change. 
https://github.com/spring-projects/spring-boot/pull/12829
Please review.

**Comment by snicoll** [comment]
@JagmohanSharma thanks for the PR but I was already working on a solution. I've also raised https://github.com/spring-cloud/spring-cloud-commons/issues/354 as I believe the naming in Spring Cloud is too broad.
