### ISSUE TITLE
Upgrading to Springboot 2.0 @Autowired AuthenticationManager fails no such bean

### ISSUE THREAD

**Issue by nedge** [spring-projects/spring-boot#12836]
I have a `SecurityService` with an auto wired authentication manager

```java
class SecurityService implements ISecurityService{
  @Autowired
  private AuthenticationManager authenticationManager;
...
}
```

I'm using a `GlobalAuthenticationConfigurerAdapter` to set up a authentication manager as follows:

```java
@Configuration
public class AuthenticationSecurityConfig extends GlobalAuthenticationConfigurerAdapter {
 @Override
    public void init(AuthenticationManagerBuilder builder) throws Exception {
        builder.userDetailsService(userDetailsService)
        	.passwordEncoder(bcryptPasswordEncoder);
    }
}
```

However the `authenticationManager` is failing - no such bean

The Application is using:

```java
@ComponentScan(basePackages = "com.....")
@EnableAutoConfiguration
@EnableTransactionManagement
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)
```

This code worked fine in SpringBoot 1.5.3.RELEASE but no longer in 2.0.0.RELEASE

**Comment by mbhave** [comment]
@nedge As of Spring Boot 2.0, we no longer auto-configure a bean for `AuthenticationManager`. We provide a bean for `UserDetailsService`. Can you provide a small, minimalistic sample so that we can understand what your use case is?

**Comment by snicoll** [comment]
@nedge this is also covered in the [Migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#authenticationmanager-bean). If that doesn't help, please attach a sample and we can reopen this one.
