### ISSUE TITLE
Support Devtools with Java 9+ modulepath

### ISSUE THREAD

**Issue by TumanovViktor** [spring-projects/spring-boot#12832]
I am using Java 10 with gradle and spring-boot 2.0.0.RELEASE.
The problem is that DevTools does not work with Java 9 modularity.

-- ChangeableUrls does not read entries from module path
-- It is not possible to override DefaultRestartInitializer by our own implementation to add URLs
Is there any way to make java 9 modularity work?

**Comment by philwebb** [comment]
Not currently I'm afraid.

**Comment by philwebb** [comment]
Given the limited number of Spring Boot developers using module paths, we've decided not to invest in this at this time.
