### ISSUE TITLE
Upgrade spring boot 2.0.x to Tomcat 8.5.30

### ISSUE THREAD

**Issue by mrcasablr** [spring-projects/spring-boot#12846]
Tomcat 8.5.30 is now available - http://mail-archives.apache.org/mod_mbox/www-announce/201804.mbox/%3Cd80fbc83-a1a5-953f-3a0d-32b712705700%40apache.org%3E

**Comment by snicoll** [comment]
@mrcasablr thanks but there is no need to raise dependencies upgrade issue, we have a semi-automated process that takes care of this.
