### ISSUE TITLE
Devtools does not trigger a restart upon jar change

### ISSUE THREAD

**Issue by edpeng** [spring-projects/spring-boot#12869]
# Summary
As per devtools documentation: "Applications that use spring-boot-devtools automatically restart whenever files on the classpath change".

Restart detection does not appear to work for changes made to jar based classpath resources even when specified by the **restart.include** property.

# Description
Refer to [test project](https://github.com/edpeng/devtools-restart-with-jar-dependencies) to reproduce this problem.

Given spring-devtools.properties
`restart.include.mydep=/maindep-.*\.jar`

Spring log confirms Restarter has included the jar:
```2018-04-16 14:47:43.525 DEBUG 79272 --- [  restartedMain] o.s.boot.devtools.restart.Restarter      : Starting application my.mainapp.MainappApplication with URLs [file:/home/dev/workspace/restart-app/mainapp/build/classes/java/main/, file:/home/dev/workspace/restart-app/mainapp/build/resources/main/, file:/home/dev/workspace/restart-app/main-dep/build/libs/maindep-1.0-SNAPSHOT.jar]```

Changes under "app/mainapp/build/classes/java/main" causes spring boot to restart as expected. Changes made to the maindep-1.0-SNAPSHOT.jar **does not cause restart**. Any attempt to use the application post jar change causes the following exception:

```2018-04-16 14:52:05.391 ERROR 79272 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: my/HelloDep] with root cause```

```
java.lang.ClassNotFoundException: my.HelloDep
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
        at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:148) ~[spring-boot-devtools-2.0.1.RELEASE.jar:2.0.1.RELEASE]
```
# Possible cause ...

```
public ClassPathFileSystemWatcher(FileSystemWatcherFactory fileSystemWatcherFactory,
			ClassPathRestartStrategy restartStrategy, URL[] urls) {
		Assert.notNull(fileSystemWatcherFactory,
				"FileSystemWatcherFactory must not be null");
		Assert.notNull(urls, "Urls must not be null");
		this.fileSystemWatcher = fileSystemWatcherFactory.getFileSystemWatcher();
		this.restartStrategy = restartStrategy;
		this.fileSystemWatcher.addSourceFolders(new ClassPathFolders(urls));
}
```
In the constructor of `org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher` it receives the correct list of urls matching the entries found in the log file. 

It is on this line: `this.fileSystemWatcher.addSourceFolders(new ClassPathFolders(urls));` 

where the URL to the jar is excluded because it is not a folder (does not end with "/). 

Refer to `new ClassPathFolders(urls)` -> `addUrl()` -> `url.getProtocol().equals("file") && url.getPath().endsWith("/")`.

Perhaps the file system watcher can be modified to handle files as well?

**Comment by wilkinsona** [comment]
This is working as designed.

DevTools is intended to be used in your IDE where individual `.java` files are compiled into one or more `.class` files that are available directly on the filesystem. Watching `.jar` files would add complexity and would also be of limited benefit as you'd have to rely on something recompiling and packaging the jar's contents before a change could be picked up.

As described [in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload), the `restart.include` property can be used to customise the restart class loader. It does not affect the locations that are watched for changes. Additional paths can be watched using [`spring.devtools.restart.additional-paths`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart-additional-paths).
