### ISSUE TITLE
Allow LocalHostUriTemplateHandler to be created with a custom underlying UriTemplateHandler

### ISSUE THREAD

**Issue by mihhail-lapushkin** [spring-projects/spring-boot#12871]
* In [TestRestTemplateContextCustomizer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/TestRestTemplateContextCustomizer.java) a `LocalHostUriTemplateHandler` gets created and passed to `TestRestTemplate`.
* [LocalHostUriTemplateHandler](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/LocalHostUriTemplateHandler.java) creates `DefaultUriBuilderFactory` in the constructor and does not provide any means to modify/replace it later.
* I would like to have a way to replace `DefaultUriBuilderFactory` (`RootUriTemplateHandler.handler`) with my custom implementation.

**Comment by wilkinsona** [comment]
Can you please describe what you'd like to be able to do in more detail? You've describe the how (of one approach) but I don't really understand what, exactly, you want to do and why you want to do it. It's important to understand it as there may be another way to achieve the same goal.

**Comment by mihhail-lapushkin** [comment]
My issue is that SB2 (or rather Spring 5) removed `+` encoding in `TestRestTemplate`:
https://github.com/spring-projects/spring-framework/commit/f2e293aadf98cb64ba7ef3044b59f469efd21503#diff-774d5dc1a5c7494860b8f715e5976d04

I need to use `+` in URLs in my tests. Full URLs as a string, not as a template. There are 2 way I can make it happen:
1. Provide my own implementation of `RootUriTemplateHandler.handler` that just encodes plusses. My current approach.
2. Obtain a reference to `RootUriTemplateHandler.handler` and modify the `EncodingMode` to `VALUES_ONLY`. This would force me to pre-encode the URL myself as I understood it from testing, but I don't want to do it, as I would have to duplicate a lot of code that already exists in `RestTemplate`.

If there is an easy third way to bring back `+` encoding, I would love to hear it.

**Comment by wilkinsona** [comment]
Thanks.

How about an overloaded constructor on `LocalHostUriTemplateHandler` that takes a `UriTemplateHandler`:

```java
	public LocalHostUriTemplateHandler(Environment environment, String scheme,
			UriTemplateHandler uriTemplateHandler) {
		super(uriTemplateHandler);
		Assert.notNull(environment, "Environment must not be null");
		Assert.notNull(scheme, "Scheme must not be null");
		this.environment = environment;
		this.scheme = scheme;
	}
```

You could then create your own `TestRestTemplate` configured to use your customised `LocalHostUriTemplateHandler`.

**Comment by mihhail-lapushkin** [comment]
This would work for me.

**Comment by snicoll** [comment]
Closing in favour of PR #13208
