### ISSUE TITLE
spring-configuration-metadata.json does not contain description for group

### ISSUE THREAD

**Issue by lchayoun** [spring-projects/spring-boot#12873]
When adding a comment on a nested properties class, the description field of the relevant property group is not filled with the written comment

**Comment by snicoll** [comment]
@lchayoun unfortunately that description is not precise enough to figure out what you're reporting. There are no descriptions for group (be it nested or not, see #11616). 

Please clarify what you meant, a sample that shows the wrong metadata generated would be ideal.

**Comment by snicoll** [comment]
Duplicate of #11616
