### ISSUE TITLE
Web client often hangs when calling tomcat endpoint (reactive)

### ISSUE THREAD

**Issue by myhau** [spring-projects/spring-boot#12870]
## Issue

`WebClient` often hangs during integration tests when requesting reactive controller endpoint (tomcat)
This issue is partially explained here: https://github.com/spring-projects/spring-boot/issues/12647 and (@bclozel said it is somehow connected) here: https://jira.spring.io/browse/SPR-16521 , but now after fix was added (in 2.0.1) it cannot be reproduced by: https://github.com/myhau/spring-boot-2-reactor-tomcat-issue, but still happens in our integration suite almost always for at least one test.

## Logs

[Here](https://github.com/myhau/spring-boot-2-tomcat-reactive-hangs-logs) you can see trace logs from two similar integration tests (both tests are testing very similar scenario, so you can assume that endpoint url is the only difference here)

- `success.log` - test that succeeded 
- `fail.log` - test that failed

As you'll see one of differences (I recommend using `Compare Files` action in intellij) between these logs is that `onAllDataRead` is called very early in `fail.log` and "reactive state machine" inside `AbstractListenerReadPublisher` does not log any state transitions.

## Possible root cause

I see that @rstoyanchev and @violetagg were working in this area, so I have a question: are you sure that this (`ServletServerHttpRequest.RequestBodyPublisher`):

```java
              protected DataBuffer read() throws IOException {
			if (this.inputStream.isReady()) {
				DataBuffer dataBuffer = readFromInputStream();
				if (dataBuffer != EOF_BUFFER) {
					return dataBuffer;
				}
				else {
					// No need to wait for container callback...
					onAllDataRead();
				}
			}
			return null;
		}
```
shouldn't be:

```java
              protected DataBuffer read() throws IOException {
			if (this.inputStream.isReady()) {
				DataBuffer dataBuffer = readFromInputStream();
				if (dataBuffer != EOF_BUFFER) {
					return dataBuffer;
				}
				else if(this.inputStream.isFinished()) {
					// No need to wait for container callback...
					onAllDataRead();
				}
			}
			return null;
		}
```

?

**Comment by bclozel** [comment]
Without a proper sample app showing the issue, it’s really hard to understand what’s going on.
Do you have such a sample? You’re saying both endpoints are really similar - can you reduce those to simple examples we can execute?

**Comment by rstoyanchev** [comment]
About the specific question: `EOF_BUFFER` is returned if [readFromInputStream returns -1](https://github.com/spring-projects/spring-framework/blob/0754833b375ec403e1d3b36e7113f9959af9d766/spring-web/src/main/java/org/springframework/http/server/reactive/ServletServerHttpRequest.java#L215), which indicates the end of the stream has been reached, but it looks like it can also return that if 0 bytes were read. Do you know if that is the case, or have you verified if the suggested diff makes the tests not fail?

**Comment by myhau** [comment]
@rstoyanchev No I did not verify this. I will try to create some minimal example project so that it is reproducible

**Comment by rstoyanchev** [comment]
I have created https://jira.spring.io/browse/SPR-16728.

**Comment by rstoyanchev** [comment]
I've committed changes for SPR-16728 and 5.0.6 and 5.1.RC1 snapshots are building. Give that a try to confirm if it makes a difference.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by myhau** [comment]
@rstoyanchev It seems to be working, but I'm not 100% sure yet (it was happening from time to time before the fix)

**Comment by bclozel** [comment]
Alright I'm closing this for now; feel free to reopen with a repro project if this happens again.
