### ISSUE TITLE
Upgrading to 2.0.1: Jolokia is not available

### ISSUE THREAD

**Issue by evmin** [spring-projects/spring-boot#12881]
Good day. 

After upgrading to Springboot 2.0.1 jolokia endpoint became not available.

Please find attached the code sample to reproduce the issue. 

If I comment out 
`            
springBootVersion = '2.0.1.RELEASE'
`

and instead use
`
   springBootVersion = '1.5.8.RELEASE'
`

Everything works, and jolokia is available on /jolokia endpoint.
The other way around jolokia is not available.

Am I missing something obvious here?

Thank you!

**Comment by evmin** [comment]
[sample0.zip](https://github.com/spring-projects/spring-boot/files/1918577/sample0.zip)

**Comment by evmin** [comment]
Ok. Actuator issue.

**Comment by snicoll** [comment]
@evmin please consider reading [the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints) before opening an issue.
