### ISSUE TITLE
Spring Boot 1.5.3.RELEASE actuator endpoint redirect to a login page when management.security.enabled is false 

### ISSUE THREAD

**Issue by ettwz** [spring-projects/spring-boot#12887]
my project used Spring Boot 1.5.3.RELEASE and Spring Cloud Dalston.SR4

I have already set
```yaml
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
```
in bootstrap.yml

But the endpoint of actuator redirect to a login page sometimes. 

- I find when endpoint status was 302, the bean of 
`org.springframework.boot.actuate.autoconfigure.EndpointHandlerMapping`
 is missing. 

- In class 
`
org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration
`
 can't get EndpointHandlerMapping through
`
endpointHandlerMapping = context.getBean(EndpointHandlerMapping.class);
`
- As a result, variable delegate only have "/login" and "/error" two endpoint. So the actuator endpoints have been redirected.

It seems like `@ConditionalOnMissingBean` have some problems.
What should I do?
Thanks.

**Comment by snicoll** [comment]
There's nothing that really indicates a bug in Spring Boot and it' impossible to tell what is going on without a sample that we can run ourselves. Can you share one please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
