### ISSUE TITLE
Shutdown endpoint can be synchronous or can I choose whether to execute it synchronously?

### ISSUE THREAD

**Issue by fudali113** [spring-projects/spring-boot#12880]
https://github.com/spring-projects/spring-boot/blob/3cb2246e7a6f4094b9dda8ff767117e5f78f2dea/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/context/ShutdownEndpoint.java#L51

In some cases I might want to make it clear that my application has been closed.
such as k8s preStop exec /shutdowm by safe stop my application

**Comment by snicoll** [comment]
@fudali113 sorry I am not following. You've used the term synchronously twice which, I believe, wasn't your intention.

**Comment by fudali113** [comment]
my mean the shutdown endpoint should be able to choose whether to execute in sync.
Synchronous execution allows me to verify that the application is closed.
@snicoll

**Comment by philwebb** [comment]
I don't think it will be possible for us to wait for shutdown to complete before returning a response because shutdown needs to close the HTTP server.
