### ISSUE TITLE
Spring Boot 2.0 Migration Guide Additions

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#12889]
When trying to update to Spring Boot 2 I ran into some additional ideas to add to the migration guide.

* In Spring Boot 1.x `spring-boot-starter-thymeleaf` the `thymeleaf-layout-dialect` dependency was included automatically, but in Boot 2.x it is no longer included. It would be nice to list that users need to include `nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect` explicitly.
* To be consistent with Spring Boot 1.0.x, set `spring.jpa.hibernate.use-new-id-generator-mappings=false`

**Comment by snicoll** [comment]
The migration guide has been updated
