### ISSUE TITLE
Deprecate Maven Plugin excludeArtifactIds property

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12885]
The Spring Boot maven plugin has a `excludeArtifactIds` property that allows to exclude dependencies by specifying their artifactId. I think this was a mistake now that we have the general include/exclude mechanism. 

Excluding by groups does make sense though. 

I'd like to deprecate this sooner than latter. Perhaps too late for `2.0.x`?

**Comment by wilkinsona** [comment]
I think it's fine to add the deprecation in 2.0.x as the recommended alternative is already in place.
