### ISSUE TITLE
Spring data mongodb - Lazying initialization/Loading not working after upgrading to Spring boot 2.0

### ISSUE THREAD

**Issue by Afridikht** [spring-projects/spring-boot#12896]
Why `@DBRef`(in Spring data Mongodb) not working after upgrading project from Spring boot 1.5.* to 2 and Mongodb from 3.4 to 3.6?

Before up-gradation everything was working fine, but just after upgrading to Spring boot 2, `@DBRef` is not working with both `lazy = true` & `lazy = false`

```
@Document(collection = "user")
public class MerchantUser{
    @Id
    private String id;

    @DBRef(db = "merchant", lazy = true)
    MerchantBusinessInfo merchant;

    //Constructors, Getters & Setters
}

@Document(collection = "merchant")
public class MerchantBusinessInfo{
    @Id
    private String id;

    //Basic properties, Constructors, Getters & Setters
}
```

Now after successfully loading merchant user, `merchant ` look like this(`id ` is present, and `lazy = true`)

![1](https://user-images.githubusercontent.com/6583666/38912540-4703fca6-42ef-11e8-9027-6d9e61f74594.png)

But when I try to get `id `or any other field using `merchantUser.getMerchant().get**()`, it returns `null `without any error.
In case if I set `lazy = false`, complete `merchant `object becomes `null`.

**_Same issue raises for each and every object annotated with_** `@DBRef`

**Comment by snicoll** [comment]
Thanks but there is no indication that's a bug in Spring Boot. Please raise that issue [in the Spring Data MongoDB issue tracker](https://jira.spring.io/browse/DATAMONGO/).
