### ISSUE TITLE
When spring applications with gradle multi-module run, these can't load property sources.

### ISSUE THREAD

**Issue by jinbeomhong** [spring-projects/spring-boot#12909]
I found a bug with spring boot when using gradle multi module project. I setup spring boot applications project with gradle multi module project. Each module is just spring boot application. To run all applications rightly, i have to refresh all module through refreshing gradle project on root project. On the other hand, If i refresh specific gradle module, other applications which also are submodule cannot load property source. For detailed explanation, i want to present sample application: https://github.com/jinbeomhong/sample-demonstrating-boot-cannot-load-propertysource-in-multi-module.git

And i uploaded the video demonstrating this problem on youtube. You can reproduce this situation: (https://www.youtube.com/watch?v=5kGu6MhHfmY)

I also asked question on stackoverflow here : https://stackoverflow.com/questions/49885634/when-spring-applications-with-gradle-multi-module-runs-on-spring-ide-dash-board

**Comment by snicoll** [comment]
@jinbeomhong I've seen your SO question and the post on Gitter. I don't think there is a need to cross-post to a third location. I've had a look to the video and could find out why you believe it is related to Spring Boot. Let's continue the discussion on SO and please do not cross post like this in the future.
