### ISSUE TITLE
Missing documentation for migration of EmbeddedServletContainerCustomizer

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#12902]
I looked in the (migration guide)[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide] but I couldn't see any reference to `EmbeddedServletContainerCustomizer`.

**Comment by philwebb** [comment]
Good point. The replacement is `WebServerFactoryCustomizer` for anyone that finds this issue before we fix the migration guide.

**Comment by wilkinsona** [comment]
I've updated the [relevant section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#embedded-containers-package-structure) of the migration guide.
