### ISSUE TITLE
start main method occur error message

### ISSUE THREAD

**Issue by czgczg** [spring-projects/spring-boot#12907]

**Comment by snicoll** [comment]
@czgczg I don't know understand the problem you are reporting but it looks like you're having a question.  As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask on StackOverflow or come chat with us on Gitter.
