### ISSUE TITLE
Documentation at https://docs.spring.io/spring-boot/docs/ - .BUILD-SNAPSHOT/ version is produced only once (and is not needed))

### ISSUE THREAD

**Issue by paulvi** [spring-projects/spring-boot#12915]
When looking at Documentation at https://docs.spring.io/spring-boot/docs/ , one might notice that `.BUILD-SNAPSHOT/` version is produced only once with previous version release

![image](https://user-images.githubusercontent.com/1614482/38967376-512f1542-43b9-11e8-8c45-0f55be153061.png)

So it looks like during maven-release a cut `.RELEASE` version docs are copied to docs,
and then next (+1) version `.BUILD-SNAPSHOT/` version docs are copied, but never updated afterwards.

But there is no need for them to be updated as there is `current-SNAPSHOT/` for current development,
and once in the end, say, `2.0.5.BUILD-SNAPSHOT`  must become identical to `2.0.5.RELEASE`,
so there is no value of specific version docs copy.

**Suggestion** is no to copy   `.BUILD-SNAPSHOT/` specific version docs at all.  (As it was for 1.1.x versions)

![image](https://user-images.githubusercontent.com/1614482/38967619-782750fa-43ba-11e8-9571-ade7233bb18f.png)

**Comment by paulvi** [comment]
P.S. Actually the content of the folder is updated, it is just folder timestamp stays the same.

For example
https://docs.spring.io/spring-boot/docs/2.0.1.BUILD-SNAPSHOT/reference/pdf/  
and  
https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/pdf/  
have pdf produced on the same date 2018-04-05

Nevertheless, I still think producing .BUILD-SNAPSHOT/ for specific version is overdo, and create clutter.  

N.N.x.-SNAPSHOT is enough, as there is no actually branches for N.N.x versions

**Comment by snicoll** [comment]
> (As it was for 1.1.x versions)

That statement is also inaccurate. Those were removed as part of a manual polish on the doc server. Given you've found out that the doc is updated as it should I am going to close this issue.

**Comment by paulvi** [comment]
Could folder time stamp be updated?

Then it will be always easy to see if some folder content is not updated.
Right now it would require looking inside.
