### ISSUE TITLE
Able to enable only management endpoints

### ISSUE THREAD

**Issue by Delorien84** [spring-projects/spring-boot#12927]
Hi,
 I have spring-cloud-stream application, that does not have any REST endpoints at all. I would like to have option to disable standard mvc server and only enable management server. Currently I have only option to set `spring.main.web-application-type=none` but this will disable also management server. 

I may have standard and management on same port. But still standard MVC filters and handlers are registered. Also as side effect, when I use spring-cloud-consul, there are registered two services `app` and `app-management`.

Proposal:
* via configuration options be able to disable standard mvc server (eg. using `server.port=-1` as similar to `management.port=-1` to disable management part)
* application will only expose management server ( /actuator endpoints)
* spring cloud service registry will register only management server
 
Thanks

**Comment by wilkinsona** [comment]
>  I would like to have option to disable standard mvc server and only enable management server

What benefits would this bring? Currently, the management.port is intended to allow you to separate the management endpoints from the application's own endpoints by exposing them on a different port. If the application does not have any of its own endpoints then that separation isn't needed.

**Comment by Delorien84** [comment]
Hi, I would like to have some options to have enable only /actuator endpoints.  Eg. currently following endpoints are registered by default:

```
Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.reactive.resource.ResourceWebHandler]
Mapped URL path [/**] onto handler of type [class org.springframework.web.reactive.resource.ResourceWebHandler]
``` 
And possible something more beans (features) are registered, that I will never use. So it should save some resources. 

Also as side effect, I would like that when using spring cloud consul (or other service discovery), the application will register only management part, as there is no "application" part.

It would be fine to have some configuration options to do this all in simple way.

**Comment by wilkinsona** [comment]
You can disable static resource handling using `spring.resources.add-mappings: false`. Please try that and let us know if it meets your needs.

**Comment by Delorien84** [comment]
Thank you, this is sufficient solution. I have opened https://github.com/spring-cloud/spring-cloud-consul/issues/418 to resolve spring-cloud part.

**Comment by JigarJoshi** [comment]
👍 Please support this feature and consider re-opening it.
