### ISSUE TITLE
Add support for commons-dbcp2

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#1292]
At the moment Spring Boot supports auto configuration for commons-dbcp. However there is now also a [commons-dbcp2](http://commons.apache.org/proper/commons-dbcp/) which is a JDBC4.1 implementation of a datasource. 

Would be nice if this could be added as an autoconfig alternative.

**Comment by hantsy** [comment]
Hi, I can not find a DataSourcePoolMetadata for commons-dbcp2, what the purpose of DataSourcePoolMetadata class itself?

**Comment by snicoll** [comment]
@hantsy this issue is closed and questions are to be asked on stackoverflow. That being said, you have a point that there is no metrics from Commons-dbcp2 so I've raised #4562 for that.

**Comment by hantsy** [comment]
@snicoll  Thanks.
