### ISSUE TITLE
spring security  in mysql 8 new keywords "groups" table name error cause bug

### ISSUE THREAD

**Issue by vnobo** [spring-projects/spring-boot#12929]
look [MySQL 8.0 New Keywords and Reserved Words](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series)

add "groups" keywords.

so security error!

message:

> Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups' at line

thanks!

**Comment by snicoll** [comment]
> so security error!

I am sorry, I don't understand the problem you are reporting nor the component that might trigger it. You'll have to provide more details first. A sample would be ideal.

**Comment by vnobo** [comment]
hi,mainly because spring security JDBC WebSecurityConfigurerAdapter .us config  
 

> @Configuration
    @EnableWebSecurity
     public class WebSecurityConfig extends WebSecurityConfigurerAdapter {


           @Autowired
           public void configureGlobal(AuthenticationManagerBuilder auth,
                                                  @Qualifier("dataSource") DataSource dataSource) throws Exception {
                   auth
                       .jdbcAuthentication()
                      .dataSource(dataSource)
                      .passwordEncoder(pbkdf2PasswordEncoder())
                      .withUser(User.withUsername("admin").roles("admin").build());
           }
    }
so default JdbcUserDetailsManager About the groups SQL statement.
   

> 
	// GroupManager SQL
	public static final String DEF_FIND_GROUPS_SQL = "select group_name from groups";
	public static final String DEF_FIND_USERS_IN_GROUP_SQL = "select username from 
                     group_members gm, groups g "
			+ "where gm.group_id = g.id" + " and g.group_name = ?";
	public static final String DEF_INSERT_GROUP_SQL = "insert into groups (group_name) values (?)";
	public static final String DEF_FIND_GROUP_ID_SQL = "select id from groups where group_name = 
                                   ?";
	public static final String DEF_INSERT_GROUP_AUTHORITY_SQL = "insert into group_authorities 
                          (group_id, authority) values (?,?)";
	public static final String DEF_DELETE_GROUP_SQL = "delete from groups where id = ?";
	public static final String DEF_DELETE_GROUP_AUTHORITIES_SQL = "delete from group_authorities 
                      where group_id = ?";
	public static final String DEF_DELETE_GROUP_MEMBERS_SQL = "delete from group_members where 
                         group_id = ?";
	public static final String DEF_RENAME_GROUP_SQL = "update groups set group_name = ? where 
                        group_name = ?";
	public static final String DEF_INSERT_GROUP_MEMBER_SQL = "insert into group_members 
                              (group_id, username) values (?,?)";
	public static final String DEF_DELETE_GROUP_MEMBER_SQL = "delete from group_members where 
                        group_id = ? and username = ?";
	public static final String DEF_GROUP_AUTHORITIES_QUERY_SQL = "select g.id, g.group_name, 
               ga.authority "
			+ "from groups g, group_authorities ga "
			+ "where g.group_name = ? "
			+ "and g.id = ga.group_id ";
	public static final String DEF_DELETE_GROUP_AUTHORITY_SQL = "delete from group_authorities 
                       where group_id = ? and authority = ?";

 look "GROUPS" become the MYSQL 8  keyword.

If executed, it will cause errors.
`Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups' at line`

so is me temporary solution is:

>     @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth,
                                                  @Qualifier("dataSource") DataSource dataSource) throws Exception {
        JdbcUserDetailsManager jdbcUserDetailsManager = auth
                .jdbcAuthentication()
                .dataSource(dataSource)
                .passwordEncoder(pbkdf2PasswordEncoder())
                .getUserDetailsService();
        jdbcUserDetailsManager.setEnableGroups(true);
        jdbcUserDetailsManager.setFindAllGroupsSql("select group_name from `groups`");
        jdbcUserDetailsManager.setInsertGroupSql("insert into `groups` (group_name) values (?)");
        jdbcUserDetailsManager.setFindGroupIdSql("select id from `groups` where group_name = ?");
        jdbcUserDetailsManager.setDeleteGroupSql("delete from `groups` where id = ?");
        jdbcUserDetailsManager.setRenameGroupSql("update `groups` set group_name = ? where 
                   group_name = ?");
        jdbcUserDetailsManager.setFindUsersInGroupSql("select username from group_members gm, 
                        `groups` g "
                + "where gm.group_id = g.id" + " and g.group_name = ?");
        jdbcUserDetailsManager.setGroupAuthoritiesByUsernameQuery("select g.id, g.group_name, 
                 ga.authority "
                + "from `groups` g, group_authorities ga "
                + "where g.group_name = ? "
                + "and g.id = ga.group_id ");
        //return jdbcUserDetailsManager;
    }

look code "  `groups` ", all groups increased"``"symbols.

I think this is a BUG,so Feedback here.

Thanks to the efforts of the spring team, this is only possible when you use MYSQL 8 and  enable a permission group.

**Comment by snicoll** [comment]
@vnobo thanks for the feedback. This issue is unrelated to Spring Boot I am afraid (as per the class you mentioned). Please open an issue in the [Spring Security issue tracker](https://github.com/spring-projects/spring-security/issues/)

(/cc @rwinch)
