### ISSUE TITLE
update 1.5 > 2.0.1 (405 not allowed only on my authentication endpoint)

### ISSUE THREAD

**Issue by istiti** [spring-projects/spring-boot#12928]
I update my spring boot 1.5 app to 2.0.1 all seems ok when I use created "token" at springboot startup and make a post/get request to my restcontroller it works, but When I make a call to my `/imo/api/authenticate` with sending:
```
X-Auth-Password: 19531228
X-Auth-Username: admin
```

it get me 405 response code. 

Here's my spring security config:

```java
@Override
protected void configure(HttpSecurity http) throws Exception {
	
	http
    	.csrf().disable()
    	.headers()
    		.addHeaderWriter((request,response)->{ 
    			response.addHeader("X-Content-Security-Policy", "......");
    			response.addHeader("Content-Security-Policy", "......");
    		})
    		
    	.and()
    	.headers()
    		.frameOptions()
    			.sameOrigin()
    	.and()
    	.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
    .and()
    	.authorizeRequests()
    
    	.antMatchers(HttpMethod.GET
    			     ,"/api/token/*/isvalid"
    			     ,"/api/backup/lastupdate"
    			).permitAll()
    .and()
    	.authorizeRequests()
    	.anyRequest()
    	.authenticated()
    .and()

    	.exceptionHandling().authenticationEntryPoint(unauthorizedEntryPoint())
	.and()
		.requestMatchers()
			.antMatchers("/api/**", "/ws")
	.and(); 
	http.addFilterBefore(allowCrossOriginFilter, ChannelProcessingFilter.class)
	 	.addFilterBefore(new AuthenticationFilter(this.authenticationManager), BasicAuthenticationFilter.class);
		
}
```

Network  request: 
![image](https://user-images.githubusercontent.com/2789203/39035911-17b94ea4-447c-11e8-8027-070baec3470a.png)

I get: 
Request URL: http://localhost:8080/imo/api/authenticate
Request Method: POST
Status Code: 405 Method Not Allowed
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade

Current behavior: 
only 405 on my authentication controller endpoint
If I try another rest call GET:/imo/otherone?token={spring boot srtartup created token} it works 
Expected: 
POST call to `imo/api/authenticate` must return me new token as in spring boot v1.5!

ps: it seems i must say /autenticate is used to login and allowed but this was working in v1.5

**Comment by mbhave** [comment]
@istiti It's hard to tell what's going on just by looking at the code snippet that you've provided. If you'd like us to investigate further, please provide a minimalistic sample with steps to reproduce.

**Comment by istiti** [comment]
@mbhave hard to me get out complet repro from my large private souces, can’t we investigate otherwise like what file could help here? /api/authenticate was my login POST endpoint in v1.5

Regatds, 
Thanks

**Comment by snicoll** [comment]
@istiti if you want us to help you, please take the time to share a minimal sample as @mbhave asked you already.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
