### ISSUE TITLE
Request body is missing if returned Mono completes before input body Mono

### ISSUE THREAD

**Issue by myhau** [spring-projects/spring-boot#12921]
# Issue

Repo to reproduce: https://github.com/myhau/spring-boot-2-reactive-missing-body-issue

Run test in `MainControllerTest` and see what happens in logs (search for `Request body is missing`)

# Details
- I had to write log4j appender that slows down specific log messages so that issue is always reproducible
- this probably happens only for chunked encoding (I'm not sure)

# Environment
- Spring boot version: 2.0.1.RELEASE (webflux)
- happens for netty and tomcat server implementations

**Comment by philwebb** [comment]
@myhau Spring Boot isn't directly involved with the low level WebFlux code. I've raised [SPR-16747](https://jira.spring.io/browse/SPR-16747) so see if the Spring Framework team can investigate.

**Comment by bclozel** [comment]
I've closed the Spring Framework issue as this is the expected behavior (and you should not do that in a controller handler in the first place). @myhau please use StackOverflow or come and chat on gitter for further questions.

Thanks!
