### ISSUE TITLE
spring-boot application get warning: CONSOLE_LOG_PATTERN_IS_UNDEFINED

### ISSUE THREAD

**Issue by kuchaguangjie** [spring-projects/spring-boot#12925]
There is a **spring-boot** *(2.0.0.RELEASE)* application as part of the **spring-cloud** *(Finchley.M9)* cluster.  
On startup, it always print following line:

> CONSOLE_LOG_PATTERN_IS_UNDEFINEDCONSOLE_LOG_PATTERN_IS_UNDEFINEDCONSOLE_LOG_PATTERN_IS_UNDEFINED

Screenshot:  
![a](https://user-images.githubusercontent.com/4230959/39030830-1d44c4aa-4497-11e8-86b0-48c1a2b9633e.png)

---
*(following are the configuration)*  

**application.yml:**

	## spring-boot configuration,

	# logging
	logging:
	  file: "log/hello.log"
	  pattern:
	    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
	    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
	  level:
	    root: INFO

	spring:
	  application:
	    name: eric-sc-hello

	server:
	  port: 9191

	management:
	  endpoints:
	    web:
	      exposure:
		include: "*"

	eureka:
	  client:
	    serviceUrl:
	      defaultZone: http://localhost:8761/eureka/

	eric-sc-hello:
	  ribbon:
	    eureka:
	      enabled: false
	    listOfServers: localhost:9191,localhost:9192,localhost:9193
	    ServerListRefreshInterval: 15000

**logback-spring.xml:**

	<?xml version="1.0" encoding="UTF-8"?>
	<configuration>
	  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
	    <encoder>
	      <charset>UTF-8</charset>
	      <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
	    </encoder>
	  </appender>
	  <appender name="FILE"
	    class="ch.qos.logback.core.rolling.RollingFileAppender">
	    <encoder>
	      <pattern>${FILE_LOG_PATTERN}</pattern>
	    </encoder>
	    <file>${LOG_FILE}</file>
	    <rollingPolicy
	      class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
	      <fileNamePattern>${LOG_FILE}.%i</fileNamePattern>
	      <minIndex>1</minIndex>
	      <maxIndex>10</maxIndex>
	    </rollingPolicy>
	    <triggeringPolicy
	      class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
	      <MaxFileSize>10MB</MaxFileSize>
	    </triggeringPolicy>
	  </appender>

	  <root level="INFO">
	    <appender-ref ref="CONSOLE" />
	    <appender-ref ref="FILE" />
	  </root>
	</configuration>

---

The warning says `CONSOLE_LOG_PATTERN` is undefined for 3 times.

But `logging.pattern.console` is defined in `application.yml`, and the log lines in console is printed in the specified format.

So, why the warning pop-up, and how can I remove it?

_(I asked this on stackoverflow several days ago, but didn't get any respond yet: https://stackoverflow.com/questions/49879518)_

**Comment by snicoll** [comment]
Please do no need to cross-post. The template in this issue you've created mentioned that we don't use the tracker for questions. See also [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues).

**Comment by kuchaguangjie** [comment]
This is a bug, right? Not just a question I guess.

**Comment by snicoll** [comment]
there is nothing that indicates a bug at this point, and there's nothing that indicates it's related to Spring Boot to me. If that proves to be wrong, we can of course reopen.

**Comment by kuchaguangjie** [comment]
According to spring-boot document https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration, with `logging.pattern.console` defined in application config file, `CONSOLE_LOG_PATTERN` should be available for the `logback-spring.xml`.

This works in `spring-boot 1.5.8`, but after upgrading to `spring-boot (2.0.0.RELEASE)` and `spring-cloud (Finchley.M9)`, the warning line appear, so I guess it's related to spring-boot, and seems to be a bug.

**Comment by snicoll** [comment]
@kuchaguangjie don't you think if it would have been a good idea to indicate the exact same setup works with a previous version? 

The documentation you referenced mentions "Only supported with the default Logback setup". You have a custom logback config so I would expect this not to be the default.

Please share a sample that reproduces the problem and that works with 1.5

**Comment by kuchaguangjie** [comment]
I just did more test, and here is the details:

(1) There is an old pure spring-boot application, without spring-cloud, that use `spring-boot 1.5.8`, it use the same `logback-spring.xml` and same logging config in `application.yml` mentioned in the post above, and on startup it will print:

![a](https://user-images.githubusercontent.com/4230959/39033643-9e72fcb4-44a5-11e8-9164-af39ba656d04.png)

It says it found `logging.pattern.console` and `logging.pattern.file`, in the console output.

And, it don't have any warning about logging config.

(2) Then I got another project, use `spring-boot 2.0.0 RELEASE` and `spring-cloud Finchley.M9`, with exactly the same  `logback-spring.xml` and logging config in `application.yml`, then it complains `CONSOLE_LOG_PATTERN_IS_UNDEFINED`, and create a file named `LOG_FILE_IS_UNDEFINED` at application root on startup.

(3) Then I though maybe it's `spring-cloud`'s issue, so I take the old application in `(1)`, and upgrade the spring-boot from 1.5.8 to 2.0.0, and start it with spring-boot maven plugin, and there is no warning, but it also didn't say it found `logging.pattern.console`. So, maybe also might be caused by `spring-boot maven plugin`? I am not sure.

Above are the test results, a bit confused for me, need your experts to check that.

**Comment by snicoll** [comment]
@koupeng for the benefit of the entire community, it would be nicer to share a sample so that the team can reproduce the problem and fix it if applicable. If you share a minimal sample that we can run ourselves we can reopen this issue again.
