### ISSUE TITLE
Actuator's EndpointRequest doesn't consider server.servlet.path

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#12934]
In application.properties, set `server.servlet.path=/spring`

Now notice that EndpointRequest.* doesn't match anything. For example, a request for `/spring/actuator`/health doesn't match (a request for `/actuator/health` does match, though - even though it will return a 404).

**Comment by candrews** [comment]
It looks like the created `AntPathRequestMatcher` need to have their match patterns prefixed with the `server.servlet.path` value. Those lines are:
https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/security/servlet/EndpointRequest.java#L191
https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/security/servlet/EndpointRequest.java#L220
https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/security/servlet/EndpointRequest.java#L251

**Comment by mbhave** [comment]
@candrews I don't think it does. The `RequestMatcher` matches on `request.getServletPath`, which in this case (even when the request is `/spring/actuator/health`) is `/actuator/health`. If you would like us to investigate this issue further, please provide a minimalistic sample that we can use to reproduce the issue.

**Comment by candrews** [comment]
Create a new project using https://start.spring.io/ including Web, Security, and Actuator
In application.properties: `server.servlet.path=/spring`
Create this class:
```
package com.example.demo;

import org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.web.util.matcher.AntPathRequestMatcher;

@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests()
            	// this line works
//            	.requestMatchers(new AntPathRequestMatcher("/spring/actuator/health")).permitAll()
            	
//            	 this line does not work, but should: https://github.com/spring-projects/spring-boot/issues/12934
            	.requestMatchers(EndpointRequest.to("health")).permitAll()
                .anyRequest().denyAll()
                
                .and()
            .formLogin()
                .loginPage("/spring/login")
                .permitAll()
                .and()
            .logout()
                .permitAll();
    }
    
}
```

Run it, now go to http://localhost:8080/spring/actuator/health

I'd expect to get a JSON result back with the health check status of "UP" I actually get a 302 redirect.
In WebSecurityConfig, if you comment out the first noted line, and uncomment the second noted line, then run this test again, you'll get the expected result.

**Comment by mbhave** [comment]
ah, I didn't realize that the property you were configuring was `server.servlet.path` and not `server.servlet.context-path`. The issue title says context-path and if that's what you want to do, you'd need to set `server.servlet.context-path`. `EndpointRequest` will work in that case. But we need to fix the case where `EndpointRequest` doesn't match if `server.servlet.path` is set.

**Comment by candrews** [comment]
I'm sorry about the error in the title :(
I'm glad we're on the same page now, though! Thank you.

**Comment by n0mer** [comment]
@mbhave `server.servlet.context-path` is also ignored in 2.0.1.RELEASE for **webflux**

I have the following in `application.yml`

```yaml
management:
  server:
    port: ${MANAGEMENT_PORT:8889}
    servlet:
      context-path: "/management"
```

But `info` endpoint is mapped to `/actuator/info`, not to `/management/actuator/info`

```
2018-05-03 12:38:40.235  INFO 1 --- [           main] .b.a.e.w.r.WebFluxEndpointHandlerMapping : Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public org.reactivestreams.Publisher<org.springframework.http.ResponseEntity<java.lang.Object>> org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler.handle(org.springframework.web.server.ServerWebExchange)
```

**Comment by snicoll** [comment]
@n0mer that fact that it has `servlet` in the name should be a strong indicator that it will not work on environments that do not require the servlet API. If you have more questions, please ask on StackOverflow or come chat with us on Gitter.

**Comment by wilkinsona** [comment]
@n0mer What you're talking about is not a bug. It's by design that a servlet-specific property has no effect on a WebFlux application. It's also unrelated to this issue which is specifically about the `EndpointRequest` class that's used to configure Spring Security.

**Comment by gmcouto** [comment]
I'm still facing this jolokia endpoint issue... With the current 2.0.2.BUILD-SNAPSHOT build.
`
	//actuator specific version
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version:'2.0.2.BUILD-SNAPSHOT'
	compile group: 'org.springframework.boot', name: 'spring-boot-actuator', version:'2.0.2.BUILD-SNAPSHOT'
`
Shouldn't it be fixed?

**Comment by gmcouto** [comment]
Sample
[defect-actuator-jolokia.zip](https://github.com/spring-projects/spring-boot/files/1985632/defect-actuator-jolokia.zip)

**Comment by mbhave** [comment]
@gmcouto Thanks for the sample but this issue was about the matchers created by `EndpointRequest`. Your application does not have Spring Security on the classpath so it has nothing to do with the original issue. 

The jolokia issue you've noticed is a separate bug and I've opened an issue for it [here].(https://github.com/spring-projects/spring-boot/issues/13106)
