### ISSUE TITLE
Allow adding Micrometer Common Tags declaratively using the application properties

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-boot#12933]
To analyze [metrics](http://micrometer.io/docs/concepts) from different application instances, hosts, regions ..., additional (usually platform specific) [common tags](http://micrometer.io/docs/concepts#_common_tags) are required to allow distinguishing and aggregating the metrics across those different platforms, instances and environments...

While the [MeterRegistryCustomizer](https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/htmlsingle/#production-ready-metrics-getting-started) allows adding common tags, it implies that every time a new tag is need the target boot application will have to be re-compiled. Furthermore the boot app will have to hardcode, keep and broadcast the superset of all added tags, although only subset of those might be required in a given deployment environment.

This problem is visible in [Spring Cloud Data Flow](https://cloud.spring.io/spring-cloud-dataflow/) and [Spring Cloud Streams App Starters](https://cloud.spring.io/spring-cloud-stream-app-starters/) where certain SCDF specific tags (such as stream name, app guid, app type, instance id) are need for all  apps and each [Spring Cloud Deployer](https://github.com/spring-cloud/spring-cloud-deployer) requires its own specific tags as well.

Therefore a declarative mechanism for setting common tags at application deployment time is required.  For example by using application property like this: `management.metrics.tags=<my-tag-name>:<my-tag-value>`

**Comment by snicoll** [comment]
cc @jkschneider

**Comment by wilkinsona** [comment]
Adding property-based configuration for this makes sense to me (although I'd like some confirmation from @jkschneider before we implement anything). One change I'd make from the proposal above is to use a `Map<String, String>` for tags so that the properties would be like this:

```
management.metrics.tags.<my-tag-name> = <my-tag-value>
```

**Comment by jkschneider** [comment]
Looks good @wilkinsona. The [order](https://github.com/micrometer-metrics/micrometer/issues/561) of common tags is important to graphite users. Can we guarantee such an ordering within a props file?

**Comment by jkschneider** [comment]
Thanks for the detail @wilkinsona, and agree. If it were easy to accomodate Graphite users, great. If not, let's do what's best for the majority of folks going forward. Graphite isn't exactly gaining market share at this point.

**Comment by maximusfloydus** [comment]
+1 for following semantic versioning!   I create something similar for my projects already, just planning when I can deprecate it.

**Comment by manivkm** [comment]
I'm assuming, this feature is tracked as part of https://github.com/micrometer-metrics/micrometer/issues/646?

**Comment by jkschneider** [comment]
@ghost That's right!
