### ISSUE TITLE
Elastic existsById always returns true if record doesn't exist

### ISSUE THREAD

**Issue by lengoyvaerts** [spring-projects/spring-boot#12931]
Bug Report

I'm using Spring Boot 2.0.1-RELEASE.

I'm checking if a record exists by using the existsById(ID id) which uses the findById(ID id) method internally. If the record doesn't exist, it still returns true, because it performs the following check:

`return this.findById(id) != null;`

Now, findById(ID id) returns:

`Optional.ofNullable(this.elasticsearchOperations.queryForObject(query, this.getEntityClass()));`

which is never a null value.

Excerpt from the `ofNullable` java doc:

> @return an {@code Optional} with a present value if the specified value is non-null, otherwise an empty {@code Optional}

**Comment by snicoll** [comment]
@lengoyvaerts that Spring Data issue should be reported against [the Spring Data project](https://jira.spring.io/projects/DATAES) (as there isn't anything Spring Boot specific in your issue).
