### ISSUE TITLE
Jackson configuration does not work for WebTestClient

### ISSUE THREAD

**Issue by martinkalina** [spring-projects/spring-boot#12930]
I have a SpringBoot (2.0.1.RELEASE) reactive web application:
[test-web-client.tar.gz](https://github.com/spring-projects/spring-boot/files/1932321/test-web-client.tar.gz)

I set in application.properties:
`spring.jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS=true`

I try to deserialize float value into a map
It works when application is started and called through external REST client:

`curl --request PATCH \
  --url http://localhost:8080/ \
  --header 'content-type: application/json' \
  --data '{"x":1.5}'`

It does not work when WebTestClient is used:

`mvn test -Dtest=WebClientIT`

**Comment by snicoll** [comment]
Thanks for the sample but `WebTestClient` (and the webflux support) is part of Spring Framework. Please report this issue in [the appropriate tracker](https://jira.spring.io/projects/SPR)

**Comment by bclozel** [comment]
This is actually a Spring Boot question.
In this case, you've manually set up the `WebTestClient` which skips the auto-configuration done by Spring Boot (which you're trying to leverage by adding that configuration property).

Amending your sample with the following solves the issue:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureWebTestClient
public class TestWebClient {

	@Autowired
	WebTestClient webTestClient;
```
