### ISSUE TITLE
I have an idea.,from application.yml config of spring cors?

### ISSUE THREAD

**Issue by vnobo** [spring-projects/spring-boot#12937]
thank sir,i thank from application config cors,so I don't have to change it from the code.

Although you can now use custom implementations.

But I hope it benefits from native support.

thanks again

**Comment by snicoll** [comment]
@vnobo I am sorry but we don't use the tracker to ask questions or chat. Please join us on [gitter](https://gitter.im/spring-projects/spring-boot) if you want to discuss about a specific feature.
