### ISSUE TITLE
PageableHandlerMethodArgumentResolver not registered for WebMvcTest

### ISSUE THREAD

**Issue by ideaplugins** [spring-projects/spring-boot#12938]
While testing a controller that receives a `Pageable` parameter the test fails with this exception: `java.lang.NoSuchMethodException: org.springframework.data.domain.Pageable.<init>()`

If I register manually `PageableHandlerMethodArgumentResolver` then the test passes.

Spring version is 2.0.1.RELEASE

You can reproduce this behavior with this [project](https://github.com/ideaplugins/springbootissue1)

`FailingTest` reproduces the problem.

`PassingTest` shows the workaround.

**Comment by ideaplugins** [comment]
`AnotherPassingTest` shows a different and easier workaround

**Comment by snicoll** [comment]
@ideaplugins thanks for the sample, that is very useful. That's a duplicate of #9028

**Comment by ideaplugins** [comment]
@snicoll thanks for your quick response. I did a quick search before raising the issue and found nothing, my bad

**Comment by snicoll** [comment]
Thank you! Closing in favour of PR #13066
