### ISSUE TITLE
webflux does not work with stomp 

### ISSUE THREAD

**Issue by am-kram** [spring-projects/spring-boot#12932]
Spring boot w/  webflux seems neat and it works with websockets - when is webflux expected to work with stomp? ETA / story that is being worked on /patch would be super helpful.

**Comment by rstoyanchev** [comment]
There is a general intent to provide higher-level, messaging support aligned with WebFlux, but there is no specific target release yet. Note that we are researching gRPC [SPR-16358](https://jira.spring.io/browse/SPR-16358) and RSocket [SPR-16751](https://jira.spring.io/browse/SPR-16751) support, which is very closely related. 

If you have specific needs or requirements, please create a ticket in the [Spring Framework issue tracker](jira.spring.io/browse/SPR), and please provide as much context as possible. That would be very helpful.
