### ISSUE TITLE
Outdated wiki reference on Spring Boot with Java 9

### ISSUE THREAD

**Issue by jonathanlermitage** [spring-projects/spring-boot#12936]
[Spring-Boot-with-Java-9#testing](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9#testing) indicates `maven-surefire-plugin` version (`2.20.1`) introduced a regression when running tests, and we should downgrade to `2.20.0`.  
This issue is now [closed](https://issues.apache.org/jira/browse/SUREFIRE-1424), we should upgrade to `2.21.0`.

**Comment by snicoll** [comment]
Good catch. `2.21.0` is the default version for the upcoming `2.0.2.RELEASE` so that section is no longer necessary.
