### ISSUE TITLE
Pageable Always Adding From Entity to Sort Field Name

### ISSUE THREAD

**Issue by re-pvsr** [spring-projects/spring-boot#12948]
I am having the exact issue that is mentioned on this link [https://jira.spring.io/browse/DATAJPA-726](url)
It is mentioned as solved there, but I am getting the same issue, and a search on stackoverflow shows that the problem persists. I am using Spring 1.5.6.

Basically, I am doing a pagination on JOIN query as follows

`@Query(Select DISTINCT new com.api.dto.FilterDTO(c.id, p.id, CASE WHEN item.dateDue IS NOT NULL THEN item.dateDue ELSE p.dateDue END AS dateDue) FROM Customer c join c.productOrder p JOIN p.items item  ") `

And my page request is 
`PageRequest page = new PageRequest(0, 20, Direction.DESC, "dateDue");`

However, when i run this I keep getting the error
`could not resolve property: dateDue of: com.api.beans.Customer`

Evidently, it is searching for the sort field in the Customer Entity where it is not present.

So my question is 
1. Is Pagable not applicable when a JOIN is present ?
2. Then is the only alternative to use native sql query ? But the link provided above says, this has been solved and it works for Spring Data JPA -  I would like to continue using Spring Data JPA for this if it works - please help.

Thanks.

Note:There are other queries too on stackoverflow with similiar problems but no solutions. Links are as below
- [https://stackoverflow.com/q/43993952/6043669](url)

- [https://stackoverflow.com/q/5903774/6043669](url)

**Comment by wilkinsona** [comment]
Thanks for the report, but it's not clear why you've opened a Spring Boot issue. Judging by the link to DATAJPA-726, you seem to know that this is a Spring Data JPA problem and that Spring Data JPA has a separate issue tracker.

I would recommend upgrading to Spring Boot 1.5.12 and checking to see if your problem has been resolved. If it has not, I would recommend opening a Spring Data JPA JIRA ticket and providing a small sample that illustrates the problem.

**Comment by re-pvsr** [comment]
Thanks for that - sorry about the wrong posting.
