### ISSUE TITLE
Improve @ConditionalOnEnabledEndpoint to be used on any component

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12945]
If a component is solely used in the context of an endpoint, there is no easy way to make it available only said component is enabled. The main reason behind that is that the logic in `@ConditionalOnEnabledEndpoint` requires the return type to be an endpoint (or an extension).

**Comment by philwebb** [comment]
I quite like `Void.class` for class defaults that aren't considered.

**Comment by philwebb** [comment]
I think the change is sensible and I'm not too worried about the scenario you mentioned above.
