### ISSUE TITLE
ObjectMapper can not be autowired since 2.0.1 ,but 2.0.0 is ok

### ISSUE THREAD

**Issue by javamonkey** [spring-projects/spring-boot#12950]
I got  issues that ObjectMapper can not be Autowired since 2.0.1 ,but 2.0.0 is ok

Do i need create ObjectMapper by Myslef ,the following code is ok  in 2.0.0.RELEASE
```
@bean
@conditionalonbean(ObjectMapper.class)
public WebSimulate getWebSimulate(GroupTemplate gt,ObjectMapper objectMapper){
return new WebSimulate(gt,new ObjectMapperJsonUtil(objectMapper) );
}
```

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field webSimulate in com.bee.sample.ch4.controller.SimulateController required a bean of type 'org.beetl.ext.simulate.WebSimulate' that could not be found.
	- Bean method 'getWebSimulate' in 'WebSimulateConfig' not loaded because @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) did not find any beans of type com.fasterxml.jackson.databind.ObjectMapper


Action:

Consider revisiting the conditions above or defining a bean of type 'org.beetl.ext.simulate.WebSimulate' in your configuration.
```

**Comment by wilkinsona** [comment]
Nothing's changed in this area in Spring Boot 2.0.1 and an `ObjectMapper` should still be auto-configured. Perhaps you have a corrupted Jackson jar on the classpath? If you'd like us to investigate further, please provide a minimal and complete example that reproduces the problem.

**Comment by javamonkey** [comment]
@wilkinsona , this is my git project: 

https://github.com/javamonkey/SpringBoot2.0Test 

`@Configuration
@ConditionalOnMissingBean(WebSimulate.class)
@ConditionalOnBean(GroupTemplate.class)
public class WebSimulateConfig {

	@Bean	
	@ConditionalOnBean(ObjectMapper.class)
	public WebSimulate getWebSimulate(GroupTemplate gt,ObjectMapper objectMapper){
		return new WebSimulate(gt,new ObjectMapperJsonUtil(objectMapper) );
	}
}`

WebSimulateConfig  can wok well  in 2.0.0, but not since 2.0.1.  if i remove "@ConditionalOnBean(ObjectMapper.class)",it works.

**Comment by wilkinsona** [comment]
Thanks, but I can't find `WebSimulateConfig` in your repository. Can you please update the repository so that it contains all of the relevant code?

**Comment by javamonkey** [comment]
sorry, WebSimulateConfig  is not in Project but is one of class of the dependency of beetl-framework-starter . if i move this class to project as source code, work fine in bot 2.0.0 and 2.0.1

**Comment by wilkinsona** [comment]
If `WebSimulateConfig` is an auto-configuration class and it expects to consume the auto-configured `ObjectMapper`, then it needs to be processed after Boot's Jackson auto-configuration:

```java
@AutoConfigureAfter(JacksonAutoConfiguration.class)
```

If it's not an auto-configuration class, then, in addition to the above, it needs to become one so that `@ConditionalOnBean` will work reliably.
