### ISSUE TITLE
Unable to add request/response body to httptrace (actuator)  2.0.1-RELEASE

### ISSUE THREAD

**Issue by fat-panda** [spring-projects/spring-boot#12953]
<!--
Thanks for raising a Spring Boot issue. What sort of issue are you raising?

Currently not able to add request body/response body to HTTP tracing.
The option is not there in Include.class.

Previously we could extend WebRequestTraceFilter and add any options...

How do we do this in Spring Boot 2?

Thanks in advance :)

**Comment by wilkinsona** [comment]
HTTP tracing in 2.0 is intentionally less flexible than it was in 1.5. The flexibility of the implementation in 1.5 caused a number of problems and made it impossible to support on top of WebFlux, Spring MVC, and Jersey. Tracing the request and response body has never been supported out of the box. Support for tracing parameters was dropped as, when the request is POSTed form data, it requires reading the entire request body. If you want to capture one or both of these, and I would recommend that you don't, you should implement your own endpoint.

**Comment by wilkinsona** [comment]
@ahmedju This remains something that we do not want to support. Please see my comment above and the discussion on https://github.com/spring-projects/spring-boot/issues/23907 for further details.

**Comment by ahmedju** [comment]
> @ahmedju This remains something that we do not want to support. Please see my comment above and the discussion on #23907 for further details.

Thanks for reply.
Excuse me is there any way, any way, to add new endpoint to view request/response for Actuator?
custom Bean?
