### ISSUE TITLE
Remove code deprecated in 2.0

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12962]
For instance, #12655

**Comment by vpavic** [comment]
Sorry to comment on a closed issue, but isn't this a bit too aggressive having [semver](https://semver.org/#how-should-i-handle-deprecating-functionality) guidelines in mind?

**Comment by wilkinsona** [comment]
Also, Spring Boot isn't strictly semantically versioned. Rather, we aim for a n.n.x release to be a drop-in replacement, and n.x releases to be easy to adopt. We consider the deprecation period in 2.0.x to make it sufficiently easy for people to move from 2.0.x to 2.x in this case.
