### ISSUE TITLE
Enhancement to Spring devtools restart for the Gradle composite build use case

### ISSUE THREAD

**Issue by edpeng** [spring-projects/spring-boot#12974]
Gradle [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) provides the ability to build a project's dependencies in place of its declared binary dependency.

This enhancement is for Spring devtools file system watcher to include the folder of the jars specified in `restart.include` so that when Gradle automatically rebuilds the jar (via `build --continuous`), Spring devtools will detect the change and restart.

This change will be a lot easier to maintain than to specify the folders containing the jars in `spring.devtools.restart.additional-paths` which is not easily portable. This enhancement from a project configuration perspective will work by just specifying the jars in the gradle dependencies block and in spring-devtools.properties `restart.include`.

### Change suggestion

More analysis can be found [here](https://github.com/spring-projects/spring-boot/issues/12869). In summary, one suggestion is to change ClassPathFolders.java so that if the file is a jar then it will include the jar's folder instead of excluding it because it does not ends with "/".

```
	private void addUrl(URL url) {
		if (url.getProtocol().equals("file") && url.getPath().endsWith("/")) {
			try {
				this.folders.add(ResourceUtils.getFile(url));
			}
			catch (Exception ex) {
				logger.warn("Unable to get classpath URL " + url);
				logger.trace("Unable to get classpath URL " + url, ex);
			}
		}
	}
```

A sample composite build project can be found [here](https://github.com/edpeng/devtools-restart-with-jar-dependencies).

**Comment by wilkinsona** [comment]
Thanks, but this is really a rewording of #12869 where I said the following:

> Watching .jar files would add complexity and would also be of limited benefit as you'd have to rely on something recompiling and packaging the jar's contents before a change could be picked up

This proposal doesn't address those concerns. If you are in position to make changes to some code and have Gradle build it, presumably you are also in a position to make change to that code and have your IDE build it. This has two advantages:

1. It's less cumbersome for you as you don't have to switch from your development environment to Gradle to build the code.
2. It achieves the desired result without adding complexity to DevTools.
