### ISSUE TITLE
Provide access to the CopySpec for BOOT-INF of BootJar as Gradle's War task does for WEB-INF

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13000]
Gradle's `War` task has methods for working with the `WEB-INF` `CopySpec`:

- `getWebInf()`
- `webInf(Action<CopySpec>)`
- `webInf(Closure)`

`BootJar` has no such methods for its `CopySpec` for `BOOT-INF` which is analogous to the `War` task's `CopySpec` for `WEB-INF`. When should add both `getWebInf()` and `webInf(Action<CopySpec>)`. I don't think there's any need for `webInf(Closure)` as Groovy can happily use the `Action` variant.

**Comment by wilkinsona** [comment]
If there are no objections, I'd like to add the missing methods in 2.0.x as they, arguably, should have been there from the outset.

**Comment by wilkinsona** [comment]
Yeah, I think they’d be:

- `getBootInf()`
- `bootInf(Action<CopySpec>)`

**Comment by philwebb** [comment]
+1 from me then

**Comment by wilkinsona** [comment]
And now I see why you asked. I used the wrong names in the opening description. Sorry for the confusion.

**Comment by wilkinsona** [comment]
I'm not sure this is possible without using internal API. Gradle's `War` task calls an internal `addChild()` method on its `CopySpec`. I've reached out to the Gradle team for some guidance. Moving back out to 2.0.x until we know what's possible.

**Comment by wilkinsona** [comment]
This isn't possible without using internal API so I don't think we should do it. I've opened https://github.com/gradle/gradle/issues/5239 to see if the Gradle team can provide the necessary API. In the meantime, I'm going to decline this issue. We can re-open it if Gradle provides the necessary API at some point in the future.

**Comment by wilkinsona** [comment]
Turns out that this is possible after all.
