### ISSUE TITLE
It is unclear that configuring a JNDI name for the auto-configured mail sender's session causes property-based configuration to back off

### ISSUE THREAD

**Issue by iyerha** [spring-projects/spring-boot#13026]
The following bean definition in MailSenderAutoConfiguration does not set any mail properties when configuring the JavaMailSenderImpl using the session, especially the default encoding. This causes any message created via the MimeMessageHelper to generate the wrong content type.

```
@Bean
public JavaMailSenderImpl mailSender() {
	JavaMailSenderImpl sender = new JavaMailSenderImpl();
	if (this.session != null) {
		sender.setSession(this.session);
	}
	else {
		applyProperties(sender);
	}
	return sender;
}
```

**Comment by wilkinsona** [comment]
Thanks for the report. Looks like this is an oversight from when the JNDI support was [added](https://github.com/spring-projects/spring-boot/commit/28cb13c31d3a33c5c728d8db0aa525f16e9330f8). As far as I can tell, the only properties that shouldn't be applied when using the `Session` from JNDI are the JavaMail properties (calling `setJavaMailProperties(Properties)` sets the season to null).

**Comment by snicoll** [comment]
Closing in favour of PR #13050

**Comment by iyerha** [comment]
AFAIK the only way to set an encoding on the session is to set the 'mail.mime.charset' property. However, this is never retrieved by the JavaMailSenderImpl (in contrast, the 'mail.transport.protocol' is processed by getTransport( ) from the session). So this doesn't work.
I have worked around it by post processing the bean and setting the default encoding in code. It would be nicer to have this work by configuration, though.

**Comment by iyerha** [comment]
I guess in case of JNDI you would have to set the 'mail.mime.charset' system property as the default encoding.

**Comment by snicoll** [comment]
@iyerha That's correct, the encoding is the only thing that is specific to `JavaMailSender` that we can't get from the `Session` so we should use that information and clarify what properties get ignored.
