### ISSUE TITLE
Web-Flux: Strings are getting concatenated!

### ISSUE THREAD

**Issue by Montrazul** [spring-projects/spring-boot#13020]
Spring-Boot version: 2.0.0.RELEASE

Actually im not really sure if this behaviour is a bug or if it is intended to be like that.
Im sending strings via the web client to an REST-Endpoint:

```
List<String> list = new ArrayList<>();
list.add("1");
list.add("2");
list.add("3");
list.add("4");
	
client.post()
    .uri("some endpoint")
    .accept(MediaType.APPLICATION_STREAM_JSON)
    .contentType(MediaType.APPLICATION_STREAM_JSON)
    .body(Flux.fromIterable(list), String.class)
    .exchange().block();
```

on the endpoint we are doing:

`flux.log().subscribe(element -> doStuffWithElement(element));`

**What I expect:**

> 20:25:19.550 [main] INFO  reactor.Flux.Array.1 - | onSubscribe([Synchronous Fuseable] FluxArray.ArraySubscription)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | request(unbounded)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onNext(1)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onNext(2)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onNext(3)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onNext(4)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onComplete()

**What I actually get:**

> 20:25:19.550 [main] INFO  reactor.Flux.Array.1 - | onSubscribe([Synchronous Fuseable] FluxArray.ArraySubscription)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | request(unbounded)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onNext(1234)
> 20:25:19.553 [main] INFO  reactor.Flux.Array.1 - | onComplete()

This is happening only with `String`. I also tested `Integer`, `Double`, `Long`.
A workaround is to wrap the string into a wrapper object:

```
List<Wrapper> list = new ArrayList<>();
list.add(new Wrapper("1"));
list.add(new Wrapper("2"));
....
```

With this wrapper I get the expected behaviour.

**Comment by bclozel** [comment]
Hi, there's nothing we can do here since it's actually a Spring Framework issue. It's been raised already as [SPR-16260](https://jira.spring.io/browse/SPR-16260) and considered as working as designed. This has been document in the [Spring Framework reference docs](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-jackson).
