### ISSUE TITLE
CacheAutoConfiguration triggers early initialization of cache components

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13038]
While working on a feature to demonstrate how to swap a `CacheManager` in a BPP, I found that the cache auto-configuration was triggering early initializations.

This basically boil down to `CacheManagerValidator` whose purpose is to throw an exception "early enough" if no `CacheManager` could be auto-configured. Removing that locally was enough to fix the problem

**Comment by jtktam** [comment]
Hi, has this fix been merged to 2.0.2.RELEASE? thanks

**Comment by snicoll** [comment]
@jtktam if you click on the link above your comment, it states in which tags the fix is included. Yes, it's included (we always merge forward so whatever is in `1.5` is in `2.0` and will be in `2.1`).

**Comment by jtktam** [comment]
I think I am still running into the early initialization bug in 2.0.2.RELEASE, that's why i wanted to confirm it's merged forward

**Comment by snicoll** [comment]
@jtktam we don't use the tracker for questions (see [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues)). Feel free to come chat with us on Gitter.
