### ISSUE TITLE
The bug of email

### ISSUE THREAD

**Issue by fuyongde** [spring-projects/spring-boot#13034]
When uploading a Chinese name attachment, if the attachment name is too long, the receiver received the attachment is garbled.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by fuyongde** [comment]
I write a method like this:
```     
      @Autowired private JavaMailSender javaMailSender;
      @Autowired private MailProperties mailProperties;
    
      @Async
      public void sendMailWithFile(String[] toArray, String[] ccArray, String subject, String text, File[] files) {
        try {
          MimeMessage mimeMessage = javaMailSender.createMimeMessage();
          MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, true);
          for (String to : toArray) {
            helper.addTo(to);
          }
          if (ccArray != null && ccArray.length > 0) {
            for (String cc : ccArray) {
              helper.addCc(cc);
            }
          }
          if (files != null && files.length > 0) {
            for (File file : files) {
              FileDataSource fileDataSource = new FileDataSource(file);
              helper.addAttachment(file.getName(), fileDataSource);
            }
          }
          helper.setFrom(mailProperties.getUsername());
          helper.setSubject(subject);
          helper.setText(text);
          javaMailSender.send(mimeMessage);
        } catch (Exception e) {
          if (logger.isInfoEnabled()) {
            logger.error("send fail!!! to：{}，subject：{}，content：{}", toArray, subject, text);
          }
        }
      }
```

When I upload a Chinese attachment with a very long name, the attachment in the email received by the recipient will become garbled and the suffix name will be '.bin'.However, with the 1.4.7 version of javax.mail, the problem will be solved.

**Comment by wilkinsona** [comment]
> However, with the 1.4.7 version of javax.mail, the problem will be solved.

That sounds like a bug in the version of JavaMail that you're using. If you'd like to pursue this, you should report the issue to that project.

**Comment by fuyongde** [comment]
Spring-boot-starter-mail contains a new version of javax.mail (1.5.6), I excluded this and introduced the old version (1.4.7) to solve this problem.This problem occurs when the Chinese name of the attachment exceeds 10 Chinese characters. But still thank you.
