### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/expression/spel/support/SimpleEvaluationContext

### ISSUE THREAD

**Issue by Stefku** [spring-projects/spring-boot#13044]
Version: spring-boot 1.5.12.RELEASE

Problem: Navigating to a html resource that's not available, I get an Exception

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/expression/spel/support/SimpleEvaluationContext
	at org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$ExpressionResolver.getContext(ErrorMvcAutoConfiguration.java:279)
	at org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$ExpressionResolver.<init>(ErrorMvcAutoConfiguration.java:275)
	at org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$SpelView.render(ErrorMvcAutoConfiguration.java:225)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)

```

I looked into the dependency hierarchy:
spring-boot-starter-security: 1.5.12.RELEASE uses 
spring-security-web: 4.2.3.RELEASE 
uses spring-expression: 4.3.9.RELEASE

The class SimpleEvaluationContext is not available in spring-expression: 4.3.9.RELEASE. In later versions it is.

When I add manually a newer version the error disappears

```
<dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-expression</artifactId>
	<version>4.3.16.RELEASE</version>
</dependency>
```

**Comment by snicoll** [comment]
The jar got corrupted when you upgraded your app. Please clear you maven cache and download that jar again. If that still does not work, please share a sample that reproduces the problem and we can reopen.

**Comment by Stefku** [comment]
Yes, thanks. We upgraded spring-boot, but not spring-cloud.

Wondering, how I can force kind of check that this cannot happen any more..

**Comment by snicoll** [comment]
> Yes, thanks. We upgraded spring-boot, but not spring-cloud.

That must be unrelated to the issue you've described. If you have more questions, ask on StackOverflow or Gitter.

**Comment by dmaidaniuk** [comment]
I used recommended config for Cloud starter Edgware.SR3 from http://projects.spring.io/spring-cloud/
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.13.RELEASE</version>
</parent>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Edgware.SR3</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
    <dependency>
        <groupId></groupId>
        <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
        <groupId></groupId>
        <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>
</dependencies>
```
And I got exactly same exception as described in this issue. I download [spring-expression version 4.3.14.RELEASE](https://mvnrepository.com/artifact/org.springframework/spring-expression/4.3.14.RELEASE) which goes with Boot 1.5.13 and see that there is no such class as `org/springframework/expression/spel/support/SimpleEvaluationContext` in it. This class available on mentioned version `4.3.16.RELEASE`. So it is not an issue with corrupted JAR but rather issue with corrupted starter config.

**Comment by snicoll** [comment]
`SimpleEvaluationContext` was [added in `4.3.15.RELEASE`](https://github.com/spring-projects/spring-framework/blob/master/spring-expression/src/main/java/org/springframework/expression/spel/support/SimpleEvaluationContext.java#L81) so the fact you can't find it in `4.3.14.RELEASE` is perfectly normal.

Spring Boot `1.5.13` [uses Spring Framework `4.3.17.RELEASE`](https://github.com/spring-projects/spring-boot/blob/v1.5.13.RELEASE/spring-boot-dependencies/pom.xml#L154).

As requested above already, if you have more dependency management questions, ask on StackOverflow or Gitter.

**Comment by dmaidaniuk** [comment]
@snicoll ,
That's what command `mvn dependency:tree` said:
```
INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.5.13.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.5.13.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.31:compile
[INFO] |  |  |  \- org.apache.tomcat:tomcat-annotations-api:jar:8.5.31:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.31:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.31:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.6.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.10:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.14.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.14.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.3.14.RELEASE:compile
```

**Comment by snicoll** [comment]
It's no surprise it states that given your project uses the wrong version of Spring Framework. I can't guess what the problem is as you haven't shared any detail about your build. Perhaps you can start by creating a project on start.spring.io and see the difference with yours?
