### ISSUE TITLE
Upgrade to Ehcache 2.10.5

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13056]

**Comment by wilkinsona** [comment]
2.10.5 appears to be broken. Its `ehcache-root` module references version 2.21 of `ehcache-parent` which, at the time of writing, isn't available in Maven Central.

**Comment by snicoll** [comment]
The ehcache release issue is being tracked in [EHC-1152](https://jira.terracotta.org/jira/browse/EHC-1152)
