### ISSUE TITLE
Default maven filtering does not apply to bootstrap.yml

### ISSUE THREAD

**Issue by Laures** [spring-projects/spring-boot#13062]
With the spring-boot default config (parent-pom) i can only use maven filtering in application-properties or -yml files but not the spring-cloud-config bootstrap.yml.

I'm my case i want to use cloud-config together with eureka and i want the metadata-map of eureka to include the project version so my bootstrap.yml looks like this:

```
spring:
    application:
        name: gateway-service
    profiles:
        active: staging
    cloud:
        config:
          discovery:
            service-id: service-registry
            enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    metadata-map:
      profile: ${spring.profiles.active}
      version: ${info.project.version}

info:
  project:
    version: @project.version@
```

i did add the bootstrap.yml to the list of filtered resources but filtering it by default sounds useful to me.

**Comment by spencergibb** [comment]
If you used `spring.config.name=myconfig`, so boot was looking for `myconfig.{yml|properties}` you'd be in a similar situation.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we've decided that we don't want to do this for the reasons described above.
