### ISSUE TITLE
Configuration metadata doc has a reference to a private class

### ISSUE THREAD

**Issue by jmkgreen** [spring-projects/spring-boot#13060]
See https://docs.spring.io/spring-boot/docs/1.5.11.RELEASE/reference/html/configuration-metadata.html in section _B.3.1. Nested Properties_ the nested class `Host` is marked `private` yet my application will not boot until my equivalent class is marked `public`.

I do not know if this also applies to 2.x.

Stack trace when marked `private:

```java
Caused by: java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class com.foo.RepliesConfiguration$Queues with modifiers "private"
```

**Comment by snicoll** [comment]
Good catch, thank you. Yes, it applies to 2.0 most probably.

**Comment by snicoll** [comment]
I take this back. I can bind to a `private static class` in both `1.5.x` and `2.0.x`.

I will update the documentation regardless as it is wrong to recommend `private` there but you may want to review your sample and provide a better description of the problem. Sharing a sample that demonstrates the issue would be ideal.

**Comment by jmkgreen** [comment]
Interesting. In my 1.5 application I can get the stack trace with a private nest class. If I copy this source into an otherwise empty (-web starter only) 2.x application that one boots fine.

**Comment by snicoll** [comment]
To be clear, this works for me in 1.5 as well. If you have a simple sample, I'd like to be able to run it myself and see the exception.

**Comment by jmkgreen** [comment]
Yep if I drop the sample down to 1.5.11.RELEASE it breaks immediately. I will shove the sample into GitHub.

**Comment by snicoll** [comment]
@jmkgreen you don't need to have a setter for a nested object. I've restructure the code as follows

```
private final Nested nested = new Nested();

public Nested getNested() {
    return nested;
}

private static class Nested { ... }
```

and it works both in 1.5 and 2.0. Also, please note that add `@Configuration` on such object is a bad practice (it's not a configuration class, it does not contribute any beans). 

Alright, now that's clarified, I'll update the doc you've mentioned, thank you.

**Comment by jmkgreen** [comment]
So the setter is a bit of a red herring (it may for all I know alter the initialisation behaviour) - I really needed the field level initialisation. And that's the bit missing from the documentation. Well spotted to yourself, Sir!

And yes, I've replaced `@Configuration` with `@Component` since I need to inject this elsewhere.

**Comment by snicoll** [comment]
> And that's the bit missing from the documentation.

Not really. There is nothing wrong with having a getter/setter for that stuff if you want to instantiate the class on demand (or if you want to easily detect that no attribute of the nested class was set). The 
[documentation for `@ConfigurationProperties`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) has an example of `Security` nested namespace with no setter.
