### ISSUE TITLE
Document url pattern syntax for Servlet and Filter RegistrationBean addUrlPatterns()

### ISSUE THREAD

**Issue by rehfeldchris** [spring-projects/spring-boot#13080]
I think it would be helpful to improve the javadoc for `org.springframework.boot.web.servlet.FilterRegistrationBean .addUrlPatterns()`  so that it specifies the url pattern syntax. This SO question ( https://stackoverflow.com/questions/44769047/spring-security-how-to-use-multiple-url-patterns-in-filterregistrationbean ) implies at least some people have made the same mistake as me - thinking that addUrlPatterns() takes Ant matcher patterns, but it doesn't. It would be nice if it specified the syntax, and maybe even specifically warned that it's not the Ant matcher style commonly used by spring security. I imagine a lot of users who use this class method also use spring security, and so are likely to make the same mistake and assume the same url pattern syntax, which can manifest as very subtle bugs. 

Thanks!

**Comment by wilkinsona** [comment]
Updating the javadoc to mention that the syntax is the one defined in the Servlet spec makes sense, I think.
