### ISSUE TITLE
X-Application-Context HTTP response header exposes internal server port

### ISSUE THREAD

**Issue by gmarziou** [spring-projects/spring-boot#1308]
Using spring-boot 1.1.4.

Spring-boot-actuator's EndpointWebMvcAutoConfiguration.ApplicationContextFilterConfiguration registers a Filter that adds a response header X-Application-Context that contains the application id but it does not remove it and so the browser gets it.

By default, the application id is something like this "application:int:8080" which is a concatenation of the "application" (?), profile and server port.

In the scenario where the application is behind a reverse proxy, I find it a bit unsafe to expose the internal port number even though it should be not accessible from the external world.

Is there a way to disable this behavior without breaking actuator?

**Comment by pires** [comment]
Also, `management.add-application-context-header: false` disables this completely.
