### ISSUE TITLE
Update Spring-Boot documention considering new scopes, e.g. "webDriver" Scope

### ISSUE THREAD

**Issue by rfelgent** [spring-projects/spring-boot#13093]
Hello everyone,

first of all: great job for your spring-boot !!!

I would like to request an update of the Spring-Boot documentation considering scopes, that are part of Spring-Boot but not Spring-Core itself, e.g. "webDriver" (There might be other scopes? I do not know..)

I had the same problem as described in https://github.com/spring-projects/spring-boot/issues/7454 (https://github.com/spring-projects/spring-boot/issues/6641) My own lifcecycle of webDriver was interrupted/overwritten by Spring Boot. It took a while for me to figure out this specific behaviour of Spring-Boot autoconfigure.

I can create a PR. Please guide me in the right direction what should be updated:

- Spring Boot reference docu?
- WebDriverScope.class ? WebDriverTestExecutionListener.class?

Best regards

**Comment by philwebb** [comment]
I'm not sure that we should add a dedicated section for scopes. The `webDriver` scope is the only one that we actually add and it's only used in tests. We do already have a small note about it in the [Auto-configured Spring MVC Tests](https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-mvc-tests) section of the docs. I'll expand that just to add a warning.
