### ISSUE TITLE
why EnvironmentAware init order is diff in windows&linux

### ISSUE THREAD

**Issue by dtssv** [spring-projects/spring-boot#13091]
I have a config class implements EnvironmentAware。
`
@Configuration
@PropertySource(value = {"classpath:mq.properties","classpath:sms.properties"})
public class MQConfig implements EnvironmentAware {
    private Environment environment;

    @Override
    public void setEnvironment(Environment environment) {
        this.environment = environment;
    }
    @Bean
    public AmqpTemplate getTemplate(){
        RabbitTemplate template = new RabbitTemplate();
        template.setQueue(environment.getProperty("smsQueue"));
        template.setRoutingKey(environment.getProperty("smsQueue"));
        template.setEncoding("utf-8");
        template.setConnectionFactory(getConnectionFactory());
        template.setMessageConverter(getMessageConvert());
        return template;
    }
}
`

this code work well on windows，but when i use linux，this code start error，it report nullpointexception，debugg find `getTemplate` init before then `setEnvironment`。
so i add `@Autowired` at `environment` and it work well too. why have this diff with windows and linux.
3q!

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, it’s impossible to tell exactly why this is happening from the information provided. I suspect it’s an early initialisation problem.

You could try replacing the use of `EnvironmentAware` with constructor injection of the `Environment`. That we enforce that it’s injected before the instance `@Bean` method is called.

If the above suggestion does not help, please provide a minimal sample that reproduces the problem and we can investigate further.

**Comment by dtssv** [comment]
i tried again，and  all ways work well，and 3q again。
