### ISSUE TITLE
Provide an Actuator endpoint for Spring Security filter chains

### ISSUE THREAD

**Issue by marcelvdh** [spring-projects/spring-boot#13104]
It would be nice to have a report of the Spring Security filter chains that are defined for the Web Servlet stack and Web Reactive stack. 

An example of the JSON produced (only includes the Servlet stack)

GET `/actuator/filterchains`:

```json
{
  "filterChains": {
    "servlets": [
      {
        "requestMatcher": "Ant [pattern='/web1/**']",
        "filterDetails": [
          {
            "className": "org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter"
          },
          {
            "className": "org.springframework.security.web.context.SecurityContextPersistenceFilter"
          },
          {
            "className": "org.springframework.security.web.header.HeaderWriterFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.logout.LogoutFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter"
          },
          {
            "className": "org.springframework.security.web.savedrequest.RequestCacheAwareFilter"
          },
          {
            "className": "org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.AnonymousAuthenticationFilter"
          },
          {
            "className": "org.springframework.security.web.session.SessionManagementFilter"
          },
          {
            "className": "org.springframework.security.web.access.ExceptionTranslationFilter"
          }
        ]
      },
      {
        "requestMatcher": "OrRequestMatcher [requestMatchers=[Ant [pattern='/web2/**'], Ant [pattern='/web3/**']]]",
        "filterDetails": [
          {
            "className": "org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter"
          },
          {
            "className": "org.springframework.security.web.context.SecurityContextPersistenceFilter"
          },
          {
            "className": "org.springframework.security.web.header.HeaderWriterFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.logout.LogoutFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter"
          },
          {
            "className": "org.springframework.security.web.savedrequest.RequestCacheAwareFilter"
          },
          {
            "className": "org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter"
          },
          {
            "className": "org.springframework.security.web.authentication.AnonymousAuthenticationFilter"
          },
          {
            "className": "org.springframework.security.web.session.SessionManagementFilter"
          },
          {
            "className": "org.springframework.security.web.access.ExceptionTranslationFilter"
          }
        ]
      }
    ],
    "reactive": []
  }
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Can you please describe how you'd use the information that's exposed by the endpoint?

The Actuator's primarily aimed at provided information that's useful when an application is running in production. I'm wondering if the information above would be more commonly useful at development time. As such, it may belong in a different form in Boot's DevTools or in Spring Security.

/cc @rwinch

**Comment by marcelvdh** [comment]
@wilkinsona Thank you for your response. I use the information in the same way as I currently use the information that is provided by the `mappings` actuator. The data from both these actuators gives me a good overview of the RequestMapping paths, Filters and the Spring Security configuration (Matchers and Spring Security filters) of a Spring Boot application.

I understand your point of view that this information is potentially only useful during development but I think that the same could be said about the data provided by the `mappings` actuator.

**Comment by wilkinsona** [comment]
@rwinch What's your take on this please?

**Comment by philwebb** [comment]
We'd definitely need some changes to the Spring Security matchers so that they have a nice `toString()`

**Comment by rwinch** [comment]
@wilkinsona I'm not sure how to go about doing this without Boot needing to dig into the internals. As it stands you can obtain the mappings from [FilterChainProxy.getFilterChains()](https://github.com/spring-projects/spring-security/blob/71986e5f424ed44c475d21af54a8cf51962b9bdd/web/src/main/java/org/springframework/security/web/FilterChainProxy.java#L249). However, the `SecurityFilterChain` API does not expose the underlying `RequestMatcher` but the [DefaultSecurityFilterChain](https://github.com/spring-projects/spring-security/blob/71986e5f424ed44c475d21af54a8cf51962b9bdd/web/src/main/java/org/springframework/security/web/DefaultSecurityFilterChain.java#L48) implementation does allow accessing the `RequestMatcher`. I'm not sure that relying on the specific implementation is something I would recommend.

@philwebb Many of the `RequestMatcher`s have a defined `toString()`. If you find some that need improvements, please don't hesitate to create an issue or PR.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-security/issues/5446 for four request matcher implementations that do not override `toString()`.

**Comment by wilkinsona** [comment]
Thanks, @rwinch. How internal do you consider `DefaultSecurityFilterChain` to be? If its public API is stable, we could depend on it defensively and make the endpoint return nothing for the matchers if a different`SecurityFilterChain` implementation is being used.

If we did that, things wouldn't be too dissimilar to the mappings endpoint where we expose different information for different handler types. However, in the mappings case, we can group the mappings by type making the structure of each part of the response predictable. With the security filter chains, I don't think we could do that as their ordering is important so we'd want to keep them all together, irrespective of the concrete type.

There's also a question of how useful a `toString()` on the top-level matcher would actually be. The output isn't likely to be particularly amenable to parsing. If we're not careful, we're in danger of recreating the problems that we had with the mappings endpoint in 1.5 and that we fixed in 2.0.

**Comment by marcelvdh** [comment]
@rwinch @wilkinsona There is also no getFilterChains() method on the `WebFilterChainProxy` that is used by the web reactive stack.

**Comment by rwinch** [comment]
@wilkinsona 

> How internal do you consider DefaultSecurityFilterChain to be? 

I probably should have phrased this differently. It isn't considered internal, but just implementation specific. The API is quite stable, but you might run into different implementations.

**Comment by wilkinsona** [comment]
Good point, @marcelvdh. That's an interesting difference in the two APIs in Spring Security. There's also no accessor for the matcher on `MatcherSecurityWebFilterChain`.

I've labelled this one as blocked for now as, if we decide to do something here, we'd want to be able to do it for both web stacks which will require API changes in Spring Security.

@rwinch As we're not completely sold on the value of this change, I don't think this issue should drive API changes in Spring Security. However, if you think the changes that would be needed have merit in their own right then we can of course consider building on top of them.

**Comment by philwebb** [comment]
We'll close this for now. If Spring Security make the necessary changes we can revisit.

**Comment by rwinch** [comment]
@philwebb Can you please create  or point to a ticket in Spring Security on the necessary changes?

**Comment by wilkinsona** [comment]
@rwinch As I said above, we don't think that this issue should drive any changes in Spring Security:

> As we're not completely sold on the value of this change, I don't think this issue should drive API changes in Spring Security. However, if you think the changes that would be needed have merit in their own right then we can of course consider building on top of them.

If those changes happen organically then we'll build on top of them, but I don't think Boot should be lodging a request for them.

**Comment by rwinch** [comment]
@wilkinsona I guess I feel like this is an organic request by a user wanting a feature that Boot cannot implement unless Spring Security makes changes.

**Comment by wilkinsona** [comment]
Perhaps @marcelvdh can open one if they're keen to see this functionality? Even if we don't do anything in Boot, some changes to Security would allow them to implement their own endpoint.

**Comment by marcelvdh** [comment]
I'm okay with things as they stand. As @wilkinsona mentions he feels the proposed changes don't add that much value to Spring Boot as an actuator and the reasons make sense to me.

@rwinch I'd be happy to create a ticket for Spring Security `getFilterChains()` that is missing on [WebFilterChainProxy.java](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/server/WebFilterChainProxy.java). on the Web Reactive stack. This method does exist in [FilterChainProxy.java](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/FilterChainProxy.java) in the Web Servlet stack.
