### ISSUE TITLE
use Boot Embedded Undertow Support pinpoint apm?

### ISSUE THREAD

**Issue by peachyy** [spring-projects/spring-boot#13110]
use Boot Embedded Undertow Support pinpoint apm

At present, there is no support for any plan because pinpoint team is not familiar with Undertow.
So come spring-boot open this issue

**Comment by wilkinsona** [comment]
There's an existing [Pinpoint issue](https://github.com/naver/pinpoint/issues/1563) for Undertow support.

**Comment by peachyy** [comment]
ok thank!

**Comment by peachyy** [comment]
@wilkinsona ok thank!
