### ISSUE TITLE
NoSuchBeanDefinitionException when using AOP

### ISSUE THREAD

**Issue by mhmpl** [spring-projects/spring-boot#1311]
Hey guys! I tried to add Aspects (for Logging) to my Spring Boot application. However, since created an aspect, my application fails to start (because of `NoSuchBeanDefinitionException`).

I followed the aop example (adding spring-boot-starter-aop dependency and annotating a class with `@Aspect` and `@Component`):

    @Aspect
    @Component
    public class ValidatorLogging {

        @Before( "execution(* myapp.validator.AffiliateValidator.validate(..))" )
        public void logBefore( JoinPoint joinPoint ) {
            System.out.println( "Hello" );
        }
    }

Im using the `1.1.5.BUILD-SNAPSHOT` build but already tried the latest release as well.

    +--- org.apache.commons:commons-lang3:3.3.2
    +--- com.google.guava:guava:17.0
    +--- org.springframework.boot:spring-boot-starter: -> 1.1.5.BUILD-SNAPSHOT
    |    +--- org.springframework.boot:spring-boot:1.1.5.BUILD-SNAPSHOT
    |    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    \--- org.springframework:spring-context:4.0.6.RELEASE
    |    |         +--- org.springframework:spring-aop:4.0.6.RELEASE
    |    |         |    +--- aopalliance:aopalliance:1.0
    |    |         |    +--- org.springframework:spring-beans:4.0.6.RELEASE
    |    |         |    |    \--- org.springframework:spring-core:4.0.6.RELEASE
    |    |         |    \--- org.springframework:spring-core:4.0.6.RELEASE
    |    |         +--- org.springframework:spring-beans:4.0.6.RELEASE (*)
    |    |         +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |         \--- org.springframework:spring-expression:4.0.6.RELEASE
    |    |              \--- org.springframework:spring-core:4.0.6.RELEASE
    |    +--- org.springframework.boot:spring-boot-autoconfigure:1.1.5.BUILD-SNAPSHOT
    |    |    \--- org.springframework.boot:spring-boot:1.1.5.BUILD-SNAPSHOT (*)
    |    +--- org.springframework.boot:spring-boot-starter-logging:1.1.5.BUILD-SNAPSHOT
    |    |    +--- org.slf4j:jcl-over-slf4j:1.7.7
    |    |    |    \--- org.slf4j:slf4j-api:1.7.7
    |    |    +--- org.slf4j:jul-to-slf4j:1.7.7
    |    |    |    \--- org.slf4j:slf4j-api:1.7.7
    |    |    +--- org.slf4j:log4j-over-slf4j:1.7.7
    |    |    |    \--- org.slf4j:slf4j-api:1.7.7
    |    |    \--- ch.qos.logback:logback-classic:1.1.2
    |    |         +--- ch.qos.logback:logback-core:1.1.2
    |    |         \--- org.slf4j:slf4j-api:1.7.6 -> 1.7.7
    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    \--- org.yaml:snakeyaml:1.13
    +--- org.springframework.boot:spring-boot-starter-logging: -> 1.1.5.BUILD-SNAPSHOT (*)
    +--- org.springframework.boot:spring-boot-starter-data-jpa: -> 1.1.5.BUILD-SNAPSHOT
    |    +--- org.springframework.boot:spring-boot-starter:1.1.5.BUILD-SNAPSHOT (*)
    |    +--- org.springframework.boot:spring-boot-starter-aop:1.1.5.BUILD-SNAPSHOT
    |    |    +--- org.springframework.boot:spring-boot-starter:1.1.5.BUILD-SNAPSHOT (*)
    |    |    +--- org.springframework:spring-aop:4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    +--- org.aspectj:aspectjrt:1.8.1
    |    |    \--- org.aspectj:aspectjweaver:1.8.1
    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    +--- org.springframework.boot:spring-boot-starter-jdbc:1.1.5.BUILD-SNAPSHOT
    |    |    +--- org.springframework.boot:spring-boot-starter:1.1.5.BUILD-SNAPSHOT (*)
    |    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    +--- org.springframework:spring-jdbc:4.0.6.RELEASE
    |    |    |    +--- org.springframework:spring-beans:4.0.6.RELEASE (*)
    |    |    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    |    \--- org.springframework:spring-tx:4.0.6.RELEASE
    |    |    |         +--- org.springframework:spring-beans:4.0.6.RELEASE (*)
    |    |    |         \--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    +--- org.apache.tomcat:tomcat-jdbc:7.0.54
    |    |    |    \--- org.apache.tomcat:tomcat-juli:7.0.54
    |    |    \--- org.springframework:spring-tx:4.0.6.RELEASE (*)
    |    +--- org.hibernate:hibernate-entitymanager:4.3.5.Final
    |    |    +--- org.jboss.logging:jboss-logging:3.1.3.GA
    |    |    +--- org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1
    |    |    +--- org.hibernate:hibernate-core:4.3.5.Final
    |    |    |    +--- org.jboss.logging:jboss-logging:3.1.3.GA
    |    |    |    +--- org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1
    |    |    |    +--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.0.0.Final
    |    |    |    +--- dom4j:dom4j:1.6.1
    |    |    |    |    \--- xml-apis:xml-apis:1.0.b2
    |    |    |    +--- org.hibernate.common:hibernate-commons-annotations:4.0.4.Final
    |    |    |    |    +--- org.jboss.logging:jboss-logging:3.1.3.GA
    |    |    |    |    \--- org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1
    |    |    |    +--- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final
    |    |    |    +--- org.javassist:javassist:3.18.1-GA
    |    |    |    +--- antlr:antlr:2.7.7
    |    |    |    \--- org.jboss:jandex:1.1.0.Final
    |    |    +--- dom4j:dom4j:1.6.1 (*)
    |    |    +--- org.hibernate.common:hibernate-commons-annotations:4.0.4.Final (*)
    |    |    +--- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final
    |    |    +--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.0.0.Final
    |    |    \--- org.javassist:javassist:3.18.1-GA
    |    +--- org.springframework:spring-orm:4.0.6.RELEASE
    |    |    +--- org.springframework:spring-beans:4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-core:4.0.6.RELEASE
    |    |    +--- org.springframework:spring-jdbc:4.0.6.RELEASE (*)
    |    |    \--- org.springframework:spring-tx:4.0.6.RELEASE (*)
    |    +--- org.springframework.data:spring-data-jpa:1.6.2.RELEASE
    |    |    +--- org.springframework.data:spring-data-commons:1.8.2.RELEASE
    |    |    |    +--- org.springframework:spring-core:3.2.10.RELEASE -> 4.0.6.RELEASE
    |    |    |    +--- org.springframework:spring-beans:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    |    +--- org.slf4j:slf4j-api:1.7.7
    |    |    |    \--- org.slf4j:jcl-over-slf4j:1.7.7 (*)
    |    |    +--- org.springframework:spring-orm:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-context:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-aop:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-tx:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-beans:3.2.10.RELEASE -> 4.0.6.RELEASE (*)
    |    |    +--- org.springframework:spring-core:3.2.10.RELEASE -> 4.0.6.RELEASE
    |    |    +--- org.aspectj:aspectjrt:1.8.1
    |    |    +--- org.slf4j:slf4j-api:1.7.7
    |    |    \--- org.slf4j:jcl-over-slf4j:1.7.7 (*)
    |    \--- org.springframework:spring-aspects:4.0.6.RELEASE
    |         \--- org.aspectj:aspectjweaver:1.8.1
    +--- org.springframework.boot:spring-boot-starter-aop: -> 1.1.5.BUILD-SNAPSHOT (*)
    +--- com.h2database:h2: -> 1.3.176
    \--- project :commons
         +--- org.apache.commons:commons-lang3:3.3.2
         \--- com.google.guava:guava:17.0

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.
