### ISSUE TITLE
Schema.sql not found when not using JPA and using Liquibase.

### ISSUE THREAD

**Issue by virmundi** [spring-projects/spring-boot#13123]
I use Liquibase. If the schema already exists in the database, Liquibase runs fine. If I remove it, and use schema.sql instead, Liquibase fails to create its lock table and the contents of the schema since it does not exist.

The schema.sql file sits at src/main/resources.

Diagnostic info

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.0.RELEASE</version>
    <relativePath></relativePath>
  </parent>
<spring-integration.version>5.0.3.RELEASE</spring-integration.version>

**Comment by wilkinsona** [comment]
Thanks for the report but I'm not sure that I understand what's causing the problem. Can you please provide a complete, minimal sample that reproduces the problem? A repository on GitHub or a zip attached to this issue would be ideal.

**Comment by virmundi** [comment]
I'm making one now.

**Comment by virmundi** [comment]
Sorry for the delay. Please see https://github.com/virmundi/spring-init-bug.

**Comment by wilkinsona** [comment]
Thanks for the sample. As [described in the documentation](
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-initialize-a-database-using-spring-jdbc), `schema.sql` is only applied to an embedded database by default. You need to set `spring.datasource.initialization-mode=always`.
