### ISSUE TITLE
ApplicationContextRunner does not work correctly when AutoConfiguration class has not @Configuration

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#13129]
This is most definitely my error that I forgot to add an `@Configuration` to my custom auto configuration. 

The problem occurs when an auto configuration class (e.g. `MyCustomAutoConfiguration`) has a nested configuration class with `@EnableConfigurationProperties` is missing a `@Configuration` (the root class) then the Spring Boot application works correctly. However, when using the `ApplicationContextRunner` the behaviour is not the same.

See [this](https://github.com/filiphr/boot-test-infra-issue) repository for a reproducing example. In the example repo if you move the `@EnableConfigurationProperties` then tests that were failing before will pass.

If you think that there is nothing that Boot can do about this, feel free to close it. I was just confused why it was working in one instance, but not in the other

**Comment by filiphr** [comment]
Thanks a lot analysis and looking into it

**Comment by wilkinsona** [comment]
I believe this is a Spring Framework bug so I have opened [SPR-16839](https://jira.spring.io/browse/SPR-16839). If the Framework team disagree we can re-open this issue and look for a workaround.
