### ISSUE TITLE
ServletContextListener contextDestroyed is not called when Undertow stops

### ISSUE THREAD

**Issue by Xiaobaxi** [spring-projects/spring-boot#13134]
Spring boot：1.5.12.RELEASE
Container：spring-boot-starter-undertow

when i defined the MyServletContextListener class with the @WebListener annotation
and add the @ServletComponentScan annotation on the bootstrap class

when i start the server
1、EmbeddedWebApplicationContext#onRefresh called the createEmbeddedServletContainer
2、UndertowEmbeddedServletContainerFactory#createDeploymentManager
3、DeploymentImpl#deploy method will add the MyServletContextListene
4、the MyServletContextListener#contextInitialized method called
but when i stop the server
1、EmbeddedWebApplicationContext#onClose called the stopAndReleaseEmbeddedServletContainer
2、UndertowEmbeddedServletContainer#stop
3、DeploymentManager#stop， do not called the undeploy method, so the contextDestroyed is not called

How can I solve it? By the way，change the spring-boot-starter-tomcat it is ok

**Comment by wilkinsona** [comment]
Thanks for the report. You can work around the problem by providing a custom Undertow factory that returns a custom Undertow container that overrides `stop()` to also call `undeploy()`. Something like this:

```java
@Bean
public UndertowEmbeddedServletContainerFactory undertowFactory() {
    return new UndertowEmbeddedServletContainerFactory() {

        @Override
        protected UndertowEmbeddedServletContainer getUndertowEmbeddedServletContainer(
                Builder builder, DeploymentManager manager, int port) {
            return new UndertowEmbeddedServletContainer(builder, manager,
                    getContextPath(), isUseForwardHeaders(), port >= 0,
                    getCompression(), getServerHeader()) {

                @Override
                public void stop() throws EmbeddedServletContainerException {
                    super.stop();
                    System.out.println("Undeploying");
                    manager.undeploy();
                    System.out.println("Undeployed");
                }

            };
        }

    };
}
```

**Comment by Xiaobaxi** [comment]
the ApplicationListeners implements the Lifecycle and DeploymentManager#stop will stop the deployment's lifecycleObjects
Can it be added to the DeploymentImpl#addLifecycleObjects

**Comment by Xiaobaxi** [comment]
@wilkinsona thank u very much
