### ISSUE TITLE
Property spring.config.location does not work for value file./

### ISSUE THREAD

**Issue by kaczoor** [spring-projects/spring-boot#13147]
Hi,
I've changed default value of property `spring.config.location`. One of these locations is `file:./` but spring does not load properly files from this location.

Steps to reproduce:

1. Generate simple app in https://start.spring.io/
2. Add class
```java
@Service
class FileResourceTest implements CommandLineRunner {

    @Value("${test}")
    private String test;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Testing value: " + test);
    }
}
```
3. Build the project
4. Create application.properties in directory where jar was built
`
test=OK
`
4. Run jar:` java -jar -Dspring.config.location=file:./ demo-0.0.1-SNAPSHOT.jar`
5. Application throws exception 
```java.lang.IllegalArgumentException: Could not resolve placeholder 'test' in value "${test}"```
6. Rename `application.properties` to `null.properties`
7. Run jar again
8. Application prints Testing value OK

Probably the problem is in  `ConfigFileApplicationListener.Loader`. `StringUtils.cleanPath(path);` removes `./` from `file:./` and then `boolean isFolder = location.endsWith("/");` returns false.

Spring Boot 2.0.x

**Comment by mbhave** [comment]
This might be something that could be fixed in Spring Framework. I've created an issue [here](https://jira.spring.io/browse/SPR-16908).

**Comment by mbhave** [comment]
The Spring Framework issue has been resolved. The fix will be available in Spring Boot when we upgrade to Framework 5.0.8.
