### ISSUE TITLE
forbid RANDOM_PORT and MockMvc combination

### ISSUE THREAD

**Issue by isopov** [spring-projects/spring-boot#13153]
Currently it is possible to write such strange test:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
@AutoConfigureMockMvc
public class MockMvcRandomPortApplicationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TestRestTemplate testRestTemplate;

    @Test
    public void testHello() throws Exception {
        mockMvc.perform(get("/hello"))
                .andExpect(status().isOk())
                .andExpect(content().string("Hello World!"));

        ResponseEntity<String> resp
                = testRestTemplate.getForEntity("/hello", String.class);
        assertEquals(HttpStatus.OK, resp.getStatusCode());
        assertEquals("Hello World!", resp.getBody());
    }

}
```
It works but I expect some strange problem if I try make something complex - e.g. autowiring ServletContext gives org.apache.catalina.core.ApplicationContextFacade while autowiring it for MockMvc-based test gives SpringBootMockServletContext.

I understand that there may be tests depending on this combination. But if it is not purposely supported maybe it is worth clear indicate it by failing this combination? It will also promote more clean tests, I think.

**Comment by snicoll** [comment]
That can be said for many other features IMO. I personally don't see why we should look for this explicit combination without reviewing the whole slice test infrastructure. This test reads that you want to start a server on a random port and mock the server at the same time. 

Let's see what the rest of the team thinks.

**Comment by isopov** [comment]
BTW, in unofficial tutorials this combination is used - http://www.baeldung.com/spring-boot-testing

**Comment by wilkinsona** [comment]
While guiding users away from strange configuration combinations and towards the right approach is something we like to do, I'm not sure there's anything that we can do here that won't introduce a maintenance cost that's higher than its benefits. My feeling is that we should decline this issue.

**Comment by isopov** [comment]
There is also similar check (only that it seems to prevent from not working combination) - https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/SpringBootTestContextBootstrapper.java 
```
	protected void verifyConfiguration(Class<?> testClass) {
		SpringBootTest springBootTest = getAnnotation(testClass);
		if (springBootTest != null
				&& (springBootTest.webEnvironment() == WebEnvironment.DEFINED_PORT
						|| springBootTest.webEnvironment() == WebEnvironment.RANDOM_PORT)
				&& getAnnotation(WebAppConfiguration.class, testClass) != null) {
			throw new IllegalStateException("@WebAppConfiguration should only be used "
					+ "with @SpringBootTest when @SpringBootTest is configured with a "
					+ "mock web environment. Please remove @WebAppConfiguration or "
					+ "reconfigure @SpringBootTest.");
		}
	}
```

**Comment by wilkinsona** [comment]
That check is somewhat similar but, as I think you've noted, it's protecting against a combination that'll fail not matter what you do. See https://github.com/spring-projects/spring-boot/issues/6795 for details.

This issue is rather different as you'll only encounter a problem if you use the unusual combination and then autowire something like the `ServletContext`. That's where I think the balance of the benefit vs the cost changes to the point that I'm not convinced it's worth doing anything.

**Comment by snicoll** [comment]
We had a pass on this one during the team meeting and we confirm that we don't want to pursue this for the reasons exposed above.
