### ISSUE TITLE
Different profile precedence introduced in Spring Boot 2.0.2 - include profile now comes after active.

### ISSUE THREAD

**Issue by davidmelia** [spring-projects/spring-boot#13151]
Hi,

Spring Boot 2.0.2 has introduced a different profile precedence when compared to previous versions.

It's very easy to reproduce.  

1. In STS create a Spring boot starter web project
2. In the application.properties add _spring.profiles.include=include_
3. Build and run the project with java -jar ./target/somename-0.0.1-SNAPSHOT.jar --spring.profiles.active=active
4. You will see _The following profiles are active: active,include_ which is incorrect

Downgrade the pom to Spring boot 2.0.1 and run again and you will see 
_The following profiles are active: include,active_
which is correct

Spring boot 1.5.13 also gives _The following profiles are active: include,active_

I'm using Java 8 & MacOS High Sierra.

Thanks

**Comment by davidmelia** [comment]
Hi,

If I explain my use case:

I'm deploying in a microservice architecture so I've created a common microservices maven dependency containing spring boot properties I want across all Microservices:
_application-microservice.properties_
and also contains a common override when I deploy to the cloud
_application-cloud.properties_

Every microservice pulls in this maven dependency & switches on the first profile via
_spring.profiles.include=microservice_ 
in the local application.properties of that service.

When I deploy to the cloud I additionally add the command line argument
--spring.profiles.active=cloud
which turns on the override.  

What's happening now is the cloud profile property is being overridden by the microservice profile and therefore Spring Boot 2.0.2 is quite a large breaking change for me.

To illustrate this further if I have a spring boot app with the following properties
```
application-cloud.properties
    some.key=cloudprop
application-microservice.properties
    some.key=microserviceprop
application.properties
    spring.profiles.include=microservice
```
and a command line active profile of 'cloud' then Spring Boot <=2.0.1 outputs 'cloudprop' where as 2.0.2 outputs 'microserviceprop'

Thanks

**Comment by wilkinsona** [comment]
That additional description is very useful. Thank you.

**Comment by jpopadak** [comment]
I seem to be having the exact same issues. Anything in `include` is overriding my `active` profile.

**Comment by philwebb** [comment]
_assigning myself to review [this fix](https://github.com/mbhave/spring-boot/tree/include-profiles)_

**Comment by vivekasingh** [comment]
I have similar experience too. My services get configuration from config server and the order of profile in http request is changed.
For example:
Spring Boot 2.0.1: http://localhost:8080/config/fooservice/mysql,native
Spring Boot 2.0.2: http://localhost:8080/config/fooservice/native,mysql

**Comment by vivekasingh** [comment]
@philwebb I still the issue with Spring Boot 2.0.3, included profiles are still having higher priority than active profile.

**Comment by philwebb** [comment]
@vivekasingh I tested with the example given in https://github.com/spring-projects/spring-boot/issues/13151#issuecomment-388567781. Perhaps it's related to the use of `bootstrap.yml`. Can you please open a new issue with a sample that we can run?

**Comment by vivekasingh** [comment]
Thanks @philwebb Just opened https://github.com/spring-projects/spring-boot/issues/13513 with sample project to demonstrate the issue.

**Comment by PaulGobin** [comment]
on a similar note for Kubernetes ConfigMap, I have the following in bootstrap.yml
..
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      secrets:
        enable-api: false
        enabled: false  
      config:
        enable-api: true
        enabled: true
        sources:
          - name: ${spring.application.name}
          - name: common
          - name: common-sqlserver
          - name: common-doc
...

Output in console:
Located property source: CompositePropertySource {name='composite-configmap', propertySources=[ConfigMapPropertySource {name='configmap.common-doc.default'}, ConfigMapPropertySource {name='configmap.common-sqlserver.default'}, ConfigMapPropertySource {name='configmap.common.default'}, ConfigMapPropertySource {name='configmap.we-order-service.default'}]}

I am thinking the ordering should be top down vs bottom up?

**Comment by rohan-blackbuck** [comment]
@philwebb @mbhave 

Sorry to be commenting here on an old issue, but my company is using a rather old version of spring boot (1.5.6.RELEASE), and I think this same bug exists in that version too. Is this correct?

**Comment by kapad** [comment]
@philwebb @mbhave 

Sorry to be commenting here on an old issue, but my company is using a rather old version of spring-boot (1.5.6.RELEASE) and I'm not sure if this same bug existed in that version or not. 

I seem to facing the same problem, where a profile included using `spring.profiles.include` overrides properties that it shouldn't be as per the documentation. 

The problem that I am facing is

**application-dev.yml**
```
spring:
  profiles:
    include: 
      - 'main-dev'

flyway:
  enabled: true
  location: 'migrations'
```

**application-main-dev.yml**
```
flyway:
  enabled: false
```

When I run with `-Dspring.profiles.active=dev` my console prints the active profiles as `main-dev, dev`, which seems correct. What I expect, is that properties in the `dev` profile would override properties in the `main-dev` profile. But the behavior is the exact opposite, and the value that the flyway auto configuration class sees for `flyway.enabled` is `false`.

**Comment by philwebb** [comment]
@kapad There are a few known issues with property file handling in 1.5.x but we've decided that it's too risky to fix them at this point. On a related note, [1.5.x is EOL in August](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019) so you should consider upgrading if possible.

**Comment by kapad** [comment]
@philwebb thanks for replying to this really old issue. :)

Where can I see the EOL of different spring versions? What you mention is definitely something my team needs to look into, and I would like to link to the official pages and raise the EOL issue to my manager.

**Comment by philwebb** [comment]
@kapad Announcements are usually made on spring.io/blog. Spring Framework also have a [wiki page](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions). We have an open issue to make this information easier to find.

**Comment by kapad** [comment]
hey @philwebb 

So I was going through the dependencies of spring-boot 2.0.x and saw that the spring core version that is required is 5.0.x
Now, my org is using spring-boot 1.5.6 and as you mentioned in an earlier comment, that version of spring boot is reaching EOL on 1st August, 2019. 
spring-boot 1.5.6 though, depends on spring-core 4.3.10 ([see](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/1.5.6.RELEASE)), which will continue to be maintained until mid-2020 (from the [wiki](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions) that you shared earlier).
So my question is this -> which version of spring boot should I upgrade to, so that I continue depending on spring-core (and other framework dependencies) of the 4.3.10 LTS version and also continue using a spring boot version that is officially supported?

**Comment by wilkinsona** [comment]
After 1st August there will not be a supported version of Spring Boot that depends on Spring Framework 4.3.x. If you want to continue to use a supported version of Spring Boot, you should upgrade to 2.1.x.
