### ISSUE TITLE
Dependency management for Spring Web Services is incomplete

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13150]
There's no dependency management for `org.springframework.ws:spring-xml`. It's a dependency of `spring-ws-core` which is managed.

**Comment by xenoterracide** [comment]
is this going to be added to 2.x as well?

**Comment by philwebb** [comment]
@xenoterracide Yes it will be in 2.0.3. We forward merge all commits so anything in 1.5.x will also be in 2.0.x and master.
