### ISSUE TITLE
NoClassDefFoundError: ParserContext when running integration tests since Spring Boot 2.0.2

### ISSUE THREAD

**Issue by mtritschler** [spring-projects/spring-boot#13168]
It appears that Spring Boot 2.0.2 introduced a bug that causes integration tests running with maven-failsafe-plugin to fail with

    java.lang.NoClassDefFoundError: org/springframework/expression/ParserContext
    Caused by: java.lang.ClassNotFoundException: org.springframework.expression.ParserContext

I created https://github.com/mtritschler/broken-spring-boot-demo with a minimal broken example to demonstrate the behaviour. Running `mvn clean verify` finishes successfully when using Spring Boot `2.0.1.RELEASE`, but is broken when upgrading to `2.0.2.RELEASE` and still is broken in `2.0.3.BUILD-SNAPSHOT`

Reproduced with

    mtritschler$ mvn -v
    Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
    Maven home: /usr/local/Cellar/maven/3.5.3/libexec
    Java version: 1.8.0_102, vendor: Oracle Corporation
    Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

    mtritschler$ java -version
    java version "1.8.0_102"
    Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by wilkinsona** [comment]
Thanks for the sample. It works for me with 2.0.2.RELEASE. I suspect that Maven has corrupted the `spring-expression` jar file when it downloaded it. Please clear out your Maven cache and try again.

**Comment by mtritschler** [comment]
Oh, you are completely right @wilkinsona, this fixed the problem. Sorry for the spam and thanks for the hint
