### ISSUE TITLE
Spring Cloud Sleuth and Spring Rest Docs dependencies cause missing ServletWebServerFactory error in test

### ISSUE THREAD

**Issue by tomBP** [spring-projects/spring-boot#13162]
I'm using Spring Boot 2.0.2.RELEASE, Spring Cloud Finchley.BUILD-SNAPSHOT and Spring Rest Docs 2.0.1.RELEASE. I have a test that uses the `WebTestClient` to test a Rest controller and is annotated with:

```
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
```

If I include the following two dependencies in the build:

```
 compile('org.springframework.cloud:spring-cloud-starter-sleuth')
 testCompile "org.springframework.restdocs:spring-restdocs-mockmvc:${restDocsVersion}"
```

then the test fails with:

```
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
```

 Commenting out either dependency makes the test pass.

**Comment by wilkinsona** [comment]
If you are using `WebTestClient` in your tests, why have you opted to use REST Docs' `MockMvc` support? Have you considered using `spring-restdocs-webtestclient` instead?

**Comment by tomBP** [comment]
I wasn't using REST Docs in that test. I wanted to document a different piece of functionality using `MockMvc` as I wasn't aware that the `WebTestClient` could be used without a HTTP server. I've now changed the dependency to `spring-restdocs-webtestclient`, used `WebTestClient.bindToController(controller)` (instantiating the controller with a mock dep) and all is working as expected. Sorry for any time wasted.
