### ISSUE TITLE
ConfigurationProperties metadata contains fields with non-public setter/getter from Lombok

### ISSUE THREAD

**Issue by kesslerj** [spring-projects/spring-boot#13172]
Property metadata contains properties for fields which have a non-public (or none) setter or getter when using lombok. The bug occures if there are lombok annotations used, which define the `lombok.AccessLevel` as annotation attribute.

Example:

```java 
@Data
@ConfigurationProperties("test.lombok")
public class LombokProperties {

	@Getter(AccessLevel.PRIVATE)
	@Setter(AccessLevel.PRIVATE)
	private String shouldNotAppear;

	private String shouldAppear;

}
```

Property `test.lombok.should-not-appear` is contained in the metadata, but it should not.

Behaviour in spring-boot-configuration-processor: `ConfigurationMetadataAnnotationProcessor` only checks if lomboks `@Getter` or `@Setter` are used, not if any attributes were set.

See my example project to verify the bug: https://github.com/kesslerj/spring-boot-properties-metadata-lombok-bug

I started fixing the issue and will offer a pull request soon.

**Comment by snicoll** [comment]
> I started fixing the issue and will offer a pull request soon.

Cool, thanks. For the record we don't need an issue and a PR (as one duplicates the other). Looking forward to the PR then!

**Comment by kesslerj** [comment]
Ah, ok. Good to know :)

**Comment by snicoll** [comment]
Closing in favour of PR #13175
