### ISSUE TITLE
spring.flyway.baseline-version is not supporting larger values like appending timestamp in version string

### ISSUE THREAD

**Issue by vir2610** [spring-projects/spring-boot#13170]
Facing issue while putting the **spring.flyway.baseline-version** in **application.properties** with larger numbers such as **V6.0.150520183007**.
Its suggesting to change the configuration in console when looking for trace. I came across one ticket in flyway for the same and suggested this as spring boot issue. 
Ref. https://github.com/flyway/flyway/issues/1065

My **application.properties** flyway configuration looks like below.
```
#Flyway migration properties
spring.flyway.baselineOnMigrate=true
spring.flyway.out-of-order=true
spring.flyway.baseline-version=V6.0.150520183007
```
Encountered error :

```
Failed to bind properties under 'spring.flyway.baseline-version' to org.flywaydb.core.api.MigrationVersion:

    Property: spring.flyway.baseline-version
    Value: V6.0.150520183007
    Origin: class path resource [application.properties]:26:32
    Reason: Failed to convert from type [java.lang.String] to type [org.flywaydb.core.api.MigrationVersion] for value 'V6.0.150520183007'; nested exception is org.flywaydb.core.api.FlywayException: Invalid version containing non-numeric characters. Only 0..9 and . are allowed. Invalid version: V6.0.150520183007

Action:

Update your application's configuration
```

**Comment by wilkinsona** [comment]
The size of the value isn't the problem. The problem is that you've used an illegal character. This is described in Flyway's error message:

```
Invalid version containing non-numeric characters. Only 0..9 and . are allowed. Invalid version: V6.0.150520183007
```

You can reproduce the problem with this line of code:

```
MigrationVersion.fromVersion("V6.0.150520183007");
```

You need to update your baseline version to remove the `V`.

**Comment by vir2610** [comment]
@wilkinsona I couldn't find invalid character in that version number, can you please point it exactly ? and also have you checked that flyway ticket I have mentioned above ?
We are kinda stuck here so please point it out exactly what is the issue in my configuration

**Comment by spencergibb** [comment]
> You need to update your baseline version to remove the V.

**Comment by vir2610** [comment]
@spencergibb Thanks mate 👍 really appreciate your help
