### ISSUE TITLE
Add to JackonProperties and JacksonAutoconfiguration support to set visibility

### ISSUE THREAD

**Issue by Alexuy** [spring-projects/spring-boot#13176]
Hi!

When Spring Framework 5.1 will be released and when you upgrade spring-boot to it, please, add possibility to set visibility properties to default Jackson ObjectMapper.

See Spring Framework issue:

https://jira.spring.io/browse/SPR-16411

**Comment by snicoll** [comment]
Closing in favour of PR #13214
