### ISSUE TITLE
@ConfigurationProperties : issue with com.hazelcast.client.config.ClientConfig.networkConfig.addressList/setAddresses()

### ISSUE THREAD

**Issue by blop** [spring-projects/spring-boot#13189]
It seems the processing of ConfigurationProperties has changed in spring-boot 2.X versus 1.5.X.

I have a @Bean of type com.hazelcast.client.config.ClientConfig annotated with @ConfigurationProperties("hazelcast.client").

Since the upgrade in spring-boot 2.0.0.RELEASE, we can no longer inject a value through a property like "hazelcast.client.networkConfig.addresses".

I guess there some sort of issue because of the mismatch between the field name (addressList) and the getter/setter names (getAddresses/setAddresses) inside the class com.hazelcast.client.config.ClientNetworkConfig.

It used to work properly in the older versions though, could we imagine some improvement to make it work again?

**Comment by snicoll** [comment]
> could we imagine some improvement to make it work again?

@blop if something doesn't work for you, it would be much more efficient to actually show what doesn't work. I've created a simple project based on the property you've defined and the `ClientConfig` bean has been created properly for me.

2.0 has added support for Hazelcast Client (#7469) and I am guessing that's what you wrongly assumed to be a binding problem. Please review your setup and clarify the problem you are experiencing. We prefer a small sample that demonstrates the issue.

**Comment by blop** [comment]
Sure.
Here is one example : 
```
package com.spring.boot.issue13189

import com.hazelcast.client.config.ClientConfig
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.runApplication
import org.springframework.context.ConfigurableApplicationContext
import org.springframework.context.annotation.Bean

@SpringBootApplication
@EnableAutoConfiguration(exclude = [org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration::class])
class Issue13189Application {
    @Bean
    @ConfigurationProperties("hazelcast.client")
    fun myClientConfig() = ClientConfig()
}

fun main(args: Array<String>) {
    val context: ConfigurableApplicationContext = runApplication<Issue13189Application>(*args)
    println("ClientConfig.instanceName = " + context.getBean(ClientConfig::class.java).instanceName)
    println("ClientConfig.networkConfig.addresses = " + context.getBean(ClientConfig::class.java).networkConfig.addresses)
}
```

Environment variables : 
hazelcast.client.networkConfig.addresses=1.1.1.1
hazelcast.client.instanceName=test

VM options : 
-Dhazelcast.client.instanceName=mouh -Dhazelcast.client.networkConfig.addresses=3.3.3.3

Output : 
ClientConfig.instanceName = mouh
ClientConfig.networkConfig.addresses = []

**Comment by blop** [comment]
Hum, seems to be fixed since 2.0.1.RELEASE

**Comment by snicoll** [comment]
> Here is one example :
Thanks but that's not a sample we can run ourselves. Copy/pasting this to a new project and then attempting to reproduce the problem is time spent on our end that we would better use at trying to help you.

> Environment variables
Environment variables were restricted to upper case underscore initially and we've relaxed that as of `2.0.1.RELEASE`. Please upgrade.

**Comment by blop** [comment]
Yes, it's working fine in 2.0.1.RELEASE+.
For info, it was not working with either lowercase nor uppercase environment variables notation in 2.0.0.RELEASE.
