### ISSUE TITLE
Reference Guide mentions "WebEnvironmentType" instead of WebApplicationType

### ISSUE THREAD

**Issue by klr8** [spring-projects/spring-boot#13195]
In the Spring Boot 2.0.2 Reference Guide, §23.6 states:

> The algorithm used to determine a WebEnvironmentType is fairly simple

This should be "WebApplicationType". There is no such thing as a WebEnvironmentType.

**Comment by snicoll** [comment]
@klr8 thanks a lot for the report. That's ironic considering I've introduced that wrong term in an issue that was supposed to remove deprecated reference 😬 (#12330)
