### ISSUE TITLE
flyway location to root subfolder

### ISSUE THREAD

**Issue by zwolej** [spring-projects/spring-boot#13190]
I placed migration files in root of project and there is no way to point to that folder.
Before migration to spring boot 2 working path was:
``
flyway.locations=filesystem:./in_root_folder
``
now, nothing works
``
spring.flyway.locations=classpath:/../../../in_root_folder
spring.flyway.locations=filesystem:./in_root_folder
spring.flyway.locations=filesystem:/../../../in_root_folder
``

**Comment by wilkinsona** [comment]
How have you identified that "nothing works"? If there's an error, is it produced by Spring Boot or by Flyway? Can you please provide a small sample application (either as a GitHub repository or as a zip attached to this issue) that works with Boot 1.5 and fails when upgraded to Boot 2.0?

**Comment by zwolej** [comment]
I ve been just migrating spring boot from 1.5 to 2.0 and nothing more and as migration guide tells I changed deprecated 
`
flyway.locations > spring.flyway.locations:
`
so from
`
flyway.locations: filesystem:./x-db/sql/model
`
to 
`
spring.flyway.locations: filesystem:./x-db/sql/model
`
and it is not working anymore. Error:
`
Caused by: java.lang.IllegalStateException: Cannot find migrations location in: [classpath:./x-db/sql/model] (please add migrations or check your Flyway configuration)
`
This error occurs while running flyway in tests

**Comment by wilkinsona** [comment]
Thanks but, unfortunately, we don't have time to piece something together from a brief description. Even if we did have time, there's still a risk that we'll end up with something different that either doesn't reproduce the problem or fails in a different way. If you'd like us to spend some time investigating, please spend some time to provide a complete sample that reproduces the behaviour you have described either in a GitHub repository in a zip attached to this issue.

**Comment by poppinlr** [comment]
@wilkinsona https://github.com/poppinlr/springboot_flyway_issue.git
here is my template project to show the issue

I do put the sql file in classpath:db/migration
but still got error : ```
Cannot find migrations location in: [classpath:db/migration] (please add migrations or check your Flyway configuration)
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
```

**Comment by wilkinsona** [comment]
Thanks for the sample.

Your migrations are in the wrong directory. They are in a directory named `src/main/resources/db.migrations`. They need to be in a directory named `src/main/resources/db/migrations`. Note the `/` rather than the `.` between `db` and `migrations`.

I can't see any usage of a property with a value beginning with `filesystem:` like you mentioned in your original description of the problem. Does this sample reproduce the exact problem you're seeing?

**Comment by poppinlr** [comment]
Thanks @wilkinsona 

> db.migrations

 in my old project 
but I soled the problem by create a folder named **flyway** 
and add config in property 

> spring.flyway.locations=classpath:flyway

**Comment by wilkinsona** [comment]
I'm pleased to hear you've solved your problem. Thanks for letting us know.

**Comment by zwolej** [comment]
@poppinlr 
but you placed folder flyway in root of project? 
I want to admit that I don't want to place sql files in src/main/resources I want them in root directory of project

**Comment by emeentag** [comment]
This path below is worked for me:
```    check-location: true
    locations:
    - classpath:./db/migration```
`./db` dot is needed in here.
