### ISSUE TITLE
@Procedure annotation passing wrong parameters

### ISSUE THREAD

**Issue by vikram06** [spring-projects/spring-boot#13199]
**Spring Boot version**  1.5.6.RELEASE
**Bug annotation**  @Procedure
**Expectation** Actual call with two parameters
**Getting**  Three parameters
In My Repo 
```
 @Procedure(name = "PROC_NAME")
 String PROC_NAME(String X,String Y);
```
I am passing two parameters but i am getting 
` call PROC_NAME with three parameters`

**Comment by snicoll** [comment]
`@Procedure` is part of Spring Data. Please use [the appropriate issue tracker](https://jira.spring.io/browse/DATAJPA). Before creating the issue there, gather additional details about the problem (a sample would be helpful).
