### ISSUE TITLE
Integrated spring boot application fires all flyway scripts from the class-path folder every time I switch run mode of application 

### ISSUE THREAD

**Issue by vir2610** [spring-projects/spring-boot#13207]
Question

I am running my spring boot application with flyway configured in application.properties in 2 different modes, one from which I am developing this application, and one from executable WAR to see after packaged the application, flyway still behaves perfectly.
But What I found is, flyway overwrites DB content (i.e. Firing all scripts again) on same DB which I used to run from IDE. Now this issue only happened if I change the run mode (i.e. from IDE to new build WAR or from WAR to IDE). Please note that everything related to DB configuration is same, I just change the run mode to executable WAR.
Please find my application.properties for flyway configuration

```
#Spring datasource properties
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1501;databaseName=issueDB1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.dbcp2.max-total=5

#Flyway migration properties
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration/testissue
spring.flyway.out-of-order=true
spring.flyway.baseline-version=1.3
spring.flyway.mixed=true
spring.flyway.cleanOnValidationError=true
```
I am not using any profiles here (i.e. dev or prod).

**Comment by wilkinsona** [comment]
Can you please explain why you believe this is a Spring Boot issue? It’s not clear to me exactly how Flyway is behaving or why you consider it to be a problem and one that’s caused by Boot at that. At the very list, your migration scripts and some detailed logging from Flyway to show how it is behaving would be useful. A complete, minimal sample that reproduces the problem would be even better.

**Comment by wilkinsona** [comment]
To avoid wasting any more of our time, can you please link to the Flyway issue that you opened? As things stand we’re just duplicating effort that’s already been expended by the Flyway team.

You haven’t shared your migration scripts so you’re the only person who can see what’s happening and diagnose the problem. If you want us to spend time investigating please spend the time to provide the information that we need to be able to do so.

You’ve enabled cleaning on a validation error. Right now I would guess that there’s a validation error so Flyway is cleaning your database and then running the migrations.

**Comment by vir2610** [comment]
I though cleaning on validation error would simply throw exception and will be stopped at that place. But as now I understand from you last comment, I got the point, You can close this issue.
Thanks for you support @wilkinsona
