### ISSUE TITLE
Problem with passing null parameter to MapSqlParameterSource 

### ISSUE THREAD

**Issue by glengarski** [spring-projects/spring-boot#13209]
I have following problem when pass null to MapSqlParameterSource

```
    final MapSqlParameterSource paramMap = new MapSqlParameterSource()
            .addValue("ALERT_ID", null);

```

Code | Warning
-- | --
NP | Null passed for non-null parameter of org.springframework.jdbc.core.namedparam.MapSqlParameterSource.addValue(String, Object) in bug.DocDao.test()
  | Bug type NP_NONNULL_PARAM_VIOLATION (click for details) In class bug.DocDaoIn method bug.DocDao.test()Called method org.springframework.jdbc.core.namedparam.MapSqlParameterSource.addValue(String, Object)Argument 2 is definitely null but must not be nullAt DocDao.java:[line 15]

In my case null is  valid value for database.
Sample code is attached here 
https://github.com/lengarski/bug

Here is the response from spotbugs
 https://github.com/spotbugs/spotbugs/issues/642

**Comment by wilkinsona** [comment]
Thanks for the report but `MapSqlParameterSource` is part of Spring Framework. It's issue tracker is [here](https://jira.spring.io/browse/SPR).
