### ISSUE TITLE
Make possible disabling all the schedulers with a application property

### ISSUE THREAD

**Issue by Hanor** [spring-projects/spring-boot#13201]
I have an application with two mains. One main uses schedules and the other main don't. 
I need to disable all the schedules in the second main, I can disable all the schedules of my application only removing the @EnableScheduling, but if you have a jar dependency and this jar was annotated with @EnableScheduling then my main will be enabled to use schedules and I don't want this on the second  main.

I know  how to resolve this with a property and annotation but I will need to annotate all the schedules. The humans make misstakes then in the future the human can forget this and create a new schedule without the annotation to disable the schedule then second main will run the schedule. If we have a property like: spring.disableAllSchedules=true, the my me of the future will be very happy.

I have googled some times and this scenario ocurs some times. Bring this to humanity make us lives better!

**Comment by snicoll** [comment]
Duplicate of #12682
