### ISSUE TITLE
about org.springframework.data.redis.core.ValueOperations<K, V>

### ISSUE THREAD

**Issue by 15058126273** [spring-projects/spring-boot#13216]
why not get(K key); but get(Object key);  ?
![image](https://user-images.githubusercontent.com/20962939/40275615-747e4d70-5c27-11e8-8164-415a875a2064.png)

**Comment by wilkinsona** [comment]
Issues aren’t really the right place to ask questions. Also, that code is not part of Spring Boot. It’s from Spring Data Redis.
