### ISSUE TITLE
Autowiring BuildProperties when running in Eclipse

### ISSUE THREAD

**Issue by ravikancherla** [spring-projects/spring-boot#13224]
I am trying to debug my spring boot application in debug mode

I have autowired `BuildProperties` to get build information from `build-info.properties` in one of my configuration files

```java
@Autowired
private BuildProperties buildProperties;
```

And I am also using dev-tools. I tried removing this but no luck. So, i am assuming the issue is not with dev tools

```
compile "org.springframework.boot:spring-boot-devtools"
```

I am getting `UnsatisfiedDependencyException`.

```
2018-05-21 12:34:59 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'swaggerConfig': Unsatisfied dependency expressed through field 'buildProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.info.BuildProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

This is working perfectly fine when i am `NOT` running in debug mode

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, you haven’t provided enough information for us to begin to diagnose the problem. To do so, we’ll need two things:

1. Clarification of what you mean by “debug mode”. Are you starting the JVM with the debugging agent enabled and attaching a debugger?
2. A minimal sample that reproduces the problem, either as a zip attached to this issue or a repository on GitHub, BitBucket, or similar.

**Comment by ravikancherla** [comment]
1. I am just right clicking on spring boot application main class and and running it as java application.
2. I want to use build properties in swagger and this is the sample class i can provide.

`
package com.xxx;

import static com.google.common.collect.Lists.newArrayList;
import static springfox.documentation.schema.AlternateTypeRules.newRule;

import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.ResponseEntity;
import org.springframework.web.context.request.async.DeferredResult;

import com.fasterxml.classmate.TypeResolver;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.schema.WildcardType;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig
{

  @Autowired
  private TypeResolver typeResolver;

  @Autowired
  private BuildProperties buildProperties;

  @Bean
  public Docket swaggerDocket()
  {
    return new Docket( DocumentationType.SWAGGER_2 ).select().apis( RequestHandlerSelectors.basePackage( "com.xxx" ) ).paths( PathSelectors.regex( "/services/.*" ) ).build()
        .pathMapping( "/" ).directModelSubstitute( LocalDate.class, String.class ).genericModelSubstitutes( ResponseEntity.class )
        .alternateTypeRules( newRule( typeResolver.resolve( DeferredResult.class, typeResolver.resolve( ResponseEntity.class, WildcardType.class ) ), typeResolver.resolve( WildcardType.class ) ) )
        .apiInfo( apiInfo() );
  }

  private ApiInfo apiInfo()
  {
    return new ApiInfo( buildProperties.get( "XXX" ),
                        "Blah Blah Blah",
                        buildProperties.getVersion(),
                        "",
                        new Contact( "XXX", "xxx", "xxx" ),
                        "",
                        "",
                        newArrayList() );
  }

}`

**Comment by wilkinsona** [comment]
Thanks. Unfortunately, some code in a comment isn’t really sufficient as there’s lots of things involved that we can’t see. If we guess, we’ll inevitably waste time trying to reproduce the same arrangement as you have. If you would like us to spend more time trying to help you, please spend some time to produce the requested minimal and complete sample that reproduces the problem.

**Comment by ravikancherla** [comment]
[demo.zip](https://github.com/spring-projects/spring-boot/files/2028418/demo.zip)

Steps to reproduce:
1. Run bootRun gradle task - It works fine
2. Right click on DemoApplication.java and debug as Java Application. It fails as it cannot find build-info.properties. Verified that it is present in build/resources/main/META-INF/build-info.properties

**Comment by wilkinsona** [comment]
Thanks for the sample.

The debugging part of the description was a red herring. As @philwebb suspected, the problem's actually due to a different classpath being used in Eclipse and occurs whether the application's run or debugged.

When the application's run with `bootRun` the following two directories are on the classpath:

```
file:/Users/awilkinson/Downloads/gh-13224/build/classes/java/main/
file:/Users/awilkinson/Downloads/gh-13224/build/resources/main/
```

When it's run in Eclipse, Buildship controls things and the following directory is on the classpath:

```
file:/Users/awilkinson/Downloads/gh-13224/bin/main/
```

Classes and resources are lumped together in a single directory and it's `bin/main` rather than being beneath `build` which is what's used on the command line and it where the `build-info.properties` file has been written.

This difference and the fact that the `buildInfo` task hasn't been run is an unfortunate limitation of Gradle's Eclipse tooling that's out of our control. Unfortunately, even running the `bootBuildInfo` task directly in Eclipse isn't sufficient as it doesn't use the default output location rather than the custom location that's preferred by Buildship.

I don't think there's anything that we can or should try to do in Spring Boot to work around these limitations. I would recommend looking at [Buildship's issues](https://github.com/eclipse/buildship/issues) and, if there isn't an existing issue, opening one.
