### ISSUE TITLE
Support Klaxon in addition to Jackson and GSON

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#13229]
It might be useful to support Klaxon (https://github.com/cbeust/klaxon) as a JSON mapper in addition to Jackson and GSON. BTW, Klaxon is from from Cedric Beust (creator of TestNG).

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I think this probably only makes sense when there's some Klaxon support in Spring Framework for us to build upon. As far as I know, there's no such support at the moment. Searching the [Framework's JIRA](https://jira.spring.io/browse/SPR) suggests that none is planned. @sdeleuze do you know what, if anything, is planned around Klaxon support in Framework?

**Comment by wilkinsona** [comment]
Thanks, @sdeleuze. In that case, I'm going to close this one. We can revisit it in the future if Klaxon support is added to Framework. Thanks again for the suggestion, @juergenzimmermann.
