### ISSUE TITLE
TTL property is not working for health indicator for Spring Boot 2.x

### ISSUE THREAD

**Issue by alexey-atiskov** [spring-projects/spring-boot#13238]
If project has no Spring Security, then Spring Boot 2.x always treats health request as authorized with adding "Principal is considered as input to the endpoint" per documentation https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-caching. So TTL is always zero.

Even after setting application.properties to
`management.endpoint.health.cache.time-to-live=100s
management.endpoint.info.cache.time-to-live=100s
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always`
request to http://localhost:8080/actuator/health is always processed by ReflectiveOperationInvoker (not CachingOperationInvoker).

Example test project 
[demo.zip](https://github.com/spring-projects/spring-boot/files/2029855/demo.zip)
 with TestHealthIndicator.java is showing that every response to /actuator/health has different time field value

> {
"status": "UP",
"details": {
"test": {
"status": "UNKNOWN",
"details": {
"time": "2018-05-22T15:25:48.617+0000"
}
},
"diskSpace": {
"status": "UP",
"details": {
"total": 217852637184,
"free": 124520787968,
"threshold": 10485760
}
}
}
}

BTW no such trouble for /info request - TTL can be set correctly by application properties

**Comment by alexey-atiskov** [comment]
[demo.zip](https://github.com/spring-projects/spring-boot/files/2029849/demo.zip)

**Comment by snicoll** [comment]
@alexey-atiskov than you very much for the report and the complete analysis, that's very helpful!

**Comment by edmundham** [comment]
Hello @snicoll, I am having a similar problem in Spring boot 2.1.10. 
TTL for the health endpoint is working normally, but when there are alive sessions, TTL is ignored (not cached at all). This was not a case in Spring boot 1.x. Is this expected behaviour or a bug?

**Comment by snicoll** [comment]
@edmundham please don't ask questions on closed issues. If you believe you've found an issue in Spring Boot, try with the latest version first and report an issue with a small sample accordingly (a github repo link or a zip with a small app we can run ourselves). Thank you!
