### ISSUE TITLE
provide xstream dependency in bom

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#13246]
related to #13150 (which is also an issue in SB2, left comment there) no version of 

com.thoughtworks.xstream | xstream | 1.4.10

is provided by Spring Boot Dependencies, I would like to see this added if possible.

p.s. if not possible, we have some really old code (converted from xml to javaconfig) (I know castor won't be supported) is it possible to point us in the direction of what we should be going to?

```
    @Bean( name = "webServiceTemplate" )
    public WebServiceTemplate webServiceTemplate( final CastorMarshaller castorMarshaller ) {
        WebServiceTemplate webServiceTemplate = new WebServiceTemplate( messageFactory() );
        webServiceTemplate.setMarshaller( castorMarshaller );
        webServiceTemplate.setUnmarshaller( xStreamMarshaller() );
        return webServiceTemplate;
    }
```

**Comment by wilkinsona** [comment]
Spring Boot doesn't touch XStream and, as an optional dependency of `spring-oxm`, it doesn't even end up on Boot's classpath transitively. As such, it doesn't meet the criteria for its version being managed in `spring-boot-dependencies`.

I don't have an opinion on which marshaller you should be going to other than noting that Spring Framework's Castor support is deprecated so it should be avoided. Declining the request to manage XStream's version should not be taken to imply that it shouldn't be used. It's purely about limiting the scope of Boot's dependency management to something that's sustainable. If it works for you, I would continue to use it.
