### ISSUE TITLE
@GetMapping vs @DeleteMapping and @RequestParam

### ISSUE THREAD

**Issue by Lapkritinis** [spring-projects/spring-boot#13254]
I have issue, that identical methods different only by annotation `@DeleteMapping` vs `@GetMapping`- `@DeleteMapping` doesn't recognise passed params.

Here are methods. I am using forked version of `gs-rest-service` example.
Full fork can be found here: [https://github.com/Lapkritinis/gs-rest-service](https://github.com/Lapkritinis/gs-rest-service)

Note: I have written MockMvc test and it passes, BUT real world Rest API fails with error:
`Required String parameter 'name' is not present`

Here are the methods in question. I removed default intentionally.

```
    @DeleteMapping(value = "/greeting")
    public Greeting notWorking(@RequestParam(value="name") String name) {
        return new Greeting(counter.incrementAndGet(),
                            String.format(template, name));
    }

    @GetMapping(value = "/greeting")
    public Greeting working(@RequestParam(value="name", defaultValue = "World") String name) {
        return new Greeting(counter.incrementAndGet(),
                String.format(template, name));
    }
```

**Comment by mbhave** [comment]
`GetMapping` and `DeleteMapping` are part of Spring Framework. The Spring Framework issue tracker is [here.](https://jira.spring.io/browse/SPR/)
