### ISSUE TITLE
JNDI with Spring boot (Embedded container)

### ISSUE THREAD

**Issue by aallou** [spring-projects/spring-boot#13259]
I started a new project with a very simple code with Spring Boot. I tried to get a JNDI resource, but I have an error. This is my code :

```
@SpringBootApplication
public class DemoJndiApplication {

public static void main(String[] args) throws NamingException {
    SpringApplication.run(DemoJndiApplication.class, args);
    testJNDI();
}

private static void testJNDI() throws NamingException {
    javax.naming.Context ctx = new InitialContext();
    ctx.lookup("java:comp/env");
}

@Bean
public TomcatEmbeddedServletContainerFactory tomcatFactory() {
    return new TomcatEmbeddedServletContainerFactory() {

        @Override
        protected TomcatEmbeddedServletContainer getTomcatEmbeddedServletContainer(Tomcat tomcat) {
            tomcat.enableNaming();
            return super.getTomcatEmbeddedServletContainer(tomcat);
        }

        @Override
        protected void postProcessContext(Context context) {
            ContextResource resource = new ContextResource();
            resource.setName("someThing");
            resource.setType("someType");
            context.getNamingResources().addResource(resource);
        }
    };
}
```

We have this error : 
`javax.naming.NameNotFoundException: Name [java:comp/env] is not bound in this Context. Unable to find [java:comp].
at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
at javax.naming.InitialContext.lookup(InitialContext.java:417)`

If we deploy the same application, but with the war packaging in an external web container (tomcat), it works.

Spring Boot version : 1.5.13.RELEASE

**Comment by wilkinsona** [comment]
JNDI lookups in Tomcat only work when the thread context class loader is Tomcat's web app class loader. That's the case during application context refresh and web request handling.
