### ISSUE TITLE
Regression in 2.0.2 for autoconfiguration order?

### ISSUE THREAD

**Issue by iNikem** [spring-projects/spring-boot#13264]
After upgrading from 2.0.0 to 2.0.2 we face an issue similar to #4781 . After some investigation it seems that in version 2.0.2 Hibernate gets initialised _before_ `EhCacheCacheConfiguration` thus leading to double cache initialisation and failure. I can confirm that in 2.0.1 the order is the correct one

**Comment by iNikem** [comment]
It seems that although `EhCacheCacheConfiguration` is still processed before `HibernateJpaAutoConfiguration` the first time when `CacheManager` bean is requested is long after Hibernate was initialised. 

May be important aspect is that `CacheManager` bean is requested by our own library which exposes beans as autoconfiguration itself...

**Comment by snicoll** [comment]
@iNikem There was an early initialization bug in the cache infrastructure that got fixed so I think that whatever problem you're experiencing is there since the beginning and hidden behind that bug. To go further, please share a sample we can run ourselves that reproduces the problem.

**Comment by iNikem** [comment]
I am unable to create a standalone reproducible example for this problem. It seems that our complex setup screws things in some non-obvious way. I have a workaround for this, so it is not a blocker for us.

**Comment by wilkinsona** [comment]
Thanks for following up, @iNikem. If you manage to create a reproducible example please let us know and we can re-open this issue.
