### ISSUE TITLE
Adding intelligence which will exclude dependencies which are not used.

### ISSUE THREAD

**Issue by vyankat70war** [spring-projects/spring-boot#13263]
**Problem Statement:** To add intelligence to exclude dependencies which are not used in application.

**Description:**  Spring boot adds every dependency required,  many of which are not used through out application life cycle. Adding all possibly required dependencies increases size of package needs to be deployed. 

**Suggestion :** It will be very useful if an intelligence is added which will exclude dependencies which are not used or imported in application.

**Comment by snicoll** [comment]
>  Spring boot adds every dependency required, many of which are not used through out application life cycle

@vyankat70war I don't understand what you mean. Spring Boot doesn't add "every dependency required". A starter may bring something sensible that you don't want to use but you're not forced to use that if you don't like it. 

Please provide a concrete example of what you mean.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
