### ISSUE TITLE
No log information for misconfigured PathVariable

### ISSUE THREAD

**Issue by lucasfsousa** [spring-projects/spring-boot#13278]
When you use a wrong valure in a PathVariable, there is no information about it, except when you use DEBUG level.

For example:
```
@RequestMapping("users/{id}")
User get(@PathVariable("name"))
```

If you try to access it you will get a 500 without any clue about the real error.

**Comment by snicoll** [comment]
> If you try to access it you will get a 500 without any clue about the real error.

What do you mean? This is what I get

```
➜  demo http :8080/users/test
HTTP/1.1 500 
Connection: close
Content-Type: application/json;charset=UTF-8
Date: Mon, 28 May 2018 14:06:47 GMT
Transfer-Encoding: chunked

{
    "error": "Internal Server Error",
    "message": "Missing URI template variable 'name' for method parameter of type String",
    "path": "/users/test",
    "status": 500,
    "timestamp": "2018-05-28T14:06:47.863+0000"
}
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lucasfsousa** [comment]
Sorry guys, I think the problem was some configuration in the project.
I tried now in a clean project and I had the same response with the detailed message.
