### ISSUE TITLE
MariaDB4j integration?

### ISSUE THREAD

**Issue by vorburger** [spring-projects/spring-boot#1329]
Hello, I don't suppose you may be interested in (a contribution?) integrating Spring Boot out-of-the-box nicely with my https://github.com/vorburger/MariaDB4j project?

MariaDB4j allows to use mysql as if it were an embedded database (H2, HSQL or Derby) - completely installation free.. basically it pulls down (platform specific) native binaries and then (properly) starts it up in a separate process etc. etc.

FYI I'll likely have a 2.1.0 (non-SNAPSHOT) up on Maven Central sometime in near future, as I'll need it for what I'm cooking up on https://github.com/vorburger/mifosx/compare/SpringBootAndMariaDB4j

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
