### ISSUE TITLE
Validate `server.servlet.path` does not contain unusual patterns (eg `/*`)

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#13292]
In application.properties:
```
server.servlet.path=/*
```

```
EndpointRequest.to(HealthEndpoint.class).matches(request)
```

Make a request for `/actuator/health`

I'd expect for the matcher to match, but it doesn't. Looking inside EndpointRequest, the `delegate` field has a `OrRequestMatcher` instance composed of an `AntPathRequestMatcher` with `pattern` set to `/*/actuator/health/**` - the pattern should be `/actuator/health/**`

**Comment by candrews** [comment]
I'm not sure why my application has `server.servlet.path=/*` set - the history isn't telling me. However, google shows me a few pages instructing users to use this configuration for JBoss. https://victal.eti.br/deploying-springboot-applications-on-jboss-7.html is one such example. So I think I'm probably not the only person with this configuration.

Setting `server.servlet.path=/` (which is the default) doesn't seem to break anything. So if you do nothing with this issue, it won't bother me.

If `server.servlet.path=/*` really is invalid, perhaps Spring Boot can have a validator on that field raising an error if this invalid value is provided?

**Comment by philwebb** [comment]
Good idea, I'll re-purpose this issue to add validation.

**Comment by mbhave** [comment]
We have [some tests](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcPropertiesTests.java#L42) that rely on this behavior at the moment. I'm not quite sure what we want to allow for `spring.mvc.servlet.path`.

**Comment by philwebb** [comment]
We discussed this on the call and decided to keep it as strict as possible until someone complains that they really need `*`.
