### ISSUE TITLE
Component indexer does not index springfox-swagger2 components

### ISSUE THREAD

**Issue by ssouris** [spring-projects/spring-boot#13293]
# **Spring Boot Version**

2.0.2.RELEASE

# **Description**
When using `component-indexer` with `springfox-swagger2`, the application fails to start.

Error:
```
Parameter 2 of method swagger2ControllerMapping in springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration 
required a bean of type 'springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper' 
that could not be found.
```

# **Test case**

https://github.com/ssouris/swagger-component-indexer-bug

**Comment by philwebb** [comment]
Spring Boot doesn't provide any direct integration with Swagger. You'll need to raise this at https://github.com/springfox/springfox/issues

**Comment by ssouris** [comment]
Thanks. I was afraid if it was a generic problem in the way indexer works. Will do.
