### ISSUE TITLE
Check if sync-to-maven-central CI task should have git trigger true

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13296]
I have a feeling it should be false. The `spring-javaformat` pipeline seemed to trigger it before the promote. That might have been because it was in a failed state.

**Comment by philwebb** [comment]
I think the "Waiting for artifacts to be published" curl might also need `-s` to make it silent

**Comment by mbhave** [comment]
We should trigger it on artifactory instead
