### ISSUE TITLE
Non-web application spams dead threads when SpringApplicationAdminJmxAutoConfiguration isn't included

### ISSUE THREAD

**Issue by severn-everett** [spring-projects/spring-boot#13301]
In a non-web Spring Boot Application, the application creates around 4 "JMX server connection timeout ##" threads every second if SpringApplicationAdminJmxAutoConfiguration is excluded in the `@EnableAutoConfiguration` annotation. The base code that's required to run this is as follows:
```
package com.example.jmxautoconfig;

import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.CountDownLatch;

@Configuration
@EnableAutoConfiguration(exclude = {
    SpringApplicationAdminJmxAutoConfiguration.class
})
@ComponentScan
public class JmxautoconfigApplication {

  public static void main(String[] args) {
    new SpringApplicationBuilder(JmxautoconfigApplication.class)
        .web(WebApplicationType.NONE)
        .run(args);
    CountDownLatch countDownLatch = new CountDownLatch(1);
    try {
      countDownLatch.await();
    } catch (Exception ex) {
      //No-Op
    }
  }
}
```

If it's intended behavior that the Spring JMX does not function correctly if this auto configuration is not included, it would be nice to either get a warning in the logs or prevent the application from starting up, as there's currently no notice in normal runtime conditions (i.e. logs at INFO level) that something is wrong.

Spring Boot Version: "Spring Boot 2.0.2.RELEASE"
Java Version: jdk-10.0.1

Excluding SpringApplicationAdminJmxAutoConfiguration:
![no_spring_application_admin_jmx_auto_config](https://user-images.githubusercontent.com/12528881/40722279-2f38d65c-641c-11e8-87e4-cce3d27591b9.png)

No exclusions:
![no_excludes_auto_config](https://user-images.githubusercontent.com/12528881/40722403-88303e80-641c-11e8-95e9-5c8fe48c49bb.png)

Console output when SpringApplicationAdminJmxAutoConfiguration is excluded:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.2.RELEASE)

2018-05-30 15:11:31.180  INFO 11612 --- [           main] c.e.j.JmxautoconfigApplication           : Starting JmxautoconfigApplication on Computer with PID 11612 (D:\Development\jmxautoconfig\build\classes\java\main started by Developer in D:\Development\jmxautoconfig)
2018-05-30 15:11:31.182  INFO 11612 --- [           main] c.e.j.JmxautoconfigApplication           : No active profile set, falling back to default profiles: default
2018-05-30 15:11:31.210  INFO 11612 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4397ad89: startup date [Wed May 30 15:11:31 CEST 2018]; root of context hierarchy
2018-05-30 15:11:31.539  INFO 11612 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-30 15:11:31.551  INFO 11612 --- [           main] c.e.j.JmxautoconfigApplication           : Started JmxautoconfigApplication in 0.561 seconds (JVM running for 1.102)
```

**Comment by snicoll** [comment]
@severn-everett do you get that from an IDE? The IDE may call this JMX bean periodically to understand what is going on with that app and failing as it's not registered.

**Comment by severn-everett** [comment]
You're right that it's only occurring when I run the program via my IDE: the default settings are to enable JMX. Is there a way to at least print out a warning if `SpringApplicationAdminJmxAutoConfiguration` has been excluded when it's required?

**Comment by snicoll** [comment]
@severn-everett what IDE are you using? As @wilkinsona indicated, this is most probably a problem there. May I ask why you've disabled that auto-configuration exactly?

**Comment by snicoll** [comment]
The answer to that is no. Excluding auto-configuration is an advanced technique and this really is a problem of the client using the JMX interface, not Spring Boot. Can you please open an issue in the IntelliJ IDEA tracker for this?

**Comment by kaleev** [comment]
Issue in the IntelliJ IDEA tracker: https://youtrack.jetbrains.com/issue/IDEA-192998
