### ISSUE TITLE
Regression with property binding to List<String>

### ISSUE THREAD

**Issue by marcelstoer** [spring-projects/spring-boot#13303]
With 1.5.x I used to have a property binding like this; a comma-separated String to `List<String>`.

```java
@ConfigurationProperties(prefix = "foo.bar")
public class MyAppProperties {
    private final Kafka kafka = new Kafka();

    public Kafka getKafka() {
        return this.kafka;
    }

    public static class Kafka {
        private List<String> topics;
        public void setTopics(List<String> topics) {
            this.topics = topics;
        }
...
```

```yaml
foo.bar:
    kafka:
      topics: test,failures
```

With Boot 2.0.2 this now fails with 

```
Failed to bind properties under 'foo.bar.kafka.topics' to java.util.List<java.lang.String>:

    Reason: Unable to get value for property topics
```

Replacing `List<String>` in the setter with `String[]` fixes this.

```java
public void setTopics(String[] topics) {
  this.topics = Lists.newArrayList(topics);
}
```

**Comment by snicoll** [comment]
According to the documentation, binding [requires a `getter`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties). Do I understand you don't have a getter there (i.e. it's not an oversight)?

**Comment by marcelstoer** [comment]
The getter is there - below the `...` in the initial snippet 😉 For the sake of completeness here it is:

```java
public List<String> getTopics() {
  return Collections.unmodifiableList(this.topics);
}
```

**Comment by mbhave** [comment]
It fails when the `CollectionBinder` tries to get the existing value for the collection [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/CollectionBinder.java#L60). In this case, it's a NPE. I think we should guard against this.

**Comment by marcelstoer** [comment]
@mbhave spot on 👍 If `topics` is initialized with an empty collection then I don't need the `String[]` workaround.
