### ISSUE TITLE
HTTP 400 when using path variable arrays

### ISSUE THREAD

**Issue by mac-chong** [spring-projects/spring-boot#13305]
Hey everyone,

I've recently upgraded Spring Boot Starter Web to 1.5.13.RELEASE and found that path variable arrays such as `/abc/def/[a,b,c]` returned HTTP 400 errors.
I did some investigation myself and found that this regression has only in the 1.5.13.RELEASE version as 1.5.12.RELEASE worked fine.

My REST controller used to test this was standard:

```java
@RestController
public class WebController {

    @RequestMapping("/[{pathVariable}]")
    public String[] helloWorld(@PathVariable String[] pathVariable){
        return pathVariable;
    }
}
```

Looking a little more closely to the issue, I found that upgrading tomcat-embed-core in spring-boot-starter-tomcat from 8.5.29 to 8.5.31 was the culprit as when I downgraded it, I no longer get the errors I've been was seeing:

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <!--Parent version 1.5.13.RELEASE-->
            <exclusions>
                <exclusion>
                    <groupId>org.apache.tomcat.embed</groupId>
                    <artifactId>tomcat-embed-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>8.5.29</version>
        </dependency>
```

I know using square brackets as path variables might appear silly, but I hope to get your thoughts on this. Thanks!

**Comment by philwebb** [comment]
Are you encoding the square brackets? They're [not valid in URLs otherwise](https://stackoverflow.com/questions/40568/are-square-brackets-permitted-in-urls)

**Comment by mac-chong** [comment]
That's a really good point - No I did not encode the square brackets on the URL, and after encoding them, the request works. Thanks!! 👍 
Should we still expect this to be addressed in future versions of Spring Boot or will unencoded square brackets in URLs no longer be supported?

**Comment by philwebb** [comment]
I expect that Tomcat tightened their encoding rules and I doubt they'll relax them again. I think it's probably a bug that the unencoded versions were ever accepted. If you want you can raise an issue [on their issue tracker](https://bz.apache.org/bugzilla/enter_bug.cgi?product=Tomcat%208).
