### ISSUE TITLE
Document Reactor Netty server configuration

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#13315]
The reference documentation lists, in "Embedded Web Servers", several sections explaining how to configure Tomcat, Jetty and Undertow. Those sections are quite similar and are missing a few concrete examples.

We should regroup all servers under a single section and expand a bit the explanation with samples.

**Comment by rstoyanchev** [comment]
@bclozel I suggested some further improvements with https://github.com/spring-projects/spring-boot/pull/13401, I thought it would be easier than comments on the commit.

Also what about backporting this to 2.0.x ? It seems worth the relatively minor effort and the fact 2.1 is still some time away.

**Comment by philwebb** [comment]
@rstoyanchev I've raised #13402 to look at the backport.
