### ISSUE TITLE
Auto-configure jOOQ with TransactionListenerProvider beans

### ISSUE THREAD

**Issue by Timmeey** [spring-projects/spring-boot#13329]
I'm letting Spring manage my DSLContext and Configuration. Therefore it uses the [JooqAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqAutoConfiguration.java) class to instantiate everything.

Now i wanted to use a custom TransactionListener(Provider)

Contrary to Execute/Record/Visit-Listener the JooqAutoConfiguration does not ask for a Bean of the Type TransactionListenerProvider.

This doesn't look intentional

**Comment by wilkinsona** [comment]
No, I don't think this was intentional. I suspect we just didn't notice the new functionality when we upgraded to jOOQ 3.9.

I think you can work around this using a bean post-processor like this:

```
@Bean
public static BeanPostProcessor jooqConfigurationPostProcessor() {
    return new BeanPostProcessor() {

        @Override
        public Object postProcessBeforeInitialization(Object bean, String beanName)
                throws BeansException {
            return bean;
        }

        @Override
        public Object postProcessAfterInitialization(Object bean, String beanName)
                throws BeansException {
            if (bean instanceof Configuration) {
                ((Configuration) bean).set(transactionListenerProvider);
            }
            return bean;
        }
        
    };
}
```

Would you like to contribute a pull request that adds support for automatically registering `TransactionListenerProvider` beans?

**Comment by snicoll** [comment]
@Timmeey for the record, someone else already submitted a PR in the meantime.

**Comment by snicoll** [comment]
Closing in favour of PR #13331
