### ISSUE TITLE
Make SpringTransactionProvider public (JOOQ)

### ISSUE THREAD

**Issue by Raniz85** [spring-projects/spring-boot#13325]
I'm trying to provide a second DSLContext connected to a different database and I would like to reuse the *SpringTransactionProvider* from the JOOQ auto configuration but since that class has default access I can't access it.

Would it be possible to make it public instead of default?

**Comment by snicoll** [comment]
`SpringTransactionProvider` is public. What am I missing?

**Comment by Raniz85** [comment]
Seems to have changed in 1.5.10, my bad

**Comment by wilkinsona** [comment]
Duplicate of #11324
