### ISSUE TITLE
InetAddressFormatterTests reliance on DNS lookup

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#13326]
In `InetAddressFormatterTests` the test `convertFromStringToInetAddressWhenHostDoesNotExistShouldThrowException()`
attempts to convert a missing domain and expects an exception.

The operation of this test depends on your ISP.

Some will do the obvious and let the bad lookup fail.
Some will return the IP address of a help page.

**Comment by wilkinsona** [comment]
Duplicate of #11897
