### ISSUE TITLE
InMemoryAuditEventRepository causes memory leak

### ISSUE THREAD

**Issue by ask4gilles** [spring-projects/spring-boot#13335]
SB 1.5.9:
1. It seems like org.springframework.boot.actuate.audit.InMemoryAuditEventRepository is causing memory leak. See attached heap dump analysis.
[heapdump-1527921313266_Leak_Suspects.zip](https://github.com/spring-projects/spring-boot/files/2064765/heapdump-1527921313266_Leak_Suspects.zip)

2. org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration should only be triggered if  endpoints.auditevents.enabled=true

**Comment by wilkinsona** [comment]
I can't seen any sign of a leak. `InMemoryAuditEvenyRepository` will, by default, hold up to 4000 events. The heap dump analysis shows that it contains 309 events. Please note that we've [reduced the default size to 1000 in 2.0](https://github.com/spring-projects/spring-boot/issues/9056) although that would not have made a difference here.

We consider the endpoint to only be one way to view the auditing information. As such, it wouldn't be appropriate to disable auditing when the endpoint is disabled. Thanks anyway for the suggestion.

**Comment by ask4gilles** [comment]
@wilkinsona Thank you for your analysis.
