### ISSUE TITLE
JPA Autoconfigure to support ClasspathScanningPersistenceUnitPostProcessor

### ISSUE THREAD

**Issue by XhstormR** [spring-projects/spring-boot#13339]
I use spring-boot-starter-data-jpa to configure JPA automatically. I saw [ClasspathScanningPersistenceUnitPostProcessor](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.misc.entity-scanning) in the reference for spring-data-jpa and I want to use it. 

However, I found that using it must be manually configured LocalContainerEntityManagerFactoryBean, and so the automatic configuration of spring-boot-starter-data-jpa will not take effect.

It would be best if the following code configuration worked.

```kotlin
//Kotlin language

@Bean
open fun persistenceUnitPostProcessor(): ClasspathScanningPersistenceUnitPostProcessor {
    val persistenceUnitPostProcessor = ClasspathScanningPersistenceUnitPostProcessor("com.acme.domain")
    persistenceUnitPostProcessor.setMappingFileNamePattern("**/*Mapping.xml")
    return persistenceUnitPostProcessor
}
```

Sorry for my poor english.

**Comment by wilkinsona** [comment]
@XhstormR There is nothing poor about your English. Thank you for the suggestion.

Can you please describe in a bit more detail what you want to use `ClasspathScanningPersistencveUnitPostProcessor` for? It may already be possible to do it:

1. `LocalContainerEntityManagerFactoryBean` is already auto-configured with the base packages to scan. This can also be controlled using `@EntityScan`.
2. The `spring.jpa.mapping-resources` properties may already give you control over the mapping files.

**Comment by XhstormR** [comment]
@wilkinsona If it cannot, spring.jpa.mapping-resources is also a good choice, at least not requiring the persistence.xml file.

**Comment by snicoll** [comment]
@XhstormR sorry I don't understand the problem. Spring Boot scans entities and build a persistence.xml for you. If you don't like that, you can define an `orm.xml` with your configuration or, if necessary, add a `spring.jpa.mapping-resources` property to get more control over your mapping files. 

I don't think there's much else we should do. If you think otherwise, please clarify what the expected behaviour would be.

**Comment by XhstormR** [comment]
@snicoll I don't want to write SQL in a class, and I don't want to write all the SQL in an orm.xml, but write in multiple files. Each entity class corresponds to a mapping file, for example AccountMapping.xml, CarMapping.xml. The contents of these mapping files are mainly named-query.

I want the mapping file to be automatically scanned, just like the entity class, without needing to specify the file name.

**Comment by snicoll** [comment]
@XhstormR it looks like that's what the 6 lines of code in your original description is doing, is that correct?

**Comment by XhstormR** [comment]
@snicoll Yes，but not take effect，it need LocalContainerEntityManagerFactoryBean.

**Comment by snicoll** [comment]
I had a chat with @olivergierke and @jhoeller. Juergen reminded me that entities scanning is part of JPA while mapping file names have to be specified explicitly. There will not be a framework change for this and I am not keen to introduce one in Spring Boot.

You can post-process the `LocalContainerEntityManagerFactoryBean` and set the processor you have above if you really want to pursue this, something like

```java
public class MappingsScannerPostProcessor implements BeanPostProcessor {

	@Override
	public Object postProcessAfterInitialization(Object bean, String beanName)
			throws BeansException {
		if (bean instanceof LocalContainerEntityManagerFactoryBean) {
			postProcess((LocalContainerEntityManagerFactoryBean) bean);
		}
		return bean;
	}

	private void postProcess(LocalContainerEntityManagerFactoryBean emf) {
		emf.setPersistenceUnitPostProcessors(yourPostProcessor());
	}

}
```
