### ISSUE TITLE
Make JMX metrics domain configurable

### ISSUE THREAD

**Issue by markusheiden** [spring-projects/spring-boot#13356]
It would be nice, if `io.micrometer.jmx.JmxConfig` / `org.springframework.boot.actuate.autoconfigure.metrics.export.jmx.JmxProperties` in `JmxMetricsExportAutoConfiguration` would be configurable (`@ConfigurationProperties`).

I am deploying multiple spring boot apps to a Tomcat and would like to avoid JMX name clashes. Minimum requirement for that is to make the JMX domain configurable.

**Comment by snicoll** [comment]
Looks like an oversight to me.
