### ISSUE TITLE
ArrayIndexOutOfBoundsException while Enum field validation

### ISSUE THREAD

**Issue by pavel-pismerov** [spring-projects/spring-boot#13354]
Please, look at my post on [stackoverflow.com](https://stackoverflow.com/questions/50656089/model-validation-exception-with-spring-boot-2-0-2-release)

Validator gets wrong parameter's metadata. Seems that it gets default fields from _Enum_ type (_name_, _ordinal_)

It was working with Spring Boot 1.5.10 version and still works with Java and Spring Boot 2.0.2.

**Comment by snicoll** [comment]
Please do not cross post your question, the discussion can continue on SO.
