### ISSUE TITLE
Spring Websocket: header simpHeartbeat cannot be read

### ISSUE THREAD

**Issue by JohannesFluegel** [spring-projects/spring-boot#13369]
I am using spring-websocket-4.3.17.RELEASE. 
In `org.springframework.web.socket.messaging.StompSubProtocolHandler` it is tried to read the value of the simpHeartbeat header via
`long[] heartbeat = (long[]) connectAckHeaders.getHeader(SimpMessageHeaderAccessor.HEART_BEAT_HEADER);` (note: HEART_BEAT_HEADER = "simpHeartbeat")
It always returns null, because the headers of connectAckHeaders only contain the keys simpMessageType, simpConnectMessage, and simpSessionId. If you want to get the value of simpHeartbeat, first get `connectAckHeaders.getHeader("simpConnectMessage")`. This is a GenericMessage. Its headers contain the key simpHeartbeat.

**Comment by snicoll** [comment]
> I am using spring-websocket-4.3.17.RELEASE.

This issue tracker doesn't handle Spring Framework issues (they have a [dedicated issue tracker](https://jira.spring.io/projects/SPR/)). This looks like more of a question than a bug report to me so you may want to ask on StackOverflow.
