### ISSUE TITLE
Issue with Collection-based binding for Collections and multiple property sources

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-projects/spring-boot#13376]
Hi, 

As far as I see in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding: 

> If Collection properties are specified in multiple property sources, only the elements from the property source with the highest precedence will be used. Properties from different property sources will NOT be combined when binding to a Collection. For example, if a .properties file has
> foo[0] = 1
> foo[1] = 2
> and the Environment has
> foo=3,4
> the bound collection will only contain the elements 3 and 4
> 

I am using spring-boot 1.5.13 version and it seems that it is not correct when the signature of the list in the yaml differs from one to another property source.  

For example, I have two yaml files, application.yml and application-standalone.yml (for my standalone profile), where I define the list as: 

application.yml

```
test:
  myList:
    - one
    - two
```

application-standalone.yml
```
test:
  myList: onestandalone, twostandalone, threestandalone
```

On the other hand, I am loading the list through an object with @ConfigurationProperties which contains the list 'myList'

```
    @Bean
    @ConfigurationProperties(prefix = "test")
    public MyTest myTest() {
        return new MyTest();
    }
```
As far as I know, as the application-standalone.yml has higher priority (as it is the profile yml in contrast of the application.yml which is the base one), the loading of the list should be [onestandalone, twostandalone, threestandalone]. But it is not, the result is: [one, two, threestandalone]

It seems like, first of all, the properties from application-standalone.yml are bound to the list, and after it, the properties from application.yml are applied to it. 

This behavior only occurs when the sintaxis from the list differs from one property source to another. It the sintaxis is the same, the result is the expected one. 

Thanks!,

**Comment by mbhave** [comment]
The behavior described [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding) is with Spring Boot 2.0. There was some confusing behavior in the 1.5.x line with `@ConfigurationProperties` and lists (see #6793). We've fixed this in 2.0 with the new binding infrastructure.
