### ISSUE TITLE
Spring Boot 2 migration results in "Error executing DDL via JDBC Statement"

### ISSUE THREAD

**Issue by DmytroRybka** [spring-projects/spring-boot#13375]
After migration to `spring-boot-gradle-plugin` `2.0.2` from `1.4.6` I start getting :

```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: PUBLIC.USER
at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
```

With the `1.4.6` everything runs smooth. 
Exception comes during db initialization with `import.sql`

```
spring:
  jpa:
    hibernate:
      ddl-auto: create
```

**Comment by snicoll** [comment]
Upgrading from 1.4 to 2.0 also upgrades the Hibernate version you are using (as confirmed by the snippet you've shared). 

It is impossible for us to say if this is a problem in Spring Boot, Hibernate or your application. If you want us to investigate, please take the time to share a sample that we can clone and run ourselves.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by carlosag0712** [comment]
Hello, here's a repo show the problem described, it is only happening with spring boot 2+
https://github.com/carlosag0712/DEVCONNECTOR

**Comment by snicoll** [comment]
@carlosag0712 thanks for the feedback but that sample doesn't look  minimal and I can't build it

```
[ERROR]   The project io.agileintelligence:demo:0.0.1-SNAPSHOT (/Users/snicoll/Downloads/DEVCONNECTOR-master/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for gravatar:gravatar:jar is missing. @ line 66, column 21
```

Then your sample uses the MySQL dialect with H2 (which is not going to work very well). What are the instructions to reproduce the problem?

**Comment by snicoll** [comment]
`from` is a reserved keywords in many databases. I've renamed that field in both `Experience` and `Education` and the app starts fine.

**Comment by rajkumar-cp** [comment]
Hi ,

I am facing the same kind of issue. Could you please look into the same.

Git Repo : https://github.com/rajkumar-cp/SpringJDBCerrorissue

**Comment by snicoll** [comment]
@rajkumar-cp please do not comment on a closed issue to report an issue "of the same kind". Even if we can help you, we should not do it on an unrelated issue. I've had a look to your issue and it is related to #7706. If you still have a question, please ask on StackOverflow.
