### ISSUE TITLE
Request method 'POST' not supported while running test

### ISSUE THREAD

**Issue by Ben1980** [spring-projects/spring-boot#13371]
This simple spring boot 2.0.2 security [Example](https://github.com/Ben1980/spring-sec-problem.git) is giving `com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 405 Request method 'POST' not supported for http://localhost:8080/login` while running:

`@And("^the user clicks the login button$")
    public void theUserClicksTheLoginButton() throws IOException {
    page = page.getElementById("login").click();
}`

But the same example is running fine if executed normally.
I would consider this as a bug because i would expect the same behavior between test and production. 

This example would work with spring boot 1.5.6 and dependencies to `org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0` tests where behaving as production.

I was also asking on [StackOverflow](https://stackoverflow.com/questions/50612767/405-request-method-post-not-supported-when-testing-spring-application) but didn't get any further.

**Comment by bclozel** [comment]
I've answered your question on StackOverflow. Please continue the conversation there. Thanks!
