### ISSUE TITLE
Spring-Boot 2.0.2 actuator with Spring-Security, /shutdown is forbidden 

### ISSUE THREAD

**Issue by illingtonFlex** [spring-projects/spring-boot#13370]
My Spring-Boot config is working fine except the /actuator/shutdown endpoint is forbidden. I can access all of the other endpoints using http basic auth, but trying a POST to shutdown returns 403.

```
        compile('org.springframework.boot:spring-boot-starter-security')
```

```    
@Configuration
    public static class ActuatorWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
        protected void configure(HttpSecurity http) throws Exception {
            http.requestMatcher(EndpointRequest.toAnyEndpoint()).authorizeRequests()
                    .anyRequest().hasRole("ACTUATOR")
                    .and()
                    .httpBasic();
        }
    }
```

```
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.git.mode=full
management.endpoint.shutdown.enabled=true
spring.security.user.name=actuator
spring.security.user.password=password
spring.security.user.roles=ACTUATOR
```

**Comment by snicoll** [comment]
This behaviour is [documented in the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-csrf)

**Comment by ahoehma** [comment]
@snicoll I come here because I have currently the same effect of getting a 403 for /actuator/shutdown . All my other actuators secured as well an there I have no problem. And I checked the link you postet 2018 here and I can't find the "special" thing about shutdown. Please give me a hint.

Thanks
