### ISSUE TITLE
Spring Boot fails to start when a configuration class contains a field named 'includes'

### ISSUE THREAD

**Issue by parvanov** [spring-projects/spring-boot#13381]
Spring Boot v2.0.2.RELEASE

Spring boot fails to start when a configuration class contains a field named `**includes**` that is of type `List<SomeClass>`.

Please consider the configuration classes:

```java
import lombok.Data;

@Data
public class LogIncludeField {
	String str;
}
```

```
@Data
@Configuration
@ConfigurationProperties
@PropertySource({"${log.config.location}"})
public class LogConfiguration {
	private List&lt;LogIncludeField&gt; **includes**;
}
```

Staring with them produces the error:

```
APPLICATION FAILED TO START
 
Description:

Failed to bind properties under 'includes' to >java.util.List<com.....LogIncludeField>:

>   Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.List<com.....LogIncludeField>]

Action:

Update your application's configuration
```

However, renaming the '**includes**' field to '**include**' or '**abc**', works as normal.
Or, keeping the field '**includes**' but changing its type to `List<String>` also makes it work.
The following class works:

```java
@Data
@Configuration
@ConfigurationProperties
@PropertySource({"${log.config.location}"})
public class LogConfiguration {
	private List&lt;LogIncludeField&gt; **include**;
	private List&lt;LogIncludeField&gt; **abc**;
	private List&lt;String&gt; **includes**;
}
```

This is the combination of spring boot I'm using:

```
spring-boot-starter-parent - 2.0.2.RELEASE

spring-boot-starter
spring-boot-configuration-processor
spring-boot-starter-web
spring-boot-starter-actuator
spring-boot-properties-migrator
```

**Comment by wilkinsona** [comment]
Thanks, but it's rather hard to tell what's going on from a few snippets of code. I can see that there are a few things that don't look quite right:

1. A `@ConfigurationProperties` class should not be annotation with `@Configuration`. It should either be a `@Component` or enabled using `@EnableConfigurationProperties(LogConfiguration.class) on a separate `@Configuration` class.
2. You need to be careful when using `@PropertySource` as the properties it loads may be available too late. See [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-environment-or-application-context) for more details.

Beyond that, the use of Lombok also makes problem diagnosis harder.

If correcting the two points above does not resolve the problem for you, can you please provide a complete minimal sample that we can run to reproduce the problem? The sample can be provided as a zip attached to this issue or in a repository on GitHub.

**Comment by parvanov** [comment]
Please find attached a sample.
[Zzz.zip](https://github.com/spring-projects/spring-boot/files/2078524/Zzz.zip)

I've found that naming doesn't really matter - only if the config file has matching fields. Renaming was hiding the values and thus no parsing was needed.

I've also found that it fails only when loading data with @PropertySource
When loading directly from application.yml with prefix it works as expected.

Not sure if this is a bug or not.
However, this prevents separating data in multiple files.

**Comment by parvanov** [comment]
Forgot to mention that it is working in spring boot 1.5.10
When migrating to 2.0.2 we encountered the issue.

**Comment by snicoll** [comment]
@parvanov thanks for the sample (there are several weird constructs in it). However, it doesn't work with `1.5.10.RELEASE` either

```

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target {xyz: null, abc: null} failed:

    Property: target.abc
    Value: 
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.util.List' for property 'abc'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.zzz.loggers.LogIncludeField' for property 'abc[0]': no matching editors or conversion strategy found

    Property: target.xyz
    Value: 
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'com.zzz.loggers.LogIncludeField' for property 'xyz'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.zzz.loggers.LogIncludeField' for property 'xyz': no matching editors or conversion strategy found


Action:

Update your application's configuration
```

I don't really understand how you expect that sample to work really. Your `@ConfigurationProperties` must have a prefix and adding `@PropertySource` on it is asking for trouble as the evaluation order of the annotation won't be as you would expect.

And what is the relationship with `includes` per your original description?

I've cleaned up your sample and the binding is `null` in both Spring Boot 1.x and 2.x

```
Loaded config: {xyz: null, abc: null}
```

Please rework your sample to show that your sample works with 1.5 and does not in 2.0 (only by changing the version in the pom).

**Comment by parvanov** [comment]
Thank you for the explanation.
It was my misunderstanding of `@PropertySource` that was causing the problems I had.
