### ISSUE TITLE
@Transactional not working with Quartz job

### ISSUE THREAD

**Issue by anabulsi** [spring-projects/spring-boot#13380]
`@Transactional` annotation is working like charm for all components except Quartz jobs. I'm using Spring Boot Starter Quartz and noticed with behavior with Spring Boot `2.0.2-STABLE` and `2.1.0-SNAPSHOT`. I haven't tested earlier versions. 

This behavior was observed when using JPA Streams within a Quartz job, Hibernate kept complaining that Streams must be started within a transaction even though the class was annotated with `@Transactional`. I tried starting a  transaction manually using:

```java
TransactionStatus ts = transactionManager.getTransaction(new DefaultTransactionDefinition());
```

and it worked. I tested several several `@Transactional` annotated classes and methods for transaction availability using `TransactionSynchronizationManager.isActualTransactionActive()` and the result was true except for Quartz jobs. `@Transactional` has no effect on Quartz jobs.

The easiest way to reproduce this is to clone Spring Quartz Sample `https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-quartz` and add `@Transactioal`  to `SampleJob` class and observe the behavior.

**Comment by snicoll** [comment]
>  add @Transactioal to SampleJob class and observe the behavior.

None of this is related to Spring Boot (but Quartz and the Quartz integration in Spring Framework).  

Your transaction demarcation shouldn't be specified at the Job level but on the actual implementation (service layer). If you want to pursue and get transaction support at the job level, please raise an issue [in the Spring Framework issue tracker](https://jira.spring.io/browse/SPR)
