### ISSUE TITLE
Don't fail build on duplicate module-info classes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13403]
It's common for multiple jars to contain `module-info` classes but currently our build fails with such a setup.

**Comment by philwebb** [comment]
See also https://github.com/basepom/duplicate-finder-maven-plugin/issues/31

**Comment by bclozel** [comment]
Can we upgrade that plugin to 1.3.0 instead and remove all the `module-info` ignored class patterns? It seems this is now the case by default in that plugin.

**Comment by philwebb** [comment]
> shouldn't that be backported to 2.0.x?

We can backport if the build fails, but currently it seems fine.
