### ISSUE TITLE
Deprecate micrometer's enabled flags (in favour of excluding the auto-configuration)

### ISSUE THREAD

**Issue by ramato-procon** [spring-projects/spring-boot#13408]
[SpringBoot 2.0.2]
Currently you have only following properties to disable metric binders:
```
management.metrics.binders.files.enabled=false
management.metrics.binders.integration.enabled=false
management.metrics.binders.jvm.enabled=false
management.metrics.binders.logback.enabled=false
management.metrics.binders.processor.enabled=false
management.metrics.binders.uptime.enabled=false
management.metrics.web.server.auto-time-requests=false
```
Autoconfigured metric binders such as [tomcat](https://github.com/spring-projects/spring-boot/blob/e72506c35368c412ad020ab4d15f8f32798c50d1/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/web/tomcat/TomcatMetricsAutoConfiguration.java), [rabbitmq](https://github.com/spring-projects/spring-boot/blob/e72506c35368c412ad020ab4d15f8f32798c50d1/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/amqp/RabbitMetricsAutoConfiguration.java) cannot be disabled.
Please add properties to disable AutoConfiguration for these binders.

**Comment by snicoll** [comment]
This section of the doc explains [how to disable metrics](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_per_meter_properties). 

@jkschneider what are your thoughts on this? Are those `enabled` flag a different way of achieving the same thing or is there a performance impact to take into account?

**Comment by snicoll** [comment]
> Autoconfigured metric binders such as tomcat, rabbitmq cannot be disabled.

@ramato-procon to be clear, my first comment was for you. They can be disabled, see the docs for more details.

**Comment by jkschneider** [comment]
@snicoll It depends on the binder. For example, the logback binder adds a `TurboFilter` that remains even if the metric is disabled from the perspective of an individual `MeterRegistry`.

**Comment by snicoll** [comment]
The mix between dedicated `enabled` flags and `management.metrics.enable` can be confusing and we don't want to add a dedicated `enabled` flags for everything.

When users want to disable the feature altogether we request them to exclude the auto-configurations. For consistency, we should probably do that and deprecate those `enabled` flags. 

@jkschneider please correct me if that's not an accurate summary of our discussion.

**Comment by jkschneider** [comment]
@snicoll I should add that generally binders use a name taxonomy that has a common prefix. So Tomcat metrics will all have names like `tomcat.*`. Setting `management.metrics.enable.tomcat=false` should be sufficient to disable all tomcat metrics emanating from that binder.

**Comment by jkschneider** [comment]
That last bit seems like a bug @ramato-procon. The intended behavior is to match the most specific property.

**Comment by snicoll** [comment]
We've decided to deprecate the `.enabled` flags and redirect users to excluding the auto-configuration if they really want to do that (rather than using `management.metrics.enable.*`). I am not sure we'll have a fine grained auto-configuration model that matches those flags (perhaps all JVM metrics will stay in the same auto-config).
