### ISSUE TITLE
Controller makes changes to entity attributes

### ISSUE THREAD

**Issue by maskleo** [spring-projects/spring-boot#13405]
version :1.5.4.RELEASE

```java
public BaseResp<CreditCardCheckResult> checkStatus
```
Part of the attributes of  `CreditCardCheckResult` 

```java
protected String OrderID;

protected String PAN;

protected String TransDate;

protected String TransTime;

protected String TransAmt;

protected String ResponseCode;
```
I get the end result:
```json
{
    "code": "20000",
    "msg": "succeed",
    "desc": "成功",
    "data": {
        "serialNum": "180528111500002",
        "remark": "拒绝交易",
        "responseCode": "05",
        "transDate": "20180601",
        "pan": "552046******3802",
        "orderID": "P20180601025",
        "transAmt": "1",
        "transTime": "051353"
    },
    "ok": true
}
```

The entity's property case has changed.
Is this normal or a bug?

**Comment by philwebb** [comment]
This is the standard behavior for Jackson. I strongly recommend that you follow usual Java conventions and start your member variables with a lowercase.

In the future, please ask this sort of question on stackoverflow.com or join us on gitter.im.

**Comment by maskleo** [comment]
Thank you for your reply.
The data returned by the third party is called. I just try to restore the original data as much as possible. The attributes are as consistent as possible.
