### ISSUE TITLE
Default Whitelabel Error Page is not adequate for final users nor developers

### ISSUE THREAD

**Issue by TieSKey** [spring-projects/spring-boot#1340]
The new default error page "Whitelabel Error Page" is pointless as it is:
- Not suitable for end users of the web site. It is ugly and does not state the error clearly enough for a final user.
- Useless for a developer who needs an exception stack trace. Actually, this exception is NOT logged by default on the java console either. You have to catch the error with javascript and look for the response text to know what the error was.

Idk how to report this kind of "bug" so I'm willing to edit it as indicated.

Plz, improve the whitelabel error page or return to the previous version at least.
Implementing my custom error page is not a valid solution to the issue that the default is as useless as an existent page.

Sorry if I sound rude, english is not my mother language.

**Comment by dagnelies** [comment]
I preferred the default tomcat error page too. my 2 cents.

...I spent hours to find the `@EnableAutoConfiguration(exclude=ErrorMvcAutoConfiguration.class)` trick.

**Comment by philwebb** [comment]
@dagnelies Out of interest, are you deploying your application as a WAR or using embedded Tomcat in a JAR?

**Comment by dagnelies** [comment]
Both actually. As a war for deployment, as embedded when developping.

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
