### ISSUE TITLE
There are two active profiles when using environment variable(spring_profiles_active=prod)

### ISSUE THREAD

**Issue by wangjianwen** [spring-projects/spring-boot#13418]
Dear @bclozel:

We will continue to discuss the previous issue in [https://github.com/spring-projects/spring-boot/issues/13341](https://github.com/spring-projects/spring-boot/issues/13341).  Below I will show the process of producing the provious problem:

-  step 1: In Spring Cloud Common Project `BootstrapApplicationListener.mergeAdditionalPropertySources`

```java
private void mergeAdditionalPropertySources(MutablePropertySources environment,
			MutablePropertySources bootstrap) {
		PropertySource<?> defaultProperties = environment.get(DEFAULT_PROPERTIES);
		ExtendedDefaultPropertySource result = defaultProperties instanceof ExtendedDefaultPropertySource
				? (ExtendedDefaultPropertySource) defaultProperties
				: new ExtendedDefaultPropertySource(DEFAULT_PROPERTIES,
						defaultProperties);
		... ...
		addOrReplace(environment, result);
		addOrReplace(bootstrap, result);
	}
```

In the above code, defaultProperties is replaced with ExtendedDefaultPropertySource (load configuration information from the file bootstrap.properties or bootstrap.yaml ).  Moreover, defaultProperties has lower priority than systemEnviroment. In other words, **spring.profiles.active=local (in bootstrap.properties) has lower priority than spring_profiles_active=alpha (environment variables)**.

- step 2: In Spring boot project `ConfigFileApplicationListener.Loader`

```java
 private SpringProfiles bindSpringProfiles(PropertySources propertySources) {
            SpringProfiles springProfiles = new SpringProfiles();
            RelaxedDataBinder dataBinder = new RelaxedDataBinder(springProfiles,
                    "spring.profiles");
            dataBinder.bind(new PropertySourcesPropertyValues(propertySources, false));
            springProfiles.setActive(resolvePlaceholders(springProfiles.getActive()));
            springProfiles.setInclude(resolvePlaceholders(springProfiles.getInclude()));
            return springProfiles;
 }
```

After method `RelaxedDataBinder.bind`  in the above code, we expect:
       `springProfiles.active = alpha`

but actually, the result is 
       `springProfiles.active = local`

The reason is that the property value in systemEnviroment  will be overrided the value in defaultProperties.  This situation should not occur in normal circumstances.

**Comment by mbhave** [comment]
@wangjianwen Thanks for the explanation but please don't open duplicate issues. As @bclozel mentioned here, `bootstrap.properties` is a Spring Cloud feature. I don't think there is anything we can do in Spring Boot about this as the code that causes `spring_profiles_active` from the systemEnvironment is part of the [Spring Framework](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/MutablePropertyValues.java#L170). 

I'll leave the issue open to see what the rest of the team thinks.

**Comment by snicoll** [comment]
@wangjianwen thanks but @bclozel already answered you on the original issue you've raised.

>  if you don't think this behavior is right, you can get in touch with the Spring Cloud team about that.

We don't discuss or deal with Spring Cloud-related code here. Please raise this [in the appropriate issue tracker](https://github.com/spring-cloud/spring-cloud-commons)
