### ISSUE TITLE
BackgroundPreinitializer probably doesn't need to do Charset.availableCharsets() any more

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13423]
I think `BackgroundPreinitializer` probably initializes `Charset.availableCharsets()` to avoid it happening in `StringHttpMessageConverter`. The internals of `StringHttpMessageConverter` changed in Spring 5 so that `Charset.availableCharsets()` is called lazily, so we probably don't have to pay this cost on startup in Spring boot 2.0, even in a background thread. It causes quite a bit of activity including GC pressure.

**Comment by bclozel** [comment]
For reference, the improvement in Spring Framework has been done in [SPR-15502](https://jira.spring.io/browse/SPR-15502), and the Spring Boot change in #11570.

**Comment by dsyer** [comment]
So if we fix this it doesn't need to be backported, I guess.
