### ISSUE TITLE
Logging to $TMP combined with SizeAndTimeBasedRollingPolicy can lead to significant garbage being created during startup

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13425]
When `SizeAndTimeBasedRollingPolicy.start()` is called it starts a `SizeAndTimeBasedFNATP` which results in a call to `ch.qos.logback.core.rolling.helper.FileFilterUtil.filesInFolderMatchingStemRegex(File, String)`. The second string argument is a regular expression that's used in a filename filter where it's passed into `String.matches`:

```
public static File[] filesInFolderMatchingStemRegex(File file, final String stemRegex) {

    if (file == null) {
        return new File[0];
    }
    if (!file.exists() || !file.isDirectory()) {
        return new File[0];
    }
    return file.listFiles(new FilenameFilter() {
        public boolean accept(File dir, String name) {
            return name.matches(stemRegex);
        }
     });
 }
```

`String.matches(String)` compiles a regular expression `Pattern`. This is currently happening once for every file or directory in `file` which, by default, is `$TMP`. I've currently got in excess of 46000 files in my laptop's temp directory which results in 64MB of garbage being created by the `String.matches(String)` calls which accounts for 10% of GC pressure.

This may end up just being a Logback performance improvement (the regular expression could be compiled once and reused), but we may also want to reconsider our default logging configuration.

**Comment by wilkinsona** [comment]
I've opened [LOGBACK-1409](https://jira.qos.ch/browse/LOGBACK-1409).

**Comment by vpavic** [comment]
> but we may also want to reconsider our default logging configuration

Are you referring to changing Boot's default Logback configuration, or possibly changing the default logging provider altogether?

**Comment by wilkinsona** [comment]
I was referring to possibly changing Boot's default Logback configuration.

**Comment by wilkinsona** [comment]
On closer inspection, the logging to `$TMP` isn't done by default. A `logback.xml` that enabled file-based logging had found its way onto the classpath. I think the Logback issue I've opened is sufficient to address this.
