### ISSUE TITLE
JSP files are not loaded starting with version 1.4.3 

### ISSUE THREAD

**Issue by DanielLupu** [spring-projects/spring-boot#13420]
If you will create an MVC application with Spring-Boot version 1.4.3 (or even release 1.5.13.RELEASE) and place JSP files under src/main/resources/META-INF/resources/WEB-INF/view then these are not working. After build these files are copied properly under META-INF/resources/WEB-INF/view/ folder in spring boot JAR, however the problem seems to be due to spring boot maven plugin. 
If parent pom is with version 1.4.3 but spring-boot maven plugin: 
```
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>1.4.2.RELEASE</version>
      </plugin>
    </plugins>
  </build>
```
then it is working.

For example please check pom.xml file from "Web application in jar packaging" link: https://www.logicbig.com/tutorials/spring-framework/spring-boot/boot-exploded-war.html

There are a dozen of examples on net with JSP with spring-boot but they are using command: mvn spring-boot:run 
In all these cases the application is working because JSP files are not loaded from JAR file, these are loaded directly from /src/main/resources/META-INF/resources/WEB-INF/view. If you will copy their jar in another location and execute it like any java jar file then the problem will appear. 

Please solve this issue because is very important for any JSP web-application when you will try to execute a spring-boot JAR file in staging or production.

**Comment by wilkinsona** [comment]
Thanks for the report but, as [noted in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-jsp-limitations), JSPs are only supported with war packaging.

**Comment by DanielLupu** [comment]
Probably you didn't read the bug description, it is not with war packaging it is with JAR packaging

**Comment by wilkinsona** [comment]
> Probably you didn't read the bug description

I read it. We never close an issue without reading it.

> it is not with war packaging it is with JAR packaging

That is the problem. JSPs are not supported with jar packaging. If you want to use JSPs, you should package your application as a war file. Note that an executable war file can still be run using `java -jar` so you don't lose anything by changing the packaging format.

**Comment by DanielLupu** [comment]
Ok, I'm more confusing for documentation, because it was working until version 1.4.2 using executable JARs. In spec: "An executable jar does not work because of a hard-coded file pattern in Tomcat". I think the problem is not Tomcat but something that you have changed starting with 1.4.3 since I didn't change my Tomcat version only spring version. 
So in my opinion documentation should be updated or simply deleted this statement from JSP limitations section. 

Here you can find a workaround for JSP limitations, but this developer was lucky to use version 1.4.2. This limitation is caused by Spring-Boot code after version 1 changes instead of Tomcat hard-coded file pattern:
https://www.logicbig.com/tutorials/spring-framework/spring-boot/boot-serve-dynamic.html

**Comment by wilkinsona** [comment]
Ok. I have strengthened the wording of the limitations in https://github.com/spring-projects/spring-boot/commit/9d9acc92e328159063b916083a2988b563869e04.
