### ISSUE TITLE
Error while sourcing _spring on zsh

### ISSUE THREAD

**Issue by martinicr** [spring-projects/spring-boot#1342]
Hi, I just installed springboot via GVM and when sourcing the _spring completion, I got the following errors:

_spring:4: bad floating point constant
_describe:27: condition can only be used in completion function

I'm kind of new with zsh so, don't know if I missing something.

Regards, 
Martin

**Comment by justincalleja** [comment]
Same issue. Copying `$SPRING_BOOT/shell-completion/zsh/_spring` to `$HOME/.oh-my-zsh/completions` works as per output of `echo $fpath` suggested by @philwebb - thanks!
