### ISSUE TITLE
ErrorPageFilter causes an infinite loop when error page produces an error

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1343]
This was originally reported against Spring: https://jira.spring.io/browse/SPR-12066. It's reproducible. We need to short-circuit the error filter so that it gives up if the forward to the error page produces an error.

**Comment by dingziyang** [comment]
Today， I get this Error. I does not know Why ? Please tell me how to resolve it .Thanks.

**Comment by snicoll** [comment]
@dingziyang this issue was closed over 3 years ago. We don't use the tracker for questions, please ask on StackOverflow or join us on Gitter.
