### ISSUE TITLE
Autoconfigure Reactor Netty for CloudFoundry endpoint 

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-projects/spring-boot#13445]
CloudFoundry AppsManager actuator [features](https://docs.pivotal.io/pivotalcf/2-1/console/using-actuators.html) aren't working with Reactor Netty by default. CloudFoundry endpoint is returning links without **https** so browser doesn't send request to /cloudfoundryapplication/* endpoints because they are not secure. 

response from /cloudfoundryapplication
```javascript
{
  "_links": {
    "httptrace": {
      "href": "http:\/\/actuator-app.cfapps.io\/cloudfoundryapplication\/httptrace",
      "templated": false
    },
...
...
  }
}
```
Spring Boot 2.1 is now using Reactor Netty 0.8 which has X-Forwarded-* HTTP header support.

Following configuration made Apps manager features work again with Reactor Netty
```java
@Configuration 
class NettyConfiguration {

	@Bean
	WebServerFactoryCustomizer<NettyReactiveWebServerFactory> configure() {
		return factory -> factory.addServerCustomizers(new EventLoopNettyCustomizer());
	}

}

class EventLoopNettyCustomizer implements NettyServerCustomizer {

    @Override
    public HttpServer apply(HttpServer httpServer) {
    	return httpServer.forwarded();
    }
}
```
As *server.use-forward-headers* are autoconfigure to true for CloudFoundry and Heroku platforms, ReactiveWebServerFactoryCustomizer could use this autoconfigured value and setup servers to use forwarded headers.

**Comment by mbhave** [comment]
@nkolosnjaji thanks, but we already have an issue open for supporting X-Forwarded-* headers for WebFlux application [here](#10900).
