### ISSUE TITLE
Tomcat 8.5.31 in Spring Boot 2.0.2 fails to validate certain domains, resulting in HTTP 400 responses

### ISSUE THREAD

**Issue by rgacki** [spring-projects/spring-boot#13451]
Spring Boot 2.0.2 ships with Tomcat 8.5.31, when spring-boot-starter-tomcat is used. This Tomcat version introduced a stricter domain name validation, which causes problems in networks, that have hyphens in their TLDs (e.g. `.acme-xy`). If such a domain is validated, Tomcat will respond the request with HTTP status 400 and terminate the connection. There are no logs written or exceptions thrown.

The issue is explained in [ASF Bugzilla – Bug 55917](https://bz.apache.org/bugzilla/show_bug.cgi?id=55917)

I just want to report this, because I was bitten by this problem and it took me a day to figure out the cause.

Workaround: Either downgrade to Tomcat 8.5.30 or use another embedded web server.

**Comment by snicoll** [comment]
Thanks but this has been reported several times already. For instance #13236
