### ISSUE TITLE
Cache configurations are imported even if CacheAutoConfiguration is not enabled

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13478]
The `CacheAutoConfiguration` is `@ConditionalOnBean(CacheAspectSupport.class)` and this condition does not match in a vanilla empty Spring Boot app, so the `CacheAutoConfiguration` itself is not loaded. But its imports are, so you always pay the price of processing the beans in `GenericCacheConfiguration, `RedisCacheConfiguration, `SimpleCacheConfiguration`, `NoOpCacheConfiguration.class`, (as well as `CacheAutoConfiguration` up to the point where the condition fails to match). The other cache configurations fail condition matches, but those ones are always active, it seems. Given the cost of processing `@Configuration` this perhaps should be avoided.

**Comment by snicoll** [comment]
Thank you, I've noticed that in a while and didn't take the time to analyse why the nested conditions would show up even if `@EnableCaching` is missing. I think we might have a similar situation somewhere else so I'll look that up too.

**Comment by snicoll** [comment]
It turns out that those classes are in the report but aren't instantiated. See #13509 for more context as why the auto-configuration wrongly report them.
