### ISSUE TITLE
java -jar VS  mvn spring-boot:run

### ISSUE THREAD

**Issue by izern** [spring-projects/spring-boot#13472]
Using java -jar consumes more memory than mvn spring-boot:run or using IDE.

##jconsole JVM overview, but it's Chinese.

mvn spring-boot:run 
![image](https://user-images.githubusercontent.com/17672970/41364230-abf8961c-6f68-11e8-8c26-9b5af6f8b978.png)
Memory:  ≈ 400M
java -jar
![image](https://user-images.githubusercontent.com/17672970/41364261-c6b26ef6-6f68-11e8-9b48-cc8c067916bc.png)
Memory:  ≈ 1G

and finded this
[https://github.com/spring-projects/spring-boot/issues/6177](#6177)

springboot version 1.5.8.RELEASE
os: linux x64
jdk:1.8

**Comment by wilkinsona** [comment]
Thanks for the report, but those stats from JConsole are rather meaningless on their own. For example, while the current heap size with `mvn spring-boot:run` is 164MB whereas it's `java -jar` it is 648MB that doesn't tell us anything about how much memory is actually being used as we don't know how many of the objects on the heap are reachable. Garbage collection may have run recently in the `java -jar` case, freeing up a large amount of heap.

I've you'd like us to spend some time investigating the problem, please provide a small sample that we can run with `mvn spring-boot:run` and `java -jar` and observe the different memory usage.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
