### ISSUE TITLE
Add support for multiple Rest Docs customizers

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#13491]
In Spring Cloud Contract we leverage the:

- `RestDocsWebTestClientConfigurationCustomizer`,  [example of usage](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockWebTestClientConfiguration.java)
- `RestDocsRestAssuredConfigurationCustomizer`,  [example of usage](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockRestAssuredConfiguration.java)
- `RestDocsMockMvcConfigurationCustomizer`, [example of usage](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockRestDocsConfiguration.java)

to add the `WireMockSnippet` as an additional default. Since those customizers are registered by Spring Cloud Contract it seems that the user can't register their own beans. It would be great to add support of multiple beans of those types

**Comment by eddumelendez** [comment]
@wilkinsona can you confirm is it feasible to do this? IMHO, I think it is and I can take it. Sorry if this sounds rude.

**Comment by wilkinsona** [comment]
It doesn’t seem rude at all. Yeah, I think this is feasible. We need to autowire a list of customisers rather than only one. A pull request wouid be most welcome.

**Comment by wilkinsona** [comment]
Closing in favour of PR #13498
