### ISSUE TITLE
Maximum pool size is growing with the amount of repository classes

### ISSUE THREAD

**Issue by Maze-fr** [spring-projects/spring-boot#13494]
Hello,

I have an issue for which I don't find any equivalent problem anywhere, so I decided to post it here, because I think it's a bug and not a support question.

My configuration :
- Spring Platform Athens-SR6, so Spring Boot 1.4.7 (yes, I know, it's old... but I didn't find any fix about my problem, so I assume it's still going on)
- The only override is Hibernate version to 5.2.12
- Hikari CP (2.4.7 as it is from Athens-SR6)

Here is my "test" case :
I'm working in a relatively big project in which we have around 50 repository classes and more than 70 entities.

The problem is that when the amount of repository classes was growing, we had a not clearly understandable error message when "Spring Booting" the app.
After investigating about it, the problem appeared to be that we had to set a bigger maximum pool size. And so with time, we went from 10 to 50...
Note that my minimum idle for Hikari is 0.

So here is my bug report :
When booting, the application shouldn't take one connection for each repository __all in the same time__, but queue in the pool.

Unfortunately, I can't provide a code sample. To paraphrase "Steel Panther" :
"My heart is yours, but my code is not community property", sorry.

Nevertheless, I can provide the pieces of code used to configure Hikari and Hibernate :
```java
public DataSource getDataSource() {
        final HikariDataSource dataSource = new HikariDataSource();
        dataSource.setPoolName(dataSourceName + "Pool");
        dataSource.setDriverClassName(getDriverClassName());
        dataSource.setJdbcUrl(formatDbUrl());
        dataSource.setUsername(getRequiredProperty("username"));
        dataSource.setPassword(getRequiredProperty("password"));
        dataSource.setConnectionTestQuery(getOptionalProperty("connectionTestQuery", "select 1"));
        dataSource.setIdleTimeout(Integer.valueOf(getOptionalProperty("idleTimeout", "600000")));
        dataSource.setMinimumIdle(Integer.valueOf(getOptionalProperty("minimumIdle", "0")));
        dataSource.setMaximumPoolSize(Integer.valueOf(getOptionalProperty("maximumPoolSize", "10")));
        return dataSource;
}

public Properties getHibernateProperties() {
        final Properties properties = new Properties();
        properties.put("hibernate.dialect", getDialect());
        properties.put("hibernate.show_sql", env.getProperty("hibernate.show_sql", "false"));
        properties.put("hibernate.format_sql", env.getProperty("hibernate.format_sql", "false"));
        return properties;
}
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by wilkinsona** [comment]
Ok, thanks. I'll close this one for now. We can re-open it if you are able to provide a sample.
