### ISSUE TITLE
Purge private classes and interfaces in `@Bean` methods

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13490]
I would like Spring Boot autoconfiguration to be a public (or at least package-private) contract, so that I can use it to create functional bean registrations with all the same features. There's a barrier to doing that, which is that there are some private types that can't be used, even from a class in the same package.

There are a bunch of these in Spring Boot autoconfiguration, generally following one of two patterns. The first is a private class with a public interface, e.g. in `ErrorMvcAutoConfiguration`:

```java
	@Bean
	public ErrorPageCustomizer errorPageCustomizer() {
		return new ErrorPageCustomizer(this.serverProperties);
	}

	private static class ErrorPageCustomizer implements ErrorPageRegistrar, Ordered {
		...
	}
```

The second is a private class with a private interface, e.g. in `WebMvcAutoConfiguration`:

```java
	@Configuration
	@ConditionalOnEnabledResourceChain
	static class ResourceChainCustomizerConfiguration {

		@Bean
		public ResourceChainResourceHandlerRegistrationCustomizer resourceHandlerRegistrationCustomizer() {
			return new ResourceChainResourceHandlerRegistrationCustomizer();
		}

	}

	interface ResourceHandlerRegistrationCustomizer {

		void customize(ResourceHandlerRegistration registration);

	}

	private static class ResourceChainResourceHandlerRegistrationCustomizer
			implements ResourceHandlerRegistrationCustomizer {
		...
	}
```

**Comment by dsyer** [comment]
The second pattern is the most pernicious (the first can be worked around by using the public interface). In spring-boot-autoconfigure it occurs 3 times:

```
WebMvcAutoConfiguration.ResourceChainResourceHandlerRegistrationCustomizer
HazelcastJCacheCustomizationConfiguration.HazelcastPropertiesCustomizer
WebFluxAutoConfiguration.ResourceChainResourceHandlerRegistrationCustomizer
```

The first pattern is more widespread. I can generate a list if necessary.

**Comment by wilkinsona** [comment]
Generally speaking, I think we should make things package-private and no more. However, there are a few types that I think should be made more visible than that.

For example, `ErrorPageCustomizer` is exposed by a public method on `ErrorMvcAutoConfiguration`. This, among other things, breaks the javadoc for `ErrorMvcAutoConfiguration` as we end up with a link to https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-autoconfigure/apidocs/org/springframework/boot/autoconfigure/web/servlet/error/ErrorMvcAutoConfiguration.ErrorPageCustomizer.html?is-external=true. It doesn't exist and redirects to https://spring.io/projects/spring-boot.

**Comment by wilkinsona** [comment]
I think #13795 has (largely) taken care of this. If we need further changes, such as those proposed in #14399, I think it makes sense to do so in small, targeted issues and PRs.
