### ISSUE TITLE
Spring Boot 1.5.14 introduced a breaking Lombok change - Lombok 1.16.22

### ISSUE THREAD

**Issue by davidgoate** [spring-projects/spring-boot#13492]
Spring Boot 1.5.14 isn't backward compatible with some Lombok usage. Updating Lombok from `1.16.20` -> `1.16.22` introduces a change for constructor generation (see https://projectlombok.org/changelog) - this was not backwards compatible and was fixed in `1.18.0`.

Manually updating the dependency in `pom.xml` fixes this for now.

```xml
 <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.0</version>
            <optional>true</optional>
</dependency>
```

rather than using the managed version:

```xml
 <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
</dependency>
```

Also see: https://github.com/rzwitserloot/lombok/issues/1731

**Comment by wilkinsona** [comment]
Thanks for the report, but our position is that this the price that you pay for using Lombok and its approach to breaking changes being enabled by default in maintenance releases (A similar change was made in 1.6.20 (see https://github.com/spring-projects/spring-boot/issues/12568)). 

For those that do not want to upgrade to a new minor version (1.18.0), I would recommend setting `lombok.noArgsConstructor.extraPrivate=false` to disable the problematic behaviour.

**Comment by davidgoate** [comment]
@wilkinsona thanks for the clarification.

**Comment by victorwss** [comment]
@wilkinsona Unfortunately, lombok do not uses semantic versioning yet. So, you should not assume that when lombok authors upgrade the third number, that they are doing maintenance releases, nor that when they upgrade the second, that it is a minor release. So far, almost every version release breaks something or introduces major new features even if only the third versioning number changes. In lombok, so far, there is no concept of major, minor or maintenance release, there is simply "something was released".

**Comment by wilkinsona** [comment]
It’s already clear that Lombok doesn’t follow semantic versioning. They do, however, have the concept of minor releases. The theory of their approach is described in the [`Version` class](https://github.com/rzwitserloot/lombok/blob/2c5395d4c80458d01f7a720b2ad667d165357339/src/core/lombok/core/Version.java#L69-71) where it discusses the relationship between release names and version numbers:

>  The release name is a string (not numbers). Every time a new release has a significantly improved feature set, a new release name is given. Thus, many versions can carry the same release name. Version bumps and release names are not related; if a new version of lombok is entirely backwards compatible with a previous one, but also adds many new features, it will get only a minor version bump, but also a new release name.

Short of never upgrading Lombok, I see no alternative but to continue with our current approach.
