### ISSUE TITLE
Issue with Spring profiles

### ISSUE THREAD

**Issue by preetigupta25** [spring-projects/spring-boot#13504]
In the legacy app I am handling, I have three yaml files for profiles. application.yaml, application_dev.yaml and application_qa.yaml. In application.yaml, default profile is declared.

For Spring 1.2.5.RELEASE, the properties of application.yaml were also being used in addition to application_qa.yaml if I ran the application with qa profile. 
But for 1.5.12.RELEASE, only application_qa.yaml is loaded (and it does not find the properties present in application.yaml). 

```
 spring:
  profiles.active: default
---
spring:
  profiles: default
validityHours: 336 
```

However, when I remove the profiling part

```
# spring:
#  profiles.active: default
---
#spring:
#  profiles: default
validityHours: 336 
```

it works fine and rest of the properties from application.yaml are loaded.

I think the behavior with 1.5.12.RELEASE is what is expected but how is it working with 1.2.5.RELEASE is what I am not sure of. Any idea?

**Comment by wilkinsona** [comment]
If you explicitly make a profile (other than default) active then, yes, the default profile will no longer be active. If the default profile is not active then any configuration in a YAML file that's specific to that profile will no longer apply.

> I think the behavior with 1.5.12.RELEASE is what is expected

Assuming I have understood your description correctly, I think so too.

> how is it working with 1.2.5.RELEASE is what I am not sure of. Any idea?

Presumably there was a bug that was fixed sometime between 1.2.5 and 1.5.12. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements so this isn't the right place to ask.

If you are interested in find exactly when the change in behaviour occurred, I would recommend that you do the following:

1. Perform a binary search of releases between 1.2.5 and 1.5.12 to pinpoint the release in which the behaviour changed.
2. Review the changes in the milestone on GitHub for that release to find the issue and commit which changed the behaviour.
3. If, having taken the time to following the steps above, you still require further information, chat with the community on Gitter as someone there may have the time to help you further.
