### ISSUE TITLE
Document when and how to use bracket notation when binding to a map

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#13506]
Camel's zipkin spring boot thing uses wildcard mappings to properties like this:

```
# the zipkin service name
camel.zipkin.server-service-mappings.*=service1
camel.zipkin.client-service-mappings.*=service2
```

The corresponding `@ConfigurationProperties` would receive a map entry for the wildcard into a map field like this: `private Map<String, String> clientServiceMappings`

The last version this worked on was Spring Boot 2.0 M7. Afterwards, this mapping fails with the following exception:

```
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>] at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound (GenericConversionService.java:321)
```

So that you don't have to build camel, you can paste the below into a start.spring.io app, setting the above as application.properties

```java
@SpringBootApplication
@EnableConfigurationProperties(ZipkinConfigurationProperties.class)
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }
}
```

```java
@ConfigurationProperties(prefix = "camel.zipkin")
public class ZipkinConfigurationProperties {
  private Map<String, String> clientServiceMappings;
  private Map<String, String> serverServiceMappings;

  public Map<String, String> getClientServiceMappings() {
    return clientServiceMappings;
  }

  public void setClientServiceMappings(Map<String, String> clientServiceMappings) {
    this.clientServiceMappings = clientServiceMappings;
  }

  public Map<String, String> getServerServiceMappings() {
    return serverServiceMappings;
  }

  public void setServerServiceMappings(Map<String, String> serverServiceMappings) {
    this.serverServiceMappings = serverServiceMappings;
  }
}
```

**Comment by wilkinsona** [comment]
I think this is, essentially, the same limitation as #13404 is tracking. You can get the `*` to bind by surrounding it with `[*]`:

```properties
# the zipkin service name
camel.zipkin.server-service-mappings.[*]=service1
camel.zipkin.client-service-mappings.[*]=service2
```

**Comment by wilkinsona** [comment]
Given that we've got #13404 to make this easier, I think we should use this issue to document the current situation. There's a brief mention of bracket notation [on the wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding), but I can't find any mention in the reference documentation.

**Comment by adriancole** [comment]
sounds good. somehow I thought brackets were about lists, but anyway
escaping like this sounds fine to me.

**Comment by garyrussell** [comment]
Is this behavior expected:

```yaml
logging:
  level:
    org.springframework.kafka.listener[KafkaMessageListenerContainer$ListenerConsumer]: info
```

and

```yaml
logging:
  level:
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: info
```

(with and without `.` before `[`) ?

They both work.

**Comment by mbhave** [comment]
yes this is [expected behavior](https://github.com/spring-projects/spring-boot/blob/95174a077386222a311ee225b044815e2f81a8d0/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/MapBinderTests.java#L97-L98).
