### ISSUE TITLE
Lombok 1.6.22 has issues with constructor generation

### ISSUE THREAD

**Issue by joshfix** [spring-projects/spring-boot#13514]
Upon upgrading to Spring Boot 1.5.14, I received many compilation errors in my project stating that default constructors were already defined.  In addition, certain spring managed services were throwing NullPointerExceptions because fields that should have been automatically wired in via constructor injection were not.

Upon further investigation, it seems Spring Boot 1.5.14 upgraded Lombok to version 1.16.22 which is known to have an issue:

https://github.com/rzwitserloot/lombok/issues/1731

Manually overriding the Lombok version to 1.18.0 using the `<lombok.version>` property seemed to fix all issues for me.

**Comment by joshfix** [comment]
PR submitted.  #13515

**Comment by bclozel** [comment]
Duplicates #13492.
