### ISSUE TITLE
PropertiesLauncher: loader.path failed to reference a windows folder

### ISSUE THREAD

**Issue by jeromevalentin** [spring-projects/spring-boot#1352]
The problem occurred when using the parameter below:
`-Dloader.pah=C:/MyFolder,D:/AnotherFolder,lib`

`MyFolder` is ignored as the source code of `PropertiesLauncher.java` is performing a check of a starting '/' character which makes sense under Linux but not under Windows.

Below is the identified bug:

```
private List<Archive> getClassPathArchives(String path) throws Exception {
    String root = cleanupPath(stripFileUrlPrefix(path));
    List<Archive> lib = new ArrayList<Archive>();
    File file = new File(root);
    if (!root.startsWith("/")) {
      file = new File(this.home, root);
    }
....
```

The effect is that launcher is looking for resource `C:/MyFolder` under the user home directory ... which does not exist. The effect is that folder is ignored without any notice...

As Workaround I may use the `-Dhome=C:/` to customize the "user.home" folder, unfortunately this solve only the problem for `MyFolder` but does not solve my whole problem as I need to refer directories from multiple partitions ...

Another idea was to prefix `C:/MyFolder` with a `'/C:/MyFolder'` ... it works better, but for resources in `MyFolder` `ClassLoader.getResource` returns URL while `getResourceAsStream` return null on the same resource .... (due to the presence of the leading / in the URL)

To Workaround totally the issue I need to write a custom `ClassLoader` and declared it with `-Dloader.classLoader ....` and perform URL correction on the fly ...

**Comment by tree-chutes** [comment]
Sorry to bring this one back to life.

I am using 1.3.5 in a OS X, java 1.8. I am running into the following:

-Dloader.path=file:/Users/xxx/folder_with_classes is ignored when launching the executable jar (PropertiesLauncher). 

When I try to create new ClassPathXmlApplicationContext("Beans.xml") it throws a FNF exception. I know the file is there because I am using a another classloader to read ahead the bean definitions.

Any suggestions? Can I plug my classloader in there? 

Thanks a lot in advance!!!

**Comment by tree-chutes** [comment]
Well, scratch the custom classloader option. I need the restart functionality in place. The main issue is that I need to add a final entry to the class paths. The class folder that will be listened to by the restart loader. I assumed that the -Dloader.path would do the trick. Is this a valid assumption?

**Comment by philwebb** [comment]
@tree-chutes Probably best to ask these types of questions on stackoverflow.com. This bug has been closed for a while and we'd prefer to not add additional comments to it now.

**Comment by tree-chutes** [comment]
Ok. Will do
