### ISSUE TITLE
Spring Boot 2.0.3.RELEASE and Micrometer 1.0.5 is broken

### ISSUE THREAD

**Issue by ctoestreich** [spring-projects/spring-boot#13528]
There was a failure to shade a dependent jar into the micrometer 1.0.5 library.  Issue logged below and fix will be in 1.0.6.  There is a work around which involved directly importing the org.pcollections dep.

https://github.com/micrometer-metrics/micrometer/issues/655

This appears to cascade through Cairo-SR2 and Boot 2.0.3.RELEASE

**Comment by jkschneider** [comment]
This issue can be closed. There is nothing to do in Spring Boot.

**Comment by ctoestreich** [comment]
@jkschneider @wilkinsona Thanks for the follow up and I am sure 1.0.6 of micrometer is on the way.  My intent here was simply to make sure that the 2.0.4.RELEASE includes the 1.0.6 micrometer release to fix this issue.  While true that the only change to boot is a dep version bump, It just happened to catch us when we were upgrading hundreds of boot services that are derived from platform.io Cairo-SR2 and the micrometer issue came up immediately.  The initial upgrade was scrapped as bumping a common property was pretty simple given our CI/CD pipeline, but having to additionally add the missing shaded jar for pcollections to hundreds of applications was not worth the time in hopes that the 2.0.4.RELEASE way of a new platform release would resolve this issue.
