### ISSUE TITLE
Update Migration guide to incorporate latest Apache Maven Surefire release

### ISSUE THREAD

**Issue by britter** [spring-projects/spring-boot#13520]
The [Spring Boot 2.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) has a tip regarding the usage of Surefire 2.19.1 for JUnit 5 support in section "Surefire Defaults". This should be changed, since Surefire 2.22.0 ships with native JUnit 5 support. So I suggest to change the text to:

> If you are using JUnit 5, make sure you are using at least [Surefire 2.22.0](http://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html).

**Comment by snicoll** [comment]
Thanks for the report, the migration guide has been updated.
