### ISSUE TITLE
Actuator breaks schema.sql init

### ISSUE THREAD

**Issue by rotilho** [spring-projects/spring-boot#13539]
I'm using `spring-boot:2.0.3.RELEASE` + `spring-cloud-dependencies:Finchley.RELEASE`

My application is working fine however when I add actuator the schema-h2.sql is not been executed making my tests to fail.

No warn or error is logged beside table not found.

**Comment by snicoll** [comment]
> when I add actuator the schema-h2.sql is not been executed making my tests to fail.

Thanks for the report but we'll need more information before investigating any further as adding the actuator should not have any such impact. Please share a sample that we can clone and run ourselves.

**Comment by rotilho** [comment]
I need to invest more time, so far I couldn't reproduce it in a project from scratch.

Debugging I see that in the buggy project when JdbcTemplate.execute -> getConnection is called the exception Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is there an unresolvable circular reference? is thrown

The same not occur for the new project from scratch.

**Comment by wilkinsona** [comment]
This sounds like a duplicate of https://github.com/spring-projects/spring-boot/issues/13042. I don't think it's the Actuator that's the problem, but Spring Cloud and it moving the `DataSource` into the refresh scope.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by rotilho** [comment]
I can't reproduce it still but the issue seems quite similar to the one pointed by @wilkinsona. I close this issue and keep a look in #13042 if the bug persists I'll invest more time to reproduce it
