### ISSUE TITLE
Consider replacing `XyzCustomizer` by `Consumer<Xyz>`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13530]
While reviewing a PR, I've noticed that our current arrangement for post-processing infrastructure elements that we've auto-configured is to defined a `Customizer` interface (that is a `@FunctionalInterface`). 

Now that we're Java8-based, I wonder if we shouldn't stop doing that in favour of the standard `Consumer` contract. There might be generic resolution side effect that may be annoying but I'd certainly welcome that over a specific contract.

**Comment by wilkinsona** [comment]
While the signature of an `XyzCustomizer` is essentially the same as a `Consumer<Xyz>`, I prefer the former as I think it's more expressive and makes the intent clearer. Even with a lambda expression, having `Customizer` in the type name improves the readability of the code as it'll typically be the return type of a `@Bean` method.

**Comment by philwebb** [comment]
I agree with @wilkinsona. I like having the dedicated type as it gives us a nice place to hang javadoc.
