### ISSUE TITLE
Provide proper exception/log for the missing application.properties/application.yml file

### ISSUE THREAD

**Issue by NageswaraRaoMaridu** [spring-projects/spring-boot#13532]
I have a spring boot application which is using v1.5.10.RELEASE of spring boot. When the application.properties or application.yml file is missing from the classpath the spring boot bootstrapping process not throwing any error or not showing any useful information. The application is failing to start and the user has no idea why it has terminated. A meaningful hint will be useful in this case.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but an application doesn't have to have an application.properties or application.yml file so logging something or throwing an exception when one isn't found would not be appropriate.

> The application is failing to start and the user has no idea why it has terminated.

Can you give a concrete example of this? I'm guessing you have something that requires some configuration and none is found. Perhaps the error that shown in the specific scenario could be improved.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
