### ISSUE TITLE
Additional dependencyManagement entry for org.elasticsearch.distribution.zip:elasticsearch@zip

### ISSUE THREAD

**Issue by chriswhite199** [spring-projects/spring-boot#13547]
Would is be possible to add a `dependencyManagement` entry for the `org.elasticsearch.distribution.integ-test-zip:elasticsearch` artifact, such that the zip file could be used within a Maven / Gradle build that is associated with the same version as the `org.elasticsearch:elasticsearch` artifact?

What I'm trying to get to is to ensure the distribution zip is pulled down as part of the dependency management, and can then be unpacked and used for integration tests against a test node stood up from the unpacked distro.

Currently, i have to do something like this (paired with spring boot dependency mgmt), and i'd rather do away with having to keep the zip version up to date with the spring boot managed version:

```
    dependencies {
        compile 'org.elasticsearch:elasticsearch'
        integTestRuntimeOnly 'org.elasticsearch.distribution.integ-test-zip:elasticsearch:5.6.10@zip'

        // I want to be able to do this instead:
        // integTestRuntimeOnly 'org.elasticsearch.distribution.integ-test-zip:elasticsearch@zip'
    }
```

**Comment by wilkinsona** [comment]
Seems reasonable to me. Thanks for the suggestion. In the meantime, you can do this in Gradle to use the same version as the `org.elasticsearch:elasticsearch` artifact:

```groovy
dependencies {
    integTestRuntimeOnly "org.elasticsearch.distribution.integ-test-zip:elasticsearch:${dependencyManagement.managedVersions['org.elasticsearch:elasticsearch']}@zip"
}
```
