### ISSUE TITLE
Add support for EXTRA_JAVA_OPTS in executable jar

### ISSUE THREAD

**Issue by dmarkhas** [spring-projects/spring-boot#13542]
In Spring Boot 1.5.13, the executable jar sources the conf file, overriding any pre-existing JAVA_OPTS that were set in the executing shell.

`[[ -r "${CONF_FOLDER}/${configfile}" ]] && source "${CONF_FOLDER}/${configfile}"`

This is a request to modify this behavior by adding support for EXTRA_JAVA_OPTS (or a similar variable) that would allow to start the Java process with additional options that would not be overridden by the .conf file (for example, adding debug flags on demand).

**Comment by wilkinsona** [comment]
I don't think there's a need for another variable to achieve this. If you want the conf file to preserve any existing `JAVA_OPTS` that you can do so. Something like the following, for example:

```
JAVA_OPTS=$JAVA_OPTS -DadditionalOption
```

If this does not meet your needs, can you please explain what you'd like to be able to do in more detail?

**Comment by dmarkhas** [comment]
Actually it does, kinda embarassing such a trivial solution hasn't occurred to me. Thanks :)
