### ISSUE TITLE
Support for dashes in profiles broken

### ISSUE THREAD

**Issue by deveth0** [spring-projects/spring-boot#13544]
I think this might be related to #384:

I've got an application 'foo' which supports two profiles: 'profile1' and 'pro-file2'. 

Configuration is served by a configuration-server (Springboot v2.0.3) but this only works without the dash:

* http://localhost:9001/config/foo-default.json (/)
* http://localhost:9001/config/foo-profile1.json (/) 
* http://localhost:9001/config/foo-pro-file2.json (x) serves the same as -default.

I build a demo project which demonstrates the issue:
https://github.com/deveth0/spring-boot-config-dash

Do I miss something here or are dashes in profiles currently a problem?
Thanks

**Comment by snicoll** [comment]
I don't know but this issue tracker doesn't handle Spring Cloud issues. Please report this to the [appropriate issue tracker](https://github.com/spring-cloud/spring-cloud-config).

**Comment by deveth0** [comment]
ach **** sry, my fault
