### ISSUE TITLE
When setting the platform property with schema-{platform}.sql present UTC timestamps are interpeted as non-UTC (GMT)

### ISSUE THREAD

**Issue by tbrannt** [spring-projects/spring-boot#13543]
I use Spring Boot 2.0.3 and have my datasource configured as follows:

```
spring.datasource.url=jdbc:mysql://localhost/myschema?useUnicode=true
spring.datasource.username=user
spring.datasource.password=pw
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.platform=devmysql
```

I also have a sql script called schema-devmysql.sql which has some simple create table DDL:

```
DROP TABLE IF EXISTS myschema.user;

CREATE TABLE myschema.user (
    id BIGINT NOT NULL AUTO_INCREMENT
);
```
I have my mysql database completely set to UTC and intend to only work with UTC dates. I also used 

```
@PostConstruct
void started() {
    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
}
```

to set my spring boot application to UTC.
I already found out when switching to spring boot >2 that suddenly you'll not execute the schema-{platform}.sql and data-{platform}.sql scripts anymore for a non-embedded datasource like mysql. So I did not change the `spring.datasource.initialization-mode` parameter which means I'm not using these scripts to execute my sql. 
The weird thing now is that as soon as I have the platform value set to match the name of my `schema-devmysl.sql` script spring will interpret all dates differently. E.g. a timestamp set to 11AM will appear as 9AM in my application. Once I set  

```
spring.datasource.platform=none
```

I will see the same timestamp correctly as 11AM. What really surprises me is that the presence of my `schema-devmysql.sql` script seems to have an effect even though it is not executed!

I did not have this issue with spring boot <= 1.59.

**Comment by wilkinsona** [comment]
Thanks for the report but I'm not sure I understand the description of the behaviour to diagnose the problem. If you would like us to spend some more time investigating, please take the time to provide a minimal example (something that we can unzip or git clone and run) that reproduces it.

**Comment by tbrannt** [comment]
I created a minimal example [timezonesample.zip](https://github.com/spring-projects/spring-boot/files/2127740/timezonesample.zip).

I could boil it down to the appearance of the jdbcTemplate in a LoginFilter. The jdcbTemplate does not do anything. 

The `create-schema-and-table.sql` script in /docs needs to be executed for the example to work. Also I have 5.7.17 MySQL Community Server (GPL) installed and the following configured in my.cnf (my.ini in my case):
```
[mysqld]
default-time-zone='+00:00'
```

By surfing http://localhost:8080 you can now see that the timestamp that is set to '2018-06-21 11:09:45.725' in the db is shown as '2018-06-21 09:09:45.725':

`loginDate of user is: 2018-06-21 09:09:45.725`

Either removing the autowired `JdbcTemplate` bean in the `LoginFilter` or renaming `schema-devmysql` or changing the `spring.datasource.platform` property to e.g. `none` will prohibit this behavior from happening.

**Comment by tbrannt** [comment]
And I have to take it back: This is also happening in <= 2.0.0 Spring Boot versions.

**Comment by wilkinsona** [comment]
I haven't been able to reproduce the problem with the sample, but I think it's helped me to figure out the cause.

Setting the time zone in `@PostConstruct` of your `Application` class doesn't provide any really strong guarantees of when that will happen in relation to other parts of the application's lifecycle. Specifically, it doesn't guarantee that it'll happen before a connection to the database is opened. I suspect that the `schema-devmsql.sql` file being processed results in a connection to the database being opened before the timezone has been set.

To fix the problem, I would recommend moving the call to `TimeZone.setDefault(TimeZone.getTimeZone("UTC"))` into your application's main method before you call `SpringApplication.run`:

```java
public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
    System.out.println("Sample started");
}
```

**Comment by tbrannt** [comment]
That fixed my problem. I guess for reproducing it it's important that the system time is set to something other than UTC.

Weird though that I found the `@PostConstruct` location as **the** place to set spring boots timezone across many different sources. Also doing it in the main method doesn't work for tests. But I guess I'll use a jvm parameter for them.
