### ISSUE TITLE
Erro Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by maykon-oliveira** [spring-projects/spring-boot#13549]
🐞 Bug 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I searched for internet to solve this problem. I've tried everything but I can't fix it.

**Comment by mbhave** [comment]
There’s no information here to indicate that this is a bug or that it is a Spring Boot issue. 
If you would like us to spend time trying to help you, please spend some time describing the problem in the form of a minimal, complete, and verifiable example. We can reopen the issue if the example indicates that this is an issue in Spring Boot.
