### ISSUE TITLE
Add support for new SpringLiquibase properties from 3.6.2

### ISSUE THREAD

**Issue by isopov** [spring-projects/spring-boot#13550]
In liquibase/liquibase#774 support for liquibase properties
- liquibaseSchema
- databaseChangeLogTable
- databaseChangeLogLockTable
- liquibaseTablespace

was added to SpringLiquibase integration and it should be available in 3.6.2 release. (Yet to be released) Once updated to this version of  liquibase, please add support for these properties in LiquibaseAutoConfiguration and LiquibaseProperties

**Comment by 72MiguelGomes** [comment]
@isopov I already created a PR with the support (https://github.com/spring-projects/spring-boot/pull/13625), this way part of the work is already done.

**Comment by philwebb** [comment]
Closing in favor of PR #13625
