### ISSUE TITLE
WebDriverScope init FactoryBean early

### ISSUE THREAD

**Issue by leizhiyuan** [spring-projects/spring-boot#13563]
Env

```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-test-autoconfigure</artifactId>
<version>1.4.2.RELEASE</version>
```
We have a BeanPostProcessor  to get some information from our FactoryBean ,But when we use webDriver to test, 
in

``` 
org.springframework.boot.test.autoconfigure.web.servlet.WebDriverScope#registerWith 
```

It register a BeanFactoryPostProcessor ,will init our FactoryBean early. then FactoryBean  instance will not be passed to our BeanPostProcessor correctly (It has been inited in this BeanFactoryPostProcessor), 

What my question is  can we change getBeanNamesForType parameter  to 

```
private static void postProcessBeanFactory(
			ConfigurableListableBeanFactory beanFactory) {
		for (String beanClass : BEAN_CLASSES) {
			for (String beanName : beanFactory
					.getBeanNamesForType(ClassUtils.resolveClassName(beanClass, null),true,false)) {
				BeanDefinition definition = beanFactory.getBeanDefinition(beanName);
				if (!StringUtils.hasLength(definition.getScope())) {
					definition.setScope(NAME);
				}
			}
		}
	}
```

here(add allowEagerInit =false),  Then FactoryBean will not be inited early?

**Comment by wilkinsona** [comment]
Thanks for the report, @leizhiyuan. Unfortunately, it's impossible to tell if the change that you have proposed is the right one to make as you haven't fully described the problem. Can you please provide a small sample that reproduces the early initialisation problem and we can take things from there? The sample should use Spring Boot 1.5.x or later as 1.4.x is no longer maintained.

**Comment by leizhiyuan** [comment]
@wilkinsona Thanks, I will use Spring Boot 1.5.x to provide a demo later

**Comment by leizhiyuan** [comment]
Sorry, When I write the demo, I debugged and know this problem. in our FactoryBean ,There has a special logic 

```
 @Override
    public Class<?> getObjectType() {

        if (applicationContext == null) {
            return null;
        } else {
            return DemoService.class;
        }
    }
```

when It return null, Spring will init it to know it's type.
```
// Check bean class whether we're dealing with a FactoryBean.
			if (FactoryBean.class.isAssignableFrom(beanType)) {
				if (!BeanFactoryUtils.isFactoryDereference(name)) {
					// If it's a FactoryBean, we want to look at what it creates, not the factory class.
					beanType = getTypeForFactoryBean(beanName, mbd);
					if (beanType == null) {
						return false;
					}
				}
			}
```

close this issue
