### ISSUE TITLE
Documentation minor enhancement: Use of @ClassRule instead @Rule to capture set-up logging

### ISSUE THREAD

**Issue by vorburger** [spring-projects/spring-boot#1356]
Maybe on http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-output-capture-test-utility a paragraph saying something like this could be added:

If you would like to capture set-up logging from Spring Boot and your beans, which run before your @Test, then use this instead of @Rule:

     @ClassRule // and NOT just @Rule - else the Spring Boot set-up logging isn't captured
     public static OutputCapture capture = new OutputCapture();

PS, not directly related - but just FYI: https://github.com/qos-ch/slf4j/pull/76

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
