### ISSUE TITLE
JVM args necessary for Cloud-Config-Bootstrap SSL are forwarded to Tomcat

### ISSUE THREAD

**Issue by trickert76** [spring-projects/spring-boot#13569]
Based on my question on https://stackoverflow.com/questions/50972390/springbooteurekacloudconfig-in-a-ssl-environment I think, we're talking about a bug. At least - it's an unexpected behaviour.

A spring boot application needs a truststore to connect during bootstrap phase to a Eureka/Cloud Config service to register and retrieve the configuration. This is demonstrated al over the net - but without SSL.

Because the Spring context isn't available during bootstrap I've set the System.properties javax.net.ssl.trustStore... The client service connects (so the truststore works fine).

But after the Spring contect comes up and the embedded Tomcat wants to start, there is an Exception from Tomcat saying, that the Truststore has no aliases in it ("the trustAnchors parameter must be non-empty"). If I switch the embedded Tomcat to an embedded Undertow - everything works as expected. So the embedded Tomcat reacts on the JVM args, saying, the truststore is "wrong" but the same truststore is used just seconds before. In the bootstrap phase it's used to trust the self signed certificates from the Eureka/Cloud Config server, but I don't know, why the Tomcat uses it (the service starts, there is no "activity").

Because I think, the truststore is okay, it works with Undertow, there must be a problem, why Tomcat uses the Truststore in a different unexptected way - but I couldn't find any reason.

**Comment by wilkinsona** [comment]
Thanks for the report. I don't think Spring Boot itself does anything with the SSL-related system properties. This means that how Tomcat uses them is out of Boot's control. Perhaps you have evidence to the contrary but "there is an Exception from Tomcat" doesn't really tell us anything. If you want to pursue this aspect of the problem, I would recommend posting to the Tomcat users mailing list or commenting on this issue with the details that show why you believe Spring Boot is causing the problem.

With that said, relying on System properties to use SSL with the config server doesn't sound like the optimal approach to me. Rather than pursuing the system property-based approach, I would recommend chatting with the [Spring Cloud team on Gitter](https://gitter.im/spring-cloud/spring-cloud) about the best way to use SSL with a custom truststore.

**Comment by trickert76** [comment]
Hi Andy,
thanks for your reply. I think, this isn't really a Tomcat issue, so I didn't send the stacktrace. I could do, but it wouldn't really help.

The problem is something else. In a world where "security by design" should be something normal, this default settings from Spring Cloud Config aren't helpful. If you have several services that need to contact a cloud config server then it should be normal, that this connection should be easily secured. 

The documentation and much more Google searches helped very good - but all of them only work, when the Spring context is up and running. But the cloud configuration must be ready earlier in a start up where no Spring context is available and all the @Configuration's aren't working. At that time the system already read the bootstrap.yml - but there is no good way to configure either the Eureka client nor the Cloud config client and give them the order to use a specific trust store.

To solve this problem - I could only do either set the System.property or add the certificate to the system trust store. Both ways aren't "smart" and I would like to have another way. But there is no way I could find. So I opened an issue here on Github. Closing it and saying please talk to the Tomcat team isn't helpful.

I thought, we want to make the Spring environment better by finding problems and issues. And because I need and like the idea of "security by design" I think, the Spring Cloud Config Client (and the Eureka client) isn't ready for this pattern. Today I'll create an example project on Github and I hope, you'll have a look on it.

So - please reopen the issue and let's talk about solutions.

**Comment by wilkinsona** [comment]
Spring Cloud Config isn’t part of Spring Boot so this isn’t the right place to talk about solutions. You may be interested in this existing [Spring Cloud Config issue](https://github.com/spring-cloud/spring-cloud-config/issues/148). If that doesn’t help then I’d have a chat with the team on Gitter.

**Comment by trickert76** [comment]
hmm, ok - you're right - maybe it is a problem with Cloud Config or Eureka, because both are necessary in bootstrap to get the correct location of the configuration. I'll add the issue there.

But - by-the-way - sslVerify: false is never a solution.
