### ISSUE TITLE
springboot-webflux  Severe underperformance!

### ISSUE THREAD

**Issue by yu199195** [spring-projects/spring-boot#13576]
I use webflux  in spring-boot 2.0.0.M3. 
i use Apache Jmeter 4.0 test the projects . with fifty threads run concurrently for 5 minutes

this is test report:
生成概要结果 +   3164 in 00:00:32 =   97.5/s Avg:   157 Min:     0 Max: 17602 Er
r:     0 (0.00%) Active: 50 Started: 50 Finished: 0
生成概要结果 = 267358 in 00:02:53 = 1545.1/s Avg:    19 Min:     0 Max: 18336 Er
r:     0 (0.00%)
生成概要结果 +   1885 in 00:00:31 =   61.6/s Avg:   263 Min:     0 Max: 23121 Er
r:     0 (0.00%) Active: 50 Started: 50 Finished: 0
生成概要结果 = 269243 in 00:03:24 = 1322.3/s Avg:    20 Min:     0 Max: 23121 Er
r:     0 (0.00%)
生成概要结果 +   1160 in 00:00:29 =   39.3/s Avg:   561 Min:     0 Max: 29609 Er
r:     0 (0.00%) Active: 50 Started: 50 Finished: 0
生成概要结果 = 270403 in 00:03:53 = 1160.0/s Avg:    23 Min:     0 Max: 29609 Er
r:     0 (0.00%)
生成概要结果 +    706 in 00:00:29 =   24.2/s Avg:   771 Min:     0 Max: 51656 Er
r:     0 (0.00%) Active: 50 Started: 50 Finished: 0
生成概要结果 = 271109 in 00:04:22 = 1033.8/s Avg:    25 Min:     0 Max: 51656 Er
r:     0 (0.00%)
生成概要结果 +    355 in 00:00:30 =   12.0/s Avg:  2690 Min:     0 Max: 58854 Er
r:     0 (0.00%) Active: 50 Started: 50 Finished: 0
生成概要结果 = 271464 in 00:04:52 =  930.4/s Avg:    28 Min:     0 Max: 58854 Er
r:     0 (0.00%)
生成概要结果 +    178 in 00:00:14 =   12.4/s Avg:  6893 Min:     0 Max: 36326 Er
r:     0 (0.00%) Active: 0 Started: 50 Finished: 50
生成概要结果 = 271642 in 00:05:06 =  887.1/s Avg:    32 Min:     0 Max: 58854 Er
r:     0 (0.00%)

BUG:
when 00:04:22  response time is  2690 Min  Lasted about 30 seconds . why?

this is my environment
    cpu = 64Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz,
    memory = 12GB
    windows7
    java = Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
    JVM = Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by wilkinsona** [comment]
This is very unlikely to have anything to do with Spring Boot. It’s responsible for the auto-configuration of WebFlux but isn’t really involved at runtime. Also, why are you using Spring Boot 2.0 M3? Many changes have been made in Boot and the underlying components that provide WebFlux’s runtime.

I would recommend upgrading to Spring Boot 2.0.3. If the problem still occurs then it could be a bug in your application or in WebFlux. If you are certain that your application is not the cause, I would open a Spring Framework JIRA ticket. In that ticket you should provide as much information as possible and, ideally, a small sample that reproduces the problem.

**Comment by yu199195** [comment]
i m sorry ， i use spring boot 2.0.2  . The problem is easy to reproduce.
use spring-boot-starter-webflux  provide web service (restful api).
and then Use high concurrency requests with Apache Jmeter 4.0 .
as time goes on, this response time is 2690 Min About three minutes.
meantime 500 megabytes of off-heap memory was used and not freed.

**Comment by wilkinsona** [comment]
As requested above, please try 2.0.3 (it includes new versions of Reactor Netty and Spring Framework). If that doesn’t help, please open a [Spring Framework JIRA issue](https://jira.spring.io/browse/SPR).
