### ISSUE TITLE
Announce 1.5 EOL

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13575]

**Comment by bclozel** [comment]
To give some context here (I’m seeing confused emojis here): Spring Framework should soon announce the official plan for the 4.3 line and when the official support should end (4.3 EOL). The release cadence is already slowing down, with the project entering its maintenance mode. Looking at the previous generations, you can see that Spring Framework usually gives plenty of time.

Spring Boot is a different project, with different constraints - so the team has to figure out the best plan once all the information is available. The current adoption for Spring Boot 2.x is pretty good and the whole ecosystem is quickly catching up - the Spring Boot community usually moves quickly.

**Comment by bclozel** [comment]
@dreis2211 nothing very scientific unfortunately.
We’re keeping an eye on start.spring.io usage and maven central download stats, community feedback through Gitter/GitHub/Twitter/meetups/customers/blog comments, questions on StackOverflow, and more.

Of course many developers can hide behind a single corporate artifact repository and count as very few download counts in maven central stats. We’re often looking at trends and comparing with historical data.

**Comment by dreis2211** [comment]
@bclozel Thanks for elaborating, though. I was curious because I always find this sort of thing hard to measure (e.g. because of corporate repos)
