### ISSUE TITLE
Rest problem mappedwith spring-boot-starter-web

### ISSUE THREAD

**Issue by deluxxx** [spring-projects/spring-boot#13577]
Hello,
I have problem with rest mapping when I use RouterFunctions.

`@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Autowired
    private WholesaleHandler wholesaleHandler;

    @Autowired
    private DeparmentController deparmentController;

    @Bean
    public RouterFunction<?> wholesaleRouter() {
        return
                RouterFunctions.nest(RequestPredicates.path("/api/wholesales"),
                        RouterFunctions.nest(RequestPredicates.accept(MediaType.APPLICATION_JSON),
                                RouterFunctions.route(RequestPredicates.method(HttpMethod.POST), wholesaleHandler::getAll)))
                ;
    }

    @Bean
    public RouterFunction<?> departmentsRouter() {
        return
                RouterFunctions.nest(RequestPredicates.path("/api/departments/"),
                        RouterFunctions.nest(RequestPredicates.accept(MediaType.APPLICATION_JSON),
                                RouterFunctions.route(RequestPredicates.POST("/{wholesaleId}"), deparmentController::getDepartmentByWholesale))
                                );
    }

}`

When I don't add 
`<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>`

I see in console: 
`2018-06-26 07:50:08.259  INFO 16480 --- [           main] o.s.w.r.f.s.s.RouterFunctionMapping      : Mapped /api/wholesales => {
 Accept: [application/json] => {
  POST -> com.edge1s.marche.BlesApplication$$Lambda$356/1970528559@39e43310
 }
}
2018-06-26 07:50:08.259  INFO 16480 --- [           main] o.s.w.r.f.s.s.RouterFunctionMapping      : Mapped /api/departments/ => {
 Accept: [application/json] => {
  (POST && /{wholesaleId}) -> com.edge1s.marche.BlesApplication$$Lambda$358/1206180304@eb507b9
 }
}`

but when I add that depedency the rest is not mapped.

I need that depedency when I want create documentation using swagger.

When I created normally Controller everything is ok. Like that:

` @RestController("/api/translations/")
public class TranslationsController {

    private TranslationsService translationsService;

    @Autowired
    public TranslationsController(TranslationsService translationsService) {
        this.translationsService = translationsService;
    }

    @GetMapping(path = "/byShortcut/{page}/{language}")
    public Mono<Translation> byShortcut(@PathVariable("page") String page, @PathVariable("language") String language){
        Mono<Translation> propertiesByLanguage = translationsService.getPropertiesByLanguage(page, language);

        return propertiesByLanguage;
    }

}`

**Comment by wilkinsona** [comment]
When you add the starter-web dependency, you are no longer using WebFlux. You are using Spring MVC running on top of the Servlet stack instead. Support for RouterFunction is WebFlux-specific so it’s lost when you stop using WebFlux.

I guess you are trying to use Spring Fox. It doesn’t, AFAIK, support WebFlux. If you want to use it to generate a Swagger definition you’ll have to stick with Spring MVC.

**Comment by deluxxx** [comment]
Thanks for explanation. 

Yes I use : 
`		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.7.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.7.0</version>
			<scope>compile</scope>
		</dependency>`

So when I create
`RestController("/api/user")
public class UserController {


    @PostMapping(path = "/register")
    public Mono<UserEntity> register(@RequestBody UserEntity object) {
        return null;
    }
}
`

and using web that webflux is stopped or only when I using RouterFunction?

**Comment by wilkinsona** [comment]
Just adding a dependency on `starter-web` stops the use of WebFlux. You have to choose to either use WebFlux or to use SpringFox. You cannot use both. There a [several open SpringFox issues](https://github.com/springfox/springfox/issues?utf8=✓&q=is%3Aissue+is%3Aopen+WebFlux) about supporting WebFlux.
