### ISSUE TITLE
Should Delete Tomcat temp directories on exit

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#13573]
Running Spring Boot with Tomcat (ex, using `mvn spring-boot:run`) a number of times results in a bunch of directories being created in the temp (`java.io.tmpdir`) directory. Over time, that adds up to decent amount of wasted disk space. It would be nice to try to clean up those temp files when done with them.

**Comment by wilkinsona** [comment]
Duplicates #9983.
