### ISSUE TITLE
Spring boot AOP ignores JAX-RS resources registered using @Named

### ISSUE THREAD

**Issue by mkargar** [spring-projects/spring-boot#13571]
I originally posted this on stackoverflow [here](https://stackoverflow.com/questions/51013822/spring-boot-aop-ignores-jax-rs-resources-registered-using-named).
__________________________________________________________

Working on a simple web application where Spring boot 2.x handles wiring between different components and JAX-RS/Jersey handles REST calls.

A simple configuration like the one below is used for intercepting REST calls.

```
@Aspect
@Configuration
public class MyAspectConfig {

    @After("execution(public * *..*Resource.*(..))")
    public void afterExec(JoinPoint joinPoint) {
        System.out.println("====================== " + joinPoint);
    }
}
```

We have noticed that if JAX-RS resource classes annotated with `@Named` then the advice above doesn't get invoked. However replacing `@Named` with `@Component` fixes the issue.

Is this a known issue/limitation? Aren't `@Named` and `@Component` interchangeable?

**Comment by mkargar** [comment]
Here's the application code to reproduce the bug (attached you can find the project).
[demo.zip](https://github.com/spring-projects/spring-boot/files/2137971/demo.zip)

`package com.example.demo;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Aspect;
import org.glassfish.jersey.server.ResourceConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.stereotype.Component;

import javax.inject.Named;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.Collections;
import java.util.Map;

@SpringBootApplication
@EnableAspectJAutoProxy
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	//@Component
	@Named
	@Path("/demo")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	public static class DemoResource {

		@GET
		public Map<String, String> get() {
			return Collections.singletonMap("msg", "hi");
		}
	}

	@Named
	public static class DemoConfigJersey extends ResourceConfig {
		public DemoConfigJersey() {
			register(DemoResource.class);
		}
	}

	@Aspect
	@Configuration
	public static class DemoConfigAspect {

		@After("execution(public * *..*Resource.*(..))")
		public void afterExec(JoinPoint joinPoint) {
			System.out.println("====================== " + joinPoint);
		}
	}

}
`

**Comment by wilkinsona** [comment]
This is a limitation of Jersey's Spring integration. You are registering `DemoResource` as a class so you are relying on Jersey either finding the Spring bean `DemoResource` or creating its own instance. When you use `@Component`, the former happens. When you use `@Named`, the latter happens. Jersey creates its own instance when you use `@Named` as `org.glassfish.jersey.server.spring.SpringComponentProvider` [only looks for `@Component`](https://github.com/eclipse-ee4j/jersey/blob/c169c8437f28675d0c970b903007c7c0f28c7115/ext/spring4/src/main/java/org/glassfish/jersey/server/spring/SpringComponentProvider.java#L104).
