### ISSUE TITLE
not support biginteger when length greate than 16

### ISSUE THREAD

**Issue by damozhiying** [spring-projects/spring-boot#13579]
```java
import io.swagger.annotations.ApiOperation;
import java.math.BigInteger;
import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/apis/gateway-conf")
public class ApiGatewayInfoController {

@ApiOperation(value = "获取api网关信息")
	@RequestMapping(value = "/test2", method = RequestMethod.GET)
	public Zoo getGatewayInfo3() throws DcoosException {

		BigInteger bi = new BigInteger("999999999999999889");
		Zoo z = new Zoo(bi,"abc");

		return z;
	}
	@ApiOperation(value = "获取api网关信息")
	@RequestMapping(value = "/test3", method = RequestMethod.GET)
	public BigInteger getGatewayInfo4() throws DcoosException {

		BigInteger bi = new BigInteger("999999999999999889");

		return bi;
	}
}
```

```js
response body
{
  "bi": 999999999999999900,
  "name": "abc"
}
```

**Comment by wilkinsona** [comment]
How have you verified the contents of the response? It works for me using curl or HTTPie. If you'd like us to spend more time investigating, please provide a complete example of how to reproduce the problem (something that we can unzip or git clone and run) including how you are calling the service and checking the contents of the response.

**Comment by damozhiying** [comment]
@wilkinsona  you can clone from https://github.com/damozhiying/spring-boot-demo
when app startup can look in http://127.0.0.1:8080/swagger-ui.html#/

**Comment by wilkinsona** [comment]
Thanks. As suspected, this isn't due to Spring Boot. The response is as expected when accessed with curl:

```
$ curl localhost:8080/apis/gateway-conf/test2
{"bi":999999999999999889,"name":"abc"}
```

The problem only occurs when Swagger UI is involved. See https://github.com/swagger-api/swagger-ui/issues/2030.

**Comment by damozhiying** [comment]
@wilkinsona  thanks a lot
