### ISSUE TITLE
Enable git remote linking automatically on CF

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13586]
Appsman will provide links to the git repo if the URL if the properties provide the info. It would be nice if users didn't need to configure this themselves.

**Comment by philwebb** [comment]
This is about setting the mode to full, we could do this automatically for CF

**Comment by nkolosnjaji** [comment]
I can try creating a PR if you agree.

**Comment by mbhave** [comment]
@nkolosnjaji As @wilkinsona mentioned above, just providing a `CloudFoundryInfoEndpointExtension ` would not be sufficient as the info comes from the `GitInfoContributor `. One way to do this would be to create a cloudfoundry specific `GitInfoContributor`. This would always return full git info and could then replace the main `GitInfoContributor` if that is present in the `CloudFoundryInfoEndpointExtension`.

**Comment by snicoll** [comment]
I am not keen to have an accessor that exposes the `InfoContributor` and a direct link to the `InfoEndpoint` there. In the past, we've used the same strategy to get things in multiple places if need to be. If that doesn't work, then we can have a `InfoIndicator` or something?
