### ISSUE TITLE
Properties getting trimmed since 2.0

### ISSUE THREAD

**Issue by jacekkruger** [spring-projects/spring-boot#13602]
The following application running under Spring Boot 1.5.14 outputs
```
	:1
abc   :6
```

but after upgrading to 2.0.0 outputs
```
:0
abc:3
```

Is that intended behavior? The [comment](https://github.com/spring-projects/spring-boot/issues/4106#issuecomment-173278825) on #4106 by @wilkinsona suggests that properties should not be trimmed. But discussion under #11029 suggests that there were in fact some changes related to trimming of collection properties.

I used a "separator" property in an application that does CSV parsing just like in the example below. The separator is a tab and with 2.0 it seems I have no way to specify that via properties.

Application.java:
```java
@SpringBootApplication
@ConfigurationProperties("application")
public class Application {

    private String separator;

    private String string;

    public String getSeparator() {
        return separator;
    }

    public void setSeparator(String separator) {
        this.separator = separator;
    }

    public String getString() {
        return string;
    }

    public void setString(String string) {
        this.string = string;
    }

    @PostConstruct
    void postConstruct() {
        System.out.println(separator + ":" + separator.length());
        System.out.println(string + ":" + string.length());
    }

    public static void main(String args[]) {
        SpringApplication.run(Application.class, args);
    }

}
```

application.properties:
```properties
application.separator=\t
application.string=   abc   
```

**Comment by philwebb** [comment]
This discussion in #11029 specifically relates to binding comma-separated strings to collections and arrays. E.g. you can have properties `some.value=Fred,   Velma,Daphne` bound to `List<String>` and it will contain `["Fred", "Velma", "Daphne"]`. That change was driven mainly by the `StringToCollectionConverter` in Spring Framework which [trims elements](https://github.com/spring-projects/spring-framework/blob/e72f4ec501f2bcf37931628cc44d48db03607609/spring-core/src/main/java/org/springframework/core/convert/support/StringToCollectionConverter.java#L75).

I think the trimming of other values is more problematic unless we can provide a sensible way to escape things. From a quick glance, it's not entirely clear which part of the Spring Boot code is actually trimming those values. Nothing in `org.springframework.boot.context.properties.bind` seems to be doing it. Perhaps it's related to our new property loading. We'll need to dig a bit deeper.

**Comment by philwebb** [comment]
This is a bug in `OriginTrackedPropertiesLoader`. If I add `withspace=  with  ` to the `test-properties.properties` used by `OriginTrackedPropertiesLoaderTests` then `compareToJavaProperties` fails.

**Comment by jacekkruger** [comment]
It should now work just like before but I'm also curious why is the leading whitespace trimmed? Haven't found that documented anywhere.

**Comment by wilkinsona** [comment]
It's specified in the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) for `Properties.load` where it says:

> Any white space after the key is skipped; if the first non-white space character after the key is '=' or ':', then it is ignored and any white space characters after it are also skipped. All remaining characters on the line become part of the associated element string
