### ISSUE TITLE
Support multiple paths in DispatcherServletPathProvider

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#13603]

**Comment by mbhave** [comment]
@filiphr You're right, it is a breaking change between `2.0.3` and `2.0.4`. However, the `DispatcherServletPathProvider` was introduced quite recently (in `2.0.2`) and we didn't expect that there would be too many consumers of this class. This change originally stemmed from #13527. 

I'll reopen the issue to see what the rest of the team thinks.

**Comment by filiphr** [comment]
Thanks for having a look at it. I noticed that it is quite new as well. My usage for it is due to #13183

**Comment by wilkinsona** [comment]
I think the breaking change is OK as it is fixing a bug in the API. While the default method is a nice non-breaking solution, I don’t think it is warranted in this case.

**Comment by philwebb** [comment]
Reopened because #12971 is making me reconsider if we should have multiple path support

**Comment by philwebb** [comment]
See also #12934

**Comment by philwebb** [comment]
We're going to roll back support for multiple paths because of the issues identified in #13834
