### ISSUE TITLE
Spring Boot v1.5.x cannot override multiline properties

### ISSUE THREAD

**Issue by bacey** [spring-projects/spring-boot#13617]
A minimal working example, which demonstrates the bug, can be found here: https://github.com/bacey/bootbug

Spring Boot (version 1.5.x and 2.1.x) can read properties (or more specifically, a list of property values) without problems:

```
propertyWithValuesListedInASingleLine: val1a from test/r/app.yml, val2a from test/r/app.yml, val3a from test/r/app.yml

propertyWithValuesListedInMultipleLines:
    - val1b from test/r/app.yml
    - val2b from test/r/app.yml
    - val3b from test/r/app.yml

propertyWithValuesListedInASingleLineInAnArray: [val1c from test/r/app.yml, val2c from test/r/app.yml, val3c from test/r/app.yml]
```

Spring Boot can override properties using this syntax:

```java
@SpringBootTest(
        properties = {
                "propertyWithValuesListedInASingleLine=inline overriding value1a, inline overriding value2a, inline overriding value3a",
                "propertyWithValuesListedInMultipleLines=inline overriding value1b, inline overriding value2b, inline overriding value3b",
                "propertyWithValuesListedInASingleLineInAnArray=inline overriding value1c, inline overriding value2c, inline overriding value3c"
        }
)
```

Unfortunately, Spring Boot version 1.5.x can only override such a property which is defined in one single line and without brackets:

```
propertyWithValuesListedInASingleLine: val1a from test/r/app.yml, val2a from test/r/app.yml, val3a from test/r/app.yml
```

But it cannot override these (although it can read them without a problem):

```
propertyWithValuesListedInMultipleLines:
    - val1b from test/r/app.yml
    - val2b from test/r/app.yml
    - val3b from test/r/app.yml

propertyWithValuesListedInASingleLineInAnArray: [val1c from test/r/app.yml, val2c from test/r/app.yml, val3c from test/r/app.yml]
```

Spring Boot version 2.1.x does not exhibit this bug: it can read and override multiline and "bracketed" properties without any problems.

To see the failing tests, please check out the https://github.com/bacey/bootbug repo and run the commands specified in its README.

**Comment by philwebb** [comment]
See also #10172

This is unfortunately a known issue with the property binding in Spring Boot 1.5 and it was one of the drivers for redeveloping it in 2.0. Unfortunately there's no easy way to fix this with the 1.5 code so it will have to remain as a known 1.5.x limitation.

If at all possible, I'd suggest upgrading to 2.0.x.
