### ISSUE TITLE
Accommodate for disabling Tomcat WebResource caching.

### ISSUE THREAD

**Issue by chtompki** [spring-projects/spring-boot#13613]
I would like to have a configuration option that accommodates toggling the Tomcat WebResource caching mechanics. Currently I would need to declare the following bean:

```java
@Bean
@ConditionalOnClass(name = "org.apache.catalina.startup.Tomcat")
public WebServerFactoryCustomizer<TomcatServletWebServerFactory> chassisTomcatCustomizer(
    final ServerProperties serverProperties, @Value("${server.tomcat.is-web-resource-caching-allowed}") boolean isWebResourceCachingAllowed) {
  return (factory) -> {
    factory.addContextCustomizers((context) -> {
      WebResourceRoot webResourceRoot = context.getResources();
      if (webResourceRoot == null) {
        webResourceRoot = new StandardRoot(context);
      }
      webResourceRoot.setCachingAllowed(isWebResourceCachingAllowed);
      context.setResources(webResourceRoot);
    });
  };
}
```

which feels like a contrivance. It would be nice if you (or if you'd let me contribute the code), had something in `ServerProperties.Tomcat` that accommodated for `server.tomcat.is-web-resource-caching-allowed` where it defaults to `true`.

Thoughts?

**Comment by chtompki** [comment]
I'm on the PMC for Apache Commons, but I haven't done any Spring contributions before. Do let me know if I've done things properly here.

**Comment by philwebb** [comment]
Thanks for the suggestion and the PR. I'll close this one and we can continue the discussion in #13614
