### ISSUE TITLE
Liquibase ServiceLocator is initialized twice

### ISSUE THREAD

**Issue by benbenw** [spring-projects/spring-boot#13615]
In our app (2.0.3) the liquibase ServiceLocator initialization in LiquibaseServiceLocatorApplicationListener$LiquibasePresent#replaceServiceLocator accounts for ~20% of the memory allocated at startup.

The classpath is scanned twice in ServiceLocator#setResourceAccessor
- in the default ServiceLocator constructor
  - called by the static block initialization
- in the CustomResolverServiceLocator constructor in LiquibasePresent#replaceServiceLocator

I'm afraid nothing can be done on the spring boot side.
I've created this bug to eventually track the liquibase bug (https://liquibase.jira.com/browse/CORE-3273).

<img width="1190" alt="liquibase" src="https://user-images.githubusercontent.com/5681005/42097969-d4b93d9c-7bb9-11e8-87e8-8db2f1ce34f3.png">

**Comment by wilkinsona** [comment]
Thanks for the analysis and for opening the Liquibase issue which I am now watching. We don't need an issue to track this in Boot as we'll pick up the new version of Liquibase as part of our regular dependency upgrade process once it becomes available.
