### ISSUE TITLE
SsEmitter closes response stream if Gson is used

### ISSUE THREAD

**Issue by hydroid7** [spring-projects/spring-boot#13628]
When using `SseEmitter` and `Gson` is configured as global message converter, the response stream is closed after every update.

[Demo Repository to reproduce the bug](https://github.com/hydroid7/spring-sse-gson-bug)

**Comment by wilkinsona** [comment]
Thanks for the sample. It's using 1.3.0.M1 which was released 3 years ago. Before raising an issue, please take the time to upgrade to at least the latest minor release as the problem may have already been fixed. At the time of writing, the latest release in the 1.x line is 1.5.14.RELEASE. The problem does not occur with this version.
