### ISSUE TITLE
Support microseconds in Duration conversions

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-boot#13624]
When `ms` is too long, one has to resort to using `ns` right now but it's 6 orders difference. It would be useful to support `μs` as a unit in between. It could be a little cumbersome to type as alt+m but I guess it'd be ok occasionally. My specific use case is with scaling micrometer histograms where calls take less than a millisecond to complete but still in thousands of nanoseconds, so microseconds would be very welcomed to be configured through external configuration.

**Comment by philwebb** [comment]
I wonder if we could come up with some other suffix that's easier to type and less likely to get messed up by character encoding. Perhaps `mu`?

**Comment by wilkinsona** [comment]
How about `us`?

**Comment by snicoll** [comment]
Reopening as the metadata [won't be generated properly](https://github.com/spring-projects/spring-boot/blob/60457f1d9ad9984d3da04dec0600ce3de875deae/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/main/java/org/springframework/boot/configurationprocessor/fieldvalues/javac/JavaCompilerFieldValuesParser.java#L108) if that style is used

**Comment by snicoll** [comment]
I thought we were doing something special with `DurationStyle` but we don't. As there isn't a way to construct such value, I guess that's fine even though this is now a format we can only used as an input and that we can't have as default value. Are we ok with that inconsistency?

**Comment by wilkinsona** [comment]
I'm fine with that.
