### ISSUE TITLE
Error in documentation section 29.3.3 Creating and dropping JPA databases

### ISSUE THREAD

**Issue by zendu** [spring-projects/spring-boot#13699]
Documentation error in Spring Boot Reference document
Spring Boot 1.5.8 (https://docs.spring.io/spring-boot/docs/1.5.8.RELEASE/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases)
Spring Boot current (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases)

Section "29.3.3 Creating and dropping JPA databases" mentions following.

> You can set it, along with other Hibernate native properties, by using spring.jpa.properties.* (the prefix is stripped before adding them to the entity manager). The following line shows an example of setting JPA properties for Hibernate: `spring.jpa.properties.hibernate.globally_quoted_identifiers=true`

In fact, the properties need to be set as `spring.jpa.hibernate.globally_quoted_identifiers=true`. Notice the missing "properties" word. This is misleading for new users.

**Comment by wilkinsona** [comment]
Thanks for the report, but I believe your analysis is incorrect. 

Boot provides first-class support for a small number of Hibernate-specific properties. These are the following:

```
spring.jpa.hibernate.ddl-auto= # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
spring.jpa.hibernate.naming.implicit-strategy= # Fully qualified name of the implicit naming strategy.
spring.jpa.hibernate.naming.physical-strategy= # Fully qualified name of the physical naming strategy.
spring.jpa.hibernate.use-new-id-generator-mappings= # Whether to use Hibernate's newer IdentifierGenerator for AUTO, TABLE and SEQUENCE.
```

Additionally, other properties can be passed in using `spring.jpa.properties.*`. As described in the documentation that you have quoted above, the `spring.jpa.properties.` prefix is removed. For example, this means that the property `spring.jpa.properties.hibernate.globally_quoted_identifiers` is passes to Hibernate as `hibernate.globally_quoted_identifiers`.

If you believe you've found a problem with configuring properties on Hibernate, please provide a small sample that illustrates the problem and we can re-open this issue and investigate. As far as I can tell, the documentation is correct.
