### ISSUE TITLE
Latest releases are not published to SDKMAN

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#13702]
It appears that the `2.0.3.RELEASE` and `1.5.14.RELEASE` weren't published to SDKMAN since `2.0.2.RELEASE` and `1.5.13.RELEASE` are still the most recent available candidates.

**Comment by wilkinsona** [comment]
Thanks, @vpavic. We missed updating Homebrew for 2.0.3 as well.

**Comment by wilkinsona** [comment]
1.5.14.RELEASE and 2.0.3.RELEASE are now available on SDKMAN and a [pull request](https://github.com/pivotal-legacy/homebrew-tap/pull/114) for updating the Homebrew tap has been submitted.

Thanks again for letting us know, Vedran.
