### ISSUE TITLE
Ensure reference manual doesn't generate horizontal scrollbar

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#13709]
Spring Boot's reference manual currently generates horizontal scrollbar at common screen sizes, which is a bit annoying for the reader.

The cause of this is a table in _Customize the Jackson ObjectMapper_ section which has a cell containing value `spring.jackson.default-property-inclusion=always|non_null|non_absent|non_default|non_empty` that sticks out like a sore thumb and results in a horizontal scrollbar being rendered. This is present in both `1.5.x` and `2.0.x`:

- https://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#howto-customize-the-jackson-objectmapper
- https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#howto-customize-the-jackson-objectmapper

Ideally, the horizontal scrollbar (if really needed) should be placed on the enclosing element (table in this case) rather than on the whole document. This approach is already present in many places in the reference manual, like the [application properties appendix](https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#common-application-properties).

**Comment by wilkinsona** [comment]
Well spotted, @vpavic. Thanks. I haven't been able to figure out how to get Asciidoctor to add a scroll bar to a table like it does to a code block, so I've taken the approach of reformatting the table so that it will at least fit within the default width.
