### ISSUE TITLE
exclude spring-core from spring-retry

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#13701]
https://github.com/spring-projects/spring-boot/blob/v2.0.3.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml

handles spring-retry, but this has a dependency to spring-core 4.x.

the right thing to do is probably to exclude spring-core from spring-retry.

maven dependency-tree:
```
...
[INFO] +- org.springframework.retry:spring-retry:jar:1.2.2.RELEASE:compile
[INFO] |  \- org.springframework:spring-core:jar:4.3.13.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-config:jar:5.0.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-beans:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-core:jar:5.0.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.0.7.RELEASE:compile
...
```

**Comment by wilkinsona** [comment]
`spring-retry` requires `spring-core` so it shouldn’t be excluded. If you use Boot’s dependency management the `spring-core` dependency will be managed to an appropriate version. If you are using Boot’s dependency management and that is not happening, please provide a small sample that reproduces the behaviour and we can re-open this issue and investigate.
