### ISSUE TITLE
Make SpringBootConfigurationFinder public and usable with other annotations

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#13713]
I'm trying to extend Spring Boot's integration testing feature and need to introduce a custom root application annotation. My custom test annotation now has to find this exact annotation, exactly in the same way `SpringBootConfigurationFinder` looks up `@SpringBootConfiguration` annotations.

Ideally I'd just reuse the class and would like to pass the annotation I'd like to find into its constructor.

**Comment by philwebb** [comment]
Making it public isn't a big change, but I'm wondering if adding `@SpringBootConfiguration` to your custom root annotation might be better. Have you got a bit more background about the feature you're developing?

**Comment by olivergierke** [comment]
I need to find an annotation equipped with `@SpringBootConfiguration` to evaluate some of its attributes. I've invited you to the repo containing that code.

**Comment by philwebb** [comment]
Got it, thanks. Do you need this in 2.0.x or will 2.1 suffice?

**Comment by olivergierke** [comment]
I of course wouldn't mind to see it in 2.0, but could very well live with a change in 2.1. For now I just copied the class.

**Comment by philwebb** [comment]
Closing in favor of PR #13904
