### ISSUE TITLE
Spring data jpa query creation keyword "Like" is not work

### ISSUE THREAD

**Issue by MrParkerZ7** [spring-projects/spring-boot#13729]
The keyword "Like" in query creation is not work. 
I was try to use in java and kotlin spring both. But, the result is completely equal to findByXxx.
It's not work event IgnoreCase if gonna findByName which value name is "Park" if i put "park" into parameter it not gonna found anything.

Thank you.

**Comment by philwebb** [comment]
Spring Data use a different issue tracker, you'll need to raise your issue [here](https://jira.spring.io/projects/DATACMNS). I'm not totally understanding the issue as you've described it, so I'd suggest providing a small sample that shows what you mean.
