### ISSUE TITLE
@WebMvcTest should register PageableHandlerMethodArgumentResolver

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#13730]
I tried to return a `Page`  from my controller and wrote a `@WebMvcTest` tests, and inject a `MockMvc`, I found it does not work as expected.

I have to switch `@SpringBootTest` and use `MockMVcBuilders` to  register `PageableHandlerMethodArgumentResolver` and build a `MockMvc` manually  to make it work.

**Comment by wilkinsona** [comment]
Duplicate of #13066
