### ISSUE TITLE
If add @EnableRedisHttpSession，the RedisSessionConfiguration will be invalid.

### ISSUE THREAD

**Issue by kinglcc** [spring-projects/spring-boot#13731]
The code such as

```
import org.springframework.session.data.redis.config.annotation.web.http.EnableRedisHttpSession;

@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 7200, redisNamespace = "demo:sessions")
public class HttpSessionConfig {
}
```
Then, the `RedisSessionConfiguration` is invalid. And, the `spring.session` configuration is invalid, such as spring.session.redis.namespace.

**Comment by wilkinsona** [comment]
This is working as designed. When you add `@EnableRedisHttpSession` you are takin full control so the auto-configuration backs off.
