### ISSUE TITLE
AWS EC2 instance with spring-boot process issue 

### ISSUE THREAD

**Issue by gkizior** [spring-projects/spring-boot#13745]
I am running a spring-boot application on a AWS EC2 instance. The instance has remained healthy but the spring boot application I am running on it fails to receive http calls after it has been running for a while (~12 hours).
I am running the spring-boot application by the following:
`nohup java -jar target/xxx-0.0.1-SNAPSHOT.jar &`

The process has never prematurely terminated - that can be verified with `fuser 8080/tcp`. 

The problem is that the process running and the spring-boot application working as intended seem to be independent.

What is the proper way to run a spring boot application and keep it executing until manually terminating on a AWS EC2 instance?

**Comment by wilkinsona** [comment]
> What is the proper way to run a spring boot application and keep it executing until manually terminating on a AWS EC2 instance?

I can't see anything improper about what you have done.

>  it fails to receive http calls after it has been running for a while (~12 hours)

We'll need to dig into this some more. In what way does it fail to receive the HTTP calls? How does the client behave and what state are the server threads in at this point?

**Comment by gkizior** [comment]
Client is using `HttpClient` angular's `@angular/common/http`

and chrome devtool says `Failed to load resource: net::ERR_CONNECTION_REFUSED` when performing the HTTP calls

**Comment by wilkinsona** [comment]
Connection refused doesn't really tell us much, we need to figure out why the connection was refused. As requested above, the state of the server threads when connections are refused will help us to do that. Can you take a thread dump when the server stops accepting connections and share it here?
