### ISSUE TITLE
Embedded Database - Prevent automatic dropping of tables.

### ISSUE THREAD

**Issue by kennyk65** [spring-projects/spring-boot#1374]
Referencing Issue #621 - there is an issue where Boot has made the decision that all tables in an embedded database should be dropped on startup.  I don't think Boot should default to doing that -- for one thing an embedded db is typically empty already unless you take measures to populate it, such as placing sql in schema.sql and data.sql.  But even if it does, one should be able to override this behavior as described in the reference documentation, or the reference document should be updated to clarify that this default behavior cannot be overridden.

I'm using Boot 1.1.5 (current as of today). I'm populating an H2 DB with schema.sql and data.sql.  After the SQL runs, JPA starts in drop-create mode and drops all of the tables.   According to the [current reference](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-initialize-a-database-using-jpa), One should be able to override this behavior with one of the following:

```
spring.jpa.hibernate.ddl-auto=none 
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.hbm2ddl.auto=none
```

But I've found these settings don't alter the behavior.  I've also tried setting `ddl-auto` explicitly to "" without success. JPA happily deletes the tables and data that were previously created in the `schema.sql` and `data.sql` files.

The only workaround that I found was to use the hibernate-specific `import.sql` instead of `schema.sql` and `data.sql` files. When present, this keeps the drops from happening.

At minimum, perhaps the information on those settings can be clarified in the docs since the current reference makes it sound that these settings will in fact alter the behavior, see http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-intialize-a-database-using-spring-jdbc

**Comment by lava18** [comment]
I am still facing this problem and all documentation I read till now is not helping.
Can anyone please help with what was the final solution for preventing JPA Hibernate to drop tables when server stops?

**Comment by snicoll** [comment]
@lava18 we don't use the issue tracker for questions. Please ask on StackOverflow or join us on Gitter.

**Comment by SwingGuy1024** [comment]
Thank you for the suggestion to add
  `spring.jpa.generate-ddl=false`
to my application.properties file. Now I'm trying to figure out where in the Spring Boot documentation it says to use this.

**Comment by madmaxfreestyles** [comment]
spring.jpa.hibernate.ddl-auto=update

This will help; remember this property from hibernate .cfg file ?

**Comment by corneel** [comment]
OMG how can the the decision ever be to drop all the tables. Whose brain-dead idea was that?

**Comment by wilkinsona** [comment]
@corneel We've changed our minds in the past and I am sure that we will again in the future, but this isn't a good way to ask us to do so. It leaves us frustrated as we struggle to assume positive intent and it leaves you frustrated as your suggestion isn't given serious consideration.

If you would like us to consider a change in behaviour here, please open a new issue that explains the problem that the current behaviour causes and what you think a better default would be.

**Comment by salueii** [comment]
to disable table recreation in Spring Boot application just add this line

spring.jpa.generate-ddl=false

to application.properties
