### ISSUE TITLE
Using custom FreeMarkerConfigurationFactoryBean does not work on Web Application

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#13748]
There are 3 ways the freemarker auto configuration is configured:

* [FreeMarkerNonWebConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/freemarker/FreeMarkerNonWebConfiguration.java) - it works fine here
* [FreeMarkerServletWebConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/freemarker/FreeMarkerServletWebConfiguration.java) - providing a custom `Configuration` is not taken into consideration. One needs to provide `FreeMarkerConfig` in order to override it
* [FreeMarkerReactiveWebConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/freemarker/FreeMarkerReactiveWebConfiguration.java) - same as the Servlet one

Initially I thought that one can use 

```
@Bean
@ConditionalOnMissingBean(FreeMarkerConfig.class)
public FreeMarkerConfigurer freeMarkerConfigurer(ObjectProvider<Configuration> configurationProvider) {
	FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
        freemarker.template.Configuration configuration = configurationProvider.getIfAvailable();
        if (configuration == null) {
            applyProperties(configurer);
        } else {
            configurer.setConfiguration(configuration);
        }
	
	return configurer;
}
```

However, this is would create cyclic dependencies I suppose. Correct me if I am wrong. Therefore, another solution could be to do what the `FreeMarkerNonWebConfiguration` is doing and expose the configuration through there instead of through the other configurers

**Comment by filiphr** [comment]
Sorry for the confusion. The problem that I want to solve is to provide a custom `freemarker.template.Configuration` and not use the one that Spring Boot creates. 

In our application we actually don't need the Freemarker web templates, but we want to use Freemarker for emails for example. We are defining our own `freemarker.tempalte.Configuration` for that. However, we have to exclude the `FreemarkerAutoConfiguration` as it interferes with our own.

`FreemarkerFactoryBean` that one actually comes from `org.springframework.ui.freemarker` from `spring-context-support`

**Comment by wilkinsona** [comment]
> FreemarkerFactoryBean that one actually comes from org.springframework.ui.freemarker from spring-context-support

Unless I'm missing something, there's no such class. Do you mean `FreeMarkerConfigurationFactoryBean`?

**Comment by filiphr** [comment]
Damn, yes that is what I mean. Sorry for the confusion. I did a typo. I will edit my issues.

**Comment by wilkinsona** [comment]
Ok, thanks. I think I understand what you'd like to do now but Spring Framework's web-based FreeMarker support doesn't work that way.

From the javadoc of `FreeMarkerView`:

> Depends on a single FreeMarkerConfig object such as FreeMarkerConfigurer being accessible in the current web application context, with any bean name. Alternatively, you can set the FreeMarker Configuration object as bean property. See setConfiguration for more details on the impacts of this approach.

The web-based auto-configuration creates a `FreeMarkerConfigurer` bean so that it can be retrieved from the context by `FreeMarkerView`. The alternative that's described isn't really applicable here as Boot isn't creating the `FreeMarkerView` instances so there's no opportunity for it to set the `Configuration` on it.

What's the problem with providing your own `FreeMarkerConfigurer` bean as a source for the `Configuration`?

**Comment by filiphr** [comment]
Spring Boot uses `FreeMarkerConfigurer` and from its `FreeMarkerConfigurer#setConfiguration` it says:

>Set a preconfigured Configuration to use for the FreeMarker web config, e.g. a
>shared one for web and email usage, set up via FreeMarkerConfigurationFactoryBean.
>If this is not set, FreeMarkerConfigurationFactory's properties (inherited by
>this class) have to be specified.
>@see org.springframework.ui.freemarker.FreeMarkerConfigurationFactoryBean

The thing is that we don't need the `FreeMarkerView` at all. However, we are providing a library of our tools to other developers, which means that they either need to do this manually if they need it and / or exclude the `FreeMarkerAutoConfiguration`. 

That is why I thought that it would be good if there is a single consistent way from Spring Boot to provide the `Configuration` and then use that within the appropriate configurers. As currently if one needs to use both email and web templates and want to customize the `Configuration` they would need to do 2 things on their own instead of just customizing the `Configuration`. Not sure if that made sense?

**Comment by wilkinsona** [comment]
> As currently if one needs to use both email and web templates and want to customize the Configuration they would need to do 2 things on their own instead of just customizing the Configuration

Why do they need to do two things? All they need to do is provide a custom `FreeMarkerConfigurer`. That will be used by `FreeMarkerView` and they can also use it to get a `Configuration`.

**Comment by filiphr** [comment]
Well if an enhanced configuration comes from some other auto configuration for example that won't be possible. As currently it is also not possible to have a configurer of the `Configuration`

**Comment by wilkinsona** [comment]
That sounds like a flaw with the other auto-configuration. It should either create a `FreeMarkerConfig` bean or a `Configuration` bean depending on whether or not it's a web application.

> That will be used by `FreeMarkerView` and they can also use it to get a `Configuration`.

Looking more closely at the code, it's actually simpler than this. The auto-configuration will automatically take care of exposing the `Configuration` from the `FreeMarkerConfig` as a bean so you can just inject `Configuration` without having to go via the `FreeMarkerConfig`.

**Comment by filiphr** [comment]
What is the flaw with the other-configuration? That configuration wants to customize the `Configuration`? In case we want to do this one has to have 3 conditionals to check whether we are in a SERVLET, REACTIVE or non web application and provide the appropriate beans

**Comment by wilkinsona** [comment]
> What is the flaw with the other-configuration? That configuration wants to customize the `Configuration`?

Correct. Customizing the `Configuration` is insufficient for the reactive and servlet cases. In both of those cases a `FreeMarkerConfigurer` is needed. It's used to create the `Configuration` bean so it can't also be configured with a custom `Configuration` bean. As you've already noted, that would create a cycle.

> one has to have 3 conditionals to check whether we are in a SERVLET, REACTIVE or non web application and provide the appropriate beans.

Correct, you'll have to check for the 3 different environments. That will match what Boot's own auto-configuration does.
