### ISSUE TITLE
Provide support for actuators and /error rendering with Gson

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13766]
The Jackson dependency can be a burden for some apps (Gson is faster, and some people just prefer it). It would be good to provide an option. It's complicated in webflux by the fact that Gson doesn't support non-blocking rendering out of the box, but probably worth it.

**Comment by wilkinsona** [comment]
> It's complicated in webflux by the fact that Gson doesn't support non-blocking rendering out of the box

That's a bit more than a complication, isn't it? Doesn't it mean that it's currently impossible in WebFlux?

**Comment by wilkinsona** [comment]
This feels more important now in light of #18139. Moving up to 2.x.

**Comment by philwebb** [comment]
I wonder if we should try to fail hard if GSON is used? We're getting a few bug reports because it _appears_ to work even though we don't support it.

**Comment by dsyer** [comment]
Also maybe this is interesting: https://github.com/FasterXML/jackson-jr

**Comment by bclozel** [comment]
We've just fixed #12951, so as of Spring Boot 2.3, an application can choose Gson as a preferred JSON mapper and not risk Actuator endpoint responses being broken.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by pedrohms** [comment]
still not working with Gson. Has anyone found an alternative?

**Comment by marcgise** [comment]
I have the same problem using GSON. Basically ChatGPT and all Internet says to use Jackson...
