### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/springframework/boot/context/properties/bind/PlaceholdersResolver. Method lambda$static$0(Ljava/lang/Object;)Ljava/lang/Object; at index 31 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

### ISSUE THREAD

**Issue by dada1008** [spring-projects/spring-boot#13767]
Getting below error when executing junit tests while maven build on Java 10, In Java 8 it is working fine.

java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/springframework/boot/context/properties/bind/PlaceholdersResolver. Method lambda$static$0(Ljava/lang/Object;)Ljava/lang/Object; at index 31 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

My test class contains below annotations -
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringRunner.class)
@SpringBootTest(classes = {RestConfig.class, Command.class, 
	CommonService.class})
@PowerMockIgnore("javax.management.*")
@PrepareForTest({ RestRequestHandler.class, SOAPRequestHandler.class, SoapClient.class })

Spring boot version 2.0.3
Java 10.0.1
OS: Windows 10 64-bit

Please let me know if you need any additional details.

**Comment by dada1008** [comment]
When I comment @SpringBootTest annotation my test cases get executed

**Comment by wilkinsona** [comment]
Without `@SpringBootTest`, I don't think `PlaceholdersResolver` will even be loaded. I suspect the problem may actually be caused by PowerMock. Does the problem occur in tests that do not use PowerMock?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by dada1008** [comment]
This issue got fixed after
change annotation @SpringBootTest(classes =...
to @ContextConfiguration(classes =...
