### ISSUE TITLE
Separate LogFileWebEndpoint from the concern of actually logging files

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-boot#13768]
🎁 Enhancement

`LogFileWebEndpoint` seems to have an assumption baked into it that the Spring `LoggingSystem` will be responsible for writing a log file to disk. To get this endpoint to function, we need to set the `logging.file` or `logging.path` properties which has the side effect of also making the `LoggingSystem` write to those locations. However, in the case where we are already piping stdout to a file through something like cronolog, trying to use those properties to serve up the cronolog file results in both cronolog and Spring writing to the same location. 

It seems less than ideal to have to choose between cronolog and this LogFileWebEndpoint, and I do acknowledge that we could configure the `LoggingSystem` to replicate the functionality we currently get from cronolog. However, before doing that I wanted to raise the question of whether or not it would be reasonable to add a new property such that we could configure the resource location served by `LogFileWebEndpoint` without enabling a log appender from Spring Boot.

**Comment by wilkinsona** [comment]
This is already supported by setting `management.endpoint.logfile.external-file`.

**Comment by wilkinsona** [comment]
Duplicate of #4836.
