### ISSUE TITLE
Update HttpPutFormContentFilter auto-configuration to reflect its deprecation and the introduction of  FormContentFilter

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13769]
In Framework 5.1, `HttpPutFormContentFilter` has been deprecated and `FormContentFilter` has be introduced as its replacement. We need to reflect this in our auto-configuration. I think we'll have to replace the auto-configuration as I don't think both filters will work in tandem (and there would be no benefit even if they did).

**Comment by bclozel** [comment]
Related to #13363

**Comment by wilkinsona** [comment]
Oops. Thanks, @bclozel. Rather than just being related, I think this one is a duplicate.
