### ISSUE TITLE
SpringBoot2 endpoint deploy error in parent-child ApplicationContext

### ISSUE THREAD

**Issue by fangjian0423** [spring-projects/spring-boot#13777]
When I using SpringBoot 2.0.1， I define custom endpoint autoconfiguration class and write it in spring.factories：

`
org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration=\
org.springframework.boot.test.MyEndpointAutoConfiguration
`

autoconfiguration class:

`
@ManagementContextConfiguration
public class MyEndpointAutoConfiguration {

    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnEnabledEndpoint
    public MyEndPoint myEndPoint() {
        return new MyEndPoint();
    }

}
`

When management port and application server port same, it's ok.

but if port is different, this endpoint deploy error. 

I read some source and find that endpoints construct by WebEndpointDiscoverer.

WebEndpointDiscoverer build endpoints from parent ApplicationContext, but MyEndPoint was build by child ApplicationContext. so WebEndpointDiscoverer won't found endpoints that construct by child ApplicationContext.

If i modify spring.factories like this:

`
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
org.springframework.boot.test.MyEndpointAutoConfiguration
`

this endpoint deploy success because WebEndpointDiscoverer build endpoints from parent ApplicationContext and MyEndpointAutoConfiguration construct by parent ApplicationContext.

At last, I have a question:

The best way of define custom endpoint in SpringBoot2 is using the key "org.springframework.boot.autoconfigure.EnableAutoConfiguration" in spring.factories and using @ConditionalOnClass(value = ManagementContextConfiguration.class) in autoconfiguration class. Is it right or is there a better way to do this ?

Thanks, English is poor.

**Comment by wilkinsona** [comment]
There’s no need to use `@ManagementContextConfiguration` in Spring Boot 2.0 (which is why it’s no longer mentioned in the reference documentation). You should use an auto-configuration class. There’s no need for `@ConditionalOnClass(value = ManagementContextConfiguration.class)`.
