### ISSUE TITLE
`@RequestParam` throws `java.lang.NullPointerException: The mapper returned a null value.`

### ISSUE THREAD

**Issue by NeveHanter** [spring-projects/spring-boot#13786]
The reactive controller method with `@RequestParam(required = false)` parameter fails with `java.lang.NullPointerException: The mapper returned a null value.` and returns HTTP 500 instead of the HTTP 400 with some conversion error message when called with empty parameter value, i.e. `integer?parameter=` or `boolean?parameter=`.

I've pushed [sample project](https://github.com/NeveHanter/spring_boot_request_param_bug) using spring-boot `2.0.3.RELEASE` with failing JUnit 5 tests for integer and boolean types of parameter and one successful test with string type parameter.

**Comment by snicoll** [comment]
Thanks for the sample.

The `@RequestParam(required = false)` is noise as it  fails the same way without it (that test is actually passing the parameter with an "empty" value). None of this is handled here so please open an issue [in the Spring Framework issue tracker](https://https://jira.spring.io/browse/SPR).

**Comment by bclozel** [comment]
See https://jira.spring.io/browse/SPR-17050
