### ISSUE TITLE
spring-boot-gradle-plugin: importing an already imported BOM will override that BOM

### ISSUE THREAD

**Issue by jfourment** [spring-projects/spring-boot#13780]
We are using dependency management with spring boot on a multi-modules application.
One of this module contains the main class and some properties and aggregates all other modules to build a spring boot jar:

    moduleA
    moduleB
    module-jar (which depends on A and B)

Dependency management is defined in root build.gradle for all subprojects and imports spring-boot-dependencies bom.

The plan is to use spring-boot plugin in conjunction with dependency management plugin in all modules, but only have the spring boot task available in the module-jar module.

In order to have dependency management applied to all modules, root build.gradle file looks like this:

```
plugins {
    id "io.spring.dependency-management" version "1.0.5.RELEASE"
    id "org.springframework.boot" version "1.5.14.RELEASE" apply false
}
subprojects {
    apply plugin: 'io.spring.dependency-management'
    configurations {
        all {
            dependencyManagement {
                imports {
                    mavenBom ("org.springframework.boot:spring-boot-dependencies:1.5.14.RELEASE") {
                            bomProperty "hibernate.version", "5.2.17.Final"
                    }
                }
```
And in order to build the spring boot app in our specific module, the spring-boot plugin is applied again in this module and the build.gradle looks like this:

```
apply plugin: 'org.springframework.boot'
dependencies {
    implementation group: 'org.hibernate', name: 'hibernate-core'
....
}
```

Now, what happens is when the spring-boot plugin is applied again in this specific module, it will import the ```spring-boot-dependencies``` again (and therefore ignoring any of the bomProperty overrides at root level). 

It would be nice to have a mechanism in the plugin detecting if a bom has already been imported before applying it.

**Comment by wilkinsona** [comment]
See 
https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/219 where this request originated.

On further consideration, I’m not sure that this is a good idea. I don’t think it would be possible to accurately infer the intent of the second bom import in a multi-module project. Is it essentially unintentional and should be a no-op, or is it deliberate and intended as an override? Only the author of the build knows that so I think the most robust approach is for them to express that in the build. In the example above, I think you could do that by conditionally applying the Spring Boot plugin in the `subprojects` block.
