### ISSUE TITLE
Revert  d9215d5 on Spring Data regression is fixed

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13784]
It looks like Spring Data MongoDB (reactive?) cannot store `Duration` attributes anymore. The `spring-boot-sample-session-webflux` module breaks with `Lovelace` but not with `Kay`.

I'll update the issue as soon as the Spring Data issue is created.

**Comment by mp911de** [comment]
This issue is caused by a bug in Spring Data MongoDB, see https://jira.spring.io/browse/DATAMONGO-2028.

**Comment by mp911de** [comment]
The cause is fixed now in Spring Data MongoDB.
