### ISSUE TITLE
Documentation Issue: 74.1.1 Automatic Property Expansion Using Maven

### ISSUE THREAD

**Issue by LuculentDig** [spring-projects/spring-boot#13788]
The Spring Boot documentation **74.1.1 Automatic Property Expansion Using Maven** said "If you do not use the starter parent, you'll need to include the following element inside the <build/> element of your pom.xml:". And it is not true. Even if you use the starter parent, you still need to inject the plugin inside the pom file. I have tried without it and it didn't work. 

Issue discovered along with Chris Chaney, Andrew Moon, Grace Jensen and Wenyuan Wu (me).

**Comment by snicoll** [comment]
> And it is not true

What does that mean? What file are you trying to filter?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
