### ISSUE TITLE
Include a meter id's base unit and description in the metrics endpoint's output

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#13791]
Spring Boot Admin takes the various time gauges from the metrics endpoint (e.g. `process.uptime`) . Unfortunately the time unit is  not given in the actuator output and can vary depending on the underlying micrometer registry.
Therefore it would be great if either the time unit is fixed in the metrics endpoint or included in the output. Currently the time unit can only be guessed.

**Comment by wilkinsona** [comment]
This looks like a Micrometer bug to me. Both `Statistic.TOTAL_TIME` and `Statistic.DURATION` say that they are "always reported in nanoseconds". `Statistic.MAX` says the same when it represents a time. `MetricsEndpoint` handles `Measurements` which are a `Statistic` and value pair. For measurements for a `TOTAL_TIME`, `DURATION`, or `MAX` statistic, I'd expect the value to always be in nanoseconds, irrespective of the `MeterRegistry` that returned the `Meter`.

@joshiste Can you please open a Micrometer issue? I'll close this one for now but we can re-open it if changes are needed in Boot after all.

**Comment by jkschneider** [comment]
@wilkinsona The javadocs are wrong and have been [changed](https://github.com/micrometer-metrics/micrometer/commit/73d5d5e867fcbd6828a2b68b9b40950e3f8ba211). I think I've mentioned before that it would be better if Spring Boot Admin did not rely on the metrics endpoint. I think it should provide a meter registry implementation that exposes metrics in a way that is peculiar to it.

If we standardize the base unit of time in the metrics endpoint, somebody will complain that the values aren't the same as what they see in their monitoring system. If we align with the monitoring system (what we are doing) somebody will complain about inconsistency depending on implementation. It is a lose-lose situation that highlights the fact that the metrics endpoint is a diagnostic only tool.

**Comment by joshiste** [comment]
@jkschneider 
>  I think it should provide a meter registry implementation that exposes metrics in a way that is peculiar to it.

We try to support spring boot applications without the user having to do serious modifications to it.

> If we standardize the base unit of time in the metrics endpoint, ...

Agreed. What's about the other option to ouptut the baseUnit for the meter in the endpoint? So we don't get inconsistent with other implementation. 
(BTW: Also having the meter's description in the endpoint would be awesome)

@wilkinsona could you reopen the issue?

**Comment by wilkinsona** [comment]
Thanks, @jkschneider.

Even if it's only a diagnostic tool, and putting aside Spring Boot Admin for now, I can see some value in the endpoint exposing the base unit of time of the underlying registry. Do you think it would be worth making `getBaseTimeUnit()` on `MeterRegistry` public so that we could include that information in the endpoint's response?

**Comment by wilkinsona** [comment]
> @wilkinsona could you reopen the issue?

We can re-open it if/when we agree that there's a change to be made. Right now, Boot's hands are tied as Micrometer does not expose a registry's base time unit.

**Comment by joshiste** [comment]
@wilkinsona Imho we should not get the MeterRegistry's BaseUnit, but the one for the meter via ` `Meter.getId().getBaseUnit()` (currently also package scope)

**Comment by joshiste** [comment]
@wilkinsona updated my last comment... `Meter.getId().getBaseUnit()` isn't package scoped. So it would be possible right now. I'd provide a PR if you want me to.

**Comment by wilkinsona** [comment]
@jkschneider Can we use the base unit from the meter id? Judging by the updated javadoc, a statistic’s value will be in the registry’s base unit whereas the meter is makes no such promises. That makes me think that it’s the registry’s that we need. Regardless, I’d prefer to deal with the strongly-typed `TimeUnit` from the registry rather than a `String` from the Id as it will give endpoint clients a fixed set of possible values to deal with.

**Comment by joshiste** [comment]
@jkschneider `meter.getId().getBaseUnit()` is `null` for `process.uptime` having a quick look at the micrometer source tells me that it's always `null` for `TimeGauge`s...
So this issue still depends on a change in micrometer...

**Comment by jkschneider** [comment]
Great, Github API issues caused the same issue to be opened 6 times.

**Comment by jkschneider** [comment]
The `TimeGauge` issue has been resolved for Micrometer 1.0.6.

**Comment by wilkinsona** [comment]
Thanks, Jon. Any thoughts on [using the registry’s base time unit vs the id’s](
https://github.com/spring-projects/spring-boot/issues/13791#issuecomment-405704071)?

**Comment by jkschneider** [comment]
IMO use the ID's. While they should always be matched up on Micrometer-provided meter types, folks are free to do whatever they want on custom meter types.

**Comment by wilkinsona** [comment]
Thanks again, @jkschneider.

@joshiste I think we've got what we need to be able to implement this. A pull request would be much appreciated.

**Comment by wilkinsona** [comment]
Closing in favour of PR #13813.
