### ISSUE TITLE
Default value for server.tomcat.internal-proxies is not aligned with Tomcat's default

### ISSUE THREAD

**Issue by pbialonc** [spring-projects/spring-boot#13798]
Current default regular expression in ServerProperties overrides tomcat fix for:
https://bz.apache.org/bugzilla/show_bug.cgi?id=62389

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java

We should extend internalProxies with IPv6 compliant version.

Thanks

**Comment by wilkinsona** [comment]
Good catch, thank you. I thought we had a test that ensured our default aligned with Tomcat's but it would appear that's not the case. If we did have a test, it would have failed when we upgraded to 8.5.32 without updating our default.

**Comment by wilkinsona** [comment]
I'm wondering why I added an explicit default for this when I fixed https://github.com/spring-projects/spring-boot/issues/1522. We don't have explicit defaults for many other Tomcat properties so I'm wondering if we should just align implicitly. Or perhaps those other properties should also have explicit defaults. Either way, there's an inconsistency that it would probably be good to get rid of.

**Comment by wilkinsona** [comment]
We're going to try to align all of the defaults for our Tomcat properties with Tomcat's own defaults.
