### ISSUE TITLE
Issue while exposing an individual cache as a Bean and through properties   

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-boot#13804]
Hello everyone,

I'm facing an issue with the auto-configuration of my caches (only caffeine caches for your information). I have a library that configures an individual cache as a Bean, and a project consuming this library that configures its caches in a property file. 

The problem is that the caches defined in my property file are not configured, and only the one defined as a Bean is. I don't think this should be the case. Every caches should be correctly configured, and should at least use a different **CacheManager**. 

Please refer to this [sample-project](https://github.com/celcius112/springboot-cache).

Thank you for your time and hard work.

**Comment by snicoll** [comment]
> I don't think this should be the case

This [is working as advertized](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_supported_cache_providers) with the argument that "Generic" takes precedence as a back-off signal if you provide your own configuration.

> Every caches should be correctly configured, and should at least use a different CacheManager.

That use case of mixed types is not taken into account by the auto-configuration. And certainly not configuring multiple `CacheManager` beans (which would be the right call if we ever supported multiple types). If we tried to do that, we'll quickly hit the issue that there is no way to correctly name those manager or determine which one should be used by default.

I am not keen to update the auto-configuration to support that scenario as it would increase the complexity of the auto-configuration by a large factor. Thanks for the suggestion anyway.
