### ISSUE TITLE
Possible bug - Spring Web - WebMvcMetricsFilter has invalid order

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-boot#13800]
Hello Spring fans, 
during source code analysis I think I found potential bug. 
`org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter`  has defined `@Order(Ordered.HIGHEST_PRECEDENCE + 1)` but this value is not applied. 

From the init log
```
2018-07-17 17:44:31.209 DEBUG 14084 --- [ost-startStop-1]                 o.s.b.w.s.ServletContextInitializerBeans : Added existing Filter initializer bean 'webMvcMetricsFilter'; order=2147483647, resource=class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsAutoConfiguration.class]
```
This filter is initialized in `WebMvcMetricsAutoConfiguration`  with `FilterRegistrationBean`, but this initialization does not set filter's order (and default value is the lowest one), it ignores `@Order`.

Suggested fix is to set order during filter registration in `WebMvcMetricsAutoConfiguration`:
`registration.setOrder(Ordered.HIGHEST_PRECEDENCE + 1)` - depends on what's the original design intention (and I suppose the metrics filter should be positioned as the first).

Thank you for your evaluation.

Spring Boot 2.0.3

**Comment by Vity01** [comment]
Ahh damn it, this bug has been already reported.

**Comment by snicoll** [comment]
Duplicate of #13781
