### ISSUE TITLE
New Tag on WebMvc Metrics To Distinguish Status Code Group

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#13801]
_This effects spring boot actuator and specifically it's metrics classes._

**Situation**
I want to graph a count of calls made to an api that returned a 4xx status code.

Some monitoring systems ie. Datadog do not allow wildcards when selecting tag values.

It would be useful to have a tag on those metrics that would group the response codes appropriately. For example these groupings could be:
- 2xx -> success
- 4xx -> client_error
- 5xx -> server_error

So all api calls that returned a status code in the 4xx range would all have a tag "outcome: client_error"

**Comment by wilkinsona** [comment]
@michaelmcfadyen Just in case you aren't already aware, you can do this in your own code by providing a custom `WebMvcTagsProvider` or `WebFluxTagsProvider` bean.

Let's get some feedback from @jkschneider and we can then decide if this is something that we want Boot to offer out of the box.

**Comment by jkschneider** [comment]
I think we should. It's difficult on Prometheus and Atlas too. In fact, I don't know yet of a monitoring system for which we can select tags on `response >= 400`. It's always something like `response ~= [45]\d{2}`, which is just kinda ugly.

I was struggling to think of a tag key, but "outcome" is a clever choice.

**Comment by mveitas** [comment]
One other thing to consider is the option to filter out certain codes from being included in this metric. For example in an API it might be ok to return back 404 as a "valid" status code and including these in the "client_error" metric might not be desirable.

I might suggest that the above is the default implementation, but it's left open to allow a developer to override and provide their own "outcome" bucketing strategy

**Comment by jkschneider** [comment]
Good point @mveitas. I imagine this would come with a default implementation, much like `WebMvcTags#status` [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java#L71).

You'd be free to do your own thing if you provide a custom implementation of `WebMvcTagsProvider/WebFluxTagsProvider`, possibly delegating to the default implementations for everything other than what you want to change.

**Comment by wilkinsona** [comment]
Closing in favour of #14486.
