### ISSUE TITLE
Multi-tenancy enhancement without losing the JPA auto configuration coming from application.properties

### ISSUE THREAD

**Issue by duayres** [spring-projects/spring-boot#13814]
I can't find in the current docs (and in StackOverflow neither) any solution on how change the database schema on the fly (freely switch between two or more schemas). 
So came to me the idea of using multi-tenancy to change the schema (as much overkill it sounds, it seems reasonable). Found a partial solution [here](http://www.baeldung.com/spring-data-jpa-multiple-databases) using another JpaRepository approach.

The main problem is that the use of `@EnableJpaRepositories()` configuration  class (wich do the magic by rewriting the `hibernate.default_schema` property on `EntityManagerFactory`) "kills" the auto-configurer (or overrides, i don't know the inner) for JPA, so everything i've wrote in application.properties (a lot of things) will not be auto-loaded nor applited to datasource, entityManager and transactionManager.

If some feature to create others/aditional transactionManagers (using `@EnableJpaRepositories`) is added, multi-tenancy will be more smoother and the default JPA auto configuration is not lost in the process. 

The secondary enhancement I see (maybe it is more hibernate related) is the option to change schemas on the fly, by parameters (not using an entire `@Transactional("newWholeTransaction")`.

Sorry if I'm wrong and the feature is already implemented. Thanks.

_PS: Spring Boot 2.0.1 with AutoConfiguration enabled and using repositories and envers_

**Comment by wilkinsona** [comment]
Sorry, I don’t understand what you are trying to do. Can you please share a small sample (something that we can unzip or git clone) that shows the minimal configuration for what you’d like to be able to do but that doesn’t work at the moment?

**Comment by duayres** [comment]
Created a gist [here](https://gist.github.com/duayres/f9ca1e5c2a1af45b657e31139008a56b):
The problem is the moment I create an custom JPA configuration, all I've set on my properties/yml file is discarded, because spring assumes my secondary JPA configuration as primary.
I need the auto-config JPA configurations ( datasource, entityManager and transactionManager), and a copy of this, but modifying *only* `spring.jpa.hibernate.properties.default_schame` (and maybe `spring.datasource.url`).

I can't even create a second em/ds in order to use another database schema, see?

I see a major enhancement if the auto-configured JPA is not discarded when one set a secondary JPA configuration (whether based on the auto-configured one or not).

_PS: By auto-configured I mean the one that spring internally creates with the properties in the yml file_

**Comment by wilkinsona** [comment]
Thank you. I understand now.

It would add a huge amount of complexity to the auto-configuration to allow a second JPA setup to be configured alongside the auto-configured setup. For example, how would we differentiate between a user that wants two different JPA setups to co-exist, and a user that wants the auto-configured setup to back off so they can use their own? Even assuming we could find a solution to this, we don't think the extra complexity is worth it.

For the reason above, I'm going to close and decline this enhancement request. Thanks anyway.

**Comment by duayres** [comment]
Got it thanks, for the feedback!

@wilkinsona I know it's not the correct channel but, is there a way I can reuse LocalContainerEntityManagerFactoryBean/EntityManager to create a secondary one? (the intent is the same of this topic)

Or maybe a way to get all the properties in `spring.jpa.*` in application.yml and reapply to my EntityManagerFactoryBean/EntityManager (aggain, some intent).

The idea is not lose all the dataset/entityManager/transactionManager configuration set in `application yml`, or to be more specific: **replicate** what spring do in JPA auto configuration.

Any guide,link, anything is appreciated.
Thanks again.

**Comment by wilkinsona** [comment]
There's a demo repository made by @snicoll [here](https://github.com/snicoll-demos/demo-multi-entity-managers).
