### ISSUE TITLE
Auto-config authorization_code grant for oauth2-client

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#13812]
Spring Security 5.1 has added support for the `authorization_code` grant on the client side.
Boot should also auto-configure the `authorization_code` grant feature just like it does today with `oauth2Login()` feature.

The updated configuration in `OAuth2WebSecurityConfiguration` would be:

```java
@Configuration
@ConditionalOnMissingBean(WebSecurityConfigurerAdapter.class)
static class OAuth2WebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
				.anyRequest().authenticated()
				.and()
			.oauth2Login()
				.and()
			.oauth2()
				.client()
					.authorizationCodeGrant();
	}
}
```

**Comment by jgrandja** [comment]
@mbhave Slight change here.

Instead of:

```
...
  .oauth2()
    .client()
      .authorizationCodeGrant();
```

Please apply:

```
...
  .oauth2()
    .client();
```

This way when we add support for another grant type there is no change required on the Boot end as it will automatically be enabled.

**Comment by mbhave** [comment]
Placing on hold as some upcoming changes in Spring Security might affect this change.

**Comment by mbhave** [comment]
@jgrandja Would you agree that `redirect_uri` for authorization_code clients is a required field?
