### ISSUE TITLE
MessageSourceAutoConfiguration relies on internal method call for BeanFactory.getBean()

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13824]
There might be other places. This is the only one I found so far. I assume there's a weird ordering issue that made it the way it is, but it would be nice to refactor it so that CGLib isn't strictly needed to create the beans in this class.

See also https://github.com/spring-projects/spring-boot/issues/9068

**Comment by dsyer** [comment]
FWIW: this works for me:

```java
	@Bean
	public MessageSource messageSource(MessageSourceProperties properties) {
		ResourceBundleMessageSource messageSource = new ResourceBundleMessageSource();
```

c.f. (from master):

```java
	@Bean
	public MessageSource messageSource() {
		MessageSourceProperties properties = messageSourceProperties();
```

**Comment by snicoll** [comment]
Yup, that's clearly not necessary.

**Comment by snicoll** [comment]
Or not ... https://github.com/spring-projects/spring-boot/issues/9666#issuecomment-313880372

**Comment by dsyer** [comment]
That comment appears to be wrong or out of date. Need to test with a custom `MessageSource` bean to make sure, but it seems to work for a custom `messages.properties` (as in Petclinic for instance) with the code above.

**Comment by snicoll** [comment]
Yep, I've reached the same conclusion.

**Comment by snicoll** [comment]
That being said, I don't think this was added by accident anymore. This auto-configuration has the following: 

```
@ConditionalOnMissingBean(value = MessageSource.class, search = SearchStrategy.CURRENT)
```

Assuming a hierarchy of `ApplicationContext` where the parent is also configured via Spring Boot, the auto-configuration could kick-in in the parent and doing such injection allows to use the expected properties set. One might argue that the set will be exactly the same so it doesn't really matter.

Not entierely sure what to do here.

**Comment by snicoll** [comment]
That will work as the bean in the child will take precedence.
