### ISSUE TITLE
@AutoConfigureMockMvc imports auto-configurations manually

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13822]
`@AutoConfigureMockMvc` has a `secure` attribute that's `true` by default. It is possible for the user to set that to `false` in which case security should not apply.

It is currently implemented using an `@Import` that is conditional on the property. This makes that a very unusual construct for importing auto-configurations. The side effect is that if you exclude the security auto-configuration in your app (via `exclude` on  `@SpringBootApplication`) that exclude is ignored, even if #12586 is implemented.

**Comment by philwebb** [comment]
On hold since if we complete #14227 this should go away

**Comment by izeye** [comment]
This looks resolved as #14227 which supersedes this has been closed.

**Comment by snicoll** [comment]
@izeye the flag has been deprecated but it's still honoured and that still loads the security auto-config manually. The purpose of this issue in the next feature release is to remove the deprecated flag and fix this issue for good.

Does that make sense?

**Comment by izeye** [comment]
@snicoll Sure, I just thought this has been missed accidentally 😄

**Comment by FA-tvonmoll** [comment]
In the meantime: is there a workaround? Excluding the security autoconfiguration in `@SpringBootTest` in addition to `secure = false` still resulted in `401` every time. Context here is an oauth2 resource server with security driven by `@EnableResourceServer`.

My apologies if this is included in one of the other closed tickets already. Thanks! 

```
@SpringBootTest(
    properties =
     "spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration")
@AutoConfigureMockMvc(secure = false)
```

**Comment by mbhave** [comment]
@FA-tvonmoll The `secure` flag doesn't affect custom security. Instead of disabling security completely in your tests, you might want to look at using Spring Security's [test support](https://docs.spring.io/spring-security/site/docs/current/reference/html/test-method.html#test-method-withmockuser) to run your tests as an authenticated user. If you really want to disable security in tests, you can do that by providing your own `@Configuration`class for the test with a `WebSecurityConfigurerAdapter` that allows access to everything. 

If you have any more questions, feel free to join us on gitter.

**Comment by antonalechnovic** [comment]
I am revisiting this change second time in a year in an attempt to fix the deprecation which everyone in the team ignored probably for the same reason of non clear transition, having test which works with annotation:

```
@RunWith(SpringRunner.class)
@WebMvcTest({ExceptionHandlerControllerAdvice.class, NumberController.class})
@AutoConfigureMockMvc(secure = false)
public class XControllerTest {
```

Stops working without `@AutoConfigureMockMvc(secure = false)`

using injected `MockMvc` whether I use annotation on the test/class or don't use it all 403 all the time... Security configuration for the app is very trivial:

```
@Configuration
@EnableWebSecurity
@Profile({"qa", "prod"})
public class SpringSecurityConfig extends WebSecurityConfigurerAdapter {

    @Value("${auth.user}")
    private String user;
    @Value("${auth.password}")
    private String password;

    private final AuthenticationEntryPoint authEntryPoint;

    public SpringSecurityConfig(AuthenticationEntryPoint authEntryPoint) {
        this.authEntryPoint = authEntryPoint;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
            .anyRequest()
            .authenticated()
            .and()
            .csrf()
            .disable()
            .httpBasic().authenticationEntryPoint(authEntryPoint);
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
            .withUser(user)
            .password(password)
            .roles("ADMIN");
    }

    @Bean
    public PasswordEncoder encoder() {
        return new BCryptPasswordEncoder();
    }

}

```

**Comment by wilkinsona** [comment]
@antonalechnovic Being passive aggressive isn't a constructive way to engage the project's maintainers. Madhura offered an alternative which was to use Spring Security's test support. It appears that you've tried that but it didn't work. I can't offer any help on why it didn't work as you haven't shown how you tried to use it. There may be room for further improvement here, but if you want us to make an improvement you're going to have to spend some time to help us to understand why what's currently offered isn't working well for you.

**Comment by antonalechnovic** [comment]
Wow, ok, deleted detailed info, no problems, will refrain from commenting in future, I've shown how I tried to use it in the first post but you seemed to ignored it? But anyway, engaging with people who are trying to use your product this way isn't constructive way either. Good luck.

**Comment by antonalechnovic** [comment]
For all other observers, the `@WithMockUser` didn't appear to work with `@WebMvcTest` using basic auth in memory authentication.
