### ISSUE TITLE
Add starter for OpenID Connect

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#13830]
We should add a starter for Spring Security's OpenID Connect support to make it easier for user's to include the required dependencies.

The required dependencies are:

`spring-security-oauth2-core`
`spring-security-oauth2-client`
`spring-security-oauth2-jose`

**Comment by mbhave** [comment]
It's not clear why this OpenID Connect focused. The starter would be the same even for Oauth `authorization_code` grant?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by wilkinsona** [comment]
Ping @jgrandja. If you'd like us to do something about this one, can you please answer the [question above](
https://github.com/spring-projects/spring-boot/issues/13830#issuecomment-406392056) from @mbhave.

**Comment by rwinch** [comment]
It would not be the same for the authorization grant. OIDC support requires jose but authorization grant does not.

**Comment by snicoll** [comment]
Is that enough to deserve a separate starter though?

**Comment by rwinch** [comment]
The thought was that OAuth2 itself didn't need a separate starter since it is just spring-security-starter-web + spring-security-oauth2-client while logging in with OAuth was 3 different dependencies.

For what it's worth we logged the issue after feedback from the community looking for something to help them set it up.

**Comment by jgrandja** [comment]
@wilkinsona @mbhave @snicoll Apologies for the delayed response. My email filters were not setup correctly so I missed these notifications.

Anyway, let me give some context here with the goal of helping in naming the starter.

As mentioned, there are 3 modules that are used by the OAuth 2.0 Client features:

```
spring-security-oauth2-core
spring-security-oauth2-client
spring-security-oauth2-jose
```

Both `spring-security-oauth2-core` and `spring-security-oauth2-client` provide client features defined in the [OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749) and [OpenID Connect 1.0](http://openid.net/specs/openid-connect-core-1_0.html). 

> FYI, the OAuth 2.0 Authorization Framework is all about **Authorization**, whereas, OpenID Connect 1.0 extends from the OAuth 2.0 Authorization Framework and provides **Authentication**.

The `spring-security-oauth2-jose` module provides features that implement the JOSE (Javascript Object Signing and Encryption) framework, for example, [JWT](https://tools.ietf.org/html/rfc7519), [JWS](https://tools.ietf.org/html/rfc7515), [JWE](https://tools.ietf.org/html/rfc7516), [JWK](https://tools.ietf.org/html/rfc7517) and [JWA](https://tools.ietf.org/html/rfc7518).

The important thing to point out here is that parts of the JOSE framework is leveraged by OpenID Connect Core 1.0 as well as the extension specifications of OpenID Connect. The OAuth 2.0 Authorization Framework **does not** make use (or reference) any parts of JOSE in the spec. However, it doesn't mean that a standard OAuth 2.0 Provider would not implement part of the JOSE framework. For example, it's possible that a standard OAuth 2.0 Provider, may implement JWK and expose a JWK Set that would allow client's or resource server's to verify the token signature. As well, some OAuth 2.0 Provider's may support the JWT token format.

The main point I'm getting at is that the `spring-security-oauth2-jose` module is required when the client is using an OpenID Connect Provider, such as Google, Okta, or UAA. But it also **may be required** for standard OAuth 2.0 Providers that implement/support parts of JOSE.

From @mbhave comment:
> It's not clear why this OpenID Connect focused. The starter would be the same even for Oauth authorization_code grant?

On second thought, I also feel that the starter should not be OpenID Connect focused only. It really should be OAuth 2.0 and OpenID Connect 1.0 focused. It doesn't make sense to have 2 starters: 1 for OAuth 2.0 client and the other for OIDC client. I feel there should be one starter that includes the 3 dependencies. If the client is not using an OIDC provider than they can exclude the `spring-security-oauth2-jose` dependency (if they want to).

So given this, I would suggest the starter name to be something along the lines of `spring-boot-starter-oauth2-oidc-client`.
I think the key is to have `*-oauth2-oidc-client` in the name as the client support is for both OAuth 2.0 (Authorization) and OIDC (Authentication).

When we start building out the Provider features in 5.2+ we can name the Provider starter something like `spring-boot-starter-oauth2-oidc-provider`.

On the Resource Server side of things, I think the name should be `spring-boot-starter-oauth2-resource-server`.
It doesn't make sense to have `oidc` in the name as the Resource Server does not participate in the Authentication flows - it only enforces Authorization of incoming requests.

Does this make sense? Are there any other questions or thoughts?
