### ISSUE TITLE
Align max HTTP header size configuration across all supported containers

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13831]
Max HTTP header size is currently configured using `server.max-http-header-size`. It is an `int` in `ServerProperties` with a default value of 0. The actual default value for Tomcat and Jetty is 8KB and for Undertow is 1MB. The property doesn't seem to have any effect on Netty. These different defaults make it impossible for a property that's shared across containers to have an accurate default in the metadata. An added complication is that Jetty allows different max headers sizes for requests and responses.

A couple of options:

- Pick a default in Boot and use this across all the containers.
- Make the property container specific so that it can accurately reflect the container's default and so that we can offer separate properties for requests and responses with Jetty if we wish.

**Comment by snicoll** [comment]
Closing in favour of PR #13831
