### ISSUE TITLE
class 'TaskLock' cannot be injected

### ISSUE THREAD

**Issue by InternetPseudonym** [spring-projects/spring-boot#13867]
**description** : Spring boot refuses to inject Spring beans via `org.springframework.beans.factory.annotation.Autowired` which are annotated with `org.springframework.stereotype.Service` and are named "TaskLock".

**how to reproduce** : use Spring Boot and create a class with that name, try to inject it and start the app.

**environment** : 

- Spring boot 2.0.1.RELEASE
- Spring cloud Finchley.M9
- spring-boot-starter-data-jpa
- spring-boot-starter-web
- spring-cloud-starter-netflix-eureka-client
- spring-cloud-starter-sleuth
- spring-boot-starter-test
- several irrelevant dependencies

built via spring-boot-maven-plugin

This really smells like some weird, string-based classloading problem, i think someone should investigate it and probably search for similar problems

![image](https://user-images.githubusercontent.com/4394783/43076055-3a3cfba0-8e83-11e8-8632-9815954f346b.png)

Btw : changing the aforementioned classname to something else makes the problem go away, spring is happy to inject again.

**Comment by snicoll** [comment]
@InternetPseudonym there is nothing wrong naming your class `TaskLock`. However, you may have some auto-configuration that creates a bean of that type. Spring Boot doesn't. 

My best guess is that one of your dependencies does that and you are creating a bean with the same name (you can try by changing back to that name with `@Service("myTaskLock")` and the problem will most probably go away.

See #13609
