### ISSUE TITLE
Support authenticationMethod property for oauth2-client ClientRegistration

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#13860]
A new property has been added to `ClientRegistration.ProviderDetails.UserInfoEndpoint.authenticationMethod`, which is the authentication method used when requesting the `UserInfo` resource. The valid values are `header`, `form`, and `query` - see `AuthenticationMethod`.

The recommended Boot property -> `spring.security.oauth2.client.provider.[providerId].user-info-authentication-method`

**Comment by mbhave** [comment]
Closing in favor of PR #13865.
