### ISSUE TITLE
Write operation for actuator endpoint is not working with bean classes

### ISSUE THREAD

**Issue by DanielLupu** [spring-projects/spring-boot#13866]
Spring Boot version: 2.0.3.RELEASE

The Spring Boot example for using `@WriteOperation` can be found at ["Endpoint infrastructure" section](https://spring.io/blog/2017/08/22/introducing-actuator-endpoints-in-spring-boot-2-0)
This example is working OK because JSON body is passed as a parameter with string value: `{ "configuredLevel": "WARN" }` and LogLevel is an enum.

Unfortunately, if you will try to pass a bean class included in body for a HTTP POST request then it will fail with 400 - bad request. You can take a look at this example which is not working:
http://www.baeldung.com/spring-boot-actuators, 4.7. "Creating a Custom Endpoint" section

Using curl command: 
```
$ curl -X POST http://localhost:8080/actuator/features/payment -H "Content-Type: application/json" -d '{"enabled":  true}'
response: 
{"timestamp":"2018-07-23T09:57:57.922+0000","status":400,"error":"Bad Request","message":"Missing parameters: feature","path":"/actuator/features/payment"}
```

It indicates a missing feature parameter. Even though this feature parameter is added: 
```
$ curl -X POST http://localhost:8080/actuator/features/payment -H "Content-Type: application/json" -d '{"feature": {"enabled":true}}'
response:
"Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of java.lang.String out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException"
Feature bean class is not interpreted because Jackson is expecting a string instead of a bean class.
```

After debugging Jackson and Spring sources I found that the problem appears at startup, because `RequestMappingHandlerMapping.isHandler()` knows to create handler for identifying bean classes from endpoint methods only for `Controller` and `RequestMapping`.  According to [50.8 "Implementing Custom Endpoints" section](https://docs.spring.io/spring-boot/docs/2.0.2.RELEASE/reference/htmlsingle/#production-ready-endpoints) Endpoint and WebEndpoint are exposed over HTTP.
Therefore, both classes should be added in `isHandler()` method to create a handler for parsing bean classes.

**Comment by DanielLupu** [comment]
There are no accidental Controller or RestController annotations. RequestMappingHandlerMapping is not an abstract class, so in our case it is instantiated without a need of ControllerEndpointHandlerMapping

Below you can find the stack trace: 
![custom-endpoint-start-stacktrace](https://user-images.githubusercontent.com/3379077/43076609-67b8a552-8e8d-11e8-87b8-115b7584a8d6.png)

**Comment by snicoll** [comment]
@DanielLupu thank you but that's not what we had in mind. Please share a sample that we can clone/download and run ourselves.

**Comment by DanielLupu** [comment]
Here are the steps to create a sample for this issue:
1. From spring initialiser add web and actuator, see screen shot:
![spring-boot-custom-endpoint](https://user-images.githubusercontent.com/3379077/43076752-e22e1286-8e8d-11e8-8d17-5a625bdb5488.png)
2. From http://www.baeldung.com/spring-boot-actuators, 4.7. Creating a Custom Endpoint copy into your project FeatureEndpoint class (make sure you have setter/getter for "enabled" boolean variable of inner class Feature)
3. In application.properties add: 
management.endpoints.web.exposure.include=info, health, features

**Comment by DanielLupu** [comment]
Or simple just use the attached sources:
[spring-boot-custom-endpoint.zip](https://github.com/spring-projects/spring-boot/files/2219276/spring-boot-custom-endpoint.zip)

**Comment by snicoll** [comment]
Thanks for the sample. This is working as advertized:

1. As you're working with the endpoint abstraction, we want to make sure that such endpoint can be invoked via JMX. Declaring such type will not allow that
2. It looks like you expect the JSON body to be serialized back to `Feature`. What should happen if you add a third parameter?

If you want to end up with such higher-level method signature, I am not sure `@Endpoint` is the right fit for you (considering the JMX use case).

**Comment by philwebb** [comment]
If you only want to support Spring MVC you might want to look at the `@ControllerEndpoint` annotation which will allow you to develop using standard MVC annotations at the expense of portability.

**Comment by DanielLupu** [comment]
You can add as many parameters as you want if these are strings. 
Could you point me into documentation where it says all these behaviours?
In my opinion the documentation should be updated with clear explanations about the input parameters and Endpoint interface constraints.

**Comment by snicoll** [comment]
> You can add as many parameters as you want if these are strings.

I wasn't really asking a question and that's certainly not something we'd consider (for a start, there are other types to consider). 

The [documentation is here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints-custom-input). I agree we could use an example (and some cautious note about what it means to expose an operation in a technology agnostic way. Perhaps you'd be willing to contribute a PR to improve the documentation?

**Comment by DanielLupu** [comment]
I would like to contribute to Spring documentation if time allows.
For the moment I found the followings: 
1. Endpoint annotation and the other endpoints which are annotated with Endpoint must also be annotated with @Component in order to expose it in actuator
Below example should be updated:
https://spring.io/blog/2017/08/22/introducing-actuator-endpoints-in-spring-boot-2-0
2. There is no annotation for WebEndpointExtension, therefore 
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints-custom-input
50.8.2 Custom Web Endpoints
"Operations on an @Endpoint, @WebEndpoint, or @WebEndpointExtension are automatically exposed over HTTP using Jersey, Spring MVC, or Spring WebFlux"
should be updated, most probably with EndpointWebExtension
3. Definitely a naming convention issue: ServletEndpoint and EndpointServlet
50.8.3 Servlet endpoints
"A Servlet can be exposed as an endpoint by implementing a class annotated with @ServletEndpoint that also implements Supplier<EndpointServlet>."
4. The 50.8.3 Servlet endpoints & 50.8.4 Controller endpoints sections are ending with: ".. but at the expense of portability. The @Endpoint and @WebEndpoint annotations should be preferred whenever possible." 
I suppose it is related to JMX in terms of portability (correct me if you thought to something else for portability) because I find only this advantage for @Endpoint and @WebEndpoint. In my opinion these are not even HTTP endpoints since we cannot take advantage of REST and SOAP, because of the limited JMX convention for handling input parameters. So rather these are limited endpoints and are not exposing what should do a java servlet: "A Java servlet is a Java software component that extends the capabilities of a server. Although servlets can respond to any types of requests"

I understand that you cannot take this into consideration for now but maybe at next Spring Boot version you will think to do improvements in a way to reuse existing controller annotations (I can help you with this) when it comes to add features. Only for actuator and JMX support have been added most than 5 annotations which could have been implemented in a simply manner to enable the necessary support only from application properties (or eventually adding an annotation on the methods from RestController or Controller). If this will be resolved then adding custom endpoints will be performed in a natural way with a direct advantage for monitoring API endpoints. 

I don't want to let you without an explanation for: 
> It looks like you expect the JSON body to be serialized back to Feature. What should happen if you add a third parameter?
Initially I tried to use @RequestBody it in conjunction with actuate operators but it failed. I didn't expected to have 2 separate approaches for handling endpoints. 

I was able to test RestControllerEndpoint and ControllerEndpoint but no chance for ServletEndpoint. 
It is registered like this at spring-boot startup: "Registered '/actuator/servlet-features' to servlet-features-actuator-endpoint" but no HTTP available method to call like for RestControllerEndpoint: "Mapped "{[/actuator/rest-features/{id}],methods=[GET]}" onto public org.springframework.http.ResponseEntity com.example.web.simpleweb.actuator.FeatureRestControllerEndpoint.getPayment(java.lang.String)"
How should I call it from client side?

**Comment by snicoll** [comment]
> I would like to contribute to Spring documentation if time allows.
> For the moment I found the followings:

Thank you for the feedback but we don't use the issue tracker as a "support forum". We prefer issues to be focused on one topic only. This one is about the fact you can't inject a POJO from json data. As I've indicated I am happy to review a PR or other issues if necessary.

For the record, I disagree that  that blog post excerpt should add a `@Component` (please review [the configuration section](https://spring.io/blog/2017/08/22/introducing-actuator-endpoints-in-spring-boot-2-0#configuration)). I've also fixed the typo raised in 2, thanks.

**Comment by philwebb** [comment]
I've raised #13894 for number 3 on the list. Thanks!

**Comment by philwebb** [comment]
> I suppose it is related to JMX in terms of portability (correct me if you thought to something else for portability) 

In terms of portability we _currently_ mean JMX and HTTP, but there could always be more technologies we could support in the future. HTTP is not limited to just servlets, we also support WebFlux (which doesn't use the servlet API).

> maybe at next Spring Boot version you will think to do improvements in a way to reuse existing controller annotations

We've intentionally created a higher level abstraction for actuator endpoints. Trying to fudge MVC annotations to do something different really doesn't work very well.  We also need to consider the fact that we don't want actuator endpoints to be found and exposed as regular Spring MVC controllers (that's why we intentionally didn't use `@RestController` or `@Controller`. In short, we're unlikely to change our current approach anytime soon.

**Comment by philwebb** [comment]
I've opened #13896 to see if we can improve the docs about the types of parameters that are supported.

**Comment by snicoll** [comment]
I do know this. A blog is a living thing, I am not sure we should always go back and change content (the Actuator has significantly changed since this article was written). Hopefully [What's next?](https://spring.io/blog/2017/08/22/introducing-actuator-endpoints-in-spring-boot-2-0#what-s-next) should give you a hint at all that. Please refer to the documentation and we're happy to review a PR if something in the blog post is explained and missing in the doc.

> which in my opinion can be also simplified in future.

I can relate to that but given you enable an endpoint when a certain condition is met, it doesn't make a lot of sense to scan it IMO. Again, that's what the configuration section tried to showcase.

> I understand the limitation for write operation, so this issue can be closed.

For the record, I don't believe this to be a limitation but a conscious choice to allow other clients to invoke the operation (as described in the context of this issue).

**Comment by DanielLupu** [comment]
> We've intentionally created a higher level abstraction for actuator endpoints. Trying to fudge MVC annotations to do something different really doesn't work very well. We also need to consider the fact that we don't want actuator endpoints to be found and exposed as regular Spring MVC controllers 
> 
Agree with you to not alter implementation for MVC annotations to do something different, but I had thought to something else, to use AOP only for those we need to expose on actuator path, not for all. But the most important problem for Endpoint annotation is the missing extensibility for request params as long as it is strictly related to JMX pattern, to handle only a list strings. If it will be changed to handle all types of requests then you will end-up with 2 set of implementations for controller. 
But this is a design problem and should not be debated here. If you have a forum where we can discuss then let me know.
