### ISSUE TITLE
Cache metrics are not exported for supported caches wrapped in TransactionAwareCacheDecorator

### ISSUE THREAD

**Issue by jamorin** [spring-projects/spring-boot#13861]
Bug report (maybe feature request?)
Version: 2.0.3.RELEASE

It looks like there was a related issue in the past for 1.x, however things have changed with 2.x and micrometer. See #8984

metrics are reported to actuator for caffeine caches like:

```java
 CaffeineCache cache = new CaffeineCache("myCache", Caffeine.newBuilder().recordStats().build());
// Register cache to a CacheManager....
```

however, when wrapped with TransactionAwareCacheDecorator, metrics are not reported:

```java
 CaffeineCache delegate = new CaffeineCache("myCache", Caffeine.newBuilder().recordStats().build());
 // wrap in transaction aware decorator
Cache cache = new TransactionAwareCacheDecorator(delegate);
// Register cache to a CacheManager....
  }
```

Seems like the type must be a CaffeineCache to register metrics. I'm not sure if this is applicable to other caches

**Comment by snicoll** [comment]
That's a regression indeed, thanks for the report.
