### ISSUE TITLE
Add ConditionalOnBean change to Migration Guide

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#13877]
When I was looking into https://github.com/micrometer-metrics/micrometer/issues/753, I noticed that the `@ConditionalOnBean` change from https://github.com/spring-projects/spring-boot/commit/457d0414ea419dbe9044343d9aa69009743a0548 is missing in Migration Guide. It would be good to add it.

**Comment by snicoll** [comment]
Good catch @izeye, the migration guide has been updated.
