### ISSUE TITLE
Revisit usage of `ObjectProvider`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13876]
There are several interesting refinements in 5.1 in that area:

* `ObjectProvider<X>` can also be used for collections (allowing you to stream the collection). That behaviour is also completely lazy. `ObjectProvider<List<X>>`can be replaced by `ObjectProvider<X>`. 
* It is no longer necessary to guard `List` and `Map` injections in case the target bean is optional. Lists are always handled by the several points (unless the lazy part isn't important). There are no replacement for maps and it's adviser to inject the map directly (and check if it's empty if necessary).

**Comment by philwebb** [comment]
We think we've handled most of these as of 2.2.x. If we find any others we'll do them as polish commits.
