### ISSUE TITLE
Unnessary database connections when starting up JPA/Hibernate

### ISSUE THREAD

**Issue by remmeier** [spring-projects/spring-boot#13893]
Spring Boot by default is rather slow when it comes to setting up a Hibernate. There are a number of issues like determining the database type or reading all the JDBC meta data. Most can be configured to be ignored.  For example in `DataSourceInitializedPublisher.isInitializingDatabase` we have:

```
	private boolean isInitializingDatabase(DataSource dataSource) {
		if (this.properties == null) {
			return true; // better safe than sorry
		}
		String defaultDdlAuto = (EmbeddedDatabaseConnection.isEmbedded(dataSource)
				? "create-drop" : "none");
		Map<String, Object> hibernate = this.properties
				.getHibernateProperties(new HibernateSettings().ddlAuto(defaultDdlAuto));
		if (hibernate.containsKey("hibernate.hbm2ddl.auto")) {
			return true;
		}
		return false;
	}
```

which establishes a connection just to attempt to find whether it is an embeddable database to determine a default value. It should not do then when hibernate.hbm2ddl.auto was disabled. 

Maybe it would be beneficial to avoid any database connections on startup in general.

**Comment by snicoll** [comment]
@remmeier there is a `spring.datasource.initialize` that you can set to `never`. Those checks are there to offer a feature and you are free to opt-out of it. As for the code you referenced, that is already fixed (see #12374).

It should be noted that Hibernate itself will initiate a connection to the database as part of its startup phase.

**Comment by philwebb** [comment]
We've also investigated deferring some database initialization to a background thread in the past, but unfortunately it didn't really work that well. It would be nice to have another look at that, but currently our focus is on more of the general purpose optimizations that will benefit all apps.

**Comment by philwebb** [comment]
See also #13833
