### ISSUE TITLE
I configured a new Connector to implement APR+Http2+SSL, but the local so is reporting an error

### ISSUE THREAD

**Issue by xinwu-yang** [spring-projects/spring-boot#13907]
Env:
```
JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
SpringBoot version 2.0.3.RELEASE
Tomcat version 9.0.10
Tomcat Native library 1.2.17
APR version 1.6.3
OpenSSL 1.0.2o  27 Mar 2018
```

Deployed in docker image(store/oracle/serverjre:8)
```
Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
Code:
![image](https://user-images.githubusercontent.com/12267648/43235919-d3596bd8-90b4-11e8-9dfa-e397eb8295d3.png)

Errors:
![image](https://user-images.githubusercontent.com/12267648/43236046-a0443646-90b5-11e8-8f84-3030fbd24f12.png)

hs_err_pid.log:
![image](https://user-images.githubusercontent.com/12267648/43235971-36ddcf00-90b5-11e8-9ae9-d1890963b4a1.png)
![image](https://user-images.githubusercontent.com/12267648/43235977-3cfccb20-90b5-11e8-8495-c530fd094238.png)

**Comment by bclozel** [comment]
Did you try [following the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-configure-http2-tomcat) instead of configuring your own connector?

It seems they've "fixed it" using a property, even though the JVM shoudn't crash in this case.
As you've pointed out, this is more likely a tc-native issue rather than a Spring Boot issue, so I'll close this issue right now.

Did you create a Tomcat issue for that?
Please keep us updated here. Thanks!

**Comment by xinwu-yang** [comment]
@bclozel Thanks! I fix it! 
Need to configure AprLifecycleListener.
Default SSLEngine off

```
private Connector createSslConnector() {
        Connector connector = new Connector("org.apache.coyote.http11.Http11AprProtocol");
        Http11AprProtocol protocol = (Http11AprProtocol) connector.getProtocolHandler();
        connector.setScheme("https");
        connector.setSecure(true);
        connector.setPort(443);
        connector.addUpgradeProtocol(new Http2Protocol());
        protocol.setSSLEnabled(true);
        protocol.setSSLCertificateFile("/certs/tomcat.crt");
        protocol.setSSLCertificateKeyFile("/certs/tomcat.key");
        //add AprLifecycleListener config
        connector.addLifecycleListener(new AprLifecycleListener());
        return connector;
    }
```
