### ISSUE TITLE
PropertiesLauncher does not add default classpath entries when loader path has been set

### ISSUE THREAD

**Issue by paulspeijers** [spring-projects/spring-boot#13909]
I have 2 microservices that need to share a common resource bundle. Because the bundle is environment specific I would like to leave it outside the jar file. The solution I am trying to implement is to add it within the /config directory of my Docker containers, and add the /config directory as an additional classpath entry using PropertiesLauncher in combination with loader.path.

However it seems that whenever I set the loader.path the application.yml file is not loaded properly anymore from the default classpath entries (such as BOOT-INF and classes,BOOT-INF/lib).

I notice this because I'm getting various exceptions that state properties from my application.yml file could not be found such as:

> Could not resolve placeholder 

My Docker container looks as follows:
```
FROM openjdk:8-jre-alpine
VOLUME ["/tmp", "/config"]
ARG JAR_FILE
COPY ${JAR_FILE} app.jar

ENV LOADER_PATH=/config
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dloader.debug=true","-jar","/app.jar"]
```

And I create the Docker container with the spring-boot-maven-plugin as follows:
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <layout>ZIP</layout>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
I noticed that it does work whenever I add the default classpath entries to the loader path:
`ENV LOADER_PATH=/config,BOOT-INF/classes,BOOT-INF/lib`

However, this is not a desirable solution since I then have to manually define Spring boot defaults, including their order, that might change in the future. Moreover, this is not in line with the Javadoc on PropertiesLauncher.PATH that states the following:

> BOOT-INF/classes,BOOT-INF/lib} in the application archive are always used

What makes it harder that debugging the PropertiesLauncher is impossible. Especially since it does not log debug statements, because the following method on line 615 always evaluates to false because the variable DEBUG (value = "loader.debug") never equals "true".
```
private void debug(String message) {
	if (Boolean.getBoolean(DEBUG)) {
		System.out.println(message);
	}
}
```

Moreover, it has not been documented how to enable debugging. I tried the following within my Docker file:
`ENV LOAD_DEBUG=true`
and
`ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dloader.debug=true","-jar","/app.jar"]`

Should these both work?

I would expect loader.debug to be mentioned somewhere within the following page, but it isn't:
https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html

Spring boot version: 2.0.3.RELEASE

To recapitalize this actually concerns 3 issues:
1. Setting loader path seems to override default classpath entries.
2. Debug logging does not work.
3. Activating debug logging has not been documented.

**Comment by paulspeijers** [comment]
I found a workaround for this issue. Initially I set the loader.path to /config that caused the default application.yml file to not being loaded anymore. 

I have a setup in which I have an application.yml file within BOOT-INF/classes, and another one within /config with environment specific values. Somehow setting the loader.path to this /config directory seemed to mess up the loading of application.yml within BOOT-INF/classes.

I know moved the shared configuration to /config/shared/ and left the environment specific application.yml file within /config and now it seems to work.

The debug logging related issues are still there.

**Comment by philwebb** [comment]
A few tips for debugging:

1) The undocumented debug logging is only enabled when the `loader.debug` system property is set. Unlike the other properties, this one needs to be a system property and it needs to exactly match the case. Try starting your app with `java -Dloader.debug=true ...`

2) You can use remote debugging if you want to actually step into the code. We used this technique quite a bit when initially developing the fat jar support. Use `java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y ...` when you start your app and it will wait for the remote debugger to attach to port 8000 before continuing.

**Comment by philwebb** [comment]
@paulspeijers Are you able to share a cut-down version of your project that we can run to see why the `BOOT-INF/...` folders aren't being picked up?

**Comment by paulspeijers** [comment]
Hi @philwebb Thanks for your debugging tips. However, I think logging will never be performed because the following will aways evaluate to false at L615:
if (Boolean.getBoolean(DEBUG)) {

Regarding the cut-down version, I could strip it but then it will be severely stripped. Which parts are you interested in?

**Comment by philwebb** [comment]
The `Boolean.getBoolean(..)` call is a bit funky. We're effectively calling `Boolean.getBoolean("loader.debug")` which should check if a system property named `loader.debug` is set to "true". From the javadoc:

> Returns `true` if and only if the system property named by the argument exists and is equal to the string `"true"`

...

> Regarding the cut-down version, I could strip it but then it will be severely stripped. Which parts are you interested in?

For a sample, we'd ideally like the smallest possible thing that reproduces the issue.

**Comment by paulspeijers** [comment]
Sorry for my late reply @philwebb. I had to take some time to strip the application. I just did, and now ... it works :-S. So I guess the problem was related to something else. Thanks again for your support!

**Comment by snicoll** [comment]
Thanks for the feedback @paulspeijers
