### ISSUE TITLE
Remove redundancy from actuator documentation

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#13905]
Some sections of the actuator documentation seem repetitive. [This](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints-custom-mapping) can be combined with [this section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-management-server-context-path). Also, [this](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-monitoring) seems redundant as HTTP endpoints have been covered in a previous section.

**Comment by mbhave** [comment]
Also the [disabling HTTP endpoints](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-disabling-http-endpoints) should include the `management.endpoints.web.exposure.exclude` property.

**Comment by kuldeepsidhu88** [comment]
@mbhave I will be happy to work on this, I may need your help along the way as this would be my first contribution.

**Comment by mbhave** [comment]
@kuldeepsidhu88 sure, feel free to ask any questions you have. The guidelines for contributing are [here](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)

**Comment by philwebb** [comment]
Closing in favor of PR #14206
