### ISSUE TITLE
JUnit 5 platform missing in maven dependency management

### ISSUE THREAD

**Issue by ankurbhakta** [spring-projects/spring-boot#13918]
Spring boot 2.0.3 has defined <junit-platform.version>1.1.0</junit-platform.version> in spring-boot-dependencies property section  but is missing the below in  depdendencyManagement section.

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit-platform.version}</version>
        </dependency>

**Comment by snicoll** [comment]
The documentation for this dependency states

> Public API for configuring and launching test plans — typically used by IDEs and build tools.

Why do you need to use that as part of an application?

**Comment by snicoll** [comment]
Regardless of the answer, we've migrated to `junit-bom` on `master` which  brings full dependency management by relying on the bom.

Duplicate of #13118
