### ISSUE TITLE
Spring-Boot 2.0.3, Spring-Kafka 2.1.7, Spring-Mongodb 2.0.3:  "kafka_consumer" message header cannot be written to mongo

### ISSUE THREAD

**Issue by LawrenceMouarkach** [spring-projects/spring-boot#13914]
**Given:**
I am running a spring integration java dsl service with kafkaMessageDrivenAdapter.
**When:**
A message comes in from kafka with the "kafka_consumer"(Default header)
**And:**
The service writes the entire message with the "kafka_consumer" header to mongo
**Then:**
(Expected) The message appears in mongo.
(Actual) **Ambiguous field mapping detected! Both _ConsumerCoordinator_ and _AbstractCoordinator_ map to the same field name _log_! Disambiguate using @Field annotation!** <--- Class: **BasicMongoPersistentEntity** Line:**303**

This issue is across multiple spring-projects and potentially might also require a change in the actual apache-kafka code.

**Comment by philwebb** [comment]
There's not enough information here to know if this is a bug or a programming error. Either way, it's unlikely to be an issue in Spring Boot. Your best bet is to raise an issue at https://github.com/spring-projects/spring-kafka/issues, but please take the time to provide a much more detailed report. Ideally you should provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) that the Spring Kafka team can run themselves.
