### ISSUE TITLE
Add reactive health indicator for Couchbase 

### ISSUE THREAD

**Issue by ayudovin** [spring-projects/spring-boot#13925]

**Comment by snicoll** [comment]
Given the time between this issue got created and the PR, I can only assume this was a joint effort of some sort. @ayudovin we don't need an issue and a PR (as one duplicates the other). I'll close this one for now.

**Comment by ayudovin** [comment]
@snicoll Hi, you are right it was a join effort. It was my idea to add such enhancement but implementation was created by @schCRABicus. Frankly speaking we just don't know how to organize this enhancement. 
@snicoll,Sorry for the inconvenience
