### ISSUE TITLE
Migration guide refers to wrong starter reference

### ISSUE THREAD

**Issue by markthegrea** [spring-projects/spring-boot#13928]
Trying to upgrade to Spring Boot 2.

1.  The documentation for REDIS on this page:  
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide)

Says to use:  spring-boot-starter-redis
But this is correct:  spring-boot-starter-data-redis

2.  When I use the correct one above and try to start my app, I get:  

Exception in thread "main" java.lang.IllegalStateException: Failed to read Class-Path attribute from manifest of jar file:/C:/Users/jucheme/.m2/repository/io/netty/netty-handler/4.1.25.Final/netty-handler-4.1.25.Final.jar

[pom.txt](https://github.com/spring-projects/spring-boot/files/2236297/pom.txt)

**Comment by snicoll** [comment]
Thanks, I've fixed the typo. As for the exception, yes a jar should have been corrupted in your local repository. Try to download it again.

If that doesn't help, please create an issue with a sample we can clone and run (as a pom.txt file won't help us track the problem).
