### ISSUE TITLE
Spring ErrorWrapperResponse sendErrorIfNecessary in getWriter cause committed response error in standalone container (Tomcat 8.5.x)

### ISSUE THREAD

**Issue by kitsingchan** [spring-projects/spring-boot#13951]
When accessing a missing page in webapp deployed in standalone container (Tomcat 8.5.x), after the calling of `ErrorPageFilter.doFilter` which passes the `ErrorWrapperResponse` and in the `ApplicationDispatcher` which calls the `response.getWriter` trigger from `doForward`, the `response.getWriter` will trigger `ErrorWrapperResponse.getWriter` which calls the `sendErrorIfNecessary` that triggers the container `sendError` and committed the response which will cause the  `handleErrorStatus` in `ErrorPageFilter` to fail when check 
response is committed or not and prompt the error "Cannot forward to error page for request XXX as the response has already been committed. ...".

In the old version of `ErrorWrapperResponse` , there is no override of the `getWriter`, which won't trigger the `sendError` that cause the committed response to happen early and can forward the error response to the custom error controller.

For now, when accessing a missing page in webapp, the tomcat generic error page will be displayed with the committed response error message instead of forwarding to the custom error controller.

Please fix the `ErrorWrapperResponse.getWriter`.

**Comment by kitsingchan** [comment]
The following is the stack trace of tracking the ErrorWrapperResponse problem:

ErrorPageFilter$ErrorWrapperResponse.sendErrorIfNecessary() line: 358	
ErrorPageFilter$ErrorWrapperResponse.getWriter() line: 373	
FirewalledResponse(ServletResponseWrapper).getWriter() line: 109	
HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper(ServletResponseWrapper).getWriter() line: 109	
HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper(OnCommittedResponseWrapper).getWriter() line: 149	
HeaderWriterFilter$HeaderWriterResponse(ServletResponseWrapper).getWriter() line: 109	
HeaderWriterFilter$HeaderWriterResponse(OnCommittedResponseWrapper).getWriter() line: 149	
ApplicationDispatcher.doForward(ServletRequest, ServletResponse) line: 420	
ApplicationDispatcher.forward(ServletRequest, ServletResponse) line: 316	
DefaultServletHttpRequestHandler.handleRequest(HttpServletRequest, HttpServletResponse) line: 122	
HttpRequestHandlerAdapter.handle(HttpServletRequest, HttpServletResponse, Object) line: 51	
DispatcherServlet.doDispatch(HttpServletRequest, HttpServletResponse) line: 967	
DispatcherServlet.doService(HttpServletRequest, HttpServletResponse) line: 901	
DispatcherServlet(FrameworkServlet).processRequest(HttpServletRequest, HttpServletResponse) line: 970	
DispatcherServlet(FrameworkServlet).doGet(HttpServletRequest, HttpServletResponse) line: 861	
DispatcherServlet(HttpServlet).service(HttpServletRequest, HttpServletResponse) line: 635	
DispatcherServlet(FrameworkServlet).service(HttpServletRequest, HttpServletResponse) line: 846	
DispatcherServlet(HttpServlet).service(ServletRequest, ServletResponse) line: 742	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 231	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
WsFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 52	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 116	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
SingleSignOutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 97	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
CasAuthenticationFilter(AbstractAuthenticationProcessingFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 200	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
OAuth2ClientContextFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 60	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 317	
FilterSecurityInterceptor.invoke(FilterInvocation) line: 127	
FilterSecurityInterceptor.doFilter(ServletRequest, ServletResponse, FilterChain) line: 91	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
ExceptionTranslationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 114	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
SessionManagementFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 137	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
AnonymousAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 111	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
SecurityContextHolderAwareRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 170	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
RequestCacheAwareFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 63	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 116	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
HeaderWriterFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 66	
HeaderWriterFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
SecurityContextPersistenceFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 105	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
WebAsyncManagerIntegrationFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 56	
WebAsyncManagerIntegrationFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 331	
FilterChainProxy.doFilterInternal(ServletRequest, ServletResponse, FilterChain) line: 214	
FilterChainProxy.doFilter(ServletRequest, ServletResponse, FilterChain) line: 177	
DelegatingFilterProxyRegistrationBean$1(DelegatingFilterProxy).invokeDelegate(Filter, ServletRequest, ServletResponse, FilterChain) line: 347	
DelegatingFilterProxyRegistrationBean$1(DelegatingFilterProxy).doFilter(ServletRequest, ServletResponse, FilterChain) line: 263	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
OrderedCharacterEncodingFilter(CharacterEncodingFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 197	
OrderedCharacterEncodingFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
ErrorPageFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 130	
...

**Comment by wilkinsona** [comment]
I'm not 100% sure that I have understood your description of the behaviour that you are seeing, but I believe the behaviour is intentional. Please see https://github.com/spring-projects/spring-boot/commit/ac88a60071a063456da9c868e7745eb6709bc1e5 and https://github.com/spring-projects/spring-boot/issues/11814.

If you believe there's a further refinement to be made, please provide a minimal sample and precise instructions of how to reproduce the behaviour you have described and a precise description of how you think it should behave and we can re-open this issue.

**Comment by kitsingchan** [comment]
@wilkinsona In [https://github.com/spring-projects/spring-boot/commit/ac88a60071a063456da9c868e7745eb6709bc1e5](url), the paragraph about 
```
Such responses will now include the correct status, but will not be
forwarded to the error controller. Such forwarding is not possible
due to the response already having been committed.
```

Does it mean that when deployed to standalone container, I can't use the `/error` mapping to render a 404 response? As there will be not forwarding to `/error`, while in embedded tomcat container, it seems the behavior about this part is different, how can do a error mapping for the 404 response if not catch by `/error`.

**Comment by wilkinsona** [comment]
It entirely depends on whether or not the wrapper has captured an error (something has called `sendError`)  at the point that the writer or output stream is accessed. If an error has been captured at that point, the error will be sent to ensure that a 200 isn't inadvertently sent to the client.

The `ErrorPageFilter` isn't used with embedded containers so there will always be some difference in behaviour, but that filter attempts to minimise those differences.

As you can see from 
https://github.com/spring-projects/spring-boot/commit/ac88a60071a063456da9c868e7745eb6709bc1e5, the only change to the filter's tests was an addition so the change should be a refinement of the filter's existing behaviour (or there's some missing test coverage). Either way, if you'd like to look at this further (and as already requested above), please provide a minimal sample and precise instructions of how to reproduce the behaviour you have described and a precise description of how you think it should behave and we can re-open this issue.

**Comment by kitsingchan** [comment]
@wilkinsona I have look through the previous issue mentioned in [https://github.com/spring-projects/spring-boot/issues/11814](url), I understand that the fix is to send the correct status code instead of 200 at that scenario, but after the fix due to the `sendError` is triggered, the tomcat 404 page is displayed and there is no way for webapp to customise the 404 page using the traditional approach (through the error controller), does it mean that I need to configure error page customisation for this scenario through other approach? (not by error controller)

**Comment by wilkinsona** [comment]
> does it mean that I need to configure error page customisation for this scenario through other approach? (not by error controller)

I can't accurately answer that question without a minimal sample and precise instructions of how to reproduce the behaviour you have described and a precise description of how you think it should behave.

If you'd like me to spend some more time trying to help you, please spend the time to provide the information that I need to be able to do so.

**Comment by kitsingchan** [comment]
@wilkinsona I will try to use [spring-boot-sample-war](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-war) to make a minimal sample, as I can't disclose much of my current webapp, as it is quite complicated with a lot of dependencies.

I will provide the instructions ASAP, thank you for the help.

**Comment by kitsingchan** [comment]
@wilkinsona I have try to simulate the case using the `spring-boot-sample-web-jsp` and finally find the configuration that would cause this problem, when customise `WebMvcConfigurerAdapter`, I have override the method `configureDefaultServletHandling` with `configurer.enable`, that would forward all unhandled request to Servlet's container's "default" servlet, so when accessing a missing page, the webapp will forward the request to servlet container default servlet which  `sendError ` to display the tomcat 404 generic page, then as the response is already processed (committed), and if the `ErrorPageFilter `is not disabled the `ErrorPageFilter `will prompt error of the response committed before forward request to `/error`.

So if we need customise error controller then we can't turn override `configureDefaultServletHandling` with `configurer.enable`. This problem will only occurred in Apache Tomcat 8.5.X, while in Apache Tomcat 8.0.X, it won't happen.

For anymore that are upgrading from Spring Boot 1.2.8 with Apache Tomcat 8.0.X to Spring Boot 1.5.x with Apache Tomcat 8.5.x, please do check your configuration for `configureDefaultServletHandling` .

**Comment by wilkinsona** [comment]
Thanks for following up with your findings. I'm sure they'll be useful to other users in the same position as you.

**Comment by kk580kk** [comment]
same problem and I didn't understand how to resolve this problem , is there someone can help me?
