### ISSUE TITLE
Properties from custom PropertySourceLoader are used in 1.5 but not in 2.0

### ISSUE THREAD

**Issue by jinhill** [spring-projects/spring-boot#13955]
The Custom PropertySourceLoader is fine when it runs in the 1.5.10.RELEASE version, but upgrade to 2.0.3.RELEASE, it is invalid.
my demo code :https://github.com/jinhill/springboot
the UTF8PropertySourceLoader.java

```java
package com.jinhill.common.spring;

import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.springframework.boot.env.PropertySourceLoader;
import org.springframework.core.env.MapPropertySource;
import org.springframework.core.env.PropertySource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.EncodedResource;
import org.springframework.core.io.support.PropertiesLoaderUtils;

//use utf-8 load properties, need set src/main/resources/META-INF/spring.factories
//org.springframework.boot.env.PropertySourceLoader=com.jinhill.spring.UTF8PropertySourceLoader
public class UTF8PropertySourceLoader implements PropertySourceLoader {

	@Override
	public String[] getFileExtensions() {
		return new String[] { "properties" };
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	private Map<String, ?> loadProperties(Resource resource) throws IOException {
		System.out.println("loadProperties"+resource.getFilename());
		EncodedResource ecResource = new EncodedResource(resource, "UTF-8");
		return (Map) PropertiesLoaderUtils.loadProperties(ecResource);
	}

	@Override
	public List<PropertySource<?>> load(String name, Resource resource)
			throws IOException {
		Map<String, ?> properties = loadProperties(resource);
		if (properties.isEmpty()) {
			return Collections.emptyList();
		}
		return Collections
				.singletonList(new MapPropertySource(name, (Map<String, Object>) properties));
		
	}
}
```
and set PropertySourceLoader in spring.factories:

```
org.springframework.boot.env.PropertySourceLoader=com.jinhill.common.spring.UTF8PropertySourceLoader
```

when i debug UTF8PropertySourceLoader.java ,it can get utf-8 charset, but it doesn't work for `@Value`.

my debug screenshot：
https://github.com/jinhill/springboot/blob/master/1.png
https://github.com/jinhill/springboot/blob/master/2.png
https://github.com/jinhill/springboot/blob/master/3.png

**Comment by wilkinsona** [comment]
Thanks for the sample. In 1.5, `PropertySourcesLoader` would [return as soon as a loader was found for a particular file](https://github.com/spring-projects/spring-boot/blob/e51c26efdcbe4cd4b0f86231d8149b9c215e3c96/spring-boot/src/main/java/org/springframework/boot/env/PropertySourcesLoader.java#L131). The [equivalent code](https://github.com/spring-projects/spring-boot/blob/2c4e451fde95fbf6146212aaa06bc70a9bf4552b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L456-L471) in 2.0 doesn't do that so the last loader wins. In the case of your example, this means that the values loaded by `UTF8PropertySourceLoader` are overwritten by those from Boot's own `PropertiesPropertySourceLoader`.

**Comment by jinhill** [comment]
@wilkinsona 
Thank you. I know how to solve it. I suggest that the priority of customization is higher than the default.
