### ISSUE TITLE
Deprecate JMS PooledConnectionFactory that are no longer supported

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13956]
In 2.1 we've decided to switch to [`pooled-jms`](https://github.com/messaginghub/pooled-jms) as the pool implementation we use is not JMS 2 compliant. 

Some properties are no longer supported with some more details [in this issue](https://github.com/messaginghub/pooled-jms/issues/12#issuecomment-409164758). 

We should deprecate those and add a note in the doc that the current pool implementation is not JMS 2 compliant.

See also #13927

**Comment by mballoni** [comment]
Hi.
Something is not exactly clear for me.
What is the difference between the CachingConnectionFactory and the new PooledConnectionFactory?
Since both are available what are the facts I should consider to choose one or another?

Thank you!

**Comment by snicoll** [comment]
@mballoni please ask questions on Stackoverflow or join us on Gitter.
