### ISSUE TITLE
After upgrading to 2.0.4, hystrix.stream does not work in Servlet environment

### ISSUE THREAD

**Issue by alexsderkach** [spring-projects/spring-boot#13964]
I am using `management.endpoints.web.base-path: ''`.
After update from 2.0.3 to 2.0.4, I see a new class [DispatcherServletPath.java](https://github.com/spring-projects/spring-boot/blob/b5b60c2053921dfd368ac8406172744c3c979a7a/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/DispatcherServletPath.java#L47) which converts '' to /.
Then, [ServletEndpointRegistrar.java](https://github.com/spring-projects/spring-boot/blob/80da9cf5ebdc256c0b743fd0c34c451a368530aa/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/ServletEndpointRegistrar.java#L63) comes into action with 
`String path = this.basePath + "/" + endpoint.getRootPath();
`

As a result, I see in logs:
`o.s.b.a.e.w.ServletEndpointRegistrar     : Registered '//hystrix.stream' to hystrix.stream-actuator-endpoint`
And `http://localhost:8081/hystrix.stream` now returns 404.

**Comment by snicoll** [comment]
Thanks for the report, you can use `management.endpoints.web.base-path=/` for the time being. We may also tighten the rule regarding the format of such properties in a future release.

**Comment by snicoll** [comment]
Actually, that comment above is wrong for the record so we really need a fix if you want to use the root.
