### ISSUE TITLE
Add the ability to specify active profiles in test annotations

### ISSUE THREAD

**Issue by Alexuy** [spring-projects/spring-boot#13960]
Hi!

It would be cool if you could set the profiles for testing right in spring-boot test annotation, like this:
```java
@SpringBootTest(profiles="test")
```
Now, i must write 2 annotations in every test (JUnit Jupiter sample):
```java
@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")
@DataJpaTest // or @SpringBootTest or @JdbcTest or etc. 
```
Why not using system property? Because if you develop with IDE, for example, IntelliJ IDEA, you can run test by one click and IDEA must know, which profile must be used for this test.

I think, most Spring Boot Tests uses custom test profile.

About this discussion: https://jira.spring.io/browse/SPR-17101

**Comment by mbhave** [comment]
@Alexuy `@SpringBootTest` has a properties attribute which can be used to set `spring.profiles.active`.

We can reopen the issue if that doesn't work for you for some reason.

**Comment by Alexuy** [comment]
@mbhave yes, SpringBootTest has it, but other annotations, like @JdbcTest, @DataJpaTest, @RestClientTest, and all other haven't it!
