### ISSUE TITLE
Multipart property cannot be parsed if it has a trailing whitespace

### ISSUE THREAD

**Issue by phloww** [spring-projects/spring-boot#13967]
After Upgrade from Boot 2.0.3 to 2.0.4. my application fails to start.
It seems to be caused by a **property value** in application.properties **with a trailing whitespace** that cannot be parsed (into a Long in that case) correctly.

application.properties:
`spring.servlet.multipart.max-file-size=100MB `

Boot 2.0.3 didnt seem to mind the trailing whitespace, 2.0.4 does.

If policy on property values changed with that release, please close this issue. But for messy ppl like me the old behaviour saved some troubleshooting :-)

**Comment by snicoll** [comment]
2.0.3 used to trime incoming values and 2.0.4 doesn't anymore. Maybe related to #13602

**Comment by snicoll** [comment]
Thanks for sharing the details I've missed. Looking at the `Duration` matcher, you'd get a proper exception that input doesn't match the pattern (which is what we'll do once #13974 is implemented. Did you have other types in mind?

**Comment by wilkinsona** [comment]
No, I don't think so. This one can probably closed as things are back to behaving the way they always have and that way will be improved by #13974.
