### ISSUE TITLE
Dependency resolution performance for large projects

### ISSUE THREAD

**Issue by moley** [spring-projects/spring-boot#13979]
We are facing a performance issue on resolving dependencies with gradle.
We have a large project which we modularize. At the end we will have about 20 modules, each of them is a multi project build with about 10-20 subprojects. We also modularized our framework, which comes along with about 30 subprojects. We are half the way and have dependency resolution times per module of 30 seconds each time. I have done different performance measurements coming to inconclusive results, but all together they are ways to slow. I have uploaded a testproject to github. Details on handling you can see in README.md.
For us this is currently a show stopper for this modularization, so it would be nice to get a solution, workaround or a tip what goes wrong in our scenario asap. If you have problems to reproduce or any further questions, please call.
I have also opened a bug in [gradle](https://github.com/gradle/gradle/issues/6171), because the basic gradle resolution is slow itself, too.
Thanks in advance

Cheers
Markus

**Comment by moley** [comment]
The bug in gradle could be worked around by never using local releases which are pushed to mavenLocal(), this improved performance of normal gradle build to 3-4 seconds, which is OK. But the second testproject with spring-dependencies plugin still needs about 43 seconds to resolve. If you only disable/enable the line     plugin 'io.spring.dependency-management'
this performance is reproducable

**Comment by wilkinsona** [comment]
Thanks, but, AFAIK, Spring Boot itself doesn't do anything that should affect dependency resolution performance. I suspect this needs to be reported against the [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin). Could you please open an issue there along with a link to the project on GitHub that demonstrates the problem?
