### ISSUE TITLE
Provide a rich type and converter to be used by properties that configure a number of bytes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13974]
We have a few places where you can use things like 1MB or 8KB and we'll parse that into the right number of bytes. We'd like to formalise this in a similar way to what we did for `Duration` so it's not just specific to one or two properties.

**Comment by snicoll** [comment]
We're considering move the data type itself in Spring Framework as it could be reused in other places, see [SPR-17154](https://jira.spring.io/browse/SPR-17154) for more details.
