### ISSUE TITLE
Date Parsing/Formatting Inconsistent

### ISSUE THREAD

**Issue by cfloersch** [spring-projects/spring-boot#13975]
I am using SpringBoot 2.0.3 with Java 8

The HttpHeaders.setDate() method uses a different format to encode the date header than the HeaderResultMatchers.dateValue() method resulting in failing test cases.

The HttpHeaders.setDate utilizes Java 8's DateTimeFormatter.RFC_1123_DATE_TIME which does NOT zero pad the day.

HeaderResultMatchers.dateValue() on the other hand uses a SimpleDateFormat that DOES zero pad the day. 

This bug can only be reproduced for dates in which the day is less than 10. Example:

Expected :Wed, 01 Aug 2018 13:29:27 GMT
Actual   :Wed, 1 Aug 2018 13:29:27 GMT

Easiest way to fix this is to use the same DateTimeFormatter.RFC_1123_DATE_TIME in the HeaderResultMatchers implementation that you use in the HttpHeaders implementation.

**Comment by snicoll** [comment]
Thanks for the report. Both classes are in Spring Framework and framework issues are handled [in a separate issue tracker](https://jira.spring.io/projects/SPR).
