### ISSUE TITLE
Update Liquibase Dependency To Resolve Performance Regression

### ISSUE THREAD

**Issue by tze** [spring-projects/spring-boot#13980]
I've read the issue guideline regarding automatic dependency updates, but in this case it does not appear to be working.

Starting with Liquibase 3.5.0 there is a 10 fold performance regression when importing SQL files, see [CORE-2745](https://liquibase.jira.com/browse/CORE-2745). This has been resolved in 3.6.0. Spring Boot 2.0.4 references Liquibase 3.5.5. Latest Liquibase version is 3.6.2. Please update the referenced version to resolve this issue.

**Comment by snicoll** [comment]
> it does not appear to be working.

We don't upgrade to major releases of a third party dependency in a maintenance release of Spring Boot. `master` (Spring Boot 2.1) uses `3.6.2` already so I don't see any problem.

You can override the Liquibase version [in your own project](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven-parent-pom).
