### ISSUE TITLE
spring-boot-loader ends up exploded in executable jar or executable war - can I avoid that ?

### ISSUE THREAD

**Issue by anthonydahanne** [spring-projects/spring-boot#13993]
Using spring-boot 2.0.2 and gradle, if I apply the spring boot plugin to my project, (and use ```bootWar```, as described in https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/), I'll obtain my application in such a war archive : 

```
myApp.war/
├── META-INF
│   └── MANIFEST.MF
├── WEB-INF
│   ├── classes
│   │   ├── ValidationMessages.properties
│   │   ├── application.properties
│   │   ├── com
│   │   │   └── company
│   │   │       └── app
│   │   │           └── server
│   │   │               ├── Application.class
etc...
│   │   ├── public
│   │   │   └── error
│   │   │       └── 404.html
│   │   └── other.properties
│   └── lib
│       ├── jackson-annotations-2.9.0.jar
│       ├── jackson-core-2.9.5.jar
│       ├── spring-aop-5.0.6.RELEASE.jar
│       ├── spring-beans-5.0.6.RELEASE.jar
│       ├── spring-boot-2.0.2.RELEASE.jar
etc...
└── org
    └── springframework
        └── boot
            └── loader
                ├── ExecutableArchiveLauncher.class
                ├── JarLauncher.class
                ├── LaunchedURLClassLoader$UseFastConnectionExceptionsEnumeration.class
                ├── LaunchedURLClassLoader.class
                ├── Launcher.class
                ├── MainMethodRunner.class
                ├── PropertiesLauncher$1.class
                ├── PropertiesLauncher$ArchiveEntryFilter.class
                ├── PropertiesLauncher$PrefixMatchingArchiveFilter.class
                ├── PropertiesLauncher.class
                ├── WarLauncher.class
                ├── archive
                │   ├── Archive$Entry.class
                │   ├── Archive$EntryFilter.class
                │   ├── Archive.class
                │   ├── ExplodedArchive$1.class
                │   ├── ExplodedArchive$FileEntry.class
                │   ├── ExplodedArchive$FileEntryIterator$EntryComparator.class
                │   ├── ExplodedArchive$FileEntryIterator.class
                │   ├── ExplodedArchive.class
                │   ├── JarFileArchive$EntryIterator.class
                │   ├── JarFileArchive$JarFileEntry.class
                │   └── JarFileArchive.class
                ├── data
                │   ├── RandomAccessData.class
                │   ├── RandomAccessDataFile$1.class
                │   ├── RandomAccessDataFile$DataInputStream.class
                │   ├── RandomAccessDataFile$FileAccess.class
                │   └── RandomAccessDataFile.class
                ├── jar
                │   ├── AsciiBytes.class
                │   ├── Bytes.class
                │   ├── CentralDirectoryEndRecord.class
                │   ├── CentralDirectoryFileHeader.class
                │   ├── CentralDirectoryParser.class
                │   ├── CentralDirectoryVisitor.class
                │   ├── FileHeader.class
                │   ├── Handler.class
                │   ├── JarEntry.class
                │   ├── JarEntryFilter.class
                │   ├── JarFile$1.class
                │   ├── JarFile$2.class
                │   ├── JarFile$JarFileType.class
                │   ├── JarFile.class
                │   ├── JarFileEntries$1.class
                │   ├── JarFileEntries$EntryIterator.class
                │   ├── JarFileEntries.class
                │   ├── JarURLConnection$1.class
                │   ├── JarURLConnection$JarEntryName.class
                │   ├── JarURLConnection.class
                │   ├── StringSequence.class
                │   └── ZipInflaterInputStream.class
                └── util
                    └── SystemPropertyUtils.class
```
Basically : 

- my classes under WEB-INF/classes,
- my dependencies under WEB-INF/lib
- and an exploded version of the ```spring-boot-loader``` library.

That basically means my application "repackages" classes from the spring framework project, and, believe it or not, some IP checking tools do not appreciate that.

Is there a way to tell the spring boot packaging mechanism to not explode ```spring-boot-loader``` in my archive, and still benefit from the ```bootWar``` or ```bootJar``` packaging ?
Thanks !

**Comment by snicoll** [comment]
> That basically means my application "repackages" classes from the spring framework project, and, believe it or not, some IP checking tools do not appreciate that.

I'd argue it's a problem of your IP checking tools more than anything else. What tool is that?

**Comment by anthonydahanne** [comment]
Hello Stéphane;
in fact it's probably both an issue with the tool and internal policies regarding its usage and alerts.
Anyway, I'm also working that possibility, to have regular spring boot apps compliant with internal policies ...
If that does not succeed, I'll probably PR spring-boot-loader to be able to use it like that : 

```
java -DarchiveToLoad=myApp-almost-regular-war-without-boot-loader.war \ 
  -cp  spring-boot-loader-2.0.2.RELEASE.jar \ 
  org.springframework.boot.loader.WarLauncher
```

For the war archive, that'd require to still have the ```Start-Class``` Manifest entry, and make sure jar entries are not inflated / compressed, still spring-boot-loader expects non inflated jar entries; but that's a matter of gradle config for the war plugin, no big deal.

You can meanwhile close the issue if you want, I'll re open if I have a PR to suggest to you; or I'll comment on it to tell you that internal policies accepted regular spring boot packaging.
Thank you

**Comment by wilkinsona** [comment]
The best way to avoid bundling Spring Boot's loader in your jar or war file is to not build a Spring Boot fat jar or war. If you have such a requirement, I would recommend that you use Maven's Shade plugin or Gradle's Shadow plugin instead.
