### ISSUE TITLE
Set system properties in groovy app script

### ISSUE THREAD

**Issue by Alvison** [spring-projects/spring-boot#13994]
Give us a chance to Set system properties in groovy app script.

like
```
@EnableDiscoveryClient
class A{
	static {
	System.properties.'spring.application.name'='service-B'
	System.properties.'server.port'=7075
	println System.properties.'server.port'
	}
}
```
(above doesn't work currently when i try to change server.port, because the compiled class loaded after  Root WebApplicationContext: initialization completed)

or introduce an annotation PreProperties 
```
@EnableDiscoveryClient
@PreProperties([
server.port=7075
spring.application.name=service-B
])
class A{
	static {
	System.properties.'spring.application.name'='service-B'
	System.properties.'server.port'=7075
	println System.properties.'server.port'
	}
}
```
by now what we can do is that provide properties at commandline args, like
``` spring run A.groovy -- --server.port=9017 ```
which is not persist in the groovy script for convenience use;

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we are not planning to make any further enhancements to the CLI at this time.
