### ISSUE TITLE
Add mock package functionality

### ISSUE THREAD

**Issue by andbul** [spring-projects/spring-boot#13995]
Like there is a parameter `@ComponentScan`, it would be useful to have something like `@MockComponentScan` for mocking all beans in package.
For example, currently, when we tests some layers, we need to do `@ComponentScan(basepackages = "...") `and then `@MockBean` for each bean in package.
That looks terrible if you have a lot of beans in package.

Currently it looks like:

```java
@SpringJUnitConfig(classes = {
        FooServiceConfigurationContext.class,
        MockRepositoryConfigurationContext.class
})
public class FooServiceTest {


    @Test
    public void fooTest() {
    	...
    }

}


@Configuration
@ComponentScan(basePackages = {
        "org.foo.repository"
})
public class MockRepositoryConfigurationContext {

    @MockBean
    Foo fooRepository;

    ...Many @MockBean here...

}
```

I think it would be better, if we could write:
```java
@Configuration
@MockComponentScan(basePackages = {
        "org.foo.repository"
})
public class MockRepositoryConfigurationContext {

}
```
Correct me, if such feature already exists.

**Comment by snicoll** [comment]
That's really hard to tell for sure considering that you haven't shared much of the use case. Spring Boot has a concept of [slice tests](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-tests). Have you look at that and confirm why that wouldn't work for you? IMO, "many mock" is a smell something else isn't right.

**Comment by andbul** [comment]
One of use cases:

Imagine 3 layer arhitecture: ControllerLayer ->  ServiceLayer -> RepositoryLayer and we want to test different classes for each layer.


For testing ControllerLayer we create abstract class which will configure our child test classes.
So we need All Controllers and All mocked Services.

```java
@SpringJUnitConfig(classes = {
        ConrollerConfigurationContext.class,
        MockServiceConfigurationContext.class
        OtherNonMockedConfigurationContext.class
        ..some other configuration...
})
public abstract class ControllerTest {

    ...some setUp methods...

}
```

```java
@Configuration
@ComponentScan(basePackages = {
        "org.foo.controller"
})
public class ConrollerConfigurationContext {

}
```
```java
@Configuration
@ComponentScan(basePackages = {
        "org.foo.service"
})
public class MockServiceConfigurationContext {
    
    @MockBean
    Foo1Service foo1Service;

    @MockBean
    Foo2Service foo2Service;

    ... And so on...

}

```

Now we create test clases:

```java
pubic class Foo1ControllerTest extends ControllerTest{
    
    @Test
    public void foo1Test(){
        ...
    }
}
```

```java
pubic class Foo2ControllerTest extends ControllerTest{
    
    @Test
    public void foo2Test(){
        ...
    }
}
```

Such Configurations may be more complicated (and it's not about a smell, it's about a real life).

So, globaly, the idea is to have feature that helps to initialize beans of some package using certain factories or postprocessors.

(If I am right), spring can specified factorie methods for each bean manualy. I think that could be usefull to make that automaticaly. Configure mockDefinition for whole package maybe.


```java
@ComponentScan(basePackages = {
        "org.foo.controller"
}, factories=MockFactory.class)

```
or 

```java
@ComponentScan(basePackages = {
        "org.foo.controller"
}, postProcessor=MockitoPostProcessor.class)

```
(I don't know what term is right here: PostProcessor or Factory)

**Comment by snicoll** [comment]
You didn't really answered my question about slicing. It would be nice if you could confirm you had a look to it and that doesn't work for you. If so, I'd like to understand why as you are suggesting a separate approach and it needs to be justified before we consider doing so.

> So we need All Controllers and All mocked Services.

Why? If you look at `@WebMvcTest` you can indeed let it create all your controllers if your surface area is small and you can afford it or you can configure it with a particular controller and test just that. IMO, that's the best combination for a test focused on a particular functionality. And for that you only need to mock (if necessary) the direct dependency of that controller.

> Such Configurations may be more complicated (and it's not about a smell, it's about a real life).

I am not sure what you mean by that.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
