### ISSUE TITLE
Spring Boot Samples individual READMEs

### ISSUE THREAD

**Issue by pjBooms** [spring-projects/spring-boot#14016]
[Spring Boot samples](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples) have a very short description for every sample. It is unclear what is expected behavior of a sample from the descriptions. In other words, if I run an example via "java -jar spring-boot-sample.jar" what I can do with the example? It would be great if you could provide a README for each example with more description.

PS:
Why do I need it? I do an out-of-box support of Spring Boot in [Excelsior JET](https://www.excelsiorjet.com/) JVM.  To test the support, I would like to compile all your examples into native executables with Excelsior JET and test that they work the same as running on HotSpot. Some examples are just HelloWorlds (so I go to http://localhost:8080 and that's it) but for some examples I do not know how to proceed except to start them and see that the output is the same. 

For example,  if I run Kafka example (with "java -jar spring-boot-sample-kafka-2.1.0.BUILD-SNAPSHOT.jar"), it first prints "Connection to node -1 could not be established. Broker may not be available." and then terminates with "Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata". I suspect that I need to do something more to really enjoy the sample.

**Comment by mbhave** [comment]
We have a few issues related to improving the samples and their documentation. See #6370 and #12723. We can use #12723 as a wider issue for improving the samples documentation.
