### ISSUE TITLE
Change default value of spring.main.allow-bean-definition-overriding to true

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#14014]
Original issue #13609

Related spring cloud change https://github.com/spring-cloud/spring-cloud-commons/commit/87bb8f1fa17f71f0bc21a7d9f5c972706fe5feb4#diff-09d0c681fbe54b8a84f6bfa2f96ed21bR146

Related spring cloud stream change https://github.com/spring-cloud/spring-cloud-stream/pull/1428

/cc @mminella @olegz

Task seams like it might have a way forward since it's beans can be governed by `@ConditionalOnMissingBean`.

It doesn't look like stream has a similar way out.

**Comment by philwebb** [comment]
I'm wondering if we can close this issue now? @spencergibb Are you aware of any downstream projects that are still broken?

**Comment by spencergibb** [comment]
Not on the spring-cloud core side.

**Comment by philwebb** [comment]
I'm going to close this one then for now. If we find other project that have problems we can reopen it.

**Comment by spencergibb** [comment]
Turns out I did not have this sorted out. We continue to need to override bean definitions (we couldn't do our work in a `BeanPostProcessor, but I broke the tests so they passed without actually testing the functionality). See https://github.com/spring-cloud/spring-cloud-commons/commit/4da0d95e11798765024cb18cbe455739748a6ccb.

I do this now:
```java
			boolean allowBeanOverriding = false;
			if (registry instanceof DefaultListableBeanFactory) {
				DefaultListableBeanFactory beanFactory = (DefaultListableBeanFactory) registry;
				allowBeanOverriding = beanFactory.isAllowBeanDefinitionOverriding();
				beanFactory.setAllowBeanDefinitionOverriding(true);
			}
```
And then later restore the original value.

**Comment by wilkinsona** [comment]
I don't think that should be necessary. It should be possible to do a containsBeanDefinition check, and if the bean is already defined, remove the definition before adding the replacement. We do that in Boot for `@MockBean`: https://github.com/spring-projects/spring-boot/blob/3e259964050f3c862b2c171b1e425dc47ec1853e/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L188-L193

Yours would be simpler as there'd be no need to copy the definition details.

**Comment by spencergibb** [comment]
Thanks for the hint. I'll try it and report back.

**Comment by spencergibb** [comment]
Seems to work fine. Thanks again @wilkinsona.
