### ISSUE TITLE
Bean Validation not working in Spring Boot

### ISSUE THREAD

**Issue by met68** [spring-projects/spring-boot#14027]
I have been trying for ages to get a very simple Spring Boot REST API to work with simple Bean validation. The details can be found [here](https://stackoverflow.com/questions/51733338/bean-validation-in-spring-boot-data-rest-not-working).

While the project I posted on Stackoverflow uses Spring Data Rest, I get exactly the same error, if I do not use Spring Data Rest, but a simple REST Controller instead, which suggests that it is an issue in Spring Boot.

If the error should be on my side, I would appreciate some help with this. 

Otherwise, what is the most recent Spring Boot version where Bean validation still works? And when can we expect this to be fixed? It would seem to be a fairly grave issue to me, if it is indeed a Spring Boot bug, as I can't think of any real-world projects that would not need Bean validation.

P.S. I have also since tried adding the Spring Boot Starter Web (MVC) dependency to Maven, but again, this has changed nothing and I still get the same error.

**Comment by snicoll** [comment]
Thanks but there is no need to open a duplicate at this point as there isn't anything specific in your report that would point to a bug in Spring Boot. Please attach a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) to your SO question. If it turns out it is a bug in Spring Boot we can reopen this issue.

**Comment by met68** [comment]
I think what I posted on SO is Minimal, Complete and Verifiable. I wouldn't know how to make it more so. It is not clear from your post, whether this is indeed a bug that you guys are working on or not. If it is, then can you please let me know, what the last version of Spring Boot is, where the REST API would return the correct JSON validation result as expected or at least pick-up any custom exception handlers? Thanks.

**Comment by met68** [comment]
Ok, so I have done some more research and testing and have now got Bean validation to work in Spring Boot without Spring Data Rest. The problem was that I passed the BindingResult in the POST controller. That was apparently mistake. I now use a CustomResponseEntityExceptionHandler which I have adapted from the one found [here](http://www.springboottutorial.com/spring-boot-validation-for-rest-services) and which now looks as follows and now works as expected and intended (ApiError is just a helper POJO class):

    @ControllerAdvice
    @RestController
    public class CustomResponseEntityExceptionHandler extends ResponseEntityExceptionHandler {

        @Override
        protected ResponseEntity<Object> handleMethodArgumentNotValid(
			  MethodArgumentNotValidException exception,
			  HttpHeaders headers, 
			  HttpStatus status, 
			  WebRequest request) {
	   
            List<FieldError> errors = exception.getBindingResult().getFieldErrors();
            ApiError apiError = new ApiError(HttpStatus.BAD_REQUEST, exception.getLocalizedMessage(), errors);
		  
            return new ResponseEntity<Object>(apiError, new HttpHeaders(), apiError.getStatus());	
        }	
    }

**Comment by danilomcb** [comment]
I have the same problem @met68
