### ISSUE TITLE
@Bean in top-level class @TestConfiguration is ignored

### ISSUE THREAD

**Issue by mnovoseltsev** [spring-projects/spring-boot#14026]
I have faced an issue that @Bean that defined in the top-level class `@TestConfiguration` is never created and actually ignored. When `@TestConfiguration` is defined as inner static class, everything works as expected. Making `@Bean` as `@Primary` doesn't help.

Please, see https://github.com/mnovoseltsev/testconfiguration-bug for demo project example.

Spring Boot version is 2.0.4.RELEASE

BTW, @MockBean works correctly in both cases.

**Comment by snicoll** [comment]
> @bean that defined in the top-level class @TestConfiguration is never created and actually ignored.

Thanks for the sample but that's not what happens. The bean defined by your `@SpringBootApplication` actually overrides the one defined in `SomeTestConfiguration`. Try to remove the bean definition in your `@SpringBootApplication` and the test will pass. 

This is not related to `@TestConfiguration` but the order in which configuration classes are processed. Bean overriding that way is a bit fragile so I'd recommend you to research another way to implement the real use cases behind this simplified sample.
