### ISSUE TITLE
Spring boot training materials 

### ISSUE THREAD

**Issue by appsstuff** [spring-projects/spring-boot#14020]
Dear spring boot geeks
I want Spring Boot course training materials with labs ..
That’s is urgent fir me ..
Could you send me the materials with labs as pdf or ppt 
MuhammadYassein@gmail.com

**Comment by wilkinsona** [comment]
Sorry, but this isn't the right place to make sure a request. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

Your favourite search engine should help you to find lots of options for Spring Boot training, both online and in person.
