### ISSUE TITLE
Bug - Spring Boot Batch 2.0.4 (Spring Batch 4.0.1) Job parameter  Overwrite

### ISSUE THREAD

**Issue by jojoldu** [spring-projects/spring-boot#14036]
Hi
Update to Spring Boot 2.0 and use Spring Boot Batch.
But Sprinb Boot. I have a part that works differently than 1.5 (Spring Batch 3.0).
(Maybe the bug is right)

As far as I know, if there is a failed history in Spring Batch, when the same batch job is run
I know that you are using the job parameter of the failed job.
However, I know that if the same key and another value are passed to the Job parameter, it will be executed with the new value replaced.

But now it is not the latest version.
If there is a failure, the new value of the same key is not changed, and the job parameter of the failed job is always used.

So, if you use the latest version of Batch now, you should always delete the job meta table if there are any jobs that failed.
Otherwise, no matter how you change the Job parameter, only the old failed Job parameter will be used.

I found a problem in the Spring Batch code and sent a [PR](https://github.com/spring-projects/spring-batch/pull/625).
Spring Batch Github does not have an issue tab, so leave it here

Please share the review once you get in touch.
I have a lot of difficulties developing the service now.

**Comment by spencergibb** [comment]
Spring Batch uses http://jira.spring.io

**Comment by jojoldu** [comment]
Thanks.
