### ISSUE TITLE
starter配置顺序影响了依赖的解释

### ISSUE THREAD

**Issue by jianghuzai** [spring-projects/spring-boot#14045]
# 重现：在spring boot 1.x版本里面不会有这个问题
## spring-boot版本
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.4.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

## 选择了security和web起始依赖
这个顺序是spring-boot Initlalizer生成的
```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
                        <!--我想用log4j-->
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
```
## idea2016 解释出来的libary
启动会报日志冲突
![image](https://user-images.githubusercontent.com/16590040/43987210-ec272d88-9d4f-11e8-934b-4a5163eebd41.png)

## 解决办法
把依赖顺序换过来（获取把exclusions移到security的starter里面）
![image](https://user-images.githubusercontent.com/16590040/43987225-36f9db76-9d50-11e8-9ea6-f5f9796edf2c.png)

## 最后
我是中国人，所以我用中文

**Comment by wilkinsona** [comment]
Thanks for the report, but I don't think this has anything to do with Spring Boot itself. The resolution of dependencies declared in your pom is handled by Maven, or, as is the case here, by Maven and IntelliJ IDEA.
