### ISSUE TITLE
Reactor Netty resources created by the auto-configured WebClient may outlive the application context

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14058]
We should hopefully be able to use a `ReactorResourceFactory` bean and a custom `ReactorClientHttpConnector` to tie the lifecycle of the resources to the application context. See [SPR-16963](https://jira.spring.io/browse/SPR-16963) for some background information.

**Comment by rstoyanchev** [comment]
I've [updated the docs](https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/web/webflux-webclient.adoc#reactor-netty).

Spring WebFlux can still rely on global resources, I think. It's the idiomatic way with Reactor Netty and will work better alongside other libraries that embed Reactor Netty. Perhaps declare `ReactorResourceFactory` as  a bean with `globalResources=true` just in case. Can the application context and re-recreated in the same process? There is the devtools case based on #9146. Perhaps declaring the factory could be used to clean that up a bit.

For Spring MVC, similar reasoning. Clearly when running in a WAR with the `SpringBootServletInitializer`, the `ReactorResourceFactory` in global mode is needed.

**Comment by rstoyanchev** [comment]
A couple of data points. The CF Java client [manages its own](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java#L101-L117) resources. The RabbitMQ HTTP management client [doesn't do](https://github.com/rabbitmq/hop/blob/5b00508bdf08831403f57683f592f2ed8959833e/src/main/java/com/rabbitmq/http/client/ReactorNettyClient.java#L125-L126) anything special for resources, and hence participates in global resources by default.

I've also created a related issue https://github.com/reactor/reactor-netty/issues/416.
