### ISSUE TITLE
MebMvcTags not longer giving uri-attribute with pathinfo

### ISSUE THREAD

**Issue by bjornhilstad** [spring-projects/spring-boot#14068]
As of version 2.0.3.RELEASE org.springframework.boot.actuate.metrics.web.servlet.WebMvcTags stopped giving correct uri attribute for requests made to servlets. It is now consistently returning UNKNOWN for these requests. For instance, if a servlet is registered under /servlet and that is accessed using /servlet/test then WebMvcTags returns uri=UNKNOWN. In 2.0.2.RELEASE the same case would give uri=/test.
I think the change that cause this was https://github.com/spring-projects/spring-boot/issues/12447 and it may be that you want it this way for good reasons, but it has negative effects in my case as we no longer get the currect uri that we use in http_server_requests_* metrics

**Comment by wilkinsona** [comment]
This is indeed the intended behaviour as it's the only way to reliably protect against an explosion of metrics. If you want alternative behaviour, you should provide your own `WebMvcTagsProvider` implementation.
