### ISSUE TITLE
Enhancement - ShutdownHook Guard?

### ISSUE THREAD

**Issue by sddakoty** [spring-projects/spring-boot#14074]
`spring-boot` offers so many production-ready services to be used. But what I often miss is some kind of "Shutdown Guard" that monitors certain ongoing running tasks to finish, and delays the shutdown accordingly (no matter if it's a simple `jar` or a `war` in a `tomcat`).

Example: imagine a typical usecase where a 3rd party api is used via `RestTemplate`, and each request requires a response. Usually I introduce a service that keeps track of all requests not having received a response yet (or at least a count). If the app is shut down, the shutdown is delayed until all responses have been received and processed.

The goal is to minimize the probability of losing important responses in case of a shutdown/redeployment/reboot whatsoever. Of course this can only be stretched to a certain extend, as a 3rdparty service may take too long to respond and the shutdown cannot wait forever.

Could this be a valid enhancement for spring to provide some kind of production-ready service for this?

In general, such a service could be similar to:
```
public class ShutdownHookGuard implements ApplicationListener<ContextClosedEvent> {
	private final AtomicInteger counter = new AtomicInteger(0);

	public void increment() {	
		counter.incrementAndGet();	
	}
	
	public void decrement() {	
		counter.decrementAndGet();
	}

	/**
	 * Wait for pending response on shutdown/undeploy.
	 */
	@Override
	public void onApplicationEvent(ContextClosedEvent contextClosedEvent) {
		if (counter.get() > 0) {
			//block until finished.
			//TODO this still lacks some kind of global TIMEOUT to force shutdown if the counter did not 0 within X seconds (eg 60s)	
			while (counter.get() > 0) {
				TimeUnit.SECONDS.sleep(1);
			}
		}
	}
}

@Service
public ThirdpartyService() {
        private ShutdownHookGuard guard;

        public void send() {
              try {
                     guard.increment(); //add lock
                     Object rsp = restTemplate.postForEntity(..);
                     processResponse(rsp);
              } finally {
                     guard.decrement(); //release the lock
              }
        }
}
```

You can probably write that better, and make it more robust, as creating locks is often error-prone.
Could this be a valid enhancement?

**Comment by wilkinsona** [comment]
This is already possible using `org.springframework.context.SmartLifecycle` and its `stop(Runnable)` method in particular. When the context is being closed `stop(Runnable)` is called. You then call the `Runnable` once you're happy for close processing to continue. The container will wait for up to 30 seconds by default for all of the beans in a particular phase to have stopped. This timeout can be changed by calling `org.springframework.context.support.DefaultLifecycleProcessor.setTimeoutPerShutdownPhase(long)`. We may end up exposing a property for this as part of https://github.com/spring-projects/spring-boot/issues/4657.
