### ISSUE TITLE
DataSourceProperties should be created with conditional beans in Auto Configuration.

### ISSUE THREAD

**Issue by kingbbode** [spring-projects/spring-boot#14071]
The `DataSourceProperties` are public, and there are many customization examples in the documentation.

The example states the following:

```java
@Bean
@Primary
@ConfigurationProperties("app.datasource")
public DataSourceProperties dataSourceProperties() {
	return new DataSourceProperties();
}
```

I think it's strange about the `@Primary` setting. Without this setting, throws `NoUniqueBeanDefinitionException`.

This is because of `@EnableConfigurationProperties(DataSourceProperties.class)`.

`@EnableConfigurationProperties (DataSourceProperties.class)` is used in several places of spring boot auto-configuration.

The following code is representative.

```java
@Configuration
@ConditionalOnClass({ DataSource.class, EmbeddedDatabaseType.class })
@EnableConfigurationProperties(DataSourceProperties.class)
@Import({ DataSourcePoolMetadataProvidersConfiguration.class,
		DataSourceInitializationConfiguration.class })
public class DataSourceAutoConfiguration {
```

Why do I need to make a useless `DataSourceProperties` Bean from "spring.datasource"?

**I think, remove `EnableConfigurationProperties`, and `DataSourceProperties` should be created with conditional beans.**

```java
@Bean
@ConditionalOnMissingBean(DataSourceProperties.class)
public DataSourceProperties dataSourceProperties() {
    return new DataSourceProperties();
}
```

**In addition, all `DatasourceProperties` inserted into the Spring Boot Auto Configuration must be wrapped in an `ObjectProvider`.**

The following code is representative.

```java
DataSourceInitializerInvoker(ObjectProvider<DataSource> dataSource,
		DataSourceProperties properties, ApplicationContext applicationContext) {
	this.dataSource = dataSource;
	this.properties = properties;
	this.applicationContext = applicationContext;
}
```
Although the `DataSourceInitializerInvoker` not works with multiple data sources, throw  `NoUniqueBeanDefinitionException` Without Primary. 

I think `DataSourceProperties` should be assigned like `DataSource`.

thanks.

**Comment by wilkinsona** [comment]
Thanks for the report but it's difficult to know what to do with it as you have described a solution to a problem without telling us what the problem is.

> I think it's strange about the `@Primary` setting. Without this setting, throws `NoUniqueBeanDefinitionException`.

This example is for defining two `DataSource` beans. The need for `@Primary` is explained in the documentation:

> You must, however, mark one of the DataSource instances as `@Primary`, because various auto-configurations down the road expect to be able to get one by type.

> Why do I need to make a useless `DataSourceProperties` bean from "spring.datasource"?

Why is the bean useless? It's not clear what you are trying to do.

**Comment by wilkinsona** [comment]
There's a related problem here with how other components use `DataSourceProperties`. For example, Flyway's auto-configuration falls back to using the URL, username, or password from `DataSourceProperties` but those properties may have nothing to do with the configuration of the context's `DataSource`.

**Comment by kingbbode** [comment]
I agree that there are issues related to how other components use DataSourceProperties.

And I changed my mind and reached the following conclusion.

1. remove `EnableConfigurationProperties` from `DataSourceAutoConfiguration` and `DataSourceProperties` should be created with conditional beans.

2. Only the `DataSourceInitializerInvoker` needs to be changed.


Below are the configuration classes used in `AutoConfiguration` that use `DataSourceProperties`.

```
FlywayAutoConfiguration
DataSourceAutoConfiguration
DataSourceBeanCreationFailureAnalyzer
DataSourceConfiguration
DataSourceInitializerInvoker
DataSourceTransactionManagerAutoConfiguration
EmbeddedDataSourceConfiguration
JndiDataSourceAutoConfiguration
XADataSourceAutoConfiguration
LiquibaseAutoConfiguration
```

Except for `DataSourceInitializerInvoker`, there is a good reason to grant an independent `DataSourceProperties`. I think it's right to have a NoUniqueBeanDefinitionException when using them.

I also noticed that there is a `Condition` that they should work with except DataSourceInitializerInvoker.

`DataSourceAutoConfiguration` is the most basic and most important configuration class for using the database in Spring Boot.

Therefore, it is correct that the `DataSourceInitializerInvoker` should be changed. `DataSourceInitializerInvoker` does not need to have an independent` DataSourceProperties`.

Below is the conclusion I think.

remove EnableConfigurationProperties from `DataSourceAutoConfiguration` and create DataSourceProperties as a conditional bean.

```java
@Bean
@ConditionalOnMissingBean(DataSourceProperties.class)
public DataSourceProperties dataSourceProperties() {
    return new DataSourceProperties();
}
```

The `DataSourceProperties` in` DataSourceInitializerInvoker` are wrapped in `ObjectProvider`.

```java
DataSourceInitializerInvoker(
    ObjectProvider<DataSource> dataSource,
		ObjectProvider<DataSourceProperties> properties, 
    ApplicationContext applicationContext) {
	this.dataSource = dataSource;
	this.properties = properties;
	this.applicationContext = applicationContext;
}
```

```java
private DataSourceInitializer getDataSourceInitializer() {
	if (this.dataSourceInitializer == null) {
		DataSource ds = this.dataSource.getIfUnique();
    DataSourceProperties props = this.properties.getIfUnique();
    
		if (ds != null && props != null) {
			this.dataSourceInitializer = new DataSourceInitializer(ds, properties, this.applicationContext);
		}
	}
	return this.dataSourceInitializer;
}
```

**Comment by nosan** [comment]
@wilkinsona 
May I take this bug?
If yes, Could you please clarify what exactly should be done?

**Comment by wilkinsona** [comment]
@nosan Thanks for the offer, but we don't know yet. I'd like to address the problem described [here](https://github.com/spring-projects/spring-boot/issues/14071#issuecomment-413220454) but it's tied up in other related problems such as #9528. We're blocked here until we've figured out what to do there.

**Comment by wilkinsona** [comment]
I think this has been addressed as part of reworking DataSource initialization in Spring Boot 2.5. An app with these two beans fails with 2.4.x:

```java
@Bean
@ConfigurationProperties("custom.datasource")
public DataSourceProperties dataSourceProperties() {
	return new DataSourceProperties();
}
	
@Bean
public DataSource dataSource() {
	DataSourceProperties properties = dataSourceProperties();
	return DataSourceBuilder.create().url(properties.determineUrl()).build();
}
```

It starts successfully when using 2.5.
