### ISSUE TITLE
Default locale from spring.mvc.locale ignored in CompletableFuture

### ISSUE THREAD

**Issue by sddakoty** [spring-projects/spring-boot#14079]
I'm resolving a message bundle as follows, always relying on the requested locale. With fallback to configured `spring.mvc.locale=de` in my case.

```
@Autowired
private MessageSource bundle;

bundle.getMessage(key, null, LocalContextHolder.getLocale());

@Bean
public MessageSource bundle() {
	ResourceBundleMessageSource bundle = new ResourceBundleMessageSource();
        bundle.setBasenames(filename);
	return bundle;
}
```

In a normal servlet call, the `LocalContextHolder` always has the correct locale and everything works fine.

Problem: when accessing the `LocalContextHolder.getLocale()` inside a `CompletableFuture`, the local context is lost. Thus, it falls back to the systemwide locale, which is `en` if you're using an english machine like me. And thus taking 'en' resource bundle as default fallback if the message bundle is resolved within the completable future.

Is this a bug, or does it work as intended?

**Comment by nosan** [comment]
Hey @sddakoty,

`LocaleContextHolder.setLocale(locale)  -> (the same as setLocaleContext(LocaleContext localeContext, inheritable=false)` keeps locale in 

 ```
 private static final ThreadLocal<LocaleContext> localeContextHolder =
			new NamedThreadLocal<>("LocaleContext");

	private static final ThreadLocal<LocaleContext> inheritableLocaleContextHolder =
			new NamedInheritableThreadLocal<>("LocaleContext");
```  
depends on `inheritable` flag,  if it was `true` than context will be set to  `inheritableLocaleContextHolder` otherwise to `localeContextHolder`

Related to your issue, `FrameworkServlet`  has a field 
```
	/** Expose LocaleContext and RequestAttributes as inheritable for child threads? */
	private boolean threadContextInheritable = false;
```
and a method to init context holders such as request attributes and locale context.
```

	private void initContextHolders(HttpServletRequest request,
			@Nullable LocaleContext localeContext, @Nullable RequestAttributes requestAttributes) {
		if (localeContext != null) {
			LocaleContextHolder.setLocaleContext(localeContext, this.threadContextInheritable);
		}
		if (requestAttributes != null) {
			RequestContextHolder.setRequestAttributes(requestAttributes, this.threadContextInheritable);
		}

	}
``` 
and as you can see the default value is `false` that means the child threads will not see a `locale`.

You can try the following snippets:
  - Inheritable = true
```
LocaleContextHolder.setLocale(Locale.CHINA, true);
		System.out.println(LocaleContextHolder.getLocale());
		System.out.println(Thread.currentThread());
		CompletableFuture
				.runAsync(() -> {
					System.out.println(Thread.currentThread());
					System.out.println(LocaleContextHolder.getLocale());
				});
zh_CN
Thread[main,5,main]
Thread[ForkJoinPool.commonPool-worker-1,5,main]
zh_CN
```

 -  Inheritable = false 
```
LocaleContextHolder.setLocale(Locale.CHINA, false);
		System.out.println(LocaleContextHolder.getLocale());
		System.out.println(Thread.currentThread());
		CompletableFuture
				.runAsync(() -> {
					System.out.println(Thread.currentThread());
					System.out.println(LocaleContextHolder.getLocale());
				});
zh_CN
Thread[main,5,main]
Thread[ForkJoinPool.commonPool-worker-1,5,main]
en_EA

```

As a workaround you can try:

```
LocaleContextHolder.setLocale(Locale.CHINA, false);
		System.out.println(LocaleContextHolder.getLocale());
		System.out.println(Thread.currentThread());
		Locale locale = LocaleContextHolder.getLocale();
		CompletableFuture
				.runAsync(() -> {
					System.out.println(Thread.currentThread());
					System.out.println(locale);
				});
zh_CN
Thread[main,5,main]
Thread[ForkJoinPool.commonPool-worker-1,5,main]
zh_CN

```
, or set  `DispatcherServlet#setThreadContextInheritable(true)` .

Currently, `DispatcherServletAutoConfiguration` doesn't use this method.

**Comment by sddakoty** [comment]
Unfortunately I'm not settings the locale myself anywhere (it is implicit set by spring, eg by `Accept-Language` parameter), so I cannot force context inheritance myself.

So maybe spring could add a property to inherit the context for the `DispatcherServlet`? Though I'm not sure if this could be safely done, because there is a javadoc warning about usage in threadpools, thus it might be a bad idea to switch the context inheritance globally.

**Comment by nosan** [comment]
Yeah, you actually not :) `DispatcherServlet` does, also like a variant you can try:
```
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(DemoApplication.class);
		DispatcherServlet dispatcherServlet = context.getBean(DispatcherServlet.class);
		dispatcherServlet.setThreadContextInheritable(true);
	}

}
```
, but still, I'm not sure that you really need this and you can `getLocale()` before running `CompletableFuture`

**Comment by philwebb** [comment]
I think this is working as designed since the `CompletableFuture` is running in a new thread. As @nosan suggest, calling `LocaleContextHolder.getLocale()` in the MVC thread then using it in the `CompletableFuture` is probably the best approach.
