### ISSUE TITLE
Deprecate org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder.EntityManagerFactoryBeanCallback

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14083]
It was added in #894 but, as far as I can tell, it isn't used any more. We should deprecate it in 2.0.x and then remove it in 2.1.

**Comment by leumas95** [comment]
Hi, I was using this functionality to change the CONNECTION_PROVIDER in the jpaPropertyMap.
Is there an alternate solution now that this code has been removed?

**Comment by philwebb** [comment]
@leumas95 Does `HibernatePropertiesCustomizer` meet your needs?

**Comment by leumas95** [comment]
@philwebb yes, thank you that works perfectly.
