### ISSUE TITLE
Gradle plugin should have option to name WAR differently

### ISSUE THREAD

**Issue by msgilligan** [spring-projects/spring-boot#141]
Updating the WAR file in place seems like a bad practice from a build (DAG) perspective. It's also confusing to people who are in the process of learning Spring Boot.

Default behavior should be to preserve the WAR file generated by the WAR plugin and generate a new Spring Boot loader-enhanced WAR with a name like archiveName-boot-version.war (or something like that.)

If I can't convince you to change the default behavior, there should at least be a documented way to change the behavior so a "virgin" war and a "Spring Boot" war are produced in separate files.

**Comment by clipod** [comment]
Just curious, is there a fix where the virgin war will not have .original in the suffix?
I am using maven and would like to not see the suffix. May be *.original.war will be useful for lot of people or else people will end up writing a script to change the suffix before they deploy the war.

**Comment by dsyer** [comment]
If you set a classifier, the original war has its original name. That should suffice for anyone that needs both artifacts.
