### ISSUE TITLE
Extend RabbitProperties with SimpleMessageListenerContainer.setMissingQueuesFatal

### ISSUE THREAD

**Issue by ramato-procon** [spring-projects/spring-boot#14122]
Please add to [RabbitProperties-SimpleContainer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L623) the [SimpleMessageListenerContainer.setMissingQueuesFatal](https://docs.spring.io/spring-amqp/api/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.html#setMissingQueuesFatal-boolean-).
Especially for clustered rabbitmq configuration the default option (true) may cause the ListenerContainer to stop forever until the SpringBoot instance was restarted. E.g. exclusive (Anonymous) queues may not be recreated during a network partition.
It should also be discussed if Autoconfiguration should set the default value to "false".

**Comment by garyrussell** [comment]
>It should also be discussed if Autoconfiguration should set the default value to "false".

The default should remain `true` IMHO.

**Comment by mbhave** [comment]
Closing in favor of PR #14252.
