### ISSUE TITLE
Document that `DispatcherServletPath` is required in case of custom dispatcher servlet arrangement

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14145]
`DispatcherServletPath` is not documented in the ref guide and [this section of the ref guide](https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#howto-switch-off-the-spring-mvc-dispatcherservlet) looks outdated.

**Comment by ltorzynski** [comment]
@snicoll - what about registration of DispatcherServlet for more than one separate "paths" in Spring Boot application ? In 1.5.X it was possible simply using f.ex ServletRegistrationBean.addUrlMappings" method. Now using DispatcherServletRegistrationBean that is not possible anymore (single path parameter) How to migrate existing 1.5 Spring Boot application to 2.0.X having such requirement ?

**Comment by snicoll** [comment]
This doesn't change anything and I've already indicated you don't have to use `DispatcherServletRegistrationBean`. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. I've already suggested to join us on Gitter to discuss your use case.
