### ISSUE TITLE
Add ApplicationHome class

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1414]
The `StartupInfoLogger` class contains some generally useful logic that can be used to find the application home folder (i.e. the folder containing the jar or the root folder of an exploded archive). We're going to need this in a few other places so it could be extracted into its own class.

**Comment by persapiens** [comment]
Hi @rajjaiswalsaumya , 

You have two options to integrate one technology like JSF with Spring Boot: manually or using [Spring Boot Starters](http://stackoverflow.com/questions/28273543/what-are-spring-boot-starter-jars). 

There is no built in Spring Boot Starter to integrate JSF, but Spring Boot references [one Community Contribution](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters) called [JoinFaces](http://joinfaces.org).

You could try [JoinFaces Example](https://github.com/joinfaces/joinfaces-example) also.
