### ISSUE TITLE
Add additional guard for web application detection in AOT

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14147]
This code in `SpringApplication` blows up at runtime in a native image when `WebApplicationContext` is not on the classpath:

```java
	private boolean isWebApplicationContext(Class<?> applicationContextClass) {
		try {
			return WebApplicationContext.class.isAssignableFrom(applicationContextClass);
		}
		catch (NoClassDefFoundError ex) {
			return false;
		}
	}
```

Probably we could add an additional check that `WebApplicationContext` is present before we check for `isAssignableFrom()` it?

Adding this check worked for me:

```java
	    if (!ClassUtils.isPresent("org.springframework.web.context.WebApplicationContext", null)) {
	        return false;
	    }
```

but it didn't work to simply `catch Throwable`.

**Comment by snicoll** [comment]
That's a pattern we use in other places so if that becomes problematic, I'd prefer to understand where this is coming from.

**Comment by snicoll** [comment]
There is `OnBeanCondition` that does that or am I missing something?

**Comment by dsyer** [comment]
`OnBeanCondition` does not call `isAssignableFrom()`. Am I missing something?

**Comment by snicoll** [comment]
No but I surely was. Sorry.

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/issues/14157#issuecomment-417030452. Closing for now and awaiting the result of https://github.com/oracle/graal/issues/622
