### ISSUE TITLE
DataSourceAutoConfiguration with spring-cloud-eureka

### ISSUE THREAD

**Issue by countree** [spring-projects/spring-boot#14141]
DataSourceAutoConfiguration is configured too early before registering with eureka-server

**Comment by snicoll** [comment]
@countree thanks for the report but there's not enough information for us to do investigate (you haven't even provided the version you're using, if it's a regression on update, etc). Maybe this is related to the Eureka integration in which case this issue shouldn't be reported here in the first place.

To figure things out, please share a sample that we can run ourselves (a link to a zip or a repo). Thank you.

**Comment by countree** [comment]
got it
