### ISSUE TITLE
Reactive Resource Server Auto Configuration

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-boot#14166]
Complementary to https://github.com/spring-projects/spring-boot/issues/14150 for Servlet-based apps is the equivalent for WebFlux-based apps.

The property is the same (`spring.security.oauth2.resource-server.jwt.oidc-issuer-location`).

As is the needed configuration:

```java
http.
    oauth2().
        resourceServer().
            jwt();
```

And when WebFlux is present, as well as `ReactiveJwtAuthenticationManager`, then it is appropriate to use this property to publish a `ReactiveJwtDecoder` bean, e.g.:

```java
@Bean
ReactiveJwtDecoder jwtDecoder() {
    return ReactiveJwtDecoders.fromOidcIssuerLocation(oidcIssuerLocation)
}
```

At that point, the Spring Security WebFlux configurer will pick up the bean and compose its security components accordingly.

**Comment by jgrandja** [comment]
The updated DSL should be:

```java
http.oauth2ResourceServer().jwt();
```

See related issue [#5715](https://github.com/spring-projects/spring-security/issues/5715) and #[5712](https://github.com/spring-projects/spring-security/issues/5712)

**Comment by mbhave** [comment]
Closing in favor of PR #14199.
