### ISSUE TITLE
ON_TRACE_PARAM to include stacktrace behaves differently in Spring Boot 2

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-boot#14171]
When migrating an application from Spring Boot 1.x to Spring Boot 2.0.4 I noticed that our error page was displaying the stacktrace.

Turns out that the change in AbstractErrorController returns include stacktrace as true when the trace parameter is not set. Please see below of details.

https://github.com/spring-projects/spring-boot/commit/a93a4e8715acfd5aaa6714214878855e2c61565f#commitcomment-30251151

If this change in behavior is not intentional please consider putting the null check back in to return false when the trace parameter is not set.

**Comment by snicoll** [comment]
This looks like an oversight introduced by #11330, flagging for team attention
