### ISSUE TITLE
spring boot 1.5.1 support with hibernate 5.2.1 

### ISSUE THREAD

**Issue by DmitryevichD** [spring-projects/spring-boot#14180]
Unable to start embedded container; nested exception is
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionFactoryImplementor.getProperties()Ljava/util/Properties;`

**Comment by snicoll** [comment]
@DmitryevichD `1.5.1` is old, please upgrade to the latest bug fix in that line first. If you have more questions, please ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
