### ISSUE TITLE
In a context hierarchy with a shared classpath a parent context prevents child contexts from overriding server.* and management.* properties

### ISSUE THREAD

**Issue by janniksch** [spring-projects/spring-boot#14189]
When having a context hierarchy with a shared classpath configured via `SpringApplicationBuilder` with the parent context being of `WebApplicationType.NONE` and multiple child contexts being of `WebApplicationType.SERVLET` there are properties with prefix "server" and "management" which can't be overridden in child context's `PropertySources`.

For prefix "server" this is caused by `EmbeddedWebServerFactoryCustomizerAutoConfiguration`, which is not a conditional configuration and therefore enables configuration properties ServerProperties per default in the parent context:

```
@Configuration
@EnableConfigurationProperties(ServerProperties.class)
public class EmbeddedWebServerFactoryCustomizerAutoConfiguration { ... }
```

The ServerProperties bean is passed on to the child contexts and therefore is not loaded again with the child context's properties. It can be avoided by adding `EmbeddedWebServerFactoryCustomizerAutoConfiguration.class` to exclude field in `@EnableAutoConfiguration` in parent context, but in my opinion this auto configuration should only be applied for WebApplicationTypes SERVLET and REACTIVE. So a simple solution could be adding `@ConditionalOnWebApplication` annotation:

```
@Configuration
@ConditionalOnWebApplication
@EnableConfigurationProperties(ServerProperties.class)
public class EmbeddedWebServerFactoryCustomizerAutoConfiguration { ... }
```

Same goes for configuration class `ManagementContextAutoConfiguration`:

```
@Configuration
@AutoConfigureOrder(Ordered.LOWEST_PRECEDENCE)
@EnableConfigurationProperties({ WebEndpointProperties.class,
		ManagementServerProperties.class })
public class ManagementContextAutoConfiguration { ... }
```

It is not conditional so that properties mapped in `ManagementServerProperties `and `WebEndpointProperties `are again passed into the child contexts. The solution would also be to annotate this class with `@ConditionalOnWebApplication`.

A sample project can be found at https://github.com/janniksch/spring-boot-hierarchy.git

**Comment by philwebb** [comment]
We've not really considered such complex configurations and I expect that even if we could solve these immediate issues there will be other assumptions in the code that will cause problems. What's the reason that you need to create such a hierarchy?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
