### ISSUE TITLE
2.1.0 M2 has "cannot find symbol" when using Lombok @Builder.Default

### ISSUE THREAD

**Issue by Hana-Lee** [spring-projects/spring-boot#14193]
Spring boot 2.1.0 M2 has cannot find symbol error.
Spring boot 2.1.0 M1 was no problem.

```
[ERROR] /C:/Users/Hana/Downloads/demo/src/main/java/com/example/demo/WebixTreeNode.java:[18,1] cannot find symbol
  symbol:   method $default$open()
  location: class com.example.demo.WebixTreeNode
```

WebixTreeNode.java
```java
import java.util.ArrayList;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@EqualsAndHashCode(of = { "id", "code" })
public class WebixTreeNode {

	private Long id;
	private String code;
	private String value;

	@Builder.Default
	private boolean open = true;
	private String type;

	@Builder.Default
	private List<WebixTreeNode> data = new ArrayList<>();

	@Builder
	public WebixTreeNode(Long id, String code, String value, String type) {
		this.id = id;
		this.code = code;
		this.value = value;
		this.type = type;
	}
}
```

* OS : Windows 10
* Build: maven
* JDK : oracle jdk 10.0.2

**Comment by Hana-Lee** [comment]
Here is test code sample.
[2.1.0.M2.demo.zip](https://github.com/spring-projects/spring-boot/files/2317500/2.1.0.M2.demo.zip)

**Comment by snicoll** [comment]
@Hana-Lee I am not sure I understand why you're reporting a bug against Spring Boot for a compilation failure with Lombok. If you have a question, please ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
