### ISSUE TITLE
Devtools doesn't reload the app if the class is named 'Test'

### ISSUE THREAD

**Issue by cdxf** [spring-projects/spring-boot#14192]
This is a strange problem. I created a simple Spring Boot project, then I created a class named "Test" like this:
```
@RestController
@RequestMapping("/")
public class Test{
    @RequestMapping
    public String index(){
        return "index";
    }
}

```
The app runs fine but if I change the Test class and recompile it, devtools wont reload the app. I've tried rename the class and everything works so the problem only happens if the class is named 'Test'

- Spring version: >2.0.0 ( I've tried with 2.1.0.M2)
- IDE: Intellij (use Intellij Build process)
- OS: Windows 10

-- Updated:
I tried again using gradle continuous build and it works fine. So this problem only happens when I use the IDE build.

**Comment by snicoll** [comment]
@cdxf getting help on how to use your favorite IDE should be requested in a dedicated forum. I am closing this as there is no indication there is a bug in Spring Boot. We can reopen if necessary.
