### ISSUE TITLE
Spring boot 2.0.4  server.port bug

### ISSUE THREAD

**Issue by sundy20** [spring-projects/spring-boot#14195]
Server.port=8090 request http status 405
After replacing the port
Server.port=8081 request http status 200

**Comment by snicoll** [comment]
@sundy20 there's nowhere near enough information to figure out if there is an issue in Spring Boot or your environment. Spring Boot doesn't do anything special in this area. To know for sure, please share a sample we can run ourselves that reproduces the problem.

**Comment by sundy20** [comment]
https://github.com/sundy20/netty-push/tree/master/netty-push-client
set Server.port=8090 request http status 405
you can try

**Comment by snicoll** [comment]
@sundy20 thanks for the reference to the sample but that's not really what I have in mind. What are the instructions to reproduce the problem? If you want us to take the time to investigate, please take the time to explain how the issue can be reproduced.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sundy20** [comment]
thanks for your reply
use this project   https://github.com/sundy20/netty-push/tree/master/netty-push-client
run NettyPushClientApplication.java
application.yml  set  Server.port=8090 
request  http://localhost:8090/error   response status  405
After replacing the port
application.yml  set  Server.port=8081 
request http://localhost:8081/error   response status  200

**Comment by sundy20** [comment]
[demo.zip](https://github.com/spring-projects/spring-boot/files/2343971/demo.zip)
this spring boot 2.0.4 release demo,try again
wait for your reply,thanks

**Comment by minorpoet** [comment]
i meet 405  on port 8090 too ~~ 

@Controller
@RequestMapping("/")
public class SchedulerController {

     @RequestMapping(value = "/create", method = {RequestMethod.GET, RequestMethod.POST})
     public String create(){
         return "success";
     }
}

dependency:
buildscript {
	ext {
		springBootVersion = '2.0.4.RELEASE'
	}
	repositories {
		mavenCentral()
		maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
		maven { url 'http://repo.spring.io/plugins-release' }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}
dependencies {
	compile 'org.slf4j:slf4j-api'
	compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-validation')
	compile ('com.alibaba:fastjson:1.2.49')
    compile('org.springframework.cloud:spring-cloud-starter-sleuth')
    compileOnly('org.projectlombok:lombok')
    testCompile('org.springframework.boot:spring-boot-starter-test')
    compile('org.springframework.boot:spring-boot-starter-amqp') 
}

**Comment by snicoll** [comment]
@sundy20 you've attached an empty project with no instructions. What am I supposed to "test" with this exactly?

@minorpoet I've got 200 on that controller you've attached (both with `GET` and `POST`).  I am closing this for now as there is no indication that there is a bug in Spring Boot. If you've new evidences of the contrary we can reopen this issue.
