### ISSUE TITLE
Suspected issue with MethodInterceptor chain when using combination of proxy-dependent features

### ISSUE THREAD

**Issue by michalrames** [spring-projects/spring-boot#14208]
I am using `@EnableCaching`, `@EnableTransactionManagement`, `@EnableAspectJAutoProxy`, and `@EnableAsync` in my project, all of which depend on proxying. 

I was experiencing issues with execution pointcuts not working intermittently - described here https://stackoverflow.com/questions/51995734/spring-aop-aspect-inconsistent-behaviour-with-pointcuts-for-spring-data-reposito 

I was able to restore the working order through the steps described in my answer in SO, but I'm not 100% sure why (I wasn't able to pinpoint the root cause). I'd be grateful for any insights. 

Expected behaviour:
If there is a configuration issue, it would be useful if the framework pointed that out as a warning during startup.

Possibly related to https://jira.spring.io/browse/SPR-16532,

**Comment by snicoll** [comment]
Thanks for getting in touch but, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. I've replied to your SO thread and you can also join us on Gitter if you want to chat.
