### ISSUE TITLE
FileSystemWatcher timeout

### ISSUE THREAD

**Issue by dassader** [spring-projects/spring-boot#14209]
Could you please add possibility to set timeout for `FileSystemWatcher`?
As you can see on screenshot the watcher will be use file system in cycle, without sleep. 
In this case we have an excess load.

![image](https://user-images.githubusercontent.com/6272505/44648003-66fa8100-a9e8-11e8-9185-019ee081bfd6.png)

**Comment by philwebb** [comment]
@dassader Can you provide some more information about the excess load that you're seeing and where you want the timeout? There are some `Thread.sleep` class in the `scan()` method.

**Comment by dassader** [comment]
@philwebb Oh, I see. I am really sorry.

**Comment by philwebb** [comment]
@dassader No worries, thanks for investigating.
