### ISSUE TITLE
@Validated groups don't work with @RequestBody

### ISSUE THREAD

**Issue by Kidlike** [spring-projects/spring-boot#14207]
Inside a `@RestController`, when a `@RequestBody` object is also `@Validated` with a group, then **validation does not occur at all.**

`@Validated` without a group works as expected.

Sample code: https://github.com/spring-projects/spring-boot-issues/pull/80

**Comment by alimate** [comment]
> validation does not occur at all.

When you specify a validation group with the `Validated` annotation, then only constraints with that group would be picked up by the Bean Validation. In your case, you specified a validation group in your controller parameter:
```java
@Validated(ShouldFail.class) @RequestBody SomeDto someDto
```
But you didn't assign any validation group to `SomeDto` constraint, i.e. the`@ValidDto`. So the `ValidDto` annotation will be ignored when you're applying the `ShouldFail` group. I suppose it should work when you do the following:
```java
 @Data
 @Builder
 @ToString
 @ValidDto(groups = ShouldFail.class)
 class SomeDto {
     private String firstName;
     private String lastName;
 }
``` 

IMHO, this is the expected result and not a bug.

**Comment by snicoll** [comment]
@alimate Thanks. I've been poking at the Spring Framework issue tracker for a related issue as clearly this isn't Spring Boot related but couldn't find a reference.

**Comment by Kidlike** [comment]
Well this is not strictly `spring-boot` related, but it is spring related, since `@Validated` is coming from Spring.

Also, why exactly did you close this? Please provide some information, not just `for:stackoverflow` without reasoning.

Anyway... Back to the issue at hand.

Exactly the same behavior as described in the ticket **is** working for request params that live inside a class. i.e. if you just remove the `@RequestBody`

I will update the sample code with working examples.

**Comment by snicoll** [comment]
@Kidlike you've got an answer about your use case right above. If you have more usage questions, please ask them on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by Kidlike** [comment]
It is a bug... just wait I'm writing the working example. The use case provided is not valid, or as expected.

**Comment by Kidlike** [comment]
Thanks. I was actually trying to replicate the working example, and it doesn't. I don't know why I was under the false assumption that it's working. Cheers.
