### ISSUE TITLE
Adding @DataCassandraTest for typical Cassandra tests

### ISSUE THREAD

**Issue by ayudovin** [spring-projects/spring-boot#14214]
Create annotation `@DataCassandraTest` like `@DataMongoTest` or `@DataRedisTest`, `@DataNeo4jTest` for unit tests

**Comment by mbhave** [comment]
@ayudovin We've discussed this quite recently as a team and declined a similar issue. Perhaps, [this comment](https://github.com/spring-projects/spring-boot/pull/13033#issuecomment-400430466) can provide more background. Also, see [this](https://github.com/spring-projects/spring-boot/issues/8607#issuecomment-403414742).

**Comment by ayudovin** [comment]
ok, sorry, I don't know about those discussions.
