### ISSUE TITLE
Remove `spring.cloud.enabled` property

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14219]
`CloudAutoConfiguration` (worth renaming?) has a `spring.cloud.enabled` property that has no metadata. I don't think it was ever advertized so I'd like us to get rid of it (since `spring.cloud` is a different territory anyway).

**Comment by philwebb** [comment]
`SpringCloudServiceConnectorsAutoConfiguration` ?

**Comment by philwebb** [comment]
I think we can just drop the property and use standard auto-configure exclusions to disable it.

**Comment by snicoll** [comment]
Thanks, let's do this as this unknown property will keep popping up in report until we remove/document it.

**Comment by ankitvd6** [comment]
I am getting this error on upgrading my spring boot version from 2.0.4-RELEASE to 2.6.6
```Unable to read meta-data for class org.springframework.boot.autoconfigure.cloud.CloudAutoConfiguration```. I cannot find org.springframework.boot.autoconfigure.cloud in version 2.6.6. Can I safely exclude CloudAutoConfiguration.class from scan using @SpringBootApplication(exclude={CloudAutoConfiguration.class}) ?
@snicoll @philwebb

**Comment by bclozel** [comment]
It's been renamed to `CloudServiceConnectorsAutoConfiguration` and later completely removed in #19798. You can just delete this exclusion from your application.
