### ISSUE TITLE
Define execution id for repackage goal in spring-boot-starter-parent

### ISSUE THREAD

**Issue by ST-DDT** [spring-projects/spring-boot#14210]
To simplify overriding and extending the goals it would be nice if you could define a execution id for the repackage goal. This is helpful, if you only need the build-info and not the repackage goal.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter-parent/pom.xml#L154

**Example:**

````xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>repackage</id>
			<goals>
				<goal>repackage</goal>
			</goals>
			<configuration>
				<skip>true</skip>
			</configuration>
		</execution>
	</executions>
</plugin>
````

**Comment by snicoll** [comment]
> This is helpful, if you only need the build-info and not the repackage goal.

I am assuming you mean you could then add a config where `skip` is `true` for the `repackage` execution? If you have something else in mind, please clarify. Thank you.

**Comment by ST-DDT** [comment]
Yes.
