### ISSUE TITLE
Spring Boot Groovy & Gradle version issues

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#14225]
In Spring Cloud Contract we're creating a Gradle plugin. We're inheriting the Groovy version from Boot (2.5). 

Let's say that we have a Gradle (4.10) application that uses the Boot Gradle plugin (2.1.0.M2) and the Spring Cloud Contract Gradle Plugin (2.1.0.BUILD-SNAPSHOT). For the application code, the Groovy (2.5) version gets inherited from Boot. For the plugin classpath, the Groovy version (2.4) gets inherited from Gradle (4.10). 

Due to the fact that the SC-Contract Gradle Plugin got compiled with Groovy 2.5 we have a problem. In Groovy 2.5 they've introduced a backward incompatible change that all `collect` methods on `Collection` classes are now calling a method that gets mixed in to `Iterables`. That means that the method used is `collect(Iterable self...)` instead of `collect(Collection self...)`. At runtime of the Spring Cloud Contract plugin you start getting `MethodNotFoundError` because it's trying to call the `Iterable` version of Groovy 2.5, against the Groovy 2.4 runtime that doesn't have this method.

A workaround is to

- not to use Boot as version management for a Gradle Plugin
- when building a Gradle Plugin, that uses Boot as version management
  - hardcode the Groovy version to the latest acceptable by Gradle
  - rewrite all `collect` to `for-each` loops

Post-mortem:

- don't write plugins in Groovy, write them in Java

**Comment by wilkinsona** [comment]
Writing plugins in Java is also aligns with the Gradle team's recommendations. FWIW, I'd avoid using Groovy for writing Gradle plugins unless you are prepared to spend a lot of time dealing with hard to diagnose compatibility issues.

**Comment by wilkinsona** [comment]
> The whole core of sc-contract is written in Groovy.

😬
