### ISSUE TITLE
Throwing an exception on invalid syntax in SPRING_APPLICATION_JSON

### ISSUE THREAD

**Issue by pvorb** [spring-projects/spring-boot#14239]
As far as I can tell, Spring Boot 2 accepts syntax errors in the `SPRING_APPLICATION_JSON` environment variable and silently ignores the whole content of the environment variable. This leads to problems that are hard to debug, where properties are not overridden when running an application.

Consider the following example.

`application.yml`:

~~~ json
parentKey:
    childKey: true
~~~

`SPRING_APPLICATION_JSON`:

~~~ json
{"parentKey" {"childKey": false}}
~~~

(Note the missing colon after `"parentKey"`.)

If you now try to inject the value via `@Value` or a `@ConfigurationProperties` class, you get `true` instead of `false`.

In my opinion it would be better to throw an exception and abort application startup in this case or at least to log an error or warning.

**Comment by philwebb** [comment]
We currently [log a warning](https://github.com/spring-projects/spring-boot/blob/0590c4de3210a1cf41e63b928d46f99f6c0c5c6b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/SpringApplicationJsonEnvironmentPostProcessor.java#L109) but I'm inclined to agree that an exception would be better.

This will be a breaking change so it's not something we can do in a patch release.

**Comment by pvorb** [comment]
You are right. I missed the warning because of a misconfigured logger.

**Comment by philwebb** [comment]
Closing in favor of PR #14251
