### ISSUE TITLE
enhancement: spring-boot-starter-rollbar

### ISSUE THREAD

**Issue by pkaufi** [spring-projects/spring-boot#14248]
Hello there,
We wrote a spring-boot-starter-rollbar (and spring-boot-starter-rollbar-logback) to integrate and configure rollbar into our projects more easily.
Please have a look at the following repo: https://github.com/olmero/spring-boot-starter-rollbar

We'd happily contribute to spring-boot, if there's positive feedback about this spring boot starter. We're also more than happy to adapt the starter so it applies to the spring code conventions (we already have tests ;))

To use it, you simply need to add it to the dependencies of your project (maven or gradle) and provide the `com.rollbar.access-token` and `com.rollbar.environment`. For test or local environment, there's also a possibility to disable it with ` com.rollbar.enable=false` (default = true).

To use the logback starter, simply add it to your dependencies as well. Configuring is as easy as adding 
`com.rollbar.logging.level.root=WARN` to your application.properties file. The configuration is the same as in spring boot system logging. From here on, everything that is logged as WARN or ERROR will be forwarded to Rollbar. As the logback starter is based on the rollbar starter, you can (and should) also use the properties mentioned above.

Thank you for your time

**Comment by snicoll** [comment]
@pkaufi thanks a lot for creating the starter. I have a few suggestions that I am going to share in that project later today. I prefer keep the starter where it is now and we will add a reference to it in our [third party list](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/README.adoc) once the naming issue is fixed. 

We can always reconsider later but I think the current situation is fine.
