### ISSUE TITLE
How to update HttpServletResponse inside a Filter 

### ISSUE THREAD

**Issue by apexkid** [spring-projects/spring-boot#14256]
Sorry for asking a question here but unfortunately i couldn't get a satisfactory answer on stackoverflow. 

https://stackoverflow.com/questions/52030874/how-to-modify-httpservletresponse-to-include-some-standard-attributes-in-json-us/52040296

I want to write a filter which 
1. takes in the response returned by my controller and adds some standard metadata around it.
2. If controller throws exception, then also return some standard json output to user other than 500 error code. I know now this part can be probably done by controlleradvice and exceptionhandlers. 

For the part 1, i do not have a standard solution which feels strange. I understand one way to achieve this is to have a standard response base class and have controllers return a child class but this just feels like forcing a way out. Filters should be able to transform the response from controller I believe, I don't know how. 

Please confirm if there is no way to transform ServletResponse object.

**Comment by bclozel** [comment]
You were right to ask this question on SO. Your question has 2 answers (+3 deleted) and is marked as a potential duplicate as well.
