### ISSUE TITLE
Provide a way to inject a customize transformer for responses returned by controller

### ISSUE THREAD

**Issue by apexkid** [spring-projects/spring-boot#14257]
There should be a mechanism to inject ResponseTransformer into the spring request-response lifecycle. This would allow to change the object which is returned by a spring controller. Another way to look into this will be to enable ControllerAdvice to transform response objects.

**Comment by snicoll** [comment]
@apexkid as I've mentioned on Gitter, there is an ongoing discussion about what you're trying to do. Let's keep the conversation there and we can follow-up with an issue accordingly.
