### ISSUE TITLE
Logback config logpath Configured by environment only effective at running

### ISSUE THREAD

**Issue by JokerG** [spring-projects/spring-boot#14265]
running log output path  is corrected ,but bootstrap log output path  is default path rather than what i configed.

**Comment by snicoll** [comment]
I am guessing that by bootstrap log, you mean the Spring Cloud bootstrap log?

**Comment by JokerG** [comment]
it's my fault, i mean  Startup log ,
my project does not use bootstrap.properties ,it's only a springboot project .version 1.5.10.RELEASE

**Comment by snicoll** [comment]
@JokerG you'll have to provide a bit more details. It would be easier if you shared a project (github repo or ref to a zip) so that we can see what you mean. Since it's about logging, you could create an empty project from start.spring.io and add your logging config there.

**Comment by JokerG** [comment]
logback-spring.xml 
`<springProperty scope="context" name="log.srv.tag" source="log.srv.tag" defaultValue="TEST"/>
    <springProperty scope="context" name="log.base" source="log.base" defaultValue="/home/test"/>
    <springProperty scope="context" name="log.file.name" source="log.file.name" defaultValue="test"/>
    <appender name="rootLoggerFileOut"  class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${log.base}/${log.file.name}_root.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <FileNamePattern>${log.base}/${log.file.name}.%d{yyyy-MM-dd}.%i.log
            </FileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy
                    class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                
                <maxFileSize>50MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%date [%thread] [${log.srv.tag}] %-5level %logger{80} -
                %msg%n
            </pattern>
        </encoder>
    </appender>`
application-dev.properties
`log.base=/home/dev`
`log.file.name=test`
`log.srv.tag=TEST`
when application run  ,/home/test/test.log and /home/dev/test.log  both created at startup

**Comment by philwebb** [comment]
@JokerG This is probably because when the logging system is first start there is no active profile so the default `log.base` value is used and `/home/test/test.log` is written. Then the logging system is re-initialized once `application*.properties` files have been loaded and you get the second file.

Perhaps you can use console based logging by default and only active file logging if `log.file` is set. You can use [logback conditions](https://logback.qos.ch/manual/configuration.html#conditional) to do this.
