### ISSUE TITLE
ReactiveSecurityAutoConfiguration is missing conditions

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14263]
It only does an import of another class that has some conditions on them. That looks weird to me. It should at the very least check Spring Security and Project reactor

**Comment by snicoll** [comment]
I don't understand why `ReactiveUserDetailsServiceAutoConfiguration` is a separate auto-config. It looks like both this class and `WebFluxSecurityConfiguration` could be imported by what is current `ReactiveSecurityAutoConfiguration` and their basic conditions should move there.

Also a condition on reactor should be added as it less costly than checking the web application type.

**Comment by ayudovin** [comment]
Does it mean that 
 `@Configuration`
 `@EnableWebFluxSecurity`
 `static class EnableWebFluxSecurityConfiguration {}`
also should be located in `ReactiveSecurityAutoConfiguration` ?

**Comment by snicoll** [comment]
@ayudovin You are correct. Madhura and I just discussed this one and I think we have this covered. I am assigning Madhura so that work is not duplicated.

**Comment by ayudovin** [comment]
@snicoll, ok, som in this case i won't fix this bug.
