### ISSUE TITLE
Using HTTP proxy implicitly creates a tunnel

### ISSUE THREAD

**Issue by kleinron** [spring-projects/spring-boot#14276]
### Expected behavior
When I run a local proxy (port 7000), and use `curl`, the command looks like this:
```bash
curl "http://httpbin.org/get?a=z" -x localhost:7000
```
What happens, and this is the expected behavior, is that `curl` establishes a TCP connection to localhost:7000, and runs the HTTP request against the local proxy, rather than the target (httpbin).

### Actual behavior
If I use the following code:
```java
public static void main(String[] args) {
  ReactorClientHttpConnector connector = new ReactorClientHttpConnector(options -> {
    options.httpProxy(addressSpec -> addressSpec.address(InetSocketAddress.createUnresolved("localhost", 7000)));
  });
  WebClient webClient = WebClient.builder()
      .clientConnector(connector)
      .build();

  Mono<ClientResponse> exchange = webClient.get().uri(URI.create("http://httpbin.org/status/200")).exchange();
  ClientResponse response = exchange.block();
  System.out.println(response.statusCode().value());
}
```
then the http client would first execute a `CONNECT` command (method) against the local proxy, and then would execute the original HTTP request (`GET`) inside the TCP level channel/tunnel it created from the executed `CONNECT` method.
I would expect that the default behavior when using a HTTP proxy would be the same as the one provided by `curl`, demonstrated above.

Spring Version:
2.0.4.RELEASE
OS:
Mac 10.13.6

**Comment by philwebb** [comment]
Thanks for the report. Unfortunately this is the wrong issue tracker for the problem. Can you raise it at [jira.spring.io](http://jira.spring.io) instead please.
