### ISSUE TITLE
Spring Boot + JSF without web.xml is not working

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#1428]
I tried setting up the project from https://github.com/stephanrauh/JSF-on-Spring-Boot which really works fine, even without faces-config.xml. But as soon as i removed web.xml, it threw java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.FacesContextFactory.

Can somebody look into the matter and find exact way for spring boot to work with jsf with annotations only.

**Comment by persapiens** [comment]
Hi @rajjaiswalsaumya , 

You have two options to integrate one technology like JSF with Spring Boot: manually or using [Spring Boot Starters](http://stackoverflow.com/questions/28273543/what-are-spring-boot-starter-jars). 

You configured Spring Boot with JSF manually. All these steps could be done by specific JSF Spring Boot Starter.

There is no built in Spring Boot Starter to integrate JSF, but Spring Boot references [one Community Contribution](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters) called [JoinFaces](http://joinfaces.org).

You could try [JoinFaces Example](https://github.com/joinfaces/joinfaces-example) also.

**Comment by achkaramine** [comment]
Thank you @rajjaiswalsaumya, i had the same issue and it was resolved by replacing the Application class by the one you give in the example ;)
