### ISSUE TITLE
Add runApplication kotlin extension function to spring-boot 1.x

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-boot#14282]
I don't understand, why spring-boot 1.x don't have same `runApplication` kotlin extension function like we have in spring-boot 2.x?

```kotlin
inline fun <reified T: Any> runApplication(vararg args: String) =
    SpringApplication.run(T::class.java, *args)
```

Is it possible somehow add it also in 1.x?

---
Regards,
Maksim

**Comment by snicoll** [comment]
Official Kotlin support was added in Spring Framework 5 and Spring Boot 2. If you have questions, please come ask us on Gitter or ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
