### ISSUE TITLE
kafka-Serializer/Deserializer config not work if i put it  in boostrap.yml,but worked in application.yml

### ISSUE THREAD

**Issue by celesky** [spring-projects/spring-boot#14286]
kafka-Serializer/Deserializer config not work if i put it  in boostrap.yml,but worked in application.yml
It's very confusing,because other properties all effective except the serde properties.
eg:
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

test case:
https://github.com/celesky/spring-cloud-demo/tree/master/bus-kafka

just run it to reproduce this ~

**Comment by snicoll** [comment]
This issue tracker does not deal with Spring Cloud-related issues. `bootstrap.properties` is a Spring Cloud concept that is not meant to contain your application configuration (check [the doc](https://cloud.spring.io/spring-cloud-static/spring-cloud.html#_the_bootstrap_application_context)). If you believe you've found a bug there, please raise it against [the appropriate project](https://github.com/spring-cloud/spring-cloud-commons)
