### ISSUE TITLE
Koltin DSL (RouterFunctionDsl) doesn't supports RenderingResponse in router function

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-boot#14300]
Hello all,

With java, to render template engine views i can use RouterFunction<?> in routes bean:

```java
@SpringBootApplication
public class Application {
  @Bean RouterFunction routes(final ApplicationHandlers handlers) {
    return //...skipped
        .andOther(route(GET("/").and(accept(TEXT_HTML)), handlers::index))
        ;
  }
// main skipped..
```

so with that, I can use both, ServerResponse:

```java
  Mono<ServerResponse> index(final ServerRequest request) {
    return ok().contentType(TEXT_HTML)
               .render("index", singletonMap("message", "Hello, World!"))
        ;
  }
```

and RenderingResponse:

```java
  Mono<RenderingResponse> index(final ServerRequest request) {
    return create("index").modelAttribute("message", "Hello, World!")
                          .build()
        ;
  }
```

but unfortunately I can't do similar with Kotlin DSL:

![image](https://user-images.githubusercontent.com/2445604/45049366-1984b080-b087-11e8-876d-6f992be911fa.png)

Only `Mono<ServerResponse>` handler like so:

```kotlin
  val index: Mono<ServerResponse> by lazy {
    ok().contentType(TEXT_HTML)
        .render("index", mapOf("message" to "hey"))
  }
```
will works correctly...

I think it's bug

---
Regards,
Maksim

**Comment by philwebb** [comment]
Thanks for raising the issue but I'm afraid that this is the wrong tracker. The [RouterFunctionDsl](https://github.com/spring-projects/spring-framework/blob/1bdbc7bdef75709bec7abc3972db23c8211b17d1/spring-webflux/src/main/kotlin/org/springframework/web/reactive/function/server/RouterFunctionDsl.kt) class is part of Spring Framework so you'll need to open an issue on [jira.spring.io](https://jira.spring.io/projects/SPR/issues). If you have time, creating a small sample application that shows the problem will really help.

**Comment by daggerok** [comment]
Hello, @philwebb 

I have created [that](https://jira.spring.io/browse/SPR-17244) JIRA

---
Regards,
Maksim
