### ISSUE TITLE
Corrupted request body when using publishOn() in ReactiveAuthenticationManager

### ISSUE THREAD

**Issue by voychris** [spring-projects/spring-boot#14315]
I've ran into an issue when using `spring-boot-starter-webflux` & `spring-boot-starter-security`. 
When I hit the api with enough concurrency the body of the request gets corrupted. For example, if I hit the api with 20k requests containing `{"foo": "yyy"}` in the body and another 20k requests containing `{"foo": "xxx"}` and log the body in the controller I occasionally get something like `xxy`, `xyx`, `yyx` and all the other permutations of `xxx` and `yyy`.

Here's a sample project to reproduce the issue and a README with all the steps & explanation: https://github.com/voychris/webflux-security-concurrency-issue

The sample app has a controller (`SimpleController`) and a security filter chain which uses a custom `FooReactiveAuthenticationManager` & a `FooAuthenticationConverter`.

Notes:
- Spring Boot 2.0.4.RELEASE
- OSX:
```
❯ uname -a
Darwin xxx.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```
- I've used 2 Java versions
```
❯ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

❯ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

**Comment by bclozel** [comment]
I think this looks like a duplicate of [SPR-17193](https://jira.spring.io/browse/SPR-17193).

@voychris could you take a look at that other issue and let us know? Rossen added a comment with a possible workaround there.

**Comment by voychris** [comment]
I think you're right, @bclozel. Following Rossen's advice and disabling `USE_THREAD_LOCAL_FOR_BUFFER_RECYCLING` did help:

```java
@Configuration
@EnableWebFlux
public class WebConfig implements WebFluxConfigurer {

    private final ObjectMapper objectMapper = new ObjectMapper(
        new JsonFactory().disable(JsonFactory.Feature.USE_THREAD_LOCAL_FOR_BUFFER_RECYCLING));

    @Override
    public void configureHttpMessageCodecs(ServerCodecConfigurer configurer) {
        configurer.defaultCodecs().jackson2JsonDecoder(
            new Jackson2JsonDecoder(objectMapper)
        );

        configurer.defaultCodecs().jackson2JsonEncoder(
            new Jackson2JsonEncoder(objectMapper)
        );
    }
}
```
What's interesting, though, is that I've observed the same (garbled) behaviour with Gson.

**Comment by bclozel** [comment]
Thanks for checking, I'm now closing this is a duplicate of [SPR-17193](https://jira.spring.io/browse/SPR-17193).

I don't understand your note about Gson, since Spring WebFlux doesn't support Gson as an Encoder right now. Did you implement it yourself?

**Comment by voychris** [comment]
My bad @bclozel. I haven't properly swapped Jackson out so that note was not true.
