### ISSUE TITLE
Unable to override org.springframework logging levels since 2.1.0.M2

### ISSUE THREAD

**Issue by docent** [spring-projects/spring-boot#14310]
Since 2.1.0M2, overriding Spring logging levels in dev mode using `logback-spring.xml` doesn't work. Attaching a project generated with Initializr, with `logback-spring.xml` file (that lowers spring level to WARN) added in resources
[demo (8).zip](https://github.com/spring-projects/spring-boot/files/2352593/demo.8.zip). To reproduce:
- run `gradlew bootRun`
- observe log messages
- revert boot version to 2.1.0.M1 in `build.gradle`
- run `gradlew bootRun` again and watch spring related log entries disappear

On a side note, I'm not sure if the decision to include these DEBUG logs by default, even in dev mode, was well thought. The result is a lot of unhelpful information in the log. Frankly I would rather leave the DEBUG off by default, as 99% percent of the time I don't need these logs while developing.

Also reported [here](https://stackoverflow.com/questions/51243923/logback-logging-levels-are-ignored-spring-boot-2-1-0)

**Comment by snicoll** [comment]
I think this report is much wider than what is happening in practice. 

> Unable to override logging levels

Just to be sure we're taking about the same thing, I assume you mean certain `org.springframework` log levels. Overriding of other levels should work fine.

**Comment by docent** [comment]
Yeah, I mean overriding `org.springframework` log levels, e.g.:
```
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml" />
    <logger name="org.springframework" level="warn"/>
</configuration>```

**Comment by philwebb** [comment]
The additional output only happens when devtools is present. I think it's due to [this change](https://github.com/spring-projects/spring-boot/commit/f2511b7fa3ceec800a2fb6adedcbf0e39c3cb253#diff-518d871f83187bdb14818725044d64d2)
