### ISSUE TITLE
ReactiveMongo autoconfiguration bug

### ISSUE THREAD

**Issue by GlebovV** [spring-projects/spring-boot#14317]
There is exception when springboot inits reactive mongo auto config:

```
...
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveMongoTemplate' ry.java:1096) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
y.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at ...
Caused by: java.lang.IllegalStateException: Invalid mongo configuration, either uri or host/port/credentials must be specified
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.autoconfigure.mongo.ReactiveMongoClientFactory.createCredentialNetworkMongoClient(ReactiveMongoClientFactory.java:107) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
...
```

Mongo properties is correct and works fine with non reactive mongo;
Exception was thrown in class: org.springframework.boot.autoconfigure.mongo.ReactiveMongoClientFactory
method:
```
...
package org.springframework.boot.autoconfigure.mongo;
...
public class ReactiveMongoClientFactory {
...
	private MongoClient createCredentialNetworkMongoClient(MongoClientSettings settings) {
		Assert.state(this.properties.getUri() == null, "Invalid mongo configuration, "
				+ "either uri or host/port/credentials must be specified");
		...
	}
...
}
```
It throws an exception when properties.uri != null, but should at properties.uri == null

Assert.state code:
```
...
package org.springframework.util;
...
public abstract class Assert {
...
	// Assert a boolean expression, throwing an IllegalStateException
	// if the expression evaluates to false.
	public static void state(boolean expression, String message) {
		if (!expression) {
			throw new IllegalStateException(message);
		}
	}
...
}
```

**Comment by snicoll** [comment]
I got confused myself but the check is proper. If you set authorization or host/port, you can't set the URL. There are unit tests that are covering this scenario.

Rather than analysing what the problem in our code could be, please share details about your setup. A sample project we can run ourselves would be ideal.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
