### ISSUE TITLE
Enable request compression on Jetty

### ISSUE THREAD

**Issue by castorm** [spring-projects/spring-boot#14311]
Following up on #11827 

Apparently Jetty actually does implement this on `GzipHttpInputInterceptor` see: https://github.com/eclipse/jetty.project/pull/964

However, it requires specifying `inflateBufferSize` on `GzipHandler` as per the following snippet:
```
// Handle request inflation
if (_inflateBufferSize>0)
{
    HttpField ce = baseRequest.getHttpFields().getField(HttpHeader.CONTENT_ENCODING);
    if (ce!=null && "gzip".equalsIgnoreCase(ce.getValue()))
    {
        // TODO should check ce.contains and then remove just the gzip encoding
        baseRequest.getHttpFields().remove(HttpHeader.CONTENT_ENCODING);
        baseRequest.getHttpFields().add(new HttpField("X-Content-Encoding",ce.getValue()));
        baseRequest.getHttpInput().addInterceptor(new GzipHttpInputInterceptor(baseRequest.getHttpChannel().getByteBufferPool(),_inflateBufferSize));
    }
}
```

In the original issue, it was pointed out that request compression should be offered by the underlying container, which is the case for Jetty, however, it requires this additional parameter to work out-of-the-box.

Would you consider including such attribute on `JettyHandlerWrappers#createGzipHandlerWrapper`?

My current workaround is either using my own GzipHandler, or inspect registered handlers on my customizer looking for the GzipHandler provided by spring-boot, and set the parameter there:

```
@Component
public class JettyWebServerCustomizer implements WebServerFactoryCustomizer<JettyServletWebServerFactory> {

    private final int inflateBufferSize;

    public JettyWebServerCustomizer(@Value("${server.compression.inflate-buffer-size:65536}") int inflateBufferSize) {
        this.inflateBufferSize = inflateBufferSize;
    }

    @Override
    public void customize(JettyServletWebServerFactory factory) {
        factory.addServerCustomizers(server -> {
            configureGzipHandler(server.getHandler(), inflateBufferSize);
        });
    }

    private static void configureGzipHandler(Handler handler, int inflateBufferSize) {
        if (handler == null) {
            return;
        } else if (handler instanceof GzipHandler) {
            ((GzipHandler) handler).setInflateBufferSize(inflateBufferSize);
        } else if (handler instanceof HandlerWrapper) {
            configureGzipHandler(((HandlerWrapper) handler).getHandler(), inflateBufferSize);
        }
    }
}
```

**Comment by philwebb** [comment]
I'm not sure that we should enable this by default, it feels like something that should be opt-in. Ideally I'd like to see the [Tomcat issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=62072) fixed so we can support this in a uniform way. Looks like Undertow [already supports it](https://github.com/undertow-io/undertow/commit/097da9634056bca6b94c3bec523afcadfe7cf108)

**Comment by snicoll** [comment]
There was a comment in #11827 that states we're watching those issues and we'd reconsider when they're done. I am not sure what else we could do really.

**Comment by wilkinsona** [comment]
It looks like Jetty already has the functionality that the open issue I have been watching is tracking, so we're just left with Tomcat now. I'll continue to watch the Tomcat issue. I agree that there's not much more we can do at this stage so let's close this. As already mentioned on #11827, we can re-open it if Tomcat adds the functionality. In the meantime, it's pretty straightforward to enable on Jetty and Undertow using a customiser.
