### ISSUE TITLE
Spring boot start fail

### ISSUE THREAD

**Issue by WilliamShoww** [spring-projects/spring-boot#14316]
I'm use spring boot 2.0.3 or 2.0.4 .I start spring boot fail,but no exception viewed.Amazing! run spring test,
can look error exception. why?how to handler it?

**Comment by wilkinsona** [comment]
Can you please provide some more details? As sample that reproduces the behaviour would be ideal. This can be caused by having Commons Logging on the classpath (please see #12457 for details).

**Comment by WilliamShoww** [comment]
@wilkinsona  Thank you very much. It's OK
