### ISSUE TITLE
Spring Boot Actuator error 406 Not Acceptable

### ISSUE THREAD

**Issue by eduardocintra** [spring-projects/spring-boot#14321]
I'm trying to use spring-boot-admin and I was get a error saying that my application is "down", then I began a search about this and discovered that Spring-boot-admin uses the actuator to get some informations about the application, then I trying to acess the URL http://localhost:8084/actuator and always I get the errror "type=Not Acceptable, status=406".

![err](https://user-images.githubusercontent.com/2051934/45160147-1a206280-b1bf-11e8-8c23-47836308bb10.png)

Then I discovered that the actuator just responds if I send the "Accept: application/json" in the request.

![screenshot_2](https://user-images.githubusercontent.com/2051934/45159640-b9445a80-b1bd-11e8-8684-9d1073672601.png)

I don't know if this is a bug or it was to be that way. I guess that spring-boot-admin dont send "Accept: application/json".

**Comment by snicoll** [comment]
@eduardocintra it's a bit unclear what's going on (especially the 406 in the browser) but Spring Boot Admin is not managed here, see https://github.com/codecentric/spring-boot-admin
