### ISSUE TITLE
Configure memory leak detection for Netty

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#14338]
We should add a property for configuring the level of leak detection with Netty.

This can be done statically, has obviously a performance cost, but is really useful if an application is dealing with `DataBuffer` instances or extensive customizations on the Netty engine.

This applies to both server and client use cases, and Netty offers an API for that:

```java
ResourceLeakDetector.setLevel(Level.PARANOID);
```

We could also consider enabling this by default when the devtools are activated.

**Comment by bclozel** [comment]
Closing as there isn't much demand for this and the JVM argument might still be the best way to achieve that.

**Comment by JamesChenX** [comment]
@bclozel  Is it possible to reopen this ticket? Our project wants to set the level to ADVANCED in the development environment and SIMPLE in the production environment according to the profile in application.yaml.

**Comment by bclozel** [comment]
@JamesChenX Thanks for the comment, we'll reconsider this. This is indeed a good use case.

@violetagg I'm wondering if this is enough, or if we should make this feature more general. When dealing with memory leak issues with Netty, are there other options to enable? Typically, when working on a memory leak report - what would you ask developers to enable in their applications to collect useful information? Are specific logs enabled?

I'm trying to figure out if changing the Netty flag is enough or if we can do something more here. Thanks!

**Comment by wilkinsona** [comment]
Should this be assigned to 2.5.x rather than 2.4.x? If is is an enhancement then I don't think it belongs in 2.4.x.

**Comment by bclozel** [comment]
Yes, wrong milestone indeed!
