### ISSUE TITLE
Migrate size properties to DataSize

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14345]
We have some properties that represents a size (usually in bytes). Now #13821 is done we should migrate them to `DataSize` so that we get proper IDE support.

**Comment by qct** [comment]
Do you need any help?

**Comment by snicoll** [comment]
@qct if you have time today then please go ahead but I've assigned myself as I really want this to be fix for M4 Monday.

**Comment by qct** [comment]
@snicoll  please take a look, build error because of previous commits, seems I can't trigger a CI rebuild

**Comment by snicoll** [comment]
Closing in favour of PR #14549
