### ISSUE TITLE
BasicJsonParser fail to parse a value with an escaped double quote

### ISSUE THREAD

**Issue by johnchen1993** [spring-projects/spring-boot#14348]
version: spring-boot-2.0.4.RELEASE.jar

Test code: 

```java
public static void main(String[] args) {
	String str = "{\"title\": \"\\\"hello , test\"}";
	System.out.println(str);
	Map<String, Object> map = new BasicJsonParser().parseMap(str);
	System.out.println(map);
}
```

Test result:

`{"title": "\"hello , test"}`

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.springframework.boot.json.BasicJsonParser.parseMapInternal(BasicJsonParser.java:103)
	at org.springframework.boot.json.AbstractJsonParser.trimParse(AbstractJsonParser.java:49)
	at org.springframework.boot.json.AbstractJsonParser.parseMap(AbstractJsonParser.java:37)
	at org.springframework.boot.json.BasicJsonParser.parseMap(BasicJsonParser.java:42)
```

in the debug of Eclipse:

BasicJsonParser.java

```java
for (String pair : tokenize(json)) {
	String[] values = StringUtils.trimArrayElements(StringUtils.split(pair, ":"));
	String key = trimLeadingCharacter(trimTrailingCharacter(values[0], '"'), '"');
	Object value = parseInternal(values[1]);
	map.put(key, value);
}
```
the tokenize() returns is:

`"title": "\"hello `
and
` test"`

**Comment by johnchen1993** [comment]
{"title": "\"hello , test"}

**Comment by philwebb** [comment]
The `BasicJsonParser` is quite limited so I'm not surprised that there are edge cases like this that don't work. We'll see what we can do to fix this but until then you should consider adding Jackson or GSON to your project.

**Comment by johnchen1993** [comment]
Jackson it's good.

seems you guys already knew what might happen, instead there has not `warn ` or `@Deprecated`.

not realize that we have some difference understanding at the words like 'limitations' and 'basic' until this bug shows up. LOL.

**Comment by philwebb** [comment]
> seems you already knew what might happen

Not specifically, but there's obviously been a lot more investment in libraries like Jackson than we've been able to spend on `BasicJsonParser`, that's why I'm not surprised you've found the issue.

**Comment by philwebb** [comment]
Closing in favor of PR #14521
