### ISSUE TITLE
Support Prometheus Pushgateway

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#14346]
It would be nice to bring the Prometheus push-gateway functionality that was implemented in micrometer-legacy into spring boot 2.x. See
* https://github.com/micrometer-metrics/micrometer/pull/394
* https://github.com/micrometer-metrics/micrometer/issues/830
* https://stackoverflow.com/questions/49779684/how-to-export-metrics-to-prometheus-via-pushgateway-using-spring-boot-2-0

The push-gateway is handy for batch-programs (e.g. non-longrunning processes)

**Comment by philwebb** [comment]
Closing in favor of PR #14353
