### ISSUE TITLE
Autoconfiguration for WebClient + OAuth2 + WebFlux

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14351]
It would be nice if we could simplify the configuration for WebClient + OAuth2 + WebFlux. For example, a user must do this right now:

```
@Bean
WebClient webClient(ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepository, authorizedClientRepository);
	return WebClient.builder()
			.filter(oauth)
			.build();
}
```

It would be nice if Spring Boot could auto configure this if there is a `ReactiveClientRegistrationRepository` and `ServerOAuth2AuthorizedClientRepository` bean available and it is NOT a servlet environment (this includes web applications that are of type none since CLI tools would use this).

Related #14352

**Comment by snicoll** [comment]
Thanks but we don't need two separate issues for this. This is about the same thing in the two web environments we support.
