### ISSUE TITLE
Cannot override spring.version in spring-boot-starter-parent pom with a property

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14355]
It used to be possible to define `spring.version` and override the version used in an app that has the `spring-boot-starter-parent`. It's not working now, e.g. with Spring Boot 2.1.0.BUILD-SNAPSHOT you always get `spring-core` 5.1.0.RC3. Possibly because of the usage of `flatten-maven-plugin` in `spring-boot-parent`?

**Comment by snicoll** [comment]
I did test the introduction of `spring-framwork.version` and made sure it was properly aliasing the previous property. Unfortunately I forgot about the flatten plugin and I hope there is a way to configure it so that it keeps the current aliasing.

**Comment by dsyer** [comment]
I see. So there is a new property `spring-framework.version` which I was unaware of. I tried using that instead and it seems to work the same way the old `spring.version` used to. Maybe if we put a comment in the `spring-boot-dependencies` pom saying that it is deprecated or something that would be clearer?

**Comment by wilkinsona** [comment]
Apparently not as Stephane [already did that](https://github.com/spring-projects/spring-boot/blob/67d543c64cd79734a9d27d9a086d099e0c364648/spring-boot-project/spring-boot-dependencies/pom.xml#L159-L160).

I think we can fix this by using `keep` for `<properties>` when the pom is flattened but some experimentation is needed.

**Comment by wilkinsona** [comment]
I've reopened #12544 to fine tune or revert the change as needed.
