### ISSUE TITLE
Create InMemoryReactiveClientRegistrationRepository in web-application-type=none

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14350]
Currently Spring Boot only creates `InMemoryReactiveClientRegistrationRepository` in web applications. However, it is quite likely that users will want to leverage this with non web applications (i.e. a CLI tool).

It would be nice if `InMemoryReactiveClientRegistrationRepository` would be created for non web applications too.

**Comment by mbhave** [comment]
We also need to create a `ServerOAuth2AuthorizedClientRepository` bean.

**Comment by rwinch** [comment]
Thanks! I can confirm that this is working and improves the setup for those using a non-web application. You can find the diff after these changes here https://github.com/rwinch/webclientoauth2-cli/commit/ed86aed8f6d8de510b594cded5fb8832a66d2022
