### ISSUE TITLE
Add auto-configuration related components index metadata

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14356]
I thought for some reason they were already there, but I must have dreamt it, or tried it in a branch and deleted it, because I can't see them now. They wouldn't be used in a regular Spring Boot app with `@EnableAutoConfiguration` but there might be other applications so it would be a courtesy to include them in the regular published jars (e.g. I wanted a `ConfigurationClassPostProcessor` that ignored classes not in the index).

**Comment by philwebb** [comment]
Hopefully just a case of adding an annotation processor right?

**Comment by dsyer** [comment]
Yes, that should do it.

**Comment by snicoll** [comment]
I don't think we should do that. Adding `spring.components` _anywhere_ turns off classpath scanning and replaces it with the index. If Spring Boot shipped such file, then all Spring Boot applications would require to use the annotation processor as well as their components wouldn't be discovered anymore.

**Comment by snicoll** [comment]
This issue is now blocked until we find a way to provide that information without enabling index usage for the whole application.

**Comment by philwebb** [comment]
Actually, thinking about this some more, we don't do scanning directly in Boot so I'm not sure we should add the index at all. Users should not be scanning `org.springframework` IMO.
