### ISSUE TITLE
Autoconfiguration for WebClient and OAuth2 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14352]
It would be nice if we could simplify the configuration for WebClient + OAuth2 + Servlet. For example, a user must do this right now:

```java
@Bean
WebClient webClient(ClientRegistrationRepository clientRegistrationRepository, OAuth2AuthorizedClientRepository authorizedClientRepository) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2 = new ServletOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepository, authorizedClientRepository);
	return WebClient.builder()
			.apply(oauth2.oauth2Configuration())
			.build();
}
```

It would be nice if Spring Boot could auto configure this if there is a ClientRegistrationRepository and OAuth2AuthorizedClientRepository bean available and it is a servlet environment

-----

Description from #14351:

It would be nice if we could simplify the configuration for WebClient + OAuth2 + WebFlux. For example, a user must do this right now:

```
@Bean
WebClient webClient(ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepository, authorizedClientRepository);
	return WebClient.builder()
			.filter(oauth)
			.build();
}
```

It would be nice if Spring Boot could auto configure this if there is a `ReactiveClientRegistrationRepository` and `ServerOAuth2AuthorizedClientRepository` bean available and it is NOT a servlet environment (this includes web applications that are of type none since CLI tools would use this).

**Comment by snicoll** [comment]
> could auto configure this 

Do you mean exposing a `WebClient` bean? We've done that in the past with `RestTemplate` and it turned out to be quite a bad idea (that's where the builder idea comes from). 

Or perhaps you have some kind of dedicated builder in mind?

**Comment by rwinch** [comment]
I can see how you wouldn't want to necessarily expose a `WebClient` bean. Would you consider exposing `ServerOAuth2AuthorizedClientExchangeFilterFunction` as a `Bean` so that users can automatically get all `ExchangeFilterFunction` when defining their `WebClient`?

**Comment by mbhave** [comment]
We could provide a `WebClientCustomizer` that adds the `ExchangeFilterFunction` to the builder if OAuth is present.

**Comment by bclozel** [comment]
I think @mbhave is right - this would apply transparently to all `WebClient` instances built with the auto-configured `WebClient.Builder`; if developers choose to create their own builder, this would not apply.

I'm wondering about a couple of things:

* Is this a problem if that filter function is applied to `WebClient` instances that don't need this? Could this have unintended consequences on client instances that are communicating with other hosts not related to that OAuth2 resource?
* Should we restrict its application in to some contexts, i.e. should this also be active during tests?
* Should we enforce a certain order in the applied filter functions, i.e. should this be applied early or late in the order filter functions?

**Comment by rwinch** [comment]
@mbhave @bclozel Thanks for your input. I really think that applying it to the WebClient.Builder is a good option.

The questions that were asked are good things to consider. I have responded to each below. Please let me know if there is any additional ways I can help.

> Is this a problem if that filter function is applied to WebClient instances that don't need this? Could this have unintended consequences on client instances that are communicating with other hosts not related to that OAuth2 resource?

It depends on how you instantiate the `ExchangeFilterFunction`. As I advised above, this would not have any unintended consequences because the `ExchangeFilterFunction` does nothing unless the user explicitly provides one of the client request attributes that are supported (i.e. they must provide the clientRegistrationId or oauth2AuthorizedClient as a client request attribute). For example, the user must do something like this:

```java
this.webClient.get()
	.uri(this.uri)
	// the user explicitly opted into using the OAuth support by providing the clientRegistrationId
	.attributes(clientRegistrationId("google"))
	.retrieve()
	.bodyToMono(String.class);
```

If you set `defaultOAuth2AuthorizedClient = true`, then the access token from a user who authenticates with `oauth2Login` would be sent. This is not an advisable default because the request might be made to an external service that should not see the access token. For example, if the `ExchangeFilterFunction` is setup like this:

```java
ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepository, authorizedClientRepository);
	// explicitly opt into oauth2Login providing an access token implicitly
	oauth.setDefaultOAuth2AuthorizedClient(true);
	return WebClient.builder()
			.filter(oauth)
			.build();
```
then the following would include an implicit access token if the user logged in via `oauth2Login`.

```java
this.webClient.get()
	.uri(this.uri)
	// implicitly includes the currently logged in users OAuth token because defaultOAuth2AuthorizedClient = true
	.attributes(clientRegistrationId("google"))
	.retrieve()
	.bodyToMono(String.class);
```

If a user wants this to be set to true, they can manually configure their own `WebClient`.

> Should we restrict its application in to some contexts, i.e. should this also be active during tests?

As long as it is configured as shown above, it will not have any unintentional consequences since the user must explicitly apply a client request attribute for it to do any work.

> Should we enforce a certain order in the applied filter functions, i.e. should this be applied early or late in the order filter functions?

This is a bit difficult to answer without knowing what other `ExchangeFilterFunction` are out there. My current understanding is the order does not matter, but I wouldn't be surprised if that changes as I become more aware of what `ExchangeFilterFunction` are available.

**Comment by bclozel** [comment]
The team has discussed this issue and we don't feel it's the right decision to apply this `ExchangeFilterFunction` to all `WebClient` instances. We don't have enough experience with this feature nor enough feedback from the community.

Also, a typical code snippet for that should look like:

```java
@Component
public class MyComponent {

  private WebClient oauthWebClient;

  // use the auto-configured builder by Spring Boot
  // avoid creating a WebClient bean, as we don't necessarily consider that a best practice
  public MyComponent(WebClient.Builder builder,
        ReactiveClientRegistrationRepository clientRegistrationRepository,
        ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {
        ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepository, authorizedClientRepository);
	return builder.filter(oauth).build();
  }

}
```

We thought about:

* applying the filter function to all builders, but we feel it's a bit of an overreach
* creating a `ServerOAuth2AuthorizedClientExchangeFilterFunction` bean
* creating builder/utils methods to help developers achieve that

In the end, the combination of conditions (Spring Security on the classpath, Servlet web application, Spring Security beans being present) and the various solutions we thought about didn't convince us.

We can of course reconsider this decision in the future; for now we don't want to commit to something that we're not sure is the right decision.
