### ISSUE TITLE
CloudServiceConnectors: Provide replacement for deprecated JedisConnectionFactory.setPoolConfig()

### ISSUE THREAD

**Issue by markbigler** [spring-projects/spring-boot#14396]
Spring Boot: 2.0.4.RELEASE

If you create the RedisConnectionFactory via ServiceConnectionFactory

`RedisConnectionFactory redisConnectionFactory(String serviceId, PooledServiceConnectorConfig redisConnectionFactoryConfig);`

then it is currently not possible to set a detailed JedisPoolConfig.

Also the following config with an additional RedisConnectionFactoryConfig (documented in https://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_redis) does not work, because in the RedisConnectionFactory (RedisJedisClientConfigurer.configureClient(builder)) a JedisClientConfigurationBuilder (without setter methods) is used:

``` java
protected static class MyConfiguration extends AbstractCloudConfig {

	@Bean
	public RedisConnectionFactory redisConnectionFactoryDeprecated(RedisConnectionCloudProperties properties) {
		RedisConnectionFactory connectionFactory = connectionFactory().redisConnectionFactory(properties.getServiceId());
		if(connectionFactory instanceof JedisConnectionFactory) {
			JedisPoolConfig poolConfig = new JedisPoolConfig();
			poolConfig.setTestOnBorrow(true);
			// DEPRECATED (no longer working)
			((JedisConnectionFactory)connectionFactory).setPoolConfig(poolConfig);
		}
		return connectionFactory;
	}

	@Bean
	public RedisConnectionFactory redisConnectionFactoryNotWorking(RedisConnectionCloudProperties properties) {
		JedisPoolConfig poolConfig = new JedisPoolConfig();
		poolConfig.setTestOnBorrow(true);

		Map<String, Object> properties = new HashMap<String, Object>();
		properties.put("poolConfig", poolConfig);

		RedisConnectionFactoryConfig config = new RedisConnectionFactoryConfig(properties);

		RedisConnectionFactory connectionFactory = connectionFactory().redisConnectionFactory(properties.getServiceId(), config);
		return connectionFactory;
	}

}
```

A cool thing would be to be able to use something like the JedisClientConfigurationBuilderCustomizer (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html), but that doesn't work in the context of Spring-Cloud-Service-Connectors either.

It would be great if a way would be provided which would allow a more detailed configuration of the ConnectionPool.

**Comment by wilkinsona** [comment]
Thanks for the suggestions, but Spring Cloud Connectors are managed as a [separate project](https://github.com/spring-cloud/spring-cloud-connectors) I believe it's the logical place to implement any enhancements that may come from them.
