### ISSUE TITLE
Enable JMX automatically in spring-boot-starter-integration

### ISSUE THREAD

**Issue by zachariahyoung** [spring-projects/spring-boot#1440]
Could we include the following dependency to spring-boot-starter-integration.

		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-jmx</artifactId>
		</dependency>

I posted a question about JMX and Spring Integration with Boot at http://stackoverflow.com/questions/25497372/how-to-configure-jmx-with-spring-boot/25497956#25497956

And @artembilan suggested that we discuss this feature.

**Comment by dsyer** [comment]
+1 for including JMX in the integration starter - it's kind of a special case because it provides features that are useful to users of pretty much all other SI modules.

**Comment by artembilan** [comment]
Guys, how about to revise this issue with the fact of [recent](https://github.com/spring-projects/spring-boot/commit/c06828558609d2da58fa9f45dff1f1095b93778c) changes to the `spring-boot-starter-integration`?

CC @wilkinsona

**Comment by OzoneGrif** [comment]
Sorry, I reopen this ticket because since Spring-boot 1.3.5 I'm getting JMX warnings :
Failed to unregister the JMX name: org.apache.commons.dbcp2

I reverted to 1.3.4 and the warning disappears. After a tons of googling, I noticed that ticket was closed 3 days ago and that was my issue.

**Comment by wilkinsona** [comment]
@OzoneGrif The change that closed this issue was only made in master (1.4 snapshots) and wasn't included in 1.3.5 so, whatever your problem is, it's unrelated to this issue. If you believe you've found a bug please open a new issue, providing as much information as possible. A small sample that reproduces the problem would be ideal.

**Comment by OzoneGrif** [comment]
Okay thank you. I will continue further testing on my side.

**Comment by stepio** [comment]
I'm not sure that it's a good reason to reopen the ticket, but in my opinion the required dependency on `spring-integration-jmx` should be mentioned here:
http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-jmx.html

**Comment by snicoll** [comment]
This issue is closed so if you want to report something, please create another issue. Before you do, I don't think that adding anything related to Spring Integration in that particular section makes sense.

**Comment by lanaya-corelogic** [comment]
> Could we include the following dependency to spring-boot-starter-integration.
> 
> ```
>     <dependency>
>         <groupId>org.springframework.integration</groupId>
>         <artifactId>spring-integration-jmx</artifactId>
>     </dependency>
> ```
> I posted a question about JMX and Spring Integration with Boot at http://stackoverflow.com/questions/25497372/how-to-configure-jmx-with-spring-boot/25497956#25497956
> 
> And @artembilan suggested that we discuss this feature.

Greetings. I hope I don't reopen this ticket just by replying it. I have added **spring-integration-jmx** dependency to my project and still JVisualVM states:

```
Data not available because JMX connection to the JMX agent could not be established
```

I'm using spring-boot-starter-parent:2.1.1.RELEASE versions. I've tried tons of things combining or getting rid of EnableMBeanExport, EnableIntegrationMBeanExport, ManagedResource, ManagedAttribute... but most of all, I think there should be a log during startup indicating JMX has started and the port it's running, which is never shown.

I'm seeing some messages but I've read I shouldn't care too much about them:

```
2019-01-16 16:50:48.755  INFO 14992 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration$$EnhancerBySpringCGLIB$$45b9c631] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-16 16:50:48.771  INFO 14992 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration' of type [org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration$$EnhancerBySpringCGLIB$$214bd151] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-16 16:50:48.796  INFO 14992 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration' of type [org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration$$EnhancerBySpringCGLIB$$5a337a1e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-16 16:50:48.838  INFO 14992 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mbeanServer' of type [com.sun.jmx.mbeanserver.JmxMBeanServer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-16 16:50:48.871  INFO 14992 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

Any clue would be **highly appreciated**. Thanks in advance.

**Comment by snicoll** [comment]
> most of all, I think there should be a log during startup indicating JMX has started and the port it's running on, which is never shown.

Spring Boot does not start an `MBeanServer` but reuses the existing platform `MBeanServer`unless configured otherwise. This isn't explicit in the doc so I've created https://github.com/spring-projects/spring-boot/issues/15728. 

@lanaya-corelogic it looks like you're trying to connect to a remote JMX server. You should probably configure the platform `MBeanServer` to [listen to remote connections](https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html). In the future, please ask questions on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by lanaya-corelogic** [comment]
> Spring Boot does not start an `MBeanServer` but reuses the existing platform `MBeanServer`unless configured otherwise. This isn't explicit in the doc so I've created #15728.
> 
> In the future, please ask questions on StackOverflow..., we prefer to use GitHub issues only for bugs and enhancements.

Thanks. It looked like a bug according to next documentation, even the JmxAutoConfiguration seems to be attempted to be started up in the log I shared:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-jmx.html

I'll keep testing it out. Thanks again.

**Comment by snicoll** [comment]
>  It looked like a bug according to next documentation, even the JmxAutoConfiguration seems to be attempted to be started up in the log I shared:

I don't think it is. That log is about an `MBeanServer` being eagerly processed which might mean you are configuring something yourself. The fact a bean is created doesn't mean that we're going to create an underlying `MBeanServer`. As indicated in my update to the doc, Spring Boot attempts to locate an existing `MBeanServer` and wraps it in a `mbeanServer` bean. Regardless of all that, I don't understand why that matters as I don't have enough details to what you're trying to do.

Let's stop this conversation here please as this is not the right place. You can ask a question on StackOverflow or chat with the community on gitter.
