### ISSUE TITLE
Upgrade to Junit Jupiter 5.3.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14416]

**Comment by SanderSmee** [comment]
Looking at the [published pom.xml](https://repo.spring.io/release/org/springframework/boot/spring-boot-dependencies/2.0.5.RELEASE/spring-boot-dependencies-2.0.5.RELEASE.pom) for spring-boot-dependencies the version is still the same as for spring-boot 2.0.4.RELEASE:
```
<junit-jupiter.version>5.1.1</junit-jupiter.version>
<junit-platform.version>1.1.0</junit-platform.version>
```

**Comment by wilkinsona** [comment]
Thanks for spotting that, @SanderSmee. The issue was in the wrong milestone.
