### ISSUE TITLE
Add jackson-annotations managed dependency

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14425]
In Jackson 3.0 they are not planning to release patches for `jackson-annotations` but in 2.9 they do. This makes our dependency management look slightly odd because we don't pick the latest version.

See https://github.com/FasterXML/jackson-bom/blob/2.9/pom.xml#L39

**Comment by wilkinsona** [comment]
I don't think we should do this. I think the simplicity of just using the bom outweighs the artificial benefit of using the latest `jackson-annotations` dependency that's identical to the `x.y.0` version.
