### ISSUE TITLE
Upgrade to xml-apis 2.0.2

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14438]

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-boot/issues/6102 for background on why this was added in the first place.

**Comment by wilkinsona** [comment]
Also see https://github.com/spring-projects/spring-boot/issues/7731. IMO, removal would be preferable if it's possible.

**Comment by philwebb** [comment]
We'll remove it instead.
