### ISSUE TITLE
Update description of the `logger-name` hint

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14456]
Logging groups are currently configured using `logging.level.<group>`. Although nice and simple, It's possible that the group name could clash with an existing logger. We should review if a distinct namespace might work better.

One idea would be:
```
logging.group.<name>.level=...
logging.group.<name>.loggers=...
```

Unfortunately it's hard to get good meta-data for that. 

Another option would be:
```
logging.group.level.<name>=...
logging.group.logger.<name>=...
```

That, feels a little backward.

**Comment by snicoll** [comment]
We've discussed this and the current situation is ok. We do have an explicit [`logger-name`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_value_providers) hint already so we should update the semantic of the hint to account for the group and let IDE developers know.

**Comment by snicoll** [comment]
I'd like to update the doc for `logger-name` as part of of this issue and create the relevant issues for the IDE support.

**Comment by snicoll** [comment]
The issue for IntelliJ IDEA is [here](https://youtrack.jetbrains.com/issue/IDEA-199842) and the one for STS [here](https://github.com/spring-projects/spring-ide/issues/325).
