### ISSUE TITLE
Devtools documentation incorrectly uses compileOnly Gradle scope

### ISSUE THREAD

**Issue by douglyuckling** [spring-projects/spring-boot#14451]
The [Developer Tools section of the documentation](https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/reference/htmlsingle/#using-boot-devtools) says:

> ... using `compileOnly` in Gradle is a best practice that prevents devtools from being transitively applied to other modules that use your project.

But the `compileOnly` configuration doesn't work for devtools, as noted by @wilkinsona in [his comment on spring-io/initializr#128](https://github.com/spring-io/initializr/issues/128#issuecomment-258191411).

**Comment by wilkinsona** [comment]
Well spotted, @douglyuckling . If only I'd remembered what I said in November 2016 when [changing the docs](https://github.com/spring-projects/spring-boot/issues/12573) in March 2018.

**Comment by wilkinsona** [comment]
Unfortunately, I don't think Gradle has a built-in configuration that meets our needs and I'm reluctant to start recommending the propdeps plugin again. I've asked on the Gradle Slack channel to see if that's anything I'm not aware of. If there is not then, given that we don't encourage people using a Spring Boot application as a dependency anyway, I'm tempted to just recommend that people us `compile`.

**Comment by douglyuckling** [comment]
Yeah, I had a feeling this wouldn't simply be a documentation fix. 😉

I'm sure you'll get a good answer from the folks on the Gradle Slack channel, but here's my unsolicited opinion anyway:

I think it would make sense for the Gradle plugin to add a custom configuration called `bootRunOnly` that extends the `runtimeClasspath` configuration, and have the `bootRun` task use that configuration for its classpath (instead of `runtimeClasspath`). The "best practice" would be to add devtools to the `bootRunOnly` configuration. If users wanted to include devtools in the JAR they would want to add it to the `runtime` configuration instead (it's not actually used at compile time, right?) in addition to setting `excludeDevtools = false`.

(And my apologies if that solution has previously been proposed and rejected for some reason. I haven't researched the issue deeply.)

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I'd considered customising the classpath of `bootRun`. Unfortunately it won't work well in an IDE when the main method is launched directly as it'd lose DevTools.

Daz DeBoer on the Gradle team has suggested a refinement though by inverting the extension. It looks as if a custom configuration that `runtimeClasspath` extends from may work. I'll need to do some experimenting when I get some time.

**Comment by wilkinsona** [comment]
>  Adding the dependency directly to the runtimeOnly configuration would achieve the same result, no?

It would not. `runtimeOnly` dependencies end up on the test runtime classpath and are also pulled in transitively if another project depends on the project with the `runtimeOnly` dependency in it.

> True, but I'll point out that launching the main class directly from the IDE also doesn't get the classpath modifications made by sourceResources

Indeed not, but that's not necessary when you're using an IDE as it'll "build" any changes to the resource so the DevTools finds them anyway.

> Also, shouldn't it be the IDE's job to support alternative classpaths provided by the build tool, not the build tool's job to make sure everything the user could ever want is in the one and only classpath supported by the IDE?

No, I don't think so. If we can provide something that fits into the existing model that's served IDEs well, we won't place an unnecessary burden on the IDEs' developers and users will be able to use the new functionality as soon as we ship it, rather than waiting for a new version of their IDE to be available and for them to be able to upgrade to it.
