### ISSUE TITLE
Enable debug logging for the web logging group when using DevTools

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14450]
We disabled devtools logging level tweaks in #14310 but this might have been a bit hasty. Perhaps if there was a warning and a way to opt-out the logging changes would be fine.

**Comment by docent** [comment]
Hi @philwebb, after upgrading to 2.1.0.M3, is there any way to disable these default DEBUG logs when using devtools? The solution involving modifying `logback-spring.xml` doesn't work anymore.

**Comment by wilkinsona** [comment]
@docent The reference documentation was updated with that information in the commit that originally closed this issue. It now says the following:

> If you don't want property defaults to be applied you can set
 `spring.devtools.add-properties` to `false` in your `application.properties`

**Comment by bclozel** [comment]
@docent Out of curiosity, could you elaborate why you don't want those logs while working on your app? The Spring Framework team worked on reducing a lot the amount and making those more relevant.

If there's something particular that we could improve here, let us know. If it's just something you don't want to see, then Andy's suggestion is the right thing to do.

**Comment by bclozel** [comment]
@docent We've created #14575 to reconsider that. Thanks for your feedback.
