### ISSUE TITLE
Add ApplicationContextInitializedEvent to correspond to contextPrepared in SpringApplicationRunListener

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14469]
`EventPublishingRunListener` has a `contextPrepared()` method that is fired after the context is prepared but before any bean definitions are loaded. But there is no corresponding `AplicationEvent`. To listen for that callback the user can implement the whole of `SpringApplicationRunListener`, but it would be natural to expect there would be an `ApplicationEvent`.

**Comment by dsyer** [comment]
Actually it's not even possible to do this with a `SpringApplicationRunListener` unless I miss something (at least not from `spring.factories`), because the `SpringApplication` instance is not available to the vanilla interface.

**Comment by wilkinsona** [comment]
Any suggestions for a name for the new event. Here's its position among the others we already have:

1. `ApplicationStartingEvent`
2. `ApplicationEnvironmentPreparedEvent`
3. 
4. `ApplicationPreparedEvent`
5. `ApplicationStartedEvent`
6. `ApplicationReadyEvent`

`ApplicationContextPreparedEvent` is the best I've thought of thus far.

**Comment by dsyer** [comment]
Or just `ContextPreparedEvent`? Maybe too close to Spring Framework naming convention.

I think `ApplicationContextPreparedEvent` is too hard to distinguish from `ApplicationPreparedEvent`.

Maybe `ApplicationContextRefreshingEvent`? It is called just before the context is refreshed, I think.

**Comment by wilkinsona** [comment]
> It is called just before the context is refreshed, I think.

Nope, that's when `ApplicationPreparedEvent` is published as a result of `contextLoaded()` being called.

`contextPrepared()` is called once the application context has been created but its sources haven't been loaded.

**Comment by dsyer** [comment]
OK, how about `ApplicationContextInitializedEvent` (it happens just after the `ApplicationContextInitializers` are applied?

**Comment by philwebb** [comment]
I quite like that name

**Comment by mbhave** [comment]
Closing in favor of #14478.
