### ISSUE TITLE
Spring Data Neo4J @Index(unique = true) does not work

### ISSUE THREAD

**Issue by rahnemon2011** [spring-projects/spring-boot#14465]
In the documentation, it is said that to make a property as a unique, you should use @Index(unique = true) above your property.
But when I use it above my property, and after running the spring boot application, it doesn't create a unique constraint in the Neo4j database. (I Expect that Spring Data Neo4J creates the unique constraint automatically.)

But if I create a constraint in the Neo4j Browser by myself, it will work fine.

    CREATE CONSTRAINT ON (user:User) ASSERT user.userName IS UNIQUE

After that, if I create a user with the same userName twice, it will throw DataIntegrityViolationException. 

So, @Index(unique = true)  doesn't work.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to create an issue on [the spring data neo4j issue tracker](https://jira.spring.io/secure/RapidBoard.jspa?rapidView=27&projectKey=DATAGRAPH&view=planning&selectedIssue=DATAGRAPH-1030) if you feel this is a genuine bug.

**Comment by rahnemon2011** [comment]
@index(unique = true) doesn't work. It's a bug. All other people have the same problem.

**Comment by wilkinsona** [comment]
Then, as @bclozel already suggested, please create an issue in the [Spring Data Neo4J issue tracker](https://jira.spring.io/browse/DATAGRAPH).
