### ISSUE TITLE
Deprecate properties for configuring Cassandra retry, reconnection and load balancing policies in favour of using a ClusterBuilderCustomizer

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14473]
The property-based approach requires the policy implementation to have a default constructor and none of the standard implementations do. The properties should be deprecated in favour of using a cluster build customiser.

**Comment by ayudovin** [comment]
@wilkinsona, as far as i understand you want to just deprecate properties : `loadBalancingPolicy` and `reconnectionPolicy`
