### ISSUE TITLE
Raise the default version of Mongo used with Embedded Mongo to 3.5.5

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-projects/spring-boot#14476]
The current version of embedded MongoDB is 3.2.2 as minimum version of MongoDB used is 3.8.x . can you please raise embedded MongoDB version as well.

**Comment by wilkinsona** [comment]
Sounds reasonable to me. We probably should have raised it in 2.0, but better late than never.

**Comment by wilkinsona** [comment]
I've pushed the changes again to see if it was a one-off problem on Concourse, or something more repeatable. The changes build fine locally for both @mbhave and me.

**Comment by wilkinsona** [comment]
It appears to have hung again across all 4 builds (Java 8, 9, 10, and 11). Running `top` having hijacked the container shows three `extract-…` processes consuming lots of CPU:

```
  20325 root      10 -10  921200  67388  29544 S 105.6  0.2  12:38.09 extract-c780078                                              
  20361 root      10 -10  919140  67756  29944 S 102.7  0.2  12:32.80 extract-0b35940                                              
  20396 root      10 -10  920168  67376  29728 S 100.3  0.2  12:33.71 extract-e160fac  
```

I believe the `extract-` processes are Mongo due to the filename used by Embedded Mongo when it installs it.

**Comment by wilkinsona** [comment]
Let's give 3.5.5 a shot.
