### ISSUE TITLE
Add a paragraph about EnvironmentTestUtils to the Spring Boot 2.0 migration guide

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14475]
`EnvironmentTestUtils` was replaced with `TestPropertyValues` (I think). A sentence or two plus an example would help.

**Comment by kuldeepsidhu88** [comment]
@dsyer I will work on updating the documentation.

**Comment by wilkinsona** [comment]
@kuldeepsidhu88 Thank you for the offer, but the change needs to be made in this repository's wiki. As far as I know, there's no easy way to contribute a change that needs to be made to the wiki (short of copy and paste) as pull requests can't be used.

**Comment by kuldeepsidhu88** [comment]
yes @wilkinsona Earlier, I thought migration guide is part of spring docs which is not the case. 
I don't have permission to edit the wiki page.

**Comment by kuldeepsidhu88** [comment]
Spring docs has been already updated with the latest changes here [TestPropertyValues](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-test-property-values)

**Comment by snicoll** [comment]
I've added [a section in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#environmenttestutils)
