### ISSUE TITLE
Receive parameter with brackets

### ISSUE THREAD

**Issue by fabioebner** [spring-projects/spring-boot#14487]
After the version 2.0.1 the follow controller don't works:

```
@GetMapping("/" )
    public List<Cidade> findByEstado(@RequestParam(name = "q[]") String[] q){
        return cidadeService.findByEstadoIn(Arrays.asList(q));
    }
```

**Comment by wilkinsona** [comment]
Thanks for the report, but you haven't provided enough information to diagnose the problem. I think it's very likely that this is due to a change in Spring MVC, but I can't say for sure as you haven't told us how you're sending the request or which container you're using. If you would like us to spend some time investigating this, please provide us with a minimal sample (something we can unzip or `git clone` and run) that reproduces the problem.

**Comment by fabioebner** [comment]
@wilkinsona  I only create a simple project at https://start.spring.io/ with the 2.0.5 Version. then I Create a controller equals that in my first Post, and try to call with postman for sample or my App (using Axios, and passing an array to parameter) the axios, generate this url: 

`http://localhost:8081/cartorio/?q[]=5b9cfd0170607a2e968b0a1d&q[]=5b9cfd0170607a2e968b0a1e`

After 2 hours trying a lot of workarounds I try to downgrade to 2.0.0 and work fine, then I try to upgrade the version one by one, and until the 2.0.1 work fine, when I chante to any version greather than 2.0.1 stops works. And the server are a embeded tomcat.

**Comment by bclozel** [comment]
While this doesn't explain the behavior change, the [`Servlet` spec](https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameterValues(java.lang.String)) and many other frameworks are using `?q=5b9cfd0170607a2e968b0a1d&q=5b9cfd0170607a2e968b0a1e` and don't use the array notation.

Your sample with a `"q"` parameter name works.

**Comment by fabioebner** [comment]
@bclozel if I remove the "[]" from my parameter work fine.. but the frameworks to use REST(Javascript like AXIOS) when try to transform an Array in Query Parameter he transforms in q[](with brackets)(or depends your parameter name) So until Version 2.0.1 from SpringBoot works fine, when I put in my controller que @RequestParam(name = "q[]") after the 2.0.1 that's annotation dont works,

**Comment by wilkinsona** [comment]
@fabioebner Thanks for the additional description, but that's not really what I was looking for. If you would like us to spend any more time trying to help you, please take the time to provide the minimal sample requested above.

**Comment by fabioebner** [comment]
@wilkinsona  I create a Repo to demonstrate the error:

https://github.com/fabioebner/springboot-test

tks for help

**Comment by fabioebner** [comment]
I try to change the server to Jetty and works in version 2.0.5.RELEASE :D

**Comment by wilkinsona** [comment]
Thanks. I would have saved us all a lot of time if, rather than just saying "don't works", you'd taken the time to provide the details of the failure. I presume that it is the following:

```
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:479) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

This is due to [a change](https://bz.apache.org/bugzilla/show_bug.cgi?id=62273) in Tomcat 8.5.32. If you want Tomcat to continue to be able to parse requests that are non-compliant, you can configure it with a connector customiser:

```
@Bean
public WebServerFactoryCustomizer<TomcatServletWebServerFactory> tomcatCustomizer() {
	return (tomcat) -> {
		tomcat.addConnectorCustomizers((connector) ->
			((AbstractHttp11Protocol<?>)connector.getProtocolHandler()).setRelaxedQueryChars("[]"));
	};
}
```
