### ISSUE TITLE
Auto-Configure HTTP Resource Factories on Jetty and Reactor servers

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#14495]
#14058 introduced the auto-configuration of HTTP resource factories for Jetty and Reactor Netty based clients. With that, developers can customize those HTTP resources and we make sure that they're tied to the application lifecycle.

This issue is about taking the same resources and configuring them on the server side as well.

**Comment by bclozel** [comment]
@rstoyanchev, does that description fits our discussion?

If we do that, server and clients configured by Spring Boot will *always* share the resources created by those factories. The only way to get around that would be to manually `WebClient.create()` a client instance.

I'm fine with that state of things but I was wondering if this sounds good to you.

**Comment by rstoyanchev** [comment]
@bclozel that sounds right. For Reactor Netty, client and server already used to share the global resources before #14058 so in a way this would restore the previous arrangement. As for deviating from that model, couldn't one inject `WebClient.Builder` and then change the connector?
