### ISSUE TITLE
Add auto-config support for Spring Security with LDAP Authentication Provider

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#1449]
When Spring LDAP is detected (see #1448) and the needed Spring Security LDAP classes are on the classpath Spring Boot could/should attempt to setup Spring Security with a LDAP AuthenticationProvider. 

Preferably also allowing for running an embedded server (when specifiying an ldif) or to connect to a remote server.

**Comment by mbhave** [comment]
@dsyer does `LdapAutoConfiguration` and `EmbeddedLdapAutoConfiguration` take care of this?

**Comment by dsyer** [comment]
Probably. Is that for security?

**Comment by mbhave** [comment]
actually no, doesn't look like it is.

**Comment by wilkinsona** [comment]
We've dramatically simplified security auto-configuration in 2.0 so that it doesn't try to be quite so clever. See https://spring.io/blog/2017/09/15/security-changes-in-spring-boot-2-0-m4 for details. As such, I no longer think it's appropriate to consider adding this in auto-configuration.
