### ISSUE TITLE
Make it possible for the output from the BuildInfo task to be repeatable

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-boot#14494]
Follow-up to #8391

The _build-info.properties_ file contains a timestamp in the header comment, this leads to [non-reproducible builds](https://reproducible-builds.org).

https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/gradle-plugin/reference/html/#integrating-with-actuator-build-info
```
springBoot {
  buildInfo {
    properties {
      time = null
    }
  }
}
```

Will remove the _build.time_ property, but the timestamp in the header comment will be changed on every build:

```
#Properties
#Mon Sep 17 17:34:11 CEST 2018
build.artifact=example-artifact
build.group=example-group
build.name=example-name
build.version=1.0.0
```

**Comment by wilkinsona** [comment]
Thanks for the report. Nulling out the time is aimed at up-to-date checking rather than repeatability. It works fine for up-to-date checks as Gradle compares the property key-value pairs and doesn't care about any comments. Unfortunately, the writing of the date is baked into `java.util.Properties` and can't be disabled. Short of implementing our class for writing the properties to disk, or using a custom `Writer` that suppresses the output of the comment there's not a lot we can do about this.

**Comment by sdavids** [comment]
Also the order of the keys could be sorted to be independent of their hash values.

**Comment by sdavids** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.WriteProperties.html

> - no timestamp comment is generated at the beginning of the file
> - the lines in the resulting files are separated by a pre-set separator (defaults to '\n') instead of the system default line separator
> - the properties are sorted alphabetically

**Comment by wilkinsona** [comment]
Thanks for the pointer to `WriteProperties`. I wasn't aware of that Gradle task. Unfortunately, the code in question here is shared between our Gradle plugin and our Maven plugin so changing it to depend on something that's Cradle-Specific isn't an option. I does, however, open up the option of reworking things to no longer use the shared code and use `WriteProperties` in the Gradle case. We've done something similar in other places in the plugin where the shared code didn't work well with Gradle.

**Comment by pgilad** [comment]
This is what I do in the mean time:
```groovy
springBoot {
    mainClassName = 'com.sample.sample.SampleApplication'
    buildInfo {
        properties {
             time = null
        }

        // Watch https://github.com/spring-projects/spring-boot/issues/14494
        doLast {
            File f = new File(destinationDir, 'build-info.properties')
            f.text = f.filterLine { !it.startsWith('#') }
        }
    }
}
```

And I get the same md5 for each jar

**Comment by wilkinsona** [comment]
With thanks to @sbrannen for the new sorted properties support in Framework, this one is now straightforward.

**Comment by mbarve31** [comment]
How to make multiple properties null?

**Comment by philwebb** [comment]
@mbarve31 Please ask questions on stackoverflow.com or join us on gitter.im. We prefer to keep the issue tracker for bugs and enhancements.
