### ISSUE TITLE
spring boot jsp 404 Whitelabel Error Page

### ISSUE THREAD

**Issue by godpit** [spring-projects/spring-boot#14493]
spring boot 1.4.0.RELEASE: Realpath=null, it is ok
<img width="1265" alt="wx20180917-214329 2x" src="https://user-images.githubusercontent.com/34534331/45627127-c9b0db00-bac3-11e8-9800-03e888589fd0.png">

spring boot 1.5.10.RELEASE:Realpath=/private/var/folder/....
the path is not found in my OS, so that  it is 404 with Whitelabel Error Page
<img width="1825" alt="wx20180917-214727 2x" src="https://user-images.githubusercontent.com/34534331/45627126-c9184480-bac3-11e8-8b95-fc481b501ed8.png">

However, how i could solve this problem?

**Comment by bclozel** [comment]
Given this description, I don't understand the issue here.
Could you provide a small application that reproduces the issue and describe 1) what you're trying to achieve, 2) what you've tried, 3) what you expected as a result and 4) what you got instead.

Thanks!

**Comment by godpit** [comment]
Both of them could go into the method of controller,  but it is error with Whitelabel Error Page in spring boot 1.5.10. So, i  found that it is different between 1.4.0 and 1.5.10 in org.apache.jasper.servlet.JspServlet .

**Comment by godpit** [comment]
I  build that it is a package of jar package ,not a war.

**Comment by wilkinsona** [comment]
We do not support JSPs in a jar file. If you want to use JSPs you must use jar packaging. Given that it's not clear that this is a bug in Spring Boot, I'm going to close this one. If it doesn't work with war packaging, please provide a sample that reproduces the problem and we can re-open the issue.

**Comment by godpit** [comment]
why is it ok with spring boot 1.4.0?

**Comment by godpit** [comment]
I add the node in the pom :
<resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
               
                <directory>src/main/webapp</directory>
          
                <targetPath>META-INF/resources</targetPath>
            </resource>
it is ok with spring boot 1.4.10.

**Comment by godpit** [comment]
I want to know the reason for that, please help me!  Thanks a lot!

**Comment by godpit** [comment]
@wilkinsona I add the zip of the example. please help me, thanks a lot!

**Comment by wilkinsona** [comment]
Your sample is using jar packaging which is not supported.  If t's working, it's only doing so by accident. Unfortunately, I can't afford to spend time figuring out why it appears to work in your case for two reasons.

1. We only support JSPs with war packaging.
2. 1.4.0 is no longer supported.

The 1.4.0 reference documentation already state that you should use war packaging if you want to use JSPs: https://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#boot-features-jsp-limitations. This recommendation still stands with 1.5.x and 2.0.x which are the two currently supported versions.

**Comment by godpit** [comment]
@wilkinsona  I'm so sorry for  troubling you. but 1.4.0, it is ok with jar packaging.
