### ISSUE TITLE
MessageSource can not get message

### ISSUE THREAD

**Issue by xinwu-yang** [spring-projects/spring-boot#14498]
`String msg = messageSource.getMessage("password.format.error",null,LocaleContextHolder.getLocale());`

But report error : No message found under code 'password.format.error' for locale 'zh_CN'.

I am using SpringBoot 2.0.5

I am using CookieLocaleResolver:
```
    @Bean
    public LocaleResolver localeResolver() {
        CookieLocaleResolver cookieLocaleResolver = new CookieLocaleResolver();
        cookieLocaleResolver.setDefaultLocale(Locale.SIMPLIFIED_CHINESE);
        cookieLocaleResolver.setCookieName("i18n");
        return cookieLocaleResolver;
    }
```
My config:

![image](https://user-images.githubusercontent.com/12267648/45662831-0b7a6980-bb36-11e8-9111-5ba8cb8905b2.png)

![image](https://user-images.githubusercontent.com/12267648/45662990-d15d9780-bb36-11e8-9309-24025d403751.png)

**Comment by wilkinsona** [comment]
@xinwu-yang Can you please provide a small sample (something that we can unzip or `git clone` and run) that reproduces the problem? Unfortunately, reverse engineering something from screenshots is too time consuming and too error-prone to be worthwhile.

**Comment by xinwu-yang** [comment]
Thanks for the reply, I found this problem because I did not add the message.properties for the default.

message.properties is required.

![image](https://user-images.githubusercontent.com/12267648/45670368-2dcfaf80-bb55-11e8-8fcd-28244764fafc.png)

**Comment by wilkinsona** [comment]
Thanks for letting us know.
