### ISSUE TITLE
Unnecessary recursive call to initialize(String, Set<String) in RelaxedNames

### ISSUE THREAD

**Issue by QilongZhang** [spring-projects/spring-boot#14508]
https://github.com/spring-projects/spring-boot/blob/a91f9b6f1796d505a837e43a9283b260aaea5af5/spring-boot/src/main/java/org/springframework/boot/bind/RelaxedNames.java#L62-L75

Line 72 makes no sense.

**Comment by wilkinsona** [comment]
Thanks for the report. Given the `result` is added to `values` on line 71, the call to `initialize(result, values)` on line 72 doesn't seem to make sense as the contains check on line 63 will always return `true` and will then return early from the method. If line 72 was removed I don't think there'd be any functional difference.

**Comment by QilongZhang** [comment]
@wilkinsona  Can you give a refer doc about the strategy generating RelaxedNames? it's  a little strange. For example, for `a_b`, the RelaxedNames contain `a.b`; however, for `a-b`, the RelaxedNames do not contain `a.b`

**Comment by wilkinsona** [comment]
Relaxed names are a little strange in 1.5, which is why they've been made significantly less relaxed in 2.0. I don't believe the strategy used in 1.x has been formally documented anywhere.

**Comment by wilkinsona** [comment]
Given that this won't be a functional change, there's no real benefit to removing it. That means that in our opinion the small risk of making the change isn't worth it. Thanks anyway.
