### ISSUE TITLE
How can I configure enabled cihper suits for Https?

### ISSUE THREAD

**Issue by wding2** [spring-projects/spring-boot#14502]
Now I want to set the cihper suits for Https in an spring boot project, but I don't know how to configure it.
Could you please tell me how can I configure enabled cihper suits for Https?
thanks.

**Comment by bclozel** [comment]
There's a `server.ssl.ciphers` configuration property for that - please check out the reference documentation.

Also, please use our gitter channel or StackOverflow for future questions.
