### ISSUE TITLE
Register functional rather than reflective bean definitions where possible

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14516]
`BeanTypeRegistry` is used in `@Conditional` processing, and needs to be installed into the bean factory super early. It registers a `BeanDefinition` in order to get lifecycle callbacks from the `ApplicationContext`. The problem for performance (and AOT) is that it forces the `BeanFactory` to construct the instance using reflection, when that is completely unnecessary now that we have the function bean registration API.

Changing this:

```java
			BeanDefinition bd = new RootBeanDefinition(BeanTypeRegistry.class);
			bd.getConstructorArgumentValues().addIndexedArgumentValue(0, beanFactory);
			listableBeanFactory.registerBeanDefinition(BEAN_NAME, bd);
```

to this:

```java
			BeanDefinition bd = BeanDefinitionBuilder
					.genericBeanDefinition(BeanTypeRegistry.class,
							() -> new BeanTypeRegistry(
									(DefaultListableBeanFactory) beanFactory))
					.getBeanDefinition();
			listableBeanFactory.registerBeanDefinition(BEAN_NAME, bd);
```

reduces startup time fractionally (maybe 1% of a microapp).

**Comment by wilkinsona** [comment]
It looks like we can do something similar in `SharedMetadataReaderFactoryContextInitializer` and `WsdlDefinitionBeanFactoryPostProcessor`. The latter will only benefit apps using Web Services, but the former should be more broadly beneficial.
