### ISSUE TITLE
Auto-configure Micrometer's Kafka consumer metrics

### ISSUE THREAD

**Issue by jkschneider** [spring-projects/spring-boot#14525]
See https://github.com/micrometer-metrics/micrometer/issues/512

**Comment by wilkinsona** [comment]
`KafkaConsumerMetrics` is currently [marked as incubating](https://github.com/micrometer-metrics/micrometer/blob/b0b16a3d1553359791315f8de46a96ef1ade7d4e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L48). That means that it is "a feature that is experimental and may yield a breaking change in a minor release". As such, I think it may be a bit too soon to add auto-configuration in Boot.

**Comment by jkschneider** [comment]
Removed the incubating label in https://github.com/micrometer-metrics/micrometer/commit/f82e3a51e21a93a96d2b746df25b2dde5a6894a1. I was originally a bit confused by the Kafka metrics docs which still refer to their inclusion in a pre-1.0 version of the Kafka client. 

The metrics have been tested against the 2.x line of Kafka. Inclusion of metrics that were added between 1.x and 2.x of Kafka are gated by a major version check. The Kafka client's major version can be read from a particular JMX property.

**Comment by ayudovin** [comment]
@wilkinsona, have you started this enhancement?

**Comment by wilkinsona** [comment]
Yes, I have. Thanks anyway.

**Comment by wilkinsona** [comment]
@vspiliopoulos Sorry, this isn’t the right place. `KafkaConsumerMetrics` is part of Micrometer and Boot just provides auto-configuration for it. Also please note that, in the absence of the required MBeans, a [notification listener is used](
https://github.com/micrometer-metrics/micrometer/blob/39054157800d8c8107c0719bc61d3b071bac8726/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L212) to bind the metrics when the MBeans are eventually registered.

**Comment by vspiliopoulos** [comment]
@wilkinsona thanks for the quick reply! Very good point that the is the notification listener.. but they are not registered in my case. I will investigate this a little bit more, as the code looks ok, and maybe comment this on the micrometrics project.

**Comment by vspiliopoulos** [comment]
@wilkinsona it is a indeed  micrometer issue. If at least one "kafka.consumer" mbean is registered, then no notification listener is ever registered because if the [return statement](https://github.com/micrometer-metrics/micrometer/blob/39054157800d8c8107c0719bc61d3b071bac8726/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L206). Thanks again for the help!
