### ISSUE TITLE
Remove OAuth2 AutoConfiguration for Grant Type

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14553]
The changes in https://github.com/spring-projects/spring-boot/commit/f5deebf0cb2fb802bafb5ff85652ebe89e9da98d#diff-b716836901d5fea39e485e35997f2f62 made it so that the grant type is already configured in the hiearchy, so it does not make sense to be able to provide that again as a property.

Related: #14552
Related: #14554

**Comment by mbhave** [comment]
This isn't valid anymore since #14554 will remove the grant type hierarchy.
