### ISSUE TITLE
Remove `jackson-module-parameter-names` from `spring-boot-starter-json`

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#14566]
The`jackson-module-parameter-names` github page says:
> This module has become part of Jackson Java 8 Modules as of Jackson 2.8.5

Considering that:
- Spring Boot is using Jackson `2.9.7`
- `spring-boot-starter-json` already includes the Java8 module.

`jackson-module-parameter-names` should probably be removed from the json starter.

**Comment by wilkinsona** [comment]
Thanks, but I think you have misunderstood the change that was made in Jackson.

The change that GitHub page is describing is that the code has moved from that repository into the Java 8 Modules repository. It's is not saying that it's now part of another Maven module.

The code's now [here](https://github.com/FasterXML/jackson-modules-java8/tree/master/parameter-names). The `com.fasterxml.jackson.module:jackson-module-parameter-names` Maven module still exists in Jackson 2.9 and contains code that isn't part of any other module.

**Comment by brenuart** [comment]
Oh… indeed. Sorry, I went too fast at creating the ticket ☹
