### ISSUE TITLE
SpringApplication.setApplicationContextClass does not correctly deduce REACTIVE type

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14589]
This appears not to cause any problems with existing applications, but it seems inconsistent and results in a `SpringApplication` having `webApplicationType=NONE` in an integration test (per the logic in `setApplicationContextClass()` which is called by the test context loader).

**Comment by wilkinsona** [comment]
> GenericReactiveWebApplicationContext is not a WebApplicationContext

This is by design. `WebApplicationContext` is [coupled to the Servlet API](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/WebApplicationContext.html#getServletContext--).

> results in a `SpringApplication` having `webApplicationType=NONE` in an integration test 

I don’t think this is deliberate and reminds me of a discussion we had recently (this issue may be a duplicate). I’ll repurpose the issue to tackle this part for now.

**Comment by philwebb** [comment]
We had a discussion recently about the fact `ConfigurableReactiveWebEnvironment` is used in`OnWebApplicationCondition` but we didn't support it in the `EnvironmentConverter` (#13977).

**Comment by philwebb** [comment]
@dsyer have you got an example test we can run for this one?

**Comment by dsyer** [comment]
Is the reason for the current behaviour that an integration text uses a mock server by default (not a full HTTP stack)? I think the context class ends up as `GenericReactiveWebApplicationContext` instead of `ReactiveWebServerApplicationContext` or something? To me that is still not "NONE", but it's also somewhere in between "NONE" and "REACTIVE" in the way it behaves when the context is created.

**Comment by dsyer** [comment]
> have you got an example test we can run for this one?

Duh. I was wrong about the test context - it was me setting the application context class in a `spring.factories` listener - so wrong about the mock server as well. But the logic is still wrong in `SpringApplication` I think - a reactive web application type gets converted to "NONE".

**Comment by philwebb** [comment]
@dsyer You mean in [this method](https://github.com/spring-projects/spring-boot/blob/64627fa9d6a205deea9c87bf57055b99ecbdc087/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L284) or something else?

**Comment by dsyer** [comment]
No, sorry [this one](https://github.com/spring-projects/spring-boot/blob/64627fa9d6a205deea9c87bf57055b99ecbdc087/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L1195.)

**Comment by dsyer** [comment]
And... I was right about the test context loader: https://github.com/spring-projects/spring-boot/blob/fd2080e7cc38af2db7c7a669e650fcce9a6194b3/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/SpringBootContextLoader.java#L313.

**Comment by snicoll** [comment]
I had some trouble understanding the underlying issue so here's a summary now I got it.

The application context is fine but there is a disconnect with `SpringApplication#getWebApplicationType` and the context. 

This can be reproduced by adding the following listener:

```
class Listener implements ApplicationListener<ApplicationPreparedEvent> {

    @Override
    public void onApplicationEvent(ApplicationPreparedEvent event) {
        System.err
                .println("****: " + event.getSpringApplication().getWebApplicationType());
    }

}
```

You can see that the context is a reactive web application context but the type is `NONE` (rather than `REACTIVE`).

**Comment by wilkinsona** [comment]
Re-opening to fix the problem with the change made in https://github.com/spring-projects/spring-boot/commit/b4c5aea1526cb36ecbd7bd1e0df04118ee7957f5 that was reported in #14697.
