### ISSUE TITLE
Does not work on older bash; operator =~ problems

### ISSUE THREAD

**Issue by mustafic** [spring-projects/spring-boot#14588]
Found an error on this line when using it on older versions of bash:

https://github.com/spring-projects/spring-boot/blob/0fe60109b10cc4e89dfafd6ba0d8ee46e8cfe6b8/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L35

Why not do it so, that also the older versions of bash understand this command, example:

`[[ $jarfile = *"init.d"* ]]`

The error that we are getting is:

`./rest-service-0.0.1-SNAPSHOT.jar: line 35: conditional binary operator expected
./rest-service-0.0.1-SNAPSHOT.jar: line 35: syntax error near unexpected token ``=~\'
./rest-service-0.0.1-SNAPSHOT.jar: line 35: ``  if [[ "$jarfile" =~ init\.d ]]; then'`

Thank you

**Comment by wilkinsona** [comment]
What distro are you using and what version of Bash does it contain? We test against Ubuntu Trusty and Xenial from 2016 as well as CentOS 6.9.

**Comment by mustafic** [comment]
Here is the version:

> bash --version
GNU bash, version 2.04.0(1)-release (powerpc-ibm-aix4.3.2.0)
Copyright 1999 Free Software Foundation, Inc.

The operator =~ was introduced in bash version 3. See [Bash, version 3](http://tldp.org/LDP/abs/html/bashver3.html#REGEXMATCHREF)

I know that upgrading the bash on my machine would fix the problem but fixing the script would cover a broader population (those like me 😄 with bash 2.0) without any need on updating bash.

Thanks.

**Comment by wilkinsona** [comment]
Thanks. Assuming I have read that output correctly, you are using AIX 4.3.2 which was released in 1998. While we could make the change you have suggested, it does not come without risk. I am not yet convinced that the risk is worth it to suppprt a twenty-year-old OS. Doubly so as we are unlikely to add tests for an environment that uses Bash 2 so the risk of regression would be high.

Requiring Bash 3, released in 2004, doesn’t seem unreasonable to me. Those, like you, who require Bash 2 can always provide their own launch script. Let’s see what the rest of the team thinks.

**Comment by mustafic** [comment]
Thanks and hoping the team votes in my favor 🤞

**Comment by philwebb** [comment]
I have a feeling we'll be playing whack-a-mole if we try to  to support older bash versions, especially without an integration test. I'm sorry, but I think the best option if you want to support AIX is to [embed your own launch script](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html#embeddedLaunchScript).
