### ISSUE TITLE
Auto-configure binding of Micrometer's JettyServerThreadPoolMetrics

### ISSUE THREAD

**Issue by matsumana** [spring-projects/spring-boot#14591]
Few months ago, I've added several Jetty's ThreadPool metrics in Micrometer.
ref: https://github.com/micrometer-metrics/micrometer/pull/593

Could you add the following sources to Spring Boot 2.1?
I want to use them in Spring Boot 2.1

- https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/web/jetty/JettyMetricsAutoConfiguration.java
- https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/web/jetty/JettyMetricsPostProcessor.java

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We can take a look at what's possible, but I don't think we can implement this in the same way as has been done in Micrometer. The biggest problem is that, if a user has customised Jetty's thread pool, the auto-configuration will overwrite that customisation.

**Comment by wilkinsona** [comment]
I asked a few questions on the [Micrometer PR](micrometer-metrics/micrometer#593). We'll need some feedback on those to make progress on this one.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by matsumana** [comment]
I commented in https://github.com/micrometer-metrics/micrometer/pull/593#issuecomment-427890735.
Could you please check it?

**Comment by wilkinsona** [comment]
Thanks. I've taken a look. Unfortunately, the problem with overwriting the user's thread pool customisation remains.

**Comment by wilkinsona** [comment]
FYI, @izeye. I think this approach is better than the one that we discussed on the Micrometer PR and the one that Boot was using for `TomcatMetrics`.

**Comment by izeye** [comment]
@wilkinsona Thanks for the quick feedback! I'll try with it.

**Comment by izeye** [comment]
@wilkinsona I created https://github.com/micrometer-metrics/micrometer/pull/925 and https://github.com/micrometer-metrics/micrometer/pull/926 to align Spring Boot 1.5.x support with this approach.

**Comment by matsumana** [comment]
Thank you so much!
