### ISSUE TITLE
Could not find spring-boot-loader-tools.jar (2.1.0.M4)

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#14595]
Gradle project using spring-boot-gradle-plugin 2.1.0.M4 fails with the following error:
```
Could not find spring-boot-loader-tools.jar (org.springframework.boot:spring-boot-loader-tools:2.1.0.M4).
Searched in the following locations:
    https://repo.spring.io/milestone/org/springframework/boot/spring-boot-loader-tools/2.1.0.M4/spring-boot-loader-tools-2.1.0.M4.jar
```

The said jar doesn't exist. However, it exists for 2.1.0.M3 and below.

I have both https://repo.spring.io/snapshot and https://repo.spring.io/milestone repos set up in the build file.

**Comment by wilkinsona** [comment]
I suspect this was a temporary problem during the release process. The jar's there now.

**Comment by SelvaSurukam** [comment]
Still facing the same issue.

**Comment by wilkinsona** [comment]
@SelvaSurukam The jar is there: https://repo.spring.io/milestone/org/springframework/boot/spring-boot-loader-tools/2.1.0.M4. Perhaps you can provide an example build that cannot find it?
