### ISSUE TITLE
Make GenericApplicationContext the default ApplicationContext class for non-webapp 

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14590]
`GenericApplicationContext` is arguably a better choice these days and all the default webapp context types used by Boot are `GenericApplicationContext`, so it would make things (by default) uniform and more predictable. It would simplify the job of anyone trying to add `ApplicationContextInitializers` with functional bean definitions.

**Comment by philwebb** [comment]
The default is currently `AnnotationConfigApplicationContext` which extends `GenericApplicationContext`. This works:

```java
SpringApplication application = new SpringApplication(ScratchApplication.class);
application.setWebApplicationType(WebApplicationType.NONE);
GenericApplicationContext run = (GenericApplicationContext) application.run(args);
```

Is `AnnotationConfigApplicationContext` doing too much or causing some other issues?

**Comment by dsyer** [comment]
I don't think it was always a `GenericApplicationContext`, was it (maybe I am misremembering)? Anyway it has a built in `AnnotatedBeanDefinitionReader` which is too much for anything that doesn't want to use `@Configuration` or wants to control it a bit more. Probably this can be rolled up into #7562.

**Comment by philwebb** [comment]
#7562 doesn't look related, wrong issue perhaps?

**Comment by philwebb** [comment]
I've added a comment to #8115.
