### ISSUE TITLE
Integration tests failing after 2.0.5.RELEASE

### ISSUE THREAD

**Issue by wesleyody** [spring-projects/spring-boot#14606]
When I run my integration tests it's giving me the error below on the moment that tries to insert something on the "database":
```
ERROR: relation "subscription" does not exist
```
<sup>*subscription is the name of my table that I'm trying to insert*</sup>

But when I just run my application it is working fine. It seems that is creating an empty database. With `1.5.4.RELEASE` works fine

My configuration:

```
spring.datasource.platform=postgres
spring.datasource.dbcp.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=true

spring.flyway.enabled=true
spring.flyway.out-of-order=true
spring.flyway.validate-on-migrate=false
spring.flyway.table=schema_version
```

```java
@RunWith( SpringJUnit4ClassRunner.class )
@SpringBootTest
@EnableJpaRepositories( repositoryBaseClass = BaseRepositoryImpl.class )
public class ApplicationIT {
```

```java
@RunWith( SpringJUnit4ClassRunner.class )
@WebAppConfiguration
@Transactional
public class TestIT {

    private MockMvc mockMvc;
    @Resource
    private WebApplicationContext webApplicationContext;

    @Before
    public void setup () {
        mockMvc = MockMvcBuilders
            .webAppContextSetup( webApplicationContext )
            .apply( SecurityMockMvcConfigurers.springSecurity() )
            .build();
    }
}
```

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, you haven't provided enough information for us to be able to help you. It's not clear why you expect to be creating the `subscription` table. Is it Flyway, Hibernate, or something else?

If you would like us to spend some time trying to help you, please provide a minimal sample application that works with 1.5 and fails with 2.0.

**Comment by wilkinsona** [comment]
Thanks, but some code snippets in a comment aren't really what we need. Can you please turn those into a minimal sample application (something that we can `git clone` or unzip) that reproduces the problem. We'll also need details of how to setup any dependencies your application has. Ideally, a minimal sample should not have any unless they are strictly necessary to reproduce the problem.

**Comment by wesleyody** [comment]
It was a problem created by https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#updated-default-create-drop-handling

It's all good thanks
