### ISSUE TITLE
Publish release notes after artifacts have been promoted on CI

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#14604]
@wilkinsona suggested removing this job as it adds extra overhead and we don't often run into a situation where staging is useful. However, in case we decide to keep staging, we should publish the release notes after promotion.

**Comment by philwebb** [comment]
Does @wilkinsona mean the `stage-rc`, `stage-milestone` and `stage-release` tasks or something else?

**Comment by wilkinsona** [comment]
I meant that we’d just go straight to the release or milestone repository. We so rarely rollback a staged release, I’m not sure the extra complexity is worth it.

**Comment by philwebb** [comment]
I've rolled back on more than one occasion in the past (although less so since moving to concourse). The main time it's helped is when the flatten goal wasn't quite correct and the published POMs didn't work. I think we should leave it in for now.

**Comment by mbhave** [comment]
Converting this issue to just move publishing of release notes after promotion.
