### ISSUE TITLE
Allow Undertow's HTTPS listener to be configured with an SSLContext that uses a custom TrustManager

### ISSUE THREAD

**Issue by b0c1** [spring-projects/spring-boot#14611]
Hi team, I want to use embedded Undertow WebServer with custom trust manager (no I don't want to use the embedded trustore support).
I know I can create a new endpoint in the `addBuilderCustomizers`, but in this case, the application will start two port. Why private the customizeSsl method?

**Comment by wilkinsona** [comment]
It looks like an oversight to me in the support for customising Undertow. Looking at the code, it's possible to customise Jetty or Tomcat's SSL configuration at this level without having multiple connectors. Unless I have missed something, that doesn't appear to be possible with Undertow.

**Comment by eppjo** [comment]
I am eagerly waiting for the availability of this feature. When can I expect it?

**Comment by wilkinsona** [comment]
@eppjo We don't have a firm date at the moment. As things stand, it won't be in Spring Boot 2.3 but will be considered for future 2.x releases. A pull request is a great way to being that forward and possibly get the functionality into 2.3.

**Comment by rodrigoserracoelho** [comment]
Hello team, same here, we are also eagerly waiting for this feature to be available, we have a big spring boot ecosystem. 
Any news?

**Comment by rodrigoserracoelho** [comment]
And actually the same applies for Tomcat, also not possible to configure SSLContext.

**Comment by wilkinsona** [comment]
@rodrigoserracoelho No news at this time. If there was, it would appear in this issue.

> And actually the same applies for Tomcat, also not possible to configure SSLContext.

You can take complete control over the SSL configuration of a Tomcat `Connector` using a `TomatConnectorCustomizer` bean. Take a look at Boot's own [`SslConnectorCustomizer`](https://github.com/spring-projects/spring-boot/blob/68bd9d6b6d38631d1d748c087e522439e9e867f0/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/tomcat/SslConnectorCustomizer.java) for inspiration.

**Comment by rodrigoserracoelho** [comment]
Thanks @wilkinsona for your suggestion, i will take a look.

**Comment by wilkinsona** [comment]
This has been addressed in 3.1 with the introduction of support for `SslBundle`s.
