### ISSUE TITLE
Upgrade Java 11 CI image to openjdk:11.ea-28-jdk

### ISSUE THREAD

**Issue by gandrade** [spring-projects/spring-boot#14629]
According to https://hub.docker.com/_/openjdk/, update the current Java 11 CI version to the latest one. available (openjdk:11.ea-28-jdk)

**Comment by snicoll** [comment]
Closing in favour of PR #14631 

@gandrade fyi we don't need an issue if you intend to submit a PR. A PR only is enough.

**Comment by gandrade** [comment]
@snicoll Got it. Thanks for the heads-up. :+1:
