### ISSUE TITLE
@AutoConfigureMockMvc does not honor FilterRegistrationBean.enabled=false

### ISSUE THREAD

**Issue by nttd-zhangxibin** [spring-projects/spring-boot#14636]
I think the FilterRegistrationBean.enabled flag should be use at the [org.springframework.boot.test.autoconfigure.web.servlet.SpringBootMockMvcBuilderCustomizer#addFilters]

**Comment by philwebb** [comment]
I think I agree.

**Comment by wilkinsona** [comment]
Me too. The only reason to have a filter registration bean with enabled set to `false` is to disable the filter. I can't think of a reason why you'd want your MockMvc tests to have the filter but your app not to have it.

**Comment by nttd-zhangxibin** [comment]
Thanks for modified

> I can't think of a reason why you'd want your MockMvc tests to have the filter but your app not to have it.

In my case, i configured a customize filter to security filter chains,but do not want to let it enable on global filter chains.The following way is used, may be very low.

MyWebSecurityConfigurerAdapter

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        List<SecurityFilterChain> chains = new ArrayList<>();

        chains.add(
           new DefaultSecurityFilterChain(new AntPathRequestMatcher("..."), myFilter()));

        http.addFilterBefore(new FilterChainProxy(chains),
                BasicAuthenticationFilter.class);
    }

    @Bean
    public MyFilter myFilter() {
        return new MyFilter();
    }

    @Bean
    public FilterRegistrationBean registrationMyFilter(MyFilter filter) {
        FilterRegistrationBean registration = new FilterRegistrationBean(filter);
        registration.setEnabled(false);
        return registration;
    }
