### ISSUE TITLE
RequestRateLimiterGatewayFilterFactory

### ISSUE THREAD

**Issue by rainbowJson** [spring-projects/spring-boot#14632]
I want to use json response to limit the flow prompt,
Can you provide an exception throw method, I want to capture the current limit exception, give the caller a friendly hint

<img width="560" alt="default" src="https://user-images.githubusercontent.com/12165006/46195807-dfca6100-c337-11e8-8dec-e100116e2f81.png">

<img width="947" alt="default" src="https://user-images.githubusercontent.com/12165006/46195896-1ef8b200-c338-11e8-8f5d-1e284ec2df7e.png">

**Comment by spencergibb** [comment]
Gateway is not part of spring boot

**Comment by snicoll** [comment]
Thanks @spencergibb.
