### ISSUE TITLE
Load ApplicationContextIntiailizers using the resource loader's class loader

### ISSUE THREAD

**Issue by PantherDD** [spring-projects/spring-boot#14641]
When loading the Spring factories, `SpringApplication.getSpringFactoriesInstances()` [uses the thread context classloader](https://github.com/spring-projects/spring-boot/blob/0c00508b3cdec4d30641dd26d8503299e0391fd3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L449) instead of the one passed at construction (inside the `ResourceLoader`). Using `Thread.currentThread().getContextClassLoader()` has caused an issue in my setup, as I was expecting the passed-in classloader to be used.

If you agree this is a bug, please use `getClassLoader()` in this method too, like the rest of the class does.

Also, there seem to be a total of [38 places in Spring Boot where this thread context classloader is used](https://github.com/spring-projects/spring-boot/search?q=getContextClassLoader). Not sure if those are legitimate uses, but I'd be nice to check them whether they can also use the `ResourceLoader` instead, so as to avoid further bugs popping up because of the same root cause.

**Comment by philwebb** [comment]
It feels like a bug to me, but I'd like a second opinion from someone else on the team so I'll flag this one for "team attention".

**Comment by wilkinsona** [comment]
While the change in [this commit](https://github.com/spring-projects/spring-boot/commit/042e512d3dd4460b3975e50deb1285ac656dd9f4) doesn't appear to have been intentional, it's been this way since before 1.0 was released. I think we'd need a pretty compelling argument to change it now as it has the potential to be a breaking change.

@PantherDD Can you please describe the issue that you've faced in your setup is as much detail as possible?

**Comment by PantherDD** [comment]
@wilkinsona I also don't see a reason why this would've been intentional. And even though fixing it might theoretically be a breaking change, to me it seems very likely that in practice, it won't break anything really. The reason is that `SpringApplication` is usually the entry point into the program, where there are no other classloaders present yet (so all are the same). And if someone tried to use the classloader customization via `ResourceLoader`  constructor arg like I did, they must have run into this issue as well, so fixing it would probably help them too.

Details about my case: I was trying to build up the Spring context inside a custom Ant task, to extract some information about the wiring of the actual production service and document it. The way this works is that Ant creates a new classloader that uses the classpath defined in `build.xml` for the task, instantiates your task class using that loader, then runs it. The tread context classloader however stays the same as before: the classloader that loaded Ant itself. This original loader doesn't know about Spring (let alone the JARs containing my service classes and config), so `spring.factories` will be completely missing, and `SpringApplication` will fail.
I could of course simply switch out the tread context classloader while I'm doing Spring stuff inside the Ant task, and replace the original one afterwards, but then what's the point of passing in a `ResourceLoader` to `SpringApplication`?

**Comment by wilkinsona** [comment]
Any `ApplicationContextInitializer` that relies on being loaded by the thread context class loader and that's different to the class loader from the resource loader will be broken. That may well be unlikely, but we have no way of knowing. Someone may have looked at the existing code, not noticed what's possible via a resource loader and relied on the thread context class loader instead. Breaking that scenario in a maintenance release, particularly when there's a workaround, can't be justified. I agree with Phil that if we do anything here, it should be done in 2.1.x at the earliest.

**Comment by PantherDD** [comment]
> Someone may have looked at the existing code, not noticed what's possible via a resource loader and relied on the thread context class loader instead.

@wilkinsona But for this fix to make any difference, they _did_ have to realize what a `ResourceLoader` is, what it's for, as well as explicitly instantiating one that uses a specific classloader and passing it into the constructor. If they didn't, then `resourceLoader == null`, thus `getClassLoader() == Thread.currentThread().getContextClassLoader()`, so there's no change in behavior at all.

**Comment by PantherDD** [comment]
That's fine, as I said, I really just wanted to understand in what scenario would this be a breaking change. But something as simple as a client providing a `ResourceLoader` only to customize loading of the Spring application banner could be a valid example. If someone were to do that, they would probably implement `getClassLoader()` as `return CustomBannerLoader.class.getClassLoader();`, which in theory could be different from the thread's context classloader. Still, it's very unlikely that this would cause an issue, but I understand your point of having to play it totally safe. Let it be a v2.1 fix then. :+1:
