### ISSUE TITLE
Actuator's EndpointRequest doesn't consider server.servlet.path

### ISSUE THREAD

**Issue by qavid** [spring-projects/spring-boot#14646]
Same issue #12934 was fixed in spring-boot 2.0.2 and it worked until spring-boot 2.0.5
Sample is the same as @candrews provided in his [comment](https://github.com/spring-projects/spring-boot/issues/12934#issuecomment-383201943).

**Comment by wilkinsona** [comment]
Closed by d4cad5e916c3fa0e10fa1469583d20ba323b8615.
