### ISSUE TITLE
Context fails to load when using -f ./pom.xml and spring-boot-maven-plugin

### ISSUE THREAD

**Issue by StevenPG** [spring-projects/spring-boot#14649]
I have a relatively simple spring boot project using 2.0.3-RELEASE that builds successfully using mvn clean install without any issues.

However, when pushing this code to a CI server I manage, I run mvn clean install -f ./pom.xml and I get the following errors:

`
[ERROR]   ApplicationTests.contextLoads » IllegalState Failed to load ApplicationContext
`

With any attempt to load the context in unit tests, the application will not build. However, if a build is attempted using `mvn clean install` without the `-f pom.xml`, the application context is successfully able to load. When built, the application runs using `java -jar appname.jar` without any issues.

Is this potentially an issue with the spring-boot-maven-plugin?

I ran `mvn clean install -f ./pom.xml` on a new project generated using `mvn archetype:generate` and the issue did not occur.

I couldn't find anything via the search, are there any known bugs with `-f ./pom.xml` usage via maven using the spring boot maven plugin? 

If I'm asking in the wrong place, please redirect me. Thanks

**Comment by wilkinsona** [comment]
I'm not aware of any issues with using `-f`. If tests are failing, then `spring-boot-maven-plugin` isn't involved. It's the Surefire plugin that runs the tests. From your description, it sounds like `mvn clean install` and `mvn clean install -f ./pom.xml` should run the same build. Given that the behaviour is different, then there may be a difference that you haven't described or I'd speculate that you've found an obscure bug in Maven. Either way, to make any progress on this we'll really need a small sample that reproduces the behaviour you've described.

**Comment by StevenPG** [comment]
I'll work on reproducing the issue. At the very least, I can put out the actual root error message. Maybe I'm looking in the wrong place.

`java.lang.IllegalStateException: Failed to load ApplicationContext`

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Unable to resolve persistence unit root URL`

`Caused by: java.io.FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist`

The reason I was looking in the direction of the `spring-boot-maven-plugin` was specifically due to the failures being during the test run. The exception is thrown only in tests where the context attempts to be loaded. Tests with no context initialization pass without issue.

Hopefully I can reproduce with a generated project.

**Comment by wilkinsona** [comment]
Typically, that error will occur when the app class loader only has jars on its classpath, i.e. there aren't any directories on the classpath. I wouldn't expect that to be the case when Surefire has built the classpath as target/classes should be there. Hopefully knowing what may cause the problem will help you to home in on an arrangement that reproduces it.

**Comment by StevenPG** [comment]
So hopefully this still the right place to chase the issue, but I am able to clear the error by removing 

`<dependency>`
`	<groupId>org.springframework.boot</groupId>`
`	<artifactId>spring-boot-starter-data-jpa</artifactId>`
`</dependency>`

I cut the project down to only the roots, and if I remove this dependency it builds properly. Application properties contains the correct datasource components that worked properly just a week ago.

Is there a better place I can chase down those specific resource and entityManager errors regarding the data-jpa starter?

I should mention I can build normally in an IDE with STS, but attempting to build on CLI or on the remote server are what bomb out.

**Comment by wilkinsona** [comment]
This is the right place. Can you turn what you've got into a small sample that we can run and reproduce the problem?

**Comment by StevenPG** [comment]
Alright I was able to knock the project into it's smallest pieces. Attaching here:
[whacky-pom.zip](https://github.com/spring-projects/spring-boot/files/2434437/whacky-pom.zip)

**Comment by StevenPG** [comment]
Sorry, I overlooked that. But yeah that should create the same issue. Let me reproduce that here as well.

**Comment by StevenPG** [comment]
I can verify that the same issue occurs when switching to an embedded H2.

`[ERROR]   PipelineVersionTrackerApplicationTests.contextLoads » IllegalState Failed to l...`

Alterations from the zip on my end are updating the application.properties to 

`spring.datasource.url=jdbc:h2:file:/data/sample`

and adding the following to the pom

`		<!-- https://mvnrepository.com/artifact/com.h2database/h2 -->`
`<dependency>`
`    <groupId>com.h2database</groupId>`
`    <artifactId>h2</artifactId>`
`    <version>1.4.197</version>`
`    <scope>test</scope>`
`</dependency>`

**Comment by wilkinsona** [comment]
This looks like a bug in Surefire to me. When the build is run with `-f ./pom.xml` that paths in the manifest of the Surefire Booter jar have extraneous `/./` segments in their paths:

```
file:/Users/awilkinson/Downloads/whacky-pom/./target/test-classes/
file:/Users/awilkinson/Downloads/whacky-pom/./target/classes/
```

These prevent the ClassLoader from returning `file:/Users/awilkinson/Downloads/whacky-pom/./target/test-classes/ ` as a classpath root. When launched with `-f pom.xml` or without any `-f` argument at all, the `/./` segments are not there:

```
file:/Users/awilkinson/Downloads/whacky-pom/target/test-classes/
file:/Users/awilkinson/Downloads/whacky-pom/target/classes/
```

With this configuration, the app class loader is able to return `file:/Users/awilkinson/Downloads/whacky-pom/target/test-classes/` as a classpath root.

This difference in behaviour is out of Spring Boot's control and I don't think there's anything that we can do to work around it. If you'd like to pursue this, I'd recommend raising a Surefire issue and, in the meantime, using `-f pom.xml` rather than `-f ./pom.xml`.
