### ISSUE TITLE
depend on major dependency versions when working on a major spring boot release.

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-boot#14647]
I am facing an issue that, I am using spring boot 2.0.0, and spring boot 2.0.0 uses hibernate 5.2.14. 

According to: http://central.maven.org/maven2/org/springframework/boot/spring-boot/2.0.0.RELEASE/spring-boot-2.0.0.RELEASE.pom:

```
<groupId>org.hibernate</groupId>
<artifactId>hibernate-core</artifactId>
<version>5.2.14.Final</version>
<scope>compile</scope>
```

And because hibernate 5.2.14 not a majro release, it might contains breaking changes, for example; this issue https://hibernate.atlassian.net/browse/HHH-12329 that hibernate team decided to return the original behaviour - with a flag - in version 5.2.17 https://hibernate.atlassian.net/browse/HHH-12454.

So, my suggestion is, for major spring boot releases, to pick major releaes for its dependices even if it is a little bit out-dated.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we do not want to stay on outdated versions of our dependencies as it means that users will miss out on bug fixes and possibly be exposed to security vulnerabilities unnecessarily. Our policy is that maintenance releases of Spring Boot will pick up new maintenance releases of our dependencies. For example, Spring Boot 2.0.x releases will pick up Hibernate 5.2.x releases but will not upgrade to Hibernate 5.3.x. For major releases of Spring Boot we will pick up the latest release in a new major version line of our dependencies. For example, Spring Boot 2.1 has upgraded to Hibernate 5.3.x (5.3.6 at the time of writing).
