### ISSUE TITLE
Transactions not working with Spring data mongodb 2.1.0.RELEASE

### ISSUE THREAD

**Issue by BadrDRAIFI** [spring-projects/spring-boot#14644]
Transactions not working with Spring data mongodb 2.1.0.RELEASE ( Lovelace-RELEASE & Spring boot 2.0.5-RELEASE ) because it's compiled against java driver 3.6.4 while Mongodb 4 requires 3.8.2 driver : ClientSession been moved from mongodb.session.ClientSession to mongodb.client.ClientSession

**Comment by philwebb** [comment]
Spring Boot 2.0.x does not support Spring Data Lovelace. You'll need to wait for Spring Boot 2.1 which upgrades both Spring Data MongoDB and the driver.

**Comment by BadrDRAIFI** [comment]
Thanks, now I see. By the way this was not mentioned in the reference docs of spring data Mongo : https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/
