### ISSUE TITLE
Clarify conversion system in Appendix 

### ISSUE THREAD

**Issue by vilhelm-persson-viper** [spring-projects/spring-boot#14645]
The unit for `server.connection-timeout` is unclear in the documentation. 
Earlier version of the documentation stated milliseconds. 
All other properties in `application.properties` are given as seconds. 
In version 2.0.4 the value need to be in milliseconds in order for Tomcat to handle the value correctly. 

The issue can be solved by
* indicating in documentation that the value should be in milliseconds
* use seconds in the property file and in the Tomcat and other server configuration property classes convert the second value to milliseconds or the unit the server need.

**Comment by philwebb** [comment]
@vilhelm-persson-viper As of 2.0 all time based values have been migrated to `Duration` types. There's some [documentation about the conversion system](https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#boot-features-external-config-conversion-duration). Perhaps we need an additional call-out in the configuration properties index.

Out of interest, are you talking about the reference documentation, the javadoc or the tooling support that IDE's provide for `application.properties` ?

**Comment by vilhelm-persson-viper** [comment]
I was referring to documentation in [Appendix A. Common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html).

I changed my property from 65000 to 65s in application.properites and it worked fine.

I agree that this is a much better solution than stating that all values should be given in a specific unit.

I read about the change to `Duration` in 2.0 but did not understand that that aslo applied to the values in the property file.

Thanks for the explanation.
This can be closed or kept as an minor issue for the documentation.

**Comment by snicoll** [comment]
I don't think the appendix is the right place for that stuff. We already have [a dedicated section on duration support](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion-duration)

> I read about the change to Duration in 2.0 but did not understand that that aslo applied to the values in the property file.

What specific section are you referring to? If that wasn't clean it also applied to configuration, I think that's probably the right place to update the documentation

**Comment by vilhelm-persson-viper** [comment]
I read about the change in the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes).
And now when i re-read the notes it state that it is for the _Existing properties_ and an example string `10m`, but since the rest of the text referred to @DurationUnit I did not connect it to the changes in property file.

I agree that the the documentation in [Converting durations](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion-duration) is good but I guess what I am missing is the information that the the text applies to the properties in Appendix A.
Currently the text state thet _If you expose a java.time.Duration property_, but since there are no types in the Appendix A documentation the connection is hard to understand.

If possible add a reference from _Apendix A_ to the _Converting duration_ section.

**Comment by philwebb** [comment]
I think a small TIP at the top of appendix C would be worthwhile. Just a quick note to briefly cover the units we support.
