### ISSUE TITLE
use log4j2 can't access actuator/logfile

### ISSUE THREAD

**Issue by pkptzx** [spring-projects/spring-boot#14640]
use log4j2 can't access actuator/logfile

u example can't access actuator/logfile too.

**Comment by philwebb** [comment]
The `LogFileEndpoint` should just surface a standard file, regardless of which logging system writes it. Have you set the `management.endpoint.logfile.external-file` property? If so, please provide a small sample application that we can download and run that shows the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
