### ISSUE TITLE
Allow to specify environment variables via conf file for fully-executable jars

### ISSUE THREAD

**Issue by mmanciop** [spring-projects/spring-boot#14662]
With many APM tools it is useful to provide additional configuration in the environment of Java processes. Unfortunately, fully-executable jars do not currently have an easy way to add properties to the environment.

Ideally, one would have a `JAVA_ENV` property in the `<executable-file-minus-jar>.conf` file and have the default embedded script put the values in the environment of the Java process.

With multiple variables, the `JAVA_ENV` variable should probably be quotes within single quotes.

**Comment by philwebb** [comment]
I think you can [use `JAVA_OPTS` for this](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-script-customization-when-it-runs). You should be able to set a [`-Dproperty=value`](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html#BABDJJFI) option to put a value into Java's system properties.

Does that work for you, or do you need something else?

**Comment by wilkinsona** [comment]
The conf scripts is sourced by the launch script. Can't you just set the necessary environment variables in the conf script and they'll be picked up by the application's process?

**Comment by mmanciop** [comment]
@wilkinsona does not work, because the way the launch script is structured, its own environment is *not* propagated to the process running the executable jar when running as an init.d script. The only case where the environment seems to be propagated is when running the jar as `./my-jar.jar`.

**Comment by wilkinsona** [comment]
I think it’s a bit soon to say it does not work. We may need some tweaks to the launch script (preserving the environment when calling `su`, for example), but I’m not yet convinced that we need to introduce our own mechanism to achieve something that’s already part of Linux.

I think a good first step here would be to add some tests to the launch script integration tests that verify what currently works with init.d.

**Comment by mmanciop** [comment]
@wilkinsona I am looking forward to a better solution :-)

For the record: passing the ‘—preserve-environment’ flag AFAIk will pass to the Java process every environment property of the parent process,l such as “JAVA_OPTS”, which sounds pretty dangerous to me. But, at least, ‘su —preserve-environment’ is consistent with the ‘run’ action of the script, so there’s that.

**Comment by mmanciop** [comment]
Spoke to soon about “we cannot begin to guess”. In the age of Google, guess is overrated:
* https://stackoverflow.com/questions/5241743/how-do-i-use-the-java-opts-environment-variable . Admittedly this case should not be an issue in Spring boot as Tomcat is bootstrapped differently, but it is a proof point that ‘JAVA_OPTS’ seems to be an overloaded environment property.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
