### ISSUE TITLE
ReactiveWebServerApplicationContext.getHttpHandler() causes early bean initialization

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#14666]
The config is like this:

```java
@EnableIntegration
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public DirectChannel channel1() {
        return new DirectChannel();
    }

    @Bean
    public DirectChannel channel2() {
        return new DirectChannel();
    }

    @Bean // remove this bean to fix Transformer creation
    public JavaTimeModule timeModule() {
        return new JavaTimeModule();
    }

    /**
     * This method depends on object mapper, which is not yet configured (with module above) when
     * Spring DI is trying to instantiate transformer.
     *
     * Useful debug points:
     * {@link org.springframework.beans.factory.support.DefaultListableBeanFactory#getBeansOfType(Class, boolean, boolean)}
     * {@link org.springframework.integration.config.annotation.TransformerAnnotationPostProcessor#createHandler(Object, Method, List)}
     *
     */
    @Bean
    @Transformer(inputChannel = "channel1", outputChannel = "channel2")
    public AbstractPayloadTransformer transformer(ObjectMapper dependency) {
        return new AbstractPayloadTransformer<Object, Object>() {
            @Override
            protected Object transformPayload(Object payload) {
                return payload;
            }
        };
    }
}
```

But Spring Integration is not relevant here at all.

The main point that we have some Jackson `Module` bean definition and other one depends on the `ObjectMapper` auto-configured in the mentioned `JacksonAutoConfiguration`.

The `JacksonAutoConfiguration` has the code like this:

```java
@Bean
@ConditionalOnMissingBean
public Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder(
      List<Jackson2ObjectMapperBuilderCustomizer> customizers) {
   Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
   builder.applicationContext(this.applicationContext);
   customize(builder, customizers);
   return builder;
}
```

That `customize()` calls a

```java
Collection<Module> moduleBeans = getBeans(this.applicationContext,
      Module.class);
```
eventually.

This is really inappropriate to call `getBeansOfType()` from the other bean definition: it's too early to instantiate all the beans in the application context.

I wonder why `ObjectProvider<Module>` is not used as a dependency for that `jacksonObjectMapperBuilder` bean definition...

For more info see https://github.com/spring-projects/spring-integration/issues/2565

**Comment by artembilan** [comment]
@philwebb , thanks for the quick turn around, but I don't think that this fixes our original problem with the `JacksonAutoConfiguration` and its call for the `BeanFactoryUtils.beansOfTypeIncludingAncestors(beanFactory, type)` from the `jacksonObjectMapperBuilder` bean definition.
What is the problem to do that via `ObjectProvider<Module>` method argument injection instead?

**Comment by snicoll** [comment]
@philwebb I am not sure I get the history of this issue either. This is the single call to the variant that allows eager init so perhaps we should change it to the one that allows to skip eager inits? 

This wouldn't force factory beans that do not expose the type though.

**Comment by wilkinsona** [comment]
@artembilan Injecting `ObjectProvider<Module>` would be a point solution for a broader problem. Phil's change should benefit any type of bean that was previously being created eagerly via `HttpHandler`. I would guess that the post-processing of `@Transformer` methods is complicating things further. We'll need to try the sample again and see what's going on. I assume you've tried it with a Boot snapshot and the problem still occurs?

**Comment by philwebb** [comment]
@artembilan Can you also provide some more details of what we should do with sample? It runs, but I'm not sure what to look at.

**Comment by artembilan** [comment]
I confirm that with this fix the mentioned sample works as expected:
```
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-webflux:2.1.0.BUILD-SNAPSHOT'
    compile 'org.springframework.boot:spring-boot-starter-integration:2.1.0.BUILD-SNAPSHOT'
}
```
and I did this change in the code:
```
public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = SpringApplication.run(Application.class, args);
        Map<String, EventDrivenConsumer> beansOfType = applicationContext.getBeansOfType(EventDrivenConsumer.class);
        System.out.println(beansOfType);
        applicationContext.close();
}
```
The output is pretty good:
```
10-03 10:59:59.289  INFO 11608 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-10-03 10:59:59.289  INFO 11608 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {:application.transformer.transformer} as a subscriber to the 'channel1' channel
2018-10-03 10:59:59.289  INFO 11608 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'application.channel1' has 1 subscriber(s).
2018-10-03 10:59:59.289  INFO 11608 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started application.transformer.transformer
2018-10-03 10:59:59.409  INFO 11608 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2018-10-03 10:59:59.412  INFO 11608 --- [           main] com.github.fred84.Application            : Started Application in 1.635 seconds (JVM running for 2.26)
{_org.springframework.integration.errorLogger=_org.springframework.integration.errorLogger, application.transformer.transformer=application.transformer.transformer}
```

So, I think we are good so far, however we still need to revise our usage for the `BeanFactory.getBeansOfType()` whenever it is called from other beans definitions. If we do this, we really cause an eager initialization as @snicoll mentioned above.

Thank you all for the help!

**Comment by wilkinsona** [comment]
The use of `getBeansOfType()` is only a problem if it's done very early during refresh. That was the case previously due to when the `HttpHandler` bean was being created. Since Phil's fix, it's no longer the case. As Phil said above, calling it from a `@Bean` method is no different to in terms of the initialisation it'll trigger to injecting the dependency or injecting an `ObjectProvider` and the calling it. In short, I don't think we need to change our usage of `getBeansOfType()`.

We do, however, need to make a change to the use of volatile fields in `ReactiveWebServerApplicationContext` as there's a race condition where the handler could, in theory, be initialised twice.

**Comment by snicoll** [comment]
> if we do this, we really cause an eager initialization as @snicoll mentioned above.

I am afraid I sent you in the wrong direction. And while I was typing, Andy wrote a fully summary so I'll just refer to that :)

**Comment by artembilan** [comment]
OK. So, looks like we are all good then! 😄 

Thank you again!

**Comment by philwebb** [comment]
I'm going to refactor this a little because @wilkinsona pointed out we're no longer thread safe.
