### ISSUE TITLE
Reinstate META-INF/maven/${groupId}/${artifactId}/pom.xml in published jar files

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14672]
Somewhere between 2.0.0.M6 and 2.0.0.RELEASE the spring-boot jars stopped having their pom.xml included:

```
$ jar -tvf ~/.m2/repository/org/springframework/boot/spring-boot/2.0.0.RELEASE/spring-boot-2.0.0.RELEASE.jar | grep pom
$ jar -tvf ~/.m2/repository/org/springframework/boot/spring-boot/2.0.0.M6/spring-boot-2.0.0.M6.jar | grep pom
   104 Mon Nov 06 05:56:56 GMT 2017 META-INF/maven/org.springframework.boot/spring-boot/pom.properties
 13521 Mon Nov 06 05:55:14 GMT 2017 META-INF/maven/org.springframework.boot/spring-boot/pom.xml
```

Since including the pom.xml is a standard feature of the Maven JAR plugin, it seems like this might be unintended. Maybe something to do with the `maven-flatten-plugin` (but that first showed up in 2.0.0.M4)?

**Comment by wilkinsona** [comment]
The pom is there in RC2 as well so it seems to have disappeared due to [something that changed between RC2 and RELEASE](https://github.com/spring-projects/spring-boot/compare/v2.0.0.RC2...v2.0.0.RELEASE).

**Comment by dsyer** [comment]
Looks like probably this: https://github.com/spring-projects/spring-boot/blob/84c8f38368feb7369dec3a00729159f2fb82b6ce/spring-boot-project/spring-boot-parent/pom.xml#L602

**Comment by wilkinsona** [comment]
I think that one affects the manifest. It's this one that's switching off the pom I think: https://github.com/spring-projects/spring-boot/blob/84c8f38368feb7369dec3a00729159f2fb82b6ce/spring-boot-project/spring-boot-parent/pom.xml#L600

**Comment by dsyer** [comment]
Yes. Part of this: https://github.com/spring-projects/spring-boot/issues/11994 (although it looks like maybe unrelated collateral damage to me).

**Comment by wilkinsona** [comment]
Removing that line restores the pom and doesn't seem to make any difference to the manifest. This is 2.0.5.RELEASE:

```
Manifest-Version: 1.0
Implementation-Title: Spring Boot
Automatic-Module-Name: spring.boot
Implementation-Version: 2.0.5.RELEASE
Built-By: Spring
Created-By: Apache Maven 3.5.4
Build-Jdk: 1.8.0_141
```

And this is 2.0.x with that line removed:

```
Manifest-Version: 1.0
Implementation-Title: Spring Boot
Automatic-Module-Name: spring.boot
Implementation-Version: 2.0.6.BUILD-SNAPSHOT
Built-By: Spring
Created-By: Apache Maven 3.5.4
Build-Jdk: 1.8.0_181
```

**Comment by wilkinsona** [comment]
I suspect it's collateral damage too. Flagging for team attention just in case I'm overlooking something.

**Comment by philwebb** [comment]
I think I removed it because it seemed a little unnecessary and I wanted to align with what Framework does. Do we need them back for a specific reason?

**Comment by dsyer** [comment]
> Do we need them back for a specific reason?

I was just surprised not to see them since they are "standard". Also I assert their presence in tests in the thin launcher, but I can change that if I have to.

**Comment by philwebb** [comment]
I think I'd rather keep them out to align with the jars published by Spring Framework. I guess the build system might play a big part in whether they are there or not. Maven probably adds them, Gradle probably doesn't.

Another reason not to add them back is because we flatten then and remove a few some bits. I've no idea if the flattened or orginal POM gets added, but its certainly easier our end to simply leave them out.
