### ISSUE TITLE
2.1.0.M4 Release Notes Typo

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#14683]
The 2.1.0.M4 Releases Notes state:

```
@SpringBootTest(randomPort = true) can now generate a separate random port for the management server.
```

`randomPort` is not a property in the `SpringBootTest` annotation.

I think this is just a typo and `@SpringBootTest(randomPort = true)` should instead be `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)`.

**Comment by wilkinsona** [comment]
Thanks. I've updated the release notes.
