### ISSUE TITLE
Make devtools set `spring.messages.reloadable=true`

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#14699]
Devtools should set `spring.messages.reloadable=true` when it's active, see #13377

**Comment by philwebb** [comment]
Yeah, I think that would make sense.

**Comment by wilkinsona** [comment]
With some regret, we've decided to revert this change. The approach taken in #13377 isn't quite right and enabling it by default in DevTools causes some problems that can't be easily addressed in the time available.
