### ISSUE TITLE
Allow construction of HttpTrace objects from custom HttpTraceRepository implementations

### ISSUE THREAD

**Issue by ferstl** [spring-projects/spring-boot#14726]
The spring-boot-actuator allows writing custom `HttpTraceRepository` instances. However, with the current implementation of the `HttpTrace` class it is impossible to do that properly. The reason is that neither the `HttpTrace` class nor its internal classes provide any public constructor. This prevents a proper implementation of `HttpTraceRepository#findAll()`.

In https://github.com/spring-projects/spring-boot/pull/14725 I proposed the changes to create `HttpTrace` objects from other packages than `org.springframework.boot.actuate.trace.http`. I do also think that it should be possible to deserialize `HttpTrace` objects from their JSON representation since these objects are also serialized to JSON.

I'm willing to continue working on the PR if you have any suggestions for improvements.

**Comment by wilkinsona** [comment]
Thanks for opening the issue.

> This prevents a proper implementation of `HttpTraceRepository#findAll()`

What do you consider to be a proper implementation? Boot's own `InMemoryHttpTraceRepository` implements `findAll`without using any package-private API.

Can you please clarify exactly what you are trying to do? From #14725, I think I understood that you're trying to write an `HttpTraceRepository` that persists `HttpTrace` instances somehow and then needs to recreate them, but I'd like to be certain.

> I do also think that it should be possible to deserialize HttpTrace objects from their JSON representation since these objects are also serialized to JSON.

I wouldn't encourage trying to use `HttpTrace` on the client side as it promotes coupling between the client and the server. That said, if we make it possible to create `HttpTrace` instances via public API, then creation from JSON will be possible without any further changes. It may require use of a mixin or custom serialiser, but it will be possible.

**Comment by ferstl** [comment]
> Can you please clarify exactly what you are trying to do? From #14725, I think I understood that you're trying to write an HttpTraceRepository that persists HttpTrace instances somehow and then needs to recreate them, but I'd like to be certain.

Yes, exactly. I need to implement a custom `HttpTraceRepository` that persists all requests and responses for compliance reasons. In order to implement the `findAll()` method of my custom repository correctly I need to be able to re-construct the persisted `HttpTrace` objects. This is impossible with the current implementation.

> I wouldn't encourage trying to use HttpTrace on the client side as it promotes coupling between the client and the server. That said, if we make it possible to create HttpTrace instances via public API, then creation from JSON will be possible without any further changes. It may require use of a mixin or custom serialiser, but it will be possible.

I am persisting the `HttpTrace` objects as JSON and for my purpose it would be convenient to just deserialize it again without writing a custom deserializer. I think it would also add some symmetry between serialization and deserialization. But I would also be fine with a public API to construct `HttpTrace` objects.

**Comment by wilkinsona** [comment]
Thanks for the confirmation. Do [these changes](https://github.com/wilkinsona/spring-boot/commit/34dfb2dba54f3f0fdbc94ddd46e35bddd28588cf) give you the foundation that you need to build the functionality that you'd like?

**Comment by ferstl** [comment]
Looks good!

**Comment by wilkinsona** [comment]
Thanks for taking a look. I've labelled this one for team attention so we can discuss the changes and, if everyone is happy with them, which release they should go in.
