### ISSUE TITLE
Cannot set enableLoggingRequestDetails via WebFluxConfigurer

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-boot#14723]
I tried adding:

```java
@Configuration
static class WebConfig implements WebFluxConfigurer {

	@Override
	public void configureHttpMessageCodecs(ServerCodecConfigurer configurer) {
		configurer.defaultCodecs().enableLoggingRequestDetails(true);
	}
}
```
However it gets overridden from the `CodecsAutoConfiguration` which uses the value from `HttpProperties#isLogRequestDetails()` but I have not set that property. Perhaps the `logRequestDetails` property should return `Boolean`, so it's possible to check if it was explicitly set, and if not then leave it to whatever it is already set to?

**Comment by philwebb** [comment]
We discussed this a bit on the call and we're wondering if our configurer should rub before the custom one.

**Comment by wilkinsona** [comment]
The theory is that if our configured is ordered (with zero, probably) it will run before any user-provider configured that's using the default order of lowest precedence. This would mean that the user's configured overrides the value set by ours while avoiding the need for a custom condition or for the property to be a `Boolean` which would cause the metadata to lose the default value.

**Comment by rstoyanchev** [comment]
Not that the default value in the Spring Framework is likely to change, but isn't cleaner in any case to have for Boot to have no impact on this, unless the property was set? And leave whatever default is already in place vs indirectly enforcing one.

**Comment by wilkinsona** [comment]
Boot's configuration property metadata describes the default value that Boot will apply if you don't configure it. To ensure that default is honoured, it's better if we always apply it. What we need to do is apply it in a way that allows the user to override it with programatic configuration like you've shown above.

**Comment by mbhave** [comment]
@wilkinsona That makes sense to me. It's also consistent with some what some [other customizers](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/UndertowWebServerFactoryCustomizer.java#L99) do.
