### ISSUE TITLE
WebFluxAutoConfiguration ignores spring.resources.cache.cachecontrol

### ISSUE THREAD

**Issue by astiob** [spring-projects/spring-boot#14724]
#10514 added a `spring.resources.cache.cachecontrol` application property in addition to `spring.resources.cache.period` to allow for fine-grained control of the Cache-Control HTTP response header. Unfortunately, support for this property was only added to `WebMvcAutoConfiguration` but not to `WebFluxAutoConfiguration`, even despite WebFlux being mentioned in the discussion. As a result, WebFlux still honours only `spring.resources.cache.period` and ignores the new property completely.

**Comment by ayudovin** [comment]
`ResourceHandlerRegistry` from spring-webflux has only method `setCacheControl` unlike `ResourceHandlerRegistry` from spring-webmvc. `ResourceHandlerRegistry` from spring-webmvc has two methods `setCachePeriod`  and `setCacheControl`.
In such case we should choose which property has priority for webflux :   `spring.resources.cache.cachecontrol` or `spring.resources.cache.period`
@philwebb  Could you give any advice ?

**Comment by bclozel** [comment]
`cacheControl` takes precedence in the `WebContentGenerator` implementation, so I think `cacheControl` should take precedence as well in WebFlux. We can try and convert the cache period configuration into a proper cache control value, `CacheControl.maxAge` if positive, `CacheControl.noStore` if zero.

**Comment by philwebb** [comment]
Closing in favor of PR #14741
