### ISSUE TITLE
Support ConfigurationProperties BindHandler advisors

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14745]
Spring Cloud Stream have the concept of user supplied default values. The idea is that users may defined per-binder properties, but also "default" properties that should apply to every binder.

For example, the user might define the following:

```
spring.cloud.stream.default.content-type=text/plain
spring.cloud.stream.bindings.input.content-type=application/json
```

In this example, `spring.cloud.stream.bindings.input.content-type` would be `application.json` because it's explicitly defined and any other name (e.g. `spring.cloud.stream.bindings.output.content-type`) would be `text/plain` because the user has defined a default fallback.

Their existing code is quite complicated because it attempts to merge values manually, it also needs to call `.bind` twice. See [EnvironmentEntryInitializingTreeMap](https://github.com/spring-cloud/spring-cloud-stream/blob/60b6f02a499aa45333850f3b8ec79795f46f68f0/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/EnvironmentEntryInitializingTreeMap.java#L121) and [BindingServiceProperties](https://github.com/spring-cloud/spring-cloud-stream/blob/60b6f02a499aa45333850f3b8ec79795f46f68f0/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceProperties.java#L160) for the existing implementation. What they really need is hooks that would allow them to introduce this concept without needing to do so much work themselves.

**Comment by spencergibb** [comment]
Spring cloud kubernetes has similar requirements.

**Comment by philwebb** [comment]
One idea for how to do this is here: https://github.com/philwebb/spring-boot/commits/gh-14745

**Comment by snicoll** [comment]
That rings a bell and we've discussed something similar at the team meeting. Relates to #7986 ?
