### ISSUE TITLE
ConditionalOnProperty should allow checking if boolean property is present

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#14746]
For boolean properties, `@ConditionalOnProperty` can't be used to check if the property has been configured. If the property is set to `false`, `ConditionalOnProperty` will not match. At the moment you can only match non-null values that are not `false`.

**Comment by philwebb** [comment]
You mean you want `@ConditionalOnProperty("foo.bar")` to match both `foo.bar=true` and `foo.bar=false` but not match if `foo.bar` is missing?

**Comment by philwebb** [comment]
Perhaps we should replace `matchIfMissing` with an enum called `having` that could be 
`NON_FALSE_VALUE`, `ANY_VALUE` or `NO_VALUE`?

So you could then write `@ConditionalOnProperty(name="foo.bar", having=Match.ANY_VALUE)`

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/commit/b18751ebd941b75a322717464ba22c8256c6cdc4

**Comment by philwebb** [comment]
We discussed this on the call and decided we probably shouldn't add any additional complexity to the annotation at this time. Using a custom condition seems like the best compromise.
