### ISSUE TITLE
Stop binding Flyway directly to the environment

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14776]
`FlywayCalback` is deprecated. We should also deprecate it as we're handling both `Callback` and `FlywayCallback` at the moment.

See also #14775

**Comment by wilkinsona** [comment]
I thought about this when I implemented the upgrade and I'm not sure that we need to do anything more. If someone uses `FlywayCallback` they'll get the deprecation warning from Flyway. Migrating to `Callback`, as the warning from Flyway recommends, will resolve the problem. What did you have in mind, @snicoll?

**Comment by snicoll** [comment]
Flagging the property as `deprecated` in the metadata and move any test that uses that stuff to `@Deprecated` so that we can identify those easily when start 2.2.

I used the wrong issue type again, should have been task, sorry.

**Comment by snicoll** [comment]
So both `setter` are deprecated and that's for the better as they allow you to specify an instance and there's no way you can do that via application.properties.

I think we should reconsider stop binding `Flyway` directly to the environment as we contribute properties we just can't specify.
