### ISSUE TITLE
For better compatibility with Flyway 5.1, avoid calling setFlywayCallback when flywayCallbacks is empty

### ISSUE THREAD

**Issue by emichalsky** [spring-projects/spring-boot#14775]
Having migrated my Spring Boot Application to version 2.0.5, using Flyway version 5.1.4,
I get the WARN message 

"WARN localhost-startStop-1 o.f.c.Flyway:53 - Flyway.setCallbacks(FlywayCallback) has been deprecated and will be removed in Flyway 6.0. Use Flyway.setCallbacks(Callback) instead."

upon application start, although I don't configure any callbacks.

Same problem as here: https://stackoverflow.com/questions/51905633/flyway-deprecation-message-logged-when-using-spring-boot-2

**Comment by wilkinsona** [comment]
We use Flyway 5.0 in 2.0.x where the method isn't deprecated and there's no alternative. I guess we just need to avoid calling `setCallbacks` when there are none. To be able to use `Callback` with Boot's auto-configuration, you'll have to wait for Spring Boot 2.1.

**Comment by emichalsky** [comment]
Thanks!
