### ISSUE TITLE
Spring-Boot web-app with Tomcat in Azure is missing X-Original-Host header behind Web Application Firewall

### ISSUE THREAD

**Issue by wpcata** [spring-projects/spring-boot#14771]
We have a simple web application (Spring-Boot 2.0.4) with Spring Security for user authentication in Azure behind a Web Application Firewall.

Using the default tomcat web server the automatic redirection of Spring Security to the login page fails always:
Instead of redirecting to a page based on the host from the Web Application Firewall ("...cloudapp.azure.com/login") Spring Security creates a link based on its local VM-IP ("192.168.../login").

The necessary information to configure Tomcat should be in the "X-Original-Host" header (added by the Web Application Firewall) of every incoming request but it is always missing (we logged out all received headers multiple times).
Packet captures on the VM in the same time show that the "X-Original-Host" is in fact always present though.

So it seems that the "X-Original-Host" header goes missing at some point with Tomcat.
(By the way: It is the only header which is present in packet captures but not in the app)

After configuring our project to use Jetty instead of Tomcat all problems are gone:
Every logged out request contains the "X-Original-Host".
(After respective Jetty configuration Spring Security creates correct redirection links)

**Comment by wilkinsona** [comment]
It sounds like this is working as [documented](
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server). Tomcat looks for `X-Forwarded-For` by default. AFAIK, it doesn’t do anything with `X-Original-Host`. If, after reading the docs, you believe that this should work as described, please explain why and we can re-open the issue.

**Comment by mmoehring** [comment]
Let me try to explain the issue in a reduced way:
We have a Spring Boot Application with a RestController which gets a request with a few headers.

- When using the default embedded tomcat, one of the headers is missing when reading them in the RestController.
- When switching to Jetty, nothing is missing, all headers are there.

The header which is missing is not one of the documented headers, so tomcat should not filter and it should not be missing.

**Comment by wilkinsona** [comment]
It sounds like a filter that runs after the `RequestLoggingFilter` is wrapping the request and hiding the header. I can't say what that may be or why it's apparently only happening with Tomcat from the information that's been provided thus far. I'm also unable to reproduce the behaviour you've described in a minimal application.

If you'd like us to spend some time taking another look at this, please take some time to provide a minimal sample (something that we can unzip or `git clone` and run) that reproduces the problem.

**Comment by mmoehring** [comment]
Thanks. We will strip down our application and provide a minimal sample. This may take a few days.

**Comment by mmoehring** [comment]
While switching back and forth between Jetty and Tomcat the described issue suddenly vanished and all Headers were visible without any changes (we know of) in the Tomcat version.
As we are not able the reproduce the issue at the moment, the issue can be closed.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
