### ISSUE TITLE
Stop relying on server customizer ordering for Tomcat metrics binding

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14784]
In 2.0, we added auto-configuration for Micrometer's `TomcatMetrics`. To publish metrics about HTTP sessions, `TomcatMetrics` requires the `Manager` from the `Context` of the embedded Tomcat server. It's not easy to get hold of the `Context` and then the `Manager` to be used by something that's returned from a `@Bean` method. The current auto-configuration looks like this: https://github.com/spring-projects/spring-boot/blob/a296a805c57a25425a97e080f8e1b23230d77418/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/web/tomcat/TomcatMetricsAutoConfiguration.java#L42-L73

It relies on the `WebServerFactoryCustomizer` being called before the `tomcatMetrics` `@Bean` method is called. This works, but it's not very pleasant. The `Manager` being optional in `TomcatMetrics` is also a benefit as it allows things to work when there's no embedded container, such as a `@SpringBootTest` using a mock web environment.

The requirement has come up again with publishing metrics for Jetty's thread pool. Following roughly the same pattern works but, without making Micrometer's `JettyThreadPoolMetrics` tolerate a `null` `ThreadPool`, tests with a mock web environment don't work. This was discovered by @izeye [here](https://github.com/micrometer-metrics/micrometer/issues/911#issuecomment-428840584).

I think we need a more robust way of making a bean conditional on an embedded web server. It's complicated at the moment by the fact that the embedded server is created in `onRefresh` which is called after condition evaluation has been performed. We could, perhaps, move the creation of the embedded web server earlier in refresh processing, but this would be quite a big change. It may allow the `WebServer` to be defined as a bean which could be quite nice.

**Comment by philwebb** [comment]
> It may allow the WebServer to be defined as a bean which could be quite nice.

`WebApplicationContext` has `getServletContext()` which we set during the refresh. Perhaps we can use that or something similar to it.

**Comment by wilkinsona** [comment]
I wonder if a `WebServerAware` callback might be a better option. It avoids the risk of defining a bean that can’t be used until a certain point in refresh processing.

**Comment by wilkinsona** [comment]
Neither approach works particularly well for binding Tomcat metrics. `TomcatMetrics` binds some meters based on Tomcat's MBeans. As such, it's useful with both embedded Tomcat and standalone Tomcat. If we move to a `WebServer` based approach, either as a bean or a callback, the standalone case won't work.

An event-based approach looks like it may work. [This branch](https://github.com/wilkinsona/spring-boot/tree/gh-14784) contains an implementation for binding Tomcat's metrics. I believe the approach should work for Jetty too.
