### ISSUE TITLE
Remove usages of BasicAuthorizationInterceptor

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#14798]
Hi,

due to the work on [SPR-17326](https://jira.spring.io/projects/SPR/issues/SPR-17326) there are quite some deprecation warnings now caused by BasicAuthorizationInterceptor. I would be willing to tackle that, but I want to sync first on the approach.

1. Deprecate `RestTemplateBuilder.basicAuthorization(String username, String password)`
2. Remove `RestTemplateBuilder.basicAuthorization(String username, String password)` all together
3. Stick to `RestTemplateBuilder.basicAuthorization(String username, String password)` and use `BasicAuthenticationInterceptor` underneath.

For options 1&2, I would include a new method `RestTemplateBuilder.basicAuthentication(String username, String password)` that uses the new `BasicAuthenticationInterceptor`. In order to stay compatible to the current behaviour, I'd like to pass UTF-8 as a charset here, but I'm also fine with sticking to ISO_8859_1 that is used on `HttpHeaders.setBasicAuth` underneath.

Option 1 would be a "softer" variant, but needs work in a later release to eventually remove the leftovers.
Option 2 would be the cleanest in terms of code, but also the hardest from a user perspective.
Option 3 would be probably the simplest, but naming-wise it's not consistent to the new class (authentication vs. authorization).

We could also go for Option 1&3 in order to have consistent naming, and to give users a soft way of migrating.

What do you think?

Cheers,
Christoph

**Comment by philwebb** [comment]
I noticed those the other day as well. I think option 1 might be safest, but I need to refresh my memory on that part of the code.

**Comment by dreis2211** [comment]
If the question about the encoding (UTF-8 vs. ISO_8859_1) is clarified, I'd be happy to provide a PR.

**Comment by snicoll** [comment]
@dreis2211 the framework team recommends that headers have to be encoded with `ISO-8859-1` and they actually changed that in 5.1 if you use this new implementation. So calling the 2 parameters arguments would align us. 

Do you still have time to work on a PR for this? RC1 is around the corner!

**Comment by dreis2211** [comment]
On my way.

**Comment by snicoll** [comment]
Let's continue the discussion on the PR. Thanks Christoph!
