### ISSUE TITLE
Customized compression configuration is EmbeddedServletContainerFactory gets overridden by ServerProperties.java 

### ISSUE THREAD

**Issue by wenjiezhang2013** [spring-projects/spring-boot#14803]
🐞 Bug report

Spring boot version: 1.5.16.

I have defined my own EmbeddedServletContainerFactory and provided the `compression` configuration properties like the following code:

```
@Bean
    public EmbeddedServletContainerFactory tomcatContainer() {
        final TomcatEmbeddedServletContainerFactory tomcatContainerFactory = new TomcatEmbeddedServletContainerFactory();
        tomcatContainerFactory.setPort(8080);

        final Compression compression = new Compression();
        compression.setEnabled(true);
        final String[] mimeTypes = {MediaType.APPLICATION_JSON_UTF8_VALUE};
        compression.setMimeTypes(mimeTypes);
        compression.setMinResponseSize(10);
        return tomcatContainerFactory;
    }
```
But when checking the response headers, I do not see `Content-Encoding` header, after spending some time on debugging this issue, I found my `compression` gets overridden by `ServerProperties.java`  at https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L214.

Here is my sample project to reproduce this issue:

https://github.com/wenjiezhang2013/spring-boot-compression-bug-demo

PR is here: https://github.com/spring-projects/spring-boot/pull/14801

**Comment by philwebb** [comment]
Closing in favor of PR #14801
