### ISSUE TITLE
Can not start spring application with webflux and websocket for ObjectPostProcessor is needed.

### ISSUE THREAD

**Issue by Macrame** [spring-projects/spring-boot#14810]
🎁 Enhancement

### Summary
\***************************
APPLICATION FAILED TO START
\***************************

Description:

A component required a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' in your configuration.

### Configuration
```
@Configuration
@EnableWebFluxSecurity
public class WebSecurityConfig {
    @Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
       ...
    }
   ...
}
```

```
@Configuration
public class WebSocketConfiguration {
    @Bean
    public HandlerMapping handlerMapping() {
        Map<String, WebSocketHandler> map = new HashMap<>();
        map.put("/websocket", new WebSocketMessageHandler());
        SimpleUrlHandlerMapping mapping = new SimpleUrlHandlerMapping();
        mapping.setUrlMap(map);
        mapping.setOrder(-1); // before annotated controllers
        return mapping;
    }

    @Bean
    public WebSocketHandlerAdapter handlerAdapter() {
        return new WebSocketHandlerAdapter();
    }
}
```
### Version
spring boot 2.0.5.RELEASE
io.spring.platform:platform-bom:Cairo-SR4
org.springframework.cloud:spring-cloud-dependencies:Finchley.SR1

### dependencies
...
compile("org.springframework.boot:spring-boot-starter-actuator")
compile("org.springframework.boot:spring-boot-starter-security")
compile("org.springframework.boot:spring-boot-starter-websocket")
...
### Solution

I tried again and found that it works well while using dependency of 'org.springframework:spring-websocket' instead of 'org.springframework.boot:spring-boot-starter-websocket'. In deed, spring-boot-starter-websocket depends on 'org.springframework:spring-webmvc' to case this issue. We can exclude 'org.springframework:spring-webmvc' to avoid it.

I suggest that spring-boot-starter-websocket does not depends on 'org.springframework:spring-webmvc' or there is another spring-boot-starter-webflux-websocket which depends on 'org.springframework:spring-webflux' instead of 'org.springframework:spring-webmvc'.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we don’t want to make any changes to the structure of the starters. We’ve improved the documentation in 
https://github.com/spring-projects/spring-boot/issues/14069.

**Comment by wilkinsona** [comment]
We don't want to change it because we don't want to have more starters than we need and we try to compose starters as much as possible. `spring-boot-starter-web` provides many components that are useful for the vast majority of applications building on the Servlet stack that want to use WebSockets. That includes `spring-webmvc` as, in our experience, it's unusual for a web application to only being using WebSockets.

**Comment by Macrame** [comment]
By the way, I can't find any section to describe this important point. If a user starts a spring application depending on webflux, spring-security and spring-boot-starter-websocket but forgets to exclude spring-mvc he will get failure.

**Comment by bclozel** [comment]
@Macrame We did improve documentation on that in the issue duplicating this one. See: https://docs.spring.io/spring-boot/docs/2.1.0.BUILD-SNAPSHOT/reference/html/boot-features-websockets.html

**Comment by Evgen-Krasnenkov** [comment]
@bclozel hello. The link dosent work

**Comment by bclozel** [comment]
@Evgen-Krasnenkov I've updated the link. Thanks!
