### ISSUE TITLE
Configuration metadata for Map properties does not include their default value

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#14813]
The properties for Humio metrics export include a `Map<String, String>` property with a default value:

```
/**
 * Humio tags describing the datasource in which metrics will be stored. Humio tags
 * are a distinct concept from Micrometer's tags. Micrometer's tags are used to divide
 * metrics along dimensional boundaries.
 */
private Map<String, String> tags = new HashMap<>(
		Collections.singletonMap("name", "micrometer"));
```

This default is required to match the default in Micrometer's `HumioConfig`. The resulting configuration property metadata does not include the default value:

```
{
      "name": "management.metrics.export.humio.tags",
      "type": "java.util.Map<java.lang.String,java.lang.String>",
      "description": "Humio tags describing the datasource in which metrics will be stored. Humio tags are a distinct concept from Micrometer's tags. Micrometer's tags are used to divide metrics along dimensional boundaries.",
      "sourceType": "org.springframework.boot.actuate.autoconfigure.metrics.export.humio.HumioProperties"
},
```

I'm not sure if it's possible for the annotation processor to capture the default in the case and, even if it could, what form the default should then take in the JSON. However, it would be good to be able to offer something so that users are aware of the default.

The work in progress to add support for Humio is in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-14804).

**Comment by jkschneider** [comment]
@wilkinsona Would it help to add an intermediate type other than a `Map` that resembles a `Map`?

**Comment by snicoll** [comment]
There is no metadata for maps at all. Having said that, defaultValue is somewhat unrelated. 

There is no way to define a key value in this field at the moment. I am not sure what that would look like besides a nested Json object.

**Comment by wilkinsona** [comment]
A map with default entries is problematic as it makes it impossible to remove those entries without resorting to programmatic configuration. That alone is enough to make me believe that any configuration properties that are a map should be empty by default. If that's the case, the problem described in this issue goes away.
