### ISSUE TITLE
Auto-configure KairosDB metrics

### ISSUE THREAD

**Issue by jkschneider** [spring-projects/spring-boot#14821]
See https://github.com/micrometer-metrics/micrometer/issues/761.

**Comment by snicoll** [comment]
There are some tests missing for the config adapter

**Comment by jkschneider** [comment]
[Polished](https://github.com/micrometer-metrics/micrometer/commit/ee4ef0c0723d6eeedbf42b6ff0026b6a1d3254f8) Kairos configuration in `micrometer-spring-legacy` to align with text in Spring Boot 2.
