### ISSUE TITLE
EndpointId does not accept id with dash mark "-"

### ISSUE THREAD

**Issue by 391861737** [spring-projects/spring-boot#14827]
I'm working on an [issue](https://github.com/spring-cloud/spring-cloud-commons/pull/426)
 of spring-cloud, and got a tests failure which refers to the method : `org.springframework.boot.actuate.endpoint.EndpointId#of` it asserts the argument of the EndpointId's contructor should not contain the dash mark (which should be ALPHA_NUMERIC `[a-zA-Z0-9]+`). But obviously lots of endpoints in spring-cloud contains "-". 

Should this be considered as a REAL change and we should edit our codes everywhere that containing dash mark "-", or EndpointId#of should allow it?

**Comment by snicoll** [comment]
Let's add this use case to our discussion on #14773

**Comment by philwebb** [comment]
I've added this to #14773
