### ISSUE TITLE
Metrics for JMS ConnectionFactory

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#1485]
Currently the `DataSource` implemenations have some metrics applied (min, max, active, usage) it would be nice if there would also be metrics along these lines for a configured `ConnectionFactory` if that happens to be a pool like, for instance, [`PooledConnectionFactory`](http://activemq.apache.org/maven/apidocs/org/apache/activemq/pool/PooledConnectionFactory.html)

**Comment by snicoll** [comment]
It looks like we don't have much actual use cases for that (I only see the ActiveMQ support). Thoughts?

**Comment by snicoll** [comment]
I don't see a lot of data to process from that thing actually (besides ActiveMQ) so I am closing this issue.
