### ISSUE TITLE
Add properties to enable/disable Dropwizard metrics.

### ISSUE THREAD

**Issue by godzsa** [spring-projects/spring-boot#14852]
It would be a great idea to be able to enable/disable automatic Dropwizard metrics in Spring-Boot-Actuator. I am creating my own metrics, and don't want to see the ones Spring-Boot-Actuator automatically adds to Dropwizard. This could be done easily on `MetricsDropwizardAutoConfiguration.class`. Just introduce a property e.g. `spring.metrics.dropwizard.enabled: false` which modifies the default behavior.

**Comment by snicoll** [comment]
Thanks for the suggestion but we're not keen to add `enabled` flag when there is a [general-purpose feature to disable auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-disabling-specific-auto-configuration). 

In this particular theme, #13408 is also relevant.
