### ISSUE TITLE
Handle StepRegistry connect/read timeout deprecation

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14855]
The `read-timeout` and `connect-timout` of `StepRegistry` is deprecated in favour of configuring the client yourself.

Any registry that is a `StepRegistry` is affected. We expose two related properties for each implementation. We should figure out what we want to do with this.

**Comment by snicoll** [comment]
IMO, we have two choices here: 

* Either we cal the deprecated mapping method to the config object and those two properties should be deprecated
* Or, we don't call that mapping any longer and we do whatever is the recommendation in the auto-config

**Comment by snicoll** [comment]
Thanks Jon, Andy told me about that discussion and I believe that this is the same thing as the second option in my previous comment.

**Comment by wilkinsona** [comment]
I'm not sure that we can stop performing the mapping in 2.1 as it will be a breaking change for anyone who is using the auto-configured `…PropertiesConfigAdapter` `…Config` implementation to retrieve the connect or read timeout.

**Comment by wilkinsona** [comment]
We've decided to remove the mappings in the config adapters.

**Comment by wilkinsona** [comment]
Closing in favour of #14886.
