### ISSUE TITLE
Interceptor is added to SimpleUrlHandlerMapping in Boot 2.x wasn't in 1.5 causing unexpected execution and wrong response status

### ISSUE THREAD

**Issue by davideas** [spring-projects/spring-boot#14856]
Spring Boot 2.0.x and 2.1.0.M4

### Scenario is the following
Having a custom JwtInterceptor, I wanted to test _invalid_ endpoints but for which the mapping _matches_ the pattern (see below), like `.../api/v1/dkdk`, it is expected to respond with **404**. But having indeed an `AuthenticationException` thrown inside the `jwtInterceptor`, it responds with **500**.

###### Logs:
```
org.springframework.boot.web.servlet.support.ErrorPageFilter - Forwarding to error page from request [/api/v1/dkdk] due to exception [No JWT token found in request header]
...
org.springframework.web.servlet.DispatcherServlet - Exiting from "FORWARD" dispatch, status 500
```

###### The interceptor is added to the `InterceptorRegistry` as usual:
``` java
@Override
public void addInterceptors(InterceptorRegistry registry) {
    registry.addInterceptor(jwtInterceptor)
            .addPathPatterns(
                    "/api/v1/**"
            ).
            excludePathPatterns(
                    "/api/v1/auth/validateUsername/*",
                    "/api/v1/auth/login",
                    "/api/v1/auth/signup"
            );
}
```
Debugging the startup I verified that in Spring Boot 2 the interceptor is added to the list of interceptors of `SimpleUrlHandlerMapping` and of course _is executed_, but it shouldn't :exclamation: Indeed, with Boot 1.5.x _it is not_ and the mapping goes directly to `/error` with correct status code **404** .

### Global Exception Handler Advice annotated with `@RestControllerAdvice`
Moreover, I also verified that, if the request has a valid and mapped URL, like `/api/v1/auth/logout` and of course matches with the pattern, the `ExceptionHandlerAdvice` will catch the exception and respond with the Json body (I understood it, because it monitors the controller mappings), but how to manage invalid URLs to have Json body instead of 404 html page?
I tried to use `spring.mvc.throw-exception-if-no-handler-found=true` but it seems does not work either. we need to add also `spring.resources.add-mappings=false`.

Interesting thing is, still having the interceptor registered but not having anymore the basePackages (using only the `@RestControllerAdvice` annotation), the interceptor _is not executed_ and the 404 will be caught and presented as Json by the `ExceptionHandlerAdvice` supposing having a method for `@ExceptionHandler(NoHandlerFoundException.class)`.
But by removing the 2 lines in `application.properties`, it responds with **500** (because of the exception in the interceptor as previously stated).

> Something need to be fixed I believe.

**Comment by bclozel** [comment]
I think the behavior change can be traced back to a Spring Framework change in [SPR-16034](https://jira.spring.io/browse/SPR-16034). Interceptors are now also applied to resource handling, whereas they were not all applied in that case. This was problematic, for example, when collecting metrics (see #10335).

I guess in your case the interceptor is executed twice: once for the controller handlers, and another one when trying to match the requests against static resources.

I'm not sure about this particular use case, but here are a few ideas:

* add a request attribute to signal that the interceptor has been executed already and not run it twice
* map static resources handling to a different root (i.e. not `/`)
* disable static resources handling completely

Please let me know how this goes.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by davideas** [comment]
I got no time to try the proposed ideas. However, for the first one, there's no double execution: as said, I've debugged.
I will try the next days.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
