### ISSUE TITLE
Maven Plugin's documentation still refers to module layout that was removed in 2.0

### ISSUE THREAD

**Issue by pavelmorozov** [spring-projects/spring-boot#14854]
I have a problem with Spring Boot 2.0.5 and Spring Boot Maven plugin. I found I should report bug here on: 
https://docs.spring.io/spring-boot/docs/current/maven-plugin/issue-tracking.html

I cannot create the module jar file with:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<layout>MODULE</layout>
    	</configuration> 
</plugin>

```
Error says:

> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:repackage (default) on project module-test: Unable to parse configuration of mojo org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:repackage: Cannot convert 'MODULE' to Enum: No enum constant org.springframework.boot.maven.RepackageMojo.LayoutType.MODULE

Spring docs says MODULE should works https://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html

I was able to resolve by mention old version of spring-boot-maven-plugin 1.5.6

You can see sample application on https://github.com/pavelmorozov/spring-boot-maven-plugin-module/blob/master/pom.xml

**Comment by wilkinsona** [comment]
Support for the module layout was removed in Spring Boot 2.0 (https://github.com/spring-projects/spring-boot/issues/8107). Unfortunately, the updates to the Maven Plugin's documentation were missed so we can use this issue to sort that out. You should use a custom `LayoutFactory` instead.

**Comment by pavelmorozov** [comment]
Nice.

I hope to get the migration manual or how to build jar library with example. Until that time I will have to stay with 1.x
