### ISSUE TITLE
Provide support for deprecated auto-configuration classes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14860]
#14412 shows that we need a way to offer deprecated auto-configuration classes. Such classes would not need to actually contain configuration, but would still be valid when used as an `exclude` or and `@AutoConfigureBefore`/`@AutoConfigureAfter` value.

**Comment by philwebb** [comment]
Prototype work https://github.com/philwebb/spring-boot/tree/gh-14860

**Comment by mbhave** [comment]
This one looks similar: #6684

**Comment by wilkinsona** [comment]
We have no need for this at this time. Closing for now.
