### ISSUE TITLE
Nondeterministical behavior when launcing on Tomcat

### ISSUE THREAD

**Issue by iJadric** [spring-projects/spring-boot#14861]
When a Spring Boot application, containing a class that extends AbstractSecurityWebApplicationInitializer and a class annotated by @EnableWebSecurity that extends WebSecurityConfigurerAdapter,  is deployed on Tomcat, it will sometimes be deployed and started up normally, and sometimes will throw an IllegalStateException: "Duplicate Filter registration for 'springSecurityFilterChain'. Check to ensure the Filter is only configured once." Deleting the class that extends AbstractSecurityWebApplicationInitializer causes the application to be always deployed normally. Spring Boot version used is 2.0.3 and the jdk is Java 1.8.

**Comment by wilkinsona** [comment]
Thanks for the report, but this is out of Spring Boot's control. `WebApplicationInitializer` implementations are handled by Spring Framework. You can control their ordering by annotating your implementation with `@Order` or implementing `Ordered. It's also worth noting that there's no need to sub-class `AbstractSecurityWebApplicationInitializer` in a Spring Boot application as Spring Security will be configured for you.
