### ISSUE TITLE
Resource Versioning Handler not being called if actuator starter is included

### ISSUE THREAD

**Issue by iamareebjamal** [spring-projects/spring-boot#14897]
### Issue:
If actuator starter dependency is included in the project, the resource strategies stop working, for instance, GZip or Content Versioning strategies are not called. Even AbstractResourceHandler stops getting invoked. Removing the actuator starter dependency makes the config start working again. This is reproducible on a simple https://start.spring.io template (with thymeleaf, web and actuator starters) as well. This also gets resolved on downgrading to 2.0.5. Sample repo is provided below

### Sample Repo:
https://github.com/iamareebjamal/spring-boot-resource-versioning-bug

### Environment:
Spring Boot 2.0.6

**Comment by philwebb** [comment]
Thanks for the detailed report and for the sample application. I'm still digging into the root cause, but it looks like the problem might be related to the `@ConditionalOnMissingBean` on the `FilterRegistrationBean<ResourceUrlEncodingFilter> resourceUrlEncodingFilter()` method in `ThymeleafWebMvcConfiguration`.

In 2.0.5 running with debug reports:

```
   ThymeleafAutoConfiguration.ThymeleafWebMvcConfiguration#resourceUrlEncodingFilter matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.servlet.resource.ResourceUrlEncodingFilter; SearchStrategy: all) did not find any beans (OnBeanCondition)
      - @ConditionalOnEnabledResourceChain enabled (OnEnabledResourceChainCondition)
```

in 2.0.6

```
   ThymeleafAutoConfiguration.ThymeleafWebMvcConfiguration#resourceUrlEncodingFilter:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.boot.web.servlet.FilterRegistrationBean; SearchStrategy: all) found beans of type 'org.springframework.boot.web.servlet.FilterRegistrationBean' webMvcMetricsFilter (OnBeanCondition)
```

**Comment by philwebb** [comment]
Commit 64f04fceea461317e2afc04d66ff0e50140e28ed changed `resourceUrlEncodingFilter` from a concrete bean of type `ResourceUrlEncodingFilter` to a `FilterRegistrationBean`. The `@ConditionalOnMissingBean` doesn't check generics so it now matches when any other `FilterRegistrationBean` exists (for example, when actuator adds one for metrics).

**Comment by philwebb** [comment]
@iamareebjamal Until we can fix this, you can work-around the issue by adding the following to your `@SpringBootApplication` class:

```java

	@Bean
	public FilterRegistrationBean<ResourceUrlEncodingFilter> resourceUrlEncodingFilter() {
		FilterRegistrationBean<ResourceUrlEncodingFilter> registration = new FilterRegistrationBean<>(
				new ResourceUrlEncodingFilter());
		registration.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ERROR);
		return registration;
	}
```

**Comment by bclozel** [comment]
Should we reconsider #7475 ?

**Comment by wilkinsona** [comment]
It looks like it. An alternative would be to use a specific bean name when checking for a missing bean, but that feels more like a workaround than a long-term solution.
