### ISSUE TITLE
Incompatibility spring-security-OAuth2 with 2.0.6.RELEASE

### ISSUE THREAD

**Issue by becerriljc** [spring-projects/spring-boot#14899]
I CANT USE DEPENDENCIES 
spring-boot-starter-security
spring-security-oauth2

I HAD BACK TO 2.0.5

greetings!

**Comment by mbhave** [comment]
@becerriljc There is nowhere near enough information in this issue to understand the problem you're facing. Could you provide a minimalistic sample that we can run that reproduces the issue? Also, please see the section in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#oauth2) regarding the OAuth2 changes in Spring Boot 2.0.

**Comment by shaheerakhlaq** [comment]
@mbhave... Spring Security : Encoded password does not look like BCrypt

Spring Boot 2.0.6
Spring Security OAuth2 2.3.4

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by shaheerakhlaq** [comment]
> If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

1.5.12 code used on 2.0.6 and getting runtime error

URL: http://localhost:8080/oauth/token
Method Type: POST
Params
username: shaheer
password: shaheer
grant_type: password

Set header.. application/json

Authentication type: Basic Auth

**Comment by wilkinsona** [comment]
Thanks, but that still isn’t enough information. “runtime error” tells us almost nothing and without a way to reproduce whatever that error may be we can’t make any progress

@mbhave has already made a request and provided some advice:

> Could you provide a minimalistic sample that we can run that reproduces the issue? Also, please see the section in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#oauth2) regarding the OAuth2 changes in Spring Boot 2.0.

If you would like us to spend time trying to help you, please take the time to follow the requests and advice that we’ve already taken the time to offer.

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
