### ISSUE TITLE
New Binder API modifies property keys

### ISSUE THREAD

**Issue by juan-palacios** [spring-projects/spring-boot#14902]
Upgrading to Spring Boot `2.x` we've run into an issue where the new Binder API is changing the keys for the properties we define. That's a problem for us as some of our properties are defined as a `<PREFIX>.<TYPE>=<VALUE>` and if the key is modified we load the wrong information on startup.

I've attached a small project ([binder-test.zip](https://github.com/spring-projects/spring-boot/files/2494657/binder-test.zip)) which shows this behaviour:
```
Expected :{application/vnd.coffeescript.extensions=js, application/x-httpd-php=extensions=inc, text/javascript.executables=node}
Actual   :{applicationvnd.coffeescript.extensions=js, applicationx-httpd-phpextensions=inc, textjavascript.executables=node}
```
AFAICT the clean up is happening in [ConfigurationPropertyName#adapt](https://github.com/spring-projects/spring-boot/blob/v2.0.3.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/source/ConfigurationPropertyName.java#L490-L511)

**Comment by wilkinsona** [comment]
Thanks for the test that reproduces your problem. You need to use [bracket notation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding) to indicate to the configuration property infrastructure that a portion of the key should be left as-is:

> When binding to Map properties, if the key contains anything other than lowercase alpha-numeric characters or `-`, you need to use the bracket notation so that the original value is preserved. If the key is not surrounded by `[]`, any characters that are not alpha-numeric or `-` are removed.

In your specific case, your tests will pass when the properties are configured as follows:

```
environment.getPropertySources().addFirst(new MapPropertySource("application-default.properties",
        ImmutableMap.of(PREFIX + "[application/vnd.coffeescript.extensions]", "js", //Multiple dots; valid
                PREFIX + "[application/x-httpd-php=extensions]", "inc",             //= instead of .; skip
                PREFIX + "[text/javascript.executables]", "node")));                //Control; valid
```
