### ISSUE TITLE
META-INF/spring.factories: EnableAutoConfiguration should tolerate whitespace

### ISSUE THREAD

**Issue by pfoermer** [spring-projects/spring-boot#14903]
**Used Spring Boot Version:** 1.5.13.RELEASE

**Scenario:**
Provided a custom auto configuration definition in META-INF/spring.factories of the following form:
"org.springframework.boot.autoconfigure.EnableAutoConfiguration=FQNClassA, FQNClassB".

**Problem:** 
Spring failed to load the configuration class " FQNClassB", because no whitespace trimming was done. 

**Proposed improvement:**
As a java identifier can not have got any whitespace in it, whitespace trimming should be applied for a class token in EnableAutoConfiguration key.
In my opinion this would make a definition more robust, as whitespace mistakes are harder to review and this might be an unexpected behaviour from user perspective as whitespace is expected to be ignored.

**Comment by wilkinsona** [comment]
Thanks for the report. The code that reads the class names from `META-INF/spring.factories` is in `org.springframework.core.io.support.SpringFactoriesLoader` which is part of Spring Framework. If you'd like to pursue this, please open a [Spring Framework JIRA ticket](https://jira.spring.io/browse/SPR).

**Comment by pfoermer** [comment]
@wilkinsona Thank you for the hints. Created https://jira.spring.io/browse/SPR-17413.
