### ISSUE TITLE
Support for bare double dash in argument parsing of SpringApplication

### ISSUE THREAD

**Issue by mprimi** [spring-projects/spring-boot#14909]
I would like Spring Boot application to support guideline 10 of POSIX.1-2017 - Utility argument convention section: 

> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

The desired behavior is to recognize the `--` and leave all the arguments to the right of it alone.

Just for context: in `2.0.x` passing `--` to a SpringBoot application results in an error (sample trace below). The double dash is treated as an invalid option (whose name is zero-length) and there seems to be no way to configure this behavior.

```
java.lang.IllegalArgumentException: Invalid argument syntax: --
	at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75)
	at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90)
	at org.springframework.boot.DefaultApplicationArguments$Source.<init>(DefaultApplicationArguments.java:76)
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:42)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at com.netflix.genie.GenieAgentApplication.run(GenieAgentApplication.java:63)
```

**Comment by philwebb** [comment]
The `SimpleCommandLineArgsParser` is part of Spring Framework so I've raised [JIRA issue SPR-17416](https://jira.spring.io/browse/SPR-17416) for them to consider.

**Comment by mprimi** [comment]
@philwebb would you consider a feature request that completely turns off argument parsing?
(happy to open a separate issue, but not going to if you have the feeling it wouldn't fly).

**Comment by philwebb** [comment]
@mprimi You can already do that using the following:

```
SpringApplication application = new SpringApplication(MyApp.class);
application.setAddCommandLineProperties(false);
application.run(args);
```

**Comment by mprimi** [comment]
@philwebb that does not bypass argument parsing unfortunately. `SimpleCommandLineArgsParser` still kicks in.

**Comment by philwebb** [comment]
Oh interesting, I thought that because `SimpleCommandLinePropertySource` wasn't created neither would the `SimpleCommandLineArgsParser`. If you've got some enhancement in mind then please do submit it (along with tests if possible) and we can take a look.
