### ISSUE TITLE
Make TaskExecutionAutoConfiguration#applicationTaskExecutor lazy

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14904]
The creation of the bean itself is not costly as it does not hold/create any thread until a task is actually submitted to it but it logs twice at `INFO` level: once on startup and once on shutdown.

Given we've tried to polish and clean logs in 2.1, I think it would be worthwhile to look if we can't make that bean lazy.

**Comment by ayudovin** [comment]
As far as I understand we can just add `@Lazy` on creating bean `ThreadPoolTaskExecutor`, right?

**Comment by mbhave** [comment]
Closing in favor of PR #14934.
