### ISSUE TITLE
Improve migration documentation at "28.1.8 Path Matching and Content Negotiation"

### ISSUE THREAD

**Issue by huberchrigu** [spring-projects/spring-boot#14919]
The Spring Boot migration guide links https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-pathmatch for migrating MVC endpoints with suffix matching. There the documentation says

> Spring Boot chooses to disable suffix pattern matching by default, which means that requests like "GET /projects/spring-boot.json" won’t be matched to @GetMapping("/projects/spring-boot") mappings. ... If you understand the caveats and would still like your application to use suffix pattern matching, the following configuration is required:
> 
> `spring.mvc.contentnegotiation.favor-path-extension=true`
> ...

That is not accurate, the given example will still not work. I suggest you also mention to add the following property

`spring.mvc.pathmatch.use-suffix-pattern=true`

Only then it works as with Spring 4.

**Comment by nishantraut** [comment]
Hi Phil, Can you help us to understand which file to be updated, as i understand that paragraph need to be updated to include property spring.mvc.pathmatch.use-suffix-pattern=true

Can you please guide?  Thanks.

**Comment by philwebb** [comment]
Hi @nishantraut, The file in question is in [spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc). It's an asciidoctor file. You can find details about the syntax [here](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/)

Thanks!

**Comment by nishantraut** [comment]
Hi @philwebb Thanks for the update. I will try to update as soon as i can, bit busy with weekdays office work, mostly on Saturday will try to raise PR.

**Comment by nishantraut** [comment]
Or early if i get a chance.

**Comment by nishantraut** [comment]
Hi @philwebb Have committed changes under PR https://github.com/spring-projects/spring-boot/pull/14977 Please review and merge if looks ok. Thanks.

**Comment by philwebb** [comment]
Thanks @nishantraut, I'll close this one in favor of the PR.
