### ISSUE TITLE
Add logging checkstye rule

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14911]
See #14910 for an example of there we've used the wrong logger. A checkstyle import restriction would probably help.

**Comment by nishantraut** [comment]
Hi Phil, would lile to contribute on this. can you point me on sample if already implemented such feature. Is it extending Check class from checkstyle jar and adding logic. Can you please guide? Thanks.

**Comment by nishantraut** [comment]
Hi Phil, 
Went through quick checkstyle docs there is xml configuration, can you please tell we want restrict slf4j logging package or particular class. Waiting to do my first contribution on spring boot :)  Can you please guide further?

**Comment by nishantraut** [comment]
Hi Phil, 
Adding more on groundwork i see there is import-control.xml we just need to add one more rule, so we need subpackage and disallow package names? I am going in right direction?

**Comment by philwebb** [comment]
Hi @nishantraut, thanks for offering to help. We've done something similar for JUnit already which is inherited from the `spring-javaformat` project. We can probably do something similar to that. The relevant lines from that project [are here](https://github.com/spring-io/spring-javaformat/blob/1830776220d0fc89456d947d24d8ca346118a0b9/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml#L142-L148)

We might have some legitimate use of SLF4J in the `LoggingSystem` implementation classes. We'll probably need to add those to the [suppressions file](https://github.com/spring-projects/spring-boot/blob/45a0bfd870524b781bf64936ff167d6bd1a95a22/src/checkstyle/checkstyle-suppressions.xml).

**Comment by nishantraut** [comment]
Hi @philwebb Thanks for the pointers, will setup local workspace and try to fix the issue, if it works then will let you know and raise PR.

**Comment by philwebb** [comment]
@nishantraut Thanks for your offer to help but this turned out to be a relatively simple change, and I wanted to get it in before 2.1.0 is GA. I've just pushed something to master.

**Comment by nishantraut** [comment]
Hi @phwebb Great you fixed it. Let me know any other issue on which i can contribute. Thanks
