### ISSUE TITLE
Response time increases due to WebMvcMetricsFilter.doFilter()

### ISSUE THREAD

**Issue by vxfactor** [spring-projects/spring-boot#14929]
Here is a New Relic screenshot of response time for one of my endpoints:

![scr](https://user-images.githubusercontent.com/28916548/47338498-c3f77800-d6b5-11e8-84c2-cbcd644d0ab5.png)

The issue is with the `WebMvcMetricsFilter.doFilter()` component. It starts out as almost zero when app is deployed and then gradually increases. In my app, it has gone upto ~200ms.

Is it because I have enabled actuator in my application? 

It is present in the response time chart for all my endpoints and has roughly the same value (irrespective of the throughput or actual response time of the endpoint).

I'm using Spring boot 2.0.1.RELEASE.

**Comment by bclozel** [comment]
Are you seeing the same issue with Spring Boot 2.0.5.RELEASE? We've limited the amount of uri collected and this might be the underlying issue here (see #14173).
How's the memory going on those applications - do you have a similar graph for memory usage?

**Comment by vxfactor** [comment]
Yes. Here are the graphs.

![responsetime](https://user-images.githubusercontent.com/74436/47357169-a50fda80-d6e3-11e8-8441-58f30603e4be.png)

![memory](https://user-images.githubusercontent.com/74436/47357178-a93bf800-d6e3-11e8-88f9-79a7870b49d4.png)

There is a gradual increase in Heap Memory usage and Old Gen usage.

**Comment by bclozel** [comment]
Can you upgrade to Spring Boot 2.0.5+ and check if it's been fixed?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
