### ISSUE TITLE
Update spring.mvc.log-resolved-exception with logging changes in Spring Framework

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#14936]
As of [SPR-17178](https://jira.spring.io/browse/SPR-17178) and [SPR-17383](https://jira.spring.io/browse/SPR-17383), the `DefaultHandlerExceptionResolver` has a WARN logger configured by default. It was previously logging at WARN level, so this Spring Framework change doesn't really counts as a behavior change.

Spring Boot has a configuration property that enables WARN logging on other `HandlerExceptionResolver` instances.

```
spring.mvc.log-resolved-exception=false # Whether to enable warn logging of exceptions resolved by a "HandlerExceptionResolver".
```

In light of the latest changes, we might want to update the configuration property description, deprecate it, or update its behavior.

In any case, this issue should fix the latest build failures because our current test suite relies on all `HandlerExceptionResolver` instances to not have a configured WARN logger by default, which is not the case anymore.

**Comment by bclozel** [comment]
In my opinion this is just a assumption that needs to change in our tests, but doesn't question our current configuration property. Pinging @rstoyanchev on this, since we've discussed that within the Spring Framework team.

**Comment by rstoyanchev** [comment]
Indeed, DefaultHandlerExceptionResolver now simply taps into the option to set the warnLoggerCategory instead of using its own Log instance if the warnLogger is not set. So adjusting the test sounds fine.

Also as `HandlerExceptionResolver` is the interface, I think it be less ambiguous if the docs said "**any** HandlerExceptionResolver". I'm assuming that's what it means.

**Comment by mbhave** [comment]
I'm wondering if it might be confusing if someone set `spring.mvc.log-resolved-exception=false`, that wouldn't stop the `DefaultHandlerExceptionResolver ` from logging at WARN. Maybe the doc could clarify that.

**Comment by rstoyanchev** [comment]
Good point that the flag promises to work the same for all resolvers. `DefaultHandlerExceptionResolver` always did some logging at warn level, but after the recent change, it's possible for Boot to enforce the flag by resetting warnLoggerCategory to null. Perhaps it's worth considering that for consistent behavior of the flag across resolvers. An extra flag targeting `DefaultHandlerExceptionResolver` specifically could always be added later if that ever became an issue.

**Comment by philwebb** [comment]
We're going to update the documentation but keep the behavior as it is.
