### ISSUE TITLE
Spring Boot incompatibility: starter-web + actuator + cloud-consul

### ISSUE THREAD

**Issue by Neikius** [spring-projects/spring-boot#14946]
When including the aforementioned libs in 1 project there will be an error: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

Attached a minimal mvn app that produces this. This is a runtime problem: mvn spring-boot:run produces it.
[springbug.zip](https://github.com/spring-projects/spring-boot/files/2510444/springbug.zip)

**Comment by bclozel** [comment]
Could you [raise that against the Spring Cloud Consul project](https://github.com/spring-cloud/spring-cloud-consul/issues) please? It seems the incompatibility is coming from `spring-cloud-starter-consul-discovery` and Spring Boot is not maintaining that.

I've tested against the latest `Finchley.SR1` version and I'm getting the same exception.

Thanks!

**Comment by Neikius** [comment]
Thanks for the pointer, will report there. I have to point out the spring project structure is unfathomable to an outsider.
