### ISSUE TITLE
ClassCastException in DefaultErrorWebExceptionHandler if the error attributes contains an HttpStatus

### ISSUE THREAD

**Issue by mmanciop** [spring-projects/spring-boot#14945]
[DefaultErrorWebExceptionHandler](https://github.com/spring-projects/spring-boot/blob/4322b9781bd95694a7bafd084e82b8bf00546920/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/error/DefaultErrorWebExceptionHandler.java#L175)  breaks due to the casting in case the `status` error attribute is specified as `HttpStatus`.

I think that, in general, it is wrong for `DefaultErrorWebExceptionHandler` to try to shoe-horn the status code to an `HttpStatus` value, as it breaks horribly when the status code is not a canonical one, which is the case, for example, when Spring Cloud Gateway proxies for a Cloud Foundry API.

**Comment by bclozel** [comment]
@mmanciop Are you sure it's a `ClassCastException`? Looking at the source code it should rather be an `IllegalArgumentException`.
Thanks for the report!

**Comment by bclozel** [comment]
Actually, I'm really missing something here.

The `DefaultErrorAttributes` ([see here](https://github.com/spring-projects/spring-boot/blob/be7c0a15f7fbd729983614e8ad66399bebe9f647/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/reactive/error/DefaultErrorAttributes.java#L90-L95)) are trying to extract the error status from the `ResponseStatusException` or falling back on an "Internal Server Error" by default.

Is there a custom `ErrorAttributes` bean at play here? Could you provide a simple app that shows the issue? The `DefaultErrorWebExceptionHandler` is trying to read the status information as an `HttpStatus`, but some code might be adding something to the error map that's not of the expected `HttpStatus` type, hence the `ClassCastException` you're seeing.

**Comment by mmanciop** [comment]
It’s definitely ClassCastException because the value in the map is of type HttpStatus, so it cannot unbox it to int.

I am having this issue in a Spring Cloud Gayeway app. I’ll try to come up with a repro project and test.

**Comment by bclozel** [comment]
We're not putting the actual `HttpStatus` value in the map, [see here](https://github.com/spring-projects/spring-boot/blob/be7c0a15f7fbd729983614e8ad66399bebe9f647/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/reactive/error/DefaultErrorAttributes.java#L83) so I don't understand how that `ClassCastException` is happening. Thanks for working on a repro project!

**Comment by mmanciop** [comment]
It will take a little time to repro. In the meanwhile, food for thoughts from my experience with MVC: an enum like HttpStatus is excellent for “input” to the API (e.g., ‘@ResponseStatus’), far less so for processing status codes coming from user-space code. I had run-ins with code generating non-canonical status codes in Zuul, at the time that it was integrated in Spring Cloud, and failed spectacularly when proxying for API that... got creative woth status codes. Maybe it could be considered to drop the dependency here to HttpStatus altogether?

**Comment by bclozel** [comment]
In Spring Framework we've run into similar issues where we were trying to enforce well-known only HTTP status code where things could get "more creative".

In this case, it's the other way around. The error response status can be extracted from two different places currently: an `ResponStatusException` thrown by the application or an `@ResponseStatus` annotation on a custom exception; both only accept `HttpStatus` instances. So there's no way to use non-standard HTTP status codes. If none was found, it falls back to HTTP 500.

This allows us to enforce well-known HTTP status codes to the external world and shield HTTP clients from other codes. I'm not aware of anything overriding this in Spring Cloud Gateway and the only place I've seen working with this is spring-cloud/spring-cloud-gateway#554.

Let us know about that repro!

**Comment by mmanciop** [comment]
A bad case of PBKAC. My apologies ;_;

(But I would love to see type-safety in the return type of `DefaultErrorAttributes#getErrorAttributes`, maybe using a parametrized-key pattern like [`HystrixProperty`](https://netflix.github.io/Hystrix/javadoc/index.html?com/netflix/hystrix/HystrixCommandProperties.html).)
