### ISSUE TITLE
Consider renaming `spring-boot-starter-oauth2-oidc-client`

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#14951]
I believe it would be better if the starter in subject is named `spring-boot-starter-oauth2-client`.

Arguments:
- `spring-boot-starter-oauth2-client` is shorter, and therefore easier to remember than `spring-boot-starter-oauth2-oidc-client`
- it would provide more consistency with other OAuth 2.0 related starters, e.g. `spring-boot-starter-oauth2-resource-server` that was proposed in #14950
- it would provide more consistency with the underlying Spring Security module which is named `spring-security-oauth2-client` (and not `spring-security-oauth2-oidc-client`)
- OpenID Connect is an extension of OAuth 2.0
    - to have it in starter name somewhat suggests that the starter is OpenID Connect focused
    - the starter is used for OAuth 2.0 login with providers that don't implement OpenID Connect, such as GitHub
    - the inclusion of `spring-security-oauth2-jose` dependency that starter pulls in, which is required for login with OpenID Connect compliant providers but not for ones like GitHub, shouldn't influence starter naming but rather be viewed as Boot's opinionated set of dependencies for OAuth 2.0 login feature
- OIDC as an acronym is more colloquial rather than formal - the https://openid.net/connect/ website for instance has no mention of OIDC (not even in the page source :wink:)

**Comment by mbhave** [comment]
I think those are valid points and I'm leaning towards changing it to `spring-boot-starter-oauth2-client` too. 

/cc @jgrandja since this was originally discussed [here](https://github.com/spring-projects/spring-boot/issues/13830#issuecomment-411250809).

**Comment by jgrandja** [comment]
Those are all very good points.
When I originally discussed this with @rwinch, he wanted OIDC in the starter name from what I recall.
@rwinch It's been a while so can you clarify the reasoning once again?

**Comment by philwebb** [comment]
I think I prefer the `spring-boot-starter-oauth2-client` name, even if it brings in a jose that some users might not need. I'm not a fan of acronyms in general and I think the `spring-boot-starter-oauth2-client` name is more Boot-like. Users can always exclude the dependency if they really don't want it.

**Comment by rwinch** [comment]
Thanks @philwebb This works for me. My main goal was to make it easy to get dependencies to support oidc which required the jose dependency too.
