### ISSUE TITLE
spring-boot-actuator: HttpTrace: Allow Customization of Capacity and UrlPattern

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-boot#14966]
# Problem
If you use HttpTrace with a default configuration two small issues exist:
- Number of 100 requests might be low, and it's not configurable  
- By default, all requests are logged including health and static resources 

# Workaround
- Customize HttpTraceRepository + HttpTraceFilter like this

```kotlin
import org.springframework.beans.factory.annotation.Value
import org.springframework.boot.actuate.trace.http.HttpTraceRepository
import org.springframework.boot.actuate.trace.http.InMemoryHttpTraceRepository
import org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter
import org.springframework.boot.web.servlet.FilterRegistrationBean
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
class HttpTraceConfig {

    @Value("\${management.trace.http.capacity:100}")
    lateinit var capacity: Integer

    @Bean
    fun traceFilterRegistration(filter: HttpTraceFilter): FilterRegistrationBean<HttpTraceFilter> {
        val registration = FilterRegistrationBean(filter)
        registration.urlPatterns = setOf("/myapi/*")
        return registration
    }

    @Bean
    fun httpTraceRepository(): HttpTraceRepository {
        val repo = InMemoryHttpTraceRepository()
        repo.setCapacity(capacity.toInt())
        return repo
    }
}
```
# Suggest Implementation
- Add `management.trace.http.capacity` property with default=100
- Add `management.trace.http.urls` 
- Exclude Health Endpoint by default (?)

Would like to contribute if this is a welcome addition

**Comment by philwebb** [comment]
We'll need to be careful with a `management.trace.http.capacity` since it's not a general capacity but something that only effects the `InMemoryHttpTraceRepository`. Perhaps `management.trace.http.inmemory.capacity` would be clearer?

**Comment by philwebb** [comment]
@rowi1de Thanks for the suggestions, but we've decided we don't want to encourage customization of the memory limits or the patterns. In fact, we're reconsidering if the feature should even be enabled by default since it's likely to have a performance impact in production and seems somewhat limited compared to other tracing solutions.

We'd be interested to hear more about where you're currently using the feature? What do you currently do with the endpoint?
