### ISSUE TITLE
Remove uncessary call in PropertiesMigrationReport

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-boot#14974]
Just wondering what that call before the loop accomplishes?

https://github.com/spring-projects/spring-boot/blob/1a0a8470e58d1b95a4e253678eec1deaaa2e6b00/spring-boot-project/spring-boot-properties-migrator/src/main/java/org/springframework/boot/context/properties/migrator/PropertiesMigrationReporter.java#L177

**Comment by philwebb** [comment]
@dima767 Good spot, looks like we can just drop it.
