### ISSUE TITLE
[Enhancement]  @Bean can only inject one dependency,can I inject  many dependencies in one method?

### ISSUE THREAD

**Issue by Paleozoic** [spring-projects/spring-boot#14978]
When inject two beans,such as the following code:
```java
@Bean("bean1")
public Bean buildBean1(){
    Bean bean = new Bean();
    return bean ;
}
@Bean("bean2")
public Bean buildBean2(){
    Bean bean = new Bean();
    return bean ;
}
```
can I just write the code? such as:
```java
@Beans
public Map<String,Bean> buildBeans(){
    Map<String,Bean> beans = new HashMap<>();
    beans.put("bean1",new Bean());
    beans.put("bean2",new Bean());
    return beans ;
}
```

sometimes we can not confirm how many beans to inject,we have to write complex `BeanDefinition` and then `registerBeanDefinition`.
if we have `@Beans`,everything is easy~

**Comment by philwebb** [comment]
The `@Bean` annotation and `@Configuration` processing code is part of Spring Framework so you'll need to raise a [JIRA](https://jira.spring.io/browse/SPR) for this.

I'm personally not convinced this is a good idea given the limited number of times users will need to create multiple beans in one go.
