### ISSUE TITLE
No dependency management is provided for Mockito's new mockito-junit-jupiter module

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#14973]
Would it make sense to manage  mockito-junit-jupiter - since you already manage mockito and junit versions? Then it is easier to add this dependency and have the version harmonize with boot

**Comment by bclozel** [comment]
I believe this is a duplicate of #14716 and #14736. I'm closing this now.

**Comment by nishantraut** [comment]
Hi @wilkinsona Can you please guide on this, would like to work on it. Thanks

**Comment by philwebb** [comment]
@nishantraut Thanks for the offer, but this is a fairly simple dependency addition so there's no need for a PR.

**Comment by wilkinsona** [comment]
We've had dependency management for the new module since 2.1 M1.

Duplicate of #12890.
