### ISSUE TITLE
Wrong condition for RedisSessionConfiguration.java

### ISSUE THREAD

**Issue by chuongnn** [spring-projects/spring-boot#14987]
In [RedisSessionConfiguration.java](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/RedisSessionConfiguration.java), the following condition is wrong and needs to be removed:

`@ConditionalOnClass({ RedisTemplate.class, RedisOperationsSessionRepository.class })`

Because the purpose of `RedisHttpSessionConfiguration`, parent of `RedisSessionConfiguration.SpringBootRedisHttpSessionConfiguration` is to expose a bean of `RedisOperationsSessionRepository.class`, it can not itself depend on existing of a `RedisOperationsSessionRepository.class` bean.

The same for [JdbcSessionConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/JdbcSessionConfiguration.java), the following condition is wrong and needs to be removed:

`@ConditionalOnClass({ JdbcTemplate.class, JdbcOperationsSessionRepository.class })`

**Comment by snicoll** [comment]
Thanks but that condition (per javadoc) checks that the class is available on the classpath. It doesn’t check if a bean is available (ConditionalOnClass does that).

**Comment by chuongnn** [comment]
Thanks, this turns out to be a tool-issue. May because `RedisSessionConfiguration` has package-private scope, Intellij keeps highlighting the beans exposed by `FindByIndexNameSessionRepository` not found.
