### ISSUE TITLE
Provide a way to bind the Flyway Pro license key property

### ISSUE THREAD

**Issue by anderius** [spring-projects/spring-boot#14989]
Flyway, starting from 5.2, added a configuration property required when using the pro/enterprise version:

https://github.com/flyway/flyway/issues/2043

It would be nice to be able to configure this directly from yaml/properties files, without having to use a FlywayConfigurationCustomizer.

I could probably create a PR if this sounds nice to you.

For the record, the following is needed without this support:

```
@Configuration
class FlywayConfig(
        @Value("\${my-app.flyway.license}") private val flywayLicense: String) {

    @Bean
    fun flywayLicenseCustomizer() = FlywayConfigurationCustomizer { it.licenseKey(flywayLicense) }
}
```
With the support I suggest, it would be done simply with:

`spring.flyway.license-key: "trial"`

**Comment by wilkinsona** [comment]
Unfortunately, there's no way for us to test the mapping of properties that are only supported in the Pro version of Flyway as the getters and setters in the OSS version all throw a `FlywayProUpgradeRequiredException`. With no way to test the mapping of the Pro-only properties to ensure that they're mapped correctly and that our defaults align with Flyway's, there's too much risk involved in supporting them.

**Comment by axelfontaine** [comment]
@wilkinsona Would you be willing to reconsider this? We actually have quite a number of users confused by the fact Spring Boot only supports a subset of Flyway's configuration properties.

The exact behavior of any of these remaining properties (like `licenseKey`) really shouldn't matter from a Spring Boot perspective. In fact getting a `FlywayProUpgradeRequiredException` in your tests should be validation enough that the mapping between Spring Boot's config and Flyway's config was successful, which is really what this integration is about.

What do you think?

**Comment by wilkinsona** [comment]
> In fact getting a FlywayProUpgradeRequiredException in your tests should be validation enough that the mapping between Spring Boot's config and Flyway's config was successful

IIRC, that would only tell us that we'd successfully mapped it to a pro-only property and not to the correct pro-only property. I guess we could scrape the property name from the exception's message which, while a bit unpleasant, wouldn't be too bad as it's only in our tests.

Let me discuss it with the rest of the team and see what they think.

**Comment by axelfontaine** [comment]
All messages are constructed using the same code. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/license/FlywayProUpgradeRequiredException.java#L25

Scraping should therefore be highly reliable. Additionally if desired we would be happy to turn the `feature` argument into a field and add a getter if that makes things easier for you.

**Comment by philwebb** [comment]
We'll have another look into this and try to get it into 2.2. Allowing the license key to be set via properties would be quite useful for a lot of users.

**Comment by wilkinsona** [comment]
[This branch](https://github.com/wilkinsona/spring-boot/tree/gh-14989) contains a proposal for supporting Flyway Pro's properties. I'm wondering if it would be better if we grouped them together under `spring.flyway.pro`.

**Comment by axelfontaine** [comment]
While the separate namespace may provide a distinction, it could actually confuse more than it helps and those properties do not have a special prefix when used with Flyway directly.

**Comment by snicoll** [comment]
> those properties do not have a special prefix when used with Flyway directly.

I am not sure to see how that matters. The argument is that we can clarify what is pro only and what isn't as it isn't obvious from the name of the property at all (besides the license key of course).

**Comment by wilkinsona** [comment]
Re-opening as Checkstyle is failing due to the import of `org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException`.
