### ISSUE TITLE
Provide a configuration property for configuring Tomcat's processor cache

### ISSUE THREAD

**Issue by rimal** [spring-projects/spring-boot#14991]
Can we please have a way to set a custom value for `processorCache` for embedded tomcat.

**Comment by wilkinsona** [comment]
We can consider adding a configuration property, but you can already configure the size of the processor cache using a `TomcatConnectorCustomizer`. Something like the following:

```java
@Bean
public WebServerFactoryCustomizer<TomcatServletWebServerFactory> processorCacheCustomizer() {
	return (tomcat) -> {
		tomcat.addConnectorCustomizers(
			(connector) -> ((AbstractHttp11Protocol<?>) connector
				.getProtocolHandler()).setProcessorCache(250));
	};
}
```

**Comment by rimal** [comment]
Ok. For now, this will help for sure! Thanks 👍

**Comment by snicoll** [comment]
Closing in favour of PR #15054

**Comment by philwebb** [comment]
We discussed this a little on the call and there's and decided we should expose this as a property. The main reason is the documentation for `processorCache` states:

> The default is 200. A value of `-1` means unlimited. In the unlimited case, the theoretical maximum number of cached Processor objects is`getMaxConnections()` although it will usually be closer to `getMaxThreads()`

This means it's quite likely you're going to want to change this value if you've set `server.tomcat.max-threads` or `server.tomcat.max-connections`.
