### ISSUE TITLE
java.util.Properties-Definition by ConfigurationProperties impossible if PropertyName contains "illegal" character

### ISSUE THREAD

**Issue by hosea** [spring-projects/spring-boot#14998]
Hello!
I'm using Spring Boot Version 2.0.3.RELEASE.
Because of a database-issue, I have to provide a specific property to the database connection (Oracle-Database). The property-Key is "v$session.program".
I tried to add the property in my application.yml:

```yaml
spring:
  datasource:
    dataSourceProperties:
       v$session.program=<MyValue>
```
and configured the DataSource as following:

```java
@Bean(name = "myDataSource")
@ConfigurationProperties(prefix = "spring.datasource")
public DataSource dataSource() {
	return DataSourceBuilder.create().build();
}
```

Unfortunatly this does not work: the property is not passed correctly: its name is changed to "vsession.program" during binding (before it is passed to the HikariConfig).
I could track it down: Spring boot uses ConfigurationPropertyNames during Property Binding. ConfigurationPropertyNames are "normalized". This means, that signs like "$" are skipped.
As "v$session.propram" is a key for java.util.Properties, this normalization should not be applied. Otherwise the definition of `java.util.Properties` via `@ConfigurationProperties` is very restricted.

Best regards
Hans

**Comment by wilkinsona** [comment]
As [described in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding), you need to surround the key with `[]`:

> If the key is not surrounded by `[]`, any characters that are not alpha-numeric or `-` are removed. For example, consider binding the following properties to a Map:
>
> ```
> acme:
>   map:
>     "[/key1]": value1
>     "[/key2]": value2
>     /key3: value3
> ```
> The properties above will bind to a Map with `/key1`, `/key2` and `key3` as the keys in the map.
