### ISSUE TITLE
Managed dependency groupId: com.googlecode.json-simple, artifactId: json-simple fails to print valid json

### ISSUE THREAD

**Issue by jt908** [spring-projects/spring-boot#15002]
Problem:
Using spring-boot-starter-parent version 1.5.14.RELEASE and:
```
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
        </dependency>
```
managed version 1.1.1 incorrectly handles java.util.Date and java.sql.Date objs when serialising to json.

e.g:
```
        Map<String, Object> map = new HashMap<>();
        map.put("timestamp", new Date());
        map.put("other", new java.sql.Date(System.currentTimeMillis()));
        System.out.println(JSONValue.toJSONString(map));

```
prints:
`{"other":2018-10-29,"timestamp":Mon Oct 29 12:02:45 GMT 2018}
`

**Comment by wilkinsona** [comment]
Thanks for the report, but there's nothing we can do in Spring Boot to address a bug in JSON simple. Please note that we've [dropped support for JSON Simple in 2.1](https://github.com/spring-projects/spring-boot/issues/13471) as the project has been abandoned.

If you have encountered a bug in JSON Simple that you cannot work around, I would recommend using another JSON library in its place.
