### ISSUE TITLE
Setting the gradle-plugin attribute on the Bintray package appears to fail silently

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15014]
The promotion of 2.1.0.RELEASE completed but it did not set the `gradle-plugin` attribute on the Bintray package.

**Comment by wilkinsona** [comment]
Other than it failing silently, I suspect this is a duplicate of #15015.

**Comment by mbhave** [comment]
Due to #15015, the response from the curl command is a `401` which doesn't cause the script to exit 1. I think we can close this issue, since we don't need to do anything here once the credentials are fixed.
