### ISSUE TITLE
Review differences between ApplicationConversionService and WebConversionService and align where appropriate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15019]
See https://github.com/spring-projects/spring-boot/issues/3021#issuecomment-434329952 for some background.

**Comment by wilkinsona** [comment]
We're not sure that much, if any, alignment is appropriate. `ApplicationConversionService` is really intended for `@ConfigurationProperties` and `@Value` conversion, i.e. things that are internal to the application. The `WebConversionService` is used to handle essentially any input received in an HTTP request and as such then conversion that it performs needs to be appropriate for the HTTP-based API that the application provides. We're not convinced that the conversions provided by `ApplicationConversionService` are appropriate.

**Comment by michaldo** [comment]
Andy, going back to #3021, what should I do, if I would like to have lowercase web conversion String -> Enum and I do not want reinvent ~wheel~ StringToEnumIgnoringCaseConverterFactory?

**Comment by wilkinsona** [comment]
@michaldo As I said above, we're not convinced that the conversions offered by `ApplicationConversionService` are appropriate. That includes the conversion performed by `StringToEnumIgnoringCaseConverterFactory`.

If it happens to do exactly what you want in your HTTP-based API then you are free to copy-and-paste the code into your own application where you can guarantee that your HTTP-based API will not then be affected as we evolve Boot's configuration property binding support in future versions.

If it's close to what you want, but not an exact match (note that, in addition to ignoring case, it also ignores any characters that are not letters or digits), then you can use the existing code in Boot as inspiration for your own implementation.

**Comment by michaldo** [comment]
Acknowledged

**Comment by michaldo** [comment]
I would like to mention that I found other  conversion service from `ApplicationConversionService` family useful for MVC: `DelimitedStringToCollectionConverter` . This converter can regulate conversion to `List`.

Example:

For particular parameter `foo`, I need request `foo=bar,baz&foo=qux` to be interpreted as `["bar,baz", "quz"]` and `foo=bar,baz` as `["bar,baz"]`
Standard MVC StringToCollectionConverter is too primitive for that, but DelimitedStringToCollectionConverter is fine:
```java
@Delimiter(Delimiter.NONE)
private List<String> foo;
```
I still desire more than freedom in copy-and-paste :grinning:

**Comment by philwebb** [comment]
I've raised https://github.com/spring-projects/spring-framework/issues/22808 to see if Spring Framework might consider adding `@Delimiter` support directly. I'm not convinced that we should do more than that to align `ApplicationConversionService` and `WebConversionService` since I think `WebConversionService` should really remain a framework concern.
