### ISSUE TITLE
Spring Boot 2.1.0.RC1 Parent Pom Having Bug wWhen Used With Spring Security 5.1.2.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-boot#15012]
I followed the steps provided in 5.1.2.BUILD-SNAPSHOT.by updating my pom of Spring Boot with:

<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
<java.version>11</java.version>
<spring-security.version>5.1.2.BUILD-SNAPSHOT</spring-security.version>

But now project is not even building with mvn clean install -U and failing with below stack trace:

[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.security:spring-security-bom:pom:5.1.2.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:2.1.0.RC1, /home/ankur/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.1.0.RC1/spring-boot-dependencies-2.1.0.RC1.pom, line 2856, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-test:jar is missing. @ line 51, column 21
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR] The project com.github.ankurpathak:facebook-login:0.0.1-SNAPSHOT (/home/ankur/Development/projects/facebook-login/pom.xml) has 2 errors
[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.security:spring-security-bom:pom:5.1.2.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:2.1.0.RC1, /home/ankur/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.1.0.RC1/spring-boot-dependencies-2.1.0.RC1.pom, line 2856, column 25 -> [Help 2]

The seeing the stack trace I can only see their is something wired with this parent pom and missing some version for spring-security-test.
You can try with this sample:
https://github.com/ankurpathak/facebook-login
By going into parent pom of spring boot spring-boot-starter-parent-2.1.0.RC1.pom at line 2856 I see
this maven coordinates

org.springframework.security
spring-security-bom
${spring-security.version}
pom
import

But at this url for 5.1.2.BUILD-SNAPSHOT in Spring SNAPSHOT repo no POM is their:
https://repo.spring.io/snapshot/org/springframework/security/spring-security-bom/5.1.2.BUILD-SNAPSHOT/
But at this url for 5.1.1.BUILD-SNAPSHOT in Spring SNAPSHOt repo we have a pom:
https://repo.spring.io/snapshot/org/springframework/security/spring-security-bom/5.1.1.BUILD-SNAPSHOT/
So I think snapshot is not properly build or pushed. Can you put more on this or correct me.

This issue is linkde with this closed issue on Spring Security at:
https://github.com/spring-projects/spring-security/issues/6017

**Comment by mbhave** [comment]
@ankurpathak Please don't cross-post the same issue in two places. If it turns out that the snapshot is not published correctly, it's something that needs to be fixed in Spring Security and there isn't much we can do in Spring Boot about this.
