### ISSUE TITLE
auto register injection points for junit 5

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#15010]
This test, imho, should pass, unfortunately I get an exception
```
import java.time.Duration;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jms.annotation.JmsListener;
import org.springframework.stereotype.Component;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import static org.junit.jupiter.api.Assertions.assertTimeoutPreemptively;

@DataJpaTest
@SpringJUnitConfig
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@SpringBootTest( properties = {
        EmrPublisher.CREATED_SCHEDULE_PLACEHOLDER + "=1 second"
})
class EmrPublisherTest {

    @MockBean Listener listener;

    @Test
    void test( @Value( EmrPublisher.CREATED_SCHEDULE_PLACEHOLDER ) Duration duration ) {
        assertTimeoutPreemptively( duration.plusMillis( 10 ), () -> {
            Mockito.verify( listener  ).receiveMessage( Mockito.any() );
        } );
    }

    @Component
    interface Listener {
        @JmsListener( destination = EmrPublisher.EMR )
        void receiveMessage( EmrCreated emrCreated );
    }
}
```

```
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [java.time.Duration arg0] in executable [void com.potrero.ph.event.emr.EmrPublisherTest.test(java.time.Duration)]
```

I have also noticed that I can `@Autowired` Junit constructors, but for some reason I cannot inject with the single constructor scenario without.

**Comment by wilkinsona** [comment]
You haven't supplied the complete stack trace, but I suspect the root cause will be similar to the following:

```
Caused by: java.lang.IllegalArgumentException: '1 second' is not a valid duration
	at org.springframework.boot.convert.DurationStyle.detect(DurationStyle.java:170)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:65)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:50)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:40)
	... 47 more
```

As [noted in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion-duration), `s` should be used as the unit for seconds, i.e. your property should be `EmrPublisher.CREATED_SCHEDULE_PLACEHOLDER + "=1s"`

If making that change doesn't help, please provide complete details of the failure along with a minimal, complete example (something we can unzip or git clone) that reproduces the problem and we can re-open this issue and take another look.

**Comment by xenoterracide** [comment]
@wilkinsona updated with what I believe to be sufficient information. This is actually testing a `@Scheduled` jms event, but I don't believe that's needed to reproduce the issue

**Comment by wilkinsona** [comment]
Thanks, but we need more than that. If you’d like us to spend time investigating further, please take some time to provide the complete, minimal sample that I requested above.

Probably unrelated to this issue, but I’d also review your use of `@DataJpaTest` and `@SpringBootTest`. You should use one or the other.

**Comment by xenoterracide** [comment]
You can't combine those? but `@DataJpaTest` doesn't support setting properties like this...

**Comment by xenoterracide** [comment]
updated it again, that should be sufficient to reproduce the issue, I mean, I don't have a gradle file with the starter, but this is truly a very simple issue. At least as far as reproducing goes. Thanks for the other input.

**Comment by philwebb** [comment]
@xenoterracide The code in the comment isn't enough to tell exactly what's going on, but I believe your test will work when you upgrade to Spring Boot 2.1 because of #12148. If that's not the case then please provide a complete sample that we can run.
