### ISSUE TITLE
Reference documentation incorrectly states that the heapdump returned from /actuator/heapdump will be gzipped

### ISSUE THREAD

**Issue by hlang** [spring-projects/spring-boot#15016]
Calling /actuator/heapdump is giving me a heap-dump-file. 
In spring boot 2.0.6 the heap-dump is not GZip compressed any more (it was compressed in spring boot 1.5.x)
The [documentation ](https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#production-ready-endpoints)says:
> heapdump  Returns a GZip compressed hprof heap dump file.

**Comment by wilkinsona** [comment]
Thanks for the report. That's an oversight as the documentation should have been updated as part of the rewrite of the Actuator in 2.0.
