### ISSUE TITLE
FR: Add Path to @Controller

### ISSUE THREAD

**Issue by GabrielBB** [spring-projects/spring-boot#15021]
Instead of:
```
@RestController
@RequestMapping("/api/")
```
It would be cleaner to do this:

`@RestController("/api/")`

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but `@RestController` is from Spring MVC which is part of Spring Framework. If you'd like to pursue this, please open a [Spring Framework JIRA ticket](https://jira.spring.io/projects/SPR) and comment here with a link to it.

**Comment by GabrielBB** [comment]
Done: [Add Path to @Controller - JIRA Ticket](https://jira.spring.io/browse/SPR-17447)
