### ISSUE TITLE
Typo in 2.1 Release Notes

### ISSUE THREAD

**Issue by rweisleder** [spring-projects/spring-boot#15029]
The section [JUnit 5](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#junit-5) contains

> All `@…​Test` annotations are meta-annotated with `@ExtendedWith(SpringExtension.class)`

In reality, those annotations are meta-annotated with `@ExtendWith(SpringExtension.class)`

**Comment by wilkinsona** [comment]
Fixed. Thanks for letting us know.
