### ISSUE TITLE
Oauth bearer token change 

### ISSUE THREAD

**Issue by viplavfauzdar** [spring-projects/spring-boot#15024]
It seems like that with spring security 5/boot 2 the keyword “Bearer” is no longer acceptable in the “Authorization” header. Adding “Bearer” before the “token” is now causing “invalid_token” error now.

This seems to be not in-line with oauth2 specs. 

See: 
https://tools.ietf.org/html/rfc6750 
sec 2.1

**Comment by mbhave** [comment]
This looks like it's been opened in error.  

@viplavfauzdar Feel free to reopen this issue with some more details if you feel this is a genuine bug.

**Comment by viplavfauzdar** [comment]
Unless I am missing something, the bearer token needs to be preceded by the keyword “Bearer” but today when I upgraded from spring-boot 1.5 to 2.0.2 my api broke till I realized that now I had to omit the “Bearer” in the “Authorization” header and just send the token by itself.

**Comment by viplavfauzdar** [comment]
Thanks. I’ll open the issue there and yes I did look at the migration
guide.
