### ISSUE TITLE
SpringBoot Kotlin with Kafka utilizing @SendTo does not properly work with Springs- Kotlin property substitution

### ISSUE THREAD

**Issue by meshpaul** [spring-projects/spring-boot#15036]
🐞 Bug report (do not copy/paste)
Hi,

  While working with Spring Boot, Kotlin, Spring Kafka and utilizing Springs Request Reply template
```grade
 kotlinVersion = '1.2.61'
    springBootVersion = '2.0.5.RELEASE'
    springCloudVersion = 'Greenwich.BUILD-SNAPSHOT'
    gsonVersion = '2.8.5'
    commonsValidatorVersion = '1.4.1'
    libphonenumberVersion = '5.5'
    log4jVersion = '2.11.1'
    junitVersion = '4.12'
    protobufGradlePluginVersion = '0.8.6'
    springKafkaVersion = '2.1.10.RELEASE'
    commonsValidatorVersion = '1.4.1'
    jacksonModuleKotlinVersion = '2.9.6'
    javaVersion='1.8'
```

I have stumbled upon an issue here is scenario thats easily replicated
1. Using Spring KafkaRequestReplyTemplate set up a required client call to REQ/REPLY topics 
2. Using Listener to receive required messages on REQ topic and once received send them to REPLY topic via `@SendTo` the value in `@SendTo` is as follows

```kotlin
     @KafkaListener(topics = ["\${my.input-request-topic}"])
    @SendTo("\${my.output-reply-topic}")
    override fun caseRequestListener(myModel: CommandModel): CommandModel {
       logger.warn("SUCCESS RECIVED MESSAGE {} ", myModel)

       myModel.responseType = CommandModel.ResponseType.SUCCESS

        return myModel

    }
```
the above property definition in `@SendTo` does not resolve and kept as is ${my.output-reply-topic}.

The only way this works if I use static declarations or change to use Spring EL using `#{` and not Kotlin supported `\${myVal}`... I also tried [git issue](https://github.com/spring-projects/spring-boot/issues/8061) with custom property resolver that did not work...  what works is something like this :   
```  @SendTo("#{systemProperties['my.output-response-topic'] ?: 'MY.CMD.CREATE.RESPONSE'}") ```

**Comment by wilkinsona** [comment]
Thanks for the report, but the handling of `@SendTo` is done by Spring Kafka which is managed as a [separate project](https://github.com/spring-projects/spring-kafka).

**Comment by meshpaul** [comment]
Thanks
