### ISSUE TITLE
Consider disabling management.trace.http by default

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15039]
Currently we only offer `InMemoryHttpTraceRepository` and if actuator is present then we trace every request. This seems a little wasteful so perhaps we should disable support by default.

**Comment by philwebb** [comment]
Devtools could switch it back on perhaps.

**Comment by philwebb** [comment]
Whoops, wrong milestone

**Comment by philwebb** [comment]
See also #8679

**Comment by mbhave** [comment]
We have decided to make the auto-configuration conditional on the presence of a `HttpTraceRepository` bean instead of auto-configuring an `InMemoryTraceRepository`. The `management.trace.http` flag can be used as an opt-out if tracing needs to be disabled even if the bean is present.
