### ISSUE TITLE
Add Tomcat ProtocolHandlerCustomizer

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15035]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background
Spring Boot provides a number of callback interfaces that can be used to customize the web server. A `TomcatConnectorCustomizer` can be used to customize a Tomcat `Connector`.

## Problem
Customizing the `ProtocolHandler` on the `Connector` requires creating a `TomcatConnectorCustomizer`. This is bit tedious as can be seen from the example below:

```java
@Bean
public TomcatConnectorCustomizer connectorCustomizer() {
       return (connector) -> { ((AbstractHttp11Protocol<?>) connector
				.getProtocolHandler()).setProcessorCache(250));
       };
}
```

Instead, if we added a `TomcatProtocolHandlerCustomizer` and applied those beans automatically, that would simplify the configuration to the following:

```java
@Bean
public TomcatProtocolHandlerCustomizer<AbstractHttp11Protocol<?>> processorCacheCustomizer() {
	return (handler) -> handler.setProcessorCache(250);
}
```

## Solution

Add a `TomcatProtocolHandlerCustomizer` type. Beans of  `TomcatProtocolHandlerCustomizer` type should be applied automatically to `TomcatServletWebServerFactory` and `TomcatReactiveWebServerFactory`. For `TomcatServletWebServerFactory`, this can be done [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration.java#L60) and the configuration for the reactive one can be found [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration.java#L71). 

The `ObjectProvider` interface can be used for injecting a dependency. [Here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisEmbeddedServerConfiguration.java#L59) is an example that can be used to inject customizers when there can be 0..n of them.

Tests for the servlet and reactive versions are [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfigurationTests.java) and [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryAutoConfigurationTests.java) respectively.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [x] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [x] Try to fix the issue following the steps above
- [x] Commit your changes and start a pull request.

**Comment by pas2al** [comment]
I would love to give it a try.

**Comment by atulkulkarni18** [comment]
I would like to fix this issue.

**Comment by mbhave** [comment]
@pas2al It's all yours! Please let us know if you have any questions.

@atulkulkarni18 Thanks, we'll reach out to you if @pas2al isn't able to work on it for some reason.

**Comment by mhewedy** [comment]
I like the idea 😃

**Comment by FDelporte** [comment]
@philwebb @mbhave great idea! You can add me to the waiting list :-)

**Comment by saket88** [comment]
I am on the waitlist :)

**Comment by sundarraj4u** [comment]
Can you put me on the waiting list for future issue fix.

**Comment by snicoll** [comment]
@sundarraj4u sorry but that's not how this works. We don't have a waiting list, please watch for future issues flagged with `first-timers-only`.

**Comment by pas2al** [comment]
I have problems setting up the project. I did import the project using the root `pom.xml` in IntelliJ and selected the modules i want to work on:
* `spring-boot/spring-boot-project/spring-boot`
* `spring-boot/spring-boot-project/spring-boot-autoconfigure`

Before, i built the whole project from the root with `mvn clean install`. Some test were failing due to dependency problems. This is the error when running a build for the whole project:

```
[INFO] [ERROR] Failed to execute goal on project spring-boot-sample-oauth2-resource-server: Could not resolve dependencies for project org.springframework.boot:spring-boot-sample-oauth2-resource-server:jar:2.2.0.BUILD-SNAPSHOT: Failed to collect dependencies at com.squareup.okhttp3:mockwebserver:jar:3.9.0 -> com.squareup.okhttp3:okhttp:jar:3.9.0: Failed to read artifact descriptor for com.squareup.okhttp3:okhttp:jar:3.9.0: Could not transfer artifact com.squareup.okhttp3:okhttp:pom:3.9.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
```

This is the rest of the log, every other module was successfully:

```
[INFO] Spring Boot Samples Invoker ........................ FAILURE [08:43 min]
[INFO] Spring Boot Tests .................................. SKIPPED
[INFO] Spring Boot Integration Tests ...................... SKIPPED
[INFO] Spring Boot Configuration Processor Tests .......... SKIPPED
[INFO] Spring Boot DevTools Tests ......................... SKIPPED
[INFO] Spring Boot Hibernate 5.2 tests .................... SKIPPED
[INFO] Spring Boot Server Tests ........................... SKIPPED
[INFO] Spring Boot Launch Script Integration Tests 2.2.0.BUILD-SNAPSHOT SKIPPED
```

The `spring-boot` module works fine in my IDE, but `spring-boot-autoconfigure` does not compile, due to dependency problems. It does not find Spring dependencies or even JUnit. I rebuilt the`spring-boot-autoconfigure` and reimported the maven module in IntelliJ. It still does not compile. The `spring-boot-autoconfigure` module does build when i run a `mvn clean install`. Can you help me?

**Comment by saket88** [comment]
@pas2al Please make sure you have a stable internet connection and you are not having  a proxy. Also check your settings.xml. Your build is failing because it is not able to download com.squareup.okhttp3.
Cheers

**Comment by pas2al** [comment]
I don't have any proxy configuration or a settings.xml (there is nothing to configure right now). The `spring-boot-autoconfigure` build was successful when running a build on the whole project (see the log above, the module was included in the list of successfully built modules) and it is successful when running it separately. But i don't get it why IntelliJ is not able to figure out the dependencies.

**Comment by saket88** [comment]
If you are able to build entire project from terminal, there shouldn't be any problem. I would build the project first from terminal and then reimport the entire project.

**Comment by pas2al** [comment]
Yep, it should :-). I imported the project now separately in IntelliJ. I imported multiple modules before and that crashed somehow. But now i can work.

**Comment by thaneeshshanand** [comment]
I would like to give it a try.

**Comment by snicoll** [comment]
@thaneeshshanand please read the whole thread before commenting. [This comment](https://github.com/spring-projects/spring-boot/issues/15035#issuecomment-472761177), in particular, gives you some information

**Comment by mbhave** [comment]
How's it going, @pas2al? If you have any questions, please feel free to ask them here and we'll do our best to help.

**Comment by pas2al** [comment]
@mbhave It looks good. I started with the implemention. I am going to submit a wip pull request on the weekend. If i have questions we can take that pr as a basis.

**Comment by pas2al** [comment]
@mbhave Just want to let you know that i am making progress with the implementation. I just need some time to get my head around the details and finish it. Expect a PR within the next days.

**Comment by Razi007** [comment]
Interested to work here.

**Comment by snicoll** [comment]
@Razi007 thank you for the interest. Please read the whole thread before commenting, [this comment](https://github.com/spring-projects/spring-boot/issues/15035#issuecomment-472761177), in particular.

**Comment by pas2al** [comment]
PR is now open and ready for review. I am looking forward to your feedback. Did i miss something?

**Comment by snicoll** [comment]
Closing in favour of PR #16342
