### ISSUE TITLE
Jetty management access logs should be written to a different file

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15041]
We have `TomcatAccessLogCustomizer` and `UndertowAccessLogCustomizer` in `ServletManagementChildContextConfiguration` but no `Jetty` one.

**Comment by wilkinsona** [comment]
Support for Jetty's access logging was added in 2.0: https://github.com/spring-projects/spring-boot/pull/8819.

**Comment by mbhave** [comment]
On a slightly separate note, should the [Undertow customizer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/servlet/ServletManagementChildContextConfiguration.java#L73) be `@ConditionalOnClass`?

**Comment by philwebb** [comment]
Yes, I think so.
