### ISSUE TITLE
StaticResourceRequest.at*() have incorrect javadoc

### ISSUE THREAD

**Issue by ykartsev** [spring-projects/spring-boot#15050]
Looks like `at*()` methods of [org.springframework.boot.autoconfigure.security.servlet.StaticResourceRequest](
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/security/servlet/StaticResourceRequest.html) are not static, although it's examples in javadoc are shown as if they are:
```java
/**
 * Returns a matcher that includes all commonly used {@link StaticResourceLocation
 * Locations}. The
 * {@link StaticResourceRequestMatcher#excluding(StaticResourceLocation, StaticResourceLocation...)
 * excluding} method can be used to remove specific locations if required. For
 * example: <pre class="code">
 * StaticResourceRequest.atCommonLocations().excluding(StaticResourceLocation.CSS)
 * </pre>
 * @return the configured {@link RequestMatcher}
 */
public StaticResourceRequestMatcher atCommonLocations() {
    return at(EnumSet.allOf(StaticResourceLocation.class));
}
```

Having in mind the fact that its constructor is private, there is no way to use these methods.

I assume those `at*()` methods should be made static to follow the javadoc, unless, of course, I'm missing something...

Thank you in advance!

**Comment by philwebb** [comment]
It's actually the Javadoc that's wrong. They should be used from the `PathRequest` class. e.g.:

```java
RequestMatcher m = PathRequest.toStaticResources().atCommonLocations();
```
