### ISSUE TITLE
Spring Boot 2.0.5.RELEASE with Spring Data Elasticsearch 2.0.5.RELEASE Failing

### ISSUE THREAD

**Issue by shazin** [spring-projects/spring-boot#15067]
I am using following frameworks and datastores

spring-boot-starter version 2.0.5.RELEASE
spring-boot-starter-data-elasticsearch version 2.0.5.RELEASE
elasticsearch version 6.2.4 

I have a Document which has a _org.springframework.data.elasticsearch.core.geo.GeoPoint_ to store location. And when I query by that location with _ElasticsearchRepository_ custom method _Page<?> findByLocation(GeoPoint point, Pageable pageable_). I get the following Exception.

This is working with Spring Boot 1.x.

> UncategorizedExecutionException[Failed execution]; nested: EOFException[tried to read: 109 bytes but only 50 remaining];
> 	at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:89)
> 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:47)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:941)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:937)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:363)
> 	at org.springframework.data.elasticsearch.repository.query.ElasticsearchPartQuery.execute(ElasticsearchPartQuery.java:60)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:602)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:590)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
> 	at com.sun.proxy.$Proxy105.findByLocation(Unknown Source)
> 	at lk.luxeliving.property.service.LuxeLivingApplication.lambda$applicationRunner$1(LuxeLivingApplication.java:74)
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:809)
> 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:799)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
> 	at lk.luxeliving.property.service.LuxeLivingApplication.main(LuxeLivingApplication.java:42)
> Caused by: java.io.EOFException: tried to read: 109 bytes but only 50 remaining
> 	at org.elasticsearch.transport.netty4.ByteBufStreamInput.ensureCanReadBytes(ByteBufStreamInput.java:75)
> 	at org.elasticsearch.common.io.stream.FilterStreamInput.ensureCanReadBytes(FilterStreamInput.java:80)
> 	at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:961)
> 	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:347)
> 	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:38)
> 	at org.elasticsearch.common.io.stream.StreamInput.readNamedWriteableList(StreamInput.java:921)
> 	at org.elasticsearch.search.builder.SearchSourceBuilder.<init>(SearchSourceBuilder.java:205)
> 	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:733)
> 	at org.elasticsearch.action.search.SearchRequest.readFrom(SearchRequest.java:421)
> 	at org.elasticsearch.common.io.stream.Streamable.lambda$newWriteableReader$0(Streamable.java:51)
> 	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56)
> 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1508)
> 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1382)
> 	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by wilkinsona** [comment]
Spring Boot 2.0 uses Spring Data Kay and, as far as I know, Spring Data Elasticsearch from Spring Data Kay does not support Elasticsearch 6. Boot’s dependency management uses 5.6.x for this reason. To use Elasticsearch 6 you should upgrade to Spring Boot 2.1 which contains Spring Data Lovelace that does support Elasticsearch 6.
