### ISSUE TITLE
Make UndertowAccessLogCustomizer conditional on class

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#15065]

**Comment by philwebb** [comment]
This should be as simple as adding `@ConditionalOnClass(Undertow.class)` to [this method](https://github.com/spring-projects/spring-boot/blob/624c1306fd909df88e5060452ac36257a0f060b0/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/servlet/ServletManagementChildContextConfiguration.java#L73)
