### ISSUE TITLE
All converters are scanned for a controller test even they are not relevant to that controller

### ISSUE THREAD

**Issue by xiuwyang** [spring-projects/spring-boot#15064]
Recently upgraded from 1.4.6.RELEASE to 2.0.6.RELEASE, noticed controller tests started to fail. 

Dug around a bit, found out that [this commit](https://github.com/spring-projects/spring-boot/commit/4e88db9883c6db6bc6c8c6c9c6d84723129cf0ba) made sure that `Converter`s are auto-configured as well when a test uses `@WebMvcTest`. 

The question is why auto scan all `Converter`s even some are not related to the controller that I am testing against? Suppose one `Converter` uses another service dependence that has nothing to do within the test, and I need to mock that irrelevant dependency in the test now?

It seems to be a bug, let me know what you think, thanks.

**Comment by philwebb** [comment]
The change was intentional, see #10802 for some background. I think the change makes sense and I'm not keen to revert it. You can always use the `excludeFilters` attribute on `@WebMvcTest` if you need to filter specific beans.
