### ISSUE TITLE
Support excludes on @SpringBootTest

### ISSUE THREAD

**Issue by AsinRay** [spring-projects/spring-boot#15068]
I like the new `@SpringBootTest` but still need to be able to exclude some of the classes that are too eager to jump in. Is it possible with Spring's meta-annotation model to extend the excludes attribute from `@ExcludesClass` onto the new annotation?

**Comment by wilkinsona** [comment]
@AsinRay Thanks for the suggestion but I am not sure I understand what you are looking for. You’ve mentioned `@SpringBootApplication` in the title and `@SpringBootTest` in the description. I’m also not sure what you mean by “too eager to jump in”. Can you describe the problem you have in more detail please? Lastly, I am not familiar with (or have forgotten about) `@ExcludesClass`. Where is that annotation from?

**Comment by AsinRay** [comment]
When test the code using SpringBootTest, is there any convenient way to excludes classes from application context?

**Comment by wilkinsona** [comment]
The `exclude` attribute on `@SpringBootApplication` is for excluding auto-configuration classes, not classes in general. It will be honoured by `@SpringBootTest`. If you want a specific test class to exclude additional auto-configuration classes, you can use its `properties` attribute to configure the `spring.autoconfiguration.exclude` property with a comma-separated list of the names of the classes that you want to exclude. Does that meet your needs?

**Comment by erezwncare** [comment]
I think in general @SpringBootTest does not provide enough flexibility, and that is why I opened #15077. There are many tweeks and annotations that I may want to support in junit\integration tests that have a spring context: 

@ComponentScan with full flexibility (excludeClassesPackage and more...)
@PropertySource that can actually effect the context creation (for example add "spring.autoconfiguration.exclude" or "management.server.port"=-1)
or creating something like @DisableEmbeddedMongo (managing Application env before TestContext is created from configuration)
etc

All these things can't really be achieved  when one tries to @SpringBootTest a full application that is already well defined : 

@SpringBootApplication
@CustomFrameworkAnnotationsHere ( that runs the whole show...)
class Application{

}

@SprintBootTest(class="Application.class")
@CantRealyDoMuchHereOnceTestContextIsFullyCreated :(
class ApplicationIT{

}

The small tweek that can allow TestContext full manipulation , is as I see it, is by extending the bootstrap. Any small functionality addition to @SpringBootTest (like exclude=) would only scratch the surface of what a full proper IntegrationTest wants to be able to do to a @SpringBootApplication.

**Comment by wilkinsona** [comment]
@AsinRay Thank you for the additional explanation. `@SpringBootTest` is intended for integration testing an entire application. As such, attributes for filtering some classes out of those that are considered for auto-configuration or component scanning are outwith its scope so I am going to close this issue.

I would recommend taking a look at `TypeExcludeFilter` and the numerous test slice annotations that Boot provides (such as `@DataJpaTest`) for some inspiration.  They launch a context focussed on specific classes and types of components.

**Comment by wilkinsona** [comment]
@erezwncare Can you please add the comment you have made above to #15077? It’s useful information about your motivation for opening the issue which we should consider when triaging it.

**Comment by erezwncare** [comment]
Added my comment to #15077. +1 to the TypeExcludeFilter. May be something like this :

public abstract class AnnotationBasedTypeExcludeFilter extends TypeExcludeFilter
		implements BeanClassLoaderAware {...}
