### ISSUE TITLE
RestTemplateBuilder.basicAuth causes the entire body to be read into memory

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15078]
See https://github.com/spring-io/artifactory-resource/issues/27 for background. I'm not sure if we need to just document this as a warning or look for an alternative way to add the header.

**Comment by wilkinsona** [comment]
This feels to me like it should be fixed/enhanced in Framework so that there’s a mechanism for setting request headers without buffering the whole body.

**Comment by philwebb** [comment]
Ive raised [SPR-17470](https://jira.spring.io/browse/SPR-17470) to see what Framework can do. I'll leave this one open but blocked since we'll probably need changes regardless.

**Comment by mbhave** [comment]
Given that the framework issue has been declined, we should decide if we just want to document this or do something else to prevent an OOM error.

**Comment by philwebb** [comment]
I think I can probably port https://github.com/spring-io/artifactory-resource/commit/62215780e903bac4eb13c7b5f4ccf4aba8deb540

**Comment by philwebb** [comment]
Closing in favor of PR #17010
