### ISSUE TITLE
@WebFluxTest tests fail in 2.1 with 401 UNAUTHORIZED if spring security is a dependency

### ISSUE THREAD

**Issue by mahanhz** [spring-projects/spring-boot#15073]
In upgrading to Spring Boot 2.1, my @WebFluxTest tests failed. 
They return 401 UNAUTHORIZED where they previously returned 2xx or 3xx.

In the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes) there is a line stating: _"Security configuration is now applied to WebTestClient"._

I have written my @WebFluxTest tests according to the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-webflux-tests).

If this is intended behaviour now in 2.1 then it would be helpful to have documentation stating how tests could be written if spring security is a dependency.

In case you want an example of the behaviour then you can see it in this [sample repository](https://github.com/mahanhz/templateissue).
The [PingControllerTest](https://github.com/mahanhz/templateissue/blob/master/src/test/java/com/example/templateissue/PingControllerTest.java) test passes in 2.0.6.RELEASE but if you upgrade to 2.1.0.RELEASE then the test fais with 401 UNAUTHORIZED.

**Comment by wilkinsona** [comment]
Thanks for the sample. This is intended behaviour. It aligns WebFlux-based tested with the equivalent in Spring MVC.

I've updated the release notes to link to the [relevant section](https://docs.spring.io/spring-security/site/docs/5.1.x/reference/html5/#test-method-setup) of Spring Security's reference documentation. You can add `@WithMockUser` to your test class or test methods to run the test or tests as a particular user in a particular role.
