### ISSUE TITLE
i didn't inject Apache-CXF client proxy web service bean(s) registered in BeanDefinitionRegistryPostProcessor

### ISSUE THREAD

**Issue by semihokanpehlivan** [spring-projects/spring-boot#15079]
Hello everyone i was asked a question 16 days ago about defining Apache-cxf client proxy dynamically in stackoverflow, but there is no answer or comment. 

Problem in stackoverflow is [this](https://stackoverflow.com/questions/52853492/how-can-i-inject-apache-cxf-client-proxy-web-service-beans-registered-in-beand).

I am getting the service endpoints from database or external config file according to my application environment like: DEVL, TEST or PROD. I explained that with details and example code. I'm waiting your comments. 

Thank you.

**Comment by snicoll** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements so please do not cross post questions here.
