### ISSUE TITLE
When using WebFluxTest, WebTestClient's codecs are not customized breaking JSON (de)serialisation that relies on Module-provided functionality

### ISSUE THREAD

**Issue by mkheck** [spring-projects/spring-boot#15070]
Possible bug report/regression:

This code works with v2.0.6.RELEASE & prior versions of Boot, and Jackson dependencies were unchanged between 2.0.6 & 2.1.0.

Unit test fails with this stack trace: https://gist.github.com/mkheck/f94d3a2caea883004fc3442379d3b07d

Sample project is here: https://github.com/mkheck/Boot210JacksonNoCreatorsException

Steps to reproduce: run only active unit test in RouteConfigTest (getAllCoffees()).

**Comment by wilkinsona** [comment]
That’s a good point about the migration guide (or release notes for 2.1 I guess), @bclozel.

**Comment by mkheck** [comment]
Updated the project to be Lombok-less (& updated the repo on GH). Same issue persists.

**Comment by mkheck** [comment]
Just to follow up on the Lombok @Value topic, here is the last note about it, from their release notes for v1.16.22 "Envious Ferret" (May 29th, 2018):

"FEATURE: Private no-args constructor for @Data and @Value to enable deserialization frameworks (like Jackson) to operate out-of-the-box. Use lombok.noArgsConstructor.extraPrivate = false to disable this behavior."

No notes since contradicting it, even from their 30 October release. :/

**Comment by wilkinsona** [comment]
There is a problem with Lombok. The provided sample in its Lombok variant works when Lombok's version if overridden to downgrade it to 1.16.22.

**Comment by wilkinsona** [comment]
I can also get the sample to work without Lombok after making some modifications to test it using `@SpringBootTest` rather than `@WebFluxTest`. I think the difference here is that the `ParameterNamesModule` is registered when using the format but it is not registered when using the latter. This applies when using Spring Boot 2.0.x and Spring Boot 2.1.

**Comment by wilkinsona** [comment]
I think `@WebFluxTest` needs to be meta-annotated with `@AutoConfigureJson` and should also list `org.springframework.boot.autoconfigure.http.codec.CodecsAutoConfiguration` in its entry in `spring.factories`. Does that sounds right to you, @bclozel?

**Comment by mkheck** [comment]
The last version I can find locally I had confirmed working was using Boot 2.0.5.RELEASE with (you guessed it) Lombok 1.16.22. So yeah...

I use WebFluxTest to scope the test down to simply WebFlux components...let me take a look at it a bit further tomorrow to see what needs to happen to restore its former glory. 😆 Thanks Andy.

**Comment by hantsy** [comment]
Is there a workaround for this issue, I encountered the same issue when upgraded to 2.1.0.RELEASE. https://stackoverflow.com/questions/53208701/webfluxtest-does-not-create-objectmapper-when-upgraded-to-spring-boot-2-1-0-rel
