### ISSUE TITLE
suggest:support the fluent method style of property bind

### ISSUE THREAD

**Issue by liudaomanbu** [spring-projects/spring-boot#15072]
I found `@ConfigurationProperties` invalid. The reason is lombok's `@Accessors(fluent = true)`. Can consider to support the fluent set method style?

![image](https://user-images.githubusercontent.com/21155988/47906146-97b4d600-dec3-11e8-9360-1785f0a234f8.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The binder intentionally only supports Java Bean-style property accessors and we've [documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) that this is the case. Adding support for this fluent style of accessor would be a breaking change for anyone who is currently relying on such methods being ignored by the binder. As a result, I don't think we can do this.

A secondary concern is that I also think it would be hard to precisely identify which methods are property accessors and which do something else. With no `get` and `set` prefixes to identify them, almost any method that takes no arguments and return something could be a getter and any method that takes one argument and returns void could be a setter.
