### ISSUE TITLE
WebFlux doesn't render HTTP status error templates

### ISSUE THREAD

**Issue by butterfly-valley** [spring-projects/spring-boot#15083]
When I try to create a demo project on spring initializr and choose spring-boot-starter-webflux I can't for my life customize my error pages. I have tried putting the templates under /resources/public/error, /resources/templates/error (I am using Thymeleaf), defining a custom ErrorController to no avail. Each time I want to throw a 404 page for example the application throws the WhiteLabel page. BUT when I change the dependency to spring-boot-starter-web it picks my templates right away.

Is there some other way of declaring the error pages or this is just a bug (currently using Spring Boot 2.1.0.RELEASE)?

I eventually remedied the issue by falling back to 2.0.5 but it is no solution.

Thanks in advance.

[Copy of the issue on stackoverflow](https://stackoverflow.com/questions/52899283/how-to-customize-spring-webflux-error-page/52900277#52900277)

**Comment by bclozel** [comment]
Since [SPR-16898](https://jira.spring.io/browse/SPR-16898), the `toString` implementation of `HttpStatus` has been changed, and unfortunately, we were relying on that to resolve the HTTP status view names instead of just using the `HttpStatus.value()`.

We need to fix that in `DefaultErrorWebExceptionHandler` and add tests for this.

**Comment by bclozel** [comment]
Note: there is no issue with Spring Boot 2.0.6.RELEASE - the Thymeleaf error pages aren't working there but for a different reason (see [SPR-17407](https://jira.spring.io/browse/SPR-17407)). This has been solved in #14920 and upgrading Thymeleaf to 3.0.11.RELEASE should work.

This issue only affects Spring Boot 2.1.0.RELEASE.
