### ISSUE TITLE
Exception loading nested configuration file from jar

### ISSUE THREAD

**Issue by linead** [spring-projects/spring-boot#1508]
In my project I have the following structure

    my-jar.jar
      |- my_entities.jar
         |-META-INF
           |-orm.xml          
      |- lib
         |- all deps
     
I'm using eclipselink for JPA and setting things up manually (porting a legacy code base)
The problem is that eclipselink finds orm.xml inside the my_entities jar and tries to load the following url

`jar:jar:file:my-jar.jar!/my_entities.jar!/META-INF/orm.xml`

which the spring boot handler retrieves a root jar of

`jar:file:my-jar.jar!/my_entities.jar`

and fails because it's not a file: protocol.

I've rebuilt spring-boot and made it strip off all the protocols except the last. This got past this problem.

However then the `jarURLConnection` would assume that the url of the root jar was up the front of the url, so it would end up trying to pull a random segment out of the url and load that. I've just solved this by making sure to strip the url plust any preceeding characters and everything appears to have worked. 

What I'd like to know is if there's an underlying problem that i'm working around here or if my solutions are fine.

Please see : 
https://github.com/linead/spring-boot/commit/032f00f6197d39b67022415f6cfc0ee926db4c4e

**Comment by wilkinsona** [comment]
It's been almost 18 months now so I doubt we're going to get the requested test case
