### ISSUE TITLE
Please fix the wrong comments of RedisPubSubCommands

### ISSUE THREAD

**Issue by sisyphsu** [spring-projects/spring-boot#15091]
The comment of `org.springframework.data.redis.connection.RedisPubSubCommands#subscribe` is like:
```
/**
 * Subscribes the connection to the given channels. Once subscribed, a connection enters listening mode and can only
 * subscribe to other channels or unsubscribe. No other commands are accepted until the connection is unsubscribed.
 * <p>
 * Note that this operation is blocking and the current thread starts waiting for new messages immediately.
 *
 * @param listener message listener, must not be {@literal null}.
 * @param channels channel names, must not be {@literal null}.
 * @see <a href="http://redis.io/commands/subscribe">Redis Documentation: SUBSCRIBE</a>
 */
void subscribe(MessageListener listener, byte[]... channels);
```

`Note that this operation is blocking and the current thread starts waiting for new messages immediately.` is wrong. when I use `lettuce`, this method was totally **asynchronized**, not block at all.

**Comment by wilkinsona** [comment]
Thanks for the report, but this code is part of Spring Data Redis which is managed as a separate project from Spring Boot. Spring Data Redis uses [JIRA](https://jira.spring.io/browse/DATAREDIS) for issue tracking.
