### ISSUE TITLE
Reference documentation contains stale reference to Gradle plugin's embeddedLaunchScriptProperties

### ISSUE THREAD

**Issue by elion** [spring-projects/spring-boot#15094]
The documentation at https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html says: 

> To customize written elements, use the embeddedLaunchScriptProperties option of the Spring Boot Maven or Gradle plugins.

There is no embeddedLaunchScriptProperties property in Gradle plugin. 
Affected versions: Spring Boot 2.

**Comment by wilkinsona** [comment]
Thanks for the report. We missed updating that piece of the documentation when the Gradle plugin was rewritten in Spring Boot 2.0. You can find up-to-date documentation for configuring the launch script [here](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-configuring-launch-script).

**Comment by LostYang** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html上的文档说：
<configuration>
        <executable>true</executable>
    </configuration>

How to set this property（executable）？

**Comment by snicoll** [comment]
@LostYang please don't ask questions on an issue, especially considering it is closed and the issue doesn't seem related to your question. If you need support, please review [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), and ask a question on StackOverflow or Gitter. When you do, please provide more details as the link you've provided show a code snippet that does set the flag.
