### ISSUE TITLE
Documentation code can easily generate java.lang.IllegalStateException

### ISSUE THREAD

**Issue by estevaodias** [spring-projects/spring-boot#15090]
Hi,

This doc teaches me to include a model in the Controller's GET method signature, but this is leading me to an error after submit the form twice or just reload the page after the first error:

java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name '' available as request attribute

```
@GetMapping("/")
public String showForm(PersonForm personForm) {
   return "form";
}
```

https://spring.io/guides/gs/validating-form-input/

I'm using 2.0.3.RELEASE and everything under its parent p(b?)om.

https://stackoverflow.com/questions/36726525/thymeleaf-neither-bindingresult-nor-plain-target-object-for-bean-name-person-a

https://stackoverflow.com/questions/35318401/html-form-validation-using-thymeleaf-not-working-spring-boot/35330380#35330380

**Comment by wilkinsona** [comment]
Thanks for the report, but issues for each guide are managed in the guide’s repository. In this case that’s https://github.com/spring-guides/gs-validating-form-input.
