### ISSUE TITLE
Remove recommendation to add a dependency on Woodstox as it's now a transitive dependency of jackson-dataformat-xml

### ISSUE THREAD

**Issue by ziodave** [spring-projects/spring-boot#15092]
According to https://github.com/FasterXML/woodstox#maven, the artifact

```
<dependency>
	<groupId>org.codehaus.woodstox</groupId>
	<artifactId>woodstox-core-asl</artifactId>
</dependency>
```

changed to 
```
<dependency>
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
</dependency>
```

Should the Spring Boot documentation reflect this change here?

https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#howto-write-an-xml-rest-service

**Comment by wilkinsona** [comment]
Thanks for pointing out the problem. We don't have any dependency management for Woodstox so, even if we don't change the coordinates, the current example could do with being updated in some form. I don't think we should add dependency management for Woodstox as Boot itself doesn't interact with it and I'm also not keen on adding a version in the documentation as it would inevitably become out of date. I'm leaning towards removing the pom.xml and retaining the existing link to the project on GitHub where the README mentions the artifact coordinates.

**Comment by ziodave** [comment]
Hello @wilkinsona, makes sense. After a test I noticed also that it's still necessary to use 

```
<dependency>
	<groupId>org.codehaus.woodstox</groupId>
	<artifactId>woodstox-core-asl</artifactId>
</dependency>
```

because the package name changed as well.
