### ISSUE TITLE
Add a reference to autoconfigure-processor to the "Creating Your Own Starter" section

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15099]
We want to make sure all auto-configurations can benefit from the performance optimizations that the autoconfigure processor brings. 

Adding a reference to it to the "Create your own starter" should help with that.

**Comment by wilkinsona** [comment]
We already have a mention of it [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-module-autoconfigure) that looks sufficient to me.

Duplicate of #13368.
