### ISSUE TITLE
Tolerate Hibernate 5.2

### ISSUE THREAD

**Issue by garethpowell** [spring-projects/spring-boot#15100]
Whilst trying to upgrade our application to use Spring Boot 2.1.0 I hit upon a problem when Hibernate initialises. We are currently tied to using Hibernate 5.2.x and so far as I can tell Spring Boot 2.1.0 should still support this version. However, there appears to be  an explicit dependency on Hibernate 5.3.x during the Spring Boot JPA auto-configuration. With Hibernate 5.2.x when the `HibernateJpaConfiguration` class executes to bootstrap Hibernate, a `ClassNotFoundException` is thrown as it's unable to locate the new to Hibernate 5.3.x class BeanContainer.

```
Caused by: java.lang.ClassNotFoundException: org.hibernate.resource.beans.container.spi.BeanContainer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 45 common frames omitted
```

The problem looks to be in the `HibernateJpaConfiguration.determineHibernatePropertiesCustomizers` method where it instantiates a `SpringBeanContainer`.

I have attached a super simple project generated from the Spring Initializr that demonstrates the problem. The only change I made following project creation was to set the property `hibernate.version` to be `5.2.17.Final`. Simply run the Maven build or start up the app to see the problem.

Having taken a look at the sources, there appears to be no conditional check during initialization to establish whether the `BeanContainer` class is available. I think we need something similar to what can be found in `LocalSessionFactoryBean`

```java
	@Override
	public void setBeanFactory(BeanFactory beanFactory) {
		if (beanFactory instanceof ConfigurableListableBeanFactory &&
				ClassUtils.isPresent("org.hibernate.resource.beans.container.spi.BeanContainer",
						getClass().getClassLoader())) {
			this.beanFactory = (ConfigurableListableBeanFactory) beanFactory;
		}
	}
```

[spring-boot-hibernate-problem-demo.zip](https://github.com/spring-projects/spring-boot/files/2548838/spring-boot-hibernate-problem-demo.zip)

**Comment by philwebb** [comment]
@garethpowell Is there anything specific blocking you from upgrading to Hibernate 5.3?

**Comment by wilkinsona** [comment]
It's not just `BeanContainer`. We also use `RegionFactoryTemplate` which is another 5.3 addition.

**Comment by wilkinsona** [comment]
Actually, it's not us, but a different Hibernate module. That shows the difficulty in testing that we're 5.2 compatible when 5.3 is on the classpath.

**Comment by garethpowell** [comment]
@wilkinsona I suppose I inferred that Spring Boot would/should continue to support older versions of Hibernate based on the support from Spring 5.x. I don't think Spring Boot should force that particular upgrade on users as there are significant changes between 5.2 and 5.3 in particular the Caching SPI, and it's for this reason we can't simply upgrade to 5.3 at the moment @philwebb. We are using Elasticache in AWS as the backend and the library supporting this is not available for Hibernate 5.3 yet. I have been looking for alternatives, but so far haven't found a suitable one.

> As of Spring Framework 5.0, Spring requires Hibernate ORM 4.3 or later for JPA support and even Hibernate ORM 5.0+ for programming against the native Hibernate Session API. Note that the Hibernate team does not maintain any versions prior to 5.1 anymore and is likely to focus on 5.3+ exclusively soon.

**Comment by wilkinsona** [comment]
Spring Boot takes a more opinionated view of things than Spring Framework so you can't safely assume that because Framework supports a particular range of versions of a dependency that Boot will do the same.

Generally speaking, projects focus on backwards compatibility rather than forwards compatibility. This means that it will usually be safe to override Boot's dependency management to upgrade to a new minor release but that an override that downgrades to an older minor version may not work.

This feels to me more like an issue for the Elasticache Hibernate integration. Have you considered sticking on Boot 2.0.x until they have implemented Hibernate 5.3 compatibility?

**Comment by garethpowell** [comment]
As an organisation we endeavour to to keep up to date with Spring and other core libraries as new versions become available, thus avoiding any big bang changes. I appreciate the opinionated approach of Spring Boot and this works marvelously for the most part. I could understand support for pre 5.x Hibernate compatibility being dropped, but I can't help but think that this is going to prevent a large number of people upgrading to Spring Boot 2.1 if they're also forced to update to Hibernate 5.3. Anyway, we'll be staying on Boot 2.0 for at least awhile yet then. Thanks for your prompt response to this issue.

**Comment by wilkinsona** [comment]
As far as I can tell, it's impossible to test support for 5.2 using our ModifiedClassPathRunner. Hibernate insists on using the system class loader even if it's not an ancestor of the class loader that loaded Hibernate. This prevents us from hiding the Hibernate 5.3 classes.

**Comment by garethpowell** [comment]
Is it not the case that you can simply check for the existence of the 5.3 BeanContainer class as Spring Framework does and thus do the 5.3 specific bootstrapping, otherwise fall back to the previous way of setting up Hibernate. [https://jira.spring.io/browse/SPR-16305 ](url) and the associated Spring Boot issue [https://github.com/spring-projects/spring-boot/issues/13717](url). Also the same may be possible with the RegionFactoryTemplate.

Apologies if I'm missing anything and thanks for your time.

**Comment by garethpowell** [comment]
Ah right. I'm with you now. I've started looking at alternatives to remove the caching library dependency preventing us from upgrading to Hibernate 5.3.

**Comment by jhoeller** [comment]
FWIW, the Hibernate team does not support the Hibernate ORM 5.2 line anymore. They seem to consider 5.3 as immediately superseding the 5.2 line. In practice, they only maintain the 5.3.x and 5.1.x lines at this point... which makes sense since 5.2 was a major revision with its merged Hibernate/JPA APIs, so most people would rather be stuck on 5.1.x for binary compatibility reasons (or because it is what's shipping with their JBoss EAP installation)... and otherwise be able to move on to 5.3 rather quickly.

**Comment by wilkinsona** [comment]
@garethpowell Testing the change is sample if we use a separate module to do so, which is what I've done in https://github.com/spring-projects/spring-boot/commit/bfb0886495fd043815d482916b526de863ce7c9a. You should be able to use Hibernate 5.2 again with Spring Boot 2.1.1.

**Comment by garethpowell** [comment]
That's awesome @wilkinsona . Many thanks.
