### ISSUE TITLE
No dependency in maven central repo com.sun.xml.bind:jaxb-core with version 2.3.1

### ISSUE THREAD

**Issue by koval4uk** [spring-projects/spring-boot#15102]
Why version update to 2.3.1, but in maven i can get only  com.sun.xml.bind:jaxb-core:jar:2.3.0.1?

`Failed to execute goal on project server: Could not resolve dependencies for project server:development-SNAPSHOT: Could not find artifact com.sun.xml.bind:jaxb-core:jar:2.3.1`

Use Spring Boot 2.1.0.RELEASE

**Comment by philwebb** [comment]
We don't provide a managed dependency for `com.sun.xml.bind:jaxb-core` but we do for `javax.xml.bind:jaxb-api:2.3.1` which is in [maven central](http://central.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/).

Where is your `com.sun.xml.bind:jaxb-core` dependency coming from? Can you please share a project that shows the problem you're facing.

**Comment by koval4uk** [comment]
Thanks, I'm inattentive. BOM don't have com.sun.xml.bind:jaxb-core, but i use <javax-jaxb.version> with com.sun.xml.bind:jaxb-core

**Comment by philwebb** [comment]
>  I use `<javax-jaxb.version>` with `com.sun.xml.bind:jaxb-core`

I'm afraid that won't work and you'll need to manage your own version if you really want to use ` com.sun.xml.bind:jaxb-core`
