### ISSUE TITLE
The onstatus method of webclient causes a memory leak.

### ISSUE THREAD

**Issue by KimSeongIl** [spring-projects/spring-boot#15119]
spring boot version : 2.0.4.RELEASE, 2.1.0.RELEASE

```
private WebClient webClient;

    private final static int DEFAULT_CONNECT_TIMEOUT = 900;
    private final static int DEFAULT_SOCKET_TIMEOUT = 900;

    @PostConstruct
    public void initialize() {
        ReactorClientHttpConnector connector = new ReactorClientHttpConnector(options ->
                options.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, DEFAULT_CONNECT_TIMEOUT)
                        .poolResources(PoolResources.fixed("httpPool", 1000))
                        .afterNettyContextInit(ctx -> {
                            ctx.addHandlerLast(new ReadTimeoutHandler(DEFAULT_SOCKET_TIMEOUT, TimeUnit.MILLISECONDS));
                        }));

        webClient = WebClient.builder()
                .clientConnector(connector)
                .build();

    }

@GetMapping("/test")
    public Mono<String> webclientTest() {

        return webClient
                .get()
                .uri("http://testurl.com/response500test")
                .retrieve()
                .onStatus(httpStatus -> httpStatus != HttpStatus.OK, clientResponse -> Mono.error(new RuntimeException(String.format("api status: %s", clientResponse.statusCode()))))
                .bodyToMono(String.class);
    }
```

The above source code called an API that responded to 500 errors with 600 tps.

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 8573157383, max: 8589934592)
```

The onstatus method of webclient causes a memory leak.

![2018-11-07 2 01 06](https://user-images.githubusercontent.com/10323016/48113773-c7872380-e29f-11e8-8ffb-c5efd7a0f3f7.png)

In the photo attached above
We used the onStatus method from 13:40 to 13:48,
We removed the onStatus method from 13:55 to 14:00.
Is this a bug?
Why does the onStatus method cause a memory leak?

I used SpringBoot version 2.0.4 and upgraded to 2.1.0, but I still have a problem.

**Comment by wilkinsona** [comment]
Thanks for the report but `WebClient` is part of Spring Framework rather than Spring Boot. Spring Framework uses [JIRA](https://jira.spring.io/browse/SPR) for issue tracking. Please open an issue there if you would like to pursue this. If you do so, please comment here with a link to your issue so that others can find it.
