### ISSUE TITLE
spring-boot-dependencies 2.1.0.RELEASE missing groovy-all

### ISSUE THREAD

**Issue by prafsoni** [spring-projects/spring-boot#15112]
After upgrading to sb-2.1.0.RELEASE, I have to explicitly provide version for `'org.codehaus.groovy:groovy-all'`. I checked maven and I don't see groovy-all in dependencies, Is this change intentional ?

**Comment by bclozel** [comment]
In Groovy 2.5, `groovy-all` changed significantly and doesn't exist as a Jar anymore (see [Groovy release notes](http://groovy-lang.org/releasenotes/groovy-2.5.html)) and #13670.

This change is intentional and you should look into those release notes to figure out what to do for your application.

**Comment by dansomething** [comment]
I'm really surprised there is no mention of the change to Groovy 2.5 in any of the Spring Boot 2.1 release notes?

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes
https://spring.io/blog/2018/10/30/spring-boot-2-1-0
