### ISSUE TITLE
update StatsdMetricRegistryExportAutoConfiguration to support custom HierarchicalNameMappers

### ISSUE THREAD

**Issue by dkuc84** [spring-projects/spring-boot#15116]
[StatsdMetricsExportAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/statsd/StatsdMetricsExportAutoConfiguration.java#L64) creates [StatsdMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L67) using default hierarchical name mapper. Unfortunately it is not possible to update the name mapper using [MeterRegistryCustomizer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/MeterRegistryCustomizer.java) as micrometer does not allow to change it after the meter registry was already created.

Two possible workarounds:
* disable `StatsdMetricsExportAutoConfiguration` and reimplement the beans in the target app configuration class
* enable bean overriding (`spring.main.allow-bean-definition-overriding=true`) and only override `StatsdMeterRegistry` bean in the target app configuration class

While it is possible to use those workarounds it would be great if this could be supported in the auto configuration class especially since `HierarchicalNameMapper` is used in the [default (ETSY)](https://github.com/etsy/statsd/blob/master/docs/metric_types.md) flavor.

**Comment by wilkinsona** [comment]
There’s no need to disable the auto-configuration or to allow bean overriding at the auto-configured registry is `@ConditionalOnMissingBean`. If you declare your own `StatdMeterRegistry` bean, configured to meet your needs, the auto-configured bean will back off.

**Comment by dkuc84** [comment]
AFAIK `@Conditionals` are evaluated just once when given configuration class is read (and not against the whole context*) based on the specified configuration order (if provided). Unless order is explicitly enforced it is fairly easy to break it especially when multiple configuration classes are loaded through component scanning. With spring boot 2.1 default behavior of disabling bean overrides those manifest as `BeanDefinitionOverrideException`. 

*unless this behavior changed recently

**Comment by wilkinsona** [comment]
Ordering of auto-configuration classes is explicitly enforced and always has been. They are loaded and their conditions are evaluated after all user-contributed beans. This is unaffected by component scanning, unless it has been misconfigured to cover auto-configuration classes within the `org.springframework.boot` package space.

Auto-configurations can also be ordered both absolutely and relatively. Even if another auto-configuration will provide the alternate `StatsdRegistry` bean, it can be ordered with `@AutoConfigureBefore(StatsdMetricsExportAutoConfiguration)` to ensure that it's registry is defined first, thereby causing the default auto-configured registry to back off.

**Comment by dkuc84** [comment]
Thanks for the follow ups. It turned out to be an issue with my `SpringBootTest`.
