### ISSUE TITLE
Mysql JSON data type as a result creates Character object with the first charater of the json only

### ISSUE THREAD

**Issue by raxim1** [spring-projects/spring-boot#15117]
https://stackoverflow.com/questions/38568930/cannot-extract-mysqls-json-column-using-spring-data-jpa

It's a very basic issue, which hasn't been solved in the last 2 years.

It would be better, if the jackson serializer can be triggered automatically, and i can just get back the List of typed object. (it would be far more cleaner code)

spring boot: 2.0.6.RELEASE

Naturally i'm using if for independent (no entity class behind - so i cannot use the NativeQuery annotation) native report queries. I'm not sure whether it's a good approach, however my code is much more cleaner, as i don't need to transform the data. (temporary table contains it in a structured way anyway)

**Comment by wilkinsona** [comment]
Thanks for the report, but Spring Data JPA is managed as a separate project. It uses [JIRA](https://jira.spring.io/browse/DATAJPA) for issue tracking. Please open a `DATAJPA` issue if you'd like to pursue this. If you do so, please comment here with a link so that others can find it.
