### ISSUE TITLE
Change DataSourceHealthIndicator details from "hello" to "result"

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15114]
See [this comment](https://github.com/spring-projects/spring-boot/pull/15055#issuecomment-436188728). Let's do that as a separate issue to we can track it.

**Comment by restolho** [comment]
@philwebb This would be my first contribution to an open source project but it seems simple enough. You think i could take this?

**Comment by philwebb** [comment]
@restolho Yes please, that would be great! If you need any help just shout.

**Comment by snicoll** [comment]
Closing in favour of PR #15136
