### ISSUE TITLE
If you do not visit a redis for a long time, you will have this exception.

### ISSUE THREAD

**Issue by shanchanghui** [spring-projects/spring-boot#15122]
error：
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: The remote host has forced an existing connection to close.

The connection from redisTemplate can not be used. How can we ensure the normal use of this connection?

The connection in the redis connection pool is kept up to date?

**Comment by wilkinsona** [comment]
You have already opened a [Lettuce issue](https://github.com/lettuce-io/lettuce-core/issues/912) for this. Please do not cross-post issues, particularly without indicating that you have done so. It's a waste of people's time and that time that could have been spent trying to help someone.
