### ISSUE TITLE
DevTools: ClassCastException when using custom Hibernate types

### ISSUE THREAD

**Issue by Katona** [spring-projects/spring-boot#15127]
I know there several similar issues like this but I couldn't find a solution to this problem apart from turning completely off devtools' restart facility with `-Dspring.devtools.restart.enabled=false`.

I have a user type implementing `org.hibernate.usertype.UserType` in my project and I am facing `ClassCastException`s when the deserialized object is to be assigned to one of the fields of the entity object. I checked the class loaders and I can see that the deserialized object has been loaded by the `AppClassLoader` while the the class of the field is loaded by the `RestartClassLoader`. So, this seems to be the typical case when the `AppClassLoader` needs a class defined in the project which is normally loaded by the `RestartClassLoader` hence the `ClassCastException`. I went on with trying to include hibernate in the classpath of the `RestartClassLoader` by including the following line in  `META-INF/spring-devtools.properties`
```
restart.include.hibernate=/hibernate-.*jar
```
However, my service fails to start with the only error in the logs being

```
2018-11-07 17:17:26.099  WARN 6810 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
```
I am stuck here at the moment.

I am using `spring-boot-devtools:2.0.4.RELEASE`.

**Comment by wilkinsona** [comment]
Unfortunately we're stuck too without some more information. If you'd like us to spend some time investigating and trying to help you, please take the time to provide a minimal and complete sample project that reproduces the `ClassCastException`.

**Comment by Katona** [comment]
I managed to create a sample project here based on `gs-accessing-data-jpa`: https://github.com/Katona/devtools-jpa-exception. The custom type `hello.JsonType` is a generic type mapping for storing any Java type as JSON string in the db. And by now, I also know that the problem is caused by using `org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl` to load the Java class to serialize into. If I change the line 107

**Comment by wilkinsona** [comment]
Thanks for letting us know.
