### ISSUE TITLE
Streamline WebTestClient creation and customization in integration tests

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-boot#15132]
The docs [show an example](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-with-mock-environment) of using the `WebTestClient` but nothing to show how to customize its configuration like [this section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-webclient-customization) does for the `WebClient`. I did find `WebTestClientBuilderCustomizer` but that should be explained in the reference and if there are other options, those could be mentioned too.

This is based on [related comment](https://jira.spring.io/browse/SPR-17039?focusedCommentId=163282&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-163282) under SPR-17039.

**Comment by michaldo** [comment]
@rstoyanchev, your proposal does not apply case 
`@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)`
In that case test framework setup host and port inside `WebTestClient` and `@Before mutate()` clears that data. Eventually, client does not know hostname nor port.

That is why I wrote *The only way I found is drop autoconfigured webclient and create custom one.*

**Comment by rstoyanchev** [comment]
Oh, I see now. You want to customize the UriBuilderFactory but that overrides the baseUrl set up by Boot. Hm, I'm not sure I see both the test code and Boot are effectively competing to customize the UriBuilderFactory.

**Comment by wilkinsona** [comment]
The `WebTestClient` produced by `@AutoConfigureWebTestClient` can be customized using a `@TestConfiguration` static inner-class that defines a `@Bean`:

```java
@TestConfiguration
static class BuilderCustomizerConfiguration {

	@Bean
	WebTestClientBuilderCustomizer customizer() {
		return (builder) -> {
			builder.filter((request, next) -> {
				System.out.println(request.method() + " " + request.url());
				return next.exchange(request);
			});
		};
	}

}
```

This is an imperfect solution, though. Using `@AutoConfigureWebTestClient` means that `WebTestClientContextCustomizer` backs off. The auto-configured `WebTestClient` is found in the bean factory so it does not create a `WebTestClient` bean with a customized base URL. The auto-configured `WebTestClient` still works despite not knowing the port on which the server is running as it uses `HttpHandlerConnector`, calling the `HttpHandler` directly rather than going via the network stack and HTTP.

I think this is more than a documentation issue as I don't think we have a particularly good solution to document at the moment.

**Comment by wilkinsona** [comment]
When a test is annotated with `@SpringBootTest` that has an embedded web environment, `spring-boot-test` will:

-  register a `TestRestTemplate` bean with a custom `UriTemplateHandler` that takes into account the use of SSL and the local server port. Customization is supported via a `RestTemplateBuilder` bean which, if present in the context, will be used to create the `TestRestTemplate`.
- register a `WebTestClient` bean with a customized base URL that takes into account the use of SSL and the local server port. No further customization is supported.

There are some other difference in `spring-boot-test-autoconfigure` but things aren't directly comparable as mock testing comes into play where the servlet-based stack uses `MockMvc` while the reactive stack uses an application context bound `WebTestClient`. There's also `MockRestServiceServer` for testing `RestTemplate` usage for which the reactive stack has no equivalent. For the time being at least, I think we may be best served by focusing on the differences in `spring-boot-test`, specifically the lack of `WebTestClient` customization that's offered.

**Comment by wilkinsona** [comment]
[Here's](https://github.com/wilkinsona/spring-boot/tree/gh-15132) a proposal for the team's consideration. It implements the second of the two options listed [above](https://github.com/spring-projects/spring-boot/issues/15132#issuecomment-534052239). It still limits support to a server bound `WebTestClient`. I think that expanding it to include mock environments should be considered in a separate issue as it also raises the question about `MockMvc` when using the Servlet stack.
