### ISSUE TITLE
Using springboot 2.1.0 to integrate zuul

### ISSUE THREAD

**Issue by Madisoon** [spring-projects/spring-boot#15140]
error:The bean 'counterFactory', defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration$ZuulCounterFactoryConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration$ZuulMetricsConfiguration.class] and overriding is disabled.

**Comment by snicoll** [comment]
Thanks but Zuul is [not managed here](https://github.com/spring-cloud/spring-cloud-netflix) and you may want to check you're using the proper Spring Cloud version as I suspect this is fixed already.

**Comment by Madisoon** [comment]
thanks
