### ISSUE TITLE
Surefire plugin throws exception: Could not find or load main class ...ForkedBooter

### ISSUE THREAD

**Issue by daniloteodoro** [spring-projects/spring-boot#15150]
**Problem**: running command like `./mvnw test` results in the following error:

> Created at 2018-11-11T10:18:36.176
> Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter
> Created at 2018-11-11T10:18:36.177
> Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.booter.ForkedBooter

**How to reproduce the problem**: Just go to https://start.spring.io/ , create a project with default options (Maven, Java, Spring Boot 2.1.0) and run `./mvnw test` on it.

**Possible solution**: Adding the following configuration to Surefire plugin on pom.xml as stated here: https://stackoverflow.com/questions/50661648/spring-boot-fails-to-run-maven-surefire-plugin-classnotfoundexception-org-apache

```
<configuration>
    <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
</configuration>
```

My configuration:
OpenJDK 10.0.2 on Ubuntu 18.04, Spring Boot 2.1.0

**Comment by snicoll** [comment]
Thanks but I don't really understand why you are reporting a surefire problem here. There is nothing we can do about it and [it has already been reported anyway](https://issues.apache.org/jira/browse/SUREFIRE-1588)

**Comment by wilkinsona** [comment]
I think it’s also worth noting that you are using Java 10 which is no longer supported. I would recommend upgrading to Java 11.

**Comment by daniloteodoro** [comment]
@snicoll The reason is that some Spring Boot 'parent' POM.xml contains configurations for plugins, so that would be possible to add this extra configuration and avoid developers having trouble with this. But as the solution from Surefire is already been developed, maybe it's better just to wait for it (thanks for that link btw)
