### ISSUE TITLE
Document escaping of blanks/spaces in application.properties

### ISSUE THREAD

**Issue by lathspell** [spring-projects/spring-boot#15157]
I tried to add a map that has keys with spaces to my `application.properties` files.

Neither https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html nor https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding had an example for spaces.

The following seems to work, every other method using single-quotes or double-quotes didn't.

   models[Foo\ Bar] = Baz

(It's probably a general feature of the properties format and not really SpringBoot specific but as you have a whole wiki page dedicated on how special cases can be written, it would be nice if it was mentioned there)

**Comment by mbhave** [comment]
We have a [wiki page](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#maps) that's dedicated to relaxed binding. There's a link to it from [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding#relaxed-binding). I've added an [example](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#maps) for binding to maps with spaces in the key.
