### ISSUE TITLE
Wrong default unit for "spring.servlet.multipart" sizes

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15162]
`spring.servlet.multipart.max-file-size` and `spring.servlet.multipart.max-request-size` have a default value of 1MB and 10MB respectively. Previously these where handled as raw string value with ad-hoc parsing and moved to `DataSize` in 2.1

Unfortunately, their unit were set to MB while the former code was considering a raw number to be in bytes. This means that a user upgrading without the suffix will get different sizes. For consistency with 2.0 we should consider change the unit to bytes (basically removeing the two overrides we have at the moment).

**Comment by pbetkier** [comment]
I would consider requiring the unit to be set explicitly, i.e. no default units. This way if someone has raw number, without the suffix, he gets a loud failure during startup after upgrading to new version. It also seems more readable to me.

**Comment by snicoll** [comment]
@pbetkier thanks for the feedback but that's not an option for those upgrading. We have a bunch of `long` properties that were migrated to `DataSize` and we still need to accept the raw value.
