### ISSUE TITLE
Validation always fails if a @ConfigurationProperties bean is a @Scoped proxy

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#1516]
Validation always fails if a `@ConfigurationProperties` bean is a `@Scoped` proxy because it is applied in a `BeanPostProcessor` in `postProcessBeforeInitialization()` (at which point it is not fully initialized). There is a good reason to bind in `postProcessBeforeInitialization()`, so that the beans can validate themselves in `@PostConstruct`, but the validation might be deferrable.

**Comment by snicoll** [comment]
I was discussing this one with @dsyer and we're unable to reproduce the issue. Closing for now.
