### ISSUE TITLE
Source Code of  Spring One Talk: It's a Kind of Magic: Under the Covers of Spring Boot - Brian Clozel, Stéphane Nicoll

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-boot#15170]
@bclozel I have gone through this talk to learn magic done by Spring Boot. It was promished to share source code of talk at the end of talk. But I coudn't find that mentioned at the end of talk. I have also checked homepage of talk at youtube
at: https://www.youtube.com/watch?v=jDchAEHIht0
And comments below by various viewers, but coudn't find the source code.
One comment list github repo of source code at:
https://github.com/snicoll?tab=repositories﻿
But this url has many git repos and I even tried to go to any repo to find the source code, but coudn't find
the source code of talk. 
Can we have the source code of talk, so we can go through it to understant it clearly.

**Comment by snicoll** [comment]
@ankurpathak I've added a comment to that youtube video that points to https://github.com/snicoll-demos/hello-service-auto-configuration

**Comment by ankurpathak** [comment]
@snicoll Thanks.
