### ISSUE TITLE
Add actuator health check support for Elasticsearch REST Clients

### ISSUE THREAD

**Issue by anthofo** [spring-projects/spring-boot#15174]
Hi,

Spring Boot 2.1 add auto-configurations for ElasticSearch `RestClient` and `RestHighLevelClient`.
It works well, but there is no actuator health check for the ES Rest clients.

There are two existing HealthIndicator for ES:
- ElasticsearchHealthIndicator: it works only with the **tcp** client, not the **rest** one
- ElasticsearchJestHealthIndicator: it works only with the **Jest** client

A solution would be to add an `ElasticsearchRestHealthIndicator` or to make the existing `ElasticsearchHealthIndicator` work with both **tcp** and **rest** clients.

For now, I use my own implementation:

```Java
@Component
public class ElasticsearchHealthIndicator extends AbstractHealthIndicator {

	@Autowired
	private RestHighLevelClient client;

	@Override
	protected void doHealthCheck(Health.Builder builder) throws IOException {
		ClusterHealthResponse response = client.cluster().health(new ClusterHealthRequest(), RequestOptions.DEFAULT);

		switch (response.getStatus()) {
			case GREEN:
			case YELLOW:
				builder.up();
				break;
			case RED:
			default:
				builder.down();
				break;
		}
	}
}
```

**Comment by nishantraut** [comment]
How is this enhancement planned to implement? Planning to add ElasticsearchRestHealthIndicator similar to ElasticsearchHealthIndicator using RestHighLevelClient, can someone give me pointers would like to raise PR.

**Comment by mbhave** [comment]
Thanks for offering to help, @nishantraut although it looks like we've received a [PR](https://github.com/spring-projects/spring-boot/pull/15211) for this issue.
