### ISSUE TITLE
Provide metric auto-configuration for spring data repository

### ISSUE THREAD

**Issue by jfougere** [spring-projects/spring-boot#15185]
With spring actuator we get automatically metrics around a whole bunch of things (jvm, cpu, tomcat, file, log, mvc, jersey, webflux, http client, rabbitmq, hibernate, cache, datasource, etc...) but we don't get any metrics related to spring data repositories.

In my case, I would be interested in having time gauge around JPA repository methods.
Tags could be automatically added with class & method names.

What do u think ? 

_On my side, I have this working fine for JpaRepository. I haven't propose a PR because I didn't manage to do it the auto-configuration way (did not find a way to dynamically replace/prevent the default repositoryFactoryBean so I went the annotation way by providing an EnableJpaMetricsRepositories annotation)_

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Similar to the [discussion about metrics for `WebServicesTemplate](https://github.com/spring-projects/spring-boot/pull/13373), I think the bulk of the support belongs in Spring Data where it will benefit everyone and not just those using Spring Boot. Spring Boot could then auto-configure that support. If you'd like to pursue this, please open a [Spring Data Commons issue](https://jira.spring.io/projects/DATACMNS) and comment here with a link to it.

I'm going to close this issue for now at least. We can re-open it or open a new issue if/when the foundations are in place in Spring Data. In the meantime, I believe you could implement metrics for Spring Data repositories using an aspect which would remove the need to replace the default repository factory bean. There's a little bit of information about intercepting calls to a repository in the [Spring Data JPA documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#_common). It's using XML configuration, but hopefully it will still provide a general idea of what to do.

**Comment by jfougere** [comment]
Issue opened on Spring Data Commons: [DATACMNS-1420](https://jira.spring.io/browse/DATACMNS-1420)
