### ISSUE TITLE
Upgrade to Spring Data Moore M2

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15197]
When we do, we should revert b6aff10

**Comment by mp911de** [comment]
Summary of dependency upgrades to consider
* Elasticsearch 6.5.4 -> 6.6.1
* MongoDB 3.8.2 -> 3.10.1
* Lettuce 5.1.4.RELEASE -> 5.1.5.RELEASE
* Spring Hateoas 1.0.0.BUILD-SNAPSHOT -> 1.0.0.M1
* Spring Plugin 2.0.0.BUILD-SNAPSHOT -> 2.0.0.M1

Skipped dependencies that already match versions used for Spring Data Moore M2.

**Comment by wilkinsona** [comment]
Thanks, @mp911de. We should be aligned there now. Do you have any plans to upgrade to the latest Reactive Mongo driver?

**Comment by mp911de** [comment]
Missed that one, here's our [upgrade ticket DATAMONGO-2220](https://jira.spring.io/browse/DATAMONGO-2220).

**Comment by wilkinsona** [comment]
Thanks again. We're aligned there too now. One last one (I hope). How about Cassandra's driver? Boot and SDC are currently on 3.6.0 but the latest is 3.7.1.

**Comment by mp911de** [comment]
Spring Data Cassandra is now upgraded to Cassandra driver 3.7.1 and Spring Data Couchbase now also uses Couchbase Client 2.7.4.

**Comment by wilkinsona** [comment]
Thanks again, @mp911de. We're aligned on Cassandra's driver now too.
