### ISSUE TITLE
Remove redundant dependency management for dom4j:dom4j

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15199]
We were managing it for Hibernate's benefit and it has moved to org.dom4j:dom4j.

**Comment by charanbir** [comment]
This is my first contribution to your codebase. I signed the CLA. Please let me know if I missed anything. Thanks in advance.

$ mvn dependency:tree | grep dom4j
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile
[INFO] |  +- org.dom4j:dom4j:jar:2.1.1:compile (optional)
