### ISSUE TITLE
Add ClassPathResource overrides to org.springframework.boot.web.server.Ssl

### ISSUE THREAD

**Issue by jonfreedman** [spring-projects/spring-boot#15209]
In order to facilitate programmatic configuration of SSL e.g. configuration which interacts with a password manager explicitly it would be great to allow the KeyStore/TrustStore to be set as a `ClassPathResource` as currently I end up with the following code:

```java
ssl.setKeyStore("classpath:" + keystoreLocation.getPath());
```

**Comment by philwebb** [comment]
Can you provide a bit more background for this issue. Specifically, which web server are you using (Tomcat, Jetty, Netty etc) and how are you applying the code above?

If I remember correctly, not all servers can load stores from classpath resource. Most use plain `File` reference so won't work with classpath resources that are packaged inside a jar. Have you seen the `SslStoreProvider` interface that was added to support loading stores from other locations?
