### ISSUE TITLE
Spring Data Rest - Cassandra - Couldn't find PersistentEntity

### ISSUE THREAD

**Issue by nagrm** [spring-projects/spring-boot#15217]
I am using spring-boot-starter-data-rest and spring-boot-starter-data-cassandra in Spring Boot 2.1.0.RELEAS.

When i access User resource the following exception happens:
_java.lang.IllegalArgumentException: Couldn't find PersistentEntity for type class com.demo.cassandradatarest.entity.User!_

I use the below configuration class: 

```
@SpringBootApplication
@EnableAutoConfiguration(exclude={CassandraDataAutoConfiguration.class})
public class CassandraDataRestDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(CassandraDataRestDemoApplication.class, args);
	}
}

```

**Comment by wilkinsona** [comment]
Given that the problem appears to be with Spring Data Cassandra and that Spring Boot is not involved there (you have excluded the auto-configuration of Spring Data Cassandra), it is not clear to me why you believe this to be a problem with Spring Boot. You also haven’t provided enough information to identify where the problem might actually be.

If you would like us to spend some more time on this, please take the time to provide a complete and minimal sample (something that we can unzip or git clone and run) that reproduces the problem.

**Comment by nagrm** [comment]
Thanks for your fast response Wilkinsona.
The attached project has just the required code. Please check.
[cassandra_data_rest_demo.zip](https://github.com/spring-projects/spring-boot/files/2598692/cassandra_data_rest_demo.zip)

**Comment by nagrm** [comment]
Ok, thanks Wilkinsona. I will try as you have suggested.

**Comment by nagrm** [comment]
Thanks a lot Wilkinsona. 
Adding entity to CassandraMappingContext fixed the issue.
