### ISSUE TITLE
Spring boot 2.1.0.RELEASE jpa persists entity's DATETIME filed incorrectly!

### ISSUE THREAD

**Issue by airxiechao** [spring-projects/spring-boot#15218]
I am using spring-boot 2.1.0.RELEASE and mysql 5.7.21, centos 7.5

I have an entity class with a Date filed :
`
@Column(name = "create_time")
private Date createTime;
`

When persists this entity, it turns out to save a different value in database. I turns on general_log in mysql to see the insert sql, the insert value('**2018-11-20 00:02:44.034**') in sql is different from what I insert('**2018-11-20 14:02:44**''). It seems to have a timezone transformation from UTC+8:00(**Asia/Shanghai (CST, +0800)**)(my system's timezone) to UTC-6:00(**America/Chicago (CST, -0600)**). 

When I switch to spring-boot 2.0.6.RELEASE, there is no such problem.

**Comment by snicoll** [comment]
There is nothing in Spring Boot doing that. However the mysql driver has been upgraded between 2.0.x and 2.1.x. As Spring Boot does not do anything there I am going to close this issue.

**Comment by airxiechao** [comment]
Thanks, I found mysql-connector-java's bug report here: https://bugs.mysql.com/bug.php?id=91112
