### ISSUE TITLE
Environment variable bound behavior differs 

### ISSUE THREAD

**Issue by mumutu66** [spring-projects/spring-boot#15213]
Spring Boot version is 1.5.14
injecting a variable with the key like `foo.bar.bird-talk.platToken` which include "-"  lowercase and uppercase
we are using docker image to deliver application so the configurations is inside the os 's environment and obey the spring convention. we expect the  `FOO_BAR_BIRD-TALK.PLATTOKEN` to bound to the previews variable.
following are three environments
* windows10 
  * java version "1.8.0_111" 
  * java(TM) SE Runtime Environment (build 1.8.0_111-b14)
  * Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
* linux alpine:3.7
  * openjdk version "1.8.0_121"
  * OpenJDK Runtime Environment (IcedTea 3.3.0) (Alpine 8.121.13-r0)
  * OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
* linux openjdk:8u181-jre-slim-stretch
  * openjdk version "1.8.0_171"
  * OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
  * OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

the problem in the first and second circumstance the env variable works well while in the left one it failed the Env variable cannot bind to the property in application.  and I haven't dived into the code to find out the reason ..cuz I don't where to start. and I am glad if u can provide me some hints , thanks

I have no idea if I missed something..  If it is not a issue ...feel free to close the ticket

**Comment by mumutu66** [comment]
@wilkinsona  thanks ~ I will investigate it

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mumutu66** [comment]
After few days research I finally found the reason, the `sh` in openjdk:8u181-jre-slim-stretch not support the env variable name with dash while it's  `bash` supports , really drive me mad ....and docker uses `sh` as a default execution environment .. emm  nothing to do with Spring ~~, but it would be pretty nice if there exists some tips in the document  of System ENV properties to tell others need to take care or avoid using env variable with dash~
