### ISSUE TITLE
Add Annotation for bean overriding

### ISSUE THREAD

**Issue by huehnerlady** [spring-projects/spring-boot#15216]
We like the idea that with spring boot 2.1.0 the default value for the property `spring.main.allow-bean-definition-overriding` is now set to false. 

But this comes with a challenge. We have tests which override one specific bean with a mock for integration testing. Now for these tests we get a BeanOverrideException. 
We currently use the workaround with setting the property `spring.main.allow-bean-definition-overriding` to `true` for these specific tests, but in the end we might miss other overridden beans in a test which makes the app fail to start later. So we have to add another (expensive) Integration test that checks whether the app starts up without any errors.

So my proposal is to add an annotation - kind of similar to `@Primary`, that says that you actively want to override ONE SPECIFIC bean and make THIS bean primary. 

Other idea is to just have an annotation to allow ONE SPECIFIC bean to be overridden and add the `@Primary` annotation as well.

What do you think?

**Comment by wilkinsona** [comment]
It's an interesting suggestion. Thank you. I'd prefer to avoid adding to the programming model if we can, though.

There are a few existing ways, of varying degrees of elegance, to achieve what you want:

- Use`@MockBean` to replace a bean with a mock for integration testing
- Use a `BeanPostProcessor` in your tests to swap out the bean that's normally used and replace it with a mock
- Get your hands really dirty and use a `BeanFactoryPostProcessor` to replace the bean definition. This is what the `@MockBean` infrastructure does under the covers.

Do any of the above meet your needs?

**Comment by huehnerlady** [comment]
@wilkinsona this sounds very interesting, I tried the `@MockBean` annotation which sounds like what I want, but unfortunately this does not work with Spock what we use as a test framework.

In [this issue](https://github.com/spring-projects/spring-boot/issues/9372) it sounds like you will not provide native support for Spock and the library mentioned in there does ed up in the same problem with the BeanDefinitionOverrideException.

Will there be a change of mind and maybe support spock after all then?

**Comment by wilkinsona** [comment]
Sorry, but I don't think this issue will cause us to change our minds about supporting Spock with `@MockBean`. It should be possible for the library mentioned in #9372 to avoid the `BeanDefinitionOverrideException` by calling `BeanDefinitionRegistry.removeBeanDefinition(name)` before it registers the double. You'd need to do something similar in your own code if you went down the `BeanFactoryPostProcessor` route in your own code.

**Comment by huehnerlady** [comment]
So you will not think about adding such an annotation to the spring boot framework then? 

Something like `@Override`?

**Comment by philwebb** [comment]
@huehnerlady That would be something that the Spring Framework team would need decided. You can raise a JIRA [here](http://jira.spring.io) for them to consider it if you like. I'd personally not be in favor of adding an additional annotation.

**Comment by huehnerlady** [comment]
For other people who might be interested: https://jira.spring.io/browse/SPR-17519
