### ISSUE TITLE
Check for other DataSource unwrapping calls

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15227]
The update in https://github.com/spring-projects/spring-boot/pull/15206 may apply to other areas of the code. We should do a sweep to check.

**Comment by wilkinsona** [comment]
The `instanceof` checks in `DataSourcePoolMetadataProvidersConfiguration` might be problematic.

**Comment by snicoll** [comment]
There are potentially others, non Tomcat datasource related. I've started to work on this in the base PR and will adapt here after.
