### ISSUE TITLE
SpringBoot start when init StandardAnnotationMetadata

### ISSUE THREAD

**Issue by gougouzcm** [spring-projects/spring-boot#15224]
I am running a spring boot project with 
spring spring-boot-starter-2.0.3.RELEASE
spring-cloud-dependencies-Finchley.RELEASE

It will error when startup.
![image](https://user-images.githubusercontent.com/16322041/48831749-72283780-edb2-11e8-9926-0f4d192b6912.png)

I found a similar issues [issue](https://github.com/spring-cloud/spring-cloud-stream/issues/1175)

I exclude the `actuator `dependency as that issue said  , but still not work.

jdk version is 
![image](https://user-images.githubusercontent.com/16322041/48833979-8b7fb280-edb7-11e8-9a0d-b0b89750fbf4.png)

**Comment by wilkinsona** [comment]
An `ArrayStoreException` occurs when an annotation has a `Class` attribute that references a class that is not on the classpath. Unfortunately, the JVM's diagnostics are rather poor and the exception does not provide any information about which class is missing. You can, however, get that information using the debugger.

If you create an entry breakpoint on the constructor of sun.reflect.annotation.TypeNotPresentExceptionProxy.TypeNotPresentExceptionProxy and debug your application, the `Throwable` that is passed into it will show which class is missing. Can you please try that and comment on this issue with the message and stack trace of that `Throwable`? If you're not comfortable doing that then we can investigate on your behalf but to be able to so do we'll need a complete and minimal sample (something that we can unzip or git clone and run) that reproduces the problem.

**Comment by gougouzcm** [comment]
you are right. thank you .
