### ISSUE TITLE
Support for externalized configuration at Servlet container

### ISSUE THREAD

**Issue by uzikhanak** [spring-projects/spring-boot#15233]
I know that standalone Spring Boot application supports externalized configuration via ‘_spring.config.location_’ java system property. However, it is not much usable at Servlet container environment as the system property is shared with all other deployed Spring boot applications.
It is a common need to deploy slightly different versions of the same application in one Servlet container with possibility to define independently different external configuration for each one. Imagine I have two app versions myApp-1.4.war and myApp-1.5.war with fixed bug. Then I want to deploy them into one Tomcat server and compare their behavior. Currently they will share configuration defined by ‘_spring.config.location_’ system property and log configuration as well.

In my other non Spring Boot project I derive path to external configuration from application _contextPath_. First thing which I do when application starts is getting _contextPath_  by _ServletContext. getContextPath()_ at _ServletContextListener_ and read a system property for example  ‘_apps.extern-base_’. Then I construct path to external configuration like `${apps.extern-base}/${contextPath}/conf`, read log configuration from there and initialize log system. After that I read other configuration files and initialize Spring framework.

To achieve the same functionality with Spring Boot application the _contextPath_ must be available at very early phase of application initialization at _SpringApplicationBuilder_ so it can be used at overridden method
`org.springframework.boot.web.support.SpringBootServletInitializer.configure(SpringApplicationBuilder builder)`

**Comment by wilkinsona** [comment]
The context path is already available to you in your `SpringBootServletInitializer` subclass by overriding one of the methods that takes the `ServletContext` as a parameter. For example, you can do this:

```java
import javax.servlet.ServletContext;
import javax.servlet.ServletException;

import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ServletInitializer extends SpringBootServletInitializer {

	private ServletContext servletContext;

	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		this.servletContext = servletContext;
		super.onStartup(servletContext);
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
		String contextPath = this.servletContext.getContextPath();
		// Configure the builder using the context path
		return builder;
	}

}
```

Does this meet your needs?

**Comment by uzikhanak** [comment]
Yes, it works exactly as I need. Great! Thank you!

**Comment by wilkinsona** [comment]
Great. Thanks for letting us know.
