### ISSUE TITLE
Allow for a use case where the startup script is written not at the start of the jar but seperatly

### ISSUE THREAD

**Issue by cranphin** [spring-projects/spring-boot#15235]
Basically what we would like is an option for the script that's prepended to the jar when spring-boot:repackage with 'executable' set to true is used, to be written to a text/sh file next to the jar.

The reason for wanting this is that our system admins would like us to provide this script, but want to be able to customize it for different systems, especially the part under: ### BEGIN INIT INFO,
which cannot be changed using the .conf file.

We could manually remove the generated file once from the jar, and use that, but ideally we would like to benefit from any improvements with new versions of the default script.

I'm open to suggestions for better approaches to this as well :)

Ofcourse, with the script file seperatly, we would have to provide a JARFILE environent variable to let the script know where to find it's jar.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think this is something that we should support in Spring Boot itself as it's already possible using mechanisms provided by Maven or Gradle. The script is packaged in `spring-boot-loader-tools` at `org/springframework/boot/loader/tools/launch.script` from where you could extract it.

For example, you could do that using Gradle as follows:

```
configurations {
	launchScript
}

dependencies {
	launchScript('org.springframework.boot:spring-boot-loader-tools') {
		transitive = false
	}
}

task extractLaunchScript(type: Copy) {
	from zipTree(configurations.launchScript.singleFile).matching {
		include '/org/springframework/boot/loader/tools/launch.script'
	}
	into buildDir
	includeEmptyDirs = false
	filesMatching('**') {
		path = 'launch.script'
	}
}

```

The `extractLaunchScript` task will result in the script being written to your project's `build` directory.

I believe you can do something similar with Maven using the dependency plugin's unpack goal.

**Comment by wilkinsona** [comment]
Ah, sorry, I'd overlooked the placeholder side of things. `DefaultLaunchScript` is the class that performs the replacement. It's public API and should therefore remain stable. Using it actually simplifies things considerably:

```groovy
import org.springframework.boot.loader.tools.DefaultLaunchScript

// …

task writeLaunchScript {
	def properties = [
		'a': 'alpha',
		'b': 'bravo'
	]
	new File(buildDir, 'launch.script') << new DefaultLaunchScript(null, properties).toByteArray()
}
```
