### ISSUE TITLE
SpringBoot Migration for @EnableScheduling

### ISSUE THREAD

**Issue by StephanPraetsch** [spring-projects/spring-boot#15234]
Hi there,

we just noticed during a migration from SpringBoot 1.5.9 to 2.0.3 that our @Scheduled tasks haven't been executed anymore. A fix is to add @EnableScheduling. So far so good. But why don't we find anything for that in that migration guide? Obviously something was changed with SpringBoot 2: A dependency we use doesn't enable scheduling anymore? I don't know, I guess so. Maybe you could add this to the migration guide?

```
## @Scheduled
If you use @Scheduled annotion be aware that you might enable it on your own now by adding @EnableScheduling.
```

Kind regards
Stephan

**Comment by snicoll** [comment]
> we just noticed during a migration from SpringBoot 1.5.9 to 2.0.3 that our @scheduled tasks haven't been executed anymore.

Scheduling must always have been enabled explicitly and `2.x` doesn't change anything to that. My best guess is that you were relying on the fact an auto-configured component was applying `@EnableScheduling` for you (a feature of the Actuator comes to mind).

In short, your scheduled tasks have been working so far more by side effect than anything else and I don't think the upgrade has anything to do with it. I am going to close this issue. If you believe this is an upgrade problem, please share a sample that shows the difference and we can reconsider.

**Comment by StephanPraetsch** [comment]
Well, I won't reopen that issue though it is an upgrading problem - as you just added an assumption as well. But I don't want to investigate which dependency has a different behavior because we know the solution and our 1.5.9 code was incomplete (relying on an implicit behavior).

**Comment by snicoll** [comment]
>  as you just added an assumption as well

Enabling scheduling tasks is and never was auto-configured so you expecting that to work without any use of an explicit `@EnableScheduling` is wrong. There is no assumption in that IMO.

> If you use @Scheduled annotion be aware that you might enable it on your own now by adding @EnableScheduling.

The point I was trying to make is that we can't write that as it always was the case.
