### ISSUE TITLE
Upgrade to Lombok 1.18.4

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15268]

**Comment by owolabiezekiel** [comment]
this upgrade doesn't work recently with Spring boot. Looks like Spring can't find the dependency link

**Comment by philwebb** [comment]
@owolabiezekiel That sounds like an issue with your Maven cache. The artifact [is in central](http://central.maven.org/maven2/org/projectlombok/lombok/1.18.4/) and our CI build finds it without issue.
