### ISSUE TITLE
@EnableAspectJAutoProxy,@Aspect and @RestController

### ISSUE THREAD

**Issue by scizeron** [spring-projects/spring-boot#1529]
Hi, 

I use Spring-boot since few months and it's absolutely great but I have some problems with the association `@EnableAspectJAutoProx`, `@Aspect` and `@RestController`.

If I declare `@EnableAspectJAutoProxy` and a java bean with `@RestController`, nothing to add, it works great.

On the other side, if I add a @Aspect with a pointcut matching the bean with `@RestController`, I have no more request mapping. 
When I looked the debug output, the logger `RequestMappingHandlerMapping` is quiet, the request is not performed because the mapping is not registered. 
For info, the bean with the `@RestController` is an implementation of a simple java Interface and the `EnableAspectJAutoProxy` use the default interface-based JDK proxy approach.

Stéphane

**Comment by kidnan1991** [comment]
AFAIK, it uses same mechanism as proxyMode in @Component annotation.
The instance is not be injected but its proxy.
For more information, refer section 3.4.1 of Spring in action for detail explanation

**Comment by confool** [comment]
is  this explained？
