### ISSUE TITLE
Aspect order and DataSourceTransactionManagerAutoConfiguration with fixed "return Integer.MAX_VALUE;"

### ISSUE THREAD

**Issue by patoi** [spring-projects/spring-boot#1530]
As I see the DataSourceTransactionManagerAutoConfiguration ( https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceTransactionManagerAutoConfiguration.java ) __has fixed Order:__ return Integer.MAX_VALUE;

If I use two aspect I can't set neccessary order of the transaction.

```java
/**
* Save business transaction metadata and create transaction ID.
*/
@Aspect
@Order(Ordered.LOWEST_PRECEDENCE - 1)
@Component
public class TransactionAuditAspect {
...
```
```java
/**
* Save method input and output data, connected to the business transaction record with transaction ID.
*/
@Aspect
@Order(Ordered.LOWEST_PRECEDENCE)
@Component
public class MessageAuditAspect {
...
```
My service method:
```java
@Transactional
@TransactionAudit
@MessageAudit
public ServiceResult<MyClass> create(...
```

Aspects precedence: @Transactional <- @TransactionAudit <- @MessageAudit

__Logic:__ If application couldn't save MessageAudit data or TransactionAudit data, then business transaction (@Transactional create method) must be rollback.

__Problem:__
If I throw exception in MessageAuditAspect (Ordered.LOWEST_PRECEDENCE) then @Transactional method has been rollbacked, it is OK. __But if I throw exception in the TransactionAuditAspect (Ordered.LOWEST_PRECEDENCE - 1) then the @Transactional method hasn't been rollbacked!__

I annotated my app config with: __@EnableTransactionManagement(order = 0)__ but it doesn't solve my problem.
```java
@Configuration
@ComponentScan(basePackages = "com.mypackage")
@EnableAutoConfiguration
@EnableTransactionManagement(order = 0)
@EnableAspectJAutoProxy
public class TomcatStart { 
...
```

**Comment by wilkinsona** [comment]
SPR-12201 was closed as won't fix. Users affected by this problem should upgrade to Spring Boot 1.2.x.
