### ISSUE TITLE
Deprecate spring.rabbitmq.template.queue

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15301]
The [latest Spring AMQP release](https://github.com/spring-projects/spring-boot/issues/15271) has deprecated `setQueue` in favour of `setDefaultReceiveQueue`. We should probably adapt our configuration structure to match that change and deprecate `spring.rabbitmq.template.queue` in favour of `spring.rabbitmq.template.default-receive-queue`.

Given this change was introduced early in `2.1.x` I am tempted to make it for `2.1.1` still.

Let's see what the rest of the team thinks.

**Comment by snicoll** [comment]
ping @garyrussell

**Comment by wilkinsona** [comment]
Agreed on doing this for 2.1.1. The change described here as well as updating the test that's currently failing was what I was alluding to in 
https://github.com/spring-projects/spring-boot/issues/15271#issuecomment-441761990.
