### ISSUE TITLE
Replace use of DirectFieldAccessor with AssertJ's hasFieldOrPropertyWithValue

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15304]
Following on from #14696, there are some usages of `DirectFieldAccessor` that could be replaced with AssertJ's `hasFieldOrPropertyWithValue`.

**Comment by dreis2211** [comment]
There are actually some places where neither `DirectFieldAccessor` nor `hasFieldOrPropertyWithValue` is needed as the field is exposed via a normal getter. I'd volunteer to tackle that task and clean those places while being on it, if you want @wilkinsona.

**Comment by wilkinsona** [comment]
That would be great. Thank you!

**Comment by dreis2211** [comment]
Is there a preference between `ReflectionTestUtils` and `DirectFieldAccessor` btw? Should we harmonize this as well?

**Comment by wilkinsona** [comment]
Looks purely at the class level, `ReflectionTestUtils` is more widely used in the code base at the moment. I think it'd be nice to harmonise on that one where it makes sense to do so.

**Comment by philwebb** [comment]
Closing in favor of PR #15312
