### ISSUE TITLE
Spring data layer for spring-boot and mongodb very slow

### ISSUE THREAD

**Issue by rekaparathalwar** [spring-projects/spring-boot#15308]
We are a java REST API based application using spring boot + MongoDB.
We are doing performance testing of our app and analysing the performance using APM like Appdynamics. The spring data layer ie MongoRepository layer is taking much time ( more than 50% time in many tests). This time does not include the query execution time. It is just the time taken only at the spring data layer( Repository level). Can you please throw us some light on this issue.

```
@Repository
public interface ProductRepository extends MongoRepository<Product, String>, ProductRepositoryGrouping, ProductRepositorySearch {

	@Query(value = "{?0:{ $elemMatch: { ?1: {$in : ?2} } }, ?3: {$eq : ?4}, ?5: {$eq : ?6}}")
	List<Product> findByBarcodeAndFilteredAttributeIn(String version, String barcodeType, List<String> values, String filterAttribute, String filterValue, String filterAttribute2, String filterValue2);

}
```

**Comment by wilkinsona** [comment]
Spring Data MongoDB is managed as a separate project with its [own issue tracker](https://jira.spring.io/projects/DATAMONGO). If you'd like to pursue this, please open an issue there providing as much information as possible. For example, it would be helpful to quantify "very slow" and "much time". It would also be useful if you provided a small sample that reproduced the behaviour you have described.
