### ISSUE TITLE
Shoudlnt this log statement at error instead of warn?

### ISSUE THREAD

**Issue by patelmiral81** [spring-projects/spring-boot#15309]
2018-11-27T09:05:29.05-0600 [APP/PROC/WEB/0] OUT 27-11-2018 15:05:29.049 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContex
t.log - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Err
or creating bean with name 'myBean': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentExce
ption: Could not resolve placeholder 'my.property' in value "${my.property}"

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but the message is logged by [code in Spring Framework](https://github.com/spring-projects/spring-framework/blob/dfc193b85e4c50105c0c05bbcd3e74b208aee067/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L553-L556). FWIW, I don't think it should change from warn to error, but if you would like to pursue this you can do so by opening a [Spring Framework JIRA](https://jira.spring.io/browse/SPR). If you do so, please comment here with a link to it.
