### ISSUE TITLE
Spring Boot application failed to start after configured second org.springframework.cache.CacheManager

### ISSUE THREAD

**Issue by dknc** [spring-projects/spring-boot#15314]
My spring boot application start failed after configured the second `org.springframework.cache.CacheManager` bean,  also tomcat reported a lot of  'xxx thread stop failed, This is very likely to create a memory leak. Stack trace of thread'. 

Major dependencies: 
```
Spring boot: 2.0.5.RELEASE
Spring Core: 5.0.9.RELEASE
Spring Session:  2.0.5.RELEASE
Lettuce: 5.0.4.RELEASE
Redisson: 3.9.1
EhCache: 3.6.2
```
In the application , it uses
- spring-sesson to persistent session in redis
- distributed locks from redisson. but did not use its  JCache implementation
- Used spring cache abstraction but define the cache manager without using auto configuration
- The default cache manager bean is a RedisCacheManager which use redis connection from Lettuce
- The second `org.springframework.cache.CacheManager` bean is Spring JCache wrapper of EhCache cache manager

Here is my bean definition.
```
    @Bean(name = "cacheManager")
    public CacheManager cacheManager(RedisConnectionFactory redisConnectionFactory) {
        HashMap<String, RedisCacheConfiguration> cacheConfigurations = new HashMap<>();
        Arrays.stream(cacheNames).forEach((cacheName) -> {
            String cacheTtlConfigKey = CACHE_PARAM_PREFIX + cacheName + TTL;
            String ttlValue = env.getProperty(cacheTtlConfigKey);
            RedisCacheConfiguration cacheConfig = getDefaultRedisConfiguration();
            try {
                Long cacheTtl = Long.valueOf(ttlValue);
                cacheConfigurations.put(cacheName, cacheConfig.entryTtl(Duration.ofMillis(cacheTtl)));
            } catch (Exception ex) {
                logger.error("Illegal cache time-to-live value: {} for cache {}", ttlValue, cacheName);
            }
        });
        RedisCacheConfiguration shoppingCartCacheConfig = getDefaultRedisConfiguration();
        cacheConfigurations.put(SHOPPING_CART_CACHE, shoppingCartCacheConfig.entryTtl(Duration.ZERO));
        return RedisCacheManager.builder(redisConnectionFactory)
                .cacheDefaults(getDefaultRedisConfiguration())
                .withInitialCacheConfigurations(cacheConfigurations)
                .build();
    }

    @Bean
    public javax.cache.CacheManager standardCacheManager() throws IOException {
        CachingProvider cachingProvider = getCachingProvider(
                cacheProperties.getJcache().getProvider());
        Resource configLocation = cacheProperties
                .resolveConfigLocation(cacheProperties.getJcache().getConfig());
        URI configUri = configLocation == null ? null : configLocation.getURI();
        javax.cache.CacheManager jCacheCacheManager = cachingProvider.getCacheManager(configUri, this.getClass().getClassLoader(), null);

        List<String> cacheNames = cacheProperties.getCacheNames();
        if (!CollectionUtils.isEmpty(cacheNames)) {
            for (String cacheName : cacheNames) {
                jCacheCacheManager.createCache(cacheName, new MutableConfiguration<>());
            }
        }
        return jCacheCacheManager;
    }

    @Bean  
    public CacheManager jCacheCacheManager(javax.cache.CacheManager standardCacheManager) {
        JCacheCacheManager cacheManager = new JCacheCacheManager(standardCacheManager);
        return cacheManager;
    }

```
**If we remove the `jCacheCacheManager` bean definition,  everything goes well.**

Here is the log and stack trace.
```
2018-11-28 10:14:08.073  WARN [ost-startStop-1] o.a.c.l.WebappClassLoaderBase            : The web application [ROOT] appears to have started a thread named [lettuce-eventExecutorLoop-1-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
 io.netty.util.concurrent.SingleThreadEventExecutor.takeTask(SingleThreadEventExecutor.java:251)
 io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:64)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:745)
2018-11-28 10:14:08.073  WARN [ost-startStop-1] o.a.c.l.WebappClassLoaderBase            : The web application [ROOT] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.net.dns.ResolverConfigurationImpl.notifyAddrChange0(Native Method)
 sun.net.dns.ResolverConfigurationImpl$AddressChangeListener.run(ResolverConfigurationImpl.java:144)
2018-11-28 10:14:08.074  WARN [ost-startStop-1] o.a.c.l.WebappClassLoaderBase            : The web application [ROOT] appears to have started a thread named [redisson-netty-4-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
 sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
 sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
 sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
 io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:745)

The web application [ROOT] appears to have started a thread named [redisson-netty-4-7] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
....

```

           <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-oxm</artifactId>
                <version>5.1.0.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-config</artifactId>
                <version>5.0.8.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-web</artifactId>
                <version>5.0.8.RELEASE</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-jdbc</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>2.0.5.RELEASE</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.9.1</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-actuator</artifactId>
                <version>2.0.5.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-tomcat</artifactId>
                <version>2.0.5.RELEASE</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-webmvc</artifactId>
                <version>5.0.9.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>2.0.5.RELEASE</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-log4j2</artifactId>
                <version>2.0.5.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.session</groupId>
                <artifactId>spring-session-data-redis</artifactId>
                <version>2.0.5.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-cache</artifactId>
                <version>2.0.5.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>javax.cache</groupId>
                <artifactId>cache-api</artifactId>
                <version>1.1.0</version>
            </dependency>
            <dependency>
                <groupId>org.ehcache</groupId>
                <artifactId>ehcache</artifactId>
                <version>3.6.2</version>
            </dependency>
            <dependency>
                <groupId>io.lettuce</groupId>
                <artifactId>lettuce-core</artifactId>
                <version>5.0.4.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-core</artifactId>
                <version>5.0.8.RELEASE</version>
            </dependency>

**Comment by snicoll** [comment]
Thanks for the report but Spring Boot only auto-configures the infrastructure in this area and you're not even using it. I'd suggest reporting this against the [Spring Data Redis](https://jira.spring.io/projects/DATAREDIS) project (that provides the `RedisCacheManager`). When you do, please share a sample that the team can actually run (clone or unzip) rather than code snippets.
