### ISSUE TITLE
When spring.profiles.include is set, spring.profiles.active has no effect

### ISSUE THREAD

**Issue by facugaich** [spring-projects/spring-boot#15344]
Spring Boot version: 2.1.0.RELEASE

Summary: Setting `spring.profiles.active` in `application.properties` has no effect if system property `spring.profiles.include` or env var `SPRING_PROFILES_INCLUDE` is also set.

How to reproduce, using demo project from initializr:

application.properties
`spring.profiles.active=active`

Run with:
`./mvnw -Dspring.profiles.include=include spring-boot:run`

Expected:
`The following profiles are active: include,active`

But got:
`The following profiles are active: include`

I have also tested that the profile specific `application-active.properties` is not being loaded into the environment.

Setting active profiles in system properties seems to work:
`./mvnw -Dspring.profiles.active=active -Dspring.profiles.include=include spring-boot:run`

Output:
`The following profiles are active: include,active`

**Comment by philwebb** [comment]
This is actually behaving as I would expect. The `spring.profiles.active` entry in your `application.properties` will _only_ apply if no other profiles have been activated. When you use `-Dspring.profiles.include=include` this is setting a system property that will be evaluated before the `application.properties` file is loaded. Since the system property has activated the `include` profile, the `spring.profiles.active` property will not be used.

**Comment by facugaich** [comment]
@philwebb Thank you

Isn't this behaviour at odds with the documentation on [Profiles](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/boot-features-profiles.html#boot-features-adding-active-profiles)? More specifically:

> The spring.profiles.active property follows the same ordering rules as other properties: The highest PropertySource wins. This means that you can specify active profiles in application.properties and then replace them by using the command line switch.

>Sometimes, it is useful to have profile-specific properties that _add to the active profiles rather than replace them_. The spring.profiles.include property can be used to unconditionally add active profiles.

**Comment by philwebb** [comment]
I agree that the behavior is a little unexpected. I've reopened this one to see if we can improve things in 2.2.

**Comment by wilkinsona** [comment]
It looks like we need to avoid setting `activatedProfiles` to `true` when recording the profiles that have been activated via the `spring.profiles.include` system property or environment variable. This should then allow `spring.profiles.active` found in an application properties file to still take effect.

**Comment by ayudovin** [comment]
As far as I understand, all profiles from environment variables and files should be summarized, is it correct?
