### ISSUE TITLE
Document that spring.application.autoconfigure.exclude=autoclazz property disables @ImportAutoConfiguration(classes = autoclazz)

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-boot#15340]
Hello,
I am not sure if it's a bug or wanted behavior but there is definitely a change in behavior between **2.0.4** and **2.1** and this change is not listed in **2.1** release notes. 

For **2.0.4** combination of setting 
`spring.application.autoconfigure.exclude=autoclazz` in application.properties and 
`@ImportAutoConfiguration(classes = autoclazz)` in `@Configuration` class enabled by `@Profile` the autoclazz is being applied.

For **2.1** autoclazz is being excluded globally no matter of @ImportAutoConfiguration usage, `autoclazz` is not imported. 

Let me know if it's unclear.

**Comment by wilkinsona** [comment]
This is intentional. See https://github.com/spring-projects/spring-boot/issues/12586 for details. We should update the release notes to mention it. Thanks for bringing that omission to our attention.

**Comment by snicoll** [comment]
I've updated the [2.1 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#auto-configuration-exclusion)
