### ISSUE TITLE
Spring-Boot Gradle plugin fails for unknown reason on dependent sub-project.

### ISSUE THREAD

**Issue by soberich** [spring-projects/spring-boot#15345]
Spring boot gradle plugin fails with jdk 8 or 11 when applied on dependent project.

if comment out `id("spring-boot")` which is the `SpringPlugin.groovy` gradle plugin in `buildSrc` folder, then all passes. I thought at first the issue is swagger plugin.. so it is named `swagger-fails`.
When the line applying the plugin is not commented out - build fails
__repository__

### https://github.com/soberich/swagger_fails

Gradle 5.0

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Windows 10 10.0 amd64

**Comment by wilkinsona** [comment]
You are using a Spring Boot application as a dependency [which we do not recommend](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-an-additional-executable-jar). If you wish to continue doing so, you will need to configure your `swagger_fails-web` project to build both a fat jar with code in `BOOT-INF/classes` and a normal jar as [described](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-and-normal) in the Gradle Plugin's documentation.

**Comment by soberich** [comment]
@wilkinsona Thanks. I forgot about this yesterday.
You definitely don't do this normally but since swagger 2.0.6 they made build time openapi definition generation possible, I've tried that one. 
Thanks again!
