### ISSUE TITLE
Spring Boot  2.1.1 dependency on Flyway 5.2.3

### ISSUE THREAD

**Issue by alanross16** [spring-projects/spring-boot#15355]
I want to upgrade to latest Spring Boot.
I am using flyway and Oracle
This version of flyway only supports the latest versions of Oracle (I have no control over the Oracle version I use)  so it won't start unless I pay for an enterprise license
I would like to point to an older version of Flyway in the mean time so that I can still use the latets Srping Boot but I get this exception
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.api.configuration.FluentConfiguration

Can you sort your code out so that I am not forced to use the latest version of flyway because as of this point I am stuck and cannot upgrade to newer versions of Spring Boot

**Comment by wilkinsona** [comment]
It's not clear what you're trying to tell us as you haven't provided any information. We did upgrade to Flyway 5.2.3 in 2.1.1. 2.1.0 used 5.2.1. Can you please add a description to the issue?

**Comment by alanross16** [comment]
That was quick - was still in the middle of updating the first comment

**Comment by wilkinsona** [comment]
> Can you sort your code out so that I am not forced to use the latest version of flyway because as of this point I am stuck and cannot upgrade to newer versions of Spring Boot

Unfortunately not, no. Spring Boot 2.1 supports and is tested against Flyway 5.2. You may be able to get away with using Flyway 5.1 as that's the release in which `FluentConfiguration` was introduced. Alternatively, you can exclude `FlywayAutoConfiguration` and manually configure version of Flyway you want.

**Comment by alanross16** [comment]
Thanks - looks like thats flyway ditched going forward
