### ISSUE TITLE
Deploying a WAR to WebLogic - update instructions for spring boot 2.1.0

### ISSUE THREAD

**Issue by adelinor** [spring-projects/spring-boot#15351]
The section [92.3](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-weblogic) is extremely useful for deploying to Weblogic.

This is to update the instructions to add two small changes I had to do to make the deployment successful on:
* JDK: 8
* Weblogic server version: 12.2.1.2.0
* Spring boot version: 2.1.0

1) Update exclusion in weblogic.xml
The exclusion was added to avoid a conflict of versions with the dependency `jackson-datatype-jsr310`:
```xml
<wls:package-name>com.fasterxml.jackson</wls:package-name>
```

2) Add exclusions to pom.xml to `spring-boot-starter-web` dependency

```xml
<artifactId>spring-boot-starter-web</artifactId>
<exclusions>
	<exclusion>
		<artifactId>tomcat-embed-logging-juli</artifactId>
		<groupId>org.apache.tomcat.embed</groupId>
	</exclusion>
	<exclusion>
		<artifactId>tomcat-embed-websocket</artifactId>
		<groupId>org.apache.tomcat.embed</groupId>
	</exclusion>
	<exclusion>
		<artifactId>tomcat-embed-el</artifactId>
		<groupId>org.apache.tomcat.embed</groupId>
	</exclusion>
</exclusions>
```

**Comment by wilkinsona** [comment]
Thanks for the suggestions.

Those exclusions shouldn't be necessary if, [as we suggest](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#howto-create-a-deployable-war-file), you mark `spring-boot-starter-tomcat` as provided.

I don't think we should go to the level of detail required to document application server-specific configuration that is needed to prevent them from polluting an application's classpath with out-of-date dependencies. It would be a significant undertaking to do so for all the major app servers and keeping it up-to-date would be a large maintenance burden. It also isn't something that is Spring Boot-specific. The configuration that you have mentioned is necessary for any application that using an up-to-date version of Jackson with WebLogic 12.2.1.2.0.

Thanks anyway.
