### ISSUE TITLE
Provide an easy way of turning off response body for errors

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#15353]
Currently, the default `BasicErrorController` adds the response body to all error requests. If you use response status codes to control the flow in the application, you usually override `ErrorDecoder` used in `RestTemplate` to now throw an error for particular status codes. However, if the response from the server contains a body, `RestTemplate` tries to deserialize it to the target entity (being for example `ResponseEntity<Product>`). It'd be nice to be able to turn-off such behavior with a simple property.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. You may already be able to achieve what you want by excluding `ErrorMvcAutoConfiguration`. That aside, this is really a limitation of `RestTemplate` and I'm not sure that the server side is the right place to be addressing a client-side limitation. If `RestTemplate` does not meet your needs, the [recommendation from the Framework team](https://jira.spring.io/browse/SPR-10961?focusedCommentId=155015) is to use `WebClient` instead:

> Yes in more than one respects `WebClient` is a more modern alternative. We've deprecated `AsyncRestTemplate` in favor of `WebClient`. The `RestTemplate` is not deprecated and is fine to use if it meets the needs but `WebClient` does more with no downsides.

Some of the benefits of `WebClient` that are relevant here are described in an earlier comment on that issue:

> in 5.0 we have added the `WebClient` which allows you to perform an `exchange()` and get access to the response status and headers, before the response body is consumed or decoded. So you can check the status first, and then decide how to proceed. It also provides a way a convenience route to `retrieve()` and convert to a body with pre-declared status handlers that indicate how errors should be treated.
