### ISSUE TITLE
Inconsistency in spring-boot-starter-jersey

### ISSUE THREAD

**Issue by raphw** [spring-projects/spring-boot#15365]
A simple project with the single dependency

```xml
<dependencies>
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jersey</artifactId>
    <version>2.1.1.RELEASE</version>
  </dependency>
</dependencies>
```
with
```java
@SpringBootApplication
public class SampleApp {
    public static void main(String[] args) {
        SpringApplication.run(SampleApp.class);
    }
}
```
will fail to start with the error:
```java
java.lang.NoSuchMethodError: org.springframework.aop.framework.AopProxyUtils.getSingletonTarget(Ljava/lang/Object;)Ljava/lang/Object;
```

It seems like the Jersey dependency is dragging ing Spring 4 via the HK2 bridge what causes an inconsistency with Spring Boot that is using Spring 5.

**Comment by snicoll** [comment]
@raphw thanks for the report but there's not much we can do if you're not using [proper dependency management](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-dependency-management) for the project (You can generate an app with jersey on start.spring.io and it won't drag Spring 4). There isn't a `jersey-spring5` integration at the moment and it would be nice if Jersey aligned. Please cast your vote on https://github.com/eclipse-ee4j/jersey/issues/3736

**Comment by wilkinsona** [comment]
Judging by the version on the dependency, am I right to assume that you aren’t using Spring Boot’s dependency management? If you’re not using it, is there something that prevents you from doing so?

**Comment by snicoll** [comment]
You can have your own bom and import ours. Alternatively you can provide dependency management for the bits that you need. You could import `spring-framework-bom` for a start. 

But I highly encourage you to import our bom if you can.

**Comment by raphw** [comment]
I'd do that but I integrate against a bunch of infrastructure code that is compiled against outdated versions of everything. Eventually, I'd like to use the Spring BOM but as a first step, I wanted to drag in isolated Spring dependencies and find some common ground.

It's not a problem once you know the issue, I was just surprised that I could not create a single-Spring-only-dependency project without Spring dependency management. Intuitively, I found that to be a bug which could be solved by setting the dependency in the starter POM.

**Comment by ankurpathak** [comment]
@snicoll We have the issue related to spring 5support moving but we need help from Spring Team.
So can you please help for:
https://github.com/eclipse-ee4j/jersey/pull/4062
and related to this:
https://github.com/eclipse-ee4j/jersey/pull/4080
