### ISSUE TITLE
Document the property configuration of the auto-configured EntityManagerFactoryBuilder

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15361]
See https://github.com/spring-projects/spring-boot/issues/15318. We need to describe that some properties are applied to the auto-configured `EntityManagerFactoryBuilder` and that some are only applied in isolation when the builder's being used to create the entity manager factory.

**Comment by mbhave** [comment]
@wilkinsona I tried [documenting this](https://github.com/mbhave/spring-boot/commit/cae5bea62a78a710ba4c2aa9c9d3e3b9982d1d93). Could you take a look and see if it's accurate and what you had in mind?

**Comment by wilkinsona** [comment]
LGTM, @mbhave. Thank you.
