### ISSUE TITLE
Support server.connection-timeout for Netty server

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#15368]
Should be done with a `NettyWebServerFactoryCustomizer`.

**Comment by bclozel** [comment]
Closing in favor of #15368

**Comment by paulvi** [comment]
#15368 is actually this issue.

I guess Brian @bclozel means #15385

**Comment by wilkinsona** [comment]
> I guess Brian @bclozel means #15385

Yes, thank you.

> But usually issue should be closed, when it is solved, not a PR created...

That's not the process that we follow. We don't need an issue and a PR tracking the same change so, when a PR is closed, the issue is closed and labelled as having been superseded by the PR.

**Comment by xgene** [comment]
“Use a value of -1 to indicate no (that is, an infinite) timeout.” 
I used - 1, but got an exception. Is your document written casually?

**Comment by bclozel** [comment]
@xgene No, our documentation is not written casually. I've created #16497 to fix this problem.
