### ISSUE TITLE
Remove explicit dependency management for spring-core from spring-boot-dependencies

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15380]
`spring-boot-dependencies` currently manages `spring-core` explicitly and imports Spring Framework's bom. As far as I can tell, the former is redundant and can be removed.

**Comment by snicoll** [comment]
As far as I remember, we did this regarding something related to `commons-logging`. Now that it has been harmonized with Spring 5 we should probably remove that indeed.
