### ISSUE TITLE
can't authenticate with the default CouchbaseProperties

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#15388]
Hi, 

I couldn't figure out how to authenticate using the properties in Spring Boot and Couchbase 6. I created a user in couchbase and assigned it to a bucket but couldn't use the properties (AFAICT) in Spring boot to achieve the following which calls `CouchbaseCluster#authenticate( String u, String pw)`. In the auto configuration there's no `@ConditionalOnMissingBean`, either, which means that I had to define a whole `CouchbaseConfigurer` which was all but identical to the configuration in the auto-configuration's defined beans for 90% of the code. It'd be nice if I could just define a `@Bean Cluster myCluster() ...` to override just that bit. 

```
@Configuration
class ILoveCouchbase implements CouchbaseConfigurer {

	@Override
	public CouchbaseEnvironment couchbaseEnvironment() throws Exception {
		return DefaultCouchbaseEnvironment.create();
	}

	@Override
	public Cluster couchbaseCluster() throws Exception {
		CouchbaseCluster localhost = CouchbaseCluster.create(couchbaseEnvironment(), "localhost");
		localhost.authenticate("jlong", "password");// new. 
		return localhost;
	}

	@Override
	public ClusterInfo couchbaseClusterInfo() throws Exception {
		return couchbaseCluster().clusterManager("Administrator", "asdasd").info();
	}

	@Override
	public Bucket couchbaseClient() throws Exception {
		return couchbaseCluster().openBucket("reservations");
	}
}

```

thanks in advance for any and all help.

**Comment by snicoll** [comment]
> In the auto configuration there's no @ConditionalOnMissingBean, either, which means that I had to define a whole CouchbaseConfigurer

There is a `@ConditionalOnMissingBean` on the configurer itself and we provide one with sensible defaults so I guess you could do the following for the time being:

```
@Configuration
class ILoveCouchbase extends org.springframework.boot.autoconfigure.couchbase.CouchbaseConfiguration {

    ILoveCouchbase(CouchbaseProperties properties) { super(properties); }

    @Override
    public Cluster couchbaseCluster() {
        Cluster cluster = super.couchbaseCluster();
        cluster.authenticate("jlong", "password");// new. 
        return cluster;
    }
}
```

Having said that, don't you want to authenticate against the bucket rather than the cluster? There is a `spring.couchbase.bucket.[name|password]` for this.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
