### ISSUE TITLE
Change "Colophon" to "Legal"

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15393]
I'd like to change the title of https://docs.spring.io/spring-boot/docs/2.2.0.BUILD-SNAPSHOT/reference/html/colophon.html#colophon to legal, or some other term that's easier to understand.

**Comment by kdpapado** [comment]
Hi @philwebb, I am a computer science student and I am trying to enter the GitHub world.
If I am not wrong, you mean that you want to change the colophon.adoc file. Right?
Something like in image below?

![colophontolegal](https://user-images.githubusercontent.com/43214712/49615278-b96b1680-f9b5-11e8-9000-61a1d1618f77.png)

**Comment by snicoll** [comment]
Closing in favour of PR #15580
