### ISSUE TITLE
Feature: JMS networked testing/client

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#15391]
related spring-guides/getting-started-guides/issues/76, it would be nice to be able to test jms in full server mode similar to what can be done with http random port and webclient.

**Comment by snicoll** [comment]
`WebClient` makes sense as HTTP is a universal protocol and Spring Boot and Spring Framework can be used to create an HTTP server.

A JMS equivalent doesn't really make sense as there's no universal protocol and neither Spring Boot nor Spring Framework provides a JMS broker. As such, you need to use the JMS client that's appropriate for the JMS broker that you are connecting to and that can communicate using the broker's proprietary protocol.

Doing it in "full server mode" also means that we should embed and start an actual broker with a network stack and that's not something that we do or something we would recommend anyway as the messaging infrastructure must have a different lifecycle than the application.

If you need to start a full broker as part of a test suite, I'd recommend you having a look to TestContainers.
