### ISSUE TITLE
Upgrade to Flyway 5.2.4

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#15402]
Flyway `5.2.3` has a regression [2215](https://github.com/flyway/flyway/issues/2215) with `mysql` and this is supposedly fixed in `5.2.4` which were released this week. Got burned with this in dataflow when we started a work to upgrade to boot 2.1.x, so it'd be great to get this into snapshots.

**Comment by snicoll** [comment]
@jvalkeal thanks for letting us know. You'll get a `2.1.x` snapshot with that version once [this build completes](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.1.x/jobs/build/builds/9).
