### ISSUE TITLE
Provide configuration property to set name for RabbitMQ connection factory

### ISSUE THREAD

**Issue by holgerstolzenberg** [spring-projects/spring-boot#15403]
At the moment it is not possible to set the (human readable) name of the auto configured RabbitMQ `ConnectionFactory` connection identifier. We are running multiple Spring-Boot applications against a RabbitMQ instance. Problematic connections can only be identified by IP right now. This makes defect analysis a bit slacky. It would be nice to have a human readable name identifying the source connection factory.

You can work around this with the following solution:
https://stackoverflow.com/questions/49089915/how-to-set-custom-name-for-rabbitmq-connection

```java
@Bean
public SmartInitializingSingleton reconfigureConnectionFactory(final AbstractConnectionFactory cf) {
        return () -> cf.setConnectionNameStrategy(f -> generateConnectionName());
}
```

Still having a dedicated config property would be great. Another option would be to find some sensible default like `${spring.application.nane}-ConnectionFactory` or something like that.

A backport to the `1.5` branch is also very appreciated.

**Comment by snicoll** [comment]
> At the moment it is not possible to set the (human readable) name of the auto configured RabbitMQ ConnectionFactory connection identifier.

As [documented in the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-rabbitmq), this is already supported.

**Comment by holgerstolzenberg** [comment]
I missed that one. Thanks for the clarification.
