### ISSUE TITLE
Directly inject Maps of bean name to bean rather than an ObjectProvider of the same

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#15419]
See https://jira.spring.io/browse/SPR-17577 for background (Spring does not support injection of `ObjectProvider<Map<String,Foo>>` in the "functional style", and we essentially only support it for `@Autowired` dependencies for historic reasons). It only happens in a couple of places that I found so far. Example:

```
	@Configuration
	@ConditionalOnClass(Flux.class)
	static class ReactiveHealthIndicatorConfiguration {

		@Bean
		@ConditionalOnMissingBean
		public ReactiveHealthIndicatorRegistry reactiveHealthIndicatorRegistry(
				ObjectProvider<Map<String, ReactiveHealthIndicator>> reactiveHealthIndicators,
				ObjectProvider<Map<String, HealthIndicator>> healthIndicators) {
			return new ReactiveHealthIndicatorRegistryFactory()
					.createReactiveHealthIndicatorRegistry(
							reactiveHealthIndicators
									.getIfAvailable(Collections::emptyMap),
							healthIndicators.getIfAvailable(Collections::emptyMap));
		}

	}
```

Would it not suffice in that case to simply inject the `Map` (which would be empty if there were no beans of that type)?

**Comment by dsyer** [comment]
I can work around this with a convenience class and a custom implementation of `ObjectProvider`, but I still wonder if just injecting a `Map` would be clearer anyway.

**Comment by wilkinsona** [comment]
We discussed this and agreed that we should replace injection of `ObjectProvider<Map<String, Bean>>` with injection of `Map<String, Bean>`. The use of `ObjectProvider` is unnecessary as Framework will inject an empty `Map` if there are no beans of the required type.

**Comment by mbhave** [comment]
Closing in favor of PR #15798.
