### ISSUE TITLE
Replace ${sys:PID} with %pid in log4j2 configuration

### ISSUE THREAD

**Issue by thekalinga** [spring-projects/spring-boot#15426]
Currently log4j2 configuration in spring boot uses `????` as `PID` in the [configuration file](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2-file.xml#L4)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
	<Properties>
		<Property name="PID">????</Property>
		<Property name="CONSOLE_LOG_PATTERN">%clr{%d{${LOG_DATEFORMAT_PATTERN}}}{faint} %clr{${LOG_LEVEL_PATTERN}} %clr{${sys:PID}}{magenta} %clr{---}{faint} %clr{[%15.15t]}{faint} %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n${sys:LOG_EXCEPTION_CONVERSION_WORD}</Property>
		<!-- a lot more -->
	</Properties>
	<!-- a lot more -->
</Configuration>
```

And [`LoggingSystemProperties`](https://github.com/spring-projects/spring-boot/blob/2f4751a6486f0b9c5653725cb3cb0b346524c03b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/LoggingSystemProperties.java#L106) sets a system property `PID` and replaces this `????` with actual PID

However, Log4j2 provides a native pid plugin [`ProcessIdPatternConverter`](https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ProcessIdPatternConverter.java) that can used directly in the configuration if we use `%pid` instead of `${sys:PID}`

Its better to use the native version so that log4j2 users dont have to worry about learning Spring boot magic under the hood (one less thing to worry about) when they try to copy default spring boot `log4j2.xml` as a base template before they start making their own changes to the file

More info: https://stackoverflow.com/questions/53683177/how-does-spring-boot-resolve-pid-thru-using-log4j2/53686018

**Comment by thekalinga** [comment]
This is applicable to both [log4j2.xml](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml) &  [log4j2-file.xml](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2-file.xml)

**Comment by mmitropolitsky** [comment]
Hi, can I contribute to this issue?
If not, is there another one that I can help with?

**Comment by wilkinsona** [comment]
@mmitropolitsky Thanks very much for the offer. A contribution would be most welcome.

**Comment by wilkinsona** [comment]
Closing in favour of the PR from @mmitropolitsky (thank you!).
