### ISSUE TITLE
Add an outcome tag to RestTemplate/WebClient metrics similar to that provided for WebMVC and WebFlux

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#15420]
Related to #13801

_This effects spring boot actuator and specifically it's metrics classes._

**Situation**
I want to graph a count of calls made to a downstream api that returned a 4xx status code.

It would be useful to have a tag on those metrics that would group the response codes appropriately. For example these groupings could be:
- 1xx -> informational
- 2xx -> success
- 3xx -> redirection
- 4xx -> client_error
- 5xx -> server_error

This tag has already been added to the web mvc metrics.

**Comment by wilkinsona** [comment]
Sounds sensible to me, thanks for the suggestion. In the meantime, you can implement this yourself by configuring a custom `RestTemplateExchangeTagsProvider` bean.

**Comment by snicoll** [comment]
We should make sure this gets added to `WebClient` as well for consistency.

**Comment by nishantraut** [comment]
Updated PR for WebClient as well

**Comment by snicoll** [comment]
Closing in favour of PR #15594
