### ISSUE TITLE
Getting 404 on anything but localhost

### ISSUE THREAD

**Issue by wytten** [spring-projects/spring-boot#1542]
Strange behavior from spring boot app when run as a windows service created by cygrunsrv.
URL that uses 'localhost' works, but these other supposedly equivalent variations all fail with a 404:
http://(hostname):8080/page.html
http://(hostip):8080/page.html
http://127.0.0.1:8080/page.html

When I run the app with 'java -jar ...' manually, all of these URL's work but when run as a service,
only the 'localhost' variation works.  The definition of the service is nothing more than to run the same  'java -jar ...' command.

Perhaps this has nothing to do directly with spring-boot, if so my apologies.

**Comment by wramirez2401** [comment]
Hello, also I have the same problem as solved?

**Comment by bclozel** [comment]
@wramirez2401 Please [don't cross-post](https://github.com/spring-io/sagan/issues/288).

Could you ask your question on StackOverflow? Commenting on a closed, and probably unrelated issue won't really help you here.

Thanks!
