### ISSUE TITLE
Provide a means for a TomcatContextCustomizer to use LoaderHidingResourceRoot when the context has no resources

### ISSUE THREAD

**Issue by ilya-ershov** [spring-projects/spring-boot#15434]
The issue happens when jar executable doesn't have **webapp** (or static, or public, e.g.) directory. Then `org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory#prepareContext` leaves `context.recources == null`, and when I try to add new resources inside `TomcatStaticResourcesSupportWorkaround` fails with NPE. 
`context.setResources(new StandardRoot())` can be used to cover that case, because there is no public access to `new LoaderHidingResourceRoot()`.
Would be nice if `LoaderHidingResourceRoot` can be made public to allow customizer's to set spring-classpath-secured [`WebResourceRoot`.[]

Attaching sampls project. NPE on DemoApplication run
[demo.zip](https://github.com/spring-projects/spring-boot/files/2663417/demo.zip)

**Comment by dennysfredericci** [comment]
Hi @ilya-ershov 

Is this problem already solved? I tried to reproduce this issue using the "demo.zip" and removing TomcatStaticResourcesSupportWorkaround but i don't have any exception on my console.

Tks

**Comment by ilya-ershov** [comment]
Looks like it is solved. I can't reproduce it either.
