### ISSUE TITLE
TestRestTemplate.withBasicAuth resets custom requestFactory

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#15443]
I'm currently using a `RestTemplateCustomizer` bean to set a custom request factory for all RestTemplate's:

https://github.com/freefair/okhttp-spring-boot/blob/f0f6dcc0ba685c40ebe15de725c1170307027173/autoconfigure/src/main/java/io/freefair/spring/okhttp/OkHttpRestTemplateAutoConfiguration.java#L22-L27

The `TestRestTemplate` I get injected into my unit tests also uses this custom request factory, but calling `withBasicAuth()` returns a new `TestRestTemplate`-instance which no longer contains the custom request factory but a default one.

Environment:
Spring Boot 2.1.1.RELEASE
OpenJDK 11

Similar issues:
see #7812
see #7441
see #7265

**Comment by mbhave** [comment]
I think we should fix this but [this commit](https://github.com/spring-projects/spring-boot/commit/db7268b841b9b90d498822b4ab37981792303126) has some history around why a new request factory is selected when a `TestRestTemplate` with `withBasicAuth` is created.

**Comment by mbhave** [comment]
Closing in favor of PR #15982.
