### ISSUE TITLE
spring.profiles.active from defaultProperties takes precedence over config files

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#15445]
The documentation states that Default properties (specified by setting `SpringApplication.setDefaultProperties`) has the lowest precedence. This happens because the `ConfigFileApplicationListener` runs after the `defaultProperties` property source has been added to the environment. The listener only adds active profiles from the config files to the environment if none are already present in the environment.

**Comment by wilkinsona** [comment]
We need to decorate the default property source so that it temporarily filters out any `spring.profiles.active` property that may have been set in it.

**Comment by wilkinsona** [comment]
There's a similar problem to consider with `spring.profiles.include` where a profile that's included via that property in the default property source should have lower precedence than one included via that property in a config file.
