### ISSUE TITLE
Backport RabbitMQ ConnectionNameStrategy feature to 1.5.x branch

### ISSUE THREAD

**Issue by holgerstolzenberg** [spring-projects/spring-boot#15442]
Is it possible to backport feature https://github.com/spring-projects/spring-boot/commit/42629cb8ae8e574760b81e30af6c70e955770e67#diff-aa17d28af40ee9c1f9045ec6afe55db9 to the Spring Boot 1.5.x branch?

**Comment by snicoll** [comment]
@holgerstolzenberg I read your request [the first time you asked](https://github.com/spring-projects/spring-boot/issues/15403#issue-388597621). `1.5` is in maintenance mode and OEL next August. You should consider upgrading in any case.
