### ISSUE TITLE
Transparently integrate Flyway 6.0's support JavaMigration instances created by DI frameworks

### ISSUE THREAD

**Issue by axelfontaine** [spring-projects/spring-boot#15446]
Starting with Flyway 6.0 (due out in Q1 2019), Spring users can use this to automatically use all `JavaMigration` Spring beans with Flyway:

```java
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.migration.JavaMigration;
import org.springframework.context.ApplicationContext;

...
ApplicationContext applicationContext = ...; // obtain a reference to Spring's ApplicationContext.

Flyway flyway = Flyway.configure()
    .dataSource(url, user, password)
    // Add all Spring-instantiated JavaMigration beans
    .javaMigrations(applicationContext.getBeansOfType(JavaMigration.class).values().toArray(new JavaMigration[0]))
    .load();
flyway.migrate();
```

Spring Boot is most certainly able to make this fully transparent for its users.

References:
- https://github.com/flyway/flyway/issues/1062#issuecomment-446279678
- https://twitter.com/snicoll/status/1072755676923998208

**Comment by SammyVimes** [comment]
Is there still no assignee? If so, I'd like to work on that task

**Comment by wilkinsona** [comment]
@SammyVimes Thanks for the offer, but Flyway 6 has not yet been released so nothing can be done here at the moment.

**Comment by SammyVimes** [comment]
@wilkinsona Yes, but it's possible to use Java migrations in Flyway Beta, so I thought I can add support for it and merge when the release comes out :)

**Comment by wilkinsona** [comment]
Cool. If you'd like to prepare something against the beta, ready to be updated to the GA when it's released and then merged, that'd be much appreciated.

**Comment by SammyVimes** [comment]
[Done](https://github.com/SammyVimes/spring-boot/commit/838046f9dcf1ac4842780cef9acf753efc0d7658)! Waiting for GA (looks like it will happen in the beginning of april).

Also, there has been slight API changes in Flyway6, so I had to fix the compatibility.

**Comment by wilkinsona** [comment]
Great! Thanks very much. Would you mind splitting the changes into two separate commits? One that does the upgrade and makes the necessary changes for breaking API changes, and one that adds support for Java migrations?

**Comment by SammyVimes** [comment]
Ofcourse!

**Comment by SammyVimes** [comment]
[Flyway6](https://github.com/SammyVimes/spring-boot/commit/f0e42cec2b50cdb1e9db580d327ad11bce163653)

[AutoConfiguration](https://github.com/SammyVimes/spring-boot/commit/aca76148c6816e084ab1ef32b21731fcc3209cc3)

To clarify: I've put them to different branches, so I can rebase and squash `Flyway6` branch when it will be released and then `autoconfiguration` brench could be rebased onto it.

**Comment by wilkinsona** [comment]
This looks great. Thanks very much @SammyVimes. We'll look forward to Flyway 6's release so that we can get those changes merged.

**Comment by kedar-joshi** [comment]
Flyway 6.0 is now GA.

**Comment by SammyVimes** [comment]
Yay, thanks for the notice, I'll have merge request ready today!

**Comment by SammyVimes** [comment]
Whoops, looks like flyway 6.0.0 is broken! Tests fail and the commit log of flyway repo contains this commit

![image](https://user-images.githubusercontent.com/4058545/63267733-5f885380-c29b-11e9-8a68-cea01d6ec742.png)

**Comment by wilkinsona** [comment]
Looks like we'll have to wait for 6.0.1 which is currently scheduled for 27/8: https://github.com/flyway/flyway/milestone/37.

**Comment by kedar-joshi** [comment]
Flyway 6.0.1 released https://github.com/flyway/flyway/releases/tag/flyway-6.0.1.

**Comment by SammyVimes** [comment]
Good, I will update my code later today

**Comment by wilkinsona** [comment]
Closing in favour of #17993.
