### ISSUE TITLE
MatrixVariable position with Tomcat and Undertow

### ISSUE THREAD

**Issue by sydneyhenrard** [spring-projects/spring-boot#15452]
I defined a REST endpoint that accepts a `MatrixVariable`. I did some testing, and concluded that the `MatrixVariable` is not processed the same way depending on the container. The v1 endpoint ends with a "static" path, whereas the v2 endpoint ends with a `PathVariable`.

```
@RestController
public class BugResource {
    @GetMapping(value = "/v1/{a}/plus/{b}/equal", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> bug(
            @PathVariable String a,
            @PathVariable String b,
            @MatrixVariable(required = false) String matrix
    ) {
        return ResponseEntity.ok(a + " " + b + " " + matrix);
    }

    @GetMapping(value = "/v2/{a}/plus/{b}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> bug2(
            @PathVariable String a,
            @PathVariable String b,
            @MatrixVariable(required = false) String matrix
    ) {
        return ResponseEntity.ok(a + " " + b + " " + matrix);
    }
}
```

Then I tried to call the REST endpoint:

**with Tomcat**
http://localhost:8080/v1/a;matrix=matrix/plus/b/equal => 200
http://localhost:8080/v1/a/plus/b;matrix=matrix/equal => 200
http://localhost:8080/v2/a/plus/b;matrix=matrix => 200
http://localhost:8080/v2/a;matrix=matrix/plus/b => 200

**with Undertow**
http://localhost:8080/v1/a;matrix=matrix/plus/b/equal => 404
http://localhost:8080/v1/a/plus/b;matrix=matrix/equal => 404
http://localhost:8080/v2/a/plus/b;matrix=matrix => 200
http://localhost:8080/v2/a;matrix=matrix/plus/b => 404

So it seems that Undertow only deals with `MatrixVariable` when the endpoint ends with a `PathVariable`, and the `MatrixVariable` is placed at the end of the endpoint

To reproduce, I just created a Spring Initializr maven project:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>matrixparam</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>matrixparam</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

The configuration to enable `MatrixVariable`:
```
@Configuration
public class WebConfig implements WebMvcConfigurer {
    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
        UrlPathHelper urlPathHelper = new UrlPathHelper();
        urlPathHelper.setRemoveSemicolonContent(false);
        configurer.setUrlPathHelper(urlPathHelper);
    }
}
```

**Comment by bclozel** [comment]
Hi @sydneyhenrard 

I managed to reproduce this behavior with standalone Undertow, no Spring involved. See the following code snippet:

```java
import io.undertow.Undertow;
import io.undertow.server.HttpHandler;
import io.undertow.server.HttpServerExchange;
import io.undertow.util.Headers;

class Scratch {
  public static void main(String[] args) {
    Undertow server = Undertow.builder()
        .addHttpListener(8080, "localhost")
        .setHandler(new HttpHandler() {
          @Override
          public void handleRequest(final HttpServerExchange exchange) throws Exception {
            exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, "text/plain");
            exchange.getResponseSender().send(exchange.getRequestPath());
          }
        }).build();
    server.start();
  }
}
```

```
$ curl -v http://localhost:8080/v2/a\;matrix\=matrix/plus/b
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 5
Content-Type: text/plain
Date: Tue, 18 Dec 2018 22:53:08 GMT

/v2/a
```

The path information seems to be incorrect, and Spring Framework after that calls `request.getServletContext()` which returns `"/v2/a"`. From that point, the request information is wrong and there's no way to correctly map the request to the controller. Tomcat in this case returns `""` as the context path, as expected.

Looking at `io.undertow.server.protocol.http.HttpRequestParser`, it seems the parsing of the HTTP request path stops at the first encounter of a matrix variable on a path segment.

I might have missed something here - maybe I misunderstand the way undertow behaves, or I missed a specific configuration property. But could you [raise an issue against the Undertow project](https://issues.jboss.org/projects/UNDERTOW/issues) and report back here?

Thanks for your report!

**Comment by chrsoo** [comment]
The issue is managed in [UNDERTOW-1464](https://issues.jboss.org/browse/UNDERTOW-1464).

**Comment by chrsoo** [comment]
@bclozel it seems to be possible to implement a custom URL parser by setting the `UndertowOptions.DECODE_URL` to `false` and an implementing a `URLDecodingHandler`, cf [Carter Kozak's comment](https://issues.jboss.org/browse/UNDERTOW-1464?focusedCommentId=13685585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13685585) on [UNDERTOWN-1464](https://issues.jboss.org/browse/UNDERTOW-1464)

Although the ideal solution of course would be to fix the underlying Undertow issue would you consider this workaround in the Spring code for Undertow?

I have not yet looked into how feasible this would be but I am willing to invest some time if you think it a viable alternative.

**Comment by philwebb** [comment]
@chrsoo It feels like that workaround might cause issues elsewhere and is a bit risky for us apply by default. I think we should wait to see how UNDERTOW-1464 plays out.

**Comment by chrsoo** [comment]
@philwebb, @bclozel I have opened [PR 832](https://github.com/undertow-io/undertow/pull/832) for [UNDERTOW-1464](https://issues.redhat.com/browse/UNDERTOW-1464) - would love your feedback on how it would affect the downstream Spring Boot project - any suggestions are welcome!

In particular it would be good to know whether the `getRequestPath()` method should return the path including or excluding matrix parameters...
