### ISSUE TITLE
Spring Boot Maven Plugin 'agent' parameter does not explain how to use multiple agents

### ISSUE THREAD

**Issue by kriegaex** [spring-projects/spring-boot#15455]
From the plugin documentation, it is unclear how to actually add multiple Java agents to the command line, even though `agent` permits an array of file names, see also my [answer](https://stackoverflow.com/a/53754498/1082681) to a corresponding StackOverflow question for more details. The strangest part is that `agent` is a singular word and not the expected plural `agents`, which would imply that inside you could list agents using `agent`. But in this case the singular is the list element. I found out that I can just invent any subtag name in order to list multiple agents, but this is neither documented nor intuitive. I know it would be a breaking change to rename the parameter to its plural form, but maybe you could add an alias and then deprecate the singular name and also explain how to use multiple agents in the plugin documentation and/or in an example. The way it is now just keeps people guessing. I also did not find any integration or unit test case for it in the code base.

**Comment by philwebb** [comment]
Thanks for raising the issue. I don't think the naming is intentional and the plural would seem to make sense to me.

**Comment by kriegaex** [comment]
This is nice, thanks for the swift reaction. In the commit I do not see much update with regard to comprehensive documentation and/or a usage example, though. Has this been done somewhere else or have you decided not to do it?

**Comment by snicoll** [comment]
Your feedback on the documentation is more related to a general Maven usage than anything specific to this plugin . The attributes are [already documented](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/run-mojo.html) and I don't think this deserves a dedicated example.
