### ISSUE TITLE
Appendix A seems to be broken in current-SNAPSHOT version

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#15457]
I'm not sure it's working in progress but "Appendix A" seems to be broken to me now as follows:

<img width="1371" alt="screen shot 2018-12-13 at 3 01 34 pm" src="https://user-images.githubusercontent.com/1059363/49919020-78f52680-fee8-11e8-8d12-89063b80731d.png">

I'm using Google Chrome on macOS.

See https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/appendix.html#common-application-properties

**Comment by bclozel** [comment]
I did reproduce that on Google Chrome macOS as well, but this is working as expected on Firefox and Safari (both macOS). I don't see any CSS directive that limiting the height here - @oodamien any idea?

**Comment by wilkinsona** [comment]
This has been fixed by the switch to the auto-generated tables (
https://github.com/spring-projects/spring-boot/issues/8237).
