### ISSUE TITLE
Support script pre-processor hook for sql scripts before database population for tests

### ISSUE THREAD

**Issue by evgdim** [spring-projects/spring-boot#15453]
Please consider providing a hook before sql execution of `schema.sql`, `data.sql`, scripts defined with `@org.springframework.test.context.jdbc.Sql` and other database population sources for tests. e,g, a place where one can plug something like `Function<String,String>` that accepts the string of the sql to be executed and return a possibly modified script.

The use case for that is that some database initialization scripts, that development teams should provide as part of their deployment packages, should contain variables/placeholders specific to a database vendor.
For example we use oracle's sqlplus variables:
`CREATE TABLE &&schema..ADDITIONAL_INFO(...`  
This makes it impossible to reuse the script for integration tests with in-memory database. Such hook will allow to replace the placeholders with a regex, for example.

**Comment by snicoll** [comment]
Have you considered using a schema management tool rather? (i.e. Flyway or Liquibase).The core support we have is basic and I am not too keen to extend it unless absolutely necessary.

**Comment by evgdim** [comment]
I wanted to reuse the scripts that are required by the deployment team (company policy) and i thought that it might be a common issue for other people. If you identify the issue as a rear use case, I won't insist on adding the functionality. Thanks for the feedback.

**Comment by wilkinsona** [comment]
I'm not keen on adding this. `DataSourceInitializer` already has support for providing platform-specific scripts via `spring.datasource.platform` and providing two different ways to do, essentially, the same thing will lead to confusion.

**Comment by wilkinsona** [comment]
Given the company policy of reusing the deployment scripts in integration tests, I would consider using Testcontainers to run against the same database platform as you use in production rather than using an in-memory database.

**Comment by evgdim** [comment]
OK, thank you both for the replays. Closing the issue.
