### ISSUE TITLE
Update migration guide to document need for a DispatcherServletPath bean when using a custom dispatcher servlet registration

### ISSUE THREAD

**Issue by Puspendert** [spring-projects/spring-boot#15450]
I was using boot `2.0.1.RELEASE` and configured the dispacther servlet as below:
```
@Configuration
public class ServletConfig {

    @Bean
    public DispatcherServlet dispatcherServlet() {
        return new DispatcherServlet();
    }

    @Bean
    public ServletRegistrationBean<DispatcherServlet> dispatcherServletRegistration() {
        final ServletRegistrationBean<DispatcherServlet> registration = new ServletRegistrationBean<>(dispatcherServlet(), "api/v1/*");

        final Map<String, String> params = new HashMap<String, String>();
        params.put("contextClass", "org.springframework.web.context.support.AnnotationConfigWebApplicationContext");
        params.put("contextConfigLocation", "org.spring.sec2.spring");
        params.put("dispatchOptionsRequest", "true");
        registration.setInitParameters(params);

        registration.setLoadOnStartup(1);
        return registration;
    }
}
```
Everythings is working with `2.0.1.RELEASE`

But when I upgrade the boot version to `2.1.1.RELEASE` I get the following error:
```Parameter 1 of constructor in org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'dispatcherServletRegistration' in 'DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration' not loaded because DispatcherServlet Registration found servlet registration bean dispatcherServletRegistration


Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' in your configuration.
```
Its a maven multi module project and I am using `spring-boot-starter-parent`
```	
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.1.RELEASE</version>
</parent>```

**Comment by wilkinsona** [comment]
If you're providing a custom registration for the dispatcher servlet then you now also need to provide a `DispatcherServletPath` bean so that other components can find out how the dispatcher servlet has been mapped. One way to provide a `DispatcherServletPath` bean is to use `DispatcherServletRegistrationBean` rather than `ServletRegistrationBean` and `DIspatcherServletRegistrationBean` implements `DispatcherServletPath`.

**Comment by snicoll** [comment]
@wilkinsona wasn't this added sometime in the cycle of `2.0.x`? Perhaps this should be more visible in the 2.0 release notes for those upgrading from `1.5.x`.

**Comment by wilkinsona** [comment]
Good catch. Thanks. It was indeed added in the 2.0.x cycle – in 2.0.4 to be precise. We should add it to the migration guide.

**Comment by Puspendert** [comment]
Thanks. `DispatcherServletRegistrationBean` worked.

**Comment by wilkinsona** [comment]
I've added [a section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#custom-dispatcherservlet-registration) to the migration guide.
