### ISSUE TITLE
Review use of @ConditionalOnEnabledEndpoint on @Bean methods and move to @Configuration class where appropriate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15451]
Spotted by @dsyer, we're creating some configuration classes unnecessarily. For example:

```java
@Configuration
public class BeansEndpointAutoConfiguration {

	@Bean
	@ConditionalOnMissingBean
	@ConditionalOnEnabledEndpoint
	public BeansEndpoint beansEndpoint(
			ConfigurableApplicationContext applicationContext) {
		return new BeansEndpoint(applicationContext);
	}

}
```

We should move `@ConditionalOnEnabledEndpoint` from the bean method to the configuration class where appropriate.

**Comment by dsyer** [comment]
That example is only the most trivial one - it's a bit more complicated in general. Many endpoints have a swarm of supporting beans that they depend on, and probably all of those should be disabled if the endpoint itself is explicitly disabled. As an example for I searched the bean names in an actuator app where no endpoints were enabled for  "trace", and this is the result:

```
org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceAutoConfiguration
org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceAutoConfiguration$ReactiveTraceFilterConfiguration
org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceEndpointAutoConfiguration
traceRepository
httpExchangeTracer
httpTraceWebFilter
management.trace.http-org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceProperties
```

That's 7 beans for an unused feature. There are over 100 beans in this app more than the no-actuators version of the same thing, so I think we need a way to disable all of them and selectively switch them back on.

Related but different issue: the web endpoints support enabling them by a pattern, but the underlying `management.endpoint.*.enabled` flags all ahve to be explicitly enumerated. Is that right (seems like a pain)?

**Comment by wilkinsona** [comment]
> That's 7 beans for an unused feature

I don't think we can make that assumption We've seen people disable the endpoint but continue to use the underlying infrastructure for their own purpose. Maybe that isn't something that we should support in the future, but it would be a breaking change to disable all the supporting beans when the endpoint is disabled.

> the underlying management.endpoint.*.enabled flags all ahve to be explicitly enumerated. Is that right (seems like a pain)?

I suspect it's just something we haven't considered till now. I've opened https://github.com/spring-projects/spring-boot/issues/15460.

**Comment by dsyer** [comment]
> I don't think we can make that assumption. 

Agree in general (i.e we can't assume that they are unused unless the user tells us so). But in this case they really were unused and I had no interest in them, and had no way to tell Spring Boot about that. I feel like we need a better (more flexible maybe) API/configuration model for switching these things on and off.
