### ISSUE TITLE
Update Infinispan to 9.4.4.Final

### ISSUE THREAD

**Issue by DanielFran** [spring-projects/spring-boot#15454]
Infinispan fixed some bugs related to migration to Spring 5:
- Adds Spring 5 and Spring Boot 2.1 support
- Fixes for JDK 11 compatibility
- Spring Session 2.1.2.RELEASE support

It will be important to migrate asap to the latest infinispan version 9.4.4.Final. for next 2.1,x release.

**Comment by mbhave** [comment]
We have a semi-automated process that takes care of dependency upgrades and we don't need an issue for that. Thanks anyway!
