### ISSUE TITLE
Dependency management for Groovy 2.5 is incomplete

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#15468]
Right now I have to use explicitly a Groovy version in my project for extra Groovy dependencies (e.g. `groovy-dateutils`, `groovy-datetime` etc.) where I can't rely on the Spring Boot as parent, but I use its BOM for imports.

It might be the fact that there is just enough to have a `groovy-all` dependency which is now very close to the BOM structure: https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.5.2/groovy-all-2.5.2.pom.
With the issue that they don't wrap dependencies into the `<dependencyManagement>` (🤷‍♂️), so, I'm not sure how to use in Maven. It works well in Gradle though... But that's already a different story and we may just list all the dependencies from there, plus `groovy-dateutils`, which enhance a `Date` class with extra `format()` and `parse()` methods. 

Thanks

**Comment by artembilan** [comment]
Some external use-case: https://github.com/spring-cloud-stream-app-starters/scriptable-transform/issues/7

**Comment by artembilan** [comment]
@wilkinsona ,

Thank you for fixing this! Although I see that `groovy-jaxb` is still missed: https://search.maven.org/search?q=a:groovy-jaxb
Or is that intentional?

**Comment by artembilan** [comment]
However I see that it is not available for version 3.0: https://search.maven.org/search?q=g:org.codehaus.groovy

So, maybe it is really fine to look ahead and don't add it into our dependency management.

**Comment by wilkinsona** [comment]
Oops. No, that wasn't intentional. Thanks for spotting it. I used [Bomr's `artifacts` command](https://github.com/spring-io/bomr#artifacts) and pointed it at 2.5.0. Interestingly, `groovy-jaxb` is new in 2.5.1. I'll run it again against 2.5.4 and more sure we're fully aligned.
