### ISSUE TITLE
Add some logging to debug concourse cache

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#15462]

**Comment by farooqkhan003** [comment]
Hi @mbhave I am new contributor to spring project. Can you add some more description to this issue. I want to pick this up.

**Comment by snicoll** [comment]
@farooqkhan003 thank you very much for offering to help but this issue is already assigned to @mbhave. You can find suitable issues using the [ideal for contribution](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) label.

**Comment by farooqkhan003** [comment]
@snicoll thanks for updating.

**Comment by mbhave** [comment]
I'm going to close this because the concourse cache works as expected.
