### ISSUE TITLE
When deploying as a WAR, "Bad Credentials" error from Spring Security uses container error page instead of Spring error handler

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#1548]
Steps to reproduce:
1. Get this sample application:  https://github.com/spring-guides/gs-convert-jar-to-war-maven/tree/master/complete .
2. Add `spring-boot-starter-security` to pom.xml .
3. `mvn package` to get the WAR file.
4. Deploy the WAR file to a servlet container (I tried Tomcat and Websphere).
5. `curl --user invalid:credentials http://localhost:10080/gs-convert-jar-to-war-maven/` (I have tomcat running on port 10080)

The output is:

```
<html><head><title>Apache Tomcat/7.0.54 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - Bad credentials</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Bad credentials</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.54</h3></body></html>
```

**Notes:**
- The bug only happens with "Bad Credentials". Other errors are handled correctly, for example:`curl http://localhost:10080/gs-convert-jar-to-war-maven/` (no user credentials supplied)
  
  ```
  {"timestamp":1410409793317,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource"}
  ```
- The bug only happens when deployed as a WAR file, running the application directly using `java -jar` does not trigger the bug. For example: `curl --user invalid:credentials http://localhost:8080/`
  
  ```
  {"timestamp":1410410056046,"status":401,"error":"Unauthorized","message":"Bad credentials","path":"/"}
  ```

**Comment by mikymigs** [comment]
> I see, thanks for the help. I guess I'll add /error to my ignored paths in my application.

I know this is old, but how do you do that? (ignore /error)
