### ISSUE TITLE
Improve Spring Boot 2.0 Migration Guide

### ISSUE THREAD

**Issue by witek1902** [spring-projects/spring-boot#15486]
We prepared article about migration from Spring Boot 1.5.x to 2.0.x (https://altkomsoftware.pl/en/blog/spring-boot-migration-java/). 
Based on our experiences we would like to report some improvements to migration guide:

1.  Add info about the removal of the `ACCESS_OVERRIDE_ORDER`  and how it affects the application.
2. Add info about Spring Boot & Spring Cloud compatibility (https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Finchley-Release-Notes#finchleyrelease)
3. Add info about changes in packages, for example `SpringBootServletInitializer`, `EnableFeignClients`
4. `GuavaCacheManager` to `CaffeineCacheManager` (we should add additional dependency)
5. Changes in CrudRepository method names and also started return Optional type by default.

@snicoll thanks for the tweet that encouraged me to create this issue! :)

What do you think about above improvements?

**Comment by snicoll** [comment]
@witek1902 thanks for reaching out and reporting the issue.

> Add info about the removal of the ACCESS_OVERRIDE_ORDER and how it affects the application.

That's a very good point

> Add info about Spring Boot & Spring Cloud compatibility 

I am afraid we cannot add information about the Spring Cloud upgrade as Spring Cloud builds on top of us. If that information is missing or is not visible, please create an in issue in the Spring Cloud project.

> Add info about changes in packages

We cannot document changes in Spring Cloud as I've explained above. I am not entirely convinced that we should document all package changes explicitly. If you upgrade, the compiler will tell you what is going on an an IDE should quickly suggest what to import once you've removed the faulty import. Can you share why you think that's necessary?

> GuavaCacheManager to CaffeineCacheManager (we should add additional dependency)

There is [a note in the framework upgrade page](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#dropped-support) but I guess it wouldn't hurt to add a note here.

> Changes in CrudRepository method names and also started return Optional type by default.

There is [a note in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#working-with-sql-databases). That's not related to Spring Boot, but Spring Data and we cannot document here all API changes in projects that we integrate with. Again, if you don't find a document in the Spring Data project that helps you with this, then please report it there. It would be nice, however, to add a link to this page from the migration guide if the Spring Data project has one (ping @odrotbohm)

**Comment by witek1902** [comment]
> I am afraid we cannot add information about the Spring Cloud upgrade as Spring Cloud builds on top of us. 
You're right. Perhaps a better place for this information will be Spring Cloud projects.

> Can you share why you think that's necessary?
You're right. The addition of such detailed information may adversely affect readability.

> There is a note in the framework upgrade page but I guess it wouldn't hurt to add a note here.
IMO note here will help.

**Comment by wilkinsona** [comment]
>> I am afraid we cannot add information about the Spring Cloud upgrade as Spring Cloud builds on top of us.
> You're right. Perhaps a better place for this information will be Spring Cloud projects.

The compatibility is documented in the [Spring Cloud project page](https://spring.io/projects/spring-cloud). Perhaps we could link to that from the migration guide.

**Comment by witek1902** [comment]
> The compatibility is documented in the [Spring Cloud project page](https://spring.io/projects/spring-cloud). Perhaps we could link to that from the migration guide.

I think that is enough,

**Comment by wilkinsona** [comment]
I have added [an explanation](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0#custom-security) regarding the removal of `ACCESS_OVERRIDE_ORDER` and a [section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#guavacachemanager) about switching from `GuavaCacheManager` to `CaffeineCacheManager`.
