### ISSUE TITLE
Look for optimizations in AutoConfigurationImportSelector

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#15495]
A regression in performance in spring-projects-experimental/spring-init was traced to a hostspot in `AutoConfigurationImportSelector.getAutoConfigurationEntry()` - once we prevented that method from being called when we already knew the imports, we were able to save nearly 5% of startup time in a micro app.

**Comment by wilkinsona** [comment]
I'm not sure that there's much to be gained here in a typical app that uses `@SpringBootApplication`. `AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationMetadata, AnnotationMetadata)` is called once and takes in the region of 10ms on my laptop. 7ms of that is spent in `AutoConfigurationImportSelector.filter(List<String>, AutoConfigurationMetadata)`.

Can you give us some code to run where it's taking 5% of startup and will appear as a hotspot?

**Comment by dsyer** [comment]
10ms is less than 5% of the app I was running, so probably I overstated it - I made other changes, but it was the biggest one. The hotspot was in `getAttributes()`. The app was this one: https://github.com/spring-projects-experimental/spring-init/blob/master/tests/benchmarks/src/main/java/com/example (there are 3 apps there and the difference between the "manual" and "init" ones was driving the changes). You'd have to go back a few commits in spring-init to wind back through the optimizations and see the effect.

In a `@SpringBootApplication` aren't the imports known by reading `spring.factories`? Why do we even need to read the annotation metadata in that case? It seems over-engineered for the simplest use case, so even if it is only a small gain, it might be worth having.

**Comment by wilkinsona** [comment]
> 10ms is less than 5% of the app I was running, so probably I overstated it

That's really frustrating. Precision is vital here otherwise we're going to waste time chasing benefits that don't exist.

> The hotspot was in `getAttributes()`

That methods takes < 1ms for me. As I said above, the main cost that I see is in `filter`. It takes 7ms with 3-4ms of that being the call to load the filters via `spring.factories`. That 7ms is time well spent  as it removes considerably more than 7ms of processing later on in startup. See https://github.com/spring-projects/spring-boot/issues/7573.

> Why do we even need to read the annotation metadata in that case?

To honour the `exclude` attribute.

**Comment by dsyer** [comment]
OK. So probably there is nothing further to do here for now. There was a real gain in the prototype, but it can't be translated into a general benefit for Spring Boot.
