### ISSUE TITLE
When doing an exponential backoff on a mono coming from a WebClient that has an error, an unexpected error is printed in the console

### ISSUE THREAD

**Issue by robisrob** [spring-projects/spring-boot#15497]
Problem: When doing an exponential backoff on a mono coming from a WebClient that has an error the following exception is printed in the console:
```java.lang.IllegalStateException: Only one connection receive subscriber allowed. ``` 

Version: Spring boot 2.1.1
 
I made an example project to demonstrate this problem: 
https://github.com/robisrob/webclient_bug

**Comment by bclozel** [comment]
Thanks for the report @robisrob , this was fixed already in [SPR-17564](https://jira.spring.io/browse/SPR-17564). We'll upgrade to the Spring Framework fixing this in #15493, so you'll have that fix in Spring Boot 2.1.2.RELEASE.
