### ISSUE TITLE
Merge conflict leftover after dependency updates

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#15534]
Hi,

I just updated my fork and noticed a corruption in `spring-boot-dependencies\pom.xml` - probably coming from a merge conflict. I currently don't have the overview which versions should be the correct ones, otherwise I'd fix it myself (especially because this is broken in 2.1.x as well).

Cheers,
Christoph

**Comment by dreis2211** [comment]
Just fixed by 974c4bfdb3c902b52a824a7c3bee3e96a923ee79 - sorry for the noise.

**Comment by wilkinsona** [comment]
Not at all. Thanks for making sure we were aware and sorry for the sloppy merge.
