### ISSUE TITLE
Issue on @version and RepositoryEntityController

### ISSUE THREAD

**Issue by asifbakht** [spring-projects/spring-boot#15547]
I have a class model having field version with @version annotation. This will increment on each update. Spring have `RepositoryEntityController` that automates every endpoints with POST, PUT , DELETE and GET etc.

While on "PUT" when send json data with higher/lower version in version field it sets proper version and saves data. After investigation I found that version field value is properly set before going through `RestEntityController`. I want control of version and do not want Spring-Boot control and change it. Spring should takes whatever version provided by user and saves in db if the version is higher or lower it should through exception. If version is properly set by spring then data will always be updated without knowing which user data was newer.

betweeen I am using MONGO DB and Spring 1.5.3 & java 8

**Comment by wilkinsona** [comment]
Thanks for the report. `RepositoryEntityController` isn't part of Spring Boot itself. It's part of Spring Data REST. If you would like to pursue this, please open a [Spring Data REST JIRA ticket](https://jira.spring.io/browse/DATAREST).
