### ISSUE TITLE
Documentation links in the README have not been updated following the move to pure Asciidoctor

### ISSUE THREAD

**Issue by JEuler** [spring-projects/spring-boot#15545]
Please check the links for the documentation in the readme file for repo. It seems, that they are not working. 
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/ - should be https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/

**Comment by wilkinsona** [comment]
Thanks. Looks like we missed this as part of #12611.
