### ISSUE TITLE
springboot project launch is very slow in mac machine

### ISSUE THREAD

**Issue by xiangjiexj** [spring-projects/spring-boot#15546]
spring boot project launch is very slow in mac machine.

**Comment by wilkinsona** [comment]
"Very slow" doesn't really tell us much, but I suspect this is due to a network configuration problem. Please see https://thoeni.io/post/macos-sierra-java/ for details. If that doesn't help, please take the time to describe exactly what is slow and we can re-open this issue and investigate.
