### ISSUE TITLE
Reactive health indicator for Redis waits forever when the redis server is down

### ISSUE THREAD

**Issue by dknc** [spring-projects/spring-boot#15542]
version:
spring-boot-actuator 2.1.1.RELEASE
spring-data-redis  2.0.5.RELEASE
letuce-core 5.0.4.RELEASE

Class: RedisReactiveHealthIndicator, method: doHealthCheck
 
Access the actuator health check  hangs when the redis server is down.  It hangs on calling the doHalthCheck method in RedisReactiveHealthIndicator.  

Expected behavior would be make it fail quickly instead of continuously hang.

**Comment by alimate** [comment]
When the Redis server is down at application startup, `ReactiveRedisConnectionFactory` can't give us a `ReactiveRedisConnection` to the Redis instance and we get a `DOWN` health check right away.

But when the Redis instance becomes unavailable or unresponsive after application startup (which btw is more probable in production), the following `Flux` chain would wait forever to get something back from the Redis instance:
```
connection.serverCommands().info().map((info) -> up(builder, info))
				.doFinally((signal) -> connection.close())
```

**Comment by snicoll** [comment]
Paging @mp911de

**Comment by mp911de** [comment]
Lettuce applies timeouts only to synchronous API calls and not to async/reactive API calls. 

Lettuce 5.1 introduced `TimeoutOptions` to control timeouts globally, so timeouts also apply to async/reactive API calls.

You can enable global timeouts by providing a `LettuceClientConfigurationBuilderCustomizer` such as 

```java
class ConfigCustomizer implements LettuceClientConfigurationBuilderCustomizer {

	@Override
	public void customize(LettuceClientConfigurationBuilder builder) {
		builder.clientOptions(ClientOptions.builder()
                     .timeoutOptions(TimeoutOptions.enabled(duration)).build());
	}
}
```

Spring Boot and Spring Data Redis have config properties for command timeouts, and we should consider configuring `TimeoutOptions` by default – probably in Spring Data Redis. I'm a bit torn as `TimeoutOptions` makes sense for reactive usage, non-reactive use is already covered. On the other side, the application type (reactive/non-reactive) is known by Spring Boot.

For now, how about adding a timeout operator to `RedisReactiveHealthIndicator` as suggested above?

What do you think?

**Comment by mp911de** [comment]
Let's address this issue in Spring Data Redis, I filed [DATAREDIS-918](https://jira.spring.io/browse/DATAREDIS-918) to provide a better default so if `ClientOptions` are not overwritten by a user, then global timeouts will also time out reactive API calls.

**Comment by snicoll** [comment]
Thanks for the support @mp911de!

**Comment by markuskruse** [comment]
Still doesn't work for me:
https://github.com/markuskruse/demo-redis-health-bug
Using spring boot 2.1.10

**Comment by mp911de** [comment]
You're disabling the timeout settings by configuring `LettuceConnectionFactory` yourself @markuskruse . Please remove the `LettuceConnectionFactory` bean from your config or configure `ClientOptions` with enabled `TimeoutOptions`.

**Comment by markuskruse** [comment]
It worked. Thank you very much (sorry for posting in a closed issue).
If you want the bounty on stackoverflow just post this as an answer.
https://stackoverflow.com/questions/58949065/redis-health-check-for-spring-boot-2-hangs
