### ISSUE TITLE
Add @ContributeInfo annotation

### ISSUE THREAD

**Issue by DariusX** [spring-projects/spring-boot#15558]
I'd like to declare/register certain informational items close to my code and have them show up in the /info endpoint. 

Imagine an annotation like this:
`@ContibuteInfo("tablesUsed", "INVOICE,INVOICE_DETAIL")`
used right before a SQL string in the code. One might even extend with a custom annotation, to get something like:
`@ContibuteInfoTablesUsed("INVOICE,INVOICE_DETAIL")`

Similarly, I might annotate URLs that will be called. 
It would be easy to declare properties or environment variables for such things. But if change-ability is not the issue, but trace-ability is, then documenting things close to the code -- without a level of indirection -- seems like a good choice.

**Comment by wilkinsona** [comment]
FWIW, I agree with @snicoll. I think a custom `InfoContributor` that collects to contributed information by whatever means best fits your needs is the right approach here. As such, I don't think we should do anything in Spring Boot itself.

**Comment by snicoll** [comment]
Thanks for the suggestion but we're not keen to introduce such a mechanism.
