### ISSUE TITLE
HierarchicalUriComponents.encodeUriComponent() method can not encode Pchar

### ISSUE THREAD

**Issue by sunbufu** [spring-projects/spring-boot#15557]
Hi guy,

I have a question about HierarchicalUriComponents.encodeUriComponent() method. I think it should encode all special char in url query param, Actually, It can not encode many special char. For example + - ! $ ... in url query param. and my email is sunyoubufu@qq.com .

**Comment by sunbufu** [comment]
and I created a JIRA https://jira.spring.io/projects/SPR/issues/SPR-17621

**Comment by bclozel** [comment]
`HierarchicalUriComponents` is part of Spring Framework, so there's no need to create another issue here. Thanks!

**Comment by sunbufu** [comment]
so, It's a bug or what ?
