### ISSUE TITLE
hiddenHttpMethodFilter 

### ISSUE THREAD

**Issue by WuYaoWang** [spring-projects/spring-boot#15560]
about **hiddenHttpMethodFilter** definition conflict
BeanDefinitionOverrideException: Invalid bean definition with name 'hiddenHttpMethodFilter' 
defined in class path resource **[org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]**
defined in class path resource **[org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration.class]**

at 
`<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.1.1.RELEASE</version>

<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-gateway</artifactId>
<version>2.0.2.RELEASE</version>`

**Comment by bclozel** [comment]
Spring Boot already addressed the issue in #14520.
Your issue looks very similar to 
spring-cloud/spring-cloud-gateway#629 and I believe you might be using a Spring Cloud version that’s incompatible with this Spring Boot generation. A new Greenwich RC has been recently published: 
https://spring.io/blog/2018/12/21/spring-cloud-greenwich-rc2-is-now-available
