### ISSUE TITLE
Upgrade to Hibernate ORM 5.4.0

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-boot#15570]
Hibernate 5.4.0 has been released with Java 11 support out the box. According to the release blog http://in.relation.to/2018/12/12/hibernate-orm-540-final-out/  It is designed to be a drop in replacement for ORM 5.3.x

Can this upgrade be done within the scope of Boot 2.1.2 timeline?

**Comment by snicoll** [comment]
Thanks for the suggestion but our upgrade policy does not allow feature upgrade in a maintenance release. We'll upgrade to Hibernate 5.4 as part of Spring Boot 2.2.

We also have a semi-automated process to upgrade dependencies so we'll process this in due course and therefore don't need an issue for it.
