### ISSUE TITLE
/resources/text.txt does not exist

### ISSUE THREAD

**Issue by ferhatyaman** [spring-projects/spring-boot#15571]
https://github.com/spring-projects/spring-boot/blob/b578dc05dfc0b9467ff2d8fcb4d81f86f7b5a302/spring-boot-samples/spring-boot-sample-web-jsp/src/main/webapp/WEB-INF/jsp/welcome.jsp#L9

I think there should be file to display but this text file does not exist.

**Comment by bclozel** [comment]
Indeed, the file doesn't exist but there is a test that checks that the spring taglib has been properly executed.

See `SampleWebJspApplicationTests`:

```
@Test
public void testJspWithEl() {
	ResponseEntity<String> entity = this.restTemplate.getForEntity("/", String.class);
	assertThat(entity.getStatusCode()).isEqualTo(HttpStatus.OK);
	assertThat(entity.getBody()).contains("/resources/text.txt");
}
```

The samples are really a mix of sample projects showing how to set up a technology and actual integration tests. In this case, there's no `text.txt` file but IMO it's alright as the link being processed in the JSP is the key. #6370 aims at fixing the integration test vs. sample problem.

Thanks for the heads up!
