### ISSUE TITLE
Document that `@ConditionalOnClass` should not be used directly on methods

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15578]
The condition can't be put in places where the JVM may have loaded the class and look at method definitions. 

A typical use case is a `@Bean` method that returns something and that something may not be on the classpath. Using the condition on the method will be useless as the JVM will load the class before the condition kicks in.

It would be nice to update both the ref guide and the javadoc.

**Comment by bondolo** [comment]
The documentation update wasn't nearly specific enough to be useful. This is still a painful problem to discover and diagnose. Can a clarification of "Extra care" be provided similar to the solution described in the doc?

**Comment by philwebb** [comment]
@bondolo I've opened #32166 and pushed [this update](https://github.com/spring-projects/spring-boot/commit/24c2daa99d29e42c375fa5355d96884a24063ad4). Feel free to comment on #32166 if you think further updates are needed.
