### ISSUE TITLE
LoggingSystemProperties  costs too much time to attain the ApplicationPid

### ISSUE THREAD

**Issue by tbwork** [spring-projects/spring-boot#15576]
See the fragment codes in LoggingSystemProperties: 

```
public void apply(LogFile logFile) {
		RelaxedPropertyResolver propertyResolver = RelaxedPropertyResolver
				.ignoringUnresolvableNestedPlaceholders(this.environment, "logging.");
		setSystemProperty(propertyResolver, EXCEPTION_CONVERSION_WORD,
				"exception-conversion-word");
		setSystemProperty(PID_KEY, new ApplicationPid().toString());
		setSystemProperty(propertyResolver, CONSOLE_LOG_PATTERN, "pattern.console");
		setSystemProperty(propertyResolver, FILE_LOG_PATTERN, "pattern.file");
		setSystemProperty(propertyResolver, LOG_LEVEL_PATTERN, "pattern.level");
		if (logFile != null) {
			logFile.applyToSystemProperties();
		}
	}
```

In the line of "`setSystemProperty(PID_KEY, new ApplicationPid().toString());`", we see every time the `apply()` function is called,  the `new ApplicationPid()` would be called too, and this will eventually call `ManagementFactory.getRuntimeMXBean().getName()` which costs about 5 seconds in my Mac-book.
And in my case, the `apply()` is often called in the startup stage.

I recommend to cache the Application's pid at the first time. Thanks. :)

**Comment by tbwork** [comment]
Further information: I found that  `ManagementFactory.getRuntimeMXBean().getName()` will call getVmId() which leads to "localhost" resolving, and eventually it leads to DNS lookup which is ambitious.
So, maybe this class should not call the `getName()` function and find another way to access the pid,
AND cache it.

**Comment by snicoll** [comment]
@tbwork you are most probably affected by a MacOS specific issue, see for instance [this blog post](https://thoeni.io/post/macos-sierra-java/). DNS lookup shouldn't take 5sec so caching this invocation shouldn't be necessary.

**Comment by nhunter1093** [comment]
Hello, 
This is Nick via iPhone S6 in NW Portland
