### ISSUE TITLE
Simplify agent setup for Boot Maven plugin

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#1559]
Currently defining the Boot plugin with an agent to be run requires something similar to the following:

``` xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-instrument</artifactId>
            <version>${spring.version}</version>
        </dependency>
    </dependencies>
    <configuration>
        <agent>${settings.localRepository}/org/springframework/spring-instrument/${spring.version}/spring-instrument-${spring.version}.jar</agent>
    </configuration>
</plugin>
```

Would be cool if the duplication could be reduced to `<agentDependency />` or even a wrapper to declare multiple ones. Is there maybe even a way to avoid the version declarations?

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by olivergierke** [comment]
Not necessarily qualifying as "much demand", it just felt like nicely matching the attention to detail and removing boilerplate themes that Spring Boot usually pursues.
