### ISSUE TITLE
Use the JAXB's BOM for dependency management 

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#15599]
The Glassfish JAXB RI provides a BOM file to ensure correct dependency versions (`org.glassfish.jaxb:jaxb-bom`). `spring-boot-dependencies` should be using this BOM instead of enumerating individual JAXB dependencies.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we can't use JAX-B's BOM as it manages the versions of dependencies from multiple projects that shouldn't necessarily be tied to the version of JAX-B.
