### ISSUE TITLE
@ConfigurationProperty validation not working when a key matching the prefix is set

### ISSUE THREAD

**Issue by mamachanko** [spring-projects/spring-boot#15597]
`@ConfigurationProperty` validation is great as it forces the application to not start if properties are invalid or missing. However, there is a case of partially missing properties that does not work as I expected.

 * Spring Boot version: `2.1.1.RELEASE`
 * Java version: `1.8`

# Steps to reproduce
Consider the following web app which exposes the property `app.value` at the endpoint `/`:

```java
package io.github.mamachanko.configurationpropertyvalidation;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.constraints.NotBlank;

@SpringBootApplication
public class ConfigurationPropertyValidationApplication {

    public static void main(String[] args) {
        SpringApplication.run(ConfigurationPropertyValidationApplication.class, args);
    }
}

@RestController
class Web {

    private Config config;

    Web(Config config) {
        this.config = config;
    }

    @GetMapping
    public String index() {
        return String.format("The configured value is '%s'.", config.getValue());
    }
}

@Configuration
@ConfigurationProperties(prefix = "app")
@Validated
class Config {

    @NotBlank
    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```

Assume I provide partially missing configuration in my `application.yml` as follows:
```yml
app:
```
The application comes up and exposes a null value:
```bash
➜  ~ curl localhost:8080/
The configured value is 'null'.%
```

What I would have expected is the same behaviour as for the following case. If I either fail to provide any configuration - `application.yml` is empty - or fail to provide the value
```yml
app:
  value:
```
... then (as expected) the application fails to come up
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'app' to io.github.mamachanko.configurationpropertyvalidation.Config$$EnhancerBySpringCGLIB$$e06d273 failed:

    Property: app.value
    Value: null
    Reason: must not be blank


Action:

Update your application's configuration
```

Am I missing an annotation or setting to also fail in the _odd_ case?

Thanks!

**Comment by snicoll** [comment]
@mamachanko thanks for the report, it looks like validation does not work properly if a property with key `app` is set in the `Environment` (it doesn't matter the value, I've tried `app=test` and it fails the same way). I've also reproduced the problem without yaml to confirm this isn't yaml specific.

(Side note, please do not flag your `@ConfigurationProperties` bean as `@Configuration`: these are not configuration classes providing `@Bean` definitions but regular `@Component` classes that are bound to the `Environment`).

**Comment by izeye** [comment]
It looks the milestone needs to be updated to 2.1.2.

**Comment by mbhave** [comment]
Done. Thanks @izeye!
