### ISSUE TITLE
actuator WebFluxTags#uri() cannot access other server's handlerMapping leads to tag explosion

### ISSUE THREAD

**Issue by youzipi** [spring-projects/spring-boot#15608]
I have two server  z-admin and z-gateway.
all request is sent to z-gateway and then dispatch to other servers (z-admin, ... )

In `org.springframework.boot.actuate.metrics.web.reactive.server.WebFluxTags#uri`,
the gateway cannot access the `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE`，as it is on `z-admin`. so it record the full path with path variable to the tag.

I found this commit:
[Avoid unbounded metrics creation for requests not handled by Spring MVC](
https://github.com/spring-projects/spring-boot/commit/b35e1ad232b5cf030cbb893aa51e92c71c8f135e)
But the `nomapping` seems not work in my situation

![](https://user-images.githubusercontent.com/5629307/50679499-a3955380-103e-11e9-9048-fc2ae1875e53.png)

## environment
```xml
<spring-boot.version>2.0.6.RELEASE</spring-boot.version>
<spring-cloud.version>Finchley.SR2</spring-cloud.version>
```

**Comment by bclozel** [comment]
Closing in favor of #15609.
