### ISSUE TITLE
Upgrade to Hikaricp 3.3.0

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15620]

**Comment by PascalSchumacher** [comment]
Just wondering why this is 2.2.0 only and not 2.1.x?

**Comment by snicoll** [comment]
Because our upgrade policy is to upgrade to a new feature release of a dependency in a feature release of Spring Boot or, said differently, not upgrade to a new feature release of a dependency in a maintenance release of Spring Boot. 

There's nothing preventing you to use `3.3.0` in Spring Boot 2.1 though.
