### ISSUE TITLE
Add import ordering instruction for spring-boot code

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#15623]
According to https://github.com/spring-io/spring-javaformat/issues/77, spring-javaformat plugin doesn't work for import ordering.

Can you share import layout somewhere?
Maybe in `CONTRIBUTING.adoc`?

**Comment by snicoll** [comment]
@ttddyy this should be taken care of by the Eclipse setup and I've just added some [instructions for `IntelliJ IDEA`](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#importing-into-intellij-idea). Before we consider dumping those rules in text I'd like to understand if that change matches this requirement.

**Comment by ttddyy** [comment]
@snicoll 
Thanks, yes, that's what I needed.
Since now it covers eclipse and intellij, it's good for me.
Generic rule might be helpful for other IDEs such as NetBeans, Visual Studio, etc.

**Comment by snicoll** [comment]
Thanks for the feedback.
