### ISSUE TITLE
SpringBoot2.1.1  There is no log when errors are encountered

### ISSUE THREAD

**Issue by kinsey-jian** [spring-projects/spring-boot#15632]
Hi，When i use spring boot 2.1.1，There is no log when errors are encountered，I find source code，
In the DefaultErrorWebExceptionHandler.class  
![image](https://user-images.githubusercontent.com/30062085/50757596-d176d400-129a-11e9-8bfa-8f97c71635ad.png)

Why the log is printed in debug mode

**Comment by bclozel** [comment]
Yes, this is all explained in the dedicated commit f2511b7fa3.
You can join us to chat on Gitter if you have other questions, we're trying to use the issue tracker for bugs and enhancements only.
Thanks!

**Comment by kinsey-jian** [comment]
@bclozel Sorry, I still haven't found this code in the 2.1.1.release
