### ISSUE TITLE
Now, I can send metrics to prometheus and elastic search，how can I send it to cloudwatch

### ISSUE THREAD

**Issue by TsingLiang** [spring-projects/spring-boot#15631]
Now, I can send metrics to prometheus and elastic search，how can I send it to cloudwatch。Is there any docs? I find that the source code doesn't include cloudwatch export

**Comment by snicoll** [comment]
Duplicate of https://github.com/micrometer-metrics/micrometer-docs/issues/49

**Comment by TsingLiang** [comment]
I didn't see cloudwatch，is there any docs or examples?
![image](https://user-images.githubusercontent.com/13382535/50758272-a4c3bc00-129c-11e9-8b6e-bbc79ab3ccdf.png)

**Comment by snicoll** [comment]
@TsingLiang please take the time to click on the link I've referenced.

**Comment by TsingLiang** [comment]
I'm sorry. I didn't see it :( . And this guy didn't see it too
![image](https://user-images.githubusercontent.com/13382535/50758855-58797b80-129e-11e9-8e3b-55a63dc83358.png)

**Comment by TsingLiang** [comment]
There is only aws sdk，but it not support actuator(micrometer).
