### ISSUE TITLE
Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.

### ISSUE THREAD

**Issue by xiaoxing598** [spring-projects/spring-boot#15633]
After I update the `actuate` version to `2.1.1`, the following warning appears. I need to know why I am prompted.

```
o.s.b.a.e.EndpointId                     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
o.s.b.a.e.EndpointId                     : Endpoint ID 'hystrix.stream' contains invalid characters, please migrate to a valid format.
```

**Comment by snicoll** [comment]
> I need to know why I am prompted.

Please take the time to review [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#endpoint-id-names) before opening an issue. Both these endpoints are Spring Cloud endpoints and are not handled here anyway.

**Comment by xiaoxing598** [comment]
Maybe my description is not clear, I want to know why this change was made, I am discussing the problem itself, instead of adding new features to the new version.

**Comment by snicoll** [comment]
@xiaoxing598 as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. You can ask questions on StackOverflow or join the community on Gitter.
