### ISSUE TITLE
Document using the same port for the management server on Cloud Foundry

### ISSUE THREAD

**Issue by milindsonawane** [spring-projects/spring-boot#15640]
I have deployed my spring boot application on PCF; all the actuator endpoints have been exposed. The actuator endpoints are configured as:

```
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.server.port=${CF_INSTANCE_PORT}
```

On hitting the `/actuator/**` or `/actuator`, the requests are redirected to `/` endpoint. This was verified by creating an endpoint in the controller. While the application worked perfectly on local environment, it failed on PCF (have not tried this in other env). If we add any actuator endpoint in a controller, it works smoothly. For example, I added `/actuator/health` is added in a controller and all the request for health endpoint were redirected to this endpoint within my controller.

The spring boot version is `2.0.5` and the spring cloud dependencies are managed under `Finchley.SR1`.

Here's the [code link](https://github.com/milindsonawane/spring_actuator).

**Comment by philwebb** [comment]
According to the [Cloud Foundry documentation](`https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-PORT`) `CF-INSTANCE-PORT` is the external port so I don't think it's possible to use it as a management port.

If you want to access actuator URLs using standard CF routes then try removing the `management.server.port=${CF_INSTANCE_PORT}` line from your properties file.

You should then be able to hit the actuator via `https://myapp.cfapps.io/actuator/health`.

**Comment by mbhave** [comment]
Since only a single port is routable through the go-router on CF (by default at least), we can document that `management.server.port` should be the same as `server.port` for a CF deployment.

**Comment by milindsonawane** [comment]
> 
> 
> According to the Cloud Foundry documentation `CF-INSTANCE-PORT` is the external port so I don't think it's possible to use it as a management port.
> 
> If you want to access actuator URLs using standard CF routes then try removing the `management.server.port=${CF_INSTANCE_PORT}` line from your properties file.
> 
> You should then be able to hit the actuator via `https://myapp.cfapps.io/actuator/health`.

Okay, but are the requests supposed to be redirected to `/` on adding the property on cloudfoundry?

**Comment by milindsonawane** [comment]
@philwebb Can I please request you to share the link of the documentation?

**Comment by milindsonawane** [comment]
> 
> 
> That is not related to CloudFoundry. You have an empty `@GetMapping` which acts as the fallback.
> 
> I'm going to convert this to a documentation issue to document using the same port for the management server for a CF deployment.
> 
> If you have any more questions, please ask on StackOverflow or join us on Gitter.

What might the issue be in this case? IMO, it should not fall back to an empty `@GetMapping` at all. The reason I tagged this as a Cloud Foundry issue is that I haven't seen this issue elsewhere.

**Comment by wilkinsona** [comment]
@milindsonawane The documentation is here: https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html. It's the first result (for me at least) when Googling for "CloudFoundry CF_INSTANCE_PORT".

**Comment by dilipmighty245** [comment]
@milindsonawane 

use ```eureka.instance.metadata-map.management.port=${CF_INSTANCE_PORT} ```
instead of 
```management.server.port=${CF_INSTANCE_PORT}``` , it will work.

**Comment by milindsonawane** [comment]
@dilipmighty245 
But it won't always be a micro-service. Also, this property helps only is case you are using eureka. What if someone opts for consul or zookeeper?
