### ISSUE TITLE
Include licence files in shipped jars

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15643]
@mp911de noticed that we don't include license/notice files inside our JARs whereas Spring Framework does. We do have copyright on each file and a license in our POM but we should consider if we also want to include it in the shipped JARs.

**Comment by mp911de** [comment]
As per the Apache license, the original binaries seem not to be required to include license/notice. The requirement comes from redistributing these binaries, so the redistributor needs to include these files. Having license/notice packaged would make it easier to redistribute Spring Boot jars.

**Comment by wagnerluis1982** [comment]
Hi, @philwebb. I'm candidating myself to deal with this issue. If it's okay, what files are to be changed? For now, I suppose to be a packaging issue, so it's related to Maven files.

**Comment by philwebb** [comment]
@wagnerluis1982 We'd need to find a way to add the file when the jars are build (we don't want to manually add a file to each project). One reason we pushed this issue back is we may work on some build improvements that might change the way this can be fixed.

**Comment by codingchica** [comment]
Do you mean something like the following?
https://www.mojohaus.org/license-maven-plugin/update-project-license-mojo.html

**Comment by wilkinsona** [comment]
Closing in favour of #20058.
