### ISSUE TITLE
Failed to send GenericMessage websockets 

### ISSUE THREAD

**Issue by rshibley** [spring-projects/spring-boot#15651]
After switching from spring boot 2.0.6 to 2.1.1 I'm getting the following error with no additional explanation. 

Failed to send GenericMessage [payload=byte[158], headers={spanTraceId=2e65817257823376, spanId=2e65817257823376, simpMessageType=MESSAGE, nativeHeaders={spanTraceId=[2e65817257823376], spanId=[2e65817257823376], spanSampled=[0]}, spanSampled=0, contentType=application/json;charset=UTF-8, simpDestination=/topic/chat:1}]

Everything works fine when I switch back to: 
    compile 'org.springframework:spring-websocket:5.0.10.RELEASE'
    compile 'org.springframework:spring-messaging:5.0.10.RELEASE'

I'm using StompClient with Websockets over Redis: 

       WebSocketClient client = new StandardWebSocketClient();
        WebSocketStompClient stompClient = new WebSocketStompClient(client);
        stompClient.setMessageConverter(new MappingJackson2MessageConverter());
        StompSessionHandler sessionHandler = new MyStompSessionHandler();
        stompClient.connect("ws://localhost:8080/pubsub/websocket", sessionHandler);

        private class MyStompSessionHandler implements StompSessionHandler {

        @Override
        public void afterConnected( StompSession session,  StompHeaders connectedHeaders) {
            session.subscribe("/topic/chat:1", this);
            pushService.push("chat","1","Test Message");
        }
        @Override
        public void handleException( StompSession session, StompCommand command,  StompHeaders headers,  byte[] payload,  Throwable exception) {
            exception.printStackTrace();
        }
        @Override
        public void handleTransportError( StompSession session,  Throwable exception) {
            exception.printStackTrace();
        }
        @Override
        public Type getPayloadType( StompHeaders headers) {
            return PushMessage.class;
        }
        @Override
        public void handleFrame( StompHeaders headers, Object payload) {
            PushMessage msg = (PushMessage) payload;
        }
    }

**Comment by snicoll** [comment]
@rshibley thanks for the report but both the artifacts you've defined are part of the Spring Framework that has [its own issue tracker](https://jira.spring.io/projects/SPR). Please report the issue there and, before doing so, consider creating a small sample as it is way more effective than (incomplete) code snippets.
