### ISSUE TITLE
Spring boot jpa does not report error present in sql that gets generated

### ISSUE THREAD

**Issue by gmhoolageri** [spring-projects/spring-boot#15656]
I created a new spring boot project with starter jpa with Oracle DB. I have a JPA entity with few fields(columns) and one among those columns is 

@Column(name = "REQUEST_DATA", columnDefinition = "varchar2(32767)")
private String requestData;

If you notice the column size of this field is very large. This is due to recommendations form oracle (https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adjsn/overview-of-storage-and-management-of-JSON-data.html#GUID-26AB85D2-3277-451B-BFAA-9DD45355FCC7).  

Now when I run my project I could see that sql query is being generated in the logs - 

_[INFO ] 2019-01-09 10:29:15.956 [main] FilterRegistrationBean - Mapping filter: 'requestContextFilter' to: [/*]
**Hibernate: create table request (id number(19,0) not null, creation timestamp, modification timestamp, request_data varchar2(32767), request_type varchar2(255 char), service_name varchar2(255), system_name varchar2(255), primary key (id))**
[INFO ] 2019-01-09 10:29:30.841 [main] LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'_

Actual table is not created in the database and no errors are reported. If I change the column size to 255 char then table is getting created. If I run the sql directly on the database I could see the error -  [Code: 910, SQL State: 42000]  ORA-00910: specified length too long for its datatype

Problem here is that I could not guess why the table is not being created. JPA should be reporting errors that are thrown back from database. This is just one usecase, there may be several different cases like this and I simply cannot trust spring boot jpa for larger scale applications.

**Comment by snicoll** [comment]
> JPA should be reporting errors that are thrown back from database.

Spring Boot does not implement JPA but configures an implementation (Hibernate by default via `spring-boot-starter-data-jpa`). This is the wrong issue tracker to report what you are experiencing.
