### ISSUE TITLE
Print build info if available at start

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#15650]
So the goal here is to be able to discern what version of my app someone (ops) is using. In debugging they are using the wrong version but it would have been a lot easier to tell if Spring Boot was simply logging the artifact information. This is essentially the same objective as https://stackoverflow.com/q/54083990/206466 where I'm trying to do it myself; but I think this would be a nice feature in 2.2. This needs to be logged as early as possible so that it happens before other significant logic/chance of failure can happen.

**Comment by snicoll** [comment]
This is already possible using the `MANIFEST`. Have you considered [using `${application.version}` in a custom banner](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-banner)?

**Comment by xenoterracide** [comment]
I hadn't but I will now, however I think this info (even if done this way) would be incredibly useful without customization. I will note that out of the box that the filename is printed, but one of the issues is person was renaming said file to be more generic, making it harder to debug the issue.

**Comment by snicoll** [comment]
One more time, please do not use the issue tracker for questions. If you need help to configure your build to add this entry, ask on StackOverflow.

**Comment by snicoll** [comment]
I don't think we should add more information by default to the banner. The current infrastructure is flexible enough to add more if needed and that includes the version of the app using the manifest.

**Comment by mvmn** [comment]
How can I get property like build.group in the banner?
