### ISSUE TITLE
link in wiki does not work

### ISSUE THREAD

**Issue by yami12376** [spring-projects/spring-boot#15662]
link from: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-boot-actuator
 in text "For more on this, check out the Micrometer documentation about Spring Boot 2.0."
refering to:
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-metrics

does not work.

**Comment by bclozel** [comment]
Thanks for the heads up, this is now fixed.
