### ISSUE TITLE
Configure JNDI over Embedded Tomcat

### ISSUE THREAD

**Issue by nekperu15739** [spring-projects/spring-boot#1566]
I´m trying to publish a jndi datasource with and embedded tomcat, but nothing works. following the samples on http://docs.spring.io/spring-boot/docs/1.1.6.RELEASE/reference/htmlsingle/#howto-configure-tomcat, folowing the xml configuration i had two objects: ContextResource like should be in server.xml and ContextResourceLink like should be in context.xml:

```
@Bean
    public EmbeddedServletContainerCustomizer containerCustomizer(){
        return new MyCustomizer();
    }


public class MyCustomizer implements EmbeddedServletContainerCustomizer {

        @Override
        public void customize(ConfigurableEmbeddedServletContainer factory) {
            customizeTomcat((TomcatEmbeddedServletContainerFactory) factory);           
        }

         public void customizeTomcat(TomcatEmbeddedServletContainerFactory factory) {
             TomcatContextCustomizer tomcatContextCustomizers = new TomcatContextCustomizer() {

                @Override
                public void customize(Context context) {
                    ContextResource resource = new ContextResource();
                    resource.setAuth("Container");
                    resource.setProperty("driverClassName", "oracle.jdbc.driver.OracleDriver");
                    resource.setProperty("global", "jdbc/aJNDIGlobal");
                    resource.setProperty("maxActive", "20");

                    resource.setName("jdbc/aJNDIGlobal");
                    resource.setProperty("password", "aaaaaaa");
                    resource.setType("javax.sql.DataSource");

                    resource.setProperty("username", "bbbbbb");

                    context.getNamingResources().addResource(resource);

                    ContextResourceLink resourceLink = new ContextResourceLink();
                    resourceLink.setName("jdbc/aJNDI");
                    resourceLink.setGlobal("jdbc/aJNDIGlobal");
                    resourceLink.setType("javax.sql.DataSource");
                    resourceLink.setProperty("auth", "Container");

                    context.getNamingResources().addResourceLink(resourceLink);

                    NamingResources namingResources = context.getNamingResources();
                    logger.info(namingResources);
                }
             };

            factory.addContextCustomizers(tomcatContextCustomizers);
         }

    }
```

In other try i add this line: tomcat.enableNaming();

but without results, can somebody help me with this, im stuck until finish it.

**Comment by garimamannan** [comment]
Hi, 
I am trying to have jndi setup for local setup(embedded tomcat) and i used your sample from Github but i am still getting the error 
org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script; nested exception is org.springframework.jndi.JndiLookupFailureException: JndiObjectTargetSource failed to obtain new target object; nested exception is javax.naming.NameNotFoundException: Name [jdbc/UcpDB] is not bound in this Context. Unable to find [jdbc].

I havent made any change in xml files. Is that whats missing? JNDI setup works on tomcat server but embedded tomcat is giving this error.

**Comment by philwebb** [comment]
@garimamannan This ticket has been closed for some time and we prefer to use the issue tracker only for bugs and enhancement requests. If you have a question please ask on http://stackoverflow.com
