### ISSUE TITLE
HATEAOS HAL representation does not work when Jaxb Annotation Module is in the context

### ISSUE THREAD

**Issue by jjoslet** [spring-projects/spring-boot#15663]
**Affect versions:** 1.5.16, 2.1.1

When adding the `com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule` Jackson Module in the context, the Spring HATEOAS HAL reprensentation does not work.

In the attached [sample.zip](https://github.com/spring-projects/spring-boot/files/2741265/sample.zip) project, instead of having the HAL response:
```
{
    "content": "Hello, World!",
    "_links": {
        "self": {
            "href": "http://localhost:8080/greeting?name=World"
        }
    }
}
```

I get:
```
{
    "content": "Hello, World!",
    "link": {
        "self": {
            "href": "http://localhost:8080/greeting?name=World"
        }
    }
}
```

`link` instead of `_links`.

See the [sample.zip](https://github.com/spring-projects/spring-boot/files/2741265/sample.zip) project to reproduce. This sample is based on https://github.com/spring-guides/gs-rest-hateoas

**Comment by snicoll** [comment]
Thanks for the report but Spring HATEOAS has [a dedicated issue tracker](https://github.com/spring-projects/spring-hateoas) and I am not sure I understand what issue you are reporting either.

`_links_` is the standard [property name](https://docs.spring.io/spring-hateoas/docs/0.25.0.RELEASE/reference/html/#client.link-discoverer) for links. It looks like you expect it to be `link` because you've added JAXB? 

What do you mean by "does not work" exactly?

**Comment by snicoll** [comment]
Sorry, I read the report backward. This looks a bit odd indeed and this also affects Spring Boot 2.x

**Comment by jjoslet** [comment]
By default using the HATEOS boot starter, the representation a Spring Hateoas resource is the HAL representation that produces the following (correct) JSON HAL representation:
```
{
    "content": "Hello, World!",
    "_links": {
        "self": {
            "href": "http://localhost:8080/greeting?name=World"
        }
    }
}
```
You can reproduce it from https://github.com/spring-guides/gs-rest-hateoas/tree/master/complete.

But when I add the `JaxbAnnotationModule` in the context:
```
@Bean
public Module jacksonJaxbAnnotationModule() {
	return new JaxbAnnotationModule();
}
```

The representation becomes:
```
{
    "content": "Hello, World!",
    "link": {
        "self": {
            "href": "http://localhost:8080/greeting?name=World"
        }
    }
}
```
which is not a correct HAL representation.
You can reproduce it using the provided sample.zip.

I don't think this is desired.

I created the issue first in the Spring Boot project since its related to the `HypermediaAutoConfiguration` from Spring Boot that enhance the HAL Object Mapper with the modules from the context but I admit that this is tightly coupled to the Spring Hateaos project ;).

**Comment by jjoslet** [comment]
I'll try to reproduce the same behavior using Spring Hateoas without the auto configuration from Spring Boot and reduce the problem to "The HAL ObjectMapper no more produces HAL representation if the JaxbAnnotationModule is installed".

**Comment by bclozel** [comment]
Hey @odrotbohm and @gregturn, any idea about this? Is this something we overlooked in our auto-configuration or should this be opened against Spring HATEOAS?

**Comment by jjoslet** [comment]
I've reproduced the same behavior disabling the `HypermediaAutoConfiguration` and using a `BeanPostProcessor` to register the `JaxbAnnotationModule` in the HAL Object Mapper (see [sample-no-autoconfigure.zip](https://github.com/spring-projects/spring-boot/files/2741535/sample-no-autoconfigure.zip)).

Therefore, I will open an issue in Spring HATEOAS project.

**Comment by snicoll** [comment]
Thanks @jjoslet - superseded by https://github.com/spring-projects/spring-hateoas/issues/783
