### ISSUE TITLE
HibernateJpaAutoConfiguration does not find class org.hibernate.jpa.HibernateEntityManager in Spring Boot 2.1.1

### ISSUE THREAD

**Issue by mefernandez** [spring-projects/spring-boot#15661]
I have created a Spring Boot 2.1.1 application using https://start.spring.io.
I added JPA, H2, MVC and Lombok starters.

I added a `CRUDRepository` and an `@Entity`.

```java
public interface MyRepository extends CrudRepository<MyEntity, Long> {

}
```

```java
@Entity
public class MyEntity {
	
	@Id
	Long id;
	
}
```

When running the application i get the following error:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'entityManagerFactory' available
```

The **CONDITIONS EVALUATION REPORT** shows this:
```
   HibernateJpaAutoConfiguration:
      Did not match:
         - HibernateEntityManager did not find classes 'org.hibernate.ejb.HibernateEntityManager', 'org.hibernate.jpa.HibernateEntityManager' (HibernateJpaAutoConfiguration.HibernateEntityManagerCondition)
      Matched:
         - @ConditionalOnClass found required classes 'org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean', 'javax.persistence.EntityManager' (OnClassCondition)
```

The code in `HibernateJpaAutoConfiguration` fails to find `org.hibernate.ejb.HibernateEntityManager`  and `org.hibernate.jpa.HibernateEntityManager` classes.

```java
		@Override
		public ConditionOutcome getMatchOutcome(ConditionContext context,
				AnnotatedTypeMetadata metadata) {
			ConditionMessage.Builder message = ConditionMessage
					.forCondition("HibernateEntityManager");
			for (String className : CLASS_NAMES) {
				if (ClassUtils.isPresent(className, context.getClassLoader())) {
					return ConditionOutcome
							.match(message.found("class").items(Style.QUOTE, className));
				}
			}
			return ConditionOutcome.noMatch(message.didNotFind("class", "classes")
					.items(Style.QUOTE, Arrays.asList(CLASS_NAMES)));
		}
```

The `ClassUtils.isPresent(className, context.getClassLoader())` expression returns `false` for both classes.

The same code works ok for Spring Boot versions `2.0.7.RELEASE` and `1.5.18.RELEASE`.

**Comment by snicoll** [comment]
One jar got corrupted when it was downloaded from the Maven repository. Please clean your cache for `2.1.1.RELEASE` and try again and if you need help with that, there are several threads on StackOverflow already.

**Comment by mefernandez** [comment]
Thanks @snicoll, I deleted the `~/.m2/repository/org/hibernate/hibernate-core/5.3.7.Final` directory and now it works. I'm curious, how did you know one jar got corrupted? It's not obviuos to me.

**Comment by snicoll** [comment]
We've had that kind of report dozens of times unfortunately so we can easily detect them now.
