### ISSUE TITLE
Add a failure analyzer for Flyway's bootstrap failure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15674]
See https://github.com/spring-io/initializr/issues/799 for a concrete use case but there might be others we could consider while implementing this.

**Comment by anandshastri1990** [comment]
Hi I would like to work on this issue. I have gone through the suggested use case. I can implement similar solution here as well. Do you have any other failure scenarios in your mind or I can spend some time to investigate and find out more.

**Comment by snicoll** [comment]
Thanks for the offer. I don't have any other failure scenarios since I haven't investigated yet but feel free to give that a try if you can though having a dedicated report for this case alone would be great. Looking forward to your PR then.

**Comment by anandshastri1990** [comment]
Thanks for the response. I have raised PR against master. Please let me know if I need to change it to a specific version or in case of any code changes.

**Comment by ielatif** [comment]
Resolved by #16015

**Comment by snicoll** [comment]
Good catch @ielatif, I forgot to close this one.

Closing in favour of PR #16015
