### ISSUE TITLE
A better cookie support in HTTP Tracing of Spring Boot Actuator 

### ISSUE THREAD

**Issue by ackintosh** [spring-projects/spring-boot#15678]
Hi, I'm trying to use [HTTP Tracing](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-http-tracing.html) to trace request values, especially a particular cookie value.

It is possible to obtain the "Cookie" header with the following but the value is not one I expected as that is whole of the "Cookie" header value:

```kotlin

class AccessLoggingHttpTraceRepositoryDecorator(
        private val repository: HttpTraceRepository,
        private val logger: Logger
    ) : HttpTraceRepository {

    // ...

    override fun add(trace: HttpTrace) {
        trace.request.headers["Cookie"].first()
        // JSESSIONID=xxxxxxxx; FOO=foovalue; BAR=barvalue; ...
    }
}

```

I think it is better if we can obtain a particular cookie value like below:

```kotlin
    // ...

    override fun add(trace: HttpTrace) {
        trace.request.cookies["FOO"].first()
        // foovalue
    }
```

What do you think about this? I would file a PR if it's OK. :octocat:

**Comment by wilkinsona** [comment]
I'm not sure that the new functionality we'd be of sufficiently broad interest to justify the changes that would have to be made. HTTP tracing has to web framework agnostic so we'd have to introduce our own equivalents of Spring Framework's `HttpCookie` and `ResponseCookie` classes. I think we'd also have to make additions to the public `TraceableRequest` and `TraceableResponse` interfaces which, even with default methods, would be difficult to do in a backwards-compatible manner.

Perhaps you could provide some more information about exactly what you want to do. I don't yet understand why having access to a particular cookie during HTTP tracing is important to you. At the moment, it sounds like you're trying to use HTTP tracing for something more specific than it is intended to be used for.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
