### ISSUE TITLE
Liquibase datasource is not closed when liquibase endpoint is disabled

### ISSUE THREAD

**Issue by jumal** [spring-projects/spring-boot#15693]
Spring Boot version: 2.1.2

Liquibase datasource is not closed when liquibase endpoint is disabled.

This seems to be caused by `LiquibaseEndpointAutoConfiguration`'s BeanPostProcessor calling `DataSourceClosingSpringLiquibase.setCloseDataSourceOnceMigrated(false)` even if `LiquibaseEndpointAutoConfiguration` is annotated with `@ConditionalOnEnabledEndpoint(endpoint = LiquibaseEndpoint.class)`

application.properties reproducing the issue:
```
management.endpoints.web.exposure.include=health
spring.datasource.url=jdbc:h2:mem:foo
spring.datasource.username=foo
spring.datasource.password=foo
spring.liquibase.user=foo
spring.liquibase.password=foo
```

**Comment by snicoll** [comment]
That configuration does not disable the endpoint. The `include` property has nothing to do with enablement. If you want to disable the liquibase endpoint, there is `management.endpoint.liquibase.enabled=false`

**Comment by jumal** [comment]
Thanks @snicoll for your quick feedback and pointing out this subtlety
