### ISSUE TITLE
Profile specific properties does not inheric since 2.1.2 (compared to 2.1.1)

### ISSUE THREAD

**Issue by kdejaeger** [spring-projects/spring-boot#15699]
I tried out the new release today and noticed my profile specific properties do not take the 'base' configuration into account. Am I doing it wrong?

I have a file application.yml with the property spring.main.allow-bean-definition-overriding set to true.
In my 'dev' profile (file application-dev.yml), I have not set this redundant setting.

2.1.1 -> property inherits properly
2.1.2 -> property does not seem to inherit ( works if I add it manually to the application-dev.yml file )

What could this be.

**Comment by mbhave** [comment]
@kdejaeger I don't recollect anything related to profile specific properties changing between `2.1.1` and `2.1.2`. Can you share a minimal sample that we can use to reproduce the issue?

**Comment by kdejaeger** [comment]
Here are some files [toreproduce.tar.gz](https://github.com/spring-projects/spring-boot/files/2758640/toreproduce.tar.gz).

**Comment by kdejaeger** [comment]
Ok, I'll try later today maybe.

**Comment by kdejaeger** [comment]
And whatdoyouknow ... I cannot reproduce it anymore. It was intellij fooling me probably.
