### ISSUE TITLE
Provide the ability to get the Spring Boot version

### ISSUE THREAD

**Issue by sdavids13** [spring-projects/spring-boot#15700]
Please provide the ability to get the current Spring Boot version from the Gradle plugin (similar to how the `SpringBootPlugin.BOM_COORDINATES` is available). I am currently incorporating `org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure` which isn't included in the Spring BOM so I need to maintain the Spring Boot version in two places (the `plugins` definition and a separate property since `plugins` doesn't allow the use of properties). Ideally I would only define the Spring Boot version in the `plugins` section then be able to access that same version later.

It looks like we can merely make the [private static final SPRING_BOOT_VERSION](https://github.com/spring-projects/spring-boot/blob/33f2bd4d61d9449c833aa1b8562405cff512ed9e/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/SpringBootPlugin.java#L50) `public` and call it a day.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I'm not sure that increasing the surface area of Boot's public API is justified to work around a limitation in Gradle. The situation with `spring-security-oauth2-autoconfigure` is also only temporary, there's no guarantee that the versions will be maintained in lock-step, and there's already a window where a version of Spring Boot exists but the same version of `spring-security-oauth2-autoconfigure` does not so I'm not sure that I would recommend using the same version for each.

If using the same version for each is something that you want to do, have you considered using a workaround for the Gradle limitation such as [this one](https://github.com/gradle/gradle/issues/1697#issuecomment-386824663) instead? There's also support in the dependency management plugin for [accessing a managed version](https://docs.spring.io/dependency-management-plugin/docs/1.0.7.BUILD-SNAPSHOT/reference/html5/#working-with-managed-versions-programmatic-access), albeit with [some caveats](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/193).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
