### ISSUE TITLE
Rename ElasticSearchJestHealthIndicatorAutoConfiguration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15705]
It should be `ElasticsearchJestHealthIndicatorAutoConfiguration`

**Comment by snicoll** [comment]
Closing in favour of PR #15723

**Comment by snicoll** [comment]
While reviewing the related PR, we've decided not to pursue this, see https://github.com/spring-projects/spring-boot/pull/15723#issuecomment-464116701 for more details
