### ISSUE TITLE
EndpointRequest shouldn't match request on main application port when management port is different 

### ISSUE THREAD

**Issue by DenisGlot** [spring-projects/spring-boot#15702]
In my spring boot 2 application the management port and server port are different. I'm trying to disable security for all endpoints in the management server. I disabled security as was described [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0#disabling-actuator-security-but-not-user-defined-endpoints). Yet my main application paths `/actuator/<endpoint>` have become insecure too.

**Comment by mbhave** [comment]
We discussed this on the team call today and think that making `EndpointRequest` port aware is only part of the problem. We need some samples/documentation on how to configure security just for the management context.
