### ISSUE TITLE
Add properties for setting the elasticsearch high level rest client timeouts

### ISSUE THREAD

**Issue by cbm-afoulfoin** [spring-projects/spring-boot#15701]
Hi, 
There are 2 ES clients supported by spring boot autoconfiguration: 
- Jest 
- The official ES RestHighLevelClient

For configuring Jest (`org.springframework.boot.autoconfigure.elasticsearch.jest.JestProperties`), we can set the properties `connectionTimeout` and `readTimeout`.
For configuring the ES RestHighLevelClient (`org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientProperties`), we can only set the uris, username and password, but not the timeouts that can only be set by a `RestClientBuilderCustomizer`.

Since timeouts are common properties that often need to be customized, it would be great to be able to configure them the same way spring boot is doing for Jest, via properties only (under `spring.elasticsearch.rest.*`).

Thanks!

**Comment by bclozel** [comment]
Superseded by #15965
