### ISSUE TITLE
HttpMessageConvertersAutoConfiguration should be conditional on not being a reactive web application

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15712]
Http message converters shouldn't be used in a reactive web application, but may be used in a servlet-based web application or a non-web application. We should update the conditions on HttpMessageConvertersAutoConfiguration accordingly to avoid their auto-configuration when running a reactive web application.

**Comment by dsyer** [comment]
They are used in `RestTemplate` though, right, and there is autoconfiguration for that (probably needs to be picked apart and offered separately to `WebClient`)?

**Comment by wilkinsona** [comment]
We talked about that, and decided that no one should be using `RestTemplate` in a reactive web application as it's a blocking API. We probably need an issue similar to this one to disable `RestTemplate` auto-configuration in the same situation.

**Comment by daslan31** [comment]
What if I'm using FeignClient for invoking api's outside of the app? FeignClientsConfiguration requires these converters, in order to workaround this I'm creating these beans by myself

**Comment by wilkinsona** [comment]
You should use https://github.com/Playtika/feign-reactive or similar in a reactive application.
