### ISSUE TITLE
Review "Working with Git branches"

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15739]
This page may be outdated or require a refresh. 

Potentially interesting resource: https://yastgithubio.readthedocs.io/en/latest/maintenance-branches/

**Comment by wilkinsona** [comment]
@philwebb has [updated](https://github.com/spring-projects/spring-boot/wiki/Working-with-Git-branches/_compare/b51b9914190d6bbe78e1a80a390d1ba7dbc87b97...826a50497e377f7c1748932681f4ec3eb2db26bd) the page on the wiki.
