### ISSUE TITLE
Wrong version of text banner logo (2.1.2.RELEASE) show 2.1.1.RELEASE

### ISSUE THREAD

**Issue by donhuvy** [spring-projects/spring-boot#15741]
My file `build.gradle`
```
buildscript {
	ext {
		springBootVersion = '2.1.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}
```

Logo
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.1.RELEASE)
```

![version](https://user-images.githubusercontent.com/1328316/51429155-6d5ef300-1c3e-11e9-88ab-bafc871db343.png)

**Comment by donhuvy** [comment]
![version](https://user-images.githubusercontent.com/1328316/51429146-4e606100-1c3e-11e9-9eee-75f7f0cc87b6.png)

**Comment by snicoll** [comment]
@donhuvy the spring boot version shows fine on a vanilla app created on start.spring.io. Your screenshot does not help us help you and it must be some sort of sync issue between your build and the generated artifact. 

In the future, please ask questions on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by donhuvy** [comment]
I am sorry, this is not an issue.
