### ISSUE TITLE
Ambiguous documentation about ConfigurationProperties

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-boot#15753]
[This paragraph](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) is a bit ambiguous and could benefit from some rewording:

> Even if the preceding configuration creates a regular bean for `AcmeProperties`, we
recommend that `@ConfigurationProperties` only deal with the environment and, in
particular, does not inject other beans from the context. Having said that, the
`@EnableConfigurationProperties` annotation is _also_ automatically applied to your
project so that any _existing_ bean annotated with `@ConfigurationProperties` is
configured from the `Environment`. You could shortcut `MyConfiguration` by making sure
`AcmeProperties` is already a bean, as shown in the following example:

* Why is this section started with _Even if the preceding configuration creates a regular bean for `AcmeProperties` [...]_, in particular _Even if_? It either creates a bean or it doesn't. From memory, merely annotating a POJO with `@ConfigurationProperties` does not turn it into a bean. Even if it did, this paragraph should read _The preceding configuration creates a regular bean for `AcmeProperties`_
* Then, why is it connected to the next paragraph using _Having said that [...]_?
* Finally, in _You could shortcut `MyConfiguration` [...]_, what are we shortcutting? In other words, what is getting shortcut if we annotate `MyConfiguration` with `@Component`? It turns the POJO into a bean, but what is getting shortcut?

**Comment by snicoll** [comment]
@behrangsa would you consider submitting a PR that improves the paragraph?

**Comment by viktoriya-kutsarova** [comment]
@snicoll If @behrangsa is not going to tackle this issue, I would like to take it.

**Comment by snicoll** [comment]
Thanks for the offer @viktoriya-kutsarova. Please go ahead and let us know if you need anything.

**Comment by mbhave** [comment]
Closing in favor of PR #16166.
