### ISSUE TITLE
The function parameter deleted in DefaultHashOperations is not clear

### ISSUE THREAD

**Issue by ch0ice** [spring-projects/spring-boot#15755]
spring boot version = 2.1.1.RELEASE
When I use the following code
``` java
redisTemplate.opsForHash().delete(key);

@Override
public Long delete(K key, Object... hashKeys) {

	byte[] rawKey = rawKey(key);
	byte[][] rawHashKeys = rawHashKeys(hashKeys);

	return execute(connection -> connection.hDel(rawKey, rawHashKeys), true);
}
```
This function should pass two parameters, because it uses the "..." syntax, so it can not pass parameters marked as "...", but the second parameter is used in the function, which results in compilation success, but runtime error.

**Comment by wilkinsona** [comment]
Thanks for the report, but `org.springframework.data.redis.core.HashOperations.delete(H, Object...)` is part of Spring Data Redis. It uses [JIRA](https://jira.spring.io/projects/DATAREDIS) for its issue tracking. Unfortunately, I can't move an issue from JIRA to GitHub. If you'd like to pursue this, please open a DATAREDIS JIRA ticket. If you do so, please comment here with a link to it.

**Comment by ch0ice** [comment]
Thank you for your reply, this is the JIRA link https://jira.spring.io/browse/DATAREDIS-924
