### ISSUE TITLE
Inject dependencies into auto-configuration classes more precisely

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15751]
This is an expansion of https://github.com/spring-projects/spring-boot/issues/15750.

There are a number of places in Boot's auto-configuration where a dependency is injected into a configuration class's constructor and then only used in a single `@Bean` method. This is inefficient when the `@Bean` method is conditional and its conditions don't match. For example, `BatchAutoConfiguration` injects `ObjectProvider<JobParametersConverter>` into its constructor and then only uses it in `jobOperator` which will back off if there's an existing `JobOperator` bean. Another, similar example is `RabbitTemplateConfiguration`'s injection of `ObjectProvider<MessageConverter>`.

**Comment by bhargodevarya** [comment]
I would like to work on this.

**Comment by wilkinsona** [comment]
Thanks for the offer, @bhargodevarya, but as shown by the issue being assigned, we are already working on this one.
