### ISSUE TITLE
Provide a different more convenient API/configuration model for actuator enabling

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#15762]
Following on from #15451... If I want to disable all endpoints except a handful (including all the beans that go with them) it's painful because I need to enumerate all the actuator endpoints and explicitly set their enabled flag to "false". I would prefer it if there was a way to group them together, or provide a pattern (like there is for the HTTP endpoints).

**Comment by wilkinsona** [comment]
Duplicate of #15460?
