### ISSUE TITLE
dev-tools ConditionEvaluationDeltaLoggingListener on multi-child context application

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-boot#15766]
I tried to run multi-context spring-boot application as Andy Wilkinson described in his [answer](https://stackoverflow.com/a/54309688/758991) and it works, but some strange thing happen: `ConditionEvaluationDeltaLoggingListener`  prints report between first and second child context start.

It prints:

```
2019-01-22 16:40:46.477  INFO 3268 --- [  restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation delta:


==========================
CONDITION EVALUATION DELTA
==========================


Positive matches:
-----------------

   DispatcherServletAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
```

..and many more rows.

Andy thinks that it can be a bug in `dev-tools`, so I opened report here.
MCVE: [gh-15766.zip](https://github.com/spring-projects/spring-boot/files/2786494/gh-15766.zip)
You can run it with `mvnw spring-boot:run`.

Spring boot: 2.1.2.RELEASE

**Comment by wilkinsona** [comment]
Thanks for opening an issue. We need to update ConditionEvaluationDeltaLoggingListener to be aware of the context for which the previous report was generated, otherwise it will report a delta between two different contexts rather than two different iterations of the same context.
