### ISSUE TITLE
Complete migration to AssertJ-based exception assertions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15761]
Following on from https://github.com/spring-projects/spring-boot/issues/14336, there are still some places where we are not using AssertJ-based exception assertions. Here's one example: https://github.com/spring-projects/spring-boot/blob/babe98f06418ede9e9d518e04e36d869c04fffc3/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/web/embedded/netty/SslServerCustomizerTests.java#L62-L70

**Comment by philwebb** [comment]
We probably can't checkstyle those either :( I guess using `fail()` is pretty rare, but I'm not sure we should ban it.

**Comment by rhamedy** [comment]
Need help with this?

**Comment by snicoll** [comment]
@rhamedy thanks for the offer. I'd be more than happy to review a PR for this one.

**Comment by wilkinsona** [comment]
@rhamedy @snicoll I've already made a start on this one (hence it being assigned to me). Thanks for the offer, but I don't think we need help with this one.
