### ISSUE TITLE
Consistently enable/disable http/1.1 when http/2 is configured

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#15764]
As seen in #15742, enabling http/2 in a Spring Boot app is not always consistent depending on the chosen server.

Jetty and Undertow support both http/1.1 and http/2 at the same time. Tomcat supports only http/2.

We should update the infrastructure setup to have a consistent experience for all servers, including Netty which hasn't been checked when this issue was created.

**Comment by mbhave** [comment]
I tried this with http/2 enabled on `SampleTomcatSslApplication` and `curl --http1.1 https://localhost:8443` was able to fallback to http1.1. Netty behaves the same. Closing the issue as the inconsistency doesn't seem to exist anymore.
