### ISSUE TITLE
Filter is not initialized on startup with Undertow

### ISSUE THREAD

**Issue by ldcsaa** [spring-projects/spring-boot#15771]
spring-boot (v1.5.18.RELEASE) can not init filter on startup while use undertow server, even if I set the property "server.undertow.eager-filter-init=true".
But tomcat server can do it correctly.

**Comment by mbhave** [comment]
@ldcsaa Can you please share a complete, minimal project that reproduces the problem? That should be something that we can unzip or a Git repository that we can clone and then run.

**Comment by wilkinsona** [comment]
@ldcsaa Please don't make the same comment on multiple issues.
