### ISSUE TITLE
Pristine 2.1.2.RELEASE web app stops after start

### ISSUE THREAD

**Issue by mamachanko** [spring-projects/spring-boot#15781]
Hi. My pristine Spring Boot web app with version `2.1.2.RELEASE` stops right after it starts. Version `2.1.1.RELEASE` starts and stays up as expected. By _pristine_ I mean generated via `start.spring.io`.

I am running:
 * OSX `10.13.6`
 * Java `1.8.0.191`

It can consistently reproduce it with this script: https://gist.github.com/mamachanko/b31d91da164bcec82eb0cc12b79ca3f3#file-spring-boot-web-app-sh
(shortened to: https://git.io/fhr4u)

# `2.1.1.RELEASE` works as expected
The app starts and stays up as expected. 

Reproduce with this script:
```bash
curl -sL git.io/fhr4u | bash -s 2.1.1.RELEASE
```
See log [here](https://gist.github.com/mamachanko/b31d91da164bcec82eb0cc12b79ca3f3#file-2-1-1-release). 

# `2.1.2.RELEASE` shuts down after start
The app starts but shuts down right away. There is no error in the application logs. 

Reproduce with this script:
```bash
curl -sL git.io/fhr4u | bash -s 2.1.2.RELEASE
```
See log [here](https://gist.github.com/mamachanko/b31d91da164bcec82eb0cc12b79ca3f3#file-2-1-2-release).

There's [this]https://gist.github.com/mamachanko/b31d91da164bcec82eb0cc12b79ca3f3#file-2-1-2-release-L57-L58) error in the from the Maven compiler plugin:
```
[ERROR] error reading /Users/user/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.14/tomcat-embed-core-9.0.14.jar; zip file is empty
```
However, the Spring app still doesn't complain other than just shutting down. I wouldn't have expected that from a patch release.

I cannot reproduce the issue using the `openjdk:8-jdk` docker image.

**Comment by wilkinsona** [comment]
2.1.2 includes a new version of Tomcat. When Maven downloaded the tomcat-embed-core jar for that version it corrupted it and wrote out an empty jar. As a result, there's no embedded container on the classpath so one isn't started. With no container running in the app there are no threads left alive once the main thread exits so the JVM stops. In short, you need to take heed of the compiler warning from Maven, delete the empty jar from your local cache, and rebuild your app.
