### ISSUE TITLE
Allow for nested objects in HealthIndicator details

### ISSUE THREAD

**Issue by Lucas-C** [spring-projects/spring-boot#15795]
Given the following health indicator:
```java
@Component
public class MyHealthIndicator implements HealthIndicator {
    @Override
    public Health health() {
        Map<String, Object> subDetails = new HashMap<String ,Object>() {{
            put("B", 42);
        }};
        Map<String, Object> details = new HashMap<String ,Object>() {{
            put("A", subDetails);
        }};
        return Health.up().withDetails(details).build();
    }
}
```

I would like to be able to retrieve the health information on "B" in the REST indicator output:
```
curl -s http://localhost:8080/rest/manage/health/my | jq .details
{
  "A": null
}
```

**Comment by snicoll** [comment]
I am not sure I understand what you're asking, really. I've copy/pasted that to a project and got the following (as expected):

```
 http :8080/actuator/health/my
HTTP/1.1 200 
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Mon, 28 Jan 2019 10:57:12 GMT
Transfer-Encoding: chunked

{
    "details": {
        "A": {
            "B": 42
        }
    },
    "status": "UP"
}
```

**Comment by Lucas-C** [comment]
Interesting.
Thank you for testing my example.

I think that my issue may be specific to using Gson for serialization then.
I have this in my class implementing `WebMvcConfigurer`:
```java
    @Autowired
    Gson gson;

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        GsonHttpMessageConverter gsonHttpMessageConverter = new GsonHttpMessageConverter();
        gsonHttpMessageConverter.setGson(gson);
        converters.add(gsonHttpMessageConverter);
    }
```

**Comment by snicoll** [comment]
Gson is not supported by the Actuator at the moment (see #13766). If you have more questions, please ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
