### ISSUE TITLE
Don't publish docs jar to maven central

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#15809]
We should not publish a docs jar.

**Comment by snicoll** [comment]
Looks like that exclude has been a bit agressive :(

**Comment by wilkinsona** [comment]
I'm a bit wary that Central will reject a project with jar packaging that does not have a jar artifact.

**Comment by philwebb** [comment]
We unfortunately need to be a jar project:

```
[INFO] --- maven-javadoc-plugin:3.1.1:jar (attach-javadocs) @ spring-boot-docs ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
```

**Comment by philwebb** [comment]
I've reverted and declined the issue. It doesn't seem to be worth spending too much time on this.
