### ISSUE TITLE
Upgrade to Spring Doc Resources 0.1.0.RELEASE

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15805]
Our document generation pipeline relies on the snapshot at the moment. 

We don't have a reference to the release repository and we're not keen to add one as this repo serves artifacts that central also serves and we'd like to avoid that duplication.

Brainstorming with @wilkinsona, an alternative would be to publish that internal jar only in a separate repo we can add to our list, something like repo.spring.io/support or something.

**Comment by bclozel** [comment]
I'm willing to publish it on Maven Central as a `zip` or `.tar.gz` artifact if that helps.

**Comment by snicoll** [comment]
We've decided to try to "curl" the bits to avoid going to maven central for it
