### ISSUE TITLE
look like a word spelling mistake in spring-boot documentation

### ISSUE THREAD

**Issue by jinminer** [spring-projects/spring-boot#15803]
![image](https://user-images.githubusercontent.com/43385137/51881655-f3093e00-23b6-11e9-80e7-86fb861bda24.png)
i don't understand this word , that looks like a spelling mistake .

url: [https://docs.spring.io/spring-boot/docs/2.0.8.RELEASE/reference/htmlsingle/#boot-documentation-about](url)

**Comment by mbhave** [comment]
As @rhamedy mentioned, that is the intended word.
