### ISSUE TITLE
Run Mojo triggered from maven profile runs build helper twice because of phase binding.

### ISSUE THREAD

**Issue by warrenc5** [spring-projects/spring-boot#15817]
When the plugin is triggered from a profile it reruns the maven profile trying to parallel run test-compile.

This breaks plugins like build-helper reserve network port bound to any lifecycle phase earlier than test-compile. i.e initialize.

So I couldn't get the port properties into the spring-boot execution configuration. 

I found I had to move the spring-boot:run goal to the integration-test phase and build helper to pre-integration-test.

Can you make the default lifecycle of run goal integration-test ?

@Execute(phase = LifecyclePhase.TEST_COMPILE)
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/RunMojo.java

**Comment by snicoll** [comment]
I've edited your comment to remove the bug report part (the template has an explicit "do not copy paste" mention so please don't).

> Can you make the default lifecycle of run goal integration-test ?

That would be highly unusual and I thought we were aligned to official maven plugins (such as the exec plugin) but I can see they don't see to have a default phase.

Can you share a sample we can run ourselves that describes the issue you're experiencing?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by warrenc5** [comment]
Thanks a lot for your reply.  

I think this happens because the default lifecycle is bound to initialize so I can't get the build helper (or any other plugin) to run first. 

If I move spring-boot:run to after the test-compile - it EXECUTES initialize->test-compile again. 
Some plugins can't run twice (like build helper port reserve)

I have a test case here.

`mvn -X -Prun`

https://github.com/warrenc5/15817-springbootmavenplugin

You'll see my.server.port is already interpolated into the configured spring-boot:run plugin - and doesn't get re-evaluated after the execution test-compile has completed.  On the way to Test-compile ran build-helper.

The only way for me to fix this was to bind build helper to pre-integration-test (after of test-compile) and spring-boot:run bound to integration-test 

I tried to move the configuration of the plugin to pluginManagement and it re-ran every plugin in the profile < test-compile.

I noticed spring-boot:start/stop don't have this similar binding and execution.

**Comment by snicoll** [comment]
@warrenc5 thank you for the sample. `spring-boot:run` was never meant to be bound to an execution and I personally didn't expect someone to use it like that. 

Can you explain why you can't use `start` and/or why you're binding `run` the way you do?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
