### ISSUE TITLE
Upgrade java8 version in CI image

### ISSUE THREAD

**Issue by spring-buildmaster** [spring-projects/spring-boot#15813]
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz

**Comment by wilkinsona** [comment]
We're stripping too many components on 2.0.x. We end up with `java` in the right place as it comes from a more nested directory for the JRE but `javac` ends up in the wrong place.
