### ISSUE TITLE
Clarify in the docs whether Spring Boot plugin version must match the Boot dependencies version

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#15826]
In a multimodule (Gradle) project, only one of them is going to be the executable/fat jar, while the others are just libraries. The Boot Gradle plugin should ideally be applied only to the executable module, and the library dependencies should be managed using the Gradle dependency management plugin. The docs don't go into this common use case, and assume that every project is going to apply the Boot plugin, which as described above, is an oversimplified assumption for almost any sizeable enterprise project.

I'd like to understand the interdependencies of the various Boot dependencies (starters, and stuff pulled in by the starters) and the Boot plugin. What is the implication of having different versions for those? If there's a hard dependency that these must match up, it should be clearly stated in the docs.

**Comment by wilkinsona** [comment]
> The docs don't go into this common use case, and assume that every project is going to apply the Boot plugin, which as described above, is an oversimplified assumption for almost any sizeable enterprise project.

There's a [section](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/gradle-plugin/reference/html/#managing-dependencies-using-in-isolation] in the Gradle's plugins documentation about using Boot's dependency management without applying Boot's plugin.

> What is the implication of having different versions for those? If there's a hard dependency that these must match up, it should be clearly stated in the docs.

Mixing different versions of Boot's modules isn't a good idea and should be avoided. There's nothing Boot specific about that, though. You are free to override the versions of other dependencies and details of how to do so are also [provided in the documentation](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/gradle-plugin/reference/html/#managing-dependencies-customizing) along with a note about doing so with care.

As far as I can tell, the documentation already covers the situation you've described. If you think what's there could be improved or expanded upon, please feel free to open a pull request with some suggested changes and we'll take a look.
