### ISSUE TITLE
REST Endpoint unreachable if ID in URL contains %2F

### ISSUE THREAD

**Issue by patoi** [spring-projects/spring-boot#1583]
Version: Spring Boot 1.1.6

My assumption is that, this issue is related to https://jira.spring.io/browse/SPR-11101

URL:

```
http://localhost:9090/api/registration/7QMxEZSrvaWPVhq6eBAa4Q%2F%2Fwy6lUL5hdEvDb5QiT4ixdKZpQKnmoM4nmo7Iiu1A
```

If I remove %2F, it works fine.

```
http://localhost:9090/api/registration/7QMxEZSrvaWPVhq6eBAa4Qwy6lUL5hdEvDb5QiT4ixdKZpQKnmoM4nmo7Iiu1A
```

**Comment by celiovasconcelos** [comment]
Wonderful!!!

**Comment by bb245** [comment]
Setting this system property works fine only one %2F appear in the URL. In my case, I'm getting two %2F. Can you please advise if there is way this could be handled.
