### ISSUE TITLE
Illegal reflective access by org.springframework.boot.loader.jar.Handler when resolving classpath* resource pattern

### ISSUE THREAD

**Issue by tom-su** [spring-projects/spring-boot#15844]
Has anyone faced such a problem?

``WARNING: An illegal reflective access operation has occurred  
WARNING: Illegal reflective access by org.springframework.boot.loader.jar.Handler to method java.net.URLStreamHandler.openConnection(java.net.URL)     
WARNING: Please consider reporting this to the maintainers of org.springframework.boot.loader.jar.Handler  
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations  
WARNING: All illegal access operations will be denied in a future release  ``

* **Spring Boot 2.1.2.RELEASE**
* **Java 11 - (_openjdk 11.0.2-  Runtime Environment 18.9 (build 11.0.2+9)_)**
* **Gradle 5.1.1**

I'm running this app using java -jar. Beside this warning everything works fine.

**Comment by wilkinsona** [comment]
AFAIK, no one has faced the problem. I cannot reproduce it using `Java(TM) SE Runtime Environment 18.9 (build 11+28)`. Perhaps you could upgrade to a more recent build of Java 11. If the problem still occurs and you'd like us to spend some more time investigating, please take the time to provide a minimal sample that reproduces the problem.

**Comment by tom-su** [comment]
Ok, I've found that my configuration for myBatis is responsible for this problem.
I'm using 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.0.0' and this Warning occurs when application.yml contains:
``
mybatis:  
      mapper-locations: classpath*:**/mappers/*.xml
``

Warning disappeared when I remove asterisks from *mapper-locations*:
``
mybatis:  
  mapper-locations: classpath:/mappers/*.xml
``

**Comment by wilkinsona** [comment]
Thanks. We'll see what we can do.

As something of an aside, I would avoid using a location pattern like `classpath*:**/mappers/*.xml`. It will require every entry of every jar on the classpath to be scanned to see if it matches the pattern `**/mappers/*.xml`. The `classpath:/mappers/*.xml` pattern should be quite a bit more efficient.

**Comment by dschulz** [comment]
I don't know if this is relevant here, but I can reproduce this consistently by just importing [springdoc-openapi](https://github.com/springdoc/springdoc-openapi) dependency in a simple Spring Boot project with a few RestControllers.

I ran the bootJar (built with Gradle) with `--illegal-access=deny` to see what triggers the illegal  access:

`java --illegal-access=deny -jar build/libs/testproject-0.0.1-SNAPSHOT.jar`

and it blows up when accessing the Swagger UI, which requires to load the swagger-ui jar from the bootJar itself.

```
java.io.IOException: Unable to open root Jar file 'war:file:/Users/dschulz/workspace-sts/testproject/build/libs/testproject-0.0.1-SNAPSHOT.jar*/BOOT-INF/lib/swagger-ui-3.23.5.jar'
	at org.springframework.boot.loader.jar.Handler.getRootJarFile(Handler.java:316) ~[lecturas-0.0.7-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.jar.Handler.getRootJarFileFromUrl(Handler.java:298) ~[lecturas-0.0.7-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:84) ~[lecturas-0.0.7-SNAPSHOT.jar:na]
	at java.base/java.net.URL.openConnection(URL.java:1086) ~[na:na]
	at org.springframework.core.io.AbstractFileResolvingResource.contentLength(AbstractFileResolvingResource.java:239) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
...
(snip)
```

**Comment by philwebb** [comment]
@dschulz If you're seeing this with Spring Boot 2.1.9 could you please open a new issue and attach the example project that you created. Thanks.
