### ISSUE TITLE
Hi am facing below issue after spring boot 2 upgrade ..Service has been failing @ startup

### ISSUE THREAD

**Issue by chaitanyayelamakuru** [spring-projects/spring-boot#15849]

**Comment by chaitanyayelamakuru** [comment]
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DCAppealDomainServiceImpl': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.opt.optimum.ui.benefits.appeal.domain.DCAppealDomainServiceImpl] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@17f052a3]

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by chaitanyayelamakuru** [comment]
Thanks for reaching me out ..i would like to close this issue,
Root cause of this issue is due to another internal services causes this issue.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
