### ISSUE TITLE
spring-boot-maven-plugin changed behavior between 2.0.8 and 2.1.2

### ISSUE THREAD

**Issue by Anonymous-Coward** [spring-projects/spring-boot#15845]
1. Steps to reproduce

- Create a simple spring boot project using spring boot starter parent 2.0.8.RELEASE.
- Execute mvn clean install
- verify that only the fat jar gets deployed to ~/.m2/repository - not good, because the original jar is not usable as a dependency
- add this to the default spring boot maven plugin configuration:

```
<executions>
    <execution>
        <goals>
            <goal>repackage</goal>
        </goals>
        <configuration>
            <classifier>exec</classifier>
        </configuration>
    </execution>
</executions>
```
- delete the directory containing the previous build artifacts from ~/.m2/repository
- perform mvn install again
- verify that both the fat jar, with a classifier exec, and the original jar, with no modifications, gets deployed
- change the spring-boot-starter-parent version number in the project's pom to 2.1.2.RELEASE
- perform both builds again
- verify that in neither case the original slim jar gets deployed with no name change to ~/.m2/repository - this is bad, since there's no easy way to use the original jar as a dependency

2. Expected results

For both  spring boot 2.0.8 and spring boot 2.1.2 the spring boot maven plugin behaves identically, and it is easy to deploy the slim jar so that it is usable as a dependency.

3. Actual results

For spring boot 2.0.8 there is a simple way to install/deploy the original slim jar, with no name change, for using it as a dependency; for spring boot 2.1.2 there isn't a straightforward one. (I found one, but it involves using additional maven plugins, not related to spring boot.) The behavior of the spring boot maven plugin is different between spring boot 2.0.8 and 2.1.2.

4. Notes

I have attached a demo project where the portions that need to be enabled/disabled/changed while performing the steps described above are all commented. The initial state corresponds to the first build to be performed. In order to advance through the tests, different blocks need to be commented/un-commented.
[demo.tar.gz](https://github.com/spring-projects/spring-boot/files/2829958/demo.tar.gz)

**Comment by snicoll** [comment]
Have you read the release notes that mention that the [`repackage` execution has now an id](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#maven-plugin) that should be used?

Your plugin execution above is not how it should have been done in the first place as there is already an execution in the parent so if you want to tune these settings you just need to provide the id of the execution and the bit of configuration that you need. We didn't have an id which is why we added one.

If you look at the output with `2.1.2.RELEASE` you can see the plugin is invoked twice:

```
[INFO] --- spring-boot-maven-plugin:2.1.2.RELEASE:repackage (repackage) @ demo ---
[INFO] Replacing main artifact with repackaged archive
[INFO]
[INFO] --- spring-boot-maven-plugin:2.1.2.RELEASE:repackage (default) @ demo ---
[INFO] Attaching repackaged archive /Users/snicoll/Downloads/demo 5/demo/target/demo-0.0.1-SNAPSHOT-exec.jar with classifier exec
```

If I change the pom as follows it is only executed once:

```
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<executions>
				<execution>
					<id>repackage</id>
					<configuration>
						<classifier>exec</classifier>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
```

And the regular jar is the one that can be used as a `<dependency>`.
