### ISSUE TITLE
Configuration processor does not handle generics

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#15850]
Given

```java
@ConfigurationProperties("foo.bar")
public class GenericProperties extends AbstractPropeties<Foo> {

}
```

and
```java
public class AbstractPropeties<T> {

	private Map<String, T> props;

	public Map<String, T> getProps() {
		return props;
	}

	public void setProps(Map<String, T> props) {
		this.props = props;
	}

}
```

The generated metadata is

```json
{
  "groups": [
    {
      "name": "foo.bar",
      "type": "com.example.GenericProperties",
      "sourceType": "com.example.GenericProperties"
    }
  ],
  "properties": [
    {
      "name": "foo.bar.props",
      "type": "java.util.Map<java.lang.String,T>",
      "sourceType": "com.example.GenericProperties"
    }
  ],
  "hints": []
}
```

Should be
```json
{
  "groups": [
    {
      "name": "foo.bar",
      "type": "com.example.GenericProperties",
      "sourceType": "com.example.GenericProperties"
    }
  ],
  "properties": [
    {
      "name": "foo.bar.props",
      "type": "java.util.Map<java.lang.String,com.example.Foo>",
      "sourceType": "com.example.GenericProperties"
    }
  ],
  "hints": []
}
```

The generator should be able to determine the generic type.

Per Kris De Volder in Slack

>Generics is complex, so I'm never surprised if it breaks stuff like this. But in my opinion it should be considered a bug. The method may be inherted from a generic superclass (or overridden). But from the subclass point of view we know that type 'T' is really 'RabbitBindingProperties'. So its reasonable to expect the Spring boot annotation processor to treat 'T' as if it is equal to 'RabbitBindingProperties' in that context.
So I think you should raise a bug against spring boot configuration processor.

See https://github.com/spring-cloud/spring-cloud-stream/issues/1601

**Comment by snicoll** [comment]
Yes, you're right, the annotation processor should be able to resolve `T`. I deliberately ignored generics as I've been dealing with them in the past for another annotation processor I wrote and it's quite hard to get it right with all possible combinations. 

Would it be possible to simplify that arrangement to avoid the generics. We prefer that `@ConfigurationProperties` to be as simple as possible and limit hierarchies whenever possible.

Flagging for team attention to see what the rest of the team thinks.

**Comment by garyrussell** [comment]
```java
		Method method = ClassUtils.getMostSpecificMethod(
				ClassUtils.getMethod(GenericProperties.class, "getProps", new Class[0]), GenericProperties.class);
		Type returnType = method.getGenericReturnType();
		System.out.println(returnType);
```

    java.util.Map<java.lang.String, com.example.Foo>

**Comment by wilkinsona** [comment]
It's easy for me to say as I do not how hard it is to implement, but when I first saw the discussion on Slack my reaction was that this is something that we should support. That's still my view now so I'd like us to take a look at what it would entail.
