### ISSUE TITLE
Consider adding EVO inflector to managed dependencies

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#15852]
[EVO inflector](https://search.maven.org/artifact/org.atteo/evo-inflector/1.2.2/jar) is an optional dependency of [Spring HATEOAS](https://search.maven.org/artifact/org.springframework.hateoas/spring-hateoas/0.25.0.RELEASE/jar) that's used in a few places to enhance the handling of relations:

- https://docs.spring.io/spring-hateoas/docs/current/reference/html/#configuration.at-enable
- https://docs.spring.io/spring-hateoas/docs/current/reference/html/#spis.rel-provider

With that in mind, it would be nice if Spring Boot would provide dependency management for EVO inflector.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but to keep the scope of Boot's dependency management we try to limit it to dependencies that Boot interacts with. We don't interact with Evo Inflector so I do not think we should manage its version.

**Comment by vpavic** [comment]
Given the usefulness of EVO inflector, IMO a case could maybe even be made to make it a part of Spring HATEOAS starter - for example, [spring-projects/spring-hateoas-examples](https://github.com/spring-projects/spring-hateoas-examples) repo [uses it](https://github.com/spring-projects/spring-hateoas-examples/blob/dd57e0a515eb7d35681ce9521722281d37a16c87/pom.xml#L95-L99) for all the sample apps.

**Comment by wilkinsona** [comment]
I don't think the library is sufficiently active to feel comfortable including it in one of our starters. There were only 4 commits in 2018. Two of those appear to have been bug fixes but the most recent release was in 2016.

I'll mark this one for team attention to see what the rest of the team thinks.

**Comment by snicoll** [comment]
I don't see a compelling reason to add it either.
