### ISSUE TITLE
Change Logback's maxHistory property default to 7 days

### ISSUE THREAD

**Issue by anthofo** [spring-projects/spring-boot#15875]
Using Spring Boot 2.1.0 and logback.

It appears that the `file-appender.xml` configuration changed in Spring Boot 2 compared to Spring Boot 1.5 : https://github.com/spring-projects/spring-boot/commit/991468b0ef1d68b0fb6fc32d7a52e2a7b22f4281#diff-cc7bd2aeeab66c424f816d9e42ea9e53

The 1.5 file:

```xml
<included>
	<appender name="FILE"
		class="ch.qos.logback.core.rolling.RollingFileAppender">
		<encoder>
			<pattern>${FILE_LOG_PATTERN}</pattern>
		</encoder>
		<file>${LOG_FILE}</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
			<fileNamePattern>${LOG_FILE}.%i</fileNamePattern>
		</rollingPolicy>
		<triggeringPolicy
			class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
			<MaxFileSize>10MB</MaxFileSize>
		</triggeringPolicy>
	</appender>
</included>
```

The 2.1 file:
```xml
<included>
	<appender name="FILE"
		class="ch.qos.logback.core.rolling.RollingFileAppender">
		<encoder>
			<pattern>${FILE_LOG_PATTERN}</pattern>
		</encoder>
		<file>${LOG_FILE}</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
			<fileNamePattern>${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz</fileNamePattern>
			<maxFileSize>${LOG_FILE_MAX_SIZE:-10MB}</maxFileSize>
			<maxHistory>${LOG_FILE_MAX_HISTORY:-0}</maxHistory>
		</rollingPolicy>
	</appender>
</included>
```

The ` FixedWindowRollingPolicy` has been changed for a `SizeAndTimeBasedRollingPolicy`.
The issue is that the previous ` FixedWindowRollingPolicy` has a default rolling index of 7, keeping only 7 log files.

In Spring Boot 2.1, the `SizeAndTimeBasedRollingPolicy` is configured by default with a maxHistory of 0 (`<maxHistory>${LOG_FILE_MAX_HISTORY:-0}</maxHistory>`) , which means log files are kept indefinitly. Some of our servers crashed because of a full disk space, since old log files are not deleted anymore, this issue never happened with Spring Boot 1.5.

To prevent that, it would be great to set a default value (like 7 or 14) different than `0` for the `maxHistory` property. Users can still set the `LOG_FILE_MAX_HISTORY` property to set their own value if they wan, but it would prevent a lot of issues for users using the default config.

Thanks :)

**Comment by wilkinsona** [comment]
Allowing an unbounded number of log files to be written doesn't seem like a particularly good default to me, so I agree we should take a look at changing it. We may also want to consider adding `<totalSizeCap>` as well. I don't think we should change things in a maintenance release, but I think it would be reasonable to make a change in 2.2.x. We just need to decide what that change should be.

**Comment by wilkinsona** [comment]
We're going to default to a max history of 7. We'll leave `<totalSizeCap>` as-is for now.
