### ISSUE TITLE
Provide a configuration option to enable lazy initialisation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15870]
The bean factory that is used by default in a Spring Boot application performs eager initialisation of all singleton beans. There has been some interest in performing initialisation lazily so we want to provide a configuration option that will allow users to opt in to this behaviour. When enabled, beans will be initialised on first use. In a web application, this will mean that a large number of beans are initialised on first request rather than during the application's startup.

The main benefit of lazy initialisation is that initial startup time is reduced. However, this comes at a cost:

1. Handling of HTTP requests may take longer while any deferred initialisation occurs
2. Failures that would normally occur at startup will now not occur until later

**Comment by bishoybasily** [comment]
hi @wilkinsona , 
i'm just asking if something like this can do the job ?

``` java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Import(ProcessorConfiguration.class)
public @interface EnableLazyInitByDefault { }
```
``` java
public class ProcessorConfiguration {

    @Bean
    public FactoryProcessor factoryProcessor() {
        return new FactoryProcessor();
    }

}
```
``` java
public class FactoryProcessor implements BeanFactoryPostProcessor {

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        beanFactory.getBeanNamesIterator().forEachRemaining(s -> beanFactory.getBeanDefinition(s).setLazyInit(true));
    }
}
```
i know it's already assigned, i'm just validating my understanding!
thank you.

**Comment by wilkinsona** [comment]
Yeah, that's a large part of it. We're currently planning on enabling lazy init of all beans, not just those in a particular package space. There's also a bit of work to do to make things lazy in a WebFlux app. If you'd like to see what the code currently looks like, it is available in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-15870).

**Comment by wilkinsona** [comment]
This needs some reference documentation then we're happy for it to be merged.

**Comment by wilkinsona** [comment]
Reopening as DevTools restart does not work with lazy initialization enabled.

**Comment by tkvangorder** [comment]
Hi Andy, 

I am glad to see this in the official codebase.

Back when I had originally purposed the idea in the context of integration tests, 
we had run into some issues with the Spring Integration DSL:

https://github.com/spring-projects/spring-boot/issues/9685

Once we migrate to Boot 2.2, will we still have to exclude the flows or was there some other workaround?

Thanks!

**Comment by wilkinsona** [comment]
I'd forgotten about the problems that you encountered with the Spring Integration DSL. Sorry. I'm not aware of any changes in Spring Integration so the problem may still exist. Please give 2.2 M1 a try and let us know how you get on. There may be something that we can do to improve the situation, or we may be able to do something in conjunction with the Spring Integration team. If the problem you encountered still occurs, please open a new issue and we'll take a look.

**Comment by tkvangorder** [comment]
It might be a bit before we move to 2.2, we JUST finished moving to 2.1. If I get some time I will try to come up with a sample to test things out.
