### ISSUE TITLE
Fix broken Appendix links due to section overhaul

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15884]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

The documentation has been restructured on `master` so that it is splits differently with one file per major section rather than a collection of individual files. For instance, rather than rendering each appendix in a dedicated file, all appendixes are now rendered in a single [appendix.html](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/appendix.html).

## Problem

There are several places in the documentation where we are still referring to dedicated files rather than the new "major section file" and those links are therefore broken.

## Solution

First of all, make sure to generate [the documentation locally](https://github.com/spring-projects/spring-boot/blob/master/README.adoc#building-reference-documentation) so that you can check your changes are properly applied. Once you've performed the initialization step to build the maven plugin documentation and the starters, only the last step is required to generate the documentation again with your changes.

The sources for the documentation are located in `spring-boot-project/spring-boot-docs/src/main/asciidoc`. Checking for `appendix-` is an effective way to spot the places where links are still referring to the old format.

Consider the following broken link: `<<appendix-executable-jar-format.adoc#executable-jar, Executable Jars>>`. The first part of the link must be `appendix.adoc` and the anchor probably didn't change but it's worth double checking anyway. In this case it is still valid so the new link should be `<<appendix.adoc#executable-jar, Executable Jars>>`.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [x] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by govi20** [comment]
would love to work on it.

**Comment by snicoll** [comment]
Great! Thank you. Please let us know if you have any questions.

**Comment by govi20** [comment]
I am able to generate the documentation using the maven command.

do we have any old doc patterns which I should look for or I should search every link manually?

**Comment by snicoll** [comment]
> do we have any old doc patterns which I should look for or I should search every link manually?

I mentioned in the description the pattern to use.

> Checking for `appendix-` is an effective way to spot the places where links are still referring to the old format.

Let me know if something isn't clear.

**Comment by govi20** [comment]
I have fixed broken links. But would need your help to clean up the history. Pull request is including old commits also, Here's link https://github.com/spring-projects/spring-boot/compare/master...govi20:master

**Comment by snicoll** [comment]
Feel free to submit the PR and we can figure it out from there. Thanks!

**Comment by govi20** [comment]
#15933

**Comment by snicoll** [comment]
Closing in favour of PR #15933
