### ISSUE TITLE
Exclude guava from the activemq-broker in the spring-boot-starter-activemq

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#15895]
I've just noticed that the activemq-broker has a compile time dependency on guava. Doing quick [search](https://github.com/apache/activemq/search?q=guava&unscoped_q=guava) on GitHub shows that guava is not really used within ActiveMQ. Looking at the [pom.xml](https://github.com/apache/activemq/blob/1cf13c4742dcf65aa5c0b68e4bfcdb3da21dd935/activemq-broker/pom.xml#L86-L90) from the activemq-broker it seems that Guava is under the testing dependency section.

Is it even an option the Spring Boot to team to automatically exclude the guava from activemq-broker in the spring-boot-starter-activemq. I have also raised [AMQ-7151](https://jira.apache.org/jira/browse/AMQ-7151) for the ActiveMQ team in order to clear out the reasoning of them having Guava.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The cost of excluding a dependency is quite high. Every time we upgrade, we need to remember to check that the exclude is still needed and that it doesn't break anything. As such, it's better if this sort of problem is fixed at source. I'm going to close this one for now. We can re-open it in the unlikely event of the ActiveMQ indicating that Guava is not needed and also not updating their own pom.

**Comment by filiphr** [comment]
Fair enough. Thanks for the detailed explanation.
