### ISSUE TITLE
Expose Tomcat AccessLogValve.maxDays as an Application Property

### ISSUE THREAD

**Issue by shqie** [spring-projects/spring-boot#15897]
It would be useful to expose the AccessLog `maxDays` as an application property:
https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/AccessLogValve.html#setMaxDays(int)
[github link](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/valves/AccessLogValve.java#L163)

and set it to the `TomcatWebServerFactoryCustomizer` and/or others:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/TomcatWebServerFactoryCustomizer.java#L255

Maybe:
`server.tomcat.accesslog.max-days=
`
Being able to set this as part of the application could make sure that the access logs are removed after certain days. This could be one way to solve an issue where the number of files (size of logs) grows indefinitely. 
There does not appear to be access log rotation based on the size, which would solve the above issue. 
However, this way it is one measure to not keep too many files.

**Comment by shqie** [comment]
The workarounds at this time:
Create a Customizer class that implements `WebServerFactoryCustomizer` . Get the access log engine valve and set the max days.

1.
```

@Component
public class TomcatWebServerAccessLogCustomizer
    implements WebServerFactoryCustomizer<TomcatServletWebServerFactory> {

  @Value("${server.tomcat.accesslog.max-days}")
  int accessLogMaxDays;

  @Override
  public void customize(TomcatServletWebServerFactory factory) {

  Collection<Valve> engineValves = factory.getEngineValves();
    for (Valve tempObject : engineValves) {
      if (tempObject instanceof AccessLogValve) {
        AccessLogValve accessLogValve = (AccessLogValve) tempObject;
        accessLogValve.setMaxDays(accessLogMaxDays);
      }

    }
  }
}

```
2.  Same as above, but here create the `AccessLogValve`, set everything, and add it as an engine valve to the factory.
disable access log rotation in properties :
`server.tomcat.accesslog.enabled=false
`

```
@Component
public class TomcatWebServerAccessLogCustomizer
    implements WebServerFactoryCustomizer<TomcatServletWebServerFactory> {

  @Value("${server.tomcat.accesslog.max-days}")
  int accessLogMaxDays;

  @Autowired
  ServerProperties serverProperties;

  @Override
  public void customize(TomcatServletWebServerFactory factory) {

        ServerProperties.Tomcat tomcatProperties = serverProperties.getTomcat();

    AccessLogValve valve = new AccessLogValve();
    valve.setPattern(tomcatProperties.getAccesslog().getPattern());
    valve.setDirectory(tomcatProperties.getAccesslog().getDirectory());
    valve.setPrefix(tomcatProperties.getAccesslog().getPrefix());
    valve.setSuffix(tomcatProperties.getAccesslog().getSuffix());
    valve.setRenameOnRotate(tomcatProperties.getAccesslog().isRenameOnRotate());
    valve.setFileDateFormat(tomcatProperties.getAccesslog().getFileDateFormat());
    valve.setRequestAttributesEnabled(
        tomcatProperties.getAccesslog().isRequestAttributesEnabled());
    valve.setRotatable(tomcatProperties.getAccesslog().isRotate());
    valve.setBuffered(tomcatProperties.getAccesslog().isBuffered());
    
    valve.setMaxDays(accessLogMaxDays);

    factory.addEngineValves(valve);
  }

```

**Comment by snicoll** [comment]
Closing in favour of PR #15954
