### ISSUE TITLE
https://repo.spring.io/ is down

### ISSUE THREAD

**Issue by edrevo** [spring-projects/spring-boot#15899]
The spring repo is timing out on any HTTP requests. Can't download any dependencies 😢

**Comment by wilkinsona** [comment]
Thanks for letting us know, but there's nothing that the Spring Boot project can do to fix that. Our ops team is already aware: https://twitter.com/springops/status/1095250181467979777.

**Comment by BertCC** [comment]
Looks like repo is down again today 3/12/2019
