### ISSUE TITLE
EmbeddedLdapAutoConfiguration Address already in use

### ISSUE THREAD

**Issue by cproinger** [spring-projects/spring-boot#15931]
The InMemoryDirectoryServer-Bean defined in 

https://github.com/spring-projects/spring-boot/blob/81e6a5a4d9b0c4749eb653782d2d1530958035cd/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/ldap/embedded/EmbeddedLdapAutoConfiguration.java#L114

should define a destroy-method (maybe with a wrapper or something) because otherwise the issue can arise in integration-tests where there are different configurations used that spring would invoke this method twice and thereby running into an issue with the currently used port because the old server is not shut down properly

**Comment by wilkinsona** [comment]
The server is already shutdown when the context is closed:

https://github.com/spring-projects/spring-boot/blob/81e6a5a4d9b0c4749eb653782d2d1530958035cd/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/ldap/embedded/EmbeddedLdapAutoConfiguration.java#L199-L204

If you are using the test framework and contexts are being cached (the default behaviour), you will need to ensure that each new context that uses the embedded LDAP server is configured to use a different port. The easiest way to do that is to use a random port for each server. Alternatively, you could disable caching of the context by using `@DirtiesContext`.

As far as I can tell from the information provided, everything is working as expected here. If, having read the above, you do not agree please explain why and we can re-open this issue and take another look.
