### ISSUE TITLE
spring boot admin can not update from consul

### ISSUE THREAD

**Issue by gxl191911** [spring-projects/spring-boot#15934]
spring boot admin use consul discovery,but admin can not update from consul with a new service.
It only can diacovery already registed service.
Could you give me some solutions?

**Comment by snicoll** [comment]
Spring Boot Admin is a Codecentric project that is not handled here. I don't know about their policies but please review it before contributing. Ours states that [we prefer to use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues).
