### ISSUE TITLE
Consider switching from FileSize to DataSize for logback size-based properties

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15930]
Follow-up of #15325

Our `logging.file` namespace has two properties that use `FileSize` behind the scenes. That object is very similar to our new `DataSize` support so it would be nice to expose `DataSize` based properties for consistency.

Unfortunately, [the format is not 100% the same](https://github.com/qos-ch/logback/blob/4dd08e68321548cd85251ec389f5a832505e1268/logback-core/src/main/java/ch/qos/logback/core/util/FileSize.java#L23-L27) so we could keep binding to `String` and do some magic in the code? Or simply move to `DataSize`.

**Comment by nosan** [comment]
@snicoll,
I'm ready to start working on this issue, but, I have a few questions:
- Should I change the type of these properties? (`String` -> `DataSize`)
- Should I add support for both formats? 

Thanks in advance

**Comment by snicoll** [comment]
The purpose is to support `DataSize` and pass a long bytes to Logback wherever we can. I can't tell you as I haven't investigated yet.

>Unfortunately, [the format is not 100% the same](https://github.com/qos-ch/logback/blob/4dd08e68321548cd85251ec389f5a832505e1268/logback-core/src/main/java/ch/qos/logback/core/util/FileSize.java#L23-L27) so we could keep binding to `String` and do some magic in the code? Or simply move to `DataSize`.

The preference is to only care about `DataSize` but we should investigate first what happens if we use the old (String) format with it
