### ISSUE TITLE
fix(webclient): allow to run webclient with Schedulers.immediate()

### ISSUE THREAD

**Issue by davinkevin** [spring-projects/spring-boot#15959]
Hi, 

I've done a lot of search about this during the last months. I choose to open an issue because I think this is a bug (or not covered perimeter) from the WebClient point of view.

**tldr:**
I try to run the WebClient call with a different scheduler (mainly in `Schedulers.immediate()`) to be able to call block on it. It seems whatever the `Scheduler` is (in `subscribeOn` or `publishOn`)  the call is executed in the `reactor-http-nio-X` thread. 

I'm working on an application which exposes rest endpoints ( based on `spring-webflux`) and, for some call to those endpoints will launch some `spring-batch` job. 

The problem is the `Spring-Batch` system doesn't support for now `Reactor` types, so I have to use the `.block()` operator inside my `Processor`. The problem is the call to this trigger an exception [from this code](https://github.com/reactor/reactor-core/blob/f32944fdd10dfc4dc97fd21453b626d77b2856d9/reactor-core/src/main/java/reactor/core/publisher/BlockingSingleSubscriber.java#L111). 

I've tried to run the job inside a specific JobLauncher:
```
    @Bean
    @Primary
    fun launcher(j: JobRepository) = SimpleJobLauncher().apply {
        setJobRepository(j)
        setTaskExecutor(SimpleAsyncTaskExecutor())
    }
```

The problem here is the behavior of another spring component (Spring Cloud Sleuth used by Spring-Cloud-GCP) which doesn't propagate `X-B3` headers when call from inside this different thread

Thanks for your help

**Comment by wilkinsona** [comment]
> It seems whatever the `Scheduler` is (in `subscribeOn` or `publishOn`) the call is executed in the `reactor-http-nio-X` thread.

[`Schedulers.immediate`](https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#immediate--) is documented as using the caller’s thread so the behaviour you have described is to be expected.

> The problem here is the behavior of another spring component (Spring Cloud Sleuth used by Spring-Cloud-GCP) which doesn't propagate `X-B3` headers when call from inside this different thread

Spring Cloud Sleuth is managed as a [separate project](https://github.com/spring-cloud/spring-cloud-sleuth). In the first instance, I would recommend raising this with the Spring Cloud community on [Gitter](https://gitter.im/spring-cloud/spring-cloud).

**Comment by davinkevin** [comment]
Thanks for your time @wilkinsona. I will reach the `spring-cloud` project.

BTW, I have tried something yesterday, and find this: 

```
    @Test
    fun `should do the job with webClient`() {
        /* Given */
        println("The name of the main thread is ${Thread.currentThread().name}")
        /* When */
        val block = wc.get()
                .uri("/actuator/health")
                .retrieve()
                .bodyToMono<String>()
                .subscribeOn(Schedulers.immediate())
                .publishOn(Schedulers.immediate())
                .doOnNext { println("The name of the thread inside `OnNext` is ${Thread.currentThread().name}")}
                .block()

        /* Then */
        assertThat(block).isNotNull()
    }
```

This produces the following output:
```log
The name of the main thread is main
The name of the thread inside `OnNext` is reactor-http-nio-4
```

And the same thing, but with a simple `Mono`: 
```
    @Test
    fun `should do the job with mono`() {
        /* Given */
        println("The name of the main thread is ${Thread.currentThread().name}")
        /* When */
        val block = Mono.just("1")
                .subscribeOn(Schedulers.immediate())
                .publishOn(Schedulers.immediate())
                .doOnNext { println("The name of the thread inside `OnNext` is ${Thread.currentThread().name}")}
                .block()

        /* Then */
        assertThat(block).isNotNull()
    }
```

Will produces the following output:
```
The name of the main thread is main
The name of the thread inside `OnNext` is main
```

From my point of view / knowledge, it does not seem coherent, but I should miss something...

**Comment by wilkinsona** [comment]
If you’d like some help with Reactor, they have a Gitter channel too.

With that said, the behaviour you have observed is what I would expect. In each case you are building a pipeline. When you use the immediate scheduler you are saying that the next step in the pipeline should be executed on the same thread as the previous step.

When you use `WebClient` to make a request and retrieve a response, the response is received on a Reactor Netty thread. In the absence of something causing it to switch to a different thread, each subsequent step then uses that same thread. Processing only returns to the main thread due to your use of `block()` to get the result.

In your simpler test that does not use `WebClient`, none of the steps in the pipeline cause a different thread to be used so all of the processing is performed on the main thread.
