### ISSUE TITLE
Enable build scan generation on CI

### ISSUE THREAD

**Issue by aalmiray** [spring-projects/spring-boot#15966]
Would the team be interested in enabling build scans when running on CI?

I noticed that the project has a gitter channel, perhaps you'd be interested in letting members know when a scan is ready, as it's shown at http://andresalmiray.com/hooking-gradle-build-scans-notifications-to-gitter/

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but Spring Boot is built with Maven. As with the dependency management plugin, I'm also not keen on tying our build to any external services unless absolutely necessary. Furthermore, Concourse already gives us the ability to hook into Slack or Gitter or pretty much anything else upon build completion should we wish to do so.

**Comment by aalmiray** [comment]
As I understand it, build scans for Maven will become available to the general public soon.
