### ISSUE TITLE
org.springframework.boot.loader.jar.Handler rootFileCache can not be refreshed 

### ISSUE THREAD

**Issue by guoao** [spring-projects/spring-boot#15964]
This class use a softReference to cache the file but never clean the cache. If the content of the file has been changed but the file name remains the same，we will get a wrong jar file instance next time,

```
private JarFile getRootJarFile(String name) throws IOException {
	try {
		if (!name.startsWith(FILE_PROTOCOL)) {
			throw new IllegalStateException("Not a file URL");
		}
		String path = name.substring(FILE_PROTOCOL.length());
		File file = new File(URLDecoder.decode(path, "UTF-8"));
		Map<File, JarFile> cache = rootFileCache.get();
		JarFile result = (cache == null ? null : cache.get(file));
		if (result == null) {
			result = new JarFile(file);
			addToRootFileCache(file, result);
		}
		return result;
	}
	catch (Exception ex) {
		throw new IOException("Unable to open root Jar file '" + name + "'", ex);
	}
}
```

**Comment by wilkinsona** [comment]
> If the content of the file has been changed but the file name remains the same

A fat jar and its contents are expected not to change during the lifetime of an application.

Perhaps you can take a step back and describe what you're trying to do and the problem that you're experiencing?

**Comment by guoao** [comment]
### Backgroup
Our code are written in different jar for business isolation . The jar was run as a single container(using a specific classloader), so that we can hot deploy the jar without restarting the application. We deploy our modified code by replace the jar and refresh the spring context.

### code
To refresh spring context, we need get a xml file from a jar file, and we use PathMatchingResourcePatternResolver to match the location pattern, the code is like this:
```
PathMatchingResourcePatternResolver.getResources("spring/spring-*.xml")
```
### problem
Because the jar file name are the same ,but the file content has been changed. Next time I replace the jar file ,an error occured:
```
java.lang.IllegalArgumentException: invalid compression method
        at java.util.zip.ZipEntry.setMethod(ZipEntry.java:409)
```

**Comment by wilkinsona** [comment]
Thanks. As I suspected, what you are attempting isn't supported by Boot's fat jars and `jar:` URL handler. While we could update the `Handler` to invalidate an entry in the case by, for example, comparing the last-modified time of the entry in the cache and the file, I suspect that would fall some way short of a solution that worked in all cases.

My feeling is that this isn't something that we should try to support. I'll flag it for team attention to see what everyone else thinks.

**Comment by guoao** [comment]
Thanks a lot. Just let me know whether you are trying to support it.

**Comment by wilkinsona** [comment]
We discussed this today and we do not want to add the extra complexity to the fat jar support to support dynamically reloading them.
