### ISSUE TITLE
Order TaskExecutionAutoConfiguration before TaskSchedulerAutoConfiguration

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#15963]
In Spring Boot 2.1.2, if ThreadPoolTaskExecutor and ThreadPoolTaskScheduler exist, 
the two instance beans will be automatically configured, but both classes implement java.util.concurrent.Executor. 
After testing, ThreadPoolTaskExecutor takes precedence over  ThreadPoolTaskScheduler instantiation, there is no problem. but these two kinds of instantiation do not specify priority, If ThreadPoolTaskScheduler first instantiates will cause ThreadPoolTaskExecutor to fail to instantiate because the existence of 
java.util.concurrent.Executor implementation classes is checked before ThreadPoolTaskExecutor instantiation.
![image](https://user-images.githubusercontent.com/13413715/52845421-0d2a7680-3142-11e9-987c-b895fd21994a.png)
![image](https://user-images.githubusercontent.com/13413715/52845447-1adffc00-3142-11e9-8229-d13d231ceee5.png)

**Comment by snicoll** [comment]
@brucelwl thanks but I am not sure I understand what problem you are trying to report (I am afraid screenshots of code are not very useful). Those  two beans cover different use cases. Rather than describing what happens, can we please take a step back and can you describe the actual problem you are facing?

**Comment by brucelwl** [comment]
@snicoll Thank you for your reply. I want to confirm whether ThreadpoolTaskScheduler may have been injected as a bean before ThreadpoolTaskExecutor.

**Comment by snicoll** [comment]
Superseded by a first timers issue that was easier to write in a dedicated issue, see #15983
