### ISSUE TITLE
Trim trailing whitespace from value of spring.server.servlet.context-path

### ISSUE THREAD

**Issue by sattamshobaki** [spring-projects/spring-boot#15972]
Hello,
I encountered issue for spring boot application that all resources are not working
it's giving me 404 always
after that i found the issue because there was space in context-path value in the application.properties

So it's better to trim the context patch before applying it

**Comment by wilkinsona** [comment]
Thanks for the suggestion. There's a tiny (but non-zero) chance that trimming may break someone's application. As such, I don't think we should start trimming the context path in a maintenance release, but could do so in 2.2 with an appropriate entry in the release notes.

**Comment by mrifni** [comment]
Hi, I would like to pick this up and start contributing to spring boot. Please let me know....

**Comment by wilkinsona** [comment]
Great! Thank you, @mrifni. A pull request that trims the whitespace and checks that it has been trimmed would be most welcome.

**Comment by mrifni** [comment]
sure, doing now..

**Comment by mrifni** [comment]
@wilkinsona Please find the fix [here](https://github.com/spring-projects/spring-boot/pull/16165).

Happy to contribute.

**Comment by wilkinsona** [comment]
Thank you. I'll close this in favour of your PR.
