### ISSUE TITLE
additional tomcat connectors does not support compression

### ISSUE THREAD

**Issue by UncleTom** [spring-projects/spring-boot#15974]
In default TomcatServletWebServerFactory class, it just supports the data compression on the default Connector, but all other additionalTomcatConnectors are not support compression.

see the code in the getWebServer method:
```
Connector connector = new Connector(this.protocol);
tomcat.getService().addConnector(connector);
this.customizeConnector(connector);
```

Requires consistent behavior for all connectors.

**Comment by wilkinsona** [comment]
This is by design. It gives you complete control over the connector that you add. While you may want compression to be enabled for all connectors, others may not. The same applies to SSL and the like. If you want your additional connector to use compression you should configure it to do so.

**Comment by UncleTom** [comment]
ok, we can copy **CompressionConnectorCustomizer** class's code and create a new class to implement our functionality.
