### ISSUE TITLE
CLI Support for version upgrade

### ISSUE THREAD

**Issue by DreamPWJ** [spring-projects/spring-boot#15971]
-In front-end presents cli can support the main version of the automatic update such as ng update @ presents/cli @ presents/core more updates for the cli， to do such destructive to reduce a lot of work to， upgrade the version spring boot 1. x Upgrade 2.x may need a few days， but if you develop a cli to automatically upgrade may only take a few minutes to upgrade， the new users more convenient this way let more people to use the new also to reduce the maintenance of the old version，We like spring boot very much and hope spring boot will get better and better thanks。

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we do not plan to make any enhancements to Spring Boot’s CLI at this time. When upgrading, I would recommend using our [migration guide](
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) to help you instead. If there are parts of an upgrade that you have found difficult then please let us know and we will improve the guide if we can. There are also other tools in the ecosystem, such as the Versions plugins for Maven and Gradle, that may be of interest.
