### ISSUE TITLE
Error creating bean with name 'requestMappingHandlerMapping' while using Spring Boot 2 with PCF SSO dependencies

### ISSUE THREAD

**Issue by dpolianskyi-ua** [spring-projects/spring-boot#15985]
Hi everyone.

I have a problem during using Spring Boot 2 and building security from perspective of PCF SSO.

Error looks like:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
> 	at com.epam.addressbook.registration.RegistrationApplication.main(RegistrationApplication.java:29) [classes/:na]
> Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
> 	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_191]
> 	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_191]
> 	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[na:1.8.0_191]
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[na:1.8.0_191]
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_191]
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_191]
> 	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_191]
> 	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_191]
> 	at java.lang.Class.createAnnotationData(Class.java:3526) ~[na:1.8.0_191]
> 	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_191]
> 	at java.lang.Class.getAnnotation(Class.java:3415) ~[na:1.8.0_191]
> 	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258) ~[na:1.8.0_191]
> 	at java.lang.Class.isAnnotationPresent(Class.java:3425) ~[na:1.8.0_191]
> 	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:570) ~[spring-core-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:177) ~[spring-webmvc-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:218) ~[spring-webmvc-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:189) ~[spring-webmvc-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:136) ~[spring-webmvc-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	... 16 common frames omitted
> 
> 
> Process finished with exit code 1

**Let me provide some brief**

I'm building a **_microservice_**-like applications, which contains (**_~/applications/... , ~/components/..._**):

- 1 accommodation server and its component (this server is **GREEN**)
- 1 leasing server and its component (this server is **GREEN**)
- 1 history server and its component (this server is **GREEN**)
- 1 registration server and its components - account, housing, person (this server is **RED** and produces error above)

All servers are bounded to Eureka Server as Eureka clients and using OAuth2 Server to get a token. (**_~/platform/..._**)

For simplifying behavior from OAuth2 perspective, I've used next configuration for my servers (server.gradle):

`
...

bootRun.environment([
        "APPLICATION_OAUTH_ENABLED": false,
        "SECURITY_OAUTH2_CLIENT_CLIENT_ID": "address-book",
        "SECURITY_OAUTH2_CLIENT_CLIENT_SECRET": "abpassword",
        "SECURITY_USER_NAME": "actuator",
        "SECURITY_USER_PASSWORD": "actpass"
])`

When I'm running registration server separately (without OAuth2 and Eureka servers) and passing all environment variable above - _**I've been facing with exception logs at the head of the topic**_

My **_codebase_** is available here: https://github.com/dpolianskyi-ua/abex

Thanks.

**Comment by snicoll** [comment]
You are managing versions yourself in this project and you have incompatible versions on the classpath that leads to this exception. We've shared some tips to debug this problem on your end in https://github.com/spring-projects/spring-boot/issues/11214#issuecomment-348455967.

In the future, please ask questions on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by wilkinsona** [comment]
I don't think this is quite as simple as having incompatible versions on the classpath.

The problem is your `spring-cloud-sso-connector` dependency. It is pulling in a 1.x version of `spring-cloud-security` that is compatible with Spring Boot 1.x but you're using Spring Boot 2.x:

```
+--- io.pivotal.spring.cloud:spring-cloud-sso-connector:2.1.3.RELEASE
|    +--- org.springframework.cloud:spring-cloud-starter-oauth2:1.2.0.RELEASE
|    |    +--- org.springframework.cloud:spring-cloud-starter-security:1.2.0.RELEASE
|    |    |    +--- org.springframework.cloud:spring-cloud-starter:1.2.0.RELEASE -> 2.0.0.RELEASE (*)
|    |    |    +--- org.springframework.boot:spring-boot-starter-actuator:1.5.2.RELEASE -> 2.0.8.RELEASE (*)
|    |    |    \--- org.springframework.cloud:spring-cloud-security:1.2.0.RELEASE
```

`spring-cloud-security` depends on the OAuth auto-configuration from Spring Boot 1.x. that was removed in 2.x. It's now available as a separate project to ease migrations such as this. If you add the following dependency to your registration server it should start up successfully:

```
runtime 'org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.2.RELEASE'
```

[dpolianskyi-ua](/dpolianskyi-ua), please open an issue against the [Spring Cloud SSO Connector project](https://github.com/pivotal-cf/spring-cloud-sso-connector). Ideally, there would be a release of that project that is compatible with Spring Boot 2.x out of the box. Failing that it would be good if they could document how to use the project with Spring Boot 2 and Spring Cloud Finchley and later.

**Comment by dpolianskyi** [comment]
@snicoll @wilkinsona guys, thanks for rapid response. I'll prepare further description for Spring Cloud SSO Connector project and ping them.
