### ISSUE TITLE
Add Spring-specific styling to the Gradle Plugin's documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15990]
The Gradle Plugin's documentation is using the default Asciidoctor styling. We should update it to use the Spring-specific styling that the reference documentation is now using.

**Comment by DontSeeSharp** [comment]
I'll look into this.

**Comment by DontSeeSharp** [comment]
@wilkinsona I have some questions:

1) It seems that the `switch--item`, `switch--item selected` and `switch` CSS classes need a change in spring-doc-resources. I couldn't find the `spring.css` file in the spring-doc-resources github page. Where is the proper place I can create an issue for this?  

2) Documentation is also generated to pdf right now for Spring Gradle Plugin Documentation. Is that needed? (It's not there for reference documentation)

3) Should I wait with the PR for this until CSS classes get fixed and released?
  
For future reference:
I suggest replacing `#7a2519` with `#6BB344` in following CSS classes:
```
.switch--item.selected {
    background-color: #6BB344;
    color: #ffffff;
}
```
and
```
.switch--item {
    padding: 10px;
    background-color: #ffffff;
    color: #6BB344;
    display: inline-block;
    cursor: pointer;
}
```
and
```
.switch {
    border-width: 1px 1px 0 1px;
    border-style: solid;
    border-color: #6BB344;
    display: inline-block;
}
```
![image](https://user-images.githubusercontent.com/16798824/54772778-69ccf580-4c08-11e9-9f29-e2e1be1d3903.png)
## -->
![image](https://user-images.githubusercontent.com/16798824/54772858-94b74980-4c08-11e9-9f9d-d5757a7fafd6.png)

**Comment by wilkinsona** [comment]
@DontSeeSharp Thanks for your work on this. 

1. We can avoid changing that file. See 3.
2. Let’s keep the PDF, unchanged, please.
3. We can use the same approach as I used in the dependency management plugin’s documentation by adding CSS [like this](
https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/b95614c66bd56b273bbba1568ef82c7faa2524ab#diff-1690f4c22a8c81c44bbe1fcf3ce9922a) to this project.

**Comment by mbhave** [comment]
Closing in favor of PR #16327.
