### ISSUE TITLE
Remove code deprecated in 2.1

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#15996]
There are a number of things we deprecated in 2.1 (or in 2.0 that we didn't remove in 2.1 for some reason) so we should deal with them, ideally in the first milestone so that the change are available as soon as possible.

This includes:

* `RestTemplateBuilder#basicAuthorization`
* `RestTemplateBuilder#setConnectionTimeout` (int)
* `RestTemplateBuilder#setReadTimeout` (int)
* `AbstractFilterRegistrationBean#REQUEST_WRAPPER_FILTER_MAX_ORDER`
* `FilterRegistrationBean#REQUEST_WRAPPER_FILTER_MAX_ORDER`
* `MultipartConfigFactory` (bytes-based setters)
* `PathMapper#useEndpointId()`
* `CompositeHealthIndicator` constructor without a registry and `addHealthIndicator`
* `CompositeHealthIndicatorFactory`
* `CompositeReactiveHealthIndicator` constructors without a registry and `addHealthIndicator`
* `MetricsWebFilter` constructor without `autoTimeRequests` (Since 2.0.6)
* `WebMvcMetricsFilter` constructor that takes the context (Since 2.0.7)
* `DiskSpaceHealthIndicator` that takes a long instead of `DataSize`
* `JobLauncherCommandLineRunner` constructor without a `JobRepository` (Since 2.0.7)
* `DispatcherServletPathProvider` (since 2.0.4)

I don't see a particular problem with those. We have also a few properties that should be removed.

These two probably require us to figure out if they should be included in this round.

* `AutoConfigureMockMvc#secure`
* `WebMvcTest#secure`

**Comment by mbhave** [comment]
There is a [separate issue](https://github.com/spring-projects/spring-boot/issues/13822) for the `secure` flags in `2.2.x`. The change is a bit more involved than just removing the flags so we can do this as part of the other issue.

**Comment by mbhave** [comment]
Closing in favor of PR #16013.
