### ISSUE TITLE
Upgrade to Jetty 9.4.15.v20190215

### ISSUE THREAD

**Issue by GFriedrich** [spring-projects/spring-boot#15992]
@snicoll: When stumbling upon the Jedis upgrade ticket, I also found that you could update the Jetty version.
So, please upgrade Jetty for Spring Boot ```1.5.x```, ```2.0.x``` and ```2.1.x``` to ```9.4.15.v20190215``` - e.g. see http://central.maven.org/maven2/org/eclipse/jetty/jetty-servlets/9.4.15.v20190215/
Thanks in advance!

**Comment by wilkinsona** [comment]
Thanks for raising this issue, but as described in the template that you were shown when you opened it, we don't need one for an upgrade like this:

> You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release. BUT pull requests for upgrades that are more involved than just a version property change are still most welcome.

We'll take care of the upgrade in due course.

**Comment by GFriedrich** [comment]
Mea culpa - as said: just saw the ticket of Jedis created by @snicoll and thought it would be good to have this updated too with the next 1.5.x release which is quite near and missed to read the complete template. :)
