### ISSUE TITLE
Add Spring-specific styling to the Actuator's API documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#15991]
The Actuator's API documentation is using the default Asciidoctor styling. We should update it to use the Spring-specific styling that the reference documentation is now using.

**Comment by simionAndrei** [comment]
@wilkinsona I would like to contribute in solving this issue, but I have a question about it. Where in the project structure can I find the Actuator API adoc files, since in spring-boot-project/spring-boot-actuator or in spring-boot-docs I wasn't able to identify it.  If this issue is not suitable for contribution, could you please guide me to another one?

**Comment by wilkinsona** [comment]
Thanks for the offer.

The Actuator's API documentation can be found [here](https://github.com/spring-projects/spring-boot/tree/2bd3d19bee6f504b1a7e0742f6703908fa751784/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/asciidoc). This issue might be a little bit tricky for a first-time contribution, but if you're interested in having a go, the end result of [this commit](https://github.com/spring-projects/spring-boot/commit/ed3347f00da189346097faf4f948dca4b8c3f634#diff-f9e0e8080feb048de01369aec4cc234d) may help you figure out what's needed.

If you decide not to tackle this one, please let us know. You may want to look at an issue that's [labelled as ideal for contribution](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) or keep an eye out for one that's specifically intended [for first-timers only](https://github.com/spring-projects/spring-boot/labels/status%3A%20first-timers-only).

**Comment by DontSeeSharp** [comment]
I'll look into this, since this should be similar to #15990.

**Comment by mbhave** [comment]
Closing in favor of PR #16326.
