### ISSUE TITLE
Repackage META-INF/<module-name>.kotlin_module files into BOOT-INF/classes

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-boot#16003]
Issue #15890 was addressed to to repackage META-INF/<module-name>.kotlin-module (with a dash), but the the suffix is supposed to be .kotlin_module with an underscore instead of a dash. The dash instead of the underscore was my bad from when I reported the issue. I apologize for the confusion.

Running `jar tf` against a kotlin project reveals that the correct suffix is kotlin_module.

**Comment by wilkinsona** [comment]
Gah, thanks for spotting this @thorntonrp and sorry that I didn't spot it when I implemented the fix. I'll close this one in favour of your PR.
