### ISSUE TITLE
Extend ApplicationContextRunner to accept simple bean definitions

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#16011]
Inspired by `ProjectTester` in Spring Initializr, I'd like us to extend `ApplicationContextRunner` to allow registering beans in addition to `Configurations`.

Lots of tests are declaring a test `@Configuration` class with one or two bean definitions to export additional beans in the context to test. This requires quite a lot of code in the end and a muscle memory to remember what the inner class at the end of the test does.

Consider this:

```java
@Test
public void cacheManagerBackOff() {
	this.contextRunner.withUserConfiguration(CustomCacheManagerConfiguration.class)
			.run((context) -> assertThat(
					getCacheManager(context, ConcurrentMapCacheManager.class)
							.getCacheNames()).containsOnly("custom1"));
}
```

To be replaced with this proposal by

```java
@Test
public void cacheManagerBackOff() {
	this.contextRunner
			.withBean(CacheManager.class,
					() -> new ConcurrentMapCacheManager("custom1"))
			.run((context) -> assertThat(
					getCacheManager(context, ConcurrentMapCacheManager.class)
							.getCacheNames()).containsOnly("custom1"));
}
```

**Comment by wilkinsona** [comment]
I like that a lot, particularly as it helps to make the test more self-contained.

**Comment by snicoll** [comment]
Considering calling that `withUserBean` to make it crystal clear it's not related with auto-configuration at all?

**Comment by wilkinsona** [comment]
I think `withBean` is fine. Unlike with configuration, can’t see a need to offer a way to add user beans and auto-configured beans. I prefer the more concise name and the javadoc should be able to remove any ambiguity about what it does.

**Comment by snicoll** [comment]
Unfortunately it is not that easy as the method to register beans that way is part of `GenericApplicationContext` and some of the contexts we use are not inheriting from that base class.

**Comment by snicoll** [comment]
This issue is blocked by #16096

**Comment by snicoll** [comment]
The feature is now available at a different level in framework so we should be able to use it without requiring to change the hierarchy. I guess it's probably going to be easier if we fix #16096 first though

**Comment by philwebb** [comment]
I think we might have an ordering issue with functional registration, but I'm not 100% sure. The current setup uses `Configurations` to apply ordering. With functional registrations we're using an `initializer` that gets applied after the configuration classes. I think ideally we'd want to register the functional beans after user defined configuration, but before auto-configuration.

**Comment by philwebb** [comment]
Actually the ordering looks fine. I'll push a commit to align the signatures as much as possible with the ones in `ApplicationContext`. For now, I think we can drop the overloaded `Function` version (the `Supplier` seems more useful). If it turns out we need it later we can add it in again.
