### ISSUE TITLE
custom security config with @EnableWebSecurity exposes sensitive Actuator endpoints

### ISSUE THREAD

**Issue by fabianbuch** [spring-projects/spring-boot#1602]
Adding Spring Boot to a legacy app, Boot correctly excludes auto-configuration for already configured things. In the case of where the actuator dependency is 'accidentally' added, it might be a bad idea to expose all endpoints without a big warning (either in logs or documentation) or apply a security config anyway that denies all requests to actuator endpoints by defaults until the custom security config makes them available.

**Comment by mbhave** [comment]
See #6889. Spring Boot 1.5 and later versions require that the user should have the required role to be able to access actuator endpoints by default.
