### ISSUE TITLE
Spring Security events are being published twice in Spring Boot > 1.1.4

### ISSUE THREAD

**Issue by tmendenhall** [spring-projects/spring-boot#1603]
I am using a SecurityConfiguration class that extends WebSecurityConfigurerAdapter with the annotations @Configuration and @EnableWebSecurity.

When I override the configure(AuthenticationManagerBuilder auth) method to configure all of my providers they are added as the parent AuthenticationManager to the http configuration. Since there are no authenticationManagers configured in the protected void configure(HttpSecurity http) method the provider chain is empty.

In the ProviderManager class the parent manager is allowed to do the authentication.

      if (result == null && parent != null) {
            // Allow the parent to try.
            try {
                result = parent.authenticate(authentication);
            } catch (ProviderNotFoundException e) {
                // ignore as we will throw below if no other exception occurred prior to calling parent and the parent
                // may throw ProviderNotFound even though a provider in the child already handled the request
            } catch (AuthenticationException e) {
                lastException = e;
            }
        }
So the parent returns the correct result and publishes the event.

        if (result != null) {
            if (eraseCredentialsAfterAuthentication && (result instanceof CredentialsContainer)) {
                // Authentication is complete. Remove credentials and other secret data from authentication
                ((CredentialsContainer)result).eraseCredentials();
            }

            eventPublisher.publishAuthenticationSuccess(result);
            return result;
        }

and then when you return from the stack the other resolver also publishes the event.

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.
