### ISSUE TITLE
The recent upgrade to Httpclient 4.5.7 broke URLs with encoded forward slashes (%2F).

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#16043]
This upgrade breaks any apps using a URL with an encoded `/`.

This is the most common virtual host for RabbitMQ.

`http://localhost:15672/api/queues/%2F/foo` becomes `GET /api/queues/foo HTTP/1.1`

The issue is [fixed in 4.5.8](https://issues.apache.org/jira/browse/HTTPCLIENT-1968) which is not yet released.

Consider dropping back to 4.5.6 until 4.5.8 is available.

**Comment by wilkinsona** [comment]
How did you become aware of the problem, @garyrussell?

4.5.7 contains [10 changes, 5 of them major](https://issues.apache.org/jira/projects/HTTPCLIENT/versions/12343595). I’m not sure that we should drop back to 4.5.6 and cause people to miss out on those changes just to avoid this problem. It’s a tough call to make.

**Comment by garyrussell** [comment]
@wilkinsona I found it because some tests in `spring-cloud-stream-binder-kafka` started failing, where we use the RabbitMQ `http-client` (which uses `RestTemplate`) to check some provisioning activity.

I have worked around it by adding the 4.5.6 version (in test scope) to the rabbit binder, so I think it's ok to close this.

I just wanted to bring it to your attention.

**Comment by wilkinsona** [comment]
We discussed this today, and we want to stay on the latest maintenance release of the client. It may be worth lobbying the HTTP Client team for a 4.5.8 release if it causes problems when working with Rabbit. Thanks for bringing it to our attention.

**Comment by garyrussell** [comment]
Pinged them [here](https://issues.apache.org/jira/browse/HTTPCLIENT-1968?focusedCommentId=16788228&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16788228). Let's see if we get a reply in time for 2.1.4.

**Comment by krm1312** [comment]
Thanks.  Just spent 2 hours tracking this down w/ https://github.com/rabbitmq/hop.
