### ISSUE TITLE
NullPointerException with empty X-Forwarded-For header.

### ISSUE THREAD

**Issue by luiz290788** [spring-projects/spring-boot#16044]
spring-boot: 2.1.3
spring-boot-actuator: 2.1.3

A NullPointerException is thrown in [line 49](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/web/trace/reactive/ServerWebExchangeTraceableRequest.java#L49) of [ServerWebExchangeTraceableRequest](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/web/trace/reactive/ServerWebExchangeTraceableRequest.java) because `request.getRemoteAddress().getAddress()` is null when you make a request with an empty X-Forwarded-For header.

You can reproduce it with a request like this
```http
GET http://localhost:8080/some-path
X-Forwarded-For: 
```

The path doesn't matter because the request doesn't reach the routing system.

**Comment by snicoll** [comment]
Closing in favour of PR #16046
