### ISSUE TITLE
Support for Spring Boot DevTools YAML Configuration

### ISSUE THREAD

**Issue by ddcruver** [spring-projects/spring-boot#16042]
DevTools should support DevTools overrides formatted with yaml.

So in addition to reading in .spring-boot-devtools.properties it should also read in 
_.spring-boot-devtools.yaml_.  It could also read _.spring-boot-devtools.yml_ but when both are provided then an order would need to be determined.

See [DevToolsHomePropertiesPostProcessor](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/env/DevToolsHomePropertiesPostProcessor.java)

Side note why doesn't .spring-boot-devtools place folder at the root instead of making a hidden folder for future proofing of additional files.

Value Adds:
- YAML subjectively can provide better organization of properties
- You can define mulitple profiles in a YAML File

**Comment by philwebb** [comment]
> Side note why doesn't .spring-boot-devtools place folder at the root instead of making a hidden folder for future proofing of additional files.

Good idea. If we add additional file support we could consider `.config/spring-boot/` to align with https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ddcruver** [comment]
I don't recall if I have seen others follow the .config standard; most pollute the home directory or slightly better make a hidden folder of their choosing.  If you do that I believe then on Windows you should use that platforms recommendations.  I believe that is to store it in AppData (%LOCALAPPDATA%).

References:
[Windows Shell Developer's Guide - Default Known Folders in Windows](https://docs.microsoft.com/en-us/windows/desktop/shell/knownfolderid)
[Microsoft UWP Documentation](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.ApplicationData#Windows_Storage_ApplicationData_LocalFolder)

**Comment by ddcruver** [comment]
Here is a Python project https://github.com/ActiveState/appdirs that tries to address cross platform storage of configuration files per-user which on Linux appears to uses XDG spec and Windows uses Microsoft recommendations.

Maybe this can be used as a model of what to do.

See user_config_dir in https://github.com/ActiveState/appdirs/blob/master/appdirs.py.

**Comment by philwebb** [comment]
Closing in favor of PR #17915
