### ISSUE TITLE
Spring Boot creates two beans for MongoDataAutoConfiguration when using @RefreshScope Annotation

### ISSUE THREAD

**Issue by anshumt** [spring-projects/spring-boot#16052]
I have defined the following configuration class in my Spring boot project:

```
@RefreshScope
@Configuration
@EnableMongoRepositories(basePackages = {"repository-package"})
public class MongoConfig extends AbstractMongoConfiguration {

	@Value("${spring.data.mongodb.database}")
	private String database;

	@Value("${spring.data.mongodb.host}")
	private String host;

	@Value("${spring.data.mongodb.username}")
	private String username;

	@Value("${spring.data.mongodb.password}")
	private String password;

	@Value("${spring.data.mongodb.port}")
	private Integer port;

	@Override
	protected String getDatabaseName() {
		return database;
	}

	@Override
	@Bean
	public Mongo mongo() throws Exception {
		return new MongoClient(Collections.singletonList(new ServerAddress(host, port)),
				Collections.singletonList(MongoCredential.createCredential(username,database, password.toCharArray())));
	}
}
```

When I start my spring boot app, it fails with the following reason:

> Parameter 1 of method mongoMappingContext in org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration required a single bean, but 2 were found:
> 	- customConversions: defined by method 'customConversions' in class path resource [config-package-path/MongoConfig.class]
> 	- mongoCustomConversions: defined by method 'mongoCustomConversions' in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.class]

The reason I added @RefreshScope annotation is because I have externalized the property file using spring cloud config.

The property file is in a remote github repo and when I over-write that file with some changes, the @refreshScope annotation refreshes the values that are being passed.

Any work-around for this?

**Comment by spencergibb** [comment]
Boot folks, he posted in spring cloud, we'll handle it there.

**Comment by wilkinsona** [comment]
Thanks, @spencergibb.
