### ISSUE TITLE
Rest service with Spring Boot and Jersey incorrectly returns HTTP Status 404 even though resource exists. 

### ISSUE THREAD

**Issue by imitrabhanu** [spring-projects/spring-boot#16050]
All my get methods are working fine, however, I am getting 404 for post. Following are my spring boot and jersey version. 
springBootVersion = '1.5.19.RELEASE'
springVersion = '4.3.22.RELEASE'
jerseyVersion = '1.19.4'
Thanks!
![screen shot 2019-02-27 at 8 14 21 pm](https://user-images.githubusercontent.com/5598323/53498427-57114600-3acc-11e9-8af0-dffbbeefb198.png)

**Comment by wilkinsona** [comment]
Without knowing how you've configured Jersey and how you've configured the mappings for your POST requests, I don't think we're going to be able to diagnose the problem. If you would us to spend some time trying to help you, please spend some time providing sufficient details for us to do so. A complete and minimal example that reproduces the problem in the form of a zip attached to this issue or a separate repository on GitHub would be ideal.

**Comment by imitrabhanu** [comment]
My apologies. 
Hope the below details will help you understand the configuration and mapping.
// Jersey Configuration Class

@Configuration
public class WebXmlConfiguration {

    @Bean
    public Filter springSecurityFilterChain() {
        return new DelegatingFilterProxy();
    }

    @Bean
    public ServletRegistrationBean jersey() {
        Servlet jerseyServlet = new SpringServlet();
        ServletRegistrationBean jerseyServletRegistration = new ServletRegistrationBean();
        jerseyServletRegistration.setServlet(jerseyServlet);
        jerseyServletRegistration.addUrlMappings("/api/v1/*");
        jerseyServletRegistration.setName("jersey-servlet");
        jerseyServletRegistration.setLoadOnStartup(1);
        jerseyServletRegistration.addInitParameter("com.sun.jersey.api.json.POJOMappingFeature", "true");
        jerseyServletRegistration.addInitParameter("com.sun.jersey.spi.container.ContainerResponseFilters",
                ResponseCorsFilter.class.getName());
        jerseyServletRegistration.addInitParameter("com.sun.jersey.config.feature.DisableWADL", "true");
        return jerseyServletRegistration;
    }
}

// API gateway

@Path("/authentication")
@Component
@Scope("singleton")
public class AuthenticationApiResource {
    private final Log logger = LogFactory.getLog(getClass());
    
    @POST
    @Produces({ MediaType.APPLICATION_JSON })
    public String authenticate(final String apiRequestBodyAsJson) {  
        //Auth implementation
    }
}


// Client request
var apiVer = '/novobank-core/api/v1';
httpService.post(apiVer + "/authentication",{username:credentials.username,password:encryptedPassword})
                            .success(onSuccess)
                            .error(onFailure);

**Comment by wilkinsona** [comment]
Using the above, I have tried to piece together an application that reproduces the problem and have been unable to do so. With the following resource:

```java
@Path("/authentication")
@Component
@Scope("singleton")
public class AuthenticationApiResource {

    private final Log logger = LogFactory.getLog(getClass());

    @POST
    @Produces({ MediaType.APPLICATION_JSON })
    public String authenticate(final String apiRequestBodyAsJson) {
    	return "hello";
    }

}
```

A POST request produces a 200 response with `hello` as its body:

```
curl -iX POST localhost:8080/api/v1/authentication
HTTP/1.1 200 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 27 Feb 2019 15:32:53 GMT

hello
```

If you would like us to spend any more time on this please take the time to provide a zip file or Git repository that contains a minimal application that reproduces the problem.

**Comment by imitrabhanu** [comment]
Thanks for your time, Andy.
I tried creating a sample project to reproduce the issue and I was able to do so. Using spring mapping it is working without any issue however with jersey it is not working. Please find the attached project for your reference.
[SpringBootJerseyTest.zip](https://github.com/spring-projects/spring-boot/files/2918759/SpringBootJerseyTest.zip)

**Comment by wilkinsona** [comment]
When you're using Jersey 1, you need to register Jersey's `Filter` or `Servlet` yourself and your sample doesn't do that. As a result, neither `GET` nor `POST` works which doesn't match the behaviour that you described above why you said that `GET` requests worked and `POST` requests did not.

If I add the following bean to your sample:

```java
@Bean
public ServletRegistrationBean jersey() {
    Servlet jerseyServlet = new SpringServlet();
    ServletRegistrationBean jerseyServletRegistration = new ServletRegistrationBean();
    jerseyServletRegistration.setServlet(jerseyServlet);
    jerseyServletRegistration.addUrlMappings("/jersey/*");
    jerseyServletRegistration.setName("jersey");
    return jerseyServletRegistration;
}
```

Both `GET` and `POST` requests work as expected:

```
curl -i localhost:8080/jersey/jersey/get
HTTP/1.1 200 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Fri, 01 Mar 2019 09:34:04 GMT

Hello Get
```
```
curl -i -X POST localhost:8080/jersey/jersey/post
HTTP/1.1 200 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Fri, 01 Mar 2019 09:34:11 GMT

Hello POST
```

If you'd like us to spend some more time on this, please provide a sample that reproduces the behaviour you have described where `GET` requests work but `POST` requests do not.

**Comment by imitrabhanu** [comment]
I tried multiple ways to reproduce the issue with some small application, but I am not able to do so.
The issue is only coming in our main application which is pretty big for sharing. 
I have enabled debug and able to get some more logs, hope it might help in finding the issue.

Debug logs:- 
13:19:54.161 [https-jsse-nio-8443-exec-2] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@254e1617
/crypt/getpublicrsakey & OPTIONS
/crypt/getpublicrsakey & OPTIONS
/crypt/getpublicrsakey & OPTIONS
13:19:55.475 [https-jsse-nio-8443-exec-2] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@254e1617
13:19:55.486 [https-jsse-nio-8443-exec-3] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@254e1617
Tenant = /novobank-core/api/v1/crypt/getpublicrsakey = GET
13:19:55.487 [https-jsse-nio-8443-exec-3] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tomcatJdbcDataSourcePerTenantService'
13:19:55.489 [https-jsse-nio-8443-exec-3] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tomcatJdbcDataSourcePerTenantService'
/crypt/getpublicrsakey & GET
/crypt/getpublicrsakey & GET
/crypt/getpublicrsakey & GET
13:19:55.495 [https-jsse-nio-8443-exec-3] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tomcatJdbcDataSourcePerTenantService'
13:19:55.501 [https-jsse-nio-8443-exec-3] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@254e1617
13:19:55.525 [https-jsse-nio-8443-exec-4] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@254e1617
/authentication & OPTIONS
/authentication & OPTIONS
/authentication & OPTIONS
13:19:55.530 [https-jsse-nio-8443-exec-4] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@254e1617
13:19:55.538 [https-jsse-nio-8443-exec-5] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@254e1617
Tenant = /novobank-core/api/v1/authentication = POST
13:19:55.539 [https-jsse-nio-8443-exec-5] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tomcatJdbcDataSourcePerTenantService'
13:19:55.540 [https-jsse-nio-8443-exec-5] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tomcatJdbcDataSourcePerTenantService'
13:19:55.544 [https-jsse-nio-8443-exec-5] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@254e1617
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.web.servlet.DispatcherServlet - DispatcherServlet with name 'dispatcherServlet' processing POST request for [/novobank-core/error]
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Looking up handler method for path /error
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Did not find handler method for [/error]
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Matching patterns for request [/error] are [/**]
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - URI Template variables for request [/error] are {}
13:19:55.545 [https-jsse-nio-8443-exec-5] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Mapping [/error] to HandlerExecutionChain with handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], class path resource [public/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@70acea6]]] and 1 interceptor
13:19:55.550 [https-jsse-nio-8443-exec-5] DEBUG o.s.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
13:19:55.550 [https-jsse-nio-8443-exec-5] DEBUG o.s.web.servlet.DispatcherServlet - Successfully completed request

As we are not able to solve the issue as a last resort will try to shift to SPRING Rest.

**Comment by wilkinsona** [comment]
The `POST` request has been routed into Spring MVC's `DispatcherServlet` rather than into Jersey. That routing is performed by Tomcat (assuming you're using the default embedded container). You could try using a debugger and some breakpoints in `org.apache.catalina.mapper.Mapper` to determine why the `POST` request is apparently being routed differently.

**Comment by imitrabhanu** [comment]
As starting from Spring Security 4.x the CSRF protection is enabled by default the post requests were blocked by CSRF filter. 
Disabling the filter resolved the issue.

**Comment by wilkinsona** [comment]
I'm glad to hear that you've figured it out. Thanks for letting us know.
