### ISSUE TITLE
The lack of punctuation in a document

### ISSUE THREAD

**Issue by caojiele** [spring-projects/spring-boot#16055]
Hi, The lack of punctuation in document that links is [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/documentation-overview.adoc). "Working with Spring Boot"-"Running your code" Should be added behind the colon.

**Comment by mbhave** [comment]
@caojiele Thanks but there's no need to create an issue and a PR for the same thing. Closing in favor of PR #16056.

**Comment by caojiele** [comment]
@mbhave ok, and these documents need to translate? I have recently been writing about spring boot.
