### ISSUE TITLE
Logs of java.util.logging.Logger are not output when war is deployed to tomcat.

### ISSUE THREAD

**Issue by neut-funahashi** [spring-projects/spring-boot#16062]
Spring boot 2.0.4.RELEASE
apache tomcat 8.5.38

SLF4JBridgeHandler.install will not run because the isJulUsingASingleConsoleHandlerAtMost method is false at runtime on org.springframework.boot.logging.Slf4JLoggingSystem class configureJdkLoggingBridgeHandler.

In order to prevent log duplication, how about installing after uninstalling in advance?

It is confirmed that it is output normally with Spring boot 1.3.8.

**Comment by wilkinsona** [comment]
While not ideal, this is working as designed.

In a multi-application environment, such as standalone Tomcat, bridging JUL into SLF4J results in any logging using JUL (by Tomcat itself or any of the applications) being routed into the application-specific log. To avoid this problem we deliberately do not install the bridge in such environments. Please see https://github.com/spring-projects/spring-boot/issues/13470 for further details.

We should probably note this behaviour in the documentation. We can use this issue to do that.

**Comment by hengyunabc** [comment]
@wilkinsona 

When there are only two Handlers: `java.util.logging.ConsoleHandler` and `org.slf4j.bridge.SLF4JBridgeHandler` , remove these two Handlers?

```java
    private boolean isJulUsingASingleConsoleHandlerAtMost() {
        Logger rootLogger = LogManager.getLogManager().getLogger("");
        Handler[] handlers = rootLogger.getHandlers();
        return handlers.length == 0
                || (handlers.length == 1 && handlers[0] instanceof ConsoleHandler)
                || (handlers.length == 2 && handlers[0] instanceof ConsoleHandler && handlers[1].getClass().getName().equals("org.slf4j.bridge.SLF4JBridgeHandler"));
    }
```

**Comment by wilkinsona** [comment]
@hengyunabc Can you explain the benefit of what you have proposed? `isJulUsingASingleConsoleHandlerAtMost` is used to determine whether or not the `SLF4JBridgeHandler` should be installed. Why would we install it when it's already present, and in what situation would it already be present?

**Comment by hengyunabc** [comment]
@wilkinsona We have a problem like this: 

In the main method, before the spring boot application starts, we have the initialization code. In this code, slf4j will install a `SLF4JBridgeHandler`, then the spring boot will skip the install in 
 `Slf4JLoggingSystem`.

```java
	public static void main(String[] args) {
		// some init code, will install a SLF4JBridgeHandler
		XXX.init();
		// start spring boot
		SpringApplication.run(DemoApplication.class, args);
	}
```

Currently, I am removing the `SLF4JBridgeHandler` before starting the spring boot. 

So I think when there are only two Handlers: `java.util.logging.ConsoleHandler` and `org.slf4j.bridge.SLF4JBridgeHandler`, can remove these two Handlers?

**Comment by wilkinsona** [comment]
The problem that you are facing seems to be specific to your application and it calling `XXX.init()`. Unfortunately, we can't change the behaviour of `Slf4jLoggingSystem` for everyone to work around the unusual behaviour in your application. Thanks anyway for the suggestion.
