### ISSUE TITLE
Gradle plugin does not write all required manifest entries

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16068]
The Java buildpack relies on a few manifest entries to detect Spring Boot archives. With the Maven Plugin these are written [here](
https://github.com/spring-projects/spring-boot/blob/25bf0c2493a5b21c8ff2233c4751d3d06eb6613e/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/Repackager.java#L307).

Since Spring Boot 2.0 the Gradle plugin no longer uses the `Repackager` class and we've unfortunately lost these entries. We'll likely need to change [these lines](https://github.com/spring-projects/spring-boot/blob/25bf0c2493a5b21c8ff2233c4751d3d06eb6613e/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/bundling/BootArchiveSupport.java#L82).

**Comment by rhamedy** [comment]
@philwebb how is this for a ‘first-timer’ contribution?

**Comment by clevertension** [comment]
@philwebb @rhamedy  are you working to fix this issue? if not, i can provide a PR :stuck_out_tongue:
