### ISSUE TITLE
Migration guide multipart

### ISSUE THREAD

**Issue by MonsieurMan** [spring-projects/spring-boot#16061]
Hello this change in the application configuration file has not been documented in the migration guide :
`spring.`**http**`.multipart`
`spring.`**servlet**`.multiparts`

We just broke one production feature aha 🛠

**Comment by snicoll** [comment]
Not all keys need to be documented as we offer a tool that would warn you in case you're not using an IDE with Spring Boot support, see [the first section of the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#before-you-start).

The full changelog for changed configuration keys [is also available](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Configuration-Changelog) and referenced [at the beginning of the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes#new-and-noteworthy).

**Comment by MonsieurMan** [comment]
It sure makes sense, thanks for the quick reply ! Cheers 👍
