### ISSUE TITLE
[Feature Request/Project Code Handover] Lightweight support of RBAC

### ISSUE THREAD

**Issue by vsfalexanderpilch** [spring-projects/spring-boot#16075]
Summary
Support of a simple rbac approach would be great. It doesn't have to be a full blown implementation, but just the basic role to privileges mapping would be sufficient in a lot of cases.

We've implemented something like this at https://github.com/vsfexperts/rbac . Would you be interested in taking over the code/providing something similar?

There's also a ticket with spring-security project (https://github.com/spring-projects/spring-security/issues/6570), as I'm unsure which is the correct project.

**Comment by wilkinsona** [comment]
Please don't cross-post issues in multiple places. It divides the discussion and makes it harder to follow. I think this is more likely to belong in Spring Security than in Spring Boot so I am going to close this issue. If that changes, we can move the issue once we've had a chance to discuss it in one place.
