### ISSUE TITLE
Support YAML for Hazelcast configuration

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#16074]
Hazelcast has been traditionally configured with an XML file, `hazelcast.xml` for servers and `hazelcast-client.xml` for clients, and this is supported by Spring Boot Autoconfiguration.

Hazelcast is enhancing this to allow the same to be done with YAML, see https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#configuring-declaratively-yaml

As an enhancement, Spring Boot should auto-configure a Hazelcast instance based on the presence of this YAML in the same way as is done for the presence of XML

**Comment by neilstevenson** [comment]
I'd be happy to implement this feature, just checking the PR would be accepted first, as it's a reasonable amount of work

**Comment by snicoll** [comment]
Thanks for reaching out and letting us know about this feature. I'd be more than happy to review a PR.

**Comment by izeye** [comment]
This seems resolved via #16632.

**Comment by snicoll** [comment]
Good catch, I forgot to supersede this one. Thanks again, @izeye!
