### ISSUE TITLE
Auto-configured PrometheusPushGatewayManager cannot be configured to use HTTPS to connect to the gateway

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16073]
The String-based `PushGateway` constructor that we use hardcodes an `http` scheme to the `URL`. We should switch to the `URL`-based constructor instead to allow users to specify an `https` URL via `management.metrics.export.prometheus.pushgateway.base-url`. We'll have to take care to do so in a backwards-compatible manner, probably by preserving the existing assumption that the scheme should be `http` if not specified.

**Comment by mbhave** [comment]
Closing in favor of PR #16084.
