### ISSUE TITLE
Issue in spring-boot-legacy apps while migrating spring-boot from 2.0.5 to 2.1.3

### ISSUE THREAD

**Issue by balaji-tech87** [spring-projects/spring-boot#16085]
I am migrating spring-boot from 2.0.5 to 2.1.3.
Some of our applications uses **spring-boot-legacy** support (2.0.0.RELEASE).
While migrating the application, we face below issue, as there is some update in the "ServletContextInitializerBeans:constructor"

Please advice, if this is an issue or any configurations needs to be done.

**Error details:**
04-Mar-2019 16:32:40.487 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
04-Mar-2019 16:32:44.571 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring Boot Legacy WebApplicationContext
04-Mar-2019 16:32:44.608 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.boot.legacy.context.web.SpringBootContextLoaderListener]
 org.springframework.context.ApplicationContextException: Unable to start application context; nested exception is **java.lang.NoSuchMethodError:** org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(Lorg/springframework/beans/factory/ListableBeanFactory;)V
	at org.springframework.boot.legacy.context.web.NonEmbeddedWebApplicationContext.onRefresh(NonEmbeddedWebApplicationContext.java:78)

**Comment by snicoll** [comment]
Sorry but this is the wrong place to ask, this extension is not handed here, see https://github.com/dsyer/spring-boot-legacy
