### ISSUE TITLE
boot.autoconfigure doesn't work when using default boot library in Maven

### ISSUE THREAD

**Issue by velicanerdem** [spring-projects/spring-boot#16089]
Enhancement

Hello

I am a new user of Spring and Maven, so when I tried to use default  [spring-boot](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot) I encountered a problem where I couldn't import boot.autoconfigure. There were couple of questions and answers but none of them solved the problem.

I solved the problem by using [spring-boot-autoconfigure](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-autoconfigure) instead. So what is the exact problem here? Is spring-boot in Maven deprecated? (because it couldn't resolve org.springframework.boot.autoconfigure) Or does it have other use?

**Comment by snicoll** [comment]
Those are simply two different maven modules. Classes in the `org.springframework.boot.autoconfigure` package are in the `spring-boot-autoconfigure` module so if you add `spring-boot` to your project, you won't have those on the classpath. Applications usually rely on [starters](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter). if you're getting started, you can also bootstrap your application on https://start.spring.io.

Having said all that, we don't use the issue tracker for questions (see [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues)). If you have more questions, please ask on StackOverflow.
