### ISSUE TITLE
config-client  no need @RefreshScope 

### ISSUE THREAD

**Issue by wmyteacher** [spring-projects/spring-boot#16082]
clould :  Finchley.RELEASE 
boot   :  2.0.2.RELEASE
refreshing configuration files at the receiving end without no need @RefreshScope  annotation

this is my public git address ： https://git.imooc.com/wmy/private-error-order.git
contain eureka    config-server(config)  config-client(order)
demo url in order  project         http://192.168.0.118:9002 /girl/print
configuration  file  use order-dev.yml   in   https://gitee.com/halfroom/config-repo.git 
!!!!!!       manually refresh bus address after configuration change   
                http://192.168.0.118:9091/actuator/bus-refresh

**Comment by snicoll** [comment]
This issue tracker does not manage Spring Cloud issues. Please consider asking a question on StackOverflow first. If you're convinced you've found a bug in the way configuration is refreshed by Spring Cloud, please open an issue [in the appropriate issue tracker](https://github.com/spring-cloud/spring-cloud-commons).

**Comment by wmyteacher** [comment]
o....thks
