### ISSUE TITLE
lost session in BasicErrorController

### ISSUE THREAD

**Issue by HongKing** [spring-projects/spring-boot#16095]
version: Spring Boot (v2.0.6.RELEASE)

In MyControoler, the session in `HttpServletRequest request` is not null, but when MyController throw an exception, in `org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController` session is null, this may be a bug or I use wrong? how can I get the session when I catch all excetpion in spring boot?

MyControoler
![1](https://user-images.githubusercontent.com/1324004/53778469-d0c78a80-3f37-11e9-9df9-956eee7bdbf1.png)
![2](https://user-images.githubusercontent.com/1324004/53778471-d4f3a800-3f37-11e9-9796-8c8690c71a8c.png)

BasicErrorController
![3](https://user-images.githubusercontent.com/1324004/53778485-e341c400-3f37-11e9-9d93-37b2fe17045f.png)
![4](https://user-images.githubusercontent.com/1324004/53778489-e63cb480-3f37-11e9-9fef-32a98bfe3ceb.png)

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, I can’t tell if you are using something wrongly from a few screenshots. If you would like us to spend some time trying to help you please spend some time providing a complete and minimal sample that reproduces the problem.

**Comment by HongKing** [comment]
sorry. my usage error. I cleared the session before it's in BasicErrorController.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
