### ISSUE TITLE
@WebFluxTest does not enable auto-configuration for any reactive template engines

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16101]
Mustache, FreeMarker, and Thymeleaf all support reactive web apps and should be included in `@WebFluxTest`

**Comment by ayudovin** [comment]
@wilkinsona, I want to work on it. Please let me know if I can start working on it?

**Comment by wilkinsona** [comment]
@ayudovin Thanks for asking, @ayudovin. Yes, you can start working on this. A PR would be much appreciated.

**Comment by wilkinsona** [comment]
Closing in favour of #16170.
