### ISSUE TITLE
When using WebFlux /actuator/health/{component} returns a 200 response when the component is down

### ISSUE THREAD

**Issue by jrushto1** [spring-projects/spring-boot#16109]
When using the spring-boot-starter-webflux dependency custom health indicators return a status code of 200 when navigating to /actuator/health/{custom} despite the health object being down.

Sample project [here](https://github.com/jrushto1/springbootactuatortest).

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem isn't specific to a custom health indicator and can be recreated by, for example, setting a very large threshold for `diskSpace` health:

```
http :8080/actuator/health/diskSpace
HTTP/1.1 200 OK
Content-Length: 98
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8

{
    "details": {
        "free": 782707150848,
        "threshold": 54975581388800,
        "total": 1000240963584
    },
    "status": "DOWN"
}
```

Both `ReactiveHealthIndicator` and `HealthIndicator` implementations are affected.

The problem does not occur when using the Servlet-based stack:

```
http :8080/actuator/health/diskSpace
HTTP/1.1 503 
Connection: close
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Wed, 06 Mar 2019 10:15:04 GMT
Transfer-Encoding: chunked

{
    "details": {
        "free": 782717988864,
        "threshold": 54975581388800,
        "total": 1000240963584
    },
    "status": "DOWN"
}
```

**Comment by avyyaaggarwal** [comment]
Hello @wilkinsona : I am trying to understand which commit introduced the bug. Can help me which line in the current fix commit fixed the bug? is it line number 63 in the file healthendpointwebIntegrationTests.java? Thanks
