### ISSUE TITLE
Default login page - Could not verify the provided CSRF token because your session was not found. 

### ISSUE THREAD

**Issue by tomaszmil** [spring-projects/spring-boot#16103]
Spring boot version: 2.1.3

**Dependencies:**
* spring-boot-starter-security
* spring-boot-starter-web

**Issue**
Default login page does not work as the session is not created.

**How to reproduce:**
* Generate project from https://start.spring.io/ with *web* and *security* dependencies.
* Build and start the boot application
* Access your project root page
* On login page provide any credentials you'd like to (you can use valid one username as *user* and password that has been generated during the start of application)
* Observe page reload with no error message

**Comment by mbhave** [comment]
@tomaszmil I don't think I fully understand the issue from the above description. I created an app with `spring-boot-starter-security` and `spring-boot-starter-web` and was able to login successfully.

Please provide a minimal sample application that we can run to reproduce the issue.

**Comment by tomaszmil** [comment]
Please find the code I am using in this repository: https://github.com/tomaszmil/spring-boot-login-issue 

**note** Application port is 4991 (I changed that because I've docker image running under 8080)

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it does not reproduce the behaviour that you have described and I can log in successfully.

Are you sure that you have cookies enabled in your browser?

**Comment by tomaszmil** [comment]
You are right! This is the problem with my browser. Apology for not checking that earlier.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
