### ISSUE TITLE
Upgrade to Junit Jupiter 5.4.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16149]

**Comment by PascalSchumacher** [comment]
Hi Andy,

what about adding dependency management for the new `junit-jupiter` artifact (see: https://junit.org/junit5/docs/current/release-notes/index.html#new-features-and-improvements-2 for details)?

**Comment by wilkinsona** [comment]
There's nothing for us to add. We import their bom which contains the new artifact.
