### ISSUE TITLE
Review @ConditionalOnExposedEndpoint

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#16169]
Since #16093, a new conditional annotation has been introduced to guard Actuator endpoints and only instantiate infrastructure when endpoints are exposed.

Given [this comment on the issue](https://github.com/spring-projects/spring-boot/issues/16093#issuecomment-470845127):

> The current implementation is completely separating enablement and exposure.
For now, @ConditionalOnEnabledEndpoint and @ConditionalOnExposedEndpoint are used together. It might make sense to revisit that in the next milestone and make @ConditionalOnExposedEndpoint call the other. Right now I'm wondering if it's still best to keep those separated as they are different concepts and there might be cases where we want to let developers reuse/extend existing infrastructure independently of what's happening with the endpoints.

We should review this annotation and consider whether we want to merge condition implementations, or consider both conditions when `@ConditionalOnExposedEndpoint` is added.

**Comment by snicoll** [comment]
How about `ConditionalOnAvailableEndpoint`? Or perhaps we only need that and not the exposed one? I wonder if there is a case to check if it's exposed but not enabled. If there isn't we could replace `ConditionalOnExposedEndpoint` by `@ConditionalOnAvailableEndpoint` that checks both. 

That way, we'd have a single annotation for both purposes.

**Comment by bclozel** [comment]
My vote goes to deprecating `@ConditionalOnEnabledEndpoint` and `@ConditionalOnExposedEndpoint`, and merging them both into a new `@ConditionalOnAvailableEndpoint`.

**Comment by snicoll** [comment]
`@ConditionalOnEnableEndpoint` is now deprecated and users are invited to move to `@ConditionalOnAvailableEndpoint` to get extra checks that prevent the bean to be created if the underlying endpoint is not going to be used in practice.
