### ISSUE TITLE
Investigate problem with Maven Flatten Plugin and Maven 3.6.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16167]
When using Maven 3.6.0, the Flatten Plugin fails to create an effective pom as it is unable to resolve a milestone dependency. This failure occurs because it only has Maven Central available as a repository.

In Maven 3.5.4, all of the repositories configured in the pom are available because the project's remote repositories have been [set](https://github.com/apache/maven/blob/maven-3.5.4/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java#L646) on the project building request before it's used by the flatten plugin. This happens because there was no `MavenProject` found with a model ID of `org.springframework.boot:spring-boot-build:${revision}`.

In Maven 3.6.0, the repositories are not set on the project building request. They are not set because the different model ID is used when looking up the parent. Rather than `org.springframework.boot:spring-boot-build:${revision}` which is used in Maven 3.5.4, `org.springframework.boot:spring-boot-build:2.2.0.BUILD-SNAPSHOT` is used instead. The expansion of `${revision}` into `2.2.0.BUILD-SNAPSHOT` allows an [existing entry in the `projects` map to be found](https://github.com/apache/maven/blob/maven-3.6.0/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java#L638).

Further investigation is needed. I've yet to determine if this is a regression in Maven, a bug in the Flatten Plugin, or if we're doing something wrong that only comes to light with Maven 3.6.0.

**Comment by wilkinsona** [comment]
Our use of `${revision}` appears to be crucial to it working in 3.5.4. Swapping that out and setting the version directly results in the same failure with 3.5.4 as is occurring with 3.6.0. My hunch is that we were relying on a quirk of Maven's behaviour that's been fixed in 3.6. Hopefully the Flatten Plugin issue will shed some light on things. In the meantime, we can roll back to 3.5.4.

**Comment by philwebb** [comment]
See this Maven PR https://github.com/mojohaus/flatten-maven-plugin/pull/98
