### ISSUE TITLE
logfile endpoint returns HTTP 406 on Accept: text/plain

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#16188]
The logfile endpoint responds with a content of type `text/plain`.
When doing the get request with `Accept: text/plain` a HTTP 406 (Not Acceptable) is returned. I'd expected such a request to succeed.

**Comment by joshiste** [comment]
It looks like that only `Accept: */*` (or omitting the header) works.

**Comment by wilkinsona** [comment]
Thanks for the report, @joshiste. Looks like this affects all three web stacks. Here's an addition to `LogFileWebEndpointWebIntegrationTests` that fails on Jersey, Spring MVC, and Reactive:

```java
@Test
public void getRequestThatAcceptsTextPlainProducesResponseWithLogFile() {
	TestPropertyValues.of("logging.file:" + this.logFile.getAbsolutePath())
			.applyTo(context);
	client.get().uri("/actuator/logfile").accept(MediaType.TEXT_PLAIN).exchange()
			.expectStatus().isOk().expectBody(String.class).isEqualTo("--TEST--");
}
```
