### ISSUE TITLE
Review need for `@Autowired` on `@ConfigurationProperties` class's constructor

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16186]
The new support for constructor binding of configuration properties has introduced a need for `@Autowired` on a `@ConfigurationProperties` class's constructor. I find it a little confusing when the class only has a single constructor as, since Framework 4.3 (I think), `@Autowired` has not been necessary when the class only has a single constructor. I'd like to see if we can drop the requirement. If we can't, the documentation should be updated to explain why it's needed so that we can reduce the potential confusion as much as possible.

**Comment by wilkinsona** [comment]
We can do this is part of the original issue as it hasn’t been in a release yet.

**Comment by snicoll** [comment]
There is already a doc issue #16175 - as for the use of autowired this may evolve once we implement classpath scanning that also has a dedicated issue.
