### ISSUE TITLE
Registering custom Mongo type converters should be more easy

### ISSUE THREAD

**Issue by holgerstolzenberg** [spring-projects/spring-boot#1619]
Having a look at

https://github.com/ewerk/sample_spring-boot-camel-mongo-jdk8/blob/features/jsr310/prototype-app/src/main/java/com/ewerk/prototype/persistence/PersistenceConfiguration.java

shows that it took me to override three bean definitions in order to register the JSR-310 custom type converters for the Mongo stack. It was a bit tricky to figure out because documentation is really quit about this.

I needed to look up  `org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration` and `org.springframework.data.mongodb.config.AbstractMongoConfiguration` sources to get it to work.

The  bean definitions
- `MappingMongoConverter`
- `MongoTemplate` (more specific than in current auto configuration)

could be provided by the `@MongoAutoConfiguration` out of the box, so that it is only necessary to provide a own `@Bean` of type `org.springframework.data.mongodb.core.convert.CustomConversions`.

Extending `AbstractMongoConfiguration` is also not an option for me, as it requires me to override e.g. `getDatabaseName()` in which the `Environment` is not accessible which holds my configured database name. Or am I missing something obvious here?

Registering the `CustomConversions` bean should be as easy as it is for `MongoClientOptions`.

I am using `1.1.6.RELEASE`.

**Comment by lsoares** [comment]
Hi,

This thread is > 2 years.
Is it solved?
Is this still the best way to create MongoDB custom converters?
https://github.com/ewerk/sample_spring-boot-camel-mongo-jdk8/blob/features/jsr310/prototype-app/src/main/java/com/ewerk/prototype/persistence/PersistenceConfiguration.java

**Comment by wilkinsona** [comment]
@lsoares As you can see above, this issue was closed almost two years ago. You can now provide your own `CustomConversions` bean that contains one or more converters.

**Comment by lsoares** [comment]
I suspected it was solved.. but I was looking for a practical example. I searched the web I see a lot, but they're very similar to the old style.

Do you have any good example?

**Comment by wilkinsona** [comment]
There's [a test](https://github.com/spring-projects/spring-boot/commit/670ba33bec4b0e578e6e113fed5b0b2890807472#diff-2535a8965773add60ef1bbeb7dcb873d) in the commit that closed this issue.
