### ISSUE TITLE
PropertySource and arrays of string

### ISSUE THREAD

**Issue by emax19** [spring-projects/spring-boot#16198]
l tried to use configuration file(another-prop.yml) using PropertySource annotation. But in including file doesn't parse an array of string like in main file configuration(application.yml). 
In application yml, arrays is working with separating each line via '-', for another-prop.yml it is not working

It has been tested in spring boot version of 2.2.0.M1, 2.2.0.BUILD-SNAPSHOT and 2.1.3.RELEASE... 
jdk1.8.0_191

![image](https://user-images.githubusercontent.com/23064543/54144361-346c1f00-4434-11e9-9e0b-13c518456f13.png)
sources -> [demo.zip](https://github.com/spring-projects/spring-boot/files/2953516/demo.zip)

**Comment by wilkinsona** [comment]
`@PropertySource` is part of Spring Framework and does not support YAML.
