### ISSUE TITLE
Typo in 'Testing Spring Boot Applications' note on JUnit 5

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#16207]
There is a typo in the documentation. It currently states:

>If you are using JUnit 4, don’t forget to also add @RunWith(SpringRunner.class) to your test, otherwise the annotations will be ignored. If you are using JUnit 5, there’s no need to add the equivalent @ExtendWith(SpringExtension) as @SpringBootTest and the other @…Test annotations are already annotated with it.

The `.class` is missing, so it should be:

>  ....equivalent @ExtendWith(SpringExtension.class) as....

**Comment by orangeroad0922** [comment]
Hi. Can I work this issue?

**Comment by orangeroad0922** [comment]
Hi. Can I work this issue?

**Comment by orangeroad0922** [comment]
Hi. Can I work this issue?

**Comment by wilkinsona** [comment]
I see you already have. Thanks very much for the PR. I'll close this issue in favour of it.
