### ISSUE TITLE
Default Jackson HttpMessageConverter does not honor autoconfigured ObjectMapper 

### ISSUE THREAD

**Issue by holgerstolzenberg** [spring-projects/spring-boot#1620]
Please see 

https://github.com/ewerk/sample_spring-boot-camel-mongo-jdk8/blob/features/jsr310/prototype-app/src/main/java/com/ewerk/prototype/api/ApiConfiguration.java

that illustrates the problem. The `ApiConfiguration` class does nothing special then overriding the HttpMessageConverters used by WebMVC. I am not configuring anything special to the Jackson `ObjectMapper`. The jackson JSR-310 module is on the classpath.

If you launch the app and access the URL `http://localhost:9090/prototype/api/persons/all` you can see that the person beans birthday property is correctly mapped to a string representation

Commenting out the code within `ApiConfiguration` and running the app again shows that the birthday property is rendered as a JSON object.

Debugging the app shows that all autoconfiguration related stuff is honoring the JSR-310 module, which then gets registered in the `@PostConstruct` method of `JacksonAutoConfiguration`. But something in bean creation order is messed up or the Jackson message converter created as default does not use the `ObjectMapper` instance created by spring boot autoconfiguration.

**Comment by hantsy** [comment]
I used `@EnableWebMvc` on the `WebConfig`, and created a custome @Configuration for `ObjectMapper`, it does not work.

<pre>
@Configuration
public class Jackson2ObjectMapperConfig {

    @Bean
    @Primary
    public ObjectMapper objectMapper() {
        
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder(); 
        builder.serializationInclusion(Include.NON_EMPTY);
        builder.featuresToDisable(
                SerializationFeature.WRITE_DATES_AS_TIMESTAMPS,
                DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES,
                DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        builder.featuresToEnable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
        builder.modulesToInstall(JSR310Module.class);

        return builder.build();
    }

}

</pre>

**Comment by wilkinsona** [comment]
Using `@EnableWebMvc` turns off Spring Boot's auto-configuration of Spring MVC, is that what you intended? Also, it's not clear what you mean by "it does not work".

If you'd like some help, please post on Stackoverflow using the `spring-boot` tag, describing the behaviour that you expected to see and what the actual behaviour was. A small sample that reproduces the problem would also help.

**Comment by sdeleuze** [comment]
Using `@EnableWebMvc` disable Spring Boot web autoconfiguration, so the `ObjectMapper` bean is not used anymore. In order to make it work, remove `@EnableWebMvc`. If you need to use Spring MVC JavaConfig, you can declare a `WebMvcConfigurer` bean instead, and return a `WebMvcConfigurerAdpter` instance.

**Comment by hantsy** [comment]
@sdeleuze I used custom `WebMvcConfigurerAdpter` class(`WebConfig`) which annotated with`EnableWebMvc` and `@Configuration`.  And a standalone `Jackson2ObjectMapperConfig` for `ObjectMapper`(listed above). All of these are ported from my before projects(none spring boot project), but these did not work as exptected, the new Jdk 8 jsr310 jackson serialization configuration is not applied. As an end user of Spring boot, I hope my custom configuration owns high priority other than auto configuration provided by Spring Boot, thus I can move to Spring Boot painlessly.

**Comment by hantsy** [comment]
Thanks for your help, @sdeleuze , and @wilkinsona

**Comment by sdeleuze** [comment]
@hantsy As propsed by @wilkinsona , feel free to post a Stackoverflow question link, I will answer you there.
