### ISSUE TITLE
Test the Gradle plugin against Gradle 5.3-rc-3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16211]

**Comment by wilkinsona** [comment]
This is revealed what may be a regression in Gradle. I've opened https://github.com/gradle/gradle/issues/8748.

**Comment by pkostrzewa** [comment]
Gradle [v5.3.0-RC3](https://github.com/gradle/gradle/releases/tag/v5.3.0-RC3) has been released. I can verify plugin with this newly released version.
