### ISSUE TITLE
Auto-configure reactive Elasticsearch components introduced in Spring Data Moore

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16214]
We should auto-configure the new reactive Elasticsearch components, including a `ReactiveElasticsearchTemplate` and `ReactiveElasticsearchClient`, when the necessary dependencies are on the classpath.

**Comment by ayudovin** [comment]
@wilkinsona, Can I start working on it?

**Comment by ayudovin** [comment]
@wilkinsona, Can I try to do this enhancement?
