### ISSUE TITLE
Neo4jRepositoriesAutoConfiguration uses old style of checking whether repositories are enabled

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#16210]
`org.springframework.boot.autoconfigure.data.neo4j.Neo4jRepositoriesAutoConfiguration` uses `@ConditionalOnProperty` to check whether Neo4j repositories are enabled or not.

Since Spring Boot 2.0.0 there is a dedicated condition for it: `@ConditionalOnRepositoryType`. This condition makes the intentions clearer. It also explicitly states the type of the repository (at the moment, Neo4j supports only `IMPERATIVE`).

I could change this myself, but I think that would make a nice issue for a first-time contribution in the area of automatic configuration.

**Comment by mbhave** [comment]
It's slightly different because the property that the two conditions check are different (`spring.data.neo4j.repositories.enabled` vs `spring.data.neo4j.repositories.type`). #11134 has some history around why the enabled flag was kept around for repositories that do not have a reactive option.

**Comment by michael-simons** [comment]
Oh that's a good point!

Would it be an idea to throw an `InvalidConfigurationPropertyValueException` in a case where the reactive variant is not supported?

**Comment by snicoll** [comment]
IMO we should not move to `type` if there is no reactive support, offering a configuration option and then throwing an option seems nasty unless I misunderstood your proposal @michael-simons?

**Comment by michael-simons** [comment]
Yeah, one could call this nasty :) I wasn't sure how important a unified configuration is.
So, without having us reactive support, we should close this and leave stuff the way it is.
