### ISSUE TITLE
Please auto configure the WebSocketHandlerAdapter

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#16226]
I haven’t yet had to override the WebSockethandlerAdapter. Normally, in order to use websockets for reactive web apps I need to register:

- `WebSocketHandlerAdapter` (no-arg bean, same every time) 
- `WebSocketHandler` - the business logic 
- `SimpleUrlHandlerMapping` - mounts the `WebSocketHandler` at a particular URL

The last two i can understand having to register, but the `WebSocketHandlerAdapter` seems like work Spring Boot could be doing and have auto-configured with a `@ConditionalOnMissingBean` and `@COnditionalOnClass` combo.

**Comment by wilkinsona** [comment]
I have a strong feeling of deja vu: https://github.com/spring-projects/spring-framework/issues/22587.
