### ISSUE TITLE
Document using AssertJ's satisfies together with extractingJsonPathNumberValue

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#16229]
I am using `extractingJsonPathNumberValue` to test a double value in my JSON:

     assertThat(json.write(message))
       .extractingJsonPathNumberValue("@.stopTime.percentage").isEqualTo(0.16666666666666666)

However, this does not work because of different types:

> org.opentest4j.AssertionFailedError: 
> Expecting:
>  <"0.16666666666666666 (BigDecimal@1c52552f)">
> to be equal to:
>  <"0.16666666666666666 (Double@5dc769f9)">
> but was not.
> Expected :0.16666666666666666
> Actual   :0.16666666666666666

What is the recommended way to do this? Should there be other methods like `extractingJsonPathDoubleValue` or `extractingJsonPathFloatValue` that could return `DoubleAssert` or `FloatAssert` so that methods like `isCloseTo` can be used?

**Comment by wilkinsona** [comment]
We can consider adding some more methods, but I'm not sure that we need to increase the surface area of the API. You can use AssertJ's `satisfies` and your knowledge of the type of the `Number` to then use `isCloseTo`:

```java
assertThat(json.write(message))
    .extractingJsonPathNumberValue("@.stopTime.percentage")
    .satisfies((number) -> assertThat(number.floatValue()).isCloseTo(0.16f, within(0.01f)));
```

**Comment by wimdeblauwe** [comment]
Using `satisfies` is indeed a very good way to do it. Maybe this could be added to the https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-json-tests documentation instead of adding those extra methods to the API ?
