### ISSUE TITLE
Inner class @Configuration prevents application context startup

### ISSUE THREAD

**Issue by cameronxm** [spring-projects/spring-boot#16234]
It appears that trying to use a static inner class as a configuration prevents context startup (at least in the Spring Boot test world; I haven't tested it for an actual application). A standalone configuration class (i.e., in its own file) works just fine.

I created a project (Initializr with Boot 2.1.3 and only web dependency) which shows this behavior; you should just be able to run as JUnit to reproduce it:

https://github.com/cameronxm/spring-boot-inner-configuration-class-breaks-webflux

The error is:

> ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
>	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82)

There doesn't seem to be any reason that inner classes should be disallowed as configuration, but perhaps I'm missing something?

**Comment by wilkinsona** [comment]
This is covered [in the documentation](https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-config):

> If you want to customize the primary configuration, you can use a nested `@TestConfiguration` class. Unlike a nested `@Configuration` class, which would be used instead of your application’s primary configuration, a nested `@TestConfiguration` class is used in addition to your application’s primary configuration.

**Comment by cameronxm** [comment]
Wow, thanks for the quick response! I did actually search the documentation but missed that. Apologies.
