### ISSUE TITLE
Make WebMvcAutoConfigurationAdapter.FaviconRequestHandler package private

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#16233]
There's a new private class in `spring-boot-autoconfigure`. Can I ask that `WebMvcAutoConfigurationAdapter.FaviconRequestHandler` be package private please?

**Comment by mrifni** [comment]
Can I pick this up please ?

**Comment by snicoll** [comment]
@mrifni please go ahead, the issue is not assigned.

**Comment by mrifni** [comment]
sure doing it..

**Comment by snicoll** [comment]
Closing in favour of PR #16250

**Comment by mrifni** [comment]
@snicoll please find the simple PR for this task [here](https://github.com/spring-projects/spring-boot/pull/16250).

Happy to contrtibute.
@pkostrzewa thanks.
