### ISSUE TITLE
Gradle BootJar Task has a strange behaviour when there are dependencies with the same name

### ISSUE THREAD

**Issue by mxab** [spring-projects/spring-boot#16241]
Hi,
we had a project where we had two subprojects as dependency that had the same name, see this showcase
https://github.com/mxab/gradle-bootjar-problem

Therefore the two `client.jar` files were build and copied into the `BOOT-INF/lib` and therefore this cause problems.
My workaround solution is the name by subprojects unique.

So far so obvious... but I tried to create a unit test to showcase this but it turns out that the boot jar actually can handle two jar entries with the same name, at least at in the tests.

So this one actually passes:
```
@Test
  public void classpathJarsArePackagedBeneathLibPathEvenIfTheNameIsTheSame() throws IOException {
    this.task.setMainClassName("com.example.Main");
    this.temp.newFolder("foo");
    this.temp.newFolder("bar");
    this.task.classpath(jarFile("foo/client.jar"), jarFile("bar/client.jar"));
    executeTask();

    final String clientJarEntryName = this.libPath + "/client.jar";

    try (JarFile jarFile = new JarFile(this.task.getArchivePath())) {
      assertThat(jarFile.stream().map(JarEntry::getName).filter(clientJarEntryName::equals)).hasSize(2); // yes 2?!
    }
  }
```
This test passes also if I would you the jar that is built by `./gradlew bootJar`

In case this was intended I think the JarLauncher has to be adjusted to handle multiple jar entries with the same name, but I think this is generally a wired state.

I tried to come up with a fix on the gradle site but this would maybe mean to not use the `FileCollection` from the main sources set directly but use it's configuration and access it's ResolvedArtifact ids to generate a filename the will hopefully unique.
Any ideas?

**Comment by wilkinsona** [comment]
> I tried to come up with a fix on the gradle site but this would maybe mean to not use the FileCollection from the main sources set directly but use it's configuration and access it's ResolvedArtifact ids to generate a filename the will hopefully unique.

We do that in the Maven plugin, but cannot do so with Gradle as there's no guarantee that a file in the jar will have come from a resolved artifact with Maven coordinates. For example, it may have come from a flat file repository.

Gradle already provides two tools to handle this situation:

1. The jar's [duplicates strategy](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/AbstractCopyTask.html#setDuplicatesStrategy-org.gradle.api.file.DuplicatesStrategy-)
2. The ability to [rename](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/AbstractCopyTask.html#rename-org.gradle.api.Transformer-) files as they're added to the jar

We can consider changing the default duplicates strategy to [fail](
https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html#FAIL) or [warn](
https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html#warn) to make the problem easier to identify. If both jars are wanted, and can't be renamed at source, users would then have to implement their own transformation for renaming.

**Comment by mxab** [comment]
I think adding the `fail` would make sense even if it would break your build as otherwise there was something off before.

Regarding the the coordinates, wouldn't it possible to check the type of `ComponentIdentifier` and use its values to infer somekind of naming?
https://github.com/mxab/gradle-bootjar-problem/blob/dep-analysis/app/build.gradle#L45

**Comment by wilkinsona** [comment]
Unfortunately not, not without introducing a large amount of complexity anyway. `BootJar` uses a `FileCollection` to control its contents. While that collection may be a `Configuration` it cannot be assumed that it will be.

I've just reminded myself that Gradle uses a `null` duplicates strategy by default in its [war plugin](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.War.html#org.gradle.api.tasks.bundling.War:duplicatesStrategy) so we're aligned with Gradle's behaviour at the moment. Generally speaking, we aim to align our defaults with Gradle's so that things behave consistently for those with experience of Gradle's own plugins. As such, I'm no longer sure that it's a good idea to just `BootJar`'s default strategy. Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
We're going to stay with our current arrangement and remain aligned with Gradle. Thanks anyway.
