### ISSUE TITLE
Boolean ENV variables properties precedence

### ISSUE THREAD

**Issue by destebanm** [spring-projects/spring-boot#16254]
Hi!

I am having a possible issue related with precedence when loading properties with ENV variables. I have checked with these versions:
v2.1.1.RELEASE
v1.3.1.RELEASE

The problem arises when I define properties in application.properties of a library, and then I add the library as a dependency of a spring boot app. After then, I override this properties in the spring boot app.

_application.properties_ (library)
```
logging.request.filter.enabled=${LOGGING_REQUEST_FILTER_ENABLED}
logging.filter.markers.confidential.onMatch=${MATCH}
```

_application-default.properties_ (spring boot app)
```
logging:
  filter:
    markers:
      confidential:
        onMatch: ACCEPT
  request:
    filter:
      enabled: true
```

```
export LOGGING_REQUEST_FILTER_ENABLED=false
export MATCH=DENY
```

```
 @Value("${logging.request.filter.enabled}")
  private Boolean enabled;

  @Value("${logging.filter.markers.confidential.onMatch}")
  private String match;
  
  @PostConstruct
  void init() {
    System.out.println("@@@@@@"+enabled);
    System.out.println("@@@@@@"+match);
  }
```

It is printing:
```
false
ACCEPT
```
but it should print:
```
true
ACCEPT
```

If I define the property without an ENV variable:

`logging.request.filter.enabled=false`

then it prints 
`
true`

So, it seems that **boolean** properties with ENV variables are not following precedence rules.

Did you know this case?

Thanks!

**Comment by mbhave** [comment]
@destebanm This is the expected behavior. As mentioned in the [docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config), environment variables have higher precedence than config files such as `application.properties`.

If you have other questions about property source precedence, please join us on Gitter.
