### ISSUE TITLE
spring-boot-actuator solr health indicator reports solr down when solr client baseUrl contains core

### ISSUE THREAD

**Issue by schuch** [spring-projects/spring-boot#16256]
Using 2.1.3.RELEASE and the `SolrHealthIndicator` reports `down` when the `SolrClient` is created with a particular core specified in the baseUrl, e.g. http://localhost:8983/solr/techproducts`

The health indicator tries to use `http://localhost:8983/solr/techproducts/admin/cores` (`CoreAdminRequest`) which is a 404.

Example Project: https://github.com/schuch/spring-boot-actuator-solr-issue

To start solr with the techproducts collection run a fresh extracted solr distro with
```
solr -e techproducts
```

Output from http://localhost:8080/actuator/health
```
{
  "status": "DOWN",
  "details": {
    "solr": {
      "status": "DOWN",
      "details": {
        "solrClient": {
          "status": "UP",
          "details": {
            "status": 0
          }
        },
        "solrClientWithCollection": {
          "status": "DOWN",
          "details": {
            "error": "org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/techproducts: Expected mime type application/octet-stream but got text/html. <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /solr/techproducts/admin/cores. Reason:\n<pre>    Not Found</pre></p>\n</body>\n</html>\n"
          }
        }
      }
    },
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 251627827200,
        "free": 202209427456,
        "threshold": 10485760
      }
    }
  }
}
```

Related solr mailing list thread: to https://www.mail-archive.com/solr-user@lucene.apache.org/msg144629.html

**Comment by schuch** [comment]
According to the response on the solr-user mailing ist, this is expected behavior

| `HttpSolrClient` baseUrl points to... | PingRequest| CoreAdminRequest |
| --- | --- | --- |
| context, e.g. `/solr`  | ❌ | ✔️  |
| core, e.g. `/solr/techproducts`| ✔️  | ❌ |

I think there is no way to tell, if the base URL is actually points to the context or the core when when looking at a `SolrClient` bean.

What about making the kind of check configurable through `SolrProperties`?

**Comment by philwebb** [comment]
See also #8463 for some background on the last change we made in this area.

**Comment by schuch** [comment]
I am proposing trying to fallback to `ping()` if the CoreAdmin request fails due to a 404, although I'm not really happy with that. But I see no other way.

https://github.com/spring-projects/spring-boot/pull/16477

**Comment by christophstrobl** [comment]
The `SolrClientBuilder` defines two ways for setting up the `SolrClient`. 
One is by pinning the `SolrClient` to a specific core. 

> A path pointing directly at a particular core
> ```java
>   SolrClient client = builder.withBaseSolrUrl("http://my-solr-server:8983/solr/core1").build();
>   QueryResponse resp = client.query(new SolrQuery("*:*"));
> ```
> Note that when a core is provided in the base URL, queries and other requests can be made without mentioning the
> core explicitly.  However, the client can only send requests to that core.``

Spring Data for Apache Solr infers the _core_ from the domain type and therefore needs the root Solr path using the extended flexibility the `SolrClient` provides by being able to send requests to any core.

> The path of the root Solr path ("/solr")
> ```java
>   SolrClient client = builder.withBaseSolrUrl("http://my-solr-server:8983/solr").build();
>   QueryResponse resp = client.query("core1", new SolrQuery("*:*"));
> ```
> In this case the client is more flexible and can be used to send requests to any cores.  This flexibility though
> requires that the core is specified on all requests.

Using the Spring Data domain model to identify all possible collections may check cores that are actually never loaded or ever used. 
Reading available cores from Apache Solr itself requires a _core admin_ request anyway. Bottom line, I would rather keep it the way it is.

**Comment by schuch** [comment]
What about users who do not use Spring Data Solr, but SolrJ directly, which is the case in my scenario?

**Comment by christophstrobl** [comment]
@schuch I just had a look at the sample project you referenced, which was using the `SolrTemplate`. Sorry for false assumption. As you've already mentioned one cannot judge which option has been used to create the `SolrClient`. 
Maybe it would be feasable to try hit the `admin/ping` endpoint if the core request fails, just to cover both scenarios.

**Comment by snicoll** [comment]
Closing in favour of PR #16477
