### ISSUE TITLE
configuration processor not working

### ISSUE THREAD

**Issue by iPhotoner** [spring-projects/spring-boot#16257]
hi,i am using spring boot 2.1.3,custom property via configuration processor,
Expecting a 'String' but got a 'Mapping' node,it works fine such as server.serverlet.context-path
it works on previous version such as boot 2.0.3

environment:
Eclipse IDE for Java Developers
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
Sts 4.10 Plugin

@see https://github.com/iPhotoner/demonstration-repository.git demo-configuration-processor
what's wrong with it,thank you!

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem is that you have defined `cp` as a string property in your additional metadata.

**Comment by iPhotoner** [comment]
i remove /META-INF/additional-spring-configuration-metadata.json,
yes,it works now,add this json file cause there will be a yellow underline on String property,
so i add it hand-actuated.thank you,@wilkinsona
