### ISSUE TITLE
Spring Boot: @ConditionalOnMissingBean seems to prevent expected bean instantiation 

### ISSUE THREAD

**Issue by chrismerrill1974** [spring-projects/spring-boot#1625]
I'm developing a framework / example application based on Spring Boot, Spring Boot Actuator, and Spring HATEOAS.

I would like to use the @ConditionalOnMissingBean annotation to mark a number of component scanned classes as replaceable by classes that framework users develop... I would expect that they would name their overriding beans the same thing as the beans I've declared. This doesn't seem to work as I expect, and I'm wondering if its a bug or not.

Here are the details and an example of what the problem appears to be. I've provided an example you can download from github (link below) that illustrates the problem (that is, if it is a problem and not a misunderstanding on my part).

For Spring Boot v1.1.2.RELEASE:
The documentation states:
@Conditional annotations are processed when @Configuration classes are parsed. Auto-configure @Configuration is always parsed last (after any user defined beans), however, if you are using these annotations on regular @Configuration classes, care must be taken not to refer to bean definitions that have not yet been created.
In the context of a java package that will be component scanned on startup, it doesn't appear that the following bean will be loaded, even though I would expect it to be, since the name is unique.

```
    @ConditionalOnMissingBean("ServiceA")
    @Component("ServiceA")
    public class ServiceA { ...}
```

Whereas,

```
    @Component("ServiceB")
     public class ServiceB { ...}
```

will be loaded.

I have forked the gs-spring-actuator example and created demo code. If you build the following project in gradle, and check out the spring-boot-actuator "beans" status page (http://localhost:9001/beans) after starting the app, you'll see that ServiceA doesn't appear in the bean listing, whereas ServiceB does.

https://github.com/chrismerrill1974/spring-boot-issue-example

**Comment by chadsandquist1** [comment]
Could you add an option to @springbootapplication or @componentscan that would fail startup if @conditionalOnMissingBean are scanned on startup?
