### ISSUE TITLE
@WebFluxTest Doesn't Import the ErrorWebFluxAutoConfiguration

### ISSUE THREAD

**Issue by alimate** [spring-projects/spring-boot#16258]
Synopsis
---
As I was experimenting with the `@WebFluxTest`s to test Reactive controllers, I noticed that the provided test _auto-configurations_ do not import the default `ErrorWebExceptionHandler`, so the following test would fail:
```java
@AutoConfigureErrors
@RunWith(SpringRunner.class)
@WebFluxTest(PersonController.class)
public class ReactiveWebApplicationTests {

    @Autowired private WebTestClient webClient;

    @Test
    public void personName_CanNotBeBlank() {
        webClient.post().uri("/persons")
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .syncBody("{}")
                .exchange()
                .expectStatus().isBadRequest()
                .expectBody()
                    .jsonPath("$.errors[0].code").isEqualTo("name.blank");
    }
}
```

This can be easily fixed just by importing the `ErrorWebFluxAutoConfiguration`:
```java
@AutoConfigureErrors
@RunWith(SpringRunner.class)
@WebFluxTest(PersonController.class)
@ImportAutoConfiguration(ErrorWebFluxAutoConfiguration.class)
public class ReactiveWebApplicationTests {

    @Autowired private WebTestClient webClient;

    @Test
    public void personName_CanNotBeBlank() {
        webClient.post().uri("/persons")
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .syncBody("{}")
                .exchange()
                .expectStatus().isBadRequest()
                .expectBody()
                    .jsonPath("$.errors[0].code").isEqualTo("name.blank");
    }
}
```

Suggestion
---
Although the problem is so easy to fix, that'd be great if we import the default auto-configuration automatically. For example by adding an `AutoConfigureErrorWebFlux` annotation.

Related Issues
---
Apparently supporting `WebExceptionHandler`s was added in #13627 but the default auto-configuration is missing from the `WebFluxTest`.

**Comment by wilkinsona** [comment]
Well spotted. This seems like a bug to me, particularly as `@WebMvcTest` imports the equivalent auto-configuration for the servlet stack. Do you agree, @bclozel?

**Comment by bclozel** [comment]
Yes, we should align with our existing MVC setup here.

**Comment by alimate** [comment]
@bclozel @wilkinsona May I provide a PR to fix that?

**Comment by wilkinsona** [comment]
@alimate Yes, please. That would be much appreciated.

**Comment by mbhave** [comment]
Closing in favor of PR #16266.
