### ISSUE TITLE
Do we plan to support GraalVM with native image like Spring Framework Planned？

### ISSUE THREAD

**Issue by guanchao-yang** [spring-projects/spring-boot#16261]
Do we plan to support GraalVM with native image like Spring Framework Planned？ 

Spring [GraalVM](https://www.graalvm.org/) Issues ： https://github.com/spring-projects/spring-framework/issues?utf8=✓&q=GraalVM

**Comment by wilkinsona** [comment]
Thanks for your interest but, as mentioned in the guidelines for contributing, we prefer to use issues only for bugs and enhancements. A question like to is better-suited to Gitter.

With that said, yes, we do plan to support Graal. Support will largely come from Spring Framework with few, if any, changes to be made in Spring Boot. [Spring Fu](https://github.com/spring-projects/spring-fu) may be of interest as well as issues [Graal issues in this repository](https://github.com/spring-projects/spring-boot/issues?utf8=✓&q=label%3A%22theme%3A+graal%22+).
