### ISSUE TITLE
spring.redis.cluster.max-redirects is ineffective 

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#16271]
spring.redis.cluster.max-redirects  is ineffective when user the LettuceConnectionFactory, This value is always the default 5

**Comment by snicoll** [comment]
@brucelwl thanks for the report but @mp911de just confirmed this was an issue in Spring Data Redis, see [DATAREDIS-949](https://jira.spring.io/browse/DATAREDIS-949).

**Comment by mp911de** [comment]
As workaround: Configure yourself `ClusterClientOptions` with the appropriate `maxRedirects` value and apply it through `LettuceClientConfigurationBuilderCustomizer` .

**Comment by brucelwl** [comment]
@mp911de Thank you for your reply. this is a solution, but I still hope to modify this bug.
