### ISSUE TITLE
Add actuator support for RSocket

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#16282]
Since #16021, Spring Boot supports RSocket as a type of server applications (meaning there's a single RSocket server available and no HTTP server).

We should try and expose actuator endpoints in a meaningful way over RSocket.

**Comment by spencergibb** [comment]
I'm very interested in this as well. It will be interesting to see how this gets done as the routing in Framework is still basic (simple string). Spring Cloud Gateway needs similar functionality.

**Comment by philwebb** [comment]
I think we might run out of time for this one. I'm going to move it to 2.x for now (@bclozel feel free to move back if you have something in hand already).

**Comment by spencergibb** [comment]
@bclozel I'd like to chat with you about it. Gateway needs something like this and I'd like to be not far off when I implement it there.

**Comment by bono007** [comment]
@bclozel I would love to help out on this one.

**Comment by bclozel** [comment]
@snicoll and I are looking into this issue. We've discussed with the Framework team about this and it seems that:
* there are a lot of open questions still about conventions and best practices when it comes to routes and RSocket interaction models
* we're missing critical infrastructure in Spring Framework to support this, and this might be considered at the same time as a possible functional programming model as well.
* we need to learn more about the use cases behind this and what other pieces would be missing to provide a complete support (we'll get in touch with @spencergibb for that)

We're pushing it back to 2.x as 2.3 will be based on Spring Framework 5.2 and we won't have time to cover all this in the next release.

**Comment by AxelHeathnet** [comment]
Is this still open?

**Comment by bclozel** [comment]
@AxelHeathnet yes

**Comment by peter-natkaniec** [comment]
Any progress ?

**Comment by bclozel** [comment]
@peter-natkaniec not yet - we suspect we'll need more infrastructure from Spring Framework itself, but we need to work on drafting this support first. We're looking at the number of votes on issues to prioritize work.

**Comment by tomasz-galuszka** [comment]
Looks like a big blocker for going into production without monitoring (I mean prometheus/grafana stack). Are there any other ways for monitoring r-socket based micro-services ?

**Comment by PPrydorozhnyi** [comment]
any news please?

**Comment by bclozel** [comment]
We haven't made much progress on this and the demand is quite low compared to many other feature requests. I'm closing this issue for now. We can reconsider this decision depending on the number of votes on this issue.
