### ISSUE TITLE
Undocumented differing behavior between ErrorPageFilter and JettyEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by lheadden** [spring-projects/spring-boot#1629]
When running as a deployed WAR, ErrorPageFilter is used as a ConfigurableEmbeddedServletContainer instead of JettyEmbeddedServletContainerFactory. 

When ErrorPageFilter handles an error, it does not re-invoke the filter chain. This means that error pages cannot use the SecurityContext and similar filter-defined values. This differs from the way in which JettyEmbeddedServletContainerFactory does this which allows the use of these values on the page.

This may be intended behaviour but it should probably be documented as discovering why this occurs takes some time. 

Using Spring Boot 1.1.6RELEASE on Jetty 9.2.1.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
