### ISSUE TITLE
2.2.x has no htmlsingle documentation variant anymore.

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#16295]
Since version 2.2.x, the spring boot documentation has no `htmlsingle` variant anymore.

This will cause all links across the web pointing to `https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/` to break, once 2.2.0 goes GA.

I propose to put a placeholder `index.html` under `reference/htmlsingle/` which either redirects to the new documentation or shows at least a nice information about the fact that the documentation has changed (instead of a basic 404 error page)

**Comment by jnizet** [comment]
Losing the htmlsingle would be really sad. It's extremely useful to be able to Ctrl-F in the complete documentation to find what we want.
