### ISSUE TITLE
Invoke the init() method repeatedly after implementing the Filter interface if the filter's name is self-defined

### ISSUE THREAD

**Issue by LannyYao** [spring-projects/spring-boot#16297]
Spring boot version: 1.5.16.RELEASE
dependency: 'org.springframework.boot:spring-boot-starter-web'

Like the code below, there is a SimpleFilter class and I define the filter name as 'myFilter' in the WebFilter annotation. And then when I run the application, I find that the init() method is invoked twice. And also, the same as doFilter() method when request arrived.

After investigating, I found that there will be 2 filters with the same type which has been registered in the filter list, one is 'simpleFilter' and another is 'myFilter'. As a result,  this filter with such type will be invoked twice. Only if there is no customized filter name or make it same with the bean name of this instance can it be invoked only one time.
```java
@Slf4j
@Component
@WebFilter(urlPatterns = {"/api/filter/*"}, filterName = "myFilter")
public class SimpleFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        log.warn("SimpleFilter init()");
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException { }

    @Override
    public void destroy() {}
}
```

**Comment by wilkinsona** [comment]
With only a single class to look at it is difficult to be certain, but I suspect that `SimpleFilter` is being found by both normal component scanning and `@ServletComponentScan`. Given your use of `@WebFilter` you could remove `@Component`. Alternatively you could remove `@WebFilter` and use a `FilterRegistrationBean` to configure its name and patterns.

I am going to close this issue as there is no evidence of a bug in Spring Boot. If my guess above is incorrect, please take the time to provide a complete example that reproduces the problem and we can re-open this issue and take another look.
