### ISSUE TITLE
Using @SpyBean with @Qualifer does not work in Spring 1.5.x

### ISSUE THREAD

**Issue by dome313** [spring-projects/spring-boot#16292]
Hello all
In the Spring boot docs [here](https://docs.spring.io/spring-boot/docs/1.5.19.RELEASE/api/org/springframework/boot/test/mock/mockito/SpyBean.html) it says

> If there is more than one bean of the requested type, qualifier metadata must be specified at field level: 
```
     @SpyBean
     @Qualifier("example")
     private ExampleService service;
```

This is not working for me on Spring boot 1.5.19.RELEASE. The simple example is 
```
@SpringBootApplication
public class QualifierspyApplication {
	public static void main(String[] args) {
		SpringApplication.run(QualifierspyApplication.class, args);
	}

	@Primary
	@Bean("simpleService1")
	public SimpleService simpleService1() {
		return new SimpleService("hello 1");
	}

	@Bean("simpleService2")
	public SimpleService simpleService2() {
		return new SimpleService("hello 2");
	}
}
```
The test is 
```
@RunWith(SpringRunner.class)
@SpringBootTest
public class QualifierspyApplicationFailingTest {
	@SpyBean
	@Qualifier("simpleService2")
	private SimpleService simpleService2;

	@Test
	public void testSpy() {
		Assert.assertEquals("hello 2", simpleService2.method());
	}
}
```
The test only works if I put `@SpyBean(name = "simpleService2")`. 
If i remove `@Primary` it fails with
```
java.lang.IllegalStateException: No bean found for definition [SpyDefinition@209da20d name = '', typeToSpy = se.lolotron.qualifierspy.SimpleService, reset = AFTER]
```

You can find the example [here](https://github.com/dome313/Qualifierspy).

**Comment by mbhave** [comment]
Thanks for the sample. This looks like a bug to me. It's probably [this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L313) bit which should look at the qualifier when determining the bean name.

**Comment by rhamedy** [comment]
@mbhave can I work on a fix for this `bug`?

**Comment by snicoll** [comment]
@rhamedy thanks for the offer. We're releasing this Friday and I'd like this to be fixed beforehand. If you have time to propose something in the next 2 days, please go ahead.

**Comment by rhamedy** [comment]
@snicoll I looked into the `determineBeanName` mentioned in the above comment by @mbhave and I could not figure out how to access the `@Qualifier` annotation's value in there. The `SpyDefinition` does not expose anything. 

I also came across this issue https://github.com/spring-projects/spring-boot/pull/11077 and while it's not related to this `bug` it is relating to the `@Primary`. 

I could look into this issue again in the evening (if it won't be too late) and it would be nice to get some help/suggestions.

**Comment by rhamedy** [comment]
I think I have a solution! Basically in the method `determineBeanName` after the check `if (StringUtils.hasText(definition.getName()))` I do the following 

- Loop through the passed beans

- For each bean check if `definition.getQualifier()` is not null 

- Using the `QualifierDefinition.matches(...)` to figure out whether the bean name matches the `Qualifier` value, if true then that's the correct `determined` bean name

- If above step failed to return then it proceeds with normal flow which goes and checks for `@Primary`

Using this solution, the test that is failing in `1.5.x` is passing, I need to do some more checks. The if check using `QualifierDefinition.matches(...)` is a little scary but works. The `determineBeanName` method would look as follow after the fix

```
private String determineBeanName(String[] existingBeans, SpyDefinition definition,
			BeanDefinitionRegistry registry) {
		if (StringUtils.hasText(definition.getName())) {
			return definition.getName();
		}

		for (String bean : existingBeans) {
			if (definition.getQualifier() != null) {
				if (definition.getQualifier().matches(
						(ConfigurableListableBeanFactory) this.beanFactory, bean)) {
					return bean;
				}
			}
		}

		if (existingBeans.length == 1) {
			return existingBeans[0];
		}
		return determinePrimaryCandidate(registry, existingBeans,
				definition.getTypeToSpy());
	}
```
The `for loop` is the new addition? Any feedbacks?

**Comment by mbhave** [comment]
@rhamedy The `determineBeanName` was just my initial hunch. I hadn't looked at it in detail. I just took a look at the code on master and it's been refactored quite a bit following the issue that you've referenced. This isn't a bug in `2.1.x` and master because the qualifier is checked [here](https://github.com/spring-projects/spring-boot/blob/a2d37dc0b9416a03c145cb45c20a27f868d9e920/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L246). 

Let's see if the rest of the team thinks this is worth fixing only for `1.5.x`.

**Comment by rhamedy** [comment]
I noticed the `1.5.x` tag and I also knew that it is working in `master`. The fix that I have is for `1.5.x` (based off it). Sounds good to me, I will push the PR anyway and will leave it to the team to decide what's best 👍

**Comment by wilkinsona** [comment]
Given there's a workaround, I don't think we should fix this in 1.5.x, particularly as it will reach EOL in a little over 4 months' time.

**Comment by philwebb** [comment]
I agree with Andy. We only really want to touch 1.5.x for critical bugs given the limited life it has left.

**Comment by surapuramakhil** [comment]
Hie, I am facing the same problem in version 2.1.7

**Comment by snicoll** [comment]
@surapuramakhil Madhura has [indicated above](https://github.com/spring-projects/spring-boot/issues/16292#issuecomment-476927560) that this should work with `2.1.x`. If you think otherwise, please attach a small sample we can run ourselves and we can reopen this issue.

**Comment by surapuramakhil** [comment]
@snicoll try running the below-mentioned test
https://github.com/surapuramakhil/springBootTestDataJpaIssue/blob/master/src/test/java/com/akhil/demo/SpyQualifierTest.java

If you use mock bean instead of spy then bean qualifier works. but ideally, the qualifier should also be working for SpyBean .
