### ISSUE TITLE
Not possible to use two beans extending MongoConfigurationSupport without allowing bean overriding

### ISSUE THREAD

**Issue by ddoubleday** [spring-projects/spring-boot#16310]
Using Spring Boot 2.1.2 spring-boot-starter-data-mongodb. I would like to do things right and avoid allowing bean overriding, but it won't work if I have two Mongo data sources. 

I extend from Spring Data MongoConfigurationSupport for both my primary and secondary data sources. MongoConfigurationSupport creates internal beans like 
@Bean
public MappingMongoConverter mappingMongoConverter() without any qualification, so if I have two such MongoConfigurationSupport extensions, their internal bean names will conflict. 

I could revert to allowing bean overriding, but that actually seems like a bug that the new default false value has uncovered--these internal beans SHOULDN'T be allowed to override each other.

**Comment by wilkinsona** [comment]
Thanks for the report. I think this is really a usability problem with Spring Data Mongo that's being highlighted by Boot disabling bean overriding.

With bean overriding enabled, you may still run into difficulties as, for example, one `MongoMappingContext` will override the other which will cause problems if they should have had different base packages. Please open a [Data Mongo issue](https://jira.spring.io/projects/DATAMONGO) to see if they can improve the usability here. In the meantime, I believe you can work around the problem by overriding all the `@Bean` methods on `MongoConfigurationSupport` and using the `name` attribute on `@Bean` to provide unique names.
