### ISSUE TITLE
In spring-boot jackson MonthDaySerializer does not serialize objects as JSON array 

### ISSUE THREAD

**Issue by XhstormR** [spring-projects/spring-boot#16335]
Unlike YearMonthSerializer serialize objects as JSON array " [2018, 5]", MonthDaySerializer serialize to "--03-02". I think this may be a spring boot bug.

This link has the smallest reproduction.
https://github.com/FasterXML/jackson-modules-java8/issues/107#issuecomment-476998275

**Comment by wilkinsona** [comment]
This isn't a problem with Spring Boot. It can be reproduced with Jackson alone:

```java
ObjectMapper objectMapper = new ObjectMapper().enable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS).registerModule(new JavaTimeModule());
System.out.println(objectMapper.writeValueAsString(MonthDay.now()));
System.out.println(objectMapper.writeValueAsString(YearMonth.now()));
System.out.println(objectMapper.writeValueAsString(LocalDateTime.now()));
```

The above code will produce output similar to the following:

```
"--03-28"
[2019,3]
[2019,3,28,15,35,59,579000000]
```
