### ISSUE TITLE
Issue in load method of snakeyml

### ISSUE THREAD

**Issue by svaidya401** [spring-projects/spring-boot#16355]
Load method of snakeyml is not able to convert special characters to string.

Yaml yaml = new Yaml();
String filePath = "src\\main\\resources\\application-excel-export-column-mapping.yml";
Reader reader = null;
Map<String, Map<String, Map<String, String>>> options = null;
try {
FileInputStream file = new FileInputStream(filePath);
BufferedReader in = new BufferedReader(new InputStreamReader(file, "UTF-8"));

PrintStream out = new PrintStream(System.out, true, "UTF-8");
in.lines().peek(out::println);
options = (Map<String, Map<String, Map<String, String>>>) yaml.load(in);

**Comment by wilkinsona** [comment]
Thanks for the report, but it doesn't look like it belongs here as the code you've shared above makes no use of Spring Boot. SnakeYAML's issues are tracked on [BitBucket](https://bitbucket.org/asomov/snakeyaml/issues).
