### ISSUE TITLE
spring tech:luckwine-mall:payment system

### ISSUE THREAD

**Issue by worm128** [spring-projects/spring-boot#16366]
程序员ICU救助群:806864360
开源支付系统：https://github.com/guangtong-information/luckwine-mall
程序员ICU救助群:806864360
ELK大数据技术：http://note.youdao.com/noteshare?id=590a28a35c82e1c426386009d62740ef&sub=95f643299a66eaf57f811998145be7a3
spring integration技术分享：http://note.youdao.com/noteshare?id=c85c12270668789a8b6b496a0ba2d5a3&sub=1FBE9F5732F442EAA9A2AD27A015072D

**Comment by wilkinsona** [comment]
Courtesy of Google translate:

> Programmer ICU rescue group: 806864360
Open source payment system: https://github.com/guangtong-information/luckwine-mall
Programmer ICU rescue group: 806864360
ELK big data technology: http://note.youdao.com/noteshare?id=590a28a35c82e1c426386009d62740ef&sub=95f643299a66eaf57f811998145be7a3
Spring integration technology sharing: http://note.youdao.com/noteshare?id=c85c12270668789a8b6b496a0ba2d5a3&sub=1FBE9F5732F442EAA9A2AD27A015072D

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. A GitHub issue isn't an appropriate way to share links such as these.
