### ISSUE TITLE
Username  Support for 5.x and later versions of Couchbase to Spring Data Couchbase 

### ISSUE THREAD

**Issue by enesacikoglu** [spring-projects/spring-boot#16388]
Hello,

Couchbase role-based access for bucket released after version 5.X.But ,there is no configuration support for Spring Data Couchbase auto configuration after couchbase version 5.X takes username for authentication.

Related problem as linked below;

https://stackoverflow.com/questions/47169384/couchbase-bucket-authentication-error

**Comment by snicoll** [comment]
@enesacikoglu if you intend to submit a PR, there is no need to create an issue first.

Duplicates #16389
