### ISSUE TITLE
I am looking forward to the fescar and spring boot, spring cloud integration demo

### ISSUE THREAD

**Issue by yuchonghua** [spring-projects/spring-boot#16391]
I am looking forward to the fescar and spring boot, spring cloud integration demo
---
[Spring boot instance](https://github.com/alibaba/fescar/issues/59)
[Spring boot example](https://github.com/alibaba/fescar/pull/281)
[1.0 approximate time will be released](https://github.com/alibaba/fescar/issues/438)

**Comment by wilkinsona** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
