### ISSUE TITLE
Extend reporting of properties migrator when new and old properties exist

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#16390]
Hi,

I'm currently in the process of migrating some apps to Spring-Boot 2 and of course make use of the `spring-boot-properties-migrator`.

Several of those apps have externally managed application.properties, so I was thinking of adding both new and old properties to that file for the migration phase. By that the old applications would still work as well as the new ones. More specifically, I had the following properties in my file:
```
flyway.enabled=true
flyway.table=schema_version
```
Those should be prefixed with `spring` now. So I did the following to ensure a smooth migration and added both new and old properties:
```
spring.flyway.enabled=true
spring.flyway.table=schema_version
# Remove after migration to Spring Boot 2
flyway.enabled=true
flyway.table=schema_version
``` 

Although having the new properties already, `spring-boot-properties-migrator` still warned me about the old properties being used. Not a big problem really. But then I was thinking: Instead of migrating the old ones always, why not map them to the new ones (at least if their values match). Even without the direct mapping feature I was thinking: I would like to know if there are already new ones available in the file that make the old ones obsolete. 

Would there be value in extending the reporting and/or mapping of `spring-boot-properties-migrator` in cases like that? I have fiddled around already with some ideas in the code and I'm currently at the point where I can get a list of "already configured new properties" and also tried mapping them instead of migrating the old ones. I'm just not sure how the report should look like in those cases. If there is interest in the general idea, I would invest a bit more to figure that out. But I want to gather feedback from you before I invest time in something that seems not worth it.

So what do you think?

Cheers,
Christoph

**Comment by philwebb** [comment]
Having both isn't a scenario we really considered. I guess we figured most people would not need to support two versions at once.

> But then I was thinking: Instead of migrating the old ones always, why not map them to the new ones (at least if their values match).

I think currently there's an additional property source that contains all the migrated values. I have a feeling it's not going to work very well if there's a mix of old and new values. Things can get even more complicated if there are multiple `application.properties` files to consider.

 I'm not sure we should try and deal with any of this in the migrator. Limiting the scope of the migrator to just be "one shot" migration helps to keep things simple from our side. The migrator also adds an overhead to application startup, so I wouldn't really want people to use it long-term.

I'll flag this to see what the rest of the team think. For now, you might be better creating a local fork of the migrator for your specific needs.

**Comment by dreis2211** [comment]
Appreciate the feedback so far. Thanks @philwebb

**Comment by dreis2211** [comment]
> The migrator also adds an overhead to application startup, so I wouldn't really want people to use it long-term.

That's a good point by the way. I wasn't sure if I would just keep it in the dependencies list for future migrations. Maybe some more documentation (in the upgrade guides) would be helpful here, so people remove it after they migrated their apps.

**Comment by wilkinsona** [comment]
I agree with Phil. I don't think we should try to tackle this scenario in the migrator.

> Maybe some more documentation (in the upgrade guides) would be helpful here, so people remove it after they migrated their apps.

The upgrade guide already calls out the following in a note:

> Once you’re done with the migration, please make sure to remove this module from your project’s dependencies.

**Comment by snicoll** [comment]
I agree we shouldn't do this, there's too much danger in being smart and silencing a useful warning. I am going to close this one for now. Thank you for the suggestion.

**Comment by dreis2211** [comment]
@wilkinsona Embarassing - I must have been blind in order to miss this note. Sorry!

Thanks for your input guys. I didn't want to put effort in something you don't find useful.
Cheers,
Christoph
