### ISSUE TITLE
API to check architecture

### ISSUE THREAD

**Issue by desmethans** [spring-projects/spring-boot#16408]
Spring is often used to write **large** applications.
In large applications a good architecture is important.
I propose an API to check the architecture of an Spring project:
-  Are beans not directly, but via interfaces injected in other beans ?
-  Are repository beans only injected in service beans, not directly in controller beans ?
- Do beans have package visibility so that they are invisble in other layers ?
-  ...

These classes can be used in integrations tests.

I imagine an API like this:
First, you need a class to look up the beans you want to inspect:
```
public class BeanFinder {
	public static ArchitectureAssertions beans(Class<?> ... classes) {
		...
	}
	public static ArchitectureAssertions beansInPackage(String packageName) {
		...
	}
	public static ArchitectureAssertions beansInSamePackageAs(Class<?> clazz) {
		...
	}	
}
``` 
Next, ArchitectureAssertions contains methods to check the architecture:
```
public interface ArchitectureAssertions {
	public boolean havePackageVisibility();
	public boolean containOnlyBeansInjectedViaInterfaces();
	public boolean areOnlyViaInterfacesInjectedInOtherBeans();
	public boolean areOnlyInjectedInBeans(Class<?> ... classes);
	public boolean areOnlyInjectedInBeansInPackage (String packageName);
	public boolean areOnlyInjectedInBeansInSamenPackageAs(Class<?> clazz);
	public boolean areNotInjectedInBeans(Class<?> ... classes);
	public boolean areNotInjectedInBeansInPackage (String packageName);
	public boolean areNotInjectedInBeansInSamenPackageAs(Class<?> clazz);
	public boolean haveNoDirectDependenciesOnBeans(Class<?> clazz);
	public boolean haveNoDirectDependenciesOnBeansInPackage(String packageName);
	public boolean haveNoDirectDependenciesOnBeansInSamePackageAs(Class<?> clazz);
	public boolean haveOnlyDependenciesOnBeans(Class<?> clazz);
	public boolean haveOnlyDependenciesOnBeansInPackage(String packageName);
	public boolean haveOnlyDependenciesOnBeansInSamePackageAs(Class<?> clazz);	
}
```
Examples of using this API in an integration test:
``` 
assertTrue(beans(ClientService.class, ProductService.class).havePackageVisibility());
assertTrue(beansInPackage("org.example.app.services").areOnlyViaInterfacesInjectedInOtherBeans());
assertTrue(beansInSamePackageAs(ClientController.class).haveOnlyDependenciesOnBeansInSamePackageAs(ClientService.class));
```
I proposed this originally as a Spring Framework improvement:
[https://github.com/spring-projects/spring-framework/issues/22716](url)
Sam Brannen suggested to propose it here.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. In my opinion, what you have proposed is outside the scope of Spring Boot. Instead, I would recommend using an existing project such as [ArchUnit](https://www.archunit.org). You may also be interested in the work that @odrotbohm has done in his moduliths project [https://github.com/odrotbohm/moduliths].

I'll hold off on closing this in case the rest of the team have a different view.

**Comment by odrotbohm** [comment]
I  second Andy's objections but I highly appreciate the intent. I am happy to see suggestions to add more user controlled rules in [Moduliths](https://github.com/odrotbohm/moduliths) or even Spring specific extensions to ArchUnit. In Moduliths we currently only enforce rules derived from the module conventions but of course we could introduce means to allow users to opt into more fine grained rules.

There's also a [Spring plugin](https://github.com/buschmais/jqa-spring-plugin) for [jQAssistant](https://jqassistant.org) that covers parts of what you're suggesting and even goes a bit further as it knows about method invocations etc.

**Comment by wilkinsona** [comment]
We've discussed this today and are in agreement that it's out of the scope of Spring Boot. Thanks for the suggestion.
