### ISSUE TITLE
Consider dropping PDF versions of Gradle plugin and Actuator endpoints docs

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#16414]
We've removed PDF generation for the docs on `master`. For consistency, we should remove the specific docs for the Gradle plugin and the Actuator endpoints

**Comment by philwebb** [comment]
I'd rather attempt to restore PDFs for everything before we do this.

**Comment by snicoll** [comment]
OK but that relates to single page support more than anything else to me (right now we'd generate one PDF per section). Do we have an issue for that?

**Comment by wilkinsona** [comment]
> Do we have an issue for that?

Yes: https://github.com/spring-projects/spring-boot/issues/16295
