### ISSUE TITLE
Audit Related Bug (@CreatedDate, @LastModifiedDate, etc.) on null Embedded Objects When Saving in MongoDB

### ISSUE THREAD

**Issue by snow-drop** [spring-projects/spring-boot#16426]
Good day. After upgrading to 2.1.3.RELEASE, I encountered a bug and have been thorougly explained here -> https://github.com/gznglor/spring-boot-mongo-bug/issues

I've researched on the net and still can't find any solutions so far.

**Comment by wilkinsona** [comment]
@gznglor Already reported this problem to us. Please see https://github.com/spring-projects/spring-boot/issues/15851 for details. The property lookup problem does not occur in the sample to which you have linked when upgraded to Spring Boot 2.1.2 or 2.1.3. If you are still have a problem with those version of Spring Boot, please open a [Spring Data Commons issue](https://jira.spring.io/projects/DATACMNS) with a new sample that reproduces the problem using the latest version.

**Comment by snow-drop** [comment]
Yes, this still occurs as I encountered it. As @gznglor said in #15851 -> https://github.com/spring-projects/spring-boot/issues/15851#issuecomment-460771818, it still occurs on his complex project.
