### ISSUE TITLE
Liquibase endpoint does not honor custom change log table

### ISSUE THREAD

**Issue by stephanecot** [spring-projects/spring-boot#16442]
Hello,
I am using Spring Boot 2.1.3.
With this, I have a project where I use Liquibase to build my database.
My config is like this:

<pre>
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    check-change-log-location: true
    drop-first: false
    enabled: true
    database-change-log-lock-table: liquibase_database_changelog_lock
    database-change-log-table: liquibase_database_changelog
</pre>

It is working fine.
But, when I used Spring Boot Admin (and so the end point **/actuator/liquibase**), It is not working ==> No datas.
In my log file, I have: 

<pre>
2019-04-03 17:19:01.002  INFO 6 --- [nio-7911-exec-6] liquibase.executor.jvm.JdbcExecutor      : SELECT COUNT(*) FROM portal_partners.DATABASECHANGELOG
</pre>

==> The endpoint doesn't use the config from the spring.liquibase.*** config.

**Comment by snicoll** [comment]
The template has a “do not copy paste” section so please don’t add the issue type. I’ve edited your comment.

**Comment by stephanecot** [comment]
Sorry, I thinked it was for the "all" comment.
