### ISSUE TITLE
Spring boot dev tools not support inject bean's properties that created from bytecode direct 

### ISSUE THREAD

**Issue by BlizzardMulholland** [spring-projects/spring-boot#16445]
[https://stackoverflow.com/questions/55501501/when-project-include-spring-dev-tools-the-spring-beans-created-by-asm-cant-inj](https://stackoverflow.com/questions/55501501/when-project-include-spring-dev-tools-the-spring-beans-created-by-asm-cant-inj)

When project include spring dev tools, the bean that created by ASM dynamically can't inject properties, when remove spring dev tools, anything is OK.

**Comment by wilkinsona** [comment]
To avoid wasting people’s time, let’s keep the discussion in one place.
