### ISSUE TITLE
Feature request: Allow overriding `application.properties` (from starter) inside final app

### ISSUE THREAD

**Issue by sta-szek** [spring-projects/spring-boot#16441]
Hi guys, I will try to make it short.

My problem:
I have few custom starters, some of them with classes, some of them contain only dependencies + application.yaml.
I wish to put some (default) configuration into starter application.yaml file, which can be overridden by final app.

I have tried following:
1. [Put `application.yaml` to `config` dir](https://stackoverflow.com/a/41991876/9198384) and it worked, but as suggested by [next answer](https://stackoverflow.com/a/41985868/9198384) - this is not clean solution. Especially I already have 3 custom starters and will create more of them. Also this solution does not allow me to override properties in application.yaml (inside final app) because of ([link to docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html)):

```
14. Application properties outside of your packaged jar (application.properties and YAML variants).
15. Application properties packaged inside your jar (application.properties and YAML variants).
```
I debugged, when point no. 14 is done, then 15 is skipped.

2. Tried to use:

```
@Configuration
@PropertySource("classpath:/application.yaml")
public class AppConfig {
}
```
inside starter, as described [here](https://stackoverflow.com/a/41985868/9198384) but it did not work (properties from starter were not taken into consideration at all). Also the solution is not compliant for me because my starter does not contain any classes, and I would like to keep it simple (if possible)

3. Third way is to use `Default properties (specified by setting SpringApplication.setDefaultProperties).`, however I dont want to read properties manually (from starter) and set them as default in each microservice, it's not scalable at all, because everytime i wish to use new starter i have to read properties and set them as default.

Feature description:
```
String args[] = {"overrideProperties=true"};
SpringApplication.run(POCApplication.class, args);
```
or anything similar.

My imagination is that this flag will not stop after point no. 14 and will proceed to point no. 15 (see above), but no further! (in order not to use default properties all the time)

Motivation: I want to keep common config (sleuth config, logbook config, some other default) in starters in order not to maintain configuration hell for microservices

Or is there any other solution for my problem?

----
Question:
When I declare `resources/application.yaml` in any starter and `resources/application.yaml` in final app that is using this starter, then properties from starter are completely omitted. Is it by design? Why?

**Comment by wilkinsona** [comment]
If you want to customise the environment in a starter, you should use an environment post-processor as [described in the documentation](https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#howto-customize-the-environment-or-application-context).

> When I declare resources/application.yaml in any starter and resources/application.yaml in final app that is using this starter, then properties from starter are completely omitted. Is it by design? Why?

Yes, this is by design. In the case you have described, `application.properties` and `application.yaml` files are found via the classpath. This means that the first file that's found wins and any subsequent files are ignored. Finding multiple files with the same name to allow partial overriding would require the entire classpath to be searched which would come at the cost of slower startup and increased complexity.

**Comment by sta-szek** [comment]
Thanks @wilkinsona !
