### ISSUE TITLE
Recursive ConfigurationProperties class doesn't bind recursive properties

### ISSUE THREAD

**Issue by engineal** [spring-projects/spring-boot#16444]
A ConfigurationProperties class with a recursive subclass will not bind the recursive properties. I have tested this with Spring Boot 2.1.3.

This issue can be reproduced using the following application.properties file:
```
test.x.value: "Test1"
test.x.test.value: "Test2"
test.x.test.test.value: "Test3"
```

I would expect this application.properties to be bound to the TestProperties bean as `TestProperties{x=Test{value='Test1', test=Test{value='Test2', test=Test{value='Test3', test=null}}}}`, but Spring is only creating this: `TestProperties{x=Test{value='Test1', test=null}}`

Here is the ConfigurationProperties class (enabled with`@EnableConfigurationProperties({TestProperties.class})`):
```java
@ConfigurationProperties(prefix = "test")
public class TestProperties {

    static class Test {

        private String value;
        private Test test;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public Test getTest() {
            return test;
        }

        public void setTest(Test test) {
            this.test = test;
        }

        @Override
        public String toString() {
            return "Test{" +
                    "value='" + value + '\'' +
                    ", test=" + test +
                    '}';
        }
    }

    private Test x;

    public Test getX() {
        return x;
    }

    public void setX(Test x) {
        this.x = x;
    }

    @Override
    public String toString() {
        return "TestProperties{" +
                "x=" + x +
                '}';
    }
}
```
In addition, the spring boot configuration processor does not support this class, it will throw a StackOverflowException.

See https://stackoverflow.com/questions/52906556/spring-configuration-properties-recursive-type

**Comment by mbhave** [comment]
This was done as stack-overflow protection which is required when binding a bean to a non enumerable source. I wonder if we can allow recursive binding for beans when the source is iterable.

/cc @philwebb

**Comment by snicoll** [comment]
> In addition, the spring boot configuration processor does not support this class, it will throw a StackOverflowException.

What metadata do you expect with such setup anyway? I agree the SO is far from ideal (feel free to create a separate issue for it) but the metadata represents a finite set of information, it's not "dynamic".

**Comment by philwebb** [comment]
I'm not really sure that we should attempt to support such a setup, it feels like we'd be introducing a lot of additional complexity in the binder.

@engineal what kind of data are you trying to represent in your properties?

**Comment by philwebb** [comment]
We've discussed this again today as a team and the general consensus is that we don't want to supported recursive property binding. We can't really see a clear way to implement such a feature without adding a lot of complexity.

@engineal and @Naeramarth, for your specific use-cases I would investigate other binding options. Perhaps using a JSON or XML format might allow you to use other libraries that don't have any recursive binding restrictions.

**Comment by brucelwl** [comment]
@engineal Maybe you can solve your problem by using the extends keyword,
![image](https://user-images.githubusercontent.com/13413715/59555250-366ced80-8fe2-11e9-9a12-195a4f3a60a7.png)
![image](https://user-images.githubusercontent.com/13413715/59555256-4d134480-8fe2-11e9-8c53-37dc2337bee6.png)
![image](https://user-images.githubusercontent.com/13413715/59555261-5b616080-8fe2-11e9-8077-289dcdbfdaeb.png)
![image](https://user-images.githubusercontent.com/13413715/59555286-a11e2900-8fe2-11e9-8520-54eb86e589ad.png)
