### ISSUE TITLE
Spring Boot Maven Plugin adds version to JAR filename

### ISSUE THREAD

**Issue by mpalourdio** [spring-projects/spring-boot#16457]
Hello,

I have just updated from Spring Boot 2.1.3 to 2.1.4. We heavily use spring-boot-maven-plugin to build executable jar. Before 2.1.4, we were able to build jar whose file name did not contain the project version with this configuration :

```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>true</executable>
                    <finalName>${project.artifactId}</finalName>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

From 2.1.4,  the generated jar always contain the version (ex : **myapp.2.1.0-SNAPSHOT.jar**), what breaks our CI. Before, it would always have been **myapp.jar** with this configuration.

I didn't see anything relevant in the changelog about this.

Thanks for feedback.

**Comment by mpalourdio** [comment]
Looks related to this : https://github.com/spring-projects/spring-boot/issues/16202

**Comment by snicoll** [comment]
@mpalourdio the `finalName` attribute is read-only (and therefore not advertized in the doc) as of Spring Boot `2.1.0.M1`, see #12608 - It's a mystery to me why Maven would allow you to set the value anyway. This should have been done as part of the upgrade to `2.1.0` but it looks like you're all set now.

**Comment by mpalourdio** [comment]
Thanks for feedback, I had totally missed this change !
