### ISSUE TITLE
StackOverflow in ConfigurationProcessor during Gradle build

### ISSUE THREAD

**Issue by davidbilge** [spring-projects/spring-boot#16451]
In a Gradle project using Spring Boot 2.1.3, I tried upgrading to Spring Boot 2.1.4. The build failed with a `StackOverflowError` (2.1.3 works fine).

This is on macOS 10.14.4, with JDK 11.0.2 and Gradle 5.3.

[stacktrace.txt](https://github.com/spring-projects/spring-boot/files/3042090/stacktrace.txt)

Plugins in my `build.gradle` that might be relevant:
* `org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}`
* `io.spring.gradle:propdeps-plugin:0.0.10.RELEASE`
* `id "io.spring.dependency-management" version "1.0.7.RELEASE"`.

**Comment by snicoll** [comment]
@davidbilge We need the `@ConfigurationProperties` annotated class that lead to this error please. If you can share a small sample we can run that would be ideal.

**Comment by davidbilge** [comment]
Is there any way I can share the class with you privately?

**Comment by snicoll** [comment]
That's a regression introduced by #15850  - Yes, feel free to send the sample by email (snicoll at pivotal dot io)

**Comment by davidbilge** [comment]
I just sent you a mail.

**Comment by snicoll** [comment]
Alright, this can be reproduces with a nested property, something like

```
pubic class MyGroup<T extends Enum<T>> { ...}
```

And said type used in a configprops type

```
@ConfigurationProperties("test")
public class MyConfig {

  @NestedConfigurationProperty
  private MyGroup<MyEnum> group = new MyGroup<>();
}
```

@davidbilge even if that arrangement did not trigger any sort of error, advanced generics are not supported and the generated metadata in previous versions was useless to your IDE as it was simply adding the generic type (here `T`).

I am not going to see how I can avoid the cycle but it's very much likely to write the same as in `2.1.3` and therefore no proper assistance will be provided.

**Comment by davidbilge** [comment]
Okay, I was not aware of that limitation. Using this hint I should be able to implement a workaround.
