### ISSUE TITLE
Using RestClientTest and DataJpaTest in one test leads to error spring 2.1.3

### ISSUE THREAD

**Issue by ravin-singh** [spring-projects/spring-boot#16455]
In one of the test I am using RestClientTest and DataJpaTest since spring 2.1.3 it doesn't work due to following error. How to solve this?

```
java.lang.IllegalStateException: Configuration error: found multiple declarations of @BootstrapWith for test class [x.y.z.Test]: [@org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.autoconfigure.web.client.RestClientTestContextBootstrapper), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTestContextBootstrapper)]
```

**Comment by ravin-singh** [comment]
Code: 
@RestClientTest({Service.class})
@DataJpaTest
class Test {

**Comment by snicoll** [comment]
Slice tests never were supposed to be combined, please see [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-tests).

In the future, ask such question on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
