### ISSUE TITLE
Restore indentation in published spring-boot-dependencies and spring-boot-starter-parent poms

### ISSUE THREAD

**Issue by KingBuzzer** [spring-projects/spring-boot#16466]
The POMs in 2.1.4 lost all formatting/indentation which makes them harder to read. 

Examples:

2.1.3 is using 4 spaces indentation:
https://search.maven.org/remotecontent?filepath=org/springframework/boot/spring-boot-dependencies/2.1.3.RELEASE/spring-boot-dependencies-2.1.3.RELEASE.pom

2.1.4 is using no indentation
https://search.maven.org/remotecontent?filepath=org/springframework/boot/spring-boot-dependencies/2.1.4.RELEASE/spring-boot-dependencies-2.1.4.RELEASE.pom

No biggie of course :-) Thanks for a great framework!

**Comment by wilkinsona** [comment]
Thanks for spotting this, it wasn't intentional. The good news is that the indentation is missing in the snapshot repo (for example https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-dependencies/2.1.5.BUILD-SNAPSHOT/spring-boot-dependencies-2.1.5.BUILD-SNAPSHOT.pom), so the indentation is being lost somewhere that should be in our control, rather than on the way to Maven Central.

**Comment by songxinqiang** [comment]
By the way, i found in `<artifactId>spring-boot</artifactId>` use 2 spaces to indentation,but in `<artifactId>spring-boot-dependencies</artifactId>` use 4 spaces to indentation.
Can we use 4 space in all pom files?

**Comment by wilkinsona** [comment]
@songxinqiang Where did you find this difference?

**Comment by wilkinsona** [comment]
Curiously, the problem doesn't seem to affect every pom. For example, the pom for `spring-boot` is fine (https://repo.spring.io/snapshot/org/springframework/boot/spring-boot/2.1.5.BUILD-SNAPSHOT/spring-boot-2.1.5.BUILD-SNAPSHOT.pom).

**Comment by wilkinsona** [comment]
I think I see what @songxinqiang was getting at. In 2.1.3, `spring-boot` is indented with 2 spaces but `spring-boot-dependencies` is indented with 4 spaces. In 2.1.4, `spring-boot` is still indented with 2 spaces but `spring-boot-dependencies` is no longer indented.

**Comment by philwebb** [comment]
We have another one of these in `spring-boot-starter-parent`.

**Comment by songxinqiang** [comment]
> I think I see what @songxinqiang was getting at. In 2.1.3, `spring-boot` is indented with 2 spaces but `spring-boot-dependencies` is indented with 4 spaces. In 2.1.4, `spring-boot` is still indented with 2 spaces but `spring-boot-dependencies` is no longer indented.

yeah, I found a different number of indented spaces in different files.
