### ISSUE TITLE
Upgrading from 2.0.5 to anything higher results in application never finishing startup

### ISSUE THREAD

**Issue by dillius** [spring-projects/spring-boot#16479]
Attempting to start back on an older project I haven't worked on in a while, and attempting to upgrade to a newer spring boot release results in a non-start. No errors are logged, and trying to debug has led me nowhere.

It appears that for some reason my routing configuration is completely ignored, and the application never starts to listen on 8080. 

I have tried going from 2.0.5 to 2.0.6, 2.0.9, and to 2.1.4. All have the same result on startup, which I have attached logs for.

I could not find anything in the 2.0.6 release notes that seemed to relate. If I try to go as far as 2.1.4 I do have very obvious issues with bean overriding no longer being enabled by default and my application conflicting, so possibly even the 2.0.X problems are related to this symptom?

[successful_2_0_5_startup.log](https://github.com/spring-projects/spring-boot/files/3050791/successful_2_0_5_startup.log)
[failed_2_0_9_startup.log](https://github.com/spring-projects/spring-boot/files/3050792/failed_2_0_9_startup.log)

**Comment by snicoll** [comment]
Sharing the logs is nowhere near enough to be able to help you. Can you share a sample that reproduces the problem you're experiencing (a zip file or a link to a github repo we can run ourselves would be ideal).

**Comment by dillius** [comment]
I believe I have determined the cause, and it relates to another issue: 

https://github.com/spring-projects/spring-framework/issues/20904

My security setup involved blocking a publisher to pull information from a reactive repository for user information, then manipulate it, during the creation of a Bean. Starting in 2.0.6 this apparently is no longer valid, and the thread will simply block waiting forever for that repository.

I am going to have to redo my security setup such that no blocking is required.

Can just leave this issue here in case another user comes across it.

**Comment by snicoll** [comment]
I was actually suspecting something like that. Glad you figured it out.

The issue isn't going anywhere.
