### ISSUE TITLE
Integrated support for AJP connector on tomcat

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#1647]
It would be handy to have predefined configuration constants to enable an AJP connector, as for server.ssl configuration variables.
The most important one would be "server.ajp.port", that when present would create a default AJP connector on the provided port number.
Other variables as defined by the configuration (the reference is here: https://tomcat.apache.org/tomcat-8.0-doc/config/ajp.html) would be for example:

```
server.ajp.protocol
server.ajp.secure
server.ajp.URIEncoding
server.ajp.acceptCount
server.ajp.maxThreads
server.ajp.asyncTimeout
server.ajp.enableLookups
```

etc etc

I know all these options can be configured writing a configuration classes the instantiate the new ad-hoc connector, but the point is to avoid doing that using standard config properties.

**Comment by mmoayyed** [comment]
Wanted to point out that I have done this here:
https://github.com/apereo/cas/blob/master/webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java#L211

Happy to turn this into a PR if needed.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
