### ISSUE TITLE
The Spring boot actuator root endpoint ignore the reverse proxy X-forwaded-prefix header value when building links

### ISSUE THREAD

**Issue by Beennnn** [spring-projects/spring-boot#16492]
When displaying spring boot actuator root endpoint behind a reverse proxy (e.g. Zuul or Kubernetes Ingress), **the actuator root page links does not refer to the reverse proxy caller URL but to the request URL directly**.

Consequently, all actuator endpoints are broken.

When inspecting the code in method WebMvcEndpointHandlerMapping.WebMvcLinksHandler.links() : it confirms the method uses the request URL:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/servlet/WebMvcEndpointHandlerMapping.java#L81

> request.getRequestURL().toString()

I think it should use:

> ServletUriComponentsBuilder.fromServletMapping(request)

 as done in ServletUriComponentsBuilder :

https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/support/ServletUriComponentsBuilder.java#L154

**Comment by philwebb** [comment]
Do you have the `server.use-forward-headers` property set to true (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server) or the `ForwardedHeaderFilter` installed?

Usually those take care of transparently modifying calls to `getRequestURL()`.

**Comment by Beennnn** [comment]
I have the ForwardedHeaderFilter installed : I see the request is wrapped to a ForwardedHeaderRemovingRequest removing the X-forwarded headers from the getHeaders() method.

I confirm the other calls building Hateoas links do work as expected, so I think it is a bug specifically related to the actuator main page, due to the change I suggest to be made in the code.
I use Spring Boot actuator version 2.1.3. Do you expect me for an additional test or to patch the code as proposed to confirm it solves the issue ?

**Comment by philwebb** [comment]
@Beennnn Are you seeing `ForwardedHeaderExtractingRequest` also being used, or do you have `removeOnly` set to `true`?

If you have a sample that we can run that recreates the issue that would be very useful.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Beennnn** [comment]
I attached a simple use case:
[test-actuator.zip](https://github.com/spring-projects/spring-boot/files/3099172/test-actuator.zip)

This projects exposes **a "/hello" endpoint displaying two way of extracting the caller url**:
- using **request.getRequestURL()** as done in WebMvcEndpointHandlerMapping
- using **ServletUriComponentsBuilder.fromServletMapping()** as it should be

It also exposes **a endpoint "/callHello" calling /hello with x-forwarded headers**.

**Only the call to  ServletUriComponentsBuilder.fromServletMapping() works, taking into account the x-forwarded headers.**

Process:
1. Compile using Maven
2. Run the HelloWorld application. The server starts on localhost:8080
3. Call the URL http://localhost:8080/callHello.

It displays:
> result of call: value http://localhost:8080/hello should be equal to http://host:1234/prefix/hello

It you call http://localhost:8080/callActuator you also notice that actuator does not take into account the x-forwarded headers. When fixed, it should prefix all links with host:1234/prefix"

Notice: `server.use-forward-headers=true` is set with no effect

The code of the controller:
```
@Controller
public class HelloWorldController {	
    private static final String URL_BASE = "http://localhost:8080";
    private static final String HELLO_PATH = "/hello";
    private static final String ACTUATOR_PATH = "/actuator";

    @GetMapping(HELLO_PATH)
    @ResponseBody
    public String sayHello(HttpServletRequest request) throws MalformedURLException {
    	//extract URL as done in WebMvcEndpointHandlerMapping
    	//see https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/servlet/WebMvcEndpointHandlerMapping.java#L81
		String urlWithoutContext = request.getRequestURL().toString();
		
		//extract URL as it should be, taking into account the Forwarded prefix headers
		ServletUriComponentsBuilder fromServletMapping = ServletUriComponentsBuilder.fromServletMapping(request);		
		URL urlWithContext= fromServletMapping.path(HELLO_PATH).build().toUri().toURL();
        return "value "+urlWithoutContext+" should be equal to "+urlWithContext;
    }

	@GetMapping("/callHello")
	@ResponseBody
	public String callHello() {
		
		return remoteCallWithForwardedPrefix(URL_BASE+HELLO_PATH);
	}
    
	@GetMapping("/callActuator")
	@ResponseBody
	public String callActuator() {
		
		return remoteCallWithForwardedPrefix(URL_BASE+ACTUATOR_PATH);
	}
	

	private String remoteCallWithForwardedPrefix(String url) {
		RestTemplate restTemplate = new RestTemplate();
		
		HttpHeaders headers = new HttpHeaders();
		headers.add("X-Forwarded-Host","host");
		headers.add("X-Forwarded-Port","1234");
		headers.add("X-Forwarded-Prefix","prefix");
		
		HttpEntity<String> entity = new HttpEntity<>(headers);
		ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.GET, entity, String.class);
		return "result of call:\n" + response.getBody();
	}
}
```

**Comment by mbhave** [comment]
Thanks for the sample @Beennnn. The `use-forward-headers` flag configures the container's native support for forward headers, in this case, Tomcat's support. `X-Forwarded-Prefix` doesn't seem to be supported which is why the `use-forward-headers` flag doesn't work in this case. But it is supported by Spring's `ForwardedHeaderFilter` and as you mentioned the `ServletUriComponentsBuilder`.

I was able to get the right links in the `/actuator` response by adding the `ForwardedHeaderFilter` to your sample. It's still not clear why adding the `ForwardedHeaderFilter` didn't work for you. Could you try adding this to your sample and let us know why it doesn't work?

```java
@Bean
public FilterRegistrationBean<ForwardedHeaderFilter> forwardedHeaderFilterFilterRegistrationBean() {
  ForwardedHeaderFilter forwardedHeaderFilter = new ForwardedHeaderFilter();
  FilterRegistrationBean<ForwardedHeaderFilter> bean = new FilterRegistrationBean<>(forwardedHeaderFilter); 
  bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
  return bean;
}
```

**Comment by Beennnn** [comment]
Thanks @mbhave. I confirm adding this to my sample make it work. 👍 

I missed the `bean.setOrder(Ordered.HIGHEST_PRECEDENCE)` instruction when I followed this link when migrating to spring boot 5.1: https://stackoverflow.com/questions/30020188/how-to-configure-spring-hateoas-behind-proxy

This code is not correct:
```java
@Bean
public FilterRegistrationBean<ForwardedHeaderFilter> forwardedHeaderFilter() {
  FilterRegistrationBean<ForwardedHeaderFilter> bean = new FilterRegistrationBean<>();
  bean.setFilter(new ForwardedHeaderFilter());
  return bean;
}
```
So, this is not related to actuator, but to a bad configuration of Spring Boot.
Thanks.
