### ISSUE TITLE
Dependency management is provided for solr-uima which does not exist in 7.7

### ISSUE THREAD

**Issue by Sachpat** [spring-projects/spring-boot#16490]
Hi,

Looks like as a part of https://github.com/spring-projects/spring-boot/issues/16273, you also made 

```xml
<groupId>org.apache.solr</groupId>
<artifactId>solr-uima</artifactId>
```

to also refer to version 7.7.1 as it uses a common version property ${solr.version}. But, as per https://mvnrepository.com/artifact/org.apache.solr/solr-uima, there is no 7.7.1 version for solr-uima and hence the build fails if one refers to this dependency from org.springframework.boot:spring-boot-dependencies:2.1.4. 

Or am I missing something?

**Comment by philwebb** [comment]
Looks like we missed that [UIMA was removed](https://issues.apache.org/jira/browse/SOLR-11694) in 7.5.

**Comment by philwebb** [comment]
Note that we intentionally took the slightly unusual step of jumping from Solr 7.4 -> 7.7.1 in a maintenance release.

**Comment by Sachpat** [comment]
@philwebb thanks for taking care of this.
