### ISSUE TITLE
spring.profiles.include not working properly

### ISSUE THREAD

**Issue by vbansal027** [spring-projects/spring-boot#16493]

**Comment by philwebb** [comment]
Opened in error I assume.

**Comment by vbansal027** [comment]
I am using Spring Boot version 2.0.4. I am trying to build a micro-service type spring boot project. My project structure is as follows : 
-Parent Module (packaging POM)
    -child A (packaging JAR) [application aggregator] {app.prps, app-dev.prps}
    -child B (packaging JAR) [application module 1] {app-B.prps, app-B-dev.prps}
    -child C (packaging JAR) [application module 2] {app-C.prps, app-C-dev.prps}
    -child D (packaging JAR) [database module] {app-D.prps, app-D-dev.prps}

NOTE : application.properties is abbreviated as app.prps

The app.prps file in module A, has spring.profiles.active set to dev.
Now, app-dev.prps file in module A has property spring.profiles.include=app-B-dev.prps,app-C-dev.prps
app-B-dev.prps has property spring.profiles.include=app-D-dev.prps

Now when I run the JAR for aggregator module A from the terminal using the command java -jar -Dspring.profiles.active=dev <jar_name>.jar , spring shows active profiles : dev, app-B-dev, app-C-dev

It is NOT including app-D-dev in profiles.

Where as when I run the module from STS editor, through run as Spring boot App, it DOES include the app-D-dev also.

Could you please help me figure out why is it happening and what I am doing wrong here.
Thank you

**Comment by vbansal027** [comment]
![SpringError](https://user-images.githubusercontent.com/20636236/55747293-8adf7400-5a59-11e9-8d6e-7b48ddd5a0a6.png)

In the above screenshot you can see in active profiles. cst-apihandler, cst-apihandler-localhost, cst-persistence-middleware, cst-persistence-middleware-localhost, these 4 profiles are mentioned in spring.profiles.include for cst-mw-uap-localhost

**Comment by mbhave** [comment]
@vbansal027 It's really hard to tell what's going on from screenshots, especially because the profiles in the screenshots do not match the profiles in your issue description. Please provide a complete, minimal sample that we can run to reproduce the issue.

**Comment by mbhave** [comment]
Actually, I think I know what's going on here. In your example [here](https://github.com/spring-projects/spring-boot/issues/16493#issuecomment-480937531), you've got 

> app-dev.prps file in module A has property spring.profiles.include=app-B-dev.prps,app-C-dev.prps

`spring.profiles.include` shouldn't be the file name but instead the profile name. Profile specific property files work by [appending the profile name to `application-`](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties). If you want a file called `application-B-dev.properties` to be processed, the included profile should be `B-dev`.

**Comment by vbansal027** [comment]
Apologies for the typing mistakes in description. I have included the files correctly as you have mentioned above. Also, as I have mentioned before, the program is running perfectly fine, when it is run as configuration from STS editor. It is only when I run the jar from terminal it fails.

**Comment by snicoll** [comment]
That doesn’t help us unfortunately. Please attach a sample project we can run ourselves (a github repo link or a zip).

**Comment by vbansal027** [comment]
Thank you for addressing the problem. The project I have mentioned in the screenshot is my company's official repo, so I can't share it as it is. But, I will try to create a similar structure in some sample repo to share here.

**Comment by vbansal027** [comment]
[FIXED]
The issue has been fixed. The pom.xml for the child B and child C had the maven <build> plugin in them, for building separate executable JARs. Commenting out the <build> section from their respective pom.xmls, resulted in spring.profiles.include working correctly and including the necessary properties files.

Note : I don't know why this worked. So any explanation regarding this will be appreciated :P

**Comment by snicoll** [comment]
Thanks for the feedback. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask usage questions on StackOverflow or Gitter.
