### ISSUE TITLE
Fix connection timeout configuration for Netty

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#16497]
As of #15385, Spring Boot can configure the server connection timeout for Netty servers.
We're using the `server.connection-timeout` configuration property for that and applying it directly to Netty as a channel option.

In https://github.com/spring-projects/spring-boot/issues/15368#issuecomment-481180205, it seems that `-1` and `0` values don't mean the same thing for Netty:

* `-1` is an illegal value, we should map it to `0` instead as this is the value that disables the connection timeout for Netty
* `0` is not the default value for Netty and it disables the connection timeout. We should instead ignore completely this value and not set anything for Netty

See the [Netty ChannelConfig](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelConfig.java).

**Comment by philwebb** [comment]
Closed in favor of PR #16535

**Comment by izeye** [comment]
Based on @philwebb‘s comment, this seems meant to be closed.
