### ISSUE TITLE
RestartClassLoader can not reload some classes which are used to  override lib packages classes.

### ISSUE THREAD

**Issue by chenqimiao** [spring-projects/spring-boot#16508]
RestartClassLoader can not reload some classes which are used to  override lib packages classes.

**Comment by chenqimiao** [comment]
for example:
There are the following structures in my project
![image](https://user-images.githubusercontent.com/15151483/55866134-4fa48880-5bb2-11e9-8f59-c840be92b105.png)
The AccessControlFilter of picture is used to override the class in org.apache.shiro:shiro-web lib .

and the restartClassLoader can not reload AccessControlFilter class.

**Comment by philwebb** [comment]
It looks like you have local copies of library files. If so, you probably need to configure the restart classloader so that they are excluded. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload

**Comment by chenqimiao** [comment]
thanks!
