### ISSUE TITLE
Spring Config Server - Error while specifying files instead of directories into the configuration

### ISSUE THREAD

**Issue by jyacine** [spring-projects/spring-boot#16501]
Hi,

I'm using the versions above : 

<spring.cloud.version>Greenwich.SR1</spring.cloud.version>
<spring.cloud.config>2.1.1.RELEASE</spring.cloud.config>

While investifgation the source code, I found that an issue in the class : `org.springframework.cloud.config.server.environment.NativeEnvironmentRepository`. The method 

`public Locations getLocations(String application, String profile, String label)`

At line 188, a  check is made to identify if the path is a directory or not =>
```
if (isDirectory(value)) {
       output.add(value);
}
```
The isDirectory method check the conditions above :
```
private boolean isDirectory(String location) {
		return !location.contains("{") && !location.endsWith(".properties")
				&& !location.endsWith(".yml") && !location.endsWith(".yaml");
}
```

But juste before the call if isDirectory, the path is changed like that (line 185):
```
if (!value.endsWith("/")) {
	value = value + "/";
}
```
So we will always have true returned from isDirectory (even if the file is specified)

Best regards,
Yacine

**Comment by spencergibb** [comment]
This is not the config server issue tracker https://github.com/spring-cloud/spring-cloud-config

**Comment by jyacine** [comment]
Ok, sorry for the inconvenience.
