### ISSUE TITLE
Apply UndertowDeploymentInfoCustomizer and UndertowBuilderCustomizer beans automatically

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#16514]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background
Spring Boot provides a number of callback interfaces that can be used to customize the web server. For Undertow, a `UndertowDeploymentInfoCustomizer` can be used to customize an Undertow `DeploymentInfo` and an `UndertowBuilderCustomizer` can be used to customize an Undertow `Builder`.

## Problem
The customizers can be configured via the `addDeploymentInfoCustomizers()` and `addBuilderCustomizers()` methods on the `ConfigurableUndertowWebServerFactory`. This is bit tedious as can be seen from the example below:

```java
@Bean
public WebServerFactoryCustomizer<UndertowServletWebServerFactory> deploymentCustomizer() {
	return factory -> {
	    UndertowDeploymentInfoCustomizer customizer = deploymentInfo -> {
	        WebSocketDeploymentInfo inf = new WebSocketDeploymentInfo();
	        deploymentInfo.addServletContextAttribute(
	            WebSocketDeploymentInfo.ATTRIBUTE_NAME, inf); //sample customizer
	  };
	factory.addDeploymentInfoCustomizers(customizer); 
      };
}
```

Instead, if we applied `UndertowDeploymentInfoCustomizer` and `UndertowBuilderCustomizer` beans automatically, that would simplify the configuration to the following:

```java
@Bean
public UndertowDeploymentInfoCustomizer webSocketCustomizer() {
	return deploymentInfo -> {
            WebSocketDeploymentInfo info = new WebSocketDeploymentInfo();
	    deploymentInfo.addServletContextAttribute(
	        WebSocketDeploymentInfo.ATTRIBUTE_NAME, info);
	}; // example connector customization
}
``` 

## Solution

Beans of both the `UndertowDeploymentInfoCustomizer` and `UndertowBuilderCustomizer` types should be applied automatically to `UndertowServletWebServerFactory` and `UndertowReactiveWebServerFactory`. For `UndertowServletWebServerFactory`, this can be done [here](https://github.com/spring-projects/spring-boot/blob/2112e02edaef75c6b36513d16ac618750f9f1d5f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration.java#L112) and the configuration for the reactive one can be found [here](https://github.com/spring-projects/spring-boot/blob/2112e02edaef75c6b36513d16ac618750f9f1d5f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration.java#L122). 

The `ObjectProvider` interface can be used for injecting a dependency. [Here](https://github.com/spring-projects/spring-boot/blob/2112e02edaef75c6b36513d16ac618750f9f1d5f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration.java#L79) is an example that can be used to inject customizers when there can be 0..n of them.

Tests for the servlet and reactive versions are [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfigurationTests.java) and [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryAutoConfigurationTests.java) respectively.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by SergeyHydra** [comment]
@mbhave Hello! I'm interested in working on this.

**Comment by turackangal** [comment]
Hello @mbhave, I would like to work on this issue

**Comment by bsandoval** [comment]
Hi there, I'm interested too! Otherwise I would love to take the next first-timers-only.

**Comment by mbhave** [comment]
Thanks for your interest everyone. Going by the order of the comments, @SergeyHydra claimed it first. 

@SergeyHydra, We'll look forward to your pull request. Please let us know if you have any questions.

**Comment by SergeyHydra** [comment]
@mbhave ty! I'm starting work on it.

**Comment by SergeyHydra** [comment]
Hello @mbhave! I have done fix for Undertow, but I have question. I look at jetty factory and it has the same problem. What do you think about automatic apply JettyServerCustomizer in JettyServletWebServerFactory?

**Comment by mbhave** [comment]
@SergeyHydra Thanks, that will be a nice addition if you want to take care of it as part of this issue.

**Comment by SergeyHydra** [comment]
@mbhave pr is ready.

**Comment by mbhave** [comment]
Closing in favor of PR #16584.
