### ISSUE TITLE
exposeProxy = true  not  in effect

### ISSUE THREAD

**Issue by dongguabai** [spring-projects/spring-boot#16516]
Sorry, my English is not very good.

**describe:**
I use `@EnableAspectJAutoProxy(exposeProxy = true)`,but I can not get the current AOP proxy by `AopContex.currentProxy()`.

**environment:**
Spring Boot （2.1.4.RELEASE）.

There are only two classes of this project：

```java
@SpringBootApplication
@EnableAsync
@EnableAspectJAutoProxy(exposeProxy = true)
public class DemoTest2Application {

	public static void main(String[] args) {
		SpringApplication.run(DemoTest2Application.class, args);
	}
}
```

```java
@Controller
public class EmailController {

    @RequestMapping(value = "/test", method = RequestMethod.GET)
    @ResponseBody
    public Object asyncCall() throws InterruptedException {
        System.out.println("before....");
        ((EmailController) AopContext.currentProxy()).testAsyncTask();
        System.out.println("after....");
        return "OK";
    }


    @Async
    public void testAsyncTask() throws InterruptedException {
        Thread.sleep(10000);
        System.out.println("异步任务执行完成！");
    }
    }
```

when I  request  "localhost:8080/test" .I get exception:

```java
java.lang.IllegalStateException: Cannot find current proxy: Set 'exposeProxy' property on Advised to 'true' to make it available.
	at org.springframework.aop.framework.AopContext.currentProxy(AopContext.java:69) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
```
**Looking through all kinds of documents, I don't know where I was wrong.**

**Comment by snicoll** [comment]
@dongguabai interesting, that's probably because Spring Boot auto-configures this already. Can you please add `spring.aop.auto=false` to your app and check if that fixes the problem?

**Comment by dongguabai** [comment]
> @dongguabai interesting, that's probably because Spring Boot auto-configures this already. Can you please add `spring.aop.auto=false` to your app and check if that fixes the problem?

Thank you for your reply.
I add `spring.aop.auto=false` ,but the problem is still unsolved.

**Comment by NoviceDian** [comment]
((EmailController) AopContext.currentProxy()).testAsyncTask();这个方法必须要获得当前代理类啊，但是你的testAsyncTask()并没有使用到切面之类的东西，所以就获取不到当前方法的代理类了。。你需要在方法上加上@Transactional之类会形成切面的东西。让他代理到AOP

**Comment by dongguabai** [comment]
> ((EmailController) AopContext.currentProxy()).testAsyncTask();这个方法必须要获得当前代理类啊，但是你的testAsyncTask()并没有使用到切面之类的东西，所以就获取不到当前方法的代理类了。。你需要在方法上加上@transactional之类会形成切面的东西。让他代理到AOP

但是 testAsyncTask() 使用了 @Async 注解啊

**Comment by NoviceDian** [comment]
没用过@async注解，你看看这个注解的实现是用的aop吗？好像不是吧，没有使用到AOP在AOP的上下文就获取不到的吧。

**Comment by dongguabai** [comment]
> 没用过@async注解，你看看这个注解的实现是用的aop吗？好像不是吧，没有使用到AOP在AOP的上下文就获取不到的吧。

本质用的就是 AOP

**Comment by karanb192** [comment]
I'm also facing the same issue.

**Comment by wilkinsona** [comment]
As far as I can tell, there's nothing to tie together the `exposeProxy` setting on `@EnableAspectJAutoProxy` with the proxy creation that's done as a result of `@EnableAsync`. The latter has its own proxy-related attributes but does not have one for proxy exposure. This results in `AnnotationAwareAspectJAutoProxyCreator` having its `exposeProxy` property set to `true` and `AsyncAnnotationBeanPostProcessor` (which creates proxies for classes with `@Async` methods  having its `exposeProxy` property with the default value of  `false`.

**Comment by dngzs** [comment]
What should we do to change the ExposeProxy property of AsyncAnnotationBeanPostProcessor

**Comment by wilkinsona** [comment]
@dngzs Set the `exposedProxy` attribute when you add `@EnableAsync` to your application.

**Comment by dngzs** [comment]
sorry，Can you be more specific? ProxyAsyncConfiguration is not set, how can I cover it?

@Bean(name = TaskManagementConfigUtils.ASYNC_ANNOTATION_PROCESSOR_BEAN_NAME)
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	public AsyncAnnotationBeanPostProcessor asyncAdvisor() {
		Assert.notNull(this.enableAsync, "@EnableAsync annotation metadata was not injected");
		AsyncAnnotationBeanPostProcessor bpp = new AsyncAnnotationBeanPostProcessor();
		Class<? extends Annotation> customAsyncAnnotation = enableAsync.getClass("annotation");
		if (customAsyncAnnotation != AnnotationUtils.getDefaultValue(EnableAsync.class, "annotation")) {
			bpp.setAsyncAnnotationType(customAsyncAnnotation);
		}
		if (this.executor != null) {
			bpp.setExecutor(this.executor);
		}
		if (this.exceptionHandler != null) {
			bpp.setExceptionHandler(this.exceptionHandler);
		}
		bpp.setProxyTargetClass(this.enableAsync.getBoolean("proxyTargetClass"));
		bpp.setOrder(this.enableAsync.<Integer>getNumber("order"));
		return bpp;
	}
I am sorry for your work time.

**Comment by wilkinsona** [comment]
Sorry, I answered too hastily. As I'd already [noted above](https://github.com/spring-projects/spring-boot/issues/16516#issuecomment-496533580) there's no such attribute on `@EnableAsync`.

The code you have quoted above is part of Spring Framework rather than Spring Boot. If you would like to be able to configure the `AsyncAnnotationBeanPostProcessor` that is created to expose the proxies that it creates, please open a [Spring Framework](https://github.com/spring-projects/spring-framework/issues) enhancement request.

**Comment by dngzs** [comment]
Thank you very much for your answer, delay your precious time.

**Comment by IFT8** [comment]
` @Resource
    private AsyncAnnotationBeanPostProcessor asyncAdvisor;

    @PostConstruct
    private void init(){
        asyncAdvisor.setExposeProxy(true);
    }`

**Comment by dngzs** [comment]
> ```
>     @Resource
>     private AsyncAnnotationBeanPostProcessor asyncAdvisor;
> 
>     @PostConstruct
>     private void init(){
>         asyncAdvisor.setExposeProxy(true);
>     }
> ```

hi,This way is definitely not working.Should be implemented using BeanPostProcessor, and inherit the PriorityOrdered interface

**Comment by dongguabai** [comment]
I found that this problem might be related to the version. This problem arises when I use 2.1.4. RELEASE, but it does not arise when I use 2.0.3. RELEASE, for example.

**Comment by nor-deen** [comment]
it seems adding `@EnableAspectJAutoProxy(exposeProxy = true)` to the actual bean works

**Comment by wilkinsona** [comment]
As [noted above](https://github.com/spring-projects/spring-boot/issues/16516#issuecomment-498208538) this needs to be addressed via an enhancement to Spring Framework.

**Comment by yarnping** [comment]
this works for me, set the property manually

---

@Component
public class AsyncBeanFactoryPostProcessor implements BeanFactoryPostProcessor {
    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        BeanDefinition beanDefinition = beanFactory.getBeanDefinition(org.springframework.scheduling.config.TaskManagementConfigUtils.ASYNC_ANNOTATION_PROCESSOR_BEAN_NAME);
        beanDefinition.getPropertyValues().add("exposeProxy", true);
    }
}
