### ISSUE TITLE
spring data elasticsearch entity @field annotation analazer setting

### ISSUE THREAD

**Issue by pgm-rookie** [spring-projects/spring-boot#16517]
In my entity, there's a property named param, max length over 32766. An error will occur when I save data with elasticsearchTemplate, so I configured a property analyzer="ik" on field annotation like below:

    @Field(type = FieldType.Keyword, analyzer = "ik")
	private String param;

But I see ignore_above=256 in ES server:

    "param": {
        "type": "text",
        "fields": {
            "keyword": {
                "type": "keyword",
                "ignore_above": 256
            }
        }
    }

I expect ignore_above value should be 32766 .
My question is how to ignore or cut off this property if data length over 32766 in spring-boot-start-data-elasticsearch, is there any way to configure ?

**Comment by mp911de** [comment]
This isn't a Spring Boot issue. Please file a ticket in https://jira.spring.io/projects/DATAES.

**Comment by snicoll** [comment]
Thanks @mp911de!
