### ISSUE TITLE
Rename spring.reactor.stacktrace-mode configuration property

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#16537]
The hook has been renamed in Reactor for a while now to `Hooks.onOperatorDebug()`.
We should rename this property, as we're not really generating stacktraces.

Should we go with `spring.reactor.operator-debug=enabled` or is there another name we should consider?

@rstoyanchev @smaldini @bsideup

**Comment by rstoyanchev** [comment]
Following closely the naming in Reactor sounds good to me. Could other Hooks be potential candidates to be exposed in the future, and if so perhaps `spring.reactor.hooks.**`?

**Comment by wilkinsona** [comment]
+1 for a `hooks` group, even if we only have a property for a single hook initially.

**Comment by bsideup** [comment]
-1 for a `hook` group. It exposes an implementation detail (we may not use `Hooks` in future and fully replace it with `reactor-tools`, for instance). Also, I don't think there is anything else in `hooks.**` group that makes sense to be enabled in Spring Boot (need to double check)

I would go with something like `spring.reactor.debug=enabled` to turn on the "debug mode", and then leave it up to Reactor what to include in the debug mode.
Otherwise, `spring.reactor.operator-debug.enabled=true` is preferred I guess.

**Comment by bsideup** [comment]
I would also highly recommend to keep "debug" word, otherwise users may accidentally turn it on in production

**Comment by wilkinsona** [comment]
`spring.reactor.debug` sounds good to me. Thanks for the suggestion, @bsideup.

**Comment by bclozel** [comment]
@smaldini @simonbasle @bsideup 
I remember the reactor team mentioning that this feature might be moved out of the reactor-core module. Is that still the case?

**Comment by bsideup** [comment]
@bclozel
we have https://github.com/reactor/reactor-tools now, but our plan is the opposite - to move it to core some day

**Comment by bclozel** [comment]
@bsideup I'm talking about `reactor.core.publisher.Hooks`, which is in Reactor Core at the moment. I remember the reactor team talking about unifying the reactor tooling/debug under reactor-tools.

**Comment by simonbasle** [comment]
@bclozel `Hooks#onOperatorDebug()` is going to be deprecated in 3.3.0.M2, in favor of the implementation of the debug agent, which is in the process of being moved closer to the core (same repo to keep releases in sync, see reactor/reactor-core#1731)

**Comment by simonbasle** [comment]
note the debug agent needs to be manually activated, so the property could ultimately act as the switch for either activating the debug agent (if on classpath) or the `Hooks.onOperatorDebug()` (if not). The hook might be kept around as a last resort for envs where an agent isn't practical, with the deprecation just a way of pointing users in the direction of the agent as the first step.

**Comment by bclozel** [comment]
See #17128 as a follow up issue.
