### ISSUE TITLE
Make it easier to set bufferRequestBody on ClientHttpRequestFactory

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16538]
When using `RestTemplateBuilder` it's currently quite hard to set `bufferRequestBody` on the `ClientHttpRequestFactory`

Without this set we get issues such as https://github.com/spring-io/artifactory-resource/issues/50

**Comment by kstrijbos** [comment]
I would like to have a go at this if possible.

**Comment by philwebb** [comment]
Thanks @kstrijbos, nobody is currently looking at this so feel free if you have the time.

**Comment by philwebb** [comment]
Closing in favor of PR #16972
