### ISSUE TITLE
Complete migration to @Configuration(proxyBeanMethods=false) wherever possible

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#16533]
There are still a few classes to review, see https://github.com/spring-projects/spring-boot/issues/9068#issuecomment-472098792

**Comment by SergeyHydra** [comment]
@snicoll Hello! Can I fix this issue?

**Comment by snicoll** [comment]
@SergeyHydra I don't think so. This issue is vague and was created as a reminder more than anything else. I actually don't know what needs to be done and was waiting for @wilkinsona to comment.
