### ISSUE TITLE
Some syntax in the reference documentation is not highlighted or is missing altogether

### ISSUE THREAD

**Issue by artellador** [spring-projects/spring-boot#16548]
I haven't checked the full PDF but it happens at least on the first 3 parts. It looks like the annotation is not inserted. Look at the attached images:

![SpringAnnotHTML](https://user-images.githubusercontent.com/34487006/56031224-1dfd0000-5d1f-11e9-8b25-32502290ffaf.png)
![springAnnotPDF](https://user-images.githubusercontent.com/34487006/56031225-1dfd0000-5d1f-11e9-80d0-b39a7e9ded44.png)

**Comment by wilkinsona** [comment]
1.5.19 does not have the problem but 1.5.20 does. I would guess this is a regression caused by the URL cleanup changes.

**Comment by wilkinsona** [comment]
The syntax highlighting in the HTML documentation is also affected, although it isn't as bad. In the HTML case the styling of the text is lost but the text is still visible.

**Comment by dreis2211** [comment]
May I ask how you found the root-cause of this, @wilkinsona ? I was looking into this one as well actually today, but didn't see an obvious reason  ;)

**Comment by wilkinsona** [comment]
Once I'd figured out it was ok in 1.5.19 and broken in 1.5.20, I suspected the URL cleanup changes as it felt similar to https://github.com/spring-projects/spring-boot/issues/16466. That led to me looking at the changes made to the XSL for PDF generation. Thankfully, the only recent change was the switch from `http://xslthl.sf.net` to `http://xslthl.sourceforge.net/` so there wasn't too many things to try.

**Comment by dreis2211** [comment]
Thanks for the explanation. I assume the Spring-Operator bot would report this again next time and proposes to change the url again, doesn't it?

**Comment by wilkinsona** [comment]
The Bot's inactive now and has been replaced by the [NoHTTP project](https://github.com/spring-io/nohttp/issues/4). I've raised an issue over there.
