### ISSUE TITLE
Debug mode should not be triggered only by the presence of a "debug" env property

### ISSUE THREAD

**Issue by jiahut** [spring-projects/spring-boot#16545]
As soon as  system environment exist the debug variable, the spring boot will  set `springBootLogging` to  `debug`  

It is so freedom

in my case, oneday,  someone executed some program like `shell`, it had been set environment variable  `debug = 1` or `trace` careless.  when restart, it set the springBootLogging to  `debug`.

We can't restrict others from doing so.

I think  set springBootLogging to  `debug` so freedom , it should be added some prefix 

look at `LoggingApplicationListener.java`

```java 
private void initializeEarlyLoggingLevel(ConfigurableEnvironment environment) {
	if (this.parseArgs && this.springBootLogging == null) {
		if (isSet(environment, "debug")) {
			this.springBootLogging = LogLevel.DEBUG;
		}
		if (isSet(environment, "trace")) {
			this.springBootLogging = LogLevel.TRACE;
		}
	}
}
```

**Comment by philwebb** [comment]
This is one part of a broader problem that's discussed in #3450 and I don't think we can change the existing behavior without breaking existing apps. If would be nice if we could offer a quick way to opt-out of picking up those flags from the system environment.

**Comment by philwebb** [comment]
I think we should consider this a duplicate of #3450.

@jiahut If you want a work-around until #3450 is fixed you can do something like the following:

```java
SpringApplication springApplication = new SpringApplication(MyApp.class);
for(ApplicationListener<?> listener: springApplication.getListeners()) {
  if (listener instanceof LoggingApplicationListener) {
    ((LoggingApplicationListener) listener).setParseArgs(false);
  }
}
```

**Comment by jiahut** [comment]
@philwebb  thinks.  +1 for #3450
