### ISSUE TITLE
EmbeddedMongoAutoConfiguration should depend on bean by type

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16540]
Currently the `DependsOnBeanFactoryPostProcessor` beans in  `EmbeddedMongoAutoConfiguration` declare dependencies on a bean named "embeddedMongoServer". The `@Bean` method for `embeddedMongoServer` is `@ConditionalOnMissingBean` so it's possible that that a custom type will mean the name changes and the dependsOn check fails.

Se should probably check against `MongodExecutable.cass` instead.

See #16048 for background.

**Comment by SergeyHydra** [comment]
@philwebb Hello! Is it still actual? Can I try to fix it?

**Comment by philwebb** [comment]
@SergeyHydra Please feel free. The issue is open and not assigned to anyone.

**Comment by ielatif** [comment]
@SergeyHydra @philwebb i submited this PR https://github.com/spring-projects/spring-boot/issues/16627 your thoughts ?

**Comment by ielatif** [comment]
@philwebb @nosan [embedded mongo docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-mongo-embedded) state that :

> You can declare your own IMongodConfig and IRuntimeConfig beans to take control of the Mongo instance’s configuration and logging routing

So in my understanding to customize `embeddedMongoServer` bean one should only customize `IMongodConfig` and `IRuntimeConfig` beans and not create a new custom bean with different name.

If that make sens for you, i think we have to update Embedded Mongo documentation to state that a bean with name `embeddedMongoServer` is mandatory and is customizable via `IMongodConfig` and `IRuntimeConfig`.

Your thoughts ?

**Comment by nosan** [comment]
As for me, if I use a custom bean, I am expecting `@ConditionalOnBean` will be working correctly, but currently, it is failing and from my perspective, it should be handled properly, even more, it is not the only one configuration which can fail. (e.g. `QuartzAutoConfiguration.DataSourceInitializerSchedulerDependencyPostProcessor`)

**Comment by wilkinsona** [comment]
Closing in favour of #16627.
