### ISSUE TITLE
Migrate to MergedAnnotations API

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#16551]
Hi,

there are currently a few deprecation warnings about the usage of AnnotationUtils that should be superseded by the new MergedAnnotations API. I would love to fix them, but it's not really clear how the new way should look like (at least from the docs).

Specifically we're talking about the following methods and what I think could be their potential replacements:

Deprecated | Replacement
------------ | -------------
`AnnotationUtils.getDeclaredRepeatableAnnotations()` | ?
`AnnotationUtils.getRepeatableAnnotations()` | `AnnotatedElementUtils.getMergedRepeatableAnnotations()`
`AnnotationUtils.isAnnotationMetaPresent()` | `AnnotatedElementUtils.hasMetaAnnotationTypes()`
`AnnotationUtils.getAnnotations(AnnotatedElement annotatedElement)` | ?

If you give some general guidance, I can do it on my own and provide a PR. Otherwise you have to do it ;-)

Cheers,
Christoph

**Comment by philwebb** [comment]
There's now a new `MergedAnnotations` interface which most of these can use directly. I'll take a look at these since I wrote most of the new code and it will give me a chance to double check the API works OK.

**Comment by dreis2211** [comment]
Fair enough - thanks.

**Comment by sabareeshkkanan** [comment]
@philwebb I wish this can be part of 2.1.X release. We use following annotation in our custom extension class but in web flux when a exception is thrown it wont set actual message
```
@ResponseStatus(HttpStatus.BAD_REQUEST)
public class RDataException extends RuntimeException
```
This code fixes it but not available yet on 2.1.8

**Comment by philwebb** [comment]
@sabareeshkkanan We can't use `MergedAnnotations` in 2.1.x because it was only introduced in Spring Boot 5.2. If you'd like to raise a new issue and provide a sample application then perhaps we can fix it in another way for 2.1.x.

**Comment by sabareeshkkanan** [comment]
@philwebb Just checking reason is not empty as implemented in following method will work

```

    private String determineMessage(Throwable error) {
        if (error instanceof WebExchangeBindException) {
            return error.getMessage();
        }
        if (error instanceof ResponseStatusException) {
            return ((ResponseStatusException) error).getReason();
        }
        ResponseStatus responseStatus = AnnotatedElementUtils.findMergedAnnotation(error.getClass(),
                ResponseStatus.class);
        if (responseStatus != null && !responseStatus.reason().isEmpty()) {
            return responseStatus.reason();
        }
        return error.getMessage();
    }
```

**Comment by philwebb** [comment]
@sabareeshkkanan I believe that should work. If you have any further questions please ask on stackoverflow.com or gitter.im. If you've found a new bug then please open a new issue.
