### ISSUE TITLE
Independent web server for management

### ISSUE THREAD

**Issue by JigarJoshi** [spring-projects/spring-boot#16552]
I have a use-case where 

- I have a custom RPC server that is started up by command-line runner in spring boot.
- I have application which might need custom RPC server or a web server (typically embedded Tomcat)
 - I expose actuators on web via embedded tomcat on a dedicated port (which is different from the custom RPC server port and different from regular HTTP server port)

Problem

In scenarios where I use custom RPC server I do not need regular HTTP server for RPC but I need it for accessing actuators over the web.

If I specify `management.server.port` different than `server.port` it initializes two instances of embedded tomcat.

Is there a way to turn the regular tomcat instance (one that starts on `server.port`) and only start one for management?

(note: this was raised on stackoverflow, and gitter and basic code inspection was done before posting this ask)

**Comment by spencergibb** [comment]
In similar cases, when nothing but actuator is running on the http port, I've treated it as the management port.

**Comment by philwebb** [comment]
This is not a typical scenario so I'm not sure we've really considered it. Looking at `ManagementPortType.get` I wonder if setting `server.port=-1` and `management.server.port=8081` might work?

**Comment by mbhave** [comment]
#12927 is somewhat related.

**Comment by JigarJoshi** [comment]
@philwebb 
I think with adoption of other non-typical HTTP RPC servers (like gRPC for example) this will be one of the common requirement. With `-1` as `server.port` it fallsback to default server port which is `8080` (for Tomcat)

@spencergibb 
yes keeping both as same is one option (workaround) but the infrastructure is designed to provide port to the process by the type of transport/encoding combination.

@mbhave Yes it is related to https://github.com/spring-cloud/spring-cloud-consul/issues/418 and https://github.com/spring-projects/spring-boot/issues/12927
However solution supplied there isn't applicable here.

I think I will vote on this https://github.com/spring-projects/spring-boot/issues/12927 and we can close this one out.

**Comment by JigarJoshi** [comment]
@philwebb @spencergibb @mbhave could you please re-evaluate https://github.com/spring-projects/spring-boot/issues/12927 and consider re-opening it?

**Comment by philwebb** [comment]
> With -1 as server.port it fallsback to default server port which is 8080 (for Tomcat)

This should not be the case and I can't replicate that locally. Starting a sample application with the following properties:

```
server.port=-1
management.server.port=8081
```

Gives a management port on 8181 and nothing listing on 8080.

> I think with adoption of other non-typical HTTP RPC servers (like gRPC for example) this will be one of the common requirement

I'm not convinced that we need to specifically use the management port for such situations. It's clear why the comments in https://github.com/spring-projects/spring-boot/issues/12927#issuecomment-386012922 wouldn't also apply for RPC applications.

**Comment by JigarJoshi** [comment]
> > With -1 as server.port it fallsback to default server port which is 8080 (for Tomcat)
> 
> This should not be the case and I can't replicate that locally. Starting a sample application with the following properties:
> 
> ```
> server.port=-1
> management.server.port=8081
> ```
> 
> Gives a management port on 8181 and nothing listing on 8080.
> 
> > I think with adoption of other non-typical HTTP RPC servers (like gRPC for example) this will be one of the common requirement
> 
> I'm not convinced that we need to specifically use the management port for such situations. It's clear why the comments in [#12927 (comment)](https://github.com/spring-projects/spring-boot/issues/12927#issuecomment-386012922) wouldn't also apply for RPC applications.

You are right. My bad I had `8080` exposed from some other spring-boot application.

Thank you for quick help here 👍

**Comment by JigarJoshi** [comment]
Is there a way to disable constructing second instance of Tomcat server in such case. Looking at the code I found none.

**Comment by philwebb** [comment]
I don't think so currently as the second instance is required to start the management server. If you don't want that then I'd suggest just exposing the actuator via the primary server.

**Comment by JigarJoshi** [comment]
> I don't think so currently as the second instance is required to start the management server. If you don't want that then I'd suggest just exposing the actuator via the primary server.

Can we start with https://github.com/spring-projects/spring-boot/pull/16852 to avoid creating unnecessary threads and exercising initialization code.
