### ISSUE TITLE
Cannot create asynchronous JobLauncher

### ISSUE THREAD

**Issue by ameraljovic** [spring-projects/spring-boot#1655]
The Spring Boot implementations does not set any `TaskExecutor` so it defaults to `SyncTaskExecutor`. And there is no way (as I know) to override the default `jobLauncher` bean because of this line in  `BasicBatchConfigurer` which creates a default `jobLauncher`:

```
@PostConstruct
    public void initialize() {
        try {
            this.transactionManager = createTransactionManager();
            this.jobRepository = createJobRepository();
            this.jobLauncher = createJobLauncher();
            this.jobExplorer = createJobExplorer();
        }
        catch (Exception ex) {
            throw new IllegalStateException("Unable to initialize Spring Batch", ex);
        }
    }
```

I also tried to autowire `jobLauncher` and set the `TaskExecutor` by myself. But because I can only autowire the interface, I can't call `jobLauncher.setTaskExecutor(simpleAsyncTaskExecutor)`.

**Comment by Wifsimster** [comment]
@kakawait - I think i need to kiss you for this code :+1:

**Comment by tomerku** [comment]
Hi kakawait, 
When using the "public JobLauncher asyncJobLauncher()" my tasks aren't getting run at all, 

What I did was:

	@Autowired
	private JobRepository jobRepository;

	@Autowired
	private Job job;
	
	@Test
	public void testLaunchJob() throws Exception {


		JobExecution execution = asyncJobLauncher().run(job, new JobParameters());

		System.out.println("\n\n\nTomer\n\n\n");

		System.out.println("Exit Status : " + execution.getStatus());
		System.out.println("Exit Status : " + execution.getAllFailureExceptions());
	}

	@Bean
	public JobLauncher asyncJobLauncher() {
		SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
		jobLauncher.setJobRepository(jobRepository);
		jobLauncher.setTaskExecutor(new SimpleAsyncTaskExecutor());
		return jobLauncher;
	}

Help will be appreciated,

Thanks,
Tomer

**Comment by snicoll** [comment]
@tomerku this tracker is not the right place for asking such question. Please ask them on Stackoverflow.

**Comment by tomerku** [comment]
Will do. Thanks.

**Comment by snicoll** [comment]
Actually, I think this issue can be closed. `createJobLauncher()` is `protected` as of #4888 so all you need to do really is create your own `BatchConfigurer` that provides a custom `JobLauncher`.
