### ISSUE TITLE
Not able to load ResourceBundle required by dependency jar

### ISSUE THREAD

**Issue by Yavdhesh** [spring-projects/spring-boot#16562]
Friends,

I have created one batch jar named 'myBatch.jar' which has a dependency jar 'confidentialGDPR.jar'

'confidentialGDPR.jar' has a line of code :

    `ResourceBundle resource= new ResourceBundle('GDPR.properties');`

```
export CLASSPATH=/branch/jboss-eap-6.4/modules/system/layers/base/com/gobi/jars/Batches/

nohup /usr/bin/java -Djava.security.egd=file:/dev/./urandom -Dlogging.config=./log4j.xml -Dspring.profiles.active=dev -jar  /branch/jboss-eap-6.4/modules/system/layers/base/com/gobi/jars/Batches/myBatch.jar --spring.config.location=CLASSPATH:/GDPR.properties --spring.config.additional-location=CLASSPATH:/GDPR.properties  &
```
--

Even after mentioning config.location and config.additional-location.
GDPR properties, I am not able to load.

**Comment by snicoll** [comment]
`spring.config.additional-location` can't be used to refer to a jar file, please [review the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files).

In the future, please ask that question on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by Yavdhesh** [comment]
**But I am not trying to load jar**, 

I am trying load a property file which is required by a dependency jar.

This dependency jar is bundled inside my batch jar. Thus,we are required to load the property via command line argument.

**Comment by snicoll** [comment]
Sorry, I wrote "jar" but I mean resource. `spring.config.additional-location` sets a location not a resource (have you looked at the doc I've shared?). It's a bit unclear why you think this is a bug in Spring Boot but if you can share a sample (zip file or link to a github repo) that demonstrates the problem you've described we can reopen and have a look.

**Comment by Yavdhesh** [comment]
Due to privacy breach, I can not share the code. but I can definitely explain with the screen shots.

1) We have a jar 'myBatch.jar' which requires 'confidentialGDPR.jar'.
2) 'confidentialGDPR.jar' in turn requires 'GDPR.properties'
3) So while executing the jar, we are setting spring.config.location like
-Dspring.config.location=/branch/jboss-eap-6.4/modules/system/layers/base/com/gobi/jars/Batches/GDPR.properties

But in the code we are getting an error like :

![image](https://user-images.githubusercontent.com/22321498/56125760-47c05c00-5f97-11e9-91c3-42c149d3ad4f.png)


```
Caused by: java.lang.RuntimeException: Could not load resource bundle GDPR.properties. Throwing runtime exception.
	at com.gobi.gdpr.KeyClient.readProperties(KeyClient.java:138)
	at com.gobi.gdpr.KeyClient.<init>(KeyClient.java:38)
	at com.gobi.gdpr.KeyClient.<clinit>(KeyClient.java:27)
	... 51 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name GDPR, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at com.gobi.gdpr.KeyClient.readProperties(KeyClient.java:128)
```

**Comment by snicoll** [comment]
> Due to privacy breach, I can not share the code. 

That's not what I asked. I asked for a sample (zip file or link to a github repo) that demonstrates the problem you've described.
