### ISSUE TITLE
Condition Evaluation report log property of Automatic Restart not working

### ISSUE THREAD

**Issue by leggiero** [spring-projects/spring-boot#16578]
Setting `spring.devtools.restart.log-condition-evaluation-delta=false` in application.properties do not prevent the Condition Evaluation report to be writing to the log output.

[20.2.1 Logging changes in condition evaluation](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-logging-condition-delta)

Note that I have `debug=true` as I'm running the application in my development environment.

As a workaround, I'm setting `logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=INFO`. This should be avoided by using the correct property to disable the report.

The application restart is working properly.
I'm using Spring Boot **2.1.4.RELEASE**.

Could you please have a look?

Thank you.

**Comment by wilkinsona** [comment]
The logging of the report when the application context refreshes and the logging of a delta when DevTools restarts the application are two separate things. Setting `debug=true` enables the former while setting `spring.devtools.restart.log-condition-evaluation-delta=false` disables the latter so I believe that things are behaving as expected.

Tuning the log level for `ConditionEvaluationReportLoggingListener` is the right thing to do if you want to run with `debug=true` but do not want the condition evaluation report to be logged.
