### ISSUE TITLE
Simplify starter validation dependencies and make validation easier to exclude from WebFlux applications

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16582]
This is a follow-on from #16176. The changes made in that issue are also applicable to `spring-boot-starter-webflux` as well.

**Comment by pkostrzewa** [comment]
Can I provide an PR for this?

**Comment by wilkinsona** [comment]
Yes please, that'd be great. Thanks.

**Comment by wilkinsona** [comment]
Closing in favour of #16593.
