### ISSUE TITLE
spring-boot-maven-plugin v2.2.0.M2 execute repackage produce ${project.name}.jar

### ISSUE THREAD

**Issue by kaojunsong** [spring-projects/spring-boot#16609]

**Comment by philwebb** [comment]
There's not enough information here to reproduce the issue. Please could you provide a sample application that shows what you mean?

**Comment by kaojunsong** [comment]
> There's not enough information here to reproduce the issue. Please could you provide a sample application that shows what you mean?

Hi,
Thanks for you quick reply!
The Sample application is in https://github.com/kaojunsong/spring-boot.git  
when I execute the package goal: mvn clean package -Dmaven.test.skip=true ,the package I produce is ${project.name}.jar 
![image](https://user-images.githubusercontent.com/9572722/56448997-e574ac00-6346-11e9-878e-f7287996d6fd.png)
 I debug the spring-boot-maven-plugin v2.2.0.M2,and I found ine 
262 of RepackageMojo.java had been changed compared with previous version.
I suspect the problem comes from
 `String finalName = this.project.getBuild().getFinalName();`.

Please tell me if I am right or there's some other reason.And how to fix it,Thank you!

**Comment by philwebb** [comment]
I have a feeling this might be a duplicate of #16456, but we'll need some input from @snicoll

**Comment by snicoll** [comment]
It indeed is. 

Duplicate of #16456
