### ISSUE TITLE
Convince apache httpcomponents 5 team to simplify dependency management

### ISSUE THREAD

**Issue by seregamorph** [spring-projects/spring-boot#16605]
There is at least three repos with 3 groups of httpcomponents artifacts: core, client, asyncclient, each group has its own version.
But in fact in a complicated project with big count of dependencies including dozens of artifacts, there can easily be a jar hell with incompatible versions of artifacts.

Probably you know what I am talking about.

The more detailed it's described here
https://issues.apache.org/jira/browse/HTTPCLIENT-1985

Right now the generation 5 of http components is being prepared to release, but not yet released. This still can be solved. And you can affect with good advice (for sure if you think it's a good idea).

Anyway, it's just my IMHO, I'm curious what you think about it.
Thanks.

**Comment by philwebb** [comment]
Thanks for the suggestion, but I don't feel like it's our place to try and convince other projects how they should manage their artifacts. I think we should leave that to a discussion between the maintainers and the people that consume their libraries (like yourself).
