### ISSUE TITLE
Dependency management for Glassfish JAXB is incomplete

### ISSUE THREAD

**Issue by altro3** [spring-projects/spring-boot#16619]
Hi! I know, you can't add whole JAXB BOM file to spring-boot-dependencies (https://github.com/spring-projects/spring-boot/issues/15599), but, maybe you can add only
```
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-xjc</artifactId>
    <version>${glassfish-jaxb.version}</version>
</dependency>
```
You already have property glassfish-jaxb.version in your file for dependency org.glassfish.jaxb:jaxb-runtime.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We generally try to manage all of project's modules. We currently only manage jaxb-runtime so we're missing quite a few for Glassfish JAXB.
