### ISSUE TITLE
Support jsr-303 annotations on collection elements within ConfigurationProperties

### ISSUE THREAD

**Issue by danveloper** [spring-projects/spring-boot#1662]
Would be nice if the context failed to start due to a validation failure described by JSR-303 annotations on a `@ConfigurationProperties` annotated component.

when:
```yaml
name: foo
```

then:
```groovy
@Component
@ConfigurationProperties
class ConfigProps {
  String name

  @javax.validation.constraints.NotNull
  String host
}
```

...should result in the context not starting due to a validation constraint.

**Comment by snicoll** [comment]
You need to put `@Valid` on ` List<Account> accounts`
