### ISSUE TITLE
spring boot maven plugin : repackage ignores finalName (since 2.1.4.RELEASE)

### ISSUE THREAD

**Issue by juergenschuft** [spring-projects/spring-boot#16638]
Since 2.1.4.RELEASE, the finalName property of spring boot maven plugin / repackage configuration is beeing ignored. The war file created is named with artifact id and version (in our case "pvFrontend-39.0.0.war"), no matter which values are being configured.

Please refer to attached pom:
[pvFrontend.pom.txt](https://github.com/spring-projects/spring-boot/files/3111610/pvFrontend.pom.txt)

**Comment by wilkinsona** [comment]
Thanks for the report. This is a duplicate of #16456.
