### ISSUE TITLE
Autowire collection members automatically created inside ConfigurationProperties objects

### ISSUE THREAD

**Issue by danveloper** [spring-projects/spring-boot#1663]
Would be nice to be able to implement DDD-style "rich" domains through the `@ConfigurationProperties` mechanism.

For example:

```groovy
@Component
@ConfigurationProperties
class ConfigObj {
  List<Account> accounts
}

class Account {
  @Autowired
  RestTemplate restTemplate

  String host

  boolean doSomeCall() {
    def entity = restTemplate.getForEntity(host, Map)
    entity.statusCode == HttpStatus.OK
  }
}
```

**Comment by earthling** [comment]
+1 - I think if spring instantiates your object, it ought to perform dependency injection on the instance.

**Comment by snicoll** [comment]
This one hasn't moved for quite some time and I agree with Dave. We're really pushing for using `@ConfigurationProperties` as a type-safe facade for the environment. Making them complex objects goes in the opposite direction.
