### ISSUE TITLE
using @cacheable will lead to proxy problem

### ISSUE THREAD

**Issue by wuyuan0717** [spring-projects/spring-boot#16634]
springboot edition: 2.1.3.RELEASE

### opening cache support:
![image](https://user-images.githubusercontent.com/14838846/56642390-e8a2cb80-66a9-11e9-8123-70fdde5caee2.png)

### adding cahce when login:
![image](https://user-images.githubusercontent.com/14838846/56642598-636be680-66aa-11e9-9043-7d7aafe92f66.png)

**when i start my project up ,i find a problem , LoginController will not be as a request handler. maybe it had be proxied by cache support,**
![image](https://user-images.githubusercontent.com/14838846/56642695-98783900-66aa-11e9-9670-08ac5b97a503.png)

` isHandler(beanType)` retrun false,but LoginController  should be a controller

`if (beanType != null && isHandler(beanType)) {
			detectHandlerMethods(beanName);
		}
`

#16630

**Comment by wuyuan0717** [comment]
How can I solve this problem?

**Comment by snicoll** [comment]
@wuyuan0717 screenshots are not a great way to get support and I am not sure to understand what you're trying to achieve by caching that login method.

> LoginController will not be as a request handler. 

Sorry but I don't understand what that means. Can you please a small sample that reproduces the problem you're experiencing (a zip or a link to a github repo).

**Comment by snicoll** [comment]
@wuyuan0717 I can see you've already submitted this an hour ago #16630 and you were redirected to ask a question on StackOverflow. Ignoring a reply from the team and opening a duplicate issue is not a great way to get support either.

**Comment by wuyuan0717** [comment]
@snicoll when i using '@EnableCaching' open cache support ,and i add '@Cacheable' on a method that need cache support.  AbstractHandlerMethodMapping can`t register it as a handler,because  this beanType is 'class com.sun.proxy.$Proxy109' ,'@RestController' and '@Requesrmapping' will not find .
```@Override
	protected boolean isHandler(Class<?> beanType) {
		return (AnnotatedElementUtils.hasAnnotation(beanType, Controller.class) ||
				AnnotatedElementUtils.hasAnnotation(beanType, RequestMapping.class));
	}
```
![image](https://user-images.githubusercontent.com/14838846/56644007-6ae0bf00-66ad-11e9-8c82-e88b9a63698f.png)

**Comment by wuyuan0717** [comment]
@snicoll The screenshot is what I want to show my LoginContoller annotations, but he is not registered as a request processing class. When I used caching, he was proxyed and the annotations ‘@Controller’、‘@RequestMapping’ could not be found

**Comment by snicoll** [comment]
Alright, I am going to close this now. Take the time to read what I've asked you to provide and we can reopen this issue for investigations.

**Comment by wuyuan0717** [comment]
I'm sorry for the question I asked yesterday. I've found the reason for the problem. It turned out that there was a problem with the jar of **shiro-spring-boot-web-starter** I added. It adds a bean of **DefaultAdvisorAutoProxyCreator** by default. 
I set the **shiro.annotations.enabled** to false. All the problems have been solved.
### Now I have a question, why does joining bean of **DefaultAdvisorAutoProxyCreator**  lead to proxy problems?


``` 
package org.apache.shiro.spring.boot.autoconfigure;

import org.apache.shiro.mgt.SecurityManager;
import org.apache.shiro.spring.config.AbstractShiroAnnotationProcessorConfiguration;
import org.apache.shiro.spring.security.interceptor.AuthorizationAttributeSourceAdvisor;
import org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;

/**
 * @since 1.4.0
 */
@SuppressWarnings("SpringFacetCodeInspection")
@Configuration
@ConditionalOnProperty(name = "shiro.annotations.enabled", matchIfMissing = true)
public class ShiroAnnotationProcessorAutoConfiguration extends AbstractShiroAnnotationProcessorConfiguration {

    @Bean
    @DependsOn("lifecycleBeanPostProcessor")
    @ConditionalOnMissingBean
    @Override
    public DefaultAdvisorAutoProxyCreator defaultAdvisorAutoProxyCreator() {
        return super.defaultAdvisorAutoProxyCreator();
    }

    @Bean
    @ConditionalOnMissingBean
    @Override
    public AuthorizationAttributeSourceAdvisor authorizationAttributeSourceAdvisor(SecurityManager securityManager) {
        return super.authorizationAttributeSourceAdvisor(securityManager);
    }
}

```

**Comment by snicoll** [comment]
> Now I have a question

Please take the time to [review the guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues) before contributing again. As [we've already mentioned](https://github.com/spring-projects/spring-boot/issues/16630#issuecomment-486104521), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by wuyuan0717** [comment]
I have taked some time to review the guidelines. Thanks for your sincerely advise
