### ISSUE TITLE
Ensure that @Profile always works with @ConfigurationProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16645]
We need to check that `@Profile` works with `@ConfigurationProperties` no matter how they are loaded. Currently we think it will work on `@Bean` and using scanning, but not with `@EnableConfigurationProperties`.

See #16622

**Comment by mbhave** [comment]
`@EnableConfigurationProperties` works using a `ImportBeanDefinitionRegistrar` which registers beans without any condition evaluation. If you're using `@EnableConfigurationProperties`, the configuration properties bean can be made profile-specific by having `@Profile` on the `@Configuration` that declared `@EnableConfigurationProperties`.

I think we should document that if `@EnableConfigurationProperties` is replaced by configuration properties scanning, the `@Profile`  annotation needs to be moved to the `@ConfigurationProperties` class.

**Comment by mbhave** [comment]
Closing this in favor of #16622.
