### ISSUE TITLE
ApplicationListener not working when I add resource.filtering to pom.xml

### ISSUE THREAD

**Issue by monkeydp** [spring-projects/spring-boot#16641]
Spring Boot: 2.1.3.RELEASE
Maven: 3.3.9

When I add following config to pom.xml, ApplicationListener.onApplicationEvent() is not execute anymore

```
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.properties</include>
                </includes>
            </resource>
        </resources>
    </build>
```

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, I can't see the connection between filtering properties files and application event handling. If you would like us to spend some time investigating, please spend some time providing a complete and minimal sample that reproduces the problem either as a zip attached to this issue or in a separate repository on GitHub.

**Comment by monkeydp** [comment]
I will prepare a sample tomorrow. Thanks for your reply！------------------ Original ------------------From: Andy Wilkinson  <notifications@github.com>Date: Wed,Apr 24,2019 8:49 PMTo: spring-projects/spring-boot <spring-boot@noreply.github.com>Cc: Monkey D. Potato <monkeydpotato@gmail.com>, Author <author@noreply.github.com>Subject: Re: [spring-projects/spring-boot] Bug report: ApplicationListener notworking when I add resource.filtering to pom.xml (#16641)Thanks for the report. Unfortunately, I can't see the connection between filtering properties files and application event handling. If you would like us to spend some time investigating, please spend some time providing a complete and minimal sample that reproduces the problem either as a zip attached to this issue or in a separate repository on GitHub.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spring-projects/spring-boot","title":"spring-projects/spring-boot","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/spring-projects/spring-boot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wilkinsona in #16641: Thanks for the report. Unfortunately, I can't see the connection between filtering properties files and application event handling. If you would like us to spend some time investigating, please spend some time providing a complete and minimal sample that reproduces the problem either as a zip attached to this issue or in a separate repository on GitHub."}],"action":{"name":"View Issue","url":"https://github.com/spring-projects/spring-boot/issues/16641#issuecomment-486212764"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spring-projects/spring-boot/issues/16641#issuecomment-486212764",
"url": "https://github.com/spring-projects/spring-boot/issues/16641#issuecomment-486212764",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by monkeydp** [comment]
[bugsample.zip](https://github.com/spring-projects/spring-boot/files/3114874/bugsample.zip)

**Comment by monkeydp** [comment]
Here is a bug sample

README.md can help you understand the bug

**Comment by snicoll** [comment]
You are overriding the `resources` element of your build so that only `*.properties` file are copied. `spring.factories` is no longer copied by Maven and therefore your listener is not picked up.

If you need help how to configure Maven, please ask on StackOverflow

**Comment by monkeydp** [comment]
Get it. I should not add following config to pom.xml

```
                <includes>
                    <include>*.properties</include>
                </includes>
```

And also, Spring Boot 1.3 or higher, I should replace `${project.basedir}` with `@project.basedir@`

**Comment by monkeydp** [comment]
Get it!
I should not add following config to pom.xml

```
                <includes>
                    <include>*.properties</include>
                </includes>
```

And also, Spring Boot 1.3 or higher, I should replace `${project.basedir}` with `@project.basedir@`
