### ISSUE TITLE
Upgrade to Spring boot 2 causing startup failure

### ISSUE THREAD

**Issue by avinashzen123** [spring-projects/spring-boot#16653]
> **While upgrading Spring boot version from 1.5.7.RELEASE to 2.0.2.RELEASE, we are getting below exception while service startup.**

> Even after trying new versions of spring we are facing same problem

$ sudo /etc/init.d/my-service start
/etc/init.d/my-service: 1: /etc/init.d/my-service: PK: not found
/etc/init.d/my-service: 2: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 3: /etc/init.d/my-service: l�Lorg/PK: not found
/etc/init.d/my-service: 4: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 5: /etc/init.d/my-service: l�Lorg/springframework/PK: not found
/etc/init.d/my-service: 6: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 7: /etc/init.d/my-service: l�Lorg/springframework/boot/PK: not found
/etc/init.d/my-service: 8: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 9: /etc/init.d/my-service: l�L: not found
/etc/init.d/my-service: 10: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 11: /etc/init.d/my-service: l�L%org/springframework/boot/loader/data/PK: not found
/etc/init.d/my-service: 12: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 13: /etc/init.d/my-service: l�L/springframework/boot/loader/jar/PK: not found
/etc/init.d/my-service: 14: /etc/init.d/my-service:: not found
/etc/init.d/my-service: 15: /etc/init.d/my-service: Syntax error: word unexpected (expecting ")")

**Comment by wilkinsona** [comment]
It would appear that you are trying to execute a jar file that is not fully executable. Without knowing how you've built the jar file it's impossible to know why that might be the case. If you would like us to spend some time investigating, please take the time to provide a minimal sample that reproduces the problem either as a zip attached to this issue or in a separate repository on GitHub.

**Comment by avinashzen123** [comment]
[build.gradle.txt](https://github.com/spring-projects/spring-boot/files/3116741/build.gradle.txt)

Attaching the build.gradle file which we used to build war file.

We also tried removing below snippets.

`bootJar {
    mainClassName = 'com.MyApp'
    launchScript()

}`

and still facing same problem.

**Comment by wilkinsona** [comment]
If you are building a war file then you need to configure `bootWar` to include the launch script rather than `bootJar`:

```
bootWar {
    launchScript()
}
```
