### ISSUE TITLE
Investigate why java JarLauncher on an unpacked jar is slower than java -cp

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16655]
Specifically on https://github.com/spring-projects/sts4/tree/master/headless-services/spring-boot-language-server

**Comment by philwebb** [comment]
@martinlippert Can you add some instructions on the various ways you start that app and what timings you see?

**Comment by martinlippert** [comment]
I tried three different things to run the app:

- PropertiesLauncher: `java -jar 1.7.0.qualifier-spring-boot-language-server-1.7.0-SNAPSHOT.jar`
- JarLauncher: unzip, then `java org.springframework.boot.loader.JarLauncher`
- plain classpath: unzip, then `java -cp "BOOT-INF/classes:BOOT-INF/lib/*" org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp`

PropertiesLauncher and JarLauncher is roughly about the same startup time (from the output that appears one the console). The plain class path thing is noticeable faster for me.

**Comment by martinlippert** [comment]
Our goal is to get the startup time of the overall language server below 1000ms in total, which means that we might have about 500ms available for the pure boot app startup (as measured here), all in total JVM up time. At the moment this is at around ~2300ms for the PropertiesLauncher and the JarLauncher, and around ~1600ms for the plain classpath launch. Looks like this will be an important step towards our goal.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/pull/16248 will, I believe, speed up the second case.

**Comment by wilkinsona** [comment]
It looks like it may have been wishful thinking that #16248 would help here. Interestingly, I've also observed that `java -jar` is faster than `java org.springframework.boot.loader.JarLauncher`. This appears to be the case both with 2.2.0.M2 and with a polished version of changes proposed in #16248.

**Comment by wilkinsona** [comment]
I take that back.

Having double-checking my results and built and timed things more scientifically, #16248 does help with the exploded case where the launcher is still used. It brings its start time down so it lies somewhere in between `java -cp` and `java -jar`.

|  | Classpath | Launcher | Jar |
| - | - | - | - |
| 2.2 snapshots |  0.767 | 0.974 | 0.934 |
| gh-16248 |  0.768 | 0.851 | 0.926 |

**Comment by wilkinsona** [comment]
I've [tried](https://github.com/wilkinsona/spring-boot/tree/gh-16655) deferring the creation of the `JarFile` when the launcher's creating the classpath as all it needs is the `URL`. Unfortunately, it's made almost no difference – maybe 5ms at best.

**Comment by mbhave** [comment]
These are some numbers based on the above changes:

|  | Exploded classpath | Exploded launcher |
| - | - | - |
|       |    1.480 | 1.189 |
|       |    1.253 | 1.351 |
|       |    1.242 | 1.231 |
|       |    1.662 | 1.387 |
|       |    1.342 | 1.497 |
|       |    1.301 | 1.219 |
|       |    1.515 | 1.257 |
|       |    1.296 | 1.374 |
|       |    1.318 | 1.205 |
|       |    1.348 | 1.393 |
|  Mean |    **1.376** | **1.310** |
| Range |    0.420 | 0.308 |
