### ISSUE TITLE
@ComponentScan for external dependency package is not working in 2.1.x at the time of building the jar and running that jar

### ISSUE THREAD

**Issue by mrkunal** [spring-projects/spring-boot#16664]
I'm facing an issuing while using the spring boot 2.1.x.RELEASE as it is not scanning the basepackages in component scan but It is working perfectly fine in 2.0.x.

@ComponentScan(basePackages = { "com.app.base*", "com.app.child.*" })
When creating a build using

mvn clean package
It's jar has been created but when running the jar it is not loading the beans from the base external repository.

java -jar child.jar
Exception:

ConfigServletWebServerApplicationContext : Exception encountered during context initialization 
- cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: 
Failed to parse configuration class [org.orange.quotra.user.UserApiApplication]; 
nested exception is java.io.FileNotFoundException: 
class path resource [com/app/base/service/BaseService.class] cannot be opened because it does not exist
I am adding base.jar in the lib/base.jar of the child project. Following is the pom.xml

<dependency>
  <groupId>com.app</groupId>
  <artifactId>base</artifactId>
  <version>0.2</version>
</dependency>
<repository>
  <id>myRepo</id>
  <url>file://${basedir}/lib</url>
</repository>
For deploy base.jar into my local repository

 mvn deploy:deploy-file -DgroupId=com.app -DartifactId=base-Dversion=0.2 -Durl=file:./myRepo -DrepositoryId=myRepo -DupdateReleaseInfo=true -Dfile=lib/base-0.2.jar
The component scan is well working when I run the application from STS. But when I am creating build and trying to run the jar It is throwing error.

I have also exploded the child.jar using

jar -tf child.jar
base.jar was there in the list.

**Comment by snicoll** [comment]
Thanks for the sample and this is one reason why providing one is super important. 

Please consider reviewing [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#maven-plugin) when upgrading. As of `2.1.x` the `repackage` execution has an identifier. You're adding a second repackage so you end up with two fat jars.

Also it took me some time to figure out why that wasn't fixing it. That `lib` folder with an hardcoded jar is, ahem, special. A word about that would have helped.

I've submitted a PR to fix your sample according to the release notes.

**Comment by mrkunal** [comment]
thanks a lot @snicoll for the help. It's working fine now and for the hardcoded jar in the lib folder we are planning to use our nexus repository for team. but for the workaround we have placed this jar in lib folder. Thanks again one more time :)
