### ISSUE TITLE
The -d option of spring init CLI command is not POSIX compliant

### ISSUE THREAD

**Issue by bgx90** [spring-projects/spring-boot#16663]
Currently, supplying a list of dependencies to `spring init` using the short version of the dependencies option requires separating the option from its argument with an equals sign like this `spring init -d=lombok,devtools,web`. This special syntax does not follow the [POSIX standard regarding utility argument syntax](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_01) and consequently feels very unnatural to me as a command line user.  I cannot think of another utility that uses this kind of syntax for a single-letter option with arguments.  I can get around the awkwardness of remembering this special case by using the long GNU-style option `--dependencies` instead since that style allows `=` to separate the option and its argument(s) ([GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) actually says `=` should be used, but most utilities I've used will allow a space as well), but I would prefer to use the shorter `-d` with the expected syntax.  Can the `-d` option be made to allow a space to separate it from its argument in order to make it POSIX-compliant (e.g. `spring init -d lombok,devtools,web`) ?

**Comment by philwebb** [comment]
It turns out this is a bug with `CommandRunner.removeDebugFlags` which is removing `-d` early and treating it as a debug switch. JOptSimple then tries to parse `spring init lombok,devtools,web`.

**Comment by philwebb** [comment]
I'm tempted to remove the short `-d` for debugging in 2.2
