### ISSUE TITLE
Enhance documentation to support frames / sidebar for navigation

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#1667]
The rationale for this request to support something similar to what is provided for Spring XD:

http://docs.spring.io/autorepo/docs/spring-xd/1.0.0.M4/reference/html/

As a personal side note, the layout seems more space efficient and visually appealing. Any plans in the works for the Spring Team will normalize on a consistent documentation format?

**Comment by philwebb** [comment]
We've decided not try and customize our existing HTML and instead try to upgrade to direct asciidoctor generated HTML.
