### ISSUE TITLE
Consider removing configuration properties import selector 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#16679]
`EnableConfigurationPropertiesImportSelector` imports two `ImportBeanDefinitionRegistrar`s. This intermediate step seems unnecessary and we could just do a 
```
@Import({ConfigurationPropertiesBeanRegistrar,ConfigurationPropertiesBindingPostProcessorRegistrar})
```

**Comment by mrifni** [comment]
HI, can I pick up this task ?

**Comment by snicoll** [comment]
@mrifni thanks for the offer but the issue is assigned to @mbhave.
