### ISSUE TITLE
Multi-module Spring Boot Project with a Kotlin project when I want to bootJar  

### ISSUE THREAD

**Issue by houshuai0816** [spring-projects/spring-boot#16689]
Before submitting the question, I've implemented a look at it (#8980 ),But it didn't solve our problem.

A multi module project with Kotlin source code, which used to work, stops working after upgrading to Gradle 5.2, because the Kotlin classes from the compile project('other-module') dependency are not found.

Expected Behavior
The Kotlin classes in the compile project('depend-test') dependency should be found.

Current Behavior
The Kotlin classes in the compile project('depend-test') dependency are not found:

> Task :test-test:compileKotlin FAILED
e: /Users/houshuai/Documents/dev/demo/test/test-test/src/main/kotlin/com/example/test/controller/TestController.kt: (3, 20): Unresolved reference: dependtest
e: /Users/houshuai/Documents/dev/demo/test/test-test/src/main/kotlin/com/example/test/controller/TestController.kt: (22, 18): Unresolved reference: Test
Context

Doesn't work in Gradle 5.2
Steps to Reproduce
See https://github.com/houshuai0816/gradle-multimodule-kotlin-bug

**Comment by snicoll** [comment]
@sdeleuze said he'd have a look to the sample. Thanks Sébastien !

**Comment by wilkinsona** [comment]
You have applied the Spring Boot plugin to the `depend-test` project which disables the `jar` task and just builds a Spring Boot fat jar instead. A Spring Boot fat jar isn't suitable for use as a dependency. For sub-modules that are only used as a dependency, I would recommend using Spring Boot's dependency management in isolation as [described in the documentation](https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/gradle-plugin/reference/html/#managing-dependencies-using-in-isolation).

**Comment by houshuai0816** [comment]
Thank you very much for having solved my problem. @wilkinsona
