### ISSUE TITLE
Provide support for custom class loader to bridge into LaunchedURLClassLoader

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#1668]
This class provides ability to specify a custom JVM System Class Loader to enable loading classes provided inside nested jars of the Spring Boot uber-jar for use cases such as setting custom `policy.provider` or `java.security.manager` or `java.rmi.server.RMIClassLoaderSpi`. All those classes are being loaded by JVM from the System Class Loader, so this enables packaging custom implementations inside the distribution jar as nested artifact dependencies.
`-Djava.system.class.loader=org.springframework.boot.loader.SpringBootSystemClassLoader` can be provided as a startup argument to enable use of custom system class loader

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-boot/pull/1669#issuecomment-169958723
