### ISSUE TITLE
Support configuring logging groups via loggers endpoint

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#16680]
I don't think it's possible to update or get the configuration of a group via the loggers endpoint at the moment. In fact, with logback, if you try to `GET` the configuration using the group's name, it creates a child logger with that name which is a bit confusing. Adding an issue to see what the rest of the team thinks about this.

**Comment by wilkinsona** [comment]
I think we should support getting or updating the log level for a logging group via the endpoint. I don't think we should support creating groups or changing the loggers to which an existing group maps via the endpoint.

**Comment by mbhave** [comment]
Yup, that's what I was thinking as well.

**Comment by mbhave** [comment]
Closing in favor of PR #17515.
