### ISSUE TITLE
property:'spring.jpa.properties.hibernate.naming.physical-strategy' not work

### ISSUE THREAD

**Issue by s-mop** [spring-projects/spring-boot#16686]
here is a bean config code

```java
	@Bean
	public LocalContainerEntityManagerFactoryBean entityManagerFactoryBean(EntityManagerFactoryBuilder builder, DynamicDataSource dynamicDataSource) {
		HashMap<String, String> properties = new HashMap<String, String>();
		properties.put("spring.jpa.properties.hibernate.naming.physical-strategy", "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy");
		return builder.dataSource(dynamicDataSource).properties(properties).packages("com.bigaka.wxy").build();
	}
```

Naming strategy is not work as I expected before I change code like this:

```java

	@Bean
	public LocalContainerEntityManagerFactoryBean entityManagerFactoryBean(EntityManagerFactoryBuilder builder, DynamicDataSource dynamicDataSource) {
		HashMap<String, String> properties = new HashMap<String, String>();
		properties.put("hibernate.implicit_naming_strategy", "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy");
		properties.put("hibernate.physical_naming_strategy", "org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy");
		return builder.dataSource(dynamicDataSource).properties(properties).packages("com.xxx").build();
	}
```

In org.hibernate.boot.internal.MetadataBuilderImpl 669

```java

			this.physicalNamingStrategy = strategySelector.resolveDefaultableStrategy(
					PhysicalNamingStrategy.class,
					configService.getSettings().get( AvailableSettings.PHYSICAL_NAMING_STRATEGY ),
					PhysicalNamingStrategyStandardImpl.INSTANCE
			);
```
The key 'PhysicalNamingStrategyStandardImpl.INSTANCE' was hibernate.physical_naming_strategy

**Comment by snicoll** [comment]
> here is a bean config code

If you configure your own bean, auto-configuration does not apply and `spring.jpa.properties.hibernate.naming.physical-strategy` will be ignored. I am not sure I understand what problem you are reporting so if that does not help, please share a small sample (zip or github repo)  that we can run that reproduces the issue. Code in text is not very useful as it's likely to miss something.

**Comment by s-mop** [comment]
> If you configure your own bean, auto-configuration does not apply and spring.jpa.properties.hibernate.naming.physical-strategy will be ignored

Thanks for your explanation. I think this is clear enough for me.
It was just out of my expectation that even 'hibernate.naming.physical-strategy' won't work in 'LocalContainerEntityManagerFactoryBean'(as a class in spring-orm).
