### ISSUE TITLE
Document that auto-configuration classes and properties are considered internal

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16704]

**Comment by snicoll** [comment]
@mbhave I wonder if that shouldn't be a bit more high level (in some dedicated section) that explains that extending from auto-configuration should be avoided, etc.

**Comment by wilkinsona** [comment]
We looked at this today, and concluded that what we currently have is fine. We consider not sub-classing to be a specific example of not relying anything other than the class's name which is already covered in the additions that have already been made.
