### ISSUE TITLE
Provide discovery page for actuators at / when using a separate management port

### ISSUE THREAD

**Issue by JigarJoshi** [spring-projects/spring-boot#16713]
From [the doc](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-hypermedia)

> When the management context path is set to /, the discovery page is disabled to prevent the possibility of a clash with other mappings.

This is great. However when management server is running on different server it will be useful to still see this page. There are two approaches comes to my mind.

1. Either provide the discovery page when baseContext is set to `/` and management server is running on different port than the regular application server. Or if the regular application server is not running entirely

2. Move discovery page under `_meta` endpoint which renders this page regardless at this specific endpoint.

Code reference

`org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping#registerLinksMapping`

**Comment by mbhave** [comment]
> Either provide the discovery page when baseContext is set to / and management server is running on different port than the regular application server.

I think it makes sense to enable the discovery endpoint if the management server is on a different port even when the base path is `/`. Our original plan was to [disable mapping actuators to `/`](https://github.com/spring-projects/spring-boot/issues/9898) to avoid a potential path clash that the discovery endpoint would cause unless a different port was used. We decided against that and instead disabled the discovery endpoint for a base-path of `/`. We might not have considered the separate server use case as part of that change.

Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
> I think it makes sense to enable the discovery endpoint if the management server is on a different port even when the base path is `/`

👍

**Comment by mbhave** [comment]
Closing in favor of PR #16713.
