### ISSUE TITLE
Investigate meta-annotating @ConfigurationProperties with @Component rather than having custom scanning

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16712]

**Comment by mbhave** [comment]
This probably won't work for immutable constructor-based `@ConfigurationProperties` because those require the bean to be fully bound before registering.

**Comment by mbhave** [comment]
Blocked on [this framework issue](https://github.com/spring-projects/spring-framework/issues/22995).

**Comment by snicoll** [comment]
I've investigated this proposal a bit and I don't think we should do this for the reasons exposed below:

Doing this means that we merge the `@ConfigurationProperties` stereotype with the `@Component` stereotype. Usually, we do this when we need a specialized `@Component` but that does not apply here. Consider the following example:

```java
@Bean
@ConfigurationProperties("acme")
AcmeProperties acmeProperties() { ... }
```

It doesn't feel right that an explicit bean registration uses a stereotype that is linked to component scan.

Besisdes, `@ConfigurationProperties` wouldn't be a regular component as it needs to be handled by a custom `BeanDefintion` (constructor-based binding). It would be easy to create a non Spring Boot application context where such component is automatically scaned and break startup as that special handing isn't registered.

Finally, merging those two stereotypes does not allow a user to manually select a `@ConfigurationProperties` class that is the target of component scan as it was the case before. While this is ok in the case of a `@SpringBootApplication` as this is the feature we want to add, it is less for other kind of contexts that users may have for testing purposes. They'd be forced to remove `@ConfigurationProperties` and resort to `@Bean` registration.

As for the framework issue, I think meta-annotate `@ConfigurationProperties` by `@Component` is just one of the options on the table so I think the actual work (and problem to fix) should happen in #16659

**Comment by wilkinsona** [comment]
> Doing this means that we merge the @ConfigurationProperties stereotype with the @Component stereotype. Usually, we do this when we need a specialized @Component but that does not apply here. 
> …
> It doesn't feel right that an explicit bean registration uses a stereotype that is linked to component scan.

I agree. This is a compelling reason not to do this.

**Comment by snicoll** [comment]
Thanks for the feedback. Let's close this one for now.
