### ISSUE TITLE
Rename ApplicationPidListener

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1673]
The current name doesn't really reflect what the class does. Perhaps `ApplicationPidFileWriter` would be better?

**Comment by jasperblues** [comment]
The docs for `ApplicationPidListener` include the deprecation note, but don't say which class instead. Had to come here to find out.

**Comment by philwebb** [comment]
@jasperblues I've raised a new issue to address this. Track #4743 for updates.
