### ISSUE TITLE
Changing the http response status causes the response body to disappear

### ISSUE THREAD

**Issue by matsev** [spring-projects/spring-boot#1677]
When a http request causes a web application to throw an exception such as `new IllegalArgumentException("Bad argument")` the client receives a response with a default error message:

```
HTTP Status 500 - Internal Server Error
{
    "timestamp": 1412861896541,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.IllegalArgumentException",
    "message": "Bad argument",
    "path": "/test"
}
```

The http response status code can be changed by using a `@ControllerAdvice` such as:

```
@ControllerAdvice
class CustomControllerAdvice extends DefaultHandlerExceptionResolver {

    @ExceptionHandler
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    void handleIllegalArgumentException(IllegalArgumentException e) {
    }
}
```

By doing so the status code is indeed updated, but the response body is not present anymore. Preferably, the client should receive a similar response as before, but with the new status code.

```
HTTP Status 400 - Bad Request
{
    "timestamp": 1412861896541,
    "status": 400,
    "error": "Bad Request",
    "exception": "java.lang.IllegalArgumentException",
    "message": "Bad argument",
    "path": "/test"
}
```

**Comment by 8804645769** [comment]
Please remove HTTP error 400

**Comment by ZaitsevY** [comment]
```
@ExceptionHandler(CustomException.class)
void handleCustomExcepption(HttpServletResponse response) throws IOException {
    response.sendError(HttpStatus.NO_CONTENT.value());
}
```
won't produce default error message as of Spring Boot 1.5.5

**Comment by wilkinsona** [comment]
@ZaitsevY This issue has been closed for almost two years. If you believe you have found a problem please open a new issue with a small sample that reproduces it.

**Comment by gredler** [comment]
See #5774 for a more recent discussion.

Based on a hint in one of the comments there, the following code seems to successfully modify the HTTP status code without losing the response body (using Spring Boot 1.5.6):

```
@ControllerAdvice
public class MyExceptionHandler {

    @ExceptionHandler(MyException.class)
    public void handle(HttpServletResponse response) throws IOException {
        response.sendError(HttpServletResponse.SC_BAD_REQUEST);
    }

}
```
