### ISSUE TITLE
@PropertySource and YAML support documentation

### ISSUE THREAD

**Issue by yatho** [spring-projects/spring-boot#16805]
Hi,

I found the following text in [Springboot documentation 24.7.4 YAML Shortcomings](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml-shortcomings): 
```
YAML files cannot be loaded by using the @PropertySource annotation. So, in the case that you need to load values that way, you need to use a properties file.
```
In fact, in my project, I tried to use yaml with this ```@PropertySource``` annotation with springboot 2.1.4 and in fact it works well.

Could you please explain me if I am doing something wrong, or maybe the documentation is not up to date.

**Comment by snicoll** [comment]
There is no official support for loading YAML files with `@PropertySource` and we don't intend to add one. Can you please clarify what you mean by "it works well"?

**Comment by snicoll** [comment]
As the report was unable to provide a working sample ([this is just a properties file](https://github.com/yatho/springboot-yaml-test/blob/095caa87f9d83548b6d171cb0ca50002301ace6d/src/main/resources/application-test.yaml) with a different extension), I am going to close this one.
