### ISSUE TITLE
spring-boot:run uses the wrong default working directory for a forked JVM

### ISSUE THREAD

**Issue by drahkrub** [spring-projects/spring-boot#16811]
I would like to migrate some ancient multi module spring application containing lots of JSPs to spring-boot.

I know https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jsp-limitations but some preceding (single module) tests all ran fine.

Since I would like to preserve the multi module structure, I first ran into a problem, which  fortunately has been solved here: https://github.com/spring-projects/spring-boot/issues/3436

So, I can start my multi module project with the usual `mvn spring-boot:run` but unfortunately JSPs can **not** be served this way!

I created a simple example project https://github.com/drahkrub/spring-boot-multi-module-jsp (a simplified version of https://github.com/spring-projects/spring-boot/tree/v2.1.4.RELEASE/spring-boot-samples/spring-boot-sample-tomcat-jsp turned into a multi module project) with the following minimalistic content:
```
.
├── pom.xml
└── webapp
    ├── pom.xml
    └── src
        └── main
            ├── java
            │   └── de
            │       └── idon
            │           └── sandbox
            │               ├── SandboxJspApplication.java
            │               └── WelcomeController.java
            ├── resources
            │   └── application.properties
            └── webapp
                └── WEB-INF
                    └── jsp
                        └── welcome.jsp
```
Now, if started with `mvn spring-boot:run` (or `mvn -pl webapp -am spring-boot:run`) http://localhost:8080/ gives
```
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/jsp/welcome.jsp
```
But if running the WAR file, i.e. `mvn clean package` followed by
```
java -jar webapp/target/spring-boot-multi-module-jsp-webapp-0.0.1-SNAPSHOT.war
```
http://localhost:8080 works as expected.

I noticed that `mvn spring-boot:run` also works if the content of `webapp/src/main/webapp` is copied in a folder `src/main/webapp` in the **parent module** (obviously the place expected by the spring-boot maven plugin if operating in single module mode).

Is there a clean solution for this problem?

I tried some of the parameters described [here](https://docs.spring.io/spring-boot/docs/current/maven-plugin/run-mojo.html) but maybe I've used them incorrectly or tried the wrong ones... ;-)

**Comment by wilkinsona** [comment]
Thanks for the sample.

This looks like a bug in Boot's Maven plugin to me. By default, the `run` goal's default working directory should be the `basedir` of the Maven project being built but that does not appear to be the case. Instead, the working directory is the directory in which Maven was invoked. You can work around the problem by adding the following to the configuration of `spring-boot-maven-plugin` in your `webapp` project:

```xml
<workingDirectory>${basedir}</workingDirectory>
```

**Comment by drahkrub** [comment]
@wilkinsona Thanks for the quick response and the workaround! I'd have bet I tried adding `<workingDirectory>${basedir}</workingDirectory>`...

**Comment by drahkrub** [comment]
@wilkinsona Follow-up question: Is it "normal" that system properties defined on the command line e.g.
```
mvn spring-boot:run -Dspring-boot.run.profiles=foo,bar
```
or
```
mvn spring-boot:run -Dspring.profiles.active=foo,bar
```
are **not** propagated to the forked JVM?

(the run process is forked if the parameter `workingDirectory` is used)

I digged into the source code: In `RunMojo#runWithForkedJvm(...)` the parameter `environmentVariables` is empty (or an empty map - I'm not sure right now) and also `args` does not contain definitions of system properties defined on the command line...

**Comment by drahkrub** [comment]
This works:
```
mvn clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.profiles.active=foo,bar"
```

**Comment by drahkrub** [comment]
Sorry for the mess, I just found https://github.com/spring-projects/spring-boot/issues/1095 where all this is explained... Right now I ran in a maybe related problem, I stay quiet until I understand better...

**Comment by snicoll** [comment]
> Follow-up question

@drahkrub Please don't raise different topics in the same issue and ask questions on StackOverlow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by drahkrub** [comment]
Ok, I think, I got it: There are several pitfalls when defining active profiles in Spring-Boot:
1. When working with the Spring-Boot Maven plugin the usage of `-Dspring.profiles.active=...` should IMHO produce a **bit fat warning** on screen, because it simply does not work if the JVM is forked which can implicitely happen when using specific parameters.
2. `-Dspring-boot.run.profiles=...` instead is the right way to go, but it can **only** be used with the Spring-Boot Maven plugin. It implicitely creates the command line argument `--spring.profiles.active=...` which in return **must** be consumed by `SpringApplication#run(...)`, therefore using `run(...)` without args should produce a **bit fat warning** in the logs, too.
3. When starting a JAR- or WAR-file then using `--spring.profiles.active=...` is problematic because of the aforementioned reasons. In this case the best way to go is using `-Dspring.profiles.active=...`, I think.

Looks a litte bit messy... ;-)

Would be interested to hear your opinion about that!
