### ISSUE TITLE
Enhance configuration binding options for elasticsearch

### ISSUE THREAD

**Issue by jeacott** [spring-projects/spring-boot#1681]
the autoconfiguration options for elasticsearch are far too limited to be useful in all but the most trivial cases.
  There is no opportunity to alter the discovery type, multicast behaviour or the myriad of other config available to ES.
  Elasticsearch itself provides a very convenient settings filter that can be handed directly to the 
client. 
eg:

```
ImmutableSettings.Builder settings = ImmutableSettings.settingsBuilder();
		settings.putProperties("spring.data.elasticsearch.", getEnvProperties());

Client client= NodeBuilder.nodeBuilder()
				.settings(settings)
				.node()
				.client();
```

if the boot elasticsearch module were to use this approach then spring boot elasticsearch users would trivially be able to append any existing or new elasticsearch configuration option to the standard boot config file with nothing more to do.

**Comment by ppuffinburger** [comment]
Isn't this issue resolved by wilkonsona's commit of 89b4cac8b05fdbbd5f116f4bc99e4a618302fbd9 which is in Spring Boot 1.2.3?

**Comment by jeacott** [comment]
actually not that commit (it was an initial attempt, it got improved a lot from that).
but this issue pre dates the one where it was fixed, so please link to it and close.
ref: https://github.com/spring-projects/spring-boot/issues/1838#issuecomment-82494615

**Comment by wilkinsona** [comment]
Implemented in https://github.com/spring-projects/spring-boot/commit/0a38b9b3ab38fbcb40f7006251b8bc8c89a5ccfa
