### ISSUE TITLE
Support setting mutual TLS verify depth

### ISSUE THREAD

**Issue by alex0ptr** [spring-projects/spring-boot#16818]
We are using Spring Cloud Gateway in combination with mutual TLS. Our clients authenticate with a certificate that is signed by an intermediate which in turn is signed by a self-signed CA. This CA is added to the trust store of our Gateway service. This setup works fine. There is however one major issue: some clients do not send the full certificate chain, but omit the root CA. This is allowed according to the TLS spec. However Spring Cloud Gateway responds with an TLS error in this case and we have no control over the clients.

For that reason some web servers like nginx [provide options](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_depth) to increase verification depth of the client chain.

I also found a similar parameter in the [Netty codebase](https://github.com/netty/netty-tcnative/blob/f06c0bac67e750236675707ded4e53f034ca3ac1/openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java#L489
). Although I'm not sure if this component is used in Reactor-Netty.

We would love to be able to change verification depth of client certificate chains and hope there is a Netty option that can be exposed on the `server.ssl` configuration level.

**Comment by philwebb** [comment]
I think we're unfortunately going to be blocked doing anything in Spring Boot until there are some upstream API changes. AFACT the public [SslContext API](https://github.com/netty/netty/blob/0a1786c32cb5d4ad3832c6072ff396873ee9dbc6/handler/src/main/java/io/netty/handler/ssl/SslContext.java) doesn't surface any way to configure this (at least there's a TODO in [ReferenceCountedOpenSslContext](https://github.com/netty/netty/blob/cf2f1f54b623a62e5632eb073cb20b766bc6fdc2/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java#L100) that suggests as much.

Can you raise an issue with reactor-netty to see if they have any suggestions. You might also need to raise an issue with Netty as well.

**Comment by alex0ptr** [comment]
We spent some more time on investigating the issue. Our test setup has a configuration issue and the above described issue does not exist. MTLS works, as expected, even if the client omits the root CA. Sorry for bothering you.
