### ISSUE TITLE
Cannot call HTTP when rsocket server is activated

### ISSUE THREAD

**Issue by belkirdi** [spring-projects/spring-boot#16826]
I tried to make rsocket server work with my api in webflux using the spring boot 2.2.0.M2 but unfortunately the http request stopped working

**Comment by belkirdi** [comment]
what I tried to explain is that you cannot call http request when rsocket server is activated

**Comment by philwebb** [comment]
I'm afraid there's not really enough information here to tell if we have a bug or if this is a configuration issue. Please could you provide a small sample that shows what you mean?

**Comment by belkirdi** [comment]
The issue still remaining in your latest version 2.2.0.M3. Please find below a sample code of how to reproduce the bug: (I find another issue is if if I define another port than default netty the Server doesn't respond to my http and rsocket request from a client )

package com.belkirdi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.messaging.handler.annotation.MessageExceptionHandler;
import org.springframework.messaging.handler.annotation.MessageMapping;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }


    @RestController
    public class RestApi {

        @GetMapping("/rest_test")
        public Mono<Boolean> sendBoolean() {
            return Mono.just(Boolean.TRUE);
        }
    }


    @Controller
    public class RSocketApi {

        @MessageExceptionHandler
        Flux<String> errorHandler(IllegalArgumentException iia) {
            return Flux.just("error");
        }

        @MessageMapping("/rs_test")
        Mono<Boolean> requestResponse() {
            return Mono.just(Boolean.TRUE);
        }
    }
}

Application.properties

package com.belkirdi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.messaging.handler.annotation.MessageExceptionHandler;
import org.springframework.messaging.handler.annotation.MessageMapping;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }


    @RestController
    public class RestApi {

        @GetMapping("/rest_test")
        public Mono<Boolean> sendBoolean() {
            return Mono.just(Boolean.TRUE);
        }
    }


    @Controller
    public class RSocketApi {

        @MessageExceptionHandler
        Flux<String> errorHandler(IllegalArgumentException iia) {
            return Flux.just("error");
        }

        @MessageMapping("/rs_test")
        Mono<Boolean> requestResponse() {
            return Mono.just(Boolean.TRUE);
        }
    }
}


pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.M3</version>
		<relativePath/> 
	</parent>
	<groupId>com.belkirdi.issue</groupId>
	<artifactId>rsocket-http</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>rsocket-with-http-server-issue</name>
	<description>Not able to use RSocket Server with HTTP Server at the same time</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-rsocket</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
	</pluginRepositories>

</project>

**Comment by belkirdi** [comment]
The workaround is to exclude spring-boot-rsocket and use the rsocket-core directly

**Comment by wilkinsona** [comment]
Here's a sample from @linux-china: https://github.com/linux-china/rest-404-with-rsocket

**Comment by belkirdi** [comment]
Please don't forget in the case of using a different port for rsocket server. Everything stop working http and rsocket
