### ISSUE TITLE
@ConfigurationPropertiesScan should import ConfigurationPropertiesBindingPostProcessorRegistrar

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#16822]
Configuration properties are bound via the `ConfigurationPropertiesBindingPostProcessor` which are registered by `ConfigurationPropertiesBindingPostProcessorRegistrar`. This registrar is imported by `@EnableConfigurationProperties` which happens to get switched on if an auto-configuration that has the annotation is switched on or if the user themselves adds the `@EnableConfigurationProperties` annotation. 

In a situation where auto-configuration is disabled or no auto-configuration class with `@EnableConfigurationProperties` kicks in (unlikely), user-defined `@ConfigurationProperties` registered via configuration properties scanning won't get bound.

**Comment by wilkinsona** [comment]
If we get [this change](https://github.com/spring-projects/spring-framework/issues/22995) in Framework, this will become unnecessary.

**Comment by snicoll** [comment]
The related issue has been fixed differently and we still have `@ConfigurationPropertiesScan` and friends so revisiting this issue is in order.
