### ISSUE TITLE
Adding custom SolrContext configured with zkServer

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#1682]
I needed to implement custom solr repository as current solr template is not able to meet my requirements. For that when i tried Autowired SolrTemplate, it raise an exception stating that it could not find bean. Hence I wrote a small class which does create a custom SolrContext. But it is not able to interact with zookeeper servers. All the properties are already configured in in application.properties like spring.data.solr.host and spring.data.solr.zkHost. I tried with CloudSolrServer class still bean not found. 
Am I missing something? 
 
```
@Configuration
@EnableConfigurationProperties(SolrProperties.class)
@EnableSolrRepositories("org.repository")
@PropertySource("classpath:application.properties")

public class SolrContext {

    @Resource
    private Environment environment;


    @Bean
    public HttpSolrServerFactoryBean solrServerFactoryBean() {
        HttpSolrServerFactoryBean factory = new HttpSolrServerFactoryBean();
        factory.setUrl(environment.getRequiredProperty("spring.data.solr.host"));

        return factory;
    }

    @Bean
    public SolrTemplate solrTemplate() throws Exception {
        return new SolrTemplate(solrServerFactoryBean().getObject());
    }
```

**Comment by wilkinsona** [comment]
It looks like this has been resolved. If that's not the case, please comment and we can reopen the issue.
