### ISSUE TITLE
Allow the comment prefix used in data source initialisation scripts to be configured

### ISSUE THREAD

**Issue by szumszym** [spring-projects/spring-boot#16820]
Any line in the schema script with a sql comment and without semi-colon at the end of that line causes that the next sql statement is not executed but the rest of the script will be executed anyway.

Spring Boot v2.1.4.RELEASE

DOESNT' WORK:
`DROP TABLE abc IF EXISTS;`
 `# blablabla`
`DROP TABLE efg IF EXISTS;`

DOES WORK:
`DROP TABLE abc IF EXISTS;`
 `# blablabla;`    <-- semi-colon added
`DROP TABLE efg IF EXISTS;`

(Please check if the issue occurs also for data.sql script)

**Comment by thackel** [comment]
I am pretty sure SQL comments are only
`-- line comment`
and
`/* block comment */`
but not starting with `#`.

So just change your DDL to use correct SQL comments and it will work.

**Comment by wilkinsona** [comment]
Spring Boot uses `ResourceDatabasePopulator` which is part of Spring Framework. By default, it uses `--` for line comments and `/* … */` for block comments. AIUI, these are the standard SQL comment types. Some databases, MySQL for example, also support `#` for line comments. The comment prefix used by `ResourceDatabasePopulator` can be configured, but Spring Boot does not expose this for its data source initialization. We can consider adding such a configuration option but I would recommend stick with the standard SQL comment syntax.

**Comment by philwebb** [comment]
I think it's better that we keep ourselves aligned with the defaults in Spring Framework. A configuration option for such an edge case feels a bit too much. Only allowing standard SQL comments will also help keep scripts portable if developers ever choose to move to a different server.
