### ISSUE TITLE
spring-boot-data-jpa : show information about physical-strategy and implicit implicit-strategy settings in log

### ISSUE THREAD

**Issue by ah1508** [spring-projects/spring-boot#16832]
As written [here](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-configure-hibernate-naming-strategy), by default Spring apply a naming strategy which is not the hibernate 5 default strategy.

Then, moving from JPA / hibernate + spring-orm to spring-boot-starter-jpa can lead to errors which are not  always easy to fix.  At best the query execution fails and the sql log helps to understand the cause of the problem, at worst the `entityManagerFactory` cannot even be built (and then the error message doesn't say anything about naming strategy, and many average hibernate users don't even know the concept of naming strategy). 

Since Spring applies settings which are not default Hibernate settings, I think it should be mentioned in the log when the application starts (something like the WARN message when `spring.jpa.open-in-view` is not set.), with maybe a link to the documentation. Adding the following lines to solve the issue
```
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
```
is far from obvious.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think a warning is appropriate here. Unlike the open in view support, the naming strategy does not bring with it a risk of unexpected performance problems. Instead, it's just part of Spring Boot's opinionated defaults. As you've already noted, the default is [already documented](https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#howto-configure-hibernate-naming-strategy) and I think that is sufficient.
