### ISSUE TITLE
Problem accessing SQL data

### ISSUE THREAD

**Issue by elidor22** [spring-projects/spring-boot#16834]
There is  a bug in which while trying to access data from relational databases using Spring Data JPA, it can delete the whole table if the user tries to access the backend url using partial link, eg only demo not demo/all, the framework deletes the whole database table. 

Even the code in your tutorial page creates this bug:
https://spring.io/guides/gs/accessing-data-mysql/#_create_the_entity_model

In my case I have a Mysql database hosted in GCP and the code used was the same as the one included in the tutorial page cause I was just testing Spring as a possible backend framework for a mobile app. The bug is simple to be reproduced, just access http://localhost:8080/demo instead of http://localhost:8080/demo/all 

Hopefully this bug will be fixed soon

**Comment by philwebb** [comment]
I'm unable to replicate the problem using the getting started guide. When I run the complete application I can do the following:

```
$ curl 'localhost:8080/demo/add?name=First&email=someemail@someemailprovider.com'  
```

I can then check the contents of the database:
```
$ mysql -uspringuser -pThePassword 
use db_example;
select * from user;
+----+---------------------------------+-------+
| id | email                           | name  |
+----+---------------------------------+-------+
|  1 | someemail@someemailprovider.com | First |
+----+---------------------------------+-------+
1 row in set (0.00 sec)
```

I then tried:

```
$ curl 'localhost:8080/demo/'
```

This gave me an error:
```
{"timestamp":"2019-05-14T04:34:15.968+0000","status":404,"error":"Not Found","message":"No message available","path":"/demo/"}% 
```

Checking the contents of the database again showed the user table still contained an entry.

Since the `/demo` path is not mapped to any controller method, it's not clear to me how it could be deleting the database.

Please could you provide a sample application that we can unpack and run, along with some detailed instructions on how to reproduce the issue?

**Comment by elidor22** [comment]
So I am submitting the whole project with a few small modifications in it's table code. GCP managed Mysql was used in my case. The used database is from a test account, but without adding users public IP, it is impossible to access it from another computer connected to another network that is not registered in google cloud account. I am using IntelliJ Ultimate, Java 11 and Gradle in this project. I also recorded the screen while this problem occurs in order to give a better idea how this happens. In the video Datagrip is the program used to show the database table, however that table was displayed by a simple classic java code used to query relational datasources. 
Hopefully the submitted material in the following dropbox folder helps:
[](https://www.dropbox.com/sh/qxfo35h20eo82fb/AABfFepmam0RW2vjYB3urgGRa?dl=0)

**Comment by wilkinsona** [comment]
Thanks for the sample, but it doesn't appear to contain any source code. Could you please update it?

**Comment by elidor22** [comment]
Ok, just uploaded it on Google drive, this link is functional:
https://drive.google.com/drive/folders/1thoVxvEXUL76lwl_ChHyUxFmaZXN97HB?usp=sharing

**Comment by philwebb** [comment]
I'm having some trouble running the app, but I noticed some errors in the log. Can you add the following to your `application.properties`

```
spring.jpa.show-sql=true
```

Then run the application again and paste the log in here.

**Comment by elidor22** [comment]
[SpringErrorLog.docx](https://github.com/spring-projects/spring-boot/files/3178824/SpringErrorLog.docx)

`

**Comment by philwebb** [comment]
Thanks, but can you include the full log up to the point that the data gets deleted? i.e. after you call the URL in postman.

**Comment by elidor22** [comment]
It looks like the table class is the one who deletes the table then Spring cannot find anything after getting the request from postman. Maybe the problem is between SPring and Hibernate annotations in Table1 

[SpringERRLog.docx](https://github.com/spring-projects/spring-boot/files/3178952/SpringERRLog.docx)

**Comment by philwebb** [comment]
Yes, I see what's going on here. You have the following your `application.properties`:

```
spring.jpa.hibernate.ddl-auto=create
```

This tells Hibernate to create new tables when it starts. You can see this in the logs here:

```
Hibernate: drop table if exists hibernate_sequence
Hibernate: drop table if exists table2
Hibernate: create table hibernate_sequence (next_val bigint) engine=MyISAM
```

The Google hosted MySQL instance [does not support](https://cloud.google.com/sql/docs/mysql/diagnose-issues) `MyISAM` so the drop command works but the create command does not.

The query you make with postman actually isn't responsible for the table being dropped. Just starting the app is enough to trigger the problem.

Remove the `spring.jpa.hibernate.ddl-auto` property and I think your app will start.

**Comment by elidor22** [comment]
Thanks! After removing spring.jpa.hibernate.ddl-auto everything is actually right.
