### ISSUE TITLE
Flyway and Liquibase auto configurations require DataSource bean to be declared

### ISSUE THREAD

**Issue by L00kian** [spring-projects/spring-boot#16849]
Hello,

`LiquibaseAutoConfiguration` and `FlywayAutoConfiguration` both require `DataSource` bean to be declared. However both configurations allow to explicitly define datasource properties which would create one anyway.

Context: I've been playing around with r2dbc and tried to assemble an application with it + flyway. was not able to apply migrations as there is no need for datasource when using r2dbc (also don't really fancy the idea that i need one living in context just for migrations spring-projects/spring-data-r2dbc#40 which is not directly related but explains why)

Regards,
Ilya

**Comment by philwebb** [comment]
Thanks for the PR, I'll close this issue and we can continue the discussion on #16850
