### ISSUE TITLE
Reinstate htmlsingle and PDF reference docs

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16854]
b527d364dc972a821149e47254256f51a5adab9d has reintroduced the single page documentation but it's not all that discoverable since the multi-page version always shows up at https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/ which hides the fact that the https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/single-index.html file exists.

I think we should try to also restore the previous folder structure.

**Comment by bclozel** [comment]
I think reinstating the former `htmlsingle` folder only solves one problem: keeping those URLs alive, like `https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/` for existing browser bookmarks.

Now the discoverability/docs variants problem is much bigger than that:

* we're not consistent when pointing to the reference docs on our project page; sometimes pointing the single page, other to the multi-page version
* browsing the static server index pages IMO does not count as a nice way to discover documentation variants
* in the 2.1.x line we were generating the docs twice independently and then trying to link one to another (without any guarantee, just relative links)

I think we should solve the problem in two parts:

1. make sure that those bookmarks are still valid for the well-known aliases like `/current` and `/current-SNAPSHOT`. A rewrite rule or an index page that redirects to the new one should work.
2. find a way to make the single page variant easier to find, but still linking to the multi-page one by default (friendlier for slower Internet connections and devices). Maybe a proper link on the multi-page index as well (and not only the documentation overview section?)

**Comment by philwebb** [comment]
I think I've restored the `html`, `htmlsingle` and `pdf` folders which should get us back to parity with 2.1.x. 

@bclozel Do we need to open new issues to cover the additional items from your comment above?
