### ISSUE TITLE
ConfigurationPropertyName.equals can fail with dashed names

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16855]
Raised by @snicoll in Slack

Found what might be a very weird bug in binding. I wasn’t able to reproduce in an isolated test but you can easily update one to reproduce it here: https://github.com/spring-projects/spring-boot/blob/4d8df3cc47b7abca2ea966491fbaf7656b39891d/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/metrics/web/reactive/WebFluxMetricsAutoConfigurationTests.java#L119 - Just remove the `s` in `requests` (so the last character of the property) and the test will pass. I confirmed it was binding to the setter.

Looks like, in this particular case, binding does not care if there is a “s” at the end or not. I’ve tried other combination and the test was failing as it didn’t bind

**Comment by philwebb** [comment]
This only appears to happen on master, 2.1.x seems fine.

**Comment by dreis2211** [comment]
I'm very sorry for this one. Good catch!

**Comment by philwebb** [comment]
@dreis2211 Don't worry about it. It's really easy to mess up the logic in those equals methods (I speak from experience)!
