### ISSUE TITLE
Document the properties used by spring-boot-dependencies to control dependency versions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16868]
We have [an appendix](https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#appendix-dependency-versions) that documents `groupId`, `artifactId`, and `version` for all of the dependencies managed by `spring-boot-dependencies`. I think it would also be useful to document the version property, if any, that determines each version. It would make things easier for users who want to override a dependency version.

I'm not 100% sure that the is possible due to bom imports and our current approach of extracting the versions from the effective pom, by which point the version properties have been lost.

**Comment by codebuster007** [comment]
Hi! @wilkinsona ,

I'd like to know if this issue has been resolved or assigned to anyone because I'll love to work on it.

Thanks.

**Comment by wilkinsona** [comment]
Thanks very much for the offer, @codebuster007. This has been implemented in https://github.com/spring-projects/spring-boot/pull/19898 but we forgot to close this issue. I'll do that now.
