### ISSUE TITLE
/actuator/httptrace endpoint not available in 2.2.0.M3

### ISSUE THREAD

**Issue by bahrigencsoy** [spring-projects/spring-boot#16870]
I was actively working on a small project with Spring Boot `2.2.0.M2` while I received the email for `2.2.0.M3` release, and immediately upgraded.

I noticed that the web exposure of the `httptrace` is not respected anymore:

```
server.port=8070
spring.main.lazy-initialization=true
management.endpoint.httptrace.enabled=true
management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=health, info, httptrace, shutdown, loggers
```

Gives error on `http://localhost:8070/actuator/httptrace`:

```
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Wed May 15 15:04:05 EET 2019
[3482b46f] There was an unexpected error (type=Not Found, status=404).
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
	at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$0(ResourceWebHandler.java:325)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
```

Further analysis shows that it is not enabled at-all: `http://localhost:8070/actuator/`

```json
{
_links: {
self: {
href: "http://localhost:8070/actuator",
templated: false
},
health: {
href: "http://localhost:8070/actuator/health",
templated: false
},
health-component: {
href: "http://localhost:8070/actuator/health/{component}",
templated: true
},
health-component-instance: {
href: "http://localhost:8070/actuator/health/{component}/{instance}",
templated: true
},
info: {
href: "http://localhost:8070/actuator/info",
templated: false
},
loggers: {
href: "http://localhost:8070/actuator/loggers",
templated: false
},
loggers-name: {
href: "http://localhost:8070/actuator/loggers/{name}",
templated: true
}
}
}
```

I can confirm that changing the version back to 2.2.0.M2 fixes the problem.

**Comment by wilkinsona** [comment]
Sorry for the inconvenience but this is intentional. Please see the [relevant section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2.0-M3-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default) of the release notes for details.

**Comment by aru-royal** [comment]
@wilkinsona  Thank for clarification , I have been struggling to add httptrace.  You have mentioned by contributing bean for HttpTraceRepository we can achieve httptrace. Can you please share any sample piece of code

**Comment by snicoll** [comment]
@aru-royal please review the section Andy already shared. If you have more questions, please ask on StackOverflow or join the community on Gitter.
