### ISSUE TITLE
Jackson auto-configuration code does not appear to match documention

### ISSUE THREAD

**Issue by NedAmes-acc** [spring-projects/spring-boot#16884]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-jackson-objectmapper indicates that 

`MapperFeature.DEFAULT_VIEW_INCLUSION` is disabled
DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is disabled
SerializationFeature.WRITE_DATES_AS_TIMESTAMPS is disabled

The corresponding source code, https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java, only sets `featureDefaults.put(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);`

Is the documentation out of sync?

**Comment by philwebb** [comment]
The documentation is correct. Those specific defaults are provided by Spring Frameworks [Jackson2ObjectMapperBuilder](https://github.com/spring-projects/spring-framework/blob/ed2a3bd451ca8a330bb1ef7fb5e9f06a2fb5793c/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L729-L736).
