### ISSUE TITLE
Spring boot upgrade from 2.1.4 to 2.1.5 release

### ISSUE THREAD

**Issue by casper5822** [spring-projects/spring-boot#16882]
Hello,

I tried to upgrade my spring boot project from 2.1.4_RELEASE to the 2.1.5_RELEASE
I got many errors when i changed the maven version, the errors are the same:

Maven Configuration Problem.

I tried multiple times:

Clean project,
Force Maven Update with forced download
And anything work.
Maybe there is a problem in your maven rep, because the 2.1.4 works well.

My environment:
* Spring boot 2.1.4_RELEASE
* STS 4.2.0
* JDK 12

Thank you
Best regards

**Comment by philwebb** [comment]
If these errors are only in your IDE then It sounds like you might be hitting https://github.com/spring-projects/spring-boot/issues/16846#issuecomment-492792506.

Does downgrading the plugin fix the problem?

```
<properties>
  <maven-jar-plugin.version>3.1.1</maven-jar-plugin.version>
</properties>
```

**Comment by casper5822** [comment]
Yes, it fixes the problem, it is the same problem. Thank you for the help.

**Comment by wilkinsona** [comment]
A fix for Eclipse is now available. Please see https://bugs.eclipse.org/bugs/show_bug.cgi?id=547340#c9 for details.
