### ISSUE TITLE
Liquibase includeAll YML

### ISSUE THREAD

**Issue by pkempec** [spring-projects/spring-boot#16888]
## Versions
Liquibase: 3.6.3
SpringBoot 2.0.2.RELEASE

## Description
Using tag includeAll does not work when running application from jar file.
When running the same code directly from IDE (IntelliJ) it is working fine.

## Workaround
Use include tag and specify each file.

**Comment by wilkinsona** [comment]
Thanks for the report. This is a [known problem](https://liquibase.jira.com/browse/CORE-3344) with Liquibase that is out of Spring Boot's control. Please continue to use your workaround until the Liquibase issue has been resolved.
