### ISSUE TITLE
Use deferred logging rather than System.out to report jars on the classpath with Class-Path manifest attributes that point to non-existent files when using DevTools

### ISSUE THREAD

**Issue by TurtleBeach** [spring-projects/spring-boot#16883]
When I run a spring-boot application that depends on **azure-spring-boot-starter** (created by **spring-initialzr**), a message indicates various grpc jar files listed in the manifest for grpc-netty-shaded-1.14.0.jar do not exist. The manifest apparently expects all associated grpc jar files to be in the same folder as grpc-netty-shaded-1.14.0.jar (i.e., **…\io\grpc\grpc-netty-shaded\1.14.0\**), yet in my local repository the associated jars each exist in separate folders under **...io/grpc** (for example, the grpc-core jar is at **…\io\grpc\grpc-core\1.14.0\grpc-core-1.14.0.jar**).

The misconfiguration appears to have no impact on actually running the application, but it is disconcerting to see the message, and it is not clear under what circumstances things might break as I add more functionality to the application.
Jack

**Comment by wilkinsona** [comment]
Thanks for the report. It's not clear what message you are referring to, but an educated guess is that you're using DevTools and the message is being output by this code:

https://github.com/spring-projects/spring-boot/blob/cce8c45ae63d2d10f781963e40b6a65c18abc112/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/ChangeableUrls.java#L181-L183

Can you please provide some more information about the circumstances in which you are seeing the message?

**Comment by TurtleBeach** [comment]
Yes, I did select DevTools when I created the spring-boot application using spring-initializr, at spring.io.
The message appears as the last line of a bunch of lines which appear in the Netbeans Output window right before the Spring ascii art and subsequent application startup logging information. (Running in Netbeans IDE 8.2). To create the Netbeans project, I imported the zip file generated by spring-initializr into Netbeans, then let Netbeans get all the dependencies.
The message does not appear when I build a Jar file (using .mvnw command line outside of Netbeans).
Jack

**Comment by wilkinsona** [comment]
Thanks. The problem really lies with the manifest of grpc-netty-shaded-1.14.0, the contents of which are out of Spring Boot's control. The message that's being output is a symptom of that problem. We can probably improve things a bit by switching from `System.out` to DevTools' deferred logging support at info level. We'll use this issue to do that.
