### ISSUE TITLE
STS + Spring Boot 2.2.0 M3 = Maven issue

### ISSUE THREAD

**Issue by romainmoreau** [spring-projects/spring-boot#16899]
### Summary
Since Spring Boot 2.2.0 M3, STS 4 is not able anymore to correctly configure Maven projects.
When switching back to Spring Boot 2.2.0 M2, the issue is gone.

### Optional reproducing steps
_Just to make sure it's reproducible with a fresh STS and is not related to a faulty workspace, plugin, etc._
1. Download the latest STS from https://spring.io/tools (`4.2.1.RELEASE` at current date).
2. Unzip and open.
3. Create a new workspace as proposed in the first run.

### Actual reproducing steps
1. Go to `File` → `New`→ `Spring Starter Project`.
2. Hit `Next` to keep defaults.
3. Select `2.2.0 M3` in `Spring Boot Version`.
4. Click on `Next` (the generated URL should be `https://start.spring.io/starter.zip?name=demo&groupId=com.example&artifactId=demo&version=0.0.1-SNAPSHOT&description=Demo+project+for+Spring+Boot&packageName=com.example.demo&type=maven-project&packaging=jar&javaVersion=1.8&language=java&bootVersion=2.2.0.M3`) and `Finish`.
5. Wait for the build to finish and have a look at the `Problems` view: there is an error on the `pom.xml` which has `Unknown` as description and whose location is `line 1`.

### Workaround steps
1. Open the `pom.xml` and replace on line 8 `2.2.0.M3` by `2.2.0.M2`.
2. Right click on the project in the `Package Explorer` then click on `Maven` → `Update Project...` finally click on `OK` and the project now builds fine without any errors.

**Comment by belkirdi** [comment]
I have the same problem in eclipse but work fine in intellij

**Comment by romainmoreau** [comment]
I'm not sure either where this issue really comes from: maybe there is something broken in a POM since Spring Boot 2.2.0.M3 or maybe the issue is in the M2Eclipse plugin.
I tend to believe in the first hypothesis but I have nothing to confirm it as I saw nothing interesting in the Eclipse log during my tests.

**Comment by romainmoreau** [comment]
I made more tests and it seems the issue comes from the latest version of `maven-jar-plugin`.
So another workaround is to just add this property: `<maven-jar-plugin.version>3.1.1</maven-jar-plugin.version>`.

**Comment by snicoll** [comment]
Thanks for the reproduction. This has been reported several times already, see #16846 for more details.
