### ISSUE TITLE
ConfigurationProperties failed to convert java.lang.String to long after upgrading from 2.1.4 to 2.1.5

### ISSUE THREAD

**Issue by hmmlopez** [spring-projects/spring-boot#16895]
After upgrading from version 2.1.4 to 2.1.5 I'm getting the following error:

> Failed to bind properties under 'storage.file-size' to long:
> 
>     Property: storage.file-size
>     Value: 512MB
>     Origin: class path resource [application.yml]:2:14
>     Reason: failed to convert java.lang.String to long

Here is the code to reproduce:

```java
package com.example.datasize;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;
import org.springframework.util.unit.DataSize;

@Slf4j
@SpringBootApplication
public class DataSizeApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(DataSizeApplication.class, args);
		log.info("File Size: " + context.getBean(Storage.class).getFileSize());
	}

	@Component
	@ConfigurationProperties(prefix = "storage")
	public class StorageProperties extends Storage {
		public void setFileSize(DataSize fileSize) {
			super.setFileSize(fileSize.toBytes());
		}
	}

	@Data
	public class Storage {
		private long fileSize;
	}

}
```

And the `application.properties`:

> storage.file-size=512MB

Humphrey

**Comment by philwebb** [comment]
Can you share your `Storage` class? Or better still a full sample that we can run. My best guess is that you have overloaded setters and #16206 is coming into play.

**Comment by wilkinsona** [comment]
I think you're right, Phil. With `Storage` being a Lombok `@Data` class, the `StorageProperties` sub-class will have both `setFileSize(long)` and `setFileSize(DataSize)` methods.

**Comment by philwebb** [comment]
Oh I missed the fact it was a nested classes, I'm not used to Lombok!

I don't think is a bug since the old behavior wasn't predicable. You should update `Storage` so that it uses `DataSize` as its type, then use `storage.getFileSize().to...` if you need to convert it.

**Comment by hmmlopez** [comment]
Phillweb all classes are inner classes and provided in the code above. I'm using Lombok with @Data annotation. As Wilkinsona commented is correct the StorageProperties will have both methods (overloaded). I wonder why this error is popping up with the latest version of spring boot 2.1.5 because the versions before it was working fine.

**Comment by philwebb** [comment]
The error is due to the change we made for #16206. When the binder is trying to find the setter to use, in Spring Boot 2.1.4 it would just pick the first that it found (In your case that happened to be `setFileSize(DataSize fileSize)`).

We now check that if more than one setter is available, we call the one that matches the getter. So in your example we have the following to choose from:

```
setFileSize(DataSize fileSize) 
setFileSize(long fileSize)
long getFileSize()
```

We see there is `getFileSize` that returns a `long` so we pick the corresponding setter.
