### ISSUE TITLE
ConditionalOnMissingBean does not handle `annotation` correctly

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#16907]
I have an `@Bean` method annotated with `@ConditionalOnMissingBean(value = RestTemplate.class, annotation = MyQualifier.class)`. This condition fails because of matching a completely different `RestTemplate` bean in the context.

Debugging `OnBeanCondition`, it seems that COMB delegates to the standard `getMatchingBeans` and fails to apply De Morgan's laws by flipping the union of matches into an intersection of matches. This is particularly pernicious because COMB *implicitly* adds the type as a constraint, so removing the `value` parameter does not make it work.

I suspect that `OnBeanCondition:161` should be using `isAllMatched()` instead of `isAnyMatched()`.

I'm using Boot 2.1.4.

**Comment by wilkinsona** [comment]
> I suspect that OnBeanCondition:161 should be using isAllMatched() instead of isAnyMatched().

`ConditionalOnMissingBean` is intentionally an `OR`-based match while `ConditionalOnBean` is an `AND`-based match. Switching to `isAllMatched` as suggested would make `ConditionalOnMissingBean` an `AND`-based match which would be an unwanted and breaking change.

It sounds like you may want a negated `@ConditionalOnBean` which could be achieved with `NoneNestedConditions` and a single nested condition, but I can't be sure based on the information provided. Can you please take a step back and describe what you're trying to do?

**Comment by chrylis** [comment]
`@ConditionalOnMissingBean(annotation=)` *does not work* because it implicitly adds a type condition defaulted from the annotated element, and then that type condition is OR'd.

I am, very simply, trying to do this:

```
@Bean
@ConditionalOnMissingBean(annotation = SpecificRestTemplateQualifier.class)
public RestTemplate customRestTemplate() { ... }
```

This COMB matches *any* `RestTemplate` present in the context.

**Comment by wilkinsona** [comment]
Thanks. _Does not work_ (complete with italics) is, I think, an overstatement. It does not work for your specific use case and I think that's only the case when used on a `@Bean` method. Have you tried moving the definition of your `customRestTemplate` bean into a nested inner class and annotating the class with `@ConditionalOnMissingBean` instead?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
