### ISSUE TITLE
Documentation clarification on ConditionalOnMissingBean

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#16906]
The documentation for the value/type on `@ConditionalOnMissingBean` read:

> The condition matches when no bean of each class specified is contained in the `BeanFactory`.

It would be helpful to clarify which of these cases is meant:

> The condition matches when no bean of any of the classes specified is contained in the `BeanFactory`.

> The condition matches when every class specified has no bean in the `BeanFactory`.

**Comment by wilkinsona** [comment]
I don't think I understand the clarification that you'd like to be made. I've read the two cases four or five times now and can't see any difference in meaning. 

Perhaps it would help if I attempted to describe the current behaviour?

For each class, `@ConditionalOnMissingBean` looks for a bean in the `BeanFactory` of that type. It will match when it does not find any beans of any of those types. It will not match if it finds one or more beans that is of any of those types.

**Comment by chrylis** [comment]
The meaning (along with the phrasing on line 31, which I believe intends "Each requirement must be unmet") is ambiguous in English. Example:

`@ConditionalOnMissingBean({A.class, B.class})`

A bean of type `A` is present in the context. No bean of one of the classes (`B`) is present.

The text "matches when no bean of each class specified" can mean "∀ class, class ∉ context" (the intended meaning, and my first case) or "∃class, class ∉ context" (my second case).

I know this is a very fine point, but the behavior tripped me up, and I've been writing auto-configuration classes since 0.5.0, and the ambiguity can be eliminated by rephrasing the quantifier as in my first case.

**Comment by bclozel** [comment]
All three options look fine to me:

> The condition matches when no bean of each class specified is contained in the BeanFactory.

> The condition matches when every class specified has no bean in the BeanFactory.

> The condition matches when, for every class specified, the BeanFactory has no bean of that type.

This issue seems to be about "is this a OR or an AND"? Both descriptions look simpler than `∃class, class ∉ context`, which only brings back painful memories of maths and algorithm courses. 

Not being a native speaker, I'm still perfectly fine with the current situation.

**Comment by snicoll** [comment]
> Not being a native speaker, I'm still perfectly fine with the current situation.

Same and I am going to close this issue.
