### ISSUE TITLE
spring-boot-devtools have problem with 'Reload Static Content' when add a same named file after delete it

### ISSUE THREAD

**Issue by zhaoxiong** [spring-projects/spring-boot#16908]
I try the tutorial  "Serving Web Content with Spring MVC" on website "https://spring.io/guides/gs/serving-web-content/". I download the code with git , and open it with idea. i add  spring-boot-devtools to the pom.xml file . when i add a new file  'greeting.html' in 'templates' folder, it works well without restart . but when i do the following step, it have some problem:
1.delete the file 'greeting.html' exists  in the templates folder
2.refresh the browser, of course it will report error , that is not the point ,do the next
3.add a new file with the same name 'greeting.html' to the templates folder
4.refresh the browse , now that is the point , the browser still reports error

**Comment by snicoll** [comment]
@zhaoxiong I've completed the steps as you've described them and it works for me. When I refresh at point 4 I get the page again. Can you please review the steps and help me reproduce the problem on my side?

**Comment by zhaoxiong** [comment]
sorry, my bad . try that with eclipse , it works well. I just try Idea recently, there must be some problem with the configuration of idea,maybe i will figure it out later. thanks a lot

**Comment by robozb** [comment]
Maybe this problem is similar to the above: https://github.com/spring-projects/spring-boot/issues/33668
