### ISSUE TITLE
Review on ConfigurationPropertiesBeanDefinition

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#16903]
There is a leftover of a review on `ConfigurationPropertiesBeanDefinition` that we should address.

**Comment by philwebb** [comment]
I've removed the FIXME for now so we can release, but I'd like to take another look at this. I have a feeling we might be able to move some of the logic from `ConfigurationPropertiesBeanDefinition` and `ConfigurationPropertiesBindingPostProcessor` into `ConfigurationPropertiesBinder`.

**Comment by mbhave** [comment]
@philwebb If you haven't started on this already, might be better to wait till we decide what to do in #16712.

**Comment by snicoll** [comment]
@philwebb this issue is now ready as #16172 has been declined.
