### ISSUE TITLE
ReactiveRedisTemplate  reactiveRedisTemplate

### ISSUE THREAD

**Issue by 3tem** [spring-projects/spring-boot#16904]
use the `reactiveRedisTemplate.opsForValue().set("test:"+i, st).block()`, this string key is messy code.
but i use the `redisTemplate` and the configuration `setKeySerializer` this key is not  messy code

**Comment by snicoll** [comment]
@3tem sorry but I don't understand what you are reporting. If you are reporting a bug against Spring Boot, this has to be related to the way we auto-configure `reactiveRedisTemplate`. If that's against a feature of Spring Data Redis, their issue tracker (with a sample that shows the issue) is the right place. 

If you're having a question, you should use StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.  Can you please clarify?

**Comment by 3tem** [comment]
ok，please close the problem。
