### ISSUE TITLE
Spring Boot Actuator with custom web security problem

### ISSUE THREAD

**Issue by hasanbirol89** [spring-projects/spring-boot#16929]
Hi,

I am using spring-boot-actuator(2.1.5 RELEASE). But, i got 404 when i sent a request http://localhost:8080/actuator/health. I have also custom spring security class that annotated with @EnableWebSecurity. If I exclude my class of jar, i am getting 200 with health response..

There is no match with the request still gets 404

Thanks.

___________________________________ Debug Security _____________________________

Getting no match still gets 404 notfound.. 

Request received for GET '/actuator/health':

org.apache.catalina.connector.RequestFacade@27b93e1e

servletPath:
pathInfo:/actuator/health
headers: 
host: localhost:8080
connection: keep-alive
accept: */*
accept-encoding: gzip, deflate, br
cookie: JSESSIONID=0FE49206B93BE9F296CBC5E87D5C2684

Security filter chain: no match

************************************************************

2019-05-21 16:40:48.953  INFO 18492 --- [nio-8080-exec-1] Spring Security Debugger                 : 

************************************************************

Request received for GET '/error':

org.apache.catalina.core.ApplicationHttpRequest@2bb5a81b

servletPath:
pathInfo:/error
headers: 
host: localhost:8080
connection: keep-alive
accept: */*
accept-encoding: gzip, deflate, br
cookie: JSESSIONID=0FE49206B93BE9F296CBC5E87D5C2684

Security filter chain: no match

************************************************************

__________________________________________________________________________

**Comment by hasanbirol89** [comment]
Also, when i change management.server.port=8089 It runs in a  successful way.. Why could I run it in spring boot tomcat port?

**Comment by hasanbirol89** [comment]
management.endpoints.web.base-path=/actuator
management.server.port=8089 

It runs in a successful way. <ctrl+b>
I guess, security parts are different. </ctrl+b>

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, it's hard to know exactly what's happening and why from the description provided. If you'd like us to spend some time investigating, can you please spend some time to provide a complete and minimal sample that reproduces the problem? A project zipped and attached to this issue or hosted in a separate repository on GitHub would be ideal.

**Comment by hasanbirol89** [comment]
I will send a sample code.Thanks for helping

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by hasanbirol89** [comment]
The problem is giving 404 http error instead of 403
