### ISSUE TITLE
Using eclipse to import the project, the pom file will display "unknow error", but IDEA will not

### ISSUE THREAD

**Issue by bpzhang** [spring-projects/spring-boot#16951]
Spring boot Version:2.1.5
Using eclipse to import the project, the pom file will display "unknow error", but IDEA will not.
When I lower the version to 2.1.4, it will display normal.

**Comment by wilkinsona** [comment]
Thanks for the report, but please take a moment to search for existing issues before opening a new one. This has already been reported several times already. See https://github.com/spring-projects/spring-boot/issues/16846 for details. A fix for Eclipse is now available.
