### ISSUE TITLE
Disable auto-configuration of HiddenHttpMethodFilter by default

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#16953]
`WebMvcAutoConfiguration` currently configures a lot of components that are specific to use of Spring MVC with a templating engine to produce server-side generated `text/html` content. An example of this is `HiddenHttpMethodFilter`, which is enabled by default. Such components present an unnecessary overhead when Spring MVC is solely used to produce e.g. `application/json` based APIs.

This has caught my attention after we discovered that the aforementioned `HiddenHttpMethodFilter` has been taking up to 80% of processing time on certain endpoints. While it was simple enough to disable the filter using `spring.mvc.hiddenmethod.filter.enabled` property, you have to do it in each project and I believe configuration could be made more lightweight there. In the case of this particular filter, a case could be made that it's not really needed even in all projects that use a templating engine.

**Comment by philwebb** [comment]
I'm not sure we've got a good signal that we won't need the `HiddenHttpMethodFilter`. Perhaps we could make it conditional on a `ViewResolver` bean. It feels a bit risky.

@vpavic I'm curious why `HiddenHttpMethodFilter` was taking so much time, it doesn't seem to do all that much. Did you ever discover the cause?

**Comment by vpavic** [comment]
Before opening this issue I also explored options around `ViewResolver` being the condition but wasn't able to come up with anything since `defaultViewResolver` (which is `InternalResourceViewResolver`) will always be there.

The endpoints that were affected by this were accepting `MultipartFile` request parameter - we didn't look that deep in since disabling the filter basically fixed the problem and improved performance significantly but I assume this was related to size of the request as `HiddenHttpMethodFilter` does `ServletRequest#getParameter`. Here's an example of how it looked in New Relic:

![Screenshot from 2019-05-29 18-52-26](https://user-images.githubusercontent.com/1149230/58576332-5f505d00-8244-11e9-98d2-a24af7773d83.png)

Anyway, after taking a closer look at `WebMvcAutoConfiguration` I realized that significant part of it was not needed where you're using Spring MVC to simply serve API and not server-side generated HTML. Having in mind that nowadays a setup like this is quite common I'd like to see Spring Boot provide a way to have more suitable (i.e. reduced) set of MVC components registered.

**Comment by vpavic** [comment]
Seeing this issue was repurposed to only handle disabling of auto-config for `HttpMethodFilter`, does that mean the original proposal of more substantial `WebMvcAutoConfiguration` simplification for applications that don't use templating engine won't be explored?

**Comment by philwebb** [comment]
@vpavic I think we just missed that there might be additional items that we might be able to simplify. I've opened #17354. Feel free to add any suggestions to that issue.

**Comment by destan** [comment]
@wilkinsona in `spring-boot-starter-parent:2.2.0.M6` default value of `spring.mvc.hiddenmethod.filter.enabled` is reported as `true` but `HiddenHttpMethodFilter` is not autoconfigured.

Moreover, when we explicitly set `spring.mvc.hiddenmethod.filter.enabled` to true then `HiddenHttpMethodFilter` is autoconfigured and works as expected.

![image](https://user-images.githubusercontent.com/442813/65832593-77a5b680-e2ce-11e9-83e8-3e4f0a8406e7.png)

![image](https://user-images.githubusercontent.com/442813/65832628-f3076800-e2ce-11e9-81bc-e5d967499329.png)

**Comment by snicoll** [comment]
@destan thanks, that's an oversight in the metadata and we already have a PR to fix that.
