### ISSUE TITLE
SpringBootVersion fails with a NullPointerException if Package has no implementation version and the ProtectionDomain returns a null CodeSource

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16956]
`java.security.ProtectionDomain.getCodeSource()` may return `null` but `SpringBootVersion` assumes that it will not do so. We should review other usages of `getCodeSource()` and check that they are null-safe while we're at it.

**Comment by pkostrzewa** [comment]
Can I work on this one?

**Comment by wilkinsona** [comment]
Thanks for the offer, @pkostrzewa, but as shown by the issue being assigned, we're already working on this one.

**Comment by wilkinsona** [comment]
This is a regression in 2.2.0.M3 that I did not spot when I merged #16182.
