### ISSUE TITLE
2.2 regression on nested @ConfigurationProperties classes

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#16969]
In Spring Boot 2.1 I use a configuration class marked with `@ConfigurationProperties` that has nested classes, also marked with the same annotation, and while trying with 2.2 the app was unable to start for two reasons:

1) it seems like inner classes are not scanned anymore for `@ConfigurationProperties`.
My app has a class defined in this way:

```java
@ConfigurationProperties
public class AConfig {
// Some properties

  @ConfigurationProperties(prefix = "myprefix")
  public class BConfig {
  // Other properties
  }
}
```

In one of my services I use the config this way:
```java
@Autowired
private AConfig.BConfig bConfig;
```

and while this works correctly in spring boot 2.1, it doesn't in 2.2.
I solved the problem by removing nested classes and creating new classes on their own, but since there are many, I preferred to have all of them in the same file.

2) The `@Component` annotation that I needed to have in my application has now become incompatible with `@ConfigurationProperties`, so I need to remove it. The problem is that if I remove it than I can't switch back to Spring Boot 2.1 because the bean is not found any more.
(maybe for this other thing I need to create a separate issue?)

**Comment by snicoll** [comment]
@Polve is the code you paster above what you're effectively doing in Spring Boot 2.1? (i.e. is it `public class BConfig` and not `public static class BConfig`). If `BConfig` isn't declared `static`, I'd argue it is very unusual and I didn't even expect this to work at all. 

Can you please clarify?

**Comment by Polve** [comment]
I confirm: it isn't static. If this is my error I will gladly fix it, thanks!

What about point 2) instead?
