### ISSUE TITLE
Failed to load resource when behind Kubernetes Ingress / Reverse Proxy path

### ISSUE THREAD

**Issue by dkirrane** [spring-projects/spring-boot#16976]
I'm using Spring Boot Admin `2.1.3` with Spring Boot `2.1.3.RELEASE`

I've deployed Spring Boot Admin into a Kubernetes cluster. It if frontended by an Ingress (I've tried both NginX & Istio Gateway).

The Ingress uses path based routing, so URI path with `/bootadmin` gets routed to the Spring Boot Admin Service -> Pod -> container. .

The problem is that it fails to load static resources like CSS because it is not looking for them at base path `/bootadmin`.
Not sure if there is a anyway to tell Spring Boot Admin UI the root context path for static content?
```
Failed to load resource: the server responded with a status of 404 (Not Found)
chunk-vendors.6399881d.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
sba-core.a6b7e5ec.js:1 Failed
...
```

**Comment by dkirrane** [comment]
wrong repo

**Comment by CamiloFD22** [comment]
same problem!
