### ISSUE TITLE
Wrong reference to org.apache.catalina.core.ApplicationContext in ServletWebServerFactory

### ISSUE THREAD

**Issue by mu-so** [spring-projects/spring-boot#16978]
hi,

just found this gem:

spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/server/ServletWebServerFactory.java

has an import to org.apache.catalina.core.ApplicationContext which is broken, if you don't have any Tomcat depdendencies in your project.

kr
Mustafa

**Comment by snicoll** [comment]
@mu-so good catch, this is used in a javadoc reference so it's not as harmful as you think. Let's fix that to use Spring's `ApplicationContext` reference.
