### ISSUE TITLE
Exclude groovy.lang.MetaClass type from configuration annotation processor

### ISSUE THREAD

**Issue by dmurat** [spring-projects/spring-boot#16981]
I have a simple Groovy Gradle project here: https://github.com/dmurat/config-annotation-processor-demo . It uses Groovy and Java classes annotated with `@ConfigurationProperties`. My issue is that for Groovy class annotation processor emits properties of `groovy.lang.MetaClass` type which is not really usefull.

I will like if `groovy.lang.MetaClass` can be included in a list of exclusions in `org.springframework.boot.configurationprocessor.TypeExcludeFilter`.

In a project mentioned above, it can be seen how metadata generation works with modifed `TypeExcludeFilter`. To get original behavior it is enough to switch the comments on `annotationProcessor` dependency in `build.gradle`.

Spring Boot version used is 2.1.4.RELEASE.

Tnx

**Comment by dmurat** [comment]
I noticed that this is scheduled for 2.2.x. Can you, please, consider it for 2.1.x too?

Tnx

**Comment by philwebb** [comment]
It feels safe enough to consider in 2.1.x
