### ISSUE TITLE
@RefreshScope and @Scheduled

### ISSUE THREAD

**Issue by anpu2018** [spring-projects/spring-boot#16999]
When I use the @RefreshScope annotation to dynamically refresh the internal private properties of the class, if the @Scheduled annotation is used in this class or the SchedulingConfigurer interface is used to define the scheduled task, the scheduled task will be invalidated while the property is refreshed. The current guess is because of RefreshScope. Will generate a proxy class, affecting the thread pool required for the running of scheduled tasks, how should this problem be solved?

**Comment by wilkinsona** [comment]
`@RefreshScope` is part of Spring Cloud. If you would like to pursue this, please chat with the Spring Cloud team on [Gitter](https://gitter.im/spring-cloud/spring-cloud) or open a [Spring Cloud Commons](https://github.com/spring-cloud/spring-cloud-commons) issue.
