### ISSUE TITLE
server.port should not be set to -1 if the test does not start an embedded web server

### ISSUE THREAD

**Issue by midstr** [spring-projects/spring-boot#16998]
when i use spring-boot for no-web application, in the spring-boot-test ,"server.port" was be override by `org.springframework.boot.test.context.SpringBootContextLoader.getInlinedProperties()`
`properties.add("server.port=-1")` . therefore on my unit test, i cannot start server.

application.properties:

```
server.port=12345
server.name=myserver`
```

MyServer.java:

```java
@Component
public class MyServer implements Closeable {

    @Value("${server.port}")
    private int serverPort;

    @Value("${server.name}")
    private String serverName;

    private ServerSocket serverSocket;

    @PostConstruct
    public void init() {
        System.out.println("server.port:" + serverPort);
        System.out.println("server.name:" + serverName);
        // start my server on port "server.port"
        ....
    }
   
}
```

SpringBootDemoApplication.java:

```java
@SpringBootApplication
public class SpringBootDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootDemoApplication.class, args);
	}

}
```

SpringBootDemoApplicationTest.java:

```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class SpringBootDemoApplicationTest {

    @Resource
    private MyServer myServer;

    @After
    public void tearDown() throws Exception {
        myServer.close();
    }

    @Test
    public void contextLoads() throws Exception {
        String message = MyClient.sendToServer();
        assertThat(message, startsWith("hello client!"));
    }


}
```

[spring-boot-demo.zip](https://github.com/spring-projects/spring-boot/files/3230669/spring-boot-demo.zip)

**Comment by philwebb** [comment]
We might be able to improve the detection logic, but in the meantime you can try using the `@SpringBootTest(webEnvironment=WebEnvironment.NONE)`

**Comment by midstr** [comment]
> We might be able to improve the detection logic, but in the meantime you can try using the `@SpringBootTest(webEnvironment=WebEnvironment.NONE)`

It didn't work, and if I add `@TestPropertySource(properties = "server.port=12345")` is the my solution for now.

**Comment by snicoll** [comment]
> when i use spring-boot for no-web application, in the spring-boot-test ,"server.port" was be override by 

@midstr what is your use of `server.port`? `server.*` is a reserved namespace for the embedded server and while we shouldn't set it to `-1` with a non web application, it would nice if you had dedicated properties for something that's not related to the standard embedded web server. Can you please clarify the use case?

**Comment by midstr** [comment]
> > when i use spring-boot for no-web application, in the spring-boot-test ,"server.port" was be override by
> 
> @midstr what is your use of `server.port`? `server.*` is a reserved namespace for the embedded server and while we shouldn't set it to `-1` with a non web application, it would nice if you had dedicated properties for something that's not related to the standard embedded web server. Can you please clarify the use case?

in our case ,we use spring-boot + netty for customize server (and customize protocol, not a web server).  Common properties like `server.id`、`server.port` `server.name` we use

**Comment by mindhaq** [comment]
I have this issue as well, and I am not specifying `server.port` manually.

I'm using the [workaround](https://github.com/spring-projects/spring-boot/issues/16998#issuecomment-496774893) for now.

**Comment by nkjackzhang** [comment]
> 
> 
> > > when i use spring-boot for no-web application, in the spring-boot-test ,"server.port" was be override by
> > 
> > 
> > @midstr what is your use of `server.port`? `server.*` is a reserved namespace for the embedded server and while we shouldn't set it to `-1` with a non web application, it would nice if you had dedicated properties for something that's not related to the standard embedded web server. Can you please clarify the use case?
> 
> in our case ,we use spring-boot + netty for customize server (and customize protocol, not a web server). Common properties like `server.id`、`server.port` `server.name` we use

There is another judgement using `hasCustomServerPort()`, if you config custom server port, this method will return true, and server port will not be overridden.

**Comment by snicoll** [comment]
Looking at the PR and the current code, I don't really understand why we set `server.port` to -1 at all when there isn't an embedded environment. Flagging for team attention to see if someone remembers.

**Comment by wilkinsona** [comment]
The only thing that I can think of is that a port < 0 is used to disable auto-start of the container and setting the property is a left-over from before the web environment stuff was reworked?
