### ISSUE TITLE
Strings starting with 0 will be parsed incorrectly. Although I defined the properties in java beans, there is no String.

### ISSUE THREAD

**Issue by geemu** [spring-projects/spring-boot#17009]
When using yaml as a configuration file, the string starting with 0 will be parsed incorrectly. Although I defined the property in the java bean as a String, although I can parse it correctly like '0454545' like this, 0545545 will be parsed as 153957. But I will not see this through the properties file. Is this a bug? Or I have to write String in the way of "" or "'

spring boot 2.1.5.RELEASE

yaml 0545545 will be parsed as 153957
yaml ‘0545545’ or "0545545" and Properties will be parsed correctly 0545545

**Comment by snicoll** [comment]
That's part of what YAML calls implicit types and that's not related to Spring Boot in any way.

**Comment by wilkinsona** [comment]
For anyone else encountering this behaviour, 0454545 becomes 153957 as the YAML specification states that a leading zero indicates that the number is octal and 454545 in octal is 153957 in decimal.
