### ISSUE TITLE
spring-boot-2.1.4.RELEASE pdf annotations missing

### ISSUE THREAD

**Issue by xiaobei-ihmhny** [spring-projects/spring-boot#17021]
All annotations in the code in the pdf document are missing，No annotations in all code snippets

**Comment by xiaobei-ihmhny** [comment]
https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/pdf/spring-boot-reference.pdf

**Comment by wilkinsona** [comment]
This has already been fixed. Please see #16548 and #16579 for details.
