### ISSUE TITLE
Replace deprecated MediaType.APPLICATION_JSON_UTF8 usage

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17023]
Since it's deprecated in Spring Framework we should also stop using it.

**Comment by bclozel** [comment]
Related to (but does not duplicate) #16979 - I see we have at least one of those in `DefaultErrorWebExceptionHandler`.

**Comment by pluttrell** [comment]
Will a fix for this be in 2.2.0?

**Comment by philwebb** [comment]
Closing in favor of PR #17596

**Comment by philwebb** [comment]
> Will a fix for this be in 2.2.0? 

@pluttrell Yes we merged the PR and it will be in M5
