### ISSUE TITLE
@ConditionalOnBean should provide an option to apply only with single instance match

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#1702]
Several auto-configuration options are breaking when more than one instance of a given type is defined (see #1701 for instance). This is because the `@Bean` method (or `@Configuration` class) is defined with `@ConditionalOnBean` and that bean can't be autowired because several candidates exist. The workaround is to flag one of the instances as `@Primary` but:

1. Sometimes there's no primary
2. The bean is defined using a namespace and does not offer an easy way to expose it as a primary bean

It would be nice if we could add a `singleInstance` parameter to the annotation that would match only if one instance is available in the context.

**Comment by snicoll** [comment]
@philwebb I have yet another concrete need for this one. Can we move on and do it for 1.3?

**Comment by snicoll** [comment]
I have a first draft in f62442d  but I am wondering if it wouldn't be  safer to move that to a dedicated annotation. Two reasons for that:

1. It's hard to find a good name for the attribute that states that only one autowire candidate should be found. This must be a sign
2. Adding that to `ConditionalOnBean` makes it a bit inconsistent (i.e. you can put that flag together with `name` and `annotation` and that makes much less sense all the  sudden)

How about `@ConditionalOnSingleCandidate` with `value` and `type` both taking a single value instead of an array? (+ some refactoring for `OnBeanCondition`).

**Comment by philwebb** [comment]
:+1:

**Comment by snicoll** [comment]
@philwebb I have reworked the initial proposal according to the proposal above. It works fine even though I am not super happy about the changes in `OnBeanCondition`. Could you please have a second look to it before I merge that to master? I can also merge that and we can revisit the internals later on. Thanks!
