### ISSUE TITLE
spring-cloud-netflix-turbine-stream can not work with spring-boot-starter-actuator

### ISSUE THREAD

**Issue by FlyRabit** [spring-projects/spring-boot#17028]
Question
spring boot version:2.1.3.RELEASE
spring cloud version: Greenwich.SR1
when I add dependency spring-boot-starter-actuator , the turbine stream can't work but just output "{data: ping}" when open the stream in browser. if the dependency removed from pom file,it works fine.

below is my pom file
```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-boot-starter-netflix-turbine-stream</artifactId>
            <exclusions>
            	<exclusion>
            		<groupId>org.springframework.cloud</groupId>
            		<artifactId>spring-boot-starter-netflix-eureka-client</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-boot-starter-stream-rabbit</artifactId>
        </dependency>
        <dependency>
        	<groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.7</version>
        </dependency>
    </dependencies>
```
my application.properties just config the spring.rabbitmq.*

**Comment by philwebb** [comment]
The `spring-boot-starter-netflix-turbine-stream` is part of `spring-cloud-netflix` so could you please raise your issue [here](https://github.com/spring-cloud/spring-cloud-netflix/issues). There's not a lot to go on from your report as it stands, so it would be very useful if you could also provide a sample application when you transfer the issue.
