### ISSUE TITLE
Build fails if port 8080 is in use

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17025]
Out build currently fails locally if port 8080 is already in use. At one point we used to ensure we were only using random ports, but this appears to no longer be the case. The first test that failed for me was `ServletWebServerFactoryAutoConfigurationTests`.

**Comment by gauravbhtngr** [comment]
In order to find random port one need to set server.port=0 to enable random port allocation.
Right now in AbstractConfigurableWebServerFactory default port value is 8080 so it always looks for 8080

**Comment by gauravbhtngr** [comment]
Code was removed as part of https://github.com/spring-projects/spring-boot/commit/8efa2fc569307cdd7bbf71f6a61e52216fc2aaa5 I believe

**Comment by philwebb** [comment]
@gauravbhtngr That commit was removing the problematic use of `SocketUtils` which we definitely don't want to reintroduce. Using port `0` allows the server itself to grab a port which is much less error prone. The problem with `SocketUtils` is it grabs a port which we then need to release so the server can use it. In that time, something else can grab it.

**Comment by gauravbhtngr** [comment]
Thanks @philwebb for the background.
Yes by looking at 8efa2fc it seemed a good fix as you mentioned.
**Using port 0 allows the server itself to grab a port which is much less error prone**

**Comment by linyonggui** [comment]
I think is a convention，but u can config it

**Comment by wilkinsona** [comment]
2.1 builds cleanly but I do see some clashes when building 2.2.
