### ISSUE TITLE
spring-boot-starter-parent:2.1.5 non-parseable pom

### ISSUE THREAD

**Issue by shajikurian** [spring-projects/spring-boot#17038]
Getting following error:
Failed to load Effective POM
Can't read Maven project
1 problem was encountered while building the effective model
[FATAL] Non-parseable POM C:\Users\Shaji\.m2\repository\org\springframework\boot\spring-boot-dependencies\2.1.5.RELEASE\spring-boot-dependencies-2.1.5.RELEASE.pom: in epilog non whitespace content is not allowed but got t (position: END_TAG seen ...</build>\n</project>\nt... @3244:2)  @ line 3244, column 2
 for project  at C:\Users\Shaji\.m2\repository\org\springframework\boot\spring-boot-dependencies\2.1.5.RELEASE\spring-boot-dependencies-2.1.5.RELEASE.pom
1 problem was encountered while building the effective model
[FATAL] Non-parseable POM C:\Users\Shaji\.m2\repository\org\springframework\boot\spring-boot-dependencies\2.1.5.RELEASE\spring-boot-dependencies-2.1.5.RELEASE.pom: in epilog non whitespace content is not allowed but got t (position: END_TAG seen ...</build>\n</project>\nt... @3244:2)  @ line 3244, column 2
 for project  at C:\Users\Shaji\.m2\repository\org\springframework\boot\spring-boot-dependencies\2.1.5.RELEASE\spring-boot-dependencies-2.1.5.RELEASE.pom

seeing the following @ line 3242 - 3246
```
</pluginManagement>
  </build>
</project>
**tifactId>**
        <version>${nekohtml.version}</version>
      </dependency>
```

**Comment by wilkinsona** [comment]
Thanks for the report. We would not have been able to build and release 2.1.5 if the pom was corrupted. Furthermore, no one else has reported the problem. Something must have corrupted your cache copy of the pom. Please delete it from Maven's local cache and try again.

**Comment by icemagno** [comment]
Facing same problem.
![Sem título](https://user-images.githubusercontent.com/4127512/66123328-16286500-e5b8-11e9-836b-7edb4a48fd43.png)

**Comment by snicoll** [comment]
Releases are not available on the snapshot repository (but on `repo.spring.io/release`). If you have more questions, please ask on StackOverflow or chat with the community on Gitter.
