### ISSUE TITLE
using actuator/health for kubernetes health check and  ignore apdex in newrelic

### ISSUE THREAD

**Issue by yezhoujie** [spring-projects/spring-boot#17031]
we are using spring-boot-actuate for health check in kubernetes with newrelic, and we want to ignore apdex for the URL ' actuator/health' called by kubernetes, the official document of newrelic says it needs to add an annotation on the method of the endpoint 'actuator/health‘. 

here is the URL of the document https://docs.newrelic.com/docs/agents/java-agent/instrumentation/ignore-transactions-using-api#apdex

does the spring-boot-actuate support for it? thanks.

**Comment by wilkinsona** [comment]
We don't have any dependencies on New Relic API and would not want to introduce any. Earlier in the documentation page to which you have linked above, it describes how to ignore transactions using a servlet filter which you could implement and add to your application. It also links to an option for using an XML instrumentation file to do the same.
