### ISSUE TITLE
@EnableConfigurationProperties、@ConfigurationProperties do not work properly

### ISSUE THREAD

**Issue by xiongshiyan** [spring-projects/spring-boot#17046]
I use SpringBoot1.5.7.RELEASE。and I want to do some auto configuration。
firstly.I define a properties component with annotation @ConfigurationProperties.

```java
@Component
@ConfigurationProperties("http.smart")
public class SmartHttpProperties{
...some bean properties
}
```

Then I config a implement of interface `SmartHttpClient` based on the different imported jar.

```java
@Configuration
//@EnableConfigurationProperties(SmartHttpProperties.class)
public class SmartHttpAutoConfigure {

    @ConditionalOnMissingBean(type = "top.jfunc.common.http.smart.SmartHttpClient")
    @ConditionalOnClass(OkHttp3SmartHttpClient.class)
    @ConditionalOnProperty(name = "spring.http.smart.type", havingValue = "top.jfunc.common.http.smart.OkHttp3SmartHttpClient", matchIfMissing = true)
    static class OkHttp3{
        /**
         * OkHttp3实现的话
         */
        @Bean(name = "OkHttp3SmartHttpClient")
        public SmartHttpClient okHttp3SmartHttpClient(@Autowired SmartHttpProperties smartHttpProperties){
            SmartHttpClient smartHttpClient = new OkHttp3SmartHttpClient();
            SmartHttpAutoConfigureUtil.configSmartHttpClient(smartHttpClient , smartHttpProperties);
            return smartHttpClient;
        }
    }

    @ConditionalOnMissingBean(type = "top.jfunc.common.http.smart.SmartHttpClient")
    @ConditionalOnClass(NativeSmartHttpClient.class)
    @ConditionalOnProperty(name = "spring.http.smart.type", havingValue = "top.jfunc.common.http.smart.NativeSmartHttpClient", matchIfMissing = true)
    static class Jdk{
        /**
         * JDK实现的话
         */
        @Bean(name = "JdkSmartHttpClient")
        public SmartHttpClient jdkSmartHttpClient(@Autowired SmartHttpProperties smartHttpProperties){
            SmartHttpClient smartHttpClient = new NativeSmartHttpClient();
            SmartHttpAutoConfigureUtil.configSmartHttpClient(smartHttpClient , smartHttpProperties);
            return smartHttpClient;
        }
    }

    @ConditionalOnMissingBean(type = "top.jfunc.common.http.smart.SmartHttpClient")
    @ConditionalOnClass(ApacheSmartHttpClient.class)
    @ConditionalOnProperty(name = "spring.http.smart.type", havingValue = "top.jfunc.common.http.smart.ApacheSmartHttpClient", matchIfMissing = true)
    static class Apache{
        /**
         * Apache实现的话
         */
        @Bean(name = "ApacheSmartHttpClient")
        public SmartHttpClient apacheSmartHttpClient(@Autowired SmartHttpProperties smartHttpProperties){
            SmartHttpClient smartHttpClient = new ApacheSmartHttpClient();
            SmartHttpAutoConfigureUtil.configSmartHttpClient(smartHttpClient , smartHttpProperties);
            return smartHttpClient;
        }

    }

    @ConditionalOnMissingBean(type = "top.jfunc.common.http.smart.SmartHttpClient")
    @ConditionalOnClass(JoddSmartHttpClient.class)
    @ConditionalOnProperty(name = "spring.http.smart.type", havingValue = "top.jfunc.common.http.smart.JoddSmartHttpClient", matchIfMissing = true)
    static class Jodd{
        /**
         * Jodd-Http实现的话
         */
        @Bean(name = "JoddSmartHttpClient")
        public SmartHttpClient joddSmartHttpClient(@Autowired SmartHttpProperties smartHttpProperties){
            SmartHttpClient smartHttpClient = new JoddSmartHttpClient();
            SmartHttpAutoConfigureUtil.configSmartHttpClient(smartHttpClient , smartHttpProperties);
            return smartHttpClient;
        }
    }

```

then,I use A annotation to import this autoconfigure Class and it works all right.

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Documented
@Import({SmartHttpProperties.class ,
        SmartHttpAutoConfigure.OkHttp3.class , SmartHttpAutoConfigure.Jdk.class,
        SmartHttpAutoConfigure.Apache.class , SmartHttpAutoConfigure.Jodd.class,
        SmartHttpAutoConfigure.class})
public @interface EnableSmartHttp {
}
```

but, when I do some more config in `SmartHttpAutoConfigure` which depend on `SmartHttpClient`, it does not work properly, as shown by the fact that `SmartHttpProperties` attributes are not automated.

```java
@Bean
    public HttpServiceCreator httpServiceCreator(@Autowired SmartHttpClient smartHttpClient){
        return new HttpServiceCreator().setSmartHttpClient(smartHttpClient);
    }

    @Bean
    public HttpServiceScanConfigure httpServiceScanConfigure(@Autowired HttpServiceCreator httpServiceCreator ,
                                                             @Value("${spring.http.smart.scanPackages:top.jfunc.network}") String scanPackages){
        HttpServiceScanConfigure httpServiceScanConfigure = new HttpServiceScanConfigure(httpServiceCreator);
        httpServiceScanConfigure.setAnnotationClassScan(HttpService.class);
        httpServiceScanConfigure.setScanPackages(scanPackages);
        return httpServiceScanConfigure;
    }

```

it's the same fact that use `@EnableConfigurationProperties` or `@Import`.

THANKS A LOT

**Comment by philwebb** [comment]
This looks like a continuation of the discussion in #17027. The request in that issue still stands:

> Can you please take the snippets of code that you have shared and turn them into a complete and minimal example that reproduces the problem?

In order to help understand the issue, we need a small sample that reproduces issue. This need to be something that we can download and run.

**Comment by xiongshiyan** [comment]
thanks a lot for feedback. I provide two projects to reproduces issue.
[git clone this and publish to maven local](https://gitee.com/xxssyyyyssxx/test-spring-boot-properties)
[git clone this and run main](https://gitee.com/xxssyyyyssxx/http-server-test/).


debug main method， the smartHttpProperties's properties is not injected correctly。
 If I replace the automatic configuration with the following configuration, an exception occurs.
 It's like this code doesn't work. @ConditionalOnMissingBean({SmartHttpClient.class}) on SmartHttpAutoConfigure

**No qualifying bean** of type 'top.jfunc.common.http.smart.SmartHttpClient' available: expected single matching bean but found 2: ApacheSmartHttpClient,smartHttpClient

**Comment by wilkinsona** [comment]
Thanks for the sample. You are indirectly wiring your `SmartHttpProperties` into `HttpServiceScanConfigure`, a `BeanDefinitionRegistryPostProcessor`. `BeanDefinitionRegistryPostProcessor`s are called very early in the application context's lifecycle and should deal only with bean definitions rather than actual beans. By depending on the `SmartHttpProperties` bean (via your `HttpServiceCreator` and `SmartHttpClient` beans), you are causing the `SmartHttpProperties` bean to be created too early. The bean post-processor that binds configuration properties has not been registered at this time so its configuration properties are not bound to it.

You need to rework your configuration so that your `BeanDefinitionRegistryPostProcessor` does not depend upon any other beans. If you want to read configuration properties at this time using Spring Boot's relaxed binding, you should use a `RelaxedDataBinder` to do so.

**Comment by xiongshiyan** [comment]
thanks a lot，I decided to replace automatic configuration with manual configuration.
