### ISSUE TITLE
Rectify javadoc for disabling management server port

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#17054]
According to the JavaDoc, setting the `management.server.port` property to `0` should disable the management server.
https://github.com/spring-projects/spring-boot/blob/b5d19b798eca7a6400a97e80d42601e027789aa6/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.java#L67-L72

However, according to the [Reference Guide](https://docs.spring.io/spring-boot/docs/2.1.5.RELEASE/reference/htmlsingle/#production-ready-disabling-http-endpoints), setting the value to `-1` is what is used to disable the http management server.

Based on empirical observation, the reference guide is correct. Setting the value of 
 `management.server.port` to `0` actually causes it to use a new random port for the management server, while setting the value to `-1` will disable the management server.

**Comment by mbhave** [comment]
Closing in favor of #17068.
