### ISSUE TITLE
Documentation: 92.1 Create a Deployable War File

### ISSUE THREAD

**Issue by molzb** [spring-projects/spring-boot#17053]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file

To create a deployable WAR file, you need to add a _start-class_ tag in your pom.xml.
This was not mentioned in this chapter.

E.g. 
```
<project>
    <properties>
        <start-class>com.demo.Application</start-class>
```
Tested on Tomcat 8.5 with two different projects.

**Comment by philwebb** [comment]
You shouldn't need to do that as long as you have a valid main method. Can you please share a sample that shows the actual error that you get when you don't declare that property?

**Comment by molzb** [comment]
Just as I wanted to reproduce it (uploading the WAR file without `start-class`-tag), it works as designed ;-) Sorry that I wasted your time.

**Comment by philwebb** [comment]
No worries. Happy to hear it works.
