### ISSUE TITLE
Add some javax.* dependencies to BOM file

### ISSUE THREAD

**Issue by altro3** [spring-projects/spring-boot#17059]
Hi! For working in JDK11 will be cool add versions for some dependencies:
```groovy
"javax.jws:javax.jws-api:1.1"
"jakarta.jws:jakarta.jws-api:1.1.1"
"javax.activation:activation:1.1.1"
```

**Comment by wilkinsona** [comment]
> `javax.jws:javax.jws-api:1.1`

We haven't seen any need for this dependency with Spring Boot. It isn't used by Spring Web Services, for example, which uses `javax.xml.ws:javax.xml.ws-api`. What do you need it for?

> `jakarta.jws:jakarta.jws-api:1.1.1`

There doesn't appear to be a `jakarta.jws` group in Maven Central. Can you please clarify?

> `javax.activation:activation:1.1.1`

You should use `javax.activation:javax.activation-api` which is already managed. Boot 2.2 adds management for `jakarta.activation:jakarta.activation-api`.

**Comment by altro3** [comment]
1. In this case, I proceed from my needs. After switching to Java 11, I had to figure out how to work with JavaEE web services (many banks use them); to minimize coding, I chose apache CXF as the code generator. The generated client class uses annotations from javax.jws-api (jakarta.jws-api):
```java
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
```
And also, since this is part of the java EE cut from the JDK and you have added almost all versions of dependencies, are required to work in JDK 11, it’s logical to add this dependency for completeness

2. About jakarta.jws: https://mvnrepository.com/artifact/jakarta.jws/jakarta.jws-api/1.1.1

3. Yes, of course, in most cases, activation-api is enough. But the problem is the separation of ```javax.activation-api``` and ```javax.activation```: the classes javax.activation.MailcapCommandMap and javax.activation.MimetypesFileTypeMap from activation-api use the class from activation, you can see the sources here: https://github.com/javaee/activation/blob/master/activation/src/main/java/javax/activation/MailcapCommandMap.java. Same problem in ```jakarta.activation:activation-api```. Another words, if you using ```activation-api```, most likely you need add ```activation``` dependency too.

**Comment by wilkinsona** [comment]
1. To limit the scope of our dependency management to something that is maintainable, we only manage dependencies that Spring Boot interacts with either directly or indirectly. There's no such interaction with JWS so providing dependency management for it is out of scope.

2. Sorry, I'm not sure how I missed that earlier. However, the same applies here as applies to `javax.jws:javax.jws-api` so it's out of scope too.

3. The dependency management that we provide for Javax Activation is version 1.2 where the implementation jar has the coordinates `com.sun.activation:javax.activation` or `com.sun.activation:jakarta.activation`. We should have dependency management for this as it's part of the same project as the API dependencies that we already manage. I've opened https://github.com/spring-projects/spring-boot/issues/17062 to correct that.

**Comment by altro3** [comment]
1. and 2. ok, understood

3. yeah, will be great. Thanks!
