### ISSUE TITLE
It is recommended that when the parsing value is null, it can be customized by BindHandler

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#17050]
org.springframework.boot.context.properties.bind.Binder
![image](https://user-images.githubusercontent.com/13413715/58802529-0156b780-8640-11e9-9ce9-5b1f91f2ae97.png)

It is recommended that when the parsing value is null, it can be customized by BindHandler,because when the return value is null, I need to give a default value through BindHandler,the recommended code is modified as follows: 
![image](https://user-images.githubusercontent.com/13413715/58803773-d326a700-8642-11e9-96fc-46081ebd3813.png)

The second solution is that the finish method of bindhander can add method return value,the code is as follows:
![image](https://user-images.githubusercontent.com/13413715/58804059-8394ab00-8643-11e9-9f0e-dffdac1161ed.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestions. Unfortunately, I don't think we can proceed with them as they are both breaking changes:

1. The `result` that is passed to `onSuccess` is documented as never being `null`.
2. Changing the runtime type of `onFinish` from `void` to `Object` would break any existing implementations of that method.

Rather than describing possible solutions, can you please take a step back and describe the problem that you are facing?

**Comment by brucelwl** [comment]
I need to dynamically bind attributes to beans, so I use binder Api, but some attributes are not standard field mapping, so I want to use a custom handler to process @value and assign special attributes.
Look at my demo please. I hope that the 'slaveJdbcUrl' attribute in MyBatis Properties can get the configuration value of "mybatis.config.slave.slaveJdbcUrl", and preferably support Spring's EL expression
https://github.com/brucelwl/demo.git

**Comment by brucelwl** [comment]
Do you understand my question? look forward to your reply  @wilkinsona  @spring-issuemaster

**Comment by philwebb** [comment]
I would not recommend trying to reuse the `@Value` annotation in the way that you're doing. It's very likely to cause you problems (for example, it doesn't support relaxed binding).

It seems like you're trying to support a form of fallback properties. The user can set `mybatis.config.slave-jdbc-url`, or leave it blank to have it set to `mybatis.config.slave.slave-jdbc-url`. Rather than trying to do that in the binder, I'd create some explicit logic for that:

```java
public static String getSlaveJdbcUrl(MyBatisProperties properties) {
    String result = properties.getSlaveJdbcUrl();
    if (result == null) {
        result = properties.getSlave().getSlaveJdbcUrl();
    }
    return result;
}
```

**Comment by philwebb** [comment]
We're not keen to add additional complexity to the Binder to support fallback functionality. See #7986 for background.

**Comment by brucelwl** [comment]
> I would not recommend trying to reuse the `@Value` annotation in the way that you're doing. It's very likely to cause you problems (for example, it doesn't support relaxed binding).
> 
> It seems like you're trying to support a form of fallback properties. The user can set `mybatis.config.slave-jdbc-url`, or leave it blank to have it set to `mybatis.config.slave.slave-jdbc-url`. Rather than trying to do that in the binder, I'd create some explicit logic for that:
> 
> ```java
> public static String getSlaveJdbcUrl(MyBatisProperties properties) {
>     String result = properties.getSlaveJdbcUrl();
>     if (result == null) {
>         result = properties.getSlave().getSlaveJdbcUrl();
>     }
>     return result;
> }
> ```

@philwebb Sorry, I don't think this is a good solution to my problem, because I may have to write a lot of such logic code, I want to call Binder API binding dynamically, so @ConfigurationProperties can't solve my problem either.

**Comment by philwebb** [comment]
> Do you think it's feasible to change the name attribute through the handler`s start method?

You mean the `onStart` method? I don't see how we could do that.

Perhaps you can subclass the `Binder` and override the following protected method to do what you need:

```java
protected final <T> T bind(ConfigurationPropertyName name, Bindable<T> target,
		BindHandler handler, Context context, boolean allowRecursiveBinding) {
```

**Comment by brucelwl** [comment]
@philwebb Thank you for your reply, but the final method cannot be rewritten. I've implemented my requirements through two solutions. 
          The first one is to rewrite attribute values using reflection through Binder Hadnler's onStart method, but it can't support nested attributes. 
          The second one is more violent, replicates a lot of spring source code, but supports embedded attributes. I hope you can consider my second one and modify the interface of binderHandler. Method, see my custom 'MyBinderHandler', add a return value to the onFinish method, and add the onNoDescendSkip method.
        I recommend expanding the access rights of the classes under package'org. spring framework. boot. context. properties. bind'so that there is no need to duplicate too much redundant code
      Please take a look at my demo:  https://github.com/brucelwl/demo.git

**Comment by philwebb** [comment]
> I recommend expanding the access rights of the classes under package'org. spring framework. boot. context. properties. bind'so that there is no need to duplicate too much redundant code

I'm sorry, but we don't want to expand the surface area of the public API. Your specific use-case is quite unusual and as such I think that maintaining your own copy of the code is the best approach.

**Comment by brucelwl** [comment]
@philwebb Thank you for your reply
