### ISSUE TITLE
Dependency management for JavaBeans Activation Framework is incomplete

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17062]
We manage the API dependency but not the implementation. Both should be managed as, while they have different group IDs, they are developed as part of the same project and are tagged and released together.

**Comment by ielatif** [comment]
Interesting discussions about this topic from eclipse-ee4j projects [jakarta.activation-api should not be used at runtime](https://github.com/eclipse-ee4j/jaxb-ri/issues/1284)  and [Substitute jakarta.activation-api with jakarta.activation](https://github.com/eclipse-ee4j/jaxb-ri/pull/1296)
