### ISSUE TITLE
DataSourceInitializedEvent picks wrong datasource

### ISSUE THREAD

**Issue by m-kay** [spring-projects/spring-boot#17061]
With spring boot 2.1.x the `DataSourceInitializedEvent` picks the wrong datasource again because the property to get the datasource from the `EntityManagerFactory` changed to `hibernate.connection.datasource` compared to `javax.persistence.nonJtaDataSource` used in the fix for #8296.

As a workaround one can fix this by passing the legacy property `javax.persistence.nonJtaDataSource` to the `EntityManagerFactoryBuilder` with the correct datasource. I have created a minimal example with everything needed to initialize two datasources at https://github.com/m-kay/spring-boot-init-two-datasources and you can see the fix in `FirstDbConfig`line 84 and `SecondDbConfig` line 83. I had to create my own `DataSourceInitializer` which executes init scripts after the event is fired for my second datasource, since the defaults only work with a single datasource.

**Comment by philwebb** [comment]
Thanks for the sample application @m-kay. I think that this might be a bug in recent Hibernate versions. I've raise [HHH-13432](https://hibernate.atlassian.net/browse/HHH-13432) to see if the Hibernate team agree. I'll close this issue for now, but if it turns out to be a bug on our side we'll reopen it.

**Comment by philwebb** [comment]
Turns out we're relying on something that isn't defined in the spec

> I’m not aware that the spec says this should be supported (accessing “config settings” defined outside its properties block).  It is not tested in the TCK.

I think the Hibernate team are going to change their code, but we should also look if there's something we can do locally.

**Comment by philwebb** [comment]
We're unfortunately very light on tests for `DataSourceInitializedPublisher` but the I tried the sample application with the fix and it appears to work.
