### ISSUE TITLE
OAuth2ResourceServerJwtConfiguration uses deprecated JwtDecoder

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#17071]
`OAuth2ResourceServerJwtConfiguration` currently uses `NimbusJwtDecoderJwkSupport`, which was recently deprecated. The direct replacement is `NimbusJwtDecoder`.

The only update required is as follows:

Change:

`new NimbusJwtDecoderJwkSupport(this.properties.getJwkSetUri(), this.properties.getJwsAlgorithm())`

To:

`NimbusJwtDecoder.withJwkSetUri(jwkSetUri).jwsAlgorithm(jwsAlgorithm).build()`

**Comment by mbhave** [comment]
Thanks @jgrandja. Looks like it was changed on master but missed in 2.1.x.

**Comment by jgrandja** [comment]
@mbhave Sorry, I should have checked in master before I logged this issue. I noticed this in 2.2.0.M1 with my local setup. Obviously, it was updated after M1.

> ...but missed in 2.1.x

Note that `NimbusJwtDecoder` was added for 5.2.0 release so no need to apply this change to 2.1.x.

**Comment by mbhave** [comment]
Cool, there's nothing to be done here then. I'll close the issue.
