### ISSUE TITLE
Remove Checkstyle suppression for SpringJUnit5 from JerseyAutoConfigurationServletContainerTests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17086]

**Comment by wilkinsona** [comment]
`JerseyAutoConfigurationServletContainerTests` only has the implicit public default constructor at the moment. If I add a package-private default constructor the tests pass. What did you have in mind here, @philwebb?

**Comment by philwebb** [comment]
@wilkinsona  Nothing in mind, it was just a test I didn't have time to investigate when adding the checkstyle rule. If that's all there is then we can just migrate it I guess.

**Comment by wilkinsona** [comment]
I've just realised that it's the `public` `Application` inner-class that's the problem.
