### ISSUE TITLE
Ensure nohttp checkstyle is only applied at top level

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17081]
The `sourceDirectories` configuration of our Checkstyle setup mean that modules will check the entire directory tree beneath their location, including any sub-modules. In the 2.x builds this means that checking in `spring-boot-build` covers the entire source tree. We need to find a way to check more than just `.java` files, but avoid checking nested modules.

**Comment by philwebb** [comment]
I think we can flip this on its head and have the main build check all subfolders and just not inherited it in the children. I think I have it working locally but we'll need some CI updates.
