### ISSUE TITLE
A tutorial that shows how to import project into IDEA&ECLIPSE  . pls

### ISSUE THREAD

**Issue by linyonggui** [spring-projects/spring-boot#17102]
A tutorial that shows how to import project into IDEA&ECLIPSE

**Comment by wilkinsona** [comment]
The [guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#working-with-the-code) describe how to import Spring Boot's own code into IntelliJ IDEA and Eclipse.

Importing an application that uses Spring Boot into Eclipse is no different to importing any other Java application built with Maven or Gradle so we consider it to be out of scope for Spring Boot itself to document. If you use the IDE's start.spring.io integration, the IDE will automatically import the project when it is generated. If you want to import and existing project, you can follow your IDE's standard process for importing a project. For example, here's IntelliJ IDEA's documentation on [importing a Maven project](https://www.jetbrains.com/help/idea/maven-support.html#maven_import_project_start).

**Comment by linyonggui** [comment]
thanks
