### ISSUE TITLE
Automatically auto-configure Kafka ErrorHandler beans

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17110]
Reading https://www.confluent.io/blog/spring-for-apache-kafka-deep-dive-part-1-error-handling-message-conversion-transaction-support, I wonder if we can auto-configure `ErrorHandler` beans to save needing to redefine `ConcurrentKafkaListenerContainerFactory`.

@garyrussell Is this a common thing to do? Would it make sense to make it easier?

**Comment by garyrussell** [comment]
Hi Phil,

It's already done: https://github.com/spring-projects/spring-boot/commit/59c6dc5c7ad595082ccf37ddd8f891df86543b21 and https://github.com/spring-projects/spring-boot/commit/bb7940f8e40e8e1dc87d6dcb00b1a66cc95aab42.

(I think I originally wrote that blog before Boot 2.1 was released, but failed to update it before it was published 😦 ).

**Comment by philwebb** [comment]
Ha, nice.
