### ISSUE TITLE
support any number of the cluster node config with rabbitmq

### ISSUE THREAD

**Issue by lmx1989219** [spring-projects/spring-boot#17130]
due to my apps is already running online and the rabbitmq server is running in single node.
now i want rabbitmq server is running in cluster,but i wan't restart my apps.

## currently right conf
````
spring.rabbitmq.addresses=192.168.103.34:5672,192.168.73.129:5672,192.168.73.130:5672
````

## i needed conf
````
spring.rabbitmq.host=192.168.103.34
spring.rabbitmq.port=5672
````

currently,the client could't auto detect other nodes in cluster and when network failure it can't auto swithing to health node.
if can did,i wannot to rewrite my conf and restart my apps.

thanks.

**Comment by wilkinsona** [comment]
Sorry, I don't think I've understood what you'd like to be able to do. You can already configure multiple nodes using the `spring.rabbitmq.addresses` property as you have shown above.

Are you hoping to reconfigure your Rabbit client without restarting your app? That isn't something that Spring Boot supports out of the box, but `org.springframework.amqp.rabbit.connection.CachingConnectionFactory` has a setter method for the addresses which you may be able to use. If you'd like to explore that possibility, I'd recommend asking the Spring AMQP team on [Gitter](https://gitter.im/spring-projects/spring-amqp).

If I have misunderstood, can you please clarify what it is that you would like to be able to do.

**Comment by lmx1989219** [comment]
@wilkinsona 
yes,i want it `org.springframework.amqp.rabbit.connection.CachingConnectionFactory` can auto detect and refresh available address.

**Comment by wilkinsona** [comment]
Assuming that RabbitMQ makes that information available to clients, it would require a change to Spring AMQP for the connection factory to automatically update itself. Please open a [Spring AMQP issue](https://github.com/spring-projects/spring-amqp) if you would like to pursue this.

**Comment by lmx1989219** [comment]
@wilkinsona 
thanks for your help
