### ISSUE TITLE
Missing configuration metadata for RestDocsProperties

### ISSUE THREAD

**Issue by iNikem** [spring-projects/spring-boot#17133]
`spring-boot-test-autoconfigure` jar provides, among other things `RestDocsProperties` class to configure Spring Rest Docs used during tests. Unfortunately this jar lacks corresponding `spring-configuration-metadata.json` file which would describe those properties and allow for proper IDE integration.

**Comment by wilkinsona** [comment]
There are many `spring.test.*` properties that are not documented. They're really a detail of how the various `@AutoConfigure…` annotations have been implemented.  In the specific case of REST Docs, the intent is that you use the various attributes on `@AutoConfigureRestDocs`.

Is there any particular reason why you're using the properties directly?

**Comment by iNikem** [comment]
No. I have missed `@AutoConfigureRestDocs` attributes when I went reporting this issue. So for the particular case of `RestDocsProperties` configuration metadata is indeed not needed.

The question remains: why not to document all other test properties?

**Comment by snicoll** [comment]
Properties that have a default will ignore those set in `application.propertes` as we want the test annotation to drive things. There are a handful properties that we consider relevant for use in `application.properties` and those are documented.

**Comment by wilkinsona** [comment]
Thanks, @snicoll.
