### ISSUE TITLE
Align with Framework changes to RSocket routing and new message/x.rsocket.routing.v0 requests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17135]

**Comment by wilkinsona** [comment]
@bclozel @rstoyanchev Can you please confirm that [this](https://github.com/spring-projects/spring-boot/commit/704b5fb2ee0334fa505b24fa6ec541104cf66966) was the right change to make? Given that all mime types or just `text/plain` are the two options for `CharSequenceEncoder` it seems reasonable. It's also the encoder that [Framework's tests use](https://github.com/spring-projects/spring-framework/blob/eef9bc899f859445bbcf93980c7df2df02ed97b3/spring-messaging/src/test/java/org/springframework/messaging/rsocket/DefaultRSocketRequesterTests.java#L75).

**Comment by rstoyanchev** [comment]
That's a reasonable change for now and in general, although you should be able to switch back to the stricter `"text/plain"` when https://github.com/spring-projects/spring-framework/issues/23137 is resolved.

**Comment by philwebb** [comment]
I've raised https://github.com/spring-projects/spring-boot/issues/17146 to make sure we remember to switch back.
