### ISSUE TITLE
Split package between spring-boot-autoconfigure and spring-security-oauth2-autoconfigure

### ISSUE THREAD

**Issue by PiotrMachner** [spring-projects/spring-boot#17138]
My Spring Boot application has among others the following dependency:

```xml
<dependency>
   <groupId>org.springframework.security.oauth.boot</groupId>
   <artifactId>spring-security-oauth2-autoconfigure</artifactId>
   <version>2.1.5.RELEASE</version>
</dependency>
```

which in turn depends on:

```xml
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-autoconfigure</artifactId>
   <scope>compile</scope>
   <version>2.1.5.RELEASE</version>
</dependency>
```

My code depends actually on both of the above, because I'm using `org.springframework.boot.autoconfigure.condition.ConditionalOnProperty` and `org.springframework.boot.autoconfigure.security.oauth2.client.EnableOAuth2Sso`.

I'm trying to migrate my application by Java 11, including a migration to JPMS. I've created a `module-info.java` file with the following content:

```java
module com.machner.myapp {
// ...
    requires spring.boot.autoconfigure;
    requires spring.security.oauth2.autoconfigure;
// ....
}
```

Due to the mentioned usage of `ConditionalOnProperty` and `EnableOAuth2Sso` I need both of the above requires.

The compilation fails due to a split package:

```
[ERROR] the unnamed module reads package org.springframework.boot.autoconfigure.security.oauth2.client from both spring.boot.autoconfigure and spring.security.oauth2.autoconfigure
```
Would you be able to suggest a workaround (and eventually fix the split package issue)?
Thanks in advance for any help, much appreciated :)

**Comment by mbhave** [comment]
@PiotrMachner `spring-security-oauth2-autoconfigure` exists as a bridge between the old Spring Security OAuth support and Spring Boot 2.x. OAuth2 client support is available in Spring Boot 2.0 (Spring Security 5.0) and above.

Is there a reason you need to use `@EnableOAuth2Sso` instead of using the [OAuth2 support](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-client) available with Spring Boot 2? 

Also, I don't think there's anything we can do in Spring Boot regarding the package split as `spring-security-oauth2-autoconfigure` lives outside of Spring Boot.

**Comment by philwebb** [comment]
:) I was just typing the exact same thing. The [spring-security-oauth2-boot](https://github.com/spring-projects/spring-security-oauth2-boot) project is in maintenance mode. In hindsight, It should have used a different package name when it was published. If you can't migrate to Spring Security then you can raise an issue [here](https://github.com/spring-projects/spring-security-oauth2-boot/issues/new), but I think it's unlikely that the package structure can be changed now.

**Comment by PiotrMachner** [comment]
@mbhave @philwebb Thank you very much for the very fast and informative response. This is exactly the advice I needed - I'll try to migrate to the newer OAuth2 support.

However, I would also suggest to fix this Spring Boot tutorial:
https://spring.io/guides/tutorials/spring-boot-oauth2/
I imagine that whoever wrote the code using `@EnableOAuth2Sso` in our app probably used this tutorial.

Anyway, thanks a lot!

**Comment by philwebb** [comment]
@PiotrMachner Good point, looks like https://github.com/spring-guides/tut-spring-boot-oauth2/issues/91 has already been raised for that.
