### ISSUE TITLE
Which day we plan to release 2.2.0.RELEASE version

### ISSUE THREAD

**Issue by guanchao-yang** [spring-projects/spring-boot#17134]
The latest Spring Boot version is `2.2.0.M4` from [this document](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes). Which day do we plan to release 2.2.0.RELEASE version not `M`  version ? 

Thanks very much !

**Comment by wilkinsona** [comment]
You can find this information on the [milestone page](https://github.com/spring-projects/spring-boot/milestones). 2.2.0 is currently scheduled for 25 September.

In the future, please do not use GitHub issues for questions such as this. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. [Gitter](https://gitter.im/spring-projects/spring-boot) is a better place to ask.

**Comment by guanchao-yang** [comment]
@wilkinsona  ok ,Get it .Thank you.
