### ISSUE TITLE
Switch RSocket routing back to text/plain

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17146]
See https://github.com/spring-projects/spring-boot/issues/17135#issuecomment-501886439

Currently blocked on https://github.com/spring-projects/spring-framework/issues/23137

**Comment by linux-china** [comment]
like this  https://github.com/spring-projects/spring-framework/issues/23157 ?    RSocket Metadata Mimetype "text/plain" and "application/json" support

**Comment by wilkinsona** [comment]
@bclozel took care of this in https://github.com/spring-projects/spring-boot/commit/1996952e680614c05e2e29739250f7b37ca3c837#diff-cbec0cac87b23b90bd32d2f8caffcf0c.
