### ISSUE TITLE
BootstrapConfigurationTests from Spring Cloud fails with configuration property issues

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17141]
See #17011 for background and [this failing test](https://jenkins.spring.io/job/spring-cloud-commons-master-ci/8853/testReport/org.springframework.cloud.bootstrap.config/BootstrapConfigurationTests/includeProfileFromBootstrapProperties/)

**Comment by philwebb** [comment]
@ryanjbaxter @spencergibb We're a bit stuck with this one on our end, there doesn't seem to be an obvious way to support both this and #15445. Is it possible to investigate renaming the property source on your side to something other than `defaultProperties`?

**Comment by spencergibb** [comment]
I think so. I don't know of any reason for that particular name. Maybe @dsyer knows?

**Comment by ryanjbaxter** [comment]
I confirmed that changing the property source name to something other than `defaultProperties` does fix the broken test.  Unless @dsyer sees a reason to not do this (I think we just use the name internally in our code) I think we can make that change.

**Comment by philwebb** [comment]
I'll close this one for now, but if you don't get anywhere let us know.
