### ISSUE TITLE
Remove tranisitive web starter dependency from HATEOAS starter

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#17140]
The starter POM for Spring HATEOAS currently pulls in the web starter, which means that the project resulting will be a servlet based one. As of Spring HATEOAS 1.0 M2, we support Spring WebFlux as well which in turn means that they end up selecting the WebFlux starter *and* the HATEOAS one which messes up their WebFlux projects.

I suggest to remove the web starter from the HATEOAS one and rely on Initializr to make users aware of the fact that they have to select either the WebMVC or WebFlux one if they want to create a bootable application,

**Comment by wilkinsona** [comment]
We'll tackle this as part of #16020.
