### ISSUE TITLE
Allow disable select(dbIndex) when getAsyncDedicatedConnection in LettuceConnection

### ISSUE THREAD

**Issue by PaniniGelato** [spring-projects/spring-boot#17145]
My company is using a REDIS-PROXY infront of the redis cluster,  the proxy DOSE NOT support SELECT command

The redis-connction keep crash at startup

I found the `select(dbIndex)` in LettuceConnection:
```
protected RedisClusterAsyncCommands<byte[], byte[]> getAsyncDedicatedConnection() {

		if (asyncDedicatedConn == null) {

			asyncDedicatedConn = doGetAsyncDedicatedConnection();

			if (asyncDedicatedConn instanceof StatefulRedisConnection) {
				((StatefulRedisConnection<byte[], byte[]>) asyncDedicatedConn).sync().select(dbIndex);
			}
		}

		if (asyncDedicatedConn instanceof StatefulRedisConnection) {
			return ((StatefulRedisConnection<byte[], byte[]>) asyncDedicatedConn).async();
		}
		if (asyncDedicatedConn instanceof StatefulRedisClusterConnection) {
			return ((StatefulRedisClusterConnection<byte[], byte[]>) asyncDedicatedConn).async();
		}

		throw new IllegalStateException(
				String.format("%s is not a supported connection type.", asyncDedicatedConn.getClass().getName()));
	}
```

I would like to call select() when needed or base on config

**Comment by philwebb** [comment]
The code snippet that you've referenced is [part of spring-data-redis](https://github.com/spring-projects/spring-data-redis/blob/10329559a68f2a557c386859f0ab7a90d8f24858/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L932-L952). If you think you've found a bug in that area, please raise an issue [here](https://jira.spring.io/secure/RapidBoard.jspa?projectKey=DATAREDIS&useStoredSettings=true&rapidView=69).

**Comment by PaniniGelato** [comment]
Thanks, i will do that
