### ISSUE TITLE
Rename samples to smoke tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17197]
The samples confuse people, renaming to make it clear they are simply smoke tests might help

**Comment by ielatif** [comment]
It confused me also before dicovering [‘How-to’ guides](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html). I think README file should state that those applications are smoke tests and for samples consult [‘How-to’ guides](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html)

**Comment by rugden** [comment]
smoke tests is more confusing for me. what does smoke tests mean in this context?

**Comment by philwebb** [comment]
@rugden You can find some more information about the term [here](http://softwaretestingfundamentals.com/smoke-testing/)

**Comment by rugden** [comment]
That's what i thought it meant. I generally looked to sample projects in the last to see how to use certain spring boot features. 

Thanks for clarifying!
