### ISSUE TITLE
Binder Nesting of the same entity class is not supported

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#17207]
org.springframework.boot.context.properties.bind.Binder 
Nesting of the same entity class is not supported !!! please see my demo 
https://github.com/brucelwl/demo.git

![image](https://user-images.githubusercontent.com/13413715/59524158-bf622700-8f05-11e9-943e-5df31bb34b2c.png)
![image](https://user-images.githubusercontent.com/13413715/59524203-d9036e80-8f05-11e9-8b32-ddc5f2afae59.png)

**Comment by wilkinsona** [comment]
Recursive binding of configuration properties is not supported. Please see https://github.com/spring-projects/spring-boot/issues/16444 for details.

**Comment by brucelwl** [comment]
@wilkinsona I found that method bind(....) has parameter allowRecursiveBinding, so why not open it? and why is the protected method set to final?

**Comment by wilkinsona** [comment]
The parameter is currently used for a specific case and not for general recursive binding. The method is final as it has not been designed to be sub-classed. Our reasons for not wanting to open up and expand support for recursive binding are already documented in #16444:

> We've discussed this again today as a team and the general consensus is that we don't want to supported recursive property binding. We can't really see a clear way to implement such a feature without adding a lot of complexity.
