### ISSUE TITLE
Move away from bash for release process

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17261]
The build process never seems to go well, in part because we can't really test the bash property. Now that we know the commands we need to issue, it would be worth looking at writing a tool in a language that we can properly test.

**Comment by wagnerluis1982** [comment]
@philwebb, the bash script is committed to the repository? I think Python is a good candidate for a new script.

**Comment by philwebb** [comment]
Thanks for the suggestion @wagnerluis1982, but I don't want to introduce another language just for releases.

**Comment by wagnerluis1982** [comment]
@philwebb, I understood, from description, that you are looking for a language which can be properly tested. On this premisse I understand almost any language can do the job, but scripting languages are the best.

**Comment by wagnerluis1982** [comment]
I see now that Groovy is also a good candidate and it's a language already used in the repository :slightly_smiling_face:

**Comment by philwebb** [comment]
@wagnerluis1982 I think ideally we'll want to create a new project that contains our build logic in a way that we can test it. The problem isn't with bash per se, rather that we don't have a good way to test the scripts before we actually run a release.

**Comment by wagnerluis1982** [comment]
Understood :+1:

**Comment by snicoll** [comment]
FTR I could see files were still syncing with Bintray while, according to the logs, CI was trying to sync with central. This will never work so we probably need to revisit those calls and make sure they block (including the creating of signatures that happen with a async job as far as I can see).

```
Syncing spring-boot/spring-boot-2.1.x-stage-release-10 to Maven Central
Calling Bintray to sync to Sonatype
Failed to sync
```

Second line was after 7 min or something. And all files were definitely not on Bintray at that time.
