### ISSUE TITLE
PooledDataSourceAvailableCondition uses some strange classloader!=null logic

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#17284]
In `PooledDataSourceAvailableCondition` we see this:

```java
if (getDataSourceClassLoader(context) != null) {
	return ConditionOutcome
						.match(message.foundExactly("supported DataSource"));
}
```

where `getDataSourceClassLoader(context)` is a private method which is only called once. It looks like it could or should be refactored to a boolean method:

```java
private boolean hasDataSourceClassLoader(ConditionContext context) {
            Class<?> dataSourceClass = DataSourceBuilder
                    .findType(context.getClassLoader());
            return dataSourceClass != null;
        }
```

What class has a null classloader? Answer, "none" (in a regular JVM), so the refactoring isn't needed (although the intent is clearer). But in GraalVM, answer "all of them", so the test is always false, even if the class is present and loaded.

**Comment by dsyer** [comment]
So it appears that the class loader null check is in case the `DataSource` is in the boot classloader (still bizarre), but the driver is in the app classcloader. I'm not even sure I get that. The intention is that the condition only matches if there is a pooled `DataSource` implementation available, and that it can create connections. But we don't want to actually create a connection at that point, I guess. So we have kind of a rule of thumb. Which I guess could still fail in practice, but for at least one archaeologically interesting use case it works.

**Comment by wilkinsona** [comment]
The strange logic was added [here](https://github.com/spring-projects/spring-boot/commit/5249f54c5a3253c30132d80cf715c9a734db7409#diff-e335e933c4b5fe8e58b5fec085353c68R200). I can't tell why looking at the commit and the referenced issues. Perhaps it jogs your memory a bit and you can remember, @dsyer?

**Comment by dsyer** [comment]
Nope sorry. I see that I shaved quite few lines of code from the custom condition. I probably just felt good that it worked and didn't really analyse what the null check was doing. The comment on `getDataSourceClassLoader()` looks like it came from before that change, and most of the code that used that method was removed. I suspect we can clean this up.
