### ISSUE TITLE
server.compression fails unless default port is changed

### ISSUE THREAD

**Issue by kay73** [spring-projects/spring-boot#17296]
Hi all,

`server.compression` properties fail or are ignored in a Spring Boot (WebMVC) application if default `server.port` 8080 is kept. As soon as it is changed, compression works.

Please find attached a vanilla [Spring Initializr](https://start.spring.io/) generated Spring Boot 2.1.6 Maven application with WebMVC as its only dependency:

[boot-mvc-property-issue-demo.zip](https://github.com/spring-projects/spring-boot/files/3318401/boot-mvc-property-issue-demo.zip)

 I deleted test code and its dependencies. I added a 54 kb text file as a static resource that compresses efficiently and pasted `server.compression` properties into `application.properties` which I took verbatim from [Spring Common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html).

Steps to reproduce:

* Build: `mvn clean package`
* Run: `java -jar target/demo-0.0.1-SNAPSHOT.jar`
* In browser using devtools access http://localhost:8080/test.txt: Observe that transferred bytes are 54 kb and `Content-Encoding` header is absent.

* Terminate application, run: `java -Dserver.port=8089 -jar target/demo-0.0.1-SNAPSHOT.jar`
* In browser using devtools access http://localhost:8089/test.txt: Observe that transferred bytes are 1.4 kb and `Content-Encoding` header is present and has value `gzip`.

Reproduced in Chrome (5.0.3770.100) regular/incognito, Firefox (67.0.3, 67.0.4) and cURL on macoS Sierra. Same happens with Jetty instead of Tomcat. Any other port than 8080 seems to work.

Reproducible on macOS:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
````
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-macosx) (build 1.8.0_202-b05)
OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-macosx) (build 25.202-b05, mixed mode)
````
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_202, vendor: Azul Systems, Inc., runtime: /Users/kay/.sdkman/candidates/java/8.0.202-zulu/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```
Reproducible on Linux:
```
Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
```
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

However: **Not reproducible** and reported to work on Windows (Oracle-JDK):
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Can anyone confirm or report successful behavior?

Best regards,
Kay

**Comment by wilkinsona** [comment]
Thanks for the sample. I cannot reproduce the behaviour that you have described on macOS.

Safari:

```
HTTP/1.1 200
Transfer-Encoding: Identity
Content-Type: text/plain
Last-Modified: Sun, 23 Jun 2019 19:05:09 GMT
Accept-Ranges: bytes
Date: Sun, 23 Jun 2019 19:05:34 GMT
Content-Encoding: gzip
Vary: accept-encoding
```

Chrome:

```
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Type: text/plain
Date: Sun, 23 Jun 2019 19:07:16 GMT
Last-Modified: Sun, 23 Jun 2019 19:05:09 GMT
Transfer-Encoding: chunked
vary: accept-encoding
```

> cURL on macoS Sierra

How did you send the request with curl? It won't send the required `Accept-Encoding` header automatically. `--compressed` is one way to get it to send the necessary header and a gzip compressed response is returned:

cURL:

```
curl -i --compressed localhost:8080/test.txt
HTTP/1.1 200 
Last-Modified: Sun, 23 Jun 2019 19:05:09 GMT
Accept-Ranges: bytes
vary: accept-encoding
Content-Encoding: gzip
Content-Type: text/plain
Transfer-Encoding: chunked
Date: Sun, 23 Jun 2019 19:09:22 GMT
```

It looks like there's something specific to your environment that is preventing this from working as expected. I would guess that the required `Accept-Encoding` header is not being sent. If you can show that Tomcat and Jetty are receiving a request with the required `Accept-Encoding` header and are still sending an uncompressed approach, we can take another look. Failing that, you'll have to diagnose the client side problem yourself as it's out of Boot's control.

**Comment by kay73** [comment]
Thank you for the quick response @wilkinsona !

my cURL call is was generated by the Chrome DevTools. I shortened it somewhat. It accepts gzip encodings and this one triggers the issue on my system:

```
curl 'http://localhost:8080/test.txt' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6' --compressed -o out.txt
```

This one displays transferred bytes quite nicely and changing 8080 for other shows the problem on my side.

I also checked the request headers in the Dev tools of Chrome and they properly send `Accept-Encoding: gzip, deflate, br`.

Nevertheless, it is valuable information that the configuration actually works on other similar systems and I will concentrate on my local system.

**Comment by wilkinsona** [comment]
For the record, here's cURL's behaviour for me on macOS:

```
$ curl 'http://localhost:8080/test.txt' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6' --compressed -o out.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1157    0  1157    0     0  13203      0 --:--:-- --:--:-- --:--:-- 13298
```

**Comment by wilkinsona** [comment]
@kay73 If you're not already aware, Tomcat makes the decision about whether or not to compress a response in `org.apache.coyote.CompressionConfig.useCompression(Request, Response)`. You may want to place a breakpoint in that method and step through to see why the response is not being compressed. Given that it does not work on 8080 but does work on other ports, I still suspect that the `Accept-Encoding` header is not reaching the server as the compression configuration is independent of the port configuration.

**Comment by kay73** [comment]
Hi all, 

since this issue cannot be reproduced and since I received reports that things are working, it really appears to be a local issue. Sorry for bothering. Closing ticket.

**Comment by wilkinsona** [comment]
Thanks for letting us know.

**Comment by kay73** [comment]
After endless frustrating digging w/ Wireshark, I found the issue and it has nothing to do with Spring Boot. If you are interested: My company forces me to run a pointless overpriced Anti-Virus-Software on macOs. It acts as an invisible proxy (more like a MIM attack) on ports 80, 8080 and 3128, duplicates the requests, decompresses and scans the responses and forwards them back to the browser.

**Comment by wilkinsona** [comment]
There's no need to apologise. Thanks very much for letting us know the cause of the problem. Hopefully it'll help to save someone else some time in the future if they have a similar problem.
