### ISSUE TITLE
Conditioning alonbean invalidation problem

### ISSUE THREAD

**Issue by lxchinesszz** [spring-projects/spring-boot#17303]
```java
@ConditionalOnBean(ConfigC.class)
@Configuration
public class ConfigB {
    public ConfigB() {
        System.out.println("ConfigB create");
    }
}
@ConditionalOnMissingBean(ConfigA.class)
@Configuration
public class ConfigC {
    public ConfigC(){
        System.out.println("ConfigC create");
    }
}
@Configuration
public class ConfigA {
    public ConfigA(){
        System.out.println("ConfigA create");
    }
}
```
#### Issues: A and B will load successfully, but C will not load. At this point, the condition for B does not take effect。
Why the conditional judgment cannot pass 'beanfactory.getbean (...) ', so that the order of dependencies is automatically guaranteed, rather than being determined by the 'getBeanNamesForType' method?

**Comment by philwebb** [comment]
I'm afraid you can't use `ConditionalOnMissingBean` on regular `@Configuration` classes because the order is not defined. See https://github.com/spring-projects/spring-boot/issues/17300#issuecomment-505099149 for a similar issue discussing `@ConditionalOnBean`.
