### ISSUE TITLE
Customize the 'message' field in the response error body?

### ISSUE THREAD

**Issue by matsev** [spring-projects/spring-boot#1731]
How can one customize the `message` field in the error response body (and at the same time customize the http status code)?

Based on the answer to #1677 I attempted to use the [sendError(int, String)](http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#sendError%28int, java.lang.String%29) method to customize both the http status code and the `message` field simultaneously:

```
@ExceptionHandler(IllegalArgumentException.class)
void handleIllegalArgumentException(HttpServletResponse response) throws IOException {
    response.sendError(HttpStatus.BAD_REQUEST.value(), "custom message");
}
```

When a request causes an `IllegalArgumentException` the client will get the following response:

```
HTTP Status 400 - Bad Request
 {
    "timestamp": 1413702719532,
    "status": 400,
    "error": "Bad Request",
    "exception": "java.lang.IllegalArgumentException",
    "message": "original exception message",
    "path": "/test"
}
```

The problem is that I expected the `message` field to equal `custom message` (or whatever the value was passed to message parameter to the `sendError(int, java.lang.String)` method). Instead, I see `original exception message` (i.e. the value that was passed to the `IllegalArgumentException` constructor).

Side note, the http status header and all other fields in the response body are correct.

Related to #1677 
Spring Boot version 1.1.8

**Comment by singhalavi** [comment]
i spent couple of hours sorting it out, thought of sharing it for others benefit.

you can do it this way

`@ExceptionHandler(ServiceException.class)
	@ResponseBody
	public ErrorResponse handleServiceException(HttpServletRequest req, HttpServletResponse response, ServiceException e) 
	{
		ErrorResponse error = new ErrorResponse();
		error.setResponseMessage(e.getMessage());
		//Set custom non standard http status code
		response.setStatus(499);
		return error;
	}`

ErrorResponse is a normal java object

**Comment by Kartikkman** [comment]
> 
> 
> i spent couple of hours sorting it out, thought of sharing it for others benefit.
> 
> you can do it this way
> 
> @ExceptionHandler(ServiceException.class)
> 	@ResponseBody
> 	public ErrorResponse handleServiceException(HttpServletRequest req, HttpServletResponse response, ServiceException e) 
> 	{
> 		ErrorResponse error = new ErrorResponse();
> 		error.setResponseMessage(e.getMessage());
> 		//Set custom non standard http status code
> 		response.setStatus(499);
> 		return error;
> 	}
> 
> ErrorResponse is a normal java object

Hi @singhalavi , It worked Thanks a lot man !! 
Could you please also share the reason behind it working !!

**Comment by RajHirani** [comment]
You can also use @ControllerAdvice
`
@ControllerAdvice
@Slf4j
public class ExceptionHelper {

    @ExceptionHandler(value = { UserAlreadyExistAuthenticationException.class })
    public ResponseEntity handleInvalidInputException(UserAlreadyExistAuthenticationException ex) {
        log.error("UserAlreadyExistAuthenticationException: ",ex.getMessage());
        return new ResponseEntity<Object>(ex.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
`
