### ISSUE TITLE
Add application property for redis client name

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#17315]
Both [Lettuce](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.LettuceClientConfigurationBuilder.html#clientName-java.lang.String-) and [Jedis](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/jedis/JedisClientConfiguration.JedisClientConfigurationBuilder.html#clientName-java.lang.String-) support configuring a client name to be set on new connections.
It would be convenient if autoconfiguration supported it via an application property.

**Comment by philwebb** [comment]
Closing in favor of PR #17330
