### ISSUE TITLE
Allow custom resource handlers to provide favicon

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#17318]
In Spring Data REST's HAL Explorer module we repackage an Angular application in a JAR and add a resource handler via `StaticResourceProvider.customizeResources(…)`. That application contains a `favicon.ico`. This one unfortunately does not get served unless I explicitly configure `spring.mvc.favicon.enabled=false`.

Would it make sense to tweak the auto configuration to also try the `ResourceHandlers` registered for the file and use the Boot provided one as fallback? Using the configuration option feels a bit weird, as you seem to have to disable favicons to actually make it work.

**Comment by wilkinsona** [comment]
We currently configure a separate handler mapping for `**/favicon.ico` that will serve the favicon from all of the configured static resource locations and the root of the classpath in that order. Spring Data REST registers a resource handler for `/explorer/**` the will serve the HAL explorer from `classpath:META-INF/spring-data-rest/hal-browser/`. The resource handler mapping is never called for any `favicon.ico` request as our separate handler mapping gets in there first. 

Setting `spring.mvc.favicon.enabled=false` disables our separate handler mapping for `**/favicon.ico`. Perhaps confusingly, this only disables support for serving a `favicon.ico` from the root of the classpath, most likely Boot's default favicon. A custom favicon in one of the app's static resource locations will continue to work. Disabling our separate handler mapping allows Data REST's resource registration to serve HAL explorer's favicon.

We cannot move our separate handler mapping after the static resource handler mapping as the latter will then handle the request and prevent the former from doing so. An alternative would be to add a resource registration that can serve a favicon from the root of the classpath and remove our separate handler mapping entirely. This could be implemented in a couple of different ways:

1. Add a handler for `**/favicon.ico`
2. Add a handler for `favicon.ico`

The first works for any `favicon.ico` request but the `**/favicon.ico` pattern takes precedence over the `/explorer/**` pattern for a request for `/explorer/**` so it does not solve the problem described in this issue.

The second handles requests to `/favicon.ico` but not requests for a nested favicon such as `/nested/favicon.ico`. This means that if a user has placed a custom favicon nested beneath the root of the classpath, it would no longer work. A nested favicon in a static resource location would work as before.

The second option seems like a reasonable change for 2.2 to me. Boot's default favicon will continue to work for apps that do not have a favicon. A custom favicon placed at the root of the classpath will also continue to work as it did before (with the same reliance on classpath ordering). A custom favicon placed somewhere beneath a static resources location will also continue to work as it did before. That leaves a favicon nested beneath the root of the classpath that will no longer work. However, I suspect such usage is rare. Migration could be performed by moving the favicon to a static resource location or via a custom resource handler registration.

**Comment by wilkinsona** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/8aed06452d0e6b06fb04999611adaa7a4af1e94e.
