### ISSUE TITLE
spring-boot-starter-swagger module with autoconfiguration

### ISSUE THREAD

**Issue by Aloren** [spring-projects/spring-boot#17313]
Swagger is one of the tools for documenting Rest API. Does it make sense to add `spring-boot-starter-swagger` with default auto configuration into Spring Boot project?

I've found the relevant issue: https://github.com/spring-projects/spring-boot/issues/842
It's been already 5 years since it was opened. Maybe there were any changes regarding this topic?

**Comment by wilkinsona** [comment]
Thanks for your interest in a Swagger starter. Please comment on #842 rather than opening a new issue for the same thing.
