### ISSUE TITLE
StringToEnumIgnoringCaseConverterFactory getLettersAndDigits returns an integer string

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17327]
The `StringToEnumIgnoringCaseConverterFactory.getLettersAndDigits` accidentally returns a string containing the integer representations of the chars. We get away with it because the same method is used to compare the source and candidate but it makes debugging harder.

We should be casting the `int` back to a `char` when we build the String.

**Comment by ielatif** [comment]
@philwebb we can fix this by using `name.chars().mapToObj((c) -> (char) c)`

see this [stackoverflow](https://stackoverflow.com/questions/22435833/why-is-string-chars-a-stream-of-ints-in-java-8/22436638)

> ```
> hello.chars()
>         .mapToObj(i -> (char)i)
>         .forEach(System.out::println);
> ```
> Here I obtain an IntStream and map it to an object via the lambda i -> (char)i, this will automatically box it into a Stream<Character>, and then we can do what we want, and still use method references as a plus.

**Comment by philwebb** [comment]
Thanks @ielatif, I had the same fix lined up locally. I've just not pushed it yet.
