### ISSUE TITLE
Update caching auto-configuration to use Infinispan's Spring 5 support

### ISSUE THREAD

**Issue by evpaassen** [spring-projects/spring-boot#17333]
Spring Boot 2 still uses the Spring 4 version of Infinispan: the BOM includes `infinispan-spring4-common` and `infinispan-spring4-embedded`. Instead, I think it should use `infinispan-spring5-common` and `infinispan-spring5-embedded`.

Or is there a reason why the Spring 4 version is still being used? Can't find anything about it here, so I guess it's never been considered yet, because `infinispan-spring5-embedded` is still a relatively new artifact?

**Comment by wilkinsona** [comment]
Thanks for bringing this to our attention. I don't think there's a good reason for it. Looks like we (I, most likely) just missed it when upgrading to 9.4.9 or later.

**Comment by wilkinsona** [comment]
There's a bit more to this as the new `infinispan-spring5-*` modules are not backwards compatible with their equivalent `infinispan-spring4-*` modules. For example, `org.infinispan.spring.provider.SpringEmbeddedCacheManager`, which we expose as a bean, has moved to the `org.infinispan.spring.embedded.provider` package.

**Comment by evpaassen** [comment]
I see, that would be a kind of a breaking change.

It might be worth noting here that the `infinispan-spring-boot-starter-embedded` starter provided by Infinispan (see https://github.com/infinispan/infinispan-spring-boot) *does* use `infinispan-spring5-embedded`. And it seems like Infinispan 10 won't get Spring 4 artifacts anymore.

**Comment by wilkinsona** [comment]
We're going to switch to the `-spring5-` modules in 2.2.
