### ISSUE TITLE
[Feature] FilterRegistrationBean http method

### ISSUE THREAD

**Issue by speedfl** [spring-projects/spring-boot#17340]
Enhancement (please don't include this emoji/text, just add your details)

Hello.

First thanks for the work you are doing. I am currently facing an issue trying to implement Filter for my authentication mechanism.

I Saw that I can add urlPattern like this:

``` 
registrationBean.setUrlPatterns(Arrays.asList("/path1", "/path2/*"));
```

However I am not able to add pattern base on the httpMethod. 

A concrete example: Only allowed users can Create modify or delete the resource. However everybody can display it.

```
// Only allowed
POST /path1
PUT /path1/{id}
DELETE /path1/{id}

// all
GET /path1?q=query
GET /path1/{id}

```

I implemented my own mechanism by always entering in the Filter and providing to constructor a list of object containing the path + method.

```
registrationBean.setFilter(new MyFilter(context, 
				Arrays.asList(new UrlPattern(HttpMethod.POST, "/path1"),
						new UrlPattern(HttpMethod.PUT, "/path1/*"),
						new UrlPattern(HttpMethod.DELETE, "/path1/*"))));
```

However I think it could be a good improvement.

Thanks in advance for your answer

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

Spring Boot's Filter registration maps directly onto the APIs provided by the Servlet specification, specifically the methods available on `javax.servlet.FilterRegistration.Dynamic`. This API does not support HTTP method-specific path patterns so we do not offer such functionality in Spring Boot. If you would like to see support for this in the future, you should raise it with the Servlet expert group for consideration for inclusion in a future update to the specification.

In the meantime, your approach of implementing HTTP method-specific behaviour in your Filter is a good approach. Alternatively, you may want too look at Spring Security which provides built-in support for configuring different security rules for different HTTP methods.
