### ISSUE TITLE
Consistently coerce false to off where applicable

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17385]
YAML 1.1 maps `off` to `false`. We deal with this in `LoggingApplicationListener` by coercing `false` back to `LogLevel.OFF`:

https://github.com/spring-projects/spring-boot/blob/35a178abab02217d64c3731736dc6921c03334f1/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/logging/LoggingApplicationListener.java#L363-L369

This allows users to configure logging using `logging.level.example.my.package: off` in YAML.

We do no perform any coercion when turning the banner off so `spring.main.banner-mode: off` will fail and `spring.main.banner-mode: 'off'` has to be used instead.

I think we should consistently allow `false` to be bound to an enum that would accept `off`. Perhaps this is something that could be done in the binder rather than as a special case for banner mode.

**Comment by wilkinsona** [comment]
There's some advice in the docs about turning the banner off that we can remove now.

**Comment by romainmoreau** [comment]
Since Spring Boot 2.2.0.M5, I have to use `logging.level.example.my.package: 'off'` instead of `logging.level.example.my.package: off` which worked with Spring Boot 2.2.0.M4 but is now silently ignored with Spring Boot 2.2.0.M5.
When I read this issue, I understand that it should not be the case, should it?

**Comment by mbhave** [comment]
@romainmoreau Thanks for trying out the milestone. It does look like this isn't working anymore. I've created a [new issue](https://github.com/spring-projects/spring-boot/issues/17798) for it since this was already closed.

**Comment by freekry** [comment]
> Since Spring Boot 2.2.0.M5, I have to use `logging.level.example.my.package: 'off'` instead of `logging.level.example.my.package: off` which worked with Spring Boot 2.2.0.M4 but is now silently ignored with Spring Boot 2.2.0.M5.
> When I read this issue, I understand that it should not be the case, should it?

I tried and they(logging.level.example.my.package: 'off' ,logging.level.example.my.package: off) were all worked with Spring Boot 2.2.0.M5,can you show you demo?
