### ISSUE TITLE
Tables don't look as nice in the new documentation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17392]
Compare

https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints

https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints

**Comment by bclozel** [comment]
Maybe something to open against https://github.com/spring-io/spring-doc-resources/issues ?
I don't know if there's something to be done in our documentation sources directly.

**Comment by philwebb** [comment]
Closing in favor of https://github.com/spring-io/spring-doc-resources/issues/16
