### ISSUE TITLE
Provide a Spring Boot REST Security example with access token

### ISSUE THREAD

**Issue by Vad1mo** [spring-projects/spring-boot#1741]
There is no Spring Boot REST Security examples out there. The one exist on the net are all different and do not fit into the ease of spring boot.

**Comment by Loki-Afro** [comment]
What is meant here? OAuth2? Did you see this project: https://github.com/royclarkson/spring-rest-service-oauth?

**Comment by wilkinsona** [comment]
`spring-boot-sample-secure-oauth2`, new in 1.3, shows how to secure a REST API built with Spring Data REST using Spring Security OAuth.
