### ISSUE TITLE
JacksonAutoConfiguration with better default time zone

### ISSUE THREAD

**Issue by imbyungjun** [spring-projects/spring-boot#17414]
`JacksonAutoConfiguration` configures default time zone as `UTC` ([L136](https://github.com/spring-projects/spring-boot/blob/40f66c80f8a3636df2a17c98d7fc8de8ff1c0a22/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L136)). 
But, if want to use the **default time zone**, there's no way to achieve it with autoconfiguration. To achieve the **default time zone**, we must register a custom message converter bean.

Using the default date format with the **default time zone** looks more convenient. In this case, if want to use UTC time zone, we can easily set it up in `spring.jackson.time-zone` property.

Default time zone should be like this
```java
new JacksonJodaDateFormat(DateTimeFormat.forPattern(jacksonProperties.getDateFormat()).withZone(DateTimeZone.getDefault());
```

**Comment by wilkinsona** [comment]
Jackson uses UTC as its default timezone so I think it makes sense for Boot to align with that. That's what we do when configuring the date format. Jackson's Joda Time integration complicates things as its time zone needs to be configured separately. We currently hardcode it to UTC. Perhaps we should make it configurable, but I also think we should consider deprecating and removing Joda Time support. Now that we have a Java 8 baseline and, therefore, `java.time`, I would expect usage of Joda Time to be minimal. Joda Time's [documentation](https://www.joda.org/joda-time/) asks users to migrate:

> Joda-Time is the de facto standard date and time library for Java prior to Java SE 8. Users are now asked to migrate to java.time (JSR-310).

@imbyungjun Are you only interested in configuring the time zone used with Joda Time? You can configure the default time zone that's used for `Date`, `java.time`, etc, using a `Jackson2ObjectMapperBuilderCustomizer`.

To support configuring the use of the default time zone via application.properties, I think a change to Framework would be required in its `StringToTimeZoneConverter` to special case something like `default`.

**Comment by imbyungjun** [comment]
After reading your mention above, it seems quite complicated to change the Joda-Time related codes. And current implementation of `JacksonAutoConfiguration`, UTC as default, look reasonable as a default time zone.

I thought that it is not reasonable that I can't set the time zone as `default` by using auto configuration and application.properties.
To make the `StringToTimeZoneConverter` allows `default` would be nice and enough in my opinion.

**Comment by philwebb** [comment]
I've raised https://github.com/spring-projects/spring-framework/issues/23232 to discuss the conversion option.

**Comment by philwebb** [comment]
We've decided to [deprecate Jodatime support](https://github.com/spring-projects/spring-boot/issues/17419) in 2.2.x and since changing the default from UTC to the `spring.jackson.time-zone` might break some users I think it's best if we leave this code as it is.

@imbyungjun you should be able to use the `Jackson2ObjectMapperBuilderCustomizer` option discussed above to meet your needs.
