### ISSUE TITLE
Fresh Spring Boot Starter Jersey

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-boot#17427]
Jersey 2.29 is released and have a fresh Spring 5 Module:
http://blog.supol.cz/?p=144
https://github.com/eclipse-ee4j/jersey/pull/4062
And earlier also we faced problem with Jersey on Spring Boot recent version:
https://github.com/spring-projects/spring-boot/issues/15365
So it make sence to update Spring Boot Jersey Module to use
new Jersey 2.29 along with its new Spring 5 Integration Module.

**Comment by wilkinsona** [comment]
Duplicates #17412 and #17404.
