### ISSUE TITLE
Improve/disambiguate the documentation for spring.profiles.active 

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-boot#17436]
According to the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html#boot-features-adding-active-profiles):

> Sometimes, it is useful to have profile-specific properties that add to the active profiles rather than replace them. The spring.profiles.include property can be used to unconditionally add active profiles.

The example in the documentation shows two included profiles that look to have mutually exclusive properties:

```yaml
spring.profiles.include:
  - proddb
  - prodmq
```

As evidenced by [this question](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html#boot-features-adding-active-profiles), and [this comment](https://stackoverflow.com/questions/47368086/spring-spring-profiles-include-overrides#comment81706086_47373190), the documentation is a bit ambiguous.

Let's add this extra information to the documentation:

#### `application-foo.yaml`

```
myCustomProperty: 10
```

#### `application-bar.yaml`

```
spring:
  profiles:
    include: foo
myCustomProperty: 20
```

In this case, `foo` wins and `myCustomProperty = 10`.

#### `application-x.yaml`

```
myCustomProperty: 10
```

#### `application-y.yaml`
```
myCustomProperty: 20
```

#### `application-z.yaml`
```
spring:
  profiles:
    include: x, y

myCustomProperty: 30
```

In this, `y` wins and `myCustomProperty = 20`.

---

Also, IMHO, when the included profiles (e.g. x and y in the example above) have shared property definitions, a warning log message should be emitted as I think a situation like this is the sign of a potential misconfiguration by the user.

**Comment by mbhave** [comment]
Profile includes can get quite tricky depending on the order, which can quickly make the documentation confusing. See [this comment](https://github.com/spring-projects/spring-boot/issues/16303#issuecomment-480398738). We have a number of open issues around [active and included profiles](https://github.com/spring-projects/spring-boot/issues?q=is%3Aopen+is%3Aissue+label%3A%22theme%3A+profiles%22). It will probably lead to a bigger refactor of the profiles code and we can tackle this documentation issue as part of that.

**Comment by mbhave** [comment]
With the rewrite of config file and profile processing in 2.4.x, profiles can no longer be included in profile specific sub sections. All profiles need to be available before any profile-specific files/documents are loaded. This issue can be closed.
