### ISSUE TITLE
Micrometer common tags for Cloud Foundry deployment properties

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-boot#17433]
Add Micrometer common tags for Cloud Foundry deployment properties, e.g. for [CF environment variables](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html).

Tags should be set only if the ["cloud" Spring profile is set](https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections/spring-service-bindings.html#cloud-profiles)
 
In `Spring Cloud Data Flow` to support metrics aggregation based on Cloud Foundry properties (such as `org`, `space`, `application id` ...), we’ve extended all `Spring Cloud Stream Apps` with an additional [CloudFoundryMicrometerCommonTags](https://github.com/spring-cloud-stream-app-starters/core/blob/master/common/app-starters-micrometer-common/src/main/java/org/springframework/cloud/stream/app/micrometer/common/CloudFoundryMicrometerCommonTags.java) 

Now to provide similar experience for the `Spring Cloud Task` apps we've copied the equivalent functionality into the [task core project](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/configuration/MetricsAutoConfiguration.java#L64) too.

It feels like this is a generic functionality that could benefit any Spring Boot application deployed on CF platform.

**Caveats**: While the `MeterRegistryCustomizer` is part of the `actuator`, some projects such as the `Spring Cloud Task` intentionally exclude the actuator dependency and implementing the tag injections [directly](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/configuration/MetricsAutoConfiguration.java)

**Comment by philwebb** [comment]
We discussed this issue today on one of our weekly calls and we think it's a nice addition, however, it should live in actuator. For the Spring Cloud Task case, could they use `actuator` but not `actuator-autoconfigure`?

**Comment by snicoll** [comment]
There are a few things to consider.

I don't think checking for the `cloud` profile is a a good idea as this profile name can be reused in other situations. Rather we should check that the app is running on CloudFoundry using `@ConditionalOnCloudPlatforù`.

I am also a bit concerned by the number of tags exposed: `cf.org.name`, `cf.space.id`, `cf.space.name`, `cf.app.id`, `cf.app.name`, `cf.app.version`, 	`cf.instance.index`. Do we want to expose all that by default? 

paging @shakuzen as I am wondering about what the best practices are for this.

**Comment by shakuzen** [comment]
Note there is also an issue in the java-buildpack to support the same thing: https://github.com/cloudfoundry/java-buildpack/issues/644. We should coordinate on tag names we use to mean the same thing. To some degree these issues obviate each other, but applications that use the java-buildpack are not necessarily Spring Boot apps, and Spring Boot apps don't necessarily use the java-buildpack on Cloud Foundry.

As for best practice, cardinality of tag values should grow at most at a "reasonable rate" compared to the retention period of metrics. What is reasonable depends on the scale of the metrics backend and the scale of metrics collected. In essence, will the metrics backend be able to handle the growth of time series over the retention period and still perform queries quickly enough?

For each unique combination of tag values, it will create a new time series in the metrics backend. For example, `cf.app.version` (which is derived from VCAP_APPLICATION's `application_version`) is [documented as](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION):

> GUID identifying a version of the app. Each time an app is pushed or restarted, this value is updated.

Therefore, each time an application is restarted/pushed, if this were being tagged, it would result in new time series for every metric from that application. Similarly, some Cloud Foundry users include a version in the application name, manually or via a tool such as Spinnaker (which uses frigga, mentioned in the java-buildpack issue).

@tzolov Why include `cf.app.id` and `cf.app.version`? They both seem to serve the purpose of identifying a version of a deployed application uniquely. Also `cf.space.id` and `cf.space.name` seem redundant if also including `cf.org.name` - I believe org name + space name combinations must be unique inside a Cloud Foundry foundation.

I would say `cf.org.name`, `cf.space.name`, `cf.app.name`, and `cf.instance.index` are probably safe defaults. A version tag would be useful for comparing metrics from the same app across versions, but a random GUID does not seem meaningful to a human. For example, using the `cf.app.version` you wouldn't be able to distinguish between a restart, a push of the same version, a push of a previous version, and a push of a new version.

Another thing to consider might be to make the list of tagged attributes from Cloud Foundry into a configuration property, so users can pick which they want tagged more easily.

Adding common tags by default should also be called out in the release notes as this can affect the results of some metrics queries, depending on how they are written (e.g. with assumptions of what tags are on a metric)

**Comment by philwebb** [comment]
Thanks for the feedback @shakuzen, especially the note about the buildpack also trying to support the same thing. After some more consideration, we're not sure we should try to include this in Spring Boot after all (at least not at this point). I'm going to close this one for now but add a comment to https://github.com/cloudfoundry/java-buildpack/issues/644 so that we can look more broadly at the problem.
