### ISSUE TITLE
Caching documentation contains instruction for removed Guava support

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-boot#17446]
>If you add dependencies manually, you must include spring-context-support in order to use the JCache, EhCache 2.x, or Guava support.

Source: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html

I guess this sentence should be updated, as Guava support was removed (if I am not mistaken).

**Comment by snicoll** [comment]
Good catch @PascalSchumacher!
