### ISSUE TITLE
Clarify how RestTemplateBuilder.defaultHeader treats the values

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17441]
https://github.com/spring-projects/spring-boot/pull/17440 raised an interesting point about how the values of the default header are treated. The current behaviour allows an array to be passed in and reflects subsequent modifications to this array in the default header. We should either keep that behaviour and add a test that verifies it or we should simplify things as proposed by @izeye in #17440.

**Comment by nosan** [comment]
> The current behaviour allows and array to be passed in and reflects subsequent modifications to this array in the default header.

Current implementation copies the array values into the list to avoid this, hence if an array is changed this will not affect to builder's list.

**Comment by wilkinsona** [comment]
Whoops. I got that the wrong way around. Thanks, @nosan.

As I've just shown, the methods for creating a `List` from a `Collection` or a `List` from an array often confuse me as I can never remember which copies the contents of the input and which uses the input as a backing store. Perhaps we should rename the `setOf` and `listOf` methods to `copiedSetOf` and `copiedListOf` to clarify things (for me at least).
