### ISSUE TITLE
Spring Boot connect with Postgres SSL 

### ISSUE THREAD

**Issue by ryrun168** [spring-projects/spring-boot#17447]
Dear All,

I have an issued to related to connection between spring boot to postgres ssl. 

My database is postgres and i enabled it with SSL Mode, but when i connect it to spring bot it can't work.

So do you have any solution ?

**Comment by wilkinsona** [comment]
GitHub issues aren’t the best place to ask for advice. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Perhaps you’ve found a bug or something that we could make easier but it’s impossible to tell without a much more detailed description of what you tried and in what way it didn’t work.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
