### ISSUE TITLE
Configuration Properties are not read by Spring boot when setting properties like this “export my_variable=something”

### ISSUE THREAD

**Issue by farazdurrani** [spring-projects/spring-boot#17456]
I want to make changes without having to rebuild and redeploy the application. I want to make changes on the fly.
```
export TACO_ORDERS_PAGESIZE=NINETY
```
This is my code where it is injected:
```
@SpringBootApplication
@RestController
@EnableScheduling
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Value("${taco.orders.pageSize}")
    private String pageSize;

    @GetMapping("/myName")
    public String myName() {
        return pageSize;
    }

    int i = 0;

    @Scheduled(fixedRate = 2000L)
    public void scheduled() {
        System.err.println(++i + "-" + pageSize);
    }
}
```
This is what I have in my application.yml file as a default value:
```
taco:
  orders:
    pageSize: fifty
```
This print fine "fifty". But when I go to terminal and set a different value for the key, that new value is not reflected.

I have created a [github repo](https://github.com/farazdurrani/SpringBoot_ConfigurationProperties_NotWorking) to reproduce this issue:

**Comment by wilkinsona** [comment]
Spring Boot does not support changing configuration properties at runtime. If you want a new configuration property value to be picked up you have to restart your application. Spring Cloud provides support for refreshing properties at runtime that may be of interest to you. You can learn more about it [here](https://cloud.spring.io/spring-cloud-static/spring-cloud.html#_refresh_scope).
