### ISSUE TITLE
Align with changes to WebFlux body methods

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17460]
https://github.com/spring-projects/spring-framework/pull/23212 deprecated some body-related methods and provided replacements. We should align.

**Comment by making** [comment]
These methods have been renamed again in https://github.com/spring-projects/spring-framework/commit/008687d5aef120205ad218a27c2d8f2fa65122f3

**Comment by wilkinsona** [comment]
Thank you, @making. I believe @bclozel is working on the necessary change.
