### ISSUE TITLE
Mutation of Jackson2ObjectMapperBuilder in one injection point may affect subsequent usages

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17477]
`Jackson2ObjectMapperBuilder` is stateful and we have a few places where it's injected and mutated:

https://github.com/spring-projects/spring-boot/blob/3c28622ebc81444974859685b14a663697612e23/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/JacksonHttpMessageConvertersConfiguration.java#L63-L68

https://github.com/spring-projects/spring-boot/blob/3c28622ebc81444974859685b14a663697612e23/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L102-L107

https://github.com/spring-projects/spring-boot/blob/3c28622ebc81444974859685b14a663697612e23/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketStrategiesAutoConfiguration.java#L76-L85

As things stand, depending on auto-configuration ordering, whether or not you have Jackson's XML format on the classpath, and when precisely the `Jackson2ObjectMapperBuilder` is used, you may or may not get an XML mapper. Perhaps that's OK and we expect consumers of the builder to always call `createXmlMapper(true|false)` to meet their needs but I'm not sure that the current behaviour is intentional and I think it could be a bit brittle and confusing. https://github.com/spring-projects/spring-boot/issues/17425 is an example of that.

**Comment by philwebb** [comment]
We're going to try making this a prototype bean.
