### ISSUE TITLE
Add idle count (number of idle connections in pool) to DataSourcePoolMetadata and DataSourcePoolMetrics

### ISSUE THREAD

**Issue by tgeens** [spring-projects/spring-boot#17472]
I would like to track the size of the jdbc connection pool. 

Spring Boot already expose a number of metrics (see `DataSourcePoolMetrics`):

* `jdbc.connections.active` - number of active connections
* `jdbc.connections.min` - minimum number of idle connections in the pool
* `jdbc.connections.max` - maximum number of active connections

What am I missing: the number of idle connections in the pool

I'm expecting the number of connections in the pool to be:
min <= active + idle <= max

Adding a new `jdbc.connections.idle` metric would cover this scenario.

Alternatively - and maybe more in line with micrometer philosophy - would be two gauges contributing to `jdbc.connections.count`, 1st with tag `state=idle` and 2nd with tag `state=active`.

This _idle_-count is currently not exposed by the `DataSourcePoolMetadata` abstraction. From a quick look in the javadocs, it seems to be available in most supported DataSources:

* DBCP2 - [getNumIdle](https://commons.apache.org/proper/commons-dbcp/apidocs/org/apache/commons/dbcp2/BasicDataSource.html#getNumIdle--)
* Tomcat - [getNumIdle](https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/tomcat/jdbc/pool/DataSourceProxy.html#getNumIdle--)
* Hikari - [getIdleConnections](https://static.javadoc.io/com.zaxxer/HikariCP/3.3.1/com/zaxxer/hikari/metrics/PoolStats.html#getIdleConnections--)

See https://github.com/spring-projects/spring-boot/issues/12788 for a similar discussion about wait-counts - but that stat was not available on all data sources

**Comment by snicoll** [comment]
We'd like to harmonize with what Hikari does for consistency. It does expose this in flat more with an `idle` metric. This would be a breaking change so we should probably add a default method for `getIdle()` that returns `null`

**Comment by philwebb** [comment]
Closing in favor of PR #17504
