### ISSUE TITLE
Clarify documented behavior of MessageSource auto-configuration when no resource bundles matching the configured basenames exist

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-boot#17485]
From https://github.com/spring-projects/spring-security/issues/7067

If you set only one nonexisting message bundle, the following warning is printed correctly: `spring.messages.basename=messages1`
> ResourceBundle [messages] not found for MessageSource: Can't find bundle for base name messages, locale en 

If you set 2 nonexisting message bundles, the warning is missing:
`spring.messages.basename=messages1, messages2`

**Comment by wilkinsona** [comment]
This is working as designed from a Spring Boot perspective. The warning is produced by a `ResourceBundleMessageSource`. Such a bean is auto-configured by `MessageSourceAutoConfiguration` if a resource bundle that matches one of the configured base names exists. You can see this in the auto-configuration report if you run your application with `--debug`. Here's the output with two base names for which there is no resource bundle:

```
   MessageSourceAutoConfiguration:
      Did not match:
         - ResourceBundle did not find bundle with basename messages,message-commons2 (MessageSourceAutoConfiguration.ResourceBundleCondition)
```

And here's the output when one exists:

```
   MessageSourceAutoConfiguration matched:
      - ResourceBundle found bundle URL [file:/Users/awilkinson/Downloads/resourcebundle-failure/target/classes/message-commons.properties] (MessageSourceAutoConfiguration.ResourceBundleCondition)
      - @ConditionalOnMissingBean (types: org.springframework.context.MessageSource; SearchStrategy: current) did not find any beans (OnBeanCondition)
```

This behaviour is what the documentation is attempting to describe when it says the following:

> The auto-configuration applies when the default properties file for the configured resource bundle is available (i.e. messages.properties by default). If your resource bundle contains only language-specific properties files, you are required to add the default.

Let's see if we can word that differently to make the behaviour more clear.
