### ISSUE TITLE
Whitespace in provider name in the OAuth2 properties causes mismatch

### ISSUE THREAD

**Issue by wpuhl10775** [spring-projects/spring-boot#17487]
### Summary
Whitespace in provider name in the OAuth2 properties causes mismatch for provider ID as it is not able to match the ID to the other proprty parameters

### Actual Behavior

1. Define oauth2 properties in application.properties file

```
spring.security.oauth2.client.registration.xxx.provider=xxx     
spring.security.oauth2.client.provider.xxx.authorization-uri=http://localhost:8282/o/oauth2/v2/auth
```

2. Start Spring Boot
3. Spring Boot throws error: `Caused by: java.lang.IllegalStateException: Unknown provider ID 'xxx  
 '`

### Expected Behavior
Expect 'xxx' provider name to match provider properties

### Configuration
```
spring.security.oauth2.client.registration.fake_oauth.client-id=dummy-client-id
spring.security.oauth2.client.registration.fake_oauth.client-secret=dummy-client-secret
spring.security.oauth2.client.registration.fake_oauth.client-name=fake_oauth
spring.security.oauth2.client.registration.fake_oauth.scope=
spring.security.oauth2.client.registration.fake_oauth.provider=fake_oauth   
spring.security.oauth2.client.registration.fake_oauth.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.fake_oauth.client-authentication-scheme=basic
spring.security.oauth2.client.registration.fake_oauth.redirect-uri-template=http://localhost:8000/oseries-auth/login/oauth2/code/fake_oauth

spring.security.oauth2.client.provider.fake_oauth.authorization-uri=http://localhost:8282/o/oauth2/v2/auth
spring.security.oauth2.client.provider.fake_oauth.token-uri=http://localhost:8282/oauth2/v4/token
spring.security.oauth2.client.provider.fake_oauth.user-info-uri=http://localhost:8282/oauth2/v3/userinfo
spring.security.oauth2.client.provider.fake_oauth.user-info-authentication-method=basic
spring.security.oauth2.client.provider.fake_oauth.user-name-attribute=name
```

### Version

Spring boot 2.1.2.RELEASE
spring-security-oauth2-client-5.1.3.RELEASE

**Comment by philwebb** [comment]
I've transferred the issue

**Comment by philwebb** [comment]
See #4106 for a general discussion on whitespace. The last similar issue to this was #15972 where we trimmed the servlet context path.

**Comment by philwebb** [comment]
I'd probably be in favor of trimming the whitespace for this one in `OAuth2ClientPropertiesRegistrationAdapter`. What are your thoughts @mbhave?

**Comment by mbhave** [comment]
Yup I think we can trim it.

**Comment by mbhave** [comment]
Closing in favor of PR #17497.
