### ISSUE TITLE
Release pipeline is not marking milestones as pre-releases on GitHub

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#17492]
The GitHub release resource is not marking pre-releases as such when publishing the information to GitHub. This is apparently linked to concourse/github-release-resource#40.

As a workaround, we should add `release: false` to our pipeline configuration and update it.
Existing 2.2.0 Milestones have been marked manually as pre-releases, we should make sure that this is done automatically for 2.2.0.M5.

**Comment by snicoll** [comment]
I've also added a dedicated section in our releases checklist so that we double check this part next time.
