### ISSUE TITLE
Provide configuration property for DispatcherServlet.publishEvents 

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#17500]
_Edited for clarity_

It would be useful to have a configuration  property that allows the value of `DispatcherServlet.setPublishEvents` to be changed.

---
Original report

`ServletRequestHandledEvent` will be send when there is an HTTP request. I want to close the `ServletRequestHandledEvent  `through `application. properties`, but it is no effect.

**Comment by wilkinsona** [comment]
@brucelwl Can you please expand a little bit on what you'd like to be able to do? There's no `close()` method on `ServletRequestHandledEvent` so I'm not sure what you mean by wanting to close it. I also can't see the connection with runtime request handling events and `application.properties`.

**Comment by brucelwl** [comment]
please see `org.springframework.web.servlet.FrameworkServlet` line 1137 and `org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration` line 98
I want to be able to control whether or not to post this event. If it is a large number of requests, but many listeners listen to this event that does not need to be processed, it will cause performance problems.

this is my demo code https://github.com/brucelwl/demo

**Comment by karmeYin** [comment]
test
