### ISSUE TITLE
@DataJdbcTest is documented as being transactional but isn't

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-boot#17513]
I'll propose to support the `@Transactional` as meta-annotation at `@DataJdbcTest` as same with `@JdbcTest`. WDYT?

**Comment by philwebb** [comment]
I think we probably should. `@DataJpaTest` also has it.

**Comment by yoshikawaa** [comment]
I think that it is better to support `@Transactional` not only `@DataJdbcTest` but also `@DataRedisTest`,`@DataMongoTest`,`@DataLdapTest`.

**Comment by philwebb** [comment]
@yoshikawaa Have you actually needed to add `@Transactional` yourself for tests that use those other slice annotations? The case is less clear-cut than for `@DataJdbcTest` since they are often used in reactive applications where transaction support is still being worked on.

**Comment by yoshikawaa** [comment]
@philwebb  surely. It may be necessary in the future, but the current need seems to be lower than `@DataJdbcTest`.

**Comment by snicoll** [comment]
Thanks for the feedback @yoshikawaa, we've discussed at the call yesterday and we'd like to stick with `DataJdbcTest` for the time being. We can revisit later.

**Comment by snicoll** [comment]
Interestingly enough, the [current documentation states that `@DataJdbcTest` is transactional](https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-data-jdbc-test). We should probably remove that sentence from the ref guide in `2.1.x`.

**Comment by snicoll** [comment]
Given that this is documented, let's turn that into a bug and fix the behaviour in `2.1.x`
