### ISSUE TITLE
Allow OutputCaptureRule to be used directly with AssertJ

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17512]
If we make `OutputCaptureRule` implement `CapturedOutput` it could be used directly with AssertJ.

**Comment by dreis2211** [comment]
@philwebb I think there is a chance that #17491 would make `OutputCaptureRule` obsolete as it wouldn't be used anymore - apart from its own tests. At least the internal one under `org.springframework.boot.testsupport.system` could be removed. Not sure about the one under `org.springframework.boot.test.system` as I don't know what your JUnit 4 support plans are, but there should be no internal usages of it anymore as well once #17491 is merged.

Thought I better comment on this - maybe it saves you some work. If not, ignore me ;)

**Comment by philwebb** [comment]
Thanks @dreis2211. We're going to continue to support JUnit4 externally for quite a while. The internal version is copy/paste at the moment but it'll be a good idea to delete it eventually.
