### ISSUE TITLE
Quartz may attempt to use the DataSource before migrations have been run

### ISSUE THREAD

**Issue by zhangxb1987** [spring-projects/spring-boot#17528]
I am trying to use flyway handling the quartz schema initialization, but it seems `QuartzAutoConfiguration` is always processed ahead of `FlywayAutoConfiguration`, which will raise the `[org.quartz.JobPersistenceException: Couldn't retrieve job: ORA-00942]` exception, because the quartz schema is not initialized yet（I am using jdbc as the quartz job store type, `spring.quartz.job-store-type=jdbc`）.

So, am i got something wrong , or maybe should put 

```java
@AutoConfigurationAfter(FlywayAutoConfiguration.class) on the QuartzAutoConfiguration ?
```

THX!!

**Comment by zhangxb1987** [comment]
Using spring-boot-2.1.6.RELEASE

**Comment by wilkinsona** [comment]
Closing in favour of #17539.
