### ISSUE TITLE
Broken link to Spring Integration metrics in documentation

### ISSUE THREAD

**Issue by marcos-fernandez** [spring-projects/spring-boot#17543]
Hi, there is a broken link in [Supported Metrics section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-meter).

Spring Integration metrics link goes to [https://docs.spring.io/spring-integration/docs/current/reference/html/system-management-chapter.html#micrometer-integration](https://docs.spring.io/spring-integration/docs/current/reference/html/system-management-chapter.html#micrometer-integration)

The correct one seems to be [https://docs.spring.io/spring-integration/docs/current/reference/html/#micrometer-integration](https://docs.spring.io/spring-integration/docs/current/reference/html/#micrometer-integration)

Thanks

**Comment by snicoll** [comment]
@marcos-fernandez thanks for reporting it!

**Comment by marcos-fernandez** [comment]
Thanks, incredible!!!
