### ISSUE TITLE
NoSuchMethodFailureAnalyzer does not work with Java 13

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17544]
The structure of the message has changed with Java 13 which requires an updated of the algorithm the failure analyzer users to extract the relevant data of the report.

Java 8-12:

```
java.lang.NoSuchMethodError: javax.servlet.ServletContext.addServlet(Ljava/lang/String;Ljavax/servlet/Servlet;)Ljavax/servlet/ServletRegistration$Dynamic;
	at org.springframework.boot.diagnostics.analyzer.NoSuchMethodFailureAnalyzerTests.createFailure(NoSuchMethodFailureAnalyzerTests.java:55)
```

Java 13:

```
java.lang.NoSuchMethodError: javax/servlet/ServletContext.addServlet(Ljava/lang/String;Ljavax/servlet/Servlet;)Ljavax/servlet/ServletRegistration$Dynamic; (loaded from file:/Users/snicoll/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar by org.springframework.boot.testsupport.classpath.ModifiedClassPathClassLoader@86bcf4ad) called from class org.springframework.boot.diagnostics.analyzer.NoSuchMethodFailureAnalyzerTests (loaded from file:/Users/snicoll/workspace/pivotal/spring-boot/spring-boot-project/spring-boot/target/test-classes/ by org.springframework.boot.testsupport.classpath.ModifiedClassPathClassLoader@86bcf4ad).
	at org.springframework.boot.diagnostics.analyzer.NoSuchMethodFailureAnalyzerTests.createFailure(NoSuchMethodFailureAnalyzerTests.java:55)
```

See also #16970

**Comment by snicoll** [comment]
Wondering what to do here. I've managed to clean up things a bit in b6f4beb but the test still fails as it expects a method representation to use dots in its FQN whereas Java 13 uses slashes, i.e.

`javax/servlet/ServletContext.addServlet(Ljava/lang/String;Ljavax/servlet/Servlet;)Ljavax/servlet/ServletRegistration$Dynamic;`

vs. 

`javax.servlet.ServletContext.addServlet(Ljava/lang/String;Ljavax/servlet/Servlet;)Ljavax/servlet/ServletRegistration$Dynamic;`

I guess I could harmonize that back but I'd like to keep that difference in representation as that's what Java 13 mandates. This would make for a potentially weaker assertions.

**Comment by wilkinsona** [comment]
> This would make for a potentially weaker assertions.

Perhaps we could have different assertions for different versions of Java, possibly using JUnit 5's `@EnabledOnJre`?

**Comment by snicoll** [comment]
So the diff above was for OpenJ9. The error message is different again with Java 13 hotspot:

`'javax.servlet.ServletRegistration$Dynamic javax.servlet.ServletContext.addServlet(java.lang.String, javax.servlet.Servlet)'`

There is an extra quote and the return value is swapped.
