### ISSUE TITLE
Duplicate metadata entry for property that is @Deprecated when Lombok runs before spring-boot-configuration-processor

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#17550]
When Lombok is used, fields marked @Deprecated will be generated twice in the spring-configuration-metadata.json file

```
@ConfigurationProperties("my.application")
@Setter
@Getter
public class ApplicationConfig {

    // application name
    private String name;

    // module version
    private String version;

    // architecture layer
    @Deprecated
    private String architecture = "hello";

}
```
```
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
```

As shown in the picture, two descriptions are generated.

![image](https://user-images.githubusercontent.com/13413715/61369150-1753cb00-a8c2-11e9-9e88-8a92d5f7d185.png)

**Comment by snicoll** [comment]
@brucelwl thanks for the report but I find code in text generally not helpful as often something that's not shown is necessary to reproduce the problem. I've copy/pasted your example in a small project and I can't reproduce the problem.

Can you please provide a small sample (github repo or project zip) and instructions to reproduce the problem?

**Comment by brucelwl** [comment]
@snicoll please see my demo https://github.com/brucelwl/demo
You just need to run the main method and look at `spring-configuration-metadata.json` in the target directory

**Comment by snicoll** [comment]
Thanks. I can reproduce and this depends the order in which the APs are invoked on the project. I've swapped the order of `lombok` and `spring-boot-configuration-processor` in the pom and it didn't created the duplicate.

When lombok runs first, I suspect it creates an additional candidate that the AP detects and shouldn't.

**Comment by brucelwl** [comment]
@snicoll When generating spring-configuration-metadata.json, I hope you can add the annotation `@ConfigurationMetadata` to support the same entity class with different prefixes

**Comment by wilkinsona** [comment]
This only appears to happen when the configuration property is `@Deprecated`. When that's the case, metadata is added twice:

1. By `processSimpleTypes` with null deprecation
2. By `processSimpleLombokTypes` with non-null deprecation

**Comment by wilkinsona** [comment]
The metadata is also added twice when the property is not `@Deprecated`, however the two `ItemMetadata` instances are equal so the second addition attempt is ignored. They are not equal in the `@Deprecated` case as the Lombok-generated getter that is found by `processSimpleTypes` is not identified as being `@Deprecated`.
