### ISSUE TITLE
Clarify description of "logging.file.max-history"

### ISSUE THREAD

**Issue by lihongmingming** [spring-projects/spring-boot#17566]
The max-history is the maximum retention days of the log，not number. so i think it will bring ambiguity

**Comment by bclozel** [comment]
The default configuration is rotating files when the size limit is reached and this option is about the maximum number of archive files to keep. The default configuration is not doing daily rollovers.

Even if it did, the official logback documentation is about [the maximum number of files and doesn't mention how rotation is configured](https://logback.qos.ch/manual/appenders.html#tbrpMaxHistory).

Could you explain what lead you to think that there was a mistake in the docs? Maybe you're experiencing a different problem?

**Comment by lihongmingming** [comment]
I tested it in my environment. If I set max-history = 3, the logback will clear all logs of three days ago.
So I think this is the number of days to save the file, but it does not refer to the number of logs.

**Comment by lihongmingming** [comment]
I tested it in my environment. If I set max-history = 3, the logback will clear all logs of three days ago.
So I think this is the number of days to save the file, but it does not refer to the number of logs.

**Comment by bclozel** [comment]
Could you show your logging options? Did you have other logback configuration files?
Did those log files reach the 10Mb limit?

**Comment by lihongmingming** [comment]
I only configure it in my bootstrap.yml,did'nt have any other configuration files.

> logging:
>   file: 
>     max-history: 3
>     max-size: 2KB

**Comment by bclozel** [comment]
I'm wondering if we shouldn't add support for `total-size-cap` Logback property, because currently the total size of archived logs is unbounded. See [example in the Logback docs](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy).

**Comment by prodingerd** [comment]
> I'm wondering if we shouldn't add support for `total-size-cap` Logback property, because currently the total size of archived logs is unbounded. See [example in the Logback docs](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy).

Haven't you done this already? See [this commit](https://github.com/spring-projects/spring-boot/commit/999780f342c5719a3443a184638329c95282e2d9).

**Comment by bclozel** [comment]
Right, thanks @prodingerd
