### ISSUE TITLE
Include HandlerInterceptor beans in WebMvcTest slice

### ISSUE THREAD

**Issue by jhyot** [spring-projects/spring-boot#17572]
The `WebMvcTypeExcludeFilter` (for `@WebMvcTest` test slice) is missing the `org.springframework.web.servlet.HandlerInterceptor` interface from its default includes in my opinion.

Or should components implementing the interface be marked in a different way so that they are included in WebMvcTest slices?

**Comment by snicoll** [comment]
Closing in favour of PR #17600
