### ISSUE TITLE
Move third-party starters to the wiki and add a link from the docs

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17598]
Our current list is somewhat hard to find and it probably doesn't belong in the middle of our source repo.

https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters

**Comment by snicoll** [comment]
I agree the current list is far from ideal. Before we move it though, I'd like we consider https://github.com/spring-io/start.spring.io/issues/185 as well.
