### ISSUE TITLE
@EnableWebMvc breaks the encoding of the response

### ISSUE THREAD

**Issue by anddero** [spring-projects/spring-boot#17605]
I was not sure whether or not this is actually a bug, therefore I wanted to report it here just in case.

Sorry for the cross-post: [https://stackoverflow.com/questions/57152648/enablewebmvc-annotation-changes-response-encoding](https://stackoverflow.com/questions/57152648/enablewebmvc-annotation-changes-response-encoding)

**Comment by wilkinsona** [comment]
Thanks. To avoid duplicated and wasted effort, it's better to keep everything in one place. If it turns out that there's a bug we can re-open this issue.
