### ISSUE TITLE
Allow @ConditionalOn to work on @Components

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#17655]
```
@Service
@ConditionalOnMissingBean(PatientService::class)
class DetachedPatientService(private val emrRepo: EmrRepository) : PatientService {
```

I get this result
```
Parameter 2 of constructor in com.potreromed.gateway.usecase.InitialFoleySetupApplicationService required a bean of type 'com.potreromed.gateway.model.PatientService' that could not be found.
    Action:
    Consider defining a bean of type 'com.potreromed.gateway.model.PatientService' in your configuration.
```
this does work... but it's so much more verbose

```
@Configuration
open class DetachedConfig {

    @Bean
    @ConditionalOnMissingBean
    open fun detachedPatientService(repo: EmrRepository): PatientService {
        return DetachedPatientService(repo)
    }
}
```

it would be nice if we could use `@ConditionalOnMissingBean` and other `@Conditional`'s on `@Component`'s.

P.S. I can create a full demo project if necessary.

**Comment by philwebb** [comment]
@xenoterracide How are your service beans being imported? I believe that Spring Framwork's `@Condition` support should work on components, however, Spring Boot conditions (and `@ConditionalOn...Bean` especially) are very sensitive to when they run. You can really only use them on auto-configuration classes. There's a small warning about this [in the javadoc](https://github.com/spring-projects/spring-boot/blob/ed0f6e66ca3bf72b24c958a2c63504485530cc91/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean.java#L54-L56).

**Comment by xenoterracide** [comment]
imported? I presume you're asking how I'm injecting them... (otherwise just the normal `import`) I'm using constructor injection into other services.

```
@Service
open class InitialFoleySetupApplicationService(
    private val foleyRepo: FoleyRepository,
    private val emrRepo: EmrRepository,
    private val patientSvc: PatientService,
    private val mfcRepo: MonitorFoleyConnectionRepository,
    private val monitorRepo: MonitorRepository,
    private val site: SiteConfig
) {
```

**Comment by snicoll** [comment]
@xenoterracide using conditions on components identified by classpath scanning will not work. You should really use those on auto-configurations (see the note in the javadoc that Phil already linked).

Ignoring the fact using such conditions that way is not supported, I don't know why your project fails the way you've described but it looks like a different problem to me. If you share a small sample we can have a look.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
