### ISSUE TITLE
Generated metadata documentation does not escape the | character

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17657]
See #17636 - We should update the syntax to handle the `|` character in a description. The generated doc is broken currently, see `server.tomcat.relaxed-path-char` for an example.

**Comment by vivganes** [comment]
@snicoll I would like to take this up.  Is there a place where i can see how docs are generated from the javadoc comments?

**Comment by snicoll** [comment]
@vivganes thanks for offering to help. We'd like to fix this before the next milestone is released which should happen in a week or so. If you have time to look at it, the code that generates the appendix is in [spring-boot-configuration-docs](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-configuration-docs).

**Comment by vivganes** [comment]
@snicoll  I am on it :) Will create a pull request soon :)

**Comment by snicoll** [comment]
Closing in favour of PR #17663
