### ISSUE TITLE
SPRING_APPLICATION_JSON is evaluated too late

### ISSUE THREAD

**Issue by stovocor** [spring-projects/spring-boot#17652]
I am trying to override servlet context parameters included in the `web.xml` of a Spring Boot war file. To achieve this, I added the environment variable `SPRING_APPLICATION_JSON` to the `setenv.sh` file of my Tomcat installation.

According to the [documentation](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-external-config.html), the JSON config should be evaluated first. This is not the case, the valued from the `web.xml` are used instead.

While debugging `PropertySourcesPropertyResolver`, I discovered that the list of property resolvers has a different ordering than described in the documentation:

![image](https://user-images.githubusercontent.com/1096199/61947209-edc32f80-afa4-11e9-9569-fe4b112a1cab.png)

Is this a bug or is there any other way to override parameters from `web.xml`?

**Comment by mbhave** [comment]
It does look like there's a discrepancy between the docs and the actual behavior. The property source for `SPRING_APPLICATION_JSON` is [ordered before `jndiProperties`](https://github.com/spring-projects/spring-boot/blob/ed0f6e66ca3bf72b24c958a2c63504485530cc91/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/SpringApplicationJsonEnvironmentPostProcessor.java#L146) but it doesn't seem to be doing anything about ordering it with respect to `servletConfigInitParams` and `servletContextInitParams`. 

Let's see what the team thinks about what the correct behavior should be.
