### ISSUE TITLE
Spring Data JDBC now requires a PlatformTransactionManager

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17654]
The build is currently broken and It looks like Spring Data JDBC now requires a `PlatformTransactionManager`. We should review our auto-configuration and adapt so that it takes appropriate decisions.

**Comment by mbhave** [comment]
@snicoll I have a fix for the tests [here](https://github.com/mbhave/spring-boot/commit/53b464461ad7717a1e0121004f3303f17965707f). I'll hold off on pushing it since it looks like there might be more to it going by your previous comment.

**Comment by snicoll** [comment]
Thanks Madhura, I've pushed your fix to restore the build. Given how repositories scanning is failing, I think the auto-configuration should make sure a `PlatformTransactionManager` is present. I am wondering if we do such checks for other repositories.
