### ISSUE TITLE
Possible bug in start.spring.io (missing aop/aspectj)

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#17658]
Hello SB Team

In https://start.spring.io/ when I write either `aop` or `aspectj` terms in the `Search dependencies to add` text field does not appear nothing about aop. It used to appear previously.

In `Spring Boot Reference Guide` appears the `spring-boot-starter-aop` value in the `Table 13.1`. It in the [13.5 Starters](https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/html/using-boot-build-systems.html#using-boot-starter) section

Not sure if it is a bug or not.

Thanks

-Manuel

**Comment by snicoll** [comment]
Hello. When you are on start.spring.io, there is a Github icon on the top right of the screen that redirects to the appropriate Github project.

Duplicates https://github.com/spring-io/start.spring.io/issues/180
