### ISSUE TITLE
Expose embedded database connection coordinates from TestDatabaseAutoConfiguration

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-boot#17651]
The use case is to use the same embedded test database through JDBC and R2DBC.

`TestDatabaseAutoConfiguration` configures an embedded database connection for testing. Trying to connect to the same database with e.g. R2DBC H2 isn't possible as connection coordinates are not exposed.

Extensions (`@R2dbcTest`) that set up a R2DBC connector end up with a separate database instance.

In contrast, connecting to a regular embedded database is possible as `DataSourceProperties` expose the database name that remains the same throughout the application session.

**Comment by mbhave** [comment]
@mp911de I'm not sure I totally followed the use-case. Do you have a small sample that could clarify what you'd like to happen?

**Comment by mp911de** [comment]
What I want to achieve is:

```java
@RunWith(SpringRunner.class)
@R2dbcTest
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class DataR2dbcTestIntegrationTests {

	@Autowired
	DataSource dataSource;

	@Autowired
	private ConnectionFactory connectionFactory;

	@Test
	public void test() {

		JdbcTemplate template = new JdbcTemplate(dataSource);
		template.execute("INSERT INTO person (firstname, lastname) VALUES('Walter', 'White')");

		DatabaseClient databaseClient = DatabaseClient.create(connectionFactory);
		databaseClient.execute("SELECT * FROM person")
				.fetch()
				.all()
				.as(StepVerifier::create)
				.consumeNextWith(rowAsMap -> assertThat(rowAsMap)
						.containsEntry("firstname", "Walter"))
				.verifyComplete();
	}
}
```

The embedded database gets configured by [`EmbeddedDataSourceFactoryBean`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/jdbc/TestDatabaseAutoConfiguration.java#L131) exposing a `DataSource`. There's no possibility to inspect the `DataSource` to get information how it was configured.

Ideally, we get [metadata](https://github.com/spring-projects-experimental/spring-boot-r2dbc/blob/c2893f4020dcaa015141cea214f16f315bc230d4/spring-boot-autoconfigure-r2dbc/src/main/java/org/springframework/boot/autoconfigure/r2dbc/EmbeddedDatabaseConfiguration.java#L120) containing details how to configure an embedded database connection for R2DBC H2.

**Comment by philwebb** [comment]
I might be missing something, but I'm not sure that we have a `name` , `username` and `password` for the embedded cases.

Taking a step back. Is trying to reuse `AutoConfigureTestDatabase` for R2DBC a good idea? The `EmbeddedDatabaseConnection` class is in the `jdbc` package and it's very much tied to those APIs. Might we be better off instead trying to offer a first-class R2DBC alternative?

**Comment by mp911de** [comment]
> The EmbeddedDatabaseConnection class is in the jdbc package

This is a very good point. For R2DBC, we currently support H2 as an embedded database (others may follow). HSQL and Derby are both JDBC-bound and it doesn't look like we get a non-JDBC in-memory database. 

It makes sense to bootstrap a dedicated R2DBC instance. With the tight JDBC integration, we face the question of how to transition from R2DBC into the JDBC world. This is, because setup use-cases (`schema.sql`, `data.sql`, Flyway/Liquibase bootstrapping, fixtures using `JdbcTemplate`/JDBC Repositories/JPA Repositories) are easier to achieve using an imperative API while the actual test remains reactive.

**Comment by philwebb** [comment]
@mp911de We discussed this today as a team and the general feeling is that we don't want to expose the connection details as a bean. We think some more time is needed to consider how R2DBC and JDBC should interact with each other. It feels like a `DataSource` -> `RDBC` adapter might be a good long term solution. I've no idea if it's technically possible or how much work it might be, but it would be very nice to only have a single thing responsible for the actual database network traffic.
