### ISSUE TITLE
Document that @ConfigurationProperties Doesn't Evaluate SpEL

### ISSUE THREAD

**Issue by wtatum** [spring-projects/spring-boot#1768]
It seems that `@ConfigurationProperties` doesn't evaluate Spring Expression Language, but `@Value` does. That means in cases where configuration may contain expressions, `@Value` can't transparently be replaced with `@ConfigurationProperties`. This was a bit of a surprise and took me a while to diagnose. For example:

application.properties:

```properties
test.expression=#{1+1}
```

TestValue.java:

```java
@Component
public class TestValue {
	private @Value("${test.expression}") String expression;
	
	@PostConstruct
	public void print() {
		System.out.println("Test Value: " + expression);
	}
}
```

TestConfigurationProperties.java

```java
@Component
@ConfigurationProperties("test")
@Getter @Setter
public class TestConfigurationProperties {
	private String expression;
	
	@PostConstruct
	public void print() {
		System.out.println("Test ConfigurationProperties: " + expression);
	}
}
```

prints:
> Test ConfigurationProperties: #{1+1}
> Test Value: 2

It seems like it would be reasonably straightforward to perform this evaluation, or to add an argument to `@ConfigurationProperties`. Any thoughts?

**Comment by bstick12** [comment]
We have just been hit by this issue as well. In one instance we want to retrieve the hostname as part of the property - #{T(java.net.InetAddress).getLocalHost().getHostName()}

I agree with your assessment of the possible security risk but having the behavior being different to @Value is a little strange.

Could it be enabled via an argument on the ConfiguirationProperties?

**Comment by philwebb** [comment]
I agree with @dsyer, I'm not keen to enable SpEL inside properties, I think it's best to keep code in the application itself if possible.

**Comment by bstick12** [comment]
@philwebb That's no problem I can see where you are coming from on the security.  

Maybe just a note in the JavaDoc detailing that @Value type SpEL isn't supported.
