### ISSUE TITLE
Expose WebClient Connection Provider Metrics

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#17694]
When configuring a web client you can provide an instance of `reactor.netty.resources.ConnectionProvider`. This class manages the connections used within the web client. There are several versions available including pooled connections and creating new connection each time. 

It would be useful to expose metrics describing the state (active, inactive) of each connection within the pool.

It would also be useful to expose a gauge of the pending requests.

Possible metrics name could be:

_web_client_connections_

with tags:

 - state (active/inactive/pending)

Feedback welcome

**Comment by philwebb** [comment]
@michaelmcfadyen I've edited your comment to make it clear that you're talking about `reactor.netty.resources.ConnectionProvider`. I hope that's correct.

I think this would be worth raising with the reactor netty team first. I think they already have Micrometer integration for a few classes.

Unfortunately I can't transfer the issue but their tracker is [here](https://github.com/reactor/reactor-netty/issues).

**Comment by michaelmcfadyen** [comment]
Yeah, that is the class I was referring to. I'll raise this with reactor netty then. Thanks for the response.

**Comment by michaelmcfadyen** [comment]
for reference, client metrics will be released as part of reactor netty 0.9.0 (including connection pool metrics).
This is the specific issue for connection pool metrics: https://github.com/reactor/reactor-netty/issues/797
