### ISSUE TITLE
SpringBoot starts slowly

### ISSUE THREAD

**Issue by developers-youcong** [spring-projects/spring-boot#17696]
![image](https://user-images.githubusercontent.com/45055576/62095097-eb691a00-b2b1-11e9-8c32-bde782157162.png)
The SpringBoot version is 1.5.9

Problem description:
Start SpringBoot and it stays stuck. This has never been the case before, but yesterday the problem popped up.

This is my startup class code:
==============================================================
@EnableTransactionManagement
@SpringBootApplication
public class Application {

    protected final static Logger logger = LoggerFactory.getLogger(Application.class);

    public static void main(String[] args) {
    	
        SpringApplication app = new SpringApplication(Application.class);
        app.setBannerMode(Banner.Mode.OFF);
        app.run(args);
        logger.info("Application is success!");
    }
}
==============================================================

**Comment by developers-youcong** [comment]
![image](https://user-images.githubusercontent.com/45055576/62095517-3f283300-b2b3-11e9-8ad4-8fd88a7a7a0b.png)
Several recent SpringBoot projects have experienced this slow start

**Comment by mbhave** [comment]
@developers-youcong It's hard to tell what's happening based off a few screenshots. Also, there have been many releases after 1.5.9. 1.5.21 is the latest release in the 1.5.x line with 1.5.22 scheduled for later this week. However, as the 1.5.x line will reach EOL this August, please try upgrading to Spring Boot 2.1 to see if the problem still persists.

If it does, a minimal sample that we can run to reproduce the issue would be helpful.

**Comment by developers-youcong** [comment]
Thank you

**Comment by developers-youcong** [comment]
@mbhave Thank you

**Comment by developers-youcong** [comment]
To my surprise, I have four SpringBoot projects, all 1.5.9. There are two that work, and the other two are the ones in the screenshot, which work very slowly. Also, a SpringBoot project started slowly yesterday because I added a lot of static resources, and when I removed the static resources, it loaded faster.
By checking online, it seems that SpringBoot starts slowly due to the database. As shown in figure:
![image](https://user-images.githubusercontent.com/45055576/62096755-5832e300-b2b7-11e9-9d0f-2dd25e43cbcb.png)

**Comment by philwebb** [comment]
>  it seems that SpringBoot starts slowly due to the database

That sounds like an issue with your local environment. I'm going to close this one for now. We can re-open if you manage to replicate the problem in a isolated sample that we can run locally.

**Comment by developers-youcong** [comment]
The root cause has been identified, it has to do with bandwidth, bandwidth constraints
