### ISSUE TITLE
Leftover additional configuration metadata in actuator

### ISSUE THREAD

**Issue by AlexFalappa** [spring-projects/spring-boot#17704]
In `spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json` [at this line](https://github.com/spring-projects/spring-boot/blob/6e5ad13c0dd48ef630f0a0e1822fc2e8a64aab8a/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L27) I noticed the following property definition:
```
    {
      "name": "management.endpoint.health.show-details",
      "defaultValue": "never"
    },
```
that should be useless as overridden by the more complete definition generated by the configuration processor in the `spring-configuration-metadata.json` file:
```
    {
      "name": "management.endpoint.health.show-details",
      "type": "org.springframework.boot.actuate.health.ShowDetails",
      "description": "When to show full health details.",
      "sourceType": "org.springframework.boot.actuate.autoconfigure.health.HealthEndpointProperties",
      "defaultValue": "never"
    },
```

I think the former can be safely deleted.

**Comment by snicoll** [comment]
Thanks for the report @AlexFalappa. This entry is there on purpose as the annotation processor cannot extract default value for `Enum`. The purpose of the additional metadata is to complement the one generated automatically. 

If I've misunderstood please let me know and we can reopen.

**Comment by AlexFalappa** [comment]
@snicoll thanks for the explanation.

I also verified it on a personal project. Apologies for the "noise".
