### ISSUE TITLE
Add official Gitter chat room to communicate

### ISSUE THREAD

**Issue by aliaksei-lithium** [spring-projects/spring-boot#1771]
[Gitter](https://gitter.im) is a great tool to communicate based on github repos. So you can create an official chat based on this repo.

**Comment by dlehammer** [comment]
Hi Spring Gurus,

I'm unfortunately unable to join the "spring-boot" room, as reached when following https://gitter.im/spring-projects/spring-boot referenced under https://github.com/spring-projects/spring-boot#getting-help

![Image](https://github.com/user-attachments/assets/f59c81a0-12a5-4264-9b20-b47b2d83d596)

```
Failed to join

MatrixError: [403] You are not invited to this room. (https://gitter.ems.host/_matrix/client/v3/join/%23spring-projects_spring-boot%3Agitter.im)
```

Seems I need some form of invite, and "Getting Help" doesn't outline how an invitation is obtained 😕 

Hope you're able to clear a path going forward 🙏

**Comment by wilkinsona** [comment]
It works for me and there should be no need for an invitation. If you're having problems, you'll have to raise them with Gitter support.

**Comment by wilkinsona** [comment]
@bclozel has reminded me that the channel is now invite-only. This was done due to a huge spam problem on Gitter and the team not having time to deal with it. We'll update the getting help page to remove the Gitter references as we no longer recommend using it.

**Comment by GabSouza98** [comment]
@bclozel Is there a way to request an invite?

**Comment by bclozel** [comment]
@GabSouza98 the channel is now closed.

**Comment by nillpoe** [comment]
<img width="1389" height="1212" alt="Image" src="https://github.com/user-attachments/assets/73b17761-fa77-4ccd-bc36-1d78ca4599e9" />

@bclozel please remove this one too!
https://spring.io/community

**Comment by bclozel** [comment]
@nillpoe thanks for letting us know, I have sent this report to the website team.
