### ISSUE TITLE
Perform classpath scanning at build-time in the gradle and maven plugins

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#17739]
I propose to add a classpath scanning feature to the Spring Boot Maven and Gradle plugins.

This could be used to generate the `META-INF/spring.components` file, which would improve the startup performance.

Performing the classpath scan in Maven/Gradle (instead of using `org.springframework:spring-context-indexer`) has the benefit that the whole runtime classpath can be scanned at once.

An already working example of this can be found here:
- https://github.com/joinfaces/joinfaces/blob/4.1.0-m3/joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/ClasspathScanPlugin.java
- https://github.com/joinfaces/joinfaces/blob/4.1.0-m3/joinfaces-tools/joinfaces-maven-plugin/src/main/java/org/joinfaces/maven/ClasspathScanMojo.java
- https://github.com/joinfaces/joinfaces/tree/4.1.0-m3/joinfaces-tools/joinfaces-scan-tools/src/main/java/org/joinfaces/tools

If you like, I can provide a PR which moves this from our third-party spring boot starter into Spring Boot itself.

See also #14356

**Comment by philwebb** [comment]
Thanks for the suggestion but we don't feel that adding an index for the full classpath is currently a good idea. For typical Spring Boot application component scanning doesn't add a great deal of time and is usually limited to just user written packages. It's very unusual to need to perform a full scan of every jar.

We also don't want to make the assumption that the classpath that's available at compile time is necessarily the one that's going to be used at runtime.

@larsgrefer Have you seen noticeable performance improvements doing this in JoinFaces?

**Comment by larsgrefer** [comment]
> We also don't want to make the assumption that the classpath that's available at compile time is necessarily the one that's going to be used at runtime.

At JoinFaces we expect that the actual runtime classpath is correctly modeled using the appropriate maven scopes or Gradle configurations. (For Gradle - for example - we scan the `runtimeClasspath` configuration, which also includes `runtime` and `runtimeOnly` dependencies). In cases where the runtime classpath cannot be modeled correctly, its still possible to just disable the build-time scan.

> Have you seen noticeable performance improvements doing this in JoinFaces?

I don't have numbers for the `spring.components` index in particular.
At JoinFaces we have to perform additional full classpath scans (not limited to a base package) in order to execute `ServletContainerInitializer`s (see Section 8.2.4 of the Servlet Spec). For these scans, we saved >2 seconds at the application startup.
