### ISSUE TITLE
Document how to import and run a smoke tests in the IDE

### ISSUE THREAD

**Issue by jamesward** [spring-projects/spring-boot#17757]
Seems like there should be a way to run an individual smoke test but I can't find it.  Would be great to have this info in the `CONTRIBUTING.adoc` file.

**Comment by snicoll** [comment]
@jamesward I am not sure I got that. Do you mean a smoke test module (and all the tests within it) or one particular test class or one particular test within a class?

**Comment by jamesward** [comment]
I'm trying to just run `spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-static` and it appears that I can go into that dir and run `../../../mvnw test` but I'm not totally certain if that is right.

**Comment by jamesward** [comment]
I'm also trying to figure out how to run the smoke test from my IDE so I can do some debugging.

**Comment by snicoll** [comment]
Thanks for the feedback. The smoke test is quite specific as it's invoked in a particular way which means that those modules are not part of the reactor. 

If you don't have maven installed or want to rely on the wrapper, that command works yes. Here is [more details](https://github.com/takari/maven-wrapper/issues/30) about how to use it with sub-modules.

If you want to import a smoke test in IntelliJ IDEA, you can right click on the pom of the project you're interested in (i.e. `spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-static/pom.xml`) and invoke "Add as a Maven project". I can only assume other IDEs have a similar feature.

We can improve the current contributing page but I am not sure about what you're asking as it falls more in the documentation of the maven wrapper or the IDE you are using. Flagging for team attention to see what the rest of the team thinks.

**Comment by jamesward** [comment]
Thanks for the quick response.  What I was hoping I could do is to run a smoke test like I run a project's unit tests.  That would enable me to pick a specific one to run, make change to the underlying stuff to retest, and debug into the underlying stuff via an IDE if needed.

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

You can use `./gradlew spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-{whatever}`. Running an individual test or debugging can be done using Gradle's standard mechanisms.
