### ISSUE TITLE
@TestPropertySource does not get reflected in application context

### ISSUE THREAD

**Issue by peterjurkovic** [spring-projects/spring-boot#17760]
If the following test is run as a standalone then it passes. But If it run within all tests it doesn't. It is because `@TestPropertySource(properties = "logging.pattern.console=%X{traceId}")` doesn't get refreshed and is used different pattern set by a different test. Also annotating it by  `@DirtiesContext` didn't help. Maybe this is issue for the Spring Framework core team and `@DirtiesContext` should actually does it. 

```java

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestPropertySource(properties = "logging.pattern.console=%X{traceId}")
@DirtiesContext(classMode = ClassMode.BEFORE_CLASS)
@RunWith(SpringRunner.class)
public class LogHelperTest {

    private final Logger log = LoggerFactory.getLogger(getClass());

    @Rule
    public final SystemOutRule systemOutRule = new SystemOutRule().enableLog();

    @Test
    public void testLogOnNext(){
        Mono.just("HI")
            .doOnEach(LogHelper.onNext(hi -> log.info("")))
            .subscriberContext( ctx -> ctx.put("traceId", "traceIdValue"))
            .subscribe();

        String output = systemOutRule.getLog();

        assertThat(output).isEqualTo("traceIdValue");
    }
}
```

Failing test result
```
expected:<"[traceIdValue]"> but was:<"[2019-08-01 23:32:54.816  INFO 2369 --- [    Test worker] c.n.s.webflux.tracing.LogHelperTest      
```

**Comment by snicoll** [comment]
> But If it run within all tests it doesn't. It is because @TestPropertySource(properties = "logging.pattern.console=%X{traceId}") doesn't get refreshed and is used different pattern set by a different test. 

@peterjurkovic that's not what the bootstrap context is supposed to do. `TestPropertySource` (be it a properties or a location)  is part of the key and should create a separate `ApplicationContext` which will bootstrap a separate `LoggingSystem`.

Code in text isn't usually helpful I am afraid. Can you please share a minimal sample (zip or github repo) we can use to run the tests suite ourselves?

**Comment by peterjurkovic** [comment]
@snicoll Here is a sample project where you can reproduce it: [propertiestest.zip](http://upload.peterjurkovic.com/uploaded_files/propertiestest.zip)

run `./gradlew test`  (if it pusses run it multiple times)
Then run `com.example.propertiestest.test.PropertiestestApplicationTests` individually, it passes.

Let me know if you need any future information.

**Comment by snicoll** [comment]
@peterjurkovic thanks for the sample. The error has nothing to do with a lack of refresh as I was suspecting. There is an optimization in `LoggingSystem` so that it is configured only once for the duration of the test suite.

Changing the logging system in flight seems rather specific, flagging for team attention to see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
I don't think this is something that we should support. Assertions that validate logging output should, IMO, by a last resort. As such, adding complexity to the `LoggingSystem` or test context bootstrapping in support of search assertions should be avoided, and an alternative mechanism for verifying the code's behaviour sought instead.

**Comment by snicoll** [comment]
Sorry for the lack of follow-up here. We've discussed this and agreed this isn't something we want to support, see the comment above for more details.
