### ISSUE TITLE
Wrong bean name on Reactive Cassandra Health Indicator condition

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#17763]
The condition on which the reactive cassandra health indicator is created does not look correct. The bean that is being created has the name "cassandraHealthIndicator" however the conditional is on a missing bean with name "cassandraReactiveHealthIndicator".

	@Bean
	@ConditionalOnMissingBean(name = "cassandraReactiveHealthIndicator")
	public ReactiveHealthIndicator cassandraHealthIndicator(
			Map<String, ReactiveCassandraOperations> reactiveCassandraOperations) {
		return createHealthIndicator(reactiveCassandraOperations);
	}

Shouldn't the conditional bean name be the  same as the name of the bean we are creating?

**Comment by snicoll** [comment]
Oops, good catch @michaelmcfadyen. Thank you for reporting it.
