### ISSUE TITLE
registerAsParallelCapable is not compatible with Graal native image

### ISSUE THREAD

**Issue by mwiacek** [spring-projects/spring-boot#17771]
Bug report
Spring Boot 2.1.6

Spring uses `ClassLoader.registerAsParallelCapable` in some classes. That call is not compatible with Graal native image runtime. It would be good to detect Graal runtime and make the call to `registerAsParallelCapable` conditional.

**Comment by philwebb** [comment]
Thanks for raising the issue. Graal support is something we're investigating but we won't be able to support it fully until Spring Boot 2.3.
