### ISSUE TITLE
Include logger group with configuredLevel in LoggersEndpoint documentation

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#17772]

**Comment by wilkinsona** [comment]
If I've understood the issue title correctly, this is Jackson's standard behaviour (it omits fields with `null` values) and is why the description of the `configuredLevel` field ends with "if any". Perhaps what that means isn't clear? "If any" is used consistently (I think) across all of the Actuator API docs so if we decide it's unclear we should change it across the board.

**Comment by wilkinsona** [comment]
While wondering about this one, I noticed that the response structure for retrieving a single group wasn't documented. I've addressed that in https://github.com/spring-projects/spring-boot/issues/17909. A side-effect of that is that the example response now includes a `configuredLevel` as it's no longer `null`.

**Comment by mbhave** [comment]
Discussed this with @wilkinsona and we concluded that having no `configuredLevel` seems to be more idiomatic JSON than a `configuredLevel` of `null`. We've used this issue to update the tests to include a logger group with an explicitly configured level so that there's a mixture of groups with and without `configuredLevel` in the docs.
