### ISSUE TITLE
Switch implementation of thymeleaf-layout-dialect

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#17770]
See also #7557.
The artifact `nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect` depends on Groovy, which is quite large and triggers many JDK9 module warnings.

There is a fork that uses pure Java instead, which may be better to use by default.
GitHub: https://github.com/zhanhb/thymeleaf-layout-dialect
Maven: `com.github.zhanhb:thymeleaf-layout-dialect`

**Comment by philwebb** [comment]
Thanks @OrangeDog, we'll look into this.

**Comment by bclozel** [comment]
The team discussed this issue and we've agreed that:

* given Thymeleaf's 3.x native layout support, we wouldn't add such dialect support if we were to start over today
* even if the dependency management and auto-configuration are light, we might consider dropping support in the future for the layout dialect. We're just waiting for more signs from the community to decide on that

So we're not in favor of adding another variant of a layout dialect.

**Comment by OrangeDog** [comment]
Fair enough.

It should be noted that Thymeleaf 3 still doesn't support hierarchical templates (e.g. like Jinja and Django) natively. The [official documentation](https://www.thymeleaf.org/doc/articles/layouts.html) specifically says to use the Layout Dialect.
