### ISSUE TITLE
Contradictory bean state

### ISSUE THREAD

**Issue by theHilikus** [spring-projects/spring-boot#17784]
In the task of trying to create a conditional bean that is active when `@EnableWebMvc` is present and inactive when it is not present, I am getting this seemingly contradictory report. I am not 100% sure that it's an actual bug but I thought it would be a good idea to report it in case it is
This state happens when `@EnableWebMvc` _is_ present

```
ProblemModulesRegisterer matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport; SearchStrategy: all) did not find any beans (OnBeanCondition)

WebMvcAutoConfiguration:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport; SearchStrategy: all) found beans of type 'org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport' org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration (OnBeanCondition)
```
So the exact same condition `@ConditionalOnMissingBean(WebMvcConfigurationSupport.class)` is matching in `ProblemModulesRegisterer` and not matching in `WebMvcAutoConfiguration` at the same time. Am I missing something or is this a bug? I also tried with `@DependsOn` in case it was a matter or ordering but I got the same result.

These are my two configuration classes
```
@Configuration
@ConditionalOnMissingBean(WebMvcConfigurationSupport.class)
public class ProblemModulesRegisterer implements WebMvcConfigurer  {
...
}

@Configuration
@EnableWebMvc
public class MyConfig implements WebMvcConfigurer {
}
```

**Comment by snicoll** [comment]
@theHilikus I am not really sure what you are reporting really. Conditions are matched at a given time and based on the state of the `ApplicationContext` (please review [the javadoc](https://github.com/spring-projects/spring-boot/blob/cd4da0320419d6d4facef868c919c1d2f75d9cb4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean.java#L52-L56)).

My best guess is that there wasn't a `WebMvcConfigurationSupport` when `ProblemModulesRegisterer` was handled but there was one when `WebMvcAutoConfiguration` was handled. This makes total sense if something has contributed such bean in between. 

If I misunderstood and you think this is a problem in Spring Boot, please share a small sample that we can run ourselves (not code in text but a sample on github or a zip we can run ourselves).

**Comment by theHilikus** [comment]
Thank you for your reply @snicoll 
My first thought was exactly what you said, a matter of the bean not being there in the first conditional and being there for the second one. I thought a `@DependsOn` would rule that out but maybe i'm misunderstanding something

Here is the sample project. The strange bean is ProblemModulesRegisterer. I know that my logic is inverted and the conditional should be a positive conditional and not a negative one, but for the purpose of highlighting the bug, I inverted it to show more clearly that the exact same condition was evaluating differently in two different beans
[dummy-project.zip](https://github.com/spring-projects/spring-boot/files/3468307/dummy-project.zip)

**Comment by mbhave** [comment]
Thanks for the sample @theHilikus. `@ConditionalOnMissingBean` is meant to be used for auto-configuration classes and not regular `@Configuration` classes. See [this comment](https://github.com/spring-projects/spring-boot/issues/17303#issuecomment-505287078).

**Comment by theHilikus** [comment]
@mbhave ok. i didn't know that. thank you for the info. Is there an alternative that you can propose then to have a bean to conditionally configure spring mvc based on weather `@EnableWebMvc` is present or not?

**Comment by snicoll** [comment]
@theHilikus this was the section of the Javadoc that I already shared in my previous comment. Regardless. If you have more questions, please ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by theHilikus** [comment]
will do. thank you
