### ISSUE TITLE
Issue with Spring Boot / OpenJDK / Docker Windows Containers

### ISSUE THREAD

**Issue by TurtleBeach** [spring-projects/spring-boot#17781]
I am seeing the following exception when I attempt to run a Spring-boot application in a Docker Windows nanoserver container (started with Verbose option):

> [Loaded java.text.Format$FieldDelegate from c:\JDK_1.8-Zulu-222\jre\lib\rt.jar]
> [Loaded java.text.DontCareFieldPosition$1 from c:\JDK_1.8-Zulu-222\jre\lib\rt.jar]
> [Loaded java.text.NumberFormat$Field from c:\JDK_1.8-Zulu-222\jre\lib\rt.jar]
> [Loaded ch.qos.logback.core.pattern.SpacePadder from jar:file:/C:/portal/server-0.0.4-SNAPSHOT.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/]
> 2019-08-03 18:12:57.232 ERROR ??? --- [           main] o.s.boot.SpringApplication               : Application run failed
> **java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress**
>         at org.springframework.boot.StartupInfoLogger.lambda$getOn$1(StartupInfoLogger.java:108) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.StartupInfoLogger.getValue(StartupInfoLogger.java:138) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.StartupInfoLogger.getValue(StartupInfoLogger.java:133) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.StartupInfoLogger.getOn(StartupInfoLogger.java:108) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.StartupInfoLogger.getStartupMessage(StartupInfoLogger.java:68) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:50) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.SpringApplication.logStartupInfo(SpringApplication.java:632) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:368) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
>         at ai.com.neuralstudio.portal.server.ServerApplication.main(ServerApplication.java:117) [classes!/:0.0.4-SNAPSHOT]
>         **at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]**
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [server-0.0.4-SNAPSHOT.jar:0.0.4-SNAPSHOT]

A simple stand-alone Jar that is executed before the Spring Boot app starts runs fine. The Spring Boot app runs fine stand-alone on Windows 10 Pro (1903) and in NetBeans on same W10Pro.

The path in Container is:

> Path=C:\Windows\system32;C:\Windows;c:\JDK_1.8-Zulu-222\jre\bin;c:\JDK_1.8-Zulu-222\jre\lib;c:\JDK_1.8-Zulu-222\jre\lib\ext;
I have added two Microsoft restributable DLLs to System32 that are not currently in nanoserver:

> msvcr100.dll and msvcp140.dll

,
but that did not help.
The Spring Boot application will run with Oracle 1.8.0_181 in container.
Admittedly I am not sure this is a Spring Boot problem (I have also raised it at Azul Systems) but any insights would be appreciated.
Thanks

**Comment by snicoll** [comment]
Sorry but an `Error` such as `NoClassDefFoundError`  refers to a runtime environment and nothing we can do about it. I'd suggest raise that on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
