### ISSUE TITLE
Upgrade to Mockito 3.0.0

### ISSUE THREAD

**Issue by MartinX3** [spring-projects/spring-boot#17803]
"Mockito 3.0.0 is equivalent to Mockito 2, but now requires Java 8. No API changes were made."
https://github.com/mockito/mockito/releases/tag/v3.0.0
https://github.com/mockito/mockito/releases/tag/v3.0.4

**Comment by wilkinsona** [comment]
3.0.4 isn't on Central. Let's go with 3.0.0.
