### ISSUE TITLE
Extend RabbitProperties to include simplePublisherConfirms

### ISSUE THREAD

**Issue by pcoates33** [spring-projects/spring-boot#17828]
Add new property to allow `simplePublisherConfirms` to be set on the default `connectionFactory`.

```
spring.rabbitmq.simple-publisher-confirms=false # Whether to enable simple publisher confirms.
```

We already have properties for

```
spring.rabbitmq.publisher-confirms=false # Whether to enable publisher confirms.
spring.rabbitmq.publisher-returns=false # Whether to enable publisher returns.
```

https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by philwebb** [comment]
See #3945

**Comment by snicoll** [comment]
Closing in favour of PR #17848
