### ISSUE TITLE
Expose dependency management plugin version in dependency management

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17842]
Spring Initializr is trying to read the version of the plugin from dependency management so that we don't have to maintain which version works with which version of Spring Boot.

Unfortunately, this information is not available in `spring-boot-dependencies` at the moment so we can't read it as other poms are processed by the flatten maven plugin.

It would be nice if we had a way to expose that information.

See https://github.com/spring-io/initializr/issues/977

**Comment by wilkinsona** [comment]
I think we should move the entry from `spring-boot-parent` to `spring-boot-dependencies`. We [already document](https://docs.spring.io/spring-boot/docs/2.1.x/gradle-plugin/reference/html/#managing-dependencies-using-in-isolation) the use of the plugin's version for certain Kotlin DSL scenarios so making it more public by including it in `spring-boot-dependencies` and, therefore, in the reference documentation appendix that lists all of the managed versions makes sense to me.
