### ISSUE TITLE
Add Support For MongoDb JobStore

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-boot#17849]
Currently We have only suport for only two Job Store InMemory and JDBC. But their are projects
which provide Mongo and Redis Job Store For Quartz. We can bring those projects configuration
under Spring Boot Starter Quartz and provide more job store for Quartz.
https://github.com/michaelklishin/quartz-mongodb
https://github.com/spring-projects/spring-boot/issues/10924

**Comment by snicoll** [comment]
Thanks for the suggestion. Have you tried to use it with Spring Boot and is there a problem of configuring it with `spring.quartz.properties.*`.

**Comment by ankurpathak** [comment]
Yes it working with spring.quartz.properties.*. But it will use it own Connection Pool for Mongo.
The whole point of bringing in buld integration is to use Spring Thread Pool and Spring Data MongoDB
Mongo Resources like Connection Pool.

**Comment by bclozel** [comment]
Looking at the quartz-mongodb project, it seems it's not being actively maintained and [is stuck on a required update](https://github.com/michaelklishin/quartz-mongodb/issues/157). With that in mind, we don't want to add support to a library that might prevent us from upgrading to newer quartz versions.

I'm closing this issue for now, feel free to reopen if the project's situation changes.
Thanks,

**Comment by ankurpathak** [comment]
I have raised a issue for this with owner of project. Lets wait for his response for same.
