### ISSUE TITLE
Update Opaque Token Client Name Updated

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-boot#17846]
Related to #15872

`OAuth2TokenIntrospectionClient` has been updated to `OpaqueTokenInterceptor` and the associated implementation `NimbusOAuth2TokenIntrospectionClient` was updated to `NimbusOpaqueTokenInterceptor`.

This will require an update in Spring Boot since it instantiates a `NimbusOAuth2TokenIntrospectionClient`, given the appropriate parameters.

**Comment by mbhave** [comment]
@jzheaux Guessing `OpaqueTokenInterceptor` was a typo and it's actually `OpaqueTokenIntrospector`?
