### ISSUE TITLE
Clarify that build plugins or the CLI does not have an auto-compile feature

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17851]
Let's review the documentation across the board to make it crystal clear that Spring Boot doesn't have an auto-compile feature. 

This can be tricky for newcomers. For instance, [Section 6.2](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/gradle-plugin/reference/html/#running-your-application-reloading-resources) talks about "resources" but doesn't explicitly defines what that means.

**Comment by mbhave** [comment]
@snicoll Can you provide more details on this one please?

**Comment by snicoll** [comment]
Certainly. It's about making sure users don't imply that devtools doesn't recompile your code on the fly (or that `spring-boot:run`) does. With all the notes and warnings we have in our doc, some users are still confused to not see their app restarting when they make a change in the source code.
