### ISSUE TITLE
Add support for SocketAcceptorInterceptor

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#17869]
It would be nice if support was added for `SocketAcceptorInterceptor` to `ServerRSocketFactoryCustomizer` similar to how `RSocketInterceptor` support exists. See https://github.com/rsocket/rsocket-java/pull/676

**Comment by bclozel** [comment]
Hey @rwinch ,

This API has been added in the rsocket-java library directly and the `ServerRSocketFactoryCustomizer` contract is using directly `RSocketFactory.ServerRSocketFactory`.

As far as I understand we can keep using that contract for the same goal, like this:

```java
@Bean
ServerRSocketFactoryCustomizer myCustomizer() {
	return (serverRSocketFactory) -> {
		SocketAcceptorInterceptor interceptor = null;
		return serverRSocketFactory.addSocketAcceptorPlugin(interceptor);
	};
}
```

Would that work for you or is there something missing here?
