### ISSUE TITLE
WebSecurity performBuild documentation

### ISSUE THREAD

**Issue by aobeidah** [spring-projects/spring-boot#17865]
WebSecurity is declared final which cannot be extended and the performBuild method documentation states that in Subclasses... so I believe this should be fixed as we cannot create Subclasses from final class. 
it's minor but wanted to raise the issue for improving the docs. Thanks spring team

**Comment by wilkinsona** [comment]
Thanks for the report. `WebSecurity` is part of [Spring Security](https://github.com/spring-projects/spring-security). Note that the perform build method is declared on `AbstractConfiguredSecurityBuilder` which `WebSecurity` sub-classes.
