### ISSUE TITLE
Disable H2C by default when using Reactor Netty, aligning it with Jetty, Tomcat, and Undertow

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#17867]
For Http/2 support on Tomcat, Jetty and Undertow we only support HTTP/2 over TLS (h2) whereas for Netty we support the cleartext variant (h2c) as well. We should look at making it consistent which would mean we either need to enable h2c with Tomcat, Jetty and Undertow or disable it with Netty.

/cc @bclozel

**Comment by bclozel** [comment]
The discussed this point and chose to be consistent and disable h2c in our Netty setup.

**Comment by wilkinsona** [comment]
Once this has been fixed, H2C can be enabled by using a `NettyServerCustomizer`:

```java
@Bean
NettyServerCustomizer h2cCustomizer() {
    return (httpServer) -> httpServer.protocol(HttpProtocol.HTTP11, HttpProtocol.H2C);
}
```
