### ISSUE TITLE
Deprecate spring-boot-starter-cloud-connectors

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#17877]
The [Spring Cloud Connectors project](https://spring.io/projects/spring-cloud-connectors) has entered a maintenance mode, as it is being [replaced by the Java CFEnv project](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services#what-rsquo-s-next). Guidance for migrating applications from Connectors to Java CFEnv is forthcoming. 

The `spring-boot-starter-cloud-connectors` starter should be deprecated and eventually removed from Spring Boot to reflect this change.

**Comment by vinovin777** [comment]
Hi Team,
I would like take this up and work!!
