### ISSUE TITLE
Consider Upgrade to Git Commit Id Plugin 3.0.1

### ISSUE THREAD

**Issue by edwardsre** [spring-projects/spring-boot#17879]
We recently ran into an issue with this plugin on a Spring Boot 2.1.7 project that resulted in long build execution times. We used `<excludedProperties>` with the `git-commit-id-plugin` version 2.2.6 (managed by Spring Boot), but this did not help the plugin execution time as version 2.2.6 still goes through all of the work to calculate property values, and then filters the output based on which properties should be included/excluded.

Version 3.0.1 has been [fixed](https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/185) to not do the work for excluded property values which resulted in plugin execution times cut in half. 

This version also has a minimum Java version of 1.8 whereas 2.2.6 has a minimum Java version of 1.7. Just dropping support for Java 1.7 was enough to bump the version to 3.0.

https://github.com/git-commit-id/maven-git-commit-id-plugin/releases/tag/v3.0.0
https://github.com/git-commit-id/maven-git-commit-id-plugin/releases/tag/v3.0.1

**Comment by snicoll** [comment]
@edwardsre thanks for sharing. Yes, I think that might sense, flagging to see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
Closing in favour of #17981.
