### ISSUE TITLE
Add information about the input into the property binding process to the configprops endpoint

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17886]
When trying to determine why a property on a `@ConfigurationProperties` bean has a particular value, it would be useful to know the input into the binding process that resulted in the value. For example, this would make it possible to see if any placeholders are used in the original input.

Relates to #8293.

**Comment by philwebb** [comment]
See also #14880

**Comment by mbhave** [comment]
[This](https://github.com/spring-projects/spring-boot/commit/8dcf1e4033eb1b453447fe48d2cbc9aa8c674d97) also closes this issue.
