### ISSUE TITLE
Consistently use type variant of AbstractDependsOnBeanFactoryPostProcessor dependsOn 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#17888]
#17805 and #16627 switched to using the type variant for mongo and liquibase. 

Potential usages which could be switched are

`flyway`
`cacheManager`
`quartzDataSourceInitializer`

**Comment by snicoll** [comment]
@mbhave is there a reason this is backported to `2.1.x`? I can't help to feel a bit nervous to replace dependency by name to dependency by time in a maintenance release.

**Comment by wilkinsona** [comment]
FWIW, I think the fix should be made in 2.1.x as it's addressing the same sort of problems as were reported in #17805 and #16627. We categorised both of those a bugs and fixed both of them in 2.1.x.

**Comment by mbhave** [comment]
Yeah what @wilkinsona said was my reasoning for putting it in 2.1.x

**Comment by wilkinsona** [comment]
`cacheManager` does not appear to be affected as `CacheAutoConfiguration` will back off if a custom `CacheManager` bean is defined. When it backs off it will take `CacheManagerJpaDependencyConfiguration` with it. While this avoids the dependency problem, it creates a different problem as defining a custom `CacheManager` stops the entity manager factory bean from being configured to depend upon it. I've opened https://github.com/spring-projects/spring-boot/issues/18107.

**Comment by wilkinsona** [comment]
`quartzDataSourceInitializer` has been addressed in https://github.com/spring-projects/spring-boot/pull/17539.
