### ISSUE TITLE
build failure on ppc64le platform

### ISSUE THREAD

**Issue by shirodkara** [spring-projects/spring-boot#17894]
I am trying to build spring-boot on ppc64le , I run into the following error :

> [INFO] Running org.springframework.boot.web.embedded.jetty.SslServerCustomizerTests [ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.072 s <<< FAILURE! - in org.springframework.boot.web.embedded.jetty.SslServerCustomizerTests [ERROR] alpnConnectionFactoryHasNullDefaultProtocolToAllowNegotiationToHttp11 Time elapsed: 0.07 s <<< ERROR! java.lang.IllegalStateException: No Server ALPNProcessors!

This is because there there is a dependency on conscrypt (jetty alpn) , and conscrypt does not build on ppc64le . Any input in what would be the best approach ? Is using another provider in place of conscrypt an option ?

I came across the following that mentions using alpn-boot for non-conscrypt cases:
https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-openjdk8

Any inputs ? Thanks in advance.

**Comment by wilkinsona** [comment]
I see you've also [raised this on Gitter](https://gitter.im/spring-projects/spring-boot?at=5d590198029a51607fb74324), which is a better place for a question such as this.
