### ISSUE TITLE
Support for glob patterns in spring.flyway.locations

### ISSUE THREAD

**Issue by mirkoscotti** [spring-projects/spring-boot#17890]
I have more or less the same requirement as the one explained [here](https://github.com/flyway/flyway/issues/1192). Since neither Flyway architects are planning to manage glob support for custom locations, nor [FlywayAutoConfiguration#FlywayConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java) helps using the ResourceLoader to solve locations like for example `classpath*:com/mycompany/**/ddl`, I have implemented a [configuration hack](https://github.com/spring-projects/spring-boot/files/3511738/flyway-glob-hack.zip) to patch the `FlywayProperties#locations` content. I wonder if you could evaluate to integrate this kind of feature in a future version of Spring Boot.

**Comment by philwebb** [comment]
Thanks for the suggestion, but we don't think adding additional complexity to our `FlywayConfiguration` to support this is something we should do. We'd rather see https://github.com/flyway/flyway/issues/1192 fixed by the Flyway team so we can support it without needing any unnecessary hacks.
