### ISSUE TITLE
How to properly stop a Spring Boot app in Android Studio?

### ISSUE THREAD

**Issue by algakzru** [spring-projects/spring-boot#17892]
Since nobody has answered my question on [Stackoverflow](https://stackoverflow.com/questions/57447303/how-to-properly-stop-a-spring-boot-app-in-android-studio)  I am asking it here.

When I try to stop a Spring Boot app in Android Studio by clicking the stop button on the top right corner of Android Studio the stop button remains enabled although the app is already terminated.

[![enter image description here][1]][1]

I don't have this problem when I stop an Android app in Android Studio.

[![enter image description here][2]][2]

I know that Android Studio is build for the Android development, not for the Spring Boot development, but since our frontend is an Android app and backend is a Spring Boot app, it's more convenient to develop both apps in one IDE, instead of switching between Android Studio and IntelliJ IDEA.

[![enter image description here][3]][3]

Since Android Studio is just a modified version of IntelliJ IDEA, running a Spring Boot app in Android Studio is exactly the same as it is in IntelliJ IDEA, but stopping it apparently requires some extra effort.

When I stop a Spring Boot app with the stop button it prints the following message to the console, could that be a reason ?
```
Process finished with exit code -1
```

**Reproduce this issue:**

1. Create a new Android project (Empty Activity)
2. Create a new Spring Boot Web project on https://start.spring.io
3. Add Spring boot Web project as a module to the Android project
4. Run the Spring Boot module
5. Stop the Spring Boot module with the stop button on the top right corner of Android Studio

**Expected/actual:**

I expect the stop button to become disabled after the Spring Boot app is terminated, but it remains enabled.

  [1]: https://i.stack.imgur.com/oF4FJ.png
  [2]: https://i.stack.imgur.com/4MVvO.png
  [3]: https://i.stack.imgur.com/7FR6Q.png

**Comment by snicoll** [comment]
Thanks for getting in touch, but as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you believe this is a tooling issue, you should report it to Jetbrains and not here.
