### ISSUE TITLE
mix-up in ConfigurationProperties Documentation?

### ISSUE THREAD

**Issue by jo2** [spring-projects/spring-boot#17917]
Browsing the Documentation of [ConfigurationProperties](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/ConfigurationProperties.html) I saw that at the Element Detail of value and prefix both words seem to have been mixed up sometimes. At least to me it is confusing. Is it just my understanding causing this or is this an error? If so, I can provide a PR.

**Comment by snicoll** [comment]
@jo2 hard to say as I can only guess hat you find confusing. Perhaps you can quote what's wrong and why you think that is?

**Comment by jo2** [comment]
![image](https://user-images.githubusercontent.com/7516893/63343880-6375ad80-c34f-11e9-8208-6933b138e447.png)

I find it confusing that for value it is @AliasFor(value="prefix") and for prefix it is the other way round. 

Also the description is in both cases the exact same except for the method. in both cases it is 'A valid prefix is defined by ..'. Shoudln't it be 'A valid value is defined by ..' for the value attribute?

Also in both cases it returns 'the name prefix of the properties to bind'. Shouldn't it be 'the name value of the properties to bind' for the value attribute?

**Comment by snicoll** [comment]
`value` is an alias for `prefix` and `prefix` is an alias for `value`. That's exactly what it's supposed to do. The idea is that you can configure things as `@ConfigurationProperties("com.example")` and `@ConfigurationProperties(prefix = "com.example")` when you need to customize more attributes. 

If we hadn't that feature, it would read `@ConfigurationPropertiers(value = "com.example")` which doesn't read as nice.

What made you think these are two different properties? Specifically in the reference guide, an example or something else.

**Comment by jo2** [comment]
Them being listed as two separate elements made me think that. But thanks for that clarification. If they are the same it makes sense.
