### ISSUE TITLE
Configure ping (formerly application) health indicator by default

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17926]
When #14022 is fixed it's possible that the `ApplicationHealthIndicator` might be generally useful for use in a group. Currently we only enable it if no other indicators are active but I think we should consider always adding it.

**Comment by wilkinsona** [comment]
+1. From what I've seen, some people would like to use a ping-like health indicator in a liveness check in Kubernetes.

**Comment by philwebb** [comment]
We'll rename it to `PingHealthIndicator` and always add it.
