### ISSUE TITLE
Resource Server Configuration of Issuer Validation 

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-boot#17920]
Related to https://github.com/spring-projects/spring-security/issues/7274

When an application configures an `issuer-uri`, this does three things:

* Looks up the JWK Set Uri
* Creates a `JwtDecoder`, using that JWK Set Uri
* Adds issuer validation to that `JwtDecoder`

When an application configures a `jwk-set-uri`, this does one thing:

* Creates a `JwtDecoder`, using that JWK Set Uri

When an application configures both of these properties, it does only one thing:

* Creates a `JwtDecoder`, using that JWK Set Uri

It's reasonable, though, that when an application configures both of these properties, it should do two things:

* Creates a `JwtDecoder`, using that JWK Set Uri
* Adds issuer validation to that `JwtDecoder`

This would allow applications who don't want to be reliant on OIDC Discovery at startup time to still get the same security guarantees that Boot provides with that feature.

When both properties are specified, Boot could do something like:

```java
@Bean 
JwtDecoder jwtDecoder() {
    NimbusJwtDecoder jwtDecoder = NimbusJwtDecoder.withJwkSetUri(jwkSetUri).build();
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(issuerUri));
    return jwtDecoder;
}
```

This setup would ensure a quick startup time while still adding issuer validation.

**Comment by mbhave** [comment]
Closing in favor of PR #17952.
