### ISSUE TITLE
Custom favicon placed in static resources doesn't work since 2.2.0.M5

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#17922]
After upgrading to Spring Boot `2.2.0.M5` custom favicon placed in `src/main/resources/static/favicon.ico` stopped working, and Boot's default favicon is returned instead.

At quick glance, I suspect this is a regression caused by #17318. It seems unintended, as [this comment](https://github.com/spring-projects/spring-boot/issues/17318#issuecomment-509182619) states that:

> A custom favicon placed somewhere beneath a static resources location will also continue to work as it did before.

Which isn't the case, unless I misunderstood something.

This can be easily reproduced with a minimal application using just `spring-boot-starter-web` and having custom favicon placed in `src/main/resources/static/favicon.ico`. Downgrading to `2.2.0.M4` restores the expected behavior.

**Comment by wilkinsona** [comment]
When fixing https://github.com/spring-projects/spring-boot/issues/17318, I was too focused on the nested case, `GET /explorer/favicon.ico` for example, and did not consider the simpler and more common case of `GET /favicon.ico`. This simpler case is a direct match for the `favicon.ico` resource handler mapping to `classpath:favicon.ico` so the favicon found by the classpath, typically Boot's, is always returned.

**Comment by wilkinsona** [comment]
Thanks for trying out M5, @vpavic. This should now be fixed on master. You should be able to work around the problem with M5 by moving your `favicon.ico` into `src/main/resources` so that it can be found at the root of the classpath. Alternatively, you could set `spring.mvc.favicon.enabled=false`.

**Comment by vpavic** [comment]
Thanks for the prompt fix @wilkinsona. I did workaround this by disabling default favicon through environment. I'll give snapshot a try later today.
