### ISSUE TITLE
enhancement - allow .spring-boot-devtools.properties file to exist in any location per project

### ISSUE THREAD

**Issue by scottmf** [spring-projects/spring-boot#17923]
Problem - I want local configuration for my spring projects outside of my repository.  Using spring devtools to achieve this is cumbersome since I projects have overlapping configurationProperties (i.e. spring.*, server.*, etc..).  I want different values for different projects.
Issue with spring devtools - the .spring-boot-devtools.properties file is only allowed in my home directory
Solution - allow for the .spring-boot-devtools.properties file exist outside the home directory.  Allow it to be driven by an environment variable or system property.

**Comment by philwebb** [comment]
Closing in favor of PR #17924

**Comment by tedyoung** [comment]
I see that this issue was closed, but the PR referenced #17924 was never merged. It'd be nice to have this kind of support for local-to-my-machine config on a per project basis.

**Comment by snicoll** [comment]
@tedyoung this issue is now superseded by the PR and it still open.
