### ISSUE TITLE
Remove Tomcat 7 logic from TomcatErrorPage

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17937]
https://github.com/spring-projects/spring-boot/blob/b43827d6264a3eb4e9558c6e1dd7f89e537caa96/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/tomcat/TomcatErrorPage.java#L67-L80

**Comment by Sauhardstark** [comment]
@philwebb Hi
I looked at the code and couldn't understand what was required. Could you please elaborate a little more ?

**Comment by philwebb** [comment]
@philwebb This one was really just a reminder to myself to remove some dead code. It's not a big issue so there's no need for a PR.
