### ISSUE TITLE
Non MVC web applications always return 404 for errors

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#17938]
This can be reproduced by adding spring security to `SampleJerseyApplication` and setting `management.server.port` to something other than 8080. The difference between the main application port and the management port is that there's an error page for the management context.

**Comment by philwebb** [comment]
Currently `ManagementWebServerFactoryCustomizer` always adds an `ErrorPage`, however, in Jersey applications we don't have an endpoint for them so the application returns 404 for all errors. We should probably mirror `ErrorMvcAutoConfiguration.ErrorPageCustomizer` somehow and only register them for MVC.
