### ISSUE TITLE
@WebMvcTest excludeFilters doesn't seem to be working in a very specific case

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-boot#17941]
I have the following application (all the logic was removed/simplified)

```
@SpringBootApplication
public class MainApplication {
    public static void main(String[] args) {
        SpringApplication.run(MainApplication.class, args);
    }
}
```

```
@Component
public class TestFilter implements Filter {
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        System.out.println("TestFilter");
        chain.doFilter(request, response);
    }
}
```

```
@RestController
@RequestMapping("/test")
public class TestController {
    @GetMapping
    public String getHandler(@RequestParam String input) {
        return input;
    }
}
```

```
@Configuration
public class TestWebMvcConfigurer implements WebMvcConfigurer {
}
```

and the following test which is trying to test `TestController`

```
@WebMvcTest(controllers = TestController.class,
            excludeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE,
                                                   classes = TestFilter.class))
public class TestControllerTest {
    @Autowired
    private MockMvc mvc;

    @Test
    public void testGet() {
        RequestBuilder request = MockMvcRequestBuilders.get(getPath("/test", Map.of("input", "test")));
        MockHttpServletResponse response = mvc.perform(request)
            .andReturn()
            .getResponse();

        System.out.println(response.getContentAsString());
        System.out.println(response.getStatus());

        // ...
    }

    private String getPath(String path, Map<String, ?> parameters) {
        // returns an url for <path> with query parameters <parameters>
    }
}
```

In this case, the filter `TestFilter` is being excluded and I can see it is not being run. However, if I remove `@Component` from `TestFilter` and add

```
    @Bean
    public TestFilter testFilter() {
        return new TestFilter();
    }
```

to `TestWebMvcConfigurer`, then filter `TestFilter` stops being excluded.

I'm using Spring Boot 2.1.7.

**Comment by snicoll** [comment]
That's working as designed, the `Filter` is a `@ComponentScan` filter so it doesn't do anything for beans that are contributed to the context via explicit `@Configuration`.

If you want this filter to be excluded, just move it to any other `@Configuration` that's not enabled by `@WebMvcTest`.

**Comment by joca-bt** [comment]
I might have multiple `@WebMvcTest`s and want to exclude different filters (or other components/beans) in different tests. Is there another way of excluding certain `@Bean`s from certain `@WebMvcTest`s?

**Comment by snicoll** [comment]
@joca-bt you can group whatever needs to be grouping and import that on a test-by-test basis. It really depends of your project and how granular this needs to be. If you have more questions, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
