### ISSUE TITLE
Allow Custom Environment Class Specification

### ISSUE THREAD

**Issue by samjoseph** [spring-projects/spring-boot#17956]
The SpringApplication class has a private method which deduces the Environment Class from the methods present 

private Class<? extends StandardEnvironment> deduceEnvironmentClass() {
		switch (this.webApplicationType) {
		case SERVLET:
			return StandardServletEnvironment.class;
		case REACTIVE:
			return StandardReactiveWebEnvironment.class;
		default:
			return StandardEnvironment.class;
		}
	}

There must be a way to specify custom Environment Class specified by Applications which can be    used. 

We have a particular case where we use a custom Environment (extending StandardEnvironment class ) where we do fetching of credentials from other backend systems and cache them in the class.

**Comment by samjoseph** [comment]
There is particular case in the Spring Cloud Project where a Standard Environment is provided thereby removing any custom environment set using the Spring Builder Class. Allowing apps to specify which Environment Class to untilize for apps might help mitigate this issue. 

BootstrapApplicationListener Class

private ConfigurableApplicationContext bootstrapServiceContext(
			ConfigurableEnvironment environment, final SpringApplication application,
			String configName) {
		StandardEnvironment bootstrapEnvironment = new StandardEnvironment();
		MutablePropertySources bootstrapProperties = bootstrapEnvironment
				.getPropertySources();
		for (PropertySource<?> source : bootstrapProperties) {
			bootstrapProperties.remove(source.getName());
		}

**Comment by snicoll** [comment]
> We have a particular case where we use a custom Environment (extending StandardEnvironment class ) where we do fetching of credentials from other backend systems and cache them in the class.

Why do you need a a custom `Environment` for that? You could achieve the same thing with a custom `PropertySource`.

**Comment by samjoseph** [comment]
@snicoll

Giving more perspective 

sam.credential.property=MockCredentialVault("Test")

Where MockCredentialVault is a type of Credential Vault System we want to access with the "Test" value

So we need to have access to all property sources since the MockCredentialVault("Test") could also be in a different file

application.properties
sam.credential.property=${vault.system.placeholder}

prod.properties
vault.system.placeholder=MockCredentialVault("Test")

So in this case - we cannot have a Property Source - we feel that the a custom environment would be a better place to do this resolution as it has access to all property sources and we can also have a central location to cache & refresh the credentials obtained in the custom Environment class.

**Comment by snicoll** [comment]
What's wrong with `SprinApplication#setEnvironment` ?

**Comment by samjoseph** [comment]
There is nothing wrong with that it works as expected - but the thing is in the Spring Cloud Project they have a BootstrapApplicationListener that creates a Spring Application & runs it again (with a StandardEnvironment) they add to the SpringApplication

There is particular case in the Spring Cloud Project where a Standard Environment is provided thereby removing any custom environment set using the Spring Builder Class. Allowing apps to specify which Environment Class to utilize for apps might help mitigate this issue.

BootstrapApplicationListener Class

private ConfigurableApplicationContext bootstrapServiceContext(
ConfigurableEnvironment environment, final SpringApplication application,
String configName) {
StandardEnvironment bootstrapEnvironment = new StandardEnvironment();

I believe this could be avoided if there is a way to deduce the Application's Environment Class as required by the application.

**Comment by snicoll** [comment]
Thanks for the feedback. Please report that issue to [the Spring Cloud project](https://github.com/spring-cloud/spring-cloud-commons) and we can follow up in Spring Boot after if necessary.
