### ISSUE TITLE
ManagementWebServerFactoryCustomizer should not always add ErrorPage

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17951]
Currently `ManagementWebServerFactoryCustomizer` always adds an `ErrorPage`, however, in Jersey applications we don't have an endpoint for them so the application returns 404 for all errors. We should probably mirror `ErrorMvcAutoConfiguration.ErrorPageCustomizer` somehow and only register them for MVC.

**Comment by philwebb** [comment]
See #17912

**Comment by mbhave** [comment]
@philwebb I think this is a duplicate of #17938
