### ISSUE TITLE
Wrong documentation for the property to configure Undertow's accesslog directory

### ISSUE THREAD

**Issue by skivol** [spring-projects/spring-boot#17966]
> Logs are stored in a logs directory relative to the working directory of the application. You can customize this location by setting the server.undertow.accesslog.directory property.

[Docs page](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html)

Should most likely be "dir" instead of "directory" per [ServerProperties](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/ServerProperties.Undertow.Accesslog.html) and how it actually worked for "2.1.6.RELEASE".

**Comment by wilkinsona** [comment]
Thanks for pointing out the mistake, @skivol. Closing in favour of #17968.
