### ISSUE TITLE
lombok @NonNull make @NestedConfigurationProperty Invalid

### ISSUE THREAD

**Issue by jianchengwang** [spring-projects/spring-boot#17971]
here is my post issue in lombok https://github.com/rzwitserloot/lombok/issues/2218#issue-485664267

**Comment by wilkinsona** [comment]
Please don't open the same issue in multiple places. It risks teams duplicating effort and wasting time. I've had subscribed to the Lombok issue so that I can see how it progresses. If it turns out that a change is needed in Spring Boot we can re-open this issue.
