### ISSUE TITLE
Remove banner-mode: "off" hint

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17987]
We no longer need to quote "off" so we can remove the hint in the in features documentation.

**Comment by Sauhardstark** [comment]
Sorry to ask such a basic question but how would one go about changing something present in the features documentation
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-banner

**Comment by snicoll** [comment]
The readme has a section on [how to build the reference documentation](https://github.com/spring-projects/spring-boot/blob/master/README.adoc#building-reference-documentation)

**Comment by philwebb** [comment]
My mistake, I was looking at 2.1.x. This was fixed in 7d27c6ff92821b85c13dfbf80f665a2b0d757a00
