### ISSUE TITLE
`gradle build` task doesn't add content of `/src/main/webapp` folder 

### ISSUE THREAD

**Issue by fedotxxl** [spring-projects/spring-boot#180]
Hi.
I'm using spring-boot plugin 0.5.0.M6. 
I've added static files to `/src/main/webapp` and configured `run` task similar to https://github.com/jaylindquist/spring-boot-service-and-static/blob/master/build.gradle

`gradle run` works as expected. `gradle build` builds flat jar file but it doesn't add content of `/src/main/webapp` folder. So `java -jar xxx.jar` will behave incorrectly

**Comment by JavierOrtuno** [comment]
How can I configure InternalResourceViewResolver to read my views from static folder?

**Comment by snicoll** [comment]
@JavierOrtuno this issue is closed and questions are to be raised on StackOverflow. Thanks
