### ISSUE TITLE
JDBC CommunicationsException with DataSource Health Check

### ISSUE THREAD

**Issue by huangxfchn** [spring-projects/spring-boot#18010]
# Description
* Database is MySql, and connection's lifetime is 5 minutes.
* There are more idle connections in the low peak period of the business
* Using [Druid Jdbc Pool](https://github.com/alibaba/druid), the connection will be cleaned up for more than 3 minutes.
* The monitoring system calls the health check every 1 minute.

```
public class DataSourceHealthIndicator extends AbstractHealthIndicator implements InitializingBean {
	private void doDataSourceHealthCheck(Health.Builder builder) throws Exception {
		String product = getProduct();
		builder.up().withDetail("database", product);
		String validationQuery = getValidationQuery(product);
		// execute validationQuery……
	 }
    
	private String getProduct() {
		return this.jdbcTemplate.execute((ConnectionCallback<String>) this::getProduct);
	}

	private String getProduct(Connection connection) throws SQLException {
		return connection.getMetaData().getDatabaseProductName();
	}
}
```

# Exception analysis
The `spring boot actuator` gets the jdbc Connection when executing the DataSource health check, and calls `connection.getMetaData().getDatabaseProductName()`, which does not actually operate the database, resulting in the connection's effective time not being renewal.

When returning to the connection pool, Druid will change `lastActiveTimeMillis` to the latest time, which will cause the cleanup thread to mistake the connection for its validity, so it has not been cleaned up. 

In fact, it has passed the survival time. It will disturb the cleanup of the connection pool, then the next time you get this connection, it will be invalid for MySql, throwing a `CommunicationsException` exception.

# solution
- `getProduct()` method and `validationQuery` shold share the same jdbc connection, and return to the connection pool after use.

**Comment by philwebb** [comment]
It's quite a significant changing to have the `DataSourceHealthIndicator` reuse the same connection for both the product name lookup and the validation query. It feel like this might be a bug with Druid.

Are you aware of any reason why the call to `connection.getMetaData().getDatabaseProductName()` doesn't change `lastActiveTimeMillis`? If feel like a legitimate thing to do.

**Comment by huangxfchn** [comment]
> It's quite a significant changing to have the `DataSourceHealthIndicator` reuse the same connection for both the product name lookup and the validation query. It feel like this might be a bug with Druid.
> 
> Are you aware of any reason why the call to `connection.getMetaData().getDatabaseProductName()` doesn't change `lastActiveTimeMillis`? If feel like a legitimate thing to do.
1, `connection.getMetaData().getDatabaseProductName()`, just take the cache information, will not interact with the mysql server, so mysql will not renew the link
2. However, after the link is returned to Druid, the connection's lastActiveTimeMillis time is updated because the `connection` method was called before.

In addition, can Health check only execute `select 1` once?


> It's quite a significant changing to have the `DataSourceHealthIndicator` reuse the same connection for both the product name lookup and the validation query. It feel like this might be a bug with Druid.
> 
> Are you aware of any reason why the call to `connection.getMetaData().getDatabaseProductName()` doesn't change `lastActiveTimeMillis`? If feel like a legitimate thing to do.

1, `connection.getMetaData().getDatabaseProductName()`, just take the cache information, will not interact with the mysql server, so mysql will not renew the connection.
2. However, after the link is returned to Druid, the connection's lastActiveTimeMillis time is updated because the connection's method was called before. Druid thinks there is already interaction with the database.

In addition, can health check only execute `select 1` once  to avoid this issue?

**Comment by philwebb** [comment]
I'm still not sure I understand why calling `connection.getMetaData().getDatabaseProductName()` alone would break the connection pool. It seems like a perfectly legitimate thing to do and as far as I know none of the other database pools have had problems.

Can you please raise an issue with Druid first to see if they can fix the problem on their side?
