### ISSUE TITLE
ApplicationContextRequestMatcher can use the wrong ApplicationContext

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18012]
Discovered during #17912 

`ApplicationContextRequestMatcher` uses `WebApplicationContextUtils.getRequiredWebApplicationContext(request.getServletContext())` to obtain the application context and caches the supplier. If there is a management server running on a different port, it's possible for the wrong context to be used depending on who makes the first request.

**Comment by Sauhardstark** [comment]
One way might be to stop caching the context all together and call the `createContext` method each time. It's safe for Tomcat at least as `ApplicationContext` in tomcat just fetches it from a `ConcurrentHashMap attributes`
Another might be to maintain a ConcurrentHashMap inside ApplicationContextRequestMatcher, same as `ApplicationContext`.
I have also checked UnderTow and Jetty and they both do something similar (using Maps) in `ServletContextImpl` and `ContextHandler`
