### ISSUE TITLE
DataSourceInitializedEvent.java Missing in 2.1.x

### ISSUE THREAD

**Issue by consult-kk** [spring-projects/spring-boot#18020]
While upgrading from SpringBoot 1.4.x to SprignBoot 2.x I see that 
DataSourceInitializedEvent.java has been removed in SpringBoot 2.1.x , is there an alternate event mechanism I can use 

thanks,
KK

**Comment by philwebb** [comment]
Try `DataSourceSchemaCreatedEvent`
