### ISSUE TITLE
string boot 2.1.7.RELEASE is empty repository package in spring-data-jpa 

### ISSUE THREAD

**Issue by kimsangkyun** [spring-projects/spring-boot#18087]
![image](https://user-images.githubusercontent.com/9389857/64093057-d3ddef00-cd91-11e9-8acd-00da3826aa5b.png)

**Comment by wilkinsona** [comment]
@kimsangkyun Spring Data JPA is a separate project from Spring Boot and it uses [JIRA](https://jira.spring.io/browse/DATAJPA) for issue management. That said, I doubt this is a bug in Spring Data JPA. It's much more likely to be a local problem. Perhaps Maven (assuming you are using Maven) corrupted the jar file when it downloaded it. Try deleting the jar from Maven's cache and building your project again.

**Comment by kimsangkyun** [comment]
@wilkinsona i try to clean but still it is empty...
