### ISSUE TITLE
ConditionalOnProperty not work for external properties

### ISSUE THREAD

**Issue by limx1986** [spring-projects/spring-boot#18086]
Here is the code sample:
https://github.com/limx1986/property-demo
Stackoverflow address is here:
https://stackoverflow.com/questions/48717022/spring-conditionalonproperty-for-external-properties
The spring boot version is 2.1.7.RELEASE.

**Comment by wilkinsona** [comment]
As [noted in the documentation](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/htmlsingle/#howto-customize-the-environment-or-application-context), `@PropertySource` is processed too late to influence the evaluation of your property-based condition.
