### ISSUE TITLE
Should CloudFoundryVcapEnvironmentPostProcessor rely on java-cfenv?

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#18097]
According to [this article](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services) this [library](https://github.com/pivotal-cf/java-cfenv) will hep to read services from VCAP_SERVICES. `CloudFoundryVcapEnvironmentPostProcessor` already read this values but not sure if there is any plan to migrate and use `java-cfenv`. if it is so, I can work on it.

**Comment by snicoll** [comment]
`java-cfenv` relies on Spring Boot so we can't really have a dependency on it. We were considering offering dependency management for it but it looks like we won't be able to do that either.

**Comment by wilkinsona** [comment]
Thanks for the offer, @eddumelendez, but as @snicoll has explained we can't do this due to the existing dependency on Boot in java-cfenv.

**Comment by eddumelendez** [comment]
Thanks guys, just to be clear `java-cfenv` has no dependency on spring boot as far as I can see but `java-cfenv-boot` does. what I was proposing is to use the first one. In case I miss something sorry for the noise.

**Comment by wilkinsona** [comment]
`java-cfenv` and `java-cfenv-boot` are managed and released together so, while there'd be no circular dependency between modules, there would still be one between projects and that's something that we need to avoid.

**Comment by eddumelendez** [comment]
Thanks @wilkinsona got it!
