### ISSUE TITLE
HikariCP and Tomcat specific datasource properties missing in spring-configuration-metadata.json

### ISSUE THREAD

**Issue by kedar-joshi** [spring-projects/spring-boot#18124]
Significant number of properties are missing from `META-INF/spring-configuration-metadata.json`  for Spring Boot v2.2.0.M5 as compared v2.2.0.M4. Although this doesn't affect any functionality, **IDE intellisense is for sure affected** as IDE is unable to provide autocompletion for groups like `spring.datasource.hikari` and `spring.datasource.tomcat`. To name a few, following datasource property groups are missing in v2.2.0.M5 -

```json
[
  {
    "name": "spring.datasource.dbcp2",
    "type": "org.apache.commons.dbcp2.BasicDataSource",
    "sourceType": "org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Dbcp2",
    "sourceMethod": "dataSource(org.springframework.boot.autoconfigure.jdbc.DataSourceProperties)"
  },
  {
    "name": "spring.datasource.hikari",
    "type": "com.zaxxer.hikari.HikariDataSource",
    "sourceType": "org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari",
    "sourceMethod": "dataSource(org.springframework.boot.autoconfigure.jdbc.DataSourceProperties)"
  },
  {
    "name": "spring.datasource.tomcat",
    "type": "org.apache.tomcat.jdbc.pool.DataSource",
    "sourceType": "org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Tomcat",
    "sourceMethod": "dataSource(org.springframework.boot.autoconfigure.jdbc.DataSourceProperties)"
  }
]
```

Both source files are also attached [spring-configuration-metadata.json.zip](https://github.com/spring-projects/spring-boot/files/3573347/spring-configuration-metadata.json.zip).

**Comment by wilkinsona** [comment]
Thanks for the report, @kedar-joshi.

I think this is caused by the `@Bean` methods becoming package-private which causes the annotation processor to miss them.

**Comment by snicoll** [comment]
Spot on @wilkinsona, should we relax this rule in the AP?
