### ISSUE TITLE
why not make `org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker` as public class?

### ISSUE THREAD

**Issue by shauway** [spring-projects/spring-boot#18123]
why not make `org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker` as public class?

**Comment by wilkinsona** [comment]
Making it public would limit our ability to evolve its API as we would be unable to make backwards incompatible changes. We have some changes that we'd like to make that are already proving to be challenging. The constraints of the API being public would make those changes even harder.

**Comment by wilkinsona** [comment]
If you have any further questions, please follow up on [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

Alternatively, if there's something that you would like to be able to do that is not currently possible, please open an enhancement request that describe what you're trying to achieve, ignoring how it may be implemented.
