### ISSUE TITLE
BasicErrorController returns body even if NO_CONTENT status causing 406 later

### ISSUE THREAD

**Issue by aleksanderlech** [spring-projects/spring-boot#18136]
Having exception defined like this:

```java
@ResponseStatus(HttpStatus.NO_CONTENT)
public class NoContentException extends RuntimeException {

    public NoContentException(String id) {
        super("ID " + id + " has no content.");
    }
}
```

And the controller method as following:

```java
    @GetMapping(path = "/{id}/content", produces = {
            "text/plain",
            "audio/wav",
            "image/tiff"
    })
    public ResponseEntity<FileSystemResource> getContent(@PathVariable Id id, @RequestHeader(value = HttpHeaders.ACCEPT, required = false) MediaType requestedMediaType) {
        throw new NoContentException(id.toString()));
    }
```

I would expect that the response code will be no content no matter what but while executing

```
curl 'http://localhost:8080/rest/1/content' -i -X GET -H 'Accept: audio/wav'
```

I am getting 406 (Not Acceptable) because the *BasicErrorController* that always attaches the body no matter what the status code is:

```java
@RequestMapping
public ResponseEntity<Map<String, Object>> error(HttpServletRequest request) {
	Map<String, Object> body = getErrorAttributes(request, isIncludeStackTrace(request, MediaType.ALL));
	HttpStatus status = getStatus(request);
	return new ResponseEntity<>(body, status);
}
```

will later cause 406 as the body cannot be converted to the requested type. It seems to be a bug to me as according to the spec the no content response should never contain body.

**Comment by s2agrahari** [comment]
By default the registered message converter in `spring-boot-starter-web` are `"application/json, application/*+json". `

Thats the reason for getting 406 as there is no message converter found for `audio/wav` and the BasicErrorController sends the control to `unsupportedMediaType()`.

To get the desired result of 204, try updating the `MessageConverter` by overriding `WebMvcConfigurationSupport's configureMessageConverters()` 


`@Configuration
public class WebConfig extends WebMvcConfigurationSupport {

    @Override
    protected void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
        converter.setSupportedMediaTypes(Collections.singletonList(MediaType.ALL));
        converters.add(converter);
        super.configureMessageConverters(converters);
    }
}`

**Comment by wilkinsona** [comment]
Thanks for trying to help, @s2agrahari.

The 406 only occurs because the error controller is returning a body. If the response had no body, Spring MVC [would not throw a `HttpMediaTypeNotAcceptableException`](https://github.com/spring-projects/spring-framework/blob/333711fd36f7774fd0ffeebf514e83899b90f6c7/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/AbstractMessageConverterMethodProcessor.java#L250-L252) and, therefore, would not return a 406.

**Comment by wilkinsona** [comment]
@aleksanderlech Using an exception to return a 204 is, perhaps, a little unusual. It's also a little inefficient which may or may not be a problem, depending on how often your application will return such a response. You may want to consider returning a `ResponseEntity` with a 204 status directly instead:

```java
@GetMapping(path = "/{id}/content")
public ResponseEntity<FileSystemResource> getContent(@PathVariable String id) {
    return new ResponseEntity<>(HttpStatus.NO_CONTENT);
}
```

This will take Boot's error handling and error controller completely out of the picture.
