### ISSUE TITLE
（/actuator/metrics/hikaricp.connections ）The service returns an exception after a period of normal operation.

### ISSUE THREAD

**Issue by fenghualiusha** [spring-projects/spring-boot#18131]
Exeption Info：

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Sep 02 21:53:23 CST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Could not write JSON: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.; nested exception is java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
```

**Comment by philwebb** [comment]
@fenghualiusha Do you have a complete stacktrace or a sample application that you can share?

**Comment by fenghualiusha** [comment]
I use the spring boot admin for metrics monitoring, it can run for a while, but then I can't get the data.

![image](https://user-images.githubusercontent.com/22256233/64313021-cf594680-cfdc-11e9-8b25-b601f493dd1d.png)

At this point, the /actuator/metrics/hikaricp.connections interface returns the result as: 
{"name":"hikaricp.connections","measurements":[{"statistic":"VALUE","value":NaN}],"availableTags":[]}

**Comment by fenghualiusha** [comment]
2019-09-05 13:16:53.018 [http-nio-8096-exec-7] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver -Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.; nested exception is java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.

**Comment by philwebb** [comment]
Thanks, it looks like the exception is thrown from [here](https://github.com/google/gson/blob/5370b076e329444860b0ea0c7f33b10504281f27/gson/src/main/java/com/google/gson/Gson.java#L357). We probably need to null out `Double.isNaN(value)` and `Double.isInfinite(value)` `Samples` from our metrics endpoint.

**Comment by wilkinsona** [comment]
We don't yet support using GSON with the Actuator. Jackson correctly handles NaN and the like so this isn't problem when using the supported JSON serializer. #13766 is tracking the addition of support for GSON.
