### ISSUE TITLE
Allow Execution of Flyway Commands Before migrate()  

### ISSUE THREAD

**Issue by aahlenst** [spring-projects/spring-boot#1814]
Flyway offers some nice methods like [`clean()`](http://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/Flyway.html#clean()) that are handy for testing purposes. But as far as I see in `FlywayAutoConfiguration.java`, `migrate()` is directly called after creating the `Flyway` bean which means that if I would call `clean()` myself, it would run after `migrate()` so I would have to call `migrate()` a second time which isn't ideal. Would you consider adding some properties or some other means of configuration that would make it possible to control which methods are executed after the bean was created?

**Comment by lpandzic** [comment]
In what milestone is this going to be released?

**Comment by snicoll** [comment]
Good catch, it was missing the milestone. `1.3.0.M1` should be released in the coming weeks.
