### ISSUE TITLE
Set the packaging of Spring-Boot-Starters to POM

### ISSUE THREAD

**Issue by blackanthrax** [spring-projects/spring-boot#18152]
Currently the Spring-Boot-Starters have no packaging set. So maven implicitly sets it to jar.
While this might work it comes with a considerable downside when it comes to organizational regulations (e.g. Sonatype IQ scans).

Setting the packaging to POM would resolve a lot of false positives in such scans.

**Comment by snicoll** [comment]
Thanks for the suggestion but starters are `jar` packaging on purpose so that you can add them as a regular dependency. Moving to `pom` would break all users out there as well.
