### ISSUE TITLE
Quartz is failing with JDBC but without Liquibase

### ISSUE THREAD

**Issue by anderius** [spring-projects/spring-boot#18153]
Since https://github.com/spring-projects/spring-boot/pull/17539 (released in 2.1.8), it seems `org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration` uses `@ConditionalOnBean(SpringLiquibase.class)`.

Since I don't use Liquibase, and don't have it on classpath, my application won't start, with:

`Error creating bean with name 'org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration': Unexpected exception during bean creation; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy`.

Some later commit removed the similar reference to Flyway, but I suspect Liquibase was forgotten.
With Flyway, the code references `FlywayMigrationInitializer`, included in `spring-boot-autoconfigure`.

**Comment by wilkinsona** [comment]
Sorry for the inconvenience, @anderius, and thank you for the report. We'll fix this in 2.1.9. In the meantime you can either drop back to 2.1.7 or, if you'd like to stick with 2.1.9, you could add a dependency on Liquibase and disable its auto-configuration.

**Comment by philwebb** [comment]
Sorry about that. @nosan even [pointed it out as an issue](https://github.com/spring-projects/spring-boot/pull/17539#issuecomment-527559794) but I thought it would be fine. 🤦‍♂

**Comment by pioto** [comment]
@wilkinsona, do you have an expected release date for 2.1.9?

**Comment by wilkinsona** [comment]
It'll be a couple of days after Spring Framework 5.1.10. It's current scheduled for 24 September so I've set 26 September as the current date for 2.1.9. It may move a little, but I'd expect only by a day or two.
