### ISSUE TITLE
Broken links in the starter and auto-configuration class tables in the reference documentation

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#18163]
This appears to be a regression in `2.1.8.RELEASE`:

- [Appendix C in `2.1.7.RELEASE`](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/htmlsingle/#auto-configuration-classes)
- [Appendix C in `2.1.8.RELEASE`](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/htmlsingle/#auto-configuration-classes)

**Comment by wilkinsona** [comment]
The [starters table](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/htmlsingle/#using-boot-starter) has a similar problem.

**Comment by wilkinsona** [comment]
Thanks for spotting this, @vpavic. The fixed snapshot documentation should be published shortly.

**Comment by philwebb** [comment]
I'm really not having much luck with my contributions to this release :(  Thanks @vpavic for reporting and @wilkinsona for cleaning up my mess!
