### ISSUE TITLE
spring-data-redis not working with jedis +3.x

### ISSUE THREAD

**Issue by GabrielBB** [spring-projects/spring-boot#18169]
I get `java.lang.ClassNotFoundException: redis.clients.util.Pool` when i used these dependencies:

```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.8.RELEASE</version>
</parent>

 <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-redis</artifactId>
</dependency>
<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>3.1.0</version>
    <type>jar</type>
</dependency>
```

**Comment by philwebb** [comment]
The version of Spring Data that ships with Spring Boot 2.1.x is not compatible with that version. We'd always recommend using the manged version which is currently [2.9.3](https://github.com/spring-projects/spring-boot/blob/v2.1.8.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L107).

Spring Boot 2.2 will support Jedis 3.1.0 (See #17622)

**Comment by GabrielBB** [comment]
Oh, good to know the support is already on the way! The Spring Team rocks <3
