### ISSUE TITLE
Investigate walkmod

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1817]
Not everyone uses eclipse and [this](http://walkmod.com/) might allow us to apply formatting conventions

**Comment by snicoll** [comment]
@philwebb isn't that superseded by the work you've initiated with the Google formatter?

**Comment by rpau** [comment]
walkmod not only fix formatting issues. It also removes dead code (e.g unused imports, variables, etc) and many PMD rules (e.g null checks)

**Comment by snicoll** [comment]
@rpau - thanks. What we're after is something that we can run in both Eclipse and IntelliJ IDEA (NetBeans would be nice as well).

Our current checkstyle configuration is [here](https://github.com/spring-projects/spring-boot/tree/f57ff3a7771ccd339df3e632d935c8fd67078055/spring-boot-project/spring-boot-parent/src/checkstyle)

**Comment by rpau** [comment]
Thanks!.
FYI walkmod is IDE agnostic respecting the existing formatting in the files that need to be fixed.
At a first glance, there will be several automatic fixups that can be applied. More feedback in few days.

**Comment by snicoll** [comment]
> FYI walkmod is IDE agnostic 

What I meant by that is that it would be nice to be able to run this in our IDE and get the feedback there, rather than having to run something on the command line to discover we broke something.

**Comment by rpau** [comment]
Oh. IDEs are fully compatible with build tools and walkmod can be used as a gradle/maven plugin. Would this work for you at mid term? You can see the benefit of the tool first. There is an Eclipse plugin I created some time ago, but I would not want to spend time on it before you check if walkmod is useful for you.

**Comment by dreis2211** [comment]
Isn't that superseded by now with the spring-javaformat plugin?

**Comment by snicoll** [comment]
I [wonder the same](https://github.com/spring-projects/spring-boot/issues/1817#issuecomment-333385559). Flagging for team attention to see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
Yeah, I think we can close this on. Thanks, @dreis2211.
