### ISSUE TITLE
Need @LocalServerPort for random RSocket port

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#18179]
In tests, when I set `spring.rsocket.server.port=0`, I'd like to be able to resolve the port to make requests.

**Comment by eddumelendez** [comment]
I can work on this :) some friends are starting contributing and I can work this one with them

**Comment by snicoll** [comment]
Thanks @eddumelendez

**Comment by eddumelendez** [comment]
an update about this issue. this will be worked by @veronicavasq and we will submit the PR this week

**Comment by philwebb** [comment]
Great. Thanks @veronicavasq!

**Comment by mbhave** [comment]
Closing in favor of PR #18287.
