### ISSUE TITLE
HealthIndicatorRegistry bean is no longer available

### ISSUE THREAD

**Issue by krm1312** [spring-projects/spring-boot#18194]
The (standard I assume) solution to expose the health endpoint to micrometer does not seem to work in 2.2.0.M6.  A lot of the classes are deprecated (as indicated in release notes), but, it fails to start.

http://micrometer.io/docs/guide/healthAsGauge

```

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.acme.app.metrics.HealthMetricsConfig required a bean of type 'org.springframework.boot.actuate.health.HealthIndicatorRegistry' that could not be found.
```

Not sure if you want to make it work as is (with deprecated classes/beans) or update micrometer recipe.

**Comment by krm1312** [comment]
Actually, it looks like maybe I changed it for a previous upgrade a bit.  This is what we currently have:

```
@Configuration
public class HealthMetricsConfig {

    private CompositeHealthIndicator healthIndicator;

    /**
     * Configure gauge representing spring boot health indicator.
     */
    public HealthMetricsConfig(HealthAggregator healthAggregator,
                               HealthIndicatorRegistry healthIndicatorRegistry,
                               List<HealthIndicator> healthIndicators,
                               MeterRegistry registry) {

        healthIndicator = new CompositeHealthIndicator(healthAggregator, healthIndicatorRegistry);

        for (int i = 0; i < healthIndicators.size(); i++) {
            healthIndicatorRegistry.register(Integer.toString(i), healthIndicators.get(i));
        }

        // presumes there is a common tag applied elsewhere that adds tags for app, etc.
        Gauge.builder("health", healthIndicator, health -> {
            Status status = health.health().getStatus();
            switch (status.getCode()) {
                case "UP":
                    return 3;
                case "OUT_OF_SERVICE":
                    return 2;
                case "DOWN":
                    return 1;
                case "UNKNOWN":
                default:
                    return 0;
            }
        }).description("Spring boot health indicator.  3=UP, 2=OUT_OF_SERVICE, 1=DOWN, 0=UNKNOWN")
            .register(registry);
    }

}```

**Comment by philwebb** [comment]
Thanks, I think we're missing a `HealthIndicatorRegistry` bean in our auto-configuration.

**Comment by snicoll** [comment]
@philwebb I am not sure why that is. This is deprecated in favour of `HealthContributorRegistry` and that bean is exposed so I don't understand why the regression might come from.

**Comment by wilkinsona** [comment]
Isn't the Micrometer documentation just indicative of a general backwards compatibility problem? If we can provide a `HealthIndicatorRegistry` that maps onto the `HealthContributorRegistry` I think it makes sense to do so.

**Comment by philwebb** [comment]
Fixed in d7a472b8a6c90ce72447cb0439211f45ddb76889 (accidentally attributed to #16903)

**Comment by snicoll** [comment]
`HealthProperties` is again a `@Bean` with its `@ConfigurationProperties` on the target class rather than on the bean definition. This won't cause any trouble now that it doesn't have a constructor anymore but the bean is still a bit odd though, probably an oversight. I've polished that in 3c8402f

**Comment by philwebb** [comment]
Thanks, it was an oversight left over when I was trying to fix an ordering issue.

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer-docs/pull/100 to add a sample health metrics configuration for Spring Boot 2.2 in the Micrometer reference docs. However, I might miss something as it does seem to be more verbose than before to achieve the same thing.

**Comment by snicoll** [comment]
Thanks for the feedback @izeye, we agree and I've created an issue to see if there is something we can do about it: https://github.com/spring-projects/spring-boot/issues/18712
