### ISSUE TITLE
Tomcat not returning HTTP 400 

### ISSUE THREAD

**Issue by shakhal** [spring-projects/spring-boot#18197]
Using SpringBoot 2.1.8.RELEASE
Java openjdk 12.0.2

Having controller that returns 400
```
    @GetMapping(path = "/return400")
    public ResponseEntity return400() {
        return ResponseEntity.badRequest().build();
    }
```

When springboot is configured to use default Tomcat server
```
$ curl http://localhost:8080/return400 -i
```
returns:
```
curl: (52) Empty reply from server
```

But when configured to use Jetty
```
$ curl http://localhost:8080/return400 -i
```

returns:
```
HTTP/1.1 400 Bad Request
Date: Tue, 10 Sep 2019 20:36:48 GMT
Content-Length: 0
```

I created two simple duplicate projects to demonstrate this, one using Tomcat
other uses Jetty.

https://github.com/shakhal/springboot-jetty
https://github.com/shakhal/springboot-tomcat

I hope somebody can shed some light.

Other HTTP codes seem to work

**Comment by wilkinsona** [comment]
Thanks for the samples. Unfortunately, I have been unable to reproduce the behaviour that you have described. Here is the response from the Tomcat sample using JDK 12:

```
$ curl -i localhost:8080/return400
HTTP/1.1 400 
Content-Length: 0
Date: Wed, 11 Sep 2019 07:56:48 GMT
Connection: close
```

I wonder if you have something running on your machine that is proxying HTTP calls and changing the response? We have seen this in the past with some anti-virus software, for example.

If you would like us to spend some more time investigating, can you please describe your environment and how you are building and running the sample in as much detail as possible.

**Comment by shakhal** [comment]
Hey Andy,

Thanks for taking the time to verify this.
I tried with other teammates and they had the same issue,
some got the `empty reply` only after the second `curl`.

Anyways, glad to hear it's probably not a real issue, I will try to track it down, maybe an anti-virus indeed.

Thanks!

**Comment by snicoll** [comment]
Thanks for letting us know.
