### ISSUE TITLE
Spring Boot when to support Graphql

### ISSUE THREAD

**Issue by songzeyang** [spring-projects/spring-boot#18201]
When will the community support Graphql

**Comment by songzeyang** [comment]
When will the community support it

**Comment by wilkinsona** [comment]
We have no current plans for first-party support for GraphQL. A [third-party project](https://github.com/graphql-java/graphql-spring-boot), listed [here](https://github.com/graphql-java-kickstart/graphql-spring-boot), already exists.

If you have any further questions, please follow up on [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by songzeyang** [comment]
Sorry




| |
宋泽洋
|
|
邮箱：17600028368@163.com
|

签名由 网易邮箱大师 定制

On 09/11/2019 14:38, Andy Wilkinson wrote:

We have no current plans for first-party support for GraphQL. A third-party project, listed here, already exists.

If you have any further questions, please follow up on Gitter. As mentioned in the guidelines for contributing, we prefer to use GitHub issues only for bugs and enhancements.
