### ISSUE TITLE
Provide dependency management for Awaitility

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#18205]
A common use case for `@ExtendWith(OutputCaptureExtension.class)` is to wait for some text to appear in logs, signifying that something happened in the app under test, but not accessible to direct monitoring via an API. It would be useful to have methods or utilities that directly knew about how to do this as quickly as possible, e.g.

```java
	@Test
	public void contextLoads(CapturedOutput output) throws Exception {
		output.waitFor("bar", Duration.ofSeconds(10));
		assertThat(output.getErr()).doesNotContain("foo");
	}
```

**Comment by dsyer** [comment]
I guess a utility (e.g. in Spring Framework)  would work - turning the example above into a method call:

```java
	@Test
	public void contextLoads(CapturedOutput output) throws Exception {
		Timeouts.waitFor(() -> assertThat(output.getErr()).contains("bar")), Duration.ofSeconds(10));
		assertThat(output.getErr()).doesNotContain("foo");
	}
```

Cf Guava `TimeLimiter` for similar features.

**Comment by dsyer** [comment]
Nevermind. Found it in JUnit:

```java
	@Test
	public void contextLoads(CapturedOutput output) throws Exception {
		assertTimeout(Duration.ofSeconds(10), () -> assertThat(output.getErr()).contains("bar")));
		assertThat(output.getErr()).doesNotContain("foo");
	}
```

**Comment by dsyer** [comment]
Here's one that works:

```java
	private RetryTemplate retry = new RetryTemplate();

	{
		retry.setBackOffPolicy(new ExponentialBackOffPolicy());
	}

	@Test
	public void contextLoads(CapturedOutput output) throws Exception {
		assertThat(retry.execute(context -> output.getErr().contains("bar"))
				.booleanValue()).isTrue();
		assertThat(output.getErr()).doesNotContain("foo");
	}
```

**Comment by wilkinsona** [comment]
For a test involving multiple threads, there's a race condition between the first and second assertion. I wonder if an API that calls the supplier repeatedly until a condition is met, and then passes the same value from the supplier for further checks would be better? Here's a simplified example that ignores timeout/back-off etc:

```java
@Test
void example() {
	await(this.output::getOut, (out) -> out.contains("bar"), (out) -> assertThat(out).contains("foo"));
}

public static <T> void await(Supplier<T> supplier, Predicate<T> predicate, Consumer<T> consumer) {
	T value = supplier.get();
	while (!predicate.test(value)) {
		value = supplier.get();
	}
	consumer.accept(value);
}
```

This feels like a general purpose testing utility rather than something that should be coupled to output capture. As such, it feels better suited to being in JUnit, AssertJ, or even Framework.

**Comment by wilkinsona** [comment]
And now that my memory has stopped failing me, this is what [Awaitility](https://github.com/awaitility/awaitility) does, just with slightly different syntax. I think we'd be reinventing (part of) the wheel if we did anything here.

**Comment by dsyer** [comment]
Or you could fold the `Consumer` into the test by just asserting on the result:

```
@Test
void example() {
	 assertThat(await(this.output::getOut, (out) -> out.contains("bar")).contains("foo");
}

public static <T> T await(Supplier<T> supplier, Predicate<T> predicate, Consumer<T> consumer) {
	T value = supplier.get();
	while (!predicate.test(value)) {
		// omit timeout and backoff
		value = supplier.get();
	}
	return value;
}
```

**Comment by wilkinsona** [comment]
Yep. FWIW, that's exactly what Awaitility does. See [`<T> T until(Callable<T> supplier,
                   Predicate<? super T> predicate)`](https://static.javadoc.io/org.awaitility/awaitility/4.0.1/org/awaitility/core/ConditionFactory.html#until-java.util.concurrent.Callable-java.util.function.Predicate-) for example.

**Comment by dsyer** [comment]
Any chance we could use Awaitility in Boot, so we can get the dependency version in our BOM?

**Comment by wilkinsona** [comment]
We can certainly consider it. We do have some tests where it would be useful.

**Comment by wilkinsona** [comment]
We need to look at its `junit:junit` dependency a bit. We may need to exclude it and perhaps raise an issue for it to be made optional.

**Comment by dsyer** [comment]
Makes sense that it should be optional. FWIW I'm including awaitility at version 4.0.1 and it hasn't broken anything yet (Spring Boot is still managing the junit version for me).

**Comment by snicoll** [comment]
We are considering the option to add Awaitility now or in the future in the test starter. As I suspect we'll remove the `vintage-engine` at some point, it would be a problem if `Awaitility` requires `junit:junit`. Given that we are heading towards JUnit Jupiter with Junit 4 as a potential solution, we need to be careful about adding a dependency that absolutely require it.

**Comment by dsyer** [comment]
I did a quick scan of the imports in the classes I'm using and none of them imports `org.junit.*`. As far as I can see Junit is only used in tests in Awaitility (https://github.com/awaitility/awaitility/search?p=3&q=%22import+org.junit%22&unscoped_q=%22import+org.junit%22).

**Comment by wilkinsona** [comment]
The project builds cleanly with the `junit:junit` dependencies moved to test scope. I'm working on a PR.
