### ISSUE TITLE
Duplicate metrics can be recorded by WebMvcTags since it does not rationalize trailing slashes

### ISSUE THREAD

**Issue by rswart** [spring-projects/spring-boot#18207]
The `WebMvcMetricsFilter` uses the `HandlerMapping.BEST_MATCHING_HANDLER_ATTRIBUTE` to determine which handler the metric should be labeled with.

Since `useTrailingSlashMatch` is true by default most mvc controllers configured with a request mapping like:

```java
@GetMapping(path = "/foo", produces = {MediaType.APPLICATION_JSON_VALUE})
```

will match both `/foo` and `/foo/` and as a result `BEST_MATCHING_HANDLER_ATTRIBUTE` for this request mapping can have 2 values.   

This leads to split metrics for the same request mapping: one for `/foo` and one for `/foo/`. 

For now I have worked around this with a `MeterRegistryCustomizer` that strips the trailing slash, but I wonder if this does not deserve a more structural solution, e.g inside the metrics filter itself.

**Comment by bclozel** [comment]
The team decided to strip trailing slashes in our metrics filter, but still offer a configuration property in case trailing slashes are meaningful for some applications.
