### ISSUE TITLE
MongoTemplate#count does not use hinted index

### ISSUE THREAD

**Issue by huantt** [spring-projects/spring-boot#18202]
![image](https://user-images.githubusercontent.com/19801770/64669084-5f3e3b00-d48a-11e9-8015-909f746c88b1.png)
In count method, you don't put my hint from Query into CountOptions. So the index hinted in Query is not applied in count method.

### How to reproduce:
```groovy
        Query query = new Query(Criteria.where("country_code").is("Viet Nam"))
        query.withHint("does_not_exist_index")
        long count = mongoTemplate.count(query,"users")
```
In this case, if MongoTemplate#count use hinted index, I expected an error likes `error planner returned error: bad hint`, however have no error

**Comment by wilkinsona** [comment]
Thanks for the report, but `MongoTemplate` is not part of Spring Boot itself. It is part of the Spring Data MongoDB project which uses [JIRA](https://jira.spring.io/projects/DATAMONGO) for issue tracking. Can you please open a JIRA ticket and comment here with a link to it?

**Comment by huantt** [comment]
Ok thank you.

**Comment by huantt** [comment]
I've just created a new issue: https://jira.spring.io/browse/DATAMONGO-2360
