### ISSUE TITLE
Document relaxed binding from environment variables

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#18215]
> If you use environment variables rather than system properties, most operating systems disallow period-separated key names, but you can use underscores instead (for example, SPRING_CONFIG_NAME instead of spring.config.name).

table 24.1 partially addresses this, but isn't nearby, and doesn't include the array/map syntax. Honestly I think the information is probably all there, it's just hard to find because it's scattered about. It's also hard to google. Links could be another solution, just needs to be easier to find this information and for it to be centralized in one spot, as well as including the array/map syntax.

**Comment by philwebb** [comment]
@rajputvishwas Thanks for the offer of help but I'm not sure what needs to change just yet. Unfortunately I won't have time to review this for a while.
