### ISSUE TITLE
Allow Customization of SpringLiquibase Bean

### ISSUE THREAD

**Issue by aegliv** [spring-projects/spring-boot#18224]
Hello, this is an enhancement suggestion (I'm happy to provide a PR if you can guide me on how to best implement it in proper Spring style).

### Problem Statement
As part of #9218, the `DataSourceClosingSpringLiquibase` class was added, which extends the original  `liquibase.integration.spring.SpringLiquibase` class. I'm happy with Spring's `DataSourceClosingSpringLiquibase`, however I want to make changes to the way Liquibase is initialized and the migration is performed.

Right now, the  `LiquibaseAutoConfiguration`  class has a heavy setup and instantiates the `DataSourceClosingSpringLiquibase` class in a private method:

https://github.com/spring-projects/spring-boot/blob/b5589f8abec3e033515b320653f20bd2702f928e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L113-L124

To achieve my goal, I currently have to copy the contents of the whole `LiquibaseAutoConfiguration` class (as well as `LiquibaseSchemaManagementProvider`, since is package-private?) to swap out your `DataSourceClosingSpringLiquibase` class for my custom one.

### Suggestion
Change `LiquibaseAutoConfiguration` so that it accepts a `SpringLiquibaseFactory` which is used to instantiate `SpringLiquibase` classes. Then I only had to provide my own Factory in my Application which feels more Spring like

**Comment by philwebb** [comment]
The `SpringLiquibaseFactory` would need to be in `org.springframework.boot.autoconfigure.liquibase` but it would be a little more complex than a regular factory. If you look at `LiquibaseAutoConfiguration.createSpringLiquibase` you'll see that `DataSourceClosingSpringLiquibase` is only used when a new `DataSource` is opened. If the `DataSource` is a bean then a regular `SpringLiquibase` is used.

To be honest, I'm not sure how common it is to want a custom `SpringLiquibase` subclass. I'll flag this one for team attention to see if others from the team think the factory is a good idea or not. It might be the case that copy/paste of the auto-configuration is the best option.

**Comment by aegliv** [comment]
Thanks for reaching out!

**Comment by philwebb** [comment]
We discussed this a little today as team and currently feel that adding an extra factory will add quite a lot of complexity that most users probably won't need. I hate to suggest copy/paste code, but in this case I think it's best for you to duplicate the code from `LiquibaseAutoConfiguration` in your own project.
