### ISSUE TITLE
Clarify scope of "@SpringBootTest#classes"

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#18229]
I found this test passes:

```java
@SpringBootTest(classes = RestTemplate.class)
class MyTest {

    @Autowired
    RestTemplate restTemplate;

    @Test
    void check() {
        assertThat(restTemplate).isNotNull();
    }
}
```

The underlying reason is same as what I reported here: https://github.com/spring-projects/spring-framework/issues/23638

Since spring-boot is more opinionated, I think it makes sense to restrict `@SpringBootTest#classes` for only `@Configuration` classes.

`SpringBootTestContextBootstrapper` may filter out non `@Configuration` classes or throw exception when it constructs `MergedContextConfiguration`.

**Comment by snicoll** [comment]
Thanks for the suggestion but I don't think we should restrict `classes` to be configuration classes. However, I can see the "annotated classes" part was copied from what the documentation for `@ContextConfiguration` states. We're polishing that in https://github.com/spring-projects/spring-boot/issues/18230 and should apply the same here.

**Comment by sbrannen** [comment]
FYI: https://github.com/spring-projects/spring-framework/issues/23638 has been resolved.

**Comment by snicoll** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/e4ba6049ff0ff2578ce7b99f7917d4cfb0928c8d
