### ISSUE TITLE
Restrict `@ImportAutoConfiguration` to only take @Configuration classes

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#18230]
I found this code in real world:

```java
@ExtendWith({MockitoExtension.class, SpringExtension.class})
@ImportAutoConfiguration(classes = {ResourceBundleMessageSource.class, MyService.class,
        MyExceptionHandler.class, MyPropertyConfiguration.class, RestTemplate.class})
public class MyExceptionHandlerTest {
}
```

It's pretty much wrong in usage, but this works because `@ImportAutoConfiguration` accepts any classes.

I believe it would be better that `ImportAutoConfigurationImportSelector` filters out or throw exception when non `@Configuration` or even non auto configuration beans are specified.

Relates to:
- https://github.com/spring-projects/spring-boot/issues/18229
- https://github.com/spring-projects/spring-framework/issues/23638

**Comment by philwebb** [comment]
There's no hard requirement for the classes to actually be annotated with `@Configuration` so I'm not sure that we can enforce this without potentially breaking back compatibly. I think we need to leave things as they are unfortunately.
