### ISSUE TITLE
Add support for X-Forwarded-Host using Tomcat's new RemoteIpValve hostHeader attribute

### ISSUE THREAD

**Issue by NFarrington** [spring-projects/spring-boot#18233]
Tomcat now supports the `X-Forwarded-Host` header, per https://bz.apache.org/bugzilla/show_bug.cgi?id=57665 (as referenced in #5677).

It would be great to add support for this in order to enable a more complete support for X-Forwarded-* headers without needing to use the `ForwardedHeaderFilter`, and to provide closer feature parity with what's available in `RemoteIpValve`.

The current (Spring Boot 2.1.8.RELEASE) `RemoteIpValve` configuration can be found here:
https://github.com/spring-projects/spring-boot/blob/b1ca1ae6e948a5f2da823687a10323b6611d8d2e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/TomcatWebServerFactoryCustomizer.java#L146-L166

**Comment by philwebb** [comment]
This is the relevant Tomcat commit: https://github.com/apache/tomcat/commit/67c3af97230135af8f6f7566c77a79a69722a713
