### ISSUE TITLE
Upgrade to HttpClient 4.5.10

### ISSUE THREAD

**Issue by juliojgd** [spring-projects/spring-boot#18235]
https://github.com/spring-projects/spring-boot/blob/ad326036353112e938166b5b59dcaf643e949c1d/spring-boot-project/spring-boot-dependencies/pom.xml#L81

I think Httpclient version should be upgraded to 4.5.10, because 4.5.9 introduced a bug https://issues.apache.org/jira/browse/HTTPCLIENT-1997 that is causing problems with SSL certificates. This bug affected to us and we had to overwrite version downgrading to 4.5.8.
Now we are upgrading to 4.5.10 as this new version solves the bug.

I think this must be done for 2.2 RC and for 4.1.9. If you agree I can send the PR.

**Comment by philwebb** [comment]
Thanks but we have a semi-automated process to upgrade dependencies. We'll process this in due course and therefore don't need an issue for it.

**Comment by juliojgd** [comment]
Ok, but I think this should be upgraded before GA release of Spring Boot 2.2 as the bug referenced is causing problems with secure communications (TLS) and should be avoided in SB.
Regards,
