### ISSUE TITLE
spring-boot-devtools: auto reload not work with kotlin on Eclipse

### ISSUE THREAD

**Issue by shirosaki** [spring-projects/spring-boot#18245]
I create a spring boot project using kotlin and java with spring-boot-devtools.
I can build the project in Eclipse with kotlin plugin.
I can run the application in Eclipse from Application.kt file which contains main function.

The application is auto reloaded when a java file is modified, but not reloaded when a kotlin file is modified.

It should be auto reloaded when a kotlin file is modified.

Is it a bug of spring-boot-devtools or eclipse plugin?

When I use IntejiJ IDEA community instead of Eclipse, auto reload works fine.

**Comment by snicoll** [comment]
> When I use IntejiJ IDEA community instead of Eclipse, auto reload works fine.

This is a good sign this is the wrong place to report the issue. Devtools does nothing more than scanning the classpath and checking if a `.class` file has changed. Whatever IDE you are using is responsible to update the classpath when you invoke the build action. Perhaps this is a question about how to use the Eclipse Kotlin plugin? 

I am going to close this now and suggest you first ask on StackOverflow. If you believe this is a bug in the Eclipse integration, please create an issue in their issue tracker.

**Comment by shirosaki** [comment]
Thanks for comments.
The Jetbrains Kotlin compiler in Eclipse outputs to a hidden folder inside the Eclipse compiler plugin.
So it seems that devtools cannot access `.class` file in the hidden folder.

https://stackoverflow.com/questions/36248021/output-folder-of-the-kotlin-compiler-in-eclipse

Kotlin Eclipse plugin cannot output `.class` to file system folder folder, then auto reload cannot be possible?

**Comment by wilkinsona** [comment]
> Kotlin Eclipse plugin cannot output .class to file system folder folder, then auto reload cannot be possible?

Correct.
