### ISSUE TITLE
NoSuchMethodError in WebSocketMessageBrokerConfigurationSupport

### ISSUE THREAD

**Issue by nitin-** [spring-projects/spring-boot#18243]
> messageBrokerTaskScheduler method is missing in class file WebSocketMessageBrokerConfigurationSupport Hence throwing an error 

java.lang.NoSuchMethodError: 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurationSupport.messageBrokerTaskScheduler()'

**Comment by nitin-** [comment]
@spring-issuemaster Please take an immediate action

**Comment by spencergibb** [comment]
You likely have mismatched versions of spring

**Comment by snicoll** [comment]
@nitin- this is likely a broken setup on your end with mismatched versions of Spring. To be sure, please share a minimal sample that we can run and reproduces the issue. Pasting incomplete stacktrace is not helping us helping you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
