### ISSUE TITLE
Improve documentation about RedisCacheConfiguration (1.5 -> 2.0 migration)

### ISSUE THREAD

**Issue by joaoqalves** [spring-projects/spring-boot#18250]
During a migration from Spring Boot 1.5.x to 2.x, I found that the default behavior for `RedisCacheManager` changes. Before, `cacheNullValues` default was `false` and now its default is `true`. 

Perhaps, in the Migration wiki we could add the following to the `Caching` section:

```asciidoc

=== `RedisCacheManager`

NOTE: When upgrading to Spring Data Redis 2.x, the new default value for `cacheNullValues` is `true`. Before, this value's default was `false`. Therefore, you might want to double-check the new configuration.

```

**Comment by snicoll** [comment]
@joaoqalves thanks for reporting it. This is part of Spring Data Redis and we can't document every change like this. It is true however that the redis cache manager implementation has changed significantly so I've added a note with a link to the reference documentation, see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#rediscachemanager

**Comment by joaoqalves** [comment]
@snicoll This helps! Thanks for taking care of it!
