### ISSUE TITLE
SpringBoot Liquibase autoconfiguration and rollbacks

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#1826]
Hi!

As suggested on Twitter I'm pushing the question here.

The question is - with Liqiubase autoconfiguration we can easilly make Liquibase read the changesets and apply all the necessary changes. That's awesome :) 

Now let's assume that we have an application that has already applied one changeset (let's call it "1" and the JAR version is 1.0.0) and we've done a deploy and have applied Liquibase changes comprising of two changesets (let's call them "2" and "3" and the JAR version is 1.1.0 ). Now on production it turned out that our application doesn't work the way it should. We would like to downgrade the application from version 1.1.0 to 1.0.0. That means we would like to rollback the liqubase changes from "3" to "1". Of course it's feasible by using the Liquibase scripts but my question is - is it possible to start our Spring Boot application in such a way to tell JAR version 1.1.0 to rollback the changesets "3" and "2" and then normally deploy version 1.0.0?

**Comment by marcingrzejszczak** [comment]
Anything new on this matter? ;) Or should we start thinking of creating a PR? :)

**Comment by philwebb** [comment]
A PR would be most welcome. We're still primarily working on the 1.2.x branch so we've not really started looking at enhancements just yet.

**Comment by gazal-k** [comment]
:+1:

**Comment by gazal-k** [comment]
I think `SpringLiquibase.rollbackFile` property might be what we need. From what I understood by looking at the code, if we set that property, liquibase will generate a rollback file when updating the database.

Later, when we want to rollback, I guess we could just execute the generated rollback files.

**Comment by alxll** [comment]
Hi,

For now I can generate the rollback script - that is Ok. But how I can execute this script? manually? useing liquidbase command line tool? Or any possibility to use spring boot integrations?

**Comment by gazal-k** [comment]
The rollback script is a regular .sql file. You can execute it directly on the database which you need to rollback.

**Comment by alxll** [comment]
Of course I can execute the regular sql file "directly on the database"! But... at the same time the following is also true:

1) I can execude any database change sets "directly on the database" as well as rollback script stored as sql script - I can do it without liquidbase and without spring boot. 

2) generated rollback script contains full list of rollbacks for all incrementally applied change sets. so I cannot just "execute it directly on the database" if I want to rollback only last change set (or only last few change sets) - I have to open this file and manually copy required SQL commands for execution 

But it there is no any other options... I have to just accept it as is...

**Comment by gazal-k** [comment]
Sorry, I didn't understand your question earlier.
I think I would approach the problem like this:

Say you are currently running an application v1.0.0.
You upgrade to v1.0.1 and the corresponding db changes are done by liquibase, also generating a rollback file. (You can configure the location and file name using some nifty SPEL).
Now, in the eventuality that you need to revert the upgrade, run the rollback file created for v1.0.1.

This still doesn't solve your requirement of rollback of a few of those changes. Liquibase does have this capability, but I'm not sure how exactly it can be accommodated into spring-boot. The rollback file creation is automatic, because it can be done while starting your application. But how do we determine when to actually rollback a few changes?

**Comment by alxll** [comment]
>>Say you are currently running an application v1.0.0.
You upgrade to v1.0.1 and the corresponding db changes are done by liquibase, also generating a rollback file.

Hmm...  when I do that I have rollback sql file containting rollbacks for both v1.0.0 and v1.0.1 (and from my point of view it looks very reasonable - the sql file commented well and it is really possible to get one or more rollbacks for any number of change sets applied analizing comments mannualy or atomatically)

>>I'm not sure how exactly it can be accommodated into spring-boot.

Well... The first what coming to my head is run the existing application jar (or war) with specified parameter. In some specific parameter exists, the application just executes rollback script and exits... 

e.g. if you have a spring boot application "my-spring-boot-app.jar"  you may run it as:
java -jar my-spring-boot-app.jar
and some change sets will be aplied against the database configured in apring application. the rollback file "./my-spring-boot-app-rooback.sql" will be generated Then you may run the command:

java -jar -Dliquidbase.rollback.tag=v1.0.0 -Dliquidbase.rollback.file=my-spring-boot-app-rooback.sql my-spring-boot-app.jar

this will select all SQL commands preceding v1.0.0 and then execute it. and the application will exit... 

something like that.. propably I will do that in my applicattion...but I understand that this looks ugly.. but more logical and more convinient than have just SQL file without database connection parameters

**Comment by gazal-k** [comment]
> Hmm... when I do that I have rollback sql file containting rollbacks for both v1.0.0 and v1.0.1 (and from my point of view it looks very reasonable - the sql file commented well and it is really possible to get one or more rollbacks for any number of change sets applied analizing comments mannualy or atomatically)

Actually, if I upgrade to 1.0.1 from 1.0.0, only the rollbacks for 1.0.1 will be present in the latest rollback file. Every release would have its own rollback file.

**Comment by alxll** [comment]
Propably I did something NOT right but I have exactly I what described:

-- *********************************************************************
-- SQL to roll back currently unexecuted changes
-- *********************************************************************
-- Change Log: classpath:/db/changelog/db.changelog-master.yaml
-- Ran at: 5/9/16 10:59 AM
-- Against: ssuser@jdbc:postgresql://localhost:5432/liquidbase_test_db
-- Liquibase version: 3.4.2
-- *********************************************************************

-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'alxll (192.168.99.1)', LOCKGRANTED = '2016-05-09 10:59:49.046' WHERE ID = 1 AND LOCKED = FALSE;

-- Rolling Back ChangeSet: classpath:/db/changelog/v-2.0/_changelog-v.2.0-cumulative.yaml::v-2.0::alxll
set schema 'test_schema';

drop table test;

DELETE FROM public.databasechangelog WHERE ID = 'v-2.0' AND AUTHOR = 'alxll' AND FILENAME = 'classpath:/db/changelog/v-2.0/_changelog-v.2.0-cumulative.yaml';

-- Rolling Back ChangeSet: classpath:/db/changelog/v-1.0/_changelog-v.1.0-cumulative.yaml::v-1.0::alxll
set schema 'test_schema';

DROP TABLE some_table_01;

DROP TABLE some_table_02;
.......................

**Comment by alxll** [comment]
db.changelog-master.yaml 
__________________________________
databaseChangeLog:
  - include:
      file: v-1.0/_changelog-v.1.0-cumulative.yaml
      relativeToChangelogFile: true
  - include:
      file: v-2.0/_changelog-v.2.0-cumulative.yaml
      relativeToChangelogFile: true
_____________________________________

_changelog-v.1.0-cumulative.yaml 
___________________________________
databaseChangeLog:
  - changeSet:
      id: v-1.0
      author: alxll
      changes:
        - sqlFile:
            path: create_tables_intexes.sql 
            encoding: utf8
            relativeToChangelogFile: true
        - sqlFile:
            path: create_index_tables.sql
            encoding: utf8
            relativeToChangelogFile: true
        - sqlFile:
            path: spatial_indexes.sql
            encoding: utf8
            relativeToChangelogFile: true
        - sqlFile:
            path: sequences.sql
            encoding: utf8
            relativeToChangelogFile: true
      rollback:
        - sqlFile:
            path: drop_tables.sql
            encoding: utf8
            relativeToChangelogFile: true

**Comment by zskr** [comment]
Looks like part of the original question is still unresolved. "is it possible to start our Spring Boot application in such a way to tell JAR version 1.1.0 to rollback the changesets "3" and "2" and then normally deploy version 1.0.0?"

I am also facing the same issue when using blue green deployment. I want to downgrade my application if the green deployment is not working. How do we rollback the DB changes when we downgrade an application version?. Since we have used spring boot + liquibase to upgrade the DB, could we somehow tell the application to rollback the changes when we stop the application.

**Comment by philwebb** [comment]
@zskr This issue has been closed since 2016. If you think you've found a new bug please open a new issue and provide a small sample that replicates it. If you have a general question, please ask on stackoverflow.com
