### ISSUE TITLE
Update QuartzDataSourceInitializerTests.commentPrefixCanBeCustomized to use a custom prefix that isn't covered by the default

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18275]
The test uses `##` as the custom prefix, but this is covered by the default of `#`. As a result the test passes without setting `spring.quartz.jdbc.comment-prefix=##`.

**Comment by adiohana** [comment]
@wilkinsona I created #18285 for this. 
please let me know if that's what you meant.

**Comment by wilkinsona** [comment]
Closing in favour of #18285.
