### ISSUE TITLE
Dead link (404) in Spring Boot 2.0 Migration Guide

### ISSUE THREAD

**Issue by rweisleder** [spring-projects/spring-boot#18273]
The section [Relaxed Binding](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#relaxed-binding) links to the reference guide (link "have been tightened" in the first paragraph), but this link results in a 404.

Maybe related to the [last change](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide/_compare/24dd2cdcd4f7b0d3d7e9565ee8cc1c7635dee343...f0a01faefcf930d9fb2e57873a140a3a9eb7aeed)?

**Comment by snicoll** [comment]
@rweisleder looks like some things were polished there yes. Thanks for reporting it!

**Comment by snicoll** [comment]
I've fixed the links in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide/_compare/f0a01faefcf930d9fb2e57873a140a3a9eb7aeed...7becbe3fa66c5aedf2a12fab61f6dceae495aa04
