### ISSUE TITLE
When JAR was build on Windows, the launch script embedded in JAR file can not be started

### ISSUE THREAD

**Issue by skyline75489** [spring-projects/spring-boot#18280]
Due to Windows line ending, the script fails to start in bash:

```plaintext
-bash: ./application.jar: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by wilkinsona** [comment]
Thanks for the report, but we'll need some more information to be able to diagnose the problem. 

- How are you building the jar? Both the Maven and Gradle plugins read and write the scripts as a stream of bytes so the script should be written as-is into the jar with no changes to line endings.
- Are you using the default launch script or a custom script?
- What versions of Windows and bash are you using? Is this a Linux subsystem running within Windows?

**Comment by skyline75489** [comment]
Thanks for the feedback. We are indeed using a modified version of launch script (which I didn't realized until now). I just tested this with a pure Spring Boot project without modification. It turns out the line ending is good.

**Comment by snicoll** [comment]
Thanks for letting us know.
