### ISSUE TITLE
Support of incremental mode in ConfigurationMetadataAnnotationProcessor

### ISSUE THREAD

**Issue by frost13it** [spring-projects/spring-boot#18282]
The `ConfigurationMetadataAnnotationProcessor` should support incremental annotation processing.
At the moment (2.1.8.RELEASE and 2.2.0.M6) in a Gradle project with Kotlin and kapt the following warning is displayed on build:
```
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor (NON_INCREMENTAL).
```

There are many annotation processors that support incremental mode, some of them are listed [here](https://docs.gradle.org/current/userguide/java_plugin.html#state_of_support_in_popular_annotation_processors).

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately this isn't possible due to a limitation in Gradle. Please see https://github.com/spring-projects/spring-boot/pull/16603#issuecomment-486164149 for details.

**Comment by frost13it** [comment]
Thanks for response and sorry for my failure to find the similar issue.

**Comment by mattdkerr** [comment]
Is this now possible in Gradle 6.0?

**Comment by wilkinsona** [comment]
@mattdkerr Please don't make essentially the same comment on multiple issues, particularly when one is already marked as a duplicate of the other. It creates unnecessary noise for everyone watching the repository.
