### ISSUE TITLE
Group together properties related to Tomcat's RemoteIpValve

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18302]
We have six properties that all relate to the configuration of Tomcat's `RemoteIpValve`:

- `server.tomcat.host-header`
- `server.tomcat.internal-proxies`
- `server.tomcat.protocol-header`
- `server.tomcat.protocol-header-https-value`
- `server.tomcat.port-header`
- `server.tomcat.remote-ip-header`

They aren't grouped and sit alongside several other properties related to various other areas of Tomcat (threading, connection handling, URI encoding, TLD scanning, etc.). This is becoming increasingly unwieldy. For example, we may want to provide configuration properties for `RemoteIpValve`'s `changeLocalName` and `changeLocalPort` properties and naming them succinctly while making their purpose clear is harder than it needs to be at the moment.

**Comment by eddumelendez** [comment]
@wilkinsona I would like to take this one and may will work with a friend. Is this just about grouping the properties. I think they should be also backward compatible right?

**Comment by wilkinsona** [comment]
Yes, that's right. We should move the properties listed above into a new group in a way that is backwards compatible.

**Comment by eddumelendez** [comment]
thanks @wilkinsona! I will work on this with @manduinca

**Comment by manduinca** [comment]
Great @eddumelendez, let’s get to work.

**Comment by mbhave** [comment]
Closing in favor of PR #18489.
