### ISSUE TITLE
Don't require actuator to customize MeterRegistry

### ISSUE THREAD

**Issue by codefromthecrypt** [spring-projects/spring-boot#18304]
Right now, customization of Micrometer's MeterRegistry requires loading of the following actuator class: `org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer`

Since `MeterRegistry` is a core type of micrometer, it should be possible to configure this even if actuator is not in the classpath.

I'm not sure if the issue is better here or on micrometer itself, so feel free to tell me to move it.

One path is to copy the type MeterRegistryCustomizer into a core package and backport the actuator one to extend it.

**Comment by snicoll** [comment]
@adriancole I am not sure I got that. `MeterRegistryCustomizer` is actually processed by the actuator auto-configuration so moving the type would leave you with a callback that nobody would actually invoke.

**Comment by adriancole** [comment]
Main point is that micrometer can be in use without actuator, so you are right it doesn't make sense unless the config that processes it is also refactored.

**Comment by snicoll** [comment]
Point taken. We've actually discussed this in the past but I am going to flag this to give it another go.

**Comment by wilkinsona** [comment]
This is now possible in Spring Boot 4.0 with `MeterRegistryCustomizer` moving to the new `spring-boot-metrics` module that does not require Actuator.
