### ISSUE TITLE
Support block based image banner pixels

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18301]
With #18264 merged, many image banners would look better with unicode block chars rather than letters. It might be nice to offer this as an option.

**Comment by wilkinsona** [comment]
The test introduced in https://github.com/spring-projects/spring-boot/commit/303974fde976f833e73b3fd1b552d51a09a4f085 is failing on Concourse:

```
08:54:33 [ERROR]   ImageBannerTests.printBannerWhenPixelModeIsBlockShouldRenderBlocks:187 
08:54:33 Expecting:
08:54:33  <"
08:54:33
08:54:33 ????? 
08:54:33
08:54:33 ">
08:54:33 to contain:
08:54:33  <"???? ">
```

I don't know why yet. It passes locally on macOS and Linux.

**Comment by wilkinsona** [comment]
It's an encoding problem. On Concourse or in the CI Docker image run locally, the test uses US-ASCII encoding. It needs to use UTF-8.
