### ISSUE TITLE
Spring cloud gateway-skipping login page

### ISSUE THREAD

**Issue by ishwar12go** [spring-projects/spring-boot#18309]
We have overridden configure(http) method of WebSecurityConfigurerAdapter abstract class. The code we have written inside this method is to skip the login page. But Spring cloud gateway is not invoking this overridden method. Despite that it is calling default configure(http) method. Because of this we are not able to skip the login page.

**Comment by wilkinsona** [comment]
Spring Cloud Gateway is managed as a [separate project](https://github.com/spring-cloud/spring-cloud-gateway/). If you believe you have found a bug, please open an issue in their tracker and provide as much information as possible about the problem including steps showing how to reproduce it. If you are looking for some advice, you can chat with the Spring Cloud team and community on [Gitter](https://gitter.im/spring-cloud/spring-cloud).
