### ISSUE TITLE
TTL property is not working for health indicator when using webflux

### ISSUE THREAD

**Issue by worldtiki** [spring-projects/spring-boot#18324]
The `management.endpoint.health.cache.time-to-live` doesn't seem  to work when using Webflux.

I created a dummy project and uploaded it here: https://github.com/worldtiki/healthchecks-ttl/blob/master/src/main/java/com/example/demo/MyHealthIndicator.java

The problem can be reproduced by calling `/actuator/health` multiple times.
Each time the custom health indicator is called, it prints "potato". It should only print potato once since we're asking Spring Boot to cache the responses for 60s, however the string is printed every time. 

This works fine with non reactive Boot but doesn't when using Webflux.
The `CachingOperationInvoker` is working as expected and it does return the cached response, but because it returns a `Mono` (`MonoMapFuseable`) and not the actual response body, the health indicator code is still executed.

**Comment by philwebb** [comment]
Closing in favor of PR #18339
