### ISSUE TITLE
Gradle 6.x warning when using BootJar task

### ISSUE THREAD

**Issue by rpalcolea** [spring-projects/spring-boot#18326]
Hi folks,

While doing some Gradle 6.x nightly release exploration found the following warning when using `spring-boot-gradle-pliugin`

```
java.lang.IllegalArgumentException: Deprecation warnings were found (Set the ignoreDeprecations system property during the test to ignore):
 - Property 'bootInf' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
``` 

It appears to be related to `https://github.com/spring-projects/spring-boot/blob/d86c72bf73f58811b992e117aff2196b6bba6d9b/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/bundling/BootJar.java#L44`

One of the Gradle 6.x changes is that `validateTaskProperties` will now fail builds for plugins where the tasks are missing input/output annotations for properties.

**Comment by wilkinsona** [comment]
Thanks, @rpalcolea. It should be `@Internal` to align with the war task's `webInf` property.

**Comment by rpalcolea** [comment]
yeah, that's what I thought 👍 

Thanks for the quick response!

**Comment by wilkinsona** [comment]
Hmm, it's `@Internal` already (https://github.com/spring-projects/spring-boot/issues/15488):

https://github.com/spring-projects/spring-boot/blob/42e0dc14b5d9da403b61d91ab0674973d02b96e9/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/bundling/BootJar.java#L163-L168

That looks like a false positive from Gradle to me. What version of Boot's Gradle plugin did you test with?

**Comment by rpalcolea** [comment]
tried with `2.0.7` and `2.1.1`. 

Noticed that right now... wondering if doesn't like the getter for some reason, weird since this is a Java project, so really annotation on property wouldn't solve this.

**Comment by rpalcolea** [comment]
Well... `2.1.8` works fine. I guess it is fine to disregard this.

I got confused with the `@since 2.0.3`

**Comment by rpalcolea** [comment]
Closing this now @wilkinsona.

Sorry for the false alarm

**Comment by wilkinsona** [comment]
No problem. Thanks for taking another look.
