### ISSUE TITLE
Update Documentation of Task Execution Properties

### ISSUE THREAD

**Issue by arisen1145** [spring-projects/spring-boot#18327]
The property `spring.task.execution.pool.max-threads` documented in articel 42 is not the correct property. In the appendix and in code it is named `spring.task.execution.pool.max-size`

See:
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-task-execution-scheduling

**Comment by philwebb** [comment]
Closing in favor of PR #18331
