### ISSUE TITLE
See if provided scope can be removed for tomcat starter in Jersey smoke test

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#18346]
I'm not sure why the jersey sample`spring-boot-starter-tomcat` has scope `provided`. Flagging to see if anyone else remembers.

**Comment by philwebb** [comment]
It's got `<packaging>war</packaging>` so we're probably just following the [how-to docs](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-create-a-deployable-war-file) to make sure it works. It's not got JSPs so I'm not sure why it's a war.
