### ISSUE TITLE
Spring not throwing NoHandlerFoundException

### ISSUE THREAD

**Issue by zhangjiaxin281** [spring-projects/spring-boot#18353]
I'm sorry, I asked again,@bclozel, @AndRossi ,Set by the @androssi method, getting static resources is fine in my environment, but the lack of uris does not throw NoHandlerFoundException

I want to do both at the same time:
- If the handler cannot be found, be sure to throw an exception
- Provide my static resources to customers

But the existing configuration has not been solved

application.yaml
```
spring:
  resources:
    static-locations: "classpath:/static/"
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern : "/**"
```
ControllerExceptionAdvice
```
@ControllerAdvice
public class ControllerExceptionAdvice {

    @ExceptionHandler(NoHandlerFoundException.class)
    public void noHandlerFoundExceptionExceptionResolvers(HttpServletResponse response) throws Exception {
        writeResponse(response, JsonResult.JsonResult(false, "resources lost!", 404));
    }


    private void writeResponse(HttpServletResponse response, JsonResult message) throws IOException {
        response.setContentType("application/json");
        response.setCharacterEncoding("utf-8");
        response.getWriter().write(Json.encode(message)  );
    }

}
```
https://github.com/zhangjiaxin281/testNoHandler.git
https://stackoverflow.com/questions/39973945/no-handler-found-exception-and-static-resources-in-spring-boot
https://github.com/spring-projects/spring-boot/issues/9263
_Originally posted by @zhangjiaxin281 in https://github.com/spring-projects/spring-boot/issues/9263#issuecomment-535094871_

**Comment by philwebb** [comment]
@zhangjiaxin281 Please don't add a comment and a new issue asking the same thing. It causes unnecessary notifications for everyone watching this repo.

As mentioned in #9263, the correct place to ask questions is stackoverflow.com. Thanks.
