### ISSUE TITLE
Add multiple paths to disk space health check

### ISSUE THREAD

**Issue by cyterdan** [spring-projects/spring-boot#18359]
Current configuration for disk space monitoring looks like this:

`
management.health.diskspace.path=/var/log/tomcat8
`

I have a requirement to monitor multiple paths. 
If you think that's useful, I can take this on and create a PR.

Thanks

**Comment by philwebb** [comment]
Thanks for the suggestion @cyterdan, I think it would be a worthwhile enhancement. It should be possible to update `DiskSpaceHealthIndicator` to accept a collection of path/threshold pairs. If you're interested in creating a PR, this would be most welcome.

**Comment by eddumelendez** [comment]
Hi, I would like to work on this with a friend @manduinca. Can we take it?

I think we should keep backward compatibility, right?

WDYT about having the following properties?

```properties
management.health.diskspace.<alias>.path=
management.health.diskspace.<alias>.threshold=
```

**Comment by snicoll** [comment]
@eddumelendez thanks for the offer but the issue is already assigned. See #18413

**Comment by eddumelendez** [comment]
thanks @snicoll

**Comment by wilkinsona** [comment]
As described in https://github.com/spring-projects/spring-boot/issues/27306#issuecomment-903907394, we have decided that we do not want to add support for configuring the disk space health indicator with multiple paths.
