### ISSUE TITLE
Publish an AuditEvent on logout

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#1836]
Currently the actuator does a good job on sending `AuditEvent`s on login (ok/failure) authentication etc. would be nice if that could also be done for a logout. This can probably be implemented with a `LogoutHandler` which gets invoked in the logout chain or another `ApplicationListener` that listens for `SessionDestroyedEvent`s. 

Would be especially nice if a difference could be made between a regular logoff or a session timeout.

Might be related to [SEC-2680](https://jira.spring.io/browse/SEC-2680).

**Comment by ptahchiev** [comment]
+1 for this

**Comment by philwebb** [comment]
I think we should leave this to the Spring Security fix suggested in [SEC-2680](https://github.com/spring-projects/spring-security/issues/2900)

**Comment by Chu3laMan** [comment]
can I make a try out on this?

**Comment by philwebb** [comment]
Please do @Chu3laMan. You'll probably want to take a look at `AuthenticationAuditListener` and add something to `onApplicationEvent` that deals with `org.springframework.security.authentication.event.LogoutSuccessEvent`. There are existing tests in `AuthenticationAuditListenerTests` that might also help.

**Comment by Chu3laMan** [comment]
It's already done, don't we need to take care about handling errors during logout phase?

**Comment by philwebb** [comment]
Closing in favor of PR #41278. Thanks @Chu3laMan
