### ISSUE TITLE
Upgrade to Tomcat 9.0.26

### ISSUE THREAD

**Issue by lingocoder** [spring-projects/spring-boot#18388]
According to [*the release notes for 2.2.0.M6*](http://bit.ly/Boot220M6) Spring Boot has a dependency on [*Tomcat 9.0.24*](http://bit.ly/Tmct9024). 

Several libraries in that version of Tomcat have this [*Bug 63739 - Automatic-Module-Names in embedded jars are language-level invalid*](http://bit.ly/TmctBug). 

The effect of that bug can be observed when launching a Spring Boot Jersey application with a command like this:

```
java --module-path ..:/home/lingocoder/libs/org.springframework.boot/spring-boot-starter-jersey/2.1.8.RELEASE/spring-boot-starter-jersey-2.1.8.RELEASE.jar:../home/lingocoder/libs/org.apache.tomcat.embed/tomcat-embed-websocket/9.0.24/tomcat-embed-websocket-9.0.24.jar:/home/lingocoder/libs/org.apache.tomcat.embed/tomcat-embed-core/9.0.24/tomcat-embed-core-9.0.24.jar:/home/lingocoder/libs/org.apache.tomcat.embed/tomcat-embed-el/9.0.24/tomcat-embed-el-9.0.24.jar -m my.module/my.springboot.application.Main
```

The error message the bug produces is this:

```
...
java.lang.module.FindException: Unable to derive module descriptor for /home/lingocoder/libs/org.apache.tomcat.embed/tomcat-embed-websocket/9.0.24/tomcat-embed-websocket-9.0.24.jar
...
Caused by: java.lang.module.FindException: Automatic-Module-Name: org.apache.tomcat-embed-websocket: Invalid module name: 'tomcat-embed-websocket' is not a Java identifier
```

[*The release notes for Tomcat 9.0.25*](http://bit.ly/Tomcat9025) report that bug as fixed in that more recent version:

> „[*63739*](http://bit.ly/TmctBug): *Correct the invalid `Automatic-Module-Name` manifest entries for the Tomcat provided JARs included in the Tomcat embedded distribution. (markt)*...“

**Comment by mbhave** [comment]
Thanks but we have a semi-automated process to upgrade dependencies. We'll process this in due course and therefore don't need an issue for it.

**Comment by lingocoder** [comment]
[*Thank you*](https://github.com/spring-projects/spring-boot/issues/18403) both @mbhave and @snicoll :+1:

**Comment by snicoll** [comment]
I haven’t applied the upgrade process on master yet but I will soon and before releasing as usual.

**Comment by lingocoder** [comment]
That's better than nothing :+1:
