### ISSUE TITLE
Elasticsearch cluster nodes (TransportClient)

### ISSUE THREAD

**Issue by mhmpl** [spring-projects/spring-boot#1838]
Hi! 

Im trying to connect to a remote Elasticsearch instance via the `TransportClient` by setting the `spring.data.elasticsearch.clusterNodes` property. In my case the value is localhost:3337 (I'm running ES on a vagrant vm). 
However, a `data` directory is always created within my application. So I guess an embedded ES instance is used.
Second thing, the documentation says, that the property is named `spring.data.elasticsearch.cluster-nodes` but when I check the `ElasticsearchProperties` class the properties are named `clusterNodes` and `clusterName`.

**Comment by jeacott** [comment]
on this, and looking at the delegation, I'm struggling to understand how I should be able to configure
a transport client beyond just cluster-name and cluster-nodes.

the latest incarnation of elasticsearch doesn't connect a remote transport node unless client.transport.sniff=false

how can I configure this while I'm using spring boot and spring data es?
before looking at the code I'd thought something like spring.data.elasticsearch.client.transport.sniff=false would have done it, but now I think not.

any suggestions?

**Comment by jeacott** [comment]
ok,
 so I ended up with this solution. I hope theres a better way?

@EnableAutoConfiguration(exclude = {ElasticsearchRepositoriesAutoConfiguration.class,ElasticsearchAutoConfiguration.class })

    @Bean
    public TransportClientFactoryBean createTransportClientFactoryBean(){
    	TransportClientFactoryBean clientFactoryBean=new TransportClientFactoryBean();
    	clientFactoryBean.setClientTransportSniff(Boolean.valueOf(sniff));
    	clientFactoryBean.setClusterName(clusterName);
    	clientFactoryBean.setClusterNodes(clusterNodes);
    	return clientFactoryBean;
    }

**Comment by jeacott** [comment]
This seems like a really short term solution. The es client can be configured by simply passing a properties object full of settings to it, it can also accept a prefix. So why not just pass all properties beginning with spring.data.elasticsearch? Then this issue is fixed for all existing and new settings.

**Comment by wilkinsona** [comment]
Good suggestion, thanks. We could pass through anything beginning with `spring.data.elasticsearch.properties`, similar to what we do for JPA (`spring.jpa.properties`).
