### ISSUE TITLE
Load submodule properties from a multimodule project.

### ISSUE THREAD

**Issue by kingbbode** [spring-projects/spring-boot#18399]
The current usability is inconvenient when many multi-module projects are used.

Spring Boot offers three ways to load custom settings.

spring.config.location, spring.config.name
SpringApplicationBuilder
EnvironmentPostProcessor
[[Spring Docs : howto-properties-and-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html)]

There is also this method using Profile

[[Spring Docs : boot-features-external-config](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html)]

**[Example]**
*[main module]*
```
spring:
  profiles:
    include:
      - a
      - b
      - c
```
*[sub module a]*
`application-a.yml`

*[sub module b]*
`application-b.yml`

*[sub module c]*
`application-c.yml`

but this is cumbersome. when a lot of multi-modules and settings are created, you have to work on them every time.

In a multimodule project, modules should be as easy to extend as creating classes and methods. I think spring boot can support this.

I used `EnvironmentPostProcessor` to build a project that supports this.(https://github.com/kingbbode/spring-boot-custom-yaml-importer)

can make it more flexible and nice with Spring Boot.

```
spring.properties.additional-location=config
spring.properties.additional-pattern=custom-*
```

My goal is to provide the above usability and to support writing in application modules.

I'm curious about your thoughts.

**Comment by philwebb** [comment]
We have to balance requests like this against the additional complexity and potential performance issues that they might bring. All things considered, we feel like our currently solution works well for most users and we don't think that extending it into modules is something we'd want to directly support.

The `EnvironmentPostProcessor` provides a nice hook if users really want to support additional patterns, but I'm afraid it's not something we currently have an appetite for ourselves.

Thanks anyway for the suggestion and for the project that you've developed.
