### ISSUE TITLE
Renaming ServerRSocketFactoryCustomizer to ServerRSocketFactoryProcessor

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18390]
`ServerRSocketFactoryCustomizer` is a little unusual because it extends `Function` and needs to return a new result. Most other `*Customizer` interfaces return `void` so I wonder if we should rename it to `ServerRSocketFactoryProcessor` or `ServerRSocketFactoryInteceptor` or something else?

**Comment by snicoll** [comment]
+1 for not naming it `Customizer` if the method signature isn't `void`

**Comment by wilkinsona** [comment]
`ServerRSocketFactoryTransformer`?

**Comment by bclozel** [comment]
While reading our actual support there (and chatting with other team members), I'm also reconsidering the interface altogether.

Currently rsocket-java's `RSocketFactory.ServerRSocketFactory` builder is stateful, and it's building the actual server in stages, switching to a `RSocketFactory.ServerTransportAcceptor` type once the acceptor is being configured with `RSocketFactory.ServerRSocketFactory#acceptor`.

I think I chose the `Function` approach thinking that the builder returned a new instance for every call and to avoid people calling that acceptor method. We could turn this interface into a proper Customizer with a void return type.

The only downside to that is that if developers call `RSocketFactory.ServerRSocketFactory#acceptor` they might think they actually customized the acceptor, but we will actually override that later in our infrastructure.

So our two options are:

1. make that a proper customizer and find a way to avoid people calling the `acceptor` method
2. leave it as is and rename it to `Transformer`/`Processor`

2) is a bit artificial, but I think it's protecting us from possible changes in the RSocket API (it's still in its RC phase), and it avoids the `acceptor` confusion. So my vote goes to that.

**Comment by philwebb** [comment]
I'd vote 2 as well. If it turns out we can do it with an `Customizer` once RSocket is GA we can always introduce that as well.

**Comment by philwebb** [comment]
We'll rename it to `ServerRSocketFactoryProcessor`
