### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.dao.DataAccessException

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#1839]
When 'org.springframework.boot:spring-boot-starter-web' dependency is only added and

run the following code:

``` java
@EnableAutoConfiguration
@ComponentScan
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class);
    }

}
```

Got the following exception:

``` java
java.lang.ClassNotFoundException: org.springframework.dao.DataAccessException
```

I think there's no reason to get the above exception.

**Comment by rollenholt** [comment]
@snicoll Thank you very much

**Comment by snicoll** [comment]
:+1:

**Comment by javabeat** [comment]
Hi, I have the very similar issue in the latest version of Spring boot

**Comment by snicoll** [comment]
As [I told you on stackoverflow](http://stackoverflow.com/questions/32294405/custom-endpoint-in-spring-boot-actuator/32296608?noredirect=1#comment52487771_32296608) already, you probably have one class in the _default_ package that has component scan (_defaut_ package = no `package` statement in the class). If that's not the case, please  create a separate issue with a sample project that reproduces the problem.

**Comment by javabeat** [comment]
I have created new issue #3850 with details. Please check if that is issue or not and close it.

**Comment by linxingzhi** [comment]
I also have this problem   do you resolve it 。   please tell me thanks
