### ISSUE TITLE
Enable auto-configuration of HiddenHttpMethodFilter when an HTML view resolver is in classpath

### ISSUE THREAD

**Issue by destan** [spring-projects/spring-boot#18434]
With #16953 we don't have `HiddenHttpMethodFilter` autoconfigured anymore (I've checked `spring-boot-starter-parent:2.2.0.M6`). However, I think it should be autoconfigured when the application uses any html view resolver like `Thymeleaf`.

I believe developers would appreciate this functionality to be working out-of-the-box when dealing with HTML forms.

_I thought this is a separate issue than #17354 so I've opened a new issue._

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think we should do that. `HiddenHttpMethodFilter` is still potentially harmful when there is a `ViewResolver` and in a lot of cases an HTML form using `GET` or `POST` is sufficient. If you need to be able to use other HTTP methods, you should opt in and accept the downside of the request's parameters being read early in the request's processing.
