### ISSUE TITLE
disabling default security password when defining our own WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by amgohan** [spring-projects/spring-boot#1843]
Hi,

I upgraded my spring boot from 1.1.4.RELEASE to 1.1.8.RELEASE without any change in my code source. everything works fine, but I get ``Using default security password: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`` in my log, somehow in ``AuthenticationManagerConfiguration.BootDefaultingAuthenticationConfigurerAdapter.configure(AuthenticationManagerBuilder auth)`` the condition ``auth.isConfigured()`` return false.

Have you a suggestion to disable the default password??

**Comment by mgooty** [comment]
Move the `AuthenticationManagerBuilder` logic to a separate configuration class as below:

    @Configuration
    protected static class AuthenticationConfiguration extends
                    GlobalAuthenticationConfigurerAdapter {
    	
		@Override
		public void init(AuthenticationManagerBuilder auth) throws Exception {
			// Authentication manager builder logic goes here
		}
	}

**Comment by bjconlan** [comment]
I'm having a similar problem moving from 1.2.1 to 1.2.2. (my case is much simpler)

```java
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth, UserDetailsService accountUserDetailService,
	                            PasswordEncoder passwordEncoder) throws Exception {
		auth.userDetailsService(accountUserDetailService).passwordEncoder(passwordEncoder);
	}
}
```
Has something changes in regards to the builders for the security configuration?

**Comment by rwinch** [comment]
@amgohan - When using the protected method it is expected that Boot will still generate a user and password due to the fact that the protected method is isolated.

> I'm having a similar problem moving from 1.2.1 to 1.2.2. (my case is much simpler)

@bjconlan This appears to be a duplicate of #2567 Can you try the latest Spring Boot SNAPSHOT (i.e. 1.2.3.BUILD-SNAPSHOT) and see if it resolves your issue?

**Comment by bjconlan** [comment]
Sorry for the delay in response, Just tested against 1.2.3.BUILD-SNAPSHOT and works as expected (ie as in 1.2.1.RELEASE)

**Comment by rwinch** [comment]
Thank you for the response. Per the previous comment I'm closing this as a duplicate of #2567
