### ISSUE TITLE
Allow more detailed customization of Jackson's ObjectMapper while retaining auto-configuration

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-boot#18449]
[Jackson2ObjectMapperBuilderCustomizer](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/jackson/Jackson2ObjectMapperBuilderCustomizer.html) allows us to customize part of Jackson and its [ObjectMapper](http://fasterxml.github.io/jackson-databind/javadoc/2.10/com/fasterxml/jackson/databind/ObjectMapper.html). However, this customization mechanism doesn't allow us to configure some advanced options of ObjectMapper, such as [setDefaultSetterInfo](http://fasterxml.github.io/jackson-databind/javadoc/2.10/com/fasterxml/jackson/databind/ObjectMapper.html#setDefaultSetterInfo-com.fasterxml.jackson.annotation.JsonSetter.Value-).

We can always define a custom ObjectMapper Bean but that will disable [Spring Boot's auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper).

As an alternative, we can also access the ObjectMapper Bean and change it. However, would it make sense to have a more modular and composable way of customizing the ObjectMapper, similar to what was done with Jackson2ObjectMapperBuilderCustomizer but with full access to the ObjectMapper instead of pre-defined options?

**Comment by wilkinsona** [comment]
You can already do this by using the auto-configured `Jackson2ObjectMapperBuilder` to create your custom `ObjectMapper`. Something like this:

```java
@Bean
@Primary
ObjectMapper jacksonObjectMapper(Jackson2ObjectMapperBuilder builder) {
	ObjectMapper objectMapper = builder.createXmlMapper(false).build();
	// Further customization as required
	return objectMapper;
}
```

I am not keen on having something like an `ObjectMapperCustomizer` callback in addition to the existing builder. If something is missing, I'd rather see that being added to the builder in Spring Framework. That said, if you need such a callback, you could implement it yourself and call and customisers in your own `ObjectMapper` `@Bean` method.

**Comment by joca-bt** [comment]
Leaving this note here as it may be helpful for someone else in the future:

Spring 5.3 introduced a new customization point that allows to do this in another way ([link](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.html#postConfigurer-java.util.function.Consumer-)).
