### ISSUE TITLE
run bomr against internally managed dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18448]
While discussing on #18446 it occurred to me we could run `bomr` on `spring-boot-starter-parent`. I patched `bomr.yaml` locally to be able to do so and they were a number of upgrades worth looking at IMO.

**Comment by dreis2211** [comment]
At best `bomr` could specify multiple boms for such cases. I was already thinking that a while ago and thought about contributing it. What do you think?

**Comment by snicoll** [comment]
I am not sure what the best course of action for that is but I agree there should be a way ideally. Let's not forget that the upgrade policy you put for one bom may not apply to another so having multiple boms there or a way to override can be confusing or too limited. While this is more a topic for the bomr project, let's reuse this issue to discuss this feature.

**Comment by wilkinsona** [comment]
As chance would have it, I started playing around with Bomr running against multiple boms recently. It needs some changes in the innards to support Boot's arrangement where `spring-boot-parent` extends from `spring-boot-dependencies`. If you're upgrading `spring-boot-parent` it needs to be smart enough to ignore stuff inherited from `spring-boot-dependencies`. I should open an issue at least.

**Comment by snicoll** [comment]
I did that, let's follow-up on spring-io/bomr#19.
