### ISSUE TITLE
Upgrade to Maven Resolver 1.4.1

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18454]

**Comment by snicoll** [comment]
Looks like that upgrading means we need to add a SLF4J binding to the CLI. It might be a bit late to look at that so flagging for team attention to see what the rest of the team thinks.

**Comment by snicoll** [comment]
We discussed it and I forgot what the outcome was. This requires adding an slf4j implementation on the classpath for the CLI. I am not sure what to do. I've added `slf4j-simple` but given that our codebase uses JCL, I wonder if we shouldn't do something else. Flagging again for team attention.

**Comment by philwebb** [comment]
Looks like this was fixed during the Gradle migration.
