### ISSUE TITLE
Logging at method level

### ISSUE THREAD

**Issue by priyasaloni** [spring-projects/spring-boot#18491]
## currently, we can control logging at class level, what if we can do this at method level as well
here's a scenario:If I want to enable debug logs for one particular method of a class, this could be really useful.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This is really an logging framework (Logback of Log4j2) enhancement request rather than something that can be improved in Spring Boot. You could implement it today by using differently named loggers for each method in the class.
