### ISSUE TITLE
Feign, can't inject service

### ISSUE THREAD

**Issue by cielswift** [spring-projects/spring-boot#18498]
java version 12
spring boot version 2.18

![捕获](https://user-images.githubusercontent.com/42295829/66108531-61ad3400-e5f5-11e9-9ce8-06c790b9efe3.PNG)
![捕获2](https://user-images.githubusercontent.com/42295829/66108532-61ad3400-e5f5-11e9-864c-efd3a3d8adda.PNG)
![捕获3](https://user-images.githubusercontent.com/42295829/66108534-6245ca80-e5f5-11e9-94f7-09fecb6abafd.PNG)
![捕获4](https://user-images.githubusercontent.com/42295829/66108535-6245ca80-e5f5-11e9-9b3f-e45271641a91.PNG)
![捕获5](https://user-images.githubusercontent.com/42295829/66108537-6245ca80-e5f5-11e9-95cf-a8f1b3c11b32.PNG)
![捕获6](https://user-images.githubusercontent.com/42295829/66108539-62de6100-e5f5-11e9-8043-5fd4ca8074f1.PNG)

**Comment by snicoll** [comment]
OpenFeign is not part of Spring Boot and reporting an issue with screenshots is quite hard for the team to grasp what the problem can be. Please consider asking a question on StackOverflow, describing the problem first. A sample that reproduces the problem should definitely help you get an answer.
