### ISSUE TITLE
🎁 It would be interesting to create a default docker image to start spring boot

### ISSUE THREAD

**Issue by javyxx** [spring-projects/spring-boot#18499]
Because there are more and more versions of the java virtual machine. It would be good to evaluate the performance and establish a docker image with the best.

docker pull spring-boot-jvm:2.2.0-RELEASE

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but our opinion is that best is too subjective when it comes to choosing a JVM to use. Different applications have different requirements and different performance characteristics that well be best-served by different JVMs. On top of that some users will have a support contract with a particular JVM vendor and will need to use the JVM built by the vendor over any other.
