### ISSUE TITLE
Support specifying MVC format for LocalDateTime/LocalTime

### ISSUE THREAD

**Issue by trygveaa** [spring-projects/spring-boot#18511]
Currently, you can specify the format to use for parsing/formatting `LocalDate` with `spring.mvc.date-format`. However, I don't see any way to specify the format for `LocalDateTime` or `LocalTime` (except programatically register the formatter).

I would also like to be able to specify that all these three Local-classes should use the ISO 8601 format, without having to specify that format myself.

**Comment by philwebb** [comment]
Closing in favor of PR #18772
