### ISSUE TITLE
Publish Gradle marker artifact for the Spring Boot plugin

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18514]
Our plugin coordinates do not match what Gradle expects from the plugin id so some additional code is required to resolve the plugin with a snapshot or milestone version.

Publishing [a marker artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) will avoid that and make the setup simpler with Gradle.

**Comment by wilkinsona** [comment]
[This branch](https://github.com/wilkinsona/spring-boot/tree/gh-18514) contains the changes to publish a marker artifact. It allows the following configuration to be removed from `pluginManagement` in `settings.gradle`:

```groovy
resolutionStrategy {
    eachPlugin {
        if (requested.id.id == 'org.springframework.boot') {
            useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
        }
    }
}
```

The marker artifact could also be of benefit when a release version of the plugin is being used. If the Gradle Plugin Portal is down, the marker artifact will allow it to be resolved from Maven Central if we added `mavenCentral()` as a repository.
