### ISSUE TITLE
Property to configure Kafka error handler

### ISSUE THREAD

**Issue by nikolashermann** [spring-projects/spring-boot#18512]
Spring Kafka has some container-level error handlers built in.
Provide a property to use them with spring boot.

Examples:
```
spring.kafka.listener.error-handler=org.springframework.kafka.listener.SeekToCurrentErrorHandler
```

```
spring.kafka.listener.error-handler=org.springframework.kafka.listener.ContainerStoppingErrorHandler
```

**Comment by wilkinsona** [comment]
WDYT @artembilan and @garyrussell?

**Comment by artembilan** [comment]
I wouldn't say this is what configuration properties are for.
An `ErrorHandler` must be a bean and it may have its own configuration.
The `KafkaAnnotationDrivenConfiguration` accepts an `ObjectProvider<ErrorHandler> errorHandler` for this purpose.

While a `ContainerStoppingErrorHandler` is pretty simple and straightforward to instantiate from the class now, it doesn't matter that it isn't going to evolve eventually for some customization.
At the same time a `SeekToCurrentErrorHandler` is not so simple and may be already customized with some extra non-default properties.

So, for a single source of the truth I would stick with only bean-based configuration for this `ErrorHandler` approach.

My opinion *Won't Fix*

Thanks

**Comment by snicoll** [comment]
We've usually refrained from exposing configuration properties that refer to classes so I am not in favour of introducing such property. There is already support for this and if you register a `ErrorHandler` bean in your configuration [it will be picked up automatically](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-kafka-receiving-a-message).

**Comment by wilkinsona** [comment]
Thank you, @artembilan.
