### ISSUE TITLE
AOP Smoke test package reference is incorrect

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18527]
the AOP example no longer works following the move as the advice needs to change to reflect the new package name.

**Comment by vivganes** [comment]
@philwebb I can take and work on it. Can you please point me to the URL where i can find the incorrect README?

**Comment by philwebb** [comment]
Thanks for the offer @vivganes. I actually made a mistake raising this issue, it's not the readme but [this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-aop/src/main/java/smoketest/aop/monitor/ServiceMonitor.java#L29) expression that needs to change.

**Comment by snicoll** [comment]
Closing in favour of PR #18558
