### ISSUE TITLE
Target bean of type java.util.Collections$EmptySet is not of type of the persistent entity

### ISSUE THREAD

**Issue by smastika** [spring-projects/spring-boot#18535]
When trying to save a Document that contains a collection of objects, setting a default value (Collections.emptyList()/Collections.emptySet()) in builder and trying to save document using repository.save(); gives java.util.Collections$EmptySet is not of type of the persistent entity pointing to the type of objects for that empty collection. I just stepped version from 2.1.4.RELEASE to 2.2.0.RC1

**Comment by wilkinsona** [comment]
Given the mention of `Document` and looking at earlier revisions of your comment, I think you're using Spring Data MongoDB which is managed as a [separate project](/spring-projects/spring-data-mongodb) and uses [JIRA](https://jira.spring.io/browse/DATAMONGO) for issue tracking. Can you please raise an issue with them, providing a complete and minimal sample that reproduces the problem?
