### ISSUE TITLE
Unexpected settings in effective pom when inheriting from spring-boot-starter-parent

### ISSUE THREAD

**Issue by rweisleder** [spring-projects/spring-boot#18532]
The [two documented ways](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/htmlsingle/#using-boot-maven) to start a Maven project are either inherit from `spring-boot-starter-parent` or import `spring-boot-dependencies`. The main differences are of course, that `spring-boot-starter-parent` provides the version properties and more configured plugins.

However, when inheriting from `spring-boot-starter-parent` there are more settings made. See this snippet from an effective pom:
```xml
  <description>Parent pom providing dependency and plugin management for applications
		built with Maven</description>
  <url>https://projects.spring.io/spring-boot/#/spring-boot-starter-parent/myproject</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>Pivotal</name>
      <email>info@pivotal.io</email>
      <organization>Pivotal Software, Inc.</organization>
      <organizationUrl>https://www.spring.io</organizationUrl>
    </developer>
  </developers>
  <scm>
    <url>https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/myproject</url>
  </scm>
```

I wouldn't expect these settings in a new project. These are not correct in most cases. This should either be documented or removed.

Steps to reproduce:
* create new Maven project which inherits from `spring-boot-starter-parent` ([like this](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/htmlsingle/#getting-started-first-application-pom))
* run `mvn help:effective-pom`

**Comment by wilkinsona** [comment]
Unfortunately, removal isn't an option as the information is a [requirement](https://central.sonatype.org/pages/requirements.html#sufficient-metadata) for publishing to Maven Central.

**Comment by rweisleder** [comment]
Thanks for resolving this, @wilkinsona!
But what about `<description>`, `<url>` and `<scm>`, should users override them as well? I think users shouldn't use the defaults.

**Comment by wilkinsona** [comment]
Gah, yes we'll need to do something about those too. Thanks.

**Comment by wilkinsona** [comment]
This is the complete, minimal set of overrides:

```xml
<description/>
<developers>
    <developer/>
</developers>
<licenses>
    <license/>
</licenses>
<scm>
    <url/>
</scm>
<url/>
```
