### ISSUE TITLE
spring-cloud-config-monitor

### ISSUE THREAD

**Issue by prince129** [spring-projects/spring-boot#18537]
I am tring to update the config server by enabling the monitor endpoint in the spring-cloud-config server as I am using the bitbucket as my repo. It genrates the pull-request as webhook object in the post call. When I went to the class BitbucketPropertyPathNotificationExtractor

if (("repo:push".equals(headers.getFirst("X-Event-Key"))
				|| "pullrequest:fulfilled".equals(headers.getFirst("X-Event-Key")))
				&& StringUtils.hasText(headers.getFirst("X-Hook-UUID"))) {
			// Bitbucket cloud
			Object push = request.get("push");
			if (push instanceof Map
					&& ((Map<?, ?>) push).get("changes") instanceof Collection) {
				// Bitbucket doesn't tell us the files that changed so this is a
				// broadcast to all apps
				return new PropertyPathNotification("application.yml");
			}
		}

It looks for push object in the post request genrated by the webhook. But bitbucket genrates the object as pull-request.

Can you help me to resolve the issue.

**Comment by spencergibb** [comment]
Please open the issue in spring-cloud-config
