### ISSUE TITLE
spring boot fails to set logging level correctly while using log4j2 instead of logback

### ISSUE THREAD

**Issue by c3y28** [spring-projects/spring-boot#18551]
- Spring Boot 2.1.x.RELEASE
- JUL as logging API
- Oracle JDK 11.0.4 or Oracle JDK 1.8.0_221

setting logging level to TRACE in application.properties but not take effect. Actually logging.properties under working JAVA_HOME takes effect

if using default logging.properties, we will find missing these level items in log(config, fine, finer, finest)

please find the attached for a simple demo to reproduce the issue.
[spring-boot-logging-demo.zip](https://github.com/spring-projects/spring-boot/files/3710118/spring-boot-logging-demo.zip)

**Comment by wilkinsona** [comment]
Thank you for the sample. To route all JUL logging into Log4j2 you need to set a system property as described in the [usage section](https://logging.apache.org/log4j/2.x/log4j-jul/index.html) of their documentation. There's a [mention of this](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/htmlsingle/#howto-configure-log4j-for-logging) in Boot's documentation as well. Given the use of a system property I'm still (https://github.com/spring-projects/spring-boot/issues/2923#issuecomment-358451260) wary of enabling this by default so I don't think there's much more that we can do here.
