### ISSUE TITLE
Remove @ImmutableConfigurationProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18563]

**Comment by wilkinsona** [comment]
See #18517 for background.

The summary is that it became apparent that `@ImmutableConfigurationProperties` was a misleading name as the use of constructor binding doesn't require a configuration properties class to be immutable. If we were to rename the annotation, a more accurate name would be something like `@ConstructorBoundConfigurationProperties`. The benefit of this over `@ConfigurationProperties` and `@ConstructorBinding` is negligible at best, particularly when the latter may still be required on a constructor when it's necessary to identify which constructor should be used for property binding. We concluded that removing `@ImmutableConfigurationProperties` and requiring `@ConfigurationProperties` and `@ConstructorBinding` was the best available option.
