### ISSUE TITLE
Document formatting recommendations for configuration property javadoc

### ISSUE THREAD

**Issue by jjoslet** [spring-projects/spring-boot#18572]
The configuration-processor removes all new lines from JavaDoc but this can cause troubles when one is using an HTML `<pre>` tag in its JavaDoc.

**Comment by wilkinsona** [comment]
This is working as designed as there's no support for formatting of the configuration property descriptions. We should probably make this clearer in the documentation by mentioning it in [this section](https://docs.spring.io/spring-boot/docs/2.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-custom-starter-configuration-keys).

**Comment by snicoll** [comment]
I agree adding a note there is a good idea. For the record, there is already a [note in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor)

**Comment by rhamedy** [comment]
@wilkinsina @snicoll can I make a PR for this?

**Comment by philwebb** [comment]
@rhamedy A PR would be most welcome. Thanks.

**Comment by snicoll** [comment]
Closing in favour of PR #18578
