### ISSUE TITLE
LegacyReactiveHealthEndpointCompatibilityConfiguration activates in non-reactive application

### ISSUE THREAD

**Issue by gbehrmann** [spring-projects/spring-boot#18570]
After upgrading to Spring Boot 2.2.0.RC1, `io.micrometer:micrometer-registry-statsd` cannot be used without also added a dependency on `org.springframework.boot:spring-boot-starter-webflux`.

To reproduce, create a Spring Initializr project with Spring Web and Spring Boot Actuator. Alter the dependencies of the generated project to:
```
	implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'io.micrometer:micrometer-registry-statsd'
        implementation 'org.springframework.boot:spring-boot-starter-actuator'
```
With Spring Boot 2.1.9 these dependencies are sufficient for creating an application that can publish micrometer stats to statsd, but after upgrading to 2.2.0.RC1 the resulting project fails with:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method reactiveHealthIndicatorRegistry in org.springframework.boot.actuate.autoconfigure.health.LegacyHealthEndpointCompatibilityConfiguration$LegacyReactiveHealthEndpointCompatibilityConfiguration required a bean of type 'org.springframework.boot.actuate.health.ReactiveHealthContributorRegistry' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'reactiveHealthContributorRegistry' in 'ReactiveHealthEndpointConfiguration' not loaded because @ConditionalOnClass did not find required class 'reactor.core.publisher.Flux'


Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.boot.actuate.health.ReactiveHealthContributorRegistry' in your configuration.
```

It turns out that `LegacyHealthEndpointCompatibilityConfiguration#LegacyReactiveHealthEndpointCompatibilityConfiguration` is `@ConditionalOnClass(Mono.class)`, however this particular `Mono` is `io.micrometer.shaded.reactor.core.publisher.Mono`.  The required bean `ReactiveHealthContributorRegistry` is supposed to be created in `ReactiveHealthEndpointConfiguration`, however that class is `@ConditionalOnClass(Flux.class)` with `Flux` being the regular non-shaded version.

**Comment by wilkinsona** [comment]
Closing in favour of #18571.

**Comment by wilkinsona** [comment]
@gbehrmann, thanks very much for trying out RC1 and taking the time to report the problem you found.
