### ISSUE TITLE
Add ability to disable peer verification via RedisProperties

### ISSUE THREAD

**Issue by chadlwilson** [spring-projects/spring-boot#18584]
Currently you can set `spring.redis.ssl=true` to opt-into SSL usage on Spring Data Redis -> Lettuce -> Netty. However, the `LettuceClientConfiguration.verifyPeer` setting is not available for configuration by Spring Boot properties/environment.

A simple workaround for this is currently possible with a `LettuceClientConfigurationBuilderCustomizer` like the below (note that `spring.redis.ssl.disable-peer-verification` is my own invention); however it'd be nice to have out-of-the-box support for this property.

```java
@Configuration
public class RedisConfig {

    @Bean
    @ConditionalOnProperty({"spring.redis.ssl", "spring.redis.ssl.disable-peer-verification"})
    public LettuceClientConfigurationBuilderCustomizer builderCustomizer() {
        return builder -> builder.useSsl().disablePeerVerification();
    }

}
```
**Note:** I haven't given any thought/testing to non-Lettuce based usage; clustered Redis etc.

**Comment by philwebb** [comment]
Thanks for the suggestion @chadlwilson. It's always a bit of a balancing act with how many properties we expose for the underlying technology. In this specific case, I think it's better if we don't directly surface it as a property and instead suggest that the `LettuceClientConfigurationBuilderCustomizer` is used.

**Comment by chadlwilson** [comment]
Thanks for the consideration @philwebb. I understand the balancing act, however perhaps if I give a bit more context to a use case for this it might seem less of an edge scenario?

Currently we are using AWS ElasticCache auto-provisioned by infra-as-code to setup Redis for use by our Spring Boot applications. With a managed service like this you get a big long random-ish AWS domain for Redis. To reduce coupling between the configuration our infra and app streams of work and provide a clear "contract", we provision private DNS aliases for this ElasticCache/Redis which are stable and survive re-provisioning. The IaC updates the DNS alias. The app stream always points to a stable alias for a given environment.

Unfortunately this means that SSL peer verification fails, because AWS do not support adding SAN to the certs presented by ElasticCache and the domain in the Redis connection is different to the domain of the presented cert. My feeling is that this is a useful enough configuration setting to deserve getting its own property; however I am happy enough to see whether anyone else stumbles across this ticket over time and reconsider it if so.

**Comment by philwebb** [comment]
Thanks for the additional details, let me discuss this one with the rest of the team before we make a final decision.

**Comment by wilkinsona** [comment]
When peer verification is disabled, Lettuce (quite reasonably) uses Netty's `InsecureTrustManagerFactory.INSTANCE` as the trust manager factory. Its javadoc notes that it should never be used in production and that it is purely for testing purposes. Your solution to AWS's limitation is requiring you to accept the risk of a man in the middle attack. I don't think that's something that we should encourage people to do by offering a configuration property for it. I think there's benefit in it being hard but still possible to opt into such an insecure configuration. 

It may be possible to work around AWS's limitation in a secure manner if a custom trust manager factory could be used that didn't disable peer verification completely, but required a signed and trusted SSL certificate from the actual ElasticCache host rather than the DNS alias. As far as I can tell, this would require an enhancement to Lettuce as I can't see how to plug in such a trust manager factory. /cc @mp911de

**Comment by mp911de** [comment]
Lettuce has currently no means to configure a custom `TrustManagerFactory`. @chadlwilson you might want to file an issue at https://github.com/lettuce-io/lettuce-core/issues.

**Comment by philwebb** [comment]
I think given Andy's comments we should not add a property for this and the `LettuceClientConfigurationBuilderCustomizer` should be used. If `TrustManagerFactory` support is added to Lettuce we can consider surfacing properties to configure it later.

**Comment by chadlwilson** [comment]
Thanks @wilkinsona, @mp911de and @philwebb for your consideration. We understand this isn't an appropriate setup for production configurations and I should have mentioned that - our intention is not to allow that; but to support lower test environments, often ephemeral, where speed of feedback can trump such concerns - and be a more reasonable solution than dealing with the overhead even of custom `TrustManagerFactory`s and distributing certs/keys or having a full PKI setup (although inarguably "better").

Such compromises in the interests of fast feedback are sometimes appropriate and most tooling support disabling for these kinds of reasons; not as a recommended production configuration. Since the Spring Data Redis team felt it was important/useful enough to expose a property, I wasn't imagining it to be particularly controversial to expose the same thing via Spring Boot also. Not to worry.
