### ISSUE TITLE
Support 'org.junit.jupiter:junit-jupiter'

### ISSUE THREAD

**Issue by octopus-prime** [spring-projects/spring-boot#18590]
Using
```
testImplementation(group: 'org.junit.jupiter', name: 'junit-jupiter')
```
in version `2.1.9.RELEASE` causes
```
Could not resolve: org.junit.jupiter:junit-jupiter
```

The workaround
```
ext['junit-jupiter.version'] = '5.5.2'
```
should be done by spring

**Comment by wilkinsona** [comment]
The `junit-jupiter` module is new in JUnit 5.4 and Spring Boot 2.1 uses JUnit 5.3.x. We cannot upgrade to a new minor version of JUnit Jupiter in a Spring Boot 2.1.x maintenance release. We've already upgraded to 5.5.x in Spring Boot 2.2 so I don't think there's anything more that we can do here.
