### ISSUE TITLE
Update server without downtime.

### ISSUE THREAD

**Issue by zgqq** [spring-projects/spring-boot#18616]
Now the normal operation of updating the server is to kill the previous process and then deploy the latest code. However, if the latest code fails and the server stops serving, we usually need to roll back the code and restore the service with the previous code, which will affect our development efficiency. Instead, we could deploy the latest code to use a random port, load it successfully, kill the previous process to close port, and then restore current server's port.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Our recommended approach is to use [blue-green deployments](https://martinfowler.com/bliki/BlueGreenDeployment.html).

**Comment by zgqq** [comment]
That article seems like a lot of work, and I've implemented it through the spring boot API without any other dependencies, which is useful for an environment with only one test server.
