### ISSUE TITLE
Regroup thread-related server properties under groups

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#18620]
There are already several thread-related configuration properties for Undertow, Tomcat and Jetty. We should regroup those under dedicated `threads` group to better organize the configuration namespace.

We might also consider other related issues like #18489 at the same time.

**Comment by bono007** [comment]
@bclozel I have a PR almost ready to submit for this. Where can I find out more about Spring Boot property deprecation policy? Specifically, do I need to mark the older properties with `@DeprecatedConfigurationProperty(replacement = "server.tomcat.threads.max")` for example?

**Comment by snicoll** [comment]
@bono007 no specific other than the usual deprecation: the existing property should still be bound and flagged as deprecated. Tests should adapt to the new scheme but you we need to keep a `@Deprecated` test that exercises the deprecated properties to validate they still work. Here is [a concrete example](https://github.com/spring-projects/spring-boot/blob/83e594ad6a581df62284125970b2090abd677991/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/MetricsProperties.java#L113-L133).

**Comment by snicoll** [comment]
Closing in favour of PR #19475
