### ISSUE TITLE
x-forwarded-host issue even after using ForwardedHeaderFilter Tomcat Spring Boot Upgrade 2.1.5, Hateoas 0.25.1

### ISSUE THREAD

**Issue by Shah0708** [spring-projects/spring-boot#18628]

**Comment by Shah0708** [comment]
I have upgraded the project from Spring Boot 1.5.13 to 2.1.5
Along with the upgrade --> HATEOAS upgraded from 0.23.0 to 0.25.1
Using Embedded Tomcat 
Tried using "ForwardedHeaderFilter" but didn't work for EntityLinks

>     
@Bean                                                                                                                                                                                                                                                                                                                                                                                 
    public FilterRegistrationBean<ForwardedHeaderFilter> forwardedHeaderFilter() {                                                                                                                                                                                                                                                                                                        
        final FilterRegistrationBean<ForwardedHeaderFilter> filter = new FilterRegistrationBean<>();                                                                                                                                                                                                                                                                                  
        filter.setFilter(new ForwardedHeaderFilter());                                                                                                                                                                                                                                                                                                                                
        return filter;                                                                                                                                                                                                                                                                                                                                                                
    } 

>

**Comment by wilkinsona** [comment]
Thanks for the snippet of filter configuration, but we'll need some more information to be able to help you. Can you please provide a complete and minimal sample that illustrates the problem. It would also be useful to know exactly what the problem is as "didn't work" doesn't tell us how to reproduce the problem or how to identify that it has occurred.

**Comment by Shah0708** [comment]
sure @wilkinsona 

The below screenshot is after the upgrade. Before the upgrade the value sent via "X-Forwarded-Host" gets populated in the href link. "X-Forwarded-Proto" and "X-Forwarded-Port" are working fine.

![image](https://user-images.githubusercontent.com/23692925/66947048-c7e37f00-f017-11e9-984d-2780617435de.png)

**Comment by wilkinsona** [comment]
Thanks. I think I understand the problem now but do not know how to recreate it. Can you please provide the complete and minimal sample that I asked for above? The best way to do that is by zipping up a project and attaching it to this issue.

**Comment by Shah0708** [comment]
@wilkinsona The issue got resolved.
A mistake from my side. We have a customized tomcat container where the configurations are made to override rempoteIpHeader as 'X-Forwarded-Host'. This configuration is made wrong. Usage of 

`@bean
public FilterRegistrationBean forwardedHeaderFilter() {
final FilterRegistrationBean filter = new FilterRegistrationBean<>();
filter.setFilter(new ForwardedHeaderFilter());
return filter;
}`

worked. Thanks for asking me to provide a sample project. That helped me to understand the issue.


> 

>
