### ISSUE TITLE
Document that auto-configuration of Jersey server metrics requires a dependency on micrometer-jersey2

### ISSUE THREAD

**Issue by krzyk** [spring-projects/spring-boot#18622]
I have both Jersey and Spring MVC in classpath (actuators are using Spring MVC and the rest of application uses Jersey).
When I enable `management.metrics.web.server.auto-time-requests` only Spring MVC requests are metered - so in my case only actuators (I think), I see only following links:
* `UNKNOWN`
* `NOT_FOUND`
* `/**`
* `/health`
* `/info`
* `root`

(I have no idea what a `root`, `UNKNOWN`, `NOT_FOUND`, `/**` or `root` urls are, I don't have those in my application, all links in my application start with /v1 or /v2).

I suggest to split the `management.metrics.web.server.auto-time-requests` to be technology specific so I can enable either Jersey or Spring MVC.
Something like:
`management.metrics.web.server.jersey.auto-time-requests`
`management.metrics.web.server.spring-mvc.auto-time-requests`

I hope the `@Timed` works in such case, so I can have Spring MVC and I can annotate Jersey controllers and get the metrics.

Spring Boot version 2.1.6.

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem? We using Jersey, metrics should be recorded via Micrometer's `MetricsRequestEventListener` and should take into consideration the auto-timing of requests. In other words, judging by what you've shared thus far, I would expect to see metrics being records for requests that are handled by Jersey. A sample will help us to figure out why that's not the case.

**Comment by wilkinsona** [comment]
> you are saying that if I have both Jersey and Spring MVC in classpath I should get metrics recorderd for both?

Yes, I believe so. The MVC metrics and Jersey metrics are collected using two separate mechanisms and they should work side-by-side.

**Comment by krzyk** [comment]
OK, I think I know where's the issue, and it looks like it is a documentation bug one not code bug.
I don't see anywhere in spring boot metrics section mentioned that I need a micrometer-jersey2 dependency to make it work, I only see that I need dependency on one of the registry dependencies.

Your mention of `MetricsRequestEventListener` got me thinking and I wasn't able to find it in my IDE, and now I know why, because I didn't have micrometer-jersey2 dependency.

**Comment by wilkinsona** [comment]
Thanks for your help in tracking this down, @krzyk. We'll update the documentation as you suggest.
