### ISSUE TITLE
org.springframework.boot.context.properties.ImmutableConfigurationProperties missing.

### ISSUE THREAD

**Issue by dldiehl77** [spring-projects/spring-boot#18630]
The class org.springframework.boot.context.properties.ImmutableConfigurationProperties was in the RC1 but is missing from the release version.  I checked the downloaded jar and also the source.zip and it was missing from both.

Was this intentional to remove this class or simply some problem with the build process that resulted in it getting not included by accident?

**Comment by mbhave** [comment]
@dldiehl77 This was an intentional change. See [this comment](https://github.com/spring-projects/spring-boot/issues/18563#issuecomment-541578426) for some background on why we decided to remove it.

**Comment by dldiehl77** [comment]
Got it...jumped the gun w/o reading the updated release notes.  So sorry.  Will not use:

@ConstructorBinding
@ConfigurationProperties("acme")
