### ISSUE TITLE
Update 2.2 release notes to note that spring-boot:run now forks a new JVM by default

### ISSUE THREAD

**Issue by ryenus** [spring-projects/spring-boot#18638]
After updating to spring boot version `2.2.0.RELEASE`, some properties passed along with `mvn spring-boot:run` doesn't work.

For example, with a project using spring boot starter `2.2.0.RELEASE`:

    mvn -Dspring.profiles.active=cloud spring-boot:run

The profile reported in the console is still `default`:
> No active profile set, falling back to default profiles: **default**

But when run with previous version of spring boot maven plugin

    mvn -Dspring.profiles.active=cloud \
    org.springframework.boot:spring-boot-maven-plugin:2.1.9.RELEASE:run

The active profile is then reported correctly:
> The following profiles are active: **cloud**

**Comment by wilkinsona** [comment]
Thanks for the report. You are passing a system property into Maven's JVM and relying upon this being the same JVM as the one that runs your application. The doesn't hold true in 2.2 where we [switched to forking by default](https://github.com/spring-projects/spring-boot/issues/16945). You should use `-Dspring-boot.run.jvmArguments` to pass arguments to the JVM that runs your app and we should check that this change is mentioned in the release notes for 2.2.

**Comment by ryenus** [comment]
@wilkinsona thank you for the prompt response!
I just did a quick check with `-Dspring-boot.run.jvmArguments` and it worked:

    mvn -Dspring-boot.run.jvmArguments=-Dspring.profiles.active=cloud spring-boot:run

However, with fork mode now on by default, it becomes problematic to start a debug process when launched within Intellij IDEA for me, I was wondering why the debug session could no longer be attached, and this seems to be the cause. (yeah, I probably should use `Application.main` directly)

May I ask if there's a way to turn off the fork mode when using `mvn spring-boot:run`?

**Comment by ryenus** [comment]
Ah, never mind, I figured it out:

    mvn -Dspring-boot.run.fork=false spring-boot:run

**Comment by snicoll** [comment]
A [section has been added](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#fork-enabled-by-default-in-maven-plugin) in the release notes.
