### ISSUE TITLE
Documentation does not make it clear that micrometer-registry-prometheus dependency is required to use the prometheus endpoint

### ISSUE THREAD

**Issue by benweizhu** [spring-projects/spring-boot#18633]
Hi,

I follow the spring boot actuator [Spring Boot Document](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready) to use Prometheus endpoint. 

But it doesn't show until I add the micrometer-registry-prometheus dependency in my gradle build.

```
implementation 'io.micrometer:micrometer-registry-prometheus'
```

And this doesn't mention in the document?

**Comment by wilkinsona** [comment]
Thanks for the report. I can see how the table in the documentation is misleading here as it states that a number of endpoints are enabled by default but that's only true when a required dependency or bean is also available. We documented this in https://github.com/spring-projects/spring-boot/issues/18352 for the `httptrace` and `auditevent` endpoints. We probably need to apply that approach consistently across all of the endpoints or take a different approach.

**Comment by wilkinsona** [comment]
We're going to remove the misleading enabled by default column and add some more information where needed in the description.
