### ISSUE TITLE
Some links to "current" are broken

### ISSUE THREAD

**Issue by objectbakery** [spring-projects/spring-boot#18642]
E.g. google "spring boot externalize properties"

First search result is https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

The link returns a 404 not found!

**Comment by wilkinsona** [comment]
The documentation was re-structured a bit in 2.2 and Google hasn't caught up yet, unfortunately. The correct URL is https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config. Let's see if we can do something to smooth things out.

**Comment by andrebraitc** [comment]
Could you guys add some redirection to some index of a section or something? Or redirect links in the old format to documentation for 2.1.9.RELEASE (or latest 2.1)?

That change broke basically every link to "current" Spring documentation out there.

I know it's not a real issue, though

**Comment by wilkinsona** [comment]
Redirects are now in place so you should on longer get 404s for any current documentation links. Please let us know if that's not the case.

**Comment by snicoll** [comment]
Someone in the community found a candidate: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html should redirect to https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

**Comment by snicoll** [comment]
The links to appendixes are working again.
