### ISSUE TITLE
Spring 2.2 Hibernate Dialect - PostgreSQL

### ISSUE THREAD

**Issue by 4val0v** [spring-projects/spring-boot#18641]
Was updated today to version 2.2

The release notes say:
> **Hibernate Dialect**
Spring Boot now lets Hibernate chose the dialect to use rather than applying a default dialect based on the detected database. If you had a dialect configured previously, you may want to remove your customization.

I am using Java 11 & PostgreSQL 11, but the dialect used by version 9.5 :(
`2019-10-17 19:36:40.915  INFO 8929 --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect`

Why does this happen if I see Hibernate v5.4.6 in packages and there is a dialect for version 10 that can work with `GENERATED BY DEFAULT AS IDENTITY?`

It is necessary to employ a configuration: `spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect`

**Comment by wilkinsona** [comment]
If you haven't configured the dialect anywhere then this is likely to be a Hibernate problem. You could place a breakpoint in the `resolveDialect` method of `org.hibernate.dialect.Database.POSTGRESQL` and step through the process of it selecting the dialect to use. It looks as if `DialectResolutionInfo.getDatabaseMajorVersion()` must be returning 9 for the major version.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mdeinum** [comment]
@wilkinsona Isn't this hardcoded in the [`HibernateJpaVendorAdapter`](https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/jpa/vendor/HibernateJpaVendorAdapter.java#L195)? Which is configured by the `HibernateJpaConfiguration` and used by the `LocalContainerEntityManagerFactoryBean` to determine the dialect if none has been explicitly set. 

This would mean that the `spring.jpa.database` properties has been set in the project for this to work. 

@4val0v could you provide information on the usage of the `spring.jpa.database` property?

**Comment by 4val0v** [comment]
> could you provide information on the usage of the `spring.jpa.database` property?

`spring.jpa.database=postgresql`

**Comment by snicoll** [comment]
@4val0v if you specify the database platform we'll use that rather than letting Hibernate figure out what the dialect it should be. I've updated the release notes [to make that more explicit](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#hibernate-dialect).
