### ISSUE TITLE
Actuator health check groups allow to specify checks only in lower case

### ISSUE THREAD

**Issue by sonatdev** [spring-projects/spring-boot#18649]
Spring Boot **2.2.0.RELEASE** provides possibility to separate health checks by different groups 
([docs](https://docs.spring.io/spring-boot/docs/2.2.0.BUILD-SNAPSHOT/reference/html/production-ready-features.html#health-groups))

However is's impossible to add a health check with a camel case name (e.g. the built-in discSpace health check) 
because its name is trimmed and converted to lower case before checking if the group contains it or not.
Take a look at the [IncludeExcludeGroupMemberPredicate](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/IncludeExcludeGroupMemberPredicate.java) 
class (`clean` method).

If the following configuration is used only the `ping` health check is executed.
```
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
```

**Comment by snicoll** [comment]
Thank you very much for reporting it @sonatdev.
