### ISSUE TITLE
ConfigurationProperties with constructor binding cannot be mocked

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#18652]
I have migrated https://spring.io/guides/tutorials/spring-boot-kotlin/ to Spring Boot `2.2.0.RELEASE` and updated it to leverage immutable configuration properties. As discussed with @snicoll, `@ConfigurationProperties` are not scanned by default in test slices, so I have to add to my `@WebMvcTest` test either `@EnableConfigurationProperties(BlogProperties::class)` or mock `BlogProperties` bean.

My test works with `@EnableConfigurationProperties(BlogProperties::class)` but fails if I try to mockk `BlogProperties` bean (in my case with `@MockkBean` from https://github.com/Ninja-Squad/springmockk) with following error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.blog.BlogProperties#0': @EnableConfigurationProperties or @ConfigurationPropertiesScan must be used to add @ConstructorBinding type com.example.blog.BlogProperties
```

**Comment by snicoll** [comment]
Interesting data point is that it only fails if `@ConstructorBinding` is set on the type. If the annotation is set on the constructor, then the error goes away. I have a hunch that this is directly related to #18685

**Comment by snicoll** [comment]
And I was wrong. It works because the mock does not have any annotation that are on the target type so the current validation does not apply.

**Comment by philwebb** [comment]
@sdeleuze Have you got a branch somewhere we can look at?

**Comment by snicoll** [comment]
@philwebb that wasn't obvious from my previous comment but that's not Kotlin specific as far as I can see. I didn't try with Kotlin so can't say but that's what seems to happen with plain Java, see https://github.com/snicoll-scratches/test-mock-config-props

If the annotation is found in both cases, it will fail in both cases whereas this issue is about it not failing at all. If a bean is mocked, the verification should not check for the bind method anyway.

**Comment by sdeleuze** [comment]
@philwebb Sadly not anymore, it was on my laptop which was stolen last week.

**Comment by philwebb** [comment]
:(

**Comment by davinkevin** [comment]
Same thing for me with mockito btw (in kotlin too, not tested in java).

**Comment by mbhave** [comment]
@sdeleuze @davinkevin I've pushed a fix for this. Could you verify if this works for you? Thanks.

**Comment by snicoll** [comment]
@mbhave the sample I built for this now works with `master`. Thanks!
