### ISSUE TITLE
Spring Boot 2.2 release notes mentions 'far jars'

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#18655]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes has the line:

> Zip64 files are now supported inside "Far Jars".

Which should probably be

> Zip64 files are now supported inside "Fat Jars".

I guess?

**Comment by wilkinsona** [comment]
@wimdeblauwe Thank you. I've corrected the typo.
