### ISSUE TITLE
Spring Data R2DBC ReactiveCrudRepository.save() method is not working even with method / class level @Transactional annotation

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-boot#18664]
Hello,

Please, let me know if spring-data-r2dbc transactions by default are read only?
For some reasons, data cannot be saved when I do it using ReactiveCrudRepository like so:

```java
    @Transactional
    @ResponseBody
    @PostMapping("/sessions")
    public Mono<Session> save(@RequestBody Session session) {
        return Mono.just(session)
                   .filter(s -> Objects.nonNull(s.getName()))
                   .filter(s -> Objects.nonNull(s.getSpeakers()))
                   .map(s -> Objects.isNull(s.getId()) ? s.setId(UUID.randomUUID()) : s)
                   .flatMap(sessionRepository::save);
    }
```

I have prepared a repo, and that par is present, but commented [here](https://github.com/daggerok/from-zero-to-reactive-cloud-micro-hero/blob/f0229503e862b45eee8b6599ac4d730ef4dcf4e9/step2-sessions-rsocket-service/src/main/java/com/github/daggerok/hero/rsocket/RSocketSessions.java#L45). Cannot understand, why it cannot be committed... but anyway, data can be successfully saved in database if I'm using DatabaseClient for that:

```java
    @ResponseBody
    @PostMapping("/sessions")
    public Mono<Integer> save(@RequestBody Session session) {
        return Mono.just(session)
                   .filter(s -> Objects.nonNull(s.getName()))
                   .filter(s -> Objects.nonNull(s.getSpeakers()))
                   .map(s -> Objects.isNull(s.getId()) ? s.setId(UUID.randomUUID()) : s)
                   .flatMap(s -> client.execute("INSERT INTO sessions (id, name, speakers) VALUES ($1, $2, $3)")
                                       .bind("$1", s.getId())
                                       .bind("$2", s.getName())
                                       .bind("$3", s.getSpeakers())
                                       .fetch().rowsUpdated());
    }
```

full code located [here](https://github.com/daggerok/from-zero-to-reactive-cloud-micro-hero/blob/f0229503e862b45eee8b6599ac4d730ef4dcf4e9/step2-sessions-rsocket-service/src/main/java/com/github/daggerok/hero/rsocket/RSocketSessions.java#L40)

_versions_

* spring-boot **2.2.0.RELEASE**
* spring-boot-starter-data-r2dbc: **0.1.0.BUILD-SNAPSHOT**
* r2dbc-postgresql: **0.8.0.RC2**

Is it bug or I missed something? 
Thanks!

---
Regards,
Maksim

**Comment by wilkinsona** [comment]
Spring Data R2DBC is managed as a [separate project](https://github.com/spring-projects/spring-data-r2dbc).

**Comment by daggerok** [comment]
Hello @wilkinsona 
Created there issue here: https://github.com/spring-projects/spring-data-r2dbc/issues/218
