### ISSUE TITLE
Spring Boot 2.2 migration guide not mentioning deprecated server.use-forward-headers

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#18667]
The Spring Boot 2.2 migration guide (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22) is not mentioning that `server.use-forward-headers` is now deprecated. (I noticed it because IntelliJ marked it in my `application.properties` file).

I found that it is related to https://github.com/spring-projects/spring-boot/issues/5677 and has been replaced with `server.forward-headers-strategy` which has options `native`, `framework` or `none`.

I mainly would like to know what I should use if I have the current setting at `true`. Should I use `native` or `framework` and what is the difference?

**Comment by bclozel** [comment]
Hi @wimdeblauwe , I've just added a note in the section of the wiki you were referring to.
If you'd like to get the exact same experience as before, `native` is probably the best choice.

However, if you'd like to get a consistent behavior while switching servers, or if you're interested in proper `"Forwarded"` headers support, the `framework` option should be of interest.
