### ISSUE TITLE
`/actuator/health` returns 404 if no indicator is present

### ISSUE THREAD

**Issue by aprantl** [spring-projects/spring-boot#18676]
I am just upgrading our application to Spring Boot 2.2.0. I am basically following the release notes at:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes
As far as I can see, there is only one behavioral change missing in the documentation.

In my Spring Boot 2.1 application, I had disabled the heath endpoint defaults with:
`management.health.defaults.enabled=false`
This disabled all health indicators apart from from the `ApplicationHealthIndicator`.

Now with Sprint Boot 2.2, the same endpoint returns a 404 HTTP response. My other applications still work the same because they additionally define some custom health indicators.

It seems to be related to the following fix:
https://github.com/spring-projects/spring-boot/issues/17926
It is now always added. But it seems disabled with the defaults. According the `HealthContributorAutoConfigurationTests` the behavior was changed intentionally, and as such it should be added to the release notes IMHO.

**Comment by weiwensangsang** [comment]
@philwebb I am new here. I want to fix it as my first work. Can I do it?

**Comment by philwebb** [comment]
@weiwensangsang Thanks for the offer but this is part of the release notes on the WIKI and as such it's a little hard to contribute to.

**Comment by snicoll** [comment]
We've discussed this one today and while we have to document the effect of disabling the health indicators, having no indicator shouldn't lead to a 404. It's inconsistent with JMX and having the endpoint disappearing (from an HTTP client’s perspective) doesn’t make sense.

We've decided to return a simple `UP` with no further details in this case.
