### ISSUE TITLE
Documentation for DevTools Global Settings has a typo when displaying spring.devtools.restart.trigger-file property example

### ISSUE THREAD

**Issue by ddcruver** [spring-projects/spring-boot#18679]
In https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-globalsettings it lists the file as ~/config/spring-boot/spring-boot-devtools.properties but I think that it should be ~/.config/spring-boot/spring-boot-devtools.properties.

**Comment by snicoll** [comment]
@ddcruver good catch, thanks for reporting it.
