### ISSUE TITLE
Support commas embedded in command line arguments from Maven plugin

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#18688]
It's actually impossible (as far as I can tell) to specify a command line argument that has a comma embedded in it. The comma is swallowed by Maven and turned into a value separator.

E.g.

```
$ mvn spring-boot:run -Dspring-boot.run.arguments='--management.endpoints.web.exposure.include=prometheus,info,health,metrics'
```

only exposes one endpoint.

Other Maven plugins seem to make configuration properties of type `String` and parse them out to a `String[]` manually. Example: http://maven.apache.org/plugins/maven-site-plugin/site-mojo.html#locales. We would have to document an escape sequence, or alternative separator.

**Comment by philwebb** [comment]
I think we should consider this a bug, but I'm worried it might involve making a breaking change. I'll target it to 2.2.x for now.

**Comment by philwebb** [comment]
Closing in favor of PR #18711
