### ISSUE TITLE
Make Kubernetes detection slightly more efficient

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#18681]
In #15537 we implemented a kubernetes detector based on an env var pattern. But 99.99% of the time `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` will be defined, and they can be looked up quickly without looping around the enumerable property source. The negative case, unfortunately, remains inefficient.

**Comment by dsyer** [comment]
https://stackoverflow.com/a/54130803/1368236

I like this one:

```
if File.exists?('/var/run/secrets/kubernetes.io')
  puts "I'm also running in a Kubernetes pod"
end
```

That's cheap and efficient.
Probably. I guess if `/var/run/secrets` exists and is network attached it might be slow.

**Comment by philwebb** [comment]
Thomas Risberg also suggested `/var/run/secrets/kubernetes.io/serviceaccount/namespace` that even gives you the namespace

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

**Comment by mbhave** [comment]
Closing in favor of PR #19002.
