### ISSUE TITLE
ConfigurationPropertiesBean detects class-level @ConstructorBinding unexpectedly

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18685]
Consider the following:

```java
@ConfigurationProperties("test")
@ConstructorBinding
public class TestProperties {

    public TestProperties(String property, int counter) { ... }

}
```

And the current code:

https://github.com/spring-projects/spring-boot/blob/d254c6271253c57383e351998ffdd97b2d385c99/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBean.java#L247-L248

`BindMethod.findBindConstructor(TestProperties.class)` will return `null` as it does not test the fact `@ConstructorBinding` is specified at class level. However, `BindMethod.forClass(type)` will work as it has the extra assertion. 

The current code arrangement feels a bit weird considering we have a dedicated method to retrieve the relevant constructor and that returns `null` whereas it shouldn't.

**Comment by snicoll** [comment]
An additional note that the binder takes any constructor when built in such a mode (i.e. I don't see an immediate check that only one relevant constructor is present).

**Comment by snicoll** [comment]
At this point, I don't understand why we store a `Predicate<Constructor<?>>` rather than the `Constructor<?>` to use effectively as this information is statically defined and we have access to that.

**Comment by mbhave** [comment]
I think this can be refactored as part of #18670. There are a few bugs covered by [these tests](https://github.com/mbhave/spring-boot/commit/2b5acdb050a86856b3da220975e3820995b5b8e6#diff-761785337e4b4f3079fb437baf65b453R852-R897) which might involve touching a lot of that code.
