### ISSUE TITLE
Configure Flyway for multiple datasource migrations

### ISSUE THREAD

**Issue by muhammad-zpw** [spring-projects/spring-boot#18699]
I recently work in a project that require multiple data source in one Spring boot application. Obviously, I need migration mechanism for both data sources. I've took a look into Flyway auto-configuration here: https://github.com/spring-projects/spring-boot/blob/4d5d90847e7b6c9f3206a9ff0488ffd57d05f205/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java

As far as I understand the code, It seems like it only handle migration from one and only datasource. It would be great if we can do this via auto-configuration. 

I still don't have a good idea to design the API, but what comes in my mind now is we can add a configuration like this:
```java
@Configuration
class FlywayConfiguration {
    @Primary
    @FlywayDataSource(config = "PrimaryDataSourceConfig.class")
    public DataSource primaryDataSource() {
        ...
    }
    @FlywayDataSource(config = "SecondDataSourceConfig.class")
    public DataSource secondDataSource() {
        ...
    }    
}
```
If we declare several beans with `@FlywayDataSource` the auto-configuration will automatically configure those those datasource for us. I really appreciate for the help. Thanks.

**Comment by wilkinsona** [comment]
We'll consider this as part of #15732.
