### ISSUE TITLE
BootWar doesn't correctly represent its contents when used as CopySpec

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#18709]
The `bootWar` gradle task doesn't correctly represent its own contents when used as CopySpec.

When the `bootWar` task is used as argument to [`CopySpec.with()`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/CopySpec.html#with-org.gradle.api.file.CopySpec...-) the loader (org/springframework/boot/loader/**) is missing and the META-INF/MANIFEST.MF is different.

### Reproducible example

```gradle
plugins {
    id "war"
    id "org.springframework.boot" version "2.1.9.RELEASE"
}

// dependencies ...

task unzip1(type: Sync) {
    into "build/unzip1"
    with bootWar
}

task unzip2(type: Sync) {
    into "build/unzip2"
    from project.zipTree(bootWar.archiveFile)
    dependsOn bootWar
}
```
I'd expect that both `unzip1` and `unzip2` produce the same output.
The output of `unzip1` doesn't contain the `org/springframework/boot/loader` folder and its MANIFEST.MF is missing the `Main-Class`, `Start-Class` and `Spring-Boot-*` entries.

### Background

I'm trying to add the exploded war file to a gradle distribution like so:

```
distributions {
    main {
        contents.into("my-awesome-boot-app") {
            with bootWar
        }
    }
}
```

My current workaround is to zip and then unzip the war file (like in `unzip2` above) and to set up some task dependencies manually:

```gradle
installDist.dependsOn bootWar
distZip.dependsOn bootWar
distTar.dependsOn bootWar
```

**Comment by wilkinsona** [comment]
It isn't possible for BootJar or BootWar to behave as a CopySpec due to the custom handling of nested archives, prepending the launch script, etc. You'll need to stick with your current approach I'm afraid.

**Comment by larsgrefer** [comment]
> You'll need to stick with your current approach I'm afraid.

In this case, this restriction should be documented somewhere.

Would it be possible log a warning or even throw an exception if a BootWar or BootJar instance is used as CopySpec somehere?

**Comment by wilkinsona** [comment]
> In this case, this restriction should be documented somewhere.

I think this is too much of an edge-case to warrant an entry in the reference documentation. Until we see evidence of lots of people being affected, this issue will suffice.

> Would it be possible log a warning or even throw an exception if a BootWar or BootJar instance is used as CopySpec somehere?

I don't know. I suspect it either isn't possible or it would require overriding every method on `CopySpec` at which point I don't think the benefit would be worth it.

**Comment by larsgrefer** [comment]
I'm afraid you're right.
Thanks for the fast response.
