### ISSUE TITLE
Check if we can reduce the code required to get an overall Health status

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18712]
This is a follow-up of https://github.com/spring-projects/spring-boot/issues/18194#issuecomment-539337300

In the related PR, the code that is required to get the overall status [in 2.2 is more involved](https://github.com/micrometer-metrics/micrometer-docs/pull/100/files#diff-5337bb90e2bfbdc9b9194632ce5ee82aR49-R94) than [it used to be with 2.1](https://github.com/micrometer-metrics/micrometer-docs/pull/100/files#diff-5337bb90e2bfbdc9b9194632ce5ee82aR21-R40).

**Comment by bono007** [comment]
@snicoll 
What are your thoughts about adding `@Configuration` w/ `@ConditionalOnProperty` that exposes this overall health as  a Gauge - basically take the [code from the doc](https://github.com/micrometer-metrics/micrometer-docs/pull/100/files#diff-5337bb90e2bfbdc9b9194632ce5ee82aR51) and guard it w/ the conditional. We would have to allow customization of the mapped status codes. Also, it only support single health indicators.

Another thought is to have a higher level abstraction for the metric provider - a bean/class like https://github.com/micrometer-metrics/micrometer-docs/pull/100/files#diff-5337bb90e2bfbdc9b9194632ce5ee82aR61 - but also add support for composites.

I would not mind working this ticket.

**Comment by snicoll** [comment]
@bono007 I personally thing we need to craft the API in such a way that computing the overall status is as easy as before. Anything in between where we take that complexity on our side is hiding the underlying problem (if there is one) IMO. I haven't looked in more details so can't say right now but I'd rather rework the API.

**Comment by philwebb** [comment]
I fixed the Micrometer documentation by injecting the `HealthEndpoint` and using that directly (see #18329). I'll close this one for now unless that approach turns out to be too limited.
