### ISSUE TITLE
configprops error when jobscope defined in configuration

### ISSUE THREAD

**Issue by guillaumeyan** [spring-projects/spring-boot#18714]
I recently update my spring boot app 2.1.9 to 2.2.0 that use Spring Batch. When i'm calling "configprops" from actuator endpoint, an exception is throw :
Scope 'job' is not active for the current thread

I reproduce the bug : https://github.com/guillaumeyan/bugspringbatch (just launch the test). Original project come from https://github.com/spring-guides/gs-batch-processing/tree/master/complete

```
ExceptionHandlerExceptionResolver[199] - Resolved [org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'scopedTarget.dossierToDiagnosticReader': Scope 'job' is not active for the current thread; 
consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for job scope]
```

**Comment by philwebb** [comment]
Thanks very much for the sample @guillaumeyan, it made tracking down the bug much easier. I've pushed a fix for Spring Boot 2.2.1.
