### ISSUE TITLE
Failure analysis description for BeanDefinitionOverrideExceptions includes useless information when a bean definition has no resource description

### ISSUE THREAD

**Issue by fabiomilson** [spring-projects/spring-boot#18721]
Hello, I come to report that the following bug can be reproduced (Spring Boot 2.2.0.RELEASE):

1 - Use the dependencies:
  spring-boot-starter-data-jdbc, spring-boot-starter-data-jpa, spring-boot-starter-web, spring-boot-devtools, mysql-connector-java, lombok, spring-boot-starter-test, junit-vintage-engine

2 - Create a repository interface and extending entity JpaRepository

3 - Following error is displayed when starting the spring application using Spring Tool Suite 4:
          **The bean 'personRepository', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.**

4 - When removing the **spring-boot-devtools** dependency the error no longer occurs.

5 - When starting the spring application with the spring-boot-devtools dependency it is possible to verify that the application's Main method is invoked twice.

6 - Example: 
`public static void main (String [] args) {
System.out.println ("test");
SpringApplication.run (XXXApplication.class, args);
}`

[example.zip](https://github.com/spring-projects/spring-boot/files/3765319/example.zip)

**Comment by philwebb** [comment]
@fabiomilson Thanks for the report. The root cause of the error is the fact that two Spring Data projects are active and both are trying to implement the `PersonRepository`.

I assume you just want JPA so you can remove the following lines from your `pom.xml`:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jdbc</artifactId>
</dependency>
```

The error message is quite unhelpful, so I'll leave this issue open to see if we can improve that.

**Comment by wilkinsona** [comment]
> When removing the spring-boot-devtools dependency the error no longer occurs.

FWIW, I see the same failure both with and without DevTools.

**Comment by mp911de** [comment]
This is an issue in Spring Data JDBC that is going to be addressed with [DATAJDBC-437](https://jira.spring.io/browse/DATAJDBC-437).

**Comment by odrotbohm** [comment]
We've got [~~DATACMNS-1596~~](https://jira.spring.io/browse/DATACMNS-1596) and [~~DATAJDBC-437~~](https://jira.spring.io/browse/DATAJDBC-437) fixed and ready for the Spring Data service release that will make it into Spring Boot 2.2.1. Feel free to give the snapshots a try by setting `spring-data-releasetrain.version` to either `Moore-BUILD-SNAPSHOT` or `Neumann-BUILD-SNAPSHOT` (prefer the former for better chance of compatibility).
