### ISSUE TITLE
Break up AutoConfigurations that declare a SpringSecurityFilterChain 

### ISSUE THREAD

**Issue by philsttr** [spring-projects/spring-boot#18731]
As a workaround for #18507, I'm trying to create a custom AutoConfiguration class to be used by lots of our apps that configures a `SecurityWebFilterChain` with the OAuth2 client, OAuth2 resource server, and some other things configured.  

Unfortunately, I'm running into a circular startup problem.

In order for my AutoConfiguration class to "win" the race to create a `SecurityWebFilterChain`, it must be processed _before_ the `ReactiveOAuth2ResourceServerAutoConfiguration` and the `ReactiveOAuth2ClientAutoConfiguration`, since those also declare a `SecurityWebFilterChain`.

However, I want my AutoConfiguration to rely on the beans created by `ReactiveOAuth2ResourceServerJwkConfiguration.JwtConfiguration` or `ReactiveOAuth2ResourceServerOpaqueTokenConfiguration.OpaqueTokenIntrospectionClientConfiguration`, which are both package-private and imported by `ReactiveOAuth2ResourceServerAutoConfiguration`.

Therefore, I have a circular startup problem.

My desired startup order is:
1. Everything in `ReactiveOAuth2ClientAutoConfiguration` and `ReactiveOAuth2ClientAutoConfiguration` _except_ the definition of the `SecurityWebFilterChain` bean
2. My AutoConfiguration that declares a `SecurityWebFilterChain`, and relies on beans declared from step 1
3. The remaining portion of `ReactiveOAuth2ClientAutoConfiguration` and `ReactiveOAuth2ClientAutoConfiguration` that conditionally declares the  `SecurityWebFilterChain`, which will back-off, since I declared it in my AutoConfiguration

One solution to this would be to break up `ReactiveOAuth2ResourceServerAutoConfiguration` and `ReactiveOAuth2ClientAutoConfiguration` into separate auto-configuration classes (one for step 1 above, and one for step 3 above)   They already are broken up internally.  We would just need to "promote" that internal breakup up a level to the AutoConfiguration classes.

In general, since spring-boot does not provide a contribution model for `SpringSecurityFilterChain`/`ServerHttpSecurity` (see #18507 ), I would like to propose the following practice:
1. Standard AutoConfigurations provided by spring boot that declare a `SpringSecurityFilterChain` bean should _only_ declare
   * the `SpringSecurityFilterChain`, and 
   * (optionally) other beans that depend-on that `SpringSecurityFilterChain`.
2. Separate AutoConfigurations should be provided by spring boot that declare any beans required to configure the `SpringSecurityFilterChain` from 1

This will allow user-defined AutoConfigurations to utilize most of the standard spring-boot auto configuration logic, but still "win" the race to create a `SpringSecurityFilterChain`

**Comment by mbhave** [comment]
@philsttr I'm not sure why there's a circular problem. If I understood correctly, you want to be able to inject beans from `ReactiveOAuth2ResourceServerOpaqueTokenConfiguration` (which would be `NimbusReactiveOpaqueTokenIntrospector`) and `ReactiveOAuth2ResourceServerJwkConfiguration` (which would be `ReactiveJwtDecoder`) in your custom `SecurityWebFilterChain` bean definition. At first glance, it seems like you should be able to do that and have the auto-configured `SecurityWebFilterChain` back off. Maybe there's something I'm missing here. Could you provide a small sample that we can run to help reproduce the issue you're seeing?

**Comment by philsttr** [comment]
@mbhave , the key here is that I'm defining an AutoConfiguration class in an autoconfigure library for reuse by multiple applicaitons, not a regular configuration class in an application.

I believe it would work when defining a `SecurityWebFilterChain` bean in a regular configuration class in an application, but that's not what I'm trying to do.

I'll see if I can come up with a small example app.

**Comment by philsttr** [comment]
Here is an example project with failing unit tests that show the circular startup ordering problem.

[security-web-filter-chain-demo.zip](https://github.com/spring-projects/spring-boot/files/3769916/security-web-filter-chain-demo.zip)

The custom `SecurityWebFilterChainAutoConfiguration` in the project should work with either JWTs or Opaque Tokens, similar to `ReactiveOAuth2ResourceServerAutoConfiguration`.  It utilizes `ServerHttpSecurityCustomizer`s to contribute to the `ServerHttpSecurity`.

**Comment by mbhave** [comment]
Thank you for the sample @philsttr. I had indeed missed the fact that you were defining the custom `SecurityWebFilterChain` in an Auto-configuration class. 

We discussed this on the team call and this feels like quite a specialized use-case to warrant the split. We don't expect too many people to be doing this in a custom Auto-configuration class. In this case, I think it's best for you to copy the configuration from `ReactiveOAuth2ResourceServerJwkConfiguration` and `ReactiveOAuth2ResourceServerOpaqueTokenConfiguration` into your Autoconfiguration.

**Comment by philsttr** [comment]
Sigh.  I have to respectfully disagree that this is a specialized use case.  Since spring-boot doesn't provide a contribution model to the SecurityWebFilterChain, I can only assume that others will try the same thing.

And it's not just `ReactiveOAuth2ResourceServerJwkConfiguration`, and `ReactiveOAuth2ResourceServerOpaqueTokenConfiguration`.  It's also `ReactiveOAuth2ClientConfigurations.ReactiveClientRegistrationRepositoryConfiguration` and `ReactiveOAuth2ClientConfigurations.ReactiveOAuth2ClientConfiguration` (I didn't include those in the example, but the same concept applies), and potentially other future AutoConfigurations that we want to use that also declare `SecurityWebFilterChain`s.

Can you at least consider making those inner classes public, so I don't have to copy/paste code, and can just import them in my AutoConfiguration class?   All this copy/paste is going to become unwieldy very quickly, and we'll constantly have to revisit it on each spring-boot upgrade.

**Comment by mbhave** [comment]
Let me reopen the issue so that the team can consider making these classes public. The other option I can think of for your case is to use an `ObjectProvider` for the beans that you want from Spring Boot's auto-configuration. So instead of having `@ConditionalOnBean(ReactiveJwtDecoder.class)` you could do something like

```java
@Bean
ServerHttpSecurityCustomizer httpSecurityCustomizer(ObjectProvider<ReactiveJwtDecoder> jwtDecoder, ObjectProvider<ReactiveOpaqueTokenIntrospector> introspector) {
	if (jwtDecoder.getIfAvailable() != null) {
		return http -> http.oauth2ResourceServer(
			resourceServerSpec -> resourceServerSpec.jwt(jwtSpec -> jwtSpec.jwtDecoder(jwtDecoder.getIfAvailable())));
	}
	if (introspector.getIfAvailable() != null) {
		return http -> http.oauth2ResourceServer(
			resourceServerSpec -> resourceServerSpec.opaqueToken(
				opaqueTokenSpec -> opaqueTokenSpec.introspector(introspector.getIfAvailable())));
	}
	return http -> http.authorizeExchange(
		exchanges -> exchanges.anyExchange().authenticated());
	}
}
```

This could be done in combination with a `@AutoConfigureBefore(ReactiveOAuth2ResourceServerAutoConfiguration.class)`

**Comment by philsttr** [comment]
I've implemented a solution using `ObjectProvider`, similar to what you have mentioned.  I'm not 100% happy with it, but it'll work.

You can close this issue.

My only remaining request is that the spring-boot team consider the challenges with auto-configuring the `SpringSecurityFilterChain`.  i.e. the fact that only one auto-configuration will "win".  Anything that can be done in the future to help this would be greatly appreciated.
