### ISSUE TITLE
Reactive HealthContributors do not hide non-reactive ones

### ISSUE THREAD

**Issue by hban** [spring-projects/spring-boot#18748]
Lettuce connection factory, which is both reactive and non-reactive, has two active health indicators when running Boot 2.2.0.

Output of `/actuator/health`:

```
{ 
   "status":"UP",
   "components":{ 
      "redis":{ 
         "status":"UP",
         "details":{ 
            "cluster_size":2,
            "slots_up":16384,
            "slots_fail":0
         }
      },
      "redisReactive":{ 
         "status":"UP",
         "details":{ 
            "version":"5.0.5"
         }
      }
   }
}
```

Only reactive indicator was active in Boot 2.1.

**Comment by nosan** [comment]
@philwebb,
It looks like that bug affects all `HealthIndicators`, not only `Redis`.

Previously, `@ConditionalOnMissingBean(name="...")` was the same for both indicators.

More is here:  f09e0264d9195f6c4dacabe07a51836058092dbf
