### ISSUE TITLE
@SpringBootTest + @MockBean + custom annotation extending @SpringExtension fails with BeanCreationException

### ISSUE THREAD

**Issue by camhashemi** [spring-projects/spring-boot#18758]
Spring Boot Version: 2.2.0.RELEASE
Language: Kotlin

Example project here: https://github.com/camhashemi/mock-bean-spring-boot-test-failure

I have a SpringBootTest where I would like to use an @MockBean for one of my dependencies.

I also have a custom annotation which extends SpringExtension, which I use to override `beforeTestExecution` and run some test setup.

The custom annotation leads to `TestContextManager.prepareTestInstance` being called twice, which calls `MockitoTestExecutionListener.prepareTestInstance` twice, which seems to inject the mocked class twice, throwing the exception on the second run.

Is there a better method for extending `SpringExtension` and overriding `beforeTestExecution` in a customizable way?

**Comment by wilkinsona** [comment]
Thanks for the sample. I note from the discussion on Gitter that you have got this working:

> okay, fixed it by extending TestExecutionListener instead of SpringExtension. Not sure if this is a still a bug on SpringExtension, but wanted to update for completeness.

With the previous arrangement you were using `SpringExtension` twice. Once via `@SpringBootTest` and once via your custom annotation. I'm a little surprised that this results in the extension being called twice, but that's a matter for the JUnit team as it's out of Spring Boot's control. I'll cc @sbrannen from that team (and the Spring Framework team) as he may be interested in this.

**Comment by camhashemi** [comment]
@sbrannen note that this doesn't lead to any issues until you start using @MockBean, which seems like it's not idempotent.
