### ISSUE TITLE
Application.properties not reading data from environment variables

### ISSUE THREAD

**Issue by danieldonev** [spring-projects/spring-boot#18768]
After update to spring-boot 2.2.0, the application.properties is not picking the values from the java env variables

application.properties
 ```server.port=${PORT}```

running the application
```mvn -DPORT=8080 spring-boot:run```

The error I get is the following:

```Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'PORT' in value "${PORT}"```

When I downgrade to 2.1.9 it works properly.

Can someone check if that is a bug or something that I am doing wrong?

**Comment by snicoll** [comment]
Thank for the report, this is covered in [this section of the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#fork-enabled-by-default-in-maven-plugin).

**Comment by danieldonev** [comment]
My apologies. I really didn't see that part. Thank you for reply @snicoll !
