### ISSUE TITLE
Possible form based PUT request regression

### ISSUE THREAD

**Issue by erbrecht** [spring-projects/spring-boot#18760]
Spring Boot Version: 2.2.0.RELEASE  
Template Engine: Thymeleaf

I was in the process  of updating an application to 2.2.0.RELEASE, from 2.0.2.RELEASE. Everything worked as expected, except submitting HTML forms with the PUT method. I'm using Thymeleaf, so the hidden `_method` input field is present and being sent to the server. I get a 'method not supported' exception. This was working in 2.0.2, all the way up through 2.1.9.

I created a project that has 2 simple forms, one that uses POST, and one that uses PUT. I see this error when using the app via the web, and I also created some tests as well. There are 3 tests actually, one that POSTs the form data, one that PUTs the form data, and one that POSTs the form data with the `_method` parameter set to PUT. The first 2 work, the third does not.

The following repo has 2 branches: master (2.2.0.RELEASE) and 2.1.9 (2.1.9.RELEASE). Each has appropriate tests configured.

https://github.com/erbrecht/spring-boot-put-demo

I couldn't find anything related to this in release notes or in the issues. Did I miss some configuration change for this?

**Comment by wilkinsona** [comment]
Thanks for the sample. The change in behaviour is due to the `HiddenHttpMethodFilter` now being [disabled by default in Spring Boot 2.2](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#httphiddenmethodfilter-disabled-by-default):

> The filter that handles the `_method` request parameter is now disabled by default as it causes early consumption of a request body if the body may contain parameters. This can be restored by setting either `spring.webflux.hiddenmethod.filter.enabled` or `spring.mvc.hiddenmethod.filter.enabled` to true.

You are using Spring MVC so you should set `spring.mvc.hiddenmethod.filter.enabled=true`.
