### ISSUE TITLE
Must send only 1 link to update a property reference that isn't a List or a Map

### ISSUE THREAD

**Issue by blured75** [spring-projects/spring-boot#18776]
Hi,

Following this tutorial https://www.baeldung.com/spring-data-rest-relationships I'm trying to reproduce the link creation onetoone between 2 entities with a rest put call.

However I've got the following error message when I try to link addresses/1 & libraries/1/libraryAddress curl -i -X PUT -d "http://localhost:8080/addresses/1" -H "Content-Type:text/uri-list" http://localhost:8080/libraries/1/libraryAddress

"Must send only 1 link to update a property reference that isn't a List or a Map"

It happens also with trying to update OneToMany relations.

It's working correctly with 2.1.10.BUILD-SNAPSHOT but not 2.2.0.RELEASE

Is there a new way to generate the association with the 2.2.0.RELEASE ? Or is it a bug ?

Original question posted to stackoverflow : https://stackoverflow.com/questions/58601905/create-relation-link-one-to-one-between-2-entities-using-spring-data-rest?noredirect=1#comment103517712_58601905

Regards,
Denis.

**Comment by wilkinsona** [comment]
Thanks for the report. Spring Data REST is managed as a separate project from Spring Boot. They use [JIRA](https://jira.spring.io/browse/DATAREST) for issue tracking. Can you please open an issue there and comment here with a link to it so that we can follow along?
