### ISSUE TITLE
RemoteTokenServices. getAuthorizationHeader doesn't handle NULL clientId and clientSecret

### ISSUE THREAD

**Issue by yaddes-next** [spring-projects/spring-boot#18774]
Bug in RemoteTokenServices. getAuthorizationHeader.  If clientId or clientSecret is null, I would expect the request to be send without authorization header, instead the Header is always build with Basic authentication passing "null":"null"
Version: 2.3.7.RELEASE

**Comment by mbhave** [comment]
@yaddes-next It looks like you're referring to the [`spring-security-oauth`](https://github.com/spring-projects/spring-security-oauth) project which is managed separately.
