### ISSUE TITLE
Support MemCached

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#18813]
It would be nice with support (auto-configuration, actuator) for MemCached.
Although there is a rich choice of caching solutions for SB today, we favour MemCached due to it's simplicity and scalability features (which can be paired with [mcrouter](https://engineering.fb.com/web/introducing-mcrouter-a-memcached-protocol-router-for-scaling-memcached-deployments/) if a stronger feature-set is required.

There is a project here https://github.com/sixhours-team/memcached-spring-boot, it doesn't seem very active - but the configuration-approach is quite nice (especially the ability to configure TTL per cache declaratively) - maybe that code can be adopted?

**Comment by snicoll** [comment]
@nosan Thanks for the offer but it hasn't been triaged yet.

**Comment by davidkarlsen** [comment]
@snicoll Have you given this any though? Do you triage issues on a regular basis?

**Comment by snicoll** [comment]
@davidkarlsen sorry for the late reply.

Spring Boot merely auto-configures existing implementations of our cache abstraction and there isn't an obvious one I can see for memcached. There is one implementation in that starter but we can't really reuse that. You could ask for adding memcached to the list of libraries supported by Spring Framework although we have been focusing more on JCache lately.

There is nothing wrong with having a third party starter and if you like it, I'd suggest using that.
