### ISSUE TITLE
Remove 1.5.x from spring.io website

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#18819]
Hi,

I wasn't sure if that's something for spring-io/sagan or for Boot itself (or none of those), so forgive me if this is the wrong issue tracker for this particular issue:

I noticed that 1.5.22 is still shown under https://spring.io/projects/spring-boot#learn. Since 1.5.x is EOL, I guess it can (and probably should) be removed from there.

Let me know what you think.
Cheers,
Christoph

**Comment by philwebb** [comment]
Good spot. I've removed it.
