### ISSUE TITLE
Update documentation about endpoint enablement to reflect behaviour of @ConditionalOnAvailableEndpoint

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18814]
In 2.2, we introduced `@ConditionalOnAvailableEndpoint` so that an endpoint is now only auto-configured if it's available. Being available means that an endpoint is both enabled and exposed (made remotely accessible) over HTTP or JMX. The documentation is out of date at the moment as it states that an endpoint's enabled property "controls whether or not the endpoint is created and its bean exists in the application context".

**Comment by ericus20** [comment]
How can I take up this issue and work on it?

**Comment by mbhave** [comment]
@ericus20 Sure, I've assigned it to `spring-contributor` to indicate that you're working on it.

**Comment by ericus20** [comment]
This issue seems to be addressed already per the documentation I am seeing for https://docs.spring.io/spring-boot/docs/2.2.3.BUILD-SNAPSHOT/api/org/springframework/boot/actuate/autoconfigure/endpoint/condition/ConditionalOnAvailableEndpoint.html Please let me know if that is not correct.

**Comment by wilkinsona** [comment]
@ericus20 Thanks for taking a look. The problem is with the reference documentation rather than the javadoc. The section that I quoted above can be found [here](https://docs.spring.io/spring-boot/docs/2.1.11.RELEASE/reference/html/production-ready-endpoints.html).

**Comment by wilkinsona** [comment]
How's it going, @ericus20?

**Comment by spencergibb** [comment]
I think someone else needs to pick this up as we're seeing questions on the spring cloud side.

**Comment by ericus20** [comment]
Let me wrap up my changes and submit it for review this weekend. I had an emergency and sorry for the late response.

**Comment by wilkinsona** [comment]
Hi, @ericus20. How's it going? It's a weird time for everyone right now so no worries at all if you haven't been able to make the progress that you'd hoped to make. If you'd like someone else to pick this on up, please let us know.

**Comment by ericus20** [comment]
Hello, @wilkinsona I haven't been able to make the progress I hoped due to certain procedures I went through but I am currently able and willing to take it from here and will update it accordingly as I am cleared to work.

**Comment by wilkinsona** [comment]
Great stuff, thank you. We'll look forward to hearing from you soon. Please let us know if you have any questions.

**Comment by ericus20** [comment]
A PR has been created for this issue https://github.com/spring-projects/spring-boot/pull/20799

**Comment by wilkinsona** [comment]
Closing in favour of #20799.
