### ISSUE TITLE
Possible bug in @WebFilter when using @RequestBody parameters

### ISSUE THREAD

**Issue by guillermocalvo** [spring-projects/spring-boot#18836]
I am trying to make a reactive `@WebFilter` that executes stuff *before* and *after* the actual server exchange (i. e. the controller code handling the request):

```java
public static class Foobar implements WebFilter {

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        return Mono.empty()
                .doOnEach(s -> /* BEFORE */))
                .then(chain.filter(exchange) /* CONTROLLER */)
                .and(Mono.empty().doOnEach(s -> /* AFTER */))
                .and(Mono.empty().doFinally(s -> /* FINALLY */));
    }
}
```

Everything works as expected for simple `GET` requests that return a `Mono`:

```java
@RestController
@RequestMapping
public static class Foo {

    @GetMapping
    @PostMapping(value = "foo")
    public Mono<String> foo(ServerWebExchange exchange) {
        return Mono.just("FOOBAR").map(e -> "OK");
    }
}
```

But something really unexpected happens when the controller receives a parameter annotated as `@RequestBody`. Say, for example a `POST` request that takes a `Mono<String>` from the client:

```java
@RestController
@RequestMapping
public static class Bar {

    @PostMapping(value = "bar")
    public Mono<String> bar(ServerWebExchange exchange, @RequestBody Mono<String> text) {
        return text.map(s -> "OK");
    }
}
```

In this case, all steps in my filter are executed **before the controller gets to complete the request**. This means that the web exchange is committed independently of the filter and therefore I cannot do anything right after the response is sent back to the client.

I'm not exactly sure if this is an actual bug or maybe I am doing something wrong. In any case, I've created a small Gist containing a test case that reproduces the problem:

- <https://gist.github.com/guillermocalvo/740b4fcab471ebc6fe69227fee6d79d5>

**Comment by bclozel** [comment]
I think it's due to the choice of operators in your `WebFilter` - could you make that a proper [StackOverflow](https://stackoverflow.com/) question (and optionally point me to it?). Thanks!

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by guillermocalvo** [comment]
@bclozel https://stackoverflow.com/questions/58654059/how-to-make-reactive-webfilter-work-properly-with-requestbody
