### ISSUE TITLE
Rationalize RabbitProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18830]
#18808 will add support for `amqps://` support but we have `isEnabled`  and `getPort` methods that change depending on the address. Changing those to Object types and making them `null` might help us fix them.

**Comment by snicoll** [comment]
There are more features that are potentially misleading at the moment. To make things consistent, we've considered revisiting the description of such properties to mention that specifying an address takes precedence. 

As for the port it should be `Integer` in any case as it has two "default" values.

**Comment by wilkinsona** [comment]
Let's look at this for 2.3.0.M2.
