### ISSUE TITLE
HazelcastHealthContributorAutoConfiguration not bootstrapped

### ISSUE THREAD

**Issue by frichard35** [spring-projects/spring-boot#18846]
Hi,

one of the new features of Spring Boot 2.2.0 (Hazelcast Health Indicator) cannot work directly. In fact, there is not entry for the class : `org.springframework.boot.actuate.autoconfigure.hazelcast.HazelcastHealthContributorAutoConfiguration` In the corresponding 'spring.factories' neither import from the others Hazelcast auto-configuration classes. 

François

PS: thx again for this great release, with lot's of features useful for me.

**Comment by snicoll** [comment]
🤦‍♀️oh dear, good catch @frichard35.

Closing in favour of PR #18847
