### ISSUE TITLE
Rename spring-boot CI pipeline to include the version in its name

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18844]
The history of the spring-boot pipeline is a little confusing as it has built 2.1.x and 2.2.x. To avoid this problem in the future we decided that we should include the version number in the pipeline's name. The first step is to rename the spring-boot pipeline to be spring-boot-2.2.x.

When we create the 2.2.x branch and master becomes 2.3.x, we'd then:

- Create a new spring-boot-2.3.x pipeline 
- Update the CI config for the 2.2.x pipeline to point to the 2.2.x branch rather than master

**Comment by mbhave** [comment]
Blocked on master being switched to 2.3.x.

**Comment by wilkinsona** [comment]
Can't we do the first step now? That would be to rename our existing `spring-boot` pipeline to `spring-boot-2.2.x`.

**Comment by mbhave** [comment]
Yup I guess that doesn't need to wait. Taking the label off.
