### ISSUE TITLE
Improve JettyEmbeddedErrorHandler based on feedback from the Jetty team

### ISSUE THREAD

**Issue by Stephan202** [spring-projects/spring-boot#18842]
###### Context
No current release of Spring Boot is compatible with Jetty 9.4.21+. This was [fixed](https://github.com/spring-projects/spring-boot/blob/d0d55d3c0a2a6570b89da2ea55e1a7a185f5b417/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyEmbeddedErrorHandler.java) for the upcoming Spring Boot 2.2.1 and 2.1.10 releases, but an issue was filed against Jetty to raise awareness of the fact that the Jetty 9.4.21 release contains a backwards incompatible change; see eclipse/jetty.project#4264.

###### Reason for this issue
In response to the report Jetty maintainer @joakime reviewed Spring Boot's `JettyEmbeddedErrorHandler` implementation and suggested several improvements; see https://github.com/eclipse/jetty.project/issues/4264#issuecomment-548927847. A number of these recommendations also apply to the current Jetty 9.4.21-compatible implementation. In order to reduce the likelihood of future incompatibilities the Spring Boot team may wish to follow up on these.

**Comment by philwebb** [comment]
Thanks very much for the reference @Stephan202

**Comment by wilkinsona** [comment]
Some further changes are coming in 9.4.23. They current include a breaking change to throws clause of a method that we've been recommended to override. I've [asked](https://github.com/eclipse/jetty.project/issues/4264#issuecomment-549801671) the Jetty team for some further guidance.

**Comment by wilkinsona** [comment]
For the record, this is what `JettyEmbeddedErrorHandler` looks like with my understanding of the recommendations applied:

```java
class JettyEmbeddedErrorHandler extends ErrorPageErrorHandler {

	@Override
	public boolean errorPageForMethod(String method) {
		return true;
	}

	@Override
	public void doError(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		baseRequest.setMethod("GET");
		super.doError(target, baseRequest, request, response);
	}

}
```

The breaking change is that `super.doError(…)` throws a `ServletException` in 9.4.23 whereas it only threw an `IOException` in 9.4.22.
