### ISSUE TITLE
Jackson cannot serialize Spring class: MethodParameter

### ISSUE THREAD

**Issue by azuryy** [spring-projects/spring-boot#18853]
Jackson: 2.10.0
Spring boot: 1.5.13.RELEASE

I am using Jackson to serialize Spring class:
`org.springframework.core.MethodParameter`
it reports: 
`org.codehaus.jackson.map.JsonMappingException: Infinite recursion`

My code looks like:

```
ObjectMapper mapper = Jackson2ObjectMapperBuilder.json()
                .dateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"))
                .autoDetectGettersSetters(true)
                .failOnEmptyBeans(false)
                .failOnUnknownProperties(false)
                .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .featuresToEnable(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES)
                .build();
```

```
public static String toJSONString(Object obj) {
        Writer strWriter = new StringWriter();
        try {
            mapper.writeValue(strWriter, obj);
            return strWriter.toString();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
```
```
public class MyOperatorArgumentResolver implements HandlerMethodArgumentResolver {
  @Override
  public Object resolveArgument(MethodParameter parameter, 
                                ModelAndViewContainer mavContainer,
                                NativeWebRequest webRequest, 
                                WebDataBinderFactory binderFactory) throws Exception {
    System.out.println(toJSONString(parameter));   //----------> Infinite recursion here
    return xxxx;
  }
}
```
I asked Jackson team, they guys don't familiar with Spring, and advice me to file issue to Spring team.
Then I post here. Thanks!

**Comment by wilkinsona** [comment]
Thanks for the report, but `MethodParameter` isn't part of Spring Boot. It's a class from Spring Framework. I am not surprised that it cannot be serialised to JSON as it almost certainly won't have been designed to be used in that way. I would recommend that you either create your own object that capture the relevant parts of `MethodParameter` that is designed for JSON serialisation, or you plug a custom serialiser into Jackson that is capable of serialising a `MethodParameter` instance.
