### ISSUE TITLE
Migration guide 2.0.x to 2.1.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18887]
Forward port of issue #17532 to 2.2.1.

**Comment by izeye** [comment]
Based on the commit that closed this issue, the intended title seems to be "Improve documentation of how actuator integrates with both Jersey and Spring MVC", and the intended referenced issue seems to be #17523.

**Comment by wilkinsona** [comment]
Thanks very much, @izeye. I think I've straightened things out as much as possible, including an update to the release notes for 2.2.1.
