### ISSUE TITLE
Support amqps:// URIs in spring.rabbitmq.addresses

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18885]
Forward port of issue #18808 to 2.2.1.

**Comment by DevQuandt** [comment]
I used addresses and didn't add a protocol but set ssl.enabled to true.
Before this change the server connected via ssl, but now spring ignores the ssl.enabled flag.
Should this be the case?

**Comment by wilkinsona** [comment]
Thanks for letting us know. It's unfortunate, and I'm not sure that we considered it, but it does align the handling of the SSL property with things like host and port that are determined from the configured addresses.

**Comment by wilkinsona** [comment]
@DevQuandt Thanks again for letting us know. We discussed this today and believe that we can reinstate the old behaviour while also keeping the new functionality. I've opened https://github.com/spring-projects/spring-boot/issues/19102 to do that.
