### ISSUE TITLE
Spring boot tests overrides surefire plugin listeners

### ISSUE THREAD

**Issue by estigma88** [spring-projects/spring-boot#18893]
Spring boot tests seem to be overridden surefire plugin listeners.

Spring boot parent version: 2.2.0.RELEASE
Surefire maven plugin version: 3.0.0-M3
Java version: 11

I attached a project to demonstrate it, where there is a listener that prints to the sysout if it is executed. If I change the spring boot parent version to 2.1.9.RELEASE, the listener is executed.

[demouuuuu.zip](https://github.com/spring-projects/spring-boot/files/3811511/demouuuuu.zip)

**Comment by philwebb** [comment]
Thanks for the issue report. It turns out this is related to our upgrade to JUnit 5. I've update the release notes to show how you can rollback to JUnit 4 if you need to use listeners.

You need to do the following:

```xml
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
		<exclusions>
			<exclusion>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.junit.vintage</groupId>
				<artifactId>junit-vintage-engine</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-junit-jupiter</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.12</version>
	</dependency>
</dependencies>
```
