### ISSUE TITLE
Remove broken JSP sample link from the reference documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18905]
[This section](https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/reference/html/spring-boot-features.html#boot-features-jsp-limitations) contains a broken link which we should remove.

**Comment by philwebb** [comment]
See also #18904

**Comment by wilkinsona** [comment]
Phil's too quick for me. Duplicates #18905.
