### ISSUE TITLE
Process receive date and picture togother from the frontend

### ISSUE THREAD

**Issue by mohamadhamid** [spring-projects/spring-boot#18907]
I note no exist clear method to process  a request has data and picture togother, I tried and searched on stackOverFlow, but 
I don't find good solution. 
I am now send request for json and other request for picture.

**Comment by philwebb** [comment]
I'm sorry that you've not had any luck searching stackoverflow.com. but that's definitely the place to ask. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
