### ISSUE TITLE
HttpTraceFilter bean missing

### ISSUE THREAD

**Issue by cielswift** [spring-projects/spring-boot#18916]
version- spring boot 2.2

No qualifying bean of type 'javax.servlet.Filter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value="httpTraceFilter")}
![212f5dce0f37bfe047a469c4a366fe1cf58](https://user-images.githubusercontent.com/42295829/68385385-9bdd9880-0194-11ea-995a-0b925c2f414f.jpg)

**Comment by snicoll** [comment]
@cielswift thanks for the report but a screenshot and a partial error message isn't really helpful. Could you please describe the problem you're facing in more details? Is it an upgrade problem to 2.2? Sharing a sample we can run ourselves would be ideal.

**Comment by wilkinsona** [comment]
@cielswift I would guess that you haven't defined an `HttpTraceRepository` bean. As of 2.2, one is required to enable HTTP tracing and the auto-configuration of the endpoint, filter, etc. Please see [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default) of the release notes. If that's not the case, please provide the sample that @snicoll has asked for and we can re-open this issue and take another look.
