### ISSUE TITLE
RabbitMq message getting lost

### ISSUE THREAD

**Issue by MkJha** [spring-projects/spring-boot#18950]
Environment : 
spring-boot-starter-amqp : 2.1.4
Platform : Windows 10
Java : 11

I am using RabbitTemplate.convertAndSend , it does not throw any exception or error but message is not published to the exchange (direct exchange in this case).  There is no error in rabbitMq server log as well. Any Help would be appreciated. 

Sample metrics :: 

No of message sent ------------------>Found in Queue
25--------------------------- ----------->19
100-------------------------------------->69
100--------------------------------------->80

Metrics is just to show that, there is no pattern for number of missing messages.

**Comment by wilkinsona** [comment]
Thanks for the report, but `RabbitTemplate` is part of Spring AMQP which is managed as a [separate project](https://github.com/spring-projects/spring-amqp). Please open an issue there, and comment here with a link to it so that we can follow along.
