### ISSUE TITLE
Kafka properties for multiple producers

### ISSUE THREAD

**Issue by emilnkrastev** [spring-projects/spring-boot#19009]
Hi team,

I have a project with multiple producers and I would like to have a way to provide Kafka properties for each one of them. For example: spring.kafka.producers.<producer-name>.<property>

Does it make sense to have such functionality?

Regards!

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but auto-configuration is targeted at the simpler more common use-case at the moment where only a single producer is used. If you require multiple producers you can do so via your own `@Configuration` and `@Bean` methods. This position may change in the future as we're [considering support for auto-configuring multiple DataSources](https://github.com/spring-projects/spring-boot/issues/15732). If we end up doing something there, the solution is likely to be generally applicable. At that point we can reconsider this suggestion. Closing for now.
