### ISSUE TITLE
Type inferred environment not need to be converted?

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#19016]
``environment`` is created based on ``webApplicationType`` judgment, why is it still possible to convert?

![image](https://user-images.githubusercontent.com/13413715/68838924-93d4aa00-06fa-11ea-9a1e-a1c0cb84436d.png)

**Comment by snicoll** [comment]
@brucelwl rather than asking questions, could you please describe the issue you're facing, preferably in the form of a small sample (zip or github repo) we can run ourselves.

**Comment by brucelwl** [comment]
@snicoll ``environment`` is created according to ``webapplicationtype``. When converting ``StandardEnvironment``, it still queries the types to be converted according to ``webapplicationtype``. They must be the same, so there is no need to convert. This is a place worth optimizing.
The adjusted code should look like this:

```
private ConfigurableEnvironment prepareEnvironment(
			SpringApplicationRunListeners listeners,
			ApplicationArguments applicationArguments) {
		// Create and configure the environment
		ConfigurableEnvironment environment = getOrCreateEnvironment();
		configureEnvironment(environment, applicationArguments.getSourceArgs());
		listeners.environmentPrepared(environment);
		bindToSpringApplication(environment);
		ConfigurationPropertySources.attach(environment);
		return environment;
	}

```

**Comment by philwebb** [comment]
Thanks for the suggestion, but there's actually a very subtle reason why the `EnvironmentConverter` may still need to be called. If the user has a `spring.main.web-application-type` property set then the `bindToSpringApplication` call can change the deduce type.

**Comment by brucelwl** [comment]
> Thanks for the suggestion, but there's actually a very subtle reason why the `EnvironmentConverter` may still need to be called. If the user has a `spring.main.web-application-type` property set then the `bindToSpringApplication` call can change the deduce type.

@philwebb Thank you for your reply!!!
