### ISSUE TITLE
management.metrics.web.server.request.autotime.enabled=true doesn't work for webflux

### ISSUE THREAD

**Issue by pstitt** [spring-projects/spring-boot#19025]
I have a simple springboot webflux application that exposes http server metrics using prometheus  through actuator.

With springboot 2.2 the management.metrics.web.server.auto-time-requests property was deprecated in favour of management.metrics.web.server.request.autotime.enabled.

However, with the latter no http server metrics are produced.

**Comment by snicoll** [comment]
The property is `management.metrics.web.server.request.autotime.enabled`. Is that a typo in your description or something wrong you read somewhere.

**Comment by pstitt** [comment]
Yes, sorry it was a typo in my description. My app config included:

management.metrics.web.server.request.autotime.enabled=true

**Comment by pstitt** [comment]
I've corrected the description now.

**Comment by snicoll** [comment]
Thanks for the feedback. I am a little bit confused here. The default value of that property is `true` so I don't really understand why you'd add it explicitly. It's unclear if things are working for you with `management.metrics.web.server.auto-time-requests` and broke on upgrade. 

I've tried with a Spring Boot 2.2 projects and with or without the property, everything works as expected for me. To help you further, please share a small sample (zip or github repo) we can run ourselves.

**Comment by pstitt** [comment]
I’ll try and pull an example together next week. I suspect it might be only for spring-webflux projects.

**Comment by pstitt** [comment]
I'm closing this. It was an application issue. It was a library that was disabling the metrics.
