### ISSUE TITLE
màu sắc kết hợp tự nhiên

### ISSUE THREAD

**Issue by Dinhhai94** [spring-projects/spring-boot#19034]
màu sắc kết hợp tự nhiên

_Originally posted by @Dinhhai94 in https://github.com/spring-projects/spring-boot/issues/18949#issuecomment-554648307_

**Comment by snicoll** [comment]
Google translate gives me back  « Natural color combination » for « màu sắc kết hợp tự nhiên ». 

Sorry but I don’t understand. Can you please rephrase in English?

**Comment by Dinhhai94** [comment]
màu sắc nguyên bản: cổ nhân
khác biệt: pha
kết hợp màu sắc: đơn thuần

**Comment by snicoll** [comment]
I applogize but none of this seems related to spring boot. If you can rephrase in English or provide us any indication of what what you’re reporting we can reopen.

**Comment by Dinhhai94** [comment]
Natural color combination
