### ISSUE TITLE
The dependency of 'jersey-media-multipart' is not managed as the other jersey dependencies

### ISSUE THREAD

**Issue by smil2k** [spring-projects/spring-boot#19030]
Please include the following artifact also into the dependency management of jersey:

            <dependency>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-multipart</artifactId>
            </dependency>

Thank you!

**Comment by dreis2211** [comment]
Hi @smil2k. I wonder if you're on Spring-Boot 2.0.x still. Spring-Boot 2.1.x upwards uses the jersey-bom which should include the dependency. Not a team member though - don't trust a word I'm saying ;-)

**Comment by wilkinsona** [comment]
Thanks, @dreis2211.

@smil2k As shown by its presence in the [list of dependency versions](https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#appendix-dependency-versions) in the reference docs, `jersey-media-multipart` is already a managed dependency in 2.1.x (and later). 2.0.x has reached the end of its life and is no longer maintained.
