### ISSUE TITLE
The length of several file names prevents cloning the repository for Windows based systems

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects/spring-boot#19036]
The offending file names are:
![image](https://user-images.githubusercontent.com/1829699/68995698-9c45f580-085e-11ea-9bb6-f91dd945d774.png)

Given the verbose naming convention used in the repository, it appears several directories could be shortened to resolve this issue and prevent potential future issues.  For example, "spring-boot-" appears three times in the files with the issue:

> spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/....
Could be shortened to "spring-boot/tools/gradle-plugin/..." eliminating 32 characters in the file name.  

> ...IntegrationTests-...
Could be shortened to ..IT...  eliminating 15 characters in the file name

**Comment by wilkinsona** [comment]
You need to [clone the repository with long paths enabled](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows).
