### ISSUE TITLE
Spring Boot doesn't convert hyphen parameters to CamelCase and doesn't show error

### ISSUE THREAD

**Issue by garg10may** [spring-projects/spring-boot#19043]
https://stackoverflow.com/questions/56726490/dockerized-zuul-gateway-failing-to-connect-to-dockerized-eureka-server

This looks like a bug to me. 

In zuul gateway as per documentation:
`https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html`
```
(  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/)
```

Above is the property for location eureka server. 
However when using property without camelCase it doesn't work neither it shows any error. 

eureka.client.serivce-url.default-zone=http://localhost:8761/eureka

**Comment by wilkinsona** [comment]
In Spring Cloud Netflix, the `serviceUrl` property is a `Map<String, String>`. This means that there is no information available to know that `default-url` should be `defaultUrl`. We have a similar situation with some JPA properties in Spring Boot where we have [documented the behaviour](https://docs.spring.io/spring-boot/docs/2.2.1.RELEASE/reference/htmlsingle/#howto-configure-jpa-properties):

> You need to ensure that names defined under `spring.jpa.properties.*` exactly match those expected by your JPA provider. Spring Boot will not attempt any kind of relaxed binding for these entries.

> For example, if you want to configure Hibernate’s batch size you must use `spring.jpa.properties.hibernate.jdbc.batch_size`. If you use other forms, such as `batchSize` or `batch-size`, Hibernate will not apply the setting.

@garg10may please open a [Spring Cloud Netflix](/spring-cloud/spring-cloud-netflix] issue does that they can take a look and perhaps make a similar note in their documentation.

**Comment by wilkinsona** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/issues/3695
