### ISSUE TITLE
Redis Cache Autoconfigure not able to configure individual cache timeouts by Cachename

### ISSUE THREAD

**Issue by miller79** [spring-projects/spring-boot#19042]
Currently the Redis Cache Configuration available in spring allows you to set the following:

- spring.cache.redis.cache-null-values
- spring.cache.redis.key-prefix
- spring.cache.redis.time-to-live
- spring.cache.redis.use-key-prefix

These settings are great to have at the global level allowing you to set timeouts on the CacheManager without the need to create a custom CacheManager.
However with the general caching case, a typical application requires individual cache timeouts to be set by cachename more time than not.
With the current implementation of RedisCacheManager, there is no way to configure that after the manager is already created thus making the autoconfiguration borderline useless as if you want to still want to include the code that is provided with the customization, you are required to copy the entire autoconfiguration within your application.

This could easily be fixed if the autoconfigure exposes the withInitialCacheConfigurations option within the RedisCacheManagerBuilder.
This method takes in the RedisCacheConfiguration which is already available at the global level so I don't see why this would not be available within a map for this level.
I feel this is a common caching requirement and that it should be available along with the global timeout configuration.

I had a [PR](https://github.com/spring-projects/spring-boot/pull/18803) that provided this but would like to discuss here as well if there is a current gap or if there is another approach that could solve this problem that I am not aware of.

Please let me know your thoughts.

**Comment by mbhave** [comment]
@miller79 Have you taken a look at `RedisCacheManagerBuilderCustomizer`? You should be able to customize the builder as follows:

```java
@Bean
RedisCacheManagerBuilderCustomizer ttlRedisCacheManagerBuilderCustomizer() {
  return (builder) -> {
    builder.withInitialCacheConfigurations(...)
  }
}
```

This is a good way to add the customization you need without having to copy-paste all of the auto-configuration.

**Comment by miller79** [comment]
Sorry, it looks like I misunderstood what `RedisCacheManagerBuilderCustomizer` was intended for when I played with it before.  Thanks for the example as that made it clear of its original intent.  It definitely solves the problem of needing to copy the autoconfigure.  However I still feel that the use case for adding the `withInitialCacheConfigurations` could easily be handled in the autoconfigure especially considering the `RedisCacheConfiguration` is the same configuration that is used in the `defaultCacheConfiguration` which is available to configure via the application properties.

I am still thinking that having a way to configure cache specific TTLs at a minimum would be helpful to have in the application properties for developers.  This would avoid the need to add custom `RedisCacheManagerBuilderCustomizer`'s in the case that I just want a TTL for one or more specific caches.  Ultimately my code is going to have configuration properties for the TTL's as that is a configuration I would like to change in a `RefreshScope` bean potentially with Spring Cloud Config or a ConfigMap in the future.  We had the same need in Ehcache however Ehcache's config is already external and was available to change outside of code.  I personally still feel that is a common use case for a cache and would think it would greatly be beneficial to anyone wanting to use Spring Boot and Redis.

Let me know what you think.

**Comment by snicoll** [comment]
We've discussed this at the team meeting and we believe offering an externalized configuration system is a feature of the cache library. Besides, doing so for Redis and not the other store sounds inconsistent and doing it for all stores brings us back with a false promise of consistency.

There is such feature request for Spring Data Redis, please watch [DATAREDIS-938](https://jira.spring.io/browse/DATAREDIS-938) if you're interested.
