### ISSUE TITLE
Support tc datasource prefix for test containers

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19040]
As suggested by @bsideup :

> ... currently one has to set `spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver` to make Testcontainers JDBC-style containers work. Do you think it makes sense to contribute to Spring Boot and make it auto-detect TC-style JDBC URLs (the ones with tc: prefix)?

**Comment by snicoll** [comment]
Closing in favour of PR #19044
