### ISSUE TITLE
Upgrade to Gson 2.8.7

### ISSUE THREAD

**Issue by maximusfloydus** [spring-projects/spring-boot#19058]
Gson needs to be downgraded (2.8.5) or upgraded (2.8.7) when a new release of gson is released with this fix: https://github.com/google/gson/pull/1603

2.1.10 broke our builds because of OSGI issues with gson 2.8.6
https://github.com/google/gson/issues/1601
https://github.com/google/gson/issues/1602

**Comment by wilkinsona** [comment]
Thanks for letting us know. We won't downgrade as the majority of users won't be affected by the OSGi-specific problems. You can do so yourself by overriding the `gson.version` property. We'll upgrade to 2.8.7 in due course.

**Comment by wilkinsona** [comment]
There’s no date for 2.8.7 at the moment. Bomr will pick up the release when it happens so I am going to close this.
