### ISSUE TITLE
Incorrect Javadoc regarding default Tomcat async request timeout

### ISSUE THREAD

**Issue by adammichalik** [spring-projects/spring-boot#19056]
Follow-up on https://github.com/spring-projects/spring-framework/issues/24030

In `org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties.Async#requestTimeout` the Javadoc says

```java
/**
 * Amount of time before asynchronous request handling times out. If this value is
 * not set, the default timeout of the underlying implementation is used, e.g. 10
 * seconds on Tomcat with Servlet 3.
 */
```

However, actually the default timeout in Tomcat is 30 seconds as noted in this comment: https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/core/AsyncContextImpl.java#L74 and indeed set to the default 30000 ms here: https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/connector/Connector.java#L134

The incorrect explicit values were removed from Spring WebMvc Javadocs and so should the Javadoc in Spring Boot.

**Comment by wilkinsona** [comment]
Thanks, @adammichalik. For further reference, if you intended to open a pull request, there's no need for an issue as well.
