### ISSUE TITLE
事务问题springboot 2.1.6.RELEASE

### ISSUE THREAD

**Issue by czbphoto** [spring-projects/spring-boot#19063]
springboot 2.1.6.RELEASE   使用jpa  hibernate 5.4.3.Final
A.a()调用B.b()
a()使用@Transactional(propagation = Propagation.REQUIRED)
b()使用@Transactional(propagation = Propagation.NOT_SUPPORTED,readOnly = true)
高并发的时候造成阻塞
连接池耗尽
链接一直不释放直到超时
后续访问拿不到数据库连接而报错
请问怎么解决

**Comment by snicoll** [comment]
Duplicate of #19064
