### ISSUE TITLE
Deprecate CachingOperationInvoker#apply

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19089]
Unless I am missing the context `CachingOperationInvoker#apply` isn't called anywhere and I fail to see why we'd open such contract for public use. 

If that's correct, we should probably deprecate it.

**Comment by dreis2211** [comment]
Maybe because the constructor of CachingOperationInvoker isn't public? Was wondering about it when working on #18961 as well.

**Comment by wilkinsona** [comment]
We'll deprecate it in 2.3.

**Comment by dreis2211** [comment]
I'd be happy to contribute. Just deprecating it and not changing anything else then?

**Comment by wilkinsona** [comment]
Other than in tests, I can't see anything that requires the class to be public. It's tempting to deprecate the whole thing with a view to making it package-private in 2.4. I wonder if Spring Cloud uses it for some reason, @spencergibb?

**Comment by snicoll** [comment]
I've deprecated the method with a note. @spencergibb if Spring Cloud is using it after all, please let us know.
