### ISSUE TITLE
Provide documentation for the Maven Plugin that is consistent with our other reference documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19080]
The use of Maven's Site plugin means that we have limited control over the structure and appearance of the Maven Plugin's reference documentation. We'd like to migrate the documentation to Asciidoctor so that we control its structure and align its appearance with the rest of our reference documentation.

**Comment by wilkinsona** [comment]
There are some links from the main reference documentation that I forgot to update.

**Comment by wilkinsona** [comment]
We also need to tidy up the redundant site source files. @snicoll is going to do that after a final review.

**Comment by snicoll** [comment]
That's hopefully done in https://github.com/spring-projects/spring-boot/commit/a76a864270ef47784ddeb703f4366409736bd4b3
