### ISSUE TITLE
Set up redirects for the Maven Plugin documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19093]
Once 2.3.0.RELEASE has shipped, some `current` documentation links to the Maven Plugin will be broken as there's only a single page now. We should set up some redirects to point to the equivalent anchors in the new documentation.

**Comment by snicoll** [comment]
Redirects are in place, we'll enable that once 2.3.0 is actually released and the `current` symlink switches to 2.3
