### ISSUE TITLE
ssl.enabled is ignored when Rabbit is configured with an address with no protocol

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19102]

**Comment by mbhave** [comment]
We should also determine the port based on `ssl.enabled` if no protocol and port is configured in the address. See [this](https://github.com/spring-projects/spring-boot/blob/6ac05539fc8495f7880f1c3dcb2564059a1c2297/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L1043).

**Comment by snicoll** [comment]
Closing in favour of PR #19109
