### ISSUE TITLE
Consider adding support for version ranges for actuator apiVersion

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#19143]
We use the `ApiVersion` enum to return a response compatible with the requested version. Given the way things are structured today, if we add a new version, we'd have to make a change in every place where the version is used to determine the response structure. We need a way to use the apiVersion as a range. For example, [the health endpoint](https://github.com/spring-projects/spring-boot/blob/6c3332b0813aa2f3eebaa3261bc787b6f946df12/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/CompositeHealth.java#L49) needs to be able to say if the version is >= 3 do X otherwise do Y.

**Comment by philwebb** [comment]
I'm not against adding something like `apiVersion.isSince(ApiVersion.V3)`, but for this specific one I wonder if we should just make that code a bit more verbose and change it to:

```java
if(apiVersion == ApiVersion.V2) {
    this.components = null;
    this.details = sort(components);
}
else {
    this.components = sort(components);
    this.details = null;
}
```

**Comment by philwebb** [comment]
We'll go with the extended `if` for now and look at `isSince` later if we need to.

**Comment by philwebb** [comment]
I'm going to close this one since we've not needed this in the last few years.
