### ISSUE TITLE
spring.batch.job.enabled=false flag is working until 2.2.0.RELEASE but not in 2.2.1.RELEASE. 

### ISSUE THREAD

**Issue by NaseemAhamed** [spring-projects/spring-boot#19160]
Expectation:
As per the documentation, the configured job would not execute if the flag 'spring.batch.job.enabled' is set as false. 

Actual:
Job is executing on server start-up. 

Setup:
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

Code:
```
@Configuration
@EnableBatchProcessing
public class BatchConfig extends DefaultBatchConfigurer
```

**Comment by snicoll** [comment]
@NaseemAhamed thanks for the report but I don't quite understand why it would work with 2.2.0 and not 2.2.1. Can you please attach a small sample that reproduces the issue you're experiencing (something we can run ourselves that breaks in 2.2.1 but works in 2.2.0).

**Comment by NaseemAhamed** [comment]
@snicoll I sincerely apologise for the issue. The flag is working as expected. This is an invalid issue.

As we do not have access to create Spring Batch's default tables, we have overridden the setDataSource method to do nothing in spring parent 2.1.3. 
```
@Override
    public void setDataSource(DataSource dataSource) {
    }
```
Now, in 2.2.1, it is giving the error during server start-up that the default batch table does not exist (though it does not prevent the server from booting up). I mistook the error for the table referred in the batch query and thought that the job was executing during the start-up!

**Comment by snicoll** [comment]
Thanks for letting us know.
