### ISSUE TITLE
Add some more assertions to SampleTestApplicationWebIntegrationTests.test() to check that the expected response is received

### ISSUE THREAD

**Issue by vojkog** [spring-projects/spring-boot#19167]
In the [following test](https://github.com/spring-projects/spring-boot/blob/c3786e727fc6bb80deb0f830a6fc2537de73e3a1/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-test/src/test/java/smoketest/test/SampleTestApplicationWebIntegrationTests.java#L58) we are not asserting status code or content. That test will pass regardless of the parameter.

**Comment by wilkinsona** [comment]
Thanks for the report. The test will fail if the random port is setup incorrectly as a `ResourceAccessException` will be thrown. That said, it wouldn't hurt to add some extra assertions.

**Comment by jcordoba95** [comment]
Hello! I could add some extra assertions if no one else is working on it.

**Comment by philwebb** [comment]
Thanks @jcordoba95. I've assigned the issue to `spring-contributor` so nobody else will take it.

**Comment by wilkinsona** [comment]
Closing in favour of #19326.
