### ISSUE TITLE
Move Maven-specific content in reference guide to dedicated documentation

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19165]
Now that we have dedicated documentation for our Maven Plugin we should move everything related to Maven there rather than having some content in both guides.

**Comment by cicioflaviu** [comment]
@snicoll 
Can I work on this one?

**Comment by snicoll** [comment]
@cicioflaviu sorry, I missed that. There are a number of things we'd like to do as part of moving the documentation to the reference guide so I think it's better if the team handles this one.
