### ISSUE TITLE
Confusing docs on actuator endpoints, enabled, exposed, defaults etc.

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#19179]
From https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready:

> By default, all endpoints except for shutdown are enabled.

I'm not sure that's even true any more, but it's kind of misleading or confusing anyway, I think. Isn't it only `/info` and `/health` that are exposed by default since Spring Boot 2.0. In 2.2 I don't think the others are even there for JMX.

**Comment by wilkinsona** [comment]
Thanks. We talked about this a few weeks ago, didn't we? That led to me creating #18814 which I think this issue duplicates.
