### ISSUE TITLE
Better test method name suggestion

### ISSUE THREAD

**Issue by vojkog** [spring-projects/spring-boot#19186]
The test method name in the following test 
[permlink](https://github.com/spring-projects/spring-boot/blob/60d563e88ab35602ecbcc1b92a285d327107c8ed/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-test/src/test/java/smoketest/test/web/UserVehicleControllerTests.java#L94
) is little confusing. The better name might be welcomeCommandLineRunnerShouldNotBeAvailable or "*ShouldThrowException".

**Comment by wilkinsona** [comment]
Well spotted. Thank you.
