### ISSUE TITLE
About the coding problem with properties

### ISSUE THREAD

**Issue by zhengchb** [spring-projects/spring-boot#19185]
Can I modify the encoding format of the properties reading file to facilitate the use of Chinese configuration

Let's change the code

        CharacterReader(Resource resource) throws IOException {
            this.reader = new LineNumberReader(new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8));
        }

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I assume that the code that you are referring to is the following:

https://github.com/spring-projects/spring-boot/blob/60d563e88ab35602ecbcc1b92a285d327107c8ed/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/OriginTrackedPropertiesLoader.java#L155-L158

The use of `StandardCharsets.ISO_8859_1` is deliberate (see https://github.com/spring-projects/spring-boot/pull/10565, https://github.com/spring-projects/spring-boot/issues/10564, and https://github.com/spring-projects/spring-boot/issues/5361). The key thing is that the use of ISO 8859-1 aligns with the default encoding used by [`java.util.Properties`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Properties.html).
