### ISSUE TITLE
Absolute URL for feign client stopped working in Spring Cloud Hoxton.RELEASE

### ISSUE THREAD

**Issue by cancerian0684** [spring-projects/spring-boot#19201]
FeignClient with absolute URL doesn't work using Spring Cloud Loadbalancer in Hoxton.RELEASE

With Spring Cloud Hoxton.RELEASE, FeignClient with ribbon disabled stopped respecting Absolute URLs.

FeignClient
```
@FeignClient(name = "feedback-client", url = "http://some.absolute.url") 
interface FeedbackClient {

   @RequestMapping(value = ["/feedback"], method = [RequestMethod.GET])
   fun findAll(@RequestParam("page") page: Int): Page<Feedback>
}
```

application.yml
```
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
```

Error:
`s.c.o.l.FeignBlockingLoadBalancerClient : Load balancer does not contain an instance for the service <absolute http url> `

Dependencies:
-  Spring Boot 2.2.1
-  Spring Cloud Hoxton.RELEASE

Github Repo to reproduce the scenario:

https://github.com/cancerian0684/demo-openfeign

**Comment by spencergibb** [comment]
Please open in Spring Cloud Openfeign
