### ISSUE TITLE
Error pages are not working when an async controller is used with Tomcat7/8 [Spring Boot 1.1.9]

### ISSUE THREAD

**Issue by AndreasKl** [spring-projects/spring-boot#1920]
I'm currently integrating Java 8 CompletableFuture in Spring Web MVC to have more Java 8ish programming model. While switching from Jetty to Tomcat to do performance evaluation I observed that the global catch all error handler (white label error page) does not work in all scenarios with an embedded Tomcat.

If there is for instance a template issue (or the deferred times out) on an async request the standard tomcat error page is displayed. This is not the case with sync requests or with jetty where sync and async works flawlessly.

A ready to run sample can be found here
https://github.com/AndreasKl/spring-boot-mvc-completablefuture
*master* is using jetty and the *tomcat-strange-error-behavior* branch is using tomcat.

**Comment by wilkinsona** [comment]
The Tomcat bug has been fixed, but is not yet available in a Tomcat 7 or Tomcat 8 release

**Comment by AndreasKl** [comment]
@wilkinsona I think we should close this ticket. Thanks for tracing this issue and providing the sample to the tomcat team.

**Comment by wilkinsona** [comment]
Let's keep it open until we upgrade to versions of Tomcat that contain the fix. I don't want people to see that this is closed and get the incorrect impression that it's now fixed.

**Comment by AndreasKl** [comment]
Tested and the scenario works now. Thanks for fixing.

**Comment by DavidJFelix** [comment]
Currently having this issue using CompletableFuture in 1.3.0.RC1. Tomcat is 8.0.28. Does not happen in Jetty. Let me know if you'd like more info. I'm working on a test case.

**Comment by wilkinsona** [comment]
@DavidJFelix We'll need some more info please. The sample project provided when this issue was opened works fine with 1.3.0.RC1 so, whatever problem you're having, I don't think it's the one described in this issue. Please open a new issue with a test case when you have it.

**Comment by DavidJFelix** [comment]
I'm pretty sure the issues are related. I'll try to get a minimal test case, but it sounds like you guys want a full project that fails, and thats a lot to build without sharing my closed source project. The primary difference is I'm using RestController and not Controller. I'll see what I can get together and open a new bug. I'm still going to link this one.

**Comment by lazystone** [comment]
I have the same issue setting errorResult in DeferredResult with tomcat + SpringBoot 1.3.0.RC1. Switching to jetty solves the problem.

**Comment by OrangeDog** [comment]
Can reproduce with a very simple spring-boot example.

    @Controller
    public class TestController {
        @RequestMapping("/timeout")
        public ListenableFuture<String> timeout() {
            return new SettableListenableFuture<>();
        }
    }

A request to /timeout then gives the error.

    2015-12-17 13:04:30.139 ERROR 3152 --- [nio-8080-exec-4] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

    java.lang.IllegalStateException: Cannot forward after response has been committed
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:328) ~[tomcat-embed-core-8.0.28.jar:8.0.28]

**Comment by wilkinsona** [comment]
@OrangeDog That looks like a subtly different problem (and this issue is closed). This issue concerns an async response that throws an exception (the sample app tries to render a broken template), whereas your example looks like it's relying on the async request timing out. If you'd like us to investigate further, can you please open a new issue? Ideally with a complete sample project and instructions on exactly how to reproduce the problem.

**Comment by OrangeDog** [comment]
Righto. I only got here because it was linked from https://jira.spring.io/browse/SPR-12764 which is closed because it's not a spring core problem.
