### ISSUE TITLE
Example AuthorizationServer using only Spring Security 5 and NOT using the spring-security-oauth2 dependency.

### ISSUE THREAD

**Issue by jarrodhroberson** [spring-projects/spring-boot#19235]
Can someone provide an example of creating an AuthorizationServer that only uses the native oAuth2 support in Spring Security 5 and does not use/rely on `spring-security-oauth2`?

I am working a new project and would like to remove as many things that are "not supported/deprecated" as possible.

```
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>
```

This dependency is listed as not part of Spring Boot 2.x anymore and that all its functionality is available in Spring Security 5. I have been able to remove the "autoconfigure" dependency, but I have not been able to find any documentation that shows how to remove this dependency.

Is there an example that can be added to shows how to achieve an AuthorizatonServer without these "unsupported" and for all practical purposes "deprecated" adapter dependencies?

**Comment by wilkinsona** [comment]
Please see [this blog post](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update#no-authorization-server-support) for information about Spring Security's authorization server support. If you'd like to discuss this further with them and the broader community, you can find them [on Gitter](https://gitter.im/spring-projects/spring-security).
