### ISSUE TITLE
What are the spring.provides for?

### ISSUE THREAD

**Issue by dennislaumen** [spring-projects/spring-boot#1926]
When browsing the source code for the different starters for Spring Boot I'm stumbling upon _spring.provides_ files. I'm not sure what these files are doing and what these are for. I'm looking into building some starters for some frameworks we're using but am unsure as to why I'd have to add these files (and what I should put into it).

I'm hoping someone can clarify this for me (it might be a bit "under the hood" but it would be a nice addition to the documentation).

**Comment by LiveAlone** [comment]
1
