### ISSUE TITLE
Upgrade to Webjars Locator Core 0.43

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19275]

**Comment by OrangeDog** [comment]
Can this be backported to 2.2.x? As far as I can see these are the only changes.

- Fix including test dependency at compile time
- Update (not already managed) dependency patch versions

**Comment by wilkinsona** [comment]
No, sorry, I don't think so. As a rule, we don't pick up new minor or major versions of dependencies in maintenance releases irrespective of the changes that they contain. You are, of course, free to override the version in your build.

**Comment by OrangeDog** [comment]
I guess the problem is with the definition of major/minor/patch for a `0.x` project.
