### ISSUE TITLE
Why do I get log4j related warning messages while I use logback?

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-boot#1928]
Hey,

I'm using logback as my default logging, and it works fine. 

However, my question is that why Spring Boot stillI spits below warning messages although it uses logback.

```
og4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
```

I think Spring Boot uses `log4j-over-slf4` library for integration with logback, but I do not know why it still throws the warning message.

Could you answer my question?

**Comment by pmuntyanu** [comment]
From my side deletion the org.slf4j.slf4j-log4j12-1.7.7.jar fixed the issue

**Comment by snicoll** [comment]
@pmuntyanu that issue is close for over a year ago. If  you're having a question, please ask on stackoverflow. If you believe you've found an issue in Spring Boot, please create a new issue with a description of the problem (a sample is always better). Thanks!
