### ISSUE TITLE
Delete useless judgment 

### ISSUE THREAD

**Issue by lyyprean** [spring-projects/spring-boot#19282]
# 1.old  code

```java
if (StringUtils.hasText(validationQuery)) {
	try {
		// Avoid calling getObject as it breaks MySQL on Java 7
		List<Object> results = this.jdbcTemplate.query(validationQuery, new SingleColumnRowMapper());
		Object result = DataAccessUtils.requiredSingleResult(results);
		builder.withDetail("result", result);
	}
	finally {
		builder.withDetail("validationQuery", validationQuery);
	}
}
```

# 2. After updating the code

Delete useless judgment，Because `validationQuery` must not be null  or “” or “ ”

```java
try {
	// Avoid calling getObject as it breaks MySQL on Java 7
	List<Object> results = this.jdbcTemplate.query(validationQuery, new SingleColumnRowMapper());
	Object result = DataAccessUtils.requiredSingleResult(results);
	builder.withDetail("result", result);
}
finally {
	builder.withDetail("validationQuery", validationQuery);
}
```

**Comment by philwebb** [comment]
Good spot. The code in question is in `DataSourceHealthIndicator` and isn't needed because `getValidationQuery()` always returns a string.

**Comment by lyyprean** [comment]
Thank you:
&nbsp; &nbsp; &nbsp;&nbsp;May I ask if I can join the contributor list，My English is not very good, hope forgive me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Phil Webb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 中午12:46
收件人:&nbsp;"spring-projects/spring-boot"<spring-boot@noreply.github.com&gt;;
抄送:&nbsp;"满天花落"<869441600@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/spring-boot] Delete useless judgment type：enhancement (#19282)




Good spot. The code in question is in DataSourceHealthIndicator and isn't needed because getValidationQuery() always returns a string.

**Comment by lyyprean** [comment]
thank you

**Comment by philwebb** [comment]
You're most welcome to submit a PR if you'd like to become a contributor.

**Comment by lyyprean** [comment]
What is PR ?   Sorry, my english is not very good

**Comment by philwebb** [comment]
A PR is short for a "pull request". It's the way that GitHub lets you contribute to a project. You can read about them [here](https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request). In addition we have some contributor guidelines [here](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc).

**Comment by lyyprean** [comment]
Thank you very much

**Comment by philwebb** [comment]
Closing in favor of PR #19290
