### ISSUE TITLE
Can not set spring.devtools.restart.enabled from application property file

### ISSUE THREAD

**Issue by tomlpark** [spring-projects/spring-boot#19302]
Version: Spring Boot 2.2.1-RELEASE
spring-boot-devtools: 2.2.1-RELEASE

If you set the restart enabled option to false in the application.properties this is not obeyed, you have to set it as a system property. Setting this setting via the properties file does not seem to be deprecated or removed however because if you add:

spring.devtools.restart.enabled=false

Then DevToolsProperties Restart object does get called and it's setter for Enabled is called and set to false correctly. However, this happens long after the RestartApplicationListener's onApplicationStartingEvent is called and the dev tools are enabled or disabled. This method just makes a call to:

System.getProperty("spring.devtools.restart.enabled")

and never considers the DevToolsProperties. Even if it did, the setter for the properties is called long after the starting event is processed.

It seems to me this property either needs to be removed or enabling/disabling needs reworking to be able to read the property.

**Comment by wilkinsona** [comment]
This sounds like it is working as [documented](https://docs.spring.io/spring-boot/docs/2.2.1.RELEASE/reference/htmlsingle/#using-boot-devtools-restart-disable):

> If you do not want to use the restart feature, you can disable it by using the `spring.devtools.restart.enabled` property. In most cases, you can set this property in your `application.properties` (doing so still initializes the restart classloader, but it does not watch for file changes).

> If you need to completely disable restart support (for example, because it does not work with a specific library), you need to set the `spring.devtools.restart.enabled` System property to false before calling `SpringApplication.run(…​)`

If I have misunderstood your description,  please provide some more details about the behaviour that you are seeing and we can re-open this issue and take another look. The best way to provide those details would be in the form of a small sample application that reproduces the behaviour you are seeing.
