### ISSUE TITLE
LoggedExceptionHandlerThreadLocal causes undeploy/redeploy problems in tomcat

### ISSUE THREAD

**Issue by dagnelies** [spring-projects/spring-boot#19307]
Hi,

there seems to be an issue with LoggedExceptionHandlerThreadLocal 

Undeploying a webapp does not work properly because some thread is not terminated. The consequence is that spring .jar libraries keep being locked and an undeploy/redeploy fails.

Following error appears in the logs:

```
16:16:59.513 SEVERE [http-nio-9070-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks 
The web application [...] created a ThreadLocal
with key of type [org.springframework.boot.SpringBootExceptionHandler.LoggedExceptionHandlerThreadLocal]
(value [org.springframework.boot.SpringBootExceptionHandler$LoggedExceptionHandlerThreadLocal@c91d3d])
and a value of type [org.springframework.boot.SpringBootExceptionHandler] 
(value [org.springframework.boot.SpringBootExceptionHandler@246057a3]) 
but failed to remove it when the web application was stopped.
Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by wilkinsona** [comment]
When you say "undeploy a webapp", are you undeploying a war file from a standalone instance of Tomcat? If so, `SpringBootExceptionHandler` shouldn't be used as it's only installed when the application started on the main thread:

https://github.com/spring-projects/spring-boot/blob/4957994defc20f4fe6ae0a2aa071e0fafe420e08/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L884-L889

Can you please provide a small sample application that reproduces the problem and a description of how you are performing the deployment and undeployment of the app?

**Comment by dagnelies** [comment]
It's packaged as "war" file and deployed in tomcat where the main class looks like

```java
@SpringBootApplication
public class MyWebApp extends SpringBootServletInitializer {
```

...and the deployment is moving the "war" inside tomcat webapps directory (or via tomcat's html manager) which works just fine and undeploying via tomcat's html manager too. For testing purposes, I removed other webapps.

I'll try to build a small application to reproduce it, give me some time ;)

**Comment by dagnelies** [comment]
The issue also occurs for a brand new blank webapp:

https://github.com/dagnelies/SpringIssue19307

**Comment by dagnelies** [comment]
Hmmm... the Thread issue might be misleading or a separate issue. 😕 

I'll open a separate issue to avoid mixing both topics. The issue persists that the undeploy fails for this simplistic webapp but apparently, it's because of locked libs that cannot be deleted.
