### ISSUE TITLE
Undeploy spring webapps fails on tomcat

### ISSUE THREAD

**Issue by dagnelies** [spring-projects/spring-boot#19311]
Hi,

Procedure:

- make a blank Spring Boot Web project, like https://github.com/dagnelies/SpringIssue19307
- package it as "war" file
- deploy the webapp ( either move it inside tomcat/webapps or using the html manager for example)
- undeploy the webapp (using the html manager for example)
- 💥 `FAIL - Unable to delete [...\webapps\...]. The continued presence of this file may cause problems.`

The tomcat logs show the same:

    17:32:35.657 SEVERE [Catalina-utility-1] org.apache.catalina.startup.ExpandWar.deleteDir [...\webapps\...\WEB-INF\lib] could not be completely deleted. The presence of the remaining files may cause problems

Apparently, something is blocking following jar libs to be deleted:

- logback-classic-1.2.3.jar
- spring-web-5.2.1.RELEASE.jar
- spring-webmvc-5.2.1.RELEASE

And the only way to cleanly undeploy/redeploy the webapp is to kill the whole tomcat forcefully ...shutting it down normally also works but take ages until some sort of timeout kicks in, probably because the files are locked.

**Comment by dagnelies** [comment]
I'll try on another blank tomcat ...

**Comment by wilkinsona** [comment]
Are you using Windows?

**Comment by dagnelies** [comment]
yup

**Comment by dagnelies** [comment]
OK ...on a blank VM with a brand new Tomcat, the issue is not present ...it appears a side effect is coming from somewhere else (??!?!!?!) ...I'll close this issue for now, until I can reproduce it better from scratch. 😞 
Sorry for having taken up your time.
