### ISSUE TITLE
Add disruptor dependency to spring-boot-dependencies

### ISSUE THREAD

**Issue by Aloren** [spring-projects/spring-boot#19322]
It is possible to configure async logging via Log4j2, this requires `disruptor` dependency to be on the classpath. Since `spring-boot-dependencies` already manages version for log4j2, maybe it makes sense to add `disruptor` dependency to `dependencyManagement` section as well? What do you think?

**Comment by wilkinsona** [comment]
To avoid the scope of Spring Boot's dependency management becoming too broad, we generally limit it to those dependencies with which Spring Boot interacts directly. Log4j2 falls into that category, but the LMAX Disruptor does not. Thanks anyway for the suggestion.

**Comment by Aloren** [comment]
Makes sense. Thank you.
