### ISSUE TITLE
@DataJpaTest using H2 with schema.sql and spring.datasource.schema-username fails

### ISSUE THREAD

**Issue by silovmar** [spring-projects/spring-boot#19321]
Version: Spring Boot v2.2.1.RELEASE, Spring v5.2.1.RELEASE

Hi, I'm using `@DataJpaTest` with default embedded H2 DB for testing. Also I'm creating DB schema using `schema.sql` which contains `CREATE SCHEMA IF NOT EXISTS TEST_SCHEMA;`.

Unit tests annotated with the `@DataJpaTest` ran fine until I added to my production `application.properties` properties `spring.datasource.schema-username=${DB_USERNAME_SCH}` and `spring.datasource.schema-password=${DB_PASSWORD_SCH}`.

This causes that a datasource based on the application.properties is trying to be created instead of the default H2 database. The creation of DB from application.properties fails because the datasource configuration looks like this:

```
spring.datasource.driver-class-name= oracle.jdbc.OracleDriver
spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.schema-username= ${DB_USERNAME_SCH}
spring.datasource.schema-password= ${DB_PASSWORD_SCH}
```

I would expect that the embedded H2 is used even if the schema-username and schema-password is used.

Source code which caueses the problem:
[org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java:197](https://github.com/spring-projects/spring-boot/blob/eb0eb492b4a12d12955e77f2d94492405ce4c076/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java#L197) which is called from [org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java:101](https://github.com/spring-projects/spring-boot/blob/eb0eb492b4a12d12955e77f2d94492405ce4c076/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java#L101)

**Comment by philwebb** [comment]
This is an edge case that we've not considered. You might be able to work around it by overriding the `spring.datasource.schema-username` property to `""` in your test.

**Comment by eddumelendez** [comment]
I have added my findings in https://github.com/spring-projects/spring-boot/pull/19327#issuecomment-562846662

**Comment by wilkinsona** [comment]
Closing in favour of #19327.

**Comment by snicoll** [comment]
We're going to give it another go by overriding `spring.datasource.schema-username` when we replace the `DataSource`.

**Comment by somayaj** [comment]
Can this be worked?

**Comment by somayaj** [comment]
The !isEmbedded boolean check added to the username and password might solve the issue here: https://github.com/spring-projects/spring-boot/blob/eb0eb492b4a12d12955e77f2d94492405ce4c076/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java#L197[](url)

**Comment by wilkinsona** [comment]
[This](https://github.com/wilkinsona/spring-boot/tree/gh-19321) appears to work, but I'd like some more eyes on it before merging it.

**Comment by somayaj** [comment]
I haven't created a PR yet. will do so if you think its a viable fix.

**Comment by wilkinsona** [comment]
Thanks for the offer, @somayaj, but if the team agree that may proposed changes seem reasonable we won't need a PR for this one.

**Comment by snicoll** [comment]
LGTM Andy. Thanks!
