### ISSUE TITLE
springBoot 2.1.9.RELEASE  https configuration packaging jar Can't start   BUG

### ISSUE THREAD

**Issue by diasjda** [spring-projects/spring-boot#19324]

**Comment by wilkinsona** [comment]
Given the empty description, I'm guessing this was opened in error. If that's not the case, please provide enough information for us to diagnose the problem and we can re-open the issue and take another look.

**Comment by diasjda** [comment]
In the idea editor, I can start normally, but after I package it into a jar, the startup will not work. After changing to 2.2.0, it will start normally, or it is the reason of tomcat version.

**Comment by wilkinsona** [comment]
Thanks. It sounds like you may have configured your keystore in such a way that it cannot be read when your application is packaged as a jar file. Perhaps you’ve used an absolute file path?

If you would like us to spend some more time trying to help you please take the time to provide a complete sample that reproduces the problem.

**Comment by diasjda** [comment]
No, at first I thought so, but then I changed nothing and just changed the version to 2.2.0, and it ran successfully. The files were packaged in. The packaged jar was checked and there Key file

**Comment by wilkinsona** [comment]
As I said above, if you would like us to spend some more time trying to help you please take the time to provide a complete sample that reproduces the problem.
