### ISSUE TITLE
spring.hazelcast.config not found when Webflux enabled

### ISSUE THREAD

**Issue by hochraldo** [spring-projects/spring-boot#19337]
When using `spring.hazelcast.config` together with `@EnableWebFlux` it cannot find the hazelcast configuration.

The reason seems to be that HazelcastProperties#resolveConfigLocation fails due to:
```
Assert.isTrue(this.config.exists(),
				() -> "Hazelcast configuration does not exist '" + this.config.getDescription() + "'");
```

`config.exists()` always returns false as a `FilteredReactiveWebContextResource` is used in this case.

spring boot version used is 2.2.1.RELEASE

**Comment by wilkinsona** [comment]
You haven't described how you have configured `spring.hazelcast.config`, but I would guess that you haven't provided a hint as to how the config file should be found. For example, if the config is located in `src/main/resources`, you should use something like `classpath:your-config.xml`. This will result in a `ClassPathResource` being injected. Alternatively, if you expect the config to be loaded from an external location on the file system, you should use something like `file:/path/of/your-config.xml`.

The same applies for a Servlet-based web application unless you have included your config file in a location that would make it available via the servlet context. That is to be avoided as doing so would allow it to be served as a static resources.

**Comment by hochraldo** [comment]
Yes you are right. Sorry for that. I thought it always uses a `FilteredReactiveWebContextResource ` (which returns false for exists) and that's why it fails.
