### ISSUE TITLE
Increase visibility of RedisSession inner class in order to write custom behavior

### ISSUE THREAD

**Issue by Stoony** [spring-projects/spring-boot#19332]
Hi,

I'm facing some issues with the default behavior of the _spring-session-data-redis_ module which doesn't manage redis unavailability with a fallback strategy for example. I need to extend the RedisIndexedSessionRepository class in order  to implement the desired behavior but I can't achieve this because some methods (save) signature use the RedisSession type and this one has got a package visibility only.

I also need to override the SessionRepositoryFilter class which requires the RedisSession type to be given as generic argument and led to the same issue.

Is it possible to set the visibility of the class RedisSession to public so we can use a custom implementation of the session repository staying with the use of standard annotations and session object to enable redis http session.

Thank by advance for considering this problem, I'd like to avoid to duplicate the entire module in my app to write the needed features.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. `RedisSession` is part of Spring Session which is managed as a [separate project](https://github.com/spring-projects/spring-session).
