### ISSUE TITLE
No cipher suites in common: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - after 2.2.2.RELEASE

### ISSUE THREAD

**Issue by maxim-bandurko-lsvt** [spring-projects/spring-boot#19335]
Have this problem started after upgrading from "2.2.2.BUILD-SNAPSHOT" to "2.2.2.RELEASE". Problem still remains at "2.2.3.BUILD-SNAPSHOT". Checked for dependencies, and the only switch in netty was at "netty-tcnative-boringssl-static" from "2.0.26.Final" to "2.0.28.Final"

**Comment by philwebb** [comment]
@maxim-bandurko-lsvt Do you have a stack trace or a sample that reproduces the problem? I don't think we've made any functional changes in this area so I suspect this issue will need to be raised with either https://github.com/reactor/reactor-netty or https://github.com/netty/netty

**Comment by maxim-bandurko-lsvt** [comment]
@philwebb While trying to replicate the issue with self signed generated certificate found that it is connected with intermiediate certificate chain, not the ciper suite related. If generation of jks keystore was done by keytool after using openssl importing key pairs and converting to new version of pkcs12:

`openssl pkcs12 -export -in cert.pem -inkey key.pem -name my-alias -out keystore.p12`

`keytool -importkeystore -deststorepass my-password -destkeystore keystore.jks -srckeystore keystore.p12 -srcstoretype PKCS12 -deststoretype pkcs12`

`keytool -import -alias my-alias -trustcacerts -file IntermediateCA.crt -keystore keystore.jks`

Netty can't find alias any more and reports:

`javax.net.ssl|ALL|2B|reactor-http-nio-2|2019-12-09 15:33:26.941 PST|X509Authentication.java:303|my-alias is not a private key entry`

But, if we will use openssl:

`openssl pkcs12 -export  -inkey key.pem -in cert.pem -certfile IntermediateCA.crt -name my-alias -out keystore.p12`

And just using this pkcs from openssl - works properly.

I can say that my issue is resolved, as found way how to make it working (not sure, if that is supposed to be so after release). If it is ok, we may close this issue ticket, as using native openssl instead of keytool solves issue.

**Comment by philwebb** [comment]
Thanks for additional info @maxim-bandurko-lsvt. I'll close this one.
