### ISSUE TITLE
CookieCsrfTokenRepository doesn't work properly with CsrfFilter

### ISSUE THREAD

**Issue by springfan** [spring-projects/spring-boot#19341]
Spring v2.1.4.RELEASE

[CookieCsrfTokenRepository  ](https://docs.spring.io/spring-security/site/docs/4.2.13.RELEASE/apidocs/org/springframework/security/web/csrf/CookieCsrfTokenRepository.html) is a dedicated class to make CSRF integration with AngularJS work out of the box / pretty easy. 

In an AngularJS application it's enough to fulfill that preconditon and AngularJS automatically adds the CSRF header to POST and other requests:
Enable CSRF in the WebConfig through ``http.csrf().csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse()).``

Bug Summary:
In [CookieCsrfTokenRepository ](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java) the CSRF header name is hard wired as "X-XSRF-TOKEN". The intercepting [CsrfFilter](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java#L121) is not able to retrieve the actual token because the request object's header names are stored in lowercase ("x-xsrf-token") but the lookup uses the hard wired upper case value "X-XSRF-TOKEN" (see [code](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java#L121)).

In depth:
Once CSRF is enabled requests from AngularJS to Spring are intercepted by the [CsrfFilter](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java#L121).
That filter determines the token's header name from the `CookieCsrfTokenRepository` (in which it is set to "X-XSRF-TOKEN") . It tries to read that header value from the requests `headerMap` through ``String actualToken = request.getHeader(csrfToken.getHeaderName());`` . All the headers from the request's `headerMap` store the header names in lowercase. Thus `actualToken` can't be set to the token value as "x-xsrf-token" != "X-XSRF-TOKEN".

Proper Requests from AngularJS that include the header "X-XSRF-TOKEN" end up with logging error 
`2019-12-10 09:48:36.633 DEBUG 18896 --- [nio-8080-exec-4] o.s.security.web.csrf.CsrfFilter         : Invalid CSRF token found for http://localhost:8080/api/`.  The frontend shows `Request Method Not Supported (405)` .

CC @rwinch as he's the author of `CookieCsrfTokenRepository`.

**Comment by wilkinsona** [comment]
Thanks for the problem analysis. The code in question is part of Spring Security which is managed as a [separate project](https://github.com/spring-projects/spring-security). If a fix is needed, I think it will need to be made there rather than in Spring Boot. Can you please open a Spring Security issue instead?

**Comment by springfan** [comment]
For reference the new issue in the Spring security repo: https://github.com/spring-projects/spring-security/issues/7719
