### ISSUE TITLE
Spring-boot 2.2.0 with embedded jetty and activemq-http 5.15.10 version conflict

### ISSUE THREAD

**Issue by shilan** [spring-projects/spring-boot#19347]
Trying to upgrade to spring-boot 2.2.0 with embedded jetty, I get version conflict with jetty-all used in activemq-http dependency version 5.15.10 coming from spring-boot. So these two version don't match and I get method not found and duplicate method declaration in the following classes when trying to start spring boot:

The method's class, org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer, is available from the following locations:

jar:file:/some-dir/target/p3.0.166-SNAPSHOT.war!/WEB-INF/lib/jetty-all-9.4.19.v20190610-uber.jar!/org/eclipse/jetty/websocket/server/NativeWebSocketServletContainerInitializer.class
jar:file:/some-dir/target/p3.0.166-SNAPSHOT.war!/WEB-INF/lib/websocket-server-9.4.20.v20190813.jar!/org/eclipse/jetty/websocket/server/NativeWebSocketServletContainerInitializer.class

**Comment by wilkinsona** [comment]
We use Jetty's bom to manage the version of all of the Jetty modules upon which Spring Boot depends. Jetty's bom doesn't include dependency management for `jetty-all`. As far as I know, it isn't included as it's misnamed and [shouldn't be used as a dependency](https://github.com/eclipse/jetty.project/issues/1511).

I'd recommend that you raise this with the ActiveMQ team to encourage them to move away from `jetty-all` to using the specific Jetty modules that they need. In the meantime, you can use the `jetty.version` inherited from `spring-boot-starter-parent` to override the version of `jetty-all` that `activemq-http` pulls in.
