### ISSUE TITLE
Jackson Serialization for Duration is broken since Spring Boot 2.2 upgrade

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#19345]
Jackson added a breaking change for the way `Duration` is serialized. Before The `DurationSerializer` was using `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` to check whether `Duration` should be serialized as a timestamp or not. Since 2.10 Jackson uses `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` to check whether `Duration` should be serialized as a timestamp or not. 

I would suggest that the `JacksonAutoConfiguration` adds `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` with a value `false` as a default configuration.

This was done in https://github.com/FasterXML/jackson-modules-java8/pull/75

**Comment by wilkinsona** [comment]
Thanks for the PR, @filiphr. Closing in favour of #19352.
