### ISSUE TITLE
Upgrade to SpringData MongoDB 3.0 and MongoDB Java Driver 4.0

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-boot#19356]
SpringData MongoDB intends to upgrade to the MongoDB Java Driver 4.0 (sync/reactive) with the Neumann (M1) release. This will be a major upgrade due to breaking changes in the public API of SpringData (see [upgrading from 2.x to 3.x](https://github.com/spring-projects/spring-data-mongodb/blob/3.x/src/main/asciidoc/upgrading.adoc) for details).

Both, the MongoDB 4.0 drivers as well as SpringData MongoDB 3.0 are currently only available as SNAPSHOT dependencies. 

---

SpringData MongoDB - 3.0
https://github.com/spring-projects/spring-data-mongodb/tree/3.x

Spring Boot - Mongo Drivers 4.0 (incl. Spring Data MongoDB 3.0)
https://github.com/christophstrobl/spring-boot/tree/mongo-driver-4_0

Spring Session Data MongoDB
https://github.com/spring-projects/spring-session-data-mongodb/tree/mongo-driver-4_0

**Comment by wilkinsona** [comment]
Thanks, @christophstrobl. This will require some coordination across a few projects to get this into Boot 2.3 (due in April 2020) as it will pull a few projects into that schedule.

I think at least the following projects will be affected:

- Spring Batch (@benas @mminella)
- Spring Integration (@artembilan @garyrussell)
- Spring Session (@vpavic @rwinch)

There may be others that are affected directly or indirectly. Can you and @mp911de please coordinate with the other projects and make sure that everyone has the bandwidth to absorb the breaking changes coming in Neumann?

**Comment by christophstrobl** [comment]
@vpavic @gregturn there's already a branch with the required changes ([spring-session-data-mongodb/mongo-driver-4_0](https://github.com/spring-projects/spring-session-data-mongodb/tree/mongo-driver-4_0)) for Spring Session MongoDB.

**Comment by artembilan** [comment]
See https://github.com/spring-projects/spring-integration/issues/3121.

This is going to be one more argument to release Spring Integration 5.3 in time for Spring Boot 2.3.

Thanks for heads up!

**Comment by christophstrobl** [comment]
SD-MongoDB 4.0 (beta1) driver changes are on master now. I'll update https://github.com/christophstrobl/spring-boot/tree/mongo-driver-4_0 and open a PR.

**Comment by snicoll** [comment]
Closing in favour of PR #19960 

Thanks Christoph!
