### ISSUE TITLE
Add reactor-kotlin-extensions into dependency when create a kotlin based webflux app

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#19353]
I was trying to upgrade [my sample](https://github.com/hantsy/spring-kotlin-coroutines-sample) to the following newest stack:

* Spring 2.2.2.RELEASE
* Java 11
* Kotlin/Webflux

When I tried to refresh the APIs according to the changes in the new dependencies and  found 

`WebClient....exchange().test()` is marked as **deprecated**, and the new *reactor.kotlin.test* is from `reactor-kotlin-extensions`.

I think it should be added into dependencies when creating a kotlin based webflux app.

```xml
        <!-- https://mvnrepository.com/artifact/io.projectreactor.kotlin/reactor-kotlin-extensions -->
        <dependency>
            <groupId>io.projectreactor.kotlin</groupId>
            <artifactId>reactor-kotlin-extensions</artifactId>
            <version>1.0.1.RELEASE</version>
            <scope>test</scope>
        </dependency>
```

>I just used it in test scope, it could be added into *compile* ?

**Comment by snicoll** [comment]
@hantsy If you're requesting a change on start.spring.io, this is the wrong place to ask, there is [a dedicated project for that](https://github.com/spring-io/start.spring.io). As for the deprecation itself and the move to a separate module, this is something out of our control and nothing we can do in Spring Boot itself I am afraid.
