### ISSUE TITLE
Log4J2LoggingSystemTests loggingThatUsesJulIsCaptured unintentionally uses Logback

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19365]
The test requires severe logging to be output for it to pass but does not ensure that this will be the case. We should set the log level before making the logging call.

**Comment by wilkinsona** [comment]
My initial theory was wrong. The problem is that when the `SLF4JBridgeHandler` retrieves an SLF4J it is a `ch.qos.logback.classic.Logger` rather than a Log4j2 logger. The test then passes or fails based on whatever state previous tests left Logback in. For the test to work properly, we need `org.apache.logging.log4j:log4j-slf4j-impl` to be on the classpath before or in place of Logback. Other tests need Logback before in in place of Log4j2, however, so we can't just add a dependency. We may be able to use the modified classpath runner.

**Comment by wilkinsona** [comment]
We can't use the modified classpath runner as Log4j2 makes some assumptions about the class loader hierarchy that break it. See [this commit](https://github.com/spring-projects/spring-boot/commit/45a24b87051243f80775e283d1e127b80cdb7d02) for details. We'll have to remove the test for now. In 2.3 we want to split out the logging systems into separate build-only modules that are merged into `spring-boot`.

**Comment by wilkinsona** [comment]
> In 2.3 we want to split out the logging systems into separate build-only modules that are merged into `spring-boot`.

This isn't as easy as we'd hoped. To move the logging systems out into separate modules would require them to be depended upon by `spring-boot` so that it could include their classes in its jar. We'd have a dependency from `spring-boot` to each of the new logging system modules. Unfortunately, the logging system code currently depends on code elsewhere in `spring-boot`. There are imports of code in both `org.springframework.boot.ansi` and `org.springframework.boot.system`. The latter is just for `ApplicationPid` and could be duplicated at little cost. The former is a bigger problem as it's multiple classes and the code is more complex. The `org.springframework.boot.ansi` package doesn't depend on any other `org.springframework.boot` packages so it could be moved out too, but it's starting to get increasingly complex and I'm not sure it's worth it.

**Comment by philwebb** [comment]
I think I've fixed this by using `@ClassPathOverrides` but I had to change `ModifiedClassPathClassLoader` to not exclude log4j by default. For failing tests, I've manually added a log4j `@ClassPathExclusions` annotation.
