### ISSUE TITLE
Micrometer's Dynatrace group property cannot be configured via application properties

### ISSUE THREAD

**Issue by diepet** [spring-projects/spring-boot#19368]
From Micrometer 1.2.0 the following property has been added in order to set the Dynatrace process group name of where the metrics will be published:

`management.metrics.export.dynatrace.group=mycustomgroup`

I added the above property in an `application.properties` file of a simple Spring Boot 2 app, but it is completely unused.

Spring Boot 2 version used `2.2.2.RELEASE`. 

More details about that property are in the following Micrometer issue:

https://github.com/micrometer-metrics/micrometer/issues/1464

**Comment by snicoll** [comment]
Closing in favour of PR #19369
