### ISSUE TITLE
AbstractErrorWebExceptionHandler should not keep exchange response headers in an error response

### ISSUE THREAD

**Issue by timsazon** [spring-projects/spring-boot#19371]
I ran into a problem where one of my Gateway Filter which filters an exchange response throws an exception. 
There was a header `Content-Encoding: gzip` in the response and this header (along with the rest) was forwarded to error response headers. But the `ServerResponse` body was written as JSON (error attributes) and wasn't zipped therefore a server response is incorrect.

I suggest clearing all headers in an exchange's response in order to fix that and similar header problems.

Currently `AbstractErrorWebExceptionHandler` just overwrites `Content-Type` header of the response:
```
private Mono<? extends Void> write(ServerWebExchange exchange, ServerResponse response) {
	// force content-type since writeTo won't overwrite response header values
	exchange.getResponse().getHeaders().setContentType(response.headers().getContentType());
	return response.writeTo(exchange, new ResponseContext());
}
```
which can be replaced with
`exchange.getResponse().getHeaders().clear();`

**Comment by bclozel** [comment]
Clearing all response headers is a bit harsh, as we might remove security-related headers.
When handling errors we must clear assumptions about the response body, so both `Content-Type` and `Content-Encoding` seem reasonable.
Maybe clearing all response headers makes sense from a Spring Cloud Gateway perspective, but in this case it should be handled there.
I'm closing this issue in favour of #19372 - I'll ask you to amend it there.
Thanks!
