### ISSUE TITLE
Devtools cannot be use with jaxws-ri

### ISSUE THREAD

**Issue by Canos** [spring-projects/spring-boot#19379]
Since Java 11 we have to include a dependency to jaxws-ri to use javax.xml.ws.* clases in our code.
After including the dependency i'm getting an error if devtools is enabled.
Everything works fine if devtools is removed.

```
java.lang.IllegalArgumentException: interface <name-of-the-class-using-javax.xml.ws> is not visible from class loader
```

My first impression was that generated sources' creating problems and I tried to exclude them from devtools by creating a META-INF/spring-devtools.properties but actually the class is not visible is not generated. 
So i tried to exclude the jakarta jars, but it's still failing.

The dependency i'm using is
```xml
<!-- https://mvnrepository.com/artifact/com.sun.xml.ws/jaxws-ri -->
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>jaxws-ri</artifactId>
    <version>2.3.2</version>
    <type>pom</type>
</dependency>
```

I've tested Java 11 and 8.
At the moment i have only tested in Spring Boot 2.2

**Comment by bclozel** [comment]
Could you provide the complete stacktrace? I don't understand what the application was trying to do when this error happened. When does this error happens? Startup time, runtime, when devtools restarts the application after a change in a specific class?
Also, why are you importing the `jaxws-ri` which is a POM for a zipped bundle (including samples and documentation). Are you sure this is the preferred way of consuming this artifact? Shouldn't you have regular compile dependencies instead?

**Comment by Canos** [comment]
The error not happens on start up.  
It raises when using the webservice during runtime.

It's happening in the first run, not when devtools restarts.

Stacktrace:
![stacktrace](https://user-images.githubusercontent.com/1698420/70905065-400ff600-2003-11ea-8bea-5800d09b67db.png)

it seems that importing the pom is the right way, atm i'm investigating any alternative on this topic.

**Comment by bclozel** [comment]
It seems that this jaxws class is trying to create a proxy for an application class which is not visible from the base classloader (what's the visbility of your `SerClsWSEntrada` class and its methods?).

You could try changing the visibility of that class, and it might be the simplest solution.
Or you could move the `com.sun.xml.ws` jars to the restart classloader like this:

    restart.include.projectcommon=/jax-ws-[\\w\\d-\.]+\.jar

I haven't tested this code snippet so you might want to [read about this in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-devtools-customizing-classload) and try variants of this.

Please let us know if this worked out for your application.

**Comment by Canos** [comment]
Thanks Brian. 

Updates:
All the methods in SerClsWSEntrada are public.
I checked the pom looking for multiple duplicated javax.ws imports but nothing relevant found.

That line you said, makes nothing because the jar file is now behind jakarta naming, so i changed to:
```
restart.include.projectcommon=/jakarta.xml.ws-api-[\\w\\d-\.]+\.jar
```
That makes the process breaks one step before, while creating the bean instead of while calling the webservice, saying: 
`javax.xml.ws.WebServiceException: Error while searching for service [javax.xml.ws.spi.Provider]
com.sun.xml.ws.spi.ProviderImpl not a subtype of javax.xml.ws.spi.provider 
`
The fact that the process breaks before makes me guess this restart.include is not making what you were looking for.

For the moment i'll disable devtools, and everything works as expected until futher ideas.

Thanks

**Comment by bclozel** [comment]
I'm confused. Your first comment mentions this [dependency](https://search.maven.org/artifact/com.sun.xml.ws/jaxws-ri/2.3.2/pom) which is not bringing jakarta dependencies on the classpath.
This type of error message can also be a sign of conflicting dependencies. Could you provide a sample application replicating this issue so I can take a proper look? Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Canos** [comment]
it was not a bug, it was a classloader problem due to a Jdk9 change of behavior in ForkJoinPool threads, more info here https://stackoverflow.com/a/59444016/878015

Sorry to bother you, next time i'll be more precise before posting. Thanks.
