### ISSUE TITLE
The Gradle plugin is not compatible with the Gradle's builtin Java test fixtures plugin

### ISSUE THREAD

**Issue by bsautel** [spring-projects/spring-boot#19380]
I noticed that when using both the Spring Boot Gradle plugin, the [Java library plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html) and the [Java test fixtures plugin](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures), the tests are broken using Gradle 6 whereas they are successful with Gradle 5. All tests are broken because the production code (the `main` source set) is not in the classpath (`NoClassDefFoundError`).

I read that the [Spring Boot Gradle plugin documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#getting-started) suggests to use the [Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html) and not the Java library plugin. Indeed, that makes sense, I am building an application and not a library. If I use the Java plugin instead of the Java plugin library, the tests no longer compile. This time, it is the same problem but at compile time instead of runtime: the production code is not accessible from the test code. And this time, this does not work neither with Gradle 5.

In both cases, the problem comes from the same thing: for some reason, the test fixtures plugin makes Gradle reference the `main` classpath using the jar file and not the build output file (`build/classes/java/main`). But when using the Spring Boot plugin, this jar file exists, but is executable. It contains only the bootstrap classes, the `main` classes are in the `BOOT-INF/classes` directory. When used in the classpath, those classes do not exist.

It sounds like when using the Java plugin, the jar is used at compile time and at runtime, whereas when using the Java library plugin, it is only used at runtime since the tests compile.

I found a workaround:
1. Change the name of the Spring Boot application jar:
```groovy
bootJar {
    archiveFileName = "another-name.jar"
}
```
2. Enable the jar task that is disabled by the Spring Boot plugin:
```groovy
jar {
    enabled = true
}
```
In these conditions, the jar generated by the Java plugin (containing only the `main` classes) exists as usual and the Spring Boot application jar already exists, each one having a different usage.

I created a [simple project](https://github.com/bsautel/spring-boot-gradle-java-test-fixtures-issue) that reproduces that.

**Comment by wilkinsona** [comment]
Thanks for the sample.

I think this will need to be raised as a Gradle issue as the behaviour that you've described is largely out of Spring Boot's control and seems inconsistent:

- Using Gradle 5.6.4 and the `java-library` plugin, `/build/classes/java/main` is on the classpath of the `test` task and the build passes. Using Gradle 6.0, it is not and the build fails. This would appear to be a regression in Gradle 6.0.
- Using Gradle 5.6.4 or 6.0 and the `java-library` plugin,  `/build/classes/java/main` is on the classpath of `compileTestFixturesJava`. Using Gradle 5.6.4 or 6.0 and the `java` plugin, `build/libs/spring-boot-gradle-java-test-fixtures-issue-0.0.1-SNAPSHOT.jar` is on the classpath of `compileTestFixturesJava`. The [documentation](https://docs.gradle.org/5.6/userguide/java_testing.html#sec:java_test_fixtures) states that the classes from the main source set will be visible so the latter seems to be contrary to the documentation.

Please open a Gradle issue and comment here with a link to it. I'll subscribe to it and help as needed.

**Comment by bsautel** [comment]
Thanks for you answer. I reported this issue to [Gradle](https://github.com/gradle/gradle/issues/11696).
