### ISSUE TITLE
Docs: File rotation text not updated after logging maxHistory changes

### ISSUE THREAD

**Issue by Anden** [spring-projects/spring-boot#19386]
Hi, found a problem in the documentation:

https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging-file-output
> Previously rotated files are archived indefinitely unless the logging.file.max-history property has been set. 

Since #15875 logging.file.max-history is set to 7 by default, so above text should be updated.

**Comment by snicoll** [comment]
This should have done as part of #15875, Closing in favour of PR #19458
