### ISSUE TITLE
Make it clear that spring-boot-starter-hateoas is for Spring MVC

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-boot#19391]
When you grab `spring-boot-starter-hateoas` and `spring-boot-starter-webflux` things fall apart. That's because the starter for Spring HATEOAS pulls in Spring MVC, and thus starts trying to configure things for that. The WebFlux stuff just doesn't kick in.

The user must exclude Spring MVC in order for it to work, e.g.

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-hateoas</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

And should there be a comparable `spring-boot-starter-hateoas-webflux` (or `-reactive-hateoas`)?

**Comment by wilkinsona** [comment]
> And should there be a comparable `spring-boot-starter-hateoas-webflux` (or `-reactive-hateoas`)?

There should. We tried to do it in 2.2 but it didn’t make it. See https://github.com/spring-projects/spring-boot/issues/16020 for details. Time permitting, we can have another go in 2.3 if we agree it makes sense to do so.

**Comment by philwebb** [comment]
I consider this one a duplicate. It's already listed in initial comment of #16020
