### ISSUE TITLE
Typo in configuration key in configuration structure topic of Spring Boot Configuration Binding wiki

### ISSUE THREAD

**Issue by AtulDwivedi** [spring-projects/spring-boot#19396]
There is typo in one of the configuration key mentioned on [Spring Boot Configuration Binding](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding) wiki page.

In the explanation of topic [Configuration Structure](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding#configuration-structure) mentioned key `server.tomcat.port.max-threads` is incorrect, it should be `server.tomcat.max-threads`.

**Comment by snicoll** [comment]
@AtulDwivedi thank you for reporting it, I've fixed the typo.
