### ISSUE TITLE
Allow actuator endpoints to be exposed at multiple paths

### ISSUE THREAD

**Issue by tvrmsmith** [spring-projects/spring-boot#19406]
I'd would be great if the actuator endpoints could be exposed at more than one path. Right now my team is upgrading from Spring Boot 1.x and having the ability for the applications to expose their health check at the old '/health' path as well as the new '/actuator/health' would make migrating less painful. With that capability, we could gradually upgrade our apps without having to ensure that our infrastructure has been changed to check the new path. Then, after the fact, go back and point them to the new path. 

This could be accomplished by allowing any set of arbitrary paths or a set of paths relative to the actuator base path.

Thanks for all your hard work, Spring Boot is a great project!

**Comment by bclozel** [comment]
In general, I don't really see the point of exposing actuator endpoints on multiple locations. There were [a lot of changes in that space between 1.x and 2.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-boot-actuator): base paths, endpoints, security defaults, the payloads and even the media type. So it won't really help migration, but maybe discovery.

Now the `/health` endpoint is a specific case, but it means that your health check client is only considering the HTTP response code (and not parsing the response body or relying on the media type). Also, one of the main drivers behind changing the base path is to avoid collisions between actuator endpoints and application endpoints - so exposing everything back at the root might create different migration issues.

[Spring Boot 1.5.x and 2.0.x have been EOL for a few months already](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions), and we've announced 2.1.x EOL date as well. At that point in time, I think we've missed that opportunity and developers got around that issue. Some projects, like [Spring Boot Admin](https://github.com/codecentric/spring-boot-admin) are using a mix of heuristics and apps registering themselves.

Now back to your problem, I think you can solve this with something like:

```
@Configuration
public class ActuatorWebConfig implements WebMvcConfigurer {

	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addViewController("/health").setViewName("/actuator/health");
	}
}
```

Given the timeline and the possible solutions, I don't think we're going to implement this.
If you've got other ideas in mind, or more context to share (how are you declaring apps to your health check infrastructure, how is it processing the health response, is it using other endpoints and how?), we might come up with a better solution.

We'll share a first [Milestone for 2.3.0 pretty soon](https://github.com/spring-projects/spring-boot/milestone/157) - this should give you a chance to review changes and give feedback; I hope you'll get the opportunity to check it out.

Thanks for the kind words, and thanks for sharing your experience!

**Comment by bclozel** [comment]
Thanks for your feedback!
