### ISSUE TITLE
Exceptions thrown in ControllerAdvice class are not handled correctly

### ISSUE THREAD

**Issue by mus65** [spring-projects/spring-boot#1940]
Consider the following simple ControllerAdvice class:

```
@ControllerAdvice
public class TestControllerAdvice {

    @ModelAttribute
    public boolean test() {
        throw new RuntimeException("test");
    }
}
```

I would expect the whitelabel error page to be displayed. Instead, there will only be a blank page when running with an embedded Tomcat. When deployed on a standalone Tomcat server, it will even show the default Tomcat error page with the stack trace.

I confirmed this behaviour on 1.1.9 and 1.2.0.RC1.

**Comment by Jacksai** [comment]
Could someone provide alternative for this kind of Error Handling ?

**Comment by dsyer** [comment]
You mean other than checking the dispatcher type or not throwing exceptions or not binding to model data (that's 3 ways to work around it)? I can't see any reason to use `@ModelAttribute` in `@ControllerAdvice` anyway (how can it handle all requests to all endpoints with a single model?).

**Comment by rstoyanchev** [comment]
If an error occurs while trying to render an error (during an ERROR dispatch) I'm not surprised the outcome is undefined. Error handling should be as simple and fail-safe as possible. 

That said I can see how the use of a @ControllerAdvice in this case has an unexpected side effect. Do you need the @ControllerAdvice that's adding a model attribute to be as "global" or would making it more selecting (through its attributes) make sense for your case? 

I think a case could also be made also for Spring Boot's error handling to use a simple HttpRequestHandler (something like an error component that implements HandlerMapping and HttpRequestHandler). That might insulate it a little better from application code like this. 

I'm also surprised that the DispatcherType is different with embedded vs standalone Tomcat. Is that expected? It doesn't make sense intuitively that it should be different.

**Comment by dsyer** [comment]
> I think a case could also be made also for Spring Boot's error handling to use a simple `HttpRequestHandler`

The idea is that it can be provided by a user and so we want it to be an `@Controller` really (the default implementation uses `@RequestMapping`), to make it as "normal" as possible. Unfortunately `@ControllerAdvice` can always be added by users and get into the handler execution where it might not be wanted or needed. I don't see a good way round that (other than the existing workarounds mentioned above).

> I'm also surprised that the `DispatcherType` is different with embedded vs standalone Tomcat. Is that expected?

I'm not sure we can change that (but it might be worth a look). The FORWARD comes from the `ErrorPageFilter` without which standalone Tomcat does not have the same error handling as the embedded case. We have to try and control the error handling, and as soon as we let the container send an ERROR dispatch, we have lost it.

**Comment by rstoyanchev** [comment]
Okay I see. Regarding the FORWARD from ErrorPageFilter, it sets up the "javax.servlet.error.*" request attributes so the ControllerAdvice could check for that (vs DispatcherType). 

Again considering the feature to have an @Controller as an error handler, an @ControllerAdvice takes on additional responsibility to be careful about how an @ModelAttribute method is implemented to avoid interfering with error-handling controllers.

**Comment by mus65** [comment]
btw, I had another look at the ```ControllerAdvice``` attributes and am now using a less hackish workaround. I simply use ```basePackageClasses = Application.class``` which works fine in my case since ```Application.java``` is in my root package and all my controllers are in a sub-package.

**Comment by philwebb** [comment]
This is quite an old issue so I'm assuming most people have worked around it. I'm going to close it for now, but if it's still causing big problems please add a comment.
