### ISSUE TITLE
Clarify the behaviour of @CacheConfig with respect to on-the-fly cache creation and cache metrics

### ISSUE THREAD

**Issue by jorgheymans** [spring-projects/spring-boot#19412]
When cache names are configured in application.properties, metrics are automatically provided through actuator (in my case prometheus)

```
spring.cache.type=caffeine
spring.cache.cache-names=cacheA,cacheB
```

```
# HELP cache_puts_total The number of entries added to the cache
# TYPE cache_puts_total counter
cache_puts_total{cache="cacheA",cacheManager="cacheManager",name="cacheA",} 5.0
cache_puts_total{cache="cacheB",cacheManager="cacheManager",name="cacheB",} 65.0
... etc
```

However when i instead define cache names locally using `@CacheConfig` on the class where the cache is used , the metrics are no longer provided through actuator. Note the cache itself still works fine, just no metrics.

If this works as intended, it's sligthly surprising nonetheless.

**Comment by snicoll** [comment]
> If this works as intended

Yes. Please [review the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-cache) and #14576.

**Comment by jorgheymans** [comment]
Thanks, i have added a note there.

**Comment by snicoll** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/8f9d9fa20edd90ab9832c18297b6311253fa8aec
