### ISSUE TITLE
Provide a condition for detecting war deployments

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19421]
If a war file is deployed to Tomcat, Jetty, or Undertow, we currently configure and customise the servlet web server factory even though it will never be used. It [would be useful](https://github.com/spring-projects/spring-boot/issues/19308#issue-533428577) to be able to make the configuration and customization conditional on the app not being deployed to an external container.

**Comment by spencergibb** [comment]
Spring Cloud has a similar requirement to do something different in a war.

**Comment by philwebb** [comment]
Adding a note here in case we need to return to this issue in the future. 

The code below currently works because we set the `ServletContext` quite late in the embedded case. With a war deployment, it's set very early.

```java
		ServletContext servletContext = applicationContext.getServletContext();
			if (servletContext != null) {
				return ConditionOutcome.match("Application is deployed as a WAR file.");
			}
```
