### ISSUE TITLE
Configurer for RabbitTemplate similar to SimpleRabbitListenerContainerFactoryConfigurer

### ISSUE THREAD

**Issue by ryandanielspmc** [spring-projects/spring-boot#19440]
Often, you might want multiple `RabbitTemplate` instances with slight variations on the default properties. `RabbitAutoConfiguration` configures a default `RabbitTemplate` with settings pre-populated from `RabbitProperties.Template` and `RabbitProperties.Retry`. But, as far as I know, you cannot get multiple unique instances from `RabbitAutoConfiguration`. It would be great to have something similar to `SimpleRabbitListenerContainerFactoryConfigurer` that would allow applying the default settings to custom-made `RabbitTemplate` instances.

**Comment by snicoll** [comment]
@ryandanielspmc that's an interesting idea, thank you.

**Comment by garyrussell** [comment]
@snicoll Yes, it seems like a reasonable request to me and will help users to avoid referencing `RabbitProperties` directly, which is discouraged.

**Comment by snicoll** [comment]
Good point Gary, tentatively adding that to `2.3.x`.

**Comment by snicoll** [comment]
@ryandanielspmc this will be available in a `2.3.0.BUILD-SNAPSHOT` shortly and in `2.3.0.M1` in January. If you can give it a try and let us know if that works out for you that would be great.
