### ISSUE TITLE
Spring Integration Doc Improvement

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#19462]
You can assign this to me if you wish and I will address it next year.

>Spring Boot offers several conveniences for working with Spring Integration, including the spring-boot-starter-integration “Starter”. Spring Integration provides abstractions over messaging and also other transports such as HTTP, TCP, and others. If Spring Integration is available on your classpath, it is initialized through the @EnableIntegration annotation.

This is no longer true; we removed the "other" jars from the starter a long time ago to avoid over-populating the class path.

>and also other transports such as HTTP, TCP, and others

Should be removed; perhaps replace it with

>Spring Boot offers several conveniences for working with Spring Integration, including the spring-boot-starter-integration “Starter”. Spring Integration provides abstractions over messaging. If Spring Integration is available on your classpath, it is initialized through the @EnableIntegration annotation. Note that the starter only adds the `spring-integration-core` module; if you wish to use other integration modules (e.g. `spring-integration-ip`, `spring-integration-http`), you should add them to your pom or build script. Spring Boot will manage the version of all standard modules added this way so you should not specify a verdsion. Versions for eextension projects (such as `spring-integration-kafka`) are not managed by Boot so you will need to add appropriate versions for those modules when adding them.

/cc @artembilan

**Comment by snicoll** [comment]
> Should be removed; perhaps replace it with

I read that more as a feature of Spring Integration than something that comes out of the box with the starter. Or are you saying that this statement of Spring Integration is no longer true?

**Comment by artembilan** [comment]
I'm not sure, Stephane, what is misleading you in Gary's request, but I know that many beginners would like to understand how to have access to some protocol-specific Spring Integration channel adapters in Spring Boot.
The starter really comes only with the `core` module: everything else has to be added into dependencies explicitly.

A description about Spring Integration features is already out of Spring Boot scope.

**Comment by garyrussell** [comment]
>and also other transports such as HTTP, TCP, and others

I am saying this part is no longer true. The original starter pulled in core + a handful of modules. That is no longer the case (users complained about getting jars on the CP that they didn't need.

https://github.com/spring-projects/spring-boot/commit/c06828558609d2da58fa9f45dff1f1095b93778c#diff-d96284c213e252bbf65057cbfffe4636

**Comment by garyrussell** [comment]
Sorry, I read this

>and also other transports such as HTTP, TCP, and others.


as if the starter does that (which it no longer does and also other transports such as HTTP, TCP, and others.).


I still think it would be useful to add this

>Note that the starter only adds the spring-integration-core module; if you wish to use other integration modules (e.g. spring-integration-ip, spring-integration-http), you should add them to your pom or build script. Spring Boot will manage the version of all standard modules added this way so you should not specify a verdsion. Versions for eextension projects (such as spring-integration-kafka) are not managed by Boot so you will need to add appropriate versions for those modules when adding them.

**Comment by garyrussell** [comment]
Sorry, I read this

>and also other transports such as HTTP, TCP, and others.


as if the **starter** does that (which it [no longer does](https://github.com/spring-projects/spring-boot/commit/c06828558609d2da58fa9f45dff1f1095b93778c#diff-d96284c213e252bbf65057cbfffe4636)) .


I still think it would be useful to add this

>Note that the starter only adds the spring-integration-core module; if you wish to use other integration modules (e.g. spring-integration-ip, spring-integration-http), you should add them to your pom or build script. Spring Boot will manage the version of all standard modules added this way so you should not specify a verdsion. Versions for eextension projects (such as spring-integration-kafka) are not managed by Boot so you will need to add appropriate versions for those modules when adding them.

**Comment by snicoll** [comment]
> A description about Spring Integration features is already out of Spring Boot scope.

Correct but the proposed change removes what Spring Integration is able to do and I am not keen to do that. I am not denying we should clarify what the starter brings though but that's two different things.

> I still think it would be useful to add this

Rather than specifying which "jar" is added by the starter, how about describing what features are available without any extra dependency. The remaining of that section is already describing optional features such as JMX and JDBC. I'd rather expand that section to cover what used to be provided by the starter.

As for versioning and references to Spring Kafka, I don't think this is warranted in that level of details. There are a bunch of other areas where things can be added and we don't remind users constantly that they don't have to put a version for dependencies. Have I missed something?

**Comment by garyrussell** [comment]
>how about describing what features are available without any extra dependency

It's difficult to summarize in a few words; the `-core` module has all of the (eh) **core** SI functionality.

>As for versioning and references to Spring Kafka, I don't think this is warranted in that level of details.

OK; I know that (at least with eclipse/STS) if you provide a version when one is not needed you get a warning and you get an error when one is needed.

I am OK with closing this, if you prefer to leave it as-is.

**Comment by snicoll** [comment]
Thanks for the feedback. I read the section again and if we don't have a proposal to improve the description of the starter, I think we can keep things as they are.
