### ISSUE TITLE
http2 protocol upgrade does not work well when the request has body

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-boot#19460]
check it here:

[spring boot netty server for http2 results in 413](https://stackoverflow.com/questions/59466859/spring-boot-netty-server-for-http2-results-in-413/59467416#59467416)

pom:
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

**Comment by bclozel** [comment]
This is a Netty feature and it seems it is not considered as a bug, but rather a configuration choice. See https://github.com/netty/netty/issues/7079.

In any case this is not something we can change in Spring Boot. You can create a new issue in reactor Netty here https://github.com/reactor/reactor-netty/issues
