### ISSUE TITLE
Allow Gson to be configured declaratively

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1946]
`GsonBuilder` allows a custom `Gson` instance to be created. `GsonAutoConfiguration` could be updated to use `GsonBuilder` and configure it from `spring.gson.*` properties in much the same way as `JacksonAutoConfiguration` does with `spring.jackson.*` properties

**Comment by geoff-wasilwa** [comment]
Hi @wilkinsona is this still being worked on?

**Comment by wilkinsona** [comment]
Not to my knowledge. It's just a possible enhancement at the moment. Pull requests welcome.

**Comment by ioanngolovko** [comment]
Hi @wilkinsona. I want to implement this as well as jackson.  I have an only one question.

In which branch to make a pull request?

**Comment by wilkinsona** [comment]
@ioanngolovko Against the master branch, please.

**Comment by izeye** [comment]
This looks resolved via https://github.com/spring-projects/spring-boot/pull/11498.

**Comment by snicoll** [comment]
Indeed @izeye, thanks!

Duplicate of #11498
