### ISSUE TITLE
spring webflux returned Mono is very confusing

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-boot#19470]
```
public Mono<ResponseEntity> handler(ServerRequest req) {
    return a concrete Mono;
}
```

Mono is an abstract type, and it has multiple concrete types. But not every concrete type is feasible as the returned `Mono<ResponseEntity>`. For example:
`Mono.just(...)`  works fine with a body but
`Mono anotherMono = myMono.map(m - > {})` fails. 
Because the second one is a `MonoMapFuseable` Mono, while the first one is a `MonoJust` Mono. If a method only expects certain kinds of types, it should not use the abstract type.

**Comment by snicoll** [comment]
@Jovons While being abstract, `Mono` represents a certain contract (0 or 1 value emitted). Asking about project reactor here is the wrong channel to do so. Please join the community on [their gitter channel](https://gitter.im/reactor/reactor) or ask questions on StackOverflow.
