### ISSUE TITLE
Springboot Repository Consecutive Queries Return The Same Results

### ISSUE THREAD

**Issue by bliu13** [spring-projects/spring-boot#19489]
I am experienced this weird issue with the repositories where when I make 2 database queries in the same controller function consecutively, all the results that are returned are the same as the first database query.

Example: If I call getPredictedValue() followed by getCalled(), depending on the order that these two functions are called, I get the same result for the second function call as the first call.

```
@Repository
public interface SomeRepository extends PagingAndSortingRepository<SomeObject, Integer> {
  @Query(nativeQuery=true, value="SELECT SUM(c.count_of_something) AS num_of_something, " +
      "TO_CHAR(c.inserted_at, 'HH24:00:00') AS hour_of_the_day " +
      "FROM some_table c " +
      "GROUP BY TO_CHAR(c.inserted_at, 'HH24:00:00') " +
      "ORDER BY TO_CHAR(c.inserted_at, 'HH24:00:00')")
  public List<SomeObject> getPredictedValue();

  @Query(nativeQuery=true, value="SELECT COUNT(c.*) AS num_of_something, " +
      "TO_CHAR(c.inserted_at, 'HH24:00:00') AS hour_of_the_day " +
      "FROM some_table c " +
      "GROUP BY TO_CHAR(c.inserted_at, 'HH24:00:00') " +
      "ORDER BY TO_CHAR(c.inserted_at, 'HH24:00:00')")
  public List<SomeObject> getCalled();
}
```

**Comment by snicoll** [comment]
@bliu13 you'd have to create a small sample that reproduces the issue you're experiencing (a zip or a github repo with instructions on how to reproduce the problem. Running those queries directly against your data store (in the same session) would also be in order before reporting [an issue to Spring Data](https://jira.spring.io/projects/DATAJPA/issues).
