### ISSUE TITLE
WebMvcAutoConfiguration : the order of static RESOURCE_LOCATIONS

### ISSUE THREAD

**Issue by hepengju** [spring-projects/spring-boot#19485]
In my project, I want add a favicon.ico, then I put it into public. Always it's OK. 
But when I use a third jar knife4j(swagger), it has a favicon.ico in his META-INF/resources.
So I have to adjust spring.resources.static-locations config.

I think my static files should have the highest priority, but not the third jar, please think about it.
```
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
```

**Comment by snicoll** [comment]
Sorry but there's not much we can do if there are competing resources on the classpath. It's the same issue with any other duplicate resources you may have and not something we have control over.
