### ISSUE TITLE
Can't use `springBoot` scope in Kotlin build script

### ISSUE THREAD

**Issue by heowc** [spring-projects/spring-boot#19495]
Hi, I have a question.

There is a question about `spring-boot-gradle-plugin`. I written about spring boot example that allows the specified version (ex. `2.2.1.RELEASE`).

`springBoot` scope is not available when applying `spring-boot-gradle-plugin` written in legacy plugin application style. But the plugin DSL style is not a problem.

I know that there is no dynamic version assignment in the plugins scope in Kotlin build scripts, so I have to write in the legacy plugin application style.

The code is as follows:

Using legacy plugin application:
```kotlin
buildscript {
  repositories {
    gradlePluginPortal()
  }
  dependencies {
    classpath("org.springframework.boot:spring-boot-gradle-plugin:2.2.1.RELEASE")
  }
}

apply(plugin = "org.springframework.boot")

springBoot {
  mainClassName = "blabla~~"
}
```
> e: .../build.gradle.kts:25:1: Unresolved reference: springBoot

Using the plugins DSL:
```kotlin
plugins {
  id("org.springframework.boot") version "2.2.1.RELEASE"
}

springBoot {
  mainClassName = "blabla~~"
}
```
> no problem

I'm asking here because I don't know exactly which problem. Thanks! 😄

**Comment by snicoll** [comment]
> Hi, I have a question.

Please consider reviewing the issue template before contribution. It has a specific section about not asking questions here, see also [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues).
