### ISSUE TITLE
Outdated reference in ArtemisConfigurationCustomizer javadoc

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19502]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
The Javadoc of `ArtemisConfigurationCustomizer` has a reference to `EmbeddedJMS` that is a deprecated type. The auto-configuration now uses the replacement, `EmbeddedActiveMQ` but the reference in the Javadoc was not updated.

## Solution
The class Javadoc of `ArtemisConfigurationCustomizer` should rather be:

```java
/**
 * Callback interface that can be implemented by beans wishing to customize the Artemis
 * JMS server {@link Configuration} before it is used by an auto-configured
 * {@link EmbeddedActiveMQ} instance.
 *
...
```

When replacing the class reference, make sure to remove the unused `EmbeddedJMS` import.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by ochiengolanga** [comment]
@snicoll sign me up

**Comment by snicoll** [comment]
Thank you very much @ochiengolanga, it's yours. Let us know if you need anything.

**Comment by snicoll** [comment]
Closing in favour of PR #19503
