### ISSUE TITLE
Spring boot Conectivty for intelij ide

### ISSUE THREAD

**Issue by madilraza** [spring-projects/spring-boot#19551]

**Comment by bclozel** [comment]
I don't understand the problem here. Could you edit this issue to explain the bug or the requested feature? If it's a bug, a minimal Spring Boot application reproducing the issue is really helpful.

Thanks,

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
