### ISSUE TITLE
Document that actuator over HTTP requires Jackson

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19564]
A customer reported an issue to the Apps Manager team that was due to changes in the actuator API. The status keys have a value that is an object like:

```
"status": {
        "code": "UP",
        "description": ""
      }
```

The root cause is [this annotation](https://github.com/spring-projects/spring-boot/blob/c9ad3564d9b20a7c1493210650db3ee683cc7661/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/HealthComponent.java#L38) not being respected if Jackson isn't being used.

**Comment by ericus20** [comment]
How can I take up this issue and work on it?

**Comment by philwebb** [comment]
Hi @ericus20, thanks for the offer of help. I think we really need an additional note in our [Actuator API documentation](https://docs.spring.io/spring-boot/docs/2.2.2.RELEASE/actuator-api/html/) that lets people know that they need to be using Jackson in order to get the correct JSON responses.

I think the best place would be in the "Overview" section.

If you're interested in adding that you can edit [this file](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/docs/asciidoc/index.adoc). It's written using asciidoctor markup which you can read about at https://asciidoctor.org/.

**Comment by ericus20** [comment]
@philwebb Thanks a lot. I will work on that then.

**Comment by maxim-nazarenko** [comment]
@philwebb what about [this documentation page](https://docs.spring.io/spring-boot/docs/2.2.4.RELEASE/reference/html/production-ready-features.html#production-ready-monitoring)?
I read it first as it is the first link I get in Google. Should it be updated as well?

**Comment by snicoll** [comment]
@maxim-nazarenko not sure that should be the reason to update this particular section.  I was about to say that it might make sense in the overview for endpoints but it already has a link to the part Phil referenced:

> To learn more about the Actuator’s endpoints and their request and response formats, please refer to the separate API documentation (HTML or PDF).

@ericus20 any update about this documentation update? Do you need help?

**Comment by ericus20** [comment]
Yeah, I am on it and almost through. Just double-checking a couple of stuff before I present it for review.

**Comment by maxim-nazarenko** [comment]
@snicoll I see, thanks for clarification.

I've created a #20173  but not sure what exactly should be put as a note.
If you could advise or provide me with an example of a good documentation section about dependencies, it would be great.

**Comment by snicoll** [comment]
@ericus20 hello, are you still willing to work on this issue?

**Comment by snicoll** [comment]
@ericus20 given the lack of feedback, I am putting this one back to the pool.

**Comment by maxim-nazarenko** [comment]
@snicoll does this PR #20173 cover the issue?
If so, I would like to help you with that and know more about SpringBoot internals to start helping not only with documentation stuff.

**Comment by snicoll** [comment]
@maxim-nazarenko I don't think it does but I would need to spend a bit more time to know for sure. I know @bclozel has done some changes in that area so I'll check with him today. Thanks for the PR in any case!
