### ISSUE TITLE
Embedded Mongo Auth Setup

### ISSUE THREAD

**Issue by p1Machado** [spring-projects/spring-boot#19583]
Context:

[EmbeddedMongoAutoConfiguration](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded)

I'm trying to setup embedded-mongo using authentication on integration tests.
As I have some custom mongodb configuration using authentication and would like not to change them in order to use embedded-mongo, it would be nice if the Spring Auto Configuration could handle authentication. [It looks like someone filled a PR on embedded-mongo repository in order to provide authentication setup](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/117/commits/c231ba7bd06b1b30034fd7e6ecb68a44a96dfef4)

Proposal:

As of the PR, you should notice that they've included a `Map<String, String> params();` on their `IMongodConfig`, therefore it could be a property params on Spring's `EmbeddedMongoProperties`.
Doing so, settings `spring.mongodb.embedded.params.UserName` and `spring.mongodb.embedded.params.Password` should enable `Mongo's --auth` mode.

**Comment by anandshastri1990** [comment]
Hi, I would be glad to work on this issue.

**Comment by snicoll** [comment]
@anandshah123 thank you!

**Comment by anandshastri1990** [comment]
@p1Machado @snicoll 
Looks like passing the username and password in the params is not enabling the Auth mode. 
I looked into the source code of embedded mongo repo and what I have found out so far is, Auth mode is disabled by default in the MongoCmdOptionsBuilder and enableAuth() method to set the auth mode is never used. Please let me know if I am missing something. 

I have made a work in progress commit, which has failing tests.
Error message: "BadValue: Illegal --setParameter parameter: "Password"".

**Comment by Lacritz** [comment]
@anandshastri1990 
I've added a request on de.flapdoodle.embed.mongo ([issue-link](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/311)) 
Probably they are adding a proper way to activate the `--auth` programmatically.

**Comment by SeifMostafa** [comment]
Hello, Any help?

**Comment by somayaj** [comment]
hi, what's the status on this? Can it be worked on?

**Comment by snicoll** [comment]
Thanks for asking @somayaj. The issue is already assigned but we haven't heard from them in a while. @anandshastri1990 how is it going?

**Comment by anandshastri1990** [comment]
@snicoll if you see the comment from @Lacritz the fix has to happen on "de.flapdoodle.embed.mongo" side. 
Looks like that's still open:  https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/311

Once that fix is done, I can push the necessary changes needed on Spring boot side.

**Comment by snicoll** [comment]
I missed that @anandshastri1990, thank you very much. I am going to add the `blocked` label to make that a bit more obvious.

**Comment by wilkinsona** [comment]
These days, we generally recommend the use of Testcontainers for managing services needed for integration testing rather than bespoke service-specific projects. Furthermore, the embedded Mongo issue is still open so there's nothing we can do here anyway.
