### ISSUE TITLE
Add configuration property for Reactor Netty shutdown quiet period

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#19607]
As of reactor/reactor-netty#860, we can now configure the quiet period after the shutdown of the Reactor Netty web server.
We should consider using that API in `NettyWebServer` and even change the default value for a shorter one when devtools is present: right now, restarting the application with devtools inflicts the default quiet period on the user, making the feedback loop longer than necessary.

**Comment by Lacritz** [comment]
Hi @bclozel,
is this issue currently still unassigned? I would like to contribute here - but currently not seeing the newly introduced api reflected in the current dependencies. Am i missing something?

**Comment by bclozel** [comment]
@Lacritz we need to address spring-projects/spring-framework#24538 first.

**Comment by bclozel** [comment]
This has been superseded by #4657
