### ISSUE TITLE
Port the build to Gradle

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19608]

**Comment by dreis2211** [comment]
Hi @wilkinsona. I maybe have a stupid question. Isn't that breaking the semi automatic dependency upgrade process? And is there maybe a replacement for it?

Could you elaborate on the reasoning behind moving to Gradle other than publishing metadata for the modules? Where there any problems with the Maven tooling?

Cheers,
Christoph

**Comment by wilkinsona** [comment]
>  I maybe have a stupid question. Isn't that breaking the semi automatic dependency upgrade process? And is there maybe a replacement for it?

It's built into the build now:

```
 ./gradlew spring-boot-project:spring-boot-dependencies:bomrUpgrade
```

> Could you elaborate on the reasoning behind moving to Gradle other than publishing metadata for the modules?

The Gradle metadata is really just an added bonus. The main motivation was to be able to reduce build times by parallelising the build (something we couldn't do in Maven due to our use of the Invoker plugin) and to take full advantage of Gradle's build cache.

**Comment by dreis2211** [comment]
Are the build times of 8-10 minutes correct? That would be an amazing improvement. 🚀

**Comment by wilkinsona** [comment]
Yep, they're correct. Things won't always be that good as that's pretty much a best-case scenario where there are lots of cache hits.
