### ISSUE TITLE
Update build instructions in README after switch to Gradle

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#19617]
Hi,

the README still mentions `mvn clean install` and alike for building the project.

Cheers,
Christoph

**Comment by philwebb** [comment]
Thanks, we've got a few issues like this left to sort out.

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. I remembered the notes in CONTRIBUTING.adoc but forgot that the README had some too.
