### ISSUE TITLE
Add quickstart mode 

### ISSUE THREAD

**Issue by zgqq** [spring-projects/spring-boot#19627]
Spring boot application start up with many features that are not useful for development.

**Comment by philwebb** [comment]
Could you provide a bit more background? Which features do you think aren't useful?

**Comment by zgqq** [comment]
@philwebb For example, security, actuator and... these auto-configurations don't help much in development environments.

**Comment by wilkinsona** [comment]
Thanks, @zgqq. I'm not sure that I agree security and actuator aren't useful in development environments. For example, if part of your development work is to configure your application's security then you'll need security to be enabled. If you want to disable it or change the configuration when working on other pieces of the application, you could use a profile to do so.

Unfortunately, I think that if we asked 10 different people what features they considered to be useful during development we'd get 10 different answers. The requirements will vary depending on the sort of app that's being developed and what piece of the app is being worked on. I think your best bet is to tailor things to suit your needs using profile-specific beans and properties.

Thanks anyway for the suggestion.
