### ISSUE TITLE
Offer "buildify" option in the CLI

### ISSUE THREAD

**Issue by habuma** [spring-projects/spring-boot#1964]
The Spring Boot CLI is a fantastic way to get your feet wet with Spring Boot, but a lot of developers consider it a toy, as they'll never be able to deploy their applications as CLI apps. Eventually, they'll likely graduate to a more traditional project structure built with Maven or Gradle and producing a JAR or WAR.

I noticed that Spring Boot CLI 1.2.0 has the "init" command to initialize a new Spring Boot project from Initializr (and I really like this feature). But I was thinking that another way to get to the same point might be for the CLI to offer a "buildify" command (obviously, a better name should be found) that takes an existing CLI-based project and graduates it to a conventional project structure.

Essentially it would:
- Move *.java to src/main/java
- Move *.groovy to src/main/groovy
- Move everything else to src/main/resources
- Create either a pom.xml or build.gradle file (developer's choice)
- Populate the build specification with appropriate dependencies (top-level, non-transitive dependencies that would be grabbed when running "spring grab" or "spring run")
- Set the build to produce either JAR or WAR (developer's choice)
- Set the build to compile either Java or Groovy (developer's choice unless there are *.groovy files, in which case it should default to Groovy)

There are other cases I'm likely overlooking.

In any event, this feature would enable someone to kick the tires with the CLI, even start prototyping a real app with the CLI, but then graduate to a traditional build if they want without having to start over.

**Comment by philwebb** [comment]
We've discussed this at our team meeting and we don't feel the amount of effort would be worth it.

**Comment by spencergibb** [comment]
Feels like atomist
