### ISSUE TITLE
 java.net.URL heap bigger and bigger

### ISSUE THREAD

**Issue by shihu19860215** [spring-projects/spring-boot#19667]
I have a very simple project .
It jush have one controller, use org.springframework.web.client.RestTemplate.postForObject to get info.
But heap is bigger and bigger, old gen is bigger and bigger。
old gen max 1G, if full gc , old gen 100m .
It can be full gc, but can't be young gc。
I dump heap. 
char[]  have 444k+ .
one kind of char[] has 100k-200k
it is be reference by java.net.URL.
watch 'jmap -histo 20213 |grep java.net.URL' and gc info
young gc can destroy  part  java.net.URL，but it is bigger and bigger.

![20200113184709](https://user-images.githubusercontent.com/33929319/72249971-845bd980-3635-11ea-8e63-11fe71631052.png)

![20200113185251](https://user-images.githubusercontent.com/33929319/72250286-34c9dd80-3636-11ea-951e-b4e9b4788a3e.png)

**Comment by wilkinsona** [comment]
@shihu19860215 Please do not open duplicate issues. This is a repeat of #19664.
