### ISSUE TITLE
Update documentation on excluding an auto-configuration to recommend exclude on SpringBootApplication

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19662]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
The [documentation for disabling specific auto-configuration](https://docs.spring.io/spring-boot/docs/2.2.2.RELEASE/reference/htmlsingle/#using-boot-disabling-specific-auto-configuration) describes how to use the `exclude` attribute on `@EnableAutoConfiguration`, but a typical Spring Boot application will use `@SpringBootApplication` rather than `@EnableAutoConfiguration`.

## Solution
The documentation should be updated to describe and demonstrate the use of the `exclude` attribute on `@SpringBootApplication` rather than `@EnableAutoConfiguration`. A sentence should be added after the example to note that, if you are using `@EnableAutoConfiguration` rather than `@SpringBootApplication`, it has an `exclude` attribute that can be used.

The following changes should be made:

- Update [the description](https://github.com/spring-projects/spring-boot/blame/18ccbf031ae85fe0aec2a8ba0577a64efae1c6da/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using-spring-boot.adoc#L398) to describe `@SpringBootApplication` rather than `@EnableAutoConfiguration`
- Update [the example](https://github.com/spring-projects/spring-boot/blame/18ccbf031ae85fe0aec2a8ba0577a64efae1c6da/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using-spring-boot.adoc#L407) to use `@SpringBootApplication` rather than `@EnableAutoConfiguration`
- Add a sentence before [this one](https://github.com/spring-projects/spring-boot/blame/18ccbf031ae85fe0aec2a8ba0577a64efae1c6da/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using-spring-boot.adoc#L412) that lets the user know that if they are using `@EnableAutoConfiguration` rather than `@SpringBootApplication` it has an `exclude` attribute that they can use for the same purpose.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by protyay** [comment]
Hello, I would like to work on this issue. Can you please guide me ?

**Comment by wilkinsona** [comment]
Excellent. Thanks very much, @protyay. Please let us know what guidance you need in addition to the steps described above, and we'll do our best to help.

**Comment by protyay** [comment]
Thanks. 
I'll begin by setting up the project locally and will ask the follow-up questions, if any.

**Comment by vsethi13** [comment]
Ahh.. I missed it by 30 mins :)

**Comment by protyay** [comment]
Hello @wilkinsona , I've made the suggested changes and the updated HTML snippet is attached. 
I've also signed the contributor license. 

I need some help regarding the workflow for submitting the PR. ( Fork/Clone/Commit/Push/Submit PR?)

**Snippet**
![image](https://user-images.githubusercontent.com/8929811/72461756-a69c5580-37f5-11ea-90f0-61a8adbdae30.png)

**Comment by wilkinsona** [comment]
Thanks for the update, @protyay. It's looking good.

I can see that [you already have a fork](https://github.com/protyay/spring-boot) so the next step is to commit and push the changes that you have made. Once that's done you can open a pull request. GitHub's help documentation on [collaborating with issues and pull requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests) provides a good overview of what needs to be done, particularly the section on [proposing changes with a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests) and [creating a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

Please have a read of the links above and then if you have any specific questions please ask here and we'll do our best to answer them.

**Comment by 2wkamd** [comment]
Hi @protyay thanks for firs-time-only issue
I start contributing can you check i did the task correct?

**Comment by 2wkamd** [comment]
Hi @wilkinsona thanks for firs-time-only issue
I start contributing  Can you check if I did the task correct?

**Comment by wilkinsona** [comment]
@2wkamd Thank you, but as indicated above, @protyay has already claimed this one and is working on it. If they need to drop out for some reason @vsethi13 is next in line.

**Comment by 2wkamd** [comment]
OK, I think I misunderstood the process to claim issue.
Thanks @wilkinsona.

**Comment by wilkinsona** [comment]
Thanks very much, @protyay. Closing in favour of #19855.

**Comment by protyay** [comment]
Great. 
I'm looking to work on other issues.
Is there a specific rules to assign tasks to yourself ?  @wilkinsona

**Comment by snicoll** [comment]
@protyay issues that are assigned are not open for contributions as work may have already started, leading to duplicate efforts. If you are interested by an unassigned issue and want to work on it, just add a comment (alongside any question you may have) and we'll assign `spring-contributor`, as we did in this very issue.
