### ISSUE TITLE
Review Cassandra's timeout options

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19673]
Follow-up of #18621

The upgrade to v4 changes some of the timeout options, i.e. 

* I am not sure what `connectTimeout` is now. We found `CONNECTION_INIT_QUERY_TIMEOUT` but I don't think this is equivalent
* `readTimeout` was mapped to `request-timeout`. Again, not sure this is accurate
* I didn't find a replacement for `poolTimeout`

**Comment by adutra** [comment]
Hi, driver 4 introduces the notion of global timeouts. This means that the value you set for `datastax-java-driver.basic.request.timeout` is really the maximum time that the driver is allowed to spend on a query. In driver 3, the timeout was per request-response cycle, thus making it difficult for the user to reason about SLAs.

In other words there is not exact equivalent for `readTimeout` in driver 4.  `request-timeout` is the closest option, but with the caveat that it is now meant as the total amount of time to spend on a query, not on a single request.

Concerning `connectTimeout`, the best equivalent is indeed `init-query-timeout`. That said driver 4.0 has more fine-grained timeouts, search for “timeout” in the [reference configuration](https://docs.datastax.com/en/developer/java-driver/4.4/manual/core/configuration/reference/).
