### ISSUE TITLE
Allow to configure Cassandra's request throttling

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19674]
Follow-up of #18621

The `maxQueueSize` property in Spring Boot 2.2 has been mapped to `REQUEST_THROTTLER_MAX_QUEUE_SIZE`. There is a case there to improve the support around request throttling by creating a dedicated namespace and offer additional configuration options.

**Comment by adutra** [comment]
Request throttling in driver 4.0 has indeed a few more configurable options, see [here](https://docs.datastax.com/en/developer/java-driver/4.4/manual/core/throttling/) for details.
