### ISSUE TITLE
Enforce no snapshots during a release

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19700]
I think our older branches have enforcer rules to make sure that we don't accidentally ship with SNAPSHOT dependencies. We should add something similar to Gradle.

**Comment by wilkinsona** [comment]
Once we have no snapshot dependencies, we should remove the snapshot repository declarations from the build.

**Comment by wilkinsona** [comment]
Better than that, we can configure the repositories based on what we're building.
