### ISSUE TITLE
Output buildscan URL from CI to Slack

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19703]
It would be nice if we could record the Gradle buildscan URL and include it in the Slack message.

**Comment by wilkinsona** [comment]
We can write the scan URL to a file with something like this:

```
gradleEnterprise {
    buildScan {
        buildScanPublished { PublishedBuildScan scan ->
            file("build-scan-url.txt") << "${scan.buildScanUri}\n"
        }
    }
}
```

Hopefully we can then read the URL from the file and include it in the Slack alert.
