### ISSUE TITLE
Support generation and loading of layered jars

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19767]
As part of #19697 we need to update the `Repackager` to generate layered JARs and update the `JarLauncher` to support them.

**Comment by wilkinsona** [comment]
Re-opening as I think we need some equivalent Gradle changes and I don't want them to fall through the cracks.

**Comment by philwebb** [comment]
We'll handle the Gradle work in #19792

**Comment by philwebb** [comment]
I messed up and managed to not actually write the index file.
