### ISSUE TITLE
Provide an implicit layer for buildpack contributions

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19771]
We should define a special layer name that's reserved for external contributions to an unpacked jar. I think the current code will already support any additional layer dropped into `BOOT-INF/layers` but it might be better to have a specific folder (e.g. `BOOT-INF/ext`) or a reserved layer name.

**Comment by snicoll** [comment]
A bit curious about that one and how you intend to handle layers ordering.

**Comment by snicoll** [comment]
We discussed it today and weren't sure what the original intention is. @philwebb can you please clarify?

**Comment by wilkinsona** [comment]
We can't think of a reason for the application to express an opinion about the layers used by the buildpack to add things to the classpath. The buildpack can make the decision while building the image, as it currently does with the launcher classes, for example.

**Comment by philwebb** [comment]
The original intent was just to reserve a folder name for the buildpack to use. I was worried that the user might accidentally pick the same name as the buildpack wanted and the entire thing would break. Now that we've reverted to the standard layout, there's no need for this.
