### ISSUE TITLE
Asciidoctor warnings due to javadoc conversion

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19785]
```
> Task :spring-boot-project:spring-boot-docs:asciidoctorPdf
Failed to parse formatted text: Whether to disable the escaping of HTML characters such as '<', '>', etc.
Failed to parse formatted text: Whether to disable the escaping of HTML characters such as '<', '>', etc.
Failed to parse formatted text: JNDI location of the datasource. Class, url, username & password are ignored when set.
Failed to parse formatted text: JNDI location of the datasource. Class, url, username & password are ignored when set.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.
```

I think this is due to our use if `<` and `>` in some of the configuration properties javadoc. We might want to escape those then update the converter code to deal with them. We'll also need to update the annotation processor that generates JSON.

**Comment by snicoll** [comment]
>  We'll also need to update the annotation processor that generates JSON.

I don't think these needs escaping as it's part of the description that's already a `String`.

**Comment by philwebb** [comment]
What I meant was we have comments like this in `ServerProperties`:

```java
/**
 * Comma-separated list of additional unencoded characters that should be allowed
 * in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
 */
```

Those cause javadoc warnings because `<` should be written as `&lt;`. We've generally tried to avoid javadoc specific markup in the configuration properties but I think these are different.

If we replaced those chars, I don't know what the impact would be on the JSON generation.

**Comment by wilkinsona** [comment]
They're Asciidoctor warnings rather than javadoc warnings, aren't they? I think those [above](https://github.com/spring-projects/spring-boot/issues/19785#issue-551236422) are from Asciidoctor's PDF generation. There aren't any warnings from the HTML generation, but it [sounds like it might be bad too](https://github.com/asciidoctor/asciidoctor-pdf/issues/875).

**Comment by philwebb** [comment]
I thought I'd seen IDE errors as well, but now I'm not so sure.

**Comment by dreis2211** [comment]
With the asciidoctor gradle plugin on version 3.0.0 this starts to actually fail. I've opened https://github.com/spring-projects/spring-boot/pull/19953 that addresses the upgrade and attempts to fix the issues above.

**Comment by wilkinsona** [comment]
Superseded by #19953.
