### ISSUE TITLE
Revise documentation that mentions Gradle "compile" configuration 

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#19794]
Hi,

afaik `compile` has been deprecated in favor of using `api` or `implementation`. In some places in the documentation the old approach is still mentioned: 
```
dependencies {
	compile("org.springframework.boot:spring-boot-starter-actuator")
}
```

I specifically didn't open a PR directly, because I wanted to discuss first if we should stick to `api` or `implementation` here. `api` would be closer to the old approach, but `implementation` is generally preferable. What do you think?

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. I think we should use `implementation`. It's always right for a module that nothing else depends on. And it's a good starting point for a module with dependents as it will encourage people to think about what dependencies they want those dependents to receive transitively. They can then use the Java library plugin and `api` as appropriate.

**Comment by wilkinsona** [comment]
Closing in favour of #19797.
