### ISSUE TITLE
Update dependency management to use Infinispan BOM

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#19791]
We should consider using `infinispan-bom` instead of listing Infinispan modules explicitly, considering the large number of Inifinispan modules Spring Boot manages. 

The [current BOM as of `10.1.0.Final`](https://search.maven.org/artifact/org.infinispan/infinispan-bom/10.1.0.Final/pom) includes dependency management for non-Infinispan artifacts (see [ISPN-11115](https://issues.redhat.com/browse/ISPN-11115)) and includes several modules that may not be necessary.

**Comment by snicoll** [comment]
The issue has been fixed so all we need is a release. Maybe we could wait for `10.1.1.Final` ?

**Comment by scottfrederick** [comment]
The `10.1.0.Final` BOM includes several modules that Boot doesn't currently manage, many with the comment `<!-- TODO should be here? -->`. Some appear to be test and demo/sample modules.

**Comment by dreis2211** [comment]
Hi guys,

I checked this before and spring-boot currently manages the following modules, that don't seem to be included in the BOM (explicitly):
- infinispan-jcache-commons
- infinispan-persistence-cli
- infinispan-tree

You probably want to check that out for yourself.

**Comment by scottfrederick** [comment]
`infinispan-persistence-cli` and `infinispan-tree` have been removed for `2.3.x` as part of the upgrade to `10.1.0.Final` (those modules don't have versions published for that release). `infinispan-jcache-commons` is a transitive dependency of the other two `infinispan-jcache-*` modules that Spring Boot does list, so that might just be an omission from the Infinispan BOM. 

I don't think we'd want to remove modules in a Boot maintenance release.

**Comment by dreis2211** [comment]
> `infinispan-persistence-cli` and `infinispan-tree` have been removed for `2.3.x`

I was wondering if I missed something and just noticed that there is a pending PR still #19790

**Comment by wilkinsona** [comment]
> `infinispan-jcache-commons` is a transitive dependency of the other two `infinispan-jcache-*` modules that Spring Boot does list, so that might just be an omission from the Infinispan BOM.

That sounds like a bug in their bom to me too.

**Comment by snicoll** [comment]
> That sounds like a bug in their bom to me too.

Agreed. I've created [ISPN-11202](https://issues.redhat.com/browse/ISPN-11202)

**Comment by snicoll** [comment]
I've decided to use the bom and add a manual entry for  `infinispan-jcache-commons`. Let's repurpose this issue to remove it once the issue I've created is fixed.

**Comment by snicoll** [comment]
This has been superseded by #22286

**Comment by snicoll** [comment]
Reopening as the BOM has yet another issue I forgot about, see https://github.com/spring-projects/spring-boot/issues/22286#issuecomment-656078277 and https://issues.redhat.com/browse/ISPN-11202

**Comment by snicoll** [comment]
So I've tried to reproduce the issue and I am unable to so I suggest that we keep this for now. We can always reconsider if someone manages to trigger that warning again.
