### ISSUE TITLE
Remove spring-boot-starter-cloud-connectors 

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#19798]
`spring-boot-starter-cloud-connectors` was [deprecated in Spring Boot `2.2.0`](https://github.com/spring-projects/spring-boot/issues/17877). We should consider removing it in `2.3.0`.

**Comment by wilkinsona** [comment]
+1 for removing it in 2.3.

**Comment by philwebb** [comment]
Lets do it. We can even try to get it into M1 if there's time.
