### ISSUE TITLE
Cassandra integration tests fail intermittently

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19802]
This failure is from `hasRecreateSchemaActionSet`:

```
Could not reach any contact point, make sure you've provided valid addresses (showing first 1, use getErrors() for more: Node(endPoint=/172.17.0.1:32832, hostId=null, hashCode=401ca295): com.datastax.oss.driver.api.core.DriverTimeoutException: [s0|control|id: 0x97060aa4, L:/172.17.0.1:54734 - R:/172.17.0.1:32832] init query OPTIONS: timed out after 500 ms)
```

It looks like we could do with increasing a timeout somewhere. 500ms doesn't appear to be enough time for a response to be received reliably.

**Comment by snicoll** [comment]
@mbhave I don't understand the proposed change as `advanced.connection.init-query-timeout` is already mapped from the [`connection-timeout` property](https://github.com/spring-projects/spring-boot/blob/84ea3d359b2c69e8e3920b6fe0e6a811889bb5dc/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.java#L136-L137). It looks like changing the already existing property should do it.

**Comment by snicoll** [comment]
I've validated a value without unit is mapped to `ms`. The previous timeout was 10s. However, this test is creating a keyspace upfront and that change of yours make sure that operation uses the 1s timeout. I've now adapted the test to apply timeouts on both operations. I wish I could reuse the same config but unfortunately, the keyspace creation has to be created before the `CqlSession` initializes itself so creating a session without the keyspace seems the only solution.

**Comment by snicoll** [comment]
I discussed this a bit more with @mbhave and we concluded that that change wasn't ideal either. That discussion led me to another proposal where we create the `CqlSession` ourselves, intializing the keyspace if necessary.

This also covers more ground for that particular integration test, see b6c5c3a

**Comment by adutra** [comment]
Just a heads up that since driver 4.8.0, the timeout for init queries was raised to 5 seconds, see [JAVA-2841](https://datastax-oss.atlassian.net/browse/JAVA-2841). This should hopefully make integration tests much more reliable.

**Comment by snicoll** [comment]
Thanks for the heads up @adutra.
