### ISSUE TITLE
Microservice by default compressing in gzip format

### ISSUE THREAD

**Issue by dineshv1234567** [spring-projects/spring-boot#19818]
**Problem Statement**: Microservice is by default compressing in gzip format in response when Accept-Encoding is not sent in the header.
**Spring boot version used**: 2.1.7.RELEASE
**Code**:
I added the following in application.properties:
server.compression.enabled=true
**Cases:**
Test case 1: 
Request with a header:- Accept-Encoding: gzip
Response in gzip _(Works fine)_
Test case 2: 
Request with a header:- Accept-Encoding: xyz
Response not in gzip _(Works fine)_
Test case 3: 
Request with a header:- Accept-Encoding: <null>
Response not in gzip _(Works fine)_
Test case 4: 
Request with empty header
Response in gzip _(Doesn't Work fine)_
It should return response in normal, but not in gzip encoding

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
