### ISSUE TITLE
Write classpath index file from Gradle plugin

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19847]
See #9128 for details. We need an update to the Gradle plugin to support this.

**Comment by wilkinsona** [comment]
We need to do this for war files as well.

**Comment by wilkinsona** [comment]
Maybe not. Only the`Jar` layout is a `RepackagingLayout` on the Maven side of things. Exploding a war has the same problem as exploding a jar so it may be something that we want to support in the future.
