### ISSUE TITLE
Wrapped Jolokia AgentServlet  should handle OPTIONS request

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#1987]
[Jolokia has it's own mechanism for serving CORS-Headers](http://www.jolokia.org/reference/html/security.html). Therefore the AgentServlet must handle the OPTIONS-request itself. In order to do this the DispatcherServlet must be configured with dispatchOptionsRequest = true and the ServletWrappingController for the AgentServlet must include OPTIONS in the supportedMethods.

**Comment by wilkinsona** [comment]
The changes made in 57a51ed will be superseded by those that address #2936
