### ISSUE TITLE
BootBuildImageIntegrationTests do not run on JDK13

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#19879]
Hi,

the new `BootBuildImageIntegrationTests` do not seem to run on JDK 13. This is what I get from running locally:

```
Error: LinkageError occurred while loading main class example.Main

	java.lang.UnsupportedClassVersionError: example/Main has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Maybe you have some more insights on this one. I would disable them for now by skipping them on JDK13. Should I provide a PR for the time being?

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, Christoph. This should hopefully be fixed by https://github.com/spring-projects/spring-boot/commit/1d396abec5131baca2c30555b8c86b76070ea149. I'll re-open if that proves not to be the case.

**Comment by dreis2211** [comment]
I'm having a timing issue lately. Every time I report something, some minutes later it's fixed already. 😆 Sorry for the noise.

**Comment by wilkinsona** [comment]
No problem at all. Thanks for helping out.
