### ISSUE TITLE
Upgrade to Couchbase Java SDK 3

### ISSUE THREAD

**Issue by daschl** [spring-projects/spring-boot#19893]
Hi spring-boot team,

after a chat with @mp911de  he suggested I open a ticket here to give everyone a heads up. We just released Couchbase Java 3.0 and are in the process of moving spring-data-couchbase over to it, trying to make the Neumann M3 release train. As the version number suggests this is a breaking release so I expect more changes than usual.

Since I know this has a direct impact on boot as well I wanted to start this ticket and also in parallel start updating boot where needed (future PRs will reference this).

I'll start the porting effort and ping again once I made progress.

**Comment by daschl** [comment]
Migration is still in progress. I saw that boot currently depends on `couchbase-spring-cache` as well. In the process of updating `spring-data-couchbase` we've moved the caching implementation into it, similar to redis and others. This means we don't need to track an individual dependency in boot.

I'll share more details once we got the initial push to master done for SDC.

**Comment by daschl** [comment]
Okay with https://github.com/spring-projects/spring-data-couchbase/commit/c3e66d74a3b692a0abea7735c342d00ac332147b we merged it into master! We are still working through things, but the config section should be mostly done (of course if we need to change anything, let me know). if anything, hopefully it got simpler!

**Comment by snicoll** [comment]
@daschl thanks for the heads-up. Do you still intend to update Spring Boot as well? I am asking as there are quite a lot of changes and if you don't, a migration guide of some sort would be super helpful to us.

**Comment by daschl** [comment]
@snicoll I can give it a shot at least, but I'll probably need some feedback cycles. When is the next release planned until it needs to be solid?

**Comment by snicoll** [comment]
Milestones [are available](https://github.com/spring-projects/spring-boot/milestones) and we do our best to keep them current. The next milestone is mid-March. Whenever you ship `spring-data-couchbase` with a `Neumann` milestone, we must adapt here. So the question is back to you, really. 

I understood in the original description that you'd "update boot in parallel". That's why I am asking as if we have to make it our next milestone, we don't have much time to understand the changes and adapt here. Other data stores took two solid days so I'd like to know asap. 

Thanks!

**Comment by daschl** [comment]
@snicoll okay thanks - I'll make it a priority and let you know quickly if I get stuck

**Comment by dreis2211** [comment]
I can't build the project currently because of the changes in spring-data-couchbase. Are you guys aware? :)

**Comment by snicoll** [comment]
Yes, we're on a team meeting but we have a workaround locally. We'll push that soon.

**Comment by snicoll** [comment]
This is currently blocked by [DATACOUCH-509](https://jira.spring.io/browse/DATACOUCH-509).

**Comment by snicoll** [comment]
And now by [DATACOUCH-510](https://jira.spring.io/projects/DATACOUCH/issues/DATACOUCH-510)
