### ISSUE TITLE
Provide a way to inject parsed application arguments

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1990]
From [StackOverflow](http://stackoverflow.com/questions/27059936/spring-boot-commandlinerunner-filter-option-argument):

> Considering a Spring Boot `CommandLineRunner` Application, I would like to know how to filter the "switch" options passed to Spring Boot as externalized configuration.

> For example, with:

>     @Component
    public class FileProcessingCommandLine implements CommandLineRunner {
        @Override
        public void run(String... strings) throws Exception {
            for (String filename: strings) {
               File file = new File(filename);
               service.doSomething(file);
            }
        }
    }

> I can call ` java -jar myJar.jar /tmp/file1 /tmp/file2` and the service will be called for both files.

> But if I add a Spring parameter, like ` java -jar myJar.jar /tmp/file1 /tmp/file2 --spring.config.name=myproject ` then the configuration name is updated (right!) but the service is also called for file `./--spring.config.name=myproject` which of course doesn't exist.

> I know I can filter manually on the filename with something like

>     if (!filename.startsWith("--")) ...

> But as all of this components came from Spring, I wonder if there is not a option somewhere to let it manage it, and to ensure the `strings` parameter passed to the `run` method will not contain at all the properties options already parsed at the Application level.

**Comment by abatkin** [comment]
Alternatively, expose the `CommandLinePropertySource` as a bean *and* make `getNonOptionArgs()` public.

Or even better, somehow make the nonOptionArgs an injectable bean and then `CommandLineRunner` isn't even needed anymore.

**Comment by MadaraUchiha** [comment]
Bump, can this be considered?

**Comment by philwebb** [comment]
Does injecting the `ConfigurableEnvironment` then calling `environment.getProperty(CommandLinePropertySource.DEFAULT_NON_OPTION_ARGS_PROPERTY_NAME)` work for for you?

**Comment by philwebb** [comment]
Although I also like the idea of a `NonOptionArgs` bean.

**Comment by abatkin** [comment]
To me, either `getProperty(...)` or a `NonOptionArgs` bean would be fine (anything to make it accessible) but the latter is definitely preferred, and I think that's the more *Springy* way.

**Comment by philwebb** [comment]
I've added a new `ApplicationArguments` bean which you can inject. It provides access to the option and non-option arguments. There is also a new `ApplicationRunner` interface which works in a similar way to `CommandLineRunner` but provides `ApplicationArguments` rather than a `String[]`.

Let me know if anything is missing or if the approach doesn't work.

**Comment by abatkin** [comment]
That looks perfect!

**Comment by itzg** [comment]
:+1: IMHO this is a major feature that should be advertised in 1.3.0. This is the kind of goodness that continues to make Spring Boot the last application framework I'll ever need to use. Thanks!

**Comment by snicoll** [comment]
Thanks for the kind words! `M2` is around the corner and the release notes will be reviewed at the same time.

**Comment by philwebb** [comment]
Reopening to fix javadoc https://github.com/spring-projects/spring-boot/commit/582239b03bdf8f041f9e13bb2fa0628081e51860#commitcomment-12083844
