### ISSUE TITLE
Spring Boot CLI adds classes from current directory to the classpath on Unix-like platforms

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#19910]
Running `spring` in a directory which had another Spring Boot fat jar unzipped, resulted in an error because it was using the `Launcher` from the unzipped `org` directory.

**Comment by gaurav-91** [comment]
Hi,
I would like to work on this request.

Thanks

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/commit/0d583deb27a27a7ed15b5a2da3b27865a01a33f3 added `.` to the `CLASSPATH`, although only to the bash script. As far as I can, the corresponding update was never made to the .bat script. I think we can safely remove `.` from the classpath.
