### ISSUE TITLE
Non-parseable POM error while building Spring Boot 2.2.4

### ISSUE THREAD

**Issue by rajibhalder** [spring-projects/spring-boot#19935]
JDK Version: 1.8.0_231
Maven: 3.6.1
Spring Boot: 2.2.4
Eclipse: Version: 2019-09 R (4.13.0)
             Build id: 20190917-1200

Hi,

After generating a spring boot project (Version 2.2.4) from https://start.spring.io/ while trying to build using eclipse, getting below error:

> [INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\Users\rajib\.m2\repository\org\springframework\boot\spring-boot-starter-parent\2.2.4.RELEASE\spring-boot-starter-parent-2.2.4.RELEASE.pom: Expected root element 'project' but found 'html' (position: START_TAG seen <!DOCTYPE html>\n<html xml:lang="en" lang="en">... @2:31)  @ C:\Users\rajib\.m2\repository\org\springframework\boot\spring-boot-starter-parent\2.2.4.RELEASE\spring-boot-starter-parent-2.2.4.RELEASE.pom, line 2, column 31
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:demo:0.0.1-SNAPSHOT (C:\My_Workplace\Warehouse\demo\pom.xml) has 1 error
[ERROR]     Non-parseable POM C:\Users\rajib\.m2\repository\org\springframework\boot\spring-boot-starter-parent\2.2.4.RELEASE\spring-boot-starter-parent-2.2.4.RELEASE.pom: Expected root element 'project' but found 'html' (position: START_TAG seen <!DOCTYPE html>\n<html xml:lang="en" lang="en">... @2:31)  @ C:\Users\rajib\.m2\repository\org\springframework\boot\spring-boot-starter-parent\2.2.4.RELEASE\spring-boot-starter-parent-2.2.4.RELEASE.pom, line 2, column 31 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

>

**Comment by wilkinsona** [comment]
You appear to have a problem with a proxy or your network configuration that has resulted in the pom having HTML content. Unfortunately that is out of Spring Boot’s control so there’s nothing we can do to help you here. I’d recommend checking your Maven configuration and network settings.

**Comment by gobozov** [comment]
I just got similar issue, VPN wan't connected properly and somehow I got html content in my dependency poms. Ran `mvn dependency:purge-local-repository` to purge local dependencies and then 'mvn clean install'
