### ISSUE TITLE
Execution-specific build image configuration examples in Maven plugin docs can be misleading

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#19946]
When the configuration is declared on an execution rather than on the plugin as a whole, it only affects that specific execution. Crucially, it means that it you run `./mvnw spring-boot:build-image` the configuration has no effect. We should perhaps show the configuration being applied to the whole plugin, or at least document the subtleties of Maven's behaviour here.

**Comment by snicoll** [comment]
I think this is a template I've used based on our `repackage` execution of the `repackage` goal in our parent pom. Given we have no such constraint, we should really document things differently. I'll update the doc to that effect. Thanks for raising it!
