### ISSUE TITLE
Create a smoke test that builds an image

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19940]
We need a smoke tests that creates an image from a project. Ideally a Maven and Gradle equivalent would be nice. 

The problem is that such goal should only be invoked if the docker daemon is available. And we need to  clean-up the image the build has generated. That last part can easily be done as part of an integration test, I don't know about the first.

**Comment by wilkinsona** [comment]
We have one for the Gradle plugin: [BootBuildImaheIntegrationTests.java](https://github.com/spring-projects/spring-boot/blob/0bd0b2a6c06a1977a2b0295113f660f8583f2df2/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/tasks/bundling/BootBuildImageIntegrationTests.java).

**Comment by snicoll** [comment]
We do have one for the Maven plugin as well but none of those break without the fix for #19908. Thinking of it a bit more, that sounds a bit odd so I'll double check again.

**Comment by snicoll** [comment]
Something went wrong as the smoke tests we have are indeed failing the build without the fix. I can confirm they are covering the fix for Windows.
