### ISSUE TITLE
Add example of default Cloud Native Buildpacks Builder

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19967]
The build plugins use the `cloudfoundry/cnb:0.0.43-bionic` Builder by default, which bundles the OpenJDK Buildpack. The OpenJDK Buildpack exposes a number of options as env variables, see https://github.com/cloudfoundry/openjdk-cnb/blob/master/README.md.

A couple examples demonstrating the use of the default  builder with the OpenJDK Buildpack would be interesting to help users getting started.

**Comment by scottfrederick** [comment]
The default builder includes [several buildpacks](https://github.com/cloudfoundry/java-cnb) that might influence how a Boot app gets configured in the resulting container. We should look at these other Java-related buildpacks as well to see if any of them have env variables that we might want to document (for example https://github.com/cloudfoundry/debug-cnb/blob/master/README.md).

**Comment by snicoll** [comment]
I am starting to wonder if this is a good idea considering that some options have changed quite a lot recently and keeping them in sync on our side is challenging (that can be a problem for users on its own as well). Flagging for team attention to discuss this again.

**Comment by nebhale** [comment]
I agree that Boot should probably kick out to Paketo Java Buildpack documentation that contains an up-to-date collection of possible configuration options.  We'll be working on that over the next couple of weeks.

Also, it should be noted that when staging happens, all available configuration options are printed as part of the logs.
