### ISSUE TITLE
Springboot 2.3.0.M1 

### ISSUE THREAD

**Issue by TLiese** [spring-projects/spring-boot#19980]
Springboot 2.3.0.M1 is not in maven therefor testing the current code base against it is unnesasary difficult.

**Comment by spencergibb** [comment]
We don't publish milestones to maven Central but to https://repo.spring.io/milestone

**Comment by wilkinsona** [comment]
Thanks, @spencergibb. @TLiese if you generate a project on start.spring.io and select 2.3.0.M1, the  build (Maven or Gradle) will be automatically configured with the required repository.
