### ISSUE TITLE
Document spring-boot.run.arguments behaviour with multiple arguments

### ISSUE THREAD

**Issue by ebussieres** [spring-projects/spring-boot#19998]
Since version 2.2.3.RELEASE, I have a regression when using command line arguments from Maven plugin.

When I use the maven plugin and pass multiple arguments, the args array contains only one value. For example, if I use the following command line, the array will containe only one value.

```
mvn spring-boot:run -Dspring-boot.run.arguments="param1,param2"
```

It was working with version 2.2.2.RELEASE

An example can be found here : https://github.com/ebussieres/spring-boot-run-bug

**Comment by snicoll** [comment]
Thanks for the report. That's an effect of fixing a bug that harmonize how such an argument should be processed on the command-line, see #18711. 

Arguments on the command line have to be separated by a space (to allow commas to be used in the value itself).

```
mvn spring-boot:run -Dspring-boot.run.arguments="param1 param2"
```

This is documented but for some reasons I can't see that being reflected on the generated web site so we'll use this issue to improve that.

**Comment by ebussieres** [comment]
And if my parameter contains space. is it a workaround ?

**Comment by snicoll** [comment]
It's also specified in the doc that's supposed to show up. You need to quote it. 

What I meant by harmonizing is that we now use the same mechanism as any other Maven plugin does so there are plenty of resources online about that stuff.

**Comment by glmars** [comment]
@snicoll Unfortunately, these breaking changes still aren't documented in the [Spring Boot 2.2 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes) :grimacing:
