### ISSUE TITLE
Exposing Scheduled Jobs as REST endpoints to allow adhoc executions

### ISSUE THREAD

**Issue by DhavalShewale** [spring-projects/spring-boot#19996]
Currently Scheduled Jobs are triggered only as per defined schedule, however there is always a need to schedule these jobs on adhoc basis.

These jobs can be exposed as REST endpoints, may be as child links under `<context-root>/scheduled` url.

Users can use these URLs to invoke the jobs on adhoc basis. An application property can be used to enable / disable this feature.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This is a duplicate of part of #17585.
