### ISSUE TITLE
Spring boot Profiles Active Websphere 9.0.0.11

### ISSUE THREAD

**Issue by daviMustafa** [spring-projects/spring-boot#20018]
Spring Boot version: 2.1.8.RELEASE

When developing a spring boot application. Most of times we just put it on the given property with a value:

**spring.profiles.active = myProfile**

But sometimes we don't. While a standalone spring boot application or when running on a wildfly, when this property is not set, the default property value will be **"default"**. 

**_No active profile set, falling back to default profiles: default_**

When running on a Websphere Application Server (tested on version 9.0.0.11), the default value will just be **"@spring.profile.active@"**.

**_The following profiles are active: @spring.profile.active@_**

Shouldn't it be just like standalone and wildfly?

Thanks

**Comment by snicoll** [comment]
> When running on a Websphere Application Server (tested on version 9.0.0.11), the default value will just be "@spring.profile.active@".

Something else is setting that property to `@spring.profile.active@` (looks like some value was not replaced by Maven). There is nothing in Spring Boot that sets this property to such value. Can you please review your arrangement? If you have a place where you set that property, you may want to double check it's not set to this value by your build when you package the app for WAS.

**Comment by daviMustafa** [comment]
I'll look forward but when I compiled the package I wasn't even setting this property. I just left it application.properties without it.

**Comment by daviMustafa** [comment]
Ok, fixed. It was a problem on my Websphere picking up old configurations when it was suppose to pick up the new ones.

**Comment by snicoll** [comment]
Thanks for letting us know.
