### ISSUE TITLE
Unlike all other Maven properties, spring-boot.run.arguments on the command line takes precedence over the pom

### ISSUE THREAD

**Issue by rawfg** [spring-projects/spring-boot#20024]
**Description:** the `spring-boot.run.jvmArguments` does not take precedence over the `< systemPropertyVariables>` map when there is a `<jvmArguments>` section defined for the `spring-boot-maven-plugin`.

**Documented behavior:**
According to the https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-system-properties.html when the `spring-boot.run.jvmArguments` parameter is provided for the `spring-boot:run` command the parameter takes precedence and overwrites the system properties defined within the `<systemPropertyVariables>` XML configuration. I would expect that the presence of the `jvmArguments` section does not influence the documented behavior.

**Steps to reproduce:**
There is a sample application which demonstrates non-documented (faulty?) behavior located at https://github.com/rawfg/maven-jvmargs.

1. The sample application prints the system properties starting with the `xyz` and by default there are [two system properties](https://github.com/rawfg/maven-jvmargs/blob/master/pom.xml#L45-L50) configured: one comes from the `<jvmArguments>` section and the other one comes from the `< systemPropertyVariables>` section.

2. When the application is run from the command line via the command:
```bash
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dxyz.MavenSystemProperty='cmd-system-property'" 
``` 
the output is (system properties configured in the pom.xml):
```bash
xyz.MavenSystemProperty=maven-system-property
xyz.MavenJvmProperty=maven-jvm-property
```

3. When the [`<jvmArguments>` section](https://github.com/rawfg/maven-jvmargs/blob/master/pom.xml#L46) is commented out the application behaves as it was documented, so running the command:
```bash
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dxyz.MavenSystemProperty='cmd-system-property'" 
```
results in the output:
```bash
xyz.MavenSystemProperty=cmd-system-property
```
4. I tested it with the Spring Boot version `2.2.4` but I've downgraded to the `2.1.7` version and I observed the same outcome.

**Expected behavior:**
- `-Dspring-boot.run.jvmArguments` always works as documented (step 3) or
- the exception is documented in the https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-system-properties.html

**Comment by scottfrederick** [comment]
A value provided by `<jvmArguments>` in the POM configuration takes precedence over a value provided by the `spring-boot.run.jvmArguments` system property.  So in the case of your sample app as provided without changes, the `-Dspring-boot.run.jvmArguments=-Dxyz.MavenSystemProperty=cmd-system-property` will be ignored. When the `<jvmArguments>` POM configuration is removed, then the `spring-boot.run.jvmArguments` value is used. 

> Expected behavior:
> * -Dspring-boot.run.jvmArguments always works as documented (step 3) or
> * the exception is documented in the https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-system-properties.html

This isn't so much an exception as it is an order of precedence.  The documentation states that `jvmArguments` takes precedence over `<systemPropertyVariables>`, which is always the case. What isn't documented is which manner of providing `jvmArguments` takes precedence. A quick test shows that the order of precedence isn't consistent between configuration properties like `jvmArguments` and `arguments`. 

I've marked this for team attention so we can discuss the proper order of precedence between POM configuration and `spring-boot.run` system properties, talk about adding tests to confirm the proper behavior, and document it.

**Comment by wilkinsona** [comment]
For consistency with configuration precedence in other area of Spring Boot, I think that system properties provided on the command line should take precedence over something that's hardcoded in the pom.xml file.

**Comment by scottfrederick** [comment]
Maven documents the fact that Mojo `@Parameter`s can be set via POM configuration or from system properties (provided the `@Parameter` has a `property` attribute) but I can't find the order of precedence documented anywhere. However, testing shows that POM configuration takes precedence over system properties. 

`spring-boot.run.arguments` is the exception to the rule because Boot's Mojo reverses the default Maven order by [declaring two separate parameters](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/AbstractRunMojo.java#L145-L159) and [resolving them explicitly](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/AbstractRunMojo.java#L320-L321).

**Comment by wilkinsona** [comment]
> However, testing shows that POM configuration takes precedence over system properties.

Just to make sure I've understood, that's the opposite of what would align with Boot's configuration precedence in other areas?

**Comment by scottfrederick** [comment]
> Just to make sure I've understood, that's the opposite of what would align with Boot's configuration precedence in other areas?

Yes, exactly the opposite.

**Comment by wilkinsona** [comment]
We're going to align with Maven's defaults.

**Comment by wilkinsona** [comment]
Re-opening so that we can investigate the test failures on Windows: https://ge.spring.io/s/m62r4fmeh6y6k/tests/failed.

**Comment by wilkinsona** [comment]
2.2.x is unaffected by the test failures.
