### ISSUE TITLE
Upgrade to Jetty 9.4.26.v20200117

### ISSUE THREAD

**Issue by oleborup** [spring-projects/spring-boot#20040]
The current version 9.4.25.v20191220 in 2.2.4 has the following bug: https://github.com/eclipse/jetty.project/issues/4461

We encountered the bug with 2.2.4 when enabling compression with `server.compression.enabled` and serving static content from the `resources/static` folder. Using Jersey as filter and `jersey.config.servlet.filter.staticContentRegex` for defining static content regex.

**Comment by wilkinsona** [comment]
Thanks, but, as mentioned in the issue template, we prefer people not to open issues for dependency upgrades. We have a semi-automated process that is run prior to each release that will open issues and make the necessary changes for each upgrade that is applicable to the version of Spring Boot being released. We will pick up the latest Jetty 9.4.x release in due course.
