### ISSUE TITLE
Link to Jetty request log documentation is broken

### ISSUE THREAD

**Issue by bcalmac** [spring-projects/spring-boot#20044]
In section [9.3.11. Configure Access Logging](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-accesslogs) of the reference documentation the following Jetty link is broken: https://www.eclipse.org/jetty/documentation/9.4.25.v20191220/configuring-jetty-request-logs.html

**Comment by dreis2211** [comment]
Unfortunately, Jetty seems to only publish the latest docs for a minor version. So 9.4.26.v20200117 is available, while previous ones are not.

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. That does indeed appear to be the case. It's unfortunate as it means that we can't link to a precise version of Jetty's documentation without the links being broken then next time they release. We could link to current, but those links will become inaccurate, and increasingly so over time. There's also the option of linking to 9.4.x but this points to snapshots so isn't ideal either.

I've opened a [Jetty issue](https://github.com/eclipse/jetty.project/issues/4546) to see if they could make an improvement on their side. Let's wait and see what they say before deciding what to do here.

**Comment by wilkinsona** [comment]
A change to how Jetty's documentation is published does not look likely. In the meantime we've addressed the problem by removing the unstable links to Jetty's documentation. I think that's about the best that we can do.
