### ISSUE TITLE
spring.ftl spring.messageArgs doesn't work properly in freemarker

### ISSUE THREAD

**Issue by ahmedGazieAbed** [spring-projects/spring-boot#20098]
In messages.properties I have this property:
`welcome.message=Welcome {0}. {1} {2}`
and in hello.ftl I try to parse this property as below:
`<#import "/spring.ftl" as spring/>`
`<@spring.message code="welcome.message" args="'Mr','Ahmed','Abed'"/>`
and the result is:
`Welcome {0}. {1} {2}`

I have make workaround in hello.ftl as below:
`${springMacroRequestContext.getMessage("welcome.message",['Mr','Ahmed','Abed'],"testtesttest",false)}`
and the result print correctly:
`Welcome Mr. Ahmed Abed`

Can you please take a look? thanks.

**Comment by mbhave** [comment]
```
<@spring.messageArgs code="welcome.message" args=["Mr", "A", "B"]/>
```

@ahmedGazieAbed The above worked for me. I don't think specifying it without the `[ ]` syntax works but if you think you've found a bug please raise it in the [Spring Framework](https://github.com/spring-projects/spring-framework/issues/) issues tracker.
