### ISSUE TITLE
RabbitTemplate dependency of autoconfigured RabbitMessagingTemplate with custom RabbitTemplate

### ISSUE THREAD

**Issue by bijukunjummen** [spring-projects/spring-boot#2011]
RabbitMessagingTemplate has a dependency on RabbitTemplate, now if I were to define my custom RabbitTemplate, this autoconfiguration fails as then there are two RabbitTemplates available. Can you please suggest a good workaround, this is the exception:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitMessagingTemplate' defined in class path resource [org/springframework/boot/autoconfigure/amqp/RabbitAutoConfiguration$MessagingTemplateConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.amqp.rabbit.core.RabbitTemplate]: : No qualifying bean of type [org.springframework.amqp.rabbit.core.RabbitTemplate] is defined: expected single matching bean but found 2: amqpTemplate,rubeExchangeTemplate; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.amqp.rabbit.core.RabbitTemplate] is defined: expected single matching bean but found 2: amqpTemplate,rubeExchangeTemplate
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:752)
```

Temporarily I have worked around this by defining my own RabbitMessageTemplate which prevents the autoconfigured one from being defined also.

**Comment by carlosdarienvizcaino** [comment]
Hey guys, 

If you wish to have 2 or more RabbitTemplate defined in your rabbit-config.xml file your could do the following:

<rabbit:template
        id="rabbitMessagingTemplate"
        connection-factory="connectionFactory"
        retry-template="retryTemplate" />
<rabbit:template
            id="template1"
            connection-factory="connectionFactory"
            retry-template="retryTemplate"
            message-converter="jsonMessageConverter"
            exchange="queue1"
            routing-key="key1"/>
    <rabbit:template
            id="template2"
            connection-factory="connectionFactory"
            retry-template="retryTemplate"
            message-converter="jsonMessageConverter"
            exchange="exchange2"
            routing-key="key2"/>

Now, Spring Boot knows which RabbitTemplate to pick first (rabbitMessagingTemplate). Notice, this template definition does not have any exchange and/or routing key, At least in my application I don't use rabbitMessaginTemplate at ALL.

**Comment by GovindRajuSavi** [comment]
spring.main.allow-bean-definition-overriding=true

This property help.?

**Comment by mbhave** [comment]
@GovindRajuSavi Please ask questions on [gitter](https://gitter.im/spring-projects/spring-boot) or StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
