### ISSUE TITLE
Unnecessary use of / in classpath:/db/changelog/db.changelog-master.yaml prevents Liquibase from identifying that a change set has already been applied when run from the command line

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20118]
Forward port of issue #19926 to 2.3.0.M2.

**Comment by Marax** [comment]
Hi, this change actually broke my application. I have to manually remove slash from all previous changes in DATABASECHANGELOG, otherwise it tries to install them all again.

**Comment by wilkinsona** [comment]
@Marax Thanks very much for trying out M2 and letting us know about the problem. We'll have to consider what to do for 2.3.0.M3. The workaround you have found (thanks for that too) is useful, but I'm not sure it's enough to make us feel comfortable about making this change.
