### ISSUE TITLE
Issues while using springboot-gradle-plugin with Eclipse

### ISSUE THREAD

**Issue by EspinolaAbel** [spring-projects/spring-boot#20110]
I'm having issues to use springboot-gradle-plugin with Eclipse.
I had created this stackoverflow post:

[https://stackoverflow.com/questions/60140145/springboot-gradle-plugin-not-working-with-eclipse](url)

Thanks

**Comment by snicoll** [comment]
Thanks but there is really no need to create a duplicate. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. You link does not work so feel free to edit the description so it points to your existing question.

**Comment by EspinolaAbel** [comment]
I edited the link. Now is working. ¿can you give me the link of the duplicated issue you are talking about?.
Thanks

**Comment by snicoll** [comment]
@EspinolaAbel this very issue is a duplicate, as there is a StackOverflow question and I've indicated above we prefer not to use this issue tracker for questions. I had a look at the SO thread and there's nothing we can do here as it's an IDE usage problem.
