### ISSUE TITLE
Unnecessary use of / in classpath:/db/changelog/db.changelog-master.yaml prevents Liquibase from identifying that a change set has already been applied when run from the command line

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20117]
Forward port of issue #19926 to 2.2.5.

**Comment by wilkinsona** [comment]
Re-opening as we may need to revert this change. See https://github.com/spring-projects/spring-boot/pull/19926#issuecomment-586142069 for details.

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-boot/pull/19926#issuecomment-586172784
