### ISSUE TITLE
Document missing reference to DataSourceHealthIndicator

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20214]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
The [documentation that lists the available health indicators](https://docs.spring.io/spring-boot/docs/2.2.4.RELEASE/reference/html/production-ready-features.html#auto-configured-healthindicators) is missing an entry for `DataSourceHealthIndicator`. This is a regression as the entry is present [in the `2.1.x` version](https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/production-ready-endpoints.html#_auto_configured_healthindicators).

## Solution
The documentation should be updated to add an entry for the datasource health indicator. This should be done in `spring-boot-project/spring-boot-docs/src/docs/asciidoc/production-ready-features.adoc` and the entry should be added after the `DiskSpaceHealthIndicator` entry.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by hbellahc** [comment]
Hi
Can I take it ?

Thanks

**Comment by snicoll** [comment]
@hbellahc it's yours, thank you very much and let us know if you have questions (see the description above for details on how to get started).

**Comment by hbellahc** [comment]
@snicoll Just to be sure, my modification will be done on 2.2.x branch ?

**Comment by snicoll** [comment]
Thanks for asking. It doesn't have to. You can do it of `master` and we'll figure out.

**Comment by hbellahc** [comment]
@snicoll Thanks for you help, I just start a PR. 

Hope that the PR is OK and I stay there if need
:)

**Comment by snicoll** [comment]
Sweet, that was quick!

Closing in favour of PRR #20216
