### ISSUE TITLE
The configuration under the server in springboot can set cookie parameters, but it is two cookies after integrating jdbc storage

### ISSUE THREAD

**Issue by jidianzhixia** [spring-projects/spring-boot#20239]

**Comment by snicoll** [comment]
@jidianzhixia if you're asking a question, we've [already indicated](https://github.com/spring-io/initializr/issues/1060) the issue tracker is not the right place to do so. 

If you're reporting an issue with Spring Boot, a title with no description is nowhere near enough. If that's your intention, please update the description to describe the problem with a small sample that reproduces the problem and we can reopen this issue. Thank you.
