### ISSUE TITLE
spring-boot-starter-rsocket pom contains security dependencies

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#20243]
It appears that as of [spring-boot-starter-rsocket-2.3.0.M1.pom](https://repo.spring.io/libs-snapshot/org/springframework/boot/spring-boot-starter-rsocket/2.3.0.M1/spring-boot-starter-rsocket-2.3.0.M1.pom) it contains Spring Security dependencies that are being pulled in transitively. The dependencies are in 2.3.0.M2 and the latest 2.3.0.BUILD-SNAPSHOT:

```xml
<dependency>
  <groupId>org.springframework.security</groupId>
  <artifactId>spring-security-config</artifactId>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>org.springframework.security</groupId>
  <artifactId>spring-security-web</artifactId>
  <scope>compile</scope>
</dependency>
```

This means that simply adding the `spring-boot-starter-rsocket` triggers the Spring Boot auto configuration for Security.

This was originally brought to my attention because @joshlong was having difficulties doing a demo and asked for my help. I haven't investigated the scope of the problem, so it would probably be good to check if other dependencies are impacted.

**Comment by mbhave** [comment]
Those dependencies are explicitly included in the [`build.gradle`](https://github.com/spring-projects/spring-boot/blob/23e781033ca2ad33eb07c92ce1ef9f0bcc676762/spring-boot-project/spring-boot-starters/spring-boot-starter-rsocket/build.gradle). They aren't in 2.2.x so I'm not sure if there was a reason for adding them in master or an oversight. Flagging for team attention to see if anyone remembers.

**Comment by bclozel** [comment]
That's odd. I don't remember any decision around that. Probably a copy/paste issue during the Gradle migration?

**Comment by mbhave** [comment]
Seems like that to me. Since you don't remember anything related to this either, I'll mark it as a bug.

**Comment by rwinch** [comment]
Thanks for the quick turnaround on this!

**Comment by wilkinsona** [comment]
🤦‍♂ Thanks for spotting and reporting this, @rwinch. Not quite sure how I managed that during the migration.

**Comment by rwinch** [comment]
No problem. A migration of that size is going to have a few :man_facepalming: moments. Thanks again @mbhave for the fast turnaround :smile:
