### ISSUE TITLE
Upgrade to Httpclient 4.5.11

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20275]

**Comment by juliojgd** [comment]
With this upgrade this issue is reproducing again, broking SSL connections on some (frequent) cases: https://github.com/spring-projects/spring-boot/issues/18235

HttpClient 4.5.10 was working.
I think it should be downgraded to 4.5.10

**Comment by juliojgd** [comment]
If affects  2.2.5 but also 2.1.13  @snicoll

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but downgrading a dependency is something that we try to avoid. While it may be the right thing to do in your case, other users may not be affected by the problem that you're seeing but do require some of the other changes in 4.5.11.

If you would prefer to use 4.5.10, you can use the `httpclient.version` property to do so.

**Comment by juliojgd** [comment]
Thanks, I am  using that property to downgrade, but I think that SSL wildcard certificates is something a lot of servers are dependent of, and can break a lot of connections. Only for your consideration :-)
