### ISSUE TITLE
Provide an RSocketMessageHandlerCustomizer to allow customizing of the RSocketMessageHandler

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#20303]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background
Spring Boot provides a number of callback interfaces that can be used to customize the beans that it auto-configures. For example, a `TomcatConnectorCustomizer` can be used to customize a Tomcat `Connector`.

## Problem
At the moment, the only way to add customizations to a `RSocketMessageHandler` is to provide your own `RSocketMessageHandler` bean which completely overrides the auto-configured `RSocketMessageHandler` bean. This can be bit tedious and we should allow providing customizers instead which can be applied to the bean created by Spring Boot.

It would look something like:

```java
@Bean
public RSocketMessageHandlerCustomizer messageHandlerCustomizer() {
	return (handler) -> handler.setRouteMatcher(...);
}
```

## Solution

Add a `RSocketMessageHandlerCustomizer` type. Beans of  `RSocketMessageHandlerCustomizer` type should be applied automatically to `RSocketMessageHandler`, this can be done [here](https://github.com/spring-projects/spring-boot/blob/7d7b1e13a2409a9a5499c87fcfe73c757b0cea09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketMessagingAutoConfiguration.java#L47). 

The `ObjectProvider` interface can be used for injecting a dependency. [Here](https://github.com/spring-projects/spring-boot/blob/7d7b1e13a2409a9a5499c87fcfe73c757b0cea09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisEmbeddedServerConfiguration.java#L68) is an example that can be used to inject customizers when there can be 0..n of them.

Tests are [here](https://github.com/spring-projects/spring-boot/blob/7d7b1e13a2409a9a5499c87fcfe73c757b0cea09/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/rsocket/RSocketMessagingAutoConfigurationTests.java).

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [x] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [x] Try to fix the issue following the steps above
- [x] Commit your changes and start a pull request.

**Comment by joshlong** [comment]
This is following up on https://github.com/spring-projects/spring-boot/issues/18356#issuecomment-587316687

**Comment by aartiguptaa** [comment]
I can pick this up !

**Comment by snicoll** [comment]
@aartiguptaa thank you very much, it's all yours. Let us know if you have any question.

**Comment by cicioflaviu** [comment]
If something comes up and @aartiguptaa will not be able to complete the task, I'm available to take over.

**Comment by mbhave** [comment]
@aartiguptaa how's it going? Please let us know if you need any help tackling this issue.

**Comment by logicatmidod** [comment]
Hi 

looks like this one's gone. please let me know if there is any first timer issue which I can contribute to?

Thanks

**Comment by snicoll** [comment]
@logicatmidod we can't let you know when there are a first timer issue available. If you're trying to contribute, I've answered a similar question this morning, please read [this comment](https://github.com/spring-projects/spring-boot/pull/20917#issuecomment-612369883). We prefer no to use the issue tracker for questions so for any follow-up questions on the project, please join the community on Gitter.

**Comment by aartiguptaa** [comment]
Apologies for the delay folks, I am working on this now, and should have more updates this weekend.

**Comment by corneliouzbett** [comment]
@joshlong @snicoll could you refer me to a good first-time issue to work on. I want to understand the codebase and contribute more In future

**Comment by snicoll** [comment]
@aartiguptaa How are things? Do you need help with anything?

@corneliouzbett I've [answered that question already here](https://github.com/spring-projects/spring-boot/issues/20303#issuecomment-612435012) but it was hidden so I just changed that.

**Comment by aartiguptaa** [comment]
@snicoll , @mbhave , which dependency should the Object Provider interface be used to inject?

**Comment by snicoll** [comment]
I am not sure I got the question. `ObjectProvider` is part of Spring Framework. There is an [example here](https://github.com/spring-projects/spring-boot/blob/7d7b1e13a2409a9a5499c87fcfe73c757b0cea09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisEmbeddedServerConfiguration.java#L68)

**Comment by aartiguptaa** [comment]
The instructions say "The ObjectProvider interface can be used for injecting a dependency. Here is an example that can be used to inject customizers when there can be 0..n of them."


which dependency should ObjectProvider inject ?

Is it the message handler bean ? or a customizer bean?

@Bean
	@ConditionalOnMissingBean(RSocketMessageHandler.class)
	public <WhatType?>  RSocketMessageHandler(ObjectProvider<RSocketMessageHandlerCustomizer> customizers) {
		(what should this inject?)
	}

**Comment by scottfrederick** [comment]
@aartiguptaa The existing method that looks like this: 

```
	@Bean
	@ConditionalOnMissingBean
	public RSocketMessageHandler messageHandler(RSocketStrategies rSocketStrategies) {
		RSocketMessageHandler messageHandler = new RSocketMessageHandler();
		messageHandler.setRSocketStrategies(rSocketStrategies);
		return messageHandler;
	}
```

would be changed to take the new optional customizer dependency using `ObjectProvider`, looking something like this: 

```
	public RSocketMessageHandler messageHandler(RSocketStrategies rSocketStrategies, ObjectProvider<RSocketMessageHandlerCustomizer> customizers) {
            ...
	}
```

Inside of that method, each  `RSocketMessageHandlerCustomizer` can be applied to the `messageHandler` object as in [this example](https://github.com/spring-projects/spring-boot/blob/7d7b1e13a2409a9a5499c87fcfe73c757b0cea09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisEmbeddedServerConfiguration.java#L82).

**Comment by aartiguptaa** [comment]
Trying to push a PR, on a new branch,

**Comment by scottfrederick** [comment]
@aartiguptaa You'll need to [create your own fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) of `spring-boot` and push your changes there. 

After creating a fork, you should be able to 
```
$ git remote origin set-url https://github.com/aartiguptaa/spring-boot
```
 to point the `origin` remote to your fork instead of `spring-projects/spring-boot`. Then you can 
```
$ git push --set-upstream origin RSocketMessageHandlerCustomizer
```
to push your new branch to your own fork. 

Once the branch is pushed to your fork, see the github docs for [creating a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by wilkinsona** [comment]
Closing in favour of #21081.
