### ISSUE TITLE
Backport Maven plugin integration tests from master to 2.2.x

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#20336]
The Maven plugin integration tests changed completely between the `2.2.x` branch and `master`. This makes forward-porting changes to the Maven plugin from `2.2.x` harder than they should be. 

The integration testing approach on `master` is a big improvement over what's on `2.2.x`, as it allows test cases to easily assert contents of the build log output, makes it possible to share a test project between test cases, and generally gives more control to individual tests cases.

**Comment by philwebb** [comment]
Since 2.2.x is now out of OSS support I'm going to close this one.
