### ISSUE TITLE
Hibernate Search configuration ignored in application.yml

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [spring-projects/spring-boot#2034]
Not sure if this is by design, but configuring Hibernate Search is only available through the hibernate.properties configuration, not through the application.yml's `spring.jpa.hibernate namespace`. This may have just been the result of the mistaken assumption that the spring boot jpa auto-configuration passes along all hibernate configuration.

**Comment by wilkinsona** [comment]
Closing due to lack of response. If you're still interested in this enhancement, please comment again with the requested information and we can reopen the issue.
