### ISSUE TITLE
Compabibility of v1.2.3 with Tomcat 7.0.100 ?

### ISSUE THREAD

**Issue by mwithheld** [spring-projects/spring-boot#20351]
We upgraded our app from Tomcat 7.0.96 to 7.0.100 and found that although the app appears to start, it's not responding to http requests.  It uses Spring Boot v1.2.3.  

When running the latest version 7.0.100 the spring boot 1.2.3 never logs to the log file,
The deploy time for the app .war is 39 seconds when working but only 24 seconds
when not working.

Is this a known incompatibility?  Any workarounds short up upgrading everything in the app?

**Comment by wilkinsona** [comment]
We’re not aware of any incompatibilities, however the last 1.2.x release was over four years ago and the whole 1.x like reached end-of-life in August 2019. Unfortunately, that means that there is nothing we can do to help you here. I urge you to upgrade to a supported version of Spring Boot as soon as possible.

If you cannot or will not upgrade for some reason then, if things work with Tomcat 7.0.96 but fail with 7.0.100, you may want to ask the Tomcat community for some assistance. I would not expect a breaking change in behaviour between those two releases.

**Comment by wortner** [comment]
What has been the problem seems like we are experiencing the same problem with spring-core-5.1.2. My investigation shows the problem is the spring context will not start for 7.0.100, but no problem on 7.0.96

**Comment by bclozel** [comment]
@wortner As of 5.0, [Spring Framework guarantees compatibility with Tomcat 8.5+ only](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#web-servers).

**Comment by wortner** [comment]
I have found that too lately, but still what is the exact change that broke the app. We as for now cannot change to 8.5+ so I was wondering what is the exact cause. This will be really tedious task. Thanks anyway.

**Comment by mwithheld** [comment]
To be clear, this is very likely Apache Tomcat's fault for introducing backwards-breaking changes ([changelog](https://tomcat.apache.org/tomcat-7.0-doc/changelog.html)).  For those on the same path, the ones we hit are:

- AJP connectors need secretRequired="false"
- AJP only listens on specific addresses and Apache mod_jk proxy defaults to IPv6, so worker.properties may need to specify IPv4 localhost address

But again: This part is a Tomcat problem and nothing to do with Spring Boot.

For our (ancient Spring Boot v1.2.3) app, we upgraded to Tomcat 8.5.x successfully without any application changes.

**Comment by pgpx** [comment]
Had the same problem with Spring 4 - works on Tomcat 7.0.99 and 8.5.51/53, but not on Tomcat 7.0.100.  From [this thread](https://marc.info/?l=tomcat-user&m=158271944425239&w=2) it looks like it might be fixed in Tomcat 7.0.101

**Comment by LeeSiler** [comment]
> I have found that too lately, but still what is the exact change that broke the app. We as for now cannot change to 8.5+ so I was wondering what is the exact cause. This will be really tedious task. Thanks anyway.

 Did you solved it? We get the proble when  force to upgrade tomcat to  v.7.0.100.No application log

**Comment by pgpx** [comment]
Have you tried it on 7.0.103 that was just released?

**Comment by jonespm** [comment]
Thanks for the reminder @pgpx , I tried 7.0.103 and it worked for my spring boot app (where 7.0.100 didn't work)

**Comment by wortner** [comment]
For me it seems to be working as well.
