### ISSUE TITLE
Auto-configure @IntegrationComponentScan

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2037]
We could auto-configure the Spring Integration Java DSL `@IntegrationComponentScan` annotation.

**Comment by artembilan** [comment]
`@IntegrationComponentScan` isn't for SI Java DSL, but just for `@MessagingGateway` right now.
But, eh, I agree, that it could be utilized by default, as you have `@ComponentScan` on the `@SpringBootApplication`.
Not sure if `spring.integration.base-package` is an option for `@ConfigurationProperties`, but at least we can specify `@IntegrationComponentScan` by default as is.

I would like to see it in Boot 1.5 together with some other possible `IntegrationProperties`. 
Different story, but at least I shared my head...

**Comment by philwebb** [comment]
I don't think we'll get to this in 1.5 unfortunately.

**Comment by artembilan** [comment]
@philwebb ,

Thank you for the heads up!
I think I can come up with some PR till the end of today.
Then you'll see if it is appropriate for `1.5` or will go to `2.0` already.
