### ISSUE TITLE
TomcatReactiveWebServerFactory does not call getTomcatWebServer to create the TomcatWebServer

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20386]
`TomcatReactiveWebServerFactory.getWebServer(HttpHandler)` doesn't delegate to `TomcatReactiveWebServerFactory.getTomcatWebServer(Tomcat)` and instead creates the `TomcatWebServer` instance directly. This makes the javadoc for `getTomcatWebServer(Tomcat)` misleading:

> Factory method called to create the `TomcatWebServer`. Subclasses can override this method to return a different `TomcatWebServer` or apply additional processing to the `Tomcat` server.

**Comment by gangganghong** [comment]
@wilkinsona, I want to modify `TomcatReactiveWebServerFactory.getWebServer(HttpHandler)`,

replacing `return new TomcatWebServer(tomcat, getPort() >= 0);` with `return getTomcatWebServer(tomcat);`.

If you agree with me,then may I work on the issue?

**Comment by wilkinsona** [comment]
Thanks for the pull request, @gangganghong. The change you have proposed is exactly what I had in mind. I'll close this issue in favour of your PR.

**Comment by gangganghong** [comment]
Thanks.

**Comment by wilkinsona** [comment]
Reopening as the pull request was closed.
