### ISSUE TITLE
OpenAPI support for the spring web framework

### ISSUE THREAD

**Issue by Nirostar** [spring-projects/spring-boot#20396]
Dear Spring-Team,

I love using Spring and I have recently started a new project where I want to use spring-data-rest with all its features and then generate a Swagger/OpenAPI file from it and further generate Angular client methods and model from that.

* I found [springdoc-openapi](https://github.com/springdoc/springdoc-openapi) which doesn't support spring-data-rest at all
* and [springfox](https://github.com/springfox/springfox) which doesn't support the finer details like Pages and Projections/Excerpts

My feature request is that you include a possibility to generate (machine-readable) API documentation directly into spring boot. This would make good API documentation much easier and would lead to very nice, generated client code, which can be generated for a lot of programming languages (see [openapi-generator](https://github.com/OpenAPITools/openapi-generator))

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We consider HTTP/RESTful API documentation to be out of scope of Spring Boot itself. That role is filled by the [Spring REST Docs](/spring-projects/spring-restdocs) project. REST Docs itself does not have OpenAPI support [although it has been considered in the past](https://github.com/spring-projects/spring-restdocs/issues/213), but a [third-party extension](https://github.com/ePages-de/restdocs-api-spec) does.
