### ISSUE TITLE
Allow @DefaultValue to be used in fields

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#20402]
Currently, `@DefaultValue` is limited to constructor arguments.
This prevents auto generating constructor with lombok.

If `@DefaultValue` can be assigned to fields, immutable properties class can be written like this:

```java
@Getter
@AllArgsConstructor
@ConfigurationProperties(prefix = "my")
@ConstructorBinding
public class MyProperties {

	@DefaultValue("Foo")
	private final String name;
}

**Comment by snicoll** [comment]
I have some sympathy for that but enabling `@DefaultValue` on field opens up the possibility of the annotation to be used in non-lombok classes and I am not keen to do that.

Thanks for the suggestion anyway.
