### ISSUE TITLE
DependencyCustomizer ifAllResourcesPresent adds modules if any resources are present

### ISSUE THREAD

**Issue by wycm** [spring-projects/spring-boot#20418]
I found that the logic of the
`ifAllResourcesPresent`
and 
`ifAnyResourcesPresent`
methods is exactly the same
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-cli/src/main/java/org/springframework/boot/cli/compiler/DependencyCustomizer.java#L131

`

	/**
	 * Create a nested {@link DependencyCustomizer} that only applies if the specified
	 * paths are on the class path.
	 * @param paths the paths to test
	 * @return a nested {@link DependencyCustomizer}
	 */
	public DependencyCustomizer ifAllResourcesPresent(String... paths) {
		return new DependencyCustomizer(this) {
			@Override
			protected boolean canAdd() {
				for (String path : paths) {
					try {
						return DependencyCustomizer.this.loader.getResource(path) != null;
					}
					catch (Exception ex) {
						// swallow exception and continue
					}
				}
				return DependencyCustomizer.this.canAdd();
			}
		};
	}

	/**
	 * Create a nested {@link DependencyCustomizer} that only applies at least one of the
	 * specified paths is on the class path.
	 * @param paths the paths to test
	 * @return a nested {@link DependencyCustomizer}
	 */
	public DependencyCustomizer ifAnyResourcesPresent(String... paths) {
		return new DependencyCustomizer(this) {
			@Override
			protected boolean canAdd() {
				for (String path : paths) {
					try {
						return DependencyCustomizer.this.loader.getResource(path) != null;
					}
					catch (Exception ex) {
						// swallow exception and continue
					}
				}
				return DependencyCustomizer.this.canAdd();
			}
		};
	}
`

**Comment by wilkinsona** [comment]
Thanks for the report. Have you written a CLI extension where this is causing a problem? As far as I can tell, Spring Boot itself doesn't use `ifAllResourcesPresent`.

**Comment by wycm** [comment]
Thanks for the reply, I did not cause a specific problem because of the `ifAllResourcesPresent` method, I just found it in the process of reading the source code
