### ISSUE TITLE
Spring Boot Actuator tomcat metrics broken in 2.2.5.RELEASE

### ISSUE THREAD

**Issue by gstaykov** [spring-projects/spring-boot#20437]
I'm trying to update my Spring Boot Application from 2.1.5.RELEASE to 2.2.5.RELEASE  but my Tomcat metrics from Spring Boot Actuator start missing. When I reverted to 2.1.5.RELEASE they show up again. (http://localhost:8080/actuator/metrics metrics from actuator are usually here)

The exact metrics that are missing are:
```
tomcat.threads.busy
tomcat.threads.config.max
tomcat.threads.current
```

I'm afraid that there will be more missing metrics too. After I debug the problem I saw that  `MBeanExporter.afterSingletonsInstantiated` is not call on application initialization which leads to not registered/exposed  JMX beans and so later when `TomcatMetrics.bindTo` method is called `TomcatMetrics.registerThreadPoolMetrics` can't find those JMX beans needed for the metrics and they are not reported via spring-boot-actuator. (TomcatMetrics is class comming from spring-boot-actuator > io.micrometer > package io.micrometer.core.instrument.binder.tomcat )

I tested the same case in the same code base with 2.1.5.RELEASE and everything is working fine there. If you need more details message me :)

**Comment by snicoll** [comment]
@gstaykov thanks for the report, this is covered [in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#tomcats-mbean-registry).

**Comment by gstaykov** [comment]
ahhh .... I missed this :(   Thank you !
