### ISSUE TITLE
Upgrade to HttpClient 4.5.12

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20449]

**Comment by fmartinou** [comment]
Hi,

When is planned the Spring Boot 2.3 RELEASE?

Because the current HttpClient version (4.5.11) is suffering from a MAJOR issue fixed in 4.5.12 : 
[HTTPCLIENT-2047](https://issues.apache.org/jira/browse/HTTPCLIENT-2047)

**Comment by wilkinsona** [comment]
Please use the [milestone page](https://github.com/spring-projects/spring-boot/milestones) to answer questions about release dates.

Also,  please not that you don't need to wait for us to upgrade. You can use the `httpclient.version` property to override Boot's dependency management. Lastly, in addition to upgrading in 2.3, we'll pick up the latest Http Client 4.5.x release in this week's 2.2.6 release.
