### ISSUE TITLE
Metrics support for "bar chart" data

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2047]
It would be nice if the metrics generic API provided by Spring boot would allow to represent the distribution of data. 

For instance, spring initializr has a metrics to count the number of times a project was requested with a given dependencies. We have something like this now:

```
counter.initializr.dependency.actuator: 123,
counter.initializr.dependency.amqp: 34,
...
counter.initializr.dependency.velocity: 25,
counter.initializr.dependency.web: 822,
counter.initializr.dependency.websocket: 75,
counter.initializr.dependency.ws: 97
```

It would be nice if I could give the id of the metric and pass the _qualifier_ instead. in the JSON output this would give a nested object instead of a flat list of metrics

```
counter.initializr.dependency : {
    actuator: 123,
    amqp: 34,
    ...
    velocity: 25,
    web: 822,
    websocket: 75,
    ws: 97
}
```

Not sure that's the proper way of representing that though.

**Comment by dsyer** [comment]
I don't think anything is changing here (no need as far as I can tell), but there might be some new implementations of `CounterService` in #2682 (so follow progress there).
