### ISSUE TITLE
Add origin support for empty YAML list and map

### ISSUE THREAD

**Issue by copa2** [spring-projects/spring-boot#20506]
While searching the root cause for https://github.com/spring-cloud/spring-cloud-config/issues/1572 I reviewed `OriginTrackedYamlLoader`. In cases of an empty list or empty map there is no origin created. 

**Reproduction**
Add to https://raw.githubusercontent.com/spring-projects/spring-boot/master/spring-boot-project/spring-boot/src/test/resources/org/springframework/boot/env/test-yaml.yml
```yaml
emptylist: []
emptymap: {}
```
and extend testcases for emptylist and emptymap.

**Fix**
Add additional code for CollectionNodes which are empty In `OriginTrackedYamlLoader.constructObject` between ScalarNode and MappingNode check.
```java
} else if (node instanceof CollectionNode && ((CollectionNode<?>) node).getValue().isEmpty()) {
   return constructTrackedObject(node, super.constructObject(node));
}
```
https://github.com/spring-projects/spring-boot/blob/a66c4d3096877b33119366ea9ea165c892b462c8/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/OriginTrackedYamlLoader.java#L85-L95

**Comment by mbhave** [comment]
See #21704.

**Comment by izeye** [comment]
It seems that @mbhave intended to close this.

**Comment by wilkinsona** [comment]
Thanks.

**Comment by cnualapati-hub** [comment]
I still get this issue with springboot 4.0.1 as well. can someone please help me on this?

**Comment by wilkinsona** [comment]
I'm not sure exactly what you mean by "this issue" but please note that origin support for empty YAML maps was [removed](https://github.com/spring-projects/spring-boot/commit/69de06ac2dd4020f2dcaa3aabba532107a7cc729) as it caused an unwanted change in behavior for configuration property binding.

**Comment by cnualapati-hub** [comment]
cloud-config service returns an empty string ("") instead of an empty array '[ ]'
ex: 
My `config yml`

```yaml
company:
    name: xyz1
    empList: []
```

I receive

```
{
    company: {
        name: xyz,
        empList: ""
    }
}
```

**Comment by wilkinsona** [comment]
I can't see any connection between that and this issue which was about tracking the origin of a property's value not the value itself.

If you'd like us to investigate, please create a new issue with a minimal sample that reproduces the problem. Such a sample should not involve Spring Cloud Config Server unless the problem only occurs when using Config Server. If that's the case, a Spring Cloud issue would be more appropriate than a Spring Boot issue.
