### ISSUE TITLE
Remove packages from the javadoc that are not user-facing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20517]
There are some differences between 2.2 and 2.3, for example 2.3 includes javadoc for `org.springframework.boot.autoconfigureprocessor` and `org.springframework.boot.configurationprocessor.*` whereas 2.2 does not. We need to decide which is right and then fix the other one.

**Comment by lzy1993lzy** [comment]
我也看不懂啊。
