### ISSUE TITLE
Deploy XSDs automatically

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20519]
The new layers configuration work introduced a first Spring Boot specific XSD. We've deployed it manually for the time being but we should deploy it the same way other projects do.

**Comment by snicoll** [comment]
To deploy it automatically, we need to create a `spring-boot-docs-schema.zip` with additional properties attached to the zip, the same way we do for the main documentation distribution. The properties are:

```
zip.deployed=false
zip.type=schema
```

See [how Spring Framework does it](https://github.com/spring-projects/spring-framework/blob/e1c0f3b067016b1940003a63220eb0fa4a9cd1e4/gradle/docs.gradle#L226)

**Comment by philwebb** [comment]
Moving to 2.6.9 since we need to push updated XSDs for #31126

**Comment by snicoll** [comment]
The layers have been [updated manually](http://www.springframework.org/schema/boot/layers/) so that we can proceed with the release.

**Comment by wilkinsona** [comment]
Chatting with @snicoll, Framework no longer does this automatically. Given that and how infrequently we change the XSD, this doesn't feel worth spending time on at this time.
