### ISSUE TITLE
Spring Boot Actuator: Endpoint

### ISSUE THREAD

**Issue by aeiplatform** [spring-projects/spring-boot#20515]
[Implementing Custom Endpoints](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-custom)

```
@Component
@Endpoint(id = "test")
class TestEndpoint {
// ... some operations ...
}
```

Endpoint needs to be also annotated with one of stereotypes otherwise it won't be exposed via HTTP or JMX.

**Comment by snicoll** [comment]
@aeiplatform there are a number of ways you can register a new bean in the `ApplicationContext`. You may decide to configure it via `@Bean` in a `@Configuration` class or via classpath scanning. If you chose the later, you need to add the `@Component` stereotype like for any other components. I don't think anywhere the doc infers that an `@Endpoint` is all that is required. 

If you feel differently, can you please quote the doc that you think is misleading?

**Comment by aeiplatform** [comment]
@snicoll I just wanted to know if such behavior is expected by default if so close this. Thx.

**Comment by snicoll** [comment]
Thanks for the feedback. Going forward, if you have more questions, please ask on StackOverflow or Gitter, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
