### ISSUE TITLE
Add package info to javadoc for new packages in spring-boot-loader(-tools)

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20516]
The following packages have no description:

- `org.springframework.boot.loader.jarmode`
- `org.springframework.boot.loader.tools.layer`
- `org.springframework.boot.loader.tools.layer.classes`
- `org.springframework.boot.loader.tools.layer.library`

**Comment by cicioflaviu** [comment]
Can I work on this one?

**Comment by wilkinsona** [comment]
Thanks for the offer, @cicioflaviu. We have some renaming planned for at least some of those packages (#20526) so I think it's probably better if we take care of this ourselves as part of sorting that out.
