### ISSUE TITLE
Jwt Decoder: signature algorithm configuration not used in combination with public-key-file

### ISSUE THREAD

**Issue by m-kay** [spring-projects/spring-boot#20521]
When configuring a jwk public key file the alogrithm configuration is not used but always set to RS256.

See [OAuth2ResourceServerJwtConfiguration.java#L78](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/servlet/OAuth2ResourceServerJwtConfiguration.java#L78)

Should be something like this:
```java
@Bean
@Conditional(KeyValueCondition.class)
JwtDecoder jwtDecoderByPublicKeyValue() throws Exception {
	RSAPublicKey publicKey = (RSAPublicKey) KeyFactory.getInstance("RSA")
			.generatePublic(new X509EncodedKeySpec(getKeySpec(this.properties.readPublicKey())));
	return NimbusJwtDecoder.withPublicKey(publicKey).signatureAlgorithm(SignatureAlgorithm.from(this.properties.getJwsAlgorithm())).build();
}
```

**Comment by wilkinsona** [comment]
Closing in favour of #20523.
