### ISSUE TITLE
Deprecate spring.mvc.pathmatch.use-suffix-pattern, spring.mvc.pathmatch.use-registered-suffix-pattern, and spring.mvc.contentnegotiation.favor-path-extension

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20528]
The underlying properties have been deprecated in Spring MVC. We should consider following suit with our configuration properties.

**Comment by ettingshausen** [comment]
@wilkinsona Excuse me for interrupting. Is there a new recommended usage? For some old applications which use `*.do` or `*.action`.

**Comment by snicoll** [comment]
@ettingshausen the original description states that we're merely deprecating configuration properties that control a behaviour that's now discouraged in the core framework. The reference guide of the Spring Framework [has an explicit note about it](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-suffix-pattern-match).

Going forward, please ask questions on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
