### ISSUE TITLE
Build failures in WarIntegrationTests

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#20535]
Hi,

I haven't been able to fix it straight away today, so this time I only report it instead of creating a PR.

After `ca202ad59fb2c526c7d1738fc31b5e147aa5f600` the build seems to [fail](https://ci.spring.io/builds/109301).

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. I'm looking at it now. I've re-opened #20176.
