### ISSUE TITLE
Ignore trailing slash should not apply to single character URIs

### ISSUE THREAD

**Issue by rworsnop** [spring-projects/spring-boot#20536]
The fix for #18207 chops off the trailing slash of URIs sent in the "http.server.requests" metric.
It's doing it for root URLs, too - meaning that "/" becomes "".
CloudWatch does not like this. It responds with:
```
The parameter MetricData.member.19.Dimensions.member.5.Value is required. (Service: AmazonCloudWatch; Status Code: 400; Error Code: MissingParameter; Request ID: 2c440f89-401b-4c8f-bd7c-0b1051ee4a0a)
```
Would it make sense to leave the root URI alone?

**Comment by rworsnop** [comment]
For now I am working around this by setting `management.metrics.web.server.request.ignore-trailing-slash=false`

**Comment by snicoll** [comment]
@rworsnop thanks for the report. There was a (very recent) change in micrometer to drop such an invalid tag, see https://github.com/micrometer-metrics/micrometer/issues/1813

We should avoid a situation where we provide a tag value that some monitoring systems won't accept and I think it makes sense not to trail it. Flagging for team attention to see if the rest of the team feels differently.

**Comment by snicoll** [comment]
@rworsnop a `2.2.6.BUILD-SNAPSHOT` with a fix will be available shortly. `2.2.6` is scheduled for later next week. If you have time to give a snapshot a try, your feedback would be very much appreciated. Thanks.
