### ISSUE TITLE
Include templates in the default resources layer

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20542]
The default resources layer currently gets its content from the following locations:

- `META-INF/resources/`
- `resources`
- `static`
- `public`

I think it makes sense to add `templates` to this list as they're likely to change at the same frequency as content in the locations above. This would also align things more closely with [the locations the do not trigger a DevTools restart but do trigger a live reload](https://docs.spring.io/spring-boot/docs/2.3.0.M3/reference/htmlsingle/#using-boot-devtools-restart-exclude).

**Comment by mbhave** [comment]
We can close this as we're going to go with a single layer for the `application` by default. See #20562.
