### ISSUE TITLE
Add HealthEndpointGroupsRegistry and its Customizer

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#20554]
As of 2.2.0, Spring Boot introduced `HealthEndpointGroups` for grouping subsets of health indicators under a single name and correlating their status. Right now groups are driven only by configuration properties and auto-configuration; there is no way to programmatically/conditionally add new groups.

This issue aims at introducing an `HealthEndpointGroupsRegistry` interface that can be mutated by `HealthEndpointGroupsRegistryCustomizer` components (for looking into the registry, adding and deleting groups).

This infrastructure is required by #19593, since we want to automatically add`"liveness"` and `"readiness"` health groups if they are not already defined by the application.

**Comment by aivinog1** [comment]
@bclozel Hello. Do you mind if I do this issue? I already start working on this issue: https://github.com/aivinog1/spring-boot/commit/67e2feb80e6acb67f46114c9c81cbe5518516f9d. For me, this issue is pretty clear I think that I'll create a PR in a day or two.

**Comment by bclozel** [comment]
Hello @aivinog1 
Thanks for the offer, but I’m already done with this issue (and I was mostly done when I created it). This issue is mostly supporting #19593 and will be closed at the same time.

I’m sorry you’ve spent time on this. To avoid that situation in the future, please note that we have dedicated labels for first time contributors or help wanted. It’s always a good idea to leave a comment before spending time on an issue: the team can give you guidance or let you know how likely it is going to be scheduled for a milestone.

Thanks!

**Comment by aivinog1** [comment]
@bclozel Got it, thanks!
