### ISSUE TITLE
Provide an option when using layer tools' extract to flatten the extracted content

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20564]
`extract` currently writes the content into a directory structure the closely resembles the structure of the entries in the jar, with the layer name appearing twice in the path of each extracted file:

```
<layer-name>/BOOT-INF/layers/<layer-name>/…
```

We'd like to offer an option to simplify this so that, once extracted, the directory structure looks more like a normal fat jar that has been exploded:

```
<layer-name>/BOOT-INF/…
```

This will make it easier for users to use `java -cp` with an extracted layered jar and for other existing tooling that relies on the current directory structure. It will require a change to the `classpath.idx` file as it currently includes `BOOT-INF/layers/<layer-name>/lib` in its entries. We think we can switch to just using the names of the jar files instead.

**Comment by mbhave** [comment]
Depending on the outcome of #20529 this might not be needed.

**Comment by wilkinsona** [comment]
This is no longer needed as the layers are entirely represented by the index with no changes to the location of files in the jar.
