### ISSUE TITLE
Failure with Thymeleaf and java -jar

### ISSUE THREAD

**Issue by transentia** [spring-projects/spring-boot#2057]
I have an app that works perfectly when started within IntelliJ or via gradle bootRun.

However, if I do gradle bootRepackage and then try and run the resulting jar, I end up with:

```
2014-12-02 21:46:14.086 ERROR 9839 --- [nio-2014-exec-2] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-2014-exec-2] Exception processing template "/login": Error resolving template "/login", template might not exist or might not be accessible by any of the configured Template Resolvers
2014-12-02 21:46:14.087 ERROR 9839 --- [nio-2014-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/login", template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/login", template might not exist or might not be accessible by any of the configured Template Resolvers
```

This gives an EXTREMELY BAD impression of spring boot. Extremely.

In my case, I was pretty much ready to move into UAT... Quote I to my manager: "now I'll simply package it up, and we're ready to go..."

And...Crash. 

Red faces all round. Mine especially. I don't like the feeling. Worse, I now have a manger who is nervous about Spring Boot. The immortal phrase "unknown unknowns" was used more than once in discussion.

LOTS of frantic searching ensued. Too much searching was required before I came across issue 1744. I admit,I should have looked here earlier in the process but still...

What is particularly galling is that it seems to indicate that none of the SB examples have been run via jars. This error is so straightforward that it would have been seen immediately in any jarred exemplar. Without the workaround, the whole idea of jarring is killed dead.

I have seen https://github.com/spring-projects/spring-boot/issues/1744. I strongly believe that this should be re-considered.

Also see: http://stackoverflow.com/questions/27249078/spring-boot-gives-templateinputexception-error-resolving-template-when-runnin?noredirect=1#comment42982098_27249078. I describe how I used the workaround from issue 1744.

_I_ estimate this bug as HIGH priority.

**Comment by bowenchen6** [comment]
I use redirect url , failure with Thymeleaf and java -jar, but not redirect success.
when I add prefix: classpath:/templates, not redirect also failure.

**Comment by philwebb** [comment]
@bowenchen6 I'm afraid this issue has been closed for a little while now. Could you open a new one with some more details if you think you've found a bug. Alternatively, you can ask general questions on stackoverflow.com using the `spring-boot` tag.

**Comment by mkulasi** [comment]
> @transentia The security configuration is referring to URLs that should be used for login, success and failure. How are you mapping those URLs to your templates? Are you using something like this:
> 
> ```java
>     @Bean
>     WebMvcConfigurerAdapter mvcViewConfigurer() {
>         return new WebMvcConfigurerAdapter() {
>             @Override
>             public void addViewControllers(ViewControllerRegistry registry) {
>                 registry.addViewController("/login").setViewName("login");
>                 // ...
>             }
>         };
>     }
> ```

By following this comment i was able to resolve similar problem :)
