### ISSUE TITLE
Actuator 2.3.0 SNAPSHOT version is not resolvable

### ISSUE THREAD

**Issue by maczikasz** [spring-projects/spring-boot#20602]
There is a mismatch between the jar name and the maven-metadata.xml

https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-actuator/2.3.0.BUILD-SNAPSHOT/spring-boot-actuator-2.3.0.BUILD-20200321.144200-411.jar

![image](https://user-images.githubusercontent.com/5039095/77236469-1e547b00-6bbf-11ea-8feb-4aa110b2999d.png)

**Comment by snicoll** [comment]
@maczikasz thank you, we are aware of the problem and have raised a support request with JFrog as we believe this is a regression introduced by a recent upgrade on repo.spring.io.
