### ISSUE TITLE
spring-kafka state store health indicator

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-boot#20626]
I accidentally opened an issue at spring-kafka project: https://github.com/spring-projects/spring-kafka/issues/1421

In short, a kafka state store can be tracked whether it is population process is finished or not. Also kafka-streams is unreachable when a state store is closed. A KafkaStateStoreHealthIndicator can handle those changes and reflect as health.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Reading around a bit, and in particular [Confluent's documentation](https://docs.confluent.io/current/streams/monitoring.html#runtime-status-information), I'm not sure that there will be a one-size-fits-all solution here.

The first thing the Confluent documentation discusses is the [state of a `KafkaStreams` instance](https://docs.confluent.io/current/streams/monitoring.html#status-of-kafkastreams-instances). This seems to be something of a general recommendations as there aren't many ifs in the description. Later on it covers [monitoring state store restoration](https://docs.confluent.io/current/streams/monitoring.html#monitoring-the-restoration-progress-of-fault-tolerant-state-stores) but, to my reading, this doesn't seem to be so broadly applicable.

Unless we can find something that works well for a large majority of applications using Kafka Streams, I am concerned that auto-configuring something will do more harm than good.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
