### ISSUE TITLE
Custom X509AuthenticationFilter is not properly initialized with AuthenticationManager

### ISSUE THREAD

**Issue by altery** [spring-projects/spring-boot#2067]
We use a `WebSecurityConfigurerAdapter` to configure X509 authentication. This worked well until we tried to initialize the `X509Configurere` with a custom `X509AuthenticationFilter`:

``` java
public static class DeviceApiSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {

  protected void configure (HttpSecurity http) {
  X509AuthenticationFilterExt x509Filter= new X509AuthenticationFilterExt(http);
    (...).and().x509().userDetailsService(new SomeDetailsService()).x509AuthenticationFilter(x509Filter);
  }
}
```

The problem is that the `AuthenticationManager` is not set on the filter instance during configuration in `X509Configurer#getFilter()`. We tried to do that manually by injecting the `AuthenticationManager` into the `WebSecurityConfigurerAdapter`, which resolves to an instance of `AuthenticationManagerConfiguration.LazyAuthenticationManager`. Unfortunately, when the manager is resolved during authentication it is missing the `PreAuthenticatedAuthenticationProvider`.

For now we worked around the issue by lazily initializing the filter with the `AuthenticationManager` in `getPreAuthenticatedPrincipal()`, because at that time, the `HttpSecurity` instance already contains the correctly initialized instance.

Affects spring boot 1.1.9 and might be related to this change: https://github.com/spring-projects/spring-boot/issues/1801

**Comment by philwebb** [comment]
Since you have a work-around and we're planning to overhaul security in 2.0 I'll close this one.
