### ISSUE TITLE
Remove UNDERTOW-350 work-around

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2069]
When [UNDERTOW-350](https://issues.jboss.org/browse/UNDERTOW-350) is fixed we can revert 78c22813d35f1e715ffccc7a65bae75301d61e3f.

**Comment by wilkinsona** [comment]
This has already been taken care of in 1.2.x where we're now using Undertow 1.1.3 which includes the fix for UNDERTOW-350
