### ISSUE TITLE
Consistently separate properties that require Spring Data and properties that do not

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20702]
`CassandraProperties` is currently mapped to `spring.data.cassandra`. There isn't any property that is Spring Data specific so it sounds like a mistake when the support was added.

We should remap it to `spring.cassandra` for consistency with other stores.

**Comment by mp911de** [comment]
Note that `schemaAction` has no effect without Spring Data Cassandra. There's a similar arrangement with MongoDB where `MongoProperties` does not depend on Spring Data MongoDB.

**Comment by snicoll** [comment]
Yes, so the plan would be to move that to a `CassandraDataProperties`.

> There's a similar arrangement with MongoDB where MongoProperties

Thanks, that's useful context for us to figure what to do and when.

**Comment by snicoll** [comment]
And looking a bit more Redis is `spring.redis` but the auto-configuration is Spring Data specific.

**Comment by mbhave** [comment]
Probably related: #11574

**Comment by wilkinsona** [comment]
Thanks, @mbhave. This looks like a dup of #11574 to me.
