### ISSUE TITLE
Clarify logging.file.clean-history-on-start documentation.

### ISSUE THREAD

**Issue by dailytabs** [spring-projects/spring-boot#20705]
"To force log archive cleanup on application startup, use the logging.file.clean-history-on-start property."

"logging.file.clean-history-on-start      LOG_FILE_CLEAN_HISTORY_ON_START        Whether to clean the archive log files on startup (if LOG_FILE enabled). (Only supported with the default Logback setup.)"

That is everything on https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging with the term "clean".

The term "clean" is not used anywhere else and has no context. What does it mean? Are you going to delete ALL the logs? Are you going to empty out the current log? Are you going to trigger a rotate? What exactly does this do?

Please clarify "clean" in your documentation.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Cleaning the history on start is a Logback feature. The best place to learn about exactly what it does and how it behaves is Logback's documentation. You can find that [here](http://logback.qos.ch/manual/appenders.html#tbrpCleanHistoryOnStart).

**Comment by dailytabs** [comment]
Then maybe don't put it under the generic "logging"? Maybe put it under logback? Maybe update documentation to indicate this isn't yours and where I should look. Why are you documenting things that you have no control or concern over?

Answers like this really piss me off. Humanity can do better.

**Comment by wilkinsona** [comment]
@dailytabs Your comment above does not adhere to the repository's [code of conduct](https://github.com/spring-projects/spring-boot/blob/04777d06d90e15ffbd869ebf5bf0376266baeb0c/CODE_OF_CONDUCT.adoc). Similar comments in the future may result in you being temporarily or permanently blocked.

The [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-custom-log-configuration) already notes that `logging.file.clean-history-on-start` is "only supported with the default Logback setup". If you don't think this is sufficient and would like to move things forward in a more constructive manner, perhaps you could open a pull request with what you think is a better approach?
