### ISSUE TITLE
Improve migration of legacy endpoint ids

### ISSUE THREAD

**Issue by philippn** [spring-projects/spring-boot#20703]
Hi there,

This is a essentially a follow-up on #18148 . As far as I understand this property was essentially introduced to help out with some warnings that are issued when Spring Cloud is on the classpath.

There is one notably case, where the current implementation doesn't cut it though: As per https://github.com/spring-cloud/spring-cloud-commons/issues/458, Spring Cloud still causes a warning message because of an endpoint called `service-registry`. The current implementation of the legacy id migration doesn't fix this, because it does not take the dash into account.

Thanks for your time and keep up the good work!

**Comment by philwebb** [comment]
Closing in favor of PR #21615
