### ISSUE TITLE
Where is the META-INF/spring-autoconfigure-metadata.properties?

### ISSUE THREAD

**Issue by tswstarplanet** [spring-projects/spring-boot#20721]
I wrote a demo to hack the code. And I found when Spring Boot choosed what classes to be loaded, it would use a configuration file 'META-INF/spring-autoconfigure-metadata.properties', but I didn't find the file in the Spring Boot source code.
So how does this file be generated ?
Thank you !

**Comment by snicoll** [comment]
There is an [annotation processor](https://github.com/spring-projects/spring-boot/tree/a7e8829560093bd566118a5c76016b7b3cd124f0/spring-boot-project/spring-boot-tools/spring-boot-autoconfigure-processor) that generates that file based on conditions in the module.

If you have further question, please chat with the community on Gitter or ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by x-j-j** [comment]
I find it at org.springframework.boot:spring-boot-autofonfigure:xxx.jar

**Comment by x-j-j** [comment]
I find it at org.springframework.boot:spring-boot-autoconfigure:xxx.jar
