### ISSUE TITLE
JsonParserFactory Should Look For JSON-P First

### ISSUE THREAD

**Issue by amihaiemil** [spring-projects/spring-boot#20723]
There is the class [JsonParserFactory](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/json/JsonParserFactory.java#L38) which tries to find a Json parser on the classpath. 

I think the first parser that is looked up should be [JSON-P (JSR-374)](https://javaee.github.io/jsonp/) since that is the standard for a few years now.

Furthermore, using SnakeYaml as a JSON parser may not be such a good idea, because exception stacktraces will be very confusing for the user -- they are working with JSON and seeing exceptions about YAML.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. While JSON-P may be a standard in name, it is not a standard in terms of adoption. From what we have seen, Jackson renames the dominant de-facto standard for JSON parsing on the JVM with Gson being the most commonly seen alternative.

**Comment by amihaiemil** [comment]
@wilkinsona I understand your point. However, I would still endorse JSON-P. 

The Java world was designed and is supposed to work primarily on standard interfaces. Sadly, the market shows us that most developers did not understand that. Most developers are using Jackson not because it is the best, but because they have no idea about JSR 374 and can't appreciate Java Interfaces.

That said, I'd still try to look for JSON-P first. Then Jackson second and Gson third. Perhaps it would also be elegant to display warnings if the user has more then one of them on the classpath.
