### ISSUE TITLE
Use spring.* prefix for all of our configuration properties

### ISSUE THREAD

**Issue by netbeansuser2019** [spring-projects/spring-boot#20736]
I would like to mark obsolete all properties (configurations) that do not start with "spring." and it is used by spring framework.

Reason:
To avoid issues e.g. https://github.com/spring-projects/spring-boot/issues/1432 and/or any issue with upgrade of final application that possibly set its own properties/configuration, but it could be in collision with any of defined by newer spring framework version.

Suggested solution:
1) mark all such configuration that do not start with "spring." as obsolete and report that to logging and keep old one supported for some time/some version (searching firstly over "spring." over all possible way like environment properties (SET), system properties "-D", command line argument "--", ... and if there is no match then try obsolete way that means prior name without "spring." at start of the name)
2) use always "spring." prefix

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/3450 is somewhat related to this.

**Comment by netbeansuser2019** [comment]
Sorry, I do not think that this is anyhow related to #3450 as it is not about setup prefix for configurations used by particular application only (that to me is how people should do it without any extending of Spring), but I am talking about Spring defined ones.

**Comment by philwebb** [comment]
It's related from our point of view since both issues relate to the danger of a property that we define being configured accidentally by the user. We also might find that renaming all our properties as suggested here would limit the need for the prefix idea discussed in #3450.

**Comment by netbeansuser2019** [comment]
Frankly speaking when I am thinking about prefix it comes to my mind these examples:
- spring.
- io.spring. or org.springframework.

**Comment by wilkinsona** [comment]
We've discussed this today and decided that the upgrade pain that it will cause outweighs the benefit. Closing.
