### ISSUE TITLE
Document how to initialize a database with R2DBC

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20742]
Follow-up of #20715

Neither Flyway nor Liquibase have native support for R2DBC at the moment. One way to initialize a database using R2DBC is to create a `DataSource` for the duration of the migration.

Hopefully both of them have excellent support for that and we expose properties to let users configure the database to migrate. A caveat is that `spring-jdbc` is still required on the  classpath so we should document all that and make sure it works as expected with smoke tests.

**Comment by nkonev** [comment]
Sorry for PR, but I've written simple migration library and published to Maven Central

https://github.com/nkonev/r2dbc-migrate
