### ISSUE TITLE
Harmonize issue title for auto-created Docker upgrade issues

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20760]
The current title/commit is currently `Upgrade Docker version in CI`. It would be more consistent if we changed it to something like `Upgrade CI to Docker X.Y.Z` where `X.Y.Z` is the new version.

**Comment by dreis2211** [comment]
The actual commit has the version information btw: https://github.com/spring-projects/spring-boot/pull/20756/commits

**Comment by dreis2211** [comment]
Nonetheless, I can do this if you want me to.

**Comment by snicoll** [comment]
> The actual commit has the version information btw

It does but not with the standard format we use.

> Nonetheless, I can do this if you want me to - just let me know

PR more than welcome! :)

**Comment by dreis2211** [comment]
I will do it this evening

**Comment by mbhave** [comment]
Closing in favor of PR #20793.
