### ISSUE TITLE
Add package-info to org.springframework.boot.buildpack.platform.docker.ssl

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20817]

**Comment by cicioflaviu** [comment]
I'd like to work on this one as my first contribution.

**Comment by snicoll** [comment]
Thanks for the offer, let us know if you have a question.

**Comment by cicioflaviu** [comment]
@wilkinsona - Pull request is ready.

**Comment by scottfrederick** [comment]
Superseded by #20913

**Comment by snicoll** [comment]
@cicioflaviu going forward, there is no need to ping about that. The team (and everyone matching this repository) already receive a notification when a PR is submitted.
