### ISSUE TITLE
Deprecate getters and setters for deprecated configuration properties consistently

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#20812]
When we deprecate a configuration property, we add `@DeprecatedConfigurationProperty` to the `getter` along with a `@Deprecated` on the getter and setter. We don't do this consistently though. This is [one example](https://github.com/spring-projects/spring-boot/blob/ffc2cff8de850ced28b131620ebf1ea0effac5f7/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L489-L521) where the getter and setter don't have `@Deprecated`.

**Comment by shahaf-sameach** [comment]
hi, would like to be a new contributor, can I take this for starters?

**Comment by snicoll** [comment]
@shahaf-sameach Thanks for the offer. Yes, please give that a try and let us know how it goes.

**Comment by snicoll** [comment]
I think going forward we should also make sure to add `@since` on the deprecation message, see #20991. 

@shahaf-sameach how is it going by the way? Do you need any help?

**Comment by philwebb** [comment]
We could add a `since` attribute on `@DeprecatedConfigurationProperty`

**Comment by shahaf-sameach** [comment]
hi @snicoll, thank you, just wanted to ask if that is straight forward as it seems, look for any `@Deprecated ` occurrence at a getter, and check the setter also annotated, am I missing something?

**Comment by snicoll** [comment]
Yes.

**Comment by snicoll** [comment]
@shahaf-sameach and I discussed offline and we've decided I would take over this one after all.
