### ISSUE TITLE
Link to the Maven Plugin's documentation is broken

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20818]
https://docs.spring.io/spring-boot/docs/2.3.0.M4/reference/htmlsingle/#build-tool-plugins-maven-plugin links to https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/html/ which no longer exists. The correct link is https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/reference/html/. We may want to add a link to the javadoc and PDF reference documentation while we're at it, aligning with those [provided for the Gradle plugin](https://docs.spring.io/spring-boot/docs/2.3.0.M4/reference/htmlsingle/#build-tool-plugins-gradle-plugin).

**Comment by snicoll** [comment]
Sorry, I forgot to fix the link. The second part of this is already the plan for #19165
