### ISSUE TITLE
Default for spring.kafka.listener.missing-topics-fatal is no longer aligned with Spring Kafka's default

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#20828]
(Also Boot 2.2).

We changed the default in spring-kafka to `false` in 2.3.4.

This property was added in S-K 2.2 with default `true` but this caused too many problems for the community.

https://docs.spring.io/spring-kafka/docs/2.4.5.RELEASE/reference/html/#configuration-changes

**Comment by dhirenmathur** [comment]
Hi, I'm looking to start contributing to OSS and this looks like a good place to start, is this up for grabs?

**Comment by snicoll** [comment]
Yes. We’d need a test to assert the default is consistent. Thanks for the offer!

**Comment by dhirenmathur** [comment]
Thanks @snicoll , I'll start working on it. 👍

**Comment by snicoll** [comment]
Closing in favour of PR #20917
