### ISSUE TITLE
Migrate NewRelic metrics to NewRelicClientProvider

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#20839]
The `httpClient` is now deprecated so we need to migrate to the new API.

As a result, we should double check that the `connect-timeout` and `read-timeout` properties are still honoured. If they aren't we need to make sure we add metadata to flag them as error.

**Comment by snicoll** [comment]
There is a `clientProviderType` that we may have to expose as well.

**Comment by shakuzen** [comment]
@neiljpowell has work on this prepared, I believe.

**Comment by neiljpowell** [comment]
Hi. Yes, I have a branch and can submit a PR for the new API later today.  @shakuzen we'll need to finalize moving the connect/readTimeout into NewRelicConfig or other, per the other Micrometer PR I submitted.

**Comment by snicoll** [comment]
Superseded by #20908
