### ISSUE TITLE
Request method 'MOVE' not supported

### ISSUE THREAD

**Issue by Sheldor5** [spring-projects/spring-boot#20848]
Missing documentation on how to add custom HTTP Method mappings/handlers/whatsoever.

I already raised a SO Question (https://stackoverflow.com/questions/61042630/spring-boot-2-2-5-request-method-move-not-supported) but since all solutions I found on Google/SO are not working anymore and I have not found anything about this in the docs I rais this issue in hope to get some docs about the extensibility on this use case.

I tried various options without any luck, solving one problem created 2 other problems and so on until I gave up. Most components which are auto-configured won't work if overriding just one. I also came across circular references which made no sense. And at last as my app was finally running and using my code some internal request dispatching completely overruled my custom code in the filter chain ...

**Comment by wilkinsona** [comment]
There's nothing to document here as using a custom HTTP method isn't supported by Spring MVC. You may be able to get creative without your own servlet and request dispatching logic, but you'd have to write it yourself. I'd strongly recommend that you stick to the standard HTTP request methods instead. It will make things considerably easier to implement both for you and for the clients calling your HTTP API.
