### ISSUE TITLE
Ensure empty layers are written to the index file

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#20858]
Raised on [Gitter](https://gitter.im/spring-projects/spring-boot?at=5e8b6e1ee24b4d6c44ee05e2):

> I noticed that from 2.3.0.M1 to 2.3.0.M4 the behavior has changed slightly. Now, a snapshot layer is not created if the project does not have snapshot dependencies, which is cool, but also complicates the Dockerfile that needs to be created as it needs to know whether the specific application has snapshot dependencies or not. I can no longer use a generic Dockerfile. I can workaround this problem via a Docker COPY trick, but I wondered if this is a “conscious” change.

**Comment by philwebb** [comment]
We're going to try a YAML compatible format that looks like this:

```yaml
- "test":
  - "BOOT-INF/lib/a.jar"
  - "BOOT-INF/lib/b.jar"
- "application":
  - "BOOT-INF/classes/Demo.class"
  - "META-INF/"
```

Entries that end `/` mean everything in that folder is in the same layer.

The file above can be parsed in Go quite easily:

```go
package main

import (
	"fmt"
	"gopkg.in/yaml.v2"
)

type Layer map[string][]string

func main() {
	data := `[{"deps": ["a", "b"]}, {"app": ["c", "d"]}]`
	layers := make([]Layer, 0)
	err := yaml.Unmarshal([]byte(data), &layers)
	if err != nil {
		panic(err)
	}
	for _, layer := range layers {
		for name, entries := range layer {
        		fmt.Println(name, "=>", entries)
    		}
	}
}
```

**Comment by nickstolwijk** [comment]
Will this solve https://stackoverflow.com/questions/61413181/spring-boot-2-3-0-m4-layered-jar-is-missing-a-layer-docker-fails-on-missing-dir/61413361 ?

**Comment by wilkinsona** [comment]
Yes, it will.
