### ISSUE TITLE
Properties files in subdirectories are not loaded when one file is empty

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-boot#20873]
I have a directory structure like

`./config/configmaps/application.yaml`
`./config/secrets/application.yaml`

Currently `./config/configmaps/application.yaml` is empty (it does not have any data in it).  In this situation the property file in `./config/secrets` is never loaded.  If I put some data in `./config/configmaps/application.yaml` than the property file in `./config/secrets` gets loaded as I would expect.

**Comment by dreis2211** [comment]
I think I have a fix ready - will post a PR soon.

**Comment by scottfrederick** [comment]
@dreis2211 Sorry, I should have assigned this to myself. I'm about to push a fix.
