### ISSUE TITLE
Spring devtools does not load classes generated by ActiveJDBC instrumentation correctly

### ISSUE THREAD

**Issue by logue** [spring-projects/spring-boot#20877]
The class file generated by ActiveJDBC cannot be recognized normally by the RestartClassLoader of spring devtools, and `an error named unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader occurs`.

There was a similar problem report with #3316, but the same was set as follows, but the problem was not solved.

META-INF/spring-devtools.properties
```properties
restart.include.models=/target/classes/dev/logue/app/models/*.class
```

In addition, the following lines have been added to application.properties to make sure that the classes in models are generated by ActiveJDBC.

```properties
spring.devtools.restart.additional-exclude=src/main/java/dev/logue/app/models/**
```

I also asked [Stackoverflow](https://stackoverflow.com/questions/60928442/spring-boot-devtools-and-activejdbc-integration), but it was said that it was a problem on the devtools side.

**Comment by snicoll** [comment]
> I also asked Stackoverflow, but it was said that it was a problem on the devtools side.

@logue I saw that and I don't think that's the case. Let's continue on the StackOverflow question you've raised to avoid duplicate efforts.
