### ISSUE TITLE
Actuator health check endpoint should return content-length header

### ISSUE THREAD

**Issue by kmandeville** [spring-projects/spring-boot#2089]
I'm deploying my Spring Boot application into AWS. When adding an instance to an AWS load balancer, you can configure a healthcheck for the load balancer to ping to determine if an instance is healthy or not. Actuator healthcheck endpoint should work great for this. Unfortunately, AWS requires that when using an HTTP type healthcheck ping when the response returns an actual body, then Transport-Encoding set to chunked (which it is already) and a Content-Length header that is equal to or greater than Zero. The actuator healthcheck endpoint does NOT set a content-length header and it seems like this should be fairly straightforward to set. I'm going to look through the source to see if I can figure out where that addition can be made. 

If this can't be added for reasons outside of my understanding, then I will have to use something other than the actuator healthcheck which seems like a big waste. 

From the AWS documentation on the ELB healthcheck: 

`If the load balancer receives any response other than "200 OK" within the response timeout period, the instance is considered unhealthy. If the response includes a body, then your application must either set the Content-Length header to a value greater than or equal to zero, or specify Transfer-Encoding with a value set to 'chunked'.`

**Comment by vpiduri** [comment]
Hi I am facing similar issue, can you provide your inputs.

We are running consul in OpenShift cluster. All services have been developed by Spring Boot/Cloud APIs and they have been registered successfully in consul. There is a health point exposed using SpringBoot actuator. The health point itself works just fine when try to hit using curl. But from Consul seeing a below errors frequently which causes issues in discovering the service.

Any suggestions would be great help.. 

2016/08/05 05:57:15 [WARN] agent: http request failed 'http://10.1.0.18:9080/health': Get http://10.1.0.18:9080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

[root@gtwtdlaposhv01 ~]# curl -i http://10.1.1.13:9089/health
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: spreadsheetloader-service:staging:9089
Set-Cookie: SESSION=1199bd63-c1c2-40cd-acac-218db0877123; HttpOnly
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked

Sometimes I do get the "status":"UP" ... sometimes I do not see this.

**Comment by wilkinsona** [comment]
@vpiduri This is closed. If you believe you have found a bug, please open a new issue. If you do so, please provide as much detail as possible and, ideally, a small sample that reproduces the problem.

**Comment by saurabhdevops** [comment]
@vpiduri , @wilkinsona , was there an issue open for this? I am facing a similar issue. I was wondering if There's already an issue open, I don't want to open a duplicate issue.

**Comment by wilkinsona** [comment]
@saurabhdevops I don't recall seeing one
