### ISSUE TITLE
Checkstyle is not catching Mockito.when

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#20902]
Called to `Mockito.when` should fail, but a few have somehow snuck in.

**Comment by philwebb** [comment]
E.g. `HazelcastHealthIndicatorTests`.

**Comment by mbhave** [comment]
@philwebb I couldn't find any usages of `Mockito.when`. `HazelcastHealthIndicatorTests` is using `BDDMockito.when`.

**Comment by philwebb** [comment]
Ahh, that explains it. There isn't a `BDDMockito.when` static method, it's picking it up because `BDDMockito` extends `Mockito` and there's a `Mockito.when`. Really we should bad static references like that.

Eclipse has a cleanup rule call "Change all access though subtype" which gets applied. If I did a cleanup on `HazelcastHealthIndicatorTests` it would change `BDDMockito.when` to `Mockito.when` and then we'd see checkstyle fail.
