### ISSUE TITLE
Modularizing Spring

### ISSUE THREAD

**Issue by rolaca11** [spring-projects/spring-boot#20903]
I'm sorry if this topic has come up a million times before, but I couldn't find an official statement about what the plans are for incorporating the JPMS into the Spring framework.

This feature has obviously received a lot of bad rep from the community, but I think it can open up interesting opportunities for the framework. Especially for Spring Boot, a `@ConditionalOnModule` annotation could be a nice addition, giving developers another set of tools into their auto-configuration repertoire.

By design, implementing this feature would not break projects that are not making use of modularity, since unnamed modules have access to all available modules. It also seems like Java 8 based projects are fine since JDK 8 just ignores the `module-info.class` altogether.

I have worked a bunch with JPMS lately, so I understand that a feature like this takes more than 5 minutes to implement and takes a lot of effort testing in the first iteration, however, I also feel like this feature would be worth the effort.

**Comment by snicoll** [comment]
> I'm sorry if this topic has come up a million times before, but I couldn't find an official statement about what the plans are for incorporating the JPMS into the Spring framework.

#13799 and in particular [this comment](https://github.com/spring-projects/spring-boot/issues/13799#issuecomment-405933453) should give you a bit more context about our position.

See also https://github.com/spring-projects/spring-framework/issues/18079.
