### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by jongmin92** [spring-projects/spring-boot#20914]
Hi,
I think there is a typo in the documentation: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-adding-active-profiles

> Sometimes, it is useful to have  `profil`-specific properties that add to the active profiles rather than replace them. 

`profil` -> `profile` is right?

**Comment by snicoll** [comment]
Thanks for the report @jongmin92, this was fixed this morning, see https://github.com/spring-projects/spring-boot/pull/20907
