### ISSUE TITLE
Add Jackson Afterburner module to spring-boot-starter-json autoconfiguration

### ISSUE THREAD

**Issue by helpermethod** [spring-projects/spring-boot#20922]
Hi,

it seems the [Jackson Afterburner Module](https://github.com/FasterXML/jackson-modules-base/tree/master/afterburner) will result in improved performance in most cases, sometimes considerably.

Thus I suggest to add it to the list of autoconfigured Jackson modules.

I would love to provide a PR, possibly accompanied by some (performance) tests.

References:
[Presentation: Jackson Performance](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#compatible-easy-afterburner)

**Comment by bclozel** [comment]
Dependency management is shipped with the jackson-bom already, and activating this module is about declaring a module instance as a `@Bean`.

Currently we're only auto-configuring the parameter names modules; given the required effort and the module popularity, I'm not sure we should add an auto-configuration for this module, as we'd need to do the same for the many other available modules.

I've marked this issue for team-attention to discuss that point.

**Comment by helpermethod** [comment]
It seems that Afterburner has [issues](https://github.com/FasterXML/jackson-modules-base/issues/37) with Java 9+.

Closing the issue.
