### ISSUE TITLE
Managing Files on Cloud

### ISSUE THREAD

**Issue by logicatmidod** [spring-projects/spring-boot#20921]
Hi All

I liked the idea of "spring-cloud-config" and able to expose environment properties as rest api's. However working with that I realised That sometimes we need the application to be able to access more than just environment properties for example JKS files or certificates or from the experience of the project I am coming from few XSD files. 

I know docker has options of mounting folders but I was thinking will it be a good idea if we can connect to a file-server say with protocol like ftp and all at backend of cloud-config server allowing the files to be exposed and become part of environment itself. to be used by spring boot application.

I am not sure if this is a good or bad thought or if there is something already existing like that.

Please let me know what do you think about this idea and if there is something like this already available.

**Comment by spencergibb** [comment]
Config server has a file api as well

**Comment by logicatmidod** [comment]
@spencergibb : Thanks for the information good to know. Could you please provide any guide on how to use it?

Thanks
Kunal

**Comment by spencergibb** [comment]
On mobile, here's a link to docs https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.1.RELEASE/reference/html/#_serving_plain_text

**Comment by snicoll** [comment]
Thanks @spencer. I am going to close this now as this is specific to Spring Cloud. @logicatmidod if you have more questions, please join the community on the #spring-cloud gitter channel.

**Comment by logicatmidod** [comment]
Thanks @spencergibb  and @snicoll
