### ISSUE TITLE
Add more context to the Kubernetes container lifecycle documentation

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-boot#20932]
The YAML in Kubernetes Container Lifecycle documentation should provide more context about where the user should place this YAML

https://docs.spring.io/spring-boot/docs/2.3.0.M4/reference/html/deployment.html#cloud-deployment-kubernetes-container-lifecycle

For a novice they might now know that this belongs in the podspec of the deployment yaml

**Comment by scottfrederick** [comment]
See https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#define-poststart-and-prestop-handlers
