### ISSUE TITLE
Switching default to include layers index for fat jar

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#20983]

**Comment by philwebb** [comment]
We'd need a Gradle API to switch off support. Since this is quite late for 2.3, we'll reassess in 2.4

**Comment by bclozel** [comment]
We also need to decide whether we should include the layertools classes to the fat jar, or just the idx file.

**Comment by wilkinsona** [comment]
Looking at #22195 caused me to notice that there are a few places in the Gradle plugin, javadoc for example, where it reads as if layers are disabled by default. Re-opening so that we can address those.

**Comment by bclozel** [comment]
It seems that both layers.idx and layertools are included in the fat jar by default now. You can only exclude the layertools from the jar explicitly.

I know that layertools isn't that big, but in this case should this be included with the launcher? I'm a bit confused by this situation.

**Comment by mbhave** [comment]
I thought it made sense to include layertools by default if layers.idx was present by default as well. I'm not sure what you mean by 

> but in this case should this be included with the launcher?

but we can discuss this on the next call.

**Comment by snicoll** [comment]
> I'm not sure what you mean by

The use case we want to promote is CNB and our build image build integration. This does not require layertools  so that seems a bit strange to include it by default. 

This would break users creating docker image and relying on that when upgrading to 2.3 but they'd have to change the `enabled` flag to `includeLayerTools`. That doesn't sound too bad to me.

**Comment by snicoll** [comment]
We've discussed this and we concluded that offering a good out-of-the-box experience for both CNB users (via our build image task in the Maven and Gradle plugins) as well as those who prefer to craft their `Dockerfile` themselves is important. Advanced users can opt-out for layers, the layertools or both via configuration.
