### ISSUE TITLE
Remove deprecated configuration properties

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#20991]
Hi,

I just noticed that the deprecated `server.connection-timeout` was deprecated in 2.1.x already (see #18473) . While relatively late in the 2.3.x release, I was wondering if we could remove it still for 2.3.x?

If the decision is made to remove it, I'm happy to do it in a PR. Let me know what you think.

Cheers,
Christoph

**Comment by snicoll** [comment]
Thanks for the nudge @dreis2211. I've noticed additional properties that should have been cleaned up from the `2.2.x` release: 

* `server.is-use-forward-headers`
* `server.tomcat.max-http-post-size`
* `server.jersey.max-http-post-size`

Removing `connect-timeout` seems a no brainer to me but I do wonder about those three so late in the 2.3.x release indeed. Flagging for team attention to see what the rest of the team think.

**Comment by dreis2211** [comment]
I think they were missed because they didn't have a `@deprecated since 2.1.x`

**Comment by snicoll** [comment]
Those 3 were deprecated in `2.2.x` but I think you're right. I've added a comment to that effect in https://github.com/spring-projects/spring-boot/issues/20812

**Comment by dreis2211** [comment]
On a deeper look, I think connection-timeout can't be removed as there is no replacement for undertow :/
