### ISSUE TITLE
Add support for publishing docker images to a registry

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21001]
Currently we don't have the option to publish a locally built docker image to a remote repository. You can do it using the docker CLI, but it would be nice to have some built in support.

**Comment by jayanth-iyer** [comment]
Will there be any support to create K8s manifests automatically -skeletons - just using the mvn command - part of native build pack? Later the developer can just add the values and add and remove the keys from the yaml
Does it even make sense to add this support? - want to understand

**Comment by jorgemoralespou** [comment]
I don't think this use case should be something the spring-boot maven plugin should do. If it did, shouldn't it also need to include goals to deploy the application/image into different platforms? 
I think that users should stick to using multiple plugins rather than have one single plugin that does it all (not saying can't be provided by spring-boot). I saw that pattern in fabric8 maven plugin, and they had to slowly rollback and break that plugin into smaller ones, more single purposed.
My 2 cents.

**Comment by jorgemoralespou** [comment]
Then my bad, as there's no description in the issue, it might seem confusing for others as it's been for me. Maybe @philwebb can add the description so people understand better what they are voting/commenting on.

**Comment by philwebb** [comment]
Sorry about that, I threw in the issue for my own reference and wasn't expecting any votes/comments. I've added a brief description.

**Comment by jorgemoralespou** [comment]
I think then thy my comment is not outdated. https://github.com/spring-projects/spring-boot/issues/21001#issuecomment-686548109

**Comment by philwebb** [comment]
@jorgemoralespou Can you elaborate a bit more on the problems we might face? I was originally thinking we might be able to shell out and call `docker push`. I think that's currently how jib deals with it.

**Comment by jorgemoralespou** [comment]
Well, there's 2 sides:
- Technical: You'd need to be able to support private and insecure registries, and you'd need to interface with Docker on Windows/Mac/Linux in different ways, so better to not shell out to docker but rather use a library that can deal with the pushing direclty.
- Strategically: To me this is the real deal. If the spring-boot plugin start doing this, then what else? where's the line of what should be done in this plugin vs other plugins? To be honest, maven/gradle users know how to configure multiple plugins and how to call them, so what would be the difference of doing something like: `mvn spring-boot:build-image spring-boot:push-image` vs `mvn spring-boot:build-image other-plugin:push-image`.? I have in mind fabric8 times, now [jKube](https://www.eclipse.org/jkube/) and they struggle and broke it down as it was doing just way too much in a single place. Single purposed  plugins that can be composed should be favoured in my opinion.

**Comment by philwebb** [comment]
If there was a single purpose Maven and Gradle plugin that we could lean on and perhaps automatically configure (so you don't need to give the image tag) that would be an ideal option. The only one I found when looking previously was jib, and pushing isn't really a stand-alone feature. I also didn't have much luck finding a Java library that can talk to the registry, only [Go](https://github.com/google/go-containerregistry) and [Python](https://github.com/google/containerregistry) seem to exist. Perhaps [RegistryClient](https://github.com/GoogleContainerTools/jib/blob/c9fb349bf09db0e09724aa97657c695cda990b37/jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java#L57) from jib will be extracted into a library at some point.

**Comment by scottfrederick** [comment]
Images can be [tagged](https://docs.docker.com/engine/api/v1.39/#operation/ImageTag) and [pushed](https://docs.docker.com/engine/api/v1.39/#operation/ImagePush) using the Docker daemon API, letting the daemon do all the work. We're in the process of [adding support for authenticating to a registry](hub.com/spring-projects/spring-boot/pull/22972) from the daemon, which should suffice for pushing also. 

We've generally tried to maintain parity between the Boot plugins and the `pack` CLI. `pack` supports pushing to a registry with a `pack build --publish` option. I don't think there's much risk of scope creep with just adding a comparable feature to the Boot plugins.

**Comment by theHilikus** [comment]
the way the maven lifecycle is structured, it seems to me that publishing should be separate from building. `build-image` attaches to `package` stage, which makes sense, but not publishing. That should be done in the maven `deploy` phase. I haven't been able to find a way to only build in `package` and only publish in `deploy`. Am I missing something?

**Comment by scottfrederick** [comment]
@theHilikus There is some discussion of this in #26187. We've tried to keep the focus of the Spring Boot build plugins on Cloud Native Buildpacks integration, and avoid adding features to cover the full lifecycle of an OCI image.

**Comment by theHilikus** [comment]
I missed that ticket. thank you
