### ISSUE TITLE
Accessing Properties in ImportBeanDefinitionRegistrar's 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2100]
I am trying to create an autoconfiguration for registering mutliple datasources. Using an ImportBeanDefinitionRegistrar seems best option to me. However I could not find a solution to access properties below in ImportBeanDefinitionRegistrar. I can not use @Bean annotation since I need to declare multiple datasources. I also need to name beans with a special qualifier.

```
spring:
    datasources:
        <data-source-qualifier #1>:
            primary: true
            driverName:
            url: 
            username: 
            password::
        <data-source-qualifier #2>:
            driverName:
            url
            username
            password:
```

I think that this might require a change in Spring Core as well. What do you think?

**Comment by javaty** [comment]
Hi Cemo,

I'm having similar requirement of creating beans from Properties at the Runtime in SpringBoot application, did you manage to solve your issue. Can you please share the solution.
