### ISSUE TITLE
Documentation on Layering Docker Images has a broken link to the Maven Plugin doc

### ISSUE THREAD

**Issue by ciberkleid** [spring-projects/spring-boot#21019]
Broken link

In this section of the docs:
https://docs.spring.io/spring-boot/docs/2.3.0.M4/reference/htmlsingle/#layering-docker-images

The last sentence has two links, one for Maven and one for Gradle. The Maven link is broken (returns 404 Not Found). Instead of:

https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/html//#repackage-layered-jars

It should be:

https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/reference/html//#repackage-layered-jars

**Comment by dreis2211** [comment]
I guess this is already fixed via #20818 . See the latest snapshot docs at https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#layering-docker-images

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. There's no 404 now, but it looks like the anchor's incorrect. I think it should be linking to https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/maven-plugin/reference/html/#repackage-layers.

**Comment by dreis2211** [comment]
You're of course right. Shall I open a PR or will you do it?

**Comment by wilkinsona** [comment]
A PR would be great. Thanks.

**Comment by wilkinsona** [comment]
Closing in favour of #21033.
