### ISSUE TITLE
@ElementCollection(fetch = EAGER) doesn't work properly with @EntityGraph

### ISSUE THREAD

**Issue by maystrovyy** [spring-projects/spring-boot#21011]
I have a query that selects entities "*A*" with joining "*B*" entity via @EntityGraph(attributePaths = {"b"}), which has **eagerly** Set<Long> by @ElementCollection(fetch = EAGER).
So, on version **2.2.4** this works correctly, but since version 2.2.5 (including 2.2.6) I get a LazyInitializationException.
I've found a similar [issue](https://stackoverflow.com/questions/61141446/why-does-entitygraph-not-load-eager-scince-spring-version-2-2-5) on StackOverflow.

**Comment by snicoll** [comment]
Thanks for the report but that's nothing we can fix in Spring Boot. Please reach out to the Hibernate team for support. `2.2.4.RELEASE` uses `5.4.10.Final` while `2.2.5.RELEASE` uses `5.4.12.Final`. You may want to downgrade Hibernate to `5.4.10.Final` to see if that changes anything for you. 

If it does you may want to search for an issue in the Hibernate issue tracker.
