### ISSUE TITLE
Long default values in properties make properties tables render poorly

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#21051]
e.g.

>%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx} 

in `logging.pattern.console`

https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/reference/html/appendix-application-properties.html#core-properties

**Comment by philwebb** [comment]
I think this must be related to the new CSS. I've opened https://github.com/spring-io/spring-doc-resources/issues/43

**Comment by bclozel** [comment]
Fixed in the latest SNAPSHOTs of the library. Closing this issue in favor of #21057
