### ISSUE TITLE
Failure to find org.springframework.boot:spring-boot-test-support:jar:2.2.6.RELEASE

### ISSUE THREAD

**Issue by pratham-m** [spring-projects/spring-boot#21059]
Hi Team,

I am getting below error while building the source code.

[ERROR] Failed to execute goal on project spring-boot-actuator-autoconfigure: Could not resolve dependencies for project org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.2.6.RELEASE: Failure to find org.springframework.boot:spring-boot-test-support:jar:2.2.6.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

--------------
Using release **2.2.6**
commands used for build, after cloning the tag:
`cd spring-boot-project/spring-boot/`
`mvn clean install`

Am I missing something? Any help would be appreciated. Thanks.

**Comment by wilkinsona** [comment]
`spring-boot-test-support` is an unpublished support module that must be built and installed locally before you can build individual modules. Please refer to the [contributing guidelines](https://github.com/spring-projects/spring-boot/blob/2.2.x/CONTRIBUTING.adoc#working-with-the-code) for the recommended way to build the project.
