### ISSUE TITLE
Fix naming of IncludExcludeEndpointFilter

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#21061]
Hi,

I just stumbled over `IncludExcludeEndpointFilter` which seems to be rather an `IncludeExcludeEndpointFilter`.

I was wondering if we should deprecate the former. And if so - in which branch.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Good catch, @dreis2211. Thank you. It's [new in 2.2.7](https://github.com/spring-projects/spring-boot/commit/df26e2460582102b1ea82b10722afbe79064643a) which thankfully hasn't been released yet. I think we can just rename it.

**Comment by dreis2211** [comment]
Should I or will you do it?

**Comment by wilkinsona** [comment]
Thanks for the offer. I'll take care of it.

**Comment by philwebb** [comment]
Sorry about that 🤦
