### ISSUE TITLE
Maven plugin examples for build-image command line properties are incorrect

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#21078]
The [`2.3.0.M4` docs](https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/reference/html/#build-image-examples) contain these examples: 

```
$ mvn spring-boot:build-image -Dspring-boot.build-image:builder=mine/java-cnb-builder
$ mvn spring-boot:build-image -Dspring-boot.build-image:imageName=example.com/library/v1
```

There should be a `.` instead of `:` between `-Dspring-boot.build-image` and the property name.

**Comment by venkateshdatta1993** [comment]
Hey @scottfrederick

Is this one open for contribution?
Can I try it?

**Comment by snicoll** [comment]
@venkateshdatta1993 thanks for the offer. We were discussing of also reviewing the examples so that they are consistent for all examples so it would be better we take care of it. Thanks anyway.

**Comment by venkateshdatta1993** [comment]
@snicoll Sure. Thank you.
