### ISSUE TITLE
Add Period converter support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21080]
As suggested by @odrotbohm, It would be nice to have a `Period` converter similar to the `Duration` one we provide.

**Comment by snicoll** [comment]
When we look at this, make sure to update the annotation processor to handle Period if necessary.

**Comment by eddumelendez** [comment]
Hi guys, can I take this one? May a friend of mine would be interested too so we can pair. WDYT?

**Comment by mbhave** [comment]
@eddumelendez Sure, thank you.

**Comment by Grubhart** [comment]
Hi everibody!!! I will work on this with @eddumelendez

**Comment by philwebb** [comment]
Closing in favor of PR #21136
