### ISSUE TITLE
 Bug report : RepositoryRestResource annotated classes start returning 404 errors

### ISSUE THREAD

**Issue by yanndemel** [spring-projects/spring-boot#21089]
After upgrading to spring-boot 2.2.6 : PagingAndSortingRepository classes annotated with @RepositoryRestResource started randomly to return 404 errors... Rollbacking to version 2.2.5 solved the problem.

I have found on stackoverflow other people who encountererd the same issue : https://stackoverflow.com/questions/61262802/repositoryrestresource-resources-started-returning-404-errors-after-running-for

**Comment by philwebb** [comment]
I think the root cause of this is [DATAREST-1502](https://jira.spring.io/browse/DATAREST-1502) but @mp911de can probably confirm. Can you please try the latest Spring Boot SNAPSHOT and let us know if it's fixed?

**Comment by mp911de** [comment]
Confirming that the issue is addressed with [DATAREST-1502](https://jira.spring.io/browse/DATAREST-1502).
