### ISSUE TITLE
PortInUseException can be thrown when server address is wrong

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-boot#21101]
I'm using Spring Boot 2.2.6 with the embedded Tomcat server.

When I set the server.address property to a number then it seems to be a valid InetAddress.

For example:

    server.address=12346

Unfortunately then I get a this error message:

> Web server failed to start. Port 8080 was already in use.

This is very misleading because the error is not that Port 8080 is in use but that the IP address is invalid.

Can you improve this error message?

**Comment by philwebb** [comment]
Interesting find, thanks for reporting it.
