### ISSUE TITLE
Review support and documentation for preventing compile-only dependencies from being packaged in fat jars

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21109]
The reference documentation [recommends](https://docs.spring.io/spring-boot/docs/2.2.6.RELEASE/reference/htmlsingle/#boot-features-custom-starter-module-autoconfigure) using `<optional>true</optional>` when declaring a dependency on `spring-boot-autoconfigure-processor` but, following a discussion with @odrotbohm, it's apparent that this doesn't prevent the dependency from being packaged in the fat jar. The same goes for a Lombok dependency when generated by start.spring.io which also uses `<optional>true</optional>`. The Maven plugin's documentation [recommends an exclusion-based approach instead](https://docs.spring.io/spring-boot/docs/2.2.6.RELEASE/maven-plugin/examples/exclude-dependency.html).

We should review the current documentation and Maven plugin behaviour and make the updates that are necessary to make things consistent. We should also verify how things behave with Gradle. I believe it will not have the same problem if the `annotationProcessor` configuration is used, but we should double-check. Once this has been straightened out, we may need to make some updates to start.spring.io as it currently uses `<optional>true</optional>` with Lombok.

**Comment by mpens** [comment]
Hi @wilkinsona you could guide me, where can i  find the doc?. I would like to take this issue

**Comment by snicoll** [comment]
Closing in favor of PR #22000
