### ISSUE TITLE
Add a default method to Lettuce/JedisClientConfigurationBuilderCustomizer

### ISSUE THREAD

**Issue by zmapleshine** [spring-projects/spring-boot#21125]
the old issue #21120

A pull request was submitted before but it involves a change in the interface signature and thus destroys the original code. 

So I tried to modify the interface again, adding the default method has reached the problem of custom multiple data source clientResource and attribute matching.

A new pull request will be submitted later..

**Comment by philwebb** [comment]
I'm not keen to add additional methods to the `JedisClientConfigurationBuilderCustomizer` interface. I think we need to understand your issue a little more, let me reopen #21120 and we can discuss things there.
