### ISSUE TITLE
Some entries in the tables of configuration properties are incomplete

### ISSUE THREAD

**Issue by nikmanzotti** [spring-projects/spring-boot#21131]
While discussing some documentation improvements (see #21077 and #21121), I've noticed that several common application properties have no description in the [current docs dedicated section](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-properties).
However, all these properties have the descriptive comment, as visible in [version `2.1.x` docs](https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/common-application-properties.html) which was using a different "template" for rendering documentation.

Some properties in this situation are:

- `spring.info.git.location`
- `spring.data.rest.detection-strategy`
- `spring.datasource.initialization-mode` (see screenshots below)
- `spring.elasticsearch.rest.uris`
- `spring.mongodb.embedded.features`

After a quick look at the 2.1.x doc page, it seems that all the properties have a comment from which the description should be obtained. 

This should be further investigated (maybe also checking the `Default Value` field too), but I have no clue on where to find the code which does this "description extraction". If someone can point me in the right direction, I'll try to have a look.

_**`spring.datasource.initialization-mode` - Current doc**_
![image](https://user-images.githubusercontent.com/34871840/80275325-c68ac180-86e0-11ea-9238-8d5a5aeca3ea.png)

_**`spring.datasource.initialization-mode` - 2.1.x doc**_
![image](https://user-images.githubusercontent.com/34871840/80304586-47b48800-87b7-11ea-8dc7-948a9a9220c9.png)

**Comment by snicoll** [comment]
FTR, that affects only `2.2.x` as I can see those properties are correctly documented on `master`.
