### ISSUE TITLE
Upgrade to Glassfish Jaxb 2.3.3

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21195]

**Comment by snicoll** [comment]
This upgrade brings the activation-api via a `com.sun` groupId. We need to figure out what to do as it breaks verification for the JPA starter.

**Comment by wilkinsona** [comment]
The runtime module of the JAX-B RI switching from the Activation API to the complete runtime in [this commit](https://github.com/eclipse-ee4j/jaxb-ri/commit/69339bf9f5ac2f49f932391d66abc75fe1f0ad85#diff-1e0a06fb1ab2cd6c7221d3a0682e7fdd). It's not clear why that change was made but we're going to have to live with it somehow. Some options:

1. Drop the Activation API from the starter and allow on them being provided by the runtime jar
2. Tolerate the duplicate classes in the JPA starter that result from having both the API jar and the runtime jar on the classpath
3. Still with JAX-B 2.3.2.

Of these three, the first seems to be the least bad. It will leave users relying on our starters and dependency management with a clean classpath that does not have duplicates. If a user downgrades to 2.3.2, things should continue to work as the JAX-B runtime's transitive dependency on the Activation API will then be in place.

**Comment by merusso** [comment]
This dependency upgrade broke our Java 8 application unfortunately.

I now see the following exception:
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.regions.ccs.integration.tsys.core.TsysCoreClientImpl]: Factory method 'tsysCoreClientImpl' threw exception; nested exception is java.lang.ClassCastException: com.tsys.xmlmessaging.cc.DateTime$JaxbAccessorF_value cannot be cast to com.sun.xml.bind.v2.runtime.reflect.Accessor
```

I can resolve this issue by excluding this dependency in our builds:
```groovy
configurations {
    all {
        // jaxb-runtime v2.3.3 is incompatible with our app
        exclude group: 'org.glassfish.jaxb', module: 'jaxb-runtime'
    }
}
```

Judging by my experience, this is a fairly disruptive change for a patch version upgrade. I'd be very interested to know why the JAX-B RI changed this transitive dependency in a patch version.

**Comment by wilkinsona** [comment]
@merusso Sorry for the inconvenience. If you haven't already done so, can you please raise an issue against the RI: https://github.com/eclipse-ee4j/jaxb-ri/issues?

**Comment by jordanms** [comment]
I created this question about this upgrade: https://stackoverflow.com/questions/66856141/spring-boot-2-2-7-migration-breaks-jaxb-unmarshal
