### ISSUE TITLE
Perform JDBC URL validation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21215]
Section 4.2 of the [JDBC spec](https://download.oracle.com/otn-pub/jcp/jdbc-4_2-mrel2-eval-spec/jdbc4.2-fr-spec.pdf) states that a JDBC URL's format is `jdbc:<subprotocol>:<subname>`. We could perform some validation of the URL that's bound to `DataSourceProperties` so that we can fail fast if it doesn't meet this requirement rather than waiting for the connection pool to deal with it.

**Comment by philwebb** [comment]
I'm a bit worried that there might be a connection pool that bends this rule. Is the problem with letting the connection pool deal with it that it fails after the app starts?

**Comment by wilkinsona** [comment]
It's more theoretical than anything. It came up in a discussion with @odrotbohm.

**Comment by philwebb** [comment]
We discussed this today but we're not sure we should enforce this rule ourselves. We generally treat properties like this as opaque values and expect the relevant delegates to deal with errors.
