### ISSUE TITLE
Expose additional CNB builder options with build plugins

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#21258]
The CNB builder infrastructure supports the options `cleanCache` and `verboseLogging`, which control builder behavior. The Maven and Gradle plugins should expose these options to the user and pass them to the builder.

**Comment by wilkinsona** [comment]
`BootBuildImage` in the Gradle plugin already has properties for `cleanCache` and `verboseLogging` and applies them to the `BuildRequest`:

https://github.com/spring-projects/spring-boot/blob/1abe0f16d0575e53464182935e6ba8a7646fd265/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/bundling/BootBuildImage.java#L233-L234

**Comment by wilkinsona** [comment]
`Image` in the Maven plugin, which is used by `BuildImageMojo` has the same functionality:

https://github.com/spring-projects/spring-boot/blob/1abe0f16d0575e53464182935e6ba8a7646fd265/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/Image.java#L92-L93

**Comment by wilkinsona** [comment]
As far as I can tell, this has already been implemented. @scottfrederick please re-open this if I've misunderstood.
