### ISSUE TITLE
Add support to Bomr for aligning a dependency version with the one pulled in by an external dependency

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21279]
It'd be useful for things like the NoSQL clients that Spring Data modules depend upon if we could configure Bomr to verify that the version in `spring-boot-dependencies` aligns with the version that's pulled in by an external dependency

**Comment by snicoll** [comment]
Would it be still possible to show all versions matching the policy? It happens quite frequently that a bug fix release of a driver was done after the Spring Data release and the team would like us to pick this one rather than the one they have in the bom.

**Comment by wilkinsona** [comment]
Yes, that would be possible. We could use something similar to the upgrade policy to control the versions will be suggested.

**Comment by wilkinsona** [comment]
We can't easily implement this at the moment as we currently need to use a separate project to resolve all of the constraints defined in `spring-boot-dependencies`. We need those constraints so that we know which version of an external dependency we should be looking at when aligning our version for a dependency with its version of that dependency. I've opened https://github.com/gradle/gradle/issues/13162.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/34114 has taken care of this.
