### ISSUE TITLE
Delete ErrorProperties.IncludeStacktrace

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21286]
Since it's only used for binding, in 2.4 we should be able to delete `ErrorProperties.IncludeStackStrace` and replace it with `ErrorProperties.Include`

**Comment by snicoll** [comment]
`ON_TRACE_PARAM` is deprecated since 2.3 so we won't be able to get rid of it before `2.5.x`. Moving to the next feature release.

**Comment by quaff** [comment]
`ErrorProperties.IncludeStacktrace` is back again by accident?

https://github.com/spring-projects/spring-boot/blob/7ada32ca778bc3f34d27920d3f973cfb39a69ed6/core/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ErrorProperties.java#L120-L137

**Comment by philwebb** [comment]
Thanks @quaff, I've opened https://github.com/spring-projects/spring-boot/issues/47235

**Comment by snicoll** [comment]
Ugh, that's really odd. Thanks for reporting this!
