### ISSUE TITLE
Extract EnvironmentPostProcessor logic from ConfigFileApplicationListener

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21299]
It's bit odd that `ConfigFileApplicationListener` is currently the thing that invoked `EnvironmentPostProcessors`. I feel like the logic should live in the `org.springframework.boot.env` package.

**Comment by bono007** [comment]
Hi @philwebb - I too have thought this about CFAL for a while now. I would love to take this one unless you are already planning on moving out on it?

**Comment by bono007** [comment]
Also, what are your thoughts about inlining the invocation of the EPPs in SpringApplication like what is done for the ACIs currently?

**Comment by wilkinsona** [comment]
Thanks for the offer, @bono007. We're in the early stages of designing a revamp of configuration property file loading and profile support for Spring Boot 2.4. We won't be able to tackle this issue until that work has been completed.

**Comment by bono007** [comment]
I look forward to seeing the revamp. Thanks for the info @wilkinsona .

**Comment by wilkinsona** [comment]
This has been tackled in https://github.com/spring-projects/spring-boot/issues/22497.
