### ISSUE TITLE
@Column with name attribute not working property on entities

### ISSUE THREAD

**Issue by Kacper86** [spring-projects/spring-boot#2129]
Hi,

I'm using spring-boot-starter-parent and spring-boot-starter-data-jpa (version 1.1.9). I found some strange behaviour on entities. When I specify @Column(name = "myName") then jpa is generating sql query containing "my_name" column (so it changes the name I provide).

Other examples:
- @Column(name = "aa") -> sql query uses column "aa" -> correct
- @Column(name = "aA") -> sql query uses column "aa" -> incorrect
- @Column(name = "aAa") -> sql query uses column "a_aa" -> incorrect

When I put "spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy" into application.properties, then everything works properly. But I don't think that the initial behaviour is correct.

Greetings,
Kacper86

**Comment by bassemZohdy** [comment]
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

not working with me on Spring Boot 1.2.2 will check the reason
but why naming-strategy work while there is @Column with name attribute, for me it is bug, as I already mentioned the name of column so the naming-strategy shouldn't apply here, I'll check how to do it and updates you.

**Comment by bassemZohdy** [comment]
I found the issue it is in ImprovedNamingStrategy if you want to solve it without details use DefaultNamingStrategy instead ImprovedNamingStrategy as below

spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultNamingStrategy

Details:
There are 2 methods in NamingStrategy interface propertyToColumnName and columnName, first one called if you didn't specify name in @Column and 2nd one called if you specify name in @Column.

in ImprovedNamingStrategy both change the name from camel to _ format while in DefaultNamingStrategy it is returning name as it is in 2nd method which is from my point of view the correct behavior.

**Comment by philwebb** [comment]
Thanks for the analysis. The `DefaultNamingStrategy` doesn't convert to the `_` format at all if I remember correctly.

I'm think there will be side-effects if we change the `columnName` method in `SpringNamingStrategy` so I'd rather leave this as it is. I think the change should be in the Hibernate `ImprovedNamingStrategy` class if anywhere, but I imagine that the Hibernate team will also not be keen to change things.

**Comment by bassemZohdy** [comment]
I Already pulled class there and update it waiting for their feedback.

**Comment by mtkuyucu** [comment]
Thanks it worked for me 
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultNamingStrategy

**Comment by arlago** [comment]
I am using this config file, and the @Table(name = "asdf") annotation is always ignored.
spring:
  data.rest.base-uri: api/v1

  datasource:
    url: jdbc:postgresql://localhost:5432/qwer
    username: qwer
    password: qwer
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.hbm2dll.auto: update

**Comment by holdlg** [comment]
oh, awesome.
spring boot 1.3.3  `spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultNamingStrategy`

**Comment by akhilsnet** [comment]
I am trying to deploy the spring boot application in WAS Liberty server and I am facing the same issue. I have tried with all the following ways, however still its not been resolved, its expecting the actual name instead of the available snake case.

spring.jpa.hibernate.naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy 
spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultNamingStrategy

**Comment by jacks808** [comment]
At spring boot 1.4.1 add those two config will fix this issue:
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

**Comment by Surendev** [comment]
I have some problem with Spring-boot-starter-data-jpa 1.5.2.
None of the solutions,that are written above not working.
Can someone help me with this.

**Comment by orrymr** [comment]
@Surendev solution helped (Spring boot 1.5.3)

**Comment by alan-czajkowski** [comment]
it is totally unacceptable that `@Column(name = "...")` is being ignored, this should always override any naming strategy provided, please re-open this issue

**Comment by semteXKG** [comment]
I'm aware that changing this behaviour now will cause havoc but this issue cost me half an hour till I figured it out what happened to my Column name annotations... totally unexpected

**Comment by alaxcc** [comment]
@philwebb and other guys,

I find there is  no key "spring.jpa.hibernate.naming-strategy",and use 
`spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl` is OK.

validate on spring boot M2.

**Comment by wilkinsona** [comment]
For the record, as far as I can tell, there's no way to differentiate between `@Column(name="…")` and `@Column` in a naming strategy. Hibernate's `Ejb3Column` class makes identical calls to the physical naming strategy in both cases:

- [`@Column(name="…")`](https://github.com/hibernate/hibernate-orm/blob/47382f69cc282a3df1bc373300eeeeee5237b81f/hibernate-core/src/main/java/org/hibernate/cfg/Ejb3Column.java#L304)
- [`@Column`](https://github.com/hibernate/hibernate-orm/blob/47382f69cc282a3df1bc373300eeeeee5237b81f/hibernate-core/src/main/java/org/hibernate/cfg/Ejb3Column.java#L311)

If anyone who's commented on this issue would like a naming strategy to apply to `@Column` but not apply to `@Column(name="…")`, then I would recommend opening a Hibernate issue.

**Comment by langley-agm** [comment]
Not sure if related or not but I couldn't fix this with the options provided in the Thread.

![image](https://user-images.githubusercontent.com/10603341/38222107-d6737e02-3697-11e8-8472-84b263a334e4.png)

![image](https://user-images.githubusercontent.com/10603341/38222131-f5b0eeda-3697-11e8-927e-f2a7f6598c11.png)

**Comment by alan-czajkowski** [comment]
@langley-agm the complete solution for Spring Boot in your application configuration:

**YAML:**
```
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
```

**Properties:**
```
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
```

@philwebb please re-open this issue as there is strong demand to fix this issue, you can imagine the tons of hours (and money) wasted on this issue alone

**Comment by wilkinsona** [comment]
@alan-czajkowski Please see my [comment above](https://github.com/spring-projects/spring-boot/issues/2129#issuecomment-346312535). As far as we know, Hibernate does not support what you are asking for, making it pointless to re-open this issue.

**Comment by langley-agm** [comment]
@alan-czajkowski 

I did try those but it didn't work, apparently the issue is that Hibernate will only consider either all @Columns in properties or all @Columns in methods, it won't work if you mix them up in a single class.

**Comment by philwebb** [comment]
@alan-czajkowski I'm more than happy to re-open this one if we can find a way to fix it. I've raised [HIBERNATE-160](https://issues.jboss.org/browse/HIBERNATE-160) to see if there's anything that the Hibernate team can do. Feel free to comment or vote on that issue.

**Comment by alan-czajkowski** [comment]
everybody please vote for [HIBERNATE-160](https://issues.jboss.org/browse/HIBERNATE-160)

**Comment by end-user** [comment]
Is this issue also affecting `@Table(name="...")` and `@DiscriminatorColumn(name="...")` and other naming annotations?

**Comment by prakashtjp** [comment]
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

It worked for me, Thankyou

**Comment by garrydias** [comment]
**My Problem WITHOUT ImplicitNamingStrategyLegacyJpaImpl property set**

- @Column(name = "aa") -> sql query uses column "aa" -> correct

- @Column(name = "aA") -> sql query uses column "aa" -> incorrect

- @Column(name = "aAa") -> sql query uses column "a_aa" -> incorrect

**My Problem WITH ImplicitNamingStrategyLegacyJpaImpl property set**

- @Column(name = "aa") -> sql query uses column "aa" -> correct
- @Column(name = "aA") -> sql query uses column "aa" -> incorrect
- @Column(name = "aAa") -> sql query uses column "aaa" -> incorrect
- @Column(name = "[aAa]") -> sql query uses column "aAa" -> correct (my goal)

My solution only worked after this::

set application.properties like this:
`spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl`

... and

`@Table("[CamelCaseTable])` on entity class

AND

`@Column("[camelCaseAttribute]")` on entity class attribute

**My Conclusions**
Only `spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl` should be sufficient to respect what @Kacper86 expected. I've been debuging ImplicitNamingStrategyLegacyJpaImpl and everything respects the classes and attributes names as it is, without annotation trickies. 


Spring Boot 2.2.3.RELEASE
Database: Postgres 12

**Comment by anilkumar-ak** [comment]
> @langley-agm the complete solution for Spring Boot in your application configuration:
> 
> **YAML:**
> 
> ```
> spring:
>   jpa:
>     hibernate:
>       naming:
>         implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
>         physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
> ```
> 
> **Properties:**
> 
> ```
> spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
> spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
> ```
> 
> @philwebb please re-open this issue as there is strong demand to fix this issue, you can imagine the tons of hours (and money) wasted on this issue alone

thanks is work for me

**Comment by djBo** [comment]
It's a shame this is still a problem in 2020 :(

I ran into this today, trying to map to an existing schema using obvious "incorrect" naming conventions for one of it's columns.
The issue I have with the solutions provided, is that they change the naming strategy at a global level. This now requires me to adjust all my model classes and add @Table/@Column annotations to each and every field to accommodate that change. I just need this **one** entry to be case sensitive in the way the schema tells me, not the other way around.

To be fair, the whole idea with the @Column name attribute, it that it should be used as an override, and used as is. That's what it is there for, to provide an alternative to any existing naming strategy layer. It is clearly stating: when in doubt, use **this**.

It's fine if an non-annotated field like "myType" ends up as "my_type". But when I explicitly annotate this entry with @Column("myType"), I am giving clear information on what I **really** want. Which is not "my_type" obv.

This is why we can't have nice things.

**Comment by wilkinsona** [comment]
Unfortunately, there's nothing we can do in Boot to fix this without a change in Hibernate. I've added the blocked label to hopefully make that more clear.

If you'd like us to be able to fix this in the future, please take a moment to vote for [HIBERNATE-160](https://issues.redhat.com/browse/HIBERNATE-160).

**Comment by alan-czajkowski** [comment]
as of this date, there are only 12 votes for this issue: [HIBERNATE-160](https://issues.jboss.org/browse/HIBERNATE-160)
come on guys and girls, we can do much better than that

voting ensures that issues get top priority and visibility, please take the time to go to that link and vote (create an account on that JIRA if you have to -- it is worth it), please do not be lazy, voting works

**Comment by hussienalbared** [comment]
spring boot 2.4.0
Hibernate ORM core version 5.4.23.Final
That worked for me
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

**Comment by LuisMCunha** [comment]
This too made me lose a lot of hours or scouring the internet, the resolution mentioned in this thread solved the issue, but it's crazy that it happens in the first place.

**Comment by alan-czajkowski** [comment]
because this issue tracker has been shut down: [HIBERNATE-160](https://issues.redhat.com/browse/HIBERNATE-160)
I have re-created the issue here: [HHH-14584](https://hibernate.atlassian.net/browse/HHH-14584)

please go ahead and vote for this issue in the new issue tracker

**Comment by MirosmarOliveira** [comment]
spring boot V.5.3.23 
the same problem, and the same  "solution"
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

**Comment by wilkinsona** [comment]
@MirosmarOliveira That's to be expected. Please vote for https://hibernate.atlassian.net/browse/HHH-14584 is you'd like the situation to change.
