### ISSUE TITLE
Implementation attributes are missing from Maven shade transformer configuration in spring-boot-starter-parent

### ISSUE THREAD

**Issue by pse-sonic** [spring-projects/spring-boot#21304]
Hi,
I've noticed that the **spring-boot-starter-parent** probably contains an invalid configuration of the maven-shade-plugin. There is an "empty" transformer `delegate.transformer('')` which causes a NoSuchMethodException in some cases. The configuration of the transformers has been changed from 2.2.x to 2.3.x.

**Comment by wilkinsona** [comment]
Can you please provide some more information about the `NoSuchMethodException`? There's an accidental empty `<transformer></transformer>` in the configuration, but I doubt that would cause a `NoSuchMethodException`.

**Comment by pse-sonic** [comment]
My fault - The empty transformer is also a part of the 2.2.x configuration of the shade plugin.

I figured out that the problem is caused by the missing attribute **implementation** for **all** listed transformers. If I override the shade plugin configuration and add these attributes to the transformers (based on the 2.2.x configuration) the problem is solved.
