### ISSUE TITLE
Consider adding an extra batch property: spring.batch.table-prefix

### ISSUE THREAD

**Issue by cmousset** [spring-projects/spring-boot#2132]
My company uses db2/as400. We have a different scheme for batch tables and need to set the tableprefix property on both JobExplorer and JobRepository.

I achieved this by copying org.springframework.boot.autoconfigure.batch.BasicBatchConfigurer to our own java package in order to set the property. 

I would like to be able to set the tableprefix via application.properties.

**Comment by dobromyslov** [comment]
I also want it to be implemented. I use PostgreSQL and can not use spring.batch out of the box.

**Comment by snicoll** [comment]
@cmousset how about this PR?

**Comment by dobromyslov** [comment]
Found solution. It's enough to implement a custom BatchConfigurer and to set it in the context.
