### ISSUE TITLE
visit jsp page on both server.port and management.server.port

### ISSUE THREAD

**Issue by xuchang-x** [spring-projects/spring-boot#21345]
here is my application.properties
`management.server.port=8080
server.port=8414`
and when i run my appliction, i can visit my jsp page on both 8080 & 8414
![image](https://user-images.githubusercontent.com/33126624/81246102-4b62cd00-9049-11ea-9d95-c5090b2cbac8.png)
but the restcontroller can work only on 8414 like this,
![image](https://user-images.githubusercontent.com/33126624/81246180-70efd680-9049-11ea-91c7-e0c43b521c6e.png)

here is the test code if you need
https://github.com/xuchang-x/monitor-test

**Comment by xuchang-x** [comment]
i think i can only visit jsp on 8414 for this config

**Comment by philwebb** [comment]
The sample you've provided doesn't serve any JSPs on either port. You have JSP files in `src/webapp` but you have `jar` packaging so this folder is ignored.

When you hit `localhost:8414/test` you see the response from your `@RestController`. When you hit `localhost:8080/test` you get a 404 as expected.
