### ISSUE TITLE
Spring data jpa shifts saved LocalDates back by one date after spring boot update 2.2.6 -> 2.2.7

### ISSUE THREAD

**Issue by Ejstn** [spring-projects/spring-boot#21362]
Hi, I have run into following issue after updating spring boot from 2.2.6 to 2.2.7:

When I save `LocalDate` with spring data jpa repository to mysql - for example:
`2020-05-08`, it is correctly written to database as `2020-05-08`.

But when I later want to retrieve it with the repository what I get back is shifted by one day backwards:
`2020-05-07`. This started to happen only after this update.

I made sure that the database is set to UTC:
![image](https://user-images.githubusercontent.com/22277875/81390143-41110380-911b-11ea-8e4c-2058079590de.png)
And I also set the application to the same timezone:

```
@ConfigurationPropertiesScan
@EnableScheduling
@SpringBootApplication
class EconomyApplication {

    @PostConstruct
    fun init() {
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
    }
}
```

This problem is also described previously by someone on [stackoverflow](https://stackoverflow.com/questions/54418827/mysql-date-changes-to-yesterdays-date-after-jpa-save)

**Comment by snicoll** [comment]
@Ejstn I am afraid there is nothing we can do about that. Spring Boot `2.2.7` upgraded to a new [version of the mysql driver](https://github.com/spring-projects/spring-boot/issues/21188). Please try to downgrade to `8.0.19` and see if that makes any difference.

**Comment by Ejstn** [comment]
@snicoll Thank you, you are right. I downgraded mysql connector to `8.0.19` and I dont get this issue. I will try to raise this issue to mysql connector maintainers.

**Comment by Ejstn** [comment]
@snicoll Thank you, you are right. I downgraded mysql connector to 8.0.19 and I dont get this issue. I will try to raise this issue to mysql connector maintainers.

**Comment by snicoll** [comment]
Thanks for the follow up
