### ISSUE TITLE
Upgrade to  use Groovy 3

### ISSUE THREAD

**Issue by drewtwitchell** [spring-projects/spring-boot#21368]
Groovy 3 resolves an issue where it caused the following:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (xxx.jar!/BOOT-INF/lib/groovy-all-2.4.12.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
See the Groovy ticket here: https://issues.apache.org/jira/browse/GROOVY-8339

With Spring Boot using an older version of Groovy we see these issues show up in our product as we are dependent on Spring Boot and it is your dependency causing these WARNINGS to show up.

**Comment by dreis2211** [comment]
There is #20119 that tracks the Groovy 3 upgrade already. I'm basically waiting for Spock 2.x to be released in order to complete that.
