### ISSUE TITLE
DataSourceInitializationConfiguration should back off if datasource initialization is disabled

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21363]
If an application has configured `spring.datasource.initialization-mode=never` we are still registering `DataSourceInitializerInvoker` and its post processor. It looks like ultimately they do nothing so  we should probably not register this infrastructure at all.

**Comment by ThomasVitale** [comment]
@snicoll Can I help with this task?

**Comment by snicoll** [comment]
Thanks for offering to help but datasource initialization is a tricky topic and there are a number of things we'd like to verify as part of the issue. I've assigned myself to make that more clear. Thanks for the offer in any case.

**Comment by ThomasVitale** [comment]
Ok, no problem.

**Comment by wilkinsona** [comment]
This has been addressed in 2.5 as part of the revamping of DataSource initialization.
