### ISSUE TITLE
Address Spring Cloud problems caused by slash config restrictions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21371]
As per [this comment from @spencergibb](https://github.com/spring-projects/spring-boot/commit/720d23af41e6111ae5845b5147d6e71ceac8d253#r39009229), the changes made for https://github.com/spring-projects/spring-boot/issues/21217 causes some problems for Spring Clould. Opening this issue so that we don't forget to look at it before 2.3 GAs.

@spencergibb Can you please let us know some more details about the assumptions that no longer hold true?

Issue labelled as a task for now. It may become a regression depending on what we learn.

**Comment by spencergibb** [comment]
It wasn't wild cards, it was slashes

**Comment by wilkinsona** [comment]
@spencergibb Thanks. Could you point us to some of the tests that we broke please?

**Comment by spencergibb** [comment]
https://jenkins.spring.io/view/Spring%20Cloud/view/CI.MASTER/job/spring-cloud-config-master-ci/10626/

**Comment by philwebb** [comment]
I think I fixed this already in 81058cab030ba98e221ce8046c50c43411219c61 (with the amusing typo)

**Comment by philwebb** [comment]
@spencergibb Is this still a problem, or did my fix do the trick?

**Comment by spencergibb** [comment]
it did fix it.

**Comment by philwebb** [comment]
Fixed in 81058ca
