### ISSUE TITLE
Upgrade to Spring Data Neumann-RELEASE

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21383]

**Comment by dreis2211** [comment]
I think the couchbase stuff broke the current build. There is no `@ViewIndexed` anymore.

**Comment by snicoll** [comment]
We are aware @dreis2211. I've reached out to the data team and I am waiting for feedback.

**Comment by mp911de** [comment]
The annotations are [reinstated as deprecated API](https://github.com/spring-projects/spring-data-couchbase/commit/33fdffab2fcec6ecd14e4e476f47d3f33ac90ce5) now. Sorry for inconvenience.
