### ISSUE TITLE
Sometimes tests with Couchbase are falling without no visible reason

### ISSUE THREAD

**Issue by aivinog1** [spring-projects/spring-boot#21389]
Spring Boot 2.3.0.BUILD-SNAPSHOT. 
Sometimes tests are falling because of the compilation error at this line: https://github.com/spring-projects/spring-boot/blob/07958ac5cc4b477161dd34a4effaebe8c2689590/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-data-couchbase/src/main/java/smoketest/data/couchbase/UserRepository.java#L19
See [this](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build-pull-requests/builds/576#L5e4648af:2264) and [this](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build/builds/912#L5e464862:2320).

But the jar that contains that class is present on the classpath and build is passing (locally and usually in the CI).

**Comment by wilkinsona** [comment]
Thanks for the report and sorry for the inconvenience. There was an unexpected breaking change in the latest Spring Data Couchbase snapshots that [removed `@ViewIndexed`](https://github.com/spring-projects/spring-data-couchbase/commit/b47fc007b58e8d8e829b2323a698b692fa5d1f6b#diff-055fa555245d98b4b2dd0546e25e2e43). The Spring Data team are aware. We'll automatically pick up a new snapshot that resolves the problem when it becomes available.

/cc @mp911de

**Comment by aivinog1** [comment]
@wilkinsona Thanks. Can you help me? How can I trigger a pipeline again in a Spring Boot CI?

**Comment by wilkinsona** [comment]
If you push a change to your branch, I believe it will trigger another build. Please don't worry about it too much, though. We'll build any changes locally before merging them.

**Comment by aivinog1** [comment]
@wilkinsona Got it. Thanks!
