### ISSUE TITLE
Cannot connect to remote shell with 1.2.0

### ISSUE THREAD

**Issue by tleveque23** [spring-projects/spring-boot#2138]
Since my upgrade to 1.2.0, I am unable to connect to the remote shell.
I have the following properties set:

    shell.ssh.port=29922
    shell.auth.simple.user.name=user
    shell.auth.simple.user.password=123

And when I try to connect using 
>ssh -p 29922 user@localhost

The password 123 is rejected.

In the log I can see that it is started correctly:

    CRaSSHD started on port 29922

But if I remove the name and password properties, I can get the password from the log and it is working fine (using "user" as username).

**Comment by snicoll** [comment]
I couldn't reproduce with the provided details. Please reopen if you have more info to share. Thanks.

**Comment by itscopedev** [comment]
Using
```
management.shell.auth.simple.user.name=user
management.shell.auth.simple.user.password=123
```
instead of 
```shell.ssh.port=29922
shell.auth.simple.user.name=user
shell.auth.simple.user.password=123
```
solved that problem for us.
