### ISSUE TITLE
Incorrect link targets in 2.3 RC1 wiki

### ISSUE THREAD

**Issue by krm1312** [spring-projects/spring-boot#21393]
The M3 and M4 links under "Upgrading from Spring Boot 2.2" in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-RC1-Release-Notes for M3 and M4 go to the wrong page (M2).

"In addition to the below, please see the instructions in the 2.3.0.M1, 2.3.0.M2, **2.3.0.M3**, and **2.3.0.M4** release notes for upgrading from Spring Boot 2.2."

**Comment by bclozel** [comment]
Thanks for the heads up, this is fixed now.
