### ISSUE TITLE
Update properties migrator to run on on deprecated properties with warn level as well

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21425]
The properties migrator is able to map a deprecated property to its replacement automatically but it does so only if the property is flagged with `error` level.

At first, it seems a shame we don't expand that mechanism to any deprecated property. Doing that, adding the module would help when something has just been deprecated (but is still honoured) so that the configuration is changed sooner than later.

Flagging for team attention to see if anyone remembers why it is restricted to error level only.

**Comment by wilkinsona** [comment]
I can't recall a reason for it being restricted to error level. Expanding it to cover warn-level deprecated properties sounds good to me.

**Comment by snicoll** [comment]
Thanks for the feedback. While doing the change, I think I've remembered. They were not considered as they are still effectively handled. In retrospect, I think I've been too cautious as opting-in for the tool should tell you as much as possible, including about supported deprecation. That count as a warning after all.
