### ISSUE TITLE
Use bomr to also handle internal dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21439]
At the moment `bomr` only handles our public dependency management (in `spring-boot-dependencies`). It would be very useful that it also handles our internal dependency management, located in `spring-boot-parent`.

**Comment by dreis2211** [comment]
Oh yes :)

**Comment by aivinog1** [comment]
@snicoll Hello, do you mind if I take this? I would like to challenge BOMR and understand how it works.

**Comment by philwebb** [comment]
@aivinog1 You're more than welcome to take a look, but we don't have a lot of documentation available for BOMR.
