### ISSUE TITLE
Build does not compile docs example java source

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21445]
It's  currently hard to write asciidoc example code in eclipse because the `/src...` folders aren't imported and there's no classpath.

**Comment by snicoll** [comment]
That was the case in IntelliJ IDEA for me at some point but it seems to be working now, no idea what changed.

**Comment by wilkinsona** [comment]
There's no source set defined so there's nothing for the IDE to import. That also means that the code isn't getting compile at the moment as part of the build. I don't understand how it can be working in IDEA as the project doesn't define the dependencies that are required for the code to compile.
