### ISSUE TITLE
Reinstate release scripts POM

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#21462]
We need to fix #21460 for 2.2.x as well.

**Comment by aivinog1** [comment]
@mbhave Hello! Do you mind if I take this issue? I understand what needs to be done.

**Comment by mbhave** [comment]
Thanks for the offer @aivinog1. We accidentally removed the file so it just needs to be added back. I think it's best if the team handles this one.

**Comment by mbhave** [comment]
Actually it looks like it [never got removed](https://github.com/spring-projects/spring-boot/blob/4a896f2272375b5f959b91c188059fc47b948d44/ci/images/releasescripts/pom.xml) from `2.2.x`. So we can just close this issue.

**Comment by aivinog1** [comment]
@mbhave ok, thanks!
