### ISSUE TITLE
web: custom exception message is missing after upgrade to 2.3.0.RELEASE

### ISSUE THREAD

**Issue by amarkevich** [spring-projects/spring-boot#21469]
Works on 2.2.7.RELEASE [1].
After upgrade to 2.3.0 response message is empty [2]
`
{"timestamp":"2020-05-15T11:00:34.384+00:00","status":422,"error":"Unprocessable Entity","message":"","path":"/failure"}`

1. https://github.com/amarkevich/spring-boot-jwt-test/blob/master/spring-boot-application/src/main/java/com/wedextim/spring/boot/application/controller/impl/ControllerFailureImpl.java
2. https://github.com/amarkevich/spring-boot-jwt-test/blob/master/spring-boot-application/src/test/java/com/wedextim/spring/boot/application/ApplicationTest.java#L99

**Comment by wilkinsona** [comment]
This is intentional to reduce the chance of information leaking. Please see the [relevant section of the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content) for details.
