### ISSUE TITLE
 spring-boot-buildpack-platform 2.3.0.RELEASE No plugin descriptor found

### ISSUE THREAD

**Issue by VassilMarjunits** [spring-projects/spring-boot#21467]
**Bug report**
**Artifacts**
spring-boot-buildpack-platform 2.3.0.RELEASE
and
org.springframework.boot:spring-boot-loader-tools:2.3.0.RELEASE

**Action**
`mvn -U org.springframework.boot:spring-boot-buildpack-platform:2.3.0.RELEASE:get -Dartifact=org.springframework.boot:spring-boot-buildpack-platform:2.3.0.RELEASE`

**Result:**
```
Unble to parse
Failed to parse plugin descriptor for org.springframework.boot:spring-boot-loader-tools:2.3.0.RELEASE 
(/home/user.m2/repository/org/springframework/boot/spring-boot-loader-tools/2.3.0.RELEASE/spring-boot-loader-tools-2.3.0.RELEASE.jar): 
No plugin descriptor found at META-INF/maven/plugin.xml -> 
```
**Maven**
`Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-40-generic", arch: "amd64", family: "unix"`

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, it's not clear to me what you are trying to do. Neither `spring-boot-loader-tools` nor `spring-boot-buildpack-platform` is a Maven plugin so it's expected that they do not have plugin descriptors.

**Comment by wilkinsona** [comment]
Perhaps you're trying to use the `get` goal of the dependency plugin. If so, the command should be the following:

```
mvn -U org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -Dartifact=org.springframework.boot:spring-boot-buildpack-platform:2.3.0.RELEASE
```
