### ISSUE TITLE
Improve logging for release promotion

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#21463]
It's really hard to tell why the promote job failed.

**Comment by bclozel** [comment]
I’m planning on moving master to https://github.com/spring-io/concourse-release-scripts
Would you like to do the same for 2.2.x?

**Comment by mbhave** [comment]
yeah I think moving to a consistent location makes sense. For 2.1.x as well then.

**Comment by mbhave** [comment]
I think we have better logging now so I'm going to close this.
