### ISSUE TITLE
Spring Boot 2.3.0 - Error:(8, 24) java: package javax.validation does not exist

### ISSUE THREAD

**Issue by Adriansun** [spring-projects/spring-boot#21476]
package javax.validation does not exist

Change pom to :
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.3.0.RELEASE</version>

Build it. 
Result is that javax.validation does not exist. Where in the release notes does it say that javax.validation was removed?

Version: <version>2.2.7.RELEASE</version> is okay.

**Comment by scottfrederick** [comment]
> Where in the release notes does it say that javax.validation was removed?

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters

**Comment by snicoll** [comment]
Duplicate of #21465
