### ISSUE TITLE
Add a note about generating a unique DataSource name to the release notes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21475]
https://twitter.com/cpcolin/status/1261369053630754816?s=21

**Comment by Alok255** [comment]
Hello, I am interested in the contribution.
Is that only document fix? Or should we modify the source code?

**Comment by snicoll** [comment]
Thanks for the offer @alex859. This was a left over of the 2.3 release notes for which I've just [added a section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#unique-datasource-name-by-default).
