### ISSUE TITLE
Checkstyle is failing build

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#21473]
Hi,

the recent changes in https://github.com/spring-projects/spring-boot/commit/ee758fa6704c5c2a03ed4426f4f164b72dd99b37 seem to have broken the checkstyle task. I would fix it on my own, but my contribution time is a bit limited at the moment and I couldn't fix it so far. The only thing that I saw was the following in src/checkstyle/checkstyle.xml:

```
	<module name="io.spring.nohttp.checkstyle.check.NoHttpCheck">
		<property name="whitelistFileName" value="${config_loc}/nohttp-whitelist.txt"/>
	</module>
```

As the nohttp-whitelist.txt doesn't exist anymore, I tried to point to the whitelist.lines file, but that didn't work. I'm wondering if the whole module is still needed? Without it, it seems to work. Let me know if this is already it and I contribute it.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. It's clearly time for me to step away for the weekend. You guess that the module is no longer needed was correct. I've removed it and thing should be working again now. Thanks again.

**Comment by dreis2211** [comment]
Have yourself a nice weekend then :)
