### ISSUE TITLE
Allow anyone on the team to generate the configuration changelog

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21486]
Stéphane has some code for generating the configuration properties changelog. It'd be nice if we all knew how to use it, maintain it, etc.

Edit: I think [this](https://github.com/snicoll-scratches/spring-boot-config/tree/8f7b5dfc813aa71509799b4b222332aabbac16fc/spring-boot-config-diff) is the code.

**Comment by snicoll** [comment]
I've made progress by polishing and adding the low-level infrastructure in 568930f. Based on that, we can [generate an Asciidoc file](https://github.com/snicoll/spring-boot/blob/0e29d7c949710cc512edeb2884ddc594ea9b3df7/spring-boot-project/spring-boot-tools/spring-boot-configuration-metadata/src/test/java/org/springframework/boot/configurationmetadata/diff/example/AsciidoctorDiffGenerator.java#L38) that describes the diff between the previous version and the version we've just released.

With that in place, there are two tasks that are remaining to make it a bit more high-level:

1. Add code somewhere that would download the jars for the previous version, the just released version, extract the metadata and build the two repositories. We already have that code [in my scratches project](https://github.com/snicoll-scratches/spring-boot-config/tree/main/spring-boot-config-loader/src/main/java/net/nicoll/boot/config/loader).
2. Have a method somewhere in our codebase we can trigger to generate the diff

I am a bit stuck at this point as I don't really know where to add this code. Making this part of our build could be an option but it would have to have a dependency on the `spring-boot-configuration-metadata` that's far from ideal (if at all possible?).
