### ISSUE TITLE
Maven Site Plugin: version missing in 2.3.0.RELEASE

### ISSUE THREAD

**Issue by rupert-madden-abbott** [spring-projects/spring-boot#21489]
Version: 2.3.0.RELEASE

The Maven Site Plugin no longer appears to be defined [here](https://github.com/spring-projects/spring-boot/blob/v2.3.0.RELEASE/spring-boot-project/spring-boot-dependencies/build.gradle) but it used to be defined [here](https://github.com/spring-projects/spring-boot/blob/v2.2.7.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L3332-L3336) in 2.2.7.RELEASE.

I'm unsure if this is deliberate or an unintended consequence of the migration to gradle.

If it is deliberate, it would be helpful if the upgrade Wiki could include the necessary configuration that downstream builds should adopt if they wish to use the previous maven-site-plugin config i.e.:

```
<plugin>
<artifactId>maven-site-plugin</artifactId>
<version>3.8.2</version>
</plugin>
```

However, I think it is helpful if all default maven plugin versions are defined in the Spring Boot parent as this helps to stabilise the build and the site plugin is now a surprising exception compared to all other maven plugins.

In my particular case, I am enforcing stable plugin versions using the maven-enforcer-plugin so upgrading to 2.3.0.RELEASE caused my build to break.

**Comment by wilkinsona** [comment]
This was intentional. I've updated the release notes to [mention the change](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#removal-of-some-maven-plugin-management).
