### ISSUE TITLE
Property for MongoDB UUID representation (in Spring Data MongoDB 3.0.0.RELEASE)

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#21498]
Spring Data MongoDB 3.0.0.RELEASE (by  @christophstrobl) introduced a programmatic way to configure the _MongoDB UUID representation_ . See chapter 7.4.2 at https://docs.spring.io/spring-data/mongodb/docs/3.0.0.RELEASE/reference/html/#upgrading.2-3.
It would be much more convenient to have a property for this configuration.

**Comment by juergenzimmermann** [comment]
`spring.data.mongodb.uuid-representation` is already available.

**Comment by wilkinsona** [comment]
Duplicate of #19960.
