### ISSUE TITLE
Tests using SpringBootTest no longer run

### ISSUE THREAD

**Issue by juan-palacios** [spring-projects/spring-boot#21500]
I upgraded to Spring Boot `2.3.0.RELEASE` and my tests no longer run. IDEA comes back saying no tests were found. The `maven-failsafe-plugin` says no tests were found. I tried `2.2.7.RELEASE` and I did not see the same problem.

This is a Kotlin project using JUnit 5. My tests use an abstract base class annotated with:

```kotlin
@ActiveProfiles(
    "local",
    "test",
    "acceptance-test"
)
@ExtendWith(PostgresContainerExtension::class)
@Import(AcceptanceTestConfiguration::class)
@TestPropertySource(
    properties = [
        // A set of properties for connecting to the DB
    ]
)
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
    classes = [MyApplication::class]
)
```

The sub-classes are (mostly) annotated with:

```kotlin
@Execution(ExecutionMode.CONCURRENT)
```

**Comment by wilkinsona** [comment]
Thanks for the report. It's hard to say what the cause my be from a couple of code snippets. Can you please provide a minimal sample that reproduces the problem?

**Comment by juan-palacios** [comment]
I'll try and put something together in the next couple of days

**Comment by jacakk** [comment]
Same here.
I think problem may be with annotations processor. I have this test:
```java
class TransactionsKafkaTest extends KafkaTest {
```
```java
@ActiveProfiles("mocks")
public abstract class KafkaTest extends EndpointTest {
```
```java
@ActiveProfiles("test")
@SpringBootTest(classes = TestConfiguration.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public abstract class EndpointTest {
```
```java
@Configuration
@Import(ApplicationInitializer.class)
public class TestConfiguration {
```
```java
@SpringBootApplication
@Import({
        RedisConfiguration.class
})
public class ApplicationInitializer {
```
```java
@Configuration
@Profile("!mocks")
public class RedisConfiguration {
```
and yet bean `RedisConfiguration ` is initialized...

There was no problem with Spring Boot 2.2.6.RELEASE.

**Comment by wilkinsona** [comment]
@jacakk I"m not sure that's the same problem. If `RedisConfiguration` is being initialised it would suggest that profile-specific beans are working. On the face of it, that doesn't seem to be related to tests annotated with `@SpringBootTest` not running at all. To avoid this issue tracking two potentially separate problems, please open a new issue with a complete example (an entire project that we can unzip or git clone) that reproduces the problem.

**Comment by jacakk** [comment]
That code I gave... that was a bad example because I omitted one thing:
It should be:
```java
@ActiveProfiles("profil,mocks")
public abstract class KafkaTest extends EndpointTest {
```
Two profiles separated by coma, it was working in Spring Boot 2.2.6 but now it's not.

I can't find this in Spring Core changelog, if it's a bug I can provide a working example in a new issue thread.

**Comment by wilkinsona** [comment]
@jacakk That still doesn't match @juan-palacios's setup as far as I can see. It's almost certainly due to https://github.com/spring-projects/spring-boot/issues/19537 where we fixed a bug that prevented a profile with a comma in its name from being activated. If you want to activate `profil` and `mocks` you should provide two separate names:

```
@ActiveProfiles({"profil", "mocks"})
```

To avoid derailing this issue any further, if you want to follow up please do some in a separate issue or on Gitter.

**Comment by juan-palacios** [comment]
This seems to get resolved when I removed some extra JUnit dependencies we had added a while ago:

```
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>1.5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <version>1.5.2</version>
            <scope>test</scope>
        </dependency>
```

Not sure why Spring Boot 2.3.0.RELEASE triggers this behaviour

**Comment by mbhave** [comment]
@juan-palacios As @wilkinsona suggested, could you provide a minimal sample that we can run to reproduce the issue?

**Comment by juan-palacios** [comment]
I tried to create a small project but couldn't reproduce the behaviour. Not sure what else from my project I need to bring in. I'm not sure I'll have the cycles to dig into it any further, so I'm going to close this for the time being
