### ISSUE TITLE
 javax.validation and hibernate validator dependencies missing in Spring Boot 2.3.0

### ISSUE THREAD

**Issue by ajkr195** [spring-projects/spring-boot#21512]
I tried to upgrade my Spring Boot 2.2.6 project to 2.3.0. The build and start up failed complaining about javax.validation apis missing. On top of it Hibernate validators too I had to add manually. Why it has been done or what are the advantages of doing so?

**Comment by gingermanjh** [comment]
@ajkr195 
[This](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters) will help.

**Comment by bclozel** [comment]
Duplicate of #21465.
