### ISSUE TITLE
Issue with Oracle 11g and ddl-auto set to validate

### ISSUE THREAD

**Issue by benjaminlefevre** [spring-projects/spring-boot#21520]
Since I bumped to spring-boot 2.3.0 (which comes with hibernate-orm 5.4.15.Final) I got a severe issue at startup (app doesn't even start).

**Context**
**Oracle 11g** / **Oracle10gDialect**
`spring.jpa.hibernate.ddl-auto: validate `(because of legacy context, deactivate ddl validation is not an option)

It fails with this message on one of my entity (the sequence is of course existing):

`[PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing sequence [seq_canal]`

Same code was working with spring boot 2.2.6 and before

**Comment by wilkinsona** [comment]
Spring Boot 2.2.6 uses Hibernate 5.4.12.Final by default so I suspect this is a regression in 5.4.15 (or .13 or .14). Can you please try using the `hibernate.version` to downgrade Hibernate to 5.4.12.Final and see if the problem still occurs?

**Comment by benjaminlefevre** [comment]
I will try tonight!

Notice we don't have the issue with PostgresSql and same code (id generated by séquences)

**Comment by benjaminlefevre** [comment]
> Spring Boot 2.2.6 uses Hibernate 5.4.12.Final by default so I suspect this is a regression in 5.4.15 (or .13 or .14). Can you please try using the `hibernate.version` property to downgrade Hibernate to 5.4.12.Final and see if the problem still occurs?

By downgrading hibernate to 5.4.12.Final, it works. You was just right.

It try also to upgrade to 5.4.16.Final (latest hibernate's release) it's the same issue.

**Comment by benjaminlefevre** [comment]
some people got the same issue, a ticket is opened in hibernate's JIRA: https://hibernate.atlassian.net/browse/HHH-14022
