### ISSUE TITLE
Maven layers documentation is incomplete

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21555]
The following isn't really that helpful: 

https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/html/#goals-build-image-parameters-details-layers

We could also do with a link from "Building OCI Images" to "Layered Jars" since it's hidden in the ToC.

**Comment by snicoll** [comment]
> The following isn't really that helpful:

I am not sure what you mean by that. This is a rendering of what the Maven plugin generates and choosing a nested type for a parameter as we've decided is unfortunately not supported by Maven.

**Comment by philwebb** [comment]
I wasn't sure how we generated it. I was hoping we could link out to the Javadoc of the class

**Comment by snicoll** [comment]
`DocumentPluginGoals` is generating the file so we could generate Javadoc links when we detect a matching type.
