### ISSUE TITLE
No hibernate validator in 2.3.0

### ISSUE THREAD

**Issue by feiquan666** [spring-projects/spring-boot#21552]
Hello, I have built a new springboot project through spring-initializer today, the version is 2.3.0 RELEASE. After introducing spring boot starter web, when I use @NotBlank annotation in my bean class, I find that hibernate validator has not been introduced. I know that this dependency still exists in version 2.1.2. Excuse me, how can I gracefully introduce hibernate validator in version 2.3.0?

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters

**Comment by feiquan666** [comment]
> https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters

thank you very much
