### ISSUE TITLE
Maven plugin help is missing

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21556]
We used to publish `META-INF/maven/org.springframework.boot/spring-boot-maven-plugin/plugin-help.xml` (Generated by maven-plugin-tools 3.6). It's missing since we switched to Gradle.

**Comment by gaurav-91** [comment]
Hi Phil,

I would like to work on this request. I am starting first time to contribute to Open Source projects to enhance my java skills.  Please advise if this would be helpful for me

Thanks

**Comment by philwebb** [comment]
Turns out there's a little bit more to this, the `HelpMojo` class file is also missing.
