### ISSUE TITLE
Deserialization-exception-handler: sendtodlq not working with Spring Boot 2.3.0.RELEASE

### ISSUE THREAD

**Issue by Elvendir94** [spring-projects/spring-boot#21564]
Hi!
I'm using Spring Boot 2.3.0.RELEASE with spring-cloud-dependencies Hoxton.SR4
I've set my application properties like below:
![image](https://user-images.githubusercontent.com/18270670/82822142-92ecb400-9ea5-11ea-94c9-680161627661.png)

I can't start my application because of this error:
![image](https://user-images.githubusercontent.com/18270670/82822313-db0bd680-9ea5-11ea-8a26-9d6d8ed85043.png)

I can run this application with Spring Boot 2.2.7.RELEASE version and sendtodlq is working.

**Comment by bclozel** [comment]
It seems that there's a binary incompatibility between Spring Cloud and our Spring Kafka upgrade #21387 
Could you [open an issue against Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream/issues)? Thanks!

**Comment by spencergibb** [comment]
There hasn't been a compatible release yet. Likely early this week

**Comment by Elvendir94** [comment]
> It seems that there's a binary incompatibility between Spring Cloud and our Spring Kafka upgrade #21387
> Could you [open an issue against Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream/issues)? Feel free to ping back here with a link to the new issue you've created so that we can track the problem in Spring Boot as well.
> 
> Thanks!

Thanks! You can track this issue here: https://github.com/spring-cloud/spring-cloud-stream/issues/1971
