### ISSUE TITLE
Add a note for the moved Elasticsearch auto configuration and RestClientCustomizer in the release notes

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#21567]
We were moving to Spring Boot 2.3 and noticed that the ES auto configuration classes were moved as part of https://github.com/spring-projects/spring-boot/commit/fec386b574d503f8caef74708e2ad6f767e79b5a. The `RestClientBuilderCustomizer` also got moved. Can this be mentioned in the release notes?

The move of the `RestClientBuilderCustomizer` is also a breaking change.

**Comment by philwebb** [comment]
Sorry about that, we'll update the docs. I've also opened #21572 to see if we can't reintroduce it in a deprecated form.

**Comment by filiphr** [comment]
Thanks for understanding

**Comment by snicoll** [comment]
I've added a note in the deprecation section. The original customizer has been restored in a deprecated fashion in #21572
