### ISSUE TITLE
Expose Hibernate Statistics through Metrics endpoint

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#2157]
When using Hibernate as the ORM provider it would be nice that, when statistics are enabled, those would be accessible through a metrics endpoint.

**Comment by kiview** [comment]
How do you enable Hibernate Statistics in Spring-Boot?

**Comment by wilkinsona** [comment]
Set `spring.jpa.properties.hibernate.generate_statistics` to `true` in `application.properties`

**Comment by csavory** [comment]
@wilkinsona @mdeinum  I'm not sure if this would help, but I wrote a subclass of ```PublicMetrics``` for our project that exposes some hibernate metrics.

**Comment by marcushenrique** [comment]
Any news about this? Would appreciate to access statistics through actuator.

**Comment by snicoll** [comment]
Closing in favour of the PR #3596
