### ISSUE TITLE
Document how to use Gradle's native bom support as an alternative to the dependency management plugin

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-boot#21570]
After watching  [Managing Dependencies for Spring Projects with Gradle by Jenn Strater and Andy Wilkinson](https://www.youtube.com/watch?v=AADeX1AEmzU) talk. I started a new  project using the [Gradle Java Platfrom Plugin](https://docs.gradle.org/current/userguide/java_platform_plugin.html) rather than the Spring Boot dependency gradle plugin which worked but required a lot of trial and error.  Upgrading from boot 2.2.6 to 2.3.0 caused the breakage #21569. 

It's unclear how the boot plugin [interacts](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/gradle-plugin/reference/html/#reacting-to-other-plugins) with the Java Platform Plugin. Documenting how to use the Java Platform Plugin rather than the dependency management plugin is quite useful for many users.

**Comment by philwebb** [comment]
We should also add a smoke test if it's brittle.

**Comment by wilkinsona** [comment]
The Java Platform Plugin isn't really an alternative to the Dependency Management Plugin. The former is used when you're creating a project that defines a platform/bom. The latter is used when you're consuming a bom. A more typical replacement for the dependency management plugin is a `platform` or `enforcedPlatform` dependency on `spring-boot-dependencies`. I think that's what we should document.
