### ISSUE TITLE
Add Java 15 CI

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21604]
It might be a bit early for us (we waited for the JDK's RC phase for Java 14), but Framework 5.3 is building against Java 15 already. We should consider when we want to start doing the same.

**Comment by dreis2211** [comment]
There are simply no AdoptOpenJDK builds for JDK 15 yet. I wonder if Spring Framework uses OpenJDK EA builds!?

**Comment by aahlenst** [comment]
We're doing JDK 15 for quite some time: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases. But we don't surface them yet on the website.

**Comment by dreis2211** [comment]
That's what I meant to say, sorry. Spring-Boot does a check against the API to check for JDK upgrades, which wouldn't work on 15 because it's not officially exposed to the outside. But that might be acceptable.

**Comment by dreis2211** [comment]
Btw...I would volunteer to do this again for JDK 15.

**Comment by aahlenst** [comment]
@dreis2211 If we can make anything easier, please open tickets in either https://github.com/AdoptOpenJDK/openjdk-website or https://github.com/AdoptOpenJDK/openjdk-api-v3.

**Comment by dreis2211** [comment]
@aahlenst I think there is already https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/212 that would be sufficient ;)

**Comment by philwebb** [comment]
> Btw...I would volunteer to do this again for JDK 15.

That would be great if you have time. Thanks @dreis2211!

**Comment by dreis2211** [comment]
If there is no big pressure here, I'd like to resolve it in a way so that we don't have to skip the update logic for JDK 15, which means a little bit of waiting time until the AdoptOpenJDK issue is resolved. But I can also simply skip the update logic for JDK 15. Just let me know.

**Comment by snicoll** [comment]
I don't think getting automatic update right away is a blocker. If that changes the pipeline config too much, we can wait.

**Comment by dreis2211** [comment]
It doesn't - from what I have in mind. Just wanted to have it clarified upfront. Will work on JDK 15 next week then ;)

**Comment by snicoll** [comment]
Closing in favour of PR #21173
