### ISSUE TITLE
Provide auto-configuration for SendGrid's Java client

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2160]
https://github.com/sendgrid/sendgrid-java

**Comment by maciejwalkowiak** [comment]
I would be happy to contribute this feature. Do you have in mind anything more than registering `com.sendgrid.SendGrid` bean when properties for Sendgrid username and password are set?

**Comment by wilkinsona** [comment]
Cool! Thanks.

Beyond username and password, the only thing I had in mind was to explore whether or not proxy configuration could be done from the environment as well.
