### ISSUE TITLE
Docs update on graceful shutdown?

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-boot#21602]
The migration guide advises:
"_When a grace period is configured, upon shutdown, the web server will no longer permit new requests and will wait for up to the grace period for active requests to complete._"
https://spring.io/blog/2020/05/15/spring-boot-2-3-0-available-now

While this is certainly a nice feature, but could you add any reference to where this feature is documented? I mean, how do you configure that grace period? I could not find anything in the spring docs that mentions either "grace" or "shutdown" keywords...

**Comment by wilkinsona** [comment]
Where did you look? There are 13 occurrences of "grace" in the reference documentation and 12 occurrences of "graceful". The most relevant of these is for [4.8 Graceful shutdown](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#boot-features-graceful-shutdown).

**Comment by membersound** [comment]
Ok thanks for clarification. That's certainly sufficient. Maybe I had a

**Comment by wilkinsona** [comment]
Thanks for the suggestion. There are more details in the release notes that are linked to from the intro in the blog post. I've added a link from the release notes to the relevant section of the reference documentation.
