### ISSUE TITLE
SpringApplicationBuilder: Initialize siblings concurrently

### ISSUE THREAD

**Issue by OLibutzki** [spring-projects/spring-boot#21608]
The _SpringApplicationBuilder_ supports the creation of hierarchical application contexts. Those contexts are initialized sequentially. In order to accelerate the startup time, siblings can be initialized concurrently.

It would be great to extend the _SpringApplicationBuilder_-API to support concurrent initialization.

**Comment by philwebb** [comment]
Thanks for the suggestion but I think this would add quite a lot of complexity to the builder. I'm also not sure how much of a benefit this would be for typical Spring Boot applications which tend to only have one a single application context.

**Comment by OLibutzki** [comment]
Ok, thanks for the response. I'm going to solve this in our project locally.
