### ISSUE TITLE
Version-specific content is missing from Gradle Plugin's reference documentation

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#21610]
I think it should be in the getting started here

https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/gradle-plugin/reference/html/#getting-started

and possibly in the reference docs I had trouble finding it.

**Comment by wilkinsona** [comment]
Thanks. It's there in the [2.2.7 docs](https://docs.spring.io/spring-boot/docs/2.2.7.RELEASE/gradle-plugin/reference/html/#getting-started) but missing in 2.3. The content varies depending on the type of the version (milestone, RC, or release) so it looks like there's a problem with the logic that determines what to include.
