### ISSUE TITLE
Clean up jackson modules from the bom

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#21622]
modules like this are deprecated https://github.com/FasterXML/jackson-datatype-jsr310 I'd go through them all and remove the ones that are, though to be fair... I'm not sure how this is generated in the documentation, so Im not certain if they're just part of the jackson.bom, and then get listed.

this isn't critical to me, I just noticed a 3rd party starter recommending the JavaTime module, and I realized that it shouldn't be used.

**Comment by philwebb** [comment]
I'm afraid we just have a single dependency that leans on the published jackson-bom:

```gradle
	library("Jackson Bom", "2.11.0") {
		group("com.fasterxml.jackson") {
			imports = [
				"jackson-bom"
			]
		}
	}
```

We don't have the option to remove individual projects so we're stuck with whatever Jackson themselves publish.
