### ISSUE TITLE
Document deprecations of org.springframework.boot.loader.archive.Archive.iterator()

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21695]
`org.springframework.boot.loader.archive.Archive.iterator()` was deprecated in 2.3 but `Archive` implements `Iterable<Archive.Entry>` which defines the `iterator()` method. If we remove the deprecated method it'll become present in undeprecated form as it'll be inherited from `Iterable`. I think we either need to deprecate all three methods defined by `Iterable` so that `Archive` can stop extending it in the future or we need to undeprecate `iterator()`.

**Comment by philwebb** [comment]
My preference would be to deprecate all three.
