### ISSUE TITLE
The private method of the auto configuration class will be reflected, causing the provided dependency to be thrown java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by lkqm** [spring-projects/spring-boot#21733]
There is one AutoConfiguration class call `WxMpStorageAutoConfiguration`, include method `private JedisPool getJedisPool(){}` and the `JedisPool` dependency is provided, when spring boot runing, It's will reflected the private method, will raise ClassNotFoundException.

## enviroments
- spring-boot: 2.2.2-RELEASE
- jdk: 1.8.0_232

## code
![image](https://user-images.githubusercontent.com/20638840/83946834-d94af700-a845-11ea-83ed-90405eb46f03.png)

![image](https://user-images.githubusercontent.com/20638840/83946842-e49e2280-a845-11ea-96e4-4584cb98838e.png)

![image](https://user-images.githubusercontent.com/20638840/83946850-f384d500-a845-11ea-8185-25d51490e3d9.png)

detail: https://paste.ubuntu.com/p/zd8SFysPXh/

**Comment by snicoll** [comment]
`WxMpStorageAutoConfiguration` seems to be part [of this project](https://github.com/FanWenTao-Felix/WxJava). I am assuming that you mean when `JedisPool` isn't provided, right? 

You should raise an issue in that project so they had the necessary condition to backoff when Jedis isn't on the classpath.

**Comment by lkqm** [comment]
No, I wite `WxMpStorageAutoConfiguration`is part of this [project](https://github.com/Wechat-Group/WxJava/blob/master/spring-boot-starters/wx-java-mp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/mp/config/WxMpStorageAutoConfiguration.java). It is clear that jedis dependency is optional. The problem is that why spring boot will reflect all private methods in the auto configuration class when loading, which will be reflected through the reflectutils tool class.
Thanks.

**Comment by snicoll** [comment]
If you are the author, you need to put `@ConditionalOnClass` to guard the JVM from scanning signatures and failing the way it does now. Spring Boot doesn't do that.
