### ISSUE TITLE
Improve CI slack notification message that includes a build scan

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#21757]
The pattern for our notification is as follows:

```
spring-boot-2.4.x jdk14-build was successful! [build log] [build scan]
```

Before the move to Gradle it used to be like this:

```
 spring-boot-2.1.x build was successful!
```

Where the whole text is a link to the build log. I suggest we simplify and harmonize the notification message with a build log as follows:

```
spring-boot-2.4.x jdk14-build was successful! [build scan]
```

Where the text is back again a link to the build log for consistency.

**Comment by dreis2211** [comment]
I can tackle that.

**Comment by philwebb** [comment]
Thanks @dreis2211, I've assigned the issue to you.

**Comment by mbhave** [comment]
Closing in favor of PR #21793.
