### ISSUE TITLE
Make it more obvious that web.xml and web-fragment.xml are ignored when running with an embedded container

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2175]
The answer might just be better documentation, or perhaps a warning if we find a `web.xml` on the filesystem or in the jar. Searching all dependencies for `web-fragment.xml` files might be a step too far as it could be rather slow.

**Comment by kenwdelong** [comment]
Is there any way to add a JAR with a web-fragment.xml to a Spring Boot app?

**Comment by wilkinsona** [comment]
What end result are you aiming for and are you using an embedded container?

**Comment by kenwdelong** [comment]
I want a JMX console (like the one in JBoss) that is visible as an HTTP page.  Yes, i am using the embedded container/executable JAR.

I have a github project https://github.com/kenwdelong/jmx-console that I am used to just dropping in my WAR projects, and the console just shows up at /jmx-console.  It's a web fragment.

I tried registering the servlets individually, which worked, but I could not figure out how to get the static resources and JSPs to work.

**Comment by wilkinsona** [comment]
Using `ServletRegistrationBeans` in place of the `web-fragment.xml` is what I'd do. You could [write your own auto-configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-developing-auto-configuration) and include it in your JMX console project so that you only need to implement it once and can then drop the project into any Boot app.

[As documented](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-jsp-limitations), and assuming you're using Tomcat, I believe you'll need to use an executable war to get JSPs to work. You'll also need a dependency on Jasper:

```
<dependency>
    <groupId>org.apache.tomcat.embed</groupId>
    <artifactId>tomcat-embed-jasper</artifactId>
    <scope>provided</scope>
</dependency>
```

**Comment by kenwdelong** [comment]
Ok, thanks Andy.  I think what I will do is rewrite JMX Console to use Groovy builders to generate the HTML (hopefully that will work; I fear all the forms) and install standard spring controllers, and then as you said add some autoconfig.
