### ISSUE TITLE
How can I show error details in 2.3.x?

### ISSUE THREAD

**Issue by qq253498229** [spring-projects/spring-boot#21773]
After upgrading to 2.3. X.release, the default validation was removed. After I manually added the `spring-boot-starter-validation` dependency, I found result was different .
Before:

```
{
    "timestamp": "2020-06-09T06:30:56.456+0000",
    "status": 400,
    "error": "Bad Request",
    "errors": [
        {
            "codes": [
                "NotBlank.testClass.name",
                "NotBlank.name",
                "NotBlank.java.lang.String",
                "NotBlank"
            ],
            "arguments": [
                {
                    "codes": [
                        "testClass.name",
                        "name"
                    ],
                    "arguments": null,
                    "defaultMessage": "name",
                    "code": "name"
                }
            ],
            "defaultMessage": "不能为空",
            "objectName": "testClass",
            "field": "name",
            "rejectedValue": null,
            "bindingFailure": false,
            "code": "NotBlank"
        }
    ],
    "message": "Validation failed for object='testClass'. Error count: 1",
    "path": "/test"
}
```

Now:

```
{
    "timestamp": "2020-06-09T07:19:29.794+00:00",
    "status": 400,
    "error": "Bad Request",
    "message": "",
    "path": "/test"
}
```

What can I do to make the result the same as before?

**Comment by snicoll** [comment]
@qq253498229 please [review the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) before upgrading. 

The validation starter change is [covered in a dedicated section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters) and so is [the change in output](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content).

**Comment by qq253498229** [comment]
> @qq253498229 please [review the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) before upgrading.
> 
> The validation starter change is [covered in a dedicated section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters) and so is [the change in output](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content).

Thanks a lot, it solved my problem.
