### ISSUE TITLE
Document that application.conf is not read by default when using the Cassandra auto-configuration

### ISSUE THREAD

**Issue by Esakkimuthu991** [spring-projects/spring-boot#21787]
`CqlSession.getMetrics()` returning null value, even after configuration for enabling the metrics has been added to it.

```java
@Autowired
private CqlSession cqlsession;

MetricRegistry metricRegistry = cqlsession.getMetrics()
            .orElseThrow(() -> new IllegalArgumentException("not able to get metrics"))
            .getRegistry();
```

application.properties:

```
datastax-java-driver.advanced.metrics {
  session.enabled = [connected-nodes, cql-requests]
  node.enabled = [pool.open-connections, pool.in-flight]
}
```

**Comment by wilkinsona** [comment]
Your `application.properties` configuration doesn't look like it is in the correct format. It looks like Cassandra driver's `.conf` file format to me. Perhaps a typo in the file's name in the description above?

Using `application.conf` won't fix your problem as, when using Spring Boot's auto-configuration of Cassandra's Driver `application.conf` is not used. The supported mechanisms for configuring Cassandra are [described in the documentation](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#boot-features-connecting-to-cassandra). In your case, you should use a `DriverConfigLoaderBuilderCustomizer` bean:

```java
@Bean
DriverConfigLoaderBuilderCustomizer metricsCustomizer() {
	return (builder) -> {
		builder.withStringList(DefaultDriverOption.METRICS_SESSION_ENABLED,
				Arrays.asList("connected-nodes, cql-requests"));
		builder.withStringList(DefaultDriverOption.METRICS_NODE_ENABLED,
				Arrays.asList("pool.open-connections", "pool.in-flight"));
	};
}
```

We should probably update the documentation to clarify that `application.conf` is not used by the auto-configured `DriverConfigLoader`.

**Comment by Esakkimuthu991** [comment]
> Your `application.properties` configuration doesn't look like it is in the correct format. It looks like Cassandra driver's `.conf` file format to me. Perhaps a typo in the file's name in the description above?
> 
> Using `application.conf` won't fix your problem as, when using Spring Boot's auto-configuration of Cassandra's Driver, `application.conf` is not used. The supported mechanisms for configuring Cassandra are [described in the documentation](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#boot-features-connecting-to-cassandra). In your case, you should use a `DriverConfigLoaderBuilderCustomizer` bean:
> 
> ```java
> @Bean
> DriverConfigLoaderBuilderCustomizer metricsCustomizer() {
> 	return (builder) -> {
> 		builder.withStringList(DefaultDriverOption.METRICS_SESSION_ENABLED,
> 				Arrays.asList("connected-nodes, cql-requests"));
> 		builder.withStringList(DefaultDriverOption.METRICS_NODE_ENABLED,
> 				Arrays.asList("pool.open-connections", "pool.in-flight"));
> 	};
> }
> ```
> 
> We should probably update the documentation to clarify that `application.conf` is not used by the auto-configured `DriverConfigLoader`.

After changing my code to use above as suggested. 

<img width="731" alt="cqlsessionmetrics" src="https://user-images.githubusercontent.com/43499028/84153537-a5f5ab80-aa83-11ea-9c17-c076409b855c.PNG">

**Comment by wilkinsona** [comment]
Sorry, that was a typo in my code snippet. I've edited it above to correct it. It should have read `Arrays.asList("connected-nodes", "cql-requests")` rather than `Arrays.asList("connected-nodes, cql-requests")`.

**Comment by Esakkimuthu991** [comment]
> Sorry, that was a typo in my code snippet. I've edited it above to correct it. It should have read `Arrays.asList("connected-nodes", "cql-requests")` rather than `Arrays.asList("connected-nodes, cql-requests")`.

Thanks Solved my problem
