### ISSUE TITLE
Endpoint for autoconfigured Filters, Servlets and Listeners

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2178]
It would be useful to list them and in the order that they were registered. Could perhaps be part of the auto-configuration report.

See #2177 for the original request.

**Comment by wilkinsona** [comment]
For Filters and Servlets, I was wondering if we should include them in an improved mappings endpoint (#9979).

**Comment by philwebb** [comment]
We'll handle servlet and filter mappings in #9979 and not do listeners.
