### ISSUE TITLE
Actuator and streams does not work together out of the box

### ISSUE THREAD

**Issue by paul-ovchinnikov** [spring-projects/spring-boot#21785]
**Describe the issue**
There are several closed issues about RabbitAutoConfiguration error in multi-binder mode
[998](https://github.com/spring-cloud/spring-cloud-stream/issues/998)
[commit in documentation](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/commit/4d9c1c4c1b5928c046b1c496c74e58cedd2d26f6)

Actuator and streams does not work together out of the box

**To Reproduce**
1. Create new project
2. Add actuator dependency
3. Add spring cloud stream dependency
4. Start application

**Version of the framework**
Spring Boot - 2.2.7
Spring Cloud Stream - Horsham SR5

**Expected behavior**
Should work without additional configuration
**Screenshots**

**Additional context**
As you can see I didn't make any configurations about your "multi-binder" mode. And a reason of 
> repeating he same question especially when it was already answered
as @olegz said a several year ago, is that note in documentation is not a solution of problem

And it's weird why I should apply additional settings to disable RabbitAutoConfiguration
I have post the same issue to Spring Cloud Stream team

**Comment by wilkinsona** [comment]
Please don't cross-post the same issue in multiple places.

As far as I can tell, the Streams team believe that they have already addressed this. I'll leave them to comment on https://github.com/spring-cloud/spring-cloud-stream/issues/1983 to confirm if that's the case. If this is something that they decide to revisit and refine, we can consider what, if any, changes in Spring Boot may be helpful at that time.
