### ISSUE TITLE
The @ActiveProfiles throws exception while trying to overriding properties file values

### ISSUE THREAD

**Issue by tamademicheli** [spring-projects/spring-boot#21791]
IS: while upgrading from SpringBoot 2.2.7 to 2.3.0, the overriding behaviour of @ActiveProfiles changed without notice on the migration. This test works with 2.2.7 and not with 2.3.0 https://github.com/tamademicheli/springboot230issueTestActiveProfile/blob/master/demo23/src/test/java/com/example/demo23/ActiveProfilesTestBackendTest.java

SHOULD: work in both version. if not please add to the migration path this breaking change and how we should accomplish to override properties likely as the linked test.

A similar issue which could be related to that:
https://github.com/spring-projects/spring-boot/issues/21302

`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'mybackendvalue' in value "${mybackendvalue}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)`

**Comment by scottfrederick** [comment]
This change was caused by a bug fix (#19537) that prevented profile names containing commas from being activated. To enable multiple profiles, you should provide each as a separate value, as in 

```
@ActiveProfiles({"backend", "test"})
```

**Comment by scottfrederick** [comment]
Added to the 2.3.0 release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#activating-multiple-profiles-with-activeprofiles

**Comment by tamademicheli** [comment]
Thank you , that helped a lot.
