### ISSUE TITLE
spring.datasource is ambiguous

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2183]
`spring.datasource` is used to configure Boot's own configuration support (see `DataSourceProperties`)  but it's also used to configure the connection pool specific implementation when it's auto-configured.

Depending on the environment, `spring-datasource` can react to Tomcat, Hikari or Commons DBCP. These pools have commonalities but they do have conflicts too (`url` vs. `jdbcUrl`). It would probably be better if those boundaries where clearly identified. This has several advantages:

* It's much more clear to the user they can configure implementation specific settings if we write that these are mapped from, let's say `spring.datasource.tomcat` for Tomcat
* The generated meta-data use an isolated namespace for each implementation which clearly shows what a connections pool can do (IDE auto-completion)
* If one of those connection pools decide to give a different semantic to a property that is managed by a different implementation, we are not affected since they have a different property name

The clear downside is that you have to configure the same settings twice if you happen to use 2 different connection pools and they share the same property. 

We can approach this issue in two ways:

1. We break it: no support for `spring.datasource` for implementation specific settings.
2. We don't: not sure we should use @ConfigurationProperties for that then because we should only apply a property if it wasn't found in its specific namespace. Can be tricky.

A good approach would be to support the existing namespace and the implementation specific namespace ASAP and ask user to move to that model. Update meta-data harvesting so that only the specific namespaces are discovered (easy).

On a final note: we should think carefully about choosing the right namespace. If we go for `spring.datasource.tomcat` then it's clear that it becomes 'reserved' for the tomcat specific implementation (same for hikari, dbcp and dbcp2). Hopefully product names are specific enough.

**Comment by snicoll** [comment]
The conclusion of our discussions is to go the break route (that is option 1). Please let me know asap if I got this wrong.

**Comment by cemo** [comment]
Any chance for multidatasource support?

**Comment by snicoll** [comment]
@cemo that's not the place to ask. We already discussed that (I just can't find the issue right now).

**Comment by cemo** [comment]
ok :)

**Comment by snicoll** [comment]
Okay so we had a lengthy discussion with @dsyer on the proposal (https://github.com/snicoll/spring-boot/commit/e71504b8b74c2a9ad2b97518f64b891c00bd8e87) and it's definitely more complicated than I thought. 

Spring cloud uses `@ConfigurationProperties` to identify the components that can be rebound at runtime and this change will actually break that feature. It seems that we have all that we need but some meta-data is missing to let Spring Cloud do its thing.

**Comment by philwebb** [comment]
I think we should push this back to 1.4 for now and just live with things in 1.3.

**Comment by snicoll** [comment]
Updated [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M1-Release-Notes#datasource-binding) as well.

**Comment by cbornet** [comment]
Is this working for properties that cannot be changed at runtime (eg . Hikari's connectionTestQuery) ?

**Comment by snicoll** [comment]
That commit does not change anything related to binding. If it's working now, it will work as well and I can't see anything that would prevent proper binding.

**Comment by cbornet** [comment]
I had missed the binding part. Thanks to have pointed that.

**Comment by philwebb** [comment]
For some reason `DataSourceAutoConfigurationTests` now fails in eclipse. I think it might be because `PooledDataSourceConfiguration` is loading the nested configuration classes directly rather than via the import.
