### ISSUE TITLE
Placeholder replacement in prefix of @ConfigurationProperties?

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#2186]
Any way to use `@ConfigurationProperties(prefix="#somepropertyinconfig",ignoreUnknownFields=true)`

I have a specific requirement where i am configuring akamai and localservers behave the same way, so if there goes a case where akamai goes off from the project, we can work with local systems.

For that i have exactly same config for local and akamai say 

```
application.server=akamai/local

akamai.host=somehost1
local.host=somehost2
```

And i want this config to be mapped to same class having 

```
@ConfigurationProperties(prefix="#application.server", ignoreUnknownFields=true){
class ApplicationConfig{
private String host;
}
```

And this should map to akamai or local depending upon the application.server key value

I tried with `@Value` annotation, but that is not a string but value error was reported by jdk.

Any way to do that ?

**Comment by ak4721857** [comment]
We could have another option to load properties from two different properties files having same key with different value and with one configuration class.

STEPS:
1.Place @PropertySource(value= {"classpath:/"+"${appfileName}"+".properties"}) on configuration class
2.Mention property in application.properties file        appfileName=app1/app2(app1 and app2 are name of two other properties files).
3.For key such as host in app1 or app2 properties file, get the value in configuration class with @Value("${host}")

Based on provided property file name for property appfileName ,value will be obtained in configuration class.
