### ISSUE TITLE
Not able to use digest in 'builder' reference

### ISSUE THREAD

**Issue by srinivasa-vasu** [spring-projects/spring-boot#21879]
Not able to use digest in builder property,
```
bootBuildImage {
	builder 	= "registry/repo/image:@sha256:<id>"
}
```
bcoz of the below,

https://github.com/spring-projects/spring-boot/blob/1c3cf220644e0b11915fbd1aa6501d9a93335cc5/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform/src/main/java/org/springframework/boot/buildpack/platform/build/BuildRequest.java#L87

Any specific reason not to allow digest in the builder?

**Comment by philwebb** [comment]
@srinivasa-vasu Can you provide more information. What error do you get?

**Comment by srinivasa-vasu** [comment]
@philwebb - Pls find the info,

Gradle snippet
```
bootBuildImage {
	imageName 	= "humourmind/${project.name}:${project.version}"
	environment = ["BP_JVM_VERSION" : "11.0.7", "BPL_JVM_HEAD_ROOM" : "5"]
	builder 	= "humourmind/paketo-java-builder-tiny@sha256:f92f93d050ce0ecad7503ebe35a6be57ae6cf74163a7926a53f1c8079d30cf66"
}

```

Build log
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :bootBuildImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootBuildImage'.
> Image reference 'docker.io/humourmind/paketo-java-builder-tiny@sha256:f92f93d050ce0ecad7503ebe35a6be57ae6cf74163a7926a53f1c8079d30cf66' cannot contain a digest

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
5 actionable tasks: 5 executed

```

I could see it failing at **return new BuildRequest(...)** in the stacktrace.

**Comment by philwebb** [comment]
Can you please attach the stack trace.

**Comment by srinivasa-vasu** [comment]
"org.springframework.util.Assert.state(Assert.java:94)"
"org.springframework.boot.buildpack.platform.docker.type.ImageReference.inTaggedForm(ImageReference.java:154)"
"org.springframework.boot.buildpack.platform.build.BuildRequest.withBuilder(BuildRequest.java:87)"
"org.springframework.boot.gradle.tasks.bundling.BootBuildImage.customizeBuilder(BootBuildImage.java:240)"
"org.springframework.boot.gradle.tasks.bundling.BootBuildImage.customize(BootBuildImage.java:230)"
"org.springframework.boot.gradle.tasks.bundling.BootBuildImage.createRequest(BootBuildImage.java:213)"
"org.springframework.boot.gradle.tasks.bundling.BootBuildImage.buildImage(BootBuildImage.java:208)"
"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
"java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
 "java.base/java.lang.reflect.Method.invoke(Method.java:566)"
 "org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)"
 "org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)"
 "org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)"
 "org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)"
 "org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:722)"
 "org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:689)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)"
 "org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:554)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:537)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:278)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:267)"
 "org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)"
 "java.base/java.util.Optional.orElseGet(Optional.java:369)"
 "org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)"
 "org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)"
 "org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)"
 "org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)"
 "org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)"
 "org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)"
 "org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)"
 "org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)"
 "org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)"
 "org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)"
 "org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)"
 "org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)"
 "org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)"
 "org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)"
 "org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)"
 "org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)"
 "org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)"
 "org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)"
 "org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)"
 "org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)"
 "org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)"
 "org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)"
 "org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)"
 "java.base/java.util.Optional.map(Optional.java:265)"
 "org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)"
 "org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)"
 "org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)"
 "org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)"
 "org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)"
 "org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)"
 "org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)"
 "org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)"
 "org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)"
 "org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)"
 "org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)"
 "org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)"
 "java.base/java.util.Optional.orElseGet(Optional.java:369)"
 "org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)"
 "org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)"
 "org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)"
 "org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)"
 "org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)"
 "org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)"
 "org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)"
 "org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)"
 "org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)"
 "org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)"
 "org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)"
 "org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)"
 "org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)"
 "org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)"
 "org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)"
 "org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)"
 "org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)"
 "org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)"
 "org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)"
 "org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)"
 "org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:370)"
 "org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:357)"
 "org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:350)"
 "org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)"
 "org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)"
 "org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)"
 "org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)"
 "org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)"
 "org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)"
 "org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)"
 "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)"
 "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)"
 "org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)"
 "java.base/java.lang.Thread.run(Thread.java:834)"
