### ISSUE TITLE
Use Awaitility to address flakiness of LiveReloadServerTests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21873]
We're currently using Thread.sleep to allow enough time for a message to be processed. This fails occasionally if the message processing thread isn't scheduled quickly enough. We should use Awaitility instead.

**Comment by tszmytka** [comment]
If no one else is working on this I would be happy to take over.

**Comment by wilkinsona** [comment]
Yes please, @tszmytka. That'd be great.

**Comment by wilkinsona** [comment]
Closing in favour of https://github.com/spring-projects/spring-boot/pull/21988.
