### ISSUE TITLE
spring boot 2.3.0 @StatusResponse reason not use

### ISSUE THREAD

**Issue by 909446172** [spring-projects/spring-boot#21884]
this annotation value reason not availabe in @StatusResponse at 2.3.0 version

**Comment by philwebb** [comment]
I'm sorry but I don't understand your question. We don't have a `@StatusResponse` annotation.

**Comment by snicoll** [comment]
@909446172 perhaps you mean `@ResponseStatus`? and the fact the reason does not show up anymore. Please [review the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content) before upgrading.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
