### ISSUE TITLE
Micrometer Metrics for KafkaStreams

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#21890]
Similar to https://github.com/spring-projects/spring-boot/commit/d16074d8fdc457107177bca026635e4575fe0c08#diff-2f3136f1958043f3d7c37de45bf062fa - consider adding a `KafkaStreamsMicrometerListener` to the default `StreamsBuilderFactoryBean`.

(When spring-kafka 2.5.3 is available - PR here https://github.com/spring-projects/spring-kafka/pull/1502)

**Comment by snicoll** [comment]
Closing in favor of PR #21921
