### ISSUE TITLE
Add sdkman to concourse

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21903]
We should rewrite SDKman publish scripts so they can be run in concourse. We should also somehow detect the default version because we keep forgetting to change it.

**Comment by mbhave** [comment]
Detect the default version for?

**Comment by snicoll** [comment]
The current line (2.4.x) at the moment. See the if clause that was recently changed in the side project for more details.

**Comment by philwebb** [comment]
[This line](https://github.com/philwebb/spring-boot-gvm-publish/blob/a46f60d761fab5bb78124f979f3377a58e841420/gvmpublish.groovy#L43) of the current script.

**Comment by mbhave** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/7b38b0ed11f29692e9a04a78d8cc4e3ca1067a1e.

**Comment by philwebb** [comment]
Reopening to look at making it a manual step in the pipeline
