### ISSUE TITLE
Broken encoding for @Bean in reference documentation

### ISSUE THREAD

**Issue by sahrawat** [spring-projects/spring-boot#21908]
Quoting https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/htmlsingle/#production-ready-metrics-web-flux

> To add to the default tags, provide one or more <code>@Bean&grave;s that implement &grave;WebFluxTagsContributor</code>

I suppose it's a encoding problem.

**Comment by snicoll** [comment]
@sahrawat good catch, thank you for reporting it.
