### ISSUE TITLE
Upgrade Spring Retry to 1.3.0

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-boot#21901]
> - Managed Dependency Upgrade
You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release.

Somehow this wasn't updated for 2.2.8/2.3.1 🤔

**Comment by philwebb** [comment]
We have a policy of only upgrading patch releases once we've made a release. That means for Spring Boot 2.3.x we'll be keeping with Spring Retry 1.2.x. We'll upgrade to Spring Retry 1.3 when we release Spring Boot 2.4.
