### ISSUE TITLE
Create a default certificate and turn on SSL by default.

### ISSUE THREAD

**Issue by jliu666** [spring-projects/spring-boot#21907]
The creation of SSL certificate is complex. Using HTTP alone is not enough security. Creating SSL certificate automatically and opening it by default can improve the security of the whole network. Of course, this is just my point. You can close this issue at any time. 
But I still think that automatically creating SSL certificates can be a part of spring boot auto configuration and we can add a switch to it.

**Comment by bclozel** [comment]
Closing as a duplicate of #6148

Thanks!
