### ISSUE TITLE
Document Kafka metrics support

### ISSUE THREAD

**Issue by hoplers** [spring-projects/spring-boot#21910]
Spring Boot 2.3 release notes states that it now supports native consumer & **producer** metrics (i guess this was implemented here - https://github.com/spring-projects/spring-boot/issues/20838), but documentation (latest,2.3.0,2.3.1,2.3.2) states that only kafka consumer metrics are supproted natively - for example https://docs.spring.io/spring-boot/docs/2.3.2.BUILD-SNAPSHOT/reference/htmlsingle/#production-ready-metrics-meter

**Comment by snicoll** [comment]
@hoplers good catch. I've also added a small section to provide additional details and link to Spring Kafka's documentation.

**Comment by hoplers** [comment]
Awesome, thank you!
