### ISSUE TITLE
Spring REST not returning message during errors

### ISSUE THREAD

**Issue by nikhilteja** [spring-projects/spring-boot#22027]
**Only observed with spring-boot-starter-parent 2.3.0.RELEASE and 2.3.1.RELEASE**

Whenever there's any error (bad request, internal server error or even custom ResponseStatusException), the error response returned to the client only has the HttpStatus code and message/reason/error are always empty (despite giving explicit reasons too).

I tried multiple times and downgraded to 2.2.8.RELEASE and found it be working as expected. Did something break in 2.3.0.RELEASE and above wrt to web dependencies?

**Comment by knoobie** [comment]
You can find more about this change here https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content

**Comment by snicoll** [comment]
Thanks @knoobie 

@nikhilteja please consider reading [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) before opening an issue.

**Comment by nikhilteja** [comment]
Thanks @knoobie for the quick reply.

Sorry @snicoll , yup, should've read release notes first.
