### ISSUE TITLE
Remove code deprecated in 2.2

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#22034]
Most code marked as deprecated since 2.2 was removed in 2.3, before we decided that it would be better to [leave deprecated APIs in place for two minor releases before deleting](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#release-compatibility). Following this direction, code marked as deprecated since 2.2 should be removed in 2.4. 

See issues #19597 and #19860, as well as commits https://github.com/spring-projects/spring-boot/commit/de1a26cf35b260fdf1133742cce00e64d31d033f and https://github.com/spring-projects/spring-boot/commit/afb67887da5586353f71fe4d79d23431d69bc3f2.

**Comment by mla-mpensdavila** [comment]
Hi @scottfrederick, just to be sure, do we need to remove all the code marked as deprecated in the version 2.2.x

**Comment by philwebb** [comment]
@mla-mpensdavila The plan is to remove the code deprecated since 2.2 but it's probably best if we handle this one since we need to co-ordinate with the Spring Clould team.

**Comment by mla-mpensdavila** [comment]
Hi @philwebb, i would like to help, can you guide me what i need to do? and How i can coordinate this?

**Comment by philwebb** [comment]
Thanks for the offer @mla-mpensdavila, but since we need to chat with other Spring teams it's best if we handle this one ourselves.

**Comment by mla-mpensdavila** [comment]
> Thanks for the offer @mla-mpensdavila, but since we need to chat with other Spring teams it's best if we handle this one ourselves.

Great, thanks for the info, I'll looking another task to do..
