### ISSUE TITLE
ResponseStatusException is not returning the error message with Springboot 2.3.1

### ISSUE THREAD

**Issue by KapilBhandari** [spring-projects/spring-boot#22033]
**Affects:** \<Spring Framework version>

---

**Comment by snicoll** [comment]
Please consider [reading the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content) before upgrading. Thank you.

**Comment by julyusandreas** [comment]
Add this
server.error.include-message=always
to application.properties
