### ISSUE TITLE
ResponseStatus annotation's reason property is not being set

### ISSUE THREAD

**Issue by mcanessa** [spring-projects/spring-boot#22046]
Hello everybody, I have a problem with the following code:
```java
@RestController
public class DemoController {
    @ExceptionHandler(IllegalArgumentException.class)
    @ResponseStatus(value = HttpStatus.BAD_REQUEST, reason = "no reason at all")
    public void illegalArgumentException() {
    }

    @GetMapping(value="try/{option}")
    public ResponseEntity<String> tryOption(@PathVariable String option){
        if(!"ok".equals(option))
            throw new IllegalArgumentException();
        return ResponseEntity.ok("Everything is ok!");
    }
}
```

Using spring boot 2.2.7.RELEASE works as expected when requesting:
http://localhost:8080/try/nok
The result is a status = 400 and reason = "no reason at all".

However, if I update the version to spring boot 2.3.0.RELEASE + (tried with 2.3.1.RELEASE also), the same example returns status=400 and no reason.

thanks in advance.
regards,

**Comment by bclozel** [comment]
Indeed, [this is an expected change underlined in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content).

Thanks!
