### ISSUE TITLE
logging.config configuration item is invalid in springboot

### ISSUE THREAD

**Issue by fzustone** [spring-projects/spring-boot#22044]
hello, I create a springboot project by https://start.spring.io/,and then i add logback jar in pom file.i create a `logback.xml` in `resources/config/ ` and add `logging.config=classpath:config/logback.xml` ,look this pic
![image.png](https://i.loli.net/2020/06/18/iVCnA45qaWQgFLf.png)
start via war package,I found that the configuration in yml cannot be recognized.look at it:
![image.png](https://i.loli.net/2020/06/19/epracFVZxjBtH4Q.png)
I found this related to tomcat version.tomcat 8.5.46 and below will have problems, but 8.5.55 and above are no problem.

**Comment by wilkinsona** [comment]
Tomcat used to set a `LOGGING_CONFIG` environment variable. This would override `logging.config`. This was changed in Tomcat 8.5.54:

> Deprecated the `LOGGING_CONFIG` environment variable and replace it with the `CATALINA_LOGGING_CONFIG` environment variable to avoid clashes with other components that use `LOGGING_CONFIG`. (markt)

You should upgrade to Tomcat 8.5.54 or later.

**Comment by fzustone** [comment]
Thank you for your reply
