### ISSUE TITLE
Consider using layered option as default for Buildpacks image

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#22043]
It seems to be good to use layered option as default for Buildpacks image.

I'm not familiar with Buildbacks, so I might miss something.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @izeye.

We try to avoid having different defaults for different usages so we wouldn’t want image building to default to a layered jar when building a fat jar does not. We could avoid this by making a layered jar the default across the board. This would then require some syntax to disable it which, when considering it in the past, we felt could be quite confusing.

The other thing to consider here is that a layered jar being understood depends on the builder that you are using and the capabilities of its buildpacks. Enabling layering by default when the builder may not understand the layering metadata may also cause some confusion.

All in all, I think it’s less confusing if layered jars require opting in at this time.
