### ISSUE TITLE
how about writing a offical guide for how to write a spring boot starter?

### ISSUE THREAD

**Issue by XSun771** [spring-projects/spring-boot#22041]
I've tried to google "spring boot starter inurl:spring.io/guide" and the result is depressing. There are some good articles about writing a spring boot starter, but I still hope to get a offical guide so as to solve my confusion:
If i just need annotations like @ConditionalOnClass, @Configuration, @Bean, and the project, the starter I write, will only be an denpendency in another spring boot project, is it still necessary to import spring boot using
```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.4.RELEASE</version>
    </parent>
```
?

Thanks a lot.

**Comment by wilkinsona** [comment]
Have you seen the [section about writing your own auto-configuration and starter](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-developing-auto-configuration) in the reference documentation? It covers  `@Configuration`, `@Bean`, `@ConditionalOn…`, the use of `spring.factories` etc.

If you’d like to see a guide on this subject, you can request one by opening [an issue](https://github.com/spring-guides/getting-started-guides/issues) in the `getting-started-guides` project.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
