### ISSUE TITLE
Extending the ResponseEntityExceptionHandler class for validation in SB 2.3.0 / 1. 

### ISSUE THREAD

**Issue by harjeetp** [spring-projects/spring-boot#22050]
Hi Team,

I have successfully `extended` the `ResponseEntityExceptionHandler` class to perform validation. It was successfully in SB version 2.2.7.RELEASE. Unfortunately, I am not able to replicate the same successful validation behavior by `extending` the `ResponseEntityExceptionHandler` class in SB 2.3.0.RELEASE or 2.3.1.RELEASE. Any guidance around this issue would be very helpful.

Thanks,

-h

**Comment by scottfrederick** [comment]
Thanks for the report. We'll need more information to be able to provide guidance on what's not working for you. The `ResponseEntityExceptionHandler` interface is provided by Spring Framework, not by Spring Boot, so it's not clear which project is involved in this issue. 

If you would like us to spend some time investigating, please provide more detail on what you mean by "not able to replicate the same successful validation behavior", including any error messages you are getting. A minimal sample that reproduces the problem would be ideal.

**Comment by wilkinsona** [comment]
@harjeetp Have you added a dependency on `spring-boot-starter-validation`, as described in the [release notes for 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters)?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by harjeetp** [comment]
> @harjeetp Have you added a dependency on `spring-boot-starter-validation`, as described in the [release notes for 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters)?

Dear Andy,

I had not seen that note. I made the changes based on that note, and everything works as expected with the validation. Thank you for all your help.

Harjeet

**Comment by scottfrederick** [comment]
@harjeetp Thanks for the update. Marking this as a duplicate of other validation-related issues.
