### ISSUE TITLE
Please do something like ReactJS with Java and Thymeleaf so that we don't need another thing for Front-end.

### ISSUE THREAD

**Issue by ibnshayed** [spring-projects/spring-boot#22079]
Now we can interact with thymeleaf that works same as HTML... if you can use Java like javascript anyhow . I think spring will be full fill for full stack development. I think it's very easy . just we need to implement it.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but a ReactJS equivalent implemented using Java and Thymeleaf is out of the scope of this project.
