### ISSUE TITLE
Limit JLine to 2.11

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22072]

**Comment by wilkinsona** [comment]
The upgrade breaks `EscapeAwareWhiteSpaceArgumentDelimiter`. Given that JLine is only used in the CLI, spending time addressing the breaking changes does not feel worthwhile. Let's restrict JLine to 2.11 instead.

**Comment by dreis2211** [comment]
I already tried upgrading this in the past as well. It breaks not just the delimiter but more, so I can only second that.
