### ISSUE TITLE
Improve error handling in JDK upgrade checks

### ISSUE THREAD

**Issue by spring-buildmaster** [spring-projects/spring-boot#22098]

**Comment by dreis2211** [comment]
What about just adding `set -e` on top? That should probably exit the script before it tries to create the issue. What do you think? I can provide a PR for that.

**Comment by wilkinsona** [comment]
That would certainly be better than how it behaves at the moment. I was wondering if we should output the response that couldn't be parsed so that we can be sure that it was just a glitch rather than a breaking change in the format of the response.

**Comment by dreis2211** [comment]
I'm currently playing around with more incremental steps and additional checks. Since I'm hitting that at the moment and I can't see the logs of the build unfortunately to see where it exactly failed: maybe it's related to rate-limiting? This produces another result which can't be parsed.

**Comment by wilkinsona** [comment]
Closing in favour of #22110.
