### ISSUE TITLE
Not able to startup webapp inside of Tomcat

### ISSUE THREAD

**Issue by csavory** [spring-projects/spring-boot#221]
I can start my app (as a jar) from the command line, but as soon as I try to start from Tomcat (as a war) I get a a startup error.

SpringServletContainerInitializer will loop through all the WebApplicationInitializer that it finds:

``` java
        for (WebApplicationInitializer initializer : initializers) {
            initializer.onStartup(servletContext);
        }
```

SpringBootServletInitializer is found and and its onStartup is called.

SpringBootServletInitializer will create a new SpringApplicationBuilder on line 81:

``` java
SpringApplicationBuilder application = new SpringApplicationBuilder();
```

this is not passing any sources into the constructor.  

Then on line 328 of SpringApplication there is an Assert that fails.

``` java
Assert.notEmpty(sources, "Sources must not be empty");
```

Am I configuring this wrong?  I have tried several versions and even dropping back to 0.5.0.M7 and M6.

**Comment by nedjs** [comment]
After a few hours of looking around online and digging through your source code I ended up with the following solution which changes the field names after the fact to conform to your ObjectMappers style. Couldnt find any fix anywhere. Maybe someone will find some use for it here

```java
    @Component
    public class SwaggerNamingStrategyBuilderPlugin implements ModelPropertyBuilderPlugin {

        private final ObjectMapper mapper;

        @Autowired
        SwaggerNamingStrategyBuilderPlugin(ObjectMapper objectMapper) {
            this.mapper = objectMapper;
        }

        @Override
        public void apply(ModelPropertyContext modelPropertyContext) {
            String oldName = modelPropertyContext.getBuilder().build().getName();

            String newName = mapper.getPropertyNamingStrategy().nameForField(mapper.getDeserializationConfig(), null, oldName);
            modelPropertyContext.getBuilder().name(newName);
        }

        @Override
        public boolean supports(DocumentationType documentationType) {
            return SwaggerPluginSupport.pluginDoesApply(documentationType);
        }
    }
```

**Comment by dsyer** [comment]
@nedjs I don't think that's even vaguely relevant to this (closed) issue. If you have a usage question please go to stackoverflow. If you have an issue you want to raise with the Spring Boot team, pleas open a new one (with a bit more context to explain what you need than you provided so far please).

**Comment by nedjs** [comment]
@dsyer Oh my, sorry about that. I posted this on the wrong gosh darn issue last night in my tired haze. Sorry about that
