### ISSUE TITLE
Temporary files not cleaned up after Maven plugin execution

### ISSUE THREAD

**Issue by ancoron** [spring-projects/spring-boot#22108]
Whenever executing a Maven project build (with or without tests - doesn't matter), exactly two temporary files are left in place without any content, e.g.:

```
-rw-rw-r-- 1 ancoron ancoron 0 Jun 25 14:23 /tmp/springboot-11563970946139969408-entrycontent
-rw-rw-r-- 1 ancoron ancoron 0 Jun 25 14:23 /tmp/springboot-5070898860288932403-entrycontent
```

The only reference I found to this pattern was from the [SizeCalculatingEntryWriter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/SizeCalculatingEntryWriter.java#L102).

As everyone can see, using the temporary file is optional, although created every time and there is no safe-guard that would delete those files on JVM exit.

This means that over time, the temporary directory gets flooded with empty files.

**Comment by wilkinsona** [comment]
Closing in favour of #22112.

**Comment by wilkinsona** [comment]
Looking at this more closely, I'd like to understand the need for the temporary file. Presumably there were entries of an unknown size that are too large to be dealt with in memory. If that's the case, I'd expect them to also be too large when writing unpack comments as it currently does everything in memory as well. It may be that, as the unpack comments are opt-in, we just haven't seen the problem yet.

**Comment by philwebb** [comment]
Closing in favor of PR #22112. I've also opened #22305 to see if we can find a better long-term solution.
