### ISSUE TITLE
Remove spring.rabbitmq.publisher-confirms from additional metadata

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#22123]
See https://github.com/spring-projects/spring-boot/commit/8f102aee6862b92a8e4c5db7a30527db05a2b183#r40196934

**Comment by wilkinsona** [comment]
Could that be an IDE bug? Is the error level not meant to result in it being flagged as an error in the IDE so you know you have to change or remove it?

**Comment by bclozel** [comment]
I'm getting the same behavior in Intellij IDEA:

![image](https://user-images.githubusercontent.com/103264/86477118-15d81880-bd48-11ea-9269-b88d7c56d9b8.png)

Our reference documentation says:

> The level of deprecation, which can be either warning (the default) or error. When a property has a warning deprecation level, it should still be bound in the environment. However, when it has an error deprecation level, the property is no longer managed and is not bound.

So as a matter of fact, the "error" level is correct here.
