### ISSUE TITLE
EnumSet.copyOf calls fail with empty collections

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22128]
Both `SecurityFilterAutoConfiguration` and `SessionRepositoryFilterConfiguration` use `EnumSet::copyOf` in a stream. If the stream ends up being empty then the `copyOf` method will throw an exception.

**Comment by DogeC0in** [comment]
I find that SessionProperties.Servlet#setFilterDispatcherType(Set<DispatcherType> filterDispatcherTypes),when filterDispatcherTypes have a null element，the bug will be reproduce.So,what do I think filterDispatcherTypes have empty element or not there?

**Comment by wilkinsona** [comment]
Closing in favour of https://github.com/spring-projects/spring-boot/pull/22138#pullrequestreview-438712825.
