### ISSUE TITLE
@Valid Annotation not found

### ISSUE THREAD

**Issue by Aragami1408** [spring-projects/spring-boot#22144]
Hey there!

When I started a new Spring Boot Project. I just creating controller normally till I found out that `@Valid` Annotation is not recognized and basically can't be founded.

![image](https://user-images.githubusercontent.com/25903678/86004893-22096080-ba3e-11ea-94ec-6b1863ef85f8.png)

Even I imported the package that contains the annotation:

![image](https://user-images.githubusercontent.com/25903678/86005002-45341000-ba3e-11ea-8a9e-7ab24da25bb5.png)

Is that the new bug or something?

**Comment by wilkinsona** [comment]
As of Spring Boot 2.3, if you want to use bean validation and Hibernate Validator, you must add a dependency on `spring-boot-starter-validation` as [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters).

**Comment by YShane** [comment]
I don't want to say this should me more prominent, but I'll say it any way.

**Comment by Abhishek9166919669** [comment]
I have also faced the same issue  and I am able to solve the issue by  adding  Sprign-boot-validator dependency  in pom.xml file 

from Spring Boot 2.3.0 we need to add below dependency in our project.

      

Hope this will help you.
