### ISSUE TITLE
Enhancement: extends @RestControllerEndpoint by @Component

### ISSUE THREAD

**Issue by rfelgent** [spring-projects/spring-boot#22145]
Hello community,

I would like to request an enhancement: could you extend the `@RestControllerEndpoint` with the `@Component` per default.
I think this enhancement would be in alignment with other default Meta-Annotations.
Furthermore, I "lost" some time figuring out why my custom Actuator endpoint was not registrered automatically...

If there is more support for this idea, I could provide a pull request, too.

Best regards

**Comment by wilkinsona** [comment]
Thanks for the suggestion. None of the `@…Endpoint` annotations are meta-annotated with `@Component` as we don't consider endpoints to be a specific type of component. They're as likely to be defined using `@Bean` methods as they are using component scanning.
