### ISSUE TITLE
Whitelabel Error

### ISSUE THREAD

**Issue by mehmetanbaki** [spring-projects/spring-boot#22140]
I have this issue and tried out every solutions in stackoverflow and here and didn't work. I'm pretty sure a lot face this problem 

    Whitelabel Error Page

    This application has no explicit mapping for /error, so you are seeing this as a fallback.

    Sat Jun 27 20:26:22 AST 2020
    There was an unexpected error (type=Not Found, status=404).

**Comment by wilkinsona** [comment]
This is Spring Boot’s default error response. As far as I can tell, you have attempted to access a URI which is unknown to your application. This results in a not found (404) error response being sent. As there error is no specific error response configuration, the default is being sent. In short, without some more information everything seems to be working as designed.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by mehmetanbaki** [comment]
@wilkinsona 
I figure it out I didn't give more attention for the exact path when give it the exact path it's work fine so it's done thanks a lot
