### ISSUE TITLE
Support incremental annotation processing with Gradle

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22150]
See #16603 for background. The actual fix will be slightly more complex as we'll need to unwrap some Gradle types.

**Comment by renjfk** [comment]
This is still failing with error `Full recompilation is required because '@Override' has source retention. Aggregating annotation processors require class or runtime retention.`

**Comment by wilkinsona** [comment]
@renjfk Thanks for letting us know. I'm not sure I fully understand the connection between `@Override` and Boot's annotation configuration properties annotation processor. It doesn't look at `@Override` but I wonder if Gradle's is being confused as the annotation processor declares that it supports all annotation types.

To help us to investigate, can you please open a new issue with a minimal sample that reproduces the behaviour you have described?

**Comment by wilkinsona** [comment]
With thanks to @ve2m, we now have a new issue and sample: https://github.com/spring-projects/spring-boot/issues/23580.
