### ISSUE TITLE
https://repo.spring.io is failing

### ISSUE THREAD

**Issue by sergiofigueras** [spring-projects/spring-boot#22154]
Hello folks,

Unfortunately, this was the only way that I've found to report this issue. I'm sorry if it is not the correct place. If it is not, please lemme know what another way I should do.

https://repo.spring.io/release is failing occasionally while we are reloading the page. Half of the times that I try to load https://repo.spring.io/release, it fails with:
<img width="728" alt="Screen Shot 2020-06-29 at 20 48 50" src="https://user-images.githubusercontent.com/1733227/86066957-fc825400-ba49-11ea-9d47-bdf99d9f81b8.png">

During the other half, it presents properly the results with:
<img width="557" alt="Screen Shot 2020-06-29 at 20 49 30" src="https://user-images.githubusercontent.com/1733227/86066976-0c9a3380-ba4a-11ea-89c4-a74d72037985.png">

I've tried from 4 different connections, even using an US connection, and I got the same issue.

Thanks.

**Comment by mbhave** [comment]
Thanks for letting us know, but there's nothing that the Spring Boot project can do to fix that. Our ops team is already aware.

**Comment by sergiofigueras** [comment]
Thanks @mbhave , but just in case of a next glitch: should I report it here or in any other way? Thanks.

**Comment by wilkinsona** [comment]
@sergiofigueras https://twitter.com/springops Is a good way to see what we’re already aware of and to let us know about anything else.
