### ISSUE TITLE
gradle tasks bootBuildImage does not support setting mirror

### ISSUE THREAD

**Issue by fangzhengjin** [spring-projects/spring-boot#22161]
Due to China's special network environment, it is not possible to access the gcr service. Can you provide mirror settings to obtain paketo-buildpacks mirrors from other locations?

For paketo-buildpacks/builder:base-platform-api-0.3 images can currently be set by builder parameters, but paketo-buildpacks/run:base-cnb images cannot be set by parameters, is there any other way to change the mirror address?

**Comment by scottfrederick** [comment]
The ability to specify an alternate run image in build configuration or on the command line is covered by #21534. Once this is released in 2.3.2, you will be able to override both the builder image and run image to use a mirror instead of gcr.
