### ISSUE TITLE
Failed to create ES mapping when using spring-data-elasticsearch

### ISSUE THREAD

**Issue by QiangYoung** [spring-projects/spring-boot#22181]
I am using spring-data-elasticserach-4.0.0.RELEASE. 
According to [elasticsearch guide](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/term-vector.html), the _term_vector_ can be: **with_positions_offsets** .

But in: org.springframework.data.elasticsearch.annotations.TermVector, provide **woth_positions_offsets**. 
When i use this value to create mapping, got an error: _wrong value for termVector [woth_positions_offsets]_
Is it right? Or just spelling mistake?

**Comment by wilkinsona** [comment]
That looks like a bug in Spring Data Elasticsearch to me. They use [JIRA](https://jira.spring.io/browse/DATAES) for issue tracking. Can you please open an issue over there and comment here with a link to it?

**Comment by QiangYoung** [comment]
[Wrong value for TermVector(woth_positions_offsets)](https://jira.spring.io/browse/DATAES-878) 
#https://github.com/spring-projects/spring-data-elasticsearch/pull/492
