### ISSUE TITLE
Jetty with Conscrypt no longer a requirement for easy HTTP/2

### ISSUE THREAD

**Issue by joakime** [spring-projects/spring-boot#22188]
Starting with Java 8u252 (note: not 8u251) the ALPN layer has been backported from Java 11 back to Java 8.

The mandated use of Conscrypt with Jetty for HTTP/2 (in SpringBoot) is now no longer a requirement.
You can use Jetty and HTTP/2 without the need for a bootclasspath or an agent, as long as you use Java 8u252 or newer.

There is also a lack of documentation about how to disable the Conscrypt provider when using Jetty with SpringBoot.

**Comment by bclozel** [comment]
I'm scheduling this as a documentation improvement for [this section of the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-configure-http2). Depending on the outcome of this, we might also repurpose this issue as an enhancement for removing the conscrypt requirement.

**Comment by sunng87** [comment]
By the way it's not just a doc change. The Jetty's `SslServerCustomizer` still requires conscrypt as SSL provider. The conscrypt library has serious memory leak issue. So it would be nice to use JDK based provider or at least configurable.

**Comment by bclozel** [comment]
We've improved the auto-configuration to be more flexible and allow several deployments: JDK9+, JDK8u252+ or Conscrypt. We're also now guiding developers if there's a missing `jetty-alpn-*-server` dependency. We've updated the documentation accordingly.
