### ISSUE TITLE
Fail with exception if management.server.address is set but actuator is on the same port

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22187]
As discovered in #22142, it's possible to have a `management.server.address` that doesn't get applied if the `ManagementPortType` is `SAME`. It would be better if we failed hard instead of ignoring the property.

**Comment by pcornelissen** [comment]
Just to reiterate, it may be also a good idea to add a note in the documentation of management.server.port that it requires server.port to be set when the real port is on a different port and management.server.port is supposed to be 8080.
This is a very hard to track down bug when your settings are ignored in the way it is now.
Or maybe you should force server.port to be set when the management.server.port is set, just to be safe. This would make things easier to document and shouldn't be a big burden.
