### ISSUE TITLE
Ability to provide latency of cascased backend calls through spring-boot-actuator framework

### ISSUE THREAD

**Issue by debashish-github** [spring-projects/spring-boot#22205]
Hi,
   I have a Http Rest End Point that internally calls some other Http Rest Endpoints (backends) . I know actuator framework gives overall latency of the http requests to my end Point . 
But is there  a way to even get a breakup of the latency of all other backend http endpoints my rest API calls .

So for Example my API  say API 1  is using actuator framework for getting metrics.
My API1 calls API2 and API3  and combines the results to return the response ..
Actuator framework gives me latency information for may API1 .. But does it have the ability give the latency for API2 and API3..

So for example if the overall latency of API1 is 5 seconds out of which API 2 consumes 1 second and API3 consumes 2 seconds ..
and the residual 2 seconds is consumed by my servers processing ..
Is there a way to get the latency metrics for API2 and API3 as well ?

Thanks
Debashish

**Comment by bclozel** [comment]
You might be interested in https://spring.io/projects/spring-cloud-sleuth

Thanks!
