### ISSUE TITLE
Spring Data JDBC - Postgres JSONB

### ISSUE THREAD

**Issue by kviesi** [spring-projects/spring-boot#22219]
how to use a jsonb (Postgres) with spring data jdbc?

Caused by: org.postgresql.util.PSQLException: ERROR: column "extradata" is of type jsonb but expression is of type character varying
  Dica: You will need to rewrite or cast the expression.

**Comment by wilkinsona** [comment]
Spring Data JDBC is managed as a separate project. You can learn how to get some help in [this section](https://github.com/spring-projects/spring-data-jdbc#getting-help) of the project’s README.
