### ISSUE TITLE
Include system scoped artifacts in repackage goal

### ISSUE THREAD

**Issue by frisco82** [spring-projects/spring-boot#2224]
Currently only runtime, compile and provided are included in the final jar when repackaging for a runnable jar, given that provided are already being packaged it makes sense that system scoped artifacts can be included too.

The simplest workaround is setting a private maven repo but if you are using system scope usually you can not set up your own maven repo.

**Comment by xfcjscn** [comment]
Base on my understanding, the system scope defined by maven means it will be available in both compile & runtime. 
So it's reasonable to support system scoped jar included in runtime lib via repackage.

**Comment by huima** [comment]
Looking forward to this! 

Usecase where I see this is with some wrapper libraries not available in maven - and CI server being operated centrally and not liking people adding stuff to repositories on their own, or running own repositories.

**Comment by snicoll** [comment]
@xfcjscn that's actually not accurate: `system` is exactly like `provided`. Since Spring Boot embeds the actual process, we have a specific way of handling `provided` dependencies. From that perspective, it makes sense indeed to handle `system` scoped dependencies as well.

**Comment by snicoll** [comment]
There is an `includeSystemScope` that you can use to add system-scope dependencies to the fat jar.

**Comment by Turbots** [comment]
Nice work @snicoll !!

**Comment by beijingzhangwei** [comment]
perfect!!! @snicoll
