### ISSUE TITLE
It would have been better if the release notes for Spring Boot 2.3.0 contained a hint about a breaking change in the Jackson dependency

### ISSUE THREAD

**Issue by Bas83** [spring-projects/spring-boot#22259]
In the release notes of Spring Boot 2.3.0 at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes there is no mention of a breaking change in the Jackson update to version 2.11.0 which formats the timezone offset with an additional colon, as per issue at https://github.com/FasterXML/jackson-databind/issues/2643

While we should have found this ourselves too (we didn't use exact String testing in our tests but immediately parsed to our DTO's too), this resulted in us finding out by a customer integrating with our API contacting us about it. We have updated our tests with some more low-level String validation, however it would have been nice to find out about this in the release notes of Spring Boot too. I understand this comes from a dependency update but it is rather important. As mentioned in the Jackson ticket they have additional plans to use Z instead of 00:00 for zero offsets: 
_"Yes, retain 00:00 for the 2.x line and move fully to XXX in 3.0. I wouldn't really touch that in 2.x as it cause too many confusion with broken stuff out there. Don't make the hodge-podge even worse for now."_
So be aware this will happen again in Jackson 3.0 as well.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I've added a [small section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#jackson) to the release notes.
