### ISSUE TITLE
Mention buildpacks in the introduction to the section on building Docker images

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22279]
The [section on building Docker images](https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/html/spring-boot-features.html#building-docker-images) makes no mention of buildpacks until you reach the [buildpacks subsection](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#buildpacks). We should provide a high-level overview of the two options (Dockerfile and using buildpacks) in the introduction so that the reader can then go straight to the subsection that's of most interest to them.

**Comment by philwebb** [comment]
Closing in favor of PR #22296
