### ISSUE TITLE
Update documentation to reflect the web server now being started immediately before the ContextRefreshedEvent is published

### ISSUE THREAD

**Issue by ykalemi** [spring-projects/spring-boot#22277]
There are some behavior changes in Spring Boot 2.3.0. This issue #21325 commit introduced new Web Server lifecycle logic - WebServerStartStopLifecycle. And now there is this order during an applicaton startup:

1. WebServerStartStopLifecycle.start -> webServer.start
2. publishEvent(new ContextRefreshedEvent(this));

In Spring Boot 2.2.0 there was another logic (ServletWebServerApplicationContext.java):

```
protected void finishRefresh() {
    super.finishRefresh();
    WebServer webServer = startWebServer();
    if (webServer != null) {
        publishEvent(new ServletWebServerInitializedEvent(webServer, this));
    }
}
```
And order was like this:

1. publishEvent(new ContextRefreshedEvent(this));
2. webServer.start 

We run some logic after the Spring context has been initialized but before web server started. With Spring Boot 2.3.0 web server processes requests before this logic is done.

If it is an expected change of events order, it should be mentioned in migration guide.

**Comment by wilkinsona** [comment]
It is expected, but it looks like we have a bit of tidying up to do after that change, both in the migration guide and in a few places in the code. Thanks for letting us know.

**Comment by ykalemi** [comment]
@wilkinsona thanks for your answer.
Is there another possibility to run some code after context has been initialized but before web server started? Should there be some other extension point for this?

**Comment by wilkinsona** [comment]
Generally, we expect that sort of work to be done as part of the usual bean lifecycle. There are lots of different options depending on exactly what you want to do. For example, the code could be run:

- as part of a bean's construction
- in a `@PostConstruct` method
- in `afterPropertiesSet()` having implemented `InitializingBean`
- in `start()` having implemented `Lifecycle` or `SmartLifecycle`
