### ISSUE TITLE
Support redis-socket:// URLs when configuring a Redis client

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#22273]
This is related to #21920. 

Spring Data Redis has a `RedisSocketConfiguration` that can be used to configure a Unix domain socket connection to Redis. The Lettuce client [supports domain socket configuration](https://lettuce.io/core/release/reference/#unix-domain-sockets) with URLs like `redis-socket://redis/redis.sock`. 

If we decide to support `redis-sentinel://` URLs in `spring.redis.url`, we might also want to support `redis-socket://` URLs.

**Comment by snicoll** [comment]
Closing in favor of PR #27373
