### ISSUE TITLE
Support loading external configuration from files with no file extension

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22280]
See https://github.com/microsoft/azure-spring-boot/issues/926 and https://github.com/spring-projects/spring-boot/issues/22278 for background. Azure does not allow `.` characters in the name of a secret file so you have to jump through a renaming hoop to add the `.properties` or `.yaml` suffix.

**Comment by philwebb** [comment]
We'll look at supporting a new syntax for this. Something like `spring.config.location=/etc/application[.properties]` where the `[.properties]` isn't part of the filename, but just a hint for the content type.
