### ISSUE TITLE
2.3.1.RELEASE doesn't respect logging.path property in application.properties file. The logging file was not generated.

### ISSUE THREAD

**Issue by parisana** [spring-projects/spring-boot#22295]

**Comment by wilkinsona** [comment]
You should be using `logging.file.path` with Sprinf Boot 2.2 and later. `logging.path` was deprecated in 2.2 in favour of `logging.file.path` it was then removed in 2.3.

**Comment by parisana** [comment]
Hi Andy,

Thanks a lot. I should have done more research into it before asking the
question.
