### ISSUE TITLE
Warn user when using parallelStream within a @Transactional DAO method

### ISSUE THREAD

**Issue by tanmaylaud** [spring-projects/spring-boot#22319]
Enhancement:
The user should be warned when using .parallelStream() in a method annotated with @Transactional

Consider the following example: 

    @Autowired
    Repository  jpaRepo;

    @Transactional
    public void mySaveMethod( List records) {
    
       records.parallelStream().forEach( record ->
                  jpaRepo.save(record)
        );
     
   }

// Here the transaction boundary will be maintained per Parallel Thread. In some cases, user might require (and expect) a global transaction boundary which above method does not provide.

**Comment by scottfrederick** [comment]
Transactional behavior of repositories is implemented by the various Spring Data projects, not by Spring Boot.

You can ask questions about Spring Data on [StackOverflow](https://gitter.im/spring-projects/spring-data) or [gitter](https://gitter.im/spring-projects/spring-data?utm_source=share-link&utm_medium=link&utm_campaign=share-link), or file an issue in one of the [Spring Data projects in Jira](https://jira.spring.io/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all&contains=spring+data&sortColumn=name&sortOrder=ascending&s=view_projects).

**Comment by tanmaylaud** [comment]
> Transactional behavior of repositories is implemented by the various Spring Data projects, not by Spring Boot.
> 
> You can ask questions about Spring Data on [StackOverflow](https://stackoverflow.com/questions/tagged/spring-data) or [gitter](https://gitter.im/spring-projects/spring-data), or file an issue in one of the [Spring Data projects in Jira](https://jira.spring.io/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all&contains=spring+data&sortColumn=name&sortOrder=ascending&s=view_projects).

@scottfrederick  thanks for the suggestion :)
