### ISSUE TITLE
How to add extra operations for spring boot + buildpacks image

### ISSUE THREAD

**Issue by fangzhengjin** [spring-projects/spring-boot#22310]
When using gradle + spring boot + buildpacks, how to add operations other than code to the image?
The most common operation is to set the time zone for the mirror.When there is a Dockerfile file, I only need to add the RUN command to easily set the time zone.
But in buildpacks, I feel very confused and don't know how to add commands

**Comment by wilkinsona** [comment]
This is something that isn't as easy as we'd like at the moment. If you want to set the timezone in every image that you build, a custom builder that does so automatically without requiring any further configuration is probably your best option. Alternatively, you can use `JAVA_OPTS` and `-Duser.timezone` when running the image as described in [this comment](https://github.com/spring-projects/spring-boot/issues/21478#issuecomment-630265660). You may also be interested in [this discussion](https://paketobuildpacks.slack.com/archives/C0124SD3GTG/p1589813637001200) in the [Paketo slack](https://slack.paketo.io/).

I'm going to close this issue in favour of #21478, #21582 and the discussion on the Paketo Slack.
