### ISSUE TITLE
spring-boot-starter-data-rest 1.2.0 generates links using http instead of https

### ISSUE THREAD

**Issue by hg-schneider** [spring-projects/spring-boot#2232]
I have written a spring boot application which is using `spring-boot-starter-data-jpa`.
The application is configured to use https only. When I use Version 1.1.10 the generated links in the documents send by the server are using https as a protocol. If I switch to version 1.2.0 the links are generated with http protocol, which is not available in my application.

To reproduce this I've provided a simple example. This is a slightly changed version of the gs-accessing-data-rest example (https://github.com/hg-schneider/gs-accessing-data-rest).

In the complete folder I've changed the build to use jetty and enabled https. If you checkout HEAD which is using spring boot version 1.2.0, run the application and curl it with `curl -k https://localhost:8443` you receive a document with links using http.

If you checkout the previous commit (`git checkout  c9b04504`) you get the same sources but using spring boot 1.1.10. Running this and curl it again with `curl -k https://localhost:8443` you will receive a document with links using https links.

Thanks for developing spring.

**Comment by philwebb** [comment]
Thanks for the reminder. I've added a test now (and also tested with reverted commits to make sure it fails without the fix).
