### ISSUE TITLE
Spring Boot 2.3.1 application.yml logging.file not work

### ISSUE THREAD

**Issue by zengfan2** [spring-projects/spring-boot#22333]
When I want output logging to file, it not work. It works on 2.2.5, I want this feature.

**Comment by wilkinsona** [comment]
@zengfan2 Please take a moment to search for existing issues before opening a new one. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/21627 and https://github.com/spring-projects/spring-boot/issues/21479.

**Comment by zengfan2** [comment]
but logging.file.name not work too

**Comment by zengfan2** [comment]
Thanks
