### ISSUE TITLE
Javadoc does not work with Java 8

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2233]
Java 8 introduced more agressive checks on default when generating javadoc. This prevents a full build of Boot using Java 8 when such task is enabled (full profile)

```
[ERROR] /Users/snicoll/workspace/pivotal/spring-boot/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/DependencyFilter.java:65: warning: no @param for dependency
[ERROR] protected final boolean equals(Artifact artifact, FilterableDependency dependency) {
[ERROR] ^
```

Note that some errors are legit so we should review them before disabling checks that aren't enabled with Java 7

**Comment by philwebb** [comment]
Unfortunately 78432fc7451ddd025f53c9d79908f0dc0d219cd9 breaks the default build if you happen to use Java 8. This is because the JDK profile ends up disabling the default profile.

**Comment by wilkinsona** [comment]
Sorry, @philwebb. @olivergierke ans I discussed this last week on HipChat when he hit the problem. We were waiting on your input and I then forgot about it. I concluded:

> I think we could just move the repo.spring.io/ext-release-local repository into spring-boot-dependencies' default profile and remove the default profile from spring-boot-parent but I'm rather wary of making that change...
