### ISSUE TITLE
config MANIFEST.MF Spring-Boot-Lib

### ISSUE THREAD

**Issue by fushengruomengzhang** [spring-projects/spring-boot#22354]
I use the spring boot maven plugin plug-in to package my project. I looked at the source code of this plug-in. In a dependency, the configuration of spring boot lib is not configurable and is fixed as boot-info / lib. I want to configure spring boot Lib in this plug-in, just like configuring executable, and directly configure my lib directory

[22353](https://github.com/spring-projects/spring-boot/issues/22353)

**Comment by snicoll** [comment]
@fushengruomengzhang please do not open a duplicate issue. If something needs to be done based on your feedback, we can always reopen the first issue you've raised.
