### ISSUE TITLE
Issue with spring boot 2.4M1 and mariadb connector

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#22365]
I recently upgraded to Spring Boot 2.4M1 to be sure my app is compatible with the latest snapshots but I'm unable to make it work anymore due to database issues. The app fails with this
`error:

    java.sql.SQLSyntaxErrorException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=409) Variable 'character_set_client' can't be set to the value of 'utf32'

    at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[mariadb-java-client-2.6.1.jar!/:na]
`

I tried various things like changing the character set in the url (CharSet=utf8), or setting mariadb global variables like character-set-server and character-set-client, but without luck: I'm unable to make it start anymore.

I verified the problem is with version 2.6.1 of mariadb connector-j, because up to version 2.6.0 it works fine.
Maybe it's something related to https://github.com/mariadb-corporation/mariadb-connector-j/commit/6edc091e ?

I understand this may not be a spring boot issue but if the problem is blocking for other people maybe it's worth evaluating to stick with the older version, or maybe add a release warning/note?

**Comment by wilkinsona** [comment]
Thanks for trying the milestone and for letting us know, but I don't think we should do anything about this in Spring Boot. Downgrading isn't a good option as it means that people who aren't affected by this particular problem miss out on other bug fixes in 2.6.1. Unfortunately, we also don't want to start trying to track and document all known problems with every dependency that Spring Boot manages as we don't have the time to do so. We prefer to allow each project to manage and communicate about their own issues. In this case it looks like [CONJ-804](https://jira.mariadb.org/browse/CONJ-804) is tracking the problem. We'll pick up any fix that it made available in due course. In the meantime, anyone who is affected can use the `maridb.version` property to select a version that meets their needs.
