### ISSUE TITLE
My project already has a property class. How do I use the spring-boot-configuration-processor in the process of writing a spring-boot-starter for it?

### ISSUE THREAD

**Issue by XSun771** [spring-projects/spring-boot#22377]
a few weeks ago, I asked the question on stackoverflow but there is still no anser. Here is the [question](https://stackoverflow.com/questions/62789223/how-to-ask-spring-boot-configuration-processor-to-handle-nested-class-in-a-subcl?noredirect=1#comment111036179_62789223).

Thanks a lot.

**Comment by snicoll** [comment]
Sorry you didn't get an answer to your question. However, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. We also have a Gitter channel if you want to chat with the community.
