### ISSUE TITLE
Remove plugin version management for exec-maven plugin

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-boot#22380]
The Spring Boot 2.3. Release Notes contain a section on [Removal of some Maven Plugin Management](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#removal-of-some-maven-plugin-management) that says:

> Spring Boot’s build no longer makes use of Maven’s exec plugin (`exec-maven-plugin`) or site plugin (`maven-site-plugin`) and plugin management for them has been removed. If you were relying on Spring Boot’s managed versions, you should add your own plugin management.

Looking at https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies/2.3.1.RELEASE/pom I indeed don't see plugin management for `maven-site-plugin` anymore, but the entry for `exec-maven-plugin` is still present. The source for that seems to be https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/build.gradle#L307-L313

I don't know if that was intentional or not, but at least the remark about `exec-maven-plugin` in the release notes doesn't seem to match the contents of the `spring-boot-dependencies` POM and projects that use `exec-maven-plugin` can currently still use Spring Boot's managed version.

**Comment by wilkinsona** [comment]
Thanks for letting us know. This was unintentional. It was removed from `spring-boot-starter-parent` in #20883 but we missed removing it from `spring-boot-dependencies`.

**Comment by dreis2211** [comment]
I can tackle that later today...

**Comment by snicoll** [comment]
I am not sure removing the version in `2.3.2` is a good idea. Shouldn't we do this in 2.4 and update the release notes section rather?

**Comment by snicoll** [comment]
We've decided to remove version management in 2.4 as doing it in 2.3 is a bit late now with no real added benefit for users. I've [updated the release notes to clarify what we've done in 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#removal-of-maven-exec-plugin-custom-configuration).

Closing in favour of PR #22397
