### ISSUE TITLE
Add the ability to customize threads properties for management when in distinct port

### ISSUE THREAD

**Issue by juliojgd** [spring-projects/spring-boot#22391]
https://github.com/spring-projects/spring-boot/blob/2c60672d7015c539e10f1e9f4dffbcd35a0bd4b6/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.java#L38

Would it be useful to add 'Threads' related properties like in ServerProperties to add the ability to configure threading when management port is distinct to main port.

And example: With Tomcat you have main port at 8080 and you configure 8081 as management port. You want to assign maxThreads=2 for management ProtocolHandler but in main port you want to have mexThreads=100.

Would it make sense to allow to specify this threads properties for management ports independently?

**Comment by wilkinsona** [comment]
Yes, we think this makes sense. #9560 is tracking making it possible to configure things separately.
