### ISSUE TITLE
Lettuce: Add configuration to disable Redis Cluster dynamic sources refresh

### ISSUE THREAD

**Issue by DamianFekete** [spring-projects/spring-boot#22398]
In https://github.com/spring-projects/spring-boot/issues/15630 some Lettuce specific options were added:
```
spring.redis.lettuce.cluster.refresh.adaptive
spring.redis.lettuce.cluster.refresh.period
```

Please add a similar configuration option to disable the [dynamicRefreshSources](https://lettuce.io/core/5.1.0.M1/api/io/lettuce/core/cluster/ClusterTopologyRefreshOptions.html#useDynamicRefreshSources--). Maybe `spring.redis.lettuce.cluster.refresh.dynamic-sources` ?

To set this option we have to currently implement a `LettuceClientConfigurationBuilderCustomizer`, which also needs to set the previously mentioned clientOptions.

The option is needed to be able to (re-)connect to Redis using DNS names (in case nodes are restarted and get new IP addresses) (see https://github.com/lettuce-io/lettuce-core/issues/1343)

**Comment by wilkinsona** [comment]
This sounds like a good idea to me, @DamianFekete. Thanks for the suggestion. @mp911de do you agree?

**Comment by mp911de** [comment]
Makes sense.

**Comment by wilkinsona** [comment]
Thanks, @mp911de.

**Comment by snicoll** [comment]
Closing in favour of PR #22571
