### ISSUE TITLE
gradle bootBuildImage --verboseLogging=true results in Unknown command-line option '--verboseLogging'

### ISSUE THREAD

**Issue by jamesward** [spring-projects/spring-boot#22396]
With `2.3.1.RELEASE`:
```
./gradlew bootBuildImage --verboseLogging=true
```

Results in:
```
Unknown command-line option '--verboseLogging'
```

Seems this should work:
https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/gradle-plugin/reference/html/#build-image-customization

**Comment by jamesward** [comment]
Oh, actually it looks like that isn't exposed as a command line param.

**Comment by jamesward** [comment]
BTW, it would be nice to have a sample for this cause it took some figuring:
```
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

tasks.getByName<BootBuildImage>("bootBuildImage") {
        isVerboseLogging = true
}
```

**Comment by snicoll** [comment]
@jamesward there is [an example right below the section you've referenced](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#build-image-examples). Granted, it's using `builder` rather than `verboseLogging` but that should cover it. Have I missed something?

**Comment by jamesward** [comment]
I had to figure out the `import` and that it needs to be `isVerboseLogging` instead of `verboseLogging`. So not just a copy & paste :)

**Comment by wilkinsona** [comment]
The Gradle Plugin documentation's [section on building OCI images](https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/gradle-plugin/reference/html/#build-image) hopefully helps with the import. It contains a link to the javadoc for [`BootBuildImage`](https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/gradle-plugin/api/org/springframework/boot/gradle/tasks/bundling/BootBuildImage.html).

The need for the `is` prefix is a quirk of Kotlin. With the Groovy DSL the more intuitive `verboseLogging = true` will work.
