### ISSUE TITLE
Support for Mustache Template Engine

### ISSUE THREAD

**Issue by mnrasul** [spring-projects/spring-boot#2242]
@dsyer has already made available Mustache Template Engine at https://github.com/dsyer/spring-boot-mustache. 

It would be great if it can be made part of spring boot.

Thanks.

**Comment by philwebb** [comment]
Reopening to consider comments about `MustacheEnvironmentCollector`.

**Comment by wilkinsona** [comment]
The new starter also needs to be added to the documentation
