### ISSUE TITLE
Spring Boot Actuator dependency on Jackson prevents usage of GSON

### ISSUE THREAD

**Issue by laurikimmel** [spring-projects/spring-boot#2247]
According to Spring Boot 1.2.0 release notes all Jackson libraries has to be excluded from the classpath to use GSON for creating JSON output. This is not possible in case application is using ```spring-boot-starter-actuator```. 

Excluding ```jackson-core```, ```jackson-databind``` and ```jackson-annotations``` from ```spring-boot-starter-actuator``` will result with ```BeanCreationException```:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesReportEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint]: Factory method 'configurationPropertiesReportEndpoint' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector
```

And the application is not able to start.

It turns out ```spring-boot-starter-actuator``` needs all three mentioned Jackson libraries to start properly. Once Jackson libraries are included in the classpath GSON is not used to produce JSON output any more.

**Comment by philwebb** [comment]
Reopening to consider comments in commit d718a80

**Comment by balajeetm** [comment]
Is there a way to use Gson only for specific classes - mainly (JsonElement, JsonObject, JsonArray) and for the rest use Jackson. JsonElement is not a plain pojo, hence jackson has trouble serialising it. Would be good if we can use both or if actuator can work with Gson. How should we go about it?

**Comment by philwebb** [comment]
@balajeetm This issue has been closed for a while. If you've got additional questions please ask on stackoverflow.com. Thanks!
