### ISSUE TITLE
AbstractRepositoryConfigurationSourceSupport does not override registerBeanDefinitions(AnnotationMetadata, BeanDefinitionRegistry)

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#22480]
`AbstractRepositoryConfigurationSourceSupport` overrides one of the `registerBeanDefinitions()` method in `ImportBeanDefinitionRegistrar` but not the other. The other one has an empty default implementation, so if anyone calls it, nothing happens. It would be helpful to add an implementation, even if it just throws an exception (hopefully it wouldn't need to).

**Comment by wilkinsona** [comment]
The `BeanNameGenerator` that's missing when `registerBeanDefinitions(AnnotationMetadata, BeanDefinitionRegistry)` is called is eventually passed into an AnnotationRepositoryConfigurationSource constructor where it's marked as `@Nullable`. It looks like we can safely implement the missing override as follows:

```java
@Override
public void registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry) {
	registerBeanDefinitions(importingClassMetadata, registry, null);
}
```
