### ISSUE TITLE
Spring Circular dependency + Setter Dependency Injection + Java Config => Getting Exception - Documentation update may require

### ISSUE THREAD

**Issue by ELearnTez** [spring-projects/spring-boot#22482]
Hi Team,

This is continuous to https://github.com/spring-projects/spring-boot/issues/22479
 Thanks for the information. I'm not looking for the solution, just trying to understand the concept here.
How the same code is working fine with XML config and why not on Java config. And it's not mentioned on Spring documentation about this conflict.

![image](https://user-images.githubusercontent.com/41267120/88064306-bd4aad00-cb88-11ea-8b56-0106ece28a18.png)

**Comment by wilkinsona** [comment]
Thanks, but there's no need to open a new issue as well as commenting on an existing issue.
