### ISSUE TITLE
Add @Name support for value object binding

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22492]
Currently the `ValueObjectBinder` uses the parameter name when binding properties. This works well in most situations, but prevents us from using Java reserved words as property names. It would be helpful to offer an annotation so that the property name can be defined independently of the parameter name.

**Comment by snicoll** [comment]
Reopening as the `@Name` annotation should be processed by the Configuration Metadata AP to generate the intended property name.
