### ISSUE TITLE
Docs say Health's inner `details` section may contain components

### ISSUE THREAD

**Issue by derekm** [spring-projects/spring-boot#22490]
Docs here in this test and on the website say the `components.*.details` object "May contain nested components that make up the health," but this should no longer be the case with the addition of `components.*.components`:

https://github.com/spring-projects/spring-boot/blob/a94ab673a3230e89403c1046837359c300f8717c/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/documentation/HealthEndpointDocumentationTests.java#L84

https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/actuator-api/html/#health-retrieving-response-structure

The work done in the original issue here seems to have missed updating the documentation: https://github.com/spring-projects/spring-boot/issues/17929

**Comment by derekm** [comment]
@mbhave — does this fix the website docs which are also out of date?

**Comment by snicoll** [comment]
Thanks for bringing this to our attention @derekm. It looks like the latest build did not refresh the docs. We'll have a look.

**Comment by snicoll** [comment]
Turn out this was a cache issue in our build. This is now fixed, see #22819 for more details.
