### ISSUE TITLE
UndertowWebServerFactoryCustomizer does not support Options but only UndertowOptions

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-projects/spring-boot#22502]
`UndertowWebServerFactoryCustomizer` can map properties from:
- `server.undertow.options.server.* `
- `server.undertow.options.socket.*`
into:
- `builder.setSocketOption(...)`
- `builder.setSocketOption(...)`

but it does not support  `org.xnio.Options` but only `UndertowOptions`, see: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/UndertowWebServerFactoryCustomizer.java#L141

To use `builder.setSocketOption(...)` we need properties from `org.xnio.Options`.

**Comment by wilkinsona** [comment]
Thanks for the report. This looks like a bug to me. As far as I can tell, none of the options on `UndertowOptions` is intended for use as a socket option. This means that the `server.undertow.options.socket.*` properties are of no use as currently implemented.
