### ISSUE TITLE
webflux base path does not work with router functions

### ISSUE THREAD

**Issue by lfcortes12** [spring-projects/spring-boot#22510]
WebFlux is not able to find a route defined as a router function when spring.webflux.base-path is set. Server response is org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND. I'm using version 2.3.1.RELEASE. Routes are defined in GameScoreRouter in the attached project
[spring-game-score - copy.zip](https://github.com/spring-projects/spring-boot/files/4962120/spring-game-score.-.copy.zip)

.

**Comment by bclozel** [comment]
This problem will be addressed in Spring Framework, see https://github.com/spring-projects/spring-framework/issues/25270

I'm closing this issue as there's nothing we can do in the meantime.
