### ISSUE TITLE
Remove spring.profiles support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22523]
The `spring.profiles` property was replaced in Spring Boot 2.4 with `spring.config.activate.on-profile`. We currently still support the old property and we should consider when to remove it.

**Comment by shawnz** [comment]
What would be the intended way of setting the active profiles if this property were removed? My understanding is that `spring.config.activate.on-profile` doesn't actually activate the profile itself.

**Comment by mbhave** [comment]
@shawnz that's correct. `spring.profiles.active` is not deprecated and can be used to activate profiles.

**Comment by shawnz** [comment]
Understood, thanks!

**Comment by raqueru** [comment]
In this case we should simply remove every mention of spring.profiles.include or change it for other thing?

**Comment by philwebb** [comment]
This issue is only about removing the `spring.profiles` property. The `spring.profiles.include` and `spring.profiles.active` properties will remain.

**Comment by raqueru** [comment]
> This issue is only about removing the `spring.profiles` property. The `spring.profiles.include` and `spring.profiles.active` properties will remain.

got it! thanks

**Comment by philwebb** [comment]
Moving this to 3.0.x and flagging for team attention because I'm not sure we should drop `ConfigFileApplicationListener` before then.

**Comment by wilkinsona** [comment]
> As far as I can see, the documentation for SpringBoot 3.0.0-M2 is still using this property

That is to be expected as this issue is still open and we have not yet removed support for `spring.profiles`.
