### ISSUE TITLE
@Value in combination with @ConfigurationProperties prefix not working as expected

### ISSUE THREAD

**Issue by rweisleder** [spring-projects/spring-boot#2254]
I get unexpected results if I use `@ConfigurationProperties` with prefix and `@Value` in the same class. For example:

application.properties:

``` properties
test.key=value1
test.inner.secondkey=value2
```

ConfigProps.java:

``` java
@ConfigurationProperties(prefix = "test")
public class ConfigProps {

    private String key;

    @Value("${inner.secondkey}")
    private String innerSecondkey;

    // getter and setter...
}
```

While starting the context I get an `IllegalArgumentException: Could not resolve placeholder 'inner.secondkey' in string value "${inner.secondkey}"`
I thought when using `${inner.secondkey}"` Spring Boot would prepend the given prefix and look for `${test.inner.secondkey}"`.

Question 1: Is it intended to use both annotations in the same class?
Question 2: Is it possible for Spring Boot to resolve my field `innerSecondkey` to the property `inner.secondkey`?

**Comment by hohwille** [comment]
FYI: I have the problem that I mapped an existing properties format via @ConfigurationProperties.
Now someone whom I have no influence on changed that format such that I do have one case like this:
```
foo.bar=value1
foo.bar.some=value2
```

as `@Value` is not supported within `@ConfigProperties` this leaves me with a problem I can not solve except for getting away from `@ConfigProperties` and refactoring the complete approach. Sad.
