### ISSUE TITLE
BuildImage download buildpacks everytime when tag changed

### ISSUE THREAD

**Issue by helloworlde** [spring-projects/spring-boot#22567]
Hi, when i use `spring-boot:build-image` in `2.3.2.RELEASE`, it will download paketo-buildpacks files from GitHub everytime when I change tag; Is there has any configuration for use exist image cache? And may I ask and why not? It's hard to download files from GitHub in China!

```
[INFO]     [creator]     5 of 15 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 2.8.1
[INFO]     [creator]     paketo-buildpacks/executable-jar    1.2.8
[INFO]     [creator]     paketo-buildpacks/apache-tomcat     1.3.1
[INFO]     [creator]     paketo-buildpacks/dist-zip          1.3.6
[INFO]     [creator]     paketo-buildpacks/spring-boot       1.9.1
```

**Comment by scottfrederick** [comment]
As of Spring Boot [`2.4.0-M2`](https://spring.io/blog/2020/08/14/spring-boot-2-4-0-m2-is-now-available), the `spring-boot:build-image` goal supports a `pullPolicy` option to control whether the plugin pulls the builder image from a remote registry or uses a locally cached builder image. See https://docs.spring.io/spring-boot/docs/2.4.0-M2/maven-plugin/reference/html/#build-image-customization. 

Once Spring Boot invokes the builder using the specified builder image (e.g. `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3` by default), it is up to the builder to decide if it needs to download individual buildpacks, and where it downloads buildpacks from. Spring Boot cannot control this builder behavior. You can get more information on engaging with the Paketo community to discuss builder behavior on the[ Paketo website](https://paketo.io/).
