### ISSUE TITLE
Spring Boot 2.3.2: new context is created for every IT class if SpyBean is used

### ISSUE THREAD

**Issue by jonathanlermitage** [spring-projects/spring-boot#22566]
If an integration test uses the `org.springframework.boot.test.mock.mockito.SpyBean` annotation to spy a bean, a new Spring Context is created even if it was cached already. In other words, if I have 3 classes (which use the same Spring configuration) for integration tests, the Spring application is started 3 times. Normally, the first context should be cached and reused in the two other test classes. 
I imagine that spied components are no longer identical between two tests, so the context is not the same?

This problem occurs with Spring Boot 2.3.2.RELEASE (and 2.4.0 snapshots and M1). No problem with 2.3.1 and previous versions. 

You can reproduce this problem with this sample project: https://github.com/jonathanlermitage/spring-mvc-tiny-sample/tree/issue-spybean , run `./mvnw verify`: the application is started 4 times instead of 1 time.  
This is a simple REST API with one API that uses one Service. An [abstract class](https://github.com/jonathanlermitage/spring-mvc-tiny-sample/blob/issue-spybean/src/test/java/demo/springmvctinysample/AbstracBaseIT.java#L31) is the parent of Integration Test classes ([1](https://github.com/jonathanlermitage/spring-mvc-tiny-sample/blob/issue-spybean/src/test/java/demo/springmvctinysample/ApplicationIT.java), [2](https://github.com/jonathanlermitage/spring-mvc-tiny-sample/blob/issue-spybean/src/test/java/demo/springmvctinysample/Application2IT.java), etc).

If you remove the [spied bean](https://github.com/jonathanlermitage/spring-mvc-tiny-sample/blob/issue-spybean/src/test/java/demo/springmvctinysample/AbstracBaseIT.java#L31) field, or if you set Spring Boot version to 2.3.1 in pom.xml, you will see that the Spring context is cached and reused.

**Comment by krusche** [comment]
We have the same problem in our project.

When upgrading to Spring Boot 2.3.2, the server application is started several times during integration tests, while in Spring Boot 2.3.1, the server application is only started 3 times (as we test with different profiles).

This essentially prevents us from upgrading at the moment

**Comment by wilkinsona** [comment]
Thanks for the report and sample, @jonathanlermitage. Unfortunately, I haven't been able to reproduce the problem. I updated the `pom.xml` to use Spring Boot 2.3.2.RELEASE and the application is only started once when running `./mvnw verify`. To double-check, I enabled debug logging for `org.springframework.test` and it shows that only a single context has been created:

```
2020-07-26 17:00:25.494 DEBUG 80340 --- [           main] org.springframework.test.context.cache   : Spring test ApplicationContext cache statistics: [DefaultContextCache@737db7f8 size = 1, maxSize = 32, parentContextCount = 0, hitCount = 70, missCount = 1]
```

What do I need to do with the sample to reproduce the behaviour that you have described?

**Comment by wilkinsona** [comment]
@krusche Thanks for the pointer to your app, unfortunately there's a bit too much to it for us to be able to use it to reproduce the problem. If you can provide us with something minimal that we can more easily use to reproduce the problem we can take a look.

**Comment by jonathanlermitage** [comment]
Tested on Windows 10 and ubuntu 18.04.  
Here is the console output on Windows: [console.log](https://github.com/spring-projects/spring-boot/files/4977908/console.log)

You will see 4 banners and 4 Tomcat startups on different port.

**Comment by wilkinsona** [comment]
@jonathanlermitage Thanks. Only 7 tests were run for me whereas your log shows 9. That led to me looking for differences and I noticed that I'd neglected to switch to the `issue-spybean` branch. I've reproduced the problem now.

**Comment by jansu76** [comment]
Probably not adding much value to the topic anymore, but I am experiencing the same. Upgrading from 2.2.8 to 2.2.9 causes test context creations to grow from 12 to 57 in our builds, and doubles the build time.

**Comment by wilkinsona** [comment]
Thanks, @jansu76. It's valuable to know that the problem also occurs with 2.2.9. My suspicion is that the fix for https://github.com/spring-projects/spring-boot/issues/20916 is the cause and it was made in 2.2.x.

**Comment by krusche** [comment]
Thanks for the fix. I'll hope you can release 2.3.3 quickly so that we can upgrade to it 👍
