### ISSUE TITLE
 Couchbase Cache support documentation still refers to previous version

### ISSUE THREAD

**Issue by scollector65** [spring-projects/spring-boot#22572]
> docs.spring.io about spring cache couchbase
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-caching-provider-couchbase

> Upgrade to Couchbase SDK v3
https://github.com/spring-projects/spring-boot/commit/abe43b2e83713591bc23821add3763cc2c41e3bd

I think document should update about "Upgrade to Couchbase SDK v3".
It is very confused for new couchbase cache users.

> CouchbaseCacheConfiguration
https://github.com/spring-projects/spring-boot/blob/58eb0ba4d3919743901c9900c17f6f8c34d80aed/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/CouchbaseCacheConfiguration.java

And I think CacheManagerCustomizers cannot working on couchbase cache. CacheManagerCustomizers cannot change about 
CouchbaseCacheManager.

**Comment by wilkinsona** [comment]
> I think document should update about "Upgrade to Couchbase SDK v3".
It is very confused for new couchbase cache users.

Thanks for the feedback. Are you saying that the documentation is out-of-date and does not work with v3 of the Couchbase SDK or that the migration to v3 of the SDK is confusing?

**Comment by snicoll** [comment]
@scollector65 Andy and I chatted as I've review the PR and the cache documentation is indeed outdated, sorry about that. We will have to investigate how to offer a customization callback that offers the same feature as the current doc (I.e. `prepareCache`).

**Comment by snicoll** [comment]
Let's tackle the lack of customization in #22573 as it is unrelated to the fact the doc is outdated. Thanks for the report @scollector65!

**Comment by snicoll** [comment]
It turns out that the documentation had to be rewritten as part of fixing the customisation problem anyway.

This issue is now superseded by #22573
