### ISSUE TITLE
Include a hint where to find documentation for DevTools in docs overview

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#22591]
If you look for documentation on the DevTools and arrive at the documentation [home page](https://docs.spring.io/autorepo/docs/spring-boot/current/reference/html/index.html) there's no way to find the right sub-section to proceed to. Turn's out it's in "Using Spring Boot". Does it make sense to list DevTools in the summary line? It seems to be a prominent thing to look for in the overview as it's such a distinguished feature.

**Comment by wilkinsona** [comment]
Done. Thanks for the suggestion, @odrotbohm.
