### ISSUE TITLE
UT error with mockito in spring-boot 2.3.2

### ISSUE THREAD

**Issue by yuanpli** [spring-projects/spring-boot#22595]
Hello,
I got the following error in UT randomly. But the UT is working in 2.3.1 and 2.3.0
`
java.lang.IllegalAccessError: tried to access method org.mockito.internal.util.MockUtil.()V from class com.foreach.common.test.MockedLoader$BeanFactoryDecorator 21:28:17 at com.foreach.common.test.MockedLoader$BeanFactoryDecorator.destroySingletons(MockedLoader.java:120) 21:28:17 at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) 21:28:17 at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) 21:28:17 at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979) 21:28:17 at org.springframework.test.context.cache.DefaultContextCache.remove(DefaultContextCache.java:207) 21:28:17 at org.springframework.test.context.cache.DefaultContextCache.remove(DefaultContextCache.java:172) 21:28:17 at org.springframework.test.context.cache.DefaultContextCache$LruCache.removeEldestEntry(DefaultContextCache.java:337) 21:28:17 at java.util.LinkedHashMap.afterNodeInsertion(LinkedHashMap.java:299) 21:28:17 at java.util.HashMap.putVal(HashMap.java:663) 21:28:17 at java.util.HashMap.put(HashMap.java:611) 21:28:17 at java.util.Collections$SynchronizedMap.put(Collections.java:2588) 21:28:17 at org.springframework.test.context.cache.DefaultContextCache.put(DefaultContextCache.java:142) 21:28:17 at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:129) 21:28:17 at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123) 21:28:17 at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190) 21:28:17 at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132) 21:28:17 at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289) 21:28:17 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) 21:28:17 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 21:28:17 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 21:28:17 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 21:28:17 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 21:28:17 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 21:28:17 at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) 21:28:17 at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) 21:28:17 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 21:28:17 at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 21:28:17 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) 21:28:17 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) 21:28:17 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) 21:28:17 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) 21:28:17 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 21:28:17 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 21:28:17 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 21:28:17 at java.lang.reflect.Method.invoke(Method.java:498) 21:28:17 at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) 21:28:17 at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) 21:28:17 at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) 21:28:17 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) 21:28:17 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)`

See also from https://stackoverflow.com/questions/63117438/ut-error-with-mockito-in-springboot-2-3-2

**Comment by wilkinsona** [comment]
Thanks for the report, but let's keep the discussion in one place for now. If it turns out that this is due to a bug in Spring Boot, we can re-open this issue.
