### ISSUE TITLE
Link to App Engine Standard sample not working

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#22607]
Hi,

while going through the docs I noticed that the [Google Cloud documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#cloud-deployment-gae) has a broken link:

> Follow [these steps](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/appengine-standard-java8/springboot-appengine-standard/README.md) to deploy App Engine Standard application to Google Cloud.

Apparently, the Spring-Boot Java sample was removed. As I don't know what the link provided, I don't really know how to replace it. There's a [Kotlin sample](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/kotlin-sb-appengine-standard) still & the [Google docs](https://cloud.google.com/appengine/docs/standard/java/tools/uploadinganapp#deploying_an_app) which could be candidates.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Well spotted, @dreis2211. Thank you. I think it's moved [here](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/springboot-helloworld).
