### ISSUE TITLE
spring-data-redis `opsForStream` missing `xtrim` [~] support

### ISSUE THREAD

**Issue by YiuTerran** [spring-projects/spring-boot#22613]
> It is possible to give the command in the following special form in order to make it more efficient:
> 
> XTRIM mystream MAXLEN ~ 1000
> 
> The ~ argument between the MAXLEN option and the actual count means that the user is not really requesting that the stream length is exactly 1000 items, but instead it could be a few tens of entries more, but never less than 1000 items. When this option modifier is used, the trimming is performed only when Redis is able to remove a whole macro node. This makes it much more efficient, and it is usually what you want.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but Spring Data Redis is managed as a separate project and they use [JIRA](https://jira.spring.io/browse/DATAREDIS) for issue tracking.
