### ISSUE TITLE
Make spring-boot-gradle-plugin available via the Gradle plugin repository

### ISSUE THREAD

**Issue by cbeams** [spring-projects/spring-boot#2263]
The Gradle plugin is not currently available from https://plugins.gradle.org, meaning that the plugin is harder to find, and that users cannot take advantage of the new plugin syntax in Gradle 2.x.

Instructions for submitting a plugin can be found at https://plugins.gradle.org/submit.

**Comment by snicoll** [comment]
Spring Boot support in IDEA is coming later this year Chris.
