### ISSUE TITLE
Revisit DispatcherServletsMappingDescriptionProvider Spring Data Rest's support

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#22654]
With the upgrade to Spring Data `2020.0.0` snapshots, `org.springframework.data.rest.webmvc.support.DelegatingHandlerMapping` is deprecated. The deprecation indicates we should look for `Iterable<HandlerMapping>`. 

Unfortunatley, `DispatcherServletsMappingDescriptionProvider` uses a `Class` to identify the source of interest so we'd have to either look for `Iterable` and check the underlying type or get back to a concrete type for this, which would require some adaptation in Spring Data rest potentially.

/cc @odrotbohm

**Comment by odrotbohm** [comment]
I might be missing context but couldn't you refactor what's now `DelegatingHandlerMappingDescriptionProvider` to take a class from the outside? The set up code would then create an instance of that if it detects the original type to implement `Iterable<HandlerMapping>` (`ResolvableType` helps here) and if so, initialize that description provider with the wrapping mapping's type (which would be `DelegatingHandlerMapping` transparently) *and* the downstream descriptors obtained by iterating over the original mapping?
