### ISSUE TITLE
Note the Kt class name suffix when describing how to configure a Kotlin application's main class name

### ISSUE THREAD

**Issue by Inego** [spring-projects/spring-boot#22664]
This can probably be obvious to Kotlin developers, but values of the `mainClassName` property for Kotlin classes should include the `Kt` postfix, if the corresponding application is a Kotlin class.

For example, a Kotlin `ExampleApplication` like

```kotlin
package com.example

@SpringBootApplication
class ExampleApplication

fun main() {
    runApplication<ExampleApplication>()
}
```

would require specifying its entry point as

```kotlin
springBoot {
    mainClassName = "com.example.ExampleApplicationKt"
}
```

and not `"com.example.ExampleApplication"` (as shown in the Reference).

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The Kotlin examples in the Gradle plugin's documentation are for configuring Gradle using its Kotlin DSL. It's not intended to imply that the application itself has been written in Kotlin. That said, there's no harm in including a tip in the [section on configuring the application's main class](https://docs.spring.io/spring-boot/docs/2.3.2.RELEASE/gradle-plugin/reference/html/#packaging-executable-configuring-main-class).

**Comment by fernandezseb** [comment]
Hey, I'd gladly make a PR to add a note.
I would add something along the lines:

> If the main class is written in Kotlin, the name of the generated Java class should be used,
because the Kotlin function `fun main(args: Array<String>)` is defined at the package-level.
By default this is the name of the Kotlin class with the `Kt` suffix added.
For example: `ExampleApplication` becomes `ExampleApplicationKt`.
(If another name is defined using the `@JvmName` annotation, then that name should be used.)

**Comment by wilkinsona** [comment]
@fernandezseb Yes, please. That'd be great. FWIW, I'd omit "because the Kotlin function fun `main(args: Array<String>)` is defined at the package-level" purely in the interests of brevity.

**Comment by wilkinsona** [comment]
Closing in favour of #23418.
