### ISSUE TITLE
Hibernate @Enity annotation changes Jackson serialization behavior

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-boot#2267]
When an object is annotated with @Entity, then Jackson doesn't serialize the id.

```java
@Entity
public class Test implements Serializable {
	@Id
	private Long id;
	private String attribute;
	// getters, setters, toString, hashCode, equals, serialVersionUID, etc.
}
```
This will serialize to

```json
{
  "attribute" : "attribute"
}
```
Commenting out ```@Entity``` will fix the serialization:
```json
{
  "id" : 1,
  "attribute" : "attribute"
}
```

I've created a minimal project to demonstrate the problem here:
https://github.com/efenderbosch/spring-hibernate-jackson-error

Should I also submit this to the Hibernate project?

I'm using OpenJDK 1.7.0_65 on Ubuntu 14.04.

**Comment by philwebb** [comment]
It appears to be `PersistentEntityJackson2Module` from spring-data-rest that is causing this behavior. The `updateBuilder` method is called which removes ID attributes.

@olivergierke it looks like this is expected behavior, do we need to provide a quick global opt-out property.

@efenderbosch Are you actually using Spring Data Rest? If not you could try removing it from your classpath. You can also exclude `RepositoryRestMvcAutoConfiguration` as a work-around.

**Comment by philwebb** [comment]
BTW also tested with 1.1.10 so this isn't a recent regression.

**Comment by efenderbosch** [comment]
I'm using Spring Data Rest because it brings in spring-web (HttpStatus) and spring-hateos (PagedResources). Our app is a pretty basic RESTful service w/ JPA.

If there's a different spring-boot-starter or combination that will provide this functionality, I can use that instead.

**Comment by efenderbosch** [comment]
I was hopeful that this would work, but it didn't:

```java
	@Bean
	@Primary
	public RepositoryRestConfiguration repositoryRestConfiguration() {
		RepositoryRestConfiguration repositoryRestConfiguration = new RepositoryRestConfiguration();
		repositoryRestConfiguration.exposeIdsFor(Test.class);
		return repositoryRestConfiguration;
	}
```

I'm not confident that my bean is replacing the default bean. If I leave off ```@Primary`` then I get "expected single matching bean but found 2."

**Comment by efenderbosch** [comment]
This does work, however:

```java
	@Bean
	@Primary
	public RepositoryRestConfiguration repositoryRestConfiguration(PersistentEntities persistentEntities,
			RepositoryRestConfiguration repositoryRestConfiguration) {
		for (PersistentEntity<?, ?> persistentEntity : persistentEntities) {
			repositoryRestConfiguration.exposeIdsFor(persistentEntity.getType());
		}
		return repositoryRestConfiguration;
	}
```

**Comment by wilkinsona** [comment]
I'd like to make `RepositoryRestMvcBootConfiguration`'s `RepositoryRestConfiguration` bean `@ConditionalOnMissingBean`, however Spring Framework won't let me. It evaluates the condition on the overriding method and determines that it should be skipped, but then looks at the unconditional overridden method on the superclass and creates the bean anyway. I've opened [SPR-12695](https://jira.spring.io/browse/SPR-12694).

**Comment by wilkinsona** [comment]
My [comment above](https://github.com/spring-projects/spring-boot/issues/2267#issuecomment-73073034) was with a view towards users declaring their own `RepositoryRestConfiguration` bean as @efenderbosch has attempted above. A major drawback of this approach is that the bean _has_ to be called `config` as Spring Data REST references it by name.

`RepositoryRestMvcBootConfiguration` was recently made public (#2392). This provides a much nicer way to customise `RepositoryRestConfiguration`. For example, here's how to enable the exposure of ids for an entity:

```java
@Configuration
class CustomRepositoryRestMvcConfiguration extends RepositoryRestMvcBootConfiguration {
    @Override
    protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        config.exposeIdsFor(City.class);
    }
}
```

This allows you to use Spring Data REST's approach to customising the configuration while also taking advantage of Boot's auto-configuration – any `spring.data.rest.*` properties will still be applied to the `RepositoryRestConfiguration` instance.

**Comment by wilkinsona** [comment]
@efenderbosch If you're not actually using Spring Data REST, but simply looking for a starter to pull in spring-web and spring-hateoas, we added `spring-boot-starter-hateoas` recently (#2396). It'll be in 1.2.2.

**Comment by new23d** [comment]
Note that `RepositoryRestMvcBootConfiguration` has since been renamed to `SpringBootRepositoryRestMvcConfiguration` .
