### ISSUE TITLE
Use loop variable ApplicationContext to determine all Liquibase beans

### ISSUE THREAD

**Issue by biergit** [spring-projects/spring-boot#22680]
https://github.com/spring-projects/spring-boot/blob/d2926e02222f942948637bd5bb6972379eb094c8/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/liquibase/LiquibaseEndpoint.java#L65

should be replaced with `target.getBeansOfType(SpringLiquibase.class)`

**Comment by wilkinsona** [comment]
Closing in favour of #22681.
