### ISSUE TITLE
OCI image build fails if environment has any empty properties

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#22703]
pom.xml:

```xml
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<env>
							<FOO></FOO>
						</env>
					</image>
				</configuration>
			</plugin>
```

result:

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.4.0-SNAPSHOT:build-image (default-cli) on project func: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.4.0-SNAPSHOT:build-image failed: String must not be null -> [Help 1]
```

**Comment by scottfrederick** [comment]
@dsyer What are you expecting to happen with your use case - should the empty `env` entry be ignored or should an entry named `FOO` be provided to the builder with an empty value? The latter seems appropriate, but I'm wondering if there's something specific that led you to try this.

**Comment by dsyer** [comment]
The value is empty so null is a poor representation I would say. Your call. I stumbled on this accidentally, but I wild t expect it to blow up really.
