### ISSUE TITLE
Autowired in hibernate constraintvalidator custom annotation returns nullexception

### ISSUE THREAD

**Issue by fenzox** [spring-projects/spring-boot#22728]
After looking around, I couldn't find any good solution to this.

My autowired didn't work as expected where it returns null. I've autowired this particular class in other classes and it works so it only doesn't work in constraintvalidator classes.

Error

> java.lang.IllegalStateException: Failed to execute CommandLineRunner
> 	at
> org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> com.Alex.Mains.JpaApplication.main(JpaApplication.java:21)
> ~[classes/:na] Caused by:
> org.springframework.transaction.TransactionSystemException: Could not
> commit JPA transaction; nested exception is
> javax.persistence.RollbackException: Error while committing the
> transaction 	at
> org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:543)
> ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:632)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
> ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
> ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	at
> org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
> ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	at
> com.sun.proxy.$Proxy93.save(Unknown Source) ~[na:na] 	at
> com.Alex.Mains.UserRepositoryCommandLineRunner.run(UserRepositoryCommandLineRunner.java:26)
> ~[classes/:na] 	at
> org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
> ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE] 	... 5 common frames
> omitted Caused by: javax.persistence.RollbackException: Error while
> committing the transaction 	at
> org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
> ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE] 	... 21 common frames
> omitted Caused by: javax.validation.ValidationException: HV000028:
> Unexpected exception during isValid call. 	at
> org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:186)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:62)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final] 	at
> org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:116)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:227)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
> ~[na:na] 	at
> org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1360)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:451)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3210)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2378)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	at
> org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
> ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final] 	... 22 common frames
> omitted Caused by: java.lang.NullPointerException: null 	at
> com.Alex.Validations.EmailValidator.isValid(EmailValidator.java:26)
> ~[classes/:na] 	at
> com.Alex.Validations.EmailValidator.isValid(EmailValidator.java:1)
> ~[classes/:na] 	at
> org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:180)
> ~[hibernate-validator-6.1.5.Final.jar:6.1.5.Final]

UserService class

    @Service
    public class UserService {
    
    	@Autowired
    	private UserRepository userRep;
    	
    	public void addUser(User user) {
    		userRep.save(user);
    	}
    	
    	
    	public void deleteUser(long userId) {
    		userRep.deleteById(userId);
    	}
    	
    	public List<User> retrieveAllUsers(){
    		Iterable<User>temp =userRep.findAll();
    		List<User>allUsers = null;
    		temp.forEach(allUsers::add);
    		return allUsers;
    	}
    	
    	public boolean searchByEmail(String email) {
    		return userRep.findByEmail(email);
    	}
    	
    	public void updateUser(User user) {
    		userRep.save(user);
    	}
    }

Annotation interface class
   

     @Target(ElementType.FIELD) 
        //When will the annotation be processed compilation, runtime etc
        @Retention(RetentionPolicy.RUNTIME)
        //Where is the logic
        @Constraint(validatedBy = EmailValidator.class)
        @Documented
        public @interface ValidEmail {
        	
        	//Error message
        	String message() default "Invalid email";
        	//Required for annotation
            Class<?>[] groups() default {};
            Class<? extends Payload>[] payload() default {};
        	
        }

Annotation logic class

    public class EmailValidator implements ConstraintValidator<ValidEmail, String> {
    
    	@Autowired
    	private UserService service;
    	//Actual place to place the logic to check if the data is valid or not
    	@Override
    	public boolean isValid(String email, ConstraintValidatorContext context) {
    		if (email == null) {
    		return false;
    		}
    		
    		List<User> users = service.retrieveAllUsers();
    		if (users.size() > 0) { 
    		return Pattern.matches("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])", email)
    				&& service.searchByEmail(email);
    		}
    		
    		else {
    			return Pattern.matches("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])", email);
    		}
    		}
    		
    	
    	
    	@Override
    	public void initialize(ValidEmail validEmail) {
    		validEmail.message();
    	}
    
    }

**Comment by snicoll** [comment]
@fenzox thanks but you've asked the same question 10 min ago on Gitter and there is a [StackOverflow question](https://stackoverflow.com/questions/63232702/autoried-in-bibernate-constaintvalidator-custom-annotation-returns-nullexception/63235020#63235020) as well. To reduce the possibility of duplicating effort, I am going to close this now in the benefit of your SO question.
