### ISSUE TITLE
Spring Boot Actuator behind a Proxy

### ISSUE THREAD

**Issue by NF10** [spring-projects/spring-boot#22720]
The application is behind a proxy and reachable over for example this url https://app-x/node-x01. The problem is that the spring boot admin use the urls from https://app-x/node-x01/management and this urls are without node-x01 in the path.
So the Solution would be that the `org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver` handle a specific http-header which has the information about the proxy.

I create my own WebMvcEndpointHandlerMapping Bean and override the resolveLinks Method of EndpointLinksResolver. That works for me as a workaround.

I don´t find any standard http-header which could transport the path information. Like X-Forwarded-Host for the hostname.

The reason for use the path is the better handling of certificates. It is worse to handle the certificates for every app-instance like https://app-x01/, https://app-x02/, and so on.

**Comment by wilkinsona** [comment]
Assuming that I have understood what you're trying to do, `X-Forwarded-Prefix` can be used for this purpose. It is supported by Spring Framework's `ForwardedHeaderFilter` which Spring Boot will auto-configure for you if you set `server.forward-headers-strategy=framework`. Does this meet your needs?

**Comment by NF10** [comment]
That should be the solution. Thanks a lot!
