### ISSUE TITLE
WebMvcEndpointExposureIntegrationTests is flaky 

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#22743]
```
WebMvcEndpointExposureIntegrationTests > singleWebEndpointCanBeExcluded() FAILED
    org.springframework.core.io.buffer.DataBufferLimitException at LimitedDataBufferList.java:101

WebMvcEndpointExposureIntegrationTests > webEndpointsCanBeExposed() FAILED
    org.springframework.core.io.buffer.DataBufferLimitException at LimitedDataBufferList.java:101
```

The output of some endpoints may reach the default limit and breaking the test. It's failing for me consistently with Java 11 but does not with Java 1.8.

**Comment by wilkinsona** [comment]
We've [seen this before](https://github.com/spring-projects/spring-boot/issues/19566) and increased the limit to 512KB. We also saw [a similar problem](https://github.com/spring-projects/spring-boot/issues/22101) and I disabled the limit entirely there. That's probably a more robust way to go for the tests.
