### ISSUE TITLE
Exclude all cookie headers by default from HTTP traces

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22745]
HTTP traces currently include `Cookie` headers but exclude `Authorization` headers by default. We should consider excluding `Cookie` headers by default.

**Comment by JoeBeeton** [comment]
As mentioned privately, The current configuration which is  by default showing the cookies, has the potential to leak sensitive information if the http trace endpoint is enabled. We would very much like for this to not be enabled by default.

**Comment by philwebb** [comment]
We'll look at doing this in 2.4.x

**Comment by philwebb** [comment]
Closing in favor of PR #22829
