### ISSUE TITLE
Duplicate or near duplicate methods that could possibly be refactoring candidates

### ISSUE THREAD

**Issue by zibbly** [spring-projects/spring-boot#2276]
The code in the following method pairs is duplicated or nearly duplicated and the methods could possibly be candidates for refactoring...

org.springframework.boot.autoconfigure.orm.jpa.Registrar

		@Override
		public void registerBeanDefinitions(AnnotationMetadata importingClassMetadata,
				BeanDefinitionRegistry registry) {
			if (!registry.containsBeanDefinition(BEAN_NAME)) {
				GenericBeanDefinition beanDefinition = new GenericBeanDefinition();
				beanDefinition.setBeanClass(DataSourceInitializedPublisher.class);
				beanDefinition.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
				// We don't need this one to be post processed otherwise it can cause a
				// cascade of bean instantiation that we would rather avoid.
				beanDefinition.setSynthetic(true);
				registry.registerBeanDefinition(BEAN_NAME, beanDefinition);
			}
		}

org.springframework.boot.autoconfigure.jdbc.Registrar

		@Override
		public void registerBeanDefinitions(AnnotationMetadata importingClassMetadata,
				BeanDefinitionRegistry registry) {
			if (!registry.containsBeanDefinition(BEAN_NAME)) {
				GenericBeanDefinition beanDefinition = new GenericBeanDefinition();
				beanDefinition.setBeanClass(DataSourceInitializerPostProcessor.class);
				beanDefinition.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
				// We don't need this one to be post processed otherwise it can cause a
				// cascade of bean instantiation that we would rather avoid.
				beanDefinition.setSynthetic(true);
				registry.registerBeanDefinition(BEAN_NAME, beanDefinition);
			}

org.springframework.boot.cli.command.jar.JarOptionHandler

		private boolean isZip(InputStream inputStream) throws IOException {
			for (int i = 0; i < ZIP_FILE_HEADER.length; i++) {
				if (inputStream.read() != ZIP_FILE_HEADER[i]) {
					return false;
				}
			}
			return true;
		}

org.springframework.boot.loader.tools.Repackager

	private boolean isZip(InputStream inputStream) throws IOException {
		for (int i = 0; i < ZIP_FILE_HEADER.length; i++) {
			if (inputStream.read() != ZIP_FILE_HEADER[i]) {
				return false;
			}
		}
		return true;
	}

org.springframework.boot.loader.archive.JarFileArchive

	@Override
	public List<Archive> getNestedArchives(EntryFilter filter) throws IOException {
		List<Archive> nestedArchives = new ArrayList<Archive>();
		for (Entry entry : getEntries()) {
			if (filter.matches(entry)) {
				nestedArchives.add(getNestedArchive(entry));
			}
		}
		return Collections.unmodifiableList(nestedArchives);
	}

org.springframework.boot.loader.archive.ExplodedArchive

	@Override
	public List<Archive> getNestedArchives(EntryFilter filter) throws IOException {
		List<Archive> nestedArchives = new ArrayList<Archive>();
		for (Entry entry : getEntries()) {
			if (filter.matches(entry)) {
				nestedArchives.add(getNestedArchive(entry));
			}
		}
		return Collections.unmodifiableList(nestedArchives);
	}

org.springframework.boot.autoconfigure.jms.activemq.ActiveMQConnectionFactoryConfiguration

	@Bean
	public ConnectionFactory jmsConnectionFactory(ActiveMQProperties properties) {
		ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactoryFactory(
				properties).createConnectionFactory(ActiveMQConnectionFactory.class);
		if (properties.isPooled()) {
			PooledConnectionFactory pool = new PooledConnectionFactory();
			pool.setConnectionFactory(connectionFactory);
			return pool;
		}
		return connectionFactory;
	}

org.springframework.boot.autoconfigure.jms.activemq.ActiveMQXAConnectionFactoryConfiguration

	@Bean
	public ConnectionFactory nonXaJmsConnectionFactory(ActiveMQProperties properties) {
		ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactoryFactory(
				properties).createConnectionFactory(ActiveMQConnectionFactory.class);
		if (properties.isPooled()) {
			PooledConnectionFactory pool = new PooledConnectionFactory();
			pool.setConnectionFactory(connectionFactory);
			return pool;
		}
		return connectionFactory;
	}

org.springframework.boot.cli.compiler.grape.DefaultRepositorySystemSessionAutoConfiguration

	private File getDefaultM2HomeDirectory() {
		String mavenRoot = System.getProperty("maven.home");
		if (StringUtils.hasLength(mavenRoot)) {
			return new File(mavenRoot);
		}
		return new File(System.getProperty("user.home"), ".m2");
	}

org.springframework.boot.cli.compiler.RepositoryConfigurationFactory

	private static File getM2HomeDirectory() {
		String mavenRoot = System.getProperty("maven.home");
		if (StringUtils.hasLength(mavenRoot)) {
			return new File(mavenRoot);
		}
		return new File(System.getProperty("user.home"), ".m2");
	}

org.springframework.boot.cli.command.jar.GrabAnnotationTransform

		@Override
		public void visit(ASTNode[] nodes, SourceUnit source) {
			for (ASTNode node : nodes) {
				if (node instanceof ModuleNode) {
					visitModule((ModuleNode) node);
				}
			}
		}

org.springframework.boot.cli.compiler.DependencyAutoConfigurationTransformation

	@Override
	public void visit(ASTNode[] nodes, SourceUnit source) {
		for (ASTNode astNode : nodes) {
			if (astNode instanceof ModuleNode) {
				visitModule((ModuleNode) astNode);
			}
		}
	}

org.springframework.boot.jta.atomikos.AtomikosDependsOnBeanFactoryPostProcessor

	private String[] getBeanNamesForType(ConfigurableListableBeanFactory beanFactory,
			String type) {
		try {
			return beanFactory.getBeanNamesForType(Class.forName(type), true, false);
		}
		catch (ClassNotFoundException ex) {
			// Ignore
		}
		catch (NoClassDefFoundError ex) {
			// Ignore
		}
		return NO_BEANS;
	}
		return connectionFactory;
	}

org.springframework.boot.jta.bitronix.BitronixDependentBeanFactoryPostProcessor

	private String[] getBeanNamesForType(ConfigurableListableBeanFactory beanFactory,
			String type) {
		try {
			return beanFactory.getBeanNamesForType(Class.forName(type), true, false);
		}
		catch (ClassNotFoundException ex) {
			// Ignore
		}
		catch (NoClassDefFoundError ex) {
			// Ignore
		}
		return NO_BEANS;
	}

org.springframework.boot.ApplicationPid

	private void createParentFolder(File file) {
		File parent = file.getParentFile();
		if (parent != null) {
			parent.mkdirs();
		}
	}

org.springframework.boot.actuate.system.EmbeddedServerPortFileWriter

	private void createParentFolder(File file) {
		File parent = file.getParentFile();
		if (parent != null) {
			parent.mkdirs();
		}
	}

org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationAdapter

		public BeanNameViewResolver beanNameViewResolver() {
			BeanNameViewResolver resolver = new BeanNameViewResolver();
			resolver.setOrder(Ordered.LOWEST_PRECEDENCE - 10);
			return resolver;
		}

org.springframework.boot.autoconfigure.web.WhitelabelErrorViewConfiguration

		public BeanNameViewResolver beanNameViewResolver() {
			BeanNameViewResolver resolver = new BeanNameViewResolver();
			resolver.setOrder(Ordered.LOWEST_PRECEDENCE - 10);
			return resolver;
		}

org.springframework.boot.cli.command.jar.JarOptionHandler

		private List<URL> getClassPathUrls(GroovyCompiler compiler) {
			return new ArrayList<URL>(Arrays.asList(compiler.getLoader().getURLs()));
		}

org.springframework.boot.cli.command.install.GroovyGrabDependencyResolver

	private List<URL> getClassPathUrls(GroovyCompiler compiler) {
		return new ArrayList<URL>(Arrays.asList(compiler.getLoader().getURLs()));
	}

org.springframework.boot.env.EnumerableCompositePropertySource

	@Override
	public Object getProperty(String name) {
		for (PropertySource<?> propertySource : getSource()) {
			Object value = propertySource.getProperty(name);
			if (value != null) {
				return value;
			}
		}
		return null;
	}

org.springframework.boot.context.config.ConfigurationPropertySources

		@Override
		public Object getProperty(String name) {
			for (PropertySource<?> propertySource : this.sources) {
				Object value = propertySource.getProperty(name);
				if (value != null) {
					return value;
				}
			}
			return null;
		}

org.springframework.boot.actuate.metrics.repository.redis.RedisMetricRepository

	private String serialize(Metric<?> entity) {
		return String.valueOf(entity.getTimestamp().getTime());
	}

org.springframework.boot.actuate.metrics.repository.redis.RedisMultiMetricRepository

	private String serialize(Metric<?> entity) {
		return String.valueOf(entity.getTimestamp().getTime());
	}

org.springframework.boot.autoconfigure.jms.hornetq.HornetQConnectionFactoryConfiguration

	@Bean
	public ConnectionFactory jmsConnectionFactory(ListableBeanFactory beanFactory,
			HornetQProperties properties) {
		return new HornetQConnectionFactoryFactory(beanFactory, properties)
				.createConnectionFactory(HornetQConnectionFactory.class);
	}

org.springframework.boot.autoconfigure.jms.hornetq.HornetQXAConnectionFactoryConfiguration

	@Bean
	public ConnectionFactory nonXaJmsConnectionFactory(ListableBeanFactory beanFactory,
			HornetQProperties properties) {
		return new HornetQConnectionFactoryFactory(beanFactory, properties)
				.createConnectionFactory(HornetQConnectionFactory.class);
	}

**Comment by philwebb** [comment]
We'll have to take a look at each one in a little more detail. Many times the duplication is preferable to introducing dependency issues or package tangles. For example, `AtomikosDependsOnBeanFactoryPostProcessor` and `BitronixDependentBeanFactoryPostProcessor` do indeed have identical `getBeanNamesForType` methods, but there isn't an obvious place for that method to move. We don't want the classes to be aware of each other, and introducing a common base class or utils class seems overkill for such a small amount of code.

I generally try to avoid creating `*Utils` classes if possible because they tend to become a dumping ground.

**Comment by philwebb** [comment]
After some consideration I think the duplication is probably better than additional dependencies.
