### ISSUE TITLE
Add bootstrap.yml to filtered resources

### ISSUE THREAD

**Issue by joelroyer** [spring-projects/spring-boot#22769]
Currently, Spring Boot filters those resources in src/main/resources:
- application*.yml
- application*.yaml
- application*.properties

It would be useful to add these resources in order to inject pom properties:
- bootstrap.yml
- bootstrap.yaml
- bootstrap.properties

**Comment by mbhave** [comment]
`bootstrap.yml` is a Spring Cloud feature. Their issue tracker is [here](https://github.com/spring-cloud/spring-cloud-commons).

**Comment by wilkinsona** [comment]
This is also a duplicate of #13062.
