### ISSUE TITLE
Filter test resources

### ISSUE THREAD

**Issue by joelroyer** [spring-projects/spring-boot#22770]
It would be usefull to filter application*.yml in test resources by adding to Spring Boot parent POM:
```xml
<build>
	<testResources>
		<testResource>
			<directory>${basedir}/src/test/resources</directory>
			<filtering>true</filtering>
			<includes>
				<include>**/application*.yml</include>
				<include>**/application*.yaml</include>
				<include>**/application*.properties</include>
			</includes>
		</testResource>
		<testResource>
			<directory>${basedir}/src/test/resources</directory>
			<excludes>
				<exclude>**/application*.yml</exclude>
				<exclude>**/application*.yaml</exclude>
				<exclude>**/application*.properties</exclude>
			</excludes>
		</testResource>
	</testResources>
</build>
```

**Comment by philwebb** [comment]
Thanks for the suggestion, but we found filtering with the default delimiter to be problematic. We do already offer filtering support, but you need to be using the `spring-boot-starter-parent` POM and you need to use `@` as the delimiter. Some documentation in this is available [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-automatic-expansion).

**Comment by philwebb** [comment]
Reopening as I misread this issue as a request to apply filtering in general.

**Comment by snicoll** [comment]
We've discussed this one and while we understand that users may want to filter production resources to include some information from their build, we don't believe it is as common to do this for test resources. If that's what you prefer to do, you can obviously add that configuration in your own project. Thanks for the suggestion, in any case.
