### ISSUE TITLE
Naming inconsistency between AtomikosDependsOnBeanFactoryPostProcessor and BitronixDependentBeanFactoryPostProcessor

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#2278]
`AtomikosDependsOnBeanFactoryPostProcessor` uses 'DependsOn',

whereas `BitronixDependentBeanFactoryPostProcessor` uses 'Dependent'.

**Comment by philwebb** [comment]
I'm not following what you mean here. What lines are you referring to? One uses `beanFactory.registerDependentBean` whilst the other uses `bean.setDependsOn` so I don't think different local variable names are an issue.

**Comment by izeye** [comment]
@philwebb Sorry for confusion. I meant the class names.

Atomikos**DependsOn**BeanFactoryPostProcessor

Bitronix**Dependent**BeanFactoryPostProcessor

**Comment by philwebb** [comment]
The names are reflective of the subtly different way that the processors work. I guess the `AtomikosDependsOnBeanFactoryPostProcessor` could be renamed but I don't think it would be worth it.

**Comment by izeye** [comment]
Ok, it was just a superficial suggestion :-)

**Comment by philwebb** [comment]
No problem, keep them coming. I'd probably change the name if we were still at the milestone phase.
