### ISSUE TITLE
org.springframework.boot.jta.bitronix.PoolingDataSourceBean.getParentLogger() and org.springframework.boot.jta.bitronix.DirectXADataSource.getParentLogger() look like they use a Java 7+ method

### ISSUE THREAD

**Issue by zibbly** [spring-projects/spring-boot#2281]
The ((DataSource) this).getParentLogger() call in the org.springframework.boot.jta.bitronix.PoolingDataSourceBean.getParentLogger()
method looks to use a javax.sql.CommonDataSource interface method that has only existed since Java 7.

If the minimum supported Java version for Spring Boot is Java 6 should this code be using the javax.sql.CommonDataSource.getParentLogger() method?

	@Override
	public Logger getParentLogger() throws SQLFeatureNotSupportedException {
		try {
			return ((DataSource) this).getParentLogger();
		}
		catch (Exception ex) {
			// Work around https://jira.codehaus.org/browse/BTM-134
			return Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);
		}
	}

And the story is the same for org.springframework.boot.jta.bitronix.DirectXADataSource

		@Override
		public Logger getParentLogger() throws SQLFeatureNotSupportedException {
			return this.dataSource.getParentLogger();
		}

**Comment by snicoll** [comment]
Looks like configuring Animal sniffer is in order, see #716

**Comment by wilkinsona** [comment]
In each case a call to `DataSource.getParentLogger()` is being delegated to another `DataSource` instance. The assumption is that the outer method will only be called in Java 7+ and, therefore, the delegation will always be successful. AFAIK, this assumption is sound and the code in question works fine on Java 6 and Java 7+. I don't think we should change the code unless someone presents evidence to the contrary.
