### ISSUE TITLE
Provide health for an AbstractRoutingDataSource's resolved targets

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22824]

**Comment by philwebb** [comment]
Closing in favor of PR #25708

**Comment by limkinZero** [comment]
Hi @bono007 @wilkinsona , I´m check this functionality in a spring boot (2.5.0) test app with one abstractRoutingDataSource and I have some dudes.

Is possible, show the health of resolve target datasources which have been added after the initialization of the datasource bean. In my case, I fill the map with info pickup from one table on my database to create the data sources.

Regards,

**Comment by bono007** [comment]
@limkinZero do you mind asking the question on [Gitter](https://gitter.im/spring-projects/spring-boot#) instead of this closed issue?
