### ISSUE TITLE
Spring data cassandra autoconfig hard codes contact-points which cannot be changed

### ISSUE THREAD

**Issue by garrychnca** [spring-projects/spring-boot#22827]
https://github.com/spring-projects/spring-boot/blob/e26f3e2a65cba16cc0b47b997828456cf4ec3e66/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cassandra/CassandraProperties.java#L57

And I see this in `spring-configuration-metadata.json` bundled with `spring-boot-autoconfigure:2.3.1.RELEASE`:

```
{
    "name": "spring.data.cassandra.contact-points",
    "type": "java.util.List<java.lang.String>",
    "description": "Cluster node addresses in the form 'host:port', or a simple 'host' to use the configured port.",
    "sourceType": "org.springframework.boot.autoconfigure.cassandra.CassandraProperties",
    "defaultValue": [
        "127.0.0.1:9042"
    ]
}
```

In my application I just go ahead and configure `spring.data.cassandra.contact-points` to the non-localhost contact-points of my C* cluster but just to figured that it didn't work at all due to it being hard coded to localhost.

Am I missing something or is this intended?

**Comment by snicoll** [comment]
@garrychnca this is the default value and the metadata is used to display the default value in your IDE.

> In my application I just go ahead and configure spring.data.cassandra.contact-points to the non-localhost contact-points of my C* cluster but just to figured that it didn't work at all due to it being hard coded to localhost.

It's hard to provide you with support with the information that you've shared. Can you please share a small sample that we can run ourselves? (a zip attached to this issue or a link to a GitHub repo).

**Comment by garrychnca** [comment]
I am really sorry this turns out to be my mistake. There is no issue with it and I will close this ticket now.

**Comment by snicoll** [comment]
No worries and thank you for letting us know.
