### ISSUE TITLE
Error due to unknown properties with prefix 'security.'

### ISSUE THREAD

**Issue by kamoor** [spring-projects/spring-boot#2283]
While upgrading to new boot release I came across unknown secuity.xxx properties found error. This is due to a code added as below, 

``` java
@ConfigurationProperties(prefix = "security", ignoreUnknownFields = true)
public class SecurityProperties implements SecurityPrerequisite {
...
}
```

`ignoreUnknownFields = true` restriction will force clients to refactor their code for new upgrades. I am wondering why Boot needs to restrict user properties. Can we make it "ignoreUnknownFields = false"

OR 

Have unique namespace for spring to avoid any property conflicts with third party properties. Something like `spring.security.x`.

**Comment by philwebb** [comment]
Did you mean `ignoreUnknownFields = false` on the `SecurityProperties` class?

**Comment by kamoor** [comment]
Yes, updated

**Comment by snicoll** [comment]
My take at this is that we should try as much as possible to restrict the number of "root" prefixes. `spring`, `security`, `management` and `server` should be the only ones as from now on. Anything that is "libs-related" should go in `spring`. 

I also think that users should accept that situation and not try to define properties within those namespaces. Flipping the `ignoreUnknownFields` attribute isn't just going to fix the issue: we may add extra properties that will conflict with user properties.

**Comment by kamoor** [comment]
@dsyer  What is the third party that uses security.* from System properties? It doesn't matter who has it today or who will have in future. A unique namespace (example log4j.*) will avoid conflict more reliably. In my application I had home grown properties. There may be frameworks tomorrow with such scenarios and it will stop working with boot.  

@snicoll  You are right, Flipping ignoreUnknownFields is dangerous. IMHO, Introducing a unique prefix is the only way to solve problem for ever.

**Comment by philwebb** [comment]
We've move security properties under the `spring` namespace in 2.0 so this issue should be fine now.
