### ISSUE TITLE
ActiveProfiles with comma separated profiles does not work in release 2.3.2

### ISSUE THREAD

**Issue by masrawi** [spring-projects/spring-boot#22857]
the following code will pass in release 2.2.9 but in 2.3.2

```java

@SpringBootTest
@ActiveProfiles("test1,test2")
@ContextConfiguration(classes = SpringBootTestWithActiveProfilesWithCommaTests.class)
public class SpringBootTestWithActiveProfilesWithCommaTests
{

    @Autowired
    private Environment environment;

    @Test
    void getActiveProfiles()
    {
        assertThat(this.environment.getActiveProfiles()).containsOnly("test1", "test2");
    }
}
```

**Comment by snicoll** [comment]
Thanks for the report. I am not sure yet what was the change that led to this but the test above looks wrong to me if you intend to enable two profiles. It should rather be `@ActiveProfiles({"test1", "test2"})`. When I do that change, this test passes for me.

**Comment by snicoll** [comment]
The [release notes for 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) also has a [dedicated section about this](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#activating-multiple-profiles-with-activeprofiles). Please make sure to review them when upgrading.
