### ISSUE TITLE
Kotlin examples for configuring bootBuildImage's environment use wrong map configuration syntax

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#22913]
We document setting some environment variables but the configuration is untested. @sdeleuze thinks the syntax may be wrong so this could turn into a documentation issue.

**Comment by jnizet** [comment]
I think I can take care of this

**Comment by wilkinsona** [comment]
Thanks, @jnizet, but I already have a fix lined up for this one.
