### ISSUE TITLE
Spring Boot Actuator Audit repository method parameter ignored

### ISSUE THREAD

**Issue by damianbl** [spring-projects/spring-boot#2291]
Hi,

`AuditEventRepository` interface has the following method:

`List find(String principal, Date after)`

It is implemented in `InMemoryAuditEventRepository`. The problem is that the second parameter (`Date after`) seems to be ignored.

Spring-Boot-1.2.0.RELEASE

**Comment by philwebb** [comment]
It looks to me like we might also have a potential memory problem by only limiting the capacity per principal. If enough audit events are triggered using different principals then memory could be blown.
