### ISSUE TITLE
Stop registering the default servlet by default

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22915]
The `DefaultServlet` is registered by default and mapped to `/` but in the vast majority of Boot apps this is overridden by the `DispatcherServlet` which is also mapped to `/`. When overridden like this the registration is pointless as the servlet will never be used. To avoid wasting memory and CPU cycles, we should change the default of `server.servlet.register-default-servlet` to `false` and document that you can set it to `true` to reinstate the previous behaviour in apps that were using it.

**Comment by mdiskin** [comment]
I'm good with this so long as we retain server.servlet.context-path functionally. 

We use spring boot/containers to migrate off appservers and the context-path allow for load balancer smart rules on host:port without rewriting the uri.

**Comment by philwebb** [comment]
@mdiskin We're not planning to break that functionality. A lot of user rely on it.

**Comment by wilkinsona** [comment]
Users will need to enable the default servlet if they are:

- Using JSPs
- Using Jersey configured as a filter and the default servlet was previously the servlet at the end of the filter chain

This list probably isn't exhaustive but those are the two identified by Boot's test suite.

**Comment by wtfiwtz** [comment]
Could this impact on loading static resources from the `src\main\webapp` directory of a Spring Boot application? I've attempted to register a new static resource handler for `/**` => `/` but it doesn't seem to make any difference.

We have a IBM WebSphere app that was ported to Spring Boot and the .css file loading is now broken on Spring Boot `2.4.1/2`, but was okay on `2.3.8`. Javascript is loaded through JAWR so most other functionality stays the same.

```
  @Configuration
  public class ApplicationConfig implements WebMvcConfigurer
  {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry)
    {
      registry.addResourceHandler("/path/**").addResourceLocations("/path/");
      registry.addResourceHandler("/**").addResourceLocations("/");
    }
  }
```
There is already a registration for `/**` (confirmed with `hasResourceHandler( )`

Cheers,
Nigel

**Comment by wtfiwtz** [comment]
I added `server.servlet.register-default-servlet=true` to the `application.properties file and this seems to have fixed it.

Cheers!

**Comment by PAX523** [comment]
> Could this impact on loading static resources from the `src\main\webapp` directory of a Spring Boot application? I've attempted to register a new static resource handler for `/**` => `/` but it doesn't seem to make any difference.
> 
> We have a IBM WebSphere app that was ported to Spring Boot and the .css file loading is now broken on Spring Boot `2.4.1/2`, but was okay on `2.3.8`. Javascript is loaded through JAWR so most other functionality stays the same.
> 
> ```
>   ...
>       registry.addResourceHandler("/**").addResourceLocations("/");
>   ...
> ```
> 
> There is already a registration for `/**` (confirmed with `hasResourceHandler( )`
> 
> Cheers, Nigel

That's not good, it allows exposing arbitrary Java classes/etc. in Tomcat deployments.
