### ISSUE TITLE
Default value of server.jetty.accesslog.format is wrongly associated to server.forward-headers-strategy

### ISSUE THREAD

**Issue by cniesen** [spring-projects/spring-boot#22921]
The generated documentation for [ServerProperties](https://docs.spring.io/spring-boot/docs/2.3.2.RELEASE/reference/html/appendix-application-properties.html#server-properties) isn't correct.  
`server.jetty.accesslog.format` default should be "ncsa" while
`server.forward-headers-strategy` should shouldn't have a default. At least I couldn't find in code where that property is initialized. 

Relevant code snippets:
* https://github.com/spring-projects/spring-boot/blob/v2.3.2.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L1182
* https://github.com/spring-projects/spring-boot/blob/v2.3.2.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L91

**Comment by snicoll** [comment]
Thanks for the report. This is a [polish commit](https://github.com/spring-projects/spring-boot/commit/623fbcbf8cc6f9870e55a6755af35558879ddaea#) that unfortunately mixed things up
