### ISSUE TITLE
Mark `bootArchives` as nonresolvable configuration in Gradle plugin to better convey its purpose.

### ISSUE THREAD

**Issue by chali** [spring-projects/spring-boot#22942]
If my understanding is correct `bootArchives` configuration in spring-boot gradle plugin is supposed to be used as a place where artifacts for publishing are placed. If this is correct, I would suggest marking it as non-resolvable. It would help in interactions with other gradle plugins which might manipulate all resolvable configurations and ignoring `bootArchives` requires special handling.

**Comment by wilkinsona** [comment]
That's a good suggestion. Thank you. For future reference, please feel free to jump straight to a PR unless you'd like to discuss a change before implementing it. Closing in favour of #22943.
