### ISSUE TITLE
Rename neo4j.version to neo4j-java-driver.version

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#22952]
In Spring Boot 2.4.0-M2, `neo4j.version` will probably lead to confusion: It is currently used to specify the version of the [Neo4j Java Driver ](https://github.com/neo4j/neo4j-java-driver) which is most often not the same as the Neo4j server version. 

I would much appreciate  a change back to

```
<neo4j-java-driver.version>4.1.1</neo4j-java-driver.version>
```

As it was in the independent driver starter we at Neo4j developed.

Paging @meistermeier, too

**Comment by snicoll** [comment]
The version is inferred by the name of the dependency in `spring-boot-dependencies` and it was [originally contributed as `Neo4j`](https://github.com/spring-projects/spring-boot/pull/22301/files#diff-76ff4fe38f0762e0fcb54986cae8e0b6R1177). 

It's easy enough to rename that to `Neo4j Java Driver` and I agree it would be better indeed. Thanks for the suggestion.

**Comment by michael-simons** [comment]
I guess that was an oversight on our side in those huge PRs. Thanks for the quick fix, much appreciated.
