### ISSUE TITLE
Add a registry to support long lived instances during environment processing

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22956]
Currently `ConfigDataLocationResolver` and `ConfigDataLoader` only support ephemeral connections and object instances. For some technologies, these might be expensive to create. It would be helpful if we could provide some mechanism to manage the lifecycle of such instances. It would also be nice if they could sometimes get converted into true bean instances that can be registered in the application context.

**Comment by spencergibb** [comment]
The specific request is to support vault's session (/cc @mp911de) in spring cloud vault and a curator connection in spring cloud zookeeper. This may be applicable for other future config data implementations in GCP, Azure, AWS or Alibaba (which all have spring cloud `PropertySourceLocator` implementations right now).
