### ISSUE TITLE
CommandLine Runner Hangs When Trying to Close JPA EntityManagerFactory

### ISSUE THREAD

**Issue by jmiller-boundless** [spring-projects/spring-boot#2295]
Using Spring Boot 1.1.9 Release with Hibernate-JPA 2.0 to build a desktop application that implements CommandLineRunner.  Calling ConfigurableApplicationContext.close() hangs with the following in the console output:
  main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'

Manually closing the EntityManagerFactory (retrieved using @PersistenceUnit) successfully closes the Factory but leads to an error when  ConfigurableApplicationContext.close() is called and doesn't solve the issue (the application remains open).

**Comment by wilkinsona** [comment]
It sounds like that log message may be a red herring. Can you take a thread dump when it's hung please?

**Comment by jmiller-boundless** [comment]
Thread [AWT-EventQueue-0] 	
	Unsafe.park(boolean, long) line: not available [native method]	
	LockSupport.park(Object) line: 186	
	AbstractQueuedSynchronizer$ConditionObject.await() line: 2043	
	EventQueue.getNextEvent() line: 543	
	EventDispatchThread.pumpOneEventForFilters(int) line: 211	
	EventDispatchThread.pumpEventsForFilter(int, Conditional, EventFilter) line: 161	
	EventDispatchThread.pumpEventsForHierarchy(int, Conditional, Component) line: 150	
	EventDispatchThread.pumpEvents(int, Conditional) line: 146	
	EventDispatchThread.pumpEvents(Conditional) line: 138	
	EventDispatchThread.run() line: 91

**Comment by wilkinsona** [comment]
Is that the only thread that's running? If so, the problem's with AWT/Swing and has nothing to do with Boot

**Comment by jmiller-boundless** [comment]
You are absolutely correct.  Apologies for the confusion.
