### ISSUE TITLE
Changes in Log4JLoggingSystem breaks Log4j logging

### ISSUE THREAD

**Issue by j-gurda** [spring-projects/spring-boot#2296]
I believe that changes in commit cf24af0bfbfdd778bfb076947ea6f012a88f372d in class Log4JLoggingSystem may break Log4j configuration in some scenarios. Here is the code added:

```java
public void beforeInitialize() {
	super.beforeInitialize();
	LogManager.getRootLogger().setLevel(Level.FATAL);
}
```
You simply set RootLogger to use FATAL level. In my use case scenario I use the simplest log4j.xml configuration:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration debug="true"
	xmlns:log4j='http://jakarta.apache.org/log4j/'>
 
	<appender name="console" class="org.apache.log4j.ConsoleAppender">
	    <layout class="org.apache.log4j.PatternLayout">
		<param name="ConversionPattern" 
		  value="%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n" />
	    </layout>
	</appender>
 
	<root>
		<level value="INFO" />
		<appender-ref ref="console" />
	</root>
 
</log4j:configuration>
```

When using Spring Boot 1.1.9 I saw log entries being printed to console however logging is broken in 1.2.0 (I see only banner).
After some time of playing with debugger I realized that RootLogger is initialized (and also INFO level is set) before method Log4JLoggingSystem.beforeInitialize() is called. This results in FATAL level being set for RootLogger in my application and no log entries printed on console.

**Comment by philwebb** [comment]
Have you tried 1.2.1-BUILD-SNAPSHOT? I have a feeling that this has been fixed in #2125

**Comment by j-gurda** [comment]
Thanks Phil. That works for me.

**Comment by philwebb** [comment]
Cool. We'll be releasing 1.2.1 very soon.
