### ISSUE TITLE
java.lang.VerifyError: class reactor.ipc.netty.http.client.MonoHttpClientResponse overrides final method subscribe.(Lorg/reactivestreams/Subscriber;)V

### ISSUE THREAD

**Issue by HarshaVardhanAcharyAthaluri** [spring-projects/spring-boot#22969]
failed with following dependency
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
again tried by excluding netty still same issue

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-boot-starter-reactor-netty</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by snicoll** [comment]
@HarshaVardhanAcharyAthaluri this error indicates that you have most likely incompatible versions on the classpath. Without sharing the version that you are using in the form of a sample project, it will be very hard for us to help you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by HarshaVardhanAcharyAthaluri** [comment]
after updating jetty version its working

**Comment by snicoll** [comment]
Glad you got it resolved.
