### ISSUE TITLE
@ConfigurationProperties and @EnableConfigurationProperties cannot bind any properties in .yml or .properties

### ISSUE THREAD

**Issue by jxsrlsl1234** [spring-projects/spring-boot#22978]
issues in : 
https://stackoverflow.com/questions/63448844/configurationproperties-and-enableconfigurationproperties-cannot-bind-any-prop

SpringBoot version: 2.3.2

**Comment by snicoll** [comment]
In the interest of avoiding duplicating efforts I am going to close this one in favour of your SO question.
