### ISSUE TITLE
Rename CompositeMeterRegistryAutoConfiguration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22988]
`CompositeMeterRegistryAutoConfiguration` might actually not create a composite registry. We should probably rename it to `MeterRegistryAutoConfiguration`.

**Comment by evenh** [comment]
Just updated some autoconfiguration code depending on `CompositeMeterRegistryAutoConfiguration` from `v2.3.4.RELEASE` to `2.4.0-M3` and traced it back to this issue. It broke my configuration classes and test code.

My question is: `CompositeMeterRegistryAutoConfiguration` not extending `MeterRegistryAutoConfiguration`, is it a deliberate choice?

**Comment by philwebb** [comment]
@evenh Thanks for raising this, we're going to revert the rename before GA
