### ISSUE TITLE
Upgrade to Spring Integration 5.4.0-M3 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23010]

**Comment by krohan100** [comment]
HI Phil, I would like to work on this issue.

**Comment by snicoll** [comment]
@krohan100 thank you for offering to contribute but we prefer to do dependency upgrades ourselves (this is usually about flipping the version once the dependency has been released).

**Comment by krohan100** [comment]
@snicoll Thanks for your reply! Just for clarification, why was this issue public if it was to be done by th eteam itself? Aldo are there any more issues to work ( specific tags ) which can be done my a member outside the team?

**Comment by snicoll** [comment]
> why was this issue public if it was to be done by the team itself?

There is no such concept of private issues on GitHub and even if it were, it's all OSS so we really have no intention to hide this from the community. Concretely, there is not much work to be done here besides [changing the version of Spring Integration](https://github.com/spring-projects/spring-boot/commit/0beb30bb5ae7e6b3256c80eb8f3e034b0ebb4157) in the build. We can't do that as the version hasn't been released yet and we like to do it as soon as it is. If you're looking to contribute on Spring Integration features and you have ideas, feel free to raise an issue or submit a PR for it.

The issue tracker also has [status: ideal-for-contribution](https://github.com/spring-projects/spring-boot/issues?q=label%3A%22status%3A+ideal-for-contribution%22+is%3Aopen) tagged issues for issues that we believe can be handled by the community.
