### ISSUE TITLE
can spring-boot support druid connection pool

### ISSUE THREAD

**Issue by luffyke** [spring-projects/spring-boot#2301]
i have found from the document, and seems that spring-boot only support tomcat-jdbc,HikariCP and DBCP connection pool, if i want to use druid(https://github.com/alibaba/druid/wiki/FAQ) in my project with spring-boot, may i know how to do?

**Comment by philwebb** [comment]
This kind of question is best asked on stackoverflow.com (use the `spring-boot` tag).

We don't currently offer any auto-configuration support for druid, but you should be able to configure directly as you would any other Spring Bean. Probably something like this:

```java
@Bean
public DruidDataSource dataSource() {
    DruidDataSource ds = new DruidDataSource();
    ds.setUrl(...);
    ds.setUserName(...);
    ds.setPassword(...);
    // any other configuration
    return ds;
}
```
