### ISSUE TITLE
Refine OnClassCondition thread split threshold

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23026]
We currently split to the threaded mode whenever the number of classes is more than one. This probably isn't very efficient and a bigger threshold would be better.

**Comment by dreis2211** [comment]
In a vanilla app there is only one call anyhow that has more than 1 class passed and you can easily reach 200+ classes with actuator + web + security, which could probably benefit from splitting the work in half, so I'm wondering what threshold you have in mind, @philwebb ? Maybe `classes > Runtime.availableProcessors()`?

**Comment by philwebb** [comment]
I was thinking something fairly low, but more than 1. Perhaps I'll try something around 20.

**Comment by philwebb** [comment]
I guess it won't make a difference for most current apps.
