### ISSUE TITLE
mvn compile error

### ISSUE THREAD

**Issue by BaleroCMS** [spring-projects/spring-boot#2303]
Im trying making my application auto-reloading when user's edit/save changed java file. After

> $ mvn spring-boot:run

Edit some file and:

> $ mvn compile

> Spring Loaded: Cannot reload new version of com.sun.proxy.$Proxy77
> Reason: Type modifiers changed

Any solution?

Regards!

**Comment by philwebb** [comment]
It sounds like a Spring Loaded issue. @aclement might have some ideas. Not all types of change are supported, what did you actually change in your class to trigger the reload?

**Comment by aclement** [comment]
That is a strange one, I'm a bit surprised type modifiers are changing on a generated proxy class. As Phil said, useful to know what you changed. Many of these issues need me to locally recreate them before i can sort them out.

**Comment by kkilaru** [comment]
Seems to be happening when I make any change to a class marked @Component. Even if it is just an addition of a comment or changing a method parameter name. It works fine with similar changes in @RestController or @Service classes.

**Comment by neblina-software** [comment]
Any update?

**$ mvn compile**

> Spring Loaded: Cannot reload new version of com.sun.proxy.$Proxy97
> Reason: Type modifiers changed from=0x11 to=0x31

Tested with: https://github.com/neblina-software/balerocms-enterprise

**Comment by philwebb** [comment]
I'm afraid this one is almost certainly a Spring Loaded issue. Please raise an issue at https://github.com/spring-projects/spring-loaded with the exact steps needed to reproduce.
