### ISSUE TITLE
Caffeine cache metrics don't work with caches created via spring.cache.cache-names

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#23047]
Caffeine cache metrics don't work with caches created via `spring.cache.cache-names` as the caches don't seem to record statistics.

See https://github.com/izeye/spring-boot-throwaway-branches/tree/cache-caffeine for a sample project to reproduce this.

If a custom `Caffeine` bean with `recordStats()` is provided, the metrics work.

See https://github.com/izeye/spring-boot-throwaway-branches/tree/cache-caffeine-custom for an updated one.

**Comment by michaldo** [comment]
After spending few hours for searching why my caches are have no metrics I vote for add this sentence to https://docs.spring.io/spring-boot/3.4/reference/actuator/metrics.html#actuator.metrics.supported.cache

**Comment by snicoll** [comment]
> I vote for add this sentence

What sentence? The fact that recordStats must be enabled? That's a cache-specific settings that is not related to Spring Boot.

**Comment by michaldo** [comment]
What sentence? I don't know 😄 

When i read the chapter, I understand that cache metrics works out of the box and then only issue to care is setup cache names in advance. 
The minimal sentence which helps me is "_Note: cache metrics are not enabled automatically and must be enabled within cache provider configuration_"

The enough sentence would be "spring.cache.caffeine.spec=recordStats". This sentence let me enable Caffeing metrics in 25 seconds.
I'm aware that each cache provider has own configuration and even provider may be configured in many ways. 
It may be a challenge to describe how to enable metrics for each provider and for each configuration way.

But small sentence `spring.cache.caffeine.spec=recordStats` for reference documentation, big help for developers. May be it could be an example?

**Comment by snicoll** [comment]
> When i read the chapter, I understand that cache metrics works out of the box

Fair enough, I guess. Everything else in the cache library you're using should be configured (TTL, size, expiration policy, metrics). I have added a note as you suggested.
