### ISSUE TITLE
spring.redis.timeout seems to apply inconsistently across its implementations

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#23070]
Looking at the code related to `spring.redis.timeout` application property, it seems to apply inconsistently across its implementations as follows:

- Jedis: Connect and read timeouts
- Lettuce: Command (read) timeout

Its document says "Connection timeout.".

Aside from its inconsistency, it would be good if connect and read timeouts could be configured separately.

**Comment by snicoll** [comment]
Closing in favour of PR #23137
