### ISSUE TITLE
Deprecate HSQL in EmbeddedDatabaseConnection and add HSQLDB as its preferred replacement

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#23092]
## Problem

We have to enums related to databases and their JDBC drivers, `EmbeddedDatabaseConnection` and `DatabaseDriver`. Both of a constant related to HSQLDB, but they're not named consistently. The constant in `EmbeddedDatabaseConnection` is named `HSQL` while in `DatabaseDriver` it's named `HSQLDB`. 

## Solution

We'd like to remove this inconsistency by replacing `EmbeddedDatabaseConnection.HSQL` with `EmbeddedDatabaseConnection.HSQLDB`. To avoid breaking backwards compatibility a new constant named `HSQLDB` should be introduced and the existing `HSQL` constant should be deprecated in favour of the new `HSQLDB` constant.

**Comment by desainidhi99** [comment]
Is these open ? Then i would like to give it a try

**Comment by mbhave** [comment]
@desainidhi99 sure! Feel free to ask any questions that you have and I'll be happy to help.

**Comment by Bhanu-Latha** [comment]
Hi Nidhi, can I pair with you to work on this issue?

**Comment by mbhave** [comment]
Closing in favor of PR #23565.
