### ISSUE TITLE
Manual addition to a collection could be replaced with the use of Collections.addAll

### ISSUE THREAD

**Issue by zibbly** [spring-projects/spring-boot#2309]
Just like #2277 in the `org.springframework.boot.autoconfigure.condition.OnClassCondition.addAll(List<String>, List<Object>)` method a for loop to add elements to a collection could be replaced by use of the `Collections.addAll` method. This would also remove a redundant `toString()` call on the existing `arrayItem` that is already a String.

```java
org.springframework.boot.autoconfigure.condition.OnClassCondition.addAll(List<String>, List<Object>)

	private void addAll(List<String> list, List<Object> itemsToAdd) {
		if (itemsToAdd != null) {
			for (Object item : itemsToAdd) {
				for (String arrayItem : (String[]) item) {
					list.add(arrayItem.toString());
				}
			}
		}
	}
```

to

```java
	private void addAll(List<String> list, List<Object> itemsToAdd) {
		if (itemsToAdd != null) {
			for (Object item : itemsToAdd) {
				Collections.addAll(list, (String[]) item);
			}
		}
	}
```

**Comment by zibbly** [comment]
Here's some more candidates...

org.springframework.boot.SpringApplication.configureProfiles(ConfigurableEnvironment, String[])

		for (String profile : this.profiles) {
			profiles.add(profile);
		}

to

		Collections.addAll(profiles, this.profiles);

org.springframework.boot.context.config.Loader.addConfigurationProperties(MutablePropertySources)

			for (PropertySource<?> item : sources) {
				reorderedSources.add(item);
			}

to

			Collections.addAll(reorderedSources, sources);

org.springframework.boot.context.embedded.MimeMappingsTests.iterate()

		for (MimeMappings.Mapping mapping : mappings) {
			mappingList.add(mapping);
		}

to

		Collections.addAll(mappingList, mappings);

org.springframework.boot.context.web.SpringBootServletInitializerTests.equalToSet(Object...)

		for (Object item : items) {
			set.add(item);
		}

to

		Collections.addAll(set, items);

org.springframework.boot.actuate.metrics.Iterables.collection(Iterable<T>)

		for (T t : iterable) {
			list.add(t);
		}

to

		Collections.addAll(list, iterable);

org.springframework.boot.actuate.metrics.reader.CompositeMetricReader.findAll() 

			for (Metric<?> value : all) {
				values.add(value);
			}

to

		Collections.addAll(values, all);

sample.data.gemfire.SampleDataGemFireApplicationTests.asList(final Iterable<Gemstone>) 

			for (Gemstone gemstone : gemstones) {
				gemstoneList.add(gemstone);
			}

to

		Collections.addAll(gemstoneList, gemstones);

org.springframework.boot.bind.PropertiesConfigurationFactory.getNames()

					for (String relaxedName : new RelaxedNames(prefix + name)) {
						names.add(relaxedName);
					}

to

		Collections.addAll(names, new RelaxedNames(prefix + name));

org.springframework.boot.actuate.endpoint.MetricReaderPublicMetrics.metrics()

		for (Metric<?> metric : this.metricReader.findAll()) {
			result.add(metric);
		}

to

		Collections.addAll(result, this.metricReader.findAll());

org.springframework.boot.actuate.endpoint.VanillaPublicMetrics.metrics() 

		for (Metric<?> metric : this.reader.findAll()) {
			result.add(metric);
		}

to

		Collections.addAll(result,  this.reader.findAll());

**Comment by zibbly** [comment]
And this candidate too...

org.springframework.boot.cli.compiler.GroovyCompiler(final GroovyCompilerConfiguration)

		for (ASTTransformation transformation : ServiceLoader
				.load(SpringBootAstTransformation.class)) {
			this.transformations.add(transformation);
		}

to

Collections.addAll(this.transformations,  ServiceLoader.load(SpringBootAstTransformation.class));

**Comment by wilkinsona** [comment]
Thanks. A lot of these were false positives as Collections.addAll doesn't work with an Iterable. I've modified the ones that were applicable.
