### ISSUE TITLE
Add global optional config data opt-out

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23097]
The recently introduced `optional:` prefix causes problems for Spring Cloud and likely for some of our users as well. We should offer a quick way to opt-out. One idea would be a `spring.config.on-import-not-found=WARN/IGNORE/FAIL` property.

**Comment by philwebb** [comment]
I went with a slightly simpler `boolean` property in the end.

**Comment by wilkinsona** [comment]
In the interests of future-proofing things, I wonder if we should use an enum with two values rather than a boolean?

**Comment by philwebb** [comment]
`spring.config.on-location-not-found` `WARN/IGNORE/FAIL`
