### ISSUE TITLE
Log ApplicationAvailability state changes

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#23098]
While discussing #22632, we thought that logging `ApplicationAvailability` state changes should be generally useful for applications, even if Actuator is not on the classpath.

Here's a sample use case: the readiness state of the application changes and this change is logged right away; the platform later notices that change and reacts accordingly by not sending traffic anymore. This allow developers to better understand issues where the application state changes and the expected action is not performed in time, maybe because of a check interval issue.

**Comment by philwebb** [comment]
Should this be 2.4.x?
