### ISSUE TITLE
Change favicon default StaticResourceLocation

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#23126]
Currently, in `org.springframework.boot.autoconfigure.security.StaticResourceLocation`, there is only `favicon.ico` support. Given that [favicons can be SVG images](https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df) now as well, it might be good to add support for those?

I believe just changing:

```
FAVICON("/**/favicon.ico");
```

to 
```
FAVICON("/**/favicon.ico", "/**/favicon.svg");
```

should be enough?

(Note sure why there is `/**` in there. Aren't favicons located at the root always?)

**Comment by philwebb** [comment]
There's an issue about the `/**/` path open in #22833
