### ISSUE TITLE
PropertiesLoader can't see files in the root of the classpath if using -cp "."

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2314]
It seems like it sees everything else, including files in the filesystem at ".", but not the files in the root of the jar.

SO link: http://stackoverflow.com/questions/27825904/no-qualifying-bean-of-type-org-springframework-jdbc-core-jdbctemplate-with-sprin/27826843?noredirect=1#comment44091195_27826843

**Comment by wilkinsona** [comment]
The fix for gh-270 has regressed. It works in 1.1.5.RELEASE but is broken since then.

**Comment by wilkinsona** [comment]
@dsyer I'm not sure I understand why gh-270 was fixed. Setting `loader.path` to `.` seems to be saying that you don't want `lib/` to be on the classpath and all you want is the root of the archive, and/or the current working directory. Coming back to this issue, that's certainly what the Stackoverflow user seemed to expect, and what is shown in [their recreation project](https://github.com/Aure77/spring-boot-classpath-sample). I can fix this issue with a simple change to stop stripping out the '.' path:

```diff
diff --git a/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java b/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java
index 6f8d6ee..d299e05 100644
--- a/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java
+++ b/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java
@@ -314,7 +314,7 @@ public class PropertiesLauncher extends Launcher {
                        path = cleanupPath(path);
                        // Empty path (i.e. the archive itself if running from a JAR) is always added
                        // to the classpath so no need for it to be explicitly listed
-                       if (!(path.equals(".") || path.equals(""))) {
+                       if (!(path.equals(""))) {
                                paths.add(path);
                        }
                }
```

I can't, however, see how to do that and also have the scenario described in gh-270 work as well.

**Comment by dsyer** [comment]
I'm not sure I ever knew what the problem was in #270. The "fix" was in response to a problem I thought I had identified as a result of failing to find the original problem - classpath resources in the JAR archive not being available from the `PropertiesLauncher` if `loader.path` is set. That problem seems to be fairly well posed and similar if not identical to this one (#2314), so hopefully we can converge on a solution. Always having "." on the classpath seems like it might be wrong (since the filesystem might not always be needed), and I think that's why the "." is excluded in the "if" statement above. But I don't really follow the logic in there (despite having written it), so I think we can proceed to a fix for the underlying problem(s).

I think there are 2 things I would want as a user: 

1. Resources from the JAR itself (in "." and "lib") should always be on the classpath, whether or not the user supplies a `loader.path` (I think adding "." to an empty path win d299e05 was a hack to provide the illusion that this was working)

2. The `loader.path` could add "." and "lib" (meaning on the filesystem) and those would take precedence, but not replace the jar resources.
