### ISSUE TITLE
MongoMappingContext not getting auto wired

### ISSUE THREAD

**Issue by srchaitanya** [spring-projects/spring-boot#23149]
In my application, we were using Spring Boot **2.1.6.Release**.
And in one of the application classes, we have auto wired- MongoMappingContext class.
When I run the app, it works fine and autowiring happens.
Now I upgraded the Spring Boot version to **2.2.6.Release**.
Now when I start the app, the autowiring of the class **MongoMappingContext** starts failing.

**Comment by snicoll** [comment]
@srchaitanya it is very hard to give you support with the information that you've provided. I suppose that "start failing" means that the bean is not found but perhaps that's something else entirely. You could run your application [in debug mode](https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/spring-boot-features.html#boot-features-startup-failure) to look at the auto-configuration report and find out why `MongoMappingContext` wasn't created.

If that doesn't help and you want support, please share a small sample that reproduces the problem. You can do so by attaching a zip to this issue or sharing the link to a GitHub repository.

**Comment by srchaitanya** [comment]
My apologies for wrongly raising the issue. There is no issue with MongoMappingContext.
There was a Maven issue in my PC and that lead me to believe that the auto-wiring issue with MongoMappingContext.
After maven issue is fixed, I tried again, and found no auto-wiring issue.

**Comment by snicoll** [comment]
Thanks for letting us know.
