### ISSUE TITLE
Consider setting spring.beaninfo.ignore=true by default

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#23147]
Could we consider to set `spring.beaninfo.ignore=true` in Spring Boot (2.4.0+) applications? I don't think this JavaBeans compatibility legacy capability makes sense in Boot apps context and would improve Spring Boot efficiency.

See https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/CachedIntrospectionResults.java#L96

**Comment by dreis2211** [comment]
Isn't it already defaulting to true in `SpringApplication`?

```
	private void configureIgnoreBeanInfo(ConfigurableEnvironment environment) {
		if (System.getProperty(CachedIntrospectionResults.IGNORE_BEANINFO_PROPERTY_NAME) == null) {
			Boolean ignore = environment.getProperty("spring.beaninfo.ignore", Boolean.class, Boolean.TRUE);
			System.setProperty(CachedIntrospectionResults.IGNORE_BEANINFO_PROPERTY_NAME, ignore.toString());
		}
	}
```

I would rather argue to make it default to `false` to make use of the JDK internal caching of things. While looking through some things for #23114 I noticed that this might help a little.

**Comment by sdeleuze** [comment]
Good point I was not aware it was already set of that so I close this issue. I am surprised by your findings, but let's track that point as part of #23114 then.
