### ISSUE TITLE
spring-data-mongodb 3.0.3 getPath doesn't try catch

### ISSUE THREAD

**Issue by leopard7777777** [spring-projects/spring-boot#23150]
![image](https://user-images.githubusercontent.com/11750796/91737524-c4ca9080-ebe1-11ea-9b89-f4ad78847cc1.png)
![image](https://user-images.githubusercontent.com/11750796/91737754-12df9400-ebe2-11ea-9366-a6eaf2860ead.png)
![image](https://user-images.githubusercontent.com/11750796/91738197-b4ff7c00-ebe2-11ea-9c72-b27c4a7650d8.png)
![image](https://user-images.githubusercontent.com/11750796/91737772-1b37cf00-ebe2-11ea-9868-ff4481ed0767.png)
![image](https://user-images.githubusercontent.com/11750796/91737798-2428a080-ebe2-11ea-96cc-676794c66c5c.png)
![image](https://user-images.githubusercontent.com/11750796/91737819-2db20880-ebe2-11ea-88be-8df3da41ac7d.png)
![image](https://user-images.githubusercontent.com/11750796/91737889-4b7f6d80-ebe2-11ea-9eda-c03426d9866b.png)
![image](https://user-images.githubusercontent.com/11750796/91738447-0f004180-ebe3-11ea-87c5-8389c5dfd46d.png)
![image](https://user-images.githubusercontent.com/11750796/91737921-563a0280-ebe2-11ea-8385-e56917729823.png)

org.springframework.data.mongodb.core.convert.QueryMapper.java  line:561
PropertyPath.from need try catch and return null

**Comment by snicoll** [comment]
@leopard7777777 `org.springframework.data.mongodb.core.convert.QueryMapper` is part of Spring Data and they use [Jira for issue tracking](https://jira.spring.io/projects/DATAMONGO/issues/). If you believe you've found a bug in Spring Data, please create an issue there as we can't move it. When you do, please do not attach screenshots as you've done here. If you have a small sample that reproduces the NPE, that would be ideal. Thank you.
