### ISSUE TITLE
Update Paketo builder coordinates to Dockerhub location

### ISSUE THREAD

**Issue by kvedurmu** [spring-projects/spring-boot#23152]
The Paketo Buildpacks project is actively moving away from GCR locations for builders to Dockerhub. We'll continue shipping builders to GCR so that we're not breaking Spring Boot users, but it would be great if we could get Paketo Buildpack builder coordinates updated to the Dockerhub location before the next major release so that we could eventually stop publishing to GCR.

Builder locations:
Tiny: `paketobuildpacks/builder:tiny`
Base: `paketobuildpacks/builder:base`
Full: `paketobuildpacks/builder:full`

CC: @nebhale

**Comment by scottfrederick** [comment]
Marking this for team attention to discuss what version we should make this change in. It *should* be safe to change the default builder location in `2.3`, but there might be reasons to only change it for `2.4`. 

We should also review the use of `base` vs `full` or `tiny`, and possibly the stack we're choosing by default. Any change in these builder variants should probably only be done in `2.4`.

**Comment by scottfrederick** [comment]
Superseded by #23628
