### ISSUE TITLE
Add settings for deadlock retry on repositories

### ISSUE THREAD

**Issue by cesnek** [spring-projects/spring-boot#2317]
With high volumes database operations - deadlock can happen even on select statement.
http://stackoverflow.com/questions/5826600/transaction-deadlock-for-select-query
http://stackoverflow.com/questions/661908/sql-server-deadlocks-between-select-update-or-multiple-selects

There is about four possible resolutions. 
Suggested fixes include adding an index that covers all of the columns the select needs, switching to snapshot isolation, or explicitly forcing the select to grab an update lock that it wouldn't normally need.

No silver bullet for whole application.

**We think about the creation repositoty aspect, which repeates safe (readonly) operations.**
In our experience, it will solve all the problems across the entire application.

What about add this to spring boot
*spring.repository.deadlockretry.count = -1*

**Comment by philwebb** [comment]
This is something that @olivergierke might have an opinion on. My initial reaction is that this isn't a problem that we should try to solve in Spring Boot, but it's something that we could support if something were developed in Spring Data.

**Comment by olivergierke** [comment]
I don't think this is a feature for Boot necessarily but probably one of the data related projects. Reading your suggestions it becomes quite clear that you might even have to influence the persistence operations on a very fine grained level. This makes me wonder whether a feature like this shouldn't even be part of your application and could be composed of a simple aspect using mechanisms of [Spring Retry](https://github.com/spring-projects/spring-retry) eventually exposing a few settings (including the suggested one) via a `@ConfigurationProperties` type.

**Comment by cesnek** [comment]
Yes, is probably Spring Data bussiness.

In fact it is complex problem, because some repository might rollback whole transaction when deadlock occurs. So Spring Data must not allow a retry. 

_Thank for Spring Retry tip_
