### ISSUE TITLE
Add a command line option for image.cleanCache when building with Maven

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#23202]
One of the build plugin configuration properties that is not current exposed on the command line (with Maven at least) is `image.cleanCache`. It would be quite helpful to be able to clear the cache once via a command line switch (rather than have it do that on every build).

**Comment by scottfrederick** [comment]
The command-line option for cache cleaning should be added to the Gradle plugin also. 

For the Maven plugin, the command-line option should be `mvn spring-boot:build-image -Dspring-boot.build-image.cleanCache=[true|false]`. 
For the Gradle plugin, the command-line option would be `gradle bootBuildImage --cleanCache=[true|false]`.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/23206 is tracking the change to the Gradle plugin.

**Comment by Bhanu-Latha** [comment]
I would like to work on it

**Comment by mbhave** [comment]
@Bhanu-Latha Sure. Let me know if you have any questions.

**Comment by snicoll** [comment]
@Bhanu-Latha how is it going? If you don't have time to look at this anymore, please let us know.

**Comment by snicoll** [comment]
In the meantime, someone else in the community submitted a PR for this issue so I am going to close this is issue in favour of #23719. 

Sorry it didn't work out @Bhanu-Latha. We'll do our best to continue sharing issues that are ideal for contribution. If you're interested, please watch the `status: ideal-for-contribution` label.
