### ISSUE TITLE
Add startup Actuator endpoint

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#23213]
As of #22603, developers can configure a `BufferingApplicationStartup` on their `SpringApplication` and collect application startup events.

While this feature can be used by a custom component to push this data in an external metrics system - we should provide a dedicated Actuator endpoint that drains the buffered data and exports it as a JSON document for further analysis.

**Comment by wilkinsona** [comment]
It's unusual for a `@ReadOperation` (which maps to a GET request with HTTP access) to have side-effects. I wonder if it should be a `@WriteOperation` (POST request when exposed over HTTP) of some form? The goal of that would be to make the draining behaviour clearer and also aligns a bit better with conventional HTTP semantics.

**Comment by bclozel** [comment]
Good call, I'll change that to a POST. I don't see the point of adding a fetch-only variant (i.e. not draining) but at least this change leaves this option on the table.

**Comment by qian0205** [comment]
hello, I want to use the startup endpoint of actuator, but i don't know how to configure and code. Can you post the code for reference, Thanks!

**Comment by bclozel** [comment]
@qian0205 [this section of the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-application-startup-tracking) should help. Thanks!
