### ISSUE TITLE
Allow @ConstructorBinding to be optional

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23216]
Currently `ConfigurationPropertiesBindConstructorProvider` requires that `@ConstructorBinding` be used to indicate that a `@ConfigurationProperties` instance should use the `ValueObjectBinder`. I think we could skip the need for this if there is a single constructor with one or more arguments.

Somewhat related to #23172

**Comment by Davio** [comment]
Would this mean that my `@ConfigurationProperties` classes which are currently annotated by Lombok's `@Data` (which creates getters and setters for my non-final fields) can be annotated by `@Value` instead (which creates final fields with an all args constructor)?

If so, I think that would be a reasonable improvement.

**Comment by snicoll** [comment]
>  I think we could skip the need for this if there is a single constructor with one or more arguments.

I don't think we can/should. I remember us having a very lengthy conversation that concluded with the current arrangement. One problem with this approach is that you can't opt-out if you happe to have a single constructor and you don't want it to be used that way (can be surprising for folks having an existing class that users javabean conventions and a constructor for whatever reason).

**Comment by Davio** [comment]
Maybe it's an idea to consolidate `@ConfigurationProperties` and `@ConstructorBinding` by adding the binding mode as an optional property to `@ConfigurationProperties` or something like `useConstructor = true` which would work if there is a single constructor?

Would it work if the constructor only sets some of the properties, but others should still be set by setters?

**Comment by philwebb** [comment]
@snicoll I remember some discussions, but I can't remember exactly why we landed on the current setup.

> One problem with this approach is that you can't opt-out if you happen to have a single constructor and you don't want it to be used that way

Ah yes, I remember now. The issue is that you may have a `@ConfigurationProperties` class that is either a `@Component` or is loaded via a `@Import`. In those situations you want Spring to inject beans into the constructor and getter/setter binding to be applied afterwards.
