### ISSUE TITLE
Update configuration metadata appendix to remove description for Gradle 4.5 and earlier as it is no longer supported

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#23245]
The reference documentation [describes how to configuration the annotation processor](https://docs.spring.io/spring-boot/docs/2.2.9.RELEASE/reference/htmlsingle/#configuration-metadata-annotation-processor) to generate configuration property metadata. For Gradle, different configuration for Gradle 4.5 and earlier and Gradle 4.6 and later is described. The minimum supported version of Gradle is 4.10 so the description can be simplified to only describe the Gradle 4.6 and later approach.

**Comment by ketaki-t** [comment]
I would like to give this a try.

**Comment by mbhave** [comment]
@ketaki-t sure! Let me know if you have any questions.

**Comment by mbhave** [comment]
Closing in favor of PR #23562.
