### ISSUE TITLE
Make maxAliasesForCollections of yaml loader configurable

### ISSUE THREAD

**Issue by bsokolovu** [spring-projects/spring-boot#23248]
There is `OriginTrackedYamlLoader` which loads yaml files into a map. When it creates instance of `Yaml` from `snakeyaml` library it passes `LoaderOptions` as parameter. The `LoaderOptions` contains value called `maxAliasesForCollections`.
The value restricts amount of used aliases for non-scalar nodes. Would be nice to make this value configurable.
I've faced the restriction in configuration for feature which has:
* 3 types of components
* each type has 4 ways of acting
* the feature has 12 instances of components

Every combination of type and acting way has part common for all 12 instances. 
Extracting common parts to use anchors implements single source of truth. Splitting such configuration to different files used as workaround in this case but undesirable for common usage.
So please make this parameter configurable.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This has already been addressed by https://github.com/spring-projects/spring-boot/issues/23096.
