### ISSUE TITLE
Add configuration option to customize RSocketServer's fragment size

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-boot#23247]
The documentation is not clear how to set the max frame payload size, all questions are pointing to cloud gateway. Currently we are not using gateway and just using rsocker server.
Thanks

**Comment by rstoyanchev** [comment]
@bclozel yes one option is to increase the WebSocket frame size at the transport level in Reactor Netty. Isn't it also an option to enable fragmentation of large Payload's at the RSocket level via `RSocketServerCustomizer`? That would get the Payload through as well without changing the WebSocket frame size.

**Comment by srinivasvsk** [comment]
Great thank you all
