### ISSUE TITLE
-Dlogging.path=/path/to/log not working on 1.2.1-RELEASE

### ISSUE THREAD

**Issue by avishayh** [spring-projects/spring-boot#2325]
I am running 

```
$ java -Dlogging.path=/path/to/log/ -jar myapp.jar 
```

I am using the default configuration which is logback.

with spring boot 1.2.0.RELEASE it works
after upgrading to 1.2.1-RELEASE , it stopped working and ignores the attribute - the location of the log file returns to the default which is the working dir

**Comment by wilkinsona** [comment]
I'm seeing the exact opposite of the reported behaviour, i.e it's broken on 1.2.0.RELEASE and `spring.log` appears in the working directory, but works as expected on 1.2.1.RELEASE.

@avishayh I tested using our spring-boot-sample-batch application. Can you point me to an app that reproduces the broken behaviour on 1.2.1?

**Comment by wilkinsona** [comment]
In the absence of an app that reproduces the problem on 1.2.1, I'm going to close this. @avishayh please comment if you are successful in reproducing the problem on 1.2.1 and we'll re-open the issue.
