### ISSUE TITLE
Split up adoc files

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23254]
Our adoc files are quite large, it would be nice to split them up a bit.

**Comment by wilkinsona** [comment]
I've split up `spring-boot-features.adoc` so that we can get a feel for what the end result might be like: https://github.com/wilkinsona/spring-boot/tree/gh-23254.

**Comment by wilkinsona** [comment]
Automating the split is hampered a bit by some of our section ids. For example, `boot-features-custom-log-levels` and `boot-features-custom-log-groups` are both nested beneath `boot-features-logging` but this isn't reflected in their IDs. Ideally, they would be named `boot-features-logging-custom-log-levels` and `boot-features-logging-custom-log-groups`. Unfortunately, correcting the IDs to follow our conventions will break existing links to those specific sections.

**Comment by wilkinsona** [comment]
We also have some sections with no ID so they're using Asciidoctor's default which also doesn't match our conventions. The last four sections in 2.1.x's documentation-overview.adoc for example.

**Comment by philwebb** [comment]
We might be able to add multiple anchors. I did that with "External Application Properties" in `spring-boot-features.adoc`.

**Comment by philwebb** [comment]
Looking at the mess with the anchor names, I'm starting to form the opinion that we should just do this on `main`. I suspect that forward merge pain won't be all that hard and it's quite a risk to change the maintenance branches.
