### ISSUE TITLE
Issue when Locale is used in application.properties 

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#2328]
No converter found capable of converting from type java.lang.String to type java.util.Locale]

Can't map directly to Locale type in Configuration classes.

**Comment by snicoll** [comment]
Works for me. Please provide more details.

**Comment by rajjaiswalsaumya** [comment]
application.properties contains 
files.rootDir=/opt/source
files.stateDir=${files.rootDir}/blabla
files.processedDir=${files.rootDir}/blablabla
files.locale=Locale.UK

And in ConfigurationProperties i have 
@ConfigurationProperties(prefix = "files")
public class DirsConfig {
    private String rootDir;
    private String stateDir;
    private String processedDir;
    private Locale locale;
    private Logger logger = LoggerFactory.getLogger(getClass());

   //Getters

  //Setters
}




Using
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.0.RELEASE</version>
    </parent>

All others properties are mapped correctly leaving Locale

**Comment by snicoll** [comment]
Locale.UK is not a string representation of a `Locale`. `en_GB` is.

**Comment by rajjaiswalsaumya** [comment]
Thanks sni, just saw the docs
