### ISSUE TITLE
Add configuration option to configure RabbitConnectionFactory's channelRpcTimeout

### ISSUE THREAD

**Issue by pierre-sion** [spring-projects/spring-boot#23319]
The property `channelRpcTimeout` is currently not configurable in `RabbitAutoConfiguration` via the usual `spring.rabbitmq.channel-rpc-timeout` property.

As a workaround, one have to either:
- provide its own `RabbitConnectionFactoryBean`
- use a `BeanPostProcessor` to invoke `CachingConnectionFactory#getRabbitConnectionFactory()#setChannelRpcTimeout(int)`

**Comment by jkhoward** [comment]
I'm interested in helping with this

**Comment by mbhave** [comment]
Thanks @jkhoward. Let me know if you have any questions!

**Comment by mbhave** [comment]
Closing in favor of PR #23564.
