### ISSUE TITLE
Make it easier to enable colour-coded output using Jansi on Windows

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2331]
With the Jansi library on the classpath, you also need to configure the console appender with `<withJansi>true</withJansi>` to get coloured output on Windows. As far as I can tell, this is harder than it should be as I can't figure out how to import `base.xml` and just enable Jansi output. It would be good if something like this was possible:

```xml
<configuration>
    <property name="WITH_JANSI" value="true" />
    <include resource="org/springframework/boot/logging/logback/base.xml" />	
</configuration>
```

**Comment by philwebb** [comment]
We could probably also detect jansi and configure it automatically in `DefaultLogbackConfiguration`.

**Comment by philwebb** [comment]
I'm not sure that we should do this due the reasons discussed in https://github.com/spring-projects/spring-boot/pull/2799#issuecomment-112943540
