### ISSUE TITLE
Refactor BootstrapRegistry

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23326]
Discussing things with @spencergibb, we need to rework `BootstrapRegistry` so that it meets all of Spring Cloud's needs. Whilst we're at it we should fix the typo in `DefaultBootstrapRegisty`

**Comment by philwebb** [comment]
There's also a package tangle due to `DefaultPropertiesPropertySource`

**Comment by mdeinum** [comment]
Should this really rely on the undertow API? I suspect the javadoc should use the `InstanceSupplier` (which probably got renamed from `InstanceFactory` somewhere).

**Comment by wilkinsona** [comment]
Well spotted, @mdeinum. Thank you. I've corrected that in ea5c6c292333df48e8f7dea1a3497d81ff8af5a2.
