### ISSUE TITLE
Enhancement: Add Java Module in Spring Initializr

### ISSUE THREAD

**Issue by xiaoxiangmoe** [spring-projects/spring-boot#23327]
I create a Spring project by Spring Initializr. But it has no `module-info.java` file.
Can you add a option in Spring Initializr to create spring project with java module support? Thank you very much.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We deliberately limit the configuration options that we offer to those that we believe will be widely used by a broad set of users. From what we've seen, the module path and therefore `module-info.java` are not widely used when writing Spring Boot applications so we don't feel it's worth offering an option to generate it.

**Comment by xiaoxiangmoe** [comment]
@wilkinsona 
> the module path and therefore module-info.java are not widely used when writing Spring Boot applications

Will spring add some official doc for using spring boot with java module? This will increase the usage amount of java module.

**Comment by wilkinsona** [comment]
We don't have any plans to do so. The benefits are minimal so it isn't something that we generally recommend. There also isn't anything Spring Boot-specific about using the module path if you choose to do so.
