### ISSUE TITLE
Jboss-logging does not log trace level with spring-boot

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-boot#2340]
The jboss-logging framework has methods like `tracef()` (for instance look at hibernate's DefaultPersistEventListener:217):

    LOG.tracef(
				"un-scheduling entity deletion [%s]",
				MessageHelper.infoString(
						persister,
						persister.getIdentifier( entity, source ),
						source.getFactory()
				)
		);

This does not get printed in the log, even if I specify the following:
    logging.level.org.hibernate.event.internal.DefaultPersistEventListener=TRACE

**Comment by philwebb** [comment]
Are you using Spring Boot with logback? Do you have an example application we could try?

**Comment by paranoiabla** [comment]
I'm using log4j2 to aggregate all the logs and then redirect it to boot's logback. I do have a sample application and I can show it tomorrow to @snicoll

**Comment by snicoll** [comment]
The interesting piece here is that other logging events are properly emitted (i.e. `INFO` but `TRACE` are not). I vaguely remember that jboss-logging has its own "trace" level historically. Maybe that's related to the issue.

**Comment by carljmosca** [comment]
Are there any hints or comments on this?

**Comment by wilkinsona** [comment]
This works for me with Logback-based logging. With the following in `application.properties`:

```
logging.level.org.hibernate=TRACE
```

I see trace level output from Hibernate, for example:

```
2016-01-28 11:23:23.858 TRACE 3384 --- [           main] o.h.s.i.AbstractServiceRegistryImpl      : Initializing service [role=org.hibernate.engine.transaction.spi.TransactionFactory]
```

@carljmosca  Unfortunately we never, as far as I know, saw the sample from @ptahchiev that illustrated the problem. If you have such a sample, please share it with us and we'll take a look.

**Comment by carljmosca** [comment]
Thank you @wilkinsona 

I was able to get logging output with logback.

org.jboss.logging.provider=logback

I think the first example I found on SO was log4j so that's where I started.  I don't know what may have been keeping that from working.

**Comment by wilkinsona** [comment]
@ptahchiev Do you still have the sample application? Trace level logging written using JBoss Logging is output correctly when either Logback or Log4j2 is used on its own so I would guess that your problem lies somewhere in the aggregation of logs using Log4j2 and the routing of them into Logback. We'll need to see how that is configured if we're going to make any progress on this.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
