### ISSUE TITLE
Add a FailureAnalyzer for ConfigDataLocationNotFoundException

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#23429]
As suggested by @dsyer, we could add a `FailureAnalyzer` for `ConfigDataLocationNotFoundException `.

**Comment by Miehau** [comment]
Hi, mind if I take a look at this one?

**Comment by wilkinsona** [comment]
Thanks for the offer, @Miehau. That'd be great. Please let us know if you have any questions.

**Comment by philwebb** [comment]
Closing in favor of PR #23633

**Comment by Miehau** [comment]
@philwebb is that the right PR linked? I don't quite understand the superseded tag

**Comment by philwebb** [comment]
When someone submits a pull-request for an issue we usually close the issue in favor of the pull-request. We add the `status: superseded` label to indicate that this issue is older than the pull-request that replaced it. So in this case, issue #23429 has been superseded by pull-request #23633.
