### ISSUE TITLE
HttpEncodingAutoConfiguration erroneously adds charset=UTF-8 to JSON responses

### ISSUE THREAD

**Issue by seanmmills** [spring-projects/spring-boot#2342]
Upgrading from 1.1.9 to 1.2.0+ causes REST responses of `application/json` contentType to return charset: `application/json; charset=utf-8` instead of just `application/json`.  This causes client libraries strictly following the RFC 7159 specification to fail.

I found a workaround by disabling the http encoding, however, this may interfere with other areas of the application where the encoding should be set.
```
spring.http.encoding.enabled=false
```

**Comment by snicoll** [comment]
I am not following. RFC 7159 states that there are no optional or required parameters but does not prevent extra parameters to apply. Am I missing something?

**Comment by seanmmills** [comment]
This is not a Spring issue, but rather a client problem.  I found the answer in http://tools.ietf.org/html/rfc2045#section-5:
...Parameters may be required by their defining content type or subtype or they may be optional. MIME implementations must ignore any parameters whose names they do not recognize.

**Comment by espiegel** [comment]
I encountered the same problem as @seanmmills where a controller produces `application/json;charset=UTF-8` instead of `application/json` by default.

Setting the property `spring.http.encoding.enabled=false` doesn't seem to help.

When I downgraded spring boot's version from 1.4.0.RELEASE to 1.3.5.RELEASE it reverted back to `application/json`.

**Comment by bclozel** [comment]
@espiegel Since the issue you're describing is about different versions (and probably a different problem) - could you create a new issue with a way to reproduce your problem?
