### ISSUE TITLE
Drop JDK 14 pipeline

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#23432]
Hi,

as JDK 15 is GA since last week, I was wondering if we should drop the JDK 14 pipeline on 2.4.x and wanted to discuss this before I'm actually doing anything .(Obviously, I'm volunteering to tackle this if we agree on getting rid of it)

Let me know what you think.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Yes please, @dreis2211.

**Comment by dreis2211** [comment]
Can you assign this to me? I will tackle the ticket then - probably on Wednesday.

**Comment by philwebb** [comment]
I ended up doing this as part of merge commit fa81c3742264efa2fb6f6eae17027cfcd95a26ac since it was easier than trying to deal with converting the jdk14 tasks. Thanks anyway for the offer @dreis2211
