### ISSUE TITLE
Provide properties to configure WebFlux's locale and how it's resolved

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#23449]
MVC has `locale` and `locale-resolver` properties that control the locale and how it's resolved (fixed or via the `Accept-Language` header). We should offer the same with WebFlux.

**Comment by wilkinsona** [comment]
This would give us the following properties:

- `spring.mvc.locale`
- `spring.mvc.locale-resolver`
- `spring.webflux.locale`
- `spring.webflux.locale-resolver`

The properties would behave the same with both WebFlux and MVC. We could, perhaps, consider a common property that works with both web stacks. That would align with, for example, `spring.resources.*` that both MVC and WebFlux consume.

**Comment by philwebb** [comment]
We're going to try:

```
spring.web.locale-resolver=fixed
spring.web.locale=en_GB
```

We'll also consider moving `spring.resources.*` under it.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/23917 for the `spring.resources.*` move.

**Comment by wilkinsona** [comment]
This issue is noteworthy due to the deprecation of the `spring.mvc.locale` and `spring.mvc.locale-resolver` properties.
