### ISSUE TITLE
Support CalVer format more explicitly

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#23451]
Some projects have switched from an alphabetical release train scheme to a CalVer format. As we don't know that format, it considers that `2020` is "older" than, say,  `Aluminium-RELEASE`.

It would be nice if `bomr` understands this new  format and only offer (actual) newest releases that match the current policy.

**Comment by wilkinsona** [comment]
We don't need this in 2.3.x as we only started having CalVer dependencies in 2.4
