### ISSUE TITLE
Provide a way to add details in pre-existing HealthIndicators

### ISSUE THREAD

**Issue by wyfrel** [spring-projects/spring-boot#23460]
To help my company monitoring team, I would like to add some details on the datasourceHealthIndicator (eg jdbc connection String).

I think it would be a great enhancement to have a way to add custom details in health.details map on existing HealthIndicators.

**Comment by philwebb** [comment]
Thanks for the suggestion @wyfrel. We discussed this today on our team call and decided that we don't really want to overload health indicators with application information at this point. We think that the `/info` endpoint is best suited for general application information and if custom health information is required then users can create new health indicators directly.
