### ISSUE TITLE
PropertiesLauncher requires spring-core on the classpath

### ISSUE THREAD

**Issue by maxxedev** [spring-projects/spring-boot#23474]
Uber jar created by spring-boot-maven-plugin sometimes requires that the application depends on spring-framework. 

1. [PropertiesLauncher](https://github.com/spring-projects/spring-boot/blame/v2.3.4.RELEASE/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java#L47) imports Assert from spring-framework, and can sometimes fail. 

2. [JarModeLauncher](https://github.com/spring-projects/spring-boot/blob/v2.3.4.RELEASE/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jarmode/JarModeLauncher.java#L21-L22) imports two spring-framework classes, and always fails. This means layered jar cannot be used without spring-framework.

It is perhaps reasonable to assume that spring-boot-maven-plugin is used only in spring-boot apps which should have spring-framework on the classpath. Nonetheless, it'd be nice to eliminate these dependencies so that the plugin can be used for non-spring apps too.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we're happy with `spring-core` being required here. `JarModeLauncher` in particular would add quite a bit of extra complexity without `spring-core` as it uses `SpringFactoriesLoader`.

**Comment by wilkinsona** [comment]
On second thought, let's consider this for `PropertiesLauncher`. It has no dependency on spring-core in 2.1 (and earlier I believe). The use of `Assert` was introduced in [this commit](https://github.com/spring-projects/spring-boot/commit/266d6334b230e61e60f884e2e4ff48f88d6d88b3).

**Comment by philwebb** [comment]
+1 for updating `PropertiesLauncher`. The `JarModeLauncher` was an intentional design decision since we wanted to lean on `spring.factories`.
