### ISSUE TITLE
(2.3.4.RELEASE) (PostgreSql) (PSQLException) A tentativa de conexão falhou.

### ISSUE THREAD

**Issue by jaksonlima** [spring-projects/spring-boot#23491]
org.postgresql.util.PSQLException: A tentativa de conexão falhou.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315) ~[postgresql 42.2.16.jar:42.2.16]

----------------------------------
Alguem esta com esse erro na conexão com postgresql, na versão  (2.3.3.RELEASE), funciona tranquilo se trocar o final para 4 já da erro.

**Comment by wilkinsona** [comment]
It's impossible to say for certain based on an exception message and part of a stacktrace, but I suspect this is a side-effect of the Postgres upgrade. Spring Boot 2.3.4 upgraded to 42.2.16 (from 42.2.14). As such, it is out of Spring Boot control. You could try downgrading to 42.2.14 and see if that resolves the problem. If it does, I would recommend reporting the change in behaviour to the Postgres team. If you believe that Spring Boot is the cause of the problem and you'd like us to spend some time taking another look, then please take the time to explain why you think that's the case and to provide a complete yet minimal sample that reproduces the problem. We can then re-open the issue and take another look.

**Comment by xp-vit** [comment]
Same issue on Azure Postgres.  adding `gssEncMode=disable` to the connection string helps.

**Comment by jaksonlima** [comment]
@xp-vit Did I get to give an example?

**Comment by xp-vit** [comment]
@jaksonlima  in your spring.properties:

`spring.datasource.url=jdbc:postgresql://localhost:5432/testdb?gssEncMode=disable`

**Comment by jaksonlima** [comment]
@xp-vit i use yml, but it works properly thanks.
