### ISSUE TITLE
Spring Boot transaction rollback not working in weblogic

### ISSUE THREAD

**Issue by bingxueyinlian** [spring-projects/spring-boot#23503]
Spring Boot transaction rollback not working  in weblogic(version 12.2.1.3.0 and 14.1.1.0.0)，but it works in tomcat。
Spring Boot Version：2.2.7.RELEASE
Database : Oracle 11g
>https://stackoverflow.com/questions/45328812/weblogic-12c-spring-boot-transaction-rollback-not-working-with-rollbackfor

**Comment by wilkinsona** [comment]
If it works in Tomcat but fails in WebLogic, that would suggest that WebLogic is caused the problem. Please raise this with Oracle.
