### ISSUE TITLE
Welcome pages not mapped when using different servlet path

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2351]
The forward route added by the MVC auto-configuration for welcome pages doesn't include the servlet path. If you add the following to `application.properties`:

```
server.servlet-path=/home/*
```

And have a `static/index.html` you can't hit it from `/home` only `/home/index.html`.

**Comment by mdoninger** [comment]
Is someone from you guys already working on that? If not, i would try to dig deeper and fix it.
