### ISSUE TITLE
Update spring-boot-starter-data-couchbase with new Config

### ISSUE THREAD

**Issue by deniswsrosa** [spring-projects/spring-boot#23516]
New configs should be added to spring-boot-starter-data-couchbase to allow RBAC and Spring Data Couchbase 4, can anyone point me to the right repo so I can start working on a PR?

**Comment by philwebb** [comment]
I'm not sure I totally understand the question I'm afraid. Are looking to add something to Spring Data to support new Couchbase features? If so, they have a repo at https://github.com/spring-projects/spring-data-couchbase.

**Comment by deniswsrosa** [comment]
Hi Phil, Sorry for not asking the question properly. Do you know where this project lives: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-couchbase ? There are some updates that must be made there.

**Comment by snicoll** [comment]
The starter live here but has no feature. Features are in the `spring-boot-autoconfigure` and the [`org.springframework.boot.couchbase` package](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/couchbase).

Can we please take a step back? We still don't know what you're trying to do or what missing feature you're talking about.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
