### ISSUE TITLE
BootJar.getConfigurations() should not be public API

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#23527]
The `getConfigurations()` method was [introduced in this commit](https://github.com/spring-projects/spring-boot/commit/7bc7d86ad4a2aae902f032494f9756012cfe94b6).  It's only used for testing but it's `protected` and is therefore part of the public API. We should deprecate it in favour of `Project.getConfigurations()` so that we can remove it in the future.

Ideally, I'd like to do this in 2.3.x.

**Comment by somayaj** [comment]
Can this be worked?
