### ISSUE TITLE
Log exceptions in message conversion by default

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2353]
I've run into a problem where a library I'm using has objects that don't play nice with Jackson serialization (property getters throw exceptions), and I've been getting 500 errors when trying to return them from an `@ResponseBody` method, but nothing shows up on the console. I suggest changing the log settings so that exceptions that occur when trying to prepare the response output get logged (exceptions earlier in MVC processing are logged).

**Comment by philwebb** [comment]
Possibly relates to #2176

**Comment by snicoll** [comment]
@chrylis is that issue still applicable with a recent boot version?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
