### ISSUE TITLE
Security properties appendix contains spring.session and spring.ldap properties that belong elsewhere

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-boot#23558]
When looking at the documentation for [Common Application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html), at the [Security section](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#security-properties), I also found the properties prefixed by `spring.session`.

In my opinion, the properties related to **Spring Session** would deserve their own section, as they are not really related to security.

What do you think ?

---

I found the merge of these properties is done there : https://github.com/spring-projects/spring-boot/blob/master/buildSrc/src/main/java/org/springframework/boot/build/context/properties/DocumentConfigurationProperties.java#L80

**Comment by vpavic** [comment]
This is a good point.

While it might seem a bit odd a first, these are actually a better fit for the _Server properties_ section, as Spring Session effectively replaces container's default session management facilities. The auto-configuration even consumes the value of `server.servlet.session.timeout` property when configuring Spring Session.

**Comment by ghusta** [comment]
Good suggestion, it could also fit server properties, indeed.

**Comment by Nnadozie** [comment]
I'd like to work on this if it's decided the docs should be updated

**Comment by wilkinsona** [comment]
Thanks, @ghusta. We're going to move the LDAP properties to the Data section and the Session properties to the Web section.
