### ISSUE TITLE
Document that spring-boot-devtools.properties is no longer considered in integration tests

### ISSUE THREAD

**Issue by yyan111** [spring-projects/spring-boot#23581]
Spring-boot version: 2.3.4
It seems this happened since 2.2, there is a stackoverflow post regarding this as well:
https://stackoverflow.com/questions/62409094/springboot-not-resolving-devtools-properties-in-tests

**Comment by yyan111** [comment]
The integration test class was annotated with @SpringBootTest only, no other property configurations added.

**Comment by snicoll** [comment]
Relying on devtools to configure your tests is a bad idea so we've disabled that, see https://github.com/spring-projects/spring-boot/issues/5307. I can see that's not explicitly described in the release notes for 2.2 so we should add something about that.

**Comment by djnautiyal** [comment]
Is it good for first timers? May I take this up?

**Comment by snicoll** [comment]
Thanks for asking. It isn’t as this one is about upgrading the wiki.

**Comment by snicoll** [comment]
I've added a note in the release notes for 2.2
