### ISSUE TITLE
spring-boot-sample-web-ui has some error, can't work

### ISSUE THREAD

**Issue by hrbq** [spring-projects/spring-boot#2362]
Hi, I'm learning how to used spring-boot with spring mvc + thymeleaf. I've download project run in my local, then some thing just heppened with this "There was an unexpected error (type=Internal Server Error, status=500).Failed to convert value of type 'java.lang.String' to required type com.iisi.scs.domain.People'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [com.iisi.scs.domain.People]: no matching editors or conversion strategy found"

And I figure out the solution to fix it. Just change the sample.ui.mvc.MessageController.view()'s parameter to String, and every thing good.

**Comment by wilkinsona** [comment]
Why do you think that this is a problem with the sample? The class `com.iisi.scs.domain.People` isn't part of the sample and changing the view method's parameter to a `String` will break the automatic conversion of the message id into a `Message` instance.

If I have misunderstood, please comment with some more details on why you think the sample is broken and we can take another look.

**Comment by fangwd** [comment]
As of the current version (1.3.0.BUILD-SNAPSHOT), it still does not work. The only request mapping that works as expected is "foo", which throws "Expected exception in controller". Not sure if any body else has successfully run it.

**Comment by snicoll** [comment]
I just ran it from the IDE and it worked for me. But I had a weird `spring-loaded` related issue on the command line (I've created #3800).

This issue is closed anyway (and I just confirmed it was working) so if you're still experiencing some issue, create a new issue and provide the steps you used to reproduce.

**Comment by fangwd** [comment]
Sorry yes it did work. The reason it did not work for me before was I ran it "standalone" (outside of spring-boot directory). Changing the pom.xml to use the release version fixed the problem.

Nice work spring boot!
