### ISSUE TITLE
Document that a  reactive transaction manager is not auto-configured with Spring Data Neo4j

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#23629]
I am trying to update [the former SDN Rx example project](https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-neo4j-rx) to [the latest Spring Boot 2.4](https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-neo4j)(SDN RX is merged right ?).

The first problem is I have to configure a `ReactiveTransactionManager` to make it run.

```java
	@Bean
	public ReactiveTransactionManager reactiveTransactionManager(Driver driver) {
		return  new ReactiveNeo4jTransactionManager(driver);
	}
```

I am not sure why we have to configure a transaction manager for Neo4j.

If it is a must in the new infrastructure, it should be autoconfigured.

**Comment by snicoll** [comment]
@hantsy please read the release notes before opening an issue. 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4.0-M2-Release-Notes#neo4j-1

**Comment by snicoll** [comment]
Let's reuse this issue to add a note in the reference guide as what we thought was temporary is likely to stay in the 2.4.x line at least.

**Comment by hantsy** [comment]
@snicoll Thanks for providing the link, it clarified my confusion.
But now `TransactionManager` became a must, in the pre versions, I remember it was optional.

**Comment by snicoll** [comment]
I can't comment on whatever has been done outside of Spring Boot. Please reach out to the Spring Data Neo4j team.
