### ISSUE TITLE
Postgresql 42.2.16 #23297 - Not working on SSL Connections to e.g. Azure or AWS Databases

### ISSUE THREAD

**Issue by flaxoiu** [spring-projects/spring-boot#23624]
Postgres JDBC-Driver 42.2.16 is not working corretly with enabled ssl connection.

org.postgresql.util.PSQLException: The connection attempt failed. at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315) at 

https://github.com/pgjdbc/pgjdbc/issues/1868

Integration of a working Postgres JDBC-Driver would be great if ssl is enabled on db connection 

Maybe fixed in 42.2.17. With Version 42.2.14 its still working.

**Comment by wilkinsona** [comment]
Duplicates #23491 and #23523. We'll upgrade to a new version of Postgres's driver that contains the fix in due course.
