### ISSUE TITLE
Unsupported option defined for thread pattern in defaults.xml CONSOLE_LOG_PATTERN

### ISSUE THREAD

**Issue by apogrebnyak** [spring-projects/spring-boot#2366]
The file in question is https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml

In `CONSOLE_LOG_PATTERN`, the thread pattern is defined as `%15.15t{14}`
According to [logback documentation](http://logback.qos.ch/manual/layouts.html#relative) (and code), `t/thread` conversion word does not support any additional options.

For clarity, can you remove it, and leave just the field formatting options in-place, as `%15.15t`?

**Comment by wilkinsona** [comment]
`basic.xml` in 1.1.x has the same problem
