### ISSUE TITLE
Jetty SecureRequestCustomizer should be added to SslConnectionFactory

### ISSUE THREAD

**Issue by lazpk9uu** [spring-projects/spring-boot#2368]
Inside JettyEmbeddedServletContainerFactory.Jetty9SslServerConnectorFactory, the HttpConnectionFactory should add a SecureRequestCustomizer by default.  This ensures that the Request objects later created have a scheme of "https" instead of "http" when an SSL request is made.

This becomes important when using Spring Security, which redirects to a URL created by detecting the scheme from the request. (See LoginUrlAuthenticationEntryPoint#buildRedirectUrlToLoginPage in spring-security-web).

As a workaround, a developer can add SecureRequestCustomizer to the server after creation by doing something along these lines:

    Connector[] connectors = server.getConnectors();
    for (Connector c : connectors)
    {
        for (ConnectionFactory f : c.getConnectionFactories())
        {
            if (f instanceof HttpConnectionFactory)
            {
                HttpConfiguration config = ((HttpConfiguration.ConnectionFactory) f).getHttpConfiguration();
                config.addCustomizer(new SecureRequestCustomizer());
            }
        }
    }

**Comment by wilkinsona** [comment]
Duplicates #2232
