### ISSUE TITLE
LiveReload doesn't work without restart enabled

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#23726]
Using `spring.devtools.restart.enabled=false` disables livereload even if `spring.devtools.livereload.enabled=true` .
Browser connects successfully to LiveReload, but changing files does not trigger reload.

Spring Boot 2.3.3.RELEASE

**Comment by philwebb** [comment]
This is expected, the live reload feature need something to trigger it and means that restart needs to be enabled.

**Comment by cdalexndr** [comment]
A warning should be added to [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-devtools-livereload)

**Comment by wilkinsona** [comment]
We'd be happy to review a pull request if you'd like to propose something, @cdalexndr.

**Comment by cdalexndr** [comment]
What project contains spring boot documentation? Is there any guide to update documentation?

**Comment by wilkinsona** [comment]
The reference documentation is all in this repository in the `spring-boot-docs` project. You can find the source for the existing docs on LiveReload here: https://github.com/spring-projects/spring-boot/blob/3f1f830efee820d04460ce6a5ca88d3f130f3b5d/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using-spring-boot.adoc#livereload. GitHub's built-in editor for Asciidoc source is quite good so you may want to use the Edit button. (top-right of the page) to edit the documentation in your browser. Alternatively, you can clone the code and change it in an editor of your choice on your machine.
