### ISSUE TITLE
LogbackLoggingSystem installs FILTER TurboFilter that prevents logging from PropertySourcesPropertyResolver

### ISSUE THREAD

**Issue by apogrebnyak** [spring-projects/spring-boot#2374]
`PropertySourcesPropertyResolver.FILTER` always returns `FilterReply.DENY`.

Because of this, all logging from `org.springframework.core.env.PropertySourcesPropertyResolver` is disabled after the filter is installed in the initial logging context.

It makes pretty hard to debug property resolution issues.

**Comment by wilkinsona** [comment]
Which version of Boot were you using? It works fine for me with both 1.1.10.RELEASE and 1.2.1.RELEASE.

Note that the filter is only installed temporarily. It's added in `beforeInitialize` and then removed again in `initialize`.

**Comment by apogrebnyak** [comment]
It does not log at all for some period of time starting at `SpringApplication.configureProfiles`, and until some event in `runListener.environmentPrepared`.

I;ve added this line to my logback configuration:
```
  <logger name="org.springframework.core.env.PropertySourcesPropertyResolver" level="TRACE"/>
```

and added conditional breakpoint on `debugEnabled==false` in `PropertySourcesPropertyResolver.getProperty` on line 75.  It does hit it during the early initialization phase.

Notice, that logging is disabled on all levels during this phase because the turbo filter denies it unconditionally.

I don't know if logging from other subsystems is disabled during this phase as well.

**Comment by wilkinsona** [comment]
It's by design. The filter's used to suppress logging output while the logging system is being configured. The logging system can't be configured until the environment has been prepared as the environment can be used to configure logging.

Do you have an example of the property resolution that you were trying to debug for which no logging was generated?

**Comment by apogrebnyak** [comment]
If it's by design, I understand.

I was able to resolve my original problem.  It had to do with my custom `Converter` choking on a `server.port=-1`.  I was trying to see, who defines `server.port=-1` for integration tests.  Found it in `SpringApplicationContextLoader.getDefaultEnvironmentProperties`.

Closing it.
