### ISSUE TITLE
HttpEncodingAutoConfiguration is not added to the WebMvcTest slice

### ISSUE THREAD

**Issue by rob-valor** [spring-projects/spring-boot#23749]
**Affects:** 5.4.3

`HttpEncodingAutoConfiguration` is not added to the `WebMvcTest` slice. Not sure if this is intentional but when running with _full_ auto-configuration this configuration is loaded in the application context. When starting a test application context with `@WebMvcTest` the `CharacterEncodingFilter` provided by the `HttpEncodingAutoConfiguration` is not added which makes http request processing different in those tests compared to `@SpringBootTest` or production application context. By default that filter makes request character encoding always UTF-8. see ([filter config](https://github.com/spring-projects/spring-boot/blob/3657c6c85de0bd49529d2dc256dd4350b61ad7c1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/HttpEncodingAutoConfiguration.java#L60) with default [utf-8](https://github.com/spring-projects/spring-boot/blob/3657c6c85de0bd49529d2dc256dd4350b61ad7c1/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/server/Encoding.java#L43) being [forced for requests](https://github.com/spring-projects/spring-boot/blob/3657c6c85de0bd49529d2dc256dd4350b61ad7c1/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/server/Encoding.java#L113))

This is triggered by spring-projects/spring-framework#22788. That made us use `MediaType.APPLICATION_JSON` (without the character encoding) for the requests during `WebMvcTest`s.

**Comment by bclozel** [comment]
Indeed, the `WebMvcTypeExcludeFilter` includes `FilterRegistrationBean` but not the `HttpEncodingAutoConfiguration`, which configures the `CharacterEncodingFilter` if the configuration property is set.
