### ISSUE TITLE
Upgrade to MSSQL JDBC 8.4.1.jre8

### ISSUE THREAD

**Issue by boukewoudstra** [spring-projects/spring-boot#23742]
It seems that the latest stable release supports the same SQL server databases as current version 7.4.1.jre8 does. Therefore it should be considered to be a safe upgrade. It has several performance fixes and lots of bugfixes as well.

The compatibility table can be found here:
https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-2017#sql-version-compatibility

See also https://github.com/spring-projects/spring-boot/issues/17965 for a previous upgrade.

Thanks in advance for considering the upgrade.

**Comment by wilkinsona** [comment]
I think an upgrade makes sense in this instance as well. The release notes don't list any breaking changes and, as you say, the SQL Server compatibility is unchanged. Thanks for the suggestion.
