### ISSUE TITLE
Upgrade to Lombok 1.18.16

### ISSUE THREAD

**Issue by mdiskin** [spring-projects/spring-boot#23748]
#23659 Don't use this version. It is broken. Changes are listed under 1.18.16
https://github.com/rzwitserloot/lombok/releases/tag/v1.18.14

**Comment by snicoll** [comment]
@mdiskin as noted in the issue template, there's no need to create an issue for upgrading a dependency, we'll do that in due course.

**Comment by mdiskin** [comment]
No worries I initially added it to the prior issue upgrade when I say lombok team re-released that shipped version.
