### ISSUE TITLE
Upgrade maven plugin to maven archiver 2.6

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#2376]
The current spring-boot-maven-plugin 1.2.0.RELEASE depends on maven-archiver 2.5. However, this gives me issues when I can only connect to my internal nexus and not the full internet. I get this:
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.0.RELEASE:repackage (default) on project datasheets-app: 
Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.0.RELEASE:repackage failed: 
Plugin org.springframework.boot:spring-boot-maven-plugin:1.2.0.RELEASE or one of its dependencies could not be resolved: 
Failed to collect dependencies at org.springframework.boot:spring-boot-maven-plugin:jar:1.2.0.RELEASE -> 
org.apache.maven:maven-archiver:jar:2.5 -> 
org.apache.maven:maven-core:jar:3.1.1 -> 
org.apache.maven:maven-plugin-api:jar:3.1.1 -> 
org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5 -> 
javax.enterprise:cdi-api:jar:1.0: Failed to read artifact descriptor for javax.enterprise:cdi-api:jar:1.0: 
Could not find artifact org.jboss.weld:weld-api-parent:pom:1.0 in nexus 
```

It works when I update my pom with the following:
```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-archiver</artifactId>
      <version>2.6</version>
    </dependency>
  </dependencies>
</plugin>
```
I guess it has something to do with https://issues.jboss.org/browse/WELD-948

**Comment by snicoll** [comment]
That looks weird to me. That's the first time I hear this issue and I can't find any trace of such problem with maven archiver 2.5.

I'd prefer to better understand the problem instead of "simply" upgrading. Can you share a project that reproduces the issue?

**Comment by wimdeblauwe** [comment]
Hi,

Did you read the jira issue from the boss project? It seems they had their
repo hard coded in their pom.

Regards,

Wim

Op zaterdag 17 januari 2015 heeft Stéphane Nicoll <notifications@github.com>
het volgende geschreven:

**Comment by snicoll** [comment]
Yes, I did and to me it's unrelated for the simple reason that `maven-archiver` has no dependency on any of the JBoss artifacts. It should be something else in your project that is triggering it.

At this point, I am afraid I am not able to help much further unless you provide a sample project that exhibits a problem in Spring Boot.

**Comment by wimdeblauwe** [comment]
ok. In my project, I only had to update that dependency to make it work
strangely enough. Anyway, I have a workaround for now.

2015-01-19 9:46 GMT+01:00 Stéphane Nicoll <notifications@github.com>:

**Comment by snicoll** [comment]
There's something else in your project that triggers it. Your dependency:tree shows `org.eclipse.sisu.plexus:jar:0.0.0.M5 ` and that's the one that brings CDI. You should have another dependency that uses that faulty dependency you referred to  and Maven is wrongly using it. 

all this is hardly related to Spring Boot. That being said, if that fixes the issue for you, we can at least consider upgrading our dependency as 2.5 is almost 3 years old now

**Comment by wimdeblauwe** [comment]
I just ran:

`mvn dependency:tree | grep eclipse`

But it did not return anything.

**Comment by snicoll** [comment]
That's for the project dependencies not the plugins dependencies. Anyways, without a project I am just guessing here and that's not very interesting.
