### ISSUE TITLE
springboot undertown Large file uploads can also cause downtime

### ISSUE THREAD

**Issue by dngzs** [spring-projects/spring-boot#23796]
springoot undertow 2.0.0
Large file uploads can also cause downtime，Below is the code of springmvc
```
   @GetMapping("/hello")
    public void hello(HttpServletResponse response) throws IOException {
        String path="C:\\Users\\bg317957\\Desktop\\1.mp4";
        FileInputStream fileInputStream=new FileInputStream(path);
        response.setContentType("video/mp4");
        Streams.copy(fileInputStream,response.getOutputStream(),true);
    }

```

![1](https://user-images.githubusercontent.com/18388958/96719108-8da37f00-13db-11eb-8368-54361ddb324e.png)

**Comment by philwebb** [comment]
I'm afraid I don't totally understand the issue that's being reported here but it doesn't look like Spring Boot is involved.

You'll need to probably raise this with either the Undertow or Spring Framework team. Before you do that, I suggest you spend a bit of time creating a sample application that shows the exact nature of the problem. It's going to be very hard to tell if this is a bug or not from the limited details that you've provided here.
