### ISSUE TITLE
Enhancement to AbstractHealthIndicator Log Level

### ISSUE THREAD

**Issue by fdevilish84** [spring-projects/spring-boot#23804]
Hi

If database healt check fails due to broken db connection for instance, we get only Warn on log.  Due to broken connection whole application may stall / stop working. If database connection doesn't work, maybe it should be indicated using error level message ?

Warn level seems to be defined in: 
```
	@Override
	public final Health health() {
		Health.Builder builder = new Health.Builder();
		try {
			doHealthCheck(builder);
		}
		catch (Exception ex) {
			if (this.logger.isWarnEnabled()) {
				String message = this.healthCheckFailedMessage.apply(ex);
				this.logger.warn(StringUtils.hasText(message) ? message : DEFAULT_MESSAGE, ex);
			}
			builder.down(ex);
		}
		return builder.build();
	}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I think that `warn` is the right level here. The health check failure may only be a temporary problem, due to a network glitch for example. I don't think an error-level message is appropriate for such a temporary problem.
