### ISSUE TITLE
SpringBoot 中文文档的13.2 Maven部分的第三个case中Spring被翻译为了春天，应该是Spring

### ISSUE THREAD

**Issue by wanderlustlee** [spring-projects/spring-boot#23803]

**Comment by bclozel** [comment]
Using an automated translation tool:

> In the third case of the 13.2 Maven section of the SpringBoot Chinese document, Spring is translated as Spring, which should be Spring

Hello @wanderlustlee , the team doesn't maintain a chinese translation of our documentation. Maybe you meant to submit this issue to another website? Could you point us to the URL of that documentation?

Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lilaboc** [comment]
I guess it's here https://www.springcloud.cc/spring-boot.html#using-boot-maven 

which has nothing to do with here, spring was translated to spring (the season) in Chinese

I guess issue can be closed
