### ISSUE TITLE
Jar entries are duplicated in BOOT-INF/lib with layered jars and Maven

### ISSUE THREAD

**Issue by Ahli** [spring-projects/spring-boot#23801]
In my project, a generated executable jar contains every jar within the BOOT-INF/lib directory twice with identical file names. This pretty much doubles the size of the final jar.

The issue is not present in 2.4.0-M1 of the Maven-Plugin.
The issue is present since 2.4.0-M2. So, M4 still contains it.

The produced executable jar is functional. Just the file size is doubled.

My library usage:
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>2.4.0-M4</version> <!-- M2-M4 add lib jars twice; M1 is fine -->
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
            <configuration>
                <!--<finalName>${jarName}</finalName>-->
                <layout>JAR</layout>
                <classifier>spring-boot</classifier>
                <mainClass>${mainClass}</mainClass>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by philwebb** [comment]
I'm having trouble replicating this issue. Could you please share a sample project that shows the problem?

**Comment by Ahli** [comment]
Project where I encounter this issue: https://github.com/Ahli/Galaxy-Observer-UI/tree/master/tools/interfaceBuilder

I will try and reduce this to a small standalone project demonstrating the issue.

**Comment by philwebb** [comment]
I'm manged to build that project after running `mvn install -DskipTests` I don't see any duplicates. Running `unzip -l target/compile.jar | sort | uniq -c` shows a count of `1` for all jars.

Is there any trick to getting the duplicate entries? What operating system are you using?

**Comment by Ahli** [comment]
My environment: Win 10 20H2, JDK 15, Maven 3.5.3, IntelliJ IDEA 2020.3EAP

Here are the jars generated for me (placed in a single zip): https://www.dropbox.com/s/vz1gj1brakt33pr/spring_issue23801.zip?dl=1

**Comment by philwebb** [comment]
I think I see the duplicates. They're in `compile-spring-boot.jar` not `compile.jar`.

**Comment by philwebb** [comment]
A standard project from start.spring.io with the following plugin config replicates it:

```xml
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
						  <classifier>spring-boot</classifier>
					  </configuration>
					</execution>
			  </executions>
			</plugin>
		</plugins>
	</build>
```

**Comment by Ahli** [comment]
The issue is not present when layering is disabled.

```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>2.4.0-M4</version>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
            <configuration>
                <layers>
                    <enabled>false</enabled> <!-- prevents duplicated jars in BOOT-INF/lib/ in 2.4.0-M2 to M4 -->
                </layers>
                <layout>JAR</layout>
                <classifier>spring-boot</classifier>
                <mainClass>${mainClass}</mainClass>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Layering was enabled by default between M1 and M2 (between 29th June and 14 August 2020).

**Commit History**: https://github.com/spring-projects/spring-boot/commits/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven
**Commit that enabled layering by default**: https://github.com/spring-projects/spring-boot/commit/41f5ba9077f01b16a3c6fd0b543ddbac566f7e2f#diff-9621a7691c90b1bf3c0b6cdebd10f29dbd8a3fd27aef00b8357b44725ed90804

**Comment by wilkinsona** [comment]
All of the launcher classes are also packaged twice. Once beneath `/` and once beneath `/BOOT-INF/classes/`.

**Comment by wilkinsona** [comment]
The launcher class are also duplicated in 2.3.4, however the contents of `BOOT-INF/lib` is not.
