### ISSUE TITLE
Notify the use of logback specific system property

### ISSUE THREAD

**Issue by stepancheg** [spring-projects/spring-boot#2382]
[Logging manual](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html) needs an explatation how to disable logger configuration.

Problem is that you set `-Dlogback.configurationFile=...` as specified in logback manual, and then spend an hour in debugger trying to understand how to disable spring-boot override of that configuration.

Spring-boot defaults are cool, but should be easy to turn off.

**Comment by sartan** [comment]
If anyone else is trying to figure out how to specify a non-standard logback filename, this worked for me:
-Dlogging.config=

**Comment by stepancheg** [comment]
@sartan this seems not to be true: setting `logging.config` to empty strings makes spring-boot to reinitialize logger with defaults.

```
        String logConfig = environment.getProperty(CONFIG_PROPERTY);
        if (ignoreLogConfig(logConfig)) {
            system.initialize(initializationContext, null, logFile);
        }
        else {
            try {
                ResourceUtils.getURL(logConfig).openStream().close();
                system.initialize(initializationContext, logConfig, logFile);
            }
            catch (Exception ex) {
                // NOTE: We can't use the logger here to report the problem
                System.err.println("Logging system failed to initialize "
                        + "using configuration from '" + logConfig + "'");
                ex.printStackTrace(System.err);
                throw new IllegalStateException(ex);
            }
        }
```

There's not way to tell spring boot not to initialize logger.

**Comment by stepancheg** [comment]
OK, I've found a way to disable logger reconfiguration. You need a class like [NopLoggingSystem](https://gist.github.com/stepancheg/4746ede5b48ba4396760), and use it like that:

```
System.setProperty(LoggingSystem.SYSTEM_PROPERTY, NopLoggingSystem.class.getName());
```

**Comment by sartan** [comment]
@stepancheg Sorry, I don't think I was clear. I was saying that -Dlogging.config=[filename] I was able to specify a non-standard logback file, thus overriding Boot's default behavior.
