### ISSUE TITLE
Log4j2

### ISSUE THREAD

**Issue by hooligan495** [spring-projects/spring-boot#2384]
I've a springboot application using log4j2 as logging.  using the 1.2 milestone 2.  A gradle run shows log messages on teh console.  Upgrading to 1.2.1  release (or 1.2.0).

All my console log messages spit out as:

${LOG_PATTERN}  

When I deploy my war file to tomcat the log messages work properly.  Is there a configuration thing I am missing?

**Comment by wilkinsona** [comment]
Can you share some configuration that reproduces the problem?

Using this build.gradle:

```groovy
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.2.1.RELEASE'
	}
}

apply plugin: 'spring-boot'

repositories {
	jcenter()
}

configurations {
	all {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}
}

dependencies {
	compile 'org.springframework.boot:spring-boot-starter-actuator'
	compile 'org.springframework.boot:spring-boot-starter-web'
	compile 'org.springframework.boot:spring-boot-starter-log4j2'
	testCompile 'org.springframework.boot:spring-boot-starter-test'
}
```
the [Actuator Log4J 2 sample](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-actuator-log4j2) produces sensible logging output when run with `gradle bootRun`.

**Comment by hooligan495** [comment]
I will, perhaps it's better for me to start with your gradle file and the actuator log4J 2 project above and start adding my dependencies and see if one of them surfaces the issue in this project.  That way if it truly is something I've done then I won't make you debug it :)

**Comment by wilkinsona** [comment]
@hooligan495 I like the sound of having less debugging to do. Thanks.

**Comment by hooligan495** [comment]
Sorry for the long time on this.  Here's what I found:

It was my log4j.xml file.

This gist shows what I had and what I changed to fix it.
https://gist.github.com/hooligan495/c321f98f6c8f5338f726

So at the end of the day... I'm not sure this is a spring boot issue.  Or some way that I configured something else.  I'll keep trying to look into it.

**Comment by wilkinsona** [comment]
That gist doesn't make much sense to me. There's no reason why using a `LOG_PATTERN` property shouldn't work – the Actuator Log4J 2 sample does just that and works fine. I've tried the sample with the `Properties` and `Appenders` configuration from your gist and that works fine too.

I'm going to close this one. If you find anything that points towards this being a problem with Spring Boot, please comment again and we'll re-open the issue.
