### ISSUE TITLE
Provide Documentation/Guidance on Deploying Boot Applications to Production

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#2385]
The current Spring Boot documentation does provide documentation on using Spring Boot behind a proxy and how to enable SSL. However, it could be improved to include:
- How to setup load balancing. Some documentation and a config example on how to use nginx might be useful for this.
- How to support clustered environments (i.e. Sessions)

Related https://github.com/spring-projects/spring-boot/issues/1117 https://github.com/spring-projects/spring-boot/pull/2071

**Comment by sloppycoder** [comment]
I'm working on these 2 topics. so far I have got clustering to work with spring-session with last code on master, but still having trouble with nginix SSL proxy setup.

Please provide some guideline and I'd like to contribute.

**Comment by philwebb** [comment]
The session information would be useful but I don't think we should include `nginx` details in the core reference guide. A stand-alone guide on spring.io would be very welcome though.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
