### ISSUE TITLE
Spring Boot can't be checked out on Windows without enabling git core.longpaths

### ISSUE THREAD

**Issue by kedar-joshi** [spring-projects/spring-boot#23864]
Currently Spring Boot project can't be checked out on Windows due to `Filename too long` error. Commit d1f543fc added a file `spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/tasks/buildinfo/BuildInfoIntegrationTests-notUpToDateWhenExecutedTwiceWithFixedTimeAndChangedGradlePropertiesProjectVersion.gradle` which requires Git `core.longpaths` to be set to `true`.

**Comment by snicoll** [comment]
Thanks but we are aware of that and it is [also documented in CONTRIBUTING.md](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows).

**Comment by wilkinsona** [comment]
Thanks, but [as shown by the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/e0f123e6761547f8326d37ec1ae54972bf23a90c/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows), we're already aware of this. You should enable core.longpaths if you're on Windows.
