### ISSUE TITLE
Extra dot in keys only supported for CharSequence

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2387]
@kdvolder and I brainstormed yesterday (#2054) to give proper semantic demarcation to properties binding and we found this issue. Consider the following examples, assuming a `config` prefix and a  `Map` of `String` to _something_ with name `content`:

If the value is `String` the following configuration creates two entries with key `foo` and `bar.key`
```
config.content.foo=4
config.content.bar.key=2
```

Now if the **value** of the map is integer, the exact same configuration throws an exception because the binder tries to "auto-grow" an integer for the key `bar` and can't obviously. 

Why does the **value** of the map triggers this special handling for keys having dots? Shouldn't that be the type of the key since I assume we can safely disable key navigation since the type is _immutable_.

The current fuziness of the binding is also a severe issue for IDE support  that are trying to assist the user with what they can or cannot do. The basic behaviour is that a dot is a request to navigate. What happens when there is a dot in the intermediate element? Ideally this should only happen for maps and forcing the user to use the bracket notation would be a good way of harmonizing the current support (after fixing #2386 ). 

But there is this special case for Map of String... I think IDE support would be much easier if the rule would be:

* Each dot is a request to navigate to another element
* If the element has a dot in it, you should use the bracket notation

Thoughts?

(that's obviously breaking for `logging.level.*` and others probably but if we have to handle a special case, we should probably define it and stick to it.

**Comment by kdvolder** [comment]
Just adding some thoughts (I think also came out of our discussion)...

A 'rule' that makes sense to me is that two cases are distinguished based
on the 'domain type' of a map.

For this we need the concept of 'navigable type'. A navigable type is one
where it is meaningful to access properties to navigate into 'sub objects'.
Not sure yet how this can unambigously decided for all cases. But at least
there are some cases for which it is obvious they are not 'navigable'
(Integer, String, etc).

Let's say we have a property definition "foo.some.extra.stuff=..."

And 'foo' is bound to a Map<?,DomainType>

Two cases are:

  1) domain type is 'navigable'
     => the key is only taken as the portion upto next dot, the next dot is
taken as 'navigation' into the values in the map.
     i.e. the key is 'some' and 'extra.stuff' navigates deeper into the
values in the map.

  2) domain type is not 'navigable'
    => the dots in the remainder of the key can't sensibly be interpreted
as 'navigation' so it is somewhat logical they are just treated as any
other character.
    => the key in the example is 'some.extra.stuff'

I think this 'rule' is compatible with the way 'logging.level.' currently
works, assuming that the 'domainType' of that property is something like
'String' or 'Enum' which are not 'navigable'.

Also I think it would be compatible with the idea that 'nested maps' can be
navigated with '.' in the key, if we assume that nested maps are specified
as

Map<?,Object>

and we say that 'Object' is considered a navigable type.

**Comment by kdvolder** [comment]
PS: Don't make too big a point about 'tool support would be easier if...'.
Rather, I think it is important that there are some sensible rules on how
to interpret a property assignment string, so that anybody (tool or person)
who knows the rules actually knows what it means when they read or write a
property assignment.

So discussion and decisions should be framed in terms of whether the
'rules' are well-defined and logical, rather than whether they are 'good
for tool support'.

**Comment by kdvolder** [comment]
The easiest and, to me, most logical 'rule' would be that the '.' (on the left side of the '=') are always interpreted in the same way. I.e. they always mean 'navigate into'. Thus, if one wished to have a '.' in a map's key, then one would need to escape it somehow. The '[]' notation could work as an 'escape' mechanism to avoid breaking a 'dotted key' apart (if only it worked as expected: see https://mail.google.com/mail/u/0/?shva=1#inbox/14b0b76079a8d8eb).

Personally I would prefer this 'simple' rule. But it is not compatible with existing notation of things like 'logging.level'. As one would have to write:

      logging.level[com.acme]=...

instead of

      logging.level.com.acme=...

Personally, I think the first way of writing it is actually 'nicer' as its clearer to me what it means.

**Comment by philwebb** [comment]
I wonder how many existing users currently have the `logging.level.com.acme` format. I don't particularly want to break any existing applications. We also need to consider how YAML configuration files will look if we require the `[...]` notation.

In terms of navigability, could we only provide ctrl+click links for the `logging.level` part? We probably have to deal with something similar already for nested properties. e.g. `server.tomcat.port-header` could offer 3 links depending on where you click:

```
server.tomcat.port-header=ServerProperties$Tomcat.portHeader
server.tomcat=ServerProperties$Tomcat
server=ServerProperties
```

**Comment by snicoll** [comment]
I just discussed this with @dsyer and our special case should apply to dedicated immutable types and on the key (not the value) so we're definitively having a bug here. I think it's fine if we fix the inconsistency and document it (i.e. only support "dot keys" for String and primitive wrappers or something). We should also fix the bracket notation not to navigate. I'll work on that and propose a PR that you guys can review.

@philwebb regarding your last question, I believe IJ only support one link and I think it would be _very_ confusing if the same area would gave you a different link depending where you click. The current behaviour is fine by me.

**Comment by kdvolder** [comment]
> I believe IJ only support one link and I think it would be *very*
confusing if the same area would gave you a different link depending where
you click.

Same for the stuff I implemented for Eclipse. Still, it might make sense to
refine this however, as Phill suggests.

> ... *very* confusing if the same area would gave you a different link
depending where you click

Right but maybe the link areas in that case are not the whole property
names, but just the individual 'segments'.
