### ISSUE TITLE
Apply Jackson configuration to ObjectMapper used by EndpointMBean

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2393]
Every `EndpointMBean` that's created (11 in the case I've just been looking at) creates its own `ObjectMapper` that's then used in its default configuration. It would be nice to be able to configure the JSON output produced by the endpoints using `spring.jackson.*` configuration or using a custom `Jackson2ObjectMapperBuilder` bean that the user's configured in the application context.

A pleasant side-effect of this change could be to get all of the `EndpointMBean`'s to share an `ObjectMapper`, thereby reducing their heap footprint.

**Comment by cemo** [comment]
+1
