### ISSUE TITLE
Provide dependency management for jOOQ's new jooq-kotlin module

### ISSUE THREAD

**Issue by XhstormR** [spring-projects/spring-boot#23964]
I found that the JOOQ group in the dependency management does not contain the newly released jooq-kotlin module.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/build.gradle#L832

https://github.com/jOOQ/jOOQ/tree/main/jOOQ-kotlin

**Comment by wilkinsona** [comment]
Thanks. I missed that new module in https://github.com/spring-projects/spring-boot/issues/23894.
