### ISSUE TITLE
The number of TCP connections still increase after update spring boot version unless restart spring gateway.

### ISSUE THREAD

**Issue by hcl78184889** [spring-projects/spring-boot#23967]
spring boot 2.3.3
spring cloud Hoxton.SR7
 
Refer to below :

![tcp connections](https://user-images.githubusercontent.com/6574953/97594087-46516a00-1a3d-11eb-85b8-4fcd0f860c73.png)

Source code:
[gateway.zip](https://github.com/spring-projects/spring-boot/files/5459578/gateway.zip)

**Comment by hcl78184889** [comment]
refer to before issue：

https://github.com/spring-projects/spring-boot/issues/22245#issue-652170800

**Comment by wilkinsona** [comment]
Thanks for the report. Given the similarity to #22245, I suspect this one is a Reactor Netty issue as well. Can you please raise an issue there? If the problem turns out to be due to how Spring Boot is configuring Reactor Netty, we can re-open this issue.

**Comment by hcl78184889** [comment]
OK, thanks
