### ISSUE TITLE
Update GVM publish script to deal with new version scheme

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23975]

**Comment by snicoll** [comment]
I've submitted a PR for that in the relevant project so I believe this issue is now superseded by https://github.com/philwebb/spring-boot-gvm-publish/pull/5

**Comment by philwebb** [comment]
Reopening to remind us to change the `version.startsWith("2.3.")` line

**Comment by snicoll** [comment]
I've created a PR we can merge right before releasing `2.4.0`, see https://github.com/philwebb/spring-boot-gvm-publish/pull/6

**Comment by wilkinsona** [comment]
I've merged @snicoll's GVM publish PR so I think we're good here.

**Comment by snicoll** [comment]
I haven’t used the script for 2.3.6 but I guess that’s ok with 2.4.0 coming up the same day.
