### ISSUE TITLE
Ensure starter javadoc and source jars have different checksums

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23974]
We should try to add something to the zips to ensure they get a unique digest.

**Comment by philwebb** [comment]
Perhaps we can add the gradle file

**Comment by wilkinsona** [comment]
How about making different customisations to the manifest for sources and javadoc jars? We currently apply the same customisations to them as we apply to the main jar artifact which I'm not sure makes a whole lot of sense. How about something like [this](https://github.com/wilkinsona/spring-boot/tree/gh-23974)? It changes the implementation title to reflect the nature of the jar.
