### ISSUE TITLE
App fails to start when deployed to Tomcat if it uses a DataSource retrieved from JNDI and JMX auto-configuration is enabled

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2397]
http://stackoverflow.com/questions/28063430/spring-boot-1-2-1-release-and-jndi-errors

Tomcat exposes an MBean for the DataSource and Boot's JMX export tries to create an MBean with the same name. Setting `spring.jmx.enabled: false` works around the problem.

**Comment by bruce-szalwinski** [comment]
works on tomcat 7.0.57.  Fails on tomcat 8.0.14.

**Comment by wilkinsona** [comment]
One way to fix this would be to assume that any MBean retrieved from JNDI is being managed by the container and that we don't need to export it to the MBean server. `AnnotationMBeanExporter` doesn't support the accumulation of a list of bean names to exclude from export, it only offers a setter. We could possibly create our own bean that holds a mutable list and then use it when auto-configuring our `AnnotationMBeanExporter` to set the excludes but this may run into ordering issues.

@snicoll I see you're an author on `MbeanExporter`. Would it be appropriate to make a change to allow us to add to the list of excluded bean names? It would be useful to be able to configure them right up until the point that it performs the exports in `afterSingletonsInstantiated`?

**Comment by snicoll** [comment]
I don't see why we couldn't do that, yeah. Can you create an issue for the exclude option?

**Comment by wilkinsona** [comment]
Thanks. I've opened [SPR-12686](https://jira.spring.io/browse/SPR-12686).

**Comment by snicoll** [comment]
That issue is fixed so you should be able to exclude it the way you want. Can you please try so that we have a chance to correct anything before the SPR release tomorrow? Thanks!

**Comment by wilkinsona** [comment]
@snicoll The Spring Framework change looks good to me. Thanks.

**Comment by wilkinsona** [comment]
SimpleNamingContextBuilder pollutes the JVMs JNDI configuration and, depending on the order in which the tests are run, may cause subsequent tests to fail.
