### ISSUE TITLE
favicon.ico is distorted when served from a Spring Boot instance

### ISSUE THREAD

**Issue by csavory** [spring-projects/spring-boot#2398]
I can't attach our favicon.ico to this issue since it is not supported file type.  I guess I will have to submit a sample project to spring-boot-issues.  

The reason that I am creating this issue is that it works fine when I drop the ico file in an apache instance, but it is distorted when served through spring boot instance from the root of the /static folder.  I'm not sure if this a Spring Resource or Embedded Tomcat issue, but I thought I would start here since the Favicon Resource Handler is created by WebMvcAutoConfiguration.

**Comment by wilkinsona** [comment]
Works for me with GitHub's favicon.ico:

    $ curl -s https://github.com/favicon.ico | shasum
    4eda7c0f3a36181f483dd0a14efe9f58c8b29814  -
    $ curl -s http://localhost:8080/favicon.ico | shasum
    4eda7c0f3a36181f483dd0a14efe9f58c8b29814  -

I think we'll need a sample that reproduces the problem to be able to investigate further

**Comment by csavory** [comment]
@wilkinsona I just used the same one that I uploaded yesterday but added the favicon.ico file.  If you want to delete the PR due to copyright issues, that is fine.

Here is my curl output when compared to my zend/apache server:
```
Christophers-MacBook-Pro-2:elrc csavory$ curl -s http://localhost/favicon.ico | shasum
7592641caa75f66f897357a0b9f96c224b345d25  -
Christophers-MacBook-Pro-2:elrc csavory$ curl -s http://localhost:8080/favicon.ico | shasum
4a7596a4efb80f732c205f80d80e5a89ac802b9b  -
Christophers-MacBook-Pro-2:elrc csavory$ 
```

If you serve up the later through the browser, you can see the distortion.

**Comment by wilkinsona** [comment]
Your resource filtering configuration has corrupted the file. Remove the following from your pom:

    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>

Alternatively, configure suitable includes and excludes to avoid filtering binary files.

**Comment by csavory** [comment]
@wilkinsona how were you able to find that?  We spent many hours trying to find that issue.

**Comment by wilkinsona** [comment]
@casavory Largely because I'd encountered similar problems in the past. I ran your app with `mvn spring-boot:run` and the problem didn't occur. I then packaged it and ran it with `java -jar` and it did, so I knew it was probably something to do with the build. The was enough for the resource filtering penny to drop.
