### ISSUE TITLE
Incorrect link built into "Learn" docs page

### ISSUE THREAD

**Issue by hagemt** [spring-projects/spring-boot#23987]
The `API Doc.` link on this page incorrectly points to the latest reference docs: https://spring.io/projects/spring-boot#learn

It should probably go to: https://docs.spring.io/spring-boot/docs/current/api/

I forked to open a pull request, but while the API docs are built using this repo, I don't think that "parent" page is.

Anyway, thought someone here would be interested. Current is 2.3.5.RELEASE, as of a few days ago.

**Comment by bclozel** [comment]
The link is now fixed.
Thank you!
