### ISSUE TITLE
Add support of HttpMessageConvertersAutoConfiguration for @AutoConfigureMockMvc

### ISSUE THREAD

**Issue by tillias** [spring-projects/spring-boot#24000]
Hello folks,

I'd like to test some rest controller. I can't use @WebMvcTest cause my security config user JWT Token Provider which is @Component itself and will be filtered out by @WebMvcTest

I can't use @SpringBootTest either, because it ignores HttpMessageConvertersAutoConfiguration and I get **during test only** (this means it works in prod)

`org.springframework.http.converter.HttpMessageNotWritableException`

Can you please add support of _HttpMessageConvertersAutoConfiguration_ for @AutoConfigureMockMvc?

Here is sample code:

```
@SpringBootTest(classes = {SomeControllerUnderTest.class})
@AutoConfigureMockMvc
@WithMockUser
class SomeControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private SomeMockService service;

    @Test
    void foo() throws Exception {

       ... setup mock ...

        mockMvc.perform(get("/api/some"))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE));
    }
}
```

If I change @SpringBootTest and remove **classes** it works just fine, but initializes ALL the crap I don't need: 

```
@SpringBootTest
@AutoConfigureMockMvc
@WithMockUser
class SomeControllerTest {
```

Thanks!

**Comment by frekele** [comment]
I have similar behavior too.

**Comment by wilkinsona** [comment]
HTTP message converter auto-configuration will be included if you use `@AutoConfigureWebMvc` rather than `@AutoConfigureMockMvc`. I don't think it should be added to the latter as it's not specific to MockMvc-based testing. `@WebMvcTest` uses both `@AutoConfigureWebMvc` and `@AutoConfigureMockMvc` and it looks like you want both as well.

**Comment by tillias** [comment]
@wilkinsona many thanks, it works!

@frekele if you're interested here is custom annotation you can use: https://stackoverflow.com/questions/64648893/autoconfiguremockmvc-how-to-set-message-converters
