### ISSUE TITLE
Instance of ActiveMQConnectionFactory cannot be injected when using ActiveMQAutoConfiguration

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-boot#2403]
We just integrated Spring Security with a Spring Boot app that use AMQ to publish events. As soon as we add spring-security-oauth2 to our pom.xml, AMQ will not stand up.

I'll try to get supporting docs/test cases ASAP, but we are pushing for prod next week.

I think it has something do with with the ``@AutoConfigureAfter({ JtaAutoConfiguration.class, JndiConnectionFactoryAutoConfiguration.class })`` annotation in ``ActiveMQAutoConfiguration``.

We have a workaround by standing up our own with:

```java
	@Bean
	public ActiveMQConnectionFactory connectionFactory(@Value("${spring.activemq.brokerUrl}") String brokerUrl) {
		return new ActiveMQConnectionFactory(brokerUrl);
	}
```

I've duplicated this issue in both the spring-boot and spring-security-oauth projects.

**Comment by wilkinsona** [comment]
When you say "AMQ will not stand up" do you get a failure, or does the app run fine minus the expected connection factory? If it's the former, what's the failure you see? If it's the latter, can you share the auto-configuration report (either from the autoconfig actuator endpoint or by running with `--debug`) for your app please?

**Comment by wilkinsona** [comment]
The duplicate issue: spring-projects/spring-security-oauth#371

**Comment by efenderbosch** [comment]
Apologies for the lack of details but we are pushing for production this week. I'll update as soon as I have a moment to think.

**Comment by efenderbosch** [comment]
Ok, I created a minimal project to re-create the issue here:

https://github.com/efenderbosch/spring-security-amq-problem

It will run as-is on checkout. Simply comment out the ``@Bean ActiveMQConnectionFactory`` from ``Application.java`` and the problem will surface.

**Comment by wilkinsona** [comment]
The bean created by `ActiveMQConnectionFactoryConfiguration` is typed as a `javax.jms.ConnectionFactory` rather than a `org.apache.activemq.ActiveMQConnectionFactory` but your custom ActiveMQ health indicator is asking for an `org.apache.activemq.ActiveMQConnectionFactory`.

Your explicit `ActiveMQConnectionFactory` bean resolves the problem as it switches off the auto-configured connection factory and replaces it with one that is typed (from Spring's perspective) as an `org.apache.activemq.ActiveMQConnectionFactory`.

An alternative solution is to change your health indicator's constructor:

    @Autowired
	public ActiveMqHealthIndicator(ConnectionFactory connectionFactory) {
		this.connectionFactory = (ActiveMQConnectionFactory)connectionFactory;
	}

**Comment by efenderbosch** [comment]
I see now. Thanks.

Maybe ``ActiveMQConnectionFactoryConfiguration`` should return ``ActiveMQConnectionFactory`` instead of ``ConnectionFactory``? Any bean looking for ``ConnectionFactory`` will still get it, and beans looking for ``ActiveMQConnectionFactory`` will also get it an not have to perform a cast.

**Comment by wilkinsona** [comment]
Yeah, probably. That's a little easier said than done as the method currently returns two different types depending on whether or not pooling is enabled. We'll see what we can do. Thanks for altering us to the problem.
