### ISSUE TITLE
All batch jobs are executed if spring.batch.job.names is empty

### ISSUE THREAD

**Issue by paranoiabla** [spring-projects/spring-boot#2407]
Hello,

I have several jobs defined, and I don't want them to be started at startup. However, they are always started, and I believe the reason is `JobLauncherCommandLineRunner.java` the `if` clause on line 220. If you haven't specified the property `spring.batch.job.names` then the execution will proceed to line 227 and execute the job. So in my case the property is empty and all the jobs are executed.

**Comment by paranoiabla** [comment]
I have created a pull request for this:
https://github.com/spring-projects/spring-boot/pull/2408

However I wasn't able to run the build so I'm not sure if my changes are OK.

**Comment by wilkinsona** [comment]
The behaviour you've described is by design. From the javadoc of `JobLauncherCommandLineRunner`:

> `CommandLineRunner` to launch Spring Batch jobs. Runs all jobs in the surrounding context by default.

If you want to disable job launching entirely then you should set `spring.batch.job.enabled` to `false`.

**Comment by sddakoty** [comment]
Indeed I also have to admin this is very count intuitive! I had several jobs configured configured by default, and created an application-test.profile with "spring.batch.job.names=" to disable any jobs.

And wondered why all jobs got executed even though I did not configure a single job.
