### ISSUE TITLE
Bug: property sources within hidden folders not found since SB 2.3.5 RELEASE

### ISSUE THREAD

**Issue by skloessel** [spring-projects/spring-boot#24070]
Since the latest release 2.3.5 properties files under "hidden" folders are not detected anymore and corresponding property bindings are not initialized.

I have created a demo project (maven) with two profiles, for version 2.3.4 (fine) and 2.3.5 (bad). instructions on how to run  them are in the demo project.

[demo project on github](https://github.com/skloessel/sb-property-sources-hidden-folders)

**Comment by scottfrederick** [comment]
Duplicates #23983
