### ISSUE TITLE
Reactive: "Avoid exposing the whole classpath in a non-servlet environment"? Why?

### ISSUE THREAD

**Issue by enderteszla** [spring-projects/spring-boot#24101]
Hi there! I am trying to move from blocking JDBC repositories to reactive R2DBC repositories. But I cannot use named queries due to lack of support in `FilteredReactiveWebContextResource`. `exists()` always returns `false` in order to avoid exposing the whole classpath in a non-servlet environment.

@bclozel please help me. What's wrong with that?

Regards, L.B.

**Comment by snicoll** [comment]
@enderteszla there's no need to mention individual team members.

> But I cannot use named queries due to lack of support in FilteredReactiveWebContextResource:

I am not sure I understood what you're trying to do nor how `FilteredReactiveWebContextResource` is related. If you believe you've found a bug in Spring Boot, please share a small sample that demonstrates the problem you're facing. You can do so by attaching a zip to this issue or share a link to a GitHub repository.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
