### ISSUE TITLE
Wrong solrHealthIndicator name.

### ISSUE THREAD

**Issue by paranoiabla** [spring-projects/spring-boot#2410]
Hi,

after starting the actuator I get `rabbit` for the solr health indicator.

{
  "status" : "UP",
  "diskSpace" : {
    "status" : "UP",
    "free" : 216163561472,
    "threshold" : 10485760
  },
  "rabbit" : {
    "status" : "UP",
    "solrStatus" : "OK"
  },
  "db" : {
    "status" : "UP",
    "database" : "MySQL",
    "hello" : 1
  }
}

**Comment by paranoiabla** [comment]
The problem is in `HealthIndicatorAutoConfiguration` line 242.

petar@petar-ThinkPad-X1-Carbon:~/workspace/spring-boot$ git diff origin master
diff --git a/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java b/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java
index 48a3f3b..48276ae 100644
--- a/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java
+++ b/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java
@@ -242,7 +242,7 @@ public class HealthIndicatorAutoConfiguration {
 
                @Bean
                @ConditionalOnMissingBean(name = "solrHealthIndicator")
-               public HealthIndicator rabbitHealthIndicator() {
+               public HealthIndicator solrHealthIndicator() {
                        if (this.solrServers.size() == 1) {
                                return new SolrHealthIndicator(this.solrServers.entrySet().iterator()
                                                .next().getValue());

**Comment by snicoll** [comment]
Thanks for the report!
