### ISSUE TITLE
spring-boot:build-image has a layout parameter that cannot be always be honoured

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24105]
The `layout` and perhaps also the `layoutFactory` parameters on `spring-boot:build-image` don't make complete sense. For example, image building is currently limited to jar files yet the layout can be set to war. The parameters are also listed as being since 1.0 and 1.5 respectively, but image building was a new feature in 2.3. Perhaps `BuildImageMojo` shouldn't extend `AbstractPackagerMojo`?

**Comment by philwebb** [comment]
We'll move both out of `AbstractPackagerMojo` and push them to the subclass.
