### ISSUE TITLE
2.3.4 spring boot loggers/ROOT GET call returns 404 error

### ISSUE THREAD

**Issue by balajikrb** [spring-projects/spring-boot#24117]
With previous spring boot version this seemed to be working fine. However, in 2.3.4 I see this is no more working. Has GET call on loggers/ROOT has been removed ? or is it a bug ?
Note, loggers still returns successful response with all underlying endpoints log levels.,

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, I cannot reproduce the behaviour that you have described. With both 2.3.4 and 2.3.5, I receive a 200 response to a request to /actuator/loggers/ROOT:

```
$ http :8080/actuator/loggers/ROOT
HTTP/1.1 200 
Connection: keep-alive
Content-Type: application/vnd.spring-boot.actuator.v3+json
Date: Wed, 11 Nov 2020 09:06:30 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "configuredLevel": "INFO",
    "effectiveLevel": "INFO"
}
```

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by balajikrb** [comment]
I have the following two  configuration in my application.properties file

1). management port from env with defaulted to 8090
management.server.port=${MANAGEMENT_PORT:8090}

2). disabled few 3rd party logs
logging.level.org.springframework=OFF
logging.level.org.hibernate=OFF
logging.level.io.undertow=OFF
logging.level.com.zaxxer=OFF

with these two configurations when I tried to perform a GET operation on /loggers/ROOT then I get error result.
As I mentioned, /loggers rest resource works fine and PUT operation for changing the log level also works fine. the only thing that is not working is /loggers/ROOT

**Comment by snicoll** [comment]
@balajikrb thank you for the feedback, but please review Andy's comment:

> If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

For a start, the configuration you've shared would not allow you to access the `loggers` endpoint at all as it's not exposed by default. Adding the configuration you've shared (and exposing the loggers endpoint) things are also working fine for me.

At this point, we can't justify spending more time helping you if you don't take the time to share a project we can run ourselves as Andy has indicated. Thank you.
