### ISSUE TITLE
First line of code snippets in docs is shifted

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#24118]
Hi,

I guess this will end up in the asciidoctor-extensions repo in the end, but I didn't know for sure.

The [current documentation](https://docs.spring.io/spring-boot/docs/2.4.0-RC1/reference/htmlsingle) looks a bit weird when it comes to code snippets. When multiple lines are displayed, the first line is always shifted to the right a bit:
![image](https://user-images.githubusercontent.com/6304496/98853436-6fb8bf80-2459-11eb-836b-f5946483721e.png)
This is especially weird for YAML examples:
![image](https://user-images.githubusercontent.com/6304496/98853544-9545c900-2459-11eb-9900-71b05724f89f.png)

I wonder if that's important enough to get fixed before 2.4.0 is released.

I'm on Chrome btw, but I don't think that makes a difference here after a quick check on Safari that seems broken, too.

Cheers,
Christoph

**Comment by scottfrederick** [comment]
@dreis2211 We noticed this recently too, and [upgraded the docs resources](https://github.com/spring-projects/spring-boot/issues/24066) to fix it along with a few other formatting issues. The code blocks should look better in the [snapshot docs](https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/htmlsingle/).
