### ISSUE TITLE
System health is down because i have not specified disable to rabbit.

### ISSUE THREAD

**Issue by paranoiabla** [spring-projects/spring-boot#2411]
Hi there,

here's my `application.properties`

    management.context-path=/platform
    management.health.db.enabled=true
    management.health.diskspace.enabled=true
    management.health.solr.enabled=true
    #management.health.mongo.enabled=false
    #management.health.rabbit.enabled=false
    #management.health.redis.enabled=false

As you can see the `mongo`, `rabbit` and `redis` are commented because I don't use them in my project. However when i visit the actuator and authenticate, this is what I get:
```
{
  "status" : "DOWN",
  "diskSpace" : {
    "status" : "UP",
    "free" : 216151871488,
    "threshold" : 10485760
  },
  "rabbit" : {
    "status" : "UP",
    "solrStatus" : "OK"
  },
  "redis" : {
    "status" : "DOWN",
    "error" : "org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool"
  },
  "db" : {
    "status" : "UP",
    "database" : "MySQL",
    "hello" : 1
  }
}
```

If I uncomment them and set it to `false` it all works fine.

**Comment by paranoiabla** [comment]
I think it is because the `MongoHealthIndicatorConfiguration` contains:

```
	@Configuration
	@ConditionalOnBean(MongoTemplate.class)
	@ConditionalOnProperty(prefix = "management.health.mongo", name = "enabled", matchIfMissing = true)
	public static class MongoHealthIndicatorConfiguration {
```

I think the `matchIfMissing` should be `false`.

**Comment by snicoll** [comment]
No. The default behaviour is to enable it unless you explicitly disable it. If you have a MongoTemplate bean and you don't use mongo then you should disable it. Or disable mongo if you're not using it.

**Comment by paranoiabla** [comment]
I see. OK, I will manually specify the disable property to be true :)
