### ISSUE TITLE
Credit contributors for forward-ported contributions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24135]
I've just noticed that contributors aren't credited when their changes are ported forwards. For example, the 2.3.6 release notes do not credit @dreis2211 for https://github.com/spring-projects/spring-boot/pull/24119 which was ported forwards into 2.3.6 under #24121.

I'll flag this for team attention so that we can discuss how we might go about doing this. I think we might need a combination of changes to the forward porting script and the release notes generator.

**Comment by dreis2211** [comment]
If that helps, I don't really care about this personally. As long as the release notes mention the change it's fine.
I'm relatively certain that others might want this credit, but I wanted to make sure that you know this one particular contributor doesn't care too much about the credit ;)

**Comment by mbhave** [comment]
We discussed this on the team call but I forgot why this is a Boot issue. Wouldn't we be able to update the changelog generator to follow the forward-port chain and get the original contributor name?

**Comment by philwebb** [comment]
We thought we'd need a changelog generator change and _also_ some configuration in Boot.

**Comment by scottfrederick** [comment]
See https://github.com/spring-io/github-changelog-generator/pull/52
