### ISSUE TITLE
Upgrade to spring-doc-resources 0.2.5

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-boot#24146]
I just noticed that the anchors and navigation bar sync is not working correctly in Chrome-based browsers.
Fresh browser instance without any caching etc.

![2020-11-13 09-16-09 2020-11-13 09_18_21](https://user-images.githubusercontent.com/435872/99045522-c6291980-2591-11eb-87f7-29b65305d89c.gif)

**Comment by bclozel** [comment]
We've noticed that it's only happening in Chrome, see https://github.com/tscanlin/tocbot/issues/207.
It's probably linked to a layout rendering optimization that we applied in https://github.com/spring-io/spring-doc-resources/issues/64 - we might have to revert that change.

**Comment by bclozel** [comment]
This will be fixed with spring-io/spring-doc-resources/65, we'll use this issue to upgrade to spring-doc-resources 0.2.5

**Comment by AlexFalappa** [comment]
Please be informed that this also affects the reference guide of `2.3.6.RELEASE`. Earlier versions seem unaffected.
