### ISSUE TITLE
springboot2.4.0 start failed

### ISSUE THREAD

**Issue by asevfish** [spring-projects/spring-boot#24140]
springboot pom version update 2.4.0 failed 
error message is
![image](https://user-images.githubusercontent.com/73863060/99025710-6851fd00-25a4-11eb-819f-3a3e3328e5fa.png)

How to solve this problem

**Comment by sibidominic** [comment]
i'm also facing the same!

**Comment by lltx** [comment]
![image](https://user-images.githubusercontent.com/50090230/99031354-d3ee9700-25b1-11eb-95f2-f58eba9f79b1.png)

**Comment by oursy** [comment]
upgrade Spring Cloud Version  `<spring-cloud.version>2020.0.0-SNAPSHOT</spring-cloud.version>`

**Comment by snicoll** [comment]
Everyone, you need to make sure to use a compatible Spring Cloud version whenever you upgrade Spring Boot. Please check [the Spring Cloud project page](https://spring.io/projects/spring-cloud) or the [start.spring.io mappings](https://start.spring.io/info)
