### ISSUE TITLE
spring-boot-loader: Add configuration support for WarLauncher

### ISSUE THREAD

**Issue by mreiterer** [spring-projects/spring-boot#2414]
It is quite common to use subfolders of the `WEB-INF` directory for content which shouldn't be public accessible. E.g. `WEB-INF/views` for thymeleaf templates.

At the moment this is not possible without moving the templates to a "jar-like" structure or using another launcher (eg. `PropertiesLauncher`)

Thanks!

**Comment by philwebb** [comment]
Can you clarify what you you mean here? Are you talking about the default template location? You can set that using the `spring.thymeleaf.prefix` property.

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.
