### ISSUE TITLE
WebMvcTest and WebFluxTest ignore user-provided Thymeleaf IDialect beans

### ISSUE THREAD

**Issue by jnizet** [spring-projects/spring-boot#24149]
Beans implementing Thymeleaf's `IDialect` interface are automatically registered by Spring Boot as dialects for Thymeleaf templates. 
But this doesn't happen in WebMvcTests, where IDialect beans are not included. It seems to me that they belong to the web MVC layer, and should thus be added to the WebMvcTest slice.

The workaround is of course easy enough:

 ```
@Import(MyCustomDialect.class)
```

**Comment by wilkinsona** [comment]
Thanks, @jnizet. This feels like a bug to me. It doesn't really make sense to include an auto-configuration while excluding user-provided beans that it would normally consume.

**Comment by sadath42** [comment]
Hi @wilkinsona is this bug available to work , I would be interested to work on it.

**Comment by wilkinsona** [comment]
@sadath42 Thanks for the offer. A contribution that fixes this would be much appreciated. Please let us know if you have any questions.

**Comment by sadath42** [comment]
@wilkinsona 
I have analyzed the issue looks like we have not included the IDialect  in  WebMvcTypeExcludeFilter class .
Will include the thymleaf dependency and do the required changes .
Am I proceeding  in the correct direction.

**Comment by sadath42** [comment]
@wilkinsona  No questions as if now. I am analyzing the bug if there any questions will let you guys know .

**Comment by wilkinsona** [comment]
How's it going, @sadath42? It's been a while now. If you no longer have time to work on a fix, please just let us know and we can take care of it. Equally, please let us know if you have any questions.

**Comment by sadath42** [comment]
Hi ,
Please assign it someone else.

**Comment by priiduneemre** [comment]
Sorry for thread necromancy.

Is there a nice way to achieve the "old" behavior, _i.e._ exclude custom dialects from the `@WebMvcTest` slice, specifically? 
I suppose `excludeFilters` is the only way?

**Comment by priiduneemre** [comment]
Sorry for thread necromancy.

Is there a nice way to achieve the "old" behavior, _i.e._ exclude custom dialects from the `@WebMvcTest` slice, specifically? 
I suppose `excludeFilters` is the only way?

EDIT: To clarify the usecase, suppose you have a bunch of `@WebMvcTest`-s for REST controllers and then use Thymeleaf for templating in `javax.mail` domain. Ideally, you would like to avoid dealing with the mail-related stuff (incl. dialects) in any old controller test.

**Comment by wilkinsona** [comment]
Yes, an exclude filter would be the best way to filter out unwanted beans found via component scanning.
