### ISSUE TITLE
Typo in 2.4 release notes

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#24142]
The 2.4 release notes at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#register-weblisteners-in-a-way-that-allows-them-to-register-servlets-and-filters have:

> Servlet @WebLister classes are now registered in such...

Should be:

> Servlet @WebListener classes are now registered in such...

**Comment by wilkinsona** [comment]
Thanks, @wimdeblauwe. I've corrected the typo.
