### ISSUE TITLE
Spring Boot Plugin version: '2.3.2.RELEASE' not found

### ISSUE THREAD

**Issue by devthepenguin** [spring-projects/spring-boot#24155]
### Description

After working in the **_vs code_** workspace for a while, Gradle fails to build repeatedly and is unable to find the spring-boot plugin despite all necessary extensions being installed.

### build.gradle file
![Screenshot 2020-11-14 002458](https://user-images.githubusercontent.com/52373288/99118961-77759100-261e-11eb-8ebf-b73db9564039.png)

Error message-

Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.5.1-bin.zip'.
Build file 'C:\Users\Shivam\Desktop\gs-securing-web\complete\build.gradle' line: 2
Plugin [id: 'org.springframework.boot', version: '2.3.2.RELEASE'] was not found in any of the following sources:
- Gradle Crore Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.springframework.boot:org.springframework.boot.gradle.plugin:2.3.2.RELEASE')
  Searched in the following repositories:
    Gradle Central Plugin Repository
Plugin [id: 'org.springframework.boot', version: '2.3.2.RELEASE'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.springframework.boot:org.springframework.boot.gradle.plugin:2.3.2.RELEASE')
  Searched in the following repositories:
    Gradle Central Plugin Repository

The problem persists even after performing '.\gradlew clean' followed by '.\gradlew --refresh-dependencies'

![Screenshot 2020-11-14 023349](https://user-images.githubusercontent.com/52373288/99121134-10f27200-2622-11eb-984e-e38daeaf74ee.png)

### Visual Studio Code Version
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

### Minimal Reproduction-
[gs-securing-web.zip](https://github.com/spring-projects/spring-boot/files/5539324/gs-securing-web.zip)

**Comment by wilkinsona** [comment]
Version 2.3.2.RELEASE of Spring Boot's plugin is available from Gradle's plugin repository (https://plugins.gradle.org/plugin/org.springframework.boot/2.3.2.RELEASE) which is from where your build attempts to resolve the plugin. For it to fail, there must have been a problem with that repository. That could either have been a problem with the repository itself or with your network connection to the repository. Both are out of our control, unfortunately. If it was a problem with the portal itself, it appears to have now been resolved as your sample downloads the plugin successfully for me.
