### ISSUE TITLE
Configuration file recommendations

### ISSUE THREAD

**Issue by Synchronized1** [spring-projects/spring-boot#24159]
Yml is more concise and intuitive than properties configuration file.

![image](https://user-images.githubusercontent.com/58451554/99177980-a89eb000-2749-11eb-86c1-54b017cf7b96.png)
Every time I create the spring boot project, I have to modify it application.properties format

It is more convenient if application.yml is used as the default format of the spring boot project configuration file.

**Comment by snicoll** [comment]
> Every time I create the spring boot project, I have to modify it application.properties format

I am assuming you are referring to start.spring.io and therefore this is the wrong issue tracker to discuss this. We've already discussed this in several occasions, see [this issue](https://github.com/spring-io/start.spring.io/issues/498) in the [start.spring.io project issue tracker](https://github.com/spring-io/start.spring.io/)
