### ISSUE TITLE
Document how to customize Docker image when using CNB

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#24161]
This ticket is regarding the Boot Gradle plugin.

When [packaging OCI images](https://docs.spring.io/spring-boot/docs/2.4.0/gradle-plugin/reference/htmlsingle/#build-image), neither the [BootBuildImage](https://docs.spring.io/spring-boot/docs/2.4.0/gradle-plugin/api/org/springframework/boot/gradle/tasks/bundling/BootBuildImage.html) task nor the [paketo buildpack](https://paketo.io/docs/buildpacks/language-family-buildpacks/java/#spring-boot-applications) explains how to customize the image. One of the most common examples is including additional files in the image (`ADD` command).

**Comment by wilkinsona** [comment]
The philosophy of CNBs is that a builder and its buildpacks encapsulate predictable and reusable logic. As a result, customisation options for the user of a builder are fairly limited. If you want to add additional files to an image, a custom builder with one or more additional buildpacks is the approach that I would recommend. There is some information in the Paketo documentation about [creating a custom builder](https://buildpacks.io/docs/operator-guide/create-a-builder/) and [buildpack](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/). The [Paketo Slack](https://slack.buildpacks.io) may also be a useful resource.

**Comment by asarkar** [comment]
@wilkinsona It seems much simpler to forego the buildpack and simply use one of the Gradle Docker plugins, like [bmuschko/gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin), and craft the `Dockerfile` accordingly.

**Comment by wilkinsona** [comment]
For some use cases and situations, that is indeed the simpler option. We don't really consider one option to be better than the other and each has its own pros and cons. Just use whichever works best for the problem at hand.
