### ISSUE TITLE
Provide out-of-the-box support for Elasticsearch Sniffer

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#24174]
It would be nice if Spring Boot provides out-of-the-box support for Elasticsearch `Sniffer`.

See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_usage.html

**Comment by somayaj** [comment]
Hi, can this be worked on? Also, is this an integration of the Sniffer into the spring boot libs?

**Comment by snicoll** [comment]
@somayaj yes, it's flagged ideal for contribution. The link shows some usage of the library and this issue is about providing auto-configuration for regular use cases, potentially coupled with configuration properties to tune things as we usually do.

**Comment by scottfrederick** [comment]
Closing in favor of #24340
