### ISSUE TITLE
sprint-boot: tomcat: access.log does not honor basedir property if the server.port and management.port have been changed.

### ISSUE THREAD

**Issue by mdeimel** [spring-projects/spring-boot#2418]
Using Spring Boot `1.2.1.RELEASE` on Mac OS X 10.10.1 (Yosemite). I have the following in `application.properties`

    server.port: 9000
    management.port: 9001
    management.address: 127.0.0.1
    
    server.tomcat.access-log-enabled=true
    server.tomcat.access-log-pattern=%h %l %u %t "%r" %s %b %D
    server.tomcat.basedir=/Users/path-to-application/logs

With this setup the access logs output to `/tmp/prl-1e6aeb63-596a-4be9-b4ec-653c8e6a3c98 logs/access_log.2015-01-26.log` rather than the provided `basedir`. If I remove the first three lines of the properties file, everything logs properly.

Related to: #1581 

Thanks.

**Comment by wilkinsona** [comment]
It works for me. I configured the Actuator sample with

    server.port: 8180
    management.port: 8181
    server.tomcat.basedir: target/tomcat
    server.tomcat.access_log_enabled: true
    server.tomcat.access_log_pattern: %h %p %t "%r" %s %b

It produced `target/tomcat/logs/access_log.2015-01-28.log`:

    0:0:0:0:0:0:0:1 8180 [28/Jan/2015:17:31:20 +0000] "GET / HTTP/1.1" 401 304
    0:0:0:0:0:0:0:1 8180 [28/Jan/2015:17:31:24 +0000] "GET / HTTP/1.1" 200 35
    127.0.0.1 8181 [28/Jan/2015:17:31:11 +0000] "GET /env HTTP/1.1" 401 116
    127.0.0.1 8181 [28/Jan/2015:17:31:15 +0000] "GET /env HTTP/1.1" 200 11042

There are no access log files in my temp dir:

    $ sudo find $TMPDIR -type f | grep access | wc -l
       0

If you'd like us to investigate further, please provide an example project that illustrates the problem.

**Comment by mdeimel** [comment]
@wilkinsona Thanks for taking the time to look at this. Although I was able to reproduce it in an older project, I created a new project and it was not reproducible - as a result, closing this issue.
