### ISSUE TITLE
Release notes: `spring.config.on-location-not-found=ignore` should be  `spring.config.on-not-found=ignore`

### ISSUE THREAD

**Issue by martinbaklid** [spring-projects/spring-boot#24181]
I believe the last paragraph in the [Config Data Imports section in the Spring-Boot-2.4-Release-Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#config-data-imports) has a typo in it. `spring.config.on-location-not-found=ignore` should be  `spring.config.on-not-found=ignore` as in the [reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-optional-prefix)

**Comment by snicoll** [comment]
Thanks for the report @martinbaklid, this is fixed.
