### ISSUE TITLE
DataSourceUnwrapper calls Wrapper.isWrapperFor with a class rather than an interface causing Oracle UCP warnings

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24200]
Forward port of issue #24154 to 2.4.x.

**Comment by ankeway** [comment]
This problean causing hikariDataSource return null
because target.isInterface() 

org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration.HikariDataSourceMetricsConfiguration.bindMetricsRegistryToHikariDataSources(Collection<DataSource>)

@Autowired
		void bindMetricsRegistryToHikariDataSources(Collection<DataSource> dataSources) {
			for (DataSource dataSource : dataSources) {
				HikariDataSource hikariDataSource = DataSourceUnwrapper.unwrap(dataSource, HikariDataSource.class);
				if (hikariDataSource != null) {
					bindMetricsRegistryToHikariDataSource(hikariDataSource);
				}
			}
		}

**Comment by philwebb** [comment]
@ankeway I see you've raised #24697 as well. Let's keep the discussion on the new issue to save adding noise to one that's closed.
