### ISSUE TITLE
ConditionEvaluationReportLoggingListener registered in ApplicationContextRunner should log the report if the context fails to start

### ISSUE THREAD

**Issue by gberche-orange** [spring-projects/spring-boot#24235]
In order to help me diagnose failures of test (in particular when context fails to be initialized), I need to get a report such as the following to understand whether my `@ConditionalOnProperty` logic is correct.

```java 
@Configuration
@ConditionalOnProperty(value= DynamicCatalogConstants.OPT_IN_PROPERTY)
@EnableConfigurationProperties
public class DynamicCatalogServiceAutoConfiguration {
[...]
```

```
20-11-2020 14:47:02.380 [main] DEBUG o.s.b.a.l.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport - 


============================
CONDITIONS EVALUATION REPORT
============================


Positive matches:
-----------------

   DynamicCatalogServiceAutoConfiguration matched:
      - @ConditionalOnProperty (osbcmdb.dynamic-catalog.enabled) matched (OnPropertyCondition)


Negative matches:
-----------------

    None


Exclusions:
-----------

    None


Unconditional classes:
----------------------

    None
```

I'm using spring-boot 2.3.6.

## Observed behavior

The condition report is not invoked when context fails to start

Instead of a condition report, only the following context init exception is displayed

```
20-11-2020 14:24:10.609 [main] WARN  o.s.c.a.AnnotationConfigApplicationContext.refresh - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dynamicCatalogService' defined in com.orange.oss.osbcmdb.catalog.DynamicCatalogServiceAutoConfigurationTest$SingleServiceDefinitionAnswerAutoConfig: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dynamicCatalogServiceAutoConfigurationTest.SingleServiceDefinitionAnswerAutoConfig; factoryMethodName=dynamicCatalogService; initMethodName=null; destroyMethodName=(inferred); defined in com.orange.oss.osbcmdb.catalog.DynamicCatalogServiceAutoConfigurationTest$SingleServiceDefinitionAnswerAutoConfig] for bean 'dynamicCatalogService': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dynamicCatalogServiceAutoConfiguration; factoryMethodName=dynamicCatalogService; initMethodName=null; destroyMethodName=(inferred); defined in com.orange.oss.osbcmdb.catalog.DynamicCatalogServiceAutoConfiguration] bound.


java.lang.IllegalStateException: Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.beans.factory.support.BeanDefinitionOverrideException] failed to start

	at org.springframework.boot.test.context.assertj.AssertProviderApplicationContextInvocationHandler.getStartedApplicationContext(AssertProviderApplicationContextInvocationHandler.java:156)
	at org.springframework.boot.test.context.assertj.AssertProviderApplicationContextInvocationHandler.invokeApplicationContextMethod(AssertProviderApplicationContextInvocationHandler.java:147)
	at org.springframework.boot.test.context.assertj.AssertProviderApplicationContextInvocationHandler.invoke(AssertProviderApplicationContextInvocationHandler.java:85)
	at com.sun.proxy.$Proxy20.getBean(Unknown Source)
	at com.orange.oss.osbcmdb.catalog.DynamicCatalogServiceAutoConfigurationTest.lambda$dynamicServiceLoadWhenOptInProperty$2(DynamicCatalogServiceAutoConfigurationTest.java:84)
```

Sample code:
```java
	@Test
	void dynamicServiceLoadWhenOptInProperty() {
		ConditionEvaluationReportLoggingListener initializer = new ConditionEvaluationReportLoggingListener(LogLevel.INFO);
		ApplicationContextRunner contextRunner = new ApplicationContextRunner()
			.withInitializer(initializer)
			.withConfiguration(AutoConfigurations.of(
				SingleServiceDefinitionAnswerAutoConfig.class,
				DynamicCatalogServiceAutoConfiguration.class,
				MockedMaintenanceInfoFormatterServiceConfig.class
			))
			.withPropertyValues(DynamicCatalogConstants.OPT_IN_PROPERTY + "=true");
		contextRunner.run(context -> {
			Catalog catalog = context.getBean(Catalog.class);
			assertThat(catalog.getServiceDefinitions()).isNotEmpty();

			assertThat(context).hasSingleBean(Catalog.class);
		});
	}
```

## What I tried

The logging level is properly set to debug.

Stepping into the debugger, it seems that the `ConditionEvaluationReportLoggingListener` is never invoked for event notifications.

I however managed to manually trigger the condition report printed by invoking it explicitly with the debugger:

## References

* https://docs.spring.io/spring-boot/docs/2.3.6.RELEASE/reference/htmlsingle/#boot-features-test-autoconfig
* https://stackoverflow.com/questions/64930752/why-conditionevaluationreportlogginglistener-never-invoked-in-failed-context-tes

**Comment by snicoll** [comment]
Thanks for the report. The doc does not indicate that if the test fails the report is not going to be printed, unfortunately. It would be nice if we could alleviate this limitation so that it is provided regardless of the outcome of the test.

**Comment by wilkinsona** [comment]
I'm not sure that there's anything that we can do here. `ConditionEvaluationReportLoggingListener` listens for an `ApplicationFailedEvent` that is published by and is quite strongly coupled to `SpringApplication`. When using `ApplicationContextRunner` there's no `SpringApplication` involved – an application context is created and refresh directly instead – so I don't think we could create and publish an `ApplicationFailedEvent` as its `SpringApplication` (and args) would both have to be `null`.

**Comment by wilkinsona** [comment]
We discussed this one today and decided that we don't want to do anything to make it work out of the box. Should it be needed, you can roll your own using existing public API. Something like this:

```java
	@Test
	void deliberateStartupFailure() {
		ConditionEvaluationReportPrinter printer = new ConditionEvaluationReportPrinter();
		this.contextRunner.withInitializer(printer).withUserConfiguration(FailureConfig.class).run((context) -> {
			if (context.getStartupFailure() != null) {
				printer.print();
			}
		});
	}

	static class ConditionEvaluationReportPrinter
			implements ApplicationContextInitializer<ConfigurableApplicationContext> {

		private ConditionEvaluationReport report;

		@Override
		public void initialize(ConfigurableApplicationContext applicationContext) {
			this.report = ConditionEvaluationReport.get(applicationContext.getBeanFactory());
		}

		void print() {
			System.out.println(new ConditionEvaluationReportMessage(this.report));
		}

	}

	@Configuration(proxyBeanMethods = false)
	static class FailureConfig {

		@Bean
		public String failure() {
			throw new RuntimeException();
		}

	}
```

This could be reduced quite a bit by adding some public API to `ConditionEvaluationReportLoggingListener` to manually trigger logging of the report but, given that we haven't seen much demand for this, it doesn't feel worth it. We can reconsider in the future if demand becomes apparent.

**Comment by mauromol** [comment]
I was hit by this today and the final decision surprised me quite a lot. Also reading the documentation (that still does not report that no output is produced if the startup fails, as highlighted in https://github.com/spring-projects/spring-boot/issues/24235#issuecomment-733492212), it seems like adding this listener is helpful to test and debug autoconfigurations. If something goes wrong, and the context does not start, then it's exactly when I'd need the report more, to help me do troubleshooting...

**Comment by wilkinsona** [comment]
We discussed this today and we're going to take another look and see if we can improve things for cases where the context refresh fails. We briefly considered a convenience method for registering the `ConditionEvaluationReportLoggingListener` that could also drive it somehow if refresh fails. Unfortunately, we can't do that as the listener is in `spring-boot-autoconfigure` and the runner's in `spring-boot-test` which knows nothing of auto-configuration.

**Comment by nosan** [comment]
I think it's quite difficult to add support for `ConditionEvaluationReportLoggingListener` to `ApplicationContextRunner` with the current design.

Publishing an `ApplicationFailedEvent` when a context refresh fails inside `ApplicationContextRunner` does not feel correct to me. First, there is no `SpringApplication` involved. Second, introducing event publication into `ApplicationContextRunner` solely for this purpose feels questionable. If we start publishing events, why publish only a failure event? That seems more like a workaround than a proper solution.

Adding a dedicated method to `ApplicationContextRunner` for registering `ConditionEvaluationReportLoggingListener` is also not really an option, as `ApplicationContextRunner` and `ConditionEvaluationReportLoggingListener` live in different modules.

The root cause is that `ConditionEvaluationReportLoggingListener` relies exclusively on `ApplicationFailedEvent`, which is published by `SpringApplication`. Since `ApplicationContextRunner` does not use `SpringApplication`, the listener never receives the signal that startup has failed.

To make `ConditionEvaluationReportLoggingListener` work with `ApplicationContextRunner`, or more generally with a regular `ApplicationContext` that is not managed by `SpringApplication`, the listener would need some other way to detect that a context refresh has failed and that a crash report should be logged. Unfortunately, Spring Framework does not currently provide such an event.

I considered using `ContextClosedEvent`, but that does not help. `ContextClosedEvent` is not published when a refresh fails, and it is not even published when `close()` is called on a context whose refresh attempt failed.

Since the framework does not provide any notification for a failed refresh or for the closing of a context after a failed refresh, there is no event that can be used to trigger crash report logging. However, we do know that `ContextRefreshedEvent` is only published when `refresh()` completes successfully. Therefore, the absence of that event implies that refresh failed.

The remaining challenge is determining when the context is being destroyed. For that, we can rely on `DisposableBean`. Spring guarantees that singleton beans are destroyed both during a normal `close()` operation and when cleanup occurs after a failed `refresh()`.

Combining these two mechanisms should be sufficient to support crash report logging for any `ApplicationContext`, without relying on `ApplicationFailedEvent`:
```java
private static final class ConditionEvaluationReportListener
			implements ApplicationListener<ContextRefreshedEvent>, DisposableBean {

		private final ConfigurableApplicationContext context;

		private final ConditionEvaluationReportLogger logger;

		private final AtomicBoolean alreadyLogged = new AtomicBoolean(false);

		private ConditionEvaluationReportListener(ConfigurableApplicationContext context, LogLevel logLevel) {
			this.context = context;
			if (context instanceof GenericApplicationContext) {
				// Get the report early when the context allows early access to the bean
				// factory in case the context subsequently fails to load
				ConditionEvaluationReport report = ConditionEvaluationReport.get(context.getBeanFactory());
				this.logger = new ConditionEvaluationReportLogger(logLevel, () -> report);
			}
			else {
				this.logger = new ConditionEvaluationReportLogger(logLevel,
						() -> ConditionEvaluationReport.get(context.getBeanFactory()));
			}
		}

		/**
		 * Logs the condition report after a successful context refresh. If refresh never
		 * succeeds (for example, refresh fails), this event is not published and the
		 * crash report is logged from {@link #destroy()} when the context is closed.
		 */
		@Override
		public void onApplicationEvent(ContextRefreshedEvent event) {
			if (event.getApplicationContext() == this.context && this.alreadyLogged.compareAndSet(false, true)) {
				this.logger.logReport(false);
			}
		}

		/**
		 * Logs a crash report when the context is being destroyed without a prior
		 * {@link ContextRefreshedEvent}. This happens when refresh fails and the context
		 * is closed, so no successful refresh report has been written.
		 */
		@Override
		public void destroy() {
			if (this.alreadyLogged.compareAndSet(false, true)) {
				this.logger.logReport(true);
			}
		}

	}
```
This approach would allow `ConditionEvaluationReportLoggingListener` to work consistently with both `SpringApplication`-managed contexts and plain `ApplicationContext` instances, including those created by `ApplicationContextRunner`.

**Comment by nosan** [comment]
> The remaining challenge is determining when the context is being destroyed. For that, we can rely on DisposableBean. Spring guarantees that singleton beans are destroyed both during a normal close() operation and when cleanup occurs after a failed refresh().
Combining these two mechanisms should be sufficient to support crash report logging for any ApplicationContext, without relying on ApplicationFailedEvent:

It looks like it is a dead end. Registering `ConditionEvaluationReportLoggingListener` as a bean and relying on `Disposable` is not going work if someone overrides `onRefresh()` method and this method throws an exception. For example, `ReactiveWebServerApplicationContext`. 

I came up with an alternative solution based on the `DestructionAwareBeanPostProcessor` that waits for
**internalConfigurationAnnotationProcessor** to be  destroyed. When that destruction callback runs, the listener logs the
condition evaluation report. This is a bit of a hack, but to be honest, I've not found a better way to do it.

https://github.com/spring-projects/spring-boot/compare/main...nosan:spring-boot:24235
