### ISSUE TITLE
Include URL to springboot announcement in github release page

### ISSUE THREAD

**Issue by gberche-orange** [spring-projects/spring-boot#24232]
## Expected behavior

As a spring boot user 
* when receiving automated notifications of a new springboot release (in particular from dependabot)
* I need to access the spring boot release announcement blog entry (which provides high value content complementary to release notes)

## Observed behavior

Dependabot PRs, such as https://github.com/orange-cloudfoundry/osb-cmdb/pull/78 (reproduced below for convenience) include the content of springboot releases, e.g [v2.4.0](https://github.com/spring-projects/spring-boot/releases/tag/v2.4.0) and inline the release markdown. However, the release markdown,  but misses the URL to the blog announcement (e.g. https://spring.io/blog/2020/11/12/spring-boot-2-4-0-available-now for this release)

---

Bumps [spring-boot-gradle-plugin](https://github.com/spring-projects/spring-boot) from 2.2.6.RELEASE to 2.4.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/spring-projects/spring-boot/releases">spring-boot-gradle-plugin's releases</a>.</em></p>
<blockquote>
<h2>v2.4.0</h2>
<h2>:star: New Features</h2>
<ul>
<li>Provide a property or environment variable to enable DevTools' restarter irrespective of how the application was launched <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/21424">#21424</a></li>
</ul>
<h2>:beetle: Bug Fixes</h2>
<ul>
<li>Using last modified for static resources in reproducible archives and images causes unwanted browser caching <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24099">#24099</a></li>
<li>BootJar's afterResolve action causes resolution failures with the Versions plugin due to configurations being copied and made resolvable <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24072">#24072</a></li>
<li>Configuration metadata annotation processor may use the wrong accessor for boolean properties <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24059">#24059</a></li>
<li>When using Tomcat, key and trust store passwords set via javax.net.ssl system properties are overwritten with null when Spring Boot's equivalent properties have not been set <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24053">#24053</a></li>
<li>Config files no longer loaded if they contain a hidden path element  <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24043">#24043</a></li>
<li><code>@DataJpaTest</code> using H2 with schema.sql and spring.datasource.schema-username fails <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24024">#24024</a></li>
<li>&quot;java.lang.IllegalStateException: zip file closed&quot; when call JarFileWrapper.stream() of spring-boot-loader  <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24017">#24017</a></li>
<li>JdbcStoreTypeConfiguration picks transaction of primary data source when Quartz data source is not the primary data source <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24015">#24015</a></li>
<li>TestTypeExcludeFilter does not implement hashCode and equals as required by its super-class <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24013">#24013</a></li>
<li>Our auto-configuration should not use <code>@PostConstruct</code> as it's ignored on Java 11+ without a dependency on jakarta-annotation-api <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24010">#24010</a></li>
<li><code>@MockBean</code> fields are not reset for JUnit 5 <code>@Nested</code> tests using <code>@WebMvcTest</code> <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/23984">#23984</a></li>
<li>ClasspathLoggingApplicationListener logs the classpath as unknown on Java 11 and later <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/23138">#23138</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Fix link to Flyway callback docs <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24122">#24122</a></li>
<li>Fix deprecation warnings in javadoc comments <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/pull/24120">#24120</a></li>
<li>Provide more details about overriding SpringPhysicalNamingStrategy's case insensitive flag <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24062">#24062</a></li>
<li>Clarify documentation regarding relaxed binding of environment variables <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24033">#24033</a></li>
<li>Enhance spring.datasource.initialization-mode property description <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24030">#24030</a></li>
<li>Recommend disabling context path redirects when using proxy-terminated SSL with Tomcat <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24026">#24026</a></li>
<li>Improve Spring Session back off documentation <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24019">#24019</a></li>
<li>Clarify the javadoc of AutoConfigureTestDatabase to make it clearer that it only replaces the main DataSource <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24007">#24007</a></li>
<li>Recommend that bean definitions provide as much type information as possible <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24005">#24005</a></li>
<li>logging.file.* properties flagged with error level while they are still honoured <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/23995">#23995</a></li>
<li>Add missing default value for enum-based configuration properties <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/23992">#23992</a></li>
<li>Configuration property replacement metadata for spring.resources.cache.cachecontrol.stale-while-revalidate is invalid <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/23980">#23980</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to AppEngine SDK 1.9.83 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24082">#24082</a></li>
<li>Upgrade to AssertJ 3.18.1 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24126">#24126</a></li>
<li>Upgrade to Byte Buddy 1.10.18 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24083">#24083</a></li>
<li>Upgrade to Couchbase Client 3.0.10 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24084">#24084</a></li>
<li>Upgrade to Hibernate 5.4.23.Final <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24085">#24085</a></li>
<li>Upgrade to Infinispan 11.0.5.Final <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24127">#24127</a></li>
<li>Upgrade to Jetty 9.4.34.v20201102 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24047">#24047</a></li>
<li>Upgrade to jOOQ 3.14.3 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24128">#24128</a></li>
<li>Upgrade to Kotlin Coroutines 1.4.1 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24087">#24087</a></li>
<li>Upgrade to Micrometer 1.6.1 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24051">#24051</a></li>
<li>Upgrade to Netty 4.1.54.Final <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24129">#24129</a></li>
<li>Upgrade to Nimbus JOSE JWT 9.1.2 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24088">#24088</a></li>
<li>Upgrade to Pooled JMS 1.2.1 <a href="https://github-redirect.dependabot.com/spring-projects/spring-boot/issues/24089">#24089</a></li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/spring-projects/spring-boot/commit/72122c29aa887526a2dd2162224a038dc8516b5f"><code>72122c2</code></a> Release v2.4.0</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/6df10842d2bfb47bf728dd8c23c63aa1655b640d"><code>6df1084</code></a> Allow Devtools to be enabled irrespective of the launching ClassLoader</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/30bc0ad96a7b36dffbf00039d6a2ecf86cb09694"><code>30bc0ad</code></a> Merge branch '2.3.x'</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/5a5f5bc2ad07c0279d570baf9e732d8b8f547588"><code>5a5f5bc</code></a> Next development version (v2.3.7.BUILD-SNAPSHOT)</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/bce2029bc6a7d3706eadc648648555548fac3da7"><code>bce2029</code></a> Merge branch '2.3.x'</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/189046bd4f740bfe5bb6ed2d206a51e6cd5ba529"><code>189046b</code></a> Revert &quot;Reduce scope of META-INF customizations to main, source, and javadoc ...</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/5b311d805b4f5b6b398aaa9e47002ddfdd6abda0"><code>5b311d8</code></a> Upgrade to Netty 4.1.54.Final</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/62e5f2e8a63805daa879c7bf3e0a10480826675b"><code>62e5f2e</code></a> Upgrade to jOOQ 3.14.3</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/56ce2afe8f49e7ea47422d1516abf66c6c2ffa5c"><code>56ce2af</code></a> Upgrade to Infinispan 11.0.5.Final</li>
<li><a href="https://github.com/spring-projects/spring-boot/commit/20edba51ef3fc05484d2444928ddcdb73cbd89c0"><code>20edba5</code></a> Upgrade to AssertJ 3.18.1</li>
<li>Additional commits viewable in <a href="https://github.com/spring-projects/spring-boot/compare/v2.2.6.RELEASE...v2.4.0">compare view</a></li>
</ul>
</details>
<br />

---

**Comment by snicoll** [comment]
There's a bit of a chicken and egg problem here as we want this to be automated. What I think you're really after is the release notes on the wiki, and that's already covered by https://github.com/spring-io/github-changelog-generator/issues/46.

**Comment by gberche-orange** [comment]
thanks @snicoll for your prompt response. 

I however see that the announcement blog seems to have high level overview, whereas the releaase notes wiki seem more detailed reference. 

https://spring.io/blog/2020/11/12/spring-boot-2-4-0-available-now
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes

Having both Url in the github release note would be ideal to me.

> There's a bit of a chicken and egg problem here as we want this to be automated.

I understand the github release markdown is mutable, so it could be \[automatically?\] edited to include the blog url once this has been generated. An alternative would be that the blob url gets a deterministic url that can be included in the github release markdown notes beforehand (this url would return a 404 until the announcement blog is published)

**Comment by snicoll** [comment]
I understand that's what you'd like but we're investigating adding a reference to the release notes and we have no plan to link to the blog post at this time. While I agree that the blog post provide a high-level overview, the release notes seems more appropriate in the context of your particular need as they give more precise instructions related to the upgrade.

Thanks for the suggestion, in any case.
