### ISSUE TITLE
Dependency management for ojdbc8-observability refers to a BOM that does not exist on Maven Central

### ISSUE THREAD

**Issue by Sachpat** [spring-projects/spring-boot#24246]
The  following dependency in Spring Boot 2.4.0      
```
     <dependency>
        <groupId>com.oracle.database.jdbc</groupId>
        <artifactId>ojdbc-bom</artifactId>
        <version>19.8.0.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```
has the transitive dependency to the pom `com.oracle.database.observability:ojdbc-bom:pom:19.8.0.0`  via `com.oracle.database.observability:ojdbc8-observability:19.8.0.0` which is not available in maven central repository yet.

 And hence the build for the application using this dependency via Spring Boot 2.4.0 fails with the below error: 

`Failed to collect dependencies at com.oracle.database.observability:ojdbc8-observability:pom:19.8.0.0: Failed to read artifact descriptor for com.oracle.database.observability:ojdbc8-observability:pom:19.8.0.0: Could not find artifact com.oracle.database.observability:ojdbc-bom:pom:19.8.0.0`

**Comment by snicoll** [comment]
Thanks for the report but, unfortunately, there is nothing we can do about this bom that isn't under our control.

@Kuassim can you please help us raise that issue at the appropriate place?

**Comment by Sachpat** [comment]
> com.oracle.database.observability:ojdbc8-observability:19.8.0.0 bom has a dependency management import for com.oracle.database.observability:ojdbc-bom:19.8.0.0. I wonder if that's a typo? If it is, there is an import cycle between those BOMS which is not ideal either

That's true. Something definitely is wrong with this dependency management import.

**Comment by Kuassim** [comment]
Sorry for the inconvenience; we are looking into this, as we speak.
Will report back ASAP.

**Comment by Kuassim** [comment]
We found and fixed the problem however our filer (the person) is on vacation. Hopefully the change will be reflected early next week.

**Comment by Sachpat** [comment]
> We found and fixed the problem however our filer (the person) is on vacation. Hopefully the change will be reflected early next week.

Thanks for the quick fix @Kuassim . Sure, will wait for the change to be reflected.

**Comment by snicoll** [comment]
Thanks a lot for the quick turnaround @Kuassim. Do I understand the missing BOM is going to be published and nothing on our end is required?

**Comment by Kuassim** [comment]
That's right @snicoll.

**Comment by snicoll** [comment]
Thanks for the follow-up. I am going to close this now.
