### ISSUE TITLE
Change request: multi-module maven/gradle project generation

### ISSUE THREAD

**Issue by Insomnium** [spring-projects/spring-boot#24269]
🎁 Dear Spring Boot team, first of all thank you for your outstanding job!

May I add a request for the feature I miss almost every time I use spring boot initializr (https://start.spring.io/)? There's often a need to make the project a multi-module one, where only one of the modules is a spring boot application itself, and another one or several module(s) is/are some API/client/etc. library stuff.

I believe if you added multi-module maven and gradle checkbox or something, you'd make a lot of developers much happier, even though they're already happy with the Spring now.

Thanks.

**Comment by scottfrederick** [comment]
Spring Initializr is a separate project from Spring Boot. There is an open issue for a similar request in that project: https://github.com/spring-io/initializr/issues/663.
