### ISSUE TITLE
Add link to appendix from error handling documentation

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#24265]
Please add documentation for `server.error` properties.
There is no mention in [Error Handling docs](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-error-handling)

**Comment by scottfrederick** [comment]
The `server.error` properties are documented in the `Common Application Properties` appendix: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties. It would be useful to link to these properties from the `Error Handling` section.

**Comment by mbhave** [comment]
Closing in favor of #24314.
