### ISSUE TITLE
mvn spring-boot:build-image downloads JDK at every run

### ISSUE THREAD

**Issue by uqix** [spring-projects/spring-boot#24262]
Is there some caching mechanism?

**Comment by bclozel** [comment]
I'm afraid we're delegating that part to the Paketo Java buildpack. Could you [create an issue on that project](https://github.com/paketo-buildpacks/java/issues/)?
Thanks!

**Comment by uqix** [comment]
Moved to https://github.com/paketo-buildpacks/java/issues/86
