### ISSUE TITLE
Gradle plugin produces build failure

### ISSUE THREAD

**Issue by Gerschtli** [spring-projects/spring-boot#24267]
Hey, after updating from 2.3.5.RELEASE to 2.4.0 I get the following error:

```
$ ./gradlew build    

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tobias/projects/buggy/build.gradle' line: 2

* What went wrong:
Could not apply requested plugin [id: 'org.springframework.boot', version: '2.4.0'] as it does not provide a plugin with id 'org.springframework.boot'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'org.springframework.boot' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 956ms
```

Gradle wrapper version:
```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9 (Oracle Corporation 11.0.9+0-adhoc..source)
OS:           Linux 5.4.78 amd64
```

To reproduce, you only need the following. This is my `build.gradle`
```groovy
plugins {
    id 'org.springframework.boot' version '2.4.0'
}
```

This is my `settings.gradle`
```groovy
rootProject.name = 'buggy'
```

**Comment by snicoll** [comment]
> To reproduce, you only need the following. 

Unfortunately, that's the problem with reproduced with code in text. I can't reproduce the problem you've described.

Perhaps a jar was corrupted or something else is happening? If you want support, please take the time to build a minimal sample we can actually run (rather than having to copy/paste bits and pieces). You can do so by attaching a zip to this issue or sharing a link to a GitHub repository.

**Comment by Gerschtli** [comment]
I created a git repo, see here: https://github.com/Gerschtli/buggy/tree/spring-boot

Maybe (as mentioned here https://github.com/ben-manes/gradle-versions-plugin/issues/447) it is an issue with my local setup, but I don't know..

**Comment by Gerschtli** [comment]
I could resolve the issue via removing my local `~/.gradle` directory which resolved the issue. Maybe there were some files corrupt, my hard drive had some issues lately.

Thank you either way!

**Comment by snicoll** [comment]
Thanks for the follow-up. Going forward, please refrain from cross-posting the same issue in multiple issue trackers as it leads to a waste of time for everyone involved.

**Comment by Gerschtli** [comment]
Yes, sorry for that!
