### ISSUE TITLE
Incorrect property name for spring jmx domain

### ISSUE THREAD

**Issue by vibhaanshu** [spring-projects/spring-boot#2427]
In file https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointMBeanExportProperties.java property is ${spring.jmx.default_domain:} instead of ${spring.jmx.default-domain:}.

Refer below link for details

https://github.com/spring-cloud/spring-cloud-config/issues/73

**Comment by snicoll** [comment]
This is a documentation issue at best. Both _ and - will work just fine since Boot uses a _relaxed_ binder. That being said, we should use hyphen everywhere for consistency so we can at least "fix" that.
