### ISSUE TITLE
Remove Neo4jDefaultCallbacksRegistrar import

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24300]
>  The SDN Neo4jDefaultCallbacksRegistrar and the reactive pendant will be a Noop in the upcoming 6.0.2 patch and deprecated. They will be removed in 6.1.

**Comment by snicoll** [comment]
These are noop in 6.0.2, that's actually shipped in Spring Boot `2.4.1`. I did reviewed that as part of switching our build to Spring Data's snapshot and we can remove these right the way (see https://github.com/spring-projects/spring-boot/commit/7c59d8a32f5f73f87b66e614a43679e0a58f73a5).
