### ISSUE TITLE
Wrapper types are not displayed in actuator env endpoint

### ISSUE THREAD

**Issue by plilja** [spring-projects/spring-boot#24307]
We have upgraded on off our projects at work to Spring boot 2.4. It seems like the way properties are serialized under /actuator/env had changed. 

For example we used to be able to get the server.port like this:

```
...
"properties": {
   "local.server.port": {
   "value": 1660
   }
}
...
```

After upgrading it instead looks like:
```
...
"properties": {
   "local.server.port": {
   "value": "Complex property type java.lang.Integer"
}
```

I tracked it to this recent commit:
https://github.com/spring-projects/spring-boot/commit/1a3f810cd88ce9933fe862df1f2907a4dd12a4cf

I think the method stringifyIfNecessary should have branches for all the standard boxed types as well as BigDecimal and BigInteger.

To reproduce you can spin up a standard project from https://start.spring.io/ and include "Spring Web" and "Spring boot actuator" as dependencies and then visit the env endpoint.

**Comment by soumi1694** [comment]
The issue that's stated above I am facing the same. Is there any solution yet ..Currently I am using spring boot 2.4.0.

**Comment by scottfrederick** [comment]
@soumi1694 The issue is assigned to the milestone `2.4.1`, indicating that it was fixed in that version of Spring Boot.
