### ISSUE TITLE
Correct external application properties load order 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24308]
Originally raised in #24211, we'd like to change the order in the code rather than the docs.

**Comment by MikeN123** [comment]
Note that the docs would still require a change as well in this case. I can't figure out how to get the source of the asciidoc to link to in Github now, but in this list in the docs the order is presented as it is in the code at the moment:

<img width="354" alt="Screenshot 2020-12-01 at 17 55 28" src="https://user-images.githubusercontent.com/940409/100771221-76a27480-33fe-11eb-93b2-51c79e978302.png">
