### ISSUE TITLE
Unified version of io.netty:netty-* libraries in spring-boot-dependencies 2.4.0

### ISSUE THREAD

**Issue by yiliuTo** [spring-projects/spring-boot#24310]
spring-boot-dependencies 2.4.0 imports both `io.netty:netty-bom;4.1.54.Final` and `io.projectreactor:reactor-bom;2020.0.1`. However, the `reactor-bom` imports libraries of `io.projectreactor.netty:reactor-netty;1.0.1` which uses `io.netty:netty-*` series libraries of  version `4.1.53.Final`. 

So should the version of netty-bom be `4.1.53.Final` as well?

**Comment by philwebb** [comment]
We'd rather pull in the latest version of Netty. They should be compatible so `reactor-netty` should run with the later version.
