### ISSUE TITLE
Spring Boot profile groups with recursive references end up in endless loop

### ISSUE THREAD

**Issue by raphw** [spring-projects/spring-boot#24319]
While migrating conigurations to Spring Boot 2.4, I accidentally ended up with something like:

```yaml
spring.profiles.group.myprofile: myprofile, other
```

The JVM failed to start with an out of memory error, I assume that this ends up in a recursive loop. I suggest that the recursive definition should yield and error or be ignored.

**Comment by scottfrederick** [comment]
Closing in favor of #24327
