### ISSUE TITLE
Remove System.out.println in DevToolsPropertyDefaultsPostProcessor

### ISSUE THREAD

**Issue by ztomic** [spring-projects/spring-boot#24324]
With moving `spring.resources.*`  properties to `spring.web.resources.*` in 2.4.0 one System.out.println is introduced.

https://github.com/spring-projects/spring-boot/blame/master/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/env/DevToolsPropertyDefaultsPostProcessor.java#L107

Now with 2.4 in console is:
```log
{spring.resources.cache.period=0, spring.resources.chain.cache=false}
17:40:37.389  INFO  [restartedMain] org.springframework.boot.SpringApplication: 
```
Could you please remove it if it is not needed?

Regards

**Comment by scottfrederick** [comment]
Closing in favor of #24325
