### ISSUE TITLE
Add health check for JavaMail

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-boot#2432]
The JavaMailHealthIndicator looks like a nice addition to Spring-Boot:
https://github.com/jhipster/jhipster-sample-app/blob/e51b486ee04aae118b4165798a0824209f00869d/src/main/java/com/mycompany/myapp/config/metrics/JavaMailHealthIndicator.java#L15

**Comment by snicoll** [comment]
duplicates #2017
