### ISSUE TITLE
Inconsistent property names for JMX default domain

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2433]
In `JmxAutoConfiguration` we have `propertyResolver.getProperty("default-domain")` (direct `Environment` access which is bad on its own), and in `EndpointMBeanExportProperties` we have `@Value("${spring.jmx.default_domain:}")` (despite the javadoc saying "default-domain"). So you end up having to set both variants for it to work.

**Comment by snicoll** [comment]
I did "fix" something of that kind recently, see #2427

**Comment by dsyer** [comment]
Thanks, I didn't see that one. It's not just documentation though since there is no binding (just direct `Environment` access). But your change fixes the inconsistency at least.
