### ISSUE TITLE
Use local docker mirror for test containers

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24343]
We might be able to use the local docker mirror that is configured in concourse for test containers. I think we'd need a custom [ImageNameSubstitutor](https://www.testcontainers.org/features/image_name_substitution/) and also a custom `docker login`.

**Comment by ttddyy** [comment]
@philwebb In my project, I have [this implementation](https://gist.github.com/ttddyy/6c6069de65e1a91ec962de7118c3e09d) for image name substitution, fyi.
([Testcontainers issue comment](https://github.com/testcontainers/testcontainers-java/issues/3455#issuecomment-726429696))

**Comment by bsideup** [comment]
@philwebb if you configure your mirror like this, it would work out of the box:
https://docs.docker.com/registry/recipes/mirror/

**Comment by philwebb** [comment]
Trying something on `main`. If it's stable we can backport.

**Comment by wilkinsona** [comment]
Backported as part of 429167e71ff0e59b0dfbd8625c24307d8e74113d for gh-25135.
