### ISSUE TITLE
Consumging PageableResource

### ISSUE THREAD

**Issue by wolfmoonheart** [spring-projects/spring-boot#2434]
I tried several days to consume my webservice, what provides PageableResource. In the RespsonseEntity the content was always empty. The problem was, that my RestTemplate was not configured for consuming HAL-JSON.

With Spring-Boot 1.2.1 there were no exception or hint, that _embedded could not bind or not known attribute. The Attributes for pageable like size, totalNumber and so on where binded correctly. I only got a hint, when I downgraded to Spring-Boot 1.1.10, there was an exception _embedded not bound. Spring-Boot 1.2.1 just leave content empty without exception and anything.

**Comment by wilkinsona** [comment]
`RestTemplate` doesn't really have much to do with Spring Boot so this may well be a side-effect of the underlying move from Spring Framework 4.0.x to Spring Framework 4.1.x, but I can't tell from your description of the problem. Can you please provide a small sample that reproduces it?

**Comment by snicoll** [comment]
ping @bclozel

**Comment by bclozel** [comment]
Maybe this has something to do with [SPR-11891](https://jira.spring.io/browse/SPR-11891)?
cc @sdeleuze

**Comment by sdeleuze** [comment]
Or it is maybe related to what we discussed in [SPR-12552](https://jira.spring.io/browse/SPR-12552).
@wolfmoonheart Do you use Spring MVC `@JsonView` support in your application?

**Comment by wolfmoonheart** [comment]
Hey Guys, sorry, I forgot providing stackoverflow link:

http://stackoverflow.com/questions/28116175/consuming-spring-hateoas-pageable

**Comment by wilkinsona** [comment]
@wolfmoonheart That default was changed to `false` as it's a better option on the server-side as it ensures that a service is liberal in terms of what it accepts.

**Comment by wolfmoonheart** [comment]
For me it just hide the problem...

**Comment by wilkinsona** [comment]
That's because you're using a default that's the best option on the server-side in a client.
