### ISSUE TITLE
couchbase: SDK minor bump as well as reactor bump to 3.4

### ISSUE THREAD

**Issue by daschl** [spring-projects/spring-boot#24350]
Hi boot team,

I'm opening this ticket for awareness that in the Couchbase Java SDK we released the 3.1.0 release which now also depends on the reactor 3.4.0 release (the 3.0.x series is on reactor 3.3 at the moment).

@mp911de asked me to open it so you are aware of that change. We are planning on bumping spring-data-couchbase 4.2.0 to 3.1.0 and leave 4.1.0 and 4.0.0 on SDK 3.0.

Please let me know if I can help on getting this in properly if there are questions.

Thanks!

**Comment by mp911de** [comment]
Worth mentioning: Couchbase SDK relies on Project Reactor which puts them into a difficult situation regarding releases. The release window between Reactor and Data releases is rather short so we're currently in a situation where the current Couchbase driver (3.0.x) shipped with Boot 2.4 depends on Reactor 3.3. /cc @simonbasle

**Comment by daschl** [comment]
In theory, it should be fine to run 3.4 reactor against the later 3.0.x SDKs, because we fixed all the deprecated API usage already (so our upgrade didn't require any code changes other than some tests), so I *think* it should be ok?

**Comment by simonbasle** [comment]
> In theory, it should be fine to run 3.4 reactor against the later 3.0.x SDKs, because we fixed all the deprecated API usage already (so our upgrade didn't require any code changes other than some tests), so I think it should be ok?

I think so too... Regarding releases, if you have any insight on how we could improve the situation, let me know.

**Comment by snicoll** [comment]
Just to make sure I understood, this is about upgrading to Couchbase `3.1.0` and this upgrade will be included in Spring Data `2021.0` ultimately. This version is shipped in Spring Boot 2.5 which will use the next version of reactor. 

@daschl I don't understand what you're expecting from us at this point, sorry.

**Comment by daschl** [comment]
@snicoll as I mentioned in the ticket description, @mp911de asked me to open it to make you guys aware of the transitive dependency changes. If this information is of no use to you, I'm okay with that as well.

**Comment by snicoll** [comment]
@daschl I had seen that from the get-go but it didn't understand what action was required from our side, hence why I am asking. Mark and I chatted a bit more and we came to the conclusion that we need to take step back and discuss release schedule with the broader team. There isn't anything actionable short term here so I am going to close this issue. Thanks for letting us know.
