### ISSUE TITLE
Exclude AutoConfiguration via Properties

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-boot#2435]
It would be nice to be able to exclude AutoConfiguration classes via a property in addition to the Annotation approach. This can be helpful for disabling features without building a new artifact or for managing AutoConfig's across an org by sharing prop files.

**Comment by philwebb** [comment]
:+1:

**Comment by michaeltecourt** [comment]
Would be really cool

**Comment by haisi** [comment]
:+1:

**Comment by snicoll** [comment]
See also #2939

**Comment by snicoll** [comment]
I am tempted to give that a try with `spring.application.exclude-auto-configurations` - Thoughts?

**Comment by philwebb** [comment]
I'd prefer a different prefix. `spring.application` is currently bound to `SpringApplication` which isn't directly aware of auto-configuration. Perhaps `spring.autoconfigure.exclude`?

**Comment by snicoll** [comment]
That's `spring.main` but your key looks better than mine so let's go with that.

**Comment by JavaHelper** [comment]
I raised  a question here: https://stackoverflow.com/questions/52118145/javax-servlet-servletexception-circular-view-path-error-would-dispatch-back
Any guidance ?
