### ISSUE TITLE
QueryMap doesn't conform to set naming property style.

### ISSUE THREAD

**Issue by Pilipets** [spring-projects/spring-boot#24380]
I have a feign client with a method like below - it uses SpringQueryMap to send URL parameters.
`@PostMapping(path="/api/services/helper/reduce")`
`ResponseEntity<List<String>> filterSupply(`
`@SpringQueryMap FilterTripParams params,`
`@RequestBody List<String> supply_list);`

The problem is mapped field names are in the camel case while I expect them in the snake case since have `spring.jackson.property-naming-strategy=SNAKE_CASE`

Serialization and deserialization with the `@RequestBody` work as expected.
I would consider it a bug.

**Comment by scottfrederick** [comment]
@Pilipets Spring Cloud OpenFeign is a separate project. Please [file an issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues) in that project's GitHub repository.

**Comment by Pilipets** [comment]
Thanks for a quick response.
