### ISSUE TITLE
Add auto configuration support for ZooKeeper and Curator.

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#2438]
ZooKeeper is common for Java projects, and could it be added as auto configuration?

**Comment by snicoll** [comment]
You might want to check the [spring-cloud](http://projects.spring.io/spring-cloud/) project. Work in progress over here: https://github.com/spring-cloud/spring-cloud-zookeeper

Please raise an issue there if you have specific details to share. Thanks.
