### ISSUE TITLE
Allow a CLI app to specify the dependency management that should be used for @Grab

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2439]
Grails has recently added support for using a [Maven bom to configure the CLI's dependency management](https://github.com/grails/grails-core/commit/5fd5a7ae23ce7ea14ebabd09ffb081e6a32d356f#diff-ccc5d3f7d57972e719133964920330f0R43]). Spring Cloud also [does something similar using a properties file](https://github.com/spring-cloud/spring-cloud-cli/blob/master/spring-cloud-cli/src/main/java/org/springframework/cloud/cli/compiler/SpringCloudCompilerAutoConfiguration.java#L58)

It'd be nice if the CLI provided a way to do this itself so that projects building on the CLI didn't have to reinvent the wheel. Something like:

    @DependencyManagementBom('com.foo:bar-bom:1.0')
    class MyApp {
    }

**Comment by philwebb** [comment]
Yeah! target 1.3 perhaps?

**Comment by wilkinsona** [comment]
Embarrassingly, it turns out that my memory is terrible and that we already have something along these lines. `@GrabMetadata` can be used to point to a properties file containing dependency management information. Given that Spring Cloud has a properties file, it could, I think, be using this rather than its custom code. /cc @dsyer @spencergibb 

What's still missing is allowing the CLI to use a Maven bom and avoid the need for people to create the properties file. That's what this issue should do with `@DependencyManagementBom` replacing `@GrabMetadata`.

**Comment by dsyer** [comment]
Spring Cloud does use the properties file and it pulls it in via the equivalent of a `@GrabMetadata` in a CLI plugin (and would continue to need to do the same if `@GrabMetadata` is sperseded by `@DependencyManagementBom`). IIRC it turns out you can't install a `@GrabMetadata` in time to get the dependencies downloaded before they are needed so it has to use the library instead.

**Comment by wilkinsona** [comment]
Thanks, Dave.

> IIRC it turns out you can't install a @GrabMetadata in time to get the dependencies downloaded before they are needed so it has to use the library instead.

Interesting. Can you recall whose dependencies these were? I'd like to understand the ordering so that I don't make things any worse, and ideally make things better so you can just use the annotation or some equivalent one-liner API.
