### ISSUE TITLE
HealthIndicatorAutoConfiguration is not used without AutoConfigurationfor redis, datasource, mongodb, etc.

### ISSUE THREAD

**Issue by avthart** [spring-projects/spring-boot#2440]
My project have multiple HealthIndicators (e.g. Docker, Consul) but I see only one HealthIndicator is registered when using the HTTP endpoint /health

This project does not make use of jdbc datasource, redis, mongodb, solr, etc. so the beans in HealthIndicatorAutoConfiguration are not instantated because of the AutoConfigureAfter annotation:

```
@AutoConfigureAfter({ DataSourceAutoConfiguration.class, MongoAutoConfiguration.class,
		MongoDataAutoConfiguration.class, RedisAutoConfiguration.class,
		RabbitAutoConfiguration.class, SolrAutoConfiguration.class })
```

I want to make use of the default HealthAggregator bean without using one of the above AutoConfiguration classes.

**Comment by wilkinsona** [comment]
The `AutoConfigureAfter` annotation simply controls the ordering. If none of the listed auto-configurations are enabled then `HealthIndicatorAutoConfiguration` will still run so that's the reason why you're seeing a single indicator when you access `/health`.

I'd guess that you're using 1.2.x and you have Spring Security on the classpath. By default, 1.2 [restricts anonymous access to `/health`](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.2-Release-Notes#anonymous-health-access-restrictions)

> The `/health` actuator endpoint now restricts anonymous access. When accessed anonymously the endpoint hides the health details and simply indicates if the server is `UP` or `DOWN`. It also caches the response for the period specified by `endpoints.health.time-to-live`. These restrictions can be disabled, thereby restoring 1.1.x’s behavior, by setting `endpoints.health.sensitive` to `false`.

You can see this restriction in access if you run the actuator sample:

    $ curl localhost:8080/health
    {"status":"UP"}

    $ curl --user user:d360ee4e-0aac-426a-83bd-d7cb7f141496 localhost:8080/health
    {"status":"UP","sampleActuatorApplication":{"status":"UP","hello":"world"},"db":{"status":"UP","database":"H2","hello":1},"diskSpace":{"status":"UP","free":321375825920,"threshold":10485760}}

**Comment by avthart** [comment]
@wilkinsona Thanks for you answer. 

I don't have spring security on the classpath.

It is possible to retrieve /env, /configprops, /beans, etc but /health only displays { "Status": "UP" }
Looks like that it does not matter if spring security is on the classpath.

By setting endpoints.health.sensitive to true, I get all health information.

```
$ curl http://localhost:8001/health
{
  "status" : "UP",
  "consul" : {
    "status" : "UP",
    "X-Consul-Index" : "3690"
  },
  "docker" : {
    "status" : "UP",
    "apiVersion" : "1.16",
    "os" : "linux",
    "kernelVersion" : "3.16.7-tinycore64",
    "version" : "1.4.1"
  },
  "diskSpace" : {
    "status" : "UP",
    "free" : 187457277952,
    "threshold" : 10485760
  }
}
```

**Comment by wilkinsona** [comment]
That's all working as designed. More info in the docs: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_security_with_healthindicators

I should have explained myself more clearly above. You'll need Spring Security on the classpath if you want to be able to authenticate and get full access to the health information as I showed with the actuator sample. The alternative, as you've noted, is to set ` endpoints.health.sensitive` to `true` but that opens the health information up to anyone with HTTP access to the server.

**Comment by avthart** [comment]
@wilkinsona All clear. I also read it in the documentation. Thanks for your help. 

ps. We are using spring-restdocs in one of our new projects in it looks very good. Keep up the good work!

**Comment by wilkinsona** [comment]
> We are using your project spring-restdocs in one of our new projects in it looks very good. Keep up the good work!

Pleased to hear it. Thanks for the feedback.
