### ISSUE TITLE
Converter beans cannot be defined as lambdas

### ISSUE THREAD

**Issue by Hoysion** [spring-projects/spring-boot#24413]
```java
@Configuration
public class ConverterConfig {
    @Bean
    public Converter<String, LocalDate> localDateConverter() {
        return source -> LocalDate.parse(source, CommonConstants.DATE_FORMATTER);
//        return new Converter<String, LocalDate>() {
//            @Override
//            public LocalDate convert(String source) {
//                return LocalDate.parse(source, CommonConstants.DATE_FORMATTER);
//            }
//        };
    }
}
```
start app successfully when add converter without  the lambda exp.otherwise,failed to start app and the following result will be outputted.
Can't spring boot infer the type from the lambda exp?
```java
Caused by: java.lang.IllegalArgumentException: Unable to determine source type <S> and target type <T> for your Converter [org.hoysing.stress.converter.ConverterConfig$$Lambda$1601/1414642952]; does the class parameterize those types?
```

**Comment by Hoysion** [comment]
the version is 2.2.5

**Comment by philwebb** [comment]
We need to update `ApplicationConversionService.addBeans` to consider the factory method signature. We have some logic in `ConfigurationPropertiesBean` that could probably be extracted.

**Comment by philwebb** [comment]
Flagging for team attention to consider if we want to try and fix this as a bug, or consider it a known limitation and mark it as an enhancement.

**Comment by Hoysion** [comment]
ok.thanks!

**Comment by snicoll** [comment]
@philwebb don't we have already a PR about that that's been triaged? https://github.com/spring-projects/spring-boot/pull/22885

**Comment by philwebb** [comment]
Thanks @snicoll, I knew I'd seen this issue before but I couldn't find it. Closing as a duplicate of #22885
