### ISSUE TITLE
Application properties in 2.4 vs 2.3

### ISSUE THREAD

**Issue by carlmendoza** [spring-projects/spring-boot#24423]
Hi, just wondering if there are any other changes from Spring boot 2.3 -> 2.4? I am currently in the process of migrating a project but there seems to be an issue around trying to access a Microsoft SQL DB via AAD:

 `020-12-08T16:22:51.535920980Z ERROR [2020-12-343 16:22:51.535] [user: -] [cid: -] [main] [c.z.h.p.HikariPool] - HikariPool-1 - Exception during pool initialization. 2020-12-08T16:22:51.535952880Z com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user xxx in Active Directory (Authentication=ActiveDirectoryPassword).`

the credentials are passed using application properties as normal and did not have any blank # lines that would have messed up parsing this file although there is a double space, not sure if that is the issue.

I also added the new flag `spring.config.use-legacy-processing = true` but its underlined on intellij with cannot resolve configuration property? 

I ran the application using 2.3 and 4, and it seems to work with 2.3 but returns the error above when upgrading to 2.4.

**Comment by mbhave** [comment]
@carlmendoza There were quite a few changes related to the way config files are processed between 2.3 and 2.4. But since you've switched on the `spring.config.use-legacy-processing` flag, those changes shouldn't affect you. Do you have a small, minimal sample that we can run to reproduce the issue?

**Comment by carlmendoza** [comment]
Hi @mbhave thanks for the response, I dont have a small example at the moment unfortunately. However, just wanted to double check that double break lines between variables in application.properties shouldn't affect parsing of the field values.

Apologies for being a bit vague, just wanted to double check the application.properties I have complies with 2.4 before I delve into other potential causes of this error. Thanks!

**Comment by carlmendoza** [comment]
I will see if I can provide more info tomorrow.

**Comment by mbhave** [comment]
We fixed a [bug](https://github.com/spring-projects/spring-boot/issues/24158) related to property file processing in 2.4.1 which will be released tomorrow. In the meantime, you could try the 2.4.1 snapshots to see if that fixes your issues. If that is not the issue, a sample would be great.

**Comment by carlmendoza** [comment]
thanks @mbhave, I will try tomorrow.. is 2.4.1-SNAPSHOT on mvn, would be a quick update on our poms if it is, otherwise its fine, can create a new proj from scratch.

**Comment by carlmendoza** [comment]
closing this - the issue was with our Azure dependencies which doesn't work well with 2.4 yet, see workaround here https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-faq?pivots=programming-language-java#development

Thanks for your time @mbhave
