### ISSUE TITLE
ERROR : org.springframework.context.annotation.Configuration.proxyBeanMethods()

### ISSUE THREAD

**Issue by yzj578492228** [spring-projects/spring-boot#24426]
Hi I use spring boot 2.3.6, maven pom _spring-boot-dependencies_  ,spring-context 5.2.11

but in spring-boot-starter-data-jpa also 2.3.6,but spring-data-jpa 2.3.5 in spring-context 5.2.10 

the jar conflict each other.
ERROR : org.springframework.context.annotation.Configuration.proxyBeanMethods()

**Comment by philwebb** [comment]
I'm sorry but I'm having a hard time understanding the problem as described. Perhaps you can share a project that shows the error?

**Comment by yzj578492228** [comment]
spring-boot-starter-data-jpa:2.3.6.RELEASE
--spring-data-jpa : 2.3.6.RELEASE
_----spring-context : 5.2.10.RELEASE [compile](omitted for conflict with 5.2.11.RELEASE)_
spring-boot-starter-web:2.3.6.RELEASE
--spring-webmvc:5.2.11.RELEASE
_----spring-context : 5.2.11.RELEASE_

**Comment by bclozel** [comment]
Could you provide a sample project (some minimal application we can clone and run) that shows the problem you're having?

Also could you describe what are you trying to achieve, what behavior you were expecting and what it's doing instead? Are you getting an error message?

Your previous comments don't provide enough information. Thanks!

**Comment by yzj578492228** [comment]
2.3.7 is ok now . Thanks!

**Comment by wilkinsona** [comment]
Thanks for letting us know.
