### ISSUE TITLE
Update CI to replace $GITHUB_PASSWORD

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24458]
> Note: GitHub has discontinued password authentication to the API starting on November 13, 2020 for all GitHub.com accounts, including those on a GitHub Free, GitHub Pro, GitHub Team, or GitHub Enterprise Cloud plan. You must now authenticate to the GitHub API with an API token, such as an OAuth access token, GitHub App installation access token, or personal access token, depending on what you need to do with the token. For more information, see "Troubleshooting."

For now we're using the release token, but we should create a new one.

**Comment by snicoll** [comment]
Fixed by ff124c09027698253d2a2b9ddf751173277d52f4

**Comment by wilkinsona** [comment]
The current situation is temporary as we're reusing the release notes token. We need to generate a new token and update the CI pipelines to use it.
