### ISSUE TITLE
ActiveMQ not automatically reconnecting using pooling

### ISSUE THREAD

**Issue by weebl2000** [spring-projects/spring-boot#2447]
When setting the spring variable spring.activemq.pooled to true, the ActiveMQ Client does not automatically reconnect if it loses connection to the broker. Using Spring Boot 1.1.10.RELEASE and activemq-client 5.9.1 and activemq-pool 5.9.1

When spring.activemq.pooled=false, then it reconnects just fine.

**Comment by snicoll** [comment]
I am not sure it has anything to do with Spring Boot actually. We're just creating a regular `ConnectionFactory` and the `pooled` option is wrapping that in a `PolledConnectionFactory`. I can't see why the behaviour would be inconsistent. 

How do you reproduce that? Shutting down the broker, starting it up again and making sure the listeners are recovering?

**Comment by weebl2000** [comment]
I shutdown the broker, started it again and then I cannot send stuff with my JmsTemplate. Getting exceptions that the connection is closed.

**Comment by weebl2000** [comment]
Also: any listeners are not reconnecting to the queue.

**Comment by snicoll** [comment]
This was reported a long time ago and I wonder if that's still applicable. If that's the case, can you please share a sample that we could run ourselves?

**Comment by weebl2000** [comment]
I've been using the ActiveMQ component with 1.4.3 and it seems to reconnect fine when pooled connectionfactory is used. I think this can be closed.
