### ISSUE TITLE
Testing Properties missing from Application Properties Appendix

### ISSUE THREAD

**Issue by tedyoung** [spring-projects/spring-boot#24486]
As of the 2.3.0.RELEASE version of the documentation, the Testing Properties in the Common Application Properties section is empty. Perhaps related to the documentation splitting?

Existed here:

https://docs.spring.io/spring-boot/docs/2.2.12.RELEASE/reference/html/appendix-application-properties.html#testing-properties

Missing starting here:

https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html#testing-properties

Still missing in 2.4.1:

https://docs.spring.io/spring-boot/docs/2.4.1/reference/html/appendix-application-properties.html#testing-properties

**Comment by snicoll** [comment]
Thanks for the report @tedyoung.
