### ISSUE TITLE
如何设置下边的属性

### ISSUE THREAD

**Issue by LostYang** [spring-projects/spring-boot#24506]
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <executable>true</executable>
    </configuration>
</plugin>

在这个里边如何设置executable属性  使得jar文件可以被解压
bootJar {
    launchScript()
}

**Comment by snicoll** [comment]
@LostYang I've [already mentioned](https://github.com/spring-projects/spring-boot/issues/15094) questions have to be asked on StackOverflow or Gitter. If you think you've found a bug in Spring Boot, you'll have to provide more information in the form of a small sample with steps to reproduce and we can reconsider.
