### ISSUE TITLE
ExplodedArchive fails loading if `lib` contains files that are not `zip` archives

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-boot#2454]
An example can be found here: https://jira.spring.io/browse/XD-2578

In that case, OSX has automatically created a `.DS_Store` file under the `lib` folder automatically, and the module couldn't be deployed anymore. Generally speaking, processing an archive could benefit from being more robust. A couple of possible solutions:

- check for the extension of a file, before processing as a `JarArchive`, or
- continue assuming that any file under `lib` is potentially a `JarArchive`, but ignore loading failures and log a warning (in case the issue is caused by a malformed file);

I would personally lean towards the second option, as it is more flexible.

**Comment by wilkinsona** [comment]
@mbogoevici We'll make this more robust, but you can improve this in XD by updating your `EntryFilter` that you've passed to `ExplodedArchive.getNestedArchives()`. It's currently returning `true` for `lib/.DS_Store` which is very unlikely to be an archive.

**Comment by mbogoevici** [comment]
@wilkinsona thanks for the suggestion!

**Comment by philwebb** [comment]
[XD-2690](https://jira.spring.io/browse/XD-2690) has fixed this in XD and I'm actually thinking that swallowing and logging the exception wouldn't be a good move for us. I prefer the full failure, rather than continuing with a potentially incomplete classpath.
