### ISSUE TITLE
Actuator doesn't use the CORS Configuration with default security configuration and Spring Webflux

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#24541]
See https://github.com/spring-projects/spring-boot/issues/11987#issuecomment-742826269

**Comment by mbhave** [comment]
Moving to 2.4.x as the [fix](https://github.com/spring-projects/spring-framework/issues/26257) for this is in Spring Framework 5.3.x

**Comment by mbhave** [comment]
It is currently blocked on Spring Framework adding a `PreflightWebFilter` and Spring Security then adding something in the DSL. The current workaround is to configure a custom security configuration as follows:

```java
    @Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http, PreFlightHandler handler) throws Exception {
        http.authorizeExchange((exchanges) -> {
            exchanges.matchers(EndpointRequest.to(HealthEndpoint.class, InfoEndpoint.class)).permitAll();
            exchanges.anyExchange().authenticated();
        });
        http.addFilterAt((e,c) -> {
            if (CorsUtils.isPreFlightRequest(e.getRequest())) {
                return handler.handlePreFlight(e);
            } else {
                return c.filter(e);
            }
        }, SecurityWebFiltersOrder.CORS);
        http.httpBasic(Customizer.withDefaults());
        http.formLogin(Customizer.withDefaults());
        return http.build();
    }
}
```

**Comment by philwebb** [comment]
The framework change is in but Spring Security issue https://github.com/spring-projects/spring-security/issues/9703 is still open. We can make this work in 2.4.x then make it pretty when the security issue is fixed.
