### ISSUE TITLE
WebServer.getPort() returns 0 instead of -1 for closed connections

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24540]
The javadoc for `WebServer.getPort()` states that it returns "the port (or -1 if none)". The implementations appear to return `0`.

**Comment by philwebb** [comment]
Flagging to see if we should change the code or the javadoc.

**Comment by mbhave** [comment]
When setting the port `0` is used for selecting a random port and `-1` to disable. That makes me think the javadoc is correct.

**Comment by wilkinsona** [comment]
The implementations could be correct too as I think we need to distinguish between being disabled (-1) and not knowing what the port is because the connector's stopped and it's configured to use an ephemeral port (0).

**Comment by mbhave** [comment]
Good point @wilkinsona.

**Comment by philwebb** [comment]
We're going to change the implementation not the javadoc

**Comment by spartusch** [comment]
Hi everyone, I've created a PR for this issue https://github.com/spring-projects/spring-boot/pull/24606. I hope that's ok. It's my first contribution so I'm not familiar with the processes. In general the PR changes the implementations to return -1 instead of 0.

**Comment by philwebb** [comment]
Thanks @spartusch, I'll close this issue in favor of PR ##24606 and we can continue any discussion there when we get a chance to review it.
