### ISSUE TITLE
spring-boot-maven-plugin build:image how to pass a Binding

### ISSUE THREAD

**Issue by uqix** [spring-projects/spring-boot#24556]
we can pass a Binding when using pack or docker like this:

```sh
pack build --volume <absolute-path-to-binding>:/platform/bindings/<binding-name> <image-name>
docker run --env SERVICE_BINDING_ROOT=/bindings --volume <absolute-path-to-binding>:/bindings/<binding-name> <image-name>
```
How to do this with spring-boot-maven-plugin `build:image`

**Comment by scottfrederick** [comment]
@uqix Thanks for the question. The equivalent of `pack build --volume` is planned for a future release of the Spring Boot build plugins. See #23518 for the details.
