### ISSUE TITLE
about @ConfigurationPropertie

### ISSUE THREAD

**Issue by ya0yy** [spring-projects/spring-boot#24557]
Why is this method called when create my configure @ConfigurationProperties class
```java
// {@link org.springframework.boot.context.properties.source.ConfigurationPropertyName#convertToOriginalForm}
private CharSequence convertToOriginalForm(CharSequence element) {
    return convertElement(element, false,
	(ch, i) -> ch == '_' || ElementsParser.isValidChar(Character.toLowerCase(ch), i));
}
```
This operation led to something I didn't expect
```yml
# my applciation.yml
config:
  mapping:
    /a: /
    /b: /hello
```
```java
// my configure class
@Data
@ConfigurationProperties(prefix = "config")
public class Config {

    private final Map<String, String> mapping = new HashMap<>();

}
```
result:
Config->mapping = {"a":"/", "b":"/hello"}

but i expect：
Config ->mapping = {"/a":"/", "/b":"/hello"}

**Comment by wilkinsona** [comment]
This behaviour is [described in the documentation](https://docs.spring.io/spring-boot/docs/2.4.0/reference/htmlsingle/#boot-features-external-config-relaxed-binding-maps). When binding to a map, properties with special characters in their name must by wrapped in `[]`.
