### ISSUE TITLE
Highlight issue 1801 in spring boot security section

### ISSUE THREAD

**Issue by yacota** [spring-projects/spring-boot#2456]
It took me several hours to find a workaround and know I realize that was an already known one
Release announcements and github search capabilities are out there I know ... but this hint in reference guide would be very valuable in my opinion

**Comment by snicoll** [comment]
See #1801

**Comment by snicoll** [comment]
which version are you using? It seems the issue has been fixed in 1.2.1. If it has not, please provide more details: a sample project would be nice.

**Comment by yacota** [comment]
Solved from 1.1.9 onwards.
I didn't see David's commit, just the comment about possible workaround. My fault
Thanks

**Comment by snicoll** [comment]
no worries, thanks for the feedback.
