### ISSUE TITLE
spring-boot-starter-data-redis - Repositories throw nullpointer exceptions after certain amount of run time

### ISSUE THREAD

**Issue by DuncanCasteleyn** [spring-projects/spring-boot#24562]
I recently upgraded to Spring Boot 2.4.1 from 2.3.6.RELEASE and started getting problems with Spring Data Redis throwing null pointer exceptions, when I revert to the previous version of Spring Boot this does not happen.

[Here is a stack trace of the issue](https://gist.github.com/DuncanCasteleyn/43c84c266e91ab1b9acb470d8a4387af), I'm using Redis with repositories and they all start throwing this exception. My code of the application can be found [here](https://github.com/DuncanCasteleyn/DiscordModBot/tree/feature/upgrade-spring-2.4.x). This application uses the starter auto configuration with no additional Redis specific properties configured.

I'm not sure if the problem is caused by Spring Boot or by Spring Data Redis itself.

**Comment by DuncanCasteleyn** [comment]
I'm currently trying to see what happens if I try to switch the jedis client instead of using the lettuce-core.

**Comment by snicoll** [comment]
@DuncanCasteleyn thanks for the report but I think this should be reported against Spring Data Redis. Can you please create your issue there?

**Comment by DuncanCasteleyn** [comment]
As switching to Jedis seems to have resolved the problem I indeed assume this issue should go into the Spring Data project so I will make an issue there later today. Thanks

**Comment by DuncanCasteleyn** [comment]
Ticket created in Spring Data Project https://jira.spring.io/browse/DATAREDIS-1266
