### ISSUE TITLE
Support MQTT 5 and Shared Subscription

### ISSUE THREAD

**Issue by Whisper40** [spring-projects/spring-boot#24575]
https://docs.spring.io/spring-integration/reference/html/mqtt.html
Following this page, I don't see any compatibility with version 5.0 of MQTT which brings a real interest of load-balancing for architecture using several pods for example.
Currently with version 3, it is not possible to manage groups of subscribers.

When will version 5 be available with the default integration you propose?

thank you

**Comment by bclozel** [comment]
Closing this issue as a duplicate of spring-projects/spring-integration#3102
