### ISSUE TITLE
Auto-configure @EnableConfigurationProperties

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-boot#2457]
Since `@SpringBootApplication `is a convenience shortcut for multiple Spring Boot related auto configuration features, would it be stupid to ship `@EnableConfigurationProperties` by default ?

`@ConfigurationProperties` would then be processed automatically by the already included `@ComponentScan` annotation.

**Comment by snicoll** [comment]
I wouldn't add too much stuff to it. You can, in any case, create your own meta-annotation.

**Comment by michaeltecourt** [comment]
Although I understand your point as everybody probably tries to fit their specific case in there, it seems to me like @SpringBootApplication is already one of those meta-annotations that users could have created themselves. And since @ConfigurationProperties is the definition of the basic convenience features Spring Boot provides, I was surprised that a "naked" terminal app requires manually adding @EnableConfigurationProperties, when a web app or a batch do not.

**Comment by snicoll** [comment]
You lost me. What would be different in a "web app" or a "batch" app exactly? Maybe you should explain what you've tried because it may hide an unrelated issue.

**Comment by michaeltecourt** [comment]
Sorry for the confusion, it's just that I first used spring-boot-starter-web and spring-boot-starter-batch for various web apps and batch processes, and both starters happen to enable configuration properties.

When I created a simple command line app that only relied on spring-boot-starter + @SpringBootApplication, I was surprised to see that @ConfigurationProperties annotations were not automatically processed in the components/configuration classes that were scanned. 

Since @SpringBootApplication toggles some auto configuration features, I felt like configuration properties activation could also belong there.

**Comment by snicoll** [comment]
Okay, that's what @wilkinsona thought then. The problem is that those starters are providing additional dependencies and some of that triggers auto-configuration elements. Some have `@EnableConfigurationProperties` on them so it works for you by side effect. 

The bottom line is that If you want to use `@ConfigurationProperties` then you should enable it, rather than relying on someone else having enabled it for you. Thanks.

**Comment by philwebb** [comment]
I'm not keen on adding the annotation directly but we could perhaps provide auto-configuration for this. I can't foresee many issues with enabling this by default.

**Comment by rajjaiswalsaumya** [comment]
Well since version 1.1.8  i had made custom annotation, that had @EnableConfiguration properties, including the one today @SpringBootApplication has. I think autoconfiguration of @EnableConfigurationProperties should be a better idea, so that Component scan can pick them up.

**Comment by snicoll** [comment]
I am willing to give that a try @philwebb but I am not sure I get what would be the condition of the auto-configuration.

**Comment by philwebb** [comment]
@snicoll No condition. We just always `@EnableAutoConfigurationProperties`. I can't see any downside.
