### ISSUE TITLE
Improve usage description for BufferedApplicationStartup

### ISSUE THREAD

**Issue by ascheman** [spring-projects/spring-boot#24605]
I was trying the nice new Spring Boot startup tracking feature and used `BufferedApplicationStartup` to collect initialization data. I found that the collected data is drained from the buffer after each request. In particular, it took me a moment to recognize that the most important data is lost after the first request. As discussed with @bclozel this could be emphasized in the documentation, cf. https://stackoverflow.com/questions/65413579/spring-boot-bufferedapplicationstartup-drained-after-first-request

**Comment by oleg-sukhov** [comment]
Hello, @snicoll. I would like to make my first contribution to spring boot project. Do you think that this issue is a good start point? If yes, what should I do to start working on it?

**Comment by snicoll** [comment]
@oleg-sukhov thanks for asking. If you've used the startup feature and see what needs to be documented, please go ahead and submit a PR. The documentation is located in `spring-boot-project/spring-boot-docs/src/docs/asciidoc` in this repository and the [contributing page](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc) should provide you more details to get started.

**Comment by mbhave** [comment]
Closing in favor of PR #25075.
