### ISSUE TITLE
Ignore WebJars resources in default Spring Security policy

### ISSUE THREAD

**Issue by qerub** [spring-projects/spring-boot#2460]
`WebMvcAutoConfiguration` enables access to WebJars resources automatically, but `SpringBootWebSecurityConfiguration` only disables Spring Security for `["/css/**", "/js/**", "/images/**", "/**/favicon.ico"]`. This creates a weird situation where WebJars (with generally available content) are more protected than custom assets and where Spring Security interferes with caching headers set by for example `ShallowEtagHeaderFilter`.

I'd like to see `"/webjars/**"` included in the default Spring Security ignore list so that not every Spring Boot application has to add it manually.

(Please let me know if you're not convinced this is a good idea and I'll try to expand with some more details.)

**Comment by philwebb** [comment]
That seems sensible to me, @dsyer or @rwinch can probably verify that it won't cause problems. We'll probably wait until 1.3 though.

**Comment by dsyer** [comment]
I think it's fine for 1.2.2 actually (it won't break any existing apps).

**Comment by philwebb** [comment]
OK

**Comment by qerub** [comment]
Do you want this addition of a list element to be more thoroughly tested? :)

@philwebb: Can you change the milestone to 1.2.x-something as per @dsyer's comment?

**Comment by philwebb** [comment]
@rwinch can you just double check this change. I still nervous about making security changes in 1.2.x so I'd prefer to keep it as 1.3 feature. Especially as there is an easy workaround.

**Comment by philwebb** [comment]
Actually ignore me @rwinch, I think this has already been discussed in #2540.

**Comment by philwebb** [comment]
I think this issue duplicates #2546.

**Comment by rwinch** [comment]
@philwebb 

Honestly, I'm not that keen on ignoring URLs by default. Hidden features like this lead to security vulnerabilities for developers that are not aware of them (especially when they are added over time). If I had my way, automatically disabling security for URLs would be removed from Boot.

Another thing to consider is this feature is totally disabling security for these URLs. This means that features like adding security related HTTP response headers is also disabled. Practically speaking most developers probably want to simply allow all users to access the URLs rather than disabling security.

I would much rather see Spring Boot remove the automatic applying of this. Instead it would provide a security configurer users would need to explicitly apply that ensures every user can access the resources. For example it might look like:

```java
http
   .apply(permitAllCommonResources())
   .authorizeUrls()
      ...
```

That said this change is not much worse than what is there now, so if we cannot make the changes I suggested then we can accept the proposed enhancement.

**Comment by philwebb** [comment]
Thanks Rob, I think that's pretty much what you said in #2546.

**Comment by rwinch** [comment]
@philwebb Sorry for the repeat...I think I had a bit of a race condition on you linking the issues and forgot where I had said that before. Cheers!

**Comment by philwebb** [comment]
My fault. I didn't notice immediately that is was a dupe. At least you're consistent :)

**Comment by philwebb** [comment]
@dsyer @rwinch I'm not entirely sure how to implement this. Any chance you could take a look at `SpringBootWebSecurityConfiguration` `getIgnored()` and make some recommendations.

**Comment by rwinch** [comment]
@philwebb I guess I am wondering what we have resolved to do. Are you ok with removing the default permitAll? How do you want to trigger the defaults?

**Comment by mmartinsson** [comment]
Anything new on when this might be fixed?

It is marked as a duplicate of #2546 but that is closed with a reference back here: "Will fix in #2460". Maybe this one doesn't show up in the todo list anymore?

**Comment by philwebb** [comment]
@mmartinsson Thanks for the prompt, looks like I managed to mark them both a duplicates of each other!

**Comment by rwinch** [comment]
@philwebb Have we decided how we want to handle this (https://github.com/spring-projects/spring-boot/issues/2460#issuecomment-121060045)? Do we want to try and make this so that permitAll is applied vs ignoring?

**Comment by dsyer** [comment]
As we approach 1.4.0 I think we are nervous about changing default behaviour and so I vote -1 to switching to `permitAll()` before 1.5. We should add /webjars to the default list of unsecured assets though.

**Comment by wimdeblauwe** [comment]
Just a warning note for anybody else that tests it. If you have `spring-boot-devtools` in the classpath, the caching does not seem to work. If you remove it from your classpath, it will work.

**Comment by snicoll** [comment]
That's no longer the case, see #7014

**Comment by wimdeblauwe** [comment]
@snicoll I do not think there is an issue at all. It is just, that if you run your spring boot app locally with dev tools enabled, then I never get a 304 back for my CSS or any of the webjars CSS/JS. I did not check running from an actual jar in production. 

I just want to warn others (or future me :-)) that if you test it locally, with devtools enabled, you have to be aware of it.

**Comment by snicoll** [comment]
OK, then a bit more context would be necessary then (you didn't mentioned testing). Also, note in github issues IMO: why here rather than in the official documentation? Feel free to create a PR that improves the documentation regarding this.

**Comment by wimdeblauwe** [comment]
Valid point. I created https://github.com/spring-projects/spring-boot/issues/7516 to further discuss this.
