### ISSUE TITLE
Setting security.headers.hsts=none alone causes the HSTS headers to still appear

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#2461]
When setting `security.headers.hsts=none` (and only that `security.header.*` setting) in `application.properties` `SpringBootWebSecurityConfiguration.configureHeaders` causes the `HstsHeaderWriter` to not be added to the `HeaderWriter`. This seems fine except that by default in Spring Boot, it appears that this is the only header that is enabled by default. Turning off this header leaves no HeaderWriters left. 

That means that later on `HeadersConfigurer.getHeaderWriters()` detects that there are no headers configured and therefore adds the default set of HeaderWriters, which includes contentTypeOptions, xssProtection, cacheControl, frameOptions and HSTS. 

It seems wrong to me that if I explicitly turn off HSTS that I still get HSTS headers. Even if there were more headers turned on by default in Spring Boot, if I explicitly turn them all off, I don't want `HeaderConfigurer` to come along later and add them back in.

**Comment by bbrouwer** [comment]
After playing around some more, what I see is when I set none of the `security.headers.*` settings, I am getting just the HSTS header. When I only set `security.headers.hsts=none`, it seems that the HSTS header is in fact gone, but now all the other headers start to appear (e.g. xss, frame, cache, contentType). Even when I explicitly turn off the other headers to false (e.g. `security.headers.xss=false`, ...) those same headers that I turned off still appear. However, when I set a single `security.header.*` header to true, then I get only that one header. 

My initial claim is still basically valid that when I try to turn off all the security headers, I still get security headers to appear in the response headers.

**Comment by rwinch** [comment]
@bbrouwer Thanks for the report. I will take a look at this in the next week or so.

**Comment by aames** [comment]
Hi @rwinch It's been a few months since an update - did you get around to looking at this? Cheers!

**Comment by rwinch** [comment]
@aames Thank you for the follow up. Unfortunately I haven't had a chance to take a look. Based on the description it does appear to be an issue. I'm wondering if a reasonable workaround is to have Spring Boot register a "dummy" HeaderWriter that does nothing. This ensures that disabling all the defaults does not enable explicitly configured defaults.

Alternatively, you might consider updating to Spring Security 4. The mechanism for how the headers are configured has changed, so this may in fact fix your issue.

**Comment by bbrouwer** [comment]
I will try out Spring Security 4. That would be my preferred solution
anyway. If Spring Security 4 does not have the same issue, I am willing to
drop this issue.

On Mon, May 11, 2015 at 11:29 AM, Rob Winch <notifications@github.com>
wrote:

> @aames <https://github.com/aames> Thank you for the follow up.
> Unfortunately I haven't had a chance to take a look. Based on the
> description it does appear to be an issue. I'm wondering if a reasonable
> workaround is to have Spring Boot register a "dummy" HeaderWriter that does
> nothing. This ensures that disabling all the defaults does not enable
> explicitly configured defaults.
>
> Alternatively, you might consider updating to Spring Security 4. The
> mechanism for how the headers are configured has changed, so this may in
> fact fix your issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-boot/issues/2461#issuecomment-100945907>
> .
>



-- 


Bruce Brouwer
about.me/bruce.brouwer
[image: Bruce Brouwer on about.me]
  <http://about.me/bruce.brouwer>

**Comment by snicoll** [comment]
@bbrouwer @rwinch can we please have some feedback on this issue please?

**Comment by bbrouwer** [comment]
I do not see this problem anymore with Spring Security 4
