### ISSUE TITLE
How to use a renamed command in Redis using redistemplate in Java Spring Boot?

### ISSUE THREAD

**Issue by bulldriver** [spring-projects/spring-boot#24613]
For security reasons We want to rename the command set and flushDb using the redis configuration. But I'm using the redisTemplate which only allows me to use the methods set and flushDb and not a renamed command.

Any idea?

**Comment by spencergibb** [comment]
This is the spring boot issue tracker. You should ask here for Spring Data Redis https://jira.spring.io/browse/DATAREDIS

**Comment by snicoll** [comment]
Thanks @spencergibb.

@bulldriver please review [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues) and ask questions on StackOverflow.

**Comment by wangzhandongvip** [comment]
I met the same problem， how did you fix it? the big thks
