### ISSUE TITLE
Empty security.user.role not handled

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#2462]
When I set `security.user.role` to blank, `SpringBootWebSecurityConfiguration.ApplicationWebSecurityConfigurerAdapter.configure()` should detect that the role array is empty and skip calling `http.authorizeRequests().anyRequest().hasAnyRole(role);`

I believe when I do this the `role` array is zero length so it should be a simple if statement.

**Comment by philwebb** [comment]
Seems sensible. @rwinch @dsyer any side effects with not calling `hasAnyRole`?

**Comment by dsyer** [comment]
I'm not sure what the intent is if the list is empty. Maybe use `authenticated()` instead of `hasRole()`? Otherwise you just deny access to all resources.

**Comment by bbrouwer** [comment]
In my particular use case, I wanted to leave all control to global method security. So I was wanting it to just completely skip that chunk of code and leave things unauthorized by default. 

But I can see the point of using `authenticated()` checks. Would it make sense to check if there is a single role called `authenticated()` and use that as a special case? Or would it be better to just allow it to be a Spel expression like `@PreAuthorize` uses where I can do all kinds of boolean logic? That would probably break existing clients, though. Maybe in that case make a new property to handle the Spel option?

**Comment by philwebb** [comment]
I've added a new `security.basic.authorize-mode` property that can be used to change how authorization is applied. The default is `role` which works the same as before but you can now use `authenticated` if you want `authenticated()` or `none` if you want to skip entirely.
