### ISSUE TITLE
Hibernate Search Dependency Management

### ISSUE THREAD

**Issue by eduanb** [spring-projects/spring-boot#24642]
Consider adding `hibernate-search-orm` to Boot's dependency management. There were a few issues recently with the Hibernate version from Boot requiring specific versions of Hibernate Search. [Here is an example.](https://stackoverflow.com/questions/65150809/java-lang-classcastexception-com-sun-proxy-proxy62-cannot-be-cast-to-org-hiber)
Future upgrades to Hibernate ORM will also require Hibernate Search 5 so this issue will come up again.

**Comment by wilkinsona** [comment]
To limit the scope of Spring Boot's dependency management, we aim to only include dependencies that Spring Boot interacts with directly. Hibernate Search does not fall into that category as Spring Boot doesn't depend upon it. Thanks anyway for the suggestion.
