### ISSUE TITLE
TransactionTemplate auto-configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2464]
No `TransactionTemplate` is auto-configured if a `PlatformTransactionManager` is present.

**Comment by williewheeler** [comment]
+1

@EnableTransactionManagement should make a TransactionTemplate available automatically.

**Comment by snicoll** [comment]
We really need #1702 first. If we don't, applications that have several transaction managers (and no explicit `@Primary` will start breaking)

**Comment by snicoll** [comment]
What I don't like with my current proposal is that it creates a `transaction` package with a `TransactionAutoConfiguration` that only defines the `TransactionTemplate` if necessary. That auto-configuration relies on several places where the transaction manager is created if necessary. 

That makes sense since we have to rely on all those auto-config to make sure that only one transaction manager is defined after all. But that `transaction` package feels off, especially when looking to the `jta` package that has all the JTA support.

@philwebb @wilkinsona thoughts?

**Comment by wilkinsona** [comment]
@snicoll I had a look in your fork for your current proposal but I failed to find it. Having a separate `transaction` package that auto-configures `TransactionTemplate` makes sense to me. Ideally, I think the `jta` package would be a child of the `transaction` package.

**Comment by snicoll** [comment]
@wilkinsona I tried that but that leads to a package tangle. I was able to cut it by inverting the location of `AutoconfigureBefore` and `AutoconfigureAfter`. I'll push a PR later today with the change.
