### ISSUE TITLE
Upgrade testcontainers to 1.15.1

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-boot#24646]
Upgrade testcontainers to 1.15.**1**
when creating an application with start.spring.io

**Comment by snicoll** [comment]
@hansdesmet I am not sure what you're asking. If you'd like start.spring.io to use `Testcontainers` 1.15.1, that's the wrong issue tracker to ask as  `Testcontainers` is not managed by Spring Boot (you can see that with it hardcoding the version in a generated project rather than reusing the bom).

**Comment by hansdesmet** [comment]
Thanks Stéphane for the quick reply.
I made an issue on the start.spring.io project.
You can close this issue.

**Comment by snicoll** [comment]
Thanks for the follow-up and for creating the issue. 

Superseded by https://github.com/spring-io/start.spring.io/issues/604
