### ISSUE TITLE
Support get requests for /actuator/startup

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24666]
Currently the `startup` actuator endpoint only supports `POST` because it clears the buffer. We should offer a `GET` version that leaves the buffer in place. This will be easier to call call because CSRF protection won't be needed.

**Comment by nfrankel** [comment]
Subscribed 😅

**Comment by jenshadlich** [comment]
I understand that `POST` makes sense because of the side effects. But it's totally unintuitive. So yes, please support `GET`.

**Comment by bclozel** [comment]
Superseded by #24717
