### ISSUE TITLE
Add jdbc-api dependency when batch dependency is selected

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-boot#24665]
With the latest release of Spring Batch a user will need to select the `spring-boot-starter-jdbc` dependency  when using the Spring Batch Starter dependency.
So for this scenario we need to add the `spring-boot-starter-jdbc` dependency anytime a user selects the Spring Batch Starter dependency.
This should help users when creating their Spring Boot/Batch Project.
However if a user decides to use an older version of the Spring Batch Starter dependency they may use the in-memory option for spring batch and may not want the `spring-boot-starter-jdbc` dependency added.

**Comment by wilkinsona** [comment]
> With the latest release of Spring Batch a user will need to select the spring-boot-starter-jdbc dependency when using the Spring Batch Starter dependency

If JDBC is now a requirement when using Spring Batch, why isn't spring-jdbc a dependency of the relevant Batch module? Put  another way, what's special about using Batch in Spring Boot that means that everyone should have Spring JDBC on the classpath while it isn't needed when not using Boot?

**Comment by cppwfs** [comment]
Looks like this is already supported.  Closing issue as invalid.
