### ISSUE TITLE
Spring Boot ManagementSecurityAutoConfiguration instantiating two realms by default

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#2466]
I'm debugging a spring boot application enabled with an actuator. I'm finding that the management application is instantiated under two different realms namely "Spring" and "Realm". (I'm not passing any realm name in the application.properties file.)

The "Spring" realm is being instantiated when the AuthenticationEntryPoint is configured on the below line of code (method - configure(HttpSecurity http))

            http.exceptionHandling().authenticationEntryPoint(entryPoint());

and subsequently in the same configure method the default realm is being initiated by the name "Realm" on the below line of code.

            http.httpBasic();
I think the above code is wrong/buggy.

I'm opening this as a bug after confirming that the above code is the culprit for my 401 errors. Also posted the same issue on stackoverflow
http://stackoverflow.com/questions/28372903/spring-boot-managementsecurityautoconfiguration-instantiating-two-realms-by-defa

**Comment by rwinch** [comment]
@tollrakesh Thanks for reporting the issue. I'll take a look at it later this week.

**Comment by tollrakesh** [comment]
@rwinch did you get a chance to look at this issue?

**Comment by rwinch** [comment]
@tollrakesh Thanks for the reminder and the detailed report. You were correct this was a bug. I have pushed fixes to 1.2.4+ (i.e. 1.2.x and master). Thanks again!
