### ISSUE TITLE
Misprint in migration wiki guide

### ISSUE THREAD

**Issue by snuyanzin** [spring-projects/spring-boot#24675]
A misprint at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#muti-document-yaml-ordering
> Muti-document YAML Ordering

`l` missed, i.e. should be 
Mu**l**ti-document YAML Ordering

and in the last sentence
>insternal

should be internal
P.S. i failed to find any edit button to create a PR for that

**Comment by mbhave** [comment]
Good catch @snuyanzin. I've fixed it in the wiki.
