### ISSUE TITLE
Switch `SpringApplication.run(...)` to not use varargs

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2468]
It's easy to accidentally miss the `args` off the static `SpringApplication.run()` method. If we changed `String... args` to `String[] args` it would be harder to mess up.

**Comment by chrylis** [comment]
What's the failure case here, somehow mixing the `args` from `main` with self-supplied `args`?

**Comment by snicoll** [comment]
it's a var args so you can omit it. People do that and then complain their (command-line) arguments are not bound.

**Comment by chrylis** [comment]
Ah. I like the ability to drop arguments in without having to deal with `new String[]`, but if that becomes annoying, I'll just switch my runner to Groovy. ;-)

**Comment by snicoll** [comment]
Well you better not define any command line arguments then because they won't be taken into account. Unless I misunderstood, you have to specify that (you don't need new String[], you just reuse the `args` parameter from your `main` method).

**Comment by chrylis** [comment]
> Well you better not define any command line arguments then because they won't be taken into account.

In all my non-toy projects, I have separate launcher classes for production and playing-around use, sometimes with markedly different configurations, and I will occasionally drop args into the main class rather than fiddling with IDE run configurations.

**Comment by wilkinsona** [comment]
> I will occasionally drop args into the main class rather than fiddling with IDE run configurations.

I regularly do the same, for example to switch on `--debug`. It's a fine balance between the helping people not to mess up and requiring people to do more typing. I'm not convinced that the former outweighs the latter.

**Comment by philwebb** [comment]
OK Sold. Leave it as it is.
