### ISSUE TITLE
Use Maven Help Plugin 3.3.0 to generate effective bom as it produces reproducible output

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24704]
We use `help:effective-bom` in our bom extension to generate an effective bom. When Maven Help Plugin 3.3.0 is released, we should make sure it's the version of the help plugin that's used. This will allow us to remove `StripUnrepeatableOutputAction` as the plugin's output [should be repeatable by default](https://issues.apache.org/jira/browse/MPH-162).

**Comment by mhalbritter** [comment]
Maven Help plugin 3.3.0 is released: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-help-plugin/3.3.0/

**Comment by wilkinsona** [comment]
The output produced by 3.3.0 isn't fully repeatable. In 3.2.0 there was a comment with a timestamp:

```
<!-- Generated by Maven Help Plugin on 2023-01-17T11:18:21Z                 -->
```

This comment is now gone, however there are still other entries that aren't repeatable. For example, the value of `<project><reporting><outputDirectory>` includes the fully-qualified path of the project's directory. I don't think there's anything we can do about this so we'll have to keep `StripUnrepeatableOutputAction`.
