### ISSUE TITLE
boot 2.4 issue with webclient

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-boot#24743]
Upgrading to 2.4.1 version seems to missing some configuration for making rest calls using webclient, this below works with 2.3.7 version but no longer works with new version. It errors with unknown host
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed

`
WebClient.builder().baseUrl("https://domain.com/")
                        .build().get()
                        .uri("item/test")
                        .retrieve()
`

**Comment by bclozel** [comment]
This doesn't look like a Spring Boot bug.

Please try [the workaround listed here](https://github.com/reactor/reactor-netty/issues/1431) or [create a new issue on the reactor-netty project](https://github.com/reactor/reactor-netty/issues/) with more information (complete stacktrace and repro project) if the workaround doesn't work.

Thanks!

**Comment by rschlick** [comment]
It's definitely a bug on Netty framework since Spring Boot 2.4.x. 
Hard to bring a reproductible case.
