### ISSUE TITLE
gradle plugin always overrides Start-Class in manifest

### ISSUE THREAD

**Issue by houbie** [spring-projects/spring-boot#2477]
I was trying to use the `PropertiesLauncher` by specifying it in the manifest:
```
manifest {
        attributes 'Main-Class': 'org.springframework.boot.loader.PropertiesLauncher',
                'Start-Class': 'sample.Application'
    }
```
but resulting manifest always has the `PropertiesLauncher` for both the `Main-Class` and the `Start-Class`. This means that I get an error if I don't specify `-Dloader.main=sample.Application`.

Is there a way to override both?

Furthermore, the jar cannot be started with `java -jar` unless the layout is set to ZIP:
```
springBoot {
    layout = 'ZIP'
}
```
It would be nice if this was in the documentation for the PropertiesLauncher.

**Comment by philwebb** [comment]
The `Main-Class` attribute gets moved to Start-Class` when the fat jar is built. Try specifying `sample.Application` as your `Main-Class` and leave out `Start-Class`. I think the `expanded` layout will use the `PropertiesLauncher`.

**Comment by houbie** [comment]
I thought I tried all combinations of main class and start class, but apparently this was enough:
    springBoot {
        mainClass = 'sample.Application'
        layout = 'ZIP'
    }

Thanks!
