### ISSUE TITLE
AutoConfiguration and BeanPostProcessor

### ISSUE THREAD

**Issue by bleporini** [spring-projects/spring-boot#2478]
Hello,

I faced the following issue: 
Consider a Spring boot project using Spring data Jpa.
Consider the package in which entities are located is not a sub package of the main class's one, so you use `@EntityScan`.
Consider you use a Spring Data Jpa repository (an interface extending `JpaRepository`.
Consider you need in the configuration to inject a bean that is using the persistence context and in that configuration class you produce a `BeanPostProcessor` the application have to use.

In this situation, the package mentioned in the `@EntityScan` annotation is not considered anymore, so the entities are not part of the persistent unit, so the application context can't set the `JpaRepository` up and the application context loading process fails.

I made a demo project in order to illustrate it: https://github.com/bleporini/BugAutoConfigAndBeanPostProcessor , just run `mvn install` to see the test failing.

I originally faced this issue using Auto-configuration and Apache Camel Javaconfig component.

Regards

**Comment by wilkinsona** [comment]
Thanks for the sample project.

I wonder if we should make `EntityScanBeanPostProcessor` implement `Ordered` so that it can be processed before any unordered or lower-ordered user-declared bean post processor? Giving it an order of 0 is sufficient to make the test in the sample project pass.

@dsyer @philwebb Am I overlooking an unpleasant side-effect?

@bleporini  In the meantime, declaring the `BeanPostProcessor` bean in a separate configuration class will work around the problem. For example:

```java
@SpringBootApplication
@EntityScan(basePackages = {"domain"})
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
    
    public DemoApplication() {
    	
    }

    @Autowired
    private AnotherRepository anotherRepository;
    
    @Configuration
    public static class BeanPostProcessorConfiguration {
    	@Bean
        public BeanPostProcessor beanPostProcessor() {
            return new BeanPostProcessor() {
                @Override
                public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
                    return bean;
                }

                @Override
                public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
                    return bean;
                }
            };
        }	
    }
}
```

**Comment by bleporini** [comment]
Thanks for your prompt feedback!

As I mentioned, the original problem appeared with a subclass of `org.apache.camel.spring.javaconfig.SingleRouteCamelConfiguration` in which I need the injected component. 

So nesting the Camel configuration in an inner class doesn't help because the injected component is not accessible...

**Comment by philwebb** [comment]
@wilkinsona I can't foresee any problems with adding `Ordered` to the `EntityScanBeanPostProcessor`.
