### ISSUE TITLE
Switch default spring.mvc.pathmatch.matching-strategy

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24805]
We could upgrade to the new PathPattern based solution now.

**Comment by wilkinsona** [comment]
#24874 and #24877 need to be addressed before we can tackle this one.

**Comment by philwebb** [comment]
Also blocked on https://github.com/spring-projects/spring-framework/issues/26415

**Comment by bclozel** [comment]
We're also fixing spring-projects/spring-framework#26411 in the upcoming Spring Framework 5.3.4 release.

**Comment by philwebb** [comment]
See also https://github.com/spring-projects/spring-framework/issues/26445 which should allow us to relax the servlet path check

**Comment by philwebb** [comment]
Fails due to https://github.com/spring-projects/spring-framework/issues/26775

**Comment by philwebb** [comment]
Reopening due to https://github.com/spring-projects/spring-framework/issues/26814
