### ISSUE TITLE
Configuration metadata json does not include spring.config.use-legacy-processing

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24816]

**Comment by snicoll** [comment]
What about `spring.config.on-not-found`?

**Comment by snicoll** [comment]
A number of `spring.config` properties have the wrong source as well. I am going to repurpose this issue to handle all of that.

**Comment by snicoll** [comment]
I see why `on-not-found` hasn't been documented now, see [this section of the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-optional-prefix)
