### ISSUE TITLE
Provide a property to change loadOnStartup for DispatcherServlet.

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#2481]
It would be nice to provide a property to change `loadOnStartup` for `DispatcherServlet`.

In Spring Boot, `loadOnStartup` for `DispatcherServlet` is `-1`.

Is there any reason to use `-1` as default value?

**Comment by philwebb** [comment]
`-1` is the default, same as `javax.servlet.ServletRegistration`. Any specific reason why you want something else?

**Comment by izeye** [comment]
@philwebb I just want to make sure

that the `DispatcherServlet` has been loaded before the first request.

Although `-1` doesn't make any problem for me, I just thought it's more natural.

Am I wrong?

And in the [Spring framework document](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/), every example has `1` for `load-on-startup` as follows:
```
    <servlet>
        <servlet-name>example</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
```
I just thought it's sort of recommendation (this could be a wrong assumption).

**Comment by philwebb** [comment]
The lifecycle with Spring Boot's embedded servlet containers is a little different to WAR based deployments. With WAR deployments, the Servlet creates the application context. With embedded containers, the application context is created first and contains the servlet container. Spring Boot should also ensure that no requests can be processed before the container is fully started.

I think the property option could be useful and it's something we can consider for 1.3.

**Comment by izeye** [comment]
@philwebb Thanks for the explanation.

**Comment by benneq** [comment]
any progress on this? i'd like to preload my dispatcher servlet, too.

**Comment by wilkinsona** [comment]
@benneq The issue's currently targeted at 1.4
