### ISSUE TITLE
Wrong logging pattern with multiple web applications

### ISSUE THREAD

**Issue by stovocor** [spring-projects/spring-boot#24835]
After updating Spring Boot from 2.3.5 to 2.4.1, our logging patterns are messed up. Our setup is that we deploy multiple Spring Boot applications onto the same Tomcat. When the first application is deployed, it sets the system property `LOG_LEVEL_PATTERN` which seems to be evaluated for all applications that are being deployed afterwards.

The log pattern itself is modified by Spring Cloud and looks like
```
%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]
```

~~When using Spring Boot 2.3.5, `spring.application.name` could not be resolved during the evaluation of `LoggingSystemProperties`, but this seems to have changed with 2.4.1.~~

~~Is it even possible to disable the system property setting so that there is no conflict between the applications?~~

Update: I think the difference can be found in `org.springframework.boot.logging.logback.LogbackLoggingSystem#loadDefaults`. In 2.3.5, `LOG_LEVEL_PATTERN` was initialized for the logger context in this method. However, in 2.4.1 the context no longer contains this property. It is evaluated in `ch.qos.logback.core.subst.NodeToStringTransformer#lookupKey`.

**Comment by wilkinsona** [comment]
Thanks for the report. https://github.com/spring-projects/spring-boot/issues/23767 removed the code that set the properties on the logger context. This works fine in the common scenario where there's a single application per JVM but not when multiple applications share a JVM as one application's configuration may set system properties that overwrite another's.

**Comment by stovocor** [comment]
From bug report to release with fix in less than a day. I am impressed, thank you very much!
