### ISSUE TITLE
everytime needs to redownloading bellsoft-jre11.0.9.1+1-linux-amd64.tar.gz?

### ISSUE THREAD

**Issue by conanchen** [spring-projects/spring-boot#24831]
I have a multi-modules maven project, when I build docker-image on the project root to build all modules' docker images, get message for every module and the building is busy on the downloading for a while : 

[INFO]     [creator]       BellSoft Liberica JRE 11.0.9: Contributing to layer
[INFO]     [creator]         Downloading from https://github.com/bell-sw/Liberica/releases/download/11.0.9.1+1/bellsoft-jre11.0.9.1+1-linux-amd64.tar.gz

can only download once?

**Comment by snicoll** [comment]
This was reported before and nothing we can do here unfortunately. Please see #24262 and the follow-up issue that was  created in the appropriate issue tracker (https://github.com/paketo-buildpacks/java/issues/86)
