### ISSUE TITLE
Extract InfoPropertiesConfiguration and move to auto-configure

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2484]
GitInfo is generally useful outside of actuator.

**Comment by cemo** [comment]
FWIW `spring.io/info` displays build info + application info

```
{  
   "app":{  
      "name":"sagan-green:2",
      "start":"2015-02-12 04:01:50 +0000"
   },
   "build":{  
      "artifact":"spring-io",
      "description":"spring-io",
      "name":"spring-io"
   },
   "spring":{  
      "profiles":"production"
   },
   "git":{  
      "branch":"detached HEAD",
      "commit":{  
         "id":"d6490ab",
         "time":"2015-02-06 08:14"
      }
   }
}
```

`spring.io` displays these info properties hardcoded by application.yml. Before spring boot, I had implemented a custom maven plugin to generate build info file and adds into our application jar. This file includes some properties from `maven` and `jenkins`. 

I think that it would be nice to add such a build info into the application with a maven plugin. If you are interested in I will be open a new issue.

**Comment by philwebb** [comment]
@cemo Yes please, could you open a new issue. I'm not sure if we can provide sensible defaults or not but at the very least we could add something to the how-to docs.
