### ISSUE TITLE
Fix a typo in Spring-Boot-Config-Data-Migration-Guide

### ISSUE THREAD

**Issue by benelog** [spring-projects/spring-boot#24847]
`application.poperties` must be fixed to `application.properties` on https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide. ( 'r' is missing in 'properties')

> Spring Boot 2.4 has provided an overhaul of the way that application.poperties and ...

**Comment by philwebb** [comment]
Now fixed. Thanks!
