### ISSUE TITLE
JPARepositories and ElasticSearchRepositories should be able to be used on the same folder tree

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-boot#24859]
cf this issue https://stackoverflow.com/questions/32878813/how-do-you-use-both-spring-data-jpa-and-spring-data-elasticsearch-repositories-o
This fix should probably be by default ->
https://github.com/izeye/spring-boot-throwaway-branches/commit/874ccba09189d6ef897bc430c43b6e3705404399

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we can't do this by default. There's no requirement for a repository that is using JPA to be a `JpaRepository` or for a repository that is using Elasticsearch to be an `ElasticsearchRepository`. They could extends `CrudRepository` or `PagingAndSortedRepository` directly, for example.
