### ISSUE TITLE
CONTRIBUTING.adoc contains broken link to spring-javaformat-intellij-idea-plugin

### ISSUE THREAD

**Issue by stefanscheidt** [spring-projects/spring-boot#24864]
[CONTRIBUTING.adoc](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc) contains in section [Install the Spring Formatter plugin](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#install-the-spring-formatter-plugin-1) a link to Maven Central Repository which only provides outdated versions. Instead it should link to <https://repo.spring.io/release/io/spring/javaformat/spring-javaformat-intellij-idea-plugin/>, see <https://github.com/spring-io/spring-javaformat#intellij-idea>.

**Comment by snicoll** [comment]
Good catch, the module was renamed recently and we forgot to fix the link here.
