### ISSUE TITLE
@JSONP annotation doesn't work Spring boot jersey @Component resource 

### ISSUE THREAD

**Issue by mariusneo** [spring-projects/spring-boot#2486]
Adding `@Component` on the jersey REST resource class breaks for some reason the JSONP functionality of Jersey.

If not adding `@Component` on the jersey REST resource class and when using perf4j for performance logging, the methods of the REST resource class require explicit perf4j stopwatches because `@Profiled` annotations
are not taken anymore into account

Spring boot version used 1.2.2.RELEASE

**Comment by wilkinsona** [comment]
Can you provide a small sample project that illustrates the problem please?

**Comment by mariusneo** [comment]
I've created a sample project for the issue reported and made a pull request on spring-boot-issues project : https://github.com/spring-projects/spring-boot-issues/pull/32

The issue is described in detail in the README.md file of the project.

Please let me know if you need more details.

**Comment by wilkinsona** [comment]
I'm not sure that we can fix this in Spring Boot.

Making your resource class a `Component` allows Spring to proxy it and apply PerfJ's advice. In this case it's a CGLib proxy, i.e. a subclass of your resource class is created. Unfortunately, Jersey doesn't consider such proxies when it's looking for the JSONP annotation (it just calls getDeclaredAnnotations on the proxy subclass's method) so it fails to find it.

**Comment by wilkinsona** [comment]
Using a JDK proxy instead (by having the resource class implement an interface) doesn't work either as Jersey's `SpringComponentProvider` then fails to find the bean.

**Comment by wilkinsona** [comment]
The underlying cause (not handling CGLib proxies) is a [known issue with Jersey](https://java.net/jira/browse/JERSEY-2112).

@mariusneo In the absence of a fix for the Jersey issue, you may be able to work around this by using AspectJ compile-time weaving for Perf4J rather than Spring's proxy-based AOP support.

**Comment by mariusneo** [comment]
@wilkinsona thanks for investigating the problem and providing the compile-time weaving alternative solution.

**Comment by mdanetzky** [comment]
I've made an example of JSONP using AspectJ:
https://github.com/mdanetzky/tour-of-heroes-java
