### ISSUE TITLE
Support Jetty 10.0.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24886]
Jetty 10 with Servlet 4 support is out and Framework is looking to support it as soon in 5.3.x as possible (https://github.com/spring-projects/spring-framework/issues/26123). We should look at upgrading to 10.0.x in Boot 2.5 (while perhaps retaining support for Jetty 9.4.x at the same time). This will align Jetty's servlet support with those of Tomcat and Undertow.

**Comment by dreis2211** [comment]
Isn't Jetty 10 (or Jetty 11) requiring Java 11?

**Comment by wilkinsona** [comment]
You're right, @dreis2211. Thank you. I had mistakenly thought that it was Jetty 11 that both raised the required version of Java and made the switch to the `jakarta.*` APIs, but those changes appear to be split across 10 and 11.

In light of this, switching to Jetty 10.0.x by default in 2.5 may be too aggressive. We may need to stick with 9.4 while also supporting 10.

**Comment by dreis2211** [comment]
Just to get that straight: I'd personally love to see the baseline raised. (Regardless of Jetty upgrades) ;-)

**Comment by wilkinsona** [comment]
Boot's baseline? We'll do that in 3.0 on top of Framework 6.

**Comment by vkennke** [comment]
jfyi: Jetty 10 will be suppored in Framework 5.3.4, would love to see Boot supports Jetty 10, maybe already in 2.5.0-M2?

**Comment by wilkinsona** [comment]
Jetty 10 depends on an alpha of SLF4J 2.0 which, in turn, requires Logback users to use an alpha of Logback 1.3. I suspect Log4j2 users will be similarly affected. I've opened https://github.com/eclipse/jetty.project/issues/5943.

**Comment by wilkinsona** [comment]
The changes required to support Jetty 10 while continuing the use Jetty 9.4.x by default are in [this branch](https://github.com/wilkinsona/spring-boot/tree/jetty-10). We now need to decide if we want to take this approach or switch to using Jetty 10 by default while supporting Jetty 9.4.x.

**Comment by wilkinsona** [comment]
We're going to support Jetty 10 while sticking with 9.4.x by default for now.
