### ISSUE TITLE
Upgrade to 2.4.2 raises ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup

### ISSUE THREAD

**Issue by silverlight** [spring-projects/spring-boot#24880]
I'm trying to upgrade spring boot version to 2.4.2 from 2.1.x, I got ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup.
The pom.xml below:
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.2</version>
        <relativePath/>
</parent>
```
The error stack trace below:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:251)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
	at com.amway.commerce.commodity.Application.main(Application.java:27)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```
I don't know if there is someting confict with this version. I wanna get some help, thanks.

**Comment by bclozel** [comment]
This Spring Boot version depends on Spring Framework 5.3.3 - and [this class is present there](https://github.com/spring-projects/spring-framework/blob/v5.3.3/spring-core/src/main/java/org/springframework/core/metrics/ApplicationStartup.java).

Maybe your `spring-core` dependency is corrupted in your local repository? Could try again after purging your local repository with `mvn dependency:purge-local-repository`?

Thanks,

**Comment by silverlight** [comment]
> This Spring Boot version depends on Spring Framework 5.3.3 - and [this class is present there](https://github.com/spring-projects/spring-framework/blob/v5.3.3/spring-core/src/main/java/org/springframework/core/metrics/ApplicationStartup.java).
> 
> Maybe your `spring-core` dependency is corrupted in your local repository? Could try again after purging your local repository with `mvn dependency:purge-local-repository`?
> 
> Also, please upgrade from one minor version to the next one - the Spring Boot team is providing dedicated wiki pages to help you migrate your applications: you should try [upgrading to 2.2](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes), [then 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) and [finally 2.4](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes).
> 
> Thanks,

ok got it,thanks a lot ! :)

**Comment by silverlight** [comment]
> This Spring Boot version depends on Spring Framework 5.3.3 - and [this class is present there](https://github.com/spring-projects/spring-framework/blob/v5.3.3/spring-core/src/main/java/org/springframework/core/metrics/ApplicationStartup.java).
> 
> Maybe your `spring-core` dependency is corrupted in your local repository? Could try again after purging your local repository with `mvn dependency:purge-local-repository`?
> 
> Also, please upgrade from one minor version to the next one - the Spring Boot team is providing dedicated wiki pages to help you migrate your applications: you should try [upgrading to 2.2](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes), [then 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) and [finally 2.4](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes).
> 
> Thanks,

ok got it,thanks a lot ! :)

**Comment by seqqueman** [comment]
Hi, I got the same problem. I have to add as dependency this one:
`<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>${version.spring-boot}</version>
			</dependency>`
Maybe it can help you too. Good luck

**Comment by seqqueman** [comment]
You can try with adding this dependency:

               <dependency>
 
			<groupId>org.springframework.boot</groupId>

			<artifactId>spring-boot-starter</artifactId>

			<version>${version.spring-boot}</version>

		</dependency>

With this one a could resolve my problem.
