### ISSUE TITLE
Is Mule ESB being considered to be supported in spring-boot ?

### ISSUE THREAD

**Issue by pkasson** [spring-projects/spring-boot#2488]

**Comment by wilkinsona** [comment]
Not as far as I know – this is certainly the first time anyone's opened an issue about it. I have very little experience with Mule. What would you like to see?

**Comment by pkasson** [comment]
It may be a one-off ... but starting up Mule with spring-boot would be great for development as projects are heavily maven centric, and getting all dependencies built quickly to run a flow (test or prod) can be a great time saver.  

It would really be about integrating the flow and its' deps with a startup of the mule server.

**Comment by joshiste** [comment]
Some months ago my colleage @denschu did some exploration on this:
https://github.com/denschu/mule-examples

**Comment by denschu** [comment]
The main problem is: Mule runs with Spring 3 :-1:

**Comment by wilkinsona** [comment]
Sadly that makes this a a non-starter. If/when Mule's Spring support is updated we can perhaps revisit this.

**Comment by pkasson** [comment]
Thanks everyone for looking into it.

**Comment by wilkinsona** [comment]
The yet-to-be-released Mule 3.7 uses Spring 4.1.x so this may warrant some further exploration now

**Comment by denschu** [comment]
I just created a Spring Boot Starter for Mule (actually 3.7.0-M1): https://github.com/denschu/mule-spring-boot-starter
It works fine...
Feedback is welcome :-)

**Comment by ambrishsingh18** [comment]
I have developed a Spring boot application which was supposed be be deployed using openshift.
But now my infrastructure team have informed, hence forth Mule Standalone Server is going to be our to go server for all applications in development, we have been asked to use Mule Server in place of Spring boot as server, if there some easy way to do this ?
