### ISSUE TITLE
Develop custom ApplicationEnvironment implementation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#24892]
We could improve quite a few things if we developed our own `Environment` implementation rather than relying on `StandardEnvironment`.

For example, whilst trying to fix #24890 I discovered it's impossible for us to totally filter out `spring.profiles.active` properties due to [AbstractEnvironment.doGetActiveProfiles()](https://github.com/spring-projects/spring-framework/blob/584dabbb3980dbed5272f79a61aa996d390e528c/spring-core/src/main/java/org/springframework/core/env/AbstractEnvironment.java#L238).

It might also allow us to remove `ConfigurationPropertySourcesPropertySource` and possibly fix #17400

**Comment by chaundhyan** [comment]
@philwebb 
Have you started working on this?
If not, would you assign this enhancement to me?
Thanks

**Comment by wilkinsona** [comment]
Thanks for the offer, @chaundhyan. @philwebb is already working on this with with some changes to Spring Framework (see https://github.com/spring-projects/spring-framework/issues/26461 and https://github.com/spring-projects/spring-framework/issues/26462 for details).
