### ISSUE TITLE
Docs: Is AutoConfigurationReport outdated?

### ISSUE THREAD

**Issue by saleese** [spring-projects/spring-boot#2493]
I am checking the how-to guides in https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc. 

The page mentions the AutoConfigurationReport class in the following description:

“Troubleshoot auto-configuration

The Spring Boot auto-configuration tries its best to do the right thing, but sometimes things fail and it can be hard to tell why.

There is a really useful AutoConfigurationReport available in any Spring Boot ApplicationContext.”

I found no AutoConfigurationReport class in the project. I was wondering if the text description is outdated, and if the description should include ConditionEvaluationReport instead of AutoConfigurationReport.

Thanks in advance,
Seonah

**Comment by wilkinsona** [comment]
Thanks. You're right. It was renamed from `AutoConfigurationReport` to `ConditionEvaluationReport` in f7d4490b2d94a64fde1595f2378452fe5a20953d#diff-28a5456fa3e896d591734fc91b4f15a3.
