### ISSUE TITLE
Use SimpleDriverDataSource when creating a Liquibase-specific DataSource

### ISSUE THREAD

**Issue by wmilewski** [spring-projects/spring-boot#24944]
Hi,

When Liquibase [creates a new DataSource instance](https://github.com/spring-projects/spring-boot/blob/4c2a7db4f896f33555ec48116f6c8654d00a0852/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L148), the connection pool size is always 10, presumably a default value. This is not always desirable. It is possible to specify a custom DataSource for Liquibase to use, but setting it up is [not trivial](https://stackoverflow.com/questions/41636250/liquibase-in-spring-boot-application-keeps-10-connections-open/60490719), at least for newcomers to SpringBoot and Liquibase. I think it would be much easier to allow developers to change the pool size by setting a custom value e.g. in the `application.properties` file.

Would there be an interest in adding this new configuration property? If yes, I'd be happy to try and provide a PR.

**Comment by wilkinsona** [comment]
This was [proposed and rejected](https://github.com/spring-projects/spring-boot/issues/6604#issuecomment-238822346) in the past in favour of `@LiquibaseDataSource`. Rather than adding more properties, we could avoid using a connection pool altogetherl. This is what Flyway does when configured with a JDBC URL, username and password. We could use Spring Framework's `SimpleDriverDataSource`.

**Comment by wmilewski** [comment]
Thanks @wilkinsona. It makes sense now that I understand this is by design. An alternative could be to improve the documentation, perhaps with a code sample.

**Comment by wilkinsona** [comment]
We're going to switch to using `SimpleDriverDataSource` when we create a Liquibase-specific `DataSource`. We can't see any need for a connection pool to be used and this will align the behaviour with what happens when using Flyway.
