### ISSUE TITLE
Property my-settings.networkName cannot be overriden with an environment variable for binding to an @PropertyConfiguration

### ISSUE THREAD

**Issue by uTestMichaelL** [spring-projects/spring-boot#2495]
I have a class like this:

<pre><code>
@ConfigurationProperties(prefix = "my-settings")
public class Settings
{
     private String networkName;
     public void setNetworkName(String networkName) {this.networkName = networkName}
}
</code></pre>

There is no way to bind an environment variable to networkName.  Environment variables cannot have dots or slashes.  I tried with MY_SETTINGS_NETWORK_NAME and MYSETTINGSNETWORKNAME and neither works.

I believe I traced the reason to the fact that I have a dot and a slash in the prefix+name, which is "my-settings.networkName"

When I put this into new RelaxedPropeties("my-settings.networkName") I get these:
<pre>
my-settings.networkName
my_settings.networkName
my-settings_networkName
my-settings.network_name
my-settings.network-name
mySettingsNetworkName
mySettingsNetworkname
my-settings.networkname
my_settings.networkname
my-settings_networkname
mysettingsnetworkname
MY-SETTINGS.NETWORKNAME
MY_SETTINGS.NETWORKNAME
MY-SETTINGS_NETWORKNAME
MY-SETTINGS.NETWORK_NAME
MY-SETTINGS.NETWORK-NAME
MYSETTINGSNETWORKNAME
</pre>

none of these are MY_SETTINGS_NETWORK_NAME, so that's the first problem.  I need the HYPHEN_TO_UNDERSCORE and PERIOD_TO_UNDERSCORE manipulations to both get applied, or a new HYPHEN_AND_PERIOD_TO_UNDERSCORE manipulation created.  I can probably do this in a pull request.

The second problem, and the reason MYSETTINGSNETWORKNAME environment variable doesn't work, is that RelaxedDataBinder.getPropertyValuesForNamePrefix() has this line:
<code>if (name.startsWith(candidate)) {</code>
and the candidates are fetched by doing <code>new RelaxedNames(this.prefix)</code> and this.prefix is "my-settings." - it also has both the dash and the dot, and the resulting candidates are:

<pre>
my-settings.
my_settings.
my-settings_
mySettings.
mysettings.
MY-SETTINGS.
MY_SETTINGS.
MY-SETTINGS_
MYSETTINGS.
</pre>

none of these are just "MYSETTINGS"

I am not sure what would be the best way to fix this part of it.

**Comment by philwebb** [comment]
Can you specify your prefix using `@ConfigurationProperties(prefix = "my.settings")` then rely on the `RelaxedNames` conversion to bind the dashed variant?

**Comment by uTestMichaelL** [comment]
Thank you for the suggestion.  You're right, it does work keeping the prefix "my.settings", but then actually using "my-settings" in properties files which looks nicer.

Would be nicer though if "my-settings" prefix worked too, to match what is in properties file

**Comment by uTestMichaelL** [comment]
Actually, I take that back.  See my related issue #2496

The networkName gets bound properly, but if I have another property like:
my-prefix.login-url=${my-prefix.network-name}/login

Then my-prefix.login-url doesn't get set properly from the environment variable value.

Sorry if this is starting to sound confusing.

**Comment by snicoll** [comment]
Thanks for the example, we'll tackle that in #4910
