### ISSUE TITLE
Provide configuration properties for Flyway's Vault and Conjur support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24969]
https://github.com/flyway/flyway/issues/3060 has been fixed so when we upgrade to a new 7.5.x release, it should be possible to test that Vault and Conjur-related settings have been applied correctly.

**Comment by wilkinsona** [comment]
This is no longer blocked. 7.5.2 has been released with the required changes.

**Comment by snicoll** [comment]
Closing in favor of PR #25456
