### ISSUE TITLE
Test that our property defaults align with Cassandra's defaults

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24965]
See https://github.com/spring-projects/spring-boot/issues/24189#issuecomment-764758231 for background. The default values of some of our properties are out of sync with Cassandra's own defaults. We should add some tests to make sure that they're aligned, similar to those that we have for other auto-configuration.

**Comment by izeye** [comment]
This seems to be resolved via #25130.

**Comment by wilkinsona** [comment]
Indeed it is. Thanks, @izeye.
