### ISSUE TITLE
Add auto-configuration for Micrometer's Dynatrace v2 meter registry

### ISSUE THREAD

**Issue by damass** [spring-projects/spring-boot#24978]
See related Issue & PR :  
     https://github.com/micrometer-metrics/micrometer/issues/2295
     https://github.com/micrometer-metrics/micrometer/pull/2406

With the hopeful addition of the new Micrometer Dynatrace v2 Meter Registry, it will be necessary to add an additional Auto Configuration for it to this project in order to utilize it. This will allow users to add in the necessary application properties needed for dynatrace2 to send metrics to Dynatrace. 

I do have a working example for this, but cannot submit a PR as the micrometer PR is still open (as of 2021/22/1) and the required dependency would cause the build to fail.

**Comment by damass** [comment]
Here is the relevant branch : https://github.com/damass/spring-boot/tree/add-autoconfig-for-micrometer-dynatrace2/spring-boot-project

**Comment by philwebb** [comment]
Thanks. I've marked this one as "blocked" and subscribed to the Micrometer issues.

**Comment by jonatan-ivanov** [comment]
fyi: The changes were merged to micrometer: https://github.com/micrometer-metrics/micrometer/pull/2619

**Comment by snicoll** [comment]
Closing in favor of PR  #26258
