### ISSUE TITLE
duplicate HttpMessageConverters when getMessageConverters() is called

### ISSUE THREAD

**Issue by BigMichi1** [spring-projects/spring-boot#24972]
we had a serious issue with some custom HttpMessageConverters so we debugged a little bit the code and had one observation that doesn't look correct. This behaviour is also present when a plain spring boot application is created by using https://start.spring.io/ and only selecting "Spring Web" dependency.
(choosing Maven, Java, SpringBoot 2.4.2 and Java 15) 

The thing is that when we had a breakpoint in `WebMvcConfigurationSupport` in method `getMessageConverters()` at the return statement, we have seen that this list contains some duplicates which are also configured differently.

The first call we have seen was initiated by the `HttpMessageConverters` constructor -> this list does not contain any duplicate
![Screenshot_20210122_135950](https://user-images.githubusercontent.com/91786/105493790-2509be00-5cba-11eb-9763-879bc4379401.png)

then an additional call is coming from `requestMappingHandlerAdapter()` method in `WebMvcConfigurationSupport` and this list then contains duplicates
![Screenshot_20210122_140201](https://user-images.githubusercontent.com/91786/105494027-774adf00-5cba-11eb-929e-2da8130df27b.png)

here we see that we have two instances of `StringHttpMessageConverter`, when we inspect the details we see that they are configured differently
![Screenshot_20210122_140401](https://user-images.githubusercontent.com/91786/105494183-b2e5a900-5cba-11eb-85f7-4f1e5bf7228c.png)

the suspicious part here is probably the `HttpMessageConverters` constructor which gets these two duplicates as an argument and then combine these with the default converters
![Screenshot_20210122_140704](https://user-images.githubusercontent.com/91786/105494679-71a1c900-5cbb-11eb-834e-47c2a89be5ca.png)

**Comment by bclozel** [comment]
Could you take a look at #21374 first (and linked issues) and report back?

We're always interested in optimizing things but I'm not sure we can do that here.

**Comment by BigMichi1** [comment]
yes it's a duplicate of #21374, sry
