### ISSUE TITLE
Extend HttpSessionEventPublisher to propagate HttpSessionIdListener events.

### ISSUE THREAD

**Issue by mahairod** [spring-projects/spring-boot#24985]
As additional funcvtionality for #24879  it's convenient to add support for propagating of session id changes to spring context. It's possible through the same HttpSessionEventPublisher used for session creation and destroy events. It's also necessary to add another HttpSessionEvent reflecting new type of event.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, I'm not sure that I have understood what you are proposing we do in Spring Boot. Spring Security's `HttpSessionEventPublisher` is already an `HttpSessionIdListener` and, in response to a `sessionIdChanged` callback, it will publish a `HttpSessionIdChangedEvent`. This functionality was [added](https://github.com/spring-projects/spring-security/commit/5fc6414377aea64953c2ecf57bb7101d052fa772) in Spring Security 5.4.

**Comment by mahairod** [comment]
Oh, sorry! My bad. I missed that functionality because it became available just few months ago.

**Comment by mahairod** [comment]
Already present
