### ISSUE TITLE
Further support of CNCF buildpacks (--buildpack= for example)

### ISSUE THREAD

**Issue by anthonydahanne** [spring-projects/spring-boot#24983]
Hello Spring Boot team,
I understand the support for the `pack` specification is still new (2.3 if I'm correct), but I was wondering what was the plan wrt to the several options that could be added to configure a CNCF buildpack builder.

For example, the default builder that Spring Boot uses is `docker.io/paketobuildpacks/builder:base`, and one can override it with `-Dspring-boot.build-image.builder=gcr.io/mycustom/builder:0.1`

That's nice, but what would be even nicer, would be to add, for example, other `pack` CLI options, such as `--buildpack`:

```
pack build demo:0.0.1-SNAPSHOT --builder=docker.io/paketobuildpacks/builder:base  --buildpack=paketo-buildpacks/ca-certificates,gcr.io/paketo-buildpacks/adopt-openjdk,paketo-buildpacks/maven,paketo-buildpacks/executable-jar,paketo-buildpacks/apache-tomcat,paketo-buildpacks/dist-zip,paketo-buildpacks/spring-boot --clear-cache
```

In the above example, I could successfully swap the Bellsoft Liberica JDK with AdoptOpenJDK .

I've looked at https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/Image.java and I could see several `pack` cli options there; just wondering what was the plan to add them all (or not)

Thank you!

**Comment by scottfrederick** [comment]
There are separate issues to add options for parity with the `pack` CLI. See #21722 and #23518 for examples. If there are other `pack` options you would find useful, feel free to open issues for those also. In cases like this we prefer small discrete issues (i.e. one for each new option).

**Comment by anthonydahanne** [comment]
Hello @scottfrederick  !
Thanks for your answer - yes, those 2 issues are definitely the 2 features of `pack` CLI that I wanted to have from the Spring Boot maven plugin.
