### ISSUE TITLE
Document how to use cloudfoundry specific actuators with a custom base path for webflux applications

### ISSUE THREAD

**Issue by mcordeiro73** [spring-projects/spring-boot#24991]
This issue is similar to #9081.  When setting the `spring.webflux.base-path`, the Cloudfoundry specific actuators are also set under the configured base-path.  

Looking for a workaround that allows the property to be set while relocating or redirecting the expected Cloudfoundry requests to the appropriate Actuators.

**Comment by mbhave** [comment]
We documented this as a known limitation for the servlet case and we should do the same for the webflux case.
