### ISSUE TITLE
Spring boot plugin at least since version 2.3.8.RELEASE included 2.4.2 that brokes badly IDE Apache Netbeans

### ISSUE THREAD

**Issue by netbeansuser2019** [spring-projects/spring-boot#25009]
Refers https://issues.apache.org/jira/browse/NETBEANS-5293

Handling of project dependencies in gradle multiproject seems changed from 2.2.13.RELEASE in 
as it is seen a project resolving issue in Apache Netbeans IDE it is needed to 
explicitly specify a "configuration" on project dependencies in context of:
https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#N1748D

It is not even documented and it is even not clear what configuration is 
the best.

**Comment by netbeansuser2019** [comment]
JDK 11+
Gradle 6.8.1
Spring Boot 2.3.8 and 2.4.2 (so plugin 'org.springframework.boot')

**Comment by wilkinsona** [comment]
Thanks for the report but tracking the same problem in two different places is likely to result in wasted effort. I'll keep an eye on the NetBeans issue and will help if there's anything to be done on the Spring Boot side.
