### ISSUE TITLE
 Upgrade to Spring Data 2021.0.0-M4

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25004]

**Comment by philwebb** [comment]
Commit 4b0ef67e8e8e61a1bbe91e1f0749fbcf98f1a5ab could do with a review (relates to #24525)

**Comment by mp911de** [comment]
Project Dependencies Spring Data 2021.0.0-M3

* Cassandra Driver (com.datastax.oss:java-driver-core): 4.10.0
* [Couchbase Client (com.couchbase.client:java-client): 3.1.2](https://github.com/spring-projects/spring-data-couchbase/issues/1079)
* [Elasticsearch (org.elasticsearch.client:elasticsearch-rest-high-level-client): 7.11](https://github.com/spring-projects/spring-data-elasticsearch/issues/1687)
* Jedis (redis.clients:jedis): 3.5.1
* Lettuce (io.lettuce:lettuce-core): 6.1.0.M1
* [MongoDB (org.mongodb:mongodb-driver-core): 4.2.0-beta1 (GA scheduled for March)](https://github.com/spring-projects/spring-data-mongodb/issues/3553)
* Neo4j Driver (org.neo4j.driver:neo4j-java-driver): 4.1.1
* Spring LDAP (org.springframework.ldap:spring-ldap-core): 2.3.3.RELEASE
