### ISSUE TITLE
Upgrade to Spring Data 2020.0.5

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25002]

**Comment by mp911de** [comment]
Project Dependencies Spring Data 2020.0.4

* Cassandra Driver (com.datastax.oss:java-driver-core): 4.9.0
* Couchbase Client (com.couchbase.client:java-client): 3.0.10
* Elasticsearch (org.elasticsearch.client:elasticsearch-rest-high-level-client): 7.9.3
* Jedis (redis.clients:jedis): 3.3.0
* Lettuce (io.lettuce:lettuce-core): 6.0.2.RELEASE
* MongoDB (org.mongodb:mongodb-driver-core): 4.1.1
* Neo4j Driver (org.neo4j.driver:neo4j-java-driver): 4.1.1
* Spring LDAP (org.springframework.ldap:spring-ldap-core): 2.3.3.RELEASE

**Comment by wilkinsona** [comment]
There are some [breaking changes](https://github.com/spring-projects/spring-data-couchbase/commit/883c931cf419f91f12ba93786e1f293f77bc7467) in the Couchbase module so this may become a 2020.0.5 upgrade.

**Comment by wilkinsona** [comment]
We should revert a91f32d14e9767491f8a0bd63fdba8ae1a1f8fc7 once the breaking change in the Couchbase module has been reverted.
