### ISSUE TITLE
Auto-configuration for P6Spy/Datasource Proxy/FlexyPool

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-projects/spring-boot#25032]
Background:
- https://github.com/spring-projects/spring-boot/issues/7863
- originally: https://vladmihalcea.com/2016/05/03/the-best-way-to-log-jdbc-statements
- @marcingrzejszczak @shakuzen and myself are thinking of ways providing more observability support for the users that are auto-configured for them and we are discussing about merging [spring-boot-data-source-decorator](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator) maintained by @gavlyukovskiy into Spring Boot and Spring Cloud Sleuth

What do you think, can we come back to this discussion?

**Comment by gavlyukovskiy** [comment]
I'd be happy to prepare PR

**Comment by philwebb** [comment]
Sorry for the delay in replying to this one. We've been discussing a few options internally. For now, we think it's best that `spring-boot-data-source-decorator` remains as a separate project. Thanks anyway for the PR offer @gavlyukovskiy.

Depending on future efforts, it might be possible that we'll want to offer some nicer APIs for the hook points that `spring-boot-data-source-decorator` uses. These might end up in Spring Boot, or possibly even higher in the stack. We can reconsider those on a case-by-case basis.
