### ISSUE TITLE
Register logging system's shutdown hook by default

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25046]
The discussion in #24507 makes me think that we should consider enabling the property by default. Whilst the arguments in #4026 are still valid, they aren't really typical Spring Boot deployments.

**Comment by wilkinsona** [comment]
I think it makes sense to flip the default now.

**Comment by wilkinsona** [comment]
When flipping the default, it'd be nice to disable it automatically in a war deployment. We already disable the application's shutdown hook in `SpringBootServletInitializer`.

**Comment by wilkinsona** [comment]
We're going to try setting something via the servlet context in the web application case to disable the shutdown hook.
