### ISSUE TITLE
javax.persistence.schema-generation.database.action may be ignored

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#25054]
Either `javax.persistence.schema-generation.database.action` or `hibernate.hbm2ddl.auto` can be used to control schema creation when using Hibernate, with the latter property taking precedence over the former.

When `HibernateDefaultDdlAutoProvider` determines that the default should be `create-drop`, `hibernate.hbm2ddl.auto` is set with that value. Due to the Hibernate property taking precedence, if the user has set `javax.persistence.schema-generation.database.action` it is now ignored.

When checking for a user-provided setting before configuring the default setting, I think we need to consider `javax.persistence.schema-generation.database.action` as well as `hibernate.hbm2ddl.auto`.

**Comment by snicoll** [comment]
Closing in favor of PR #25129
