### ISSUE TITLE
Group JDBC-related batch properties beneath spring.batch.jdbc

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-boot#25053]
As of v2.4.2, JDBC-related properties for batch are under `spring.batch`, unlike quartz, session and integration where those properties are under `spring.xxx.jdbc`.

After discussing this with @wilkinsona , I understand that this is because JDBC is currently the only store option for batch. However, I think it would be better to group those properties beneath `spring.batch.jdbc` for 1) naming consistency and 2) to pave the way for other storage options for batch in the future (We have indeed a feature request to support a non-jdbc job repository implementation, see https://github.com/spring-projects/spring-batch/issues/877 which we might consider in the next major release).

**Comment by chaundhyan** [comment]
@benas, @wilkinsona 
If allowed, may I take this enhancement ahead, please?
If you guys agree, please assign this to me.

Thanks

**Comment by wilkinsona** [comment]
Thanks for the offer, @chaundhyan. That would be great. We'll need to deprecate the existing properties (using `@DeprecatedConfigurationProperty` and then provide replacements in the new `spring.batch.jdbc.` location. Please let us know if you have any questions.

**Comment by chaundhyan** [comment]
@benas @wilkinsona : I've had done the changes. Would you like to review it over my repo?
[My Change Comparison](https://github.com/spring-projects/spring-boot/compare/master...chaundhyan:master)

Shall i raise the PR, if yes then into which branch? 
I've had taken a fork and pushed changes into main branch over my forked repo.

If any suggestion, please do let me know.

Also there exists 3 test cases which are failing while doing `./gradlew build`. But they are passing individually.
JettyReactiveWebServerFactoryTests. whenServerIsShuttingDownGracefullyThenNewConnectionsCannotBeMade()
              org.springframework.web.reactive.function.client.WebClient was not fulfilled within 30 seconds.

Same way other are failing.
NettyReactiveWebServerFactoryTests. whenServerIsShuttingDownGracefullyThenNewConnectionsCannotBeMade()
TomcatReactiveWebServerFactoryTests. whenServerIsShuttingDownGracefullyThenNewConnectionsCannotBeMade()

Please suggest.

Thanks
Mukul Kumar Chaundhyan

**Comment by wilkinsona** [comment]
@chaundhyan Yes, please do raise a PR. One change that I would make to your proposal is to nest `BatchJdbcProperties` inside `BatchProperties` and rename it to `Jdbc`. `BatchProperties` should then have a `Jdbc jdbc = new Jdbc()` field and a getter method.

**Comment by snicoll** [comment]
Closing in favor of PR #25316
