### ISSUE TITLE
Actuator not working properly for spring.config.activate.on-cloud-platform=kubernetes

### ISSUE THREAD

**Issue by sandeep540** [spring-projects/spring-boot#25063]
When I enable the property

`spring.config.activate.on-cloud-platform=kubernetes`

The actuator endpoint is not working properly and not picking up entries from application.properties

like 
`management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers,env,startup`

This is happening in Spring boot 2.4.2, JDK 11

**Comment by wilkinsona** [comment]
Without knowing exactly how you're using `spring.config.activate.on-cloud-platform`, where you have configured `management.endpoints.web.exposure.include`, and how you are deploying your application, I don't think there's enough information here to diagnose the problem.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
