### ISSUE TITLE
Stop publishing spring-boot-docs to Maven central

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25086]
Seem like something changed in 2.4.x that means we now have POMs uploaded to maven central. See https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-docs/2.4.2/

**Comment by garyrussell** [comment]
Looks like the change was in 2.3.x; earlier versions published the whole module including jar and sources https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-docs/2.2.9.RELEASE/
