### ISSUE TITLE
Spring Boot 2.3.8; Spring 5.3.3; NoSuchMethodError resourceHandlerMapping()

### ISSUE THREAD

**Issue by bhattankit** [spring-projects/spring-boot#25088]
Hi Team

I just upgraded to SpringBoot 2.3.8 and Spring 5.3.3. I noticed that SpringBoot 2.3.8 adds an overriden resourceHandlerMapping() method at https://github.com/spring-projects/spring-boot/blob/v2.3.8.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L405. 

With Spring 5.3.3, the signature of https://github.com/spring-projects/spring-boot/blob/v2.3.8.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L408 has changed causing a NoSuchMethod Error.

Is Boot 2.3.8 not compatible / officially supported with Spring 5.3.3?

On a side note - where can I find a compatibility matrix for Spring / SpringBoot versions?

Thanks
Ankit

**Comment by philwebb** [comment]
Spring Boot 2.3.x is build against Spring Framework 5.2. You can use the `spring-boot-dependencies` BOM to ensure you're using the correct version. The reference documentation includes a section that lists the versions of all dependencies (https://docs.spring.io/spring-boot/docs/2.3.x/reference/htmlsingle/#dependency-versions).

If you want to use Spring Framework 5.3, please upgrade to Spring Boot 2.4.

**Comment by bhattankit** [comment]
@philwebb -- Thank you for the quick response. One of the issues with upgrading to 2.4 is that we are using spring-cloud-zuul and are on Hoxton SR9. At this time, Hoxton only supports Boot 2.3. Do you know if there are plans for Hoxton to support 2.4 as well?

**Comment by philwebb** [comment]
@bhattankit I think you'd need to upgrade to Spring Cloud 2020.0. @spencergibb will be able to answer for sure.

**Comment by spencergibb** [comment]
There are no plans to have Hoxton support boot 2.4 as there were breaking boot apis
