### ISSUE TITLE
TestRestTemplate exchange triggers UnsupportedOperationException in RequestEntity

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#25097]
In Boot 2.4.2, both overloads of `TestRestTemplate#exchange` that accept `RequestEntity` call `getUrl` on it. When the `RequestEntity` has been initialized with a URI template instead of a `java.net.URI`, this triggers an `UnsupportedOperationException`.

```java
var req = RequestEntity.get("http://localhost/helloworld").build();
var resp = testRestTemplate.exchange(req, String.class);
```

Internally, the real `RestTemplate` dispatches based on the concrete type of `RequestEntity`, but `TestRestTemplate` fails to check.

see spring-projects/spring-framework#26500

**Comment by wilkinsona** [comment]
It looks like we must be missing some tests. I think this change in behaviour is due to [this change](https://github.com/spring-projects/spring-framework/commit/a0f4d81db76cb100b8f0da3a3cc8a945a012a2c0) that was made in Framework 5.3.0.M1.
