### ISSUE TITLE
About logback can't read bootstrap config server

### ISSUE THREAD

**Issue by 514190950** [spring-projects/spring-boot#25091]
Hello,I use logback-spring.xml  like 
```xml
<springProperty scope="context" name="logFilePath" source="logging.file.path"/>
```
but the property in the Nacos config 
I get nacos in bootstrap lifecycle, logback to read the property twice;
causing a problem for create a "XXX_IS_UNDEFINED" dirtionary 
what should i do?

**Comment by wilkinsona** [comment]
The problem should be solved in Spring Cloud 2020.0 and Spring Boot 2.4 where the new config data support allows remote configuration to be used without the bootstrap context. Please upgrade and see if that resolves it. If it does not and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by 514190950** [comment]
thank you for your answer. can I do something about the problem to springboot version 2.2.4.    
I am quite willing to do something If there is a solution

**Comment by wilkinsona** [comment]
>  can I do something about the problem to springboot version 2.2.4.

No, I don't think so. It's a limitation of the bootstrap context approach in Spring Cloud. There's a chicken and egg problem with the context making remote configuration available for use while also trying to use that configuration to initialise its logging.

As far as I know, upgrading to Spring Boot 2.4 and Spring Cloud 2020.0 is your best option. An upgrade from 2.2.4 is recommended anyway is Spring Boot 2.2.x has [reached the end of its open source support period](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#released-versions).

**Comment by 514190950** [comment]
https://github.com/spring-projects/spring-boot/issues/25091#issuecomment-772351132
Thank you very much. It's ready to close
