### ISSUE TITLE
Remove the use of Bintray from release pipeline

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#25107]
Hi,

I think Boot might be affected by the Bintray shutdown announced here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I guess mostly the release scripts flow needs to be addressed. Feel free to close this if Boot is not affected, of course.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
We're affected and have started looking at what we'll need to do to update our release process. The largest unknown at the moment is publishing our Gradle plugin to the Plugin Portal. We rely on Bintray for that at the moment and there's no alternative that fits with our current release process.
