### ISSUE TITLE
Use consistent asciidoctor subs attribute

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25101]
Our source blocks currently have a mix of different subs, with many not defining them at all. We should try to be consistent.

**Comment by robert-smith-911** [comment]
Just curious @philwebb , what do you mean by subs?

**Comment by philwebb** [comment]
@robert-smith-911 

We have a few imports that declare them:

```
[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
include::{code-examples}/context/embedded/TomcatServerCustomizerExample.java[tag=configuration]
----
```

And a lot more that don't

**Comment by robert-smith-911** [comment]
@philwebb Something I can look at?

**Comment by philwebb** [comment]
Thanks for the offer, but it's probably best if we tackle as part of #6313
