### ISSUE TITLE
file name too long!!!!!

### ISSUE THREAD

**Issue by JasonYan025** [spring-projects/spring-boot#25102]
# Enhancement
when i use git download the code,but its always fail.because!!!
filename was over win10 max filename length.
**spring-boot\spring-boot-project\spring-boot-tools\spring-boot-gradle-plugin\src\test\resources\org\springframework\boot\gradle\tasks\buildinfo\
BuildInfoIntegrationTests-notUpToDateWhenExecutedTwiceWithFixedTimeAndChangedGradlePropertiesProjectVersion.gradle**
please check it. thk.
![image](https://user-images.githubusercontent.com/24384111/106841361-ed007300-66dc-11eb-9e8e-6283c2b3af86.png)

**Comment by Soontao** [comment]
try this: 

```bash
git config --system core.longpaths true
```

**Comment by wilkinsona** [comment]
Thank you, @Soontao.

@JasonYan025, this configuration setting is [described in the contributing guidelines](https://github.com/spring-projects/spring-boot/blob/0e326d6b0f35b3ab311d7e4eb14c44049f088897/CONTRIBUTING.adoc#cloning-the-git-repository-on-windows).
