### ISSUE TITLE
Help: run failed in IDEA, because of "Unrecognized option: --add-modules Error: Could not create the Java Virtual Machine."

### ISSUE THREAD

**Issue by sluk3r** [spring-projects/spring-boot#25111]
I want to run unit test in IDEA and fix some bugs, but failed because of "Unrecognized option: --add-modules Error: Could not create the Java Virtual Machine."

In IDEA console, I find the following config: 

![image](https://user-images.githubusercontent.com/6405801/106975503-a3be2b00-6791-11eb-9e74-ce4fc53cafa8.png)

I wonder, is it ok to remove the config of "--add-modules",  and how to remove it.

**Comment by scottfrederick** [comment]
It is not clear from the information you've provided how Spring Boot is involved in this issue. If you think this is a Spring Boot problem, please provide a minimal sample that reproduces the problem. You can attach a zip to the issue or provide a link to a GitHub project.

**Comment by snicoll** [comment]
`-add-module` is a Java 9+ option and you're running your tests with Java 8. Spring Boot isn't involved in that in any way, please review your IDE configuration.
