### ISSUE TITLE
Update link in spring boot 2.0 migration guide

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#25114]
The wiki page https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide has a link to my blog:

> Alternatively, this blog post by @wimdeblauwe provides a different approach that saves the two step upgrade.

The link should be updated to:

https://www.wimdeblauwe.com/blog/2018/2018-08-30-tip-on-migration-to-spring-boot-2-when-using-flyway/

There is currently a redirect in place, but that redirect will go away in a few weeks and the link would be broken.

**Comment by wilkinsona** [comment]
Thanks, Wim. I've updated the link.
