### ISSUE TITLE
Missing `spring-boot.version`

### ISSUE THREAD

**Issue by robertsearle** [spring-projects/spring-boot#25123]
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom has the property `<spring-boot.version>2.3.3.RELEASE</spring-boot.version>`.   https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.4.RELEASE/spring-boot-dependencies-2.3.4.RELEASE.pom does not.

This is important since some projects use a `spring-cloud-starter-parent` and don't know which version is included.   Can this value be added back to future releases 2.4.X?

**Comment by wilkinsona** [comment]
I'm afraid not, no. Its inclusion was accidental. Please see https://github.com/spring-projects/spring-boot/issues/23174 for details. To see a complete view of your project's dependency management, including that inherited from a parent, you can use `mvn help:effective-pom`.
