### ISSUE TITLE
spring-boot-actuator Metric should not use java.util.Date

### ISSUE THREAD

**Issue by CodingFabian** [spring-projects/spring-boot#2513]
Hi,
I know this might be difficult to get out, as this is kind-of API, but `org.springframework.boot.actuate.metrics.Metric` uses `java.util.Date` to record timestamps.
This is a huge waste of memory and CPU time, as `Date` might be among the most inefficient data structures due to the way it deals with time zones.
The fact that this is created on every call doesn't look too promising.

Shouldn't it be possible to use for example `System.currentTimeMillis()` and let the readers decide if they want to format it with timezone?

**Comment by dsyer** [comment]
Using a Long is probably a good idea. It will have to wait until 1.3 or 2.0 though because of the API change. Pull requests welcome (work on 1.3 will be starting soon).

**Comment by chrylis** [comment]
@CodingFabian Can you explain exactly what you mean by "dealing with time zones"? `java.util.Date`. at least in OpenJDK, simply wraps a `long` when using the non-deprecated constructors, and all of the methods that invoke calculations are the ones that are deprecated in favor of `Calendar`; everything else is simply a `long` comparison. Moving from a strongly-typed to a weakly-typed value for a metric seems like overly aggressive optimization.

**Comment by dsyer** [comment]
Actually the "main" API for users is `GaugeService` and `CounterService` which don't use `Date` so there is no change necessary. But the implementation details are quite different so I think it will be a 1.3 change still.

**Comment by CodingFabian** [comment]
thank you @dsyer ! ended up being a large change, but it looks good and your tests prove that its much more efficient.

**Comment by dsyer** [comment]
The change for taking `java.util.Date` out of the write pipeline was pretty small actually (TL;DR you just need to use Java 8). That PR ended up with a huge amount of other features.
