### ISSUE TITLE
Update CassandraDataAutoConfigurationIntegrationTests to move away from deprecated properties

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#25148]
The property was deprecated in 2.3.x (see https://github.com/spring-projects/spring-boot/issues/19673) and has now been removed in 2.5.x. This means that we have a test in 2.5.x that is setting a property that no longer has any effect. We should update the tests in 2.3.x and later so we're not using a deprecated/removed property.

**Comment by snicoll** [comment]
`spring.data.cassandra.read-timeout` is affected the same way.
