### ISSUE TITLE
Disabling endpoints should not make them return a json document

### ISSUE THREAD

**Issue by axelfontaine** [spring-projects/spring-boot#2514]
Currently a disabled endpoint returns a familiar message giving away the fact the app is built using Spring Boot.

It would be nice if the json document being returned could be suppressed.

**Comment by wilkinsona** [comment]
This is Spring Boot's standard error handling, i.e. the response you're seeing is the standard 404 response that's returned to a machine client. See the [error handling section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-error-handling) for details on how to change the contents of the response.
