### ISSUE TITLE
SpringApplicationContextLoader does not detect default XML config files or Groovy scripts

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#2516]
`SpringApplicationContextLoader.processContextConfiguration(ContextConfigurationAttributes)` currently only supports detection of default `@Configuration` classes.

Since `SpringApplicationContextLoader` is a hybrid context loader with support for annotated classes, XML configuration files, and Groovy scripts as _sources_ for the `SpringApplication`, the loader should auto-detect defaults for all supported types just like the core behavior of the Spring TestContext Framework. This should be achievable by making the following (untested) changes.

	@Override
	protected String[] getResourceSuffixes() {
		return new String[] { "-context.xml", "Context.groovy" };
	}

	@Override
	protected String getResourceSuffix() {
		throw new UnsupportedOperationException(
			"SpringApplicationContextLoader does not support the getResourceSuffix() method");
	}

	@Override
	public void processContextConfiguration(ContextConfigurationAttributes configAttributes) {
		super.processContextConfiguration(configAttributes);

		// Neither XML nor Groovy default detected?
		if (!configAttributes.hasResources() && isGenerateDefaultLocations()) {
			Class<?>[] defaultConfigClasses = detectDefaultConfigurationClasses(configAttributes
					.getDeclaringClass());
			configAttributes.setClasses(defaultConfigClasses);
		}
	}

**Comment by sbrannen** [comment]
Thanks, @philwebb!

**Comment by sbrannen** [comment]
FYI: `!configAttributes.hasResources()` is logically equivalent to `!configAttributes.hasLocations() && !configAttributes.hasClasses()`. :wink:

**Comment by philwebb** [comment]
Reopen to polish as suggested above
