### ISSUE TITLE
Adding a Property Source at runtime

### ISSUE THREAD

**Issue by sincang** [spring-projects/spring-boot#2517]
Hi, 

When my application deployed in production, my company has an API that connects to the Password Vault system to get the passwords. This means that all our production passwords are kept in that vault system. Now, during start-up of the Boot enviroment, I would like to replace the values(passwords) from my application.properties. I am thinking of creating an instance of MapPropertySource then using an ApplicationListener, I will add it in the property sources with the first priority.

Any thoughts?

Thanks,
sincang

**Comment by snicoll** [comment]
Did you have a look to the [Spring Cloud config server](https://github.com/spring-cloud-samples/configserver) already? This may give you a few ideas.

**Comment by dsyer** [comment]
It's actually the [config client](https://github.com/spring-cloud/spring-cloud-config/tree/master/spring-cloud-config-client) that you would need to look at, and it is implemented in pretty much the way you describe though (a listener in Spring Boot).

**Comment by sincang** [comment]
It worked. I added a new PropertySource using the addFirst method. Love the PropertySources concept. It provides flexibility.

**Comment by wilkinsona** [comment]
Good stuff. Glad to hear you got things working.
