### ISSUE TITLE
Document ServletListenerRegistrationBean

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#2518]
Related #1537

**Comment by dsyer** [comment]
You don't need a registration bean for listeners (and it's documented here: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-add-a-servlet-filter-or-servletcontextlistener). Maybe one more sentence to mention that there is a registration bean would help?

**Comment by rwinch** [comment]
I think the main thing is that scanning the whole document there was no mention of HttpSessionListener. Your commit addresses this. Thanks.
