### ISSUE TITLE
RedisAutoConfiguration exception due to typo in @Bean annotation name attribute

### ISSUE THREAD

**Issue by zyro23** [spring-projects/spring-boot#2521]
trying to run a boot app with a `spring-data-redis` dependency, i am seeing:
```
java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.redis.RedisAutoConfiguration#redisProperties due to internal class not found. [...]
```
thrown here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/redis/RedisAutoConfiguration.java#L61

issue seems to be that it says:
```java
@Bean(name = "org.springframework.autoconfigure.redis.RedisProperties")
```
which should be, i think (missing "boot" package):
```java
@Bean(name = "org.springframework.boot.autoconfigure.redis.RedisProperties")
```
thanks, zyro

update: hmm - on a second look thats only the bean name isnt it? so that could perhaps be changed to include "boot" but it does not look like the cause of the exception i am seeing.

**Comment by zyro23** [comment]
tracked this down to a `java.lang.NoClassDefFoundError: org/springframework/data/redis/connection/RedisSentinelConfiguration`. that class comes with `spring-data-redis-1.4.0` but `spring-session-data-redis` still has a dependency to `spring-data-redis-1.3.0`. and that again seems to be somehow incompatible with `spring-boot-1.2.1`s auto-configuration...

closing this one here. sorry for the noise.
anyways maybe a bit of motivation for @rwinch to bump the dependency? ;)

**Comment by rwinch** [comment]
@zyro23  Thanks for the feedback. The challenge is ensuring that we support old versions of Spring Data along with the new ones. We have some tickets that when completed will allow for testing against the older versions as well. At that point (likely 1.1) I think we will bump the versions up.

**Comment by zyro23** [comment]
sounds good. meanwhile ill try my luck with seperate dependencies for `spring-session-1.0.0.RELEASE` and `spring-boot-starter-redis`.

btw: thanks once again for just-in-time feedback!

**Comment by lhanson** [comment]
I'm experiencing this error on a Spring Boot project with a {{spring-data-redis:jar:1.4.2.RELEASE}} dependency and I'm not clear on what the workaround is. Do I need to include additional artifacts into the project?

**Comment by snicoll** [comment]
Please create a new issue with more details (Spring Boot version, whether you're using spring session or not, etc). This issue is closed. Thanks.
