### ISSUE TITLE
Support for MongoDB 3

### ISSUE THREAD

**Issue by bagerman** [spring-projects/spring-boot#2522]
It looks like MongoDB v3 requires new v3 driver. I was wondering when support for MongoDB v3 is going to be introduced to spring-boot-starter-data-mongodb? Thanks,
Alex

**Comment by wilkinsona** [comment]
That's largely a question for the Spring Data team led by @olivergierke

**Comment by olivergierke** [comment]
The MongoDB 3.0 Java driver has not been released yet. However, we're already working on compatibility with it all ready. Be sure to follow [DATAMONGO-1158](https://jira.spring.io/browse/DATAMONGO-1158) for updates.

**Comment by wilkinsona** [comment]
Thanks, Ollie. @bagerman DATAMONGO-1158 is targeted at the Fowler release train of Spring Data which should be in Spring Boot 1.3.

**Comment by bagerman** [comment]
It appears that DATAMONGO-1158 has been merged to spring-data-mongodb and now a part of the spring-data-mongodb.1.7 but 1.3.0.BUILD-SNAPSHOT still references spring-data-mongo.1.6.2. What is ETA for moving to 1.7 for spring-data-mongo?

**Comment by wilkinsona** [comment]
As I said above, it'll be in Spring Boot 1.3. We don't have any firmer plans than that at the moment.

**Comment by olivergierke** [comment]
Generally speaking, there's no need to be obsessed about the version Spring Boot is currently referencing actually. You can always upgrade to a more recent version of Spring Data libraries by setting the `spring-data-releasetrain.version` property to point to the release train edition you'd like to use. The latest GA release is `Evans-SR2`, if you want to peek into the MongoDB 3 stuff, just use `Fowler-BUILD-SNAPSHOT`. By the time we craft releases for that this will become `Fowler-RC1`, `Fowler-RELEASE` etc.

All this already works on current Boot 1.2.2 already so it upgrading to the latest Fowler stuff is the least important step actually. It of course eventually will, but I just wanted to get across that it is by no means necessary to make Boot generally work with MongoDB 3.0.

**Comment by bagerman** [comment]
Thanks, worked perfectly!

**Comment by olivergierke** [comment]
:+1: :clap:
