### ISSUE TITLE
Filters applied twice to /public/index.html if accessed through http://localhost:8080/

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#2523]
When an `index.html` file is requested as `/`, filters get applied to it twice. This is causing the GzipFilter from ehcache-web to double-gzip it and producing garbage. The problem does not happen if requested as `/index.html`.

Tried with 1.2.2.BUILD-SNAPSHOT.
Github repo for reproduction here: https://github.com/imgx64/test-spring-boot/tree/double-filter-issue

Steps to reproduce:

    git clone https://github.com/imgx64/test-spring-boot
    cd test-spring-boot
    git checkout double-filter-issue
    mvn spring-boot:run

Then in another terminal:

    curl --compressed http://localhost:8080/

Output is garbage.

    curl --compressed http://localhost:8080/index.html

Output is: `<html><head><title>test</title></head><body><p>Hello world</p></body></html>` (the correct output)

**Comment by wilkinsona** [comment]
@imgx64 Thanks for the project that reproduces the issue

**Comment by wilkinsona** [comment]
It's a [bug in EhCache's GzipFilter](https://jira.terracotta.org/jira/browse/EHC-806). Compression occurs once for the request to `/` and again when it's forwarded to `/index.html`.

I'd recommend using Jetty's GzipFilter (we've added [auto-configuration support for it in 1.2.2](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#how-to-enable-http-response-compression)) instead as it's smart enough not to apply compression twice.

**Comment by imgx64** [comment]
@wilkinsona I see, thank you for investigating this.
