### ISSUE TITLE
Auto-configure HikariCP's metrics support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2528]
Inspired by http://stackoverflow.com/questions/28615203/how-do-i-configure-hikaricp-and-dropwizard-coda-hale-metrics-in-spring-boot-appl

**Comment by wilkinsona** [comment]
This is now a Micrometer concern and Hikari 2.7 has alpha support for Micrometer: https://github.com/brettwooldridge/HikariCP/commit/051f78c276ba04beef5419c3eb7bca338f789b7e

**Comment by shakuzen** [comment]
I believe this should be reopened. I was going to make a new issue, but this seems to be the appropriate ticket.

HikariCP has support for Micrometer as an implementation of its `MetricsTracker` (which will be updated to Micrometer GA as part of micrometer-metrics/micrometer#91). What is needed is similar to the auto-configuration of RabbitMQ metrics support. However, Spring Boot 2 snapshots do not currently auto-configure the `MetricsTrackerFactory` on the `HikariDataSource`.

The effect being that the detailed metrics HikariCP can provided are not available.

See https://github.com/brettwooldridge/HikariCP/tree/dev/src/main/java/com/zaxxer/hikari/metrics
