### ISSUE TITLE
Allow @AutoConfigureBefore/After to specify String class names

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2529]
I have a couple of modules that provide independent implementations of an interface, one of which is a fallback for non-production purposes. I'd like to be able to mark the fallback's autoconfiguration class as conditional-on-missing and auto-configure-after the main implementation, but the ordering annotations only take a class literal, and I don't want to have inter-module dependencies.

I would like to be able to specify class names as Strings, equivalent to

    @ConditionalOnMissingBean(type = "my.type.here")

**Comment by philwebb** [comment]
Should be possible by changing `AutoConfigurationSorter$AutoConfigurationClass.getAnnotationValue()`

**Comment by cemo** [comment]
For similar purpose I have implemented `ConditionOnDevelopment` and `ConditionalOnNonDevelopment`. It may be implemented better but I am using a simple class path check. At production I am assuming that there is a single executable jar and classpath includes only it. At development It includes more than one entry and I distinguish environment so.
