### ISSUE TITLE
Document exploded JARs for Docker

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2531]
Mentioned in Gitter:

> Hi everyone. We're using Spring Boot inside docker. Currently, we're baking fat jar inside a container and run it. Everything works fine, but every new commit in container results in a huge container diff since jar is fat. Is it possible to ship Spring Boot applications as "exploded" jar? With "libs" folder. If so, new container commit will contain only changed classes and dependencies, but all previous deps jars (such as Spring Boot itself) will remain the same and resulting container diff will be much thinner

**Comment by sjyun** [comment]
i`m afraid that i can't follow you
do you want to more Effective jar task?
like a shadow
https://github.com/johnrengelman/shadow

**Comment by philwebb** [comment]
Actually, I'm not sure I get this either thinking about it some more. To create a lighter docker image you'd need common libs to be in a higher layer.
