### ISSUE TITLE
@Scheduled method not triggered when spring.main.lazy-initialization=true

### ISSUE THREAD

**Issue by arikanorh** [spring-projects/spring-boot#25315]
Spring Boot Version: 2.4.2
Spring Framework Version: 5.3.3

1. `@EnableScheduling`
2. Create a `@Component` with a `@Scheduled` method
3. Add `spring.main.lazy-initialization=true` to `application.properties`
4. Start application

The method is never called.

**Comment by wilkinsona** [comment]
A general-purpose fix for this would require us to mimic some of the logic in `ScheduledAnnotationBeanPostProcessor`. When scheduling and lazy initialization are enabled, we'd need a `LazyInitializationExcludeFilter` that excludes any bean with a `@Scheduled`- or `@Schedules`-annotated method. That doesn't feel too bad I suppose. The alternative would be to document this as a restriction. Let's see what the rest of the team thinks.

@arikanorh While we're deciding what to do, you should be able to work around the problem with one or more `LazyInitializationExcludeFilter`s of your own. If you know the types that are using `@Scheduled` then you can do something like this:

```java
@Bean
LazyInitializationExcludeFilter lazyInitializationExcludeFilter() {
	return LazyInitializationExcludeFilter.forBeanTypes(TypeWithScheduledMethods.class);
}
```

**Comment by snicoll** [comment]
There are two issues here. The filtering we've described above and the fact our `TaskScheduler` isn't picked up by Spring Framework when it is flagged lazy (as this is the case for all beans in the context when the option is enabled). We're investigating if an issue in Spring Framework is necessary.
