### ISSUE TITLE
Remote devtools endpoint cannot be accessed if actuator and spring security are on the classpath 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#25350]
`managementSecurityFilterChain` does not have an explicit order and will override the `securityFilterChain` in `RemoteDevtoolsSecurityConfiguration`. We should probably order `managementSecurityFilterChain` with `BASIC_AUTH_ORDER`.

**Comment by philwebb** [comment]
Closing in favor of PR #25868
