### ISSUE TITLE
Update auto-configuration classes to return the most specific type possible from @Bean methods

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2536]
`DataSourceTransactionManagerAutoConfiguration` is one example. Its `transactionManager` bean is currently typed as a `PlatformTransactionManager` so if an attempt is made to autowire a `DataSourceTransactionManager` it fails. See [this question](http://stackoverflow.com/questions/28664062/spring-boot-auto-configure-transaction-manager) on StackOverflow, for example. #2403 is another, albeit more complicated, example.

**Comment by snicoll** [comment]
From a purely container perspective, having the most specific type is better because it gives more info to the `BeanFactory`.

**Comment by philwebb** [comment]
+1, we should return the most specific type from `@Bean` methods.
