### ISSUE TITLE
Document how third parties should identify their starters

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2537]
Third parties are creating their own starters and it seems that `spring-boot-starter` is a natural prefix for them. Both activitii and camel have such starters.

Wouldn't it be a good idea for us to "formally" document some aspects of a 3rd party starter? For one, using a different prefix would be a good idea IMO. We could avoid ending up in a situation where we have two [`spring-boot-starter-actuator`](http://mvnrepository.com/artifact/org.activiti/spring-boot-starter-actuator) now.

ping @jbarrez & @hekonsek

Here is what I suggest for what would be wrongly called `spring-boot-starter-xyz`:

* If `xyz` is small enough so that only one starter makes sense, name it `xyz-spring-boot-starter`. After all, all your modules probably start with `xyz` already anyway
* If you have more that one potential starters, just extend the prefix: `xyz-first-spring-boot-starter` - `xyz-second-spring-boot-starter`.

**Comment by dsyer** [comment]
Are you suggesting we just stick it in the user guide somewhere and hope people read it? I guess there's not much else we can do. As far as naming recommendations go, I guess I would expect anything that started with "spring-boot-starter" to be a problem, but not necessarily anything else. I would *expect* that the author of library x would want to use "x-starter-*" or "x-spring-boot-starter-*". Any other suggestions?

**Comment by hekonsek** [comment]
Hi guys,

I named our Camel starter `camel-spring-boot` to follow our Camel component naming convention. However if you create a section in the documentation suggesting that starter for 3rd party project `foo` should be named for example `spring-boot-starter-foo`, then I will change the name of our artifact. A little section in the documentation should be fine :) .

Cheers.

**Comment by dsyer** [comment]
@hekonsek thanks for the update. Actually what I said was we prefer it the way you have it already (if I read yours correctly), i.e. it definitely should *not* be named `spring-boot-starter-foo`.

@jbarrez can yours be renamed, please?

**Comment by hekonsek** [comment]
OK. I'll leave `camel-spring-boot` then. And having a section in documentation explaining the convention would be a nice thing :) .

**Comment by dsyer** [comment]
In Spring Boot there is a difference between "spring-boot-x" and "spring-boot-starter-x" (the starter has no code by convention). I think that might change in 1.3, but we haven't had that discussion yet. Meanwhile, I expect that "camel-spring-boot" probably contains code *and* has curated dependencies, so I think the name looks consistent with our usage. Other people might have other opinions I guess.

**Comment by snicoll** [comment]
anything with `projectName-spring-boot` is fine by me. Honestly the fact that the underlying dependency has code or not is irrelevant. A suffix is only needed if you expect more than one kind so I think `camel-spring-boot` is just fine.

**Comment by jbarrez** [comment]
I don't see any issue renaming the one in Activiti to activiti-spring-boot-starter-x (see https://github.com/Activiti/Activiti/tree/master/modules/activiti-spring-boot/spring-boot-starters for all our starters). It's a maven pom.xml change and a doc changes on our side.

@joshlong : Do you agree? Or was there a particular reason why we've named it like this?

**Comment by dsyer** [comment]
Probably copy-paste error (if I know the way @joshlong works) ;-).

**Comment by philwebb** [comment]
I don't really have an opinion on what other projects use but I think we should add a note saying that we prefer to keep `spring-boot-starter-*` for us.

**Comment by denschu** [comment]
How should we name this starter? -> https://github.com/codecentric/spring-boot-starter-batch-web
There is a lot of code in it :-), but it's not an official starter...

**Comment by wilkinsona** [comment]
@denschu As long as your module's artifact id starts with something other than `spring-boot-starter-` then the Boot team will be happy.

**Comment by joshlong** [comment]
It was just `spring-boot-starter-*` because the `groupId` namespaced it and it is a starter for... Spring Boot.. and the thing represented by the asterisk. `org.activiti.spring`:`spring-boot-starter-rest-api` says to me, 'this is the Spring Boot starter for the Activiti REST API.' Happy to change them, however. cc /  @jbarrez

**Comment by snicoll** [comment]
Gosh, one more :( https://docs.stormpath.com/java/spring-boot-web/quickstart.html#add-the-spring-boot-stormpath-web-starter

```
<dependency>
    <groupId>com.stormpath.spring</groupId>
    <artifactId>spring-boot-starter-stormpath-thymeleaf</artifactId>
    <version>1.0.RC4</version>
</dependency>
```

**Comment by chrylis** [comment]
Is there a strong reason *not* to include autoconfiguration classes in the Spring wrapper jar for some SDK? In my view, since the autoconfig won't activate the unless they're using Spring Boot anyway, no harm done, and for an SDK adapter, it wouldn't be included unless bean registration was clearly wanted.

**Comment by snicoll** [comment]
I have update the doc a bit already but I think a section on "Creating a third party starter" would be in order to mention this and a few extra points such as reserved namespace for configuration keys (Jhipster uses the `spring.*` prefix for instance).

**Comment by snicoll** [comment]
One more https://github.com/allegro/spring-boot-starter-handlebars/issues/4
