### ISSUE TITLE
Extract XML examples from Maven plugin adoc files

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#25376]
The Maven plugin docs have XML snippets inline with the Asciidoc content, which provides no syntax help and makes it much easier to make mistakes in the XML. Extracting the XML snippets into separate files that are included in the adoc files would make it easier to validate the XML.

**Comment by robert-smith-911** [comment]
@scottfrederick Mind if I work on this one?

**Comment by robert-smith-911** [comment]
@scottfrederick Should this apply to all xml snippets in all of the adoc files? Not just maven plugin docs?

**Comment by scottfrederick** [comment]
> Should this apply to all xml snippets in all of the adoc files? Not just maven plugin docs?

This issue should be limited to just the [Maven plugin docs](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/docs/asciidoc). There is a separate effort underway to extract code snippets/samples from the main Boot docs into separate files, so we should keep the efforts separate to avoid conflicts. We can look at extracting the XML from the main docs after the code extraction effort is complete. 

After further discussion, we'd like to use the same approach for including XML snippets that was used to include Gradle build file snippets in the Gradle plugin documentation. For example [this file](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/gradle/packaging/boot-jar-custom-launch-script.gradle) is a fully formed Gradle build file that can be tested, with the [relevant section tagged with comments](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/gradle/packaging/boot-jar-custom-launch-script.gradle#L10-L16). The Asciidoctor [`include` directive references the `tag`](https://github.com/spring-projects/spring-boot/blame/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/asciidoc/packaging.adoc#L246-L248) so that only a portion of the file is included in the documentation. This is a [feature of Asciidoctor ](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/) that can also be used with XML files. 

Following this approach, we'd need to create a fully formed Maven `pom.xml` file for each example in the docs, copy each snippet from the Asciidoctor files to a tagged section in a `pom.xml` file, then include the `pom.xml` files in the adoc files with a tag. The extracted `pom.xml` files should be in a directory structure that mirrors the names of the adoc files that include them, [as was done with the Gradle include files](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/gradle).

@robert-smith-911 Thanks for the offer to work on this. If you're willing to take it on with that scope, we can assign the issue to you. If not, we understand that too.

**Comment by robert-smith-911** [comment]
@scottfrederick That makes the scope so much larger, but sure, you can assign to me, thanks!

**Comment by scottfrederick** [comment]
Thank you @robert-smith-911. We'll just make this change on the `master` branch so I've assigned it to the `2.5.x` milestone.

**Comment by scottfrederick** [comment]
Closing in favor of #25534.
