### ISSUE TITLE
HHH000342: Could not obtain connection to query metadata : Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/db?serverTimezone=EST5EDT

### ISSUE THREAD

**Issue by barrychapman** [spring-projects/spring-boot#25383]
When appending the timezone specifier to a URL, I get the following exception (when using multiple EntityManagers):
```2021-02-22 00:57:22.711  WARN 19220 --- [on(3)-127.0.0.1] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/asa?serverTimezone=EST5EDT```

This does not appear to occur when I remove the ?serverTimezone=EST5EDT.

It also does not occur when using a single entity manager WITH the string appended.

**Comment by snicoll** [comment]
If it does not occur with a single entity manager, then I can only assume that Spring Boot's auto-configuration does something that your manual configuration does not. 

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you believe you've found a bug in Spring Boot, please share a small sample that we can run ourselves that demonstrates the problem. You can do so by attaching a zip file to this issue or sharing a link to a GitHub repository with the project.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
