### ISSUE TITLE
SpringApplication can replace existing default property source

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25408]
See https://github.com/spring-cloud/spring-cloud-commons/issues/892 for background. The [`configurePropertySources`](https://github.com/spring-projects/spring-boot/blob/10ef991e1d932bc9d13b886373831a8cd8df3d3f/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L516) method currently doesn't check if the `environment` already has a `DefaultPropertySource`. It looks like we might need to to merge rather than replace.

**Comment by slyoldfox** [comment]
Thanks for reraising this!
