### ISSUE TITLE
Remove spring-boot-smoke-test-jta-jndi

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#25414]
Hi,

I just noticed that the `spring-boot-smoke-test-jta-jndi` module is kind of orphaned. I think it was a sample in the past with a README on how to deploy the `war`, but the move to smoke tests makes this one less useful if you ask me.

Apparently, it doesn't even have a `build.gradle` anymore these days and before I add one I wanted to discuss if it might make sense to remove the package altogether. After all, adding the build.gradle won't test anything as well.

Let me know what you think.
Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. Unfortunately, I can't remember why I didn't add a build.gradle when porting the build from Maven. Looking back at 2.2.x the module's effectively useless there too as, while there's a pom.xml, there's no test code. I'm in favour of getting rid of it. If we subsequently decide that some JNDI-based testing is required, we can add something to the deployment tests.

**Comment by wilkinsona** [comment]
Closing in favour of #25434.
