### ISSUE TITLE
Add dependency management for postgres

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2545]
We do have a dependency management entry for mysql so we should have one for postgres.

**Comment by philwebb** [comment]
Seems like things aren't quite so easy with Postgress. There are lots of flavors depending on the JDBC version that you are targeting.

http://mvnrepository.com/artifact/org.postgresql/postgresql

**Comment by wilkinsona** [comment]
As with #2448 I'd prefer that we tackle this in 1.3

**Comment by snicoll** [comment]
okay, too bad for the upcoming `start.spring.io` improvement https://github.com/spring-io/initializr/issues/84

**Comment by nek4life** [comment]
+1 for this. I would like to see Postgresql in the list of databases that the spring initializr supports. Especially now that Intellij is adding a new project wizard that works with the initializr service.

**Comment by asaikali** [comment]
Postgres JDBC releases are backward compatible with earlier servers, so you only need to select the latest JDBC driver with Spring Initializer and it will work with earlier versions of postgres. Also for older JDKs it gives the option as to which version of JDBC is implemented, I think the initializer project should default to JDBC 4.1 as that is supported by Java 7 and 8 which are the only two versions of Java supported by the initializer.

The PostgreSQL projects makes a new release of postgres every year but there is a well defined protocol between the Postgres clients and the server which does not really change between releases it is quite stable, this is the protocol that is implemented by the postgres jdbc driver. 

In this case is the current most recent version of the jdbc driver, which should be included with initializer. 
 
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>9.4-1201-jdbc41</version>
</dependency>

@davecramer anything you can add this thread?

**Comment by davecramer** [comment]
Only that I'd like to break the naming convention whereby we are naming the
driver in concert with the server version.

It has caused exactly this kind of confusion.

But to be more helpful. Yes please use the latest driver which is
9.4-1201-jdbc4 or jdbc4.1 depending on jvm version. It will work on any
currently supported version of PostgreSQL which includes 9.0-9.4

Not sure what you do about JVM version though?


Dave Cramer

**Comment by asaikali** [comment]
Dave Cramer is the maintainer of the JDBC Driver for Postgres.

**Comment by dsyer** [comment]
9.4-1201-jdbc41 seems like the right choice (like Tomcat 8 it will work with our preferred JVM and anyone that wants to use JDK 1.6 can do, just by changing the version). I don't really care which Boot version it goes in, but note that is independent of the initializr issue(which has its own issue tracker so please can we keep that debate separate?).

**Comment by snicoll** [comment]
okay, added to Spring Initializr a few days ago. 

@wilkinsona are you ok if I add that version to spring-boot-dependencies or should we keep the dependency only on Spring Initializr?

**Comment by wilkinsona** [comment]
@snicoll I'm happy for this to be added in 1.3. I agree with @dsyer that 9.4-1201-jdbc41 is the version to use.

**Comment by snicoll** [comment]
cool, that's what start.spring.io uses now.
