### ISSUE TITLE
Inconsistent configuration resolution @ConfigurationProperties vs @Value from environment variables

### ISSUE THREAD

**Issue by sandor-nemeth** [spring-projects/spring-boot#25467]
When using `@ConfigurationProperties`, the camelCase variable names are resolved correctly from environment variables when they contain an `_` character between the camelcase parts. 

## Version

The issue was discovered on `2.1.5`, but also confirmed on `2.4.3`.

## Details 

Given an app with a configuration property `props.confValue` in the `application.yml`, if users try to use an the environment value `PROPS_CONF_VALUE` they resolve to different values if they use `@ConfigurationProperties` compared to using `@Value("props.confValue")`.

#### application.yml
```yaml
props:
  confValue: defaultValue
```

#### Using @ConfigurationProperties

```kotlin
@ConfigurationProperties("props")
class ConfigProps {
    var confValue: String? = null
}
```

#### Using @Value

```kotlin
@Component
class AutowiredValueBean() {
    @Value("\${props.confValue}")
    lateinit var confValue: String
}
```

### Test cases:

Starting the app with `PROPS_CONF_VALUE=envValue` results in
- `ConfigProps.confValue` having the value of `envValue`
- `AutowiredValueBean.confValue` having the value of `defaultValue`  

Starting the app with `PROPS_CONFVALUE=envValue` results in
- `ConfigProps.confValue` having the value of `envValue`
- `AutowiredValueBean.confValue` having the value of `envValue`  

A reproduction of the issue can be found [here](https://github.com/sandor-nemeth/spring-boot-config-env-mismatch/blob/master/src/test/kotlin/io/github/sandornemeth/spring/ConfigTest.kt).

**Comment by snicoll** [comment]
Thanks for the sample.

There's a [note in the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-vs-value) about this. Rather than using `props.confValue` you should be using `props.conf-value` so that the same rules apply.
