### ISSUE TITLE
Spring Boot Webflux has blocking calls retrieving static content

### ISSUE THREAD

**Issue by JanVdloock** [spring-projects/spring-boot#25474]
Bug Report
Using Spring Boot 2.4.3 with Webflux, there are blocking calls when getting static resources.
Run on Windows 10 with JDK 11.

A simple program with a static image is added in attachment. It contains a static image and when this image is requested, the call is marked as **blocking** by BlockHound. The problem is that the MediaTypeFactor reads a file from a jar file while handling the request. See test class.

[spring-reactor-webflux-blockhound mediatype.zip](https://github.com/spring-projects/spring-boot/files/6070790/spring-reactor-webflux-blockhound.mediatype.zip)

**Comment by wilkinsona** [comment]
Duplicates #25475.
