### ISSUE TITLE
Default fork value for spring-boot:stop is not consistent

### ISSUE THREAD

**Issue by fabapp2** [spring-projects/spring-boot#25472]
When starting a boot web application on the console through Maven 
`mvn spring-boot:start` 
and then shutting it down 
`mvn spring-boot:stop`
it fails with 
`Spring application lifecycle JMX bean not found (fork is null).`

The documentation states that `fork` is `true` by default which seems not to be the case here.

**Comment by snicoll** [comment]
`spring-boot:stop` uses whatever value was used by the start process. When maven runs, the start goal runs first and then sets the value it has used to start the app. When the stop goal runs later, it reads that value from the context. Therefore, if the application is started with the default settings (or fork=true), then it's trying to stop it as a forked process. If the application is started with fork=false, then it is trying to stop it in the current process. Strictly speaking, the [documentation is accurate in that regard](https://docs.spring.io/spring-boot/docs/2.3.3/maven-plugin/reference/htmlsingle/#goals-stop). It states that the fork has no default value, it doesn't for the reason I've expressed above.

What is particular about your use case is that you're using these goals in isolation. The mechanism I have described above doesn't work. You run maven first, which sets the fork value in the context, then the process exit. Then later one, you fire up a brand new maven process to stop the app that doesn't have the context.

The reason why we have a bug here is that `spring-boot:stop` uses `false` when it doesn't find the fork value that the start process has put in the context. For consistency it should use `true` rather.

**Comment by fabapp2** [comment]
Thanks for your reply Stephane.
Unfortunately the link you added is dead, but the documentation I was reading doesn't state this so clear (at least for me):
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-run-parameters-details-fork
says `default=true` which confused me and seems not to be the case in my (potentially special) scenario.
Your explanation makes sense, TIL.
If the fork is set to false the error message is also kind of misleading as it states `fork is null`.
