### ISSUE TITLE
Document how to configure Maven's Failsafe plugin when not using spring-boot-starter-parent

### ISSUE THREAD

**Issue by McFoggy** [spring-projects/spring-boot#25473]
While migrating an existing application from `2.3.7.RELEASE` to `2.4.3` I faced an issue running integration tests complaining with:

```
java.lang.IllegalStateException: Failed to find merged annotation for @org.springframework.test.context.BootstrapWith(value=org.springframework.boot.test.context.SpringBootTestContextBootstrapper.class)
````

Find attached a very simple & minimal reproducer case.

### Preparation

[spring-reproducer.zip](https://github.com/spring-projects/spring-boot/files/6043007/spring-reproducer.zip)

- `unzip spring-reproducer.zip`
- `cd spring-reproducer`

### OK with 2.3.7.RELEASE
 
- `mvn clean verify`

### Failing with 2.4.3

- `mvn -Dspring-boot.version=2.4.3 clean verify`

using this version of spring-boot the build fails showing the following details in the failsafe-report

````
-------------------------------------------------------------------------------
Test set: com.lectra.spring.ApplicationLoaderTestIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.136 s <<< FAILURE! - in com.lectra.spring.ApplicationLoaderTestIT
com.lectra.spring.ApplicationLoaderTestIT  Time elapsed: 0.136 s  <<< ERROR!
java.lang.IllegalStateException: Failed to find merged annotation for @org.springframework.test.context.BootstrapWith(value=org.springframework.boot.test.context.SpringBootTestContextBootstrapper.class)
````

**Comment by McFoggy** [comment]
Thanks for the analysis and hints.

**Comment by robert-smith-911** [comment]
@wilkinsona Something I can take a look at?

**Comment by wilkinsona** [comment]
Yes please, @robert-smith-911. That'd be great. I think https://docs.spring.io/spring-boot/docs/2.4.2/maven-plugin/reference/htmlsingle/#using-import might be the best place to mention the Failsafe setup, perhaps as a new sub-section.

**Comment by snicoll** [comment]
Closing in favor of PR #25621
