### ISSUE TITLE
Please upgrade to hibernate 5.4.29.Final before releasing 2.5.0-M3

### ISSUE THREAD

**Issue by JohnNiang** [spring-projects/spring-boot#25489]
Please upgrade to hibernate 5.4.29.Final before releasing 2.5.0-M3, @wilkinsona .

The main reason for this is that an useful function is committed  on both sides, so I'm looking forward to the release of Spring Boot 2.5.0-M3.

**Comment by mbhave** [comment]
Thanks but we don't need an issue for dependency upgrades. We have a semi-automated process that upgrades dependencies and we run it before every release.

**Comment by JohnNiang** [comment]
Thank you for reminding me.
