### ISSUE TITLE
.bat generated by gradle plugin exceeds Windows limits

### ISSUE THREAD

**Issue by konrad-garus** [spring-projects/spring-boot#2552]
The .bat file generated by the Gradle plugin includes the following:

```
set CLASSPATH=%APP_HOME%\lib\myapp-0.7.0-SNAPSHOT.jar;%APP_HOME%\lib\spring-boot-starter-jdbc-1.2.1.RELEASE.jar

@rem Execute myapp
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MYAPP_OPTS%  -classpath "%CLASSPATH%" com.example.myapp.Application %CMD_LINE_ARGS%
```

The CLASSPATH includes each and every jar, which in this kind of application can be a fairly long list. Unfortunately, the limit for Windows is pretty low (8kb): http://support.microsoft.com/kb/830473. It means that if you hit certain number of dependencies, running this bat yields the following error on the "set CLASSPATH" line:

> The input line is too long. The syntax of the command is incorrect.

**Comment by konrad-garus** [comment]
It looks like it can be solved by removing the "set CLASSPATH" line altogether, and starting Java with:
```
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MYAPP_OPTS%  -classpath "%APP_HOME%\lib\*" com.example.myapp.Application %CMD_LINE_ARGS%
```

**Comment by wilkinsona** [comment]
Are you referring to the scripts generated by the `startScripts` task?

**Comment by konrad-garus** [comment]
@wilkinsona Yes, these are the scripts.

**Comment by wilkinsona** [comment]
That task is contributed by Gradle's application plugin (which the Spring Boot plugin applies for you), i.e. the problem's in Gradle rather than Spring Boot. See [this thread](http://forums.gradle.org/gradle/topics/gradle_application_plugin_and_cmd_exe_line_size_limitations) on the Gradle forum.
