### ISSUE TITLE
Upgrade to Jetty v9.2.9.v2015022 immediately

### ISSUE THREAD

**Issue by jcayetano** [spring-projects/spring-boot#2554]
Hi,

A critical remote leakage has been disclossed for Jetty 9.2.4 to 9.2.8 where an unauthenticated remote attacker can read arbitrary data from previous requests submitted to the server by other users.

More info:
http://blog.gdssecurity.com/labs/2015/2/25/jetleak-vulnerability-remote-leakage-of-shared-buffers-in-je.html

Could you also release a bugfixed version as soon as possible?

Thanks

**Comment by wilkinsona** [comment]
Thanks for raising the issue. Spring Boot 1.2.2 is due tomorrow so it was rather well timed.

**Comment by jcayetano** [comment]
Perfect timing and quick response, thanks folks.

Looking forward to 1.2.2.
