### ISSUE TITLE
Support properties for RabbitMQ autoconfiguration with NIO

### ISSUE THREAD

**Issue by Vsevolod123** [spring-projects/spring-boot#25554]
It would be nice to autoconfigure rabbit connection factory with NIO

**Comment by mbhave** [comment]
Related #6719 which is about providing a customizer for the `RabbitConnectionFactoryBean`.

**Comment by philwebb** [comment]
The customizer approach suggested in #6719 seems like the best way to offer support for this. The `com.rabbitmq.client.impl.nio.NioParams` class seems too complex to be bound with properties anyway. We'll mark this one as a duplicate of #6719.
