### ISSUE TITLE
Support Maven's reproducible build feature for war repackaging

### ISSUE THREAD

**Issue by Jurrie** [spring-projects/spring-boot#25563]
Please support [reproducible builds](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) for the repackage goal.

This is a follow-up for [issue 20176](https://github.com/spring-projects/spring-boot/issues/20176). Previously, the fix for [issue 20176](https://github.com/spring-projects/spring-boot/issues/20176) was reverted, and the issue was closed. This was done because the `maven-war-plugin` did not handle reproducible builds correctly.

Now, I believe the maven-war-plugin is fixed because of [MWAR-432](https://issues.apache.org/jira/browse/MWAR-432) and [MWAR-436](https://issues.apache.org/jira/browse/MWAR-436). The most recent version supports `<project.build.outputTimestamp>` as far as I can tell.

I commented on [issue 20176](https://github.com/spring-projects/spring-boot/issues/20176), but was asked to open up a new one. That would be this one 😀

**Comment by wilkinsona** [comment]
Just to avoid any confusion, the entire fix for #20176 wasn't reverted, just the war part. It should already be possible to repackage a jar file in a reproducible manner.

**Comment by Jurrie** [comment]
For reference: the war part was reverted in c4a55a5fb421dadf074fb39eddd542cf29a43deb on 16-mar-2020.
The Maven WAR plugin was upgraded to 3.3.1 in a35073def58fef050136de452051f59b5504e6f0 on 7-aug-2020.
So, it is probably just a matter over reverting commit c4a55a5fb421dadf074fb39eddd542cf29a43deb.

**Comment by Jurrie** [comment]
I created https://github.com/spring-projects/spring-boot/pull/25571

**Comment by scottfrederick** [comment]
Closing in favor of #25571
