### ISSUE TITLE
How about excluding `commons-logging` in `spring-core` in `spring-boot-dependencies`?

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#2556]
In every starter module (spring-boot-starter-*),

the following dependency keeps showing up:
```
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
How about excluding `commons-logging` in `spring-core` in `spring-boot-dependencies`?

**Comment by snicoll** [comment]
The core of Spring boot uses `commons-logging` actually. Excluding that won't help much since Spring Framework uses it for [historical reasons](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#overview-logging)

**Comment by izeye** [comment]
@snicoll Okay. Thanks for the response.

**Comment by davidkarlsen** [comment]
It could be replaced with jcl-over-slf4j?

**Comment by philwebb** [comment]
@davidkarlsen Thanks for the suggestion. We actually already include `jcl-over-slf4j` with the logging starter. Also later version of Spring Boot also no longer have the exclude (this is quite an old issue report).

**Comment by davidkarlsen** [comment]
Yeah - I think it is maybe no longer relevant for 2.x since spring started using it's own logging abstraction which detects jcl, slf4j etc
