### ISSUE TITLE
Logback stopAndReset double reset

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#25589]
Spring boot 2.4.2

Logback is reset twice
https://github.com/spring-projects/spring-boot/blob/d283e5957c1a66c96ef3961de88a112abaeff5cd/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L195-L197
because stop also calls reset:
https://github.com/qos-ch/logback/blob/61ffd3aba042bbb22f588599ff5574d3b9667d22/logback-classic/src/main/java/ch/qos/logback/classic/LoggerContext.java#L349-L350

This causes issues when using a `LoggerContextListener` that adds custom appenders, and is removed after reset (`isResetResistant` false).
Due to duplicate reset, the appenders are removed at second reset and the listener is not called the second time, so the result is no custom appenders.

**Comment by cdalexndr** [comment]
Actually, `stop()` also removes all listeners, so my use case is not valid.

**Comment by scottfrederick** [comment]
Indeed, `stop()` [removes all listeners](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/LoggerContext.java#L352), while `reset()` only [removes non-reset-resistant listeners](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/LoggerContext.java#L229).
