### ISSUE TITLE
Provide build related information and include that in the `InfoEndpoint`

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2559]
`spring.io/info` displays build info + application info. But most of the information is provided by configuration file. 

```
{  
   "app":{  
      "name":"sagan-green:2",
      "start":"2015-02-12 04:01:50 +0000"
   },
   "build":{  
      "artifact":"spring-io",
      "description":"spring-io",
      "name":"spring-io"
   },
   "spring":{  
      "profiles":"production"
   },
   "git":{  
      "branch":"detached HEAD",
      "commit":{  
         "id":"d6490ab",
         "time":"2015-02-06 08:14"
      }
   }
}
```

Before moving spring boot, I had implemented a custom maven plugin to generate build info file and adds into our application jar. This file includes some properties at build time from `maven` and `jenkins`. 

And here is our `info`:

```
{  
   "app":{  
      "start":"2015-02-25T10:42:16.554"
   },
   "build":{  
      "group":"my.web",
      "timestamp":"20150225-0947",
      "version":"2.10.0-SNAPSHOT",
      "artifact":"my-web"
   },
   "git":{  
      "branch":"origin/development",
      "commit":{  
         "id":"9f6d9b1",
         "time":"2015-02-25T09:07:23+0200"
      }
   }
}
```

I think that it would be nice to add such a build info into the application at build times.

**Comment by philwebb** [comment]
Perhaps we could make this an option of the spring-boot-maven plugin. Do you have any code that you can share for your plugin?

**Comment by philwebb** [comment]
We probably need to be a bit careful not to accidentally expose information that people would rather keep private. Perhaps it should be opt-in.

**Comment by snicoll** [comment]
yeah, an additional goal that would add an extra resource in the jar that the info endpoint could read.

**Comment by cemo** [comment]
@snicoll +1

**Comment by khoubyari** [comment]
+1

**Comment by mrumpf** [comment]
Related: #4845 
Changing the current implementation to have a kind of "InfoEndpointContributor" which contributes information to the info endpoint would be a great improvement. We are working on a big refactoring towards microservices based on Spring Boot with many different teams working on their own microservice. The current implementation would force us to add the same "info" section to each application.properties file by copy&paste. This is will very likely be hard to synchronize as the teams are mostly independent of each other. Instead I would like to provide a base library together with a parent pom, where all the default configuration is provided. That means the application.properties files will only contain settings that have to be provided additionally or which differ from the defaults. A first set of "InfoEndpointContributor" implementations could be the already present GitInfo and a second one that reads the MANIFEST.MF file and displays the information under a "manifest" section.

**Comment by cemo** [comment]
```

public class InfoEndPointPropertySourceListener implements SpringApplicationRunListener {

   public InfoEndPointPropertySourceListener(SpringApplication application, String[] args) {}

   @Override
   public void started() {}

   @Override
   public void environmentPrepared(ConfigurableEnvironment environment) {
      environment.getPropertySources().addLast(new CustomPropertySource());
   }

   @Override
   public void contextPrepared(ConfigurableApplicationContext context) {}

   @Override
   public void contextLoaded(ConfigurableApplicationContext context) {}

   @Override
   public void finished(ConfigurableApplicationContext context, Throwable exception) {}

   private static class CustomPropertySource extends PropertiesPropertySource {

      static ResourceLoader resourceLoader = new DefaultResourceLoader();

      static Properties properties = init();

      private static Properties init() {
         properties = new Properties();
         properties.put("info.app.start", LocalDateTime.now().toString());
         loadProperties();
         return properties;
      }

      private static void loadProperties() {
         Properties buildProperties = new Properties();
         Resource resource = resourceLoader.getResource("/META-INF/build.properties");
         if(resource.exists()) {
            try {
               buildProperties.load(resource.getInputStream());
               properties.put("info.build.artifact", buildProperties.get("artifact"));
               properties.put("info.build.group", buildProperties.get("group"));
               properties.put("info.build.version", buildProperties.get("version"));
               properties.put("info.build.timestamp", buildProperties.get("timestamp"));
            } catch (Exception ignored) {}
         }
      }

      protected CustomPropertySource() {
         super("build.properties",  properties);
      }
   }
}

```

I had shared this previously somewhere else but forgot to add here. Here is the relevant code I am using in our projects. @snicoll and @philwebb You might be interested in as well.

I have a custom build step in our maven build to generate "build.properties" each time. This might be not perfect solution but it is an easy workaround currently.

@mrumpf Please just replace or add "MANIFEST.MF" in my codes to display necessary information.

**Comment by snicoll** [comment]
Okay so we have no `GitInfo` on `master`. Here is what I intend to do: 

1. create a `BuildInfo` with `artifact`, `name` and `version`
2. update the build plugins to generate a `META-INF/boot/build.properties` with those values (`build.artifact=my-project`)
3. When a `BuildInfo` bean is available, automatically export the information in the `build` section of the `/info` endpoint

Any info that would be missing? Any remark? Thanks!

**Comment by snicoll** [comment]
@mrumpf there is an `InfoContributor` on master. We're still making up our mind about the final API but it should do pretty much what you asked.

**Comment by snicoll** [comment]
A first good batch has just been pushed to `master`. You can try this out yourself either with the updated actuator sample or using [`test-info-contributor`](https://github.com/snicoll-scratches/test-info-contributor).

We have a new Maven goal that is opt-in and that generates a file that's picked up by Boot automatically. The plugin allows you to add an arbitrary number of extra keys. As for git, the related info contributor has a mode to only show a pre-defined set of keys or all of them. 

The Gradle plugin and docs update is coming next.
