### ISSUE TITLE
Error when adding @EnableJpaRepositories 

### ISSUE THREAD

**Issue by johanfrick-mobenga** [spring-projects/spring-boot#256]
Related to #254 (which was closed, that is why I created a new issue)

If I add @EnableJpaRepositories I get:
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'entityManagerFactory' is defined

**Comment by jatyap** [comment]
Is this issue closed? I'm having the same issue if I don't write create a datasource bean and rely on application.properties in the classpath for datasource

I have this in application.properties
<code>spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
</code>

and these are the annotations and my app class.
<code
@SpringBootApplication
@PropertySource("classpath:application.properties")
@ComponentScan("com.jatyap.ordermgmt")
@EntityScan("com.jatyap.ordermgmt.entity")
@EnableJpaRepositories("com.jatyap.ordermgmt.repository")
public class MainApplication {

	public static void main(String[] args) {
		ApplicationContext ctx = SpringApplication.run(MainApplication.class,
				args);
	}
}
</code>

I have a slightly older project where I don't use the JPA repositories, and that one starts and connects to the data just fine.

Does anybody see anything wrong with this?

**Comment by snicoll** [comment]
That issue was closed over a year ago. As @dsyer said above, please create another issue. The `PropertySource`looks very suspicious to me (why are you doing that?). In any case, please provide more details if you create an issue (a sample project would be nice).

**Comment by jatyap** [comment]
Thanks. I just wanted to confirm. I will do that if I'm not able to solve it by tinkering with some of the values in the pom.

Cheers!

**Comment by Hard-system** [comment]
This solved my issues: 
	
			<dependency>
			    <groupId>org.hibernate.javax.persistence</groupId>
			    <artifactId>hibernate-jpa-2.1-api</artifactId>
			    <version>1.0.0.Final</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-core</artifactId>
				<version>5.2.3.Final</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-entitymanager</artifactId>
				<version>5.2.3.Final</version>
			</dependency>

**Comment by philwebb** [comment]
@Hard-system We'd always recommend using our managed dependencies rather then defining your own versions.

**Comment by damienpalacio** [comment]
in our case was working fine but not for tests with @WebMvcTest

Took a while to find out but issue was:
```
@SpringBootApplication
@ComponentScan({"com.givenproject"})
@EntityScan("com.givenproject")
@EnableJpaRepositories("com.givenproject")
@Configuration
public class Application {
```

instead do:
```
@SpringBootApplication
@Configuration
public class Application {
```
and
```
@Configuration
@ComponentScan({"com.givenproject"})
@EntityScan(basePackages = "com.givenproject")
@EnableJpaRepositories(basePackages = "com.givenproject")
public class DataConfig {
}
```

**Comment by kilonet** [comment]
@damienpalacio this on caused a lot of pain, thnx for finding out
