### ISSUE TITLE
Kafka StreamsBuilderFactoryBeanCustomizer Duplicates An Interface Already in spring-kafka

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#25608]
In July last year, [this commit](https://github.com/spring-projects/spring-boot/commit/54e0a61b425d00ceb220b82dc8abbad121245c10) added interface `StreamsBuilderFactoryBeanCustomizer` (Boot 2.3, which uses S-K ).

An identical interface [has existed](https://github.com/spring-projects/spring-kafka/commit/9e86163647217dd9cefb5e35c974eb476cefc150) in `spring-kafka` for over 2 years (S-K 2.2, Boot 2.1); it is only used to customize the `DEFAULT_STREAMS_BUILDER_BEAN_NAME` configured by S-K; it looks like Boot is doing the same, just for that same FB.

Consider deprecating the Boot interface (perhaps making it extend the S-K version during the interim), to avoid confusion.

We will then need some mechanism to not apply the customization in S-K if we are running in a Boot app.; in case the customization is not idempotent.

**Comment by wilkinsona** [comment]
We use the customiser in Boot to configure Micrometer metrics:

https://github.com/spring-projects/spring-boot/blob/b5843cfd4dabba09eb8f341c4ea1a3ecfa38d91b/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/KafkaMetricsAutoConfiguration.java#L78-L81
In Boot you can have n customisers, and each will be called in order:

https://github.com/spring-projects/spring-boot/blob/b5843cfd4dabba09eb8f341c4ea1a3ecfa38d91b/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaStreamsAnnotationDrivenConfiguration.java#L76

Given Spring Kafka's requirement that there's only one `org.springframework.kafka.config. StreamsBuilderFactoryBeanCustomizer`, I'm not sure we can deprecate Boot's in favour of Spring Kafka's as they have different contracts.

**Comment by garyrussell** [comment]
Doh - I mis-read the method name; I thought they were the same.

It's still rather unfortunate that we didn't pick up this conflict; confusing for users.

I guess we'll have to just live with it.

**Comment by garyrussell** [comment]
Yes; I'll do that and deprecate the name clash.

Thanks for your input @wilkinsona .

Feel free to close with appropriate label(s); I don't have permissions.
