### ISSUE TITLE
YamlProcessor customization

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#2560]
Hi,

For a Spring-boot project using yaml properties, I need to customize _Yaml_ instance to add a home made Yaml Constructor

<pre><code>
public class SystemPropertyToIntConstructor extends Constructor {

    public SystemPropertyToIntConstructor() {
        this.yamlConstructors.put(new Tag("!sysToInt"), new ConstructSystemPropertyToInt());
    }

    private class ConstructSystemPropertyToInt extends AbstractConstruct {
    	
    	/*
    	 * (non-Javadoc)
    	 * @see org.yaml.snakeyaml.constructor.Construct#construct(org.yaml.snakeyaml.nodes.Node)
    	 */
    	@Override
		public Object construct(Node node) {
            String key = (String) constructScalar((ScalarNode) node);
            return Integer.parseInt(System.getProperty(key));
        }
    }
    
}
</code></pre>

By default _YamlProcessor_ just instantiate a _Yaml_ class

<pre><code>
	protected void process(MatchCallback callback) {
		Yaml yaml = new Yaml();
		for (Resource resource : this.resources) {
			boolean found = process(callback, yaml, resource);
			if (this.resolutionMethod == ResolutionMethod.FIRST_FOUND && found) {
				return;
			}
		}
	}
</code></pre>

I extended _YamlPropertiesFactoryBean_ class to override the _process_ method defined by the abstract _YamlProcessor_ class

<pre><code>
	protected void process(MatchCallback callback) {
		Yaml yaml = new Yaml(new SystemPropertyToIntConstructor());
		for (Resource resource : this.resources) {
			boolean found = process(callback, yaml, resource);
			if (this.resolutionMethod == ResolutionMethod.FIRST_FOUND && found) {
				return;
			}
		}
	}
</code></pre>

Unfortunately the methods that the _process_ method calls are all private. So I had to override all of them and copy/paste their content to achieve my customzation.

Is it possible that the _org.springframework.boot.yaml.YamlProcessor_ provides a way either inject my own Yaml instance or just override the process method

**Comment by snicoll** [comment]
Spring Boot 1.2.2 is coming up later today with Spring Framework 4.1.5 and we added [this method](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/factory/config/YamlProcessor.java#L148)

Does that address your need?

**Comment by RaphC** [comment]
Perfect.

Many Thanks,
