### ISSUE TITLE
Multiarch dockerimages

### ISSUE THREAD

**Issue by MarcelCoding** [spring-projects/spring-boot#25612]
Add the ability to build multi architecture docker images with [qemu](https://www.qemu.org/).
See: https://www.docker.com/blog/multi-platform-docker-builds/

**Comment by scottfrederick** [comment]
The Spring Boot build plugins integrate with a [Cloud Native Buildpacks builder](https://buildpacks.io/docs/concepts/components/builder/) to generate Docker images. The builder uses buildpacks to generate the image contents, based on a run image for the base OS layers. Spring Boot uses the [Paketo](https://paketo.io/) builders by default, but you can choose to use any other CNB-compliant builder. 

Supporting multi-arch images would be the responsibility of the CNB builder, not something that is under Spring Boot's control. I haven't seen this topic discussed in the CNB community, but you could start the discussion with the [Buildpacks.io](https://buildpacks.io/community/) or [Paketo](https://slack.paketo.io/) teams.

**Comment by MarcelCoding** [comment]
@scottfrederick Thanks for your fast reply.
