### ISSUE TITLE
Provide a simple datasource as a default option for non-embedded jdbc drivers

### ISSUE THREAD

**Issue by linead** [spring-projects/spring-boot#2561]
I'd like to see a simple default provided in the case where a non-embedded datasource is configured but there's no connection pool on the classpath. 

Something like `SimpleDriverDataSource` would be useful when building utilities with spring boot that don't have to worry about connection pooling.

**Comment by philwebb** [comment]
There are a few issues that make us a little reluctant to do this by default:
- We don't want to accidentally auto-configure a DataSource where previously there wasn't one.
- We're concerned that people might think there getting a production ready pooled database, when in fact we've auto-configured one that isn't really suitable.
- It's not going to be possible for us to map all `DataSourceProperties` to `SimpleDriverDataSource`.

For these reasons we think it's probably best if users continue to explicitly declare their own `SimpleDriverDataSource` `@Bean` if that's what they really want.
