### ISSUE TITLE
Provide a way to expose IDs for all classes in Spring Data REST by a property.

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#2564]
Spring Data REST does not expose IDs by default.

I can manually add all classes to be exposed

but it would be good to provide an easy way to do it.

How about providing a way to expose IDs for all classes in Spring Data REST by a property?

**Comment by snicoll** [comment]
Why would you want to do that?

/cc @olivergierke

**Comment by izeye** [comment]
@snicoll I'm using it for internal services so I don't care whether IDs are exposed or not.

But most cases I need IDs.

The reason why IDs are not exposed by default is a security concern, right?

Am I missing something?

**Comment by izeye** [comment]
@snicoll Actually I want to have a blacklist pattern like excluding classes from exposing IDs not a whitelist pattern in Spring Data REST if possible.

**Comment by olivergierke** [comment]
I'd like to veto on that one. In REST the URI *is* the identifier. Backend identifiers must not make it into the representation as it creates incentives to build up URI structures manually. Spring Data REST leverages hypermedia and thus I'd vote against making the wrong thing easier. If you really insist on going down that route, Spring Data REST already has the means for it. Using them being painful is a feature, not a bug :).

**Comment by izeye** [comment]
@olivergierke Okay. Then is there any easy way to get IDs from a collection? What is the right way as a REST style? Parsing _links.self.href?

**Comment by olivergierke** [comment]
`$._embedded.users.._links.self.href` where `users` is the type of the elements your interested in.

**Comment by snicoll** [comment]
If you have further questions, please create a stackoverflow thread. Thanks.
