### ISSUE TITLE
Boot Auto Generates User Despite Custom Authentication

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-boot#2567]
I just updated to Spring Boot 1.2.2 and Spring Security 3.2.6 and now I see on startup "Using default security password: 2b3fca81-99d8-490f-9bff-6f6f79c1c749".

I far as I remember this didn't appear with Boot 1.2.1 and Security 3.2.5.

My security config (omitted some stuff):

```
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
	@Autowired AuthenticationEntryPoint authenticationEntryPoint;
	@Autowired AccessDeniedHandler accessDeniedHandler;
	@Autowired LogoutSuccessHandler logoutSuccessHandler;
	@Autowired AuthenticationSuccessHandler successHandler;
	@Autowired AuthenticationFailureHandler authenticationFailureHandler;
	
	@Override protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
				.antMatchers("/public/**").permitAll()
				.anyRequest().authenticated()
				.and()
			.sessionManagement()
				.maximumSessions(1).maxSessionsPreventsLogin(false).and()
				.and()
			.exceptionHandling()
				.authenticationEntryPoint(authenticationEntryPoint)
				.accessDeniedHandler(accessDeniedHandler)
				.and()
			.formLogin()
				.loginProcessingUrl("/api/authentication")
				.successHandler(successHandler)
				.failureHandler(authenticationFailureHandler)
				.and()
			.logout()
				.logoutRequestMatcher(new AntPathRequestMatcher("/api/authentication", "DELETE", true))
				.logoutSuccessHandler(logoutSuccessHandler)
				.invalidateHttpSession(true)
				.and()
			.headers()
				.frameOptions().disable()
	            .csrf().disable();
	}
	
	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth, UserDetailsService userDetailsService, PasswordEncoder passwordEncoder) throws Exception {
		auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder);
	}
	
	@Bean
	public PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}
}
```

```
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class GlobalMethodSecurityConfig extends GlobalMethodSecurityConfiguration { }
```

```
@Service
public class UserDetailsProvider implements UserDetailsService {
	@Autowired UserRepo repo;
	
	@Override
	public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
		User user = ...;
		Set<GrantedAuthority> roles = ...;
		return new SecurityUser(user, roles);
	}
	
}
```

According to Boot's Documentation, I should only need @EnableWebSecurity and autoconfig should be disabled. 

Bug, or have I missed something?

**Comment by sjoerdmulder** [comment]
I can confirm that since the update to 1.2.2 from 1.2.1 this also happens for our project, and basically mean authentication is broken (since it doesn't pickup our own user details service).

**Comment by benneq** [comment]
For me authentication still works using the code above.

**Comment by rwinch** [comment]
@benneq Making sure I understand the situation correctly. It sounds as though the code still functions correctly (i.e. it uses your custom UserDetailsService), but it is incorrectly generating a username / password? Is that correct?

If my understanding is correct:

* Can you try authenticating with user and the generated password and see if it works?
* Can you tell me if you are using actuator?

**Comment by rwinch** [comment]
@sjoerdmulder It sounds as though your situation may be different. Can you confirm that you are unable to authenticate with your UserDetailsService? Can you provide a sample I can use to reproduce this?

**Comment by benneq** [comment]
My custom UserDetailsService is working , just like with Boot 1.2.1
I can login using my users from DB.
But with Boot 1.2.2 it seems to generate a new user during startup (I assume this because of the log msg: "Using default security password: 2b3fca81-99d8-490f-9bff-6f6f79c1c749").
I can't login with user / 2b3fca81-99d8-490f-9bff-6f6f79c1c749.

**Comment by rwinch** [comment]
@benneq Thanks! Are you using actuator?

**Comment by sjoerdmulder** [comment]
Correct i have our project working again by overriding `protected void configure(AuthenticationManagerBuilder builder)` instead of configuring the AuthenticationManagerBuilder with a `@PostConstruct` which was needed previously to have it working. Only issue now is still that it prints the `Using default security password` message.

**Comment by rwinch** [comment]
@sjoerdmulder - Thanks for the fast reply. Can you provide the code that demonstrates the issue with `@PostContstruct` (perhaps as a separate issue making sure to add @rwinch on the issue)?

**Comment by benneq** [comment]
No, there's no actuator running in our project :-/

**Comment by rwinch** [comment]
> I can't login with user / 2b3fca81-99d8-490f-9bff-6f6f79c1c749

@benneq I'm able to reproduce the issue, but the generated username/password work for me. 
Can you double check to see if the generated username / password work or not? I'm concerned that I may not be reproducing the issue correctly and am actually hitting a slight variation of the issue.

If you like, you can clone my branch and see if it fixes your issue. You can find the branch at https://github.com/rwinch/spring-boot/tree/gh-2567

After cloning, you should be able to do a maven install and then update your pom.xml or gradle file to point to the snapshot. If you are using Gradle, you will need to also ensure you have the mavenLocal() repository added.

**Comment by mikemosseri** [comment]
@rwinch I can confirm this fixes the issue. When will this also be added to 1.2.3?

**Comment by wilkinsona** [comment]
@mikemosseri Any fix that's applied in 1.1.12 (as is the intention with this issue) will be merged forward in 1.2.3.

**Comment by cemo** [comment]
@wilkinsona Could you add `1.2.3` milestone to this issue? 

https://github.com/spring-projects/spring-boot/issues?q=milestone%3A1.2.3+

**Comment by snicoll** [comment]
I am afraid we can only set one milestone.

**Comment by mchiareli** [comment]
I have the same problem in the version 1.3.0M4, I have configured security by myself, but the log shows the default security user.

I am not using actuator, but I am using the new spring-boot-devtools.

**Comment by wilkinsona** [comment]
@mchiareli This issue's now closed. If you're experiencing a similar problem with 1.3.0, please open a new issue with the steps or, ideally, a sample project, to reproduce the problem

**Comment by prabhatsubedi** [comment]
I too faced this issue, just wanted to know, why/how `@Autowired protected void globalConfigure(AuthenticationManagerBuilder auth)` did not work but adding ```
@Autowired
    protected void configure(AuthenticationManagerBuilder auth)
``` worked ?

**Comment by snicoll** [comment]
@prabhatsubedi commenting on an issue that was closed 2 years ago isn't a great way to ask for help. We don't use the tracker for questions so please join us on Gitter or ask on StackOverflow.
