### ISSUE TITLE
Change spring.kafka.streams.cleanup.on-shutdown default to false

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25730]
See https://github.com/spring-projects/spring-kafka/pull/1739 for the upstream spring-kafka change.

**Comment by snicoll** [comment]
This was merged after RC1 so I had to revert it once I upgraded to Spring Kafka `2.7.0-RC1`. We'll have to apply that again when we switch back to snapshot

**Comment by snicoll** [comment]
This is now superseded by #25930
