### ISSUE TITLE
Bootstrapper interface provides no clean upgrade path due to deprecated method

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-boot#25735]
The misspelled method needs to be default and call the correctly spelled method not the other way around.

There is no way to NOT get a deprecation warning with the current code.

PR coming shortly.

**Comment by wilkinsona** [comment]
I disagree. If the correctly spelled method was not default, its addition would be a breaking API change. Instead, you should mark your implementation of the deprecated method as `@Deprecated.`.

**Comment by jmax01** [comment]
Have you actually tried to use it?

**Comment by wilkinsona** [comment]
Yes, of course. Please see https://github.com/spring-projects/spring-boot/pull/25400 for details of the thought that went into the change and the steps we took to ensure that it's backwards compatible.  We cannot add a non-default method to an interface in a maintenance release as it will be a breaking API change.

**Comment by jmax01** [comment]
> Yes, of course. Please see #25400 for details of the thought that went into the change and the steps we took to ensure that it's backwards compatible. We cannot add a non-default method to an interface in a maintenance release as it will be a breaking API change.

Ah thanks I will just suppress the warning.

**Comment by wilkinsona** [comment]
Sorry, I'm not sure that I understand what you mean by "should call `initialize`". `Bootstrapper` is intended to be implemented by code building on top of Spring Boot, but it's Spring Boot itself that will call the `Bootstrapper` implementations. It calls `initialize` as encouraged by the deprecation of `intitialize` in favour of it.

**Comment by jmax01** [comment]
I get that SpringBoot itself calls the properly spelled `initialize`, but the implementer of a Bootstrapper class must declare their method implementation with the wrong spelling AND suppress the the warning.   This should be documented it is non-obvious.

**Comment by philwebb** [comment]
This typo has caused a lot of pain. I think the updated code makes sense for people using lambdas, but it's not great for people directly implementing the interface. The only solution I can think of is to introduce a new interface entirely. I've sketched something out in https://github.com/philwebb/spring-boot/tree/gh-25735.

**Comment by jmax01** [comment]
@philwebb I love this solution, much more clear. One thing for sure I am going to *really* pay attention to my interface method  names from now on, a miss spelling is basically unfixable.
