### ISSUE TITLE
Breaking change in Spring Boot 2.5.0-M1..M3 related to spring-data-common

### ISSUE THREAD

**Issue by khmarbaise** [spring-projects/spring-boot#25746]
Based on the upgrade to Spring Boot 2.5.0-M2 and 2.5.0-M3 we are testing (upgrading from 2.4.3) we realized there is a breaking change in an interface `org.springframework.data.domain.Pageable` which is in `spring-data-common` (picked up by this upgrade). The problem is based on adding a new method `withPage(..)` without adding a default implementation (I can't say if it would be a good idea to do so or not.).

We got the error message:
```
XXX is not abstract and does not override abstract method withPage(int) in 
```

**Comment by snicoll** [comment]
There's nothing we can do about that and that discussion can continue on the Spring Data issue you've also raised.

**Comment by khmarbaise** [comment]
Ok no problem. I only wanted to make that becoming aware... Thanks Stéphane.
