### ISSUE TITLE
Upgrade to Spring Framework 4.2

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2575]

**Comment by wilkinsona** [comment]
We should update the requirements section in the doc when we upgrade to Spring 4.2. They currently state that Boot requires Spring Framework 4.1.3 (it's actually 4.1.5)

**Comment by snicoll** [comment]
Also, there is a copy/paste of `JavaMailSenderImpl` for a lack of connectivity check operation that has been addressed in https://github.com/spring-projects/spring-framework/commit/a64532ede2546f5e4bdb470f6087d053201d2317 - We should make sure to update `MailHealthIndicator` once we upgrade.

**Comment by philwebb** [comment]
I've fixes the docs and the WIKI

**Comment by philwebb** [comment]
Also raised #2666 for the mail copy/paste removal.

**Comment by snicoll** [comment]
Thanks Phil, I'll create a separate issue next time.

**Comment by wilkinsona** [comment]
There's a [behaviour change](https://jira.spring.io/browse/SPR-12846) that causes problems with Spring Data JPA as it stops it from finding `JpaRepositoryFactoryBean`s. /cc @olivergierke

**Comment by wilkinsona** [comment]
Here's a branch where I'm trying to get things working with 4.2: https://github.com/wilkinsona/spring-boot/tree/spring-framework-4.2

@philwebb Any comments on/objections to the changes in [this commit](https://github.com/wilkinsona/spring-boot/commit/cc24e6cf01f161aac8a27f0eaf1a6bbc92f9c1e9)?

**Comment by philwebb** [comment]
@wilkinsona No objections, although I was considering a `@AutoConfiguration` annotation at one point that could be meta-annotated with `@Configuration`. That might be a sensible alternative (although the order would need to default to 0)

```
@AutoConfiguration(order=123)
public class SomeAutoConfiguration {
}
```

Probably the separate annotation still works best.
