### ISSUE TITLE
BufferingApplicationStartup fails with NoSuchElementException

### ISSUE THREAD

**Issue by IvanPavlov1995** [spring-projects/spring-boot#25792]
Very rarely my application run fails with following error:

```
[main] ERROR o.s.boot.SpringApplication - Application run failed
java.util.NoSuchElementException: null
at java.base/java.util.ArrayDeque.removeFirst(Unknown Source)
at org.springframework.boot.context.metrics.buffering.BufferingApplicationStartup.record(BufferingApplicationStartup.java:138)
at org.springframework.boot.context.metrics.buffering.BufferedStartupStep.end(BufferedStartupStep.java:92)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:614)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
```

Spring boot version is 2.4.1.
I have following spring-related dependencies:
```
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-starter</artifactId>                
</dependency>                                                   
<dependency>                                                    
    <groupId>de.codecentric</groupId>                           
    <artifactId>spring-boot-admin-starter-client</artifactId>   
</dependency>                                                   
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-autoconfigure</artifactId>          
</dependency>                                                   
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-starter-web</artifactId>            
</dependency>                                                   
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-starter-security</artifactId>       
</dependency>                                                   
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>                                   
</dependency>                                                   
<dependency>                                                    
    <groupId>org.springframework.boot</groupId>                 
    <artifactId>spring-boot-starter-data-mongodb</artifactId>   
</dependency>                                                   
```

**Comment by bclozel** [comment]
Unfortunately, this doesn't provide enough information to figure this problem out.

This should only happen if startup events during the the context refresh happen concurrently; this should not happen since the context refresh is single threaded. I'd be interested to have more clues about this instance.

* Are there `ApplicationRunner` instances or application beans doing multi-threaded work during their initialization?
* Did you set a specific value for `spring.data.jpa.repositories.bootstrap-mode`?

I'm not really optimistic here, since reproducing this issue is really hard by definition. But we can repurpose this issue to explore ways to mitigate this problem or provide more useful information in case of failures.

**Comment by IvanPavlov1995** [comment]
I didn't set a specific value for `spring.data.jpa.repositories.bootstrap-mode`. I don't think I have `ApplicationRunner` instances with such logic but regular beans could do multi-threaded work. This project is quite large so I'm not sure I can find the root cause. It would be great if you could point me where exactly I can check something you need to investigate that

**Comment by philwebb** [comment]
I wonder if `BufferedStartupStep.end()` is somehow being called twice? Perhaos we should change `currentSteps.removeFirst` to instead remove the `BufferedStartupStep.id`?

**Comment by IvanPavlov1995** [comment]
Actually I can't be sure, but I don't use it manually or something like that. I just added application runner into existing application upon migration on spring boot 2.4.1 from 2.3.x.

**Comment by philwebb** [comment]
As a first step we're going to try and add some more logging

**Comment by bharatnpti** [comment]
@philwebb - we are also facing same issue with Spring Boot version 2.4.4
Do we have any plan to back port it or some temporary fix for older versions.

**Comment by bclozel** [comment]
@bharatnpti it's been fixed in 2.4.6.

**Comment by bharatnpti** [comment]
@bclozel - yes I saw that but we are using 2.4.4 presently, so I guess only option is to move to 2.4.6 if not backported

**Comment by snicoll** [comment]
@bharatnpti `2.4.6` is a patch release of `2.4.4`. The last in this line is `2.4.13`. There's no such thing as "backporting" on the same line.
