### ISSUE TITLE
`@ComponentScan` worked based on `@Conditional` but auto-configuration failed.

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#2579]
I'm trying to `@ComponentScan` by auto-configuration

but I can't make it.

`@ComponentScan` worked based on `@Conditional` but auto-configuration failed.

This is a sample project I did try:

https://github.com/izeye/samples-spring-boot-branches/tree/auto-configuration

Did I use it in a wrong way?

**Comment by wilkinsona** [comment]
It looks like you're expecting `@ComponentScan` to only be switched on if `@ConditionalOnMissingBean` matches, correct? That'd would require an enhancement to Spring Framework I believe.

Using `@ComponentScan` on an auto-configuration class is a little strange, imo. If you look at Spring Boot's source you'll notice that none of our auto-configuration classes make use of it. Instead, we declare `@Bean` methods for all of the beans. This gives far better control as it allows conditions to be associated with each bean.

**Comment by izeye** [comment]
@wilkinsona Sorry. I thought it could be a bug. Thanks for the response.
