### ISSUE TITLE
Configuration option for R2DBC's socket option

### ISSUE THREAD

**Issue by jamesward** [spring-projects/spring-boot#25802]
Spring Boot 2.4.4

Please provide a way to set the R2DBC socket config instead of the url.

**Comment by snicoll** [comment]
@jamesward The socket option is [not part of the spec](https://github.com/r2dbc/r2dbc-spi/blob/8de2fd017366254602a185987130ba8955340644/r2dbc-spi/src/main/java/io/r2dbc/spi/ConnectionFactoryOptions.java#L53) but specific to the postgres driver. We can't add a top-level option that's specific to one database.

There are a number of mechanisms you can use right now to configure the socket. The URL of course, `spring.r2dbc.properties.*` but also the customizer callback, see [the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-r2dbc).

**Comment by jamesward** [comment]
Ah. Thanks so much for the helpful response!

**Comment by mp911de** [comment]
Alternatively, you can use `spring.r2dbc.url=spring.r2dbc.url=r2dbc:postgres:///<database>?socket=/tmp/.s.PGSQL.5432`
