### ISSUE TITLE
Documentation for ConditionalOn[Missing]Bean.annotation?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2583]
It appears that the `annotation` parameter on the bean conditions can be used to ensure that the injected bean has a meta-annotated `@Qualifier` attached. Is this the case? If so, it would be helpful to note that in the Javadoc.

**Comment by philwebb** [comment]
It's not really indented for `@Qualifier` more for annotations such as `@EnableScheduling`. I'm not keen to highlight `@ConditionalOn...Bean` annotations in the docs since they really only work in auto-configuration classes.
