### ISSUE TITLE
Document when config data properties are invalid

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#25849]
See https://github.com/spring-projects/spring-boot/issues/25848 for some background. As far as I can see, the reference documentation does not mention that `spring.profiles.active` is invalid in a profile-specific configuration file. It's [mentioned on the wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#profile-activation), but I think we should mention it and any other potential triggers of an `InvalidConfigDataPropertyException` in the reference documentation.

**Comment by robert-smith-911** [comment]
@wilkinsona Something I could look at?

**Comment by wilkinsona** [comment]
Sorry for the delay, @robert-smith-911. I missed the notification for your comment. If you're still interested in looking at this, that'd be much appreciated. Thank you.

**Comment by robert-smith-911** [comment]
@wilkinsona Sure I'll take a look, thanks. What part of the docs should this go?

**Comment by wilkinsona** [comment]
I think I'd put the bulk of the changes [here](https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-files-profile-specific) and then perhaps also mention the restriction at the end of [section 4.3](https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/htmlsingle/#boot-features-profiles).

**Comment by robert-smith-911** [comment]
@wilkinsona Got swamped, but looking to have this finished up over the weekend

**Comment by wilkinsona** [comment]
No worries, @robert-smith-911. Whenever you're ready.

**Comment by robert-smith-911** [comment]
@wilkinsona So it seems just from this issue (and some Googling) that I've really only found a handful of potential triggers of an InvalidConfigDataPropertyException. Is there somewhere specific I could be looking?

**Comment by wilkinsona** [comment]
There’s no one specific place. If it were me, I’d use my IDE to identify everywhere that `InvalidConfigDataPropertyException` is thrown and work out the different causes from there.

**Comment by robert-smith-911** [comment]
@wilkinsona ok great thanks

**Comment by robert-smith-911** [comment]
@wilkinsona My apologies, sorry to say just too swamped to finish this one 😢  hopefully this summer I can jump back in and contribute some more fixes.

**Comment by snicoll** [comment]
No worries and thanks for letting us know.
