### ISSUE TITLE
Extend VcapApplicationListener to parse all CloudFoundry environment variables

### ISSUE THREAD

**Issue by metacubed** [spring-projects/spring-boot#2587]
The `VcapApplicationListener` class maps two CloudFoundry variables (`VCAP_SERVICES` and `VCAP_APPLICATION`) into Spring properties. This metadata includes a few other CloudFoundry variables, such as:

- User-Provided Variables
  - ...
- System-Provided Variables
  - `VCAP_SERVICES`
  - `VCAP_APPLICATION`
  - ...

See [Cloud Foundry Environment Variables](http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#view-env) for details.

The functionality of this class can be extended to include this other metadata. No extra dependencies will need to be added - it will be very similar to existing code in that class.

**Comment by metacubed** [comment]
I've started work on this issue. Please let me know if things need to change!

**Comment by scottfrederick** [comment]
`VCAP_APPLICATION` and `VCAP_SERVICES` are environment variables that contain JSON data, which typically needs be parsed before it can be consumed. Parsing this JSON into flat properties is the primary value that `VcapApplicationListener` provides. 

Most other system-provided env vars are simple key/value pairs, which Boot already makes available via the [Environment abstraction](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config). What else would `VcapApplicationListener` do with these simple env vars?

**Comment by philwebb** [comment]
I think @scottfrederick is right, only the JSON needs special processing. Other variables should just work.
