### ISSUE TITLE
Spring Boot 2.4.4 maven test incompatible

### ISSUE THREAD

**Issue by sunshine55** [spring-projects/spring-boot#25871]
Same `pom.xml`, just upgrade Spring Boot parent from 2.3 to 2.4 but:

Spring Boot 2.4.4: `mvn clean test` doesn't run any test (build success, Tests run: 0)
Spring Boot 2.3.8.RELEASE: `mvn clean test` run all tests

Maven: 3.6.3
JUnit: 4.13.2
Mockito: 3.3.3

Able to run all test cases normally within IntelliJ.

**Comment by wilkinsona** [comment]
This is covered in the release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test.
