### ISSUE TITLE
Add builder docker host option for image building

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#25877]
Add support for configuring the address of the Docker daemon that processes running in the CNB builder container should use. 

In the Maven plugin `image` configuration, the option could look like this: 

```
<configuration>
	<image>
		<builderDockerHost>tcp://127.0.0.1:2375</builderDockerHost>
	</image>
</configuration>
```

In the Gradle plugin `bootBuildImage` configuration, the option could look like this: 

```
bootBuildImage {
    builderDockerHost = "tcp://127.0.0.1:2375"
}
```

**Comment by astropcr** [comment]
Hello! Any plans for this improvement to make it's way in soon? I cant use Spring Boot image building without it unfortunately.

**Comment by scottfrederick** [comment]
@astropcr We don't have any immediate plans to add this feature, as indicated by the fact that it is assigned to the 2.x backlog. 

We have recently identified [an issue ](#29384) that is related to this. The Spring Boot plugins should configure the builder container to use the same Docker host that Spring Boot is using, but we currently aren't doing that. Would the fix for the other issue address your needs, or do you have a requirement to configure the Docker host used by the build container to be different from the one used by Spring Boot plugins?

**Comment by astropcr** [comment]
thanks @scottfrederick - that would do the trick actually. Is there a link to that issue I can track?

Thanks

**Comment by scottfrederick** [comment]
@astropcr The issue is linked with hypertext in the comment above, but the direct link is #29384.

**Comment by scottfrederick** [comment]
With the addition of the `bindHostToBuilder` option in https://github.com/spring-projects/spring-boot/commit/7ad538cd84ae47240cfdd0f7179137e47c44249c, we haven't seen a need to explicitly configure a different Docker host for the builder. I'll close this issue, and we can re-open if the need arises.
