### ISSUE TITLE
Add network option for image building

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#25876]
Add support for configuring the network mode used by the build container when binding an image with CNB buildpacks. The provided value can be used to select a built-in [Docker network driver](https://docs.docker.com/network/#network-drivers) or a driver from a Docker plugin. The value will be passed through, unvalidated, to the [Docker Container Create API](https://docs.docker.com/engine/api/v1.39/#operation/ContainerCreate) when creating the builder container. 

In the Maven plugin `image` configuration, the option could look like this: 

```
<configuration>
	<image>
		<network>host</network>
	</image>
</configuration>
```

In the Gradle plugin `bootBuildImage` configuration, the option could look like this: 

```
bootBuildImage {
    network = "host"
}
```

**Comment by Meijuh** [comment]
Is there any ETA for this feature? I would love to use it. Currently, we have to invoke the `pack` binary manually and add the option `--network host`.

**Comment by Meijuh** [comment]
The linked PR should address this issue. Is there also a way for me to update the Spring reference documentation to reflect this change?

**Comment by snicoll** [comment]
@Meijuh thanks for the PR. Let's continue the discussion about the reference doc there.

**Comment by Meijuh** [comment]
@snicoll I was looking for the repo quickly, but could not find it; which one is it?

**Comment by scottfrederick** [comment]
Closing in favor of #27486
