### ISSUE TITLE
Cleanup Security Related Documentation & Samples

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#2589]
For example, we do not need to use `GlobalAuthenticationConfigurerAdapter` in the following sample:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-web-method-security/src/main/java/sample/ui/method/SampleMethodSecurityApplication.java

Instead we can use `@Autowired`

**Comment by snicoll** [comment]
@rwinch are you going to provide a PR for this? thanks.

**Comment by rwinch** [comment]
@snicoll I am planning on it, but I'm a bit overwhelmed with other items.

**Comment by philwebb** [comment]
Pushing back to 1.3.1. We'll have to live with it for now.

**Comment by philwebb** [comment]
@rwinch If you've got a quick crib sheet of the changes needed I can update the docs. Not sure totally all the issues that are wrong at the moment.

**Comment by snicoll** [comment]
ping @rwinch :)

**Comment by rwinch** [comment]
@snicoll Thanks for the ping. I think the problem is that by the time I advise on how to do it I might as well have done it :) I will schedule some time on Friday to send a PR.

**Comment by rwinch** [comment]
@philwebb - One thing I was wanting to (re-)ask is if we can enable no format tags in Spring Boot's Eclipse configuration? This would help make the source code more readable.

**Comment by philwebb** [comment]
@rwinch I think it's already configured, we just don't use it. Feel free to try with them if you prefer.

**Comment by wilkinsona** [comment]
@philwebb @rwinch They're switched off at the moment. I've tried turning them on (see https://github.com/wilkinsona/spring-boot/commit/3f5a962c70d9c5f8fd80c3b7cd3a12d2e94c744e). With these changes in place, and after doing `Maven -> Update Project...`, the configuration looks right in the Eclipse UI but the tags don't seem to be having any effect.

**Comment by philwebb** [comment]
Hmm, OK. Perhaps we can continue with this one without that and raise a new issue if we feel strongly about disabling auto-formatting.

**Comment by rwinch** [comment]
@snicoll @philwebb @wilkinsona I submitted a PR #5052 for your review

**Comment by philwebb** [comment]
Pushing back to 1.3.4. See comments in PR

**Comment by snicoll** [comment]
duplicates #5052
