### ISSUE TITLE
Add support for InfluxDB 2.x

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#25891]
There is a new client API for Influx 2.x (that's also compatible with 1.8.x). The new client is in a different package so that support for both can be provided. There are similar concepts and quite a number of configuration options that are different.

We can easily add support for the most basic options. See also https://github.com/spring-projects/spring-boot/pull/25319#issuecomment-784092142

**Comment by snicoll** [comment]
Considering that the new client has Spring Boot support in it, I think we should not provide dependency management for it as it creates a cycle between the project. This means we'll have to revert support here as well in favor of the Spring Boot support in the client itself.

**Comment by izeye** [comment]
Based on the label, it appears that @wilkinsona meant to close this issue.

**Comment by wilkinsona** [comment]
Indeed I did. Thanks.
