### ISSUE TITLE
/shutdown not working

### ISSUE THREAD

**Issue by aalmero** [spring-projects/spring-boot#2591]
using 1.1.10.RELEASE

after enabling the actuator, expected to have /shutdown to respond but i'm getting the page/error below. i understand that it is disabled by default but it should give 'disabled' message. 

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Mar 03 11:47:09 EST 2015
There was an unexpected error (type=Not Found, status=404).

All the other endpoints were working as expected.

What could I be missing?

Thanks
Alex

**Comment by snicoll** [comment]
it's a potential security threat to expose information you're not supposed to. Returning a 404 does what we intend. Does that make sense?

**Comment by aalmero** [comment]
I'm aware of it being a security threat and I believe it is documented. I'm just testing the functionality for any given use case in the future. 

Thanks
