### ISSUE TITLE
Simplify registration of Jackson mixin types

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#25920]
A common way to customize JSON representations with Jackson is to register mixin types. The currently most convenient way is to declare a `Module` implementation that the calls `setMixInAnnotation(…)` on the module. The module itself can be exposed as a bean and will be picked up by Boot. That registration code is quite a bit of boilerplate to be written and could be simplified as follows:

1. Introduce an annotation `@JsonMixin(Foo.class)` that would be added to the mixin type. `Foo` is the target type the mixin is registered for.
2. Boot could find classes annotated with `@JsonMixin` and register a module that registers all mixin types declared like this for the type declared in the annotation.

I.e. a plain declaration of this:

```java
@JsonMixin(MyType.class)
abstract class MyMixin { /* … */ }
```

would replace

```java
@Configuration
class MyConfiguration {

  @Bean 
  Module myModule() {
    return new MixinModule(Map.of(MyType.class, MyMixin.class));
  }

}
```

```java
class MixinModule extends SimpleModule {

  public MixinModule(Map<Class<?>, Class<?>> mixins) {
    mixins.entrySet().forEach(it -> setMixInAnnotation(it.getKey(), it.getValue()));
  }

}
```

**Comment by philwebb** [comment]
This would align quite nicely with the existing `@JsonComponent` support.

**Comment by wilkinsona** [comment]
Closing in favor of #30152.
