### ISSUE TITLE
Gradle plugin: document how to set custom dependency version

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#25935]
[Version properties](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html#dependency-versions-properties) doc only lists all the version properties.

How do you set these properties in gradle?
For example the following fails:
```
    springBoot{
        thymeleaf.version = "3.0.11"
    }
```
Related: https://github.com/spring-projects/spring-boot/issues/24602

**Comment by bclozel** [comment]
@cdalexndr there's a [dedicated section about customizing dependency version](https://docs.spring.io/spring-boot/docs/2.4.4/gradle-plugin/reference/htmlsingle/#managing-dependencies-dependency-management-plugin-customizing) in the plugin docs, which is [linked from the main documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins.html#build-tool-plugins-gradle-plugin).

**Comment by bclozel** [comment]
It doesn't hurt to add a link from there to the relevant section.
