### ISSUE TITLE
LDAP entities (@Entry annotated) are not parsed -- 'IllegalArgumentException: Not an managed type'

### ISSUE THREAD

**Issue by bogdansolga** [spring-projects/spring-boot#2595]
When running a Spring Boot application which uses both JPA entities ([@Entity](https://docs.jboss.org/hibernate/jpa/2.1/api/) annotated) and LDAP entities ([@Entry](http://docs.spring.io/spring-ldap/docs/current/apidocs/org/springframework/ldap/odm/annotations/Entry.html) annotated), an 'IllegalArgumentException: Not an managed type' exception is thrown at the deployment time.

I have created a small project which recreates the issue; the project is located [here](https://github.com/bogdansolga/spring-boot-ldap-integration), and it contains two small modules:
 * a Spring Boot module, which exposes the issue;
 * a Spring XML based module, which works properly;

Please tell me if I need to provide any additional information.

**Comment by wilkinsona** [comment]
You need to use `@EnableJpaRepositories` to tell Spring Data JPA where to look for the JPA entities. At the moment it's finding both the JPA entities and the LDAP entities as it's looking in the package when `@SpringBootApplication` is found (`com.example`) and all of its sub-packages. For example:

```java
@SpringBootApplication
@EnableJpaRepositories(basePackages="com.example.entities.db")
public class SpringBootLDAPIntegration {

    public static void main(String[] args) {
        SpringApplication.run(SpringBootLDAPIntegration.class, args);
    }
}
```

You'll also need to replace `@Repository` with `@Component` on `LdapUserRepository` or disable persistence exception translation (see #1929).

**Comment by bogdansolga** [comment]
Thank you very much for your help, Andy!

I have just one question - why do I need to replace @Repository with @Component? Are they treated differently by the application context building process?

Regards,
Bogdan

**Comment by wilkinsona** [comment]
It's covered in the issue I linked to above (#1929), particularly [this comment by @olivergierke](https://github.com/spring-projects/spring-boot/issues/1929#issuecomment-73575985).
