### ISSUE TITLE
ServletRegistrationBean, why is the URL mapping mandatory?

### ISSUE THREAD

**Issue by lfridael** [spring-projects/spring-boot#2596]
Servlet registered through ServletRegistrationBean have a default '/*' URL mapping assigned if no URL mapping is configured. Is there a reason for making the URL mapping mandatory?

The use case for "URL-free" servlets is to forward a request using `ServletContext.getNamedDispatcher()`.

In my case, I want to have the Jetty proxy servlet  act as a handler for a DispatcherServlet. (http://www.eclipse.org/jetty/documentation/9.2.3.v20140905/proxy-servlet.html)

```java
@Controller
@RequestMapping("/")
public class ProxyDispatcherController {

  @Autowired
  private ServletContext servletContext;

  @RequestMapping
  void dispatch(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    RequestDispatcher dispatcher = servletContext.getNamedDispatcher(ProxyServletConfig.PROXY_SERVLET_NAME);
    if (dispatcher != null) {
      dispatcher.forward(request, response);
    } else {
      response.sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
    }
  }
}

```

The workaround I'm using right now is to map the proxy servlet to a dummy URL and then secure that URL using `denyAll()`. It's bit of a hack, but it works.

**Comment by philwebb** [comment]
This looks like an oversight on my part, I just didn't consider your use case. We probably can change the existing default behavior but we could add a flag to skip the default registrations.
