### ISSUE TITLE
Improve publishing of repackaged executable jar with classifier

### ISSUE THREAD

**Issue by MartinAhrer** [spring-projects/spring-boot#2597]
When using the newer Gradle publishing mechanism (still in incubation though) and assigning a classifier it is required to add the artifact to be published using the fully qualified artifact path ```file("$libsDir/$project.name-$project.version-${bootRepackage.classifier}.jar")```.
It would be more handy to offer a shortcut so we can use ```artifact bootJar``` or  ```artifact bootRepackagedJar``` and don't have to know about the conventions of the boot jar.

```
bootRepackage {
    classifier = 'exec'
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            pom.withXml {
                def parentNode = asNode().appendNode('parent')
                parentNode.appendNode('groupId', 'org.springframework.boot')
                parentNode.appendNode('artifactId', 'spring-boot-starter-parent')
                parentNode.appendNode('version', springBootVersion)
            }

            artifact(file("$libsDir/$project.name-$project.version-${bootRepackage.classifier}.jar")) {
                classifier 'exec'
            }
        }
    }
}
```

**Comment by wilkinsona** [comment]
I think this duplicates #1666

**Comment by MartinAhrer** [comment]
Yes, that didn't pop up with my search for such an issue
