### ISSUE TITLE
Docs: Are there outdated APIs  in the docs? 

### ISSUE THREAD

**Issue by saleese** [spring-projects/spring-boot#2598]
I am checking the APIs in the spring-boot-docs folder(https://github.com/spring-projects/spring-boot/tree/master/spring-boot-docs/src/main/asciidoc), and it seems that I found outdated APIs. I hope some contributors may confirm whether the followings are outdated or not: 

1. RandomAccessJarFile
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/appendix-executable-jar-format.adoc
The doc refers to the RandomAccessJarFile class, which does not exist anymore. 

2. ThymeleafViewResolver
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc
The doc refers to the ThymeleafViewResolver class. However, the issue, posted to https://github.com/thymeleaf/thymeleaf-spring/issues/64, says that the class is not used anymore.

3. configurationPropertiesValidator
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc
The doc refers to the configurationPropertiesValidator.  However, no class has this method. 

Thanks in advance,
Seonah

**Comment by snicoll** [comment]
Thanks for the report, I'll have a look.

**Comment by philwebb** [comment]
I think 2) and 3) are actually correct in the docs. `ThymeleafViewResolver` is still used, it just needs to be configured with an `order` of `0`. The `configurationPropertiesValidator` is the name of a bean, not a method. See `ConfigurationPropertiesBindingPostProcessor.VALIDATOR_BEAN_NAME`.

**Comment by aheusingfeld** [comment]
@philwebb is there any sample that showcases how to use `configurationPropertiesValidator`? I couldn't find anything.

**Comment by pimlottc** [comment]
I was actually just trying to use `configurationPropertiesValidator` and was a bit confused by it.  I implemented `Validator.supports(Class<?>)` on my custom validator to indicate the target class it should be used for, but then I find that it appears to be bound to every Properties bean, causing an exception when `org.springframework.validation.DataBinder.assertValidators(Validator...)` calls `Validator.supports`.

Is there a better way I'm supposed to indicate what @ConfigurationProperties class it's supposed to validate?

**Comment by snicoll** [comment]
@pimlottc this issue is closed. Please create an issue with a sample project and we'll have a look; @aheusingfeld there is no sample at the moment and I can see it's lacking. I've created #3513

**Comment by aheusingfeld** [comment]
@snicoll thanks
