### ISSUE TITLE
Allow build image caches to use the container file system instead of volumes

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#25995]
When the Maven `spring-boot:build-image` goal or Gradle `bootBuildImage` task invokes the CNB lifecycle API, it creates and mounts volumes for the lifecycle to use as build and launch caches. Some restrictive environments like BitBucket don't allow writing to these volumes, but do allow writing to a specific location on the build container file system. The plugins should be enhanced to allow a user to configure file system locations for the build and launch caches instead of volumes. 

See https://github.com/spring-projects/spring-boot/issues/25606 for an example of an issue related to this, and the [Pack cache options RFC](https://github.com/buildpacks/rfcs/blob/main/text/0091-pack-cache-options.md) for the `pack` CLI implementation of a similar capability.

**Comment by mimozell** [comment]
Are there any plans around this? It's been a while :D

**Comment by scottfrederick** [comment]
@mimozell There are no immediate plans to implement this. We haven't seen enough demand for the feature to make it a high priority relative to other things the team is working on. Contributions are always welcomed.

**Comment by jdupont22** [comment]
Hi, it would be great to have this. 

I see some post around discussing about this issue, but most people see this like a bitbucket issue, maybe a lot of us are just ignoring why isn't working until we ding into it, like a just did today.

**Comment by scottfrederick** [comment]
Duplicates #28387
