### ISSUE TITLE
Allow build image cache volume names to be customized

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#25994]
When the Maven `spring-boot:build-image` goal or Gradle `bootBuildImage` task invokes the CNB lifecycle API, it creates and mounts volumes for the lifecycle to use as build and launch caches. These volume names are determined by the plugins, but in some cases it is useful to let the user override the default names with names of their choosing. 

See https://github.com/buildpacks/pack/issues/665 for one use case and the [Pack cache options RFC](https://github.com/buildpacks/rfcs/blob/pack-cache/text/0000-pack-cache-options.md) for the `pack` CLI implementation of a similar capability.

**Comment by izeye** [comment]
This seems to be resolved via https://github.com/spring-projects/spring-boot/pull/28292.

**Comment by scottfrederick** [comment]
Good catch, thanks @izeye.
