### ISSUE TITLE
Auto-configure micrometer DiskSpaceMetrics

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#25996]
AFAICT we don't currently configure `DiskSpaceMetrics`.

**Comment by izeye** [comment]
For your information, there was a PR against the `micrometer-spring-legacy` module that was pending for some reason.

See https://github.com/micrometer-metrics/micrometer/pull/703

/cc @jkschneider

**Comment by snicoll** [comment]
Closing in favor of PR #26001
