### ISSUE TITLE
Provide a mechanism to disable MetricFilterAutoConfiguration's metric filter

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-boot#2599]
Our project already uses Dropwizard `com.codahale.metrics.servlet.InstrumentedFilter`.
For us `MetricFilterAutoConfiguration.MetricsFilter` adds noise to our ops team with its added metrics.
We would like to remove it but we could not find a way.
One "easy" way would be for `MetricFilterAutoConfiguration.MetricsFilter` to be `@ConditionalOnMissingBean(name="metricFilter")`

**Comment by wilkinsona** [comment]
If you don't want the `metricFilter` bean to be created you can disable the auto-configuration:

    @SpringBootApplication(exclude=MetricFilterAutoConfiguration.class)

**Comment by paskos** [comment]
Unfortunately it's not possible.
Our `Main` class annotated with `@SpringBootApplication` is in a core project without dependency to `spring-boot-actuator.jar`.

**Comment by wilkinsona** [comment]
Making the bean `@ConditionalOnProperty` is more consistent with the rest of Spring Boot. See [`PersistenceExceptionTranslationAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/dao/PersistenceExceptionTranslationAutoConfiguration.java#L38), for example

**Comment by paskos** [comment]
I don't mind what type of `@ConditionalOn` as long as it is configurable

**Comment by cemo** [comment]
I have opened two issue and both them are resolving this issue. Please see #2661 and see #2660.

**Comment by wilkinsona** [comment]
This was fixed in https://github.com/spring-projects/spring-boot/commit/d0cf6b534bf55b718ea8bf0f2e311a974f523e1b#diff-241770c23241a05163f6cae3d9313139. `endpoints.metrics.filter.enabled: false` can now be used to turn the filter off. Alternatively, the whole auto-configuration can be excluded by class name thanks to https://github.com/spring-projects/spring-boot/commit/a6f671be3ed4ce9d70c8c5ffc76b8130bbbcc424.

**Comment by paskos** [comment]
Thanks a lot guys !!!

**Comment by khong07** [comment]
Hi,

I'm on spring boot 1.3.0 but the property is `endpoints.metrics.enabled` and not ` endpoints.metrics.filter.enabled`.

**Comment by wilkinsona** [comment]
@khong07 Thanks for pointing this out. That shouldn't be the case. #4365 will reinstate `endpoints.metrics.filter.enabled` and allow the filter to be switched off independently.
