### ISSUE TITLE
Switch banner to use a Log

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#26]
Currently the Banner implementation uses a Printstream to write the log, it would be nice if the Banner would be printen (also) using a Log. That way it would appear in logfiles also, making it quite clear when an application started.

**Comment by btiernay** [comment]
@philwebb now that there is the `Banner` abstraction, would it be possible to make this configurable? I personally would like to have this in the logs as it clearly delineates the process boundary of multiple executions of the process. The default should still be `stdout` however.

**Comment by philwebb** [comment]
@btiernay It should be possible I think. I'll open a new issue.

**Comment by btiernay** [comment]
@philwebb Bootiful!
