### ISSUE TITLE
Is there any way to configure <display-name> 

### ISSUE THREAD

**Issue by roldancer** [spring-projects/spring-boot#2600]
Hi All,
    I would like to know if it possible to configure the web.xml element "display-name" using spring boot properties ?

Many thanks.

**Comment by snicoll** [comment]
The `display-name` of the web application you mean? There is no property to configure this now but you could extend from `EmbeddedServletContainerFactory` to do it yourself.

In particular, check `TomcatEmbeddedServletContainerFactory` and the `postProcessContext` that gives you the `Context` instance. You can call `setDisplayName` on that.

What is your use case?

**Comment by roldancer** [comment]
I'm asking that because we use a java agent (CA Wily Introscope), this agent indentifies each web application by the "display name".
Currently we are monitoring several spring boot application, but the problem is that all of them are labeled "rootContext", by the way "rootContext" is the default name when "display-name" is null.

Would be possible to improve spring boot project?

**Comment by snicoll** [comment]
I am not sure that we can configure the display name for all embedded servers that we support but we can certainly give it a try. PR welcome.

**Comment by roldancer** [comment]
Yes, we are using tomcat...

**Comment by parvez1487** [comment]
Hi,
can u pls let us know how to configured wily with spring boot.

**Comment by parvez1487** [comment]
Hi,
can u pls let us know how to configured wily with spring boot.

**Comment by parvez1487** [comment]
Hi,
can u pls let us know how to configured wily with spring boot.

**Comment by parvez1487** [comment]
Hi,
can u pls let us know how to configured wily with spring boot.

**Comment by parvez1487** [comment]
Hi,
I have created a sample spring boot app and deployed on linux machine where wily agent is running,can u pls let us know how to configured wily with spring boot.

**Comment by kieste** [comment]
+1

**Comment by Sawon90** [comment]
Is there any way to set display-name on non-embedded container like on installed tomcat?

**Comment by snicoll** [comment]
@Sawon90 as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow or Gitter.
