### ISSUE TITLE
Provide auto-configuration for using Apache HttpClient 5 with WebClient

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#26004]
Framework 5.3 added [support for Apache HttpClient 5 to `WebClient`](https://github.com/spring-projects/spring-framework/pull/24700). We should add corresponding support in Spring Boot. I think that's some dependency management and some auto-configuration to create an `HttpComponentsClientHttpConnector` when it's on the classpath (and Jetty and Reactor Netty are not).

**Comment by m1ngyuan** [comment]
typos spring-boot-project/spring-boot-dependencies/build.gradle#L497

**Comment by wilkinsona** [comment]
Thanks, @m1ngyuan. I've fixed that in eda9fe4952da9897fcd22673eba737d912a5db83.
