### ISSUE TITLE
Does   spring-boot-maven-plugin  support binding volume in pack CLI

### ISSUE THREAD

**Issue by Paradox98** [spring-projects/spring-boot#26033]
Does spring-boot-maven-plugin  support binding volume in pack CLI

```
pack a --volume  /a:/b 
```

**Comment by philwebb** [comment]
See #23518. Support was added in 2.5.0-M3. The 2.5.0 release is due May 20.

**Comment by Paradox98** [comment]
thx ,but spring-native need 2.4.4
