### ISSUE TITLE
Invalid property arrays overriding in profile-specific property files

### ISSUE THREAD

**Issue by mkadan** [spring-projects/spring-boot#2611]
Spring Boot 1.2.2.RELEASE

I'm using `@ConfigurationProperties` annotation on class to populate properties.
Consider having these property files:

application.yml:
--------------------

```
urls:
                      - http://www.aargauerzeitung.ch
                      - http://www.bzbasel.ch
                      - http://www.basellandschaftlichezeitung.ch
                      - http://www.limmattalerzeitung.ch
```

application-dev.yml:
--------------------

```
urls:
                      - http://google.com
```

When launching the app with `-Dspring.profiles.active=dev` I got the following value for "urls":

```
                      - http://google.com
                      - http://www.bzbasel.ch
                      - http://www.basellandschaftlichezeitung.ch
                      - http://www.limmattalerzeitung.ch
```

but it should be just:

```
                      - http://google.com
```

**Comment by philwebb** [comment]
Profile specific properties are loaded in addition to `application.properties` so this is expected behavior (see http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-profile-specific-properties).

**Comment by mkadan** [comment]
So is there a way to reduce the size of an array from the profile-specific properties?

**Comment by philwebb** [comment]
I'm not sure that we offer a convenient way to do this at the moment. The `ConfigFileApplicationListener` class is responsible for loading the configuration. 

Probably the easiest way at the moment is to create two profiles. There is also an open issue (#1219) that we plan to address in 1.3.
