### ISSUE TITLE
Include spring.profiles.group in additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by Been24** [spring-projects/spring-boot#26127]

**Comment by snicoll** [comment]
There's no reference to `spring.profiles.group` anywhere in the reference documentation and the property is not available in IDE auto-completion either.

**Comment by philwebb** [comment]
It's missing from the meta-data but it is [in the reference docs](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-profiles-groups)

**Comment by snicoll** [comment]
Sorry about that Phil. I search for the key and it isn't present anywhere because we use the yaml form.
