### ISSUE TITLE
Asciidoctor incompatible with Gradle 7

### ISSUE THREAD

**Issue by Prieschl** [spring-projects/spring-boot#26136]
The currently used version of Asciidoctor seems to be incompatible with Gradle 7. Therefore the build fails for following command `.\gradlew.bat asciidoctor`. 

Used Configuration in Spring Initializr:
- Project: Gradle
- Language: Kotlin
- Spring Boot: 2.5.0 (SNAPSHOT)
- Dependencies: Spring REST Docs

Adaptions:
- build.gradle.kts: fixed snippetsDir and dependsOn Test task
- Added demo\src\docs\asciidoc\index.adoc as example

See attached reference project and console log:
- [console-log.txt](https://github.com/spring-projects/spring-boot/files/6319027/console-log.txt)
- [demo.zip](https://github.com/spring-projects/spring-boot/files/6319026/demo.zip)

**Comment by wilkinsona** [comment]
Thanks for the report, @Prieschl. Spring Boot doesn't have an opinion about the version of Asciidoctor's Gradle plugin. I guess you're referring to the version that's generated by start.spring.io so I've opened https://github.com/spring-io/start.spring.io/issues/676.

**Comment by Prieschl** [comment]
@wilkinsona Thank you for creating the issue for start.spring.io.
Please also notice that AFAIK there isn't any compatible version of Asciidoctor's Gradle plugin for Gradle 7 at the moment.

**Comment by wilkinsona** [comment]
id "org.asciidoctor.jvm.convert" version "3.3.2" works fine as far as I know. I've just double-checked with one of REST Docs' samples and it worked as expected.
