### ISSUE TITLE
BatchAutoConfiguration requires the JdbcOperations class in the classpath in order to be active, but does not use it

### ISSUE THREAD

**Issue by lokkju** [spring-projects/spring-boot#2613]
Is there a reason that JdbcOperations is required via the ConditionalOnClass annotation by the BatchAutoConfiguration class?  It is not used anywhere in BatchAutoConfiguration, and there are many use cases to run jobs without any JDBC connection.

It took me a while to figure out why the hell my jobs weren't running...

**Comment by snicoll** [comment]
`BatchDatabaseInitializer` requires `spring-jdbc` on the classpath and I assume that the condition on `JdbcOperations` was there to make that explicit. Is `spring.batch.initializer.enabled` set to `false` in your environment? If so, spring-jdbc does not seem to be required indeed.

**Comment by lokkju** [comment]
Spring Data Cassandra isn't supported by a default initialization anyway, iirc.
Wouldn't it make more sense to put the `JdbcOperations` condition on the `BatchDatabaseInitializer`?

**Comment by philwebb** [comment]
I think it should be safe to move the condition. @dsyer @mminella thoughts?

**Comment by mminella** [comment]
@lokkju what `JobRepository` implementation are you using?  The only production grade one we provide with the framework is based on JDBC and uses `JdbcOperations`...

**Comment by lokkju** [comment]
Looks like I'm using `org.springframework.batch.core.repository.support.SimpleJobRepository` - it's what results from extending having my own `@Configuration` class extend `BatchAutoConfiguration`.  Is `SimpleJobRepository` is not production-ready?  the docs don't mention anything...

**Comment by snicoll** [comment]
@mminella careful, the `DatabaseInitializer` also uses `spring-jdbc`. Not sure it's relevant in this use case but if we move the condition, that one should have it at least (on another class most probably).

**Comment by mminella** [comment]
@snicoll I'm actually proposing *not* removing the dependency.  @lokkju {{SimpleJobRepository}} *is* production ready and uses a database (and therefore {{JdbcOperations}}) for it's persistence mechanism.

**Comment by philwebb** [comment]
@lokkju Do you have that `spring-jdbc` jar on your classpath currently?

**Comment by lokkju** [comment]
it doesn't seem so.  relevant output of `mvn dependency:list`:

```
[INFO] The following files have been resolved:
[INFO]    org.slf4j:log4j-over-slf4j:jar:1.7.10:compile
[INFO]    com.eltoro.iptools.libs:libadrequest:jar:1.0.0:compile
[INFO]    org.springframework:spring-aop:jar:4.1.5.RELEASE:compile
[INFO]    org.springframework:spring-tx:jar:4.1.5.RELEASE:compile
[INFO]    xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO]    xpp3:xpp3_min:jar:1.1.4c:compile
[INFO]    com.google.guava:guava:jar:18.0:compile
[INFO]    com.beust:jcommander:jar:1.27:test
[INFO]    org.liquibase:liquibase-core:jar:3.3.2:compile
[INFO]    com.thoughtworks.xstream:xstream:jar:1.4.7:compile
[INFO]    com.datastax.cassandra:cassandra-driver-core:jar:2.1.4:compile
[INFO]    org.slf4j:jul-to-slf4j:jar:1.7.10:compile
[INFO]    org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO]    org.springframework:spring-expression:jar:4.1.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot:jar:1.2.2.RELEASE:compile
[INFO]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    com.ibm.jbatch:com.ibm.jbatch-tck-spi:jar:1.0:compile
[INFO]    org.springframework.retry:spring-retry:jar:1.1.0.RELEASE:compile
[INFO]    org.springframework:spring-context:jar:4.1.5.RELEASE:compile
[INFO]    org.yaml:snakeyaml:jar:1.14:compile
[INFO]    ch.qos.logback:logback-classic:jar:1.1.0:compile
[INFO]    com.google.common:s2-geometry:jar:1.0.0:compile
[INFO]    com.datastax.cassandra:cassandra-driver-dse:jar:2.0.4:compile
[INFO]    org.springframework.boot:spring-boot-autoconfigure:jar:1.2.2.RELEASE:compile
[INFO]    org.springframework:spring-beans:jar:4.1.5.RELEASE:compile
[INFO]    org.beanshell:bsh:jar:2.0b4:test
[INFO]    org.springframework.batch:spring-batch-core:jar:3.0.3.RELEASE:compile
[INFO]    org.springframework:spring-core:jar:4.1.5.RELEASE:compile
[INFO]    com.codahale.metrics:metrics-core:jar:3.0.2:compile
[INFO]    ch.qos.logback:logback-core:jar:1.1.0:compile
[INFO]    org.codehaus.jettison:jettison:jar:1.2:compile
[INFO]    org.springframework.data:spring-data-commons:jar:1.9.2.RELEASE:compile
[INFO]    javax.batch:javax.batch-api:jar:1.0:compile
[INFO]    org.springframework.batch:spring-batch-infrastructure:jar:3.0.3.RELEASE:compile
[INFO]    org.testng:testng:jar:6.8.7:test
[INFO]    org.springframework.data:spring-data-cassandra:jar:1.1.2.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-logging:jar:1.2.2.RELEASE:compile
[INFO]    aopalliance:aopalliance:jar:1.0:compile
[INFO]    com.google.protobuf:protobuf-java:jar:2.6.1:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.10:compile
[INFO]    org.springframework.data:spring-cql:jar:1.1.2.RELEASE:compile
[INFO]    org.projectlombok:lombok:jar:1.14.8:provided
[INFO]    org.springframework.boot:spring-boot-starter:jar:1.2.2.RELEASE:compile
[INFO]    junit:junit:jar:4.12:test
```

**Comment by lokkju** [comment]
Maybe relevant:
`2015-03-10 04:08:00.959  WARN 68437 --- [           main] o.s.b.c.c.a.DefaultBatchConfigurer       : No datasource was provided...using a Map based JobRepository`

**Comment by mminella** [comment]
@lokkju That means you're using the Map based JobRepository (same `SimpleJobRepository...different DAOs).  That configuration isn't recommended for production environments (the Map isn't thread safe, etc).

**Comment by snicoll** [comment]
I am still confused about this whole discussion. What about if someone wants to execute some jobs using the simple map repository (test purposes or whatever)? Are we ruling out that use case?

**Comment by lokkju** [comment]
Perhaps the default DAOs should be a bit more production ready?  It feels weird to have batch rely on JDBC, when there are so many way to use batch that have nothing to do with JDBC.

**Comment by dsyer** [comment]
The default daos *are* production ready and they *are* JDBC (that's sort of the point).

**Comment by snicoll** [comment]
So the outcome here is that `JdbcOperations` is required.
