### ISSUE TITLE
Provide auto configuration mechanism to customize SpringApplication class

### ISSUE THREAD

**Issue by joshuawhite929** [spring-projects/spring-boot#2614]
For example, to customize Spring Boot's banner, we have two options:

1.  Add a banner.txt
2.  Use SpringApplication directly to set a customer Banner implementation

Extending the SpringApplication class is not really feasible as the static "run" methods will create an instance of SpringApplication and ignore your subclass.

It would be nice if I could leverage the same spring boot  auto configuration mechanism or the spring.factories mechanism to customize the banner or anything else within the SpringApplication class.  Another option may be to use a callback mechanism similar to how DelegatingWebMvcConfiguration /WebMvcConfigurer works.  This would allow those who build on top of SpringBoot to customize the application without having endusers add boiler plate customization to their SpringApplication instance directly.

**Comment by snicoll** [comment]
You're adding an extra layer of indirection by doing that so it's harder to know who took the decision. The auto-configuration mechanism has a report to help you figuring out what was applied and why. 

I guess what I am saying is that I don't like the idea of adding such mechanism without the proper reporting. 

You could always create your own builder or your own `SpringApplication` with different defaults.

**Comment by philwebb** [comment]
Actually we also have a bit of a chicken/egg situation. The banner gets displayed early (before the application context has been created) so I don't think we can use auto-configuration to change it.
