### ISSUE TITLE
Thread dump endpoint: use plain text as default

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#26199]
https://github.com/spring-projects/spring-boot/commit/c5cae282613d4229a8e4e9b0c3de5a1924d177a9 added support for plain text thread dump (https://github.com/spring-projects/spring-boot/issues/2339)

Issuing a http request without `accepts: application/json` (such as browser request) returns json format by default.
The json format is very hard to read by humans. For example, a stacktrace element has 8 fields (10 lines pretty formatted) so reading a stacktrace requires scrolling multiple pages...
```
        {
          "classLoaderName": null,
          "moduleName": null,
          "moduleVersion": null,
          "methodName": "ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed",
          "fileName": "AbstractTransactionAspect.aj",
          "lineNumber": 67,
          "className": "org.springframework.transaction.aspectj.AbstractTransactionAspect",
          "nativeMethod": false
        },
```

The plain text format is more compact and easier to read by humans, and should be used by default instead.
This way, when requesting the thread dump through browser it will be easier to read.

**Comment by cdalexndr** [comment]
> Is there a particular reason why you can't use a command line client or a browser plugin that allows you to control the accept header when making a request to the thread dump endpoint?

The request requires authorization (spring security), so after login page I get the threaddump on my browser.
I rather make a custom endpoint for plain text threaddump than install a browser plugin for making a custom request.

**Comment by wilkinsona** [comment]
We've discussed this and decided that this isn't a change that we want to make. [You can achieve what you want with a little bit of your own code](https://github.com/spring-projects/spring-boot/issues/26229#issuecomment-826285620) and, as explained above, the proposed change wouldn't be easy to make so the cost outweighs the benefit. Thanks anyway for the suggestion.

**Comment by barfoo4711** [comment]
Sad that this was closed as won't fix. Therefore asking if there is a way/tooling to convert the produced json to plain text later on? I've googled around but not found anything so far.

**Comment by wilkinsona** [comment]
Not that we're aware of. We recommend either making a request with an appropriate accept header or using the suggestion [linked to above](https://github.com/spring-projects/spring-boot/issues/26199#issuecomment-830221721) to force the text/plain response.
