### ISSUE TITLE
Failed to bind properties under 'spring.cloud.gateway.routes[0].uri' to java.net.URI:

### ISSUE THREAD

**Issue by tshepangm** [spring-projects/spring-boot#26208]
Running Spring Boot v2.2.6 
And on docker run <container_id>

I get the below error 

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-22 13:53:42.066 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.gateway.routes[0].uri' to java.net.URI:

    Property: spring.cloud.gateway.routes[0].uri
    Value: ${RATE_LIMITED_URI}
    Origin: class path resource [application.yaml]:6:16
    Reason: failed to convert java.lang.String to @javax.validation.constraints.NotNull java.net.URI

Action:

Update your application's configuration
```

**Comment by snicoll** [comment]
@tshepangm thanks for the report but we can't really figure out if that is a problem in Spring Boot with the information that you've shared. What is the value for `spring.cloud.gateway.routes[0].uri` (at line 6 of your `application.yaml`) for a start?

**Comment by tshepangm** [comment]
Hi snicoll,thanks 

I did a locate of the application.yaml file and I gof four 

I am new on this product,and below is how the application.yaml is configured

spring:
  cloud:
    gateway:
      routes:
        - id: ratelimited_route
          uri: ${RATE_LIMITED_URI}
          predicates:
          - Path=${RATE_LIMITED_PATH}
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@apiRateLimiter}"
                key-resolver: "#{@apiKeyResolver}"


root@server api-rate-limiter]# locate application.yaml
/root/api-rate-limiter/build/resources/main/application.yaml
/root/api-rate-limiter/src/main/resources/application.yaml
/root/api-rate-limiter/src/test/resources/application.yaml
/var/lib/docker/overlay2/e5bf3934e937225e0993ca1127725bd3364bc571dd3ff19fdff738b13fad2273/diff/app/resources/application.yaml
[root@server api-rate-limiter]#

**Comment by snicoll** [comment]
Thanks for the follow-up and sorry, I should have paid attention to the error message as the value is already provided. There's no problem that we can fix for you here. `${RATE_LIMITED_URI}` hasn't been replaced and this not a valid URI, hence the message that you see. You should make sure that `RATE_LIMITED_URI` has a value and is a valid URI.

If you have more questions, please follow-up on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
