### ISSUE TITLE
'spring.web.resources.cache.use-last-modified=false' doesn't work with Spring MVC

### ISSUE THREAD

**Issue by fbuechler** [spring-projects/spring-boot#26212]
We're using Spring Boot 2.4.4 with Spring MVC to build an application that serves static resources. We noticed that although we set `spring.web.resources.cache.use-last-modified=false`, the server adds a `Last-Modified` header.
Looking at the source, the property only seems to be used in `WebFluxAutoConfiguration` and not in `WebMvcAutoConfiguration` (https://github.com/spring-projects/spring-boot/search?q=setuselastmodified). Is this intentional or an oversight?

**Comment by snicoll** [comment]
Thanks for the report, that looks like an oversight to me.

**Comment by wilkinsona** [comment]
This looks like a regression. It was there originally (in 2.4.0) but was lost in, I think, https://github.com/spring-projects/spring-boot/commit/f1fcfa6fc30c527ab5dd89ddeb069cd0f6038c40.
