### ISSUE TITLE
gradle plugin: create zip and tar distributions with fat runnable jar 

### ISSUE THREAD

**Issue by houbie** [spring-projects/spring-boot#2622]
When using fat runnable jars, it makes sense to have them also in the zip and tar distributions.
I tried to achieve this by adapting the distribution content, but that doesn't work because the bootRepackage task depends on the distributions tasks.
Is there a reason for this task dependency (I would expect the reverse dependency)?

**Comment by philwebb** [comment]
I can't recall a specific reason for the distribution dependencies, it might have just been the easiest way to get the repackage task to run at the appropriate time.

Do you have an example gradle file that you could provide to show how tar/zip distributions are typically created?

**Comment by houbie** [comment]
The distZip and distTar tasks come with the gradle application plugin (added by spring boot plugin).
See http://gradle.org/docs/current/userguide/application_plugin.html , section 45.4

I currently work around this issue with new tasks that overwrite the zip and tar distros:
```java
def distributionsCopySpec = copySpec {
    into("$name-$version") {
        into('lib') {
            from libsDir
            include '*.jar' //copy the fat jar created by bootRepackage
        }
        from 'README.md'
        into('bin') {
            from 'bin' //custom start script based on startScripts task output
        }
    }
}

task fatJarZip(type: Zip, dependsOn: 'bootRepackage') { with distributionsCopySpec }
task fatJarTar(type: Tar, dependsOn: 'bootRepackage') { with distributionsCopySpec }

uploadArchives.dependsOn(fatJarZip, fatJarTar)
```
If the dist tasks could depend on the bootRepackage task, this would be a bit easier and it would make sense to have this as default behavior.

**Comment by btiernay** [comment]
This would be a great addition. Having some serious headaches with Spring Boot and `distTar` right now due to #2679.

**Comment by rcordeau** [comment]
Same here - this would be a great addition. I guess for now the work around is custom distribution tasks but this seems... meh.
