### ISSUE TITLE
Documentation has wrong key for DataSourceHealthIndicator

### ISSUE THREAD

**Issue by roberthunt** [spring-projects/spring-boot#26268]
The documentation suggest the datasource health endpoint (actuator) can be enabled/disabled using the key `datasource`: `management.health.datasource.enabled` but I think it should be `db`: `management.health.db.enabled` which was the case for Spring Boot 2.3.x and I don't think it's changed. The current version of `DataSourceHealthContributorAutoConfiguration` has the annotation `@ConditionalOnEnabledHealthIndicator("db")` which has the key `db`.

Current docs: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-health

**Comment by snicoll** [comment]
> The documentation suggest the datasource health endpoint (actuator) can be enabled/disabled using the key datasource: management.health.datasource.enabled

Can you please share which specific part of the doc you are referring to? Is it the table in the "Auto-configured HealthIndicators" that has a key now alongside the name and the description? I am asking as this is the only place where I see a problem and those keys [are in the same state in `2.3.x`](https://docs.spring.io/spring-boot/docs/2.3.x/reference/htmlsingle/#production-ready-health-indicators).

**Comment by roberthunt** [comment]
Yes, this is the part of the latest docs:

![Screenshot 2021-04-28 at 13 27 42](https://user-images.githubusercontent.com/567676/116404113-3a950380-a826-11eb-988e-36fbca57aed1.png)

I have been using the property `management.health.db.enabled` under Spring Boot 2.3.x so I guess the docs for 2.3 are also wrong.

**Comment by snicoll** [comment]
Thanks for the feedback, now we're on the same page.
