### ISSUE TITLE
Pass maven profile as spring profile.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-boot#2626]
Hi,

here's an interesting idea that i think would be beneficial to a lot of people. It would be really nice if the spring-boot maven plugin would pass the maven profile as a spring boot active profile. So let's say i write down:

```
$ mvn spring-boot:run -Pprod
```

then this would also activate the `spring.profiles.active=prod`. You can get the maven active profiles in the mojo from the project building request.

**Comment by snicoll** [comment]
We should add a boolean flag `propagateMavenProfile` or something that should be enabled to have this behaviour.  

What happens if the user has specified some profiles on the command line (or via the configuration of the plugin?). It's not that obvious what should happen. I think the easiest would be to propagate only if no profiles have been set already.

**Comment by philwebb** [comment]
It's quite a nice idea. Perhaps we could set a new system property that `ConfigFileApplicationListener` could pickup. `spring.profiles.build.active`?

**Comment by olivergierke** [comment]
Slightly related I got a request to configure the Maven plugin's `run` goal to use a certain Spring profile. @dsyer suggested to use the `jvmArguments` configuration option and that seems to work fine. I guess that could also be used in a profile to forward the profiles name as a workaround.

**Comment by snicoll** [comment]
see also https://github.com/snicoll/spring-boot/commit/ad2330f513d0cdbd9950fecb7e70fc45f74af843

**Comment by spilth** [comment]
@olivergierke Where is the request you got? I'd love to see an `<activeProfiles>` element added to `spring-boot:run` as an optional parameter.

I currently use `<jvmArguments>-Dspring.profiles.active=${spring.profiles.active}</jvmArguments>` but would love to do just `<activeProfiles>${spring.profiles.active}</activeProfiles>`. In my opinion it helps the concept of Profiles feel like a more prominent feature of Spring.

**Comment by snicoll** [comment]
If you click on the link just above your comment you'll see it's implemented. I think we probably need to pair with the Gradle support somehow. I'll bring that up on the team call today.

**Comment by spilth** [comment]
—

**Comment by philwebb** [comment]
In hindsight we think it might be confusing to mix build profiles and Spring profiles.
