### ISSUE TITLE
spring-boot-ci jdk16 docker image configured with java8

### ISSUE THREAD

**Issue by daniellavoie** [spring-projects/spring-boot#26285]
Hello team!

Just wanted to share that I've noticed that the latest `spring-boot-ci` jdk-16 image on [docker hub](https://hub.docker.com/layers/springci/spring-boot-ci-jdk16/2.5.x/images/sha256-4090e63f495da8ef721db750f740e1e8a45a288e2c4148953a2d6e989eafd4a2?context=explore) is configured with java 8. I'm pretty sure this has an impact on current builds of https://ci.spring.io.

<img width="741" alt="Screen Shot 2021-04-28 at 2 00 40 PM" src="https://user-images.githubusercontent.com/4403970/116451207-32d75e00-a82a-11eb-8e4a-f7e1de5f9066.png">

Cheers!

**Comment by wilkinsona** [comment]
The image is configured with both Java 8 and Java 16:

https://github.com/spring-projects/spring-boot/blob/c548693fa10a01d3fa23eee55eeca340764b02d4/ci/images/ci-image-jdk16/Dockerfile#L6

We run Gradle on Java 8 and use its tool chain support to compile and test with Java 16. Thanks anyway.

**Comment by daniellavoie** [comment]
I can see that now. Thank you for your explanations.

I'm lazy and been spoiled by your previous jdk15 image which had 15 as it's default jdk. Time to fly with my own images :)
