### ISSUE TITLE
springboot data left outer join is not part of query

### ISSUE THREAD

**Issue by eranf91** [spring-projects/spring-boot#26280]
I have the following code, work perfectly fine with springboot 2.4.3, but fails with 2.4.4
The bug is relate to springboot data jpa
I have the following class:

```
@Entity
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class User {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    Long id;

    @Embedded
    Addition addition;

    @Embeddable
    @Getter
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder(toBuilder = true)
    public static class Addition {

        @Column(table = "user_addition")
        String name;
    }
}
```
Then having the following repository:

```
public interface UserRepository extends JpaRepository<User, Long>{
    boolean existsByAddition_Name(String name);
}
```

In springboot 2.4.3
The query generated from calling: existsByAddition_Name
include the left outer join of user_addition table

In springboot 2.4.4
The query generated from calling: existsByAddition_Name
**Does not** include the left outer join of user_addition table

**Comment by wilkinsona** [comment]
Thanks for the report. Spring Data JPA is managed as a separate project. You can report the problem to them [here](https://github.com/spring-projects/spring-data-jpa/issues).
