### ISSUE TITLE
Error in Javadoc example for WebIntegrationTest.randomPort

### ISSUE THREAD

**Issue by mjustin** [spring-projects/spring-boot#2628]
[The Javadocs](http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/WebIntegrationTest.html#randomPort%28%29)  for WebIntegrationTest#randomPort() give an example using `@Value("server.local.port")`.  However, this does not work for two reasons.  First, the actual property (as mentioned in the [Spring Boot documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-discover-the-http-port-at-runtime)) is "local.server.port", not "server.local.port".  Secondly, the value in the example is the String literal "server.local.port", not the value of the property (note the lack of surrounding `${}`), so the value injected would be the literal string, not the property value.

Expected value in the documentation should be `@Value("${local.server.port}")`.

**Comment by philwebb** [comment]
Thanks for reporting!
