### ISSUE TITLE
Update development guidelines to note the need to build with a HotSpot JVM

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#26309]
With thanks to @Buzzardo for finding the problem, we could change to a different metric or we could update the contributing guidelines to recommend building on HotSpot. I'm tempted to do the latter as, without an OpenJ9 CI build, it may get broken again in the future.

**Comment by Buzzardo** [comment]
We should include that HotSpot is from java.net (Oracle). sdkman doesn't make that clear, and other tools may also not be helpful.

**Comment by wilkinsona** [comment]
It doesn't have to be. https://adoptopenjdk.net provides HotSpot and OpenJ9 binaries.

**Comment by snicoll** [comment]
+1 for recommending to build on HotSpot.

**Comment by philwebb** [comment]
When we fix this we'll also extract some of the stuff from `CONTRIBUTING.adoc` to the wiki

**Comment by scottfrederick** [comment]
Updated in the [`Building from Source` section](https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code#building-from-source) of the wiki
