### ISSUE TITLE
Unrestricted Health check should be able to be cached

### ISSUE THREAD

**Issue by ericdahl** [spring-projects/spring-boot#2630]
If ```endpoints.health.sensitive``` is set to ```false```, then the caching feature of the Health endpoint is bypassed due to this check in ```HealthMvcEndpoint```:

```java
if (isCacheStale(accessTime) || isSecure(principal) || isUnrestricted()) {
	this.lastAccess = accessTime;
	this.cached = this.delegate.invoke();
}
```

It would be nice to still be able to have the caching functionality even if the health endpoint is unrestricted. For example, if I have an intensive health check which is unrestricted, but running on a local IP or otherwise protected, I may still want to have the value be cached so that an overly zealous health check doesn't cause the service to degrade.

**Comment by wilkinsona** [comment]
I have a fix for this issue [here](https://github.com/wilkinsona/spring-boot/commit/c4f4c1c941df57aa48ecee1f7f9a4473c417cbef).

@philwebb I'd welcome your thoughts on the fix. Specifically, I'm wondering if we might also want a property to force caching for secure access. If we do, or we think we might in the future, then a single, more generally named property could be preferable to one that controls caching for unrestricted access and one that controls caching for secure access. `endpoints.health.always-cache`, perhaps?

**Comment by philwebb** [comment]
@wilkinsona We could consider just always caching results. The current logic is a little complex and I'm wondering if the `time-to-live` property alone is enough for most people. The [docs](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_security_with_healthindicators) already imply that caching occurs regardless of how the endpoint is accessed or if it is secured.

**Comment by wilkinsona** [comment]
@philwebb Sold. The current logic made my head hurt a bit when I was working on this fix; simplifying it definitely sounds good to me.
