### ISSUE TITLE
Reference documentation has a 404 for banner-logo.svg

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#26305]
2.5.0-RC1's documentation is trying to load https://docs.spring.io/spring-boot/docs/2.5.0-RC1/reference/img/banner-logo.svg which doesn't exist. Snapshots are trying to load https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/img/banner-logo.svg which also doesn't exist.

**Comment by dreis2211** [comment]
@wilkinsona It loads for me when accessing https://docs.spring.io/spring-boot/docs/2.5.0-RC1/reference/htmlsingle/ - am I missing something?

![image](https://user-images.githubusercontent.com/6304496/116593303-3b5e9000-a921-11eb-81f9-4790cafdb4f6.png)

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. That prompted me to look a bit more closely and I think it may be browser-specific. I'm using Safari on macOS. It's fine in Chrome. Note the `/htmlsingle` in your screenshot that's missing from the URL in Safari. This is probably a Spring Asciidoctor Backends problem.

**Comment by wilkinsona** [comment]
Closing in favour of https://github.com/spring-io/spring-asciidoctor-backends/issues/38.
