### ISSUE TITLE
Apply RSocketConnectorConfigurer beans to the RSocketRequester.Builder

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#26304]
Currently, Spring Boot creates a prototype bean for `RSocketRequester.Builder`, since this stateful builder can be used in several places in a single application, with different purposes and customizations.

Libraries might want to configure the RSocket connector for all requester instances (for example for instrumentation purposes). We should ensure that `RSocketConnectorConfigurer` beans are picked up by the `RSocketRequesterAutoConfiguration` and applied to all builder instances.

**Comment by snicoll** [comment]
Closing in favor of PR #26341
