### ISSUE TITLE
compile use jdk 1.7 but run use 1.6

### ISSUE THREAD

**Issue by saifiahmada** [spring-projects/spring-boot#2632]
I compile spring boot application using jdk 1.7 to application.jar file, but when I run application.jar on machine that installed jdk 1.6,  this error is occured

java.lang.unsupportedclassversionerror: javax/annotation/managedbean : unsupport ed major.minor version 51.0

is it must be jdk 1.6 to compile spring boot so that running in jdk 1.6 machine ?

thanks

**Comment by snicoll** [comment]
Please post your question on [stackoverflow](https://stackoverflow.com/questions/tagged/spring-boot)

That question of yours is unrelated to Spring Boot. Here is a [good answer](http://stackoverflow.com/questions/10107831/is-it-possible-to-compile-class-files-with-the-java-7-sdk-which-can-run-on-java).

Please note that they are [some limitations of running a Spring Boot app on Java6](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-java-6)

**Comment by mathiaslin** [comment]
I'm having the same issue and wonder which dependency it is (for javax.annotation.managedbean) that should be changed, according to the Spring boot documentation.

**Comment by mathiaslin** [comment]
I found that using an older version of Spring Boot, 1.1.2.RELEASE, instead of 1.2.3-RELEASE, solved the problem for me.

**Comment by takacsot** [comment]
For me the problem was coming from tomcat. Bu default it wants to use tomcat 8 (requires java 7) but when I have changed  config to use tomcat 7 it was fine.

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_use_tomcat_7_with_maven
