### ISSUE TITLE
Multi-page links may be broken with 2.5

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#26335]
We've renamed some of the files which means some links might be broken. For example `spring-boot-features.html` is now `features.html`.

**Comment by SivaTharun** [comment]
@philwebb if you don't mind, can i work on the above issue. i would like to contribute to the spring-boot git repository.

**Comment by snicoll** [comment]
@SivaTharun thanks for the offer but there's nothing to be done in this code base. To still honor URLs with the previous name, we need to put redirections in place on the server.

I can see this has been applied in the meantime so I am going to close this one.
