### ISSUE TITLE
Caching auto-configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2633]
Given the revisited support as of Spring Framework 4.1, it would be nice to provide a better support for caching in Boot. There was already a failed attempt (#1553) and a recent PR for ehcache (#2602) brought the idea back to life.

We need this thing to be opt-in as the mere presence of a caching library in the classpath is no good reason to enable it. Fortunately (thanks @dsyer !) we can rely on the presence of `@EnableCaching` (more specifically a `CacheAspectSupport` bean). 

These are the things we could auto-configure:

* Redis
* EhCache (via `ehcache.xml` on the classpath)  - #2602
* JSR-107 (via the presence of a default JSR-107 provider)
* "Simple" `ConcurrentHashMap` which would be the fallback if `@EnableCaching` is on and no caching library was found. It would be nice to draw the attention with a log of some form

Root namespace would be `spring.cache` with dedicated namespace for each solution (i.e. `spring.cache.ehcache`).

We could also go further and offer easy configuration of, for instance, `Guava` caches thought I doubt it will be handy via configuration properties (maybe yaml would offer a better experience?)

Of course, all this should back-off if a `CacheManager` has been defined. `spring.cache.mode` is a key that defines the actual system to auto-configure when the user wants to be explicit with a deterministic order on our end (i.e. simple hash map < ehcache).

**Comment by eddumelendez** [comment]
Root package would be org.springframework.boot.autoconfigure.cache (i.e `org.springframework.boot.autoconfigure.cache.ehcache`)

**Comment by snicoll** [comment]
Well, that's what I thought at first but we didn't do it like that for web template (see `template`, `thymeleaf` and other similar packages). I guess  there is a good reason though the `template` package is infortunate IMO as it is a bit too generic. 

@dsyer , @philwebb touhgts?

**Comment by eddumelendez** [comment]
Findings for JCache support.

Dependency:

```xml
<dependency>
	<groupId>javax.cache</groupId>
	<artifactId>cache-api</artifactId>
	<version>1.0.0</version>
</dependency>
```

Some conditions:
* Classes should be available on classpath `javax.cache.CacheManager`, `org.springframework.cache.CacheManager`, `org.springframework.cache.jcache.JCacheCacheManager`
* Bean should not exist `org.springframework.cache.CacheManager`

**Comment by snicoll** [comment]
Okay so I have started a branch that brings a basic support for caching auto-configuration. It supports redis, a generic `CacheManager` based on the presence of a `Cache` bean in the context and a simple concurrent map based implementation.

We have a PR pending for ehcache so we should integrate that here. Other options such as _jcache_ and _hazelcast_ comes to mind (we don't have any dependency to the latter right now). 

Adding `@EnableCaching` to the Spring Boot app should be enough. Of course, if the user defines a specific `CacheManager` the whole thing backs off. 

Any thought before we move forward?

**Comment by snicoll** [comment]
Found a potential problem with hazelcast https://github.com/hazelcast/hazelcast/issues/4844

**Comment by snicoll** [comment]
See also https://jira.spring.io/browse/SPR-12842

**Comment by php-coder** [comment]
Please, don't forget to update documentation.

Also I want to have a way to disable it (`spring.cache.enabled: false`).

Right now I see that 2 different managers get created:

```
   GenericCacheConfiguration
      - Automatic cache type (CacheCondition)
...
   NoOpCacheConfiguration
      - Automatic cache type (CacheCondition)
...
   RedisCacheConfiguration
      - Automatic cache type (CacheCondition)
...
   SimpleCacheConfiguration
      - Automatic cache type (CacheCondition)
```

And it looks strange that I have both `RedisCacheConfiguration` and `NoOpCacheConfiguration`..

**Comment by snicoll** [comment]
The documentation update is coming this week. 

It's only enabled if you put `@EnableCaching` on your configuration (you can do so via a configuration class that is enabled via a profile only). If you can't afford that `spring.cache.type: none` uses a NoOp implementation; it's not strictly disabled though.

What makes you think you have two `CacheManager` instances. Unless we overlooked something, you don't (every configuration is guarded with `ConditionalOnMissingBean`).

**Comment by snicoll** [comment]
Let's resolve this theme for now and create individual issues for the things we'd improve in the next milestone.
