### ISSUE TITLE
Springboot based Jar hangs after running for 5-6 hrs comfortably

### ISSUE THREAD

**Issue by pratt8084** [spring-projects/spring-boot#26347]
Please help as we have deployed our springboot jar as microservice on linux server which contains both html and calls to other microservices, but after running perfectly for some hours., the microservice hangs and browser says service not available. after restarting it again works fine.

This is happening very frequently now a days. Attaching thread dump for your reference.

Thanks in advance.
[threaddump.txt](https://github.com/spring-projects/spring-boot/files/6419113/threaddump.txt)

**Comment by wilkinsona** [comment]
Thanks for the thread dump, but everything in it looks fine to me.

I can see Undertow's XNIO IO threads are all runnable and the vast majority of its task threads are all waiting for work to do. There is one task thread, `XNIO-1 task-137`, that is runnable and it is handling the request to the thread dump endpoint. As far as I can tell, the application has not hung, and judging by `XNIO-1 task-137` it is having no problems handling requests.

Can you please explain why you believe it has hung and cannot handle requests?

**Comment by pratt8084** [comment]
Thanks Andy for your prompt response. The thread dump which I have provided is of the particular time when the application is working fine. It got hanged thats why I was unable to download the thread dump too.

**Comment by wilkinsona** [comment]
Unfortunately that makes the thread dump useless for diagnosing this problem.

A thread dump taken from the machine on which the application is running would still be useful. You can take one using `jstack` or `kill -3`. The latter will require access to the process’s standard output.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
