### ISSUE TITLE
Displaying all the configuration in the log with info logger level

### ISSUE THREAD

**Issue by muqtharali** [spring-projects/spring-boot#26355]
In org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration class, displaying all the properties read from config server using the below log statement. I think we can stop displaying all the properties read from configuration file or spring cloud config server which will get displayed in Kibana or Grafana dashoboard.

At least we can change the logger level to debug so that in the production logs, we don't see all the values.

**Statement**
logger.info("Located property source: " + sourceList);

**Jar:** spring-cloud-context-2.2.2.RELEASE.jar
**Class:** org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration

**Comment by wilkinsona** [comment]
`org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration` is part of the Spring Cloud Commons project. You can make this suggestion to them [here](https://github.com/spring-cloud/spring-cloud-commons/issues).
