### ISSUE TITLE
Improve Tomcat SSL configuration with classpath resource error message

### ISSUE THREAD

**Issue by mlaccetti** [spring-projects/spring-boot#2635]
Assuming that I have the following configuration:

    server.ssl.key-store=classpath:keystore.jks
    server.ssl.trust-store=classpath:truststore.jks

It will, as always, work fine when running from the IDE/source, but fail miserably when running as a JAR:

    Caused by: java.io.FileNotFoundException: class path resource [keystore.jks] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/root/client-cert-validator/client-cert-validator-0.0.1.jar!/keystore.jks

Please, no arguments about how "good" it is to put the JKS in the JAR - let's focus on the bug itself.

**Comment by johnktims** [comment]
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc#configure-ssl

> Tomcat requires the key store (and trust store if you’re using one) to be directly accessible on the filesystem, i.e. it cannot be read from within a jar file. This limitation doesn’t apply to Jetty and Undertow.

**Comment by mlaccetti** [comment]
Perhaps an error/exception can be thrown if somebody uses a classpath/undesired resource?

**Comment by johnktims** [comment]
> Caused by: java.io.FileNotFoundException: class path resource [keystore.jks] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/root/client-cert-validator/client-cert-validator-0.0.1.jar!/keystore.jks

**Comment by mlaccetti** [comment]
@johnktims I got it, just curious about putting an assertion into the code so that a better error message is displayed; i.e. "loading a keystore from the classpath is not supported"
