### ISSUE TITLE
Add a way to intercept start of application

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-boot#2636]
I have a pretty simple usecase:

The application should refuse to start, when ```!"UTF-8".equals(System.getProperty("file.encoding"))```

Of course I could add it somewhere within a ```@PostConstruct```, but this may take up 1 minute.

Though it would be cool, if there's some protected method to ```@Override```, where I can place my code inside.

Thank you.

**Comment by spencergibb** [comment]
Boot already has injection points using Springs application events: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-spring-application.html#boot-features-application-events-and-listeners.

You could use `ApplicationStartedEvent` or `ApplicationEnvironmentPreparedEvent`.

**Comment by benneq** [comment]
Thanks for your response.

In a "normal" Boot Application I would add ```SpringApplication.addListeners``` to the main class, I'm deploying my application along with other apps on a Tomcat, my init code looks like this:

```
@SpringBootApplication
public class Application extends SpringBootServletInitializer {
	private static Class<Application> applicationClass = Application.class;
	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(applicationClass);
	}
}
```

should I put ```SpringApplication.addListeners``` within the ```configure``` or the ```onStartup``` method when using ```ApplicationStartedEvent```? Or somewhere else?

**Comment by spencergibb** [comment]
I've not used `addListeners` before.  I would create a bean of `ApplicationListener`.

**Comment by benneq** [comment]
I now created an ApplicationListener within my Application.class that listens for ALL events:
```
@SpringBootApplication
public class Application extends SpringBootServletInitializer {
	private static Class<Application> applicationClass = Application.class;
	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(applicationClass);
	}
	@Bean
	public ApplicationListener<ApplicationEvent> init() {
		return event -> System.err.println(event.getClass()));
	}
}
``` 

But I get only 3 and none of the Boot events mentioned:
```
org.springframework.data.mapping.context.MappingContextEvent
org.springframework.messaging.simp.broker.BrokerAvailabilityEvent
org.springframework.context.event.ContextRefreshedEvent
```

Maybe it's only working for Boot Applications using jar with embedded Tomcat?

Btw: I'm using Boot 1.2.2 with Spring 4.1.5

**Comment by snicoll** [comment]
You can invoke `listeners` on `SpringApplicationBuilder`

```
@SpringBootApplication
public class Application extends SpringBootServletInitializer {
    private static Class<Application> applicationClass = Application.class;
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(applicationClass).listeners(myListener());
    }
    
    private ApplicationListener< ApplicationStartedEvent> myListener() {
        ....
    }

}
```

I am surprised that the event wasn't processed the way you wrote it. It should just work. I'll have a closer look later today.

**Comment by benneq** [comment]
That did the trick! 

Now I get (in this order):
```
org.springframework.boot.context.event.ApplicationPreparedEvent
org.springframework.boot.autoconfigure.jdbc.DataSourceInitializedEvent
org.springframework.data.mapping.context.MappingContextEvent
org.springframework.messaging.simp.broker.BrokerAvailabilityEvent
org.springframework.context.event.ContextRefreshedEvent
```

The ```ApplicationPreparedEvent``` comes right after the first log message after the Spring Boot banner. That's okay for me.

I'm just wondering where the other 3 events are:
```
ApplicationStartedEvent
ApplicationEnvironmentPreparedEvent <- the one I got
ApplicationPreparedEvent
ApplicationFailedEvent
```

**Comment by snicoll** [comment]
If you have further questions, please ask on stackoverflow. We are tracking bugs and improvement requests here.

You should probably listener to `ApplicationStartedEvent`, this is the first event that we fire. If you want to shutdown the app, there is a `/shutdown` endpoint in the actuator, disabled by default (see the doc) or you can simply close the `ApplicationContext` (see `ApplicationContextAware`).

I'll keep this issue open to try out your lambda-based event as it should just work (not to intercept early events like these one of course, that's why `listeners` exist in the first place)

**Comment by snicoll** [comment]
Oh I read your comment wrong: you *do* get events with the lambda, not just the expected one. Well you got the answer in my comment above. If you register a listener in the context (as a bean) it will only intercept events that are created once the context has been created. Those events are fired even before the context exists, which is why we have a separated registration mechanism for those.
