### ISSUE TITLE
spring mongo data adds +00:00 to ISODate()

### ISSUE THREAD

**Issue by fssrepository** [spring-projects/spring-boot#26372]
Pls. check out which format is accepted by mongodb
https://docs.mongodb.com/manual/reference/operator/aggregation/toDate/

Using the @Aggregate pipeline, ISODate() translated with +00:00 at the end which is not accepted by $toDate.

I'm making some sort of pagination. Using Date() in the @Aggregate, even if it's going to be a crazy format, $toDate is picking up.

**Comment by snicoll** [comment]
Spring Data MongoDB has a [dedicated issue tracker](https://github.com/spring-projects/spring-data-mongodb/). Before creating an issue there, please take the time to provide a bit more details, a sample would be better.
