### ISSUE TITLE
Use RequestContextFilter instead of RequestContextListener 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2637]
We have an issue with Spring Session with `RequestContextListener` described at [here]. This is issue opened as a request by @philwebb.

Basically `ContextListener` is setting request very early and it should be set after Spring Session Filter.  `RequestContextFilter` has a nice advantage over listener. Filter is setting response as well and accessing Response by a static reference as Request is very useful. Please consider changing default behaviour to `RequestContextFilter`. 

[here]: https://github.com/spring-projects/spring-session/issues/129

**Comment by dsyer** [comment]
If it's a filter the only problem is how to choose an order for it. I guess we might need to make that configurable, and make sure it lands *after* the Spring Session filter if that is present (e.g. when we support it vai autoconfiguration).

**Comment by rwinch** [comment]
@cemo Can you elaborate on where you are accessing the `RequestContextHolder`? This is important because the `RequestContextFilter` must be after `SessionRepositoryFilter` and before you are accessing `RequestContextHolder`.

**Comment by prasenjit-net** [comment]
I working with spring-session with distributed session, i feel that there should be proper way to overwrite the default session in servlet-api

**Comment by wilkinsona** [comment]
Ping @cemo. Please see the question above from @rwinch

**Comment by cemo** [comment]
Sorry for late reply.

We are using `RequestContextHolder` in many places. In `Services`, `Validators`, `Security Filters` etc... Currently I had done exactly how @rwinch described to create a workaround. 

I believe that `Filter` approach is superior because of setting not only `request` but also `response`. A `Listener` can only set `Request`, but a `filter` can set `Response` as well.  

Using a listener may cause issues to access not `Spring Session` wrapped `ServletRequest`

**Comment by cemo** [comment]
This issue might see not important as much but there is not any solution to use currently `RequestContextHolder` without `RequestContextFilter`. Spring Boot's current implementation is based on `RequestContextListener` and anyone using Spring Session + Spring Boot + `RequestContextHolder` without `RequestContextFilter` will have a problem. @wilkinsona, please reconsider to schedule this is before 1.3 release.

**Comment by cemo** [comment]
also ping @rwinch

**Comment by philwebb** [comment]
I think this is a safe(ish) change to make. I've pushed an update for RC1. @dsyer @rwinch Does the filter order of 100 work OK? Does that match with the work that was done for #3613?

**Comment by dsyer** [comment]
Rather than 100 (literally) it probably should be relative to `FilterRegistrationBean.REQUEST_WRAPPER_FILTER_MAX_ORDER` or `SessionRepositoryFilter.DEFAULT_ORDER`. Maybe `SessionRepositoryFilter.DEFAULT_ORDER - <something small>` (since it isn't needed by that filter but the OP was wanting to use the request context downstream of that filter)?

**Comment by philwebb** [comment]
We can't use `SessionRepositoryFilter.DEFAULT_ORDER` directly since it might not be on the classpath. I thought it needed to be `SessionRepositoryFilter.DEFAULT_ORDER + <something small>` given https://github.com/spring-projects/spring-boot/issues/2637#issuecomment-127397375

**Comment by philwebb** [comment]
I guess we could really do with a test for this.

**Comment by wilkinsona** [comment]
The constant will get in-lined at compile time won't it?

**Comment by philwebb** [comment]
Hmm, I don't actually know. I'll need to test that.

**Comment by wilkinsona** [comment]
If my reading of the JLS is correct, all primitive and String constants will be in-lined

**Comment by rwinch** [comment]
@philwebb It's somewhat of a delegate balance on what the order should be. If it is not early enough, then code invoked via `Filter`s that occur before `RequestContextFilter ` will not refer to the correct `HttpServletRequest`. However, if it is too early, then it isn't wrapped by other Filter's that may need to wrap the request and response.

Now that we have an official stance on Filter ordering, I think the best approach is making it just after the `FilterRegistrationBean.REQUEST_WRAPPER_FILTER_MAX_ORDER` as @dsyer suggests.

**Comment by prasenjit-net** [comment]
Isn't it possible to implement this session distribution using session
manager SPI provided by all container supported by spring boot.

**Comment by prasenjit-net** [comment]
I shall create an example after my festival time is over.
