### ISSUE TITLE
Configurable time interval for executing health checks in custom Health Indicators

### ISSUE THREAD

**Issue by gvillacis-ec** [spring-projects/spring-boot#26370]
**Spring Boot 2.1.6**

**Spring boot actuator**

When writing a custom HealthIndicator extending the AbstractHealthIndicator class I suggest allowing to specify the repetition interval of the health check. Because not all HealthIndicator's need to be tested in such a short period of 10-15 seconds (default setting).

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

There's no scheduled checking of the health indicators by default. Calls to the indicators are driven by calls to the health endpoint. If you have different indicators that you want to be checked at different frequencies, I would recommend assigning them to different [health groups](https://docs.spring.io/spring-boot/docs/2.3.10.RELEASE/reference/htmlsingle/#production-ready-health-groups). To make use of this feature, you'll have to upgrade to Spring Boot 2.3.x (or later). 2.3.x is the oldest currently supported generation of Spring Boot.
