### ISSUE TITLE
Correct Kotlin version requirements in documentation

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-boot#26371]
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/kotlin.adoc claims that boot requires kotlin 1.3.x, but I'm sure start.spring.io gives me kotlin 1.4.
What's up?

Kotlin 1.5 just came out. Is that compatible with spring boot?

**Comment by scottfrederick** [comment]
The Kotlin version is correct in the [Dependency Versions ](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#dependency-versions) section of the documentation. Maybe it would be better to link to this section in `4.30.1 Requirements`, or to inject the version as a variable in the asciidoc instead of hard-coding it.

**Comment by scottfrederick** [comment]
Spring Boot 2.4 is compatible with Kotlin 1.4. Spring Boot 2.5 [will support](https://github.com/spring-projects/spring-boot/blob/main/gradle.properties#L7) Kotlin 1.5. We'll pick up the upgrade from Kotlin `1.5.0-RC` to `1.5.0` as part of our semi-automated dependency upgrade process before the Boot 2.5.0 release.

**Comment by wilkinsona** [comment]
Strictly speaking, I think we require 1.3.x or later as our Kotlin code is [compiled with a 1.3 API and language version](https://github.com/spring-projects/spring-boot/issues/25793). The default Kotlin version provided by dependency management then changes across Boot 2.3, 2.4, and 2.5.

**Comment by scottfrederick** [comment]
@wilkinsona Are you suggesting that we could change the text in `4.30.1 Requirements` to say something "Spring Boot supports Kotlin 1.3.x or later" and then leave the specific version for the managed dependency section?

**Comment by wilkinsona** [comment]
Yes, I think so. It's a bit like our Java requirement in that respect, but with some additional dependency management for its standard library, etc,

**Comment by snicoll** [comment]
@lower-case thanks for the PR. FTR there is no need to add a comment here, we've already received a notification when the PR was submitted.
