### ISSUE TITLE
Add ApplicationReadyEvent

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2638]
Such event may be useful for listeners that requires to perform the operation when the application is ready to use. Would be triggered right before returning the `ApplicationContext` from the `run` method.

**Comment by philwebb** [comment]
I think `ApplicationReadyEvent` should probably extend `SpringApplicationEvent` so that it has parity with `ApplicationFailedEvent`. We've probably also got a package tangle now so we should trigger it from `EventPublishingRunListener.finished()` rather than directly from `SpringApplication`.

**Comment by philwebb** [comment]
Also, is there a specific use-case where this is needed over a `ContextRefreshedEvent`?

**Comment by snicoll** [comment]
In the reference issue. The maven plugin listens to it to let the integration tests run. 

I disagree with it extending `SpringApplicationEvent`. This is what I did initially but semantically it does not fit: when you handle that event, the `SpringApplication` has been "fully loaded" and any attempt to modify it (call a setter, register a listener) will just not do what you expect. I think the application context is a much better source in that regard.

Good catch for the cycle.

**Comment by philwebb** [comment]
I think having context of which `SpringApplication` triggered the event is still useful. We also have precedence with `ApplicationPreparedEvent`.
