### ISSUE TITLE
ActiveMQ 5.11.0 ConnectionFactory NoSuchMethodError

### ISSUE THREAD

**Issue by covolution** [spring-projects/spring-boot#2640]
In ActiveMQ 5.11.0 the `org.apache.activemq.jms.pool.PooledConnectionFactory.setConnectionFactory` method signature changed.  Instead of `ConnectionFactory` it now uses `Object`.  This is giving me a NoSuchMethodError error in Sprint Boot.

`org.springframework.boot.autoconfigure.jms.activemq.ActiveMQConnectionFactoryConfiguration` is calling `pool.setConnectionFactory(connectionFactory)`.   In debug is looks like the class is `ActiveMQConnectionFactoryConfiguration$$EnhancerBySpringCGLIB`.  Is cglib having trouble now that the method signature is just an  `Object`?

**Comment by snicoll** [comment]
Nope, we just need to recompile the code against 5.11.0 I guess (changing a method signature is not binary backward compatible).

**Comment by jhoeller** [comment]
Boot could also call that method reflectively, checking for the present variant first. After all, ActiveMQ 5.11 is not even two months old yet...

**Comment by wilkinsona** [comment]
I agree with @jhoeller. We should wait until Boot 1.3 to start compiling against 5.11 and just tolerate it via reflection for now.

**Comment by wilkinsona** [comment]
1.2.x now tolerates the 5.11 API change and #2662 has upgraded master (1.3) to compile against 5.11.1
