### ISSUE TITLE
Document the difference between import.sql and data.sql

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2642]
Unless I misunderstood something, there is no easy way to run a script *only* when the schema is generated

* `import.sql` is an hibernate feature but only works with `create` (that drops the schema if necessary first) or `create-drop`. With `validate` (create/update the schema if necessary), `import.sql` is not executed at all
* `data.sql` and the like is executed every time we start the app. If we dont' drop the shema, our sql script must be idempotent

It may mostly be a demo purpose issue but what if we have an in memory DB locally and a cloud-based service in another environment? The local environment does not matter as  we create it at every run but the cloud thing may use an initialization at first start, reusing that for further deploys.

Thoughts?

**Comment by philwebb** [comment]
I'm not sure we should stray too far into this area. Sounds like something that Hibernate should support directly. 

Of course, there's always flyway.

**Comment by snicoll** [comment]
I am ok with that. At the very least we should update the doc because the current phrasing is confusing.
