### ISSUE TITLE
Spring actuator  with git-commit-id-plugin does not use all the data

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-boot#2644]
I am trying to use git-commit-id-plugin with Spring actuator, 

App generated these values in the "git.properties" file:

![screen shot 2015-03-12 at 17 25 26](https://cloud.githubusercontent.com/assets/7360956/6622428/cfb8f9d8-c8dc-11e4-850a-eb13cfcff282.png)

but when i use /info url the app only shows:

![screen shot 2015-03-12 at 17 23 34](https://cloud.githubusercontent.com/assets/7360956/6622381/9299b178-c8dc-11e4-8729-37d5957c30ce.png)

why only shows 2 values of git.commit? The other values does not appear. (git.commit.id.describe which is the most important value for this plugin )

**Comment by snicoll** [comment]
The values that are read from that file are constrained by the structure of  [`GitInfo`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.java#L212). 

Do you intend to show everything or do you believe only some properties are missing?

**Comment by cristianprofile** [comment]
I Inted to show every properties, specially git.commit.id.describe, This value is a must to be Able to know which version of an App is deployed in the server, this is the main feature that we use of git-commit-id- plugin in my company.

**Comment by philwebb** [comment]
I think that we deliberately kept `GitInfo` somewhat light so that it works well with other build systems. It should be relatively easy to add some more properties.

**Comment by philwebb** [comment]
Also see #2484 which discusses moving the class outside of actuator.

**Comment by cristianprofile** [comment]
Thank you philwebb and snicoll for your fast support.

**Comment by nfrankel** [comment]
I got it working for me, but I dropped the `GitInfo` in favor of a `Map<String, Object>`, so that the git.properties can evolve independently without requiring code update.

If you're interested, I can make a PR. If not, not a problem since Spring Boot is easily extensible.

**Comment by wimdeblauwe** [comment]
+1 for me

**Comment by philwebb** [comment]
See also #3492

**Comment by snicoll** [comment]
`management.info.git.mode=full` can be used to display all the information available in `git.properties`. The default is `simple` and displays what we used to so far.

**Comment by nfrankel** [comment]
@snicoll You're my hero! But now I've to update my Spring Boot Actuator demo ;-)
