### ISSUE TITLE
Scope for local.server.port property

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2646]
I am using a random port for integration tests and trying to acquire the value of `local.server.port` in a bean outside my test classes. If I specify `@Value{'local.server.port'} int port` inside one of my test classes, it's set correctly. If I put that same declaration in an external bean (whether a plain bean or an `@Configuration`), I get the "could not resolve placeholder" exception:

    java.lang.IllegalArgumentException: Could not resolve placeholder 'local.server.port' in string value "${local.server.port}"

I suspect that this has to do with using a context for the test case that's nested inside the context where the bean is, but it seems that the `local` bean should be available to the classes specified in the test's context configuration. The test case in question:

```groovy
@ContextConfiguration(
    loader = SpringApplicationContextLoader,
    classes = [GalleryRootConfiguration, GalleryLauncherTestConfiguration]
)
@WebIntegrationTest('server.port:0')
class FooTest extends GebSpec {

    @Value('${local.server.port}')
    int port

    def hello() {
        given:
            Browser b = new Browser()
        expect:true
    }
}
```

**Comment by snicoll** [comment]
I am afraid there is nothing we can do here. The actual port is determined at runtime and the `local.server.port` is set when `EmbeddedServletContainerInitializedEvent` is triggered. As you might imagine, beans have already been processed at this point.

I would expose that value as a method parameter and pass it from your test instead.

**Comment by philwebb** [comment]
You can also have your class implement `ApplicationListener<EmbeddedServletContainerInitializedEvent>` and listen for the event yourself.

**Comment by chrylis** [comment]
The question's about a Groovy script, not a traditional class, so most of the usual tricks such as using a listener aren't applicable.
