### ISSUE TITLE
Add @ControllerAdvice to be excluded from the component scan when not using @WebIntegrationTest  or @WebAppConfiguration

### ISSUE THREAD

**Issue by bjconlan** [spring-projects/spring-boot#2649]
When testing non web components as per the documentation:

> The context loader guesses whether you want to test a web application or not (e.g. with `MockMVC`) by looking for the `@WebIntegrationTest` or `@WebAppConfiguration` annotations. (`MockMVC` and `@WebAppConfiguration` are part of spring-test).

the '@ControllerAdvice' beans shouldn't be picked up and attempted to be loaded.

**Comment by bjconlan** [comment]
@ConditionalOnWebApplication seems to solve my problems (but would thing that controller/controller advice types would be conditionally included without it.

**Comment by wilkinsona** [comment]
I believe this has been taken care of with 1.4's `@WebMvcTest` support.
