### ISSUE TITLE
Add spring-session repository filter bean in springSecurityFilterChain on tests

### ISSUE THREAD

**Issue by bjconlan** [spring-projects/spring-boot#2650]
On an testing a spring boot web application which makes use of spring-session the registered sessionRepositoryFilter doesn't seem to automatically get included in the `@Autowired Filter springSecurityFilterChain;` (as I would assume) used for building a mock mvc instance.

The test class is annotated with:
```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Application.class)
@WebIntegrationTest
@ActiveProfiles("test")
```

And for clarity the spring session config:
```java
@Configuration
public class HttpSessionConfig {

	@Bean
	public SessionRepository<ExpiringSession> sessionRepository() {
		return new MapSessionRepository();
	}

	@Bean
	public <S extends ExpiringSession> SessionRepositoryFilter<? extends ExpiringSession> springSessionRepositoryFilter(SessionRepository<S> sessionRepository) {
		SessionRepositoryFilter<S> sessionRepositoryFilter = new SessionRepositoryFilter<S>(sessionRepository);
		sessionRepositoryFilter.setHttpSessionStrategy(new HeaderHttpSessionStrategy());
		return sessionRepositoryFilter;
	}
}
```

I would have expected spring-session to behave as it does when running the Application.class

**Comment by bjconlan** [comment]
P.S the current work around is to `@Autowire` in the springSessionRepositoryFilter then register it to the MockMvcBuilder before the springSecurityFilterChain.

**Comment by rwinch** [comment]
Spring Session is its own Spring Module and is added as a distinct Filter that is placed before springSecurityFilterChain. So this is expected behavior.

If you need all of the Filter instances you can `@Autowire List<Filter>`
