### ISSUE TITLE
JCache Support

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#2651]
Based on the discussion #2633, JCache AutoConfiguration is needed. In this ticket you can find some tips to take into account in the implementation.

**Comment by snicoll** [comment]
is there any particular reason to create this issue now? I'd rather keep the discussion in #2633 and fork the necessary issues once we have a plan.

**Comment by eddumelendez** [comment]
Map all related to the jcache implementation only, something like final agreements. This ticket can be on hold until find those agreements in #2633. I will add my findings and doubts about jcache implementation in that ticket.

**Comment by snicoll** [comment]
I'd rather keep the discussion in #2633 since it became a theme now :)
