### ISSUE TITLE
Use Spring AMQP's RabbitConnectionFactoryBean

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#2655]
Expose more properties to configure the connection factory (heartbeats, SSL etc).

http://stackoverflow.com/questions/29055529/channel-shutdown-connection-error

http://docs.spring.io/spring-amqp/docs/latest-ga/api/index.html?org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.html

**Comment by snicoll** [comment]
@garyrussell this is implemented. Maybe we could reconsider what the `FactoryBean` does regarding SSL (i.e. to avoid the creation of a dummy `Properties` object [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L255)) Thanks!

**Comment by garyrussell** [comment]
>Maybe we could reconsider what the FactoryBean does regarding SSL (i.e. to avoid the creation of a dummy Properties object here) Thanks!

@snicoll I am happy to make any changes to Spring AMQP that you need, but can't you avoid making the empty properties object by simply testing whether all 4 fields are null first?

If I am missing something, please open an AMQP JIRA.

Thanks

Gary

**Comment by garyrussell** [comment]
BTW, the whole reason for externalizing these properties is so that they can be placed in a file that is secured by the operating system - they contain sensitive information - key/trust store passwords.

This implementation for boot appears to have subverted that logic and these are now plain text properties...

````
+	spring.rabbitmq.ssl.key-store= # path to the key store that holds the SSL certificate
+	spring.rabbitmq.ssl.key-store-password= # password used to access the key store
+	spring.rabbitmq.ssl.trust-store= # trust store that holds SSL certificates
+	spring.rabbitmq.ssl.trust-store-password= # password used to access the trust store
````

**Comment by snicoll** [comment]
> but can't you avoid making the empty properties object by simply testing whether all 4 fields are null first?

I am not too keen to duplicate the logic of the `FactoryBean` in boot itself. What if you change this logic in a further release anyway?

> This implementation for boot appears to have subverted that logic and these are now plain text properties

Consistency. All the other SSL/security support works that way (no reference to _external_ config file): we use Spring Boot itself to separate those (_secret_ profile, etc). If you feel there is a compelling reason to add the support of a separate properties file, we can do that but the configuration becomes quite confusing all the sudden (there are two ways to do the same thing, I frankly don't like that at all).

**Comment by garyrussell** [comment]
@snicoll The RabbitConnectionFactoryBean now supports discrete properties for the SSL props.

https://github.com/spring-projects/spring-amqp/commit/62cf949e78704c7e376ca6c268da550c9f684c25#diff-396728cd9627a7a3df008a5a01a04c2c

1.5.0.RC1 is available in staging now, and will be released tomorrow (Friday).

**Comment by snicoll** [comment]
Thanks Gary, I've created #3754
