### ISSUE TITLE
Document spring.profiles.default property

### ISSUE THREAD

**Issue by Petros0** [spring-projects/spring-boot#26592]
Hello spring boot team,

I wanted to have default fallback profile when no profile is specified. I found out (from a Baeldung [article](https://www.baeldung.com/spring-profiles#the-default-profile)) that there was the property `spring.profiles.default` which does exactly what I expected. Unfortunately that is not documented in the  [Spring Boot Reference Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles) neither in [Common Application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties).

That is the log that I get when i start the application with no profile but with the property set. :)

![image](https://user-images.githubusercontent.com/12134197/118776438-481f3580-b888-11eb-8c7d-047bb15d1ae9.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestion. `spring.profiles.default` as a Spring Framework feature and it is [documented](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-definition-profiles-default) in the Spring Framework reference guide. That said, `spring.profiles.active` is also a Spring Framework feature but it is covered in Boot's own documentation. I think it's probably worth giving `spring.profiles.default` the same treatment. Let's see what the rest of the team thinks.

**Comment by philwebb** [comment]
Reopening to also add some reference docs
