### ISSUE TITLE
Disable actuators by property

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2661]
It might make sense have to disable a actuator by a property.  `spring.actuator.className` or `spring.actuator.fullyQualifiedClassName` seems as a good candidate.

This might be even generalised by a new annotation such as `@ConditionalActuator` which is checking a property to disable an actuator.

**Comment by philwebb** [comment]
Can you provide a bit more information about this? I'm not sure I totally understand what you're suggesting.

**Comment by spencergibb** [comment]
Its a similar strategy to how zuul filters are disabled: http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_disable_zuul_filters.

**Comment by philwebb** [comment]
I'm still not following what's meant by "a actuator". Is this a general properties to allow any auto-configuration class to be disabled by a property? Some like the `@EnableAutoConfiguration` `exclude` attribute?

**Comment by spencergibb** [comment]
Actuator endpoints is what I'm assuming, e.g. turn of `/metrics`.

**Comment by philwebb** [comment]
You can already do that with the `.enabled` property. See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-endpoints.

e.g. `endpoints.metrics.enabled=false`

**Comment by cemo** [comment]
Thanks for the information. You are right.
