### ISSUE TITLE
@ConditionalOnBean in a @Configuration @Bean method can fail when depending on another bean set up by a @Configuration @Bean

### ISSUE THREAD

**Issue by froh42** [spring-projects/spring-boot#26621]
# Problem

I have two separate classes marked as `@Configuration`, both set up beans with bean factory methods annotated with `@Bean` (please correct me if I have the wording off, I'm not an expert).

The first:

```java
        @Configuration
        public class KidneyConfig {
            @Bean
            KidneyBean makeKidneyBean() { return new KidneyBean() }
        }
```

The dependent one:

```java
        public class ChiliConfig {
             @ConditionalOnBean(KidneyBean.class)
             @Bean
             Chili makeChili(KidneyBean kidneyBean) { return new Chili(kidneyBean); ]
        }
```

The problem: Building everything as an application into a jar file (spring boot application, but I don't think that plays a role here) I can sometimes start the application, sometimes it will fail claiming that the condition failed.

# Analysis 

(I learned Spring internals on the go analyzing this bug, so please bear with inaccuracies):

When an `ApplicationContext` is built it will call `refresh`, and from there do a classpath scan to detect beans. The classpath scan is order dependent, so the bean definitions are in different order in the `ApplicationContext`.

Later in `refresh()` Spring will happen to call the `ConfigurationClassParser` which will scan `@Configuration` classes for `@Bean` methods. If it finds one it will use `ConfigurationClass` to locate the methods annotated with `@Bean`.

`ConfigurationClass` in turn will evaluate the `Conditionals` right away in this moment, so if my `KidneyBean` was already scanned by `ConfigurationClass` then everything will start up fine.

But if the `Chili` is scanned earlier than the `KidneyBean`, then the `@ConditionalOnBean` will fail - although just a moment later the `ConfigurationClassParser` will load the `KidneyBean`.

I'm not qualified to suggest how to fix this.

(Debugging this I found there's a post processor that validates for common problems - if using `@ConditionalOnBean` is not supported in the way I did, then one solution might be making the post processor detect that situation and complain during startup.)

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @froh42. Unfortunately, there's no way for us to detect if `@ConditionalOnBean` has been used in a regular `@Configuration` class or a `@Configuration` class that is or has been imported by an auto-configuration class. The current warnings in the javadoc and reference documentation will have to suffice.
