### ISSUE TITLE
Logging problem on configureProfiles method

### ISSUE THREAD

**Issue by andreabreu-me** [spring-projects/spring-boot#2663]
Can't log any output using Spring boot > 1.1.9 on configureProfiles method of SpringApplication class.

```
  @Override
  protected void configureProfiles(ConfigurableEnvironment environment, String[] args) {
      super.configureProfiles(environment, args);
      log.info("not showing");
  }
```

**Comment by philwebb** [comment]
Logging is disabled until the `ApplicationEnvironmentPreparedEvent` is fired in order to reduce noise. I'm not sure that there is a particularly easy fix for this. Perhaps we could record log messages during initialization then replay them once the environment is configured.

**Comment by andreabreu-me** [comment]
Since `configureProfiles` provides rules and semantics I did not expect this behavior. Another problem is that I can't provide any rules/semantics thought profiles provided by application properties file.

If I have:
```
spring.profiles.active: dev, test
```

```
@Override
protected void configureProfiles(ConfigurableEnvironment env, String[] args) {
    super.configureProfiles(environment, args);

    // this always return false
    boolean alwaysFalse = env.acceptsProfile("dev");
}
```

**Comment by philwebb** [comment]
I think the Javadoc is a little confusing on that method. It's currently used to add any directly configured profiles (i.e. those set using `SpringApplication.setAdditionalProfiles()`). The `spring.profiles.active` properties are actually processed by the `ConfigFileApplicationListener`.

**Comment by snicoll** [comment]
Duplicates #7772
