### ISSUE TITLE
Support for Thrift-based or protocol buffer clients and servers

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2664]
Interop benefits with a lot of other languages would be nice. Also allegedly very fast. There must be APache (or similar) libraries we can wrap.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by dsyer** [comment]
Actually I think there is huge demand for this.

**Comment by wilkinsona** [comment]
Where? This issue's been open for 3 years with no comments or reactions.

**Comment by dsyer** [comment]
Doesn’t mean there isn’t a gap IMO. You don’t have to look very hard to find people using binary RPC, and with Java. The fact that they get no help from Spring so far doesn’t mean there is nothing we can do. I can start a non-trivial gRPC server in a Spring Boot app in about 700ms. That’s worthy of attention on its own if you ask me. Just saying.

**Comment by wilkinsona** [comment]
I don't think Spring Boot is the right place to provide that support. There's already a third-party starter for gRPC and the Framework team are investigating RSocket. If/when that bears fruit then we can add auto-configuration for it if appropriate. I think my point stands though: we haven't seen demand for anything that's Boot-specific in this space.
