### ISSUE TITLE
add mockito-kotlin

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#26648]
Could you add mockito-kotlin (which is part of mockito itself and no longer an addon) in the dependency-management of sb?
https://repo1.maven.org/maven2/org/mockito/kotlin/

**Comment by snicoll** [comment]
It should be noted that it has a different release lifecycle so we'd have to maintain the version separately. Flagging for team attention to see what the rest of the team thinks.

**Comment by snicoll** [comment]
We've discussed this one and we don't add dependency management for the things that we don't expose features from. This is the case for `mockito-kotlin` so I am going to close this now. We can reconsider if additional Kotlin-test related features are added to Spring Boot.
