### ISSUE TITLE
Investigate caching @ConditionalOnClass results

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2665]
[This article](http://dev-blog.xoom.com/2015/03/15/use-spring-boot-auto-configuration/) discusses not using `@EnableAutoConfiguration` to reduce startup time. We might be able to get similar improvements if we could somehow cache `@ConditionalOnClass` results.

Another option might be to evaluate `@ConditionalOnClass` during compile to save it happening on every execution.

**Comment by cemo** [comment]
I have not investigate detailed but this is also our biggest headache currently. Our application started to work in 20 seconds. Before It was just around 5-6 seconds. I will also give a try this article and will let you know about details.

**Comment by philwebb** [comment]
@cemo I've tried a few benchmarks on some sample applications and I haven't found a massive amount of time is being spent evaluating conditions. My simple benchmarks show the following amount of time in each:

```
10 class org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$ErrorTemplateMissingCondition
19 class org.springframework.boot.autoconfigure.condition.OnPropertyCondition
134 class org.springframework.boot.autoconfigure.condition.OnBeanCondition
69 class org.springframework.boot.autoconfigure.MessageSourceAutoConfiguration$ResourceBundleCondition
0 class org.springframework.boot.autoconfigure.condition.OnWebApplicationCondition
68 class org.springframework.boot.autoconfigure.condition.OnClassCondition
13 class org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DefaultDispatcherServletCondition
0 class org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$NonEmbeddedDataSourceCondition
28 class org.springframework.boot.autoconfigure.condition.OnExpressionCondition
0 class org.springframework.boot.autoconfigure.condition.OnJndiCondition
2 class org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDataSourceCondition
10 class org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$DataSourceAvailableCondition
1 class org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration$HibernateEntityManagerCondition
```

I'd be interested if you have anything that you can share (privately if necessary) that demonstrates slow startup times. I think my original idea here caching `@ConditionalOnClass` results isn't actually going to buy us anything.

**Comment by philwebb** [comment]
Unable to eek out any performance improvements here so closing.

**Comment by mahmoudimus** [comment]
Unfortunately, I'm seeing this issue as well. Startup times make test iteration unbearable. I found out we are instantiating something like 544 beans! It's a large project, but it's not anything that big.

**Comment by wilkinsona** [comment]
@mahmoudimus Can you elaborate, please? What makes you think that your startup times are slow due to the time take to evaluate `@ConditionalOnClass`? As this issue is closed, it's probably better to open a separate issue if you have a specific performance problem that you'd like us to investigate.

**Comment by mahmoudimus** [comment]
@wilkinsona ah, sorry about that, I didn't read the title as I came directly from the article linked in the OP. -1 for me on paying attention. I'll re-investigate and open a more detailed issue. Thanks for the response.
