### ISSUE TITLE
spring.aop.proxy-target-class=false Invalid configuration is still using CGlib

### ISSUE THREAD

**Issue by xg704863664** [spring-projects/spring-boot#26650]
springboot 2.2.2  bean having interface implement
application.yml configuration spring.aop.proxy-target-class=false Invalid configuration is still using CGlib

**Comment by snicoll** [comment]
@xg704863664 it's hard to figure out what you're reporting based on a two lines description. Please note that Spring Boot 2.2.x is EOL so you'll have to upgrade first. If the problem still occurs, can you put that interface and config in a small sample (for instance created from start.spring.io) and attach it to this issue. Alternatively, you can push it to GitHub and share the link of the repo with us. Thank you.

**Comment by xg704863664** [comment]
spring.aop.proxy-target-class=false Invalid configuration is still using CGlib @snicoll

**Comment by snicoll** [comment]
@xg704863664 thanks but none of that is providing what I've requested. Can you please review my comment and upgrade first to check the problem persists and, if it is, share a small sample we can run ourselves.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
