### ISSUE TITLE
Better document flyway properties

### ISSUE THREAD

**Issue by paranoiabla** [spring-projects/spring-boot#2667]
Hi there,

I cannot configure flyway the I want because the `FlywayProperties` is missing on a lot of options. Specifically I'm currently creating the flyway bean like the following:
````
    @DependsOn("dataSource")
    @Bean(name = { "defaultPlatformFlywayConfiguration", "flyway" })
    protected Flyway defaultPlatformFlywayConfiguration() throws PropertyVetoException {
        final Flyway flyway = new Flyway();
        flyway.setDataSource(dataSource);
        flyway.setInitDescription("First Platform Init");
        flyway.setTable("platform_schema_version");
        flyway.setSqlMigrationPrefix(environment.getProperty("my.platform.schema.export.prefix", "EXPORT"));
        flyway.setIgnoreFailedFutureMigration(true);
        flyway.setInitOnMigrate(true);
        flyway.setValidateOnMigrate(false);
        flyway.setLocations("classpath:/db/migration");
        flyway.setSqlMigrationSuffix(".sql");

        return flyway;
    }
````
Could you please allow customizing the `validateOnMigrate`, `initOnMigrate`, `ignoreFailedFutureMigration`, `table` and `initDescription`. 

Also the documentation suggests I can add  `flyway.sql-migration-suffix` and `flyway.sql-migration-prefix` as properties:

http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

but the file does not suggest so:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java

Thanks.

**Comment by snicoll** [comment]
I think there is a misunderstanding on your end. The `Flyway` object is actually exposed [as a `@ConfigurationProperties` target](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L99) so *anything* that you can configure via a setter on `Flyway` can be configured via the `flyway` namespace.

Have you tried? looks like a documentation issue to me.

**Comment by paranoiabla** [comment]
Thanks @snicoll I never knew you could expose a bean as a @ConfigurationProperties target :). Here's my declaration, which seems to work fine:
````
# Flyway
flyway.enabled=true
flyway.sql-migration-prefix=Samplestore
flyway.sql-migration-suffix=.sql
flyway.validateOnMigrate=false
flyway.initOnMigrate=true
flyway.ignoreFailedFutureMigration=true
flyway.table=platform_schema_version
flyway.initDescription=First Platform Init
````
Although I'm still wondering why the `sql-migration-prefix` and `sql-migration-suffix` are hyphened. I'm closing this issue now, as it seems to work fine.

**Comment by snicoll** [comment]
I'd like to fix the documentation issue, still.

**Comment by eddumelendez** [comment]
More clear after read 

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java#L26-L36
