### ISSUE TITLE
Reference docs overview has broken links on 2.5.0

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#26683]
Hi,

I noticed that the non-single page reference https://docs.spring.io/spring-boot/docs/current/reference/html/ has some broken links. Mainly some of the appendix sections seem to be missing. At least they are not working.

- https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html#cli 
- https://docs.spring.io/spring-boot/docs/current/reference/html/auto-configuration-classes.html#auto-configuration-classes
- https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata
- https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar
- https://docs.spring.io/spring-boot/docs/current/reference/html/test-auto-configuration.html#test-auto-configuration

The latest snapshots seem to be working, so I wonder if the release builds had a problem. I couldn't tell what the problem is so far, maybe you have an idea.

Cheers,
Christoph

**Comment by snicoll** [comment]
Confirmed that previous redirection rules are in the way now. I've requested these to be fixed on the server-side.

**Comment by dreis2211** [comment]
Thanks for the follow-up, @snicoll

**Comment by snicoll** [comment]
Alright, these are fixed now as the rules on the server have been adapted. Considering there isn't any code change, I am going to close this now and remove the milestone.
