### ISSUE TITLE
Application fails to start with Error processing condition on org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

### ISSUE THREAD

**Issue by maletiger0404** [spring-projects/spring-boot#26681]
Hello, everyone
If anyone knows how to solve this issue, please help me.

![image](https://user-images.githubusercontent.com/67555770/119786061-16355100-bed0-11eb-9e00-b7247c28ede5.png)

Here is my build.gradle.

![image](https://user-images.githubusercontent.com/67555770/119786144-2ea56b80-bed0-11eb-92c2-138017f0a248.png)

**Comment by snicoll** [comment]
@maletiger0404 please refrain from sharing screenshots as they aren't usually very helpful. Can you please the complete stacktrace? The `IllegalStateException` should have a cause that provides more details.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
