### ISSUE TITLE
ConfigurationPropertiesBindingPostProcesser can trigger very early initialisation of Converter beans

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2669]
If there's no `ConversionService` bean named `conversionService` in the application context, `ConfigurationPropertiesBindingPostProcessor` creates a default conversion service and configures it with any `Converter` beans in the application context. As `ConfigurationPropertiesBindingPostProcessor` is a `BeanPostProcessor` this can cause any `Converter` beans and their dependencies to be initialized very early. @olivergierke has indicated this causes problems with Spring Data REST:

> I ran into this with SD REST, too, which had a few converters registered as `@Bean` to make sure they're singletons which the caused half of SD REST prematurely initializing in a Boot context but work fine in a Spring-only app.

A couple of workarounds:

1. Register your own, appropriately configured `conversionService` bean to prevent creation of the default conversion service
2. Don't expose your `Converter`s as beans

**Comment by wilkinsona** [comment]
See https://github.com/marceloverdijk/spring-boot-data-circular-dependency for a problem that @marceloverdijk is having that may be caused by this

**Comment by marceloverdijk** [comment]
Also see http://stackoverflow.com/questions/29065138/spring-data-spring-boot-circular-dependency-issue which contains some additional info.

**Comment by philwebb** [comment]
I tempted to live with this for 1.2.x and try to find a better solution for 1.3
