### ISSUE TITLE
I can't open a new connection to the database (azure) after starting spring boot app 

### ISSUE THREAD

**Issue by azeroual2017** [spring-projects/spring-boot#26726]
**Describe the issue**
We use Azure Managed PostgreSQL (11). I connect successfuly to the database from spring boot application. While connecting i disable GSS Encryption (gssEncMode=disable)

But after approximately 15 minutes all the other connections are blocked, and we can't connect from another app. we get the following error : **FATAL:  authentication failed for user "****": too many failed login attempts**

**Driver Version?** 
i have tested with 42.2.14. ,  42.2.16 and 4.42.18

**Spring version**
i have tested with 2.1.1.RELEASE and 2.3.4.RELEASE

**Java Version?**
Java 11 OpenJDK (Windows)

**OS Version?**
Windows server 2016

**PostgreSQL Version?**
11

**To Reproduce**
1. start application that uses pgjdbc to connect to the database.
2. wait for about 15 mins.
3. Open a new connection, i get the error : FATAL:  authentication failed for user "****": too many failed login attempts

Thanks for your help !!

**Comment by snicoll** [comment]
@azeroual2017 this is the wrong place to report an issue against a managed PostgreSQL instance. Please reach out to the support at Azure for this.
