### ISSUE TITLE
Upgrading to Spring Boot 2.5.0 leads to a startup warning from Jackson about Kotlin

### ISSUE THREAD

**Issue by Bas83** [spring-projects/spring-boot#26727]
After migrating to Spring Boot 2.5.0 I get the following warning during startup:

`WARN | o.s.h.c.j.Jackson2ObjectMapperBuilder | For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath`

Another person posting [this StackOverflow question](https://stackoverflow.com/questions/67630048/springboot-2-5-0-for-jackson-kotlin-classes-support-please-add-com-fasterxml-ja) has this issue as well, but there is no clear/easy solution for it without code changes.
Just like this person I am not using Kotlin at all. Please make it easy to exclude Kotlin from autoconfiguration (as for example like with ThymeLeaf with `exclude = {ThymeleafAutoConfiguration.class}`, or maybe even solve this automatically for the user entirely.

**Comment by snicoll** [comment]
@bas83 thanks for the report but that warning is logger by Spring Framework based on the presence of a kotlin-specific jar. The SO question you've shared has a comment that links to https://github.com/spring-projects/spring-framework/issues/26962. 

Can you please confirm your application uses Spring Security?

**Comment by Bas83** [comment]
Yes I am using Spring Security. Should I report this to them instead? In your link I found this issue: https://github.com/spring-projects/spring-security/issues/9811

**Comment by snicoll** [comment]
Thanks for confirming. Yes, that's the root cause of your issue. Please subscribe to that issue for further update. On our side, we'll add a temporary exclude as I am not sure that Spring Security `5.5.1` will be out before Spring Boot `2.5.1`.
