### ISSUE TITLE
Refactor JarFile and support classes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#26745]
This fix for #25538 has shown that we could really do with refactoring `JarFile` and supporting classes. We ideally shouldn't need to behave differently just because a `SecurityManager` is installed.

**Comment by dreis2211** [comment]
If I may add to this: https://openjdk.java.net/jeps/411 is deprecating the `SecurityManager` for removal.

**Comment by philwebb** [comment]
Ahh yes, thanks @dreis2211. It'll be interesting to see if we can support older and newer JDKs at the same time.

**Comment by onlyGuo** [comment]
I think I might have a similar problem. But I'm not sure if it has anything to do with this, I saved a snapshot with jmap.
[https://github.com/onlyGuo/other/raw/master/huanbao.zip](url)

**Comment by wilkinsona** [comment]
The nested jar rewrite in 3.2 has taken care of this.
