### ISSUE TITLE
Fix a typo in Spring Boot 2.5 Release Notes

### ISSUE THREAD

**Issue by KyeongMoon** [spring-projects/spring-boot#26768]
embdedded must be fixed to embedded
on https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#warning-for-users-of-schemasql-and-datasql-files

> This means that schema.sql and data.sql scripts are now applied to the primary datasource, regardless of whether it is embdedded or not.

**Comment by snicoll** [comment]
@KyeongMoon good catch, thank you.
