### ISSUE TITLE
@RabbitAutoConfiguration and 'requestedHeartBeats`

### ISSUE THREAD

**Issue by bmcustodio** [spring-projects/spring-boot#2676]
Currently, [`RabbitConnectionFactoryCreator`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitAutoConfiguration.java#L100) does not set [`requestedHeartBeats`](http://docs.spring.io/spring-amqp/reference/htmlsingle/#d4e338) on the created `CachedConnectionFactory`. Would you consider merging a PR in which this property was set based on a new configuration value, say, `spring.rabbitmq.requested-heart-beats`?

**Comment by philwebb** [comment]
Absolutely we would :)

**Comment by bmcustodio** [comment]
@philwebb Nice :-) I'll take care of that on the next couple of days.

**Comment by philwebb** [comment]
Cool. Please sign the CLA if you haven't already (see https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)

**Comment by snicoll** [comment]
hey @bmcustodio looks like we already reported that (amongst other things) in #2655 - Would you like to try to extend your PR to these additional settings. We can help you in the process.

**Comment by bmcustodio** [comment]
@snicoll Sure. I'll be working on that for the next couple of days.

**Comment by snicoll** [comment]
This was implemented as part of #2655
