### ISSUE TITLE
Provide a Validation starter

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2678]
We (rightly, imo) don't include EL dependencies in `spring-boot-starter`. This has tripped a few people up when they trying to use Hibernate validator and it fails due to their being no EL dependency available. We could, perhaps, make people's lives slightly easier by providing `spring-boot-starter-validation` that pulls in Tomcat's EL implementation and Hibernate Validator.

**Comment by snicoll** [comment]
:+1:  - nice addition for start.spring.io as well.

**Comment by rashidi** [comment]
:+1: I believe I am amoing those being trippped.
