### ISSUE TITLE
Add how-to documentation for test-only database migrations with Flyway/Liquibase

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#26796]
See #26692 for background.

Our current documentation has the following:

> If you are using a Higher-level Database Migration Tool, like Flyway or Liquibase, you should use them alone to create and initialize the schema. Using the basic schema.sql and data.sql scripts alongside Flyway or Liquibase is not recommended and support will be removed in a future release.

It would be nice if rather than just saying what users shouldn't do, we provide some details of how Flyway and Liquibase can be used for test-only migrations.

**Comment by philwebb** [comment]
We can also mention `@Sql` from `org.springframework.test.context.jdbc`.

**Comment by michael-simons** [comment]
That’s great. If you’d like a pair of eyes to review, please ping me in the PR.

**Comment by landsman** [comment]
Still the same :/
