### ISSUE TITLE
Introduce builder customizer for Lettuce `ClientResources`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-boot#26792]
Customizing an existing `ClientResources` instance is difficult for integration libraries as it requires a `BeanPostProcessor` calling `ClientResources.mutate()`. Using `BeanPostProcessor` limits the ability of what Spring Beans can be injected during customization. 

This came up while trying to set Lettuce's `ClientResources.tracing(…)` using a Spring Cloud Sleuth bean. It would be good to have a `ClientResourcesBuilderCustomizer` API to let Spring Boot create `DefaultClientResources` while being able to hook into builder customization.

**Comment by marcingrzejszczak** [comment]
This is the related commit in Spring Cloud Sleuth https://github.com/spring-cloud/spring-cloud-sleuth/commit/6bca07075f018e5bdef04bbb49df19e6f22d4a50
