### ISSUE TITLE
Remove org.eclipse.jetty:jetty-jsp from spring-boot-starter-jetty?

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2680]
Reasons why I think we should:

- The documentation claims that JSPs don't work with embedded Jetty making the dependency pointless (or the documentation incorrect...)
- `spring-boot-starter-tomcat` doesn't include JSP support so this would make things consistent
- It removes 3.2MB from a Jetty-based fat jar (`spring-boot-sample-jetty` drops from 12MB to 8.8MB).

**Comment by snicoll** [comment]
:+1:

**Comment by cemo** [comment]
+1 

As a side note I have been using JSP with embedded Jetty for a few years. The documentation might be correct but problems in embedded Jetty can be tackled with a few tricks.

**Comment by wilkinsona** [comment]
@cemo Do you think those tricks may be of general interest to Boot and Jetty users? If so, could you share them somewhere please.

**Comment by cemo** [comment]
I was planning same thing. I will create an application and will share here.

**Comment by philwebb** [comment]
+1 from me, targeting for 1.3
