### ISSUE TITLE
parse http headers in case insensitive manner

### ISSUE THREAD

**Issue by akosyakov** [spring-projects/spring-boot#26811]
HTTP headers are case insensitive by the spec. Particularly, we are trying to run spring-boot behind caddy (golang based reverse proxy) and stumbled upon https://github.com/gitpod-io/gitpod/issues/4047#issuecomment-856566526

**Comment by francislavoie** [comment]
In particular, this regexp needs to be changed to be case insensitive: https://github.com/spring-projects/spring-boot/blob/4c71e8124d99c12dfaa2e342b12355bd0954cb8b/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/livereload/Connection.java#L44

**Comment by wilkinsona** [comment]
Closing in favour of #26813.
