### ISSUE TITLE
Investigate metrics overhaul

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2682]

**Comment by dacrome** [comment]
As I already described in the mentioned issue https://github.com/spring-projects/spring-boot/issues/2627, I would like to have support also for non-numeric values in gauges. [Dropwizard Metrics Gauges] (https://dropwizard.github.io/metrics/3.1.0/getting-started/#gauges) accepting non-numeric values and when using [hystrix-codahale-metrics-publisher](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-codahale-metrics-publisher) and calling the /metrics endpoint a ClassCastException occurs (fixed with https://github.com/spring-projects/spring-boot/commit/743482ab697e844d51b059051e990a45534e8db4). But this fix just preventing the exception and ignoring all non-numeric values.

**Comment by snicoll** [comment]
On my side, I'd like we revisit the decision of dumping *everything* on a `/metrics` call. I am busy adding cache metrics with only 3 entries per cache for now (size, hit and miss count) but a large application may soon ending with too much information in there. I understand readability is not a concern but performance might be.

Maybe metrics can be "namespaced" (via the key) and the endpoint would reflect that. The root json response for `/metrics` could provide a set of url to "follow" to have more information. `/metrics/cache` may show only the cache specific metrics (and trigger only those).

**Comment by tkrille** [comment]
+1 for support of non-numeric values

**Comment by dsyer** [comment]
I'm still in the camp that believes a metric is a measurement so it has to be a number. Can you describe a use case for the non-numeric values?

**Comment by dacrome** [comment]
The netflix guys make use of different types and [have specified metrics with Boolean, String and Number](https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#property-values-informational). I think Boolean values can be also a measurement, maybe if some dependent component is on or off. String values are useful to show a current status, this could be an enumeration of the current health status of the service (OK, CRITICAL, DANGER, ...).

**Comment by wilkinsona** [comment]
It'd be nice to be able to produce metrics in a format that can be consumed via VisualVM. See [this question of Stackoverflow](http://stackoverflow.com/questions/29679887/spring-boot-mbean-metrics-compatible-with-visualvm-graph-output).

**Comment by dsyer** [comment]
(sent from my phone)

**Comment by dsyer** [comment]
Nice idea. I think all you need is to register an MBean per metric. We could do an exporter for JMX (that's how Dropwizard does it I think, so it's already available for Spring Boot apps that also use Dropwizard).

Other exporters or writers I think we could provide: graphite and/or statsd, new relic, cloudwatch. I would probably to two and look for community contributions for others (someone already asked about cloudwatch).

**Comment by sbuettner** [comment]
Would be great to have something like spring-metrics which contains strategy interfaces like `MetricWriter`. Currently you would have to depend on the actuator project to add something like a `CloudWatchMetricWriter.  Maybe relevant to: https://github.com/spring-cloud/spring-cloud-aws/issues/7

**Comment by dsyer** [comment]
Why is depending on the actuator a problem? Anyway you might have noticed this issue is closed. If you want to discuss please open another one (or drop into gitter if it's just a quick question or clarification).
