### ISSUE TITLE
Align Nimbus dependency versions with those of Spring Security

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#26820]
For Spring Boot 2.4 and 2.5 we'd like to align our dependency management for nimbus with whatever Spring Security declares. We should update our build to:

* Exclude them from bomr
* Read the Spring Security version and parse their github
* Enforce our version matches

We can parse [the lockfile](https://github.com/spring-projects/spring-security/blob/5.4.6/oauth2/oauth2-resource-server/gradle/dependency-locks/optional.lockfile) for earlier versions of Spring Security and [the dependencies file](https://github.com/spring-projects/spring-security/blob/main/dependencies/spring-security-dependencies.gradle) for later ones.

**Comment by wilkinsona** [comment]
See also https://github.com/spring-projects/spring-boot/issues/21279.

**Comment by wilkinsona** [comment]
We've decided to take a slightly different approach and use Bomr to keep things aligned.
