### ISSUE TITLE
JDBC can not use custom properties

### ISSUE THREAD

**Issue by jiaohu** [spring-projects/spring-boot#26844]
the question is that , we implement a JDBC driver,  and we want to use `DataSourceProperties`, however , there is no way to expand the params that we can use the params defined by ourself. It seems that you  could supply a param named "customerProperties" which is type for `Map<String, String>`,  just like what you do in `DataSourceProperties.Xa`. Or Are there some other good ways to realize it?

**Comment by philwebb** [comment]
You can add `@ConfigurationProperties` to your bean definition. That's how we do it for auto-configured data sources. For example [this](https://github.com/spring-projects/spring-boot/blob/2e2d1fe8d3537ddb19f6dc96ff440c33524a5ef2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L88) will bind `spring.datasource.hikari.*` properties directly to the data source.

**Comment by jiaohu** [comment]
OK! Thanks to you. I solved my problem.

**Comment by jiaohu** [comment]
> You can add `@ConfigurationProperties` to your bean definition. That's how we do it for auto-configured data sources. For example [this](https://github.com/spring-projects/spring-boot/blob/2e2d1fe8d3537ddb19f6dc96ff440c33524a5ef2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L88) will bind `spring.datasource.hikari.*` properties directly to the data source.

ok! thanks to you. I solved my problem by the way you told to me
