### ISSUE TITLE
loader: archive main class should fall back to Main-Class attribute if the Start-Class attribute is unavailable

### ISSUE THREAD

**Issue by patrikbeno** [spring-projects/spring-boot#2684]
see 
https://github.com/spring-projects/spring-boot/blob/cb067ee00c17c8b66da854436e8e02f221fb3e53/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/archive/Archive.java#L50

**Comment by patrikbeno** [comment]
#2685

**Comment by wilkinsona** [comment]
What's your use case for falling back to `Main-Class`?

**Comment by patrikbeno** [comment]
Null layout, or pluggable layouts in general, as introduced in #2629.

You may have a layout that does not inject loader and/or does not override archive entry point (Main-Class). 
In such case, expected behavior is to leave Main-Class as is.

**Comment by snicoll** [comment]
Closing in favour of pr #2685
