### ISSUE TITLE
class MetricsClientHttpRequestInterceptor - possible memory leak

### ISSUE THREAD

**Issue by mbechtold1** [spring-projects/spring-boot#26853]
Spring Boot version 2.4.6

I have recently been researching a potential memory leak in our REST service.  I believe I have narrowed it down to class MetricsClientHttpRequestInterceptor.  Specifically it contain a static list named urlTemplate.  I believe this list is growing without constraint and I have to question some code on lines 97-99 that follow:

    if (urlTemplate.get().isEmpty()) {
	urlTemplate.remove();			
    }

Do we potentially need a NOT operator here so that items are removed from the list ?
Thank you for your consideration.

![heapdump](https://user-images.githubusercontent.com/85688389/121542087-739bc880-c9cd-11eb-8203-79bcddb2beda.jpeg)

**Comment by wilkinsona** [comment]
Duplicates #25860.

**Comment by wilkinsona** [comment]
@mbechtold1, with reference to #25860, how are you using the URL template handler?
