### ISSUE TITLE
Document the necessary changes for creating a new maintenance branch

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#26863]
Given my poor attempt at branching `2.5.x` and the excellent [PR that followed](https://github.com/spring-projects/spring-boot/pull/26861) (thanks @dreis2211!), it would be nice if we documented the places to look for when switching to a new feature release.

**Comment by wilkinsona** [comment]
I've taken a first pass at this: https://github.com/spring-projects/spring-boot/wiki/Creating-A-New-Maintenance-Branch.
