### ISSUE TITLE
NoSuchMethod error from Gradle plugin's KotlinPluginAction when using Kotlin 1.5.20-RC

### ISSUE THREAD

**Issue by aerisnju** [spring-projects/spring-boot#26864]
We use `KotlinPluginWrapper.kotlinPluginVersion` to get the kotlin version in boot gradle plugin as advised in #11711. But the jetbrains developers have removed the property `kotlinPluginVersion` recently in [this change](https://github.com/JetBrains/kotlin/commit/4cb6303fa85aaad3c5b4acdd5589c7526fe1f18d). So if we try to upgrade kotlin to 1.5.20-RC, we will see the error

```
* Exception is:
java.lang.NoSuchMethodError: 'java.lang.String org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper.getKotlinPluginVersion()'
	at org.springframework.boot.gradle.plugin.KotlinPluginAction.execute(KotlinPluginAction.java:36)
	at org.springframework.boot.gradle.plugin.KotlinPluginAction.execute(KotlinPluginAction.java:32)
	at org.springframework.boot.gradle.plugin.SpringBootPlugin.lambda$null$0(SpringBootPlugin.java:126)
	...
```

which prevents us from upgrading kotlin to 1.5.20-RC. Latest boot release 2.5.1 still has the issue.

**Comment by wilkinsona** [comment]
Thanks for letting us know. That's an unfortunate breaking change in Kotlin's Gradle plugin. It looks like we may be able to retrieve the version by looking for the `project.version` in the `project.properties` file. That's what Kotlin's Gradle Plugin is doing under the covers so it should be safe for us to do the same I think.

**Comment by materemias** [comment]
@wilkinsona is there a workaround we could utilize until the fix comes?

**Comment by materemias** [comment]
thanks anyways

**Comment by wilkinsona** [comment]
I've reached out to Jetbrains to see if they can reinstate the accessor or point us to another mechanism to get the version that doesn't require us to read their properties file.

**Comment by Tapchicoma** [comment]
Method signature in `1.5.20` was changed - now it is [an extension function](https://github.com/JetBrains/kotlin/blob/8c699136402ccd92df817d6fd8ec58aa96bd4a54/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPluginWrapper.kt#L255) for the `Project` object. Will it work for you?

**Comment by wilkinsona** [comment]
No, I don't think so as we don't want to require 1.5.20. We'd like to be able to support any 1.5.x version with the same code.

**Comment by wilkinsona** [comment]
@Tapchicoma has kindly opened https://youtrack.jetbrains.com/issue/KT-47317 so I think we can close this one. I've also opened [a Boot issue](https://github.com/spring-projects/spring-boot/issues/26946) so that setting `kotlin.version` manually will be a workaround for this sort of problem in the future.
