### ISSUE TITLE
Make auto-configuration classes more lenient to multiple bean instances of uniquely required dependencies

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#2687]
A lot of auto-configuration classes depend on uniquely identifiable Spring bean being present in the `ApplicationContext`. An example of that is `HibernateJpaAutoConfiguration` which uses `@Autowired DataSource dataSource`.

In case an application uses multiple `DataSource`s, there are basically two options to work around the exception this will cause on application startup:
1. Explicitly deactivating the auto-configuration.
2. Marking one of the multiple beans as `@Primary` which can be an option but basically creates an imbalance between the competing bean definitions in terms of the application of auto-configuration. Also that approach allows unqualified autowiring of that bean into clients (as that's what the auto-config-class actually uses, too) which might be undesired as users might need to be selective about the dependency required.

I am suggesting to basically skip the auto-configuration classes that cannot be initialized properly and just explain why in the auto-configuration report. It could then still kick in if one of the competing bean definitions is marked primary. If an auto-configuration class can deal with multiple bean instances of a certain type they should explicitly express this by autowiring a `List` of that type.

Alternatively, @snicoll suggested to add a dedicated flag to `@ConditionalOnBean` to express this particular case. I'd argue it basically just duplicates what's implicitly expressed in the setup of the auto-config class already.

This [Spring Data sample project](https://github.com/spring-projects/spring-data-examples/tree/master/jpa/multiple-datasources) has a sample use case for this scenario. A Boot app interacting with two separate `DataSource`s. In that case it's particularly important not to make one of the `EntityManager`s primary as developers have to explicitly choose which one to refer to. Hence, I decided to explicitly exclude the auto-configuration for the JPA setup, `DataSource`-initialization and transaction management setup.

**Comment by olivergierke** [comment]
I just skimmed through `DataSourceTransactionManagerAutoConfiguration` and realized that my proposed change might require a bit refactoring actually for which that particular auto-configuration is a good example for.

`DSTMAC` leniently depends on a `DataSource` and then does two things:

1. Set up a `DataSourceTransactionManager` in case a `DataSource` is present.
2. Enable annotation based transactions.

The first item is already build to work around no `DataSource` being present at all. I'd argue it should just back of the attempt to apply this part of the configuration if multiple `DataSources` are a general injection candidate, too. Applying my suggested (disabling the auto-configuration) would then also disable the second item in that list, which shouldn't be the case here actually. So it boils down to the fact that some of the configuration classes might have to be restructured in a way that the strong dependencies on a unique bean instance are more isolated so that they can be switched of in a more fine grained way.

**Comment by philwebb** [comment]
On the surface this seems sensible suggestion. If we fix #1702 we probably just need to tweak a for annotations.

**Comment by philwebb** [comment]
#1702 is fixed now.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by snicoll** [comment]
On further inspection, it looks like the request expressed on a particular example in this issue has been addressed in 2.0. If that's not the case, we're happy to have another look.

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-boot/issues/8434.
