### ISSUE TITLE
PropertiesLauncher does not take into account "loader.system" property, when specified in file

### ISSUE THREAD

**Issue by astorath** [spring-projects/spring-boot#2690]
Hi, `PropertiesLauncher` resolve `"loader.system"` property against System Properties only, which does not (yet) include properties, defined in *application.properties* (`"loader.config.name"`):

``` java
			if (SystemPropertyUtils.resolvePlaceholders(
					"${" + SET_SYSTEM_PROPERTIES + ":false}").equals("true")) {
				this.logger.info("Adding resolved properties to System properties");
				for (Object key : Collections.list(this.properties.propertyNames())) {
					String value = this.properties.getProperty((String) key);
					System.setProperty((String) key, value);
				}
			}
```

**Comment by philwebb** [comment]
The `PropertiesLauncher` is invoked very early as the application starts up and before any classes from nested JARs can be loaded. Unfortunately, I don't think it's possible for us to support the same `application.properties` system.
