### ISSUE TITLE
Update Spring Boot 2.5 release notes

### ISSUE THREAD

**Issue by nicovanlooy** [spring-projects/spring-boot#26914]
Hi!

I just noticed the following detail on the [Wiki page for the Spring Boot 2.5 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes):

This wiki page mentions `Liquibase 4.2` as dependency upgrade, but in reality it is `Liquibase 4.3` according to https://github.com/spring-projects/spring-boot/releases/tag/v2.5.0.

Thanks,
Nico

**Comment by scottfrederick** [comment]
Good catch @nicovanlooy, thanks, I've updated the release notes.
