### ISSUE TITLE
spring boot plugin package supports zip or tar.gz

### ISSUE THREAD

**Issue by melin** [spring-projects/spring-boot#26927]
spring boot application packaged into jar, deployment Uninconvenient to modify the configuration and does not provide a fixed startup script to set the jvm parameter。It is recommended to provide packaged plugins like tomcat,kafka directory structure, forming a standard。

![image](https://user-images.githubusercontent.com/1145830/122193950-8c254a80-cec7-11eb-8547-34ad7f40049b.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We support this with Gradle by [building upon the functionality provided by its application plugin](https://docs.spring.io/spring-boot/docs/2.5.1/gradle-plugin/reference/htmlsingle/#publishing-your-application.distribution). I don't believe Maven has equivalent functionality and building it ourselves is out of the scope of Spring Boot. In short, you can either use Gradle to build your application and make use of its built-in capabilities or you can stick with Maven and implement something that meets your needs.

**Comment by melin** [comment]
> Thanks for the suggestion. We support this with Gradle by [building upon the functionality provided by its application plugin](https://docs.spring.io/spring-boot/docs/2.5.1/gradle-plugin/reference/htmlsingle/#publishing-your-application.distribution). I don't believe Maven has equivalent functionality and building it ourselves is out of the scope of Spring Boot. In short, you can either use Gradle to build your application and make use of its built-in capabilities or you can stick with Maven and implement something that meets your needs.

http://maven.apache.org/plugins/maven-assembly-plugin/

**Comment by wilkinsona** [comment]
Yeah, the Assembly plugin’s a good option if you want to implement something yourself with Maven. It isn’t, unfortunately, something that we can easily build on top of as we do with Gradle’s application plugin.

**Comment by melin** [comment]
> Yeah, the Assembly plugin’s a good option if you want to implement something yourself with Maven. It isn’t, unfortunately, something that we can easily build on top of as we do with Gradle’s application plugin.

In actual development, basically using maven,gradle is too flexible, learning cost is too high, it is difficult to use in a big company.

SAAS Services Software has strong basic service products that support spring boot jar for convenient and fast deployment.Delivery project is not a good option, software implementers have no fixed start or stop script, if multiple spring start applications are deployed on the machine, the process name is indistinguishable without different names, temporary modified configuration or html, css, js or image, can only be repackaged. Or use nginx to force a front-and-back separation deployment.

Integrate maven-assembly-plugin, to add new features in spring-boot-maven-plugin, providing a fixed directory structure and shell scripts. Is this solution feasible?
