### ISSUE TITLE
ConditionalOnBean does not search all other Configuration classes for the bean and hence ignores the Bean creation .

### ISSUE THREAD

**Issue by SanjayGautam** [spring-projects/spring-boot#26938]
I have Three configuration `@Configuration` files ,  e.g. `CrrConfig`, (`CrrWsConfig` extends `ParentCrrWsConfig`) `ParentCrrWsconfig` has 

```java
@Configurtion 
public class   CrrWsConfig extends ParentCrrWsConfig   {

....../// other configuration 

}
```

```java
@Configuration 
public class   ParentCrrWsConfig {

    @Bean
    @ConditionalOnBean
    @DependsOn(value = { "enableQuartz" })
    public SchedulerFactoryBean quartzScheduler(ApplicationContext applicationContext) {
              .. do something 
     }
}
```

```java
@Configuration 
public class   CrrConfig {

    @Value("${enable.quartz}")
    private String  enableQuartzFlag;

   @Bean
    publiv String enableQuartz(){
       return enableQuartzFlag;
     }
}
```

if I define the bean `enableQuartz` in a different class `CrrConfig`, the `ParentCrrWsConfig` class when configuring the application and instantiating all the Spring beans does not instantiate the quartzScheduler method, but it works if I declare the enabelQuartz been in the child classes `CrrWsConfig`, Does the Default : `org.springframework.boot.autoconfigure.condition.SearchStrategy.ALL` this really works or I have wrong understanding of the Search,.

**Comment by philwebb** [comment]
@SanjayGautam I'm afraid you can't use `@ConditionalOnBean` on regular `@Configuration` classes, it's specifically designed for auto-configuration. See [this part of the Javadoc](https://github.com/spring-projects/spring-boot/blob/7bd6611e4cb6c68ad590373f54722ab0c16a6742/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnBean.java#L53-L56).
