### ISSUE TITLE
spring-integration-jmx causes java.lang.ClassCastException: com.sun.proxy.$Proxy...

### ISSUE THREAD

**Issue by edgedalmacio** [spring-projects/spring-boot#2693]
I have a project that has a dependency on the following:

spring-boot-starter-integration:1.2.2.RELEASE
spring-integration-java-dsl:1.0.1.RELEASE

which works fine when you run with mvn spring-boot:run

but... the moment I added a dependency on spring-integration-jmx:4.1.2.RELEASE

it starts throwing the ff:

Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy50 cannot be cast to org.springframework.integration.channel.DirectChannel

UPDATE: spelling

**Comment by wilkinsona** [comment]
This is a Spring Integration but that will be addressed in its 4.2 release. See #2441 for more details
