### ISSUE TITLE
Mention @DependsOnDatabaseInitialization and when you may want to use it in the release notes 

### ISSUE THREAD

**Issue by MarcelMerkle** [spring-projects/spring-boot#26941]
Dear Spring Boot team,

with the refactoring of the datasource initialization you introduced an incompatible change regarding the datasource DDL initialization. Earlier the DDL initialization was performed directly after the initilization of the datasource which we assume was achieved by the [`DataSourceInitializerPostProcessor`](https://github.com/spring-projects/spring-boot/blob/2.4.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceInitializerPostProcessor.java). Now the datasource initialization is executed by the [`DataSourceScriptDatabaseInitializer`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/init/DataSourceScriptDatabaseInitializer.java) which is an `InitializingBean` that runs at some (random?) point during initialization. This leads to the problem that you get a datasource during initialization that is not initialized with the DDL statements causing SQL errors.

Best regards,
Marcel

**Comment by wilkinsona** [comment]
If you use the `DataSource` via `JdbcTemplate`, JPA, jOOQ, etc, it's guaranteed that the `DataSource` will have been initialized before it's used. If you're working with the `DataSource` directly you can use `@DependsOnDatabaseInitialization` on a bean's class or `@Bean` method to indicate that the bean should be initialized after the datasource. This is [described in the documentation](`https://docs.spring.io/spring-boot/docs/2.5.1/reference/htmlsingle/#howto.data-initialization.dependencies.depends-on-initialization-detection`) but we should mention it in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#sql-script-datasource-initialization) as well. We can use this issue to do that.

**Comment by wilkinsona** [comment]
I've added a [note about initialization ordering](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#initialization-ordering) to the release notes.

**Comment by MarcelMerkle** [comment]
Thank you!
