### ISSUE TITLE
There are no metrics jvm_* in the actuator/prometheus

### ISSUE THREAD

**Issue by Monax111** [spring-projects/spring-boot#26944]
After update Spring(2.4.2 -> 2.5.0) i can't see jvm metric by url 
`http://localhost:8080/application/actuator/prometheus`
dependency report: https://scans.gradle.com/s/aof3kiwqv7mae
i start debugging and found some interesting:
MeterRegistryPostProcessor.postProcessAfterInitialization() - condition `if (bean instanceof MeterRegistry)` is never true.
I think problem in order. I mark some breakPoint:
1) created bean MeterRegistryPostProcessor.
2) execute method AbstractAutowireCapableBeanFactory.doCreateBean for bean PrometheusMeterRegistry
  2.1) created bean PrometheusMeterRegistry
  2.2) execute initializeBean() witch execute method applyBeanPostProcessorsBeforeInitialization(). In debbug mode i see, then in list of beanPostProcessor do not contains MeterRegistryPostProcessor
 proof:
![image](https://user-images.githubusercontent.com/17501801/122389362-89832d80-cf79-11eb-972d-82f7dc459710.png)
  2.3)  MeterRegistryPostProcessor.postProcessAfterInitialization()  do not execute on bean PrometheusMeterRegistry.
3) Execute AbstractBeanFactory.addBeanPostProcessors() and in debuggin mode i see than  MeterRegistryPostProcessor add to context
![image](https://user-images.githubusercontent.com/17501801/122389810-00202b00-cf7a-11eb-89be-5c195e411958.png)

How i undersend problem: MeterRegistryPostProcessor do not add to context before created bean PrometheusMeterRegistry

**Comment by bclozel** [comment]
Is there a chance this is a duplicate of #26630 ?
Could you check if 2.5.1 solves the issue in your application?

**Comment by Monax111** [comment]
yep. With 2.5.1 it's work

**Comment by snicoll** [comment]
Thanks for following up.
