### ISSUE TITLE
SpringBootServletInitializer, add SpringApplicationBuilder factory method

### ISSUE THREAD

**Issue by lfridael** [spring-projects/spring-boot#2694]
It would be convenient for `SpringBootServletInitializer` to have a factory method for instantiating `SpringApplicationBuilder`.

```java
protected WebApplicationContext createRootApplicationContext(ServletContext servletContext) {
  SpringApplicationBuilder builder = new SpringApplicationBuilder();
  ...
}
```

Currently you have to override `createRootApplicationContext` in its entirety to instantiate a `SpringApplicationBuilder` subclass.

To illustrate:

```java
protected WebApplicationContext createRootApplicationContext(ServletContext servletContext) {
  SpringApplicationBuilder builder = createSpringApplicationBuilder();
  ...
}

// Default implementation
protected SpringApplicationBuilder createSpringApplicationBuilder() {
  return new SpringApplicationBuilder();
}
```

**Comment by philwebb** [comment]
I can't see any harm in adding this. Incidentally, why do you need to override `SpringApplicationBuilder`?

**Comment by lfridael** [comment]
In this case I'm overriding createSpringApplication() to instantiate a SpringApplication subclass.
