### ISSUE TITLE
org.springframework.http.converter.HttpMessageNotReadableException

### ISSUE THREAD

**Issue by felansu** [spring-projects/spring-boot#2696]
when I try to persist for a json object that contains other objects, using data rest spring generates the following error:

timestamp: 1426997592282
status: 400
error: "Bad Request"
exception: "org.springframework.http.converter.HttpMessageNotReadableException"
message: "Could not read JSON: Template must not be null or empty! (through reference chain: br.com.qrbibliokode.model.entities.EntityUsuario["pessoa"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Template must not be null or empty! (through reference chain: br.com.qrbibliokode.model.entities.EntityUsuario["pessoa"])"

Can see this in my project: https://github.com/felansu/Qr-BiblioKode-Ws/

**Comment by jorool** [comment]
@felansu e aí, cara? alguma novidade? conseguiu resolver de alguma forma? tenho esse mesmo problema há algum tempo...  =/

**Comment by felansu** [comment]
Resolvi sim cara ! 

Tem que criar o Repository do objeto que quer salvar, mesmo não exista, tente isso, se não funciona, utilize a anotação @RestResource(exported = false)

Aguardo feedback!

**Comment by jorool** [comment]
É, acho que a anotação @RestResource(exported = false) no repositório vai funcionar! Estou testando.
