### ISSUE TITLE
Sweep for deprecations to delete

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2697]
`@ConditionalOnMissingClass.value` would be particularly nice to prune

**Comment by wilkinsona** [comment]
Big +1 for getting rid of `@ConditionalOnMissingClass.value`. Its continuing existence caused #2674.

**Comment by philwebb** [comment]
Raised in #2706 

> Remove `@EnableJmsMessaging` and `@EnableRabbitMessaging`,  these are deprecated since 1.2.0 and replaced by the "official" ones (`@EnableJms` and `@EnableRabbit` respectively).

**Comment by wilkinsona** [comment]
`HttpMapperProperties` has been deprecated since 1.2.0
