### ISSUE TITLE
hystrix circuit breaker not working after boot 2.3.12 Release upgrade

### ISSUE THREAD

**Issue by Alok255** [spring-projects/spring-boot#26980]
🐞 Bug **Application has a dependency to hystrix, which does not be compatible to Spring Boot 2.5.1**

🎁 Enhancement **_Requires Spring Boot >= 2.0.0.RELEASE and < 2.4.0.M1._**

🙅 Issue 
```
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:125)
```

**Comment by snicoll** [comment]
Hystrix is not managed by Spring Boot and is in maintenance mode and is no longer maintained. This is the wrong place to report such issue. Please see https://spring.io/projects/spring-cloud-circuitbreaker
