### ISSUE TITLE
Add 172.16.0.0/12 to default internal proxies configuration

### ISSUE THREAD

**Issue by Raniz-at-Sony** [spring-projects/spring-boot#2699]
The default value in RemoteIpValve has included the 172.16.0.0/12 range since [December 2013](https://github.com/apache/tomcat/commit/c1be72fde7b8f4b0ab4059a72bda422e288a3337) whereas the default in ServerProperies doesn't meaning that this range will be excluded when using an embedded Tomcat instance.

It would be desirable to either use the value defined in RemoteIpValve as the default or at least use the same regular expression.

**Comment by wilkinsona** [comment]
We probably should have updated this when we changed to using Tomcat 8 by default; the configuration that we're using is Tomcat 7's current default. The [Tomcat issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=55820) that triggered that change makes a good point:

> I thought about back-porting it to 7.0.x but in the end opted not to as unexpectedly adding to the list of allowed internal proxies between point releases might create problems for some users.

I think we should realign in 1.3.
