### ISSUE TITLE
StartupInfoLogger should log version of more Spring project

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#27]
Currently StartupInfoLoggerm only logs information on the Spring Boot and Spring Framework version. Would be nice if the versions of all used Spring portfolio products would be logged (Spring Batch, Spring Data (JPA), Spring Security etc.).

**Comment by bhoomikatg** [comment]
Is this still an open issue?

**Comment by snicoll** [comment]
It is yes. There is an "open" icon on the top left. Why do you ask?

**Comment by wilkinsona** [comment]
We discussed this recently. For some people, a VCS tag would be sufficient to tell them all they needed to know about their application. For others, details of all of the dependencies and their versions would be useful. The consensus seemed to be that collecting the dependencies and their versions was best done at build time. The information could, perhaps, then be exposed via a plugin to the /info endpoint. Logging it, as suggested in this issue, is another option.

**Comment by philwebb** [comment]
After some consideration we don't think this is such a good idea, it's hard to know where we'd stop. The `/info` endpoint + version control is our recommended solution.
