### ISSUE TITLE
Add a Bomr option to move to SNAPSHOTs

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#27002]
It would be really handy if we had a quick way to jump all Spring dependencies to SNAPSHOTs about a week before we release. I think this is currently a manual process.

**Comment by wilkinsona** [comment]
I'd quite like Bomr to be able to do things in two stages. When there's a new release of a Spring dependency planned, Bomr could open an upgrade issue and generate a commit that moves to snapshots and references the upgrade issue. Once the Spring dependency has been released, Bomr would then generate a commit that moves to the released version and closes the upgrade issue.
