### ISSUE TITLE
Docs appendix is at wrong level

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#27003]
Appendix sections are all at the top level. They should probably move under the `Appendix` title

**Comment by mhalbritter** [comment]
I tried to fix that by adjusting the `include::application-properties.adoc[leveloffset=+1]` to `include::application-properties.adoc[leveloffset=+2]`. This works, but the https://github.com/spring-io/spring-asciidoctor-extensions/tree/main/section-ids asciidoctor plugin, which checks that section ids in child sections adhere to the `parentId.childId` convention logs a warning.

The section id of the "Appendices" is `appendix`, but the section id of the application-properties.adoc isn't `appendix.application-properties`, but only `application-properties`. The application-properties.adoc includes more files like application-properties/core.adoc, which gets autogenerated and has the wrong section ids, too.

**Comment by snicoll** [comment]
Closing in favor of PR #29667
