### ISSUE TITLE
Upgrade to Glassfish JAXB 3.0.1

### ISSUE THREAD

**Issue by ummels** [spring-projects/spring-boot#27020]
Is it possible to upgrade Glassfish/Jakarta JAXB to Version 3.0.1? We are using this version of the JAXB API in one of our dependencies already and now face the issue that our Gradle project with the Spring Boot BOM included downgrades JAXB to Version 2.3.1 which leads to compile errors due to `jakarta.xml.bind` not found.

**Comment by wilkinsona** [comment]
Upgrading to the Jakarta EE 9 versions of relevant Jakarta EE specifications, including JAXB 3, will be done as part of Spring Framework 6.0 and Spring Boot 3.0. The underlying work in Spring Framework is being tracked [here](https://github.com/spring-projects/spring-framework/issues/25354).

**Comment by ummels** [comment]
Thanks for the info!
