### ISSUE TITLE
refreshEvent trigger loggging  system reinitialize,logging configuration on startup will be ignore

### ISSUE THREAD

**Issue by flmelody** [spring-projects/spring-boot#27040]
I add a loggerAppender on startup,like below
![image](https://user-images.githubusercontent.com/47545727/123066311-863ce580-d442-11eb-9fcc-d04ce1934a6a.png)
![image](https://user-images.githubusercontent.com/47545727/123067694-c8b2f200-d443-11eb-9eb9-38f2fb2ed8b2.png)
If refreshEvent trigger,like refresn bean,logging system will reinitialize,and reset logging configuration,use resource file by default
but my appender is not a resource file,so it will be stop and remove ,I'm use logback,and class LogbackLoggingSystem is not support this,maybe some supports  for this situation should be add?

**Comment by flmelody** [comment]
or rewrite LogbackLoggingSystem user self?

**Comment by flmelody** [comment]
I didn't find any way to change the LoggingSystem,any support may I not find?

**Comment by flmelody** [comment]
org.springframework.boot.logging.LoggingSystem property ,I find it

**Comment by flmelody** [comment]
It's too ugly!!

**Comment by gogo-zby** [comment]
You can define org.springframework.boot.logging.LoggingSystem，like that ‘System.setProperty("org.springframework.boot.logging.LoggingSystem","xxx")’ before org,springframework.boot.context.logging.LoggingApplicationListener#onApplicationEvent.

**Comment by flmelody** [comment]
> You can define org.springframework.boot.logging.LoggingSystem，like that ‘System.setProperty("org.springframework.boot.logging.LoggingSystem","xxx")’ before org,springframework.boot.context.logging.LoggingApplicationListener#onApplicationEvent.

I know,but this's too ugly

**Comment by flmelody** [comment]
Maybe publish a LoggingSystemRefreshEvent ? and user do it self

**Comment by flmelody** [comment]
> @flmelody Every comment on this issue notifies everyone who is watching this repository. Please try to avoid making multiple single-sentence comments and instead combine them into a single, longer comment.
> 
> #25847 is tracking support for programmatic configuration of Logback. This issue is a duplicate of that request so I am going to close it. In the meantime, a custom logging system (configured using the system property suggested by @gogo-zby) is your best option.

I will have a try ,thanks
