### ISSUE TITLE
Default value for NettyProperties.leakDetection is not aligned with Netty's default

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#27046]
As seen in #26958, the default value for the `NettyProperties.leakDetection` configuration property does not align with the default value in Netty's `ResourceLeakDetector`. We should ensure that this is always the case.

**Comment by wilkinsona** [comment]
Re-opening as the test [appears to be flakey](https://ge.spring.io/s/cyi6zbp4bgmuy/tests/:spring-boot-project:spring-boot-autoconfigure:test/org.springframework.boot.autoconfigure.netty.NettyPropertiesTests/defaultValueShouldMatchNettys()?expanded-stacktrace=WyIwIl0&top-execution=1). I think it's a test ordering problem.

**Comment by wilkinsona** [comment]
4572ae5430120a7ff9493bdb89c264fd60f46a3a will hopefully stabilise the test.
