### ISSUE TITLE
spring-boot-maven-plugin 2.5.1 build-image goal, spring-cloud-bindings is conflict with tomcat-embed-jasper

### ISSUE THREAD

**Issue by zhanming** [spring-projects/spring-boot#27075]
To build an executable war(with jsp) OCI image, when using `tomcat-embed-jasper` dependency, the `spring-boot-maven-plugin` build-image is OK, but can't run successfully.

I dig a little deeper, during the build-image phase, `spring-boot-maven-plugin` using buidpacks add a soft link of `spring-cloud-bindings-1.7.1.jar` to `/WEB-INF/lib` folder, this jar cause `tomcat-embed-jasper`'s StandardJarScanner throw a NullPointerException.

I found a solution then,  

Add below in application.yml to skip the scan.

```
server:
  tomcat:
    additional-tld-skip-patterns:
    - spring-cloud-bindings*.jar
```

The example code is in the repo  [zhanming/demo](https://github.com/zhanming/demo)

If comment this configuration out, the issue will recur.

Is this soft link of spring-cloud-bindings-1.7.1.jar necessary?

**Comment by wilkinsona** [comment]
Thanks for the report. Spring Cloud Bindings is added to the image by the [Spring Boot Buildpack](https://github.com/paketo-buildpacks/spring-boot) and is out of Spring Boot's control. There is an environment variable, `BPL_SPRING_CLOUD_BINDINGS_ENABLED`, that can be used to control whether or not the bindings are available but it don't believe it has an effect on whether they're contributed to the image. If you'd like such an option to be added, please raise an issue [here](https://github.com/paketo-buildpacks/spring-boot/issues/new).

Interestingly, I can't reproduce the problem in an app with an explicit dependency on `spring-cloud-bindings`. Tomcat's is able to scan the jar when launched in an IDE, using `java -jar app.war`, and unpacked using `java org.springframework.boot.loader.WarLauncher`. We'll need to investigate further to see what's causing it to fail in an image.

**Comment by zhanming** [comment]
Thanks for the quick feedback.

I think `spring-cloud-bindings` is good. The issue is in `spring-boot-maven-plugin`'s `build-image` phase, as you said [Spring Boot Buildpack](https://github.com/paketo-buildpacks/spring-boot) add a soft link of `spring-cloud-bindings` to `/WEB-INF/lib`

Follow the [Whats New in Spring Boot 2.3](https://www.youtube.com/watch?v=WL7U-yGfUXA)

BTW: Thanks to Phil Webb, I'm hoping What's New in Spring Boot 2.5

You can use dive to check the image.

First, build the image.
```
mvn clean spring-boot:build-image
```

Install dive on macOS
```
$ brew install dive
```

Then dive it.
```
dive demo:0.0.1-SNAPSHOT
```

In `/workspace/WEB-INF/lib` folder, you can see `spring-cloud-bindings` is a soft link in there.

I will raise an issue to [Spring Boot Buildpack](https://github.com/paketo-buildpacks/spring-boot), thanks.

**Comment by wilkinsona** [comment]
Thanks. It's the fact that it's a symlink that is key. I can reproduce the problem locally with an unpacked war and `spring-cloud-bindings` symlinked into `WEB-INF/lib`.

**Comment by markt-asf** [comment]
Generally, symlinks won't work unless `allowLinking` is set to `true` on `Context.getResources()`. This looks like a symptom of using a symlink when that isn't set but it also looks like Tomcat could handle this better. To be consistent with how Tomcat handles this elsewhere, I'd expect Tomcat to behave as if the symlinked JAR wasn't present. Please do open a Tomcat issue for this.

**Comment by wilkinsona** [comment]
Thanks, Mark. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=65397.
