### ISSUE TITLE
Documentation for logging.file / logging.path properties defined in application.properties

### ISSUE THREAD

**Issue by ewjmulder** [spring-projects/spring-boot#2709]
I'm using a non-standard location properties file, that includes both Spring Boot properties and my own application custom properties. It is loaded with a `@PropertySource` annotation on the class that I provide to `SpringApplication.run`. This works fine for for instance `server.address` and `server.port`, but it does not pick up `logging.file` or `logging.path`. When I add an `application.properties` with only logging config, it does work.

I'm guessing the logging bootstrap is so 'early' in the process that only the `application.properties` contents is read at that point, and no `@PropertySource` annotations are processed yet? This could be a design choice, but maybe it should be possible, in which case I think this is a bug.

If any more explanation or example code is needed, just let me know. Thanks!

**Comment by philwebb** [comment]
We do indeed need to load `application.properties` early, so it's not possible to use the `@PropertySource` annotation for what you want to do. I think it should be possible to specify an alternative location by calling `SpringApplication.setDefaultProperties(...)` with `ConfigFileApplicationListener.CONFIG_LOCATION_PROPERTY` as a key and the alternative location as the value.

See [this section](http://docs.spring.io/spring-boot/docs/1.2.x/reference/htmlsingle/#boot-features-external-config-application-property-files) of the reference docs for a description of property file overrides.

**Comment by ewjmulder** [comment]
Hi Phil, thanks for the explanation and the pointer to the location override, I have it working now!

I was slightly misguided by the phrase "for example in your application.properties" in section 25.3 of the documentation (see below).

> 25.3 File output
> 
> By default, Spring Boot will only log to the console and will not write log files. If you want to write log 
> files in addition to the console output you need to set a logging.file or logging.path property (for 
> example in your application.properties).

It seemed like these logging properties could be anywhere as long as they were loaded into the Environment at startup time. Of course it makes sense that for logging you need to have a value present very early in the boot process. Maybe the documentation in section 25.3 can be amended somewhat to reflect this?

Cheers, Erik

**Comment by philwebb** [comment]
Good point. We'll fix that.

**Comment by philwebb** [comment]
Actually, I think that the documentation is correct. You can specify `logging.file`/`logging.path` in `application.properties` but you can't from a `@PropertySource` annotation.

**Comment by philwebb** [comment]
I've added a note to make it clearer that you can't use `@PropertySource` for logging properties.
