### ISSUE TITLE
Replace deprecated method call in KotlinPluginAction.getKotlinVersion

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#27090]
[This commit](https://github.com/JetBrains/kotlin/commit/4cb6303fa85aaad3c5b4acdd5589c7526fe1f18d) deprecated `getKotlinPluginVersion` and replaced it with `fun Project.getKotlinPluginVersion(): String`. We should ideally move to the new method.

**Comment by wilkinsona** [comment]
I think we can safely make this change in 2.5 by calling `KotlinPluginWrapperKt.getKotlinPluginVersion(project)`. It's been there for a while now.
