### ISSUE TITLE
Spring Boot in standalone Tomcat ignores exceptions set in DeferredResults

### ISSUE THREAD

**Issue by maddy-markovitz** [spring-projects/spring-boot#2711]
When a controller returning a DeferredResult throws an exception, as in the example below, Tomcat will ignore the exception and return an HTTP 200 with no response body.

```java
    @RequestMapping(value = "html/start", method = RequestMethod.POST, consumes =APPLICATION_FORM_URLENCODED)
    public DeferredResult<String> start(final HttpServletResponse response,
                                    @Valid @ModelAttribute final InitialisationStartAttributes model,
                                    final SessionData sessionExisting) throws MyRequestProcessingException {
    final DeferredResult<String> finalResult = new DeferredResult<>(5000);
                // Just return an error, so we can test
                if (true) {
                    finalResult.setErrorResult(new MyRequestProcessingException(
                            "Something went wrong processing request"));
                }
    return finalResult;
}
```

The exception is annotated with @ResponseStatus.

```java
@ResponseStatus(value=HttpStatus.INTERNAL_SERVER_ERROR)
public class MyRequestProcessingException extends Exception {

public MyRequestProcessingException(String message) {
    super(message);
}   
}
```

If this is executed in a Spring Boot embedded context it will return 500 as one would expect.

I'm running 1.2.1 RELEASE.

**Comment by maddy-markovitz** [comment]
I've managed to work around this to some extent by defining my own @ExceptionHandler for all exceptions, which I can use to return the correct status, but it's pervasive - affects the response status throughout the whole filter chain.  Thus filters and interceptors which are supposed to log the response status will not work.

**Comment by wilkinsona** [comment]
This sounds somewhat similar to #1920. @maddy-markovitz, what version of Tomcat are you using?

**Comment by maddy-markovitz** [comment]
7.0.52, also tested and confirmed this occurs on Tomcat 8.

**Comment by maddy-markovitz** [comment]
It does look similar to #1920, but he says it's happening with embedded Tomcat and I'm only seeing this when I deploy into standalone Tomcat.  Also not sure (without running the example) whether the expected status code is being returned.

**Comment by maddy-markovitz** [comment]
Thanks for the bug fix :)
