### ISSUE TITLE
Split spring boot features in reference documentation into smaller sections

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#27132]
- [x] Add what's next to new sections
- [x] Move hazelcast out of core features
- [x] Rename packages for code samples to match sections

**Comment by RAMESSESII2** [comment]
Hello @mbhave! I'm excited to contribute to this project. Please guide me through it.

**Comment by mbhave** [comment]
@RAMESSESII2 Thanks for your interest. You can take a look at the [issue tracker](https://github.com/spring-projects/spring-boot/issues) to see if there is any issue you'd like to work on. When looking for an issue to work on here are a few things to keep in mind:

- The issue shouldn't already have an assignee (see top right to see if there is an assignee).
- The issue shouldn't have the `blocked` or `pending-design-work` label. 
- Issues marked as `first-timer-only` are good for folks new to the project (We don't always have these).
- Issues marked as `ideal-for-contribution` are other good candidates for contributing.
- Please comment on the issue to let us know you are interested before starting work on it.
