### ISSUE TITLE
Live Reload using Devtools no longer connects

### ISSUE THREAD

**Issue by denis-anisimov** [spring-projects/spring-boot#27147]
Follow the steps here:
https://spring.io/quickstart

Add spring dev tools as a dependency during project configuration here https://start.spring.io/

Use 2.5.2 version

Install Live reload extension for Chrome: https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei/related

Run the app using `mvn spring-boot:run`.
Open browser `http://localhost:8080/hello`.

Click on the Live reload extension button.

There will be an error shown in the popup : see attached image.

The problem is : JS WebSocket class can't connect to the server.

If I write the code in the Chrome console  `ws = new WebSocket("ws://localhost:35729");` then it fails with error.

Everything works fine with `2.5.1` version.
 
<img width="451" alt="Screen Shot 2021-07-05 at 1 33 33 PM" src="https://user-images.githubusercontent.com/11425472/124460467-14489280-dd98-11eb-9bc9-be1e17f476ec.png">

**Comment by denis-anisimov** [comment]
![Uploading Screen Shot 2021-07-05 at 1.33.33 PM.png…]()

**Comment by wilkinsona** [comment]
Thanks for the report and sorry for the inconvenience. I suspect that this regression is caused by the changes for https://github.com/spring-projects/spring-boot/pull/26813. Specifically, I think the lower-casing has corrupted the value of the `sec-websocket-key` header.

**Comment by denis-anisimov** [comment]
Most likely yes.
