### ISSUE TITLE
spring.mvc.favicon.enabled=false does not work on sprint-boot-starter-web

### ISSUE THREAD

**Issue by nabedge** [spring-projects/spring-boot#2714]
```
spring.mvc.favicon.enabled=false
spring.favicon.enabled=false
```

The above properties on `src/main/resources/application.properties` does not work on both of spring-boot 1.2.x and 1.1.x .

sample project: https://github.com/nabedge/sb-favicon-sample

1. start sample application
2. go http://localhost:8080/
3. click link "get favicon.ico"

expected behavior: 404 not found.

actual behavior: download default favicon (green leaf image)

**Comment by philwebb** [comment]
Your example app doesn't returns 404 for me:

```
curl -I http://localhost:8080/favicon.ico
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Content-Length: 115
Date: Wed, 25 Mar 2015 17:09:46 GMT
```

Is it possible that your browser has cached a previous response?

**Comment by nabedge** [comment]
Oh. It's my bogus report. Thank you.
