### ISSUE TITLE
Unexpected yaml behaviour with : in value (but work in url)

### ISSUE THREAD

**Issue by matejsp** [spring-projects/spring-boot#27158]
Problem with yml changing the value in Spring Boot 2.4.4.

```
@Value("${victoria.tenant.id}")
String tenantId;
```

```
victoria.tenant.id: 43:1
```

tenantId is 2581 ... but it should be 43:1 ... 

Colon in URL is ok:
victoria.url http://192.168.80.100/insert/43:1/prometheus/api/v1/import/prometheus

Escaping with '43:1' works but it is error prone.

**Comment by snicoll** [comment]
@matejsp there's nothing we can do about that. It's part of the YAML syntax and escaping is what you should be doing.

**Comment by matejsp** [comment]
I went over https://yaml.org/spec/1.1/ and there is no such thing that 41:1 should be replaced with 2581 :D

**Comment by wilkinsona** [comment]
As per the YAML 1.1 spec, `43:1` is a [sexagesimal](https://yaml.org/spec/1.1/#id858600). It represents 43 minutes and 1 second which is 2581 seconds.
