### ISSUE TITLE
Can not switch off Tomcat in parent context if management endpoints required in child

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2716]
Originally I was concerned that management.port=-1 was causing some weird behaviour.

**Comment by philwebb** [comment]
@dsyer Is this a blocker for 1.2.3? You got a fix in mind or some more details?

**Comment by dsyer** [comment]
I'm looking at it. Confused. I see this in an app on startup:

```
2015-03-25 17:19:15.067  INFO 1058 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): -1 (http)
```

But I would have expected -1 to switch it off completely

**Comment by dsyer** [comment]
It's actually the "main" Tomcat that is started on port -1 (i.e. not listening). I think I assumed I could switch off the main webapp with server.port=-1, but of course that isn't the case. This appears to be as showstopper for a small class of apps that we are interested in for Spring Cloud (management endpoints on Tomcat but netty for the "main" port, then running in Cloud Foundry with the management port disabled).

**Comment by philwebb** [comment]
Sounds like it might be a large(ish) change. Something for 1.3 perhaps?

**Comment by dsyer** [comment]
I've narrowed this down a bit. The problem is basically that if Tomcat and Webby stuff is on the classpath then the `SpringApplication` chooses a `StandardServletEnvironment` really early in its `run()` method and from then on, even if you set `webEnvironment(false)`, the `@ConditionalOnWebApplication` will always be true because (for some reason) it uses the `Environment` to check (arguably it shouldn't). We need to be able to either get rid of that check in the `@ConditionalOnWebApplication` or allow the `Environment` to be changed before the `ApplicationContext` is created. One way to do the latter would be to check if `webEnvironment` is still "true" after the `ApplicationEnvironmentPrepraredEvent` is fired (since it could be changed when the `Environment` is bound  to the `SpringApplication`) and if not switch to a non-web `Environment`.

**Comment by philwebb** [comment]
I tweaked the fix a bit since it broke some of the tests. Might be worth confirming that it's still good.
