### ISSUE TITLE
actuator/info endpoint broken when upgrading from spring boot 2.4 to 2.5

### ISSUE THREAD

**Issue by poser55** [spring-projects/spring-boot#27187]
I created a minimal application with the Spring initializer (demo.zip attached) with Actuator and Spring MVC - I did not add any code of my own, just the default code.
The `http://localhost:8080/actuator/info` endpoint does not work in 2.5.2 (when downgrading to 2.4.8 it works again).

[demo.zip](https://github.com/spring-projects/spring-boot/files/6783012/demo.zip)

Is it related to https://github.com/spring-projects/spring-boot/issues/26746 ?
It does not seem to be related to https://github.com/spring-projects/spring-boot/issues/26630 (spring data is not in the classpath).

**Comment by snicoll** [comment]
@poser55 please consider reviewing the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes) before upgrading to a new feature release. This is covered [in this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#secure-info-endpoint).

**Comment by poser55** [comment]
Sorry, I forgot the 2nd part of the bug report:
Even with my application.yml like this, the info endpoint is not shown:

management.endpoint.info.enabled: true

---
The documentation for 2.5.2 https://docs.spring.io/spring-boot/docs/2.5.2/reference/pdf/spring-boot-reference.pdf still mentions the (old?) config setting:

management.endpoint.info.enabled=true

--
I found now an alternative config setting that works:

management.endpoints.web.exposure.include: info 


But I did not find a mention of the old setting no longer being usable?

**Comment by snicoll** [comment]
That's for enabling the endpoint, not exposing it. The link to the release notes I've shared in my initial comment has a link to [ this part of the documentation](https://docs.spring.io/spring-boot/docs/2.5.0/reference/htmlsingle/#actuator.endpoints.exposing) where the table state that `info` is not exposed. Besides that list, there are a few examples that are using `management.endpoints.web.exposure.include`.

I don't really know what problem you are reporting I am afraid.
