### ISSUE TITLE
Upgrade Reactor to 2.0.x

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#2719]

**Comment by philwebb** [comment]
We need to consider this carefully given that's it a breaking change and Spring Framework currently has an optional dependency on the old one.

**Comment by philwebb** [comment]
Actually, it might be worth adding a JIRA to see what the plan is for Spring 4.2.

**Comment by philwebb** [comment]
And there's also XD to consider.

**Comment by artembilan** [comment]
That's really a requirement from XD.
SI is already based on Reactor 2.0.
AFAIK 2.0 doesn't impact 1.1: they have different packages

**Comment by philwebb** [comment]
I think that both can co-exist but we still need to make the decision about if we should remove v1 from `spring-boot-dependencies`.

/cc @rstoyanchev @wilkinsona

**Comment by rstoyanchev** [comment]
https://jira.spring.io/browse/SPR-12599

**Comment by smaldini** [comment]
FYI we are in consolidation phase (2.0.1) so if you guys upgrade to 2.0.0.RELEASE in spring.io that will be great to verify any pending issue before the candidate we think for Maven Central: 2.0.1

**Comment by philwebb** [comment]
@smaldini We've not worked on the upgrade yet so I don't think we have anything to test yet I'm afriad.

**Comment by wilkinsona** [comment]
Spring Framework 4.2 is now compiling against Reactor 2.0.1 snapshots so now's a good time for us to do the same

**Comment by smaldini** [comment]
Feel free to ping me if you need, also 2.0.1 is around the corner, pending Reactive Streams 1.0 final imminent (https://github.com/reactive-streams/reactive-streams-jvm/issues/223).

**Comment by wilkinsona** [comment]
Boot's 1.3.0 snapshots are now building successfully against Reactor's 2.0.1 snapshots
