### ISSUE TITLE
Add class / package exclusions to @SpringBootTest annotation

### ISSUE THREAD

**Issue by Halverson-Jason** [spring-projects/spring-boot#27191]
For integration tests, it would be helpful to exclude certain classes or packages from being loaded into the application context when that specific test is run. It would be helpful to have an exclude filter within the annotation instead of having to explicitly include items in the context.

**Comment by philwebb** [comment]
Have you tried the `@TypeExcludeFilters` annotation (from `org.springframework.boot.test.autoconfigure.filter`)?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
