### ISSUE TITLE
JMX for Atomikos connection pool

### ISSUE THREAD

**Issue by SDLearner** [spring-projects/spring-boot#27214]
We are unable to view Atomikos (v 5.0.3) connection pool settings in JMX (HawtIo), our application uses Spring+Embedded Tomcat (9.0.45). Our application uses AtomikosDataSourceBean that uses oracle.jdbc.xa.client.OracleXADataSource XA data source.
 After reading various posts (for ex. https://github.com/atomikos/transactions-essentials/issues/55), it looks like the only way to view connection pool settings via JMX is to download 3.9.3 transactions-jmx project. We are unfortunately unable to download the jar from maven/atlassian repo. Any help will be greatly appreciated as we need to put the code in Production in a week or so and need to monitor db active/idle connections etc. via JMX.
Also, will there be an issue using transactions-jmx v3.9.3 jar with Atomikos 5.0.3?

**Comment by snicoll** [comment]
@SDLearner please direct that support request to the Atomikos forum.
