### ISSUE TITLE
Add Spring Data Jsr310JpaConverters (JDK8 dates) automatically to @EntityScan if applicable

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#2721]
With latest Spring Data 1.8 (Fowler) release, Spring Data provides convenient JDK8 data converters via `org.springframework.data.jpa.convert.threeten.Jsr310JpaConverters`.

To apply these automatically I have to to add the following to a configuration class:

`@EntityScan(basePackageClasses = {Application.class, Jsr310JpaConverters.class})`

It would be very nice if Spring Boot could add these `Jsr310JpaConverters.class` automatically to the entity scan process. Just like it would add the `Application.class` automatically if I would not provide the `@EntityScan` annotation.

Of course this should only be done if applicable; e.g. using JDK8 and Spring Data JPA.

Depends on: https://github.com/spring-projects/spring-boot/issues/2721

**Comment by marceloverdijk** [comment]
Also see this stackoverflow thread for reference: http://stackoverflow.com/questions/29241575/new-spring-data-jdk8-jsr310jpaconverters-not-working-automatically

**Comment by philwebb** [comment]
Also `ThreeTenBackPortJpaConverters` and see https://spring.io/blog/2015/03/26/what-s-new-in-spring-data-fowler

**Comment by philwebb** [comment]
Relates to #2721

**Comment by wilkinsona** [comment]
This isn't quite as straightforward as I thought. Using `@EntityScan` on one of our configuration classes has the unwanted side-effect of switching off the default which is retrieved from `AutoConfigurationPackages`

**Comment by thomasdarimont** [comment]
Couldn't you just add the Jsr310Converters dynamically in `EntityScanRegistrar.getPackagesToScan(..)`?

**Comment by wilkinsona** [comment]
> Perhaps you could add the Converters in EntityManagerFactoryBuilder.Builder.build().

I don't really want `EntityManagerFactoryBuilder` to know anything about Spring Data JPA

**Comment by thomasdarimont** [comment]
Sure - you're right (although it actually comes from SD Commons but the same applies here..).
Maybe we should take a step back and add those converters (which don't depend on any JPA APIs at all) to the `DefaultConversionService` in Spring Framework Core - this whould eliminate the problem in the first place, right?

**Comment by philwebb** [comment]
After some discussion we're of the opinion that it's probably not sensible to add this since it's been [fixed in Hibernate 5](https://hibernate.atlassian.net/browse/HHH-8844).

**Comment by olivergierke** [comment]
Does that mean Boot 1.4 will upgrade to Hibernate 5?

**Comment by wilkinsona** [comment]
@olivergierke Yes. See #2763.

**Comment by olivergierke** [comment]
Great news, thanks! :)
