### ISSUE TITLE
@ConstructorBinding behavior by default for @ConfigurationProperties annotated records

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-boot#27216]
From [ConfigurationProperties javadoc](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationProperties.java#L33-L35):
```
Binding is either performed by calling setters on the annotated class or, if
@ConstructorBinding is in use, by binding to the constructor
parameters.
```

Since records can't and shouldn't have setters, could Spring Boot apply `@ConstructorBinding` behavior by default for `@ConfigurationProperties` annotated records?

**Comment by wilkinsona** [comment]
That sounds like a good idea to me, thanks for the suggestion. We should be able to check if a class is a record without using Java 16 API (`Class#isRecord`) by checking to see if its superclass is `java.lang.Record`.

**Comment by wilkinsona** [comment]
The implementation for this is [pretty straightforward](https://github.com/wilkinsona/spring-boot/tree/gh-27216), but testing it as part of our Java 8-based build is not. Flagging for team meeting so that we can discuss what to do.

**Comment by philwebb** [comment]
The only solution I can think of is to have a test that runs only in our Java 16 build. The problem is creating that record class. I guess we could include a binary class file or possibly use cglib to generate the bytecode. Even without a test, the code is so minimal that I'd be tempted to merge it.

**Comment by wilkinsona** [comment]
Thanks, Phil. I'm not sure it's possible with cglib but it is with ByteBuddy. I now have a test that fails without my changes and passes with them in place.

**Comment by snicoll** [comment]
@wilkinsona looking at the commit, it doesn't look like the annotation processor has been updated to apply this mode with a record so I suspect this won't generate the proper metadata or have I missed something?

**Comment by wilkinsona** [comment]
Nope, I just forgot about it.
