### ISSUE TITLE
[docs] PDF: Some section names are not on pages, only in Table of Contents

### ISSUE THREAD

**Issue by paulvi** [spring-projects/spring-boot#2723]
Some section names are not on pages, only in Table of Contents

e.g. in 1.2.2.RELEASE
http://docs.spring.io/autorepo/docs/spring-boot/current/reference/pdf/spring-boot-reference.pdf

    20. Packaging your application for production ....................................................... 37
    21. What to read next ............................................................................................. 38

but on those pages there is no section names

**Comment by wilkinsona** [comment]
The 1.1.x documentation also has this problem. It's a simple fix so I think we might as well fix it there too.

**Comment by paulvi** [comment]
Will it get updated only with next release?

**Comment by snicoll** [comment]
as of the next releases yet. We fixed that up to 1.1.x
