### ISSUE TITLE
Optimize jar size by using Spring Native features

### ISSUE THREAD

**Issue by ArpitSuthar** [spring-projects/spring-boot#27246]
Request for enhancement to spring boot build plugins
- spring-boot-maven-plugin

With announcement of Spring-native , spring-tools can now generate a native-image using static analysis, fixing class-path and so much more. 

As a developer I would like to make a request to make these optimization available while building spring-boot executable jar. 
This should help to reduce the jar size by eliminating / removing unwanted dependencies from final jar.

Overall This would help in 
- Reducing jar size and in-turn docker image size
- Lowering security footprint
- Faster startup and lower resource consumption
- Lower run cost
- greater adoption to spring-native as this would be first step towards spring-native

**Comment by snicoll** [comment]
Our intention from the start is that what we're currently experimenting in Spring Native should also be applicable to the JVM. I don't really understand what you mean by jar size though. Spring Boot has a limited core and doesn't bring extra dependency unless you opt-in for a starter or additional dependencies.

This issue isn't very actionable at this point so I am going to close it now. Let's continue experimenting in Spring Native and see how these can be brought back to Spring Framework 6 and Spring Boot. Feel free to raise additional issues in Spring Native if you have something more specific you'd like to contribute.
