### ISSUE TITLE
Invalid source type class [Ljava.lang.String; for `new SpringApplication(Application.class, args).run(args);`

### ISSUE THREAD

**Issue by paulvi** [spring-projects/spring-boot#2724]
This simple snippet fails
```
@SpringBootApplication
public class Application {
    public static void main(String... args) {
    	new SpringApplication(Application.class, args).run(args);
    }
}
```

with

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid source type class [Ljava.lang.String;
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:146)
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
	at org.springframework.boot.SpringApplication.load(SpringApplication.java:615)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at hello2.Application.main(Application.java:27)
```
the code executes `org.springframework.boot.BeanDefinitionLoader` to load sources

```
	private int load(Object source) {
		Assert.notNull(source, "Source must not be null");

```

while docs says there should be passes `args`

```
	/**
	 * Run the Spring application, creating and refreshing a new
	 * {@link ApplicationContext}.
	 * @param args the application arguments (usually passed from a Java main method)
	 * @return a running {@link ApplicationContext}
	 */
	public ConfigurableApplicationContext run(String... args) {

```

**Comment by wilkinsona** [comment]
You're passing `args` into the `SpringApplication` constructor as well as the `run` method. It should be:

```java
new SpringApplication(Application.class).run(args);
```

**Comment by philwebb** [comment]
Or alternatively if you just have a single source you can use the static method: `SpringApplication.run(Application.class, args)`

**Comment by paulvi** [comment]
It is noticeble when it is one liner, but with some longer code

    	SpringApplication app = new SpringApplication(Application.class, args);
    	app.addListeners(new ApplicationListener<ApplicationEvent>(){
				@Override
				public void onApplicationEvent(ApplicationEvent event) {
					log(event.toString());					
				}
	    	}
    	);
    	app.run(args);

It is not clear.

I think it is logic error that internal state of app may cause error.
