### ISSUE TITLE
Neo4j health details use a deprecated information (org.neo4j.driver.summary.ServerInfo#version)

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#27289]
We are currently providing some details about the Neo4j server in our health indicator. One bit of it, the server version, is now deprecated. We should fix the deprecation and adapt the details.

**Comment by meistermeier** [comment]
Some more information: The `ServerInfo#version` does represent the protocol version database and driver agreed on to communicate with. Currently it does *not* show the version of the database itself.
We already have the call for information about the server in place but would need to extract also the version from the result set and use it as the replacement for the above call.

**Comment by wilkinsona** [comment]
Closing in favour of #27294.
