### ISSUE TITLE
Update RabbitTemplateConfigurer to take its required settings as constructor arguments

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#27313]
`RabbitTemplateConfigurer` has three settings:

- `messageConverter`
- `retryTemplateCustomizers`
- `rabbitProperties`

`rabbitProperties` must be set but both `messageConverter` and `retryTemplateCustomizer` are optional. All three are configured via setter methods making it hard to distinguish between things that are required and things that are optional. As it's required, it'd be good if `rabbitProperties` was a constructor parameter.

To do this in a backwards-compatible manner we'll have to keep the default constructor and add one that takes a `RabbitProperties` instance alongside it. We'll also have to keep the setter, albeit in a deprecated form.

**Comment by beatfreaker** [comment]
@wilkinsona is this issue open for contribution ? can I work on it ?

**Comment by wilkinsona** [comment]
Thanks for the offer, @beatfreaker, but as indicated by its assignment to me, I'm already working on it.
