### ISSUE TITLE
add neo4j test-harness to bom

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#27345]
since gradle platform (obnoxiously) can't support using the `neo4j-version` property, it would be nice if this dependency was managed by the BOM

https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#dataneo4jtest-harness40
```xml
<dependency>
    <groupId>org.neo4j.test</groupId>
    <artifactId>neo4j-harness</artifactId>
    <version>{neo4j-version}</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

```
> Could not resolve all files for configuration ':util:model-graph:testCompileClasspath'.
   > Could not find org.neo4j.test:neo4j-harness:.
     Required by:
         project :util:model-graph
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. At the moment, we only have dependency management for Neo4j's Java Driver. The test harness appears to be released on a different cadence to the Driver so it would have to be managed separately with a different version property.

We try to keep the scope of Spring Boot's dependency management manageable by limiting what we include. Generally speaking, we limit it to projects for which Spring Boot provides auto-configuration. We also extend this on a case-by-case basis for project's that you can use without any additional configuration. Spring Data JPA's QueryDSL support is an example of this. Looking at the docs for using the test harness with Spring Data Neo4j, it doesn't seem to meet either of these criteria.

I think we should roll this request into https://github.com/spring-projects/spring-boot/issues/27151. If we reduce the amount of configuration that it takes to use `org.neo4j.harness.Neo4j`, we would then have a dependency on the test harness and it would make sense for Boot to start managing its version.
