### ISSUE TITLE
Deprecate SpringPhysicalNamingStrategy in favor of Hibernate 5.5's CamelCaseToUnderscoresNamingStrategy

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#27352]
When https://github.com/hibernate/hibernate-orm/pull/4098 is merged and released we should consider dropping `SpringPhysicalNamingStrategy` and using `CamelCaseToUnderscoresNamingStrategy` instead.

**Comment by wilkinsona** [comment]
It's part of today's Hibernate 5.5.4 release.
