### ISSUE TITLE
spring.webflux.base-path did not work in spring boot 2.5.2

### ISSUE THREAD

**Issue by ft20082** [spring-projects/spring-boot#27363]
spring boot version: 2.5.2
java version: jdk 11

maven : only webflux
```
<dependency> 
      <groupId>org.springframework.boot</groupId> 
      <artifactId>spring-boot-starter-data-redis-reactive</artifactId> 
  </dependency>  
  <dependency> 
      <groupId>org.springframework.boot</groupId> 
      <artifactId>spring-boot-starter-webflux</artifactId> 
  </dependency> 
```

application.yml: 
```
spring:
    webflux:
        base-path: "/test"
```

controller: 
```
@RestController
@RequestMapping("/user")
public class UserController {

    @PostMapping("/login")
    public Mono<User> putUser() {
        return Mono.just(new User());
    }
}
```

entry:
```
@SpringBootApplication
@EnableWebFlux
@EnableScheduling
public class TestApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }

}
```

test: 
curl ip:port/test/user/login does not work,  404 error
curl ip:port/user/login works

What do I have to do to make it work? need any annotation ?

thanks

**Comment by wilkinsona** [comment]
`@EnableWebFlux` [completely disables auto-configuration of WebFlux](https://docs.spring.io/spring-boot/docs/2.5.2/reference/htmlsingle/#features.developing-web-applications.spring-webflux.auto-configuration). This means that the `spring.webflux.*` no longer have any effect. You should remove the annotation.
