### ISSUE TITLE
Provide compression feature

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2739]
Spring Boot 1.2.2 provided GzipFilter but It is [deprecated]. It seems that compression is low level operation and can be implemented more efficient low level. Jetty seems to advise GzipHandler instead of Filter. 

There is an active discussion in Spring Framework regarding [compression in DispatcherServlet].  I am also considering this to be implemented low level and providing support by Spring Boot will be a nice asset.

ping @bclozel 

[deprecated]: https://github.com/eclipse/jetty.project/blob/master/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/GzipFilter.java

[compression in DispatcherServlet]: https://jira.spring.io/browse/SPR-11714

**Comment by bclozel** [comment]
FYI, I'm closing [SPR-11714](https://jira.spring.io/browse/SPR-11714) and I won't implement that feature - containers support is a far better choice here.

**Comment by wilkinsona** [comment]
The deprecation of `GzipFilter` is only in the yet-to-be-released Jetty 9.3. There's no firm date for 9.3 so it's unclear whether or not this will affect Boot 1.3.

**Comment by wilkinsona** [comment]
This has been addressed in 1.3 by https://github.com/spring-projects/spring-boot/commit/00d594dcda6edbd7086b888e60bd0aa6562ad2e7 (#3296)

**Comment by cemo** [comment]
@wilkinsona can you set milestone for this issue as well?

**Comment by snicoll** [comment]
It's a duplicate and we don't add a milestone on duplicate.
