### ISSUE TITLE
CorsRegistry does not wrk with OncePerRequestFilter

### ISSUE THREAD

**Issue by ShaimaaSabry** [spring-projects/spring-boot#27393]
I am using spring boot 2.4.8.
I am trying to allow CORS using this code:
```
@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**");
    }
}
```
The ```WebMvcConfigurer``` gets called; however, the mapping does not get applied because I have a ```OncePerRequestFilter``` in the project.
```
@Component
public class JwtAuthorizationFilter extends OncePerRequestFilter {

    @Override
    protected void doFilterInternal(final HttpServletRequest request,
                                    final HttpServletResponse response,
                                    final FilterChain filterChain) throws ServletException, IOException {
        String authorizationHeader = request.getHeader("Authorization");
        if (authorizationHeader == null || !authorizationHeader.equals("Bearer testaccesstoken")) {
            response.setStatus(401);
            return;
        }

        filterChain.doFilter(request, response);
    }
}
```
If I remove the filter, the CORS works just fine. I attached a sample app reproducing the issue.
[demo.zip](https://github.com/spring-projects/spring-boot/files/6840459/demo.zip)

**Comment by wilkinsona** [comment]
@ShaimaaSabry Thanks for the sample. Unfortunately, it's not clear to me how it should be used to reproduce the problem. There's no test that reproduces a failure and I couldn't find any instructions describing some manual steps either. Can you please either add a test or describe the steps to take to reproduce the problem?

**Comment by ShaimaaSabry** [comment]
@wilkinsona I am using an Angular app that access this spring boot api app. I am getting this error in my Angular app:
```
Access to XMLHttpRequest at 'http://localhost:8080/authors' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Using ```@EnableWebMvc``` was the solution I found in order to allow cross origin request. If it's not recommended to use it in a spring boot application, can you please advice on what I should use instead to allow cross origin requests?

**Comment by wilkinsona** [comment]
Thanks, but there's no controller in your app that handles `/authors` so, unfortunately, I'm no closer to understanding the problem that you're reporting. If you would like us to spend some more time investigating, please spend some time providing a complete sample that reproduces the problem.

> can you please advice on what I should use instead to allow cross origin requests?

As [described in the documentation](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-cors), a `WebMvcConfigurer` bean without `@EnableWebMvc` should be sufficient.

**Comment by ShaimaaSabry** [comment]
@wilkinsona Your suggestion worked and solved my problem. Thank you.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
