### ISSUE TITLE
http2 request hang with tomcat 9.0.50

### ISSUE THREAD

**Issue by dpy1123** [spring-projects/spring-boot#27433]
We are using Spring boot 2.1.6 for now, and manuly upgrade embed tomcat to 9.0.50.
And face some issue in http2 environment, I think it`s likely to be a tomcat issue, I reported [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=65460).
And I open this issue just to inform and see if someone can help address that.

**Comment by wilkinsona** [comment]
Thanks for letting us know but there's no need to duplicate a Tomcat issue here. We'll upgrade to any new Tomcat 9.0.x release in due course.
