### ISSUE TITLE
Strip fat dependencies

### ISSUE THREAD

**Issue by mwisnicki** [spring-projects/spring-boot#2748]
When a fat jar project depends on another fat jar, `spring-boot-maven-plugin` will include it as-is, with all embedded dependencies. Instead, it should strip all embedded jars.

**Comment by snicoll** [comment]
A spring boot application relying on another spring boot application I guess? It's more complicated than it may look like. Copying blindly jars from a location means you're completely by-passing the dependency management. What if the fat jar includes a dependency on lib "foo" version 1.0 and you use "foo" version 2.0? 

If we're talking about a spring boot app, you should deploy both the application and the "regular" jar file (there is a `classifier` property for that purpose) and you should rely on the regular jar  file instead.

**Comment by mwisnicki** [comment]
Um... maybe I'm missing something but I have simple spring boot apps inheriting from starter and `mvn install` installs only fat jars with no qualifier and they are then used during packaging of other projects.

I'm not proposing to bypass dependency management, quite the opposite in fact. Required project still has a pom listing it's dependencies and normal dependency resolution takes care of them.

Say I have app1 (fat jar) that depends on libfoo and app2 that depends on app1.
Currently app2.jar will have inside it:
- app2.jar
  - lib/foo.jar (via app1 dependency)
  - lib/app1.jar
    - lib/app1.jar/lib/foo.jar

the second, doubly nested jar is not even used. I want it stripped during creation of app2.jar

**Comment by spencergibb** [comment]
Why depend on a fat jar?  If I recall you can create a fat jar and a non-fat jar.  Have `app2` depend on the non-fat jar.

**Comment by mwisnicki** [comment]
Only fat jar is created by default as far as I can see and I don't know how to change it.

**Comment by mwisnicki** [comment]
Ok, it seems quite simple,

```xml
<configuration>
  <classifier>exec</classifier>
</configuration>
```

**Comment by snicoll** [comment]
That's basically what I described in my initial comment, yes. You shouldn't rely on the fat jar.

**Comment by mwisnicki** [comment]
Great, it does exactly as I need it. Thanks!
Still I think that excluding doubly embedded jars makes sense even though it's not needed but feel free to close this issue.
