### ISSUE TITLE
Let springboot support plug-in development and dynamically expand application capabilities

### ISSUE THREAD

**Issue by UIdoer** [spring-projects/spring-boot#27481]
I want an extended function, like pf4j. I want it to help me read a jar from the disk and dynamically load it into the container. Springboot can install, uninstall, enable and disable it, and even dynamically add jars in a specific directory to expand the function of my app. This will be of great help to small and medium-sized enterprises.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, a plugin system (particularly a dynamic one) is outwith the scope of Spring Boot. You've mentioned pf4j. You may be interested in its Spring support and [using it with Spring Boot](https://ralemy.github.io/pf4j-spring-tutorial/spring-plugin-container/). You may also want to take a look at the [Spring Plugin](https://github.com/spring-projects/spring-plugin) project.
