### ISSUE TITLE
Default configurations for @ConfigurationProperties and `merge=true` added with lower priority

### ISSUE THREAD

**Issue by logogin** [spring-projects/spring-boot#2750]
When using `@ConfigurationProperties` with locations and `merge=true`, default configuration sources added with lowest priority.
May be that is by design, but then there is no way to override properties from those locations according to [Externalized Configuration](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config), i.e. command line.
[ConfigurationPropertiesBindingPostProcessor.loadPropertySources](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessor.java#L333)
line 348:
```java
if (mergeDefaultSources) {
    for (PropertySource<?> propertySource : this.propertySources) {
        loaded.addLast(propertySource);
    }
}
```

**Comment by philwebb** [comment]
I believe that this is by design, @dsyer will probably know for sure. What is it that you are actually trying to achieve?

**Comment by wilkinsona** [comment]
See #1301 for the motivation for adding merging. Something has to take precedence and my intent was to allow custom locations to override properties configured in the default locations. Perhaps we could be more subtle when merging and insert the defaults in the appropriate places?

**Comment by logogin** [comment]
I understand the purpose of merging - it is a very useful feature. But my question was regarding next case:
application.yml
```yaml
---
spring.profiles: prod
external-property: prod_value
```
external.yml
```yaml
external-property: default_value
```
ExternalConfig.java
```java
@ConfigurationProperties(locations = "external.yml", merge=true)
class ExternalConfig {
  private String externalProperty; // expected to be prod_value for prod profile
}
```
And even more required possibility to override the value with command line `--external-value=cmd_value`.
I think right now it is not possible with default property sources added with lower priority.

**Comment by logogin** [comment]
Regarding the position, my understanding of `@ConfigurationProperties` is that it is very similar to a standard `@PropertySource` with enhanced support by spring-boot. Then according to the [Externalized Configuration](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config) it should reside somewhere close to the
*10. `@PropertySource` annotations on your `@Configuration classes`.*

**Comment by dsyer** [comment]
I think we got this wrong. If we allow merging it should be the other way round (i.e. default property sources override the ones in the specific locations). Overriding with System properties seems like a useful option that is impossible to achieve as things stand.

**Comment by wilkinsona** [comment]
Both `merge` and `locations` have been deprecated in 1.4 and will be removed in 2.0
