### ISSUE TITLE
Enhancement: a la cart rest template client metrics

### ISSUE THREAD

**Issue by AndreasChristianson** [spring-projects/spring-boot#27514]
## What we'd like to do

We'd like to reuse the excellent [rest template metrics interceptor](https://github.com/spring-projects/spring-boot/blob/1bca2bbc859b0a40b6b5616c0b6433e6047c36ca/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/client/MetricsClientHttpRequestInterceptor.java) built into spring boot from our existing spring application. Upgrading the application to spring boot backlogged, but currently out of scope. 

## Problems encountered

Pulling in spring-boot-actuator without spring-boot (see below) fails as spring-boot-actuator depends on classes form spring-boot-web.

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-actuator</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

## Workaround

We [vendored](https://gist.github.com/datagrok/8577287) in some files from the actuate/metrics/web/client directory. Keeping them up to date is a maintenance headache. We hope to be converted to spring boot soon.

## Suggestion

Move the metrics stuff to a common lib or spring boot core instead of having it in boot native.

**Comment by snicoll** [comment]
Thanks for the proposal but we have no intention of moving such feature outside of Spring Boot. In the meantime, I suggest keeping your copy until your move to Spring Boot proper.
