### ISSUE TITLE
Question: How to create a @Conditional on auto configuration class that is only valid on test scope

### ISSUE THREAD

**Issue by michelzanini** [spring-projects/spring-boot#2752]
Hi,

I want to create a auto-configuration class that is only activated on tests:

```java
@Configuration
@ConditionalOnClass({Mongo.class, SpringJUnit4ClassRunner.class})
@AutoConfigureBefore({MongoAutoConfiguration.class})
public class EmbeddedMongoAutoConfiguration {
//configure an embedded mongo in memory
}
```

How do you advise to add that as conditional? 
At the moment I am using @ConditionalOnClass({SpringJUnit4ClassRunner.class}) but I think it would be better to either check for a *profile = "test"*. 
Or even better if there was an annotation like @ConditionalOnTestEnvironment?

Thanks.

**Comment by philwebb** [comment]
If you want to test for a profile you can use the `@Profile` annotation from Spring Framework itself. Alternatively, if you want to write your own `@ConditionalOnTestEnvironment` annotation you can meta-annotate it with `@Conditional` and provide a `Condition` class. For example:

```java
@Target({ ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnTestEnvironmentCondition.class)
public @interface ConditionalOnTestEnvironment {
}
```

```java
class OnTestEnvironmentCondition extends SpringBootCondition {

	@Override
	public ConditionOutcome getMatchOutcome(ConditionContext context,
			AnnotatedTypeMetadata metadata) {
		// your logic here, for example 
		if (context.getEnvironment().acceptsProfiles("test")) {
			return ConditionOutcome.match("in test");
		}
		return ConditionOutcome.noMatch("not in test");
	}

}
```
