### ISSUE TITLE
why you use cheap technologies in spring core like servlet, jsr and so on why you dont present new webserver java 8 or later with new design in serving 

### ISSUE THREAD

**Issue by loveyandex** [spring-projects/spring-boot#27529]
why you use cheap technologies in spring core like servlet, jsr and so on why you dont present new webserver java 8 or later with new design in serving

i can not understand why powerful spriong's developer use traditional web technologies  like java ee
why u can not update yourself with new design 
all java developer hate java ee ....

**Comment by loveyandex** [comment]
@scottfrederick scott you are not more celever

**Comment by scottfrederick** [comment]
This issue has been closed and locked because its language and tone violates the project [code of conduct](https://github.com/spring-projects/spring-boot/blob/main/CODE_OF_CONDUCT.adoc).
