### ISSUE TITLE
Add support for compile-time DI

### ISSUE THREAD

**Issue by voduku** [spring-projects/spring-boot#27551]
As you may know, compile time DI is a lot faster than runtime DI which spring DI is. I am wondering if we can add support for compile time DI for spring boot since spring boot come with a great support for many things. It is relatively heavy and slower than other DI like Dagger 2. I believe if spring DI can be convert or support compile time DI, it would be a game changer.

**Comment by denon82** [comment]
You can achieve It with graalvm.

**Comment by voduku** [comment]
I have been following spring natives project but I didn't hear anything about DI. I must have missed it or didn't fully understand graalvm.

**Comment by bclozel** [comment]
Thanks for reaching out, but there's nothing we can do at this time in Spring Boot.
We're indeed experimenting with build-time approaches in [Spring Native](https://github.com/spring-projects-experimental/spring-native/), and some of it might make it to Spring Framework and Spring Boot depending on the results.

Now DI is just a tiny part of what's being done at startup time - developers sometimes blame classpath scanning (or some other feature) for startup times, but it's often more complex than that. If you've experienced slow startup times, feel free to use [our application startup tracking feature](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-tracking) and report back with a JSON timeline for your application.

I'm closing this issue for now, but this doesn't mean this won't be addressed in some form in the future.
