### ISSUE TITLE
spring boot maven plugin is not using properties define in pom

### ISSUE THREAD

**Issue by ouaibsky** [spring-projects/spring-boot#2756]
**Requirement** 
Leverage on maven profile in order to activate some spring profile

Let's take an exmaple with **spring.config.name** but could be whatever.

The issue
* We are using spring-boot and are not using default configuration filename (aaa.properties in place of application.properties). Adding this property on command line (-Dspring.config.name=aaa.properties) is working but not user friendly and **become quite complex when you have many properties**

* Based on some maven profile, it could be fine to use pom properties to define some spring boot properties (specially for unit testing or integration tests).
```
            <properties>
                <spring.config.name>aaa.properties</spring.config.name>
                <spring.profiles.active>dev</spring.profiles.active>
                <!-- ..... -->
            </properties>
```

Does it make sens ?

Thx 
Christophe

**Comment by snicoll** [comment]
what about it? Just set the property in the plugin configuration with the maven property. Unless I misunderstood the problem....

Something like

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<jvmArguments>-Dspring.config.name=${spring.config.name}</jvmArguments>
	</configuration>
</plugin>
```

**Comment by ouaibsky** [comment]
Thank you !

I was not thinking to this solution.
Need to do same trick for surefire and failsafe and it works good.

Christophe
