### ISSUE TITLE
Escape character entities in strings when serializing to JSON

### ISSUE THREAD

**Issue by nikos** [spring-projects/spring-boot#2758]
For easier interoperability with web clients (suppose you want to display JSON values as part of a dashboard graph) it would be great if the serialization to JSON would escape the five standard XML character entities (" '  & <  > see  https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML).

Might be possible to use a custom CharacterEscapes implementation injected into Jackson's JsonFactory?

**Comment by philwebb** [comment]
I'm not sure that escaping XML characters is something that we should be doing when generating a JSON response. It feels like the web dashboard should be responsible for escaping characters when it renders.

Perhaps I'm missing some context here.
