### ISSUE TITLE
Add dependencyManagement for jackson-dataformat-csv

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2760]
I'm using the Jackson `CsvMapper` to load some initialization data, and I see that the JSON and XML mappers are set to `{jackson.version}` in the Spring Boot dependencies, but CSV isn't. Would it be suitable to add the dependency there?

**Comment by philwebb** [comment]
A question for @wilkinsona I think. I'm not sure how many of the Jackson modules we should provide dependencies for.

**Comment by wilkinsona** [comment]
Any of the modules described [here](https://github.com/FasterXML/jackson#data-format-modules) as "fully usable and supported" are fair game, imo.
