### ISSUE TITLE
ConfigurationProperties could use validation properties like @DateTimeFormat to change conversion strategy

### ISSUE THREAD

**Issue by mwisnicki** [spring-projects/spring-boot#2761]
it would be nice if I could use `@Value("${foo}")` to inject dates from `application.properties` or system properties without any additional configuration.

**Comment by mwisnicki** [comment]
Also for @ConfigurationProperties.

And provide (or document, if this is already possible) a way to customize it.

**Comment by mwisnicki** [comment]
BTW. I've tried `@DateTimeFormat(iso =  DateTimeFormat.ISO.DATE)` and it didn't work

**Comment by mwisnicki** [comment]
Here is complete example:

```java
@ConfigurationProperties(prefix = "my")
public class MySettings {
    @DateTimeFormat(iso =  DateTimeFormat.ISO.DATE)
    public Date when;

    // setter is needed because of #1254
    @DateTimeFormat(iso =  DateTimeFormat.ISO.DATE)
    public void setWhen(Date when) { this.when = when; }
}
```

**Comment by philwebb** [comment]
I've done a little testing and I think replacing the `conversionService` used in `ConfigurationPropertiesBindingPostProcessor` should be enough to solve the `@ConfigurationProperties` use case. I'm a little worried about side effects so I think we should treat this as an enhancement and target for 1.3.

**Comment by snicoll** [comment]
In the meantime, you could register your own `ConversionService` has a bean with name `conversionService` and we'll use that instead.

**Comment by mbhave** [comment]
@philwebb does [this](https://github.com/spring-projects/spring-boot/blob/53e5d67cdeb628d82b297173bc17b08860174540/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/JavaBeanBinderTests.java#L454-L454) take care of this?

**Comment by philwebb** [comment]
I think so, thanks @mbhave. Looks like we've got this covered as of Boot 2.0 M1
