### ISSUE TITLE
Add support for takari lifecycle plugin

### ISSUE THREAD

**Issue by mariuszs** [spring-projects/spring-boot#2762]
Please add support for takari lifecycle plugin, the main artifact has ID: `taraki-jar`

http://takari.io/book/40-lifecycle.html

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage (default) on project devskiller-git: 
Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage failed: 
For artifact {sample:sample:0.0.1-SNAPSHOT:takari-jar}: 
An attached artifact must have a different ID than its corresponding main artifact. -> [Help 1]
```

**Comment by drzewo** [comment]
It has already been investigated by Igor Fedorenko: https://github.com/takari/takari-lifecycle/issues/10

**Comment by philwebb** [comment]
The relevant comment in that thread is https://github.com/takari/takari-lifecycle/issues/10#issuecomment-73431419

**Comment by snicoll** [comment]
Yeah, that call to `getPackaging` was optimistic indeed. Let's backport that to 1.2.x as well.
