### ISSUE TITLE
Upgrade to Tomcat 9.0.52

### ISSUE THREAD

**Issue by Clotonervo** [spring-projects/spring-boot#27658]
There are some performance fixes in Tomcat 9.0.52 from version 9.0.50. I haven't seen an issue raised with this dependency, and if I am incorrect in posting this issue I apologize. Thanks!

**Comment by Clotonervo** [comment]
Preferably for version 2.5.4 if that is possible. I would be willing to help and do the commit/testing myself it that would help!

**Comment by snicoll** [comment]
@Clotonervo the issue template on this issue tracker namely states:

> - Managed Dependency Upgrade
You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release. BUT pull requests for upgrades that are more involved than just a version property change are still most welcome.

We will upgrade, as usual, in due course.
