### ISSUE TITLE
I can't  read external yml file

### ISSUE THREAD

**Issue by jorgefilho** [spring-projects/spring-boot#2765]
In my spring-boot project i put the yaml file in an external directory. I tried to define the 'spring.config.location=file:/opt/nsi/task-manager/config/yaml/'and 'spring.config.name=settings.yml' in the application.properties to identified the file but the project didn't find it.

**Comment by snicoll** [comment]
These settings are meant to define which configuration file should be loaded. When you define them, you deviate from the defaults (`application.properties`). They should be set on the command-line or as system properties as defined in the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files)

**Comment by jorgefilho** [comment]
where I find in the documentation about external yaml file ? Is there the possibility that I expose it ?
![23 nbsp externalized configuration](https://cloud.githubusercontent.com/assets/2074571/6969202/032cde80-d943-11e4-8dea-968ad3b38532.png)
