### ISSUE TITLE
@WebIntegrationTest doesn't call RequestContextHolder.setRequestAttributes()

### ISSUE THREAD

**Issue by aheusingfeld** [spring-projects/spring-boot#2766]
I currently have a scenario where I use Spring Boot 1.2.2 with Spring HATEOAS 0.17 and want to run integration tests. I annotated my test class with `@WebIntegrationTest` but unfortunately one of the tests fails when `ControllerLinkBuilder.getCurrentRequest()` calls `RequestContextHolder.getRequestAttributes()` because it returns `null`. The point is that this specific test does not call `MockMvc.perform()` - which would trigger a call to `RequestContextHolder.setRequestAttributes(RequestAttributes, boolean)` - but just tests a utility method on the controller that uses `ControllerLinkBuilder.linkTo()`.

I tried some modifications i.e. I switched from `@WebIntegrationTest` to `@IntegrationTest` and `@WebAppConfiguration`. I noticed that when I use `@WebIntegrationTest` the `ServletTestExecutionListener.setUpRequestContextIfNecessary()` is not executed correctly as it checks whether the test class is annotated with `@WebAppConfiguration`. 

In the end I found two options to get my test working
1. I run `MockMvc.perform(get("/"))` as the first thing in the test... #urgs
2. I call `RequestContextHolder.setRequestAttributes(servletWebRequest)` in my tests `@Before` method 

I don't think that either is the right way to do it, so suggestions are very welcome.

IMHO this is related to #2299. :)

**Comment by philwebb** [comment]
Are you able to share the test in question?

**Comment by aheusingfeld** [comment]
Sorry, I couldn't find the time to setup a test project. So basically what I did is take @olivergierke's approach with `AbstractWebIntegrationTest` (see https://github.com/olivergierke/spring-restbucks/blob/master/src/test/java/org/springsource/restbucks/AbstractWebIntegrationTest.java) which has the `@WebIntegrationTest` annotation for all my test classes. But whenever I had a test which didn't make use of MockMvc but touched code that used `ControllerLinkBuilder`, the test failed. I tried to highlight the reason above:
`ServletTestExecutionListener.setUpRequestContextIfNecessary()` does only check for `@WebAppConfiguration` but not for `@WebIntegrationTest`

I didn't notice this in my tests before as I always used MockMvc. `MockMvc.perform()` automatically calls/ initializes `RequestContextHolder.setRequestAttributes(RequestAttributes, boolean)`. But to me this knowledge is buried a bit too deep. I guess that's why @gregturn opened https://github.com/spring-projects/spring-hateoas/issues/342

At the moment I'm nevertheless using a workaround in my `AbstractWebIntegrationTest.setUp()` method:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = DemoApplication.class)
@WebIntegrationTest
@ActiveProfiles("test")
public abstract class AbstractWebIntegrationTest {
	private @Autowired FilterChainProxy filterChain;
	protected @Autowired WebApplicationContext context;

	@Before
	public void setUp() {

		mvc = MockMvcBuilders.webAppContextSetup(context). //
				addFilter(new ShallowEtagHeaderFilter()). //
				addFilter(filterChain).
//                apply(new RestDocumentationConfigurer()).
//                alwaysDo(document("{method-name}/{step}/")).
				build();
		if (RequestContextHolder.getRequestAttributes() == null) {
			MockHttpServletRequest request = new MockHttpServletRequest(context.getServletContext());
			MockHttpServletResponse response = new MockHttpServletResponse();
			ServletWebRequest servletWebRequest = new ServletWebRequest(request, response);

			RequestContextHolder.setRequestAttributes(servletWebRequest);
		}
	}
//...
```

**Comment by wilkinsona** [comment]
@aheusingfeld Thanks for the explanation. I'm a bit confused about why you're using `@WebIntegrationTest` at all. If you're either making `MockMvc` calls, or testing a controller's utility methods, do you really need to start up the embedded container? Put another way, why not just annotate your class with `@WebAppConfiguration` and avoid the use of `@IntegrationTest` and `@WebIntegrationTest` altogether.

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
