### ISSUE TITLE
partial endpoint enabled whereas global is disabled

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#2767]
Hi,

I noticed in Spring-boot 1.2.2.RELEASE that when you disable an endpoint you can access to a specific information.

Here is my application.yml file : 

<pre>
# ENDPOINTS
endpoints:
 enabled: false # disabled by default
/pre>

If I try to access /admin/env I got the following message : 

<pre><code>
&lt;SingletonMap&gt;
&lt;message&gt;This endpoint is disabled&lt;/message&gt;
&lt;/SingletonMap&gt;
</code></pre>

However I can access /admin/env/management.port infos

**Comment by wilkinsona** [comment]
This is somewhat similar to #2476

**Comment by wilkinsona** [comment]
The `/metrics` endpoint has the same problem

**Comment by wilkinsona** [comment]
Reopening to consider how to reinstate the support for relaxed binding

**Comment by philwebb** [comment]
You might get away with a custom condition just to deal with `endpoints.enabled`. You could then use that in combination with the previous `@ConditionalOnProperty` conditions. One other thing to note is that SpEL is a lot slower to execute that the property tests.
