### ISSUE TITLE
Spring Boot 2.2 Release Notes missing from Wiki

### ISSUE THREAD

**Issue by mackatozis** [spring-projects/spring-boot#27692]
Currently, the release notes for Spring Boot 2.2 are missing from the Wiki page. Please include it at least in the **[Spring Boot Older Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Older-Release-Notes)** page.

Thank you

**Comment by snicoll** [comment]
Thanks for the report. It wasn't removed, only the link was. I've added one in the older release notes page.
