### ISSUE TITLE
HiddenHttpMethodFilter should be ordered before FilterChainProxy

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#2773]
In order for HTTP authorization rules to be accurate (which can be based on HTTP methods), Spring Security needs to be after `HiddenHttpMethodFilter`.

**Comment by philwebb** [comment]
@rwinch I've added a fix for this but I'm unsure how to test it. It doesn't appear to have any side-effects so I went ahead and merged it.

If you have time, perhaps you could double check that it fixes things.

**Comment by rwinch** [comment]
@philwebb Sorry for the delay. The test is to ensure that when a request uses HiddenHttpMethodFilter to change the HTTP method that Spring Security's matching matches on the overridden method vs the original method. For example, a request like:

```http
POST /path HTTP/1.1
Content-Type: application/x-www-form-urlencoded

_method=PUT
```

would then be intercepted with the Security configuration of

```java
http
   .antMatchers(PUT, "/**").authenticated()
```

**Comment by philwebb** [comment]
@rwinch thanks!
