### ISSUE TITLE
Enhance operability of spring-boot-maven-plugin with maven_opts maven.config

### ISSUE THREAD

**Issue by danielkwinsor** [spring-projects/spring-boot#27760]
As a spring-boot 2.2.0.RELEASE and above user, I want the spring-boot-maven-plugin to read the properties that I define in https://maven.apache.org/configure.html in the same way they used to be in 2.1.7.RELEASE, so that I can leverage supplying custom test properties when running locally.

Example file~property that I always found handy was -Dserver.port=8888
If you have an alternative way to get that property into an execution of `mvn spring-boot:run`, but doesn't require typing out anything like `SERVER_PORT=8888 mvn spring-boot:run`, then I'd be happy to hear.

**Comment by philwebb** [comment]
You can create a `.mvn/maven.config` file with the following content to change the port:

```
-Dspring-boot.run.arguments="--server.port=8888"
```
