### ISSUE TITLE
IllegalStateException and odd timeout behaviour when RedisHealthIndicator fails

### ISSUE THREAD

**Issue by jleskovar** [spring-projects/spring-boot#2777]
Hi all,

Just noticed some odd behaviour when my Redis instance is down and I try to hit any of the actuator endpoints. First up, I'm using the `spring-boot` `1.2.3.RELEASE` parent pom to configure my dependencies. I've got a simple application that pulls in actuator, redis, and web. When Redis is up and running, everything works smoothly - I can access `/configprops`, `/health`, `/metrics` all fine and snappy. When I bring Redis down though, all of these endpoints take at first 4 seconds to partially respond - i.e. I can see the json response, but Chrome still displays the spinning wheel like it's still loading -, and then another 4 seconds for the HTTP request to finish. When it does finally finish, I end up seeing `IllegalStateException: getOutputStream() has already been called for this response` thrown from [ErrorMvcAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/3048f44a964ab2390dff26f0818c941ba40bdc56/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration.java#L196)

Is this expected behaviour? Can it be changed? 

Cheers
James

**Comment by philwebb** [comment]
Are you able to provide a [sample application](https://github.com/spring-projects/spring-boot-issues) that demonstrates the issue?

**Comment by jleskovar** [comment]
Sure thing. I have an application ready to push into spring-boot-issues, but I get 403 when I try to push. Do I need special permissions? I also neglected to mention the following, which may be pertinent...:
1. I'm wiring in a RedisMetricRepository as a data store for metrics. I believe this may be related, as there are no issues when using the default in-memory repository.
2. I'm also running redis in a local docker container. For my test, I `docker pause`d the container, which results in the port still being listened on, and the socket read timeouts to occur. If I `docker kill` instead, I get back a 500 "JedisConnectionException: Could not get a resource from the pool" immediately from the server, with no delays.

**Comment by philwebb** [comment]
You need to fork the `spring-boot-issues` repository then push to that and submit a pull-request. Some help is available here https://help.github.com/articles/using-pull-requests/.

**Comment by jleskovar** [comment]
[Done.](https://github.com/spring-projects/spring-boot-issues/pull/34)

**Comment by philwebb** [comment]
The `MetricsFilter` tries to record metrics for all pages, including the actuator pages. I'm not sure that there is much we can do about the timeouts since we just rely on the Redis driver to write results. I have however updated the filter so that failures don't cascade and create the `IllegalStateException: getOutputStream() has already been called for this response` error.

@dsyer could we do anything else to improve Redis failures?

**Comment by dsyer** [comment]
You shouldn't really use a redis repository as the primary metric writer. It's far better to buffer in memory and write periodically to redis on a `@Scheduled` method. Spring Boot 1.3 makes it much easier to do it right, but all the pieces are available in 1.2 already.
