### ISSUE TITLE
use nginx as webserver

### ISSUE THREAD

**Issue by dragon-zhang** [spring-projects/spring-boot#27783]
EN:
Recently, my company is using springboot as a gateway and has encountered performance problems. Here I propose an idea: can an `org.springframework.boot.web.server.webserver` and `org.springframework.boot.web.reactive.server.configurablereactivewebserverfactory` be implemented to adapt nginx? In the scenario of request forwarding, this can greatly improve performance.

CN:
我的公司最近在用SpringBoot做网关，遇到了性能问题，在此我提出一个设想：能否实现一个org.springframework.boot.web.server.WebServer和org.springframework.boot.web.reactive.server.ConfigurableReactiveWebServerFactory来适配适配nginx？在请求转发的场景，这能极大地提升性能。

**Comment by wilkinsona** [comment]
You can use Nginx as a proxy in front of a Spring Boot application. There is some information about [running a Spring Boot application behind a proxy server](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#howto-use-behind-a-proxy-server) in the reference documentation. An Nginx-based `WebServer` implementation is not possible as the web server in this case has to run embedded in the JVM and Nginx is not a JVM-based server.

If you're interested in a high-performance Java-based gateway, you may want to look at [Spring Cloud Gateway](https://spring.io/projects/spring-cloud-gateway) if you have not already done so. It is built on top of Spring WebFlux and Reactor Netty.

**Comment by dragon-zhang** [comment]
Well, thanks.






------------------ Original ------------------
From: Andy Wilkinson ***@***.***&gt;
Date: Fri,Aug 20,2021 5:59 PM
To: spring-projects/spring-boot ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [spring-projects/spring-boot] use nginx as webserver (#27783)





 
You can use Nginx as a proxy in front of a Spring Boot application. There is some information about running a Spring Boot application behind a proxy server in the reference documentation. An Nginx-based WebServer implementation is not possible as the web server in this case has to run embedded in the JVM and Nginx is not a JVM-based server.
 
If you're interested in a high-performance Java-based gateway, you may want to look at Spring Cloud Gateway if you have not already done so. It is built on top of Spring WebFlux and Reactor Netty.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
