### ISSUE TITLE
spring-boot application get warning: CONSOLE_LOG_PATTERN_IS_UNDEFINED

### ISSUE THREAD

**Issue by mluis7** [spring-projects/spring-boot#27796]
[Already reported and closed](https://github.com/spring-projects/spring-boot/issues/12925) but I was able to reproduce it using `logback.xml` sample from [`2.1.8.RELEASE` documentation page, section `83.1`](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/howto-logging.html) :-p

spring-boot version: 2.5.1

**Steps to reproduce:**

* Copy the sample `logback.xml` configuration from [`2.1.8.RELEASE` documentation page, section `83.1`](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/howto-logging.html)
* Start your application

**Logs will show:**

> 
> 20:26:45,329 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@6646153 - Failed to set property [charset] to value "CONSOLE_LOG_CHARSET_IS_UNDEFINED".  ch.qos.logback.core.util.PropertySetterException: Conversion to type [class java.nio.charset.Charset] failed.
>         at ch.qos.logback.core.util.PropertySetterException: Conversion to type [class java.nio.charset.Charset] failed.
> ...
> CONSOLE_LOG_PATTERN_IS_UNDEFINEDCONSOLE_LOG_PATTERN_IS_UNDEFINEDCONSOLE_<REDACTED>

**Cause**: 
The `include` string is missing the `s` in `default.xml`
`<include resource="org/springframework/boot/logging/logback/default.xml"/>`

**Notes**:
* The second example on section `83.1.1` is correct.
* The mentioned page is the second result in this google search `spring boot console appender`

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/pull/18295.
