### ISSUE TITLE
Polish SessionAutoConfiguration#addCandidateIfAvailable

### ISSUE THREAD

**Issue by weixsun** [spring-projects/spring-boot#27802]
https://github.com/spring-projects/spring-boot/blob/f386ebe61df37f8b1c3077f273905421bec0de5b/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/SessionAutoConfiguration.java#L241-L246

As far as i know, Condition `candidate != null` is always `true`.

A post regarding whether or not `Class.forName can return null` [here](https://stackoverflow.com/questions/430089/in-java-can-class-forname-ever-return-null) and everyone seems to think it can't (or wont).

I'm very curious about why this judgment condition is needed here. Could it be that I have missed some points?

**Comment by philwebb** [comment]
I think it's just an oversight. That code can be simplified to `candidates.add(Class.forName...`.

**Comment by snicoll** [comment]
Closing in favor of PR #27808
