### ISSUE TITLE
Remove @Persistent from CouchbaseDataConfiguration's entity scanning to re-align with Spring Data Couchbase

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#27810]
Scanning for `@Persistent` was removed in https://github.com/spring-projects/spring-data-couchbase/commit/351370ba4d0f166a6c59c5a92bcd179bea97c688. We should update `CouchbaseDataConfiguration` to match.

**Comment by scottfrederick** [comment]
Duplicates #26074
