### ISSUE TITLE
Consider to create a common table track history control for Common Application Properties

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#27843]
I have a demo about Spring Boot for my students and I did realize about the following.

For the following application properties

```
spring.datasource.schema = schema-h2.sql
spring.datasource.data = data-h2.sql
spring.datasource.platform = h2
```

For 2.3.4.RELEASE, they are recognised and valid to be used

![Screen Shot 2021-08-31 at 11 05 30 AM](https://user-images.githubusercontent.com/2552795/131537873-dcfc6e66-867d-40c8-9dfe-daa4cd282ff8.png)

But for 2.5.4, they are _not_ recognised but still valid to be used

![Screen Shot 2021-08-31 at 11 05 39 AM](https://user-images.githubusercontent.com/2552795/131537874-58d908d4-5592-4b70-b263-6bf25b9a003f.png)

BTW group `#1` and `#2` are "exclusive" between them, but I am enable both together to show the yellow line

I have confirmed that keys appears and not appear respectively in:

* [Common Application properties](https://docs.spring.io/spring-boot/docs/2.3.4.RELEASE/reference/html/appendix-application-properties.html#common-application-properties) 2.3.4.RELEASE
* [Common Application properties](https://docs.spring.io/spring-boot/docs/2.5.4/reference/html/application-properties.html#application-properties) 2.5.4

Here came a thought, how I should know in what version that keys were _explicitly_ removed or replaced? And the reason

* You would say, see in [releases](https://github.com/spring-projects/spring-boot/releases). - But just try to search in that page with any of the 3 `spring.datasource.X` terms and does not appear a coincidence, so is not possible to know what happened. Are they were removed or replaced? and Why? 
* Same as above but in [Wiki#Release-Notes](https://github.com/spring-projects/spring-boot/wiki#release-notes)
* You would say, look at [blog](https://spring.io/blog). - But is not straightforward to do a search (even assuming that changes were informed through there)

What about add a new section documentation isolated of the rest, it located at [Spring Boot Overview](https://spring.io/projects/spring-boot#overview) - named as: `Application Properties Track History Control` - _for example:_

Property | 2.3.4 | 2.4.1 | 2.5.4
--------- | ----- | -----| ------
spring.datasource.schema | available | removed | not available
spring.datasource.data | available | removed | not available
spring.datasource.platform | available | replaced by XXX | not available
spring.datasource.something | not available | new/added | available

Therefore I am able to see quickly what happened at a first glance.

Consider the same approach for `Dependency Versions Track History Control` - for example (numbers are not exact)

Group ID | Artifact ID |  2.3.4 | 2.4.1 | 2.5.4
--------- | ---------- |  ----- | -----| ------
org.springframework | spring-aaa | 5.0.0 | 5.0.1 | 5.0.2
org.springframework | spring-bbb | 5.0.0 | 5.0.1 | 5.0.2
org.springframework | spring-zzz | not available | 5.0.1 | 5.0.2
org.something.aaa    | aaa-aaaa    | 1.1 | replaced by XXX | not available
org.something.bbb   | bbb-bbb    | 1.2 | removed | not available

So, both tables for Spring Boot series 2.x would be valuable for the community.

To conclude, how you can see, is not possible know quickly what happened with the  `spring.datasource.schema - spring.datasource.data - spring.datasource.platform` keys and in what version

Please consider it a friendly observation and suggestion 

Thanks for your understanding.

**Comment by mbhave** [comment]
@manueljordan We provide a configuration properties changelog in the release notes for every release. See [this](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Configuration-Changelog) for what changed between 2.4 and 2.5. It seems like this is sufficient to cover the information you're looking for. Our reference documentation is specific to that version only so we prefer not to add any historical documentation in there.
