### ISSUE TITLE
ConnectionInfo  missing setUserName() method

### ISSUE THREAD

**Issue by 1161853339** [spring-projects/spring-boot#27842]
Version: Springboot 2.5.4 and 2.5.3 
Class:org.springframework.boot.autoconfigure.data.redis.RedisConnectionConfiguration 
Description：

The class RedisConnectionConfiguration use setUserName() method.But ConnectionInfo missing  the method setUserName().So it can't be init when i use redis.

![image](https://user-images.githubusercontent.com/20437338/131476840-1daeb871-fcbb-42c3-bbf9-9d69cfb39130.png)

![image](https://user-images.githubusercontent.com/20437338/131476918-dccfae48-2a78-4536-8356-8ee34a8537cd.png)

**Comment by mdeinum** [comment]
The `ConnectionInfo` doesn't have a `setUsername` method because it is set through the constructor. The `RedisStandAloneConfiguration` also has one. It looks like that you are using an incompatible version of Spring Data Redis with Spring Boot (or vice-versa).

**Comment by philwebb** [comment]
I agree with @mdeinum's analysis. The `setUsername` method was introduced in [this commit](https://github.com/spring-projects/spring-data-redis/commit/d97c5df13072a5740d530253a1b0f06e16f0100a) in Spring Data Redis 2.4-RC1. You're probably using an outdated version. If possible, we recommend using Spring Boot's managed dependencies which will ensure compatibility.

**Comment by 1161853339** [comment]
Thank for reply!
