### ISSUE TITLE
Improvement: Split logging exception conversion word for file and console

### ISSUE THREAD

**Issue by netbeansuser2019** [spring-projects/spring-boot#27863]
IN CONTEXT:

https://github.com/spring-projects/spring-boot/blob/2d89a8253cf4fc23dee831256a75730fcbba68d9/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml#L12

https://github.com/spring-projects/spring-boot/blob/2d89a8253cf4fc23dee831256a75730fcbba68d9/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml#L14

Instead of using one property of "logging exception conversion word" for both appenders split that to two.

**Comment by philwebb** [comment]
I'm sorry but I don't understand the request. Could you show an example of the update you'd like?

**Comment by Mikexianglu** [comment]
I am Japanese,I think you are so stupid!!!

**Comment by snicoll** [comment]
@Mikexianglu that comment is violating our [code of conduct](https://github.com/spring-projects/spring-boot/blob/main/CODE_OF_CONDUCT.adoc), review it before contributing again.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
