### ISSUE TITLE
Is it a bug in InvalidConfigDataPropertyException.class in 2.5.4?

### ISSUE THREAD

**Issue by LonelyPm** [spring-projects/spring-boot#27875]
When i use spring.profiles.active=xxx in properties file ,it throws a exception named InvalidConfigDataPropertyException.

`
static void throwOrWarn(Log logger, ConfigDataEnvironmentContributor contributor) {
		ConfigurationPropertySource propertySource = contributor.getConfigurationPropertySource();
		if (propertySource != null) {
			WARNINGS.forEach((name, replacement) -> {
				ConfigurationProperty property = propertySource.getConfigurationProperty(name);
				if (property != null) {
					logger.warn(getMessage(property, false, replacement, contributor.getResource()));
				}
			});
			if (contributor.isFromProfileSpecificImport()
					&& !contributor.hasConfigDataOption(ConfigData.Option.IGNORE_PROFILES)) {
				PROFILE_SPECIFIC_ERRORS.forEach((name) -> {
					ConfigurationProperty property = propertySource.getConfigurationProperty(name);
                                        **_//Is it '==' rather then '!=' ?_**
					if (property != null) { 
						throw new InvalidConfigDataPropertyException(property, true, null, contributor.getResource());
					}
				});
			}
		}
	}
`

**Comment by snicoll** [comment]
@LonelyPm it is impossible to say without showing your sample configuration. My best guess is that [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#profile-activation) of the migration guide should answer your question. If it doesn't, please follow-up on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
