### ISSUE TITLE
Spring Boot starter for Apache Flink

### ISSUE THREAD

**Issue by x80486** [spring-projects/spring-boot#27898]
Hello Spring team!

Is it possible to consider a starter for [Apache Flink](https://flink.apache.org/)? I'm not familiar on how you would go about this, or if there is a different issue tracker for such things.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Generally speaking, where there's no existing Spring support that's developed by the Spring team, we think that it's best for a starter to be developed and maintained by a third-party. That could either be the Flink project itself or a separate team. If such a starter is created, we'd then be more than happy to add it to our [list of third-party starters](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-starters#starters).
