### ISSUE TITLE
Auto-register JDK 8 Jackson module if it's on the classpath

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#2789]
There's a [Jackson module](https://github.com/FasterXML/jackson-datatype-jdk8) dedicated to JDK 8 specific types (`Optional`, new date/time types) available. We should automatically register this module, just like we auto-register the JodaTime support.

**Comment by wilkinsona** [comment]
It's Spring Framework's `Jackson2ObjectMapperBuilder` [that registers](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L666) Jackson's JodaTime and JSR310 support. I wonder if this should be handled in there too? What do you think @sdeleuze?

**Comment by olivergierke** [comment]
Sounds good to me. I just realized that the README of the module lists the stuff that's *not* included. Turns out we already have the JSR-310 one integrated so this ticket would cover `Optional`s then. I guess we could include support for the [parameter names module](https://github.com/FasterXML/jackson-module-parameter-names) here, too.

**Comment by sdeleuze** [comment]
@wilkinsona Indeed, it makes sense to register `Jdk8Module` and `ParameterNamesModule` in `Jackson2ObjectMapperBuilder` when they are on the classpath.

@olivergierke Could you create an issue (a single issue will be fine) in Spring Framework JIRA for that ?

**Comment by wilkinsona** [comment]
@sdeleuze has now added this to Spring Framework 4.2 so Boot will pick it up from there
