### ISSUE TITLE
Capture console log message in tests like OutputCaptureExtension

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#27902]
`OutputCaptureExtension` does not capture console log, It would be nice if spring boot could provide `ConsoleLogCaptureExtension` and `CapturedConsoleLog`.

**Comment by wilkinsona** [comment]
Output capture should capture everything written to `System.out` and `System.err`. We have a few tests of our own that verify that the expected logging is produced which rely on this behaviour. If this isn't working for you, please provide a minimal example of the behaviour that you're seeing, and we can take another look.

**Comment by quaff** [comment]
Here is my minimal example [example.zip](https://github.com/spring-projects/spring-boot/files/7135849/example.zip)
1. I'm using log4j2, use default logback will not cause failure.
2. I'm using both `@ExtendWith(SpringExtension.class)` and `@ExtendWith(OutputCaptureExtension.class)`, It looks like `SpringExtension` activated before `OutputCaptureExtension` causing capture failure.

**Comment by philwebb** [comment]
You need to set `follow="true"` on your console append [as we do with the default config](https://github.com/spring-projects/spring-boot/blob/bb11abef2c00d59e2b86a03f30efd530c3f4a618/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml#L11).

```xml
<Appenders>
	<Console name="CONSOLE" target="SYSTEM_OUT" follow="true">
		<PatternLayout
			pattern="%style{%d %25.25t %60.60c{1.}}{cyan} %highlight{%p %m}%n%throwable" />
	</Console>
</Appenders>
```

**Comment by quaff** [comment]
> You need to set `follow="true"` on your console append [as we do with the default config](https://github.com/spring-projects/spring-boot/blob/bb11abef2c00d59e2b86a03f30efd530c3f4a618/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml#L11).
> 
> ```
> <Appenders>
> 	<Console name="CONSOLE" target="SYSTEM_OUT" follow="true">
> 		<PatternLayout
> 			pattern="%style{%d %25.25t %60.60c{1.}}{cyan} %highlight{%p %m}%n%throwable" />
> 	</Console>
> </Appenders>
> ```

It works, thanks very much.

**Comment by emeraldhieu** [comment]
Adding follow="true" doesn't work for me in Spring Boot 3.x. I've copied the whole file https://github.com/spring-projects/spring-boot/blob/bb11abef2c00d59e2b86a03f30efd530c3f4a618/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml#L11

**Comment by wilkinsona** [comment]
@emeraldhieu Please open a new issue with a complete yet minimal example and we can take a look.
