### ISSUE TITLE
Upgrade to netty-4.1.68.Final

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects/spring-boot#27924]
Adds native support for Apple Silicon M1

https://github.com/netty/netty/pull/11666

**Comment by wilkinsona** [comment]
Thanks but, [as described in the issue template](https://github.com/spring-projects/spring-boot/blame/main/.github/ISSUE_TEMPLATE.md#L11-L12) we don't need an issue for a straightforward dependency upgrade. We'll pick up the new Netty release in due course.
