### ISSUE TITLE
ReactiveMethodSecurityConfiguration not eligible for auto-proxying

### ISSUE THREAD

**Issue by anmolgarg552** [spring-projects/spring-boot#27962]
Getting this while deployment

```
[main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization():376 {} - Bean 'org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

I faced this issue after upgrading to 2.5.1 Earlier, I was using 2.3.4.RELEASE version.

**Comment by wilkinsona** [comment]
Something has triggered eager initialization of `ReactiveMethodSecurityConfiguration`. This has resulted in it being initialized before all of the context's been post-processors which prevents if from being fully post-processed. This may or may not be a problem and we can't tell without some more information.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Marthym** [comment]
Hi,

I have the same problem when I add `spring-boot-starter-actuator` in classpath of a Webflux project. 

I use `@EnableReactiveMethodSecurity` on my security config.

```
2022-07-16 17:22:10.803  INFO 22535 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**Comment by philwebb** [comment]
@Marthym can you please provide a sample application that shows the problem.

**Comment by wilkinsona** [comment]
Thanks for the sample, @Marthym. The log message appears to be due to a bug in Spring Security. I've opened https://github.com/spring-projects/spring-security/issues/11596.
