### ISSUE TITLE
spring-boot-maven-plugin can support use timezone for  build info properties 'time'

### ISSUE THREAD

**Issue by biuabiu** [spring-projects/spring-boot#27973]

**Comment by wilkinsona** [comment]
Can you please provide some more background? Why do you want to be able to provide the timezone? The time is parsed using `Instant.parse` at the moment so the input timezone is always UTC.

**Comment by biuabiu** [comment]
> Can you please provide some more background? Why do you want to be able to provide the timezone? The time is parsed using `Instant.parse` at the moment so the input timezone is always UTC.

Thank you for your reply. You can use instan to parse the timestamp, and then you can get what I want according to the custom time zone. Then I close it
