### ISSUE TITLE
Unable to add custom manifest entries to top level MANIFEST.MF

### ISSUE THREAD

**Issue by rpomeroy** [spring-projects/spring-boot#2800]
I'm trying to make an executable war that is also deployable to JBoss.  The customer wants JBoss modules to provide the JDBC drivers.  To do this I need to add a custom manifest entry like:

```
Dependencies: <jdbc module id>, <another jdbc module id>
```
I tried adding the manifest entries using the following in my pom (placed before the spring-boot-maven-plugin)

``` xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
   <version>2.5</version>
   <inherited>true</inherited>
   <configuration>
      <archive>
        <manifestEntries>
           <Dependencies>com.oracle.jdbc optional</Dependencies>
        </manifestEntries>
     </archive>
  </configuration>
</plugin>
```
Unfortunately the manifest entries did not get written - neither at the top level or in WEB-INF/classes/META-INF/MANIFEST.MF

It currently does not seem straightforward to add custom manifest entries to the repacked **war**.  This does work for **jar** packaging

**Comment by rpomeroy** [comment]
I was going to work on a patch but by studying the integration tests for I discovered I needed to use the war plugin and place it after the spring boot maven plugin.  Not a bug.  Sorry for the noise.

**Comment by snicoll** [comment]
Let's at least document it then. Thanks!

**Comment by snicoll** [comment]
Ah, I got it all wrong. There's not much to document, actually. If you build a war, the jar plugin isn't even invoked....
