### ISSUE TITLE
spring-security 4.0.0 not compatible with spring-social 1.1.0

### ISSUE THREAD

**Issue by BigMichi1** [spring-projects/spring-boot#2802]
after the change from gh-2727 we are no longer able to use spring-boot with spring-social because of an incompatible api change in spring-security 4. 

you can have a look here what the problem is https://github.com/spring-projects/spring-social/pull/149

**Comment by wilkinsona** [comment]
Given that this only affects 1.3 snapshots, I'd prefer to live with the Spring Social limitation and provide more exposure to Spring Security 4.0. That said, we'd need a Spring Security 4.0 compatible version of Spring Social before Boot 1.3's M1 which will be released at the end of May or thereabouts.

/cc @habuma

**Comment by wilkinsona** [comment]
Fixed in 8fcc6693 which merged for Spring Social 1.1.1.RELEASE upgrade into master
