### ISSUE TITLE
Interoperability with JPA/JDBC

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-boot#28025]
Like many projects I don't want to color all of my controller routes with Flux/Flow and only have some specific legitimate use cases for R2DBC. However it is not clear at all (and it should) wether one can integrate R2DBC in an existing app and keep using JPA/JDBC for most routes and only use R2DBC where appropriate.
(our legitimate use case being a SSE stream using postgres NOTIFY/LISTEN)
If there were to be interop issues, I'd like to clarify that my use of R2DBC is read only while all writes are using the JPAs

**Comment by odrotbohm** [comment]
Moved to Spring Boot as per @mp911de's request.

**Comment by wilkinsona** [comment]
From a Spring Boot perspective, this is working as designed [and documented](https://docs.spring.io/spring-boot/docs/2.5.x/reference/htmlsingle/#features.sql.r2dbc):

> When a `ConnectionFactory` bean is available, the regular JDBC `DataSource` auto-configuration backs off. If you want to retain the JDBC `DataSource` auto-configuration, and are comfortable with the risk of using the blocking JDBC API in a reactive application, add `@Import(DataSourceAutoConfiguration.class)` on a `@Configuration` class in your application to re-enable it.

**Comment by arshiya-maersk** [comment]
**These are the changes I did to get this right.** 
**This is my R2dbc Config class ->**

@Configuration
public class R2dbcConfig {

    @Value("${spring.r2dbc.url}")
    private String url;

    @Value("${spring.r2dbc.name}")
    private String name;

    @Value("${spring.r2dbc.username}")
    private String username;

    @Value("${spring.r2dbc.password}")
    private String password;
    @Bean
    public ConnectionFactory connectionFactory() {
        return new PostgresqlConnectionFactory(
                PostgresqlConnectionConfiguration.builder()
                        .host(url)
                        .database(name)
                        .username(username)
                        .password(password)
                        .build()
        );
    }

    @Bean
    DatabaseClient databaseClient(ConnectionFactory connectionFactory) {
        return DatabaseClient.builder()
                .connectionFactory(connectionFactory)
                .namedParameters(true)
                .build();
    }
}

**Then I also define my jpa config file** 

@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(basePackages = "com.artemis.repositories")
@EntityScan("com.artemis.entities")
@Slf4j
public class JpaConfig implements EnvironmentAware {

    private static final String ENV_HIBERNATE_DIALECT = "hibernate.dialect";
    private static final String ENV_HIBERNATE_HBM2DDL_AUTO = "hibernate.hbm2ddl.auto";
    private static final String ENV_HIBERNATE_SHOW_SQL = "hibernate.show_sql";
    private static final String ENV_HIBERNATE_FORMAT_SQL = "hibernate.format_sql";
    private Environment env;

    @Bean
    public DataSource dataSource() {
        return new DriverManagerDataSource(
                env.getProperty("datasource.url"),
                env.getProperty("datasource.username"),
                env.getProperty("datasource.password")
        );
    }

    @Bean
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
        LocalContainerEntityManagerFactoryBean emf = new LocalContainerEntityManagerFactoryBean();
        emf.setDataSource(dataSource);
        emf.setPackagesToScan(ArtemisApplication.class.getPackage().getName());
        emf.setPersistenceProvider(new HibernatePersistenceProvider());
        emf.setJpaProperties(jpaProperties());
        return emf;
    }

    private Properties jpaProperties() {
        Properties extraProperties = new Properties();
        extraProperties.put(ENV_HIBERNATE_FORMAT_SQL, env.getProperty(ENV_HIBERNATE_FORMAT_SQL));
        extraProperties.put(ENV_HIBERNATE_SHOW_SQL, env.getProperty(ENV_HIBERNATE_SHOW_SQL));
        extraProperties.put(ENV_HIBERNATE_HBM2DDL_AUTO, env.getProperty(ENV_HIBERNATE_HBM2DDL_AUTO));
        if (log.isDebugEnabled()) {
            log.debug(" hibernate.dialect @" + env.getProperty(ENV_HIBERNATE_DIALECT));
        }
        if (env.getProperty(ENV_HIBERNATE_DIALECT) != null) {
            extraProperties.put(ENV_HIBERNATE_DIALECT, env.getProperty(ENV_HIBERNATE_DIALECT));
        }
        return extraProperties;
    }

    @Bean
    public PlatformTransactionManager transactionManager(LocalContainerEntityManagerFactoryBean entityManagerFactory) {
        return new JpaTransactionManager(entityManagerFactory.getObject());
    }

    @Override
    public void setEnvironment(Environment environment) {
        this.env = environment;
    }
}

**Here is my service class with a postgress trigger to listen**

class myService{

	final PostgresqlConnection connection;

	public myService(ConnectionFactory connectionFactory ) {
		this.connection =  Mono.from(connectionFactory.create())
				.cast(PostgresqlConnection.class).block();
	}

	@PostConstruct
	private void postConstruct() {
		connection.createStatement("LISTEN my_channel").execute()
				.flatMap(PostgresqlResult::getRowsUpdated).subscribe();
		connection.getNotifications().subscribe(myService::catchTrigger);
	}

	private static void catchTrigger(Notification notification) {
		System.out.println(notification.getName());
		System.out.println(notification.getParameter());
	}
}
