### ISSUE TITLE
Default value for spring.data.elasticsearch.client.reactive.endpoints is not documented

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28037]
There's no default value listed for [`spring.data.elasticsearch.client.reactive.endpoints`](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#spring.data.elasticsearch.client.reactive.endpoints). As it's a `List`, the default value needs to come from manual metadata.

**Comment by snicoll** [comment]
Closing in favor of PR #28061
