### ISSUE TITLE
Elasticsearch Enhance configuration to enable non local node

### ISSUE THREAD

**Issue by tetrawgf** [spring-projects/spring-boot#2805]
Hello,

Why is the local option always true when creating a node client in the the auto configuration :

``` java

private Client createNodeClient() throws Exception {
        ImmutableSettings.Builder settings = ImmutableSettings.settingsBuilder()
                .put("http.enabled", String.valueOf(false))
                .put(this.properties.getProperties());
        Node node = new NodeBuilder().settings(settings)
                .clusterName(this.properties.getClusterName()).local(true).node();
        this.releasable = node;
        return node.client();
    }

```

It may be interesting to set this option via a property in ElasticsearchProperties.class in order to join an existing cluster that live on another jvm.

**Comment by wilkinsona** [comment]
If you configure the `cluster-nodes` property, the auto-configuration will [create a transport client rather than a node client](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/elasticsearch/ElasticsearchAutoConfiguration.java#L72-L77):

```
private Client createClient() throws Exception {
	if (StringUtils.hasLength(this.properties.getClusterNodes())) {
		return createTransportClient();
	}
	return createNodeClient();
}
```

**Comment by tetrawgf** [comment]
What if I do not want a TransportClient but a node client ?

Please read the es documentation.
http://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html

For instance :

>The benefit of using the Client is the fact that operations are automatically routed to the node(s) the operations need to be executed on, without performing a "double hop". For example, the index operation will automatically be executed on the shard that it will end up existing at.

**Comment by wilkinsona** [comment]
Ah, I see. That makes your question/suggestion much clearer. Thanks.

@akonczak @mohsinh Any comments?

**Comment by ppuffinburger** [comment]
I just ran into this today.  

 I thought maybe since properties have now been included (Spring Boot 1.2.3) that maybe we could set up a Node Client to connect to our cluster.   But it seems the forcing local to true stops that from happening since it comes after properties have been set, so setting node.local to false in the properties gets overridden by the NodeBuilder (which just sets node.local to true in the properties in this case).

It would probably be nice to let users set local, client, and data on the NodeBuilder (which in turn et the appropriate properties of node.local, node.client, and node.data).

**Comment by akonczak** [comment]
Hi All 
Yes, the current configuration for ES is quite basic. I like the idea to separate configuration in properties for transport client and node client.

transport.client = true/false
transport.nodes = list of es nodes 

node.client = true/false
node.local = true/false
node.data = true/false
node.http.enabled = true/false
clusterName = name of the cluster share between both node and transport client 

What do you think ?

**Comment by wilkinsona** [comment]
The auto-configuration currently creates a single `Client` bean that will either be a node client or a transport client. If both `transport.client` and `node.client` were set to `true`, are you proposing that two beans (a `TransportClient` and a `Client`) would be created?

**Comment by akonczak** [comment]
There is no point in having 2 clients(beans) at the same time. If someone  set both clients to true we can create most common transport client and ignore configuration for node client. Or we can go further and have a single field in configuration called  'client' and a value for that field must be one of the values [transport or node].

client = node/transport
clusterName = name 

transport.client = true/false
transport.nodes = list of es nodes

node.local = true/false
node.data = true/false
node.http.enabled = true/false

**Comment by wilkinsona** [comment]
Thanks, @akonczak. The current implementation uses the presence of `spring.data.elasticsearch.cluster-nodes property` to choose which type of client to create. Is that approach no longer sufficient?

**Comment by akonczak** [comment]
That approach is sufficient but in some cases can lead to problems and misunderstanding.
So far we know that es boot module doesn't support very well node client and we should change it.

If you have any suggestion how to improve it, please share your ideas with us

**Comment by akonczak** [comment]
With this PR we can use properties to change any ES configuration.

Example for node client: 
spring.data.elasticsearch.properties.node.local=false
spring.data.elasticsearch.properties.node.data=false
spring.data.elasticsearch.properties.http.enabled=true
