### ISSUE TITLE
Jackson2ObjectMapperBuilder doesn't allow subclassing

### ISSUE THREAD

**Issue by johannburkard** [spring-projects/spring-boot#2806]
I stumbled over Jackson's memory usage/buffer bloat (16 KB, probably per-request) and decided to do something about it.

`Jackson2ObjectMapperBuilder` is the class responsible for creating `ObjectMapper`s. It has a private `createXmlMapper` attribute that has no (protected) getters, making it impossible in subclasses to fully override the `build` method.

The fix is easy: Add a getter.

**Comment by snicoll** [comment]
ping @sdeleuze

**Comment by wilkinsona** [comment]
@johannburkard Can you not just override `configure`?

**Comment by johannburkard** [comment]
I took another look at the class and I think `Jackson2ObjectMapperBuilder` right now is badly designed. It is into a stateful builder with static factory methods and not used consistently across Spring.

A custom `Jackson2ObjectMapperBuilder` set up as a Spring bean will be used in some places like `JacksonObjectMapperConfiguration` but not in the really interesting places like

```
	protected final void addDefaultHttpMessageConverters(List<HttpMessageConverter<?>> messageConverters) {
...
		if (jackson2Present) {
			ObjectMapper objectMapper = Jackson2ObjectMapperBuilder.json().applicationContext(this.applicationContext).build();
```

And it's those spots that set up JSON encoding. So there is no way to get either a custom `Jackson2ObjectMapperBuilder` or `ObjectMapper` configured app-wide.

What I would do is to create two subclasses of `Jackson2ObjectMapperBuilder`, one for XML, one for JSON. Allow overriding them in Spring (would be easy to do in `WebMvcConfigurationSupport`). Mark the static json/xml methods as `@Deprecated` and get rid of their occurrences.

@wilkinsona I guess I could for a custom view. But I don't have a need for those anymore with the JSON-P support in MVC 4.1 (?).

**Comment by wilkinsona** [comment]
@johannburkard Your comments seem to be aimed at `Jackson2ObjectMapperBuilder` which is a Spring Framework class, not a Spring Boot class. You should open a [Spring Framework issue](https://jira.spring.io/browse/SPR).

Spring Boot should configure the `ObjectMapper` app-wide based on your own `Jackson2ObjectMapperBuilder` bean or your configuration in `application.properties`. See [`JacksonHttpMessageConvertersConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/JacksonHttpMessageConvertersConfiguration.java), for example.

**Comment by sdeleuze** [comment]
As proposed by @wilkinsona, instead of extending `Jackson2ObjectMapperBuilder`, you should provide your own `Jackson2ObjectMapperBuilder` beans. If `Jackson2ObjectMapperBuilder` does not provide the kind of configuration customization you need, maybe you could try to register `com.fasterxml.jackson.databind.Module` beans. There are also additional customization capabilities described in [Spring Boot documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-jackson-objectmapper).

Feel free to create a [Spring Framework issue](Spring Framework issue) if you need additional configuration capabilities in `Jackson2ObjectMapperBuilder`.

**Comment by johannburkard** [comment]
Thanks, I'll open an issue there. @wilkinsona as I said, I think there are places that use a `Jackson2ObjectMapperBuilder` but the main converter configuration in `WebMvcConfigurationSupport` doesn't, it's using the static builder methods.

**Comment by wilkinsona** [comment]
> but the main converter configuration in WebMvcConfigurationSupport doesn't, it's using the static builder methods.

That doesn't matter in a Spring Boot app due to the configuration performed by `JacksonHttpMessageConvertersConfiguration`.
