### ISSUE TITLE
Set timestamp for nested jars

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2807]
See http://bsideup.blogspot.com/2015/04/spring-boots-fat-jars-vs-docker.html?utm_content=bufferd58ba&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

We might be able to set the timestamp of nested jars to save the `$ find ./app/lib/ | xargs touch -t 0000000000.00` step.

**Comment by philwebb** [comment]
Great article @bsideup. I've made some changed to the 1.3 SNAPSHOT that should hopefully remove the `xargs touch -t` step.

**Comment by bsideup** [comment]
@philwebb thanks! I will test it one more time with latest snapshot and report results here, but quick overview of changes looks promising

**Comment by bsideup** [comment]
@philwebb
```bash
$ ~/Downloads/spring-1.3.0.BUILD-SNAPSHOT/bin/spring jar app.jar app.groovy
$ rm -rf app/ && unzip -q app.jar -d app
$ docker build .
Sending build context to Docker daemon 35.36 MB
Sending build context to Docker daemon
Step 0 : FROM java:8-jre
 ---> 028f36974b77
Step 1 : ADD app/lib/ /app/lib/
 ---> Using cache
 ---> 6129cc71beb8
Step 2 : ADD app/ /app/
 ---> 526bc9ab79cf
Removing intermediate container e44b31c0d41b
Step 3 : CMD java -cp /app/ org.springframework.boot.loader.JarLauncher
 ---> Running in 076cff8bd0cf
 ---> f2a53189b48b
Removing intermediate container 076cff8bd0cf
Step 4 : EXPOSE 8080
 ---> Running in 769089a37587
 ---> bdf9bb93b3d8
Removing intermediate container 769089a37587
Successfully built bdf9bb93b3d8
```

It works!

**Comment by thomasdarimont** [comment]
Just saw this - great to have that :)
One remark: shouldn't one also delete the app.jar after unpacking it into /app to shrink the container a bit? Because  with the command sequence from above you have the app.jar AND the unpacked /app folder in your container - or am I missing something?

**Comment by bsideup** [comment]
yeah, good catch
