### ISSUE TITLE
Harvest property descriptions from a @ConfigurationProperties-annotated record

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28074]
At the moment, the configuration properties annotation processor harvests property descriptions from a class's fields. This doesn't work well with records as they don't have fields. It'd be nice if we could devise some other way of harvesting property descriptions from the record's source. At the moment, you have to use additional metadata instead.

One possibility may be to read the `@param`s from the record-level javadoc:

```java
/**
 * @param someProperty An example property to be described in the metadata.
 */
@ConfigurationProperties(prefix = "record")
public record MyRecordProperties(String someProperty) { }
```

In this example, we already generate metadata for `someProperty`:

```javascript
{
  "name": "record.some-property",
  "type": "java.lang.String",
  "sourceType": "com.example.recordconfigpropstest.MyRecordProperties"
}
```

What we're aiming for is having a `description` as well:

```javascript
{
  "name": "record.some-property",
  "type": "java.lang.String",
  "description": "An example property to be described in the metadata.",
  "sourceType": "com.example.recordconfigpropstest.MyRecordProperties"
}
```

**Comment by theoathayde** [comment]
Hello, sorry for taking so long. I`ve been having some trouble advancing with this issue, can i still work in this? If so, can i have some help?

**Comment by theoathayde** [comment]
Awesome, thank you. Sorry if this is too basic, i successfully built the code but i'm having trouble actually running spring boot so i can test the metadata.

**Comment by wilkinsona** [comment]
I don't think that's necessary. Instead, I would test the metadata by modifying [the existing `record`-based tests](https://github.com/spring-projects/spring-boot/blob/8bd3d530853c39550f87a3c8ad7bc0d68a157f3e/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/test/java/org/springframework/boot/configurationprocessor/ConfigurationMetadataAnnotationProcessorTests.java#L413-L461). The tests currently check that the properties are recorded but that's it. Those tests could be updated to check that the expected descriptions are now found. You can use `withDescription` to do so as some of the earlier tests already do. See [this one](https://github.com/spring-projects/spring-boot/blob/8bd3d530853c39550f87a3c8ad7bc0d68a157f3e/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/test/java/org/springframework/boot/configurationprocessor/ConfigurationMetadataAnnotationProcessorTests.java#L104), for example.

**Comment by theoathayde** [comment]
Hi, i`ve been working on this for a while but i still had no success. I`ve tried some things like creating a new method on Metadata to include a description and i updated the test but it failed. Do you have some tips or ideas on the changes i have to make?

**Comment by philwebb** [comment]
@theoathayde I lot of the team is taking vacation over the holiday season. I'm afraid we probably won't be able to investigate other ideas until the new year. Sorry about that.

**Comment by theoathayde** [comment]
Sure, happy holidays, we can discuss it more next year.

**Comment by wilkinsona** [comment]
@theoathayde Can you share a branch on your fork that shows your changes thus far? That'll give us a basis on which to offer some suggestions.

**Comment by theoathayde** [comment]
Hello, i'm having some health issues, i'm afraid i won't be able to work on this anymore. I'm deeply sorry.

**Comment by philwebb** [comment]
Sorry to hear about your health issues @theoathayde. Best wishes for your recovery.

**Comment by An1s9n** [comment]
Hi guys! Please glance PR #29403 as a solution for this issue.

**Comment by snicoll** [comment]
Closing in favor of PR #28074
