### ISSUE TITLE
Log ready time under 'spring.boot.application.ready' rather than 'spring.boot.application.running'

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#28080]
Currently `SpringApplicationRunListeners` logs ready time using `spring.boot.application.running`. I think we should change this to `spring.boot.application.ready` for consistency with the readiness probe support.

**Comment by snicoll** [comment]
Do you mean renaming `SpringApplicationRunListener#running` to `SpringApplicationRunListener#ready` then?

**Comment by philwebb** [comment]
Yes. That should have been done already in a polish commit I recently pushed.
