### ISSUE TITLE
@ConfigurationProperties should have the possibilty to not allow null values

### ISSUE THREAD

**Issue by Loki-Afro** [spring-projects/spring-boot#281]
Is there a solution for not checking for null values in my configuration class?
I have the case that some values can't be null and there is no default value for them.

```
@ConfigurationProperties(ignoreInvalidFields = false, ignoreUnknownFields = false, value = "mail")
public class MailConfiguration {
    //should not be null in any case
    private InetAddress host;
}
```

**Comment by Geniy00** [comment]
Is it possible to apply @NotNull and @NotBlank annotation for all properties annotated with @ConfigurationProperties

**Comment by snicoll** [comment]
@Geniy00 this tracker is not the best place to ask questions (in particular on a closed issue). Please ask your question on StackOverflow with the `spring-boot` tag.
