### ISSUE TITLE
Autoconfiguration report in test runner

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2810]
I'm refactoring an existing library to support autoconfiguration and am having what looks to be a configuration ordering issue. It would be very helpful to see the autoconfiguration report, but I can't find a way to enable it; adding `--debug` to the Eclipse run configuration has no effect, and the `@SpringApplicationConfiguration` annotation has no relevant parameters. Is there a way to have the test runner output the report?

**Comment by philwebb** [comment]
You should be able to set the logging level for `org.springframework.boot.autoconfigure.logging` to `DEBUG` (using whatever logging technologies you have in your tests) to display the report. See `AutoConfigurationReportLoggingInitializer`.

**Comment by chrylis** [comment]
Ouch. Okay, I'll give it a shot, but the ancient Eclipse slf4j bug is probably going to be involved. It might be helpful to note this in the doc Testing chapter.

**Comment by philwebb** [comment]
If you have the `LoggingApplicationListener` in the mix with your tests you might get away with setting an Environment property for the level.
