### ISSUE TITLE
DataSource Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

### ISSUE THREAD

**Issue by qmdx** [spring-projects/spring-boot#28125]
This problem can be caused when customizing datasources for multiple datasource

Can the class `XADataSourceAutoConfiguration`  and  `DataSourceAutoConfiguration `  specify `@ConditionalOnMissingBean` to avoid exceptions
`Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true`
 
Mainly involved

`org.springframework.boot:spring-boot-starter-jta-atomikos`

`org.springframework.boot:spring-boot-starter-jdbc`

**Comment by wilkinsona** [comment]
Thanks for the suggestion but I don't think I understand what you'd like us to do. Can you please provide a minimal example that reproduces the problem that you're facing?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
