### ISSUE TITLE
Is there any way to use ConfigurationProperties in standard Spring project?

### ISSUE THREAD

**Issue by wizwjw** [spring-projects/spring-boot#2815]
We have a standard Spring project, it won't be easy to migrate to Spring Boot. Since ConfigurationProperties is very useful for type safe configuration.  I wonder if there is a way to use it in my existing project.

**Comment by snicoll** [comment]
I don't see any problem with it. Just add `@EnableConfigurationProperties` as you would do with a Spring Boot app and it should work. Have you tried?

**Comment by wizwjw** [comment]
Fantastic!, it works like a charm. Thanks!
