### ISSUE TITLE
Adopt java.util.HexFormat

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28154]
There are a few places in Boot where we work with hex strings, for example:

https://github.com/spring-projects/spring-boot/blob/ea68672594a1abc302a669fee9c794abb1f28b3e/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform/src/main/java/org/springframework/boot/buildpack/platform/docker/type/VolumeName.java#L126-L132

https://github.com/spring-projects/spring-boot/blob/ea68672594a1abc302a669fee9c794abb1f28b3e/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/Digest.java#L56-L62

https://github.com/spring-projects/spring-boot/blob/ea68672594a1abc302a669fee9c794abb1f28b3e/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/system/ApplicationTemp.java#L163-L171

Where appropriate, we should use Java 17's `java.util.HexFormat` instead.

#28101 is a prerequisite for this.

**Comment by snicoll** [comment]
Closing in favor of PR #31477
