### ISSUE TITLE
Use java.util.List.of for creation of unmodifiable lists

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28174]

**Comment by mbhave** [comment]
Placing this `on-hold` because we've decided to approach this on a case-by-case basis for new usages. There are subtle differences between `List.of()` and the equivalent `Collections` method such as `contains(null)` throwing an NPE which aren't suitable for a blanket search and replace.

**Comment by Abhishekverma2002** [comment]
Would love to contribute in java and algos. If you have any such set of work ,consider me in.

**Comment by philwebb** [comment]
I think we can close this one and adapt to `List.of` in new code or when we touch existing classes. Doing an entire sweep at this point doesn't seem worth it.
