### ISSUE TITLE
Use java.util.Set.of for creation of unmodifiable sets

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28175]

**Comment by snicoll** [comment]
@aravindbargurhiriyannaiah thanks for the offer but this one isn't a great candidate, see https://github.com/spring-projects/spring-boot/issues/28179#issuecomment-935542941

**Comment by mbhave** [comment]
Placing on hold for the same reason as #28174.

**Comment by philwebb** [comment]
I think we can close this one and adapt to `List.of` in new code or when we touch existing classes. Doing an entire sweep at this point doesn't seem worth it.
