### ISSUE TITLE
Can a Filter be used to record the response status for requests to static resources?

### ISSUE THREAD

**Issue by maddy-markovitz** [spring-projects/spring-boot#2817]
I'm working on a web application, one of the requirements of which is to log all HTTP requests and response statuses.  Requests have a 'context' associated with them that needs to be included in the log messages, so using the Tomcat access log is not an option.
I thought I would be able to accomplish this using a Filter, however the Filter does not 'see' the correct response code when dealing with requests to static resources - it only ever sees 200.  I think this must be because my static resources don't go through a controller in the same way that other requests do, but I'm not sure how to fix it.  
This is how I'm adding the static resource handler:

```java
  @Configuration
    @EnableConfigurationProperties
    @EnableWebMvc
    public class AppConfiguration extends WebMvcConfigurerAdapter {

        @Autowired
        private MyAppProperties properties;

//...

        // Serve up static files directly from the external directory
        @Override
        public void addResourceHandlers(ResourceHandlerRegistry registry) {


            registry.addResourceHandler("/resources/**").addResourceLocations(
                    properties.getExternalDirectoryURI("resources/").toString()).setCachePeriod(
                    properties.getCacheControlMaxAge());

            // At least after the controller registry
            registry.setOrder(10);
        }

//...

    }

```

And here's an example of my log messages, when I request a static resource that doesn't exist:

```
2015-03-26 16:02:46.770  INFO 26576 --- [http-bio-8080-exec-3] a.c.u.app.config.RequestLoggingFilter   : CONTEXT=unknown; Type=request; Method=GET; resource=/resources/missing.html
2015-03-26 16:02:46.770  INFO 26576 --- [http-bio-8080-exec-3] a.c.u.app.config.RequestLoggingFilter   : CONTEXT=unknown; Type=response; Status=200; Length=unknown; resource=/resources/missing.html
2015-03-26 16:02:46.788  INFO 26576 --- [http-bio-8080-exec-3] a.c.u.app.config.RequestLoggingFilter   : CONTEXT=unknown; Type=request; Method=GET; resource=/error
2015-03-26 16:02:46.788  INFO 26576 --- [http-bio-8080-exec-3] a.c.u.app.config.RequestLoggingFilter   : CONTEXT=unknown; Type=response; Status=404; Length=unknown; resource=/error

```
I'm using Spring Boot 1.2.3 and Tomcat 7.0.52.

Is it expected behaviour to not be able to see the correct response status in Filter?  If not, any advice on what I might be doing wrong?

**Comment by philwebb** [comment]
Are you deploying your application as a war? If so it might be that the `ErrorPageFilter` is handling the error before your filter gets a chance to deal with it. I'm not sure if we currently offer an easy way to disable the filter, @dsyer may know.

**Comment by maddy-markovitz** [comment]
I do deploy as a war, but in development I run it in embedded Tomcat, and it's happening there too.

**Comment by philwebb** [comment]
Would you have time to submit a [sample project](https://github.com/spring-projects/spring-boot-issues) that reproduces the problem?

**Comment by maddy-markovitz** [comment]
Yes, but it will take me some time to reduce the code down to a simple app - will try to submit something this weekend.

**Comment by maddy-markovitz** [comment]
Hi Phil, I've submitted a pull request for my sample project.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem's in your filter: you're logging the response's status code before the request has been processed. At that point the assumption is that the response will be a 200. You need to perform your logging after you've invoked the filter chain:

```java
@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
        throws ServletException, IOException {
    filterChain.doFilter(request, response);
    LOGGER.info("HTTP request for resource {} - status {}", request.getRequestURI(), response.getStatus());
}
```

**Comment by maddy-markovitz** [comment]
Thanks for your help, can't believe I didn't think of that.  I guess I thought the request/response pair would be out of scope after invoking doFilter().
