### ISSUE TITLE
Use Files.readString and Files.writeString when reading and writing string data

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28179]
`String.lines()` may be useful here too.

**Comment by cmabdullah** [comment]
Hello, @wilkinsona I want to works on this enhancement task, can you please show an example class, by following the example I may be able to make a PR.

**Comment by snicoll** [comment]
@cmabdullah thanks for the interest but this task is assigned to Spring Boot `3.0.x` and we haven't a branch for it yet. It is very much likely that an IDE inspection is going to help us automate this (and other Java 17 migrations) so we can take care of that ourselves.

**Comment by wilkinsona** [comment]
Superseded by https://github.com/spring-projects/spring-boot/pull/31459.
