### ISSUE TITLE
Section 4.4 File Rotation mentions the wrong configuration file name for Log4j2

### ISSUE THREAD

**Issue by xiao1272209235** [spring-projects/spring-boot#28184]
[SpringBoot v2.5.5 - File Rotation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.file-rotation)

### original
If you are using the Logback, it’s possible to fine-tune log rotation settings using your application.properties or application.yaml file. For all other logging system, you’ll need to configure rotation settings directly yourself (for example, if you use Log4J2 then you could add a <b>log4j.xml</b> file).

### After modification
If you are using the Logback, it’s possible to fine-tune log rotation settings using your application.properties or application.yaml file. For all other logging system, you’ll need to configure rotation settings directly yourself (for example, if you use Log4J2 then you could add a <b>log4j2.xml or log4j2-spring.xml</b>  file).

**Comment by wilkinsona** [comment]
Closing in favor of #28189.
