### ISSUE TITLE
Use text blocks where appropriate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28182]

**Comment by Subhasish-Behera** [comment]
hello ! i am intrested in solving this issue  .i am a freshman . i have basic knowledge of java i.e data structures and OOPS.Please help me starting with this issue.

**Comment by philwebb** [comment]
Thanks for the offer @Subhasish-Behera but I'm afraid this issue is currently labeled as `status: blocked`. This means we're not ready to move forward with it just yet.

**Comment by philwebb** [comment]
I think we should adopt text blocks as and when we touch various aspects of the code. It's pretty hard to do a general sweep for places they could be used.
