### ISSUE TITLE
Remove dependency management for RxJava 1.x and RxJava 2.x

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#28212]
As a follow up of spring-projects/spring-framework#27443, we should drop support for RxJava 1.x and RxJava 2.x and only provide dependency management for RxJava 3.x.

**Comment by avillalain** [comment]
@bclozel after looking at another issue that was marked for the 3.0.x milestone I realized that I should have asked before creating the PR. I think I'll cancel the PR. Also on a side note, what would you recommend for a new comer to pick up, should I ask in Gitter?
