### ISSUE TITLE
EntityScanPackages has package-private constructor

### ISSUE THREAD

**Issue by riba2101** [spring-projects/spring-boot#28232]
Hello,

is there a reason why `EntityScanPackages` has a package-private constructor?
The whole thing about entity scanning is extensible, but the class is "hindering" this?

BR

**Comment by wilkinsona** [comment]
It sounds like using `@AutoConfigurationPackage` may do what you want. It's not yet very well documented so please see https://github.com/spring-projects/spring-boot/issues/27549 for some more details.

**Comment by philwebb** [comment]
I'm not really following the above example I'm afraid, but it won't be possible to make `@Enable` annotations `@Repeatable`. I also don't think we want to make the constructor of `EntityScanPackages` public.

If you want to register additional packages for entity scanning you can use the `EntityScanPackages.register` static methods.
