### ISSUE TITLE
URLClassLoader.findClass with different behavior when called within jjs Nashorn

### ISSUE THREAD

**Issue by brunoborges** [spring-projects/spring-boot#2823]
When running a script with jjs that invokes a class from a classpath configured with 'jjs -cp', that will make use of URLClassLoader.findClass, the behavior is different from when the Java library is invoked the usual way.

See log trace: https://gist.github.com/brunoborges/110af2969f2c2be7e288

To invoke code, see: https://github.com/brunoborges/nashorn/tree/master/maven/samples/springboot

**Comment by philwebb** [comment]
That's weird, I wonder why `URLClassLoader.findClass` wouldn't find that class.

**Comment by brunoborges** [comment]
That can be a bug in three different places:
1) URLClassLoader.findClass weird behavior when called from within Nashorn script executed with **jjs*
2) Nashorn's way to build a ClassLoader for the -cp classpath passed by with **jjs**
3) Spring Boot usage of findClass, plus some weird bug inside findClass

Of course #3 is likely not true :-) #ButWhoKnows

**Comment by wilkinsona** [comment]
When launched with `jjs -cp`, Nashorn creates a ClassLoader using the specified class path but, unlike `java -cp`, it does not make that ClassLoader the thread context class loader. This means we end up trying to load classes using the app class loader which can't see any of the classes that are on the class path.

Setting the thread context class loader before calling `run()` fixes the problem:

```javascript
var SpringApplication = Packages.org.springframework.boot.SpringApplication;
java.lang.Thread.currentThread().contextClassLoader = SpringApplication.class.classLoader;
```
