### ISSUE TITLE
PublicMetricsAutoConfigurationTests.multipleCacheManagers fails intermittently

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2824]
The cache managers handled in `CachePublicMetrics` aren't ordered so the logic that uses the cache manger's name as a prefix when there's a clashing cache name isn't deterministic.

/cc @snicoll

**Comment by snicoll** [comment]
Ah, good point.

**Comment by izeye** [comment]
@wilkinsona How about prefixing always?

For example, if someone has a monitoring system based on the metrics and cache name collision is occurred by adding a new cache manager or a new cache, the monitoring system won't work.

I guess prefixing always is more simple and resilient.

**Comment by wilkinsona** [comment]
I discussed that with @snicoll when I was making this change. He believed that only prefixing when necessary was a better solution and he knows more about caching than I do. Stephane?

**Comment by snicoll** [comment]
@izeye you can always change the default if that does not match your expectations. I believe that the vast majority of use cases do not involve any cache name collision so prefixing always seems like the wrong thing to do to me.

**Comment by izeye** [comment]
@snicoll Ok. Thanks for the explanation :)
