### ISSUE TITLE
Add smoke tests for Spring Session with MongoDB and Redis 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#28291]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
Spring Boot contains a comprehensive set of Smoke Tests that are used to verify high-level functionality of the various features that Spring Boot provides. Spring Boot's integration with Spring Session has automated smoke tests for JDBC and Hazelcast but similar smoke tests for MongoDB and Redis are missing. 

## Solution

MongoDB
Create a module for `spring-boot-smoke-test-session-mongodb` in `spring-boot-smoke-tests` containing the main application and the tests. This will be very similar to [`spring-boot-smoke-test-session-hazelcast`](https://github.com/spring-projects/spring-boot/tree/37426df148ff9a4a573e380be91820c1bedd2f4c/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session-hazelcast). Hazelcast dependencies will need to be replaced with dependencies for Spring Session with MongoDB which can be found [here](https://github.com/spring-projects/spring-boot/blob/37426df148ff9a4a573e380be91820c1bedd2f4c/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session/build.gradle#L18-L20).

Redis
Follow the same steps as MongoDB but [use these dependencies](https://github.com/spring-projects/spring-boot/blob/37426df148ff9a4a573e380be91820c1bedd2f4c/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session/build.gradle#L22-L25) instead.

## Steps to Fix 
 
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by avillalain** [comment]
@mbhave I would like to work on this issue.

**Comment by avillalain** [comment]
Hi @mbhave, I attached an additional set of commits, and I'm wondering if there is some feedback that you can give me. Also there are 2 scenarios I did not cover, and they are related to the WebSession support. I basically have 2 more smoke tests scenarios that I can't get to replicate the same test but in that case using the WebSession for mongo and redis. I don't know if it would make sense to add those scenarios as a commit to see if someone can figure out why it might not be working
