### ISSUE TITLE
 Disable the environment info contributor by default 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#28311]
For consistency with #28310 we should not expose the environment info contributor by default.

**Comment by charboubmustapha** [comment]
@wilkinsona  @philwebb  in the version 2.6.2 even if it's enable , the info are missing , I think it's related to the configuration of EnvironmentInfoContributor in InfoContributorAutoConfiguration . the fallback is all time disabled

**Comment by wilkinsona** [comment]
The fallback should only be used when the property has not been set and we have a test that verifies that the contributor can be enabled:

https://github.com/spring-projects/spring-boot/blob/4256344c80a2dcb7de93383f47d08aca0522ab28/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/info/InfoContributorAutoConfigurationTests.java#L51-L55

if setting `management.info.env.enabled=true` does not work for you, please open a new issue with a minimal sample that reproduces the problem and we can take a look.
