### ISSUE TITLE
Don't expose java info contributor by default

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#28310]
See https://github.com/spring-projects/spring-boot/pull/28136#issuecomment-938526006

We're going to flip the default so it's not exposed by default.

**Comment by dominikbrandon** [comment]
Would you mind sharing a hint on how to do that? This issue seemed easy to me, so I thought I'd help you with that, but I just can't find any way to set the default `management.info.java.enabled` value.
