### ISSUE TITLE
Serve generated resources with spring-boot:run

### ISSUE THREAD

**Issue by fbiville** [spring-projects/spring-boot#2833]
I'm using `spring-boot-maven-plugin` (Spring Boot version: 1.2.3.RELEASE) to repackage my application as a WAR. I generate static resources (HTML & PDF) at `prepare-package` phase so that they properly end up in the WAR.

I start the application with a simple `mvn spring-boot:run` and the generated resources remains unreachable from the app (though they are located at the root of the WAR).

If I add a `src/main/webapp` and add a static HTML file there, this one is properly served (he ends up within the exact same folder as the generated HTML file).

From what I understand (not 100% sure) from [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-maven-plugin.html) and the plugin site [usage page](http://docs.spring.io/spring-boot/docs/1.2.3.RELEASE/maven-plugin/usage.html), resources are served from the source "resources" (and I guess "webapp") folders. 

Can there be a way to run the application directly from the JAR/WAR?
If so, I'd be happy to make a contribution (probably with a little guidance).

**Comment by snicoll** [comment]
`spring-boot:run` does not work on the archive at all. It builds its classpath from the project and run stuff "in place". Your generated content is basically outside of that lifecycle which explains why it's not served.

Have you tried to configure the `folders` attribute to add the location where the generated content is placed?

**Comment by fbiville** [comment]
Yes, I've just tried by adding:

```xml
<configuration>
    <folders>
        <folder>${documentation.output.dir}</folder>
    </folders>
</configuration>
```

**Comment by snicoll** [comment]
@philwebb the whole `run` goal with `war` packaging type confuses me (i.e. for `src/main/webapp`). Can you clarify what we actually support please?

**Comment by fbiville** [comment]
You can reproduce the issue here: https://github.com/fbiville/springboot_issue_2833.
It might be somehow related to the fact that I use Jersey, this is why this minimal project includes a similar configuration to the one I use in the actual private project.

**Comment by fbiville** [comment]
Did you guys @snicoll @philwebb have any time to look at this?

**Comment by snicoll** [comment]
I was waiting for @philwebb answer and I honestly can't see why we would support that. Since your use case involves relying on the `target` content (and ultimately the content of the **generated** war) why don't you use the `jetty-maven-plugin` ?

**Comment by fbiville** [comment]
Sounds acceptable :)

**Comment by snicoll** [comment]
Alright, let's leave it like that for now. Thanks for the feedback.

**Comment by rzymek** [comment]
@fbiville: Adding `<folders>`  works when you take into account, that it [adds folders to the classpath](http://docs.spring.io/spring-boot/docs/1.2.3.RELEASE/maven-plugin/run-mojo.html#folders). [Static content is served](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content) from `/static` or `/public` subdirectories. So you when you place your contents in `target/generated/public`, then the following will work:

    <configuration>
      <folders>
        <folder>target/generated</folder>
      </folders>
    </configuration>
