### ISSUE TITLE
Qualifier-support for @Conditionals

### ISSUE THREAD

**Issue by lbeuster** [spring-projects/spring-boot#2834]
I have the use case that I have several beans of the same type but with different qualifiers (all beans are created with @Bean). I wanted to overwrite one of these beans in my tests and tried to use @ConditionalOnMissingBean on the original bean. But I could not address the qualifier of that bean. Adding the the @ConditionalOnMissingBean would mean that my bean never gets created because there are other beans of the same type (but with different qualifiers).
First I tried to use the @ConditionalOnMissingBean.annotation field but that seems to have a different meaning (for which I do not see the use case ;)).

My question: Did I miss something or is this a valueable use case?

Best regards
Lars

**Comment by philwebb** [comment]
I wouldn't recommend using `@ConditionalOnMissingBean` unless it's in the context of an auto-configuration class. The order that beans are parsed can be vary hard to determine and there are few guarantees (except that auto-configuration classes are considered after user defined beans)

I would probably recommend that you look at `@Profile` for this specific use-case.

**Comment by xorcus** [comment]
This issue is valid In the context of auto-configuration as well. How would you go about conditionally creating a qualified bean in auto-configuration, only if the qualified bean is missing, regardless of the existence of other beans of the same type?

**Comment by snicoll** [comment]
@xorcus that's a rather odd use case. If you really need to rely on a qualifier, use the bean name and `@ConditionalOnMissingBean(name = "qualifier")` in your auto-configuration. If you have more questions, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
