### ISSUE TITLE
Springboot 2.2.16 Upgrade 2.5.5 Problems

### ISSUE THREAD

**Issue by lizheng970817** [spring-projects/spring-boot#28346]
![企业微信截图_16342315381035](https://user-images.githubusercontent.com/55570132/137364854-3d38f362-7f92-41c5-aecf-75c04c85fd16.png)

Problem
![企业微信截图_16342309657391](https://user-images.githubusercontent.com/55570132/137364880-de3288d7-fbdf-42ec-b346-aca874869cb9.png)
![企业微信截图_16342310656499](https://user-images.githubusercontent.com/55570132/137364902-7da67b1e-e7da-4c38-a8d1-332ea698988e.png)

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, you haven't provided enough information for us to be able to help you. There appears to be a problem with the configuration for your `DataSource`. Without knowing how it's configured, whether or not the database you're using is embedded, etc, I don't think we'll be able to figure out the cause.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.
