### ISSUE TITLE
ConfigurationPropertiesBinding annotation can not work when cacheBeanMetadata is disabled

### ISSUE THREAD

**Issue by Ivnoidea** [spring-projects/spring-boot#28365]
my project is based on springboot 2.1.9.RELEASE
in my project, there is a self-defined AutoCongiuration module in which a bean has properties like  
List<Object> providers;

and this property is binding to strings declaired in application.yml like 

xxx:
    providers:
       - com.example.XProvider
       - com.example.YProvider
 
and when cacheBeanMetaDate is disabled , it will raise an exception like
Description:

Failed to bind properties under 'xxx.providers[0]' to com.example.XProvider:

    Property: xxx.providers[0]
    Value: com.example.XProvider
    Origin: class path resource [application.yml]:31:9
    Reason: No converter found capable of converting from type [java.lang.String] to type [com.example.XProvider]

Action:
Update your application's configuration

I have already found where the problem is.  when cacheBeanMetaDate is disabled,  the method  named isQualifierMatch in BeanFactoryAnnotationUtils.class will return false due to ((RootBeanDefinition) bd).getResolvedFactoryMethod() is null. 
and this problem is very similar to https://github.com/spring-projects/spring-boot/commit/b240c810a810c873e84d058614b5d0174591cff9

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
