### ISSUE TITLE
spring.output.ansi.enabled not work

### ISSUE THREAD

**Issue by lfz757077613** [spring-projects/spring-boot#28388]
I recur this issure in an new empty project with springboot2.5.5 
application.yml likes below, but the log is colorful
```
spring:
  output:
    ansi:
      enabled: never
```
After I debug my project, I found this code change AnsiOutput.enabled from initial DETECT to ALWAYS, but I'm confused why `Binder.get(environment).bind("spring.output.ansi.enabled", AnsiOutput.Enabled.class)` bind to ALWAYS

![image](https://user-images.githubusercontent.com/16242100/138021567-325ab4ff-0d2a-479e-8f30-4a5f5841e52a.png)

**Comment by lfz757077613** [comment]
That makes sense, thx

**Comment by LuisEscamillaMartin** [comment]
You can set it at runtime this way:

Windows: set SPRING_OUTPUT_ANSI_ENABLED=NEVER
Linux: export SPRING_OUTPUT_ANSI_ENABLED=NEVER
