### ISSUE TITLE
apply plugin: 'org.springframework.boot.spring-boot' should be apply plugin: 'spring-boot' ?

### ISSUE THREAD

**Issue by xing-kenny** [spring-projects/spring-boot#2838]
In 13.2 Gradle
 
	buildscript {
		repositories { jcenter() }
		dependencies {
			classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT")
		}
	}

	apply plugin: 'java'
	apply plugin: 'org.springframework.boot.spring-boot'

	repositories { jcenter() }
	dependencies {
		compile("org.springframework.boot:spring-boot-starter-web")
		testCompile("org.springframework.boot:spring-boot-starter-test")
	}

the result as following

	E:\gitrepo\sf4\myproject>gradle

	FAILURE: Build failed with an exception.

	* Where:
	Build file 'E:\gitrepo\sf4\myproject\build.gradle' line: 11

	* What went wrong:
	A problem occurred evaluating root project 'myproject'.
	> Failed to apply plugin [id 'org.springframework.boot.spring-boot']
	   > Plugin with id 'org.springframework.boot.spring-boot' not found.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 13.488 secs

and change to 
    apply plugin: 'spring-boot'

it OK.

**Comment by snicoll** [comment]
The `jcenter` repository does not have the SNAPSHOT build of the plugin (only releases)

you can generate a gradle build from https://start.spring.io if you want a valid example, something like this:

```groovy
buildscript {
    ext {
        springBootVersion = '1.3.0.BUILD-SNAPSHOT'
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea' 
apply plugin: 'org.springframework.boot.spring-boot' 
...
```

**Comment by wilkinsona** [comment]
We should update the documentation for snapshot builds to show the use of `https://repo.spring.io/libs-snapshot`

**Comment by pford68** [comment]
Hello, this issue just suddenly became a problem for me 10 minutes ago.  Switching to mavenCentral() from jcenter() had no effect.

**Comment by wilkinsona** [comment]
1.3.0 snapshots had changed the plugin's id from 'spring-boot' to 'org.springframework.boot.spring-boot' to make it suitable for inclusion in Gradle's plugin portal. Unfortunately, due to some changes to the Portal's publishing process, we no longer plan to include the plugin in the portal so we've reverted the change. See #1567 for more details.
