### ISSUE TITLE
Spring Boot + Data MongoDB question

### ISSUE THREAD

**Issue by whgibbo** [spring-projects/spring-boot#2839]
Hi,
Is there an equivalent for mongodb:

spring.datasource.data
spring.datasource.schema

Or does it just work ?
As I can't see any examples of how to pre-populate the datasource.

Many thanks.

**Comment by eddumelendez** [comment]
For mongodb there are these properties:

```
# MONGODB (MongoProperties)
spring.data.mongodb.host= # the db host
spring.data.mongodb.port=27017 # the connection port (defaults to 27107)
spring.data.mongodb.uri=mongodb://localhost/test # connection URL
spring.data.mongodb.database=
spring.data.mongodb.authentication-database=
spring.data.mongodb.grid-fs-database=
spring.data.mongodb.username=
spring.data.mongodb.password=
spring.data.mongodb.repositories.enabled=true # if spring data repository support is enabled
```

To see all of them check the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html).

**Comment by snicoll** [comment]
Please use stackoverflow for such questions. We prefer to use this tracker for bug report or feature request.
