### ISSUE TITLE
Spring Security reference doc links not working

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#28407]
Hi,

I noticed that the links to the Spring Security Reference are not working in the current snapshot docs. https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#web.security

I don't know if this is maybe a spring-security issue or if it's just a matter of adjusting to a new location, but maybe you could coordinate/forward this.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. https://spring.io/projects/spring-security#learn links to https://docs.spring.io/spring-security/ which works but it's unversioned so we'd prefer not to use it. The 5.6.0-RC1 javadoc link (https://docs.spring.io/spring-security/docs/5.6.0-RC1/api/) is versioned but it 404s. There are a few other broken links on Spring Security's project page. I'll ask the Security team to take a look.
