### ISSUE TITLE
Pretty print JSON in remote shell

### ISSUE THREAD

**Issue by habuma** [spring-projects/spring-boot#2841]
The output from the beans command and "endpoint invoke" are all raw, unformatted JSON. Except for cut-n-paste purposes, this limits their usefulness. It would be nice if there were a command that you could pipe the output to and have it pretty-printed.

Use of the command would be something like this:

> beans | pretty | less

This would let me see all of the beans, in an easily readable format, and page through them (thanks to less).

I'm opening this issue as a suggestion in case anyone wants to jump on it. If I get a free moment, I'll try to implement my own CRaSH command to tackle this (perhaps using Jackson's pretty print support) and submit a PR. But if anyone wants to jump on this before I get a chance, then go for it.

**Comment by wilkinsona** [comment]
#1789 is somewhat related. It tackles the problem from the other end by allowing the beans endpoint to use the shared `ObjectMapper` which can be configured to pretty print its output. There's an open PR - #2842.

**Comment by snicoll** [comment]
Unfortunately CRaSH is pretty much abandoned so we won't act on this request. You should also be aware that we're [removing remote shell](https://github.com/spring-projects/spring-boot/issues/7006) support in Spring Boot 2.0.
