### ISSUE TITLE
Release spring-boot-starter-web 2.5.6 to Maven Central

### ISSUE THREAD

**Issue by higgsch** [spring-projects/spring-boot#28426]
Spring-boot 2.5.6 was released and included a tomcat upgrade that is also applicable to spring-boot-starter-web. Maven Central has no release information for 2.5.6 besides the core spring-boot package. Spring-boot-starter-web's most current release is 2.5.5 with the old version of tomcat.

Can we get the starters updated to match the core package? This likely applies to other starters, my team just uses the web starter.

**Comment by philwebb** [comment]
All artifacts should be uploaded at the same time. I can download the POM from https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.5.6/spring-boot-starter-web-2.5.6.pom without issue so perhaps you have a network glitch on your side? You could try running `mvn -U` or clearing out your maven cache.
