### ISSUE TITLE
Validate the aud claim in OAuth2 resource server

### ISSUE THREAD

**Issue by chenrujun** [spring-projects/spring-boot#28427]
# Background

According to [this doc], resource-server must validate `iss` and `aud`.

# Current situation

### iss
1. Congiguration: Now `iss` will be configured by `spring.security.oauth2.resourceserver.jwt.issuer-uri`, 
2. Validation logic:
https://github.com/spring-projects/spring-boot/blob/30c27274e228e1a8995a7c4750b730232fae9a58/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/servlet/OAuth2ResourceServerJwtConfiguration.java#L68-L76

### aud
No related logic

# Requirement
Just like `iss`, we should validate `aud`. And add a property like `spring.security.oauth2.resourceserver.jwt.audience`.

[this doc]: https://tools.ietf.org/id/draft-bertocci-oauth-access-token-jwt-00.html#rfc.section.4

**Comment by cselagea** [comment]
> According to [this doc](https://tools.ietf.org/id/draft-bertocci-oauth-access-token-jwt-00.html#rfc.section.4), resource-server must validate `iss` and `aud`.

That draft has become [RFC 9068](https://datatracker.ietf.org/doc/html/rfc9068), which is a Proposed Standard.

**Comment by chenrujun** [comment]
Hi, @cselagea .

Thank you for your information. 

> That draft has become RFC 9068, which is a Proposed Standard.

Here is my current understanding: 
1. spring-security framework should not implement draft.
2. spring-security framework should implement Proposed Standard.

Correct me if my understanding is wrong.

**Comment by cselagea** [comment]
Hey @chenrujun, I was just sharing the most up-to-date document. I can't say what Spring Security should or shouldn't do.

**Comment by chenrujun** [comment]
@cselagea 

Got it. Thank you for your sharing.

**Comment by ahmedmq** [comment]
Hey @mbhave - Can I work on this issue please?

**Comment by mbhave** [comment]
@ahmedmq Sure, it's all yours. Please let us know if you need any help.

**Comment by chenrujun** [comment]
Hi, @ahmedmq . 
Thank you for your support.
Could you please tell me the ETA and supported Spring Boot version?

**Comment by wilkinsona** [comment]
@chenrujun I don't think @ahmedmq can really answer that question as, even once the changes are implemented, they won't be available until a member of the core that has had the time to review and merge them. The earliest GA release in which the changes could be available is 2.7.0 which is scheduled for May 2022.

**Comment by chenrujun** [comment]
@wilkinsona . I got it. Thank you for your information.

**Comment by mbhave** [comment]
Closing in favor of PR #29084.

**Comment by chenrujun** [comment]
Hi, @mbhave , why close this issue? #29084 is not merged yet.

**Comment by snicoll** [comment]
@chenrujun "in favor of PR" means that we are closing this issue as there is a PR that supersedes this issue. We don't like having both an issue and a PR open.

**Comment by wilkinsona** [comment]
@chenrujun We don’t need an issue and a pull request tracking the same piece of work. We close the issue and label it as superseded to indicate that the PR is now tracking the changes.

**Comment by chenrujun** [comment]
@snicoll , @wilkinsona .
I got it. Thank you.
