### ISSUE TITLE
Actuator document is misleading about k8s startup probe

### ISSUE THREAD

**Issue by ichenhe** [spring-projects/spring-boot#28432]
[Actuator reference](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes) says: 

> If an application takes longer to start than the configured liveness period, Kubernetes mention the "startupProbe" as a possible solution. The "startupProbe" is not necessarily needed here as the "readinessProbe" fails until all startup tasks are done.

But the fact is ["Liveness probes do not wait for readiness probes to succeed"](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes). That means if your application take a long time to start, k8s may kill it before its readinessProbe success — It will never be able to start successfully.

So startupProbe is really necessary.

**Comment by stefanocke** [comment]
I would like to mention that a common reason for slow startup might be database migration (like flyway), since it happens before the actuator endpoints are available at all. Please correct me if I am wrong.
