### ISSUE TITLE
Scheduling auto-configuration backs off with @EnableWebSocket

### ISSUE THREAD

**Issue by lfz757077613** [spring-projects/spring-boot#28449]
When use `@EnableWebSocket` and `@EnableScheduling` at the same time, `spring.task.sheduling*` will not effect
After I debug a simple empty project, I found `ScheduledTaskRegistrar` always use `localExecutor`,  because `TaskSchedulingAutoConfiguration.taskScheduler(TaskSchedulerBuilder builder)` not run.
I guess there are some conflict codes in `WebSocketConfigurationSupport` with `TaskSchedulingAutoConfiguration`

**Comment by wilkinsona** [comment]
Unfortunately, we don't think there's much we can do here in the Boot 2.x timeframe without a change in Framework that will probably have to wait till 6.0 (Boot 3.0). The simplest workaround that allows the `spring.task.scheduling.*` properties to be used is to declare the `ThreadPoolTaskScheduler` bean manually using the auto-configured builder:

```java
@Bean
public ThreadPoolTaskScheduler taskScheduler(TaskSchedulerBuilder builder) {
	return builder.build();
}
```

I've opened https://github.com/spring-projects/spring-framework/issues/27903 to track the Framework change. In the meantime, using the auto-configured builder to define your own `ThreadPoolTaskScheduler` is our recommendation.
