### ISSUE TITLE
Support resolution of AuthenticatedPrincipal in RSocket handler methods

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#28444]
It would be mighty convenient to be able to inject the current authenticated user in an RSocket controller handler method 

```java 

@MessageMapping ("test") 
Mono<String> hello (@Authenticated Principal p){ 
  return Mono.just ("Hello, "  + p.getName()) ;
} 
```

Per a discussion with @rwinch it looks like the autoconfiguration needs an  `RSocketMessageHandlerCustomizer` that adds `AuthenticationPrincipalArgumentResolver` in  `RSocketSecurityAutoConfiguration.java`

**Comment by philwebb** [comment]
Closing in favor of PR #28927. Thanks @terminux!

**Comment by mbhave** [comment]
Closing in favor of PR #28927.
