### ISSUE TITLE
ErrorPageFilter

### ISSUE THREAD

**Issue by ahirsh** [spring-projects/spring-boot#2847]
Hi , 
i have a controller which produces JSON and XML. 
allthough i dont use HTML ErrorPageFilter is throwing messages to log because the response was commited . 
it happens in handleErrorStatus function when i throw exception from my controller. 
i ended up disabling the ErrorPageFilter with :

@Bean
	    public FilterRegistrationBean filterRegistrationBean(ErrorPageFilter errorPageFilter) {
	        FilterRegistrationBean registrationBean = new FilterRegistrationBean();	        
	        registrationBean.setFilter(errorPageFilter);
	        registrationBean.setEnabled(false);
	        return registrationBean;
	    }
but i think spring boot should maybe detect that the response was not html and not use the filter at all ....
thanks.

**Comment by wilkinsona** [comment]
Duplicates #2745

**Comment by ahirsh** [comment]
Hi wilkinsona , 
thanks for your quick comment, 
regarding the link you supplied with your answer in it , 
since i dont see any BUG or enhancment on this issue , 
then what is the best-practice to work around this issue ? 

thanks.
