### ISSUE TITLE
Kotlin Symbol Processing(ksp) Support

### ISSUE THREAD

**Issue by bespaltovyj** [spring-projects/spring-boot#28499]
The new Kotlin [documentation ](https://kotlinlang.org/docs/kapt.html) says that `kapt` is in maintenance mode and new features are not planned. 
And recommend using `ksp`(it should work faster).

![image](https://user-images.githubusercontent.com/32296746/139596680-256890e3-57a8-436d-a564-1887763a4f6c.png)

Will you support ksp?
If you don't mind, then I can start adding `ksp` support.

This [issue](https://github.com/spring-projects/spring-boot/issues/28046) has already been raised, but there the main problem was in using kapt with JDK 16.

**Comment by snicoll** [comment]
@bespaltovyj we'd rather reopen the original issue (that you've commented as well).
