### ISSUE TITLE
Enhancement: Automatically defined mainClassName 

### ISSUE THREAD

**Issue by botscripter** [spring-projects/spring-boot#28491]
I would like to ask what if the property mainClassName in f.e. the build.gradle file is set automatically with the right value instead of having to be defined. In my humble opinion, it is possible to search for the one class annotated with @SpringBootApplication.

**Comment by botscripter** [comment]
Thank you for your fast and kind response. I was unaware of the existence of this feature. Tested it right now and it works fabulously.

**Comment by wilkinsona** [comment]
Great. Thanks for letting us know.
