### ISSUE TITLE
Question : How to use Spring boot behind proxy?

### ISSUE THREAD

**Issue by jagatsingh** [spring-projects/spring-boot#2850]
Hi,

I have seen couple of talks related to making spring boot behind the proxy.

Can you please confirm what way works ?

I tried JAVA_OPTS settings and 

export http_proxy settings

Both ways did not work.

Thanks

**Comment by wilkinsona** [comment]
We prefer to keep this issue tracker for bugs and feature requests. Please ask this sort of question on Stackoverflow. Also, you may want to read [this section](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-behind-a-proxy-server) of the documentation.
