### ISSUE TITLE
Add documentation update for specifying sources

### ISSUE THREAD

**Issue by Shredder121** [spring-projects/spring-boot#2851]
As discussed in the [Spring Boot chat](https://gitter.im/spring-projects/spring-boot?at=5534a83b0e3138bb6be89331) I'd like to request additional documentation on specifying sources and the way `spring.main.sources` works.

**Comment by Shredder121** [comment]
Very clear now, and it's indeed what I also noticed.
Thanks!

**Comment by snicoll** [comment]
Thanks a lot for reviewing, much appreciated!
