### ISSUE TITLE
Do not auto-configure a UserDetailsService when SAML 2.0 Login is being used

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-boot#28529]
A default password is generated by Boot in a Servlet application when SAML 2.0 Login is being used.

For the OAuth2 Login feature, [it checks if a bean of type](https://github.com/spring-projects/spring-boot/blob/fbe614a61bb55bf1f0ca917600494438e5551a02/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/servlet/UserDetailsServiceAutoConfiguration.java#L72-L75) `ClientRegistrationRepository` exists to prevent the bean creation. It should do the same for the `RelyingPartyRegistrationRepository`, which is the equivalent for SAML 2.0.

To reproduce it just run [any of those samples](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/saml2) in the Spring Security samples repository and the password is printed to the console.

Related:
- https://github.com/spring-projects/spring-boot/issues/14557

**Comment by snicoll** [comment]
Closing in favor of PR #29263
