### ISSUE TITLE
Consider configuring a separate Service rather than a whole new embedded Tomcat when management.port != server.port

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2855]
I think there may be some benefits in terms of memory usage and, perhaps, the ability to easily share access log configuration, thread pools, etc.

The configuration would look a bit like this:

``` java
    @Bean
    public TomcatEmbeddedServletContainerFactory tomcatFactory() {
        return new TomcatEmbeddedServletContainerFactory() {

            @Override
            protected TomcatEmbeddedServletContainer getTomcatEmbeddedServletContainer(
                    Tomcat tomcat) {
                Server server = tomcat.getServer();

                Service service = new StandardService();
                service.setName("other-port-service");
                Connector connector = new Connector("org.apache.coyote.http11.Http11NioProtocol");
                connector.setPort(8081);
                service.addConnector(connector);
                server.addService(service);             

                Engine engine = new StandardEngine();
                service.setContainer(engine);

                Host host = new StandardHost();
                host.setName("other-port-host");
                engine.addChild(host);
                engine.setDefaultHost(host.getName());

                Context context = new StandardContext();
                context.addLifecycleListener(new FixContextListener());
                context.setName("other-port-context");
                context.setPath("");
                host.addChild(context);

                Wrapper wrapper = context.createWrapper();
                wrapper.setServlet(new MyServlet());
                wrapper.setName("other-port-servlet");
                context.addChild(wrapper);
                context.addServletMapping("/", wrapper.getName());

                return super.getTomcatEmbeddedServletContainer(tomcat);
            }
        };
    }
```

If there proves to be some benefit to this approach, we'd probably want to figure out how to do the same with Jetty and Undertow.

**Comment by joshiste** [comment]
Would the nested spring context currently used for the 2nd tomcat disappear?

**Comment by wilkinsona** [comment]
The separate context is only used when using two different ports so, yes, I think it probably would

**Comment by wilkinsona** [comment]
This is fairly straightforward for Tomcat, but more complicated for Jetty and Undertow. Jetty does [support having a single server with different apps on different ports](https://wiki.eclipse.org/Jetty/Howto/WebappPerConnector) but the recommendation is that you create two separate servers. As far as I can tell, Undertow requires two separate `Undertow` instances. We currently have a 1-to-1 mapping between a server and an embedded servlet container. This would have to change for Jetty and Undertow if we want to pursue this approach.

Another problem is the servlet context. With all three containers we'll end up with a separate servlet context but only a single application context. That would mean that `ServletContextAware` won't work as expected for something that's part of the separate management "app".

**Comment by wilkinsona** [comment]
The new endpoint infrastructure that's hopefully going to land in M4 provides a general-purpose, endpoint focussed web abstraction that's decoupled from the Servlet API. This means that the `ServletContext` is no longer a concern. We should take another look at this.

**Comment by wilkinsona** [comment]
I've got the web endpoints running in a separate context working with MVC, Jersey, and WebFlux so there's no pressing need for this.

**Comment by wilkinsona** [comment]
The benefits of doing this are outweighed by the problems [described above](https://github.com/spring-projects/spring-boot/issues/2855#issuecomment-276111309).
