### ISSUE TITLE
Setting "Embedded" Database Properties don't have an effect

### ISSUE THREAD

**Issue by thackel** [spring-projects/spring-boot#2856]
Overwriting H2 database settings does not work.

I expect that the entity manager uses the spring.datasource.* i defined in the application properties. Instead it spawns an in memory H2 db.

Sample Project: 
https://github.com/thackel/boot-database-definition-problem
In the log output you can see that the EM is being created with a tomcat-pool and and a H2 memory db.

**Comment by snicoll** [comment]
Thanks for the sample app!

**Comment by wilkinsona** [comment]
To configure the JDBC url, you should use `spring.datasource.url` and not `spring.datasource.jdbc-url`. You also need to prefix the file path with './` otherwise H2 will complain:

```
spring.datasource.url=jdbc:h2:file:./target/something;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
```
