### ISSUE TITLE
Remove support for Atomikos

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28589]

**Comment by OrangeDog** [comment]
What's the reason, and is there an upstream issue to track that would let it back in?

**Comment by wilkinsona** [comment]
The trigger was it not being compatible with Jakarta EE 9. Even if that changes we do not plan to reinstate support. Our preference is that JTA providers maintain the integration as the Narayana team now do.

**Comment by GuyPardon** [comment]
We at Atomikos now host it in our 5.0 code base and dito releases.

@wilkinsona AFAIK Jakarta EE 9 was never mentioned. What is the Spring Boot policy re Jakarta EE?

**Comment by wilkinsona** [comment]
Spring Boot 3.0, to be release in November, uses Jakarta EE 9.

**Comment by tech-consortium** [comment]
It is possible to release a Jakarta 9 version of your dependencies by using the transformer-maven-plugin from Eclipse.  We are running Atomikos on Jakarta 9 by transforming the transactions-jta and transactions-hibernate4 as shown below...

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.danshome</groupId>
    <artifactId>jakarta-transform</artifactId>
    <version>27.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>com.atomikos</groupId>
  <artifactId>transactions-jta</artifactId>
  <version>5.0.9</version>
  <packaging>jar</packaging>
  <name>Jakarta Transform - ${project.groupId}:${project.artifactId}:${project.version}</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.release>${java.version}</maven.compiler.release>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.geronimo.specs</groupId>
        <artifactId>geronimo-jms_1.1_spec</artifactId>
        <version>1.1.1</version>
      </dependency>
      <dependency>
        <groupId>com.atomikos</groupId>
        <artifactId>atomikos-transactions-essentials</artifactId>
        <version>5.0.9</version>
        <type>pom</type>
        <scope>import</scope>
        <exclusions>
          <exclusion>
            <groupId>com.atomikos</groupId>
            <artifactId>transactions-jta</artifactId>
          </exclusion>
          <exclusion>
            <groupId></groupId>
            <artifactId></artifactId>
          </exclusion>
        </exclusions>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <defaultGoal>install</defaultGoal>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <id>unpack-dependency-${project.artifactId}-${project.version}</id>
            <goals>
              <goal>unpack</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>${project.artifactId}</artifactId>
                  <version>${project.version}</version>
                  <type>jar</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <includes>**/*.*</includes>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
          <execution>
            <id>purge-dependency-${project.artifactId}-${project.version}</id>
            <goals>
              <goal>purge-local-repository</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <manualIncludes>
                <include>${project.groupId}:${project.artifactId}</include>
              </manualIncludes>
              <verbose>true</verbose>
              <reResolve>true</reResolve>
              <resolutionFuzziness>artifactId</resolutionFuzziness>
            </configuration>
          </execution>
          <execution>
            <id>copy-dependency-${project.artifactId}-${project.version}</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>${project.artifactId}</artifactId>
                  <version>5.0.9</version>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.transformer</groupId>
        <artifactId>transformer-maven-plugin</artifactId>
        <version>0.5.0</version>
        <extensions>true</extensions>
        <configuration>
          <attach>true</attach>
          <classifier>jakarta</classifier>
          <transformDirectory>${project.build.directory}</transformDirectory>
          <outputDirectory>${project.build.directory}</outputDirectory>
          <baseName>${project.artifactId}.${project.packaging}</baseName>
          <overwrite>true</overwrite>
        </configuration>
        <executions>
          <execution>
            <id>${project.artifactId}-transform</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <rules>
                <jakartaDefaults>true</jakartaDefaults>
              </rules>
              <artifact>
                <groupId>${project.groupId}</groupId>
                <artifactId>${project.artifactId}</artifactId>
                <version>${project.version}</version>
              </artifact>
              <buildDirectory>${project.build.directory}</buildDirectory>
              <packagingTypes>jar</packagingTypes>
              <type>jar</type>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.2</version>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>install</phase>
            <configuration>
              <skipIfEmpty>false</skipIfEmpty>
              <forceCreation>true</forceCreation>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by simasch** [comment]
@wilkinsona 
You said "Our preference is that JTA providers maintain the integration as the Narayana team now do."
But I cannot find any official Narayana Spring Boot integration.
