### ISSUE TITLE
Update links to Spring Security's reference documentation

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#28618]
The docs group has made some changes to how the URLs are going to be handled. Spring Boot should update spring-security attribute to point to  https://spring.io/projects/spring-security/reference

**Comment by philwebb** [comment]
Is it live yet? I get a 404 currently.

**Comment by wilkinsona** [comment]
As discussed previously, it'd also be good to have a versioned URL so that someone reading a certain version of Boot's docs is linked to the matching version of Security's docs.

**Comment by rwinch** [comment]
> Is it live yet? I get a 404 currently.

Sorry it I pointed to the incorrect URL. It should be http://docs.spring.io/spring-security/reference/

> As discussed previously, it'd also be good to have a versioned URL so that someone reading a certain version of Boot's docs is linked to the matching version of Security's docs.

The URL for a specific version is `http://docs.spring.io/spring-security/reference/{version}`

For example, http://docs.spring.io/spring-security/reference/5.6.0-RC1 is the link for 5.6.0-RC1. For now 5.6.0-RC1 is the latest release (there are no GA releases either), so it redirects to the versionless URL.

**Comment by wilkinsona** [comment]
Thanks, Rob.

We currently take the actual Security version and then remove the last `.` and anything that follows it:

https://github.com/spring-projects/spring-boot/blob/313470ac9dc8800263b67846c33c158f1b268dbb/spring-boot-project/spring-boot-docs/build.gradle#L259-L260

I think that'll continue to work although I wonder if it's exactly what we want. https://docs.spring.io/spring-security/reference/5.6.0-SNAPSHOT and https://docs.spring.io/spring-security/reference/5.6.1-SNAPSHOT are not found so it looks like we have to do something for `-SNAPSHOT` versions, but it also sounds like we could leave other versions (`5.6.0-RC1`, `5.6.0`, `5.6.1`, and so on) unchanged and they would work.
