### ISSUE TITLE
Reinstate support for Jersey

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28637]

**Comment by wilkinsona** [comment]
This is blocked until a jersey-spring6 module is available.

**Comment by wilkinsona** [comment]
There's now [a PR for a new `jersey-spring6` module](https://github.com/eclipse-ee4j/jersey/pull/5023). A local build of Jersey with those changes applied combined with [these changes to Spring Boot](https://github.com/wilkinsona/spring-boot/tree/restore-jersey-support) gets Boot's Jersey support working again.

**Comment by aspan** [comment]
Jersey 3.0.5 was released June 15th with a spring6 module. 

Available in central.
[https://repo.maven.apache.org/maven2/org/glassfish/jersey/ext/jersey-spring6/3.0.5/](https://repo.maven.apache.org/maven2/org/glassfish/jersey/ext/jersey-spring6/3.0.5/)

**Comment by wilkinsona** [comment]
Thanks, @aspan.

**Comment by wilkinsona** [comment]
Unfortunately, this is still blocked as the new `jersey-spring6` module doesn't work as expected. I've opened https://github.com/eclipse-ee4j/jersey/issues/5093.

**Comment by bdemers** [comment]
I was just looking to start integrating v3 and jersey into a project, now that https://github.com/eclipse-ee4j/jersey/issues/5093 is fixed, any idea until this will get merged back in?

**Comment by wilkinsona** [comment]
> any idea until this will get merged back in

It's out of our control at the moment and Jersey 3.0.6 has not yet been released.

**Comment by bdemers** [comment]
Doh, sorry @wilkinsona, I miss-read one of the comments on that issue.  I'll wait more patiently 😄
