### ISSUE TITLE
Short circuit @Value injection when using a source already covered by ConfigurationPropertySourcesPropertySource

### ISSUE THREAD

**Issue by ShijunDeng** [spring-projects/spring-boot#28687]
https://github.com/spring-projects/spring-boot/blob/aaad7727f0fff71b7614bbf10cf4712cd149c84b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/source/ConfigurationPropertySourcesPropertySource.java#L33

In Springboot application，ConfigurationPropertySourcesPropertySource is added to the environment and as first element, the ConfigurationPropertySourcesPropertySource acts as a facade over the existing property sources.

When handling `@Value` annotation, [org.springframework.core.env.PropertySourcesPropertyResolver#getProperty](https://github.com/spring-projects/spring-framework/blob/c705e32a887b55a746afb4c93cb4c6a031eae4c5/spring-core/src/main/java/org/springframework/core/env/PropertySourcesPropertyResolver.java#L78) will be called.
 If the property is found then ConfigurationPropertySourcesPropertySource will return the result. otherwise, PropertySourcesPropertyResolver continues to check all subsequent sources. This is a little inefficient for any source that has already been check via ConfigurationPropertySourcesPropertySource.

**Comment by philwebb** [comment]
I think we may have fixed this already with #17400 (commit 6ad100eae618cf6fde2e43fb5b39ad1fdb668988) which was added to Spring Boot 2.5. @ShijunDeng Can you check that you're using Spring Boot 2.5 or above? If you're finding an issue with that version could you please please provide a sample that shows the problem.

**Comment by ShijunDeng** [comment]
similar problem with ConfigurationPropertySourcesPropertyResolver in  [#17400](https://github.com/spring-projects/spring-boot/issues/17400).My Springboot version is 2.5.6.  ConfigurationPropertySourcesPropertyResolver is Spring boot source code, but [ org.springframework.core.env.PropertySourcesPropertyResolver#getProperty](https://github.com/spring-projects/spring-framework/blob/c705e32a887b55a746afb4c93cb4c6a031eae4c5/spring-core/src/main/java/org/springframework/core/env/PropertySourcesPropertyResolver.java#L78) is defined in spring-core. The `@Value` processor use [PropertySourcesPropertyResolver](https://github.com/spring-projects/spring-framework/blob/c705e32a887b55a746afb4c93cb4c6a031eae4c5/spring-context/src/main/java/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.java#L157). Set a breakpoint in method  [ org.springframework.core.env.PropertySourcesPropertyResolver#getProperty](https://github.com/spring-projects/spring-framework/blob/c705e32a887b55a746afb4c93cb4c6a031eae4c5/spring-core/src/main/java/org/springframework/core/env/PropertySourcesPropertyResolver.java#L78), it's easy to see that PropertySourcesPropertyResolver continues to check all subsequent sources when not found key in ConfigurationPropertySourcesPropertySource .

**Comment by ShijunDeng** [comment]
@philwebb ，hi，How is it going ？

**Comment by philwebb** [comment]
I need to dig a bit more, but I suspect [this resolver](https://github.com/spring-projects/spring-framework/blob/e9083d7d2053fea3919bfeb9057e9fdba4049119/spring-context/src/main/java/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.java#L157) is being used which doesn't support the short-circuiting.

**Comment by philwebb** [comment]
Closing in favor of PR #34900. Thanks @terminux!
