### ISSUE TITLE
Provide a property that allows defining directly the Oauth2 public key string content

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-boot#28686]
I am using spring-boot-starter-oauth2-resource-server, 
and it would be nice if we could have a property that stores the public key, without needing it to dump it into a file. 
I store it in a sealed secret and I would like to avoid having to mount it into a file. Especially because when using Spring-Cloud-Config it might be read directly as a property

Current `spring.security.oauth2.resourceserver.jwt` properties:

* `public-key-location`: is for file (and presumably not a properties one, so not mountable from configmap)
* `jwk-set-uri`: is for requesting it to a URI
* `issuer-uri`: is for requesting the token itself

I miss something like Spring security's `security.oauth2.resource.jwt.key-value`, 
so I can use it directly by  setting the property as the content string itself

**Comment by nightswimmings** [comment]
@philwebb  you know any workaround on how to mount the key from a SealedSecret property in the meantime, we would appreciate it a lot

**Comment by nightswimmings** [comment]
Would this make sense? https://github.com/spring-projects/spring-boot/issues/28714

**Comment by mbhave** [comment]
@nightswimmings Can you provide more information on why there would be a workaround required for [sealed secrets](https://github.com/bitnami-labs/sealed-secrets). From what I can tell when sealed secrets are applied to the cluster, they are unsealed and applied as regular secrets. It could then be made available to the container by creating a volume mount with an environment variable for `SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLICKEYLOCATION` pointing to that location. However, I am not very familiar with sealed secrets so I might be missing something.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by zhemaituk** [comment]
Second the request.
It's simply convenient to use strings, there is whole specter of features in Spring to work with String content.
Examples:
1. My case: Retrieve content from AWS SSM. I.e. it would look like this in properties.yaml: `public-key: ${/auth/firebase/public-key}`. The property resolves to string.
2. In spirit of 12 factor app: just pass the value via env var. It's oftentimes much easier to supply config value via string env var directly, than to create/mount a file somewhere and still supply env var with path to this file.

I guess current alternative is to write a special property resolver specifically for public-key-location, which reads from SSM (or env var), creates a file, writes public key there, and then returns path to that file, for the framework just to read it back to String.

**Comment by nightswimmings** [comment]
Sorry for being late. As stated in my original post: _I store it in a sealed secret and I would like to avoid having to mount it into a file. Especially because when using Spring-Cloud-Config it might be read directly as a property_

I don't remember the context, but it probably refers to this: https://github.com/spring-cloud/spring-cloud-kubernetes/pull/801#issuecomment-846094701

**Comment by nightswimmings** [comment]
@mbhave Does it make sense to reopen the ticket since I eventually added feedback?

**Comment by wilkinsona** [comment]
@nightswimmings We're not keen on the idea of tackling this on a property-by-property basis and would prefer a more general purpose solution like the one you proposed in #28714.

@zhemaituk #28714 may be of interest to you as well, particularly the custom `PropertyResolver` which you could hopefully use now without any changes in Boot or Framework.

**Comment by zhemaituk** [comment]
Agree, it's consistent with other places of the framework,`server.ssl.certificate` property and alike (but unlike `security.oauth2.resource.jwt.key-value` though).

Approach described in #28714 addresses more complex cases, and also gives some further ideas how to add extra "sugar" to config code. E.g. implementing a protocol resolver directly for `ssm:` or `sealed-secret:`, so in config it would look like `public-key-location: ssm:/auth/firebase/public-key`
