### ISSUE TITLE
Drop support for Jolokia until it supports Servlet 5

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28704]
https://github.com/rhuss/jolokia/issues/451

**Comment by AlexandruIovanCerqlar** [comment]
@wilkinsona are there any alternative to this? We used JMX endpoints to trigger management operations.

**Comment by wilkinsona** [comment]
Spring Boot's JMX endpoints are unaffected by this change. Dropping support for Jolokia means that general MBeans are no longer accessible over HTTP.

**Comment by adrian-baker** [comment]
> are there any alternatives to this?

As a temporary solution I was able to restore support by 
- Adding a dependency on 
  ```
  implementation "org.jolokia:jolokia-service-jmx:2.0.0-M4"
  implementation "org.jolokia:jolokia-support-jmx:2.0.0-M4" 
  ```
- Recreating the deleted `JolokiaEndpointAutoConfiguration`, `JolokiaEndpoint` and `JolokiaProperties` classes removed in  https://github.com/spring-projects/spring-boot/commit/85f9949513806d564730c2ef6e27171d9563b5dd
