### ISSUE TITLE
Consistently use quotes in YAML samples

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#28709]
As raised in #28671 we have some YAML in the docs that doesn't quote strings. I think most of the samples do so we should probably align. Using quotes helps prevent the ["norway" problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/).

**Comment by viktorardelean** [comment]
Can I work on this issue?
As a first time contributor I think this would be a good start!

**Comment by viktorardelean** [comment]
Here are all the YAML files that I found on the 2.6.x branch:

- spring-boot\spring-boot-project\spring-boot-actuator\src\test\resources\db\changelog\db.changelog-master-backup.yaml

- spring-boot\spring-boot-project\spring-boot-actuator\src\test\resources\db\changelog\db.changelog-master.yaml

- spring-boot\spring-boot-project\spring-boot-actuator-autoconfigure\src\test\resources\db\changelog\db.changelog-master.yaml

- spring-boot\spring-boot-project\spring-boot-autoconfigure\src\test\resources\hazelcast.yaml

- spring-boot\spring-boot-project\spring-boot-autoconfigure\src\test\resources\db\changelog\db.changelog-city.yaml

- spring-boot\spring-boot-project\spring-boot-autoconfigure\src\test\resources\db\changelog\db.changelog-master.yaml

- spring-boot\spring-boot-project\spring-boot-autoconfigure\src\test\resources\org\springframework\boot\autoconfigure\hazelcast\hazelcast-client-specific.yaml

- spring-boot\spring-boot-project\spring-boot-autoconfigure\src\test\resources\org\springframework\boot\autoconfigure\hazelcast\hazelcast-specific.yaml

- spring-boot\spring-boot-project\spring-boot-devtools\src\test\resources\org\springframework\boot\devtools\env\spring-devtools.yaml

- spring-boot\spring-boot-tests\spring-boot-smoke-tests\spring-boot-smoke-test-data-r2dbc-liquibase\src\main\resources\db\changelog\db.changelog-master.yaml

- spring-boot\spring-boot-tests\spring-boot-smoke-tests\spring-boot-smoke-test-liquibase\src\main\resources\db\changelog\db.changelog-master.yaml



Would adding quotes to all the spring values in those YAML files resolve this issue?

**Comment by wilkinsona** [comment]
@viktorardelean The aim of this issue is to consistently use quotes in the YAML examples in the documentation. They can be found in the various `.adoc` files within `spring-boot-project/spring-boot-docs/src/docs/asciidoc`. If you are interested in contributing the necessary changes, please use `2.6.x` as the base branch.

**Comment by viktorardelean** [comment]
@wilkinsona Thank you very much for the valuable information.
I have raised my PR: https://github.com/spring-projects/spring-boot/pull/28911

**Comment by snicoll** [comment]
Closing in favor of PR #28911
