### ISSUE TITLE
Boot documentation mistake

### ISSUE THREAD

**Issue by florianschmitt** [spring-projects/spring-boot#2871]
It seems there is a mistake in the current documentation [0]. In section 28.1.2 in the code sample it is written "**spring.datasource.driver-class-name**=com.mysql.jdbc.Driver". This seemed to work before, but after updating to Spring Boot 1.2.3.RELEASE (from 1.2.1.RELEASE) it didn't work anymore.
The entry now has to be "**spring.datasource.driverClassName**=com.mysql.jdbc.Driver", as it is written below: "For a pooling DataSource to be created we need to be able to verify that a valid Driver class is available, so we check for that before doing anything. I.e. if you set **spring.datasource.driverClassName**=com.mysql.jdbc.Driver then that class has to be loadable."

[0] http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html

**Comment by snicoll** [comment]
Relaxed binding makes it so that `driver-class-name` is equivalent to `driverClassName`. If the latter works but not the former, then it's a bug. 

Can you clarify what exact issue you're experiencing? Thanks!

**Comment by florianschmitt** [comment]
I'm sorry I can't reproduce the error anymore. The error message was the same as in [0]. My setup is eclipselink & Mysql. Sorry for the inconvenience.

[0] http://stackoverflow.com/questions/24074749/spring-boot-cannot-determine-embedded-database-driver-class-for-database-type
