### ISSUE TITLE
Update LATEST_GA for SDKMan and Homebrew tap

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28729]
After 2.5.7 has been released and before 2.6.0 is released, we should set them to `false` in `2.5.x` and `true` in `main`.

**Comment by wilkinsona** [comment]
Pipelines have been updated on Concourse as well.

**Comment by vpavic** [comment]
I think something went wrong here because SDKMAN doesn't offer me to upgrade after broadcasting the availability of `2.5.7`:

```bash
$ sdk upgrade 
==== BROADCAST =================================================================
* 2021-11-18: springboot 2.5.7 available on SDKMAN!
* 2021-11-18: springboot 2.4.13 available on SDKMAN!
* 2021-11-13: jbang 0.83.1 available on SDKMAN! https://github.com/jbangdev/jbang/releases/tag/v0.83.1
================================================================================
```

**Comment by wilkinsona** [comment]
Strange. I think I ran the job to update SDKMan before making this change but perhaps I messed up. It's offering 2.6.0 to me now so I don't think we need to correct anything: if 2.6.0 was correctly marked as the latest, 2.6.1 should receive the same treatment when it's release.
