### ISSUE TITLE
Typo in EOL date for Spring Boot 2.4.x

### ISSUE THREAD

**Issue by pontsuyo** [spring-projects/spring-boot#28743]
EOL of 2.4.x in [Supported Versions page](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#released-versions) should be revised into February **2023**, referring to the EOL description.

> Spring Boot releases are typically marked as end of support 27 months after their release.
<img width="662" alt="screenshot 2021-11-19 14 31 46" src="https://user-images.githubusercontent.com/26256187/142572957-1f758a2d-a613-4aec-be92-ed08055c1605.png">

**Comment by snicoll** [comment]
Well spotted, thanks.
