### ISSUE TITLE
dir task inputs should use relative path sensitivity

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28751]
https://github.com/spring-projects/spring-boot/blob/70e42e09c65567828a00e50041b088ab7262872f/spring-boot-project/spring-boot-actuator-autoconfigure/build.gradle#L217

This results in absolute paths being compared which breaks caching when the code is check out into different locations, as it often is on CI vs a developer's machine.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/blob/70e42e09c65567828a00e50041b088ab7262872f/spring-boot-project/spring-boot-tools/spring-boot-antlib/build.gradle#L44 should use relative sensitivity too.

**Comment by etiennestuder** [comment]
@wilkinsona As a good practice, I would always also assign a name to custom inputs. This makes it much easier in the Gradle Enterprise comparison view, in the Task details view, and in Gradle Build Tool messages to understand what property is meant.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I've opened #28753.
