### ISSUE TITLE
Command-line Initializr uses tabs in pom and code

### ISSUE THREAD

**Issue by erikv85** [spring-projects/spring-boot#28755]
The command-line version of Spring Initializr uses tabs in pom and Java code. Maven itself does not use tabs, and tabs are unusual to use for indentation in Java - Oracle, OpenJDK, Google all use spaces.

The command-line version of Spring Initializr should use spaces for indentation in generated pom.xml and Java code.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but the indentation is determined by start.spring.io and not Spring boot's client. We don't have any plans to change to spaces. Please see https://github.com/spring-io/start.spring.io/issues/505 and https://github.com/spring-io/start.spring.io/issues/392 for further details.
