### ISSUE TITLE
springboot 2.6.0 pagehelper-spring-boot-starter 1.4.0 |||| The dependencies of some of the beans in the application context form a cycle

### ISSUE THREAD

**Issue by moeyj** [spring-projects/spring-boot#28764]
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by bclozel** [comment]
Could you report this to the PageHelper project directly?

https://github.com/pagehelper/pagehelper-spring-boot/issues

Thanks!
