### ISSUE TITLE
Spring boot intializer extension error

### ISSUE THREAD

**Issue by rohigithub** [spring-projects/spring-boot#28760]
I am getting this error "Fail to create a project. Error: end of central directory record signature not found" while creating project in VS Code. Please tell me how to resolve it..
![Screenshot (1229)](https://user-images.githubusercontent.com/86924269/142729707-1e7fac21-bf06-4411-9683-66d4008344f5.png)

**Comment by snicoll** [comment]
This is the wrong place to ask for support. A quick search reveals [this page](https://code.visualstudio.com/docs/java/java-spring-boot) that redirects question to StackOverflow.
