### ISSUE TITLE
org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:null

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-boot#28763]
springboot version:2.6.0 

![image](https://user-images.githubusercontent.com/30397655/142747796-f485e88a-8371-4012-b545-743c8e7b0d86.png)

**Comment by snicoll** [comment]
I don't know where the screenshot is coming from, nor the problem you're trying to report. If you're looking for support, please ask on StackOverflow with more details. If this is a problem with a tool, this is the wrong place to report this.

**Comment by leshalv** [comment]
spring session null index key

**Comment by ruslanys** [comment]
@leshalv I believe, this is a bug, that leads to a memory leak: https://github.com/spring-projects/spring-session/issues/1987. 

I provided description and PR to fix.
