### ISSUE TITLE
Path matching breaks compatibility even spring.mvc.pathmatch.matching-strategy=ant-path-matcher

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#28769]
Springfox doesn't support `PathPatternParser`, according to https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc, we can set `spring.mvc.pathmatch.matching-strategy=ant-path-matcher` to revert the changes, It works fine.

but it fails if `spring-boot-starter-actuator` present, I guess it cause by actuator endpoints do not respect `spring.mvc.pathmatch.matching-strategy`:
> The actuator endpoints now also use PathPattern based URL matching. 

see https://github.com/springfox/springfox/issues/3934

**Comment by wilkinsona** [comment]
This has been a [known limitation of Spring Fox for over a year](https://github.com/springfox/springfox/issues/3462). Unfortunately, we can't continue to make compromises in Boot to maintain compatibility for a library that doesn't appear to be maintained any more. As [suggested by @hpoettker](https://github.com/spring-projects/spring-boot/issues/24645#issuecomment-958006383), I've updated the release notes to mention the compatibility problem and link to Springfox issue.
