### ISSUE TITLE
Improve deprecation notice on ResourceProperties to direct people to WebProperties for dependency injection and then getResources()

### ISSUE THREAD

**Issue by bjornharvold** [spring-projects/spring-boot#28762]
After upgrading from Spring Boot 2.5.6 to Spring Boot 2.6.0, my Spring Web Flux reactive app fails to start due to my global error web exception handler.

```
public class GlobalErrorWebExceptionHandler extends AbstractErrorWebExceptionHandler {
    @Autowired
    public GlobalErrorWebExceptionHandler(ErrorAttributes errorAttributes,
                                                 WebProperties.Resources resources,
                                                 ApplicationContext applicationContext,
                                                 ServerCodecConfigurer serverCodecConfigurer) {
        super(errorAttributes, resources, applicationContext);
        super.setMessageWriters(serverCodecConfigurer.getWriters());
        super.setMessageReaders(serverCodecConfigurer.getReaders());
    }
}
```

Parameter 1 of constructor in io.trippay.platform.web.TripPayGlobalErrorWebExceptionHandler required a bean of type 'org.springframework.boot.autoconfigure.web.WebProperties$Resources' that could not be found.

I looked at the migration document and there are not clues to what changed or what should be done to mitigate this issue.

Thank you

**Comment by yu-shiba** [comment]
I had a similar problem.

```
@Configuration
public class WebMvcConfig implements WebMvcConfigurer {
    private static final String[] VERSION_PATTERNS = { "/plugins/**", "/img/**", "/css/**", "/js/**" };

    @Autowired
    Resources resources;

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        VersionResourceResolver versionResolver = new VersionResourceResolver()
                .addContentVersionStrategy(VERSION_PATTERNS);

        // enable fingerprint
        registry.addResourceHandler("/**")
                .addResourceLocations(resources)
                .setCachePeriod(3600 * 24 * 30)
                .resourceChain(true)
                .addResolver(versionResolver);
    }
}
```

I think there is a similar problem with Web Mvc.

**Comment by snicoll** [comment]
It isn't a regression. `ResourceProperties` (which is the one that was bound to `spring.resources`) is deprecated since Spring Boot 2.4. This deprecated code was removed in 2.6 as we usually do.

The tricky thing here is that `ResourceProperties` extends from `Resources` so injecting the latter worked. If you need to access resources information, you need to inject `WebProperties` and access its `getResources` accessor. I've [added a note in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#web-resources-configuration)

**Comment by wilkinsona** [comment]
I think we should improve the deprecation in 2.5.x to point people to `WebProperties` and then `getResources()` rather than just pointing them to `WebProperties.Resources`.

**Comment by bjornharvold** [comment]
Cheers Andy 🍻

**Comment by vedhavi** [comment]
> It isn't a regression. `ResourceProperties` (which is the one that was bound to `spring.resources`) is deprecated since Spring Boot 2.4. This deprecated code was removed in 2.6 as we usually do.
> 
> The tricky thing here is that `ResourceProperties` extends from `Resources` so injecting the latter worked. If you need to access resources information, you need to inject `WebProperties` and access its `getResources` accessor. I've [added a note in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#web-resources-configuration)

@snicoll Some people cannot understand how this has to be done. It would be great if you can mention a sample in your release notes. I am not sure how many people understood, but I did not. Not everyone is used to Spring terms as we are using the api and not developing them.

**Comment by vedhavi** [comment]
> It isn't a regression. `ResourceProperties` (which is the one that was bound to `spring.resources`) is deprecated since Spring Boot 2.4. This deprecated code was removed in 2.6 as we usually do.
> 
> The tricky thing here is that `ResourceProperties` extends from `Resources` so injecting the latter worked. If you need to access resources information, you need to inject `WebProperties` and access its `getResources` accessor. I've [added a note in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#web-resources-configuration)

An example would help people  better. So adding to @snicoll 's comments, as some people like me will not be able to grab it at the very first instant

For instance.

Spring boot 2.5.7 
public JHExceptionHandler(ErrorAttributes errorAttributes, **Resources resources**,
			ApplicationContext applicationContext, ServerCodecConfigurer configurer) {
		super(errorAttributes, **resources**, applicationContext);
		this.setMessageWriters(configurer.getWriters());
	}
Spring boot 2.6.0
public JHExceptionHandler(ErrorAttributes errorAttributes, **WebProperties webproperties**,
			ApplicationContext applicationContext, ServerCodecConfigurer configurer) {
		super(errorAttributes, **webproperties.getResources()**, applicationContext);
		this.setMessageWriters(configurer.getWriters());
	}

**Comment by UDragon-CK** [comment]
@Slf4j
@Configuration
public class NrpWebPropertiesConfiguration {

    @Bean
    public WebProperties.Resources resources() {
        return new WebProperties.Resources();
    }

}


---------------------------

    public WebFluxGlobalExceptionHandler(ErrorAttributes errorAttributes
      , NrpWebPropertiesConfiguration nrpWebPropertiesConfiguration
      , ApplicationContext applicationContext
      , ServerCodecConfigurer serverCodecConfigurer) {
        super(errorAttributes, nrpWebPropertiesConfiguration.resources(), applicationContext);

        super.setMessageWriters(serverCodecConfigurer.getWriters());
        super.setMessageReaders(serverCodecConfigurer.getReaders());
    }
