### ISSUE TITLE
Replace pl.project13.maven:git-commit-id-plugin 4.x with io.github.git-commit-id:git-commit-id-maven-plugin 5.x

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-boot#28775]
According to [git-commit-id-maven-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin) `io.github.git-commit-id:git-commit-id-maven-plugin` 5.x is the successor of `pl.project13.maven:git-commit-id-plugin` 4.x.

Spring Boot Dependencies currently manages `pl.project13.maven:git-commit-id-plugin` 4.x.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we cannot switch to 5.x just yet as it requires Java 11 and Spring Boot 2.x has a Java 8 baseline. We'll upgrade to 5.x in due course as part of Spring Boot 3.0.

**Comment by breun** [comment]
Ah right, I missed that Java 11 requirement. Makes sense. 👍
