### ISSUE TITLE
Add java.vendor.version to JavaInfoContributor

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-projects/spring-boot#28777]
There was a question about adding the `java.vendor.version` property to `JavaInfoContributor`: https://github.com/spring-projects/spring-boot/pull/28136#issuecomment-975536848 originally raised by @dmengelt.

I'm opening this issue to see/discuss what the community and the Boot Team thinks about adding this property. I ran some tests (see: https://github.com/spring-projects/spring-boot/pull/28136#issuecomment-976041679) and there are a good amount of cases where the property is missing (was introduced in Java 10) or it does not make sense (see my comment).

It also seems that they wanted to remove the property but the community found it useful so they kept it (see: https://github.com/spring-projects/spring-boot/pull/28136#issuecomment-976048372). Based on these I would say that the property makes sense mostly for the Zulu and the Corretto images (11 and 17, not 8) and might make sense for more distributions in the future.

**Comment by wilkinsona** [comment]
This sounds like a good idea to me. It sounds like it'll provide useful information in some situations and that it'll be harmless in others.

**Comment by jonatan-ivanov** [comment]
What do you think about moving from this:
```json
"java": {
    "vendor": "Eclipse Adoptium",
    "version": "17.0.1",
    "runtime": {
        "name": "OpenJDK Runtime Environment",
        "version": "17.0.1+12"
    },
    "vm": {
        "name": "OpenJDK 64-Bit Server VM",
        "vendor": "Eclipse Adoptium",
        "version": "17.0.1+12"
    }
}
```

to this:
```json
"java": {
    "version": "17.0.1",
    "vendor": {
        "name": "Eclipse Adoptium",
        "version": "Temurin-17.0.1+12"
    },
    "runtime": {
        "name": "OpenJDK Runtime Environment",
        "version": "17.0.1+12"
    },
    "vm": {
        "name": "OpenJDK 64-Bit Server VM",
        "vendor": "Eclipse Adoptium",
        "version": "17.0.1+12"
    }
}
```

This is a breaking change since the vendor fields was a String before and now it is an object, everything else is the same.

**Comment by snicoll** [comment]
Closing in favor of PR #29090
