### ISSUE TITLE
QuartzDataSourceScriptDatabaseInitializer does not provide a mapping for MariaDB

### ISSUE THREAD

**Issue by ztomic** [spring-projects/spring-boot#28773]
`DatabaseDriver.MYSQL` is added two times.  Probably one extra line or missing `DatabaseDriver.MARIADB`.

https://github.com/spring-projects/spring-boot/blob/196c92e12c423fbab31c19f9e894b0e568ecda09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/quartz/QuartzDataSourceScriptDatabaseInitializer.java#L71
https://github.com/spring-projects/spring-boot/blob/196c92e12c423fbab31c19f9e894b0e568ecda09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/quartz/QuartzDataSourceScriptDatabaseInitializer.java#L72

**Comment by wilkinsona** [comment]
Well spotted. Thank you. One line should be for `MARIADB` to align with the behaviour of the deprecated `QuartzDataSourceInitializer`:

https://github.com/spring-projects/spring-boot/blob/196c92e12c423fbab31c19f9e894b0e568ecda09/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/quartz/QuartzDataSourceInitializer.java#L76

**Comment by wilkinsona** [comment]
Closing in favor of #28779.
