### ISSUE TITLE
Warn about the dangers of early bean initialization when using @ConditionalOnExpression

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28771]
Referencing a bean in `@ConditionalOnExpression` will cause the bean to be initialized very early in context refresh processing. This can cause problems such as [this one](https://github.com/spring-projects/spring-framework/issues/27718). We should add a warning about this to the annotation's javadoc and, perhaps, somewhere in the references docs as well.

**Comment by mihailcornescu** [comment]
Hi. Can I take care of this one?

**Comment by wilkinsona** [comment]
Yes please, @mihailcornescu. That'd be great. Please let us know if you have any questions.

**Comment by mihailcornescu** [comment]
Yeah, sure.

**Comment by mihailcornescu** [comment]
@wilkinsona I have raised PR #29276 . What do you think of it?

**Comment by mihailcornescu** [comment]
It looks like there are some check failures. I will fix them and I will come back.

**Comment by philwebb** [comment]
Closing in favor of PR #29276. Thanks @mihailcornescu!
