### ISSUE TITLE
Drop support for CommonsMultipartResolver as it has been removed in Spring Framework 6

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28782]

**Comment by john17797** [comment]
What is the alternative class for CommonsMultipartResolver after this class has been removed?

**Comment by bclozel** [comment]
You should use the `StandardServletMultipartResolver` instead now. This should be auto-configured by Spring Boot anyway. See [the Spring Framework upgrade guide](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#web-applications-1) on that.
