### ISSUE TITLE
Port number out of range: null:-1

### ISSUE THREAD

**Issue by lyh8577** [spring-projects/spring-boot#28783]
### Env
-spring-boot: 2.6.0
-java: 17

### Examaple

- application.yml
```
spring:
  elasticsearch:
    uris: http://elasticsearch_host:9200
```
org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration.ConsolidatedProperties#getEndpoint(URI) returns null:-1

**Comment by wilkinsona** [comment]
This looks like a configuration error to me as `_` is an invalid character in a hostname. You can see this with the following code:

```java
URI uri = URI.create("http://elasticsearch_host:9200");
System.out.println(uri.getHost());
System.out.println(uri.getPort());
```

It produces the following output:

```
null
-1
```
