### ISSUE TITLE
Drop support for embedding EhCache 3 until it supports Jakarta EE 9

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28800]
https://github.com/ehcache/ehcache3/issues/2946

**Comment by linghengqian** [comment]
Not sure if this should be answered here. But according to https://github.com/ehcache/ehcache3/issues/2946#issuecomment-1033796898, EHCache already supports Jakarta EE namespace.

**Comment by wilkinsona** [comment]
Thanks. We're already aware of that issue and its developments. As it describes, they published "an early alpha" a couple of weeks ago with EE 9 support but "there is no set schedule for a GA of that right now". We'll hopefully reinstate support for EhCache 3 once things have settled down a bit more.

**Comment by chrisdennis** [comment]
@wilkinsona Right now the pre-release version of Ehcache 3.10.0 that support Jakarta only switched to Jakarta for JAXB (XML config parsing usages). The transactions module has not yet been released in a form that supports the Jakarta namespaces JTA spec. Would that also be a requirement for restoring support in spring-boot?

**Comment by wilkinsona** [comment]
Thanks, @chrisdennis. It would, yes. We need all of Ehcache's modules to be Jakarta EE 9-compatible before we can restore support.
