### ISSUE TITLE
Java version sticks to 11 when choosing kotlin on start.spring.io 

### ISSUE THREAD

**Issue by m-kay** [spring-projects/spring-boot#28820]
When the combination of Spring-Boot 2.6.0, Language Kotlin and Java 17 is selected on start.spring.io in the generated pom.xml the property `java.version` is still configured to 11. According to the Kotlin docs JVM target 17 is supported in Version 1.6.0, see https://kotlinlang.org/docs/whatsnew16.html#kotlin-jvm.

**Comment by wilkinsona** [comment]
Thanks for raising this. I've opened https://github.com/spring-io/start.spring.io/issues/803.
