### ISSUE TITLE
Update system tests following release of Paketo Java buildpack 6.0.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28823]
System tests are failing due to unexpected appearance of `paketo-buildpacks/syft`. It was added to the Java buildpack in https://github.com/paketo-buildpacks/java/pull/370.

**Comment by scottfrederick** [comment]
In addition to the new `paketo-buildpacks/syft` being included, the latest release of the Java composite buildpack [removes support for the BOM](https://github.com/paketo-buildpacks/java/issues/3#issuecomment-981859856) that the system tests verify.
