### ISSUE TITLE
Upgrade to Spring Integration 4.2

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2883]
This is a prerequisite for upgrading to Reactor 2.0.x

**Comment by nomack84** [comment]
@wilkinsona This is a duplicate of #2728.

**Comment by wilkinsona** [comment]
Oops. Thank you. As this issue has been referenced in a commit, I'll close the other one.

**Comment by snicoll** [comment]
We're already using the latest, moving to RC1

**Comment by wilkinsona** [comment]
This was taken care of in https://github.com/spring-projects/spring-boot/commit/2a779db74dd6888d8928e0a86f2872f568d06b56. See #3944.
