### ISSUE TITLE
Add server.netty.max-keep-alive-requests

### ISSUE THREAD

**Issue by philsttr** [spring-projects/spring-boot#28848]
A new `maxKeepAliveRequests` property was added to the http server in reactor-netty v1.0.13 (https://github.com/reactor/reactor-netty/issues/1865 / https://github.com/reactor/reactor-netty/pull/1867)

It would be great if spring boot allowed the `maxKeepAliveRequests` to be configured via a `server.netty.max-keep-alive-requests` property, similar to the other reactor-netty server properties.

**Comment by philwebb** [comment]
Closing in favor of PR #28875. Thanks @polarbear567!
