### ISSUE TITLE
Simplify SecurityAutoConfiguration

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#28851]
We have a number of imports which can be combined into a single class for web-related configuration. See https://github.com/mbhave/spring-boot/commit/f5cf32b0da3b8717ecd08c2c6e2c4a3b6b32eed8#diff-27ebc3922f67a14f19477eb1b5e39dbb67291e377cad17eefd26f2293045ef38.

**Comment by KishkinJ10** [comment]
Hi , I have worked on some spring projects , can you guide me how should I go with this issue ??

**Comment by mbhave** [comment]
@KishkinJ10 Thanks for the offer but I already had a commit lined up for this one which I just needed to cherry pick.
