### ISSUE TITLE
AbstractMethodError in org.springframework.boot.web.servlet.filter.ErrorPageSecurityFilter 

### ISSUE THREAD

**Issue by Artur-** [spring-projects/spring-boot#28854]
Running a Spring Boot 2.6.1 project in Jetty 9 results in

```
java.lang.AbstractMethodError: Receiver class org.springframework.boot.web.servlet.filter.ErrorPageSecurityFilter does not define or inherit an implementation of the resolved method 'abstract void init(javax.servlet.FilterConfig)' of interface javax.servlet.Filter.
```

`javax.servlet.Filter` has a default `init` implementation in Servlet 4 but not in 3.1 so is looks like the class depends on Servlet 4 API yet I see nothing in the upgrade guide about dropping Servlet 3 support.

**Comment by mbhave** [comment]
Closing in favor of PR #28902.
