### ISSUE TITLE
OnExpressionCondition does not use standard boolean coercion

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2886]
SpEL expressions are usually evaluated truthily, but the `OnExpressionCondition` uses a hard cast to `Boolean` followed by an implicit unboxing. I tried to use a condition that evaluated to `null`, usually interpreted as false in SpEL, and got an NPE at `OnExpressionCondition:59`. If the condition can't be retrofitted to use conventional EL truthiness, then the documentation ought to explain that the condition needs to return a boolean, and the NPE should probably be defended against.

**Comment by philwebb** [comment]
Closing in favor of PR #8128
