### ISSUE TITLE
@EnableConfigurationProperties is not evaluated before expressions

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2887]
I have an autoconfiguration class that uses `@EnableConfigurationProperties` and another autoconfiguration, explicitly ordered after the first one, that attempts to use the `ConfigurationProperties` bean in an expression condition. The bean is not available at that point, and the expression evaluation throws various errors depending on how I try to name it.

**Comment by chrylis** [comment]
On further investigation, this may be an issue with misunderstanding the bean naming for `ConfigurationProperties` classes. Are beans not named using the standard lowerCamelCase convention for components? If not, how are they named? (The documentation shows injection by type, but I'm needing to get them from SpEL in several places, including Thymeleaf templates.)

**Comment by chrylis** [comment]
Looks like the bean is named `prefix.CONFIGURATION_PROPERTIES`. It would be helpful to note this in the documentation.

**Comment by snicoll** [comment]
Granted. Why do you rely on the name?

**Comment by chrylis** [comment]
SpEL expression conditions (since there's no type-safe way to refer to anything inside a `ConfigurationProperties`), injection of global properties (e.g., Google Analytics property ID) into HTML templates (the alternative would be adding them to the model in every controller in the application).

**Comment by snicoll** [comment]
Uh? Why do you need the name of the bean for that? Can't you use the property key?

Show an example please.

**Comment by chrylis** [comment]
Can't use the property key because I'm relying on relaxed binding to adapt onto bash-safe environment variables, which are the only simple way to do per-deployment configuration on Cloud Foundry. I'm using properties and/or YAML in development, but the only way to get files into the CF deployment is to build them into the jar (and have them in source control or manually copied during build) or to use a custom buildpack just for them.

**Comment by chrylis** [comment]
This does appear to be accurate as initially titled; I'm now asking for the proper bean name, and I'm getting a `NoSuchBeanDefinitionException`.

**Comment by snicoll** [comment]
> Show an example please.

**Comment by chrylis** [comment]
This is essentially what my initial attempt at the class was:

```
@ConfigurationProperties(prefix = 'aws')
class AmazonCredentials {
    static class Credential {
        String accessKey
        String secretKey
    }

    Map<String,Credential> credentials
}
```

This works fine with YAML or properties:

```
aws.credentials[s3upload].accessKey: AK1234
aws.credentials[s3upload].secretKey: foobar
```

But there's no way to express the traversal in bash-safe terms.

**Comment by chrylis** [comment]
This is the autoconfiguration class that's failing. Both classes are explicitly listed in `spring.factories` and getting loaded from there.

```
@Configuration
@EnableConfigurationProperties(AwsCredentials.class)
public class S3AutoConfiguration {

    @Configuration
    public static class PolicySignerConfig {
        @Bean
//        @ConditionalOnExpression("#{'artsquare.aws.CONFIGURATION_PROPERTIES'}.fineUploader.set")
        public S3PolicySigner s3PolicySigner(AwsCredentials awsCredentials) {
            // this return line has had a lot of variations; this is the one that I finally settled on with hard-coded intermediate keys
            return new S3PolicySignerImpl(awsCredentials.getFineUploader().awsCredentials());
        }
    }
}
```

**Comment by snicoll** [comment]
If `@ConditionalOnProperty` with `prefix` and `value` does not work as you expect, we should fix that then. Have you tried?

**Comment by chrylis** [comment]
I hadn't seen that `@ConditionalOnProperty` supported relaxed binding, so I will give that a try. That said, I really want to be able to call a method on the `ConfigurationProperties` object that inspects the (multiple) properties provided rather than simply using a presence/absence test.

**Comment by wilkinsona** [comment]
@chrylis What's the status of this issue? Did you try `@ConditionalOnProperty`?

Reading the above, the exact problem isn't very clear to me. If you're still experiencing it, can you please provide a small sample so that we can be sure we're all on the same page?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
