### ISSUE TITLE
Remove image banner support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#28883]
Image banners rely on awt classes to convert the gif/png/jpeg file to text, they are also convert the image on each run of the application. It would probably be better to remove support and instead offer a tool that can be run once to convert an image to a banner files. It would also help solve the "headless" issue identified in #28803

**Comment by rudy2steiner** [comment]
Let me try this!

**Comment by joshlong** [comment]
I understand the reasoning. It makes good sense. But I am sad.
