### ISSUE TITLE
Issue in using Flux/ParallelFlux with 2.3.5 version of springboot

### ISSUE THREAD

**Issue by RB2601** [spring-projects/spring-boot#28888]
Hi Team,

The Flux returned by method ( having produces = MediaType.TEXT_EVENT_STREAM_VALUE) does not display all data in browser when Flux is of non-primitive datatype. However, it works perfectly in other version(new and old) of spring-boot  except in 2.3.5 version. However, if create a flux of primitive data type, it works perfectly.
e.g below code wont display all values of list. It will display only one.
@GetMapping(path = "/stream-flux", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
public Flux<CustomDto> streamFlux() {
    return Flux.fromIterable(list);
}

**Comment by wilkinsona** [comment]
Spring Boot 2.3.5 has [reached the end of its OSS support period](https://spring.io/projects/spring-boot#support). Please upgrade to a supported version (2.5.x or 2.6.x), particularly given that you already know that things work as you'd like in versions newer than 2.3.5.
