### ISSUE TITLE
spring-boot:build-image downloads BellSoft Liberica JRE 8.0.312 so slowly, how to resolve it?

### ISSUE THREAD

**Issue by JamesTaylor04** [spring-projects/spring-boot#28885]
- Question
  When executing spring-boot:build-image, the docker server downloads **BellSoft Liberica JRE 8.0.312** so slowly, how to resolve this problem?
- Exception
  
![image](https://user-images.githubusercontent.com/46660297/144343719-621f07aa-ec70-4214-b2e0-6c71836dd510.png)

**Comment by scottfrederick** [comment]
Spring Boot does not download the JRE when building an image. It invokes the [Paketo](https://paketo.io) CNB builder and buildpacks, and the buildpacks download any artifacts required for the image. You can view the [Paketo documentation](https://paketo.io/docs/) for details on how to customize the buildpack behavior. There is a [section in the documentation](https://paketo.io/docs/howto/configuration/#building-behind-a-firewall) that discusses techniques for configuring alternative download locations.

**Comment by JamesTaylor04** [comment]
Thanks, Mr scottfrederick! According to your suggestion, I have solved the problem, and I provide the solution below and hope this will give others a little help. There are two ways to resolve the problem:
- Firstly, also the simplest way, is to upgrade your **spring-boot-maven-plugin**, make sure **>= version 2.6.0**
  then, you have to reference the [section in the documentation ](https://paketo.io/docs/howto/configuration/#building-behind-a-firewall)

1. provide the configuration in your project root directory
  
  ![image](https://user-images.githubusercontent.com/46660297/144526225-5037d17f-d0dd-4ad1-b019-588ef3c34aff.png)
  
  the type file's content is

  ![image](https://user-images.githubusercontent.com/46660297/144526389-4564eba1-4496-47a9-99ee-f5ce4216ebea.png)
  
  the sha256 file's content is your custom url of JRE

  ![image](https://user-images.githubusercontent.com/46660297/144526588-1e0153af-ea61-4806-9460-ea94d95b253f.png)

2. copy platform directory to your docker host, and put it in your custom location, here I put it in _/home/ws/pack/_
![image](https://user-images.githubusercontent.com/46660297/144528041-f0673a6f-02d2-40b3-8f72-9bb494ba54a1.png)

3. in your maven pom file, put this code into _image_ element of spring-boot-maven-plugin's configuration element
![image](https://user-images.githubusercontent.com/46660297/144527887-3127268b-9f9b-4ace-9d8c-0d0d1d1fddfd.png)

- Secondly, also the complicated way, is to create your own buildpack and use it, you can have a try
