### ISSUE TITLE
gradle构建失败

### ISSUE THREAD

**Issue by bladeandmaster88** [spring-projects/spring-boot#28898]

**Comment by bladeandmaster88** [comment]
springboot从2.2.2开始从maven构建变成了gradle，但是gradle构建太多错了，不知道为何要用gradle，还是觉得maven好用；希望能改回maven构建

**Comment by snicoll** [comment]
Courtesy of Google Translate:
> Springboot has changed from maven build to gradle since 2.2.2, but there are too many gradle builds wrong, I don’t know why gradle is used, I still think maven is easy to use; I hope to change back to maven build 

@bladeandmaster88 us using Gradle or Maven to build Spring Boot should not have any impact on you to build applications with either. If you're looking to contribute and need help with Gradle, please consider reviewing  [Working on the Code](https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code) on our Wiki.
