### ISSUE TITLE
Spring boot takes more than ten minutes to start

### ISSUE THREAD

**Issue by zzalyp** [spring-projects/spring-boot#28896]
Through the debug log, it is found that spring repeatedly outputs "start / end expire sessions standardmanager" after executing "hibernate running scheme vaidator" at startup, resulting in slow startup. I have tried several methods to avoid this problem
1. Create a new database for my spring, but it is invalid
2. Increase the memory setting, which is still invalid
3. This problem only occurs in the formal environment, and there is no problem in the development and testing environment
------------------------------------------------------------------------------------------------------------------------------------------
spring boot ：1.5.21.RELEASE
[https://i.stack.imgur.com/auJ9i.png](url)

**Comment by bclozel** [comment]
Spring Boot 1.5.x [has been EOL for a while now](https://spring.io/projects/spring-boot#support). Please upgrade to a supported version (2.5.x or 2.6.x). Note that the problem you're seeing might not be linked to the session manager logs but rather another problem. Maybe changing your log configuration could show more information.
