### ISSUE TITLE
@Deprecated How to use this method for document annotation is abandoned

### ISSUE THREAD

**Issue by Jzow** [spring-projects/spring-boot#28908]
For example, I want to tell other engineers that this method has been eliminated, but I see that the @deprecated annotation only has since() and forRemoval(). Do I need to use Java doc to explain it?

```
    @Override
    @Deprecated
    public TchCommentClassDetailBO queryCommentClassInfoByCommentId(String commentId) {
        TchCommentClassDetailBO tchCommentClassDetailBO = TchCommentClassModelMapper
                .INSTANCE.convertEntityToBO(tchCommentClassDetailService.queryCommentClassInfoByCommentId(commentId));

        tchCommentClassDetailBO.setCommentModuleScoreBOList(JSONArray.parseArray(String.valueOf(tchCommentClassDetailBO.getWrittenScore()), CommentModuleScoreBO.class));
        tchCommentClassDetailBO.setOralTestScoreBO(JSONObject.parseObject(tchCommentClassDetailBO.getOralTestScore(), CommentModuleScoreBO.class));

        return Optional.ofNullable(tchCommentClassDetailBO)
                .orElse(null);
    }
```

**Comment by Jzow** [comment]
I'm thinking about the effect of adding markdown in the @ deprecated annotation, although my idea seems a little abnormal :)

**Comment by mdeinum** [comment]
The @deprecated annotation isn't a Spring annotation it is from Java (if you check it is from `java.lang`. So not sure what Spring (Boot) can add here. If you look at the framework documentation there is an `@Deprecated` java annotation as well as an @deprecated javadoc annotation which then provides the documentation. 

One example is, for instance, the [`RmiServiceExporter` ](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/remoting/rmi/RmiServiceExporter.html). Which has both annotations, one for documentation the other for instructing the compiler.

**Comment by bclozel** [comment]
Closing this, as this is not strictly related to Spring Boot.

**Comment by Jzow** [comment]
@mdeinum thanks
