### ISSUE TITLE
Extends Additional Path on Main or Management Port for actuator endpoints

### ISSUE THREAD

**Issue by wyfrel** [spring-projects/spring-boot#28914]
In springboot 2.6.x it's now possible to expose health groups on an additional path but it's not yet possible to do the same for an endpoint.

It would be great to have the same functionality for an entire (custom) endpoint without creating healthgroups

**Comment by wilkinsona** [comment]
Can you please explain why you think it would be great to support this for other endpoints? There are some compelling reasons to support accessing health information on the main port (see https://github.com/spring-projects/spring-boot/issues/25471 for some discussion of those) but those arguments don't really apply to other endpoints.

**Comment by wyfrel** [comment]
Hello, 

First of all thank you for your reply.

I've got a custom actuator endpoints which expose healthIndicator status in a custom XML format. This endpoint is used by my company monitoring tool.

 When the management port is changed (eg : for metrics collection ) this impact also the mycustom endpoint. With this enhancement i would be able to exposing it on the server port and it would avoid to define a new ingress route for the custom actuator endpoint

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
