### ISSUE TITLE
Fix documented default value for property `spring.mvc.pathmatch.matching-strategy`

### ISSUE THREAD

**Issue by aaguilera** [spring-projects/spring-boot#28936]
Spring Boot 2.6.x documentation states that the default value for property `spring.mvc.pathmatch.matching-strategy` is `ant-path-matcher`, but it's actually `path-pattern-parser`.

Documentation:

https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/application-properties.html#application-properties.web.spring.mvc.pathmatch.matching-strategy

Source code:

https://github.com/spring-projects/spring-boot/blob/756b9b9254ec4b09f46aba110ca837b50f7d7a92/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcProperties.java#L404

**Comment by snicoll** [comment]
Thanks for the report, the manual meta-data for the default value wasn't updated.
