### ISSUE TITLE
Platform used for Quartz, Session, Integration, and Batch schema initialization cannot be configured

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28932]
At the moment, it's only possible to derive the platform from the `DataSource`. This is a bit limiting. For example it means that the default schema location cannot be used with a database that isn't known to `DatabaseDriver`. The problem can be avoiding by configuring the schema location, for example by replacing the default location of `"classpath:org/springframework/integration/jdbc/schema-@@platform@@.sql"` with `"classpath:org/springframework/integration/jdbc/schema-sybase.sql"` but it would be easier if just the platform could be configured without having to worry about the actually location of the schema scripts.

**Comment by snicoll** [comment]
While working on this, I've realized that things have heavily changed in `2.6.x` and I am not sure how to handle it there yet.
