### ISSUE TITLE
Info Actuator - Custom Properties not returned - Spring Boot 2.6.0-2.6.1

### ISSUE THREAD

**Issue by buyukim** [spring-projects/spring-boot#28933]
We have a Spring Boot application that we just upgraded from Boot 2.5.6 to  2.6.0/2.6.1 and noticed that calling the actuator/info endpoint no longer returns custom info properties like it used to.

Here is some sample application.yaml config that we would expect to see:
```yaml
info:
  app.application-name: ${spring.application.name}
  app.image-version: ${DOCKER_IMAGE_TAG:local}
```
Right now, we are only seeing the following response:
```json
{
  "git" : { },
  "activeProfiles" : [ "local" ]
}
```
Note: not sure if this is related, but our app is still using spring-cloud-bootstrap.   There is no actuator config inside the boostrap.yaml, though.

**Comment by wilkinsona** [comment]
Have you [enabled the `env` info contributor](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default)?

**Comment by buyukim** [comment]
🤦 
Yeah, that fixed it.  Sorry about that!
