### ISSUE TITLE
DataSourceScriptDatabaseInitializer may still try to access the database even though its initialization mode is never

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28931]

**Comment by snicoll** [comment]
I am looking at this issue and I am not able to reproduce the problem in a unit test. I can see the `isEnabled` check inconsistency with `AbstractDataSourceInitializer` but I fail to see where the `DataSource` would be accessed to resolve the scripts. `AbstractScriptDatabaseInitializer` does not have `@@platform@@` support as far as I can see... 

I can move the check to make it more consistent but I'd like someone else to have a look in case I missed something.

**Comment by snicoll** [comment]
I think 2.5.x is fine and the regression is in 2.6.x where we use `DataSourceScriptDatabaseInitializer` and its settings are commuted upfront. I'll edit the title of the issue accordingly.
