### ISSUE TITLE
memory overflow in org.springframework.boot.loader.LaunchedURLClassLoader

### ISSUE THREAD

**Issue by 411937647** [spring-projects/spring-boot#28935]
spring boot version: 2.3.6.RELEASE

The application's memory footprint was always high, so I downloaded the memory dump file and used mat's analysis results to point to the classloader 。

![图片](https://user-images.githubusercontent.com/21364503/145369804-be7962b8-27ba-461f-83da-52e91cce30d8.png)
![图片](https://user-images.githubusercontent.com/21364503/145369957-9591e148-bec1-4f60-b8af-086dec32585a.png)
![图片](https://user-images.githubusercontent.com/21364503/145370026-14ba2be8-2d1c-4394-a79f-f053b34964fb.png)
![图片](https://user-images.githubusercontent.com/21364503/145370098-af8f5c43-4c77-4f74-a1b7-43130d742bfc.png)
![图片](https://user-images.githubusercontent.com/21364503/145370161-70c08f7e-bbbe-4112-9dbd-cc56be969a86.png)

**Comment by wilkinsona** [comment]
Thanks for the report but I can't see anything unusual here. `LaunchedURLClassLoader` has loaded the classes for 30,037 objects and those objects are consuming 79,957,808MB of heap. I don't think that indicates that there's a problem with the class loader. There may be a problem with the classes that it's loaded but it could equally be normal behaviour: it's impossible to tell from the information you've provided thus far.

Please note that Spring Boot 2.3.6 has [reached the end of its OSS support period](https://spring.io/projects/spring-boot#support). Please upgrade to Spring Boot 2.5.x or 2.6.x. If the problem that you are seeing remains once you have upgraded, please explain why you believe there's a problem with `LaunchedURLClassLoader`.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by 411937647** [comment]
Thank you for your reply. I will reorient my question.

**Comment by mmylili** [comment]
> Thank you for your reply. I will reorient my question.
so, at the last, whats the problem?
