### ISSUE TITLE
[Docs] Missing Spring Boot compatibility guide for Spring Cloud 2021 serial in https://spring.io/projects/spring-cloud

### ISSUE THREAD

**Issue by DevDengChao** [spring-projects/spring-boot#28968]
In document https://spring.io/projects/spring-cloud#adding-spring-cloud-to-an-existing-spring-boot-application 's `Table 1. Release train Spring Boot compatibility` section, there is no guiding for Spring Cloud 2021 serial is compatable with which version of Spring Boot like other Spring Cloud serials:

![image](https://user-images.githubusercontent.com/16363180/145526099-65d90331-c6ca-4d84-877d-c1a10fa6c788.png)

Ps: I found the compatiable Spring Boot version later in https://docs.spring.io/spring-cloud/docs/2021.0.0/reference/html/ .

Sorry that I didn't found the website's repository and opened it here. 
If it is needed, I'll close this and re-open another if someone told me the correct repository.

**Comment by snicoll** [comment]
@DevDengChao Thanks for the report but this is the Spring Boot issue tracker, not the Spring Cloud issue tracker. I suggest reporting this against https://github.com/spring-cloud/spring-cloud-release and the Spring Cloud team can move the issue if that's not the appropriate tracker.
