### ISSUE TITLE
Conditional and Profile priority

### ISSUE THREAD

**Issue by vincentmonier** [spring-projects/spring-boot#2897]
Not sure it's a spring-boot or spring framework issue, or an issue at all.

I have the following configuration:
```java
@Configuration
public class DateTimeProviderConfiguration {

	@Bean
	@ConditionalOnMissingBean(DateTimeProvider.class)
	public DateTimeProvider bean1() {
		return new FixableDateTimeProvider();
	}

	@Bean	
	@Profile({ "production" })
	public DateTimeProvider bean2() {
		return new DefaultDateTimeProvider();
	}

}
```
When *production* profile is not activate, `bean1` is created `bean2` is not created as expected.
But when i activate *production* profile both beans are created.

I was able to solve this problem using `@Primary` annotation on `bean2`.

But my concern is why my initial configuration does not work? Is there a priority or an exclusion regarding these two conditions? 
Is this the expected behavior or am I missing something?

Thanks for your answer

**Comment by kongslund** [comment]
Almost a year late to the party...

From [Spring Framework Reference Documentation](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-definition-profiles-java):

> If a given profile is prefixed with the NOT operator (!), the annotated element will be registered if the profile is not active.

So simply add `@Profile({ "!production" })` to `bean1()` and remove the `@Primary` annotation.

**Comment by philwebb** [comment]
Thanks @kongslund! This is indeed working as expected @vincentmonier. Your configuration is defining `bean2` in the `production` profile, but this has no effect on `bean1`. You can either use `!production` or mark `bean1` as `@Profile("default")` to indicate that it's only used when no other profiles are active.
