### ISSUE TITLE
how to configure a docker based deployment pipeline

### ISSUE THREAD

**Issue by rburgst** [spring-projects/spring-boot#2904]
I have the following build pipeline

1. a build job that builds a bunch of spring boot micro services (7 or so) and uploads them as fat jars to artifactory
2. another (separate) build job that takes those fat jars from artifactory and builds them into docker containers and then uploads them into a private docker registry (this could be changed, the reason we use a separate build is that not all of our build slaves have docker installed)
3. a job that deploys the latest docker containers into the staging system and restarts the containers

As stated earlier I have 3 problems

1. the generated pom file for the fat jar is wrong as it declares all dependencies of the small jar. 
    If my gradle / docker build job uses the normal dependency mechanism then it would download the fat jar as well as all dependencies such as spring security, … 
   I guess I can tweak the gradle build (if I look hard enough) to create an all custom pom.xml which basically tells it that this new fat jar has no dependencies (see also discussion #1716).

2. the disk usage on the artifactory is probably quite high since now every version of the individual services will contain the same jar files all over again

3. the disk usage on the docker registry is quite high
docker usually does a good job of creating image layers and only saving the increments, however, if we always only deploy an 50MB jar file where in reality only the 1MB service jar file is different.

Granted in times of terabyte drives this might be less of a problem but somehow this smells to me.

As discussed one approach would be to upload only the small jars and maybe even deploy only the “exploded” version of the jars into the docker containers. If you are careful enough I guess you can build an image layer that only contains the dependencies and if nothing changes re-use that one.

Something like this guy is doing might be a solution

http://bsideup.blogspot.com.es/2015/04/spring-boots-fat-jars-vs-docker.html

It just seems that there isn’t an established procedure for this problem.

As micro services with spring boot are all the rave now (and docker is too), I think this will become a permanent problem. Especially if people also go into continuous deployment.

**Comment by cordoval** [comment]
i agree, nice links man, please keep us posted how you have evolved this

**Comment by wilkinsona** [comment]
I think this is beyond the scope of Spring Boot and its reference documentation. It might make an interesting [Guide](https://spring.io/guides), or could perhaps be an update to the existing [Spring Boot with Docker](https://spring.io/guides/gs/spring-boot-docker/) Guide. Changes to the existing Docker guide can be suggested [here](https://github.com/spring-guides/gs-spring-boot-docker/issues).
