### ISSUE TITLE
ApplicationPidFileWriter fails (almost) silently

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-boot#2905]
I am including the ApplicationPidFileWriter in my app and managed to misconfigure the spring.pidfile property. 
On the start if my app it just stated that it is not able to create the pid file, but there is no way to find out what. I had to copy the class and add the exception to the log statement to find out what way wrong.
 
It's unfortunate that the catch in onApplicationEvent does not provide any information on why it went wrong. But at least it would be good to have a debug log statement that reveals the exception.

**Comment by wilkinsona** [comment]
#2764 is closely related but doesn't address the difficulty in figuring out why the PID file could not be created if you've opted to continue on error
