### ISSUE TITLE
Stop using or fix usage of LazyPublishArtifact for upcoming changes

### ISSUE THREAD

**Issue by octylFractal** [spring-projects/spring-boot#29074]
Spring Boot Gradle Plugin 2.6.1 uses the constructor `LazyPublishArtifact(Provider<?>)`, which is soon to be deprecated in Gradle 7.4. It would be best if this internal API could be avoided, or if not, changed to use `LazyPublishArtifact(Provider<?>, FileResolver)` instead, with a non-null `FileResolver`. The relevant PR for this change in Gradle is https://github.com/gradle/gradle/pull/18715.

**Comment by mihailcornescu** [comment]
Hi,

I have identified 2 places in the code where the old constructor, `LazyPublishArtifact(Provider<?>)`, is used:

https://github.com/spring-projects/spring-boot/blob/3e6c8bc78b7c62d1d8b90418dd3ad3bda79d964a/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/JavaPluginAction.java#L135

and

https://github.com/spring-projects/spring-boot/blob/3e6c8bc78b7c62d1d8b90418dd3ad3bda79d964a/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/WarPluginAction.java#L108

Shall I make the changes to use the new constructor?

**Comment by wilkinsona** [comment]
@mihailcornescu Thanks for the offer, but that may not be what we want to do here.

@octylFractal We'd quite happily stop using `LazyPublishArtifact` but I'm not sure how to achieve the same behaviour without public API. Could you please point me in the right direction?

**Comment by mihailcornescu** [comment]
@wilkinsona thanks for the answer.

**Comment by octylFractal** [comment]
> Could you please point me in the right direction?

Unfortunately I did take a look, and I wasn't certain if it would be possible to do this only in public API. I can take a deeper look sometime in the next few weeks if you don't figure it out.

**Comment by wilkinsona** [comment]
`FileResolver` is also internal API so moving to `LazyPublishArtifact(Provider<?>, FileResolver)` will increase the number of internal-yet-public classes that we depend upon. That feels like a step in the wrong direction to me. In the absence of a public alternative to `LazyPublishArtifact`, I wonder if we'd be better leaving things as-is.

This feels somewhat similar to https://github.com/gradle/gradle/issues/5239. We're trying to do something similar to various first-party plugins but they all rely on internal API:

- [War plugin](https://github.com/gradle/gradle/blob/2cb4012f55636266937b504cf580c1077c070969/subprojects/plugins/src/main/java/org/gradle/api/plugins/WarPlugin.java#L90)
- [Ear plugin](https://github.com/gradle/gradle/blob/2cb4012f55636266937b504cf580c1077c070969/subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPlugin.java#L133)
- [Java plugin](https://github.com/gradle/gradle/blob/2cb4012f55636266937b504cf580c1077c070969/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L325)

I'll leave this open for now but mark it as blocked. Unfortunately, I don't think we'll be able to make some progress without some pointers on how to avoid using `LazyPublishArtifact`.

**Comment by wilkinsona** [comment]
Closing in favor of #30209. Thanks for the PR, @octylFractal.
