### ISSUE TITLE
Make the runScripts method on AbstractScriptDatabaseInitializer more extensible

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#29137]
As revealed by fixing #29095, the configuration of the settings are done by a protected method that takes individual arguments. Adding an extra setting (for instance, comment prefixes) would break the method in its current form.

We should revisit this arrangement so that perhaps the settings (or at least something inherited from it) is used to configure the populator.

**Comment by terminux** [comment]
Hi, maybe we can replace a single parameter with the corresponding `Properties`(such as `QuartzProperties`), I submitted a PR.#29162
