### ISSUE TITLE
ErrorPageSecurityFilter prevents Spring Boot 2.6.1 from starting up under Tomcat 8.5

### ISSUE THREAD

**Issue by KnightosMaster** [spring-projects/spring-boot#29135]
After upgrading to Spring Boot 2.6.1, the application no longer starts when deployed to Tomcat 8.5, with the following error:
`org.apache.catalina.core.StandardContext.filterStart Exception starting filter errorPageSecurityFilter
 java.lang.AbstractMethodError`.

I have dug around, and discovered that Tomcat 9+ provides a default implementation for the Filter interface's init() and destroy() methods, while 8.5 does not, thus causing the issue. Please provide an implementation for these methods, so it can remain compatible with Tomcat 8.5. 

Thank you for your hard work!

**Comment by snicoll** [comment]
Thanks for the report, this is a duplicate of #28902
