### ISSUE TITLE
failed test for import into idea

### ISSUE THREAD

**Issue by jialigit** [spring-projects/spring-boot#29164]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/13768484/147346480-8a11d0f3-93ab-457d-a8f4-adfc6c3958b0.png">

In case of the pic not rendering correct. 
ConventionsPluginTests. javadocJarIsBuilt()
ConventionsPluginTests. sourceJarIsBuilt()
 when I import project using IDEA, prompting that test failed. Above is the picture.

**Comment by snicoll** [comment]
@jialigit the build is green for us and I am afraid there's not much we can do to help based on a screenshot that doesn't even show the error. Please try again (may they were flaky) If the tests work on the command-line, then perhaps this is something related to some setup of yours in IntelliJ IDEA?

**Comment by scottfrederick** [comment]
@jialigit If you were building on Windows, you might have run into #29490.

**Comment by jialigit** [comment]
many thanks, I will try again.  @scottfrederick
