### ISSUE TITLE
Documentation for Maven Plugin classifier has an unresolved external reference

### ISSUE THREAD

**Issue by mgiorgino** [spring-projects/spring-boot#29171]
There is what seems to be a failed template replacement at the end of the documentation about the classifier configuration option of the spring-boot-maven-plugin: `see $1[$2]`:

https://docs.spring.io/spring-boot/docs/2.5.x/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-classifier
https://docs.spring.io/spring-boot/docs/2.6.2/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-classifier

**Comment by snicoll** [comment]
Thanks for the report, this is a `<a href` instruction in the javadoc that our asciidoctor processor doesn't seem to handle.

**Comment by wilkinsona** [comment]
The text in the `plugin.xml` that's used to generate the Asciidoctor source as been HTML escaped so `<a href="` has become `&lt;a href=&quot`. This is also the case in 2.2 so it looks like Maven's site support copes with this escaping but our Asciidoctor-based documentation does not.
