### ISSUE TITLE
Unable to exclude a specific dependency from spring boot dependencies in gradle

### ISSUE THREAD

**Issue by voduku** [spring-projects/spring-boot#29189]
I would like to know how to exclude a specific dependency from spring boot dependencies in gradle. I am asking this because due to internal restriction and licensing, I can't pull `com.oracle.database.jdbc:ojdbc-bom`. Despite trying all exclusion recommendation out there, including instruction from spring boot gradle plugin page, none of them seems to be able to alter `detachedConfiguration`. I get this error no matter what.
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':detachedConfiguration24'.
   > Could not find com.oracle.database.jdbc:ojdbc-bom:21.3.0.0.
```

My `build.gradle`:

```groovy

plugins {
    id 'org.springframework.boot' version '2.6.2'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = ''
version = '1.0.0'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

configurations.all {
    exclude group: 'com.oracle.database.jdbc', module: 'ojdbc-bom'
}

repositories {
    ... // some internal repo that mimic mavenCentral() but with licensing restriction
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'io.r2dbc:r2dbc-postgresql'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

test {
    useJUnitPlatform()
}
```

**Comment by snicoll** [comment]
@voduku that feels like a question for the dependency management plugin, not Spring Boot. If you haven't found what you're looking for in the [reference documentation](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/), I'd suggest asking on StackOverflow first.

**Comment by voduku** [comment]
@snicoll isn't dependency management plugin provided by spring boot team?

**Comment by snicoll** [comment]
It has a separate issue repository but even if we did, we don't use the issue tracker for questions.
