### ISSUE TITLE
How to monitor Spring Batches in Spring Boot?

### ISSUE THREAD

**Issue by JyotiMittal1993** [spring-projects/spring-boot#29191]
I have around 30 cron jobs in my spring boot application. I want to display the metadata from Spring Batch Tables like status of job, Exit Message etc. I have explored Spring Batch Admin but couldn't find much with Spring Boot.
Could someone please help, how can we do this? By Actuator, or Spring Batch Admin with Spring Boot.

**Comment by gggitpl** [comment]
Can take a look at jobrunr

**Comment by JyotiMittal1993** [comment]
> Can take a look at jobrunr

I have already developed my cron job with  
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-batch</artifactId>
</dependency>

So, using jobrunr now, would become difficult.

**Comment by wilkinsona** [comment]
There's no support in Spring Boot for batch job monitoring. You may be interested in [Spring Cloud Data Flow](https://spring.io/projects/spring-cloud-dataflow) which is the successor to Spring Batch Admin.
