### ISSUE TITLE
Configuration changelog misses properties that switched from deprecated to removed

### ISSUE THREAD

**Issue by eladeyal-intel** [spring-projects/spring-boot#29197]
I think https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6.0-Configuration-Changelog  should be explicit that 
 `spring.resources.static-locations` is removed, in favor of `spring.web.resources.static-locations`

**Comment by snicoll** [comment]
Thanks for the report. That looks like a bug of the tool that generate this table as the properties [have been flagged](https://github.com/spring-projects/spring-boot/commit/36beca2c7d1ce0b1d154a29bb1e8eb914e2116af) as ERROR (i.e. removed) in `2.6.0.M1` already.

**Comment by snicoll** [comment]
The tool has been fixed and I reran it  for all recent feature releases. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6.0-Configuration-Changelog#removed-in-260
