### ISSUE TITLE
HornetQ ignores my settings in application.properties/yml

### ISSUE THREAD

**Issue by tryIO** [spring-projects/spring-boot#2925]
Hi! I tried to configure my embedded HornetQ instance in my Spring Boot application, but there's no way to change port or host since it ignores or skips (I dunno) the settings in my application properties:

    spring.hornetq.port=15100
    spring.hornetq.host=localhost
    spring.hornetq.mode=EMBEDDED
    spring.hornetq.embedded.enabled=true
    spring.hornetq.embedded.queues=service1Q, service2Q, service3Q

In my build.gradle I included the necessary dependecies as the Reference says:

    compile group: 'org.springframework.boot', name: 'spring-boot-starter-hornetq', version: '1.2.3.RELEASE'
    compile group: 'org.hornetq', name: 'hornetq-jms-server', version: '2.4.7.Final'

And here my log:

    org.hornetq.core.server                  : HQ221045: libaio is not available, switching the configuration into NI
    org.hornetq.core.server                  : HQ221043: Adding protocol support CORE                                
    org.hornetq.core.server                  : HQ221003: trying to deploy queue jms.queue.service1Q                  
    org.hornetq.core.server                  : HQ221003: trying to deploy queue jms.queue.service2Q                  
    org.hornetq.core.server                  : HQ221003: trying to deploy queue jms.queue.service3Q                  
    org.hornetq.core.server                  : HQ221020: Started Netty Acceptor version 4.0.13.Final localhost:5445  
    org.hornetq.core.server                  : HQ221007: Server is now live                   

Is there something wrong in my configuration? Something I missed? Is it somehow related to "libaio is not available"? (I noticed that HornetQ is not able to find the libHornetQAIO32.so and 64)

**Comment by wilkinsona** [comment]
The host and port are only used when you're connecting to a remote HornetQ broker. The embedded broker should be using an `InVMAcceptor` which has no concept of host and port. However, the second last log line suggests that you're using `NettyAcceptor` which I don't understand just yet. Are you using any additional configuration that you haven't shared?

**Comment by tryIO** [comment]
Yeah I found it, my bad, I didn't see there was a HornetQConfiguration file where there was additional settings...
