### ISSUE TITLE
Do we have anything in Spring Boot Admin which can tell us the status of Spring Batches? Like status, execution end time, time taken to execute job

### ISSUE THREAD

**Issue by JyotiMittal1993** [spring-projects/spring-boot#29252]

**Comment by bclozel** [comment]
Duplicates #29191

**Comment by JyotiMittal1993** [comment]
> Duplicates #29191

But I didn't get the answer.

**Comment by snicoll** [comment]
@JyotiMittal1993 please be considerate of the team's time. Not getting an answer on an opened issue is no reason for creating a duplicate.
