### ISSUE TITLE
Support for 'web' and 'rest-api' modes in SpringBoot Security Starter

### ISSUE THREAD

**Issue by sivalabs** [spring-projects/spring-boot#2926]
Hi,
Having a REST back-end with SpringBoot and a Single Page Application as front-end using any javascript framework is becoming a prominent architecture style these days.

Using Spring Security for web applications is straight forward. But in order to protect the REST API we have to extend few Spring Security components (`AuthenticationEntryPoint`, `SimpleUrlAuthenticationFailureHandler`, `SavedRequestAwareAuthenticationSuccessHandler`, `LogoutSuccessHandler`) to return appropriate HTTP Status codes instead of redirecting to login page.

This is same repeating boilerplate we need to do for securing REST API with Spring Security.

If we can have support for 'web' and 'rest-api' modes where 'web' mode works as usual and 'rest-api' mode activates the above mentioned customizations that would be great.

**Comment by cemo** [comment]
@rwinch What do you think? I believe that it would worth having these implementation in the Security side.

**Comment by rwinch** [comment]
@sivalabs I'm wondering if some of your concerns have already been addressed. Can you outline exactly what components need customized and how you want them customized? Spring Security has been chipping away at a lot of these problems via content negotiation.

**Comment by sivaprasadreddy** [comment]
Hi Rob,
I have looked into many articles on web for implementing Security for REST API using SpringSecurity and most of them do the same (more or less) as explained in the article https://dzone.com/articles/secure-rest-services-using

Basically, the process for implementing REST API Security involves implementing the following Custom Handlers like

**Comment by cemo** [comment]
@rwinch You can take a look JHipster project as well. They have also their implementations. For example: 

https://github.com/jhipster/generator-jhipster/blob/d7cd37037ee12cb2540eb3c84d413e92cbbc06fd/app/templates/src/main/java/package/security/_AjaxAuthenticationSuccessHandler.java

**Comment by mbhave** [comment]
Spring Boot 2.0 relies on Spring Security's content-negotiation which will prevent redirecting to the login page for Rest APIs.
