### ISSUE TITLE
Pre-process GraphQL schema resources at build time

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#29291]
As seen in https://github.com/spring-projects/spring-graphql/pull/218#issuecomment-997296408, using our Spring GraphQL auto-configuration with the experimental Spring Native project is causing issues.

The Spring Boot auto-configuration for Spring GraphQL is scanning classpath locations for files using the `PathMatchingResourcePatternResolver`. This approach is not compatible for now with GraalVM (see https://github.com/spring-projects/spring-graphql/issues/230#issuecomment-1007386842).

When a Spring Framework abstraction allows it, we should pre-process this at build time using the upcoming AOT engine and programmatically configure those resources on the GraphQL source builder directly.

**Comment by bclozel** [comment]
Blocked until a Spring for GraphQL version with Jakarta API is available.

**Comment by joshlong** [comment]
hi - i'm sorry I'm missing something. What does Jakarta EE have to do with Spring Graphql and its ability to resolve `Resource`s?

**Comment by wilkinsona** [comment]
It's a more general blockage at the moment. Spring for GraphQL uses Jakarta EE APIS ([such as the Servlet API, for example](https://github.com/spring-projects/spring-graphql/blob/b6897168cf976f294c45ff38e8080dbf884f4c18/spring-graphql/src/main/java/org/springframework/graphql/web/webmvc/GraphQlHttpHandler.java#L22)) and there is not yet a version of Spring for GraphQL that uses the EE 9 versions of those APIs.

**Comment by snicoll** [comment]
We've started brainstorming how we could do this for entities and that issue looks like yet another case for that need. See #30523.

**Comment by bclozel** [comment]
Closing in favor of spring-projects/spring-graphql#495
