### ISSUE TITLE
Allow custom ClassPathBeanDefinitionScanner on AnnotationConfigServletWebServerApplicationContext

### ISSUE THREAD

**Issue by xiejx618** [spring-projects/spring-boot#29294]
I use spring boot 2.5.2 to create a servlet web application, but I cannot find a way to override `ClassPathBeanDefinitionScanner.checkCandidate()` to resolve bean conflicts. 

This issue is somewhat similar to spring-projects/spring-framework#13962.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
