### ISSUE TITLE
enabled-property from Endpoints isn't showing up in configurationPropertiesReportEndpoint

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#2929]
The endpoints derived from `AbstractEndpoints` are lacking the enabled-property in `/configprops-endpoint`.
I think it is due to the fact that `isEnabled()` returns a primitive `boolean` and `setEnabled()` accepts a wrapper-type `Boolean`.

**Comment by snicoll** [comment]
Yup, switching that back to `boolean` did the trick but we can't do that as we use `null` as "check somewhere else`. `isReadable` is most probably the culprit here and we should rely on the meta-data for that stuff anyway. 

ping @dsyer

**Comment by snicoll** [comment]
Okay so I had a look to that and Jackson's `ObjectMapper` cannot detect that out-of-the-box (which makes sense). I haven't found a way to customize that so I've asked there (https://github.com/FasterXML/jackson-databind/issues/805)
