### ISSUE TITLE
Streamline build-time configuration when using Gradle

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2933]
There are three areas where I think we could improve the build configuration that's required:
- Using an embedded servlet container other than Tomcat
- Using a logging framework other than Logback
- Building an executable war file

In Gradle at least, I think that rather than requiring users to declare exclusions, add dependencies to a particular configuration, etc., we could take a more declarative approach to the configuration. There isn't a dramatic reduction in configuration in any of the three cases, it's only a single line in each, but I think it makes the intent clearer. Comments, +1s, -1s, etc are all welcome.
##### Using an embedded servlet container other than Tomcat

Current:

``` groovy
configurations {
    compile.exclude module: 'spring-boot-starter-tomcat'
}
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-undertow'
}
```

Proposal – a user declares that they want to use Undertow and the plugin takes care of the necessary dependency configuration:

``` groovy
springBoot {
    servletContainer 'undertow'
}
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
}
```
##### Using a logging framework other than Logback

Current:

``` groovy
configurations {
    compile.exclude module: 'spring-boot-starter-logback'
}
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-log4j2'
}
```

Proposal – a user declares that they want to use Log4j2 and the plugin takes care of the necessary dependency configuration:

``` groovy
springBoot {
    logging 'log4j2'
}
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
}
```
##### Building an executable war file

Current:

``` groovy
apply plugin: 'war'
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
}
```

Proposal – the presence of the war plugin is sufficient for the Spring Boot plugin to "move" the servlet container starter dependency into the `providedRuntime` configuration:

``` groovy
apply plugin: 'war'
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
}

```

**Comment by snicoll** [comment]
I think the last one is especially nice but I wonder if that will work in the IDE (which is already having some sort of issue for that kind of things). I have nothing against the two others except the following:

* Where do we draw the line? You took container and logging (pretty obvious) but this may be used externally as well.
* What about Maven? ( :D )
