### ISSUE TITLE
Launch script not included  in JAR file by spring-boot-maven-plugin since version 2.6.0

### ISSUE THREAD

**Issue by octmueller** [spring-projects/spring-boot#29355]
Since Version 2.6.0 of Spring Boot, the [launch script](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script) is not attached to the front of the executable JAR file produced by the spring-boot-maven-plugin.

I download the basic Java11, Maven Spring Boot 2.6.2 project from [Spring Initializr](https://start.spring.io/).
Added <packaging>jar</packaging>
and

`<plugin>`
`    <groupId>org.springframework.boot</groupId>`
`    <artifactId>spring-boot-maven-plugin</artifactId>`
`    <configuration>`
`        <executable>true</executable>`
`    </configuration>`
`</plugin>`

then executed "maven clean install" (I have Maven 3.6.1) 

The resulting JAR does not contain the launch script.
I played with the version of the plugin and found out that version **2.5.8 works**, i.e. the launch script is attached to the JAR.
**Version 2.6.0 does not work** properly

**Comment by wilkinsona** [comment]
Thanks for the report but I cannot reproduce the behaviour that you have described using Maven 3.8.3 (as generated by start.spring.io) and Java 11.0.10 on macOS.

I used the following pom.xml file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>executable</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>executable</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<executable>true</executable>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

This resulted in a jar with the launch script prepended:

```
$ more target/executable-0.0.1-SNAPSHOT.jar
#!/bin/bash
#
#    .   ____          _            __ _ _
#   /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
#  ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
#   \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
#    '  |____| .__|_| |_|_| |_\__, | / / / /
#   =========|_|==============|___/=/_/_/_/
#   :: Spring Boot Startup Script ::
#

### BEGIN INIT INFO
# Provides:          executable
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: executable
# Description:       Demo project for Spring Boot
# chkconfig:         2345 99 01
### END INIT INFO

[[ -n "$DEBUG" ]] && set -x

# Initialize variables that cannot be provided by a .conf file
WORKING_DIR="$(pwd)"
# shellcheck disable=SC2153
[[ -n "$JARFILE" ]] && jarfile="$JARFILE"
[[ -n "$APP_NAME" ]] && identity="$APP_NAME"

# Follow symlinks to find the real jar and detect init.d script
cd "$(dirname "$0")" || exit 1
[[ -z "$jarfile" ]] && jarfile=$(pwd)/$(basename "$0")
while [[ -L "$jarfile" ]]; do
  if [[ "$jarfile" =~ init\.d ]]; then
    init_script=$(basename "$jarfile")
  else
…
```

If you would like us to spend some more time investigating, please provide a complete sample project that reproduces the problem and some more information about your OS, Java version, etc.

**Comment by octmueller** [comment]
You are right. It is actually there. I'm having another issue with the JAR, which is already discussed [here](https://github.com/spring-projects/spring-boot/issues/29354)
Sorry and thanks for looking into this
