### ISSUE TITLE
Need to be able to enable Access-Control-* headers for Spring Boot Actuator 

### ISSUE THREAD

**Issue by pompeyjoe** [spring-projects/spring-boot#2936]
I want to be able to hit the Actuator, Jolokia, etc endpoints from a dashboard app written in Javascript.

I am unable to do so because of CORS.

I know this has been raised before - [#1124](https://github.com/spring-projects/spring-boot/issues/1124) - however, the solution was to make the actuator endpoints available on the main server port, so that they are in the same ApplicationContext as the SimpleCORSFilter suggested in http://spring.io/guides/gs/rest-service-cors/.

I want to keep the actuator endpoints on a separate management port. It would be great if it was possible to configure Access-Control-* headers for the actuator endpoints.

**Comment by wilkinsona** [comment]
This should be pretty straightforward now thanks to Spring Framework 4.2's improved CORS support. We should be able to override `getCorsConfiguration` in `EndpointHandlerMapping` and return a `CorsConfiguration` instance that's configured via `application.properties`. One complication is Jolokia. It has its own CORS configuration model (which can now be used, see #1987). We'll need to decide whether to allow Jolokia to be configured separately, or use the same configuration across the board.
