### ISSUE TITLE
Add option to pass configured Docker host to the image builder container

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#29384]
When the Docker host used for building images in the build plugins is configured using the `DOCKER_HOST` environment variable or the `docker.host` configuration property, this value should be bound to the builder container in order for the CNB lifecycle to access the host. The build plugins currently [always bind the default socket](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform/src/main/java/org/springframework/boot/buildpack/platform/build/Phase.java#L135)  `/var/run/docker.sock:/var/run/docker.sock` instead of effectively binding `${DOCKER_HOST}:/var/run/docker.sock` when `DOCKER_HOST` is set.

**Comment by terminux** [comment]
Hi, I submitted a PR to fix this issue. #29441

**Comment by scottfrederick** [comment]
After further research and testing, there are cases where we want the socket to always be bound to `/var/run/docker.sock` as is currently done and other cases where we want the socket bound to the value of the configured docker host. The `/var/run/docker.sock` value will always work with Docker Engine and minikube because those daemons make that socket available in the container that uses the binding. Other container engines require a different value like `/run/user/1000/podman/podman.sock` for podman.

In order to support both cases we will need a build plugin configuration property that the user can enable to select the non-default behavior.
