### ISSUE TITLE
SpringSecurityDialect does not get configured when using thymeleaf-extras-springsecurity4

### ISSUE THREAD

**Issue by brushmate** [spring-projects/spring-boot#2940]
Spring Boot does not autoconfigure the `SpringSecurityDialect` when I add the dependency `thymeleaf-extras-springsecurity4`. When I use `thymeleaf-extras-springsecurity3` everything works and STS marks the dependency as `managed`.

**Comment by wilkinsona** [comment]
Which version of Boot are you using? Spring Security 4 and its Thymeleaf dialect are only supported in 1.3 snapshots at the moment. You can use them with 1.2, but you'll have to configure the dialect yourself.

**Comment by brushmate** [comment]
Okay, I am using 1.2.3. Thanks.
