### ISSUE TITLE
graphical interface for rapid system design 

### ISSUE THREAD

**Issue by gitsupi** [spring-projects/spring-boot#29439]
there is no steps for designing a system in spring boot 
any feature is not accessible and all are separate and we need config none necessary java classes and many 
why you are not thinking out of programing language 
a good work is jhipster that tries a way to facilitate software implementation 
anyone knows all systems has security 
anyone know systems can be big data and stream processing 
why we have hierarchy for creating applications 

i a word this  designing is rebuilding code redundant and loose our times

**Comment by wilkinsona** [comment]
Thanks for the suggestion but a graphical interface is out of the scope of the Spring Boot project. If you like JHipster then that's a good option for you.
