### ISSUE TITLE
JobLauncherCommandLineRunner always have lowest precedence

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#2943]
Currently `JobLauncherCommandLineRunner` neither implments `Ordered` or have `@Ordered` annotation. Which mean it will get implicitly `Ordered.LOWEST_PRECEDENCE`.

This means one cannot define custom `CommandLineRunner` which is executed _before_ `JobLauncherCommandLineRunner` without overriding the jobLauncherCommandLineRunner bean defined in `BatchAutoConfiguration`. This affects the official getting started guide spring-guides/gs-batch-processing#8.

I could do a pull request if you agree on default order value. Not sure what is the practice in such cases, but since it can be number between `Integer.MIN_VALUE` and `Integer.MAX_VALUE`, and there are no other `CommandLineRunner`s in autoconfigure module - probably `0` should be OK.

**Comment by snicoll** [comment]
Potentially related to #7656
