### ISSUE TITLE
socket accept failed

### ISSUE THREAD

**Issue by WanManito** [spring-projects/spring-boot#29494]
boot version 2.6.2

![8~Q {M2YB 3F4_DAX}RQ{_L](https://user-images.githubusercontent.com/26118508/150247444-27b46d1a-f438-4abf-b72c-4a45a860d190.png)

**Comment by WanManito** [comment]
windows10 64 ,Version 2.6.1 does not appear to have this problem

**Comment by bclozel** [comment]
I don't see anything linked to Spring Boot here. The error listed in your screenshot mentions a operating system bug well-known by the Tomcat team.
Please follow the instructions in the error message.
