### ISSUE TITLE
Move core Maven artifacts to the provided scope for the maven plugin

### ISSUE THREAD

**Issue by hazendaz** [spring-projects/spring-boot#29520]
Maven recently started alerting to move maven artifacts to provided scope so the m2 repository is not cluttered with unnecessary maven artifacts and resulting transients that are already present with maven being used.  This looks to affect only maven-plugin-api in this project that is currently set to runtime and should be provided instead.  I don't work with gradle so unsure of changes needed to make that happened but wondered if that could be addressed in next release?

**Comment by philwebb** [comment]
@hazendaz Do you have any links to the discussions around this? I'm curious why `provided` is better.

**Comment by hazendaz** [comment]
@philwebb See https://issues.apache.org/jira/browse/MPLUGIN-370 and https://issues.apache.org/jira/browse/MNG-7097.
