### ISSUE TITLE
Default Embedded Tomcat Trusted Proxies Pattern Does Not Allow 172.x IP Range

### ISSUE THREAD

**Issue by davidgoate** [spring-projects/spring-boot#2952]
I am experiencing an issue running a Spring Boot 1.2.3 (Embedded Tomcat 8.0.20) app in AWS behind a proxy (ELB & NGINX).

Essentially I am running in the default AWS VPC which uses some private IP ranges like `172.31.0.0/16`.

HTTP headers such as "X-Forwarded-Proto" & "X-Forwarded-For" are being ignored by the Tomcat `org.apache.catalina.valves.RemoteIpValve#invoke` method. I believe that this is due to a check that the remote address (in my case the last proxy) is in the trusted internal proxies pattern. Since my proxy is 172.31.34.*** it is not in the list and thus it is ignored.

The check in `org.apache.catalina.valves.RemoteIpValve` is:
````
final String originalRemoteAddr = request.getRemoteAddr();
 if (internalProxies !=null && internalProxies.matcher(originalRemoteAddr).matches()) {
````

The default pattern in `org.apache.catalina.valves.RemoteIpValve` is:

````
private Pattern internalProxies = Pattern.compile(
            "10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|" +
            "192\\.168\\.\\d{1,3}\\.\\d{1,3}|" +
            "169\\.254\\.\\d{1,3}\\.\\d{1,3}|" +
            "127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|" +
            "172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|" +
            "172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|" +
            "172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}");
````

Which permits the IP range I needed. However, in `org.springframework.boot.autoconfigure.web.ServerProperties.Tomcat` the internal proxies pattern is:

````
private String internalProxies = "10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|" // 10/8
				+ "192\\.168\\.\\d{1,3}\\.\\d{1,3}|" // 192.168/16
				+ "169\\.254\\.\\d{1,3}\\.\\d{1,3}|" // 169.254/16
				+ "127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"; // 127/8
````

which is then used to configure the value in the `org.springframework.boot.autoconfigure.web.ServerProperties.Tomcat#customizeTomcat` method.

The two agree on the first 4 patterns, but Spring Boot omits the last 3 for the 172.x range.

Is this intentional, and if so why? I know I can override this by setting the `server.tomcat.internal_proxies` property. However I am curious as to whether this is intentional or a potential bug? 

It caused me some frustration and lost time debugging to come to this conclusion. Unless there is a reason could the defaults be changed to include this as it might save people some time and pain in future.

**Comment by wilkinsona** [comment]
Sorry for the trouble. We missed changing the default when we upgrade from Tomcat 7 to Tomcat 8 (the default we're using is Tomcat 7's default). We plan to realign in 1.3 - see https://github.com/spring-projects/spring-boot/issues/2699.
