### ISSUE TITLE
Is there any spring-boot version (ideally 2.3.x) which has latest 5.2.x version of spring (spring-web) 5.2.19.RELEASE?

### ISSUE THREAD

**Issue by smilep** [spring-projects/spring-boot#29527]
Last 2.3.x version of spring-boot (2.3.12.RELEASE) has spring(spring-web) version as 5.2.15.RELEASE

Next spring-boot version is 2.4.0 which has spring(spring-web) version as 5.3.1

Is there any spring-boot version (ideally 2.3.x) which has latest 5.2.x version of spring (spring-web) 5.2.19.RELEASE?

**Comment by wilkinsona** [comment]
Spring Boot 2.3.x is [no longer supported](https://spring.io/projects/spring-boot#support). If you must continue to use Spring Boot 2.3.x, you can use the `spring-framework.version` property to upgrade to `5.2.15.RELEASE`. However, please note that Spring Framework 5.2.x is also [no longer supported](https://spring.io/projects/spring-framework#support). Ideally, you should upgrade to Spring Boot 2.5.x (and therefore Spring Framework 5.3.x) as soon as possible.

**Comment by smilep** [comment]
@wilkinsona thank you!
