### ISSUE TITLE
Consider upgrading javassist to 3.20.0-GA

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#2953]
Current version is set to 3.18.1-GA - apparently the one required by Hibernate 4.3.9.Final.
However, tools like HikariCP for instance require at least 3.19.0-GA.

**Comment by wilkinsona** [comment]
Hikari's in the [process of rolling back to 3.18.2](https://github.com/brettwooldridge/HikariCP/commit/eadf8d1911da73bed9f96e5fa0d9feae11058328). AFAIK, Hibernate is deliberately avoiding 3.19 too. That still leaves the question of using 3.18.1 or 3.18.2.

**Comment by brenuart** [comment]
Good point.
According to the versioning guidelines followed by javassit, 3.18.2-GA should be ok - even if Hibernate requires 3.18.1-GA.

(it is a real nightmare to maintain all those dependencies inside a single BOM! how do you manage to do that? How can you be sure you don't introduce inconsistencies?)

**Comment by brenuart** [comment]
SpringBoot 1.3.0.BUILD-SNAPSHOT sets HikariCP to version 2.3.8. The latter now requires javassit 3.18.2-GA. Wouldn't it be time to update the version in `spring-boot-dependencies` ?

**Comment by wilkinsona** [comment]
I'm still not convinced. Given that Hibernate is more widely used than HikariCP, I'd prefer to go with the version that Hibernate builds and tests against as the default.

**Comment by shakuzen** [comment]
It should also be noted this is only a concern for Java 6 users, for which HikariCP is in maintenance mode. As written in [the changelog](https://github.com/brettwooldridge/HikariCP/blob/master/CHANGES), the runtime dependency on javassist has been removed sinced HikariCP 2.4.0.

**Comment by wilkinsona** [comment]
Hibernate 5.1 uses 3.20.0. We should align.
