### ISSUE TITLE
Spring Boot does not recognize maven properties as of version 2.6

### ISSUE THREAD

**Issue by oguzhancevik** [spring-projects/spring-boot#29541]
I was reading maven properties from application.yaml. After upgrading spring boot version from 2.5.3 to 2.6.2 spring boot does not recognize maven properties.

I've searched the Spring Boot [2.6 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes) and other sources, but haven't found a solution to this problem.

**pom.xml**

```
<groupId>io.perasoft</groupId>
<artifactId>location-service</artifactId>
<name>location-service</name>
<description>Location Service</description>
<version>0.0.2-SNAPSHOT</version>
```

**application.yaml**

```
info:
  application:
    # read from pom.xml
    name: '@name@'
    description: '@description@'
    version: '@version@'
    build-time: '@maven.build.timestamp@'
```

**Comment by snicoll** [comment]
@oguzhancevik what do you mean by "not recognize Maven properties" exactly? Do you mean that they don't show up in `/actuator/info`? If so, [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default) of the release notes is relevant.

**Comment by oguzhancevik** [comment]
@snicoll, Thank you. Yes, I mean that. I solved my problem as follows.

set `management.info.env.enabled` to `true`

resource: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default
