### ISSUE TITLE
Make JCachePropertiesCustomizer public

### ISSUE THREAD

**Issue by mwerlitz** [spring-projects/spring-boot#29542]
Please make `org.springframework.boot.autoconfigure.cache.JCachePropertiesCustomizer` public, so the properties that are used to initialize the `CacheManager` can be customized by an application.

I would like to use the property replacement feature of EhCache in the configuration XML file.
At the moment this is not possible because the properties supplied when creating the `CacheManager` in `JCacheCacheConfiguration#createCacheManager` are empty and there seems to be no way to supply additional properties. 

The code in `JCacheCacheConfiguration#createCacheManagerProperties` is supposed to create these properties with the help of `JCachePropertiesCustomizer` instances. But `JCachePropertiesCustomizer` is not public so one has no possibility to supply additional props that may be used in the XML config file.

**Comment by snicoll** [comment]
@mwerlitz thanks for the suggestion. Can you please share the properties you'd like to set?

**Comment by philwebb** [comment]
It sounds like that's the best approach for now. If the EhCache enhancement gets implemented and we need to offer more customization options please comment back here.
