### ISSUE TITLE
Allow custom RSocket WebsocketServerSpecs to be defined

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#29550]
See https://github.com/spring-projects/spring-framework/issues/27973 for background.

The `RSocketWebSocketNettyRouteProvider` auto-configuration calls `HttpServerRoutes.ws` to create the `HttpServerRoutes`. It would be nice if the `WebsocketServerSpec` argument could be specified easily.

**Comment by snicoll** [comment]
Closing in favor of PR #29567
