### ISSUE TITLE
Support CachingConnectionFactory in HornetQAutoConfiguration

### ISSUE THREAD

**Issue by sourcekick** [spring-projects/spring-boot#2956]
Migrating from Spring Boot 1.1.4 to 1.2.3 we have the following issue:

In our Spring Java configuration under 1.1.4 we combined `org.springframework.jms.connection.CachingConnectionFactory` with the "jmsConnectionFactory" templated by `org.springframework.boot.autoconfigure.jms.hornetq.HornetQAutoConfiguration` and it worked fine.

Under 1.2.3 we see that `HornetQAutoConfiguration` has been heavily reworked, so that our approach does not work any more.

I have been asked to open this issue here: http://stackoverflow.com/questions/30013801/how-to-combine-spring-boot-hornetqautoconfiguration-and-cachingconnectionfactory

If the scenario is still valid to use `CachingConnectionFactory` with HornetQ in Spring Boot to cache JMS Sessions and `MessageProducer`s, please add direct support for `CachingConnectionFactory` in `HornetQAutoConfiguration`.

**Comment by sourcekick** [comment]
On a side note to this, let me observe that it is difficult to configure several JMS `ConnectionFactory` instances within a Spring Boot application when making use of the Auto Configuration. A reason for wanting to do this could for example arise in a scenario where there are several functionally separate JMS communications going on, in which the application participates. The intention could then be to separate the software infrastructure for these communicaitons as much as possible, using one JMS `ConnectionFactory` each.

**Comment by snicoll** [comment]
Can you show your code please? (the integration with `CachingConnectionFactory`).

Regarding several `ConnectionFactory` instances, I don't see what you would expect us to do exactly. If you look at what we do for `DataSources` we reuse the JDBC facility with a `DataSourceBuilder`. If you think it would be nice to do something of the kind or if you have another idea, please create a separate issue. IMO, several connection factories enter the corner case area but I am happy to be proven wrong.

**Comment by wilkinsona** [comment]
The support for HornetQ has been deprecated in 1.4. We have no plans to enhance it.
