### ISSUE TITLE
Spring Boot 3.0.0-M1 - Application start time same, or even longer than Spring Boot 2.X

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-boot#29568]
Hello Spring Boot,

First of all, a big thank you for the release of Spring Boot 3.0.0-M1!
https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available

With this amazing news, we performed some benchmarks, and unfortunately, observed application start time staying the same, and in very few occasions start time is even higher using 3.0.0-M1.

Maybe incorrect here, the impressions portrayed by 3.0.0-M1 with Spring Native, would allow applications to start much faster.

We did the experiment across some 20 services, ranging from very lightweight services, to complex and many dependencies services.

For all of them we restarted multiple times with same hardware and / or container setup.

Result: We observed across all services similar start up time, and in very few occasions, higher start up time using Spring Boot 3.

Therefore, I am raising a possible issue here.
Is this expected? What are we doing wrong?

Thank you

**Comment by mdeinum** [comment]
Did you build a native image or just upgraded the Spring Boot version? Only when building a native image you will get the native enhancements, else it is just a regular Java application like the current Spring Boot one is.

**Comment by bclozel** [comment]
This first milestone is mainly about raising the baseline for JDK and APIs (such as the Jakarta migration). The [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes) do not mention any change on startup time or native - this work is currently ongoing and will be announced with the release notes and documented when it's available.

**Comment by patpatpat123** [comment]
Thank you Marten for answering, much appreciated.

I did the building with Java 17, a fresh maven clean install making sure everything is Java 17, and still the same application start up time.

But as Brian said, and thanks Brian for jumping in, maybe I misunderstood and thought this version will change start up time / native.

Glad to have that cleared out, and looking forward to getting a version when true native and application start up enhancement will come.

Thanks all!

**Comment by patpatpat123** [comment]
One year after, we are now running native SpringBoot in production.
Still couple of bumps, but mainly, a big thank you Spring team!
