### ISSUE TITLE
Problems with 3.0 M1 configuration properties change log 

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#29563]
Via [@OrangeDog on Gitter](https://gitter.im/spring-projects/spring-boot?at=61f02bcfbfe2f54b2e370694):

> This table doesn't make much sense
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Configuration-Changelog
The columns seem to be "default value" and "description" rather than "replacement" and "reason"

**Comment by snicoll** [comment]
I've fixed the tool that we use to generate the changelog and updated the existing page.
