### ISSUE TITLE
org.springframework.boot.web.error.ErrorAttributeOptions#isIncluded has a bug

### ISSUE THREAD

**Issue by lp2jx0309** [spring-projects/spring-boot#29581]
version: 2.3.8
org.springframework.boot.web.error.ErrorAttributeOptions#isIncluded 
The judgment condition is wrong. 
It should be options.isIncluded(Include.MESSAGE)

		if (!options.isIncluded(Include.MESSAGE) && errorAttributes.get("message") != null) {
			errorAttributes.put("message", "");
		}

**Comment by mbhave** [comment]
Spring Boot 2.3.x has reached end of life. If you think you've found a bug in the more recent versions of Spring Boot (2.5.x and above), please create an issue and attach a sample application that we can run to reproduce the issue.
