### ISSUE TITLE
UNIFORM

### ISSUE THREAD

**Issue by qxo** [spring-projects/spring-boot#29582]
```
@Configuration
@ConfigurationProperties("app")
public class AppConfig implements InitializingBean {

    private Map<String, String> mapping;

    public Map<String, String> getMapping() {
        return mapping;
    }

    public void setMapping(Map<String, String> mapping) {
        this.mapping = mapping;
    }

```
```
app:
  mapping:
    /AAA/*1: "/*AAAAAAAAAAA*/"
```
===> why "/AAA/*1" ==> AAA ?

**Comment by mbhave** [comment]
It sounds like you're asking why binding a map key with special characters doesn't contain the actual value. Please see [this section](https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.maps) of the docs to see what needs to be done when binding to a map with special characters in the key.

**Comment by qxo** [comment]
> It sounds like you're asking why binding a map key with special characters doesn't contain the actual value. Please see [this section](https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.maps) of the docs to see what needs to be done when binding to a map with special characters in the key.

Thanks, It's worked for me:)

```
app:
  mapping:
    "[/AAA/*1]": "/*AAAAAAAAAAA*/"
    "[/key2]": "value2"
```
