### ISSUE TITLE
Detect when running in development

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#296]
Certain features (e.g. thymelaf refresh) would make sense to switch on when actually developing code.

We should look to see if we can detect development time and enable a special profile. One option might be to look for `.java` files.

**Comment by philwebb** [comment]
Closing this in favor of #3082. Profile support is something that we could consider in the future but we should see how 1.3 works out first.

**Comment by cemo** [comment]
@philwebb Any chance to reopen this issue? There is a nice work here and would be nice to integrate to Boot.

**Comment by dsyer** [comment]
This one should stay closed (in favour of #3082 it says). If you have a specific feature request that isn't addressed there (I believe everything we talked about is, but isn't didn't need any profile  please open another issue.
