### ISSUE TITLE
Typo in method return documentation - DefaultOAuth2AccessToken.html#isExpired()

### ISSUE THREAD

**Issue by matsawyer** [spring-projects/spring-boot#29608]
Typo in documentation for the Returns: description of this DefaultOAuth2AccessToken.html#isExpired() method here:

https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/common/DefaultOAuth2AccessToken.html#isExpired()

The text writes `befor ethe`

> true if the expiration is befor ethe current time

instead of expected `before the`

> true if the expiration is before the current time

**Comment by snicoll** [comment]
@matsawyer thank you for the report, but this issue tracker does not deal with issues in Spring Security. Looking at the link you've provided, this looks like a dormant project and I haven't found such reference in a supported version of Spring Security. If you are using a supported version, please raise an issue against https://github.com/spring-projects/spring-security/ - Thanks!
