### ISSUE TITLE
MessageSourceAutoConfiguration has unreliable Conditional behavior

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2960]
I've written some MockMvc tests that pull in a subset of my application's configuration but that shouldn't attempt to start up the entire container with all of the components. Since I do need message resolution for HTML templates, I added `@Import(MessageSourceAutoConfiguration)` to my test config class. This works perfectly in Eclipse but fails when run from Surefire. Instead, in Surefire, the `DelegatingMessageSource` is created and injected, which fails to actually resolve any messages.

I've confirmed via `SpringBootCondition` logging that the `ResourceBundleCondition` is not getting evaluated; the `MSAC` apparently is being suppressed by the `ConditionalOnMissingBean`. Attempting to autowire the configuration class itself results in a `NoSuchBeanException`, indicating that the entire class is suppressed.

I'm using Surefire 2.18.1 with the JUnit 4.12 runner and Spock 1.0-groovy-2.4.

Logs from the Surefire runner and Eclipse are identical until:

    2015-05-17 13:14:03.275 DEBUG   --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Using MessageSource [org.springframework.context.support.ResourceBundleMessageSource: basenames=[messages,support_messages]]

    2015-05-17 13:20:34.235 DEBUG   --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Unable to locate MessageSource with name 'messageSource': using default [org.springframework.context.support.DelegatingMessageSource@5ad5be4a]

**Comment by snicoll** [comment]
does your test starts a "Spring Boot" application?

**Comment by chrylis** [comment]
No, the test is specifically avoiding Spring Boot to keep from starting up all the autoconfiguration classes that would otherwise activate, and I'm importing the ones I want manually.

**Comment by snicoll** [comment]
Then the order of auto-configuration is not applied and `MessageSourceAutoConfiguration` explicitly uses that. Adding an auto-configuration in a "simple" Spring ApplicationContext has not the same effect than in the context that Spring Boot creates. In particular, check what `EnableAutoConfigurationImportSelector` is doing. 

I guess we should find a way to let you do your think with a Spring Boot application context. Might be useful for testing purposes.

**Comment by snicoll** [comment]
Ironically, this sounds related to #2962

**Comment by snicoll** [comment]
Discussing this with @dsyer, how about putting the auto-configuration last in the list of configuration classes for your test?

**Comment by chrylis** [comment]
There's something other and stranger going on here, because it works reliably in Eclipse and fails reliably in Surefire. I'm not defining any other `MessageSource` anywhere, so the only other place that it can be being created is in `AbstractApplicationContext`, and ordering really shouldn't matter for this conditional.

Why do you suggest last instead of first?

**Comment by snicoll** [comment]
I am not sure I understand what you want to achieve in your test but all I can say is that the order of auto-configurations won't be respected in a regular Spring context (non Spring Boot app). What you're experiencing is unfortunate but  can be explained easily (I think I did already). Putting the auto-config last is a way to make sure that any bean that may be required will be present when it is evaluated. That's what a Spring Boot application context does by default for you. But you're not using that.

**Comment by chrylis** [comment]
I was importing `MessageSourceAutoConfiguration` as an ordinary `@Configuration` class to get the Spring resource-based message resolver. The problem I'm describing, as far as I can tell, has *nothing to do* with configuration-class ordering; for some reason, the `AbstractApplicationContext` was providing its fallback `DelegatingMessageSource` before evaluating the `@ConditionalOnMissingBean` on `MessageSourceAutoConfiguration`, but only under Surefire, not under Eclipse.

**Comment by snicoll** [comment]
Please provide a sample and we'll see from there.

**Comment by chrylis** [comment]
I was unable to replicate with a new project from Initializr, but I can replicate the problem at will from our private code base and can make arrangements to make it available for debugging if that would be useful at all.

**Comment by snicoll** [comment]
As long as I can run something, I am happy :)

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
