### ISSUE TITLE
Assert that sources passed to the Binder during construction do not contain null elements

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#29604]
See https://github.com/spring-cloud/spring-cloud-commons/issues/1062. The error was hard to find in part because we don't assert that sources have no `null` elements.

**Comment by snicoll** [comment]
Looking at the related issue, that sounds more like a bug to me.

**Comment by philwebb** [comment]
Closing in favor of PR #30878. Thanks @terminux!
