### ISSUE TITLE
spring-boot-gradle-plugin docs use deprecated Gradle API

### ISSUE THREAD

**Issue by halcyon22** [spring-projects/spring-boot#29610]
The [Spring Boot Gradle Reference Guide](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives) uses `AbstractArchiveTask.classifier` which is [deprecated as of Gradle 5.1](https://discuss.gradle.org/t/publishing-jars-with-classifiers-after-v5-0/30144/3) and replaced by `archiveClassifier`. As [the plugin requires Gradle 6.8, 6.9, or 7.x](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#introduction), the example should be updated.

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/gradle/packaging/boot-jar-and-jar-classifiers.gradle

```
bootJar {
    archiveClassifier = 'boot'
}

jar {
    archiveClassifier = ''
}
```

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/docs/gradle/packaging/boot-jar-and-jar-classifiers.gradle.kts
```
tasks.getByName<BootJar>("bootJar") {
    archiveClassifier.set("boot")
}

tasks.getByName<Jar>("jar") {
    archiveClassifier.set("")
}
```

I can create a PR for this change if preferred.

**Comment by snicoll** [comment]
@halcyon22 thank you for the report. If you have time for a PR, that would be much appreciated.

**Comment by snicoll** [comment]
Closing in favor of PR #29611
