### ISSUE TITLE
OutputCaptureExtension doesn't captures embedded tomcat's logs

### ISSUE THREAD

**Issue by frossi485** [spring-projects/spring-boot#29615]
When using a Spring application with `server.tomcat.accesslog` set up, then tests that uses `OutputCaptureExtension` don't capture logs from tomcat even though these logs are displayed to the console. 

**Expected behavior:** After adding `@ExtendWith(OutputCaptureExtension.class)`, when using `output.getAll()` we should get all logs displayed to the console.

**Comment by snicoll** [comment]
> then tests that uses OutputCaptureExtension don't capture logs from tomcat even though these logs are displayed to the console.

Can you share a small sample that shows what you've described? `server.tomcat.accesslogs` logs to a separate file that is relative to `server.tomcat.basedir`.  You can share the sample as a zip attached to this issue or share a link to a GitHub repository.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
