### ISSUE TITLE
Remove dependency management for spring-boot-starter-activemq

### ISSUE THREAD

**Issue by yuvanakannan** [spring-projects/spring-boot#29645]
Even though the spring-boot-dependencies-3.0.0-M1.pom lists the spring-boot-starter-activemq-3.0.0-M1 as a dependency, spring-boot-starter-activemq-3.0.0-M1 is not available in https://repo.spring.io/milestone.

**Comment by bclozel** [comment]
Support for ActiveMQ has been removed in #28591. We should remove it's reference from the dependency management.
