### ISSUE TITLE
Use Kotlin 1.6 for API and language version in reference documentation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#29654]
`KotlinConventions` currently uses 1.3, we should upgrade.

**Comment by wilkinsona** [comment]
I think we should do this only in the docs, otherwise we’re raising our Kotlin baseline from 1.3 to 1.6. That feels a bit too much for 2.7.

**Comment by philwebb** [comment]
@wilkinsona What's the difference between the version in the conventions and the version [in the `gradle.properties`](https://github.com/spring-projects/spring-boot/blob/1d153fde3782fe2ec2d9c34e6da2fdd84425fce3/gradle.properties#L7). I assumed we were already on 1.6 and had just missed it in the conventions.

**Comment by wilkinsona** [comment]
Our Kotlin set up is a bit like compiling with Java 11 and using `-release 8` to retain compatibility with an earlier version. While we depend on Kotlin 1.6, setting the API and language version to 1.3 produces Kotlin 1.3 compatible byte code.
