### ISSUE TITLE
Custom ErrorController returns 500 for unknown resources

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-boot#2965]
Hi,

While trying to make a simple example for what I thought was a [spring-security-oauth issue](https://github.com/spring-projects/spring-security-oauth/issues/471), I found out something much simpler :
**Registering a custom `ErrorController` leads to HTTP 500 responses for non-existent resources instead of 404**.

Context : I wanted to create an `ErrorController` that is virtually the same as Spring Boot's default `BasicErrorController`, with only a different format (only a code + message).

Here is the behavior that I observe :
### 1) Without a custom ErrorController
- Requesting an non-existant resource with the default `ErrorController` :arrow_right: OK (HTTP 404)
  `HttpServletRequest` implementation : `org.apache.catalina.core.ApplicationHttpRequest` (found out debugging `BasicErrorController`)
### 2) With a custom ErrorController
- Requesting an existing resource that throws an `Exception` annotated with `@ResponseStatus` with the `CustomErrorController` enabled :arrow_right: OK (HTTP 406) :
  `HttpServletRequest` implementation : `org.apache.catalina.core.ApplicationHttpRequest`
  _Pretty much all status codes seem to work except 404_
- Requesting an non-existant resource with the `CustomErrorController` enabled :arrow_right: KO (HTTP 500)
  HttpServletRequest implementation : `org.apache.catalina.connector.RequestFacade`
### 3) With a custom ErrorController + Spring Security enabled
- Requesting an existant resource with the `CustomErrorController` enabled + Spring Security enabled + valid authentication :arrow_right: KO : (HTTP 500)
  `HttpServletRequest` implementation : 
  `org.springframework.security.web.servletapi.HttpServlet3RequestFactory$Servlet3SecurityContextHolderAwareRequestWrapper`

The question is why does the `HttpServletRequest` implementation received by the custom `ErrorController` change? 
The various request proxies listed above cannot be easily processed to extract a 404 HTTP status for unknown resources.

**Comment by michaeltecourt** [comment]
Here is a sample project : https://github.com/michaeltecourt/spring-boot-issue-2965

The readme.md file has sample curl commands to verify the behavior described.

To verify part 1) : simply remove the `@Controller` annotation on `CustomErrorController`
To verify part 2) : Reactivate the CustomErrorController
To verify part 3) : Activate the spring-boot-starter-security dependency in the pom

**Comment by michaeltecourt** [comment]
After comparing with another project, the path was missing on the `CustomErrorController#error` method in the sample I provided :
```java
@RequestMapping("${error.path:/error}")
@ResponseBody
public ResponseEntity<?> error(HttpServletRequest req, HttpServletResponse resp) throws IOException {
    // ...
}
```

I'm still confused, why did this method receive strange HttpServletRequest implementations *only* for "resource not found", and other exceptions were processed properly ?

**Comment by wilkinsona** [comment]
> I'm still confused, why did this method receive strange HttpServletRequest implementations only for "resource not found", and other exceptions were processed properly ?

It's an implementation detail of Tomcat. With a custom exception, Spring MVC is calling `sendError`. When it's a 404 the request unwinds all the way back to Tomcat and it then performs the error dispatch. This different handling requests in different `HttpServletRequest` implementations being used.
