### ISSUE TITLE
Consider adding Jacoco preconfiguration on spring-boot-starter-parent, integrated with surefire and failsafe

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-boot#29665]
Given the amount of problems configuring these 3, it would be nice if Spring-Boot Parent preconfigured Jacoco

**Comment by snicoll** [comment]
@nightswimmings thanks for the suggestion but we have no plan to add such an opinionated arrangement. If configuring jacoco with failsafe and surefire is such a problem, I'd recommend reporting that to the Maven team.

**Comment by nightswimmings** [comment]
My argued motivation was providing Sonar coverage support out of the box, not the fact that is difficullt to configure per se, I worded it very wrong, but I appreciate your feedback !

**Comment by scordio** [comment]
Hi @snicoll, would Spring Boot be willing to add only the `jacoco-maven-plugin` declaration, i.e., just take care of the version management aspect?

**Comment by snicoll** [comment]
I don't think we should. Providing dependency management for something we don't use ourselves doesn't feel right.
