### ISSUE TITLE
Neo4JTransactionManager will not be created if any other exists

### ISSUE THREAD

**Issue by strict88** [spring-projects/spring-boot#29663]
I think here is a mistake, because it should be conditional on Neo4jTransactionManager. As for now if in project there is any TransactionManager Neo4j manager will not be auto created.
https://github.com/spring-projects/spring-boot/blob/ce6b12a02480f77ead612834123ba640509649c9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.java#L108

**Comment by snicoll** [comment]
That is the expected behaviour. 2 transaction managers within the same application doesn't sound idiomatic. 

Can you please rather describe what you expect to do and validate first that it works properly with manual configuration? Thanks.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
