### ISSUE TITLE
Add links to Spring Boot for Apache Geode to the reference documentation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#29697]
This section of the docs has a link to GemFire and Geode but we don't have an actual dedicated section describing it like we do with the others. Since it's a Spring project, we should add a paragraph with a description and link to the relevant project docs.

**Comment by jxblum** [comment]
Hi @philwebb and Spring Boot team-

Thank you for creating this ticket to clarify _Spring Boot's_ position on GemFire/Geode.

To start with, and to make this even easier, we don't need to mention ("VMware Tanzu"; previously "Pivotal") GemFire any longer. In short, dedicated _Spring_ bits are exclusively based on and focused towards OSS, Apache Geode now.

Reasons for this include, but are not limited to:

 1) GemFire diverged from Apache Geode - There are no standalone GemFire releases matching the latest Apache Geode releases currently, e.g. 1.13.7, 1.14.3.  GemFire 9.10 (latest) was last based on Apache Geode 1.12. I uses this as an opportunity for a clean break and separation.

 2) GemFire does not have a compatible license - GemFire is commercially licensed by VMware while Apache Geode uses the Apache 2 License the same as the corresponding _Spring_ bits.

3) GemFire is not available in Maven Central.

While `#1` might be surprising,`#2` and `#3` are not, as we have discussed in the past.

The **main problem** I have is, users, customers, and even internal VMW field engineers alike, all have trouble knowing where to start and finding relevant information on _Spring Boot's_ support for Apache Geode.

While _Google_ searches (for [example](https://www.google.com/search?q=Spring+Boot+for+Apache+Geode&oq=Spring+Boot+for+Apache+Geode&aqs=chrome..69i57j0i22i30j69i60l3j69i65l3.3017j0j7&sourceid=chrome&ie=UTF-8)) reveal bits of _Spring Boot for Apache Geode_ (SBDG), search terms have to be deliberate and precise (arguably an SEO problem).

Unfortunately, SBDG does not have a dedicated project page on [spring.io/projects](https://spring.io/projects), or specifically [here](https://spring.io/projects/spring-boot) despite being a proper _Spring_ project. However, I have, to the best of my ability tried to mirror my SBDG GitHub project page ([README](https://github.com/spring-projects/spring-boot-data-geode#spring-boot-for-apache-geode)) as closely as possible to projects on spring.io.  This includes things like a opening description and [Features](https://github.com/spring-projects/spring-boot-data-geode#project-features), [Learn](https://github.com/spring-projects/spring-boot-data-geode#learn), [Getting Started](https://github.com/spring-projects/spring-boot-data-geode#get-started), with [_Spring Initializer_](https://github.com/spring-projects/spring-boot-data-geode#get-started) even, with an [example, starter app](https://github.com/spring-projects/spring-boot-data-geode#simple-spring-boot-apache-geode-application) to references back to [_Spring Boot's_ project site](https://github.com/spring-projects/spring-boot-data-geode#spring-boot-project-site) and a [Wiki page](https://github.com/spring-projects/spring-boot-data-geode/wiki/Spring-Boot-for-Apache-Geode-and-VMware-Tanzu-GemFire-Version-Compatibility-Matrix) discussing version compatibility across the _Spring_ projects on which SBDG is based (see [here](https://github.com/spring-projects/spring-boot-data-geode/wiki/Spring-Boot-for-Apache-Geode-and-VMware-Tanzu-GemFire-Version-Compatibility-Matrix#version-compatibility-matrix), specifically).

Most users and customers I talk to, all start at spring.io and specifically the _Spring Boot_ [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/index.html), and specifically, [here](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql) to try and find relevant information.

I always communicate to users and customers alike that _Spring Boot_ documentation is deliberately vague, but precise, encouraging users to "drill down" into the relevant documentation for the projects that "owns the code" as @wilkinsona has stated, and I whole heartedly agree.

For _Spring_ developers using Apache Geode, like much of the _Spring_ portfolio of projects, **I want users to start with _Spring Boot_**. I don't want them specifically looking at _Spring Data for Apache Geode_ (SDG) unless they absolutely need to, and this has been a point of confusion. "Do I start with SDG and use explicit, declarative Annotation configuration or do I use Spring Boot?" - said nearly every single user I have encountered, and my answer is always, "_Spring Boot!_".

For example, if they are only using Apache Geode as a _caching provider_ in the core _Spring Framework's Cache Abstraction_, then _Spring Data_ (access) is irrelevant. If users are using Apache Geode for event/streaming or distributed compute use cases, then _Spring Data_ is mostly irrelevant.  SBDG has first-class, built-in _auto-configuration_ support for most of Apache Geode's features, including data access with _Spring Data_ [for Apache Geode].  All of this can be seen in the various "chapters" from SBDG's [documentation](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/).

SBDG is a culmination of _Spring Data for Apache Geode_ (SDG; and foundation), _Spring Session for Apache Geode_ (SSDG) and _Spring Test for Apache Geode_ (STDG), pulling all the bits together into a cohesive whole.  SBDG should not be confused with _Spring Data_ as SBDG and SDG's concerns are vary different (e.g. _convention over configuration_ using _auto-configuration_ vs. _data access_ concerns).

SBDG's documentation will then be responsible for "drilling down" in to the relevant docs from SDG, SSDG and STDG including Spring Boot, and Spring Data Commons, and Spring Session core, and Spring Framework as is appropriate.  I can even cover (and do) the difference from Apache Geode to VMware Tanzu GemFire so Spring Boot itself does not need to.

I hope all of this makes sense, and specifically my reasons for linking Spring Boot to SBDG.

Happy to discuss more as needed.

Regards,
@jxblum

**Comment by jxblum** [comment]
To be fully transparent, VMware is planning to release standalone versions of VMware Tanzu GemFire again, as of `9.15`, which will be based on Apache Geode `1.15`.

The _Spring_ team has no intention of owning the _Spring_ bits based on and dedicated to GemFire for the reasons cited above (1-3). Like other commercial and/or community driven projects (e.g. _Hazelcast_), the VMware engineering org will "own" _Spring Data for VMware Tanzu GemFire_.

From a _Spring_ perspective, we will view and treat this effort (_Spring Data for VMware TanzuGemFire_) as a community, or rather commercially led project, releasing independently from the rest of _Spring Data_ since another reason includes, GemFire has very different support lifecycles (driven by contracts) from the rest of _Spring_.

In addition to above, this is also why OSS Spring bit for Apache Geode will be exclusively tied to OSS Apache Geode.
