### ISSUE TITLE
okhttp update to 4.9.2

### ISSUE THREAD

**Issue by meier-th** [spring-projects/spring-boot#29726]
okhttp library is vulnerable to an information disclosure issue due to how the contents of sensitive headers, such as the Authorization header, can be logged when an IllegalArgumentException is thrown.

This issue could allow an attacker or malicious user who has access to the logs to obtain the sensitive contents of the affected headers which could facilitate further attacks.

Fixed in 5.0.0-alpha3 by [this](https://github.com/square/okhttp/commit/dcc6483b7dc6d9c0b8e03ff7c30c13f3c75264a5) commit. The fix was cherry-picked and backported into 4.9.2 with [this](https://github.com/square/okhttp/commit/1fd7c0afdc2cee9ba982b07d49662af7f60e1518) commit.

Requesting you to clarify if this dependency will be updated to a fixed version in the following releases

**Comment by snicoll** [comment]
@meier-th please search the issue tracker before raising issues like this. There is already [a conversation about oktthp 4](https://github.com/spring-projects/spring-boot/issues/18506#issuecomment-1016256152).
