### ISSUE TITLE
Getting 400 Error when URL contains Chinese

### ISSUE THREAD

**Issue by imxingquan** [spring-projects/spring-boot#29740]
I want to visit http://localhost:8080/upload/目录/文件.pdf, show 404 error. but using English words is ok. like this http://localhost:8080/upload/catalog/file.pdf

**Comment by wilkinsona** [comment]
Thanks for the report but you haven't provided enough information for us to be able to help you. Without knowing how you've configured your application's web server, how you expect the PDF to be served (is it via a `@Controller`, a static resource, something else) it's impossible to tell if the 404 is a bug in our code our yours.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by imxingquan** [comment]
My project is a released product, previously using SpringBoot2.3.12, which has been running for 4 years. Access to static files is ok, but after the upgrade to 2.6.3, if the access path contains Chinese characters, there will be an error of 400, but there is no problem in version springboot2.3.12

**Comment by wilkinsona** [comment]
We don't need your whole project, just a minimal sample that reproduces the problem.

A lot has changed between Spring Boot 2.3 and 2.6, including numerous web server version upgrades, a change to the default MVC path matching strategy, etc. Unfortunately, we don't have time to guess what the problem may be in your specific situation. Even if we find a problem with the same symptoms, it may be different problem to yours and any fix we make would not help you.

As I said above, if you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by imxingquan** [comment]
I found that there would be problems when using Shiro 1.8. When I changed Shiro to 1.6, the problem disappeared. I'm sorry. I'm taking your much time.
