### ISSUE TITLE
MimeMapping for ots has a trailing space in its mime type

### ISSUE THREAD

**Issue by SecretX33** [spring-projects/spring-boot#29746]
I, unfortunately, don't have enough time to submit a PR for this issue, but it is most likely a typo, and it should be really easy to fix. On the class MimeMappings, more precisely, on [this line](https://github.com/spring-projects/spring-boot/blob/d9acde296136e08ea1e3f06da84086ade29a3ac6/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/server/MimeMappings.java#L131), there is a space between the last letter and the `"`, and I believe this is a typo, correct me if I'm wrong.

How it is right now
```java
mappings.add("ots", "application/vnd.oasis.opendocument.spreadsheet-template ");
```

What I believe should have been
```java
mappings.add("ots", "application/vnd.oasis.opendocument.spreadsheet-template");
```

I caught that when building unit tests for a code that parses mime types of a file for the company I work for.

**Comment by wilkinsona** [comment]
Well spotted, @SecretX33. Thank you.
