### ISSUE TITLE
Consider enabling major optimization in AspectJ 1.9.8

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-boot#29754]
https://github.com/eclipse/org.aspectj/issues/9
> In our project we found out that during the build up of the spring context
the class loading takes a very long time.
Root cause is the huge amount of file I/O during pointcut class loading.
We are taking about ~250k file loads.

> With these changes we managed to cut down the starting time by around 50%.

> What we found out is that IMHO - the clear method of the ClassLoaderRepository
is called far too often -> in our settings this resulted in not a single cache
hit as the cache got cleared permanently.
Therefore we de-actived the cache clear calls inside the ClassLoaderRepository.

> Secondly we changed the Java15AnnotationFinder in a way to not always create
new objects for the ClassLoaderRepository but re-use one static instance.
Otherwise we experienced >100k objects being created.

> Last but not least we introduced a cache for unavailable classes so that
they do not have to be looked up using file I/O over and over again.

Therefore, if that performance profile is common, then enabling this optimization with a flag on the next AspectJ release has the potential:
* To cut in half Spring startup time!
* might affect overall throughput positively (including IO) 
* might affect memory consumption positively (better cache hits, etc)

While this PR seems extremely interesting, it lacks extensive testing so it would be a nice, high impact, low hanging fruit for the Spring team, to test it, to measure the effects on metrics (startup time, throughput, resource use (io, cpu) and memory use. And finally to enable it by default after some testing :)

**Comment by wilkinsona** [comment]
I don't think we should do this. From the end of @aclement's comment that @bclozel linked to above:

> So I think it is a reasonable call to make these opt-in for now, make sure people know they can try them and we are looking for feedback.

FWIW, I'm not sure that we're in a position to set an AspectJ system property either as it may conflict with something else running in the same JVM, particularly in a war deployment to a standalone container.

**Comment by LifeIsStrange** [comment]
@aclement making an announcement on the java subreddit could gather some feedback too

**Comment by bclozel** [comment]
FYI I've run [the entire Spring Framework test suite and got no failure](https://ge.spring.io/s/caobuifdnh5ok), but cannot vouch for any performance issue with tests. @LifeIsStrange do you have an application where this new feature could have an impact? If so, we'd be interested in your findings.

**Comment by LifeIsStrange** [comment]
No unfortunately I have no web application at hand to test

**Comment by philwebb** [comment]
I'm going to close this one since I don't think Spring Boot should be changing the default. I think the best plan is to try and have AssertJ users test their applications with the property set and for the default to be switched in due course.

**Comment by LifeIsStrange** [comment]
@aclement Out of curiosity, was this optimization turned on by default since then?

**Comment by aclement** [comment]
@LifeIsStrange I don't believe so.

https://github.com/eclipse-aspectj/aspectj/blob/2b0e11d8633c84e8b0827e0eb77b4639fe0914e4/weaver/src/main/java/org/aspectj/weaver/reflect/Java15AnnotationFinder.java#L54
