### ISSUE TITLE
spring boot custom classloader decryption?

### ISSUE THREAD

**Issue by fendo8888** [spring-projects/spring-boot#29782]
Hello, I have a project that encrypts the class, and I want to decrypt the class by customizing the classloader. I don't know how to deal with it in spring boot. Or, spring boot does not support global loading of custom classloaders.

**Comment by bclozel** [comment]
The `SpringApplication` class provides a way to set a custom `ResourceLoader`. You could set your own `DefaultResourceLoader` backed by your custom `ClassLoader` there.

For further questions, please use StackOverflow. Thanks!
