### ISSUE TITLE
Potential bug in Spring data; mapping null to wrapper class throws exception

### ISSUE THREAD

**Issue by MagdaZny** [spring-projects/spring-boot#29815]
Hi, 
I wanted to report a bug I noticed when upgrading Spring Boot 2.5.8 → 2.6.2.
After the upgrade the Jdbc @Query when returning null it cannot be mapped to String, as before.  Now we get an exception _Couldn't find PersistentEntity for type class java.lang.String!_. 

```java
@Query("SELECT ST_AsGeoJson(ST_Envelope(ST_Union(polygon))) FROM tableName WHERE ...")
  String findBoundsForSectors();
  ```
  
  Kind regards

**Comment by bclozel** [comment]
I guess you're using Spring Data JDBC here? I don't think Spring Boot is involved here, could you report this to  https://github.com/spring-projects/spring-data-jdbc/issues? If it turns out this is a Spring Boot problem after all, we can reopen this issue. Thanks!
