### ISSUE TITLE
Remove separate dependency management for netty-tcnative in favor of the entry in Netty’s bom

### ISSUE THREAD

**Issue by oburgosm** [spring-projects/spring-boot#29816]
Since netty [added tcnative to its BOM](https://github.com/netty/netty/pull/11609), it's no longer necessary to manage netty-tcnative in spring-boot-dependencies

**Comment by bclozel** [comment]
This is a breaking change, since this means removing the `netty-tcnative.version` version property.
Tentatively scheduling this for 3.0.x.

**Comment by wilkinsona** [comment]
I think this is the sort of breaking change that would be acceptable in a 2.x release as it's fairly easy to define your own dependency management for tcnative if you want to use a version that's out of line with Netty's.

**Comment by snicoll** [comment]
I've noticed at least one that the netty bom didn't match with the latest tcnative version (as they found out there was an issue with it and release a new version without releasing a new version of netty). I am wondering if keeping control wouldn't be so bad considering bomr has been doing a great job thus far.

**Comment by oburgosm** [comment]
Please also note that currently spring boot is not managing all netty-tcnative artifacts. So artifacts not managed by Spring Boot but managed by netty bom could be in conflict with artifacts managed by Spring Boot.
