### ISSUE TITLE
Move away from spring.factories for auto-configurations

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#29872]
Using `spring.factories` to find auto-configuration classes is causing problems with our native work. We initially used it because the code was already available, but we want to offer an alternative in 2.7 and stop using spring.factories for auto-configuration in 3.0.

Task: 

[ ] Design and document a file format that can replace spring.factories for auto-configuration
[ ] Update the `AutoConfigurationImportSelector` and the `ImportAutoConfigurationImportSelector` to not use `spring.factories` anymore
[ ] Update documentation tooling in buildSrc to read the new file
[ ] Check with existing IDE and tool vendors to ensure the new format doesn't cause issues

**Comment by mhalbritter** [comment]
The autoconfigurations are now annotated with `@AutoConfiguration` and are put in a file named `META-INF/spring-boot/org.springframework.boot.autoconfigure.AutoConfiguration`.

The autoconfigurations are listed each in a separate lines, comments are supported with the `#` character, and empty lines are ignored.

See the [current documentation](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.developing-auto-configuration.understanding-auto-configured-beans).

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/31228 is tracking providing an annotation processor that automatically generates the `META-INF/spring-boot/org.springframework.boot.autoconfigure.AutoConfiguration` file. Until that has been implemented, you should update it manually when you add a new `@AutoConfiguration` class.
