### ISSUE TITLE
Handle GitHub's secondary rate limit with dependency upgrades

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#29879]
When running `bomrUpgrade` on a version that requires more than 15 or so dependency upgrades, the build fails as creating the upgrade issues hits GitHub's secondary rate limit, see https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits.

**Comment by wilkinsona** [comment]
There's some information in https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits that I think is relevant here, specifically:

> If you're making a large number of `POST`, `PATCH`, `PUT`, or `DELETE` requests for a single user or client ID, wait at least one second between each request.

It looks like we should sleep for 1 second between creating each issue.

The guidelines also say the following:

> Requests that create content which triggers notifications, such as issues, comments and pull requests, may be further limited and will not include a `Retry-After` header in the response. Please create this content at a reasonable pace to avoid further limiting.

We're creating issues so it looks like we won't get a `Retry-After` header. Hopefully waiting at least 1 second between each issue creation will result in it happening at a  "reasonable pace".
