### ISSUE TITLE
Broaden default keys to sanitize to match anywhere in the key not just at the end

### ISSUE THREAD

**Issue by turaleck** [spring-projects/spring-boot#29949]
I have an application that bootstraps itself using Vault properties. When I hit the management endpoint, I see the vault properties values printed in plain text. These are expected to be masked.

**Sample**
In Vault, I have the following:

Path: `kv/secret/password`

Value at this path:
```
 user.password: value1
 user.password.previous: value2
```

In my application I have the following:

```
@Configuration
@VaultPropertySource("kv/secret/password")
public class VaultPropertySourceConfiguration {
}


@ConfigurationProperties(prefix = "user")
public class UserProperties {
    public String password;
}
```

When I run this application, field `password` gets populated properly. However, when I hit the Spring management endpoint, I see that `user.password` is masked. However, `user.password.previous` is not; it's in plain text.

spring boot version: 2.4.13
spring framework version: 5.3.15
spring cloud version: 2020.0.5

**Comment by turaleck** [comment]
@wilkinsona I think your suggestions to broaden default keys to sanitize is a good one. My opinion is that all vault properties, regardless of their names, should be sanitized. Does the Actuator know that a given property is a vault property?

**Comment by turaleck** [comment]
Thank you @wilkinsona

**Comment by mbhave** [comment]
If we decide to broaden the rules to match anywhere in the key, I think we'd only want to do it for certain default keys. For example, it would make sense for keys such as `password` but a key like `key`, might not always be sensitive (`management.endpoint.env.keys-to-sanitize` is not a sensitive value.) If we make that distinction, then we'd need some way of configuring that if a user overrides the default keys. I'm in favor of leaving the defaults as is and overriding the keys to providing a custom sanitizing function where appropriate.
