### ISSUE TITLE
springboot starter validation 2.6.3 not work in webflux

### ISSUE THREAD

**Issue by WunHwan** [spring-projects/spring-boot#29961]
hi, i use springboot 2.6.3 version, but starter-validation did not work in spring-webflux.

`spring-boot-starter-validation:2.6.3`
```xml
    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>6.2.0.Final</version>
      <scope>compile</scope>
    </dependency>
```
`hibernate-validator:6.2.0.Final`
```xml
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
</dependency>
```

but i see ValidationAutoConfiguration.class condition use `javax.validation`, does it mean springboot-starter-validation does not work in spring-webflux?

**Comment by snicoll** [comment]
>  but starter-validation did not work in spring-webflux.

What does this mean? Rather than doing your own analysis, please describe the problem you're facing. If you're looking for support, StackOverflow or Gitter is a more suitable place

**Comment by WunHwan** [comment]
> 

hi, springboot-webflux how to use spring-boot-starter-validation? can use jsr303?

**Comment by snicoll** [comment]
@WunHwan Hi, and Yes. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask your questions on StackOverflow.
