### ISSUE TITLE
Spring.config.import does not work

### ISSUE THREAD

**Issue by rmkrishna1977** [spring-projects/spring-boot#29992]
Hi,

I am currently upgrading to spring boot version 2.6.1 along with spring cloud 2021.0.1.  When we use this version, spring.config.import is not working and there by unable to read application.yml configured in git. This was working in 2.5.6 version of spring boot. We also tested with spring boot version 2.6.3.  but we are facing the same issue

**Comment by wilkinsona** [comment]
As far as we know it should work and you haven't provided enough information to identify why that's not the case. 
If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by rmkrishna1977** [comment]
we use some thing like this 

spring:
  config:
    import:
      - optional:configserver:\${vcap.services.pddv-config-service-development.credentials.uri}

**Comment by wilkinsona** [comment]
Unfortunately, a small snippet of YAML is insufficient to diagnose the problem as there are too many unknowns. As I said above, please provide a complete yet minimal sample that reproduces the problem.

**Comment by rmkrishna1977** [comment]
this is the complete yml file we have.

---
spring:
  profiles:
    active: local
  application:
    name: ${name?:unknown}
  config:
    import:
      - optional:configserver:\${vcap.services.pddv-config-service-development.credentials.uri}
      - optional:configserver:\${vcap.services.pddv-config-service-integration.credentials.uri}
      - optional:configserver:\${vcap.services.pddv-config-service-volume.credentials.uri}
      - optional:configserver:\${vcap.services.pddv-config-service-production.credentials.uri}

**Comment by wilkinsona** [comment]
Unfortunately, that's still not enough as there are still too many moving parts. For example, you are using optional imports which could mean that an import of something that doesn't exist fails silently and we have no way of knowing whether or not everything you are importing exists or not.

If you would like us to spend time trying to help you, then you are going to have to spend some time reducing your problem down to a complete, yet minimal sample that reproduces it. That should be something that we can `unzip` or `git clone` and run with minimal additional setup required. If you do not have time to produce such a sample then unfortunately we do not have time to try to help you as it will simply take too long.

**Comment by rmkrishna1977** [comment]
thanks
