### ISSUE TITLE
boolen query method working in 2.6.3, but does not in 2.6.4.

### ISSUE THREAD

**Issue by underbell** [spring-projects/spring-boot#30005]
After upgrading to 2.6.4, the query method for boolean does not work as desired.
I'm curious if it's a bug or something I missed.
I'll link the my repo.

https://github.com/underbell/demo_boot_2.6.4

**Comment by snicoll** [comment]
I believe this is the wrong repository to report this. Spring Data R2DBC is not managed here, but [in a dedicated repository](https://github.com/spring-projects/spring-data-r2dbc). 

Asking @mp911de for a review.

**Comment by underbell** [comment]
I'm sorry.
It has already been reported and revised.

https://github.com/spring-projects/spring-data-r2dbc/issues/698
