### ISSUE TITLE
Upgrade to Micrometer 1.9.0-M4

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#30014]
Micrometer 1.9.0-M4 duplicates the binders in a separate module named
`micrometer-binders`, and marks the binders in the core module as
deprecated. This change is done to ease the migration to 2.0.0, where the binders in the core modules will be dropped.

Spring Boot should build against Micrometer 1.9.0-M4 and use the binders in the `micrometer-binders` module. However, user-contributed beans should still work even if they come from the `micrometer-core` module.

We should note in the release notes that with Spring Boot 3.0, which will use Micrometer 2.0, the support for the old binders in `micrometer-core` will be dropped.

**Comment by mhalbritter** [comment]
The `2.7.x` branch now builds against micrometer 1.9.0-snapshot. The `main` branch still builds against 2.0.0-M1, and I applied none of the changes from `2.7.x` to `main`.

**Comment by mhalbritter** [comment]
We will track the 2.0.0 changes in https://github.com/spring-projects/spring-boot/issues/29753

**Comment by wilkinsona** [comment]
Re-opening so that we can use this issue for the move from snapshots to 1.9.0-M4.
