### ISSUE TITLE
Clarify actuator security documentation

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#30025]
The [Security section of the actuators documentation](https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/actuator.html#actuator.endpoints.security) says: 

> For security purposes, all actuators other than /health are disabled by default. You can use the `management.endpoints.web.exposure.include` property to enable the actuators.

This should state that only the `/health` endpoint is _exposed_ over HTTP rather than _enabled_.

**Comment by pashabhai** [comment]
For security purposes, by default only /health endpoint is exposed over HTTP. 
If we want to enable others from the available list of endpoints,  use the management.endpoints.web.exposure.include property to enable the actuators.

**Comment by cmabdullah** [comment]
It'll be easier to update documentation, @scottfrederick  I'd like to work on it.

**Comment by wilkinsona** [comment]
Thanks, @cmabdullah. It’s all yours. Please let us know if you have any questions.

**Comment by wilkinsona** [comment]
Closing in favor of #30065.
