### ISSUE TITLE
spring-boot-dependencies: hibernate-entitymanager.version propertly looks unused

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3004]
As I can see in file `spring-boot-dependencies/pom.xml` we introuduced property `hibernate-entitymanager.version`:
```xml
<hibernate-entitymanager.version>${hibernate.version}</hibernate-entitymanager.version>
```
but we haven't use it.

Looks like we should use it here:
```xml
<dependency>
	<groupId>org.hibernate</groupId>
	<artifactId>hibernate-entitymanager</artifactId>
	<version>${hibernate.version}</version>
</dependency>
```
or if it's not we should remove it at all.

**Comment by wilkinsona** [comment]
We used `hibernate-entitymanager.verion` initially and it was [left as a synonym when we added `hibernate.version`](https://github.com/spring-projects/spring-boot/commit/8d05cd1fb6740b8d7bd080eb3ba649ed422b430d#diff-083b496f7d7090ebebfb261636fbe139). Given that anyone who wants to override the version will have to use `hibernate.version` I think it's reasonable to remove it in 1.3.
