### ISSUE TITLE
v2.5 Release notes say spring.datasource.* properties are deprecated in favor of spring.sql.init.* properties, but official documentation tells nothing about them

### ISSUE THREAD

**Issue by smedelyan** [spring-projects/spring-boot#30053]
In https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes they say:

> SQL Script DataSource Initialization
>
> The underlying method used to support schema.sql and data.sql scripts has been redesigned in Spring Boot 2.5. spring.datasource.* properties related to DataSource initialization have been deprecated in favor of new spring.sql.init.* properties. These properties can also be used to initialize an SQL database accessed via R2DBC.

In [official documentation](https://docs.spring.io/spring-boot/docs/2.6.3/reference/htmlsingle/#data.sql.datasource.production) there are still used `spring.datasource.*`properties like `url`. 

I think that release notes are not quite clear on this topic, and, AFAIU, `spring.datasource.*` properties like `url`, `username`, `password`, etc. have *not* been deprecated and should be used without changes. Otherwise, if there *are* new properties in `spring.sql.init.*` like `url`, `password`, etc., the documentation should be updated.

**Comment by wilkinsona** [comment]
> `spring.datasource.*` properties like `url`, `username`, `password`, etc. have not been deprecated and should be used without changes

That's correct.

The release notes attempt to describe this by saying the following as you've quoted above:

> `spring.datasource.*` properties related to DataSource initialization

The key part of this is "related to DataSource initialization". `spring.datasource.*` properties like `url`, `username`, `password` are not related to DataSource initialization so they are not affected by the deprecation.

The `spring.sql.init.*` properties are [described in the reference documentation](https://docs.spring.io/spring-boot/docs/2.5.x/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts). For reference, [the same section in the 2.4.x documentation](https://docs.spring.io/spring-boot/docs/2.4.x/reference/html/howto.html#howto-initialize-a-database-using-spring-jdbc) describes the old properties that have now been deprecated.
