### ISSUE TITLE
Document that generated passwords should not be used in production

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#30062]
Related to #30061, we should also update our reference documentation with a similar notice.

**Comment by nitishsaini706** [comment]
Hi @philwebb I would like to work on this , issue please assign me

**Comment by scottfrederick** [comment]
@nitishsaini706 Thank you for the offer, we'll assign the issue to you. 

The generated password and property to change it is mentioned in the documentation [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#web.security). The notice should be added to this section.

**Comment by nitishsaini706** [comment]
@scottfrederick How do I access this documentation , 
Shall I first mention this issue in Github README file

**Comment by wilkinsona** [comment]
It turned out that the changes for #30061 required a documentation update that addressed this issue at the same time. Thanks again for the offer, @nitishsaini706, and sorry for any wasted effort.
