### ISSUE TITLE
JerseyAutoConfiguration changed tomcat context parameter

### ISSUE THREAD

**Issue by perfectworks** [spring-projects/spring-boot#3007]
`JerseyAutoConfiguration` implements `WebApplicationInitializer`, so it will be loaded from `SpringServletContainerInitializer`. It changed tomcat context parameter `contextConfigLocation` and broke default config location `applicationContext.xml`.

I imported a module which dependent spring-boot-autoconfiguration, even I never use any spring boot features. it's so annoying and I have no way to kick it out of my classpath.

**Comment by wilkinsona** [comment]
Why not exclude `spring-boot-autoconfigure` if you "never use any Spring Boot features"?

**Comment by perfectworks** [comment]
@wilkinsona I don't include `spring-boot-autoconfigure` directly, it is included by some 3rd-party module. Writing a <exlusion> section in pom.xml will break package compiling.

**Comment by wilkinsona** [comment]
If excluding it will break compilation, then is sounds like you _are_ using it. Why are you using `contextConfigLocation` in a Spring Boot application?

**Comment by perfectworks** [comment]
@wilkinsona I just kicked `spring-boot-autoconfigure` out of classpath, this problem seems been resolved.
