### ISSUE TITLE
Reduce the possibility of an entry in the additional configuration properties metadata accidentally declaring a new property

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30076]
It’d be good to reduce the risk of #30074 happening again. Perhaps we could add something to the additional metadata that indicates that an entry should augment an existing property rather than declaring a new property.

#24852 is somewhat similar as it’s also trying to detect a metadata error at build time.

**Comment by snicoll** [comment]
I've been trying to add this but didn't want to introduce a property that would be specific to additional metadata.

**Comment by SeifMostafa** [comment]
It is still available? Need more clarification, Please.

**Comment by wilkinsona** [comment]
Thanks for asking, @SeifMostafa. We're not yet sure what to do here. Some thinking and design work is required.

If you're looking for an issue that's more suited to someone needing some guidance, please keep an eye out for issues labeled with as [ideal for contribution](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) and, if you haven't contributed before, [first-timers only](https://github.com/spring-projects/spring-boot/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+first-timers-only%22).

**Comment by wilkinsona** [comment]
#31916 has improved things in this area and should prevent problems like #30074 from occurring again. Any property that does not have a description will now fail the build. This will catch stale entries in the additional metadata that only specify a default value.
