### ISSUE TITLE
No metrics are bound for R2DBC ConnectionPools that have been wrapped

### ISSUE THREAD

**Issue by guerricm** [spring-projects/spring-boot#30090]
spring boot 2.6.4, spring data r2dbc and pgsql, prometheus metrics activated, 
There is no metric for connection pool.
if i debug ConnectionPoolMetricsAutoConfiguration, i see that 
`if (connectionFactory instanceof ConnectionPool)` return always false.

So no ConnectionPoolMetrics created

![image](https://user-images.githubusercontent.com/20113664/157114612-f97b4ccb-2fec-4b55-9189-bc15f70e75b6.png)

**Comment by wilkinsona** [comment]
Something's proxied the `ConnectionPool` so that we can no longer tell that's what it is. We may be able to unwrap it (`io.r2dbc.spi.Wrapped.unwrap()`) but it's impossible to tell without knowing more. Can you please share a complete, yet minimal example that reproduces the problem?

**Comment by hongjunan** [comment]
thank you, i solved this problem

>     bean {
>         ConnectionPoolMetrics((ref() as Wrapped<ConnectionPool>).unwrap(), "r2dbc", emptyList())
>             .bindTo(ref())
>     }

**Comment by wilkinsona** [comment]
That looks like a good workaround. We should be able to do that automatically for you in our metrics auto-configuration.
