### ISSUE TITLE
Spring Mobile auto-configuration should configure AbstractDeviceDelegatingViewResolver.enableFallback

### ISSUE THREAD

**Issue by yacota** [spring-projects/spring-boot#3009]
I think it would be a good idea to expose AbstractDeviceDelegatingViewResolver.enableFallback in application.properties

**Comment by snicoll** [comment]
Do you mean something like  `spring.mobile.devicedelegatingviewresolver.enable-fallback` ?

**Comment by yacota** [comment]
Exactly

**Comment by yacota** [comment]
@snicoll I have just signed the Contributor License Agreement ... do I have to email somebody in order to be able to push changes?

**Comment by snicoll** [comment]
you should fork and push to your fork and then create a PR. Check [Contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc) for more details. Thanks!

**Comment by yacota** [comment]
PR correctly applied ... previous PR had problems with Windows vs Linux(Mac) line delimiters :|

**Comment by snicoll** [comment]
That new PR is still weird. @wilkinsona is flagged as the committer. I'll fix that on my side. Thanks!

**Comment by yacota** [comment]
Thanks ... by the way any chance to include this in 1.2.4 ?

**Comment by snicoll** [comment]
I don't see a reason to include such a change in the maintenance branch, sorry. It's a configuration property after all, you can do that yourself in 1.2.x pretty easily.
