### ISSUE TITLE
Potential unresolvable cycles created by early instantiation of Filters and Servlets

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#301]
While refactoring the SecurityAutoConfiguration to be more idiomatic (according to Rob) we noticed that Security was pushing Boot (or vice versa) into a potentially dangerous cycle because of the way that Filter and Servlet beans have to be instantiated early. It's not *very* early, to be sure, so where it causes problems might be edge cases, but worth having on the radar.

I did some experimentation with using lazy proxies for Filter and Servlet beans, since the container only needs them to register it's own metadata (paths and patterns etc.). That works up to a point, but not if the Filter (or Servlet) is a `@Bean` injected into a `ServletContextInitializer`, since the initializer gets instantiated anyway.

I also tried an approach where all the Filter and Servlet `@Beans` were replaced in a `BeanFactoryPostProcessor`, but that doesn't work if the concrete type declared in the `@Bean` definition is a subclass (since you don't know the concrete class from the `BeanDefinition` and you need it to prevent a `ClassCastException` at runtime when the factory method is finally executed).

**Comment by wilkinsona** [comment]
Closing in favour of #1605

**Comment by philwebb** [comment]
See also #4154 and #4165
