### ISSUE TITLE
Support multiple JWT issuer-uris

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-boot#30108]
Enhancement:

`spring.security.oauth2.resourceserver.jwt.issuer-uri` configuration property currently accepts a single value.

In some cases (like multi-tenant environments), resource-servers accept identities issued by more than just one authorization-server.

It would ease spring-boot apps security configuration if `spring.security.oauth2.resourceserver.jwt.issuer-uri` could accept an array of issuers.
Currently I have to use a private property for that purpose and that leads to quite some confusion for developers used to spring-boot one.

Notes: 
- properties and yaml files syntax would allow such a modification (`String` to `String[]`) without breaking existing config files 
- OAuth2ResourceServerProperties$Jwt backward compatibility can be achieved with:
```java
public class OAuth2ResourceServerProperties {
    public static class Jwt {
        // modified private property
        private String[] issuerUris;

        // untouched existing public interface
        /**
         * @deprecated Use {@link Jwt#getIssuerUris()} instead.
         */
        @Deprecated
        public String getIssuerUri() {
            if (this.issuerUris == null || this.issuerUris.length == 0) {
                return null;
            }
            if (this.issuerUris.length > 1) {
                throw new RuntimeException("Jwt#getIssuerUris() must be used when more than one issuer is configured");
            }
            return this.issuerUris[0];
        }

        // added functionnality
        public String[] getIssuerUris() {
            return this.issuerUris;
        }

        public void setIssuerUri(String... issuerUris) {
            this.issuerUris = issuerUris;
        }
    }
}

**Comment by emisbalu** [comment]
I (we as a team) would like to take this up

**Comment by EduColnago** [comment]
Is this issue available? I would like to try to do this

**Comment by ch4mpy** [comment]
https://spring.io/blog/2022/06/01/spring-security-oauth-reaches-end-of-life

I suggest you get a look at alternatives for spring-boot resource-servers auto-configuration. Maybe [this one I wrote](https://github.com/ch4mpy/spring-addons) ?

**Comment by wilkinsona** [comment]
@ch4mpy Spring Security itself provides OAuth support these days and Spring Boot provides auto-configuration for it. IMO, there's no need to look for an alternative.

**Comment by wilkinsona** [comment]
@EduColnago thanks for the offer but we're not quite sure how to handle this one yet. Please watch the ideal-for-contribution label.

**Comment by wilkinsona** [comment]
Given the Spring Security team's position on multiple issuer URIs and their decision to decline https://github.com/spring-projects/spring-security/issues/10943, I'm not sure that we should do anything in Spring Boot. IMO, it does not make sense to allow multiple URIs to be configured when Spring Boot's auto-configuration will only use one of them. This wouldn't address the confusion described in the description above, it would just change its source. I also don't think it makes sense for Spring Boot to support multiple issuer URIs if that requires us to maintain a composite `JwtDecoder` implementation that delegates to decoders created from the issuer URIs. IMO, such a class should be maintained as part of Spring Security so that all users can benefit from it, not just those using Spring Boot.

Flagging for team attention to see what everyone else thinks.

/cc @jzheaux

**Comment by ch4mpy** [comment]
> @ch4mpy Spring Security itself provides OAuth support these days and Spring Boot provides auto-configuration for it. IMO, there's no need to look for an alternative.

@wilkinsona I had read the blog post too fast. My bad.

But, actually I can find some reasons to look for alternatives to `spring-boot-starter-oauth2-resource-server` for OpenID resource-servers:
- it does not support multi issuers out of the box (reason for this ticket)
- it populates security-context with `JwtAuthenticationToken` which has very limited interface for claims. Nowadays, most authorization servers being OIDC, an `Authentication` implementation exposing OpenID claims would be usefull (at least when what we provide in configuration is a `.well-known/openid-configuration`).
- authorities parsing is made from `scope`claim, which is mostly useless and must be overriden in almost any app
- CORS config must be added in the code. "Pure" resource-servers (REST APIs without embeded client) always need CORS. It would be convenient to do it from properties without any java config.
- frequent resource-server flags must be done in the code too. It could be done from properties (without Java config). I'm thinking of: 
  - anonymous enabling (for public resources)
  - stateless session-management (user state in the token)
  - CSRF disabling
  - maybe some permit-all routes (public resources accessible to anonymous) and a default access (to isAuthenticated()?)

This are not just speculations, it is possible to achieve all of above with just a few properties: I do it [there](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_oauthentication)
with this app:
```java
@SpringBootApplication
public class ResourceServerWithOAuthenticationApplication {

	public static void main(String[] args) {
		SpringApplication.run(ResourceServerWithOAuthenticationApplication.class, args);
	}

	@EnableGlobalMethodSecurity(prePostEnabled = true)
	public static class WebSecurityConfig {
	}

}
```
and that config
```properties
# shoud be set to where your authorization-server is
com.c4-soft.springaddons.security.token-issuers[0].location=https://localhost:9443/auth/realms/master

# shoud be configured with a list of private-claims this authorization-server puts user roles into
# below is default Keycloak conf for a `spring-addons` client with client roles mapper enabled
com.c4-soft.springaddons.security.token-issuers[0].authorities.claims=realm_access.roles,resource_access.spring-addons.roles

# use IDE auto-completion or see SpringAddonsSecurityProperties javadoc for complete configuration properties list
```

As you could guess from `com.c4-soft.springaddons.security.token-issuers` being an array, it supports as many authorization-servers as needed, each with its own basic properties mapping: which claim(s) to get it from and with which basic processing (case and prefix).

> composite JwtDecoder implementation that delegates to decoders created from the issuer URIs

I do it with [JwtIssuerAuthenticationManagerResolver](https://github.com/ch4mpy/spring-addons/blob/ffefd695b1fc7f36cc7d74c071940b960047c159/webmvc/spring-security-oauth2-webmvc-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/config/synchronised/ServletSecurityBeans.java#L159) or   [ReactiveAuthenticationManagerResolver](https://github.com/ch4mpy/spring-addons/blob/ffefd695b1fc7f36cc7d74c071940b960047c159/webflux/spring-security-oauth2-webflux-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/config/reactive/ReactiveSecurityBeans.java#L117) (credits go to spring-security team who told me that it is the expected way to do it)

**Comment by philwebb** [comment]
Thanks @jzheaux. Given the comments above I don't think we should try to support multiple JWT issuer URIs. Thanks anyway for the suggestion and thanks for open-sourcing your springaddons project.

**Comment by ch4mpy** [comment]
> the reason the OAuth2 Client properties allow for declaring more than one client is to support multiple identity providers, like Google and Facebook

@jzheaux @philwebb how is the resource server supposed to handle end-users identity with a single configured authorization-server in that case? Should it choose Google or Facebook?

>  I appreciate the list of features you generated above, that's really helpful. You and I have discussed some of those already, and I'd welcome further collaboration to find what's a good fit for adding to Spring Security.

Those features are mostly configuration of existing spring-security elements, reason for me listing it here in spring-boot.

There are only two things I use which are not from spring-security:
- [`Authentication` implementation](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/OAuthentication.java) exposing [OpenID claims](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/OpenidClaimSet.java) (took me quite a few iteration to come to something as simple and usable since I opened ticket to refactor [`AbstractOAuth2Token`](https://github.com/spring-projects/spring-security/issues/6807))
- Test annotations, which were rejected too (I still haven't found how to use MockMvc post-processors or WebClient mutators to unit-test secured `@Components` such as `@Service` and `@Repository`)

> I'd welcome further collaboration to find what's a good fit for adding to Spring Security

Do not easitate to open tickets on https://github.com/ch4mpy/spring-addons if you find something useful for the comunity, I'll do my best to help you migrate corresponding code from this repo to spring-security or spring-boot ones.

**Comment by ch4mpy** [comment]
> Google's token is for protecting Google's resource servers

Only? https://developers.google.com/identity/sign-in/web/backend-auth

Beyond what Google offers as OAuth2 authentication, there are online OIDC providers out there which allows to define audience(s).

I have quite a few (dozens) resource-servers at hand that have to accept various issuers either because
- they serve clients from various editors, some sharing the same authorization-server and some having their own
- they serve a single client with different groups of users, each group having it's own identity provider (internal and external users are stored in different databases and are not authorized by the same server)

**Comment by jzheaux** [comment]
[Google's documentation](https://developers.google.com/identity/sign-in/web/backend-auth) refers to flowing the user's identity to a server, not to authorizing a client's request for resources protected by that server. If you haven't already, please see the link I posted in [my previous comment](https://github.com/spring-projects/spring-boot/issues/30108#issuecomment-1163509265). I also feel like the maintainers' comments [in this thread](https://github.com/IdentityServer/IdentityServer3/issues/2015) are a good representation of my position. That said, we might be getting off-topic discussing how various providers interpret the spec. 

The resource server arrangements you describe sound like classic multi-tenancy examples. I feel I already stated my position on changing Boot's properties from being single-tenant to multi-tenant, and I've got nothing more to add. Should multi-tenant resource servers become quite common, we can always take another look.

**Comment by jasonrberk** [comment]
what would be the correct / best approach to using `JwtAuthenticationConverter` in a multi tenant  situation?  Or, maybe conversely, how can we go about ignoring the issuer (let appealing, but might buy me some time)?

TL/DR - 

I too needed to handle a case of a resource server needing to trust tokens from two different issuers....and found this thread.  Very informative, so thanks for that.  The code I inherited has this:

```
 protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .cors()
                .and()
                .authorizeRequests(authorize ->
                        authorize
                                .mvcMatchers(routeSecurityConfig.getUnauthenticatedRoutes()).permitAll()
                                .anyRequest().authenticated())
                .oauth2ResourceServer()
                .jwt()
                .jwtAuthenticationConverter(getJwtAuthenticationConverter());
    }

    /**
     * By default, the resource server populates the authorities based on the "scope" claim
     * Our tokens are using the "authorities" claim, this provides the conversion.
     */
    private Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {
        JwtAuthenticationConverter converter = new JwtAuthenticationConverter();
        converter.setJwtGrantedAuthoritiesConverter(jwt -> {
            List<String> authorities = Optional.ofNullable(jwt.getClaimAsStringList("authorities"))
                    .orElse(List.of());
            return authorities.stream()
                    .map(SimpleGrantedAuthority::new)
                    .collect(Collectors.toList());
        });
        return converter;
    }
```

now when validating tokens that came from a different issuer, the issuer check fails as expected.  Moving to something like this, gets me past the issuer check:

```
JwtIssuerAuthenticationManagerResolver authenticationManagerResolver = new JwtIssuerAuthenticationManagerResolver
            ("https://ping-foo.company.com", "https://ping-bar.company.com");

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .cors()
                .and()
                .authorizeRequests(authorize ->
                        authorize
                                .mvcMatchers(routeSecurityConfig.getUnauthenticatedRoutes()).permitAll()
                                .anyRequest().authenticated())
                .oauth2ResourceServer(oauth2 -> oauth2
                        .authenticationManagerResolver(authenticationManagerResolver));
    }
```

but the `JwtAuthenticationConverter` is no longer user and as such, any place we use `@PreAuthorize(hasAuthority('xyz'))` will **never** be accessible as the `authorities` from the JWT are never mapped into the security context.
