### ISSUE TITLE
Anchor tag for Spring HATEOAS does not redirect properly

### ISSUE THREAD

**Issue by robertmcnees** [spring-projects/spring-boot#30106]
In the reference documentation from 2.6.4 and later versions, the anchor 
`#boot-features-spring-hateoas` points to a location that does not exist - `#features.developing-web-applications.spring-mvc.spring-hateoas`

As a result the [2.6.4 documentation](https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#boot-features-spring-hateoas) will not redirect to the appropriate location.  I believe the anchor should redirect to `#web.spring-hateoas` so that it [links correctly](https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#web.spring-hateoas)

**Comment by scottfrederick** [comment]
Closing in favor of #30107

**Comment by snicoll** [comment]
For the record this was broken as of `2.6.0` already.
