### ISSUE TITLE
Allow customization of single logout in auto-configured SAML relying party registration

### ISSUE THREAD

**Issue by ugrave** [spring-projects/spring-boot#30128]
Currently a auto configured relying party registration cannot be modified afterwards.

In my case i configured a ssaml single logout url via Spring Security. But i cannot set the configured logout url to autoconfigured `RelyingPartyRegistration.singleLogoutServiceLocation`.

```java
  @Bean
  SecurityFilterChain securityFilterChain(HttpSecurity http, RelyingPartyRegistrationRepository relyingPartyRegistrationRepository) throws Exception {
    RelyingPartyRegistrationResolver relyingPartyRegistrationResolver = new DefaultRelyingPartyRegistrationResolver(relyingPartyRegistrationRepository);
    Saml2MetadataFilter metadataFilter = new Saml2MetadataFilter(relyingPartyRegistrationResolver, new OpenSamlMetadataResolver());
    return http
      .saml2Login(Customizer.withDefaults())
      .saml2Logout(Customizer.withDefaults())
      .addFilterBefore(
        metadataFilter,
        Saml2WebSsoAuthenticationFilter.class
      )
      .build();
  }
```
I add the  `Saml2MetadataFilter` filter together with the `OpenSamlMetadataResolver` to make the relying party metadata available.
The `OpenSamlMetadataResolver` use the data from the `RelyingPartyRegistration`. 
Problem is know that the logout url is not part of the metadata because its not set in the `RelyingPartyRegistration`.

A solution could be to provide a way to customize the autoconfigured `RelyingPartyRegistration` before is is created.
Same think as it already exist for the `RestTemplate` with the `RestTemplateCustomizer`.

My current workaround is to skip the autocinfiguration and create and register the `RelyingPartyRegistration` by myself with my own `RelyingPartyRegistrationRepository` bean.

**Comment by mhalbritter** [comment]
I wonder why we only made some properties of the `RelyingPartyRegistration` configurable via `Saml2RelyingPartyProperties`. Maybe we should add `singleLogoutServiceLocation` in there, too?

**Comment by mhalbritter** [comment]
`singleLogoutServiceLocation` is new in Spring Security and our auto-configuration has been written before. We should add the `singleLogoutServiceLocation` to our properties to support that usecase.

@ugrave Would that solve your problem?

**Comment by ugrave** [comment]
This should work for me. 

There also some other missing: `singleLogoutServiceBinding​`, `singleLogoutServiceResponseLocation` and `nameIdFormat`.
Some of them are filled with values from the IDP metadata if available. (ex. the `singleLogoutServiceLocation` and `singleLogoutServiceBinding​` are filled with the values of asserting party details returnd be the IPD metadata).

**Comment by bameur** [comment]
Hello.
if I understand correctly, the SLO is not currently compatible with autconfiguration based on the config parameters. We need to code the instantiation of the RelyingPartyRegistration to be able to insert the slo conf!
Is that right?
Thank you in advance.

**Comment by mhalbritter** [comment]
Yes, see the workaround in the first message.

**Comment by bameur** [comment]
Thank you @mhalbritter.
will the next update contain the necessary config for the SLO. I just want to know if I should schedule the adaptation of my projects or I'm waiting for the update.

**Comment by wilkinsona** [comment]
We can't say for certain at this time. As shown by its milestone, we hope to address this issue in Spring Boot 2.7 but that's not guaranteed. It may have to be deferred until a later milestone if other work takes priority.

**Comment by bameur** [comment]
ok I understand, thank you for your feedback. no other workaround? my current code is the following (I don't want to impact it too much):
`// @formatter:off
        http
                .cors(Customizer.withDefaults())
                .csrf().disable()
                .exceptionHandling()
                .authenticationEntryPoint(new HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED)).and()
                .authorizeHttpRequests((authorize) -> authorize.anyRequest().authenticated())
                .requestMatcher(new RequestNotInHeaderRequestMatcher("access-token"))
                .saml2Login((saml2Login) -> saml2Login.loginProcessingUrl("/login/saml2/sso")
                                            //.authenticationManager(new ProviderManager(authenticationProvider))
                                            .successHandler(new Saml2AuthenticationSuccessHandler(OAUTH2_CLIENT_ID, OAUTH2_CLIENT_SECRET, OAUTH2_AUTHORIZATION_GRANT_TYPE, OAUTH2_TOKEN_URI))
                                            .failureHandler(new Saml2AuthenticationFailureHandler()))
                .saml2Logout((saml2Logout) -> saml2Logout
                                              .logoutRequest( logoutRequestConfigurer ->  logoutRequestConfigurer
                                                                                        .logoutUrl("/logout/saml2/slo"))
                                              .logoutResponse(logoutResponseConfigurer -> logoutResponseConfigurer
                                                                                        .logoutUrl("/logout/saml2/slo"))

                )
                .rememberMe((rememberMe) -> rememberMe
                        .rememberMeServices(rememberMeServices()))
                .sessionManagement((sessionManagement) -> sessionManagement
                        .maximumSessions(2)
                        .sessionRegistry(sessionRegistry())
                );
        // @formatter:on`
