### ISSUE TITLE
Dir and directory are used inconsistently in configuration properties

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3017]
```
server.tomcat.basedir
spring.hornetq.embedded.data-directory
spring.jta.log-dir
```

**Comment by snicoll** [comment]
point taken. `dataDirectory` is a concept in HornetQ actually. That's why it was mapped like that.

**Comment by wilkinsona** [comment]
The HornetQ support has been deprecated so this inconsistency will go away when it's removed.
