### ISSUE TITLE
Upgrade to Spring Data 2021.2.0-M4

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#30185]
I start a fresh one similar to this:

https://github.com/spring-projects/spring-boot/issues/29765

Project Dependencies Spring Data 2021.2.0-M4

* Neo4j Driver (org.neo4j.driver:neo4j-java-driver): 4.4.4

**Comment by mp911de** [comment]
Project Dependencies Spring Data 2021.2.0-M4

* Cassandra Driver (com.datastax.oss:java-driver-bom): 4.14.0
* Couchbase Client (com.couchbase.client:java-client): 3.2.6 (requires upgrade in Spring Data)
* Elasticsearch (org.elasticsearch.client:elasticsearch-rest-high-level-client): 7.17.1
* Jedis (redis.clients:jedis): 3.8.0
* Lettuce (io.lettuce:lettuce-core): 6.1.7.RELEASE (6.1.7 to be released)
* MongoDB (org.mongodb:mongodb-driver-core): 4.5.0
* Neo4j Driver (org.neo4j.driver:neo4j-java-driver): 4.4.3
* Spring LDAP (org.springframework.ldap:spring-ldap-core): 2.4.0-M2
