### ISSUE TITLE
Make StringToEnumIgnoringCaseConverterFactory public

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-boot#3021]
For Spring XD we ran into the need to have a more lenient enum converter. The functionality provided by `StringToEnumIgnoringCaseConverterFactory` is pretty much what we need, but unfortunately it is private, and hence we had to copy the code. 

See also: https://jira.spring.io/browse/XD-3066

**Comment by snicoll** [comment]
How about using the `RelaxedConversionService` then? That one is public.

**Comment by wilkinsona** [comment]
Given the lack of response to @snicoll's suggestion, I'm going to assume that this is no longer needed. We can reopen this if that turns out to not be the case.

**Comment by michaldo** [comment]
I would like to use enum binding ignoring case in Spring MVC binding.  I think simplest way is write `WebMvcConfigurer` with

    @Override
     public void addFormatters(FormatterRegistry registry) {
        registry.addConverterFactory(new StringToEnumIgnoringCaseConverterFactory());
    }

But `StringToEnumIgnoringCaseConverterFactory` is package private and `RelaxedConversionService` has gone.
Please give next suggestion

**Comment by wilkinsona** [comment]
I believe that'll work without configuring Spring MVC in 2.1 as the `ApplicationConversionService`, with which `StringToEnumIgnoringCaseConverterFactory` is registered, is now registered by default with the application context.

**Comment by michaldo** [comment]
Unfortunately, not. Spring Boot MVC 2.10 use `WebConversionService`, which is different than `ApplicationConversionService`

Fortunately, I found solution https://stackoverflow.com/a/52978020 which works in my case. But I feel a bit uncomfortable when I have to add bunch of converters (ApplicationConversionService.addApplicationConverters()) when I need only one

**Comment by wilkinsona** [comment]
Ah, yes. I'd forgotten about the different `WebConversionService`. Thanks for the reminder. I've opened https://github.com/spring-projects/spring-boot/issues/15019 to review the differences between the two and consider aligning them.
