### ISSUE TITLE
application.properties not loaded after restart

### ISSUE THREAD

**Issue by akosratku** [spring-projects/spring-boot#3023]
I noticed a very strange behaviour about the loading of the properties file. I place the external application.properties file right next to the compiled jar. At first start everything works as expected the properties get loaded from the file and injected into the beans using it. The bug happens after restarting the application when the properties file simply gets ignored. If i stop the application, insert a few new lines at the end of the file and touch the file to 5 minutes before (setting access time with touch command) it works as expected.

Operating system is Debian Wheezy 7.8.

Do you have any idea what would cause such behaviour? We have several applications, all produces the same and i couldn't find anything after several hours of debugging.

**Comment by dsyer** [comment]
"Next to the jar" is not a special place for Spring Boot. How are you restarting the app? Maybe you are doing it from the wrong directory?

**Comment by akosratku** [comment]
I am referring to the 8. point of this list: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html . I kill (-9) the process and restart it (java -jar). I address everything with absolute path.

**Comment by dsyer** [comment]
Point 7. in that list refers to properties files in the current working directory (the location of the jar is irrelevant). Does that help?

**Comment by rajjaiswalsaumya** [comment]
Dave is right. Boot loads properties from current working dir or from config dir in current working dir when app run from jar. I already suffered with this several times when i fiddled asking Dave about the issue and read docs 10 times, when i realised about current dir fact. But i m not sure how your app runs first time at start. May be it is loading properties packed inside jar ? When you change things and restart, after touch how that seems to work ? Give a try running jar from the same dir and keep application.properties in config dir inside the dir in which jar is kept.

running java -jar blabla.jar will sure pick your properties.

If that too fails 
try 
java -jar spring.config.location=location of parent of property file blabla.jar.


I even suggest adding this in your pom.xml

<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/config</outputDirectory>
							<resources>
								<resource>
									<directory>${basedir}/src/main/resources</directory>
									<includes>
										<include>*.properties</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>


   This copies all properties in config dir in your target. just copy both and start app as 
java -jar blabla.jar from dir having jar

**Comment by akosratku** [comment]
Thanks for your responses.

My directory structure looks like this:

- /var/data/appdirectory/
 - app.jar
 - application.properties

I start the app with java -jar /var/data/appdirectory/app.jar and everything works for the first time. The properties are not loaded from inside the jar simply because they are not there. I will try to explicitly set the location of the config file.

The strange thing is i am using scripts to start and stop the app so they do exactly the same every time, the only change in the enviroment is a few new line at the end of the properties file.

**Comment by akosratku** [comment]
I modified the script to cd /var/data/appdirectory and after that java -jar app.jar . Works like a charm. I am now certain that the new line was in fact unimportant, but the key was i stepped into the working directory and ran the script. 

Thanks for your help!
