### ISSUE TITLE
Replace our use of SpringFactoriesLoader#loadFactoryByNames by new infrastructure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#30235]
With https://github.com/spring-projects/spring-framework/pull/28057 available now, we can move our own use of `loadFactoryByNames`.

**Comment by philwebb** [comment]
We removed `Log` injection into `ConfigDataLoader` but I think we can support it again now the Framework code is more flexible.

**Comment by philwebb** [comment]
Actually we can't support it because we need the declaring class. The best we can do is throw an exception rather than injecting `null`.

**Comment by wilkinsona** [comment]
Given that the change is in a new major, do we really need to throw an exception?

**Comment by wilkinsona** [comment]
Looks like the change to throw an exception has been done in https://github.com/spring-projects/spring-boot/commit/693941c2c2c8e9ecfec6e3a4471567e6723b0e38. I'll close this then as the impact is pretty minimal.

**Comment by philwebb** [comment]
Spring Cloud found this one when upgrading. We might want to consider argument resolution in general because I think it would be nice to always fail rather than inject `null`.
