### ISSUE TITLE
The @requestBody annotation loses data starting with eB 

### ISSUE THREAD

**Issue by shkingve** [spring-projects/spring-boot#30233]
my log is
[log.txt](https://github.com/spring-projects/spring-boot/files/8260689/log.txt)
 
my code is 
[code.txt](https://github.com/spring-projects/spring-boot/files/8260693/code.txt)

I'm using version 2.6.4

**Comment by shkingve** [comment]
The request json is {"e1":"asfd","exsf":"fa","eBaysf":"dfsd","eBdf":"dd"}

**Comment by bclozel** [comment]
Could you turn this code snippet into a real project we can git clone/download and run to reproduce the behavior you're seeing? There might be many other problems that are not linked to your controller. A complete project reproducing the problem would be really useful.

**Comment by shkingve** [comment]
ok

**Comment by shkingve** [comment]
https://github.com/shkingve/demo.git

**Comment by bclozel** [comment]
Changing the `com.example.demo.controller.TestController.DDSs` class from a Lombok `@Data` class to a vanilla Java class solves the problem. I guess this is linked to how Lombok handles the getter/setter generation depending on the field name.

**Comment by shkingve** [comment]
Yes,because of lombok
