### ISSUE TITLE
log4j2 auto-reload does not work with spring boot

### ISSUE THREAD

**Issue by aheusingfeld** [spring-projects/spring-boot#3024]
Log4j2 has an [auto-reload feature](https://logging.apache.org/log4j/2.x/manual/configuration.html#AutomaticReconfiguration) but it unfortunately does not work with Spring Boot!
The reason is that `org.springframework.boot.logging.log4j2.Log4J2LoggingSystem:152` always uses `new ConfigurationSource(url.openStream(), url);` and Log4j2 considers reloading only possible for files.

### Suggestion:
If `logging.config` is a file (we could e.g. use `ResourceUtils.isFileURL()`), use the constructor `ConfigurationSource(final InputStream stream, final File file)` instead. If you like, I can propose a pull-request.

You might also want to take a look at https://issues.apache.org/jira/browse/LOG4J2-911 and https://issues.apache.org/jira/browse/LOG4J2-913 which is a feature request for Log4j 2 to also enable auto-reload for URLs.

**Comment by snicoll** [comment]
Thanks Alex! If you can propose a PR that'd be great.

**Comment by aheusingfeld** [comment]
@snicoll any chance we can ship this soon? This "non-reasonable" feature is a blocker in one of my projects. Thanks in advance for your support.

**Comment by aheusingfeld** [comment]
@snicoll would this fix be available quicker if I backported it to the 1.2.x branch? I'm asking as this is currently blocking one of my projects. Thanks for your support.

**Comment by snicoll** [comment]
No. `1.3.0.M1` is going to be released early June (at the same time as `1.2.4` I guess even though we don't have concrete plan for that AFAIK). 

Note that you can "unblock" yourself _now_ if you really want to. Just add your custom `LoggingSystem` implementation somewhere (let's say `com.acme.YourLog4j2LoggingSystem`) and add the following system property when you start your boot application: `-Dorg.springframework.boot.logging.LoggingSystem=com.acme.YourLog4j2LoggingSystem` - Look at [LoggingSystem](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/LoggingSystem.java#L91) for more details.

Hope that helps.

**Comment by aheusingfeld** [comment]
Awesome! `System.setProperty(LoggingSystem.class.getName(), Log4J2LoggingSystem.class.getName());` works like a charm! Thanks, pal!

**Comment by snicoll** [comment]
:+1:
