### ISSUE TITLE
Support to HTTP/2 - Undertow

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3025]
Hi all,

I am trying to enable HTTP/2 in my application with Spring Boot Undertow, but there's no parameter for the property "enable-http2=true" as in Wildfly shows. 
http://undertow.io/blog/2015/03/26/HTTP2-In-Wildfly.html

Is there any way beyond those properties above?

server.port = 8443
server.ssl.key-store = classpath:sample.jks
server.ssl.key-store-password = secret
server.ssl.key-password = password

Thanks

**Comment by ofbizbrazil** [comment]
Finally, I did it!!!

	@Bean
	public UndertowEmbeddedServletContainerFactory embeddedServletContainerFactory() {
		final UndertowEmbeddedServletContainerFactory undertowEmbeddedServletContainerFactory = new UndertowEmbeddedServletContainerFactory();
		undertowEmbeddedServletContainerFactory
				.addBuilderCustomizers(new UndertowBuilderCustomizer() {
					@Override
					public void customize(final Builder builder) {
						builder.setServerOption(UndertowOptions.ENABLE_SPDY,
								true);
					}
				});
		return undertowEmbeddedServletContainerFactory;
	}


And do no forget to set in your java execution -Xbootclasspath/p:C:\wildfly-9.0.0.CR1\bin\alpn-boot-8.1.3.v20150130.jar

**Comment by gurinderu** [comment]
Did you test SPDY with UndertowBuilderCustomizer ? 
I enabled this feature in my application and chrome latest version use http 1.1, but for google.com they use http2

**Comment by wilkinsona** [comment]
@gurinderu Did you also configure your JVM's bootclasspath with the ALPN jar?

**Comment by gurinderu** [comment]
@wilkinsona No, Could you assist how I can change bootclasspath in gradle?
