### ISSUE TITLE
 Are there any plans to translate the reference documentation for this project into other languages?

### ISSUE THREAD

**Issue by awxiaoxian2020** [spring-projects/spring-boot#30269]
I want to translate the reference documentation into Chinese and be included and supported by this project. What should I do?

**Comment by bclozel** [comment]
From [my understanding of the legal notice attached to the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/legal.html#legal), nothing prevents you from translating the docs and distributing them, as long as the original copyright and legal notices are there.

We don't plan on publishing translations as we don't have the time nor resources to maintain the documentation in multiple languages.

**Comment by HelloVonLea** [comment]
> From [my understanding of the legal notice attached to the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/legal.html#legal), nothing prevents you from translating the docs and distributing them, as long as the original copyright and legal notices are there.
> 
> We don't plan on publishing translations as we don't have the time nor resources to maintain the documentation in multiple languages.

I think it's a good idea that Spring documents are translated into multiple languages. It doesn't matter that you or someone else do that. Just a link for the foreign version, which will exactly help those whose mother tongue is not English and who are not good at English. For example, your language is English, but Spring documents are Arabic or Chinese. How hard it is! I hope there is a plan to translate the reference documentation to help people around the world. Please think about it.

**Comment by snicoll** [comment]
@HelloVonLea we certainly don't deny it would be useful. What we indicated is that we unfortunately don't have the time nor resources to do so.

**Comment by HelloVonLea** [comment]
> @HelloVonLea we certainly don't deny it would be useful. What we indicated is that we unfortunately don't have the time nor resources to do so.

Yes, I completely understand. You have made great contributions. I take my hat off to you. What I'm trying to say is whether or not it is feasible to give others an opportunity. People can do it in other countries.

**Comment by snicoll** [comment]
> What I'm trying to say is whether or not it is feasible to give others an opportunity. People can do it in other countries.

Brian already replied to that in [his first comment](https://github.com/spring-projects/spring-boot/issues/30269#issuecomment-1070891000). This is totally possible as long as you comply with the license, which isn't much really.

**Comment by HelloVonLea** [comment]
All right, thank you. I hope I could find it on official website in the future.
