### ISSUE TITLE
Race condition with Jersey starter in a deployed WAR

### ISSUE THREAD

**Issue by fbiville** [spring-projects/spring-boot#3028]
You can find more information here: http://stackoverflow.com/questions/29629992/mapping-conflict-when-deploying-with-spring-boot-jersey-starter-deployed-as-war.

This is not 100% reproducible in all environments. When it is, though, it reliably fails every time.

**Comment by dsyer** [comment]
I'm not sure there is much value in using the Spring Boot autoconfiguration stuff for Jersey in a WAR file. Do you need it?

**Comment by fbiville** [comment]
The most frustrating part is that I don't really need it. This is a decision I have to live with for now.

**Comment by snicoll** [comment]
Can't we turn this one into a documentation request based on the SO answer?

**Comment by dsyer** [comment]
I think so

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
