### ISSUE TITLE
Allow the embedded web server to be shut down gracefully without a timeout

### ISSUE THREAD

**Issue by zdaccount** [spring-projects/spring-boot#30283]
Now there is the graceful shutdown feature (https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.graceful-shutdown), but this feature uses a timeout, and only waits within the timeout. But sometimes I want to wait till all the requests are processed, without a timeout. Could you please support this?

**Comment by wilkinsona** [comment]
This duplicates the discussion that’s already taking place on #4657.
