### ISSUE TITLE
supervision support

### ISSUE THREAD

**Issue by xfcjscn** [spring-projects/spring-boot#3029]
as spring boot provide dsr, the process need to be supervisored in production env.

can i know whether your team gonna to add such feature in your future plan?

**Comment by dsyer** [comment]
What's "dsr"? I assume by "supervisored" you mean "enabled as a system service, so that it starts and stops in a standard way with the operating system, and can be kept alive if it dies"? See #519 for that.

**Comment by xfcjscn** [comment]
Stuff discussed in #519 is exactly what I want. Thanks @dsyer
