### ISSUE TITLE
Add a naming-strategy property to MongoProperties

### ISSUE THREAD

**Issue by emersonf** [spring-projects/spring-boot#3031]
à la `spring.jpa.hibernate.naming-strategy`, but one that takes a `org.springframework.data.mapping.model.FieldNamingStrategy` to customise the `MongoMappingContext` in `MongoDataAutoConfiguration`.

Or if there's an easy way to customise it, please let me know.

**Comment by izeye** [comment]
@snicoll I guess the milestone needs to be changed to 1.3.0.M2.

**Comment by snicoll** [comment]
good catch, thanks!
