### ISSUE TITLE
Report that an auto-configuration using the old registration format is no longer considered

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#30324]
Now that we expect auto-configurations to be registered in an alternative mechanism, we should provide some sort of warning/exception for those who are in `spring.factories` still.

When looking into this, we should consider the case of a starter offering support for both the old and the new mechanism and only considering this as an error if the auto-configuration is only registered in `spring.factories`.

To avoid doing this search on startup, perhaps  we should consider giving this extra information when the application has failed to start?

**Comment by philwebb** [comment]
Given the limited amount of time left, and the fact that this mainly affects integrators I'm tempted to close this and rely on the release notes instead. Flagging for team opinions.
