### ISSUE TITLE
Missing space in log message

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3033]
With `--debug` option I see the following messages:

```

DEBUG [main] --- ConfigFileApplicationListener: Skipped config file 'file:./config/application-test.xml' for profile testresource not found
DEBUG [main] --- ConfigFileApplicationListener: Skipped config file 'file:./config/application.xml' for profile testresource not found
```
There is a missing space in message. It should be: "... for profile test resource not found" instead of "... for profile testresource not found".

I believe that this line should be fixed: https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L395

**Comment by snicoll** [comment]
Thanks for the report!
