### ISSUE TITLE
MessageSourceAutoConfiguration: is it possible to provide a way for disabling falling back to system locale?

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3038]
I have configuration that is very similar to `MessageSourceAutoConfiguration` but with one little exception: I'm invoking `messageSource.setFallbackToSystemLocale(false)`.

Is it possible to provide a way to do the same thing in Spring Boot auto configuration? Or may be we may disable falling back to system locale by default?

**Comment by dsyer** [comment]
Of course it's possible, but you can probably do it your self by `@Autowiring` the `MessageSource` and downcasting to `ResourceBundleMessageSource`.

**Comment by snicoll** [comment]
Duplicates #3749
