### ISSUE TITLE
MessageSourceAutoConfiguration: consider replacing ResourceBundleMessageSource by ReloadableResourceBundleMessageSource

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3039]
Why `MessageSourceAutoConfiguration` creates `ResourceBundleMessageSource` instead of `ReloadableResourceBundleMessageSource`? Javadoc of `ResourceBundleMessageSource` says: "Consider ReloadableResourceBundleMessageSource for an alternative that is capable of refreshing the underlying bundle files."

So, why don't use `ReloadableResourceBundleMessageSource`?

**Comment by dsyer** [comment]
`ReloadableResourceBundleMessageSource` has some cost at runtime, so I assume it isn't used by default because you wouldn't necessarily want it in production.

**Comment by philwebb** [comment]
The recommended approach since 1.3 is to use Devtools.
