### ISSUE TITLE
Hystrix and @ActiveProfiles: IllegalStateException: Another strategy was already registered

### ISSUE THREAD

**Issue by kimsaabyepedersen** [spring-projects/spring-boot#3041]
Hi

I use Hystrix in my spring boot project. Some tests run using:
```
@ActiveProfiles({ "SomeProfile"})
```

A test that causes Hystrix to go haywire has this:
```
@ActiveProfiles({ "SomeOtherProfile"})
```

This makes hystrix fail with:

```
Caused by: java.lang.IllegalStateException: Another strategy was already registered.
	at com.netflix.hystrix.strategy.HystrixPlugins.registerCommandExecutionHook(HystrixPlugins.java:262)
```

Spring does not seem to reset Hystrix properly when creating a "new" context for that test.

If I add this to the test that fails, it works but I would expect Spring Test framework to handle that for me:

```
@BeforeClass
    public static void beforeClass(){
    Hystrix.reset();
}
```
Best regards and rock on
Kim

**Comment by kimsaabyepedersen** [comment]
Upon further investigation this might be the real issue:

Some test run using:
@ActiveProfiles({ "SomeProfile"})

The test that causes Hystrix to go haywire has this:
@ActiveProfiles({ "SomeOtherProfile"})

But Spring does not seem to reset Hystrix properly when creating a "new" context for the that test.

**Comment by dsyer** [comment]
It's possible this could be worked around in SpringCloud, but I doubt there is anything SpringBoot can do to help.

**Comment by kimsaabyepedersen** [comment]
@dsyer should create it in spring cloud project instead?

**Comment by dsyer** [comment]
I guess.

**Comment by kimsaabyepedersen** [comment]
Created https://github.com/spring-cloud/spring-cloud-netflix/issues/365 instead.
