### ISSUE TITLE
Dependencies of a newly published Gradle plugin may not be available from the Plugin Portal/JCenter

### ISSUE THREAD

**Issue by zromano** [spring-projects/spring-boot#30414]
spring-boot-buildpack-platform/2.6.5/ files missing in the Gradle repo

Repro:
Go to https://start.spring.io/ and create a project with Spring `2.6.5` and Gradle. It will fail because the files here are missing: https://repo.gradle.org/ui/native/jcenter/org/springframework/boot/spring-boot-buildpack-platform/2.6.5/

**Comment by bclozel** [comment]
This artifact is still resolving intermittently from my side. I guess the 404 response is being cached by Gradle's JCenter mirror's CDN. [The status website](https://status.gradle.com/) looks fine.

**Comment by zromano** [comment]
Yeah, the POM is resolving for me now so I'm unblocked. Looks like some of the files are still missing though when I load that page.

Just for documentation, here is the error I got:
```
$ ./gradlew --build-cache --gradle-user-home cache/ clean build jacocoTestReport sonarqube -Dsonar.qualitygate.wait=true
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'service-user'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.springframework.boot:spring-boot-buildpack-platform:2.6.5.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/springframework/boot/spring-boot-buildpack-platform/2.6.5/spring-boot-buildpack-platform-2.6.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > org.springframework.boot:org.springframework.boot.gradle.plugin:2.6.5 > org.springframework.boot:spring-boot-gradle-plugin:2.6.5
   > Could not find org.springframework.boot:spring-boot-loader-tools:2.6.5.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/springframework/boot/spring-boot-loader-tools/2.6.5/spring-boot-loader-tools-2.6.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > org.springframework.boot:org.springframework.boot.gradle.plugin:2.6.5 > org.springframework.boot:spring-boot-gradle-plugin:2.6.5
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 10s
```

**Comment by zromano** [comment]
Not sure if you can upload the JFrog artifacts prior to release, but would be great if they were available when the Maven update comes out   🙂

**Comment by bclozel** [comment]
We are publishing our Gradle plugin as part of our release pipeline. In this case the Gradle JCenter mirror (which goal is to mirror Maven Central if I'm not mistaken) is out of sync, or failures are cached for a while by the CDN (and this can depend on your location).

I don't know if we can improve the process here.

**Comment by wilkinsona** [comment]
> Not sure if you can upload the JFrog artifacts prior to release

We can't as we don't have write access to that repository.

One thing that we could do in the meantime is to encourage users to configure `mavenCentral()` as a plugin repository. This would allow the plugin's dependencies (and the plugin itself) to be downloaded from their canonical source, even when the Plugin Portal or JCenter is down.

Another option would be to shadow all of the Gradle plugin's dependencies into its jar so that the artifact in the Plugin Portal contains everything that's needed.

**Comment by wilkinsona** [comment]
I've discussed this with the Gradle team and they have recommended that we don't do anything at this time. They are looking into improving things on their side. We can reconsider if this causes problems with the next release. Closing for now at least.

**Comment by antoniolucasnobar** [comment]
Just for you guys to know, I am having the same problem with version 2.6.6 (important because of spring4shell vulnerability).
I really do not know what to do. Sit and wait does not seem to be cool...

**Comment by antoniolucasnobar** [comment]
Thank you very much @mxab !

This solved my urgent problem. But we use a private nexus in our company and I do not know if I can keep this configuration. 

Your suggestion is a one-time solution? Or everytime we need to update SpringBoot right after their release I have to do that?

One more time, thank you!

**Comment by YeonCheolGit** [comment]
@mxab 
This works for me. Thanks:)

**Comment by Archsx** [comment]
> put this at the top of your `settings.gradle`
> 
> ```groovy
> pluginManagement {
>     repositories {
>         mavenCentral()
>         gradlePluginPortal()
>     }
> }
> ```

Hi, what if I use IDEA to create a project with kotlin, the settings.gradle.kts have only one line : 
```
rootProject.name = "myProjectName"
```
what code  should I put here ?

**Comment by wilkinsona** [comment]
@Archsx I believe the Kotlin syntax is identical in this case:

`settings.gradle.kts`:

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "myProjectName"
```

**Comment by Archsx** [comment]
> @Archsx I believe the Kotlin syntax is identical in this case:
> 
> `settings.gradle.kts`:
> 
> ```
> pluginManagement {
>     repositories {
>         mavenCentral()
>         gradlePluginPortal()
>     }
> }
> 
> rootProject.name = "myProjectName"
> ```

thank  you ! I'm new to kotlin so I asked the question, it works. but the code looks like diffrent sytle.

**Comment by sungmin69355** [comment]
> @Archsx I believe the Kotlin syntax is identical in this case:
> 
> `settings.gradle.kts`:
> 
> ```
> pluginManagement {
>     repositories {
>         mavenCentral()
>         gradlePluginPortal()
>     }
> }
> 
> rootProject.name = "myProjectName"
> ```

How does the code above work on a multi-module?

**Comment by wilkinsona** [comment]
`settings.gradle` and `settings.gradle.kts` apply to all modules in the build.
