### ISSUE TITLE
 GzipFilterProperties for configuring the Jetty gzip filter is wrong

### ISSUE THREAD

**Issue by Corni** [spring-projects/spring-boot#3042]
Hey,

you got some typos in the properties for the jetty gzip filter:
* `excludedAgentPatterns` should be `excludeAgentPatterns`
* `excludedPaths` should be `excludePaths`
* `excludedPathPatterns` should be `excludePathPatterns`.

This means that these properties don't work at all :-(

Maybe you could expose `excludedMimeTypes` as well.

**Comment by snicoll** [comment]
good catch, thanks!
