### ISSUE TITLE
Break build if entries in additional-spring-configuration-metadata.json are not sorted

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#30438]
I sorted the properties by name in #30434.

We should add something to the `ConfigurationPropertiesPlugin` which checks if they are sorted and if not, break the build.

**Comment by MatheusPK** [comment]
Hi, everyone! My team would like to tackle this one. is it ok?

**Comment by mhalbritter** [comment]
Hi! Yes, go ahead! I'll assign the issue to you.

**Comment by wilkinsona** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/a1443d1cdc7faa85b47507452139c17940b42f30.
