### ISSUE TITLE
Spring boot base url redirect

### ISSUE THREAD

**Issue by mmesnjak** [spring-projects/spring-boot#3043]
Hi,

I've setup Spring Boot + Primefaces project and so far I'm satisfied particulary with facelets recognizing Spring Beans and Services (SpringBeanFacesELResolver).
Now I would like to configure application so that base URL would translate into faces base URL.
For example: http://localhost:8080/ to be redirected to http://localhost:8080/index.xhtml

Could you please provide such example in samples?

**Comment by benneq** [comment]
Write a controller with RequestMapping(value="",method=RequestMethod.GET) and make a redirect.

Have a look here: http://stackoverflow.com/questions/17955777/redirect-to-an-external-url-from-controller-action-in-spring-mvc

**Comment by mmesnjak** [comment]
Thanks, that did it!
