### ISSUE TITLE
Move multipart.* to spring.http.multipart.*

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3044]
`multipart` should not be a root context on its own. I am not sure where it should go though; `spring.mvc` does not sound right; `spring.web` does not exist yet. `spring.multipart`?

That's a breaking change obviously. The sooner, the better.

**Comment by wilkinsona** [comment]
`spring.http.multipart`? We already have a few `spring.http` properties.

**Comment by snicoll** [comment]
Even better IMO

**Comment by wilkinsona** [comment]
Shall we do this in 1.4?

**Comment by philwebb** [comment]
Yes
