### ISSUE TITLE
The referred version of Hibernate jpamodelgen did not work when upgrading to 3.0.0-M2

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#30445]
The reproduce example: https://github.com/hantsy/spring6-sandbox/blob/master/boot
* Spring Boot 3.0.0-M2
* Java 17
* Maven

I have configured annotation processors: Lombok, Hibernate JpaModelGen, and QueryDSL in this project, when upgrading Spring Boot to 3.0.0-M2, and compiling the project, all JPA metadata models are broke.

When I specify `hibenate-jpamdolegen-jakarta` to an older version, eg. 5.6.5.Final, check here: https://github.com/hantsy/spring6-sandbox/blob/master/boot/pom.xml#L71 it worked again.

Reproduce steps:
1. Remove the version in https://github.com/hantsy/spring6-sandbox/blob/master/boot/pom.xml#L71
2. Compile the project.

**Comment by wilkinsona** [comment]
Thanks for tracking the problem down to `hibenate-jpamdolegen-jakarta`. It appears to be a regression in `5.6.6.Final`. There's nothing we can do about this in Boot. Please report the problem to the Hibernate team.
