### ISSUE TITLE
AOP failure when circular reference and @Scheduled springboot 2.6.2

### ISSUE THREAD

**Issue by G-XD** [spring-projects/spring-boot#30444]
annotation:
```
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface RedissonLock {
    String key();
    int timeout() default 60;
}
```
The method **lockTest()** will not be intercepted by AOP :
```
@Component
public class LockTest1 {

    @Autowired
    private LockTest2 lockTest2;

    private static final SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");

    public String key = "test";

    @RedissonLock(key = "#root.targetClass.getName()")
    @Scheduled(cron = "1/10 * * * * ? ")
    public void lockTest() throws InterruptedException {
        System.out.println("Scheduled task：" + dateFormat.format(new Date()));
    }
}

@Component
public class LockTest2 {

    @Autowired
    private LockTest1 lockTest1;

    public void callLockTest1() throws InterruptedException {
        lockTest1.lockTest();
    }
}
```
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/38717659/160230340-6e0e10bf-624d-462c-b0db-c290a7943d68.png">

The class **LockTest1** is not represented by cglib in org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor#postProcessAfterInitialization

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/38717659/160230383-3ddbee3c-da2f-41d9-ab5d-a6356fb44bde.png">

See demo: https://github.com/G-XD/aop-failure

**Comment by wilkinsona** [comment]
Thanks for the sample. The loss of the proxy is a side-effect of the steps that Spring Framework has to break the dependency cycle. You should either restructure your application to avoid the cycle, or "break" it yourself using `@Lazy` on the injection point or injecting an `ObjectProvider`.
