### ISSUE TITLE
AutoConfig Saml2Logout is not available / Feature added in spring-security 2.6

### ISSUE THREAD

**Issue by bameur** [spring-projects/spring-boot#30452]
https://github.com/spring-projects/spring-boot/blob/6865f1f3d913a40192570d51857664edd2ed5a48/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyProperties.java#L36

The configuration of the smal2 logout (added in spring-security version 2.6) is not declared in the autoconfigure. Will this be included in the next release?

**Comment by wilkinsona** [comment]
Duplicates #30128.
