### ISSUE TITLE
Configure RSocket support in GraphQL

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#30453]
Since spring-projects/spring-graphql#339, Spring for GraphQL also allows RSocket transport.
Spring Boot should also support this by auto-configuring a Controller that, using `RSocketGraphQlHandler`, handles RSocket messages at a configured path.

**Comment by rstoyanchev** [comment]
Note there is also an `RSocketGraphQlClient` and `RSocketGraphQlTester` which use `RSocketRequester`. 

Currently, if you start with  `RSocketGraphQlClient.builder()`, it will create a new `RSocketRequester.Builder` and set the `dataMimeType` to "application/graphql+json", but if you start with `builder(RSocketRequester.Builder)`, which could be the builder from Boot's RSocket starter, then you'd have to make it `builder(RSocketRequester.Builder).dataMimeType("application/graphql+json")`. Either the Boot start should provide an `RSocketRequester.Builder` for GraphQL or we could set the `dataMimeType` even when we are given a builder.

In any case, if we there isn't anything to be added on the Boot side for the client or tester, a short update in the documentation with guidance would also make sense.
