### ISSUE TITLE
Add `172.16/19` to `Tomcat.internalProxies`

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3046]
The original RegEx that we copied was updated in this commit: https://github.com/apache/tomcat/commit/c1be72fde7b8f4b0ab4059a72bda422e288a3337

We should update our code (also the docs)

**Comment by fhanik** [comment]
https://github.com/spring-projects/spring-boot/commit/1fe1aa893941f7f1bf891fa7421706d575ca5c37

**Comment by wilkinsona** [comment]
This duplicates https://github.com/spring-projects/spring-boot/issues/2699. I don't think the change should be made in a maintenance release.
