### ISSUE TITLE
Modify SolrServerAutoConfiguration to work with LBHttpSolrServer using internal zookeeper

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#3047]
Can we just modify SolrAutoConfiguration.java to create SolrServerCloud if solr hosts are only provided as solr can start its cloud with internal zookeeper.

```
@Bean
    @ConditionalOnMissingBean
    public SolrServer solrServer() throws MalformedURLException {
        this.solrServer = createSolrServer();
        return this.solrServer;
    }

    private SolrServer createSolrServer() throws MalformedURLException {
        if (StringUtils.hasText(this.properties.getZkHost())) {
            return new CloudSolrServer(this.properties.getZkHost());
        } else if (this.properties.getHost().contains(",")) {
            return new      LBHttpSolrServer(StringUtils.commaDelimitedListToStringArray(this.properties.getHost()));
        }
        return new HttpSolrServer(this.properties.getHost());
    } 
```

In dev env we dont install zookeeper, and internal zookeepers are used with solr cloud. Bootstarp solr manages everything.

**Comment by snicoll** [comment]
I didn't get that. Is the `else if` your proposal? Rather than pasting code here, would you mind providing a PR or at least a test that demonstrates what you'd like in practice?

**Comment by philwebb** [comment]
Closing due to lack of requested feedback
