### ISSUE TITLE
what fix part 02 bug?

### ISSUE THREAD

**Issue by andotorg** [spring-projects/spring-boot#30473]
0day bug  part 02

**Comment by andotorg** [comment]
change tomcat server to undertow server ?

**Comment by mbhave** [comment]
@andotorg If you think you've found a bug, please provide a complete description along with a minimal sample that we can run to reproduce it.

**Comment by wilkinsona** [comment]
And if you believe it is a security vulnerability, please disclose it responsibly by following the process described in https://spring.io/security-policy.

**Comment by andotorg** [comment]
thanks you
