### ISSUE TITLE
maven/gradle plugins generated jar should use build classpath order at runtime in PropertiesLauncher

### ISSUE THREAD

**Issue by jendap** [spring-projects/spring-boot#3048]
I got bitten today by having two different versions of the same class in two jar files. Unfortunate but it happens. Maven tests run great as maven have rules to order classpath. Spring boot plugin does not.

It would be great to keep the classpath order from maven/gradle - the one people use for their testing - would make it to the launcher. Hence save maven/gradle classpath during build and add it to the resulting jar file after "repackage".

It should be pretty simple to do. I can create a pull request for it. RepackageMojo class has access to it as simple as "this.project.getRuntimeClasspathElements()". We can add a parameter "addClasspath" to enable it, store it in the jar and use it (if present) by the loader.

I believe this is actually so useful and safe that it should, imho, be enabled by default. What do you think?

BTW: It should be possible to do it with 1.3.0M1 using the startup script containing ${maven.runtime.classpath} and using maven's variable interpolation.

**Comment by snicoll** [comment]
We're going to disable the startup script by default (#3045). PR more than welcome.

**Comment by jendap** [comment]
Found it. The problem is that we are using PropertyLauncher and there is a regression between 1.1.9 and 1.2.3 releases. It reverts the classpath! The jar files inside lib/ directory inside the big final jar are in the reverse order than they are with JarLauncher or previous releases.

I have tested it. The classpath for classloader creation in ExecutableArchiveLauncher.createClassLoader is reverted on 1.2.3 for PropertyLauncher but correct for JarLauncher on the same version. PropertyLauncher is fine on 1.1.9.

It seems it may be broken by issue #2314 - commit #4e907f1.

@dsyer why is there [Collections.reverse](https://github.com/spring-projects/spring-boot/commit/4e907f19ce98eb41eb4d748dcb2f1ff7d12f9552#diff-894f9ba7120962c82dcc9523d5df19ccR453) please? Is it a bug or feature?

BTW: Is it a supported feature to have correct classpath or is it just a luck? Currently maven gives dependencies in order. Spring boot plugin happens to write the jar files into one big in that order and hence reasonable implementation of JarFile iterate over entries in the order as bytes are on the disk. So it happens to work until it get broken... I would expect to see something like Classapath entry in manifest with listed order of lib/foo, lib/bar, etc. the order which to use. But it does not seem so.

**Comment by dsyer** [comment]
I remember that being nightmare. I don't remember the precise reason for reversing the collection, but there's a comment to suggest it was done on purpose so simply removing that line will probably break something else.

**Comment by jendap** [comment]
@dsyer I know these problems may take a while to resolve.

However this is a bug for sure. We should fix it. You will get two different class path orders from the very same jar depending on whether you start using PropertyLauncher and JarLauncher.

There are tests it should not be that hard to replicate in the integration test. I will take a look at it later this week.

**Comment by dsyer** [comment]
Feed

**Comment by jendap** [comment]
Yes! That looks good. Thank you @dsyer
