### ISSUE TITLE
Revisit AeatherGrapeEngineTests

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3051]
In the fix for #2947 (https://github.com/spring-projects/spring-boot/commit/b838513fda778a9bbbcd704a7a77aac9ed2ceb6c) I had to update those tests to include our milestone repo so that Spring Framework 4.2.RC1 is resolved.

Looking at how Maven works, I wonder how it worked before (since it needs a repository source for *everything*, even if the dependency is cached in the local repository). To me, the current behaviour is more consistent. 

ping @wilkinsona

**Comment by wilkinsona** [comment]
It works with BUILD-SNAPHOT dependencies as, while they're considered unavailable when Central is the only available repository, they're also considered not to be tracked so [the availability is overridden to `true`](https://github.com/eclipse/aether-core/blob/aether-1.0.2.v20150114/aether-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManager.java#L113-L120).
