### ISSUE TITLE
Integrate AOT generation in Spring Boot Maven Plugin

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#30525]
Spring Framework has recently introduced a way to inspect the state of an application at build-time, and generate code that provides an optimized version of it.

This issue is about integrating the AOT generation part in the Maven Plugin so that those optimizations can be added to the repackaged archive and/or used by `native-image` to build a native image for the application.

**Comment by wilkinsona** [comment]
Compilation of the generated source is failing on Windows: https://ge.spring.io/s/zbgpz6gbtoice/tests/:spring-boot-project:spring-boot-tools:spring-boot-maven-plugin:intTest/org.springframework.boot.maven.AotGenerateTests/whenAotRunsSourcesAreGenerated(MavenBuild)%5B1%5D?anchor=eyIwIjoiMC0xNDU0In0&expanded-stacktrace=WyIwIl0.

**Comment by wilkinsona** [comment]
After [08768bd](https://github.com/spring-projects/spring-boot/commit/08768b58210b2839f7f6978351cd2873329eb453), this is still failing.
