### ISSUE TITLE
Current hibernate version breaks jpa and should probably be downgraded until fixed

### ISSUE THREAD

**Issue by boskokg** [spring-projects/spring-boot#30521]
We found an issue with the the latest release of the Spring Boot (2.6.5) related to hibernate bug not fixed yet. You should probably downgrade the hibernate version dependecy until fixed.
More about the hibernate bug can be found [here HHH-15142](https://hibernate.atlassian.net/browse/HHH-15142)

**Comment by wilkinsona** [comment]
Duplicates #30421.
