### ISSUE TITLE
Spring-boot latest released version 2.6.6 doesn't upgrade liquibase-core's version

### ISSUE THREAD

**Issue by AliceAmos** [spring-projects/spring-boot#30540]
Hey :)

As the latest versions of spring-boot released lately (until 2.6.6), the version of the dependency 'liquibase-core' still stays lower than 4.8.0 at least, while lots of other transitive dependencies are being promoted... is there any explanation to this decision? 
We are probably going to be required to use this version of liquibase-core, or higher, and would prefer upgrading our spring-boot version rather than override it and potentially cause problems.

Thank you!
Alice

**Comment by wilkinsona** [comment]
Please see https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies for details of our dependency upgrade policy. We will pick up the latest 4.x release of Liquibase in Spring Boot 2.7 which will be released next month. At the time of writing, 2.7's using 4.9.

Looking at the commits in 2.7.x where we've upgraded Liquibase, the new minors appear to be drop-in replacements for 4.5.0 which is what Spring Boot 2.6 is currently using. Judging by that, you should be able to use the `liquibase.version` property to override the version without any problems.
