### ISSUE TITLE
Incorrect Neo4j username property replacement hint by spring-boot-properties-migrator

### ISSUE THREAD

**Issue by s9m33r** [spring-projects/spring-boot#30550]
The spring-boot-properties-migrator seems to be suggesting incorrect replacement(`spring.neo4j.authentication.password`) recommendation for `spring.data.neo4j.username` key. I've also confirmed the same from the `spring-configuration-metadata.json` from `spring-boot-autoconfigure-2.6.3.jar`:
```json
{
    "name": "spring.data.neo4j.username",
    "type": "java.lang.String",
    "description": "Login user of the server.",
    "deprecated": true,
    "deprecation": {
        "level": "warning",
        "replacement": "spring.neo4j.authentication.password"
    }
}
```
 [The documentation](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#migrating.migrating) seems to be indicating that `spring.data.neo4j.username` needs to be replaced with `spring.neo4j.authentication.username`.

**Comment by mhalbritter** [comment]
Good catch, thanks for the report!

**Comment by s9m33r** [comment]
Great! Thanks for the quick one!

**Comment by mhalbritter** [comment]
I wish every bug fix would be that easy to solve :)
