### ISSUE TITLE
BatchDataSourceScriptDatabaseInitializer does not find the Oracle schema scripts

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30564]
The script's been [renamed](https://github.com/spring-projects/spring-batch/issues/1057) in 5.0.0-M2 so we won't find it any more. Ideally, a test would have caught this when we upgraded to 5.0.0-M2. We should look at adding one as part of fixing this.

**Comment by pruidong** [comment]
You mean you need to modify: [BatchDataSourceScriptDatabaseInitializer.java#L81](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchDataSourceScriptDatabaseInitializer.java#L81)

```java

platformResolver = platformResolver.withDriverPlatform(DatabaseDriver.ORACLE, "oracle10g");

```

This line? Can I submit a pull request?

**Comment by snicoll** [comment]
@pruidong thanks for the offer but Andy mentioned a test should have failed and hasn't so it is more than just changing the line.

**Comment by pruidong** [comment]
> @pruidong thanks for the offer but Andy mentioned a test should have failed and hasn't so it is more than just changing the line.

Okay thank you.
