### ISSUE TITLE
SpringApplication.deduceMainApplicationClass() does not work correctly when deployed as WAR

### ISSUE THREAD

**Issue by philippn** [spring-projects/spring-boot#3061]
Hi there,

I'm deploying a Spring boot application as WAR file (using SpringBootServletInitializer) in JBoss and noticed that my custom banner is missing the {application.version} variable. It works nicely when started standalone though.

Some debugging pointed me to deduceMainApplicationClass() where the Stacktrace is inspected for a main class, which doesn't work in conjunction with SpringBootServletInitializer.

**Comment by wilkinsona** [comment]
You can work around the problem by setting the main class in the `configure` method of your `SpringBootServletInitializer` subclass:

```java
@Override
protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
	application.main(getClass());
	// …
	return application;
}
```

**Comment by philippn** [comment]
I think to remember that I tried that but it didn't work back then, because the main class set this way gets overidden by the return value of deduceMainApplicationClass() (which is null).

Thanks alot for looking into it!

**Comment by philippn** [comment]
Unfortunately this problem still exists with version 1.2.5.
The problem seems to be that in SpringApplication, line 232 the mainApplicationClass is overridden no matter what.

The override should be guarded with a not null check

**Comment by wilkinsona** [comment]
I think you're mistaken. `initialize` is only called from the constructor of `SpringApplication` so the subsequent call to set `mainApplicationClass` will override the deduced class. The test that I added in cd62596 would fail if this was not the case.

The problem appears to be that Tomcat is calling `definePackage` and is supplying `null` for `implVersion`. It only does this when it can't find the manifest and I don't, yet, understand why it can't find it. Regardless, it's a separate issue to deducing/setting the main class correctly.

**Comment by wilkinsona** [comment]
I've opened #3406 to see if we can do anything about Tomcat's behaviour.

**Comment by philippn** [comment]
I stand corrected. Thanks alot for your efforts!
