### ISSUE TITLE
SqlResultSetMapping is unknown

### ISSUE THREAD

**Issue by andrewhamili** [spring-projects/spring-boot#30622]
Experiencing this error when using version 2.6.6

org.springframework.dao.InvalidDataAccessApiUsageException: The given SqlResultSetMapping name [Unknown SqlResultSetMapping [[UserSummary]] is unknown

Here is the link to my sample Github repo. I also included two TRACE log files here (app-2.4.3.log and app-2-6-6.log). You can see the difference where the SqlResultSetMapping failed.

https://github.com/andrewhamili/mysql-procedure-demo

**Comment by andrewhamili** [comment]
As a workaroud, I will be using version 2.4.3 for now.

**Comment by snicoll** [comment]
@andrewhamili the exception comes from Hibernate so I don't really understand why you're reporting a problem here. An upgrade to Spring Boot 2.6 from Spring Boot 2.4 means you're very much likely to upgrade Hibernate as well.

Spring Boot 2.4.3 uses [Hibernate 5.4.28](https://docs.spring.io/spring-boot/docs/2.4.3/reference/html/appendix-dependency-versions.html#dependency-versions) while Spring Boot 2.6.3 uses [Hibernate 5.6.7](https://docs.spring.io/spring-boot/docs/2.6.6/reference/html/dependency-versions.html#appendix.dependency-versions). Please review the changes in this version and report an issue to the Hibernate issue tracker if necessary.
