### ISSUE TITLE
Upgrade to Spring Data 2022.0-M4

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#30634]

**Comment by bclozel** [comment]
SNAPSHOT upgrade is blocked by a new `javax.inject` dependency, see https://github.com/spring-projects/spring-boot/issues/30610#issuecomment-1094067925

**Comment by christophstrobl** [comment]
Project Dependencies Spring Data 2022.0.0-M4

* Cassandra Driver (com.datastax.oss:java-driver-bom): 4.14.1
* Couchbase Client (com.couchbase.client:java-client): 3.3.0
* Jedis (redis.clients:jedis): 3.8.0
* Lettuce (io.lettuce:lettuce-core): 6.1.8.RELEASE
* MongoDB (org.mongodb:mongodb-driver-core): 4.6.0
* Neo4j Driver (org.neo4j.driver:neo4j-java-driver): 4.4.5
* Spring LDAP (org.springframework.ldap:spring-ldap-core): 3.0.0-M2
