### ISSUE TITLE
Upgrading to Spring Boot 2.5 and running into Spring Data Solr deprecation. What are the alternatives?

### ISSUE THREAD

**Issue by saramorsi** [spring-projects/spring-boot#30640]
We are using Spring Data Solr and are on Spring Boot 2.4.8 right now. Once we upgrade to Spring Boot 2.5.12 (to patch a major Spring Core vulnerability), we are running into this issue where the [auto configuration is removed] in Spring 2.5+ (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#spring-data-solr) which means we will have to handle some methods, annotations and properties on our own. E.g. annotations and classes like @SolrDocument, @query, FacetPage, SolrCrudRepository, etc.. we can’t use anymore.

I’m finding little resources online on advice around migrating over and what to use in place of these annotations, classes and code. Any advice on what equivalents we should be using instead in Spring or should we just rewrite our code to use SolrJ? What does the Spring team expect the projects already using Spring Data Solr to do in this case? The current documentation is not clear on proposed solutions and/or does not offer help for migrations. An example would be helpful as well. 

Thank you.

**Comment by snicoll** [comment]
@saramorsi Spring Data has removed Solr support and we [just followed suit](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#spring-data-solr). In an attempt to help you, I've noticed that you've raised [the same question](https://github.com/spring-projects/spring-data-solr/issues/806). Please do not cross-post, in particular without indicating you've done so as it is likely to lead to wasted efforts.

**Comment by saramorsi** [comment]
@snicoll The Spring Data Solr project is dead and no one is responding since last year. I would like to understand what the alternatives is the Spring team recommending right now because it doesn't seem like it's any. Thanks!

**Comment by snicoll** [comment]
I've subscribed to the issue you've created in the Spring Data Solr project and asked the Spring Data team to provide additional information. There's nothing we can do here about it.

**Comment by saramorsi** [comment]
Ok thank you for letting me know.
