### ISSUE TITLE
Change identityprovider to assertingparty in Saml2RelyingPartyProperties

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-boot#30642]
Since [this commit](https://github.com/spring-projects/spring-security/commit/8e8a642e5a8a25138361fc5d0127c27b453da35d) in Spring Security, some properties in the `RelyingPartyRegistration` were deprecated in favor of others aligned SAML 2.0 Spec Language.

Consider changing `identityprovider` in favor of `assertingparty` in `Saml2RelyingPartyProperties` to better align with the naming in Spring Security.

Related:
 - https://github.com/spring-projects/spring-security/issues/8777

**Comment by mhalbritter** [comment]
I've added a note to the release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7.0-RC1-Release-Notes#deprecations-in-spring-boot-27
