### ISSUE TITLE
Remove support for Elasticsearch's RestHighLevelClient

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30647]
#28597 is a prerequisite for this. Without it we would be unable to auto-configure an `ElasticsearchOperations` bean.

**Comment by misselvexu** [comment]
Does removing `RestHighLevelClient` also need to remove support for `ElasticsearchRestTemplate` ?

**Comment by wilkinsona** [comment]
Yes. Spring Boot would stop auto-configuring `ElasticseearchRestTemplate` and define an [`ElasticsearchTemplate`](https://github.com/spring-projects/spring-data-elasticsearch/blob/0950dd6c7a1fc2f3f94516e8720e83e1fb577deb/src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchTemplate.java#L69) bean instead.
