### ISSUE TITLE
[Question] could event system ensure events are publish synchronously

### ISSUE THREAD

**Issue by dugenkui03** [spring-projects/spring-boot#30653]
From #30489
> It's not expected that users inject the bean and call `onApplicationEvent` directly. If you want to change the application availability status, [you should emit an AvailabilityChangeEvent](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.spring-application.application-availability.managing). The spring event system will then ensure that these listeners are called. And they are not called concurrently.

@mhalbritter I trace the code from  [AvailabilityChangeEvent](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.spring-application.application-availability.managing), and find there is  nothing to ensure that listeners are not called concurrently —— I can't find any lock or things like `BlockingQueue`.
```java
// 1. multiple thread invoke this static method concurrently and publish different state.
 AvailabilityChangeEvent.publish(this.eventPublisher, ex, LivenessState.BROKEN);

// 2.  call multicastEvent in ‘AbstractApplicationContext#publishEvent(Object, ResolvableType)‘
//      still don't have any lock, 
getApplicationEventMulticaster().multicastEvent(applicationEvent, eventType)

// 3. multiple thread could invoke 'SimpleApplicationEventMulticaster#multicastEvent' at same time and publish different event concurrently.
protected void invokeListener(ApplicationListener<?> listener, ApplicationEvent event) {
                 ...
		doInvokeListener(listener, event);
}

private void doInvokeListener(ApplicationListener listener, ApplicationEvent event) {
	try {
		listener.onApplicationEvent(event);
	}
        ...
}
```

**Comment by scottfrederick** [comment]
@dugenkui03 Please do not open a new issue to ask a question that you've already asked in the linked issue.
