### ISSUE TITLE
Add documentation for micrometer-tracing

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#30658]
The auto-configurations have been in `main` since https://github.com/spring-projects/spring-boot/commit/3860eb211af1b429f325c05408ba2ebc82ae6698. We should add some documentation describing what it does and what to do to get tracing running with Zipkin and Wavefront. [This comment](https://github.com/spring-projects/spring-boot/pull/30251#issuecomment-1092701788) contains the dependency combinations.

There's some [documentation from the Micrometer team](https://micrometer.io/docs/tracing), too.

**Comment by wilkinsona** [comment]
We should add something to [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M3-Release-Notes) too.

**Comment by mhalbritter** [comment]
Added a [section to the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M3-Release-Notes#auto-configuration-for-micrometer-tracing).

**Comment by mhalbritter** [comment]
I'm working on that one here: https://github.com/mhalbritter/spring-boot/tree/mh/30658-add-documentation-for-micrometer-tracing
