### ISSUE TITLE
too long file path

### ISSUE THREAD

**Issue by zhengkejun** [spring-projects/spring-boot#30662]
in this path so many longlonglong file names!!!!!, like this

https://github.com/spring-projects/spring-boot/blob/v2.1.18.RELEASE/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFailsToResolve.gradle

**Comment by zhengkejun** [comment]
can't pull in windows system

**Comment by snicoll** [comment]
Please review the contributing page that links to our [Wiki](https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code#cloning-the-git-repository-on-windows)
