### ISSUE TITLE
Add WebClient based sender for Zipkin

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#30661]
We already have a `RestTemplate` based sender for Zipkin, we should add a `WebClient` based one, too. We can [take the code from sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/blob/22be601b89126bc2a4c212675522a3d021f4b32f/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/WebClientSender.java#L33).

**Comment by StefanBratanov** [comment]
Hi, I am keen to try this issue as a first commit. 🙂 Is it possible to assign?

**Comment by mhalbritter** [comment]
Hey, we have [issues labeled as "first-timers only"](https://github.com/spring-projects/spring-boot/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+first-timers-only%22) for exactly this purpose. The list is currently empty, but keep an eye out for issues with this label.

**Comment by StefanBratanov** [comment]
Hi, thank you. I will keep an eye out. In the meantime, I was interested and did changes on a branch in my fork yesterday. I understand it could be throw away work, but it was fun looking at the code. Let me know if it looks good and it can be used.

https://github.com/StefanBratanov/spring-boot/commits/web-client-sender-zipkin

**Comment by StefanBratanov** [comment]
Great, just created a PR :) https://github.com/spring-projects/spring-boot/pull/30792

**Comment by mhalbritter** [comment]
Thanks, i will close this issue then.
