### ISSUE TITLE
Tracing solution appears to be eliminated for Spring Boot 2.7.x

### ISSUE THREAD

**Issue by dmlogs** [spring-projects/spring-boot#30698]
Spring Cloud Sleuth is supported `<2.7.0-M1` and Micrometer Tracing has been recently added to Spring 3.x but does not appear to be incorporated for 2.7.x which leaves a gap in support for a spring integrated tracing solution in this release.

**Comment by snicoll** [comment]
@dmlogs I can only assume you refer to the range on start.spring.io. That's a bug, see https://github.com/spring-io/start.spring.io/issues/896.
