### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication

### ISSUE THREAD

**Issue by akashbonde** [spring-projects/spring-boot#30694]
![image](https://user-images.githubusercontent.com/46789278/163576077-fbee6e61-3819-4a3f-8912-baba4e3779e5.png)

I am getting this error while building my spring boot application in Heroku, but when I run it locally in my eclipse, then it works fine.

**Comment by bclozel** [comment]
I think the java command is not using the repackaged executable jar as it should. See [our reference docs](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#deployment.cloud.heroku) and [heroku's docs](https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku) for more on this. If you need more help, please ask on StackOverflow.
