### ISSUE TITLE
Provide easy way to pass system properties to Jetty container

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3073]
I'm looking for a way to provide system properties to Jetty container. Before, I've used `jetty-maven-plugin` and I did it like that:

```xml
<systemProperties>
		<systemProperty>
			<!-- http://www.slf4j.org/codes.html#loggerNameMismatch -->
			<name>slf4j.detectLoggerNameMismatch</name>
			<value>true</value>
	</systemProperty>
</systemProperties>
```

Suggestion: probably it's better to improve `spring-boot-maven-plugin` to allow user to pass system variables to container?

**Comment by php-coder** [comment]
Hm.. may be it's invalid because in Spring Boot you should to like this:

```java
	public static void main(String[] args) {
		System.setProperty("slf4j.detectLoggerNameMismatch", "true");
```

**Comment by snicoll** [comment]
There is an example of passing system properties in [the documentation](http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-debug.html)
