### ISSUE TITLE
Update docs to reflect AdoptOpenJDK is moving to the Eclipse Foundation

### ISSUE THREAD

**Issue by rfigueroa** [spring-projects/spring-boot#30747]
Since July 24th 2021 AdoptOpenJDK moved to the Eclipse Foundation, documentation should reflect that in the samples.
https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/

**Comment by snicoll** [comment]
@rfigueroa thanks for the report. FTR if you intend to submit a PR, there is no need to create an issue as one supersedes the other.
