### ISSUE TITLE
spring-boot-maven-plugin suggestions

### ISSUE THREAD

**Issue by ddzxlining** [spring-projects/spring-boot#30764]
155/5000 
Dear Sir,
     I am a software developer from Xi'an,China! When using 'spring-boot-maven-plugin', I found that  PropertiesMergingResourceTransformer did not consider to deal with relocations,  if I  relocated  one package whose resource file contains the package name, an error will be reported if the same process is not performed. For example, spring.factories 

Looking forward to your reply
                                                                                                                                        Lining ddzxlining@163.com

**Comment by snicoll** [comment]
@ddzxlining `PropertiesMergingResourceTransformer` applies to `META-INF/spring.factories` only in our parent and if you'd like to reuse part of the logic for other use cases, I'd recommend rolling your own class. If I misunderstood and you're reporting a bug, please attach a small sample we can run ourselves that reproduces it and we can investigate.

**Comment by ddzxlining** [comment]
Thank you very much！
