### ISSUE TITLE
spring.security.saml2.relyingparty.registration.*.asserting-party.* properties contain unwanted hyphen in asserting-party

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30785]
We try to avoid hyphens in property prefixes, reserving their use for the property's name. To align with this, `spring.security.saml2.relyingparty.registration.*.asserting-party.*` should be `spring.security.saml2.relyingparty.registration.*.assertingparty.*`.

**Comment by mhalbritter** [comment]
When the 2.7.0 changelog is written, please change the note from `RC-1`, which still uses `asserting-party` to `assertingparty`.
