### ISSUE TITLE
Auto-configure Micrometer's JVM info metrics

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30797]
Unfortunately, we missed its addition in Micrometer 1.7. While it's easy to configure it manually, we should auto-configure it.

**Comment by eddumelendez** [comment]
Hi @wilkinsona 
I've submitted a PR to `2.7.x` because `JvmInfoMetrics` was added in Micrometer `1.7.0` and branch `2.7.x` it is already in `1.9.0-RC1`.

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. I'll close this in favor of #30823.

> I've submitted a PR to 2.7.x

Given the ease with which this can be manually configured, I don't think we can justify making a change post RC1.
