### ISSUE TITLE
FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.

### ISSUE THREAD

**Issue by sehmusaydogdu** [spring-projects/spring-boot#30796]
Spring boot parent version = 2.6.3

I wrote the following in the config server file, but it didn't work.

spring.servlet.multipart.max-file-size=**10MB**
spring.servlet.multipart.max-request-size=**10MB**

I defined custom beans but again it didn't work.

```java
@Bean
public MultipartConfigElement multipartConfigElement() {
    MultipartConfigFactory factory = new MultipartConfigFactory();
    factory.setMaxFileSize("124MB");
    factory.setMaxRequestSize("124MB");
    return factory.createMultipartConfig();
}
```

I tried with version 2.2.2, it works, but I tried with version 2.6.3, it didn't work. Could something have changed in the new version?
I am trying to run the application in Cloud Foundry environment. But I am getting error. I don't get any error in local environment.

Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.

**Comment by pruidong** [comment]
In the [documentation](https://docs.spring.io/spring-boot/docs/2.6.3/reference/htmlsingle/#application-properties.web.spring.servlet.multipart.max-file-size), Your configuration is valid.

You can try to make the configuration size bigger:

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

Spring Boot will automatically configure the relevant beans.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Vishnus0** [comment]
@sehmusaydogdu @spring-projects-issues  was a solution for this found?
