### ISSUE TITLE
jvm metrics lost (2.5.+)

### ISSUE THREAD

**Issue by Darkvater** [spring-projects/spring-boot#30802]
# Description
Upgrading from spring-boot 2.3.4 to 2.5(.4) removed all the jvm, and other metrics from /actuator/metrics only leaving hikari/tomcat.

This is a similar issue to #26630 blaming `spring-boot-starter-data-jpa`.

This could be the case, however if `spring-boot-starter-security` is additionally added to the project with adding `@EnableWebSecurity` (and an empty WebSecurityConfigurer) the jvm metrics are back.

Behaviour is the same also in the latest 2.5.13 version.

 ## Question/Bug:
How do I get the jvm- metrics working with spring-boot-starter-data-jpa (if it is still a contributing factor) and without spring-boot-starter-security?

**Comment by Darkvater** [comment]
Give me a bit of time. Created a skeleton project, and of course it is working in all scenarios (2.5.4 with spring-data-jpa, with spring-data-jpa, spring-security, and without either) so this is annoying. Now I have to start trimming down the real-life project to find out where the issue actually lies... back in a day or two

**Comment by Darkvater** [comment]
I am sad/happy to report that the fact the metrics are gone is due to some oracle-aq queue functionality we are using. It's something crap built internally and it's impossible to puzzle out exactly which insane configuration there causes this issue.
Good for spring-boot, it is working otherwise :)

**Comment by wilkinsona** [comment]
Thanks for letting us know.
