### ISSUE TITLE
Improve development time experience

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3082]
Several properties and features could be enabled during development time that would help when working on Spring Boot applications:

* Automatically set sensible development time properties (such as Thymeleaf cache) [#3083]
* Watch for local class/resource file changes and restart the application [#3084]
* Provide a livereload.com server implementation and automatically trigger browser updates [#3085]
* Provide update and remote restart support for cloud deployments [#3086]
* Provide HTTP tunneling for remote debugging of cloud deployments [#3087]

**Comment by snicoll** [comment]
\o/

**Comment by bclozel** [comment]
:+1:

**Comment by cemo** [comment]
:+1:

**Comment by pasali** [comment]
:+1:

**Comment by joshlong** [comment]
:+1:
