### ISSUE TITLE
Integration test AOT source generation using the Gradle plugin

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30838]
We'll need to have `org.springframework.boot:spring-boot` available as a dependency to the application under test. This'll require some reworking of how we integration test the plugin.

**Comment by philwebb** [comment]
We could probably take this on in 3.1 and rely on the smoke tests for now.

**Comment by wilkinsona** [comment]
The smoke tests certainly remove a lot of the risk. We could also tackle it at some point in 3.0.x after 3.0.0.

**Comment by wilkinsona** [comment]
I don't think this is worth the effort. We haven't had many, if any, bugs in this area and we have good coverage courtesy of the AOT/native smoke tests.
