### ISSUE TITLE
How to map @ConfigurationProperties to java util Properties. 

### ISSUE THREAD

**Issue by saagar2000** [spring-projects/spring-boot#30840]
We have a application which accepts java util properties as input. Right now we are manually mapping each field from Configuration Properties to Properties. Is there a automatic way to map all the fields from `@ConfigurationProperties` annotated class to Properties ? Thank you.

**Comment by philwebb** [comment]
We don't offer any facility to map `@ConfigurationProperties` to `java.util.Properties`. You might be able to write something yourself wrapping the configuration properties instance in a `org.springframework.beans.BeanWrapperImpl` then using `getPropertyDescriptors()` to build the `Properties`.
