### ISSUE TITLE
Watch for local class/resource file changes and restart the application

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3084]
Watching for local filechanges and restarting the application would be quite helpful for many developers. Something simpler than Spring Loaded or JRebel but still useful for small applications.

_(part of the #3082 theme)_

**Comment by chrylis** [comment]
Am I right that this can be disabled with `spring.developertools.restart.enabled: false`?  I saw the config properties but not a doc update.

**Comment by snicoll** [comment]
The doc has not been written yet. It should happen quite soon. We're also in the process of renaming the whole thing to `spring.devtools.*`

For now, that key disables automatic restart, yes.
