### ISSUE TITLE
Document development time improvements

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3088]
Document the new features introduced in #3082

**Comment by philwebb** [comment]
Include details of remote debug timeout

**Comment by metyl** [comment]
There is an error in documentation, the name of a property which enables [remote support](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-devtools-remote) is `spring.devtools.remote.secret` not `spring.devtools.remote.password`

**Comment by snicoll** [comment]
Thanks for the report. I've fixed that in #3232
