### ISSUE TITLE
`build-image` fails with "The builder requested cannot be found" despite existing

### ISSUE THREAD

**Issue by Haarolean** [spring-projects/spring-boot#30894]
Hi, I'm trying to build an image via `build-image` goal, like this:
`./mvnw -Dmaven.test.skip=true spring-boot:build-image -Dspring-boot.build-image.imageName=provectuslabs/kafka-ui --builder paketobuildpacks/builder:0.0.464-base`

and I get this:
`[ERROR] The builder requested using id = paketobuildpacks/builder:0.0.464-base cannot be found -> [Help 1]`

This image does [exist](https://hub.docker.com/layers/builder/paketobuildpacks/builder/0.0.464-base/images/sha256-bae0a6b7ec5d51867eb49ac598775bb5fa8788bba458d2edfda314611be554a8?context=explore). I have even pulled it manually. I have no understanding why is it unavailable.

I have spring-boot v. 2.6.3 with jdk13. I'm ready to provide a project to reproduce the issue if needed. 

Thanks.

**Comment by wilkinsona** [comment]
> I'm ready to provide a project to reproduce the issue if needed.

Yes, please.

> I have spring-boot v. 2.6.3 with jdk13

Before doing so, please upgrade to 2.6.7 and note that JDK 13 is not supported. You should use 8, 11, 17, or 18.

**Comment by Haarolean** [comment]
@wilkinsona hey, thank you for your reply.

I tried upgrading spring-boot version to 2.6.7 and jdk to 17, it's all the same.

This is [the project](https://github.com/provectus/kafka-ui/tree/test/spring-native), branch is `test/spring-native`.
This is the command I executed within `kafka-ui-api` directory:
`./mvnw -Dmaven.test.skip=true spring-boot:build-image -Dspring-boot.build-image.imageName=provectuslabs/kafka-ui --builder paketobuildpacks/builder:0.0.464-base`

**Comment by wilkinsona** [comment]
`--builder` is a Maven command line argument. To specify a custom image builder, you should use ` -Dspring-boot.build-image.builder`, as [described in the Maven plugin's documentation](https://docs.spring.io/spring-boot/docs/2.6.7/maven-plugin/reference/htmlsingle/#build-image.examples.custom-image-builder).

**Comment by Haarolean** [comment]
@wilkinsona Sorry, must've copy-pasted as-is, I was wondering why there's nothing about spring in logs. Thank you 😅
