### ISSUE TITLE
Try to add an integration tests for the developer-tools sample

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3089]
The way that the Restarter works makes it difficult to test

**Comment by snicoll** [comment]
@philwebb is that one still relevant?

**Comment by wilkinsona** [comment]
We have integration tests now for Devtools. See https://github.com/spring-projects/spring-boot/tree/a427982d775797dbffdc7612aa509be23d5f81dc/spring-boot-integration-tests/spring-boot-devtools-tests
