### ISSUE TITLE
Upgrade to Netty 4.1.77.FINAL

### ISSUE THREAD

**Issue by Flash1232** [spring-projects/spring-boot#30892]
I understand there is a semi-automatic process to update managed dependencies.
In spite of that, we are experiencing inability to use Spring Boot (v2.7.0-RC1) with WebFlux as a whole because of https://github.com/netty/netty/issues/12343 which was just mitigated in https://github.com/netty/netty/releases/tag/netty-4.1.77.Final yesterday. If possible, it would be immensely appreciated to have that updated asap.
I am unsure if a simple version increment would be acceptable as a PR as outlined in your guidelines.

**Comment by bclozel** [comment]
As stated in the issue template, there is no need to create such issues as we run our dependency upgrades process before the release. This will be taken care of in due time.

Unless the upgrade requires more changes, typically, merging such PRs takes more time or they can be outdated pretty quickly in case of newer releases.
