### ISSUE TITLE
startupTimeMetrics seems to cause bean dependency cycle when a MeterBinder uses a spring data repository

### ISSUE THREAD

**Issue by JakobFels** [spring-projects/spring-boot#30902]
Spring Boot version: 2.6.7

We seem to be running into an issue similar to https://github.com/spring-projects/spring-boot/issues/27591.
We recently migrated one of our metric sources to use a spring data repository. This seems to cause a bean dependency cycle caused by `startupTimeMetrics` (See attached bean cycle screenshot).
![image](https://user-images.githubusercontent.com/4647840/167363670-ebdc4221-e1ef-4ad7-9dc8-6220a9b02929.png)

If needed, I can attempt to provide a minimal reproducer, but I hope the current information is enough.

**Comment by wilkinsona** [comment]
> If needed, I can attempt to provide a minimal reproducer, but I hope the current information is enough.

Yes, please. I have been unable to reproduce the problem from what you have described thus far.

**Comment by JakobFels** [comment]
While building the reproducer I noticed that the problem is caused by including `spring-cloud-gcp-starter-data-firestore`, with plain data-jpa I could not reproduce it as well.

I'll open an issue on that project.

**Comment by wilkinsona** [comment]
Thanks for letting me know. FWIW the dependency between `serviceInstanceRepository` and `startupTimeMetrics` looks a little unusual. If `serviceInstanceRepository` is a Data Firestore repository, that link is where I'd start looking.

**Comment by JakobFels** [comment]
I opened a corresponding issue in the spring cloud gcp project:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1113

**Comment by elefeint** [comment]
For completeness; here is a reproducer without Firestore: https://github.com/elefeint/FirestoreMetricsReproducer/tree/h2-reproducer

**Comment by wilkinsona** [comment]
The problem does not occur with Spring Boot 3.x.
