### ISSUE TITLE
Problematic configuration in example for "expand info properties at build time"

### ISSUE THREAD

**Issue by Laures** [spring-projects/spring-boot#3092]
the segment about expanding info properties at build time with maven includes a config for the `maven-resources-plugin`. This config is problematic. the delimiter tag only adds delimiters to the plugin but does not replace the default delimiter.

because of that if you have any default spring-placeholder (`${}`) that is used in a resource file set in the environment during build time, this placeholder will be filtered by the plugin.

this can be avoided by setting `<useDefaultDelimiters>false</useDefaultDelimiters>` in the configuration block inside the pom.xml

**Comment by Laures** [comment]
i just checked the `spring-boot-starter-parent` and it is also missing this setting.

**Comment by snicoll** [comment]
That's what I was about to check as well. Thanks for doing that.

I am still a bit confused. Are you referring to [this section in the doc?](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-application-info)

That one uses `@` as the delimiter so `${}` should be excluded.

**Comment by Laures** [comment]
yes. if you just use the plugin config from the doc you will use `@` and `${}` because configuring a delimiter just adds it. to remove the default delimiters you need to set useDefaultDelimiters.

If you dont the mojo adds the delimiters configured for the resources-execution [1] and these are by default `@` and `${}`. that can cause property-placeholder in resource-files to be unintentionally replaced during the maven build.

[1] resources mojo: https://svn.apache.org/viewvc/maven/plugins/tags/maven-resources-plugin-2.6/src/main/java/org/apache/maven/plugin/resources/ResourcesMojo.java?view=markup
[2] default delimiters: https://maven.apache.org/shared/maven-filtering/xref/org/apache/maven/shared/filtering/AbstractMavenFilteringRequest.html
