### ISSUE TITLE
Shutdown hook not firing in forked jvm launched by spring-boot:run on Windows

### ISSUE THREAD

**Issue by gseifert** [spring-projects/spring-boot#3093]
If I run my simple spring boot application using "mvn spring-boot:run" the application context is closed properly when I hit ctrl-c.  But if I add the spring loaded agent or specify jvmArguments this forks a new jvm and then when I hit ctrl-c the shutdown hook is not fired and so the spring application context is not closed gracefully.  I am using 32-bit Windows 7 and java 1.7.0_75.

**Comment by wilkinsona** [comment]
It works fine for me on OS X so I suspect this is Windows-specific

**Comment by wilkinsona** [comment]
I think this has been addressed by the changes made for #5815
