### ISSUE TITLE
Document ordering of Lombok and spring-boot-configuration-processor annotation processors

### ISSUE THREAD

**Issue by notizklotz** [spring-projects/spring-boot#30986]
I just made the same mistake as the reporter in #23405 that I had `spring-boot-configuration-processor` ordered before `lombok` in my pom.xml and thus combining `@lombok.Value` with `@ConstructorBinding` didn't work with the configuration-processor.

It would be great to have an info box in the [Configuration Metadata](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#appendix.configuration-metadata.annotation-processor) mentioning the importance of the order of the dependencies if using Lombok.

**Comment by tudormarc** [comment]
@philwebb @wilkinsona I added a PR for this issue :)

**Comment by wilkinsona** [comment]
Thanks, @tudormarc. Closing in favor of #31190.
