### ISSUE TITLE
Custom Favicon missing in the documentation

### ISSUE THREAD

**Issue by craph** [spring-projects/spring-boot#31026]
Hello,

I'm opening this issue because it seems the part about the custom Favicon is missing in the documentation.
Starting from Spring Boot version 2.4.0 there is no more mention about custom Favicon in the documentation.

The last time we can find it in the documentation it's in version 2.3.9 here : https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-favicon

Why this part have been removed ?

Thank you very much.
Best regards,

**Comment by wilkinsona** [comment]
Thanks, @craph. It looks like we removed a bit too much in https://github.com/spring-projects/spring-boot/commit/5fceb9d5b7e0c6ed32642d2d5bbaed524f13dc33.
