### ISSUE TITLE
UTF-8 Encoding error in application.properties

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3102]
Hi all,

I noticed if my application.properties is using UTF-8 encoding, some properties does not work.

For example banner shows if using UTF-8, when it should not.
```
application.properties
--------------------------
spring.main.show-banner=false
```

Case if it is set to "UTF-8 without BOM" or "ANSI" banner does not appear (works).

any idea?

**Comment by snicoll** [comment]
There is no need to create another issue: #3094 has already all the information that you need (thank you @tdemande!). Let me remind you that this tracker is meant for bug reports and feature requests and questions should be raised on stackoverflow.

(This issue has nothing to do with Spring Boot, by the way; properties must be encoded properly see http://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle)
