### ISSUE TITLE
Toggling dark mode on Spring.io makes widget text content unreadable due to extremely low contrast ratio (a11y)

### ISSUE THREAD

**Issue by tannerdolby** [spring-projects/spring-boot#31034]
## What's The Problem?
Accessibility concern for "Get Code" text in right sidebar widgets when toggling dark mode. When the sidebar widget containing a link to the GitHub repo gets updated, the parent container `<div class="right-pane-widget--container desktop-only">` background isn't updated to inherit from `body.dark` and instead keeps its light background.

p.s. I wasn't sure if this repo was the correct place to raise an issue regarding the docs site, my apologies if the issue needs to be transferred.

### Steps To Reproduce
1. Navigate to https://spring.io/guides/gs/consuming-rest/
2. Toggle the dark mode
3. See right sidebar widget text "Get Code" become very unreadable due to very low contrast ratio (white text on light background)

### Screenshots
<img width="1280" alt="Screen Shot 2022-05-14 at 1 06 42 AM" src="https://user-images.githubusercontent.com/48612525/168417002-a8b44280-d71f-486c-90ad-3774a19f78ef.png">

### Contrast 
<img width="1280" alt="Screen Shot 2022-05-14 at 1 03 42 AM" src="https://user-images.githubusercontent.com/48612525/168416983-c4259436-f982-47cc-9562-1c5e9334fc9f.png">

### Solution
Select the widget container and update its background to use the same background `#1b1f23` as the `.dark` class.
```css
body[class=dark] .right-pane-widget--container {
    background: #1b1f23;
    /* or background: inherit; */
}
```

Or update the existing selector `#guide main .right-pane-widget--container` when `body[class=dark]` to maintain the higher specificity selector rules.

Expected Result:
<img width="1280" alt="Screen Shot 2022-05-14 at 1 35 21 AM" src="https://user-images.githubusercontent.com/48612525/168418025-5b8419e1-d81b-4c2c-b0e4-83bad0aa476f.png">

**Comment by wilkinsona** [comment]
Thanks for raising this, @tannerdolby. Unfortunately, as you suspected, this isn't the right place as the spring.io website is not part of the Spring Boot project. https://github.com/spring-io/sagan is the correct repository. It's in a separate GitHub organization which means we can't transfer the issue. Could you please open an issue in the Sagan repository?

**Comment by tannerdolby** [comment]
No problem, @wilkinsona. Thank you for the clarification. I've opened the same [issue](https://github.com/spring-io/sagan/issues/1067) in the Sagan repository.

**Comment by wilkinsona** [comment]
Thanks, @tannerdolby.
