### ISSUE TITLE
Fix deprecation warnings in MongoDataAutoConfiguration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3105]

**Comment by wilkinsona** [comment]
@christophstrobl It looks like it's impossible to use different values for `databaseName` and `authenticationDatabaseName` in `SimpleMongoDbFactory` without calling deprecated API. Have I missed something?

**Comment by christophstrobl** [comment]
@wilkinsona the MongoDB Java driver 3.0 [dropped `authenticate` on `DB`][0] in favor of [`MongoCredential` used by `MongoClient`][1]. So you might want to use the constructor taking `MongoClient` or `MongoClientURI`.
Hope that helps.

[0]: http://mongodb.github.io/mongo-java-driver/3.0/whats-new/upgrading/#db
[1]: https://docs.mongodb.org/ecosystem/tutorial/authenticate-with-java-driver/#normal-authentication

**Comment by eddumelendez** [comment]
Inject MongoClient and MongoClientURI with credentials does not have effects. This is the private constructor used by no deprecated constructors.
https://github.com/spring-projects/spring-data-mongodb/blob/52bff39c22339807db5f03dec3ede45854615005/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/SimpleMongoDbFactory.java#L158-L169

I've already submit a PR, feedback is welcome.
