### ISSUE TITLE
Project cannot be build under WSL due to NAME environment variable

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#31076]
I'm unable to build the project in WSL environment due to `ConfigurationPropertiesTests#loadWhenBindingWithDefaultsInXmlShouldBind` failing. More specifically, this assertion is failing:
https://github.com/spring-projects/spring-boot/blob/f17a00aad1d2d5753e5313268a2b40f1568bd22a/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/context/properties/ConfigurationPropertiesTests.java#L258

It seems that this is due to WSL exposing the hostname (which is the actual value of `name` property I'm seeing when the test fails) in the `NAME` environment variable and thus overrides the value set in `spring-boot-project/spring-boot/src/test/resources/org/springframework/boot/context/properties/testProperties.xml`.

**Comment by vpavic** [comment]
I can confirm that the project now builds successfully in WSL - thanks for the prompt fix.

**Comment by LinkDownZ** [comment]
The value of the `NAME` variable is indeed the same as the Windows hostname, and the compilation can temporarily succeed by using `unset NAME`.
