### ISSUE TITLE
Jetty 9.3 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#3108]
Jetty 9.3 was announced [last week] and It requires Java 8. I think that 9.3 is important because of Http2 and other features. Will Spring Boot 1.3 support Jetty 9.3?

[last week]: https://webtide.com/jetty-9-3-features/

**Comment by wilkinsona** [comment]
I doubt that we'll move to 9.3 as the default as we don't want to require Java 8 by default. That said, it looks like 9.3 should be a drop-in replacement for 9.2 so you should be able to override the dependency management and use 9.3.

Note that there's [a bug with client auth in 9.3](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469863)  which causes a test failure when Boot's built against it.

**Comment by cemo** [comment]
Thanks for the information. Is there any timeline about default support for java 8?

**Comment by wilkinsona** [comment]
Spring Boot will require Java 8 when it moves to Spring Framework 5.0, based on the [current plans for Spring Framework 5.0](https://spring.io/blog/2015/06/10/feedback-welcome-spring-5-system-requirements) I'd expect that to be sometime next year.

It's worth noting that, as a user of Spring Boot, you can already use Java 8 and take advantage of its new functionality with the current versions of Boot. You may have to override a version number or two (as is the case with Jetty 9.3), but that's it. We also have some new features in Boot 1.3 that [detects that you're running on Java 8 and offers enhanced functionality](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-metric-repositories).

**Comment by philwebb** [comment]
Marking as `wontfix`. At least for now.
