### ISSUE TITLE
Local code cannot find git tag 2.6.7

### ISSUE THREAD

**Issue by AntsCodeCommunity** [spring-projects/spring-boot#31090]
I pulled the latest code, but I can't find git tag 2.6.7 ❓❓❓ 🧐

![SP2 6 7](https://user-images.githubusercontent.com/70638841/168943373-463847fa-f67a-400a-a60f-e3064d4f18d0.png)
![image](https://user-images.githubusercontent.com/70638841/168943396-d4cf595c-09fa-4590-9414-ba378a6959cc.png)

**Comment by diguage** [comment]
Maybe you can try this command `git fetch --all --tags`

**Comment by AntsCodeCommunity** [comment]
> 也许你可以试试这个命令`git fetch --all --tags`

Thanks a lot, it's an effective way. 😬
![image](https://user-images.githubusercontent.com/70638841/168953944-1bb0693a-c7e2-405c-86ef-324bbeaf9021.png)
