### ISSUE TITLE
Database queries logging enhancement

### ISSUE THREAD

**Issue by oleksandr-skoryi** [spring-projects/spring-boot#31105]
Hi team, thank you for the brilliant spring-boot, however there is a few things for improvement
This issue exists for a decades.

In the spring-boot 3 I want to be able to log hibernate queries in a more efficient way:

1. Be able to see compiled queries in the logs
2. Be able to track the query time 
3. Add only-for-slow-query option
4. Be able to disable the option partially/completely on different envs

The motivation is to do not use 3-rd party libs which are mostly nonames
Example: https://github.com/ttddyy/datasource-proxy

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we do not want to reinvent the wheel here and there are already a number of well-maintained projects that tackle this problem. Tadaya's datasource proxy is one example. You may also be interested in https://github.com/gavlyukovskiy/spring-boot-data-source-decorator which provides Spring Boot integration for datasource proxy among others.
