### ISSUE TITLE
Document that Undertow's record-request-start-time server option must be enabled for %D to work in access logging

### ISSUE THREAD

**Issue by JCass149** [spring-projects/spring-boot#31103]
In [this paragraph](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/webserver.adoc#configure-access-logging) it is stated:

> Access logging for Undertow can be configured in a similar fashion, as shown in the following example:
> 
> ```yaml
> server:
>   undertow:
>     accesslog:
>       enabled: true
>       pattern: "%t %a %r %s (%D ms)"
> ```

However, the `%D` RESPONSE_TIME [exchange attribute](https://undertow.io/undertow-docs/undertow-docs-2.0.0/#exchange-attributes-2) does not work "out of the box" with Spring Boot (at least for me with spring-boot-starter-parent 2.3.8.RELEASE).

I needed to also add the following:

```
server
  undertow:
    options:
      server:
        record-request-start-time: true
```

Should the docs be updated to reflect this?

Thanks :)

**Comment by barryzpc** [comment]
> In [this paragraph](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/webserver.adoc#configure-access-logging) it is stated:
> 
> > Access logging for Undertow can be configured in a similar fashion, as shown in the following example:
> > ```yaml
> > server:
> >   undertow:
> >     accesslog:
> >       enabled: true
> >       pattern: "%t %a %r %s (%D ms)"
> > ```
> 
> However, the `%D` RESPONSE_TIME [exchange attribute](https://undertow.io/undertow-docs/undertow-docs-2.0.0/#exchange-attributes-2) does not work "out of the box" with Spring Boot (at least for me with spring-boot-starter-parent 2.3.8.RELEASE).
> 
> I needed to also add the following:
> 
> ```
> server
>   undertow:
>     options:
>       server:
>         record-request-start-time: true
> ```
> 
> Should the docs be updated to reflect this?
> 
> Thanks :)

I couldn't agree with you more, and you solved my problem. thank you
