### ISSUE TITLE
Switch CI to Bellsoft JDK

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#31124]
CI could be switched to the Bellsoft JDK to align with buildpacks.

Details of the API are at https://api.bell-sw.com/api.html#/Binaries/get_liberica_releases

We'd need something like this in our existing scripts:

```
curl "https://api.bell-sw.com/v1/liberica/releases?version-feature=17&version-modifier=latest&os=linux&arch=x86&bitness=64&package-type=tar.gz&bundle-type=jdk"
```

**Comment by wilkinsona** [comment]
Closing in favor of #31139.
