### ISSUE TITLE
spring-boot-starter-data-r2dbc: 'dependencies.dependency.version' for dev.miku:r2dbc-mysql:jar is missing since 2.7

### ISSUE THREAD

**Issue by sp00m** [spring-projects/spring-boot#31135]
I used to have the following working fine on 2.6:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
</dependency>
<dependency>
    <groupId>dev.miku</groupId>
    <artifactId>r2dbc-mysql</artifactId>
</dependency>
```

But since 2.7, I'm getting:

```
'dependencies.dependency.version' for dev.miku:r2dbc-mysql:jar is missing
```

I must have missed something in the R2DBC-related dependencies updates in 2.7, but I couldn't find my way out, what's the recommended Maven config for SpringBoot + R2DBC + MySQL? Is `dev.miku:r2dbc-mysql` still supported?

Perhaps related:
- https://github.com/spring-projects/spring-data-r2dbc/issues/753
- https://github.com/spring-projects/spring-boot/issues/31015

**Comment by linghengqian** [comment]
- This is instead expected behavior, because according to https://github.com/r2dbc/r2dbc-bom/issues/53 , initializing a project via `start.spring.io` requires adding a version number to `dev.miku:r2dbc-mysql`, similar
````
<dependency>
     <groupId>dev.miku</groupId>
     <artifactId>r2dbc-mysql</artifactId>
     <scope>runtime</scope>
     <version>0.8.2.RELEASE</version>
 </dependency>
````
- According to https://twitter.com/mp911de/status/1527570621210804224?s=20&t=DhIv6rS1z9k_RaXXFVxNMQ , I can't seem to contact the author of this dependency.

**Comment by sp00m** [comment]
I see, fair enough, thanks for pointing me to these links I couldn't find.

It's indeed a bit concerning that this lib went silent since 0.8, I hope the author is doing alright.

Would you recommend moving to https://github.com/jasync-sql/jasync-sql then?

**Comment by snicoll** [comment]
I've added a reference to the upgrade to R2DBC Borca https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes with a link to their release announcement. I am afraid we can't recommend what the next step should be. Please ask the R2DBC team.

**Comment by linghengqian** [comment]
Should we explicitly add the version number to the `dev.miku:r2dbc-mysql` in the MySQL dependency at https://github.com/spring-io/start.spring.io to avoid the exception, because this Dependency not managed version number?

**Comment by wilkinsona** [comment]
@linghengqian Please see Stephane's comment immediately above yours where he said the following:

> I am afraid we can't recommend what the next step should be. Please ask the R2DBC team.

**Comment by wilkinsona** [comment]
@linghengqian I've opened https://github.com/spring-io/start.spring.io/issues/921 to figure out what to do on start.spring.io.

**Comment by sp00m** [comment]
Just a heads up, I've ended up using MariaDB's driver against our MySQL instances, worked like a charm. I'll keep an eye on the MySQL driver, thanks for the support.

**Comment by linghengqian** [comment]
> Just a heads up, I've ended up using [MariaDB's driver](https://github.com/mariadb-corporation/mariadb-connector-r2dbc) against our MySQL instances, worked like a charm. I'll keep an eye on the MySQL driver, thanks for the support 🙌 

- As a reminder, there are known issues with `testcontainer` that use the `Mariadb R2DBC driver` to connect to `MySQL Container`, see https://github.com/jhipster/generator-jhipster/pull/18511 . 

- If someone could bring `dev.miku:r2dbc-mysql` to Oracle's MySQL forum, continue to discuss its future with the community, and point it there in this issue, it would be a better option.
