### ISSUE TITLE
Could not find io.r2dbc:r2dbc-postgresql:. issue after upgrading to org.springframework.boot from 2.6.7 to 2.7.0.

### ISSUE THREAD

**Issue by anna-berezowska** [spring-projects/spring-boot#31155]
We are using org.springframework.boot with r2dbc and postgres with following dependencies:
```
    implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
    implementation("org.postgresql:postgresql")
    implementation("io.r2dbc:r2dbc-postgresql")
```

This has been working fine before, but since spring boot upgrade to 2.7.0, we're getting an error:
```
Could not find io.r2dbc:r2dbc-postgresql:.
```

Could you let me know if this is expected and we should specify io.r2dbc:r2dbc-postgresql: version in our gradle.build?  
The same issue occurs when generating a new Spring boot project with Spring Data R2DBC via Initializr

**Comment by snicoll** [comment]
Thanks for the report. The new location for the driver is `org.postgresql:r2dbc-postgresql`, see the [R2DBC release announcement](https://r2dbc.io/2022/02/04/r2dbc-borca-released) that the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes) links to.

As for start.spring.io, this is a mistake on our end. I'll update the existing issue to mention that postgresql is also affected.
