### ISSUE TITLE
Consider alignment of MimeMappings with Tomcat's defaults

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31171]
See https://github.com/spring-projects/spring-boot/issues/30885 for background. Tomcat now has many more default mappings. We need to consider if we want to align with those new defaults and, if we do, how to go about it. There may be a more memory efficient way to do it then simply updating the static map in `MimeMappings`.

**Comment by philwebb** [comment]
Closing in favor of PR #32101. Thanks @terminux!
