### ISSUE TITLE
2.7.0 Upgrade issue with H2 datasource

### ISSUE THREAD

**Issue by bradf83** [spring-projects/spring-boot#31196]
I have a Spring Boot application upgrading to 2.7.0 from 2.6.8.

The application uses an H2 database configured in Oracle compatibility mode for running tests.

It seems the new version of H2 no longer allows the use of the LIMIT clause when in Oracle Compatibility mode.  It now throws an exception when trying to use the LIMIT clause during a standard `findAll(Pageable pageable)` from a Spring Data Repository.

This was not a problem in Spring Boot 2.6.8 and previous versions but seems to be an issue now with the upgrade of H2.

I have created a sample repository that highlights this issue: [Sample Repository](https://github.com/bradf83/sb27-h2-ora)

**Comment by bclozel** [comment]
We're aware of the breaking changes in H2. This has been covered [in our release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#h2-21). I don't think Spring Boot can do anything here as downgrading is not an option for us.

Hopefully this will help you resolve this problem.

**Comment by bradf83** [comment]
Hi @bclozel,

Thanks for looking into my issue, I did read the release notes and followed the H2 migration guide and did not find a resolution to this specific problem.  

I also looked through the H2 issue tracker and did find one issue related to this [related issue](https://github.com/h2database/h2database/issues/3269).

Based on the issue above it seems like maybe `LIMIT` could be implemented differently when talking to an H2 database.  Do you think something could be done in Spring Data JPA to resolve this issue?  Should I create an issue similar to this in their issue tracker?

I had a feeling this may not get fixed in Spring Boot but wanted to raise it here due to it happening during a Spring Boot upgrade.  

Thanks again.

**Comment by bradf83** [comment]
Thanks @wilkinsona,

I feel a bit silly for not thinking of the dialect, I will see if that helps for my situation.
