### ISSUE TITLE
Typos in Documentation(spring.factories --> spring-factories)

### ISSUE THREAD

**Issue by pxzxj** [spring-projects/spring-boot#31199]
There are two typos `META-INF/spring-factories` in chapter [Database Initialization](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/data-initialization.adoc)，correct is ‘META-INF/spring.factories’

**Comment by matei-cernaianu** [comment]
Hi @wilkinsona I am a new to open source contribution and I would like to help with this issue. Can you assign it to me ?

**Comment by wilkinsona** [comment]
Sure. Thanks for the offer, @matei-cernaianu. Please let us know if you have any questions.

**Comment by matei-cernaianu** [comment]
@wilkinsona I created a PR #31203 for this issue.

**Comment by snicoll** [comment]
Closing in favor of PR #31203
