### ISSUE TITLE
2.7.0版本-mongodb-reactive使用Repository方式过滤查询没有数据

### ISSUE THREAD

**Issue by DengChen2020** [spring-projects/spring-boot#31200]
### mongodb-reactive使用Repository方式过滤查询没有数据，springboot-version-2.7.0
示例：
@Repository
public interface UsersRepository extends ReactiveMongoRepository<Users,String> {

    /**
     * 根据用户名查询用户信息
     * @param username
     * @return
     */
    Mono<Users> findByUsername(String username);

}

**Mono<Users> usersMono = usersRepository.findByUsername(username);**

log日志：
**o.s.d.m.r.query.MongoQueryCreator        : Created query Query: { "username" : "\\"dc2020\\""}, Fields: {}, Sort: {}**

	原因可能是"\"dc2020\"" 多了\，导致查不出数据，reuslt==null

我尝试用下面这种查询方式得到了解决
	
@RequiredArgsConstructor
@Service
public class UsersServiceImpl implements UsersService {

    private final ReactiveMongoTemplate reactiveMongoTemplate;

    @Override
    public Mono<Users> findByUsername(String username) {
        return reactiveMongoTemplate.findOne(Query.query(new CriteriaDefinition() {
            @Override
            public Document getCriteriaObject() {
                Document document = new Document();
                document.put("username", username);
                return document;
            }

            @Override
            public String getKey() {
                return null;
            }
        }), Users.class);
    }
}

log日志：
**o.s.d.m.core.ReactiveMongoTemplate       : findOne using query: { "username" : "dc2020"} fields: {} in db.collection: dc.user**

**Comment by wilkinsona** [comment]
Unfortunately, I don't speak Chinese. Using Google translate, you appear to be asking about Spring Data MongoDB and how it creates queries. Spring Data MongoDB is managed as [a separate project](https://github.com/spring-projects/spring-data-mongodb). Please see the [Getting Help section of their README](https://github.com/spring-projects/spring-data-mongodb#getting-help) to learn how to get help with Spring Data MongoDB.

**Comment by DengChen2020** [comment]
> ### mongodb-reactive 使用Repository 无数据条件查询，springboot-version-2.7.0
> 译文： @repository 公共接口 UsersRepository 扩展 ReactiveMongoRepository<Users,String> {
> 
> ```
> /**
>  * Query user information by user name
>  * @param username
>  * @return
>  */
> Mono<Users> findByUsername(String username);
> ```
> 
> }
> 
> **Mono usersMono = usersRepository.findByUsername(username);**
> 
> 日志： **osdmrquery.MongoQueryCreator : Created query Query: { "username" : "\"dc2020\""}, Fields: {}, Sort: {}**
> 
> ```
> reasons may be "\"dc2020\"" one more \，cause no data to be found，reuslt==null
> ```
> 
> 我尝试了以下查询并得到了解决方案。
> 
> @RequiredArgsConstructor @service 公共类 UsersServiceImpl 实现 UsersService {
> 
> ```
> private final ReactiveMongoTemplate reactiveMongoTemplate;
> 
> @Override
> public Mono<Users> findByUsername(String username) {
>     return reactiveMongoTemplate.findOne(Query.query(new CriteriaDefinition() {
>         @Override
>         public Document getCriteriaObject() {
>             Document document = new Document();
>             document.put("username", username);
>             return document;
>         }
> 
>         @Override
>         public String getKey() {
>             return null;
>         }
>     }), Users.class);
> }
> ```
> 
> }
> 
> 日志： **osdmcore.ReactiveMongoTemplate : findOne using query: { "username" : "dc2020"} fields: {} in db.collection: dc.user**



> 不幸的是，我不会说中文。使用 Google 翻译，您似乎在询问 Spring Data MongoDB 以及它如何创建查询。Spring Data MongoDB 作为[一个单独的项目](https://github.com/spring-projects/spring-data-mongodb)进行管理。请参阅[他们的 README 的获取帮助部分](https://github.com/spring-projects/spring-data-mongodb#getting-help)以了解如何获得有关 Spring Data MongoDB 的帮助。

already edited
