### ISSUE TITLE
Update Wiki with up to date info on supported versions

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#31236]
Wiki home page currently says:

> Spring Boot 2.5 and 2.6 are the actively maintained versions.

I assume this should now be `2.6` and `2.7`, and that `2.5` should be removed as indicated by both [milestones](https://github.com/spring-projects/spring-boot/milestones) and the recent [release announcement](https://spring.io/blog/2022/05/19/spring-boot-2-5-14-available-now).

**Comment by snicoll** [comment]
Thanks, I've updated the wiki.
