### ISSUE TITLE
When building with Maven, classes generated by AOT are not included in final artifact

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#31245]
Commit 8cf63a28b8736e8839b019fa9e0178b70380f468 introduced an extra directory for generated classes. If the AOT engine generates a class, it is not copied in the final artifact at the moment.

**Comment by wilkinsona** [comment]
I think this is specific to Maven. It was fixed on the Gradle side as part of [these changes](https://github.com/spring-projects/spring-boot/commit/293a3c9ec15ac8ae83fe9dc1d8ef2c467c1d87bf).
