### ISSUE TITLE
Native version does not load the database properties

### ISSUE THREAD

**Issue by operrin** [spring-projects/spring-boot#31246]
Version 2.7.0 of Springboot (reactive), native (0.12) generation, MacOS, OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) 

I try to access a Pg database, hosted on my machine, using localhost:5432/orders.
Everything is working fine using the non-native version, the resource file is used as expected.
When generating the native version, and try to access the endpoint, I get this exception:

```
2022-06-03 14:32:15.209 ERROR 67389 --- [actor-tcp-nio-1] a.w.r.e.AbstractErrorWebExceptionHandler : [3dc865e0-1]  500 Server Error for HTTP GET "/intervenants/"

org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost/<unresolved>:5432
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler org.miage.intervenantservice.boundary.IntervenantRouter$$Lambda$33f6ea66eb22970ddf524a223f0b6a228e9aeae3@2ff3d3b3 [DispatcherHandler]
	*__checkpoint ⇢ HTTP GET "/intervenants/" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]

```

**Comment by snicoll** [comment]
@operrin native support in the 2.x line is experimental and handled in the Spring Native project. It's in a different org, so I am afraid I can't transfer this issue. Can you please create it there? https://github.com/spring-projects-experimental/spring-native

**Comment by operrin** [comment]
sorry for the error, and thanks for your great work.
