### ISSUE TITLE
Rename jmx start/stop bean

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3124]
The current name (`org.springframework.boot:type=Lifecycle,name=springApplicationLifecycle`) could be renamed to `org.springframework.boot:type=Lifecycle,name=SpringApplication`

**Comment by philwebb** [comment]
`LiveBeansView` from Spring Framework might be a good guide.

**Comment by snicoll** [comment]
While the initial goal of this was to expose a way to shutdown the app it has moved to something more "admin-related": know if the app is ready, get the http port, etc.

Maybe we should move that back to `o.s.boot` and name it `SpringApplicationAdminMXBean`

Some keys should migrate as well then. And `spring.application.*` looks like a bad idea I think. Thoughts?

We have `spring.context.lifecycle.enabled` and `spring.context.lifecycle.jmx-name`

**Comment by snicoll** [comment]
The JMX name looks weird to me and there is still a `spring.context.lifecycle.enabled` property there.

**Comment by snicoll** [comment]
This broke the maven plugin (start/stop). Looking at it

**Comment by mbert** [comment]
Yesterday's changes fixed the issue, thank you!

**Comment by philwebb** [comment]
@mbert Thanks for checking.
