### ISSUE TITLE
spring-boot-dependencies manages spring-ldap-ldif-batch which no longer exists

### ISSUE THREAD

**Issue by copbint** [spring-projects/spring-boot#31254]
[spring-ldap-ldif-batch](https://github.com/spring-projects/spring-boot/blob/7f291f8da0ee2a2d78af4cbf1d0e2c64811ebe26/spring-boot-project/spring-boot-dependencies/build.gradle#L1747) is not avaible in 2.4.0, it has been removed in this commit: [Update to Gradle 7.3.3](https://github.com/spring-projects/spring-ldap/commit/28f2ca6ee0a3e87df3afede1ec9aae1a36201197), shall we remove it from spring-boot-dependencies?

**Comment by wilkinsona** [comment]
Thanks for raising this, @copbint. The stale dependency management has now been removed.
