### ISSUE TITLE
Configuring a custom EnvironmentPostProcessor in 2.7.0 

### ISSUE THREAD

**Issue by ttulka** [spring-projects/spring-boot#31252]
How are change to auto-configuration in 2.7.0 effecting `EnvironmentPostProcessor` configuration? Will this stay in `spring.factories` as it has been, or are there any recommended preparations for 3.0.0 too?

**Comment by philwebb** [comment]
`EnvironmentPostProcessor` instances should still be configured via `spring.factories`. We're only planning to change auto-configuration imports because we want to remove `SpringFactoriesLoader.loadFactoryNames`.
