### ISSUE TITLE
Do not deploy the JARs repackaged through the `spring-boot-maven-plugin`

### ISSUE THREAD

**Issue by wangliang181230** [spring-projects/spring-boot#31259]
Do not deploy the JARs repackaged through the `spring-boot-maven-plugin`, because the JARs of the spring boot application cannot be referenced as a dependency, and the file is too large, taking up a lot of disk space.

Although I can configure `maven.deploy.skip=true` to skip `maven-deploy-plugin`, but I still hope the community can provide a better solution.

I developed a simple mojo to solve this problem, hoping to help the community:
https://github.com/easyj-projects/easyj/blob/develop/maven-plugin/src/main/java/icu/easyj/maven/plugin/mojo/UndeploySpringBootJarMojo.java

**Comment by snicoll** [comment]
The maven plugin already has a [property for this](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-attach).

**Comment by wangliang181230** [comment]
Oh, thank you.
