### ISSUE TITLE
Support ReloadableResourceBundleMessageSource in MessageSourceAutoConfiguration

### ISSUE THREAD

**Issue by deeaitche** [spring-projects/spring-boot#31269]
Currently ``ResourceBundleMessageSource`` is used as MessageSource in ``MessageSourceAutoConfiguration``. But in some way ``ReloadableResourceBundleMessageSource`` is more preferable. Would it be possible if the MessageSource type is configurable?

**Comment by snicoll** [comment]
@deeaitche thanks for the suggestion. This is a duplicate of #15007
