### ISSUE TITLE
Replace our TestCompiler with Spring Framework's version

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#31266]
Our test support has a `TestCompiler` (`org.springframework.boot.testsupport.compiler.TestCompiler`). Now that Spring Framework has a test module that ships with a more powerful variant, we should remove ours and adapt our existing tests.

**Comment by scottfrederick** [comment]
There are a few blockers to implementing this completely right now. 

[One Spring Boot test](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/ValueObjectBinderTests.java#L370-L391) compiles a class that implements a Java `record`. The [qdox](https://github.com/paul-hammant/qdox) library that Framework uses to parse and validate Java source [has a bug](https://github.com/paul-hammant/qdox/issues/85) that prevents it from properly parsing records. 

Most other Spring Boot tests verify some part of annotation processing, and rely on the `TestCompiler` invoking a `javax.annotation.processing.Processor` implementation. We'll need to add support for `Processor`s to the Framework `TestCompiler` before migrating those tests.

**Comment by philwebb** [comment]
We pretty much only use qdox now to get the fully-qualified class name. I think we could probably replace it with our own parser if we wanted.
