### ISSUE TITLE
spring.profiles.active  Deprecated

### ISSUE THREAD

**Issue by rola0411** [spring-projects/spring-boot#31306]
![image](https://user-images.githubusercontent.com/46880610/172771051-5d91afc0-0943-40bd-9da7-c6e50470282c.png)
How can I use different yml 
![image](https://user-images.githubusercontent.com/46880610/172771302-c922e4c3-f6b0-4e64-9805-fbac21df04e9.png)

It doesn`t work 
![image](https://user-images.githubusercontent.com/46880610/172771436-6e1efbb8-4d1a-430a-babd-aca5166d02ab.png)

**Comment by wilkinsona** [comment]
That's a bug in your IDE. While the old `spring.profiles` property is deprecated, `spring.profiles.active`, `spring.profiles.default`, and so on are not. You can see this [in the JSON that describes the properties](https://github.com/spring-projects/spring-boot/blob/12eb7a8795c3d84020e9c5cc62340c0ddab4bab3/spring-boot-project/spring-boot/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L910-L943). Can you please open an issue with the maintainers of your IDE or the Spring Boot plugin for your IDE and comment here with a link to it?
