### ISSUE TITLE
Maven shade plugin configuration in spring-boot-starter-parent does not append META-INF/spring/*.imports files

### ISSUE THREAD

**Issue by FloEberle** [spring-projects/spring-boot#31316]
Hello everyone

We are using maven shade in latest version 3.3.0 to build our jar. When upgrading from Spring Boot 2.6.8 to 2.7.0 the actuator endpoints seem no longer to work in the shaded jar.
Since I am unsure if this is caused by spring boot or maven shade, therefore I raised the [issue](https://issues.apache.org/jira/browse/MSHADE-421) there too.

I created a small [demo project](https://github.com/FloEberle/demo-spring-boot-maven-shade-actuator-endpoints-broken) to visualize the issue. All help is appreciated.

Thanks in advance!

**Comment by philwebb** [comment]
Thanks for the report. This is due to changes we made to the way that auto-configuration classes are found. You can fix your build by changing the `<transformers>` section to:

```xml
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/spring.handlers</resource>
                  <resource>META-INF/spring.schemas</resource>
                  <resource>META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports</resource>
                  <resource>META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports</resource>
                </transformer>
```

**Comment by philwebb** [comment]
We should update our `spring-boot-starter-parent` project and also check our documentation.

**Comment by FloEberle** [comment]
Thanks a lot, that actually resolves the issue! 😎 
How can I buy u a coffee/beer @philwebb ? 🙃

**Comment by mf81bln** [comment]
@philwebb Thanks a lot for the quick response! ❤️ 

I assume this is the change you're referring to?
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration

If so, perhaps it would be helpful to mention the necessary changes in the release notes? Even though many rely on the spring-boot-starter-parent, I assume that others also encounter the same problem as we do.

**Comment by mf81bln** [comment]
@philwebb Thanks a lot! ❤️
