### ISSUE TITLE
Add resource hints for default templates location

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#31310]
Similar to #31278, it would be great to add resource hints for templates (if possible taking in account the configured value). Current regexp generated by Spring Native is `"pattern": "^templates/.*"`.

**Comment by wilkinsona** [comment]
This feels like something that the existing `TemplateAvailabilityProvider` implementations could help with. They're already loaded via `spring.factories` so using them at build time shouldn't cause any problems. Also, they already make use of the `prefix` and `suffix` application properties so they know where to look for templates.

**Comment by snicoll** [comment]
We've had a look to `TemplateAvailabilityProvider` and changing that is quite involved. For consistency with other issues that "just" register the defaut location, we're going to do the same here.
