### ISSUE TITLE
OAuth2 Resource Server Auto-Configuration can only configure a single JWS algorithm

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31321]
See PR #31230 for background.

**Comment by wilkinsona** [comment]
The differences between using a JWK Set URI and a public key location present an interesting problem. We configure both using the same `jws-algorithm` property but only the former can potentially support multiple values when creating the JWT decoder.

Use of a JWS Set URI or a public key location is mutually exclusive and we'll only ever auto-configure one decoder. This means that we could change both to use the new `jws-algorithms` property. We'd then have to handle the case where multiple algorithms and a public key location have been configured. I've implemented a proposal for this in [this branch](https://github.com/wilkinsona/spring-boot/commit/ee8be24364a4808f1606f3986990ad1c83dc4789).

**Comment by mhalbritter** [comment]
Your changes look good to me.
