### ISSUE TITLE
Remove unchecked raw casts

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31326]
There are unchecked raw casts in `TracingObservationHandlerGrouping` and `OnlyMetricsObservationHandlerGrouping` which can be removed once Micrometer 1.10.0-M3 is released, as this release contains https://github.com/micrometer-metrics/micrometer/pull/3173

**Comment by TheoCaldas** [comment]
Hi, there! Can I be assigned to this?

**Comment by snicoll** [comment]
@TheoCaldas thanks but you're already assigned to an issue. Let's take that one step at a time please.
