### ISSUE TITLE
@ConditionalOnMissingBean does not control @Component and @Service annotated beans

### ISSUE THREAD

**Issue by liubinduo** [spring-projects/spring-boot#31325]
The column code is as follows

``` java
@Component
@ConditionalOnMissingBean(value = ILogin.class)
public class LoginImpl implements ILogin {
}
```
I'm pretty sure Context doesn't have an instance of ILogin. Why can't LoginImpl be instantiated?

``` java
@RestController
@RequestMapping("login")
public interface ILogin {
    
    @PostMapping
    IRestResponse<?> login(@RequestBody @Validated LoginAccount account);
}
```
When I post ask "/login". return Not Found "/login"

I think it's a Bug, @Component and @Service annotations can be scanned and registered by @componentscan, and @ConditionalOnMissingBean should be able to control.

**Comment by snicoll** [comment]
There's no need to create a duplicated issue.
