### ISSUE TITLE
Rest service with Spring Boot and Jersey incorrectly returns HTTP Status 404 when resource exist and method is not allowed

### ISSUE THREAD

**Issue by johanhammar** [spring-projects/spring-boot#3132]
Hi!

**Description**
I've developed a small Rest API using Spring Boot and Jersey. It seems to work well except for when calling the Rest API with a method that is not allowed, i.e calling the service with PUT and only GET is allowed. This leads to a HTTP 404 Not Found instead of HTTP 405 Method Not Allowed.

**Workaround**
Setting an alternative base path using @ApplicationPath, i.e. @ApplicationPath("/api") results in HTTP 405 Method Not Allowed as expected.

It should be possible to map the api to / using Jersey.

Thanks!

**Comment by candlejack297** [comment]
I noticed this as well. The interesting thing is that response still returns the Allow header with the proper methods, so I assume the status is just being set incorrectly somewhere.

**Comment by wilkinsona** [comment]
You can map the API to `/` when using Jersey, but you have to ensure that Spring MVC isn't also using the same path. When they're both using the same path, Jersey can't handle the `PUT` so Spring MVC tries instead. It doesn't have a mapping for `/` so it responds with a 404. If you want to map Jersey to `/` and use Spring MVC, then you need to set `server.context-path` to move Spring MVC out of the way.

The workaround described by @candlejack297 switches off the auto-configuration of Spring MVC so it's no longer mapped to `/` and no longer competes with Jersey for the same path.
