### ISSUE TITLE
Configure Tomcat http2 upgrade protocol via properties

### ISSUE THREAD

**Issue by kzwang** [spring-projects/spring-boot#31324]
There are many http2 upgrade protocol configurations for Tomcat (https://tomcat.apache.org/tomcat-9.0-doc/config/http2.html), currently, those cannot be configured via Spring Boot `ServerProperties`, we can use `TomcatConnectorCustomizer` to configure those but ideally we can just use properties to do it similar to many other properties.

**Comment by philwebb** [comment]
A little analysis on what we currently support:

| Tomcat | Spring Boot |
| --- | --- |
| `compressibleMimeType` | `server.compression.mime-types` |
| `compression` | `server.compression.enabled` |
| `compressionMinSize` | `server.compression.mind-response-size` |
| `initialWindowSize` | - |
| `keepAliveTimeout` | `server.tomcat.keep-alive-timeout` |
| `maxConcurrentStreamExecution` | - |
| `maxConcurrentStreams` | - |
| `maxHeaderCount` | - |
| `maxHeaderSize` | `server.max-http-header-size` |
| `maxTrailerCount` | - |
| `maxTrailerSize` | - |
| `noCompressionStrongETag` | deprecated in Tomcat |
| `noCompressionUserAgents` | `server.compression.excluded-user-agents` |
| `overheadContinuationThreshold` | - |
| `overheadCountFactor` | - |
| `overheadDataThreshold` | - |
| `overheadWindowUpdateThreshold` | - |
| `readTimeout` | - |
| `streamReadTimeout` | - |
| `streamWriteTimeout` | - |
| `useSendfile` | - |
| `writeTimeout` | - |

**Comment by wilkinsona** [comment]
Some of those aren't specific to HTTP/2:

- `maxHeaderCount` (HTTP 1.1 `maxHeaderCount`)
- `readTimeout` (HTTP 1.1 `connectionUploadTimeout` or `connectionTimeout`)
- `writeTimeout` (HTTP 1.1 `connectionTimeout`)

We may also want to consider which properties are available across all four web servers. For example, in addition to Tomcat, Jetty, Netty, and Undertow all also allow `maxConcurrentStreams` to be configured.

**Comment by philwebb** [comment]
We discussed this as a team today and decided that we don't currently want to add any additional server properties. We feel that the `TomcatConnectorCustomizer` is the best option for users that want to configure more advanced aspects.
