### ISSUE TITLE
Support setting spring.config.* from manifest in War and JarLauncher.

### ISSUE THREAD

**Issue by rpomeroy** [spring-projects/spring-boot#3134]
When delivering a single war artifact that is both executable and JBoss deployable:

Whether deploying to JBoss or just executing the jar we want to override `spring.config.name` and augment `spring.config.location` in a consistent way.  Regardless how it's run we want the config file name to be our custom one (to avoid collision in the JBoss shared config directory `${jboss.server.config.url}`) when multiple apps are deployed in one container - and to avoid having to set system properties externally. We want names and search locations to be internal config.  

The `PropertiesLauncher` has the nice ability to get this from `MANIFEST.MF`.  If the `WarLauncher` and `JarLauncher` could look there too it would solve the problem quite elegantly.  

See http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/loader/PropertiesLauncher.html

I had to add a static initializer block to set those properties early enough to get it to work.  Ugly.  

If I can muster the time I'll try to work it out.  Just wanted to get this on the radar.  Thanks.

**Comment by dsyer** [comment]
You would have to use `System` properties in a `JarLauncher` (it has no notion of application specific property sources)? I guess that's what `PropertiesLauncher` does?

**Comment by jedvardsson** [comment]
Yes, this would be great. There is an issue in Intellij for picking up this setting. See https://youtrack.jetbrains.com/issue/IDEA-133445

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
