### ISSUE TITLE
Maven plug-in does not create outputDirectory

### ISSUE THREAD

**Issue by lcardito** [spring-projects/spring-boot#3136]
Hi guys,

I am using the spring boot mvn plug-in version 1.2.2.RELEASE to package my application in an executable jar.
When I specify the outputDirectory but this directory does not exist I'd like the plug-in to create the directory for me.

Thanks,
Luigi

**Comment by lcardito** [comment]
Hi @snicoll, I would also like to be involved in the development for this enhancement if possible?

Thanks,
Luigi

**Comment by snicoll** [comment]
Of course!

**Comment by snicoll** [comment]
There is something that you didn't mention and that is very important. Did you use a `classifier` because if you don't, that does not work either (it's trying to attach the artifact with a `null` classifier.
