### ISSUE TITLE
Upgrade to Spring Security 4.0.1

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3137]
Upgrade to new version of Spring Security 4.0.1

```
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-core</artifactId>
	<version>4.0.1.RELEASE</version>
</dependency>
```

**Comment by nomack84** [comment]
Spring Boot 1.3 already depends on Spring Security 4.0.1: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L132

**Comment by snicoll** [comment]
Indeed.
