### ISSUE TITLE
Unexpected Memory usage with spring boot 2.7.0

### ISSUE THREAD

**Issue by Thorndike** [spring-projects/spring-boot#31383]
After upgrading from spring boot 2.6.7 to 2.7.0 we experience an unexpected increase in memory usage. The average memory usage of the JVM increased from about 200MB to over 1G. Attached is a Screenshot of our Grafana monitoring.
Are there any changes that need to be done to get the memory consumption down again?

![memory](https://user-images.githubusercontent.com/10463352/173580609-7c01378f-36d3-495c-a594-49a7af535787.png)

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Thorndike** [comment]
Sorry! This was coincidence instead of correlation. We had a load increase due to external factors that changed at the same time.

**Comment by bclozel** [comment]
Thanks for letting us know @Thorndike
