### ISSUE TITLE
Provide an easy way to instantiate configuration properties programatically

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#3138]
Current way to instantiate a configuration properties programatically requires substantial amount code. Please provide an easy way to create an instance by provided property sources.

**Comment by snicoll** [comment]
You mean bind the `Environment` to an instance? Please be a bit more specific. Should that read the prefix on the annotation? What's the use case?

**Comment by cemo** [comment]
I would like to create an instance of configuration properties but not exposed as a bean. 

Let's say that I have `PhotoStoreProperties`:
```
public class PhotoStoreProperties {
     String username;
     String password;
}
```
I have an autoconfiguration class which is creating a `PhotoService` bean. This service is depends on PhotoStoreProperties. But I do not want to expose a `PhotoStoreProperties` bean. This is important because `PhotoStoreProperties` is actually only related to `PhotoService`. I prefer programatically bind a namespace to `PhotoStoreProperties` with Environment.

**Comment by snicoll** [comment]
That still does not answer my questions. It looks like you want to bind a class using the relaxed binder and a prefix that you know. In my book, that's 5 lines of code so maybe you could share what you wrote instead?

**Comment by cemo** [comment]
Previous questions:

1. I am trying to bind an environment to an instance.
2. I am considering to provide necessary prefix to it. 
3. Shared my use case.  

Current question: 

1. I have just checked https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessor.java#L266-L306 and thought that It might be easier to create an instance of configuration bean. Actually I was considering methods like Environment has. 

Hope that makes clear?

**Comment by snicoll** [comment]
Are you mad if I say "not really"?  

`Environment` has nothing to do with configuration property binding and I still don't know if that code would read the `@ConfigurationProperties` annotation. If you don't and you have the prefix at hand, it's 5 lines of code, really. Why don't you submit a PR of what you have in mind? If you don't know how to do it, that's a different problem obviously.

**Comment by cemo** [comment]
Sorry for confusion, 

> I am trying to bind an environment to an instance. 

should be:

> I am trying to bind from environment to an instance.

My autoconfiguration class knows which prefix will be used. Actually I am looking for a programmatic replacement for this :

```
      @Bean
      @ConfigurationProperties(prefix = "app.photo.store.fs")
      public PhotoStoreProperties getPhotoStoreProperties() {
         return new PhotoStoreProperties();
      } 
```

Could you share your 5 lines please?

**Comment by snicoll** [comment]
Sharing that code would have saved us a lot of time. Like I said already, taking the `@ConfigurationProperties` handling aside, it's this

```java
PhotoStoreProperties target = new PhotoStoreProperties();
new RelaxedDataBinder(target, "app.photo.store.fs").bind(env.getPropertySources());
```

If you want what the post-processor does, let's try to extract that code then...

**Comment by cemo** [comment]
Thank you.

**Comment by LiamMorrow** [comment]
Not too hard to find, but for those coming to this page in Spring Boot 2:
```java
Binder binder = Binder.get(environment);

FooClass fooConfig = binder.bind("foo", Bindable.of(FooClass.class)).get();
```

See:
https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0
