### ISSUE TITLE
Add filewatcher timing properties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3139]
Would be nice to allow watch timing to be tweaked.

**Comment by snicoll** [comment]
Maybe a related remark: using "save" feature in Eclipse would not work in other environment (Intellij IDEA auto-saves your files as you edit them).

**Comment by philwebb** [comment]
It's actually the class files that cause the reload, so I think IDEA should behave a bit better since it only recompiles when you do a full build.
