### ISSUE TITLE
Register SpringApplication as a bean

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#31393]
It would be helpful if we could get `SpringApplication` from an `ApplicationContext`. We should register it as a bean.

**Comment by snicoll** [comment]
I assume that we intend to do so as a programmatic singleton. Creating it as a regular bean (i.e. with a bean definition) means that AOT will optimize it and it may or may not be what we want.

**Comment by MatheusPK** [comment]
Hi, everyone! My team would like to tackle this one. is it ok?

**Comment by snicoll** [comment]
@MatheusPK thanks for the offer but we're in the middle of a design phase where this particular issue is part of a bigger theme.

**Comment by philwebb** [comment]
There was a driver for this, but I can't remember exactly what it was. Feels like something we can push back.
