### ISSUE TITLE
java.net.PortUnreachableException with Spring boot 2.6.6 and micrometer 1.8.4

### ISSUE THREAD

**Issue by sureshnomula74** [spring-projects/spring-boot#31399]
We are using micrometer and statsd to push our metrics to influx db, but after upgrading to spring boot to 2.6.6 version we are seeing lot of PortUnreachableException warning in our logs.

f69c5f39, L:/127.0.0.1:44835 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: readAddress(..) failed: Connection refused

Do we need to use any specific versions of spring /micrometer to fix this?

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, a single log message isn't enough for us to diagnose the problem. If you would like us to spend some more time investigating, please take the time to describe the problem in more detail. At a minimum, we will need to know the version of Spring Boot that you were using previously and more details about the error. It's unclear at the moment what component's connection attempt was refused. As the error message suggests, you should use debug level logging to produce a full stack of the problem.

**Comment by sureshnomula74** [comment]
Previously we are using spring boot 2.4.5 and  we have  "io.micrometer:micrometer-registry-statsd:1.5.1" also in class path, our app pushes metrics to statsd server. 

After upgrading to spring boot 2.6.6 and "io.micrometer:micrometer-registry-statsd:**1.8.4**" we are seeing these warnings.

**Comment by wilkinsona** [comment]
Thanks. As requested above, please provide the full stack trace as well.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by VinayagamBabu** [comment]
I think this issue is related to micrometer repository. I see a open issue available in here [2624](https://github.com/micrometer-metrics/micrometer/issues/2624)

**Comment by wilkinsona** [comment]
Thanks, @VinayagamBabu. That does look like the same problem. Closing in favour of the existing Micrometer issue.
