### ISSUE TITLE
spring.config.activate.on-profile makes empty inject bean

### ISSUE THREAD

**Issue by lfz757077613** [spring-projects/spring-boot#31401]
springboot: 2.5.14
when I set "spring.config.activate.on-profile", all field of  StaticConfig are null. But it works well for "spring.profiles.active"
![image](https://user-images.githubusercontent.com/16242100/173989261-56147fdf-a0dc-4366-a46a-e1a4fa490c13.png)
This is a simple project
[untitled1.tar.gz](https://github.com/spring-projects/spring-boot/files/8915594/untitled1.tar.gz)

**Comment by wilkinsona** [comment]
`spring.profiles.active` configures the profiles that are active.

`spring.config.activate.on-profile` indicates that the configuration should only be active when the named profile is active. On your screenshot above I can just see that only the default profile is active so the configuration has not been applied. Please refer to [the documentation](https://docs.spring.io/spring-boot/docs/2.6.x/reference/htmlsingle/#features.external-config.files.activation-properties) for further details.

Also, please note that Spring Boot 2.5.x is no longer supported. You should upgrade to 2.6.x or 2.7.x as soon as possible.

**Comment by lfz757077613** [comment]
ohh, I was wrong. Only "spring.prifiles" is deprecated, "spring.profiles.active" still work.
When I see ConfigFileApplicationListener has "@Deprecated", I thought all of "spring.prifiles*" config should be replaced by "spring.config*"
Thanks for reply
