### ISSUE TITLE
Trailing whitespace in the value of a property is hard to identify in failure analysis descriptions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31407]
I think we should quote or somehow delimit the value that's output in the failure analysis. It looks like this at the moment:

```
Property: spring.servlet.multipart.file-size-threshold
Value: 2KB 
Origin: class path resource [application.properties]:24:46
Reason: failed to convert java.lang.String to org.springframework.util.unit.DataSize
```

I think something like this would be better:

```
Property: spring.servlet.multipart.file-size-threshold
Value: "2KB "
Origin: class path resource [application.properties]:24:46
Reason: failed to convert java.lang.String to org.springframework.util.unit.DataSize
```

**Comment by TheoCaldas** [comment]
Hey! I think I might know how to resolve that. May I try it out?

**Comment by snicoll** [comment]
@TheoCaldas cool, it's all yours. Let us know if you have any question.

**Comment by EduColnago** [comment]
Hi!  i would like to tackle this one. is it ok?

**Comment by TheoCaldas** [comment]
Hi, I've been wondering about some design decisions. Is it better to delimit the value with "" in all cases or only if there is a trailing whitespace? I think it terms of standardization, the first one is the way to go. What do you think?

**Comment by snicoll** [comment]
It should be quoted in all cases.

**Comment by philwebb** [comment]
Closing in favor of PR #31571. Thanks @TheoCaldas!
