### ISSUE TITLE
Error on CAS redirect when ticket is SERVICE_TICKET_CREATED

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3141]
Hi all,

One client application in Spring Boot (Spring Security + Tomcat) try to authenticate against CAS (Central aunthencation Service) that runs in JBoss 7.1, after detect that user is not authenticated, application is redirected to CAS login page, so their credentials are inserted and is generated a GRANT_SERVICE_TICKET from CAS. So after it, CAS sends a redirect link to Spring Boot application client including the token, but unexpectedly something happens and multiples redirects are sent to browser showing the message: "The page isn't redirecting properly".

CAS receives and generates the ticket, but Spring Boot can not confirm that ticket was accepted. As described in log bellow:
```
17:45:53,009 INFO  [stdout] (http--0.0.0.0-9022-1) =============================================================
17:45:53,009 INFO  [stdout] (http--0.0.0.0-9022-1) WHO: user123
17:45:53,009 INFO  [stdout] (http--0.0.0.0-9022-1) WHAT: ST-87-TCHz2sQeio0bR5gB2TZt-localhost for https://localhost:9043/useraccess/login/cas
17:45:53,009 INFO  [stdout] (http--0.0.0.0-9022-1) ACTION: SERVICE_TICKET_CREATED
17:45:53,009 INFO  [stdout] (http--0.0.0.0-9022-1) APPLICATION: CAS
17:45:53,024 INFO  [stdout] (http--0.0.0.0-9022-1) WHEN: Fri Jun 05 17:45:53 BRT 2015
17:45:53,024 INFO  [stdout] (http--0.0.0.0-9022-1) CLIENT IP ADDRESS: 127.0.0.1
17:45:53,024 INFO  [stdout] (http--0.0.0.0-9022-1) SERVER IP ADDRESS: 127.0.0.1
17:45:53,024 INFO  [stdout] (http--0.0.0.0-9022-1) =============================================================
```

My CAS server runs in JBoss 7.1 server at https://localhost:9022/cas
My Spring Boot runs at https://localhost:9043/useraccess/

Does anybody have any idea? It seems Spring Boot can not handle cross redirects between different servers. At the moment, my CAS authentication works in web applications, and I am trying to convert to Spring Boot one.

Thanks!

**Comment by ofbizbrazil** [comment]
Take a look at my current CAS configuration, as WAR application in JBoss 7.1 it works fine, but when is used in Spring Boot something does not work, it seems can not receive the ticket granted from CAS to redirect to application home.

'''
@Configuration
@EnableWebSecurity
public class CasConfig extends WebSecurityConfigurerAdapter {
   
    @Autowired
    private WebAppProperty webAppProperty; 
    
    @Override
    public void configure(final HttpSecurity http) throws Exception {
        // Main configurations
        http.csrf().disable();
        http.headers().frameOptions().disable();

        // Authorize sub-folders permissions
        http.authorizeRequests().antMatchers("/*").authenticated();

        http.addFilter(logoutFilter());
        http.addFilter(casAuthenticationFilter());

        final ServiceProperties serviceProperties = serviceProperties();
        http.authenticationProvider(casAuthenticationProvider(serviceProperties));
        http.exceptionHandling().authenticationEntryPoint(casProcessingFilterEntryPoint(serviceProperties));
    }

    private CasAuthenticationEntryPoint casProcessingFilterEntryPoint(final ServiceProperties serviceProperties)
            throws IOException {
        final String casLoginUrl = securityProperty().getCASLoginURL();
        final CasAuthenticationEntryPoint casAuthenticationEntryPoint = new CasAuthenticationEntryPoint();
        casAuthenticationEntryPoint.setLoginUrl(casLoginUrl);
        casAuthenticationEntryPoint.setServiceProperties(serviceProperties);

        return casAuthenticationEntryPoint;
    }

    private CasAuthenticationFilter casAuthenticationFilter() throws Exception {
        final String webappLocation = webAppProperty.getContextLocation();
        final SavedRequestAwareAuthenticationSuccessHandler savedRequestAwareAuthenticationSuccessHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        savedRequestAwareAuthenticationSuccessHandler.setDefaultTargetUrl(webappLocation);

        final String casLogoutUrl = securityProperty().getCASLogoutURL();
        final SimpleUrlAuthenticationFailureHandler simpleUrlAuthenticationFailureHandler = new SimpleUrlAuthenticationFailureHandler(
                casLogoutUrl);

        final CasAuthenticationFilter casAuthenticationFilter = new CasAuthenticationFilter();
        casAuthenticationFilter.setAuthenticationFailureHandler(simpleUrlAuthenticationFailureHandler);
        casAuthenticationFilter.setAuthenticationSuccessHandler(savedRequestAwareAuthenticationSuccessHandler);
        casAuthenticationFilter.setAuthenticationManager(super.authenticationManagerBean());

        return casAuthenticationFilter;
    }

    private LogoutFilter logoutFilter() throws IOException {
        final String logoutURL = securityProperty().getCASLogoutURL();
        final LogoutFilter logoutFilter = new LogoutFilter(logoutURL, new SecurityContextLogoutHandler());

        return logoutFilter;
    }

    private CasAuthenticationProvider casAuthenticationProvider(final ServiceProperties serviceProperties)
            throws IOException, NamingException {
        final String casServerLocationSSL = securityProperty().getCASServer();
        final Cas20ServiceTicketValidator ticketValidator = new Cas20ServiceTicketValidator(casServerLocationSSL);

        final CasAuthenticationProvider casAuthenticationProvider = new CasAuthenticationProvider();
        casAuthenticationProvider
                .setAuthenticationUserDetailsService(new UserDetailsByNameServiceWrapper<CasAssertionAuthenticationToken>(
                        userDetailsService()));
        casAuthenticationProvider.setServiceProperties(serviceProperties);
        casAuthenticationProvider.setTicketValidator(ticketValidator);
        casAuthenticationProvider.setKey("an_id_for_this_auth_provider_only");

        return casAuthenticationProvider;
    }

    private ServiceProperties serviceProperties() throws IOException {
        final String casServiceLocationSSL = securityProperty().getCASService();
        final ServiceProperties serviceProperties = new ServiceProperties();
        serviceProperties.setService(casServiceLocationSSL);

        return serviceProperties;
    }

    @Bean
    @Override
    public UserDetailsService userDetailsService() {
        return new CustomUserDetailsService();
    }

    @Bean
    public SecurityProperty securityProperty() {
        return new SecurityPropertyImpl();
    }
}
'''

**Comment by dsyer** [comment]
I suspect you have an error in your Spring Security configuration. Why not just compare it to something that works? If you want to ask someone here to debug it for you, I think it might be better if you can remove the CAS piece and boil it down to a simpler problem.

**Comment by ofbizbrazil** [comment]
After some tries I found the problem, it was related to CAS mapping errors and how I was trying to Spring Security 4.01 I need to change the filter security uri.
