### ISSUE TITLE
Spring Boot 2.7.0 version does not DI at complie time in Gradle

### ISSUE THREAD

**Issue by cwangg897** [spring-projects/spring-boot#31440]
It seems that Spring Boot 2.7.0 version does not inject empty injection in the properties file in Gradle at compile time,
 so it is underlined in red.

Spring Boot 2.5.0 version Images
![image](https://user-images.githubusercontent.com/79621675/174290301-307b74fd-db6f-4806-91a3-410d7e0fa5a4.png)
![image](https://user-images.githubusercontent.com/79621675/174290344-d6623b50-670a-4e09-9f04-846646f5710e.png)
![image](https://user-images.githubusercontent.com/79621675/174290369-63d2c407-d536-4cd2-9936-0b89e6c78a34.png)

Spring Boot 2.7.0 version images
![image](https://user-images.githubusercontent.com/79621675/174290558-a78974f9-5f56-43d9-be20-8f75f02ca076.png)
![image](https://user-images.githubusercontent.com/79621675/174290492-90e81cf0-bcd6-4225-8a71-4fc349275d5c.png)
application.properties same image

**Comment by snicoll** [comment]
@cwangg897 this has nothing to do with Spring Boot. Spring Boot 2.7 has moved to a new location for auto-configuration imports you need a new version of IntelliJ IDEA to support this.

See https://youtrack.jetbrains.com/issue/IDEA-289633/Spring-Boot-new-auto-configuration-registration-in-v-27
