### ISSUE TITLE
Spring-boot 1.2.3 no longer works with jersey 1.x

### ISSUE THREAD

**Issue by majinwala** [spring-projects/spring-boot#3144]
Hello,

I am trying to use spring boot 1.2.3 with jersey 1.x. It works with boot version 1.1.4.I am using FilteredRegistrationBean approach for integration which does not seem to work as before.

```java
@Bean
public FilterRegistrationBean jersey() {
	FilterRegistrationBean bean = new FilterRegistrationBean();
	bean.setFilter(new ServletContainer());
	bean.setMatchAfter(true);
	bean.addInitParameter("com.sun.jersey.config.property.packages",
				"com.sun.jersey;com.foo.resources");
	bean.setUrlPatterns(Collections
				.singletonList("/api/*"));
	return bean;
}
```

Default health, info endpoints works fine. But when I try jersey endpoints it give 404.

Any work around will be helpfull too.

**Comment by wilkinsona** [comment]
There's a [sample](https://github.com/spring-projects/spring-boot/tree/1.2.x/spring-boot-samples/spring-boot-sample-jersey1) that uses Jersey that uses a `FilterRegistrationBean`. It's tested as part of every CI build so, as far as I know, this should work. If you'd like us to investigate further, please provide a small sample that illustrates the problem.

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
