### ISSUE TITLE
spring-boot 2.7.0 MockMvc DI 

### ISSUE THREAD

**Issue by cwangg897** [spring-projects/spring-boot#31450]
MockMvc bean auto-injection does not work in Spring Boot 2.7.0. So NPE happens.

```java
@AutoConfigureMockMvc
@SpringBootTest
class UserServiceImplTest {

    @Autowired
    MockMvc mockMvc;

// id 'org.springframework.boot' version '2.7.0'
Unsatisfied dependency expressed through field 'mockMvc'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.test.web.servlet.MockMvc' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

**Comment by bclozel** [comment]
Can you provide a sample application that reproduces the problem? Ideally something we can git clone (or a zip file as an attachment here).
We do have tests checking for this case and we need more information to understand what's happening. Thanks!

**Comment by cwangg897** [comment]
> Can you provide a sample application that reproduces the problem? Ideally something we can git clone (or a zip file as an attachment here). We do have tests checking for this case and we need more information to understand what's happening. Thanks!

I set auto-injection dependency to id 'org.springframework.boot' version '2.7.0' as 
implementation group: 'org.springframework.boot', name: 'spring-boot-autoconfigure', version: '2.6.3' It seems to have been an error.
It's my fault. But it's not a Spring Boot problem.

![image](https://user-images.githubusercontent.com/79621675/174432205-5b8b2c55-fc38-4fd6-911d-4a50e4cd916d.png)
![image](https://user-images.githubusercontent.com/79621675/174432194-37b94a7a-dd19-4d05-b1c6-012f57252bfd.png)


In IntelliJ, in spring boot 2.7.0 version, there is only a problem that @Autowired is MockMvc or a red underline while writing the test code, and it is not a problem of Spring boot.

**Comment by bclozel** [comment]
OK, thanks for letting us know. I'm glad this is working now for you.
