### ISSUE TITLE
WebMvcMetricsFilter not created after upgrading to Spring Boot 2.7.0 when another user created bean of type FilterRegistrationBean is available 

### ISSUE THREAD

**Issue by dariosanna** [spring-projects/spring-boot#31451]
After upgrading from Spring Boot 2.6.8 to 2.7.0 WebMvcMetricsAutoConfiguration does not create a WebMvcMetricsFilter bean when a user created FilterRegistrationBean is available, regardless of what type of the filter bean.

In Spring Boot 2.7.0 the FilterRegistrationBean<WebMvcMetricsFilter> has ConditionalOnMissingBean , whereas Spring Boot 2.6.8 allways creates the bean: 

Spring Boot 2.7.0 WebMvcMetricsAutoConfiguration:

```
@ConditionalOnMissingBean
public FilterRegistrationBean<WebMvcMetricsFilter>
```

It seems that ConditionalOnMisstingBean ignores the type parameter T when evaluating the condition.

Is that a bug or how to make  @ConditionalOnMissingBean respects the type parameter T ?

Best regards.

**Comment by izeye** [comment]
This seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/31150.

**Comment by wilkinsona** [comment]
Indeed it is, @izeye. Thanks.

**Comment by dariosanna** [comment]
OK thank you
