### ISSUE TITLE
When using OTel, auto-configure CompositeSpanExporters with span exporting predicates, filters, and reporters

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31469]
Micrometer Tracing uses a `SpanExportingPredicate` to determine if a span should be exported and a `SpanFilter` to change the span (like a `MeterFilter`) before it is reported. Both are used in the bridges for brave and Otel (see `CompositeSpanExporter` and `CompositeSpanHandler`). We should auto-configure this in boot.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/32753 for the Brave side of things. This issue is now specific to Otel.

**Comment by wilkinsona** [comment]
This requires some changes in Micrometer Tracing. Pushing back to 3.1.x.

**Comment by scottfrederick** [comment]
Closing in favor of #34002
