### ISSUE TITLE
Add log correlation for Micrometer Tracing

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31468]
Sleuth adds the application name (or overridable name for tracing only), the trace id, and the span id to the logs, [see here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java). This uses the [SLF4J MDC feature](https://www.slf4j.org/manual.html#mdc).

* With brave, the trace id and the span id is put in there with help of the `brave.baggage.CorrelationScopeDecorator`.
* With Otel, this is done via [Slf4jApplicationListener](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel/src/main/java/org/springframework/cloud/sleuth/otel/bridge/Slf4jApplicationListener.java) and [EventPublishingContextWrapper](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel/src/main/java/org/springframework/cloud/sleuth/otel/bridge/EventPublishingContextWrapper.java).

We should support that in Spring Boot, too, as this is a very important feature when using tracing.

**Comment by wilkinsona** [comment]
Superseded by #32480.
