### ISSUE TITLE
Consider removing support for Querydsl project

### ISSUE THREAD

**Issue by mat-mik** [spring-projects/spring-boot#31478]
Querydsl project is not maintained anymore, issues are not solved and pull requests are not reviewed. As you can see from [contributions insight](https://github.com/querydsl/querydsl/graphs/contributors) main maintainer is not involved in project anymore. Current version (5.0.0) contains [connection leak](https://github.com/querydsl/querydsl/issues/3089) we experienced.

One of the reason we decided to use Querydsl for few years back was because of Spring support (like dependency version table).

**Comment by snicoll** [comment]
@mat-mik thanks for the suggestion but this is the wrong place to ask. Spring Boot itself does not use QueryDSL, you may want to suggest that to the Spring Data repository.
