### ISSUE TITLE
Using @SpringApplicationConfiguration annotation to injecting mocks into a Spring bean

### ISSUE THREAD

**Issue by eds0404** [spring-projects/spring-boot#3147]
There is the spring-boot application that uses spring-aop. proxy-target-class is true. I'm trying to create a test for a service class. This service depends on a component class. I want to inject a mock into the service instead of the real component.

I found some similar questions:
* http://stackoverflow.com/questions/9033874/mocking-a-property-of-a-cglib-proxied-service-not-working
* http://stackoverflow.com/questions/2457239/injecting-mockito-mocks-into-a-spring-bean

I choose this [answer] (http://stackoverflow.com/a/12038571/844275) to the last question, and I have tried to implement this approach. I chose it because it is not tied to the implementation details of the proxy classes and I can easily use a config class in other tests.

Below there is the example which simulates the real problem.

```Java
@org.aspectj.lang.annotation.Aspect
@org.springframework.stereotype.Component
public class Aspect {
    @Before("within(demo.Service)")
    public void someAdvice() {
        System.out.println("advice");
    }
}

@org.springframework.stereotype.Service
public class Service {
    @Autowired
    private Component component;

    public void action() {
        System.out.println(component.action());
    }
}

@org.springframework.stereotype.Component
public class Component {
    public String action() {
        return "real action";
    }
}

@SpringApplicationConfiguration
public class ServiceTest extends BaseTest {
    @Autowired
    Service service;

    @Test
    public void testAction() {
        service.action();
    }

    @Configuration
    public static class Config {
        @Mock Component mock;

        public Config() {
            MockitoAnnotations.initMocks(this);
        }

        @Bean
        public Component component() {
            Mockito.when(mock.action()).thenReturn("mock action");
            return mock;
        }
    }
}
```
Complete example: https://github.com/eds0404/spring-inject-mock-into-proxy
The above code is not working as I expect, the service does not use mock ("real action" will be printed if you run test). But the above code works fine if the Component class is not marked with @Component annotation, and its objects are created by the method with @Been annotation.

How to solve this issue? If this is wrong approach, what is best practice?

**Comment by snicoll** [comment]
I don't see anything wrong with your code and in fact it works for me. I have copy/pasted this in a real project (this is way better than putting code in a description) and it worked. The only noticeable difference is that my `SpringApplicationConfiguration` refers to the class where those beans are defined `@SpringApplicationConfiguration(classes = DemoApplication.class)`. 

If you want us to investigate this deeper (a stackoverflow thread would have been better here) you need to confirm the issue by providing a sample that actually fails. Thanks!

**Comment by eds0404** [comment]
@snicoll  There is not stackoverflow thread.  The problem is that the service does not use the mock ("real action" will be printed if you run test. I expected "mock action" to be printed).
> If you want us to investigate this deeper (a stackoverflow thread would have been better here) you need to confirm the issue by providing a sample that actually fails.
Is the example under attached link not sufficient? (https://github.com/eds0404/spring-inject-mock-into-proxy)

**Comment by snicoll** [comment]
I guess I just missed that link, sorry. (I was inviting you to create a SO thread rather than asking your question here but now we have a conversation history let's keep it here).

**Comment by snicoll** [comment]
Someone else reported the exact same issue and looking at [this blog post](http://blog.zenika.com/index.php?post/2013/01/15/spring-mvc-test-framework) it _used to work_ so it might be a regression of some sort.

**Comment by wilkinsona** [comment]
No one else seems to have hit this problem. Also, Spring Boo 1.4 introduces `@MockBean` for this usecase.
