### ISSUE TITLE
Add auto-configuration for JdkClientHttpConnector

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31479]
Spring Framework 6 introduces `JdkClientHttpConnector`, a `ClientHttpConnector` based on the JDK HttpClient. Would be nice if Spring Boot would support an auto-configuration for it. With this you could use the WebClient out of the box, without Netty, Apache HttpClient, etc.

**Comment by aooohan** [comment]
Hi @mhalbritter  , can this issue be assigned to me?

**Comment by mhalbritter** [comment]
Yup, go ahead.

**Comment by mhalbritter** [comment]
Closing in favor of the PR.
