### ISSUE TITLE
ActiveMQ is restarted every time the session is closed

### ISSUE THREAD

**Issue by mysoko** [spring-projects/spring-boot#3150]
Refer to spring-boot-samples examples, integrate spring-boot-sample-activemq and spring-boot-sample-data-jpa examples:
ActiveMQ continues to started and stopped
![image](https://cloud.githubusercontent.com/assets/75619/8027327/9bb42df2-0dc8-11e5-9e03-d62591ab1b56.png)

pom.xml
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jms</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>activemq-broker</artifactId>
        </dependency>

```

**Comment by snicoll** [comment]
I can also reproduce with ActiveMQ 5.10.1 - I really don't get what the `data-jpa` dependencies bring (the `activmq` sample works fine.

**Comment by snicoll** [comment]
ok that dependency brings a `PlatformTransactionManager` that is associated with listener container. In our case, this is a `JpaTransactionManager`. 

The change in `JmsAnnotationDrivenConfiguration` is wrong: we should only associate a `PlatformTransactionManager` if we're using XA. 

@philwebb ping
