### ISSUE TITLE
springboot 2.7.x 

### ISSUE THREAD

**Issue by lengcz** [spring-projects/spring-boot#31519]
![fcf9817d7b97e82589ced28aad3721b](https://user-images.githubusercontent.com/32121138/175460096-6ece781b-8b0d-41d2-863b-6467b4d07bf8.png)
![dd4649c39731649d57aaffec61a00ea](https://user-images.githubusercontent.com/32121138/175460113-e961120e-70ec-45d9-895b-c4502095fc8c.png)
The demo differs only in the Springboot version, but the resulting output is different.
Spring Boot 2.7.x has this error

**Comment by lengcz** [comment]
API:https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config

**Comment by wilkinsona** [comment]
This change is [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#springboottest-property-source-precendence).
