### ISSUE TITLE
Add support for baggage in tracing

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31522]
Sleuth supports three types of baggage:

* local baggage, which is available only in the same JVM
* remote baggage, which gets propagated via network to other services (e.g. via HTTP headers)
* correlated baggage, which can be local or remote baggage, too. This baggage gets automatically synchronized to MDC

Trace id and span id are a "special" kind of baggage, which is needed for span propagation to other services.

As of now, we don't have support for that feature in Spring Boot, and should add it.

**Comment by wilkinsona** [comment]
Superseded by #32480.
