### ISSUE TITLE
Add resource hints for schema and data scripts

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-boot#31533]
Schema & data files defined via properties are not added to the `resource-config.json` which causes application to error on first access.

```bash
java.lang.IllegalStateException: Failed to execute CommandLineRunner
    Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "xyz" not found (this database is empty);
```

```properties
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql
```
should translate to:
```json
[
    { "pattern": "\\Qdb\/h2\/schema.sql\\E" },
    { "pattern": "\\Qdb\/h2\/data.sql\\E" },
]
```

**Comment by sdeleuze** [comment]
In order to be consistent with the strategy followed by other resource hints, I think what should be add by default is resource hints for `schema.sql`, `schema-*.sql`, `data.sql` and `data-*.sql`.

**Comment by wilkinsona** [comment]
> in addition to the one specified in `spring.sql.init.schema-locations` and `spring.sql.init.data-locations`

I don't think this would be consistent. For example, `WebResourcesRuntimeHintsRegistrar` only registers the default static resource locations (https://github.com/spring-projects/spring-boot/issues/31278).

**Comment by sdeleuze** [comment]
Indeed, should we begin by just registering the defaults and evaluate later (other issue) if we provide a mechanism for providing hints for `spring.sql.init.schema-locations` and `spring.sql.init.data-locations` custom values?

**Comment by wilkinsona** [comment]
Yeah, I think that's a good way forward.
