### ISSUE TITLE
Allow Jackson's lazily created standard JDK serializers to be used in a native image

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31537]
Jackson's `com.fasterxml.jackson.databind.ser.std.StdJdkSerializers` adds a number of serializers as classes. These classes are then lazily instantiated via reflection in `BasicSerializerFactory.findSerializerByLookup`. This requires a reflection hint for the default constructor.

The serializers registered as classes are:

- `com.fasterxml.jackson.databind.ser.std.StdJdkSerializers.AtomicBooleanSerializer`
- `com.fasterxml.jackson.databind.ser.std.StdJdkSerializers.AtomicIntegerSerializer`
- `com.fasterxml.jackson.databind.ser.std.StdJdkSerializers.AtomicLongSerializer`
- `com.fasterxml.jackson.databind.ser.std.FileSerializer`
- `com.fasterxml.jackson.databind.ser.std.ClassSerializer`

**Comment by philwebb** [comment]
There's also `TokenBufferSerializer` registered with `BasicSerializerFactory`.
