### ISSUE TITLE
Apache ActiveMQ Artemis Support

### ISSUE THREAD

**Issue by sbuettner** [spring-projects/spring-boot#3154]
Since [HornetQ donated all of its code to the Apache ActiveMQ Project](http://hornetq.blogspot.de/2015/06/hornetq-apache-donation-and-apache.html). I just wanted to ask if support/migration is planned for the HornetQ starter subproject.

**Comment by snicoll** [comment]
It is now :)

**Comment by sbuettner** [comment]
Great, thanks for the quick reply.

**Comment by snicoll** [comment]
For the record @eddumelendez is working on this one (in case someone else here would want to pick that up). Thanks Eddú!

**Comment by eddumelendez** [comment]
Just a little difference with HornetQ, Artemis is able to auto-create and auto-delete queues. It is not apply for topics. Look at [ACTIVEMQ6-13](https://github.com/apache/activemq-artemis/commit/e293d80f08de58e4ce2bafd9d63c1a4185e079a9)
