### ISSUE TITLE
Remove Jolokia from documentation

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31545]
Commit 85f9949513806d564730c2ef6e27171d9563b5dd dropped support for Jolokia (because it [doesn't use JakartaEE APIs](https://github.com/rhuss/jolokia/issues/451)), but it is still mentioned in the documentation. Remove it.

**Comment by adrianbob** [comment]
Hi @mhalbritter,
I'm new to open source contributing and I would like to pick up this issue. Would that be ok?

**Comment by mhalbritter** [comment]
Hi @adrianbob, sure, go for it! Please [see our contributing documentation](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc).
