### ISSUE TITLE
activemq-camel may be removed

### ISSUE THREAD

**Issue by sourabhsparkala** [spring-projects/spring-boot#31548]
From this [PR](https://github.com/apache/activemq/pull/701)  

The dependency `org.apache.activemq:activemq-camel` component is already removed.

Does it make sense to migrate to `camel-activemq` as stated [here](https://github.com/apache/activemq/pull/701#issuecomment-909213019)?

**Comment by wilkinsona** [comment]
Our dependency management in 2.7 uses Active MQ 5.16 where `activemq-camel` still exists: https://repo.maven.apache.org/maven2/org/apache/activemq/activemq-camel/5.16.5/. As such, it doesn't make sense to remove it. Dependency management for ActiveMQ has been removed entirely in 3.0 so I don't think there's anything for us to do here.
