### ISSUE TITLE
Link to dependency upgrade release notes

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#31544]
As [discussed with @wilkinsona on Gitter.im](https://gitter.im/spring-projects/spring-boot?at=62ba0126ef5ee44882e7ab22).

Whenever a new release of Spring Boot comes out, I go through the release notes to find how any changes might affect me. These changes are often not limited to Spring Boot itself, but also include any changes to further dependencies managed through Spring Boot. These latter dependency upgrades are listed, but their respective release notes are not linked presently.
 
Let's take [the 2.7.1 release as an example](https://github.com/spring-projects/spring-boot/releases).
Among it's upgraded dependencies it lists:
"Upgrade to Spring Security 5.7.2 https://github.com/spring-projects/spring-boot/issues/31375".
When you follow the link you arrive at a bare issue.

It would be helpful to see a link to [Spring Security 5.7.2](https://github.com/spring-projects/spring-security/releases/tag/5.7.2).
Such a link could either be added to the upgrade issue, as an edit or reply,
or be linked directly from the release notes to save a click.

That way users have an easy way to navigate to further release notes, especially as this patch version contains 32 such upgraded dependencies, which ideally should be easy to discover.

**Comment by philwebb** [comment]
We're going to look at adding links to the issue. Hopefully, for most, we can do this with BOMR. For Spring projects we will need a manual process until BOMR can deal with early SNAPSHOT upgrades.

**Comment by wilkinsona** [comment]
WIP: https://github.com/wilkinsona/spring-boot/tree/gh-31544
