### ISSUE TITLE
Optimistic lock errors in DB tests with Spring Boot 2.7.1 because of newer h2 version 

### ISSUE THREAD

**Issue by de-jcup** [spring-projects/spring-boot#31546]
## Situation
In https://github.com/mercedes-benz/sechub/issues/915 we wanted to update to Spring Boot 2.7.x. 
But our DB unit tests did fail now.

So I started to analyze and found a problem with the h2 database usage inside tests.

### In a nutshell
When a test first stores an entity inside database, than load it again as an entity and does an update, we have an optimistic lock error

It does work with h2 version 1.4.200 but not with 2.x

### Examle
```java
        /* prepare */
        MyEntity entityA = new MyEntity();
        repositoryToTest.save(entityA);

        UUID uuid = entityA.getUUID();

        /* execute */
        MyEntity entityALoadedAndChanged = repositoryToTest.findById(uuid).get();
        entityALoadedAndChanged.justABooleanToHaveAnUpdate = true; 
        
        repositoryToTest.save(entityALoadedAndChanged); // not possible with h2 version >=2.x

        /* test */
        List<MyEntity> allTestData = repositoryToTest.findAll();
        assertEquals(1, allTestData.size());
```

## Analyze
I created a very simple test gradle project (see attached zip file) which has a Junit test inside which reproduces the Problem

When the gradle project is imported and the test is started, an optimistic lock exception will occur:
```
org.springframework.orm.ObjectOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update my_entity set enabled=?, version=? where uuid=? and version=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update my_entity set enabled=?, version=? where uuid=? and version=?
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:318)
	...
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update my_entity set enabled=?, version=? where uuid=? and version=?
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
	...
```
When inside the build.gradle file the h2 database is changed back to v1.4.200 (as used in Spring Boot 2.6.9) via 
```gradle
// when next line is added - the test will work, because we use h2 version < 2.x
ext['h2.version'] = '1.4.200'
```
then the test is green..

[h2-jpa-problem-demo-project.zip](https://github.com/spring-projects/spring-boot/files/9008725/h2-jpa-problem-demo-project.zip)

**Comment by wilkinsona** [comment]
Thanks for the analysis. As you have identified that the change in behaviour is due to changes in H2, this will have to be address in H2 itself or possibly in Hibernate's H2 support. There's nothing that we can do about it in Spring Boot (or, I suspect, in Data JPA either).

**Comment by de-jcup** [comment]
As a remark: 

In https://github.com/mercedes-benz/sechub/issues/915  we had also the additional problem with DB tests, that stored entities were no longer fetched by a custom query. 

I think the problem described in this issue and also the the additional problems with the not working query test, have as a root cause the new introduced h2 transaction handling. As far as I know, h2 did not have transaction handling in version 1 but with version 2.

IMO it should be possible inside tests to prepare data inside a database - e.g. for testing a service class which updates the entity inside the database without any additional, special test settings. Same for testing queries.

**Comment by de-jcup** [comment]
The H2 team helped me to find a workaround - read https://github.com/h2database/h2database/issues/3563#issuecomment-1169948389 for details.

The workaround used by myself now for the optimistic lock exception is, to add inside the Entity class for the PK not 
```
   @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = COLUMN_UUID, updatable = false, nullable = false)
    UUID uUID;
```
but additional define as column definition "UUID":
```
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = COLUMN_UUID, updatable = false, nullable = false, columnDefinition="UUID")
    UUID uUID;
```
With the mentioned changes the test does no longer fail with optimistic lock exception and works as expected.

It seems to be a bug in hibernate - I created https://hibernate.atlassian.net/browse/HHH-15373 to address the problem.
