### ISSUE TITLE
Add a configuration property for the trusted proxies of Tomcat's Remote IP valve

### ISSUE THREAD

**Issue by Trinition** [spring-projects/spring-boot#31542]
Tomcat's _RemoteIpValve_ supports both _internal proxies_ as well as _trusted proxies_.  _Internal proxies_ default to the private IP spaces, but _trusted proxies_ defaults to nothing.

_Internal proxies_ can be customized by setting _server.tomcat.remoteip.internal-proxies_ which is later honored by _TomcatWebServerFactoryCustomizer_, but _trusted proxies_ is not honored by it.

When using third party proxies with public IPs (e.g. Cloudflare Access), it is desirable to include their IPs to be ignored by the _RemoteIpValve_.  To do this through configuration, the only option is to _replace_ the _internal proxies_ pattern list since the _trusted proxies_ list is not exposed to be configurable.

My suggestion is to also expose _trusted proxies_ for configuration.

**Comment by wilkinsona** [comment]
Until we've added a property for this, you can customize the auto-configured valve with the following customizer:

```java
@Bean
WebServerFactoryCustomizer<TomcatServletWebServerFactory> trustedProxiesCustomizer() {
    return (factory) -> {
        for (Valve valve : factory.getEngineValves()) {
            if (valve instanceof RemoteIpValve) {
                ((RemoteIpValve) valve).setTrustedProxies("example");
            }
        }
    };
}
```

You could externalize its configuration with something like this:

```java
@Bean
WebServerFactoryCustomizer<TomcatServletWebServerFactory> trustedProxiesCustomizer(
        @Value("${example.tomcat.remoteip.trusted-proxies}") String trustedProxies) {
    return (factory) -> {
        for (Valve valve : factory.getEngineValves()) {
            if (valve instanceof RemoteIpValve) {
                ((RemoteIpValve) valve).setTrustedProxies(trustedProxies);
            }
        }
    };
}
```

**Comment by aooohan** [comment]
@wilkinsona hi, Andy. Does this issue need to be achieved? f it need to be implemented, can I be assigned? I would be happy to provide PR.

**Comment by wilkinsona** [comment]
Thanks very much for the offer, @aooohan. I've assigned the issue to you. Please let us know if you have any questions.

**Comment by aooohan** [comment]
> Thanks very much for the offer, @aooohan. I've assigned the issue to you. Please let us know if you have any questions.

I have completed my PR, please review it for me, thanks.

**Comment by wilkinsona** [comment]
Thanks very much, @aooohan. Closing in favor of #31576.
