### ISSUE TITLE
Pagination bug of the spring.io blog for releases announcements

### ISSUE THREAD

**Issue by hbrls** [spring-projects/spring-boot#31553]
I'm reading through the spring-boot releases.

There is a link on top of the page which goes to `https://spring.io/blog/category/releases`. It only shows the category of release. But the pagination on the bottom links back to `https://spring.io/blog?page=9` which is the normal pagination.

The correct page is `https://spring.io/blog/category/releases?page=9`. And type-in the url directly works.

Would you please fix the pagination for `category`.

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-io/sagan/issues/1070
