### ISSUE TITLE
Refactor PublishingCustomizer(GodClass)

### ISSUE THREAD

**Issue by MatheusPK** [spring-projects/spring-boot#31573]
My team used PMD Software on this project for our college project and we found some interesting refactoring points. One of them is the presence of a God Class. The class in the ocasion has multiple responsibilitys(whats infringe the S - Single Responsibility rule of SOLID principles) that can be shifted to another class and be reused in other contexs in the project.

The God Class is  "PublishingCustomizer " and our refactoring suggestion is moving this node methods to another class called NodeUtils

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I disagree with PMD here. `PublishingCustomizer` as a single responsibility which is to customize the `MavenPublication`, altering the contents of its pom. At under 300 lines of code I think it's size if pretty manageable.
