### ISSUE TITLE
Configure interface-based proxies in native images

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#31659]
Now that spring-projects/spring-framework#28717 is fixed, every Spring Boot application using Spring AOP requires to configure `spring.aop.proxy-target-class=false` in order to get it working on native since spring-projects/spring-framework#28115 is not going to be fixed in time for [Spring Boot 3.0.0-M4](https://github.com/spring-projects/spring-boot/milestone/244).

If not set, the following fatal error is thrown at startup (on purpose): `org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'runner': Subclass-based proxies are not support yet in native images`.

In order to allow a reasonable developer experience, could Spring Boot 3 automatically configure `spring.aop.proxy-target-class=false` when `NativeDetector#inNativeImage` returns `true`?

**Comment by wilkinsona** [comment]
I wonder if we should use `AotDetector#useGeneratedArtifacts` rather than `NativeDetector#inNativeImage`? Doing so would reduce the chances of things working on the JVM with AOT and then failing in the native image.

**Comment by sdeleuze** [comment]
Yeah that's another option if we consider JVM + AOT mainly from the perspective of testing native behavior on the JVM.

**Comment by philwebb** [comment]
If we do change this setting for M4 we should open another issue to revert it in M5 or whenever cglib is supported. I think it's best long-term to keep JVM and Native aligned as much as possible.

**Comment by snicoll** [comment]
FWIW I am not sure we should be doing this. Yes, the exception is very strange and hard to diagnose but working around that by changing the default with AOT sounds a bit odd to me. 

I'd rather add something to the release notes.

**Comment by mhalbritter** [comment]
Let's discuss this in the team meeting.
