### ISSUE TITLE
init.d boot/loader/tools/launch.script inclusion broken sometime after June 3

### ISSUE THREAD

**Issue by bedge** [spring-projects/spring-boot#3166]
This was working perfectly but broke recently sometime after June 3.

I tried some of the older SNAPSHOT builds from here:
http://repo.spring.io/libs-snapshot-local/org/springframework/boot/spring-boot/1.3.0.BUILD-SNAPSHOT/spring-boot-1.3.0.BUILD-20150609.143456-213.jar
but all the currently available SNAPSHOTS are broken too.
From 1.3.0.BUILD-20150605.174051-204 to 1.3.0.BUILD-20150609.143456-213 have this problem.

I can confirm that my June 3 build did have the launch.script at the start of the war whereas builds today do not.

Current war head:
```
%> head /opt/nim/cmas/nim-cmas.war
�m      META-INF/��mMETA-INF/MANIFEST.MFU
@ w2T�B�B�Y�5��$&�o\�1��.���+����5Q�
��w��_.Z�!k��;��#��C�-:3~1�y�W����P=����WEB-INF/�mK
                                                   WEB-INF/lib/PPK
~:WEB-INF/lib/spring-boot-starter-actuator-1.2.3.RELEASE.jarPK
״~F     META-INF/ִ~FMETA-INF/MANIFEST.MF��AK��-Z"9D,#^e�;i�&�a2I�+*
��>KT-ueg3���-Ա�2]A�>�?{iݳ[(bȭ�(��d!>��*˼.�i�V�����D�o%-l���/ťn�y��׻e�Ɡo��l��
'
�Й�=-p�9۝����D%P���Xִ~FMETA-INF/spring.provides+(I-�R(.(K/L.)M,P'"# PK
״~FMETA-INF/maven/PK
״~F(META-INF/maven/org.springframework.boot/PK
```
Here's the old war from pre June 3:
```
#> head ~/old/nim-cmas.war
#!/bin/bash
#
#    .   ____          _            __ _ _
#   /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
#  ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
#   \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
#    '  |____| .__|_| |_|_| |_\__, | / / / /
#   =========|_|==============|___/=/_/_/_/
#   :: Spring Boot Startup Script ::
#
```

**Comment by philwebb** [comment]
We recently flipped the default to disabled since we found the special jars didn't work with all tools (including our own Cloud Foundry!). See #3045 for background. Can you try tweaking your Gradle/Maven config and see if that fixes it.

**Comment by philwebb** [comment]
The documentation was also updated (see http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_unix_linux_services)

**Comment by bedge** [comment]
Confirmed working with new gradle incantation:
```
springBoot {
    executable = true
}
```
thanks!
