### ISSUE TITLE
When using Jetty, setting the MVC Servlet path changes the static file directory.

### ISSUE THREAD

**Issue by endooo** [spring-projects/spring-boot#31677]
When using Jetty, setting the MVC Servlet path changes the static file directory.
This change is present in version 2.6.x but not in version 2.5.x.
It is also different when using Tomcat, so I think this specification is wrong, is it correct?

- environment
spring-boot-starter-web
2.6.9
jetty-servlets
9.4.48.v20220622

```application.yaml
spring.mvc.servlet.path=/demo2
```
```static file directory
src/resources/static/demo2
```

- sample application
https://github.com/endooo/spring-boot-jetty-sample

**Comment by wilkinsona** [comment]
This is the expected behaviour. Static resources in `src/main/resources/static` are served using Spring MVC's resource handling. The entry point to this resource handling is Spring MVC's dispatcher servlet. `spring.mvc.servlet.path` configures the path to which the dispatcher servlet is mapped.
