### ISSUE TITLE
Enable GraalVM reachability metadata repository

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#31687]
With https://github.com/oracle/graalvm-reachability-metadata now public and [native-build-tools 0.9.13](https://github.com/graalvm/native-build-tools/releases/tag/0.9.13) just released, it would be great if Spring Boot 3 could upgrade to this NBT version and enable automatically the flag that allows to download third party native configurations for both Maven and Gradle plugins. This is currently the main blocker for making Spring native support usable in practice.

Notice this flag may be enabled by default later but that will probably have to wait NBT 1.0.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/31688 for the version upgrade.
