### ISSUE TITLE
Parameter to disable auto-load of Spring servlet "DispatcherServlet"

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3169]
I noticed there's no way to disable the default loading of Spring servlet "DispatcherServlet" created by Spring Boot when you're using a web application (Tomcat / Undertow). 

For example, if you have a Vaadin application you will use "SpringVaadinServlet" to manage all your injections in Spring context, so there's no need to have a "DispatcherServlet" running and consuming resources , keeping in mind my application will not use Spring MVC or something else in this time.

In fact, having a property to enable / disable the default Spring servlet should be nice and a good option to optimize the application when this is really needed.

**Comment by philwebb** [comment]
See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-switch-off-the-spring-mvc-dispatcherservlet

It might be worth asking questions on stackoverflow.com to see if other people can help before opening an issue.

Cheers.

**Comment by ofbizbrazil** [comment]
@philwebb 

I read it, but if I try to disable "DispatcherServlet" as code below shoes it does not work, the servlet mapping stil exists.

```
    @Bean
    public ServletRegistrationBean servletRegistrationBean(final DispatcherServlet dispatcherServlet) {
        final ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(dispatcherServlet);
        servletRegistrationBean.setEnabled(false);

        return servletRegistrationBean;
    }
```

LOG
```
2015-06-10 09:34:39.191  INFO 6816 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Servlet dispatcherServlet was not registered (disabled)
2015-06-10 09:34:39.191  INFO 6816 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
```
