### ISSUE TITLE
spring-boot-starter-parent `2.7.1` missing from maven central

### ISSUE THREAD

**Issue by krisiye** [spring-projects/spring-boot#31698]
https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-parent  missing `2.7.1`

They do exist here: https://repo.spring.io/ui/native/release/. Any reason why this artifact was not published to maven central? I see other artifacts for `2.7.1`  except `spring-boot-starter-parent`

**Comment by scottfrederick** [comment]
The artifact was published to Maven Central here: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.7.1/. `repo1.maven.org` is the location the Spring team publishes to, and the location from which artifacts are resolved for building. `search.maven.org` is a search index that we have no control over.

**Comment by krisiye** [comment]
Thanks for verifying! closing this as this is not a bug.
