### ISSUE TITLE
Provide a resorce manager for many Spring Boot applications

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3170]
I have opened this post to share a feeling about something missing in Spring Boot like a JNDI server managing all my resources, in fact not just for the current application as many of us talked in "creating JNDI for Tomcat".

This way, all Spring Boot applications could connect easily to this Spring Boot Central Manager and get for example a common DataSource managed by a administrator who knows passwords, IP, DNS (security stuff).

Cause even externalizing the properties to hold all the external details about the datasource, it's not so transparent for the applications such as having a resource in JNDI tree.
Please take a look at org.apache.naming.java.javaURLContextFactory

Let me know your thoughts! Cheers.

**Comment by spencergibb** [comment]
Kind of sounds like https://github.com/spring-cloud/spring-cloud-config

**Comment by philwebb** [comment]
It's not something that I think we want to tackle in Spring Boot itself since we don't want to make the core too complex. Have you seen the [Spring Cloud](http://projects.spring.io/spring-cloud/)? They have a configuration server that sounds quite similar to what you are asking.

**Comment by ofbizbrazil** [comment]
@philwebb 

I tried Spring Cloud Netlix, but I didn't find anything related to how define datasources on something like JNDI server. 

I saw how to create and register REST services on the Bus, which uses HTTP protocol and JSON, as you know Datasources uses jdbc protocol.

Do you have any info about it?

**Comment by spencergibb** [comment]
You would use Spring Cloud Config (not netflix).  It would allow you to define, for example, different [data sources](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html) per environment in a distributed, managed way.

**Comment by ofbizbrazil** [comment]
The problem with Spring Cloud Config is that I would need a Git-hub project, and all my projects are placed in CVS. Is there any solution without migrating from CVS server to use Spring Cloud?

**Comment by spencergibb** [comment]
@ofbizbrazil you don't need github, just git.  You can also use a filesystem or svn. I'm sorry you still need to use CVS ;-)  If there is a java api for CVS, you can build integration for CVS.
