### ISSUE TITLE
Exclude devtools jar

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3171]
We need to document or create a way to exclude devtools jar from production apps.

**Comment by wilkinsona** [comment]
Could we work on the assumption that people won't want to use the devtools with packaged jars? If so, we could update the repackager to exclude it

**Comment by prasenjit-net** [comment]
As a user i will expect that on maven production profile this jar should be excluded. So i can do this even now without issue. But excluding it from repackage means it would exclude for dev build too. What do u think @wilkinsona . We want to use remote debug in DIT environment.

**Comment by wilkinsona** [comment]
@prasenjit-net I think that means my assumption is invalid and we'll need to come up with something else.

**Comment by prasenjit-net** [comment]
@wilkinsona i think only documentation is enough showing that it cat be easily excluded during build with the help of build profile(maven profile). Of cource its my opinion.

**Comment by dsyer** [comment]
I think it should be a documented best practice to exclude it (e.g. we should do it in start.spring.io). The only fly in the ointment is Cloud Foundry (and other PaaS) where you might want it at dev time. We probably need to work with the tools teams (STS and CF buildpack) to come up with a story that works there.

**Comment by snicoll** [comment]
@philwebb @wilkinsona I have pushed a proposal on my fork. It works but it has a few quirks:

* I couldn't find a way to have a Maven integration test due to the devtools dependency
* The Gradle plugin is not aligned as far as exclusion goes so I have a lousy attempt at introducing filtering that must be polished.

Can you guys have a look? Thanks!
