### ISSUE TITLE
Change phases of WebServer start-stop and graceful shutdown lifecycles to allow other smart lifecycles to run before graceful shutdown

### ISSUE THREAD

**Issue by jGleitz** [spring-projects/spring-boot#31714]
Use case: We would like to add some logic that runs on shutdown, but _before_ the web server is shut down. To do so, we want to implement a `SmartLifecycle` with a phase that’s higher than [`WebServerGracefulShutdownLifecycle`](https://github.com/spring-projects/spring-boot/blob/v3.0.0-M3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/context/WebServerGracefulShutdownLifecycle.java)’s.

Our concrete use case is that we want to have the application wait some time before actually shutting down, as in #20995. However, the proposed solution in #20995 relies on hanging the thread that sends out the context closed event. We think that using the `SmartLifecycle` interface is more appropriate. However, since [`WebServerGracefulShutdownLifecycle`](https://github.com/spring-projects/spring-boot/blob/v3.0.0-M3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/context/WebServerGracefulShutdownLifecycle.java)’s phase [is hard-coded to `Integer.MAX_VALUE`](https://github.com/spring-projects/spring-boot/blob/v3.0.0-M3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/context/WebServerGracefulShutdownLifecycle.java#L34), we can’t do that.

Proposal: Add a property `server.shutdown-phase` to configure the `SmartLifecycle` phase of all [`WebServerGracefulShutdownLifecycle`](https://github.com/spring-projects/spring-boot/blob/v3.0.0-M3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/context/WebServerGracefulShutdownLifecycle.java)s. Default the value to `Integer.MAX_VALUE`.

Alternative: Set the hard-coded phase of [`WebServerGracefulShutdownLifecycle`](https://github.com/spring-projects/spring-boot/blob/v3.0.0-M3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/context/WebServerGracefulShutdownLifecycle.java) to something lower than `Integer.MAX_VALUE` to allow using a higher phase. This is slightly less work, but is not strictly backwards-compatible, as it may influence the order in relation to other `SmartLifecycle`s.

We would be happy to provide a pull request if one of the proposals is accepted.

**Comment by wilkinsona** [comment]
We discussed this today and we'd prefer not to make the phase externally configurable as the phases of `WebServerGracefulShutdownLifecycle` and `WebServerStartStopLifecycle` need to be configured correctly in relation to each other. Instead, we'd prefer to change the defaults. Rather than using `MAX_VALUE` and `MAX_VALUE - 1`, we think it would be better to use something like `MAX_VALUE - 5` and `MAX_VALUE - 10`.

**Comment by jGleitz** [comment]
Hi, and thank you for considering this.

Some feedback: if this is implemented by changing the hard-coded values, I’d suggest giving more headroom than just `5`. In my experience, a lot of Lifecycles are configured to run one after the other, which can quickly fill up just `5` slots. I’d suggest something like `MAX-VALUE - 32`, or even less.
