### ISSUE TITLE
Register JSR-310 converters for JPA by default if Spring Data JPA is present and Java 8 is used

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#3175]
As of the Fowler release train, Spring Data JPA supports the usage of non-time-zoned JSR-310 types in domain classes by providing the necessary JPA 2.1 converters. To activate them, the wrapper class containing the converters needs to be [registered alongside the entities](https://spring.io/blog/2015/03/26/what-s-new-in-spring-data-fowler#jsr-310-and-threeten-backport-support).

It would be cool if this was automatically done if Spring Data JPA is on the classpath and Java 8 is used.

**Comment by holgerstolzenberg** [comment]
+1 for this one

**Comment by olivergierke** [comment]
This seems to duplicate #2721 which was just rejected. So probably suspect for rejection, too. /cc @philwebb

**Comment by snicoll** [comment]
Indeed, duplicates #2721
