### ISSUE TITLE
upgrade FlywayAutoConfiguration to Flyway 9.0.0

### ISSUE THREAD

**Issue by vwiencek** [spring-projects/spring-boot#31756]
`FlywayAutoConfiguration ` needs to be updated to ensure compliance with Flyway 9.0.0.

Specifically:
- method `ignoreIgnoredMigrations` has been removed from `FluentConfiguration`
- method `baselineMigrationPrefix` has been removed from `FluentConfiguration`
- `SQLServerConfigurationExtension` has been moved to package   `org.flywaydb.flyway-sqlserver`

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/pull/31723.
