### ISSUE TITLE
Set GlobalObservationConvention on ObservationConfig

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#31778]
If there are any beans of type `GlobalObservationConvention` they should be set on the `ObservationRegistry#observationConfig`

**Comment by adrianbob** [comment]
Hi @marcingrzejszczak, @mhalbritter,
Could I pick up this issue? If yes, could you provide a bit more about how to tackle it?

**Comment by wilkinsona** [comment]
Thanks for the offer, @adrianbob. I think this issue might be a bit stale as `KeyValuesProvider` has been [removed](https://github.com/micrometer-metrics/micrometer/commit/d510282b009e095bbff3950cb9f80358f75caf2f) from Micrometer. We'll need to sync up with @marcingrzejszczak who's out of the office at the moment and also wait till we're ready to move to Micrometer snapshots to pick up their latest changes.

**Comment by marcingrzejszczak** [comment]
Yeah, I'm back. So the only "global" thing you can set on the `ObservationConfig` currently is `Observation.GlobalObservationConvention`. We've removed the `KeyValuesProvider` - it got merged into `ObservationConvention`.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/pull/32048 has taken care of this.
