### ISSUE TITLE
Add ElasticSearch HealthIndicator for JestClients (using ES REST API)

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#3178]
As mentioned in [this PR comment](https://github.com/spring-projects/spring-boot/pull/2399#issuecomment-110644160), the current `HealthIndicator` arrangements for ElasticSearch aren't supporting all deployments.

Could we provide here a `HealthIndicator` that:
* is using a JestClient instead of a native ElasticSearch client?
* is using the Stats index API (or another one), since the cluster API may not be allowed in shared environments

**Comment by ptahchiev** [comment]
+1 for this
