### ISSUE TITLE
GET endpoint handles spanish characters in headers by default, but POST endpoint doesn't recognize them

### ISSUE THREAD

**Issue by luckypier** [spring-projects/spring-boot#31797]
### Current Behavior
POST and GET endpoint work with different encoding characters for HTTP headers.

While sending a header with Spanish word "muñoz" to a GET controller, it works as expected.
But when sending the same header to a POST controller, the character encoding fails binding the String as "muÃ±oz".

### Expected Behavior
For me both cases (GET and POST) should use the same character encoding

### Minimal yet complete reproducer code(or URL to code)
https://github.com/egosumcarlos/demo-spring-headers-specials-chars-in-post/blob/master/src/main/java/com/example/demo/DemoController.java

Hit the controllers with:

```js
curl --location --request GET 'http://localhost:8080/dummy' --header 'cust-full-name: muñoz'

curl --location --request POST 'http://localhost:8080/dummy' \
--header 'cust-full-name: muñoz' \
--header 'Content-Type: application/json' \
--data-raw '{
  "dni":"321"
}'
```

![http-header-special-characters-2](https://user-images.githubusercontent.com/11932610/179867285-853e0bbf-893e-4b8b-9a2f-c8986be2cc8c.png)

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it doesn't appear to reproduce the behavior that you have described with both `GET` and `POST` receiving the header as `muÃ±oz`:

```
2022-07-20 11:16:03.021  INFO 27131 --- [ctor-http-nio-2] com.example.demo.DemoController          : header from GET muÃ±oz
2022-07-20 11:16:30.507  INFO 27131 --- [ctor-http-nio-3] com.example.demo.DemoController          : dto 321
2022-07-20 11:16:30.507  INFO 27131 --- [ctor-http-nio-3] com.example.demo.DemoController          : header from POST muÃ±oz
```

This is the behaviour that I would expect as [only US-ASCII is permitted in HTTP headers](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.6).
