### ISSUE TITLE
Update Static Content reference documentation to reflect the DefaultServlet no longer being enabled by default

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31792]
https://docs.spring.io/spring-boot/docs/2.6.9/reference/html/web.html#web.servlet.spring-mvc.static-content

This paragraph is no longer accurate:

> In a stand-alone web application, the default servlet from the container is also enabled and acts as a fallback, serving content from the root of the ServletContext if Spring decides not to handle it. Most of the time, this does not happen (unless you modify the default MVC configuration), because Spring can always handle requests through the DispatcherServlet.

**Comment by ionascustefanciprian** [comment]
Hi @wilkinsona I am a new to open source contribution and I would like to help with this issue. Can you assign it to me?

**Comment by wilkinsona** [comment]
Thanks very much, @ionascustefanciprian. It's all yours.

**Comment by wilkinsona** [comment]
How's it going, @ionascustefanciprian?

**Comment by ionascustefanciprian** [comment]
Hi. Sorry I have been busy, Next Monday I will focus to open the PR

**Comment by ionascustefanciprian** [comment]
Hello @wilkinsona I have opened a new PR #32004

**Comment by wilkinsona** [comment]
Thanks very much, @ionascustefanciprian. I'll close this issue in favor of your PR.
