### ISSUE TITLE
springboot cli init - add extra custom parameters for target sprint Initialzr server

### ISSUE THREAD

**Issue by jkone27** [spring-projects/spring-boot#31791]
would be nice to be able to do 

```
spring init --target=https://some.custom.initializer.service.com/ -x -d=dep1,dep2,dep3.... --custom-args="a=1,b=2" my-new-project
```

and then have spring cli init send them to the target in Http 
either in Headers or in the payload
```
Request.Headers.X-CustomArgs "a=1,b=2"
```

**Comment by philwebb** [comment]
Thanks for the suggestion but we're trying to keep changes to the CLI to a minimum. For your specific use-case I wonder if a [CLI extension](https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html#cli.using-the-cli.extensions) might work. You could copy the code from [InitCommand](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-cli/src/main/java/org/springframework/boot/cli/command/init/InitCommand.java) and add additional custom options.
