### ISSUE TITLE
There seems to be a section of wrong logic in org.springframework.boot.loader.jar.Handler#captureJarContextUrl

### ISSUE THREAD

**Issue by aoyvx** [spring-projects/spring-boot#31838]
Looking at the following code, handlers will never be null. 
https://github.com/spring-projects/spring-boot/blob/47516b50c39bd6ea924a1f6720ce6d4a71088651/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/Handler.java#L414-L440

Therefore, whether the branch handlers==null can be deleted.

**Comment by aoyvx** [comment]
If this behavior does not meet expectations, please assign the issue to me.

**Comment by philwebb** [comment]
Good spot @aoyvx, I think we should be calling `String handlers = System.getProperty(PROTOCOL_HANDLER);` without the default value. I'll assign the issue to you. Thanks!

**Comment by philwebb** [comment]
Closing in favor of PR #31870. Thanks @aoyvx!

**Comment by aoyvx** [comment]
@philwebb Excuse me, I want to know how to appear on the contributors.I submitted PR to spring framework and spring boot, but I didn't join the contributors. thanks.

**Comment by snicoll** [comment]
@aoyvx you are a contributor, look at the badge next to your comment.

**Comment by aoyvx** [comment]
@snicoll Thanks, it's cool. 😀
