### ISSUE TITLE
Security raise StackOverflowError using authenticationManagerBuilder when user have wrong credentials

### ISSUE THREAD

**Issue by darkman97i** [spring-projects/spring-boot#31836]
# Description
* Spring boot version: 2.7.1
* JDK version: 1.11

I'm moving from old authentication style to the new authentication style based on the article published in the blog [spring-security-without-the-websecurityconfigureradapter ](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) -> before adding the issue I have looking in stackoverflow for similar issue, here in closed issues, dead loops etc... but I have not been able to find anything in the same direction.

Everythings goes fine, except when I introduce bad credentials, then the application seems go into a loop until it is raised an java.lang.StackOverflowError: null ( here the full error stack trace )
[error.txt](https://github.com/spring-projects/spring-boot/files/9160916/error.txt)

I have created a sample code at https://github.com/darkman97i/spring-security-test ( in the sample I'm using two providers in memory and jdbc. Also I included h2 database with users credentials into for a quick test ). 

Thanks for your time

**Comment by wilkinsona** [comment]
Your use of the shared authentication manager builder results in a provider manager that is using itself as a parent. This results in an infinite loop as when the login fails, the provider manager queries its parent to see if it can authenticate.

This problem isn't directly related to Spring Boot as it's a Spring Security usage question. Your sample works if I inject an `ObjectPostProcessor` and create a new `AuthenticationManagerBuilder`:

```java
@Bean
	public AuthenticationManager authenticationManager(HttpSecurity http, ObjectPostProcessor<Object> objectPostProcessor) throws Exception {
		
		AuthenticationManagerBuilder authenticationManagerBuilder = new AuthenticationManagerBuilder(objectPostProcessor);
```

However, I'm not sure if this is the best way to solve the problem. Unfortunately, there are no hits on `AuthenticationManagerBuilder` in the Spring Security reference documentation so it doesn't appear to offer any guidance.

Can you please open a Spring Security issue that references this issue, and comment here with a link to it? That will bring to problem to the Security team's attention. They could perhaps prohibit a cycle among the `ProviderManager` ancestors, make some updates to the documentation, or something else that the feel is more appropriate.
