### ISSUE TITLE
Remove any references to KeyValuesProviders and replace them with Observation.Conventions

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#31841]
related PR: https://github.com/micrometer-metrics/micrometer/pull/3306

**Comment by adrianbob** [comment]
Hey @marcingrzejszczak,
Can I take this issue?

**Comment by wilkinsona** [comment]
Thanks for the offer @adrianbob, but we can't work on this yet as we're not ready to move to Micrometer snapshots.

**Comment by wilkinsona** [comment]
We no longer have any such references.

**Comment by wilkinsona** [comment]
Actually, we have a test name and a configuration class that are still referring to key values providers despite now dealing with observation conventions.
