### ISSUE TITLE
`@DataJdbcTest` requires Spring Data JDBC

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#31850]
`@DataJdbcTest` currently strictly depends on Spring Data JDBC via the `DataJdbcTypeExcludeFilter` that refers to SD JDBC's `AbstractJdbcConfiguration`. While the `@Data…Test` annotations suggest an inclusion of the Spring Data projects, with Spring Frameworks extensive JDBC support, it would be nice if that reference to Data JDBC was optional.

**Comment by snicoll** [comment]
That's what `@JdbcTest` is for. Have I missed something?

**Comment by odrotbohm** [comment]
Doh, I wasn't aware of this one 😳. It seems to behave slightly different than `@DataJdbcTest` in terms of what beans are autoconfigured (I get a `JdbcTemplate` for the latter but not with `@JdbcTest`) but I guess that needs a different level of investigation. Feel free to close this one here.

**Comment by snicoll** [comment]
`@AutoConfigureJdbc` [imports `JdbcTemplateAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/68fc87bc7fa74f5df34b814ebc157a65e263ca13/spring-boot-project/spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureJdbc.imports#L5) so you should get one as long as `spring-jdbc` is on the classpath. If that's not working, please share a small sample that reproduces the problem and we can reconsider.
