### ISSUE TITLE
Empty error body from Controller

### ISSUE THREAD

**Issue by BlxckMass** [spring-projects/spring-boot#31859]
Hello everyone, I ran into one problem, namely, the standard error body in the controller
There was a version of Spring Boot 2.2, when there was an error, a body of this kind was returned - 
![image](https://user-images.githubusercontent.com/56173782/180794468-1d3fe0be-6989-42c2-b587-bbfd5a3c2a86.png)
After updating to 2.6.1 - the error body is empty, what do I need to do to get the standard error body?

**Comment by snicoll** [comment]
This is covered in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#messages-in-the-default-error-view). When upgrading to an older version like this, it is recommended to upgrade one feature release at a time and review the releases notes for each. 

Going forward, please ask questions on StackOverflow,  as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
