### ISSUE TITLE
@Conditionalonproperty value does not support uppercase letters

### ISSUE THREAD

**Issue by copbint** [spring-projects/spring-boot#31867]
# case 1: condition is not matched
```java
@ConditionalOnProperty("test.trustStore")
@AutoConfiguration
public class MyAutoConfiguration {
}
```
application.yaml
```yaml
test:
  trust-store: classpath:ssl/truststore.jks
```

# case 2:  condition is matched
```java
@ConditionalOnProperty("test.trust-store")
@AutoConfiguration
public class MyAutoConfiguration {
}
```
application.yaml
```yaml
test:
  trustStore: classpath:ssl/truststore.jks
```
# reason
After debug the source code, I found the reason: 
[org.springframework.boot.context.properties.source.ConfigurationPropertyName.ElementsParser#isAlpha](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/source/ConfigurationPropertyName.java#L1020)
```java
		private static boolean isAlpha(char ch) {
			return ch >= 'a' && ch <= 'z';
		}
```

Can we change it to support uppercase letters？If so, I'd like to submmit a PR.

**Comment by wilkinsona** [comment]
This is intentional. Please see the javadoc for `name` attribute:

> Use the dashed notation to specify each property, that is all lower case with a "-" to separate words (e.g. `my-long-property`).

Using this canonical format in the annotation ensures that it can match against a variety of different input formats.
