### ISSUE TITLE
Dependency management for REST Assured is incomplete

### ISSUE THREAD

**Issue by Rossojo** [spring-projects/spring-boot#31864]
For our integration-tests with REST Assured we use the [kotlin-extension-module](https://github.com/rest-assured/rest-assured/wiki/Usage#kotlin-extension-module) of REST Assured. To use the module an additional Gradle dependency is required:   `testImplementation("io.rest-assured:kotlin-extensions:4.5.1")`. Currently we need to lookup the REST Assured version used in the Spring BOM after every Spring Update to keep the module version in sync.

To avoid the manual lookup, is it possible to add the kotlin-extension-module dependency to the Spring BOM?

**Comment by wilkinsona** [comment]
We'll have to list the modules in 2.6.x. When merging forwards there's a bom that we can use that was introduced in REST Assured 4.5.1.
