### ISSUE TITLE
Remove documentation and metadata references to ConfigFileApplicationListener

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#31895]
Hi,

I've noticed that `ConfigFileApplicationListener` is still referenced in a few places. Including the docs which leads to a 404 obviously.

See https://github.com/spring-projects/spring-boot/search?q=ConfigFileApplicationListener

Since I'm unsure what to do with the usages inside `additional-spring-configuration-metadata.json` and how (or if) you want to rephrase the documentation, I'll leave this to you. Or you tell me what I should do and I'll do it myself.

Cheers,
Christoph

**Comment by philwebb** [comment]
Good spot @dreis2211! The documentation wasn't accurate so I've changed that and updated the meta-data to use the replacement classes. Thanks for raising the issue.
