### ISSUE TITLE
Remove ActuatorAnnotationsRuntimeHints JDK proxy registration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#31919]
https://github.com/spring-projects/spring-boot/blob/41e869744598547f2cf951fe50df7168d9b8669b/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/ActuatorAnnotationsRuntimeHints.java#L44 can be removed when https://github.com/spring-projects/spring-framework/issues/28767 is fixed.

**Comment by snicoll** [comment]
Our code really only looks for `Endpoint` and `EndpointExtension` so to "force" the creation of the proxy, we'd have to register something that composes it, such as `WebEndpoint` or `WebEndpointExtension`. This would work but register unnecessary hints. I'll see if something can be done to avoid having to know about the synthetized annotation.

**Comment by snicoll** [comment]
I've created https://github.com/spring-projects/spring-framework/issues/28887 to improve this scenario.
