### ISSUE TITLE
Harmonize AOT goal/task names

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#31918]
The maven plugin is currently named `spring-boot:aot-generate` and The Gradle task is `generateAotSources`. While brainstorming on the names to use for the related test support, we thought renaming those was in order.

* For Maven: `spring-boot:aot` (and`spring-boot:aot-test`)
* For Gradle: `bootAot` (and `bootAotTest`)

**Comment by snicoll** [comment]
@wilkinsona mentioned that it feels the current proposal uses `aot` as a verb. We've been brainstorming and found `processAot` and `processTestAot` to match nicely with Gradle's `compileJava` and `compileTestJava`

**Comment by philwebb** [comment]
At least for now we're going to go with...

Maven:

```
spring-boot:process-aot
spring-boot:process-test-aot
```

Gradle:

```
bootProcessAot
bootProcessTestAot
```
