### ISSUE TITLE
User-defined RedisCacheConfiguration doesn't work

### ISSUE THREAD

**Issue by rainman-code** [spring-projects/spring-boot#31960]
![image](https://user-images.githubusercontent.com/53501828/182375098-a2c86747-ff02-444e-a277-286e0187a88c.png)
![image](https://user-images.githubusercontent.com/53501828/182375211-76036303-c041-46cd-b61d-5bc34f9c8cb6.png)

**Comment by snicoll** [comment]
@rainman-code a couple of screenshots and "do not work" aren't really helpful I am afraid. What part of the user-defined `RedisCacheConfiguration` does not work exactly?
