### ISSUE TITLE
Official support for Spring Boot Legacy

### ISSUE THREAD

**Issue by tryIO** [spring-projects/spring-boot#3196]
Hi! this is more a curiosity than a real demand or issue, since I'm wondering if there's _any_ chance (with some hacks also) to have a Spring Boot Application running on older versions of Tomcat, let's say 6 (at minimum and w/o any upgrade of internal modules).

I looked at Spring Boot Legacy (https://github.com/scratches/spring-boot-legacy) and it seems feasible, but I don't know to what level of stability and reliability.

I'm asking this because of the post published on Spring.io/blog: https://spring.io/blog/2015/06/04/happy-second-birthday-java-ee-7-how-is-it-going-in-production and then some weird fantasies raised in my head.

**Comment by snicoll** [comment]
You can find the rationale of the Spring Boot legacy situation in #1318

Spring Boot is certainly *not* going in the direction of supporting older Java versions. There are [some notes regarding Java6](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-java-6). You could try Spring Legacy with Tomcat6.
