### ISSUE TITLE
"Unable to find main class" in a multi module gradle project

### ISSUE THREAD

**Issue by grundid** [spring-projects/spring-boot#3197]
When I add apply plugin: 'spring-boot' to all subprojects in a multi module gradle project the build task exits with the above error message.

A workaround is to add 
bootRepackage {
    mainClass = '...'
}
in all build.gradle files or to set the apply plugin line only in the one module that currently has the Application class but then the version management does not work for all modules.

It would be better if I could only set the mainClass in one module.

**Comment by xenoterracide** [comment]
I've had similar problems with multi module maven

**Comment by wilkinsona** [comment]
I'd recommend only applying the Spring Boot plugin to the module that contains the actual application. In the other modules, I'd use the [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) for version management and import Spring Boot's bom:

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.1.RELEASE"
    }
}

apply plugin: "io.spring.dependency-management"

dependencyManagement {
  imports {
    mavenBom 'org.springframework.boot:spring-boot-starter-parent:1.2.4.RELEASE'
  }
}
```

Spring Boot 1.3 uses the dependency management plugin for version management in Gradle builds so, if you're using an earlier version of Boot, this is a step in the direction that Boot is going.

**Comment by xenoterracide** [comment]
would you add a sample  multi module application that includes both maven and gradle to the samples directory? I'm still not sure how this would work for maven, and how adding the plugin to the module with the application would allow it to work. considering that when I do that it won't resolve my dependencies properly.
