### ISSUE TITLE
Stream Closed appears when uploading files using MultipartFile

### ISSUE THREAD

**Issue by Mr-YW** [spring-projects/spring-boot#31992]
In order to read the body twice, we rewrite the HttpServletRequestWrapper,And wrap the original request through the Filter.Although we packing the original Request, upload files, StandardMultipartHttpServletRequest call or use the original Request, not after we packing, We rewrite HttpServletRequestWrapper getInputStream method is not called, the original flow has been closed, result in an error

**Comment by Mr-YW** [comment]
At present, our solution is to call the getParameter method of request once in the wrapped Filter to solve this problem

**Comment by philwebb** [comment]
`StandardMultipartHttpServletRequest` is part of Spring Framework. If you think you've found a bug with that class please raise an issue for that team at https://github.com/spring-projects/spring-framework/issues/new and attach a sample application that shows the problem.
