### ISSUE TITLE
Make health show-details and show-components technology specific

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32006]
Currently `management.endpoint.health.show-components` and `management.endpoint.health.show-details` aren't applied to JMX endpoints. This is a little confusing and we think it would be better to create technology specific variants:

For JMX we can have:
```
management.endpoint.health.jmx.show-components
management.endpoint.health.jmx.show-details
```

And for Web we can have:
```
management.endpoint.health.web.show-components
management.endpoint.health.web.show-details
```

Another subtle difference is that `HealthProperties.Show` has `NEVER`, `WHEN_AUTHORIZED` and `ALWAYS`. For JMX, we don't have the concept of an authorized user so we can't offer it as an option.

Once added, we can deprecate `management.endpoint.health.show-components` and `management.endpoint.health.show-details` and consider them aliases for the `web` version.

**Comment by jsattler** [comment]
@philwebb this would then also apply to health groups, right?

So, this should be possible:

```properties
management.endpoint.health.group.custom.jmx.show-components
management.endpoint.health.group.custom.jmx.show-details

management.endpoint.health.group.custom.web.show-components
management.endpoint.health.group.custom.web.show-details
```

**Comment by mbhave** [comment]
Thanks @jsattler for pointing that out. We have decided not to introduce the technology split as it could inflict unwanted upgrade pain for users without too much benefit. We've decided to stick with the original design where JMX users are always shown the details.
