### ISSUE TITLE
SpringApplicationContextLoader not excluding classes from EnableAutoConfiguration

### ISSUE THREAD

**Issue by jakehschwartz** [spring-projects/spring-boot#3200]
I am attempting to start my application to run Cucumber tests. Using the following set of annotation, the application attempts to start but fails due to the a bean conflict in the `RabbitAutoConfiguration`. When starting the application through bootRun, the configuration is ignored, as expected.

```
@ContextConfiguration(classes = Application.class, loader = SpringApplicationContextLoader.class)
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration
@TestExecutionListeners({ServletTestExecutionListener.class})
public abstract class AbstractSpringTest
{
...
}


@Configuration
@ComponentScan
@EnableAutoConfiguration(exclude={RabbitAutoConfiguration.class, MultipartAutoConfiguration.class})
@EnableScheduling
@ImportResource({"classpath:/aspect-context.xml","classpath:/messaging-context.xml"})
public class Application extends SpringBootServletInitializer
{
...
}
```

Thanks and let me know if you need more information.
Jake

**Comment by snicoll** [comment]
Unrelated by why aren't you using `@SpringApplicationConfiguration` on your test (this will prevent you from specifying the loader yourself).

**Comment by jakehschwartz** [comment]
Replacing
    @ContextConfiguration(classes = Application.class, loader = SpringApplicationContextLoader.class)
with
    @SpringApplicationConfiguration(classes = Application.class)

causing Spring Boot not to start.

**Comment by jakehschwartz** [comment]
I made a small example app to prove my point and it ended up working. Guess I need to go back and figure out why it won't work for me.
