### ISSUE TITLE
Spring Data Source Properties

### ISSUE THREAD

**Issue by sincang** [spring-projects/spring-boot#3201]
Hi,

I am adding the following spring datasource properties and I am encountering issues.

1. spring.datasource.init-sql=alter session set current_schema = OWNER 
    The initSQl is not getting set. I verified it by looking at the jmx.

2. spring.datasource.jdbc-interceptors=org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTime
   An exception is thrown during start-up. Spring boot is not able to find the class org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTime even if tomcat-jdbc is in my classpath.

Pipo

**Comment by sincang** [comment]
I was able to resolve the issue number one. I am using the spring.datasource.init-SQL.

**Comment by snicoll** [comment]
Please ask such questions on stackoverflow. We would like to keep this tracker for bug reports and feature requests.

`init-SQL` and `init-sql` are equivalent for the binder so that feels weird to me. As for the error, I can't help you much without a sample project.
