### ISSUE TITLE
Can't use square brackets in YAML map keys

### ISSUE THREAD

**Issue by pimlottc** [spring-projects/spring-boot#3202]
I'm using a map defined in my application.yml but ran into an unexpected problem when trying to use keys that include square brackets [ ].  It seems like Spring Boot is trying to interpret them as named indices or something, and I can't figure out any way to quote or escape them so they are taken as strings.

For example, this map:

```
myConfig:
  myMap:
    'x A y': 'apple'
    'x B y': 'ball'
    'x [C] y': '[cat]'
    "x [D] y": "[dog]"
    ? "x [E] y": "[eiffel tower]"
```

Results in a map with these keys:

```
x A y
x B y
x .C y
x .D y
{x .E
```

**Comment by pimlottc** [comment]
I originally filed this on Spring JIRA, there's a test case in there to demo the example above.
https://jira.spring.io/browse/SPR-13105

**Comment by snicoll** [comment]
And it's indeed not the same thing as #2386 so thanks for creating the issue.

**Comment by philwebb** [comment]
@pimlottc Are you using `@ConfigurationProperties` to bind your YAML to an object? Have you got a snippet of code that you could share?

**Comment by philwebb** [comment]
I think the problem is most likely in `RelaxedDataBinder` and specifically the `BeanPath.splitPath` method. I'm not sure that we should try to attack this in 1.2.x due to the high probability we'll introduce some side effect.

@dsyer Have you any ideas how we could support this?

**Comment by philwebb** [comment]
Failing test is here https://github.com/philwebb/spring-boot/tree/gh-3202

**Comment by mbhave** [comment]
@pimlottc On the latest snapshot, this can be achieved by doing `[x [C] y]: [cat]`.

**Comment by mirak94** [comment]
I'm having the same problem.
@mbhave I couldn't get what you've tried to demonstrate.

Thank you in advance!

**Comment by mbhave** [comment]
@mirak94 We think this issue has been fixed. If something is not working for you, please open a new issue with a small sample that can help us reproduce the issue.
