### ISSUE TITLE
Provide property to switch to simplified logging format

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32047]
See https://twitter.com/bsideup/status/1557116232146554882

We could offer a quick property to switch to simplified logging.

**Comment by wilkinsona** [comment]
I'm not sure about this. IMO, demos are better when things with which the audience is likely to already be familiar look as they expect them to look. This then means that the audience can focus on the new stuff rather than being distracted by things that aren't as expected.
