### ISSUE TITLE
How integrate spring-flex and spring-boot without xml config?

### ISSUE THREAD

**Issue by aruis** [spring-projects/spring-boot#3204]
Now,I write code like this. But can I only use annotation?
flex-servlet.xml

     <?xml version="1.0" encoding="UTF-8"?>
     <beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:flex="http://www.springframework.org/schema/flex"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.springframework.org/schema/flex
           http://www.springframework.org/schema/flex/spring-flex-1.6.xsd"
        >

    <flex:message-broker mapping-order="0" services-config-path="classpath:/META-INF/flex/services-config.xml"/>
    </beans>   

main class is: Appliction.groovy

    @Bean
    public DispatcherServlet flexDispatcherServlet() {
        XmlWebApplicationContext appContext = new XmlWebApplicationContext();
        appContext.setConfigLocation("classpath:/META-INF/flex-servlet.xml");
        return new DispatcherServlet(appContext);
    }

    @Bean
    public ServletRegistrationBean dispatcherRegistrationFlex() {
        ServletRegistrationBean registration = new ServletRegistrationBean(flexDispatcherServlet(), "/messagebroker/*");
        registration.name = 'flex'
        registration.setLoadOnStartup(1)
        return registration;
    }

**Comment by benneq** [comment]
I had a smilar problem, maybe it helps: http://stackoverflow.com/a/30686733/1321564
It should also work with `XmlWebApplicationContext` if you need XML config.

have a look at application startup if the default dispatcher servlet gets registered (path: `/`) and your custom one. There's also a way to not register the default dispatcher servlet (explained at StackOverflow). And you don't need to expose the DispatcherServlet itself as a `@Bean`.

**Comment by aruis** [comment]
Thank you,benneq. Maybe I expressed clearly enough.
I want get rid of XML config. Because,there's only one useful line.
' <flex:message-broker ...'
I hope use annotation instead of xml.

**Comment by sdeleuze** [comment]
Spring Flex only supports XML based configuration, so I don't think it is possible easily.

**Comment by aruis** [comment]
Thank you , sdeleuze. I understand now.
