### ISSUE TITLE
Add @WebEndpointTest attribute to specify target frameworks

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#32054]
As discussed in https://github.com/spring-projects/spring-boot/pull/32046#pullrequestreview-1067421804, it would be useful if `@WebEndpointTest` had an attribute that would allow to specify target web frameworks that given test should be executed against.

**Comment by wilkinsona** [comment]
Possible implementation: https://github.com/wilkinsona/spring-boot/tree/gh-32054.
