### ISSUE TITLE
Add native hints for default LDIF file

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-boot#32084]
Spring Boot supports importing an LDIF file into an embedded LDAP server via `spring.ldap.embedded.ldif`.
When running the application natively, it fails with a NullPointerException because the resource is not added to the generated binary. It works when doing `hints.resources().registerPattern("*.ldif");`

https://github.com/spring-projects/spring-boot/blob/a8ae7a1e448486fd6d235ab1911560bf47a379a1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/ldap/embedded/EmbeddedLdapAutoConfiguration.java#L128

**Comment by snicoll** [comment]
I am trying to make this work with the default `schema.ldif` and it doesn't in the smoke test at the moment. Not sure why.

The generated hint is as follows:

```
{
        "pattern": "\\Qschema.ldif\\E"
      }
```

**Comment by snicoll** [comment]
An additional hint specific to unboundid was required.
