### ISSUE TITLE
Allow to disable JacksonFeature in JerseyAutoConfiguration

### ISSUE THREAD

**Issue by xhaggi** [spring-projects/spring-boot#32088]
When a project using both, a Jersey client with Jackson (`jersey-media-json-jackson`) and a Jersey server using MOXy (`jersey-media-moxy`), Jackson is auto-configured by `JerseyAutoConfiguration.JacksonResourceConfigCustomizer` also for the Jersey server and there is no easy way to disable that behavior. As a workaround we exclude `JacksonAutoConfiguration`, because the `JacksonResourceConfigCustomizer` requires an `ObjectMapper` that is created by `JacksonAutoConfiguration`.

By the way, I created a pull request #32083 for this, but it was declined.

**Comment by snicoll** [comment]
> By the way, I created a pull request https://github.com/spring-projects/spring-boot/pull/32083 for this, but it was declined.

The PR was declined with an offer to create an issue that stated:

> If not, please open an issue with some more details about how you're using Jackson and MOXy with Jersey and we can consider what options are available to meet your needs.

Please provide the details. A sample showing the problem we can run ourselves would be ideal.

**Comment by xhaggi** [comment]
>The PR was declined with an offer to create an issue that stated:

I know and this is the issue that describes how we're using Jackson and MOXy.

>Please provide the details. A sample showing the problem we can run ourselves would be ideal.

What details do you still need? We don't want `JacksonFeature` + `ObjectMapper` to be auto-configured by `JerseyAutoConfiguration.JacksonResourceConfigCustomizer` as we use MOXy for the Jersey server. We cannot exclude `jersey-media-json-jackson` because a Jersey client that uses Jackson is also present in the same project. Having both Jackson and MOXy configured in the `ResourceConfig` of the Jersey server may cause problems with XML serialization.

**Comment by snicoll** [comment]
Stating what you've already stated in the PR doesn't qualify as more details.

If you want this change to be considered, we need the additional details of "how you're using Jackson and MOXy with Jersey" to make an informed call.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
