### ISSUE TITLE
Porting FlywayMigrationStrategy for 1.2.x branch

### ISSUE THREAD

**Issue by dgomesbr** [spring-projects/spring-boot#3208]
As requested from @paranoiabla in the gitter channel, I'm opening this for a future PR.

> is there any chance to port-back the FlywayMigrationStrategy to the spring-boot 1.2.x branch?
currently it's only in the master which is 1.3.0.SNAPSHOT

**Comment by philwebb** [comment]
Commit ebccedcfdde14a64280aa0e3b5a8438bc84f6fd2

**Comment by philwebb** [comment]
I'm not usually keen to backport features but this one doesn't look too risky.

**Comment by ptahchiev** [comment]
Please also have a look at this https://github.com/spring-projects/spring-boot/pull/3212 before you backport. Thanks

**Comment by dgomesbr** [comment]
Hey @philwebb I've looked into the code needed before suggesting the backport and thought that was rather small.

@dsyer sugested a Interface based on Gitter. Dave, could you elaborate on that? 

@ptahchiev I'll rebase daily until the PR is ready, so feel to get the comments and fixes mentioned there.

**Comment by dsyer** [comment]
@dgomesbr interfaces are generally superior for the "strategy" pattern, I feel. As an added bonus you get to use a lambda to implement this one if you are using Java 8.

**Comment by dgomesbr** [comment]
Ahhh, my inicial plan was a copy and port. I'll open another issue to port
the db migration to a common interface then. Let me evaluate something like
flyway to get the interface methods and hooks on the way.

Thanks for the promptly reply.

**Comment by dgomesbr** [comment]
@ptahchiev I'll left open for a couple days 'till we have the #3212 is merged so I can rebase it and send a PR

**Comment by dgomesbr** [comment]
@ptahchiev I've seen that you're currently discussing #3212, I'll open the PR so we can update once the #3212 is closed.

**Comment by philwebb** [comment]
After considering this some more I'm not convinced that backporting `FlywayMigrationStrategy` is a good idea. The discussions in #3212 and #3217 make me think that we haven't quite got the current implementation right. I'm also worried that there might be some unexpected side-effects that we don't want to introduce in a point release.

For 1.2 users I think the best way to proceed is to disable our auto-configuration and handle things yourself.

**Comment by dgomesbr** [comment]
:+1:
