### ISSUE TITLE
In 2.6.10, config of `spring.web.resources.static-locations` dose't work

### ISSUE THREAD

**Issue by prayjourney** [spring-projects/spring-boot#32094]
Hello, I use the config like as below and when it's running IDEA Console output log as first image, the second image is my local resources. 
```properties
spring.mvc.static-path-pattern=/**
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
```
![Snipaste_2022-08-16_20-02-24](https://user-images.githubusercontent.com/15311937/184874945-4ab4880a-1e32-488b-9de7-23ac77b1a957.png)
![2](https://user-images.githubusercontent.com/15311937/184875578-9a1a0a92-5a95-4d83-aa00-37e5d3896ade.png)

when i create a java configuration class as below it works. i remeber that in the elder version, i use default config that write nothing in the application.properties or in the applicaiotn.yaml, at the same time, i don't create a config class about `WebMvcConfig`, it' still work,
```java
@Configuration
public class WebMvcConfig extends WebMvcConfigurationSupport {
    private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {
            "classpath:/META-INF/resources/", "classpath:/resources/",
            "classpath:/static/", "classpath:/public/"
    };
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        if (!registry.hasMappingForPattern("/**")) {
            registry.addResourceHandler("/**").addResourceLocations(CLASSPATH_RESOURCE_LOCATIONS);
        }
    }
}
```
my project use springboot and thymeleaf 2.6.10, use default config. thanks!

**Comment by mbhave** [comment]
@prayjourney Please provide a minimal sample application that we can run in order to reproduce the issue. The sample can be attached as a zip to this issue or provided as a link to a separate Github repository.

**Comment by prayjourney** [comment]
[wang-editor5-integration.zip](https://github.com/spring-projects/spring-boot/files/9357027/wang-editor5-integration.zip)
**@mbhave**, in the attached file, i commented the config class, it doesn't work, as below
![image](https://user-images.githubusercontent.com/15311937/185052190-fdc0f4e3-dd68-4d00-a7e0-70816fed6057.png)

**Comment by snicoll** [comment]
Thanks for the sample @prayjourney.

The sample contributes a bean of type `WebMvcConfigurationSupport` which switches off Spring Boot's MVC auto-configuration. As a result, none of the configuration properties are applied. If you need to customize MVC support, please use `WebMvcConfigurer` instead.

**Comment by prayjourney** [comment]
thanks!

> Thanks for the sample @prayjourney.
> 
> The sample contributes a bean of type `WebMvcConfigurationSupport` which switches off Spring Boot's MVC auto-configuration. As a result, none of the configuration properties are applied. If you need to customize MVC support, please use `WebMvcConfigurer` instead.

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！
