### ISSUE TITLE
Don't quit application on resart compile failures

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3210]
It's easy to accidentally break code during a restart and currently this causes the app to quit. We should just keep things live and wait for another file update.

**Comment by rajjaiswalsaumya** [comment]
What was this about ?

**Comment by philwebb** [comment]
@rajjaiswalsaumya There's a new devtools module coming in 1.3 (see http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-devtools) that automatically restarts your app when you change code.

It didn't work so well if you accidentally broke your code when you saved files as the app would just exit.
