### ISSUE TITLE
Why  after i used actuator-api Evict All Caches，i alose can use actuator-api Retrieving All Caches

### ISSUE THREAD

**Issue by HellLiang** [spring-projects/spring-boot#32115]

**Comment by snicoll** [comment]
It's hard to understand what you're reporting with only a title. I understand it as you invoke the evict endpoint to clear all the caches and you can still see them. Evict doesn't delete the cache, but the entries. If you have more questions, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you're trying to report a bug, you'll have to provide more details.

**Comment by HellLiang** [comment]
1、i use actuator-api like following
![1](https://user-images.githubusercontent.com/64981240/185577572-7b8a5746-e498-4895-a053-21bb18165187.png)

![2](https://user-images.githubusercontent.com/64981240/185577625-c8a5f747-f05a-456c-9a8d-c7cdaa7fb688.png)

2、but i can also use actuator-api like following:
![3](https://user-images.githubusercontent.com/64981240/185577795-78714ce9-4152-4aa1-a29a-3eaf2d4ff446.png)

![4](https://user-images.githubusercontent.com/64981240/185577837-59fd1f4f-29a5-45be-a2af-ca63a8fd24ff.png)

**Comment by snicoll** [comment]
> Evict doesn't delete the cache, but the entries

Does that help?

**Comment by HellLiang** [comment]
> > Evict doesn't delete the cache, but the entries
> 
> Does that help?

it means i can not use actuator-api delete cache?

**Comment by HellLiang** [comment]
> > Evict doesn't delete the cache, but the entries
> 
> Does that help?
how can i delete the cache，code? ore other method

**Comment by snicoll** [comment]
The cache abstraction has no feature to delete a cache. Please ask further questions on StackOverflow.

**Comment by HellLiang** [comment]
> The cache abstraction has no feature to delete a cache. Please ask further questions on StackOverflow.

all right
