### ISSUE TITLE
Provide a way to completely disable Actuator with property

### ISSUE THREAD

**Issue by yaohongkok** [spring-projects/spring-boot#32118]
Some of our company's Spring Boot 2.x apps would have their tests fail due to some Mockito issues. My colleague suggested to me that he wanted to switch of Actuator for certain tests. I went through the internet and documentation. I just could not find a way to completely shut off Actuator.

If this feature is not already available, may I recommend to provide a property to completely disable the starting of Actuator?

**Comment by snicoll** [comment]
Before we consider any option, it would be helpful to understand the relationship between "tests fail due to some Mockito issues" and disabling the actuator.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by yaohongkok** [comment]
After more investigations, you are probably right that it is not actuator
that causing Mockito to fail.

Can you treat this as a potential enhancement? It is a useful feature for
debugging. For example, to confirm Actuator isn't responsible for the
failure. It is probably not the highest priority.

Thanks!

**Comment by wilkinsona** [comment]
I don't think we should do this as there's no easy way for us to identify whether or not an auto-configuration is part of Actuator. If you want to temporarily disable Actuator to see if it's causing a problem, you should remove the actuator dependency from your application and rebuild it.
