### ISSUE TITLE
spring.metrics.export.redis.aggregate-key-pattern does not seem to be used

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3213]
Looking at `MetricExportProperties.Redis#aggregateKeyPattern` I see no use of it.

**Comment by dsyer** [comment]
It's used in the sample: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-metrics-redis/src/main/java/sample/metrics/redis/AggregateMetricsConfiguration.java#L46 (in a way that documents why it exists IMO).

**Comment by snicoll** [comment]
Ah, the samples are not opened in my project, that's why. Feel free to close this issue (though admittedly, I'd have expected a use of the property in the module, in a test for instance).
