### ISSUE TITLE
Stop using deprecated method call for Redis container to get the IP Address

### ISSUE THREAD

**Issue by thegeekyasian** [spring-projects/spring-boot#32130]
SampleCacheApplicationRedisTests uses `getContainerIpAddress` which is deprecated and should be replaced with a correct one i.e. `getHost()`

https://github.com/spring-projects/spring-boot/blob/82a9c219e11c1c5e82465d35026402b862cba033/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-cache/src/redisTest/java/smoketest/cache/SampleCacheApplicationRedisTests.java#L49

**Comment by mhalbritter** [comment]
Closing in favor of the PR.
