### ISSUE TITLE
Server remains 503 if starting without Mongodb presence

### ISSUE THREAD

**Issue by WeipingGuo** [spring-projects/spring-boot#3214]
HI All,

Need some helps.  In a sunnyday scenario, we started mongodb and then started server. Everything is cool. 

However,  the following scenario did not work for me:
1. shutdown mongodb
2. start application  -- exceptions are thrown because could not connect to mongo. the application seems started up though
3. http://localhost:8080/beans return 503
4.start mongo, however the application remains on 'service unavailable', never recover

I hoped the application can start even if mongodb is not there and recover when mongo comes back.

I might be missing something. Anything suggestions are appreciated! 

I am on 1.2.3.RELEASE

Thanks.
Weiping

**Comment by philwebb** [comment]
I'm not aware of any general strategies for dealing with this. I think most applications consider the database to be such an integral part of the application that that prefer to fail fast if it's missing.

Someone from the Spring Data team might have suggestions but your best bet is probably asking on stackoverflow.com.

/cc @olivergierke

**Comment by WeipingGuo** [comment]
Thank you very much. I will follow up on stackoverflow.com.
