### ISSUE TITLE
Hazelcast auto-configuration recognizes hazelcast.xml and hazelcast.yaml files but not hazelcast.yml

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#32141]
Hazelcast autoconfiguration recognises `hazelcast.xml` and `hazelcast.yaml` but not `hazelcast.yml`

Similarly for clients, autoconfiguration recognises `hazelcast-client.xml`, `hazelcast-client.yaml` but not `hazelcast-client.yml`

Hazelcast itself accepts `.yaml` and `.yml`, see https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/config/DeclarativeConfigUtil.java#L67

Enhancement is to make Spring Boot recognise `yml` suffix config files

**Comment by philwebb** [comment]
Closing in favor of PR #32142. Thanks @neilstevenson!
