### ISSUE TITLE
Higher level idiom for database migration strategy

### ISSUE THREAD

**Issue by dgomesbr** [spring-projects/spring-boot#3215]
Today Spring Boot (http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-use-a-higher-level-database-migration-tool) is very tied to the implementation as you can see in the docs. You should pick Flyway or Liquibase and configure properties for both.

This issue is to convert this migration tooling to something more generic and pluggable. The original idea came from beside back-porting the current implementation to the 1.2.x branch #3208, is to optimize that implementation on the 1.3.x or maybe future releases.

Feel free to supply information and critics to it.

**Comment by philwebb** [comment]
I think that the way that you use Flyway and Liquibase are different enough to warrant different configuration properties. What did you have in mind for such an abstract? Have you got a different technology in mind that you want to plug in?

**Comment by dgomesbr** [comment]
Added strategy to the tittle to make more sense, it's not the implementation per se.

**Comment by dgomesbr** [comment]
Hey @philwebb, I believe that @dsyer was telling me that the current implementation of [FlywayMigrationStrategy](https://github.com/spring-projects/spring-boot/blob/a49901f0dcc96e153114de99cd43a27ed986de12/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayMigrationStrategy.java) is a class that could be refactored to a Interface. Something like 

```java
public interface DefaultMigrationStrategy  {
    default void migrate(){
        //...
    }
}

...

public class LiquibaseMigrationStrategy  implements DefaultMigrationStrategy  {
    private Flyway flyway; 

    @autowired
    LiquibaseMigrationStrategy (Flyway instance){
       this.flyway = instance;
    }
    public void migrate(){
         flyway.migrate();
    }
}

```

I don't know if this is the end of it or how should we call the liquibase engine instead, but is there anyway to converge (or if shall we do it?)  changesets and migrations to a common language.

**Comment by philwebb** [comment]
Why would `LiquibaseMigrationStrategy` make use of Flyway? 

Currently our Liquibase integration uses `liquibase.integration.spring.SpringLiquibase` which is provided by Liquibase (and not something that we control).

My gut feeling is still that Liquibase and Flyway are different enough that common idioms don't make much sense. I also can't see people really wanting to switch between the technologies one they have chosen one.

**Comment by dgomesbr** [comment]
Read all the docs and evaluated other migration tools, makes no sense at all for sure. I'll close it.

**Comment by philwebb** [comment]
Thanks anyway for the suggestion. It's always useful to discuss these ideas.
