### ISSUE TITLE
Plugin Support, Classloader for Spring JAR files

### ISSUE THREAD

**Issue by paulsen-it** [spring-projects/spring-boot#32161]
Hello together,

I look around and search for a solution to make Spring Boot Pluginable. 
What I want: I create a master Spring Boot Application Jar File. And another Spring Boot Application Jar File. Both Projects can run alone. But if desired the first Project can load the second as Plugin. Like [PF4J](https://pf4j.org/) but PF4J cannot load Spring Boot Jar files. Only 
normal Jar Files. If there is a possibility to use the JarLauncher to add a Path, to load additional Jar files, that will be perfect. So can Spring Boot be more modularized.

Thank you very much.

**Comment by philwebb** [comment]
I'm afraid this is really out of scope for what we want to do with the `JarLauncher`. It will add complexity that I fear we wouldn't have time to maintain.

If you want to develop your own launcher, you can use the [`LayoutFactory`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-layoutFactory) interface. You can look at https://github.com/spring-projects-experimental/spring-boot-thin-launcher if you want to see it being used in a real project.
