### ISSUE TITLE
Logging documentation example incorrect

### ISSUE THREAD

**Issue by roberthunt** [spring-projects/spring-boot#3218]
Section [26.4 Log Levels](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-custom-log-levels) of the documentation provides an example logging configuration in "yml" format (for use in `application.yml`) yet the rest of the section talks about `application.properties`

**Comment by wilkinsona** [comment]
Are you referring to this example?

```
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
```

If so, that's in `.properties` format.

**Comment by roberthunt** [comment]
Yep, sorry I'm not used to seeing colon used in properties file, you can ignore this issue.

**Comment by philwebb** [comment]
I think for consistency with other snippets in the documentation we should probably change this example to use `=`.
