### ISSUE TITLE
Remove AnsiColors

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32209]
It was added as part of image banner support and image banner support was [removed](https://github.com/spring-projects/spring-boot/issues/28883) in 3.0.0-M2. AnsiColors should have been removed at that time. This issue will correct that oversight.

**Comment by meiMingle** [comment]
No, I disagree, I think maybe AnsiColors deserves to be kept. It is useful for generating Ascii Art style banners, for example I can use it to generate colored QR codes like the one below. If AnsiColors is removed, it is a big hassle to manually handle the conversion from Color to AnsiColor, AnsiBackground, Ansi8bitColor.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/39942874/187900355-71fa7adb-4b30-4a24-93a2-fa451765bbb0.png">

**Comment by meiMingle** [comment]
虽然 AnsiColors 最初是用来支持图像横幅的，但它不应该仅仅被视为图像横幅的一部分，它在将文本横幅处理成彩色 Ascii Art 横幅方面发挥着重要作用，如上图所示。

**Comment by meiMingle** [comment]
Although AnsiColors was originally used to support image banners, it should not only be seen as a part of image banners, it plays an important role in processing text banners into colored Ascii Art banners, as in the picture above.

**Comment by wilkinsona** [comment]
Unfortunately, as we no longer have any need for it in Spring Boot I don't think we can justify the ongoing maintenance cost of maintaining and enhancing it. Given Spring Boot's permissive Apache v2 licence, you are free to copy the source code into your own application and maintain it there.
