### ISSUE TITLE
Detection of DurationStyle.ISO8601 does not support lower-case input

### ISSUE THREAD

**Issue by valentine-dev** [spring-projects/spring-boot#32218]
# Bug Report

### Version of Spring Boot

2.7.3

### Version of Java

11

## Expected (what is in the Reference Documentation)

>The standard ISO-8601 format [used by java.time.Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-)

from https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion.durations

## Actual Behavior

Some format used by java.time.Duration is not working in Spring Boot app, like "pt25.234s" demonstrated in the example application at https://github.com/valentine-dev/spring-boot-duration-style-iso8601

## Suggestion Solution

1. Add `Pattern.CASE_INSENSITIVE` as the second argument to the `Pattern.compile` method at [Line 87 of DurationStyle.java](https://github.com/spring-projects/spring-boot/blob/01c68a3dc829e6c82a8f64841ae98c0bf09e6fa9/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/convert/DurationStyle.java#L87)
2. Use the following pattern string in java.time.Duration source code (Line 151 ~ 152 in the file from JDK 11) at [Line 65 of DurationStyle.java](https://github.com/spring-projects/spring-boot/blob/01c68a3dc829e6c82a8f64841ae98c0bf09e6fa9/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/convert/DurationStyle.java#L65):

``"([-+]?)P(?:([-+]?[0-9]+)D)?" +``
        ``"(T(?:([-+]?[0-9]+)H)?(?:([-+]?[0-9]+)M)?(?:([-+]?[0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?"``

**Comment by mdeinum** [comment]
Not sure it is a bug. 

From the ISO-8601 spec (emphasize is mine)

>  The **capital** letters P, Y, M, W, D, T, H, M, and S are designators for each of the date and time elements and are not replaced

It explicitly mentions capital letters. So one could argue that Spring (Boot) might adhere to strictly to the standard as opposed the `java.time.Duration` class?

**Comment by wilkinsona** [comment]
Given that we say we use the format that is used by java.time.Duration, I think it's reasonable to expect the detect and detectAndParse methods to align with Duration's own parsing.

I'm not sure that we need to go as far as using the same pattern as Duration does. Our simpler pattern used case-insensitively may be enough for our detection needs.

**Comment by valentine-dev** [comment]
> Given that we say we use the format that is used by java.time.Duration, I think it's reasonable to expect the detect and detectAndParse methods to align with Duration's own parsing.
This is the focus. If we said that way, then we need to implement the same way.
> 
> I'm not sure that we need to go as far as using the same pattern as Duration does. Our simpler pattern used case-insensitively may be enough for our detection needs.
DurationStyle.SIMPLE is fine as it is Spring's own way. Using the same pattern as Java Duration does inside is the simplest way, I think.

**Comment by valentine-dev** [comment]
> Given that we say we use the format that is used by java.time.Duration, I think it's reasonable to expect the detect and detectAndParse methods to align with Duration's own parsing.
> 
> I'm not sure that we need to go as far as using the same pattern as Duration does. Our simpler pattern used case-insensitively may be enough for our detection needs.

Thanks for the feedback! 

I would like to fix this bug - should be quick.

**Comment by valentine-dev** [comment]
PR created at https://github.com/spring-projects/spring-boot/pull/32223 to fix this bug.

**Comment by philwebb** [comment]
Closing in favor of PR #32223. Thanks @valentine-dev!
