### ISSUE TITLE
@ConfigurationProperties nested map exists inject type mismatch.

### ISSUE THREAD

**Issue by graceyu-own** [spring-projects/spring-boot#32220]
========= My application.yml config ===============
![image](https://user-images.githubusercontent.com/44594974/188112862-b9f7ad5b-d857-493b-b1d2-5d36debc33ff.png)

========= My defined ConfigurationProperties =========
![image](https://user-images.githubusercontent.com/44594974/188113046-498c4592-118f-4c5e-a444-ad02d255d5b9.png)

========= Actual data =========================
![image](https://user-images.githubusercontent.com/44594974/188113244-9c9463a0-bb57-49b0-8a21-addd7d0e9b91.png)

==========================================
I expect data 'option.input.rules' is an array, but it's map

**Comment by wilkinsona** [comment]
Unfortunately, as you haven't provided any type information in your configuration properties class, it's difficult for the binder to know what to do. The fact that it's a list in YAML is lost (somewhat) as the information is turned into properties when it's added to the environment. Have you considered using something more strongly typed than `Map<String, Object>` for `input` and `output`?

**Comment by graceyu-own** [comment]
> Unfortunately, as you haven't provided any type information in your configuration properties class, it's difficult for the binder to know what to do. The fact that it's a list in YAML is lost (somewhat) as the information is turned into properties when it's added to the environment. Have you considered using something more strongly typed than `Map<String, Object>` for `input` and `output`?


Really, if the actual data type is used, this problem can be solved. but i can't do this in real situations.
--------------------------
I have many components, their `input` data types are different (contains `key` and `value`), such as:
-------------------------
A component:
![image](https://user-images.githubusercontent.com/44594974/188300145-cdcacdac-b613-4650-83d9-f73fb3303b86.png)

B component:
![image](https://user-images.githubusercontent.com/44594974/188300177-3c5b555a-5ec3-42ff-b868-33ce7eae7152.png)
-------------------------
And there may be problems that components have the same `key` and different types, so i can only use  `Map<String, Object>`

**Comment by wilkinsona** [comment]
> And there may be problems that components have the same key and different types

Configuration properties are intended to be type-safe so they are not the right tool to use for this sort of configuration data. You may be able to write some code of your own using the `Binder` API that understands the structure of your configuration data and when a particular key will have one type and when it will have another.
