### ISSUE TITLE
Review hints for introspection/invocation use

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32241]
Whilst working on https://github.com/spring-projects/spring-boot/commit/44f1949c5eb39e187451e1286a41c1fe4d0e7168 I noticed we has a few calls like the one in `WebApplicationType` where we used to do:

```java
hints.reflection().registerType(TypeReference.of(typeName), (hint) -> {
});
```

It's possible that this hint was added when the API would pick invoke if no consumer was specified and the consumer was added to ensure introspect is used. The hint API was changed for consistency so it's possible that we may have accidentally changed a few hints to invoke where introspect would be enough.

**Comment by snicoll** [comment]
> It's possible that this hint was added when the API would pick invoke if no consumer was specified and the consumer was added to ensure introspect is used

`registerType` is not affected by this at all. What you mention was for `registerMethod` & `registerConstructor`.
