### ISSUE TITLE
Not able to override saml2.ClockSkew value (default is 5 m)  in Validation Context of OpenSaml4AuthenticationProvider, keeping default params  

### ISSUE THREAD

**Issue by babita-verma** [spring-projects/spring-boot#32257]
```java
authenticationProvider.setAssertionValidator(OpenSaml4AuthenticationProvider
            .createDefaultAssertionValidator(assertionToken -> {
                Map<String, Object> params = new HashMap<>();
                params.put(CLOCK_SKEW, Duration.ofMinutes(10).toMillis());
                // ... other validation parameters
                return new ValidationContext(params);
            })
    );
```

This method will create new ValidationContext with only CLOCK_SKEW param. But i want a way to override the default Validation context and update the clockskew value. 
Because this way i am missing all other context fields for eg : saml2.SubjectConfirmation.ValidInResponseTo, Which is difficult to generate locally and add in params.

So we will prefer a way to add or override the existing validation Context .

**Comment by wilkinsona** [comment]
This is out of Spring Boot's control as `OpenSaml4AuthenticationProvider` is part of Spring Security. Please open a [Spring Security issue](https://github.com/spring-projects/spring-security) if you would like to suggest an improvement to its API.
