### ISSUE TITLE
Enable PaketoBuilderTests on Java 18

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32296]
They're currently disabled due to `@EnabledForJreRange(min = JRE.JAVA_8, max = JRE.JAVA_17)`.

**Comment by wwx412775** [comment]
why is that？ what can i do for you?
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.enterprise:com.gradle.enterprise.gradle.plugin:3.10.3')
  Searched in the following repositories:
    MavenRepo
    Gradle Central Plugin Repository
    maven(https://repo.spring.io/release)
    maven2(https://repo.spring.io/snapshot)

**Comment by wwx412775** [comment]
This problem is my local configuration problem
