### ISSUE TITLE
Enable LoaderIntegrationTests with Java 19 once a liberica docker image is available

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#32295]

**Comment by wilkinsona** [comment]
Duplicates #32289.

**Comment by wilkinsona** [comment]
Bellsoft have published their Java 19 releases on GitHub, but have yet to make the Docker image available. To avoid holding up #32289, let's use this issue update `LoaderIntegrationTests` later.

**Comment by snicoll** [comment]
Closing in favor of PR #32501
