### ISSUE TITLE
Consistently document default configuration key value

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3230]
The appendix with the list of configuration keys currently document either the _default value_ or an _example value_. This can be confusing for others to know who is which.

We had already some discussion (see #/3160) that seems to indicate that we want to only document the default value. Since we have a tool to list the default value of each key, we could use it to upgrade this part of the doc (and therefore remove the places where we put a sample value).

Do we lose anything if we don't put a default value? Should we maybe put a default value anyway? (we should probably change the format in that case).

**Comment by philwebb** [comment]
Using the default probably makes most sense I think. I guess my only concern is that the appendix might become a bit noisy.

**Comment by snicoll** [comment]
compared to being incomplete/inconsistent now? (I am not sure I follow)

**Comment by snicoll** [comment]
We went with both actually, so something like this

```
my.key=defaultValue # the description. For instance 42
```

This allows to quickly spot a difference between the default value and '42' (an example value).
