### ISSUE TITLE
Some Spring-Boot Actuator endpoints not working with native compiled image (Spring Native integration)

### ISSUE THREAD

**Issue by jdbcplusnet** [spring-projects/spring-boot#32331]
I found the following problem with Spring Native (GraalVM) and some Spring-Boot Actuator endpoints:

At least the following Spring-Boot Actuator endpoints not working:

- /actuator/configprops
- /actuator/loggers

The problem seems to be related to ObjectMapper and some info is not available in runtime for this endpoints.
I have solved by using my own ObjectMapper and custom LoggingEndpoint class:

![image](https://user-images.githubusercontent.com/74903597/190137012-377e9df9-468d-49cf-a715-13957094bad4.png)

For instance the following java code in the LoggingEndpoint class is **not** returning any info about loggers (always returns empty data {})

![image](https://user-images.githubusercontent.com/74903597/190136897-69b556c6-8b2f-4493-8e79-0d02e64b1ef6.png)

I was using the following versions:

- Spring-boot and Spring-Boot Actuator *2.7.1*
- Spring Native plugin:

![image](https://user-images.githubusercontent.com/74903597/190137296-f7926e52-8aa0-45c9-8198-83e97b5b36ad.png)

- GraalVM 22.1.0 Java 11 CE over Ubuntu 20.04

I guess the Spring-Boot Actuator is not really ready for Spring Native.

**Comment by snicoll** [comment]
Thanks for the report but Spring Native is [an experimental project](https://github.com/spring-projects-experimental/spring-native) and is not managed here. We're moving those features to Spring Boot 3 (in milestone phase at the moment). Please give a Spring Boot 3 snapshot a try if you can with `./mvw -Pnative package`. We can reopen and have a look if that is still failing.
