### ISSUE TITLE
adopt and manage spring-integration-java-dsl version

### ISSUE THREAD

**Issue by srnm** [spring-projects/spring-boot#3234]
Currently my pom.xml must declare
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-java-dsl</artifactId>
            <version>1.0.1.RELEASE</version>
        </dependency>

It would be nice if spring-boot managed the version, as with other dependencies.

**Comment by wilkinsona** [comment]
Spring Boot only provides dependency management for modules that it depends upon. If you want dependency management for a more complete set of the various Spring projects, you should use [Spring IO Platform](http://platform.spring.io/platform/). It provides dependency management for `spring-integration-java-dsl:1.0.1.RELEASE` in its latest release (1.1.2.RELEASE).
