### ISSUE TITLE
Upgrade to postgresql 42.4.0

### ISSUE THREAD

**Issue by kocacinargiray** [spring-projects/spring-boot#32353]
postgresql driver have some bug. Pls can you update 42.4.0-release version. 
Because of this bug "fix: use Locale. ROOT for toUpperCase() toLowerCase() calls". More details;

https://jdbc.postgresql.org/changelogs/2022-06-09-42.4.0-release/

Have a great day.

**Comment by snicoll** [comment]
Thanks but, as stated in the issue template, we don't need issues for dependency upgrade as we have a semi-automated process that takes care of it.
