### ISSUE TITLE
Add setStrictServletCompliance parameter to config for StandardServletMultipartResolver

### ISSUE THREAD

**Issue by Gleydar** [spring-projects/spring-boot#32394]
Hi, 

I am using multipart/mixed requests in my spring project and needed to configure the StandardServletMultipartResolver to have setStrictServletCompliance to be set to "true" to avoid it trying to parse the parts of the request. Parsing would cause a timeout/empty body when accessing via the InputStream due to the missing "name" field, depending on the circumstances.

I think this should be a good solution, as setResolveLazily wouldn't prevent access to the parts of the request and then causing the timeout later. 

Would it possibly be a good idea to add the paramter to the config? I have prepared a fork including this change [here](https://github.com/Gleydar/spring-boot/blob/feature/strictServletCompliance/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/MultipartAutoConfiguration.java), however, I'm unsure if I have added the parameter at the right place in the code.

**Comment by wilkinsona** [comment]
@Gleydar Thanks for raising this. Your changes look go to me so far. Would you like to update `MultipartAutoConfigurationTests.java` to test the new property and then open a pull request?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Gleydar** [comment]
Sorry for not commenting sooner, I was kinda busy the last few weeks. I have added the test https://github.com/Gleydar/spring-boot/commit/96d6f1149152648601dc82af3c4cb5a37b1e28d1 here, but still have to validate that it actually works on my linux machine at home. 
Would you recommend more tests, or do you suppose that this method should suffice?

**Comment by wilkinsona** [comment]
Thanks for the update. I think that test will suffice.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
