### ISSUE TITLE
Property to set temporary folder

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3242]
Hi,

I noticed there's only one property for Tomcat where the /tmp folder is located.
In my case I am using Undertow, so a good option would set a generic spot where all temporary folders could be stored, like the System.getProperty("java.io.tmpdir") works.

```
server.tomcat.basedir=/tmp
```

To have something like:
```
server.tmp=/tmp
```

**Comment by spencergibb** [comment]
but `server.tomcat.basedir` doesn't reference the system temp directory, it references where tomcat runs.

**Comment by ofbizbrazil** [comment]
Ok. It would be nice to have a property to set where is located tmp folder of the application.

**Comment by philwebb** [comment]
I prefer that keep using the system defined temp directory rather than define our own property. Other libraries are likely to call `System.getProperty("java.io.tmpdir")` anyway so we'd just end up with an odd mix of temp files in different places.
