### ISSUE TITLE
Allow upgrade candidates to be filtered out when running bomr

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32457]
2.6.x's dependencies are currently up-to-date, but running Bomr produces the following upgrade suggestions:

```
Jaybird 4.0.6.java8:
  1: 4.0.6.java11 (some modules are missing: org.firebirdsql.jdbc:jaybird-jdk18)
Enter selection (default: 4.0.6.java8) [1..1] 

Kotlin Coroutines 1.5.2:
  1: 1.5.2-native-mt
Enter selection (default: 1.5.2) [1..1] 

MSSQL JDBC 9.4.1.jre8:
  1: 9.4.1.jre8-preview
  2: 9.4.1.jre11
  3: 9.4.1.jre11-preview
  4: 9.4.1.jre16
  5: 9.4.1.jre16-preview
Enter selection (default: 9.4.1.jre8) [1..5] 

Oracle Database 21.3.0.0:
  1: 21.4.0.0.1
  2: 21.6.0.0.1
Enter selection (default: 21.3.0.0) [1..2] 
```

Oracle Database is being tracked by https://github.com/spring-projects/spring-boot/issues/29928, however understanding 5 digit versions won't address the others. It would be useful to be able to filter out certain versions based on their ending, configured on a per-library basis. For example, Jaybird could filter out versions ending with `.java11` and Kotlin Coroutines could filter out versions ending with `-native-mt`. The goal is for no upgrades to be suggested when there are no upgrades to be made.

**Comment by snicoll** [comment]
GraphQL has 500+ releases with a timestamp that I'd love to see filtered as well.

**Comment by wilkinsona** [comment]
Some examples of the GraphQL versions:

- `2018-11-15T21-34-13-6aa96be-ignored-chars`
- `2021-05-03T08-53-12-8f1ec444`
- `230521-nf-execution`

**Comment by mhalbritter** [comment]
I created a PR where i sketched a solution for at least the original problem from Andy. This doesn't tackle the GraphQL problem.

https://github.com/spring-projects/spring-boot/pull/33815
