### ISSUE TITLE
Adapt to HttpComponentClientHttpRequestFactory changes

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#32461]
As of spring-projects/spring-framework#28925, Spring Framework doesn't configure the Apache HttpComponents client 4.x, as this generation is not maintained anymore. The implementation has switched to using the [httpclient5](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5) generation.

Besides adapting our auto-configuration and various tests, we also need to consider:
* how we should adapt our `RestTemplateBuilder` in light of the [deprecation of the `setReadTimeout` method on the request factory](https://github.com/spring-projects/spring-framework/blob/990a34074ac609e259149c993d6cc308ad9a7a88/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequestFactory.java#L150-L160)
* whether we want to completely remove our usage of this client (in devtools, buildpacks and CLI support)
* whether dependency management for the 4.x generation is still required as a result

The 5.1.x documentation has interesting bits of documentation about [migrating to the "classic" API](https://hc.apache.org/httpcomponents-client-5.1.x/migration-guide/migration-to-classic.html) as well as typical [client usage examples](https://hc.apache.org/httpcomponents-client-5.1.x/examples.html).

This change should be reflected in our own migration guide.

**Comment by wilkinsona** [comment]
I've labeled this as an enhancement as I think we'll want it to be listed in the changelog.
