### ISSUE TITLE
/env endpoint should have better sanitize default for keys

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3248]
If you deploy a Spring Boot app on cloudfoundry, the credentials of services are visible by default. We should review our defaults so that those are hidden as well (on top of the current usual suspect).

start.spring.io has a custom config already since we bind to redis now.

**Comment by lejeunen** [comment]
As of now Actuator's Sanitizer default initialisation target keys ending with "password", "secret", "key".

Many CF services also provide some kind of URI in the VCAP variables, and the password appears there as well. An easy solution would be to inventory all keys of existing CF services containing such URI, and to add the necessary patterns to Sanitizer default.

Another way to go would be to add Sanitizing based on the values (as opposed to keys), and detect the authority par of URI with a RegExp, i.e. detecting //user:password@ and sanitizing the password, leaving the rest of the URI intact. Not sure if this is a good idea though...

**Comment by lejeunen** [comment]
Looking at a few CF services, it seems many of them use keys ending with "uri" or "url", so adding these 2 would probably cover a majority of the current services available in CF marketplace.

**Comment by snicoll** [comment]
@ping dsyer

**Comment by philwebb** [comment]
I think you mean ping @dsyer :)

**Comment by dsyer** [comment]
I'm not aware of any actual secrets in "uri" and "url" variables, and hiding all of them would significantly reduce the usefulness of the endpoint. I agree we should obscure "VCAP_SERVICES" (blanket hide as first step, maybe find a way to blank out only bits of it later).

**Comment by lejeunen** [comment]
Here are a few examples

    vcap.services.ElephantSql-free.credentials.uri: "postgres://iipyogtc:PWkjjSNBoTcmMlIVsRZbINY4xuavYnQi@babar.elephantsql.com:5432/iipyogtc"
    vcap.services.amqp-free.credentials.uri: "amqp://yachpekq:FediFg1YHgKAPSrAgK2RhqozwfjHaeWU@owl.rmq.cloudamqp.com/yachpekq"
    vcap.services.amqp-free.credentials.http_api_uri: "https://yachpekq:FediFg1YHgKAPSrAgK2RhqozwfjHaeWU@owl.rmq.cloudamqp.com/api/"
    vcap.services.cleardb-free.credentials.uri: "mysql://bf204014270055:1edd1405@us-cdbr-iron-east-02.cleardb.net:3306/ad_9b03ed411cdd770?reconnect=true",
    vcap.services.cleardb-free.credentials.jdbcUrl: "jdbc:mysql://bf204014270055:1edd1405@us-cdbr-iron-east-02.cleardb.net:3306/ad_9b03ed411cdd770"

I already have deleted all these services so it's normal if you can't connect to them but you get the idea.

**Comment by dsyer** [comment]
I see. All those would be better hidden with a pattern based on "credentials" (IMO), or even "vcap" and "credentials", to avoid hiding other URLs that might not be sensitive.

**Comment by snicoll** [comment]
@philwebb oh wow. That's what happens when you do three things at the same time :)

**Comment by snicoll** [comment]
I guess having guidelines on the CF side to name sensitive stuff consistently is too much to ask?

**Comment by dsyer** [comment]
Yes, the ship has definitely sailed on that one. They are at least consistent in one important way: the use of "credentials" in the property name.
