### ISSUE TITLE
`spring.factories` does not support autowiring in `SpringBoot-M5`

### ISSUE THREAD

**Issue by livk-cloud** [spring-projects/spring-boot#32481]
> When I upgraded to `SpringBoot-M5`, I found that some autowiring has failed, such as `mybatis-spring-boot-starter`, these are the autowiring implemented by `spring.factories`

**Comment by bclozel** [comment]
Looks like this was due to #29699

**Comment by livk-cloud** [comment]
> 看起来这是由于#29699

> Thanks for your answer, I have confirmed this from both the source code and the wiki
