### ISSUE TITLE
RequestAttributes.get('path') is null in error page when running spring-boot project in a tomcat.

### ISSUE THREAD

**Issue by chanjarster** [spring-projects/spring-boot#3249]
Hello, I got a problem when run the spring-boot project in a tomcat (8.0.23).

If the controller throws an exception, ``RequestAttributes.get('path')`` is null in error page.

I debugged into ``DefaultErrorAttributes#addPath`` method and found that ``javax.servlet.error.request_uri`` is missing in the ``HttpServletRequest`` attributes.

But everything is ok if run the project in a standalone way.

And I create a github repository to demonstrate this: 

https://github.com/chanjarster/spring-boot-error-handler-bug

More details are in repository's README.md

**Comment by wilkinsona** [comment]
Thanks for the sample project

**Comment by chanjarster** [comment]
@wilkinsona Thanks for the fix.
