### ISSUE TITLE
Rename spring.view.* to spring.mvc.view.*

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3250]
We have `@Value` injection in  `WebMvcAutoConfigurationAdapter` for the following keys: `spring.view.prefix` and `spring.view.suffix`. That `spring.view` namespace would be better placed in our current `spring.mvc` area

Something like `spring.mvc.view.prefix` and `spring.mvc.view.suffix`

It is also used in `JspTemplateAvailabilityProvider` but it does not seem to be documented at all in the meta-data (which is a smell something is not right).

**Comment by philwebb** [comment]
Agreed, we should move those. I guess we could support both for a while if we're worried about the upgrade path.

**Comment by philwebb** [comment]
Reopening to remind me to put some notes in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M2-Release-Notes
