### ISSUE TITLE
Upgrade Jakarta Annotations API to 2.1.1

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-boot#32523]
I'm working on upgrading JHipster to use Spring Boot 3 M5 from 2.7.3. In the processs, I've been renaming a lot of dependencies from `javax` to `jakarta`.

Most things have worked well, except for the annotation-api dependency. With the javax version, there is a `@Nullable` annotation. This doesn't exists in the 2.0.0 version of jakarta that Spring Boot 3 depends on. 

Upgrading to 2.1.1 solves the problem.

Related: https://github.com/jhipster/jhipster-bom/pull/986

**Comment by wilkinsona** [comment]
We can't upgrade to Jakarta Annotations 2.1, I'm afraid. 2.1 is part of Jakarta EE 10 but our baseline for 3.0 is EE 9. As far as I can tell `@Nullable` is new in 2.1 and `javax.annotation.Nullable` doesn't exist in `jakarta.annotation-api:1.3.5`. From what I've seen, most projects that use it have been depending on the findbugs JSR-305 jar.
