### ISSUE TITLE
I can't find TomcatDataSourceConfiguration class any more!

### ISSUE THREAD

**Issue by devchenpy** [spring-projects/spring-boot#3252]
i ever used TomcatDataSourceConfiguration to create multi data source, convenient and easy, when i upgrade the spring boot to 1.2.3 , i was confused, the class has been removed

**Comment by snicoll** [comment]
Does [this section in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources) help? 

Please use stackoverflow for questions like that.

**Comment by devchenpy** [comment]
ok, it works. thanks! i remember the tip. but the every spring boot upgrade the version, there are so many big changes. it means a huge challenge for us, if we want to update the spring boot version which we used in our core logic business as follow
