### ISSUE TITLE
Failing calls to reactive health indicators are not logged

### ISSUE THREAD

**Issue by jGleitz** [spring-projects/spring-boot#32527]
In https://github.com/spring-projects/spring-boot/issues/22632, it was decided to log `WARN` messages whenever a `HealthIndicator` reports a status of `DOWN` _and_ adds an exception to the builder. This was implemented in `AbstractHealthIndicator`, but not in `AbstractReactiveHealthIndicator`. `AbstractReactiveHealthIndicator` still only logs if `doHealthCheck` throws or returns an error Mono. 

For the same reasons as in https://github.com/spring-projects/spring-boot/issues/22632, and for reasons of consistency, `AbstractReactiveHealthIndicator` should also log a WARN message when `doHealthCheck` returns a Mono that resolves to a Health with status `DOWN` and an exception.

**Comment by wilkinsona** [comment]
@snicoll and I have discussed this and we think it should be treated as a bug of omission. The logging should have been added in 2.6 as part of #22632.

**Comment by mhalbritter** [comment]
I've created a PR #33774 for this.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-projects/spring-boot/issues/32527
