### ISSUE TITLE
ConstrcutorBinding is missing either RECORD_COMPONENT or TYPE @Target

### ISSUE THREAD

**Issue by wind57** [spring-projects/spring-boot#32532]
In version `spring-boot-3.0.0-20220927.210028-840`, ConstructorBinding is defined as:

```
@Target(ElementType.CONSTRUCTOR)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface ConstructorBinding {

}
```

So annotating a `record` does not work. 

I've checked a slightly lower version, for example `2.7.2` and the definition there is:

```
@Target({ ElementType.TYPE, ElementType.CONSTRUCTOR })
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface ConstructorBinding {

}
```

Is this expected? Should it be the same in `3.0.0`?

thank you.  

P.S. I am trying to simplify some configs in `spring-cloud-kubernetes` and this is how I noticed this.

**Comment by wilkinsona** [comment]
This is covered in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Release-Notes#constructingbinding-no-longer-needed-at-the-type-level).
