### ISSUE TITLE
Upgrade Snakeyaml Managed Dependency version to address vulnerabilities reported

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-boot#32565]

**Comment by syedyusufh** [comment]
Snakeyaml dependency version was not upgraded in last 2 minor release of Spring Boot 2.7

**Comment by snicoll** [comment]
@syedyusufh please review the issue tracker, in particular when [an issue](https://github.com/spring-projects/spring-boot/issues/32221) is pinned that describes why we're not upgrading.
