### ISSUE TITLE
Spring Boot 3 milestone 5 EnableAutoConfiguration spring.factories

### ISSUE THREAD

**Issue by AihiAhazi** [spring-projects/spring-boot#32566]
Starting with Spring Boot 3 M5 the "org.springframework.boot.autoconfigure.EnableAutoConfiguration" auto-configurations registration from spring.factories file is no longer working. Released with 2.7 (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-autoconfiguration-annotation) a new file 'META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports' was introduced, however, for backwards compatibility, entries in spring.factories will still be honored.
The release notes for milestone 5 don't mention any changes related to removing the backward compatiblity or general auto-configuration changes at all.

After updating from milestone 4 to 5 the registrations from spring.factories file were no longer proccessed and I'd to replace it the new AutoConfiguration.imports file.

My question now is the removal of the backward compatiblity wanted but not documented or is it a bug?

**Comment by philwebb** [comment]
We cover it in the release notes [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration).
