### ISSUE TITLE
Migrate to common concourse-release-scripts

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32577]
I think we can remove our own in favor of https://github.com/spring-io/concourse-release-scripts

**Comment by wilkinsona** [comment]
https://github.com/wilkinsona/spring-boot/tree/gh-32577

We need an 0.4.0 release to pick up some enhancements:

- https://github.com/spring-io/concourse-release-scripts/issues/27
- https://github.com/spring-io/concourse-release-scripts/issues/28
