### ISSUE TITLE
Allow user to replace auto-configured Spring Data JDBC beans with their own

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#32571]
Spring Data JDBC does not have a `JdbcDataConfiguration`. Rather we only have an auto-configuration for the repositories support that brings an extension of `org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration`. I've noticed this when looking at the `ManagedTypes` support new for replacing classpath scanning in AOT scenario.

**Comment by wilkinsona** [comment]
Having discussed this with @mp911de, the main problem is that Boot sub-classing `AbstractJdbcConfiguration` prevents users from providing their own replacement for any of the beans that it defines. We can overcome this by overriding the inherited `@Bean` methods and annotating them with `@ConditionalOnMissingBean` as `EnableWebMvcConfiguration` already does in a few places for some of MVC's beans.
