### ISSUE TITLE
Enhancement-StringBuilder to provide replace(CharSequence target, CharSequence replacement) like String which will make it more easier to manipulate existing StringBuilder instead of creating new for these kind of replacement.

### ISSUE THREAD

**Issue by Shivangip285** [spring-projects/spring-boot#32584]

**Comment by wilkinsona** [comment]
I'm guessing this was opened in error as I can't see any direct link to Spring Boot. @Shivangip285 if that's not the case, please provide some more details and we can take another look.

**Comment by Shivangip285** [comment]
Hello Andy,
                I had been recently working on a project where we were
producing many events with unique identifier as string or number. For
string we have inbuilt thing like uuid but no such thing for unique number,
though we have used a custom function for it , but I had been wondering why
we don't have something like this in spring boot, are we planning to have
some feature in future. Please let me know if in case you are planning to
have something like this would like to contribute.
Thanks and regards
Shivangi Pandey

**Comment by philwebb** [comment]
@Shivangip285 We're not planning to add anything like that to Spring Boot itself. It feel out of scope for this project.

**Comment by Shivangip285** [comment]
Ok, thanks.
