### ISSUE TITLE
Add cache auto-configuration for Gemfire

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3258]
Gemfire has a `GemfireCacheManager` that we could support as well.

**Comment by snicoll** [comment]
We currently do not support Gemfire directly in Boot since the dependency is not available on maven central. We could do so reflectively but the added-value would be very poor. Besides, that part will be aligned with Apache Geode so we prefer to revisit this issue once a first public milestone of Geode is available.

**Comment by snicoll** [comment]
We discussed this with @jxblum several times and we're taking a different direction, with the gemfire support being hosted outside of boot.

**Comment by jxblum** [comment]
@snicoll - Ah, no.  "Being hosted outside of boot" has not been definitively decided and neither has the support for Pivotal GemFire vs. Apache Geode.  So, I would appreciate it if this was not closed given that I put the effort into doing the work.

**Comment by jxblum** [comment]
@snicoll - Ah, no... "the gemfire support being hosted outside of boot"... has not been definitively decided nor has Boot's support for Pivotal GemFire vs. Apache Geode.
