### ISSUE TITLE
Allow application to process failures in CommandLineRunners

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#326]
`SpringApplication.runCommandLineRunners()` simply goes through runners and then throws an `IllegalStateException` if something goes wrong.

I have a dedicated support on Hadoop Yarn to run batch jobs and I'm now trying to make it compatible with Boot. Effectively it would not make sense to use build-in functionality in my yarn code to run batch jobs if Boot can already do this. That's something a user would expect if using boot on Hadoop Yarn.

I'm using `CommandLineRunner` called `AppmasterLauncherRunner` to start a component on Yarn which is then able to dispatch partitioned steps on a hadoop cluster. For now this runner is run before boot is asking `JobLauncherCommandLineRunner` to do its tasks. If this batch job run handled by `JobLauncherCommandLineRunner` fails, `SpringApplication` then handles that error and closes the context.

I believe I'm somehow able to work around these issues by overriding some `SpringApplication` functionality, but I think we could make this easier for an end-user. Like in my case, I need to catch if something failed to be able to properly close my Yarn AppMaster which would then notify Hadoop that final status is failed.

If fine for `SpringApplication` to throw white towel in a ring if context start/refresh fails, but because CommandLineRunners are likely integration point for users to hook in their own functionality, we should allow them to process if something goes wrong.

**Comment by snicoll** [comment]
Couldn't you listen for `ApplicationFailedEvent`?

**Comment by jvalkeal** [comment]
@snicoll this was on early stages of boot and at that time we really didn't have that much facilities to hook on. At least from my point of view this ticket can be closed.

**Comment by snicoll** [comment]
Thanks for the feedback @jvalkeal!
