### ISSUE TITLE
Killing `mvn spring-boot:run` does not kill child process

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-boot#32607]
Killing `./mvn spring-boot:run` process with `SIGKILL` signal does not kill Spring Boot application running as child process.

- Spring Boot version: 3.0 M5
- Java version:
```
openjdk 17 2021-09-14 LTS
OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS)
```

Steps to reproduce:

1. Use any Spring Boot application with `spring-boot-starter-web`
2. Start application with `./mvnw spring-boot:run`
3. Find the PID of started Maven process (for example with `ps | grep "spring-boot:run"`)
4. Kill Maven process `kill <pid>`.
5. Spring Boot application started with `./mvnw spring-boot:run` is still running and the port (`8080` by default) is still occupied.

As far as I can see this issue did not exist in 2.x and 3.0 until version M5 so it must have been introduced between M4 and M5.

**Comment by wilkinsona** [comment]
Thanks for noticing and reporting this, @maciejwalkowiak.
