### ISSUE TITLE
configprops endpoint does not display DataSize properties correctly

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32613]
```json
"spring.servlet.multipart-org.springframework.boot.autoconfigure.web.servlet.MultipartProperties": {
    "inputs": {
        "enabled": {},
        "fileSizeThreshold": {},
        "maxFileSize": {},
        "maxRequestSize": {},
        "resolveLazily": {}
    },
    "prefix": "spring.servlet.multipart",
    "properties": {
        "enabled": true,
        "fileSizeThreshold": {},
        "maxFileSize": {},
        "maxRequestSize": {},
        "resolveLazily": false
    }
}
```

With thanks to @ahoehma on Gitter, `maxFileSize` and `maxRequestSize` are both `DataSize` properties but the values are missing from `properties`. It looks like there is also a problem with `inputs` as the output above was generated with `spring.servlet.multipart.max-file-size=10MB` in `application.properties` but the input for `maxFileSize` is empty.

**Comment by scottfrederick** [comment]
Closing in favor of #32645
