### ISSUE TITLE
Tests for spring-boot-gradle-plugin cannot be run in Eclipse due to missing spring-boot-loader.jar

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32625]
Running spring-boot-gradle-plugin tests with Eclipse fails out of the box because the `spring-boot-loader.jar` resource is missing. If you update `spring-boot-loader-tools` to include `build/generated-resources/main` as a source folder then the tests pass.

**Comment by wilkinsona** [comment]
This has been bugging me too but I'm not totally sure what's going on.

> If you update spring-boot-loader-tools to include build/generated-resources/main as a source folder

That's what this bit of the build.gradle for loader tools is already supposed to do:

```groovy
sourceSets {
	main {
		output.dir(generatedResources, builtBy: [layerToolsJar, reproducibleLoaderJar])
	}
}
```
