### ISSUE TITLE
Support setting KafkaAdmin#operationTimeout via externalised configuration

### ISSUE THREAD

**Issue by hari-mani** [spring-projects/spring-boot#32640]
I have a Spring Boot application that makes use of  Kafka via spring-kafka. Recently I have started observing timeouts while trying to fetch administrative data from Kafka using the `KafkaAdmin` class. To solve this I would like to set the `operationTimeout` property of `KafkaAdmin` via an externalised property like how `modifyTopicConfigs` or `fatalIfBrokerNotAvailable` properties are set. 
At present the only way to override the default value is to explicitly call the setter with the desired value from the application. Although this isn't much of a hassle it would be convenient if the auto configuration can automatically set the provided value from an externalised source like a YAML or properties file.

**Comment by wilkinsona** [comment]
Closing in favor of #33288. Thanks for the PR, @terminux!
