### ISSUE TITLE
Mustache support - content type is not set in Mustache View

### ISSUE THREAD

**Issue by gilles-stragier** [spring-projects/spring-boot#3265]
The content type set in the Mustache View Resolver is not set in the Mustache View.
This prevents producing something else than html using Mustache.

The __MustacheViewResolver#loadView__ method should be adapted to this

````
        @Override
	protected View loadView(String viewName, Locale locale) throws Exception {
		Resource resource = resolveResource(viewName, locale);
		if (resource == null) {
			return null;
		}
		MarkdownMustacheView view = new MarkdownMustacheView(createTemplate(resource));
		view.setApplicationContext(getApplicationContext());
		view.setServletContext(getServletContext());
		// FIXED - This was necessary to have the content type as set in the resolver
		view.setContentType(getContentType());
		return view;
	}
````

**Comment by philwebb** [comment]
@dsyer seems sensible, any side effects that you can foresee?

**Comment by dsyer** [comment]
I thought there was a base class for the resolver that handled all of that in Spring MVC.

**Comment by philwebb** [comment]
`UrlBasedViewResolver.buildView()` ?

**Comment by dsyer** [comment]
I think I was thinking of `AbstractTemplateViewResolver.buildView()`, but neither sets the content type it seems.

**Comment by snicoll** [comment]
Indeed, the value is actually customized in the `MustacheViewResolver` but nothing actually sets the value in the view.
