### ISSUE TITLE
Upgrade to Hazelcast 3.5

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3267]

**Comment by dgomesbr** [comment]
from the Hazelcast docs:

src: http://docs.hazelcast.org/docs/latest-dev/manual/html/upgradingfrom2x.html
> **Upgrading from 3.x**
> In this section, we list the changes what users should take into account before upgrading to latest Hazelcast from 3.x versions.

> **Introducing the spring-aware element:**
> Before the release 3.5, Hazelcast uses SpringManagedContext to scan SpringAware annotations by default. This may cause some performance overhead for the users who do not use SpringAware. This behavior has been changed with the release of Hazelcast 3.5. SpringAware annotations are disabled by default. By introducing the spring-aware element, now it is possible to enable it by adding the <hz:spring-aware /> tag to the configuration. Please see the Spring Integration section.

which redirects us to this reading: http://docs.hazelcast.org/docs/latest-dev/manual/html/springintegration.html

> *Spring Managed Context with @SpringAware*
> Hazelcast Distributed Objects could be marked with @SpringAware if the object wants:
> * to apply bean properties,
> * to apply factory callbacks such as ApplicationContextAware, BeanNameAware,
> * to apply bean post-processing annotations such as InitializingBean, @PostConstruct.
 
> Hazelcast Distributed ExecutorService, or more generally any Hazelcast managed object, can benefit from these features. To enable SpringAware objects, you must first configure HazelcastInstance using hazelcast namespace as explained in the Spring Configuration section and add <hz:spring-aware /> tag.

The [samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-configuration) aren't so user-friendly, but I'll submit a PR after testing it locally.

**Comment by dgomesbr** [comment]
Preliminary commit seems to run with tests without problems.

```
Results :
Tests run: 813, Failures: 0, Errors: 0, Skipped: 3
```
