### ISSUE TITLE
`JacksonProperties.serialization` doesn't appear in `/configprops` endpoint

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#3269]
When I added the following property in `application.properties`:

```
spring.jackson.serialization.indent_output=true
```

it doesn't appear in `/configprops` endpoint as follows:

```
  "spring.jackson.CONFIGURATION_PROPERTIES" : {
    "prefix" : "spring.jackson",
    "properties" : {
      "propertyNamingStrategy" : null,
      "dateFormat" : null,
      "serializationInclusion" : null,
      "jodaDateTimeFormat" : null
    }
  },
```

See https://github.com/spring-projects/spring-boot/pull/2783 for the previous discussion.

**Comment by snicoll** [comment]
I am not sure which issue fixed this but this bug is oudated now. I tried with the actuator sample and that worked.
