### ISSUE TITLE
init.d boot/loader/tools/launch.script env parameter defaults

### ISSUE THREAD

**Issue by bedge** [spring-projects/spring-boot#3271]
This is a minor wishlist item. The init.d wrapper is very cool. I'm just nitpicking.

The docs 
(http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-install.html#deployment-script-customization)
state that one can set env variables to change the defaults for things like the LOG_FOLDER.
This is not ideal for the use case where one distributes a package consisting of the war and an init.d symlink, which one can do with spring boot now:
```
%C> dpkg -c build/distributions/*deb
-rwxr--r-- bedge/0    39950188 2015-06-17 11:25 ./opt/nim/cmas/nim-cmas.war
lrw-r--r-- root/root         0 2015-06-17 11:25 ./etc/init.d/nim-cmas -> /opt/nim/cmas/nim-cmas.war
```
Any env settings that are global, so that they are present when init.d scripts are started necessarily impact all applications. 
IOW, to set the log folder for m one app, I need LOG_FOLDER exported globally in all shells.
If I have to apps I can't set the LOG_FOLDER settings differently.

I'd prefer to have the launch.script look for a file
```
/etc/default/<app name>
```
which, if exists is sourced. 

This would allow one to include an app-specific conffile for sping-boot wars that the user could override at an app specific level if needed.

**Comment by bedge** [comment]
I'm not great at adocs, but here's an attempt at the documentation update too:

```
--- a/spring-boot-docs/src/main/asciidoc/deployment.adoc
+++ b/spring-boot-docs/src/main/asciidoc/deployment.adoc
@@ -445,6 +445,9 @@ the default behavior in a script or on the command line:
  in the script.
 |===

+The above env settings can also be placed in an app-specific env file named /etc/default/myapp.
+This file will be sourced by the init.d script if it exists.
+


 [[deployment-whats-next]]
```

**Comment by spencergibb** [comment]
see #3243, I think it does what you are suggesting.

**Comment by bedge** [comment]
That works. I agree that putting it next to the jar file makes sense because the packager can symlink it wherever makes the most sense for the target OS.
