### ISSUE TITLE
Running ./gradlew bootRun does not produce color output

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32727]
We've had this previously in #747 and fixed it but it no longer appears to work.

**Comment by philwebb** [comment]
A bit of debugging shows `System.console()` is always `null` in the `BootRun` task.

**Comment by philwebb** [comment]
https://github.com/gradle/gradle/issues/1251

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/24169. We concluded then that this couldn't be fixed. Perhaps things have moved on since then? Let's re-open 24169 if that's the case and this can now be fixed.
