### ISSUE TITLE
EnvironmentTestUtils does not allow a value with `:`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3273]
The algorithm that detects the key and the value from a simple String is broken if the value contains `:` as it uses that as delimiter.

**Comment by wilkinsona** [comment]
IIRC, this works as long as you use `:` to separate keys and values, e.g. `foo:bar:baz` will be split into `foo` and `bar:baz`. If you use `=` it'll split in the "wrong" place as `:` takes precedence, e.g. `foo=bar:baz` will be split into `foo=bar` and `baz`.

**Comment by snicoll** [comment]
That's what I want to fix actually. It's quite confusing when your test does not pass because the wrong  value was injected.

**Comment by philwebb** [comment]
I'm a little worried that this might break existing tests that rely on the behavior. I think I'd rather revert on 1.2.5 and move to 1.3.0.

**Comment by snicoll** [comment]
You mean code out there using this test utility? 

I agree that backporting this in 1.2.x may not have been such a good idea. My reasoning was that I wanted to avoid a situation where a test implemented on master wouldn't pass when backporting it to 1.2.x (super hard to track down where the issue comes from).

To me it's a matter of whether we would allow `=` or `:` as part of the key. If we do, then we should revert this altogether (and document that behaviour).

**Comment by philwebb** [comment]
Actually, lets risk it. It will be only break tests so people should find it easily enough. I think you have a compelling argument regarding backports.
