### ISSUE TITLE
Simplify code that handles repository configuration in the CLI

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3275]
While fixing #3274 it became apparent that the code for handling repository configuration is more complex than it needs to be. I believe it should be possible to configure the default repositories on the `RepositorySystemSession` and remove the need for `RepositoryConfigurationFactory`.

It looks like tidying this up properly will require changing the signatures of some public classes, hence opening a separate issue rather than tackling it as part of #3274.

**Comment by joshiste** [comment]
Hey Andy,
can you include the functionality from my PR  #3270 when you have a look at this?

Regards Johannes

**Comment by wilkinsona** [comment]
@joshiste Absolutely. Thanks for the reminder.

**Comment by wilkinsona** [comment]
I'm not sure what I was looking at when I opened this issue, but what I proposed does not appear to be possible. Closing.
