### ISSUE TITLE
@Bean methods in KafkaAutoConfiguration provide less type information than they could

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32766]
As pointed out by @maciejwalkowiak in #32763, there are a number of `@Bean` methods in `KafkaAutoConfiguration` where the return type isn't as specific as it could be. For example, `kafkaConsumerFactory` always returns a `DefaultKafkaConsumerFactory` but its return type is only `ConsumerFactory`.

**Comment by philwebb** [comment]
Closing in favor of PR #32770. Thanks @YuanHao97!
