### ISSUE TITLE
Update getting started with alternative gradle instructions

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32779]
Our getting started section in the docs currently uses Maven. It would be nice to offer a Gradle version alongside it.

**Comment by vpavic** [comment]
I think that Gradle instructions should guide users to set up the Gradle Wrapper, which is the recommended way of executing Gradle builds. The change that resolved this issue has no mention of Wrapper at all.

**Comment by mhalbritter** [comment]
I intended to keep the Getting started instructions as simple as possible, and I don't think that the wrapper provides much benefit here.
