### ISSUE TITLE
HTTP 405 for POST requests with Data REST and Boot 3.0.0 RC1

### ISSUE THREAD

**Issue by uzonyib** [spring-projects/spring-boot#32835]
Following this [Data REST tutorial](https://spring.io/guides/gs/accessing-data-rest/) results in an HTTP 405 error for create / POST requests on the resource with Boot 3.0.0 RC1 (of course, `jakarta.persistence` imports are used instead `javax.persistence`).
Reverting to Boot 2.7.5 and old imports fix the problem.

**Comment by wilkinsona** [comment]
Thanks for trying RC1. As [described in the Spring Data 2022.0 release notes](https://github.com/spring-projects/spring-data-commons/wiki/Spring-Data-2022.0-(Turing)-Release-Notes-(Preview)#sorting-repositories-no-longer-inherit-from-crud-repositories), `PagingAndSortingRepository` is no longer a `CrudRepository` so the `PersonRepository` in the guide is read-only. Changing `PersonRepository` to also extend `CrudRepository<Person, Long>` fixes the problem.
