### ISSUE TITLE
Add tests for BindableRuntimeHintsRegistrar

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32831]
Whilst refactoring `ConfigurationPropertiesReflectionHintsProcessor` to `BindableRuntimeHintsRegistrar` I realized we don't seem to have any tests it.

**Comment by tumit** [comment]
Can i try to take care this issue ?

**Comment by philwebb** [comment]
That would be great. Thanks @tumit

**Comment by mhalbritter** [comment]
It's implicitly tested in `ConfigurationPropertiesBeanFactoryInitializationAotProcessorTests`.

**Comment by philwebb** [comment]
Thanks @mhalbritter. I figured we must have tested it somewhere but I couldn't find it.

**Comment by mhalbritter** [comment]
Should we move the tests to `BindableRuntimeHintsRegistrarTests` or is it fine the way it is?

**Comment by philwebb** [comment]
I did add a comment to `ConfigurationPropertiesBeanFactoryInitializationAotProcessorTests` saying it also tests `BindableRuntimeHintsRegistrar`. It was meant to be a polish commit but I accidentally did it in e6c37d698f4cece58ca3eb0ae5442a2df32af8a9 🤭.

I wouldn't mind having the `BindableRuntimeHintsRegistrar` logic tested in a `BindableRuntimeHintsRegistrarTests` just because it's a bit closer to the code and a bit more discoverable. It certainly not a pressing matter.

**Comment by philwebb** [comment]
I've copied a lot of the tests from `ConfigurationPropertiesBeanFactoryInitializationAotProcessorTests` over when merging #32851. There's some duplication now, but the tests are quick so I think it's fine.
