### ISSUE TITLE
Property to enable application output appenders

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3285]
It would be nice to have a property where we could enable all appenders available for the application.

Nowadays we only can use a custom log file to inform it, but via Spring Boot I can only enable the file appender but sadly console is still enabled by default.

So, it would be something like below example:

```
###############
### Logging ###
###############
logging.appender = console, file
logging.level.*=INFO
logging.file=log/${server.context-path}.log
```

**Comment by philwebb** [comment]
This has been requested in https://github.com/spring-projects/spring-boot/issues/1788#issuecomment-65195532, we'll track it there.
