### ISSUE TITLE
Sending extra "/" in URL returns 404 (Spring 3.0.0-RC1)

### ISSUE THREAD

**Issue by Thihup** [spring-projects/spring-boot#32864]
With Spring Boot 2.7.5, the following code works:

```java
@RestController
public class SomeController {

    @GetMapping("/health")
    public Object foo() {
        return Map.of("foo", "bar");
    }
}
```

```java
@WebMvcTest(SomeController.class)
public class SomeControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void health() throws Exception {
        mockMvc.perform(get("/health/"))
                .andExpect(status().isOk());
    }
}
```

After upgrading to 3.0.0-RC1, it fails with 404. Is this expected? Should I replace the URL in the Controller to include a slash or should I remove the slash from the test?

**Comment by scottfrederick** [comment]
This change is covered in the [`3.0.0-M4` release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M4-Release-Notes#spring-mvc-and-webflux-url-matching-changes), inclcuding instructions for re-instating the previous default behavior.

**Comment by Thihup** [comment]
Thank you! @scottfrederick
