### ISSUE TITLE
Unable to retrieve @EnableAutoConfiguration base packages with 3.0.0-RC1

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-boot#32868]
Build that fails - https://github.com/infobip/infobip-spring-data-querydsl/actions/runs/3318603483/jobs/5482733947
Source code for the test that fails - https://github.com/infobip/infobip-spring-data-querydsl/blob/spring-boot-3.0.0/infobip-spring-data-jpa-querydsl-boot-starter/src/test/java/com/infobip/spring/data/jpa/AutoConfigurationTest.java
It works on 2.7.4 (master branch) but starts failing once I switch to 3.0.0-RC1.
Here's a PR for easier comparison of changes - https://github.com/infobip/infobip-spring-data-querydsl/pull/70/files.

**Comment by vpavic** [comment]
Not sure if that's the only reason for the error you're seeing, but with 3.0 you need to list your auto-configuration classes in `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` as support for `org.springframework.boot.autoconfigure.EnableAutoConfiguration` property in `META-INF/spring.factories` was removed.

See [_7.9. Creating Your Own Auto-configuration_](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration) in the reference manual.

**Comment by lpandzic** [comment]
That was it, thank you! Test for that module passes after that change.

**Comment by wilkinsona** [comment]
Thanks, @vpavic.
