### ISSUE TITLE
Remove setting BP_NATIVE_IMAGE environment variable when building images

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#32884]
When https://github.com/paketo-buildpacks/spring-boot/issues/273 is implemented, Paketo buildpacks will build an image containing a native executable by default when invoked with a Spring Boot jar or war, there's no need for the Spring Boot Maven and Gradle plugins to set `BP_NATIVE_IMAGE` to `true` explicitly.

**Comment by mhalbritter** [comment]
We now no longer set `BP_NATIVE_IMAGE: true`. We, however, add `Spring-Boot-Native-Processed: true` to the manifest. This is read by [the Spring Boot buildpack](https://github.com/paketo-buildpacks/spring-boot), which then provides the `native-image-application` buildplan entry, which triggers [the native image buildpack](https://github.com/paketo-buildpacks/native-image).
