### ISSUE TITLE
Need to be able to configure the RemoteIpValve protocolHeaderHttpsValue setting

### ISSUE THREAD

**Issue by jstano** [spring-projects/spring-boot#3289]
It appears that the `org.springframework.boot.autoconfigure.web.ServerProperties` is missing a value for the `protocolHeaderHttpsValue` value in the `RemoteIpValve` configuration.

We're running behind a Barracuda device that is setting the value to "On", which we cannot change. I've had to override in code, which is not ideal, since we have to duplicate everything that is currently being done in the `ServerProperties` class.

**Comment by philwebb** [comment]
We should add that one but I believe you should be able to customize it using a `EmbeddedServletContainerCustomizer` rather than needing to duplicate everything in `ServerProperties`.
