### ISSUE TITLE
Document how to observe JDBC project with Spring Boot and micrometer-observations

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#32912]
It would be great for Spring Boot Documentation to mention that the [Micrometer Observations](https://github.com/jdbc-observations/datasource-micrometer) project under jdbc-observations org is the way to go as far as JDBC observations are concerned.

**Comment by mhalbritter** [comment]
Related: https://github.com/spring-projects/spring-boot/issues/32833
