### ISSUE TITLE
broken link in Spring Boot Config Data Migration Guide

### ISSUE THREAD

**Issue by dbyron-sf** [spring-projects/spring-boot#32914]
There's a link in the [Profile Specific External Configuration section of the Spring Boot Config Data Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#profile-specific-external-configuration):

> You can also check the [update documentation](https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-external-config-files)

that's not working for me.  I get a 404 from https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-external-config-files.

https://docs.spring.io/spring-boot/docs/2.4.0/reference/html/spring-boot-features.html#boot-features-external-config-files does work though.

**Comment by scottfrederick** [comment]
Thanks for letting us know. I've changed all the links on that page to reference the `current` documentaiton.

**Comment by dbyron-sf** [comment]
Thanks.  The title of the doc doesn't include 2.4, but it does seem like a document pretty specific to 2.4.  Is it safer to use 2.4.13 instead of `current`?

**Comment by scottfrederick** [comment]
The context of the document is migrating from Boot 2.3 to Boot 2.4 and later releases. I also made a few edits to make sure the "Spring Boot 2.4 and above" was clear. Since 2.4 is already a pretty old and out-of-support release, I think it's safer to use `current` for the long term.

**Comment by dbyron-sf** [comment]
Sounds good.
