### ISSUE TITLE
Switching off Boot Security requires overriding AuthenticationManager bean

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-boot#3292]
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-security.html says:

> To switch off the Boot default configuration completely in a web application you can add a bean with @EnableWebSecurity.

Unfortunately just by doing `@EnableWebSecurity` is not enough, my `configure(AuthenticationManagerBuilder auth)` method is still overriden (silently) by Spring Boot Security, additional step(s) are needed:

1. When overriding `configure(AuthenticationManagerBuilder auth)`, ensure do not call `super` (a strange pattern, IMHO)
2. Override and expose `authenticationManagerBean()` (this time have to call `super` as usual) as `@Bean`

i.e.

```java
@Configuration
@EnableWebSecurity(debug=true)
@Profile("daemon")
public class MyWebSecurityConfiguration extends
		WebSecurityConfigurerAdapter {

	@Inject
	private Environment env;

	@Override
	protected void configure(AuthenticationManagerBuilder auth) throws Exception {
		// do not call super, otherwise you'll get BeanCreationException: Error creating bean with name 'authenticationManagerBean' - org.springframework.beans.FatalBeanException: A dependency cycle was detected when trying to resolve the AuthenticationManager. Please ensure you have configured authentication.
		final String sysadminPassword = env.getRequiredProperty("security.user.password");
		auth.inMemoryAuthentication()
				.withUser("sysadmin")
				.password(sysadminPassword)
				.roles("SYSADMIN", "ADMIN", "USER");
	}

	// must be overriden and exposed as @Bean, otherwise boot's AuthenticationManagerConfiguration will take precedence
	@Bean @Override
	public AuthenticationManager authenticationManagerBean() throws Exception {
		return super.authenticationManagerBean();
	}
...
```

(an example code such as above would be good to put in the Spring Boot Security doc)

**Comment by dsyer** [comment]
I agree it's a bit more complicated than the current docs suggest. But it's more complicated than this issue suggests as well, so for the record, if you are reading this issue looking for help, all the answers are not here yet. 

The code above mixes two authentication configuration idioms. A bean of type `AuthenticationManager` represents global defaults. In contrast an `AuthenticationManagerBuilder` injected into a `configure()` method applies only to the current filter chain. Injecting an `AuthenticationManagerBuilder` using `@Autowired` is the recommended way to change the global defaults.

The default behaviour of Spring Boot, even if you use `@EnableWebSecurity`, is to define an `AuthenticationManager` bean (unless you define one yourself, and there are very many ways of doing that). Spring Boot also creates a default, global parent `AuthenticationManager`, which others can delegate to if they don't manage to authenticate an incoming request (this is the one created from the `security.user.*` configuration properties, and it isn't necessarily a `@Bean`). You can switch that off by injecting an `AuthenticationManagerBuilder` using `@Autowired` (the recommended way to set the global defaults in Spring Security documentation).

**Comment by ofbizbrazil** [comment]
I could switch off security doing at main class the exclusion:
```
@SpringBootApplication(exclude = SecurityAutoConfiguration.class) 
```

**Comment by ralscha** [comment]
I have a similar problem (Spring Boot 1.3.0.M2)

I use this security configuration

```
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
@EnableWebSecurity
class SecurityConfig extends WebSecurityConfigurerAdapter {

	@Bean
	public static DefaultRolesPrefixPostProcessor defaultRolesPrefixPostProcessor() {
		return new DefaultRolesPrefixPostProcessor();
	}

	@Bean
	public PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}

	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth,
			UserDetailsService userDetailsService, PasswordEncoder passwordEncoder)
					throws Exception {
		auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder);
	}

	@Override
	public void configure(WebSecurity builder) throws Exception {
		builder.ignoring().antMatchers("/resources/**",
				"/app.js", "/app.json", "/cache.appcache", "/index.html"
				);
	}
```

Even ```@EnableWebSecurity``` should switch off the default settings, Spring Boot adds ```/css/**```, ```/js/**```, ```/images/**``` and ```/**/favicon.ico``` to the ignoring list.

Also ```@SpringBootApplication(exclude = SecurityAutoConfiguration.class) ``` does not solve this minor problem.

```
2015-07-14 16:38:16.893  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/css/**'], []
2015-07-14 16:38:16.893  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/js/**'], []
2015-07-14 16:38:16.893  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/images/**'], []
2015-07-14 16:38:16.893  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/**/favicon.ico'], []
2015-07-14 16:38:16.893  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/error'], []
2015-07-14 16:38:16.894  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/resources/**'], []
2015-07-14 16:38:16.894  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/app.js'], []
2015-07-14 16:38:16.894  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/app.json'], []
2015-07-14 16:38:16.894  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/cache.appcache'], []
2015-07-14 16:38:16.894  INFO 5332 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/index.html'], []
```

**Comment by dsyer** [comment]
Works for me. Your example @ralscha is slightly odd in that it doesn't actually configure the `HttpSecurity`, but it doesn't ignore the default ignores when I try something like it. A complete sample project would be useful if you could put one in github for us. Also, I don't think it's relevant to this issue (which is about documenting how to switch off Spring Boot security), so please open a separate issue if you have a sample project.

**Comment by ralscha** [comment]
Sorry. I forgot to post the second part of the configuration with the http security and I forgot to send a feedback. Because I was able to solve my problem with the application properties file. I noticed that it is possible to list the ignored resources there.
```
security:
  ignored:
    - /resources/**
    - /app.js
    - /app.json
    - /cache.appcache
    - /index.html
```
This will override the defaults (/css/\*\*, /js/\*\*, /images/\*\*, /\*\*/favicon.ico).
