### ISSUE TITLE
Create a single PDF file with all the reference content

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-boot#32945]
As discussed in a meeting, we should make a single PDF file with all of the reference content.

You can assign this issue to me (and I'll try to assign it to myself).

**Comment by philwebb** [comment]
For those looking, the PDF version is linked at the very top of the HTML version. E.g. https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/ has

"This document is also available as [multiple HTML pages](https://docs.spring.io/spring-boot/docs/2.7.5/reference/html/) and as [a PDF](https://docs.spring.io/spring-boot/docs/2.7.5/reference/pdf/spring-boot-reference.pdf)."
