### ISSUE TITLE
Profile properties not loading during integration tests

### ISSUE THREAD

**Issue by dlvenable** [spring-projects/spring-boot#3294]
I'm trying to create some integration tests which run my Spring Boot application with a specified Spring profile. From my experimentation, it seems that I can set the profile, but Spring Boot does not load the properties file for that profile

```
@SpringApplicationConfiguration(classes = MyApplication.class, initializers = MyInitializer.class)
@WebIntegrationTest
@Stepwise
class MySpec extends Specification
{
}
```

```
class MyInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext>
{
    @Override
    void initialize(ConfigurableApplicationContext applicationContext)
    {
        applicationContext.getEnvironment().setActiveProfiles('test')
    }
}
```

Using the debugger I can see that the Spring `Environment` object does have my active profile. But, the properties for my profile are not loaded.

To clarify, by properties file, I mean files in resources like:
application.properties
application-test.properties

I've tried this in Spring Boot 1.2.3 and 1.2.4. I am building with Gradle and testing with Spock.

**Comment by dlvenable** [comment]
Also, I tried using the `@ActiveProfiles` annotation on the `MySpec` class, but this does not work. I did not try using the debugger to see if the profile was active, but I know the properties did not load because the application failed to start.

**Comment by wilkinsona** [comment]
It's too late to set the active profile in `MyInitializer` as `ConfigFileApplicationListener` (the class that's responsible for loading configuration from `application.properties` files) has already run by that point. You were on the right lines with using `@ActiveProfiles` instead.

What version of Spock are you using? If you're using 0.7 then, [as described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-with-spock), you need to use `ContextConfiguration` rather than `SpringApplicationConfiguration`.

**Comment by dlvenable** [comment]
Thank you for clarifying the problem with `MyInitializer`. Though, I did understand from the [documentation](http://docs.spring.io/autorepo/docs/spring/4.1.6.RELEASE/javadoc-api/org/springframework/context/ApplicationContextInitializer.html) for `ApplicationContextInitializer` that one could set the profiles: *For example, ... activating profiles against the context's environment.*

I am using Spock 1.0.

From my build.gradle:
```
    testCompile("org.codehaus.groovy:groovy-all:2.4.3")
    testCompile("org.spockframework:spock-core:1.0-groovy-2.4")
    testCompile("org.spockframework:spock-spring:1.0-groovy-2.4")
```
I tried using `ActiveProfiles` and `ContextConfiguration` and it is not working as expected. I'll do some debugging and report back whether the problem is the same.

**Comment by dlvenable** [comment]
I changed my integration test to:

```
@ContextConfiguration(loader = SpringApplicationContextLoader.class, classes = MyApplication.class)
@ActiveProfiles("development")
@WebIntegrationTest
@Stepwise
class MySpec extends Specification
```

I ran the application through the debugger and inspecting an `@Autowired Environment` I see the active profile *development* (it appears that there was an existing *test* so I changed my profile name). However, the profile properties are not being loaded for classes that need them.

**Comment by wilkinsona** [comment]
I've just tried this using, as far as I can tell, the same setup as you and it worked as expected. If you'd like me to investigate further, please put together a small sample that reproduces the problem.

**Comment by dlvenable** [comment]
I created a sample project, but was unable to reproduce the problem. Previously I had been running my tests from IntelliJ. I am now doing it from the Gradle build and it works. Oddly enough, in the sample project the tests do run from IntelliJ. So the issue here probably lies in IntelliJ.
