### ISSUE TITLE
The version of Hazelcast Hibernate is managed unnecessarily

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#32953]
We've currently got dependency management for `hazelcast-hibernate52` and `hazelcast-hibernate53` which seems a bit odd given that we require Hibernate 6. I'm not sure if `hazelcast-hibernate53` supports the `jakarta.persistence` JPA API or if it touches the JPA API at all. We should verify the situation and update/remove things as needed.

**Comment by wilkinsona** [comment]
Boot doesn't depend on Hazelcast Hibernate. We only have dependency management for it as it used to be part of the Hazelcast itself. It was then split out into a separate project with its own release cycle but [we kept our dependency management for it](https://github.com/spring-projects/spring-boot/pull/7023). With hindsight, I think this was a mistake as Boot doesn't depend on Hazelcast Hibernate. As such, we should remove our dependency management.

**Comment by vpavic** [comment]
It's been a while since I last used Hazelcast, but I agree with what's proposed here.

I suggested the same thing few years ago, as using `org.hibernate:hibernate-jcache` is IMO better option for the job, compared to Hazelcast's Hibernate modules. See https://github.com/spring-projects/spring-boot/issues/15624#issuecomment-453065069.

**Comment by wilkinsona** [comment]
Thanks, @vpavic. I've mentioned using `hibernate-jcache` instead in [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-RC2-Release-Notes#dependency-management-for-hazelcast-hibernate-removed).

**Comment by vpavic** [comment]
After taking another look, that should probably be `org.hibernate.orm:hibernate-jcache` these days, as Hibernate ORM has relocated to a new group id for 6.x.

**Comment by wilkinsona** [comment]
I've updated that. Thanks again.
