### ISSUE TITLE
Question about maven release

### ISSUE THREAD

**Issue by lnsane** [spring-projects/spring-boot#32981]
this is  2.7.X
![1667442835372](https://user-images.githubusercontent.com/20310872/199637499-0dfa12b8-8172-451e-9fff-c49cee55402f.png)

this is 2.1.X
![1667442962364](https://user-images.githubusercontent.com/20310872/199637652-5f3c985d-0bb2-4bc7-9ebf-64b610fd7c8a.png)

Removed the relativePath tag? that's amazing ！how did you do that?

**Comment by bclozel** [comment]
We ported our build to Gradle in 2.3.0 (see #19608), so the POMs we're publishing are generated, not actually used to build the project. This can explain some differences in their format; but everything needed by consumers should be available still.

For further questions, please use StackOverflow.
