### ISSUE TITLE
Expose a Kafka property to control the autoStartup of all listeners on all container factories

### ISSUE THREAD

**Issue by frosiere** [spring-projects/spring-boot#32984]
The autoStartup property of a listener is currently exposed at `ContainerProperties` and also on the `KafkaListener` annotation levels.

In some cases, it may be interesting to set this property at configuration level for all listeners in all configured factories.

To make it work, a new property should be added at listener level. See `KafkaProperties#Listener` (spring.kafka.listener.auto-startup=true|false) + mapping in the `ConcurrentKafkaListenerContainerFactoryConfigurer`.

More details about the issue can be found here
https://stackoverflow.com/questions/74219728/expose-a-listener-property-to-control-the-autostartup-of-all-listeners-on-all-co/74222770#74222770

**Comment by stephen-murby** [comment]
Just trying to work out the development process, it seems I need to update the `ContainerProperties` class in spring-kafka before I can add the relevant mapping to `ConcurrentKafkaListenerContainerFactoryConfigurer`.

Do I need to do the minor spring-kafka change first and have it merged?

**Comment by frosiere** [comment]
Issue can be assigned to me, I can contribute by dropping a PR.

@stephen-murby, the idea is to set the autoStartup property directly on the container factory, not on the ContainerProperties.

**Comment by snicoll** [comment]
Closing in favor of PR #33082 - Thanks François!
