### ISSUE TITLE
Throw `ContextLoadException` from `SpringBootContextLoader`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#32995]
#31793 introduced a custom `ApplicationContextFailureProcessor`; however, that is half of the support needed for processing `ApplicationContext` load failures.

The other half is the new requirement that a `SmartContextLoader` catch any exception thrown in `loadContext()` and throw it wrapped in a `ContextLoadException`.

See https://github.com/spring-projects/spring-boot/issues/31793#issuecomment-1282337468 for details.

**Comment by sbrannen** [comment]
@scottfrederick, do you think you can squeeze this in before 3.0 RC2?

**Comment by scottfrederick** [comment]
Since #31793 hasn't shipped yet, we'll re-open that issue and address this last bit there.
