### ISSUE TITLE
bootBuildImage fails with `Unable to parse image reference` in RC1

### ISSUE THREAD

**Issue by tompson** [spring-projects/spring-boot#33002]
I have the following configuration in my `build.gradle`:
```
bootBuildImage {
	imageName = "eu.gcr.io/company/imagename"
	builder = "paketobuildpacks/builder:tiny"
	if (System.getenv("IMAGE_TAGS")) {
		tags = (System.getenv("IMAGE_TAGS").split(",") as List<String>).collect { "$imageName:$it" }
	}
}
```

which worked in *3.0.0-M5* but does not work in *3.0.0-RC1* - where it throws the following error:

```
Execution failed for task ':bootBuildImage'.
> Unable to parse image reference "task ':bootBuildImage' property 'imageName':test". Image reference must be in the form '[domainHost:port/][path/]name[:tag][@digest]', with 'path' and 'name' containing only [a-z0-9][.][_][-]
```

**Comment by wilkinsona** [comment]
Thanks for trying RC1.

`imageName` on `bootBuildImage` is now a Gradle `Property`. Unfortunately that means that `"$imageName:$it"` no longer works as `$imageName` is the property not its value. This works:

```groovy
bootBuildImage {
	imageName = "eu.gcr.io/company/imagename"
	builder = "paketobuildpacks/builder:tiny"
	if (System.getenv("IMAGE_TAGS")) {
		tags = (System.getenv("IMAGE_TAGS").split(",") as List<String>).collect { "${imageName.get()}:$it" }
	}
}
```

The switch to using `Property` is [mentioned in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-RC1-Release-Notes#configuring-gradle-tasks) but we hadn't anticipated that it would have this effect. We'll update the release notes.

**Comment by wilkinsona** [comment]
I have updated the release notes. Thanks for bringing this to our attention.

**Comment by tompson** [comment]
Thanks for the quick response!
