### ISSUE TITLE
Tomcat 10 is EOL

### ISSUE THREAD

**Issue by n12c** [spring-projects/spring-boot#33020]
https://tomcat.apache.org/tomcat-10.0-eol.html 🤔 

Does SB3 need to ship with Tomcat 10.1 (seems that way?)

Does that mean that a Jakarta EE 10 baseline is needed? (ref: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) It certainly seems like Jakarta EE 10 spec JARs will be needed on the classpath if Tomcat is in use.

**Comment by philwebb** [comment]
Thanks for letting us know. We're in the process of deciding our best course of action and will open some upgrade issues if we can move to the newer version in time.
