### ISSUE TITLE
Spring Boot 3.0 no longer logs guidance to enable debug logging to see the condition evaluation report when the app fails to start

### ISSUE THREAD

**Issue by stevestorey** [spring-projects/spring-boot#33027]
This code: https://github.com/spring-projects/spring-boot/blob/533f3017d45c702eb8d15a4fe3872baaa8e435d9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/logging/ConditionEvaluationReportLoggingListener.java#L140

I _think_ should be passing `true` instead of `false` to denote that it's a crash report. I can't see any call sites that pass `true` at the mo, and I presume that `ApplicationFailedEvent` denotes a crash ?

**Comment by wilkinsona** [comment]
Thanks for spotting that, @stevestorey. That's a regression that I introduced in https://github.com/spring-projects/spring-boot/commit/8e35f2ae928f22cf895e298c72d3c1a7fee247bc.
