### ISSUE TITLE
2.7.4 Upgrade to 2.7.5 Cors

### ISSUE THREAD

**Issue by zhang20084** [spring-projects/spring-boot#33030]
![image](https://user-images.githubusercontent.com/1556397/200225816-9adfbc66-ad26-4e37-9215-d20c9b492452.png)

No change in configuration. Only upgrade from 2.7.4 to 2.7.5
2.7.4 Don't prompt for cross domain
What configuration needs to be modified in 2.7.5

**Comment by bclozel** [comment]
`application.cors.*` is not a configuration namespace managed by Spring Boot. Maybe something that your application is handling itself? I'm closing this issue as invalid as a result.

If you still believe this is a bug, please create a sample application with https://start.spring.io that demonstrates the problem.
