### ISSUE TITLE
oauth2 token generation is slow

### ISSUE THREAD

**Issue by DengChen2020** [spring-projects/spring-boot#33031]
Applicable oauth2 token is generated and org. Springframework. Security. Oauth2. The provider. The method of endpoint class TokenEndpoint postAccessToken slowly, execution time two hundred to three hundred milliseconds. How to optimize

**Comment by DengChen2020** [comment]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.5</version>
        <relativePath/>
    </parent>
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
            <version>2.1.18.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>

**Comment by wilkinsona** [comment]
`spring-security-oauth2-autoconfigure` is [no longer supported](https://github.com/spring-attic/spring-security-oauth). Please migrate to the OAuth2 support that is built into Spring Security.
