### ISSUE TITLE
Reference documentation refers to artemis-jms-server but artemis-jakarta-server should now be used instead

### ISSUE THREAD

**Issue by gotson** [spring-projects/spring-boot#33065]
Hi,

My project is declaring a dependency `org.apache.activemq:artemis-jms-server` as indicated in the documentation to use embedded mode.

Previously, having this in my `build.gradle.kts` would work fine:

```kotlin
dependencies {
  implementation(platform("org.springframework.boot:spring-boot-dependencies:2.7.5"))
  implementation("org.apache.activemq:artemis-jms-server")
}
```

Now i am trying to test 3.0.0-RC1, and the following doesn't work:

```kotlin
dependencies {
  implementation(platform("org.springframework.boot:spring-boot-dependencies:3.0.0-RC1"))
  implementation("org.apache.activemq:artemis-jms-server")
}
```

This is apparently because `spring-boot-dependencies-3.0.0-RC1.pom` doesn't declare `org.apache.activemq:artemis-jms-server` anymore, while it was there in `spring-boot-dependencies-2.7.0-RC1.pom`.

I am not sure if it's a bug or if it's on purpose?

I thought that having it declared in the spring boot dependencies would help to make sure the versions are always aligned.

**Comment by bclozel** [comment]
This has been done on purpose in #28591 and is [listed in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes#removed-support).

**Comment by wilkinsona** [comment]
@bclozel, that's Active MQ rather than Artemis.

The coordinates of the dependency have changed following the Jakarta EE 9 upgrade. `artemis-jakarta-server` should now be used in place of `artemis-jms-server`. We need to correct the docs [here](https://docs.spring.io/spring-boot/docs/3.0.0-RC1/reference/htmlsingle/#messaging.jms.artemis).
