### ISSUE TITLE
@NestedConfigurationProperty List in @ConfigurationProperties

### ISSUE THREAD

**Issue by jevin36** [spring-projects/spring-boot#3306]
Hi I am trying to get the following configuration up and running.
```
@ConfigurationProperties(prefix="my")
public class Config {
    @NestedConfigurationProperty
    private List<ServerConfiguration> servers = new ArrayList<ServerConfiguration>();

    public List<ServerConfiguration> getServers() {
        return this.servers;
    }
}
```
```
@ConfigurationProperties(prefix = "server")
public class ServerConfiguration {
    private String name;
    private String description;
}
```
So, I want to have multiple server configs nested in objects. I tried setting the properties with the following properties file. I can see that the list is added up by items but the members of the server are never set (name, description)
```
my.servers[0].name=test
my.servers[0].server.name=test
my.servers[1].name=test
my.servers[1].server.name=test
```

already asked the same question on: http://stackoverflow.com/questions/30985570/spring-nestedconfigurationproperty-list-in-configurationproperties

**Comment by snicoll** [comment]
There is no need to cross-post, your question on stackoverflow is fine.
