### ISSUE TITLE
SB 2.6.13 and 2.7.5 use  jetty-reactive-httpclient 1.1.13 which pulls in slf4j 2.0

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-boot#33104]
Since SLF4J 2 isn't supported until SB 3.0, could this  be reverted or excluded?
Prior version 1.1.12 didn't have this issue.

**Comment by wilkinsona** [comment]
You can safely downgrade to SLF4J 1.7.x. Spring boot's dependency management should already do this for you.

**Comment by mikebell90** [comment]
We do use the spring boot dependencies bom and I assure you the jetty reactive add on  still pulls in slf4j 2. The issue is simple : we use maven dependencies analyzer plugin and it fails the build because of this dep. 

the truth is from what I see scanning commit logs there is nothing new in this version just dependency upgrades. So you could safely revert

**Comment by wilkinsona** [comment]
> We do use the spring boot dependencies bom and I assure you the jetty reactive add on still pulls in slf4j 2

I can't reproduce the behaviour with Spring boot 2.7.5. SL4FJ 1.7.36 is used:

```
[INFO] +- org.eclipse.jetty:jetty-reactive-httpclient:jar:1.1.13:compile
[INFO] |  +- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- org.eclipse.jetty:jetty-client:jar:9.4.49.v20220914:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.49.v20220914:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.49.v20220914:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.49.v20220914:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
```

> the truth is from what I see scanning commit logs there is nothing new in this version just dependency upgrades. So you could safely revert

Unfortunately, that's not a viable long-term option. 1.1.13 may only upgrade dependencies but inevitably there will be a 1.1.x release that fixes a bug so we want to keep up-to-date.

If you can provide a sample project that uses Spring Boot's dependency management and ends up with SLF4J 2.0 we can take another look.
