### ISSUE TITLE
spring-boot-starter-cache does not exist

### ISSUE THREAD

**Issue by aheusingfeld** [spring-projects/spring-boot#3311]
`spring-boot-starter-cache` is referenced in the [docs](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_supported_cache_providers) but is not in the `spring-boot-dependencies-1.2.4.RELEASE.pom`

**Comment by wilkinsona** [comment]
The starter's new in 1.3. You're looking at the docs for the latest snapshot (currently 1.3.0) and the pom for 1.2.4.
