### ISSUE TITLE
Some milestone versions are not marked as "Pre-release"

### ISSUE THREAD

**Issue by marcwrobel** [spring-projects/spring-boot#33120]
### Description

Usually milestone versions in https://github.com/spring-projects/spring-boot/releases, such as https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-M5, are marked in GitHub as "Pre-release".

But some are not :

- https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.M4
- https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.M3
- https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.M2
- https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.M1

This make it more difficult for automation tools to filter out those versions.

### Implementation ideas

Edit the above versions in GitHub and set each of them as "Pre-release".

**Comment by bclozel** [comment]
This is fixed now, thanks for letting us know!
For recent versions, this flag is automatically handled by our release pipeline, I guess those were manual errors.
