### ISSUE TITLE
MockMvc tests that use contextPath fail with Thymeleaf 3.1

### ISSUE THREAD

**Issue by agebhar1** [spring-projects/spring-boot#33166]
While preparing an application to use the upcoming Spring Boot v3 a lot of tests fail where `MockMvc` is used. The application is configured with a `server.servlet.context-path` which is also used in the tests. For Spring Boot v2 these tests are successfully running. The minimal test is:

```java
@SpringBootTest
@AutoConfigureMockMvc
class DemoApplicationTests {

    @Autowired
    private MockMvc mockMvc;

    @Value("${server.servlet.context-path}")
    private String contextPath;

    @Test
    public void shouldServeIndex_mockMvc() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders.get(contextPath + "/").contextPath(contextPath))
                .andExpect(status().isOk());
    }

    @Test
    public void shouldServeIndex_webClient() throws Exception {
        try (final var webClient = MockMvcWebClientBuilder.mockMvcSetup(mockMvc).contextPath(contextPath).build()) {
            webClient.getPage("http://localhost" + contextPath + "/");
        }
    }

}
```

Running with Spring Boot 3.0.0-RC2 both tests fail with:
```
[ERROR] shouldServeIndex_mockMvc  Time elapsed: 0.236 s  <<< ERROR!
jakarta.servlet.ServletException: Request processing failed: java.lang.IllegalArgumentException: Cannot build an application for a request which servlet context does not match with the application that it is being built for.
        at com.example.demo.DemoApplicationTests.shouldServeIndex_mockMvc(DemoApplicationTests.java:26)
Caused by: java.lang.IllegalArgumentException: Cannot build an application for a request which servlet context does not match with the application that it is being built for.
        at com.example.demo.DemoApplicationTests.shouldServeIndex_mockMvc(DemoApplicationTests.java:26)
```

The check in `org.thymeleaf.web.servlet.JakartaServletWebApplication#servletContextMatches` fails because the provided current context path is not equal (it's empty) to the requested one. The module for Spring (Framework) 5 does not check the context paths.

A test project can be found [here](https://github.com/agebhar1/gh-spring-boot-thymeleaf).

**Comment by philwebb** [comment]
Although the check is new in Thymeleaf, I think the problem might actually be on our side. The `SpringBootMockServletContext` that we attach from `SpringBootContextLoader` doesn't call `setContextPath`. The mock MVC call in the test does set it so there's a mismatch between `servletContext.getContextPath()` and `httpServletRequest.getContextPath()`.

**Comment by agebhar1** [comment]
Hello @wilkinsona, thank's for your attention. Finally, I expect the tests to be passed. I assume that Thymeleaf's check is correct and the context path is not propagated correctly. As far as I can see is that the provided `ServletContext` to the `ThymeleafView`(which is an extension of `WebApplicationObjectSupport`) contains an object of class `SpringBootMockServletContext`. The object has an empty value ("") for the attribute `contextPath`. Whereby the configuration for `server.servlet.context-path` is set.

**Comment by philwebb** [comment]
I'm a little worried that if we try and set the context path in the tests then it might break a lot of users in the other direction. 

The javadoc for `MockHttpServletRequestBuilder.contextPath(...)` states:

> In most cases, tests can be written by omitting the context path from the requestURI. This is because most applications don't actually depend on the name under which they're deployed. If specified here, the context path must start with a "/" and must not end with a "/".

If we set the context path on our mock servlet then all mock MVC calls will need to remember to also set it.

If I drop it entirely from the tests, things work:

```java
@SpringBootTest
@AutoConfigureMockMvc
class DemoApplicationTests {

	@Autowired
	private MockMvc mockMvc;

	@Test
	public void shouldServeIndex_mockMvc() throws Exception {
		mockMvc.perform(MockMvcRequestBuilders.get("/")).andExpect(status().isOk());
	}

	@Test
	public void shouldServeIndex_webClient() throws Exception {
		try (final var webClient = MockMvcWebClientBuilder.mockMvcSetup(mockMvc).build()) {
			webClient.getPage("http://localhost/");
		}
	}

}
```

**Comment by wilkinsona** [comment]
Thymeleaf 3.1's `JavaxServletWebApplication` has the same check in it so this will also fail with Spring Boot 2.x if someone uses Thymeleaf 3.1.

**Comment by philwebb** [comment]
@agebhar1 We're discussing our options for this issue. Did dropping the context path entirely work for you? If not, the best idea we've had so far is to add some kind of annotation to the test that signals we should create `SpringBootMockServletContext` with the context path set.

**Comment by agebhar1** [comment]
@philwebb thank you for discussing this issue. It will work for me to remove the context path from the Tomcat configuration and add them to all controller. I'd like the test URLs to be equal to the productive ones. Maybe a hint should be added to the documentation to be aware of the situation.

**Comment by tkrah** [comment]
Little bit of a hookup but I get the same exception with spring boot 3 and Thymeleaf 3.1 and using a ForwardedHeaderFilter - the "context-path" used to deploy the app does differ from the mounted forward path and generated the same error - should I file a new bug for that - by whom, thymyleaf or spring-boot?

**Comment by philwebb** [comment]
At this point I'm not sure we should do anything in Spring Boot. It seems like the Thymeleaf updates or workarounds are generally OK for folks.
