### ISSUE TITLE
Allow to override FilterInvocationSecurityMetadataSource when building security configuration

### ISSUE THREAD

**Issue by ukimpact** [spring-projects/spring-boot#3317]
It would be very nice if we had an easy hook to be able to change the protected requests paths dynamically. This is long sought feature going years back. 

http://docs.spring.io/spring-security/site/docs/3.2.x/reference/htmlsingle/faq.html#faq-dynamic-url-metadata

I understand the implication of such feature, but at the same time dynamic protection is well implemented in many frameworks and I see no reason why Spring can't provide neat hook into that..

I am not confident enough myself to make it work right by overriding the spring security filter chain and praying it will work together with spring boot . :-) 

http://stackoverflow.com/questions/6893061/how-to-dynamically-decide-intercept-url-access-attribute-value-in-spring-secur

Ideally it would look something like that:

```java
.authorizeRequests().securityMetadataSource(source)
```

Looking at `AbstractInterceptUrlConfigurer` at the moment to check if the hook is there already, maybe I am missing something.

Thanks.

**Comment by rwinch** [comment]
@ukimpact Did you have any trouble using the code you provided? The FAQ is a bit dated and only pertains to XML based configuration, so the code you provided should work.

**Comment by axotna** [comment]
Thanks for quick reply. I haven't tried this of yet, will make my best effort converting xml and wiring with sb on weekend. See where I get to.. I am generally against changing core parts which work perfectly and which have little to do with the customization I am trying to achieve . I will report on the  outcome asap.

**Comment by Dreampie** [comment]
hi，I want custom securityMetadataSource,too.Could you resolve this？

**Comment by wilkinsona** [comment]
@rwinch Can we close this one? It seems like a general Spring Security issue rather than something that's specific to using Spring Security with Boot.

**Comment by rwinch** [comment]
@wilkinsona As far as I'm concerned it can be.

**Comment by wilkinsona** [comment]
@axotna Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
