### ISSUE TITLE
Spring Batch database default configuration

### ISSUE THREAD

**Issue by jenswl** [spring-projects/spring-boot#3318]
Hello,

I'm having a question on the behaviour of Spring Batch (see http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-initialize-a-spring-batch-database) which can be configured in Spring Boot via the "spring.batch.initializer.enabled" parameter. Currently the default behaviour is to automatically try to create the meta tables.
In our company we heavily use SB jobs working on the same meta tables and we face now the problem that we need to make sure in any situation that no(!) meta tables are created automatically (as they already exist - i can give here more details if anyone is interested ;-) ). 
If the parameters are set correctly to "false" it's not an issue. Once done wrong or forgotten it will create the tables and (in our env) influence other jobs.
From my perspective it could be more senseful to have the default behaviour for Spring Boot/Batch configured as following:
- given no "spring.batch.initializer.enabled" parameter => no tables are generated
- given no "spring.batch.initializer.enabled=false" parameter => no tables are generated (redundant)
- given no "spring.batch.initializer.enabled=true" parameter => tables are generated

I would like to hear your opinion on that and see if that change would be possible.

Thanks,
Jens

**Comment by philwebb** [comment]
A call for @dsyer or @mminella to make I think. We can't change the behavior in the 1.2.x line.

**Comment by mminella** [comment]
I'd have to double check, but I thought we updated this so that if the scripts were run again, it wouldn't impact existing deployments.  If not, I'd advocate for that over just defaulting to no.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
