### ISSUE TITLE
Upgrade to Spring Kafka 2.9.2

### ISSUE THREAD

**Issue by Crystark** [spring-projects/spring-boot#33185]
Hello,

I know this is supposed to be somewhat automatic but I'm having an issue with the current minor version that is being used of spring kafka (2.8.x)
It uses an older version of kafka (3.1.x) whereas the latest 2.9.2 spring-kafka uses kafka 3.2.3 which fixes an issue with `setStreamsUncaughtExceptionHandler` not being called. See [the comments in this stackoverflow](https://stackoverflow.com/questions/71303705/spring-cloud-kafka-stream-streamsuncaughtexceptionhandler#comment126079709_71314677).

Would it be possible to bump the minor version of spring-kafka to 2.9.2 ?

Thanks

**Comment by snicoll** [comment]
@Crystark No. Our Third party policy is so that we won't upgrade to a new feature release of a dependency in a maintenance release of Spring Boot. Spring Boot `2.7.x` is on Kafka 2.8. You can override the version as documented in the reference guide.
