### ISSUE TITLE
DataSourcePublicMetrics does not expose all the properties from DataSourcePoolMetadata

### ISSUE THREAD

**Issue by csavory** [spring-projects/spring-boot#3319]
```DataSourcePoolMetadata``` has 5 methods on the interface, but ```DataSourcePublicMetrics``` only exposes 2 of them.  The Spring Boot Docs say that all these will be exposed, but they aren't.

>The maximum number connections (datasource.xxx.max).
>The minimum number of connections (datasource.xxx.min).
>The number of active connections (datasource.xxx.active)
>The current usage of the connection pool (datasource.xxx.usage).

**Comment by snicoll** [comment]
It's a documentation issue as the the first two attributes aren't metrics. Thanks.
