### ISSUE TITLE
Missing documentation for spring boot caching

### ISSUE THREAD

**Issue by MaximeBelanger** [spring-projects/spring-boot#33204]
Hello,
the documentation regarding spring-boot caching seems to have been moved, while there are still some links to it.

In the  [Spring Caching Guide](https://spring.io/guides/gs/caching/), in the 'Enable Caching' section, there is the following:
`Spring Boot automatically configures a suitable [CacheManager](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/CacheManager.html) to serve as a provider for the relevant cache. See [the Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html) for more detail.`

The link converts to : https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#io.caching, but the section doesn't seem to exist anymore in the current version of the documentation.

Also, the [Spring Boot Reference Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/index.html) lists caching in the [Core Features](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features) : `"Profiles, Logging, Security, **Caching**, Spring Integration, Testing, and more."` while there is no section on that subject in the core feature.

From my understanding, the Caching section has now moved [here ](https://docs.spring.io/spring-boot/docs/current/reference/html/io.html#io.caching)

Also, after reading the current documentation, two questions remain:

1. What would be the current need to use spring-boot-starter-cache? It seems to be included in Spring Boot core, now. 
2. What would be the current quick way to get a Generic Spring Cache Provider Bean autoconfigured?

**Comment by philwebb** [comment]
I've raised https://github.com/spring-guides/gs-caching/issues/20 to fix the guide link

**Comment by snicoll** [comment]
@MaximeBelanger thanks for raising this. The links to the cache sections have been fixed. As for your questions, we don't use the issue tracker for that so please ask on StackOverflow. Caching was always a core framework (not Spring Boot) implementation. The starter brings `spring-context-support` which has additional cache provider implementations. I believe your question on the generic cache provider is described in the documentation, [this section](https://docs.spring.io/spring-boot/docs/current/reference/html/io.html#io.caching.provider.generic) in particular.

If that doesn't help, please follow-up on StackOverflow and feel free to add a link to your question here.

**Comment by MaximeBelanger** [comment]
Thank you! As for my questions, indeed I should have used SO. If anybody ends up here because of Google looking for the same answers, I was looking for the[ Simple cache](https://docs.spring.io/spring-boot/docs/current/reference/html/io.html#io.caching.provider.simple), and not the Generic Cache; got confused between the two.

**Comment by snicoll** [comment]
> For the sake of completeness regarding SB documentation, you could also remove the references to 'Caching' and 'Spring Integration' in the [main page,](https://docs.spring.io/spring-boot/docs/current/reference/html/index.html) since they are now documented in their specific sections.

I am a bit confused. That's exactly what I did, see the snapshot build https://docs.spring.io/spring-boot/docs/2.7.x-SNAPSHOT/reference/html/
