### ISSUE TITLE
Remove org.apache.httpcomponents:httpclient-win from Spring Boot

### ISSUE THREAD

**Issue by ManjunathMS35** [spring-projects/spring-boot#33219]
Hi,

The org.apache.httpcomponents:httpclient-win comes with the vulnerable jna-platform and this is fixed in org.apache.httpcomponents.client5:httpclient5-win, in Spring boot both of these dependencies are available for users. Does it make sense to keep only the httpclient5? and remove the vulnerable httpclient-win ?

Kind regards,
Manjunath

**Comment by bclozel** [comment]
Could you elaborate a bit on this vulnerability? Could you share the CVE ID?

**Comment by ManjunathMS35** [comment]
There is no CVE ID I could find. This was reported by WhiteSource with the below description:

JNA prior to 5.0.0 was discovered to contain an out-of-bounds read. Advapi32Util.registryGetValues does not terminate the returned string with null terminators. When it tries to identify the string content it searches for the next null-terminator and will read out-of-bounds of the buffer.

Related links: https://github.com/java-native-access/jna/issues/340 , https://github.com/java-native-access/jna/commit/12493ba771a50fae7d6303e8b58b31eacf903327
