### ISSUE TITLE
Stop adding binders to all meter registry beans 2.7.X

### ISSUE THREAD

**Issue by masokol** [spring-projects/spring-boot#33217]
In our application we are using actuator mainly for the probes. When using micrometer and creating our own composite meter registry springboot actuator seem to add binders to all meter registry beans it can find automatically.
Metrics that we don't want to have as application metrics are present (jvm, spring etc.).

I can understand that springboot would add binders etc. to the meter registry it created but adding it to all beans of type meter registry is a bit too much.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, this is a situation where it's impossible to please all of the people all of the time. If we changed the behavior as you have suggested it would be a large breaking change for many users. You may want to consider excluding `org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration`. This will remove the `MeterRegistryPostProcessor` that binds all meters to each registry. Alternatively, you could use `management.metrics.enable` to disable the metrics you don't want. For example, `management.metrics.enable.jvm=false` will prevent the binding of all meters whose id starts with `jvm`.
