### ISSUE TITLE
Consider scanning for GraphQL schemas in all `graphql` folders in the classpath

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#33221]
`GraphQlProperties.Schema` currently uses `classpath:graphql/**/` as the resource pattern which limits schema discovery to the first `graphql` folder found in the classpath.

https://github.com/spring-projects/spring-boot/blob/bad11bbe8fb7c82cfab1a14e6419cbf254b2b9f1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/GraphQlProperties.java#L75

If this is intentional, please ensure that this is well documented.

If it's not intentional, consider using `classpath*:graphql/**/` instead.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/31772.
