### ISSUE TITLE
Micrometer trace HTTP request span propagation

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-boot#33228]
We've noticed that child spans of HTTP requests were showing up as independent root traces after migrating Spring Cloud GCP to Spring Boot 3.0 (RC2).

In old Spring Cloud Sleuth, `HttpTracing` bean was [enriched with HTTP request parsing](https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/web/BraveHttpConfiguration.java#L80-L123). While in Micrometer `BraveHttpRequestParser` [exists](https://github.com/micrometer-metrics/tracing/blob/32235174962bb46f59815cbf1865cf8377d8a107/micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BraveHttpRequestParser.java#L29), it does not seem to be instantiated or injected into `HttpTracing` bean in Spring Boot autoconfiguration. In fact, `HttpTracing` bean configured in Spring Boot [looks very minimalistic](https://github.com/spring-projects/spring-boot/blob/5f6b63e277fb78c7c6f4ca5cd93e31b70c2da976/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/BraveAutoConfiguration.java#L149-L151).

Is there a new mechanism through which we should be extracting existing trace information from HTTP headers?

**Comment by elefeint** [comment]
cc:/ @joewang1127

**Comment by wilkinsona** [comment]
@marcingrzejszczak @jonatan-ivanov can you please take a look?

**Comment by jonatan-ivanov** [comment]
Yes, the new mechanism is through the instrumented HTTP clients: it's not Brave who provides these details anymore but the instrumentation.

What HTTP client are you using? Are you trying to instrument it on your own?
Could you please try a client that is supported out of the box like `RestTemplate` or `WebClient`?
(You can also set-up okhttp or, once-it is released, OpenFeign).

**Comment by elefeint** [comment]
The sample that's surfacing this issue is using [`RestTemplate`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/69545ab707d44c2ef72b21ffe3d128db49515cfd/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/main/java/com/example/WorkService.java#L59), but the [autoconfugured `HttpRequestParser`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/feature/boot3.0-migrator/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L278-L280) does not seem to be used.

At first, I thought that `brave.http.HttpRequestParser` bean needed to change over to `io.micrometer.tracing.http.HttpRequestParser`, but since I could not find a place in Boot where this could be customized at all, I figured I'd ask.

@meltsufin you 'll probably have to look into this, too, since I am out.

**Comment by jonatan-ivanov** [comment]
We have a working sample for resttemplate: https://github.com/micrometer-metrics/micrometer-samples/
Could you please try to register it as a bean as you see in the sample?

**Comment by jonatan-ivanov** [comment]
There are a few issues with the sample:
1. It is quite big, I'm not 1000% sure what you are talking about
2. You are using Sleuth (Sleuth is for Boot 2, if you are using Boot 3 please use Micrometer Tracing)
3. You are using Brave's API for things that you should be able to do with the Observation API (also with Micrometer Tracing)

>However, compared with sleuth, the default span name is not the annotated method's name, even change the name or value parameter doesn't change the span name.

If you mean `@NewSpan` by this, that won't work, that annotation is from Sleuth, it should not even be on your classpath (see the second point above). On the first screenshot I everything looks expected to me, if you want an additional span, you can use `@Observed`.

**Comment by JoeWang1127** [comment]
Hi @jonatan-ivanov, thanks for your feedback, the `@Observed` works for me (with extra help from [here](https://spring.io/blog/2022/10/12/observability-with-spring-boot-3)). You can close the issue, thanks.
