### ISSUE TITLE
Switch BindableRuntimeHintsRegistrar to use BeanUtils.getPropertyDescriptors

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#33232]
`BindableRuntimeHintsRegistrar` currently uses `BeanInfoFactory` to get properties, I think we can safely switch to `BeanUtils.getPropertyDescriptors` which will be a little simpler and also make use of caches.

**Comment by wilkinsona** [comment]
I've turned this into a bug as the change made has fixed the problem described in #33242 where no metadata was generated for a property with methods like these:

```java
    public String getStatic() {
        return staticRegion;
    }

    public void setStatic(@Nullable String staticRegion) {
        this.staticRegion = staticRegion;
    }
    
    public boolean isStatic() {
    	return StringUtils.hasText(this.staticRegion);
    }
```

The `isStatic` method meant that no metadata was generated at all for the static property.
