### ISSUE TITLE
ConfigurationProperties Not Populated Correctly In Native Image When Getter/Setter Name Is Different

### ISSUE THREAD

**Issue by akefirad** [spring-projects/spring-boot#33242]
Specifically if the field has a different name than its getter/setter (real example [`io.awspring.cloud.autoconfigure.core.RegionProperties`](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/core/RegionProperties.java)):
```java
@ConfigurationProperties(prefix = RegionProperties.PREFIX)
public static class RegionProperties {

    public static final String PREFIX = "spring.cloud.aws.region";

    private String staticRegion;

    private boolean instanceProfile = false;

    public String getStatic() {
        return staticRegion;
    }

    public void setStatic(@Nullable String staticRegion) {
        this.staticRegion = staticRegion;
    }

    public boolean isInstanceProfile() {
        return this.instanceProfile;
    }

    public void setInstanceProfile(boolean instanceProfile) {
        this.instanceProfile = instanceProfile;
    }

    @Override
    public String toString() {
        return "RegionProperties{" +
                "staticRegion='" + staticRegion + '\'' +
                ", instanceProfile=" + instanceProfile +
                '}';
    }
}
```
With the following configuration:
```yaml
spring:
  cloud:
    aws:
      region:
        static: eu-central-1
        static-region: us-east-1
        instance-profile: true
```
When loaded `System.out.println(properties)` prints:
```
RegionProperties{staticRegion='null', instanceProfile=true}
```
If you change the getter and setter to match the field name (i.e. `getStaticRegion` and `setStaticRegion`) the same configuration prints:
```
RegionProperties{staticRegion='us-east-1', instanceProfile=true}
```
I'm not sure what the root cause is or if it's a known limitation (Is there any documentation regarding known limitation apart from [beta](https://docs.spring.io/spring-native) version?), neither do I know where is the right place to file the issue.

**Comment by akefirad** [comment]
OK, while preparing the sample project, I found the root cause. It is the additional `isStatic` method in the original `RegionProperties` class. Adding `getStaticRegion` would solve the issue, but only because the field becomes a new field. I must have removed the `isStatic` method while cleaning up the code to paste it here. Sorry for the confusion. Here's the sample project. Let me know if you want to have it as a repo.
[test-property-getter.zip](https://github.com/spring-projects/spring-boot/files/10034491/test-property-getter.zip)

**Comment by wilkinsona** [comment]
Thanks, @akefirad. I've reproduced the problem now using 3.0.0-RC2. It doesn't occur with 3.0.0-SNAPSHOT due to, I believe, the changes made for https://github.com/spring-projects/spring-boot/issues/33232.
