### ISSUE TITLE
Problem with PagingAndSortingRepository in Spring Boot 2.7.5?

### ISSUE THREAD

**Issue by kentsecureappbox** [spring-projects/spring-boot#33253]
We have this repository & method declared in our system:

```
public interface ImportBatchRowsRepository extends PagingAndSortingRepository<ImportBatchRow, String> {
...
    @Query("select row from ImportBatchRow row where row.importBatch = :importBatch AND"
            + " (COALESCE( null, :statuses ) is null or row.status in (:statuses))  AND "
            + "(:searchLike IS NULL OR row.description LIKE :searchLike OR row.rowData LIKE :searchLike)")
    Page<ImportBatchRow> findByImportBatch(
            @Param("importBatch") ImportBatch importBatch,
            @Param("statuses") List<ImportBatchRowStatus> statuses,
            @Param("searchLike") String searchLike,
            Pageable pageable);
```

With 2.7.4, the call findByImportBatch(batch, null, null, pageRequest) succeds and returns a list of rows.
With 2.7.5 the same call returns an empty list.

Not sure if we are using this improperly, but don't think so, so will report this as a potential bug.

**Comment by wilkinsona** [comment]
Thanks for the report but the functionality of `PagingAndSortingRepository` and `@Query` is part of Spring Data which is managed as a number of separate projects. It looks like you're using [Spring Data JPA](https://github.com/spring-projects/spring-data-jpa) so Hibernate may also be a factor. Spring Boot 2.7.5 [upgraded to Hibernate 5.6.12.Final](https://github.com/spring-projects/spring-boot/issues/32665) from 5.6.11.Final. You may want to try downgrading back to 5.6.11.Final to see if Hibernate is the cause of the problem. If the problem still occurs with Hibernate 5.6.11, you may want to open a Spring Data JPA issue.

**Comment by kentsecureappbox** [comment]
Sorry, my misstake, I thought I was following a link to Spring Data JPA project and didn't see that it was wrong, filed an issue on the Spring Data JPA issue now instead
