### ISSUE TITLE
Spring Batch | ItemReader Read() method call for infinate loop, or some time skip and duplicate the data

### ISSUE THREAD

**Issue by MTPL0003-ShivamSoni** [spring-projects/spring-boot#33279]
package th.co.magicsoftware.kma;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.task.SimpleAsyncTaskExecutor;

import th.co.magicsoftware.partition.ColumnRangePartitioner;

@EnableBatchProcessing
@Configuration
public class JobKma {

	@Autowired
	private JobBuilderFactory jobs;

	@Autowired
	private StepBuilderFactory steps;

	@Value(value = "${job.kma.batch.chunk.size.output}")
	private int batch_chunk;

	@Value(value = "${kma.grid.size}")
	private int gridsize;

	@Bean
	public JobKmaItemReader KmaTransactionInputItemReader() {
		return new JobKmaItemReader();
	}

	@Bean
	public JobKmaItemWriter KmaTransactionWriter() {
		return new JobKmaItemWriter();
	}

	@Bean
	public StepKolItemReader KolTransactionInputItemReader() {
		return new StepKolItemReader();
	}

	@Bean
	public StepKolItemWriter KolTransactionWriter() {
		return new StepKolItemWriter();
	}

	@Bean
	public StepKbolItemReader KbolTransactionInputItemReader() {
		return new StepKbolItemReader();
	}

	@Bean
	public StepKbolItemWriter KbolTransactionWriter() {
		return new StepKbolItemWriter();
	}

	@Bean
	public ColumnRangePartitioner partitioner() {
		return new ColumnRangePartitioner();
	}

	@Bean
	public JobKmaListener jobListener() {
		return new JobKmaListener();
	}

	@Bean
	public UpdateLastExecution updatelastExecution() {
		return new UpdateLastExecution();
	}

	@Bean
	public Step KmaTransactionInputStep() {
		return steps.get("KmaTransactionInputStep").<KmaTransaction, KmaTransaction>chunk(batch_chunk)
				.reader(KmaTransactionInputItemReader()).writer(KmaTransactionWriter()).build();
	}

	@Bean
	public Step PartitionerStepKMA() {
		return steps.get("PartitionerStepKMA").partitioner(KmaTransactionInputStep().getName(), partitioner())
				.gridSize(gridsize).step(KmaTransactionInputStep()).taskExecutor(new SimpleAsyncTaskExecutor()).build();
	}

	@Bean
	public Step KolTransactionInputStep() {
		return steps.get("KolTransactionInputStep").<KmaTransaction, KmaTransaction>chunk(batch_chunk)
				.reader(KolTransactionInputItemReader()).writer(KolTransactionWriter()).build();
	}

	@Bean
	public Step PartitionerStepKOL() {
		return steps.get("PartitionerStepKOL").partitioner(KolTransactionInputStep().getName(), partitioner())
				.gridSize(gridsize).step(KolTransactionInputStep()).taskExecutor(new SimpleAsyncTaskExecutor()).build();
	}

	@Bean
	public Step KbolTransactionInputStep() {
		return steps.get("KbolTransactionInputStep").<KmaTransaction, KmaTransaction>chunk(batch_chunk)
				.reader(KbolTransactionInputItemReader()).writer(KbolTransactionWriter()).build();
	}

	@Bean
	public Step PartitionerStepKBOL() {
		return steps.get("PartitionerStepKBOL").partitioner(KbolTransactionInputStep().getName(), partitioner())
				.gridSize(gridsize).step(KbolTransactionInputStep()).taskExecutor(new SimpleAsyncTaskExecutor())
				.build();
	}

	@Bean
	public Step lastExecution() {
		return steps.get("lastExecution").tasklet(updatelastExecution()).build();

	}

	@Bean(name = "JobKma")
	public Job JobKma() {
		return jobs.get("JobKma").listener(jobListener())
				.flow(PartitionerStepKMA())
				.next(PartitionerStepKBOL())
				.next(PartitionerStepKOL())
				//.next(lastExecution())
				.end().build();
	}

	public JobBuilderFactory getJobs() {
		return jobs;
	}

	public void setJobs(JobBuilderFactory jobs) {
		this.jobs = jobs;
	}

	public StepBuilderFactory getSteps() {
		return steps;
	}

	public void setSteps(StepBuilderFactory steps) {
		this.steps = steps;
	}
}
-------------------------------------------------------------------------------------
package th.co.magicsoftware.kma;

import java.util.Iterator;

import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.annotation.AfterStep;
import org.springframework.batch.core.annotation.BeforeStep;
import org.springframework.batch.item.ItemReader;
import org.springframework.beans.factory.annotation.Autowired;

public class JobKmaItemReader implements ItemReader<KmaTransaction> {

	@Autowired
	private KmaTransactionRepo kmaTransactionRepo;

	private Iterator<KmaTransaction> Iterator;

	@BeforeStep
	public void before(StepExecution stepExecution) {
	
		Iterator = kmaTransactionRepo.findByPartitionerQuery(stepExecution.getExecutionContext().getInt("start"),
				stepExecution.getExecutionContext().getInt("end"),"KMA" ,stepExecution.getExecutionContext().getString("maxDate") ).iterator();
		
	}
	
	@AfterStep
	public void after(StepExecution stepExecution) {
	
		stepExecution.setStatus(BatchStatus.COMPLETED);
	}

	@Override
	public KmaTransaction read() {		
		
		return Iterator.hasNext()? Iterator.next():null;
		
	}
}
-------------------------------------------------------------------------------------------
package th.co.magicsoftware.kma;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.batch.item.ItemWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.client.RestTemplate;

import th.co.magicsoftware.mapper.KmaMapper;
import th.co.magicsoftware.mapper.KmaRequest;

public class JobKmaItemWriter implements ItemWriter<KmaTransaction> {

	@Value(value = "${sas.kma.api.uri}")
	private String kmaURI;
	private static final Logger LOGGER = LoggerFactory.getLogger(JobKmaItemWriter.class);

	@Autowired
	RestTemplate restTemplate;

	@Override
	public void write(List<? extends KmaTransaction> list) throws Exception {
		 System.out.println("KMATransaction Size :" + list.size());
		if (list.size() > 0) {

			LOGGER.debug("KMATransaction Size :" + list.size());

			for (KmaTransaction transaction : list) {
				KmaRequest apiReq = KmaMapper.KMATransactionMapper(transaction);
				restTemplate.postForObject(kmaURI, apiReq, String.class);
				LOGGER.debug("KMATransaction Data Output:"+apiReq);
			}
		}
	}

}
--------------------------------------------------------------------------
package th.co.magicsoftware.partition;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.batch.core.partition.support.Partitioner;
import org.springframework.batch.item.ExecutionContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import th.co.magicsoftware.jobtransactionparameter.JobTransactionParameter;
import th.co.magicsoftware.jobtransactionparameter.JobTransactionParameterRepo;
import th.co.magicsoftware.kma.KmaTransactionRepo;

public class ColumnRangePartitioner implements Partitioner {

	@Autowired
	private KmaTransactionRepo kmaTransactionRepo;

	@Autowired
	private JobTransactionParameterRepo jobTrnParameterRepo;

	@Value(value = "${kma.api.job.name}")
	private String jobName;

	@Override
	public Map<String, ExecutionContext> partition(int gridSize) {
		int min = 0;
		int max = 0;

		JobTransactionParameter jobTrnParameter = jobTrnParameterRepo.findByJobName(jobName);
		long id = jobTrnParameter.getMaxId();
		long batchSize = jobTrnParameter.getBatchSize();
		Date maxTrnParameterDate = jobTrnParameter.getMaxDate();
		List<Object[]> maxIDList = kmaTransactionRepo.getMaxMinRangPartitioner(id, batchSize, maxTrnParameterDate);

		Object[] objectList2 = maxIDList.get(0);
		max = Integer.parseInt(objectList2[0].toString());
		min = Integer.parseInt(objectList2[1].toString());

		int targetSize = (max - min) / gridSize + 1;

		Map<String, ExecutionContext> result = new HashMap<>();

		int number = 0;
		int start = min;
		int end = start + targetSize - 1;

		while (start <= max) {
			ExecutionContext value = new ExecutionContext();
			result.put("partition" + number, value);

			if (end >= max) {
				end = max;
			}
			value.putInt("start", start);
			value.putInt("end", end);
			value.putString("maxDate", maxTrnParameterDate.toString());
			start += targetSize;
			end += targetSize;
			number++;
		}
		// System.out.println("partition result:" + result.toString());
		return result;
	}

}

**Comment by snicoll** [comment]
Please do not dump code snippet. Us scanning through your code manually is not what we should be doing. It's unclear if you're asking a question, or reporting a bug. Either way this isn't the place to do so. If you're looking for support, please ask questions on StackOverflow. Spring Batch-related issues are not handled here but on the Spring Bath GitHub repository.

**Comment by MTPL0003-ShivamSoni** [comment]
Thank you
