### ISSUE TITLE
Upgrade to Jackson 2.14.1

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#33289]
Upgrading in particular for  https://github.com/FasterXML/jackson-databind/issues/3665

**Comment by bclozel** [comment]
We can't upgrade right now; it looks like the Jackson BOM is referring to `com.fasterxml.jackson.module:jackson-module-scala_2.13:2.14.1` which is not present on Maven Central.

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/issues/614 is done now
