### ISSUE TITLE
Fail the build if the additional meta-data format is invalid

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3329]
Various typos were introduced  by the PID update (https://github.com/spring-projects/spring-boot/commit/ea6162254df1843945300dd36c6e6936714459a2 and https://github.com/spring-projects/spring-boot/commit/becced5f0b7bac8200df7a5706b568687b517b90).

As a result, all the additional meta-data of the actuator modules were gone because the annotation processor simply logs a warning if it can't merge the manual meta-data. That warning never shows up in the Maven console.

I would advocate for actually failing the build with an error message that provides the actual error.

**Comment by philwebb** [comment]
:+1:
