### ISSUE TITLE
Devtools: Enable automatic logins at dev time

### ISSUE THREAD

**Issue by cbeams** [spring-projects/spring-boot#3331]
Per brainstorming with @rwinch:

I just went through the process of enabling remember-me authentication, essentially so I don't have to log into my application every time I re-start `gradle bootRun`.

It would be nice if Boot's devtools solved this by introducing a `DeveloperLoginFilter` or some such that would set the security context automatically with a fake user (or a username of my choosing, configured in `application.yml`). This approach would be like in kind to the recent additions to Spring Security Test, e.g. `@WithMockUser`, only happening at development runtime, not just test-time.

**Comment by spencergibb** [comment]
:+1:

**Comment by philwebb** [comment]
I wonder if saving session state between restarts would negate the need for this somewhat?

**Comment by rwinch** [comment]
@philwebb Thanks for the feedback. It will if you have an external place to store the session. I know many users for Spring Session are using an embedded Redis instance that will restart when the container restarts.

**Comment by philwebb** [comment]
@cbeams Do the recent updates in master that save sessions between restarts negate the need for this now?

**Comment by cbeams** [comment]
I haven't tried it yet, but perhaps it's a "good enough" measure. Given that I already have this solved for myself using remember-me authentication and that others have specifically been asking for sessions to survive restarts anyway, I don't mind this issue being closed as-is. Thanks for the follow-up.
