### ISSUE TITLE
Annotation for automatically read application.properrties/yml

### ISSUE THREAD

**Issue by drolewski** [spring-projects/spring-boot#33316]
Now we can't create the dynamic application.properties or application.yml keys.
For example, I want to declare `testapp.dynamicValue=true` and start with that @Value spring-boot app.
But after some time I need to change the value of `testapp.dynamicValue` without restarting the application.

I know that there are external solutions for this kind of issue but it would be great to make it straight from spring-boot application code without external libs.

**Comment by wilkinsona** [comment]
Duplicates #259.
