### ISSUE TITLE
Revert fb2cc7314d474faf5a3ae7c18782bac5e382d716 once we've upgraded to Thymeleaf 3.1.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#33349]
We should revert https://github.com/spring-projects/spring-boot/commit/fb2cc7314d474faf5a3ae7c18782bac5e382d716 as soon as possible. We need Thymeleaf 3.1.1 before we can do so.

**Comment by scottfrederick** [comment]
Completed in fb2cc7314d474faf5a3ae7c18782bac5e382d716
