### ISSUE TITLE
Use classfier 'jakarta' for QueryDSL dependency, since Spring Boot 3 upgraded to Hibernate 6

### ISSUE THREAD

**Issue by metaphor** [spring-projects/spring-boot#33344]
As Spring Boot 3 upgraded to Hibernate 6, it uses jakarta.persistence api.
In order to support new jakarts.persistence api, QueryDSL ships artifacts querydsl-apt , querydsl-jpa, querydsl-jpa-codegen with classifier 'jakarta'.
But spring-boot-depenencies still declare querydsl deps without classifier 'jakarta'.

Please upgrade it.

**Comment by wilkinsona** [comment]
We use QueryDSL's bom so this will have to be fixed in QueryDSL. https://github.com/querydsl/querydsl/issues/3424 is already tracking that fix.
