### ISSUE TITLE
Spring Boot 3.0 Release Notes lists incorrect Spring Session release

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#33361]
Section [_Third-party Library Upgrades_](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#third-party-library-upgrades) of _Spring Boot 3.0 Release Notes_ wiki page lists Spring Session 2022.0.

This should be Spring Session 3.0, as Spring Session BOM has moved to the core project repo, and the versioning changed from calver to semver during the RC phase.

The link should likely point to the release page, but that's [not there yet](https://github.com/spring-projects/spring-session/releases), so it's probably an action point for @rwinch.

**Comment by wilkinsona** [comment]
Thanks, @vpavic. We now link to https://github.com/spring-projects/spring-session/releases/tag/3.0.0. The changelog should appear there once Rob's back from holiday and has had a chance to finish off the Session release.
