### ISSUE TITLE
PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

### ISSUE THREAD

**Issue by bodiam** [spring-projects/spring-boot#33368]
I created a project using the following URL:

https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.0.0&packaging=jar&jvmVersion=17&groupId=com.allday&artifactId=tablebooking-api&name=tablebooking-api&description=Table%20booking%20project%20for%20AllDay&packageName=com.allday.tablebooking&dependencies=actuator,web,devtools,native,testcontainers,data-jpa

As mentioned in my other issue (#33367), the native part doesn't work, so I disabled that in my build.gradle.kts. However, now I want to build the project, and I'm still getting an issue:

```
A problem occurred configuring root project 'tablebooking-api'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-buildpack-platform:3.0.0.
     Required by:
         project : > org.springframework.boot:org.springframework.boot.gradle.plugin:3.0.0 > org.springframework.boot:spring-boot-gradle-plugin:3.0.0
      > Could not resolve org.springframework.boot:spring-boot-buildpack-platform:3.0.0.
         > Could not get resource 'https://plugins.gradle.org/m2/org/springframework/boot/spring-boot-buildpack-platform/3.0.0/spring-boot-buildpack-platform-3.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/springframework/boot/spring-boot-buildpack-platform/3.0.0/spring-boot-buildpack-platform-3.0.0.pom'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
   > Could not resolve org.springframework.boot:spring-boot-loader-tools:3.0.0.
```

For some reason the project wants to resolve something in jcenter, but I see no references, I'm not even sure where the buildpack comes from.

I think a certificate expired:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/46468/204069260-9ae87826-de7a-4f8a-a308-2d3bef332558.png">

**Comment by izeye** [comment]
The certificate for "jcenter.bintray.com" seems to have been expired yesterday as follows:

```
% openssl s_client -connect jcenter.bintray.com:443 | openssl x509 -noout -dates 
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1
verify return:1
depth=0 CN = *.bintray.com
verify error:num=10:certificate has expired
notAfter=Nov 25 23:59:59 2022 GMT
verify return:1
depth=0 CN = *.bintray.com
notAfter=Nov 25 23:59:59 2022 GMT
verify return:1
notBefore=Oct 25 00:00:00 2021 GMT
notAfter=Nov 25 23:59:59 2022 GMT
```

So this is not related to Spring Boot.

**Comment by bodiam** [comment]
I think it's an issue for Spring Boot, since it should never use jcenter in the first place. But this is because the Gradle Plugin portal is redirecting to jcenter.

I have a current workaround in my` build.gradle.kts`, this seems to resolve the issue for now:

```
buildscript {
	repositories {
		maven(url = "https://repo1.maven.org/maven2") 
	}
}
```

**Comment by wilkinsona** [comment]
This has the same root cause as https://github.com/spring-projects/spring-boot/issues/33367.
