### ISSUE TITLE
Plugin [id: 'org.graalvm.buildtools.native', version: '0.9.18'] was not found

### ISSUE THREAD

**Issue by bodiam** [spring-projects/spring-boot#33367]
I just created a new Spring Boot 3.0 project using the Spring Boot starter page. I've used the following configuration:

https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.0.0&packaging=jar&jvmVersion=17&groupId=com.allday&artifactId=tablebooking-api&name=tablebooking-api&description=Table%20booking%20project%20for%20AllDay&packageName=com.allday.tablebooking&dependencies=actuator,web,devtools,native,testcontainers,data-jpa

Now, when I try to build the project (`./gradlew clean build`), I'm getting the following error:

```
~/UserFiles/projects/tablebooking-api ❯ ./gradlew clean build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/erikp/UserFiles/projects/tablebooking-api/build.gradle.kts' line: 3

* What went wrong:
Plugin [id: 'org.graalvm.buildtools.native', version: '0.9.18'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.graalvm.buildtools.native:org.graalvm.buildtools.native.gradle.plugin:0.9.18')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

I checked the Maven Central repo, the dependency is there, but for some reason it's not getting resolved.

**Comment by wilkinsona** [comment]
This is due to [a problem with Gradle's plugin portal](https://status.gradle.com/incidents/cqrpp419w3sd) and, unfortunately, is out of our control. It has been worked around for now by the Portal redirecting to Maven Central.
