### ISSUE TITLE
Git Commit ID Plugin coordinate changes are missing in 3.0 release notes/migration guide

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-boot#33360]
After upgrading from 2.7.5 to 3.0.0 my Maven starts with several warnings:

```
...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for xyz:xyz:jar:0.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for pl.project13.maven:git-commit-id-plugin is missing. @ line 77, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
...
```

It seems that the `groupdId` and `artifactId` changed when upgrading it from `4.9.10` to `5.0.0` with https://github.com/spring-projects/spring-boot/commit/f025ab629aa8bec978abc6a93a79b4af3cb2c4bc

Because the plugin is managed by Spring Boot I would expect at least a short hint within the Release Notes/Migration Guide.

**Comment by wilkinsona** [comment]
Thanks, @mvitz. I've added [a section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#git-commit-id-maven-plugin) to the release notes.
