### ISSUE TITLE
Wavefront integration requires API_KEY making it impossible to use the basic freemium version

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-boot#33377]
It used to be possible to use Wavefront observability without signing up:

from https://docs.wavefront.com/wavefront_springboot.html:
> Freemium All users can run the Spring Boot Starter with the default settings to view their data in the Wavefront Freemium instance. Certain limitations apply, for example, alerts are not available, but you don’t have to sign up.

After upgrading to Spring Boot 3.0 (from 2.5 so not sure when exactly was the change introduced) I am getting the error message:

```
Property management.wavefront.api-token with value 'null' is invalid: This property is mandatory whenever publishing directly to the Wavefront API
```

Not sure if this has been overlooked or it is a planned change but it effectively makes the official docs (https://docs.wavefront.com/wavefront_springboot.html) misleading.

**Comment by mhalbritter** [comment]
Hey,

the starter which is mentioned in the documentation is this one: https://github.com/wavefrontHQ/wavefront-spring-boot

Unfortunately it has no support for [Spring Boot 3](https://github.com/wavefrontHQ/wavefront-spring-boot/issues/171). The freemium automatic provision is a feature of this starter which we decided not to replicate in Spring Boot. I'll take a look if there's a workaround.

**Comment by mhalbritter** [comment]
I figured that some more people will walk into this. I've created a small application which does the provisioning part for you. Feel free to use it to provision a freemium account. The properties which are printed by the application are usable with a Spring Boot 3 application.

https://github.com/mhalbritter/wavefront-account-provisioner
