### ISSUE TITLE
MappingJackson2HttpMessageConverter with Jackson2HalModule registered ObjectMapper  was not added to the message converts

### ISSUE THREAD

**Issue by yukinami** [spring-projects/spring-boot#3337]
I'm using spring boot and HATEOAS to develop a RESTful API. And I just included the `spring-boot-starter-hateoas` module at the first time, everything works fine. My controller returned a `PagedResources` object. As a result I got a JSON object with a `_embedded ` property. 

But after I included the `spring-boot-starter-data-rest` module, the `_embedded` property in the json object my controller returned became the `content` property, which I thought the `ObjectMapper` is not registered with `Jackson2HalModule`. But JSON object returned from `Spring Data REST` was correct.
 
I looked deep into the problem and I found the ***adding halConverter logic*** was not executed in `HypermediaSupportBeanDefinitionRegistrar` and `HypermediaConfiguration` was not executed neither. But I have no idea how to solve it.

**Comment by wilkinsona** [comment]
I believe this has been fixed in https://github.com/spring-projects/spring-boot/commit/c55900b43398764d924a485b1244bfba8444eab9.
