### ISSUE TITLE
Dependency management for R2dbc MariaDb is none

### ISSUE THREAD

**Issue by wonwoo** [spring-projects/spring-boot#33388]
Spring Initializr generated

<img width="463" alt="스크린샷 2022-11-28 오후 3 57 03" src="https://user-images.githubusercontent.com/747472/204213387-52be6a7b-9a43-423c-acd0-24685c89dcc1.png">

<img width="399" alt="스크린샷 2022-11-28 오후 3 57 40" src="https://user-images.githubusercontent.com/747472/204213493-6da83617-5d96-4dc0-9740-76ee2e833275.png">

**Comment by wilkinsona** [comment]
Can you please report this to [start.spring.io](https://github.com/spring-io/start.spring.io/issues)? The MariaDB R2DBC driver used to be managed by the R2DBC bom, but there's no such bom for the current generation of R2DBC so the [version is no longer managed by Spring Boot](https://github.com/spring-projects/spring-boot/issues/31702).
