### ISSUE TITLE
Add option to change docker image name after creating it

### ISSUE THREAD

**Issue by biel-correa** [spring-projects/spring-boot#33381]
Currently my front-end team needs to:
* Generate docker image with `mvn spring-boot:build-image`
* Look for the image id with `docker images`
* Rename it with `docker image tag <id> <name>`
* Run docker-compose up

After all that they can start developing

As you can see it takes quite some time that isn't necessary, if we had an option like `mvn spring-boot:build-image -n <name>` it would be much faster.

Tell me what you guys think😄

**Comment by wilkinsona** [comment]
This is [already configurable](https://docs.spring.io/spring-boot/docs/2.7.x/maven-plugin/reference/htmlsingle/#build-image.customization). On the command line you would use `-Dspring-boot.build-image.imageName`.

**Comment by biel-correa** [comment]
Thanks @wilkinsona

**Comment by biel-correa** [comment]
Found out that you can add to pox.xml and stop using a huge command

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <configuration>
                <imageName>easy-presence/api</imageName>
            </configuration>
        </plugin>
    </plugins>
</build>
```
