### ISSUE TITLE
Document migration for Spring Security when upgrading to Spring Boot 3.0

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#33393]
Spring Security released 5.8 and 6.0 on the same day. In Spring Security 5.8 there are various deprecations (mainly from the configuration) that have been removed in 6.0. However, this is not that clear in the Spring Boot migration guide. Since there is no Spring Boot version that is using Spring Security 5.8 it means that users that are only using Spring Boot dependency management are never going to get warnings for the deprecations.

I suggest that you update the https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes and either link to https://docs.spring.io/spring-security/reference/5.8/migration/index.html or write what is written in https://docs.spring.io/spring-security/reference/5.8/migration/index.html#_update_to_spring_security_5_8.

I believe that this would make the upgrade to Spring Boot 3.0 easier for users that are using Spring Security

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I've added [something](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-security) to Spring Boot's migration guide.

**Comment by filiphr** [comment]
Thanks a lot @wilkinsona. This is really appreciated.
