### ISSUE TITLE
Spring-boot 3.0 not support flyway 7.15

### ISSUE THREAD

**Issue by gecan123** [spring-projects/spring-boot#33391]
Context: We are using MySQL 5.7 which is only supported by flyway 7.15.0 or early version. Now we are bumping up spring-boot from 2.7.5 to 3.0.0, and passed the compile step.

But failed happens in app running stage, got the error like below:

build.gradle

```
plugins {
    id 'java'
    id 'org.springframework.boot' version "3.0.0"
    id 'io.spring.dependency-management' version '1.1.0'
    ...
}
ext['flyway.version'] = '7.15.0'
```

application log
```

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureProperties(FlywayAutoConfiguration.java:204)

The following method did not exist:

    'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.placeholderSeparator(java.lang.String)'

...enter image description here


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration and org.flywaydb.core.api.configuration.FluentConfiguration
```

[FlywayAutoConfiguration](https://i.stack.imgur.com/gjNUN.png) 

in method configureProperties(FluentConfiguration configuration, FlywayProperties properties), the FluentConfiguration with 7.15.0 version don't have these properties 'placeholderSeparator', 'kerberosConfigFile'

Is this issue can be resolved by spring team? or i only can bump spring-boot to 3.0 after my database upgrade?

**Comment by wilkinsona** [comment]
With the new major release, we've taken the opportunity to drop support for older versions of Flyway. You'll have to update your database or purchase Flyway Teams which [provides support for older DB versions](https://www.red-gate.com/products/flyway/editions).

**Comment by hpoettker** [comment]
Just for the sake of completeness: You can also disable the auto-configuration of Flyway by setting the property `spring.flyway.enabled` to `false`, or let the auto-configuration back off by registering a bean of type `Flyway` with code that works with Flyway 7.15.
