### ISSUE TITLE
Build fails when use mvn clean install

### ISSUE THREAD

**Issue by arturowmex** [spring-projects/spring-boot#3342]
Hello, I just cloned the project but when I'm trying to build it using mvn clean install I got the next error:

[INFO] --- maven-invoker-plugin:1.9:run (integration-test) @ spring-boot-loader
---
[INFO] Building: executable-dir\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven
executable not found at: C:\Arturo\Desarrollo\Plugins\apache-maven-3.3.1\bin\mvn
.bat
[INFO] Building: executable-jar\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven
executable not found at: C:\Arturo\Desarrollo\Plugins\apache-maven-3.3.1\bin\mvn
.bat
[INFO] Building: executable-props\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven
executable not found at: C:\Arturo\Desarrollo\Plugins\apache-maven-3.3.1\bin\mvn
.bat
[INFO] Building: executable-war\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven
executable not found at: C:\Arturo\Desarrollo\Plugins\apache-maven-3.3.1\bin\mvn
.bat
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 4, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  executable-dir\pom.xml
[ERROR] *  executable-jar\pom.xml
[ERROR] *  executable-props\pom.xml
[ERROR] *  executable-war\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Boot Dependencies ........................... SUCCESS [  6.644 s]
[INFO] Spring Boot Parent ................................. SUCCESS [  1.721 s]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.484 s]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [ 23.803 s]
[INFO] Spring Boot Loader ................................. FAILURE [ 14.488 s]

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.889 s
[INFO] Finished at: 2015-06-27T22:29:37+01:00
[INFO] Final Memory: 100M/648M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:1.9
:run (integration-test) on project spring-boot-loader: 4 builds failed. See cons
ole output above for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.

I tried to use the full build as explained in the document CONTRIBUTING.adoc but the build fails anyway, can somebody give some pointers about why this error is happening?, my objective is run cobertura on the project so I can get the test coverage of the project.

I'm using windows 8, jdk 8, maven 3.3.1

**Comment by wilkinsona** [comment]
Looks like a problem with the invoker plugin, Windows, and Maven 3.3.1: https://issues.apache.org/jira/browse/MNG-5792. Until that's fixed, it looks like you may need to use an earlier version of Maven.

**Comment by arturowmex** [comment]
Thank you very much, I downgraded the maven version, and that error is solved.

 Now there are some failures in tests that stop the building, shall I open a new issue for those??

**Comment by snicoll** [comment]
See #3349
