### ISSUE TITLE
ConditionalOnBean should load configuration class and beanMethods that it's has imported First

### ISSUE THREAD

**Issue by adgar-shi** [spring-projects/spring-boot#33425]
if there two `ConfigurationClass`, `A` import `B`, `A` have `ConditionalOn` `B`'s Bean, I guess should load `B` first then load `A`, so that way `A` will create the right Bean with `B`'s Bean

**Comment by bclozel** [comment]
I don't understand. Could you elaborate with a concrete example or better, a sample that shows a behavior that you think is wrong?

**Comment by adgar-shi** [comment]
it is like when i use @Import i don't need using @AutoConfigureAfter

Brian Clozel ***@***.***> 于2022年12月1日周四 01:38写道：

**Comment by bclozel** [comment]
I still don't get it sorry.

**Comment by philwebb** [comment]
`@AutoConfigureAfter` is only used to sort auto-configuration classes, it doesn't have any effect on regular configuration classes. With your example above, if `RedisConnectionConfiguration` is an auto-configuration class then it should not be used with `@Import`. If it's a regular configuration class then it shouldn't be in `@AutoConfigureAfter`.
