### ISSUE TITLE
ConditionalOnProperty found different value in property 'enabled' even though enabled is set to true in application.yml

### ISSUE THREAD

**Issue by plebcity** [spring-projects/spring-boot#33436]
In my `@SpringBootTest` annotated tests it won't load the `BraveAutoConfiguration` automatically as it says that there is a different value in the property 'enabled'

```java
BraveAutoConfiguration:
      Did not match:
         - @ConditionalOnProperty (management.tracing.enabled) found different value in property 'enabled' (OnPropertyCondition)
      Matched:
         - @ConditionalOnClass found required classes 'brave.Tracer', 'io.micrometer.tracing.brave.bridge.BraveTracer' (OnClassCondition)
```

But in my `application.yml` in my test resources I have `management.tracing.enabled` set to true. (it is true by default but that doesn't seem to matter)

```yaml
spring:
  profiles:
    active: test

debug: true

management:
  tracing:
    enabled: true
```

When I start my application it does find the `BraveAutoConfiguration` and the `application.yml` has the same property set to `true`.

My test is annotated with the following annotations

```java
@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration
@AutoConfigureMockMvc
```

**Comment by mhalbritter** [comment]
If you want to have tracing in your integration tests, you need to use `@AutoConfigureObservability` as [documented here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.tracing).

**Comment by plebcity** [comment]
> If you want to have tracing in your integration tests, you need to use `@AutoConfigureObservability` as [documented here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.tracing).

Thanks, it's working now.
