### ISSUE TITLE
ConfigDataEnvironment considers overridden `spring.config.import`

### ISSUE THREAD

**Issue by sayapeg** [spring-projects/spring-boot#33446]
Our Spring Boot applications use `spring.config.import=configserver:http://config:8081` where `config` is the service name resolved automatically when deployed in a system like Docker Swarm or Kubernetes. In local systems, we override this property with the environment variable `SPRING_CONFIG_IMPORT` with `configserver:http://localhost:8081`. Using Spring Boot 2.7.6 and Spring Cloud Config 2021.0.1, it is working as expected. When we change the Spring Cloud version to `2021.0.2`, the application tries to load the properties from both `http://config:8081` and `http://localhost:8081`.

I tried debugging the issue in the `ConfigData*` classes, and it seems like both URLs, are resolved in the client application side by Spring Boot which is why I have raised this in the Spring Boot project instead of Spring Cloud Config.

A  [sample reproducer](https://github.com/sayapeg/spring-config-import-issue) is provided with branches for both working and non-working version combinations.

**Comment by sayapeg** [comment]
I tried this after upgrading to Spring Boot 3 and Spring Cloud 2022.0.0-RC3, and the result was the same.

**Comment by mhalbritter** [comment]
Thanks for the report, something is wrong here.

**Comment by sayapeg** [comment]
Thanks. One more thing I observed is this got introduced in 2.6.7.

**Comment by philwebb** [comment]
I'm going to close this one here since I don't think there's a bug in Spring Boot.

**Comment by sayapeg** [comment]
@philwebb Thanks for the clarification. Seems like this is a bug in <=2.6.6 and we have been using it as a feature as the behaviour I had mentioned with works with 2.6.6. We will proceed with your approach of `CONFIGHOST`.
