### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#33445]
I've not found stackoverflow useful for some time. Maybe that's just me, but maybe it's because the devs don't hang there. gitter of course has the issue of when someone is on (also tends to be banned by corporate firewalls, although I don't *currently* have that problem). any chance you'd consider enabling discussions on repos, and keeping an eye on them?

**Comment by mhalbritter** [comment]
I'll bring it up on the next team meeting. For reference: https://docs.github.com/en/discussions

**Comment by xenoterracide** [comment]
don't know if this came up yet, but one bonus is that you can move tickets to discussions (and I suspect vice versa), this is probably better than "we prefer to keep questions..." where the asker thought they had found a bug. P.S. not nagging here, I just checked back on this to see if I had missed something.

**Comment by landsman** [comment]
What about to do survey, poll? I am votig yes. 

GitHub is much better platform for discussion than stackoverflow now. You have everything in one place.

**Comment by landsman** [comment]
@danvega @dashaun What do you think, guys? It could be a good topic for your [Office Hours podcast](https://www.youtube.com/@SpringSourceDev). Ask the community.

I think an official forum would really push the community forward, and I am ready to help with that. 🫡

The costs of running the forum, if it was solved through Discourse, can be paid from some Patreon, GitHub sponsorship, etc.

**Comment by wilkinsona** [comment]
Thanks for the input, @landsman, but this isn't a decision that can be made by the community, or indeed by the Spring Boot team alone. If the discussions/forum are to be official, it would require a commitment from all of the Spring maintainers that they're willing and able to be involved. The Spring team has yet to reach agreement on that as we have many other priorities and demands on our time. Until then, third-party venues like stackoverflow.com and springbuilders.dev are your best option.

**Comment by landsman** [comment]
See I never heard about Springbuilders. Official place for discussion is must have from my POV. GitHub is just easiest minimum without costs for runing it. I understand the aspect that mantainers have to agree with. 

Anyway, just for the possibility to allow the community, new people to discuss with each other in the expected place is a good reason. Stackoverflow is no longer the place where new developers want to discuss, as we have been used to for years. I see it today and every day when I train juniors.

Another good example: https://github.com/symfony/symfony/discussions

**Comment by philwebb** [comment]
I'm going to raise this again with the broader Spring team. Discussions can be enabled at an organization level, which would seem better than having them Spring Boot specific (especially as many Spring Boot questions end up being ultimately for other projects). Since this topic is no longer Spring Boot specific, I'll close this one.

**Comment by landsman** [comment]
@philwebb thank you, that make sense. 

I would consider starting community discussion only with a disclaimer that no one from maintainers is responsible for managing it yet, and we'll see. To make this happen faster.
