### ISSUE TITLE
Sanitizer has not default implementation - SB3

### ISSUE THREAD

**Issue by michael-wirth** [spring-projects/spring-boot#33448]
Sensitive environment properties are not sanitized in SB3

There is no key-based sanitation of environment properties as in SB2.

The default behavior has been removed and I assume it should be replaced with a SanitizingFunction. But there is no registered bean  (yet?). Is there something missing or is it on purpose?

Without any registered SanitizingFunction the Sanitizer won't do anything at all.

https://github.com/spring-projects/spring-boot/commit/47effdcade47f5b0ab2cf6c7c3e2ed41e66bde08#diff-eff1d5fafbb45ff5ee51a9ebb415f157c4949d67c64cd410c981cf5a1f5a5e09L52

**Comment by philwebb** [comment]
This is intentional. We found it was impossible to write a `SanitizingFunction` that would consistently and correctly work against everything. There's [this section in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-endpoints-sanitization) that explains things, but please let us know if you think it needs fleshing out.

**Comment by scottfrederick** [comment]
> Sensitive environment properties are not sanitized in SB3

All environment properties should be santized by default now, unless the property `management.endpoint.env.show-values` is set to somthing other than the default as mentioned in the migration guide. If that's not the case for you, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by michael-wirth** [comment]
I don't really understand the intention of the default to hide every single environment property. To achieve that I can just disable the endpoint.

I'd like to see the actual values EXCEPT for sensitive credentials as it was in SB2. In SB3 I can just sanitize all or nothing. To achieve the same behavior as in SB2 I must implement a custom SanitizingFunction. Is that your expectation?

In the example below I'd expect that the property "my.password" is hidden and all other values are readable.


```json

        {
            "name": "Config resource 'class path resource [application.properties]' via location 'optional:classpath:/'",
            "properties": {
                "management.endpoint.env.show-values": {
                    "origin": "class path resource [application.properties] - 3:37",
                    "value": "ALWAYS"
                },
                "management.endpoints.web.exposure.include": {
                    "origin": "class path resource [application.properties] - 4:43",
                    "value": "*"
                },
                "my.password": {
                    "origin": "class path resource [application.properties] - 1:13",
                    "value": "password"
                },
                "my.user": {
                    "origin": "class path resource [application.properties] - 2:9",
                    "value": "user"
                }
            }
        }

```
