### ISSUE TITLE
Mybatis compatibility problem 

### ISSUE THREAD

**Issue by l-qiang** [spring-projects/spring-boot#33442]
Same as this problem：[https://github.com/mybatis/spring/issues/30](https://github.com/mybatis/spring/issues/30)
Occurs only in `spring.aot.enabled=true`。

**Comment by bclozel** [comment]
Sorry but there's nothing we can do with so little information.
Maybe you should first get support from the MyBatis team and then report back here only if they consider that this is a Spring issue.

Thanks
