### ISSUE TITLE
Auto-configuration broken when upgrading to 3.0.0

### ISSUE THREAD

**Issue by aigloss** [spring-projects/spring-boot#33459]
Custom auto-configured beans are not included in the context anymore after upgrading to version 3.0.0.
Haven't found any related information, neither in Release Notes nor in the documentation for 3.x, about having to perform any special action to keep auto-configuration working.

Please, check this repository for a simple example: https://github.com/aigloss/spring-boot-autoconfiguration-error

**Comment by mhalbritter** [comment]
This is documented here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration

Spring Boot 3.0 dropped support for `spring.factories` for auto-configuration.

**Comment by welsh** [comment]
@mhalbritter the documentation should be updated for this: https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/howto.html#howto.application.customize-the-environment-or-application-context

As it appears to still reference the `spring.factories` as being a valid approach:

> * Declaratively, for all applications, by adding a META-INF/spring.factories and packaging a jar file that the applications all use as a library.

**Comment by scottfrederick** [comment]
@welsh `spring.factories` is still used to register many types of classes, including the ones mentioned in that section of the documentation. The links that Moritz shared describing the move to the `AutoConfiguration.imports` file format only relates to auto-configuration classes.
