### ISSUE TITLE
PostgreSqlJdbcIndexedSessionRepositoryCustomizer has no effect

### ISSUE THREAD

**Issue by devopsix** [spring-projects/spring-boot#33463]
`PostgreSqlJdbcIndexedSessionRepositoryCustomizer` makes the `JdbcIndexedSessionRepository` use a modified SQL query for creating session attributes which handles conflicting inserts better than the original query. In Spring Boot 2.7 all you had to do was adding a `PostgreSqlJdbcIndexedSessionRepositoryCustomizer` bean to the application context. In Spring Boot 3.0 that no longer seems to work.

## Steps to Reproduce

I have pushed a [minimal reproducible example](https://github.com/devopsix/spring-boot-session-issue) to GitHub.

The example contains 2 versions of the same test application, one based on Spring Boot 2.7.6, the other one based on Spring Boot 3.0.0. Both share this configuration:

```java
package org.devopsix.boot.session;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.session.jdbc.PostgreSqlJdbcIndexedSessionRepositoryCustomizer;

@Configuration
public class SessionConfig {

    @Bean
    public PostgreSqlJdbcIndexedSessionRepositoryCustomizer postgreSqlJdbcIndexedSessionRepositoryCustomizer() {
        return new PostgreSqlJdbcIndexedSessionRepositoryCustomizer();
    }
}
```

1. Check out the example.
2. Run `mvn -f spring-boot-2.7/pom.xml verify`
3. Run `mvn -f spring-boot-3.0/pom.xml verify`

The first command will print something like this:

```
2022-12-05 15:08:07.234 DEBUG 6284 --- [o-auto-1-exec-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [INSERT INTO SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) VALUES
 (?, ?, ?) ON CONFLICT (SESSION_PRIMARY_ID, ATTRIBUTE_NAME) DO UPDATE SET ATTRIBUTE_BYTES = EXCLUDED.ATTRIBUTE_BYTES]
```

The _presence_ of `ON CONFLICT ...` means the modified SQL query is being used.

The second command will print something like this:

```
2022-12-05T15:08:52.170+01:00 DEBUG 13560 --- [o-auto-1-exec-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [INSERT INTO SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)
VALUES (?, ?, ?)
]
```

The _absence_ of `ON CONFLICT ...` means the modified SQL query is _not_ being used.

## Suspected Cause and Potential Work-Arounds

[`JdbcSessionConfiguration.springBootSessionRepositoryCustomizer` adds another customizer](https://github.com/spring-projects/spring-boot/blob/c9c359fd271d1b51bf16f50d685c49fa40ca1b8a/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/JdbcSessionConfiguration.java#L67) to the application context.
[`JdbcHttpSessionConfiguration.sessionRepository` happens to apply `PostgreSqlJdbcIndexedSessionRepositoryCustomizer` before the other customizer](https://github.com/spring-projects/spring-session/blob/77e062b2cd3a3db37bb41fdc389c7af6f0eb125f/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L147). Unfortunately, the other customizer seems to cause [`JdbcIndexedSessionRepository#prepareQueries`](https://github.com/spring-projects/spring-session/blob/77e062b2cd3a3db37bb41fdc389c7af6f0eb125f/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcIndexedSessionRepository.java#L663) to be invoked again which overrides the customized query.

Adding `@Order(Ordered.LOWEST_PRECEDENCE)` to the `PostgreSqlJdbcIndexedSessionRepositoryCustomizer` bean has not helped. As far as I understand, the other customizer (implicitly) also has `LOWEST_PRECEDENCE` and hence that does not change the order of application.

I ended up adding an `InitializingBean` bean to the application context which in its `afterPropertiesSet` method applies `PostgreSqlJdbcIndexedSessionRepositoryCustomizer` to the repository bean again.

**Comment by philwebb** [comment]
Closing in favor of PR #33663 33514

**Comment by izeye** [comment]
The above comment seems to reference a wrong issue. It seems to need to be https://github.com/spring-projects/spring-boot/pull/33514, not https://github.com/spring-projects/spring-boot/pull/33663.

**Comment by wilkinsona** [comment]
Thanks, @izeye. I've updated Phil's comment.
