### ISSUE TITLE
Remove Jetty / Netty / Apache HttpClient checks for WebClient

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33474]
With https://github.com/spring-projects/spring-framework/issues/29644 the `WebClient` doesn't need external dependencies anymore. If no netty / jetty / Apache HttpClient is found, it falls back to the `JdkClientHttpConnector` which is baked into the JDK.

At least in `org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizerFactory` we check for the presence of netty / jetty / apache httpclient. This check can be removed, and maybe such checks are somewhere else in the codebase.

**Comment by wilkinsona** [comment]
I wonder if we should consider this a bug? Looking at the code, the checks are preventing the auto-configuration of a `WebTestClient` that uses the `JdkClientHttpConnector`.

**Comment by scottfrederick** [comment]
Closing in favor of #33640.
