### ISSUE TITLE
Support bootRun-style inclusion of src/main/resources on classpath when running in-IDE

### ISSUE THREAD

**Issue by cbeams** [spring-projects/spring-boot#3347]
Ideally, when running in-IDE, e.g. via IDEAs dedicated Spring Boot app Run Configuration, a change to a static resource should be picked up immediately by the running application, avoiding the need for even so much as clicking F9 to trigger copying to output directories.

See the conversation in Gitter starting [here](https://gitter.im/spring-projects/spring-boot?at=55911a5398f9c0bc3da076f3) and ending [here](https://gitter.im/spring-projects/spring-boot?at=55912cf2b4ce4e473250b6fc) for details.

**Comment by snicoll** [comment]
Before we decide to do this on Gradle, I'd like we revisit the decision of removing duplicates from `target/classes`. I am still not sure why we're doing this if `src/main/resources` is the first entry on the classpath.

**Comment by philwebb** [comment]
It might be worth @snicoll talking to JetBrains about this. I'm guessing that we could to something special with our classloader _if_ we know where to find the resources. Given that Eclipse and IDEA work quite differently here we'd probably need to have this as an opt-in option rather than on by default.

JetBrains could probably implement this directly themselves and have things work much better than if we try to do it from Boot.

**Comment by snicoll** [comment]
ping  @yanncebron

The latest EAP has [auto-make support with devtools](https://youtrack.jetbrains.com/issue/IDEA-141638) but I am not sure it's "auto-copying" resources when you change them.

IJ has already a dedicated support for Spring Boot app so it would be possible to add the sources in the classpath and treat them specifically. Yann, what do you think?

**Comment by YannCebron** [comment]
this should work out-of-the box (maybe with a slight delay after detecting FS changes triggering automake)

**Comment by philwebb** [comment]
Nice, thanks @YannCebron. I'll close this one, @cbeams please re-open if the latest IJ EAP doesn't solve things.

**Comment by cbeams** [comment]
Hey @philwebb, @YannCebron, see my [comments on the YouTrack issue](https://youtrack.jetbrains.com/issue/IDEA-141638#comment=27-1047628).
