### ISSUE TITLE
springboot 3: ConstructorBinding does not work with kotlin primary constructor

### ISSUE THREAD

**Issue by vinh-hoang** [spring-projects/spring-boot#33471]
Version: Springboot 3.0.0 the @ConstructorBinding annotation does not work with the Kotlin primary constructor. 
The Annotation is written on the class itself and produces the error "This annotation is not applicable to target 'class'".

**Comment by vinh-hoang** [comment]
Hi, thanks for the response. In version 2.7.x it works like this ([example](https://www.baeldung.com/kotlin/spring-boot-configurationproperties#2-constructor-binding-option) from baeldung):
```kotlin
@ConfigurationProperties(prefix = "api")
@ConstructorBinding
data class ApiConfiguration(
    val clientId: String,
    val url: String,
    val key: String
)
```
 So I assume this style will not be supported anymore?

**Comment by mhalbritter** [comment]
This is documented here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#constructingbinding-no-longer-needed-at-the-type-level

In your case you can drop the `@ConstructorBinding` because Spring Boot is now clever enough to use the sole constructor.
