### ISSUE TITLE
Write an AMQP section in the documentation

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3348]
We do have a JMS section in the [Messaging section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-messaging) but we don't have one for AMQP/RabbitMQ

**Comment by lucassaldanha** [comment]
@snicoll how are you in this documentation? I did some work on it and maybe it can help. Should I do a PR and you can take a look?

**Comment by snicoll** [comment]
awesome!
