### ISSUE TITLE
Problem with jakarta JMS and brave for spring boot 3.0 BOM

### ISSUE THREAD

**Issue by bademux** [spring-projects/spring-boot#33487]
Sorry if its wrong project, please point me there I can report it.

According to 
https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/dependency-versions.html#appendix.dependency-versions.coordinates
brave version is 5.14.1, but for JMS it uses `javax` package. It is incompatible with SpringBoot 3.0 expectation.
https://github.com/openzipkin/brave/blob/5.14.1/instrumentation/jms/src/main/java/brave/jms/JmsTracing.java#L34

**Comment by marcingrzejszczak** [comment]
This has nothing to do with Boot. You should create an issue in Brave. We can instrument JMS in Spring without using JmsTracing.

**Comment by bclozel** [comment]
Closing. See micrometer-metrics/tracing#124 for Marcin's suggestion.

**Comment by bademux** [comment]
@marcingrzejszczak  @bclozel 
 I definitely will prepare some tasks for brave as well.
 
 But I can't agree with you guys - spring dependencies decoratively point to the version of brave that is incompatible with spring 3.0.
https://github.com/spring-projects/spring-boot/blob/v3.0.0/spring-boot-project/spring-boot-dependencies/build.gradle#L76

 While I think moving forward with jakarta and all new stuff is great, I think it is worth to document major incompatibilities.
