### ISSUE TITLE
When a BeanDefinitionRegistryPostProcessor bean is depends on a properties bean, the properties bean will not load the properties from application.yml

### ISSUE THREAD

**Issue by wangliang181230** [spring-projects/spring-boot#33491]
`application.ym` :
![图片](https://user-images.githubusercontent.com/1527893/206368592-a26faa15-b108-491e-905d-8adbda7181a5.png)

the `SeataAutoDataSourceProxyCreator` :
![图片](https://user-images.githubusercontent.com/1527893/206368456-2400b1bf-79f1-485a-a62f-0d1bfece2bca.png)

instantiate `SeataAutoDataSourceProxyCreator`:
![图片](https://user-images.githubusercontent.com/1527893/206368383-0d611a7f-9d8a-4ed9-b04c-13ac32f34e77.png)

Is this a bug? 
I think the environment has been loaded. It can provide the properties.

springboot: 2.5.14 or 2.7.6 is tested.
When I remove the `BeanDefinitionRegistryPostProcessor` from the implements, it will load properties normally.

**Comment by kse-music** [comment]
SeataAutoDataSourceProxyCreator implements `BeanDefinitionRegistryPostProcessor` lead to premature instantiation, various `BeanPostProcessor` not instantiate yet, such as processing bean Configuration binding's `ConfigurationPropertiesBindingPostProcessor`, so the SeataProperties  will not be processed.

**Comment by wangliang181230** [comment]
> SeataAutoDataSourceProxyCreator implements `BeanDefinitionRegistryPostProcessor` lead to premature instantiation, various `BeanPostProcessor` not instantiate yet, such as processing bean Configuration binding's `ConfigurationPropertiesBindingPostProcessor`, so the SeataProperties will not be processed.

If I need some properties, can I only read them from the environment?

**Comment by kse-music** [comment]
> > SeataAutoDataSourceProxyCreator implements `BeanDefinitionRegistryPostProcessor` lead to premature instantiation, various `BeanPostProcessor` not instantiate yet, such as processing bean Configuration binding's `ConfigurationPropertiesBindingPostProcessor`, so the SeataProperties will not be processed.
> 
> If I need some properties, can I only load them from the environment?

maybe you can write like this

    public SeataAutoDataSourceProxyCreator seataAutoDataSourceProxyCreator(Environment environment, SeataProperties seataProperties){
        Binder.get(environment).bind("seata", Bindable.ofInstance(seataProperties));

        return new SeataAutoDataSourceProxyCreator (...);
    }

**Comment by bclozel** [comment]
@wangliang181230 I think @kse-music is right, `BeanDefinitionRegistryPostProcessor` is applied on bean definitions, way before any instantiation occurs. You cannot rely on properties beans being resolved and created at this phase of the application context. You can always bind directly from the environment, but note that chances are that `EnvironmentPostProcessor` were not applied at this stage so you might get the wrong property value. I'd suggest revisiting this contract with the context lifecycle in mind.

**Comment by wangliang181230** [comment]
@bclozel @kse-music Think you for your answer. I have got it.

**Comment by wangliang181230** [comment]
> but note that chances are that `EnvironmentPostProcessor` were not applied at this stage so you might get the wrong property value. I'd suggest revisiting this contract with the context lifecycle in mind.

@bclozel I tested, the `EnvironmentPostProcessor` is loaded first.
