### ISSUE TITLE
websercice soap 

### ISSUE THREAD

**Issue by DavidDXY** [spring-projects/spring-boot#33490]
Spring Boot :3.0.0-SNAPSHOT
this is a soap webservice application
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web-services</artifactId>
		</dependency>
		<dependency>
			<groupId>wsdl4j</groupId>
			<artifactId>wsdl4j</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.ws.xmlschema</groupId>
			<artifactId>xmlschema-core</artifactId>
			<version>${xmlschema.version}</version>
			<scope>runtime</scope>
		</dependency>
problem:
when i use "mvn -Pnative clean native:compile" To create the executable, it run fine,but when i get the wsdl file,it throw err "java.lang.ClassNotFoundException: org.springframework.ws.soap.saaj.SaajSoapMessageFactory",
![image](https://user-images.githubusercontent.com/28525559/206361026-1716c263-5273-4e0a-89c2-c525f500cd3a.png)
i use soapUI test the endpoint ,it throw error "Could not initialize WebServiceMessageReceiverHandlerAdapter"
![image](https://user-images.githubusercontent.com/28525559/206361231-deee1299-1ec8-4297-ad0a-8e09269e99e4.png)

**Comment by bclozel** [comment]
I don't think Spring WS supports AOT and GraalVM Native at the moment. Please create an enhancement request on the project. [I've added a section in our wiki about this](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#spring-web-services).

Thanks!
