### ISSUE TITLE
spring-boot aot Specifies whether netty is supported

### ISSUE THREAD

**Issue by Maijh97** [spring-projects/spring-boot#33501]
version
  JDK: 17
  spring-boot: 3.0.0

The introduction of spring-boot-starter-data-redis using graalvm to build the project causes the following exceptions.
`Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.netty.util.internal.SystemPropertyUtil.getInt(java.lang.String, int) 
Parsing context:
`
netty is referenced by spring-boot-starter-data-redis，
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/37288946/206674311-6c495575-8dc2-4f33-aa67-c01b7bf32431.png">

**Comment by mhalbritter** [comment]
Hey. Can you share an example project where we can reproduce that issue? Please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
