### ISSUE TITLE
Spring Webfilters and Kotlin Coroutines

### ISSUE THREAD

**Issue by akoufa** [spring-projects/spring-boot#33506]
Hello and thanks for the great work. I am heavily using Spring Boot Webflux together with Kotlin and Coroutines. I wanted to ask, if it is planned to introduce a Coroutine aware Webclient and a suspending Webfilter. So instead of using 

`
override fun filter(exchange: ServerWebExchange, chain: GatewayFilterChain): Mono<Void>
`
to be able to use something like the following:

`
override suspend fun filter(exchange: ServerWebExchange, chain: GatewayFilterChain)
`

I think having to use Reactor in some places and Coroutines in others does not allow for a consistent coding patterns for Spring Boot Kotlin users.

**Comment by philwebb** [comment]
This is a request you'd need to raise with the Spring Framework team at https://github.com/spring-projects/spring-framework/issues.
