### ISSUE TITLE
Property to enable SPDY / HTTP2.0 in Undertow server

### ISSUE THREAD

**Issue by cbelleza** [spring-projects/spring-boot#3350]
Hi,

It would be nice to have a property to enable SPDY / HTTP2.0 for Undertow server in application.properties.

I mean something like:

```
server.undertow.options=ENABLE_SPDY    # (ENABLE_HTTP2 or ENABLE_SPDY)
```

That would reflect into embedded web server the following code:

```
    @Bean
    public UndertowEmbeddedServletContainerFactory embeddedServletContainerFactory() {
        final UndertowEmbeddedServletContainerFactory undertowEmbeddedServletContainerFactory = new UndertowEmbeddedServletContainerFactory();
        undertowEmbeddedServletContainerFactory.addBuilderCustomizers(new UndertowBuilderCustomizer() {
            @Override
            public void customize(final Builder builder) {
                builder.setServerOption(UndertowOptions.ENABLE_SPDY, true);
            }
        });

        return undertowEmbeddedServletContainerFactory;
    }
```

Keeping in mind I should also add to java execution the ALPN library by all means:
-Xbootclasspath/p:C:\bin\alpn-boot-8.1.3.v20150130.jar

**Comment by ofbizbrazil** [comment]
Is there any idea when this enhancement will be available on Spring Boot?

**Comment by philwebb** [comment]
@ofbizbrazil Nobody is currently working on it. It looks like @eddumelendez might have tried something but I don't think I've seen a PR. You're welcome to contribute yourself if you have time.

**Comment by ofbizbrazil** [comment]
I took a look at the the codes of @eddumelendez has written on github, and they look what I really meant for.

His task is waiting for a commit to final release, see status: **_**"eddumelendez wants to merge 1 commit into spring-projects:master"**_**

https://github.com/spring-projects/spring-boot/pull/3904/files

Could you please confirm or may know when it will be committed to master release?

Tks,

**Comment by philwebb** [comment]
@ofbizbrazil Ahh, thanks. I'd missed the pull-request. It's not been assigned a target milestone yet so there's no immediate ETA.

**Comment by ofbizbrazil** [comment]
Awesome to hear it! 

I look forward to having this option on Spring Boot,  it will increase the performance of https protocol without doubts.  

If you could give a special atention including this feature into the next release,  I'd appreciate a lot. 

Tks a lot @philwebb

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/pull/3904#issuecomment-190159915

**Comment by JonattanV** [comment]
The http2 is already in tomcat?

**Comment by bclozel** [comment]
duplicates #10043
