### ISSUE TITLE
Devtools 3.0 is not compatible with apt-maven-plugin under Oracle JDK 19.0.1

### ISSUE THREAD

**Issue by wnameless** [spring-projects/spring-boot#33507]
I am woking a project with Spring Boot 3.0 and using apt-maven-plugin with the MongoAnnotationProcessor from Spring Data.

During the developing, I include spring-boot-devtools in my Maven dependencies and everything works fine if I use corretto64-17 JDK as my development environment.

After I changed to Oracle JDK 19.0.1(for virtual threads), each time I modified my source codes and the auto-reboot of devtools was triggered, the auto-generated classes from apt-maven-plugin became undetected until I manually stopped the whole application and started it again.

This issue makes the devtools useless for me under JDK 19.0.1.

My environment details:
CPU: Apple M1 Pro
OS: MacOS 13.0.1
JDK: Oracle JDK 19.0.1
IDE: Visual Studio Code 1.74.0
Spring Boot: 3.0.0
apt-maven-plugin: 1.1.3

**Comment by bclozel** [comment]
Can you share a minimal sample that would allow us to reproduce the issue? Ideally something we can git clone and run. Thanks !

**Comment by wnameless** [comment]
I just tried to create a sample in Eclipse IDE, but everything suddenly became normal in Eclipse. I guess that this issue is refer to a bug of VScode instead of Spring Boot Devtools. Thanks for listening. 

What's more, if I run VScode with JDK 17 but Spring Boot App with JDK 19, this issue is also solved somehow.

**Comment by bclozel** [comment]
Thanks for letting us know!
