### ISSUE TITLE
uuid = bytea\n Hint: No operator matches the given name and argument types in spring boot 3

### ISSUE THREAD

**Issue by RoopaRJ** [spring-projects/spring-boot#33517]
Hi,

i have migrated from spring boot 2.7.5 to 3.0.0 , the java version we are using is 17,dialect i am using is org.hibernate.dialect.PostgreSQLDialect  after migration i am getting issue while saving records to db wherever uuid is present and the exception i am getting is uuid = bytea\n Hint: No operator matches the given name and argument types. You might need to add explicit type casts

the entity looks like:
@Entity
@Table(name = "abc", schema = "abcd")
data class ABCEntity(
        @Id
        @Column(name = "id")
        private var id: UUID,
}

Repository looks like:
@Repository
interface ABCEntityRepo : JpaRepository<ABCEntity, UUID>

**Error log:
org.hibernate.engine.jdbc.spi.SqlExceptionHelper","level":"ERROR","msg":"ERROR: operator does not exist: uuid = bytea\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 175"}**

**Comment by mhalbritter** [comment]
Hey, Spring Boot 3.0 updated to [Hibernate 6.1](https://in.relation.to/2022/06/24/hibernate-orm-61-features/). Please make sure to read their changelog, too.

If the problem still persists, please open an issue on the [Spring Data JPA issue tracker](https://github.com/spring-projects/spring-data-jpa).
