### ISSUE TITLE
Hibernate breaks after Maven export

### ISSUE THREAD

**Issue by DxsSucuk** [spring-projects/spring-boot#33513]
Using any Springboot with these Hibernate dependencies breaks Hibernate after exporting the Project with maven.
```xml
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>6.1.6.Final</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-community-dialects</artifactId>
            <version>6.1.6.Final</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-hikaricp</artifactId>
            <version>6.1.6.Final</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>5.0.1</version>
        </dependency>
```

While running the application in an IDE calling a query will give me my Entity back.
But running the application standalone after exporting it with maven will only return its primary-key on call instead of the entity object with given data.

Im facing this Issue in my own projekt here https://github.com/Ree6-Applications/Webinterface

To repdroduce this you will need atleast 2 entries in a table and then just try to access both of these as entites over the `SQLWorker` class by using `getEntityList`.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by DxsSucuk** [comment]
Understandable, the Issue with StackOverflow is that most often you do not receive an answer, but I will try!

**Comment by bclozel** [comment]
Debugging entire 3rd party projects and looking for probably Hibernate changes during an upgrade is not sustainable from our point of view. You can get better chances at an answer on StackOverflow if you manage to create a minimal reproducer that removes all that's not necessary.

**Comment by DxsSucuk** [comment]
I understand, also for [Stackoverflow](https://stackoverflow.com/questions/74772881/hibernate-does-not-work-in-a-spring-enviroment-after-maven-export)
