### ISSUE TITLE
Recommended naming for custom starters in test scope

### ISSUE THREAD

**Issue by scordio** [spring-projects/spring-boot#33527]
The reference documentation [recommends](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration.custom-starter.naming) `acme-spring-boot-starter` as a pattern for a custom starter name. 

What if the `acme` feature has additional flavors to be auto-configured in tests? Is there any naming recommendation for the corresponding test-scoped starter?

I could imagine:
* `acme-spring-boot-starter-test`
* `acme-test-spring-boot-starter`

**Comment by wilkinsona** [comment]
The recommendation to use a `spring-boot-starter` suffix still applies so I would go with `acme-test-spring-boot-starter`.

**Comment by scordio** [comment]
Hi @wilkinsona, I assume the `acme-test-spring-boot-starter` recommendation still holds, considering the new `spring-boot-starter-XXX-test` naming pattern, right?

Now that test starters exist, I think it would be nice to have [the documentation](https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.custom-starter.naming) cover this use case as well. If agreed, I'd be happy to compose a PR for it.

**Comment by wilkinsona** [comment]
Yes, I think it should still hold. An `acme-test-spring-boot-starter` starter is a starter for something named `acme-test`. On the other hand, an `acme-spring-boot-starter-test` would be a starter used for testing when you're also using `acme-spring-boot-starter`.

**Comment by scordio** [comment]
Then I'm getting confused 🙃 in my use cases, the intention is to have test-specific auto configurations for an `acme` feature. The test auto configuration fine-tunes what the productive starter provides, e.g., replacing the productive bean definition with a testing-compatible one using a custom `BeanDefinitionRegistryPostProcessor`.

If I re-read your last comment, I think you're suggesting going with `acme-spring-boot-starter-test`?

**Comment by wilkinsona** [comment]
Ah, sorry. I misunderstood your question and my second and third sentences then contradicted the first. Let me have another go.

In 4.0, we adopted the `-test` suffix. This gave us names like `spring-boot-starter-webmvc-test`. This is a starter that's intended to be in test scope for testing functionality that's written using `spring-boot-starter-webmvc`. If you have a third-party starter named `acme-spring-boot-starter`, applying the same `-test` suffix would result in `acme-spring-boot-starter-test` and I think that makes sense.

Before we document something, let me double-check with the rest of the team and see what they think. As ever, naming is hard.

**Comment by scordio** [comment]
> As ever, naming is hard.

💯 😄 

Just a small nudge – this issue is closed, so I'm not sure if it'll pop up in your team's review. 

I'm also happy to open a new one, if it makes more sense.

EDIT: I see [there are a few more](https://github.com/spring-projects/spring-boot/issues?q=state%3Aclosed%20label%3A%22for%3A%20team-meeting%22) recently labelled, so I might just be on the wrong path 🙂 sorry for the noise!

**Comment by philwebb** [comment]
After discussion we're going to update the docs to recommend `acme-spring-boot-starter-test`

**Comment by scordio** [comment]
Should I raise a PR, or would you prefer to handle it within the team?

EDIT: I raised #49014, but feel free to close it if you prefer to handle it differently!

**Comment by snicoll** [comment]
Closing in favor of PR #49014 - Thanks again, @scordio!
