### ISSUE TITLE
The parent form a cycle with spring-boot-starter-parent:3.0.0 with Java 17 & Eclipse

### ISSUE THREAD

**Issue by escon1004** [spring-projects/spring-boot#33525]
When I try to make example of Spring Boot 3.0.0, the error messages occured like below. 

`The parents form a cycle: com.example:testapp:0.0.1-SNAPSHOT -> org.springframework.boot:spring-boot-starter-parent:3.0.0 -> org.springframework.boot:spring-boot-starter-parent:3.0.0	pom.xml	/demo	Unknown	Language Servers`

this is my pom.xml 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>testapp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>demo</name>
	<description>TestApp for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

and if I switch the spring boot starter parent version from 3.0.0 to 2.7.6 or lower, the error message is solved. I guess it is just for 3.0.0

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

**Comment by bclozel** [comment]
Maybe this is a tooling issue?
There has been changes in the Starter parent, but [I don't see any reference to itself](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.0.0/spring-boot-starter-parent-3.0.0.pom) or hints of a cycle.

Does the `Unknown Language Servers` message also happens with Spring Boot 2.7.x?

**Comment by escon1004** [comment]
> Maybe this is a tooling issue? There has been changes in the Starter parent, but [I don't see any reference to itself](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.0.0/spring-boot-starter-parent-3.0.0.pom) or hints of a cycle.
> 
> Does the `Unknown Language Servers` message also happens with Spring Boot 2.7.x?

No, I dont have any problem with 2.7.6 and lower version.

and yes, maybe It was a kind of tooling issues, I deleted `springframework` folder in maven repository directory `C:\Users\user\.m2\repository\org\springframework`, and downloaded it again. 

now I dont have any problem with 3.0.0 now thank you your answer!
