### ISSUE TITLE
Clarify that spring.security.filter properties only apply to servlet-based web apps

### ISSUE THREAD

**Issue by tgeens** [spring-projects/spring-boot#33551]
Should it be documented (or fixed) that `spring.security.filter.order` is ignored in the reactive stack ?

Context: I'm trying to convert an auto-configuration-enabled library to the reactive-stack. It uses a filter that should be registered before the spring-security-filter. The servlet variant is using `SecurityProperties.getFilter().getOrder()` as a best-effort attempt to find out the order of the spring-security-filter.

`WebFluxSecurityConfiguration` uses a fixed `@Order(WEB_FILTER_CHAIN_FILTER_ORDER)` - but the `WEB_FILTER_CHAIN_FILTER_ORDER` is a magic number, with only package visiblity.

**Comment by wilkinsona** [comment]
This feels like an oversight to me. I think we should explore applying the property to the reactive stack.

**Comment by wilkinsona** [comment]
It occurs to me that applying `spring.security.filter.order` to the reactive stack will create confusion with the `spring.security.filter.dispatcher-types` property which is Servlet-specific. If we want the order property to apply to be web stacks, we may need to rename `spring.security.filter.dispatcher-types` to make it clear that it's Servlet-specific.

**Comment by bclozel** [comment]
[There's a section in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.reactive.webflux.web-filters) that we can revisit as part of this issue if we want to do so.
