### ISSUE TITLE
BootLanguageServerBootApp class is taking all available cpu continuously

### ISSUE THREAD

**Issue by davidmichaelkarr** [spring-projects/spring-boot#33625]
I don't know if this belongs in this repository or not. It's not clear to me how to figure out a better one.

I recently noticed that there is a Java process taking as much cpu as possible.

This is the command line for it:

```
"C:\Program Files\Java\jdk-18.0.2.1\bin\javaw.exe" -cp C:\Users\dk068x\eclipse\java-2022-12\eclipse\..\..\..\.p2\pool\plugins\org.springframework.tooling.boot.ls_1.41.0.202212060707\servers\spring-boot-language-server\BOOT-INF\classes;C:\Users\dk068x\eclipse\java-2022-12\eclipse\..\..\..\.p2\pool\plugins\org.springframework.tooling.boot.ls_1.41.0.202212060707\servers\spring-boot-language-server\BOOT-INF\lib\* -Dsts.lsp.client=eclipse -Dlsp.completions.indentation.enable=true -Xmx1024m -XX:TieredStopAtLevel=1 -Xlog:jni+resolve=off -Dspring.config.location=file:C:\Users\dk068x\eclipse\java-2022-12\eclipse\..\..\..\.p2\pool\plugins\org.springframework.tooling.boot.ls_1.41.0.202212060707\servers\spring-boot-language-server\BOOT-INF\classes\application.properties org.springframework.ide.vscode.boot.app.BootLanguageServerBootApp --languageserver.hover-timeout=225
```

I recently installed Eclipse 2022-12, with the STS feature.  My eclipse.ini sets maxmem to 2048mb.  There's nothing obviously significant in the Eclipse error log, but the language server log is filling continuously, and many lines are like this:

```
java.lang.OutOfMemoryError: Java heap space
```

I imagine that's hitting the limit of 1024mb as specified in that command line, as opposed to the 2048mb limit in my main Eclipse process.

I'm also looking at other log lines in the language server log.  It appears to be scanning all projects continuously.  I'm not doing anything but watching all this happen.

**Comment by bclozel** [comment]
Could you open this against https://github.com/spring-projects/sts4/issues ?
