### ISSUE TITLE
SpringBoot3 can not autoconfigure my well configured gRpc

### ISSUE THREAD

**Issue by LaiJinwen** [spring-projects/spring-boot#33634]

**Comment by LaiJinwen** [comment]
I write down my own maven file like below, but my springboot application do not start gRpc server as i expected, and  it work well on springboot 2.7.
        
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-client-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-server-spring-boot-starter</artifactId>
        </dependency>

Finally I have to use @Imort(GrpcAdviceAutoConfiguration.class,   GrpcHealthServiceAutoConfiguration.class + ~~~~~), it work!

I don`t know if this is a bug or there is something I do wrong.

**Comment by arvgord** [comment]
It seems that the latest supported version is v2.6.13 for grpc-spring-boot-starter. See https://github.com/yidongnan/grpc-spring-boot-starter/releases/tag/v2.14.0.RELEASE

**Comment by LaiJinwen** [comment]
> It seems that the latest supported version is v2.6.13 for grpc-spring-boot-starter. See https://github.com/yidongnan/grpc-spring-boot-starter/releases/tag/v2.14.0.RELEASE

I think this is not the key. For 2 reason :(1)AutoConfiguration is springboot inner function,unless there is something changed in springboot version3, it should work well. (2)Event thought It seems that the latest supported version is v2.6.13 for grpc-spring-boot-starter, but it still work well in v2.7.3 (My leader tell me to upgrade to v3.0.0 last week).

**Comment by bclozel** [comment]
@LaiJinwen Please reach out to the starter maintainers about Spring Boot 3 support.

> AutoConfiguration is springboot inner function,unless there is something changed in springboot version3, it should work well

There was, Spring Boot 3.0 is a major version with baseline requirements changes. See [this auto-configuration change](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files).

**Comment by samir4114** [comment]
> I write down my own maven file like below, but my springboot application do not start gRpc server as i expected, and it work well on springboot 2.7.
> 
> ```
>     <dependency>
>         <groupId>net.devh</groupId>
>         <artifactId>grpc-client-spring-boot-starter</artifactId>
>     </dependency>
>     <dependency>
>         <groupId>net.devh</groupId>
>         <artifactId>grpc-server-spring-boot-starter</artifactId>
>     </dependency>
> ```
> 
> Finally I have to use @imort(GrpcAdviceAutoConfiguration.class, GrpcHealthServiceAutoConfiguration.class + ~~~~~), it work!
> 
> I don`t know if this is a bug or there is something I do wrong.

How to implement this?
