### ISSUE TITLE
Any replacement for Schema Created Event?

### ISSUE THREAD

**Issue by Blacktoviche** [spring-projects/spring-boot#33639]
I have an app that need to be notified on Schema Created which was in spring autoconfigure old versions 
DataSourceSchemaCreatedEvent was deprecated since 2.5.0 with no replacement.
`Deprecated
since 2.5.0 for removal in 2.7.0 with no replacement as the event is no longer published`

Is there any way to achieve such a task using maybe another event?

**Comment by wilkinsona** [comment]
It's hard to say without knowing what you were doing upon schema creation. You may be able to use `@DependsOnDatabaseInitialization` on a`@Bean` method to ensure that the database has been initialized before the bean is created.

**Comment by Blacktoviche** [comment]
I'm preparing the database with some custom configuration. 
is @DependsOnDatabaseInitialization the same as DataSourceSchemaCreatedEvent? 
I mean doing the same job ?

I'm gonna try it. Thanks

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
