### ISSUE TITLE
AbstractSecurityWebSocketMessageBrokerConfigurer in method configureInbound dosen't work with keycloak token

### ISSUE THREAD

**Issue by mmsayekooie** [spring-projects/spring-boot#33642]
Hello every one I created an issue in https://github.com/BijanVan/Spring-Boot-Websocket-Sample/issues/1#issue-1512135406  regarding spring-websocket-security and also i read and implement base on [spring websocketSecurity](https://docs.spring.io/spring-security/site/docs/4.0.x/reference/html/websocket.html) but unfortunately have problem and i red several stackoverflow which have same problem please please some one take care about my issue although i think this is a bug also there is a sample address in document which i couldn't found it.

**Comment by wilkinsona** [comment]
AbstractSecurityWebSocketMessageBrokerConfigurer is part of Spring Security. If you believe you've found a bug, please open a Spring Security issue with a minimal sample that reproduces the problem.
