### ISSUE TITLE
EndpointRequestMatcher is missing toString() method

### ISSUE THREAD

**Issue by tvahrst** [spring-projects/spring-boot#33647]
For compliance reasons, we do need a kind of "web security configuration report" for all of our spring-boot applications. This report should print the http authorization rules (list of path matching rules with corresponding auth-configs).

We made a simple implementation which retrieves the spring security filter chain, finds the `FilterSecurityInterceptor` Filter and prints the containing requestMap (which maps `RequestMatcher` to `Collection<ConfigAttribute`).

While most spring-security `RequestMatcher` implementations (for example `AntPathRequestMatcher`, `MvcRequestMatcher`...) provides a explicit `toString()` method, the class `EndpointRequest.EndpointRequestMatcher` does not. 

It would help us, if the `EndpointRequestMatcher` would provide a toString() method similar to spring-security requestmatchers.

**Comment by tvahrst** [comment]
At first view I thought, implementing `toString()` should be easy, using the existing `protected createDelegate()` method to obtain a delegate RequestMatcher to invoke `toString()` on. But this doesn't work out of the box, because `createDelegate()` needs references to `WebApplicationContext` and `RequestMatcherFactory` to create the delegate RequestMatcher. 

Additionally, the resulting delegate `RequestMatcher`  does not print the paths of Endoints which are not exposed to the web. (see #13749). 

So i would propose a 'simple' `toString()`  implementation which prints the `EndpointIds` of `include` and `exclude` variables  and the value of `includeLinks`. 
For example
```
public String toString(){
	StringBuilder sb = new StringBuilder();
	sb.append("EndpointIds [ includes=");
	if (includes.isEmpty()) {
		sb.append("[*]");
	} else {
		sb.append(includes.stream().map(this::getEndpointId).collect(Collectors.toList()));  // spring 6: toList()
	}
	if (!excludes.isEmpty()) {
		sb.append(" excludes=");
		sb.append(excludes.stream().map(this::getEndpointId).collect(Collectors.toList()));  // spring 6: toList()
	}
	sb.append(" includeLinks=").append(includeLinks);
	sb.append("]");
	return sb.toString();
}
```

Depending on the object type in `include` and `exclude`, `getEndpointId()` has to obtain the endpointid from the `@Endpoint` annotation of the provided class. I don't  now, whether this may be to expensive for a `toString()` method. Optionally the toString() result could be cached because `EndpointRequestMatcher` is immutable.

**Comment by wilkinsona** [comment]
Closing in favour of #33654.

**Comment by wilkinsona** [comment]
#33654 has been closed. Re-opening.

**Comment by mhalbritter** [comment]
Closing in favor of #33690.
