### ISSUE TITLE
Section of the Spring Boot 3.0 migration guide is no longer valid

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-boot#33644]
Hello, thank you for all your hard work!

I am a member of the OpenRewrite team and I have been working on a composite recipe to help users with their Spring Boot 3.0 migration. [This recipe includes upgrading to Java 17, Jakarta EE 9, and then includes items noted in your migration guide.](https://github.com/openrewrite/rewrite-spring/issues/257)

As I have been working through this recipe I noticed an item to [move the micrometer binders to a new package](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#micrometer-binders).

I believe the [Micrometer team reverted](https://github.com/micrometer-metrics/micrometer/issues/3119) the binder package relocation and this section of the migration guide can be removed.

**Comment by philwebb** [comment]
Thanks! I've removed the section. I copied it from earlier release notes without enough care.
