### ISSUE TITLE
Upgrade to Kotlin 1.8

### ISSUE THREAD

**Issue by meshpaul** [spring-projects/spring-boot#33655]
Enhancement related to https://github.com/spring-projects/spring-framework/issues/29754

**Comment by wilkinsona** [comment]
Marking as blocked for now as we'll need to see what Framework does and coordinate across the portfolio.

**Comment by wilkinsona** [comment]
@sdeleuze Given that Framework 6.0 should work fine with Kotlin 1.8, should we consider this for 3.1?

**Comment by sdeleuze** [comment]
Yes, I would be in favor of that.

**Comment by wilkinsona** [comment]
We upgrade to Kotlin 1.8.10 in 3.1.0.M1 (https://github.com/spring-projects/spring-boot/issues/34285).
