### ISSUE TITLE
GroovyTemplateProperties extends AbstractViewResolverProperties instead of AbstractTemplateViewResolverProperties

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#3365]
Is there a reason why `GroovyTemplateProperties` doesn't extend `AbstractTemplateViewResolverProperties`? This would allow for easy setting of the `exposeRequestAttribtue` property which would be needed when wanting to expose the `_csfr` property from spring security (that is available as attribute).

**Comment by philwebb** [comment]
It's probably just a hang over from when we had our own `GroovyTemplateView` class that didn't extend `AbstractTemplateView`. Since 18b8929335b3c14d190610a80bef58b2cf5095ca fixed that we can probably switch `GroovyTemplateProperties`.
