### ISSUE TITLE
Dev tools unreliable static file serving (quick folder deleting then copy file into)

### ISSUE THREAD

**Issue by robozb** [spring-projects/spring-boot#33668]
Dear Developers, 

1. run the spring boot project in dev environment (Netbeans 12.2)
2. an npm script (build,copyfiles) modifies some files in a maven project folder "\src\main\resources\static\assets" (some js files as well)
3. in the browser sometimes the file serving is well sometimes I get back 404 error code

Spring Version: 2.7.7 (spring-boot-devtools)

May I ask how can I debug this situation? How can I check the file watching process?

Thanks for any help in advance!

Bela

![DevToolError](https://user-images.githubusercontent.com/8656998/210314036-88d1ee26-627c-4f2b-9995-cfd9997e2914.JPG)

**Comment by robozb** [comment]
I tried to use this options without success, the file serving is rhapsodic

![DevToolsOptions](https://user-images.githubusercontent.com/8656998/210314936-2d94541c-c649-4cf0-a44d-a7488666a3be.JPG)

**Comment by robozb** [comment]
The dependency: 

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>  
```

**Comment by wilkinsona** [comment]
Can you please provide a minimal sample that reproduces the problem?

**Comment by robozb** [comment]
> 

Ok, I try it!

**Comment by robozb** [comment]
Until my sample/simple project creation, I made a short video what presents my problem well. 

The Spring Boot Dev Tools(?) doesn't reflect the modification by npm copyfiles script but all good if I initiate the modification in IDE by insert only one space :(

https://youtu.be/aS8xNQSn2S4

**Comment by robozb** [comment]
OK, I guess I figured out what's the problem. The Dev Tools doesn't copy files from /src/main/resources/static/ (or from other folders I guess) to /target/classes/static/ if it happens quickly after a folder deletion.

https://youtu.be/a-P0BflLzig

**Comment by robozb** [comment]
How can I debug Dev Tools?

**Comment by robozb** [comment]
A workaround could be to paralel copy the files to src and target folder :(

**Comment by robozb** [comment]
> > OK, I guess I figured out what's the problem. The Dev Tools doesn't copy files from /src/main/resources/static/ (or from other folders I guess) to /target/classes/static/ if it happens quickly after the folder deletion.
> 
> Dev Tools never performs such copying. It's the job of your IDE or build system to do so. Looking at the video, you're using NetBeans so I suspect that this is a NetBeans bug and it's missing the changes made in `src/main/resources` and failing to copy them into `target/classes`.
> 
> If you believe the problem is somehow specific to Spring Boot's Dev Tools, please provide a minimal sample that we can use to reproduce it and we can re-open the issue and take another look.

Oh, I didn't know! Thank you so much!
