### ISSUE TITLE
Spring Boot 3.0.1 war package not work on apache-tomcat 8.5.84

### ISSUE THREAD

**Issue by KamelZOUBA** [spring-projects/spring-boot#33660]
I try to deploy a simple Spring Boot project 3.0.1 with JDK 17 on apache tomcat 8.5.84.
When I lunch tomcat, I servlet container doesn't load Spring Boot configuration.
The same project works fine with Spring Boot 2.7.7
Here is github link to the project:
https://github.com/KamelZOUBA/spring-boot-war-example/tree/springboot-3.0.1-java-17
And the same project with Spring Boot 2.7.7:
https://github.com/KamelZOUBA/spring-boot-war-example/tree/springboot-2.7.7-java-17

**Comment by mdeinum** [comment]
Spring Boot 3 requires Tomcat 10.x as it is based on JakartaEE. Your tomcat is JavaEE and that isn't supported by Spring Boot 3.
