### ISSUE TITLE
security enhancement

### ISSUE THREAD

**Issue by k4n5ha0** [spring-projects/spring-boot#33667]
first, this issues not security vulnerabilities. And all tricks is opened for long time.

reason：
1.upload file with Non standard boundary to bypass waf
![89908473cc680898ff2e9eba9f78fd3e_640_wx_fmt=png wxfrom=5 wx_lazy=1 wx_co=1](https://user-images.githubusercontent.com/22064977/210227519-3b9152be-48e7-4bc6-8100-9a772484f705.png)

![aca90327a99ed8b9577cead268ec98c7_640_wx_fmt=png wxfrom=5 wx_lazy=1 wx_co=1](https://user-images.githubusercontent.com/22064977/210227523-b5f3d450-e9fd-44d1-884d-43baa948acef.png)

2.Cp037 bypass waf
![f6a76d724e4aa95cf9251a93c114d6ba_640_wx_fmt=png wxfrom=5 wx_lazy=1 wx_co=1](https://user-images.githubusercontent.com/22064977/210227534-2dbea431-f335-44a5-b801-55080e0cb5be.png)

3.upload file with / in the end to  bypass waf
![891931f701bcc4d142b33c5070057178_640_wx_fmt=png wxfrom=5 wx_lazy=1 wx_co=1](https://user-images.githubusercontent.com/22064977/210227544-222b4a9a-d12c-48bb-a068-5cc2ebb8bac6.png)

4.upload file with Non standard http method to  bypass waf
![2f4dea4b756e8ec65a3a5475d923d537_640_wx_fmt=png wxfrom=5 wx_lazy=1 wx_co=1](https://user-images.githubusercontent.com/22064977/210227550-8e6d466e-8fad-4839-96e6-fbbfdcd1f861.png)

5.upload file with rfc6266(filename*)  to  bypass waf
![image](https://user-images.githubusercontent.com/22064977/210228877-52ad2ff5-fa14-4fa9-95a0-f1605b140ef5.png)

![c3322e55dde68e94201137f005ec4798](https://user-images.githubusercontent.com/22064977/210228731-653e763a-dd2d-42f6-9218-e2775ee66c24.jpg)

![image](https://user-images.githubusercontent.com/22064977/210228713-9cf8b61e-940e-4a39-b20d-1e8678f60e0d.png)

enhancement：
with CommonsMultipartResolver and StandardServletMultipartResolver.
spingboot configuration file should limit which fileExt can upload, i think a allowlist is security.

**Comment by wilkinsona** [comment]
@k4n5ha0 As described in the issue template, all possible security issues should follow the process described in  https://spring.io/security-policy. This allows the team to double-check that a problem isn't a vulnerability before it is public knowledge. In line with this, I am going to delete this issue. Please follow the process described in https://spring.io/security-policy providing details of the problems that would be avoided by restricting the file extensions that can be uploaded.
