### ISSUE TITLE
WebMvcTags to ServerRequestObservationConvention migration

### ISSUE THREAD

**Issue by janchristian-haddorp** [spring-projects/spring-boot#33673]
Starting with Spring Boot 3.0.0 the class WebMvcTags is deprecated and should be replaced by DefaultServerRequestObservationConvention.

WebMvcTags containts specials mapping logic for Spring Data REST.

```
private static String getMatchingPattern(HttpServletRequest request) {
    PathPattern dataRestPathPattern = (PathPattern) request.getAttribute(DATA_REST_PATH_PATTERN_ATTRIBUTE);
    if (dataRestPathPattern != null) {
        return dataRestPathPattern.getPatternString();
    }
    return (String) request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE);
}
```

This functionality is missing on DefaultServerRequestObservationConvention. Will there be a full featured replacement?

**Comment by bclozel** [comment]
I've just reported this issue to spring-data-rest with the relevant information, see spring-projects/spring-data-rest#2212.
I'm closing this one has this needs to be addressed in data REST directly. Thanks for letting us know!
