### ISSUE TITLE
org.springframework.boot.loader package is gone in Spring Boot 3?

### ISSUE THREAD

**Issue by charlesxucheng** [spring-projects/spring-boot#33670]
I got an java.lang.ClassNotFoundException: org.springframework.boot.loader.PropertiesLauncher when trying to upgrade my app. Checked and found the org.springframework.boot.loader package is there in 2.7.7 documentation but completely missing in 3.0.1 documentation. And I cannot find any deprecation note in the 2.7 documentation. So what happened? Is it removed on purpose? Thanks.

https://docs.spring.io/spring-boot/docs/2.7.7/api/org/springframework/boot/loader/package-summary.html
https://docs.spring.io/spring-boot/docs/3.0.1/api/index.html

**Comment by wilkinsona** [comment]
The [class](https://github.com/spring-projects/spring-boot/blob/v3.0.1/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/PropertiesLauncher.java) is still part of the `spring-boot-loader` module. This module's classes are [no longer included in the aggregated javadoc](https://github.com/spring-projects/spring-boot/issues/31955) to better reflect the fact that we don't really expect applications to depend upon them.
