### ISSUE TITLE
Upgrade to Jackson 2.15

### ISSUE THREAD

**Issue by DRoppelt** [spring-projects/spring-boot#33679]
I know you usually do create these tickets automatically, but I am curious if we will see Jackson 2.15 in boot 3.0 or at least 3.1

In 2.15, there is a jakarta-specific change, see here:

- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
- https://github.com/FasterXML/jackson-datatype-hibernate/issues/158

Given the PR description here, 2.14.X might even be breaking in some cases with hibernate 6.0 and 6.1: https://github.com/FasterXML/jackson-datatype-hibernate/pull/162

**Comment by wilkinsona** [comment]
It will be Spring Boot 3.1 at the earliest.
