### ISSUE TITLE
Spring Boot Native 3.0.1 Fails to start when using spring data jpa, h2 and spring web

### ISSUE THREAD

**Issue by mihaita-tinta** [spring-projects/spring-boot#33684]
Spring Boot Native 3.0.1 fails to start when using spring data jpa, h2 and spring web. It gives the error below:

`IllegalStateException: No available JtaPlatform candidates  when running the spring boot native image using`

I created [here](https://github.com/mihaita-tinta/spring-boot-3-issue-jpa-native-image-run) a sample project and the steps to reproduce the problem. Please note that running the application as an executable jar or docker image works fine. I assume it should work by default with spring native too.

**Comment by scottfrederick** [comment]
@mihaita-tinta Thanks for trying the Spring Boot 3 native support. The issue with your sample is that you are missing some build configuration. As shown in the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#native-image.developing-your-first-application.buildpacks.maven), you need the Native Build Tools plugin in your `pom.xml`: 

```
  <build>
    <plugins>

      ...

      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
```

Your sample works for me after adding this plugin. 

If you compare your `pom.xml` to one [generated by start.spring.io](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.0.1&packaging=jar&jvmVersion=17&groupId=com.example.demo&artifactId=jpa-native&name=jpa-native&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo.jpa-native&dependencies=data-jpa,native,h2,web), you'll see that there is also some suggested Hibernate configuration. 

Can you try adding the NBT plugin to your build and see if it fixes your problem?

**Comment by mihaita-tinta** [comment]
After adding the plugin, I can also run the native image.
