### ISSUE TITLE
Consider adding component scan packages alias for SpringBootApplication

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3368]
Some projects can't use `SpringBootApplication` because they need to tune the packages to scan. Maybe we could add an alias to the annotation?

**Comment by philwebb** [comment]
Can we use the new `@AliasFor` annotation so that attributes have better names (`scanBasePackages`)?

**Comment by snicoll** [comment]
Probably, yeah.

**Comment by michaelisvy** [comment]
I agree that it would be great to be able to list out the list of packages to be scanned.

**Comment by shakuzen** [comment]
:+1: for this. We can't use `SpringBootApplication` in some of our applications because of the current limitation.

**Comment by sbrannen** [comment]
Cool to see more use of `@AliasFor`! :grinning:
