### ISSUE TITLE
Expose more JNDI properties when configuring a JmsListenerContainerFactory

### ISSUE THREAD

**Issue by fml2** [spring-projects/spring-boot#33680]
I want to use a JMS connection whose factory is stored in JNDI. To access the JNDI, I must specify the initial context factory's class and also the JNDI provider URL.

To my surprise, I found out that this is not possible with just the SpringBoot properties, see [this question on StackOverflow](https://stackoverflow.com/q/74995340/6023830).

The [JmsProperties object](https://github.com/spring-projects/spring-boot/blob/3bcc7ece55f88f3de6e59253205bfb5342d45a67/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/JmsProperties.java#L43) only has a property for the name of the entry for the connection and has no properties to correctly access/build up that context.

As of now, I specify the following Java system properties when starting my program (a standalone one) so that the JMS factory is found:
* `java.naming.factory.initial`
* `java.naming.provider.url`

But this is not the Spring way to do things. Also, it's too global. In my case, the two settings should only be used for getting the JMS connection factory, not other JNDI objects. E.g. a datasource (if I used one) might be somewhere else.

IMO those properties should also be exposed via JmsProperties. Or it should be documented how to use custom values here.

As of now, I'm going to create/configure some JNDI related beans manually in order to avoid the need to use Java system properties.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Using JNDI in a Spring Boot application is quite unusual, even more so when requiring a custom initial context per object. As you've already described, what you want to do is already possible by manually retrieving the `ConnectionFactory` from JNDI and exposing it as a bean. Given this situation, I'm not sure that we can justify adding support for this. I'll flag this for discussion at a team meeting to see if there's a preferred course of action among the team.

If we were to do anything here, it should be done consistently. Spring Boot has three application properties that can be used to retrieve a bean from JNDI:

- `spring.datasource.jndi-name`
- `spring.jms.jndi-name`
- `spring.mail.jndi-name`

**Comment by fml2** [comment]
> Spring Boot has three application properties that can be used to retrieve a bean from JNDI

This was the reason why I expected to be able to do it with just the "inbuilt" properties. By having these properties, SpringBoot makes the statement that it allows to retrieve the objects by specifying some properties. But this promise is implemented to 30% only.

**Comment by wilkinsona** [comment]
We have discussed this today and we are in agreement that the benefits of implementing this are outweighed by the added complexity. Please continue defining your own `ConnectionFactory` bean instead. Thanks anyway for the suggestion.

**Comment by fml2** [comment]
Although I think that two additional properties would not add much complexity, I'm fine with your decision.
