### ISSUE TITLE
Documentation should be there for better understanding in SpringApplicationAdminMXBeanRegistrar.java

### ISSUE THREAD

**Issue by deepak1067** [spring-projects/spring-boot#33685]

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
