### ISSUE TITLE
Auto-configure a JwtAuthenticationConverter

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-boot#33689]
Hi,
I learn the below way to customize the authority prefix and claim name. Would like to suggest provide configuration properties to allow developer to easily customize the JwtAuthenticationConverter, so that developer does not have to write these boilerplate codes

```java
@Bean
    public JwtAuthenticationConverter jwtAuthenticationConverter() {
        JwtGrantedAuthoritiesConverter grantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
        grantedAuthoritiesConverter.setAuthorityPrefix("");
        //grantedAuthoritiesConverter.setAuthoritiesClaimName("role");
        JwtAuthenticationConverter jwtAuthenticationConverter = new JwtAuthenticationConverter();
        jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(grantedAuthoritiesConverter);
        return jwtAuthenticationConverter;
    }
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. It looks like we could auto-configure a `JwtAuthenticationConverter` bean if there's no such existing bean in the context and a property has been set for the principal claim name, the authority prefix, or the authorities claim name.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-projects/spring-boot/pull/38105.
