### ISSUE TITLE
spring-boot:build-image fails with 401

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-boot#33699]
I'm using Spring Boot 2.7.7

Running 

    mvn spring-boot:build-image 

produces

```
Spring Cloud Bindings 1.10.0: Contributing to layer
[INFO]     [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute spring-cloud-bindings layer
[INFO]     [creator]     unable to get dependency spring-cloud-bindings
[INFO]     [creator]     unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
[INFO]     [creator]     could not download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar: 401
[INFO]     [creator]     ERROR: failed to build: exit status 1

```

**Comment by simasch** [comment]
It looks like this is causing the problem: https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023

**Comment by jeisinge** [comment]
FYI - A possible work around is available at https://github.com/paketo-buildpacks/spring-boot/issues/225#issuecomment-1186597162

**Comment by scottfrederick** [comment]
Similar download errors will happen for the following libraries when building images from a plain war file that requires Tomcat to run: 

* `tomcat-access-logging-support`
* `tomcat-lifecycle-support`
* `tomcat-logging-support`

See the Paketo Apache Tomcat buildpack issue here: https://github.com/paketo-buildpacks/apache-tomcat/issues/295
