### ISSUE TITLE
SDKMAN should not use repo.spring.io for releases

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#33705]
See https://github.com/spring-projects/spring-boot/blob/3bcc7ece55f88f3de6e59253205bfb5342d45a67/ci/images/releasescripts/src/main/java/io/spring/concourse/releasescripts/sdkman/SdkmanService.java#L43

**Comment by sannanansari** [comment]
Hi @philwebb, can I contribute to this issue. I have gone through #33702.

**Comment by wilkinsona** [comment]
Closing in favor of #33702. Thanks, @sannanansari.

**Comment by breun** [comment]
According to https://issues.apache.org/jira/browse/MNG-5151 Maven first used `repo1.maven.org`, but later decided on making `repo.maven.apache.org` the default hostname for Maven Central, so maybe that should be used?

**Comment by wilkinsona** [comment]
Thanks, @breun. I've opened https://github.com/spring-projects/spring-boot/issues/33938.
