### ISSUE TITLE
Fix invalid link in Spring Boot 3.0 Migration Guide (wiki)

### ISSUE THREAD

**Issue by hjjae2** [spring-projects/spring-boot#33717]
[dependency management for 3.0.x](https://docs.spring.io/spring-boot/docs/3.0.0-SNAPSHOT/reference/html/dependency-versions.html#appendix.dependency-versions) is an invalid URL.

The link below seems correct.
https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/dependency-versions.html#appendix.dependency-versions

**Comment by wilkinsona** [comment]
Thanks for pointing this out. The migration guide has been updated.
