### ISSUE TITLE
Controller level exceptions not getting populated in HTTP server requests metrics

### ISSUE THREAD

**Issue by bunty-raghani** [spring-projects/spring-boot#33731]
Exceptions handled at the controller level are not populated in the http.server.requests metrics.

As per the [official docs](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.error-handling), we need to set the request attribute in @ExceptionHandler method before returning a response. I tried this approach but exceptions are not included in "availableTags -> exception array".

Observed this issue only for exceptions that are handled at the controller level. For other exceptions, that are internally handled by the spring framework, such exceptions are visible in metrics.

**Endpoint:** /actuator/metrics/http.server.requests
**Spring Boot Version:** 3.0.1 (also, tried 3.0.2-SNAPSHOT)

**Comment by wilkinsona** [comment]
Thanks for filling in some blanks for me, @bclozel. @bunty-raghani there's no need for a sample now.

> Should we consider this a bug then and apply those changes in the next maintenance version?

Yes, I think we should.

**Comment by bunty-raghani** [comment]
Thank you @bclozel & @wilkinsona for considering this issue and for providing the required help. I tried the new code snippet and it is working fine.  Also, apologies for not attaching the sample code to reproduce this issue. 

Thank you once again for all your help!

Regards,
Bunty Raghani

**Comment by bunty-raghani** [comment]
Kindly ignore the closed and reopened message, it happened by mistake. Spring team will fix this in future versions as mentioned above.
