### ISSUE TITLE
Review Google AppEngine documentation

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33730]
In https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment.cloud.google, we document how to run a Boot application in Google AppEngine. It contains this snippet:

```
runtime_config:
  jdk: "openjdk8"
```

This won't work, as Spring Boot 3.x needs Java 17. I'm not sure if AppEngine has support for Java 17. If it has, update the snippet in the documentation.

**Comment by shantanusingh10** [comment]
Right now GCP only supports jdk8 and jdk11. So, what can we do for this requirement of Java 17 ?

**Comment by snicoll** [comment]
There are some other bits that are outdated in that section.
