### ISSUE TITLE
Package tangle from OnManagementMvcCondition

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3373]
The new `OnManagementMvcCondition` is causing a package tangle since it depends on `ManagementServerProperties`.

It looks like it's currently only use in `EndpointWebMvcAutoConfiguration` (unless it's indented to be publicly used). We might be able to use a custom `ImportSelector` and use the existing `ManagementServerPort` logic.

**Comment by philwebb** [comment]
@dsyer Does `@OnManagementMvcCondition` need to be public? Can we move it to `org.springframework.boot.actuate.autoconfigure` and make it package private?

**Comment by dsyer** [comment]
Possibly not.
