### ISSUE TITLE
Saml2RelyingPartyAutoConfiguration ignores `sign-request` when `metadata-url` is used

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-boot#33747]
Related to https://github.com/spring-projects/spring-security/issues/11818

The order of precedence for `security.relyingparty.{id}.assertingparty.signlesignon.sign-request` should be like this:

1. Use whatever the application declares `sign-request` to be
2. Use what comes back from the `metadata-url` query
3. Otherwise, default to `true`

But it is currently like this:

1. Use what comes back from the `metadata-url` query
2. Use whatever the application declares `sign-request` to be
3. Otherwise, default to `true`

**Comment by philwebb** [comment]
@jzheaux Do we need to change [this `when` check?](https://github.com/spring-projects/spring-boot/blob/17d4fb1e604a721a1470d9d20e10eca022f23dab/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyRegistrationConfiguration.java#L106). Do you consider this a bug or something we should only change in 3.1. I wonder if it can break existing applications if we change things now?

**Comment by jzheaux** [comment]
The behavior that this is causing it with configurations like this:

```
metadata-url: ...
sign-request: ...
```

The `sign-request` property is getting ignored. I think this would be surprising and would consider it a bug. IOW, it seems clear to me that if a property is specified, it would be expected for that property to get applied. That said, there is a workaround, which is to declare a `RelyingPartyRegistrationRepository` bean.

> Do we need to change [this when check?](https://github.com/spring-projects/spring-boot/blob/17d4fb1e604a721a1470d9d20e10eca022f23dab/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyRegistrationConfiguration.java#L106)

Possibly. IIRC, the difficulty was it being able to tell the difference between whether the `signRequest` property in `Saml2RelyingPartyProperties` is set to `true` or is simply unset. It seems to me that this property would need to be a `Boolean` so that it can be `null` and it can be clear that the application left it unset.
