### ISSUE TITLE
Remove usage of bean definition instance supplier since not compatible with AOT

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#33763]
Bean definitions with instance supplier callbacks can't be supported by design on AOT as explained in spring-projects/spring-framework#29555. Spring Framework is going to document this and throw an exception during AOT processing of such bean via spring-projects/spring-framework#29556 instead of silently ignoring the instance supplier when a default constructor on the bean class is found.

While working on changing that behavior, I noticed a few Spring Boot beans are defining instance suppliers (there may be other ones, this is just on a simple app): 
 - `org.springframework.boot.context.properties.BoundConfigurationProperties`
 - `org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor`
 - `org.springframework.boot.web.server.ErrorPageRegistrarBeanPostProcessor`
It currently works because the instance supplier references the bean class default constructor and because Spring Framework silently ignores them, but we would like to report proper error to the user when that's the case.

Could you please update Spring Boot codebase to remove the few usages of bean instance suppliers? I will also check the other project portfolio via the AOT smoke tests and reach the related teams.

**Comment by sdeleuze** [comment]
`org.springframework.boot.context.properties.ConfigurationPropertiesBinder` is using a customized instance supplier [here](https://github.com/spring-projects/spring-boot/blob/433364601d5fd8e0ac5e4742c3d702a5c9c2fabc/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBinder.java#L201), not sure if that's currently handled on AOT side or just silently ignored for now.

**Comment by mhalbritter** [comment]
I found these places where we use an instance supplier: 

* org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration.WsdlDefinitionBeanFactoryPostProcessor#registerBeans
* org.springframework.boot.context.properties.BoundConfigurationProperties#register
* org.springframework.boot.autoconfigure.web.reactive.ReactiveWebServerFactoryAutoConfiguration.BeanPostProcessorsRegistrar#registerSyntheticBeanIfMissing
* org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration.BeanPostProcessorsRegistrar#registerSyntheticBeanIfMissing
* org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrar#createBeanDefinition

Not 100% sure that i found them all.

**Comment by mhalbritter** [comment]
I started working on it here: https://github.com/mhalbritter/spring-boot/tree/mh/33763

I'm unable to solve these usages: 

* https://github.com/spring-projects/spring-boot/compare/main...mhalbritter:spring-boot:mh/33763#diff-042b71e7bd1c7eea6983864b2beaf3a3d1fe0c5fe639a3fbd714803a5509f41fR126
* https://github.com/spring-projects/spring-boot/compare/main...mhalbritter:spring-boot:mh/33763#diff-15738a2bb718ae22ba5f76e792cd8b88e594d00632e52dcb427ac79670cfa22aR96

And i'm not sure if this change has unintended consequences: https://github.com/spring-projects/spring-boot/compare/main...mhalbritter:spring-boot:mh/33763#diff-b0ed32f4a0da8cbbfe5f60b78374c8bb3715c6fea7c6577d1b5333c33b459b55R190

Any help would be appreciated :)

**Comment by sdeleuze** [comment]
For `@ConfigurationProperties`, I am not familiar with that part, but maybe this use case is already handled by `ConfigurationPropertiesBeanRegistrationAotProcessor` so no change is needed on that part? We can maybe do some experiment with a Boot version on top of https://github.com/spring-projects/spring-framework/commit/d9101ab48f79e133d7e18ba7a5e164d170e2e065 and check whats works and what does not.
