### ISSUE TITLE
How to allow anonymous classes to execute reflection in native-image?

### ISSUE THREAD

**Issue by wangliang181230** [spring-projects/spring-boot#33769]
```java
public class SerializationMembers implements Caching {

    private static final Method NO_METHOD = (new Object() {
        private void noMethod() {
        }
    }).getClass().getDeclaredMethods()[0];

}
```

![图片](https://user-images.githubusercontent.com/1527893/211997958-6f517ba9-13fa-4153-a7ee-320e650842da.png)

**Comment by bclozel** [comment]
Is this failing at runtime in a native image? Given the deterministic nature of this reflection it might be inlined already by GraalVM.
This looks like a 3rd party library, have you tried contributing reachability metadata to it?

**Comment by wangliang181230** [comment]
> 

I only register like this:
```java
try {
	Class<?> clazz = Class.forName("com.thoughtworks.xstream.core.util.SerializationMembers$1");
	hints.reflection().registerType(clazz, MemberCategory.INVOKE_DECLARED_METHODS);
} catch (ClassNotFoundException e) {
	// do nothing
}
```

**Comment by bclozel** [comment]
What do you mean it has no effect? Are you seeing a failure at runtime?
Maybe try [running your application with the tracing agent](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/AutomaticMetadataCollection.md) to get the proper metadata entry?

In any case, I don't think you should be contributing metadata for xstream using Spring's `RuntimeHints` API - this should be contributed by the library itself, or [the reachability metadata repository](https://github.com/oracle/graalvm-reachability-metadata). I'm closing this issue as a result.
