### ISSUE TITLE
Add R2DBC observation auto-configuration

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#33768]
Currently, the code exists in the spring experimental repository.
https://github.com/spring-projects-experimental/r2dbc-micrometer-spring-boot

This project provides Spring Boot auto configuration for Micrometer Tracing for R2DBC.
This ticket aims to move the code into Spring Boot.

**Comment by travispeloton** [comment]
any updates on this?

**Comment by mhalbritter** [comment]
To set the remote service, the `ObservationProxyExecutionListener` wants the R2DBC url. Reconstructing the R2DBC url when given a `ConnectionFactory` is hard, i've opened https://github.com/r2dbc/r2dbc-proxy/issues/135 for an improvement. When https://github.com/r2dbc/r2dbc-proxy/issues/135 is done, we can refactor the code in `org.springframework.boot.actuate.autoconfigure.r2dbc.R2dbcObservationAutoConfiguration#extractUrl`.

**Comment by syz51** [comment]
hey there. I see this is closed and this feature is included in 3.2.0-M2 release. Is there any pointers to how to enable this auto-configuration now? When I use r2dbc and actuator, it doesn't seem to auto configure the tracing components automatically. Much appriatiated.

**Comment by bclozel** [comment]
@syz51 you'll need the `"io.r2dbc:r2dbc-proxy"` dependency on your classpath.

**Comment by syz51** [comment]
@bclozel thanks!
