### ISSUE TITLE
DataSourceHealthIndicator identifies wrong validation query

### ISSUE THREAD

**Issue by quaso** [spring-projects/spring-boot#3377]
I am using `DB2` database where `DataSourceHealthIndicator#getProduct()` returns "`DB2/LINUXX8664`". However `PRODUCT_SPECIFIC_QUERIES` map contains just "`DB2`" key, so validation query is set to default, which is wrong.

**Comment by snicoll** [comment]
Yeah, I suspected that this `DB2` name was too lenient compared to what I saw on the web. The problem is that there isn't one name but many ones so we need to find a pattern.

**Comment by snicoll** [comment]
See #2565
