### ISSUE TITLE
Enable bomr to filter GraphQL versions

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33817]
GraphQL has 500+ releases with a timestamp that I'd love to see filtered as well.

_Originally posted by @snicoll in https://github.com/spring-projects/spring-boot/issues/32457#issuecomment-1253445847_

**Comment by mhalbritter** [comment]
Some examples of the GraphQL versions:

- `2018-11-15T21-34-13-6aa96be-ignored-chars`
- `2021-05-03T08-53-12-8f1ec444`
- `230521-nf-execution`

**Comment by snicoll** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/5022e120c17ca832dc2b07e6059f7b431aeab7ca
