### ISSUE TITLE
Wrong OpenRewrite Link in Spring Boot 3.0 Migration Guide 

### ISSUE THREAD

**Issue by claudioaltamura** [spring-projects/spring-boot#33826]
The OpenRewrite link on the page [Spring Boot 3.0 Migration Guide ](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide) does not work.

https://docs.openrewrite.org/reference/recipes/java/migrate/javaxmigrationtojakarta is wrong. It should be **https://docs.openrewrite.org/reference/recipes/java/migrate/jakarta/javaxmigrationtojakarta**

Since the wiki is not editable, please update the link 😁

**Comment by wilkinsona** [comment]
Thanks for reporting this. I've updated the link.
