### ISSUE TITLE
spring是一个备受欢迎的框架，使用者遍布全球，希望官方文档能有国际化的支持，让各国人阅读更方便

### ISSUE THREAD

**Issue by twg123** [spring-projects/spring-boot#33820]

**Comment by philwebb** [comment]
Google Translate: Spring is a popular framework with users all over the world. I hope that official documents can have international support, so that people from all over the world can read more conveniently.

**Comment by philwebb** [comment]
I would like this as well, unfortunately we don't have the resources to provide official translations so we must rely on community efforts.
