### ISSUE TITLE
org.springframework.core.io.Resource does not play nice with native-image

### ISSUE THREAD

**Issue by cmdjulian** [spring-projects/spring-boot#33835]
I have the following snippet working properly in a JVM setup:

```yaml
hello:
  message: classpath:hello/world.txt
```

```kotlin
@ConfigurationProperties("hello")
data class Config(val message: Resource)

@Configuration
@EnableConfigurationProperties(Config::class)
@ImportRuntimeHints(ResourceConfigRegistrar::class)
class GreeterService(private val config: Config) {

    private val logger = KotlinLogging.logger { }

    @PostConstruct
    fun greet() {
        logger.info { config.message.file.readText() }
    }
}

internal class ResourceConfigRegistrar : RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.resources().registerResource(ClassPathResource("hello/world.txt"))
    }
}
```

However, for native image it doesn't with the error message: `java.io.FileNotFoundException: class path resource [hello/world.txt] cannot be resolved to absolute file path because it does not reside in the file system: resource:/hello/world.txt`

When changing the code to the following, it works as intended:

```yaml
hello:
  message: /hello/world.txt
```

```kotlin
@ConfigurationProperties("hello")
data class Config(val message: String)

@Configuration
@EnableConfigurationProperties(Config::class)
@ImportRuntimeHints(ResourceConfigRegistrar::class)
class GreeterService(private val config: Config) {

    private val logger = KotlinLogging.logger { }

    @PostConstruct
    fun greet() {
        logger.info { javaClass.getResourceAsStream(config.message)!!.bufferedReader().readText() }
    }
}

internal class ResourceConfigRegistrar : RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.resources().registerResource(ClassPathResource("hello/world.txt"))
    }
}
```

As I like to use `Resource` as an abstraction in my code, I think this should work in the native image case as well.  
Eventually `ClassLoader.getSystemResource(this.absolutePath)` or `ClassLoader.getSystemClassLoader();` is called by the Spring Resource resolving mechanism. When I do remember correctly, this do not work in native image.  
I therefore tried using  `ClassPathResource("hello/world.txt")` directly, also tried `ClassPathResource("hello/world.txt", javaClass.classLoader)` but all with the same result in native image.

I pushed a sample to [cmdjulian/spring-playground on branch resource-loading-native-image](https://github.com/cmdjulian/spring-playground/tree/resource-loading-native-image). You can run it by executing `./gradlew nativeCompile && build/native/nativeCompile/notes`.

**Comment by cmdjulian** [comment]
Turns out, `ResourceConfigRegistrar` is actually not needed

**Comment by mhalbritter** [comment]
When using `.getFile()`, you assume that a `File` is available, which is not the case for resources in a native image. The correct way to to it is to use `.getInputStream`, which returns an `InputStream` abstraction, which works both for resources in the file system, in a JAR file or in a native-image.

This code works:

```kotlin
logger.info { config.message.inputStream.readAllBytes().decodeToString() }
```

**Comment by cmdjulian** [comment]
Thanks for the explanation.  
I still think there is a shortcoming though. Let's say I do ignore the file part, as it's not safe to use in native image and I only rely on the Resource interface methods.  
When I know call the `exists()` method, I will get an false positive error as well, telling me the Resource does not exists, as under the hood for a ClassPathResource Classloader.getResource() is used. Except for wrapping the `getInputStream` method inside of a try catch block, I can't safely determine if the underlying resource does in fact exist before accessing it's input stream.  
I still think Spring should make the Resource abstraction work in any case, regardless of it is in a native image or not, as this is the essential purpose of this abstraction.
