### ISSUE TITLE
Spring Boot uses an internal jetty class

### ISSUE THREAD

**Issue by Sineaggi** [spring-projects/spring-boot#33833]
Spring Boot is using an internal jetty class here in the [JettyWebSocketServletWebServerCustomizer.java:23](https://github.com/spring-projects/spring-boot/blob/fe7b13ec46f9960bebfddad984816e353f9c9349/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/websocket/servlet/JettyWebSocketServletWebServerCustomizer.java#L23)

This means if you were planning on running your dependencies (jackson, slf4j, logback and jetty) on the module path and keep spring-boot on the unnamed-module you'd need to add the flag
`--add-opens org.eclipse.jetty.websocket.jakarta.server/org.eclipse.jetty.websocket.jakarta.server.internal=ALL-UNNAMED`

**Comment by wilkinsona** [comment]
This is intentional. We try to minimise our use of internal API but will use it where there's no alternative. This may improve with Jetty 12 which we intend to support in Spring Boot 3.1 if the release dates line up.

**Comment by wilkinsona** [comment]
Re-opening as there's now some new public API that we should see if we can use as part of upgrading to Jetty 12.

**Comment by rafaelrc7** [comment]
Hello, I would like to try solving this issue. By reading what was discussed here and in eclipse/jetty.project#9182 it seems that there are two possible solutions: Either calling the same methods that were made public or following the Jetty's team's suggestion, which one would be preferable?

**Comment by wilkinsona** [comment]
Thanks for the offer, @rafaelrc7, but we can't upgrade to Jetty 12 just yet. I have some work in progress in [this branch](https://github.com/wilkinsona/spring-boot/tree/jetty-12) but it's currently blocked by https://github.com/eclipse/jetty.project/issues/9173.

**Comment by wilkinsona** [comment]
This was addressed in https://github.com/spring-projects/spring-boot/issues/36073.
