### ISSUE TITLE
MySql dependency error with Spring 2.7.8

### ISSUE THREAD

**Issue by reenadangi** [spring-projects/spring-boot#33915]
## Not able to add MySql dependency in Spring boot project created with 2.7.8, getting the following error in pom.xml
com.mysql:mysql-connector-j:jar:8.0.32 failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.mysql:mysql-connector-j:jar:8.0.32 from/to central (https://repo.maven.apache.org/maven2): The operation was cancelled.

org.eclipse.aether.transfer.ArtifactTransferException: com.mysql:mysql-connector-j:jar:8.0.32 failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.mysql:mysql-connector-j:jar:8.0.32 from/to central (https://repo.maven.apache.org/maven2): The operation was cancelled.

**Comment by wilkinsona** [comment]
The coordinates have changed in 8.0.32. Please see [Boot's release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#mysql-jdbc-driver) for details.

**Comment by l3d00m** [comment]
I would have appreciated at least a minor bump, doing some kind of minor breaking change in a patch release was very unexpected for me.

**Comment by philwebb** [comment]
@l3d00m Our options were very limited, we're not going to release a Spring Boot 2.8 version just for one dependency and we also didn't want to stay on an outdated release. It's an usual situation to have such a change between 8.0.31 and 8.0.32. We'd would have obviously preferred it if artifacts remained published for the duration of 8.0.x and were only removed in 8.1.x.

**Comment by l3d00m** [comment]
@philwebb I appreciate the explanation! I understand that it was a very questionable decision by upstream to introduce a big change like that in a patch version. 

From a purely user standpoint it would have been a lot nicer for me if you would have just ignored your usual release cycle and made it a major release. 

Instead I assumed that the resulting build issue must have surely happened only for me, and it took a while of debugging before I found the culprit. And I assume that multiple users had a very similar experience.

But I understand that from your perspective it is a very nasty thing to change your release cycle completely and that therefore you decided to go for the patch release instead.
