### ISSUE TITLE
PropertiesLauncher change on 1.2.2 make outside lib/ folder unrecognized

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3392]
I realised this after updating of my projects. I normally move `lib/` folder outside of the jar, but after this change, if I don't add `loader.path=lib`, it doesn't recognise the lib folder as stated the the `PropertiesLauncher` itself.

Related issue: https://github.com/spring-projects/spring-boot/issues/2314

**Comment by philwebb** [comment]
It looks like the change was intentional but the javadoc on `PropertiesLauncher` is out of date.

**Comment by gokhanoner** [comment]
Thanks for clarification. But it's a little bit funny behaviour for me, adding the same folder to the classpath while in the archive but not when outside. To me, it's same as adding application.properties file whether it's inside the jar or outside. But, again, it's a arch. decision, I guess.

**Comment by philwebb** [comment]
@dsyer @wilkinsona Thoughts?

**Comment by gokhanoner** [comment]
Or maybe a better alternative to modify https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/Layouts.java  and override ```getLibraryDestination``` method for ```Expanded```, ZIP and DIR types, like ```Jar``` type. This way, path will be added by the ```Repackager``` during repackage phase ?

**Comment by wilkinsona** [comment]
The current behaviour is intentional, and it matches what Dave and I settled on in #2314. @gokhanoner I can see your point about `application.properties` being handled, but that's solely about configuration rather than affecting your application's entire classpath. I don't feel particularly strongly, but I'm inclined to think that the current default is sensible and shouldn't be changed.

**Comment by gokhanoner** [comment]
Well, ok than. Not a big deal, but to be honest, I can understand Jar|War launcher add archived lib/ folder to their classpath. But becuase I cannot use these launcher, them Properties launcher should offer me something different. But on the other hand, yes, it effects application's entire classpath. And adding a ```loader.path```is not a big deal.

What about ```spring-boot-maven-plugin``` layout property? Currently ZIP and DIR makes the same thing, as far as I can see from the source code. But when I see an option like DIR, I expect a directory layout, not like ZIP, contains: one small jar, lib folder and other folders,if any, outside etc. I believe that can be nice feature rather than using maven alternatives to achieve this ?

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
