### ISSUE TITLE
Auto-configure the JMS listener container sessionTransacted flag

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3393]
See #3390 for the initial discussion.

If no JTA transaction manager is present, we really should flip the `sessionTransacted` flag to true otherwise message consumptions does not even use a local (JMS) transaction.

**Comment by marinoj** [comment]
Hi, I agree this makes sense as a default - but I have a situation where I don't require a transaction and I had to define and override the jmsListenerContainerFactory just to change the sessionTransacted flag to false ... I read the discussion in #3390 where you concluded that having the sessionTransacted flag available would be confusing - and while I agree that's true if you have a JTA transaction manager present I don't see how that justifies making it so difficult to use a simple auto-acknowledged non-transactional session.

**Comment by snicoll** [comment]
So you have a JTA `PlatformTransactionManager` and you want a listener without a JTA transaction? If I understood  correctly, please create a separate issue as this one is closed. Thank you.

**Comment by marinoj** [comment]
No I don't have a JTA PlatformTransactionManager and I don't want the sessionTransacted set to true ... I want ack mode set to AUTO and sessionTransacted set to false :)

**Comment by snicoll** [comment]
What's wrong with a local transaction managed at the message listener container level? What is the actual problem?

**Comment by marinoj** [comment]
I want the queue on the broker to reflect that the message has been dequeued and I don't want any redeliveries in case of error.

**Comment by snicoll** [comment]
Mmm ok, thanks for the reply. One more question

> I had to define and override the jmsListenerContainerFactory just to change the sessionTransacted flag to false

What's wrong with that? Looks like advanced enough to deserve your own configuration (and using the configurer it's three lines of code really)

**Comment by marinoj** [comment]
Nothing wrong with creating a custom configuration per se - but I guess I'm not sure setting the sessionTransacted flag to false is advanced enough to require a custom config ... I feel non-transactional auto acknowledged sessions are pretty common so you might expect there to be a property for it - isn't Spring Boot is all about sensible defaults but easy customization through properties?

**Comment by snicoll** [comment]
I don't. You can't have a property for every combinations anyway and there are additional context in a PR we rejected recently, see #7394

**Comment by marinoj** [comment]
Fair enough ... keep up the good work :)
