### ISSUE TITLE
Dependency management for Mongo's Java Driver is incomplete

### ISSUE THREAD

**Issue by laxika** [spring-projects/spring-boot#33939]
Can you please add MongoDB's `bson-record-codec` to the Spring-managed dependencies?

https://mvnrepository.com/artifact/org.mongodb/bson-record-codec

The version is the same as for all of the other MongoDB dependencies.

**Comment by laxika** [comment]
Never mind, sorry. The MongoDB team added it as a dependency to `mongodb-driver-core` for the past few versions.

**Comment by philwebb** [comment]
Closing in favor of PR #33941
