### ISSUE TITLE
Spring Boot : WebLogic 10.3.5

### ISSUE THREAD

**Issue by VedNirmal** [spring-projects/spring-boot#3397]
Hello,

Can we deploy Spring boot application on lower version of WebLogic 10.3.5.

I googled and found that weblogic 10.3.5 can support Spring 3 but I'm using spring boot which uses the Spring 4.X jars.

Any help!

Thanks,
Nirmal

**Comment by arnosthavelka** [comment]
Well I guess so. We used our desired spring version successfully (on WLS 10.3.x). We just added to WLS deployment descriptor (`weblogic.xml`) this content (to prefer our libraries instead libraries from the server):
```xml
<container-descriptor>
     <prefer-web-inf-classes>true</prefer-web-inf-classes> 
</container-descriptor>
```

Additionaly you should probably exclude embedded Tomcat (to use SpringBoot on AS) as:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by faisalkhan1987** [comment]
Hi Arnnosthavelka,

I am trying to deploy my spring boot application in weblogic 10.3.6.0.

I have already added the container-descriptor and the tomcat exclusion in pom.xml.

But still it is not working. PFB my pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.tools</groupId>
    <artifactId>envdb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>
    
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.5.RELEASE</version>
    </parent>
    
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
            
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-legacy</artifactId>
            <version>1.0.1.RELEASE</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            
        </plugins>
    </build>    
    <repositories>
        <repository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
</project>

**Comment by snicoll** [comment]
Guys, please move your question to stackoverflow. This issue tracker is meant for enhancements and bug reports. Thank you.
