### ISSUE TITLE
Improve documentation regarding tracing in tests

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33975]
Tracing in tests is disabled, as documented [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.tracing).

We got a lot of questions why tracing isn't working in tests, so we should document this more prominently.

We should consider:

* documenting it in the [tracing section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.micrometer-tracing)
* add a logger call in the component which disables tracing in tests with a message pointing to the documentation or how to enable it

**Comment by dsyer** [comment]
Please also consider pulling the whole "Testing" section up to the top level so it shows up in the left nav.
