### ISSUE TITLE
Log the root cause first when logging exceptions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3399]
This issue is on a similar theme to #3398. Logback also provides an [option to log the root cause first](http://logback.qos.ch/manual/layouts.html#rootException). This, potentially, saves you scrolling down through umpteen nested exception before you get to one that matters.

I'm not entirely convinced that this should be the default, but I'm interested to know what others think.

**Comment by dsyer** [comment]
I'm open to this being the default. I would soon get used to not having to scroll, and n00bs always find it difficult to know that's what you need t

**Comment by snicoll** [comment]
:+1:

**Comment by shakuzen** [comment]
:+1:
