### ISSUE TITLE
Detect accidental misconfiguration of @JsonMixin

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#33992]
`@JsonMixin` exposes both a `value` and a `type` attribute, the latter being an alias of the former, which means that both attributes define an empty default value.

`JsonMixinModuleEntries`' `registerMixinClass(…)` inspects the attributes and only registers a mixin if the attribute is set. This means that a sole `@JsonMixin` annotation on a class will be found but dropped in that purpose. While this is a pretty obvious mistake, as one does not define which class to apply the mixin for, it can easily be overseen and we could actually detect that misconfiguration. It would be nice if `….registerMixinClass(…)` could reject an empty `@JsonMixin` annotation to avoid this oversight.

**Comment by MatejNedic** [comment]
Hey, is this issue open for taking? :)

**Comment by philwebb** [comment]
Closing in favor of PR #42592. Thanks @nosan!
