### ISSUE TITLE
Spring Boot 3 Actuator indentation not working

### ISSUE THREAD

**Issue by TrinhChuong** [spring-projects/spring-boot#34000]
Created a new Spring Initializer java 17 gradle project in IntelliJ using Spring Boot version 3.0.2.
Included Spring Web and Spring Boot Actuator.

Did the same using Spring Boot version 2.7.8.

Both projects have the following in application.properties

management.endpoints.web.exposure.include=info
management.info.build.enabled=true
spring.jackson.serialization.indent-output=true

When requesting /actuator/info for version 3.0.2 project, the JSON is not indented or pretty printed. The same request for version 2.7.8 project returns pretty printed and indented JSON.

Everything is left default, no code additions, config changes. etc. Just plain vanilla out of the box project.

Is this a bug in Spring Boot version 3?

Expected the JSON response to be pretty printed and indented as per the Spring documentation for the Application Properties settings.

This is also posted in Stackoverflow (https://stackoverflow.com/questions/75221023/spring-boot-3-actuator-indentation-not-working). Seems there are other experiencing the same behaviour.

**Comment by bclozel** [comment]
This has been done on purpose in #20291 and is [also documented in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-json).

I'm closing this issue as a result. Let us know if the migration guide is missing information on how to work things out on your side. Thanks!
