### ISSUE TITLE
Wildcard support for configuration files

### ISSUE THREAD

**Issue by huifer** [spring-projects/spring-boot#34027]
The configuration file in a springboot project has the following configuration files
- application-tes.yaml
- application-tesa.yaml
- application-tess.yaml
- bootstrap-tess.yaml
Is it possible to make the spring.profiles.active parameter support wildcards and read all the above configuration files by configuring te*

**Comment by wilkinsona** [comment]
There's no concept of wildcards in Spring Framework's profile support. In other words, setting `spring.profiles.active` to `te*` would not result in the profiles `tes`, `tesa`, and `tess` being active. I think it would be confusing for a profile-specific configuration file, such as `application-tes.yaml`, to be loaded when its profile isn't actually active. Thanks anyway for the suggestion.
