### ISSUE TITLE
spring-boot-dependencies manages mysql:mysql-connector-java which no longer exists

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#34021]
It was removed in 2.7.x in https://github.com/spring-projects/spring-boot/commit/f24afd96854bcf7daafcc87607d60e8b204919a3 but I missed making the equivalent change in later branches.

**Comment by vpavic** [comment]
Note that this is technically a breaking change that causes projects that depend on `mysql:mysql-connector-java` to fail to build on upgrade to Sprint Boot `3.0.3`, requiring update of MySQL JDBC driver coordinates to `com.mysql:mysql-connector-j`.

**Comment by wilkinsona** [comment]
The breaking change is (actually was, see below) out of our control and the MySQL team stopped publishing to `mysql:mysql-connector-java` in 8.0.32. This commit removed dependency management for a module that did not exist.

It appears that they have now retrospectively published `mysql:mysql-connector-java:8.0.32`. The timestamps on Central suggest it was published on 2022-12-07 but the timestamps on `com.mysql:mysql-connector-j:8.0.32` suggest 8.0.32 wasn't actually released until 2023-01-18 and the announcement says 2023-01-17. In short, this is a bit of a mess and it's hard to be sure what's going on.

It looks like we could reinstate the dependency management for `mysql:mysql-connector-java` but I'm not sure it's worth it as it's hard to tell for how long it will be of any use. We already mention the change in coordinates in the 2.7 release notes. I'll add something to the 3.0 release notes as well.

**Comment by vpavic** [comment]
FWIW I observed this on a project where dependencies are upgraded by automation. The project was built without any issue on upgrade to Spring Boot `3.0.2` on Jan 20th but failed on upgrade to `3.0.3` on Feb 24th. This is consistent with the timeline in your comment as MySQL team appears to have published to Maven Central just in time for upgrade to `3.0.2` to be unaffected.
