### ISSUE TITLE
spring-cloud-starter-netflix-zuul incompatibility with spring-boot 3.0.2

### ISSUE THREAD

**Issue by tejasmjethva** [spring-projects/spring-boot#34032]
Hi, 

We're trying to upgrade the `spring-boot `version from `2.7.3` to `3.0.2`. As part of the project, we're also using `spring-cloud-starter-netflix-zuul` version `2.2.10-RELEASE`. While upgrading the dependencies, we observed that though we are using latest version of  `spring-cloud-starter-netflix-zuul`, the classes in the library are still using `javax.*` classes (which are not supported in spring-boot 3.0.2).

Is there a way I can use `jakarta` compatible `spring-cloud-starter-netflix-zuul` library?

**Comment by scottfrederick** [comment]
Spring Cloud Netflix Zuul was [removed from the Spring Cloud project](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes-1), and is no longer maintained. A Spring Boot 3 compatible version will not be available. 

Spring Cloud Netflix is managed as a [separate project](https://github.com/spring-cloud/spring-cloud-netflix) from Spring Boot. Any further questions about any `spring-cloud-starter-netflix-*` projects should be directed there.
