### ISSUE TITLE
Add auto-creation of retry topics to Spring Kafka non-blocking retries auto-configuration

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-boot#34046]
When auto-configuration for `Spring for Apache Kafka`'s `Non-Blocking Delayed Retries` feature was implemented, automatic creation of topics was disabled by default.

We should allow users to override that configuration for speeding up development.

My proposal is to add the following properties:

```properties
spring.kafka.retry.topic.create.retry-topics=true
spring.kafka.retry.topic.create.partitions=2
spring.kafka.retry.topic.create.replication-factor=3
```

Or, if we want less options:

```properties
spring.kafka.retry.topic.auto-create-retry-topics=true
```

How does that look? I can open a PR once we reach an agreement, and we can change any properties names.

Here are the [docs](https://docs.spring.io/spring-kafka/reference/html/#retry-topic) for the feature, and [here](https://docs.spring.io/spring-kafka/reference/html/#topics-autocreation) for topics auto-creation. Please let me know if you have any questions.

@garyrussell and @artembilan, feel free to pitch in if you have the time.

Thanks!

**Comment by tomazfernandes** [comment]
I gave some more thought on this, and perhaps we should keep it as simple as possible and have a single property:

```properties
spring.kafka.retry.topic.auto-create-topics=true
```

If users want more complex configurations than that they can provide their own configuration programmatically, and if users request further auto-configuration options we can always add them later.

I've opened a PR for this but if we decide to go another direction that's ok.

Thanks!

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
