### ISSUE TITLE
Links to old versions of Spring Boot 2.* documentation don't work

### ISSUE THREAD

**Issue by mpesa1975** [spring-projects/spring-boot#34043]
Links to the old version of Spring Boot 2.* don't work on page https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Older-Release-Notes
For example https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes
displays:
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.
[Contact Support](https://support.github.com/contact) — [GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by wilkinsona** [comment]
Thanks for the report but this is a problem on GitHub's side and is out of our control. As the message says, if the problem persists feel free to [contact GitHub support](https://support.github.com/contact).
