### ISSUE TITLE
Manifests of jars built with Gradle do not have a Implementation entries

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#34059]
The Spring Boot Maven plugin configures the `maven-jar-plugin` to add the default `Implementation-*` entries to the built archive. Archives built with the Spring Boot Gradle plugin do not have these manifest attributes by default. The Gradle plugin should add the following manifest entries for consistency: 

* `Implementation-Title`
* `Implementation-Version`
* `Implementation-Vendor`

This is similar to #32829, which we categorized as a bug and fixed in 3.0.x. We should fix this in the same version.

**Comment by wilkinsona** [comment]
Maven uses the following defaults:

```
Implementation-Title: ${project.name}
Implementation-Version: ${project.version}
Implementation-Vendor: ${project.organization.name}
```

`project.name` and `project.version` are straightforward with Gradle. `project.organization.name` is not. Maven will only add `Implementation-Vendor` if `<organization>/<name>` appears in the pom` which, in my experience, isn't very common. I think we should just focus on the title and version.
