### ISSUE TITLE
How to correctly set @Bean(destoryMethod) with native image compile?

### ISSUE THREAD

**Issue by qjekingstar** [spring-projects/spring-boot#34057]
I tried to run Redisson 3.19.2 with Spring Boot 3.0.2
but facing issues, when running the spring native compile.
```
org.springframework.context.ApplicationContextException: Unable to start web server
......
Caused by: org.springframework.beans.factory.support.BeanDefinitionValidationException: Could not find a destroy method named 'shutdown' on bean with name 'redisson'
```
org.redisson.spring.starter.RedissonAutoConfiguration
```Java
@Bean(destroyMethod = "shutdown")
@ConditionalOnMissingBean(RedissonClient.class)
public RedissonClient redisson() throws IOException {
    ......
}
```
I didn't find any part of spring documentation about destroyMethod or DisposableBean to build native image. Should I register a RuntimeHints to fix this?

**Comment by scottfrederick** [comment]
@qjekingstar You've also [opened an issue with the Redison project](https://github.com/redisson/redisson/issues/4836). Since the auto-configuration code you've mentioned is a part of that project and not maintained by the Spring team, you should let the Redison team answer your question.
