### ISSUE TITLE
spring boot migration guides are not available on github

### ISSUE THREAD

**Issue by yanaair** [spring-projects/spring-boot#34052]
some of older spring boot migration guides are returning 500 server error today, and there is no alternative source of them:

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#upgrading-from-spring-boot-23
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#upgrading-from-spring-boot-24
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#upgrading-from-spring-boot-25

**Comment by wilkinsona** [comment]
Thanks for the report but this is a problem on GitHub's side and is out of our control. As the message says, if the problem persists feel free to [contact GitHub support](https://support.github.com/contact).

**Comment by philwebb** [comment]
Not pretty, but you can still access the raw content using `https://raw.githubusercontent.com/wiki/spring-projects/spring-boot/releasenotes/<title>.asciidoc`. E.g. https://raw.githubusercontent.com/wiki/spring-projects/spring-boot/releasenotes/Spring-Boot-2.4-Release-Notes.asciidoc

I've raised a support request.

**Comment by yanaair** [comment]
Issue seems to be gone now. Thanks

**Comment by wilkinsona** [comment]
Thanks, @yanaair. We haven't made any changes on our side but it's good to hear that it's working again for you.

The response from GitHub support is interesting. Commit `ef9ac5920aac4f8dbb2d91fbdac5ae32ba5f64f7` was made on 14/12/2021. Rolling back that far would not have been an option. `99e10e3e4fccf311330ef0df14ae4d05f42ae1da` also appears to have an author date (and commit date):

```
commit 99e10e3e4fccf311330ef0df14ae4d05f42ae1da
Author:     Scott Frederick <scottyfred@gmail.com>
AuthorDate: Fri Oct 28 11:51:52 2022 -0500
Commit:     Scott Frederick <scottyfred@gmail.com>
CommitDate: Fri Oct 28 11:51:52 2022 -0500

    Fix links
```

Oh well. At least the problem's gone now. Thanks again.
