### ISSUE TITLE
Standalone Tomcat fails to find a Boot app's manifest when defining a package, resulting in a null implementation version

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3406]
[Follow on from 3061](https://github.com/spring-projects/spring-boot/issues/3061#issuecomment-118048010)

**Comment by wilkinsona** [comment]
During deployment, Tomcat explodes a war file into a directory structure. This directory structure is represented by a `DirResourceSet` which returns a `FileResource` when it's asked for a class. `FileResource` is hard-coded to return `null` from `getManifest()` so it'll never find the implementation version attribute. In short, there's nothing we can do about this in Boot.

@markt-asf would you consider a change in Tomcat so that a `FileResource` can use its `DirResourceSet` to find its manifest?

**Comment by markt-asf** [comment]
Are you expecting the Manifest from the WAR file to be returned? A quick look at the code indicates that that is what would happen if the WAR was not unpacked. It does seem inconsistent not to return it if the WAR is unpacked.

**Comment by wilkinsona** [comment]
@markt-asf Correct, I'd like to get the war's manifest via any class that's found in `WEB-INF/classes`

**Comment by markt-asf** [comment]
Any reason not to return the WAR manifest for a call to getManifest() for any resource extracted from the WAR? This is also how an unpacked WAR would behave. To put it another way, any reason to limit this to files (or even just classes) form WEB-INF/classes ?

**Comment by markt-asf** [comment]
Fixed in trunk and 8.0.x. Will be in 8.0.25 onwards (not due for at least a month). Are you happy building from source for testing the fix or would you like me to put a 8.0.x snaphot in the ASF snapshot repo?

**Comment by wilkinsona** [comment]
Perhaps a bit late, but whatever will align the exploded war behaviour with the packed war behaviour makes sense to me.

Assuming I haven't forgotten how to do it, building from source should be fine. I'll take you up on the snapshot offer if my memory fails me. Thanks.

**Comment by wilkinsona** [comment]
I've built 8.0.25 (revision 1689831) from source and the manifest's resolved successfully from an exploded war. Thanks, @markt-asf
