### ISSUE TITLE
M1 execute gradle nativeCompile stuck

### ISSUE THREAD

**Issue by huiji121** [spring-projects/spring-boot#34069]
spring-boot:3.0.2
org.graalvm.buildtools.native:0.9.18
jdk:17
gradle:7.6
system: mac m1

i want building Native Images with GraalVM and Spring Native on Apple's M1 Architecture, execute gradle nativeCompile failed
<img width="1660" alt="WeChata5c7f1fb5b4cf44d1c20a328bdb3f20d" src="https://user-images.githubusercontent.com/24616352/216929566-d93a066f-566a-42de-8906-ef83f3ee0d97.png">

**Comment by huiji121** [comment]
![WeChat84a7ce9ccd9a31ef9dd4d0d754e18490](https://user-images.githubusercontent.com/24616352/216929909-d4c30ff0-11bf-4ccf-9b40-5441b5fbcb27.png)

**Comment by wilkinsona** [comment]
Arm isn't officially supported. Please see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#building-container-images.

**Comment by huiji121** [comment]
May I ask when you plan to support arm

**Comment by wilkinsona** [comment]
That's a question for the buildpacks team. There's a link to the [relevant issue](https://github.com/buildpacks/lifecycle/issues/435) on the wiki page to which I linked above.
