### ISSUE TITLE
problem with @Scheduled 

### ISSUE THREAD

**Issue by RobertHan215** [spring-projects/spring-boot#34066]
I used docker to run my spring boot application, and there is a weird problem with @Scheduled annotion. First, i used @Scheduled to run my code every 1.06 AM, and it works fine. Then i removed the annotion, but the application still run but on 9.06 AM.

i delete the docker container and image, and rebuild all, but the application still can not stop.

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by RobertHan215** [comment]
> If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

ok, i will reproduce the problem within this week, and then provide you the minimal sample.

**Comment by RobertHan215** [comment]
i think it's a mistake, so close the issue.
