### ISSUE TITLE
Add mail test connection

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#3408]
Since `testConnection` has been added into `JavaMailSenderImpl`. Property can be added to verify the connectivity in the startup.

**Comment by snicoll** [comment]
I don't like that you're running the test in the bean declaration. It also means that you effectively don't test the connection if the `JavaMailSender` has been created manually. I had a look last week and couldn't find a good arrangement so I'll have a look again later today.

**Comment by snicoll** [comment]
I don't like that you're running the test in the bean declaration. It also means that you effectively don't test the connection if the `JavaMailSender` has been created manually. I had a look last week and couldn't find a good arrangement so I'll have a look again later today.
