### ISSUE TITLE
1.2.5 allow-session-override was removed?

### ISSUE THREAD

**Issue by aluisiodsv** [spring-projects/spring-boot#3410]
Hi,

Older versions of Spring Boot we can configure this in `application.properties`, but it was removed.
In my case I use velocity as template engine, so the key was:
```
spring.velocity.allowSessionOverride=true
```

but others engines have it too.
`AbstractTemplateViewResolver` still have this property, but no longer can be set.
Is there another way to set this?

Sorry if here is the wrong place to ask.
Thanks.

**Comment by snicoll** [comment]
I believe you mean `spring.velocity.allowRequestOverride` right?

**Comment by philwebb** [comment]
Also what version did you see the property get removed?

**Comment by aluisiodsv** [comment]
The version I'm using now is the 1.2.5, and I really mean the "session" property (spring.velocity.allow-session-override).

**Comment by snicoll** [comment]
The question is in which version it was working for you?

**Comment by philwebb** [comment]
I'm confused. I can't find a reference to `allow-session-override` in older versions of the code or the reference manual.

**Comment by snicoll** [comment]
ping @aluisiodsv

**Comment by philwebb** [comment]
Closing as invalid for now due to lack of feedback

**Comment by aluisiodsv** [comment]
http://docs.spring.io/autorepo/docs/spring-boot/1.1.3.BUILD-SNAPSHOT/reference/html/common-application-properties.html

**Comment by philwebb** [comment]
Weird, looks like 16c2477da266f08beec6af034957a99981ea96b1 changed the docs but I still can find any code where we actually set the property. This was the original commit https://github.com/spring-projects/spring-boot/blob/e40acd81e4d67b65a04ad9dc3b6c10bdd8b98395/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/template/TemplateViewResolverConfigurer.java.

I imagine we could add this without too much hassle. @wilkinsona do you think this is a good candidate for 1.2.x?

**Comment by wilkinsona** [comment]
As far as I can tell we've never supported configuring `allowSessionOverride` with Velocity. It looks like we supported it briefly (in 1.1.0.M1 but not 1.1.0.M2) for FreeMarker, but it disappeared (accidentally, I think) in [this commit](https://github.com/spring-projects/spring-boot/commit/d2112e27a339ccc539f4dba01971884a002a1d76).

It seems like a low risk change, so a reasonable candidate for 1.2.x. I believe the other template engines are all in the same position.
