### ISSUE TITLE
Properties not bound properly for Spring Boot 3.x and Kotlin

### ISSUE THREAD

**Issue by travispeloton** [spring-projects/spring-boot#34117]
Properties not bound properly for Spring Boot 3.x when using Kotlin. I thought it might be related to issue #33969.

Here is a GitHub project that reproduces the problem: https://github.com/travispeloton/spring-prop-binding-bug

With Spring Boot 3.x. You will see the following in the logs, which is **NOT** expected:

```shell
12:25:43.971 [main] INFO  com.example.MyComponent - management.metrics.export.statsd.host=localhost
```

What we expect is:

```shell
12:22:24.878 [main] INFO  com.example.MyComponent - management.metrics.export.statsd.host=127.0.0.1
```

Since we configured it in `application.yml`:

```shell
management:
  metrics:
    export:
      statsd:
        flavor: "datadog"
        # default is "localhost"
        host: "127.0.0.1"
        enabled: true
```

See the `spring-2.x` branch to see it working correctly with Spring Boot 2.x.

**Comment by travispeloton** [comment]
When its working correctly, a breakpoint at the following location will be hit during startup:

`org.springframework.boot.actuate.autoconfigure.metrics.export.statsd.StatsdProperties#setHost`

**Comment by scottfrederick** [comment]
In Spring Boot 3.0, the metrics export properties were changed, as [mentioned in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-metrics-export-properties). Changing `management.metrics.export.statsd` to `management.statsd.metrics.export` should fix your problem.

**Comment by travispeloton** [comment]
Ok thanks. Would be nice for warnings to be printed for an obscure config change like this.

**Comment by scottfrederick** [comment]
For changes in configuration properties like this, you can get warnings at startup by enabling the properties migrator, as [described in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#upgrading.to-feature).
