### ISSUE TITLE
Investigate automatic CDS support

### ISSUE THREAD

**Issue by Sineaggi** [spring-projects/spring-boot#34115]
AppCDS is a feature in java that allows java applications to startup faster thanks to creating application-specific Class-Data Sharing archives.
This issue exists to help investigate and track the progress of adding appcds to the spring boot build plugins.

Problem: How do create a class-list that represents the classes required by a spring-boot app that will positively impact startup and first-request performance, but not include classes that won't be loaded.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I don't think we need to couple AppCDS to AOT. You can use class data sharing without any AOT processing as has already been done with manual configuration and Spring Boot 2.x.

**Comment by snicoll** [comment]
For the record, we're going to investigate how to support "training runs" in the core container https://github.com/spring-projects/spring-framework/issues/31497

**Comment by bclozel** [comment]
Closing in favour of #38276, as AppCDS support requires deep integration with the classpath and Spring Boot packaging.
