### ISSUE TITLE
Mention fully executable jars when warning about Jersey's scanning limitations

### ISSUE THREAD

**Issue by lgawron** [spring-projects/spring-boot#3413]
I have a spring boot application (1.3.0.M1) with Jersey endpoints. As soon as I make the jar executable - the endpoints are not detected. 

Using following configuration in pom.xml:

``` xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>true</executable>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

gives me:

```
{"timestamp":1435928140519,"status":404,"error":"Not Found",
 "message":"Not Found","path":"/ws/auth/token"}
```

Same starts working as soon as I comment out `<executable>` tag

**Comment by philwebb** [comment]
Are you able to share an example project that replicates the issue?

**Comment by lgawron** [comment]
Sorry for such delay - I somehow missed your reply...

The problem actually goes down to: 

```java
@Configuration @ApplicationPath("ws")
public class JerseyConfig extends ResourceConfig {
	public JerseyConfig() {
		packages( "demo.rest" );
	}
}
```

This does not work for executable jar, works for standard one though. if you do `register( HelloEndpoint.java )` instead it works in both cases. Somehow Jersey's package scanning is impaired when using executable jar.

I am attaching a simple project. Please build and  navigate to `http://localhost:8080/ws/hello`

**Comment by lgawron** [comment]
Oops, I had no idea github does not allow attachments.
Here it is: [dropbox link](https://dl.dropboxusercontent.com/u/860602/jersey-spring-boot-package-scanning-problem.zip)

**Comment by nodje** [comment]
not exactly the same issue, but related:
https://stackoverflow.com/questions/32431989/jersey-bug-when-starting-spring-boot-app-unix-style

**Comment by wilkinsona** [comment]
Jersey uses a `JarInputStream` to scan the jar. It doesn't fail, but the input stream thinks it has no entries. This will produce no output:

```java
JarInputStream input = new JarInputStream(new FileInputStream("demo.jar"));
JarEntry entry;
while ((entry = input.getNextJarEntry()) != null) {
	System.out.println(entry);
}
```

Setting `<executable>false</executable>`, rebuilding, and re-running produces the expected list of entries from the jar.

**Comment by wilkinsona** [comment]
The problem appears to be specific to `JarInputStream`. `JarFile` successfully lists all the entries:

```java
JarFile jarFile = new JarFile(new File("demo.jar"));
Enumeration<JarEntry> entries = jarFile.entries();
while (entries.hasMoreElements()) {
	System.out.println(entries.nextElement());
}
jarFile.close();
```

**Comment by wilkinsona** [comment]
`ZipInputStream` expects the first 32-bits of the file to be equal to `ZipConstants.LOCSIG`, `ZipFile` has no such limitation.

**Comment by wilkinsona** [comment]
The javadoc for Jersey's `PackageNamesScanner` suggests that we could plug in our own handler for `jar` URLs:

>  Further schemes may be registered by registering an implementation of
 `UriSchemeResourceFinderFactory` in the `META-INF/services` file whose name is the
 the fully qualified class name of `UriSchemeResourceFinderFactory`

However, the code tells a different story:

```
// TODO - Services?
// for (UriSchemeResourceFinderFactory s : ServiceFinder.find(UriSchemeResourceFinderFactory.class)) {
//     add(s);
// }
```

**Comment by nick-pww** [comment]
This is also a problem with Camels [DefaultPackageScanClassResolver](https://github.com/apache/camel/blob/camel-2.15.1/camel-core/src/main/java/org/apache/camel/impl/DefaultPackageScanClassResolver.java). It also uses the JarInputStream and fails to find any entries when the jar is marked as executable. This seems to be a bigger issue then adding a custom Jeresy package scanner as any libraries that rely on JarInputStream will fail on any executable jar and you have a big game of whack-a-mole.

**Comment by Dichotomia** [comment]
I encounter the same problem. I cannot use the executable feature.

**Comment by jacowessels** [comment]
Hi there. Thanks for feedback so far. Is there a solution to this - or is this a Jersey problem that they have to fix?

**Comment by wilkinsona** [comment]
As noted above, the solution, for now at least, is to not use a fully-executable jar if you also want to use Jersey. A better solution, that would allow a jar to be fully-executable will require changes in Jersey. For example, the pluggability promised in `PackageNamesScanner` is [still commented out](https://github.com/jersey/jersey/blob/2.23.1/core-server/src/main/java/org/glassfish/jersey/server/internal/scanning/PackageNamesScanner.java#L138-L141).

**Comment by juanmbellini** [comment]
I was able to use the executable feature with Jersey. The thing is that it seems that Jersey is not fully integrated with Spring when scanning packages in the spring boot jar (at least with Spring Boot 1.5.8.RELEASE, which includes Jersey 2.25.1; I haven't tested it with Spring Boot 2.0.x). 


What I did was the following:

```java
public class JerseyConfig extends ResourceConfig {

    /**
     * Constructor.
     */
    public JerseyConfig() {
        registerPackages("com.example", "com.another.example");
    }

    /**
     * Registers the classes annotated with the {@link Provider} annotation in the given {@code packages}.
     * This allows package scanning with Jersey (as currently not supported by library).
     *
     * @param packages The packages containing providers.
     */
    private void registerPackages(String... packages) {
        // Register packages of in app Providers
        final ClassPathScanningCandidateComponentProvider scanner =
                new ClassPathScanningCandidateComponentProvider(false);
        scanner.addIncludeFilter(new AnnotationTypeFilter(Provider.class));

        Arrays.stream(packages)
                .map(scanner::findCandidateComponents).flatMap(Collection::stream)
                .map(beanDefinition ->
                        ClassUtils.resolveClassName(beanDefinition.getBeanClassName(), this.getClassLoader()))
                .forEach(this::register);
    }
}
```
The jersey configuration class contains a method that uses the ```register(Class)``` method.
This classes are selected through package scanning, getting only those annotated with the ```@Provider``` annotation.
