### ISSUE TITLE
@SendTo annotation improvements

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3415]
Useful annotation combined with ```@JmsListener```. But currently only get a destination queue name. 
Some additional features that I can think of:
* An options for routing messages to different queues depends on a header value and/or a bean reference that returns the queue name, getting message header or itself as parameter.
* A message splitter options: when JmsListener return a list to decide whether send it as a single message or send each element as a separate message
* A filter option, to filter out some messages depends of header and/or message value. Possibly a bean reference or maybe SpeL on some header values or message itself ?

**Comment by snicoll** [comment]
This is a spring framework feature. Would you mind creating that issue in the Spring framework issue tracker at jira.sprig.io?

It looks like you're asking for spring integration features though.

**Comment by gokhanoner** [comment]
Thank for pointing the correct direction.

Well, if I can select listenerFactory, concurrency etc on ```@JmsListener```annotation, then I guess ```@SendTo```can be a little mit more smart :)
