### ISSUE TITLE
Spring Boot 2.6.14 + Spring Cloud Context 3.1.5  fullgc

### ISSUE THREAD

**Issue by Johnson-Jia** [spring-projects/spring-boot#34165]
Spring Boot 2.6.14 
Nacos 2.1.1
Spring Cloud Context 3.1.5

Use Environment#getProperty to get the configuration center object. Generates a large number of LinkedHashSet objects. Cause the jvm to be full gc.

The code in BootstrapPropertySource is as follows: 
```
@Override
	public String[] getPropertyNames() {
		Set<String> names = new LinkedHashSet<>();
		names.addAll(Arrays.asList(this.delegate.getPropertyNames()));

		return StringUtils.toStringArray(names);
	}
```

**Comment by Johnson-Jia** [comment]
The Environment#getProperty method is used inside the for loop.

**Comment by Johnson-Jia** [comment]
@scottfrederick 
thank you！
I suggest you take a look again. The code call link is as follows.
![1676259874383](https://user-images.githubusercontent.com/13517143/218365891-8fd9b7b9-6025-4630-9778-5ba488c66f20.png)

**Comment by Johnson-Jia** [comment]
![微信图片_20230213114739_看图王](https://user-images.githubusercontent.com/13517143/218366089-7388742a-03a7-41f6-9cd8-1eb7b58cbfbe.png)

**Comment by Johnson-Jia** [comment]
@scottfrederick 
I understand what you mean, but I think there is a problem when SpringBoot uses this method.

**Comment by scottfrederick** [comment]
> I think there is a problem when SpringBoot uses this method.

You mentioned `LinkedHashSet`, and `BootstrapPropertySource` in Spring Cloud Commons is the class that is creating `LinkedHashSet` objects, so I'm not sure how you are coming to the conclusion that Spring Boot is the problem.

Neither the Spring Boot or the Spring Cloud team will be able to provide much assistance without more information about what your application is doing. I would still suggest starting with Spring Cloud Commons, providing a complete minimal sample application that reproduces the problem you are having.

**Comment by Johnson-Jia** [comment]
OK, thanks

**Comment by Johnson-Jia** [comment]
I think it should be the Spring Cloud problem, or my usage is wrong.

Use scenarios are as follows:
Ten thousand records were queried from the database, and the relevant business logic was executed circularly. The 'getProperty' method was called in the loop, thus a large number of 'propertyNames' configuration objects that could not be recycled were found in the memory snapshot.

**Comment by Johnson-Jia** [comment]
This should be the reason (https://github.com/spring-projects/spring-boot/issues/34172#issuecomment-1428945752)
