### ISSUE TITLE
Spring Boot 3 does not provide a configuration property for configuring red metrics custom tag keys

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#34194]
In `WavefrontTracingAutoConfiguration`, it defines a `WavefrontSpanHandler` bean.
This passes an empty collection to the `redMetricsCustomTagKeys` in the constructor.

https://github.com/spring-projects/spring-boot/blob/0e67fbc855b714253e0b1fa7115d93f76c5618e3/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/wavefront/WavefrontTracingAutoConfiguration.java#L62-L69

Per [this documentation](https://docs.wavefront.com/tracing_customize_spans_and_alerts.html) in Wavefront, the `redMetricsCustomTagKeys` should be populated by the `wavefront.tracing.red-metrics-custom-tag-keys` property.
I believe this bean definition is the corresponding part for the property.

So, what the doc mentioned to work, I think populated values need to be passed to `redMetricsCustomTagKeys` rather than an empty set.

**Comment by wilkinsona** [comment]
We can't proceed with this until we've got some input from the Wavefront team.

**Comment by oppegard** [comment]
We (Wavefront team) recommend a new property be added to `WavefrontProperties.java`: `management.wavefront.trace-derived-custom-tag-keys`.

While this property name is different from the Spring Boot 2 property (`wavefront.tracing.red-metrics-custom-tag-keys`), it matches the name used in other Wavefront Tracing usages documented at https://docs.wavefront.com/tracing_customize_spans_and_alerts.html.

This would be wired into the `WavefrontSpanHandler` that @ttddyy linked to.

**Comment by wilkinsona** [comment]
Thanks, @oppegard.

Given that this was supported with Spring Boot 2 and the separate starter (albeit with a different property name), I think we should consider it to be a bug of omission in Spring Boot 3.0.

**Comment by oppegard** [comment]
@wilkinsona that makes sense to me too. Thank you.
