### ISSUE TITLE
Align start levels in launch.script header

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3419]
The default start levels are listed as 2, 3, 4, and 5 but the chkconfig configuration specifies only 3, 4, and 5:

```
### BEGIN INIT INFO
# Provides:          spring-boot-application
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Spring Boot Application
# Description:       Spring Boot Application
# chkconfig:         345 99 01
### END INIT INFO
```

Originally raised by @shakuzen [on Gitter](https://gitter.im/spring-projects/spring-boot?at=559a43d41e35a1a03f144156).

**Comment by joshiste** [comment]
Original pr #3243 was a copy from https://wiki.debian.org/LSBInitScripts
Inconsistency came in with #3115
