### ISSUE TITLE
Upgrade to a version of Spring Batch that's compatible with Spring Framework 4.2

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3421]
[This commit](https://github.com/spring-projects/spring-batch/commit/adc2f792421bf59a2b318ce6e82641a415b7aaae) should have made Spring Batch 3.0.4 compatible with Spring Framework 4.2, but it looks like at least one usage of `ParameterizedRowMapper` was missed. Unfortunately that code path isn't tested by Spring Boot's Batch integration so it's gone unnoticed until now.

**Comment by wilkinsona** [comment]
Spring Batch pull request: https://github.com/spring-projects/spring-batch/pull/374

**Comment by philwebb** [comment]
Merged in https://github.com/spring-projects/spring-batch/commit/ff2b6a8cee1488b8990a749a81f357af12e4e96f

**Comment by philwebb** [comment]
Looks like we're waiting for v3.1.0, is that correct @mminella or did this also get backported?

**Comment by mminella** [comment]
It should have been backported.  I can address this and cut a quick 3.0.5
release.

Michael

**Comment by snicoll** [comment]
That would be awesome, thanks. We're releasing M3 soon so having it would be even better :)

**Comment by bkummel** [comment]
Also see https://jira.spring.io/browse/BATCH-2414

**Comment by wilkinsona** [comment]
We might just be able to sneak this into M3 – @mminella is currently running the release promotion gauntlet
