### ISSUE TITLE
update el value in  openfeign mapper by code 。如何动态更新openfeign中el表达式的值

### ISSUE THREAD

**Issue by xlgo** [spring-projects/spring-boot#34229]
在 openfeign 中 
 
@GetMapping("clusters/${clusterId}/deployments/{deploymentName}")
 ResultVO<String> getDeployments(@PathVariable String deploymentName);
    
    
我写在配置文件中是生效的，我使用代码设置没有效果,我必须用代码修改
My writing in the configuration file is effective, and my use of code settings has no effect。I have to modify it with java code

System.setProperty("clusterId","2222");
SpringProperties.setProperty("clusterId","33333");
Environment environment = SpringUtil.getApplicationContext().getEnvironment();
((StandardEnvironment) environment).getSystemProperties().put("clusterId","44444");

**Comment by mhalbritter** [comment]
Hey, please report that issue on the [Spring Cloud OpenFeign tracker](https://github.com/spring-cloud/spring-cloud-openfeign), thanks!
