### ISSUE TITLE
Provide a setting for automatic context propagation with reactor-core

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#34235]
Forward port of issue #34201 to 3.1.x.

**Comment by wilkinsona** [comment]
We should review e67efe2674988ac7aea38c192497e704ad351470 as part of merging forwards any changes made to address https://github.com/spring-projects/spring-boot/issues/34201#issuecomment-1437414026 and https://github.com/spring-projects/spring-boot/issues/34201#issuecomment-1437420097.

**Comment by wilkinsona** [comment]
The changes have been reverted in [f6e208c](https://github.com/spring-projects/spring-boot/commit/f6e208c6471de17c12ea45df8ccd154c65d3cfb6).
