### ISSUE TITLE
About several typos found in the Quickstart page

### ISSUE THREAD

**Issue by ginkgo97** [spring-projects/spring-boot#34233]
Within https://spring.io/quickstart:
1. In Step2, "World" is used in the code part, while "Word" is used in the text part.
2. In Step3, it seems that `./gradlew bootRun` and `.\gradlew.bat bootRun` should replace the current command.

**Comment by wilkinsona** [comment]
Thanks. I have opened https://github.com/spring-io/spring-website/issues/116 to track this.
