### ISSUE TITLE
Spring batch link is broken in a 3.0 release notes wiki page

### ISSUE THREAD

**Issue by acktsap** [spring-projects/spring-boot#34231]
It looks spring batch link is broken in [Spring Boot 3.0 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes).

It goes to [5.0.0](https://github.com/spring-projects/spring-batch/releases/tag/5.0.0). Maybe it should be [v5.0.0](https://github.com/spring-projects/spring-batch/releases/tag/v5.0.0).

**Comment by mhalbritter** [comment]
Thank you, i fixed that!
