### ISSUE TITLE
Add jackson-datatype-hibernate4 to Spring Boot Gradle plugin's list of package versions to resolve

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#3424]
Hi,

Im using Spring Boot as a base platform for our application. We use Hibernate 4 and Jackson versions as supplied from Spring Boot.

In one of the scenarios, I need Jackson to initialize a lazy collection and thus, we use jackson-datatype-hibernate4 module.

When we use Maven, we have the below way to do achieve the functionality.

    <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-hibernate4</artifactId>
        <version>${jackson.version}</version>
    </dependency>

But, when we use Gradle, there doesnt seem to be a direct way to get the value {jackson.version} property, so that I can pull the corresponding version. Since both(Hibernate 4 and Jackson) come from Spring Boot, I think it is logical to have the Spring Boot Gradle plugin support jackson-datatype-hibernate4 module as well. 

I'm creating this issue based on my question at stackoverflow - http://stackoverflow.com/questions/31222095/spring-boot-get-property-of-a-package-in-gradle

Please suggest.

**Comment by snicoll** [comment]
There is no need to cross-post. As a matter of a fact I can see that @wilkinsona just replied you!
