### ISSUE TITLE
YAML problem with `spring-boot-devtools`

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#3425]
When I'm using YAML with `spring-boot-devtools` as follows:

```
@SpringBootApplication
public class Application implements CommandLineRunner {

	private final Yaml yaml = new Yaml(new Constructor(Person.class));

	@Override
	public void run(String... args) throws Exception {
		File file = ResourceUtils.getFile("classpath:data/person.yml");
		Object object = yaml.load(new FileInputStream(file));
		System.out.println(Person.class.getClassLoader());
		System.out.println(object.getClass().getClassLoader());

		Person person = (Person) object;
		...
	}

	...
	
}
```

I got the following exception:

```
Caused by: java.lang.ClassCastException: samples.springboot.Person cannot be cast to samples.springboot.Person
	at samples.springboot.Application.run(Application.java:29)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:664)
	... 9 more
```

They have different `ClassLoader`s as follows:

```
org.springframework.boot.devtools.restart.classloader.RestartClassLoader@5325d759
sun.misc.Launcher$AppClassLoader@33c7353a
```

When I removed `spring-boot-devtools` dependency,

they have the same `ClassLoader` as follows:

```
sun.misc.Launcher$AppClassLoader@5b2133b1
sun.misc.Launcher$AppClassLoader@5b2133b1
```

and worked as expected.

This is a sample project reproducing this problem:

https://github.com/izeye/samples-spring-boot-branches/tree/devtools

**Comment by wilkinsona** [comment]
I'm not sure there's much we can do about this. SnakeYAML uses `Class.forName(String)` to load the `Person` class (even though you've already given it a `Class`). That causes it to load the class class loader that loaded `YAML` which is the app class loader

**Comment by wilkinsona** [comment]
Here's a workaround:

```java
Constructor constructor = new Constructor(Person.class);
constructor.addTypeDescription(new TypeDescription(Person.class, "tag:yaml.org,2002:samples.springboot.Person"));
Yaml yaml = new Yaml(constructor);
```

**Comment by wilkinsona** [comment]
It looks like SnakeYAML's recommended approach to this is to use a `CustomClassLoaderConstructor` rather than a plain `Constructor`:

```
Yaml yaml = new Yaml(new CustomClassLoaderConstructor(Person.class, Person.class.getClassLoader()));
```

It may be worth raising an issue regarding their use of `Class.forName` – passing in the thread context class loader would allow the standard `Constructor` to be used, I believe.

**Comment by izeye** [comment]
@wilkinsona Thanks for the solution :+1:
