### ISSUE TITLE
spring-boot-maven-plugin exclude doesn't filter sub-dependency

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#3426]
```xml
<project>
  <dependencies>
    <dependency>
      <groupId>com.mysema.querydsl</groupId>
      <artifactId>querydsl-apt</artifactId>
      <version>${querydsl.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <groupId>com.mysema.querydsl</groupId>
              <artifactId>querydsl-apt</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

I will got a package with querydsl-codegen-3.6.4.jar in its lib-provided directory.

**Comment by philwebb** [comment]
Excludes won't automatically apply to transitive dependencies, you'll need to list everything that you want removed.

**Comment by tenstriker** [comment]
Why not? Who would want child dependencies in their project when they don't want parents? Can there be a flag to exclude it conditionally at least?

**Comment by jjroldan1** [comment]
Guys, you may want to reconsider if the design is appropriate for many of the use cases of the plugin.  The current behavior is not totally consistent when using ZIP and MODULE layouts in combination. I am going to use the layout factory feature coming in 1.5 (thanks @wilkinsona for the tip, I appreciate it) but still, I don't think you thought it through.
