### ISSUE TITLE
`spring-boot-starter-test-bdd` 

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#3430]
Hi,

I've noticed that a lot of the folks at Pivotal Labs are doing unit testing and some form of acceptance testing. Many use FluentLenium (which is a DSL on top of Selenium) and some sort of BDD tech like Cucumber. 

Could we provide a `starter` that brings in the `spring-boot-starter-test` dependency as well the extra bits for BDD-centric testing including Fluentlenium, Cucumber, etc. 

I think this is a more reasonable thing to do in light o the Spring test framework support in 4.2 / Spring Boot 1.3 for using Rules. This way, we could easily mix-n-match the Cucumber test runner and leverage the Spring Test Rule to get injection and so on.

**Comment by philwebb** [comment]
Possibly, but I've not really got enough experience to know what it will bring. I'd prefer to see this developed outside of the mainline as a side project to see how it works out.

**Comment by snicoll** [comment]
:+1:

**Comment by joshlong** [comment]
Ok - that's very fair. My proposal is 99% just having cucumber and fluentlenium on the `CLASSPATH`, not really code. Let me try it out with @sbrannen on 4.2 and see what it's like to build a BDD-test with Cucumber and 4.2's rule. I just want people to pull the right bits in. For that matter, for the basic test we could also move the generated unit test to the rule as well?

**Comment by sbrannen** [comment]
@joshlong, let me know when you have something concrete to take a look at.

**Comment by CyborTronik** [comment]
Is better to have ability to start application in pre-integration-test phase and to shutdown in post-integration-test.

Currently its very problematic to have 'real' integration tests where some of modules uses spring-boot (or in microservices structure). I still didn't found a way for running a spring-boot application from another jar file without blocking current phase in maven. Maybe you will suggest something for that?

**Comment by snicoll** [comment]
@CyborTronik this is already implemented, [check the documentation](http://docs.spring.io/spring-boot/docs/1.3.0.M2/maven-plugin/usage.html) (see _Working with integration tests_)

**Comment by CyborTronik** [comment]
Lets get by scenario:
I have a spring-boot module called "A".
Then I have another module called "B". So to do integration tests for "B" I have to start "A" in pre-integration-test and just after that run the "B" itself.

Is there a way to do that?

**Comment by snicoll** [comment]
No and this is not the best place to ask. Please consider creating a separate issue.

**Comment by CyborTronik** [comment]
OK, is used as part of BDD that is why I have asked here.
So anyway thanks.
Best regards

**Comment by snicoll** [comment]
@joshlong @sbrannen once you get a chance to look at it, we're happy to look at a PR
