### ISSUE TITLE
Fix PlatformTransactionManager auto-binding for Rabbit

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3432]
#3222 introduced a regression as Rabbit does not support JTA (contrary to JMS) so a different fix should be applied there.

Rabbit also has a `channelTransacted` flag that we could use

**Comment by snicoll** [comment]
I vote for switching the check on `RabbitTransactionManager` and add `channelTransacted` if it is not set (for consistency with the JMS part). This clearly means that users who want a local data store to run as part of the processing of a message should add `@Transactional` on their `@RabbitListener` method (or anything that's actually being called by that method.

I wouldn't expose the `channelTransacted` flag as it is quite dependent of the transaction manager configuration anyway. Non-transactional listeners can be set by creating their own factory after all.

**Comment by dsyer** [comment]
I removed the transaction manager completely from the rabbit container (user can create one explicitly if he wants it). For 1.3 we could extend the configurability. From @garyrussell:

> This is what they exposed in the CF tile for the xd rabbit bus: `ackMode`, `concurrency`, `maxConcurrency`, `prefetch`, and `txSize`.
