### ISSUE TITLE
WebMvcConfigurationSupport is not working as expected

### ISSUE THREAD

**Issue by ssomlk** [spring-projects/spring-boot#34358]
I am using spring boot 2.5.7

Created a webservice using spring boot and using below URL to sort all projects retrieved from the database (sort by projectId attribute, sort direction is descending)

`http://localhost:8081/api/projects?sort=projectId,desc`

Below is my controller, ProjectPage and PageSort models

```
@GetMapping
public ResponseEntity<Page<Project>> getAllProjects(
        @Valid ProjectPage projectPage,
        ProjectSearchCriteria projectSearchCriteria){
    return null;
}

public class ProjectPage {    
    @Valid
    private List<PageSort> sort;
}

public class PageSort {
    private String sortBy;
    private String sortDirection;
}
```
In order to convert the java.lang.String (projectId,desc passed in the request URL) to PageSort I have used converter SPI documented in https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#core-convert-Converter-API and this works perfectly.

1). I have extended the WebMvcConfigurationSupport

```
public class WebMvcConfig extends WebMvcConfigurationSupport {
    @Override
    protected void addFormatters(FormatterRegistry registry) {
        registry.addConverter(stringToPageSortConverter());
        super.addFormatters(registry);
    }

    @Bean
    public StringToPageSortConverter stringToPageSortConverter(){
        return new StringToPageSortConverter();
    }
}
```
2). And implemented the Converter as below

```
@Component
public class StringToPageSortConverter implements Converter<String, PageSort> {
    @Override
    public PageSort convert(String source) {
        PageSort pageSort;
        String[] _sort = source.split(",");
        if(_sort.length > 1){
            pageSort = PageSort.builder()
                    .sortBy(_sort[0])
                    .sortDirection(_sort[1])
                    .build();
        }else{
            pageSort = PageSort.builder()
                    .sortBy(_sort[0])
                    .sortDirection("asc")
                    .build();
        }

        return pageSort;
    }
}
```

When I invoke http://localhost:8081/api/projects?sort=projectId,desc and check the StringToPageSortConverter class I am seeing something as below. (Attaching snippets of the output as it's easier to see the issue graphically)

1). snippet one 

![image](https://user-images.githubusercontent.com/30547921/220945761-99c38b18-2775-4607-abdf-d2268ec63e65.png)

2). But when I continue resume from the breakpoint it hits the breakpoint again.

![image](https://user-images.githubusercontent.com/30547921/220945949-c6a6c56d-fb04-4db3-9d59-bff76d0bd3d2.png)

In the final projectPage variable in the controller now have two sort objects which are completely wrong. Should have been a single PageSort(sortBy=projectId, sortDirection=desc)

![image](https://user-images.githubusercontent.com/30547921/220946144-da022e0f-8cee-4164-87df-49e077bca95e.png)

I am not sure whether I am missing something here.

**Comment by wilkinsona** [comment]
Spring Boot 2.5.x is [no longer supported](https://spring.io/projects/spring-boot#support). Please upgrade to 2.7.x. If the problem still occurs and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by ssomlk** [comment]
I tried this in Spring boot 2.7.9 version and the issue still exists. I will provide a complete minimal sample code at earliest.

Thanks

**Comment by ssomlk** [comment]
[WebMvcConfigurationSupport.zip](https://github.com/spring-projects/spring-boot/files/10816154/WebMvcConfigurationSupport.zip)

Attached the project with minimal code herewith.

Please note that;

1) When the request URL is http://localhost:8081/api/projects?sort=projectId,desc&sort=projectName,desc it is working as expected. (See below)

![image](https://user-images.githubusercontent.com/30547921/220976535-4efc33f5-3b86-4e8e-9724-bff724325916.png)

2). Issue is when the request URL is http://localhost:8081/api/projects?sort=projectId,desc (single sort query parameter)

![image](https://user-images.githubusercontent.com/30547921/220977429-2e5db766-8da0-4118-a2d7-1652fe3f5bd5.png)
