### ISSUE TITLE
Define constant for @ConfigurationProperties prefix

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#34389]
It cost me several hours to fix migration to Spring Boot 3.0, my application code is intent to use the `RedisProperties` prefix, which is changed from `spring.redis` to `spring.data.redis`, It would be great if such prefix is defined as constant then other code can refer it.
for example:
```java
@ConfigurationProperties(prefix = RedisProperties.PREFIX)
public class RedisProperties {

	public static final String PREFIX = "spring.data.redis";

	...
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, I don't think we should do this as we find it to be quite unusual for code to extensively refer to configuration property prefixes. If you have code that needs to do that, you could define your own constant that meets your needs.

**Comment by quaff** [comment]
> Thanks for the suggestion. Unfortunately, I don't think we should do this as we find it to be quite unusual for code to extensively refer to configuration property prefixes. If you have code that needs to do that, you could define your own constant that meets your needs.

My own constant need to be synchronized with Spring Boot manually, It's error prone.

**Comment by wilkinsona** [comment]
Sorry, but I don't think we change prefixes often enough to justify providing constants for every configuration property prefix.
