### ISSUE TITLE
Add auto-configuration for OTLP span exporter

### ISSUE THREAD

**Issue by making** [spring-projects/spring-boot#34390]
Currently, only Zipkin (`ZipkinSpanExporter`) and Wavefront (`WavefrontOtelSpanExporter`) exporters are supported in auto configuration when using OpenTelemetry as the tracer.
Since there are many OpenTelemetry backends that support OTLP, it would be very useful to have OTLP exporter support as well.

Actually spring-cloud-sleuth-otel has such an auto configuration.
https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelExporterConfiguration.java

**Comment by uniquejava** [comment]
Yes,  I found Jaeger UI is more user friendly when displaying tracing data(e.g.  Better span name and SQL displayed nicely inside span)

 I wish spring boot 3 (micrometer) can export trace data to Jaeger. Like what it used to do with spring cloud sleuth.

**Comment by jonatan-ivanov** [comment]
This issue is about OTLP really, does not have too much to do with Jaeger specifically. The Jaeger collector can accept spans in the Zipkin format so you should be able to use Jaeger out of the box. Right now you can create a `JaegerGrpcSpanExporter` but if you want Boot to do it for you, could you please open an issue for it?

**Comment by sivaprasadreddy** [comment]
Followed @jonatan-ivanov hint and get Jaeger working. Here is a sample repo https://github.com/sivaprasadreddy/spring-boot-opentelemetry-demo

However, as Jaeger is a very popular choice, having auto-configuration support would be great.

**Comment by wilkinsona** [comment]
Closing in favor of #34508.
