### ISSUE TITLE
NullPointerException in DataSourceAutoConfiguration/NonEmbeddedConfiguration with null properties when @EnableCaching 

### ISSUE THREAD

**Issue by jceloi** [spring-projects/spring-boot#3440]
Hello,

I'm facing a weird problem on the 1.3.0.M1 : I encounter a `NullPointer` in `DataSourceAutoConfiguration` line 118 when `@EnableCaching` is added to my application and no `CacheManager` `@Bean` is manually created.

I can see in the logs that by manually declaring a *CacheManager* bean the `DataSourceProperties` is processed before the `DataSourceAutoConfiguration$NonEmbeddedConfiguration` constructor is called:

```
log 2015-07-08 10:53:51.496  INFO 27645 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'spring.datasource.CONFIGURATION_PROPERTIES' of type [class org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
``` 

When the `CacheManager` is not declared, this line is absent and the `DataSourceProperties` autowired into the `DataSourceAutoConfiguration$NonEmbeddedConfiguration` is null. A lot of fail then occurs...

From what I understood of 1.3.0.M1 documentation at least a standard `CacheManager` should be created automatically, that's the reason why I did delete mine... and saw this happen.

Context :
- Webapp
- MyBatis persistence layer and SqlSessionFactory @Bean created via a factory requiring a DataSource parameter

I could try to provide a boiled-down project showcasing that.

**Comment by snicoll** [comment]
I honestly don't see any link between the two but I does indeed  ring a bell. Maybe the check to validate if a CacheManager is there is triggering stuff too early. Would you be able to test something with the SNAPSHOT?

**Comment by jceloi** [comment]
Tested against 1.3.0.BUILD-SNAPSHOT : no difference. I've uploaded a dumbed down project from mine showcasing the problem here :

 https://github.com/jceloi/boot_issue_3440

**Comment by snicoll** [comment]
I have 

> No qualifying bean of type [test.jce.persistence.authentication.dao.mapper.AuthenticationMapper]

Is that the error I am supposed to see?

**Comment by jceloi** [comment]
This is a final consequence, but you should see a lot of :warnings like:

 Bean creation exception on FactoryBean type check: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationDao' defined in URL [jar:file:/home/xxx/boot_issue_3440/TestApiPersistence/target/TestApi-persistence-0.01-SNAPSHOT.jar!/test/jce/persistence/authentication/dao/AuthenticationDao.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory': : Error creating bean with name 'sqlSessionFactory' defined in class path resource [test/jce/persistence/configuration/DatabaseConfig.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.sql.DataSource]: : Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [test/jce/persistence/configuration/DatabaseConfig.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.sql.DataSource]: : Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource **[org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException**

Don't you ?

But anyway the project I shared is a mess, I'll simplify it.

**Comment by snicoll** [comment]
Hold on, let me try something first.

**Comment by snicoll** [comment]
OK so the link with `@EnableCaching` is obvious though your project fails in all sorts of weird way for me so I'd appreciate if you could simplify it. For one, having it work at all would help me indentifying where the issue is coming from.

Note also I found this that seems quite suspicious:

```
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [test/jce/persistence/configuration/DatabaseConfig.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.sql.DataSource]: : Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
```

If you don't want to scroll too much, the interesting bits are:

```
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [test/jce/persistence/configuration/DatabaseConfig.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.sql.DataSource]
```

The `@AutoconfigureAfter` on that class is totally useless as (as it's javadoc states) it is only use for auto-configuration. That `DatabaseConfig` of yours isn't.

**Comment by jceloi** [comment]
Agreed as I said the axe-chopping I did on the project to simplify it was a failure, that's the reason why it fails as it does.

Agreed also on the interesting bits that match what I did highlight in bold in my previous message. The datasource dependency is unsatisfied because of the nullpointer while autoconfiguring the datasource.

I'll come back to you once I've got a clean and simple showcase.

**Comment by philwebb** [comment]
Also I notice `[ restartedMain ]` in the logs, it's worth trying your app without `spring-boot-devtools` to see it something there is causing the problem.

**Comment by jceloi** [comment]
I pushed a cleaned up version of the test project, still there https://github.com/jceloi/boot_issue_3440

The readme explains my test procedure and you should be able to give it a proper try.

@philwebb : I tried removing the spring-boot-devtools from my poms : no difference

**Comment by snicoll** [comment]
So the `NullPointerException` comes from the `properties` field in `NonEmbeddedConfiguration` being `null`. It puzzles me how `@EnableCaching` could lead to such side effect.

**Comment by snicoll** [comment]
Okay so `CacheManagerValidatorPostProcessor` had a faulty code path that was provoking an early initialization of all beans hence the link with `@EnableCaching`. Your project now runs fine against master. Thanks for the report!

**Comment by jceloi** [comment]
Great I'll test that in the snapshot.

Thanks for fix !
