### ISSUE TITLE
Wiki document - Spring-Boot-3.0-Migration-Guide - add bracket to method defininition

### ISSUE THREAD

**Issue by hrkt** [spring-projects/spring-boot#34402]
Hi.
Current Wiki page on 3.0 migration guide (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
) has code sample like this.

```
@RestController
public class MyController {

  @GetMapping("/some/greeting")
  public String greeting {
    return "Hello";
  }

}
```

IMHO

```
- greeting
+ greeting()
```

might be correct.

**Comment by wilkinsona** [comment]
Thank you, @hrkt. I have updated the wiki.
