### ISSUE TITLE
Command Line Runner not working in Spring-Boot 3.0.3

### ISSUE THREAD

**Issue by rayman245** [spring-projects/spring-boot#34429]
I have a class which implements CommandLineRunner, this was working up till spring boot 3.0.2, but does not seem to run in spring-boot 3.0.3.

```
import com.springdatamongodbexample.repository.UserMongoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Bootstrap implements CommandLineRunner {

    @Autowired
    UserMongoRepository mongoRepository;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Hi");
    }
}
```

With 3.0.2
![image](https://user-images.githubusercontent.com/11938827/222326775-f25a0c3b-534a-45c8-8919-5b5604638b4b.png)

With 3.0.3
![image](https://user-images.githubusercontent.com/11938827/222326826-0ce3dfed-8b70-4df7-945c-5d6b0c4e7720.png)

**Comment by philwebb** [comment]
I suspect you're hitting #34379. Do you have a space or unusual character in your path?

**Comment by rayman245** [comment]
Thanks @philwebb yes I can confirmed this is related to #34379
