### ISSUE TITLE
kotlin-maven-plugin doesn't accept java.version 8 as jvmTarget

### ISSUE THREAD

**Issue by peter-janssen** [spring-projects/spring-boot#34438]
https://github.com/spring-projects/spring-boot/blob/2b94484078f6ed3f1d373e8146efaaecddcd9964/spring-boot-project/spring-boot-starters/spring-boot-starter-parent/build.gradle#L59

The maven compiler plugin and plexus compiler are ambiguous to the formatting of the java version before java 9 (e.g. 1.8 vs 8). Unfortunately this is not the case for the jetbrains kotlin-maven-plugin. And results in an error when 8 is used instead of 1.8. I wasn't able to find any documentation on the `java.version` property so it is unclear to me if this is expected/known behaviour.

**Comment by wilkinsona** [comment]
This is to be expected. `java.version` defaults to `1.8` in the pom for 2.7.x where that is our baseline version of Java so that it's compatible with all plugins on which it's configured.
