### ISSUE TITLE
spring-boot plugin + obfuscation doesn't work in Maven multi-module project

### ISSUE THREAD

**Issue by oleghailenko** [spring-projects/spring-boot#3444]
I have a multi-module Maven project. One of the modules is a web application. When I build Web project, all jar files are copied to target directory and then obfuscation runs over them. 
But I discovered that after this spring-boot plugin uses original jars of the other modules while packaging of war (but not from target directory of that web project). 
As a result war-archive contains obfuscated web module , but the not obfuscated other modules. 

I also discovered that there is no such problem with 1.2.1.RELEASE.

**Comment by philwebb** [comment]
What product are you using to perform obfuscation? Can you share a sample project that reproduces the issue?

**Comment by oleghailenko** [comment]
For obfuscation I am using proguard. Here repo with simple project: https://github.com/oleghailenko/spring-boot-obj

**Comment by wilkinsona** [comment]
You need to tell Boot's repackaging to ignore the obfuscated modules as you've already pulled them into the war file as web resources. You can do that by adding an exclude to your configuration of Boot's plugin:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<mainClass>org.test.WebModule.Application</mainClass>
		<excludeGroupIds>org.example</excludeGroupIds>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>repackage</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by wilkinsona** [comment]
And I just noticed that you think this worked without the exclude in 1.2.1.RELEASE so the exclude-based approach I described above shouldn't be necessary

**Comment by wilkinsona** [comment]
The change in behaviour was introduced in f761916b
