### ISSUE TITLE
Smarter @ConfigurationProperties binding for nested namespaces

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3445]
`ignoreUnknownFields` on `@ConfigurationProperties` is handled _locally_ while it should probably be validated against a given application.

Consider the following case:

```
@ConfigurationProperties(prefix= "foo", ignoreUnknownFields=true)
public class FooProperties { ...}
```

Then somewhere else in the project we have the following

```
@ConfigurationProperties("foo.bar")
public class FooBarProperties { ...}
```

The binder _might_ fail if we provide a valid property, let's say `foo.bar.name` because when it is processed against `FooProperties` that class does not have such field. In practice, this setup is perfectly OK, that property is valid, it's just that it's managed by a different class.

Maybe we should build that knowledge since we have the list `@ConfigurationProperties` annotated POJO for a given app.

**Comment by dsyer** [comment]
I like the idea of a global validation. It would be a bit hairy to implement though (as anything global is wont to be).

**Comment by snicoll** [comment]
This enhancement is there for quite a while and there isn't a obvious way to replace it so we're considering removing that feature altogether instead (#12601) rather than keeping it with false promise.

Looking at properties unbound on startup and generating a report would be a nice alternative, see #10030 for more  details.
