### ISSUE TITLE
Switch from single topic for fixed delays to single topic for same intervals in Spring Kafka retry configuration

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#34454]
In 3.1, replace deprecated `useSingleTopicForFixedDelays()` with `useSingleTopicForSameIntervals()`.

https://github.com/spring-projects/spring-boot/blob/8c3bf88abaf605acabcd0d8e03ce91db726a2c4b/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java#L165

**Comment by Abhijeetmishr** [comment]
@garyrussell @philwebb @wilkinsona Is this issue up for contribution. Can I raise a PR for this ?

**Comment by scottfrederick** [comment]
Closing in favor of #34504.
