### ISSUE TITLE
Initializr (start.spring.io) no longer works

### ISSUE THREAD

**Issue by helmbold** [spring-projects/spring-boot#34455]
The [initializr](https://start.spring.io/) doesn't produce a file to be downloaded when clicking "GENERATE" button nor does it show the generated project when clicking "EXPLORE".

After clicking one of the buttons the applications seems to hang:

![grafik](https://user-images.githubusercontent.com/5079980/222668017-a105005e-5b5b-4d9d-bf9d-4124e16f2b89.png)

Tested with a recent Firefox and Chrome version on Windows 10.

**Comment by wilkinsona** [comment]
It's working fine for me. I guess it may have been a temporary network-related problem. If the problem persists for you, please open a [start.spring.io issue](https://github.com/spring-io/start.spring.io/issues) providing some details about any failures that are reported in your browser's JavaScript console.

**Comment by helmbold** [comment]
Thanks for the immediate response. It actually worked for a short time after  filing this issue, but now I have the same error again. Otherwise I don't have network issues, so I'll file a start.spring.io issue.
