### ISSUE TITLE
Enhancement: Spring Boot 3.0 Migration Guide, add async-functions-return-types

### ISSUE THREAD

**Issue by tonnoz** [spring-projects/spring-boot#34468]
Would be nice to mention about the enforced return types for @Async annotated functions in the Spring Boot 3.0 migration guide, see my forked wiki version [here](https://github.com/tonnoz/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#async-functions-return-types). Could it be an idea to add it to the wiki?

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I think it would be better to cover this in Spring Framework's [guide for upgrading to 6.x](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x).
