### ISSUE TITLE
Add deprecated-hint to configuration meta-data JSON

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3449]
It would be nice if we could provide some description of why a property is deprecated and what alternative should be used.

**Comment by snicoll** [comment]
I think we can use the description field for that. What would be nice is a new field that would refer to the full id of an alternative key. How about `see-property` or something?

**Comment by philwebb** [comment]
Using the description field is a bit annoying, I would like something akin to the `@deprected` javadoc tag. A `see-property` isn't a bad idea but it should probably be called something else. Perhaps `deprecated-replacement`.

**Comment by snicoll** [comment]
What's the problem with the `description`? Do you mean you like the IDE to show the deprecated reason in a _separate_ area?

**Comment by YannCebron** [comment]
+1 for separate field to describe the deprecation reason
use-case: we still need to show "original" description regardless of deprecation status in various places (e.g. completion lookup), also it will be easier to display such info e.g. in full documentation popup for config key

**Comment by wilkinsona** [comment]
In an ideal world, the value of `deprecated` would be more than a boolean. If it were an object, we could do something like this:

```json
"deprecated": {
    "reason": "blah",
    "replacement": "foo.bar.baz"
}
```

The presence of `deprecated` would be used to indicate that a property is deprecated. The (possibly optional) `reason` and `replacement` would then provide further information. However, I don't think we can make this change without breaking any existing IDE support.

As an alternative, how about:

```json
"deprecated": true,
"deprecation": {
    "reason": "blah",
    "replacement": "foo.bar.baz"
}
```

`deprecated` is retained to preserve backwards compatibility. The semantics of `deprecation` are as described above. We can then deprecate `deprecated`.

**Comment by snicoll** [comment]
:+1:

**Comment by snicoll** [comment]
See also #3458
