### ISSUE TITLE
@RequestParam type conversion to List<String> removing %20 or whitespace at start of each query

### ISSUE THREAD

**Issue by bh4r4th** [spring-projects/spring-boot#34498]
# Problem Summary

Suppose in context: 
`@RequestParam(myList) myList: List<String>`

Let's say we expecting ` SOME_STRING_STARTS_WITH_WHITE_SPACE`,
Then while deserialisation to list is removing whitespace that present at the start of the query param. 

I am unsure whether Spring doing this or Kotlin. 

# Stack Used
Spring boot: 2.6.6
Kotlin: 1.6.10
Maven: 3.8.1

**Comment by philwebb** [comment]
`@RequestParam` is part of `spring-framework`, please raise issues at https://github.com/spring-projects/spring-framework/issues. If you do create an issue, please provide a sample application that shows the problem.
