### ISSUE TITLE
spring.data.cassandra.contact-points is ignored

### ISSUE THREAD

**Issue by neshkeev** [spring-projects/spring-boot#34492]
# What I did

My spring-data-cassandra application was built on top of the `2.7.3` version of Spring Boot, I decided to migrate to `3.0.4` and I discovered that `spring.data.cassandra.contact-points` is ignored and the application connects to `127.0.0.1:9042` regardless if I changed the value of the setting or not

# How to reproduce the problem

1. Clone the [project](https://github.com/neshkeev/consistent-cassandra-builder/)
2. Replace `2.7.3` with `3.0.4` [here](https://github.com/neshkeev/consistent-cassandra-builder/blob/master/pom.xml#L9)
3. Run `mvn test`

The app will start a testcontainers Cassandra container first and then with the help from [`DynamicProperties`](https://github.com/neshkeev/consistent-cassandra-builder/blob/master/src/test/java/com/github/neshkeev/papers/cassandra/AbstractContainerSetup.java#L67) amends the `spring.data.cassandra.contact-points` with the host and port from the started container.

# What is expected

The `spring.data.cassandra.contact-points` config is honored and the app connects to the node that is set in this config

# Additional

spring-data-cassandra [says](https://github.com/spring-projects/spring-data-cassandra/issues/1360#issuecomment-1455638845) I should file a ticket here

**Comment by wilkinsona** [comment]
You need to use `spring.cassandra.contact-points` in Boot 3.0 as [described in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#cassandra-properties). The [properties migrator module](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#configuration-properties-migration) can help you here.
