### ISSUE TITLE
@PathVariable type conversion to UUID is not correct

### ISSUE THREAD

**Issue by bh4r4th** [spring-projects/spring-boot#34497]
# Problem Summary

Suppose in context: 
`@PathVariable(id) id: UUID`

Let's say `c7fc2ea4-b4ef-489a-b8df-2f02fac8b80e` is a valid UUID. 
If we send in path an invalid UUID, suppose like `c7fc2ea4-b4ef-489a-b8df-2f02fac8b` then on deserialisation to UUID, this string is getting converted to `c7fc2ea4-b4ef-489a-b8df-0002f02fac8b`

I am unsure whether Spring doing this or Kotlin. 

# Stack Used
Spring boot: 2.6.6
Kotlin: 1.6.10
Maven: 3.8.1

**Comment by philwebb** [comment]
`@PathVariable` is part of `spring-framework`, please raise issues at https://github.com/spring-projects/spring-framework/issues. If you do create an issue, please provide a sample application that shows the problem.
