### ISSUE TITLE
Update spring-boot-sample-amqp to use @EnableRabbit and @RabbitListener

### ISSUE THREAD

**Issue by lucassaldanha** [spring-projects/spring-boot#3451]
We recently updated the documentation to include details about using AMQP with Spring Boot (issue #3348)

I believe that it would be nice to update the **spring-boot-sample-amqp** code to match what we included in the documentation (using @EnableRabbit and @RabbitListener).

I'd be glad to help updating this code. I'll prepare a PR if you guys think that it is nice to update the examples.

@snicoll what do you think?

**Comment by snicoll** [comment]
Looks like this was done 3 days ago already, see https://github.com/spring-projects/spring-boot/commit/4581c5a27345eb4b2e15426a2ec83068171c8736
