### ISSUE TITLE
Code sample in "Developing Your First Spring Boot Application" does not work

### ISSUE THREAD

**Issue by tehnodev** [spring-projects/spring-boot#34513]
[MyApplication.java](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#getting-started.first-application.code) example code do not work without package declaration. spring-boot:run command shows
```
...
** WARNING ** : Your ApplicationContext is unlikely to start due to a @ComponentScan of the default package.
...
Caused by: java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$PoolConfiguration due to io/r2dbc/spi/ValidationDepth not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
...
```

**Comment by bclozel** [comment]
In which package is your main application located? The error message seems to indicate that it is using an invalid location.

Can you share a sample application showing the problem?

**Comment by tehnodev** [comment]
No package. File is located as stated in documentation at src/main/java/MyApplication.java

**Comment by tehnodev** [comment]
I suggest to change file location to src/main/java/sample/MyApplication.java and add "package sample;"  at the top of example file

**Comment by petrovskimario** [comment]
Has this been picked up by anyone ? If not i can pick this up

**Comment by wilkinsona** [comment]
Thanks for the offer, @petrovskimario. It's all yours.

The [code](https://github.com/spring-projects/spring-boot/blob/295702003ddb57bd5d6cfaf52a1c1426ced26249/spring-boot-project/spring-boot-docs/src/main/java/org/springframework/boot/docs/gettingstarted/firstapplication/code/MyApplication.java) already has a package but it's deliberately removed by the [code chomping in our Asciidoctor backend](https://github.com/spring-io/spring-asciidoctor-backends#code-chomping). It should be possible to use `chomp_package_replacement` to configure the package for this particular code snippet. Please let us know if you have any questions.

**Comment by wilkinsona** [comment]
You can set a document-wide attribute in `attributes.adoc`:

```
:chomp_package_replacement: example
```

But this will affect every code snippet in the documentation. I thought it should also be possible to set it on a per-snippet basis like this:

```
include::code:MyApplication[chomp_package_replacement=example]
```

But it doesn't seem to work. Should it have worked, @philwebb?

With the global attribute in place, the package always appears, even when the snippet isn't expanded:

```java
package example;

@RestController
@SpringBootApplication
public class MyApplication {

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }

}
```

I'm not sure if this is what we want. It might be nice for the package to be changed but remain hidden until the code's expanded or copied.

**Comment by philwebb** [comment]
I'll have to take a look at the backend code. We do have [this test](https://raw.githubusercontent.com/spring-io/spring-asciidoctor-backends/7ca46d42a4fc84c491b7c1d721e6655af2a4fa72/src/test/resources/io/spring/asciidoctor/backend/codetools/ChompListingContentConverterTests_convertWhenChompPackageAndReplacementReturnsWithReplacedPackage.adoc) but it's not using `include::code`.

**Comment by petrovskimario** [comment]
Is it maybe possible to use the chomp_package_replacement with some predicates ?
For example i am thinking something like this : 
:chomp_package_replacement: example where package = something

**Comment by snicoll** [comment]
@petrovskimario do you still need help for this? Any update for us?

**Comment by wilkinsona** [comment]
@snicoll as per [Phil's comment](https://github.com/spring-projects/spring-boot/issues/34513#issuecomment-1601762907) there's a limitation of the Asciidoctor backend that's blocking progress.

**Comment by philwebb** [comment]
It turns out the the backend does support but the attribute needs to be above the include line and not part of it.
