### ISSUE TITLE
Easy to integration with Spring Batch Admin.

### ISSUE THREAD

**Issue by wizwjw** [spring-projects/spring-boot#3453]
I tried to integrate Spring Batch Admin with Spring boot. 
Import SBA config file using @ImportResource.

```java
@Configuration
@EnableAutoConfiguration(exclude = {
		BatchAutoConfiguration.class,
		DataSourceAutoConfiguration.class,
		WebMvcAutoConfiguration.class,
		FreeMarkerAutoConfiguration.class})
@ComponentScan
@ImportResource({"classpath:/org/springframework/batch/admin/web/resources/servlet-config.xml",
		"classpath:/org/springframework/batch/admin/web/resources/webapp-config.xml"})
public class MyApp {
	public static void main(String[] args) {
		SpringApplication.run(MyApp.class, args);
	}
}
```

The app can start without exception, but the js and css can not load normally.

![image](https://cloud.githubusercontent.com/assets/1625837/8587323/6ee6303c-262c-11e5-89a2-a722b41658eb.png)

Then, I tried to config context-path, the resources load normally, but when I tried to visit `/jobs` url,
a server error occurs.
 I take some breakpoint in SBA source code `org.springframework.batch.admin.web.JobController`.
```java
	@ModelAttribute("jobName")
	public String getJobName(HttpServletRequest request) {
		String path = request.getPathInfo();
		int index = path.lastIndexOf("jobs/") + 5;
		if (index >= 0) {
			path = path.substring(index);
		}
		if (!path.contains(".")) {
			return path;
		}
		for (String extension : extensions) {
			if (path.endsWith(extension)) {
				path = StringUtils.stripFilenameExtension(path);
				// Only remove one extension so a job can be called job.html and
				// still be addressed
				break;
			}
		}
		return path;
	}
```
 then I find out, `request.getPathInfo()` always return null. And `NullPointerException` always throw.

**Comment by snicoll** [comment]
ping @mminella

**Comment by mminella** [comment]
@wizwjw Per your other issue in Spring Batch Admin Samples (https://github.com/spring-projects/spring-batch-admin-samples/issues/1), build the latest version locally and use the new `@EnableBatchAdmin` annotation.  It's by far the easiest option right now.  I'll be addressing the SNAPSHOT builds today.

**Comment by wilkinsona** [comment]
Thank you, @mminella.

**Comment by wizwjw** [comment]
@mminella Thank you, I already build the  latest version locally. I am looking forward the release(or milestone ) of SBA.
