### ISSUE TITLE
Best Way to Add "self-registering" spring.config.location's in a JAR

### ISSUE THREAD

**Issue by jonathanamartin** [spring-projects/spring-boot#3455]
I have 5 library projects in which I'd like to provide default profile-based configuration.  This default profile based configuration needs to be overridable by client applications.  I'd like the  "application-{profile}.yaml" config file to be located in a namespaced directory for each project.

Here's an example of the naming conventions that all projects follow:

src/main/resources/my/root/namespace/project-namespace/application-{profile}.yaml 

More concrete example:
src/main/resources/my/root/namespace/web/application-{profile}.yaml
src/main/resources/my/root/namespace/security/application-{profile}.yaml
src/main/resources/my/root/namespace/analytics/application-{profile}.yaml

I've been able to add additional spring.config.location's from the command line.  However, what I'd really like is that each project registers these additional config locations themselves.  What's the cleanest/most elegant way to do this?

I've thought of attempting to use the Spring Boot application events.  I've also thought using a staticly initialized bean might do the trick.  Though I'm not really sure what the best approach would be.

Also, since all the config files are located in a similar directory does the spring.config.location take "ant-style" paths with wild cards?

i.e. spring.config.location=classpath:/my/root/namepsace/**/config/

Any help would be greatly appreciated.

**Comment by snicoll** [comment]
Hey,

Interesting use case. As you know already `spring.config.location` needs to be a property that is available right when Spring Boot starts. Let's not forget you can do whatever you want before calling `SpringApplication.run` (or whatever you're calling).

It would be a good chance right before that to read some file descriptor of yours and build the value of `spring.config.location` accordingly. Then you can pass that as a command-line switch.

Regarding your second question (probably best asked on SO btw), [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files) mentions that you can specify folders (ending with a slash) or files. There is no support for "ant-style".

Let me know if we can close this one.

**Comment by jonathanamartin** [comment]
Hey thanks for the quick response.  That sounds like a viable approach.  I'm good to close this issue.

**Comment by jonathanamartin** [comment]
Hey my aplogies just had one more question around this.  Is there a way to add command line arguments programmatically to a test?

**Comment by snicoll** [comment]
Please ask on StackOverflow Jonathan, this tracker should be used for bug reports and feature requests. That being said, you're probably looking for [`@PropertySource`](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-location-of-external-properties) - In the case of a test, have a look to [`@TestPropertySource`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/TestPropertySource.html)

**Comment by jonathanamartin** [comment]
Will do thanks for the response.  My apologies.  Will ask other questions on SO.
