### ISSUE TITLE
spring-boot-starter-data-jpa 2.7.9 version alignment

### ISSUE THREAD

**Issue by joaquinjsb** [spring-projects/spring-boot#34564]
Hello guys,
when downloading the dependency, it still has the 2.7.8 which contains a version with a bug, this should be aligned to 2.7.9.

this is the pom
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-data-jpa/2.7.9/spring-boot-starter-data-jpa-2.7.9.pom

```

<dependency>
<groupId>org.springframework.data</groupId>
<artifactId>spring-data-jpa</artifactId>
**<version>2.7.8</version>**
<scope>compile</scope>
</dependency>
```

**Comment by wilkinsona** [comment]
We haven't released Spring Boot 2.7.x since Spring Data JPA 2.7.9 was released. https://github.com/spring-projects/spring-boot/issues/34530 is tracking the upgrade which is already available in snapshots.
