### ISSUE TITLE
I give up to use spring-boot-devtools

### ISSUE THREAD

**Issue by zdu-strong** [spring-projects/spring-boot#34584]
The new version of spring-boot-devtools is not easy to use, it is frequent to appear ClassCastException.
I had to give it up.

**Comment by wilkinsona** [comment]
Sorry to hear that you had problems with DevTools. Unfortunately, without some more information, we won't be able to help you. Have you read the [section in the reference documentation](https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/using.html#using.devtools.diagnosing-classloading-issues) on diagnosing class loading issues and followed its recommendations? If they do not help and you would like us to spend some more time trying to help you, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by zdu-strong** [comment]
I understand that devtools use BaseClassLoader for all .jar packages and RestartClassLoader for code in the project.
I recommend using BaseClassLoader only for a part .jar packages that are known to work fine.

Later, I will upload my code and steps to reproduce.

**Comment by zdu-strong** [comment]
My repository: [https://github.com/zdu-strong/temp-devtools](https://github.com/zdu-strong/temp-devtools)
Environmental requirements: Java v17
Steps to reproduce:
1. Run command:

    ./mvn clean compile spring-boot:run
    
2. Open a browser, visit http://localhost:8080
3. Comment out the code - userModel.toString();

![change](https://user-images.githubusercontent.com/48673442/224519562-830de396-ffc4-4f82-8c82-860910d9aea3.png)

4. Visit http://localhost:8080 in browser. You will see the result.

![result](https://user-images.githubusercontent.com/48673442/224519636-f6cdc7a3-55a1-4d3e-b34a-01663df975e0.png)

**Comment by zdu-strong** [comment]
Thank you.
I think the problem is due to fastjson, I replaced it with gson and it solved the problem.

![before](https://user-images.githubusercontent.com/48673442/224519745-999c61a3-a256-4294-b1c7-9eece8374e3a.png)

![after](https://user-images.githubusercontent.com/48673442/224519752-d07ffd39-91b7-4266-840c-9d348d4e15f0.png)

**Comment by myheavyhead** [comment]
@zdu-strong Why not try it jackson :).

**Comment by zdu-strong** [comment]
As you know jackson is more functional and I have switched to jackson.
Thank you.
