### ISSUE TITLE
How can I replace the default banner?

### ISSUE THREAD

**Issue by myheavyhead** [spring-projects/spring-boot#34588]
Deprecated Support for image banners has been removed. When i want to change the banner for my boot3.0.0, there are some problems.

**Comment by l4dfire** [comment]
绷，banner.txt or banner.jpg with ur spring.yml

**Comment by philwebb** [comment]
You can use a `banner.txt` file instead of `banner.jpg`. There's an [older tool someone wrote](https://github.com/cbornet/image2springbanner) that can create banners that might help.
