### ISSUE TITLE
SpringBoot3 integrate log4j2 xml 

### ISSUE THREAD

**Issue by wiscloud** [spring-projects/spring-boot#34593]
The current springboot version is 3.0.4, Reading spring environment variables failed when using log4j2's configuration file, The file name is changed to `log4j2-spring.xml`, This problem doesn't exist on windows, but it does on the Mac M1.

```xml
<Properties>
        <Property name="APPLICATION_NAME">${spring:spring.application.name}</Property>
        <property name="LOG_HOME">./${APPLICATION_NAME}/logs</property>
</Properties>
```

**Comment by wiscloud** [comment]
`
    <Properties>
 
        <Property name="APPLICATION_NAME">${spring:spring.application.name}</Property>
       
        <property name="LOG_HOME">./${APPLICATION_NAME}/logs</property>
    </Properties>
`

**Comment by philwebb** [comment]
Please could you provide a minimal sample with instructions on how we can replicate the issue.

**Comment by wiscloud** [comment]
> Please could you provide a minimal sample with instructions on how we can replicate the issue.

The cause of the problem has been identified due to the introduction of `spring-cloud-starter-bootstrap` dependency, but `spring.application.name `is configured in` application.yaml`, if the configuration is in` bootstrap.yaml,` the effect is fine
