### ISSUE TITLE
Replacement for `fork` on spring-boot-maven-plugin 

### ISSUE THREAD

**Issue by J-mirzaei** [spring-projects/spring-boot#34597]
The problem is that we need to run the e2e tests (`Cucumber`) with some stubs and the Spring config server.
Stubs and config server should start before the main application and should stop after the e2e tests.

With spring boot 2 (before removing the `fork` configuration) we were starting stubs and config server with the below configuration:

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <fork>false</fork>
        <profiles>
            <profile>local</profile>
        </profiles>
        <jmxName>org.springframework.boot:type=Admin,name=${project.artifactId}</jmxName>
    </configuration>
    <executions>
        <execution>
            <id>start-spring-boot-app</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
and the `maven-failsafe-plugin` was ending the process.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <configuration>
        <testFailureIgnore>false</testFailureIgnore>
    </configuration>
    <executions>
        <execution>
            <id>integration-test</id>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Also, I tried to kill the process with the `shutdown` of the `maven-failsafe-plugin` but it did not work.
I have created a [sample application on github](https://github.com/J-mirzaei/spring-boot-maven-plugin-sample).

I saw no replacement for `fork` on spring boot 3. So I need a solution for it and in my opinion, this is a typical setup to run e2e tests.

**Comment by wilkinsona** [comment]
@J-mirzaei Have you looked at the [stop goal](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-stop)? If so, am I right in thinking that it did not meet your needs because "stubs and config server should start before the main application and should stop after the e2e tests"?

**Comment by J-mirzaei** [comment]
Hi @wilkinsona 
Thank you for the fast response.
It can be a solution and I will test it ASAP. 
It can be handier to have some solution on spring boot to run e2e tests.

**Comment by J-mirzaei** [comment]
Hi @wilkinsona 

It works. I did an update on the shared Github project. 
But as you see the plugin has open issues. For example, running commands on a Windows machine. 
There is also a workaround for that but not a nice solution.
Thank you for the help.

**Comment by wilkinsona** [comment]
Thanks for following up, @J-mirzaei. I think using the third-party plugin is the right approach. Unfortunately we don't have the resources to implement and maintain something similar, particularly as it isn't specific to Spring Boot and is more a general piece of Maven functionality. You may also want to consider using Gradle as it doesn't have the execution ordering problems that Maven's lifecycle- and phase-based approach does.
