### ISSUE TITLE
Reduce the boilerplate that's required in tests that use a service in a Testcontainers-managed container

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#34658]
A common pattern when using Testcontainers is to use `@DynamicPropertySource` to configure the properties required to use the service in the Testcontainers-managed container. For example, you might do something like this to use Redis:

```
@Container
static GenericContainer redis = new GenericContainer(DockerImageName.parse("redis").withTag("4.0.14"));

// …

@DynamicPropertySource
static void redisProperties(DynamicPropertyRegistry registry) {
	registry.add("spring.data.redis.host", redis::getHost);
	registry.add("spring.data.redis.port", redis::getFirstMappedPort);
}
```

We can reduce this boilerplate by automatically extracting [connection details](https://github.com/spring-projects/spring-boot/issues/34657) from the service in the container and making them available to the auto-configuration:

```
@Container
@RedisConnection
static RedisContainer redis = new RedisContainer();
```

Here, `@RedisConnection` indicates that the container should be used a source of Redis connection details. Spring Boot will provide built-in support for extracting those details from the container while still allowing the Testcontainers API to be used to define and configure the container.

**Comment by rajadilipkolli** [comment]
I have a use case where I am connecting to postgres using webflux but managing sql schema using liquibase,  so in current process I need to set both database properties and liquibase properties in dynamicpropertysource , will this update takes care of this usecase as well??

**Comment by joschi** [comment]
Does this feature/how does this feature relate to https://github.com/PlaytikaOSS/testcontainers-spring-boot?

**Comment by wilkinsona** [comment]
TIL about testcontainers-spring-boot… There's no relationship between the two.

**Comment by jucosorin** [comment]
Hi @wilkinsona 

First of all, the new `@ServiceConnection` and related annotations are a great addition for running integration tests with Testcontainers. 
At the company I work for, I have created a Spring Boot Starter which is used for configuring Spring Kafka. The main autoconfiguration class kicks in with: 

```java
@AutoConfiguration(after = TaskSchedulingAutoConfiguration.class)
@EnableConfigurationProperties(StreamingKafkaProperties.class)
@ConditionalOnClass(name = "org.springframework.kafka.annotation.EnableKafka")
@ConditionalOnProperty(value = "mm.kafka.enabled", havingValue = "true")
@Import({
    StreamingKafkaSASLAutoConfiguration.class,
    StreamingKafkaProducerAutoConfiguration.class,
    StreamingKafkaConsumerAutoConfiguration.class,
    StreamingKafkaRetryAutoConfiguration.class,
    KafkaMessageService.class,
    AlertingMessageCreator.class,
    AlertingProducerService.class
})
public class StreamingKafkaAutoConfiguration {
```

We are doing integration tests using Testcontainers, and before this feature was introduced we were using the following to get the **_spring.kafka.bootstrap-servers_** injected into the Spring tests:

```java
@Container
  private static final KafkaContainer kafkaContainer = new KafkaContainer(DockerImageName.parse(TESTCONTAINERS_KAFKA_IMAGE))
      .withEnv("KAFKA_AUTO_CREATE_TOPICS_ENABLE", "FALSE");

  @DynamicPropertySource
  static void setProperties(DynamicPropertyRegistry registry) {
    registry.add("spring.kafka.bootstrap-servers", kafkaContainer::getBootstrapServers);
  }
```

I wanted to switch to using `@ServiceConnection` and the code changed to: 

```java 
@Container
@KafkaServiceConnection
private static final KafkaContainer kafkaContainer = new 
  KafkaContainer(DockerImageName.parse(TESTCONTAINERS_KAFKA_IMAGE))
      .withEnv("KAFKA_AUTO_CREATE_TOPICS_ENABLE", "FALSE");
``` 

The problem is that with this approach, the **_@KafkaServiceConnection_** test autoconfiguration kicks in after the code in my Spring Boot Starter and this results in _**"spring.kafka.bootstrap-servers"**_ always being set to the default value of "PLAINTEXT://locahost:9092". The only solution to make this work is to add back the @DynamicPropertySource code since this injects the Testcontainers Kafka container port in my autoconfiguration classes. 

Is there a more elegant solution to this? Am I not using this as it should be used?
As I understand it, the whole point of using @KafkaServiceConnection is to not need to use the @DynamicPropertySource.

**Comment by wilkinsona** [comment]
@jucosorin Thanks for trying out the milestone. Can you please open a separate issue for this?

**Comment by sergey-morenets** [comment]
Hi @wilkinsona 

Are the code samples in this thread still relevant? I upgraded to Spring Boot 3.1.0 but couldn't find annotation @JdbcServiceConnection.

**Comment by eddumelendez** [comment]
Hi, it's only `@ServiceConnection` now. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.testcontainers.service-connections

**Comment by sergey-morenets** [comment]
Hi @eddumelendez 

Thank you for the quick response.

**Comment by pandamaroder** [comment]
ive tried this 

	testImplementation("com.redis:testcontainers-redis:2.2.2")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")

	testImplementation("org.springframework.boot:spring-boot-starter-test")

	testImplementation("org.springframework.boot:spring-boot-testcontainers:2.6.0")
	testImplementation("org.springframework.boot:spring-boot-test-autoconfigure:2.6.0")

**Comment by wilkinsona** [comment]
As we worked on this, we removed the need for service-specific annotations so there's no `@RedisServiceConnection`. You should use `@ServiceConnection` instead. You can learn more in [the documentation](https://docs.spring.io/spring-boot/reference/testing/testcontainers.html#testing.testcontainers.service-connections).

**Comment by rajadilipkolli** [comment]
Hi @wilkinsona ,

for databases and others adding `@ServiceConnection` is enough but for using redis in SB 3.4.0-M1 , I still need to use `@ServiceConnection("redis")` . Is this done to support both redis and Redis-stack containers?

```java
    @Bean
    @ServiceConnection("redis")
    RedisContainer redisContainer() {
        return new RedisContainer(DockerImageName.parse("redis").withTag("7.4.0-alpine"));
    }
```

**Comment by scottfrederick** [comment]
@rajadilipkolli There is an explanation of this in the [documentation](https://docs.spring.io/spring-boot/reference/testing/testcontainers.html#testing.testcontainers.service-connections) that Andy linked to above: 

> If you’re using a `@Bean` method, Spring Boot won’t call the bean method to get the Docker image name, because this would cause eager initialization issues. Instead, the return type of the bean method is used to find out which connection detail should be used. This works as long as you’re using typed containers, e.g. `Neo4jContainer` or `RabbitMQContainer`. This stops working if you’re using `GenericContainer`, e.g. with Redis, as shown in the following example:

What is the `RedisContainer` class that you are using? Is it an implementation of `GenericContainer` or something else?

**Comment by wilkinsona** [comment]
Could be related to https://github.com/spring-projects/spring-boot/issues/41450.

**Comment by rajadilipkolli** [comment]
yes, related to #41450, I am trying the milestone release in preparation for 3.4.0 release.
