### ISSUE TITLE
Document requirement for Maven 3.6.3 or later

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#34694]
The latest version of the Maven Help Plugin (https://github.com/spring-projects/spring-boot/issues/34687) requires Maven 3.6.3. We should update our supported versions of Maven accordingly.

**Comment by Abhijeetmishr** [comment]
@wilkinsona can I pick this up ?

**Comment by wilkinsona** [comment]
Thanks for the offer, @Abhijeetmishr, but let's finish up https://github.com/spring-projects/spring-boot/pull/34744 first please.

**Comment by wilkinsona** [comment]
Thanks, @isabek. It's all yours.

**Comment by wilkinsona** [comment]
Closing in favor of #34759. Thanks very much for the PR, @isabek.
