### ISSUE TITLE
Banner placeholders do not support default values

### ISSUE THREAD

**Issue by Saucistophe** [spring-projects/spring-boot#34713]
The `ResourceBanner` uses placeholders with the regular syntax `${variable.name}` syntax.

There are only a few variables supported, which is fine; and some of them, such as the application version, is not resolved when starting the project from IDE (as opposed from the jar).

I wanted to use default values, for instance `${application.version:dev}`; when I do that, the printed version becomes `dev` regardless of whether it's defined.

I reproduced the issue in unit tests in `ResourceBannerTests`, and I think it is due to the way we handle resolvers:

```java
for (PropertyResolver resolver : getPropertyResolvers(environment, sourceClass)) {
    banner = resolver.resolvePlaceholders(banner);
}
```

If the first resolver fails to find the value, it outputs the default value and it's final.

**Comment by wilkinsona** [comment]
It's all yours, @krzyk. Thank you.

**Comment by Saucistophe** [comment]
If that can help, here is the test I wrote:
```java
	@Test
	void renderDefaultValues() {
		Resource resource = new ByteArrayResource(
				"banner ${a}${spring-boot.formatted-version:default-value}".getBytes());
		String banner = printBanner(resource, "10.2", "2.0", null);
		assertThat(banner).startsWith("banner 1 (v10.2)");
	}
```

..Which yields:
```
java.lang.AssertionError: 
Expecting actual:
  "banner 1default-value
"
to start with:
  "banner 1 (v10.2)"
```

**Comment by krzyk** [comment]
@Saucistophe I just tried to recreate it but, well, it works.
Your testcase has error, because you provide the "10.2" as the second argument (this is boot version) so if you change it to `null` it will pass.

**Comment by wilkinsona** [comment]
Closing in favor of #34764. Thanks for the PR, @krzyk.
