### ISSUE TITLE
MinIdle and MaxValidationTime properties missing for R2DBC pools

### ISSUE THREAD

**Issue by marcelop3251** [spring-projects/spring-boot#34724]
Spring boot version: 2.7.9, the spring-boot-project version of r2dbc more specifically the class
`spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations.java` does not map the new property available in r2dbc-pool, in the case of **minIdle** the idea is to map this field?

See new field in
https://github.com/r2dbc/r2dbc-pool/blob/0.9.x/src/main/java/io/r2dbc/pool/ConnectionPoolConfiguration.java

Is there any specific reason for not having mapped?

**Comment by wilkinsona** [comment]
Thanks for spotting this. It looks like it was missed as part of https://github.com/spring-projects/spring-boot/issues/32328. I think we could consider that to be a bug, but I'd like to get some opinions from the rest of the team before we make a decision about the issue's milestone.

**Comment by mhalbritter** [comment]
I added mappings for `min-idle` and `max-validation-time`.
