### ISSUE TITLE
Invalid reference to RequestParameters in Freemarker after upgrade

### ISSUE THREAD

**Issue by anabright** [spring-projects/spring-boot#34733]
I just upgraded my app to Spring Boot 3.0.5 and there seems to be something broken with `spring-boot-starter-freemarker`.

In my Freemarker template, I have this line that used to work before the upgrade:

`<div>${RequestParameters.myParam!}</div>`

After the upgrade, I get this error when loading the template:

``` 
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> RequestParameters  [in template "template.ftlh" at line 136, column 11]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${RequestParameters.myParam!}  [in template "template.ftlh" at line 136, column 9]
```

It seems like `RequestParameters` is not available anymore.

Is there a fix in sight for this? 
Any workarounds?

Thanks!

**Comment by wilkinsona** [comment]
Which version of Spring Boot were you using before the upgrade?

As far as I can remember, we haven't made many, if any, recent changes to our FreeMarker support. Once possibility is [this change in Spring Framework](https://github.com/spring-projects/spring-framework/issues/29787).

**Comment by anabright** [comment]
I upgraded from 2.7.10. If I go back to it, it works again.
Not sure if the issue you linked is the cause, it doesn't seem to mention any changes to the availability of `RequestParameters`

**Comment by startjava** [comment]
use spring-boot 3.1.2

use url：
http://localhost:8080/test20?selectedValue=d

template code：
<select>
  <#if  listString?? && listString?size!=0>
    <#list listString as list>
      <#if RequestParameters['selectedValue']==list>
        <option value="${list}" selected="selected">${list}</option>
      </#if>
      <#if RequestParameters['selectedValue']!=list>
          <option value="${list}">${list}</option>
      </#if>
    </#list>
  </#if>
<select>

controller code：
@RequestMapping("test20")
    public String test20(Model model,HttpServletRequest request,HttpServletResponse response)

{         List listString=new ArrayList();         listString.add("a");         listString.add("b");         listString.add("c");         listString.add("d");         listString.add("e");         request.setAttribute("listString",listString);         return "test20";     }
 

run result ：
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> RequestParameters  [in template "test20.ftlh" at line 12, column 12]

Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

FTL stack trace ("~" means nesting-related):
    - Failed at: #if RequestParameters.selectedValue =...  

[in template "test20.ftlh" at line 12, column 7]

@wilkinsona 
same question！

**Comment by startjava** [comment]
@anabright

**Comment by startjava** [comment]
https://github.com/spring-projects/spring-framework/issues/30186

**Comment by wilkinsona** [comment]
@startjava please stop making the same comments across multiple issues

**Comment by doctore** [comment]
I had this problem upgrading an old project from Spring 3 to Spring 6, by now we have no time to replace the technology used to render the views, so my solution was adding it as a new model attribute of FreeMarker.

Replacing:

```
<#if RequestParameters['authfail']??>
  ...
</#if>
```

By, in backend:

```
@ModelAttribute("rawRequestParameters") 
public String getRequestParameters(HttpServletRequest request) {
  return ofNullable(request)
            .map(HttpServletRequest::getQueryString)
            .orElse("");
}
```

and in frontend:

```
<#if rawRequestParameters?? && rawRequestParameters == "authfail">
  ...
</#if>
```
