### ISSUE TITLE
Application yaml files cannot be loaded when they exceed 3mb

### ISSUE THREAD

**Issue by kirangodishala** [spring-projects/spring-boot#34743]
I am from [Spinnaker community ](https://spinnaker.io/) and we are in the process of upgrading  Spring and Springboot versions. But with the yaml file size limitation introduced in [snakeyaml-1.32](https://bitbucket.org/snakeyaml/snakeyaml/src/49e794037c6be07053ce930f71f9c31b09180920/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-26) we can't upgrade to Springboot 3.0.x as it uses [snakeyaml-1.33 ](https://github.com/spring-projects/spring-boot/blob/3.0.x/spring-boot-project/spring-boot-dependencies/build.gradle#L1326) and we have many users with configuration files > 5MB size. The default file size limit of 3MB in snakeyaml can be [overriden](https://bitbucket.org/snakeyaml/snakeyaml/src/49e794037c6be07053ce930f71f9c31b09180920/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-146:148) but Springboot uses the [default LoaderOptions ](https://github.com/spring-projects/spring-boot/blob/v2.7.10/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/OriginTrackedYamlLoader.java#L70-L75) with no configurable value to override LoaderOptions.codePointLimit. 

We are looking for a configurable option to set the yaml file size limit within Springboot.

**Comment by kirangodishala** [comment]
@wilkinsona I would like to work on the PR. Can you give some pointers on how to make use of custom configuration in this scenario?

**Comment by scottfrederick** [comment]
@kirangodishala The issue is currently tagged with `team-meeting`, which indicates that we'd like some time to discuss this issue before we make any decisions about what to do. We'll update the status again and add another comment after we've had time to discuss it.
