### ISSUE TITLE
Duplicate bean definition for ServerProperties when using Spring Session in a hierarchical context

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3476]
`ServerProperties` is created by `ServerPropertiesAutoConfiguration` and by `SessionAutoConfiguration`, but with different bean names and different conditions, so it can be the case that they both contribute a bean and an `@Autowired` elsewehere fails.

**Comment by fawzyj** [comment]
Is there a work around? i am trying to port my boot 1.2.5 to 1.3, this bug blocking me as the server does not even start

**Comment by dsyer** [comment]
This issue is closed so it should be fixed in snapshots. The build has been broken do you might have to install locally to get it working.

**Comment by fawzyj** [comment]
ok, I switched to BUILD-SNAPSHOT, it is fixed there. thanks
