### ISSUE TITLE
spring-boot-maven-plugin - renaming artifact with finalName fails

### ISSUE THREAD

**Issue by lhanson** [spring-projects/spring-boot#3477]
Using the spring-boot-maven plugin (`org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE`), I'm trying to change the name of the repackaged final artifact like so:

                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <finalName>bar</finalName>
                        </configuration>
                    </execution>
                </executions>

When running `mvn package`, however, execution fails:

    [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage (default) on project foo: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage failed: For artifact mvn pa{foo:foo:1.0.0-SNAPSHOT:jar}: An attached artifact must have a different ID than its corresponding main artifact. -> [Help 1]

It does seem as though the artifacts are being created as `target/` contains both `bar.jar` and `foo-1.0.0-SNAPSHOT.jar`, but the build fails with an error:

    [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage (default) on project foo: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage failed: For artifact {foo:foo:1.0.0-SNAPSHOT:jar}: An attached artifact must have a different ID than its corresponding main artifact. -> [Help 1]

`mvn package -X` output: https://gist.github.com/lhanson/d7963a2e8976e3c84de1

**Comment by snicoll** [comment]
This is actually another issue I wasn't aware when I fixed #3177 - I can confirm that the exception is gone with `1.3.0.M2`. Please try and reopen if you disagree. Thanks for the sample project, super useful!

**Comment by lhanson** [comment]
Confirmed, works for me in `1.3.0.M2`. Thanks!
