### ISSUE TITLE
Provide service connection support for Hazelcast

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#34778]
Suggested by @eddumelendez in https://github.com/spring-projects/spring-boot/issues/34760, it would be interesting to have service connection support for Hazelcast. Unlike other services, our auto-configuration for Hazelcast leans very heavily on separate configuration files. Specifically, there's no property that's used to provide the address of a Hazelcast instance, instead this is determined from the Hazelcast configuration file. Given this arrangement, there isn't such an obvious mapping of existing properties into connection details.

**Comment by wilkinsona** [comment]
We might be able to add `HazelcastConnectionDetails` that exposes a `ClientConfig`. With some changes to the auto-configuration we could then use the `ClientConfig` from `HazelcastConnectionDetails` in favor of any user-provided `ClientConfig` bean.

**Comment by philwebb** [comment]
Closing in favor of PR #42416. Thanks @nosan!
