### ISSUE TITLE
Deprecate DelegatingApplicationContextInitializer  and DelegatingApplicationListener in favour of registering each delegate programatically or in spring.factories

### ISSUE THREAD

**Issue by kaleev** [spring-projects/spring-boot#34779]
`DelegatingApplicationContextInitializer` and `DelegatingApplicationListener` read `context.initializer.classes` and `context.listener.classes` properties to register `ApplicationContextInitializer` and `ApplicationListener`. `additional-spring-configuration-metadata.json` should contain metadata for these properties in order to provide proper editor support for these properties in IDEs.
Spring Boot 3.0 still doesn't contain the metadata.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but I am not sure that those properties should be documented in the metadata as they have no effect unless you've configured your application to use `DelegatingApplicationContextInitializer` or `DelegatingApplicationListener`.

I'm wondering if we should deprecate those `Delegating…` classes. I'm not sure they offer much value and, unlike listing classes directly in `spring.factories`, they won't work in a native image without additional reflection hints.

**Comment by wilkinsona** [comment]
We discussed this today and decided to deprecate `DelegatingApplicationContextInitializer` and `DelegatingApplicationListener`.

**Comment by snicoll** [comment]
Forgot to close this as superseded by the PR #36251
