### ISSUE TITLE
Allow auto-configuring IdGenerator in OpenTelemetryAutoConfiguration

### ISSUE THREAD

**Issue by gnagy** [spring-projects/spring-boot#34787]
AWS XRay expects traceIds to be in a specific format. Otel SDK allows customizing id generation. Please consider extending `OpenTelemetryAutoConfiguration.otelSdkTracerProvider()` to support overriding this.

Something like:

```
// depends on io.opentelemetry.contrib:opentelemetry-aws-xray:1.23.0
SdkTracerProvider.builder().setIdGenerator(AwsXrayIdGenerator.getInstance())...
```

**Comment by vpavic** [comment]
I agree that this is a bit of a pain, as it requires users to provide a configuration with a custom `SdkTracerProvider` and also manually configure several other dependent components.

I've opened #35041 to consider some improvements here.

**Comment by quaff** [comment]
It's covered by https://github.com/spring-projects/spring-boot/pull/34945

**Comment by jonatan-ivanov** [comment]
Closing this in favor of (probably) https://github.com/spring-projects/spring-boot/pull/34945.

**Comment by gnagy** [comment]
Thanks @jonatan-ivanov , #34945 looks better 👍 

Do you mean X-Ray supporting standard headers as in not needing a custom ID generator, or standard header names?

If the former, AFAIK the reason for custom X-Ray id format is that they encode the timestamp in the trace ID so they can performantly drop too old data in a stateless way on ingress.

If the latter, their recommended approach is to process headers in the collector agent (aws-otel-collector), so no need to change apps for that.

**Comment by jonatan-ivanov** [comment]
Kind of both: supporting the w3c standard would mean both the format and the header name.

Unfortunately the agent approach has many issues but I don't see too high chance of AWS supporting the w3c standard.
