### ISSUE TITLE
MailSenderAutoConfiguration.MailSenderValidator is not enabled while MailSenderConfiguration is

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3478]
Environment: Spring Boot 1.3.0.M2

When I run my app with `--debug` option I see the following:

```
Positive matches:
-----------------

   MailSenderAutoConfiguration.MailSenderConfiguration
      - any match resulted in [member condition on org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration$MailSenderConfiguration$MailSenderCondition$HostProperty] matches and [member condition on org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration$MailSenderConfiguration$MailSenderCondition$JndiNameProperty : @ConditionalOnProperty missing required properties spring.mail.jndi-name ] non matches (MailSenderAutoConfiguration.MailSenderConfiguration.MailSenderCondition)
      - @ConditionalOnMissingBean (types: org.springframework.mail.MailSender; SearchStrategy: all) found no beans (OnBeanCondition)


Negative matches:
-----------------

   MailSenderAutoConfiguration.MailSenderValidator
      - @ConditionalOnSingleCandidate (types: org.springframework.mail.javamail.JavaMailSenderImpl; SearchStrategy: all) found no beans (OnBeanCondition)
```

`MailSenderValidator` wasn't activated because there was no `JavaMailSenderImpl` but it should be created by `MailSenderConfiguration` that was activated.

Is it a bug? I didn't create `JavaMailSenderImpl` because I expect that it will be created by Spring Boot.

**Comment by snicoll** [comment]
I must confess I wasn't 100% sure when I wrote this but all my tests show positive results. Maybe the condition is evaluated before the bean is actually created. I can see that you set a `spring.mail.host` property. I have a similar test that pass so a sample project would be nice.

**Comment by php-coder** [comment]
As a sample project you could use https://github.com/php-coder/mystamps (`mvn clean package && java -jar target/mystamps.war --debug`).

**Comment by snicoll** [comment]
Actually I take it back. I have no test where the `JavaMailSenderImpl` is created by Boot since there is no way for me to test it. That's what bothered me the most when I wrote this.

**Comment by snicoll** [comment]
Thanks for the report. If you could try against `1.3.0.BUILD-SNAPSHOT` that would be nice.
