### ISSUE TITLE
Add a property to disable Observations starting with a prefix

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-projects/spring-boot#34802]
It seems there is a good amount of users who are registering an ObservationPredicate in order to disable Observations for Spring Security, something like this:
```java
@Bean
ObservationPredicate noSpringSecurityObservations() {
    return (name, context) -> !name.startsWith("spring.security.");
}
```
I think this common use-case could be simplified by creating this bean and let the users to configure this using a single property.

**Comment by mhalbritter** [comment]
Hm. On a second thought, I wonder if `spring.security.observations.enabled=false` would be a better place.

**Comment by mhalbritter** [comment]
After some discussion, we're going to change the scope of this issue a bit. We add properties to disable observations starting with a prefix like the `PropertiesMeterFilter` already allows for metrics. Then we document that Spring Security observations can be disabled by setting `management.observations.enable.spring.security=false`.
