### ISSUE TITLE
"ContextRefresher" seems to have some room for optimization

### ISSUE THREAD

**Issue by bigdou666** [spring-projects/spring-boot#34824]
When we use Nacos to refresh the configuration.The ContextRefresher.refresh() method will be called through the RefreshEvent event.
![image](https://user-images.githubusercontent.com/44945800/229051824-4dc2f32f-d035-4a80-bede-f40071d67881.png)
The changes method obtains changed configuration items. Then binds the changed configuration items and context to EnvironmentChangeEvent and sends EnvironmentChangeEvent events.
![image](https://user-images.githubusercontent.com/44945800/229052504-0df9c760-c7ea-4e41-8330-59ae3aac16d4.png)
![image](https://user-images.githubusercontent.com/44945800/229052743-04856253-f1ee-4286-8db9-24af37b7a111.png)
ConfigurationPropertiesRebinder.onApplicationEvent(EnvironmentChangeEvent event) listens to environment change events, but does not judge the changed configuration items, so all @ConfigurationProperties Beans will be refreshed.
May I ask why there is no judgment to change the configuration items (keys) here?
**spring-cloud-context version is 2.2.9.RELEASE**

**Comment by scottfrederick** [comment]
`ContextRefresher` is part of the [Spring Cloud Commons](https://github.com/spring-cloud/spring-cloud-commons) project, not Spring Boot. I would suggest asking this question on StackOverflow using the [`spring-cloud` tag](https://stackoverflow.com/questions/tagged/spring-cloud).
