### ISSUE TITLE
Documentation's "getting-started" page creates spring-boot application in default package

### ISSUE THREAD

**Issue by Rammerhead** [spring-projects/spring-boot#34827]
To be more specific, I'm referring to [Section 4.3 in the "Getting Started" page](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#getting-started.first-application.code) at docs.spring.io (which is currently making use of Spring 3.0.5. I have OpenJDK 17 and I build using Maven 3.9.1 on Linux Mint 20.3).

The code provided puts the class in the default package (as no other package gets created), and this ends up causing problems because of `@SpringBootApplication`. Ultimately, the application fails to start after executing `mvn spring-boot:run`.

The solution is to create a package in MyApplication.java. I would also recommend to move the file from  `src/main/java/MyApplication.java` to `src/main/java/com/example/myproject/MyApplication.java` to be more consistent with the tip provided in ["Developing with Spring Boot" documentation's "Structuring Your Code"](https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.structuring-your-code) section.

The changed code would finally look like this:
```java
package com.example.myproject;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@SpringBootApplication
public class MyApplication {

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }

}
```

**Comment by snicoll** [comment]
Superseded by #34838
