### ISSUE TITLE
same Trace ID is not propagated  in spring boot 3

### ISSUE THREAD

**Issue by pulsar509** [spring-projects/spring-boot#34821]
I have 2 spring boot 3 apps ; first spring boot app is calling second app, both the apps are generating trace id but it is not same.
I am using rest template to call api's.
 
<dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
  </dependency> 

2023-03-30 18:05:44,146 INFO 27964 --- [http-nio-8080-exec-1]  INFO [model-microservice, c8fbc38554bcbd8254196a78c8f787fa, 53aba1b9c1f23476]  com.sascia.modelmicroservice.controller.Controller.one(83) : Send API called

2023-03-30 18:05:44,050 INFO 22544 --- [http-nio-8081-exec-1]  INFO [microservice, aa8e748aa9d0ea493ace7f5c3a8571af, 5cff6acc1680a6ab]  com.sascia.modelmicroservice.controller.Controller.getTwo(92) : called 2
2023-03-30 18:05:44,160 INFO 22544 --- [http-nio-8081-exec-1]  INFO [microservice, aa8e748aa9d0ea493ace7f5c3a8571af, 5cff6acc1680a6ab]  com.sascia.modelmicroservice.controller.Controller.getTwo(104) : Reply = 0ne

**Comment by pulsar509** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.0</version>
        <relativePath/> 
    </parent>
    <groupId>com.siemens.sascia</groupId>
    <artifactId>model-microservice</artifactId>
    <version>${revision}</version>
    <name>model-microservice</name>
    <description>model-microservice</description>
    <properties>
        <java.version>17</java.version>
        <revision>0.0.5</revision>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by pulsar509** [comment]
Thanks for your response Scott. 
currently, I am facing this issue with resttemplate and Feign. Attached the code which uses rest template.

here is how I have initialized rest
    @Bean
    public RestTemplate getRestTemplate() {
        return new RestTemplate();
    }

the stackoverflow solution is not working for me it is showing me compile time error as "Could not autowire. No beans of 'RestTemplateBuilderConfigurer' type found. "

[model-microservice.zip](https://github.com/spring-projects/spring-boot/files/11118713/model-microservice.zip)

**Comment by maciejwalkowiak** [comment]
@pulsar509 I checked the project you attached, injecting `RestTemplateBuilderConfigurer` works as expected.

To have all the customizers applied on the RestTemplate, you should **not** create instances of RestTemplate with `new`, but rather use `RestTemplateBuilder`:

```

**Comment by pulsar509** [comment]
My problem is resolved with the above solution, thanks !

But I am still facing same issue while using Feign Client. Do not know what is going wrong.

**Comment by opticSquid** [comment]
how to configure rest client with the same configuration to maintain same trace id across applications
