### ISSUE TITLE
Document audience support in Oauth2 resource server

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#34848]
See https://github.com/spring-projects/spring-boot/pull/29084#issuecomment-1494958581

**Comment by bikash30851** [comment]
@snicoll  I want to work on it and do the documentation, in what page should the documentation go?

**Comment by bikash30851** [comment]
Perfect, I will start working on it.

**Comment by izeye** [comment]
This seems to have been resolved via https://github.com/spring-projects/spring-boot/pull/35286.

**Comment by wilkinsona** [comment]
Thanks, @izeye!
