### ISSUE TITLE
Stop using Native Build Tools "requiredVersion" configuration option

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#34840]
[GraalVM is being contributed to the OpenJDK codebase](https://www.graalvm.org/2022/openjdk-announcement/); as a result, its version string is about to change from its legacy independent versioning policy (`"23.0"`) to using the actual JDK version it's shipped with.

The `requiredVersion` option available in the [Native Build Tools plugin](https://github.com/graalvm/native-build-tools) will be deprecated and retired. This was useful for Spring projects initially, as Spring Boot 3 required GraalVM 22.3 as a baseline. This requirement is probably less of an issue as 22.2 is less popular these days.

Initially, the NBT plugin will change its behavior and will assume that JDK 20/JDK 21 is more recent than "22.3". I think we should [avoid using this option as of Spring Boot 3.1](https://github.com/spring-projects/spring-boot/blob/be014ca7e07c2aabf68ab1672e91500a583460c2/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/NativeImagePluginAction.java#L101).

**Comment by wilkinsona** [comment]
I've changed this to a task as, hopefully, users won't notice any change.

**Comment by snicoll** [comment]
FTR this has been "backported" to `3.0.x` as well as part of upgrading to NBT `0.9.21`.
