### ISSUE TITLE
Add properties to support device grant with Spring Authorization Server

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#34843]
- [ ] Add property `*.endpoint.device-authorization-uri` - maps to `AuthorizationServerSettings.getDeviceAuthorizationEndpoint()`
- [ ] Add property `*.endpoint.device-verification-uri` - maps to `AuthorizationServerSettings.getDeviceVerificationEndpoint()`
- [ ] Add property `*.token.device-code-time-to-live` - maps to `TokenSettings.getDeviceCodeTimeToLive()`
- [ ] Consider moving `OAuth2AuthorizationServerProperties` up one level to `*.oauth2.server` package to align with client and resource server auto-config

Related gh-34003

**Comment by snicoll** [comment]
@jgrandja would it be possible to rephrase that in a less generic fashion? We prefer an issue to be focused on one thing at a time and a non-generic issue title is one way to enforce that.

**Comment by mbhave** [comment]
I've update the title based on what I think is being requested. @jgrandja Feel free to update if that was not the intent of the issue.

**Comment by mbhave** [comment]
Regarding the package for `OAuth2AuthorizationServerProperties `, we decided to keep things in `servlet` until we have a `reactive` package. We can move out common functionality if reactive support is added.

**Comment by sjohnr** [comment]
@mbhave Can I take this one?

**Comment by mbhave** [comment]
@sjohnr It's all yours!

**Comment by wilkinsona** [comment]
Closing in favor of #34957. Thanks, @sjohnr!
