### ISSUE TITLE
PropertiesLauncher fails security scans.

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-boot#3488]
![01](https://cloud.githubusercontent.com/assets/2190106/8676590/1c288254-2a10-11e5-8e1c-9a2f63f06a4c.jpg)
![02](https://cloud.githubusercontent.com/assets/2190106/8676604/236b2c1a-2a10-11e5-9fb6-6d82771750e8.jpg)
![03](https://cloud.githubusercontent.com/assets/2190106/8676608/2669e280-2a10-11e5-814a-f3f079feb6bd.jpg)
![04](https://cloud.githubusercontent.com/assets/2190106/8676612/29d670c8-2a10-11e5-8c97-0430d8b062c6.jpg)

**Comment by dsyer** [comment]
Well that's interesting. Being able to control the classpath is kind of the point of this class though, so I don't really know what you expect to do with this information. What did you have in mind?

**Comment by marcuslange** [comment]
Let me talk with Veracode and see if they have a proposed solution. If so, we can work together to implement. How does that sound?

**Comment by dsyer** [comment]
It doesn't make a lot of sense, but I'm interested to see what you propose.

**Comment by marcuslange** [comment]
The issue really comes down to the fact that a lot of very large companies use Veracode and if failures like this surface, it makes it much harder for teams to adopt. I'm offering to help clear this case with you guys assuming it can be a team effort.

**Comment by dsyer** [comment]
Yes, but it's not really a problem that can be cleared up. If you use `PropertiesLauncher` you _intend_ to change the classpath at runtime based on user inputs. It's what it does. It's a feature in other words.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
