### ISSUE TITLE
Restore use of avg in JPA smoke test

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#34895]
While upgrading to Hibernate `6.2.0.Final`, the smoke test has been changed to avoid what seems to be a regression in Hibernate 6.2. I've raised https://hibernate.atlassian.net/browse/HHH-16445 and the smoke test should be updated according to the resolution of that issue.

**Comment by dreis2211** [comment]
Meh, this should have been fixed already with https://hibernate.atlassian.net/browse/HHH-15711 and was probably broken again in https://github.com/hibernate/hibernate-orm/commit/08de2ff104ea221a4ef4258a1204c30df4347e36

**Comment by mhalbritter** [comment]
FTR, this is the commit which changed the avg: f264e3c65ee36a6d0a8ef482599e009ee593d8f2

**Comment by wilkinsona** [comment]
I doesn't look like the regression's going to be fixed in Hibernate. There's a suggestion in the issue that we can use: casting to an integer.
