### ISSUE TITLE
Update tutorial, since `run` command from Spring v3.0 was removed

### ISSUE THREAD

**Issue by TryKatChup** [spring-projects/spring-boot#34899]
Spring version: v3.0.5

Since Spring Boot 3.0 the `run` command was removed (see https://github.com/spring-projects/spring-boot/issues/33482#issuecomment-1349992508). [This tutorial](https://spring.io/guides/gs/spring-boot/#scratch) should be updated as well, otherwise a beginner would have problems running the `app.groovy` file.

**Comment by scottfrederick** [comment]
@TryKatChup Thanks for letting us know. The tutorial page you linked to has a `Go To Repo` link at the top which will take you to a GitHub repo with its own issue tracker. Can you file this issue in that project instead?

**Comment by izeye** [comment]
I created https://github.com/spring-guides/gs-spring-boot/pull/155 to try to resolve it.

**Comment by wilkinsona** [comment]
Thanks very much, @izeye.
