### ISSUE TITLE
spring.cloud.config.databases latest version 4.0.1 still has spring.factories.

### ISSUE THREAD

**Issue by ilyasjaan** [spring-projects/spring-boot#34901]
Hello,

spring.cloud.config.databases is loaded with spring boot 3.0.5 as spring cloud version 2022.0.1 needs spring boot 3.0.5.

So seems like with this combination we cannot use database backend with vault anymore. As nothing is started to create creds for database as such.

We need to fix this library to be able to use with spring cloud version 2022.0.1. 

Thanks

**Comment by ilyasjaan** [comment]
According to https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes. spring.factories not supported anymore. So this breaks the use of new spring cloud version with spring.cloud.config.databases

**Comment by snicoll** [comment]
I don't know what `spring.cloud.config.databases` is but Spring Boot doesn't handle that at all so that's the wrong place to report it. You should be able to figure out which library is impacted and report the problem there.
