### ISSUE TITLE
ActiveMQConnectionFactoryFactory does not allow for use of SSL transport 

### ISSUE THREAD

**Issue by bagerman** [spring-projects/spring-boot#3496]
It looks like ActiveMQConnectionFactoryFactory only handles tcp or vm type of transport. The queue broker I need to connect to is using SSL. Is there a workaround to setup SSL transport that uses ActiveMQSslConnectionFactory?
Thanks
Alex

**Comment by snicoll** [comment]
You mean except defining it yourself? No. What you could do is configure the factory and then share the code and we could integrate that in auto-config maybe?

**Comment by bagerman** [comment]
thanks
