### ISSUE TITLE
Upgrade to Spring Data HATEOAS 2.1.0-RC1

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#34965]

**Comment by snicoll** [comment]
Duplicates #34985

**Comment by wilkinsona** [comment]
Just FYI, Bomr missed this issue and opened #34985 as the title didn't match what it expected. It [looks for an existing issue with a title that starts with "Upgrade to ${library.name}"](https://github.com/spring-projects/spring-boot/blob/148c632299f408a50ba506b1ec79a9938730d3b6/buildSrc/src/main/java/org/springframework/boot/build/bom/bomr/UpgradeDependencies.java#L188-L198). In this case it was looking for "Upgrade to Spring HATEOAS".
