### ISSUE TITLE
Improve documentation for baggage propagation into MDC

### ISSUE THREAD

**Issue by szpak** [spring-projects/spring-boot#34977]
Thanks to @marcingrzejszczak  and https://github.com/spring-projects/spring-boot/pull/32480, a standard OpenTelemetry "baggage content" is automatically propagated by default (with just `micrometer-tracing-bridge-otel` added). However, to have it accessible via (logging) MDC, it is required to add some extra configuration (only `spanId` and `traceId` are propagated to MDC automatically):

```
management:
  tracing:
    baggage:
      correlation:
        fields:
          - baggage
      remote-fields:
        - baggage
```

It might be confusing, as one might expect to have the correlation and remote-fields available for non-default fields (while "baggage" seems to be - proposed - standard - https://www.w3.org/TR/baggage/#header-name).

If the "baggage" is enabled in tracing and if anything is provided inside why not put it also into MDC (to be clear - just to be accessible with custom custom logging pattern from MDC)?

Things to consider:
 - performance - could it be a problem? It is already passed by internally, only injecting it into MDC is to be added
 - ability to disable "baggage" field propagation - by adding some other fields or by setting the empty value/list in those 2 places in configuration?
 - backward compatibility - maybe there could be just a switch to turn the bahavior on (disabled by default for now), and eventually it would be enabled by default in some 3.x or maybe 4.0?

**Comment by marcingrzejszczak** [comment]
Hey Marcin :)

With OTel support we have 2 ways of supporting baggage. One, where baggage key == header (https://github.com/micrometer-metrics/tracing/blob/v1.0.4/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/propagation/BaggageTextMapPropagator.java) and the other where all the baggage entries are there in the `baggage` key as mentioned in the standard (via `W3cBaggagePropagator` https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/OpenTelemetryAutoConfiguration.java#L199).

> If the "baggage" is enabled in tracing and if anything is provided inside why not put it also into MDC (to be clear - just to be accessible with custom custom logging pattern from MDC)?

That's exactly how this should be working - https://github.com/micrometer-metrics/tracing/blob/v1.0.4/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/Slf4JBaggageEventListener.java . We take all the baggage from all possible places (as mentioned above) and then we put it into MDC. Do you observe sth else?

**Comment by marcingrzejszczak** [comment]
Ok i guess we need to improve the docs with better examples. Brave requires to be explicit about these entries so we've decided to go with the same approach with otel
