### ISSUE TITLE
Docker-compose working directory is null

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#34992]
I think this is a simple typo in `DockerComposeFile`:

```java
		File base = (workingDirectory != null) ? workingDirectory : new File(".");
		if (!base.exists()) {
			return null;
		}
		Assert.isTrue(base.isDirectory(), () -> "'%s' is not a directory".formatted(base));
		Path basePath = workingDirectory.toPath();
```

where `workingDirectory` can be null (in fact it is the default) so there is an NPE. Fix it by replacing `workingDirectory` by `base`?

**Comment by philwebb** [comment]
Thanks Dave. I'll fix this one before merging.
