### ISSUE TITLE
Document @DataR2dbcTest support

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#35014]
Most of the test slices have been documented, however `@DataR2dbcTest` seems to be missing from the list of documented `@Data*Test` annotations. As test support for reactive is different from the other slices it would be nice that this could be added, including on how to configure the datastore etc.

**Comment by bikash30851** [comment]
@mdeinum I can work on it. What page should the documentation go on?

**Comment by wilkinsona** [comment]
Thanks for the offer, @bikash30851. Let's finish https://github.com/spring-projects/spring-boot/pull/35286 first please.
