### ISSUE TITLE
Document that properties that change an application's beans are fixed at build time

### ISSUE THREAD

**Issue by derkoe** [spring-projects/spring-boot#35032]
When running a native-built Spring Boot application on Kubernetes the `liveness` and `readiness` probes are not active (they both return a 404).

How to reproduce:
1. Go to [start.spring.io and select Web, Actuator and GraalVM Native](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.0.5&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native,web,actuator)
2. Build a native image of your application (`mvn spring-boot:build-image -Pnative`)
3. Launch the application in Kubernetes (or set the appropriate environment when running locally `docker run -it --rm  -e KUBERNETES_SERVICE_HOST=localhost -e KUBERNETES_SERVICE_PORT=8080 -p 8080:8080 docker.io/library/demo:0.0.1-SNAPSHOT`)
4. Open [`http://localhost:8080/actuator/health/liveness`](http://localhost:8080/actuator/health/liveness)

Expected result - HTTP 200 with body `{"status":"UP"}`, actual result HTTP 404.

**Comment by derkoe** [comment]
@snicoll adding `management.endpoint.health.probes.enabled=true` works.

**Comment by derkoe** [comment]
> I think we could improve the docs a bit here.

@wilkinsona I think it would be better for Spring users that these kind of features would work with native-image. 
Another option would to document list of things that do not work or a list of things that are tested to be working. Both is not easy to do.

**Comment by wilkinsona** [comment]
> I think it would be better for Spring users that these kind of features would work with native-image

Unfortunately, that's not easy due to Graal's closed-world assumptions. Furthermore, it would increase native image compile time and memory footprint. There's some more discussion related to this topic in https://github.com/spring-projects/spring-framework/issues/29844. It's talking about profiles but configuration properties are largely the same problem.

> Another option would to document list of things that do not work or a list of things that are tested to be working. Both is not easy to do

This issue will take a step in this direction.

**Comment by wilkinsona** [comment]
I think it would be good to duplicate it or move it up into https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/native-image.html#native-image.introducing-graalvm-native-images.key-differences-with-jvm-deployments from its current position in https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing.

**Comment by mhalbritter** [comment]
Ah yeah. I read the part under "Key Differences with JVM Deployments" as a general introduction to Native Image (not related to Spring Boot per se) and the "Understanding Spring Ahead-of-Time Processing" about more limitations when using Spring in a native image.

**Comment by wilkinsona** [comment]
Yeah, there is that separation at the moment and my original suggestion would blur that. Perhaps the first list should just have a bullet that links or at least point people to the second. I think it's too easy at the moment to read the first list and think that's it in terms of limitations.
