### ISSUE TITLE
Wrong interface name on the Spring-Boot-3.0-Migration-Guide wiki page

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-boot#35045]
In the [Spring-Boot-3.0-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#tag-providers-and-contributors-migration) in the chapter about `ServerRequestObservationConvention` the second example class `CustomServerRequestObservationConvention` incorrectly implements `ServerRequestObservationContext` while it should implement `ServerRequestObservationConvention`.

**Comment by wilkinsona** [comment]
Thanks for spotting this. This wiki has been updated.
