### ISSUE TITLE
JacksonObjectMapperBuilderConfiguration: configure TimeZone other than UTC

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#3505]
Jackson uses UTC timezone by default. Although `Jackson2ObjectMapperBuilder` exposes a way to set another timezone, this feature is not exposed by the `JacksonObjectMapperBuilderConfiguration`.

The only solution I found so far is to create my own `DateFormat` class (extension of Jackson's `StdDateFormat` where the TZ is set to whatever I need) then refer to that class in `spring.jackson.dateformat=<class name>`.

Wouldn't be easier to define an extra config property like `spring.jackson.timezone` and use its value to configure the ``accordingly ?

**Comment by brenuart** [comment]
The same is true for JodaTime serialisation (worst actually since there is apparently no way to overwrite the default autoconfig provided by SpringBoot). 

@wilkinsona Would a PR help for this issue?

**Comment by wilkinsona** [comment]
AFAICT, JodaTime serialisation uses the same time zone setting. Does that not match what you have seen?

**Comment by wilkinsona** [comment]
And thank you for the offer of a PR, but I've just about implemented this already

**Comment by brenuart** [comment]
They both use UTC by default, but neither allow the user to specify another TZ.

Jackson supports `java.util.Date` natively, so in this case the easiest seems to directly set `objectMapper.setTimeZone()` to a user configured value.

Joda support comes through the registration of additional Jackson serializers (see `JodaDateTimeJacksonConfiguration`) where the TZ to use is explicitly set (hardcoded).

**Comment by wilkinsona** [comment]
> Joda support comes through the registration of an additional Jackson serializer (see JodaDateTimeJacksonConfiguration) where the TZ to use is explicitly set (hardcoded).

The hardcoded value is only the default. It's set to UTC to match Jackson's default for `java.util.Date`. Settings the time zone on the `ObjectMapper` is sufficient for both `Date` and `DateTime` instances to be serialised correctly.

**Comment by brenuart** [comment]
That was a quick reaction! What a service! Thanks.

**Comment by tunix** [comment]
Hi! Does this cover ZonedDateTime instances as well? I've tried setting `spring.jackson.time-zone` and using timezone() method of Jackson2ObjectMapperBuilder but it always get serialized in UTC.

**Comment by philwebb** [comment]
@tunix I think it should, see [this line of code](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L174) in the auto-configuration class. If you're seeing problems could you please open a new issue and provide a [sample application that demonstrates the problem](https://github.com/spring-projects/spring-boot-issues).
