### ISSUE TITLE
Many spring.security.oauth2.authorizationserver properties do not have default values

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#35066]

**Comment by sjohnr** [comment]
@wilkinsona I can take this one.

Note that properties in `spring.security.oauth2.authorizationserver.client.<registration-id>.*` cannot be defaulted.

**Comment by wilkinsona** [comment]
Thanks, @sjohnr. It's all yours.

**Comment by philwebb** [comment]
Closing in favor of PR #35460
