### ISSUE TITLE
Samples using Spring-Boot + Hiraki CP

### ISSUE THREAD

**Issue by rogelio-blanco** [spring-projects/spring-boot#3506]
Hi all,

There are any samples where I can see how to setup Hiraki CP into Spring Boot app?

Regards,

**Comment by philwebb** [comment]
We don't have one in our repo but it should just be a case of making sure you have `com.zaxxer.hikari.HikariDataSource` on your classpath and you don't have `org.apache.tomcat.jdbc.pool.DataSource`. If you've got a specific problem I suggest asking on stackoverflow.com.
