### ISSUE TITLE
Error: ] Some problems were encountered while processing the POMs: [FATAL] Non-resolvable parent POM for  project-test Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.2.2.RELEASE from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.2.2.RELEASE/spring-boot-starter-parent-2.2.2.RELEASE.pom and 'parent.relativePath' points at wrong local POM @ line 11, column 13

### ISSUE THREAD

**Issue by SheetalSharma14** [spring-projects/spring-boot#35083]
I'm facing this error while the git action is executing

mvn package spring-boot:repackage
  shell: /usr/bin/bash -e {0}
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: project-test
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.19-7/x6[4](https://github.com/brandvas/public-web/actions/runs/4748976486/jobs/8436450470#step:4:4)

**Comment by philwebb** [comment]
This is a DNS issue with Maven central and out of our control. See https://twitter.com/olamy/status/1648860280859000832 for a workaround.
