### ISSUE TITLE
Add subject alt to JKS store and re-enable OkHttp SSL tests 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#35106]
See commit 77c468c95674e99fe423ca2a8195945140c27957. We need to add a subject alt to the `test.jks` file in order to enable those tests.

**Comment by mhalbritter** [comment]
I've used the [KeyStoreExplorer](https://keystore-explorer.org/) to generate a new key and a matching certificate, this time with an SubjectAltName and re-enabled the tests.

Interestingly the old certificate was expired. The new one is valid for 100 years, i've created an entry in my calendar to renew it ;)

**Comment by mhalbritter** [comment]
I've updated the [wiki page](https://github.com/spring-projects/spring-boot/wiki/Generating-SSL-KeyStores) with all needed instructions.
