### ISSUE TITLE
Upgrade to Jackson version 2.15

### ISSUE THREAD

**Issue by hongji3354** [spring-projects/spring-boot#35108]
The current version of jackson, 2.14.2, in use on Spring Boot 3-pointers is experiencing a bug where deserialization using @JsonNaming in a record results in an error. This issue has been fixed in jackson Version 2.15.0. - For more information, please visit: https://github.com/FasterXML/jackson-databind/issues/3846

How about raising the jackson Dependency Version of Spring Boot 3.0 to 2.15?

**Comment by wilkinsona** [comment]
We've already upgrade to 2.15 in 3.1. We won't upgrade to 2.15 in 3.0.x as we generally [do not upgrade to new minors in maintenance releases](https://github.com/spring-projects/spring-boot/wiki/Team-Practices#third-party-dependency-upgrades).
