### ISSUE TITLE
Enhancement: Concurrentreferencehashmap implementation, using segment lock instead of CAS

### ISSUE THREAD

**Issue by lan-dian** [spring-projects/spring-boot#35156]
The spring version is 2.3.7
I use this class, as the cache layer, we have very little data, but read and write frequently, data is acceptable to lose, so I use this class, but I find that this class still uses JDK 1.7's fragmentation lock implementation scheme, not 1.8's CAS implementation scheme.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. `ConcurrentReferenceHashMap` is part of [Spring Framework](https://github.com/spring-projects/spring-framework).
