### ISSUE TITLE
Spring-boot 3.0.6 Maven Debug issue

### ISSUE THREAD

**Issue by voodemsanthosh** [spring-projects/spring-boot#35187]
Project migrated to spring boot 3.0.6. Now it is not able to debug by `-Dspring-boot.run.fork=false` in spring boot maven command from IntelliJ

Affects: Spring boot 3.0.6
Java: corretto17
IntelliJ: IntelliJ IDEA 2023.1 (Community Edition)

Issue: Project able to start in debug mode but debug points are not stopping controller.

Impacting developer cost to debug.

**Comment by voodemsanthosh** [comment]
I found work around from here

https://docs.spring.io/spring-boot/docs/3.0.6/maven-plugin/reference/htmlsingle/#run.examples

is there a way to solve problem by like old approach ?

**Comment by wilkinsona** [comment]
Support for running the application in the same JVM as Maven was deprecated in 2.x and removed in 3.0. The docs that you have found are not a workaround, they are the recommended way to debug an application when running it using `spring-boot:run`.

**Comment by voodemsanthosh** [comment]
Thank you @wilkinsona. This helps.
