### ISSUE TITLE
FATAL log level is mapped to ERROR even for log systems that supports it.

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#3518]
Log4j and Log4j2 have FATAL log level, SpringBoots `LogLevel` defines a FATAL too but it is map to ERROR.
Is this by design or a bug?
Also the documentation mentions FATAL, but in [this section](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-logging-format) it is skipped

**Comment by snicoll** [comment]
Looks like a glitch indeed. Looking into it.
