### ISSUE TITLE
Wrong PID_FOLDER default value in documentation

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3520]
In [Installation as a init.d service (System V)](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-service.html#_installation_as_a_init_d_service_system_v) chapter:

>Tracks application PIDs using /var/run/\<appname>/\<appname>.pid

but in the chapter [Customizing the startup script](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-service.html#_customizing_the_startup_script):

>PID_FOLDER The root name of the pid folder (/var/run by default).

As we can see there `PID_FOLDER` has wrong default value (`/var/run` instead of `/var/run/<appname>`)

**Comment by philwebb** [comment]
I think the documentation is actually correct there. The `PID_FOLDER` in the config is the root location, the `<appname>` part is added by the script.

See https://github.com/spring-projects/spring-boot/blob/v1.3.0.M2/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L47
