### ISSUE TITLE
Enhancement spring-boot-starter-oauth2-client Using Non Session InMemory Implementation

### ISSUE THREAD

**Issue by BingChunMoLi** [spring-projects/spring-boot#35211]
Enhancement ：
if http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
AutoConfiguration Not working very well because request.getSession() is always null

**Comment by wilkinsona** [comment]
That Spring Security code is calling `request.getSession(false)` so it's to be expected that `null` is returned if nothing else has caused a session to be created. Spring Security is managed as a [separate project](/spring-projects/spring-security). If you believe its behavior could be improved somehow, please open a Spring Security issue.
