### ISSUE TITLE
Provide an example of .conf file

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3522]
Quote from [documentation](http://docs.spring.io/spring-boot/docs/1.3.0.M2/reference/html/deployment-install.html):

>With the exception of JARFILE and APP_NAME, the above settings can be placed in a .conf next to the jar. For example the jar /var/myapp/myapp.jar would attempt to source the configuration file /var/myapp/myapp.conf.

Please, provide an example of such file. Specifically, there may be example of passing options to JVM (by setting `JAVA_OPTS` variable), using `RUN_ARGS` and activating profile.

**Comment by kmila** [comment]
+1

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L112

It'd be nice if this **.conf** also included options to act as an "application.properties" (or provided a shorthand entry to specify `-spring.config.location`).

**Comment by spencergibb** [comment]
@kmila it's a place to put env vars or anything that can run as a shell script.
