### ISSUE TITLE
ClassNotFoundException :org.springframework.beans.factory.aot.BeanRegistrationExcludeFilter

### ISSUE THREAD

**Issue by nagaraju1692** [spring-projects/spring-boot#35232]
As per the my project requirement , i am going to migration spring boot application from springboot 2.7.6 to 3.0.0 version.

I have modified the below changes.

1) Changed the java version from java 11 to 17.
2) i have modifed the spring boot starter parent version from 2.7.6 to 3.0.0 version

I am able to build the application  ,While starting the server getting the issue as below.

**Error : Caused by: java.lang.ClassNotFoundException : org.springframework.beans.factory.aot.BeanRegistrationExcludeFilter**

**Comment by nagaraju1692** [comment]
Please let me know, If need any more details on this.

**Comment by wilkinsona** [comment]
`org.springframework.beans.factory.aot.BeanRegistrationExcludeFilter` is a new interface that was introduced in Spring Framework 6. I suspect that your Spring Boot upgrade is incomplete and some or all of your Spring Framework dependencies are still using 5.3.x.

If this isn't the case, all of your Spring Framework dependencies are using 6.0.x, and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem and we can re-open the issue. You can share a sample with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.
