### ISSUE TITLE
Consider carefully upgrade to Tomcat 8.0.26

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3526]
http://info.michael-simons.eu/2015/07/15/upgrading-to-tomcat-8-0-24/

**Comment by wilkinsona** [comment]
It'd be nice to pick up 8.0.25 (assuming it's out in time) as it contains the fix for #3406

**Comment by yaelma** [comment]
What is the fix for this one? 
I've already using spring-boot-starter-tomcat in a version that contains Tomcat 8.0.26  and still cannot retrieve the version ..

**Comment by snicoll** [comment]
There is a milestone info on the right that states `1.2.6` (quite old, that was released last August!).

> still cannot retrieve the version

I am guessing you're referring to #3406. If that's the case and you feel that you've found a bug in Spring Boot, please raise a new issue.
