### ISSUE TITLE
SpringBoot runnable JAR file, JAVA_OPTS `-Dkey=value`  |   Value does not allow spaces ?

### ISSUE THREAD

**Issue by github-edu** [spring-projects/spring-boot#35289]
# BUG / Enhancement

## Source file
spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script

## Source reference

```bash
arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar "$jarfile" $RUN_ARGS "$@")
```

## Branch
All branches

## Problem

`-Dkey=value`  

 Value does not allow spaces ?

## Resolve

Use an additional array variable ( e.g.  X_JAVA_OPTS ) to join with `arguments` 

This way, the value can be allowed to contain spaces.

-----
Thanks

**Comment by github-edu** [comment]
`arguments`  array elements  allow spaces

**Comment by github-edu** [comment]
```bash
arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS )
[ -n "$EXT_JAVA_OPTS" ] && arguments=( ${arguments[@]} ${EXT_JAVA_OPTS[@]} )
arguments=( ${arguments[@]} -jar "$jarfile" $RUN_ARGS "$@" )
```

or 

```bash
if [ -n "$EXT_JAVA_OPTS" ]; then
  arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS ${EXT_JAVA_OPTS[@]} -jar "$jarfile" $RUN_ARGS "$@")
else
 arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS  -jar "$jarfile" $RUN_ARGS "$@")
fi
```

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, handling of spaces in the launch scripts isn't as good as we'd like, but we've yet to identify a way to fix it that's backwards compatible and that we're happy with. Please see https://github.com/spring-projects/spring-boot/issues/19716 and https://github.com/spring-projects/spring-boot/issues/18540 for details. Until those issues are addressed, please use a custom launch script that meets your specific needs.

**Comment by github-edu** [comment]
Thank you so much !
