### ISSUE TITLE
Devtools don't work with bootTestRun

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#35323]
I've added devtools to my application, and added a `@TestConfiguration` in `src/test/java`. I executed `gradle bootTestRun` and the application starts up and picks up the test configuration and starts the testcontainer bean contained in it. When I change something in `src/main/java` and run `gradle classes`, the still running `bootTestRun` does not pick those changes up. This workflow works when using `gradle bootRun`.

**Comment by wilkinsona** [comment]
How have you configured your project's dependencies? If DevTools is declared as a `developmentOnly` dependency, it won't be on the classpath.  `bootTestRun` uses the test runtime classpath at the moment which does not include `developmentOnly`.

**Comment by mhalbritter** [comment]
Works with `implementation`. Thanks!
