### ISSUE TITLE
server.session-timeout is declared twice in the meta-data

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3537]
Commit 3588ca8637ebf429223333add3815f408250de5a (#3240) added an extra entry in the meta-data and has left the property in the code. As a result, we have two entries in `server.session-timeout`. 

Besides, we could use `@Value` on the new property to initialize it with the value of the former value, when set.

**Comment by snicoll** [comment]
My mistake, the value is already initialized via that setter. Since nobody is using it we can remove the getter and that will remove the duplicate from the meta-data as well.

**Comment by philwebb** [comment]
Not sure we should delete that method without first deprecating it in a release. It's a method that someone could be calling themselves (even if we don't).

**Comment by philwebb** [comment]
@snicoll Is there any other way to fix this?

**Comment by snicoll** [comment]
I don't think so. You should get away with it by removing the custom meta-data. 

If you agree to make the meta-data processor less dumb, I am more than happy to implement the merge feature.

**Comment by philwebb** [comment]
I guess merge might make sense, it's probably the only sensible way to add deprecated blocks.
