### ISSUE TITLE
Relaxed binding does not work properly for nested properties

### ISSUE THREAD

**Issue by altery** [spring-projects/spring-boot#3539]
Relaxed configuration property binding only seems to work for nested properties if the property name is already available, for example in an application.properties.

FoobarProperties.java
```
@ConfigurationProperties(prefix= "services.foobar")
@Component
public class FoobarProperties {

	private boolean mock= true;

	private Nested nested;

	public boolean isMock () {
		return this.mock;
	}

	public void setMock (boolean mock) {
		this.mock= mock;
	}

	public Nested getNested() {
		return this.ip2location;
	}

	public void setNested(Nested nested) {
		this.nested= nested;
	}

	public static class Nested {

		private String magicValue;

		public String getMagicValue() {
			return this.magicValue;
		}

		public void setMagicValue(String magicValue) {
			this.magicValue= magicValue;
		}
	}
}
```
Do not configure the properties using a .properties file (application.properties or PropertySource)
Instead, configure the properties by setting the following environment variables:
```
SERVICES_FOOBAR_MOCK=false
SERVICES_FOOBAR_NESTED_MAGICVALUE=42
```
Observe that only the services.foobar.mock is property bound to the configuration class, the services.foobar.nested.magicValue is still undefined (the setter is not called).

It seems to work for the non-nested property, because PropertiesConfigurationFactory#getNames() infers complete property names for top-level properties, but not for nested properties.

Now additionally define the non-working property application.properties (without an actual value):
```
services.foobar.nested.magicValue=
```

The value of 42 is now correctly applied. It seems to work in the this case, because resolution of property values in PropertiesConfigurationFactory#getPropertyValues() honors relaxed binding and applies the value from the 'PropertyValue' instance read from the system environment to the 'PropertyValue' read from the application.properties file, which in turn successfully binds the the configuration bean.

I found this change, which might be related:
https://github.com/spring-projects/spring-boot/pull/2479

**Comment by dsyer** [comment]
Works for me. Did you try using a snapshot (assuming something changed)? If it doesn't work for you on master can you write a complete test case so we can see exactly what you mean? `ConfigurationPropertiesBindingPostProcessorTests` is probably a good place to copy paste something to get started.

**Comment by dsyer** [comment]
Added a test and it passes, so we assume another change fixed this if there was ever a problem.

**Comment by altery** [comment]
Sorry for the lack of feedback, I was in vacation. Thanks for the update, I'll try again with 1.3.0.
