### ISSUE TITLE
Spring-boot-docker-compose with Docker in Docker

### ISSUE THREAD

**Issue by jarivandam** [spring-projects/spring-boot#35405]
Whilst trying the new spring-boot-docker-compose module, I ran into an issue in the Gitlab pipeline. Previously I used testcontainers to spin up the container environment. This pipeline is setup with a Docker-in-Docker configuration, so docker runs as a separate service. In testcontainers it is possible to start the containers with `new DockerComposeContainer().withLocalCompose(false);` to run in the Gitlab pipeline.
Currently it’s not possible to configure spring-boot-docker-compose to use this external docker instance to run docker compose. Would it be possible to make the docker host configurable?

**Comment by wilkinsona** [comment]
Thanks for trying the new module.

Spring Boot's Docker Compose integration is intended as a development-time feature. As such, supporting it in a CI pipeline hasn't really been considered and is unlikely to be something that we will invest in I'm afraid. It may be possible to get it to work but your CI environment will have to have the `docker compose` CLI available.

If you're looking for support for container-based services for tests, Spring Boot's Testcontainers integration is likely to be a much better fit. There's also the option to use [Testcontainers at development time](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.testcontainers.at-development-time) if you wish.

**Comment by jarivandam** [comment]
Thanks for the quick response.  I will take a look at the Spring Boot Testcontainers integration and see if that would improve our current setup.
