### ISSUE TITLE
Add a testAndDevelopmentOnly Gradle configuration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#35436]
`@RestartScope` is useful when working with testcontainers but with gradle we usually recommend that devtools is added to the `developmentOnly` configuration. It looks like this means it isn't available for tests. 

We can add a new `testAndDevelopmentOnly` configuration similar to `JavaPluginAction.configureDevelopmentOnlyConfiguration` where `JavaPlugin.TEST_RUNTIME_CLASSPATH_CONFIGURATION_NAME` extends from `developmentOnly`?

**Comment by mhalbritter** [comment]
When we change this, we have to update [the documentation](https://docs.spring.io/spring-boot/docs/3.1.0-SNAPSHOT/reference/htmlsingle/#features.testing.testcontainers.at-development-time.devtools), too.

**Comment by wilkinsona** [comment]
Thanks, @candrews. I've opened https://github.com/spring-projects/spring-boot/issues/38571.
