### ISSUE TITLE
MyBatis auto-configuration feature request

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#3544]
This is a feature request. My visits here in China have led me to conclude there are some insanely HUGE websites standardized on Spring and - among other things - MyBatis. Could we provide an out-of-the-box experience that supports the [Spring MyBatis project](http://mybatis.github.io/spring/)? I'm happy to write it there's a place for it and we can wait a week :)

**Comment by snicoll** [comment]
Duplicates #3008

**Comment by snicoll** [comment]
You can cast your vote on #3008 :)
