### ISSUE TITLE
JMS Dead Letter Queue Config

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3552]
Dead Letter queue config would be a nice addition, queue name changes depends on the implementation I guess but at least enabling it easily through appl.properties or a bean would be nice.

**Comment by snicoll** [comment]
enabling what exactly? A _default_ DLQ or _the_ DLQ of a given queue? This is a broker configuration I am afraid so I don't really see what we could do for you there. Can you clarify please?

**Comment by gokhanoner** [comment]
sorry. I mean enabling the default DLQ. for example ActiveMQ automatically enables it but HorhetQ not, and most probably artemis-queue not as well. So regardless of the implementation, to enable default DLQ with a switch, and also parameters like # of attemps before moving message to DLQ ?

**Comment by snicoll** [comment]
This is something that is configured at the broker level, not in the application.

**Comment by graben** [comment]
@snicoll: You're right this should be configured at broker level. And Artemis is warning all time if not configured on embedded broker. IMHO it should be possible to configure addressSettings in spring-boot for embedded Artemis broker.

**Comment by snicoll** [comment]
@graben thanks for the feedback. As this issue is closed and what you're asking is somewhat different than the original request, could you please create a separate issue? Alternatively, a PR would be awesome if you have time. If you don't, please share a sample that exhibits that warning.
