### ISSUE TITLE
Explicitly setting management.context-path=/ causes controllers to be mapped with //

### ISSUE THREAD

**Issue by axelfontaine** [spring-projects/spring-boot#3553]
When explicitly setting management.context-path=/ (the default value) in application.properties, all management controllers are mapped with an extra slash.

Using Spring Boot 1.2.5

Example:
```2015-07-19 14:27:58.202  INFO 559 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[//info],methods=[GET]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()```

**Comment by snicoll** [comment]
Actually, the default value is the empty String but I see what you mean.

**Comment by axelfontaine** [comment]
Not according to the docs: http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

```
management.context-path= # default to '/'
```

**Comment by snicoll** [comment]
Well the doc is wrong, I just changed it.

**Comment by axelfontaine** [comment]
Why is / wrong? Seems perfectly reasonable to me, just like /management is? Or do you want to avoid leading-slashes altogether? If the answer no (keeping the leading slash), then the default should remain / and the current doc is correct.

**Comment by snicoll** [comment]
I am currently discussing the current code right now. That does seems weird for me as well but the default value is the empty string. Strictly speaking the doc _is_ wrong. I didn't say it was a good thing.

**Comment by axelfontaine** [comment]
All that is missing is probably a simple if statement
