### ISSUE TITLE
Server.error.include-* not working

### ISSUE THREAD

**Issue by isaachjk** [spring-projects/spring-boot#35563]
Spring Boot Version: `3.0.6` - Still happens on `3.0.7`.

It was working on Spring Boot `2.7.X`.

In `application.properties`, I have this setting, since migration to 3.0.4, there is no way for this setting to work, I searched and can't find documentation about this.

```properties
server.error.include-message = ALWAYS
server.error.include-binding-errors = ALWAYS
server.error.include-stacktrace = ALWAYS
server.error.include-exception = TRUE
```

**Comment by philwebb** [comment]
Those properties are still supported. Please could you provide a sample application that shows the problem you're having?

**Comment by isaachjk** [comment]
> Those properties are still supported. Please could you provide a sample application that shows the problem you're having?

I made the demo that you asked me for, and in the demo it did work. the apologies of the case and thank you very much.

**Comment by michallichvar** [comment]
spring-boot-4.0.4, the same error:

Looks like the prefix should be spring.web.error
JavaBeanBinder.bind, propertyBinder.arg2 = "spring.web.error"

It all starts here ConfigurationPropertiesBinder.bind, where annotation.prefix is "spring.web".

```
    BindResult<?> bind(ConfigurationPropertiesBean propertiesBean) {
        Bindable<?> target = propertiesBean.asBindTarget();
        ConfigurationProperties annotation = propertiesBean.getAnnotation();
        BindHandler bindHandler = this.getBindHandler(target, annotation);
        return this.getBinder().bind(annotation.prefix(), target, bindHandler);
    }
```

I don't understand inner bindings of properties to beans etc, but it originates here. Maybe it's correct, and just the documentation should be changed.
However, using `spring.web.error.include-stacktrace=never` works for scenario, where I sent wrong GET throught Postman, then automatically redirected to /error (which is allowed in security), and the body of result in Postman does not contain (finally :)) trace.

EDIT: now I see, it was changed in 4.0.0, who knows why you had problems on 3.0.7: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Configuration-Changelog
