### ISSUE TITLE
management.context-path ignored when management.port is set

### ISSUE THREAD

**Issue by axelfontaine** [spring-projects/spring-boot#3556]
Using Spring Boot 1.2.5

Example:
```
management.port=9999
management.context-path=/xyz
```

will bring the management controllers up at 0.0.0.0:9999/ instead of 0.0.0.0:9999/xyz/

**Comment by dsyer** [comment]
There's a test that shows this is already working (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-actuator/src/test/java/sample/actuator/ManagementAddressActuatorApplicationTests.java#L69). I can't figure out yet why it works, or why @axelfontaine would have found it didn't work. Anyone know?

**Comment by dsyer** [comment]
Answer to first question (why it works) is here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointWebMvcManagementContextConfiguration.java#L91. What are you doing that is different? Not trying to access an endpoint?

**Comment by axelfontaine** [comment]
I have just ran some additional tests and was not able to reproduce the issue. I don't know what caused it at the time. Sincere apologies for the unnecessary trouble.

Axel

**Comment by dsyer** [comment]
No problem. Thanks for getting back to us.
