### ISSUE TITLE
Unnecessary/wrong Jersey 2 property config in JerseyAutoConfiguration

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#3557]
[Here](
https://github.com/spring-projects/spring-boot/blob/6100b3e85025ee39c644fa52cd9d24d3e07b2ebc/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jersey/JerseyAutoConfiguration.java#L215-L217) the Jersey `CommonProperties.METAINF_SERVICES_LOOKUP_DISABLE` property is set to 'true', but it seems that it has no effect. As far as I can tell, the `registration.addInitParameter` is for servlet/filter init parameters, whereas this property in question is supposed to be passed to Jerseys ResourceConfig.property method. As far as I know, Jersey doesn't read servlet/filter init params to influence its configuration, at least not for this property (it does it for package and classes, and the application class name).

A proof that this doesn't work is a Jersey 2 application with Jackson 2 in the classpath. By default, JSON serialization works fine and the jackson provider is correctly instantiated and used, and the resource returning a POJO works fine and the client gets the JSON representation. However, when this is done:

```java
@Bean
public ResourceConfig endpointConfig() {
    ResourceConfig config = new ResourceConfig();
    config.packages("com.test.rest");
    config.property(CommonProperties.METAINF_SERVICES_LOOKUP_DISABLE, "true");

    return config;
}
```

the reguest fails with:

```
2015-07-19 23:27:30.839 ERROR 50914 --- [  XNIO-2 task-1] o.g.j.m.i.WriterInterceptorExecutor      : MessageBodyWriter not found for media type=application/json, type=class com.test.rest.MyBean, genericType=class com.test.rest.MyBean.
```

So, the line which is linked to seems to be wrong and doesn't influence anything. Having it there is confusing as it kind of says Jersey's auto discovery is disabled explicitly, but that's not the case.

Suggested fix - remove the line.

**Comment by dsyer** [comment]
What about if we actually apply the `spring.jersey.init.*` properties to a bean of type `ResourceConfig` in our autoconfig? Would it actually break anything? Seems like it would expose more interesting stuff to Boot configuration properties.
