### ISSUE TITLE
Investigate HCON as a config format

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3558]
See https://github.com/typesafehub/config/blob/master/HOCON.md

Driven by this conversation https://twitter.com/antonarhipov/status/622860399453577217

**Comment by fkowal** [comment]
+1

**Comment by philwebb** [comment]
We already hit some problems supporting yaml and properties so I'd rather not add another one to the mix. It's possible to define your own `PropertySourceLoader` if you want to support a different format outside of Spring Boot.

**Comment by bluejaguar** [comment]
Phill, please provide a reference to Spring Cloud Config using a custom PropertySourceLoader.  This one here does not work with with Dalton.SR3 (that I can see from trying it) .   https://github.com/spring-projects/spring-boot/issues/4027#issuecomment-144649875
