### ISSUE TITLE
SpringBoot v3.1 breaking Jackson deserialisation of Record classes

### ISSUE THREAD

**Issue by lstoeferle** [spring-projects/spring-boot#35583]
The latest version of **spring-boot** `v3.1.0`, which comes with **jackson-bom** to `v2.15.0`, introduced a buggy version of **jackson-databind** that breaks the deserialisation  of Java Record classes. The issue has been fixed already in `v2.15.1` (see release notes [Jackson-Release-2.15.1](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.1)). 

I've added `v2.15.1` as an explicit dependency version, which resolved the issue in the meantime.

**Comment by mhalbritter** [comment]
Thanks for letting us know. This will be picked up automatically when we [upgrade dependencies](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies) in subsequent releases.
