### ISSUE TITLE
Spring3.x Migration Issue with WebServiceTemplate (HttpComponentsMessageSender support need for HttpClient 5)

### ISSUE THREAD

**Issue by amalajone** [spring-projects/spring-boot#35591]
WebServiceTemplate will be take the input of HttpComponentsMessageSender and HttpComponentsMessageSender will look for HttpClient , So for the Spring3.x migration its mandatory to support org.apache.hc.client5.http.classic.Httpclient for HttpComponentsMessageSender . IN the same project supporting for WebServiceTemplate and RestTemplate is not possible because of this issue . Please help to close this issue .

HttpComponentsMessageSender messageSender = new HttpComponentsMessageSender();
messageSender.setHttpClient(httpClient)

WebServiceTemplate webServiceTemplate = new WebServiceTemplate (marshaller);
webServiceTemplate .setMessageSender(messageSender )

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-ws/issues/1164. We'll pick up the new release of Spring Web Services that supports Http Client 5in due course.

**Comment by amalajone** [comment]
Is that fix done and released ?? I don't find the fix in spring ws core 4.0.2

**Comment by amalajone** [comment]
Even it's not there inside the latest version 4.0.4 . Can you please check and confirm , how to validate

**Comment by wilkinsona** [comment]
@amalajone As shown by the milestone assigned to the issue, the fix is in Spring Web Services 4.0.5 that has not yet been released.

**Comment by snigdhasasmal07** [comment]
is there any solutions available?

**Comment by wilkinsona** [comment]
Please don't make essentially the same comment on multiple issues. https://github.com/spring-projects/spring-ws/issues/1164 is the right place to comment if you must.

**Comment by DanyFuku** [comment]
Hi all. I want to ask you is this issue was fixed in the release version 4.0.10 because I have the same problem. Please can you send me an example with the solution for this ? Thank you in advance !

**Comment by bclozel** [comment]
@DanyFuku If you think there is a bug, please create a new issue in the spring-ws project with a sample application showing the problem. If you're looking for help, [you can ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/spring-ws).

**Comment by snigdhasasmal07** [comment]
@wilkinsona I just commented because I was not finding any solution for this. If you know the solution let me know . Is commenting a problem now

**Comment by halebki** [comment]
HttpComponentsMessageSender which version it is update
