### ISSUE TITLE
Docker compose auto configuration misleading

### ISSUE THREAD

**Issue by adamalexandru4** [spring-projects/spring-boot#35607]
I would like to start Keycloak and it's Postgres db when I start my Spring app but it doesn't have any JDBC connection (neither dependency added in pom.xml) but still tries to create a connection with Keycloak's Postgres instance which shouldn't be done automatically.
I read the docs but the only info was about `org.springframework.boot.ignore: true` which disables totally the startup of the container. 

In conclusion, how to start some containers and not binding them to the spring context (within any ConnectionDetails or RunningService) even if they looks familiar for known implementations of ConnectionDetails ? Maybe we should add a new label in order to make a difference between services which should be attached to Spring vs services which are additional for that Spring app but should also be started by docker-compose plugin.

**Comment by lombocska** [comment]
Hi there,

spring-boot-docker-compose didn't skip my pgadmin image, but pull it, create the container and start it actually.  I think there can be an issue.

Example:
- [pom.xml](https://github.com/lombocska/spring-boot-outbox-transactional-sample/blob/master/core-api/pom.xml#L56) with the exxtra spring-boot-docker-compose dependency
- [config file](https://github.com/lombocska/spring-boot-outbox-transactional-sample/blob/master/core-api/src/main/resources/application.yml#L20)
- [compose file](https://github.com/lombocska/spring-boot-outbox-transactional-sample/blob/master/docker/compose.yml)

Logs 
<img width="1573" alt="image" src="https://github.com/spring-projects/spring-boot/assets/19182100/13dacd8a-5bfa-4ee6-89cf-1693b35b34c6">

.....

<img width="1639" alt="image" src="https://github.com/spring-projects/spring-boot/assets/19182100/a7a38d52-4a88-40c3-8b32-7b5aee92f4b3">


Thanks for your answer in advance!

Moni

**Comment by scottfrederick** [comment]
@lombocska The `org.springframework.boot.ignore: true` label does not control whether an image is pulled and a container is started. Spring Boot doesn't have that level of control over what Docker Compose does when it's given a compose file. The label only tells Spring Boot not to attempt to create a service connection for that container. 

If you need to conditionally create containers from a compose file, you can use [Docker Compose profiles](https://docs.docker.com/compose/profiles/) and [select which profiles are activated](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.profiles) when Spring Boot starts Compose.
