### ISSUE TITLE
Update Git Commit ID Maven Plugin to 6.x to make it compatible with Maven 3.9.2

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-boot#35605]
Maven 3.9.2 complains about `git-commit-id-maven-plugin` 5.0.0

```
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0
[WARNING]   Declared at location(s):
[WARNING]    * com.example:demo:0.0.1-SNAPSHOT (pom.xml) @ line 38
[WARNING]   Used in module(s):
[WARNING]    * com.example:demo:0.0.1-SNAPSHOT (pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-aether-provider:3.1.0-alpha-1, org.apache.maven:maven-settings:3.1.0-alpha-1, org.apache.maven:maven-settings-builder:3.1.0-alpha-1, org.apache.maven:maven-core:3.1.0-alpha-1, org.apache.maven:maven-model-builder:3.1.0-alpha-1, org.apache.maven:maven-model:3.1.0-alpha-1, org.apache.maven:maven-artifact:3.1.0-alpha-1, org.apache.maven:maven-repository-metadata:3.1.0-alpha-1, org.apache.maven:maven-plugin-api:3.1.0-alpha-1]
[WARNING]
[WARNING]
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
```

See Maven 3.9.2 [Release Notes](https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features) - the part about "Plugin validation warnings change".

This issue is fixed by git-commit-id/git-commit-id-maven-plugin#615 that is unfortunately released only as part of a major release 6.0.0.

I'm not sure about Spring Boot policies regarding updating major plugins versions. Maybe the update to `git-commit-id-maven-plugin` 6.0.0 will be done as part of the automated dependency upgrading process. It would be good if it could be done earlier to get rid of these maven warnings.

Possible workaround at the moment is to override the plugin version in your `pom.xml`:
```
	<properties>
		<git-commit-id-maven-plugin.version>6.0.0</git-commit-id-maven-plugin.version>
	</properties>
```

**I'm not sure about all the consequences, however.** [Release Notes](https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v6.0.0) specifically mention that:
> ⚠️ This is a potentially breaking release. Read the release-notes carefully ⚠️

So, SB 3.1 is now probably stucked with 5.0.0. :(
Maybe someone could ask `git-commit-id-maven-plugin` maintainers to release 5.0.1 version with this fix.

**Comment by snicoll** [comment]
> Maybe someone could ask git-commit-id-maven-plugin maintainers to release 5.0.1 version with this fix.

Have you considered creating an issue asking for that. It might be that easy as I believe the fix is pretty simple. You could argue that the warning is annoying enough to warrant a backport.

**Comment by xak2000** [comment]
@snicoll Please check the answer from the author of the plugin: git-commit-id/git-commit-id-maven-plugin#630. Changes planned for 5.0.1 looks fine to me. But it's better if you'll look at them and say your word. :) The goal is to include 5.0.1 plugin in the next 3.1.x version of SB, I suppose.
