### ISSUE TITLE
Improve description of `build-image` and `build-image-no-fork`

### ISSUE THREAD

**Issue by ThomasKasene** [spring-projects/spring-boot#35608]
I feel that the [documentation](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals) for the `spring-boot-maven-plugin`'s `build-image` and `build-image-no-fork` could be more informative. Currently, they only talk about the difference between the two goals in terms of forking, but not what they _actually_ do and in which situations one might want to use them. The descriptions also seem to be more like JavaDoc than anything, as they're mentioning the different `*Mojo` class names, rather than the goal names.

**Comment by snicoll** [comment]
> Currently, they only talk about the difference between the two goals in terms of forking, but not what they actually do and in which situations one might want to use them.

What do you mean? Perhaps you can contribute a PR and we can take it from there?

**Comment by ThomasKasene** [comment]
Done 😃

**Comment by wilkinsona** [comment]
> The descriptions also seem to be more like JavaDoc than anything, as they're mentioning the different *Mojo class names, rather than the goal names.

Comparing the descriptions of [`spring-boot:build-image`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-build-image) and [`spring-boot:build-image-no-fork`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-build-image-no-fork) with those of the other goals, they do read very differently. I think we should try to align them.

>> Currently, they only talk about the difference between the two goals in terms of forking, but not what they actually do and >> in which situations one might want to use them.
> What do you mean? Perhaps you can contribute a PR and we can take it from there?

If @ThomasKasene can do it then great, but I'm not sure that we can expect a user to contribute a PR to document something that isn't well documented. It's a chicken and egg problem.

I think this overlaps a bit with the description reading like javadoc. For example:

> If you need to configure a mojo execution in your build, use BuildImageNoForkMojo instead.

I don't think "mojo" really belongs here. I think "goal" would be a better term. Similarly, I think `BuildImageNoForkMojo` could be replaced by `spring-boot:build-image`.

**Comment by wilkinsona** [comment]
It looks like this regressed in 3.0.x. The description of `spring-boot:build-image` is [better in 2.7.x](https://docs.spring.io/spring-boot/docs/2.7.x/maven-plugin/reference/htmlsingle/#goals).

**Comment by ThomasKasene** [comment]
> I don't think "mojo" really belongs here. I think "goal" would be a better term. Similarly, I think `BuildImageNoForkMojo` could be replaced by `spring-boot:build-image`.

In #35609 I've replaced "mojo" with "goal" like you suggested. As for the goal names, I've omitted the `spring-boot:` prefix as the other goal descriptions don't use it when referring to other goals (for example, the `spring-boot:start` description mentions the `run` goal).

**Comment by snicoll** [comment]
> I'm not sure that we can expect a user to contribute a PR to document something that isn't well documented. It's a chicken and egg problem.

I asked for a PR because I didn't understand what the problem was and the OP seems to be positive in what was missing. I can see now what they meant.

**Comment by snicoll** [comment]
Closing in favor of PR #35609. Thanks a lot for that @ThomasKasene
