### ISSUE TITLE
Spring Boot 2.7 - org.keycloak.adapters.KeycloakDeployment.java - protocol an error

### ISSUE THREAD

**Issue by AHDD44PP** [spring-projects/spring-boot#35627]
In my opinion, you should protocol an error here. In my case I had a SSLHandshakeException exception,
which was not clear to find in production log.
Locally everything worked fine, but on other machine ...crashed!!!
The problem was the cacert's trustore.
I need almost 12 h to find the problem. The problem was, that the first exception was thrown during token verification.

```

Code Snippet from your code:
    protected void resolveUrls() {
        if (realmInfoUrl == null) {
            synchronized (this) {
              ...
                        log.infov("Loaded URLs from {0}", discoveryUrl);
                    } catch (Exception e) {
                        ****log.warnv(e, "Failed to load URLs from {0}", discoveryUrl);****
                    }
                }
            }
        }
    }
```

**Comment by wilkinsona** [comment]
The [code you're referring](https://github.com/keycloak/keycloak/blob/fc0e47caa4763e0b563a237cda9c5962be13b0c3/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/KeycloakDeployment.java#L173-L209) to is part of [Keycloak](https://github.com/keycloak/keycloak).
