### ISSUE TITLE
spring-boot-maven-plugin 1.3.0 stop won't release tomcat port

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-boot#3563]
I created a Jenkins job, which should basically `stop`, install the new application version and `start` it.

Here's my Jenkins Post-Build Script`
```
#!/bin/bash
sudo service myApp stop
sleep 300
cp ${WORKSPACE}/webapp/target/webapp-0.0.1-SNAPSHOT.war /home/myUser/jenkins/webapp.war
sudo ln -s /home/myUser/jenkins/webapp.war /etc/init.d/myApp
sudo chmod +x /etc/init.d/myApp
sudo service myApp start
```

Sometimes the script works, but mostly it say's `Tomcat: java.net.BindException: Address already in use`. 
Afterwards there's no pid file, and I do `sudo killall -9 java && sudo service myApp start`.

My `Application.java` is pretty minimalistic:
```
@EntityScan(basePackageClasses = { Application.class, Jsr310JpaConverters.class })
@SpringBootApplication
public class Application extends SpringBootServletInitializer {
	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class);
	}
	public static void main(String[] args) throws Exception {
		SpringApplication.run(Application.class, args);
	}
}
```

The Application uses 2 MySQL Data Sources, MongoDB and Elasticsearch.

Do I need some additional shutdown code?

**Comment by snicoll** [comment]
I don't see anything related with the Maven plugin in here. Can you clarify please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
