### ISSUE TITLE
Spring Boot 3.0.4 + Spring actuator 3.0.4 ??  Field httpSecurity in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found:

### ISSUE THREAD

**Issue by xxscloud5722** [spring-projects/spring-boot#35649]
Spring Boot 3.0.4 + Spring actuator 3.0.4

Why is this Spring default code causing this? Is my version incorrect?

```
Description:

Field httpSecurity in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found:
	- requestMappingHandlerMapping: defined by method 'requestMappingHandlerMapping' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- controllerEndpointHandlerMapping: defined by method 'controllerEndpointHandlerMapping' in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/servlet/WebMvcEndpointManagementContextConfiguration.class]
	- 
```

**Comment by wilkinsona** [comment]
The `httpSecurity` field is a `org.springframework.security.config.annotation.web.builders.HttpSecurity`. Neither `requestMappingHandlerMapping` nor `controllerEndpointHandlerMapping` is an instance of `HttpSecurity` so the cause of the error isn't clear.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by xxscloud5722** [comment]
![image](https://github.com/spring-projects/spring-boot/assets/63572603/7268c453-bd2a-4eb1-8fb3-c09113ad0df0)
Thank you. I'm replaying the code I wrote and it seems like I found the problem
