### ISSUE TITLE
Problem when implementing ErrorController

### ISSUE THREAD

**Issue by YigWoo** [spring-projects/spring-boot#3565]
I'm trying to implement my own version of `ErrorController`. I know that `BasicController` provides some basic exception handler in spring boot if you don't provide your own `ErrorController` bean, and `BasicController` gets out of the way when you provide one.

So I copy `BasicController`'s codes and create a `DefaultErrorController` which implements `ErrorController`, and annotate it with `@Controller` and `@RequestMapping`. And the value of `RequestMapping` is `/error`, which is the same as the `BasicController`.

But I find that `/error` is never routed to the `DefaultErrorController` and the debug message: `No mapping found for HTTP request with URI [/error] in DispatcherServlet` is recorded.

Then I find that the method in my `DefaultErrorController` is not registered as handler methods, and `DefaultErrorController` is not registered as a handler, because `getApplicationContext().getType("defaultErrorController")` returns `com.sun.reflect.proxy.$Proxy51` which under the right setup should be `xxx.xxx.DefaultErrorController` that contains `@Controller` and `@RequestMapping` information for SpringMVC framework to decide a bean should be a handler.

So in init phase, SpringMVC framework decides that `defaultErrorController` is not a handler for request. Which finally causes my problem.

And my problem is why `DefaultErrorController` is instantiated as a `com.sun.reflect.proxy.$Proxy` instance, and how to fix that?

Thanks.

**Comment by wilkinsona** [comment]
This has been fixed in https://github.com/spring-projects/spring-boot/commit/cfbac208078f35fc2b7fafc961c888b92c088c05. Please see #4236 for details.
