### ISSUE TITLE
Change B3 extraction format to SINGLE

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#35674]
Right now, we're using `B3Propagation.Format.SINGLE_NO_PARENT`. We should change this to `SINGLE`.

See [this discussion](https://github.com/spring-projects/spring-boot/pull/35611#discussion_r1205290111).

**Comment by KitBolourchi** [comment]
Hey @mhalbritter, I would be happy to look into this issue. Please assign it to me :)

**Comment by scottfrederick** [comment]
Thanks @KitBolourchi, I've assigned the issue to you. We have not yet created the branches to start `3.2.x` development, so we won't be able to accept a contribution for a while.

**Comment by KitBolourchi** [comment]
Hey @scottfrederick, no problem at all! Would you recommend I make the change and create a PR which can be merged when ready or wait until you are ready before raising the PR?

**Comment by mhalbritter** [comment]
https://github.com/spring-projects/spring-boot/pull/35611/files will move some things around, so please hold off until this PR is merged, otherwise there will be quite some merge conflicts.

**Comment by KitBolourchi** [comment]
Gotcha I understand, I will hold off until the release branch is ready!

**Comment by mhalbritter** [comment]
#35611 is merged, you can now start :)

**Comment by KitBolourchi** [comment]
Great, I will get started on this shortly :) Thanks
