### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.isTrue(boolean, java.util.function.Supplier)'

### ISSUE THREAD

**Issue by Barlerer** [spring-projects/spring-boot#35685]
Bug report:
I am using the FileSystemWatcher, and when I call the `addSourceDirectory` function, I get the following error message:

`java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.isTrue(boolean, java.util.function.Supplier)'
`

It seems because 1 of the assertions is using a lambda function for the message, instead of String.

**Comment by wilkinsona** [comment]
You are using an incompatible version of Spring Framework. `org.springframework.util.Assert.isTrue(boolean, Supplier<String>)` was added in Spring Framework 5.0.
