### ISSUE TITLE
Baggage fields are not passing on with TraceableExecutor wrapping

### ISSUE THREAD

**Issue by gayanper** [spring-projects/spring-boot#35691]
I have a spring boot project which use CompleteableFutures to run certain tasks. We use our own executor for executing this futures. 

The traceId and spanId are correctly propagated to threads that runs the futures. But the baggage field we create in the root span is not passed down. 

We use w3c propagation type with otel library for slueth. 

Is this as expected? Do we need to recreate the baggage field on all spans if that needs to be propagated tracing and logs ?

**Comment by wilkinsona** [comment]
> We use w3c propagation type with otel library for slueth.

Are you using Spring Boot 2.7 with Spring Cloud Sleuth?

**Comment by gayanper** [comment]
> > We use w3c propagation type with otel library for slueth.
> 
> 
> 
> Are you using Spring Boot 2.7 with Spring Cloud Sleuth?

Springboot: 2.6.0
And we use spring cloud bom version: 2021.0.1
