### ISSUE TITLE
Spring Boot 3.1.0 Configuration Changelog does not exist

### ISSUE THREAD

**Issue by intriguingblackmesa** [spring-projects/spring-boot#35706]
The [Spring Boot 3.1.0 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes) reference the [Spring Boot 3.1.0 Configuration Changelog](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1.0-Configuration-Changelog), but as of writing, the configuration changelog page does not exist.

**Comment by wilkinsona** [comment]
Thanks for pointing out the oversight. The wiki has been updated.
