### ISSUE TITLE
When virtual threads are enabled, configure Tomcat to use them

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#35704]
Tomcat's virtual thread support [has been back-ported to 10.1.x](https://github.com/apache/tomcat/commit/3949154e2fab7e6ac40f67a8a708aeea1476a0f3) and should be available in the next 10.1.x release. We can use the new `VirtualThreadExecutor` to configure Tomcat to use virtual threads.

**Comment by mhalbritter** [comment]
`VirtualThreadExecutor` is now available with Tomcat 10.1.10.
