### ISSUE TITLE
Spring Boot docker compose  is not available in maven repository for Spring Boot 3.1 

### ISSUE THREAD

**Issue by dimasadryantos** [spring-projects/spring-boot#35717]
Hi I tried to use maven to reproduce docker compose support in Spring boot 3.1 
however when I try to use the dependency it was not available in the maven repository yet : 

```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
            <optional>true</optional>
        </dependency>
```

is it only available in gradle for now ?

**Comment by mvitz** [comment]
I already tested the dependency last week and https://central.sonatype.com/artifact/org.springframework.boot/spring-boot-docker-compose/3.1.0 lists the artifact as available, too.

Therefore I think it has something to do with your Maven configuration and or internet connection/configuration. What exact error message do you get when running `mvn verify`? Are you using a repository manager?

**Comment by dimasadryantos** [comment]
Hi @mvitz I fix it by change my path configuration in my local but I'm curious why it's not in the maven repository ?

https://mvnrepository.com/search?q=spring-boot-docker-compose

Thank you

**Comment by wilkinsona** [comment]
mvnrepository.com is an eventually consistent view of what's available in Maven Central. It's managed by a third-party and is completely out of our control. Please use https://repo.maven.apache.org/maven2/org/springframework/boot as the canonical source.
