### ISSUE TITLE
Review `TaskExecutorBuilder` and `TaskExecutorCustomizer` in the context of virtual threads

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#35711]
Both `TaskExecutorBuilder` and `TaskExecutorCustomizer` are aimed at `ThreadPoolTaskExecutor`. We should review them with virtual threads in mind. I suspect we may end up with some new classes that are aimed at `SimpleAsyncTaskExecutor` which provides virtual thread support. If we take that route, we may want to rename the existing builder and customiser to `ThreadPoolTaskExecutorBuilder` and `ThreadPoolTaskExecutorCustomizer`.

**Comment by mhalbritter** [comment]
The rename of the existing builder is handled in #36637.

**Comment by mhalbritter** [comment]
There's now a `SimpleAsyncTaskExecutorBuilder` in the context to build `SimpleAsyncTaskExecutor`s. When virtual threads are enabled, the `SimpleAsyncTaskExecutorBuilder` will be auto-configured to use them.
