### ISSUE TITLE
Spring-boot-devtools not restarted when change groovy-files

### ISSUE THREAD

**Issue by sanitar4eg** [spring-projects/spring-boot#3574]
I asked in [stackoverflow](http://stackoverflow.com/questions/31480437/spring-boot-devtools-not-restarted-when-change-groovy-files), but me not given answer.
In my project i use spring-boot:1.3.0.M1 from http://repo.spring.io/milestone and spring-boot-devtools. 
Also in the dependencies I have groove-all.
When I changed application.properties or java-classes - my server load changes, and everything works fine. But when I changed my groovy-classes - nothing happens.
I use IDEA and gradle.
Thank you in advance for help

**Comment by snicoll** [comment]
where is your groovy code located? Is that a script?

**Comment by sanitar4eg** [comment]
In src/main/groovy and it classes

**Comment by snicoll** [comment]
so you do recompile the groovy code when you change it, right?

**Comment by sanitar4eg** [comment]
Oh sorry,  i compile groovy, but in build directory class-file not changed.
Thanks for help, I'll deal with IDEA now.

**Comment by snicoll** [comment]
Can you let us know what you've changed when you're done?

**Comment by sanitar4eg** [comment]
I finished, I'm sorry to trouble you.
Now, first I'm going to ask for help on the forum.
