### ISSUE TITLE
Bug in Spring Cloud Connectors breaks Mongo apps in Cloud Foundry

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3578]
https://github.com/spring-cloud/spring-cloud-connectors/issues/129

**Comment by dsyer** [comment]
Should be fixed with the new connectors, but the build pack is probably not: https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/issues/50

**Comment by wilkinsona** [comment]
Looks like this one's been fixed now
