### ISSUE TITLE
Logging and Systemd

### ISSUE THREAD

**Issue by reppard** [spring-projects/spring-boot#3580]
I created a systemd unit as outlined here:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-service.html#_installation_as_a_systemd_service

I can see my app startup using 'journalctl --unit <my service>' but after the embedded tomcat comes up I have no log output.  Nothing in /var/log either.  The service is running and taking requests.  Any pointers here would be greatly appreciated.  Thanks!

**Comment by dsyer** [comment]
The script is here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script

What shell is it using? Maybe if it's not bash it the stdout redirection isn't working?

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
