### ISSUE TITLE
Java system properties can not be applied to RestTemplate HttpClient connection in some cases

### ISSUE THREAD

**Issue by alex-kormukhin** [spring-projects/spring-boot#35815]
Spring boot 3.1.0 `RestTemplateBuilder` with apache HTTP client in classpath (`org.apache.httpcomponents.client5:httpclient5`) ignore java system HTTP proxy command line options like `-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888`.

Spring boot before 3.1 respects such settings.

For simple `RestTemplate restTemplate = restTemplateBuilder.build()` spring boot 2.7 [instantiate](https://github.com/spring-projects/spring-boot/blob/v2.7.12/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/ClientHttpRequestFactorySupplier.java#L54) [HttpComponentsClientHttpRequestFactory](https://github.com/spring-projects/spring-framework/blob/v5.3.27/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequestFactory.java#L79) via default constructor, which create HTTP client as `HttpClients.createSystem()`, i.e. with system proxy support.

![image](https://github.com/spring-projects/spring-boot/assets/99888299/d7c8ae39-cf87-4a0f-8f54-f8fb26f7c359)

Spring boot 3.0 (if readTimeout duration is not set) also create HttpComponentsClientHttpRequestFactory via default constructor and HTTP client as [`HttpClients.createSystem()`](https://github.com/apache/httpcomponents-client/blob/rel/v5.1.4/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClients.java#L65).

![image](https://github.com/spring-projects/spring-boot/assets/99888299/75f432ad-6939-48b2-b468-34a1adcda670)

But spring boot 3.1 create HTTP client as `HttpClientBuilder.create().setConnectionManager(connectionManager).build()`. Without [`useSystemProperties()`](https://github.com/apache/httpcomponents-client/blob/rel/v5.1.4/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClients.java#L65) as `HttpClients.createSystem()` makes.

![image](https://github.com/spring-projects/spring-boot/assets/99888299/8d07178e-c7b6-4cb8-96bd-847f710a6ef4)

Suggestion: add useSystemProperties() to createHttpClient method like this
```
return HttpClientBuilder.create()
    .useSystemProperties()
    .setConnectionManager(connectionManager)
    .build();
```
For compatibility with spring boot 2.x, 3.0, and core spring HttpComponentsClientHttpRequestFactory.

**Comment by scottfrederick** [comment]
While it does appear that behavior changed with 3.1 in this regard, the fact that previous releases allowed system properties to be applied in some cases but not others (for example, when `readTImeout` is set) doesn't seem right to me. We might want to address this in earlier versions, and make sure that system properties can be applied in all cases. 

Marking this for team attention to see what other think.

**Comment by mhalbritter** [comment]
I agree with you Scott. We should restore old behavior and fix the inconsistencies in earlier versions.

**Comment by p-palanisami** [comment]
I am new to Open Source Contributor. Shall i work on this issue?
