### ISSUE TITLE
Spring boot 3.0.7 in Native failes to work with Hibernate Lazy fetch - HibernateProxy instances at runtime is not allowed when the configured BytecodeProvider

### ISSUE THREAD

**Issue by denysandriyanov** [spring-projects/spring-boot#35822]
Hello.
I am using Spring Boot version 3.0.7

Preconditions:

I have a hibernate entity that is using fetch = FetchType.LAZY 

    @JoinTable(name = "user_identities", joinColumns = {
            @JoinColumn(name = "user_id")}, inverseJoinColumns = {
            @JoinColumn(name = "user_identity_id")})
    @OneToMany(fetch = FetchType.LAZY, orphanRemoval = true)
    private Set<Identity> identities;

    @JoinTable(name = "user_roles", joinColumns = {
            @JoinColumn(name = "user_id")}, inverseJoinColumns = {
            @JoinColumn(name = "role_id")})
    @OneToMany(fetch = FetchType.LAZY)
    private Set<Role> roles;

Steps:
Execute below query
    @Query("SELECT u FROM User u JOIN u.identities i JOIN FETCH u.roles r WHERE i.sub = :sub AND i.issuer = :issuer")
    Optional<User> findByIdentitySubAndIssuer(String sub, String issuer);

Actual result in JVM: everything works as expected
Actual result in Native:   Generation of HibernateProxy instances at runtime is not allowed when the configured BytecodeProvider

Please help.

Thank you

**Comment by mhalbritter** [comment]
Do you have the hibernate enhancer plugin in your build, like the [generated project from start.spring.io](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.1.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-jpa,native) has?
