### ISSUE TITLE
Make distinction between Testcontainers for integration tests and development more clear in documentation

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#35856]
The documentation [has a section](https://docs.spring.io/spring-boot/docs/3.1.0/reference/htmlsingle/#features.testing.testcontainers) on using Testcontainers for testing. Sub-sections have information specific to integration testing and development-time testing, but this distinction is not clear from the headings. It might be better to separate these two testing concerns into separate sections to make the differences more clear.

**Comment by hantsy** [comment]
Quarkus Dev and Micronaut test-resources, the background testcontainers are working seamless in those cases running the application and running integration tests.

I really do not understand the purpose of Spring Boot newly introduced test Application class, and some config(such as declaring test containers as beans) are only for the `development time`.

**Comment by eddumelendez** [comment]
> some config(such as declaring test containers as beans) are only for the development time.

It was fixed in spring boot 3.1.3. See https://github.com/spring-projects/spring-boot/issues/36661

So, the experience is consistent between testing and development mode
