### ISSUE TITLE
Password is not used from spring.data.redis.url property without username

### ISSUE THREAD

**Issue by vuzem** [spring-projects/spring-boot#35850]
Hi team,

it appears that a provided password in the spring.data.redis.url property is not taken into account since Spring Boot 3 (version used 3.1.0), which lets a Redis connection fail.

For example, the password is provided in this spring.data.redis.url property:

`spring.data.redis.url=redis://password@redis-host:6379`

And when retrieving the password from, for example, a RedisStandaloneConfiguration, the password is empty:

```
import org.apache.commons.lang3.reflect.FieldUtils;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.RedisStandaloneConfiguration;
import org.springframework.data.redis.core.RedisTemplate;

@Configuration
public class RedisConfig {

    @Bean
    RedisTemplate<String, String> redisTemplate(RedisConnectionFactory redisConnectionFactory)
                                                      throws IllegalAccessException {

    	RedisStandaloneConfiguration configuration = 
    			(RedisStandaloneConfiguration) FieldUtils.readField(redisConnectionFactory,
    			   "configuration", true);
    			   
    	System.out.println("password present: " + configuration.getPassword().isPresent());
    	
    	RedisTemplate<String, String> redisTemplate = new RedisTemplate<>();
    	redisTemplate.setConnectionFactory(redisConnectionFactory);

        return redisTemplate;
    }

}
```

As mentioned above, the password is provided when running this configuration with Spring Boot 2 (2.7.12).

Thanks and cheers
Alex

**Comment by mhalbritter** [comment]
Thanks for the report, I've edited your description to replace "guys" with "team". While it may seem like a small thing, some people feel excluded by "guys" and we don't want them to.

**Comment by vuzem** [comment]
Hi @snicoll,

thanks for your answer. I have read the migration guide, as well as the latest Spring Boot documentation, and there it is said, that the property `spring.data.redis.url` still exists and it overrides the password property:

> Connection URL. Overrides host, port, and password. User is ignored. Example: redis://user:password@example.com:6379

https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.data.redis.url

Cheers
Alex

**Comment by vuzem** [comment]
Hi @snicoll,

thanks for your answer. Sorry for not being precise enough, for Spring Boot 2, the property needs to be `spring.redis.url` of course. I have attached two sample projects including the `RedisConfig` from above.

Sample project with Spring Boot 2.7.12 and property `spring.redis.url`:
[RedisPropertiesSpringBoot2.zip](https://github.com/spring-projects/spring-boot/files/11725433/RedisPropertiesSpringBoot2.zip)

Sample project with Spring Boot 3.1.0 and property `spring.data.redis.url`:
[RedisPropertiesSpringBoot3.zip](https://github.com/spring-projects/spring-boot/files/11725440/RedisPropertiesSpringBoot3.zip)

Cheers
Alex
