### ISSUE TITLE
Add SslAutoConfiguration to slice test annotations

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#35861]
Existing examples such as [SampleMongoApplicationReactiveSslTests](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-data-mongo/src/test/java/smoketest/data/mongo/SampleMongoApplicationReactiveSslTests.java) uses `@SpringBootTest` which will use `SslAutoConfiguration`. If `@DataMongo` is used then `@Import(SslAutoConfiguration.class)` should be declared. I think it would be great to add `SslAutoConfigure` [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports)

The same for the rest of them such `DataRedis`, `DataCouchbase`, `DataElasticSearch`.

I would like to know your opinion on this topic before raising any PR.

Thanks in advance

**Comment by SoumyoNathTripathy** [comment]
// For MongoDB:
// If you are using the @SpringBootTest annotation, which relies on SslAutoConfiguration, and you are also using
// @DataMongo, you may need to explicitly import SslAutoConfiguration in your test class using @Import annotation.
// This ensures that SSL configuration is applied correctly for the MongoDB module.

**Comment by scottfrederick** [comment]
Closing in favor of #36038
