### ISSUE TITLE
Flayway exclude when I have Flyway in classpath

### ISSUE THREAD

**Issue by CyborTronik** [spring-projects/spring-boot#3586]
I have added flyway manually in a spring boot application.
I used it to create 3 databases and managed everything by my self.
So the issue is there I have created custom locations for database migration (so new folder for each db).
But spring tries to migrate flyway automatically because it has found flyway classes in path.
I don't wanna that. So how to exclude that?
I have tried:

@EnableAutoConfiguration(
		exclude = { FlywayAutoConfiguration.class, FlywayAutoConfiguration.FlywayConfiguration.class })

**Comment by snicoll** [comment]
Please do not use this tracker for questions. Questions have to be raised on stackoverflow.

How about adding `flyway.enabled=false` to your configuration?
