### ISSUE TITLE
Disable Rabbit/JMS listeners via configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3587]
There is currently no way to disable the Rabbit or JMS listeners via configuration as  `@EnableRabbit` and `@EnableJms` are enabled automatically. 

Excluding the auto-config would be one way but a configuration option would be nice to disable that behaviour via a profile, i.e. in development.

See [this stackoverflow thread](http://stackoverflow.com/questions/31589401/disabling-the-listening-to-rabbit-queues-from-spring-application-properties)

**Comment by garyrussell** [comment]
@snicoll Are you thinking of eliminating the beans altogether, or simply exposing `autoStartup` ?

Perhaps autoStartup would provide most flexibility.

**Comment by snicoll** [comment]
Not processing the listeners at all. But that's also a good idea.

**Comment by joshthornhill** [comment]
+1 for @garyrussell's idea. I use <code>autoStartup</code> myself for this purpose.

**Comment by snicoll** [comment]
See also #1425

**Comment by snicoll** [comment]
It turns out that disabling the whole JMS/Rabbit business is more work than I expected and since the `autoStartup` flag is actually addressing the issue I've only done that.
