### ISSUE TITLE
Jackson's ObjectMapper writes empty JSON strings for Spring Boot 3.1.0 if the entity is a record

### ISSUE THREAD

**Issue by DManstrator** [spring-projects/spring-boot#35891]
# Bug Report

I noticed after upgrading from Spring Boot 2.7.12 to Spring Boot 3.1.0, that records cannot be serialized anymore. `ObjectMapper#writeObjectAsString` now returns `{ }`. With Spring Boot 2.7.12, the serilization of records was possible. Since I found nothing in the migration guideline, I expect this to be a bug.

I created a minimal, reproducable example to show this, see https://github.com/DManstrator/sb3-serialization-test/pull/1 and the Checks.

**Comment by DManstrator** [comment]
Thanks for the quick feedback. I guess the problem is that the Spring Boot upgrade also updated Jackson since I make use of the `spring-boot-dependencies` bom. Perhaps they have changed something which causes this issue. I also thought it seems unrelated to Spring Boot but I didn't have a better idea. Due to that I didn't want to make the project as minimal as possible to not waste too much time. So sorry for the wrong issue and thanks again.

**Comment by DManstrator** [comment]
@wilkinsona: Small update: This is in fact a Jackson bug which was already fixed in Jackson v2.15.1, see https://github.com/FasterXML/jackson-databind/issues/3895. However Spring Boot 3.1.0 still uses Jackson 2.15.0.

I guess in the next patch / minor update, you will also increase the Jackson version?

**Comment by philwebb** [comment]
@DManstrator Correct. We have an automated process which will pick up the next Jackson release.

**Comment by rdehuyss** [comment]
When will Spring Boot 3.1.1 be released? Users are also [reporting errors](jobrunr/jobrunr-pro#150) for JobRunr related to this.

**Comment by scottfrederick** [comment]
@rdehuyss Scheduled release dates are shown here: https://github.com/spring-projects/spring-boot/milestones

**Comment by rdehuyss** [comment]
Thanks - makes sense 🙂. I feel like a 🤡 for not checking it...
