### ISSUE TITLE
LoggingSystem backwards compatibility with 1.2.x

### ISSUE THREAD

**Issue by andrewduckett** [spring-projects/spring-boot#3591]
We're using a custom LoggingSystem implementation and as of 1.3.0.M2 (related to #3493) the interface has been enhanced to include some environment context.  While this seems like a welcome addition it's by no means backwards compatible in a minor release.  Thoughts on creating an adaptor of sorts until a major milestone to allow existing implementations to remain intact?

**Comment by philwebb** [comment]
I'll restore the old method, deprecate it and call it from the new one. I didn't think anyone would be extending it outside of us :)

**Comment by andrewduckett** [comment]
Thanks @philwebb this looks great.  You gave us that nifty system property hook and we took advantage.  We've made note of the deprecation and will plan to move off asap!

**Comment by bohrqiu** [comment]
i have used public void initialize(String configLocation, LogFile logFile) method too ....

**Comment by bohrqiu** [comment]
and i use EnvironmentHolder to hold environment context at environmentPrepared phase

**Comment by wilkinsona** [comment]
@bohrqiu Can you described your usage in a bit more detail, please? Have you also implemented your own `LoggingSystem`, or are you calling into one provided by Boot?

**Comment by bohrqiu** [comment]
yes,I have implemented own LoggingSystem to support:
1.  environment context
2. add LevelChangePropagator for performance
3. extract LogInitializer for extend 
     
    public interface LogInitializer {
	void init(LogbackConfigurator configurator);
    }

4. add ConsoleAppenderLogInitializer(same as default behave，but I will distinguish production env，production env Console will be disable ) and FileAppenderLogInitializer(asyn log support)

**Comment by wilkinsona** [comment]
Thanks. Would you mind opening a separate issue, please? This one's closed and "fixed" in M3 which has been released. If you do so, we can take a look for RC1.

**Comment by bohrqiu** [comment]
ok，I use 1.2.x now, I will upgrade 1.3.0.x and pull a request for some enhance。thank you ^_^
