### ISSUE TITLE
Bugs in spring-boot-docker-compose:3.1.0

### ISSUE THREAD

**Issue by Nick-Wunderdog** [spring-projects/spring-boot#35921]
With Spring Boot 3.1.0 using Maven parent spring-boot-starter-parent:3.1.0 On OpenSuse Linux Leap 15.5. Maven 3.8 with Java JDK  Temurin-17.0.7+7. Latest versions of everything at the moment of writing this. 

with compose.yaml file at project root (with works ok) runnin 
with Docker version

> Plugins:
>   compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
>
> Server:
>   Server Version: 20.10.23-ce

## BUG #1 
`mvn spring-boot:run`

it fails with error : 

> 2023-06-16 00:09:46,326 INFO o.s.b.l.LogLevel [OutputReader-stderr] unknown flag: --wait
> 2023-06-16 00:09:46,334 ERROR o.s.b.SpringApplication [main] Application run failed
> org.springframework.boot.docker.compose.core.ProcessExitException: 'docker compose --file ./compose.yaml --ansi never up --no-color --detach --wait' failed with exit code 16.
> 

docker compose up does not have flag "--wait" 

## BUG #2
org.springframework.boot.docker.compose.lifecycle.DockerComposeProperties: 283 
```java
		/**
		 * Readiness wait strategies.
		 */
		public enum Wait {

			/**
			 * Always perform readiness checks.
			 */
			ALWAYS,

			/**
			 * Always perform readiness checks.
			 */
			NEVER,
```
ALWAYS and NEVER have same (cut&paste) javadoc 

## BUG #3 
using property : `spring.docker.compose.start.command=start`
`mvn spring-boot:run` fails with: 

> 2023-06-16 00:13:06,947 INFO o.s.b.l.LogLevel [OutputReader-stderr] unknown flag: --no-color
> 2023-06-16 00:13:06,956 ERROR o.s.b.SpringApplication [main] Application run failed
> org.springframework.boot.docker.compose.core.ProcessExitException: 'docker compose --file ./compose.yaml --ansi never start --no-color --detach --wait' failed with exit code 16.

docker compose start does not have flag "--no-color"

**Comment by scottfrederick** [comment]
> Plugins:
> compose: Docker Compose (Docker Inc., v2.0.0-rc.3)

> docker compose up does not have flag "--wait"

> docker compose start does not have flag "--no-color"

This appears to be a pre-release version of Docker Compose that does not support the command-line flags that Spring Boot requires. The most recent version of the plugin available at the time of this writing is `v2.18.1`. Please [upgrade](https://docs.docker.com/compose/install/) to a newer version of the Docker Compose plugin. 

> ALWAYS and NEVER have same (cut&paste) javadoc

This has been fixed in https://github.com/spring-projects/spring-boot/commit/0ca3ab7249437fcacdc7dbd3021896bc4c79c81b.
