### ISSUE TITLE
Update default compressable MIME types to align with Tomcat again

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3592]
When response compression is enabled, it doesn't compress JavaScript files but it compresses CSS files. Is it intentionally? Why we don't compress JS files? Should we change the defaults?

**Comment by wilkinsona** [comment]
Spring boot uses the same default [as Tomcat](https://tomcat.apache.org/tomcat-8.0-doc/config/http.html) and I think we should continue to do so.

**Comment by php-coder** [comment]
Quote from the http://tomcat.apache.org/tomcat-8.0-doc/changelog.html: `Add text/javascript,application/javascript to the default list of compressable MIME types.`

@wilkinsona Andy, maybe we should reopen this issue and update Spring Boot's defaults?

**Comment by wilkinsona** [comment]
@php-coder Well spotted. Thanks.
