### ISSUE TITLE
Sprinboot 1.3 M2 logback extension and Logback.groovy

### ISSUE THREAD

**Issue by jamroks** [spring-projects/spring-boot#3593]
hi,

 I'm very pleased with the addition of logback extension, really cool stuff, especially  <springProperty> !! so kudos to the springboot team. 
I have also read in the release note, that " To use the tags you need to first rename any logback.xml configuration to logback-spring.xml ",   now  in our application we have been using and crafted a logback.groovy configuration which give us more flexibility than xml config. Are we gonna benefit from the goodies of Springboot logback extension and the double logging  initialization prevention if we rename logback.groovy to logback-spring.groovy ? is it even required  or supported in this case  ? 

Thanks

**Comment by snicoll** [comment]
Hey,

Thanks for the kind words. Have you tried? Short answer: yes, see [the documentation](http://docs.spring.io/spring-boot/docs/1.3.0.M2/reference/htmlsingle/#boot-features-custom-log-configuration)

**Comment by jamroks** [comment]
didn't try, traveling right now. but Cool just saw that in the doc ,  Sweet !!

Cheers
