### ISSUE TITLE
Jackson autoconfiguration depends on spring-web

### ISSUE THREAD

**Issue by Raniz85** [spring-projects/spring-boot#3594]
`JacksonAutoConfiguration` is in *spring-boot-autoconfiguration* but it uses `Jackson2ObjectMapperBuilder` which depends on `SpringHandlerInstantiator`. Both are in *spring-web* and as such the `ObjectMapper` won't be configured unless these two classes are on the classpath.

*spring-web* is a rather hefty dependency to pull in if you only want to have the `ObjectMapper` autoconfigured and I'd rather depend on a smaller library such as *spring-boot-starter-jackson* or *spring-jackson*.

**Comment by snicoll** [comment]
I'd say that if there is a problem, it's not here. It totally makes sense that our jackson auto-config uses `Jackson2ObjectMapperBuilder` and splitting that in two would remove a lot of _meat_ from it.

Maybe an issue in Spring Framework would be more appropriate.

Ping @sdeleuze

**Comment by wilkinsona** [comment]
Looks like @snicoll was typing his reply as I was typing mine. Here are my, very similar, thoughts:

I don't think this is likely to change any time soon in Spring Boot. The use of `Jackson2ObjectMapperBuilder` is pretty fundamental to how the Jackson auto-configuration works. It allows us to create an `ObjectMapper` with the user's configuration and apply that configuration to any `ObjectMapper` beans created by other components (Spring Data REST, for example).

You may want to raise a [Spring Framework issue](https://jira.spring.io/browse/SPR) asking for `Jackson2ObjectMapperBuilder` to move into a module that isn't web-specific.

**Comment by snicoll** [comment]
@Raniz85 feel free to raise a spring framework issue. Thanks.

**Comment by Raniz85** [comment]
Sounds like a reasonable solution. I've opened an [issue](https://jira.spring.io/browse/SPR-13282) on Spring Framework about moving the two classes to a separate artifact.
