### ISSUE TITLE
Allow key password to be set for a PemSslStoreBundle

### ISSUE THREAD

**Issue by chicobento** [spring-projects/spring-boot#35983]
### Background
We have a custom component for watching for changes on PEM files and reloading some components such as tomcat.
We are using `PemSslStoreBundle` to load the PEM files into keystores. This class has a limitation of not allowing to specify the key password: [it is always null](https://github.com/spring-projects/spring-boot/blob/71597300f418323bbf472f98ae71705a819f4b54/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/ssl/pem/PemSslStoreBundle.java#L107).

### Problem
Tomcat currently cannot pickup null key passwords: if the key password is null, it'll attempt to use the keystore password and consequently fail to load the keys. See: [SSLUtilBase](https://github.com/apache/tomcat/blob/10.1.8/java/org/apache/tomcat/util/net/SSLUtilBase.java#L278).
Even though the limitation should be fixed on tomcat, other 3pp components could have a similar issue, hence it would be great to improve this algorithm to take the key password as parameter.

### Workaround
A workaround for this case is to provide tomcat an empty string password: tomcat will use the empty string to load the keys, and surprisingly `keyStore.getKey("alias", "".toCharArray())` works for keys saved with null password on Open JDK 17, however it looks like an odd undocumented behavior which may not work on future versions.

**Comment by scottfrederick** [comment]
@chicobento Do you have a case where you need to set the key password to a value other than "empty", or do you just need it not be `null` (as in your workaround example) to keep Tomcat from trying to use the keystore password?

**Comment by chicobento** [comment]
Hi @scottfrederick , I dont have any case so far. 

My only concern is that there might be cases were a component receives the keystore configuration in a config file, lets say, yaml. In this case it would be a little tricky to represent an empty string depending on how the component will interpret it. Also, some components could be doing some dumb emptiness comparison to fall back to keystore password or something.
