### ISSUE TITLE
Default autoconfiguration classes without @Order to zero?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#3599]
I'm trying to provide a fallback service implementation in an autoconfiguration class using `@ConditionalOnMissingBean`, but without explicit ordering instructions, I get collisions where the live service bean isn't registered with the factory before the condition is evaluated. Using ordering annotations fixes the issue, but this requires all classes providing the bean to specify `@Order(something-smaller-than-LOWEST_PRECEDENCE)`.

I suggest that autoconfiguration classes that have no `@Order` annotation at all should be treated as though they had an order 0, allowing classes that have a strong preference to insert themselves last without requiring cooperation from every other.

**Comment by snicoll** [comment]
I am not sure I understand your setup. What service implementation are you talking about? If that's defined by another auto-config then you need to use `@AutoconfigureAfter` or something of the kind rather than implying an order across several auto-configuration units.

**Comment by chrylis** [comment]
In this immediate case, it's a mail service, but that's incidental to the overall request.

While I understand the ability provided by `@AutoConfigureBefore`/`After`, those have the serious limitation that one side of the default/override relationship must be aware of the other, and providing multi-level ordering is even more challenging. Even though it's now possible to specify the class name as a string and thus avoid actual compile-time coupling, there's a linkage between the two implementations that doesn't need to be there. Using the existing (and working `@Order`) functionality makes this sort of logic cleaner, and there's no existing specification that the default order should be `LOWEST_PRECEDENCE`.

**Comment by wilkinsona** [comment]
> those have the serious limitation that one side of the default/override relationship must be aware of the other, and providing multi-level ordering is even more challenging

I disagree with this. When you're trying to order auto-configuration with respect to each other then, conceptually at least, they must be aware of each other. Using `@AutoConfigurationBefore` and `@AutoConfigureAfter` makes the relationship very clear. Abstracting it away into arbitrary order values only hides that needs for awareness, it doesn't remove it.

That said, I think this is losing sight of the original request which was to make it easy to provide an auto-configuration class that always goes last.

> there's no existing specification that the default order should be `LOWEST_PRECEDENCE`.

Unfortunately, there is: `@Order` defaults the value to `LOWEST_PRECEDENCE` and `OrderComparator` falls back to `LOWEST_PRECEDENCE` in the absence of any ordering. I think it would be confusing for Boot to use a different default and/or fallback. However, in 1.3 we've introduced a new auto-configuration-specific ordering annotation, `@AutoConfigureOrder`. This, perhaps, gives us an opportunity to use a different default and/or fallback. If we make a change here, we'll have to tread carefully. It would be a breaking change that, for example, [will affect Spring Cloud](https://github.com/spring-cloud/spring-cloud-commons/blob/c55c6117ab4955e95b20ad9e891d26f5011b5e1b/spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java#L44) /cc @dsyer @spencergibb

**Comment by chrylis** [comment]
> That said, I think this is losing sight of the original request which was to make it easy to provide an auto-configuration class that always goes last.

Fair enough. The specificity was probably getting into the weeds.

> Unfortunately, there is: `@Order` defaults the value to `LOWEST_PRECEDENCE` and `OrderComparator` falls back to `LOWEST_PRECEDENCE` in the absence of any ordering.

The first is clearly documented, but the behavior of a missing `@Order` isn't, at least not with the annotation itself. Should I raise that against SPR?

**Comment by snicoll** [comment]
Quote from the javadoc of `OrderComparator`

> Non-Ordered objects are treated as greatest order values, thus ending up at the end of the list, in arbitrary order (just like same order values of Ordered objects).

What isn't documented in Spring Framework exactly?

**Comment by chrylis** [comment]
The behavior of ordering where some items are annotated and some are not is not referenced from the Javadoc for `@Order` itself. It was not clear to me that `OrderComparator` was where to look for that default.

**Comment by snicoll** [comment]
well. `OrderComparator` is the implementation that apply the ordering. The choice of handling non-annotated items is an implementation detail so it can't really be defined on `Order` itself.

**Comment by chrylis** [comment]
I think the alternate fix to that handles the description I was going for. I would still like to have something that's effectively the opposite of `@PriorityOrder`; not sure whether editing this issue or closing and creating a new one would be better.

**Comment by snicoll** [comment]
@chrylis if you still feel strongly that way, I'd prefer a fresh issue at this point. Thanks.
