### ISSUE TITLE
Maven plugin - exclude dependencies - incorrect documentation

### ISSUE THREAD

**Issue by tenstriker** [spring-projects/spring-boot#3601]
http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/exclude-dependency.html

```<configuration>
          <excludes>
            <excludeGroupIds>com.foo</excludeGroupIds>
          </excludes>
        </configuration>
```

This should be just 
```
<configuration>
            <excludeGroupIds>com.foo</excludeGroupIds>         
 </configuration>
```

Similar in one more example .

**Comment by wilkinsona** [comment]
@snicoll Does the same problem affect 1.2.x?

**Comment by snicoll** [comment]
good catch, that's definitely worth a backport. I'll do it tomorrow. Thanks!
