### ISSUE TITLE
TraceID not propagated from Sleuth - SB 2.7.x to SB 3.1.0

### ISSUE THREAD

**Issue by saulgiordani** [spring-projects/spring-boot#36026]
I've migrated some applications to Spring boot 3 (with observability), while others are still on 2.7 (with sleuth 3.1.5). I'm testing the tracing between applications, and while from 3 to 2.7 and from 3 to 3 the traceID is correctly propagated, from 2.7 to 3 it is not.

I've instructed sleuth to be compatible with the the new observability, setting the properties as indicated in the documentation:
```
spring.sleuth.traceId128=true
spring.sleuth.supportsJoin=false
spring.sleuth.propagation.type=w3c,b3
```
In the 2.7 apps I'm getting the traceContext like this
`tracer.currentSpan().context()`
while in the 3 like this
`Optional.ofNullable(tracer).map(Tracer::currentTraceContext).map(CurrentTraceContext::context).get()`

**Comment by wilkinsona** [comment]
Can you please provide a minimal example that reproduces the behaviour you've described?
