### ISSUE TITLE
BugReport: Regarding MongoManagedTypes is being a private constructor class with final keyword for the class for spring-boot 3.1.0

### ISSUE THREAD

**Issue by ssrksiva** [spring-projects/spring-boot#36020]
In Spring-Boot 3.1.0 version after upgrading found the MongoManagedTypes  class not found, error thrown due to the private constructor and final keyword to the class added with this release, it doesn't allow to use mongodb with earlier approach of mappingcontext. Kindly take a look and fix the bug, if possible. thank you.

**Comment by wilkinsona** [comment]
`MongoManagedTypes` is part of [Spring Data MongoDB](https://github.com/spring-projects/spring-data-mongodb).
