### ISSUE TITLE
When using Flyway 9.20.0, auto-configuration fails with a NoSuchMethodError due to the removal of Oracle-related methods from FluentConfiguration

### ISSUE THREAD

**Issue by bseeger** [spring-projects/spring-boot#36029]
This doesn't fall into the categories described in your issue template, so hopefully this is okay. 

I wanted to let you know about a flyway issue with their new minor release (9.20.0).  They [removed some methods](https://github.com/flyway/flyway/commit/5bda08d4b101b30ad6eb9c7ffd6b10a416d5f6ef#diff-af4e169b8f26dd1d2bdf77f2a097917b46acc3e326309ab88499c3e787659398L844) that requires a change in Spring Boot.  

Their comment about it being a Teams level feature is interesting and I wanted to share that with you. 
 Details here:  https://github.com/flyway/flyway/issues/3694

For reference, I tried Spring Boot version 3.1.0 with Flyway 9.20.0 and my code still fails to compile.

**Comment by wilkinsona** [comment]
Thanks for the report, @bseeger. We fixed a [somewhat similar problem](https://github.com/spring-projects/spring-boot/issues/32034) in 2.7.3. Let's see if we can do something similar in 2.7.x and later here.
