### ISSUE TITLE
Unable to Set Different Timeout for Different HTTP Interface methods

### ISSUE THREAD

**Issue by rajapanda15** [spring-projects/spring-boot#36069]
Unable to set different timeouts for different requests using HTTP Interface.

**Comment by wilkinsona** [comment]
I assume you are referring to [Spring Framework's HTTP Interface](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface) feature. If so, please raise a [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues).
