### ISSUE TITLE
Upgrade to Jetty 12

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36073]
Work in progress is available in https://github.com/wilkinsona/spring-boot/tree/jetty-12. Related Jetty issues with 12.0.0.beta2:

- https://github.com/eclipse/jetty.project/issues/9972 (inconvenient)
- https://github.com/eclipse/jetty.project/issues/9973 (blocker)
- https://github.com/eclipse/jetty.project/issues/9984 (blocker)

**Comment by Sineaggi** [comment]
Jetty 12 has been released! https://github.com/eclipse/jetty.project/releases/tag/jetty-12.0.0

**Comment by mikekuzak** [comment]
Hi, 

Does the spring-boot-starter for Spring Boot 3 work now with Jetty 12 ? 
I understand SP3 doesn't work with Jetty 11, because it's not supporting  EE10 (Servlet 6.0)

**Comment by wilkinsona** [comment]
> Does the spring-boot-starter for Spring Boot 3 work now with Jetty 12 ?

No, not yet. There are a significant number of breaking API changes in Jetty 12 to which Spring Boot will have to adapt. We hope to support Jetty 12 in Spring Boot 3.2 and Spring Framework 6.1.

> I understand SP3 doesn't work with Jetty 11, because it's not supporting EE10 (Servlet 6.0)

Spring Boot 3 works with Jetty 11 but you have to downgrade the Servlet API to 5.0. https://github.com/spring-projects/spring-boot/issues/33044 contains various ways to do that with both Maven and Gradle.

**Comment by joakime** [comment]
> > Does the spring-boot-starter for Spring Boot 3 work now with Jetty 12 ?
> 
> No, not yet. There are a significant number of breaking API changes in Jetty 12 to which Spring Boot will have to adapt. We hope to support Jetty 12 in Spring Boot 3.2 and Spring Framework 6.1.

Is there an active branch with this effort where I can participate in?

**Comment by wilkinsona** [comment]
Thanks, @joakime. https://github.com/spring-projects/spring-framework/issues/30698 is the next piece in the puzzle. I don't know if there's an active branch for that work.

**Comment by lzysuqianqiu** [comment]
Jetty 12.0.1 is GA now,any progress

**Comment by wilkinsona** [comment]
Thanks, @lzysuqianqiu. As you can see from [the branch](https://github.com/wilkinsona/spring-boot/tree/jetty-12) that's linked in this issue's description, we are already aware of that.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-framework/issues/30698 should land in Framework this week, allowing us to tackle this in 3.2.x.

**Comment by lzysuqianqiu** [comment]
ok, get it !

**Comment by kedaniilakis** [comment]
Is there already a releaseDate for SP 3.2?

**Comment by anbusampath** [comment]
> Is there already a releaseDate for SP 3.2?

@kedaniilakis  refer - https://github.com/spring-projects/spring-boot/milestones page
