### ISSUE TITLE
JacksonJsonpMapper bean autoconfigure condition bug

### ISSUE THREAD

**Issue by Pengfei-Lu** [spring-projects/spring-boot#36107]
# Spring Boot version
3.1.1

# Bug description
The autoconfigured [JacksonJsonpMapper bean](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/elasticsearch/ElasticsearchClientConfigurations.java#L52C22-L52C40) used to depend on a global `ObjectMapper` bean before SpringBoot version v3.0.3. 

After this [commit](https://github.com/spring-projects/spring-boot/commit/3af30b0a114be586e3cdfa0d49d5c5385753c511) introduced by SpringBoot version v3.0.3, the global `ObjectMapper` bean is not required when creating `JacksonJsonpMapper` bean.

However, the `JacksonJsonpMapper` bean creation condition `@ConditionalOnBean(ObjectMapper.class)` is not changed, resulting in `JacksonJsonpMapper` bean can be created only when ObjectMapper bean is present instead of the ObjectMapper class.

# Bug resolving solution
Change `@ConditionalOnBean(ObjectMapper.class)` to `@ConditionalOnClass(ObjectMapper.class)`

**Comment by wilkinsona** [comment]
Thanks, @Pengfei-Lu. If you intend to open a pull request, there's no need to open an issue as well.
