### ISSUE TITLE
Actuator endpoints issue in springboot3.*

### ISSUE THREAD

**Issue by Eddyzhang7** [spring-projects/spring-boot#36111]
Hi , I upgrade springboot2.0 to springboot3.0. 
I find a issue, in springboot2.0 , http://localhost:8080/contextpath/actuator is ok, but in springboot3.0 return **404**. When add dispatcherservletpath in url is ok ,for example , http://localhost:8080/contextpath/Dispatcherservletpath/actuator is ok.
I',m confused why url should add Dispatcherservletpath in springboot3.0

**Comment by wilkinsona** [comment]
As [requested earlier](https://github.com/spring-projects/spring-boot/issues/35426#issuecomment-1612619151), please provide a minimal sample that reproduces the behavior you are describing.

**Comment by Eddyzhang7** [comment]
Because of security， i can't provide sample , in application.yml
server:
  port: port
  servlet:
    context-path: /contextpatch
    
management:
  endpoints:
    enabled-by-default: false
    shutdown:
      enabled: false
    web:
      base-path: /actuator
      exposure:
        include: info, prometheus
        
In Springboot 2
contextpatch+servletpath+actuator-base-path is ok 
In Springboot 3
contextpatch+dispatcherservlet+actuator-base-path is ok

**Comment by wilkinsona** [comment]
It doesn't need to be your actual application. In fact, we'd prefer that it isn't. We just need the bare minimum of code and configuration that's required to reproduce the problem. Creating a new app on start.spring.io is often a good place to start.

**Comment by Eddyzhang7** [comment]
Thanks , Maybe actuator endpoints moved in Spring Boot 3.* , but i not find changelog

**Comment by wilkinsona** [comment]
No, they haven't moved. If you want us to spend any more time on this, please spend some time providing the requested sample application.

**Comment by Eddyzhang7** [comment]
Thanks
