### ISSUE TITLE
Outdated spring-boot-maven-plugin build-info documentation causing project builds to fail

### ISSUE THREAD

**Issue by bonii-xx** [spring-projects/spring-boot#36114]
With [this PR](https://github.com/spring-projects/spring-boot/pull/34761) the `maven.compiler.source` and `maven.compiler.target` properties were removed.

However, they are still used [in the build-info section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/reference/htmlsingle/#build-info) of the maven plugin, which means any project using the setup from the documentation got broken builds starting with 3.1.X.

Currently it's unclear what should be used instead (probably `java.version` or `maven.compiler.release`?) and the current documentation snippet causes builds to fail. Some migration info for anybody using this setup right now would probably also be helpful.

Documentation Pages with outdated info:

- https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/docs/asciidoc/build-info.adoc
- https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/docs/maven/build-info/pom.xml

**Comment by wilkinsona** [comment]
Thanks for spotting and reporting this, @bonii-xx. The need for a documentation update was [mentioned](https://github.com/spring-projects/spring-boot/pull/34761#issuecomment-1484159601) on the PR but it looks like it wasn't acted upon.

The [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#miscellaneous) mention that `maven.compiler.release` is now configured but not the removal of `source` and `target`. Once we've figured out what to use instead, we should update the release notes by adding a section to the [upgrade instructions](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#upgrading-from-spring-boot-30).

**Comment by mhalbritter** [comment]
I've updated the release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#switch-to-mavencompilerrelease
