### ISSUE TITLE
Property to set the package for `@EntityScan`

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3612]
Hi all,

It would be nice to have a property in "application.properties" to say which package the entity scan should look for.

Actually we have the annotation @EntityScan, or we can create a bean for "LocalContainerEntityManagerFactoryBean" where we can info the method setPackagesToScan.

So, my idea is to have something like this:
```
spring.jpa.entity-scan=com.xx.name
```

Let me know your thoughts!

**Comment by snicoll** [comment]
why would you want to make that configurable exactly?

**Comment by ofbizbrazil** [comment]
It would allow me to have an external configuration where all domains are located in application.

**Comment by snicoll** [comment]
I don't follow, sorry. Would you want to change the package containing your entities at runtime? That sounds super weird to me.

**Comment by jdbranham** [comment]
I have a similar use case where my starter library has required internal entities and repositories.
I've added a new configuration property that allows the sub-projects to define packages to scan, then when the starter builds the EM factory, it concatenates the internal packages. 

Example - 

application.properties - 
sprout.jpa.entity-packages=com.example.\*\*,com.example2.\*\*

Internal entity manager configuration -

    @Bean
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource,
                                                                       MultiTenantConnectionProvider multiTenantConnectionProviderImpl,
                                                                       CurrentTenantIdentifierResolver currentTenantIdentifierResolverImpl) {
    	**this.getEntityPackages().add(internalEntityPackages);
    	
        Map<String, Object> properties = new HashMap<>();
        properties.put(Environment.MULTI_TENANT, MultiTenancyStrategy.SCHEMA);
        properties.put(Environment.MULTI_TENANT_CONNECTION_PROVIDER, multiTenantConnectionProviderImpl);
        properties.put(Environment.MULTI_TENANT_IDENTIFIER_RESOLVER, currentTenantIdentifierResolverImpl);
        LocalContainerEntityManagerFactoryBean em = new LocalContainerEntityManagerFactoryBean();
        em.setDataSource(dataSource);
        **em.setPackagesToScan(this.getEntityPackages().toArray(new String[0]));
        em.setJpaVendorAdapter(jpaVendorAdapter());
        em.setJpaPropertyMap(properties);
        return em;
    }

https://github.com/savantly-net/sprout-platform/blob/v2.1/spring/sprout-spring-boot-starter/src/main/java/net/savantly/sprout/starter/JpaConfiguration.java
