### ISSUE TITLE
Add Order Constant for Filters that wrap the HttpServletRequest

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#3613]
The idea would be that any Filter that wraps the HttpServletRequest would be before this constant. Any Filter that relies on the wrapped HttpServletRequest would be after the constant. This would help in situations like https://github.com/grails/grails-core/issues/9137

**Comment by dsyer** [comment]
Can we start by making a list of Filters that we know might wrap the request? Spring Security's main filter is one. Also `HiddenHttpMethodFilter`. There are various filters in Spring (e.g. `*RequestLoggingFilter`) that we don't use routinely.

The `ErrorPageFilter` wraps the response, does that count? Spring Cloud wraps the request inside `Zuul`, does that count? Similar question for the multipart support in Spring - it wraps the request, but not in a `Filter`.

**Comment by dsyer** [comment]
OK, there's nothing we can do about the downstream components (like `DispatcherServlet` wrapping a request). All the filters added explicitly by Spring Boot now have order <= `FilterRegistrationBean.REQUEST_WRAPPER_FILTER_MAX_ORDER` (value 0).
