### ISSUE TITLE
Add runtime hints for MessageSource's message.properties

### ISSUE THREAD

**Issue by beckermarc** [spring-projects/spring-boot#36137]
While building a native image for a Spring Boot application that uses MessageSource and `message.properties` files I noticed that those are not registered as resources during the native image compilation by default.

After explicitly adding them to a `resource-config.json` file they were available in the native image. However I would have expected Spring Boot to provide a `RuntimeHintsRegistrar` implementation out-of-the-box that contributes these properties files automatically.

Is it reasonable to add such a `RuntimeHintsRegistrar` implementation?

**Comment by beckermarc** [comment]
I suggested a fix for this at least for the default MessageSource basename in #36682. I noticed that this approach is also taken in some other places, e.g. for schema.sql and data.sql. In my scenario this simple fix would be sufficient, as we use the defaults.

**Comment by wilkinsona** [comment]
Closing in favor of #36682. Thanks for the PR, @beckermarc!
