### ISSUE TITLE
Why spring-boot-dependencies has maven 3.0.2 as prerequisites?

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3614]
Documentation says that [Spring Boot is compatible with Apache Maven 3.2 or above](http://docs.spring.io/spring-boot/docs/1.3.0.M2/reference/htmlsingle/#getting-started-maven-installation) but [in `spring-boot-dependencies` I see that it requires Maven 3.0.2](https://github.com/spring-projects/spring-boot/blob/v1.3.0.M2/spring-boot-dependencies/pom.xml#L161)

Is it OK? May be we should update `prerequisites` tag?

**Comment by snicoll** [comment]
I think we are just being conservative about which version we support. I don't think there is anything wrong with Maven 3.1 but keeping the tool up to date is important. We can update the prerequisites tag for consistency.
