### ISSUE TITLE
springboot not have jetty configure?

### ISSUE THREAD

**Issue by flatychen** [spring-projects/spring-boot#3617]
why springboot not provide jetty configure like tomcat?

**Comment by snicoll** [comment]
Please don't use this tracker to ask questions (use Stackoverflow instead).

I am not sure I understand what "jetty configure" is. [Does this help?](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-jetty-instead-of-tomcat)

**Comment by flatychen** [comment]
er,,forgive my poor english ;
i mean spring boot not have embedded server configurtion of jetty ,so must use it in my code;
fell a little strange and confuse;

**Comment by snicoll** [comment]
We have support for Jetty, please read the link that I gave you.

**Comment by flatychen** [comment]
thank you for you commnet ,in fact,i mean the application.properies configuration for jetty,,,
