### ISSUE TITLE
Document that scripts for database initialization are optional by default and how they can be made mandatory

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#36176]
Hello

Pls, read the following SO post first

* [Why spring.sql.init.mode and spring.sql.init.platform are not throwing an error for missing sql scripts for MySQL?](https://stackoverflow.com/questions/76605614/why-spring-sql-init-mode-and-spring-sql-init-platform-are-not-throwing-an-error)

Could be consider to add a new _Application Property_ such as `spring.sql.init.missing.scripts` with enum values such as `ignore` (as default) `error` in case that the expected sql files are not found?

To be honest I expected receive a kind of error, but it did not happen. And if the comments on SO post are correct, it is not indicated at [9.3. Initialize a Database Using Basic SQL Scripts](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts)

Thanks for your understanding

**Comment by wilkinsona** [comment]
We probably need to document this better. You can make the scripts mandatory by configuring `spring.sql.init.schema-locations` and `spring.sql.init.data-locations` with values that don't use the `optional:` prefix.

**Comment by manueljordan** [comment]
Thanks for the feedback

Correct, I have confirmed that `spring.sql.init.schema-locations` and `spring.sql.init.data-locations` makes the scripts files mandatory

I have confirmed that `optional:` makes the scripts files optional, it was tested when the file scripts do not exist as follows

``` 
spring.sql.init.schema-locations=optional:/com/manuel/jordan/mysql/v2/schema-mysqlx.sql
spring.sql.init.data-locations=optional:/com/manuel/jordan/mysql/v2/data-mysqlx.sql
```

About either `optional` or `:optional`, it is not mentioned at [9.3. Initialize a Database Using Basic SQL Scripts](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts)

Just as an observation, take in consideration in indicate explicitly if the `classpath` prefix is mandatory or not, I have tested with and without this prefix and the app works too. This test was accomplished even for _with_ and _without_ a jar execution, I mean, through `mvn spring-boot:run` and `java -jar` respectively - therefore 4 scenarios. 

* with `classpath` for not jar app execution
* with `classpath` for jar app execution
* without `classpath` for not jar app execution
* without `classpath` for jar app execution

So theoretically at a first glance `classpath` is not mandatory, but ... according with this comment (written by you) in the following post:

* [spring.sql.init.schema-locations Not Working](https://stackoverflow.com/questions/71607122/spring-sql-init-schema-locations-not-working#comment126560215_71607122)

it seems is mandatory. A clarification about your comment for the Reference documentation is valuable for the community.
As usual I use the `classpath` prefix.

Thanks for your understanding

**Comment by manueljordan** [comment]
Btw the `optional:` prefix does not appear for both Application Properties as follows

![image](https://github.com/spring-projects/spring-boot/assets/2552795/92e600be-91e3-4f28-9922-fa1f92d737bc)

and

![image](https://github.com/spring-projects/spring-boot/assets/2552795/59523182-4dbb-4d2b-9a14-e9abd0ae7968)

Not sure if is related with SB or with STS4 ...

**Comment by wilkinsona** [comment]
That's a tooling issue. There's no way for the tooling to know what prefixes will work as it depends on the resource loader and any protocol resolvers. `optional:` will always work as it's a feature of `AbstractScriptDatabaseInitializer` rather than resource resolution.

**Comment by manueljordan** [comment]
Thanks for confirmation, I am going to report this situation to STS4
