### ISSUE TITLE
Is there any way to configure custom data source pool in application.properties

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#3619]
For instance, I prefer bonecp, can I configure without java code?

**Comment by snicoll** [comment]
Please don't use this tracker to ask questions (use stackoverflow for that). The supported connection pools are [defined in the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connect-to-production-database). We don't support bonecp out-of-the-box.
