### ISSUE TITLE
Add property to configure base time unit for Micrometer OTLP registry

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-projects/spring-boot#36200]
Micrometer added a new property to its OTLP registry to enable configuring the base time unit, see: https://github.com/micrometer-metrics/micrometer/issues/3870. This should be released in `1.12.0-M1` (already available in `1.12.0-SNAPSHOT`).

We should add property support for this in Boot too.
Also related: https://github.com/spring-projects/spring-boot/issues/36188

**Comment by snicoll** [comment]
Superseded by PR #36393
