### ISSUE TITLE
Update Spring Framework documentation links

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#36241]
With the move to Antora, we now have redirects happening for all our Spring Framework documentation links.

**Comment by snicoll** [comment]
Unfortunately, we can't make progress as there isn't a versioned version of each feature release. 

This works: https://docs.spring.io/spring-framework/reference/6.1/
This doesn't (at the moment): https://docs.spring.io/spring-framework/reference/6.0/

paging @rwinch for visibility.

**Comment by snicoll** [comment]
I've created https://github.com/spring-projects/spring-framework/issues/31018

**Comment by mhalbritter** [comment]
State right now:

* https://docs.spring.io/spring-framework/reference/6.0/ redirects to http://docs.spring.io/spring-framework/reference/
* http://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/ doesn't redirect
* http://docs.spring.io/spring-framework/reference/6.1/ doesn't redirect
* http://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/ doesn't redirect

I guess as soon 6.1 is GA, http://docs.spring.io/spring-framework/reference/6.1/ will become a redirect, while https://docs.spring.io/spring-framework/reference/6.0/ stops being a redirect.

**Comment by mhalbritter** [comment]
The links we have in our 3.1.x documentation have a different redirect. E.g. https://docs.spring.io/spring-framework/docs/6.0.13/reference/html/ returns a HTTP 200, but with a small html page which uses JavaScript to do the redirect to https://docs.spring.io/spring-framework/reference/. We don't link to such pages in the 3.2.x documentation anymore.

**Comment by mhalbritter** [comment]
I've gone through all the Spring Framework links and updated them to the Antora equivalent.
