### ISSUE TITLE
Add configuration property for GraphQL Schema Mapping Inspection

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-boot#36252]
In Spring GraphQL you can do schema mapping inspection:
https://docs.spring.io/spring-graphql/docs/current/reference/html/#execution.graphqlsource.schema-mapping-inspection

I have to write some Java code myself to enable this:
```java
GraphQlSource.Builder builder = ...

builder.schemaResources(..)
        .inspectSchemaMappings(report -> {
            logger.debug(report);
        })
```

Could you add a setting to application.properties which does this for me, for example:
**spring.graphql.schema.mapping.inspection=debug**
In this setting **debug** refers to logger.**debug**(.
It coud also be none (default), info, error.

**Comment by bclozel** [comment]
To better align with other properties, we went with the following arrangement:
* a new `spring.graphql.schema.inspection.enabled`
* this property is enabled by default
* the report is logged at the INFO level
