### ISSUE TITLE
Provide a `RestClientBuilderConfigurer` for apply Boot's defaults to a custom `RestClient.Builder`

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36265]
Our auto-configuration for `RestTemplateBuilder` provides a `RestTemplateBuilderConfigurer` to easily apply Boot's defaults when defining a custom `RestTemplateBuilder`. Would should consider an equivalent for `RestClient.Builder`, although we only apply `RestClientCustomizer` beans to the builder at the moment so the need for it doesn't appear to be that large.

**Comment by mhalbritter** [comment]
There's now a `RestClientBuilderConfigurer` which can be used to apply Boots defaults to every `RestClient.Builder`.
