### ISSUE TITLE
Provide Trace ID in Response Header via configuration

### ISSUE THREAD

**Issue by neiser** [spring-projects/spring-boot#36272]
When using Spring Boot in larger teams, it's really desirable to expose the Trace ID in the response headers. This way, debugging problems becomes easier as the person experiencing the problem (using a client such as `curl`) can include the Trace ID easily and tell the responsible developer exactly how to find relevant logs.

Currently, this can be achieved by defining the following `@Configuration` for WebMVC:
```
@Configuration
public class TracingConfiguration implements WebMvcConfigurer {

    private final SpanContextSupplier spanContextSupplier;

    public TracingConfiguration(SpanContextSupplier spanContextSupplier) {
        this.spanContextSupplier = spanContextSupplier;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new HandlerInterceptor() {
            @Override
            public void postHandle(HttpServletRequest request, HttpServletResponse response, Object handler, ModelAndView modelAndView) {
                response.addHeader("X-TraceId", spanContextSupplier.getTraceId());
            }
        });
    }
}
```

IMHO, it would be nice feature if this could be enabled easily by setting the `X-TraceId` header name value via configuration, such as
```
spring:
  # configuration path completely made up!
  observability:
    trace-id-response-header-name: X-TraceId
```
Which would expose the Trace Id if the header name is non-empty. And of course, this should work independent of the Web Framework in use (WebMVC/WebFlux/...).

**Comment by jonatan-ivanov** [comment]
I had been doing something similar for years in production and I'm still doing something else but similar in [demo apps](https://github.com/jonatan-ivanov/teahouse/blob/7883642f7568991934c91990a547dd815e646fae/core/src/main/java/org/example/teahouse/core/error/CommonExceptionHandler.java#L50). I find/found such a feature useful. 

On the other hand, I'm not sure this should be implemented in Boot only, I think both Micrometer Tracing and Spring Framework (where the instrumentation itself lives) can add some support for this and Boot can auto-configure it.

@marcingrzejszczak @bclozel What do you think?

**Comment by bclozel** [comment]
The filter only depends on the observation API. Can we get the traceId with that API only?

**Comment by marcingrzejszczak** [comment]
> The filter only depends on the observation API. Can we get the traceId with that API only?

No, we can't. TraceId is a Micrometer Tracing thing. There would have to be a boot based config that given tracing is on the classpath would add some logic that would add the fields that are defined by the Tracing's `Propagator` interface to the response.

**Comment by neiser** [comment]
@jonatan-ivanov @marcingrzejszczak I don't quite see why using `SpanContextSupplier` is not an option here? Anyhow, I think we need issues in upstream projects, right? Will you open them?
