### ISSUE TITLE
Improve documentation to describe how `@EntityScan` and `@Enable…Repositories` can be used to tune scanning

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#36282]
In Spring Boot about JPA and Spring Data JPA, exists in the current reference documentation the [JPA and Spring Data JPA section](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.sql.jpa-and-spring-data), where it has two sub-sections as follows:

* [Entity Classes](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.sql.jpa-and-spring-data.entity-classes)
* [Spring Data JPA Repositories](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.sql.jpa-and-spring-data.repositories)

These 2 sections have the following content respectively:

> By default, all packages below your main configuration class (the one annotated with `@EnableAutoConfiguration` or `@SpringBootApplication`) are searched

and

> If you use auto-configuration, repositories are searched from the package containing your main configuration class (the one annotated with `@EnableAutoConfiguration` or `@SpringBootApplication`) down

For Spring Boot 3.1.1 working with Spring Data JPA the `@EntityScan` and `@EnableJpaRepositories` annotations are _not_ necessary to be declared explicitly, only if the packages where the Entities and Repositories are defined, reside within the _package containing the main configuration class_.  I think it should be declared explicitly for each documentation section, according the respective annotation.

Of course, if any of these types (Entities or Repositories) are defined in a package different of the  _package containing the main configuration class_ then the respective annotation is mandatory to be declared. Other scenario would be if for `@EnableJpaRepositories`  is need it define some extra configuration, it such as  [repositoryImplementationPostfix](https://docs.spring.io/spring-data/data-jpa/docs/current/api/org/springframework/data/jpa/repository/config/EnableJpaRepositories.html#repositoryImplementationPostfix())

Therefore an expansion about when to declare or not these annotations to the current Reference Documentation would be valuable.

Thanks for your understanding

**Comment by wilkinsona** [comment]
We already mention `@EntityScan` but there's no mention at all of `@EnableJpaRepositories`. That's inconsistent as `@EnableJdbcRepositories` is mentioned. We should address that at the least.
