### ISSUE TITLE
Unable to turn off logging for a particular package

### ISSUE THREAD

**Issue by shanman190** [spring-projects/spring-boot#3628]
When configuring logging using Spring Boot's [LoggingApplicationListener](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/LoggingApplicationListener.java) and SnakeYAML, you're not able to turn off logging for a specific package. This is because of how SnakeYAML handles the word 'OFF' and represents that value as a boolean instead.

My suggestion would be to add some code to the [LoggingApplicationListener](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/LoggingApplicationListener.java) around setting the LogLevel to check if the level comes in as a String with the value of false and act as if it means 'OFF'

**Comment by snicoll** [comment]
For the record, we did something similar in #2737

**Comment by dsyer** [comment]
...and so the same workaround applies (you need to quote the value).
