### ISSUE TITLE
JolokiaMvcEndpoint endpoints.jolokia.path regex and functionality very limited

### ISSUE THREAD

**Issue by rubesMN** [spring-projects/spring-boot#3629]
I'm trying to set the Jolokia path endpoint.  I need to do this because I'm unable to use management.context-path because I'm doing this for our Eureka Server and Eureka doesn't support a separate property for the heartbeat context (I have to use server.context).   

My infrastructure for our firewall forces me to use a context such as "/diagnostics/admin", but the weird regex doesn't let me do that:

    @Pattern(regexp = "/[^/]*", message = "Path must start with /")
    private String path;

"/diagnostics" works, but not "/diagnostics/admin"

**Comment by dsyer** [comment]
I think I understand what you mean by the regex being limiting (not limited). But what was the rest of the issue (the "functionality")? We only wrap the existing Jolokia functionality, we don't extend it.

**Comment by rubesMN** [comment]
The reference to "functionality" was only in reference to the limit the regex was enforcing.   The management.contextPath is indeed irrelevant.

**Comment by dsyer** [comment]
I guess this is fixed then.
