### ISSUE TITLE
When virtual threads are enabled, auto-configure Spring Pulsar to use them

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36347]
Details are TBD (https://github.com/spring-projects/spring-pulsar/issues/414) but it's likely to be a configuration setting on `ConcurrentPulsarListenerContainerFactory`

**Comment by vpavic** [comment]
Is this still blocked and/or should it be superseded by #37559?

**Comment by wilkinsona** [comment]
Thanks for the nudge, @vpavic. This is no longer blocked. I don't think it's superseded by #37559 as we can implement this without it (and I would prefer to do so as I'm not yet sold on the complexity introduced by #37559).
