### ISSUE TITLE
Introduce 'value' attribute in @SpringApplicationConfiguration

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#3635]
Issue #3400 retrofitted `@SpringApplicationConfiguration` to use the new `@AliasFor` annotation from Spring Framework 4.2 to introduce explicit annotation attribute overrides. 

Due to the opinionated view of Spring Boot with regard to favoring `@Configuration` classes over XML and Groovy configuration, `@SpringApplicationConfiguration` can benefit from yet another feature of `@AliasFor`. Namely, `@SpringApplicationConfiguration` can introduce a new `value` attribute that is an attribute override for the `classes` attribute in `@ContextConfiguration`. 

Proposed change:

	// ...
	public @interface SpringApplicationConfiguration {

		/**
		 * @return the context configuration classes
		 * @see ContextConfiguration#classes
		 * @see #classes
		 */
		@AliasFor(annotation = ContextConfiguration.class, attribute = "classes")
		Class<?>[] value() default {};

		// ...
	}

Consequently, if a Spring Boot integration test only needs to declare a configuration class, the declaration can be simplified as follows: `@SpringApplicationConfiguration(SampleApplication.class)`.

**Comment by snicoll** [comment]
:+1:

**Comment by sbrannen** [comment]
I unfortunately made the proposal too soon...

Declaring multiple annotation attribute overrides for the same attribute in a meta-annotation is _not_ supported in Spring Framework 4.2.0. The reason is that the merge algorithm in `MergedAnnotationAttributesProcessor` in `AnnotatedElementUtils` overwrites previous aliased values with subsequent aliased values, thereby letting the last one win -- which happens silently and is not intuitive.

**Comment by sbrannen** [comment]
The following is an alternative solution:

	// ...
	public @interface SpringApplicationConfiguration {

		@AliasFor("value")
		Class<?>[] classes() default {};

		@AliasFor("classes")
		Class<?>[] value() default {};

		// ...
	}

The above approach defines an explicit local alias pair between the `classes` and `value` attributes. In theory, this should have worked with Spring Framework 4.2.0; however, due to a bug it did not. This bug has already been fixed in [SPR-13325](https://jira.spring.io/browse/SPR-13325), and the use case has been tested in commit https://github.com/spring-projects/spring-framework/commit/e20b47c3bc424ac4fd30dd101e730c280681c3f1.

Thus, this approach can be used against recent 4.2.1 snapshots.

**Comment by snicoll** [comment]
Stuck again, see [SPR-13320](https://jira.spring.io/browse/SPR-13320)

**Comment by sbrannen** [comment]
ouch!  :disappointed: 

I'll look into it.

Thanks for bearing with me.

**Comment by sbrannen** [comment]
OK, the issue with empty arrays being considered nonexistent has been fixed in [SPR-13320](https://jira.spring.io/browse/SPR-13320).

Please let me know if the upcoming 4.2.1 snapshot now works in Spring Boot.

Thanks!

Sam

**Comment by sbrannen** [comment]
See also:

- [SPR-13351](https://jira.spring.io/browse/SPR-13351)
- [SPR-13352](https://jira.spring.io/browse/SPR-13352)

**Comment by snicoll** [comment]
@sbrannen we're good now, thanks.

**Comment by sbrannen** [comment]
Whew... that's a relief. Thanks for letting me know. :wink:

**Comment by sbrannen** [comment]
Awesome! 

Nice to see that in place. :smile:

**Comment by sbrannen** [comment]
By the way, I would also recommend updating the reference manual:

1. document that either `classes` or `value` (when used a single annotation element/attribute) can be used
2. update examples to use the implicit `value` attribute whenever `classes` was used as the sole attribute

**Comment by sbrannen** [comment]
Oh, yeah, I'd also add `@see #classes` and `@see #value` to the Javadoc for the respective attributes.
