### ISSUE TITLE
spring-boot-starter-validation has dependency hibernate-validator:8.0.0.Final which does not work

### ISSUE THREAD

**Issue by Stefan4112** [spring-projects/spring-boot#36357]
Recently added spring-boot-starter-validation to my project and it stopped starting. In stacktrace I found a problem with jboss logging and after some investigation I found that hibernate is the problem.

Dependency:
```
org.springframework.boot:spring-boot-starter-validation:3.1.1
\--- org.hibernate.validator:hibernate-validator:8.0.0.Final
```
I had to exclude hibernate-validator, because version 8 does not work. Then I added the version from release note:
```
org.hibernate.validator:hibernate-validator:6.2.5.Final
\--- jakarta.validation:jakarta.validation-api:2.0.2
```
Now it includes an old version of jakarta.validation-api... so I had to manually add jakarta.validation-api:3.0.2 to use annotations again.
It was very difficult to find the error because of the first error with jboss logging.

Please use working dependency version.

**Comment by wilkinsona** [comment]
As far as we know, there are no problems with Hibernate Validator 8.

Spring Boot 3.x requires at least Jakarta EE 9 (Bean Validation 3.0) which includes the `jakarta.validation.*` API. Hibernate Validator 6 does not meet this requirement as it uses Bean Validation 2.0 which is the `javax.validation` API. This is incompatible with Spring Framework 6 and Spring Boot 3's validation integration.

Unfortunately "does not work" doesn't allow us to diagnose the problem with Hibernate Validator 8. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by Stefan4112** [comment]
Sorry, I should have started with minimum example. Must have been something wrong in cache after working with build script in large project.
Everything working fine.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
