### ISSUE TITLE
Add Require HTTPS property

### ISSUE THREAD

**Issue by wgorder** [spring-projects/spring-boot#3637]
With the world moving to HTTPS everywhere, I wonder if a require-https property that activates a filter requiring HTTPS would make sense to add.  I typically add a filter like shown below to my apps.  Thoughts?

```
  @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
        throws IOException, ServletException
    {
        HttpServletRequest servletRequest = (HttpServletRequest) request;
        String forwardProtoHeader = servletRequest.getHeader("X-Forwarded-Proto");
        if ((null != forwardProtoHeader
            && forwardProtoHeader.equalsIgnoreCase("https")) || request.isSecure())
        {
            chain.doFilter(request, response);
        }
        else
        {
            String redirectTarget = UriComponentsBuilder
                .fromHttpUrl(servletRequest.getRequestURL().toString()).scheme("https").build()
                .toUriString();
            ((HttpServletResponse) response).sendRedirect(redirectTarget);
        }
    }

```

**Comment by dsyer** [comment]
A filter that requires HTTPS is also a bit old-fashioned because it doesn't provide much security - users can still send you sensitive data over HTTP, you just won't process it (so you annoy your users without making them much more secure). If you need to be secure you can use HSTS with Spring Security (it's the default anyway, and you can configure it with `security.headers.hsts`) and/or `security.requireSsl=true`.

**Comment by wgorder** [comment]
@dsyer actually that filter redirects them kind of how when I go to http://mail.google.com I am automatically redirected to https://mail.google.com so I don't understand how it "annoys" users.  That said your other point is well taken.  However if memory serves me correctly the spring security stuff does not factor in the X-Forwarded-Proto header and therefore does not work in many cloud environments where SSL termination happens at the load balancer.  Feel free to correct me if I am wrong, or maybe I should be asking for an enhancement there...

**Comment by wgorder** [comment]
NVM I see that the HSTS does indeed seem to do what I want, I will give that a try..  Thanks.
