### ISSUE TITLE
Update to Liquibase 4.23.0

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#36377]

**Comment by wilkinsona** [comment]
I [tried it with some excludes for 4.22.0](https://github.com/spring-projects/spring-boot/commit/1e17d8eeeac091d625b6853f0c517dcd9b218c65) but then I hit https://github.com/liquibase/liquibase/issues/4135 again and prohibited the upgrade instead. I also see now that I made a bit of a mess of it as I left the excludes in place. That aside, I think we'll just have to do the same here as https://github.com/liquibase/liquibase/issues/4135 is still open so I assume 4.22.0 will break.

**Comment by snicoll** [comment]
I've also created an issue for the activation-api in the hope they can remove that on their side: https://github.com/liquibase/liquibase/issues/4487

**Comment by wilkinsona** [comment]
Thanks to https://github.com/liquibase/liquibase/pull/4282, 4.23.0 works.
