### ISSUE TITLE
Spring Boot Starter ElasticSearch: Is there any support for an embedded Kibana instance?

### ISSUE THREAD

**Issue by victor-ferrer** [spring-projects/spring-boot#3638]
Hi,

Question: I was wondering if there is any chance of launching an embedded Kibana instance in the same way that an ElasticSearch node is launched when including the spring-boot-starter-data-elasticsearch dependency in my Spring-Boot project.

Moreover. I have looked for a ServletRegistrationBean that could do the trick (like the one used for the H2 console), but nothing seems to be out there.

I raised this question in StackOverflow without any success: 
http://stackoverflow.com/questions/31614586/elk-watcher-support-in-spring-boot-starter-data-elasticsearch

So, is there any chance for accomplishing this? In that case, it would be great if you could please update/upgrade the corresponding documentation.

Thanks,
Victor

**Comment by ptahchiev** [comment]
+1 For this one.

**Comment by wilkinsona** [comment]
Kibana appears to only be available as an OS-specific download or package. Given this I can't really see how Spring Boot could easily add support for embedding it. Have I missed something?

**Comment by wilkinsona** [comment]
It's also a Node app so I really can't see how it can be embedded into Spring Boot. If I'm wrong, please provide some information on how Kibana can be used in a non-Node environment and we can re-open this issue.

**Comment by victor-ferrer** [comment]
Thanks @wilkinsona.
