### ISSUE TITLE
the FIRST api call takes TOO LOOOOOOOONG when the project is deploying by a WAR package via springboot built-in tomcat

### ISSUE THREAD

**Issue by yqji** [spring-projects/spring-boot#36408]
the FIRST api call takes TOO LOOOOOOOONG when the project is deploying by a WAR package via built-in tomcat, but this shit problem is dismissed when I deploying by a JAR package.

I'm soooooooo CONFUSED, help me pls.

**Comment by wilkinsona** [comment]
Duplicates #36407.
