### ISSUE TITLE
spring.threads.virtual.enabled - Configure Virtual Thread based AsyncTaskExecutor

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects/spring-boot#36419]
Is there any reason why `spring.threads.virtual.enabled` doesn't setup a virtual thread based `AsyncTaskExecutor`, as suggested in https://spring.io/blog/2022/10/11/embracing-virtual-threads?

```
@Bean(TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME)
public AsyncTaskExecutor asyncTaskExecutor() {
  return new TaskExecutorAdapter(Executors.newVirtualThreadPerTaskExecutor());
}
```

@mhalbritter Do you have any input on the matter?

Thanks for adding support for virtual threads!

**Comment by NicklasWallgren** [comment]
Maybe a duplicate of https://github.com/spring-projects/spring-boot/issues/35710

**Comment by snicoll** [comment]
As you found out, we already have an issue for this.
