### ISSUE TITLE
Add 'observation-enabled' properties for RabbitMQ

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#36451]
Spring AMQP does not enable Observation by default; if a user only wants Micrometer timers, it is better to use the legacy timers provided by the project, which detects the presence (or not) of a `MeterRegistry` bean.

However, if a user wants tracing, the `observationEnabled` property must be set to true; it would be more convenient if Boot provided this as an auto config property.

Furthermore, if Boot can detect that tracing is enabled (not just timers via Observation), then the properties could default to `true`, if not set by the user. If no such detection is possible, then the properties should remain at their default, false.

The `observationEnabled` property is available on `BaseRabbitListenerContainerFactory` and `RabbitTemplate`.

**Comment by mhalbritter** [comment]
Changes are here: https://github.com/mhalbritter/spring-boot/tree/mh/36451-add-observation-enabled-properties-for-rabbitmq

**Comment by scottfrederick** [comment]
@sirlatrom We only do bug fixes and dependency upgrades in patch releases, so this enhancement will not be backported.
