### ISSUE TITLE
PropertiesLauncher and loader.path property issue

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3645]
When I created an app. with ZIP layout, I move the lib/ folder outside the jar file and try to run this way. There are some weird behaviors that I see

- I'm setting the ```loader.path=lib/``` in the ***application.properties*** file inside the jar, and it's working.
- I'm moving the ***application.properties*** file outside the jar, and it's not working, raising 
```
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethod(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContext
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
```

 - I'm trying to set the property like ```-Dloader.path=lib/``` but again it's not working, same error above.
 - I put the ***application.properties*** inside the jar file, and created another one outside the jar, putting other properties in it, and it worked again, read the properties from application.properties file outside the jar file successfully..

Is this expected behavior ?

**Comment by gokhanoner** [comment]
Seems that it's not an issue, so no one ever replied after 14 days.

**Comment by wilkinsona** [comment]
Apologies for the lack of reply. It's simply an indication of how busy we all are, nothing more. If it definitely wasn't an issue, a member of the team would have closed the issue with a comment explaining why.

**Comment by dkirrane** [comment]
I've tried this in my `application.properties` bundled inside my jar and get same `java.lang.ClassNotFoundException `

`loader.path=lib/,target/lib-provided/`

where `lib` is folder bundled inside my jar and `target/lib-provided/ `is a folder in my Maven build directory with some extra _external_ jars. I've also tried full path like this

`loader.path=lib/,C:/my-spring-boot-app/target/lib-provided/`

**Comment by Junior-Sousa** [comment]
I think I'm having a similar issue, I using spring boot 1.3.3. In my case I'm working with a war project and when I try to use a external library a also got the ClassNotfoundException error.

I tried to add the loader.path point to a directory where the external jar is stored and also used the command -Dloader.path but none of them worked.

**Comment by prokod** [comment]
Hi all, I have the same issue with spring boot 1.3.3. I see that this issue is open for long time now, is `PropertiesLauncher` to be deprecated or is it not being used much ? 
@wilkinsona could you please comment on that one. Is there some know work around?

Thx

**Comment by wilkinsona** [comment]
The latter, I believe.

If the issue is important to you, a minimal sample project that reproduces the behaviour that you are seeing would be a big help.

**Comment by prokod** [comment]
I was digging around and I would like to divide my findings to two:
### The reason why in my case it seems like loader.path is 'not respected'
Certain jars are not 'digest-able' by `LaunchedURLClassLoader`. When trying spark-assembly jar, it wasn't searchable by the class loader, throwing `ClassNotFoundException` while using the small jars that contributes to this assembly instead solved the issue. I do not know yet if it is related to ZIP64 vs ZIP32 or to those restrictions mentioned in spring boot docs [E.5.1 Zip entry compression](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-property-launcher-features)
### Some general points I gathered while poking around which from user perspective could be changed to be more user friendly (valid for version 1.3.3 so it might not hold any more in latest version): 
- `getClassPathArchives` is just skipping wrong path that is being delegated to it from loader.path. So if someone by mistake added to the paths a non existing path he would not know about it in cases where this class will not have any Logger associated with it. IMO fast failing will be better approach, but I might be wrong as I might not see the whole picture.
- This class `PropertiesLauncher` is called first even before Logging is being initialised, for instance in my case where I use logback and spring-boot-starter-logging. So it means this class is not emitting any useful logs that can lead you to mistakes you might have done in configuration.
- 'Invalid' jar files from `LaunchedURLClassLoader` perspective being added to the class path using `loader.path` should also trigger some exception failing fast the running of the app, IMO.

**Comment by wilkinsona** [comment]
> I do not know yet if it is related to ZIP64 vs ZIP32 or to those restrictions mentioned in spring boot docs E.5.1 Zip entry compression

When the latter is encountered, an exception is thrown and it makes it impossible to read _any_ nested jars so I doubt it's that. I suspect it's the former; see https://github.com/spring-projects/spring-boot/issues/2895.

> getClassPathArchives is just skipping wrong path that is being delegated to it from loader.path … IMO fast failing will be better approach, but I might be wrong as I might not see the whole picture.

I believe the current behaviour matches that of the JDK. It will ignore non-existent paths that are passed in via `-classpath`.

> This class PropertiesLauncher is called first even before Logging is being initialised

That has to be the case. The launcher is responsible for creating the class loader that will load the logging system. For this reason, `PropertiesLauncher` writes logs to System.out when `loader.debug` is true.

> 'Invalid' jar files from LaunchedURLClassLoader perspective being added to the class path using loader.path should also trigger some exception failing fast the running of the app, IMO.

This matches the JDK's behaviour. For example, if you point `-classpath` to a corrupted jar file it doesn't fail. I can see why that behaviour isn't ideal in this case, but I'm reluctant to diverge even assuming it's possible to do so.

**Comment by wilkinsona** [comment]
> I'm moving the application.properties file outside the jar, and it's not working

If you move `application.properties` to a non-standard location, then you need to use `loader.config.location` to tell the launcher where to look. For example `-Dloader.config.location=./application.properties` to look in the current working directory.

> I'm trying to set the property like -Dloader.path=lib/ but again it's not working, same error above.

I would guess that your command line was malformed. `java -jar foo.jar -Dloader.path=lib/` won't work as anything after `-jar foo.jar` is ignored. For example, you should use `java -Dloader.path=lib/ -jar foo.jar` instead.

> I put the application.properties inside the jar file, and created another one outside the jar, putting other properties in it, and it worked again, read the properties from application.properties file outside the jar file successfully..

This sound like standard behaviour for externalised configuration. For general properties (as opposed to those that are property launcher-specific), `application.properties` inside the jar and outside will be used, with the latter taking precedence. See the [documentation on externalised configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) for further details.
