### ISSUE TITLE
Add observationEnabled properties for Apache Kafka

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#36452]
Spring for Apache Kafka does not enable Observation by default; if a user only wants Micrometer timers, it is better to use the legacy timers provided by the project, which detects the presence (or not) of a `MeterRegistry` bean.

However, if a user wants tracing, the `observationEnabled` property must be set to true; it would be more convenient if Boot provided this as an auto config property.

Furthermore, if Boot can detect that tracing is enabled (not just timers via Observation), then the properties could default to `true`, if not set by the user. If no such detection is possible, then the properties should remain at their default, false.

The `observationEnabled` property is available on `ContainerProperties` and `KafkaTemplate`.

**Comment by tspoeri** [comment]
Very handy enhancement that I am also missing. It is quite annoying to write a manual configuration just because of that setting when the rest can be configured through auto configuration.

**Comment by scottfrederick** [comment]
Closing in favor of #38057
