### ISSUE TITLE
-Drun.jvmArguments has no effect if jvmAguments are specified in the pom.xml

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-boot#3646]
Hello,

in my spring-boot-maven-plugin declaration I specify the following jvmArguments:
````
                <configuration>
                    <jvmArguments>-Xms512m -Xmx2048m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000</jvmArguments>
                    <addResources>false</addResources>
                </configuration>
````

Now I run my project using `mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=server"` and this has no effect whatsoever - the profile is not used at all. If I comment the jvmArguments in the `pom.xml` then the correct profile is used.

**Comment by snicoll** [comment]
This is weird, I would have expected the opposite. By the way, forking is disabled by default so I wouldn't expect this to work _at all_. Don't you have a warning that states something like

> Fork mode disabled, ignoring JVM argument(s) 

(unless you use Spring loaded or something that would flip the fork attribute automatically).

**Comment by ptahchiev** [comment]
Yeah I'm using spring-loaded.

**Comment by snicoll** [comment]
This is quite surprising but I have the exact same behaviour with an official Maven plugin (the compiler plugin for the record) so I am afraid there's nothing we can do here. You may want to report that to the Maven tracker.
