### ISSUE TITLE
Improve transitive dependencies of org.springframework.boot:spring-boot-testcontainers

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-boot#36478]
### Current behaviour with Spring Boot 3.1

When I generate a project from spring initalizr and request that test container support be added I end up with following classpath 

```
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.boot:spring-boot-testcontainers'
  testImplementation 'org.testcontainers:junit-jupiter'
}
```

I expected to see something like `org.springframework.boot:spring-boot-testcontainers` but the presence of  `org.testcontainers:junit-jupiter` is surprising given that junit jupiter is the default for spring boot 3.1, I thought it would automatically be pulled in.

When I examined the dependency tree in my IDE i noticed that  `org.springframework.boot:spring-boot-testcontainers` was pulling in junit 4 which something I don't want in the classpath and the `org.springframework.boot:spring-boot-starter-test` has exclusions for junit4.

<img width="1054" alt="Screenshot 2023-07-20 at 10 01 48 AM" src="https://github.com/spring-projects/spring-boot/assets/945207/c1a37129-b46d-43f9-92ed-388ff8e54a13">

You can find the source code for project where I noticed this behaviour at https://github.com/asaikali/docker-compose-postgres

### Suggested Improvements

1. `org.springframework.boot:spring-boot-testcontainers` should add `org.testcontainers:junit-jupiter` as a transitive dependency
2.   `org.springframework.boot:spring-boot-testcontainers` should exclude junit4 from its transitive dependencies 

I believe implementing the above enhancements  makes the dependency handling more consistent with the rest of spring boot's handling of test dependencies.

**Comment by mhalbritter** [comment]
> org.springframework.boot:spring-boot-testcontainers should add org.testcontainers:junit-jupiter as a transitive dependency

Say I'm only using "Testcontainers at development time", then I don't need the `org.testcontainers:junit-jupiter` dependency, right? Making it a dependency of `org.springframework.boot:spring-boot-testcontainers` would pull it in, even when I don't need it.

**Comment by wilkinsona** [comment]
We discussed this today and agreed that, for the reasons above, we don't want to make the suggested changes. Thanks anyway.

**Comment by asaikali** [comment]
Thanks for the explanation folks. This makes sense to me now.
