### ISSUE TITLE
After migrating to spring boot 3.1.2 application failed to start

### ISSUE THREAD

**Issue by paweleg** [spring-projects/spring-boot#36481]
Hi!
I have some problem after migrating to spring boot 3.1.2. On 3.1.1 application was started.

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'preFilterAuthorizationAdvisor', defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Regards,
PG

**Comment by wilkinsona** [comment]
This sounds like it may be a bug in Spring Security but it's hard to tell without some more information. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by bratkartoffel** [comment]
Just stumbled on this issue in my project too.
- https://github.com/bratkartoffel/security-jwt-examples
- Run the tests for the `starter-cookies-jakarta` module

**Comment by wilkinsona** [comment]
Thanks, @bratkartoffel. As suspected, this is a regression in Spring Security.

```groovy
ext {
    set("spring-security.version", "6.1.1")
}
```

With the above added to `starter-cookies-jakarta/build.gradle` the tests pass:

```
gradle starter-cookies-jakarta:test

> Task :starter-cookies-jakarta:test

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
eu.fraho.spring.example.test.starter_cookies.TestCookiesApplication

  Test testPrivateGarbageTokenCookie() PASSED
  Test testPrivateWithTokenCookie() PASSED
  Test testPrivateGarbageTokenHeader() PASSED
  Test testPrivateWithTokenHeader() PASSED
  Test testPublicWithTokenCookie() PASSED
  Test testPublicWithTokenHeader() PASSED
  Test testRefreshCookieFlow() PASSED
  Test testPublicGarbageTokenCookie() PASSED
  Test testPublicGarbageTokenHeader() PASSED
  Test testRefreshEnabled() PASSED
  Test testPrivateNoToken() PASSED
  Test testPublicNoToken() PASSED
2023-07-21T08:31:52.941+01:00  INFO 92061 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-07-21T08:31:52.943+01:00  INFO 92061 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-07-21T08:31:52.945+01:00  INFO 92061 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

SUCCESS: Executed 12 tests in 6.9s


BUILD SUCCESSFUL in 9s
4 actionable tasks: 1 executed, 3 up-to-date
```

Please report this to [the Spring Security project](https://github.com/spring-projects/spring-security).
