### ISSUE TITLE
boot2.7.X upgrade Jedis version to 3.10.0

### ISSUE THREAD

**Issue by ahgaoyong** [spring-projects/spring-boot#36487]
boot2.7.X:

Can we upgrade Jedis version to 3.10.0?

thanks!

**Comment by mhalbritter** [comment]
From here: https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies

> Spring Boot provides managed dependencies for many third-party libraries. These libraries are upgraded only at the patch level for any given Spring Boot patch release. Minor and major version upgrades of third-party libraries are only applied in Spring Boot minor or major releases.

Boot 2.7 uses 3.8.0, so no, we won't upgrade to 3.10.0 in the 2.7.x line.
