### ISSUE TITLE
JndiDataSourceAutoConfiguration creates DataSource that is disposable

### ISSUE THREAD

**Issue by soldierkam** [spring-projects/spring-boot#3648]
DataSource may implement AutoClosable (http://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/tomcat/dbcp/dbcp2/BasicDataSource.html). Setting empty String does not prevent from closing the DataSource.

**Comment by snicoll** [comment]
This was a Spring Framework issue [that got fixed in Spring Framework 4.2.RC1](https://jira.spring.io/browse/SPR-13022).
