### ISSUE TITLE
PayloadApplicationEvent seems broken in spring 2.7.14

### ISSUE THREAD

**Issue by Jojoooo1** [spring-projects/spring-boot#36501]
After upgrading to Spring Boot [v2.7.14](https://github.com/spring-projects/spring-boot/releases/tag/v2.7.14), we started to receive many errors logs. After investigating we discover that when we were trying to publish a event using `applicationEventPublisher.publishEvent` for an entity, it started to break all our function using PayloadApplicationEvent.

**Comment by wilkinsona** [comment]
`PayloadApplicationEvent` is part of Spring Framework and last changed 3 years ago in its 5.3.x branch so it's not clear why a problem would arise now. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by Jojoooo1** [comment]
It seems we had a bug inside our PayloadApplicationEvent and it was failing silently for spring  v2.7.13 but not  v2.7.14.

**Comment by wilkinsona** [comment]
Thanks for following up.
