### ISSUE TITLE
reloadable properties

### ISSUE THREAD

**Issue by krishnakumarp** [spring-projects/spring-boot#3650]
Does spring boot support runtime changes to properties in *.yml and *.properties files? Is there any plan to add this in the near future? Something similar to ReloadableResourceBundleMessageSource. 

Thanks.

**Comment by snicoll** [comment]
Please do not cross post, I replied on [stackoverflow](http://stackoverflow.com/questions/31769462/spring-boot-application-yml-properties-change-at-runtime) already.
