### ISSUE TITLE
Add BootMockMvcConfigurerAdapter

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#3653]
It would be nice to have a `BootMockMvcConfigurerAdapter` that properly sets up the `MockMvc` instance with the Spring Boot configuration. For example, it would add all of the `Filter` instances in the correct order to the `MockMvc` instance. Using it might look something like:

```java
MockMvcBuilders
				.webAppContextSetup(context)
				.apply(springBoot())
				.build();
```

**NOTE** Special attention should be given if Spring Security is added. Specifically, it should ensure to use the `SecurityMockMvcRequestPostProcessors#testSecurityContext()` as is done in `SecurityMockMvcConfigurer`

**Comment by wilkinsona** [comment]
This is very similar to #2708, although expressed a little differently. I don't think we need both. What do you, @rwinch?

**Comment by rwinch** [comment]
Thanks @wilkinsona! My report does appear to be a duplicate (my search terms didn't hit that issue). I will close it as such.
