### ISSUE TITLE
Add auto-configuration for JdbcClient

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#36579]
Spring Framework 6.1 introduces the new [JdbcClient](https://github.com/spring-projects/spring-framework/issues/30931). We should add an auto-configuration for it.

@jhoeller suggested something like this:

```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnSingleCandidate(NamedParameterJdbcTemplate.class)
@ConditionalOnMissingBean(JdbcClient.class)
class JdbcClientConfiguration {

	@Bean
	@Primary
	JdbcClient jdbcClient(NamedParameterJdbcTemplate jdbcTemplate) {
		return JdbcClient.create(jdbcTemplate);
	}

}
```

**Comment by philwebb** [comment]
Reopening as I think we need a `MyBean.kt` file for the docs.

**Comment by snicoll** [comment]
Added in 3835e25a1868
