### ISSUE TITLE
Rationalize Spring Boot configuration keys

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3659]
During its early development Spring Boot has started to take a set of _root_ prefixes for configuration such as `spring` (obviously) but also a _few_ others: `management`, `server`, `endpoints`, `logging`, `security`, `multipart`, `error`.  We also have root prefixes for 3rd party integration (`liquibase`, `flyway`, `jolokia`).

We want to push for [a _reserved namespace_ for the keys that Spring Boot is exposing](https://github.com/spring-projects/spring-boot/issues/2828) so that we can guarantee a stability over time. We can't do that with the current namespaces that we are holding. 

I think we should come with a clear policy that would avoid some unfortunate decision. `error` actually exposes one property at this point which is the path of the Spring MVC view to use in case of error. Could as easily have been `spring.mvc.error` or something...

**Comment by shakuzen** [comment]
(+1)

**Comment by arnosthavelka** [comment]
:thumbsup:

**Comment by snicoll** [comment]
See also #2020

**Comment by snicoll** [comment]
As part of this PR, we should also avoid at all cost mixing our own property POJO with 3rd party binding. 

Typical example: `Flyway`. In `FlywayProperties` we have a `locations` property of type `List<String>. In `Flyway` we have a `locations` property of type`String[]`. When you set a comma-separated value, both values are injected just fine. If you use an indexed value (typically with YAML) then it blows up because `Flyway.getLocations()` returns a new array every time and the binder fails to realize this is the "same" value somehow.

**Comment by snicoll** [comment]
With the latest changes for the banner (#11339) I believe we are in a good situation now. The only root prefixes we have are `spring`, `management` and `logging`.
