### ISSUE TITLE
Integration tests with few spring-boot applications

### ISSUE THREAD

**Issue by CyborTronik** [spring-projects/spring-boot#3663]
Currently its very problematic to have 'real' integration tests where some of modules uses spring-boot (akka microservices). I still didn't found a way for running a spring-boot application from another jar file without blocking current phase in maven. Maybe you will suggest something for that?

Scenario:
I have a spring-boot module called "A".
Then I have another module called "B". So to do integration tests for "B" I have to start "A" in pre-integration-test and just after that run the "B" itself.

Is there a way to achieve that?

**Comment by snicoll** [comment]
To be clear, is this a build pipeline request or a Spring Boot-specific feature request? If you're asking to run a build goal in module "A" and then do something in module "B" (run B and tun the integration-tests) then it's a build system specific issue and I am afraid there is not much we can do here

If you want to start A as part of the `pre-integration-test` phase of module B, then it's a different story (kind of). Can you clarify that first please?

**Comment by CyborTronik** [comment]
I want to start application A with embedded tomcat and all the things as part of pre-integration-test phase of module B. And then on post-integration-test to stop it.

**Comment by snicoll** [comment]
What would be the reference? The "fat jar" of B + some config?

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
