### ISSUE TITLE
Deprecate support for OkHttp3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36632]
Spring Framework 6.1 [deprecates support for OkHttp3](https://github.com/spring-projects/spring-framework/issues/30919). We should follow suit.

**Comment by knut-olav-hoven-ske** [comment]
Looks like the real reason why spring-web deprecated okhttp3-support is because it is built using Kotlin.
Is Spring planning on removing all Kotlin support or just avoid integrations with any Kotlin-based libraries?

**Comment by bclozel** [comment]
> Is Spring planning on removing all Kotlin support or just avoid integrations with any Kotlin-based libraries?

Neither. Spring has first class Kotlin support and has integrations with Kotlin libraries. In this case, requiring the Kotlin runtime for a library that didn't need this dependency previously was the main driver behind that decision.

**Comment by knut-olav-hoven-ske** [comment]
So the strategy is to evict all libraries that expand their dependency list, even when those dependencies are already included in the "Spring family stack"?

**Comment by knut-olav-hoven-ske** [comment]
> Neither. Spring has first class Kotlin support and has integrations with Kotlin libraries. In this case, requiring the Kotlin runtime for a library that didn't need this dependency previously was the main driver behind that decision.

So the strategy is to evict all libraries that expand their dependency list, even when those dependencies are already included in the "Spring family stack"?

**Comment by wilkinsona** [comment]
@knut-olav-hoven-ske This discussion does not belong here. As you've already noted above, the change in Spring Boot was driven by https://github.com/spring-projects/spring-framework/issues/30919. If you must question the Framework's team motivation for making the change, please do so there.
