### ISSUE TITLE
Hibernate binding parameters not showing in logs

### ISSUE THREAD

**Issue by bizwms** [spring-projects/spring-boot#36640]
I'm using Spring Boot version 3.1.1 and I've noticed that the Hibernate binding parameters are not showing in the logs. I've set the logging level for org.hibernate.type.descriptor.sql.BasicBinder to trace in my application.properties file, but it doesn't seem to have any effect.

Here is a snippet of my application.properties:

```
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.hibernate.type.EnumType=trace
spring.jpa.properties.hibernate.format_sql=true
```

I expect to see the binding parameters in the logs when executing SQL queries, but currently, I only see the SQL statements without the parameters.

Any help would be appreciated.

**Comment by quaff** [comment]
Hibernate renamed `org.hibernate.type.descriptor.sql.BasicBinder` to `org.hibernate.orm.jdbc.bind`.

**Comment by bizwms** [comment]
I was able to output the binding parameters. thank you.
application.properties:

`logging.level.org.hibernate.orm.jdbc.bind=trace`

**Comment by bizwms** [comment]
I will close this issue.
