### ISSUE TITLE
Running spring-boot application in separated thread

### ISSUE THREAD

**Issue by CyborTronik** [spring-projects/spring-boot#3664]
Lets have something like:

```
public class ParallelBootStarter {
	public static void main(String[] args) {
		Thread thread = new Thread(ParallelBootStarter::run);
		thread.setDaemon(true);
		thread.start();
	}

	private static void run() {
		ASpringBootWebApp.main(new String[] {});
	}
}
```

Then spring-boot is unable to start embedded tomcat. So how to run it in a separate thread?

**Comment by wilkinsona** [comment]
Why are you trying to run the application in a separate thread? If you're using embedded Tomcat then the call to `SpringApplication.run` will return, allowing you to do whatever else is necessary on the main thread. Other non-daemon threads that are started by Tomcat will keep the JVM running.

Also, without knowing the failure that you're seeing, it's almost impossible to offer any guidance if you really do need to be launching your app on a separate thread.

**Comment by CyborTronik** [comment]
I'm trying to find a work around for https://github.com/spring-projects/spring-boot/issues/3663

**Comment by CyborTronik** [comment]
![screenshot from 2015-08-05 13 42 01](https://cloud.githubusercontent.com/assets/3275697/9084014/e286d36a-3b77-11e5-8e3c-240d8942f172.png)
I see this error when I'm trying to start

**Comment by wilkinsona** [comment]
Sorry, that's not very helpful as it doesn't show the full stack trace. You also haven't explained why you need to use a separate thread. As I said above:

>  If you're using embedded Tomcat then the call to SpringApplication.run will return, allowing you to do whatever else is necessary on the main thread

**Comment by CyborTronik** [comment]
The SpringApplication.run is not called directly as you see in the code at the beginning of this thread.
Even if I will have direct access to this result the application is failing at SpringApplication.run step.

What is the difference for what is needed to load application in a separated thread? It does make any differences?

I need to run a separated application (imported as maven dependency) in pre-integration-test phase. 

The stacktrace is full as shown here. If you see there even SpringApplication.run exists in log.

**Comment by wilkinsona** [comment]
> The SpringApplication.run is not called directly as you see in the code at the beginning of this thread.

That shouldn't matter. I don't think Spring Boot will be causing its main method to block so, unless the main method does something unusual, the call to it should return.

> the application is failing at SpringApplication.run step

You haven't provided enough information to diagnose why that's happening. I can see that a Tomcat component has failed to start, but your screenshot doesn't show which one. I'd expect another stacktrace / some more log messages that detail the failure.

> What is the difference for what is needed to load application in a separated thread? It does make any differences?

AFAIK, it makes no difference. I started `spring-boot-sample-web-freemarker` with no difficulty on a separate thread.

If you'd like the Spring Boot team to spend any more time trying to help you, please take the time to provide all the information that we need. You might find this [information about creating a minimal, complete, and verifiable example](http://stackoverflow.com/help/mcve) to be useful.

**Comment by wilkinsona** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Comment by anantmnavagale** [comment]
I have similar requirement. I want my spring boot standalone application to run forever. If I add add spring-boot-starter-web dependency (to run it forever) with jetty as container, it includes too many dependent jars (webmvc, websocket, jackson and many more), which I want to avoid
Is there any way to run spring boot standalone app forever.
