### ISSUE TITLE
LogbackLoggingSystem does not report suppressed exception details

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#36645]
`LogbackLoggingSystem.reportConfigurationErrorsIfNecessary` currently reports errors but does not include all stacktrace details. We should pull them from the `Status` when we can and add them as suppressed exceptions .

**Comment by robozb** [comment]
Dear @philwebb, Thank you so much, you are great!

**Comment by wilkinsona** [comment]
Closed by 694ff4f8750362da443630e5eedc3eb255a197aa.
