### ISSUE TITLE
current-SNAPSHOT still has a previous version of document

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#3665]
`current-SNAPSHOT` has a current version of a document:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-install.html

but it also has a previous version of the same document:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-service.html

**Comment by snicoll** [comment]
We don't clean "old" files on the server. I'll have a look. Thanks.

**Comment by snicoll** [comment]
Fixed.
