### ISSUE TITLE
Springboot 3.1.3 artifacts not in mvncentral

### ISSUE THREAD

**Issue by apahne** [spring-projects/spring-boot#36658]
Maybe I am looking wrong, but I can't find the artifacts in maven central.

The release was a few days ago. Shouldn't the artifacts be there?

https://mvnrepository.com/artifact/org.springframework.boot/spring-boot

Thanks.

**Comment by bclozel** [comment]
We've recently released [Spring Boot 3.1.2](https://github.com/spring-projects/spring-boot/milestones?state=closed), version 3.1.3 is not scheduled yet. We [announced this release on our blog as well](https://spring.io/blog/2023/07/20/spring-boot-3-1-2-available-now). The [project page shows 3.1.2 as the current release](https://spring.io/projects/spring-boot#learn).

Is there a reference to 3.1.3 anywhere? Can you point us to it?

**Comment by apahne** [comment]
I was looking on the Spring blog:
https://spring.io/blog/2023/07/27/spring-shell-2-1-12-3-0-7-and-3-1-3-are-now-available

**Comment by philwebb** [comment]
That link is for Spring Shell, not Spring Boot.

**Comment by apahne** [comment]
OK, then sorry. My bad...
