### ISSUE TITLE
RandomServerPort and GraalVM don't cooperate (bug)

### ISSUE THREAD

**Issue by nkrul** [spring-projects/spring-boot#36657]
Bug Report:
Using the GraalVM plugin breaks things when using Kotlin and the graal plugin (org.graalvm.buildtools.native)

A worked example is here: https://github.com/nkrul/SpringBootIssue

versions:
```
plugins {
	id("org.springframework.boot") version "3.1.2"
	id("io.spring.dependency-management") version "1.1.2"
	kotlin("jvm") version "1.8.22"
	kotlin("plugin.spring") version "1.8.22"

	// this seems to interfere with tests and AOT compilation
	id("org.graalvm.buildtools.native") version "0.9.20"
}
```

I would guess that that the context reloading and the Aot Compilation steps aren't correctly computing dependencies.

To reproduce the failure, just `./gradlew test`
To prevent the failure, you can either remove the graalvm build tool, or the random server port test.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem does not occur with Spring Framework 6.0.12-SNAPSHOT:

```
repositories {
	mavenCentral()
	maven {
		url = uri("https://repo.spring.io/snapshot")
	}
}

ext {
	set("spring-framework.version", "6.0.12-SNAPSHOT")
}
```

Duplicates https://github.com/spring-projects/spring-framework/issues/30861.
