### ISSUE TITLE
Examine synchronized usage

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#36670]
Virtual threads and `synchronized` blocks don't play very well together, as they cause thread pinning. `synchronized` is fine when not doing any long-running operations, however.

We should examine our usage of `synchronized` and replace it with `Lock` when we guard long-running operations with them.

**Comment by dreis2211** [comment]
Might be wise to investigate the same for `ThreadLocal` usages eventually. They don't play along nicely with Loom either.

**Comment by mhalbritter** [comment]
Thanks @dreis2211. The ticket for that is #36681.

**Comment by mhalbritter** [comment]
I've reverted that change. We need to examine where exactly we want to have virtual threads. And when we know that code can be run on virtual threads, we're going to refactor it to `Lock` IF there is blocking going on.

**Comment by mhalbritter** [comment]
And we need to think about Checkstyle rules or something like this to not let `synchronized` in those cases creep in.

**Comment by mhalbritter** [comment]
- `ConfigTreePropertySource` uses a `synchronized` around IO operations. It's called from `toString()` and on `getInputStream()`. This could be a candidate for a `Lock`.
