### ISSUE TITLE
Review use of ArtifactRepository in ProcessTestAotMojo

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36724]
`ArtifactRepository` has been deprecated in recent versions of Maven as part of [MNG-7706](https://issues.apache.org/jira/browse/MNG-7706). It's not immediately obvious to me how to migrate away from `ArtifactRepository` as `ArtifactResolutionRequest` still uses it. Some of the discussion on https://github.com/apache/maven/pull/1012 might give us some clues.

**Comment by snicoll** [comment]
This [change in the Maven Surefire plugin](https://github.com/apache/maven-surefire/commit/2709f76c045209f0fff0bacd447cacf489ed05c3) should provide some additional hints.
