### ISSUE TITLE
Add any TransactionExecutionListener beans to the auto-configured transaction manager

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#36770]
[Suggestion from Juergen](https://github.com/spring-projects/spring-framework/issues/27479#issuecomment-1666859381):

> Boot could automatically inject any `TransactionExecutionListener` beans in the context into a `PlatformTransactionManager` or `ReactiveTransactionManager` that it configures, along the following lines:
> 
> ```java
> @Bean
> public JdbcTransactionManager transactionManager(DataSource dataSource, Collection<TransactionExecutionListener transactionExecutionListeners) {
>    JdbcTransactionManager tm = new JdbcTransactionManager();
>    tm.setDataSource(dataSource);
>    tm.setTransactionExecutionListeners(transactionExecutionListeners);
>    return tm;
> }
> ```

**Comment by snicoll** [comment]
I'd like to fix #36801 before going forward as I implemented it as a customizer which make the problem more apparent.
