### ISSUE TITLE
Add ArchUnit rule to enforce declaring @Order on built-in Customizer beans

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#36779]
Customizer beans should declare an explicit reasonable order, it should be `0` with most case.
See https://github.com/spring-projects/spring-boot/issues/36674 https://github.com/spring-projects/spring-boot/pull/36778

**Comment by wilkinsona** [comment]
As per my comment on #36778, I don't think we can do this without an unacceptably high risk of a breaking change.
