### ISSUE TITLE
Akka Config support

### ISSUE THREAD

**Issue by Loki-Afro** [spring-projects/spring-boot#368]
I really like to see Akka Config support in spring-boot
https://github.com/typesafehub/config

It is very similar to yaml but has more features also it is "even more human readable"

Is there a simple way to implement a new "properties library" like for example implementing another Servlet Container?

**Comment by dmi3zkm** [comment]
Any updates on that feature ?

**Comment by wilkinsona** [comment]
We ended up with two issues for this. See https://github.com/spring-projects/spring-boot/issues/3558 for the latest status.
