### ISSUE TITLE
Consider reverting removal of dead code from ConfigurationPropertiesMetaData

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3686]
Commit c25c07dfdddb7060f04ff32945c287f9b49b29fd removed some dead code from `ConfigurationPropertiesReportEndpoint` originally added to fix #1746 and #1921. We should double check if we want that code or not.

**Comment by snicoll** [comment]
To be clear, the code that was removed was never actually called.

**Comment by philwebb** [comment]
Looks like `metadataLocations` should have been `classpath*:/META-INF/spring-configuration-metadata.json`.

#1921 seems fixed regardless. Certainly no harm in removing this for 1.3.M3 but we should check if #1746 is a problem still.

**Comment by snicoll** [comment]
I know but because the class path location was wrong we can prove the code was never called. If we can remove that complexity I am happy. 

If we have to revert that I'd like that we use the new configuration-metadata module then. Thanks!

**Comment by snicoll** [comment]
@philwebb Looks quite outdated to me. Let me know if I am missing anything

**Comment by philwebb** [comment]
+1, this one is too old to be relevant.
