### ISSUE TITLE
Allow setting a custom ThreadPool instance when instantiating Server in JettyEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by chornyi** [spring-projects/spring-boot#3687]
Jetty's `ThreadPool` can only be set when instantiating the `Server` instance and the `JettyEmbeddedServletContainerFactory::getEmbeddedServletContainer` does not provide a way to change the way the `Server` instance is instantiated.

A custom `ThreadPool` is required for example when using Dropwizard Metrics for Jetty: https://dropwizard.github.io/metrics/3.1.0/manual/jetty/

**Comment by bashnesnos** [comment]
Yeah, that would be definitely a useful one to have.

**Comment by wilkinsona** [comment]
Closing in favour of PR #5324.
