### ISSUE TITLE
For reactive WebClient, build the URI in the Mono context when it is subscribed, and not when the RequestHeaderSpec is being built

### ISSUE THREAD

**Issue by honza-zidek** [spring-projects/spring-boot#36907]
# Request

For reactive `WebClient`, introduce some possibility to build the URI in the `Mono` context when it is subscribed, and not when the `RequestHeaderSpec` is being built. It is unpleasant that the possible exceptions thrown there are thrown in the main thread and not in the `Mono` context.

# Motivation

### Code

I have a Spring reactive web client used to connect to a web service.

```java
@Autowired
private org.springframework.web.reactive.function.client.WebClient webClient;

public Mono<MyData> getMyData(MyRequest request) {
    return webClient
        .get()
        .uri(uriBuilder -> this.createUri(uriBuilder, request))
        // Any exception thrown before this point is outside of the Mono context
        .retrieve()
        .bodyToMono(MyDataDto.class)
        .map(myDataDto -> mapToMyData(myDataDto))
        ;
}
```

There is a possibility that the `createUri()` method throws an exception:

```java
private URI createUri(UriBuilder uriBuilder, MyRequest request) {
    if (somethingIsInconsistent) {
        throw new MyException();
    }
}
```

The problem is that the exception is thrown in the main thread when the `Mono` is created, and not in the context of the `Mono` when it is subscribed.

### Tests

As a result, the following test fails:

```java
@Test
void getMyData_whenBadRequest_throwExceptionWhenSubscribed() {
    service.getMyData(badRequest)
        .as(StepVerifier::create)
        .expectError(MyException.class)
        .verify();
}
```

and this passes:

```java
@Test
void getMyData_whenBadRequest_throwExceptionWhenCreated() {
    assertThrows(MyException.class, 
        () -> service.getMyData(badRequest));
}
```

I'd like to catch all the exceptions in the context of the `Mono` subscription.

### Problem statement

I can wrap the code so **all** exceptions are thrown when the `Mono` is subscribed, but the solution is awkward and ugly. The original code was much smoother and more easily readable!

```java
public Mono<MyData> getMyData(MyRequest request) {
    return Mono.just(request)
        .flatMap(req -> webClient
            .get()
            .uri(uriBuilder -> this.createUri(uriBuilder, req))
            .retrieve()
            .bodyToMono(MyDataDto.class))
        .map(myDataDto -> mapToMyData(myDataDto))
        ;
}
```

The URI is created dynamically, depending on the `request` input parameter. Some combination of fields of the `request` is not able to produce a valid URL and such a request should fail. I cannot think of a better place to create the URI. The most logical place seems the method itself. Even if I delegated the URI creation to an external class, it would be called before the `Mono` when the `RequestHeaderSpec` is being built.

# Suggested Solution

### `uriDeferred()`

A possible solution might be to introduce a new set of methods to build URI, which will just pass the lambdas called later when the `Mono` is subscribed. A possible naming `uriDeferred()` :)

```java
public Mono<MyData> getMyData(MyRequest request) {
    return webClient
        .get()
        .uriDeferred(uriBuilder -> this.createUri(uriBuilder, request))
        .retrieve()
        .bodyToMono(MyDataDto.class)
        .map(myDataDto -> mapToMyData(myDataDto))
        ;
}
```

### `RequestHeaderSpecMono`

Another solution might be *something like* `RequestHeaderSpecMono extends Mono`, with added extra methods similar to those in `WebClient`.

```java
public Mono<MyData> getMyData(MyRequest request) {
    return webClient
        .createRequestHeaderSpecMono()    // RequestHeaderSpecMono
        // All the exceptions thrown from now on are in the Mono context
        .get() // RequestHeaderSpecMono
        .uri(uriBuilder -> this.createUri(uriBuilder, request))  // RequestHeaderSpecMono
        .retrieve()   // RequestHeaderSpecMono
        .bodyToMono(MyDataDto.class)  // Mono
        .map(myDataDto -> mapToMyData(myDataDto))
        ;
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. `WebClient` and the related classes are part of Spring Framework which is managed as a [separate project](https://github.com/spring-projects/spring-framework).

**Comment by honza-zidek** [comment]
@wilkinsona So I have created the issue anew in the Spring project: https://github.com/spring-projects/spring-framework/issues/31024
