### ISSUE TITLE
MockBean not work in the thread

### ISSUE THREAD

**Issue by stoneZ008** [spring-projects/spring-boot#36906]
I found that Mockbean is work the test main thread, but not work in the new thread call, following is my demo code. call the mock first time in new thread is work, but when call the demoService in second times, it return null (mock not work)

[demo.zip](https://github.com/spring-projects/spring-boot/files/12308715/demo.zip)

**Comment by stoneZ008** [comment]
Reference Jar Version 
mockito-core 4.11.0 
JDK1.8 
Junit4 
SpringBoot: 1.5.22.RELEASE

**Comment by wilkinsona** [comment]
Spring Boot 1.5.x [hasn't been supported since August 2019](https://spring.io/projects/spring-boot#support). Please upgrade to Spring Boot 2.7.x. If the problem still occurs, please provide an updated demo project and we can take a look.

**Comment by stoneZ008** [comment]
after upgrade to 2.7.12 , the issue is slove

**Comment by wilkinsona** [comment]
Thanks for letting us know.
