### ISSUE TITLE
spring boot's jetty8 sample rest error!

### ISSUE THREAD

**Issue by liupeifeng** [spring-projects/spring-boot#3693]
With v1.2.2 
if a rest function return a Object(eg. UserObject), it throw a exception (HttpMediaTypeNotAcceptableException:could not find acceptable representation)

But a rest function return a String, it has no exception.

why and how to do? thx!

**Comment by snicoll** [comment]
Please ask questions on StackOverflow. When you do, provide more information such as your code and the exact error that you get. Thanks.
