### ISSUE TITLE
spring-boot-maven-plugin no longer includes dependencies

### ISSUE THREAD

**Issue by patrickjamesbarry** [spring-projects/spring-boot#36945]
Version of spring boot: 3.1.2
Spring: 6.0.11
JDK: openjdk 20.0.1 2023-04-18 with ---enable-preview

Performing a mvn package, dependencies are no longer included in artifact.
 
```
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

```

I can force them to be included using `<includes>`, but that would take forever and we never had to do that before.

**Comment by snicoll** [comment]
@patrickjamesbarry thanks for the report but that's the problem with code snippet like that. I can't reproduce and I don't know what else you're not showing. Also we do have several tests and integration tests around that feature so I wonder what could cause what you've described. If you want support, please share a small sample (ideally created from start.spring.io) with the command and how you're validating that dependencies are not included.

**Comment by snicoll** [comment]
I don't see how the shade plugin from Maven can be related to our plugin. They really don't operate at the same level. Let's see if you can provide a reproducer.

**Comment by patrickjamesbarry** [comment]
I have not been able to recreate issue now.

**Comment by patrickjamesbarry** [comment]
closing
