### ISSUE TITLE
Is it possible to use Spring MVC with Jersey 2.x?

### ISSUE THREAD

**Issue by Krasnyanskiy** [spring-projects/spring-boot#3699]
I want to have an app with web part (Spring MVC) and with RESTful API (Jersey 2.x) as well. Here is a link to my [attempt](https://github.com/Krasnyanskiy/todolist-demo).

The REST part works just fine. But all my requests to `/` (to controller handler) lead to 404 error and Spring doesn't even render the page. Any requests do not get into the controller. Seems that Boot doesn't see a dispatcher somehow.

How can I integrate it? I'd be grateful for any hints.

Thanks.

**Comment by dsyer** [comment]
You need to separate the Spring and Jersey resources. E.g. using `@ApplicationPath` for Jersey and `server.servletPath` for MVC.

**Comment by Krasnyanskiy** [comment]
Thanks. It works now.

**Comment by betalb** [comment]
@dsyer are there any other options? There are internal endpoints like BasicErrorController which does a lot of useful stuff, but is using spring MVC and Jersey is mapped to `/*` which we can't remap.

Are we left only with option to implement our own error endpoint using Jersey?
