### ISSUE TITLE
Can the containerd for the document page be removed?

### ISSUE THREAD

**Issue by qq253498229** [spring-projects/spring-boot#36998]
On larger screens, containerd causes significant wastage of space on both sides, and it seems that removing it also doesn't affect the display outcome on smaller screens.
The first screenshot shows the display effect with containerd, while the second one is the result after I removed containerd.

<img width="1920" alt="c88310815f73346322725f18ddabe563" src="https://github.com/spring-projects/spring-boot/assets/31200516/d99435de-4f94-4aee-82f4-9d85faa73949">

<img width="1920" alt="25efbe7f09c645d13181ea62a55db3b1" src="https://github.com/spring-projects/spring-boot/assets/31200516/84e617e1-dfcb-4ff1-adcf-a2e78d0fa62a">

This is what I referred to as "containerd."
<img width="1850" alt="image" src="https://github.com/spring-projects/spring-boot/assets/31200516/bc3eccac-a205-40b6-b69e-7bce2c44a256">

**Comment by philwebb** [comment]
We have a plan to migrate the docs to Antora (see #33766) which should fix this. I'm not keen to make changes to the exiting CSS since it will ultimately be replaced.
