### ISSUE TITLE
Logging config URLs with query parameters are not detected as XML

### ISSUE THREAD

**Issue by nikhilraj6692** [spring-projects/spring-boot#37008]
While upgrading to Spring boot 3.0.x, if consul contains below property:
```
logging:
  config: ${spring.cloud.consul.scheme}://${spring.cloud.consul.host}:${spring.cloud.consul.port}/v1/kv/${spring.cloud.consul.config.prefix}/logger.xml?raw=true&xml
```

it works till spring boot 3.0.4, since LogbackLoggingSystem class expects url to end with "xml"
![image](https://github.com/spring-projects/spring-boot/assets/49581523/68400d7e-4250-4fa3-98e3-e3e718b4ac82)

But, with versions above 3.0.4, this has changed and expects logging url to end with ".xml"
![image](https://github.com/spring-projects/spring-boot/assets/49581523/dfbff088-76ef-445d-addb-eed46f6a6bf5)

The problem is that the issue could have been found easily, if it would have printed in logs. But with consul config, nothing prints in logs when this error occurs. Please document this in spring boot 3.0.4+ changes

**Comment by snicoll** [comment]
>  But with consul config, nothing prints in logs when this error occurs.

I'd argue you should be reporting the issue to Consul. There's nothing that we can do here I am afraid. Recent version of logback only offers XML-based configuration so we just adapted to that.

**Comment by quaff** [comment]
@snicoll I think it's a regression, `/logger.xml?raw=true&xml` is xml.

**Comment by philwebb** [comment]
I think I agree, but I think we should look at fixing the detection logic rather than documenting the limitation.

**Comment by scottfrederick** [comment]
Closing in favor of #37039
