### ISSUE TITLE
PropertiesLauncher: property "loader.path" and jar with embeded zip file

### ISSUE THREAD

**Issue by francoisgergaud** [spring-projects/spring-boot#3701]
Hi,

I am having a strange behaviour with spring-boot (version 1.2.4.RELEASE). I need to add an external jar-dependency on my classpath when launching my application (a h2 database driver which can be found here: http://www.h2database.com/html/download.html). 

Trying to launch my application defining the JVM argument this way:
`-Dloader.path=<myApplicationJar>, h2-driver.jar`
does not work, because it seems the PropertiesLauncher could not add to the classpath a jar containing a zip file (in my case, the h2 database driver comes with some images and other resources zipped inside the jar file as it contains a in-memory database administration web-app). It throws the following exception while starting the application:
>java.lang.IllegalStateException: Unable to open nested entry '<jarFileName>'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file

But when launching specifying a directory containing the jar by giving its container directory like this:
`-Dloader.path=<myApplicationJar>, <directoryContainigMyH2DriverJar>`
it works fine.

I commented a question on Stack-overflow which may provide more information:
http://stackoverflow.com/questions/28074393/spring-boot-createjarfilefromfileentry/30949243?noredirect=1#comment51598686_30949243

It seems there is a difference when adding a jar file to a classpath by giving it directly a by giving the directory containing it? It is a bug?

**Comment by wilkinsona** [comment]
The behaviour has changed (for the worse) in 1.4: it fails silently now

**Comment by wilkinsona** [comment]
@francoisgergaud Sorry, this issue fell through the cracks. To answer your question:

> It seems there is a difference when adding a jar file to a classpath by giving it directly a by giving the directory containing it? It is a bug?

The javadoc for `loader.path` describes it as "a comma-separated list of directories to append to the classpath". You've configured it with a file so the behaviour's undefined, however the way that it fails isn't very user-friendly. We'll improve that.

**Comment by wilkinsona** [comment]
On closer inspection, the javadoc is not in agreement with the reference guide [where it's described](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#executable-jar-launching) as "comma-separated list of directories or archives".

**Comment by francoisgergaud** [comment]
sorry, I am only seeing this message now. Thanks for the feedback @wilkinsona. I will use a folder to dynamically add some jars to my classpath.
