### ISSUE TITLE
name attribute conflict on @SpringView @Scope annotations

### ISSUE THREAD

**Issue by khangal** [spring-projects/spring-boot#3702]
name attribute conflict on @SpringView @Scope annotations 
It's Spring Boot 1.3.0.M2

In annotation [org.springframework.context.annotation.Scope] declared on [file [E:\workspace\cdispring\target\classes\demo\vaadin\car\CarViewImpl.class]], attribute [value] and its alias [name] are present with values of [vaadin-ui] and [cars], but only one is permitted.

**Comment by snicoll** [comment]
Neither of those classes are located in Spring Boot itself. Please create an issue [in the Spring Framework issue tracker](https://jira.spring.io/browse/SPR) with the version that you are using, the annotations on `CarView` and the full stacktrace. Thanks.

**Comment by sbrannen** [comment]
This has already been fixed in https://jira.spring.io/browse/SPR-13239. Thus, if you are using Spring Framework 4.2.0, this should no longer be an issue.

**Comment by snicoll** [comment]
@khangal you're probably using a Spring Boot 1.3 milestone at the moment. You can override to Spring Framework `4.2.0.RELEASE` or wait for M3 that will be released early next week. Thanks
