### ISSUE TITLE
Spring Boot Docker Compose class OracleEnvironment requires incorrect environment variable 

### ISSUE THREAD

**Issue by joesteel2010** [spring-projects/spring-boot#37036]
OracleEnvironment throws an exception if the environment variable APP_USER is provided and the environment variable APP_PASSWORD isn't defined. As per the documentation for the gvenzl Oracle container [here](https://hub.docker.com/r/gvenzl/oracle-xe), the correct environment variable is APP_USER_PASSWORD. This means that in order to start a new gvenzl/oracle-xe container, both APP_PASSWORD and APP_USER_PASSWORD need to be defined in the compose file.

I have identified that this issue is present in 3.1.2 and 3.2.0-SNAPSHOT

```docker-compose
services:
  oracle:
    image: 'gvenzl/oracle-xe:latest'
    environment:
      - ORACLE_PASSWORD=secret
      - APP_USER=appuser
      - APP_PASSWORD=secret_1
      - APP_USER_PASSWORD=secret_1
    ports:
      - '1521:1521'
```
The above starts correctly

```docker-compose
services:
  oracle:
    image: 'gvenzl/oracle-xe:latest'
    environment:
      - ORACLE_PASSWORD=secret
      - APP_USER=appuser
      - APP_USER_PASSWORD=secret_1
    ports:
      - '1521:1521'
```
The above throws an exception on starting the application

**Comment by scottfrederick** [comment]
Closing in favor of #37044
