### ISSUE TITLE
Java 8 support after 2.7.x OSS EOL

### ISSUE THREAD

**Issue by aboncok** [spring-projects/spring-boot#37043]
Hi,
2.7.x OSS end-of-life support is on 18 November 2023, only version 3.1.x has longer support but that does not support java 8.
Is there a plan to bring out 2.8.x to further support java 8 or will java 8 support be deprecated?
I understand that the commercial support is longer, however, we are tied to the OSS support and migrating to higher version java is not feasible for us in such a short time.

**Comment by bclozel** [comment]
We will not release a 2.8 version. [Please check out this blog post](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0), this should help you with the version upgrade.

**Comment by aboncok** [comment]
Thank you for your prompt response, @bclozel
