### ISSUE TITLE
Exception encountered during context initialization: springSessionRedisMessageListenerContainer

### ISSUE THREAD

**Issue by aaa2281002** [spring-projects/spring-boot#37041]
hello!
My error message，bean `springSessionRedisMessageListenerContainer`， Dynamically switching Redis sources，Exception occurred，

Abnormal information is as follows：

```
	2023-08-21 14:19:27.269  WARN 19480 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is java.lang.IllegalStateException: Subscription registration timeout exceeded.
```

My version 2.6.6 Upgrade to 2.7.14 Problems that arise
Which big shot has encountered a similar problem. Thank you for your timely feedback. thanks

**Comment by scottfrederick** [comment]
Duplicates #31138

See the [relevant comment](https://github.com/spring-projects/spring-boot/issues/31138#issuecomment-1134354179) on that issue.

**Comment by aaa2281002** [comment]
Hello, there is no solution to the problem with which post. The latest version 2.7.14 does not solve the current issue

**Comment by aaa2281002** [comment]
Hello, there is no solution to the problem with which post. The latest version 2.7.14 does not solve the current issue

**Comment by scottfrederick** [comment]
@aaa2281002 As noted in the comment that I linked to, we do not believe the problem lies in Spring Boot, but in Spring Data Redis or another related project. Also as noted in the other issue, the Spring Data Redis team cannot provide assistance without more information and a sample application. 

Please stop opening duplicate issues in this project pointing back to this issue.

**Comment by aaa2281002** [comment]
hello!
The example is in the compressed package！






该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spring-projects/spring-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月22日(星期二) 晚上9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spring-projects/spring-boot] Exception encountered during context initialization: springSessionRedisMessageListenerContainer (Issue #37041)





 
@aaa2281002 As noted in the comment that I linked to, we do not believe the problem lies in Spring Boot, but in Spring Data Redis or another related project. Also as noted in the other issue, the Spring Data Redis team cannot provide assistance without more information and a sample application.
 
Please stop opening duplicate issues in this project pointing back to this issue.

**Comment by aaa2281002** [comment]
hello!
Example link here:
https://github.com/aaa2281002/redis-demo.git
