### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by fmunch** [spring-projects/spring-boot#37045]
The 3 links to https://docs.oracle.com are broken in the [Core Features section of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html) :

* https://docs.oracle.com/javase/17/docs/api/java/time/Duration.html#parse-java.lang.CharSequence- redirects to https://docs.oracle.com/en/java/javase/17/docs/api/index.html#parse-java.lang.CharSequence- (should be https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence))
* https://docs.oracle.com/javase/17/docs/api/java/time/Period.html#parse-java.lang.CharSequence- redirects to https://docs.oracle.com/en/java/javase/17/docs/api/index.html#parse-java.lang.CharSequence- (should be https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Period.html#parse(java.lang.CharSequence))
* https://docs.oracle.com/javase/17/docs/api/java/util/logging/package-summary.html redirects to https://docs.oracle.com/en/java/javase/17/docs/api/index.html (should be https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/package-summary.html)

I only checked features.html, there might be more.

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by scottfrederick** [comment]
@jongwooo I've assigned the issue to you. Please let us know if you have any questions.

**Comment by scottfrederick** [comment]
Closing in favor of #37070
