### ISSUE TITLE
Allow data source type to be overwritten through spring configurations

### ISSUE THREAD

**Issue by bobonaut** [spring-projects/spring-boot#3705]
As stated in the issue #1426 spring boot auto configuration currently creates a DataSource with a specific type based on a set of predefined types in the DataSourceBuilder.

Issue #1426 was requesting to allow to specify these types using properties but was closed with a reason stating that you should exclude the types from the classpath. This is a very valid answer.
However,  when one uses tomcat as a webserver to run their packaged spring boot war in this is quite tedious, since removing the class from the classpath would required removing this class in tomcat itself.

Hence the question to reopen issue #1426 and create the ability to overwrite the type which spring boot autoconfigurer uses to create the DataSource, using properties files.

**Comment by snicoll** [comment]
Yeah, I think that makes sense. In the meantime you can add the following to your configuration

```java
@Bean
@ConfigurationProperties(prefix = "spring.datasource")
public DataSource dataSource() {
    return DataSourceBuilder.create().type(HikariDataSource.class).build();
}
```

**Comment by dsyer** [comment]
I don't see why this has to be done in properties. It's essentially a strongly typed problem, so Java is the best place for it. It's a one line method which is easy to write after all.

**Comment by snicoll** [comment]
I don't follow. You can map the property as `Class<? extends Datasource>` and we have other areas where we could just as easily write a one-liner method and we also have config options for those.

There is no way to force the connection pool that we want either. This seems like a valuable option for me.

**Comment by arnosthavelka** [comment]
If you agree on solution via configuration property than it's pretty easy (similar to my PR #3622). I can (hopefully) easily prepare PR for this issue as well.
