### ISSUE TITLE
Support parallel initialization of Testcontainers

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#37073]
Currently `TestcontainersLifecycleBeanPostProcessor` starts beans sequentially, it would be nice to offer an option to start them in parallel.

**Comment by philwebb** [comment]
Hacked up prototype code is at https://gist.github.com/bsideup/f05346e79e308ee3fc1307b50261343e

**Comment by ktevfik** [comment]
Hi, is this supposed to be a manageable option or is it supposed to be a default feature?

**Comment by AbdelHajou** [comment]
Hi @philwebb , Testcontainers now supports parallel initialization of containers by passing the `parallel = true` to the `@Testcontainers` annotation. Not sure how long it has been in there, do you still think we need support for parallel initialization in the `TestcontainersLifecycleBeanPostProcessor`?

**Comment by eddumelendez** [comment]
@AbdelHajou the parallel attribute in Testcontainers annotations is used in tests for static fields. This issue will address the parallel initialization when the container implementations are provided as a beans. See https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1

**Comment by philwebb** [comment]
Reopening to change property name to `spring.testcontainers.beans.startup`
