### ISSUE TITLE
How do I use the Paremeters listed in `spring init --list`

### ISSUE THREAD

**Issue by spilth** [spring-projects/spring-boot#3709]
I'm using Spring CLI v1.2.5.RELEASE.

When I run `spring help init` I see the following output:

    spring init - Initialize a new project using Spring Initialzr (start.spring.io)

    usage: spring init [options] [location]

    Option              Description
    ------              -----------
    -b, --boot-version  Spring Boot version to use (for
                          example '1.2.0.RELEASE')
    --build             The build system to use (for example
                          'maven' or 'gradle') (default: maven)
    -d, --dependencies  Comma separated list of dependencies
                          to include in the generated project
    -f, --force         Force overwrite of existing files
    --format            The format of the generated content
                          (for example 'build' for a build
                          file, 'project' for a project
                          archive) (default: project)
    -j, --java-version  Java version to use (for example '1.8')
    -l, --list          List the capabilities of the service.
                          Use it to discover the dependencies
                          and the types that are available
    -p, --packaging     Packaging type to use (for example
                          'jar')
    -t, --type          The project type to use. Not normally
                          needed if you use --build and/or --
                          format. Check the capabilities of
                          the service (--list) for more details
    --target            URL of the service to use (default:
                          https://start.spring.io)
    -x, --extract       Extract the project archive. Inferred
                          if a location is specified without
                          an extension

But when I run `spring init --list` I see a Parameters section with the following:

    +-------------+------------------------------------------+------------------------------+
    | Id          | Description                              | Default value                |
    +-------------+------------------------------------------+------------------------------+
    | type        | project type                             | maven-project                |
    | bootVersion | spring boot version                      | 1.2.5.RELEASE                |
    | packaging   | project packaging                        | jar                          |
    | javaVersion | language level                           | 1.8                          |
    | language    | programming language                     | java                         |
    | groupId     | project coordinates                      | org.test                     |
    | artifactId  | project coordinates (infer archive name) | demo                         |
    | version     | project version                          | 0.0.1-SNAPSHOT               |
    | name        | project name (infer application name)    | demo                         |
    | description | project description                      | Demo project for Spring Boot |
    | packageName | root package                             | demo                         |
    +-------------+------------------------------------------+------------------------------+

Some of the init options match up to the parameters (with casing changes) but a bunch do not.

How am I meant to set those parameters?  For example, how do I use `spring init` and pass a groupId and artifactId?

**Comment by snicoll** [comment]
This tracker is not meant for questions, please ask them on StackOverflow.

`list` gives you the capabilities of the server (the server is actually rendering the output). Not all parameters are backed by an explicit CLI options but we fixed that in 1.3, see #2793

**Comment by spilth** [comment]
Then I'd rename this issue to "spring init doesn't specify how to pass parameters listed in spring init --list".

**Comment by spilth** [comment]
Cool.  Looking forward to 1.3! Thanks.
