### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace when repeatedly deploying and undeploying a Spring Boot web application multiple times in Tomcat

### ISSUE THREAD

**Issue by vazhaa72** [spring-projects/spring-boot#37096]
When repeatedly deploying and undeploying a Spring Boot **version 3.1.2** web application (WAR file) in a Tomcat application server one gets `java.lang.OutOfMemoryError: Metaspace` after 7-8 attempts. 

This seems to be caused by the change in `org.springframework.boot.SpringApplicationShutdownHook` class, which now also registers `org.springframework.boot.SpringApplicationShutdownHook.Handlers` as a shut-down hook, which was not the case with Spring Boot 2.7 for example.

**Comment by philwebb** [comment]
It looks like we may have a regression that's re-introduced #27987

**Comment by philwebb** [comment]
@vazhaa72 Have experienced the same problem with 3.0.x? I'm just wondering when we broke things.

**Comment by vazhaa72** [comment]
> @vazhaa72 Have experienced the same problem with 3.0.x? I'm just wondering when we broke things.
@philwebb , I recompiled our projects with Spring Boot 3.0.0 and could not reproduce the issue. So I assume that a potential regression came in with 3.1.x.
