### ISSUE TITLE
@WebMvcTest is not picking @ControllerAdvice in spring boot 3.2.0-M2

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-projects/spring-boot#37098]
After upgrading from spring boot 3.2.0-M1 to spring boot 3.2.0-M2 `@WebMvcTest` is unable to bind `@ControllerAdvice` .

Sample code for [replication ](https://github.com/rajadilipkolli/my-spring-boot-experiments/tree/renovate/spring-boot/httpClients/boot-restclient), till 3.1.0-M1 it is working.

This [testcase ](https://github.com/rajadilipkolli/my-spring-boot-experiments/blob/renovate/spring-boot/httpClients/boot-restclient/src/test/java/com/example/restclient/bootrestclient/web/controllers/PostControllerTest.java#L100-L118) is failing though I have [exception ](https://github.com/rajadilipkolli/my-spring-boot-experiments/blob/renovate/spring-boot/httpClients/boot-restclient/src/main/java/com/example/restclient/bootrestclient/config/GlobalExceptionHandler.java)handler

**Comment by quaff** [comment]
I can not reproduce it with minimal project [GH-37098.zip](https://github.com/spring-projects/spring-boot/files/12434672/GH-37098.zip).

**Comment by rajadilipkolli** [comment]
Hi @quaff , I have modified your same to replicate the same. [GH-37098.zip](https://github.com/spring-projects/spring-boot/files/12436552/GH-37098.zip)

Not sure if it is happening only when problem details is enabled

**Comment by quaff** [comment]
@rajadilipkolli Actually `@ControllerAdvice` is picked by `@WebMvcTest`, and the test pass if `@ResponseStatus` removed, I think something changed at framework not boot side caused this.

**Comment by quaff** [comment]
> @rajadilipkolli Actually `@ControllerAdvice` is picked by `@WebMvcTest`, and the test pass if `reason` of `@ResponseStatus` removed, I think something changed at framework not boot side caused this.

I've created https://github.com/spring-projects/spring-framework/pull/31113 to fix this.

**Comment by snicoll** [comment]
Thanks very much @quaff. I am going to close this one in favor of the framework issue. 

@rajadilipkolli please subscribe to https://github.com/spring-projects/spring-framework/pull/31113 for further updates.

**Comment by quaff** [comment]
> Thanks very much @quaff. I am going to close this one in favor of the framework issue.
> 
> @rajadilipkolli please subscribe to [spring-projects/spring-framework#31113](https://github.com/spring-projects/spring-framework/pull/31113) for further updates.

@snicoll Such behavior exists over ten years, It's not likely a regression cause this problem. I think it's correct and I've created another [document enhancement PR](https://github.com/spring-projects/spring-framework/pull/31121).
@rajadilipkolli Please make another minimal project that indicate it's a recent regression.

**Comment by rajadilipkolli** [comment]
Hi @quaff , you can use [this ](https://github.com/spring-projects/spring-boot/files/12436552/GH-37098.zip) as an example.

**Comment by quaff** [comment]
> Hi @quaff , you can use [this ](https://github.com/spring-projects/spring-boot/files/12436552/GH-37098.zip) as an example.

As I described in https://github.com/spring-projects/spring-framework/pull/31121, The return value of HandlerMethod will be ignored if `reason` of `@ResponseStatus` present, It is expected behavior, you could remove the `reason` to make your test passes.
I'm wondering there is another recent changes cause the regression.
