### ISSUE TITLE
Docker images produced by gradle bootBuildImage have no layer commands

### ISSUE THREAD

**Issue by mwisnicki** [spring-projects/spring-boot#37107]
### Repro:

1.  https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.1.3&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo
2.  `gradlew bootBuildImage`
3.  Inspect image in e.g. Docker Desktop

### Actual:

All layers have blank commands.

This makes finding out what's inside rather painful.

### Expected:

Each layer has a command

**Comment by bclozel** [comment]
By "layer commands" are you referring to "COPY" "RUN" etc commands?

If that's the case I don't think we can do much here. The layers are built by https://github.com/paketo-buildpacks/java and the process is mostly out of our control. More, buildpacks build layers but do much more than running such commands. You can have a look at the [Spring Boot one](https://github.com/paketo-buildpacks/spring-boot).

**Comment by mwisnicki** [comment]
Thanks. Looks to me like non-command based builders could at least leave comments?
Not sure what's allowed in the image metadata but if real comments are not possible then one could abuse `RUN` with echo or fake command. At minimum it could insert information about each buildpack.

Although I guess this would be a request for paketo project?

**Comment by bclozel** [comment]
Yes. I'm not sure where this issue should be created as it's a general comment.

Maybe start a new discussion here?

https://github.com/buildpacks/community/discussions
