### ISSUE TITLE
response time is high for some random get api requests, when i looked into newRelic logs i found out .doFilter is taking around 50-70% of the total api duration

### ISSUE THREAD

**Issue by rabindra23** [spring-projects/spring-boot#37102]
We are calling an api lets say service_2 from service_1, in service_2 we are seeing high time consumption in our Filter class.
Filter - com.service_2.configuration.LogReqResFilter.doFilter
time taken - 8.02 s (63.21%) 
service_1 - Springboot - 3.0.1 Java 17
service_2 - Springboot - 2.7.5 Java 11

Thank you

**Comment by bclozel** [comment]
Performance issues are often quite hard to diagnose and require comparisons and profiling.
Your issue description is very vague and nothing points to Spring Boot at this point: the two services use different Java versions, lots of major dependency upgrades, drivers, etc.

I'm closing this issue for now but we can reopen it if you can provide evidence (like profiling data) that some Spring class has a performance problem.
