### ISSUE TITLE
Support config property --> object field custom mapping 

### ISSUE THREAD

**Issue by mipo256** [spring-projects/spring-boot#37105]
The following [SO question](https://stackoverflow.com/questions/52960921/spring-boot-configurationproperties-change-property-key) illustrates the problem well.

Long story short, sometimes I want to have a property in my config file, which name is different from the object field. As far as I know, and seems it is still the case, there is no way to do it other than generating some custom setters, but that seems to be a workaround, not a solution. 

It would be great to introduce a new annotation (or another way, but the annotation seems to be the smoothest) to handle this case, like:

```
class MyS3Config {

     /**
      * This annotation of course does not exists, but this is just an example
      * I cannot have an identifier named 'public' in Java, so I have to do custom mapping
      */
     @ConfigurationPropertiesMapping(property = "public")
     private String publicBucket;
}
```

Thanks  in advance

**Comment by quaff** [comment]
Could you explain why you would like to use a different key in config file?
There is another solution:
```yaml
public: ***
publicBucket: ${public}
```

**Comment by Mikhail2048** [comment]
Sure.
Example you provided, as I pointed out specifically, is not a solution, it is a workaround to just make this work. What we have in reality is this: there is a `Buckets` nested condif class in `AWSConfig` in our domain. We have a naming conention for decades of buckets, like:

```
company.iam.buckets.<bucket_name>
```

and the config from the top level looks like this:

```
public class AWSConfig {

    static class Buckets {
    } 
}
```

So now image we have a bucket named public. We cannot use `public` as an identifier in java. The only option now is to name it like:

```
company.iam.buckets.publicBucket
```

but we already have a bunch of them named like: 
```
company.iam.buckets.local
company.iam.buckets.restricted
company.iam.buckets.data
company.iam.buckets.terraform
```
So we would break the naming convention. Or we need to change the naming convention just becasue of one bucket. It is clearly easier to just name the bucket in Java code as `publicBucket`, but retain the properties naming convention in config.

I hope it is clear now.

**Comment by quaff** [comment]
> We cannot use `public` as an identifier in java. 

I got the point.

**Comment by quaff** [comment]
Introducing a new annotation will make things more complicated, I think custom setter `setPublic(String value)` or placeholder `publicBucket: ${public}` is graceful enough, If the config class is maintained by yourself then adding setter is more appropriate, otherwise use placeholder instead.

**Comment by Mikhail2048** [comment]
I do not think so. I have encoutererd this predicament multiple times, and the question itself was viewed 7k+ times, so I assume I am not alone. I can of course each time get by using custom setters, but that's again unclear for the readoer of the code on why this setter exists, becuase this setter is not utilized anywhere in the code base, so people delete it and you got the idea etc.

It is a real experience, so I think providing inforamtion about mapping sometimes by annotation or by some other means will be great.

P.S: In `spring-data` we also can name columns with other names then the ones that are in db (eg using `@Column`). So I do not see any problem in here.

**Comment by philwebb** [comment]
FWIW I don't think an additional annotation would make things too much more confusing. I'll flag this issue for team attention to see what others think.

**Comment by wilkinsona** [comment]
I don't think it would add to much confusion either.

In addition to a "standard" Java class where a field could be annotated, we'd also need to consider things like records and Kotlin data classes so the implementation may not be completely straightforward.

**Comment by mhalbritter** [comment]
I like it, too.

**Comment by SledgeHammer01** [comment]
@quaff another example for needing this ... we have a property that we map to `spring.application.name` because that's a Spring requirement, but within the context of our code, it doesn't make sense to call it 'name'. Having tons of mappings in the config files will be a maintenance nightmare. It's something similar to `@JsonProperty` and `@Column`, so multiple examples of this already being done in Spring.

**Comment by BenchmarkingBuffalo** [comment]
Hi,
I am currently working on a solution for this and I would like to reuse the `@Name` Annotation, which has already been used in #22492.
It seems to be working with Java and Kotlin as far as my tests go and I can create a PR, which makes a distinction in the `JavaBeanBinder`.
Is this an acceptable way to go?

**Comment by BenchmarkingBuffalo** [comment]
Hi @wilkinsona,
sorry, I saw your comment too late and had already prepared an idea.
Just as suggestion, this might be one possible way to go.
No need to rush things.

**Comment by philwebb** [comment]
From a brief review of #39452 I think the PR might be a good starting point. We'll probably need updates to the configuration properties annotation processor to generate the correct metadata.

**Comment by wilkinsona** [comment]
Closing in favor of #39452.
