### ISSUE TITLE
UserInfoTokenServices should attempt to extract authorities and not hard code "ROLE_USER"

### ISSUE THREAD

**Issue by tgsoverly** [spring-projects/spring-boot#3711]
Bringing over https://github.com/spring-cloud/spring-cloud-security/issues/62 because I ran into the same issue.

---

Hi there,

Having an issue with the `UserInfoTokenServices`. I've got a Resource Server configured using `@EnableOAuth2Resource` and I've setup the `spring.oauth2.resource.userInfoUri` property to point to the '/me' endpoint on my separate Auth Server. From the logs, I see that the request, the `OAuth2AuthenticationProcessingFilter` processes, successfully authenticates but with the 'Granted Authorities: USER_ROLE' even though my user doesn't have that role. 

In my `HttpSecurity` on the `ResourceServerConfigurerAdapter` class, I restrict access to my API based on `ROLE_ADMIN` and as such I always get an 'Access Denied' response.

Had a look at the `UserInfoTokenServices` and when the `UsernamePasswordAuthenticationToken` is created in the `extractAuthenticaton()` method, the `Collection<GrantedAuthority>` is always set to: `AuthorityUtils.commaSeparatedStringToAuthorityList("ROLE_USER"))`.

I had a go at implementing a method to extract the authorities from the `userInfoEndpointUrl` response map:

```java
    private String[] getAuthorities(Map<String, Object> map) {
        @SuppressWarnings("unchecked")
        List<Map<String, String>> authorityList = (List<Map<String, String>>) map.get("authorities");

        List<String> authorities = new ArrayList<>();
        for (Map<String, String> authority : authorityList) {
            authorities.add(authority.get("authority"));
        }
        return authorities.toArray(new String[] {});
    } 
```

This seems to work when I feed that into the `UsernamePasswordAuthenticationToken`:

```
UsernamePasswordAuthenticationToken user = new UsernamePasswordAuthenticationToken(getPrincipal(map), "N/A", AuthorityUtils.createAuthorityList(getAuthorities(map)));
```

Is this an issue with the `UserInfoTokenServices`? Or am I just missing something in the configuration?

Cheers,
Nuno

**Comment by tgsoverly** [comment]
https://github.com/spring-projects/spring-boot/pull/3712

**Comment by snussbaumer** [comment]
I also ran into this issue, which is quite important IMHO : authorities should be available in the resource server !

**Comment by tgsoverly** [comment]
I wrote my own user info token service just injected.  I could send that to you so you know what to override.

**Comment by snussbaumer** [comment]
Thanks, but I already dit the same :-) ... 
I commented here to help raise a bit awareness on the issue. Now we are 3 !!

**Comment by snussbaumer** [comment]
Worth noting : the scopes are not populated either.

There is a workaround if your OAuth2 provider is a Spring @EnableAuthorizationServer : use the tokenInfo checkpoint instead of the userInfo checkpoint, and the stack will pick a ResourceServerTokenServices instead of a UserInfoTokenServices. This gives correct granted authorities and scopes.

Example : 
1 - In the resource server bootstrap.yml : 
```
Spring:
  oauth2:
    client:
      clientId: client_id
      clientSecret: client_secret
    resource:
      tokenInfoUri: http://authorization-server/uaa/oauth/check_token
```
2 - In the authorization server AuthorizationServerConfigurerAdapter : 
```
    @Override
    public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
        oauthServer.checkTokenAccess("isAuthenticated()");
    }
```
