### ISSUE TITLE
Make a JdbcClient bean when using @JdbcTest, @DataJpaTest or  @SpringBootTest

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-boot#37113]
When I use @JdbcTest, or @DataJpaTest or @SpringBootTest in a test,
a JdbcTemplate bean and a NamedParameterJdbcTemplate bean is automatically created 👍.
This is very handy: i can use these beans in my test code.

Is it possible to also create a JdbcClient bean ?

**Comment by quaff** [comment]
Have you tried v3.2.0-M2? It should be fixed by https://github.com/spring-projects/spring-boot/issues/36579 .

**Comment by hansdesmet** [comment]
I tried today with 3.2.0-SNAPSHOT.
I think the JdbcClient bean is created when you **run** your application, not when you **test** your application (with @JdbcTest).

**Comment by sivaprasadreddy** [comment]
I tried with both 3m2m0-M2 and 3.2.0-SNAPSHOT, not working. See https://github.com/spring-projects/spring-boot/issues/37114 for a reproducer.

**Comment by quaff** [comment]
It should be fixed by https://github.com/spring-projects/spring-boot/pull/37122

**Comment by hansdesmet** [comment]
I put a project on https://github.com/hansdesmet/jdbctestmakesnojdbcclientbean with a JUnit test which shows the problem.

**Comment by mhalbritter** [comment]
Superseded by #37122.
