### ISSUE TITLE
springboot docker-compose with docker-compose v1.x

### ISSUE THREAD

**Issue by splazit** [spring-projects/spring-boot#37121]
- springboot version: 3.1.3
- docker-compose version: 1.29.2

In the class DockerCli [(this line),](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/core/DockerCli.java#L165) which is the command: `docker-compose version --format json`  which is an invalid command for docker-compose version 1.X and it can't output json format.

**Comment by scottfrederick** [comment]
Duplicates #36618 and #36725. Please see [this comment](https://github.com/spring-projects/spring-boot/issues/36725#issuecomment-1665937875) on the latter issue.
