### ISSUE TITLE
Add support for virtual host in RabbitProperties.Stream

### ISSUE THREAD

**Issue by anessi** [spring-projects/spring-boot#37123]
The current version of [RabbitProperties.Stream](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L1197) currently does not allow to set a virtual host. It also does not consider the virtual host set on [RabbitProperties](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L88).

This is an issue in case a non-default virtual host (other than `/`) is used for streams.
Also the virtual host does not necessarily have to be the same as the virtual host that is set in [RabbitProperties](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L88). In our setup we use a dedicated virtual host for streams. For consistency reasons a fallback would make sense as implemented for the other properties.

The following changes are required to support this:
* Extend [RabbitProperties.Stream](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L1197) with a new property for the virtual host.
* Extend [RabbitStreamConfiguration](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitStreamConfiguration.java#L106) to map the property with a fallback to `properties::getVirtualHost`
```java
map.from(stream.getVirtualHost()).as(withFallback(properties::getVirtualHost)).whenNonNull().to(builder::virtualHost);
```

If you are fine with this change, I can try to create a pull request.

**Comment by mhalbritter** [comment]
Hey, thanks for the issue and that you're willing to create a PR. I think that's a good idea.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-projects/spring-boot/pull/37189.
