### ISSUE TITLE
about jedis4.x

### ISSUE THREAD

**Issue by HengCC** [spring-projects/spring-boot#37136]
My current Spring Boot version is 2.7.15, and it should include jedis version 3.8.0 by default. However, I intend to use the search functionality provided in jedis 4. When I attempted to manually update the jedis dependency to version 4.x, the application failed to start. It couldn't find the class file "redis.clients.jedis.JedisShardInfo," as this file has been removed in jedis 4. Is there a way to resolve this issue? Unfortunately, we are unable to upgrade to Spring Boot 3.x at the moment.

**Comment by wilkinsona** [comment]
As far as I can tell, Spring Boot itself does not refer to `JedisShardInfo` so I don't think there's anything that can be done in Spring Boot to help you. You should look at the stack trace when the failure occurs, identify the code that depends on `JedisShardInfo`, and ask the maintainers of that code. In a Spring Boot application, it's likely to be `JedisConnectionFactory` that is part of [Spring Data Redis](https://github.com/spring-projects/spring-data-redis).

**Comment by HengCC** [comment]
Perhaps the version of Spring Data Redis used in Spring Boot 2.7.15 might not be compatible. Even if Spring Data Redis is fixed, it's possible that the version in Spring Boot's dependencies needs to be updated as well. I will also provide feedback there to see if there could be a solution. Thank you!
