### ISSUE TITLE
Spring Boot 2.7.X EOL dates

### ISSUE THREAD

**Issue by whgibbo** [spring-projects/spring-boot#37130]
Apologies if this not the correct place to post this question.  

Can somebody please clarify when Spring Boot 2.7.x (16) OSS will go EOL.  As reading the [documentation ](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions) it infers that it is 27 months from the release date.

- 2.7.0 was released on the **19th May 2022**
  -  27 months from this date would mean an EOL date of **19 August 2024**

Is there a location where the EOL dates are listed ?

**Comment by wilkinsona** [comment]
Please see https://spring.io/projects/spring-boot#support. Note that we're offering extended commercial support for 2.7.x beyond the typical EOL date.

**Comment by whgibbo** [comment]
@wilkinsona  Thank you
