### ISSUE TITLE
Investigate hot-reloading of TLS certificates for embedded web servers

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#37131]
It would be cool to have a feature where the webserver could hot-reload the TLS certificates: all the existing connections still use the old certificate, while new connections use the new certificate.

Investigate if and how this is possible, starting with Tomcat. In that context we should also think about what triggers the certificate reload: files changed on file system, event from the application event system, etc.

**Comment by mhalbritter** [comment]
Details on how to get TLS certificates from Azure Key Vault: https://learn.microsoft.com/en-us/azure/developer/java/fundamentals/java-azure-keyvault-ssl-integration-jvm

Details how Azure Key Vault gets the certificates to Tomcat: https://learn.microsoft.com/en-us/azure/developer/java/fundamentals/java-azure-keyvault-tomcat-integration?tabs=linux

**Comment by philwebb** [comment]
Related Tomcat issue https://bz.apache.org/bugzilla/show_bug.cgi?id=65770

**Comment by nebhale** [comment]
Additional prior art from the Cloud Foundry Java Buildpack: https://github.com/cloudfoundry/java-buildpack-security-provider.

**Comment by Hakky54** [comment]
Maybe this is sort of related to: https://github.com/spring-projects/spring-boot/issues/5450 for hot reloading tls certificates.
I managed to get spring boot with netty, jetty and untertow working with ssl reloading, however it is quite easy to keep the existing connections with the old certificates aka retaining the ssl session for a period till it is expired and enforcing new connections with the new certificates.

**Comment by mhalbritter** [comment]
Implemented in https://github.com/spring-projects/spring-boot/pull/37808
