### ISSUE TITLE
Support new CSP auth method for Wavefront (AOA)

### ISSUE THREAD

**Issue by oppegard** [spring-projects/spring-boot#37165]
Wavefront has integrated into VMware's [CSP](https://docs.vmware.com/en/VMware-Cloud-services/index.html) authentication system, and the `wavefront-sdk-java` library has been updated to support that. We would like spring-boot to support this authentication method as well.

The release version of `wavefront-sdk-java` with these changes is `3.4.0`.

There are two types of CSP authentication: server-to-server tokens and user-api-tokens. We envision the changes looking something like this:

- CSP User API Token
  - `management.wavefront.csp.api-token`
  - In WavefrontSenderConfiguration, something like `new Builder(properties.getEffectiveUri().toString(), properties.getCspApiTokenOrThrow()).useTokenForCSP()`

- CSP Server to Server OAuth
  - `management.wavefront.csp.client-id` and `management.wavefront.csp.client-secret` (and an optional `management.wavefront.csp.org-id`)
  - In WavefrontSenderConfiguration, something like `new Builder(properties.getEffectiveUri().toString(), properties.getCspClientIdOrThrow(), properties.getCspClientSecretOrThrow())`
  - If the optional OrgID is provided, calling `builder.cspOrgId(properties.getCspOrgIdOrThrow())`

Thank you!

– @oppegard and @warshawd

**Comment by scottfrederick** [comment]
Blocked on https://github.com/micrometer-metrics/micrometer/issues/4054

**Comment by mhalbritter** [comment]
Micrometer has merged Micrometer has merged https://github.com/micrometer-metrics/micrometer/pull/4102, which adds an `apiTokenType` on the Wavefront config. Boot needs to make this configurable through properties.

**Comment by mhalbritter** [comment]
Our auto-configured `WavefrontSender` is not picking up the configuration property.
