### ISSUE TITLE
@Data not working with Spring Boot 3

### ISSUE THREAD

**Issue by lohitakshay35** [spring-projects/spring-boot#37162]
I upgraded my spring boot project from 2.3 to 3.1 , I do not get any red markers in my code,but when I try to build the project, I get these errors:
![image](https://github.com/spring-projects/spring-boot/assets/49298833/1e4bbb79-cefa-452b-b7b6-e7508b689373)

Lombok works in STS:
![image](https://github.com/spring-projects/spring-boot/assets/49298833/2712b5e0-24a2-4d7e-acc6-aaa4b4406b80)

The build works upto spring boot version 3, but when I change it to 3, These errors pop up. But when I manually type in the getters and setters, the errors go away. Is there any fix to this?

![image](https://github.com/spring-projects/spring-boot/assets/49298833/85c4f34a-e04c-43ad-9d95-37e328dcfabe)

![image](https://github.com/spring-projects/spring-boot/assets/49298833/3b4e4a70-50b7-46c9-b1fe-ab28b3237247)

**Comment by bclozel** [comment]
Sorry but this is most likely linked to your build or IDE setup.
Please try creating a project on https://start.spring.io (try [this link](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.1.3&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=lombok)) for example).

You can also get help on StackOverflow if you share the content of your build file and the actual annotated class. Please avoid screenshots.

Thanks!

**Comment by lohitakshay35** [comment]
@bclozel Yeah I've tried to create another spring boot 3 project and the maven build was successful, I've gone through many StackOverflow questions but no luck.Thanks for the reply!
