### ISSUE TITLE
mvn -Pnative spring-boot:build-image error

### ISSUE THREAD

**Issue by pigping88** [spring-projects/spring-boot#37177]
[creator]     Warning: The USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM environment variable is deprecated and might be removed in a future release. Please refer to the GraalVM release notes.
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     GraalVM Native Image: Generating 'com.example.demo.DemoApplication' (static executable)...
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     This command is not for general use and should only be run as the result of a call to
[INFO]     [creator]     ProcessBuilder.start() or Runtime.exec() in a java application
[INFO]     [creator]     
[INFO]     [creator]     [1/8] Initializing...                                            (0.0s @ 0.11GB)
[INFO]     [creator]     Error: Collecting native-compiler info with '/usr/bin/gcc -v' failed
[INFO]     [creator]     Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
[INFO]     [creator]     Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]         6.5s (9.3% of total time) in 30 GCs | Peak RSS: 0.69GB | CPU load: 0.99
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Finished generating 'com.example.demo.DemoApplication' in 1m 1s.
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1

**Comment by wilkinsona** [comment]
Buildpacks do not yet have official support for M1 Macs. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#building-container-images for details.
