### ISSUE TITLE
server.tomcat.maxSwallowSize  not working

### ISSUE THREAD

**Issue by 734839030** [spring-projects/spring-boot#37181]
server.tomcat.maxSwallowSize  not working when post json

**Comment by wilkinsona** [comment]
Without any information about the version of Spring Boot that you're using, how the POST request is being made, and how you have determined that max swallow size isn't working, we're not going to be able to help you.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by 734839030** [comment]
I am tried spring boot version with 2.7.11 and 3.1.13.

![image](https://github.com/spring-projects/spring-boot/assets/12107198/e01e2040-f623-4632-b064-281d81dbd956)
![image](https://github.com/spring-projects/spring-boot/assets/12107198/f327677d-329b-40ce-95ff-1041ba9ce539)
![image](https://github.com/spring-projects/spring-boot/assets/12107198/476fc526-02dc-462b-b614-b2c7e5660cc4)

**Comment by 734839030** [comment]
minimal demo .
curl -X 'POST' \
		  'http://localhost:8080/say' \
		  -H 'accept: */*' \
		  -H 'Content-Type: application/json' \
		  -d '{
		  "msg": "hello"
		  }'
[](url)
[demo.zip](https://github.com/spring-projects/spring-boot/files/12508770/demo.zip)

**Comment by wilkinsona** [comment]
You aren't POSTing a form so `max-http-form-post-size` does not apply. Therefore, there's no opportunity for `max-swallow-size` to be applied. Please read the descriptions of `maxPostSize` and `maxSwallowSize` in [the Tomcat documentation](https://tomcat.apache.org/tomcat-10.0-doc/config/http.html) to learn more about how Tomcat handles each of these settings.
