### ISSUE TITLE
Spring Boot does not start after upgrading to 3.1.3 from 2.7.6

### ISSUE THREAD

**Issue by Smedzlatko** [spring-projects/spring-boot#37198]
Hi, I am sorry for vague description of this issue but I would be glad for any ideas what might have happened after upgrading to Spring Boot v3.

I am trying to migrate to Spring Boot v3 from v2 and my application does not start after running `gradle bootRun` anymore. It does display `BUILD SUCCESS`, though.

This is the whole log when starting the app:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.3)

Disconnected from the target VM, address: 'localhost:42803', transport: 'socket'
Connected to the target VM, address: '127.0.0.1:39009', transport: 'socket'

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 57s
```

I tried debugging the `run` method but it ends at `SpringApplicationListeners::doWithListeners` where it jumps to another thread and finish without exceptions so it is difficult to figure out what is happening.

**Comment by mhalbritter** [comment]
Hello,

unfortunately it's impossible to tell from these logs what went wrong. 
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by Smedzlatko** [comment]
Thanks, I will investigate further. I suppose it must be some specific clash of dependencies so probably will have to do this on my own.
