### ISSUE TITLE
Add Awaitility to spring-boot-starter-test

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#37195]
Awaitility is generally useful for testing so we should consider adding it as a spring-boot-test dependency.

**Comment by vpavic** [comment]
I was just about to raise this myself when stumbled upon this issue.

Awaitility is one of testing dependencies that I regularly add to nearly all the projects, so it would be nice if `spring-boot-starter-test` would take care of this.

It was hinted in https://github.com/spring-projects/spring-boot/issues/18205#issuecomment-530436254 that this addition could be considered in the future, but it seems this topic wasn't brought up in the meanwhile.
