### ISSUE TITLE
Error on init a clean project with JRebel

### ISSUE THREAD

**Issue by tiarebalbi** [spring-projects/spring-boot#3722]
I was using the current SNAPSHOT version and i noted when i start the application with JRebel i'm having problem.

This problem happens only with JRebel (6.2.1)

Follow below more information:
https://gist.github.com/tiarebalbi/7e8dd193578a135180c3

**Comment by snicoll** [comment]
And you're not having the problem with a non-snapshot version? It would be interesting to share whether or not the same project works with another version.

**Comment by henri5** [comment]
It should be fixed in the nightly build - https://zeroturnaround.com/software/jrebel/download/nightly-build/

**Comment by wilkinsona** [comment]
@henri5 Thanks for the info
@tiarebalbi Sounds like this is a JRebel issue that's been fixed so I'm going to close this issue. Please comment here if that's not the case and we can re-open it.

**Comment by tiarebalbi** [comment]
@snicoll i'll do the test.
@henri5 yes, i agree with you too.
@wilkinsona i'll try with the nightly build.
