### ISSUE TITLE
After upgrading to spring boot version 3.1.3 from 2.6.0 a warning is printed in the logs when receiving a kafka message "Foreign deserialization exception header in (*************) ignored; possible attack? " 

### ISSUE THREAD

**Issue by joakim-eriksson** [spring-projects/spring-boot#37241]
We are in the process of upgrading from 2.6 to 3.1.3. When a server using 2.6 sends a kafka message, the receiving server using 3.1.3 version of spring boot, prints the following warning in the log.

WARN org.springframework.kafka.listener.KafkaMessageListenerContainer - Foreign deserialization exception header in (********) ignored; possible attack? I could not see any difference between messages produced by spring boot 2.6 or 3.1.3. 

Am I missing something? Or are messages produced by spring boot 2.6 not compatible with 3.1.3

**Comment by wilkinsona** [comment]
`KafkaMessageListenerContainer` is part of Spring Kafka which is managed as a [separate project](https://github.com/spring-projects/spring-kafka).
