### ISSUE TITLE
Dev tools doesn't switch on the H2 console auto-configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3726]
I am working on a [sample project](https://github.com/snicoll-scratches/modern-component-design-spring-4.2) using M3 with no particular option and the `h2-console` does not show up as it should.

I can see in `/env` that the property is enabled

```
refresh: {
spring.mustache.cache: "false",
spring.h2.console.enabled: "true",
spring.groovy.template.cache: "false",
spring.thymeleaf.cache: "false",
spring.freemarker.cache: "false",
spring.velocity.cache: "false",
server.session.persistent: "true"
},
```

However the auto-config reports that

```
[
{
condition: "OnClassCondition",
message: "@ConditionalOnClass classes found: org.h2.server.web.WebServlet"
},
{
condition: "OnWebApplicationCondition",
message: "found web application StandardServletEnvironment"
},
{
condition: "OnPropertyCondition",
message: "@ConditionalOnProperty missing required properties spring.h2.console.enabled "
}
],
```

Could it be that the Devtools BPP runs _too late_?

**Comment by wilkinsona** [comment]
> Could it be that the Devtools BPP runs too late?

Bingo. Any `@ConditionalOnProperty` on a `@Configuration` class is evaluated when `ConfigurationClassPostProcessor` is called. `ConfigurationClassPostProcessor` is `PriorityOrdered` so it runs very early, before devtools' BFPP has even been registered.
