### ISSUE TITLE
VelocityLayoutViewResolver incompatible in M3

### ISSUE THREAD

**Issue by timcolson** [spring-projects/spring-boot#3729]
In M1/M2 the VelocityLayoutViewResolver could be setup in a config that extended VelocityAutoConfiguration.VelocityWebConfiguration, but now in M3, looks like an EmbeddedVelocityViewResolver is expected which means VelocityLayoutViewResolver is now an incompatible type. (FYI - VelocityLayoutViewResolver is a simple and elegant way to insert html body content into a common HTML page that holds the layout.)

```
import org.springframework.boot.autoconfigure.velocity.VelocityAutoConfiguration;
import org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityViewResolver;
import org.springframework.web.servlet.view.velocity.VelocityLayoutViewResolver;

@Configuration
public class VelocityViewConfig extends VelocityAutoConfiguration.VelocityWebConfiguration {

    @Bean(name = "velocityViewResolver")
    public VelocityLayoutViewResolver velocityViewResolver() {
        VelocityLayoutViewResolver resolver = new VelocityLayoutViewResolver();
        this.properties.applyToViewResolver(resolver);
        resolver.setLayoutUrl("layout/default.vm");
        return resolver; // incompatible type
    }
}
```

Options?

**Comment by snicoll** [comment]
What's the problem exactly? `EmbeddedVelocityViewResolver` is a `VelocityViewResolver` and `VelocityLayoutViewResolver` is as well. Nowhere in the code we cast to `EmbeddedVelocityViewResolver`.

Are you having an exception or something? If so, please share it.

**Comment by timcolson** [comment]
Sorry, it was late, should have added the compilation error:
```
Error:(12, 39) java: velocityViewResolver() 
in org.directoryx.VelocityViewConfig cannot override velocityViewResolver() 
in org.springframework.boot.autoconfigure.velocity.VelocityAutoConfiguration.VelocityWebConfiguration
return type org.springframework.web.servlet.view.velocity.VelocityLayoutViewResolver 
is not compatible with org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityViewResolver
```

In VelocityAutoConfiguration.VelocityWebConfiguration, it's returning an EmbeddedVelocityViewResolver, instead of a VelocityViewResolver, so that seems to be why the override fails.
```
	@Bean
		@ConditionalOnMissingBean(name = "velocityViewResolver")
		@ConditionalOnProperty(name = "spring.velocity.enabled", matchIfMissing = true)
		public EmbeddedVelocityViewResolver velocityViewResolver() {
			EmbeddedVelocityViewResolver resolver = new EmbeddedVelocityViewResolver();
			this.properties.applyToViewResolver(resolver);
			return resolver;
		}
```

**Comment by snicoll** [comment]
That's not how you should register your own customizations. What you want is a way to set the layoutUrl via configuration and you'll be good.

This is how you should write your code for the time being

```java
@Configuration
public class MyConfiguration {

    @Bean(name = "velocityViewResolver")
    public VelocityLayoutViewResolver velocityViewResolver(VelocityProperties properties) {
        VelocityLayoutViewResolver resolver = new VelocityLayoutViewResolver();
       properties.applyToViewResolver(resolver);
        resolver.setLayoutUrl("layout/default.vm");
        return resolver; // incompatible type
    }

}
```

**Comment by snicoll** [comment]
See #3732

**Comment by timcolson** [comment]
Thanks @snicoll for the help/instruction! Apologies for opening an issue against M3 instead of a StackOverflow question first. Figured since it worked in M1/M2 but not M3 it wasn't our code.

**Comment by snicoll** [comment]
no worries. This brings an interesting use case :)
