### ISSUE TITLE
New releases in all branches?

### ISSUE THREAD

**Issue by MentalFS** [spring-projects/spring-boot#37341]
I'm watching this repository and today I got 59 notifications for new releases from as it seems, every branch or maybe even every version that was ever released.

Right now the Github page states the latest release as [Version v1.0.0.RELEASE](https://github.com/spring-projects/spring-boot/releases/tag/v1.0.0.RELEASE).

It looks like only spring-boot-cli was re-released with new binaries. Since I'm not expecting such old versions to be maintained at all I wanted to ask: is this supposed to happen?

**Comment by philwebb** [comment]
Thanks for letting us know. This is an unfortunate side-effect of fixing #37275

**Comment by JohnNiang** [comment]
Hi @philwebb , please rectify the `latest` release to [v3.1.3](https://github.com/spring-projects/spring-boot/releases/tag/v3.1.3) instead of [v1.0.0.RELEASE](https://github.com/spring-projects/spring-boot/releases/tag/v1.0.0.RELEASE).

**Comment by philwebb** [comment]
Thanks @JohnNiang, Done!
