### ISSUE TITLE
Provide auto-configuration for OpenTelemetry logs

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#37355]
While we make it easy for users to contribute a `SdkLoggerProvider` (see #36545), we don't have full-fledged auto-configuration for OpenTelemetry logging. In this issue, should add auto-configuration for `SdkLoggerProvider`.

There are also appenders for [Logback](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library) and [Log4j2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library).

**Comment by making** [comment]
Loki 3.0 now supports native OTLP ingestion.
https://grafana.com/blog/2024/04/09/grafana-loki-3.0-release-all-the-new-features/

Isn't it a good time to support this feature?

**Comment by scottfrederick** [comment]
Closing in favor of #40961
