### ISSUE TITLE
H2 console autoconfig needs to set X-Frame-Options config in Spring Security

### ISSUE THREAD

**Issue by alexhutnik** [spring-projects/spring-boot#3735]
When Spring Security is on the classpath, H2 console is unavailable due to Same-Origin defaults in Spring Security.

Error message from Chrome console:
Refused to display 'http://localhost:8080/h2-console/header.jsp?jsessionid=[SESSION ID]' in a frame because it set 'X-Frame-Options' to 'DENY'.

No special Spring Security config other than an in-memory auth provider.  I also disabled CSRF due to issue #3734

**Comment by wilkinsona** [comment]
That should already happen. I wonder if you're being affected by #3726. Have you explicitly set `spring.h2.console.enabled=true`? Sadly, the auto-configuration won't kick in without it at the moment.

**Comment by alexhutnik** [comment]
Yes.  See #3734.

**Comment by wilkinsona** [comment]
The root cause of this issue will be the same as #3734. Closing as a duplicate.
