### ISSUE TITLE
Consider setting spring.resources.cache-period=0 when Devtools is enabled

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3739]

**Comment by bclozel** [comment]
+1
Most browser devtools have options to disable cache (i.e. send a `Cache-Control: no-cache` in the HTTP request).

**Comment by cfinucane** [comment]
As a newcomer to Spring Boot, this magic behavior really confused me.  

Would you consider adding a note to https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html that points out the existence of https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-property-defaults ?

**Comment by snicoll** [comment]
@cfinucane this issue is closed. Could you please create a new issue with your request? Having said that, I don't think that updating the appendix is the right option.
