### ISSUE TITLE
Provide public methods and constructors for ExecutableArchiveLauncher

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3740]
We need to write a generic fat-jar launcher in Spring Cloud Stream. Currently it is re-using a lot of `ExecutableArchiveLauncher` which is nice, but we can't initialize it with an `Archive` without duplicating the package because the constructor is package private. Also the `launch(String[])` method could be public for this kind of use case.

cc @ilayaperumalg @mbogoevici

**Comment by ilayaperumalg** [comment]
Submitted PR: https://github.com/spring-projects/spring-boot/pull/3741

**Comment by wilkinsona** [comment]
Duplicates #3741
