### ISSUE TITLE
Refactor PemPrivateKeyParser to use DerElement

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#37426]
The `PemPrivateKeyParser` uses a brute-force approach to find a suitable algorithm to parse a PEM-encoded key. This could be improved by using the `DerElement` class to read the ASN.1 and find out what type of key this is. This works for all PKCS#8 keys.

**Comment by Wzy19930507** [comment]
@mhalbritter Hello, I see the oids are maintained in KnownOIDs, can I refer to it and convert oid into an algorithm to solve this problem?

such as 
```
AlgName algName = spring.boot.KnownOIDs.getAlgName(int[] RSA_ALGORITHM);
new PKCS8EncodedKeySpec(bytes, algorithmName);
```

**Comment by philwebb** [comment]
Closing in favor of PR #39162. Thanks @Wzy19930507
