### ISSUE TITLE
Cannot deploy to Cloud Foundry after upgrade 1.3.0M2 -> M3

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#3745]
When deploying to Cloud Foundry, the embedded web server (Undertow in my case) must use the port defined in the PORT env variable. Simply deploying the repackaged jar to CF used to work for M2.
After an upgrade to M3, Undertow always starts on its default port 8080, which results in an error: 'Instance (index 0) failed to start accepting connections'. This issue is caused by CF checking if the application listens on the port it defined for it, and if it doesn't, it's an error and the app is killed.
I'm not sure if this is a Boot issue, or maybe Undertow's (I think M3 upgrades Untertow, among others).

**Comment by wilkinsona** [comment]
Thanks for the report. The Java build pack maps the `PORT` environment variable to the `SERVER_PORT` environment variable.

Running the Undertow sample:

 - `java -DSERVER_PORT=8888 -jar target/spring-boot-sample-undertow-1.3.0.M3.jar` uses 8080
 - `java -Dserver.port=8888 -jar target/spring-boot-sample-undertow-1.3.0.M3.jar` uses 8888

This looks like a Boot issue to me.

**Comment by wilkinsona** [comment]
`DefaultPropertyNamePatternsMatcher` is created with a single name (`server`), two delimiters (`_` and `.`) and `ignoreCase` set to `false`. This causes it to consider `SERVER_PORT` as not matching so it's not included in the property values used for the binding.
