### ISSUE TITLE
Remove sourceCompatibility/targetCompatibility blocks from Gradle plugin integration tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#37453]
A lot have this:

```
java {
	sourceCompatibility = '1.8'
	targetCompatibility = '1.8'
}
```

**Comment by wilkinsona** [comment]
I'm not sure that they should be removed. In 3.0.x and later, their values should probably be changed to `17` instead.

**Comment by scottfrederick** [comment]
It turns out a small minority of Gradle integration test build files have the compatibility blocks, and the test run fine without them, so we'll remove them all.
