### ISSUE TITLE
Environment Variable SERVER_PORT is ignored after upgrading to 1.3.0.M3

### ISSUE THREAD

**Issue by rreitmann** [spring-projects/spring-boot#3746]
Hi,

today we tried to upgrade to 1.3.0.M3, however deployment to Pivotal Web Services failed cause the SERVER_PORT environment variable (set by Pivotal) seems to be ignored and our tomcat starts on port 8080.

Regards,

René

**Comment by wilkinsona** [comment]
Sorry for the trouble. This should be fixed in the latest snapshots. See #3745.
