### ISSUE TITLE
Enable graceful shutdown by default

### ISSUE THREAD

**Issue by Sineaggi** [spring-projects/spring-boot#37495]
When running in Kubernetes if an application is requested to shutdown, it makes sense to want to handle in-flight connections gracefully during shutdown.

Now that the graceful flag has existed in spring boot for a while can we make it the default?

**Comment by philwebb** [comment]
Thanks for raising this @henry701. Given the feature has been there for a while, seems stable, and is able to be toggled easily, we're going to try to change the default for our next milestone.
