### ISSUE TITLE
Add configuration option for maxSpareThreads

### ISSUE THREAD

**Issue by zxkane** [spring-projects/spring-boot#3753]
Below attributes are listed in [doc](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) for tomcat,

```
server.tomcat.access-log-pattern= # log pattern of the access log
server.tomcat.access-log-enabled=false # is access logging enabled
server.tomcat.compression=off # is compression enabled (off, on, or an integer content length limit)
server.tomcat.compressable-mime-types=text/html,text/xml,text/plain # comma-separated list of mime types that Tomcat will compress
server.tomcat.internal-proxies=10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\
        192\\.168\\.\\d{1,3}\\.\\d{1,3}|\\
        169\\.254\\.\\d{1,3}\\.\\d{1,3}|\\
        127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3} # regular expression matching trusted IP addresses
server.tomcat.protocol-header=x-forwarded-proto # front end proxy forward header
server.tomcat.protocol-header-https-value=https # value of the protocol header that indicates that the incoming request uses SSL
server.tomcat.port-header= # front end proxy port header
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.basedir=/tmp # base dir (usually not needed, defaults to tmp)
server.tomcat.background-processor-delay=30; # in seconds
server.tomcat.max-http-header-size= # maximum size in bytes of the HTTP message header
server.tomcat.max-threads = 0 # number of threads in protocol handler
server.tomcat.uri-encoding = UTF-8 # character encoding to use for URL decoding
```

Could you also support more tomcat attributes, such as `maxSpareThreads` and `minSpareThreads`?

https://tomcat.apache.org/tomcat-8.0-doc/config/http.html

Or does **Spring boot** already implicitly support them like `server.tomcat.minSpareThreads`?

**Comment by snicoll** [comment]
`minSpareThreads` does not exist anymore. We provide configuration properties for the most used options, I am not sure `maxSpareThreads` is one of them. You can always customize the connector yourself by providing your own `TomcatEmbeddedServletContainerFactory`

**Comment by wilkinsona** [comment]
`maxThreads` has always been configurable. `minSpareThreads` can now be configured too (see https://github.com/spring-projects/spring-boot/commit/34eb3695e4ec1393e82f6995b4dfac3f9e79ce9a)
