### ISSUE TITLE
Restore Jolokia support now that it is compatible with Jakarta EE 9+

### ISSUE THREAD

**Issue by tadayosi** [spring-projects/spring-boot#37568]
The Jolokia endpoint was dropped from Spring Boot 3 because it didn't yet support Servlet API 5+ #28704.

Now the Jolokia project is working on 2.0 release, which aims at supporting Jakarta EE 9+ including Servlet API 5 jolokia/jolokia#568. It would be great if you could restore the Jolokia endpoint for Spring Boot 3 once the version is released.

Thanks.

**Comment by wilkinsona** [comment]
Thanks, but we don't need an issue for this as it'll just sit blocked indefinitely. We're already keeping an eye on the Jolokia project's progress (by watching https://github.com/jolokia/jolokia/issues/451 for example). As a when there's a release available, or even a date planned for such a release, we'll look more closely at possibly restoring support for Jolokia.

**Comment by wilkinsona** [comment]
Looking more closely at Jolokia 2.x, the project now provides its own auto-configuration. Thanks to the Jolokia team's efforts, this means that there's nothing left for us to do here. As Jolokia now [depends on Spring Boot](https://github.com/jolokia/jolokia/blob/08902b1fb84d5c1e4e48154fee9c62f59b93ac9b/support/spring/pom.xml#L78-L92) we avoid referring to it from our published artifacts to avoid a circular dependency between the two projects.
