### ISSUE TITLE
YamlMapFactoryBean wraps integer keys with square brackets

### ISSUE THREAD

**Issue by anthofo** [spring-projects/spring-boot#3757]
Hi,

Given the following yaml file : 
```
5804: height
24103: weight
```

yamlFactory.getObject() returns a map in which the integer keys are all wrapped with square brackets : 
```
"[5804]" -> "height"
"[24103]" -> "weight"
```

I expected that YamlMapFactoryBean would convert the integer keys into Strings, but without brackets.

**Comment by wilkinsona** [comment]
`YamlMapFactoryBean` is now part of Spring Framework. Please open an issue in [their JIRA](https://jira.spring.io/browse/SPR)
