### ISSUE TITLE
Managed types for Neo4j are not used in Neo4j Data auto configuration.

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#37573]
The auto configuration for imperative and reactive Spring Data variant still uses 

```java
Set<Class<?>> initialEntityClasses = new EntityScanner(applicationContext).scan(Node.class,
				RelationshipProperties.class);
```

as initial entity classes for the mapping context. This works fine in JVM mode and to some extent in native mode. It fails however with certain inheritance scenarios (See https://github.com/spring-projects/spring-data-neo4j/issues/2798).

The solution is to use populate the mapping context with the managed entities and I'll have a PR up in a moment.

**Comment by wilkinsona** [comment]
Closing in favor of #37574. Thanks for the PR, @michael-simons.

**Comment by michael-simons** [comment]
Sure, my pleasure. And sorry for not understanding how this is supposed to work to begin with.
