### ISSUE TITLE
Fail configuration property metadata processing when additional metadata has unexpected content

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#37597]
Some additional metadata currently has no effect as it's malformed. For example https://github.com/spring-projects/spring-boot/issues/37596 is caused by a default value being declared within `hints` instead of `properties`. We should consider making such errors cause a build failure so that they can be caught early.

**Comment by wilkinsona** [comment]
We could either do this in the annotation processor and it would benefit everyone (and potentially break some people's builds if, for some reason, they want to have custom content in the file) or we could do it in our own build as an addition to `CheckAdditionalSpringConfigurationMetadata` and it would only benefit us but wouldn't break anyone's build.

**Comment by philwebb** [comment]
We discussed this today and we think that we should add this functionality to the annotation processor.
