### ISSUE TITLE
Spring Boot API Modules

### ISSUE THREAD

**Issue by cpuzicha** [spring-projects/spring-boot#37604]
Our software provides extension points that are supposed to re-use the usual Spring property binding.
To do so, we currently need to include the spring-boot.jar, which contains a lot of implementation details and which is the opposite of a stable API.

It would be great, if there were dedicated API jars that contain the stable Annotations and Interfaces, e.g.:
* `org.springframework.boot.context.properties.bind.DefaultValue`
* `org.springframework.boot.context.properties.EnableConfigurationProperties`
* all annotations from `org.springframework.context.annotation`

**Comment by philwebb** [comment]
I'm sorry but we prefer to keep the annotations and interfaces co-located with the implementation code.
