### ISSUE TITLE
Expose 'highlight_sql' Hibernate option to show colourized SQL statements in console 

### ISSUE THREAD

**Issue by NathanQingyangXu** [spring-projects/spring-boot#37617]
**Affects:** \<Spring Framework v5>

---

Hibernate exposed the fancy 'SQL highlight' feature since v5.5 (see the PR at https://github.com/hibernate/hibernate-orm/pull/3553). It uses ANSI escape codes to make the logged SQL statements more readable. Below is an example (the SQL keywords are highlighted with special colors)

<img width="772" alt="Screen Shot 2021-11-12 at 15 18 19" src="https://user-images.githubusercontent.com/8211458/141529806-f39c54a3-5c0e-4b68-b36a-d48f45d39ddf.png">

It seems a good idea to expose this Hibernate option, together with 'show_sql' and 'format_sql' options we have exposed already.

**Comment by wilkinsona** [comment]
We have a specific property for showing SQL as it's a setting on Spring Framework's `AbstractJpaVendorAdapter`. We don't, as far as I know, have a property for `format_sql` as it's Hibernate-specific.

As [described in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.data-access.jpa-properties), you can configure Hibernate specific properties using the `spring.jpa.properties` prefix. For example, to format and highlight SQL, add the following to your configuration:

```
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
```

Thanks anyway for the suggestion, but I don't think we should add a property specifically for highlighting SQL. The configuration shown above should be used instead.
