### ISSUE TITLE
Error in 1.3.0.M3 release notes: mainClass not mainClassName

### ISSUE THREAD

**Issue by msgilligan** [spring-projects/spring-boot#3764]
The [Gradle section of the 1.3.0.M3 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M3-Release-Notes#gradle) says that you can no longer use the `mainClassName` project property to specify the main class and that it should be moved to the `springBoot` closure like this:

    springBoot {
        mainClassName = 'com.example.YourApplication'
    }

But the `springBoot` closure expects a `mainClass` property  like this:

    springBoot {
        mainClass = 'com.example.YourApplication'
    }

**Comment by wilkinsona** [comment]
Thanks, I've corrected the release notes.
