### ISSUE TITLE
Spring Initializr Suggestions

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects/spring-boot#37641]
hi

i have suggestions for spring initializer :

1.  kotlin as default language
2.  kotlin gradle as default project build
3.  generate aplication.yml as default application properties 
4.  drop java version 8 & 11

**Comment by bclozel** [comment]
Thanks but start.spring.io is not managed here. See https://github.com/spring-io/start.spring.io

There is no need to create a new issue there for those suggestions: these are personal opinions and the team is driving these choices with data collected by the service. Such defaults are not just about community feedback.

Also see https://github.com/spring-io/start.spring.io/issues/1155
