### ISSUE TITLE
Use the term "uber jar" in reference documentation and javadoc 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#37653]
The term "uber jar" seems to be a more popular than "far jar", we should update our reference documentation and javadoc.

**Comment by bottlerocketjonny** [comment]
Hi! Can I work on this issue please? Looking to make my first contribution :)

**Comment by philwebb** [comment]
Thanks for the offer @bottlerocketjonny, but I already had a commit lined up for this one.
