### ISSUE TITLE
Relocate launcher classes to 'org.springframework.boot.loader.launch' package

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#37667]
Currently our loader classes are in the `org.springframework.boot.loader` package but they'd really be better in a dedicated `org.springframework.boot.loader.launch` package, especially if we want to make future changes to the code. We should be able to create new classes that call the existing ones without too much difficulty.

**Comment by steklopod** [comment]
@philwebb 
I faced with the error after update to Spring Boot 3.2.0.

I have 
```sh
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
```
<img width="778" alt="Снимок экрана 2023-12-09 в 16 06 37" src="https://github.com/spring-projects/spring-boot/assets/29500153/c89be68c-0f4b-4619-994a-a1f5cf2d5bb3">

So update to
```sh
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
```
solved the problem.

But there is no info in internet about it

**Comment by wilkinsona** [comment]
The change is [described in the release notes for Spring Boot 3.2](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support).
