### ISSUE TITLE
Clearly log active profiles on startup

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#3766]
I now do this in every spring boot application I create. It has added a lot of sanity to my development process and I think most every developer would appreciate this. In projects with many different profiles that can be turned off and on, this becomes crucial when trying to do debug after the fact. 

Maybe this should be part of the banner feature?

**Comment by jjzazuet** [comment]
+1. Thanks!

**Comment by shakuzen** [comment]
:+1:

**Comment by philwebb** [comment]
Very nice idea. Thanks for the suggestion.
