### ISSUE TITLE
@ServiceConnection is not found when used in an interface implemented by a test class

### ISSUE THREAD

**Issue by therealaleko** [spring-projects/spring-boot#37671]
Using the new `@ServiceConnection` does not work as I would expect when applied within an `interface`. It starts the container on a random port rather than my spring defined port.

`@DynamicPropertySource` does work as I expect.

```
public interface PostgresContainer {
  @Container
  //  @ServiceConnection
  PostgreSQLContainer<?> postgreSQLContainer = new PostgreSQLContainer<>("postgres:11.1");

  @DynamicPropertySource
  static void initialize(DynamicPropertyRegistry registry) {
    registry.add("spring.datasource.url", postgreSQLContainer::getJdbcUrl);
    registry.add("spring.datasource.username", postgreSQLContainer::getUsername);
    registry.add("spring.datasource.password", postgreSQLContainer::getPassword);
  }
}
```

**Comment by eddumelendez** [comment]
> It starts the container on a random port rather than my spring defined port.

Can you elaborate more? I think I didn't get it.

Take into account Testcontainer starts containers in random ports and `@ServiceConnection` maps the properties from the container to spring boot

**Comment by philwebb** [comment]
Thanks @eddumelendez, I was just writing the same thing! 

@therealaleko perhaps you could provide a sample application that shows the problem?

**Comment by therealaleko** [comment]
Please check the repo here. Thanks!
https://github.com/therealaleko/spring_boot_issue_37671

**Comment by eddumelendez** [comment]
Thanks! So, the ServiceConnection doesn't work when using interfaces

I think this like here 

https://github.com/spring-projects/spring-boot/blob/d310fb6fce1bceed55596cea70186e71eca77655/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/service/connection/ServiceConnectionContextCustomizerFactory.java#L57C1-L57C1

should change to `MergedAnnotations annotations = MergedAnnotations.from(field, SearchStrategy.TYPE_HIERARCHY);`

**Comment by andreasevers** [comment]
Would it also be possible to add support for inherited interfaces? At the moment the test class has to implement the interface directly, but ideally extending a superclass that implements the interface should work too.
I could submit a PR if this is something that could be accepted.

**Comment by philwebb** [comment]
Good spot @andreasevers, I've refined the search algorithm in e01e4f19129ba671ddcbb388efbb2eb2f7ae7d35

**Comment by andreasevers** [comment]
Wow, thanks Phil! This is great, using it right away!

**Comment by andreasevers** [comment]
Could this latest commit also get backported into 3.1.x perhaps?

**Comment by wilkinsona** [comment]
Good catch, @andreasevers. Thank you. I've done that in https://github.com/spring-projects/spring-boot/commit/fcb75b6a1e61dd1772eda2b8a5e40671314c8ff5.

**Comment by andreasevers** [comment]
Much appreciated 🙏

**Comment by therealaleko** [comment]
Thank you!
