### ISSUE TITLE
Spring boot 3.1.4 micrometer tracing duplicated traceIds

### ISSUE THREAD

**Issue by pakopako** [spring-projects/spring-boot#37744]
I am trying to set up tracing in my reactive (webflux) application using spring boot version 3.1.4. I noticed that often generated traceIds are duplicated, which I can see in application logs.

Therefore I created minimal reproducible example to test if it was an error with my configuration, but the same problem happens. Here is a screenshot with duplicated traceIds highlighted:

![image](https://github.com/spring-projects/spring-boot/assets/18292827/fc8c8b86-b7dc-4504-a757-adf9c72349fc)

Repository with the project: https://github.com/pakopako/tracing-problem
To reproduce just run the application, send GET request a bunch of times on http://localhost:8080/ and observe console output for duplicated traceIds.

Note: I noticed this problem happens on spring boot version 3.1.4. I tested on 3.1.3 and all traceIds seem to be unique.

**Comment by kzander91** [comment]
This was introduced with Micrometer Tracing 1.1.5 and is fixed in 1.1.6, see micrometer-metrics/tracing#363.

**Comment by bclozel** [comment]
Thanks for the information @kzander91 - closing this issue in favor of the Micrometer one.
