### ISSUE TITLE
Spring Native executable is not checking `logging.config` property, which points to a `logback-spring.xml` to write log to file.

### ISSUE THREAD

**Issue by KaeYan93** [spring-projects/spring-boot#37750]
Hi, 

After i built the executable and run it, it does not check the `logging.config` property in `application.properties` file. I tried to change the `logging.config` to wrong logback config file path, but no error comes out about it.

**Spring boot version**: 3.0.7
**Build method**: Using base image `ghcr.io/graalvm/graalvm-ce:22.3.1` to build exe with command `mvnw native:compile -Pnative`, with maven plugin `native-maven-plugin`
**Plugin configuration**:
```
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <configuration>
        <buildArgs>
            <arg>-H:+AddAllCharsets</arg>
            <arg>-H:+TraceSecurityServices</arg>
            <arg>-H:+ReportExceptionStackTraces</arg>
        </buildArgs>
    </configuration>
</plugin>
```

Is it the case that it will not check this property? I am pretty sure it works for jar file executable. If so, how do I make it configurable? My use case is that I need to deploy this app to Windows/Linux servers, whereby the file path can be different. 

Thanks,
Kae Yan

**Comment by wilkinsona** [comment]
As [described in the wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#logging), XML-based logging configuration is processed at build time and stored in the native image in a more efficient format. It therefore cannot be changed at runtime.
