### ISSUE TITLE
Loading YAML file to a Java Class

### ISSUE THREAD

**Issue by indaduke** [spring-projects/spring-boot#3776]
Not sure if this is an issue or if i'm just not going at it the right way.  My issue is that i'm trying to load YAML files in 2 ways.  One way is via the @configurationProperties and specifying a location.  This works great and the YAML gets loaded properly into my Java object. 

@Configuration
@ConfigurationProperties(locations = "classpath:config/page.yml")
public class PageDescriptor {
	private HashMap<String, PageConfig> pageConfigs;

	public PageDescriptor() {

	}

	public HashMap<String, PageConfig> getPageConfigs() {
		return pageConfigs;
	}

	public void setPageConfigs(final HashMap<String, PageConfig> pageConfigs) {
		this.pageConfigs = pageConfigs;
	}

Next i was trying to load other YAML files into the same object but via java code.  I approached it like this.

final PathMatchingResourcePatternResolver resourceResolver = new PathMatchingResourcePatternResolver();
		final Resource[] resources = resourceResolver
				.getResources("classpath*:com/**/page.yml");
		if (!((resources == null) || (resources.length == 0))) {
			for (final Resource resource : resources) {
				// final Yaml yaml = new Yaml();
				// final InputStream in = resource.getInputStream();
				// final PageDescriptor componentPageDescriptor = yaml.loadAs(in, PageDescriptor.class);
				// in.close();
				final YamlConfigurationFactory<PageDescriptor> factory = new YamlConfigurationFactory<PageDescriptor>(
						PageDescriptor.class);
				final Map<Class<?>, Map<String, String>> aliases = new HashMap<Class<?>, Map<String, String>>();
				
				factory.setResource(resource);
				factory.setExceptionIfInvalid(true);
				factory.setPropertyAliases(aliases);
				// factory.setValidator(validator);
				factory.setMessageSource(new StaticMessageSource());
				factory.afterPropertiesSet();
				final PageDescriptor componentPageDescriptor = factory.getObject();

While this loads the object as a PageDescriptor it does not load the HashMap<String, PageConfig> correctly it instead does HashMap<String, LinkedHashMap>.  Is there an easy way to simulate how the @ConfigurationProperties works in loading the YAML files?

below is the YAML file

---
#pageDescriptors:
  pageConfigs:
    Home:
      baseUrl: "${app.context-root}"
      configLocation: "${app.context-root}/static/app/src/scripts/pages/home/config.js"
      navDescriptorKey: "Default"
      defaultRoute: ""
      routes: 
        home: 
          path: ""
          linkKey: "home"
          views: 
            "content": 
              contentUrl: "${app.context-root}/home/view"

Thanks,
Josh

**Comment by wilkinsona** [comment]
We prefer to use GitHub issues for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

**Comment by indaduke** [comment]
Sorry about that.  I wasn't sure if it was an issue or not.  I've posted the question at stackoverflow http://stackoverflow.com/questions/32092684/how-do-i-load-a-yaml-file-programatically-the-same-way-as-using-configuationpro
