### ISSUE TITLE
Trailing slash is not inserted in context name

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3777]
Tomcat in Spring Boot is not inserting the trailing slash after context name at url.

It should be done automatically by server case is not specified.

Example:
/user would be changed to /user/ by server

**Comment by wilkinsona** [comment]
I assume you're referring to the server's context path? It's required that the path does not end with a slash. For example, Jetty contains the following logic:

```
else if (contextPath.length()>1 && contextPath.endsWith("/"))
        {
            LOG.warn(this+" contextPath ends with /");
            contextPath=contextPath.substring(0,contextPath.length()-1);
        }
```

**Comment by ofbizbrazil** [comment]
Ok, but why does it remove it? Is there any way to insert it back?
