### ISSUE TITLE
Upgrade to MSSQL JDBC 11.2.4.jre17

### ISSUE THREAD

**Issue by OleksandrShkurat** [spring-projects/spring-boot#37794]
MSSQL JDBC 10.2.3 and 11.2.3 are affected with the issue
https://github.com/microsoft/mssql-jdbc/issues/2103
It was addressed in appropriate hotfix releases 10.2.4 and 11.2.4

Please include 11.2.4 in the upcoming Spring-Boot 3.1.5

**Comment by wilkinsona** [comment]
11.2.4 (and 10.2.4) is not available from [Maven Central](https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/). There's no tag for it [on GitHub either](https://github.com/microsoft/mssql-jdbc/tags) As and when it is released, our dependency upgrade process will pick it up automatically. Until then, I'm going to close this issue as there's nothing we can do at this time.

**Comment by OleksandrShkurat** [comment]
Thank you for the fast response
