### ISSUE TITLE
Use `RedisSerializer.java(ClassLoader)` rather than `new JdkSerializationRedisSerializer(ClassLoader)`

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-boot#37800]
Currently, the `RedisReactiveAutoConfiguration` class ([source](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisReactiveAutoConfiguration.java#L51-L52)) in Spring Boot directly constructs an instance of `o.s.data.redis.serializer.JdkSerializationRedisSerializer`.

It would be better if Spring Boot used the `RedisSerializer.java(:ClassLoader)` method instead.  See [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/serializer/RedisSerializer.html#java(java.lang.ClassLoader)).

In this way, Spring Boot is not tied to any implementation detail from Spring Data Redis if or when Spring Data Redis decides to change the implementation class for Java-based serialization.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, John. It looks like we can make that change in 2.7.x onwards.

If `JdkSerializationRedisSerializer` is considered to be an implementation detail, perhaps it could, after a deprecation period, be made package-private?
