### ISSUE TITLE
Enable RemoteIpValve by default

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3782]
We used to enable it by default and went super cautious in 1.2 somewhere and disabled it. I think maybe that was over cautious because it only filters requests that come from a whitelist of "local" proxy IPs.

Alternatively could we log an error if we find an `X-Forwarded-*` header and the valve isn't installed.

Cc @rwinch

**Comment by php-coder** [comment]
What about enabling `ForwardedRequestCustomizer` for Jetty too?

**Comment by dsyer** [comment]
Sounds good (probably deserves a separate issue or even a pull request).

**Comment by rwinch** [comment]
@dsyer FWIW this issue has my +1 :)

**Comment by dsyer** [comment]
This didn't get enabled by default in M5. Re-opened.

**Comment by philwebb** [comment]
NOTE: This was reverted due to #4018
