### ISSUE TITLE
Create a richer API for PropertySource customization

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3783]
Users often need to modify the `Environment` `PropertySources` but they basically have to guess the best slot to insert a new `PropertySource` to give it the correct priority. We document the priorities of the "standard" property sources, but we don't provide a way to insert custom properties at specific points in that order. Often a user wants to just add a single k-v pair with "high but not highest" priority, or "low but not lowest", something like that.

**Comment by philwebb** [comment]
I think we should close this one for now and see how the new `ConfigData` import support works out. We can reopen it if imports aren't working for a specific use-case.
