### ISSUE TITLE
Issue with Java 1.6 Compatibility using Tomcat & gradle

### ISSUE THREAD

**Issue by sathishk** [spring-projects/spring-boot#3786]
**Description**
As per the documentation http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_use_tomcat_7_with_gradle
We shall enforce tomcat version for Spring Boot. However with the latest version (1.2.5.RELEASE) it seems this property is ignored

**Steps:**
Unzip the contents of **spring-java6-issue.zip** (https://jira.spring.io/browse/SPR-13368)
run **gradlew clean build**
run **java -jar build\libs\java6spring-1.0-SNAPSHOT.jar**

**Expected Result**
Spring Boot Application should start with **tomcat version 7.0.59**

**Actual Result:**
Spring Boot Application started with **tomcat version 8.0.23** (Ref: https://jira.spring.io/browse/SPR-13368)

**Note**
* If i change the build.gradle to use old version of **Spring Boot, 1.1.12.RELEASE, Then tomcat version is considered properly**.
* There are **no issues If i use maven** to build the application.

**Comment by wilkinsona** [comment]
The documentation that you have linked to is for Spring Boot 1.3, but you are using 1.2. It works when you use 1.1.x as it used Tomcat 7 by default. You need to follow [these instructions in the Spring Boot 1.2 docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_use_tomcat_7_with_gradle).
