### ISSUE TITLE
Gradle plugin uses to-be-deprecated API for getting and setting file permissions

### ISSUE THREAD

**Issue by jbartok** [spring-projects/spring-boot#37878]
Gradle 8.3 introduces a [new API for setting file permissions](https://docs.gradle.org/8.3/userguide/working_with_files.html#sec:setting_file_permissions).

We intend to deprecate the old, Unix mode based API in Gradle, but we can't do that until major Gradle plugins start using the new one.

For that reason would be good to upgrade this plugin to use Gradle 8.3 and switch internal code to the new API.

**Comment by wilkinsona** [comment]
Will querying the permissions using the new API show changes made using the old API?

**Comment by jbartok** [comment]
> Will querying the permissions using the new API show changes made using the old API?

Yes, both APIs are backed by the same internals. But, if you tell me a specific scenario you are interested in I can double check.

**Comment by wilkinsona** [comment]
> For that reason would be good to upgrade this plugin to use Gradle 8.3

Unfortunately, we can't do that due to our users' expectations for backwards compatibility.

> and switch internal code to the new API

It looks like we can call the new API using reflection when running on Gradle 8.3 and later.

**Comment by jbartok** [comment]
@wilkinsona thank you!
