### ISSUE TITLE
Support setting gradle provider values in `BuildInfoProperties`.`additional` map

### ISSUE THREAD

**Issue by SidB3** [spring-projects/spring-boot#37889]
Since the `buildInfo` task is primary configured via gradle, It would be nice if I can set set a gradle `Provider` in `additional` map. 

Example - 

``` gradle 
springBoot {
	buildInfo {
		properties {
			additional.set(mapOf(
				"frameworkVersion" to providers.gradleProperty("frameworkVersion")
			))
		}
	}
}
```

**Comment by wilkinsona** [comment]
Can you pleased expand a bit on why you think this would be nice? `frameworkVersion` is, presumably, a constant value so the benefit of it being computed lazily isn't clear to me.

**Comment by SidB3** [comment]
We have a need to show all `runtime` dependencies appended in one string  in `/actuator/info`. 

For this, I am currently using `project.afterEvaluate` and appending them to a local script variable and referring to this variable in the `bootInfo` task. 

If providers are supported I can avoid using `project.afterEvaluate` and directly refer to the task output here.
