### ISSUE TITLE
Excluded configuration classes that don't exist in classpath are shown in negative matches

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3790]
I've excluded some auto configuration classes:

```
spring.autoconfigure.exclude: \
	org.springframework.boot.autoconfigure.transaction.jta.AtomikosJtaConfiguration, \
	org.springframework.boot.autoconfigure.transaction.jta.BitronixJtaConfiguration, \
        ...
```

But they still are shown in `Negative matches` section:

```
Negative matches:
-----------------

   AtomikosJtaConfiguration
      - required @ConditionalOnClass classes not found: com.atomikos.icatch.jta.UserTransactionManager (OnClassCondition)

   BitronixJtaConfiguration
      - required @ConditionalOnClass classes not found: bitronix.tm.jndi.BitronixContext (OnClassCondition)

```

And the same story with other auto configuration classes that relies on the classes that don't present in classpath.

It looks like that `@ConditionalOnClass` are always evaluated despite my exclusions.

**Comment by wilkinsona** [comment]
Neither `org.springframework.boot.autoconfigure.transaction.jta.AtomikosJtaConfiguration` nor `org.springframework.boot.autoconfigure.transaction.jta.BitronixJtaConfiguration` is an auto-configuration class so they're unaffected by the exclude that you have configured. The auto-configuration class for JTA is `org.springframework.boot.autoconfigure.jta.JtaAutoConfiguration`. You can exclude that if you want to be sure that JTA is disabled. Or, alternatively (and more concisely), you could set `spring.jta.enabled: false`.
