### ISSUE TITLE
Upgrade to OkHttp 4.12.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#37908]

**Comment by lexek** [comment]
Hi @wilkinsona, I'm not entirely sure what the process is here, but can this also be ported to the next 3.1.x update?

**Comment by wilkinsona** [comment]
Generally speaking, we do not upgrade to a new minor version of a dependency in a maintenance version of Spring Boot. As such, we won't upgrade from OkHttp 4.11.0 to 4.12.0 in Spring Boot 3.1.x. If you want to upgrade manually, you can do so by setting the `okhttp.version` property. This requires the use of `spring-boot-starter-parent` with Maven or the `io.spring.dependency-management` plugin with Gradle.
