### ISSUE TITLE
Can't exclude FaviconConfiguration

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3791]
I have the following:

```
spring.autoconfigure.exclude: \
	org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter.FaviconConfiguration, \
	...
```

But this configuration are enabled:

```
Positive matches:
-----------------

   WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter.FaviconConfiguration
      - matched (OnPropertyCondition)


Exclusions:
-----------

   org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter.FaviconConfiguration

```

The only way to disable it is to add `spring.mvc.favicon.enabled: false` property. So, what's the problem and why I unable to exclude it?

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

**Comment by php-coder** [comment]
Hm.. for me it looks like a bug, because exclusion doesn't work in this case..

**Comment by wilkinsona** [comment]
`org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter.FaviconConfiguration` isn't an auto-configuration class. All auto-confguration classes are [listed in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#auto-configuration-classes).

**Comment by php-coder** [comment]
Ok, thank you. I've used classes from `--debug` output and I thought that they are autoconfiguration classes.
