### ISSUE TITLE
Add @ ConditionalOnMissingBean annotation on the graphQlRouterFunction bean

### ISSUE THREAD

**Issue by m1ngyuan** [spring-projects/spring-boot#37935]
🎁 Enhancement

When users have time, they need to rewrite routing rules so that they can do more custom actions; Add @ ConditionalOnMissingBean annotation on the graphQlRouterFunction bean.
 I hope my suggestion is useful to you

https://github.com/spring-projects/spring-boot/blob/79ab4c4fa787d8a9c46b52ae9db600977bd08d53/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/servlet/GraphQlWebMvcAutoConfiguration.java#L110

**Comment by bclozel** [comment]
Sorry but we cannot apply this enhancement. `RouterFunction` beans are the common way to contribute routes to the functional web framework. Applying this condition would turn this off as soon as there is a route contributed by some other component, even if it's got nothing to do with GraphQL.
