### ISSUE TITLE
Authentication object is not found in the SecurityContext during CRaSH command invocation

### ISSUE THREAD

**Issue by DzmitryShylovich** [spring-projects/spring-boot#3795]
If my CRaSH command invoke secured by @PreAuthorize annotation method it will fail with 
`Failed to execute: An Authentication object was not found in the SecurityContext` message.
Seems that there is no Authentication object in the SecurityContext during Crash command invocation.

Is this a CRaSH/Spring Boot bug? Any ideas?

Here is a showcase [project](https://github.com/DzmitryShylovich/crash-authentication).
To reproduce the issue:
1. run the application
2. access shell via `ssh -p 2002 test@localhost`
3. password: test
4. type command: `test ls`
After that you should get the error message in the console.

**Comment by wilkinsona** [comment]
Did you manage to figure out what was happening? If so, would you care to share what you did? Others may find it useful.

**Comment by DzmitryShylovich** [comment]
Yeah, after some research I figured out that this is a CRaSH API issue. They just not support authentication with Spring Security on every request. There is also no ability to retrieve currently authenticated user from CRaSHSession so it's impossible to create Authentication object and store it in SecurityContext.

**Comment by wilkinsona** [comment]
It's possible if you're comfortable with a little bit of reflection:

    Principal user = new DirectFieldAccessor(context.session).getPropertyValue('user')

**Comment by DzmitryShylovich** [comment]
Yeap. My current solution includes reflection and instrumentation, but it looks like dirty hacks =) 
I would like to have direct access to the currently authenticated user in CRaSH api or at least some integration with Spring Security.
