### ISSUE TITLE
Spring Boot + RestFull + REDIS -->SessionDestroyedEvent get userPrincipal

### ISSUE THREAD

**Issue by gabber3000** [spring-projects/spring-boot#3796]
How can I get the object (Principal) using the class SessionDestroyedEvent?
My code is as follows:

@Service
public class TestFilter implements ApplicationListener<ApplicationEvent> {
    @Autowired
    private UserDao userDao;

    @Override
    public void onApplicationEvent(ApplicationEvent event) {
        // TODO Auto-generated method stub
        if(event instanceof SessionDestroyedEvent) {
            SessionDestroyedEvent sdEvent = (SessionDestroyedEvent) event;  
      
            String session = sdEvent.getSessionId();
            System.out.println("session Id :  "+session);
            Principal auth <---- ????

        }

    }
}
Thanks for your help

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).
