### ISSUE TITLE
refresh endpoint causes CPU spikes

### ISSUE THREAD

**Issue by rajanigk** [spring-projects/spring-boot#37971]
spring-boot version: 3.1.4
spring-cloud version : 2022.0.3 ( same is observed since spring cloud HOXTON release)

Sample
we are using spring-cloud-config-server with s3 backend. When we do config refresh using the actuator endpoint refresh, in the spring boot application using spring-cloud-config-client library, we see huge CPU spike. it is requiring atleast 7-8 times the normal CPU needed by the application. Is this behaviour expected? I observed this CPU spike even if we have not used @RefreshScope in any class to absorb the dynamic config change.  Filed the github issue in spring cloud as well. CPU spike when /refresh endpoint is hit for config refresh in the service #2325 , but no update there, then filed the issue at https://github.com/spring-guides/gs-centralized-configuration/issues/28, this issue was closed and they suggested that i openn the issue in spring-boot.

**Comment by wilkinsona** [comment]
Had you made it clear that you had already opened a Spring Cloud issue I doubt the @Buzzardo would have suggested opening another issue. https://github.com/spring-cloud/spring-cloud-config/issues/2325 is the right place for the investigation to begin.

**Comment by Buzzardo** [comment]
No, I would never ask for someone to create a duplicate issue.
