### ISSUE TITLE
Spring Batch AutoConfig does not set tablePrefix for JobRepository

### ISSUE THREAD

**Issue by madorb** [spring-projects/spring-boot#3798]
In `org.springframework.boot.autoconfigure.batch.BasicBatchConfigurer` when creating the JobExplorer the tablePrefix is set, but it is *not* set when creating the job repository and thus it always attemps to use the default prefix, which fails at runtime. 

This seems to be an oversight as the Spring Batch documentation specifically states:

"If you set the table prefix on the job repository, don't forget to set it on the job explorer as well." 

Sorry, I was going to submit a pull request to correct, but I submitted another issue because those are failing so I cannot validate my change.

**Comment by snicoll** [comment]
Thanks for the report. For the another issue, remove the `LIQUIBASE_HOME` environment property on your box and you should be fine until we fix the underlying issue.

**Comment by snicoll** [comment]
@madorb do you still intend to submit a PR?

**Comment by madorb** [comment]
Opened PR: https://github.com/spring-projects/spring-boot/pull/3818
