### ISSUE TITLE
Document that spring-boot-starter-parent sets maven.compiler.release and how to unset it if needed

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#37993]
springboot 3.2.0-RC1

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <compilerArgs>
            <arg>--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED</arg>
            <arg>--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED</arg>
        </compilerArgs>
    </configuration>
</plugin>
```

the default property `<maven.compiler.release>${java.version}</maven.compiler.release>` 

cause error

`exporting a package from system module java.base is not allowed with --release`

see 
![image](https://github.com/spring-projects/spring-boot/assets/13413715/b0c67743-fdac-4043-9f49-feb0b92bae79)

source `plexus-compiler-javac-2.13.0.jar`

![image](https://github.com/spring-projects/spring-boot/assets/13413715/c5ca780c-1621-41fb-a09c-a28e5da65902)

**Comment by wilkinsona** [comment]
Thanks for trying to RC. Have you only just started seeing this problem? We started setting `maven.compiler.release` [in 3.1](https://github.com/spring-projects/spring-boot/pull/34365).

**Comment by brucelwl** [comment]
I previously discovered this PR https://github.com/spring-projects/spring-boot/pull/34365, but it still caused my program to not compile properly, and currently I have not found a corresponding solution

**Comment by wilkinsona** [comment]
Yes, I suspect that #34365 introduced the problem. However, if that is the case, this would also fail with Spring Boot 3.1. Does it?

**Comment by brucelwl** [comment]
@wilkinsona I tried using Spring Boot version 3.1 and found the same problem

**Comment by brucelwl** [comment]
Thank you very much. `<maven.compiler.release/>` has solved my problem

**Comment by mhalbritter** [comment]
> We'll have to decide if we want to continue to set maven.compiler.release or switch back to source and target.

Upside of `release` is that the compiler then checks if you're using an API from a newer JDK, which is a definitive pro. Do we know why the JDK developers prohibit opening modules when using `--release` but allowing it when using `--target` and `--source`?

**Comment by wilkinsona** [comment]
> Upside of release is that the compiler then checks if you're using an API from a newer JDK, which is a definitive pro

It's definitely a good thing if you're building with a JDK version other than the one with which you'll run your app. However, if the two match, that benefit disappears and I wonder how common it is for them not to match.

> Do we know why the JDK developers prohibit opening modules when using `--release` but allowing it when using `--target` and `--source`?

I don't.

**Comment by wilkinsona** [comment]
We're going to document that we set `maven.compiler.release` by default and how and when to unset it. [The JEP](https://openjdk.org/jeps/247) describes when. It's if you want to use `--add-exports`, `--add-reads`, or `--patch-module` to modify system modules.
