### ISSUE TITLE
Testcontainers at Development Time doesn't work with Spring Data JPA

### ISSUE THREAD

**Issue by mosesonline** [spring-projects/spring-boot#37996]
Hello,

I've updated my application from Spring-Boot 3.2.0-M3 to 3.2.0-RC1 and since then the used postgresql testcontainer doesnt't start before the application and the following error occurs:

`[javax.sql.DataSource]: Factory method 'dataSource' threw exception with message: Mapped port can only be obtained after the container is started`

See example: https://github.com/mosesonline/container-bug
When starting the class TestContainerBugApplication it fails, but stepping back to M3 the application starts and terminates fine.
I couldn't find anysting in the change log so it might be an regression.

It can be connected with  #37989 but there is no @RestartScope.

Thanks

**Comment by eddumelendez** [comment]
See https://github.com/spring-projects/spring-boot/issues/37989

**Comment by rajadilipkolli** [comment]
Same here, following.

**Comment by Wzy19930507** [comment]
Hi, @mhalbritter may i pick it up, this issue looks good for beginners

**Comment by mhalbritter** [comment]
Hey @Wzy19930507, thanks for the offer, but I don't think this issue is suitable for beginners. It relies on bean initialization logic and bean post processors, which require a delicate understanding of Spring Framework internals.

**Comment by Wzy19930507** [comment]
Hi, @mhalbritter, If possible, I'll write a plan and discuss it with you.

**Comment by Wzy19930507** [comment]
https://github.com/spring-projects/spring-boot/blob/b167eb3b021006af3e6bd73b606376b15bd925ca/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/lifecycle/TestcontainersLifecycleBeanPostProcessor.java#L73-L79

Hi, @mhalbritter , prototype code is https://gist.github.com/Wzy19930507/057446d5249b501f6a4e91e7ead83ad9
change in L67, L77-L82, L101-L103.

**Comment by scottfrederick** [comment]
@Wzy19930507 Thanks for the suggestion. The changes that introduced this problem were done to support [starting containers in parallel](https://github.com/spring-projects/spring-boot/issues/37073). If I'm reading your changes correctly, all containers would be started sequentially regardless of the value of the `spring.testcontainers.beans.startup` that was introduced in that change. This isn't the way we would want to fix the problem. We are discussing as a team whether we want to resolve this by further refining the code or by reverting the parallel container startup changes.

**Comment by Wzy19930507** [comment]
Hi, @scottfrederick Thank you for the response.


‘’’
if (!this.beanFactory.isConfigurationFrozen()) {
    if (bean instanceof Startable) {
        startup.start(bean)
    }
}
‘’’
If use 
‘!this.beanFactory.isConfigurationFrozen()’,  most container can create at parallel mode.

**Comment by philwebb** [comment]
I think that this issue has the same underlying cause as #37989 so I'm going to close it as a duplicate.
