### ISSUE TITLE
Undocumented breaking changes in ValidationAutoConfiguration.defaultValidator between Spring Boot 2.5 and 2.6

### ISSUE THREAD

**Issue by brsolomon-deloitte** [spring-projects/spring-boot#38008]
Breaking changes in `ValidationAutoConfiguration.defaultValidator()` between Spring Boot 2.5 and 2.6 should be mentioned in the 2.6 Release notes at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes.

2.5: https://github.com/spring-projects/spring-boot/blob/6c4781086fc2fec77b0994e09e4a561d8739b616/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.java#L58

2.6: https://github.com/spring-projects/spring-boot/blob/f8c9fee3b0c8ff9ef48cf12fb4a9f8a51630a485/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.java#L59

**Comment by brsolomon-deloitte** [comment]
Thanks for the docs link @wilkinsona; we can close this issue.

> With that said, it would still be interesting to learn why you were calling the defaultValidator method on ValidationAutoConfiguration.

Here's the existing usage (where I've added `applicationContext` to at least get the build un-broken).

```java
public class AddressValidatorTests {

    @Autowired
    private ApplicationContext applicationContext;

    private final Validator validator = new DelegatingValidator(
            Collections.singletonList(new AddressValidator()),
            ValidationAutoConfiguration.defaultValidator(applicationContext));  // JSR-303 Validation Annotations

    @Test
    public void testUnitedStatesAddressWhenMissingState() {

        BindingResult result = ValidationHelper.validate(validator, addressDTOBuilder()
                .country(UNITED_STATES_OF_AMERICA)
                .address1("12345 Street")
                .city("ABC")
                .zip("12345")
                .build());
```

Where `ValidationHelper` looks like:

```java
public class ValidationHelper {

    public static BindingResult validate(Validator validator, Object dto) {

    ...
```

**Comment by wilkinsona** [comment]
Assuming the use of JUnit 5, you should be able to do something like this instead:

```java
public class AddressValidatorTests {

	private final Validator validator;

	AddressValidatorTests(@Autowired LocalValidatorFactoryBean defaultValidator) {
		this.validator = new DelegatingValidator(Collections.singletonList(new AddressValidator()), defaultValidator);
	}

	// …
	
}
```
