### ISSUE TITLE
Links to portfolio projects which use Antora are broken

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#38000]
[Our Snapshot documentation](https://docs.spring.io/spring-boot/docs/3.2.0-SNAPSHOT/reference/htmlsingle/) links to https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/ which is a 404 - the correct link would be https://docs.spring.io/spring-framework/reference/6.1/. In our [RC1 documentation](https://docs.spring.io/spring-boot/docs/3.2.0-RC1/reference/htmlsingle/) the links are fine.

Sometimes we link to the JavaDoc (search for "CachingConfigurer") - this link points to https://docs.spring.io/spring-framework/docs/6.1-SNAPSHOT/javadoc-api/org/springframework/cache/annotation/CachingConfigurer.html - but should be https://docs.spring.io/spring-framework/docs/6.1.0-SNAPSHOT/javadoc-api/org/springframework/cache/annotation/CachingConfigurer.html. 

This link is broken in our RC1 documentation, too. It should be https://docs.spring.io/spring-framework/docs/6.1.0-RC1/javadoc-api/org/springframework/cache/annotation/CachingConfigurer.html, but is https://docs.spring.io/spring-framework/docs/6.1/javadoc-api/org/springframework/cache/annotation/CachingConfigurer.html.

Everything which links to Antora docs must use the "Antora versions", everything else (JavaDoc, etc.) must use the full versions.

Antora versions for Spring Framework are:

* `6.1.0-SNAPSHOT` -> `6.1`
* `6.1.0-RC1` -> `6.1` (see https://github.com/spring-projects/spring-framework/issues/31480)
* `6.0.14-SNAPSHOT` -> `6.0-SNAPSHOT`
* `6.0.13` -> `6.0` (or just omit the version in the link)

**Comment by mhalbritter** [comment]
This doesn't only affect Spring Framework, but all projects which use Antora.

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/spring-projects/spring-boot/issues/38000#issue-1958619422)

**Comment by mhalbritter** [comment]
With https://github.com/spring-projects/spring-framework/issues/31480 done, this is fixed now. In https://github.com/spring-projects/spring-boot/commit/4c3de96d74773e403e4032a3cfd9c630e0998ca1 I fixed a lot of broken documentation linkes.
