### ISSUE TITLE
Upgrade to Lettuce 6.2.6.RELEASE

### ISSUE THREAD

**Issue by pranshupatel015** [spring-projects/spring-boot#38012]

**Comment by wilkinsona** [comment]
As [described in the new issue template](https://github.com/spring-projects/spring-boot/blame/4e7c0737d44d5d6a15f5f6c736db3ad20be7fb20/.github/ISSUE_TEMPLATE.md#L11-L12),  there's no need for an issue for a basic dependency upgrade.
