### ISSUE TITLE
MessageSourceAutoConfiguration should only check the current context for a message source bean

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3803]
The `@Conditional` on `MessageSourceAutoConfiguration` checks for an existing bean of type `MessageSource` so a parent context can switch it off, even if the parent is empty (the default). We should switch to only check the current context.

**Comment by wilkinsona** [comment]
This got fixed in 1.0.x and merged straight into master, i.e. the change isn't in 1.2.x
