### ISSUE TITLE
Minimize the number of beans created by RabbitAnnotationDrivenConfiguration

### ISSUE THREAD

**Issue by deeaitche** [spring-projects/spring-boot#38067]
In [``RabbitAnnotationDrivenConfiguration``](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitAnnotationDrivenConfiguration.java), some beans may be created but unused.

When ``spring.rabbitmq.listener.type`` is missing value or ``simple``, both ``directRabbitListenerContainerFactoryConfigurer`` and ``simpleRabbitListenerContainerFactoryConfigurer`` are created but ``directRabbitListenerContainerFactoryConfigurer`` is unused.

When ``spring.rabbitmq.listener.type`` is ``direct``,  both ``directRabbitListenerContainerFactoryConfigurer`` and ``simpleRabbitListenerContainerFactoryConfigurer`` are created  but ``simpleRabbitListenerContainerFactoryConfigurer`` is unused.

**Comment by wilkinsona** [comment]
Thanks for noticing and reporting this. I think it makes sense to reduce the number of beans that are created but we should only do so in a new minor release as there's a small chance that someone may be relying on one of the beans that appears to be unused and we wouldn't want to break their application in a maintenance release.

**Comment by Wzy19930507** [comment]
Hi @wilkinsona , may i pick it up?

**Comment by wilkinsona** [comment]
I was mistaken above. The current arrangement is [intentional](https://github.com/spring-projects/spring-boot/pull/9055#issuecomment-299428237):

> I've also simplified the configurer auto-config as we want both of them to be present regardless of the container type (you are free to create as many containers as you want after all).

Given that it's only a single possibly unused bean in each case and that removing it may be a breaking change, I no longer think that we should do this. Thanks anyway for the suggestion.
