### ISSUE TITLE
Add support for Netty metrics

### ISSUE THREAD

**Issue by be-hase** [spring-projects/spring-boot#38062]
netty's metrics have been provided since micrometer 1.11.x.
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/netty4

Can you provide this metric in Spring Boot?

**Comment by bclozel** [comment]
@be-hase can you elaborate? Which Netty instance are you expecting to be instrumented and how?
This instrumentation is meant to be used by libraries directly, as it's quite low level and requires intimate knowledge of how the event executors and allocators are used. For example, Reactor Netty already contributes [metrics around HTTP](https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_4) and could expand its footprint there with this, as it's already depending on Micrometer.

**Comment by be-hase** [comment]
Rather than using reactor netty's own metrics, I would be happy to use the official metrics provided by micrometer, as it is easier to reuse the dashboard, etc.
(However, if I were to make this request, I should ask the reactor netty side.)

**Comment by jonatan-ivanov** [comment]
fyi: https://github.com/netty/netty/issues/8546
You might want to ask the Netty team to add Micrometer support. :)

**Comment by bclozel** [comment]
> Rather than using reactor netty's own metrics, I would be happy to use the official metrics provided by micrometer, as it is easier to reuse the dashboard, etc.

I don't think this is a matter of "official" vs "unofficial" metrics. Micrometer provides instrumentation for executors and allocators (which is somewhat generic for all Netty usage), whereas Reactor instruments HTTP (which is harder to implement in a generic way).

> (However, if I were to make this request, I should ask the reactor netty side.)

As I've said, this instrumentation is quite low level and doing so in the library would be a better fit. I would suggest asking the Reactor Netty team about those metrics and how to enable them. Reactor Netty already has a dedicated API to enable metrics collection. This also applies to other libraries using Netty.

I'm closing this issue for now, we can reopen depending on the Reactor Netty and Netty team's opinions.
