### ISSUE TITLE
ReactiveMongoTemplate.changeStream ignores FullDocumentBeforeChange option passed with argument ChangeStreamOptions  

### ISSUE THREAD

**Issue by gautampushpa2008** [spring-projects/spring-boot#38087]
Hello Team,

Recently working on the SpringBoot Reactive change stream API, I found that the _ReactiveMongoTemplate.changeStream_ method doesn't consider the _FullDocumentBeforeChange_ option passed along with the argument _ChangeStreamOptions_, and the publisher i.e., ChangeStreamPublisherImpl always use the _FullDocumentBeforeChange.DEFAULT_ option while watching the change events on a collection. Due to this, I am unable to retrieve the preimage of a collection from the MongoDB and the value for field fullDocumentBeforeChange is always null in the ChangeStreamEvent. Could you please provide a solution for this?

Spring boot version: 3.1.0
Dependency: org.springframework.boot:spring-boot-starter-data-mongodb-reactive

**Comment by wilkinsona** [comment]
`ReactiveMongoTemplate` is part of Spring Data MongoDB which is managed as a [separate project](https://github.com/spring-projects/spring-data-mongodb).

First, I would upgrade to Spring Boot 3.1.5 to pick up the latest version of Spring Data MongoDB. If that does not help, I would open a Spring Data MongoDB issue.
