### ISSUE TITLE
Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is disabled by default

### ISSUE THREAD

**Issue by lako12** [spring-projects/spring-boot#38083]
In the documentation
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.spring-mvc
Section: 4.3. Customize the Jackson ObjectMapper

it is written:
The ObjectMapper (or XmlMapper for Jackson XML converter) instance (created by default) has the following customized properties:

MapperFeature.DEFAULT_VIEW_INCLUSION is disabled
DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is disabled
SerializationFeature.WRITE_DATES_AS_TIMESTAMPS is disabled

In my application, however, I noticed that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is false while the default value is true.

**Comment by wilkinsona** [comment]
You're right. Thanks. The documentation update was overlooked in https://github.com/spring-projects/spring-boot/pull/19352.
