### ISSUE TITLE
Latest Oracle 23 driver does not need to be on the "prohibited" list anymore (?)

### ISSUE THREAD

**Issue by the-vj** [spring-projects/spring-boot#38118]
JDBC driver 23.2.0.0 was planned to be taken into use, but it contained bugs and the version was explicitly prohibited from dependency management in this ticket: https://github.com/spring-projects/spring-boot/issues/35970.

Background of the topic is covered here: https://github.com/spring-projects/spring-boot/issues/35006 

There is a newer version 23.3.0.23.09 published by Oracle a few weeks back - it might have the corrections discussed earlier, as also Oracle 23c release is coming closer.

Does it make sense to re-check and update the dependency management for the upcoming SpringBoot 3.2 release?

**Comment by wilkinsona** [comment]
Thanks for raising this. It looks like 23.3.0.23.09 is OK. Please follow https://github.com/spring-projects/spring-boot/issues/38121.
