### ISSUE TITLE
Add support for Spring Session auto-configuration with Hazelcast

### ISSUE THREAD

**Issue by shakuzen** [spring-projects/spring-boot#3811]
Spring Session supports Hazelcast as a backing data store, so it would be nice if Spring Boot also offered auto-configuration for that. Right now only Redis is auto-configured. I would be willing to submit a pull request for this.

**Comment by shakuzen** [comment]
I guess the tricky part is when both Redis and Hazelcast are on the classpath with Spring Session. Any preference or ideas on how this should be handled? Does one simply get preference and to use the other in such a situation, the other must be explicitly disabled? Are there any similar situations in Spring Boot auto-configuration now?

**Comment by snicoll** [comment]
There is with caching and there's a `spring.cache.type` that one can use to force the backend store to use. 

If you can contribute a PR that works for Hazelcast (assuming that an `HazelcastInstance` is auto-provided because that's what we're going to do in #2942) then I can take that work and figure out what to do with the Redis vs. Hazelcast situation. If you think you have an idea, feel free to contribute it of course.

How does that sound?

**Comment by shakuzen** [comment]
I'll take a look at the caching auto-configuration as an example, then. Thank you for pointing me in the right direction. It seems Redis would have to be the default in the case both are available, in order to not introduce a breaking change.

Getting it done this week shouldn't be a problem as far as the time it will take me. However, a potential issue is that I would like to leverage the `@EnableHazelcastHttpSession` annotation and the corresponding `HazelcastHttpSessionConfiguration` that I have added in an open pull request (spring-projects/spring-session#277) for this auto-configuration. This would simplify things like the equivalent Redis-backed session auto-configuration and avoid duplication between here and code I believe should be in Spring Session. I am waiting to hear from @rwinch on if we can get this in a version of Spring Session that could make it in Spring Boot 1.3 or not - again, I am guessing it would have to happen this week to make the release.

**Comment by snicoll** [comment]
Looks like 1.4 to me. If you need to modify spring session to have "what you want", you're a mile away from adding auto-config in Spring Boot. Anyway, 1.3 is around the corner and we have all enough on our plates right now so I am afraid it'll have to go in a future release instead.
