### ISSUE TITLE
How to custom InvocableHandlerMethod？

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-boot#3812]
handle  all parameters  after argumentResolve

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).
