### ISSUE TITLE
Spring Boot's support for liquibase does not work for files with a space in file name.

### ISSUE THREAD

**Issue by Ayrossi** [spring-projects/spring-boot#38156]
Although I agree that spaces in file name should always be avoided, I do think that this should not be a blocking issue.
Before Spring Boot 2 this worked without any issue. For legacy projects that contain spaces in their filenames it means that they can't use the auto configured support for liquibase that they used before.

The issue is very easy to reproduce, it always happens when a changelog has a space in it's filename.

**Comment by philwebb** [comment]
I'm not sure that this is a Spring Boot bug as we don't do much more than pass the changelog property though to Liquibase. Can you please try debugging [this line](https://github.com/spring-projects/spring-boot/blob/3.1.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L101) to see if the space is present in the `liquibase.setChangeLog` parameter.

If it is, then I think you'll need to raise this with the Liquibase project.

**Comment by Ayrossi** [comment]
@philwebb 

Following your comment I started debugging more to have a better idea of what is happening behind the screens.

Using liquibase as a standalone program works even with the spaces in the filenames ( which is why I thought this was not a bug at their side ), however it does seem to indeed not be related to Spring Boot.

Liquibase internally uses the following class for the integration with Spring: [FileSystemResource](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/io/FileSystemResource.java).

More specifically it uses the following method getURL on the resource. 
This method did not encode spaces in old versions of Spring which is why the integration with liquibase was working.

This behaviour has been modified a long time ago after this issue: [FileSystemResource.getURL should return...](https://github.com/spring-projects/spring-framework/issues/8580)

I suppose this is something that Liquibase has to take in account? ( And thus, this issue can be closed ).

**Comment by philwebb** [comment]
Thanks for the update @Ayrossi. If you do open an issue with https://github.com/liquibase/liquibase/issues feel free to paste a link to it here.
