### ISSUE TITLE
Failed to build Docker image using Spring Boot Maven plugin

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-boot#38159]
Hi 

I tried to build Docker image using Spring Boot Maven plugin:

`mvn spring-boot:build-image`

However I got an exception (multiple times):

```
[INFO]     [creator]       BellSoft Liberica JRE 21.0.1: Contributing to layer
[INFO]     [creator]         Downloading from https://github.com/bell-sw/Liberica/releases/download/21.0.1+12/bellsoft-jre21.0.1+12-linux-amd64.tar.gz
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency jre
[INFO]     [creator]     unable to download https://github.com/bell-sw/Liberica/releases/download/21.0.1+12/bellsoft-jre21.0.1+12-linux-amd64.tar.gz
[INFO]     [creator]     unable to request https://github.com/bell-sw/Liberica/releases/download/21.0.1+12/bellsoft-jre21.0.1+12-linux-amd64.tar.gz
```

That's very strange behavior because I can easily download this file in my browser (https://github.com/bell-sw/Liberica/releases/download/21.0.1+12/bellsoft-jre21.0.1+12-linux-amd64.tar.gz)

Spring Boot: 3.2.0.RC1
JDK: 21
OS: Windows 10

**Comment by wilkinsona** [comment]
Thanks for the report but this is out of Spring Boot's control. The network in your Docker environment and the [Buildpacks](https://buildpacks.io) determine what's available for download. You may, for example, [need to configure the buildpacks to use an HTTP proxy](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.examples.builder-configuration) to match the host's networking configuration. If that doesn't help, the [Buildpacks community](https://buildpacks.io/community/) may be a good place to further diagnose the problem.

**Comment by scottfrederick** [comment]
@sergey-morenets I see you opened an issue against the `pack` project, but I'm afraid that's not a good place to report this. Buildpacks are completely in control of these downloads, and `pack` doesn't have any more control over that than Spring Boot does. 

I believe what you're seeing is being discussed in https://github.com/paketo-buildpacks/bellsoft-liberica/issues/488.

**Comment by sergey-morenets** [comment]
Hi @scottfrederick 

Sorry about that. I had to clue which project was responsible for this failure so I opened the ticket here.
Now I see that you're right.
