### ISSUE TITLE
When JMX is enabled also register JMX beans for logging framework

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#3819]
Enabling JMX for the application is quite easy with the `spring.jmx.enabled` property. 

It would be nice that when this is enabled to the JMX support for the used logging framework would also be registered, this would allow on-the-fly reconfiguration of the loggers for the application.

**Comment by snicoll** [comment]
I like that.

**Comment by mdeinum** [comment]
Anything I can do to push this forward?

**Comment by snicoll** [comment]
a pull request? :) I think a `LoggingEndpoint` would be awesome. Probably too late for 1.3 unless you come with a PR that the majority of the solution.

**Comment by mdeinum** [comment]
Did a little googling and that led me to https://github.com/olivergierke/spring-jmx-namespace. Maybe we could reuse part of that to expose the loggers (although I would prefer using the support in the libraries itself).

**Comment by spencergibb** [comment]
@snicoll Spring Cloud has [a `/env` endpoint](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentManagerMvcEndpoint.java) you can post environment changes to.  It reconfigures the logger if the logging config get's touched.

**Comment by cemo** [comment]
I had already files an issue about this #2182

**Comment by snicoll** [comment]
Duplicates #7219
