### ISSUE TITLE
Incorrect documentation help about Log4j2 in SpringBoot

### ISSUE THREAD

**Issue by RayTigerZ** [spring-projects/spring-boot#38191]
This maybe a Incorrect  documentation about Log4j2 help in link
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.log4j2-extensions

`The extensions supersede the [Spring Boot support](https://logging.apache.org/log4j/2.x/log4j-spring-boot/index.html) provided by Log4J. You should make sure not to include the org.apache.logging.log4j:log4j-spring-boot module in your build.`

that means 'not include the org.apache.logging.log4j:log4j-spring-boot module'? as that, Profile setting is not working.

**Comment by RayTigerZ** [comment]
I use log4j2-spring.xml with springboot 2.7.x, when exclude log4j-spring-boot module, log as:
`ERROR Error processing element SpringProfile ([Root: null]): CLASS_NOT_FOUND`

log4j2-spring.xml content:

> 
<Root level="INFO">

    <SpringProfile name="!prod">
        <AppenderRef ref="Console"/>
    </SpringProfile>
</Root>

However application run in prod or dev profile, do not log in console

**Comment by RayTigerZ** [comment]
In Log4j2 website, clearly state the need for including log4j-spring-boot module, but springboot  document do not , that makes me wonder

**Comment by wilkinsona** [comment]
Spring Boot's Log4j2 extensions were [introduced in Spring Boot 3.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#log4j2-enhancements) but you're using 2.7. The docs for Spring Boot 2.7 are available here: https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/. Your link above was to https://docs.spring.io/spring-boot/docs/current/reference/html/. The `current` URL links to the latest released version of Spring Boot. That the time of writing that's 3.1.5.

**Comment by RayTigerZ** [comment]
Could add the part of log4j2 springprofile setting in 2.7.x document

**Comment by wilkinsona** [comment]
There's nothing to document in Spring Boot's 2.7.x documentation as it isn't a Spring Boot feature in that version. You should use `org.apache.logging.log4j:log4j-spring-boot` with Spring Boot 2.7.x and refer to Log4j2's documentation to learn about the Log4j2 feature.

**Comment by RayTigerZ** [comment]
ok, Thank you for your answer.

**Comment by RayTigerZ** [comment]
and it is excellent to add this log4j2 enhancement  into SpringBoot 3.0
