### ISSUE TITLE
The version 1.2.5 read application.properties error

### ISSUE THREAD

**Issue by kinglcc** [spring-projects/spring-boot#3820]
Bootstrap the springboot application command is "java -jar -Dspring.config.location=config/application.properties springboot-app.jar".

There are application.properties and application-online.properties in the springboot-app.jar pacakge, too.
The file "config/application.properties" is the copy of config/application.properties.
But, the application read configuration from the application.properties in the jar, when config/application.properties don't contains the properties.

It looks like the application will merge all properties of the two files.

Is the problem a bug?

**Comment by nomack84** [comment]
Nope, SB reads both files, if your outside properties files doesn't contain properties, then it fall back to the default properties file, which is inside the .jar. Also, to load the application-online.properties, you'll need to active a maven/gradle profile named `online` to let SB automatically load the properties file.

**Comment by kinglcc** [comment]
Thank you very much!
I should make sure my application read the current properties, so I use maven resources plugin to exclude the properties files from the jar package.

**Comment by nomack84** [comment]
Simply override the values in your .jar's application.properties file, otherwise you could use a maven profile to use a different properties file. But the normal behavior is to have a properties inside the jar with your defaults and have an outside properties where you override those defaults.

**Comment by nomack84** [comment]
also, could you close this issue...

**Comment by snicoll** [comment]
@kinglcc please create a stackoverflow thread next time. We prefer to keep this tracker for bug reports and enhancements. Thanks.
