### ISSUE TITLE
Opentelemetry service.name default should align with OpenTelemetry Semantic Convention

### ISSUE THREAD

**Issue by lenin-jaganathan** [spring-projects/spring-boot#38218]
https://github.com/spring-projects/spring-boot/blob/4bc63b579ac90e52614be7ce214cf9d874c63b34/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/opentelemetry/OpenTelemetryAutoConfiguration.java#L54

Spring's Opentelemetry auto configuration seem to use `application` as a fall back value when the property `spring.application.name` is not set. As per [Opentelemetry semantic convention](https://opentelemetry.io/docs/specs/semconv/resource/#service), the default value when the app name is not available should be `unknown_service`. 

Note: Micrometer also defaults to the value `unknown_service`. But when used with spring's auto configuration the resource is set to a different value.

**Comment by mhalbritter** [comment]
Superseded by #38219.
