### ISSUE TITLE
Remove deprecated support for FailureAnalyzer setter injection

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#38238]
See https://github.com/spring-projects/spring-boot/issues/29811

**Comment by Wzy19930507** [comment]
Hi, @scottfrederick, @wilkinsona, 
I'm sorry to bother you again, remove the code here, right?
https://github.com/spring-projects/spring-boot/blob/e4a0e9d9acf90b2f16656e10211b7e72476acad6/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/diagnostics/FailureAnalyzers.java#L67-L97

**Comment by wilkinsona** [comment]
Closing in favor of #38322.
