### ISSUE TITLE
Spring webflux and validation starter don't work with nested generics

### ISSUE THREAD

**Issue by mamirov** [spring-projects/spring-boot#38255]
Spring version: 2.7.11

I found a problem with validation in Spring Webflux and spring-boot-starter-validation

When I try to validate a Mono object that has a nested Set, the validation doesn't work
When I use the validation without nested generic it works

Example

Doesn't work:

```java
public Mono<String> greetings(@Valid @RequestBody Mono<Set<GreetingsRequest>> request) {
  //do something
}
```

Works:
```java
public Mono<String> greetings(@Valid @RequestBody Mono<GreetingsRequest> request) {
  //do something
}
```

Works:
```java
public Mono<String> greetings(@Valid @RequestBody Set<GreetingsRequest> request) {
  //do something
}
```

**Comment by wilkinsona** [comment]
Thanks for the report but it's Spring WebFlux, part of Spring Framework, that performs request body validation. Please open a [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues), providing a minimal sample that reproduces the problem when you do so.
