### ISSUE TITLE
Enable ability to acquire token_key from a provided RestTemplate

### ISSUE THREAD

**Issue by shanman190** [spring-projects/spring-boot#3825]
This may be a slightly awkward issue since it's bridging between Spring Boot and Spring Cloud, but here is my issue that I'm having.

Presently, the [ResourceServerTokenServicesConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L223) class creates a RestTemplate client to interact with an OAuth Authorization service internally. The use case being for an OAuth Resource service to request the token_key being used by the OAuth Authorization service. Since this client is created internally, it never becomes eligible for customization, during which time Spring Cloud would add the service discovery component. Since this happens, the keyUri value must be explicitly set to a fully qualified uri (http://localhost:8080/oauth/token_key) instead of the more cloud-friendly, service-discoverable version (http://authorization/oauth/token_key).

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

**Comment by shanman190** [comment]
It is an enhancement. This code originally moved from Spring Cloud where service discovery is a thing, but this part of the process doesn't support service discovery due to the internal creation of that RestTemplate to get the OAuth token_key.

I've cleaned up the issue to make it sound more like an issue/enhancement.

**Comment by philwebb** [comment]
I've been wondering if we should auto-configure a `RestTemplate` bean so that we can provide post processor hooks and also make it easier to use `MockRestServiceServer` in tests. I guess one problem with this approach is applications often need different `RestTemplate` customization for different user-cases.

**Comment by snicoll** [comment]
I also expect Spring Boot to provide a general purpose `RestTemplate` by default. But it might be dangerous because we can't really know which one we have unless we start inspecting its _internal_ state. 

Maybe a factory would be more useful? No idea which parameter we would use but it would be much clearer what you'd get than just _a_ `RestTemplate`.

**Comment by shanman190** [comment]
I agree that Spring Boot should provide a general purpose `RestTemplate` for use, but there presently isn't a very good way of identifying which `RestTemplate` is which. The factory seems like it may be a good idea for handling this or maybe we could handle it the same as the `ObjectMapper` and `Jackson2ObjectMapperBuilder`?

**Comment by spencergibb** [comment]
Spring Cloud provides a `RestTemplate` and a [customizer](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RestTemplateCustomizer.java) to be able to tweak it.

**Comment by snicoll** [comment]
And so do we with `RestTemplateBuilder` and the customizer infrastructure.
