### ISSUE TITLE
wrong writing of a method name.

### ISSUE THREAD

**Issue by miyuki4j** [spring-projects/spring-boot#38287]
![image](https://github.com/spring-projects/spring-boot/assets/39372705/a021580e-0692-4444-b260-54b7f87f17ee)

**Comment by wilkinsona** [comment]
Why do you think it's wrong? The `enableShutdownHookAddition` method sets the `shutdownHookAdditionEnabled` flag to `true`. This then enables calls to `Runtime.getRuntime().addShutdownHook`. That looks OK to me but I may have overlooked something.

**Comment by bclozel** [comment]
Didn't we fix the typo already in #38241 ?

**Comment by mhalbritter** [comment]
Yes. The old method was named `enableShutdowHookAddition`, the new is now named `enableShutdownHookAddition`, like shown on the screenshot.

I noticed that the gutter on the left side of the editor has a blue section, which indicates a changed line. Maybe the method name has been fixed already in the screenshot?

**Comment by mhalbritter** [comment]
I think this is a duplicate of #38241.
