### ISSUE TITLE
Provide Sample to show how to deploy an application as a Windows service

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3829]
The maven and gradle tooling can stop a running process using a JMX endpoint. We could use the same APIs to support service wrappers like Apache Commons Daemon. Maybe just a sample or a helper class to make it easier.

**Comment by snicoll** [comment]
Work in progress over here https://github.com/snicoll-scratches/spring-boot-daemon/

Plenty of issues with that stuff and I am not even sure the `jvm` mode would work in the end since we need to start the JVM process with JMX enabled on a given port (to be able to trigger a shutdown).
