### ISSUE TITLE
Open community on discourse.org

### ISSUE THREAD

**Issue by sergmain** [spring-projects/spring-boot#38323]
Some time ago there was very useful community on gitter.im . But after moving it to matrix platform it became hard to use.
This gitter.im community was useful for open questions about anything related spring-boot
Also there is dedicated hash-tag on stackoverflow but moders on SO are very unfriendly right now because you have to ask only question which follow SO current policy and after chatGPT this policy aimed to help to train LLM not help to user.

So it would be nice if Spring Boot /Spring will open a community on [discourse.org](https://discourse.org/)  rn almost all communities around programming languages on discourse.org, i.e.
https://discourse.haskell.org/
https://fortran-lang.discourse.group/
https://forum.golangbridge.org/
https://discuss.rubyonrails.org/
https://discourse.julialang.org/
others

**Comment by vpavic** [comment]
This should probably be considered taking also #33445 into account.

FWIW I'd highly prefer the GitHub Discussions because IMO there's great value in having as many parts of the community as possible in the same place (and also close to the code).

**Comment by philwebb** [comment]
Thanks @vpavic. We agree that GitHub Discussions would be a better option than discourse for us. I'll close this one in favor of #33445 which we've still to discuss as a broader team.

**Comment by sergmain** [comment]
Is there any ETA of opening a GitHub Discussions for Spring Boot?

PS. I have a complex question about WebSocket to ask, specifically - SB <-> SB communication

**Comment by philwebb** [comment]
@sergmain I'm afraid we don't have an ETA for this. It will require some discussion with the broader team.

**Comment by landsman** [comment]
Discourse is nice platform. It make sense to consider it as well.
For example Vaadin just started the forum and it works nice: https://vaadin.com/forum
