### ISSUE TITLE
Spring Boot 3.1.5  Native Image on GraalVM CE 21.0.1 - Logback Janino Error

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-boot#38347]
**Spring Boot 3.1.5** Native Image on **GraalVM CE 21.0.1** fails to start due to `Logback` error as below. We have used `Janino` for some conditional evaluations and the error is thrown on startup of the successfully built native image.

Automatic hints were generated by running all the application functionality first, only then the native image was built.

```
at org.codehaus.commons.compiler.InternalCompilerException: SNO: Generated compilation unit does not declare class 'SC' 
```

**Comment by wilkinsona** [comment]
Duplicates #33758.
