### ISSUE TITLE
java -jar myrepackaged.jar --param=value does not pass variable value in program

### ISSUE THREAD

**Issue by flirtomania** [spring-projects/spring-boot#3834]
`java -jar myrepackaged.jar --fileimport.filename=value` is not working
`java -jar -Dfileimport.filename=value myrepackaged.jar` works ok

command used to build an application: `mvn clean install spring-boot:repackage`
spring-boot version: 1.2.5.RELEASE

usage in application:

    @Value("${fileimport.filename:}")
    String importFilename;

**Comment by wilkinsona** [comment]
What does your application's main method look like? I suspect you haven't passed the command line arguments into your `SpringApplication`

**Comment by flirtomania** [comment]
Yes, exactly, it was:
`SpringApplication.run(App.class);`
Thank you.
