### ISSUE TITLE
Upgrade to AspectJ 1.9.20.1

### ISSUE THREAD

**Issue by christarczon** [spring-projects/spring-boot#38355]
I know you ask not to raise issues for managed dependencies but I'm wondering if the automatic process missed this one due to the extra .1 at the end. This was released back in September but was not included in 3.2.0-RC2. It fixes a regression in 1.9.20 that I just bumped into.
https://htmlpreview.github.io/?https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/README-1920.html

**Comment by wilkinsona** [comment]
Thanks, @christarczon. This does indeed appear to have been missed.
