### ISSUE TITLE
Pull the whole "Testing" documentation section up to the top level

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#38361]
Please also consider pulling the whole "Testing" section up to the top level so it shows up in the left nav.

_Originally posted by @dsyer in https://github.com/spring-projects/spring-boot/issues/33975#issuecomment-1403586371_

**Comment by scottfrederick** [comment]
I agree we could use more fine-tuning of the organization of the docs in this area. In the latest snapshot docs, we have: 


- [7.9. Testing](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing)
  - [7.9.1. Test Scope Dependencies](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.test-scope-dependencies)
  - [7.9.2. Testing Spring Applications](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.spring-applications)
  - [7.9.3. Testing Spring Boot Applications](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.spring-boot-applications)
  - [7.9.4. Testcontainers](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.testcontainers)
  - [7.9.5. Test Utilities](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testing.utilities)
- [7.10. Docker Compose Support](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.docker-compose)
- [7.11. Testcontainers Support](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.testcontainers)

`Testcontainers` appears twice, but it's not clear what the differences between the two sections are (integration tests vs development-time services). 

`7.10 Docker Compose Support` and `7.11 Testcontainers Support` talk about development-time services, so maybe those could be under a common heading to make that more clear.

**Comment by mhalbritter** [comment]
> 7.10 Docker Compose Support and 7.11 Testcontainers Support talk about development-time services, so maybe those could be under a common heading to make that more clear.

I think that's a good idea.
