### ISSUE TITLE
Pubsub model using raw WebSocket

### ISSUE THREAD

**Issue by ADIIS007** [spring-projects/spring-boot#38367]
🎁 Enhancement 

Topic:- Pubsub model using raw WebSocket
Use case:- most HLD problems depend on WebSocket so Implementing a publish subscribe model would help a lot of develops work ok it
Application:- Time series data

**Comment by wilkinsona** [comment]
Thanks for the suggestion but I think this is out of scope for the Spring Boot project. It would possibly be something that Spring Framework would provide but it already has [support for STOMP over WebSocket](https://docs.spring.io/spring-framework/reference/web/websocket/stomp.html) which, from the little you have said, sounds like it may meet your needs.
