### ISSUE TITLE
Support composible SslBundle and ability to wrap Java's lib\security\cacerts in SslBundle

### ISSUE THREAD

**Issue by sandipchitale** [spring-projects/spring-boot#38387]
In some applications it is desirable to use multiple sources of Trust material. An application may want to use Java's default trust store as a fallback or first lookup of CA Root/Parent Certs but for some internal services also use additional, managed, shared trust and key stores. In fact in a pool of micro-services each service may contribute a self managed source of trust material. To address these types of screnarios support the following:

- static SslBundle (may be via a auto-configured Registrar) that basically wraps Java's lib\security\cacerts
- a composite, delegating SslBundle implementation that can delegate to ordered list of SslBundles
  - allow Profile or Conditional based inclusion of delegate SslBundles
- it should be possible to configure such composite SslBundles via configuration

**Comment by wilkinsona** [comment]
> a composite, delegating SslBundle implementation that can delegate to ordered list of SslBundles
allow Profile or Conditional based inclusion of delegate SslBundles

How would you expect such a composite bundle to behave? For example, what would be returned by `SslBundle.getKey()` or by `SslBundle.getStores().getKeyStore()`? There does not appear to be an opportunity for ordered delegation.

**Comment by sandipchitale** [comment]
Good point. Presumably the notion of delegate objects will have to go deeper. The key point is, now that SslBundle usage is becoming ubiquitous throughout the Spring Framework and in most places only one SslBundle can be consumed e.g. RestClient.Builder then to support a use case of composite trust material sources fronted by a single SslBundle is what I am after. Hope this helps clarifying what I am looking for.

**Comment by wilkinsona** [comment]
Thanks. Unfortunately, I'm not sure that really helps.

Ultimately, an `SslBundle` is just a convenient way of creating instances of standard Java SSL constructs such as an `SSLContext` instance. It's these instances that are consumed by things like HTTP client libraries and embedded web servers to configure their SSL support.

Ignoring the `SslBundle` abstraction, can you describe how you would achieve what you have described using Java's standard APIs?

**Comment by sandipchitale** [comment]
Something along the lines of 

https://stackoverflow.com/a/65323132/2097168

The idea is at low level Java APIs use private final List<X509TrustManager> trustManagers;

Hopefully that gives an idea.

**Comment by sandipchitale** [comment]
SSL has two sides. Server side and Client side. The server side can have a single key/certificate in a single keystore, but client could have multiple truststores. Thus the signature of:

KeyStore org.springframework.boot.ssl.SslStoreBundle#getTrustStore()

could be changed to

List<KeyStore> org.springframework.boot.ssl.SslStoreBundle#getTrustStores()

and the managers built from these multiple TrustStores. Interestingly:

TrustManager[] org.springframework.boot.ssl.SslManagerBundle#getTrustManagers()

already seem to be dealing with multiple TrustManagers.

Hope this additional commentary helps.

**Comment by sandipchitale** [comment]
Java's cacerts truststore can be easily loaded as SslBundle like this:

```
spring:
  ssl:
    bundle:
      jks:
        cacerts:
          truststore:
            type: PKCS12
            location: "${java.home}/lib/security/cacerts"
            password: changeit
```

Not sure why I did not think of that.

**Comment by mhalbritter** [comment]
I have a setup which creates a `RestClient` backed by the JDK client which trusts the server self-signed certificate and also the global cacerts file.

Code is here: https://github.com/mhalbritter/mtls-with-sslbundles/

The client uses the `client` and the `cacerts` bundle: https://github.com/mhalbritter/mtls-with-sslbundles/blob/main/src/main/java/com/example/mtls/Client.java, which are defined here: https://github.com/mhalbritter/mtls-with-sslbundles/blob/main/src/main/resources/application.yaml

I had to create the `SSLContext` myself to use the `CompositeX509TrustManager`, see here: https://github.com/mhalbritter/mtls-with-sslbundles/blob/main/src/main/java/com/example/mtls/SslContextFactory.java

All together this even works with mTLS (client sends own certificate to server).

**Comment by sandipchitale** [comment]
Ah, the following was the key. Maybe this example should be documented, but it works.

[SslContextFactory.java](https://github.com/mhalbritter/mtls-with-sslbundles/blob/main/src/main/java/com/example/mtls/SslContextFactory.java)\

I just cannot use the SslBundles directly at higher builder level thru various builders.

With that you can close the issue as there is a way to do this fairly easily at HttpClient level.

**Comment by wilkinsona** [comment]
We discussed this today and decided that we don't want to do anything here. Thank you for the suggestion though.

Our feeling is that it would be difficult to evolve the SSL bundle API into one where the trust material could be composed. Even after this evolution, it would then be harder to use for the common case where composition is not required. Instead of requiring composition, we recommend creating different clients (such as multiple RestTemplates), one for each external service that has different trust requirements.
