### ISSUE TITLE
org.springframework.web.servlet.resource.PathResourceResolver.getResource never logs a warning

### ISSUE THREAD

**Issue by matthiaskraaz** [spring-projects/spring-boot#38381]
`org.springframework.web.context.support.ServletContextResource.getURL()` 

throws FileNotFoundException, because 

`jakarta.servlet.ServletContext.getResource(String) `

returns null. Therefore

`org.springframework.web.servlet.resource.PathResourceResolver.getResource(String, Resource)`

does not log a warning as intended.

**Comment by wilkinsona** [comment]
It's only code within the `org.springframework.boot` package space that is maintained here. `org.springframework.web` is part of [Spring Framework](https://github.com/spring-projects/spring-framework).

**Comment by matthiaskraaz** [comment]
Thank you for pointing me into the right direction.
