### ISSUE TITLE
filterRegistrationBean urlPatterns are ignored

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-boot#3839]
Hello,
I'm using spring boot 1.2.5 and deploying application to tomcat. I've posted question to [stackoverflow](http://stackoverflow.com/questions/32250619/unable-to-change-filter-mapping-spring-boot). Is there currently any bug in url mapping or do I have something configured wrong?

I need to resolve this urgently, please help :)

Thanks

**Comment by snicoll** [comment]
Please do not cross post, this is a waste of time for everyone. We monitor StackOverflow and this is the right place for any question you might have on Spring Boot.
