### ISSUE TITLE
Add Auto Configuration for SecurityEvaluationContextExtension

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#3840]
We should add auto configuration support for `SecurityEvaluationContextExtension`.

**Comment by shakuzen** [comment]
@rwinch 
I believe this is actually included in 1.3.0.M5? It seems to be mistakenly tagged as 1.3.0 (GA)

**Comment by rwinch** [comment]
@shakuzen Thanks for the note. You are correct. I have updated the milestone. Thanks again!
