### ISSUE TITLE
Reinstate support for auto-configuring an embedded ActiveMQ broker

### ISSUE THREAD

**Issue by mattrpav** [spring-projects/spring-boot#38404]
ActiveMQ 6.0.1 has been released and includes Jakarta support on the broker-side.

Related:
#34011
#35048

**Comment by philwebb** [comment]
Given that we're at the RC phase we've decided to wait until Spring Boot 3.3 to do the upgrade.

**Comment by Grey1024** [comment]
I am a Java backend programmer from China, and I have lost my job. Now, I am looking for a coding job outside of China, and I don’t mind the salary. I am even willing to work for free. Additionally, I hope to improve my English communication skills. If you need my help, please contact me at [jeeun2023@outlook.com](mailto:jeeun2023@outlook.com).
I just want to find something to do; I love programming. If you have the patience to explain your work tasks to someone whose English is not good, I am willing to work for you without caring about payment.

**Comment by mattrpav** [comment]
Revising to ActiveMQ v6.1.0

**Comment by mattrpav** [comment]
@wilkinsona thanks for the update. I’ll work to get a PR up this week for the broker-side work.

**Comment by mattrpav** [comment]
@snicoll thanks for picking it up! I lost my in-progress work in a git repo shuffle.
