### ISSUE TITLE
Upgrade to MySQL 8.2.0

### ISSUE THREAD

**Issue by m1ngyuan** [spring-projects/spring-boot#38423]
MySQL driver 8.2.0 has been released, which includes bug fixes and enhancements

Related:
https://dev.mysql.com/doc/relnotes/connector-j/en/news-8-2-0.html
#36470

**Comment by philwebb** [comment]
Thanks for suggestion but since we're at RC2 we probably won't upgrade now until Spring Boot 3.3. We have an automated process for updates so there's no need to raise an issue. We're actively looking at any minor versions that have been released since RC2 to see if we want to upgrade to them.
