### ISSUE TITLE
@PropertySource should be able to overwrite the default application.properties

### ISSUE THREAD

**Issue by hygl** [spring-projects/spring-boot#3842]
We deploy multiple spring boot apps inside a single tomcat as a war. To set up each application we annotate our main configuration class with a `@ProperySource(value = "${app.config.location:application.properties}", ignoreResourceNotFound = true)` and define the location for the `application.properties` for each app in the `catalina.properties`. 

However if the app has an intern `application.properties`, it overwrites the values of the external config file. It would be nice to  tell the `PropertieSource` to overwrite the default internal config.

**Comment by snicoll** [comment]
That's not how [things are documented](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config). If you want to override this completely, you need to [use the `spring.config.location` property](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files).

**Comment by hygl** [comment]
I know, but as I said I deploy multiple spring boot apps as a war in one tomcat, they do not all have the same config so I can not use spring.config.location.

**Comment by philwebb** [comment]
There's probably not much that we can do about this since `@PropertySource` is a Spring Framework annotation and isn't aware of Spring Boot conventions.
