### ISSUE TITLE
Add support for Oracle Free, the replacement for Oracle XE, with Testcontainers and Docker Compose

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#38476]
See https://github.com/spring-io/start.spring.io/pull/1352, specifically [this comment](https://github.com/spring-io/start.spring.io/pull/1352#issuecomment-1815895518)

**Comment by wilkinsona** [comment]
Re-opening to investigate the test failures on CI:

```
 ORA-12514: Cannot connect to database. Service xepdb1 is not registered with the listener at host 127.0.0.1 port 32783. (CONNECTION_ID=iOW0NRoUQq2zqe2ckHsYEw==)
 ```
