### ISSUE TITLE
Offer API information about custom Actuator endpoints.

### ISSUE THREAD

**Issue by desiderantes** [spring-projects/spring-boot#38504]
Currently, when defining a custom actuator endpoint, there is no info about required parameters or headers to invoke such and endpoint offered by actuator itself. I'm not asking for something like OpenAPI, but to have info about additional parameters or headers offered when I list the endpoints.

**Comment by philwebb** [comment]
Thanks for the suggestion but I'm not sure we want to have the additional complexity that would be required to offer such an endpoint.
