### ISSUE TITLE
Upgrade to HikariCp 5.1.0

### ISSUE THREAD

**Issue by lzysuqianqiu** [spring-projects/spring-boot#38509]
https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES  5.1.0 has already bean released

**Comment by wilkinsona** [comment]
Thanks, but as described in the issue template, we don't need an issue for a dependency upgrade such as this. It's too late to upgrade for today's Spring Boot 3.2 release. We will upgrade in 3.3.

**Comment by w6et** [comment]
> Thanks, but as described in the issue template, we don't need an issue for a dependency upgrade such as this. It's too late to upgrade for today's Spring Boot 3.2 release. We will upgrade in 3.3.

Will version 3.2.1、3.1.7 be upgraded?

**Comment by wilkinsona** [comment]
No. As above, we will upgrade in 3.3. You can of course override the version in the meantime should you wish.
