### ISSUE TITLE
A Java programmer from China is willing to work without compensation.

### ISSUE THREAD

**Issue by Grey1024** [spring-projects/spring-boot#38517]
I am a Java backend programmer from China, and I have lost my job. Now, I am looking for a coding job outside of China, and I don’t mind the salary. I am even willing to work for free. Additionally, I hope to improve my English communication skills. If you need my help, please contact me at [jeeun2023@outlook.com](mailto:jeeun2023@outlook.com).
I just want to find something to do; I love programming. If you have the patience to explain your work tasks to someone whose English is not good, I am willing to work for you without caring about payment.

**Comment by wilkinsona** [comment]
I'm sorry to hear that you have lost your job. Unfortunately, the issue tracker isn't the right place for this. Good luck with the search.
