### ISSUE TITLE
Upgrade the com.gradle.plugin-publish plugin

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#38513]
We're using `com.gradle.plugin-publish` in version `0.15.0` in our CI when publishing the gradle plugin. We should update this to a newer version: https://plugins.gradle.org/plugin/com.gradle.plugin-publish

**Comment by ardada2468** [comment]
Can I start working on this?

**Comment by mhalbritter** [comment]
I don't think this is a good idea, as you'd have no way of testing this.

**Comment by mhalbritter** [comment]
We can get rid of this issue after all releases are done from GitHub actions. The GitHub actions variant of the Gradle plugin publish uses [version 1.2.1](https://github.com/spring-projects/spring-boot/blob/main/.github/actions/publish-gradle-plugin/build.gradle).
