### ISSUE TITLE
Allow properties configured by dev tools to be overridden

### ISSUE THREAD

**Issue by aspan** [spring-projects/spring-boot#3851]
When setting properties in `~/.spring-boot-devtools.properties` the properties don't override the properties in `DevToolsPropertyDefaultsPostProcessor`. It is also not possible to create your own EnvironmentPostProcessor that is ordered after the `DevToolsPropertyDefaultsPostProcessor`. If the `DevToolsPropertyDefaultsPostProcessor` was ordered with for instance `Ordered.LOWEST_PRECEDENCE - 1` it would work as expected.

**Comment by wilkinsona** [comment]
@aspan Out of interest, which properties do you want to override?

**Comment by aspan** [comment]
I want to override the server.session.persistent property because i have some session serialization issues in my spring-boot vaadin application. I will have to fix them but for now it is ok if the session has to be recreated on each restart.

Regards,
Andreas Asplund

**Comment by snicoll** [comment]
I'd go deeper than that. Shouldn't we put the PropertySource so that a profile can override the value?

**Comment by aspan** [comment]
That would be ideal. The overridden properties could then be kept in the project instead of living in the individual developer's `~/.spring-boot-devtools.properties`
