### ISSUE TITLE
Failure to transfer org.springframework.boot:spring-boot-starter-parent:pom:3.2.0 

### ISSUE THREAD

**Issue by hanzhentao** [spring-projects/spring-boot#38519]
Failure to transfer org.springframework.boot:spring-boot-starter-parent:pom:3.2.0 from http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of repo1 has elapsed or updates are forced. Original error: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.2.0 from/to repo1 (http://repo1.maven.org/maven2/): Failed to transfer file http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.2.0/spring-boot-starter-parent-3.2.0.pom with status code 501

![屏幕截图 2023-11-24 005020](https://github.com/spring-projects/spring-boot/assets/68985350/d2234590-de7d-4c4b-8206-5249e81d0d3b)

**Comment by wilkinsona** [comment]
A 501 response from Maven Central is out of our control. It's either a problem with Maven Central itself or with a proxy server the lies somewhere between your computer and Maven Central. Please retry using `-U` as the error suggests.

**Comment by hanzhentao** [comment]
![image](https://github.com/spring-projects/spring-boot/assets/68985350/3933f76d-56d9-4883-babb-54883d9ec29f)
![image](https://github.com/spring-projects/spring-boot/assets/68985350/f4627515-ff34-4d1b-a76b-5c3b2da7f009)
![image](https://github.com/spring-projects/spring-boot/assets/68985350/64c746bc-16e0-49c1-a825-73c1682cc19d)

**Comment by hanzhentao** [comment]
only spring-boot-starter-data-mongodb cant transfer

**Comment by hanzhentao** [comment]
how about 405
Could not transfer artifact org.springframework.boot:spring-boot-starter-data-mongodb:jar:3.2.0 from/to io.spring.repo.maven.release (http://repo.spring.io/release/): Failed to transfer file http://repo.spring.io/release/org/springframework/boot/spring-boot-starter-data-mongodb/3.2.0/spring-boot-starter-data-mongodb-3.2.0.jar with status code 405

**Comment by bclozel** [comment]
@hanzhentao [release downloads from repo.spring.io are not allowed](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023), you should use maven central instead.
