### ISSUE TITLE
Spring Boot is tagged in this repo with 3.2.0 but is not available in Maven Central

### ISSUE THREAD

**Issue by jimshowalter** [spring-projects/spring-boot#38525]
It's announced in https://spring.io/blog/2023/11/23/spring-boot-3-2-0-available-now, but Gradle can't find the artifacts.

https://mvnrepository.com/artifact/org.springframework.boot/spring-boot

Latest version is 3.1.5, for all of the pieces of spring-boot in Maven Central

**Comment by jimshowalter** [comment]
Accidentally closed, so filed a new one: https://github.com/spring-projects/spring-boot/issues/38526.

**Comment by mhalbritter** [comment]
Just FYI, you can also reopen an accidentally closed issue.
