### ISSUE TITLE
Spring Boot is tagged in this repo with 3.2.0 but is not available in Maven Central

### ISSUE THREAD

**Issue by jimshowalter** [spring-projects/spring-boot#38526]
It's announced in https://spring.io/blog/2023/11/23/spring-boot-3-2-0-available-now, but Gradle can't find the artifacts.

https://mvnrepository.com/artifact/org.springframework.boot/spring-boot

Latest version is 3.1.5, for all of the pieces of spring-boot in Maven Central.

**Comment by Adriansun** [comment]
This could be the "Maven central is indexing the front page slowly" thing. It may take up to maybe 24 hours until it shows up. I have been using Spring Boot 3.2 in my own projects for many hours today by importing the version through my Maven POM.

**Comment by jimshowalter** [comment]
I see. Thank you!
