### ISSUE TITLE
with status code 405 Could not transfer artifact org.springframework.boot:spring-boot-starter-data-mongodb:jar:3.2.0  

### ISSUE THREAD

**Issue by hanzhentao** [spring-projects/spring-boot#38520]
Could not transfer artifact org.springframework.boot:spring-boot-starter-data-mongodb:jar:3.2.0 from/to io.spring.repo.maven.release (http://repo.spring.io/release/): Failed to transfer file http://repo.spring.io/release/org/springframework/boot/spring-boot-starter-data-mongodb/3.2.0/spring-boot-starter-data-mongodb-3.2.0.jar with status code 405
![屏幕截图 2023-11-24 010708](https://github.com/spring-projects/spring-boot/assets/68985350/f5098d83-932e-44b8-aff2-d580fd0cc88a)

**Comment by bclozel** [comment]
Duplicates #38519
