### ISSUE TITLE
The startup script should support system accounts with /sbin/nologin

### ISSUE THREAD

**Issue by raehalme** [spring-projects/spring-boot#3852]
The 1.3.0 build adds support for running Spring Boot applications as Unix/Linux services which is a welcome improvement!

System accounts typically use `/sbin/nologin` as their default shell to deny improper use of the account. The startup script should support this by, for example, defining a shell to use when starting the application under the specified account.

A simple solution would be to provide parameter `-s /bin/sh` to the `su` command in the [launch.script](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L127). More advanced solution could allow the user to specify the shell in the environment variables, but I doubt if it would be useful.

What do you think? I'm happy to provide a pull request, if necessary.

**Comment by philwebb** [comment]
A pull request would be most welcome. Are there any downsides to always passing `-s /bin/sh`?

**Comment by raehalme** [comment]
I did some research regarding the use of `/bin/sh` and according to [Wikipedia](https://en.wikipedia.org/wiki/Bourne_shell): "Most Unix-like systems continue to have /bin/sh—which will be the Bourne shell, or a symbolic link or hard link to a compatible shell even when other shells are used by most users." So it should be okay. 

One might consider the use of, for example, `SHELL` variable to control the parameter, but I'm really not sure if that's necessary.

I'll send a pull request right away.

**Comment by raehalme** [comment]
Just to make sure the pull request is not missed, here is the link: https://github.com/spring-projects/spring-boot/pull/3906

**Comment by wilkinsona** [comment]
I'm not sure that using `su -s` is a good idea as it isn't supported everywhere. BSD is one example. I guess we need to decide which Unix-like OSs we want to support.

**Comment by raehalme** [comment]
How about making the `su` command configurable?

**Comment by wilkinsona** [comment]
@raehalme Yes, I think that's what we should do as long as it doesn't get too complex. Would you like to update the PR to use your proposed command as a default with an option to override it using an environment variable?

**Comment by raehalme** [comment]
@wilkinsona Yes, I'll send an updated PR next week.

**Comment by dsyer** [comment]
We're already using "su" in the script. So it won't work on a vanilla BSD (apparently you can enable it). I don't see any reason not to apply this change since it's trivial and it encourages best practice for running services as a "non-user".

**Comment by wilkinsona** [comment]
It's not the use of `su` that's the problem, but that BSD doesn't support the `-s` option

**Comment by raehalme** [comment]
If I have understood correctly the proper option on BSD would be `-m`:

> Leave the environment unmodified. The invoked shell is your
> login shell, and no directory changes are made. 

http://www.freebsd.org/cgi/man.cgi?su%281%29

**Comment by wilkinsona** [comment]
That's my understanding too. It works on OS X which is based on BSD.

**Comment by raehalme** [comment]
I have now added support for specifying environment variable SU_OPTS for the launcher. The default value is `-s /bin/sh` and can be easily changed to, for example, `-m` in the conf file.

**Comment by raehalme** [comment]
I'll also update the docs.

**Comment by raehalme** [comment]
I updated the PR by adding information about `SU_OPTS` to `deployment.adoc`.

**Comment by wilkinsona** [comment]
Unfortunately, that's not the right command structure for BSD. On BSD it needs to be `su -m $run_user -c <command>`. On Linux it needs to be `su -s /bin/sh -c <command> $run_user`. This might be getting into the realms of being more complex than we'd like.

**Comment by raehalme** [comment]
Do you think support for this could be added anyway to enable the functionality at least on Linux systems?

**Comment by raehalme** [comment]
In the long run the launcher script could try to detect if it's running on BSD and act accordingly.

**Comment by wilkinsona** [comment]
We definitely want this to work on Linux for accounts using `/sbin/nologin`. We need to decide if it's worth the effort to also support BSD out of the box. It's starting to look like it's not. I'll discuss with @dsyer and @philwebb.

**Comment by raehalme** [comment]
Ok, thanks!

**Comment by wilkinsona** [comment]
@raehalme I think I was being overly cautious here. The script in its current form doesn't actually work on BSD when run as root and no one's complained. Sorry for the unnecessary back and forth. I'll merge the original commit from your PR to add `-s /bin/sh` later this morning.
