### ISSUE TITLE
SimpleAsyncTaskExecutorBuilder - Option to set taskTerminationTimeout

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects/spring-boot#38529]
I think the builder should expose a method to set the `taskTerminationTimeout`, which was added in Spring Framework 6.1

https://github.com/spring-projects/spring-boot/issues/35710#issuecomment-1654478562

**Comment by mhalbritter** [comment]
We take care of that when doing https://github.com/spring-projects/spring-boot/issues/38528.
