### ISSUE TITLE
Upgrade to Hibernate 6.4

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#38523]
Hi,

to my surprise Hibernate 6.4 was released today shortly after the SB 3.2 release. To an even greater surprise I found the following comment on an issue that happens with Hibernate 6.3: https://hibernate.atlassian.net/browse/HHH-17454?focusedCommentId=113382 

> Hibernate 6.3 won’t be supported at all after the 6.4.0 final release. We don’t have influence of what version Spring Boot decides to be compatible with, but I’m sure they’re going to update supporting 6.4 very soon as that will be the officially supported version.
You can find more info about our maintenance policy on [our website](https://hibernate.org/community/maintenance-policy/).

Maybe we need to rethink Hibernate 6.3 being used in SB 3.2.

Let me know what you think.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
@mbladel is there anything that we can refer to so that we can learn which versions of Hibernate will be supported longer-term? I see that 6.2 has limited support but that 6.1 and 6.3 are end-of-life. How can we learn about this in advance?

**Comment by leshalv** [comment]
Well, hibernate 6.3 is at the end of its life

[hibernate 64.0 https://in.relation.to/2023/11/23/orm-640-final/](https://hibernate.org/orm/releases/)

**Comment by mbladel** [comment]
Hi @wilkinsona, we can only guarantee support on the latest released final major.minor combination. You can find additional information about versions and support at this link: https://github.com/hibernate/hibernate-orm/wiki/Huge-Project,-Small-Team.

**Comment by wilkinsona** [comment]
Thanks, @mbladel. How does 6.2 fit into that? Is there any way for us to know in advance that a minor version will move to limited support rather than end-of-life when the next minor is released?

**Comment by mbladel** [comment]
Feel free to reach out to us directly in our [Zulip chat](https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user), or one of our other [community channels](https://hibernate.org/community/), regarding future version supports plans or any other Hibernate question.

**Comment by wilkinsona** [comment]
We discussed this today and decided that we're going to upgrade in 3.2.1. /cc @mp911de

**Comment by leshalv** [comment]
Considering compatibility with Spring Data JPA, will the version of Spring Data JPA 3.2.x be upgraded at the same time?

**Comment by wilkinsona** [comment]
@leshalv Yes
