### ISSUE TITLE
Spring/Spring Boot documentation misses information about @Observed

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-boot#38521]
Hi

Spring Boot 3.2 release notes state (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-Release-Notes):

`You can now use Micrometer’s [@Timed](https://micrometer.io/docs/concepts#_the_timed_annotation), @Counted, @NewSpan, @ContinueSpan and @Observed annotations. The aspects for them are now auto-configured if you have AspectJ on the classpath.`

I reviewed Spring and Spring Boot reference documentations:

1) https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.micrometer-observation
2) https://docs.spring.io/spring-framework/reference/integration/observability.html

They contain sections about Observability and its usage but nothing about @Observed and its purpose. So it'd be better to

1) Add information with @Observed use cases/examples
2) Explain the difference between @Timed and @Observed

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We try not to duplicate information from other projects' documentation and `@Observed` is [already covered](https://micrometer.io/docs/observation#_using_annotations_with_observed) in Micrometer's documentation. I've updated the release notes to link to it. If you think further documentation would be beneficial, please raise a Micrometer issue.
