### ISSUE TITLE
Is it possible to officially support the JSON5 configuration format?

### ISSUE THREAD

**Issue by Silentdoer** [spring-projects/spring-boot#38537]
like title

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

I assume you're referring to https://json5.org? As far as I can tell, it has yet to gain much traction in the Java ecosystem. We haven't seen any other requests for JSON5 support and there doesn't appear to be a widely-used JSON 5 parser for the JVM. As such, I don't think we should add JSON5 support.

You may want to look at supporting it yourself. To do so, you would have to implement `org.springframework.boot.env.PropertySourceLoader` and register it through an entry in `META-INF/spring.factories`.
