### ISSUE TITLE
reference about logback delimiter is wrong

### ISSUE THREAD

**Issue by shun634501730** [spring-projects/spring-boot#38533]
Hello,

When i reading the spring-boot reference, it seems the below description is wrong.

Please see below details for your reproduce.
1.The reference document url is https://docs.spring.io/spring-boot/docs/3.1.6/reference/html/features.html#features.logging.custom-log-configuration
2.The wrong section as below:
If you want to use a placeholder in a logging property, you should use Spring Boot’s syntax and not the syntax of the underlying framework. Notably, if you use Logback, you should use : as the delimiter between a property name and its default value and not use :-.
3.What's wrong? 
Wrong: Notably, if you use Logback, you should use : as the delimiter between a property name and its default value and not use :-.
Correct: Notably, if you use Logback, you should use :- as the delimiter between a property name and its default value and not use :.

Since the logback document says, it default value delimitor is ":-", for exmaple, "${aName:-golden}". Please see this for more detail: https://logback.qos.ch/manual/configuration.html#defaultValuesForVariables
And also, the spring boot documents says, it default value delimitor is ":", for example, ${username:Unknown}. Please see this for more detail: https://docs.spring.io/spring-boot/docs/3.1.6/reference/html/features.html#features.external-config.files.property-placeholders

Based on above documents, so i think the default value delimitor description is wrong on spring-boot reference.

Please help to check, and fix if it should be fixed. Thanks from a developer which using spring boot.

**Comment by wilkinsona** [comment]
I think the documentation is correct. It's referring to properties that are configured in `application.properties` or `application.yaml`. They are resolved using the environment before being passed into Logback. This resolution is performed entirely by Spring so Logback's syntax is not relevant.

If you are configuring Logback using `logback.xml` or `hogback-spring.xml` then you should use the `:-` delimiter as this is a Logback configuration file and the values are passed directly to Logback. That's not what the linked section of the documentation is about though.
