### ISSUE TITLE
Upgrading to Spring Boot 3.2.0 causes Could not find snakeyaml-2.2-android.jar

### ISSUE THREAD

**Issue by aleixmorgadas** [spring-projects/spring-boot#38549]
Spring Version 3.2.0
io.spring.dependency-management version "1.1.4"
Java 21
Gradle 8.4

When I run gradle, it reports that it is unable to find the next dependency:

```Could not find snakeyaml-2.2-android.jar (org.yaml:snakeyaml:2.2).
Searched in the following locations:
Could not find snakeyaml-2.2-android.jar (org.yaml:snakeyaml:2.2).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/2.2/snakeyaml-2.2-android.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I confirm that Spring Boot 3.1.6 it works as expected.

**Comment by bclozel** [comment]
I think this duplicates #31225. Can you check your dependencies?

We will reopen this issue if you can provide a sample project that replicates this issue. Thanks!

**Comment by aleixmorgadas** [comment]
That's true. The issue was the dependency `com.github.javafaker:javafaker:1.0.2`. It contains the classifier `android`.

I replaced the library with net.datafaker:datafaker:2.0.2 and it worked fine.

Sorry for creating noise :pray:
