### ISSUE TITLE
Typo in release notes for version 3.2

### ISSUE THREAD

**Issue by ottlinger** [spring-projects/spring-boot#38545]
The webpage https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#upgrading-from-spring-boot-31 contains a typo in the first sentence:

The default log output now includes your application name whever you have a spring.application.name property set. If you prefer the previous format, you can set logging.include-application-name to false.

I pressume it should be

The default log output now includes your application name *whenver* you have a spring.application.name property set. If you prefer the previous format, you can set logging.include-application-name to false.

**Comment by philwebb** [comment]
I've edited the page to fix it. Thanks for letting us know!
