### ISSUE TITLE
Add meta-data support for write-only properties on classes annotated with @ConfigurationProperties

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#3854]
The process extracting configurable properties from a class or bean definition annotated with `@ConfigurationProcess` expects both a getter and a setter for a property to actually be considered. That means a class like this would only expose a `firstName` property in the meta-data:

```java
@ConfiguationProperties(prefix = "some.prefix")
class UserConfig {

  …

  public void setFirstname(…) { … }

  public void setLastname(…) { … }

  public String getName() { … }
}
```

The crucial aspect here is that the `firstname` and `lastname` properties only expose setters that are used to eventually construct another object exposed by a getter. One might argue that it's easy to just add the getters but it might be desirable not having to as it might be just semantically incorrect (see [DATAREST-660](https://jira.spring.io/browse/DATAREST-660) for example) to expose these setters.

**Comment by philwebb** [comment]
Somewhat related is #1254

**Comment by philwebb** [comment]
It looks like generating meta-data for classes without getters is going to reek havoc with `@ConfigurationProperties` on third-party libs. We'll fix this instead by creating a new configuration class specifically for spring-data reset and we won't extend `RepositoryRestConfiguration` directly anymore.
