### ISSUE TITLE
Spring Boot [3.2.0] is not compatible with this Spring Cloud release train

### ISSUE THREAD

**Issue by dimasadryantos** [spring-projects/spring-boot#38543]
Problem : 

I after update SpringBoot version to 3.2.0 my application failed to start-up :

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Your project setup is incompatible with our requirements due to following reasons:

- Spring Boot [3.2.0] is not compatible with this Spring Cloud release train


Action:

Consider applying the following actions:

- Change Spring Boot version to one of the following versions [3.0.x, 3.1.x] .
```

And it suggested me to downgrade the version, my question is shall we wait for SpringCloud update ?
Any help would be appreciate.

**Comment by wilkinsona** [comment]
You need to wait for [Spring Cloud 2023.0](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes).

**Comment by dimasadryantos** [comment]
@wilkinsona thank you for quick response :)
