### ISSUE TITLE
Spring Native Auto Reachability of Mono<?> or Flux<?>

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-boot#38546]
We are trying to move to **Spring Native** latest for our **100+ Spring Boot applications** with multiple endpoint / microservices. Ours is all Reactive applications where every object is a `Mono` or a `Flux`. As part of reachability metadata, adding `@RegisterReflectionForBinding` across 100+ applications is really not an easy task.

Is there a plan in place to support `Mono<?>` or `Flux<?>` auto reachability in future? Please consider this as a feature request like how we could unwrap `Mono` or `Flux` in `springdoc api-docs` generation. Thanks.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but it really needs to be made to the Spring Framework team. It's also somewhat related to https://github.com/spring-projects/spring-framework/issues/29194. Please comment on that issue or open a new Spring Framework issue as appropriate.
