### ISSUE TITLE
Spring Boot CLI's `run` command should identify and run Maven & Gradle projects

### ISSUE THREAD

**Issue by spilth** [spring-projects/spring-boot#3855]
If I use `spring run` with no Groovy script provided, it should look for `pom.xml` and `build.gradle` files.

- If `pom.xml` is found, it should run `mvn spring-boot:run`.
- If `build.gradle` is found, it should run `gradle bootRun`.

#### Optional Ideas

- use `server` insteadf of `run`, a la Rails
- `test` should look for the same files and run appropriate test task for that build tool

**Comment by philwebb** [comment]
I'm not too keen on this idea personally. It makes the run command much more difficult to describe and it means that we need to make the CLI aware of Gradle and Maven.

**Comment by philwebb** [comment]
Marking as wontfix for now. Feel free to argue with me if you disagree strongly.

/cc @snicoll @wilkinsona

**Comment by snicoll** [comment]
Yeah, I wouldn't do that either.
