### ISSUE TITLE
Migration form 3.1.5 to 3.2.0 : "Default" Tracer is not provided in test anymore

### ISSUE THREAD

**Issue by wyfrel** [spring-projects/spring-boot#38568]
I had an issue during the migration of a project from Spring Boot version 3.1.5 to 3.2.0.

In 3.1.5 the Spring boot test suite was providing a "default" tracer. I was not able to find the configuration who was adding this tracer. (May be this one ? https://github.com/spring-projects/spring-boot/blob/07d8c996058b70d5a19a7ee302a99c2c97f94367/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/actuate/observability/ObservabilityContextCustomizerFactory.java#L108)

In Spring Boot 3.2.0, no default Tracer is configured. Is this a regression or a wanted behavior ? Maybe this change need to be documented if it's a wanted behavior ?

I've fixed my project by adding an tracer implementation (micrometer-tracing-bridge-otel in my case) and by migrating from the `@WebMvcTest` annotation to the `@SpringBootTest` annotation + `@AutoConfigureMockMvc` annotation

**Comment by mhalbritter** [comment]
Hey, does this help you? https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#observability-in-tests

**Comment by wyfrel** [comment]
Hello Wilkinsona, i'm testing the behavior of an "Exception Handler" of my Rest service. I'm adding the trace information (traceId / SpanId ) of the request in the Response during the exception handling

**Comment by wilkinsona** [comment]
We discussed this today. We think we may be able to modify `@AutoConfigureObservability` so that it can be used to opt into the auto-configuration of tracing and metrics in a sliced-test that otherwise would not have a `Tracer` or `MeterRegistry` available.

**Comment by mhalbritter** [comment]
`@AutoConfigureObservability` can now be applied to sliced tests. If done so, it will auto-configure an in-memory `MeterRegistry`, a no-op `Tracer` and an `ObservationRegistry`.
