### ISSUE TITLE
Need confirmation of EOL of Spring boot 2.7.x

### ISSUE THREAD

**Issue by mnsudhan86** [spring-projects/spring-boot#38560]
According to https://spring.io/projects/spring-boot#support, OSS support for Spring boot 2.7.x has reached "End of support" on 2023-11-24 which is according to [Spring boot support policy](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#spring-boot-support-policy).
However, from this [link](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#end-of-life), I believe "End of life" is different from "End of support" and each Spring Boot releases are usually marked end of life 27 months after they were released.

![image](https://github.com/spring-projects/spring-boot/assets/136066274/6a7aaf18-5d92-4087-bafb-6fe353f5209e)

Going by this "End of life" for Spring boot 2.7.x will be some where in Aug 2024.
I know it is always better to upgrade to latest version, but we have dependency on Java 8 and cannot immediately move to latest version of Spring boot because of this dependency. 
Could you please confirm if we get maintenance releases on top of Spring boot 2.7.x for critical bugs and security issues?

**Comment by bclozel** [comment]
Spring Boot 2.7.x is out of OSS support.
It is not end of life as commercial support is still ongoing for this generation. You should not expect maintenance releases for 2.7.x unless you have subscribed to commercial support.

Thanks!

**Comment by wilkinsona** [comment]
3.x is a major release with 3.0, 3.1, and 3.2 being the minor releases thus far. To be supported for 3 years you have to track the minor releases. Each minor is supported for at least 12 months.

**Comment by amardeep2006** [comment]
Hi @wilkinsona I support a critical project that has close dependency to Springboot open source support . I am preparing the strategy till 2029.
Currently the project is on Springboot 3.3.3 . I update even patches as soon as available.

Can I get a rough date by which we can assume spring boot 4.0.0 to be available ? 
Can I assume following : 
1. Last minor release (with open source support) of 3.x series (3.6) will launch in Nov2025 which will get patches till Nov 2026 .
2. Spring boot 4.x will get first release in May 2026.

Apologies for replying on close thread. Any help highly appreciated.

**Comment by bclozel** [comment]
@amardeep2006 we don't have that information right now. We will publish it on https://spring.io/projects/spring-boot#support as soon as we have concrete plans.

**Comment by amardeep2006** [comment]
Based on this post https://spring.io/blog/2024/10/01/from-spring-framework-6-2-to-7-0
I got the clarity that spring boot 4.x will be released in November 2025.

**Comment by bclozel** [comment]
November 2025 is the provisional date for Spring Framework 7.0. Stay tuned for [the Spring Boot release dates on our milestones page](https://github.com/spring-projects/spring-boot/milestones).
