### ISSUE TITLE
Error building images: Docker API call to "paketobuildpacks builder base" failed with status code 404

### ISSUE THREAD

**Issue by pbilstein** [spring-projects/spring-boot#38575]
Hi,

I have a problem building my Spring Boot Application via bootBuildImage. Seems that necessary packeto images are missing on docker.io, so it might not be correct here, but anyway posting it here (it maybe it is a bug in buildsystem or something) as Spring Boot builds upon packeto here:

Steps to reproduce:

```
git clone https://github.com/spring-guides/gs-spring-boot.git
cd gs-spring-boot/initial
./gradlew bootBuildImage
```

results in 

```
> Task :bootBuildImage FAILED
Building image 'docker.io/library/spring-boot:0.0.1-SNAPSHOT'

 > Pulling builder image 'docker.io/paketobuildpacks/builder:base' ..................................................

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootBuildImage'.
> Docker API call to 'localhost/v1.24/images/create?fromImage=docker.io%2Fpaketobuildpacks%2Fbuilder%3Abase' failed with status code 404 "Not Found"

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 35s
4 actionable tasks: 4 executed
```

This one has Spring Boot 3.1.4 in my download. In my real project I use Spring Boot 3.1.5.

Tested on severel maschines, locally and from some servers under my control.

-EDIT typo-

**Comment by scottfrederick** [comment]
The Paketo project has announced that the Bionic builders are unsafe to use and will be permanently removed soon. See the [Paketo announcement](https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/) for the details. 

Instructions for migrating to the safer and maintained Paketo Jammy builders are documented in a recent [Spring Boot blog post](https://spring.io/blog/2023/09/22/paketo-buildpacks-bionic-end-of-support).

**Comment by pbilstein** [comment]
@scottfrederick thanks for the quick response! So, from what you have posted, it means that Spring Boot 3.1.6 will work fine. I will test it immediately!
