### ISSUE TITLE
Spring-starter-mustache: Clarify exception message for checkTemplateLocationExists

### ISSUE THREAD

**Issue by drigoangelo** [spring-projects/spring-boot#3857]
The exception message on PostConstruct method checkTempletaLocationExists says
"Cannot find template location: {location} (please add some templates, check your Mustache configuration, or set spring.mustache.**template**.check-template-location=false)"

The correct configuration would be "spring.mustache.check-template-location=false"

**Comment by snicoll** [comment]
Duplicates #2788
