### ISSUE TITLE
Reinstate mention of testAndDevelopmentOnly when using Testcontainers at dev time

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#38571]
It looks like it was lost during https://github.com/spring-projects/spring-boot/issues/38336. We should reinstate it and double-check that nothing else was lost.

**Comment by mhalbritter** [comment]
Sorry, I botched the forward merge. I've double checked the changes, and the `testAndDevelopmentOnly` was the only change lost.
