### ISSUE TITLE
Spring Boot 3.2.0 Cache miss for REQUEST dispatch to '/actuator/health/readiness'

### ISSUE THREAD

**Issue by josephearl** [spring-projects/spring-boot#38587]
This seems to be a new warning with Spring Boot 3.2.0:

> Cache miss for REQUEST dispatch to '/actuator/health/readiness' (previous null). Performing MatchableHandlerMapping lookup. This is logged once only at WARN level, and every time at TRACE.

Logger name: `org.springframework.web.servlet.handler.HandlerMappingIntrospector`

I'd expect actuator endpoints like readiness and liveness never to be cached, and to not cause any warnings.

**Comment by bclozel** [comment]
This is due to https://github.com/spring-projects/spring-framework/issues/31588
This should go away once https://github.com/spring-projects/spring-security/issues/14128 is done.

This is not a bug and does not reflect the caching status of the actuator, but rather some internal routing state with the web framework.

**Comment by salamshaikh1** [comment]
Cache miss for REQUEST dispatch to '/generate-token' (previous null). Performing CorsConfiguration lookup. This is logged once only at WARN level, and every time at TRACE  getting this error ervery time i post some thing from post app

**Comment by hendisantika** [comment]
> Cache miss for REQUEST dispatch to '/generate-token' (previous null). Performing CorsConfiguration lookup. This is logged once only at WARN level, and every time at TRACE getting this error ervery time i post some thing from post app

Same issue

**Comment by wilkinsona** [comment]
There's nothing that can be done here. As Brian described above, this is due to https://github.com/spring-projects/spring-framework/issues/31588 and will be addressed by https://github.com/spring-projects/spring-security/issues/14128.

**Comment by krishna123-sudo** [comment]
Cache miss for REQUEST dispatch to '/lifeline/getreport' (previous null). Performing CorsConfiguration lookup. This is logged once only at WARN level, and every time at TRACE.

Same issue

**Comment by wilkinsona** [comment]
And the same response from Spring Boot's perspective. If you must comment, please do so on https://github.com/spring-projects/spring-security/issues/14128.

**Comment by jmaras89** [comment]
Same issue HandlerMappingIntrospector - Cache miss for REQUEST dispatch to '/auth/login' (previous null). Performing MatchableHandlerMapping lookup. This is logged once only at WARN level 
Trying to use ContentCachingRequestWrapper

**Comment by bclozel** [comment]
Alright I'm locking this conversation because we explained the situation several times already but we keep getting the same question. Please read comments above.
