### ISSUE TITLE
SB 3.2 - Nested Jar Support Breaks Nested XML Stylesheets

### ISSUE THREAD

**Issue by nmesot** [spring-projects/spring-boot#38581]
We have nested xml stylesheets that get read by the native Java XML parser / transformer.

```
<!-- stylesheets/subfolder/stylesheet.xsl -->
<axsl:stylesheet xmlns:axsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <axsl:variable name="generalCodes" select="document('GeneralCodeLists.xsd')"/>
    ...
/>
```

```
import org.w3c.Document;
import javax.xml.*;

DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
Document sourceDoc = dbf.newDocumentBuilder.newDocument();
Document resultDoc = dbf.newDocumentBuilder.newDocument();

TransformerFactory factory = TransformerFactory.newInstance();
factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "file");
StreamSource source = new StreamSource((new ClassPathResource("stylesheets/subfolder/stylesheet.xsl")).getInputStream());
Templates templates = factory.newTemplates(source);
Transformer transformer = templates.newTransformer();

transformer.transform(new DOMSource(sourceDoc), new DOMResult(resultDoc));
```

This throws the following exception

```
java.lang.Exception: Could not read stylesheet target 'GeneralCodeLists.xsd' because 'nested' access is not allowed due to restriction set by the accessExternalStylesheet property.
```

Setting the loaderImplementation to CLASSIC fixes the problem.

```
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
            <configuration>
              <loaderImplementation>CLASSIC</loaderImplementation>
            </configuration>
          </execution>
        </executions>
    </plugin>
  </plugins>
</build>
```

**Comment by mhalbritter** [comment]
Thanks for the report. Can you please create a minimal reproducer and provide it to us?

**Comment by nmesot** [comment]
Hi! Sure, here is a working example.
Running instructions:

- Unzip
- Run `mvn clean package`
- Run `java -jar target/app.jar`
- Run `curl localhost:8080/test`

-> observe error

- Uncomment `<loaderImplementation>CLASSIC</loaderImplementation>` in pom.xml (line 40)
- Run `mvn clean package`
- Run `java -jar target/app.jar`
- Run `curl localhost:8080/test`

-> observe that error is gone

Do not run from intelIJ directly, since intelIJ does not build the "Uber Jar".

Java version:
```
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```

Maven version:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: c:\srdev\lds\jdk\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
[spring-boot-bug-report.zip](https://github.com/spring-projects/spring-boot/files/13501069/spring-boot-bug-report.zip)


Note: The code provided is as close to our production setup as possible. Because of various reasons, changing parameters for the Transformer and DocumentBuilderFactory classes is not possible.

**Comment by wilkinsona** [comment]
@nmesot when you say "parameters", does that mean you can't change anything at all on the `TransformerFactory`? The problem does not occur if you configure a `URIResolver` like this:

```java
factory.setURIResolver(new URIResolver() {

	@Override
	public Source resolve(String href, String base) throws TransformerException {
		try {
			URLConnection connection = new URL(base).openConnection();
			try (InputStream input = connection.getInputStream()) {
				return new ResourceSource(new ByteArrayResource(StreamUtils.copyToByteArray(input)));
			}
		}
		catch (Exception ex) {
			throw new TransformerException(ex);
		}
	}
	
});
```

**Comment by wilkinsona** [comment]
Thanks, @johannesboon. Are you a colleague of @nmesot or someone else affected by the same problem?

I'm not very familiar with Spring Web Services and it's not clear to me how `PayloadValidatingInterceptor` would be affected. If possible, could you provide a minimal sample that shows it breaking?

**Comment by johannesboon** [comment]
I think I'm working for a different employer and customer, so "someone else" who is also affected by the same change.

We use <https://docs.spring.io/spring-ws/docs/current/api/org/springframework/ws/config/annotation/WsConfigurer.html#addInterceptors(java.util.List)> that takes instances of e.g.: <https://docs.spring.io/spring-ws/docs/current/api/org/springframework/ws/soap/server/endpoint/interceptor/PayloadValidatingInterceptor.html> 

E.g. like this:



```java
    @Override
    public void addInterceptors(List<EndpointInterceptor> interceptors) {
        PayloadValidatingInterceptor validatingInterceptor = new PayloadValidatingInterceptor();
        validatingInterceptor.setValidateRequest(true);
        validatingInterceptor.setValidateResponse(true);
        validatingInterceptor.setXsdSchema(new SimpleXsdSchema(new ClassPathResource("schemas/ourschema.xsd"););
        interceptors.add(validatingInterceptor);
     }
```

Where `schemas/ourschema.xsd` is a resource the classloader should find in a maven dependency, that is included as jar within the uber jar.

Another example can be found in: <https://github.com/spring-projects/spring-ws-samples/blob/main/echo/server/src/main/java/org/springframework/ws/samples/echo/config/EchoConfig.java> although that might not brake as it uses Spring Boot 3.0 and the Schema is included within the same project, so it does not need to be retrieved from a nested jar.

**Comment by nmesot** [comment]
Nice to see that I am not the only one using xml stylesheets to validate payloads :D.

Configuring the `URIResolver` did the trick, thank you!

**Comment by mdehmel** [comment]
> I think I'm working for a different employer and customer, so "someone else" who is also affected by the same change.
> 
> We use https://docs.spring.io/spring-ws/docs/current/api/org/springframework/ws/config/annotation/WsConfigurer.html#addInterceptors(java.util.List) that takes instances of e.g.: https://docs.spring.io/spring-ws/docs/current/api/org/springframework/ws/soap/server/endpoint/interceptor/PayloadValidatingInterceptor.html
> 
> E.g. like this:
> 
> ```java
>     @Override
>     public void addInterceptors(List<EndpointInterceptor> interceptors) {
>         PayloadValidatingInterceptor validatingInterceptor = new PayloadValidatingInterceptor();
>         validatingInterceptor.setValidateRequest(true);
>         validatingInterceptor.setValidateResponse(true);
>         validatingInterceptor.setXsdSchema(new SimpleXsdSchema(new ClassPathResource("schemas/ourschema.xsd"););
>         interceptors.add(validatingInterceptor);
>      }
> ```
> 
> Where `schemas/ourschema.xsd` is a resource the classloader should find in a maven dependency, that is included as jar within the uber jar.
> 

I am facing the same issue with the described `PayloadValidatingInterceptor` approach. 

The call to `validatingInterceptor.setXsdSchema(...)` is leading to the instantiation of a new `XmlValidator` object. This one is using the following call to load the schema. And that's where the error is coming from.
``` java
SchemaLoaderUtils. loadSchema(new ClassPathResource("schemas/ourschema.xsd"), "http://www.w3.org/2001/XMLSchema" );
```

The `SchemaLoaderUtils` uses the `SchemaFactoryUtils` to create a new `SchemaFactory`.  And there is also a configuration applied: 
``` java
schemaFactory.setProperty("http://javax.xml.XMLConstants/property/accessExternalSchema", "file,jar:file,wsjar");
``` 

When I change the property value as follows, I am able to run `loadSchema` successfully:
``` java
schemaFactory.setProperty("http://javax.xml.XMLConstants/property/accessExternalSchema", "file,jar:file,wsjar,nested");
``` 

I am not really into this schema loading thing. So I cannot say if this is a valid and secure approach. But at least it shows where the problem seems to be coming from.

**Comment by wilkinsona** [comment]
Thanks very much, @mdehmel. I've opened https://github.com/spring-projects/spring-ws/issues/1393 to update `org.springframework.xml.validation.SchemaFactoryUtils` so that `jar:nested` is permitted by default.

I don't think there's anything more that we can do here for this one. If the `URIResolver` workaround is not suitable or until the Spring WS issue to be addressed, an alternative is to configure your uber jar to [unpack the archive](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.build.extract-specific-libraries-when-an-executable-jar-runs) that contains the external resources.
