### ISSUE TITLE
AOP>>joinPoint.getSignature()).getParameterNames() is null since SpringBoot 3.2.0

### ISSUE THREAD

**Issue by hehuipu** [spring-projects/spring-boot#38596]
SpringBoot 3.1.5 + OpenJDK17, below code could get parameternames normally,
but as Title, just upgrade SpringBoot 3.2.0(+OpenJDK17), can't get actual parameternames but null was return.

  String[] methodArgNames = ((CodeSignature) joinPoint.getSignature()).getParameterNames();

**Comment by wilkinsona** [comment]
You need to [compile your code with `-parameters`](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention).

**Comment by hehuipu** [comment]
@wilkinsona 
Tried as below, it is still null for getParameterNames().

<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.11.0</version>
    <configuration>
        <parameters>true</parameters>
    </configuration>
</plugin>

**Comment by bclozel** [comment]
@hehuipu please provide a sample application we can run and we can reopen this issue.
