### ISSUE TITLE
Support wildcards in excludeName on SpringBootApplication and EnableAutoConfiguration?

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3859]
See https://github.com/spring-projects/spring-boot/issues/2962#issuecomment-135442589:

> I have a very big project, where I'd like to use my custom AutoConfigurations.
But I don't like to use any from org.springframework.boot:spring-boot-autoconfigure (I mean package org.springframework.boot.autoconfigure.*)

> Is it possible to exclude them all?

**Comment by philwebb** [comment]
I'm not sure that we should change the current annotation, this seems like an edge case to me.

Since `EnableAutoConfigurationImportSelector` is public in 1.3 and has more protected methods it should be possible to achieve what the user wants by subclassing it.

**Comment by wilkinsona** [comment]
I'd forgotten/wasn't up to speed with the `EnableAutoConfigurationImportSelector` change when I opened this. Subclassing and using your own annotation sounds like a better solution to me too.

**Comment by blacelle** [comment]
EnableAutoConfigurationImportSelector seems not to exist anymore in SprintBoot 2.X

**Comment by gavenkoa** [comment]
`@ComponentScan` has property `excludeFilters` which allows `@ComponentScan.Filter(type = FilterType.REGEX, value = ...)`

**Comment by reda-alaoui** [comment]
To my knowledge, ComponentScan is not involved in autoconfiguration classes loading.
