### ISSUE TITLE
NoUniqueBeanDefinitionException if you don't compile with -parameters option

### ISSUE THREAD

**Issue by himanshunp** [spring-projects/spring-boot#38607]
current spring boot [upgrade guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#upgrading-from-spring-boot-31) suggests to use `-parameters` while compiling but it may be easily overlooked by lot of developers. This seems a huge shift from earlier spring boot upgrades and should be treated as breaking change or must be highlighted in possible issues that may occur.

In my project, I got `NoUniqueBeanDefinitionException` which is a very old exception and always relied on `@Qualifier` to resolve bean conflicts. I initially thought newer spring boot is stricter how it treats bean definitions and never thought it could be related to `LocalVariableTableParameterNameDiscoverer` has been removed in spring framework 6.1 

If you use spring boot as BOM dependency instead of parent, this is even worse as so far we are used to just change version number in pom to upgrade and works out of the box.  
here is a sample project to reproduce the `NoUniqueBeanDefinitionException` :  https://github.com/himanshunp/spring

**Comment by philwebb** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/31675 and #38603
