### ISSUE TITLE
Native image build failed with bouncycastle as JCA provider

### ISSUE THREAD

**Issue by davidl789** [spring-projects/spring-boot#38605]
I'm building a native executable (Spring Boot 3.1.5) with bouncycastle as JCA provider using Spring Boot Gradle Plugin bootBuildImage task.
Native build options:
-H:-EnableSecurityServicesFeature
-H:AdditionalSecurityProviders=sun.security.provider.Sun,sun.security.rsa.SunRsaSign,org.bouncycastle.jce.provider.BouncyCastleProvider

The native build failed with error "Detected an instance of Random/SplittableRandom class in the image heap", more details in attachment 
[random-seed-in-image-heap-error.txt](https://github.com/spring-projects/spring-boot/files/13505993/random-seed-in-image-heap-error.txt)
.

I attempted to resolve it by adding --initialize-at-run-time=sun.security.ssl.SSLContextImpl$AbstractTLSContext but results with more traces, more culprit classes have been added to the list but I'm still unable to resolve it.

**Comment by philwebb** [comment]
Looking at the stack trace in the error.txt file, it doesn't appear that any Spring Boot code is involved. I'm afraid you'll probably need to get advice or help from the GraalVM team.
