### ISSUE TITLE
Upgrade to Spring Data Gosling RELEASE

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3860]

**Comment by snicoll** [comment]
Missing update to spring hateoas

**Comment by olivergierke** [comment]
It might be worth investigating if you could refer to the bean named `linkRelationMessageSource` which is deployed via `HateoasConfiguration` (imported by `@EnableHypermediaSupport` as of 0.19. That would make the object mapper to be able to benefit from the just introduced internationalization support for link titles (see [this commit](https://github.com/spring-projects/spring-hateoas/commit/71ec26fc8d31f1c0982ac1cdc61b83f5d424f3b8) for details).
