### ISSUE TITLE
Docker Image SBOM incomplete

### ISSUE THREAD

**Issue by DarkAtra** [spring-projects/spring-boot#38612]
### Problem

It seems like the SBOM of Docker Images built with the new Paketo Builders is incomplete. We noticed that the versions for some dependencies is missing when we looked at our trivy reports for [the docker image](https://github.com/idealo/spring-endpoint-exporter/pkgs/container/spring-endpoint-exporter/151186644?tag=1.0.10). This yields false positives when scanning the image for security vulnerabilities. I initially thought that this is a bug in trivy and [reported it here](https://github.com/aquasecurity/trivy/discussions/5655).

This is how we're building the docker image in [our project](https://github.com/idealo/spring-endpoint-exporter):
```
./mvnw -B -ntp spring-boot:build-image
```

### Expected Behaviour

All dependency versions are correctly included in the SBOM of the docker image so that security scanners can produce better results.

**Comment by bclozel** [comment]
Spring Boot is not generating this SBOM information as this is done by paketo buildpacks. Can you [create an issue against the Spring Boot buildpack](https://github.com/paketo-buildpacks/spring-boot/issues)?
