### ISSUE TITLE
Kafka listener and Kafka Template auto-configuration for observation support

### ISSUE THREAD

**Issue by hemantmaersk** [spring-projects/spring-boot#38644]
With reference to https://github.com/spring-projects/spring-boot/issues/37388

Could you please add support from Micrometer observability in @KafkaListener & KafkaTemplate

**Comment by philwebb** [comment]
@hemantmaersk We've been intentionally cautious with enabling observations for all technologies in case there is a performance impact. I think we should try to rationalize things if we can so I've opened #38737
