### ISSUE TITLE
Disable trace propagation if tracing is disabled

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#38641]
According to https://github.com/spring-projects/spring-boot/issues/38625#issuecomment-1836120594, `management.tracing.enabled` is used to disable tracing only in tests currently, If we want to [dynamic disable tracing entirely](https://github.com/spring-projects/spring-boot/issues/38625#issuecomment-1838108363) we have to exclude `AutoConfiguration` by `spring.autoconfigure.exclude`, That's not handy especially for [profile combination](https://github.com/spring-projects/spring-boot/issues/27414).

**Comment by philwebb** [comment]
We discussed this today and we'd like to make it so that `management.tracing.enabled` also disables the propagation of traces (probably by adding conditions to brave and otel beans).

**Comment by mhalbritter** [comment]
I reworded the `management.tracing.enabled` property description in the documenation. That property will now disable trace exporting (sending traces to backends) and also trace propagation (e.g. sending trace and span ids via http for example).
