### ISSUE TITLE
Meta annotate @AutoConfiguration with @EnableConfigurationProperties

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#38640]
It would be handy, for example

```
@AutoConfiguration
@EnableConfigurationProperties({MyPropA.class, MyPropB.class})
```

can be written as

```
@AutoConfiguration(properties = {MyPropA.class, MyPropB.class})
```

**Comment by philwebb** [comment]
+1. I also think these kind of shortcuts aren't as critical in auto-configuration classes since the majority of Spring Boot users rely on, but don't typically directly use `@AutoConfiguration`.

**Comment by philwebb** [comment]
Looks like we have enough of a consensus to decline this one. Thanks anyway for the suggestion @ttddyy!
