### ISSUE TITLE
Updating Map with null value is raising NullPointerException because Collectors.toMap is checking map null value

### ISSUE THREAD

**Issue by nlenew** [spring-projects/spring-boot#38673]
Hi,

We have got that issue migrating from Spring Boot 3.1.5 (using spring-data-mongodb 4.1.6) to Spring Boot 3.2.0 (using spring-data-mongodb 4.2.0)
We have a Map we would like to save and sometimes with null values. The problem deals with those null values.
If we have a closer look at the code, we can see it is using stream collectors which requires a non-null value.
![diff_sdm416_sdm420](https://github.com/spring-projects/spring-boot/assets/1235539/13cab92e-085c-471d-b52c-01065ede0b0b)

Can you have a look at this ?

Thank you for your time.

**Comment by wilkinsona** [comment]
Spring Data MongoDB is managed as a [separate project](https://github.com/spring-projects/spring-data-mongodb).

**Comment by nlenew** [comment]
Ok, thanks, will log there.
