### ISSUE TITLE
Polymorphic @ConfigurationProperties are not loaded properly

### ISSUE THREAD

**Issue by anatoliy-balakirev** [spring-projects/spring-boot#38685]
We have a complex configuration properties, with a list of polymorphic objects. Once parsed by Spring Boot using a `@ConfigurationProperties` (version 3.1.6, but the same in 3.2.0) - those polymorphic objects are deserialized as their base class, so all the inherited properties are lost.

Here is a sample project to reproduce the issue:
https://github.com/anatoliy-balakirev/spring_boot_polymorphic_properties
The test `DemoApplicationTests` fails, because manually loaded configuration properties (deserialized by the `new ObjectMapper(new YAMLFactory())`) do not match those, loaded by the Spring Boot (using the `@ConfigurationProperties` mechanism).

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/16900.
