### ISSUE TITLE
Add more gap between the orders of CloudFoundryVcapEnvironmentPostProcessor and ConfigDataEnvironmentPostProcessor

### ISSUE THREAD

**Issue by kvmw** [spring-projects/spring-boot#38684]
`CloudFoundryVcapEnvironmentPostProcessor`'s  order is set to `ConfigDataEnvironmentPostProcessor.ORDER - 1` to give it higher priority. These consecutive numbers ( `N` and `N - 1` ) makes it impossible to register any other `EnvironmentPostProcessor` between them. Setting a bigger gap between two orders ( e.g. `N` and `N - 5`) fixes the issue.

**Comment by philwebb** [comment]
We talked about this and we're going to move the order of `CloudFoundryVcapEnvironmentPostProcessor` in 3.3. This seems like the least risky class to change.
