### ISSUE TITLE
WebFlux and resource server auto-configuration may fail due to null authentication manager

### ISSUE THREAD

**Issue by tgeens** [spring-projects/spring-boot#38713]
Running into issues with upgrading 3.1.6 project to 3.2.0, using webflux + oauth2-resource-server:

```
Caused by: java.lang.IllegalArgumentException: authenticationManager cannot be null
	at org.springframework.util.Assert.notNull(Assert.java:172)
	at org.springframework.security.web.server.authentication.AuthenticationWebFilter.<init>(AuthenticationWebFilter.java:94)
...
```

Looks very similar to https://github.com/spring-projects/spring-boot/issues/37504

To reproduce:
* webflux + oauth-resource-server starters - [Initializr link](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.2.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=webflux,oauth2-resource-server)
* run `contextLoads()` test

Looks like in 3.2 the `ReactiveUserDetailsServiceAutoConfiguration` backs off because of the `@ConditionalOnMissingClass ReactiveOpaqueTokenIntrospector` that oauth-resource-server brings along.
In my `@SpringBootTest`s I don't have any resource server configured, I'm expecting it to fall back to the default `WebFluxSecurityConfiguration`, as it did in 3.1.6

Looking at this, there would be another problem when you have oauth2-login on the classpath, which brings along `ClientRepository` ?

**Comment by wilkinsona** [comment]
Thanks for the report. It looks like the resource server-related auto-configurations are enabling web security to eagerly when they won't actually provide everything that's needed for that to succeed. We need to adjust the conditions on their `WebSecurityConfiguration` classes.

**Comment by tgeens** [comment]
@wilkinsona I'm very surprised with this change, Spring Boot 3.2.1-SNAPSHOT suddenly backs off applying any security ?

Even if oauth2-resource server is not "properly configured", I still expect everything to fall back to the `ReactiveUserDetailsServiceAutoConfiguration` ?

Given the following test:
```
@Test
void testUnauthorized(ApplicationContext context) {
	var client = WebTestClient.bindToApplicationContext(context).build();
	client.get().uri("/").exchange().expectStatus().isUnauthorized();
}
```

* Spring Boot 3.1.6: :heavy_check_mark: HTTP 401
* Spring Boot 3.2.0: :exclamation: context fails to load
* Spring Boot 3.2.1-SNAPSHOT: :question: HTTP 404

**Comment by wilkinsona** [comment]
That's not this change, it's https://github.com/spring-projects/spring-boot/issues/35338 that is causing that to happen. It failed with 3.2.0 as it wasn't backing off correctly and things were being left in a partial, broken state.

**Comment by tgeens** [comment]
Thanks for the quick reply.

I realize #35338 is the original cause, but I'm not sure I understand. Should I open a new issue or do you consider this expected behaviour ?

**Comment by wilkinsona** [comment]
As described in #38753, we need to find a better way to fix this.
