### ISSUE TITLE
Failed run bootBuildImage native image on macos apple silicon

### ISSUE THREAD

**Issue by xuyixun** [spring-projects/spring-boot#38714]
I try to use `gradle:bootBuildImage` build native image on macos apple silicon. Native image build success, but image cant run on same machine with error `rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2`. Try to set `-march=native` `-march=compatibility` fail too

**Comment by scottfrederick** [comment]
The Paketo CNB builder that is used by default by the Spring Boot plugins do not currently support ARM architectures. See this [buildpacks issue](https://github.com/buildpacks/lifecycle/issues/435) for more details. 

There is an [alternative CNB builder](https://github.com/dashaun/paketo-arm64) that does support ARM.
