### ISSUE TITLE
Unify 'observation-enabled' property defaults if possible

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#38737]
See #36451 and #38644 for examples.

Currently some technologies have an `observation-enabled` property which can be used to enable/disable observations. We should try to align the default value of this property for all of them.

There may be performance reasons why we currently don't enable all observations by default.

**Comment by mhalbritter** [comment]
Currently, we have:

* `spring.kafka.listener.observation-enabled` with default `false`
* `spring.kafka.template.observation-enabled` with default `false`
* `spring.pulsar.listener.observation-enabled` with default `true`

**Comment by mhalbritter** [comment]
Superseded by #39276.
