### ISSUE TITLE
new jdk 21 main class

### ISSUE THREAD

**Issue by mjmk3** [spring-projects/spring-boot#38748]
I want to know when we will moving forward to the new structure of the main class in spring projects,
I mean when will see this: 

```
public class DemoApplication {

  void main() {
    SpringApplication.run(DemoApplication.class);
  }

}
```

instead of this:

```
@SpringBootApplication
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

}
```

and if it's stable to use it now, is their any changes in the future???

**Comment by wilkinsona** [comment]
This isn't supported as it's a [preview feature in JDK 21](https://openjdk.org/jeps/445). We may support it in the future but that won't happen until the feature's finalised in the JDK.
