### ISSUE TITLE
logging does not work in native image

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-boot#38765]
I create an little project with the Spring Initializr
- Spring Boot version: 3.2
- Dependency: spring-boot-starter-web
- Java version: 21
You can clone the project here: https://github.com/hansdesmet/nativeLoggingProblem.git

I created a docker image with the command mvn spring-boot:build-image
- Operating System: Windows 11
- Docker version: 24.0.7
During the creation of the image, following messages come on the screen:
[INFO]     [creator]     SLF4J: No SLF4J providers were found.
[INFO]     [creator]     SLF4J: Defaulting to no-operation (NOP) logger implementation

I run the image. The following comes on screen:
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.0)

%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]

You can pull the image with the command
docker pull hansdesmet/nativeloggingproblem
if you want to run the image yourself.

**Comment by wilkinsona** [comment]
Your project is misconfigured as you have not declared the native build tools plugin:

```xml
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
</plugin>
```
Duplicates https://github.com/spring-projects/spring-boot/issues/33432.

**Comment by robinshen36** [comment]
@algora-pbc attempt

This is right up my alley!

Recently finished a project that had some overlap with this.

I'm imagining understanding the current codebase structure as the first step.. Curious about the specific requirements. Any thoughts?

Timeline-wise, probably looking at about a week or so, depending on what we find once I dig in.

Around $420-$620 feels about right, but totally flexible.

Hit me up if you want to discuss.
