### ISSUE TITLE
Add property to specify Docker Compose startup and shutdown flags

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#38763]
@dsyer ran into an issue where a Postgres update prevented the start of the Postgres container used for integration tests. Adding a `--force-recreate --renew-anon-volumes` would fix that, but as of now, there's no possibility to add additional flags to the `docker compose up` call.

**Comment by habuma** [comment]
Similarly, there's no way (at least not that I see) to specify options for Docker Compose "down". For example, when I have a Docker Compose file that stands up a Chroma database in Docker, it also creates a volume. But when the app stops, only the container goes away, not the volume. `docker compose down --volumes` takes the volume down at the command line, but it would be useful to be able to have it remove the volume when the app stops.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/41086 is requesting the ability to set `-p/--project-name`.

**Comment by osopromadze** [comment]
Hi @wilkinsona, can I work on this issue?

**Comment by wilkinsona** [comment]
Thanks for the offer, @osopromadze, but we're not ready to start work on this one, hence the `status: pending-design-work` label.

**Comment by mhalbritter** [comment]
Changes are here and ready to be merged as soon as we have the `3.3.x` branch: https://github.com/mhalbritter/spring-boot/tree/mh/38763-add-property-to-specify-docker-compose-startup-and-shutdown-flags

**Comment by ozozgun** [comment]
Hello. Thanks for this great feature. Is there any documentation on this ?

**Comment by bclozel** [comment]
@ozozgun it's called out [in the appendix here](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.docker-compose.spring.docker.compose.arguments), but it's not mentioned [in the relevant section](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose.lifecycle). Feel free to create a new issue asking for more documentation for this particular feature.

**Comment by wilkinsona** [comment]
We also seem to be missing some docs for `spring.docker.compose.arguments`. I've opened https://github.com/spring-projects/spring-boot/issues/48657.
