### ISSUE TITLE
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher

### ISSUE THREAD

**Issue by carlwang87** [spring-projects/spring-boot#38775]
Upgrade spring boot from 3.1.5 to 3.2.0

**gradle configuration**

```
buildscript {
	ext {
		SpringBootVersion = '3.2.0'
	}
}


plugins {
	id 'java'
	id 'org.springframework.boot' version "${SpringBootVersion}"
	id 'io.spring.dependency-management' version "1.1.4"
}

bootJar {
	manifest {
		attributes 'Main-Class': 'org.springframework.boot.loader.PropertiesLauncher'
		attributes 'Start-Class': 'com.java.test.Application'
		attributes 'Loader-Path': 'jar'
	}
}
```

gradle build jar successfully.

**java -jar test.jar failed as below message**

```
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.PropertiesLauncher
```

downgrade back to 3.1.5, java -jar test.jar works well.

**Comment by bclozel** [comment]
Classes were relocated in #37667

This is being [called out in the upgrade notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support). Thanks!

**Comment by rubensa** [comment]
@bclozel The [Spring Boot Docker Getting Started Guide](https://spring.io/guides/topicals/spring-boot-docker/) still references the old `org.springframework.boot.loader.JarLauncher` class.

**Comment by bclozel** [comment]
@rubensa https://github.com/spring-guides/top-spring-boot-docker/issues
