### ISSUE TITLE
Upgrade to postgresql 9.4-1202-jdbc41

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3878]

**Comment by ravshansbox** [comment]
isn't 9.4-1202-jdbc41 java 7 compiled?

**Comment by wilkinsona** [comment]
Yes, it is, but that's no different to `9.4-1201-jdbc41` which is the current version. We took the decision [here](https://github.com/spring-projects/spring-boot/issues/2545) to use a version that requires Java 7. People stuck on Java 6 should override the version to meet their needs.
