### ISSUE TITLE
MockRestServiceServerAutoConfiguration  does not support RestTemplate and RestClient together

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#38820]
It should be possible to have together RestTemplate and RestClient in application and test them independently.

Unfortunately, currently if RestTemplate is used, RestClient cannot be tested:

`org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerAutoConfiguration.DeferredRequestExpectationManager#getDelegate`

```java
if (!restTemplateExpectationManagers.isEmpty()) {
    Assert.state(restTemplateExpectationManagers.size() == 1,
            "Unable to use auto-configured MockRestServiceServer since "
                    + "MockServerRestTemplateCustomizer has been bound to more than one RestTemplate");
    return restTemplateExpectationManagers.values().iterator().next();
}
Assert.state(restClientExpectationManagers.size() == 1,
        "Unable to use auto-configured MockRestServiceServer since "
                + "MockServerRestClientCustomizer has been bound to more than one RestClient");
return restClientExpectationManagers.values().iterator().next();

**Comment by philwebb** [comment]
I'm not sure I understand your setup. Could you please provide a minimal sample project (either a GitHub project or zip file) that shows what you are trying to do.

**Comment by michaldo** [comment]
Voila: https://github.com/michaldo/rest-client-and-template-together

**Comment by mhalbritter** [comment]
The problem is in `org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerAutoConfiguration.DeferredRequestExpectationManager#getDelegate`:

When a `RestTemplate` is in the context, `restTemplateExpectationManagers` contains 1 entry, which is then always used. The expectation manager, which may be in `restClientExpectationManagers` is then ignored.
