### ISSUE TITLE
Performance - Next Gen Application

### ISSUE THREAD

**Issue by passionate2023** [spring-projects/spring-boot#38838]
Hi,

I'm exploring few next generation framework to build a microservice web application.

On analysis come across the following

colesico (https://github.com/colesico/java-frameworks-comparison)
Micronaut (https://github.com/micronaut-projects/micronaut-core)
Quarkus (https://github.com/quarkusio/quarkus)
Spring Boot - (https://github.com/spring-projects/spring-boot)

#1 - Not active 
#2 - 284 contributors - active
#3 - 884 contributors - active
#4 - 1039 contributors - active

#1 - 1 star
#2 - 5.9k stars
#3 - 12.6k stars
#4 - 70.9k stars

Does spring boot latest version has the fixes for the issues mentioned in the other open source frameworks?

Thanks

**Comment by philwebb** [comment]
I'm not sure I understand the question, but regardless we only use this issue tracker for bugs and enhancement requests. We leave comparisons to other frameworks for the broader community and try to focus only on our own work.

You should use whichever project best suits your needs.
