### ISSUE TITLE
File (image) reading from disk is not working in 3.1.6 and 3.2.0

### ISSUE THREAD

**Issue by voodoo98** [spring-projects/spring-boot#38835]
Hi,

This code works properly in 3.1.5, but not loading image neither in 3.1.6 nor 3.2.0:

```java
final String url = request.getRequestURI();
final File resource = new FileUrlResource(IMAGE_HOME_DIR + url).getFile();
final byte[] bytes = Files.readAllBytes(resource.toPath());
return ResponseEntity.ok().contentType(MediaType.IMAGE_JPEG).body(bytes);
```

comment: final **HttpServletRequest** request;

It works on my local machine with every version (including 3.1.6 and 3.2.0), but not working from docker container in a linux machine (server).

No error message in the logs. 
Browser says: 404 not found

**Comment by bclozel** [comment]
Please share a minimal sample application (using the Spring Boot docker support) so that we can reproduce the problem.

**Comment by voodoo98** [comment]
I have just checked the Win10 local docker desktop, and it is working. 
I will try to give more information later. 
Thank you!

**Comment by bclozel** [comment]
Ok we'll reopen this issue once you manage to replicate the problem independently. Thanks!

**Comment by voodoo98** [comment]
I solved by adding ":z" to end of volume defintion
