### ISSUE TITLE
getSigners() info is lost for signed jars when using the new loader implementation with requiresUnpack

### ISSUE THREAD

**Issue by lburja** [spring-projects/spring-boot#38833]
Bug report

After upgrading to Spring Boot 3.2, my application stops working, until I add the `<loaderImplementation>CLASSIC</loaderImplementation>` configuration to the `repackage` Maven goal.

The particularity of my application, is that one of the jars is a security library which is signed (the library recuperates the signature via `Class::getSigners()` to verify it when initializing). In previous versions of Spring Boot, `requiresUnpack` used to do the trick:

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <requiresUnpack>
            <dependency>
                <groupId>eu.europa.ec.digit.iam.eulogin.client</groupId>
                <artifactId>eulogin-tomcat-10.0</artifactId>
            </dependency>
        </requiresUnpack>
    </configuration>
    ...
</plugin>
```
Now, the application only works by reverting to the CLASSIC loader implementation.

By debugging the application, I see the following differences between the two cases:

In the CLASSIC loader, the library is loaded via `LaunchedURLClassLoader` using the scheme `file:/...`
![image](https://github.com/spring-projects/spring-boot/assets/459215/057f3c0a-d103-409b-b7a9-b62399cb7905)

and the signers are correctly returned:
![image](https://github.com/spring-projects/spring-boot/assets/459215/22feba26-e4e4-4ac0-ab02-1f111bb2edf1)

In the new loader, the library is loaded via `LaunchedClassLoader` using the scheme `jar:file:/...`
![image](https://github.com/spring-projects/spring-boot/assets/459215/f05caa46-ebb3-4a3f-81e4-483d9cf4139d)

and the signers are lost:
![image](https://github.com/spring-projects/spring-boot/assets/459215/5c24e060-5492-4256-92b1-fe0345eb1812)

It would be desirable that the `getSigners()` info of signed jars is preserved by the loader, when using the `repackage` Maven goal.

**Comment by philwebb** [comment]
Thanks for the analysis @lburja. Hopefully fixed for the next release.
