### ISSUE TITLE
@Timed annotation breaks http server metrics with Jersey

### ISSUE THREAD

**Issue by baeyenwo** [spring-projects/spring-boot#38843]
`MetricsAspectsAutoConfiguration` introduced in Spring boot v3.2.0 breaks existing metrics configured by Spring.
Micrometer maintainers have been discussing about the issue here: https://github.com/micrometer-metrics/micrometer/issues/780

Metrics will be registered/counted twice, and in case of Prometheus only one metric will ultimately be reported.
In our case this caused the disappearance of Spring `http.server.requests` metrics in favor of a metric with default tags created by `TimedAspect` (if a name is defined for the metric e.g. `@Timed('MyMetricName')`).

The issues they mentioned should likely be handled by Spring boot if spring-boot enables TimedAspect by default.

The workaround suggested there is the strategy I would suggest to fix this bug, but maybe a more general solution exists to reduce confusion.
```java
@Bean
@ConditionalOnMissingBean
TimedAspect timedAspect(MeterRegistry registry,
		ObjectProvider<MeterTagAnnotationHandler> meterTagAnnotationHandler) {
	TimedAspect timedAspect = new TimedAspect(registry, this::skipControllers);
	meterTagAnnotationHandler.ifAvailable(timedAspect::setMeterTagAnnotationHandler);
	return timedAspect;
}

private boolean skipControllers(ProceedingJoinPoint pjp){
	Class targetClass = pjp.getTarget().getClass();
	return (targetClass.isAnnotationPresent(RestController.class) || targetClass.isAnnotationPresent(Controller.class));
}
```

**Comment by mhalbritter** [comment]
I just annotated a controller method with `@Timed` and my Prometheus shows up both metrics (the timed one and the `http.server.requests` one`).

If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by baeyenwo** [comment]
https://github.com/baeyenwo/spring-boot-3-metric-issue - this project contains a test demonstrating the issue

**Comment by mhalbritter** [comment]
I can reproduce it, but only using Jersey. With WebMVC, it works. In your sample,

* `tutorials0` (no `@Timed`) generates a `http_` metric
* `tutorials1` (`@Timed`) generates a `http_` metric and a custom one
* `tutorials2` (`@Timed(value = "tutorials2")`) generates no `http_` metric, but a custom one

**Comment by mhalbritter** [comment]
`MetricsRequestEventListener` is from the Micrometer project, so this looks like a bug in their code. Could you please open an issue on their tracker and reference this issue? Thanks!
