### ISSUE TITLE
Add changing log levels per user session

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#3884]
It would be nice to support changing log levels per user session. I have a prototype of this at https://github.com/rwinch/spring-session-logging/ We would likely want to expose via an Endpoint so that it can be managed via all the endpoint types (i.e. JMX, SSH, HTTP, etc).

**Comment by rwinch** [comment]
PS: I added a 1.3.0 release for now so we don't forget about it, but this pending discussions after SpringOne

**Comment by wilkinsona** [comment]
RC1 is post SpringOne so I've moved it to there

**Comment by snicoll** [comment]
This is highly related to #3819

**Comment by philwebb** [comment]
I don't think we'll get to this in 1.3 so I'm pushing back to 1.4 for now.

**Comment by rwinch** [comment]
@philwebb Agreed

**Comment by philwebb** [comment]
I'm not convinced that this is something we should support out of the box. Being as the implementation is logback specific, and for quite a specific requirement, I think it would be better as an external auto-configuration.
