### ISSUE TITLE
Consider harmonizing the Spring Framework and Spring Boot defaults for RestClient request factory

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#38856]
Spring Framework [documents](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/client/RestClient.java#L346-L361) that the default `ClientHttpRequestFactory` used when building a `RestClient` is the following, conditional on the classpath: 

* Apache HTTP Client
* Jetty HTTP Client
* JDK HTTP Client
* `SimpleClientHttpRequestFactory`

Spring Boot's `RestClient` auto-configuration [overrides](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/client/RestClientAutoConfiguration.java#L83C51-L83C51) the request factory using [`ClientHttpRequestFactories`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/ClientHttpRequestFactories.java#L86-L112), which has the following order:

* Apache HTTP Client
* Jetty HTTP Client
* OkHttp3 Client (deprecated)
* `SimpleClientHttpRequestFactory`

The result is that the JDK HTTP client is not considered when Spring Boot auto-configures the `RestClient`. We should consider bringing the Boot defaults in line with Framework.

**Comment by wilkinsona** [comment]
`JdkClientHttpRequestFactory` and `SimpleClientHttpRequestFactory` behave differently, particularly with respect to redirects. With no easy was to choose to use the simple client instead of the JDK client, we didn't want to make a breaking change to the default. See https://github.com/spring-projects/spring-boot/pull/36118 and https://github.com/spring-projects/spring-boot/issues/36266 for further details.

**Comment by scottfrederick** [comment]
Closing in favor of #36266.

**Comment by Washingtonwei** [comment]
> `JdkClientHttpRequestFactory` and `SimpleClientHttpRequestFactory` behave differently, particularly with respect to redirects. With no easy was to choose to use the simple client instead of the JDK client, we didn't want to make a breaking change to the default. See #36118 and #36266 for further details.

Thank you! I am glad that since Spring Boot 3.4.0, JdkClientHttpRequestFactory is now the default HTTP client library instead of SimpleClientHttpRequestFactory. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#restclient-and-resttemplate
