### ISSUE TITLE
Fine grained enabled/disable on different Tracers.

### ISSUE THREAD

**Issue by ooraini** [spring-projects/spring-boot#38859]
In situation where you want to use a different implementation in dev/prod. For example Zipkin in local machine and OTLP in production. The current AutoConfiguration classes use `@ConditionalOnEnabledTracing` which enables/disables all of them.

Does it make sense to add `management.zipkin.tracing.enabled`, `management.otlp.tracing.enabled`?

**Comment by philwebb** [comment]
We're not too keen to add too many `enabled` poroperties, and in this case it's slightly unusual to switch tracing backends in different environments.

We recommend directly disabling the auto-configuration classes if you want to do this. Something like:

```properties
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration
```

and

```properties
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.tracing.BraveAutoConfiguration
```

Depending on which one you want to disable.
