### ISSUE TITLE
JSTL circular view error in Java 21

### ISSUE THREAD

**Issue by ujjwaleee26** [spring-projects/spring-boot#38857]
Hey ,I am facing a lot of issues regarding this JSTL usage for the springboot project on eclipse ide .
I have seen the previous issues on this repo before and nothing seems to work for me, I am posting my pom.xml .If anyone could help me, It would be great. Its a maven project  showing error:
`There was an unexpected error (type=Internal Server Error, status=500).
Circular view path [login]: would dispatch back to the current handler URL [/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
jakarta.servlet.ServletException: Circular view path [login]: would dispatch back to the current handler URL [/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)`

    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.0</version>
		<relativePath/> 
	</parent>
	<groupId>com.springboot.todolist</groupId>
	<artifactId>first</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>first</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>	
			<scope>provided</scope>
		</dependency>
		<dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <version>1.2</version>
        </dependency>
        <dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet.jsp.jstl</groupId>
			<artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
			<version>3.0.0</version>	
		</dependency>
		<dependency>
			<groupId>org.glassfish.web</groupId>
			<artifactId>jakarta.servlet.jsp.jstl</artifactId>
			<version>3.0.1</version>
		</dependency>
 		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by quaff** [comment]
Do you confirm it works with Java 17?

**Comment by ujjwaleee26** [comment]
Hi @quaff ,I am not sure about java 17, the course I am doing about SpringBoot suggests on using whatever latest is available, so I create a SpingBoot Project on spring initializer,with java 21 and maven and when i am trying to use JSTL tags by adding these dependencies they are shwoing `There was an unexpected error (type=Internal Server Error, status=500).
javax/servlet/jsp/tagext/TagLibraryValidator
java.lang.NoClassDefFoundError: javax/servlet/jsp/tagext/TagLibraryValidator`. I have seen every solution possible ,but not working, can you please help

**Comment by bclozel** [comment]
There is an issue with your application dependencies. You should not depend nor import from the `javax.*` namespace as Spring Boot 3 requires `jakarta.*`. Please review your dependencies and ask further questions on StackOverflow.
