### ISSUE TITLE
Use meta-annotations on @AutoConfigureWebMvc to compose it with @AutoConfigureJson

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#38869]
Currently `@AutoConfigureWebMvc` imports JSON auto-configuration directly. If we use `@AutoConfigureJson` then any user customizations to `org.springframework.boot.test.autoconfigure.json.AutoConfigureJson.imports` would be automatically picked up. We should review if the current arrangement is intentional and if we should switch.

**Comment by Wzy19930507** [comment]
@philwebb Hello may i pick it up, and also annotations @AutoConfigureJson on @AutoConfigureWebClient and @AutoConfigureJsonTesters
```
@AutoConfigureJson
public @interface AutoConfigureJsonTesters {
```

**Comment by scottfrederick** [comment]
Closing in favor of #39253
