### ISSUE TITLE
META-INF entries are duplicated under BOOT-INF/classes causing "Conflicting persistence unit definitions" error

### ISSUE THREAD

**Issue by rmatec** [spring-projects/spring-boot#38862]
Hi,

We recently upgraded to Spring Boot 3.2.0 and we are seeing the following error when the service starts up.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/config/EclipseLinkJpaConfiguration.class]: Conflicting persistence unit definitions for name 'persistence-config': nested:/opt/application/service.jar/!BOOT-INF/classes/, file:/opt/application/service.jar
```

We have the persistence configuration in `src/main/resources/META-INF/persistence.xml`

Am I right to think this is because of the new Nested Jar Support? It appears the jar file is twice in the error message above, one with nested:... and one without.

If we fallback to the classic loader the service starts up ok.

**Comment by scottfrederick** [comment]
@rmatec We have fixed several issues in the area of the new loader. Can you test with the latest Spring Boot `3.2.1-SNAPSHOT` and see if your use case works without falling back to the classic loader?

**Comment by rmatec** [comment]
@scottfrederick I tried with the snapshot version but I am getting the same error.

**Comment by philwebb** [comment]
@rmatec Can you please provide the full stacktrace and if possible a sample application that reproduces the problem.

**Comment by rmatec** [comment]
Hi @philwebb 
I created the following repo with a simple example https://github.com/rmatec/nested-jars-issue
To reproduce the issue, generate a jar file and run it.

**Comment by rmatec** [comment]
Thanks @philwebb
