### ISSUE TITLE
File names are hard to read on guides  (in dark mode)

### ISSUE THREAD

**Issue by mansurissa** [spring-projects/spring-boot#38897]
## Hard to read text

> 
File names are hard to read in pages under guides
For example:
<img width="995" alt="image" src="https://github.com/spring-projects/spring-boot/assets/50937835/92de74d7-f1f2-4394-89f1-695056de2b83">

 (dark mode of this page https://spring.io/guides/tutorials/rest/)

**Comment by bclozel** [comment]
Can you open this issue against https://github.com/spring-guides/getting-started-guides ? This code is not managed in this repository.

**Comment by mansurissa** [comment]
> Can you open this issue against https://github.com/spring-guides/getting-started-guides ? This code is not managed in this repository.

Yeah, thanks. Just opened on this other repo
