### ISSUE TITLE
Add support for custom x-www-form-urlencoded payload field names mapping

### ISSUE THREAD

**Issue by Smedzlatko** [spring-projects/spring-boot#3890]
When processing an `HttpRequest` with `x-www-form-urlencoded` content, we can use a controller with POJO matching the payload structure.

Example payload: `value_first=value1&value_second=value2`

```java
@RequestMapping(method = RequestMethod.POST, consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
 public String handlePost(@ModelAttribute Body body) {
 }
```
POJO:
```java
public class Body {
 private String value_first;
 private String value_second;
}
```

The problem is that the variable names must match the field names in the `HttpRequest` payload in order  to be processed by the controller. There is not way of naming them differently, for example, if I do not want to use underscopes in Java variable and method names.

What I would appreciate would be using something like this:
```java
@FormAttribute
private String value1;
```

**Comment by philwebb** [comment]
Changes would need to be made in core Spring to support this. I've raised [SPR-13433](https://jira.spring.io/browse/SPR-13433) for them to consider it. Feel free to track that issue.

Thanks for the suggestion.

**Comment by philwebb** [comment]
@Smedzlatko Rossen has some followup questions if you could comment on [SPR-13433](https://jira.spring.io/browse/SPR-13433?focusedCommentId=119316&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-119316)

**Comment by Smedzlatko** [comment]
As for the Rossens' comment: yes, I should have clarified this in my simplified example. It should , of course, be:
```java
@FormAttribute("value_first")
private String value1;
```java

As for the requirement, I am not saying that this is a core functionality of Spring that I am desperately missing but imagine this scenario:

You are processing a form-encoded payload from a third party service and you want to use POJO to map the values. You use camelCase in your whole project and now you are forced to use underscopes if the third party service does so (in the POJO) or write your own converter just for this purpose.

When I encountered this problem, I immediately looked for some Spring functionality to tackle this and was suprised that there is none. Feel free to close this issue if you feel that I am being unreasonable but I expected more people having this issue as well.

**Comment by wilkinsona** [comment]
@Smedzlatko Could you make that comment on [SPR-13433](https://jira.spring.io/browse/SPR-13433), please? I'd copy it over but I think it would be better if it's obviously from you.

**Comment by Smedzlatko** [comment]
@wilkinsona I have created an account there and copied my reply. Thank you for you support!
