### ISSUE TITLE
Upgrade to MariaDB 3.3.2

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#38901]
`org.mariadb.jdbc:mariadb-java-client:3.3.0` has been released shortly before Spring Boot 3.2.0, which is based on `org.mariadb.jdbc:mariadb-java-client:3.2.0`. Since then, there has been no 3.2.x maintenance releases of the connector.

We should determine whether the 3.2.x generation of the connector is immediately superseded and whether we should upgrade our 3.2.x maintenance branch. In all cases, Spring Boot 3.3.x should use the latest minor of the connector when we'll release.

**Comment by wilkinsona** [comment]
The [release notes for 3.3](https://mariadb.com/kb/en/mariadb-connector-j-3-3-0-release-notes/) say that it "will replace 3.2 as the maintenance releases". Given this, we discussed this today and concluded that we should upgrade to MariaDB 3.3.x in Spring Boot 3.2.x.
