### ISSUE TITLE
WARN of deprecation of org.hibernate.dialect of SQLServer2012Dialect

### ISSUE THREAD

**Issue by darckyn** [spring-projects/spring-boot#38905]
Hello.
I just migrated successful from Spring Boot version 2.7.9 to 3.2.1 and the following alerts are appearing:

```
2023-12-21 17:02:20.211  WARN 15160 --- [  restartedMain] o.h.o.deprecation                        : HHH90000025: SQLServer2012Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
```

```
2023-12-21 17:02:20.211  WARN 15160 --- [  restartedMain] o.h.o.deprecation                        : HHH90000025: SQLServer2012Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
2023-12-21 17:02:20.212  WARN 15160 --- [  restartedMain] o.h.o.deprecation                        : HHH90000026: SQLServer2012Dialect has been deprecated; use org.hibernate.dialect.SQLServerDialect instead
```

I use the SqlServer 2019 database and these are the application.properties settings:
(I applied IPs, ports, users and passwords just to give an example)

```
spring.datasource.url=jdbc:sqlserver://255.255.255.255:8095;encrypt=false
spring.datasource.hikari.catalog=DATA_BASE_EXAMPLE
spring.datasource.username=user.of.api
spring.datasource.password=aVeryNicePa$sw0rd
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database=sql-server
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=true
```

Please, can help to resolve this warm?

I am available to send more information if necessary.

Thank you very much,

**Comment by philwebb** [comment]
As far as I can tell Spring Boot does not set `hibernate.dialect` so I suspect this is something specific to your application. Please can you provide a sample application that replicates the problem?

**Comment by philwebb** [comment]
This might be a similar issue to spring-projects/spring-framework#31892

**Comment by snicoll** [comment]
From what I've done recently, I confirm that a database platform or some tuning of JPA properties must be done for this to trigger. By default, Spring Boot does not specify a dialect and let Hibernate pick it (so that warning wouldn't show). 

I've created https://github.com/spring-projects/spring-framework/issues/31896 to review the dialects but please consider removing that customization in your project.

**Comment by darckyn** [comment]
I just closed the issure by accident.
sorry

**Comment by snicoll** [comment]
@darckyn did you read my comment there? Have you tried removing the following:

```
spring.jpa.database=sql-server
```

**Comment by darckyn** [comment]
Hi @snicoll.


> @darckyn did you read my comment there? Have you tried removing the following:
> 
> ```
> spring.jpa.database=sql-server
> ```

I read it, but I didn't understand what you meant or which setting to adjust

I removed the mentioned setting and the alert stopped showing.

I also tested CRUD via the application and operations worked normally after removing the configuration.

Thank you very much for your attention, help and patience.
