### ISSUE TITLE
Support configuration properties for CORS configuration

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-boot#38909]
**Current situation:**  we need to write code to implement the MVC CORS configuration using java configuration or xml file.  This is as per described in https://docs.spring.io/spring-framework/reference/web/webmvc-cors.html

**Enhancement:** I would like to propose to support this via **properties and yaml** as well, using predefined properties keys, and let the auto-configuration for spring mvc do the job.

**Comment by philwebb** [comment]
The `CorsRegistry` interface is quite a complex API to represent as properties so I'm not sure that we should do this. Flagging to see what the rest of the team think.

**Comment by wilkinsona** [comment]
The actuator properties and the MVC XML are each configuring a single set of CORS configuration. A properties-based equivalent of `CorsRegistry` would need to be able to configure multiple sets of CORS configuration. I think that would be cumbersome as the path pattern is the identifier for each set of configuration:

```
spring.web.cors./api/**.allowed-origins=…
spring.web.cors./api/**.allowed-methods=…
spring.web.cors./api/**.allowed-headers=…
spring.web.cors./api/**.exposed-headers=…
```

I doubt this would work, particularly with environment variables where certain characters are restricted.

An alternative would be to invent some unique identifier that's repeated to create each set of configuration:

```
spring.web.cors.api.path-pattern=/api/**
spring.web.cors.api.allowed-origins=…
spring.web.cors.api.allowed-methods=…
spring.web.cors.api.allowed-headers=…
spring.web.cors.api.exposed-headers=…
```

I don't like this either. IMO, the Java API is a better option.

**Comment by bclozel** [comment]
I think the Java API is a better choice here too. While this model is supported by Spring Cloud Gateway, I think that the tradeoff is a bit different when managing a gateway vs. an application.

**Comment by wilkinsona** [comment]
There's the cost of implementing the feature and then maintaining it. This maintenance cost is likely to be larger than we'd like as the support would only work well with YAML files whereas Spring Boot users expect configuration properties to work with properties files, environment variables, system properties and so on as well.

If you are happy with support that's only intended for use with YAML, your best option is to implement it yourself using a `WebMvcConfigurer` and your own `@ConfigurationProperties`-annotated class. Thanks anyway for the suggestion.
