### ISSUE TITLE
Missing  spring-boot-gradle-plugin 3.2.1 artifact on maven

### ISSUE THREAD

**Issue by IsNull** [spring-projects/spring-boot#38914]
It appears as if the `spring-boot-gradle-plugin` artifact was not released for 3.2.1. It's missing on maven central:

https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-gradle-plugin
<img width="1103" alt="Screenshot 2023-12-22 at 17 56 40" src="https://github.com/spring-projects/spring-boot/assets/439313/e4986ab5-efdd-4264-a910-7ad89a557eab">

This breaks gradle in very strange ways, when using the below config. (It falls back on a cached version but behaves strange)

```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:3.2.1")
    }
}

```

 I was hunting for the cause way too long. 🙈

**Comment by bclozel** [comment]
If I'm not mistaken, [the gradle plugin is deployed on the Gradle plugin repository](https://plugins.gradle.org/m2/org/springframework/boot/spring-boot-gradle-plugin/3.2.1/) as it should and Gradle should resolve from this location. I can also see [the bits deployed on Maven Central](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/3.2.1/). I mvnrepository.com is a third party index that does not keep up with Central at all time?

I'm closing this issue as a result. If there are still issues with this, please provide a sample application and error logs so we can have a look.
