### ISSUE TITLE
Error with  org.hibernate.dialect.Oracle12cDialect

### ISSUE THREAD

**Issue by marcosMatias** [spring-projects/spring-boot#38918]
When updating to version 3.2.1 my application broke.
It was because of the line spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
when it is commented on, the application goes up normally.
Didn't have this problem in version 3.2.0

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/31892
