### ISSUE TITLE
Incorrect mapping on constructor expression with Oracle Database

### ISSUE THREAD

**Issue by GledisLami** [spring-projects/spring-boot#38934]
If on the database the data type is NUMBER(22,3), it still gets picked up as an int from JPQL and requires a constructor with type int for that field, instead of double

**Comment by bclozel** [comment]
Unfortunately this doesn't give us much to work on this. From what you're describing this is most likely a Hibernate or Spring Data JPA issue.

Please reconsider this issue, gather more information like stack trace and error messages. A project that reproduces the problem would really help as well. This will be useful if you intend to create an issue on a different project. Thanks!
