### ISSUE TITLE
Unable to access the web application using default port

### ISSUE THREAD

**Issue by anirudh-hegde** [spring-projects/spring-boot#38945]
Hey Developers, 
I've developed a basic portfolio application using spring-boot and html.
I've created a jar file and when I try to execute it it shows :
![image](https://github.com/spring-projects/spring-boot/assets/105560839/571f55d2-2f96-4f7f-9c42-c73e3dd0e005)

Here's my GitHub repo link: https://github.com/anirudh-hegde/AssetApp

**Comment by mannam11** [comment]
@anirudh-hegde do you have spring-web dependency in your project.
if not try to add and retry.

**Comment by anirudh-hegde** [comment]
> @anirudh-hegde do you have spring-web dependency in your project. if not try to add and retry.

I already added dependencies but however I created new project and now it's absolutely working well.
So I'm closing this issue.

**Comment by mannam11** [comment]
@anirudh-hegde sounds great..!
