### ISSUE TITLE
Consider renaming logging.exception-conversion-word

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3895]
Perhaps we should provide an enum to make it a little easier to configure?

`logging.exception-root-cause=FIRST/LAST`

**Comment by snicoll** [comment]
I like that.

**Comment by wilkinsona** [comment]
I like the ease of switching the location of the root cause. I don't like losing the other options that can be configured using the conversion word, such as whether or not class packaging information is included.
