### ISSUE TITLE
Passing spring.active.profiles argument to tomcat spring boot deployment via command line

### ISSUE THREAD

**Issue by shiv86** [spring-projects/spring-boot#3896]
I know for an embedded server passing this as an argument works fine: --spring.profiles.active=dev
However I have struggled to get this working for a standalone Tomcat server deployment.

I have attempted to do this 5-6 different ways with no luck: http://stackoverflow.com/questions/32327522/spring-boot-yml-and-standalone-tomcat-8-server

what is the correct way of passing spring boot args to a standlone tomcat server ?

**Comment by snicoll** [comment]
Please do not cross-post, this is a waste of time for everybody. I can see that @mdeinum gave you a few insight that look good to me.
