### ISSUE TITLE
Spring Boot CLI should support default configuration file

### ISSUE THREAD

**Issue by spilth** [spring-projects/spring-boot#3897]
I'd like to be able to create a ~/.springrc (or ~/.spring.properties) file that contains entries like:

```
boot-version: 1.2.5.RELEASE
java-version: 1.7
build: gradle
```

So that every time I use the `init` command I don't have to pass those options on the command-line.

**Comment by snicoll** [comment]
Good one. I've thought of that myself and I think it should actually apply to Spring CLI, not only one particular command.

**Comment by philwebb** [comment]
Is there any specific reason you don't want to always use the latest stable version with Java 8?

**Comment by spilth** [comment]
Me personally? No. 

The enterprise clients that I work with? That's another story.

This request is mainly for having Gradle as a personal default but I think all options should be supported.

**Comment by philwebb** [comment]
Thanks. I was mainly asking because Spring 5 (and therefore Boot.next) will require Java 8.

**Comment by philwebb** [comment]
We're not really planning to add more features to the CLI. Most people seem to prefer the standard project approach.
