### ISSUE TITLE
management.metrics.tags doesn't work in Spring Boot 3.2.1 version

### ISSUE THREAD

**Issue by pavel-zeger** [spring-projects/spring-boot#38973]
Hello!

Following this closed issue I would like to report the bug with the `management.metrics.tags` used together with observation property `management.observations.key-values`: https://github.com/spring-projects/spring-boot/issues/38583.

Downgrading to the previous Spring Boot 3.1.6 version clearly shows the added metric tag when I check `/actuator/prometheus` endpoint. Upgrading to 3.2.1 eliminates any metrics tag (also default metrics like `process_uptime_seconds` and etc.) added via `management.metrics.tags` property.

I use both options: observations for controllers (with `ObservedAspect`) and custom tags for other metrics with `management.metrics.tags` property.

**Comment by wilkinsona** [comment]
If `management.metrics.tags` isn't working for you, I don't think it's related to the changes in #38583. That issue did not make any functional changes, it only removed the deprecation of the property. I also don't see the connection between default tags and default metrics such as `process_uptime_seconds`. The former should have no affect on whether or not the latter is present.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by pavel-zeger** [comment]
I'll try to reproduce it outside my production service and publish it here. Thank you for the fast response.

**Comment by pavel-zeger** [comment]
I'm closing this issue due a lack of time to provide this information. I'll investigate it again and will open a new issue if needed with a relevant data. I apologize for waste of your time. Regards.

**Comment by pavel-zeger** [comment]
I'm closing this issue due a lack of time to provide this information. I'll investigate it again and will open a new issue if needed with a relevant data. I apologize for waste of your time. Regards.
