### ISSUE TITLE
Devtools: Automatic Exclusion of Tests for Reloading

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#3900]
When I modify a test in Eclipse with devtools on the classpath the Boot application is restarted. This makes sense since Eclipse does not distinguish between a test classpath and a main classpath.

I wonder if it might make sense to improve Eclipse developer experience by automatically excluding `**/Tests?.class` from triggering a reload?

**Comment by philwebb** [comment]
Yes!
