### ISSUE TITLE
ServerProperties erroring due to server environment variables

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3903]
Originally raised in #3427, we need a simpler fix for 1.2.x whilst we consider what to do longer term. 

When running a Spring Boot application on a server that has any environment variable with a prefix of "SERVER_", the ServerProperties class will attempt to use it as a property and subsequently break due to the ignoreUnknownFields = false annotation...

**Comment by theonlyguills** [comment]
This is preventing us from deploying to Weblogic which sets SERVER_CLASS as part of the startup process.

Our current workaround:

```
public class WeblogicServerClassAwareServerProperties extends ServerProperties
{
	public void setClass(Object o)
	{
		;
	}
}
```

Then override the default in a `@Configuration` bean:
```
	@Bean
	public ServerProperties serverProperties()
	{
		return new WeblogicServerClassAwareServerProperties();
	}
```

Would be great to change the mapping to something less common.
