### ISSUE TITLE
An error occurred during the compilation of Spring Boot 3.2.2.

### ISSUE THREAD

**Issue by mengxiaohe** [spring-projects/spring-boot#39045]
The error occurred while executing the "publishToMavenLocal" task.

```
  A problem was found with the configuration of task ':spring-boot-project:spring-boot-actuator-autoconfigure:asciidoctor' (type 'AsciidoctorTask').
    - In plugin 'org.asciidoctor.gradle.jvm.AsciidoctorJBasePlugin' type 'org.asciidoctor.gradle.jvm.AsciidoctorTask' property 'generatedSnippets' specifies directory 'C:\workProject\spring-boot\spring-boot-project\spring-boot-actuator-autoconfigure\build\generated-snippets' which doesn't exist.
```

**Comment by scottfrederick** [comment]
@mengxiaohe Did you run `publishToMavenLocal` after running other tasks? Can you provide the full list of tasks that you ran before this one?

**Comment by mengxiaohe** [comment]
Before executing the "publishToMavenLocal" task, the "clean," "jar," "javadocJar," and "sourcesJar" tasks were executed. All of them were successful, except the "publishToMavenLocal" task, which failed.

**Comment by wilkinsona** [comment]
This problem happens when the build is executed with tests disabled (typically `-X test`). @mengxiaohe, the tests in `spring-boot-actuator-autoconfigure` must be executed as they produce part of the Actuator's documentation.
