### ISSUE TITLE
Jetty ConnectionLimit feature is not working

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-boot#39050]
Affects: 3.2.1

Jetty ConnectionLimit feature is introduced via 

`server.jetty.max-connections` in https://github.com/spring-projects/spring-boot/issues/35899

However, this ConnectionLimit is not working properly due to problem that introduced in this issue https://github.com/spring-projects/spring-boot/issues/30565

If Spring Boot decided to give first-class support for this, I think we need to find a proper solution.

As a shortcut from #30565, instead of supported prop, this works like a charm.   
```
@Bean
public JettyServerCustomizer connectorsConnectionLimit() {
    return server -> server.addBean(new ConnectionLimit(1, server.getConnectors()));
}
```

Thanks

**Comment by wilkinsona** [comment]
Thanks, @okohub. Closing in favor of #39052.
