### ISSUE TITLE
Separate server.port and management.server.port  actuator endpoint is not use management.server.port  

### ISSUE THREAD

**Issue by Dr-wgy** [spring-projects/spring-boot#39065]
spring-boot 2.6.15 
spring-webflux 

http://xxxx:serverPort/actuator/healthCheck  { "status": "UP" }

http://xxxx:managementServerPort/actuator/healthCheck  404 

Netty started on port serverPort
 Exposing 15 endpoint(s) beneath base path '/actuator'
 Netty started on port managementServerPort

**Comment by wilkinsona** [comment]
OSS support for Spring Boot 2.6.x [has ended](https://spring.io/projects/spring-boot#support). If you can provide a sample that reproduces the problem with Spring Boot 3.1.x or later we can re-open and take another look.
