### ISSUE TITLE
Support all Initializr parameters in Spring Boot CLI 

### ISSUE THREAD

**Issue by bcalmac** [spring-projects/spring-boot#3907]
`spring help init` displays the parameters available in the web version (start.spring.io):

    Parameters
    +-------------+------------------------------------------+------------------------------+
    | Id          | Description                              | Default value                |
    +-------------+------------------------------------------+------------------------------+
    | type        | project type                             | maven-project                |
    | bootVersion | spring boot version                      | 1.2.5.RELEASE                |
    | packaging   | project packaging                        | jar                          |
    | javaVersion | language level                           | 1.8                          |
    | language    | programming language                     | java                         |
    | groupId     | project coordinates                      | org.test                     |
    | artifactId  | project coordinates (infer archive name) | demo                         |
    | version     | project version                          | 0.0.1-SNAPSHOT               |
    | name        | project name (infer application name)    | demo                         |
    | description | project description                      | Demo project for Spring Boot |
    | packageName | root package                             | demo                         |
    +-------------+------------------------------------------+------------------------------+

However, just a subset of these are available as options to `spring init`:

    Option              Description
    ------              -----------
    -b, --boot-version  Spring Boot version to use (for
                          example '1.2.0.RELEASE')
    --build             The build system to use (for example
                          'maven' or 'gradle') (default: maven)
    -d, --dependencies  Comma separated list of dependencies
                          to include in the generated project
    -f, --force         Force overwrite of existing files
    --format            The format of the generated content
                          (for example 'build' for a build
                          file, 'project' for a project
                          archive) (default: project)
    -j, --java-version  Java version to use (for example '1.8')
    -l, --list          List the capabilities of the service.
                          Use it to discover the dependencies
                          and the types that are available
    -p, --packaging     Packaging type to use (for example
                          'jar')
    -t, --type          The project type to use. Not normally
                          needed if you use --build and/or --
                          format. Check the capabilities of
                          the service (--list) for more details
    --target            URL of the service to use (default:
                          https://start.spring.io)
    -x, --extract       Extract the project archive. Inferred
                          if a location is specified without
                          an extension

It would be nice to support the same set of parameters as the web version. The following are currently missing: language, groupId, artifactId, version, name, description.

I could work on this if you think it's something worth pursuing.

**Comment by snicoll** [comment]
Duplicates #3716 #2793

Thanks for the offer but we already fixed that. You could give `1.3.0.M5` a try.
