### ISSUE TITLE
Polish SpringApplication to avoid dead code after calls to handleRunFailure

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#39086]
As reported in #38951, there's some dead code after calls to `handleRunFailure`. We think it might be better to have `handleRunFailure` return the exception to be thrown and then have the caller throw it.

**Comment by BenchmarkingBuffalo** [comment]
Hi @wilkinsona,
I would like to work on this issue.
If you want, you can assign it to me and I will open a PR for it.

**Comment by philwebb** [comment]
Closing in favor of PR #39107. Thanks @BenchmarkingBuffalo!
