### ISSUE TITLE
Improve "Sanitize Sensitive Values" section in reference documentation

### ISSUE THREAD

**Issue by filpano** [spring-projects/spring-boot#39094]
In Spring Boot 3, the Actuator security settings have changed somewhat, specifically with regard to the sanitization of potentially sensitive properties. Part of the reasoning for this (role-based vs. key-based) is given in https://github.com/spring-projects/spring-boot/issues/32156, which I do not question as being an improvement.

We currently use [Spring Boot Admin](https://github.com/codecentric/spring-boot-admin) and require an SSO administration login to see the UI which is populated by a service role with the `monitoring` role. This and other correctly configured monitoring tools now, per default, would show sensitive fields.

*Specifically* given a previous config of 
```
management.endpoint.env.show-values=WHEN_AUTHORIZED
```
and a request matcher similar to the following:

```
httpSecurity. // ...
        .and()
        .authorizeHttpRequests()
        .requestMatchers("/actuator/**").hasAnyRole("MONITORING")
        .and() // ...
```

which would semantically map to the new:

```
management.endpoint.env.show-values=WHEN_AUTHORIZED
management.endpoint.env.roles=MONITORING
```

...would exhibit behaviour that is a drastic departure from the previous one w.r.t. sensitive information.

This is great for development - no doubt, but it was a bit of a shock to see it in action without an explicit and far more prominent warning that there is no default sanitizing function.

Since Spring Boot itself has a very opinionated approach to configuration, why do common-sense approaches allow us to use proper security practices (`WHEN_AUTHORIZED` with a specific system role) and still have potentially unsafe behaviour? The fact that a developer may need to be able to check a runtime configuration property does not immediately imply that they need access to sensitive values, with a sensible-looking configuration, per default.

IMO it would be much better to *require* a sanitizing function when `WHEN_AUTHORIZED` is used, and perhaps - at the very least, provide a `NoOpSanitizingFunction` that logs a suppressable warning. No one likes a silent breaking change.

**Comment by filpano** [comment]
As a side point, in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-endpoints-sanitization), the options for the `show-value` property are given as follows:

> NEVER - All values are sanitized (the default).
>
> ALWAYS - All values are present in the output **(sanitizing functions will apply)**.
> 
> WHEN_AUTHORIZED - Values are present in the output only if a user is authorized **(sanitizing functions will apply)**.

(emphasis is mine) 

In the [current docs](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.sanitization), the options are given as follows:

> ALWAYS - all values are shown in their **unsanitized** form to all users
>
> NEVER - all values are always sanitized (that is replaced by ******)
>
> WHEN_AUTHORIZED - all values are shown in their **unsanitized** form to authorized users

(emphasis mine) including the following note:

> When show-values is set to ALWAYS or WHEN_AUTHORIZED any sanitization applied by a [SanitizingFunction](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.actuator.customizing-sanitization) will still be applied.

The migraion guide is probably the one that most people read when upgrading to Spring Boot 3, and IMO it *strongly* applies that a sensible default, as previously, is being applied out of the box.

**Comment by filpano** [comment]
For anybody looking for an example of how to get the previous behaviour back, see the comment from @welsh here: https://github.com/spring-projects/spring-boot/issues/32156#issuecomment-1470804473.

**Comment by wilkinsona** [comment]
I've had updated the migration guide to replace "sanitizing functions will apply" with "any user-defined sanitizing functions will still apply".

> Specifically given a previous config of
> ```
> management.endpoint.env.show-values=WHEN_AUTHORIZED
> ```

What do you mean by "previous config" here? `management.endpoint.env.show-values` is new in 3.0.

**Comment by filpano** [comment]
> I've had updated the migration guide to replace "sanitizing functions will apply" with "any user-defined sanitizing functions will still apply".

Great, thank you very much. I think this will help avoid a lot of misunderstandings.

> What do you mean by "previous config" here? `management.endpoint.env.show-values` is new in 3.0.

Sorry, you are correct. I was referring to the previous Health-only [configuration](https://docs.spring.io/spring-boot/docs/2.7.18/reference/htmlsingle/#actuator.endpoints.health), which used the same enum values as those of new `Show` enum. 

I suppose this, in tandem with keys being sanitized previously, is where most of the confusion stems from for me.

**Comment by philwebb** [comment]
@filpano I think our reference documentation could also be improved. I've repurposed this issue to do that.

**Comment by datagitlies** [comment]
@philwebb beyond the documentation updates was any consideration given to provide a default `SanitizingFunction` or at least a reference implementation similar to the [`Sanitizer`](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Sanitizer.java) in `spring-boot` 2.7 that accepts a list of `keysToSanitize`?  I know several engineers that are literally copying the [`Sanitizer`](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Sanitizer.java) logic into their codebase after migrating to `spring-boot` 3.X which would indicate there is a need for this.

**Comment by wilkinsona** [comment]
@datagitlies please see https://github.com/spring-projects/spring-boot/issues/33448.

**Comment by datagitlies** [comment]
@wilkinsona I still believe a better example `SanitizingFunction` should be "provided" (either in `spring-boot-actuator` or in documentation / a code example or sample ... basically somewhere!)  Similar to how it was handled for the [`InMemoryHttpExchangeRepository`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/web/exchanges/InMemoryHttpExchangeRepository.java) where it's not enabled by default, but you can easily provide it (if desired). It avoids engineers having to <s>copy</s> write the code.

**Comment by wilkinsona** [comment]
As explained in the issue to which I linked, we don't feel that we can do that:

> We found it was impossible to write a SanitizingFunction that would consistently and correctly work against everything

We think it's safer if users provide their own, limited to their specific needs.

**Comment by datagitlies** [comment]
My expectation is not that `spring-boot-actuator` would or could provide a `SanitizingFunction` that will _"correctly work against everything"_ ... I just want reasonable defaults.  I don't think it's out of the question that a property called `password` could be sanitized by default -IF- I desire to enable a "default" `SanitizingFunction` provided by `spring-boot-actuator` (the one that doesn't exist but I'm proposing).  The fact that anyone would have to spend time writing (or finding and copying) logic to sanitize that `password` property is what's at the core of this issue.  Or am I missing something non-obvious here?  Are there cases where the `spring-boot` 2.7 [Sanitizer](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Sanitizer.java) didn't work for something simple like a property called `password`?

**Comment by philwebb** [comment]
@datagitlies I think I see what you're getting at. I've raised #39243 so we can consider our options.
