### ISSUE TITLE
jdk.tracePinnedThreads make the springboot program start failed.

### ISSUE THREAD

**Issue by walkertest** [spring-projects/spring-boot#39112]
* See the stackoverflow question:https://stackoverflow.com/questions/77779953/spring-boot-virtual-threads-djdk-tracepinnedthreads-full-causes-tasks-to-hang

* I encouterd the same question,  but don't know why.

**Comment by mhalbritter** [comment]
Please don't cross-post. Let's see what StackOverflow comes up with.
