### ISSUE TITLE
Add configuration property for enabling micrometer observation annotations support

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#39128]
As of #37626, Spring Boot 3.2 auto-configures AspectJ handlers to support observation annotations like `@Timed` and `@Counted` with `MetricsAspectsAutoConfiguration`. Spring Boot 3.3 will expand that for tracing annotations in `MicrometerTracingAutoConfiguration`.

Right now those auto-configurations are conditional on the presence of Micrometer and AspectJ, but we've found that those aspects are quite broadly applied and can significant startup time difference. While this is a fine feature to support, we should restrict a bit its application to ensure that it's only applied when developers choose to. The Aspectj dependency can come from many use cases and is not a good indicator for applications opting-in for this feature.

We should add a `management.observations.annotations.enabled` configuration property and introduce it with a default `false` value. While this changes behavior, we're still early in the 3.2.x generation and this is a impact big enough that we're considering this a bug. We'll make this noteworthy in the release notes.

**Comment by DRoppelt** [comment]
> We'll make this noteworthy in the release notes.
It seems like that might have been forgotten in the release notes? I like this change but have not perceived it as a noteworthy change in the release notes/blog. It does show up under "bugfixes". https://github.com/spring-projects/spring-boot/releases/tag/v3.2.2

I think the notes should be updated to highlight that change better?

**Comment by wilkinsona** [comment]
Thanks, @DRoppelt. Looks like we missed this during the release. I've added a Noteworthy Changes section to the top of the [release notes for 3.2.2](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.2).

**Comment by DarkAtra** [comment]
hey @wilkinsona, just noticed that the release notes are incorrect. It says the property is `management.observations.annotations.enabled` but the actual name seems to be `micrometer.observations.annotations.enabled`.

**Comment by philwebb** [comment]
Thanks @DarkAtra, I've edited the notes.

**Comment by wilkinsona** [comment]
I think that may be a mistake in the code as we have [`ObservationProperties`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/observation/ObservationProperties.java) with a `management.observations` prefix.

**Comment by bclozel** [comment]
My mistake, I've created #39600 to fix that.
