### ISSUE TITLE
Unicode error after switch from 1.3.0.M4 to 1.3.0.M5

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#3914]
Hi all,

Since switching my projects from spring-boot `1.3.0.M4` to `1.3.0.M5` I get malformed uploaded unicode text. I've setup an example project to highlight the problem:
https://github.com/timtebeek/characterencodingfilter

[I've got a controller that expects the following text](https://github.com/timtebeek/characterencodingfilter/blob/master/src/main/java/com/github/timtebeek/characterencodingfilter/Uploader.java) : `"Copyright © example"`

[And a JUnit test that uploads that text](https://github.com/timtebeek/characterencodingfilter/blob/master/src/test/java/com/github/timtebeek/characterencodingfilter/UploaderTest.java), but which results in: `"Copyright Â© example"`

After the switch the JUnit test breaks:
https://travis-ci.org/timtebeek/characterencodingfilter/builds/79112950
https://github.com/timtebeek/characterencodingfilter/compare/526724206daa...17706daa5dcc

Could you look into this and tell me what I can do to resolve this?

**Comment by snicoll** [comment]
Duplicates #3912 ?

**Comment by timtebeek** [comment]
Yup it does! Wasn't yet an issue for it when I started debugging.. :(

**Comment by timtebeek** [comment]
Hope my example is of any use regardless.. Feel free to close this issue and/or copy over any details.

**Comment by snicoll** [comment]
It is, yeah. We'll tackle the problem in #3912 and we'll use your sample as well. Thanks!
