### ISSUE TITLE
Provide shell completion for spring init

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3916]
I'd really like to be able to use bash completion with spring init. I'd like suggestions for each of the supported options and, ideally, suggestions for those options' values. The latter would require communication with `start.spring.io` to determine possible values and would probably require some caching of the metadata to achieve reasonable performance.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
