### ISSUE TITLE
How to setting multiple server.servlet-path?

### ISSUE THREAD

**Issue by edwardlau** [spring-projects/spring-boot#3920]
I set server.servlet-path=*.do,*.json not use,must only one

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
