### ISSUE TITLE
Huge startup time difference between servers and local machine

### ISSUE THREAD

**Issue by lazee** [spring-projects/spring-boot#3921]
Hi,

@philwebb : I saw you somewhere else asked for real projects that are having issues with the startup time.

At the moment we are having issues with all of our spring boot apps in our test and production environments. The issue is that all of our apps start in about 4-5 seconds locally on our developer machines. But in production it takes 18-25 seconds. And we are really not sure what causes this.

From the log lines below it seems like it is the loading of the web application context that takes most of the time. 

Do you have any tip on how to debug this. I'm going to profile this deeper. But I first wanted to ask you for general tips on how to approach these issues. And secondly ask you if you are interested in looking into one of the projects?

I have tried following general recommendations online in other threads without figuring out the huge difference between servers and dev machines.

We are running on Spring Boot 1.2.5

```
1,445 [INFO ] [      main][][org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext][prepareRefresh][510] - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@afcbd46: startup date [Mon Sep 07 13:08:51 CEST 2015]; root of context hierarchy
2015-09-07 13:08:59,333 [INFO ] [      main][][org.springframework.web.context.ContextLoader][prepareEmbeddedWebApplicationContext][268] - Root WebApplicationContext: initialization completed in 7892 ms
2015-09-07 13:09:05,690 [INFO ] [      main][][org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration][configure][170]

**Comment by snicoll** [comment]
Hey, 

Please define "production environment" first.

**Comment by wilkinsona** [comment]
My first guess would be that this delay is Tomcat initialising a `SecureRandom` for session id generation. If the test and production servers are low on entropy, this will take a while as the default entropy source blocks until more is available.

**Comment by lazee** [comment]
@wilkinsona We are running on the embedded Jetty servers 9.2.10.v20150310 at the moment.

Another observation is that for DropWizard apps the startup time (also running on the same Jetty version on the same servers. Not in the same vm of course) are the same on the same servers as on developer machines. 

@snicoll We have a lot of vms running on these servers. So I guess they are fighting about resources. But the startup time is constant. Its linux servers firing up Spring boot as standard java processes with embedded jettys.

I can set up a github project with the bundle/source if that would help.

**Comment by lazee** [comment]
Another observation is that the startup time dropped by 3 seconds when I removed all the jsp and websocket packages imported by the Jetty setup. My guess is that it is caused by class scanning of some sort. But thats just a guess. Trying to get a profiler running here now.

**Comment by wilkinsona** [comment]
I think we'll either need some data from a profiler or a way to recreate the problem to make any progress on this one

**Comment by lazee** [comment]
@wilkinsona I will try to get some profiler data for you soon.

Just did a full debug dump .It took 67 seconds to start. But from the data i see several of these...

```
2015-09-08 11:48:37,934 [DEBUG] [      main][][org.springframework.beans.factory.support.DefaultListableBeanFactory][doCreateBean][523] - Eagerly caching bean 'config' to allow for resolving potential circular references
2015-09-08 11:48:44,849 [DEBUG] [      main][][org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor][postProcessAfterInitialization][235] - No @Scheduled annotations found on bean class: class org.springframework.data.rest.core.config.RepositoryRestConfiguration
20
```

"Eagerly caching..." seems to be involved everywhere there is a significant time used between to log lines.

Not sure if this really tells me anything...Back to the profiler...

**Comment by wilkinsona** [comment]
@lazee Any joy with the profiler?

**Comment by wilkinsona** [comment]
Closing due to lack of response. If this is still a problem, please let us know and we can re-open the issue.
