### ISSUE TITLE
Upgrade Prometheus' simpleclient 0.16.0 to prometheus-metrics-core 1.0.0+

### ISSUE THREAD

**Issue by DieBauer** [spring-projects/spring-boot#39235]
The Prometheus java library has released [version 1.x](https://grafana.com/blog/2023/09/27/introducing-the-prometheus-java-client-1.0.0/). In this release they changed Maven artifactnames from `simpleclient_*` to `prometheus-metrics-*`

This means that the dependency update does not find versions newer than `0.16.0` for [the simpleclient dependencies](
https://github.com/spring-projects/spring-boot/blob/686fe84a72f13899a8e432735c0015a997ae3293/spring-boot-project/spring-boot-dependencies/build.gradle#L1138-L1144). 

The first release note mentions this https://github.com/prometheus/client_java/releases/tag/v1.0.0-alpha-1

As a migration strategy they have included the simpleclient modules in the new artifact as outlined here: https://github.com/prometheus/client_java/releases/tag/v1.0.0

Can spring-boot move to this version of the prometheus java library to keep up-to-date?

**Comment by wilkinsona** [comment]
Unfortunately, I was overly optimistic in assigning this to 3.3.x.

Of Simpleclient's modules, we only interact with `io.prometheus:simpleclient_pushgateway`. The release notes for 1.0.0 of the new Java client state the following:

> Not all simpleclient modules from 0.16.0 are included in the initial 1.0.0 release. Over the next couple of weeks we will work on porting the remaining modules, starting with pushgateway and the Servlet filter.

That was back in September but I don't think the situation has changed. The link for Java on https://prometheus.io/docs/instrumenting/pushing/ currently 404s so it looks like this is still a work in progress and we'll need to stick with 0.16.0 for now.

In addition to new Maven coordinates, the new client also uses new package names so it may be possible to use the new alongside the old in the same app but that would require [changes in Micrometer](https://github.com/micrometer-metrics/micrometer/issues/4406).

I don't think there's anything actionable here at the moment so I'm going to close this one. We'll upgrade to 1.x in due course but that will only be once Micrometer has upgraded.
