### ISSUE TITLE
bootBuildImage runs forever when a custom image name is used and the tag contains an illegal character

### ISSUE THREAD

**Issue by ilozano2** [spring-projects/spring-boot#39246]
**Spring Boot Version: 3.2.1**

### Issue

Given a image reference `<hostname>/<library>/<artifact>:1.0.0+1.2.3` 
When the length of <library> or <artifact> is long, the method `ImageReference.of(...)` freezes

Tests: https://github.com/spring-projects/spring-boot/commit/30c4bd11e2460a28ee4d381c7b58fab837958439

Related: https://github.com/spring-projects/spring-boot/issues/23115 

### TL;DR

Internally, the Regex.PATH generated is `^[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:[\/][a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?$` which will report a [Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html) (you can see it in regex101 for example).

**Comment by wilkinsona** [comment]
See also https://github.com/spring-projects/spring-boot/issues/35657.

**Comment by wilkinsona** [comment]
Thanks, @ilozano2. Is the plan for https://github.com/pivotal-cf/vmware-app-analyzer/issues/240 to include a `+` character in the image's tag? AIUI, `+` isn't a permitted character in a tag and any fix for this issue would result in such an image reference being rejected.

**Comment by ilozano2** [comment]
@wilkinsona In fact, it isn't. Docker images don't support that character in the TAG. 

We are following a different format. No rush here then, but it could be nice to fail without freezing.
Thanks!

**Comment by scottfrederick** [comment]
Closing in favor of #39617
