### ISSUE TITLE
Logback log level is not propagated to java.util.logging

### ISSUE THREAD

**Issue by trecloux** [spring-projects/spring-boot#3924]
Default setup for spring boot is to use SLF4J and Logback.
The bridge between SLF4J and `java.util.logging` is installed, so `java.util.logging` logs are forwarded to SLF4J

Unfortunately, the log level configuration through Logback is not propagated to `java.util.logging` loggers.

I discovered this issue when trying to see debug logs for tomcat's jdbc connection pool. 

I'll submit a pull request to fix this.

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA?
