### ISSUE TITLE
May I ask why version 3.2 does not support undertow virtual thread configuration

### ISSUE THREAD

**Issue by JavaLionLi** [spring-projects/spring-boot#39256]

**Comment by JavaLionLi** [comment]
I adapted according to the submission records of version 3.3 and did not find any issues

**Comment by bclozel** [comment]
Duplicates #38819

**Comment by bclozel** [comment]
We just didn't get to it in time for 3.2 and got it done for 3.3.

**Comment by mhalbritter** [comment]
> I just want to know why there is no support for 3.2, but instead support was provided in 3.3. Is there any downside

We don't add enhancements in maintenance releases of Spring Boot. As 3.2.0 didn't have that feature, new enhancements will go into 3.3.

If you need this feature in 3.2, you can add this bean yourself:

```java
@Bean
public UndertowDeploymentInfoCustomizer undertowDeploymentInfoCustomizer() {
 return deploymentInfo -> deploymentInfo.setExecutor(Executors.newVirtualThreadPerTaskExecutor());
}
```
