### ISSUE TITLE
NestedJarFile constructor javadoc is incorrect

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#39252]
See https://github.com/spring-projects/spring-boot/issues/37668#issuecomment-1900640077

**Comment by philwebb** [comment]
Closing in favor of PR #39285. Thanks @PiyalAhmed!

**Comment by PiyalAhmed** [comment]
> Closing in favor of PR #39285. Thanks @PiyalAhmed!

Thanks @philwebb, you made my day!
