### ISSUE TITLE
Migrate away from using --registry-mirror with Docker CI

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#39267]
The `--registry-mirror` we use isn't that stable and it would be better to use specific image names instead. We probably need to add something like this to `testcontainers.properties`:

```
ryuk.container.image = harbor-repo.vmware.com/dockerhub-proxy-cache/testcontainers/ryuk:0.4.0
```

And also use something like https://github.com/spring-projects/spring-data-jpa/blob/699d3a2e57e39dc50df67337dfe696de93a3dd4a/spring-data-jpa/src/test/java/org/springframework/data/jpa/support/ProxyImageNameSubstitutor.java

**Comment by philwebb** [comment]
We might also want to update CI to somehow ban hub.docker.io so we know that we've caught everything.

**Comment by mhalbritter** [comment]
We can get rid of this after all releases are done from GitHub actions.
