### ISSUE TITLE
bootTestRun throws error when you have multiple @DynamicPropertySources in Spring Boot 3.2.2 -- works fine in 3.2.1

### ISSUE THREAD

**Issue by zsait-clearstreet** [spring-projects/spring-boot#39282]
With Spring Boot 3.2.2, if you have multiple classes with `@DynamicPropertySource `it throws the below error. This works fine with 3.2.1
`
The bean 'org.springframework.boot.testcontainers.properties.TestcontainersPropertySource$EventPublisherRegistrar' could not be registered. A bean with that name has already been defined and overriding is disabled.`

To replicate, see this fork of the testcontainers-quickstart with spring version upgraded to 3.2.2 and adding multiple classes with @DynamicPropertySource
https://github.com/zsait-clearstreet/testcontainers-java-spring-boot-quickstart

The commit diff
https://github.com/testcontainers/testcontainers-java-spring-boot-quickstart/compare/main...zsait-clearstreet:testcontainers-java-spring-boot-quickstart:main

Try running the 'bootTestRun' task you will see

```

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'org.springframework.boot.testcontainers.properties.TestcontainersPropertySource$EventPublisherRegistrar' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
````

Works fine if you downgrade to version Spring boot version 3.2.1

**Comment by Tish17** [comment]
@philwebb Hello! I signed the "Contributor License Agreement" but when I try to push my own branch I get 403 error, why? I want to push my branch to create a pull request with bug fix

**Comment by scottfrederick** [comment]
@Tish17 In order to submit a pull request, you first need to fork the GitHub repository and push the changes to your own fork. See the [GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for more information.

**Comment by Tish17** [comment]
@scottfrederick I have created a pull request, please let me know what should I do next?

**Comment by wilkinsona** [comment]
Nothing to do now, thanks @Tish17, other than waiting for the PR to be reviewed. We'll get to that as soon as we can. Thanks for your patience in the meantime.

**Comment by wilkinsona** [comment]
Closing in favor of #39297.
