### ISSUE TITLE
H2 console .h2.server.properties file not taken into account when app is started Unix style

### ISSUE THREAD

**Issue by nodje** [spring-projects/spring-boot#3929]
```.h2.server.properties``` is not taken into account when the spring-boot app is started Unix style: ```app.war``` or ```app.war start```.

The problem doesn't occur when the app is started with ```java -jar app.war``` or through maven ```mvn spring-boot:run```

As a way to reproduce the problem, I'm looking at the property  ```webAllowOthers=true```. It is not taken into account and as such doesn't allow access from any external IP.

The ```.h2.server.properties``` I use is located in the standard maven ```src/main/resources``` folder.

If it's a bug, I guess it concerns at least some others resources.

I'm using 1.3.0.M4

**Comment by snicoll** [comment]
H2 is reading that file, not us. 

> The settings of the H2 Console are stored in a configuration file called .h2.server.properties in you user home directory. For Windows installations, the user home directory is usually C:\Documents and Settings\[username] or C:\Users\[username]. The configuration file contains the settings of the application and is automatically created when the H2 Console is first started. 

I am confused with the `src/main/resources` part. In any case, since you are reporting it here, what makes you think it's a Spring Boot issue?

**Comment by philwebb** [comment]
This could also be related to the fact that the Unix style launch `./app.war` when run as `root` assumes the identity of the file owner (see [this line of the script](https://github.com/spring-projects/spring-boot/blob/v1.3.0.M5/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L97)). Is it possible that you have a `.h2.server.properties` file in your home dir but not that of the production run user?

**Comment by nodje** [comment]
I shouldn't have introduced H2 in the title. It just illustrates that there's probably an issue with reading resources when apps are started Unix style.
Here's the scenario that led me to think there's an issue with Unix style launch:

I have ```src/main/resources/.h2.server.properties``` packaged into a WAR app (so it becomes available in WEB-INF/classes after packaging). It is taken into account when I ```mvn spring-boot:run``` as I can open the /console and it takes into account the settings from .h2 file, and particularly ```webAllowOthers=false``` which prevents me to connect to /console from any external IP. 
When I change ```webAllowOthers=true``` in the H2 file, then boot with ```mvn spring-boot:run```, I can now access the /console from an external IP.
I can then deploy, launch the app Unix style and get a ```Sorry, remote connections ('webAllowOthers') are disabled on this server.``` Uh, odd. Get back to the local version, get the same behavior with Unix style launch.
Double check with ```java -jar app.war``` launch and it works.

I conclude that somehow the code triggered by the access to /console can't find the ```.h2.server/properties``` that would tell it to allow external IP access.

As for the script line 
```
# Determine the user to run as if we are root
[[ $(id -u) == "0" ]] && run_user=$(ls -ld "$jarfile" | awk '{print $3}')
``` 
I'm not fluent enough in bash to understand exactly what it does. I don't run the script as root but as a dedicated user. And in my specific case, due to a coincidence, ```run_user``` happens to equal to the real Unix user name under which the script is launched!
In any case the H2 property file is included in the app WAR.

**Comment by philwebb** [comment]
I don't think that `.h2.server.properties` can be loaded from `src/main/resources`. As @snicoll mentioned above the file needs to be in the user home directory. The `Constants` class in the H2 codebase also seems to [suggest this](https://github.com/h2database/h2database/blob/version-1.4.188/h2/src/main/org/h2/engine/Constants.java#L394).

Can you confirm that you're trying `java -jar app.war` and `./app.war` on the same machine? Can you also double check that you don't have any `.h2.server.properties` file when you run `ls -ah ~`.

The launcher script should start the application using `java -jar` so I'm really confused why there would be any difference.

You could also try `DEBUG=true ./app.war` to see if that provides any clues.

**Comment by nodje** [comment]
Good catch, I had a local ```.h2.server.properties```.

As a matter of fact ```.h2.server.properties``` can be loaded from the classpath, it can read its settings from it when the app is run with ```mvn spring-boot:run```. 
But I still don't get I still don't get why H2 can get a hold of it when run maven style and can't when run with ```java -jar app.war``` but at least it's a consistent behavior that I can look into.

Sorry for the confusion and thank you very much for the time spent on this.

**Comment by kane0409** [comment]
Hi, I got the same problem as yours, but after I still couldn't get how to resolve it. I don't understand that you said 'you had a local '.h2.server.properties'. Do you mean it is the file that in the C:\Users[username]? And should I put the .h2 file in the src/main/resources? Thank you.

**Comment by snicoll** [comment]
@kane0409 this issue is closed and marked as invalid. This is more an H2 question than a Spring Boot question anyway (if you're really having the same problem). Please ask on stackoverflow.
