### ISSUE TITLE
ThreadLocalAccessor implementation for MDC

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-boot#39299]
To support MDC propagation between threadlocal and reactor operation chain, e.g. using `WebClient` in Spring MVC, I use a custom `ThreadLocalAccessor`(from [micrometer context-propagation)](https://github.com/micrometer-metrics/context-propagation) implementation.  

It would be more useful if it is provided by Spring Boot and auto-configures.

Implementation sample from [this gist](https://gist.github.com/chemicL/0e0d8e95e28414f0ecb769a5b8ca326e#file-testmdc-java-L32-L55) by @chemicL

```java
    static class MdcAccessor implements ThreadLocalAccessor<Map<String, String>> {

        static final String KEY = "mdc";

        @Override
        public Object key() {
            return KEY;
        }

        @Override
        public Map<String, String> getValue() {
            return MDC.getCopyOfContextMap();
        }

        @Override
        public void setValue(Map<String, String> value) {
            MDC.setContextMap(value);
        }

        @Override
        public void reset() {
            MDC.clear();
        }
    }
```

**Comment by rstoyanchev** [comment]
I can also see this potentially in the context-propagation library itself in a support package with commonly used `ThreadLocalAccessor` and/or `ContextAccessor` implementations that don't have other obvious places to exist.

**Comment by marcingrzejszczak** [comment]
@chemicL WDYT about adding a SLF4j module in context-propagation library?

**Comment by chemicL** [comment]
Yep, created: https://github.com/micrometer-metrics/context-propagation/issues/191

**Comment by jonatan-ivanov** [comment]
I think this issue can be closed in favor of the one in context-propagation (https://github.com/micrometer-metrics/context-propagation/issues/191), we can open an new issue/PR once auto-configuration is needed.

**Comment by ttddyy** [comment]
closing in favor of https://github.com/micrometer-metrics/context-propagation/issues/191
