### ISSUE TITLE
Does launch script support java agent? 

### ISSUE THREAD

**Issue by mrajibkhan** [spring-projects/spring-boot#3930]
Hi,

We have been trying to start spring boot application (as executable jar) from /etc/init.d with new relic. Couldn't find a way to use javaagents with the builtin script. We ended up adding customized script using mvn repackage.

Wondering if current script supports this option! If not - is there any plan to add this feature in future?

**Comment by philwebb** [comment]
Did you try adding `JAVA_OPTS` to a `.conf` file next to your jar? Looking at the init script I think that should work (although it looks like we've missed that [from the docs](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#deployment-script-customization))

**Comment by mrajibkhan** [comment]
We tried by setting the env variable. But $JAVA_OPTS is used after -jar which doesn't work. So, used an new variable AGENT_CMD as a work around:  
command="$javaexe $AGENT_CMD -jar -Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS $jarfile $RUN_ARGS $@"

**Comment by philwebb** [comment]
Thanks for the feedback. I think it should be safe for us to put `$JAVA_OPTS` before the `-jar` so we'll look at that for RC1.

**Comment by n0mer** [comment]
@mrajibkhan this worked for me
```groovy
applicationDefaultJvmArgs = [
//        "-Djava.security.egd=file:/dev/./urandom",
        "-Dspring.output.ansi.enabled=always",
//        "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n",
        "-Dnewrelic.config.file=${newRelicPath}/newrelic.yml",
        "-javaagent:${newRelicPath}/newrelic-agent-${newrelicVersion}.jar"
]
```
