### ISSUE TITLE
Configure suitable TaskExecutor for WebSocket when virtual threads are enabled

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#39314]
A recent issue in Spring Framework (https://github.com/spring-projects/spring-framework/issues/32081) made us aware that we overlooked websocket broker support for virtual threads. 

Now that `ChannelRegistration` allows a plain `TaskExecutor` to be specified via the new `executor` method, it would be nice to configure it when virtual threads are enabled.

**Comment by BenchmarkingBuffalo** [comment]
HI @wilkinsona,
I can work on this, once spring 6.1.4 is out.
You can assign it to me, if you like.

**Comment by mhalbritter** [comment]
Superseded by #39611.
