### ISSUE TITLE
Switch to OpenFeign fork of QueryDSL

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#39316]
The original QueryDSL's last release was July 2021, and last commit was October 2022.
The OpenFeign project have forked it and have made an effort to update it.

https://github.com/OpenFeign/querydsl

Spring Boot should consider moving to this new fork.
Version 6.0 would match the other dependencies (Hibernate, in particular) used by Spring Boot 3.2.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This isn't a change that Boot can make on its own as we need to follow Spring Data JPA's lead. Please make the suggestion in [their issue tracker](https://github.com/spring-projects/spring-data-jpa/issues) and we can take things from there.
