### ISSUE TITLE
Can I use Jetty 9.4 with Spring Boot 3.2.0 ?

### ISSUE THREAD

**Issue by rodiamix2841** [spring-projects/spring-boot#39315]

**Comment by bclozel** [comment]
No, [Spring Framework 6.0 requires Jetty 11](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#web-applications-1). If you're using direct Jetty integrations (like the reactive client), this might require Jetty 12.
