### ISSUE TITLE
[Suggestion] Support SpEL in configuration file

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-boot#39322]
Can we have SpEL in configuration file 

Let me give one use case as an example
```
spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=root
spring.datasource.password=<encrypted value>

```
In this example, my properties define an encrypted password.  To decrypt it, i need to go thru the cumbersome of having to create manually a DataSource bean.   If spring allows SpEL in configuration, such cumbersome activity can be bypass  , by doing something like

```
spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=root
spring.datasource.password=#{T(xx.com.Decryptor).decryptPassword('<encrypted value>')}}
```

Now no need to go thru the hassle of programmatically creating a datasource bean.
I know someone would suggest a third party library (such as jasypt) to deal with my aforementioned scenario.  But the above is just only an example.  It might not be related to decrypting an encrypted value.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but, as with https://github.com/spring-projects/spring-boot/issues/7059, we think that it would add too much complexity to support SpEL in configuration files.
