### ISSUE TITLE
R2DBC Core DatabaseClient.sql replacing column 'key' to '[*]key'

### ISSUE THREAD

**Issue by corebase2023** [spring-projects/spring-boot#39325]
Affects: 3.2.0

r2dbc.core.databaseclient.sql  replace query that have column name 'key' to '[*]key' and this causes error in the query execution.

```
String select = "SELECT key FROM table_a";
Mono<Map<String, Object>> first = db.sql("SELECT key FROM table_a");
```

The executed query will be "SELECT [*]key FROM table_a". This will cause error in the application as the query failed. 

Anyone having this issue in their project? Any workaround?

**Comment by bclozel** [comment]
If you believe this is a bug, you should [raise this against the r2dbc project](https://github.com/r2dbc) as I don't see anything related to Spring Boot here. Additionally, you can [start with a question on StackOverflow](https://stackoverflow.com/questions/tagged/r2dbc) to get some help from the community first.
