### ISSUE TITLE
Spring Boot 3.2 - Facing issues with trace-id and span-id not being printed in logs when spring-cloud-loadbalancer is used.

### ISSUE THREAD

**Issue by curfew117** [spring-projects/spring-boot#39327]
I recently migrated to Spring Boot 3.2 and I'm having issues with trace-id and span-id not being printed in logs when a `RestTemplate` bean is annotated with `@LoadBalanced`.

The pic attached below is when a `RestTemplate` bean is created without the `@LoadBalanced` annotation
and trace-id and span-id is included
![image](https://github.com/spring-projects/spring-boot/assets/99183897/d78782b2-b83d-46af-9c1f-51a0f785be1b)

And the below pic when a `RestTemplate` is created with the `@LoadBalanced` annotation and trace-id and span-id is
empty
![image](https://github.com/spring-projects/spring-boot/assets/99183897/a7650020-4449-44e3-97b4-699449f028ef)

The log being printed above is a part of a `@GetMapping` whose controller has no dependency with the created `RestTemplate`.

I've attached the sample project I used to replicate the issue.
[demo.zip](https://github.com/spring-projects/spring-boot/files/14086401/demo.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. Given that this works without `@LoadBalanced`, please report this to the Spring Cloud team who maintain the load balancing functionality.
