### ISSUE TITLE
Spring boot plugin issue using gradle cache

### ISSUE THREAD

**Issue by alexisgayte** [spring-projects/spring-boot#39326]
Running Spring boot plugin with gradle 8.5 generate :

Configuration cache problems found in this build.
 2 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:bootJar` of type `org.springframework.boot.gradle.tasks.bundling.BootJar`: execution of task ':bootJar' caused invocation of 'Task.project' in other task at execution time which is unsupported.
See https://docs.gradle.org/8.5/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
Execution of task ':bootJar' caused invocation of 'Task.project' by task ':resolveMainClassName' at execution time which is unsupported.

**Comment by bclozel** [comment]
What's the Spring Boot version? What's the Gradle command to use to reproduce this?

**Comment by alexisgayte** [comment]
3.2.2 for spring boot.
gradle 8.5.0


.gradle/gradle.properties

  org.gradle.caching=true
  org.gradle.jvmargs=-Xmx2048M
  org.gradle.configuration-cache=true

gradle command :
./gradlew clean build publish --info

Tasks to be executed: [task ':clean', task ':bootBuildInfo', task ':compileJava', task ':generateGitProperties', task ':processResources', task ':classes', task ':resolveMainClassName', task ':bootJar', ...

**Comment by wilkinsona** [comment]
Unfortunately, that doesn't reproduce the problem. For example `publish` will fail in a default project as there's no such task. I can also see `generatedGitProperties` running that you haven't shown the setup for. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.
