### ISSUE TITLE
Actuator attributes for spring boot application is not available in java mission control

### ISSUE THREAD

**Issue by LokeshJonwal** [spring-projects/spring-boot#39332]
We are not able to see the actuator endpoint attributes in jmc.

We are using spring boot version 3.2.1 and jdk mission control jmc-8.3.1_macos-aarch64 and java version is. 
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode)

we also added the actuator dependency in project.

We have setup the config to expose the actuator endpoint and include all metrics 

<img width="228" alt="image" src="https://github.com/spring-projects/spring-boot/assets/43009495/851a075b-cc53-4af4-afda-9a0f4836a845">

<img width="1728" alt="image" src="https://github.com/spring-projects/spring-boot/assets/43009495/d2b8ea3c-772b-436c-96ca-d2b6582313f0">

**Comment by wilkinsona** [comment]
The endpoints expose operations, not attributes. Are the operations available in JMC?

**Comment by LokeshJonwal** [comment]
Operations

<img width="1716" alt="image" src="https://github.com/spring-projects/spring-boot/assets/43009495/44748abe-5ea9-433b-98df-0630ff496db6">

**Comment by wilkinsona** [comment]
Those operations look correct to me.

> I used to see the endpoints metrics attributes as well.

That's surprising. As far as I can remember the JMX endpoints have never exposed attributes and some experimentation with various versions seems to confirm that's the case. 

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. It should expose attributes with one version and not expose them when upgraded to 3.2.1. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by LokeshJonwal** [comment]
Yes you were right it was just operations.
