### ISSUE TITLE
Cannot build 2.6.x bue to missing io.spring.ge.conventions plugin in version 0.0.11.

### ISSUE THREAD

**Issue by superbob** [spring-projects/spring-boot#39342]
🐞 Bug report

I cannot build spring-boot in version _2.6.x_ due to missing `io.spring.ge.conventions` plugin in version _0.0.11_.

Updating the plugin in the `settings.gradle` file to version _0.0.15_ works but I don't know if this is the way to go.

In its current state some of the _2.6.x_ tags and the _2.6.x_ branch don't compile.

To reproduce the issue, just checkout the _2.6.x_ branch in a fresh environment and run `gradle tasks`.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, both OSS and commercial support for 2.6.x has now ended and no further changes will be made to that branch. You can safely remove the `io.spring.ge.conventions` plugin (and indeed the `com.gradle.enterprise` plugin and Gradle Enterprise-related configuration) from `settings.gradle`.
