### ISSUE TITLE
Support ActiveMQContainer Testcontainers implementation

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#39345]
Currently, Spring Boot supports ActiveMQ Service Connection for image `symptoma/activemq` through GenericContainer. Testcontainers 1.19.4 offers a new [activemq](https://java.testcontainers.org/modules/activemq/) module, which offers 2 flavours ActiveMQ Classic and Artemis. Artemis implementation has been already submitted in #39311. ActiveMQ Classic has started publishing [images](https://hub.docker.com/r/apache/activemq-classic/tags) in Docker Hub for amd and arm.

My suggestions is:
* Rename `ActiveMQContainerConnectionDetailsFactory` and deprecate it.
* Add new `ActiveMQContainerConnectionDetailsFactory` to support `ActiveMQContainer`
* Update examples and smoke tests to use ActiveMQContainer

After the release, add support in start.spring.io for `ActiveMQContainer` and `ArtemisContainer`.

I would like to get your feedback before submitting a PR. LMK if you have a different approach.

Thanks

**Comment by mhalbritter** [comment]
I've updated `3.2.x` and `main` to use Testcontainers 1.19.4.

I think the outlined way forward looks good. I'm not sure about the deprecation, though. As `ActiveMQContainerConnectionDetailsFactory` is not public, users will never see the deprecation.

**Comment by mhalbritter** [comment]
When we do this, we should also support `apache/activemq-classic` in our Docker Compose support.

**Comment by scottfrederick** [comment]
Closing in favor of #39363
