### ISSUE TITLE
After upgrading to 3.x, springmobile does not support jakarta

### ISSUE THREAD

**Issue by ft0907** [spring-projects/spring-boot#39349]
I am currently using springboot2.7, springmobile1.5.22.RELEASE, there is no problem!
After upgrading to 3.x, springmobile does not support jakarta. I took a look and found that the springmobile project has been archived. Will I consider upgrading and updating to support jakarta in the future?

**Comment by wilkinsona** [comment]
No, it won't. Spring Mobile is no longer maintained.

**Comment by ft0907** [comment]
if I want to use mobile in springboot3.x version, is there a solution to be compatible with javax?

**Comment by wilkinsona** [comment]
No there isn't. Spring Mobile has been completely unsupported since April 2021 and should no longer be used.
