### ISSUE TITLE
Provide a configuration property for configuring a relying party registration's name ID format

### ISSUE THREAD

**Issue by gbaso** [spring-projects/spring-boot#39343]
Support for `NameIdFormat` was introduced in https://github.com/spring-projects/spring-security/issues/9115, but there is not a corresponding property in [Saml2RelyingPartyProperties](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyProperties.java), and [Saml2RelyingPartyRegistrationConfiguration](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyRegistrationConfiguration.java) does not set any value on the `RelyingPartyRegistration`.

**Comment by BenchmarkingBuffalo** [comment]
Hi @wilkinsona 
I would like to work on this issue. 
If you want, you can assign it to me.

**Comment by scottfrederick** [comment]
Closing in favor of #39395
