### ISSUE TITLE
Update Javadoc for AutoConfigurationImportFilter

### ISSUE THREAD

**Issue by yarodinD** [spring-projects/spring-boot#39358]
In Spring Boot autoconfiguration package, the AutoConfigurationImportFilter javadoc still mentions spring.factories file, which is not supported anymore since Spring Boot 3.0.

Link to Javadoc:
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/AutoConfigurationImportFilter.java#L25

**Comment by yarodinD** [comment]
Sorry, spring.factories file is still used for the filter, I found the https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files documentation.

However, it could be clarified better that for the filter, the org.springframework.boot.autoconfigure.AutoConfigurationImportFilter property in spring.factories is still valid.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The migration guide already says the following:

> support for registering auto-configurations in spring.factories using the `org.springframework.boot.autoconfigure.EnableAutoConfiguration` key has been removed in favor of the imports file. Other entries in `spring.factories` under other keys are unaffected.

We don't want to list every single other key so I don't think there's much that we can do here that wouldn't just repeat what we've already said. `org.springframework.boot.autoconfigure.AutoConfigurationImportFilter` is a different key so, as already described, it is unaffected.
