### ISSUE TITLE
Resolution of property hierarchy from Yaml files results in unexpected behaviour.

### ISSUE THREAD

**Issue by neirfeno** [spring-projects/spring-boot#3939]
Spring resolves Yaml Lists to Properties prior to applying overrides, this means that an overridden list with less elements, will contain some of the previous lists elements. Example:
```
list:
  - aaa
  - bbb
---
spring:
  profile: dev
list:
  - ccc
```
results in:
```
"list[0]" => "ccc",
"list[1] => "bbb"
```
This is obviously not desired. Spring should resolve the hierarchy whilst still in Objects/Lists before flattening to properties.

**Comment by wilkinsona** [comment]
Originally raised as [SPR-13459](https://jira.spring.io/browse/SPR-13459).

**Comment by snicoll** [comment]
See #2611

**Comment by philwebb** [comment]
Looks like I managed to completely miss the point when #2611 was raised. I've reopened it and will close this one as a duplicate.

@neirfeno track #2611 for updates.
