### ISSUE TITLE
WebFlux virtual threads cannot be activated

### ISSUE THREAD

**Issue by MrWangGang** [spring-projects/spring-boot#39412]
When using Spring Boot with WebFlux, enabling spring.threads.virtual.enabled=true does not take effect, and virtual threads cannot be activated.

**Comment by bclozel** [comment]
Thanks for getting in touch, but this report isn't really actionable as we have no idea what configuration you were expecting, why you think it should leverage virtual threads nor how you've come to the conclusion that virtual threads aren't activated.

I'm closing this issue for now.
