### ISSUE TITLE
Spring Boot 3.2.2 post upgrade: Getting compile time error but build success

### ISSUE THREAD

**Issue by rk22927** [spring-projects/spring-boot#39429]
Getting the below error when trying to run the maven clean install comment.

[ERROR] Could not parse class file VirtualThreadDelegate.class
java.lang.UnsupportedOperationException: Hashing for Java 21 and beyond is not supported yet
    at com.sonatype.insight.scan.hash.internal.asm.AsmClassFactory.newClassNode (AsmClassFactory.java:44)

**Comment by bclozel** [comment]
It looks like a build plugin is scanning classes, including the ones shipped by Spring Framework as part of its multi release jar. The ASM version embedded in this plugin doesn't know how to parse Java 21 classes.

Please review your build plugin configuration or report this error to the plugin maintainers.
