### ISSUE TITLE
Fix typo in `TestcontainersPropertySource`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#39438]
https://github.com/spring-projects/spring-boot/blob/b1bf4bbdf5850d318fcbe3e4bcea16447bc607b3/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/properties/TestcontainersPropertySource.java#L132

That should read "Incorrect **TestcontainersPropertySource** type registered".

**Comment by amritagg** [comment]
Hello @sbrannen Can you assign me this issue?

**Comment by amritagg** [comment]
Attaching the PR here: https://github.com/spring-projects/spring-boot/pull/39440

**Comment by scottfrederick** [comment]
Closing in favor of #39440
