### ISSUE TITLE
Expose Additional RabbitMQ Connection Factory and Template AutoConfig Properties

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#3945]
`spring.rabbitmq.publisherConfirms`
`spring.rabbitmq.publisherReturns`

`CachingConnectionFactory` properties to enable confirms/returns.

`spring.rabbitmq.mandatory`

`RabbitTemplate` mandatory bit (enables returns).

All booleans (default false).

**Comment by snicoll** [comment]
not sure. `spring.rabbitmq.mandatory` is a bit vague, isn't it?

**Comment by garyrussell** [comment]
`spring.rabbitmq.publish.mandatory` ?

`spring.rabbitmq.template.mandatory` ?

See 'mandatory bit` at https://www.rabbitmq.com/amqp-0-9-1-reference.html

__mandatory__

This flag tells the server how to react if the message cannot be routed to a queue. If this flag is set, the server will return an unroutable message with a Return method. If this flag is zero, the server silently drops the message.

**Comment by garyrussell** [comment]
BTW, for returns to work in Spring AMQP, both publisherReturns and mandatory must be true.

I suppose we could "imply" the mandatory bit if publisherReturns is set on the connection factory.

**Comment by ramblingred** [comment]
+1

I am currently overriding the bean definition for my CachingConnectionFactory to set the publisher-confirms property to "true". This unfortunately does mean that I've copied much of the same logic in RabbitConnectionFactoryCreator (it's protected) to keep all the existing spring-boot properties loading correctly. Perhaps there is a better way? 

Regardless, getting publisher-confirms options added to the properties would be super helpful.

**Comment by snicoll** [comment]
> BTW, for returns to work in Spring AMQP, both publisherReturns (enables them on the connection) and mandatory must be true.

I can see in the doc that's the same for `publisherConfirms` so basically if any of those are set, the template `mandatory` bit can be enabled?
