### ISSUE TITLE
spring boot project which builed with gradle, jrebel does not wok

### ISSUE THREAD

**Issue by piterwu** [spring-projects/spring-boot#3947]
gradle.properties include:
```
org.gradle.jvmargs=-agentpath:c:/jrebel/lib/jrebel64.dll
```
jrebel.xml configured
But it does not work when run project with bootRun.
However,in project which builded  with maven,jrebel  work fine

**Comment by wilkinsona** [comment]
Can you please explain why you think this is a problem with Spring Boot rather than Gradle or JRebel? It will make it much easier for us to diagnose and fix the problem.

**Comment by piterwu** [comment]
When I use [Gradle Tomcat plugin](https://github.com/bmuschko/gradle-tomcat-plugin) ,JRebel work fine.I can see the JRebel log.
```
2015-09-12 23:48:46 JRebel: Directory '...\build\classes\main' will be monitored for changes.
```
But when I run project with gradle bootRun,no JRebel log display.So I think it might be  a problem with Spring Boot Gradle plugin.

**Comment by wilkinsona** [comment]
`bootRun` forks a separate JVM. It's that JVM that needs to be configured with JRebel's agent. To do so, you need to customise the configuration of the `bootRun` task:

```
bootRun {
    jvmArgs = ['-agentpath::c:/jrebel/lib/jrebel64.dll']
}
```
