### ISSUE TITLE
LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.helpers.NOPLoggerFactory loaded from file:/.m2/org/slf4j/slf4j-api/2.0.11/slf4j-api-2.0.11.jar).

### ISSUE THREAD

**Issue by samragu** [spring-projects/spring-boot#39470]
Upgrading from Spring Boot 2.5.14 to 3.2.2 and running into this issue. A number of suggestions are out there to exclude spring-boot-starter-logging but we use that library and the logback it bootstraps. I see similar issue  https://github.com/spring-projects/spring-boot/issues/37484 that was resolved in 3.2.2 but the above issue is in 3.2.2

**Comment by wilkinsona** [comment]
As I said in https://github.com/spring-projects/spring-boot/issues/37484#issuecomment-1881150975, if you're seeing the problem in a version where it should be fixed, please provide a minimal sample that reproduces the problem.

**Comment by samragu** [comment]
While trimming down my project to create a sample, I discovered that a separate logback version was prescribed by a parent pom that seemed to cause this error. I have fixed it and is no longer an issue. Thanks for taking time to respond, much appreciated!
