### ISSUE TITLE
Inconsistency in the documentation of Spring DevTools setup

### ISSUE THREAD

**Issue by yousoumar** [spring-projects/spring-boot#39488]
The Spring DevTools doc says in its most ranked [page](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html) that the package should be included this way:

```
dependencies {
    compileOnly("org.springframework.boot:spring-boot-devtools")
}
```

Which does not work as discussed in #14451. And on this [page](https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/reference/htmlsingle/#using-boot-devtools) it says it should be: 

```
dependencies {
	compile("org.springframework.boot:spring-boot-devtools")
}
```
While the correct one seems to be what this [page](https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools) says::

```
dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
}
```

**Comment by yousoumar** [comment]
Hi @wilkinsona ! I see. The tricky part is that the version is only mentioned in the URL, where not meany people look at and, also, some browsers like Safari do not show the full URL by default.

**Comment by wilkinsona** [comment]
Unfortunately, we can't change documentation that's already been released and published as it's built from an immutable tag in this repository. The move to Antora will help with showing the version number as well. See [Spring Framework's documentation](https://docs.spring.io/spring-framework/reference/) for example.

**Comment by yousoumar** [comment]
Thanks for the answers, and for all the effort in making this awesome framework!
