### ISSUE TITLE
update "40.4.2 Git commit information" for Gradle

### ISSUE THREAD

**Issue by n0mer** [spring-projects/spring-boot#3949]
Currently http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-git-commit-information says 

> A similar `gradle-git` plugin is also available for Gradle users, although a little more work is required to generate the properties file.

This functionality now can be achieved in Gradle as well by using https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties plugin

```groovy
plugins {
  id "com.gorylenko.gradle-git-properties" version "1.4.6"
}
```

**Comment by wwadge** [comment]
I can confirm that v1.4.6 worked for me.

**Comment by jackmatt2** [comment]
:+1:
