### ISSUE TITLE
RepositoryRestConfiguration.setBaseUri dose not recognized by Swagger

### ISSUE THREAD

**Issue by soursop** [spring-projects/spring-boot#3950]
I'm trying to set setBaseUri using RepositoryRestConfiguration class and Swagger. 
When I set base uri as '/api', this uri does not recognized by swagger.
my sample project is :
https://github.com/soursop/rest-api-sample

Is there any other reason prefixed uri that configured by setBaseUri method is not recognized by third part application(e.g. Swagger)? If you don't mind or any other reason doesn't exist, I'd would like to create PR to fix this problem.

**Comment by wilkinsona** [comment]
I'm not surprised that this doesn't work as Swagger's Spring MVC integration [doesn't support Spring Data REST](https://github.com/springfox/springfox/issues/699), in no small part because Swagger itself doesn't support hypermedia.
