### ISSUE TITLE
Refactor getElement method to clarify ignored exception in AnsiElement

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#39519]
Forward port of issue #39518 to 3.2.x.

**Comment by izeye** [comment]
https://github.com/spring-projects/spring-boot/pull/39518 has been declined, but this and https://github.com/spring-projects/spring-boot/issues/39520 don't seem to have been updated accordingly with their labels and miletone.

**Comment by wilkinsona** [comment]
Thanks, @izeye.
