### ISSUE TITLE
JDK8 Optional and Animal Sniffer plugin issue

### ISSUE THREAD

**Issue by chanwookpark** [spring-projects/spring-boot#3951]
Hi.

I trying to JDK 8 'Optional', then throw next exception.

[INFO] --- animal-sniffer-maven-plugin:1.14:check (enforce-java-6) @ applestore-front ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
...
[ERROR] ....java:41: Undefined reference: boolean java.util.Optional.isPresent()

code is that,
```java
final Optional<Product> otlProduct = repository.findOne(productId);
if (!otlProduct.isPresent()) {
   //...
}
Product product = otlProduct.get();
```

IntelliJ compiling is ok, but maven with spring boot plugin failed.

So I check Spring boot pom, then I confuse that next animal sniffer configuration.

```XML
<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>animal-sniffer-maven-plugin</artifactId>
				<configuration>
					<signature>
						<groupId>org.codehaus.mojo.signature</groupId>
						<artifactId>java16</artifactId>
						<version>1.0</version>
					</signature>
					<annotations>
						<annotation>org.springframework.lang.UsesJava8</annotation>
						<annotation>org.springframework.lang.UsesJava7</annotation>
					</annotations>
				</configuration>
				<executions>
					<execution>
						<id>enforce-java-6</id>
						<phase>test</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

Is this problem? or I missing? 

Thank you

**Comment by chanwookpark** [comment]
I'm using 1.3.0.M5.

**Comment by snicoll** [comment]
It's not clear what you're asking. Are you working in the spring boot codebase or is it your own project? If that's your own project, follow the documentation and inherit from the `spring-boot-starter-parent`. Your build is probably wrong.

Either way, that kind of question should go on StackOverflow so if that's still not clear, please create a thread there.
