### ISSUE TITLE
A metric writer for NewRelic can be integrated into boot?

### ISSUE THREAD

**Issue by dgomesbr** [spring-projects/spring-boot#3953]
I was looking into the https://github.com/spring-projects/spring-boot/tree/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics and at Bemobi we use NewRelic metrics a lot and I was thinking about writing a custom Metric writer for New Relic, would that be suitable here or any thirdparty ones? 

Another question is that since NewRelic metrics use the metric name format foo/bar/baz instead of foo.bar.baz, a custom naming strategy have to be implemented right?

ref to it: http://www.jayway.com/2014/03/26/custom-metrics-with-new-relic/

**Comment by philwebb** [comment]
Interesting, I've used New Relic only briefly so I can't really say if this should be part of Boot or best as an add-on. My gut feeling is that it might be best developed outside of Spring Boot and publicized in the "third-part" section of the reference docs.

**Comment by dgomesbr** [comment]
@philwebb Since it's a commercial APM that's my initial feeling. Regarding the implementation, is there any docs on what to implement / extend regarding the writer, configuration (look for new relic agent on classpath) and naming metrics (translating from foo.bar.baz to foo/bar/baz for example)?

Thanks!

**Comment by philwebb** [comment]
@dgomesbr Only the Javadoc I'm afraid :(

**Comment by dgomesbr** [comment]
Sample metric names using "dash separator" naming style.
![Sample new relic metrics](http://i.imgur.com/Kpa8T45.jpg)

**Comment by dgomesbr** [comment]
Hey @philwebb, feel free to close it then, I'll read some of the javadoc and try to implement such thing. Thanks again for the promptness.
