### ISSUE TITLE
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/action/AbstractEventEvaluatorAction

### ISSUE THREAD

**Issue by prabal-saxena-db** [spring-projects/spring-boot#39532]
Hi Team, I see this issue was closed without any solution because of lack of data. we are also facing this issue and we are stuck in our development. Currently, we are upgrading and fixing vulnerabilities in our application.

We are using below plugin:

ch.qos.logback logback-core 1.3.12
Error : org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logbackConfigurer' defined in class path resource [com/db/esles/configuration/LogbackConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/action/AbstractEventEvaluatorAction

As maven is not able to find this class, we are not sure how can we overcome this issue.

**Comment by bclozel** [comment]
Duplicates #37110

There is no issue with Spring Boot as far as we know. We can reopen this issue if you provide a sample application that reproduces the problem. Thanks!

**Comment by prabal-saxena-db** [comment]
[Uploading logback-classic-core-issue.zip…]()

**Comment by bclozel** [comment]
@prabal-saxena-db this link doesn't work.

**Comment by prabal-saxena-db** [comment]
Hi @bclozel, I am providing a different link in some time, this is an upload from my org email address

**Comment by Prabal-saxena** [comment]
Hi @bclozel, could you please try access below project

https://github.com/Prabal-saxena/logbackClassicIssue.git

**Comment by wilkinsona** [comment]
You are trying to use Logback 1.3 with Spring Boot 2.7 which is not supported. Spring Boot 2.7 requires Logback 1.2. Also, please note that OSS support for Spring Boot 2.7.x has ended. You could upgrade to Spring Boot 3.1.x or later.
