### ISSUE TITLE
Docker Compose Properties `spring.docker.compose.enabled=false` has no effect

### ISSUE THREAD

**Issue by ranma2913** [spring-projects/spring-boot#39541]
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.docker-compose calls out that we should be able to disable the docker compose support with `spring.docker.compose.enabled=false` however it has no affect for some reason. 

Steps to Recreate:
1. set `spring.docker.compose.enabled: false` in application.yaml
2. set `spring.docker.compose.enabled=true` in application-local.properties
3. run application in some other profile like 'stage'

I've created a simple app to emulate the issue.

https://github.com/ranma2913/spring-boot_docker-compose-support_example

**Comment by ranma2913** [comment]
Ok, so I was trying to reproduce the issue in my example app, and at first I wasn't able to. Turns out this is related to not respecting java properties used to start the spring-boot app from my IDE. You can see in the below screenshot I'm starting the application with `-Dspring.profiles.active=stage` but the active-profile isn't set.
![image](https://github.com/spring-projects/spring-boot/assets/4295880/f884d9fc-58b8-462a-971e-5c8db3b2dd8e)
![image](https://github.com/spring-projects/spring-boot/assets/4295880/1e173c04-0112-4303-aa18-44be5cd52cac)

**Comment by wilkinsona** [comment]
Docker Compose profiles and Spring profiles are two separate concepts. The former is controlled by `spring.docker.compose.profiles.active` while the latter is controlled by `spring.profiles.active`. You appear to have set the latter but your screenshots are showing the classes to which the former is bound.

**Comment by ranma2913** [comment]
> Docker Compose profiles and Spring profiles are two separate concepts. The former is controlled by `spring.docker.compose.profiles.active` while the latter is controlled by `spring.profiles.active`. You appear to have set the latter but your screenshots are showing the classes to which the former is bound.

Yeah this wasn't related. The issue seems to be because of spring-cloud-config in the bootstrap phase. This application event ends up causing the docker-compose to execute a second time.

**Comment by ranma2913** [comment]
@wilkinsona I don't think this should be closed yet. Until it's understood if there's a bug with the Spring-Cloud integration. 

I'll keep looking.

**Comment by ranma2913** [comment]
> Docker Compose profiles and Spring profiles are two separate concepts. The former is controlled by `spring.docker.compose.profiles.active` while the latter is controlled by `spring.profiles.active`. You appear to have set the latter but your screenshots are showing the classes to which the former is bound.

The issue is me trying to set the spring.profiles.active is where the `spring.docker.compose.enabled=false` is defined so if the profile isn't activating and loading properties it won't disable the docker-compose like I am expecting.

**Comment by wilkinsona** [comment]
In that case, this could be the same problem as https://github.com/spring-projects/spring-boot/issues/35878. I cannot tell for sure as I don't know what version of Spring Cloud you're using. If the problem remains when using the latest version of Spring Cloud, please open a Spring Cloud issue so that they can investigate.

**Comment by ranma2913** [comment]
Sorry for the chats. 

Anyway, I've confirmed the issue is with `spring-cloud-starter-bootstrap`. When the [Spring-Cloud Bootstrap Application Context](https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html#_the_bootstrap_application_context) starts, DockerComposeLifecycleManager.start() is called, however since I only saw the documentation mentioning setting `spring.docker.compose.enabled=false` in the application.properties file, It appeared as though the properties weren't taking affect, when in-fact they hadn't been loaded into the application context yet.

I can see how this is actually the expected behavior since a user may wish to provide something like a Hashicorp Vault pod for local development, that pod being needed as part of the bootstrap phase.

I'm just wondering if we could add a warning or note to the docs mentioning something like: "If you use Spring-Cloud Bootstrap, Docker Compose Properties can be added to your bootstrap.yaml to configure the bootstrap phase."

**Comment by wilkinsona** [comment]
Behavior changes due to the Bootstrap context aren't limited to Spring Boot's Docker Compose integration. For example, it'll affect anything that uses an `ApplicationListener` registered in `spring.factories`. As such, I don't think it's practical for Boot's documentation to mention this everywhere that it may be relevant. It would be better if it was documented once in Spring Cloud's documentation.
