### ISSUE TITLE
Add SpringApplicationBuilder#singletons(Object... singletons)

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#3954]
`SpringApplicationBuilder#singletons(Object... singletons)` would be very useful in practice:

``` java
public SpringApplicationBuilder singletons(Object... singletons) {
    return initializers(singletonBeans(singletons))
}
```

Where `singletonBeans` is a `static` utility defined as:

``` java
@RequiredArgsConstructor(access = PRIVATE)
public class SingletonBeansInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

  /**
   * Beans.
   */
  @NonNull
  private final Object[] singletonBeans;

  public static SingletonBeansInitializer singletonBeans(Object... singletonBeans) {
    return new SingletonBeansInitializer(singletonBeans);
  }

  @Override
  public void initialize(ConfigurableApplicationContext applicationContext) {
    for (val singletonBean : singletonBeans) {
      registerBean(applicationContext, singletonBean);
    }
  }

  private void registerBean(ConfigurableApplicationContext applicationContext, Object singletonBean) {
    val beanName = singletonBean.getClass().getCanonicalName();

    val factory = applicationContext.getBeanFactory();
    factory.registerSingleton(beanName, singletonBean);
  }

}
```

It could be used like this:

``` java
  // Application entry-point
  public static void main(String... args) {
    // Custom command line arguments
    val options = new Options();

    // JCommander for formal arguments
    val cli = new JCommander(options);
    cli.setAcceptUnknownOptions(true); // Play nicely with Spring Boot's -- style args
    cli.parse(args);

    // Add cli and options to the context first to be bound downstream in @Configurations, etc.
    new SpringApplicationBuilder(ClientMain.class).singletons(cli, options).run(args);
    ...
}
```

Allowing very convenient bean binding from the outside world, a feature that is currently missing.

**Comment by snicoll** [comment]
Thanks for the idea. I am not sure I understand how that would be very useful. Can you please share a concrete use case?

**Comment by btiernay** [comment]
CLI objects that need to be added into the application context. Example above.

**Comment by btiernay** [comment]
I should also mention, this is an extension to the current methods that exist such as `inializers` and `listeners`. It is also more general as I believe it can support these use cases as well.

**Comment by philwebb** [comment]
It feels like your use case is a little unusual and I'm not keen to make `SpringApplication` or `SpringApplicationBuilder` too complex.

It looks like your current code would work as is with by calling:

```java
new SpringApplicationBuilder(ClientMain.class).initializers(singletonBeans(cli, options)).run(args);
```

I think I'd rather wait for a few votes before considering this one.

**Comment by btiernay** [comment]
Fair enough, although I would argue that the case for `singletons` is actually stronger than the special case of `initializers` and `listeners`. 

That being said, how is one expected to perform formalized command line argument checking in a boot application? Or is that out of scope? The fundamental reason I need to pass objects to the context is that there is not a good way to define command line arguments in boot, with documentation and a formal interface. Instead, one needs to rely on external libraries like jcommander, jopts, etc. Its a shame because the `ConfigurationProperties` object comes pretty close, but misses the mark here.

**Comment by philwebb** [comment]
@btiernay It's not something we've really looked at in too much detail. It seems that currently Web/Rest application seem to be the 80% for Boot Applications.

We used `jopt-simple` when developing [`spring-boot-cli`](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-cli). You might be able to crib some code from that project.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by bclozel** [comment]
Spring Framework 5.0 now supports a functional way to register beans. See [SPR-14832](https://jira.spring.io/browse/SPR-14832).
