### ISSUE TITLE
Implement HttpClient based Zipkin sender

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#39545]
Currently, we have 3 Zipkin senders:

* `URLConnectionSender`, needs zipkin-sender-urlconnection
* RestTemplate based one, needs spring-web
* WebClient based one, needs spring-webflux

With the changes in #39049, the webclient one will likely be removed, as the Zipkin sender interface is no longer async by default and we have to call `block`.

We should implement a JDK `HttpClient` based sender, which can be used without any dependencies.

**Comment by mhalbritter** [comment]
Some WIP in https://github.com/mhalbritter/spring-boot/tree/mh/39545-implement-httpclient-based-zipkin-sender.

**Comment by wilkinsona** [comment]
I wonder if we should only provide a `HttpClient`-based sender. It would simplify things a little and give us less code to maintain if we got rid of the other two as well as the `WebClient`-based one.

**Comment by mhalbritter** [comment]
Yeah, I think that's a good idea. I'll try to get the `HttpClient` sender into 3.3.x and then we can deprecate the other ones.

**Comment by mhalbritter** [comment]
Blocked until #39049 is merged.

**Comment by codefromthecrypt** [comment]
this is great. looking forward to the removal of the other senders!
