### ISSUE TITLE
EmbedMongo with port=0 couses java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by paweldolecinski** [spring-projects/spring-boot#3955]
Hi,

when using Embedded MongoDB support with spring.data.mongodb.port=0 I ended up with java.lang.StackOverflowError.

The problem is with recursive invocation of method private void setPortProperty(ApplicationContext context, int port) from EmbeddedMongoAutoConfiguration.

Instead of:
```
if (this.context.getParent() != null) {
			setPortProperty(this.context.getParent(), port);
		}
```
should be:
```
if (context.getParent() != null) {
			setPortProperty(context.getParent(), port);
		}
```
Without "this" keyword.

**Comment by snicoll** [comment]
I am curious how you manage to run in such scenario. Can you explain a bit more?

**Comment by wilkinsona** [comment]
I'd like to understand too. The code's a bit sloppy, but I don't understand how it causes a StackOverflowError. Our MongoDB sample sets the port to 0 so there must be more to it than you have described.

**Comment by paweldolecinski** [comment]
After deeper investigation I see that in normal configuration indeed it works. 
However, when you look at the code above it should be clear, that for hierarchical contexts it won't work because of recursive call with the same argument for each call.

And this is exactly my case. 
I am using 'spring-cloud-starter-config', so I've got contexts hierarchy as follows:

AnnotationConfigApplicationContext (id: bootstrap:integration:0)
|_
   AnnotationConfigEmbeddedWebApplicationContext(id: my-app:integration:0)

In that situation, code:
'''
if (this.context.getParent() != null) {
   setPortProperty(this.context.getParent(), port);
} 
'''
will be trapped inside infinite loop leading to StackOverflowError

**Comment by wilkinsona** [comment]
I see now, thank you.
