### ISSUE TITLE
Document configuration property default for the show-values properties

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#39565]
See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.actuator.management.endpoint.configprops.show-values for example. They all default to `NEVER`.

There are three of them: `management.endpoint.configprops.show-values`, `management.endpoint.env.show-values` and `management.endpoint.quartz.show-values`.

**Comment by mhalbritter** [comment]
This can be done by adding an entry in `spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json`. You can take `management.prometheus.metrics.export.histogram-flavor` (the backing code is `org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusProperties#histogramFlavor`) for a blueprint, it's an enum with a default, too.

**Comment by scottfrederick** [comment]
Closing in favor of #39589.
