### ISSUE TITLE
Allow more configuration for ConditionalOnProperty

### ISSUE THREAD

**Issue by goughy000** [spring-projects/spring-boot#39607]
I was wanting to make use of `@ConditionalOnProperty` in a project recently and expected it to evaluate false if the value of the property was `null`, however it seems that the condition only evaluates false if the property is completely missing, or it's set to the string value `false`

What I want to propose is that we add another option to the annotation like follows

```java
String[] notHavingValues() default { "false" };
```

and then in `OnPropertyCondition::isMatch` we can check against this rather than the hardcoded `false` value.

For my use case I could then annotate my bean definition as so, whilst also not breaking backwards compatibility

```java
@Bean
@ConditionalOnProperty(name = "my.property", notHavingValues = { "", null })
public Widget widget() {
   return new Widget();
}
```

Happy to raise a PR, but wanted to get feedback first - thanks for your consideration!

Alternative workarounds are to use a ConditionalOnExpression and write spel

**Comment by quaff** [comment]
I offered a more general proposal https://github.com/spring-projects/spring-boot/issues/39614

**Comment by goughy000** [comment]
I'm happy with either, whichever the maintainers prefer.
