### ISSUE TITLE
Add configuration property to disable long timers in Micrometer Observations

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#39618]
Micrometer Tracing [will get a feature to turn off the long task timers in observations](https://github.com/micrometer-metrics/micrometer/pull/4755). We should add a configuration property for that, too.

**Comment by jonatan-ivanov** [comment]
Thanks for keeping this in mind. I merged the changes in Micrometer, they are available in the latest snapshot and planned to be released in `1.13.0-M2`.
