### ISSUE TITLE
Allow configure in properties to avoid the default Tomcat Error page show version

### ISSUE THREAD

**Issue by lc0138** [spring-projects/spring-boot#39634]
During a penetration test one finding was the information disclosure of using a Tomcat webserver.

If a request with an invalid URL (e.g. [http://localhost:8080/test?info={"id":null}]), the embedded Tomcats ErrorReportValve is used and presents a default Tomcat Error page. (Spring-Boot 2.1.7+Tomcat 9.0.54)

For standalone deployment of Tomcat, we can configure it in server.xml to ,like this (under Host tag):
`<Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false" />`

But for embedded Tomcat, this configuration is not possible with an application.properties file. And now we just override the ErrorReportValve.java, set the member variables showReport and showServerInfo to false. In this way, the Error page will not show the Tomcat server info, like version.

Maybe it would be a good idea to expose the properties for configuration.
What do you think?

**Comment by mhalbritter** [comment]
Hello, Spring Boot 2.1.7 is not supported anymore. Please upgrade to at least 3.1.x and see if this is still a problem.
