### ISSUE TITLE
Checkstyle and Eclipse disagree on default formatting

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3964]
Checkstyle wants:

```
features == null ? Collections.<Feature>emptySet() : features;
```

STS 3.6.4.RELEASE gives me:

```
features == null ? Collections.<Feature> emptySet() : features;
```

**Comment by philwebb** [comment]
@wilkinsona I thought 653d2b2b4eaa2c99fb30f5038d5c4759b279c55a fixed this. Try updating the project to pull in the latest project specific settings.

**Comment by wilkinsona** [comment]
Thanks, @philwebb. For reasons I don't understand, I had to remove the project from my workspace, git clean, and reimport to get the new settings.
