### ISSUE TITLE
Upgrade Hibernate to 6.4.4.Final

### ISSUE THREAD

**Issue by datazuul** [spring-projects/spring-boot#39649]
https://github.com/spring-projects/spring-boot/blob/50301a5e63dd2555947ab71afd3ab40e0854563e/spring-boot-project/spring-boot-dependencies/build.gradle#L384

Latest Hibernate fixes some bugs (6.4.1.Final has bugs like "Binding is multi-valued; illegal call to #getBindValue" false positive)
https://in.relation.to/2024/02/08/orm-644-final/

**Comment by bclozel** [comment]
There is no need to ask for a dependency upgrade.

As mentioned in our issue template:
> You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release.

We will perform upgrades matching [our 3rd party upgrade policy](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies).
If this is an urgent matter for you, there is no need to wait for us releasing as you can use a [Gradle](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies.dependency-management-plugin.customizing) or [Maven](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#using.parent-pom) build property to override the library version.
All [version properties are listed in the reference documentation appendix](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.dependency-versions.properties).

**Comment by wilkinsona** [comment]
Furthermore, this is a duplicate of https://github.com/spring-projects/spring-boot/issues/39569.
