### ISSUE TITLE
RemoteSpringApplication/Debug Tunnel not working with Proxy

### ISSUE THREAD

**Issue by chr-b** [spring-projects/spring-boot#3968]
I recently tried the debug tunnel feature of Spring Boot Remote 1.3.0.M5.
Unfortunately, `org.springframework.boot.devtools.RemoteSpringApplication` is not picking up my proxy settings. This means, I am unable to use the remote debug feature when working from behind a corporate proxy.

Setting `JAVA_OPTS=-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=PORT` for `RemoteSpringApplication` to use a local proxy to bypass the regular proxy does not work.

I checked the Spring Boot code with the debugger and noticed that the `SimpleClientHttpRequestFactory` passed in `RemoteClientConfiguration.remoteDebugTunnelClient` has a NULL proxy member.

I noticed the other tickets on similar issues (https://github.com/spring-projects/spring-boot/issues/3816, https://github.com/spring-projects/spring-boot/issues/136, https://github.com/spring-projects/spring-boot/issues/914) but I have not found a solution there.

**Comment by zhanhb** [comment]
move to stackoverflow

**Comment by philwebb** [comment]
This doesn't look like a stackoverflow type question to me, seems like the bug report is pretty complete.

**Comment by ummershervani** [comment]
Is there any guidelines on how to configure this for springboot application?
setting these doesnt seem to work
JAVA_OPTS=-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=PORT

**Comment by wilkinsona** [comment]
The documentation that was added in the commit that closed this issue tells you what to do:

> If you need to use a proxy to access the remote application, configure the `spring.devtools.remote.proxy.host` and `spring.devtools.remote.proxy.port` properties.
