### ISSUE TITLE
Springboot3.2.2 can not find symbol org.springframework.boot.loader.jar.JarFile

### ISSUE THREAD

**Issue by developwbperson** [spring-projects/spring-boot#39691]
Hi,

After we migrated from Spring Boot 3.1.5 to 3.2.2, When we build our project using Gradle, an error has occurred:

```
cannot found symbol: import org. springframework. boot. loader. jar.JarFile;
```

We used `JarFile.registerUrlProtocolHandler();` in the project.

Has anyone encountered a similar problem? I am happy with any comments. 

Thanks

**Comment by wilkinsona** [comment]
We don't consider the loader to be public API and you ideally would not be calling `JarFile.registerUrlProtocolHandler()` in your code. Why is it necessary for you to do that?

You can find the old code, including the `JarFile` class in the `spring-boot-loader-classic` module.

**Comment by developwbperson** [comment]
@wilkinsona 

Thank you.

My problem has been solved

I'm sorry for replying so late.
