### ISSUE TITLE
WebIntegrationTest with ActiveProfiles

### ISSUE THREAD

**Issue by slusset** [spring-projects/spring-boot#3970]
Hi,  I have an Abstract Test class configured for Spring Boot web integration tests.  I would like it to only run under specific maven profile.  However, the Integration Tests run even when the profile is not active.

```java
@RunWith(SpringJUnit4ClassRunner.class)
@ActiveProfiles("spring-integration-test")
@SpringApplicationConfiguration(classes = AdminApp.class)
@WebIntegrationTest("server.port=0")
public abstract class AbstractControllerTest {
```

Maven Snippet
```xml
<profile>
   <id>spit</id>
   <properties>
     <spring.profiles.active>spring-integration-test</spring.profiles.active>
   </properties>
</profile>
```

I have 

`spring-*:4.1.7.RELEASE`
`spring-boot-*:1.2.5.RELEASE`
`junit:4.12`

Thanks!

**Comment by wilkinsona** [comment]
There's no support in Spring Framework's testing support for only running a test if a particular Spring profile is active at the moment. Please see [SPR-11677](https://jira.spring.io/browse/SPR-11677) for further information.
