### ISSUE TITLE
spring-boot-starter-data-jpa: please update spring-data-jpa from 1.7.3.RELEASE to 1.9.0.RELEASE

### ISSUE THREAD

**Issue by n0mer** [spring-projects/spring-boot#3971]
Hi,

currently `spring-boot-starter-data-jpa` (and `spring-boot` [blessed dependencies](http://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html)) references dated version of spring-data-jpa: 1.7.3.RELEASE

Please update to recent [1.9.0.RELEASE](https://github.com/spring-projects/spring-data-jpa/releases/tag/1.9.0.RELEASE)

**Comment by zhanhb** [comment]
spring-data-releasetrain.version of 1.3.0.M5 is Gosling-RELEASE, 
spring-data-jpa.version of spring-data Gosling-RELEASE is 1.9.0.RELEASE.

spring-data-releasetrain.version of 1.2.6.RELEASE is Evans-SR3, 
spring-data-jpa.version of spring-data-Evans-SR3 is 1.7.3.RELEASE.

And you should ask question in stackoverflow.com

**Comment by zhanhb** [comment]
current version is 1.7.3.RELEASE, do you means http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/appendix-dependency-versions.html?

**Comment by n0mer** [comment]
@zhanhb yes i mean that this `blessed` dependency version can be bumped.

**Comment by zhanhb** [comment]
1.2.x will never update to 1.9.0.RELEASE for compatibility. 1.3.x isn't released yet.

**Comment by n0mer** [comment]
@zhanhb i understand about compatibility, just got `java.lang.AbstractMethodError` today

**Comment by zhanhb** [comment]
but how can you get the AME, and you'd better ask question in stackoverflow.

**Comment by n0mer** [comment]
@zhanhb i sorted that out, good to know that 1.3.x will have 1.9.0.RELEASE

**Comment by zhanhb** [comment]
add <spring-data-releasetrain.version>Gosling-RELEASE</spring-data-releasetrain.version> to pom.xml, you can work with spring-data-jpa 1.9.0.RELEASE and spring-boot 1.2.x

**Comment by n0mer** [comment]
@zhanhb will Gosling-RELEASE work for Gradle?

**Comment by zhanhb** [comment]
of course, but i don't know how to declare in gradle.
```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-releasetrain</artifactId>
    <version>${spring-data-releasetrain.version}</version>
    <scope>import</scope>
    <type>pom</type>
</dependency>
```
this is the code of spring-data-release-train

**Comment by n0mer** [comment]
@zhanhb thank you

**Comment by zhanhb** [comment]
That's all right.
