### ISSUE TITLE
Add comments for sample projects

### ISSUE THREAD

**Issue by bowenli86** [spring-projects/spring-boot#3972]
Can you please add comments for all sample projects in `README`? For example, currently there's no comment for `spring-boot-sample-jpa`, and I'm not sure about the difference between `spring-boot-sample-jpa` and `spring-boot-sample-data-jpa`.

Thanks!

**Comment by philwebb** [comment]
The samples are somewhat internal, we primarily use them for integration tests. The difference between `spring-boot-sample-jpa` and `spring-boot-sample-data-jpa` is that the latter uses Spring Data JPA, whilst the former just uses raw JPA.

**Comment by wilkinsona** [comment]
[The README](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/README.adoc) now includes a brief description of each sample.
