### ISSUE TITLE
Support for ClasspathResource loading in TomcatEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#3973]
Hi,

We have the below code UndertowEmbeddedServletContainerFactory. This supports loading the file from classpath.

```
			Ssl ssl = getSsl();
			String keyStoreType = ssl.getKeyStoreType();
			if (keyStoreType == null) {
				keyStoreType = "JKS";
			}
			KeyStore keyStore = KeyStore.getInstance(keyStoreType);
			URL url = ResourceUtils.getURL(ssl.getKeyStore());
			keyStore.load(url.openStream(), ssl.getKeyStorePassword().toCharArray());
```

But, in TomcatEmbeddedServletContainerFactory we have the below code

```
	private void configureSslKeyStore(AbstractHttp11JsseProtocol<?> protocol, Ssl ssl) {
		try {
			File file = ResourceUtils.getFile(ssl.getKeyStore());
			protocol.setKeystoreFile(file.getAbsolutePath());
		}
		catch (FileNotFoundException ex) {
			throw new EmbeddedServletContainerException("Could not find key store "
					+ ssl.getKeyStore(), ex);
		}
		if (ssl.getKeyStoreType() != null) {
			protocol.setKeystoreType(ssl.getKeyStoreType());
		}
		if (ssl.getKeyStoreProvider() != null) {
			protocol.setKeystoreProvider(ssl.getKeyStoreProvider());
		}
	}

```

This is not consistent and more over it does not support loading from classpath. 

I think this could be easily fixed. Any thoughts?

**Comment by wilkinsona** [comment]
As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-ssl), it's Tomcat that requires the resource to be loaded from the filesystem rather than via the classpath:

> Tomcat requires the key store (and trust store if you’re using one) to be directly accessible on the filesystem, i.e. it cannot be read from within a jar file. This limitation doesn’t apply to Jetty and Undertow.

In short, this is a Tomcat limitation that Spring Boot has to live with at the moment. There's an [open Tomcat enhancement request] that you might want to watch.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/2635
