### ISSUE TITLE
Duplicate Message Convertors

### ISSUE THREAD

**Issue by hassanrehman01398** [spring-projects/spring-boot#39743]
Issue Description:

I'm encountering an issue with duplicate MappingJackson Converters of the same data type in my Spring application. The first converter has five modules registered, while the second one has two. When making a RestTemplate call, the second converter is being invoked, leading to the following error:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type Argument #0 of constructor com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)} has no property name (and is not Injectable): cannot use as property-based Creator

This error indicates a problem during Jackson deserialization. It appears that the second converter is causing conflicts in the deserialization process, resulting in the mentioned exception.

Steps to Reproduce:

Register two MappingJackson Converters of the same data type.
The first converter has five modules, and the second converter has two modules.
Make a RestTemplate call that triggers the deserialization process.
Expected Behavior:

The RestTemplate should use the first converter for deserialization without any issues.

Actual Behavior:

The second converter is invoked during deserialization, leading to the InvalidDefinitionException.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, the steps to reproduce aren't sufficient for us to diagnose the problem as they leave too much unknown. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by hassanrehman01398** [comment]
The error is coming when I am calling API. The code of calling is simple 

RestTemplate template = restTemplateBuilder
                .rootUri(recomadUri)
                .setConnectTimeout(Duration.ofSeconds(30L))
                .setReadTimeout(Duration.ofSeconds(30L))
                .build();
                
![image](https://github.com/spring-projects/spring-boot/assets/47937749/803b273e-e034-4cbf-b3a8-f48fa52d7ebd)
Depending on the deployment, either the “correct” Converter (and therefore ObjectMapper) is higher in the list and is being prioritised, or the other. And if we are unlucky, we will use the wrong ObjectMapper that cannot deserialize this into Java. And hence, we get the exceptions.

**Comment by hassanrehman01398** [comment]
The code is private and I can't share that. I can try to explain you the more.

From time to time, we get exceptions like

Failed to evaluate Jackson deserialization for type [[simple type, class com.RecomadPublisherResponse]]: 
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `com.publisher.Publisher`: 
Argument #0 of constructor [constructor for `com.Publisher` (16 args), annotations: 
{interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)} 
has no property name (and is not Injectable): can not use as property-based Creator
when calling API

This is because of the data model Publisher using a weird approach to work with Jackson. The fields on the wire are using underscore-naming whereas java uses camelcase. Because of this,  @JsonProperty is put on every field. Not a problem so far. But, the deserialization is being done with custom constructor that has @JsonCreator:

![image](https://github.com/spring-projects/spring-boot/assets/47937749/2b3c3395-9f82-4c22-8d68-be7fbe3d5ae3)

or this combination (i.e. JsonProperty with JsonCreator) to work, ParameterNamesModule has to be registered by ObjectMapper. See [#1](https://github.com/FasterXML/jackson/discussions/170) and [#2](https://github.com/FasterXML/jackson-modules-java8/).

However, the RestTemplate for API contains 2 MappingJackson2HttpMessageConverters with 2 ObjectMappers. And… one ObjectMapper has this module whereas the other does not:

![image](https://github.com/spring-projects/spring-boot/assets/47937749/e1324690-1e2c-408c-b032-ca1f2ff0a62c)
Depending on deployment , either the “correct” Converter (and therefore ObjectMapper) is higher in the list and is being prioritised, or the other. And if we are unlucky, we will use the wrong ObjectMapper that cannot deserialize this into Java. And hence, we get the exceptions.

Spring version: 2.7.5

**Comment by wilkinsona** [comment]
> The code is private and I can't share that

We don't need to see your full app, just a minimal app that reproduces the problem.

> Spring version: 2.7.5

OSS support for Spring Boot 2.7.x is [no longer available](https://spring.io/projects/spring-boot#support). Please upgrade to 3.1.x or later. If the problem still occurs and you provide a complete yet minimal example that reproduces it, we can re-open this issue and take another look.

**Comment by bclozel** [comment]
Also see https://github.com/spring-projects/spring-boot/issues/21374#issuecomment-1961192027
