### ISSUE TITLE
Providing a default configuration for access log

### ISSUE THREAD

**Issue by nodje** [spring-projects/spring-boot#3974]
My understanding so far is that the TraceWebFilterAutoConfiguration is the closest there is to access log.
https://github.com/spring-projects/spring-boot/pull/3948 now makes it convenient to get all the informations you would need from the actuator's trace endpoint.
But there's no way to get this into a file as far as I can see. (TRACE log level on WebRequestTraceFilter doesn't write much info and would probably be slow, though a Logback ASYNC appender could help in this regard.)

Logback-access would be another external solution, and it's probably well implemented, but it requires the TeeFilter to get the payloads content and the [website itself](http://logback.qos.ch/recipes/captureHttp.html#disabling) discourages its usage in a production environment. Besides it's not as configurable as the Trace endpoint.

Would adding a default TraceRepository implementation that writes asynchronously to a log file be a good solution?

**Comment by wilkinsona** [comment]
Assuming that you're using Tomcat, you can enable its access log using `server.tomcat.access-log-enabled` and configure its pattern using `server.tomcat.access-log-pattern`. 1.3 adds more configuration for Tomcat's access log and also adds application.properties-based configuration for Undertow's access log.

**Comment by nodje** [comment]
Thanks for pointing this to me. 
For the record it has now become:```server.tomcat.accesslog.enabled```

I still feel an access log autoconfiguration would be a nice thing to have.
It could be Container dependent or not, extending TraceWebFilter, or provifing a default logback-access config. 
In any case it it would be a convenient abstraction. It could be enabled with a simple switch and one would not have to plan different config per container or profile.

**Comment by wilkinsona** [comment]
We already have an issue for auto-configuration of Logback Access: #2609
