### ISSUE TITLE
Typo in Spring Boot Docs Section 10.1 Custom HTTP Exchange Recording

### ISSUE THREAD

**Issue by raysuliteanu** [spring-projects/spring-boot#39768]
There's a typo in https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.http-exchanges.custom

"To disable recoding entirely"

"recoding" vs recording.

**Comment by wilkinsona** [comment]
Thanks, @raysuliteanu. Closing in favor of #39777.
