### ISSUE TITLE
请问一下，你们的发明在中国被申请了专利。

### ISSUE THREAD

**Issue by zzmm1** [spring-projects/spring-boot#39780]
![微信图片_20240228170128](https://github.com/spring-projects/spring-boot/assets/16304814/24b388e8-229b-42df-af4c-a4af4abd11c4)
![微信图片_20240228170132](https://github.com/spring-projects/spring-boot/assets/16304814/8a9c9d54-0ee1-4674-8ea2-5381a87f7118)

**Comment by wilkinsona** [comment]
A Google translation of the issue title:

> May I ask, your invention has been patented in China?

I'm not familiar with the patent process in China but, as far as I am aware, no one on the Spring Boot team has filed any Spring Boot-related patents in China.
