### ISSUE TITLE
Is it suite using spring boot making a common library and other application can import it in classpath

### ISSUE THREAD

**Issue by GrapeBaBa** [spring-projects/spring-boot#3978]
Hi team,

Now i want to develop a common mail service for our systems.
As we design, we want to develop a rabbitmq producer and consumer. On consumer side, we could develop and deploy a spring boot or spring cloud application, but on producer side we want to give a common mail client like the interface below and make a jar dependency for other system.
interface MailClient{
    ListentableFuture  send(Message message) ;
}
So this jar not need deploy separate and how can i do this?

**Comment by zhanhb** [comment]
you can upload to maven central repository

**Comment by GrapeBaBa** [comment]
Sorry, that is not what i mean. i see spring boot and spring cloud using many declarative method and seems must use a application class, but i just want a class reference and not need deploy. i do not know how to implement

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
