### ISSUE TITLE
Official support for Flyway 10

### ISSUE THREAD

**Issue by bekoenig** [spring-projects/spring-boot#39832]
Hey spring team,

Flyway 10 is an important milestone that [extremely narrows the gaps](https://documentation.red-gate.com/flyway/flyway-blog/the-flyway-engine-oss-open-source-software-and-redgate?_gl=1*yx7vrr*_ga*ODk1NTExNzguMTY4NzUwNDA1Mg..*_ga_X7VDRWRT4P*MTcwOTYyOTYzNC4xNi4wLjE3MDk2Mjk2MzQuNjAuMC4w) between the oss, community and teams edtions.

Which Spring version will Flyway 10 officially support?

Best greetings,
Ben

**Comment by bekoenig** [comment]
- What's the reason for the specific min version 3.1.6?
- When spring supports Flyway 10, why is Flyway 9 in the [dependency management](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project%2Fspring-boot-dependencies%2Fbuild.gradle#L380)?

**Comment by wilkinsona** [comment]
Our dependency upgrade policy dictates that we won't upgrade to a new minor or major version of a dependency in a maintenance release of Spring Boot. As a result, Spring Boot 3.1.x uses Flyway 9.16.x as this was the most recent version of Flyway that was available when Spring Boot 3.1.0 was released. Similarly, Spring Boot 3.2.x uses Flyway 9.22.x as this was the most recent version of Flyway that was available when Spring Boot 3.2.0 was released.

Perhaps you can try Flyway 10 with Spring Boot 3.2.x and let us know if you encounter any problems or limitations as others have already done (https://github.com/spring-projects/spring-boot/issues/38164, https://github.com/spring-projects/spring-boot/issues/39431).

**Comment by bekoenig** [comment]
So Spring 3.3 references Flyway 10 - right?

Thank you for your detailed explanation.

**Comment by wilkinsona** [comment]
No, not yet. Spring Boot 3.3 is the earliest release where Flyway 10 will be the default version. We'll have to see if we have time and if other priorities allow us to do the work.

**Comment by ehsansad** [comment]
Hello,

I am working with a spring application with the following lib versions

<spring.version>6.1.4</spring.version>
<spring-boot.version>3.2.3</spring-boot.version>
<postgresql.version>42.7.2</postgresql.version>
<flyway-core.version>10.8.1</flyway-core.version>

and I do have the postgresql.transactional.lock in a conf file,
flyway.postgresql.transactional.lock=false

but it still hangs on this script

> create index CONCURRENTLY if not exists job_type on job(type);
> create index CONCURRENTLY if not exists job_status on job(status);
> create index CONCURRENTLY if not exists job_xxx on job(xxx);
> create index CONCURRENTLY if not exists job_yyy on job(yyy);

I have also tried to put the property in the application.yaml file

> spring:
>     flyway:
>         postgresql:
>             transactional-lock: false

but it still hangs. Is there something I am missing here?

**Comment by philwebb** [comment]
@ehsansad I think you'll need to seek advice from the Flyway team. Spring Boot doesn't do much more than configure Flyway and initiate the database migration.
