### ISSUE TITLE
@ConfigurationProperties(prefix="application.id) is not working

### ISSUE THREAD

**Issue by mohit816** [spring-projects/spring-boot#39835]
I am using a gradle project 

Gradle version 4.8.1 
Spring boot version 2.0.3
STill i am not able to use this prefix feature in my local
Basically i am setting a map application.id.key1=value1,application.id.key2=value2

But i am not able to fetch this pls resolve this @spring-projects-issues @spring-contributor @spring-builds

**Comment by bclozel** [comment]
[Spring Boot 2.0.x is out of open source support](https://spring.io/projects/spring-boot#support), please upgrade to a supported version. If you manage to reproduce the issue with a supported version, please attach a minimal sample project here (as a zip or a link to a GitHub repository) and we'll have a look.

Thanks!
