### ISSUE TITLE
Add spring-security-data to spring-boot-starter-security

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#3984]
Hi, 

Can it be possible to add the spring-security-data to  spring-boot-starter-security POM? 

Thanks!

**Comment by zhanhb** [comment]
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SecurityDataConfiguration.java

**Comment by zhanhb** [comment]
I don't think so, security-data require spring-data such as spring-data-jpa, spring-data-mongo.

**Comment by wilkinsona** [comment]
There's no guarantee that someone using Spring Security will also be using Spring Data so I don't think it makes sense to include it in the security starter.
