### ISSUE TITLE
Spring Boot 3.2 automatically change log level during shutdown

### ISSUE THREAD

**Issue by subratadey03** [spring-projects/spring-boot#39847]
We recently upgraded springBoot version to 3.2, and Java 21 64 bit.    
We observed wired behaviour while shutting down spring boot application , log level automatically change INFO to ERROR, and we are not getting expected log messages.    

After so many research, we found there is a feature "automatic log level propagation".   

We have some important INFO messages that should appear during application off.   

We tried to disable with few properties like : 
management.tracing.enabled = false    
spring.main.log-shutdown-info = true   

But nothing help, it is still ERROR.   

We need INFO log level while spring boot application is shutting down.    
Please suggest and help what we can do to get INFO level at end of application.

**Comment by philwebb** [comment]
It looks like you have also posted this question at https://stackoverflow.com/questions/78118789/spring-boot-3-2-automatically-change-log-level-during-shutdown. So that we don't duplicate effort, I suggest we keep the conversion there until we are sure that this is actually a bug.
