### ISSUE TITLE
Using spring-boot-starter-redis dependency with JacksonJsonRedisSerializer<>

### ISSUE THREAD

**Issue by dgomesbr** [spring-projects/spring-boot#3985]
Hey guys,

Using the ```spring-boot-starter-redis``` in my pom.xml and trying to use this Configuration class leads me to a compile error in the 1.3.0.M5:

```java
@Configuration
public class RedisConfig {
    @Autowired
    private JedisConnectionFactory jedisConnFactory;

    @Bean
    public StringRedisSerializer stringRedisSerializer() {
        StringRedisSerializer stringRedisSerializer = new StringRedisSerializer();
        return stringRedisSerializer;
    }

    @Bean
    public JacksonJsonRedisSerializer<ShortenedURL> jacksonJsonRedisJsonSerializer() {
        return new JacksonJsonRedisSerializer<>(ShortenedURL.class);
    }

    @Bean
    public RedisTemplate<String, ShortenedURL> redisTemplate() {
        RedisTemplate<String, ShortenedURL> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(jedisConnFactory);
        redisTemplate.setKeySerializer(stringRedisSerializer());
        redisTemplate.setValueSerializer(jacksonJsonRedisJsonSerializer());
        return redisTemplate;
    }
}
```
The error is 
> Information:Using javac 1.8.0_05 to compile java sources
Information:java: Errors occurred while compiling module 'api'
Information:Module "api" was fully rebuilt due to project configuration/dependencies changes
Information:18/09/2015 17:05 - Compilation completed with 1 error and 0 warnings in 5s 216ms
\home\diegomagalhaes\dev\shortr\shortr-api\src\main\java\com\diegomagalhaes\shortr\configuration\RedisConfig.java
Error:(26, 16) java: cannot access org.codehaus.jackson.type.JavaType
  class file for org.codehaus.jackson.type.JavaType not found

The ```JacksonJsonRedisSerializer<ShortenedURL> ``` only works after adding the ```jackson-mapper-asl``` dependency to my pom.xml

**Comment by wilkinsona** [comment]
That's by design. Jackson is an optional dependency to allow people to use Spring Data Redis without it. If you do want to use the Jackson-related functionality that you should add Jackson to the classpath.

**Comment by dgomesbr** [comment]
Thank you, do we have that explicitly stated beside the note over Jackson
and o/x in the docs?

**Comment by wilkinsona** [comment]
I'm not sure. It's "documented" in that it's marked as optional in the pom.

I'd recommend checking the Spring Data Redis documentation and, if it's not mentioned, you may want to open a Spring Data Redis issue.

**Comment by dgomesbr** [comment]
Thanks again for the promptly response. I'll do that.

**Comment by dgomesbr** [comment]
Done, just for future ref if anyone needed: https://jira.spring.io/browse/DATAJPA-803
