### ISSUE TITLE
Remote Shell does not honor custom banner.txt

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3988]
> The CRaSH integration of Spring Boot in its "Remote Shell" project does not honor custom banner.txt. Whenever I have a custom banner.txt at classpath:banner.txt or more generally at the location pointed to by the system property "banner.location", I get that banner text when Spring boot application spools up.
But when I connect via SSH/telnet to CRaSH, it prints the default banner defined as a field in the class o.s.b.SpringBootBanner.
How can I configure the Remote Shell to use the custom banner, too?

From https://jira.spring.io/browse/SPR-13470

**Comment by Haybu** [comment]
what is the resolution to this issue? how to let Spring Boot "Remote Shell" to honor my custom banner.txt in the resource folder ?

**Comment by wilkinsona** [comment]
@Haybu This issue is still open

**Comment by cjstehno** [comment]
Not that this solves the problem, but there is a work-around. You can modify the banner for the shell in the manner described by the [Crash shell documentation](https://github.com/crashub/crash/blob/2801269c7e47bd6e243612654a74cee809d20959/doc/reference/src/main/asciidoc/developers.asciidoc), where it describes the `login.groovy` file. If you put a `login.groovy` file in the `commands` directory of your Boot application with something like this (pulled from the crash source):

```groovy
welcome = { ->
    def hostName;
    try {
        hostName = java.net.InetAddress.getLocalHost().getHostName();
    } catch (java.net.UnknownHostException ignore) {
        hostName = 'localhost';
    }
    return """\
   _____     ________                 _______    ____ ____
 .'     `.  |        `.             .'       `. |    |    | ${crash.context.version}
|    |    | |    |    |  .-------.  |    |    | |    |    |
|    |____| |    `   .' |   _|    |  .    '~_ ` |         |
|    |    | |    .   `.  .~'      | | `~_    `| |         |
|    |    | |    |    | |    |    | |    |    | |    |    |
 `._____.'  |____|____| `.________|  `._____.'  |____|____|
Follow and support the project on http://www.crashub.org
Welcome to $hostName + !
It is ${new Date()} now
""";
}

prompt = { ->
    return "% ";
}
```
It will override the default banner. I would think that it would not be difficult to access the `banner.txt` file on the classpath and display it here.

**Comment by cjstehno** [comment]
I found where this fix should be made and it seems pretty simple - I will go ahead and provide a fix pull request this week.

**Comment by snicoll** [comment]
Closing in favour of the PR #5453
