### ISSUE TITLE
Springboot version: 2.1.1.Is RELEASE compatible with Centos8.1

### ISSUE THREAD

**Issue by mingyi666** [spring-projects/spring-boot#39902]
For some reason, I need to upgrade Centos7.6 to version 8.1. May I ask if the original 2.1.1.RELEASE version of the springboot project is compatible with Centos8.1? If possible, please provide some document links to support my upgrade this time

**Comment by philwebb** [comment]
I'm afraid Spring Boot 2.1 is no longer supported.
