### ISSUE TITLE
SpringBoot 3.2 BaseStateMachineListener

### ISSUE THREAD

**Issue by subratadey03** [spring-projects/spring-boot#39905]
We recently upgraded springBoot version to 3.2, and Java 21 64 bit.    
We observed the LifecycleObjectSupport object log was output every time an Event was notified in Spring StateMachine.  
`2023/12/20,13:48:06.600 INFO [DeviceBroker ] [nio-8080-exec-7] mework.statemachine.support.LifecycleObjectSupport : stopped org.springframework.statemachine.support.DefaultStateMachineExecutor@7efa3f63 2023/12/20,13:48:06.600 INFO [DeviceBroker ] [nio-8080-exec-7] mework.statemachine.support.LifecycleObjectSupport : stopped ATTACHED / / uuid=da1c1d7d-7d54-4484-bf49-d224f7324a3e / id=null `  

Currently it says eventNotAccepted in BaseStateMachine.  
`WARN [DeviceBroker ] [nio-8080-exec-7] .device.base.statemachine.BaseStateMachineListener : [eventNotAccepted] Device- Cat event not accepted: GenericMessage [payload=CONNECT, headers={id=351edf7d-8504-39dc-29cd-973600fdba5a, timestamp=1708581146172}]`

This is warning message in the log also LifecycleObjectSupport object is not there now. 
We want to know the why and its impact .
is it expected in current version ?

**Comment by mhalbritter** [comment]
I don't think this has anything to do with Spring Boot. Please open an issue on the [statemachine tracker](https://github.com/spring-projects/spring-statemachine).
