### ISSUE TITLE
rsocket tcp cache

### ISSUE THREAD

**Issue by MrWangGang** [spring-projects/spring-boot#39917]
I'm using spring-boot-start-rsocket, but I'm quite concerned about it. I'm not sure if you have optimized it. Checking the source code is very tedious, so I'm planning to ask you directly. I'm sorry for taking up your time.

In the official rsocket-java documentation, when calling remote services with RSocket, they use .cache() to cache the connection.

Here's the official implementation:

```
return RSocketRequester.builder()
                        .rsocketFactory(factory -> factory.dataMimeType(MediaType.APPLICATION_CBOR_VALUE)
                                                          .frameDecoder(PayloadDecoder.ZERO_COPY))
                        .rsocketStrategies(builder.build())
                        .connectTcp(responderHost, responderPort)
                        .retry()
                        .cache();
```
Here's my implementation:

```
return setRSocketRequester(getBuilder(), securityStash)
                    .transports(loadBalanceTargets(serviceName), new RoundRobinLoadbalanceStrategy());
```
I retrieve the list of registered services from Nacos, and then use transports to make calls. Have you cached the connections at the underlying level? Because I'm using transports provided by you to make requests instead of using the native requests in rsocket-java. I'm not sure if you've encapsulated it. I think it's necessary to point this out in the documentation. Caching connections for cross-service calls is very useful.

**Comment by bclozel** [comment]
This code lives in rsocket-java as you have pointed out. Please [use the correct issue tracker](https://github.com/rsocket/rsocket-java/issues).
