### ISSUE TITLE
velocity template can't use "spring.velocity.charset"

### ISSUE THREAD

**Issue by niqiumao** [spring-projects/spring-boot#3993]
VelocityAutoConfiguration.java
right now the code is:
		protected void applyProperties(VelocityEngineFactory factory) {
			factory.setResourceLoaderPath(this.properties.getResourceLoaderPath());
			factory.setPreferFileSystemAccess(this.properties.isPreferFileSystemAccess());
			Properties velocityProperties = new Properties();
			velocityProperties.putAll(this.properties.getProperties());
			factory.setVelocityProperties(velocityProperties);
		}
After fix the code is: 

		protected void applyProperties(VelocityEngineFactory factory) {
			factory.setResourceLoaderPath(this.properties.getResourceLoaderPath());
			factory.setPreferFileSystemAccess(this.properties.isPreferFileSystemAccess());
                        factory.setDefaultEncoding(this.properties.getCharset());
			Properties velocityProperties = new Properties();
			velocityProperties.putAll(this.properties.getProperties());
			factory.setVelocityProperties(velocityProperties);
		}

added code:
  factory.setDefaultEncoding(this.properties.getCharset());

so that we can use the "spring.velocity.charset"

**Comment by snicoll** [comment]
Duplicates #3994
