### ISSUE TITLE
Spring Boot Native executable not logging (and then exiting immediately)

### ISSUE THREAD

**Issue by landbaychrisburrell** [spring-projects/spring-boot#39947]
Hi

My issue seems identical in symptoms to https://github.com/spring-attic/spring-native/issues/1654. 

* The executable builds fine
* When running, I have an immediate exit
* The exit code is 1
* There are NO logs at all.

I'd love to be able to provide some info on how to solve it. I've tried the following so far:
*  I tried deleting the logback-spring.xml file - but this made no difference in surfacing any root cause, nor in establishing logs
* I'm not using undertow - (using tomcat, with the standard versioning coming in from Spring Boot 3.2.3)

Versions:

```
java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

native-image 21.0.2 2024-01-16
GraalVM Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Substrate VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS, serial gc, compressed references)

Spring Boot 3.2.3
```

Seems to me there is at least one bug - the lack of logs. And then my app might be bringing other non-native compatible stuff (one for me)

How can I restore logs for this?

**Method of compiling**
* mvn clean install
* mvn spring-boot:build-image -Pnative
* (i've also simply tried mvn native:compile -Pnative) - the result is the saying in docker or direct to executable
* I have the two recommended plugins on the 'build' maven configuration
```
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
```

I would love to help identify why logs aren't spitting out - but not entirely sure where to go to help resolve this. (The app logs fine when i'm using non native mode)

**Comment by wilkinsona** [comment]
Please provide a minimal sample as [fragaLY](https://github.com/fragaLY) did in the Spring Native issue that you have linked to above.

**Comment by landbaychrisburrell** [comment]
Thanks - will do my best - it's a bit like hunting a needle in a haystack as it's a rather large app to trim down. Is it a possibility that logging is in fact working, but if it's non-blocking ( i assume it is) the app exits before std-out gets a chance to log?

**Comment by wilkinsona** [comment]
I would be surprised if that is the case as it isn't something, as far as I know, that we've seen before.

**Comment by landbaychrisburrell** [comment]
let's close it for now - as i will be picking this up again in mid-april
