### ISSUE TITLE
Spring Config does not use environment conversion service on resolved properties

### ISSUE THREAD

**Issue by burkedavison** [spring-projects/spring-boot#39944]
When [ConfigurationPropertySourcesPropertyResolver](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/source/ConfigurationPropertySourcesPropertyResolver.java#L74-L83) resolves a property, it calls [AbstractPropertyResolver.convertValueIfNecessary()](https://github.com/spring-projects/spring-framework/blob/6.1.x/spring-core/src/main/java/org/springframework/core/env/AbstractPropertyResolver.java#L252-L266) which uses a ConversionService to produce the target type. This allows types such as `com.google.protobuf.ByteString` to invoke a custom method such as `toStringUtf8` rather than `toString` to produce its `String` representation.

When [ConfigDataEnvironmentContributorPlaceholdersResolver](https://github.com/spring-projects/spring-boot/blob/2.4.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataEnvironmentContributorPlaceholdersResolver.java#L75) resolves a property, it calls `String.valueOf()` - bypassing any [registered converter](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v5.1.0/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerEnvironmentPostProcessor.java#L39-L47).

Original issue describing specific use case: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2690

Affects Spring Boot [2.4.x](https://github.com/spring-projects/spring-boot/blob/2.4.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataEnvironmentContributorPlaceholdersResolver.java#L75) - [3.2.x](https://github.com/spring-projects/spring-boot/blame/3.2.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataEnvironmentContributorPlaceholdersResolver.java#L80).

**Comment by philwebb** [comment]
We think this is a bug, however, we've had lots of issues in the past with the conversion service causing unexpected problems when we change things. We're specifically worried that someone might get an unwanted conversion.

We're going to try and fix this in 3.3 and see if it causes any problems for folks that upgrade. If it doesn't we can consider backporting the fix later.
