### ISSUE TITLE
Spring Boot 3.2.3: java.lang.NoClassDefFoundError: io/micrometer/registry/otlp/AggregationTemporality

### ISSUE THREAD

**Issue by viva-la-v** [spring-projects/spring-boot#39956]
Package of `AggregationTemporality` in `io.opentelemetry:opentelemetry-sdk-metrics:1.31.0` is changed from `io.micrometer.registry.otlp.AggregationTemporality` to `io.opentelemetry.sdk.metrics.data.AggregationTemporality` causing `NoClassDefFoundError` when using `OtlpProperties`.

Not sure since which version they changed it, in `spring-boot-dependencies-3.2.3.pom` the `opentelemetry.version` is `1.31.0` which is incompatible with the `OtlpProperties` in `spring-boot-actuator-autoconfigure:3.2.3`.

**Comment by philwebb** [comment]
There's an `AggregationTemporality` in both packages and it [should still be in Micrometer](https://github.com/micrometer-metrics/micrometer/blob/966f5fe953a69c315b44bf4f63adf101a060bbfb/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/AggregationTemporality.java). Please check you are using Micrometer 1.11 or above.

If you are, and you're still facing the problem then please provide a sample application that we can run and debug.

**Comment by glmapper** [comment]
I encountered the same problem. The Micrometer‘s version is 1.12.3, Spring Boot version is 3.2.3

**Comment by bclozel** [comment]
@glmapper this class is present in Micrometer 1.12.3, see https://github.com/micrometer-metrics/micrometer/blob/v1.12.3/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/AggregationTemporality.java

**Comment by glmapper** [comment]
@bclozel thanks，upgrade io.micrometer:micrometer-registry-otlp-1.9.0 to io.micrometer:micrometer-registry-otlp-1.12.3 , resolved~

**Comment by bclozel** [comment]
@glmapper I would advise not overriding library versions in your application unless you really need it. Leaving the Spring Boot dependency management do its work usually prevents such problems.
