### ISSUE TITLE
3.2.1 introduced undocumented Hibernate breaking changes

### ISSUE THREAD

**Issue by rbleuse** [spring-projects/spring-boot#39959]
Hi there,

3.2.0 included Hibernate 6.3 (since 3.2.0-M3) which was compatible with some old databases.
However, 3.2.1 upgraded to Hibernate 6.4 with https://github.com/spring-projects/spring-boot/issues/38870

Hibernate 6.4 introduced some breaking changes with their dialects, removing compatibility with old databases, cf https://hibernate.atlassian.net/browse/HHH-17089

We were able to upgrade successfully to Spring boot 3.2.0 with our MySQL 5.7 and using Hibernate 6 features (subselect queries), but can't upgrade to 3.2.1+ because generated subselect queries are now following MySQL 8 syntax which is not compatible with MySQL 5.7, unless we convert to manual native queries.

This update (6.3 to 6.4) is not mentioned as breaking change in this minor 3.2.1 release notes

If I want to upgrade to future 3.2.x, do you recommend to override Hibernate version to stick with the latest 6.3 ?

**Comment by bclozel** [comment]
Thanks for letting us know. I have updated [the release notes here for 3.2.1](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.1).

You won't be able to upgrade to the latest Hibernate 6.3 as there won't be any: official support has been dropped, see #38523. As a result Spring Data not Spring Boot will guarantee compatibility with this generation. This is unfortunately out of our control as we had no advance warning for this.
