### ISSUE TITLE
Management Security Settings are ignored

### ISSUE THREAD

**Issue by ChristianLohmann** [spring-projects/spring-boot#3997]
Setting the ```management.security.enabled``` to ```false``` seems to have no effect anymore. I also tried to set it on a specific endpoint like ```endpoints.health.sensitive=false```. Thus the actuator endpoints are always secured.
Maybe this behavior is affected by this one: https://github.com/spring-projects/spring-boot/issues/3888

Reproducible with Spring Boot ```1.3.0.M5``` including the ```actuator``` and ```spring-security``` starters.

**Comment by wilkinsona** [comment]
I can't recreate this with 1.3.0.M5 or the latest 1.3 snapshot. With `management.security.enabled` set to `false` I can access `http://localhost:8080/beans` without authenticating. @ChristianLohmann, can you please provide a sample project that reproduces the problem?

**Comment by wilkinsona** [comment]
I've just added two integration tests that verify the behaviour with and without management security enabled. Still no joy with reproducing the problem.

**Comment by wilkinsona** [comment]
Closing due to lack of response. If this is still a problem, please let us know and we can re-open the issue.
