### ISSUE TITLE
Runtime hint registration for property binding should not fail when parameter information is unavailable

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#40051]
On Spring Petclinic during a native build or a JVM one with the AOT plugin enabled, if I change the `pom.xml` to use `tomcat-jdbc` as following:
```xml
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.zaxxer</groupId>
          <artifactId>HikariCP</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-jdbc</artifactId>
    </dependency>
```
I get the following exception while building the application:
```
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
        org.apache.tomcat.jdbc.pool.PoolProperties$InterceptorProperty

        at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:100)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:74)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
```
Would be nice if the registrar would ignore failures due to a lack of parameter information.
Notice the application works fine without AOT involved.

**Comment by wilkinsona** [comment]
Test that reproduces the problem:

```java
@Test
void registerHintsDoesNotThrowWhenParameterInformationForConstructorBindingIsNotAvailable()
		throws NoSuchMethodException, SecurityException {
	Constructor<?> constructor = PoolProperties.InterceptorProperty.class.getConstructor(String.class, String.class);
	String[] parameterNames = new StandardReflectionParameterNameDiscoverer().getParameterNames(constructor);
	assertThat(parameterNames).isNull();
	assertThatNoException().isThrownBy(() -> registerHints(PoolProperties.class));
}
```

**Comment by mhalbritter** [comment]
The line which throws the exception has been added in https://github.com/spring-projects/spring-boot/issues/33182.

If we remove the exception, the build works, but the application still doesn't work on native, because without `-parameters` the `LocalVariableTableParameterNameDiscoverer` fallback is used (which doesn't work in a native image).

**Comment by wilkinsona** [comment]
@mhalbritter Can you share the failure? I'm not sure why we're trying to bind `org.apache.tomcat.jdbc.pool.PoolProperties$InterceptorProperty` at runtime. Hopefully the stack trace might shed some light on it.

**Comment by mhalbritter** [comment]
Oh sorry, that was not clearly phrased. I haven't tested it, just read through the history of #33182.

I've tested it, and indeed, the native image application works fine, even when using the `spring.datasource.tomcat` properties.

So this looks like a false positive of the early failure detection introduced in #33182.

**Comment by mhalbritter** [comment]
I have removed the exception.
