### ISSUE TITLE
Document CDS support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#40061]
With the Antora migration mostly done we might want to add some more documentation around CDS

**Comment by mhalbritter** [comment]
We're using the CDS friendly layout in our "Dockerfiles" doc by default now (see #40094).

**Comment by mhalbritter** [comment]
I've updated the "Efficient deployments" section.

**Comment by mhalbritter** [comment]
There are some bits missing. We could link to the [Spring Framework](https://docs.spring.io/spring-framework/reference/integration/cds.html) docs. And we could explain the CDS workflow: first, start the training run, then use the classes archive.

**Comment by mhalbritter** [comment]
Fixed by https://github.com/spring-projects/spring-boot/pull/40175.
