### ISSUE TITLE
JmxMetricWriter example in the docs doesn't work due to multiple MBeanExporter beans

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4007]
The [suggested bean definition](http://docs.spring.io/spring-boot/docs/1.3.0.M5/reference/htmlsingle/#production-ready-metric-writers-export-to-jmx
) is:

```java
@Bean
@ExportMetricWriter
MetricWriter metricWriter(MBeanExporter exporter) {
	return new JmxMetricWriter(exporter);
}
```

This fails as there are two `MBeanExporter` beans:

```
No qualifying bean of type [org.springframework.jmx.export.MBeanExporter] is defined: expected single matching bean but found 2: mbeanExporter,endpointMBeanExporter
```

There are two ways to avoid the problem:

 - Use `@Qualifier("mbeanExporter")`
 - Inject `AnnotationMBeanExporter`

Alternatively, we could update the bean definition for `mbeanExporter` to mark it as `@Primary`.

**Comment by snicoll** [comment]
Why do we have two mbean exporters in the first place?
