### ISSUE TITLE
Getting 500 instead of 404 with integration tests when updating from Spring Boot 3.1.x to to 3.2.4

### ISSUE THREAD

**Issue by lakshmipasupuleti** [spring-projects/spring-boot#40113]
Hi,

I have an integration test passing with Spring Boot (3.1.6) but when I use the latest version 3.2.4, it is failing with below error

Assertion error: Status expected:<404 NOT_FOUND> but was:<500 INTERNAL_SERVER_ERROR>

Sharing sample code below 

```java
@ExtendWith(SpringExtension.class)
@SpringBootTest
@EnableDevelopmentSecurityValidator
@AutoConfigureMockMvc
public class TestControllerIT{

      private WebTestClient testClient;
 public void getTestDetails(){
 testClient.get()
.uri(uriBuilder -> uriBuilder.path("/getUsers")
.queryParam ("id", 123)
.build())
.headers(xxx)
.exchange()
.expectStatus ()
.isNotFound();
   }
   }
```

_TestController.java_

```java
@RestController
@Validated
public class TestController{
@GetMapping(value="getEmployees")
Public Mono<Response entity<List<Employees>>> getEmployees(){
}
}
```

Can someone please check this issue and provide the fix for this issue?

Thanks,
Lakshmi

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by lakshmipasupuleti** [comment]
Sorry I can't share the code

**Comment by mhalbritter** [comment]
Unfortunately it's not possible to tell from the code above what's wrong. It could be [the changes in validation in Spring Framework](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-validation.html), e.g. something like this: https://github.com/spring-projects/spring-boot/issues/40055

But without code, we can't really tell.

We don't need the original code, just one example which passes with Boot 3.1 and fails with Boot 3.2.

**Comment by lakshmipasupuleti** [comment]
We haven't made any code changes, just updated spring boot from 3.1.x to 3.2.4

**Comment by bclozel** [comment]
Moritz already linked to related issues. If you're not willing to share a sample application we cannot justify spending the time trying to reproduce a behavior we have not seen. Very often code snippets are not enough and crucial information can be in other parts of the application.

We can reopen this issue once the requested sample is provided.

**Comment by lakshmipasupuleti** [comment]
Thanks for looking into it, I am able to resolve the issue with the help of the steps shared in below link
https://github.com/spring-projects/spring-boot/issues/38733
