### ISSUE TITLE
DataSource exception message seems misleading

### ISSUE THREAD

**Issue by jchesterpivotal** [spring-projects/spring-boot#4012]
This message:

> Cannot determine embedded database driver class for database type NONE. 
> If you want an embedded database please put a supported one on the classpath.

Is a bit misleading for us. In our project we use per-environment properties file, then inject an active profile as required (variously by OS environment and java opts). 

So if `SPRING_PROFILES_ACTIVE=foo`, we expect `application-foo.properties` will be used to configure the datasource.

When we make a mistake and don't inject the active profiles, we get the message shown above. The suggested cause is inaccurate in our case. What's missing is the configuration details of a non-embedded database.

Perhaps the message could be extended:

> Cannot determine embedded database driver class for database type NONE. 
> If you want an embedded database please put a supported one on the classpath.
> If you have expected database settings to be loaded from a particular profile, that profile might not be active. The active profiles are ...

Looks like the change would be in `DataSourceProperties`; we can see how to change the message text but are unsure of how to check for currently active profiles.

**Comment by philwebb** [comment]
:+1:

You can get active profiles using `Environment.getActiveProfiles()`.

**Comment by jchesterpivotal** [comment]
Thanks!

**Comment by sag7777** [comment]
how can i connect with rethinkdb?

**Comment by sag7777** [comment]
give me prperties file for rethinkdb

**Comment by snicoll** [comment]
@sag7777 we don't use the tracker for question and this issue is closed anyway. Please ask on StrackOverflow.
