### ISSUE TITLE
AutoConfigure RSAKey, JwtEncoder and JwtDecoder

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-boot#40138]
Hi,
  In the context of spring security, is it possible for spring boot to autoconfigure bean for RSAKey (default to RSA, 2048),  JwtEncoder (default to using RSAKey) and JwtDecoder (default to using RSAKey). 
This can really help to save time for the developer, instead of developer having to write these beans again and again.  Any overriding of default configuration can be done via configuration files

**Comment by philwebb** [comment]
Can you provide some more details of what you're looking for? We do already have some code in `OAuth2ResourceServerJwtConfiguration` which creates a `JwtDecoder`.

Perhaps you can provide a sample application with the type of configuration you usually create.

**Comment by philwebb** [comment]
@hannah23280,

We're discussing this again today and we wondered if you could provide a sample application that shows how you are currently configuring your beans. We want to make sure that we understand the use-case and that it will be broadly applicable.

**Comment by philwebb** [comment]
Thanks for the additional information. I'm not sure this pattern is generally applicable and something that will suit every application. As such, I don't think we'll be able to provide any auto-configuration ourselves for this.

If you're finding this pattern common in your own applications you could extract the code to your own auto-configuration module to make it easier to apply.

Thanks anyway for the suggestion.
