### ISSUE TITLE
Parent ApplicationContexts are not respected

### ISSUE THREAD

**Issue by tommack** [spring-projects/spring-boot#4014]
If you set a parent context with ``org.springframework.boot.builder.SpringApplicationBuilder#parent(org.springframework.context.ConfigurableApplicationContext)`` and startup as a WAR, beans from the parent context are not visible.

Directly adding ``ParentContextApplicationContextInitializer`` to the ``SpringApplicationBuilder`` fixes the problem.

Starting with Gradle's bootRun will not cause this problem to appear. 

My analysis:

``org.springframework.boot.builder.SpringApplicationBuilder#run`` has explicit code for adding the ``ParentContextApplicationContextInitializer``. When ``SpringBootServletInitializer`` is used, ``org.springframework.boot.builder.SpringApplicationBuilder#build`` is invoked immediately before any initializers are added.

**Comment by philwebb** [comment]
@tommack Do you by any chance have a project you could push to https://github.com/spring-projects/spring-boot-issues that shows the problem?

**Comment by tommack** [comment]
I can't upload the whole project, but the Main class looks something like this:

```
@SpringBootApplication(exclude = {SecurityAutoConfiguration.class, FreeMarkerAutoConfiguration.class})
public class Application extends SpringBootServletInitializer {

    private static ConfigurableApplicationContext getParentContext() {
        return ...
    }

   static SpringApplicationBuilder initializeBuilder(SpringApplicationBuilder springApplicationBuilder) {
        return springApplicationBuilder
                .parent(getParentContext())  // this does NOT work
                .sources(Application.class)
                .properties(CompanySpecificPropertySource.getProperties());
    }

    public static void main(String[] args) {
        try {
            initializeBuilder(new SpringApplicationBuilder()).run(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return super.configure(initializeBuilder(application));
    }

}

```

**Comment by wilkinsona** [comment]
There's a similar problem with `springApplicationBuilder.build().run()` vs `springApplicationBuilder.run()`. It's `SpringApplicationBuilder`'s run method that sets up the `ParentContextApplicationContextInitializer` and calling `build().run()` bypasses it.

**Comment by wilkinsona** [comment]
It feels like some of the logic that's in the builder ought to move into `SpringApplication`, however `SpringApplication` has no knowledge of its parent so I'm not sure how that would work.

Any ideas @philwebb @dsyer?

**Comment by dsyer** [comment]
Seems like a bug in the builder to me (`SpringApplication` intentionally knows nothing about parent contexts).
