### ISSUE TITLE
Add support for webjars-locator-lite

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#40146]
As a follow-up to https://github.com/spring-projects/spring-framework/issues/27619, when the related Spring Boot branch will be created, Spring Boot 3.4 should probably add support for `org.webjars:webjars-locator-lite` (`0.0.3` has been released at this time, but `1.0.0` will be shortly released, see https://github.com/spring-projects/spring-framework/issues/32564 and https://github.com/webjars/webjars-locator-lite/issues/1 related issues).

In practice, I think that would mean updating `ConditionalOnEnabledResourceChain` to detect webjars-locator-lite `org.webjars.WebJarVersionLocator`, and add dependency management for `org.webjars:webjars-locator-lite:1.0.0`.

Notice `org.webjars:webjars-locator-core` support is deprecated as of Spring Framework 6.2.

**Comment by sdeleuze** [comment]
FYI `org.webjars:webjars-locator-lite:1.0.0` has been released and will be used as a baseline as of Spring Framework `6.2.0-M2`.

**Comment by wilkinsona** [comment]
Thanks, @sdeleuze. Sounds like a good candidate for Boot 3.4.
