### ISSUE TITLE
Maven uses 'start-class' when the parent POM is being used and ignores 'spring-boot.run.main-class'

### ISSUE THREAD

**Issue by siddhsql** [spring-projects/spring-boot#40145]
I wrote a spring application with multiple main classes. When I try to run it as follows:

```
mvn spring-boot:run \
 -Dspring-boot.run.profiles=profile2 \
 -Dspring-boot.run.main-class=com.example.demo.DemoApplication2
```

I get this error:

```
Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:3.1.5:run failed: Unable to find a single main class from the following candidates [com.example.demo.DemoApplication2, com.example.demo.DemoApplication]
```

If I remove the following from my `pom.xml`:

```
<parent>	
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.1.5</version>
    <relativePath/> 
</parent>
```

then it works! seems like a bug.

**Comment by scottfrederick** [comment]
Thanks for getting in touch. Unfortunately, you have not provided enough information for us to be able to help you. If you would like us to spend some time investigating, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by codespearhead** [comment]
This is expected behavior since Spring Boot doesn't know which main class to run.

Try specifying which one you want to run [like this](https://www.baeldung.com/spring-boot-main-class#maven).

**Comment by siddhsql** [comment]
attached MRE as zipped file
[issue40145.zip](https://github.com/spring-projects/spring-boot/files/14829128/issue40145.zip)

If the correct flag is `-Dstart-class` then couple of questions wait to be begged:

1. Why is it not documented in official documentation? Official documentation says to use `-Dspring-boot.run.main-class` [[1](https://docs.spring.io/spring-boot/docs/3.2.4/maven-plugin/reference/htmlsingle/#run.run-goal.parameter-details.main-class)]

2. Why does the `-Dspring-boot.run.main-class` flag work when I don't use following in `pom.xml`:

```
<parent>	
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.4</version>
		<relativePath/> 
	</parent>
```

**Comment by codespearhead** [comment]
Upon closer inspection, you're right: you shouldn't have to resort to a JVM system property (`start-class`) when there's already an allegedly [setting for development convenience](https://docs.spring.io/spring-boot/docs/3.2.4/maven-plugin/reference/htmlsingle/#run.run-goal.parameter-details.main-class) (`spring-boot.run.main-class`).

However, here's what [Bael Dung has to say](https://www.baeldung.com/spring-boot-main-class#overview):

> A Spring Boot application’s main class is a class that contains a public static void main() method that starts up the Spring ApplicationContext. *By default, if the main class isn’t explicitly specified, Spring will search for one in the classpath at compile time and fail to start if none or multiple of them are found.*
> [...]
> Spring Boot expects the artifact’s Main-Class metadata property to be set to org.springframework.boot.loader.JarLauncher (or WarLauncher) which means that *passing our main class directly to the java command line won’t start our Spring Boot application correctly.*

Hence, I stand corrected: this is a bug in my opinion.

**Comment by philwebb** [comment]
This is an interesting problem and I'm not sure how to best solve it. Our `spring-boot-parent` POM configures a few plugins (including `spring-boot-maven-plugin`) to use a `${start-class}` variable. It seems that even if that variable isn't set, the act of configuring the plugin in the XML disables support for the `spring-boot.run.main-class` property.

We'll need to discuss this some more to work out what we should do.

**Comment by siddhsql** [comment]
It is surprising (and embarrassing - no offence) that a basic thing such as this is broken and there was no bug report on it.

**Comment by codespearhead** [comment]
That's the beauty of open source: you get feedback that you otherwise probably wouldn't.

This bug hasn't been caught for so long because you're structuring your project in a non-conventional multi-module way.

That isn't to say that it's wrong: it simply flew under the radar because few have chosen this approach and thus, it's less likely they've encountered this bug and have decided to report it.

**Comment by mhalbritter** [comment]
If we add this in our parent:

```xml
    <properties>
        <spring-boot.run.main-class>${start-class}</spring-boot.run.main-class>
    </properties>
```

and then change the config of the `spring-boot-maven-plugin` in the parent:

```xml
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${spring-boot.run.main-class}</mainClass>
                </configuration>
            </plugin>
```

then both `start-class` and `spring-boot.run.main-class` would work.

**Comment by philwebb** [comment]
The other plugins we configure with `${start-class}` are:

* maven-jar-plugin
* maven-war-plugin
* maven-shade-plugin

I don't think any of those have `-D` properties that the user can set. Given that, I think we should try the approach @mhalbritter suggests above. Since it's a little risky, and there is a work-around, we'll do this in 3.3.x.
