### ISSUE TITLE
Missing configuration meatada

### ISSUE THREAD

**Issue by jakub-bochenski** [spring-projects/spring-boot#40151]
The following configuration properties are reported by IDEA as unresolved.
I can't find them in the metadata of relevant jar files.

```
spring.cloud.stream.default.binder
spring.cloud.stream.default.group
spring.cloud.stream.default.content-type
spring.cloud.stream.default.consumer.concurrency
```
spring-cloud-stream:3.2.9

```
management.endpoint.env.show-values
management.endpoint.configprops.show-values
```
spring-boot-actuator-autoconfigure-2.7.15

**Comment by scottfrederick** [comment]
The `spring.cloud.stream` properties are managed by the [Spring Cloud Stream](https://spring.io/projects/spring-cloud-stream) project, not by Spring Boot. Please see the Spring Cloud Steam documentation and report any issues to that project. 

The `show-values` properties under `management.endpoint.env` and `management.endpoint.configprops` were [added in Spring Boot 3.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-endpoints-sanitization), so they are not valid in a Spring Boot 2.7.15 project.
