### ISSUE TITLE
Means to override managed Spring Data release train

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#4016]
I'm trying to upgrade my project to Gosling, and no matter what I do, I can't get Spring Boot's import POM to let go of version management for Spring Data. I've tried overriding the `spring-data-releasetrain.version` property, importing `spring-data-releasetrain` explicitly both before and after `spring-boot-dependencies`, and even

```
            <!-- Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.data</groupId>
                        <artifactId>spring-data-releasetrain</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Spring Data -->
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-releasetrain</artifactId>
                <version>${spring-data-releasetrain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

No matter what I do, the Spring Data dependencies stay stuck on Evans-SR3. I can only get around the problem by introducing an intermediate POM, importing Spring Boot from the top-level, and importing Spring Data at the intermediate level.

**Comment by wilkinsona** [comment]
You can't override a property in an imported pom, property overrides only work for inherited poms. If you're importing then importing the Spring Data release train bom before Spring Boot's bom should work.

**Comment by wilkinsona** [comment]
This works for me:

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-releasetrain</artifactId>
			<version>Gosling-RELEASE</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-dependencies</artifactId>
			<version>1.2.5.RELEASE</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

**Comment by chrylis** [comment]
I tried that exact arrangement, and I am still getting Evans-SR3. As described, importing Gosling in an intermediate parent POM works, but then when I pull in an artifact built with and depending on Gosling (`domain`) into another project (`controllers`) as an ordinary dependency, my dependency tree from `controllers` shows that it's attaching Evans to `domain`.

This looks very much like a Maven bug, if I can manage to replicate it, but in the meantime I haven't been able to work around with anything short of a bracketed `<version>[1.8.0.RELEASE]</version>` and equivalent in *every* leaf POM that's sensitive to the version.

**Comment by chrylis** [comment]
I can reproduce the problem, but not reliably. It appears to be a combination of some bug in the Maven graph algorithm and a bug in that Maven permits but does not respect exclusions applied to import POMs. Still no clean workaround.
