### ISSUE TITLE
Readd Jolokia dependency management

### ISSUE THREAD

**Issue by nhmarujo** [spring-projects/spring-boot#40183]
Since Jolokia is already working with Jakarta for some time now, it would be good to have Spring managing its version back again.

The mentioned dependency is:
```xml
<dependency>
          <groupId>org.jolokia</groupId>
          <artifactId>jolokia-support-spring</artifactId>
          <version>${jolokia.version}</version>
</dependency>
```

More details in:
https://jolokia.org/reference/html/manual/spring.html

**Comment by wilkinsona** [comment]
There's more to it than just re-instating the dependency management as, generally speaking, we only manage dependencies upon which Spring Boot depends. https://github.com/spring-projects/spring-boot/issues/37568, which I have just re-opened, is tracking reinstating support for Jolokia.

**Comment by nhmarujo** [comment]
Thank you for the clarification @wilkinsona . I totally understand the reasoning to leave it out of the dependency management. Thank you
