### ISSUE TITLE
Update JOOQ documentation to explain the compatibility  between Spring and JOOQ

### ISSUE THREAD

**Issue by debraj-manna** [spring-projects/spring-boot#40180]
`spring-kafka` [documentation](https://spring.io/projects/spring-kafka) calls out the compatibility between Spring and Kafka Clients. 

Is it possible to update `spring-jooq` [documentation](https://docs.spring.io/spring-boot/docs/1.3.5.RELEASE/reference/html/boot-features-jooq.html) similarly to explain the compatibility?  

I asked the same question about Spring and JOOQ compatibility in [JOOQ user group](https://groups.google.com/g/jooq-user/c/ImmztL8qBQQ/m/KprFVCfQAgAJ). I was asked to discuss this in the Spring community which makes sense also.

**Comment by wilkinsona** [comment]
We list our managed versions in [an appendix of the reference documentation](https://docs.spring.io/spring-boot/docs/3.1.x/reference/html/dependency-versions.html#appendix.dependency-versions). You should be able to safely assume that any patch version of jOOQ that's in the same minor generation will be compatible. Upgrading or downgrading to a different minor hasn't been tested and may or may not work depending on jOOQ's forwards and backwards compatibility.
