### ISSUE TITLE
Support generating CDS-Based image

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#40190]
see https://docs.spring.io/spring-framework/reference/integration/cds.html
>> Class Data Sharing (CDS) is a [JVM feature](https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html) that can help reduce the startup time and memory footprint of Java applications.

Compare to CRaC, CDS is more compatible.

**Comment by bclozel** [comment]
Duplicates #39834 and #40061

**Comment by bclozel** [comment]
Can you elaborate on what's missing?

**Comment by quaff** [comment]
> Can you elaborate on what's missing?

The two issues you linked didn't mention generating OCI image, I guess that developers need build their own CDS-Based image base on Spring Boot generated CDS-Friendly image, am I right?

**Comment by bclozel** [comment]
I guess you're looking for buildpack support here - [this is covered by the buildpack project](https://github.com/paketo-buildpacks/spring-boot/issues/423).

**Comment by quaff** [comment]
> I guess you're looking for buildpack support here - [this is covered by the buildpack project](https://github.com/paketo-buildpacks/spring-boot/issues/423).

Exactly, thanks for the link.
