### ISSUE TITLE
[actuator/metrics/export/otlp] Support configuring export step

### ISSUE THREAD

**Issue by ZIRAKrezovic** [spring-projects/spring-boot#40194]
I would like to configure "step" property of `io.micrometer.core.instrument.push.PushRegistryConfig` using `org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpPropertiesConfigAdapter` and `management.otlp.metrics.export` property hierarchy.

Current default is 1 minute and is not customizable.

**Comment by wilkinsona** [comment]
You can use [`management.otlp.metrics.export.step`](https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#application-properties.actuator.management.otlp.metrics.export.step) for this purpose.
