### ISSUE TITLE
Why did the spring data project in springboot 2.7.18 abandon support for the Influxdb database

### ISSUE THREAD

**Issue by 18236098539** [spring-projects/spring-boot#40220]
In the Internet of Things industry, we often use InfluxDB and MongoDB databases. Why did the official Spring Boot data project provide other databases and abandon support for InfluxDB databases I hope to support both the 2. x and boot3 versions of the InfluxDB database

**Comment by mdeinum** [comment]
See https://github.com/spring-projects/spring-boot/issues/35190

**Comment by wilkinsona** [comment]
Thanks, @mdeinum.
