### ISSUE TITLE
Support for adding multiple JNDI datasources (or JNDI resources in general)

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#4023]
When using a plain configured {{DataSource}} it is quite easy to create multiple different instances using the `{{DataSourceBuilder}} and as explained in the [documentation](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-two-datasources).

Would be nice if a similar helper class/bean would be available for JNDI based datasources (or JNDI resources in general ? ). 

Something along the lines of 

    @Bean
    @Primary
    @ConfigurationProperties(prefix="datasource.primary")
    public DataSource primaryDataSource() {
        return JndiDataSourceBuilder.create().build();
    }

    @Bean
    @ConfigurationProperties(prefix="datasource.secondary")
    public DataSource secondaryDataSource() {
        return JndiDataSourceBuilder.create().build();
    }

And of course a `datasource.secondary.jndi-name=jdbc/one` etc. in the configuration somewhere.

See http://stackoverflow.com/questions/32776410/configure-mutiple-datasource-in-spring-boot-with-jndi

**Comment by wilkinsona** [comment]
Why not bind `@ConfigurationProperties` to a `JndiObjectFactoryBean`?

**Comment by mdeinum** [comment]
Why didn't I think of that, that should work I guess.

**Comment by mdeinum** [comment]
That works, might be worth a mention in the reference guide.
