### ISSUE TITLE
spring-boot spring-security thymeleaf, authentication returns null on error pages

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#4024]
Authentication is null on error pages like 404 not found.
sample issue:
https://github.com/zhanhb/authentication-returns-null

**Comment by zhanhb** [comment]
I searched on stackover and found http://stackoverflow.com/questions/6305801/spring-securitycontext-returning-null-authentication-on-error-pages
There is not a way to configure security dispatcher type with spring-boot.

**Comment by php-coder** [comment]
Have a look at #1048 Is it the same problem?

**Comment by wilkinsona** [comment]
@php-coder Well spotted. Thanks

@zhanhb Please see #1048, in particular [this comment](https://github.com/spring-projects/spring-boot/issues/1048#issuecomment-102456237) which shows how to configure the dispatcher type for the security filter.

**Comment by zhanhb** [comment]
Thanks
