### ISSUE TITLE
Provide option to re-enable log4j2 JMX support when they disable it by default

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-boot#40273]
```kotlin
configurations {
  implementation {
    exclude(module = "spring-boot-starter-logging")
  }
}

dependencies {
  implementation("org.springframework.boot:spring-boot-starter")
  implementation("org.springframework.boot:spring-boot-starter-log4j2")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
}
```

```java
package com.example.demo;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jmx.support.MBeanServerFactoryBean;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
class DemoApplicationTests {

  @Test
  void contextLoads() {
    var factory = new MBeanServerFactoryBean();
    factory.setLocateExistingServerIfPossible(true);
    factory.afterPropertiesSet();
    var server = factory.getObject();
    assertThat(server.getDomains()).doesNotContain("org.apache.logging.log4j2"); // fails
  }
}
```

> JMX support is enabled by default.

https://logging.apache.org/log4j/2.x/manual/jmx.html#enabling-jmx

## Related

[Spring Boot - Disable JMX by default](https://github.com/spring-projects/spring-boot/issues/16090)

[JUnit 5 - Disable Log4J JMX beans creation in tests](https://github.com/junit-team/junit5/pull/3753#issuecomment-2045573225)

---

Ideally the auto-configuration would set `log4j2.disableJmx=true` if `spring.jmx.enabled=false` thereby no _log4j2_ JMX beans would be created.

Alternatively, the `log4j2.disableJmx` property should be mentioned in at least these two places:

- [Log4j2 System Properties](https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.log4j2-extensions.environment-property-source)
- [Monitoring and Management over JMX](https://docs.spring.io/spring-boot/reference/actuator/jmx.html)

**Comment by philwebb** [comment]
I think we might want to do something here, but I'm not sure we should tie things with `spring.jmx.enabled` since that property is really supposed to turn off Spring specific JXM features.

I wonder if we should wait to see how https://github.com/apache/logging-log4j2/issues/1229 plays out. If Log4J flip the default then we might be able to provide a quick way to turn it back on for users that need it.

**Comment by wilkinsona** [comment]
Log4j2 has flipped the default so we can consider an option to flip it back as and when we upgrade to a version with the change. That said, I learned from https://github.com/apache/logging-log4j2/pull/2468#pullrequestreview-1999738929 that Log4j 3.0 won't have any JMX support at all so I wonder if this is really worth it. The `log4j2.disableJmx=false` system property will be available irrespective of what we do here.

**Comment by sdavids** [comment]
I suggest having no code changes but a documentation improvement.

---

https://docs.spring.io/spring-boot/reference/actuator/jmx.html

Add something along the lines of:

```asciidoc
[NOTE]
====
`spring.jmx.enabled` affects only the management beans provided by Spring Boot.

The enablement of management beans provided by other frameworks, e.g. https://logging.apache.org/log4j/2.x/manual/jmx.html[Log4j2], https://www.quartz-scheduler.org/api/2.3.0/constant-values.html#org.quartz.impl.StdSchedulerFactory.PROP_SCHED_JMX_EXPORT[Quartz], or https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/appendices/Configurations.html#configurations-jmx[Hibernate], is independent.
====
```

---

https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.jmx.enabled

> Expose management beans to the JMX domain.

⇓

> Expose Spring Boot's management beans to the JMX domain.

**Comment by ppkarwasz** [comment]
@wilkinsona,

> Log4j2 has flipped the default so we can consider an option to flip it back as and when we upgrade to a version with the change. That said, I learned from [apache/logging-log4j2#2468 (review)](https://github.com/apache/logging-log4j2/pull/2468#pullrequestreview-1999738929) that Log4j 3.0 won't have any JMX support at all so I wonder if this is really worth it. The `log4j2.disableJmx=false` system property will be available irrespective of what we do here.

I think it would make sense for a Spring Application to use `!spring.jmx.enabled` as default value for `log4j2.disableJmx` regardless of the version of Log4j Core used. Adding the appropriate logic to [`SpringEnvironmentPropertySource`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/log4j2/SpringEnvironmentPropertySource.java) should be enough to accomplish this.

There are not many users that use Log4j JMX, there are probably even less users that enable JMX in Log4j, but not in Spring Boot, so it might even be safe to do it in a patch release.

**Comment by sdavids** [comment]
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.0

> Starting in version 2.24.0, JMX support is disabled by default [...]

**Comment by philwebb** [comment]
We discussed this today and given that JMX support will be dropped in Log4j 3.0 we don't think we should add support directly in Spring Boot. We want to keep `spring.jmx.enabled` specifically for Spring code. If folks want to enable Log4j JMX support they can use the standard Log4j configuration to do so.

**Comment by sdavids** [comment]
What about the documentation change?

https://github.com/spring-projects/spring-boot/issues/40273#issuecomment-2061212964

**Comment by philwebb** [comment]
Thanks @sdavids, I somehow missed that comment. I've opened #42272 to deal with that.
