### ISSUE TITLE
spring-boot-starter-data-mongodb not working in library

### ISSUE THREAD

**Issue by mrguzzi** [spring-projects/spring-boot#40292]
hello,
I created a spring structure made of Service, Repository and Entities annotated with lombok.
If I put the entire package in a java project using Helidon it's working correctly.
If I put it in a separate package it's giving the following error:

javax.enterprise.inject.UnsatisfiedResolutionException: Unable to resolve a bean for 'org.springframework.data.mongodb.core.MongoOperations' with qualifiers [@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()].
		at org.springframework.data.mongodb.repository.cdi.MongoRepositoryExtension.createRepositoryBean(MongoRepositoryExtension.java:111)

I'm using spring-boot-starter-data-mongodb  2.7.18, mongodb-driver-sync 4.6.1, jdk 13

I searched already stackoverflow and there are no cases like this.

**Comment by bclozel** [comment]
I'm sorry but [Spring Boot 2.7 is out of OSS support](https://spring.io/projects/spring-boot#support) and we have no Helidon expertise unfortunately. I think your best bet is to ask on StackOverflow.
