### ISSUE TITLE
Provide an alternative to javadoc for documenting configuration properties

### ISSUE THREAD

**Issue by vab2048** [spring-projects/spring-boot#40315]
The article [here](https://www.baeldung.com/spring-boot-configuration-metadata) gives an illustration of providing javadoc comments on fields to have the generated configuration metadata JSON file include a description. Example of code snippet:

```java
public static class Server {

    /**
     * The IP of the database server
     */
    private String ip;

    /**
     * The Port of the database server.
     * The Default value is 443.
     * The allowed values are in the range 400-4000.
     */
    @Min(400)
    @Max(800)
    private int port = 443;

    // standard getters and setters
}
```

I would like to be able to provide the description using an annotation (which points to a static final string/inline string):

```java
public static class Server {
   @Description("some string") private String ip;
   // rest of code
}
``` 

Is this currently possible? If not then I would like to ask for it to be added as an enhancement.

**Comment by wilkinsona** [comment]
What's the motivation here? What benefit will you get from using an annotation rather than javadoc? Note that you can already [provide descriptions in an additional metadata file](https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/configuration-metadata.html#appendix.configuration-metadata.annotation-processor.adding-additional-metadata).

**Comment by vab2048** [comment]
I have libraries which have a non spring core and then spring boot starters which wrap those libraries.

Within the libraries each property has a static string variable which provides a description. I would like to have the annotation point to that static string so that the description can be reused rather than copied and pasted into javadoc

**Comment by philwebb** [comment]
Thanks for the additional context @vab2048. This specific use-case feels quite unique and it's unlikely we'd be able to invest in developing such a feature ourselves. I wonder if you could develop your own annotation processor to generate the metadata file directly. You can find details of the metadata format [in our docs](https://docs.spring.io/spring-boot/docs/3.2.x/reference/htmlsingle/#appendix.configuration-metadata). Our [existing code](https://github.com/spring-projects/spring-boot/tree/3.2.x/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor) might also provide a useful reference.

Thanks anyway for the suggestion.

**Comment by vab2048** [comment]
Would a PR for this feature be accepted?

**Comment by philwebb** [comment]
@vab2048 It's hard to say for sure, but I don't think we'd particularly want to take on the maintenance burden.

**Comment by wilkinsona** [comment]
I agree with Phil. It's not so much the initial development effort that's the problem but the ongoing maintenance burden. The additional complexity would also have a lasting effect for both maintainers and users.
