### ISSUE TITLE
Consider mentioning OpenTelemetry Spring Boot starter in reference manual

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#40340]
It would be helpful if [_OpenTelemetry Support_](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.observability.opentelemetry) section of reference manual would mention OpenTelemetry's own Spring Boot starter (see https://github.com/spring-projects/spring-boot/pull/40339) as another way of configuring OpenTelemetry in Spring Boot applications as it has several advantages:
- provides instrumentation support for [large number of popular libraries](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks)
- makes it easier to use the latest version of OpenTelemetry
- doesn't require Actuator

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This isn't the sort of thing that we typically include in the reference documentation, preferring to focus on what Boot itself offers. The list of third-party starters is the right place for this.
