### ISSUE TITLE
@SpringApplicationConfiguration does not work in Spock test M5

### ISSUE THREAD

**Issue by madorb** [spring-projects/spring-boot#4039]
My Spock integration tests are no longer working after upgrading from M3 to M5. 

When I run them I get the exception:
```
org.springframework.core.annotation.AnnotationConfigurationException: In AnnotationAttributes for annotation [org.springframework.test.context.ContextConfiguration] declared on [class com.my.package.integration.AnIntegrationTest], attribute [locations] and its alias [value] are declared with values of [{}] and [{class com.my.package.Application}], but only one declaration is permitted.
```
the tests look like:

```
@SpringApplicationConfiguration(Application.class)
@ActiveProfiles(profiles=["ci"])
@WebIntegrationTest(randomPort=true)
@Slf4j
class AnIntegrationTest extends Specification{...}
```

I tried it both with and without `locations=` and it fails the same way in either case. 

In the meantime i had to revert to:

```@ContextConfiguration(loader = SpringApplicationContextLoader.class, classes = Application.class)```

for my tests to execute successfully

**Comment by madorb** [comment]
I don't know that this is specifically spock related though. This fellow mentions the same issue: http://codegur.com/32742344/contextconfiguration-annotation-exception

**Comment by philwebb** [comment]
@madorb Can you try with the latest SNAPSHOT (and make sure you are using Spring Framework 4.2.2 SNAPSHOT as well). I think you might be hitting [SPR-13345](https://jira.spring.io/browse/SPR-13345) but I though that was fixed before M5 was released.

**Comment by sbrannen** [comment]
The exception you are seeing was addressed in Spring Framework 4.2.1, specifically in the following issues:

- https://jira.spring.io/browse/SPR-13325
- https://jira.spring.io/browse/SPR-13345

And Spring Boot 1.3.0 M5 **requires** Spring Framework 4.2.1.

Thus, ensuring that you are running against Spring Framework 4.2.1 should resolve your problem.

Regards,

Sam

**Comment by madorb** [comment]
@philwebb @sbrannen thanks for the feedback, you're correct, using Spring 4.2.1 resolves the issue

**Comment by sbrannen** [comment]
@madorb, you're welcome, and thanks for letting us know that 4.2.1 solves your issue!

**Comment by wilkinsona** [comment]
@madorb I'd recommend not specifying the version of any Spring Framework dependencies in your `build.gradle` or `pom.xml` and letting Boot's dependency management take care of it for you. It's a nice way to avoid problems like this and know that you're running on a combination of versions that's been thoroughly tested.
