### ISSUE TITLE
Remote restart doesn't appear to work with jar archives

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4040]
Issue #3086 should have made remote restart work with jars, but this doesn't appear to be the case.

**Comment by philwebb** [comment]
Possible fix, needs more testing https://github.com/philwebb/spring-boot/tree/gh-4040

**Comment by snicoll** [comment]
What's the symptom on the client? Our SpringOne demo got a 404 but I got it working (with the same spring boot version) several times during the dry run.

**Comment by wilkinsona** [comment]
Assigning this to Phil as he has a possible fix

**Comment by snicoll** [comment]
Yes, please :)

**Comment by snicoll** [comment]
@philwebb I did test your branch with a rebase of current master and it's working for me now. If we could have this merged for RC1 that would be great!
