### ISSUE TITLE
Spring boot 2.7.1 .RELEASE is not deleting TMP file (upload_xx)  from the location user/appData/local/temp automatically

### ISSUE THREAD

**Issue by chethana-nisha** [spring-projects/spring-boot#40419]
I am using spring boot 2.7.1 release and embedded tomcat is 9.0.64

in our application we are uploading the multipart files and file size is high (we have set multipart.max.size = 5GB)
we are uploading large number of multipart files to the springboot

when the  files are uploaded and temp folder keep on growing which is  causing memory  issue.

Note: 
as of now not in the position to upgrade the spring boot version please provide the solution without upgrading to version

thanks in advance.

**Comment by knoobie** [comment]
> please provide the solution without upgrading to version

"End of Support" https://spring.io/projects/spring-boot

**Comment by chethana-nisha** [comment]
"End of Support" https://spring.io/projects/spring-boot

means what??

**Comment by bclozel** [comment]
This means that the [2.7.x generation is now out of open source support](https://spring.io/projects/spring-boot#support). If you can reproduce the problem with a supported Spring Boot version, please provide a minimal sample application that reproduces the problem and we will investigate. In the meantime, I'm closing this issue.
