### ISSUE TITLE
build native image using Paketo Buildpack for Bellsoft Liberica 10.7.0 (which has JDK 22 support) instead of current 10.5.5

### ISSUE THREAD

**Issue by KafkaProServerless** [spring-projects/spring-boot#40438]
Hello SpringBoot team,

Taking the latest just released Springboot 3.2.5 with the latest JDK22, to build a native image will fail, because the springboot maven plugin will by default use Paketo Buildpack for Bellsoft Liberica 10.5.5

Instead, can we upgrade so it uses the latest https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v10.7.0 which was just released couple of hours ago? This has JDK 22 support.

Thank you

**Comment by wilkinsona** [comment]
As with https://github.com/spring-projects/spring-boot/issues/40420, it's the builder that controls the buildpacks that are used. We're already using `paketobuildpacks/builder-jammy-tiny:latest`. I imagine that it will be updated in due course to use a more-recent version of the bellsoft-liberica buildpack.
