### ISSUE TITLE
Environment variable not bound

### ISSUE THREAD

**Issue by jgoelen** [spring-projects/spring-boot#4045]
Since Spring Boot `v1.2.6.RELEASE` the binding of environment variables behaves differently.
The properties of a class with an `@ConfigurationProperties` annotation are not set when combining a YAML file and OS environment variables. The following github repo contains a unit test to reproduce the problem:

https://github.com/jgoelen/spring-boot-env-bug

The test works fine with version 1.2.5.RELEASE (repo tag v1.2.5.RELEASE)

**Comment by philwebb** [comment]
@jgoelen How do I get the tests to fail? Checkout master and `mvn clean package` seems to work fine for me.

**Comment by philwebb** [comment]
Wait, never mind. Master was also on 1.2.5.RELEASE. Upgraded the POM and it failed.

**Comment by philwebb** [comment]
I bit of `git bisect` seems to show 1abd0879cab4aeadffa4687666120c9512fa8ccd is the culprit.

**Comment by philwebb** [comment]
See #3385

**Comment by philwebb** [comment]
Unit test to replicate in `PropertiesConfigurationFactoryTests`:

```java
	@Test
	public void testBindWithDashPrefix() throws Exception {
		// gh-4045
		this.targetName = "foo-bar";
		MutablePropertySources propertySources = new MutablePropertySources();
		propertySources.addLast(new SystemEnvironmentPropertySource("systemEnvironment",
				Collections.<String, Object>singletonMap("FOO_BAR_NAME", "blah")));
		propertySources.addLast(new RandomValuePropertySource("random"));
		setupFactory();
		this.factory.setPropertySources(propertySources);
		this.factory.afterPropertiesSet();
		Foo foo = this.factory.getObject();
		assertEquals("blah", foo.name);
	}
```

**Comment by philwebb** [comment]
This one turned out to be very hard to track down. Thanks for ruining my morning :)

If you have a chance should you try the `1.2.7.BUILD-SNAPSHOT` version (once CI build [BOOT-PUB3-125](https://build.spring.io/browse/BOOT-PUB3-125) finishes).

**Comment by jgoelen** [comment]
It works! Thanks for the fix.

**Comment by philwebb** [comment]
Thanks for testing.
