### ISSUE TITLE
Add configuration key spring.rabbitmq.template.json-trusted-packages

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#40459]
If the key present, then construct `Jackson2JsonMessageConverter` instead of default `SimpleMessageConverter`.

**Comment by philwebb** [comment]
I'm not sure we should add a property for this. I think it's a little confusing that setting `json-trusted-packages` would change the `MessageConverter`. I also think it's generally best if code related settings such as package names stay in code.

Let's see what the rest of the team things, but I think I'm in favor of declaring a `Jackson2JsonMessageConverter` `@Bean` for trusted packages.

**Comment by mhalbritter** [comment]
I agree with Phil. Setting `json-trusted-packages` which behind the scenes switches the converter implementation is too much "magic" for me.

**Comment by philwebb** [comment]
I think we have consensus. Thanks anyway for the suggestion @quaff.
