### ISSUE TITLE
Consider delaying Jackson 2.17.0 upgrade in Spring Boot 3.3.0

### ISSUE THREAD

**Issue by zerda** [spring-projects/spring-boot#40489]
The `LockFreePool` which was the default `RecyclerPool` implementation in Jackson 2.17.0, has been found to have performance issues. https://github.com/FasterXML/jackson-core/issues/1260

This was addressed in the upcoming version 2.17.1, where the default implementation was reverted back to `threadLocalPool()`. https://github.com/FasterXML/jackson-core/issues/1260

In the context of Spring Boot, there was an upgrade to Jackson 2.17.0 in the commit https://github.com/spring-projects/spring-boot/commit/437c654af0b2b0f8890369699d6669842d20d99b. However, considering the performance issues with the `LockFreePool` implementation in Jackson 2.17.0, it might be advisable to delay this upgrade unless there are strict requirements. @wilkinsona

**Comment by cowtowncoder** [comment]
Yeah I am planning to do 2.17.1 release soon enough, hopefully next week. And definitely before 23 May.

**Comment by cowtowncoder** [comment]
Jackson 2.17.1 is now released; release notes:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.17.1

(Scala module still to be released; all other modules done, available from Maven Central)

**Comment by wilkinsona** [comment]
Thanks very much, @cowtowncoder.
