### ISSUE TITLE
Migrating from SpringBoot 2.7.1 to 3.2.3 but Lombok @SuperBuilder is not working getting error: cannot find symbol

### ISSUE THREAD

**Issue by gbhambale5143** [spring-projects/spring-boot#40502]
Hi Team,
I am migrating from SpringBoot 2.7.1 to 3.2.3 but Lombok `@SuperBuilder` is not working getting below error.

```
cannot find symbol.
private void fillInUserReportFields(UserReport.**UserReportBuilder**<?,?> builder,
  symbol:   class UserReportBuilder
  location: class UserReport
```

I was using lombok  1.18.30 version. 

Also tried with below versions as well 
1.18.32, 1.18.28, 1.18.22, 1.18.26

Please find the code below:

```
@Setter @Getter  @SuperBuilder @EqualsAndHashCode(callSuper = false)
@JsonPropertyOrder({"userId", "location" })
public class **UserReport** extends MessageBase
{

  @JsonProperty(value = "userId", required = true)
  private Integer      userId;
  
  @JsonProperty(value = "location", required = true)
  private String       location;
 


  public UserReport (String userId, String location)
  {
    this.userId = Optional.ofNullable(userId).orElse(-1);
    this.location = Optional.of(location).filter(StringUtils::isNotBlank).orElse(null);
  }

	
}
```

```
@Service
public class **MessageService**
{

             //method
  private void fillInUserReportFields(**UserReport.UserReportBuilder**<?,?> builder,
                                         UserEvent event)
  {
   
   //body
   
}
```

```
@Data
@SuperBuilder @JsonPropertyOrder({ "messageType", "messageNumber"})
public class MessageBase
{
  private static final Logger LOGGER = LogManager.getLogger();

  @NotNull @NotBlank
  private String messageType;
  @NotNull @NotBlank
  private int messageNumber;
  private Integer requestNumber;

}
```

**Comment by scottfrederick** [comment]
Thanks for the report. It's not clear what role Spring Boot might have in this problem, but it's hard to tell from the snippets you've provided. If you would like us to spend some time investigating, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by mgaceanu** [comment]
I had a similar error when upgrading from 3.0 to 3.3
In my case there was a minor error related to `Fields.UNDERSCORE_ID` which is not a constant anymore. But this was trigerring the unrelated Lombok errors.

So check your errors carefully :-)
