### ISSUE TITLE
Spring Security OAuth2 - override how resource server retrieves public key

### ISSUE THREAD

**Issue by brendonanderson** [spring-projects/spring-boot#4052]
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L274

Is there a way to override how the resource server gets the public key from the authorization server?  We use consul in our environment and from what I can tell, `RestTemplate` does not understand `srv://` URIs.  It would be nice if there was a way to use a different client that understands SRV or even to read the public key from the filesystem (not as ideal).

If there isn't a way possible, can the code be enhanced to provide a way to add in some hooks to alternative methods to retrieve the public key?

**Comment by fkowal** [comment]
+1

**Comment by mbhave** [comment]
@brendonanderson you can configure your own bean of type `DefaultTokenServices` which can be configured with a `JwtTokenStore` and a `JwtAccessTokenConverter`. The public key (you'll need to use custom logic here to retrieve the public key depending on your use-case), can be set on the converter.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
