### ISSUE TITLE
Change or remove dependency exclusion in spring-boot-starter-jersey

### ISSUE THREAD

**Issue by viktorgunnarson** [spring-projects/spring-boot#40580]
Since `jersey-bean-validation` has changed from `jakarta.el` to `expressly` (see PR [here](https://github.com/eclipse-ee4j/jersey/pull/5551)) the exclusion of `jakarta.el` seems redundant and should probably either be changed or removed: 

https://github.com/spring-projects/spring-boot/blame/c6c02906ef8af4bf5684cb2670a8c42021265de6/spring-boot-project/spring-boot-starters/spring-boot-starter-jersey/build.gradle#L16

**Comment by wilkinsona** [comment]
It's the underlying implementation that has changed but the dependency on the API remains. We exclude it as we want `org.apache.tomcat.embed:tomcat-embed-el`, a dependency through `spring-boot-starter-validation` to be used instead.
