### ISSUE TITLE
The logback xml <springProfile> element is no longer working from included xml.

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-boot#40586]
I have the following base.xml file in a library that is being included by my logback-spring.xml configuration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<included>
    <springProfile name="local,plain-text-logging">
        <include resource="logback/text-appenders.xml" />
    </springProfile>

    <springProfile name="!local &amp; !plain-text-logging">
        <include resource="logback/json-appenders.xml" />
    </springProfile>
</included>
```

After upgrading my project from Spring Boot 3.2.5 to 3.3.0-RC1, I discovered that the `<springProfile>` element no longer works. It only works if I move the above configuration directly into my project's logback-spring.xml configuration. I've attached a simple starter project that demonstrates this issue.

[sb330rc1-demo.zip](https://github.com/spring-projects/spring-boot/files/15171722/sb330rc1-demo.zip)

**Comment by thorntonrp** [comment]
As best I can tell by debugging this issue, it appears that the `SpringBootJoranConfigurator` is not being applied to included xml.

**Comment by scottfrederick** [comment]
Duplicates #40491
