### ISSUE TITLE
Does actuator assert management.security.role when serving the /health endpoint?

### ISSUE THREAD

**Issue by sthzg** [spring-projects/spring-boot#4060]
When testing actuator's `/health` endpoint with below configuration then the endpoint doesn't seem to respect the role set in `management.security.role` to deliver sensitive properties on that endpoint.

**Configuration**
```java
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
@Configuration
public class MyWebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception{
        auth
            .inMemoryAuthentication()
                .withUser("user").password("password").roles("USER").and()
                .withUser("admin").password("password").roles("USER", "ADMIN");
    }
}
```

**Response for unauthenticated request** (as expected)
```json
{
  "status": "UP",
  "links": [
    {
      "rel": "self",
      "href": "http://localhost:29001/health"
    }
  ]
}
```

**Response for authenticated request with role `USER`** (shouldn't `diskSpace` be only visible to `ADMIN`?)
```json
{
  "status": "UP",
  "diskSpace": {
    "status": "UP",
    "total": 511250432000,
    "free": 33474105344,
    "threshold": 10485760
  },
  "links": [
    {
      "rel": "self",
      "href": "http://localhost:29001/health"
    }
  ]
}
```

**Comment by xtremebiker** [comment]
Isn't the role set supposed to have the property name `management.security.roles`?. It's told in the [docs](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html). By the way, I can't get it work either.

**Comment by philwebb** [comment]
@xtremebiker This issue has been closed for over a year. If you think you've found a new bug please raise another issue or if you have a general question please ask on stackoverflow.com.
