### ISSUE TITLE
Allow log config files to be loaded from non-classpath locations

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4061]
`AbstractLoggingSystem.findConfig(String[])` only ever tests for config file located in the classpath. It would be nice to allow other (e.g. URL-based) locations.

**Comment by philwebb** [comment]
It looks like we already support this. At least [for logback](https://github.com/spring-projects/spring-boot/blob/8dd1354d82be9bae236e3e8804c82f0987c42729/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L149)
