### ISSUE TITLE
Typo: "include-code" is written as "includ-code" to link the source code of JerseyConfig in jersey.adoc

### ISSUE THREAD

**Issue by PiyalAhmed** [spring-projects/spring-boot#40628]
There is typo: `includ-code`. It must be `include-code` to link the source code properly

https://github.com/spring-projects/spring-boot/blob/e954afdc2e8b1956d10671bf5d125f39f1bebb50/spring-boot-project/spring-boot-docs/src/docs/antora/modules/how-to/pages/jersey.adoc?plain=1#L26

**Comment by PiyalAhmed** [comment]
I would love to submit a PR fixing this.

**Comment by wilkinsona** [comment]
Duplicates #40629.

@PiyalAhmed If you intend to open a pull request, we don't need an issue as well.

**Comment by PiyalAhmed** [comment]
> Duplicates #40629.
> 
> @PiyalAhmed If you intend to open a pull request, we don't need an issue as well.

Thank you, I'll keep that in mind!
