### ISSUE TITLE
Clarify documentation of whether spring.config.location replaces or augments the default search path

### ISSUE THREAD

**Issue by tomwhoiscontrary** [spring-projects/spring-boot#4062]
In [the fine manual](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files), we read that (emphasis mine):

> If spring.config.location contains directories (as opposed to files) they should end in / (and will be appended with the names generated from spring.config.name before being loaded). **The default search path classpath:,classpath:/config,file:,file:config/ is always used, irrespective of the value of spring.config.location.** In that way you can set up default values for your application in application.properties (or whatever other basename you choose with spring.config.name) and override it at runtime with a different file, keeping the defaults.

However, @snicoll ventured the opinion that in fact, spring.config.location entirely replaces the default search path. If this is the case, could the documentation be corrected?

**Comment by snicoll** [comment]
Actually, as I said already, I was wrong so the idea is to clarify the phrasing a bit to make that more obvious.

**Comment by dsyer** [comment]
That seems pretty clear to me. Anyone have a suggested wording for a replacement?

**Comment by snicoll** [comment]
I think an example would help. And the _irrespective of_ part is a bit hidden in between a lengthy text. I got caught a few times (today again). But maybe it's just me and Tom? :)

**Comment by tomwhoiscontrary** [comment]
I think it is fairly clear.

At some point recently, i was griping about some other bits of phrasing on this page. Should i try making a pull request?

And would it be appropriate to mention [@TestPropertySource](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/TestPropertySource.html) here too?

**Comment by tomwhoiscontrary** [comment]
Uh @dsyer ...

**Comment by snicoll** [comment]
Dave your commit is referring to the wrong issue.

**Comment by dsyer** [comment]
Sorry. Aimed at #4063.

**Comment by philwebb** [comment]
@tomwhoiscontrary A pull request would be most welcome

**Comment by philwebb** [comment]
Closing in favor of PR #9707
