### ISSUE TITLE
Enable GraalVM native Paketo Builder Tests on Java 22

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#40639]

**Comment by izeye** [comment]
I'm not sure if "Java 22" in the issue title is just a typo for "Java 21", but ed42ed7c43e9c865c30258629bc9e00b5e523913 doesn't seem to include Java 22 as follows:

https://github.com/spring-projects/spring-boot/blob/ed42ed7c43e9c865c30258629bc9e00b5e523913/spring-boot-system-tests/spring-boot-image-tests/src/systemTest/java/org/springframework/boot/image/paketo/PaketoBuilderTests.java#L64-L65

**Comment by philwebb** [comment]
Thanks @izeye. Looking at commit ed42ed7c43e9c865c30258629bc9e00b5e523913 it seems like the JDK 17 limit was removed on the test, but we missed that none of the Paketo tests are running on JDK 22 yet. I wonder if we can just drop that restriction now. I've opened #43505
