### ISSUE TITLE
Management context startup failures are not reported

### ISSUE THREAD

**Issue by zbi** [spring-projects/spring-boot#4064]
Hello,

In our project, there is a cause which block the start context of spring boot. We could not access to `/health`. But the spring boot application still started with status ok.

It miss really a lot of details in the log. In our case, we could only see 

```
"2015-09-30 13:53:57.925  WARN[main] --- .s.b.a.a.EndpointWebMvcAutoConfiguration - Could not start embedded container (management endpoints are still available through JMX) "
```

The message is logged when a `EmbeddedServletContainerException` happens and there is a comment 	 in the code      

```java
// No support currently for deploying a war with management.port=<different>,
// and this is the signature of that happening
```

With this, we could not make the analysis more further because we don't even know the exception is thrown by which class. Also It is even with "WARN" but not "ERROR".

Could you please 
1. make the log level correct and have more details when there are some errors ?
2. Throw an exception when the context could not start and stop the start processing? If not, it would confuse the user and more than more no one will believe the message.

Please tell me if you need more message and I really appreciate if some of you could explain also the message " No support currently for deploying a war with management.port=<different> "

Thanks in advance,

Zhuhan

**Comment by philwebb** [comment]
Could you provide some more details. What version of Spring Boot are you using? How are you packaging your apps (war/jar)? What application server (if any) are you using?

**Comment by zbi** [comment]
Hello,

The version is 1.2.3-release, we package our apps in jar and server linux. 

Please tell me if you need more details.

regards,

**Comment by philwebb** [comment]
I'm a little confused by the "No support currently for deploying a war with management.port=<different>" comment that you've added since that's aimed at traditional war deployments.

Can you provide a [sample application](https://github.com/spring-projects/spring-boot-issues) that replicates the actual problem that you're seeing?

**Comment by zbi** [comment]
Thanks for your answer.

The comment is in the class EndpointWebMvcAutoConfiguration. You mean this configuration is only used when it is aimed the war deployments ? But when I debug the start on localhost, I could see well it entered into this class. 

We don't know excatly yet where the bug comes from(because of missing logs) and to reproduce it is vey complex.

I think the explication of the comment is not so important as adding more details in the log and stopping the start when the context failed to start. 

Or at least, could spring boot give us an annotation of configuration to decide if we need to continue to start the web app when the context is failed ?

thanks in advance,

**Comment by philwebb** [comment]
I've update `createChildManagementContext()` in master to log an additional debug message with the exception details.

Are you able to add a breakpoint to the catch block in `createChildManagementContext` and get the stacktrace of the `RuntimeException`. If you add a debug watch for `ex.printStacktrace()` you should be able to get details to print to the console.

It looks like we currently intentionally catch the exception to prevent startup failures when apps are deployed as war files (see #552). Perhaps we need a better strategy to determine when we should log a warning and when we should fail hard.

**Comment by zbi** [comment]
Thanks for your update.

Unfortunately the error could only be reproduced on the environment "staging". I will try to debug it with remote.  

If not, is it possible to make some configuration (change log level for example) to see StackTrace in stead of ex.printStacktrace ? It will be more easier for the developer. 

You are right, it will be very useful to make a better strategy also for the deploying jar. Waiting for your evolution.

**Comment by RaphC** [comment]
Hi,

IMHO, It would be nice if through a configuration key like 

<pre><code>
management: 
  stop-on-failure: true
</code></pre>

we could  specify if the application startup has to fail or ignore the context management startup error.

The main issue is that the listened port was already taken. We had to set put Jetty logs in debug to know the root cause.

**Comment by philwebb** [comment]
@zbi The change is in `1.3.0.BUILD-SNAPSHOT`

**Comment by wilkinsona** [comment]
@philwebb `ServletComponentRegisteringPostProcessor` uses this logic to detect an embedded container:

```
	private boolean isRunningInEmbeddedContainer() {
		return this.applicationContext instanceof EmbeddedWebApplicationContext
				&& ((EmbeddedWebApplicationContext) this.applicationContext)
						.getServletContext() == null;
	}
```

It relies on running during initialisation at which point the servlet context won't have been set in the embedded case.

**Comment by philwebb** [comment]
It looks like the catching `EmbeddedServletContainerException` might not be necessary at all now. It was originally added in commit 45315a97fffe395ebc4004bc77a96b9ab5dcdae2 but commit 764e34b9db567895a69ad63d6b4f73829647eb82 updated things so that starting a child context isn't even attempted.
