### ISSUE TITLE
JsonFormat does not affect serialisation of Date

### ISSUE THREAD

**Issue by marccollin** [spring-projects/spring-boot#4065]
i use spring boot 1.3.0 (tried to 1.3.0.M5), spring-data-jpa, spring rest and mysql.
i use java 8.

In my dto i have
```java
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", timezone="EST")
private Date birthdate;
```

client still continue to receive yyyy-mm-dd

**Comment by wilkinsona** [comment]
@marccollin Can you please try with 1.3.0.BUILD-SNAPSHOT? #3891 made some changes to Jackson configuration, particularly when you're also using Spring Data REST or Spring HATEOAS.

**Comment by marccollin** [comment]
tried, get same result.


sent the setup of the application, i use only annotation.
```
@EntityScan(basePackageClasses = { ServerApplication.class, Jsr310JpaConverters.class })
@SpringBootApplication
@EnableCaching
public class ServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(ServerApplication.class, args);
    }
}
```

**Comment by wilkinsona** [comment]
Thanks for trying with a snapshot

**Comment by wilkinsona** [comment]
@marccollin I can't reproduce the problem on 1.3.0.M5 or 1.3.0.BUILD-SNAPSHOT. I've tried with both a plain `@RestController` and using a controller provided by Spring Data REST that's derived from a JPA `CrudRepository`.

If you'd like me to investigate further, please provide a sample project that reproduces the issue.

**Comment by marccollin** [comment]
[Link to a small project!](http://www.pastefile.com/T8C6Pd)


it use mysql.

so create a database named chezlise.

all the schema will be created.

if no data is created automatically only do
INSERT INTO lodger  (birthdate) values(curdate());

**Comment by wilkinsona** [comment]
This doesn't have anything to do with Spring Boot. You're returning a `java.sql.Date` and Jackson doesn't appear to apply the specified formatting to it. You can see the problem with the following code that doesn't involve Boot at all:

```java
	public static void main(String[] args) throws JsonProcessingException {
		ObjectMapper objectMapper = new ObjectMapper();
		System.out.println(objectMapper.writeValueAsString(new Foo(new java.util.Date())));
		System.out.println(objectMapper.writeValueAsString(new Foo(new java.sql.Date(System.currentTimeMillis()))));
	}
	
	static class Foo {
		
	    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", timezone="EST")
		private Date birthdate;
		
		public Foo() {
			
		}

		public Foo(Date birthdate) {
			this.birthdate = birthdate;
		}
		
		public Date getBirthdate() {
			return birthdate;
		}
		
	}
```

It produces the following output:

```
{"birthdate":"01/10/2015"}
{"birthdate":"2015-10-01"}
```

Note that the [Jackson documentation](http://wiki.fasterxml.com/JacksonFAQDateHandling) has this to say about `java.sql.Date`:

> #### Notes on java.sql.Date

> (aka "Please do NOT use java.sql.Date, ever!")

> Although Jackson supports java.sql.Date, there are known issues with respect to timezone handling, partly due to design of this class. It is recommended that this type is avoided, if possible, and regular java.util.Date (or java.util.Calendar) used instead. If this is not possible, it may be necessary for applications to convert these dates using java.util.Calendar and explicit timezone definition.

**Comment by marccollin** [comment]
My bean use

```java
@Temporal(javax.persistence.TemporalType.DATE)
private Date birthdate;
```

In database, that create a field: date.

if i remove it, that create a field datetime but that display value correctly... 

strange behaviour.
