### ISSUE TITLE
Content negotiation for XML response

### ISSUE THREAD

**Issue by silentcode12** [spring-projects/spring-boot#407]
Given the example controller method shouldn't XML be returned for the Firefox default Accept header `"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"`?

```
@RequestMapping(value = "/test", method = RequestMethod.GET)
    public ResponseEntity<String[]> test(HttpServletRequest request) {      
        String[] result = {"value 1", "value 2", "value 3"};        
        return new ResponseEntity<String[]>(result, HttpStatus.OK);             
    }
```

The following URLs return a content type of **"application/json;charset=UTF-8"**:
- http://localhost:9000/test 
- http://localhost:9000/test.json

But the URL **"http://localhost:9000/test.xml"** results in a **"406 Not Acceptable"**.

Setting the Accept header, using modify headers plugin, to only accept **"application/xhtml+xml"** for the URL **"http://localhost:9000/test"** also results in the same response.

Can someone explain what is happening?

**Comment by deki** [comment]
Of course the solution works, but why is it needed? See comparison here: http://blog.codeleak.pl/2015/04/jax-rs-2x-vs-spring-mvc-returning-xml.html

Is there any better solution without wrapper?

**Comment by dsyer** [comment]
Regardless of whether there is (or should be) a better solution, I don't think it would be here. It would probably be a Spring MVC feature (like a modification to one of the `HttpMessageConverters`).
