### ISSUE TITLE
Support for exporting actuator metrics to Aws CloudWatch

### ISSUE THREAD

**Issue by gauravbrills** [spring-projects/spring-boot#4071]
It would be great if spring boot provides the out of the box configuration in order to export actuator metrics to AWS cloudwatch . This is helpful as app level matrics will be available in cloudwatch and alarms can be conveniently be configured then on app level events exported in Actuator metrics .Also a parallel functionality is currently provided by this dropwizard plugin https://github.com/jdamick/dropwizard-metrics-cloudwatch hope spring boot can also implement the same and also target doing similar exports for other cloud providers as well .

**Comment by philwebb** [comment]
You can use the Dropwizard metrics library with Spring Boot so that might be the best way to get this going quickly.

**Comment by gauravbrills** [comment]
ya @philwebb currently using the same via using Dropwizard and its plugin for cloudwatch with spring boot ..

**Comment by matsev** [comment]
What is the status of [Spring Cloud AWS Actuator](https://github.com/spring-cloud/spring-cloud-aws/tree/master/spring-cloud-aws-actuator)? Will that project solve this issue?

**Comment by theRealDrumBum** [comment]
@gauravbrills are you referring to this one: https://github.com/jdamick/dropwizard-metrics-cloudwatch

I too would like a spring version of this, but would like it to reside outside boot and be part of the io suite.

**Comment by aaronwaddell** [comment]
This appears to be a duplicate of spring-cloud/spring-cloud-aws#7

@philwebb Can we close this issue?

**Comment by wilkinsona** [comment]
@aaronwaddell Thank you
