### ISSUE TITLE
Can we use single JedisConnectionFactory instance with multiple spring redis template? 

### ISSUE THREAD

**Issue by vijayrawatsan** [spring-projects/spring-boot#4078]
I have multiple springRedisTemplate with diffrent serializers. Can I use same JedisConnectionFactory instance for both?

**Comment by philwebb** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

Thanks.
