### ISSUE TITLE
Consider update to MySQL 8.4.0

### ISSUE THREAD

**Issue by trcoelho** [spring-projects/spring-boot#40806]
Is there any action to update to MySQL connector to version 8.4.0? 

Have checked at 3.3.0-RC1 and 3.3.0-SNAPSHOT however couldn't see latest MySQL version (8.4.0) be considered.

Any plan to consider it in 3.3.0 version?

Thanks in advance.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/40801.
