### ISSUE TITLE
Upgrade to MySQL 8.4.0 LTS

### ISSUE THREAD

**Issue by jobmission** [spring-projects/spring-boot#40801]
MySQL 8.4.0 has been released as a long-term supported version.

[See release.](https://docs.oracle.com/cd/E17952_01/mysql-8.4-relnotes-en/news-8-4-0.html)

**Comment by wilkinsona** [comment]
This is covered in the issue template:

> - Managed Dependency Upgrade
You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release

We'll upgrade to 8.4 (or later) in Spring Boot 3.4. It's too late to do so in Spring Boot 3.3. In the meantime, you can use the `mysql.version` property to override the version if you wish.
