### ISSUE TITLE
Remove deprected properties from JspTemplateAvailabilityProvider

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4086]
JspTemplateAvailabilityProvider can be updated to remove `spring.view.prefix` references. It should also use `RelaxedPropertyResolver` like the others.

**Comment by jadekler** [comment]
@philwebb `RelaxedPropertyBinder` == `RelaxedPropertyResolver`? Maybe I'm missing something, but I see no `RelaxedPropertyBinder`

**Comment by snicoll** [comment]
@jadekler yes. You can find usage in several places of the codebase.

**Comment by jadekler** [comment]
@snicoll Danke

**Comment by philwebb** [comment]
Thanks, update original comment to say `RelaxedPropertyResolver`.
