### ISSUE TITLE
Sending request message remote web service using SOAP 

### ISSUE THREAD

**Issue by kubrafelek** [spring-projects/spring-boot#40868]
Hi, 

I'm getting below error message when trying to send request 

Have you any comment for this issue ?
Thanks :)

SOAPPartImpl:SAAJ0514: Unable to create envelope from given source because the root element is not named Envelope
EnvelopeFactory:SAAJ0511: Unable to create envelope from given source
On delivery attempt: 2 caught: org.springframework.ws.soap.SoapMessageCreationException: Could not create message from InputStream: Unable to create envelope from given source:

Soap Client

webServiceTemplate.marshalSendAndReceive(serverBaseURI, request.getFirst(), soapRequestHeaderModifier); 

---
        <dependency>
            <groupId>jakarta.xml.soap</groupId>
            <artifactId>jakarta.xml.soap-api</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.messaging.saaj</groupId>
            <artifactId>saaj-impl</artifactId>
            <version>3.0.3</version>
        </dependency>
---

**Comment by mhalbritter** [comment]
Hello! This looks like an issue for https://github.com/spring-projects/spring-ws. Please open an issue on their tracker. Thanks!
