### ISSUE TITLE
jarmode=tools extract does not include the META-INF/sbom folder

### ISSUE THREAD

**Issue by cachescrubber** [spring-projects/spring-boot#40881]
# jarmode=tools extract  does not include the META-INF/sbom folder

Spring Boot Version: 3.3.0-RC1

```
# java -Djarmode=tools -jar application.jar extract --layers --destination extracted
```
Following the instructions in https://docs.spring.io/spring-boot/reference/container-images/dockerfiles.html,
The extracted application.jar from the above mentioned command does not include the `META-INF/sbom` folder. As. consequence, the new sbom actuator endpoint does not contain `application.cdx.json`.

**Comment by wilkinsona** [comment]
Duplicates #40861 and #40456.
