### ISSUE TITLE
A newline character is missing from the start of the default banner

### ISSUE THREAD

**Issue by Eng-Fouad** [spring-projects/spring-boot#40888]
The banner was printed correctly In Spring Boot v3.2.5:

```
2024-05-23 00:00:00.000  INFO 11111 --- [           main] o.s.boot.SpringApplication               : 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.5)


```

However, in Spring Boot v3.3.0, it seems it eliminates the prefix new-line:

```
2024-05-23 00:00:00.000  INFO 11111 --- [           main] o.s.boot.SpringApplication               :   .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.0)


```

**Comment by wilkinsona** [comment]
Thanks for the report. This appears to have been broken sometime between 3.3.0-M1 and 3.3.0-M2. It's only really noticeable when `spring.main.banner-mode` is set to `log`. With the default mode of `console`, there is a missing newline but it has a much smaller effect:

```
> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v3.3.0-M1)
```

```
> Task :bootRun
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::             (v3.3.0-M2)
```

@Eng-Fouad I'd love to know if there's anything that prevented you from trying out the milestones or release candidates. You're obvious keen and interested as 3.3.0 was released less than an hour ago. Is there anything that we can do to make it easier for you try out pre-GA releases?

**Comment by Eng-Fouad** [comment]
> Thanks for the report. This appears to have been broken sometime between 3.3.0-M1 and 3.3.0-M2. It's only really noticeable when `spring.main.banner-mode` is set to `log`. With the default mode of `console`, there is a missing newline but it has a much smaller effect:
> 
> ```
> > Task :bootRun
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::             (v3.3.0-M1)
> ```
> 
> ```
> > Task :bootRun
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
> 
>  :: Spring Boot ::             (v3.3.0-M2)
> ```
> 
> @Eng-Fouad I'd love to know if there's anything that prevented you from trying out the milestones or release candidates. You're obvious keen and interested as 3.3.0 was released less than an hour ago. Is there anything that we can do to make it easier for you try out pre-GA releases?

GA releases are easier to access as they are available on maven central :)

**Comment by Eng-Fouad** [comment]
It looks like this is caused by #39585

**Comment by philwebb** [comment]
Closing in favor of PR #40889. Thanks @Eng-Fouad
