### ISSUE TITLE
Please add support to helidon nima mp/se webserver 

### ISSUE THREAD

**Issue by sirlordt** [spring-projects/spring-boot#40898]
Hello 

Please add support to helidon nima mp/se web server. Is a performant web server designed from scratch to work with virtual threads.

Thanks.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. To support Nima in Spring Boot, it would either have to provide an implementation of the Servlet specification (which I don't believe it does) or it would have to be supported by Spring WebFlux. The former would have to be addressed by the Nima maintainers. The latter would have to be addressed by the [Spring Framework](https://github.com/spring-projects/spring-framework) team.

I'm going to close this one for now as it isn't actionable. If things change in Nima or Spring Framework we can re-open it.
