### ISSUE TITLE
Configuring Spring Boot with Spring Security makes build fail due to reference to missing dependency

### ISSUE THREAD

**Issue by richardkabiling** [spring-projects/spring-boot#4090]
Whenever trying to run ``mvn install``, on a Spring Boot project the build fails due to:

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jersey</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

> Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
> (default-compile) on project wave: Fatal error compiling:
> java.lang.RuntimeException:
> com.sun.tools.javac.code.Symbol$CompletionFailure: class file for
> org.springframework.security.ldap.DefaultSpringSecurityContextSource
> not found -> [Help 1]

Two things solved this issue:

1. **Deleting** the following security configuration

        @Configuration
        @EnableWebSecurity
        public class SecurityConfig extends WebSecurityConfigurerAdapter {
      
          @Inject
          private UserDetailsService userDetailsService;
      
          @Inject
          public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
            auth
              .userDetailsService(userDetailsService);
          }
          
          @Override
          protected void configure(HttpSecurity http) throws Exception {
            http
              .httpBasic()
                .realmName("Wave")
                .and()
              .authorizeRequests()
                .antMatchers(HttpMethod.POST, "/wave/service/employees/**").anonymous()
                .antMatchers("/wave/service/**").authenticated()
                .and()
              .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS);
          }
    
        }

Of coruse, removing the configuration is not an option since it disables security from my application

2. **Adding** the following dependency

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-ldap</artifactId>
		</dependency>

However, while adding it made the error disappear, a new similar error (just pointing to another class) appeared:

> Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
> (default-compile) on project wave: Fatal error compiling:
> java.lang.RuntimeException:
> com.sun.tools.javac.code.Symbol$CompletionFailure: class file for
> org.springframework.security.openid.OpenIDAttribute not found -> [Help
> 1]

Fixing this again, I added the following dependency:

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-openid</artifactId>
		</dependency>

This fixed the issue again, but another error appeared:

> Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
> (default-compile) on project wave: Fatal error compiling:
> java.lang.RuntimeException:
> com.sun.tools.javac.code.Symbol$CompletionFailure: class file for
> org.apache.http.Header not found -> [Help 1]

Finally, adding the following dependency fixed all the issues:

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.1</version>
		</dependency>

However, I now have multiple dependencies I am not _using_.

Is there another way to fix this issue?

**Comment by wilkinsona** [comment]
What version of Boot are you using?

**Comment by richardkabiling** [comment]
I'm using spring boot 1.2.6

**Comment by wilkinsona** [comment]
It looks like you've found a bug in the compiler. What version of the JDK, Maven, and Maven Compiler Plugin are you using?

**Comment by richardkabiling** [comment]
I'm using jdk1.8.0_60, maven 3.3, and maven compiler 3.3

**Comment by wilkinsona** [comment]
Ok. The code you've shown above compiles fine for me with the dependencies that you listed. With the information you've provided it's impossible to say if there's a problem in Boot or a related Spring project, however there's definitely a problem with the compiler as it's crashing. I would recommend that you open a bug against the JDK. If you do so, you should include a small sample that will allow them to recreate the problem.

**Comment by erdbeerschnitzel** [comment]
I had a very similar problem with SpringBoot 1.5.6, Maven 3.3.9, Maven compiler 3.6.0 and JDK 1.8.0_74

> com.sun.tools.javac.code.Symbol$CompletionFailure: class file for groovy.lang.Closure not found

I solved it by adding the following dependencies:

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-ldap</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-openid</artifactId>
            <scope>provided</scope>
        </dependency>

I have set the dependency scope to "provided", so the JAR files don't get included in my build.

**Comment by t-oster** [comment]
WTF: I just went back a few commits, then it built successfully, then I got back to the commit I was before going back and now it works... strange thing
