### ISSUE TITLE
Support conversion of Duration like `2h30s`

### ISSUE THREAD

**Issue by bjmi** [spring-projects/spring-boot#40901]
It would be useful if parsing of formats like `3h10s` or `2h 10m 45s` to _java.time.Duration_ is supported.
[kotlin.time.Duration.parse(String)](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/parse.html#parse)  could serve as a possible reference.
Decimal notation e.g. `1.5h` would also be nice.

**Comment by bclozel** [comment]
Closing in favor of https://github.com/spring-projects/spring-framework/pull/30396, also see https://github.com/spring-projects/spring-boot/issues/37562#issuecomment-2036949439
