### ISSUE TITLE
Broken Micrometer links in documentation

### ISSUE THREAD

**Issue by Seungpang** [spring-projects/spring-boot#40916]
Hi Team,

The documentation for Spring Boot contains several references to Micrometer's documentation using the {url-micrometer-docs}, {url-micrometer-docs-implementations}, and {url-micrometer-docs-concepts} placeholders.

These links are currently broken because the URL structure of Micrometer's documentation now includes a version number.

### Affected Files
+ `metrics.adoc`
+ `observability.adoc`

![스크린샷 2024-05-27 오후 11 28 54](https://github.com/spring-projects/spring-boot/assets/37570657/4e18c0cc-b74a-4b04-a422-b28cecec6df0)

**Comment by mhalbritter** [comment]
Thanks for the report! One such link can be found on the [Metrics](https://docs.spring.io/spring-boot/reference/actuator/metrics.html) page for example:

> Micrometer’s capabilities, see its [reference documentation](https://docs.micrometer.io/micrometer/reference/1.13)

**Comment by philwebb** [comment]
I think we should ask Micrometer to fix this, otherwise we have no way of providing links for the version we actually use. I've raised https://github.com/micrometer-metrics/micrometer/issues/5152

**Comment by Seungpang** [comment]
I agree. Thank you!

**Comment by philwebb** [comment]
@Seungpang Those aren't intentional so we'd happily accept a PR to fix them.

**Comment by philwebb** [comment]
For now I'm going to drop the version part
