### ISSUE TITLE
Use latest Framework 6.0.x version when downgrading it

### ISSUE THREAD

**Issue by kjprakashji** [spring-projects/spring-boot#40929]
https://github.com/spring-projects/spring-boot/blob/d26881acb42161aae2af854d4c93df83d7dfef81/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/build.gradle#L56

**Comment by wilkinsona** [comment]
Thanks, we should probably upgrade to the latest 6.0.x version. Why do you ask, out of interest? It's an internal-only dependency of Spring Boot's Gradle plugin and should have no effect upon your application.

**Comment by kjprakashji** [comment]
Thank you. It was quarantined in one of the projects I was working and builds failed. Got a waiver updated temporarily.
