### ISSUE TITLE
Dependency Versions page (docs.spring.io) is not populated

### ISSUE THREAD

**Issue by MalikKillian** [spring-projects/spring-boot#40932]
The official Dependency Versions page has no data. https://docs.spring.io/spring-boot/appendix/dependency-versions/index.html

If I knew an easy way to get this data I might submit the PR myself but I don't.

**Comment by wilkinsona** [comment]
That page is just a (rather sparse) introduction to the appendix. You can find the dependency versions and managed coordinates in its two sub-pages:

- https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
- https://docs.spring.io/spring-boot/appendix/dependency-versions/properties.html

You can navigate to them using the left-hand navigation or the `Next` link at the foot of the page.
