### ISSUE TITLE
Add platform option for image building

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#40944]
See https://github.com/buildpacks/pack/issues/2154 for the equivalent `pack` option. The value of a `platform` option should be passed to the lifecycle API as provided by the user.

**Comment by StefanLobbenmeierObjego** [comment]
Current workaround is running pack manually, in my case something like this:
```
pack build --platform linux/amd64 --builder paketobuildpacks/builder-jammy-base:latest --buildpack paketo-buildpacks/java --env BP_JVM_VERSION=21 putyourimagenamehere
```

**Comment by scottfrederick** [comment]
While many phases of the CNB [lifecycle API](https://github.com/buildpacks/spec/blob/main/platform.md) do have a `-platform` option, that option is not related to the `--platform` option added to the pack CLI. Instead of passing the value of this new option to the lifecycle API, we should pass the value to the Docker Engine API when [pulling images](https://docs.docker.com/engine/api/v1.46/#tag/Image/operation/ImageCreate) and [creating containers](https://docs.docker.com/engine/api/v1.46/#tag/Container/operation/ContainerCreate) from images. 

To reduce the potential for confusion, we should call the new options in the Maven and Gradle configuration `imagePlatform` instead of just `platform`.

**Comment by ChildrenGreens** [comment]
@scottfrederick Well done! Looking forward to the official release of version 3.4.0!

**Comment by filipblondeel** [comment]
@scottfrederick Does this support specifying multiple platforms, for example `linux/amd64` and `linux/arm64`?

**Comment by scottfrederick** [comment]
@filipblondeel Only one platform option can be specified. Supporting multiple platform options would require Spring Boot it iterate over the entire image-building process for each option.

**Comment by birnbuazn** [comment]
> [@filipblondeel](https://github.com/filipblondeel) Only one platform option can be specified. Supporting multiple platform options would require Spring Boot to iterate over the entire image-building process for each option.

This is rather unfortunate for a Java application, where we were promised a build once run anywhere. I cannot run the amd images built in my Github pipeline on my local Mac dev box without emulator :(

**Comment by wilkinsona** [comment]
@birnbuazn it should be possible to configure your build to run the relevant Gradle task or Maven goal multiple times if you want to build multiple images for whatever reason.

**Comment by birnbuazn** [comment]
@wilkinsona I know, but this will 

* create separate Docker images (at least with different tags) for every architecture
* will not create the correct MetaInfo that points to the relevant Docker images with the same tag

This can probably all be done manually, but it IMHO really should be part of the the BootBuildImage task.

To clarify my intent: I want a linux/amd64 image to run on staging/prod, but a linux/arm64 image for (mainly) Mac dev boxes. Docker Desktop/Compose can run in QEMU emulation mode, but Docker Swarm cannot.

**Comment by wilkinsona** [comment]
I don't think either of those points would change if `imagePlatform` was a list. As @scottfrederick already explained, we'd have to iterate over the entire image building process for each option. That's equivalent to running the goal or task twice with different configuration but with less flexibility. Also, please note that `pack` does not support multiple `--platform` options and we aim for parity with `pack`.

**Comment by ThomasVitale** [comment]
@birnbuazn in case it might be useful, here's a snippet for GitHub Actions on how to publish a multi-arch image using Spring Boot Buildpacks support

```yaml
  - name: Build and publish OCI image
    run: |
      ./gradlew bootBuildImage --imageName ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-amd64 --imagePlatform linux/amd64
      docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-amd64

      ./gradlew bootBuildImage --imageName ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-arm64 --imagePlatform linux/arm64
      docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-arm64
  
      docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
        --amend ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-amd64 \
        --amend ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest-arm64
      docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
```

**Comment by birnbuazn** [comment]
> That's equivalent to running the goal or task twice with different configuration but with less flexibility.

@wilkinsona fair enough, but as mentioned: Having to create the Docker Manifest manually separately is trivial, but still a bit of a pain
