### ISSUE TITLE
org.springframework.boot/spring-boot-starter-test Does not work with a module path

### ISSUE THREAD

**Issue by bowbahdoe** [spring-projects/spring-boot#40949]
The `org.json` package is split between `jsonassert` and `android.json`.

I am validating this with a tool I wrote 

* https://github.com/bowbahdoe/jresolve-cli
* `bash < <(curl -s  https://raw.githubusercontent.com/bowbahdoe/jresolve-cli/main/install)`

```
jresolve --output-directory libs \
    pkg:maven/org.springframework.boot/spring-boot-starter-web@3.3.0
    pkg:maven/org.springframework.boot/spring-boot-starter-test@3.3.0
```

```
java --module-path libs --add-modules spring.boot.test
```

```
java --module-path libs --add-modules spring.boot.test
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules jsonassert and android.json export package org.json to module spring.boot.starter
```

**Comment by philwebb** [comment]
Unfortunately this is an issue we can't fix in Spring Boot. There's an [open pull request](https://github.com/skyscreamer/JSONassert/pull/176) but it doesn't look like JSONassert is being actively maintained at the moment.

See also #15967
