### ISSUE TITLE
[Documentation] Gradle Plugin "Getting Started" documentation section out of date

### ISSUE THREAD

**Issue by SimoneGiusso** [spring-projects/spring-boot#40954]
[Here](https://docs.spring.io/spring-boot/gradle-plugin/getting-started.html) it is suggested to apply the [io.spring.dependency-management](https://github.com/spring-gradle-plugins/dependency-management-plugin) plugin using a legacy method to apply the plugin (source -> [here](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application)).

Apply the plugin in this way, doesn't give access to the API the plugin offers to access for instance, the `managedVersions` as explained [here](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#working-with-managed-versions-programmatic-access).

**Comment by wilkinsona** [comment]
There are pros and cons to the two approaches. As the dependency management plugin is a dependency of Spring Boot's plugin, using apply allows the plugin to be applied without specifying its version. The alternative is [discussed elsewhere in the documentation](https://docs.spring.io/spring-boot/gradle-plugin/managing-dependencies.html#managing-dependencies.dependency-management-plugin.using-in-isolation).

> Apply the plugin in this way, doesn't give access to the API the plugin offers

I'm not aware of any differences in terms of the API that's available when using one of the two methods of applying the plugin. Can you please provide a minimal example that reproduces the behavior you've described?

**Comment by SimoneGiusso** [comment]
> I'm not aware of any differences in terms of the API that's available when using one of the two methods of applying the plugin. Can you please provide a minimal example that reproduces the behavior you've described?

You can use this [project](https://github.com/SimoneGiusso/spring-integration-sftp-demo) and simply add `dependencyManagement.managedVersions["org.springframework:spring-core"]!! ` [here](https://github.com/SimoneGiusso/spring-integration-sftp-demo/blob/8c7eaf08d65581eb30dd0dc448970174987cd343/app/build.gradle.kts#L54), between line 53 and 54 and run `./gradlew clean build assemble`. It should fail,

**Comment by wilkinsona** [comment]
Thanks. That's a limitation of the Kotlin DSL that's [briefly mentioned in Gradle's documentation](https://docs.gradle.org/current/userguide/kotlin_dsl.html). As shown in the documentation for Boot's Gradle plugin that I linked to above, you need to use the `the<T>()` function:

```
the<io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension>().managedVersions["org.springframework:spring-core"]
```

Given this, and the pros and cons discussed above, I don't think we should make a change here. This may change in the future depending on https://github.com/spring-io/initializr/issues/1428.
