### ISSUE TITLE
Update commons-compress from 1.25.0 to 1.26.2

### ISSUE THREAD

**Issue by martymcfry** [spring-projects/spring-boot#40969]
Looking to see if `commons-compress` library can be updated from 1.25.0 to 1.26.2 in the `spring-boot/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/build.gradle` file.

I know it says in the DO NOT Raise an Issue about managed dependencies that I don't need to do this, but it looks like [commons compress](https://mvnrepository.com/artifact/org.apache.commons/commons-compress) released the 1.26.0 version without the 2 direct vulnerabilities on Feb 19th.  [1.25.0 link for reference](https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.25.0) 

Could I raise the PR, or help solve the problem? Thanks.

**Comment by philwebb** [comment]
Unfortunately upgrading commons-compress isn't as simple as it fist appears due to compatibility issues. Luckily, the CVEs are a false positive for us since we don't use commons-compress with untrusted input.

I'm going to mark this as a duplicate of #39368. Once that issue is fixed, we can consider an upgrade for Spring Boot 3.4.

**Comment by qwertychouskie** [comment]
Is there a recommended workaround in the meantime?  Is it safe to override the dependency using constraints in Gradle, or will that break some functionality?  Even if the attacks are not possible with the way Spring uses the library, it still causes noisy warnings in our monitoring tool, which makes other warnings less likely to be spotted as quickly as possible.

**Comment by qwertychouskie** [comment]
> Unfortunately upgrading commons-compress isn't as simple as it fist appears due to compatibility issues. Luckily, the CVEs are a false positive for us since we don't use commons-compress with untrusted input.
> 
> I'm going to mark this as a duplicate of [#39368](https://github.com/spring-projects/spring-boot/issues/39368). Once that issue is fixed, we can consider an upgrade for Spring Boot 3.4.

It seems this wasn't fixed in 3.4.x.  Is this fixed in 3.5.0?

**Comment by wilkinsona** [comment]
Spring Boot doesn't have an opinion about the version of Commons Compress that appears on an application's classpath. Where are you seeing the dependency? If it's through one of Boot's build plugins then we may be able to do something. If it's on the application's own classpath then we cannot.
