### ISSUE TITLE
LogbackLoggingSystem: make getLoggerContext() protected for easy sub-classing

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#4096]
We'd like to reuse/extend `LogbackLoggingSystem` with additional custom behaviour. For this we need access to the Logback `LoggerContext` being configured. Unfortunately, `LogbackLoggingSystem.getLoggerContext()` is `private`. Would it be possible to make it `protected` instead?

**Comment by snicoll** [comment]
Can you share what you're trying to change please? Maybe we could give you a way to do that without exposing the whole `LoggerContext`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by brenuart** [comment]
Request was related to issue https://github.com/spring-projects/spring-boot/issues/4026
In addition, having access to the `LoggerContext` allows one to reuse existing code and customise the configuration process. One of the examples is register our own log back actions or property resolving mechanism.

**Comment by snicoll** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
