### ISSUE TITLE
Lombok Unexpected Deletion Issue in **Spring Boot Project v3.2.5**

### ISSUE THREAD

**Issue by Fiigueiredo** [spring-projects/spring-boot#40970]
**Problem Description:**

When starting a new Spring Boot application using Spring Initializr, I noticed that Lombok was included in the project dependencies. However, during the construction of the project, I noticed that Lombok was being deleted due to a specific setting in the pom.xml. This setting can cause problems as it prevents Lombok annotations from working properly during development.

**Problematic Configuration Details:**

In the pom.xml file, there is a section that instructs the spring-boot-maven-plugin to exclude Lombok from the build:
![lombok](https://github.com/spring-projects/spring-boot/assets/106840038/9a299e0b-eaff-472e-83cb-84bd93b12db6)

**Proposed Solution:**

To resolve this issue and ensure that Lombok works correctly in your project, you need to remove the Lombok exclusion section from the pom.xml and ensure that the Lombok dependencies are correctly configured. 

**Additional Steps:**

Install the Lombok Plugin in your IDE: Make sure that the Lombok plugin is installed in your integrated development environment (IDE), such as IntelliJ IDEA or Eclipse, so that Lombok annotations are recognized correctly.
Rebuild the Project: After adjusting the pom.xml, run the mvn clean install command to ensure that all dependencies are resolved correctly and that the project is recompiled.

**Nota:**

> I'd like to point out that I don't have much experience with advanced Maven and Spring Boot settings. If this issue has already been resolved or a better approach exists, please disregard this insis. Thank you

**Comment by philwebb** [comment]
The Lombok exclusion should only apply to the `spring-boot-maven-plugin` and it shouldn't stop Lombok from working. You should see that in the generated project there is also the following depenency:

```xml
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <optional>true</optional>
</dependency>
```

I'm not sure what's causing Lombok to fail for you, I think we're going to need a sample project and detailed instructions on how to reproduce the issue.

If you want to provide those, please open a new issue at https://github.com/spring-io/start.spring.io since that's the project responsible for generating the POM xml file.

**Comment by quangthangit** [comment]
lombok is installed but not working

**Comment by DipDeepCode** [comment]
I noticed that if you switch Annotation Processors settings to **Obtain processors from project classpath**, then Lombok works correctly
![abc](https://github.com/user-attachments/assets/30c535b5-bfbc-4168-8084-d00d8e9e3d10)
