### ISSUE TITLE
Improve consistency of documentation guidelines for packaging and running applications

### ISSUE THREAD

**Issue by abelsromero** [spring-projects/spring-boot#40977]
It's not the best to run Spring Boot as JAR applications directly. However, the documentation is inconsistent in this message and depends on what page you land from a web search. I think it could be improved.

* [Dockerfiles](https://docs.spring.io/spring-boot/reference/container-images/dockerfiles.html) is fine imo.
* [Cloud Native Buildpacks](https://docs.spring.io/spring-boot/reference/container-images/cloud-native-buildpacks.html) is vague is the improvements it provides, someone unfamiliar with the other page may assume that when the text says "Dockerfiles are just one way to build docker images", it means any Dockerfile is fine. No need to include all, but something could be added from the Dockerfiles page.
* [Packaging Your Application for Production](https://docs.spring.io/spring-boot/reference/using/packaging-for-production.html) says `Executable jars can be used for production deployment` which I think should be removed and the doc could include some info about how to extract the JAR. Also [Running Your Application](https://docs.spring.io/spring-boot/reference/using/running-your-application.html) could get some disclaimers also.

**Comment by sdeleuze** [comment]
I think that's mainly [Packaging Your Application for Production](https://docs.spring.io/spring-boot/reference/using/packaging-for-production.html) that could take advantage of links to https://docs.spring.io/spring-boot/reference/deployment/efficient.html#deployment.efficient.unpacking and related refinements.
