### ISSUE TITLE
Gradle warning: Build service is being used by task without the corresponding declaration via 'Task#usesService'

### ISSUE THREAD

**Issue by asashour** [spring-projects/spring-boot#40994]
On building, there is a warning, the details of which can be seen by using `--warning-mode=all`, which is:

> Task :spring-boot-project:spring-boot:checkKotlinGradlePluginConfigurationErrors
Build service 'KotlinToolingDiagnosticsCollector_2090800888' is being used by task ':spring-boot-project:spring-boot:checkKotlinGradlePluginConfigurationErrors' without the corresponding declaration via 'Task#usesService'. This will fail with an error in Gradle 8.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/7.6.4/userguide/upgrading_version_7.html#undeclared_build_service_usage

**Comment by wilkinsona** [comment]
This is out of Spring Boot's control as `checkKotlinGradlePluginConfigurationErrors` is a task in Kotlin's Gradle plugin.

Duplicates https://youtrack.jetbrains.com/issue/KT-63165/Gradle-checkKotlinGradlePluginConfigurationErrors-uses-deprecated-Gradle-behavior.
