### ISSUE TITLE
Kotlin runApplication<Application>(*args) isn't detecting Java Controllers.

### ISSUE THREAD

**Issue by Fliperdo** [spring-projects/spring-boot#40999]
If you start a Spring Application with Kotlin code like so:
```kotlin
@SpringBootApplication
class Application

fun main(args: Array<String>) {
	runApplication<Application>(*args)
}
```
Spring will not be able to detect `@Controller` classes written in Java like so:
```java
@Controller
public class TestController {
    @GetMapping("/test")
    public String getTestPage(Model model) {
        return "test";
    }
}
```
If you run the application with an identical java version like:
```java
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```
Then it can pickup both java and kotlin controllers.

Project structure:
![image](https://github.com/spring-projects/spring-boot/assets/7141199/3032aef7-ce74-4560-af8a-d5fb9dfd31f5)

**Comment by wilkinsona** [comment]
Please share a minimal example and describe exactly how you're building and running the application. We need to know how Maven or Gradle is configured to verify that the right plugins are in place. We also need to know how you're running the application as this affects how its classpath is created. This is particularly important if you're running it from IDEA and using Gradle as IDEA can be configure to delegate to Gradle or to run the application itself, but of which form the classpath differently.

**Comment by Fliperdo** [comment]
Hey @wilkinsona, went to make the example project, and haven't been able to reproduce the issue on my personal project or within the example. Not sure what caused that behavior, sorry for the extra administrative work. Closing this ticket as not reproducible. Thanks

**Comment by wilkinsona** [comment]
No problem. Thanks for letting us know.
