### ISSUE TITLE
Upgrade to XMLUnit Core - 2.10.0

### ISSUE THREAD

**Issue by islonik** [spring-projects/spring-boot#41029]
link: https://mvnrepository.com/artifact/org.xmlunit/xmlunit-core/2.10.0
type: dependency-upgrade
Milestone: 3.2.7; 3.3.1

**Comment by wilkinsona** [comment]
Thanks but, as described in the issue template, we don't need accept issues for straightforward dependency upgrades. We'll upgrade in due course using our semi-automated process. Note that, as 2.10.0, is a new minor release, the upgrade will happen in Spring Boot 3.4 at the earliest. In the meantime, you can override Spring Boot's dependency management to meet your needs.
