### ISSUE TITLE
Add dependency management for hazelcast-hibernate4

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#4102]
Since Hazelcast is fairly popular as a Hibernate Second Level Cache provider and Spring Boot already provides dependency management for its core and spring modules, it might be useful to also add dependency management for hibernate4 module.

**Comment by snicoll** [comment]
ping @wilkinsona - I guess the general hazelcast support in 1.3 warrants it.

**Comment by wilkinsona** [comment]
Given that `hazelcast-hibernate4' is released as part of the same logical unit as the other modules for which we already have dependency management, I think it makes sense to add this one too.

**Comment by wilkinsona** [comment]
Closing in favour of #4103.
