### ISSUE TITLE
Running as maven plugin works, but fails as packaged application

### ISSUE THREAD

**Issue by jtmelton** [spring-projects/spring-boot#4108]
I'm trying to run an app. When running with 'mvn spring-boot:run' it starts up and works fine. 

However, when I run as a packaged application ('java -jar ...') I get a FileNotFoundException that looks like: 

`Caused by: java.io.FileNotFoundException: /.../appsensor-ws-rest-server-boot/target/appsensor-ws-rest-server-boot-0.0.1-SNAPSHOT.jar!/lib/appsensor-ws-rest-server-2.2.0-SNAPSHOT.jar (No such file or directory)`

When I look at the generated jar via 

`jar -tf target/appsensor-ws-rest-server-boot-0.0.1-SNAPSHOT.jar | grep ws-rest-server`

, I get: 

`lib/appsensor-ws-rest-server-2.2.0-SNAPSHOT.jar`

So the file appears to be there. Thoughts?

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
