### ISSUE TITLE
Add Support for --project-name Option in Docker Compose

### ISSUE THREAD

**Issue by osopromadze** [spring-projects/spring-boot#41086]
### Description:
Requesting support for the `--project-name` option in Docker Compose within the `spring-boot-docker-compose` project. This feature would enable specifying a custom project name directly in the application.yml configuration.
### Current Behavior:
The current configuration does not support setting a custom Docker Compose project name via `application.yml`.
### Proposed Enhancement:
Introduce a new property `spring.docker.compose.project-name` to set the Docker Compose project name.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I think this is a specific case of https://github.com/spring-projects/spring-boot/issues/38763.

**Comment by osopromadze** [comment]
Thanks @mhalbritter for suggestion, I will use this property.
