### ISSUE TITLE
AOT causes Logback configuration error when using include

### ISSUE THREAD

**Issue by michael-wirth** [spring-projects/spring-boot#41081]
Starting an application with AOT and a custom Logback configuration file (logback-spring.xml) with `<include>` elements can cause configuration errors (specially with file appenders).

The issue is caused by loading the serialized `/META-INF/spring/logback-model` and processing the model again.

By processing the model all `<include>` elements will load the configuration files again and attach the parsed submodules to the existing ones loaded from the serialized file. 

This might not cause issues for a ConsoleAppender, but will cause a configuration error for FileAppender (same file name).

### Breakpoint in ch.qos.logback.core.model.processor.IncludeModelHandler
![Screenshot_20240611_210157](https://github.com/spring-projects/spring-boot/assets/3389626/2bf5a3b3-8e1a-4163-8237-7c79686d5581)

### Version
Tested with Spring Boot 3.3.1-SNAPSHOT and Java 21

### Stacktrace:
```
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - 'FileNamePattern' option has the same value "/tmp/spring.log.%d{yyyy-MM-dd}.%i.gz" as that given for appender [FILE] defined earlier.
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Collisions detected with FileAppender/RollingAppender instances defined earlier. Aborting.
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - For more information, please visit http://logback.qos.ch/codes.html#earlier_fa_collision
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:347)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
 
```

### logback-spring.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration>
<configuration debug="false">
    <springProperty scope="context" name="application" source="spring.application.name"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml" />
    <property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}/spring.log}"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
    <include resource="org/springframework/boot/logging/logback/file-appender.xml" />

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="FILE" />
    </root>
</configuration>
```

### Reproducing the issue:
[demo.zip](https://github.com/user-attachments/files/15795266/demo.zip)
```bash
unzip demo.zip
cd demo
mvn package
java -jar -Dspring.aot.enabled=true target/demo-0.0.1-SNAPSHOT.jar
```

**Comment by mhalbritter** [comment]
This works in Boot 3.2.x. Interestingly with Boot 3.3.x, the native image built from that AOT processed application works fine.

**Comment by wilkinsona** [comment]
This looks like another consequence of the include-related changes made in Logback 1.5.5.

With Spring Boot 3.3 and Logback 1.5.5+, AOT processing of logback.xml results in a serialized model that contains IncludeModel nodes. These nodes have, as sub-models, the configuration that's been read from the included XML file. When the application is started with AOT enabled, the serialized model is processed and the IncludeModel nodes are handled. The XML is processed again and the model that's read from it is added to the sub-models of the IncludeModel, alongside the existing sub-models that had already been created during AOT processing. This results in everything that was included being declared twice.

**Comment by umeshmishra099** [comment]
@wilkinsona 
We are doing an upgrade from spring boot 3.2.4 to 3.4.3 and getting same issue .

**Comment by wilkinsona** [comment]
@umeshmishra099 if you would like us to investigate, please open a new issue with a minimal sample that reproduces the problem. The original sample that was provided with this issue works fine with 3.4.3 so I suspect you may have a slightly different problem.
