### ISSUE TITLE
Rework Cloud Foundry actuator support behind a pluggable abstraction

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#41135]
We would like to change the `/cloudfoundryapplication` actuator support to a pluggable abstraction to allow more extensions in the future.

**Comment by philwebb** [comment]
Tasks:

- [ ] Work out what to do with `WebFluxAdditionalHealthEndpointPathsConfiguration`, `JerseyAdditionalHealthEndpointPathsConfiguration`, `MvcAdditionalHealthEndpointPathsConfiguration`
- [ ] See if we can remove `@ConditionalOnAvailableEndpoint.considerEndpointExposers`, currently used in `MvcAdditionalHealthEndpointPathsConfiguration`
- [ ] Determine if `SbomEndpointAutoConfiguration` not having `EndpointExposure.CLOUD_FOUNDRY` is intentional
- [ ] Deprecate EndpointExposure.CLOUD_FOUNDRY
- [ ] Add `EndpointExposer` to replace EndpointExposure.CLOUD_FOUNDRY
- [ ] Add value alias to `@ConditionalOnAvailableEndpoint` and migrate simple conditions

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/41890 for the SBOM endpoint's web extension on CF.

**Comment by philwebb** [comment]
"Add value alias to @ConditionalOnAvailableEndpoint and migrate simple conditions" should probably be a different issue as it's not really related.
