### ISSUE TITLE
Fix links to Spring AMQP's javadoc

### ISSUE THREAD

**Issue by jourteen** [spring-projects/spring-boot#41144]
Following links from [AMQP section](https://docs.spring.io/spring-boot/reference/messaging/amqp.html) of Spring Boot Reference lead to 404 error page:
- https://docs.spring.io/spring-amqp/docs/3.1.5/api/rabbit/core/RabbitMessagingTemplate.html
- https://docs.spring.io/spring-amqp/docs/3.1.5/api/rabbit/annotation/EnableRabbit.html

The correct links are:
- https://docs.spring.io/spring-amqp/docs/3.1.5/api/org/springframework/amqp/rabbit/core/RabbitMessagingTemplate.html
- https://docs.spring.io/spring-amqp/docs/3.1.5/api/org/springframework/amqp/rabbit/annotation/EnableRabbit.html

**Comment by wilkinsona** [comment]
Thanks for noticing and reporting this, @jourteen.
