### ISSUE TITLE
Upgrade to Oracle Database 23.4.0.24.05

### ISSUE THREAD

**Issue by chas678** [spring-projects/spring-boot#41147]
Can revert fixes for issue: https://github.com/spring-projects/spring-boot/issues/38943
as no longer seems to apply
Oracle has removed the warning words so appears that OJDBC 11 Release 23.4.0.24.05
is OK for production use - revert the restriction in the Spring dependencies?

Refs:

- https://download.oracle.com/otn-pub/otn_software/jdbc/23c/Bugs-fixed-in-23ai.txt
- https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html

**Comment by wilkinsona** [comment]
We'll have to update our dependency management as the upgrade process reports that several modules are missing when upgrading from 21.9.0.0 to 23.4.0.24.05:

- `com.oracle.database.jdbc.debug:ojdbc11-debug`
- `com.oracle.database.jdbc.debug:ojdbc11-observability-debug`
- `com.oracle.database.jdbc.debug:ojdbc11_g`
- `com.oracle.database.jdbc.debug:ojdbc11dms_g`
- `com.oracle.database.jdbc.debug:ojdbc8-debug`
- `com.oracle.database.jdbc.debug:ojdbc8-observability-debug`
- `com.oracle.database.jdbc.debug:ojdbc8_g`
- `com.oracle.database.jdbc.debug:ojdbc8dms_g`
- `com.oracle.database.observability:dms`
- `com.oracle.database.observability:ojdbc11-observability`
- `com.oracle.database.observability:ojdbc11dms`
- `com.oracle.database.observability:ojdbc8-observability`
- `com.oracle.database.observability:ojdbc8dms`
- `com.oracle.database.security:osdt_cert`
- `com.oracle.database.security:osdt_core`
