### ISSUE TITLE
Add support for DB2 AS400 drivers and datasource

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#4115]
Currently the `DatabaseDriver` doesn't know about DB2 AS400 driver classes.

**Comment by snicoll** [comment]
Duplicates #4114

**Comment by mdeinum** [comment]
Well no because DB2 AS400 is different as plain DB2... even the URLs are different `jdbc:as400` as opposed to `jdbc:db2`.

**Comment by snicoll** [comment]
Sorry, it wasn't obvious. Why are you creating two issues anyway? General DB2 support issue would have been fine, isn't it?

**Comment by mdeinum** [comment]
I figured adding support for DB2 and AS400 could be done in separate branches and merged separately. Didn't want to put it into a single branch...

**Comment by snicoll** [comment]
Not sure why but let's do this now the issues are created.
