### ISSUE TITLE
Add docker compose support for apache/activemq-classic

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#41165]
We currently support `symptoma/activemq`, but test containers uses `apache/activemq-classic` so I wonder if we should unify.

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. I don't think you're missing anything. The support looks complete to me and [it is documented](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose.service-connections).

**Comment by philwebb** [comment]
Sorry, I added this one in a bit of a rush yesterday. I was expecting a single `ConnectionDetailsFactory` implementation with two supported names but it looks like the environment keys are different so that's probably why we have two distinct implementations.
