### ISSUE TITLE
When virtual threads are enabled, configure Spring Integration's task scheduler to use them

### ISSUE THREAD

**Issue by csh0034** [spring-projects/spring-boot#41188]
In the PR below, WebSocketMessagingAutoConfiguration has been modified to use a virtual thread executor
> https://github.com/spring-projects/spring-boot/pull/39611

```java
public class WebSocketMessagingAutoConfiguration {
  // ...
  WebSocketMessageConverterConfiguration(ObjectMapper objectMapper,
    Map<String, AsyncTaskExecutor> taskExecutors) {
    this.objectMapper = objectMapper;
    this.executor = determineAsyncTaskExecutor(taskExecutors);
  }

  private static AsyncTaskExecutor determineAsyncTaskExecutor(Map<String, AsyncTaskExecutor> taskExecutors) {
    if (taskExecutors.size() == 1) {
      return taskExecutors.values().iterator().next();
    }
    return taskExecutors.get(TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME);
  }

  // ...
}
```

Upon checking the taskExecutors being injected, it is taskScheduler.  
When used with spring-integration, the following Bean is being configured first.   
Is it possible to modify it to allow for auto-configuration?

```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnBean(TaskSchedulerBuilder.class)
@ConditionalOnMissingBean(name = IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)
@SuppressWarnings("removal")
public class IntegrationAutoConfiguration {
  // ..
  protected static class IntegrationTaskSchedulerConfiguration {
    @Bean(name = IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)
    public ThreadPoolTaskScheduler taskScheduler(TaskSchedulerBuilder taskSchedulerBuilder,
      ObjectProvider<ThreadPoolTaskSchedulerBuilder> threadPoolTaskSchedulerBuilderProvider) {
      // ...
    }
  }
  // ..
}
```

Below is the configuration added without using auto-configuration.

```kotlin
@Configuration
class ExecutorConfig {
  @Bean(
    name = [
      TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME,
      AsyncAnnotationBeanPostProcessor.DEFAULT_TASK_EXECUTOR_BEAN_NAME
    ]
  )
  fun applicationTaskExecutorVirtualThreads(builder: SimpleAsyncTaskExecutorBuilder): SimpleAsyncTaskExecutor {
    return builder.build()
  }
}
```

Of course, the bottom properties are also set.

```yaml
spring:
  threads:
    virtual:
      enabled: true
```

**Comment by mhalbritter** [comment]
Ah, hm, `org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration.IntegrationTaskSchedulerConfiguration#taskScheduler` is executed if there's no `taskScheduler` bean. `org.springframework.boot.autoconfigure.task.TaskSchedulingConfigurations.TaskSchedulerConfiguration#taskSchedulerVirtualThreads` creates such a bean, but only if `@EnableScheduling` has been used on the main class.

So I guess we should make `IntegrationTaskSchedulerConfiguration` virtual threads aware.

**Comment by csh0034** [comment]
@mhalbritter 
I understand that `IntegrationTaskSchedulerConfiguration` needs to recognize virtual threads.

However, even when adding the following configuration, `IntegrationTaskSchedulerConfiguration` is called before `TaskSchedulerConfiguration`, and `TaskSchedulingConfigurations.TaskSchedulerConfiguration#taskSchedulerVirtualThreads` is not called.

```kotlin
@Configuration
@EnableScheduling
class ScheduleConfig
```

Is there a priority issue?

Additionally, as mentioned in the initial question, the executor assigned to `WebSocketMessageConverterConfiguration `should be `TaskSchedulerConfiguration.TaskSchedulerConfiguration#taskSchedulerVirtualThreads`, but this method is not called at all.
`WebSocketMessageConverterConfiguration.determineAsyncTaskExecutor` only has the taskScheduler created in `IntegrationAutoConfiguration.IntegrationTaskSchedulerConfiguration#taskScheduler`
> https://github.com/spring-projects/spring-boot/pull/39611/commits/e9bf2b32cf019a7c0f4854334d2f1a12e0f8d4a8

Should I provide a sample for verification?

**Comment by mhalbritter** [comment]
> Should I provide a sample for verification?

Yes, please.

**Comment by csh0034** [comment]
[websocket-sample.zip](https://github.com/user-attachments/files/15928234/websocket-sample.zip)

p.s. Even though I'm not using SockJS, I noticed that `defaultSockJsSchedulerContainer` is added in `WebSocketMessageConverterConfiguration.determineAsyncTaskExecutor`

It wasn't there in version 3.3.0, but it appears in version 3.3.1. I don't understand the reason for this change.

**Comment by csh0034** [comment]
It seems that the reason `TaskSchedulingConfigurations.TaskSchedulerConfiguration#taskSchedulerVirtualThreads` is not being called is due to `AbstractMessageBrokerConfiguration#messageBrokerTaskScheduler.`

**Comment by csh0034** [comment]
The `AbstractMessageBrokerConfiguration` in Spring has been modified to use the executor registered in ChannelRegistration, and `WebSocketMessagingAutoConfiguration` in Spring Boot has been changed to inject the auto-configured executor into `ChannelRegistration`.

However, due to the various Beans declared in Spring's `AbstractMessageBrokerConfiguration`, `TaskExecutorConfigurations.TaskExecutorConfiguration` in Spring Boot is not called.

```text
TaskExecutorConfigurations.TaskExecutorConfiguration:
      Did not match:
         - @ConditionalOnMissingBean (types: java.util.concurrent.Executor; SearchStrategy: all) found beans of type 'java.util.concurrent.Executor' clientInboundChannelExecutor, clientOutboundChannelExecutor, brokerChannelExecutor (OnBeanCondition)
```

I'm adding this comment here because I'm unsure where to raise this issue.

**Comment by facewise** [comment]
@mhalbritter Hello. Can I pick up this issue?

**Comment by mhalbritter** [comment]
Sure. I'll assign you to the issue.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-projects/spring-boot/pull/41695. Thanks @facewise !

**Comment by csh0034** [comment]
@mhalbritter Should I create a separate issue for this comment?
> https://github.com/spring-projects/spring-boot/issues/41188#issuecomment-2185464365

**Comment by mhalbritter** [comment]
I haven't looked at https://github.com/spring-projects/spring-boot/pull/41695 in detail - if that PR doesn't solve that issue, then yes, please create a separate issue.

**Comment by facewise** [comment]
@csh0034

`TaskSchedulingAutoConfiguration` just checks if the `TaskScheduler` bean exists (plus, if you enabled `@EnableScheduling`), otherwise instantiates a fallback. And IMO it's intended and fits well to the purpose of autoconfiguration.

However if you add `@EnableWebSocketMessageBroker` in your configuration, imported `DelegatingWebSocketMessageBrokerConfiguration` creates a `TaskScheduler` bean for the message broker, which means it's not necessary to auto-configure a `TaskScheduler` bean.

But this issue is related to `IntegrationAutoConfiguration` as @mhalbritter said, since it is not aware of virtual threads.

I see you intended the virtual threads `TaskExecutor` to be injected in `WebSocketAutoConfiguration`, then #41695 can resolve it.
