### ISSUE TITLE
Major bug , Actuator path is executed inexplicably and returns

### ISSUE THREAD

**Issue by JavaLionLi** [spring-projects/spring-boot#41189]
The actuator path has been intercepted for security reasons.
But it was still accessed and loaded in this strange way.
All relevant paths can be accessed for data.
I guess there's a problem with the path judgment.
This is a very serious bug. I hope the community can solve it quickly.

![image](https://github.com/spring-projects/spring-boot/assets/31852897/25acee07-10ee-4162-9e38-7b08c94df280)

**Comment by wilkinsona** [comment]
@JavaLionLi If you believe you've found a major bug that could be a security issue, please do not post any more details here. Instead, please report the details of the problem responsibly as [described in our security policy](https://spring.io/security-policy).
