### ISSUE TITLE
Multi DataSource setup stopped working after upgrading Spring Boot to 3.3.x

### ISSUE THREAD

**Issue by icepuma** [spring-projects/spring-boot#41229]
## Description

After upgrading Spring Boot from `3.2.7` to `3.3.1` our multi-datasource based on the [AbstractRoutingDataSource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html) stopped working. We have a test that tests different `@Transactional` - combinations.

I did read a lot about the `LazyConnectionDataSourceProxy` in issues like #15480, but nothing really worked:
* Use `LazyConnectionDataSourceProxy` as my primary datasource with the target / readonly datasource  feature
* Wrapping our `AbstractRoutingDataSource` in `LazyConnectionDataSourceProxy`

## Versions
**OS:** macOS 14.5
**Java:** 17
**Spring Boot:**
* 3.2.7 ✅
* 3.3.0 ❌
* 3.3.1 ❌

## How to reproduce the issue
**Repository:** https://github.com/open-source-issues/spring-multi-datasource
**Command:** https://github.com/open-source-issues/spring-multi-datasource/blob/main/README.md

**Comment by philwebb** [comment]
Just coming here to say the same thing. Adding the following to the build scripts makes the tests pass:

```kotlin
buildscript {
    extra.apply {
        set("hibernate.version", "6.4.9.Final")
    }
}
```

To cause seems to be a change in `org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor` where the `commit()` method now checks `isPhysicallyConnected()` which returns `false`.

**Comment by icepuma** [comment]
Thanks for the explanation!

I think I got the [issue](https://hibernate.atlassian.net/browse/HHH-14867) and related [commit](https://github.com/hibernate/hibernate-orm/commit/4ac91f793f7a5436802d436c335c422581fa1a09).

Adding a simple `entityManager.createQuery("select 1").getResultList();` to all inner transactions fixes nearly all tests, because it forces a connection acquisition (took it from the test from the linked commit) and hence a call for `dataSource.getConnection()`.
