### ISSUE TITLE
Is the Spring Maven plugin still using CF Memory Calculator?

### ISSUE THREAD

**Issue by brunoborges** [spring-projects/spring-boot#41223]
I see that the documentation points to the CF Memory Calculator. Is it still the case?

Doc: https://spring.io/guides/gs/spring-boot-docker

https://github.com/cloudfoundry/java-buildpack-memory-calculator 

I wonder what is the relationship with Packeto's Buildpack: https://paketo.io/docs/howto/java/

**Comment by philwebb** [comment]
I don't think that phrase is accurate anymore. I've opened https://github.com/spring-guides/gs-spring-boot-docker/issues/112.

I think Paketo has a fork of the original code (https://github.com/paketo-buildpacks/libjvm/blob/main/helper/memory_calculator.go)

**Comment by brunoborges** [comment]
@philwebb where is the buildpack used by the Spring Maven Plugin?

**Comment by bclozel** [comment]
@brunoborges We're using the `paketobuildpacks/builder-jammy-base:latest` builder by default, [but this is something that users can configure](https://docs.spring.io/spring-boot/maven-plugin/build-image.html#build-image.customization).
