### ISSUE TITLE
mvn spring-boot:build-image command failing to create docker image of Spring Boot application when Docker Desktop version 4.31.x is installed

### ISSUE THREAD

**Issue by Abomicode** [spring-projects/spring-boot#41233]
Hello Everyone,
Issue: When creating a docker image of a Spring Boot application with the command (mvn spring-boot:build-image) having Docker Desktop version 4.31.x installed, I faced a consistent error -> Illegal char <:> at index 5: npipe:////./pipe/dockerDesktopLinuxEngine
When downgrading to Docker Desktop version 4.30.0 everything works fine and the docker images are also getting created successfully.
Is anybody facing the same issue or if I am doing anything wrong? Thanks.

Docker Desktop version: 4.31.x
Spring Boot version: 3.2.3

Please let me know if you need any more details about the issue.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/41199.
