### ISSUE TITLE
Add support for official kafka containers

### ISSUE THREAD

**Issue by gbaso** [spring-projects/spring-boot#41242]
Testcontainer `1.19.8` (managed by Spring Boot `3.3.1`) introduced `org.testcontainers.kafka.KafkaContainer` to support `apache/kafka`, alongside `org.testcontainers.containers.KafkaContainer` for `confluentinc/cp-kafka`.

Spring Boot supports the latter via `@ServiceConnection`, but not the former. A new `KafkaConnectionDetails` should be introduced to handle it.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/pull/40695.
