### ISSUE TITLE
@RedisHash timeToLive is a long, which is not compatible with the use of SPeL

### ISSUE THREAD

**Issue by alexisgayte** [spring-projects/spring-boot#41256]
org.springframework.data.redis.core.RedisHash has a field timeToLive typed as long therefor you cannot use SPeL/Spring-style expression.

timeToLive is often a property coming from env properties and therefor pass from parameter.
The current definition of @RedisHash is @RedisHash(value="myIndex", timeToLive=60)

The issue seems to come from a long running issue (compiler issue) here @Scheduler
<img width="709" alt="image" src="https://github.com/spring-projects/spring-boot/assets/7965274/b7011769-7efa-41b0-a427-9088d0d8d176">

However this is annoying because that force user of @RedisHash to define all index/entity globally using RedisMappingContext bean

```
    @Bean
    public RedisMappingContext keyValueMappingContext() {
        return new RedisMappingContext(new MappingConfiguration(new IndexConfiguration(), new MyKeyspaceConfiguration()));
    }

    public class MyKeyspaceConfiguration extends KeyspaceConfiguration {

        @Override
        protected Iterable<KeyspaceSettings> initialConfiguration() {
            KeyspaceSettings keyspace = new KeyspaceSettings(Index.class, "myindex:Index");
            keyspace.setTimeToLive(MyIndex.getTtlInSeconds().longValue());
            return Collections.singleton(keyspace);
        }
    }

```

**Comment by wilkinsona** [comment]
This is out of Spring Boot's control. `RedisHash` is part of [Spring Data Redis](https://github.com/spring-projects/spring-data-redis). SPeL and `@Scheduled` are part of [Spring Framework](https://github.com/spring-projects/spring-framework).
