### ISSUE TITLE
Replace RFC 7807 by RFC 9457 in property documentation

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-boot#41260]
Documentation for property `spring.mvc.problemdetails.enabled` should be updated with RFC 9457.

It would reflect the changes already done in Spring FWK : 
- https://github.com/spring-projects/spring-framework/commit/89ce63f1f36c2e526ea5270fb7a5b969043d7554
- https://github.com/spring-projects/spring-framework/issues/32806

See for example in : 
- https://github.com/spring-projects/spring-boot/blob/v3.3.1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/WebFluxProperties.java
- https://github.com/spring-projects/spring-boot/blob/v3.3.1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcProperties.java

**Comment by Aysha-py** [comment]
Hi @ghusta , Kindly allow me work on updating the documentation since there is no one working on this issue currently

**Comment by ghusta** [comment]
@Aysha-py : No problem, you can go ahead !

**Comment by snicoll** [comment]
@Aysha-py how is it going? Do you need help?
