### ISSUE TITLE
Endpoint Admin response no 'Keep-Alive' header

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#4126]
Hi I'm facing an issue about staled connections in persistent mode HTTP/1.1 when I invoke /health endpoint with embedded jetty Server.

I realise that the server doesn't set Header in HTTP response 

<pre>
Keep-Alive: timeout=15, max=100
</pre>

With my http client (this one from Apache Software foundation), in certain condition when no keep-alive response header is not received the connection should be considered as indefinite

I don't know if it's a bug of spring-boot or simply a jetty embedded container misconfigurer.

Below the roundtrip debug log 

<pre><code>

DEBUG - http-outgoing-0 >> "GET /admin/health HTTP/1.1[\r][\n]"
DEBUG - http-outgoing-0 >> "Host: localhost:11005[\r][\n]"
DEBUG - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
DEBUG - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.3.5 (java 1.5)[\r][\n]"
DEBUG - http-outgoing-0 >> "[\r][\n]"
DEBUG - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
DEBUG - http-outgoing-0 << "Date: Thu, 08 Oct 2015 14:37:15 GMT[\r][\n]"
DEBUG - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
DEBUG - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
DEBUG - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
DEBUG - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
DEBUG - http-outgoing-0 << "Expires: 0[\r][\n]"
DEBUG - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
DEBUG - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
DEBUG - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
DEBUG - http-outgoing-0 << "Server: Jetty(9.2.2.v20140723)[\r][\n]"
DEBUG - http-outgoing-0 << "[\r][\n]"
DEBUG - http-outgoing-0 << "F[\r][\n]"
DEBUG - http-outgoing-0 << "{"status":"UP"}"
</code></pre>

**Comment by wilkinsona** [comment]
If it's HTTP 1.1, why is the client sending `Connection: Keep-Alive` and expecting a response header? AFAIK, the `Connection: Keep-Alive` header is only need with HTTP 1.0 and in HTTP 1.1 all connections are persistent by default.

**Comment by RaphC** [comment]
Thanks for your response. By the way Keep-alive is only needed for HTTP 1.0 connections. 

As you said, It seems not necessary that my httpclient sends Connection: Keep-Alive header whereas It'a HTTP/1.1 request.

You can close this issue.

Regards,
