### ISSUE TITLE
Springboot connection database password acquisition error

### ISSUE THREAD

**Issue by DreamToffee** [spring-projects/spring-boot#41288]
When using springboot to connect to a database, use application.properties and application.yml to connect to the database. With the same configuration, you can connect normally when using application.properties, but you will get the wrong password when using application.yml,I uploaded a public warehouse instance according to the developer's request, and this is the warehouse address I uploaded

[https://github.com/DreamToffee/springProblem.git](url)

**Comment by wilkinsona** [comment]
Duplicates #41287.
