### ISSUE TITLE
Logback rollingPolicy min and max values

### ISSUE THREAD

**Issue by zachariahyoung** [spring-projects/spring-boot#4129]
In the file-appender.xml should the configuration include a minIndex and maxIndex?  It seems like the files would never roll off.

**Comment by wilkinsona** [comment]
We're just using the defaults for `minIndex` and `maxIndex` [which are 1 and 7 respectively](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/rolling/FixedWindowRollingPolicy.java#L47-L50). It might be worth raising a Logback issue asking for the defaults to be documented.
