### ISSUE TITLE
Auto-configure Jersey to use application context's ObjectMapper

### ISSUE THREAD

**Issue by toellrich** [spring-projects/spring-boot#4131]
I have defined the following bean inside my Application class:

```java
@Bean
public Jackson2ObjectMapperBuilder jacksonBuilder() {
  return new Jackson2ObjectMapperBuilder()
      .modules(new ThreeTenModule()) // ThreeTen backport
      .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS,
            DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
}
```

As soon as I switch to Jersey my Jackson configuration is no longer being used. To define a bean like this doesn't work either:

```java
@Bean
@Primary
public ObjectMapper objectMapper() {
  ObjectMapper objectMapper = new ObjectMapper();
  objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
  objectMapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
  objectMapper.registerModule(new ThreeTenModule());
  return objectMapper;
}
```

Workaround is to create a JAX-RS ContextResolver that creates the ObjectMapper and register it with the ResourceConfig

**Comment by wilkinsona** [comment]
The Jersey auto-configuration doesn't do anything with Jackson at the moment. If it's possible to write a `ContextResolver` that has access to the application context or its beans then this should be a pretty straightforward addition. Pull requests welcome.

**Comment by eddumelendez** [comment]
PR was submitted to fix this. Feedback is welcome to polish the PR :)

**Comment by wilkinsona** [comment]
Moving to 1.4.0. Unfortunately it's a bit late to be tackling this in 1.3.0.
