### ISSUE TITLE
Log message for GraphQL applications when no schema was found

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#41320]
See spring-projects/spring-graphql#1002 for background.

Using the GraphQL and Web starters to build REST API that uses a GraphQL client is perfectly valid use case. Right now the GraphQL auto-configuration will build a GraphQL service only if a schema file has been detected, or a GraphQlSource has been contributed to the application. In some cases, developers are getting confused about this situation.

During startup we log a message with the schema information we have detected. We should consider logging a message if no schema was found. Note, we should only do this if there is a consistent way to do this  during startup, not too early in the process.

**Comment by xenoterracide** [comment]
I mean I found the whole whole not setting up the server a little weird if no schema files are found. Kind of feels like a do it anyway... Maybe something should always be there

**Comment by bclozel** [comment]
I have tried various approaches, unsuccessfully:
* logging anything during the condition processing is way too early in the process and could be logged multiple times if the condition is reused elsewhere
* we can't log anything in the `GraphQlAutoConfiguration` itself as the condition includes all known use cases (schema resources on the classpath, custom beans, etc).

I guess debugging the application will [output the auto-configuration report](https://docs.spring.io/spring-boot/how-to/application.html#howto.application.troubleshoot-auto-configuration) and this is the best way to find out why auto-configuration did not set up expected infrastructure. This is not specific to GraphQL support.
