### ISSUE TITLE
Invalid doc links when generating code from Spring Initializr

### ISSUE THREAD

**Issue by victorgawk** [spring-projects/spring-boot#41338]
When generating code from [Spring initializr](https://start.spring.io/) using project `Gradle - Groovy`, language `Java`  and version `3.3.1`, inside `HELP.md` file there is two invalid URLs resulting in `404 Not Found` error:

- https://docs.spring.io/spring-boot/docs/3.3.1/gradle-plugin/reference/html/
- https://docs.spring.io/spring-boot/docs/3.3.1/gradle-plugin/reference/html/#build-image

Error when opening these links in Google Chrome:
![image](https://github.com/spring-projects/spring-boot/assets/6736720/8eab9cb4-05c7-4883-964d-40a2abab638b)

Code generation example:
https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.3.1&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=

**Comment by wilkinsona** [comment]
Thanks, @victorgawk. Can you please open a [start.spring.io issue](https://github.com/spring-io/start.spring.io/issues) for this?

**Comment by rishiraj88** [comment]
@victorgawk , yes, the targets to these links are not available. I have checked as well.
The links are broken.

The following is the listing of [https://docs.spring.io/spring-boot/docs/](https://docs.spring.io/spring-boot/docs/) -
![screenshot 1720420230](https://github.com/spring-projects/spring-boot/assets/13426986/12f0d045-4294-4b5f-a858-9d7bc6786d3c)

In the listing, when we follow `3.3.x`, we land onto the page [Spring Boot :: Spring Boot 3.3.x](https://docs.spring.io/spring-boot/).

Then, using the navigation in left pane one can visit [the documentation notes for Gradle plugin](https://docs.spring.io/spring-boot/gradle-plugin/index.html)-
![screenshot 1720420230](https://github.com/spring-projects/spring-boot/assets/13426986/b5907615-2442-44dc-9729-38a3eee15cbe)

**Comment by victorgawk** [comment]
> Thanks, @victorgawk. Can you please open a [start.spring.io issue](https://github.com/spring-io/start.spring.io/issues) for this?

issue opened https://github.com/spring-io/start.spring.io/issues/1529
