### ISSUE TITLE
Is it possible to use mvn -Pnative spring-boot:build-image to build an image and simultaneously upload it to an image repository, similar to the Jib plugin?

### ISSUE THREAD

**Issue by ChildrenGreens** [spring-projects/spring-boot#41356]
Problem Description:

Our project has just been upgraded from Spring Boot 2.x to Spring Boot 3.2.x, and from JDK 8 to GraalVM 21. However, we have encountered some issues. Previously, we used Google Jib to build and upload images to the image repository. Now, while using the GraalVM Native Image plugin, we face the following problems:

It is necessary to download Docker tools to generate Docker images.
Images can only be manually uploaded to the remote repository.
Is it possible to optimize the above two points?

**Comment by bclozel** [comment]
Have you seen [the image publishing section](https://docs.spring.io/spring-boot/gradle-plugin/packaging-oci-image.html#build-image.examples.publish) in the reference documentation ?

**Comment by ChildrenGreens** [comment]
> Have you seen [the image publishing section](https://docs.spring.io/spring-boot/gradle-plugin/packaging-oci-image.html#build-image.examples.publish) in the reference documentation ?

Sorry, I didn't notice it before. Thank you for providing it. I took a look, and it seems to meet my current needs. Thank you very much.
