### ISSUE TITLE
Document that logging.file.name and logging.file.path cannot be used together

### ISSUE THREAD

**Issue by naris** [spring-projects/spring-boot#41351]
The spring boot documentation on [logging file output](https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/features.html#features.logging.file-output) does not adequately explain that if you set both logging.file.name and logging.file.path that the path will be completely ignored and only the value in logging.file.name will be used.

Therefore, either the documentation should be updated to make this clear as while documentation includes a matrix as to what the path will be if you set either name or path it does not explicitly have a case where both values set, apparently expecting the reader to get that it kinda implies that setting both values would ignore the path?

Of course, the better, more intuitive solution would be to use both the file and path values, if they are both set, to produce the log file path/name as one would expect to be the case as there are separate file and path settings :/

**Comment by wilkinsona** [comment]
We'll improve the documentation.

> Of course, the better, more intuitive solution would be to use both the file and path values

This is being tracked by  #16231.
