### ISSUE TITLE
spring run fails with ClassNotFoundException for org.apache.commons.logging.LogFactory 

### ISSUE THREAD

**Issue by epiphyllum** [spring-projects/spring-boot#4138]
![5a140b55-0ca2-4e7b-b153-e7f83eeb48a2](https://cloud.githubusercontent.com/assets/8348065/10408511/b3a94e54-6f31-11e5-957e-2bc3e0ce4092.png)

**Comment by wilkinsona** [comment]
This works for me with `1.2.6.RELEASE`. `org/apache/commons/logging/LogFactory` is loaded from `jcl-over-slf4j-1.7.12.jar` in my Maven cache:

```
[Loaded org.apache.commons.logging.LogFactory from file:/Users/awilkinson/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.jar]
```

I would guess that you have a corrupted download in your cache. Please try clearing out your Maven cache and running the app again.

**Comment by wilkinsona** [comment]
Closing due to lack of response. If this is still a problem, please let us know and we can re-open the issue.
