### ISSUE TITLE
Deprecate spring.gson.lenient in favor of a new spring.gson.strictness property

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#41430]
When doing this, we may want to duplicate the `Strictness` enum in our own code to preserve backwards compatibility with earlier versions of Gson. That said, I'm not sure how common it will be to want to downgrade the version of Gson so the duplication may not be necessary. Flagging for team attention to see what everyone else thinks.

**Comment by philwebb** [comment]
We've decided to use the GSON enum. We can introduce our own if a compelling reason is raised.
