### ISSUE TITLE
Metrics in "/actuator/prometheus" are not consistent in a multi nodes environment (kubernetes)

### ISSUE THREAD

**Issue by ZakariaAitErrami** [spring-projects/spring-boot#41434]
**Description**
My application is built using Spring Boot and is deployed with multiple replicas in a Kubernetes cluster. I am using the /actuator/prometheus endpoint to expose metrics. However, I've noticed that the metrics returned by this endpoint are different and inconsistent depending on which server instance is accessed. When I refresh the /actuator/prometheus page, the values change based on the server I hit.

Is there a way to make the metric values consistent across all nodes?

**Comment by jonatan-ivanov** [comment]
fyi: https://github.com/micrometer-metrics/micrometer/issues/5293
