### ISSUE TITLE
Support testcontainers-redis

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#41450]
Our support for Testcontainers and Redis currently relies on the container being named `redis`. We could add support for https://github.com/redis-developer/testcontainers-redis and its `RedisContainer`. With https://github.com/spring-projects/spring-boot/pull/41327, supporting `RedisStackContainer` (that uses `redis/redis-stack-server`) would also make sense.

**Comment by philwebb** [comment]
🫡

**Comment by wilkinsona** [comment]
Re-opening to look at supporting `RedisStackContainer` and to update the docs.
