### ISSUE TITLE
Provide a mechanism to opt out of including the CycloneDX SBOM in the uber jar or war

### ISSUE THREAD

**Issue by aykborstelmann** [spring-projects/spring-boot#41478]
Since Spring Boot 3.3 the gradle plugin copies the bom generated by cyclonedx in the resources, s.t. the jars contain these files. CycloneDx generates a creation timestamp into the generated SBOM file and thus this file changes on each execution. All tasks having a input on the jar (such as `test`) but also the the jar generation task itself thus have different gradle cache keys each execution and therefore effectively the cache is disabled for all projects that have the `cyclonedx` plugin applied and configured. 

I am aware that one could argue that this should be fixed by `cyclonedx`. On the other hand I believe this timestamp is necessary for other tools (such as the dependency track) and I don't think they will disable it. 

One quick fix for all consumers is to add the following into their `build.gradle` (use the correct filename here): 

```groovy
    normalization {
        runtimeClasspath {
            ignore "META-INF/sbom/bom.xml"
        }
    }
```

**Comment by wilkinsona** [comment]
> One quick fix for all consumers is to add the following into their `build.gradle`

I don't think we can do this as it may result in an old sbom being used and it getting out of sync with the application's dependencies. That could result in a false negative for a security vulnerability. 

> I am aware that one could argue that this should be fixed by cyclonedx

Indeed, that's exactly what I think should happen. Please raise an issue against the CycloneDX plugin.

**Comment by aykborstelmann** [comment]
Thanks for the fast answer !

> I don't think we can do this as it may result in an old sbom being used and it getting out of sync with the application's dependencies. That could result in a false negative for a security vulnerability.

This could not happen, since if the dependencies change, all tasks depending on the jar and those that build the jar would be retriggered anyways. However, I agree that it is not that clean to base on this. 

I will give it a try in opening an issue at cyclonedx's side, but don't hope for too much as I think the timestamp is relevant from their perspective.

Still, if you decide to not add something as normalization to fix this issue, I would value at least a toggle to disable this feature from spring boot perspective. 
In our project we don't need it. We only have cyclonedx for dependency track, yet our build times multiplied since the spring boot plugin update. I could imagine more people to have the same circumstances as we do.

**Comment by wilkinsona** [comment]
> I will give it a try in opening an issue at cyclonedx's side, but don't hope for too much as I think the timestamp is relevant from their perspective.

Given that SBOMs are important for security, I would hope that they will do something about it as build repeatability is also important for security. The ability for a build to produce byte-for-byte identical output allows a tag to be verified and for binaries to be recreated if necessary.

> I would value at least a toggle to disable this feature from spring boot perspective. In our project we don't need it.

That's a situation that I don't think we'd considered thus far. Thanks for raising it. I'll re-open this issue so that we can consider what to do.

**Comment by wilkinsona** [comment]
>  I think the timestamp is relevant from their perspective

I just experimented a bit and it's not clear how relevant the timestamp is. It isn't considered when Gradle performs an up-to-date check of the `cyclonedxBom` task so you can end up with an SBOM with a `metadata.timestamp` that's stale.

Interestingly, [cloud native buildpacks](https://buildpacks.io/docs/for-app-developers/how-to/build-outputs/download-sbom/), that value repeatability very highly, don't include a `timestamp` in the SBOM's metadata. Here's an example from the SBOM for the `packet-buildpacks_executable-jar`:

```json
    "metadata":
    {
        "component":
        {
            "bom-ref": "8dcbd803f369ec9f",
            "name": "/workspace",
            "type": "file"
        },
        "tools":
        {
            "components":
            [
                {
                    "author": "anchore",
                    "name": "syft",
                    "type": "application",
                    "version": "0.99.0"
                }
            ]
        }
    }
```

**Comment by wilkinsona** [comment]
It's not quite a toggle, but you can stop the SBOM from being included in the uber jar (and the classpath of `bootRun`) like this:

```
tasks.named('processResources') {
	exclude { "application.cdx.json".equals(it.name) }
}
```

**Comment by wilkinsona** [comment]
We discussed this yesterday and concluded that we don't want to do anything here, for now at least. Given the workaround above, the Maven plugin already supporting repeatable builds, and it looking like the Gradle plugin is heading in the same direction, the need for an opt-out isn't clear at the moment. We can reconsider in the future if the need becomes clear.

**Comment by vpavic** [comment]
The decision to hook in CycloneDX plugin so deep into the build lifecycle (`ProcessResources` depends on it) without any signal from the developer that its really needed there is difficult to understand and quite honestly frustrating to deal with in practice.

A non-trivial real-world project will have SBOM whose size is easily into MBs - it takes some noticeable time to generate such SBOM file and this translates into wasted resources when working with project locally and impacts build times on the CI.

Additionally it grows the deployment artifact size and (as reported in this issue) potentially messes up the build cache - workaround for these concerns is possibly but the point is that the inconveniences add up and have a real expense associated with them.

So I'd ask you to reconsider this issue, and not only include opt-out mechanism but to also flip the default and hook CycloneDX plugin in the build lifecycle only if developers express opt into it.

**Comment by wilkinsona** [comment]
> A non-trivial real-world project will have SBOM whose size is easily into MBs - it takes some noticeable time to generate such SBOM file and this translates into wasted resources when working with project locally and impacts build times on the CI.

In my experience, Gradle's up-to-date checking does a good job of minimising the time that's taken. See the discussion starting [here](https://github.com/spring-projects/spring-boot/issues/40890#issuecomment-2159816215) for some concrete numbers.

> potentially messes up the build cache

As far as I can tell, the task only executes if a compile or runtime dependency has changed. Such a change would require `test` tasks (for example) to run again anyway.

> So I'd ask you to reconsider this issue, and not only include opt-out mechanism but to also flip the default and hook CycloneDX plugin in the build lifecycle only if developers express opt into it.

These things are always hard to gauge but, thus far, I don't think we've seen enough evidence to warrant inconveniencing users who are happy with the current behavior by flipping the default. We will continue to monitor things.

**Comment by M3yo** [comment]
@wilkinsona 

In our case, all "heavy-duty" tests from all apps were constantly re-run in CI even if the code or libs hasn't changed. 

Gradle cache is tricked beause of the cycloned `application.cdx.json` file... This file is regenerated at every build on CI, (since CI restarts with "fresh" repository)
This file has a timestamp in it, so when the `processResources` task copies this file in `build/resources/main/META-INF/sbom/`  directory, it changes the fingerprint of all child tasks (test and jacocoTestReport) therefore it reruns all tests.

I've test-it with a basic demo app, when the [cyclonedx-gradle-plugin](https://github.com/CycloneDX/cyclonedx-gradle-plugin) is present and gradle cache enabled, "./gradlew clean build" retriggers tests execution for each run. Without plugin, tests task is  "FROM-CACHE" as expected.

**Comment by wilkinsona** [comment]
Perhaps you can move things forward by exploring a contribution that fixes https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/292?
