### ISSUE TITLE
Upgrade to AspectJ 1.9.22.1

### ISSUE THREAD

**Issue by stephen-j-arnold** [spring-projects/spring-boot#41470]
I understand that you've asked not to raise issues for managed dependencies, but this one may have been missed? 

The managed version of spring-aspects in boot 3.3.0 and 3.3.1 are explicitly asking for 1.9.22.1 (aspectjweaver specifically), but that's being overridden by the spring-boot-dependencies bom as a managed dependency at 1.9.22?

**Comment by wilkinsona** [comment]
Thanks for spotting this, @stephen-j-arnold. There was a bug in our upgrade tooling when the number of numeric components in a version changes from 3 to 4. I'll fix that in gh-41471.
