### ISSUE TITLE
jooq version upgrade to 3.7.0

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#4147]
Now jooq version is 3.6.2, and jooq 3.7.0 just released with Java 8 support, any plan to upgrade jooq to 3.7.0?

**Comment by lukaseder** [comment]
Spring folks, Lukas from the jOOQ team here. Is there any preferred way of communication when we release new versions? Just let us know. We're very happy to tell you about each individual update.

**Comment by philwebb** [comment]
Hi @lukaseder, raising a new issue in this repo for new jOOQ releases would be best. @wilkinsona does tend to track these things anyway but we sometimes miss updates.

**Comment by lukaseder** [comment]
OK, perfect. I suspect you're not really interested in patch releases for old versions, only the very latest, right?

**Comment by wilkinsona** [comment]
Right, for now at least. Boot 1.3 will track the jOOQ 3.7 line. If the timing works out then Boot 1.4 might start using jOOQ 3.8 (assuming such a release is planned). At that time we'll be interested in both 3.7 and 3.8 releases.

**Comment by lukaseder** [comment]
OK, I see - thanks for the clarification. Yes, 3.8 is expected in Q1 2016, although no promises as you may imagine :)
