### ISSUE TITLE
Unable to get extended health information when using security.ignored=/health

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#4152]
Hi all,

I've got a minor issue with my `/health` pages where I'm unable to get extended health info if I add the health page url to `security.ignored`. Sample app contains little more than:

```java
@Test
public void extendedHealth() throws Exception {
	mockMvc.perform(get("/health"))
			.andDo(print())
			.andExpect(status().isOk())
			.andExpect(jsonPath("$.diskSpace.status").value("UP"));
}
```
`application.yml`:
```yml
security:
  ignored:
    - /health
endpoints:
  health:
    sensitive: false
```
`pom.xml`:
```xml
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
		</dependency>
	</dependencies>
```

I know I can configure security through `HttpSecurity`, but I'd like to configure the security for my /health endpoint through my configuration files, as that way I can store the option in my shared spring cloud config server.

Is there anyway to get the desired behavior when only using config settings?

**Comment by timtebeek** [comment]
Reading the source it only works when `management.security.enabled=false`. This is something that's not mentions in the docs under [Security with HealthIndicators](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_security_with_healthindicators), but only mentioned under: [Customizing the management server port](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-management-server-port).

Might be worth to note under the 40.3, or a change in code to make it match expectations from the docs.

**Comment by philwebb** [comment]
We've added something to the latest SNAPSHOT docs. See http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-health-access-restrictions.

**Comment by philwebb** [comment]
I wonder if we need an additional property so that you can keep endpoints secure but still expose full information from `/health`.

**Comment by timtebeek** [comment]
Ah great, thanks! I'd missed that update to the docs, that really help clear things up. For me personally the issue is resolved as is, but you're welcome to keep it open if you want to see if others might find a need for it.

**Comment by philwebb** [comment]
I'll close it for now and see if anyone else raises an issue. Cheers!
