### ISSUE TITLE
DevTools restart doesn't close context when shutdown hook's been disabled

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4153]
I'm not yet sure if this should just be something that we document, or if we should do something smarter. The DevTools currently rely on the application context's shutdown hook to close it during a restart. If you explicitly disable the shutdown hook you end up with a second context being refreshed while the first is still active. If you're working on a web app that fails due to an HTTP port clash.

**Comment by philwebb** [comment]
We could perhaps add some kind of additional tracking for contexts that need to be closed. For now I'd settle for a documented known limitation.
