### ISSUE TITLE
Proposal for Content Revision on Wiki - "Spring Boot 3.0 Migration Guide"

### ISSUE THREAD

**Issue by namsoo2** [spring-projects/spring-boot#41541]
In the [Configuration Properties Migration](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#configuration-properties-migration) section, it is recommended to revise the following Gradle configuration code:

```
runtime("org.springframework.boot:spring-boot-properties-migrator")
```
to:

```
runtimeOnly("org.springframework.boot:spring-boot-properties-migrator")
```
Starting from Spring Boot 3.0.x, Gradle 7.x (7.5 or later) or 8.x is required. 
https://docs.spring.io/spring-boot/docs/3.0.x/gradle-plugin/reference/htmlsingle/#introduction

Additionally, since version 7.x, Gradle has deprecated the runtime configuration in favor of runtimeOnly. 
[Gradle upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)
https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

**Comment by wilkinsona** [comment]
Thanks, @namsoo2. I've made the suggested correction.
