### ISSUE TITLE
Strage behaviour in DelegatingWebMvcConfiguration with 1.3.0.M5

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-boot#4154]
Hi, I've got a strange problem with `DelegatingWebMvcConfiguration`:

When I start our project without Spring Security ( `@SpringBootApplication(exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration.class)` ), everything is normal.
But when I enable Spring Security (by removing the exclude), I figured out, that `DelegatingWebMvcConfiguration`'s  `@Autowired(required = false) public void setConfigurers(List<WebMvcConfigurer> configurers)` method is getting called AFTER its `protected void addFormatters(FormatterRegistry registry)` method.

I can't figure out why this is happening. I tried to setup an extremely small test project, but there everything works as expected. I thought that `@Autowired setters` get called immediately after the constructor and before any other method can be invoked?

Thanks for your help.

**Comment by philwebb** [comment]
I would expect autowired methods to get called before `@Bean` methods such as `mvcConversionService` (which triggers `addFormatters`). Without a project that replicates the issue it's very hard to tell what's going on.

Perhaps you could add some breakpoints to those methods and attach details of the call stack? That might give us some clues.

**Comment by philwebb** [comment]
BTW is this something that you see behaving differently between 1.3.0.M5 and 1.2.6?

**Comment by benneq** [comment]
Thanks for the hint. I now tried 1.2.6.RELEASE (with default spring.version 4.1.7 and with spring.version 4.2.1) and I get exactly the same behavior: frist `addFormatters`, then `setConfigurers`.

I already got breakpoints in both methods, but there's some `EnhancerBySpringCGLIB` magic going on, and I can't really tell what's going on, because Eclipse can't open those files.

I now just ran the not-working version with Boot 1.3.0.M5 and here is what I could copy from Eclipse debugger:
1. call to `setFormatters`: http://pastebin.com/4MXnYwdf
2. call to `setConfigurers`: http://pastebin.com/tG7CsHJM

If I can give you any better information, please tell me. Sadly I can't share the project. If you can't get any useful information from the Stacks, I think I'm gonna remove classes one by one till it's working as expected, and then should be able to share a stripped down project that shows the misbehavior.

**Comment by philwebb** [comment]
I think something is causing early instantiation of `WebMvcAutoConfiguration` but it's still not clear what. The most likely candidate is `SpelExpression.getValue(EvaluationContext) line: 242`.

Can you work up the stacktrace from `SpelExpression` to see what the parameters are passed to `evaluateBeanDefinitionString`. We really need to know what bean is triggering all this.

**Comment by benneq** [comment]
This sounds like there's some problem with the `@SpelAssert` validation annotation i'm using: https://github.com/jirutka/validator-spring
I will remove this dependency and let you know

**Comment by benneq** [comment]
It wasn't the dependency. Though I just spent the last 3 hours with deleting code and starting and stopping the application :laughing: 
Now there are just a few files left and I can upload the code. I also found out where you can toggle that strange behavior, but not why that happens. I'll upload the code later this afternoon.

**Comment by benneq** [comment]
Here's the code: http://pastebin.com/JcU5Y5vL
And my pom.xml: http://pastebin.com/K5MKq2ww

---

I added two break points within `DelegatingWebMvcConfiguration`:
**`1.`** at the `setConfigurers` method
**`2.`** at the `addFormatters` method

Additionally I added a simple`@RestController` for testing purpose which tries to call my custom converter, but can't find it. `No converter found capable of converting from type test.Application$MyClass to type test.Application$YourClass`.

---

Within the code I made two comments: `#1` and `#2`. These are the places I found where you can switch the strange behavior on and off.
**`#1`**: Just add `exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration.class` to turn off Spring Security and it works. (removing spring security from pom.xml also works)
**`#2`**: Turn the `@Autowired ConversionService conversionService;` into a `@Lazy` autowireing.

As a workaround I can use of course `@Lazy @Autowired`. But it would be really interesting why this happens and if it can be solved in a clean way.

Thanks in advance!

**Comment by philwebb** [comment]
It appears that the SpEL expression is from Spring Security. The `WebSecurityConfiguration.setFilterChainProxySecurityConfigurer` method calls `autowiredWebSecurityConfigurersIgnoreParents.getWebSecurityConfigurers()`. This in turn gets all `WebSecurityConfigurer` beans.

One such bean is `org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration$ApplicationWebSecurityConfigurerAdapter`. For some reason this injects `mvcContentNegotiationManager` which then triggers the whole process.

**Comment by philwebb** [comment]
@benneq Can you try the latest `1.3.0.BUILD-SNAPSHOT` to see if we've managed to fix this?

**Comment by rwinch** [comment]
@philwebb I was able to try the latest SNAPSHOT and can confirm your changes resolved this issue for me.

**Comment by benneq** [comment]
Ah sorry, haven't seen your question. But I'm glad that this bug will be gone in 1.3.0.RC1 :+1:

**Comment by benneq** [comment]
Tested it with 1.3.0.RC1 and it works! Thank you!

**Comment by wilkinsona** [comment]
@benneq Thanks for testing
