### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-boot#41558]
On https://spring.io/projects/spring-boot#learn there are two broken links:

* 3.4.0-M1 links to https://docs.spring.io/spring-boot/3.4/index.html, which returns 404 Not Found.
* 3.3.3-SNAPSHOT links to https://docs.spring.io/spring-boot/3.3-SNAPSHOT/index.html, which returns 404 Not Found.

**Comment by aquashdw** [comment]
May or may not be relevant, but Search results also leads to 3.3-SNAPSHOT for current(3.3.2) reference docs. 
https://docs.spring.io/spring-boot/index.html
![image](https://github.com/user-attachments/assets/b535f1de-dbb7-4958-ba3b-e36318d06c79)
![image](https://github.com/user-attachments/assets/cc3b438d-460c-4113-9be6-91ebd2d83d5f)

**Comment by wilkinsona** [comment]
Thanks. The links are now working.
