### ISSUE TITLE
Review docs build configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#41573]
- `BUILD_REFNAME` needs to be set on "Sync Documentation" step
- `BUILD_VERSION` needs to be set on "Sync Documentation" step
- `REFERENCE` on "Install and Run Antora" should be named `BUILD_REFNAME`

**Comment by philwebb** [comment]
Fixed in 63742a9fa85e210c2a743722d7ff982799666d45
