### ISSUE TITLE
Hibernate Search Bytecode Enhancement Issue

### ISSUE THREAD

**Issue by aiden-sim** [spring-projects/spring-boot#41584]
I reported the following issue to the Hibernate team: https://hibernate.atlassian.net/browse/HSEARCH-5205

```
org.hibernate.engine.spi.EnhancedEntity.isAssignableFrom(Parent.class) is false (Parent wasn't enhanced)
org.hibernate.engine.spi.EnhancedEntity.isAssignableFrom(Child.class) is true (was enhanced).
```

The response I received was that this is an issue that occurs before Hibernate ORM is initialized.

Here is the address of my personal repository that reproduces the issue, and I hope it will be fixed if it is a bug.
Please check it out 
https://github.com/aiden-sim/hibernate-search-bytecode-issue

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/33255
