### ISSUE TITLE
Make application properties available in the Environment

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#41604]
For structured logging it would be useful if we could access application properties (such as `spring.application.version`, `spring.application.pid`) from the Environment. Adding them would also allow us to simplify `ResourceBanner` implementation.

**Comment by khairmuhammad** [comment]
Hi, Can I work on this?

**Comment by philwebb** [comment]
Thanks for the offer @khairmuhammad, but I think we need to do some design work to check how the overlap with `ResourceBanner` might work. I forgot to add the `pending-design-work` label (which I've now done).

**Comment by mhalbritter** [comment]
I've got something we should talk about in a team meeting.
