### ISSUE TITLE
Message publishing via Sink and OutputDestination times out with Spring Boot 3.2.2

### ISSUE THREAD

**Issue by wrwksexahatvani** [spring-projects/spring-boot#41602]
The `DummyEventProducerIntegrationTest` in the sample project https://github.com/andrashatvani/spring-demo/ times out once I upgrade Spring Boot to 3.2.2 in the POM. It works with the previous 3.2.1 as it has worked so far always.

**Comment by wilkinsona** [comment]
The sample project's using Spring Boot 3.3.1. 

> once I upgrade Spring Boot to 3.2.2 in the POM. It works with the previous 3.2.1 as it has worked so far always

I assume the above is a typo and you meant that it fails when you upgrade to 3.3.2 and that it works with 3.3.1. That's the behaviour that I see anyway.

This doesn't appear to be a Spring Boot problem as it works when Spring Integration is downgraded to 6.3.1. Please report the problem to [Spring Integration](https://github.com/spring-projects/spring-integration).
