### ISSUE TITLE
JSON Mime Type is missing

### ISSUE THREAD

**Issue by ghostd** [spring-projects/spring-boot#4161]
Hi,

MimeMappings does not contain the [standard JSON declaration](http://www.ietf.org/rfc/rfc4627.txt). When my application serves my file.json, no HTTP Content-Type headers are sent. Firefox reads the file but generates a warning "not well formed".

Here is my current workaround:
```
@Component
public class ServletCustomizer implements EmbeddedServletContainerCustomizer {

    @Override
    public void customize(ConfigurableEmbeddedServletContainer container) {
        MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
        mappings.add("json", "application/json");
        container.setMimeMappings(mappings);
    }
}
```

**Comment by htynkn** [comment]
I think the reason why spring-boot don't have json mime type is we are following the same mine type mappings as [tomcat] (https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/startup/Tomcat.java#L940)

**Comment by ghostd** [comment]
Ok, this is an acceptable reason IMO.
But that means Tomcat java mapping does not match its XML default configuration:
https://github.com/apache/tomcat/blob/trunk/conf/web.xml#L2071

You can close this issue if the reference code is the Tomcat java version.

**Comment by wilkinsona** [comment]
It's interesting that Tomcat has different defaults in Java code and in web.xml. I'd like to understand that difference and figure out which it makes most sense for us to align with.

**Comment by wilkinsona** [comment]
From a conversation with @markt-asf:

> conf/web.xml is used when running Tomcat ‘normally’ without o.a.c.startup.Tomcat. DEFAULT_MIME_MAPPINGS is used when using Tomcat.addWebapp(…). I believe neither are used if you use Tomcat.addContext(…)

On the reason for the difference between the two lists of mappings:

> Only that we haven't kept DEFAULT_MIME_MAPPINGS up to date with changes in conf/web.xml

Some advice on a definitive source for mime mappings:

> We update conf/web.xml from httpd periodically so you might want to take httpd's list as the definitive one. Don't know where they pull updates from.

**Comment by wilkinsona** [comment]
The different embedded containers have different mime mapping configurations. Both Jetty and Undertow have default mime mappings that Boot's mime mappings are then added to, whereas Tomcat just uses Boot's mime mappings. One consequence of this is that both Jetty and Undertow have a mapping for JSON while Tomcat does not.

**Comment by philwebb** [comment]
Seems sensible to add it (unless you object @wilkinsona)
