### ISSUE TITLE
ConversionService named `conversionService` is eagerly initialized

### ISSUE THREAD

**Issue by mikeldpl** [spring-projects/spring-boot#4162]
```java
@SpringBootApplication
public class TestApplication {
    @Bean
    public ConversionService conversionService(MyBean bean) {
         assert bean.anotherBean == null; // it is a problem ;)
         return null;
    }

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }
}

@Component
class MyBean {
     @Autowired
     public AnotherBean anotherBean;
} 
```

Beans in parameters in ConversionService redeclaration method have null on Autowired fields.

**Comment by snicoll** [comment]
A `ConversionService` with bean name `conversionService` is special as it is requested very early by a bean post processor.  I am afraid there is not much we can do besides adding a note in the documentation. I have renamed your bean definition to `fooConversionService` and it worked as you expect.

**Comment by mikeldpl** [comment]
How many are such special beans?
