### ISSUE TITLE
Auto-configure cache infrastructure to use a CacheResolver bean if present

### ISSUE THREAD

**Issue by Crain-32** [spring-projects/spring-boot#41644]
This can be seen an extension of this conversation from [Framework](https://github.com/spring-projects/spring-framework/issues/33282), which I originally posted thinking I was in Spring Boot's Issues (I've checked 5 times that this is Boot already while writing this)

Currently Spring Boot's Autoconfiguration will handle if you provide a `CacheManager` Bean, however won't handle if you provide a `CacheResolver` bean. Both beans should like either require `CachingConfigurer`, or not. Currently it's one requires it, the other doesn't.

**Comment by snicoll** [comment]
This is a fair point. The reason why this happens this way stems in framework. If you provide a `CacheManager` bean we will use that. For any other advanced configuration, the configurer is required. I am not sure this should be fixed here, actually, even if we already provided implementations of configurer in the past for convenience.

I'll check what our options are.

**Comment by snicoll** [comment]
Looking at the auto-configuration, and https://github.com/spring-projects/spring-boot/issues/5201 in particular, I think there's not much we can do at this point. 

`CacheResolver` is an advanced SPI and anything we'd do to automatically wrap it could break others. Thanks for the suggestion, in any case.
