### ISSUE TITLE
Maven binaries should be cleared if necessary

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#41649]
Running `./gradlew clean` in `spring-boot-project/spring-boot-tools/spring-boot-maven-plugin` does not seem to clear prepared Maven binaries for integration tests. 

As a result, when older versions are made out of scope, local tests still run against them as `build/maven-binaries` is not cleaned.

**Comment by wilkinsona** [comment]
There are a couple of things:

1. `clean` needs to wipe out the `maven-binaries` directory
2. `clean` should not be necessary as the contents of the `maven-binaries` directory should be kept in sync with the configured binaries that we're testing against.

**Comment by wilkinsona** [comment]
> clean needs to wipe out the maven-binaries directory

As far as I can tell, this already happens. We need to address 2 though.
