### ISSUE TITLE
Scrollbar disappears on mouseover in Chrome Desktop on the new Antora documentation site

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-boot#41655]
According to [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes#documentation-updates):

> The [Spring Boot documentation](https://docs.spring.io/spring-boot/3.3/) has been migrated to Antora, providing more structure as well as better search capabilities.

I opened the site and instantly found a bug: the right scrollbar disappears when mouse is pointed over it. But this happens only in Chrome. The only other browser I have is Firefox and the scrollbar works fine in Firefox.

The theme (light/dark) doesn't affect the bug. The scrollbar always disapears on mouseover.

Functionally the scrollbar continues to work. I can drag it with my mouse and page scrolls, but the dragging is very uncomfortable as I'm literally dragging an invisible UI element. :)

I tried to open the official [Antora docs](https://docs.antora.org/antora/latest/) that presumably also implemented with Antora and this bug doesn't happen there. The scrollbar looks different, though. In Chrome it looks like the default (thick) browser scrollbar.

On the [Spring Boot documentation](https://docs.spring.io/spring-boot/3.3/) site the scrollbar in Chrome looks like a custom (thin and without arrows) HTML component.

Maybe it's just a different version of `antora-ui` or different configuration. Quick search for known bugs related to scrollbar in older Antora versions didn't give me any results.

The scrollbar when mouse is not over it:
![image](https://github.com/user-attachments/assets/ab47638f-77a2-4761-9815-f4cd98426e84)

The scrollbar (or rather the absense of it) when mouse is over it:
![image](https://github.com/user-attachments/assets/ce54141a-a998-40e7-90e8-eeb40a8da911)

* OS: Windows 11
* Browser: Chrome 126.0.6478.183 (Official Build) (64-bit)

**Comment by xak2000** [comment]
Found the problem in `site.css`:

```
    ::-webkit-scrollbar-thumb:hover {
        background-color: var(--scrollbar_hover-thumb-color)
    }
```

If I change `var(--scrollbar_hover-thumb-color)` to e.g. `blue`, all works fine.

Maybe `--scrollbar_hover-thumb-color` is undefined or defined as transparent?

**Comment by xak2000** [comment]
Just found the dedicated [antora-ui-spring](https://github.com/spring-io/antora-ui-spring) repository. Probably it's worth to move this issue to this project then? Somebody with permissions please do this if possible. Please let me know if it is not possible and I'll re-create the issue there.

**Comment by scottfrederick** [comment]
Thanks @xak2000. [antora-ui-spring](https://github.com/spring-io/antora-ui-spring) is the right repository for this issue. I don't think we can move issues between GitHub orgs (i.e. from `spring-projects` to `spring-io`). If you could re-create the issue in `antora-ui-spring` we'll close this one.
