### ISSUE TITLE
FlywayAutoConfiguration is triggering framework's BeanPostProcessorChecker: not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by space88man** [spring-projects/spring-boot#41656]
FlywayAutoConfiguration.class is triggering the Spring Framework's BeanPostProcessorChecker:

```
2024-07-31T10:19:01 WARNING [main] org.springframework.context.support.PostProcessorRegistrationDelegate$BeanP
ostProcessorChecker Bean 'org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration' of type [org.
springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration] is not eligible for getting processed by al
l BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into
 a currently created BeanPostProcessor [grpcClientBeanPostProcessor]? Check the corresponding BeanPostProcesso
r declaration and its dependencies. 
```

Context:
- upgraded my application to Spring Boot 3.3.2; the same application at 3.3.1 does not have these logs
- this warning has also been seen by other 3rd party configuration classes (not just Flyway) and the diagnosis (see ref. below) is that the issue lies in the configuration class
- of all the configuration classes from this repo used by my application this is the only class that triggers the checker

Reference:
- https://github.com/spring-projects/spring-boot/issues/38558

**Comment by wilkinsona** [comment]
As the error message suggests, it's the definition of the post-processor that's the problem not the bean that's being eagerly injected. The declaration of `grpcClientBeanPostProcessor` and the dependencies that it injects (ideally a post-processor would have zero dependencies) that needs to be checked and corrected.
