### ISSUE TITLE
Spring cloud config refresh leads to thread starvation

### ISSUE THREAD

**Issue by Mobe91** [spring-projects/spring-boot#41650]
I am referring to this reported issue from 2023: https://github.com/spring-cloud/spring-cloud-config/issues/2341

I am raising this issue again here because there has been no reply on the original issue and because I am experiencing the same problem with a multi-instance spring-boot application deployment.

Are there any plans to address this or guidelines for how to work around it?

Versions used:
Spring-Boot: 3.1.6
Spring-Cloud: 2022.0.3

**Comment by snicoll** [comment]
There's no need to cross post. We'd need to move things forward on the issue you've referenced. One way to do that is to provide a way for the team to reproduce.

**Comment by Mobe91** [comment]
@snicoll Thank you for you reply, I understand. It would be good though to also provide this input to the OP. Otherwise it looks like this issue is being ignored, don't you think?
