### ISSUE TITLE
Resolving an environment variable for logging.config is not working for native builds

### ISSUE THREAD

**Issue by klopfdreh** [spring-projects/spring-boot#41663]
Because we want to use a different logging styles for the runtime and the build time, it seems that it is currently not possible to use this configuration:

```yml
logging:
  config: ${LOGGING_CONFIG_VALUE:classpath:logback.xml}
```

When you perform a native build without any `LOGGING_CONFIG_VALUE` environment variable `logback.xml` from classpath is used, but when you later on add the environment variable `LOGGING_CONFIG_VALUE` during runtime still logback.xml is used.

The only way to enforce a different logging configuration is to use it during the maven build e.g. `clean deploy -Pnative_build -DLOGGING_CONFIG_VALUE=classpath:logback-json.xml` for example

**Comment by snicoll** [comment]
> The only way to enforce a different logging configuration is to use it during the maven build

That's what you should be doing. Processing the logback.xml does not work in a native image so you have to specify the one you want at build-time. AOT transforms the XML into something that can be processed by a native image. Please review [this page](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM) and, in particular [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#logging).

**Comment by klopfdreh** [comment]
All right! Thank you! 👍
