### ISSUE TITLE
GraphQL should reply with HTTP 415 for unsupported content type

### ISSUE THREAD

**Issue by nictas** [spring-projects/spring-boot#41675]
Hi,

I receive a 404 response when I try to make a request to the `/graphql` endpoint with a wrong content type (`text/plain`, for example):
```json
{
	"timestamp": "2024-07-31T15:49:28.136+00:00",
	"status": 404,
	"error": "Not Found",
	"path": "/graphql"
}
```

![image](https://github.com/user-attachments/assets/73b13cea-bf48-4ff9-b081-ab238300311c)

This is a bit confusing because it leads you to think that there's something wrong with the GraphQL configuration in the application, whereas the actual problem is with the request.

I'm using version 3.3.2 of spring-boot-starter-graphql. The problem should be reproducible with any sample project but I'll attach my own just in case:
[graphql-demo.zip](https://github.com/user-attachments/files/16444380/graphql-demo.zip)

You can execute a GraphQL request with the following body to reproduce the issue:
```
{"query":"query getCurrentUser {\n\tgetCurrentUser \n}","operationName":"getCurrentUser"}
```
The authentication is basic with a username of "user" and the password written in the application logs.

**Comment by bclozel** [comment]
This is actually a Spring Boot enhancement, I've moved the issue accordingly.
In this case, we should return an [HTTP 415 status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415) and an "Accept" header that reflects what's expected.
