### ISSUE TITLE
JSP support broken in 3.2.8 (and most likely 3.3.2, 3.4.0-M1) because of a bug in Tomcat 10.1.26

### ISSUE THREAD

**Issue by chris-wareham-unseen-group** [spring-projects/spring-boot#41689]
JSP support is broken in Spring Boot 3.2.8 because of a bug in Tomcat 10.1.26, which was an updated dependency in this Spring Boot release.

Tomcat issue: https://bz-he-de.apache.org/bugzilla/show_bug.cgi?id=69216

On startup, an application using JSP as the templating language fails with the following error:

Caused by: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl

Downgrading to Spring Boot 3.2.7 solves the issue. I am unable to test with Spring Boot 3.3.2 or 3.4.0-M1, but since they include the same dependency upgrade I would expect them to be broken too, and the Tomcat issue linked above was from a user on 3.3.2.

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/41557
