### ISSUE TITLE
Consider managing versions for `graphql-java-extended-scalars` and `graphql-java-extended-validation`

### ISSUE THREAD

**Issue by nmck257** [spring-projects/spring-boot#41690]
(I couldn't find any existing issue if this has been discussed in the past)

Spring Boot provides version management for `com.graphql-java:graphql-java` already.

`graphql-java-extended-scalars` and `graphql-java-extended-validation` are companion libraries from the same organization, and they align on major version with `graphql-java`, but not on minor version:
https://github.com/graphql-java/graphql-java-extended-scalars#getting-started
https://github.com/graphql-java/graphql-java-extended-validation?tab=readme-ov-file#using

It's easy for a developer to assume they match precisely, and try to reuse the `graphql-java.version` property to select a compatible version for the `-extended-` libraries. This will work if the developer is lucky (eg `22.0` exists for both), but in many cases will fail (as of today, Spring Boot uses `22.1`, and that version does not exist for `-extended-scalars`).

It's also error-prone to rely on the developer to check the value of the version provided by Spring Boot (especially across upgrades) and select the right compatible version of the `-extended-` libraries.

Could these libraries be added to `spring-boot-dependencies`?

**Comment by bclozel** [comment]
This was considered in https://github.com/spring-projects/spring-graphql/issues/242 and declined. I don't think the situation changed since?

**Comment by nmck257** [comment]
Ah, yep, thanks for linking that issue. It sounds like a `graphql-java` bom would be the differentiator here, so, I've raised that topic over on their side: https://github.com/graphql-java/graphql-java/discussions/3677

**Comment by philwebb** [comment]
We'll close this one for now and keep an eye on https://github.com/graphql-java/graphql-java/discussions/3677
