### ISSUE TITLE
Define default value for OpenTelemetry Trace Exporter in auto-configuration

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-boot#41841]
🎁 **Enhancement**

**Context** 
Spring Boot application using OpenTelemetry for both metrics and traces.

**Problem**
The auto-configuration for Micrometer OTLP (providing support for OpenTelemetry Metrics) sets the exporter endpoint to `http://localhost:4318/v1/metrics`, in line with the common developer experience when running a Spring Boot application with the default configuration. However, the auto-configuration for the OpenTelemetry SDK (used for providing support for OpenTelemetry Traces) doesn't set any default value for the exporter endpoint. It used to be set to `http://localhost:4318/v1/traces`, but it was removed in https://github.com/spring-projects/spring-boot/commit/214f06083b6d79d4540564064d0dcefdad9d2a73 to allow using gRPC instead of HTTP. This behaviour is not the one I would expect from a Spring Boot auto-configuration and is also inconsistent with the Metrics auto-configuration.

**Suggestion**
It would be nice to bring back the default value for the OpenTelemetry Trace Exporter and find another way to allow replacing the HTTP exporter with a gRPC exporter, at least until https://github.com/spring-projects/spring-boot/pull/41213 is solved.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but I don't think we can do anything here. The suggestion you've made would be a (small) breaking change so the earliest that it could be made is in 3.4.x. #41213 is currently scheduled for that release so it would seem to be preferable to tackle that rather than having the churn of making the change proposed here and the change that would be needed for #41213 shortly thereafter. Have I misunderstood what you're proposing?

**Comment by ThomasVitale** [comment]
Thanks for the quick answer. If https://github.com/spring-projects/spring-boot/pull/41213 is still scheduled for 3.4.x, then I agree that it wouldn't make sense to make a temp change suggested in this issue, and instead address it as part of the other task. I might have misunderstood the state of https://github.com/spring-projects/spring-boot/pull/41213 after it got put on hold.

**Comment by wilkinsona** [comment]
Even if #41213 slips to 3.5.x, I wouldn't want the default to change in 3.4.x and then change again in 3.5.x. It's been as it is now since 3.2.x. Thanks for the suggestion but I think it's better overall that we leave the default as it currently is.

**Comment by ThomasVitale** [comment]
Understood, thank you
