### ISSUE TITLE
Try to fix static initializer formatting

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4187]
Old eclipse:

``` java
    private static final Set<Include> DEFAULT_INCLUDES;
    static {
        Set<Include> defaultIncludes = new LinkedHashSet<Include>();
        defaultIncludes.add(Include.REQUEST_HEADERS);
        defaultIncludes.add(Include.RESPONSE_HEADERS);
        defaultIncludes.add(Include.ERRORS);
        DEFAULT_INCLUDES = Collections.unmodifiableSet(defaultIncludes);
    }
```

New eclipse:

``` java
    private static final Set<Include> DEFAULT_INCLUDES;

    static {
        Set<Include> defaultIncludes = new LinkedHashSet<Include>();
        defaultIncludes.add(Include.REQUEST_HEADERS);
        defaultIncludes.add(Include.RESPONSE_HEADERS);
        defaultIncludes.add(Include.ERRORS);
        DEFAULT_INCLUDES = Collections.unmodifiableSet(defaultIncludes);
    }
```

**Comment by jadekler** [comment]
@philwebb Unless I'm missing something, this formatting is used in all 47 static initializers in the code.

**Comment by wilkinsona** [comment]
@jadekler The formatting is consistent, but it's consistently "wrong". This issue is intended to investigate convincing Eclipse Mars' code formatter to not add a blank line before the `static` block.

**Comment by jadekler** [comment]
@wilkinsona Ah! Gotcha, thanks

**Comment by dsyer** [comment]
Why the heck should anyone care?

**Comment by philwebb** [comment]
Probably nobody except me does.

**Comment by snicoll** [comment]
I care but I think we should discuss it (hence the label, can you please add it back?)

**Comment by philwebb** [comment]
We probably need to discuss the broader topic of Eclipse/IntelliJ differences, I've raised #4785 for that. We can leave this one for the simple Eclipse formatter fix.

**Comment by philwebb** [comment]
Yeah, I'm fine with it.
