### ISSUE TITLE
How to package war and jar？

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-boot#4190]
When package war , how to package classes into a jar, does not include the configuration file "src / main / resources" under

**Comment by philwebb** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

You might also want to check [this section of the reference documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content).
