### ISSUE TITLE
Merge SystemPublicMetrics in MetricRegistry when using dropwizard metrics.

### ISSUE THREAD

**Issue by celiovasconcelos** [spring-projects/spring-boot#4197]
Spring actuator is awesome.
It would be nice to see [system-metrics](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-system-metrics) in `MetricRegistry`.
Devs are being forced to workaround like [this](http://stackoverflow.com/a/33124992/393046).

**Comment by sshcherbakov** [comment]
+1

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
