### ISSUE TITLE
Weird metrics behaviour when Request Method:OPTIONS

### ISSUE THREAD

**Issue by celiovasconcelos** [spring-projects/spring-boot#4198]
```
@RequestMapping(value = "/search/{id}", method = { RequestMethod.GET })
```

When calling OPTIONS `htttp://localhost:8080/search/142`
This register two metrics with the @PathVariable value

```
somepackage.status.200.search.143.count
somepackage.gauge.response.search.143.value
```

I think that OPTIONS should have a special treatment.
Also, it would be nice to have a property to disable OPTION metrics in `application.properties`

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
