### ISSUE TITLE
Release type conditionals are not working in documentation

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#41993]
The documentation Asciidoc source contains conditional statements for the release type, like:

```
ifeval::["{artifact-release-type}" == "release"]
...
endif::[]
```

and 

```
ifeval::["{artifact-release-type}" != "snapshot"]
...
endif::[]
```

The `artifact-release-type` attribute does not appear to be set when docs are built, so the `==` conditions are never true and the `!=` conditions are always true.

**Comment by izeye** [comment]
Given the changes are not in 3.2.9, this seems to have been assigned to a wrong milestone. It seems to belong to 3.3.3 milestone.
