### ISSUE TITLE
Use early static registration of EventPublishingContextWrapper in tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42005]
See https://github.com/spring-projects/spring-boot/issues/41439#issuecomment-2303907367.

We should try to make things work seamlessly with JUnit and possibly consider making some form of `EventPublisherBeansContextWrapper.addWrapperIfNecessary` public so that folks can all it directly.

**Comment by wilkinsona** [comment]
Somewhat related to this, `shouldPublishEventsWhenContextStorageIsInitializedEarly()` in `OpenTelemetryAutoConfigurationTests` is [100% flaky at the moment](https://ge.spring.io/scans/tests?search.rootProjectNames=spring-boot-build&search.tags=main&search.timeZoneId=Europe%2FLondon&tests.container=org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfigurationTests&tests.sortField=FLAKY&tests.test=shouldPublishEventsWhenContextStorageIsInitializedEarly()).
