### ISSUE TITLE
Enable Jersey baseURI to be set via configuration property (as an alternative to @ApplicationPath)

### ISSUE THREAD

**Issue by poznachowski** [spring-projects/spring-boot#4201]
I'm preparing a Spring Boot starter for my company. We have a specific baseURI used among our services, but I'd like to make that configurable. Currently it is only possible via @ApplicationPath annotation. It would be nice to have it extractable to a property, hence I could use the same value for my Swagger configuration.

I found it fairly easy to do in JerseyAutoConfiguration - findPath() method. However I had to copy the whole JerseyAutoConfiguration class. Configurable value could take precedence over the annotation.

**Comment by snicoll** [comment]
@poznachowski can you have a look at https://github.com/eddumelendez/spring-boot/commit/e352aa6090d8ed9a516f30cab31c23083697b6c5 and check if that's what you are looking for?

**Comment by poznachowski** [comment]
@snicoll yes, that's exactly it.

**Comment by philwebb** [comment]
Duplicates #4202
