### ISSUE TITLE
spring boot 3.3.2 with spring-cloud-netflix missing servo metrics

### ISSUE THREAD

**Issue by huntkalio** [spring-projects/spring-boot#42033]
https://github.com/spring-cloud/spring-cloud-netflix/issues/4303

I use spring-cloud-netflix for eureka server，and use jmx_prometheus_javaagent to get metric from JMX。
A）：spring boot 2.7.18 + netflix-eureka-server-3.1.7
B）：spring boot 3.3.2 + netflix-eureka-server-4.1.3

In A I can get many metric like： com_netflix_servo_localRegistrySize_value （from eurekaserver servo）；but in B there is nothing 。How can I get servo metrics after I upgrade spring boot version？

**Comment by mhalbritter** [comment]
Please don't double post issues. I'll close this one and let's see what https://github.com/spring-cloud/spring-cloud-netflix/issues/4303 says.
