### ISSUE TITLE
Adding docs about `TaskDecorator` for TaskExecutor

### ISSUE THREAD

**Issue by jayleeinflab** [spring-projects/spring-boot#42036]
**Enhancement Request**

**Description:**

I found spring docs for `TaskExecutor` currently lacks detailed information regarding the usage of `TaskDecorator`. 

**Proposed Solution:**

- Add a section in the Spring documentation under the `TaskExecutor` topic that covers `TaskDecorator`.
- code examples demonstrating how to configure and use `TaskDecorator`

**Rationale:**

**Version:**

**Additional Information:**

If needed, I am happy to contribute by drafting the initial documentation for this enhancement.

**Comment by bclozel** [comment]
Duplicates # 42037
