### ISSUE TITLE
loaderImplementation=CLASSIC doesn't work with spring boot maven after spring boot 3.2.x

### ISSUE THREAD

**Issue by nicolas-zheng** [spring-projects/spring-boot#42035]
loaderImplementation=CLASSIC doesn't work with spring boot maven after spring boot 3.2.x, but Gradle plugin works.

I want to use the classical boot loader for some old library.
related to this release notes:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support

can reproduce this with https://start.spring.io/, create a simple web application, maven package a fat jar, found the fat jar always didn't change with or without this configuration.

```
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
      <executions>
        <execution>
          <goals>
            <goal>repackage</goal>
          </goals>
          <configuration>
            <loaderImplementation>CLASSIC</loaderImplementation>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

**Comment by bclozel** [comment]
> found the the jar always didn't change with or without this configuration.

This part is not clear to me. Please elaborate.

**Comment by nicolas-zheng** [comment]
> > found the the jar always didn't change with or without this configuration.
> 
> This part is not clear to me. Please elaborate.
I want to use the classical boot loader for some old library.
related to this part: 
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support]

**Comment by bclozel** [comment]
I still don't get it.

Please describe:
* what are you doing precisely (sharing a minimal sample app is even better)
* what behavior you are expecting
* what behavior you are seeing instead and why it's wrong

**Comment by nicolas-zheng** [comment]
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
      <executions>
        <execution>
          <goals>
            <goal>repackage</goal>
          </goals>
          <configuration>
            <loaderImplementation>CLASSIC</loaderImplementation>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>

with this config, I still got the new boot loader class in the fat jar

**Comment by bclozel** [comment]
But the classic implementation is still being used in this case, isn't it?
Why would you assume that the loader class would be filtered out of the resulting JAR?

**Comment by nicolas-zheng** [comment]
> But the classic implementation is still being used in this case, isn't it? Why would you assume that the loader class would be filtered out of the resulting JAR?



If you do find issues with the new implementation, however, we have provided a fallback option that will allow you to use the old code.

For Gradle users you can set the bootJar.loaderImplementation to org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC. For example:

**Comment by bclozel** [comment]
How to reproduce the issue:

1. create a maven project on start.spring.io
2. Use [the configuration for the CLASSIC nested Jar implementation](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support)
3. run `./mvnw package`
4. the packaged archive does not contain the classic implementation, only the new one:

```
jar -tvf target/demo-0.0.1-SNAPSHOT.jar | grep JarLauncher
   855 Fri Feb 01 00:00:00 CET 1980 org/springframework/boot/loader/launch/JarLauncher.class
```

**Comment by wilkinsona** [comment]
<id>repackage</id> was missing from the configuration. It should be:

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>repackage</id>
			<goals>
				<goal>repackage</goal>
			</goals>
			<configuration>
				<loaderImplementation>CLASSIC</loaderImplementation>
			</configuration>
		</execution>
	</executions>
</plugin>
```

I've corrected that on the wiki.

**Comment by bclozel** [comment]
Thanks @wilkinsona I totally missed that but and was looking into our integration tests (which are all good).
