### ISSUE TITLE
Using an empty string MongoDB 'replica-set-name' property will result in ClusterType=REPLICA_SET

### ISSUE THREAD

**Issue by miaoGod** [spring-projects/spring-boot#42055]
https://github.com/spring-projects/spring-boot/blob/5490e73922b37a7f0bdde43eb318cb1038b45d60/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoPropertiesClientSettingsBuilderCustomizer.java#L91

如代码所示，不对代码做StringUtils.isBlank处理，会导致ClusterSettings的ClusterType=REPLICA_SET，这可能会产生负面影响。

**Comment by philwebb** [comment]
Courtesy of Google Translate:

As shown in the code, not doing StringUtils.isBlank processing in the code will result in ClusterType=REPLICA_SET of ClusterSettings, which may have negative effects.

**Comment by miaoGod** [comment]
@philwebb 是的，我确实遇到了这种场景，详情如下：
由于预算有限，在测试环境的mongodb配置仅有一台实例，而生产的配置为两台实例(一主一从)，而在使用主从复制配置时，我使用的方式如下代码：
```yaml
spring:
  data:
    mongodb:
      replica-set-name: ${mongo.replicaSetName}
```
其中的mongo.replicaSetName引用的是application-{env}.properties中的配置

按照以上配置启动项目以后，我发现mongo.replicaSetName无论是否有值，ClusterSettings的ClusterType都会为REPLICA_SET，
但是如果我将replica-set-name配置项直接去掉而不是让他等于一个空字符串，ClusterSettings的ClusterType则为UNKNOWN

**Comment by philwebb** [comment]
That seems like a valid use-case. We'll fix this.
