### ISSUE TITLE
Add tip to correlation IDs documentation referencing spring.reactor.context-propagation=auto

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42054]

**Comment by mhalbritter** [comment]
In a servlet application, the logs look like this:

```
{"@timestamp":"2024-08-29T06:48:50.886628003Z","log.level":"INFO","process.pid":66723,"process.thread.name":"http-nio-9000-exec-1","service.name":"tracing-service-1","log.logger":"com.example.tracing_service_1.MyController","message":"index()","traceId":"66d019d24f3c84880516a1c3aa2368c5","spanId":"0516a1c3aa2368c5","ecs.version":"8.11"}
```

This is using Brave as a tracer. The `traceId` and the `spanId` are in the MDC and are automatically included in the log message.

**Comment by mhalbritter** [comment]
In a webflux application, the `traceId` and `spanId` is missing from the log message:

```json
{"@timestamp":"2024-08-29T06:58:19.344283535Z","log.level":"INFO","process.pid":72293,"process.thread.name":"reactor-http-epoll-3","service.name":"tracing-service-1","log.logger":"com.example.tracing_service_1.MyController","message":"index()","ecs.version":"8.11"}
```

**Comment by mhalbritter** [comment]
Same behavior with Otel instead of Brave.

**Comment by philwebb** [comment]
Seems like it generally works. I wonder if we should add a note in the docs about `spring.reactor.context-propagation=auto`?

**Comment by philwebb** [comment]
There is a note already at https://docs.spring.io/spring-boot/reference/actuator/observability.html. We can extract a small section and add a TIP next to the correlation IDs section.
