### ISSUE TITLE
Upgrade maven-resources-plugin to 2.7

### ISSUE THREAD

**Issue by shakuzen** [spring-projects/spring-boot#4206]
From the [Spring REST Docs documentation](http://docs.spring.io/spring-restdocs/docs/current-SNAPSHOT/reference/html5/#getting-started-build-configuration-maven-packaging) it shows to specify `maven-resources-plugin` as 2.7 as a sample configuration. When using the Spring Boot parent, Eclipse warns that you are overriding Spring Boot's managed version.

I think it would be a good idea to upgrade this plugin to the latest version (2.7) and avoid the warning when using both Spring REST Docs and Spring Boot parent.

**Comment by wilkinsona** [comment]
I only specified 2.7 in the Spring REST Docs documentation as it's the latest version. AFAIK, it'll work fine with earlier versions. I agree that Boot should upgrade to 2.7 but, in the meantime, you should be able to remove the version from your pom and things will work as expected.

**Comment by shakuzen** [comment]
@wilkinsona Yes, it isn't a problem. I just wanted to share the background on why I came across this and opened this issue.

**Comment by wilkinsona** [comment]
Excellent, thanks for the confirmation.

**Comment by snicoll** [comment]
Closing in favour of the pull request. 

Duplicates #4207
