### ISSUE TITLE
Interface SslStoreProvider replacement in Spring boot 3.3.2

### ISSUE THREAD

**Issue by ketantalreja** [spring-projects/spring-boot#42061]
Hi there, 
Recently I started migrating our app from spring boot 2.x to spring boot 3.3.2 and found backward compatible issues mainly with the interface `SslStoreProvider` which has been removed, and I would like to learn what would be the fix in this case. 

My code: 
`factory.setSslStoreProvider((SslStoreProvider) provider);`

Do I need to use SslBundles instead in the latest ver? 
Appreciate your inputs. 
Thanks.

**Comment by philwebb** [comment]
It depends what exactly you're trying to do. Using an `SslBundle` would be recommended if it's possible. The other option is to use a `TomcatConnectorCustomizer` and configure Tomcat directly. If you need further advice, please open a question on stackoverflow.com and provide a sample that shows something that represents the 2.x code you currently use.
