### ISSUE TITLE
Restore 1.2.x CI build to Java 7

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4209]
We shouldn't have upgraded the samples and we should been the CI build on 1.7

**Comment by philwebb** [comment]
Samples reverted in commit d84889b03cea49c55868f53f57571218afb7d4f0

**Comment by philwebb** [comment]
The CI has been restored and the Java 8 samples upgrade reverted.

**Comment by wilkinsona** [comment]
CI is green
