### ISSUE TITLE
Let DevTools show a global report of the set of java types involved for each restart

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#42102]
Hello

About Spring Boot DevTools: it works as expected. Therefore when is changed/added/deleted a set of java types appears in the console something like this as a template:

```
Restarting due to N class path changes (0 additions, N deletions, N modifications)
```

Just being curious if could be added a new property at [ Common Application Properties - Devtools Properties](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.devtools) to let show in the Console the set of these classes as a global report too. Something like:

```
Added:
-

Deleted:
com.aaa.bbb.One
com.aaa.bbb.Two
...

Modified:
com.aaa.bbb.Alpha
com.aaa.bbb.Beta
com.aaa.ccc.Zeta
```

Thanks for your understanding

**Comment by wilkinsona** [comment]
If you enable debug logging for `org.springframework.boot.devtools.autoconfigure`, the whole change set will already be logged immediately after the info message that you've already seen:

https://github.com/spring-projects/spring-boot/blob/41afc6adcf2059e1d1361d5ef618f79dd45d01af/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/autoconfigure/LocalDevToolsAutoConfiguration.java#L211-L212
