### ISSUE TITLE
Groovy 2.4.5 causes PermGen build errors on Java 7

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4210]
Due to #4209 we didn't notice this at the time of the upgrade but it appears that Groovy 2.4.5 is causing OutOfMemory errors when building the CLI. Rolling back to 2.4.4 locally seems to fix the issue.

**Comment by philwebb** [comment]
Failing build example here: https://build.spring.io/browse/BOOT-PUB3-163/log

**Comment by wilkinsona** [comment]
We decided to stick with 2.4.4 for 1.2.7.
