### ISSUE TITLE
Support Jaeger / custom propagation types in actuator tracing

### ISSUE THREAD

**Issue by artsidorenko** [spring-projects/spring-boot#42151]
Hi! I am trying to set up tracing for my application. We are used to receive traces from upstream with Jaeger format header ( `uber-trace-id` )

Currently there is support for W3C, B3 and B3_MULTI propagation types, jaeger is little bit deprecated, but still used format. 

Actually, it seems that there is no simple solution to add custom propagator to actuator configuration. All types are hardcoded ([here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/TracingProperties.java#L254) i guess) and there is no option to extend them with custom type (since [mapper here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/CompositeTextMapPropagator.java#L150)support only previously noticed types)

Simple solution for my issue is just add JAEGER format support in default configuration.
Customisation support seems to be more complex.

**Comment by wilkinsona** [comment]
You should be able to define your own `ContextPropagators` bean to take control of how propagation is performed. Have you tried that?

**Comment by artsidorenko** [comment]
Yeah, it seems to be a solution for my issue.
I added 
```
@AutoConfiguration
@AutoConfigureBefore(name = ["org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration"])
class JaegerPropagationAutoConfiguration {

    @Bean
    fun jaegerPropagator(): TextMapPropagator = JaegerPropagator.getInstance()
}
```

and everything works fine now. 
Didn't mention that there is option to register custom propagators
Thank you for quick reply!
