### ISSUE TITLE
Polish configuration property references

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#42162]
@sbrannen found a bug in our documentation: There's a `configprop:spring.aop.proxy-target-class` in https://docs.spring.io/spring-boot/reference/features/aop.html.

That should be `configprop:spring.aop.proxy-target-class[]`.

**Comment by wilkinsona** [comment]
There's one in https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/web.html#web.servlet.spring-mvc.content-negotiation too.
