### ISSUE TITLE
A serialization error causes an assignment to be sent abnormally

### ISSUE THREAD

**Issue by FQXCS** [spring-projects/spring-boot#42184]
![image](https://github.com/user-attachments/assets/f9973625-c2f8-4d65-8e89-bbc0151ffad8)

![image](https://github.com/user-attachments/assets/1d71d70e-82ad-43e9-8d09-100b8c9930f6)
This is the parameter of the request pass

![image](https://github.com/user-attachments/assets/eea7f813-d3c6-47b3-bb49-25fd224b39e8)
This is the background received parameter，The id in the child attribute was incorrectly assigned to the main attribute，Of course, there is also a parameter passing problem. The type in constructionBasisList should be passed to String, but was incorrectly passed to List

![image](https://github.com/user-attachments/assets/bd893c12-8950-4783-8736-9cbf5abb1c0e)
There is a processing done to prevent xss
jackson V2.11.4
spring-boot V2.7.10

**Comment by wilkinsona** [comment]
Thanks for the report, but Spring Boot 2.7.x is [no longer supported](https://spring.io/projects/spring-boot#support). This also appears to be a problem with Jackson which, other than its initial configuration, is out of Spring Boot's control.

If you can reproduce the problem with a supported version of Spring Boot (3.2 or later) and provide a minimal sample that demonstrates that Spring Boot is causing the problem, we can re-open the issue and take another look.

**Comment by FQXCS** [comment]
I upgraded the version to: spring-boot V3.2.9、jackson V2.15.4，But problems remain.
**This is the completion code:**
```
@Slf4j
public class JacksonXssClean extends JsonDeserializer<String> {
	@Override
	public String deserialize(JsonParser p, DeserializationContext ctxt) {
		try {
			return p.getValueAsString();
		}catch (Exception e){
			e.printStackTrace();
		}
		return null;
	}
}

@RequiredArgsConstructor
@Configuration
public class EfpxXssAutoConfiguration implements WebMvcConfigurer {
	@Bean
	public Jackson2ObjectMapperBuilderCustomizer xssJacksonCustomizer() {
		return builder -> builder.deserializerByType(String.class, new JacksonXssClean());
	}
}

@Data
public class MasterVo {
    private String id;
    private String masterName;
    private List<SlaveVo> slaveVoList;
}

@Data
public class SlaveVo {
    private String id;
    private String name;
    private String type;
    private String typeStr;
}

@RestController
@RequiredArgsConstructor
@RequestMapping("/test")
public class TestController {
    @PostMapping("/test01")
    public String temporaryStorage(@RequestBody MasterVo vo) {
        return "";
    }
}
```
**This is the request parameter:**
```
{
    "id": "8d4c1e7ab5184705a056389a755c4bce",
    "masterName": "test",
    "slaveVoList": [
        {
            "name": "slaveVoList01",
            "type": [
                "01"
            ],
            "typeStr": "type01",
            "id": "66ce1086d562476a8331a6065ed5bb50"
        },
        {
            "businessId": "8d4c1e7ab5184705a056389a755c4bce",
            "name": "slaveVoList02",
            "type": [
                "01"
            ],
            "typeStr": "type01",
            "id": "6a98ff39a92c4b6a93a3cb93614e5810"
        }
    ]
}
```

**Comment by philwebb** [comment]
@FQXCS Could we please have the sample as a complete project that we can download and run. We'd also prefer if Lombok wasn't involved.

**Comment by FQXCS** [comment]
This is my improvised project, and it can go wrong again.
[springboot3.zip](https://github.com/user-attachments/files/16940091/springboot3.zip)

**Comment by bclozel** [comment]
I had a look to your sample and there are several issues.

First, your custom configuration class extends `WebMvcConfigurer`, which completely disables Spring Boot's web auto-configuration. You should remove the `extend WebMvcConfigurer` part to get a better experience.

Second, I believe the JSON input you have provided is invalid as the "type" attribute is given as an array, whereas the Java objects expect a single `String`. Removing your custom deserializer yields `Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)]`.

Once I have removed your custom deserializer and fixed the request JSON document, I can log the payload received in the controller:

```
c.e.s.test.controller.TestController     : MasterVo{id='8d4c1e7ab5184705a056389a755c4bce', masterName='test', slaveVoList=[SlaveVo{id='66ce1086d562476a8331a6065ed5bb50', name='slaveVoList01', type='01', typeStr='type01'}, SlaveVo{id='6a98ff39a92c4b6a93a3cb93614e5810', name='slaveVoList02', type='01', typeStr='type01'}]}
```

I believe the problem comes from your custom Jackson deserializer; please ask this question on StackOverflow.

**Comment by FQXCS** [comment]
Thank you for your answer. I find that the type of "type" is wrong, but I debug that JacksonXssClean returns null value. 
Because there's a try catch, even if the "type" parsing fails, the value is returned as null and the correct value is assigned (MasterVo.slavevList[n].type = null), rather than "MasterVo.slavevList[0].id" incorrectly assigned to "MasterVo.id".
