### ISSUE TITLE
Upgrade to Elasticsearch Client 8.15.1

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-boot#42204]
https://mvnrepository.com/artifact/org.elasticsearch.client/elasticsearch-rest-client/8.15.1

**Comment by wilkinsona** [comment]
Thanks, but as described in the template that you were shown when raising this, we don't need issues for basic dependency upgrades:

> You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release. BUT pull requests for upgrades that are more involved than just a version property change are still most welcome.
