### ISSUE TITLE
Configure executions for Failsafe plugin

### ISSUE THREAD

**Issue by hban** [spring-projects/spring-boot#4223]
Spring Boot Starter Parent already configures executions for some Maven plugins. I'd be nice if it would do the same for the Failsafe - bind its integration-test and verify goals so users don't have to repeat that configuration.

**Comment by snicoll** [comment]
Maybe we could add the start/stop goal of the maven plugin as well, see https://github.com/spring-projects/spring-boot/issues/4922#issuecomment-173791087
