### ISSUE TITLE
Embedded Artemis isn't autoconfigured

### ISSUE THREAD

**Issue by hban** [spring-projects/spring-boot#4226]
It looks like `ArtemisEmbeddedServerConfiguration`, which is supposed to configure embedded Artemis, isn't actually imported anywhere.

**Comment by snicoll** [comment]
That class is imported by `ArtemisAutoConfigurationWithoutXA` and we have tests that cover several variants of that use case.

**Comment by snicoll** [comment]
And that class is in a test. Oops, I spoke too soon it seems.

**Comment by wilkinsona** [comment]
There PR adds to missing import. We could really do with a test too.

**Comment by snicoll** [comment]
definitely. And check that HornetQ hasn't the same weakness (test coverage I mean).
