### ISSUE TITLE
 Name for argument of type [java.lang.Integer] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.

### ISSUE THREAD

**Issue by lichengliang1** [spring-projects/spring-boot#42274]
my pom config 

```xml
  <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <parameters>true</parameters>
                </configuration>
   </plugin>
```

How to solve this problem

**Comment by lichengliang1** [comment]
There is no issue with using spring-boot-dependencies version 3.3.2

**Comment by lichengliang1** [comment]
There is no issue with using spring-boot-dependencies version 3.3.2

**Comment by philwebb** [comment]
It's impossible to say from the limited information provided. Perhaps you have a misconfiguration in your IDE and the `.class` files are being generated from there.

If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by seevae** [comment]
后来解决了吗，我在使用jdk17，springboot3.4.4版本也遇到了同样的问题

**Comment by bclozel** [comment]
@seevae the problem is in your build file or in your IDE configuration. Spring Boot adds this compilation flag by default.
