### ISSUE TITLE
Consider switching addResources to false as we have devtools now

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4227]
See [this thread](http://stackoverflow.com/questions/33197230/resources-in-a-spring-boot-application-are-missing-from-jar-file-when-using-spri/33197556#33197556)

I always thought that setting this to `true` by default was weird (especially the thing that deletes duplicates from `target/classes`!)

Could we please reconsider and set it to `false` by default in 1.3?

**Comment by joshiste** [comment]
+1

**Comment by philwebb** [comment]
Fine by me but we should do this for RC1. @wilkinsona @dsyer want to vote?

**Comment by wilkinsona** [comment]
+1

**Comment by dsyer** [comment]
What are the ramifications? I vote a big -1 if it means you *have* to use devtools in order to get devtime reloading of static resources (there are too many potential issues with devtools for me to feel comfortable asserting that it will always work).

**Comment by snicoll** [comment]
I guess a big -1 deserves the full version then.

I think that `addResources` is fundamentally flawed. Removing resources from `target/classes` is simply wrong IMO. There is an interesting side effect if you execute the `package` phase together with the `spring-boot:run` goal (i.e. some resources have disappeared from your jar). 

I also think we need to reconsider given the fact that we have devtools now. My plan is to deprecate the property and remove it in 1.4 (or 2.0) and document the replacement (that is Devtools). There is a few edge cases indeed but you can run Devtools with `spring.devtools.remote.restart.enabled=false` and you'll still get the same friendly experience plus LiveReload. The only downside is that you have to "save"/"make" to actually copy the updated resources where the process is looking for them.

A few additional remarks:

* We have now _two_ ways of doing similar things. I don't think we should do that as it may confuse users as why they should choose one over the other. And we want them to use Devtools, don't we?
* This `addResources` feature "forces" user to run their Spring Boot app via the build plugin which is something (IMO) we don't want them to do. We want them to run their app right from the IDE and benefit from all the nice features you can get from running a simple main. 

We can maybe meet half-way and not deprecate the property (but still disabling in 1.3) which leaves thing pretty much where we stands. And maybe defer the deprecation/removal when the edge cases in devtools have been fixed.

Regardless, let's not enable something that removes resources from the target directory behind everybody's back. Please :)

**Comment by snicoll** [comment]
Dave mentioned that there are still a few edge cases to fix with devtools so we can't reasonably deprecate this feature. I agree so I just changed the default value for now. We can reconsider later.

**Comment by bosyak** [comment]
Hi.
I understand I did it completely wrong but to make FastRestart (restartedMain) &  LiveReload working I run my app with those parameters: 
-Drun.addResources=true -javaagent:/home/j2/springloaded-1.2.4.RELEASE.jar -noverify
Springloaded able restartedMain working and addResource make LiveReload working without forcing me to rebuild project.

I read documentation carefully but did not understand which is the right way.
I'm using Spring boot 1.3.0.RC1

Please point me, if I miss something in documentation.

**Comment by snicoll** [comment]
@bosyak that issue is closed and [as described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

This issue has nothing to do with either devtools or Spring Loaded.
