### ISSUE TITLE
Not defaulting to UTF-8 encoding in request

### ISSUE THREAD

**Issue by andidev** [spring-projects/spring-boot#4228]
After upgrading to Spring Boot 1.3.0.M5 from 1.2.6.RELEASE I have problems with logging in with usernames containing non ASCII characters. It seems that the encoding in the request parameters is ISO-8859-1 instead of UTF-8 and therefore the user is not found.

The login is trying to `POST` with
```
'Content-Type': 'application/x-www-form-urlencoded'
```
Here is a [sample JHipster application](https://github.com/andidev/jh/tree/spring-boot-utf8-bug) showing this problem. You can start it with `mvn spring-boot:run` and try to login with username `abcåäö` and password `user`.

The issue can be solved with adding the encoding into the content type by setting it to
```
'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
```
in [src/main/webapp/scripts/components/auth/provider/auth.session.service.js](https://github.com/andidev/jh/blob/spring-boot-utf8-bug/src/main/webapp/scripts/components/auth/provider/auth.session.service.js#L12)

**Here is a screenshot of the request from the browser console**
![screen shot 2015-10-18 at 14 24 21](https://cloud.githubusercontent.com/assets/571389/10564072/9dd61d62-75a5-11e5-889e-cd5e28702f3f.png)

**and here is the request created by the server**
![screen shot 2015-10-18 at 14 28 22](https://cloud.githubusercontent.com/assets/571389/10564073/a2910dda-75a5-11e5-9665-581f30762072.png)

**as you can see the ecoding is not UTF-8 but the queryStringEncoding is UTF-8**

**Comment by wilkinsona** [comment]
Duplicates #3912
