### ISSUE TITLE
Provide a default REST controller interface

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#4229]
It is a common need to create a Spring MVC controller that performs REST/CRUD operations + other additional custom operations. Spring Data REST allows to expose automatically repositories as REST endpoints, but this is not flexible enough for a wide range of use cases.

Spring Boot could provide a default REST/CRUD controllers interface, and maybe a Spring Data repository based implementation, in order to provide more (optional) guidance for web application developers.

As a starting point, you can have a look to the [RestController](https://github.com/resthub/resthub-spring-stack/blob/master/resthub-web/resthub-web-server/src/main/java/org/resthub/web/controller/RestController.java) interface and [RepositoryBasedRestController](https://github.com/resthub/resthub-spring-stack/blob/master/resthub-web/resthub-web-server/src/main/java/org/resthub/web/controller/RepositoryBasedRestController.java) default implementation.

**Comment by alexpanov** [comment]
@philwebb @sdeleuze Should it maybe go to the Spring Web project?

**Comment by bclozel** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
