### ISSUE TITLE
launch.script restart function does not follow Linux Standard Base Core Specification

### ISSUE THREAD

**Issue by ksokol** [spring-projects/spring-boot#4231]
According to the [specification](http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html) restart function shall 
> stop and restart the service if the service is already running, otherwise start the service.

Right now restart aborts if service is not already running.

Actually, commit 9dec0971d62483422f2bdcb970bf68a0a49213fd should be reverted.

**Comment by wilkinsona** [comment]
Some of the exit codes are also out of line with the spec. I'll fix those too.
