### ISSUE TITLE
Add configuration support for LazyConnectionDataSourceProxy in application.yaml

### ISSUE THREAD

**Issue by jayleeinflab** [spring-projects/spring-boot#42318]
Currently, to use LazyConnectionDataSourceProxy in Spring Boot, developers have to manually wrap the DataSource in code. (At least for me.) While there was a similar suggestion in the past ([Issue #15480](https://github.com/spring-projects/spring-boot/issues/15480)), it appears that this feature has not yet been implemented.

I would like to propose adding support for configuring LazyConnectionDataSourceProxy directly through application.yaml.

By enabling this setting, the DataSource could be automatically wrapped with LazyConnectionDataSourceProxy, offering greater convenience to developers.

If the Spring team is open to it, I would like to work on implementing this feature myself. :)

**Comment by philwebb** [comment]
Duplicates #42319
