### ISSUE TITLE
Add configuration support for LazyConnectionDataSourceProxy in application.yaml

### ISSUE THREAD

**Issue by erie0210** [spring-projects/spring-boot#42319]
Currently, to use LazyConnectionDataSourceProxy in Spring Boot, developers have to manually wrap the DataSource in code. While there was a similar suggestion in the past (https://github.com/spring-projects/spring-boot/issues/15480), it appears that this feature has not yet been implemented.

I would like to propose adding support for configuring LazyConnectionDataSourceProxy directly through application.yaml.

By enabling this setting, the DataSource could be automatically wrapped with LazyConnectionDataSourceProxy, offering greater convenience to developers.

If the Spring team is open to it, I would like to work on implementing this feature myself. :)

**Comment by wilkinsona** [comment]
Duplicates #15480.

**Comment by erie0210** [comment]
Okay. Thanks for letting me know the rules. Should it be better to leave comments on the #15489 instead? @wilkinsona
