### ISSUE TITLE
Allow non sudoer user to start spring-boot service by default

### ISSUE THREAD

**Issue by nodje** [spring-projects/spring-boot#4232]
It'd be nice to be able to start spring-boot as a Unix service ```/etc/init.d/myapp start``` without using sudo.

Because of the usage by default of folders ```/var/log``` and ```/var/run``` it's not possible, by default.

If launch.script creates a folder inside ```/var/log``` and ```/var/run``` and makes the non sudo user the owner of these, it should be possible to start the service as non privileged user.

**Comment by wilkinsona** [comment]
I don't think I understand what you're proposing. The default permissions for `var/log` prevent a normal user from creating a directory there so using a sub-directory by default won't help as you'd still need to use sudo to allow the script to create those directories. Note that the script already creates any directories and changes ownership of files to allow the application to run as the user that owns the application jar file. What have I missed?

**Comment by nodje** [comment]
Never mind, you haven't missed anything, I got confused.

In effect you just have to start the service once as root then it can run under the user that owns the app.
