### ISSUE TITLE
Change import order

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4234]
This seems like a more sensible order that would also work better with IJ.

![pasted image at 2015_10_19 06_33 pm](https://cloud.githubusercontent.com/assets/519772/10584317/67080fa6-7646-11e5-9a5d-26c553d79cb1.png)

**Comment by snicoll** [comment]
For the record you didn't do that. It's currently configured to have a blank line between `java` and `javax`. I don't actually care much if it stays that way but I thought you should know.

**Comment by philwebb** [comment]
Eclipse doesn't offer fine grained support for that unfortunately.
