### ISSUE TITLE
Consider removing in-memory database configuration from slice tests

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#42360]
To begin with, I'm aware of recent improvements made by https://github.com/spring-projects/spring-boot/issues/35253.

However, I'd still ask to consider removing in-memory database configuration from slice tests where it's used (`@JdbcTest`, `@DataJpaTest`, `@DataJdbcTest`) for the following reasons:

- integration testing data access layer against an in-memory isn't really a best practice (and Spring Boot should guide developers towards _best practices_)
- most major RDBMSs are available in containerized form (and Testcontainers is a obviously well established solution that helps there)
- the aforementioned https://github.com/spring-projects/spring-boot/issues/35253 IMO actually makes it easier to change the default as it should lower the impact
- changing the default will align all relational database slices in this regard (`@JooqTest` doesn't configure an in-memory database)

In practice, I haven't worked on a project where data access layer was primarily tested using an in-memory database probably since ~2016 so that's a lot of occurrences of `@AutoConfigureTestDatabase(replace=NONE)`.

**Comment by quaff** [comment]
I don't think so, at least `@DataJpaTest` should keep it, since most test cases are testing logic of persistence not sql, using which database is not important.
Testcontainers is great but it requires docker, unit tests shouldn't rely on external services, people should create dedicate integration test suite to use it.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but  I don't think we can do this. In addition to @quaff's points above, we also know from experience that a significant portion of Spring Boot's user base cannot or does not use Docker for various reasons.

> `@JooqTest` doesn't configure an in-memory database

Thanks for spotting this. It's not moving things in the direction that you'd like, but I think we should correct this by adding `@AutoConfigureTestDatabase` to `@JooqTest`. I've opened https://github.com/spring-projects/spring-boot/issues/42371 to do that.

**Comment by vpavic** [comment]
In practice, I don't remember seeing a real world project that didn't use at least some custom SQL (or JPQL) statements. Using JPA/Hibernate also doesn't mean developers shouldn't leverage native (often vendor specific) capabilities of their RDMBS - quite a few Hibernate experts are actually trying to raise awareness of that. Finally, testing against an in-memory database makes it easier to hide issues caused by change of behavior when upgrading to a new Hibernate release.

> we also know from experience that a significant portion of Spring Boot's user base cannot or does not use Docker for various reasons.

That's fine, but shouldn't be a reason for Spring Boot to have something that's clearly not a best practice as a default. Also with the change they'd still be just an annotation away from opting in to auto-configured in-memory database. That's also more explicit and less magic, which is good thing from my point of view.

Like I said, I've seen really a lot of `@AutoConfigureTestDatabase(replace=NONE)` over the years that leads me to believe a better default is to have developers opt in and be specific regarding something like this, rather than having to constantly opt out.

I must say, when it comes to data access support, Spring Boot has some quite frustrating defaults (see OSIV/OEMIV).

**Comment by wilkinsona** [comment]
I'm not sure we have sufficient evidence to state, categorically as you have done above, that what Boot is doing here is "clearly not a best practice as a default". Reducing things to being a best practice or not being a best practice often strips away a lot of context from different people's situations and the different variables that have to be weighed up.

If you're in a position to use Docker (and with some of their recent changes that probably means being in a position to pay for it), using a containerized database for integration tests could be the best choice given the situation. If you're not in a position to use Docker, then obviously you can't do that. Given a choice between using an in-memory database pretending to be your actual database and requiring everyone on a team and CI workers to have the actual database set up and running, using an in-memory database could be the best choice given the situation.

With the changes in Boot 3.4, I think we're doing a pretty good job of catering for both of the situations described above. If you write an integration test using `@DataJpaTest` or the like and you've chosen to have an in-memory database on the classpath, we'll make use of it for the test. Equally, if you write such an integration test and you've chosen to use Testcontainers in your test, we'll now make use of it. 

> to have developers opt in and be specific regarding something like this

Boot doesn't add an in-memory database to the classpath by default. The user has to opt in to using an in-memory database for testing by adding one to the classpath.

> rather than having to constantly opt out.

Haven't we addressed this in Boot 3.4? If there are still cases where `@AutoConfigureTestDatabase(replace=NONE)` is needed, I would prefer that we see if we can address those rather than making things worse for those who have chosen to use an in-memory database.

**Comment by vpavic** [comment]
Sorry for the late follow-up here, but could you please give this another look and potentially consider it for 4.0?

I'll try to again concisely list the arguments to change the default, because judging by the last comment there seems to be at least some misunderstanding about the status quo. Consider this very simple example:

<details>
<summary>build.gradle.kts</summary>

```gradle
plugins {
    id("java")
    id("org.springframework.boot").version("3.5.6")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
    implementation("org.springframework.boot:spring-boot-starter-jdbc")

    runtimeOnly("org.postgresql:postgresql")
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            useJUnitJupiter()
            dependencies {
                implementation("org.springframework.boot:spring-boot-starter-test")
            }
        }
    }
}
```
</details>

<details>
<summary>SampleApplication.java</summary>

```java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

}
```
</details>

```java
package com.example;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.simple.JdbcClient;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest(properties = {
        "spring.datasource.url=jdbc:postgresql:test",
        "spring.datasource.username=username",
        "spring.datasource.password=password",
})
class SampleJdbcTests {

    @Autowired
    JdbcClient jdbcClient;

    @Test
    void sampleTest() {
        assertThat(this.jdbcClient.sql("select 1").query(int.class).single()).isOne();
    }

}
```

Attempting to run this test suite fails with the following output:

```
> Task :testClasses
12:14:16.650 [Test worker] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils -- Could not detect default configuration classes for test class [com.example.SampleJdbcTests]: SampleJdbcTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
12:14:16.715 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper -- Found @SpringBootConfiguration com.example.SampleApplication for test class com.example.SampleJdbcTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.6)

2025-10-20T12:14:16.938+02:00  INFO 2331487 --- [sample] [    Test worker] com.example.SampleJdbcTests              : Starting SampleJdbcTests using Java 17.0.16 with PID 2331487 (started by vpavic in /home/vpavic/dev/projects/vpavic/sample-spring-boot)
2025-10-20T12:14:16.939+02:00  INFO 2331487 --- [sample] [    Test worker] com.example.SampleJdbcTests              : No active profile set, falling back to 1 default profile: "default"
2025-10-20T12:14:17.096+02:00  INFO 2331487 --- [sample] [    Test worker] beddedDataSourceBeanFactoryPostProcessor : Replacing 'dataSource' DataSource bean with embedded version
2025-10-20T12:14:17.144+02:00  WARN 2331487 --- [sample] [    Test worker] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0: Error creating bean with name 'dataSource': Failed to replace DataSource with an embedded database for tests. If you want an embedded database please put a supported one on the classpath or tune the replace attribute of @AutoConfigureTestDatabase.
```

I've got JDBC driver on the classpath, I've provided all the necessary `spring.datasource.*` configuration properties, and most importantly I've made zero indication that I want to use an embedded database - yet this simple test fails, prompting the addition of `@AutoConfigureTestDatabase(replace = Replace.NONE)`.

Regardless of the data access technology used, here are some statement that I believe we should all agree are true:
- all modern RDBMSs provide native SQL dialects that go well beyond basic SQL
- to leverage advanced RDMBS capabilities (think PostgreSQL's support for JSON or full-text search) and/or ensure optimal data access, it's needed to use native SQL dialects
- in-memory databases can only offer emulation and are limited to basic SQL compatibility with target RDBMS

Specifically, in case of ORMs, non-trivial real-world application will still likely use native SQL so all the above applies there as well. Even [Hibernate itself](https://hibernate.org/orm/just-sql/) and [recognized Hibernate experts](https://vladmihalcea.com/the-jpa-entitymanager-createnativequery-is-a-magic-wand/) advocate tactical usage of native SQL.

With all of that I can't see a case where it's preferable to test using an in-memory database that emulates target database, vs testing against a real instance of target database. With Hibernate, even without custom SQL, testing against in-memory databases only opens up room for issues related to Hibernate dialect related changes to creep in.

If it's not possible to test against a real database or when that's preferred for some reason, I don't see a reason for Spring Boot to have such a strong opinion on several data-access related test slice annotations vs having to opt-in explicitly using `@AutoConfigureTestDatabase`. Effectively, this issue boils down to which of these is perceived as lesser evil:

```java
@JdbcTest // includes @AutoConfigureTestDatabase
@AutoConfigureTestDatabase(replace = Replace.NONE)
```

```java
@JdbcTest // doesn't include @AutoConfigureTestDatabase
@AutoConfigureTestDatabase
```

I'm obviously subjective here, but the latter option makes it very clear how the test suite is set up and doesn't force anyone to deal with things they didn't want to in the first place.

> If you're in a position to use Docker...

Docker engine (community edition) is Apache 2.0 licensed and is therefore free for anyone to use, and is available on most modern CI environments. For those using OSs that require use of Docker Desktop, I believe there are free alternatives, and at the very least you could run test that require containers only on CI. I don't believe Docker/containers availability should be an argument for this discussion in 2025.

> With the changes in Boot 3.4...

I assume you're referring to [_@AutoConfigureTestDatabase with Containers_](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#autoconfiguretestdatabase-with-containers) but if I understand correctly this won't help with databases installed locally (on developer machine or CI) or Docker Compose setup managed externally (for example, using build plugins).

**Comment by wilkinsona** [comment]
Unfortunately, it's very late in the 4.0 development cycle (RC1 is on Thursday) so it's unlikely that we'll have time to make a change here. A couple of things in response to the above as I think this is still a useful discussion, even if it won't conclude in time to make changes in 4.0.

I don't think the simple sample is really representative as you're not showing how the Postgres instance used by the test is provisioned. I'd guess it's running locally as a (hidden) requirement of the test. That isn't something that we'd recommend and we encourage the use of Docker or an in-memory database instead to make it easier to run the tests. With either of those approaches, this should just work without need for further configuration.

> Docker engine (community edition) is Apache 2.0 licensed and is therefore free for anyone to use, and is available on most modern CI environments. For those using OSs that require use of Docker Desktop, I believe there are free alternatives, and at the very least you could run test that require containers only on CI. I don't believe Docker/containers availability should be an argument for this discussion in 2025.

Unfortunately, we have customers whose developers are not allowed to use Docker. I'm not privy to the exact reasons but that's their reality. I also don't think we should promote CI-only tests as a good approach as it encourages pushing changes that may break the build for others.

**Comment by wilkinsona** [comment]
We discussed this today and the team's opinion is that we're still striking the right balance so we're not going to make a change here.

**Comment by vpavic** [comment]
> I don't think the simple sample is really representative as you're not showing how the Postgres instance used by the test is provisioned. I'd guess it's running locally as a (hidden) requirement of the test. That isn't something that we'd recommend and we encourage the use of Docker or an in-memory database instead to make it easier to run the tests. With either of those approaches, this should just work without need for further configuration.

The sample not showing that detail is deliberate. There are many ways to set up environments for running integration tests, and application framework shouldn't provide too strong opinions because it's simply not in a position to do so. Such concerns often depend on broader project setup and organizational preferences, and there are several equally valid options. Many CIs offer very easy ways to use services as PostgreSQL, for example [see relevant GitHub Actions documentation](https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers).

The approach I'm using in most projects these days is to set up integration test environments using Docker Compose, and have build (using [this plugin](https://github.com/avast/gradle-docker-compose-plugin)) manage its lifecycle. Project build is IMO in better position to manage Docker Compose lifecycle and all of its usages - so not only running application locally and integration testing, but also things that are external to the application and cannot be handled using application framework's Docker Compose support (such as code generation that depends on something that runs in a container, or E2E tests).

> Unfortunately, we have customers whose developers are not allowed to use Docker. I'm not privy to the exact reasons but that's their reality. I also don't think we should promote CI-only tests as a good approach as it encourages pushing changes that may break the build for others.

I can understand that, but such customers are certainly not majority. Note that I'm not asking for Spring Boot to promote any specific way of integration testing, I'm just asking not to promote in-memory testing as the default solution and to make things easier for other (better) ways.

**Comment by wilkinsona** [comment]
>  I'm just asking not to promote in-memory testing as the default solution

I don't think we're doing that.

We're promoting a solution where the database is "provisioned" as part of running the tests. That can either be through an in-memory database or through Docker with Testcontainers (or Docker Compose if you allow Boot to manage the Docker Compose lifecycle).

I think where we see things differently is on the benefits of a project being self-contained and settings things up for itself vs moving that somewhere external that may require additional setup but perhaps offer more power. Which is better is subjective and we continue to prefer ours with the alternative only being a single annotation away.

**Comment by vpavic** [comment]
> We're promoting a solution where the database is "provisioned" as part of running the tests. That can either be through an in-memory database or through Docker with Testcontainers (or Docker Compose if you allow Boot to manage the Docker Compose lifecycle).

That way, you're only creating an even stronger opinion about the setup of integration tests and forcing us (developers) to more lock-in.

In a non-trivial real-world application, there will be hundreds or even thousands of integration tests relying on something that runs in containers. If I let Spring Boot's Docker Compose manage that, I will:

- need to add another Spring Boot module (`spring-boot-docker-compose`) that I otherwise don't need
- need to provide some explicit configuration (`spring.docker.compose.skip.in-tests=false`) to make it work for tests
- likely need to add something to my Docker Compose definition (that I otherwise wouldn't need) to make Spring Boot's Docker Compose support happy
- likely need to implement some support myself for services in my Docker Compose definition that Spring Boot doesn't support out of the box

When I do all that, my build will be much slower to execute because Spring Boot's Docker Compose will spin up and down containers several times when running integration tests. And I'll still need to use some other solution for use cases that depend on Docker Compose but are external to application framework.

In contrast to that, if it's the build plugin managing Docker Compose lifecycle, it requires only a small amount of build configuration and will spin containers only once for all the integration tests thus reducing build time significantly and the same Docker Compose facilities will be used for all the project's needs, which reduces the overall project complexity. Coincidentally, some of these benefits are possible if using something like CI provided database.

Don't get me wrong, I think it's a good thing that Spring Boot added support for Docker Compose, but it's not the solution for every project and every use case. I'm not working on some super complex or exotic projects, yet I've never used a Spring Boot database slice test without also needing to use `@AutoConfigureTestDatabase(replace = Replace.NONE)` - what I'm only really looking for is to build reliable software that's well tested and optimizing builds in order to increase developer productivity and reduce CI costs. From that standpoint, I'm extremely disappointed with this default as I need to opt out of it on each and every project.

**Comment by aahlenst** [comment]
I was never fond of `@AutoConfigureTestDatabase`. Until it was made aware of TestContainers, I always had to opt out with `@AutoConfigureTestDatabase(replace = Replace.NONE)`. To me, it's not about having to add yet another annotation, but about having to figure out what's going on and making sure some test isn't accidentally using the auto configured in-memory database which rarely does what I need. It also feels weird that a test slice, which is supposed to remove functionality, adds some. I'm a person that prefers opt in because it's explicit and less magic. Therefore I sympathize with the request. However, I'm sceptical whether it's worth the upgrade pain. 

If any change is made at all, I'm wondering whether replacing `@AutoConfigureTestDatabase` with a set of annotations like `@AutoConfigureInMemoryDatabase`, `@AutoConfigureTestContainers`, `@AutoConfigureServiceConnection` and getting rid of the `Replace` enum (that is not so easy to understand) might be a good idea. At least it would be opt-in, very explicit, and open the door for adding functionality that might not fit `@AutoConfigureTestDatabase`.
