### ISSUE TITLE
Spring AOP breaks whitelabel mvc binding 

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#4236]
Setup - latest 1.3 snapshot, with actuator and web starters.

Adding a AOP expression causes the mvc bindings for `/error` to not get mapped. eg. if you uncomment  the `@Aspect`, you will see the correct mapping registration in logs:

```
    2015-10-19 12:44:38.619  INFO 10472 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
    2015-10-19 12:44:38.619  INFO 10472 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
```

Code snippet - try with and without @aspect commented.

```java
    @SpringBootApplication
    public class Z4Application {

    public static void main(String[] args) {
        SpringApplication.run(Z4Application.class, args);
    }
    
	@Configuration
	// @Aspect
	public static class Default_Collection {
		
		@Pointcut("within(@org.springframework.stereotype.Controller *)")
		private void mvcPC() {
		};

		@Around("mvcPC()")
		public Object mvcAdvice(ProceedingJoinPoint pjp)
				throws Throwable {

			System.out.println( "got here" );

			return "Breaks Err";
		}
	}
	
```

**Comment by philwebb** [comment]
I'm no AspectJ expert but isn't your `@Aspect` saying replace all methods within `@Controller` annotated classes and make them return `"Breaks Err"`? Can you provide a complete [sample app](https://github.com/spring-projects/spring-boot-issues) that shows what you're trying to achieve?

Also, is this something that you found when upgrading an existing Spring Boot 1.2 application (i.e. is it a regression)?

**Comment by peterdnight** [comment]
This is not a 1.2.x example, but rather straight from: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html . The purpose of @Aspect is start a timer, invoke the controller, then print the timing.

Code below is a fully working example; except that the @Aspect is causing the boot registration of the whitelabel error to fail. 

Output:
```
StopWatch 'Z2Application$Default_Collection$$EnhancerBySpringCGLIB$$5420eecc': running time (millis) = 110
-----------------------------------------
ms     %     Task name
-----------------------------------------
00110  100%  testController

StopWatch 'Z2Application$Default_Collection$$EnhancerBySpringCGLIB$$5420eecc': running time (millis) = 23
-----------------------------------------
ms     %     Task name
-----------------------------------------
00023  100%  testController

StopWatch 'Z2Application$Default_Collection$$EnhancerBySpringCGLIB$$5420eecc': running time (millis) = 19
-----------------------------------------
ms     %     Task name
-----------------------------------------
00019  100%  testController
```

Working code:

```java
 package com.example;

import java.io.PrintWriter;
import java.io.Writer;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Controller;
import org.springframework.util.StopWatch;
import org.springframework.web.bind.annotation.RequestMapping;

@SpringBootApplication
public class Z2Application {

    public static void main(String[] args) {
        SpringApplication.run(Z2Application.class, args);
    }
    
    
    @Controller
	public static class SimpleMvc {
    	@RequestMapping("/testController")
    	public void testController(PrintWriter w) throws Exception {
    		
    		Thread.sleep( (new Random()).nextInt( 100 ) );
    		w.println( "Hello from " + InetAddress.getLocalHost().getHostName() + " at "
    				+ LocalDateTime.now().format( DateTimeFormatter.ofPattern( "HH:mm:ss,   MMMM d  uuuu " ) ));
    		
    		return;
    	}
    }
    
    // http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html
	@Configuration
	@Aspect
	public static class Default_Collection {
		
		@Pointcut("within(@org.springframework.stereotype.Controller *)")
		private void mvcPC() {
		};
		
//		@Pointcut("within(@org.springframework.web.bind.annotation.RestController *)")
//		private void restPC() {
//		};

		// http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html
		@Around("mvcPC()")
		public Object mvcAdvice(ProceedingJoinPoint pjp)
				throws Throwable {

			 StopWatch sw = new StopWatch(getClass().getSimpleName());
		        try {
		            sw.start(pjp.getSignature().getName());
		            return pjp.proceed();
		        } finally {
		            sw.stop();
		            System.out.println(sw.prettyPrint());
		        }
		}
	}
}
```

**Comment by philwebb** [comment]
Interesting, thanks for the sample code that helps a lot.

The root cause of this is that AspectJ is trying to create a JDK Proxy for `BasicErrorController` which in turn causes `AbstractHandlerMethodMapping.initHandlerMethods` to ultimately call `RequestMappingHandlerMapping` with a type of `Proxy`. This means that the `AnnotationUtils.findAnnotation` fails.

The easiest fix is to add `spring.aop.proxy-target-class=true` to your properties file.

**Comment by philwebb** [comment]
@dsyer @snicoll @wilkinsona I wonder if we shouldn't switch the default in 1.3 to `proxy-target-class=true`? It would seem like a more sensible default to me.

**Comment by wilkinsona** [comment]
I'm not sure about changing the default. This problem aside, I think we're less likely to confuse people if we use the same default as Spring Framework. Why is `BasicErrorController` any different to `SimpleMvc` controller in the example?

**Comment by snicoll** [comment]
I know you didn't ask me but I wouldn't change the default either. Switching everything to cglib proxy should be opt-in IMO.

**Comment by dsyer** [comment]
Agree. It's the pointcut that's the problem, not the default. If it came from an example in our own documentation we should check the source and make sure there is a warning there that it usually won't work unless you use cglib. I guess the only other thing we could do is try and change the error message (difficult).

**Comment by peterdnight** [comment]
Thanks for the configuration tip. From the client programmer perspective - while I appreciate the ease in which this can be corrected - this was a particularly painful experience to detect in the first place. Arguably - adding a very good looking piece of code that results in a hidden break in Boot is less then optimal. 

Hidden - in the sense that - unless you are looking that the logs with info mode enabled for spring (we never run this way) - and you know to look for the mapping, there is nothing to indicate a failure. ultimately I have some test controllers that throw exceptions that did not show the whitelabel page; and then I had a large number of steps to isolate to a particulare code base.

To boots credit: we have replaced @SpringBootApplication with our own annotation (@EnterpriseBoot) . I assume i can set the default for AOP in there, so that all the projects will include?  eg. can I programatically set spring.aop.proxy-target-class=true , but still allow client project developers to override in their own respective application.ymls?

**Comment by philwebb** [comment]
Spring AOP is trying to be clever about how it applies the advice. When applied to your own controller it sees that it doesn't implement any interfaces so it uses cglib. When applied to the `BasicErrorController` it sees that there is a single interface that it implements so assumes that a JDK proxy will be fine.

I've fixed this now by adding a post processor to automatically set the `PRESERVE_TARGET_CLASS_ATTRIBUTE` attribute on `ErrorController` bean definitions. This ensure that they always get created using cglib.
