### ISSUE TITLE
Support for properties and/or YAML and/or JSON embedded in environment variables

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4239]
Marius and I tried out quite a few options for this and our favourite is this:

```
SPRING_ENVIRONMENT_JSON='{"spring.cloud.stream.bindings": {"inputs": { "contentType":"application/json", "destination":"foo" }}}'
```

or

```
SPRING_ENVIRONMENT_PROPERTIES='spring.cloud.stream.bindings.inputs.contentType=application/json,spring.cloud.stream.bindings.inputs.destination=foo'
```

These would be unpacked into name-value pairs and added to the `Environment` with precedence before or after environment variables.

**Comment by philwebb** [comment]
What's driving the need for this? Something specific to Spring Cloud?

**Comment by dsyer** [comment]
It cropped up with Spring Cloud Stream because there are a lot of variables that you might want to override on the command line of a running module. I think it's pretty generic though - environment variables are a reliable source of properties in all platforms and operating systems, but there are restrictions (as we know and already recognize) on their names. The restrictions mean, specifically, that you can't tell if an underscore is meant to be replaced by a period or a camel-case boundary when binding to `@ConfigurationProperties`. It's especially acute when the target property is actually something like a `Map<String,String>` where the periods want to end up in the keys.

**Comment by snicoll** [comment]
> It's especially acute when the target property is actually something like a Map<String,String> where the periods want to end up in the keys.

In theory you should be able to use the bracket notation for that (`my.map[my.key]=value`).

**Comment by dsyer** [comment]
That doesn't help if you only have environment variables to play with does it? We need a way to get the periods on the right hand side of the assignment.

**Comment by dsyer** [comment]
We decided to go with JSON only, and only in an env var called `SPRING_APPLICATION_JSON`.

**Comment by philwebb** [comment]
Reopening for docs update. We should also add a line to the release notes.

**Comment by philwebb** [comment]
Ignore the. Docs added in 1f675c026f08e634e7e821a38d2b7aaf90e9fff4
