### ISSUE TITLE
Upgrade to Maven Javadoc Plugin 3.10.1

### ISSUE THREAD

**Issue by ZIRAKrezovic** [spring-projects/spring-boot#42401]
See discussion at https://issues.apache.org/jira/browse/MJAVADOC-812

Spring Boot Parent has updated maven-javadoc-plugin as part of spring-boot 3.4.0-M3 (#42233)

**Comment by wilkinsona** [comment]
Thanks for bringing this to our attention. I've started watching MJAVADOC-812 and hopefully it will be fixed before our next 3.4 release which is RC1 on 24 October. We can keep this open to remind us to do something (either upgrade or rollback).

**Comment by snicoll** [comment]
The PMC vote for `3.10.1` just passed so we'll be able to upgrade.
