### ISSUE TITLE
Add property support for configureContentNegotiation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4240]
See suggestion in https://github.com/spring-projects/spring-boot/issues/4220#issuecomment-149273415

**Comment by philwebb** [comment]
@wilkinsona @rstoyanchev I've got some code sketched out [here](https://github.com/philwebb/spring-boot/tree/gh-4240) but I'm having second thoughts about adding it. Do you think it makes sense to offer this as a property? After all, it's not too onerous to add your own `WebMvcConfigurerAdapter` and perhaps we're best to not go too far down the "code by properties" route?

**Comment by wilkinsona** [comment]
It's coding by properties, IMO, and I agree that's a route we don't want to go down

**Comment by snicoll** [comment]
+1 - `Map<String,String>` is a smell IMO.

**Comment by rstoyanchev** [comment]
Indeed it's already straight forward to configure.
