### ISSUE TITLE
Spring Boot 3.2.7 -> Spring Boot 3.3.3 upgrade has not impacted startup time much 

### ISSUE THREAD

**Issue by atulgupta7** [spring-projects/spring-boot#42408]

**Comment by atulgupta7** [comment]
@bclozel 
**CDS Support for improved startup times and reduced memory consumption** - I am talking about this

**Comment by bclozel** [comment]
I assumed this was opened in error since you provided zero information, description, figures, sample application.
Have you tried CDS support? Can you describe how you are building the class archive and running the application? Maybe you can share a minimal sample application?
