### ISSUE TITLE
methodSignature.getParameterNames() is null in Spring Boot 3.2 when Running Junit Tests together but tests pass individually

### ISSUE THREAD

**Issue by mohamed928** [spring-projects/spring-boot#42439]
Hello Community,

Please I'm facing an issue when running JUnit test after migrating to spring boot 3.2. When Running Tests together they fail but pass individually. methodSignature.getParameterNames() is null

![image](https://github.com/user-attachments/assets/7825ca40-473c-412f-b71b-b3c2b34b3128)

![image](https://github.com/user-attachments/assets/a1825d7b-01e9-4635-97ca-dd31dbabd156)

I have tried this solution but not its working for me: https://github.com/spring-projects/spring-boot/issues/38721
Any help would be greatly appreciated. Thanks!

**Comment by philwebb** [comment]
Please ask questions on stackoverflow.com. I think this one duplicates #38721.
