### ISSUE TITLE
Backport Gradle 8 Upgrade to all 3.x branches

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42433]
In order to help with #42333 we should align on a single Gradle version

**Comment by philwebb** [comment]
Mostly a cherry-pick of d756bf4e86a8e79dea5d89876a375f649796a475

**Comment by wilkinsona** [comment]
We should back port https://github.com/spring-projects/spring-boot/commit/162c929a80605f6f1d776757527dbbb6db3fb944 as well otherwise we'll see some weird intermittent failures, IIRC.
