### ISSUE TITLE
LoggerContext.getConfigurationLock() causes NoSuchMethodError

### ISSUE THREAD

**Issue by BlueCaboose42** [spring-projects/spring-boot#42432]
Hello,

When trying to use the `getConfigurationLock()` method of LogbackConfigurator, the following error is thrown (spring boot version `3.3.0`):

`java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'java.lang.Object ch.qos.logback.classic.LoggerContext.getConfigurationLock()`

[An issue was raised](https://github.com/qos-ch/logback/issues/853) in `logback` that seems near identical to what we're experiencing. The issue was closed citing [this commit](https://github.com/spring-projects/spring-boot/commit/dd2ed5f12d23b15ff0055e366ab6da8e95218596) which seems to have been applied to version `3.3.3`. 

Can the same fix be applied to version `3.3.0`?

Current boot version `3.3.0`
Logback version `1.5.7`, previously `1.5.6` worked fine

**Comment by wilkinsona** [comment]
We can't apply a fix to `3.3.0` as it's been released and cannot be changed. You should either allow Spring Boot to control the version of Logback so that you're using a compatible version or upgrade to Spring Boot 3.3.3 or later.
