### ISSUE TITLE
The issue of springboot not being able to refresh configuration properly

### ISSUE THREAD

**Issue by sunl888** [spring-projects/spring-boot#42444]
**Describe the bug**
When I tried to get the app configuration in the bean, I found that it was not the latest value. Even if I updated it from nacos, I could only get the old value. At first, I suspected that @ RefreshScope was not effective, but after experimentation, I found out that it was not the case. This only happened when I used webService at the same time. Is there any difference between webService beans and regular beans? 

**Simplest demo**
[This is a testing project.](https://github.com/sunl888/nacos-sync)

**To Reproduce**
1. Start a temporary `Nacos server`
2. Create a yml configuration
3. Configure the `nacos server` address and other information for the `application.yml` file of the project
4. Start the project
5. Call `http://localhost:8088/config` Address
6. Observe the configuration information output by the console
7. Modify the configuration on Nacos and re execute steps 5 and 6
8. At this point, it will be found that the configuration that has not been updated has not been output

**Expected behavior**
In theory, the configuration obtained through the service interface after modifying the configuration on the Nacos server should be the latest.

**Screenshots**
0. Initial nacos configuration value
<img width="996" alt="截屏2024-09-24 23 23 29" src="https://github.com/user-attachments/assets/e8523c3a-461d-41c6-b3bd-a94c30c5d360">

1. this is the first time calling
<img width="1335" alt="截屏2024-09-24 23 17 39" src="https://github.com/user-attachments/assets/85954cab-1047-498d-8ec4-a65c9f4f8e4f">

2. modified nacos configuration values.
<img width="1071" alt="截屏2024-09-24 23 22 07" src="https://github.com/user-attachments/assets/0ab417ef-f6d8-4cb4-8363-fe50ca187b95">

3. this is the second call 
<img width="1373" alt="截屏2024-09-24 23 21 13" src="https://github.com/user-attachments/assets/e5260a0e-00fe-4135-9379-ac6e8c330107">

**Additional context** 
OS: MacOS
JDK: Java17
spring-cloud-starter-alibaba-nacos-config: 2023.0.1.2
cxf-spring-boot-starter-jaxws: 4.0.5
spring-boot-starter-web: 3.2.10

**Comment by bclozel** [comment]
Thanks for the report, but `@RefreshScope` is outside of Spring Boot's control as this feature is managed in Spring Cloud. Please report this problem on [the relevant issue tracker](https://github.com/spring-cloud/spring-cloud-commons/issues). Thanks!
