### ISSUE TITLE
Update-rc.d can not handle multiple jar symlinks in /etc/init.d/ (on Ubuntu 15.04)

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#4245]
Hi all,

Since switching to Ubuntu 15.04 (which now uses systemd by default) I'm having trouble running my spring-boot executable jars as services using init.d. My setup is fairly simple: I have multiple `1.3.0.M5` jars in `/opt` with matching `.conf` files. These jars are symlinked in `/etc/init.d/`. However, when I try to install the services using `sudo update-rc.d my-service defaults` I get the following error message:

> ```
~$ sudo update-rc.d uniprot defaults
insserv: script uniprot: service spring-boot-application already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
```

The `spring-boot-application` seems part of [launch.script](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L13).

(I'm still using `init.d` symlinks since these are services managed through puppet, so I'd like to be able to keep managing them through puppet, and notify them when applicable, which I wasn't able to do with systemd from puppet yet.)

What can be done to make my jars work with the `service` command in Ubuntu 15.04 again?

**Comment by timtebeek** [comment]
As a workaround, currently I have to provide my own bash script in `/etc/init.d/` so I can override the `Provides` value in the header:
```
#!/bin/bash

### BEGIN INIT INFO
# Provides: executable-jar-<%= @jarname %>
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Init script for <%= @jarname %>
### END INIT INFO

# Set the mode env var to signal to the jar that we're invoking as a service
export MODE="service"

# Pass the action to the jar
/opt/<%= @jarname %>.<%= @extension %> $@

# Exit with the return code of the jar to ensure failure/success is determined by the jar, not the sh script
exit $?
```
But obviously, I'd rather just use a symlink instead

**Comment by wilkinsona** [comment]
The underlying machinery supports property Mustache-style property substitution but the default script doesn't take advantage of it. I think it may well make sense to update the header:

```
### BEGIN INIT INFO
# Provides:          {{initInfoProvides:spring-boot-application}}
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: {{initInfoShortDescription:Spring Boot Application}}
# Description:       {{initInfoDescription:Spring Boot Application}}
# chkconfig:         2345 99 01
### END INIT INFO
```

You can then provide the configuration in your application's pom:

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<executable>true</executable>
		<embeddedLaunchScriptProperties>
			<initInfoProvides>your-custom-application</initInfoProvides>
			<initInfoShortDescription>Custom application</initInfoShortDescription>
			<initInfoDescription>Long description of custom application</initInfoDescription>
		</embeddedLaunchScriptProperties>
	</configuration>
</plugin>
```

We could also provide sensible defaults for each of those properties based on your project:

Property | Default
----------- | ----------
initInfoProvides | ${project.artifactId}
initInfoShortDescription | ${project.name}
initInfoDescription | ${project.description}

Note that you can do all of this today if you're happy to configure your build to use a custom launch script:

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<executable>true</executable>
		<embeddedLaunchScript>path/of/custom/launch.script</embeddedLaunchScript>
		<embeddedLaunchScriptProperties>
		    …
		</embeddedLaunchScriptProperties>
	</configuration>
</plugin>
```

**Comment by shakuzen** [comment]
@wilkinsona +1 for your proposed solution - especially the sensible defaults. This would eventually effect applications at my workplace, most likely. We don't have any multi-tenant servers with Spring Boot applications using init scripts right now, but we likely will in the near future (since Spring Boot 1.3 will be GA in the near future).

**Comment by timtebeek** [comment]
Yeah the proposed changes sound great! While it's good to know I can override `embeddedLaunchScript`, it's more work to apply this to multiple projects at the same time. The sensible defaults could really help out in this regard.
