### ISSUE TITLE
Use AbstractAotProcessor.AOT_PROCESSING constant instead of "spring.aot.processing"

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42461]
https://github.com/spring-projects/spring-framework/issues/33388 is now fixed so we can replace our current duplicate strings.

**Comment by ngocnhan-tran1996** [comment]
Can I work on this?

**Comment by wilkinsona** [comment]
Thanks for the offer, @ngocnhan-tran1996, but this can't be done until we've moved onto Spring Framework snapshots. It's probably also easier for someone on the team to take care of it as it's just a simple search and replace and the overhead of processing a PR for that is quite high.
