### ISSUE TITLE
spring-boot-starter-test:3.3.4  has a dependency on xmlunit-core version 2.9.1 that has a vulnerability issue

### ISSUE THREAD

**Issue by ziad-saade** [spring-projects/spring-boot#42479]
latest spring-boot-starter-test version is 3.3.4
![image](https://github.com/user-attachments/assets/2d5110b0-3138-423c-8526-c224348ca4f0)

Depend on xmlunit-core version 2.9.1 that has one vulnerability:
![image](https://github.com/user-attachments/assets/da4d4458-36e4-4d72-8aad-7962fa5f746f)

to resolve the issue upgrade xmlunit-core to 2.10.0.

**Comment by snicoll** [comment]
We've upgraded to `2.10.0` in 3.4, see https://github.com/spring-projects/spring-boot/issues/41429

We won't upgrade to a new feature release of XMLUnit in a maintenance release of Spring Boot, see https://github.com/spring-projects/spring-boot/issues/41029.

**Comment by ziad-saade** [comment]
thank you @snicoll for the clarification.
