### ISSUE TITLE
Backwards stack traces are really starting to get on my nerves

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4247]
It's nice in theory, but every other thing that renders stack traces puts them the other way up (e.g. JUnit tests, anything that uses `printStackTrace()`), so you often end up with an upside down one and a normal one side by side or one after the other. It's too confusing IMO to be the default.

**Comment by snicoll** [comment]
For the record, I am with Dave but I am not sure why. I think I am too used to look at the bottom.

I am actually surprised nobody complained so far.

**Comment by vpavic** [comment]
I've also been quite annoyed by this lately.

Most commonly I look at the logs using:
- IntelliJ Console with "Scroll to the end" option
- ```less``` with ```F``` command (Scroll forward)
- ```tail```

In all three cases I constantly find myself scrolling back trying to find relevant info about the error.

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-boot/issues/3399

I have no objections to changing the default.

**Comment by dsyer** [comment]
Somebody did complain to me in the office the other day actually. I forget who it was, but it got me thinking, and I agreed.

**Comment by shakuzen** [comment]
FWIW, I voted +1 on the original issue to put them backwards, but I must admit, as Dave mentions in the issue description, the benefit of them being backwards is voided by them often being accompanied by a regularly ordered stack trace. It is annoying, if not confusing. Backwards stack traces would be nice if they were all backwards, but this seems unfeasible.

**Comment by wilkinsona** [comment]
The root's still getting logged first
