### ISSUE TITLE
Allow structure logging JSON to be customized

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42486]
From https://x.com/jkuipers/status/1840849120874950716

![GYwChGvXgAA7T3a](https://github.com/user-attachments/assets/8ba14f0f-ba9e-479d-beb7-dbd6d4d70fe0)

**Comment by philwebb** [comment]
Several interesting ideas we could consider:

* Should you be able to rename Logstash field names? I assumed they were standard, but it seems the Logstash appender allows renames.
* Should we offer a quick way to include additional fields with static values? Service name is interesting because we do have a way to set that with ECS.
* Should we offer a general MDC filtering mechanism?
* Should we offer a general stacktrace post-processing mechanism?

**Comment by mp911de** [comment]
You can draw some ideas from https://logging.paluch.biz/ that included stack trace filtering, dynamic MDC inclusion/exclusion and field name handling back from when that project has been active.

**Comment by philwebb** [comment]
We discussed this today and we'd like to offer some enhancements if we can. I'm not sure how much we'll be able to get into 3.4 at this point. We might take stacktrace post-processing off the table for now.

**Comment by maxxedev** [comment]
* It does not seem possible to rename `@timestamp` to `timestamp`
* Is it possible to customize timestamp value? Can `LOG_DATEFORMAT_PATTERN` be applied there?

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @maxxedev. Please open a new issue so that we can consider it.

**Comment by philwebb** [comment]
Issue was opened as #42980
