### ISSUE TITLE
Add property to specify Docker Compose flags

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#42500]
https://github.com/spring-projects/spring-boot/issues/38763 allows specifying the arguments passed to the start and stop Docker Compose commands.

However, there are some commands which needs to be passed to `docker compose` directly after and before any subcommand like `up`. `--project-name` is one of them.

We should add a new property to allow that. Maybe `spring.docker.compose.arguments`?

**Comment by nosan** [comment]
I've prototyped some changes in my [branch](https://github.com/spring-projects/spring-boot/compare/main...nosan:spring-boot:gh-42500). If it is something that you are looking for, let me know and I will create PR.

**Comment by mudabirhussain** [comment]
> #38763 allows specifying the arguments passed to the start and stop Docker Compose commands.
> 
> However, there are some commands which needs to be passed to `docker compose` directly after and before any subcommand like `up`. `--project-name` is one of them.
> 
> We should add a new property to allow that. Maybe `spring.docker.compose.arguments`?

Yes, arguments should be passed via props, but I suggest a slightly different approach, like spring.docker.compose.arguments.file, spring.docker.compose.arguments.project-name, and spring.docker.compose.arguments.env-file. Alternatively, we can simplify it by omitting 'arguments' and use: spring.docker.compose.project-name, spring.docker.compose.env-file, and spring.docker.compose.file.

What do you suggest?

**Comment by mhalbritter** [comment]
> I've prototyped some changes in my [branch](https://github.com/spring-projects/spring-boot/compare/main...nosan:spring-boot:gh-42500). If it is something that you are thinking about, let me know and I will create PR.

Hey @nosan , thanks for working on that. Please create a PR, i'll try to get it into 3.4.0-RC1. Thanks!

**Comment by nosan** [comment]
Hey @mhalbritter,
[PR](https://github.com/spring-projects/spring-boot/pull/42571) has been created.
Thanks

**Comment by mhalbritter** [comment]
Superseded in favor of #42571.
