### ISSUE TITLE
SPEL behavior changed after upgrading to Spring Boot 3.3.2

### ISSUE THREAD

**Issue by prathmeshpethkar** [spring-projects/spring-boot#42507]
# We noticed the value of the acceptedRoles changed 

## TestController.java

```java
@Value("#{T(java.util.Arrays).asList('${person.acceptedRoles}')}")
private List<String> acceptedRoles;
```

## application.properties

```
person.acceptedRoles=
```

With spring boot version 3.3.1 and before the value returned is 0 but after upgrading to 3.3.2 and above the value returned is 1

@lalithaawgu

**Comment by wilkinsona** [comment]
SpEL is a [Spring Framework](https://github.com/spring-projects/spring-framework) issue. Please report this in their issue tracker, providing a minimal sample that reproduces the problem. As things stand it's not clear, to me at least, what's returning the value `0` when previously it was `1`.
