### ISSUE TITLE
how to use set cache ttl  at redis?

### ISSUE THREAD

**Issue by vodcms** [spring-projects/spring-boot#4253]
pls hele !

tell my how to use set cache ttl  at redis?.

thks for you

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
