### ISSUE TITLE
EmbeddedServerPortFileWriter does not allow to override filename when used from META-INF/spring.factories

### ISSUE THREAD

**Issue by pwielgolaski** [spring-projects/spring-boot#4254]
It seems that this line should run next constructor: this(new File(...))
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/system/EmbeddedServerPortFileWriter.java#L60

**Comment by snicoll** [comment]
good catch, thanks.
