### ISSUE TITLE
Enable /logfile endpoint when installed as init.d service

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#4255]
I'm running `1.3.0.RC1` [as a linux service using init.d](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#deployment-service), relying on the `/var/log/<appname>.log` provided by default. Currently this does not match the `LogFileCondition` introduced as part of #3360 to enable the `/logfile` endpoint to work. Is that something that can be changed?

As per: https://gitter.im/spring-projects/spring-boot?at=562760e9dd7fb14516cf4906

**Comment by snicoll** [comment]
From your perspective I understand what you mean but what the linux service does is effectively redirect the out and err output to the file. In other words, this is managed outside Spring Boot, I guess we would have to pass that information to the process somehow.
