### ISSUE TITLE
ConfigFileEnvironmentPostProcessor does not log anything anymore

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4258]
`ConfigFileEnvironmentPostProcessor` is using a `DeferredLog` to cache log messages until the logging system is actually initialized. The processing of the configuration is made on one instance created by `EnvironmentPostProcessingApplicationListener` while further events (including the one that is triggering the logs) on another one.

Could it be that the second is created by `ConfigFileApplicationContextInitializer`?

I can see that `ConfigFileEnvironmentPostProcessor` is registered twice in `spring.factories` as well.

**Comment by snicoll** [comment]
ping @wilkinsona @philwebb

**Comment by snicoll** [comment]
One instance created by [`SpringApplication#initialize`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L253)

Another instance created by [`EnvironmentPostProcessingApplicationListener`]

**Comment by wilkinsona** [comment]
@snicoll Here's a possible fix: https://github.com/wilkinsona/spring-boot/tree/gh-4258

**Comment by wilkinsona** [comment]
There are other problems here:

 -  `ConfigFileEnvironmentPostProcessor` is still an `ApplicationListener`, but only for the `ApplicationPreparedEvent`. Anyone using it via `SpringApplication.setListeners` with custom search locations or names will not get the behaviour they expect: they'll get the default behaviour as it's loaded via `spring.factories` as an `EnvironmentPostProcessor`.
 - Going back to `ConfigFileApplicationListener` would address the problem described above, but it creates a new one with regards to ordering. If `ConfigFileApplicationListener` stops being an `EnvironmentPostProcessor` then it will either run before all `EnvironmentPostProcessors` or after all of them. Given it's current high precedence, going before all of them would appear to make sense. Unfortunately, `CloudFoundryVcapEnvironmentPostProcessor` needs to go before `ConfigFileApplicationListener`. To be able to do so, it would have to become an `ApplicationListener` too. At this point, we have no users (within Boot itself) of the `EnvironmentPostProcessor` abstraction.
