### ISSUE TITLE
No transactionId anymore in implementation classes of ErrorWebExceptionHandler

### ISSUE THREAD

**Issue by sigriswil** [spring-projects/spring-boot#42600]
Spring boot version: 3.3.2
sample issue spring cloud gateway repository: [https://github.com/sigriswil/spring-gateway-sample](https://github.com/sigriswil/spring-gateway-sample)

It contains a SpringBoot application that can be started locally. When reaching the endpoint /, it raises an exception which triggers the class GlobalErrorWebExceptionHandler which implements ErrorWebExceptionHandler.

In the main method, `Hooks.enableAutomaticContextPropagation()` and `ContextRegistry.getInstance().registerThreadLocalAccessor(...)` are called in FirstGatewayFilterFactory.

Add the MDC's trasactionId to the FirstGatewayFilterFactory, An exception occurs in the SecondGatewayFilterFactory.
transactionId is output from SecondGatewayFilterFactory and FirstGatewayFilterFactory, but transactionId is not output from GlobalErrorWebExceptionHandler.

```
INFO 48248 --- c.e.s.SecondGatewayFilterFactory: SecondGatewayFilterFactory start, MDC: {transactionId=2e58da57-2f01-4d29-b63d-61b2e9682301}
ERROR 48248 --- c.e.s.GlobalErrorWebExceptionHandler: MDC: null
...
INFO 48248 --- c.e.s.FirstGatewayFilterFactory: FirstGatewayFilterFactory.doFinally, MDC: {transactionId=2e58da57-2f01-4d29-b63d-61b2e9682301}
```

**Comment by philwebb** [comment]
I think someone from the Micromete, Reactor or Spring Cloud team will need to help with this issue. Spring Boot isn't really involved at this level.

It looks to me like `io.micrometer.context.DefaultContextSnapshotFactory.setAllThreadLocalsFrom` is clearing the MDC thread local.

@spencergibb @chemicL are you able to help identify what's causing the issue and which project can help?

**Comment by chemicL** [comment]
I have no knowledge about Spring Cloud Gateway's lifecycle with the `AbstractGatewayFilterFactory` but this situation where there is a global instance of `ErrorWebExceptionHandler` sounds similar to the case encountered with Spring Framework where observability was added as a `WebFilter` which was at a more internal layer than the catch-all `ExceptionHandlingWebHandler` which is outside (check related [discussion](https://github.com/spring-projects/spring-framework/issues/30013#issuecomment-1443608666) and [fix](https://github.com/bclozel/spring-framework/commit/fed0f164ece6161d23563ede606408b9239d659c)). So MDC keys set in one `AbstractGatewayFilterFactory` (`FirstGatewayFilterFactory`) won't be visible to any filter that is ordered prior to it. I am certain @spencergibb is able to provide guidance :)
