### ISSUE TITLE
Upgrade MySQL JDBC Driver to 5.1.37

### ISSUE THREAD

**Issue by michael-mccutcheon** [spring-projects/spring-boot#4262]
It would be cool to get the latest driver in 1.3.

All you have to do is update spring-boot-dependencies\pom.xml:

<mysql.version>5.1.37</mysql.version>

I tried to do this myself but I don't have privs to create branches/pull requests, etc.

**Comment by wilkinsona** [comment]
Anyone can submit a PR, but you need to fork the repository first. That said, don't worry about it for this issue unless you really want to. It's only a one-liner

**Comment by michael-mccutcheon** [comment]
I don't know everything necessary to create a merge request today, so if you want to go ahead and update that one line of code that would be great!

Thanks!
