### ISSUE TITLE
Bean from Configuration class is not picked up, 

### ISSUE THREAD

**Issue by Cuneytt** [spring-projects/spring-boot#4264]
Trying to configure a @Bean through @Configuration as below:
```
@Configuration
public class DmsConfigLocation {

    private static String path = "/opt/apps/resource/dms2/dms.conf";
    
    @Bean
    public AppConfigLocation dmsConfigLocation() {
        return AppConfigLocation.createFileLocation(path);
    }
}
```

And getting 
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type
```

But when DmsConfigLocation is switched to be a @Component then it is picked up.

```
@Component
public class DmsConfigLocation extends AppConfigLocation {
    
    private static String path = "/opt/apps/resource/dms2/dms.conf";

    public DmsConfigLocation() {
        super(Type.FILE, path);
    }   
}
```

Is there  a reason why the first approach does not work?

**Comment by philwebb** [comment]
This type of question is best asked on stackoverflow.com. If you repost your question, you should include some more details. The first line of the stacktrace is not enough to tell which bean could not be found or why.
