### ISSUE TITLE
Upgrade to HttpClient5 5.4

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#42675]

**Comment by snicoll** [comment]
There are a number of deprecations around TLS that affect our build support. I am investigating what's the best replacement for those.

**Comment by Shivam1-123** [comment]
@snicoll can you give me more details? I am new to this and I want to work on this.

**Comment by snicoll** [comment]
@Shivam1-123 thanks for the offer but I am already assigned on the issue. I am afraid the changes are pretty advanced so it might not be a good pick for a newcomer.

**Comment by Shivam1-123** [comment]
@snicoll Okay Thank you clearing that out.
