### ISSUE TITLE
Add property to control export of OTLP logs

### ISSUE THREAD

**Issue by andrzej-fisglobal** [spring-projects/spring-boot#42781]
In Spring Boot 3.4.0-M3, `OtlpLoggingConfigurations.otlpHttpLogRecordExporter` is a created if `OtlpLoggingConnectionDetails` is created, the latter is a conditionally created if the property `management.otlp.logging.endpoint` is defined. It looks like the only option to disable this to not define the endpoint key.

However, it makes it a bit difficult if we have already defined the endpoint and want to disable it. 

Is it possible to define an `enabled` toggle in a similar manner that we have for e.g. `management.otlp.metrics.export`? In general, it would be nice to be able to disable signal exporters in a consistent way -- thus something similar to `OnEnabledTracingCondition` and `OnMetricsExportEnabledCondition`?

**Comment by mhalbritter** [comment]
We have `management.*.metrics.export.enabled`, `management.*.tracing.export.enabled` and I think for consistency we should also add something like `management.otlp.logging.export.enabled`.

**Comment by nosan** [comment]
You should be able to disable the `otlpHttpLogRecordExporter` by setting `management.otlp.logging.transport=none`, right?

**Comment by nosan** [comment]
But this property does not exist in `additional-spring-configuration-metadata.json` 🥲

**Comment by nosan** [comment]
Apologies @mhalbritter and @andrzej-fisglobal for the confusion. I overlooked the fact that this property maps to enum values. My apologies for the oversight.

**Comment by mhalbritter** [comment]
Don't worry, no harm done :)

**Comment by andrzej-fisglobal** [comment]
Thanks for your comment. That makes it indeed a bit easier, but still, it would be nice to have consistency among those -- what Moritz proposed.

**Comment by mhalbritter** [comment]
Superseded in favor of #42813.
