### ISSUE TITLE
start.spring.io generates unsupported gradle wrapper 8.10.2 for kotlin 1.9.25

### ISSUE THREAD

**Issue by gmuth** [spring-projects/spring-boot#42791]
According to [kotlin gradle plugin documentation](https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin) versions 6.8.3–8.1.1 support kotlin 1.9.20–1.9.25.

However Spring Initializer for Spring Boot 3.3.4 generates:

`kotlin("jvm") version "1.9.25"`

and 

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-bin.zip`

**Comment by wilkinsona** [comment]
https://start.spring.io is a separate project. Please raise this at https://github.com/spring-io/start.spring.io/issues.
