### ISSUE TITLE
Autoconfigure micrometer tracing for transactions

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-boot#42796]
With the migration from Spring Cloud Sleuth to Micrometer Tracing, the direction was to move instrumentation support to [respective projects](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#instrumentations).

I filed https://github.com/spring-projects/spring-framework/issues/33751 to support this instrumentation on the framework level. The second part of Sleuth was to autoconfigure trace-able transaction managers. This falls into Spring Boot land.

Original autoconfiguration in Sleuth: https://github.com/spring-cloud/spring-cloud-sleuth/tree/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/tx

This would bring parity for tx tracing support to Spring Boot 3+.

**Comment by bclozel** [comment]
Framework issue was declined.
