### ISSUE TITLE
Add support for ClickHouse JDBC driver in enum DatabaseDriver

### ISSUE THREAD

**Issue by mirkoscotti** [spring-projects/spring-boot#42799]
I am using DataSourceBuilder to create a JDBC data source with this fragment of code
```
DataSourceBuilder.create(Thread.currentThread().getContextClassLoader())
				.type(DriverManagerDataSource.class)
				.driverClassName(DatabaseDriver.fromJdbcUrl(url).getDriverClassName())
				.url(url)
				.username(username)
				.password(password)
				.build()
```
Unfortunately my URL is **jdbc:clickhouse://mydatabase:myport** and DatabaseDriver does not define an item 
```
CLICKHOUSE("ClickHouse", "com.clickhouse.jdbc.ClickHouseDriver", .... )
```
I wonder if you could add the support for this kind of database. My Maven dependency is spring-boot-dependencies 3.3.4.
Thanks.

**Comment by philwebb** [comment]
Closing in favor of PR #42815. Thanks @nosan!
