### ISSUE TITLE
Actuator for non boot application

### ISSUE THREAD

**Issue by pradhakrishnan** [spring-projects/spring-boot#4280]
Team,

My application uses spring MVC with spring data rest. I need to collect the metrics for my application using Actuator.

Can some one help me how to configure Actuator for non boot application.

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com). Before posting a new question, you might like to do a quick search. [This existing question](http://stackoverflow.com/questions/26913087/use-spring-boot-actuator-without-a-spring-boot-application) may be of interest.
