### ISSUE TITLE
external application.properties when installed as an init.d service

### ISSUE THREAD

**Issue by henszey** [spring-projects/spring-boot#4281]
I'm running 1.3.0.RC1 [as a linux service using init.d](http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#deployment-service). Placing an application.properties file next to the jar does not work. It looks like when run as a service its working directory is root so its looking for /application.properties. It would be ideal if a properties file could be picked up by convention from the same directory that jar is in or /etc.

Currently I am [using a conf file](http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#deployment-script-customization-conf-file) with the following as a work around:
RUN_ARGS=--spring.config.location=/var/application/application.properties

**Comment by sauliust** [comment]
I noticed this change also after update from M5. In M5 working directory was jar file directory.

**Comment by wilkinsona** [comment]
This is an unwanted side-effect of moving to `start-stop-daemon`. We need to use `--chdir` to set the working directory.

**Comment by snicoll** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/efa730350742caaff1fa77bbde8521ab54c91db3
