### ISSUE TITLE
Support ResourceLoader delegation from ApplicationResourceLoader

### ISSUE THREAD

**Issue by zmkpr0** [spring-projects/spring-boot#42835]
Is there a reason that `JksSslStoreBundle` creates a new instance of `ApplicationResourceLoader` instead of using an existing `DefaultResourceLoader`? 

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/ssl/jks/JksSslStoreBundle.java 

`Resource resource = new ApplicationResourceLoader().getResource(location);`

Creating a new `ApplicationResourceLoader` instance means that for example [S3ProtocolResolver ](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-s3/src/main/java/io/awspring/cloud/s3/S3ProtocolResolver.java) from Spring Cloud AWS that works by registering itself using `ResourceLoaderAware` is ignored and only those declared in spring.factories get picked. 

I know there are a few ways to work around this, but it's not that obvious that not all `ProtocolResolvers` work when declaring a bundle.

**Comment by philwebb** [comment]
I'm currently looking at #42468 and would like a way to have auto-configured SSL Bundles work with the classloader from the application context `ResourceLoader`. It seems like supporting delegation would be possible once that is fixed.
