### ISSUE TITLE
HttpWebServiceMessageSenderBuilder javadoc should state that returns are this instance

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42858]
`HttpWebServiceMessageSenderBuilder` has `@return a new builder instance` Javadoc, but the instance is not actually new.

**Comment by 1328032567** [comment]
Hi @philwebb

I wanted to let you know that the bug you reported has been fixed in the pull request #42868. 

Please take a look and let me know whether the PR is ok.

Thanks!

**Comment by wilkinsona** [comment]
Oops, I've just noticed that this issue is already assigned to Phil, indicating that he's already working on it. I'm afraid that means that we won't accept a pull request for it.

**Comment by 1328032567** [comment]
> Oops, I've just noticed that this issue is already assigned to Phil, indicating that he's already working on it. I'm afraid that means that we won't accept a pull request for it.

What a pity! Btw, I'm also new in open-source project, and would like to make my little contributions to this project. Anyway, thanks for your reply.

**Comment by philwebb** [comment]
Actually, I only assigned the issue to myself because I wanted to avoid merge conflicts whilst working on something else. I'll take a look at the PR. Thanks @1328032567.

**Comment by 1328032567** [comment]
> Actually, I only assigned the issue to myself because I wanted to avoid merge conflicts whilst working on something else. I'll take a look at the PR. Thanks @1328032567.

Oh, I appreciate your reply so much. I just changed the comments on the class, and it's not a big deal, because I don't know what's the requirement haha. Now, I figured out, this issue is just for internal group to work with. Anyway, thanks for your reply again.
