### ISSUE TITLE
Unify default HTTP client redirect behavior and provide configuration option

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#42879]
Switching to `JdkClientHttpRequestFactory` as our default has interesting implications when it comes to following redirects. By default, `JdkClientHttpRequestFactory` does not where as `SimpleClientHttpRequestFactory` does. We should consider carefully what our default should be and if we want to offer a quick way to change it.

**Comment by quaff** [comment]
#27360 is related.

**Comment by philwebb** [comment]
Thanks @quaff. I wish we could configure redirects on a per call basis, but unfortunately that looks pretty tricky.

**Comment by philwebb** [comment]
Reopening to check methods other than GET

**Comment by philwebb** [comment]
| Method | JDK |
| --- | --- |
|`GET` | ✅ |
|`PUT` | ✅ |
|`POST` | ⛔ | 
|`PATCH` | ⛔ |

**Comment by philwebb** [comment]
Given that Simple is not likely to be used now, we'll leave things as they are. I'll add some more tests.
