### ISSUE TITLE
spring boot starter pulsar  maven download failed

### ISSUE THREAD

**Issue by lucky-lbc** [spring-projects/spring-boot#42897]
hi， i have a question about pom dependency。 like this pic
![图片](https://github.com/user-attachments/assets/c250c89e-f8d7-46f0-91c8-0c66a9604605)
i see the spring-boot-starter-pulsar is exist. in the starters.  not understand of download failed;

my english is pool. please understand

**Comment by bclozel** [comment]
Hello
I don't know why your IDE did not resolve this dependency. It is present on Maven Central: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-pulsar/3.3.1/

If you would like some help with your IDE, please ask the dedicated support or ask a question on Stackoverflow.

Thanks.
