### ISSUE TITLE
Spring Boot Build Crash

### ISSUE THREAD

**Issue by hottelet** [spring-projects/spring-boot#4289]
I am writing to provide this sample support project to Phil Webb, Spring Boot, et al,

Support Project 
https://www.dropbox.com/s/h1lhf86h746jb7u/rest-server-support.tar.gz?dl=0

Crash Log file:
https://www.dropbox.com/s/sxxlmycv3xfbi4i/rest-server-log-20151023T133444.txt?dl=0

'The goal of this sample project is to help the pivotal team, help this project spring boot. 
1. I used Spring beans 
2. I use spring boot 
3. There are errors with the Tomcat servlet, and linking errors. 
4. The jar file needs to be built with Intellij, to build the artifacts and executable JAR file 
5. The compiled project using build.script , after compiling the persistence library, see Readme.txt , does not run with java -jar ./target/gs-rest-service-0.1.0.jar 
6. Instead the project needs to be compiled with maven using build.script 
7. Then with Intellij, by using menu -> File-> Project Structure -> Artifacts -> click +, then select JAR -> from modules with dependencies -> gs-rest-service 
Main class = server.Application 
extract to the target JAR 
Directory for META-INF = $PROJECT_DIR/rest-server-support/rest-server-server/src/main/resources 
8. Then Intellij -> menu -> Build -> Build Artifacts --> Build 
9. The generated JAR file is in the server/out directory as gs-rest-service.jar 
10. Notice that the class loader when trying to run with maven build can not load the dependencies correctly (bullet 5) 
11. I need the Property source, and application.properties files, so that the command line arguments are configurable 
12. I need the bean.xml file so that i can point to the Properties class, that has the database connector for cassandra and the driver. 
13. Database connector persistence is used in ServletController.java , lines 94-125, I needed to link the database driver into the project using Spring Beans from the bean.xml file

I am writing to provide you the following: 
1. a sample support project that uses Spring-Boot. 
2. see Application.java lines 92-94, to see the suggested workaround by the Twitter engineer. Phil Webb had 
acknowledged that I should not have to do that. 
3. See spring boot, failed to boot, attached file rest-server-log*.txt 
'org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in server.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/catalina/LifecycleListener' 
4. See Application.java lines 96-99, TomcatEmbeddedServletContainerFactory, Phil Webb acknowledges that I should not have to do this. 
5. Refer back to spring boot exceptions being thrown 
6. See https://github.com/spring-projects/spring-boot/issues/4283 , by Stéphane Nicoll. He acknowledges that there is a problem with TraceWebFilterAutoConfiguration.

https://github.com/spring-projects/spring-boot/issues/4276#issuecomment-150326271 
Commentary from Phil Webb, "The @Configuration, @EnableAutoConfiguration and @ComponentScan annotations are not needed when you use @SpringBootApplication.
If possible I'd recommend trying to avoid using XML bean definitions with Spring Boot. 
Your @PropertySource annotations should not be needed, it appears that you're trying to define direct imports of the application.properties files that Spring Boot configures automatically. 
Your logger definition should probably be using Application.class as it's source, not ServletController.class. 
There is no need to define TomcatEmbeddedServletContainerFactory, Spring Boot will auto-configure Tomcat 
I'm not sure what the cassandraProperties stuff is about in your main methods, but you might be interested to know that the upcoming Spring Boot 1.3 version will include Cassandra support"

https://github.com/spring-projects/spring-boot/issues/4278#issuecomment-150371817 
"Consider creating a issue GitHub project rather than pasting lots of individual file snippets. 
The org.apache.tomcat.util.buf.UDecoder.URLDecode class is provided by tomcat-embedded-core. The easiest way to get the dependency is to use spring-boot-starter-web. Looking at your POM you seem to be declaring versions for various dependencies that could be managed by Spring Boot."'

**Comment by philwebb** [comment]
I downloaded the dropbox project and took a look at `out/artifacts/gs_rest_service_jar/gs-rest-service.jar`. It appears to have tomcat jars nested inside at the root and it doesn't seem to be using Spring Boot's fat jar format.

Your issues seem to be coming from your non standard build process and I don't think there is an actual Spring Boot bug here.
