### ISSUE TITLE
spring-boot-starter-test's dependency on jsonassert causes org.json conflicts in modular Java projects

### ISSUE THREAD

**Issue by allurx** [spring-projects/spring-boot#42898]
I'm encountering an issue with `spring-boot-starter-test` when using it in a modular Java project (Java 9+). Specifically, the transitive dependency on jsonassert includes `android-json`, which provides an `org.json` package that conflicts with the `org.json` package in `jsonassert`.This issue results in compilation errors when using `module-info.java`.
## Issue Details
- Spring Boot Version: 3.3.5
- Dependency Causing Conflict: `org.skyscreamer:jsonassert` → `com.vaadin.external.google:android-json:0.0.20131108.vaadin1`
- Module System: Java 9+ with `module-info.java`
Since `spring-boot-starter-test` includes `jsonassert` as a transitive dependency, and `jsonassert` relies on `android-json` (which includes `org.json`), this leads to duplicate `org.json` packages in modular projects, which Java's module system does not allow.

**Comment by wilkinsona** [comment]
Duplicates #40949.
