### ISSUE TITLE
Make AliasKeyManagerFactory.AliasX509ExtendedKeyManager.chooseClientAlias return alias instead of null

### ISSUE THREAD

**Issue by kleineman85** [spring-projects/spring-boot#42908]
Hello team,

Could you make AliasKeyManagerFactory.AliasX509ExtendedKeyManager.chooseClientAlias return alias instead of null?
I really like the new ssl module. However from the point of view of a client when using mtls and using a keystore with multiple (private) keys the SSL handshake fails after validating the server. And when chooseClientAlias returns alias it passes.

`

    @Override
    public String chooseClientAlias(String[] keyType, Principal[] issuers, Socket socket) {
        return alias;
    }
`

**Comment by wilkinsona** [comment]
We can certainly consider it. To help us to do so, please provide a complete yet minimal sample that reproduces the handshake failure you have described above.

**Comment by kleineman85** [comment]
Wow thank you for the quick reply. I didn't expect that. I will provide a sample at least before november 11th (kinda busy but I'll do my best to provide it asap).

**Comment by kleineman85** [comment]
you can close this issue. I will not be able to provide the requested information in time. My apologies
