### ISSUE TITLE
Separate CLI infrastructure from boots commands implementations 

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#4290]
I want to write a cli similar too spring boots one. I think it would be nice if the cli-infrastucture and abstractions would be separated from the concrete command implementations for spring boot.

**Comment by dsyer** [comment]
I actually always thought we'd do this in 1.3, but no-one else asked, so there was no sign of real demand, and it's a bit late now probably. You can probably work around it by just depending on spring-boot-cli and writing your own main class (`SpringCli` is pretty short so copying it won't be a burden).

**Comment by joshiste** [comment]
So do you go for it with 1.4 ?

**Comment by dsyer** [comment]
We can at least start discussing it here. If you use 1.3 with the workaround you can help shape the way it gets implemented.

**Comment by joshiste** [comment]
First of all using boot cli as dependency works great. But it pulls in a lot of maven and groovy stuff i've excluded. This forces me to do copy the `OptionHandler` and removing Groovy's `Closure`.

[It's a WIP but if you're interested can have a first look at it](https://github.com/joshiste/spring-boot-admin/tree/cli/spring-boot-admin-cli)

**Comment by philwebb** [comment]
I think one reason that we never went too far down this road is that a separating the code CLI parts becomes a maintenance burden. Currently (with the exception of CLI extensions) we are free to do what we want to the CLI without too much fear of breaking things. Once we extract common CLI code things start to become a little more set in stone.

**Comment by joshiste** [comment]
Would you the accept minor improvements (as in #4411) to the code without separating? This would make reuse a bit more easy and doesn't force you to keep the API stable since it's not 'officially' exposed.

**Comment by dsyer** [comment]
> Once we extract common CLI code things start to become a little more set in stone.

Maybe now is the right time to break it up then. Time is tight for 1.3 though and the code that @joshiste had to copy to get his CLI working wasn't much (was my impression, please correct me if that's wrong), so I reckon this can all be pushed back to 1.4.

**Comment by snicoll** [comment]
We don't plan to enhance the CLI at this point.
