### ISSUE TITLE
Allow to auto configure `ThreadPoolTaskScheduler`/`ThreadPoolTaskExecutor` even if virtual threads enabled

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#42920]
Currently Spring Boot auto configure `SimpleAsyncTaskScheduler`/`SimpleAsyncTaskExecutor` if virtual threads enabled, so far so good. 
If #42918 get merged,  I suggest to introduce configuration property that allow to auto configure `ThreadPoolTaskScheduler`/`ThreadPoolTaskExecutor` instead even if virtual threads enabled.

**Comment by bclozel** [comment]
#42918 doesn't seem related, I guess you mean #42913. In any case we didn't even have time to consider the use case nor [Juergen's comment](https://github.com/spring-projects/spring-framework/issues/33780#issuecomment-2442241269), including the fact that pooling is breaking one of the best practices of virtual threads.

I've created #42921 to start discussing that with the team.
