### ISSUE TITLE
IllegalArgumentException on org.springframework.web.servlet.resource.ResourceHttpRequestHandler v6.2.0-RC3 if resource doesn't end with slash

### ISSUE THREAD

**Issue by milazzo-g** [spring-projects/spring-boot#42929]
During context loading the `ResourceHttpRequestHandler` class scans all possible paths and if these do not end with "/" an `IllegalArgumentException` type exception is thrown with message "_Resource location does not end with slash: …_" (see `ResourceHttpRequestHandler@282` the call to `ResourceHttpRequestHandler::assertLocationPath`) this cause several issue with various jar included (in our case `camunda-webapp-webjar` **7.22.0** - included by `camunda-bpm-spring-boot-starter-root` **7.22.0)**.

The path provided by the library is "_classpath:/META-INF/resources/webjars/camunda_" which as you can see does not contain the final "/". makes it unusable with `spring-boot` **6.2.0-RC3**.

We temporary fixed creating a copy of `org.springframework.web.servlet.resource.ResourceHttpRequestHandler` in our src folder and modifying starting from line 282 from:

`ResourceHandlerUtils.assertLocationPath(location);`

to:

```
try {
 ResourceHandlerUtils.assertLocationPath(location);
} catch (Exception e) {
 if (org.apache.commons.lang3.StringUtils.containsIgnoreCase(e.getMessage(), "resource location does not end with slash")){
  location += "/";
 }else {
  throw e;
 }
}
```

this solved the issue. Could you please fix it in a next minor?

KR.

Giuseppe.

![1_ResourceHttpRequestHandler](https://github.com/user-attachments/assets/e3b5e16d-f750-4cad-8b6b-69ddef138cc6)
![2_ResourceHandlerUtils](https://github.com/user-attachments/assets/ecdb1aee-7078-4b32-a972-ce2cbf0aeb6f)
[STACKTRACE.txt](https://github.com/user-attachments/files/17559455/STACKTRACE.txt)

**Comment by philwebb** [comment]
The code in question is part of Spring Framework. I've duplicated your issue to https://github.com/spring-projects/spring-framework/issues/33815
