### ISSUE TITLE
Clarify scope of DataSourceInitializedEvent

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4292]
If you're using Flyway but not using JPA there's no DataSourceInitializedEvent once the database migrations have completed. The javadoc suggests that there should be:

> ApplicationEvent used internally to trigger DataSource initialization. Initialization can occur when `schema-*.sql` files are executed or when external libraries (e.g. JPA) initialize the database.

I suspect Liquibase will behave the same way.

See http://stackoverflow.com/questions/33307051/importing-data-with-flyway-and-spring-boot

**Comment by thombergs** [comment]
I have been looking into this. It seems easy enough to simply publish a DataSourceInitializedEvent after a successful Flyway or Liquibase migration. Is that enough, however? In both cases, the event would be published from within an `afterPropertiesSet` method and as I understand it, a potential EventListener may not yet be registered at that time and thus never receive the event.

**Comment by snicoll** [comment]
For the record I am considering removing that event altogether. This is currently used as an internal signal between two components and wasn't mean to be used externally as far as I can see.

**Comment by snicoll** [comment]
@wilkinsona actually it has a bit more side effect. If there is a `data.sql` and datasource initialization is enabled, this will execute `data.sql`. I'd rather avoid mixing our initializer with flyway and liquibase (they should probably handle everything). 

Also, do we want to fire that event for a DataSource that is up to date? An existing datasource where some patches were applied on it? 

I much rather rename the event and clarify its scope. Thoughts?
