### ISSUE TITLE
[3.3.5] : From [3.3.2] until [3.3.5] a JpaSystemException is appearing in my Spring Batch project

### ISSUE THREAD

**Issue by hamzaUppli** [spring-projects/spring-boot#42946]
Hello,

I have a [3.3.1] Spring boot project and i use Spring Batch(I am letting Spring boot handling the versions of my dependencies except the ones it can't handle like MapStruct for example).

I want to upgrade my project to 3.3.5 and i had an issue where i had this error out of nowhere [org.springframework.orm.jpa.JpaSystemException: A problem occurred in the SQL executor : JDBC parameter value not bound - null] and [Caused by: org.hibernate.sql.exec.ExecutionException: A problem occurred in the SQL executor : JDBC parameter value not bound - null]

This happens when my repository methodName is executed by the RepositoryItemReader.
Before, continuing i will provide you with an image that shows that i provide all of the parameters for the method and that i can only see them at the version [3.3.1] but not in all the upper versions[3.3.2] and beyond.

This is an example of the definition of the method in question : 

<img width="1148" alt="Capture d’écran 2024-10-30 à 17 50 03" src="https://github.com/user-attachments/assets/8a091755-94ec-45d0-904a-e7531672093a">

This image is for Spring boot [3.3.1] and down : 

<img width="1108" alt="Capture d’écran 2024-10-30 à 17 17 09" src="https://github.com/user-attachments/assets/cf6e1863-a06a-4787-a4c5-2ce349bcfbc8">

This image is for spring boot [3.3.2] and up :

<img width="1070" alt="Capture d’écran 2024-10-30 à 17 25 17" src="https://github.com/user-attachments/assets/cffdc9c3-c3db-4052-98d8-87843aa4bcce">

I do suspect the pagination and i mean by that the first argument in the request
<img width="622" alt="Capture d’écran 2024-10-30 à 17 34 25" src="https://github.com/user-attachments/assets/f021a144-1e79-4eca-909b-68b14044a798">

Here are more images of the exception because i tried to debug to understand a little bit what's happening :
<img width="1166" alt="Capture d’écran 2024-10-30 à 14 58 53" src="https://github.com/user-attachments/assets/bcc1a5b6-1b91-4bd6-a74d-05b929660b08">

<img width="1121" alt="Capture d’écran 2024-10-30 à 17 00 03" src="https://github.com/user-attachments/assets/5eec1bb0-b0a8-4fed-9695-54d633dc2035">

**Comment by wilkinsona** [comment]
Spring Boot isn't really involved in Spring Batch's use of JPA and is unlikely to be the cause of your problem. More likely is that the cause is a bug in Spring Batch or Hibernate. If you'd like some further assistance, please create a minimal sample that works with Spring Boot 3.3.1 and fails when upgraded to 3.3.2 and then open a [Spring Batch issue](https://github.com/spring-projects/spring-batch/issues) so that the Batch team can investigate.
