### ISSUE TITLE
Add a way to disable running Flyway migrations automatically without disabling Flyway itself

### ISSUE THREAD

**Issue by elnur** [spring-projects/spring-boot#4295]
I have a use case where I need to run Flyway migrations manually for testing. If I add `flyway.enabled=false` to `application-test.properties`, it disables Flyway completely meaning that I need define my own `Flyway` bean and configure it.

That's not optimal because I want to keep the `Flyway` bean created automatically but do not have its `migrate()` method called automatically.

**Comment by wilkinsona** [comment]
You can already do this by defining a bean that implements `FlywayMigrationStrategy` and does nothing in `migrate`

**Comment by elnur** [comment]
Hm. True. I see that class here but can't find it in my project that uses Boot 1.2.7. Is it coming in 1.3?

**Comment by snicoll** [comment]
Yes.

**Comment by elnur** [comment]
Okay. I'll create my own `Flyway` bean for now. Thanks.
