### ISSUE TITLE
Warning due to duplicate MockResolver extensions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#42957]
```
[WARNING] Found duplicate and different resources in [org.springframework.boot:spring-boot-test:3.4.0-20241031.110032-485, org.springframework:spring-test:6.2.0-RC3]:   mockito-extensions/org.mockito.plugins.MockResolver
```

Following https://github.com/spring-projects/spring-framework/commit/d8a6423c0cbb0aa717fa5f2762187c6ce860bca0, we should remove Boot's custom `MockResolver` and rely on Framework's instead.

**Comment by philwebb** [comment]
Closing in favor of PR #42988. Thanks @nosan!
