### ISSUE TITLE
Remote devtools fail if the application url end with a slash

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4297]
> I just tried to do the exat same things in STS Boot Dash and it..... worked.
>Comparing the launch conf that works with the one that doesn't...
>The only difference is an extra '/' at the end of remote url.
>So use remote url 'http://localhost:6789/' gets the funky errors.
>But using remote url 'http://localhost:6789' works.

**Comment by kdvolder** [comment]
I put up some more details, including a simple project and steps that reproduce the problem here:
https://github.com/kdvolder/hello-world-test-app
