### ISSUE TITLE
Compression on Undertow does work for Spring Boot 1.2.7 version

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#4303]
Hi all, 

I tried to enable the compression/gzip for Undertow on version 1.2.7, but looking the code of UndertowEmbeddedServletContainer it does not have anything about it.

If I look at https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/undertow/UndertowEmbeddedServletContainer.java I can see that exists a method called configurationCompressionIfNecessary.

Will it only able for version 1.3.0?

Tks

**Comment by snicoll** [comment]
As we have asked you _several times_ already, could you please stop asking questions here? 

If you check [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-Full-Release-Notes#http-response-compression), there is a native support in 1.3 and you can use Jetty’s GZipFilter in 1.2.
