### ISSUE TITLE
Spring Boot Actuator 1.3.0.RC1 - Statsd counter treated as gauge

### ISSUE THREAD

**Issue by 56quarters** [spring-projects/spring-boot#4305]
Hi,

I've run across a situation where inputs to a `CounterService` in Spring Boot Actuator end up being written to Statsd as gauge messages instead of counter messages. 

Expected behavior:

For calls to `CounterService.increment` to be treated as counters by `StatsdMetricWriter`.

Actual behavior:

Calls to `CounterService.increment` are treated as gauges by `StatsdMetricWriter`.

To reproduce:

* Run the following Spring Boot application: https://github.com/56quarters/metrics-demo
* Start netcat on port 8125, UDP: `netcat -u -l -p 8125`
* Hit the index page of the application: `curl 'http://localhost:8080/'`
* Observe the output from the terminal where you started netcat,
  * *Instead* of something containing `my.demo.app.counter.myMetric.happened:1|c` -- **correct**
  * You'll see something containing `my.demo.app.counter.myMetric.happened:1|g` -- **incorrect**

Per the Statsd documentation, you can see that counters should have `c` at the end: https://github.com/etsy/statsd/blob/master/docs/metric_types.md

I've poked around the code and this seems to be related to the use of the BufferedCounterService and BufferedMetricReader. When the buffers are flushed via an `Exporter`, the `StatsdMetricWriter.set` method is called which does not have a special case for metrics starting with `counter.`. Let me know if there's any other information you need.

Thanks!

**Comment by snicoll** [comment]
Wow, thanks for the detailed analysis, much appreciated!

**Comment by snicoll** [comment]
looking at the code for `StatsdMetricWriter`, there is a check for counters but we treat that as a gauge that we reset. Seems weird to me, ping @dsyer

**Comment by dsyer** [comment]
I think the metric exporter is stateless so it can't map a Spring Boot counter accurately to an external counter. I suppose that could change, but it would be quite a big change.
