### ISSUE TITLE
Update MariaDB Dialect to 10.4.0 or later

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-boot#43056]
Spring-Boot 3.3.5

When adding `mariadb-java-client` as dependency, a warning is shown that the dialect should be upgraded:
```
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
		</dependency>
```

```
2024-11-07T08:26:34.086+01:00  WARN 312520 --- [demo] [           main] org.hibernate.dialect.Dialect            : HHH000511:
 The 8.0.39 version for [org.hibernate.dialect.MariaDBDialect] is no longer supported, hence certain features may not 
 work properly. The minimum supported version is 10.4.0. Check the community dialects project or available legacy versions.
```

I would assume this is a todo inside the boot framework. If not, please give a hint how users should solve the issue.

[demo.zip](https://github.com/user-attachments/files/17657694/demo.zip)

**Comment by wilkinsona** [comment]
This warning from Hibernate is indicating that the version of MariaDB that you're using is version 8.0.39 and that `org.hibernate.dialect.MariaDBDialect` now requires 10.4.0 or later. As such it's out of Boot's control. To address the warning you have two options:

1. Upgrade Maria DB to 10.4.0 or later
2. Switch to a community or legacy dialect that supports Maria DB 8.0.39, should such a dialect exist
