### ISSUE TITLE
Autoconfigure settings such as timeouts and redirects for RestClient and RestTemplate and WebClient

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#43068]
We should introduce a `@ConfigurationProperties` bean for `[RestClient|RestTemplate|WebClient]AutoConfiguration`.

```java
@ConfigurationProperties("spring.http.client")
public class HttpClientProperties {

	private Duration connectTimeout = Duration.ofSeconds(5);

	private Duration readTimeout = Duration.ofSeconds(30);

	private Redirects redirects = Redirects.FOLLOW_WHEN_POSSIBLE;

	private Class<? extends ClientHttpRequestFactory> requestFactoryType = JdkClientHttpRequestFactory.class;

	...

}

```

**Comment by quaff** [comment]
I would like to prepare an PR if the team accepts the proposal.

**Comment by wilkinsona** [comment]
Apologies if I have have misunderstood the proposal, but don't we [already have this](https://github.com/spring-projects/spring-boot/blob/8b6c80d7305c73fc699ad0f026a99fb2ecd5be3e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/client/HttpClientProperties.java)?

**Comment by quaff** [comment]
My apologies, I didn't notice that.

**Comment by quaff** [comment]
But I think we should specify sensible default timeout, “Infinity” is a very bad default timeout.

**Comment by wilkinsona** [comment]
I don't it is infinity, at least not in all cases as it depends on the underlying client. For example, the Apache HTTP client has default connect and read timeouts of 3 minutes. Generally speaking, we prefer to keep each client's defaults as any differences may part of the reason why someone has chosen a particular client. Redirects are an exception to this as we wanted the upgrade experience to be as smooth as possible.
