### ISSUE TITLE
OAuth2AuthorizationServerConfiguration does not use all properties from BaseClientDetails

### ISSUE THREAD

**Issue by klieber** [spring-projects/spring-boot#4306]
Just trying out `1.3.0.RC1` and attempted to configure OAuth2 AuthorizationServer using the new `security.oauth2.client.*` properties in `application.properties` and noticed not all of them were being picked up. The `OAuth2AuthorizationServerConfiguration` auto configuration is ignoring the `autoApproveScopes`, `accessTokenValiditySeconds`, and `refreshTokenValiditySeconds` properties from `BaseClientDetails`.

**Comment by snicoll** [comment]
What does ignoring mean exactly? Not being set in `BaseClientDetails` or the code not using the value. Can you show your configuration and what you expect to happen?

**Comment by klieber** [comment]
@snicoll I mean that the code in the `OAuth2AuthorizationServerConfiguration#configure` method is not using their values.  I've created a pull request that should fix it. See #4316.
