### ISSUE TITLE
JdkClientHttpRequestFactoryBuilder and JettyClientHttpRequestFactoryBuilder do not set Ciphers or Enabled Protocols

### ISSUE THREAD

**Issue by matthew-js-porter** [spring-projects/spring-boot#43077]
[JdkClientHttpRequestFactoryBuilder](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/http/client/JdkClientHttpRequestFactoryBuilder.java#L92) does not set ciphers or enabled protocols from the SslBundle. See: [JdkClientHttpConnectorFactory ](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/function/client/JdkClientHttpConnectorFactory.java#L42-L44)

**Comment by philwebb** [comment]
`JettyClientHttpRequestFactoryBuilder` also has the same issue.
