### ISSUE TITLE
spring-boot-parent missing outputDirectory.

### ISSUE THREAD

**Issue by neblina-software** [spring-projects/spring-boot#4307]
The problem is, spring boot is not creating and copying *.properties files from resources to target/ folder.

It only creates when execute:

> $ mvn test # check target/classes folder

and not when executing:

> $ mvn spring-boot:run -P prod # check target/classes/ all .properties files will be deleted

Note: Using YAML format will be display a stack trace.

Testing copy resources:

/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java "-Dmaven.home=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.5 org.apache.maven.plugins:maven-resources-plugin:2.6:copy-resources -P prod,dev
[INFO] Scanning for projects...
[INFO]

[INFO] ------------------------------------------------------------------------
[INFO] Building balero 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (default-cli) @ balero ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.151s
[INFO] Finished at: Mon Oct 26 11:16:35 CST 2015
[INFO] Final Memory: 6M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:copy-resources (default-cli) on project balero: The parameters 'resources', 'outputDirectory' for goal org.apache.maven.plugins:maven-resources-plugin:2.6:copy-resources are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

**'outputDirectory' is missing**.

Note: Looks like this issue appears in Java 8, im using Java 8, tell me if i'm wrong.

So, using:

pom.xml
< properties >
                < db.user>root</db.user >
< /properties >

application.properties:
username: @db.user@

@db.user@ always be null.

I'm declaring fromPom.user in pom.xml "prod" profile, and passing it to application.properties test.pro=@fromPom.user@, fromPomuser will be null.

i'm trying to create a template property file:

var1=@var1@
var2=@var2@

im using with:

https://github.com/neblina-software/balerocms-enterprise

Looks like < outputDirectory >< /outDirectory > is missing in the configuration.

**Comment by snicoll** [comment]
In 1.2, `spring-boot:run` enables the `addResources` parameter by default that puts  `src/main/resources` on your classpath to allow static resources to be refreshed if you modify them. To avoid duplicates resources, the plugin removes any files present in both `src/main/resources` and `target/classes`. 

We believed this to be quite nasty so we have disabled that in 1.3. You can do so as well [as explained in the documentation](http://docs.spring.io/spring-boot/docs/1.2.7.RELEASE/maven-plugin/usage.html)
