### ISSUE TITLE
Devtools reload regression between (1.3.0.M5 and 1.3.0.RC1)

### ISSUE THREAD

**Issue by tonyghita** [spring-projects/spring-boot#4308]
When upgrading to 1.3.0.M5 to 1.3.0.RC1, devtools no longer reboots the application when a file one of the watched folders changes.

Specifically, I am changing files in `src/main/resources/static`.

**Comment by snicoll** [comment]
Devtools never rebooted the app when something changes in `static`. I guess you meant that the app does not refresh anymore.

We would probably need a bit more info. Do you run your app with `spring-boot:run` or  `bootRun`? If so you were probably relying on the `addResources` attribute that has been disabled in RC1. Please [check the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-RC1-Release-Notes#maven-spring-bootrun-and-gradlew-bootrun-resources).

If that's not what you are experiencing, you'll need to provide more details. A scenario that reproduces the problem would really help.

**Comment by tonyghita** [comment]
@snicoll yes I believe `addResources` is exactly what I was relying on. I start my app with `bootRun` when developing.

From the release notes:
> If you want live, in-place editing we recommend using Devtools.

Thank you for the response :)

**Comment by snicoll** [comment]
Thanks for the feedback :+1:

**Comment by tonyghita** [comment]
If anyone should also see this and want the functionality, the relevant docs are here: http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#build-tool-plugins-gradle-running-applications
