### ISSUE TITLE
Dependency management brings an invalid combination of HttpCore5 and HttpClient5

### ISSUE THREAD

**Issue by donguseo** [spring-projects/spring-boot#43113]
I use spring boot 3.3.3. 
There is a dependency problem in spring boot 3.3.3.

<img width="976" alt="image" src="https://github.com/user-attachments/assets/72ab3018-ae59-4950-b39f-1aaa62f82ee8">

And I think https://github.com/spring-projects/spring-boot/issues/41374 update may casue this problem. 

```
import org.apache.hc.client5.http.classic.HttpClient
import org.apache.hc.client5.http.config.ConnectionConfig
import org.apache.hc.client5.http.config.RequestConfig
import org.apache.hc.client5.http.impl.classic.HttpClientBuilder
import org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager
import org.apache.hc.core5.util.Timeout

class HttpClient5ClientFactory {

  companion object {
    fun createHttpClient5Client(): HttpClient {
      val connectionManager = PoolingHttpClientConnectionManager()
      connectionManager.defaultMaxPerRoute = 100
      connectionManager.maxTotal = 100
      connectionManager.setDefaultConnectionConfig(
        ConnectionConfig.custom()
          .setConnectTimeout(Timeout.ofSeconds(1))
          .build()
      )
      val requestConfig = RequestConfig.custom()
        .setResponseTimeout(Timeout.ofSeconds(5))
        .build()

      val httpClientBuilder = HttpClientBuilder.create()
        .useSystemProperties()
        .setConnectionManager(connectionManager)
        .setDefaultRequestConfig(requestConfig)

      val httpClient = httpClientBuilder.build()
      return httpClient
    }
  }
}
```

**Comment by snicoll** [comment]
Thanks for the sample. Looking at what makes it work based on your description, force downgrading HttpCore5 to `5.2.4`, makes the error go away. I've added this to your build:

```
extra["httpcore5.version"] = "5.2.4"
```

However, I am not sure what the error comes from. Yes the IDE shows an error for me as well but compilation works. Looking at the [changelog between 5.2.4 and 5.2.5](https://github.com/apache/httpcomponents-core/compare/rel/v5.2.4...rel/v5.2.5) I don't see a change that would lead to this problem. At this point, it looks like an error in the IDE.

@donguseo can you make the sample actually fail outside of the IDE? Something like compilation that does not work or an error at runtime?

**Comment by snicoll** [comment]
The IDE does not show an error for the same code written in Java.

@sdeleuze does that ring any bell?

**Comment by donguseo** [comment]
@snicoll 
Thank you. Applying it as you described removed the error I mentioned. It seems this resolves the issue I was facing.

Outside of the IDE, there were no problems. The code compiled well, and the functionality worked as expected. Since it’s still in development, I haven't seen any issues in the production environment.

I also checked the changes in httpcore5’s code, and nothing stood out as a significant problem. If you find out why this issue occurred, I’d appreciate any additional comments.

**Comment by snicoll** [comment]
@donguseo alright, thanks for confirming. Please report this issue to https://youtrack.jetbrains.com/issues. I am going to close this one but feel free to add a link to the issue you've created so that we can follow along.
