### ISSUE TITLE
Add withDefaultRequestConfigCustomizer method to HttpComponentsClientHttpRequestFactoryBuilder

### ISSUE THREAD

**Issue by oyvindhorneland** [spring-projects/spring-boot#43139]
Apache HttpClient 5.4.x (in upcoming Spring Boot 3.4) has by default enabled HTTP/1.1 TLS Upgrade in https://github.com/apache/httpcomponents-client/pull/542. This causes an issue for k8s deployments using Istio service mesh (and Envoy proxies) as described in https://github.com/istio/istio/issues/53239 where outbound http requests will receive a HTTP status 403 with "upgrade_failed".

The issue has been reported to the Apache project in https://issues.apache.org/jira/browse/HTTPCLIENT-2344, where it has been closed as invalid since they believe Envoy is not behaving correctly. 

The issue has been reported to Envoy in https://github.com/envoyproxy/envoy/issues/36305 where discussions are ongoing.

Note that the protocol upgrade is only enabled for OPTIONS, HEAD and GET requests and clients may therefore observe that some requests work and others don't (Envoy will block the ones containing the TLS upgrade headers).

Code based workaround is to change protocolUpgradeEnabled to false when creating the HttpClient's RequestConfig.

```java
        RequestConfig requestConfig = RequestConfig.custom()
                // ...
                .setProtocolUpgradeEnabled(false)
                .build();
        HttpClient httpClient = HttpClientBuilder.create()
                // ...
                .setDefaultRequestConfig(requestConfig)
                .build();
```

There is currently no system property in Apache HttpClient5 to disable protocolUpgradeEnable.

Should this known issue and possible workarounds be listed in the migration guide? 

Not sure if a configuration option is a good possibility here, but `HttpComponentsClientHttpRequestFactory` will currently by default try to use `HttpClients.createSystem()` with protocolUpgrade enabled by default.

**Comment by nosan** [comment]
A possible workaround is configuring your own `ClientHttpRequestFactoryBuilder`:


```java
@Bean
public HttpComponentsClientHttpRequestFactoryBuilder httpComponentsClientHttpRequestFactoryBuilder() {
	return ClientHttpRequestFactoryBuilder.httpComponents()
			.withHttpClientCustomizer(disableProtocolUpgrade());
}

private static Consumer<HttpClientBuilder> disableProtocolUpgrade() {
	return (customizer) -> customizer.setDefaultRequestConfig(RequestConfig.custom()
			.setProtocolUpgradeEnabled(false)
			.build());
}

```

**Comment by nosan** [comment]
> if it affects all autoconfigured HttpClient instances.

The `ClientHttpRequestFactoryBuilder` is used by `RestClientAutoConfiguration`, `RestTemplateAutoConfiguration`, and `WebServiceTemplateAutoConfiguration`.

**Comment by philwebb** [comment]
I think we should probably align with whatever defaults HttpClient provides. That's generally the rule that we try to follow. It's not ideal that there's a mismatch between what the HttpClient and Envoy maintainers consider sensible default behavior.

I'm not too keen to add a configuration property for this because we don't currently have any client specific properties. It would need to be something like `spring.http.client.httpcomponents.protocol.upgrade.enabled=false`. That then opens the door for a whole bunch of other properties being requested.

I do think we can make https://github.com/spring-projects/spring-boot/issues/43139#issuecomment-2473848564 a little easier to apply if we tweak our code. Something like:

```java
@Bean
public HttpComponentsClientHttpRequestFactoryBuilder httpComponentsClientHttpRequestFactoryBuilder() {
	return ClientHttpRequestFactoryBuilder.httpComponents()
			.withDefaultRequestConfigManagerCustomizer((builder) -> builder.setProtocolUpgradeEnabled(false));
```

I think we might have to do that as a first step and see what happens with https://issues.apache.org/jira/browse/HTTPCLIENT-2344 and https://github.com/envoyproxy/envoy/issues/36305

**Comment by nosan** [comment]
Thanks @philwebb 

Would it make sense to add a note in the migration guide as well, if feasible?

**Comment by philwebb** [comment]
Good idea, I'll do that as well.

**Comment by rafalh** [comment]
Where did the "manager" word came from in `withDefaultRequestConfigManagerCustomizer`? I think it would be nicer to have it named `withDefaultRequestConfigCustomizer`?

**Comment by nosan** [comment]
@philwebb  😄 

```java
	public HttpComponentsClientHttpRequestFactoryBuilder withDefaultRequestConfigCustomizer(
			Consumer<RequestConfig.Builder> **defaultRequestConfigManagerCustomizer**) {
		Assert.notNull(**defaultRequestConfigManagerCustomizer**,
				"'**defaultRequestConfigManagerCustomizer**' must not be null");
```

**Comment by philwebb** [comment]
This issue is cursed 😂

**Comment by rafalh** [comment]
@philwebb It's definitely cursed :P You forgot to update [Spring Boot 3.4 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes). It still references `withDefaultRequestConfigManagerCustomizer`

**Comment by wilkinsona** [comment]
Thanks, @rafalh. I've updated the release notes.
