### ISSUE TITLE
Complex types are not combined correctly from merging propery sources

### ISSUE THREAD

**Issue by irozzo** [spring-projects/spring-boot#4313]
I'm using the [externalized configuration](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) feature provided Spring Boot 1.2.5-RELEASES and when trying to upgrade to version 1.2.7-RELEASES I was surprised to see that the strategy to merge properties coming from different sources changed.

I found that the culprit is [this](https://github.com/spring-projects/spring-boot/commit/86d5c1925916043ca69da3e3443baf5b1ae4f8ad) commit, which fixes issue https://github.com/spring-projects/spring-boot/issues/2611 .

I think that the new approach is not really straightforward and consistent. Let's consider the following scenarios:

### Property source A
```
list[0]=f0
```
### Property source B
```
list[0]=s0
list[1]=s1
```
### Merged properties after fix
```
list[0]=f0
```
### Merged properties before fix
```
list[0]=f0
list[1]=s1
```
The claim is that it is more logical not to mix lists, according to me it is debatable but it can make sense. Now let's consider a slightly more complex example:

### Property source A
```
list[0].a=f0
```
### Property source B
```
list[0].a=s0
list[0].b=s1
list[1].a=s2
list[1].b=s3
```
### Merged properties after fix
```
list[0].a=f0
list[0].b=s1
list[1].b=s3
```
### Merged properties before fix
```
list[0].a=f0
list[0].b=s1
list[1].a=s2
list[1].b=s3
```
In this scenario the data is more structured. The result in this case is not really intuitive after the fix.

### Property source A
```
list[0].a=f0
list[1].b=f1
```
### Property source B
```
list[0].a=s0
list[0].b=s1
list[1].a=s2
list[1].b=s3
```
### Merged properties after fix
```
list[0].a=f0
list[1].b=f1
```
### Merged properties before fix
```
list[0].a=f0
list[0].b=s1
list[1].a=s2
list[1].b=f1
```
Again result is counter intuitive.

To conclude I think that current merge policy could be acceptable in case of flat data, but definitely not good in case of more structured one.

**Comment by irozzo** [comment]
What does *documentation* tag mean? There is no fix previewed?

**Comment by irozzo** [comment]
Sorry for being pushy, but could you please give me an update regarding how do you intend to address this issue? We are having troubles related to it. 
Consider [my PR](https://github.com/irozzo/spring-boot/commit/3894b57b4e5bd334fac015fdbb670631d9f5e5d6) I proposed a very simple solution that makes the merge more consistent in the different scenarios.

**Comment by wilkinsona** [comment]
Our intention is to document the current behaviour

**Comment by irozzo** [comment]
@wilkinsona  @philwebb  Ok, and how do you plan to explain Scenario 2 referring to my examples? Why the property *a* of the second list element disappears while property *b* remains in the merged properties? Consider that logically properties *a* and *b* belong to the same list element.

It is more evident with yaml that is structured by nature:

### application.yml
```
items:
    - mandatory_property: s0
      optional_property: a
    - mandatory_property: s1
      optional_property: b
```
### application-{profile}.yml
```
items:
    - mandatory_property: f0
```
### Merged result
```
items:
    - mandatory_property: f0
      optional_property: a
    - optional_property: b
```
I do not understand the logic, to me this does not make sense. 

If you try to use this in conjunction with **@ConfigurationProperties** you end up in a very unexpected results. If for instance you use [bean validation](http://beanvalidation.org/) to ensure that the mandatory property is not null for each of the items the validation fails, even if both configuration files are perfectly valid.

**Comment by snicoll** [comment]
While writing the documentation for this, I've found a bug with regards to collection exclusion for structured data. Gathering a test case now.
