### ISSUE TITLE
Remove deprecated method call to getFiles() in CheckBom

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#43142]
There's this code:

```
Set<File> files = this.configurations.detachedConfiguration(this.dependencies.create(coordinates))
  .getResolvedConfiguration()
  .getFiles();
```

`.getFiles()` is deprecated.

It doesn't fail the build, but displays a warning.

**Comment by wickdynex** [comment]
> There's this code:
> 
> ```
> Set<File> files = this.configurations.detachedConfiguration(this.dependencies.create(coordinates))
>   .getResolvedConfiguration()
>   .getFiles();
> ```
> 
> `.getFiles()` is deprecated.
> 
> It doesn't fail the build, but displays a warning.

Could you please assign this issue to me🥺? I'll try to fix it as soon as possible🥰.

**Comment by wickdynex** [comment]
One question: which branch need I work on and merge?🤔 Is on `3.2.x branch` and merge to it?

**Comment by mhalbritter** [comment]
Yes, 3.2.x is the base branch for this. You can also work on `main` and we do the rebasing. Directly working on `3.2.x` and create the PR to target `3.2.x` as base branch makes work easier for us, though :)

**Comment by wickdynex** [comment]
> Yes, 3.2.x is the base branch for this. You can also work on `main` and we do the rebasing. Directly working on `3.2.x` and create the PR to target `3.2.x` as base branch makes work easier for us, though :)

<3 Thanks for ur replying🥰, I'll try to fix it.❤️

**Comment by philwebb** [comment]
Closing in favor of PR #43191. Thanks @wickdynex!

**Comment by wickdynex** [comment]
> Closing in favor of PR #43191. Thanks @wickdynex!

It's my pleasure to join in this extraordinary project, thanks for your appreciate🥰.
