### ISSUE TITLE
logging.path and logging.file ignored when provided via Spring Cloud Config

### ISSUE THREAD

**Issue by kemitix** [spring-projects/spring-boot#4315]
Both `logging.path` and `logging.file` are silently ignored if provided via a Spring Cloud Config server. Are they required earlier in the bootstrap than when received from the server?

**Comment by spencergibb** [comment]
This should probably go in [spring-cloud-commons](https://github.com/spring-cloud/spring-cloud-commons) or [spring-cloud-config](https://github.com/spring-cloud/spring-cloud-config).

**Comment by wilkinsona** [comment]
That's really a Spring Cloud question as it controls when the the configuration is read from the config server. Spring Boot uses the `logging.path` and `logging.file` properties in `LoggingApplicationListener` in response to an `ApplicationEnvironmentPreparedEvent`. `LoggingApplicationListener` has an order of `HIGHEST_PRECEDENCE + 20`.

**Comment by kemitix** [comment]
Thanks. And it looks like they already have a fix. https://github.com/spring-projects/spring-boot/issues/4315
