### ISSUE TITLE
Incorrect Type for 'management.endpoints.access.default' defined in additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by matthew-js-porter** [spring-projects/spring-boot#43154]
The Type is listed as `Boolean` for the new `management.endpoints.access.default` actuator property in [additional-spring-configuration-metadata.json](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L62), but should be [Access](https://github.com/spring-projects/spring-boot/blob/87cf12a36cc41bd35b4d3bbdc3b84d63d1031ed8/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Access.java).

**Comment by philwebb** [comment]
Good spot!
