### ISSUE TITLE
Remove prohibited undertow upgrade restriction

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#43169]
Assuming https://github.com/spring-projects/spring-framework/issues/33885 is backported, we can remove the restriction.

**Comment by wickdynex** [comment]
> Assuming [spring-projects/spring-framework#33885](https://github.com/spring-projects/spring-framework/issues/33885) is backported, we can remove the restriction.

Does it means we need to wait for the feedback on the change from `Spring 6.2`? And remove the restriction until we confirm it has no defect?🤔 So we can't remove the prohibited restriction right now?

Is this task difficult? It seems that I need to modify the `build.gradle` dependency and run `regression test`, if there's some mistake, I need to refactor the code to adapt to new version. Im I right?🥺Plz give some advices.

**Comment by philwebb** [comment]
@wickdynex This one is easier for one the team to deal with directly. We can't do anything until the next set of release are out.

**Comment by wickdynex** [comment]
> @wickdynex This one is easier for one the team to deal with directly. We can't do anything until the next set of release are out.

Okey, thanks for your reply.🥺

**Comment by snicoll** [comment]
Closing in favor of PR #43333
