### ISSUE TITLE
Add info contributor support for JDK 24's VirtualThreadSchedulerMXBean

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#43175]
![image](https://github.com/user-attachments/assets/1f0aaef5-2f4c-4018-9f3a-18aab5d18131)

Maybe we can fit these information into the existing `ProcessInfo`.

**Comment by panic08** [comment]
I am very interested in this issue and would like to ask a couple questions.

1. Do I understand correctly that we want to put such fields into ProcessInfo in this form?

```
private final Long mountedVirtualThreadCount;

private final Long queuedVirtualThreadCount;

private final Integer parallelism;

private final Integer poolSize;
```

2. Am I right that we should use reflection to work safely with VirtualThreadSchedulerMXBean since it is jdk 24? Use something like

```
@SuppressWarnings(“unchecked”)
Class<? extends PlatformManagedObject> clazz = (Class<? extends PlatformManagedObject>)
	Class.forName(“jdk.management.VirtualThreadSchedulerMXBean”);

Object mxBean = ManagementFactory.getPlatformMXBean(clazz);
```

and then also call methods to get the fields we need

**Comment by mhalbritter** [comment]
Hello,

I'd add a new field to `ProcessInfo`: `private final VirtualThreads virtualThreads;`. This field could be `null` if running on Java < 24.

```java
public static class VirtualThreads {

    private final long mounted;

    private final long queued;

    private final int parallelism;

    private final int poolSize;

}
```

> 2. Am I right that we should use reflection to work safely with VirtualThreadSchedulerMXBean since it is jdk 24?

Yes. Another option would be a multi-release JAR, but I don't think we have the infrastructure for that in place. I'd go for reflection here.

**Comment by panic08** [comment]
> Should I assign you to the issue?

Yeah, that'd be cool

**Comment by philwebb** [comment]
Closing in favor of PR #43594. Thanks @panic08!
