### ISSUE TITLE
Add TaskDecorator support for scheduled tasks

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#43173]
Spring Framework has added `TaskDecorator` support in https://github.com/spring-projects/spring-framework/issues/23755.

Right now, we auto-configure `TaskDecorator` for task execution, but not for task scheduling. I think we should also support `TaskDecorator` beans for task scheduling.

**Comment by snicoll** [comment]
Closing in favor of PR #43190
