### ISSUE TITLE
Disable ApplicationContextHeaderFilter if possible

### ISSUE THREAD

**Issue by bohrqiu** [spring-projects/spring-boot#4320]
if  set `org.springframework.boot.actuate.autoconfigure.ManagementServerProperties#addApplicationContextHeader` true ,`ApplicationContextHeaderFilter` still be executed,why not disable register it?

**Comment by snicoll** [comment]
I guess you meant `false`, right?

**Comment by bohrqiu** [comment]
oh.yes, just typo

**Comment by bohrqiu** [comment]
oh.yes, just typo

**Comment by cemo** [comment]
+1
