### ISSUE TITLE
Using Environment post processor to remove spring.jpa.database-platform doesn't work the JPAproperties always have  spring.jpa.database-platform pouplated 

### ISSUE THREAD

**Issue by anand188** [spring-projects/spring-boot#43227]
BUG : 3.1.3 version spring boot 
Using Environment post processor to remove spring.jpa.database-platform doesn't work the 
JPAproperties always have  spring.jpa.database-platform populated 

As part of Hibernate 6  the old dialects are removed and to handle this automatically the above property is removed and database property is set default so auto dialect detection works.

**Comment by wilkinsona** [comment]
Spring Boot 3.1.x is [no longer supported](https://spring.io/projects/spring-boot#support). Please upgrade to a supported version. If the problem still occurs and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem with a supported version. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by anand188** [comment]
@nosan  thanks for the project the one mistake in mine is used addLast after changing it to addFirst as in the project attached my bad should have gone through each method and use which one overrides .Anyway great thanks and for quick reply
