### ISSUE TITLE
Documentation: Logback configuration snippet wrong.

### ISSUE THREAD

**Issue by Mettbrot** [spring-projects/spring-boot#43244]
The documentation for configuring logback with spring boot defaults has a typo:

https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/howto-logging.html#howto-configure-logback-for-logging

The correct XML is `defaultS.xml`.

**Comment by nosan** [comment]
@Mettbrot 
It has already been fixed.
https://docs.spring.io/spring-boot/how-to/logging.html#howto.logging.logback

**Comment by Mettbrot** [comment]
The real question would be: Why do I land on the docu for 2.1.8 when I google something like https://www.google.com/search?client=firefox-b-e&q=spring+boot+logging+config+logback

Is there anything we can do about that?

**Comment by wilkinsona** [comment]
Not much, unfortunately. The new docs should improve search engine rankings and it does appear to be having an effect. For example, https://docs.spring.io/spring-boot/how-to/logging.html is the second result for me with Google and the first result with DuckDuckGo.
