### ISSUE TITLE
Testcontainers start() methods may be started multiple times

### ISSUE THREAD

**Issue by marcantoine-bibeau** [spring-projects/spring-boot#43253]
ContainerConnectionDetailsFactory.getContainer() is doing 
```
if (this.container instanceof Startable startable) {
				startable.start();
			}
```

While ```TestcontainersLifecycleBeanPostProcessor.initializeStartables(...)``` already started the MockServer

**Comment by philwebb** [comment]
Is this causing an issue? Can you provide a sample application showing the actual problem you're facing?

**Comment by marcantoine-bibeau** [comment]
I do not think it creates a big problem but still created a regression on my side because I'm wrapping the MockServer and override the start() method to perform additional stuff. I can fix by verifying if the TestContainer is running but would be ideal to not start twice?

**Comment by snicoll** [comment]
Can you please share the sample we've requested? See also https://github.com/spring-projects/spring-boot/wiki/How-To-Get-Help

**Comment by wilkinsona** [comment]
We could perhaps use a non-null response from `ContainerState#getContainerId()` to determine that a container's already been started (as `ContainerState#getMappedPort(int)` does) but that won't work for every `Startable` implementation. Given this, it appears to be impossible for us to tell with 100% certainty if a container's already been started. @marcantoine-bibeau, I'd encourage you to implement `start()` such that it is idempotent as it is in `GenericContainer`.

**Comment by nosan** [comment]
@wilkinsona 
Is it possible to add the following condition?

```java
protected final C getContainer() {
	Assert.state(this.container != null,
			"Container cannot be obtained before the connection details bean has been initialized");
	if (!this.container.isRunning() && this.container instanceof Startable startable) {
		startable.start();
	}
	return this.container;
}
```

**Comment by philwebb** [comment]
I spent a fair bit of time looking at this today and I don't think tracking beans will work. The problem is that the container may have been started by `org.testcontainers.junit.jupiter.TestcontainersExtension` and there's no way for us to track that.
