### ISSUE TITLE
Searching current docs links to snapshot docs

### ISSUE THREAD

**Issue by ciscoo** [spring-projects/spring-boot#43252]
May or may not be a Spring Boot issue or the custom Antora setup.

When searching, you can see the bottom left links to the next snapshot docs, but I'm browsing current docs so I expect current docs link.

![Untitled](https://github.com/user-attachments/assets/d2ca96cf-6a65-4a76-a426-d2e93855d32c)

**Comment by philwebb** [comment]
It'll take a little while for our search index to update. It should be fixed within 25 hours.
