### ISSUE TITLE
JmsListener failing with Narayana (pooled ConnectionFactory) since 3.4.0

### ISSUE THREAD

**Issue by graben** [spring-projects/spring-boot#43277]
The unwrapping code introduced with [commit](https://github.com/spring-projects/spring-boot/commit/fc2890d1cd8306c77f8644b5ecc20a92df8422cd) into `JmsAnnotationDrivenConfiguration` is causing issue with Narayana integration if using pooled ConnectionFactory because it unwraps the integration "magic" away.

Reproduce with attached demo. Btw. Narayana integration from https://github.com/snowdrop/narayana-spring-boot needs to be rebuilt as SNAPSHOT because latest 3.3.0 version is not build compatible with Spring Boot 3.4.0. (snowdrop/narayana-spring-boot#172)

[demo.zip](https://github.com/user-attachments/files/17894310/demo.zip)

FYI @snicoll

**Comment by snicoll** [comment]
Thanks for the sample, see also #39816. 

>  is causing issue with Narayana 

What does that mean? How do I reproduce the problem with the sample you've shared and what is the problem. I've tried to run the application and didn't see a problem except an exception on shutdown that can happen unfortunately with ActiveMQ.

**Comment by graben** [comment]
@snicoll: Thanks for the workaround. Work for me, too! ;-)
