### ISSUE TITLE
3.4 @MockBean to @MockitoBean Not Behaving The Same - Cross Post of "Support @MockitoBean on @Configuration classes #33934"

### ISSUE THREAD

**Issue by adase11** [spring-projects/spring-boot#43282]
This is a cross post of https://github.com/spring-projects/spring-framework/issues/33934 - I think it's useful to mention here. 

I believe most people will run into this issue for the first time when upgrading to Spring Boot 3.4. 

At a high level `@MockitoBean` is no longer behaving the same as `@MockBean` was when used in tests. 

The examples in https://github.com/spring-projects/spring-framework/issues/33934 as well as my experience are specifically referencing `@WebMvcTest` (which is from Spring Boot and why I think this should be brought up here). 

Shout out to @tobias-lippert for the initial post with a solid example.

<hr> 

Ideally `@MockitoBean` would be a drop-in replacement for `@MockBean`  and those test-specific configuration classes would continue to work. Alternatively I think it would be useful to document the need to move those `@MockitoBean` declarations to the test class itself.

**Comment by wilkinsona** [comment]
I've added [a section to the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#deprecation-of-mockbean-and-spybean). Beyond that, constructive feedback should be provided in the Spring Framework issue tracker as that's where any changes will be considered and potentially made.

**Comment by adase11** [comment]
Thanks!
