### ISSUE TITLE
Spring Boot 3.4.0 - Multiple ObjectPostProcessor<ReactiveAuthenticationManager> when a single one is expected

### ISSUE THREAD

**Issue by joaodias14** [spring-projects/spring-boot#43281]
While migrating to the new Spring Boot 3.4 version I am facing the following error in a project with RSocket, Spring Security and Spring Webflux:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setAuthenticationManagerPostProcessor in org.springframework.security.config.annotation.web.reactive.ServerHttpSecurityConfiguration required a single bean, but 2 were found:
	- authenticationManagerPostProcessor: defined by method 'authenticationManagerPostProcessor' in class path resource [org/springframework/security/config/annotation/web/reactive/ReactiveObservationConfiguration.class]
	- rSocketAuthenticationManagerPostProcessor: defined by method 'rSocketAuthenticationManagerPostProcessor' in class path resource [org/springframework/security/config/annotation/rsocket/ReactiveObservationConfiguration.class]

This may be due to missing parameter name information

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

I was able to reproduce this in a simple project which you can find at https://github.com/joaodias14/Spring-Boot-RSocket. I simply used https://start.spring.io/ with Spring Boot 3.4.0 and RSocket, Spring Reactive Web and Spring Security as dependencies. If I run it with `./mvnw -o spring-boot:run` I get the error above.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, I don’t think there’s anything we can do about this in Spring Boot as both beans are defined in Spring Security configuration classes. Please open a [Spring Security](https://githib.com/spring-projects/spring-security) issue so that they can investigate.

**Comment by joaodias14** [comment]
Sure, will do. Thanks!
