### ISSUE TITLE
Methods to build producer / consumer properties from KafkaProperties are inconvienenent to use without an SSL bundle

### ISSUE THREAD

**Issue by kitkars** [spring-projects/spring-boot#43300]
This request is related to [39144](https://github.com/spring-projects/spring-boot/issues/39144).

We used to have below methods in the [KafkaProperties](https://github.com/spring-projects/spring-boot/blob/d8c41c2583bf5b5c17bf281715c5ae856a0e6ef6/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java) class.

```
buildProducerProperties()
buildConsumerProperties()
```

Looks like they have been removed / modified to accept **_SslBundles_** from 3.4.

```
buildProducerProperties(SslBundles sslBundles)
buildConsumerProperties(SslBundles sslBundles)
```

The Reactive Kafka Producer / Consumer Template classes have an option to accept the SenderOptions / ReceiverOptions as shown below. As the `buildConsumerProperties` requires `SslBundles` , I can pass null to make the code work as suggested in other thread. 

```
    @Bean
    public ReceiverOptions<String,MyEvent> receiverOptions(KafkaProperties kafkaProperties){
        return ReceiverOptions.<String, MyEvent>create(kafkaProperties.buildConsumerProperties(null))
                .consumerProperty(JsonDeserializer.REMOVE_TYPE_INFO_HEADERS, "false")
                .consumerProperty(JsonDeserializer.USE_TYPE_INFO_HEADERS, false)
                .consumerProperty(JsonDeserializer.VALUE_DEFAULT_TYPE, MyEvent.class)
                .subscription(List.of("my-events"));
    }

    @Bean
    public ReactiveKafkaConsumerTemplate<String, MyEvent> consumerTemplate(ReceiverOptions<String, MyEvent> options){
        return new ReactiveKafkaConsumerTemplate<>(options);
    }

```

However, It is really convenient to have simple below overloaded method as part of the **_KafkaProperties_** class itself which calls the appropriate methods with **_null_**.

```
buildProducerProperties()
buildConsumerProperties()
```

It would be great if you consider this request.

**Comment by philwebb** [comment]
We discussed this today, and although we don't consider these methods as public API having more convenient alternatives feels like something we can add. I'm considering this a "bug of omission" since it's so low risk to add to 3.3
