### ISSUE TITLE
AOT processing occurs when not requested

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#43317]
## Overview

If you create a new project via https://start.spring.io that includes GraalVM support (for example, like [this](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.4.0&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=boot-aot-bean-validation&name=boot-aot-bean-validation&description=Demo%20project%20for%20Spring%20Boot&packageName=example&dependencies=validation,native,data-jpa)), AOT processing occurs by default without the user requesting it.

I believe this behavior might be new in Spring Boot 3.4, and in any case I am wondering if it is intentional that AOT processing occurs for a _normal_ build or test run.

## Examples

- `./gradlew build -x test` executes the `processAot` Gradle task
- `./gradlew test` executes the `processTestAot` Gradle task

## Related Issues

- https://github.com/spring-projects/spring-framework/issues/33940

**Comment by snicoll** [comment]
> I believe this behavior might be new in Spring Boot 3.4

No, it isn't. It's been like that since the very beginning, see https://docs.spring.io/spring-boot/gradle-plugin/reacting.html#reacting-to-other-plugins.nbt
