### ISSUE TITLE
Use <annotationProcessorPaths> in Maven examples for configuring an annotation processor

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-boot#43329]
[JDK-8321319](https://bugs.openjdk.org/browse/JDK-8321319) will disable the automatic execution of annotation processors that are present on the classpath in Java 23+, because of [supply chain attack concerns](https://xdev.software/en/news/detail/discovering-the-perfect-java-supply-chain-attack-vector-and-how-it-got-fixed). 

This would for instance mean that just adding `spring-boot-configuration-processor` as a dependency won't do anything until the annotation processor in that artifact is explicitly allowed to run.

I think Spring Boot will need to respond to this change in one way or another, either by documenting how users can deal with this (e.g. `maven-compiler-plugin`'s `annotationProcessorPaths`, using `maven-processor-plugin`, or dropping this protection again by setting `-proc:full` while that's still available) or by configuring `javac` to execute Spring's (or all?) annotation processors automatically.

**Comment by breun** [comment]
Maybe Spring Boot could provide a default `<annotationProcessorPaths>` configuration for `maven-compiler-plugin` (maybe only activated when Java 23+ is used?) with all artifacts that are managed by Spring Boot and contain annotation processors?

That might still require documentation to explain how to allow _additional_ artifacts to execute their annotation processors, because a user specifying `<annotationProcessorPaths>` would override Spring Boot's default list of allowed artifacts. I think Maven's `combine.children="append"` could be used to let Spring Boot users allow additional artifacts.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think we should do that. Boot's annotation processors are currently an opt-in feature and I think that should remain the case. All that should change here is the recommended way to opt in when using Maven.

**Comment by cachescrubber** [comment]
I think besides the spring-boot documentation, start.spring.io would be an adequate place to generate a pom.xml with `maven-compiler-plugin`'s `annotationProcessorPaths` pre configured for the `spring-boot-configuration-processor`. The same would apply to Lombok, IMO.

**Comment by breun** [comment]
Configuring `<annotationProcessorPaths>` for `maven-compiler-plugin` looks like the easiest way to allow annotation processors, but it provides only artifact-level granularity and by default executes all annotation processors in the the artifact, as well as all annotation processors in transitive dependencies of the artifact. I guess that is why the [supply chain attack article](https://xdev.software/en/news/detail/discovering-the-perfect-java-supply-chain-attack-vector-and-how-it-got-fixed) that sparked this change recommends listing the explicitly listing the allowed annotation processors. The article provides an example based on `org.bsc.maven:maven-processor-plugin`, but I believe the same could be achieved via `<annotationProcessors>` with `maven-compiler-plugin`.
