### ISSUE TITLE
Bug: JDBC returning undefined/unknown database driver

### ISSUE THREAD

**Issue by NOF03** [spring-projects/spring-boot#43321]
Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 8.0.39
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
	
Only in the latest version 3.4.0 it is not reading the mysql specified version.

spring.datasource.url=jdbc:mysql://fiteverywhere-db:3306/fiteverywhere_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

**Comment by quaff** [comment]
It's handled by Hibernate not Spring Boot, and it's normal from Hibernate's perspective.

**Comment by wilkinsona** [comment]
Thanks, @quaff.

@NOF03 This logging occurs when Hibernate is configured to use an externally managed data source. It’s changed in Boot 3.4 due to a Hibernate upgrade. If you find it misleading or think that it could be improved, you may want to raise a Hibernate issue.

**Comment by dheerajmuppalla** [comment]
@NOF03 i am facing same issue can i know how you solved this problem??

**Comment by TauqeerSayeed** [comment]
@NOF03 How to solve this, even I am getting same while running. Please suggest

**Comment by yusuf7861** [comment]
is it mysql specific error.

**Comment by dheerajmuppalla** [comment]
Reinstalling mysql solves?

**Comment by Perumal1307** [comment]
Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
Database driver: undefined/unknown
Database version: 8.0.39
Autocommit mode: undefined/unknown
Isolation level: undefined/unknown
Minimum pool size: undefined/unknown
Maximum pool size: undefined/unknown


How to solve it

**Comment by Developer98-dev** [comment]
is there any solution for above?

**Comment by RutulTribhuwan** [comment]
Stuck with the same issue please help

**Comment by wilkinsona** [comment]
There's nothing that Spring Boot can do to help you here. As already explained [above](https://github.com/spring-projects/spring-boot/issues/43321#issuecomment-2507258543), this logging is produced by Hibernate and is out of Spring Boot's control. If you find it misleading or think that it could be improved, raise a Hibernate issue.

Please be considerate of people's time before commenting on an issue. Each notification that a comment generates consumes the community's time that could be spent elsewhere. We may have to lock this issue if further comments are made without reading and understanding the existing comments.

**Comment by mftakhullaziz** [comment]
I found the same issue, how do I fix that? can anyone tell me what should I do?
