### ISSUE TITLE
H2ConsoleAutoConfiguration causes early initialization of DataSource beans

### ISSUE THREAD

**Issue by AlbertoCortina** [spring-projects/spring-boot#43337]
### Context
I have an application (recently upgraded to Spring Boot 3.4.0) with two configured data sources, following a setup similar to the one described in [this Baeldung article](https://www.baeldung.com/spring-boot-configure-multiple-datasources).

Currently, I am using Testcontainers for integration tests, based on the approach outlined in [Spring Boot's documentation](https://docs.spring.io/spring-boot/reference/testing/testcontainers.html). These tests mock the second data source, and everything is working perfectly.

After a great initial experience using Testcontainers for testing, I decided to try it for local development. However, this is where I encountered some challenges.

### Problem

I followed the steps described in [Baeldung's article on Testcontainers support for local development](https://www.baeldung.com/spring-boot-built-in-testcontainers#testcontainers-support-for-local-development) and [Spring's blog post on improved Testcontainers support in Spring Boot 3.1](https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1#testcontainers-at-development-time).

Below are the classes involved:

```java
public interface OracleContainerConfiguration {

  @Container
  OracleContainer oracleContainer =
      new OracleContainer("gvenzl/oracle-free:slim-faststart")
          .withReuse(true);

  @DynamicPropertySource
  private static void configureProperties(DynamicPropertyRegistry registry) {
    registry.add("my-custom.datasource.url", oracleContainer::getJdbcUrl);
    registry.add("my-custom.datasource.username", oracleContainer::getUsername);
    registry.add("my-custom.datasource.password", oracleContainer::getPassword);
  }
}
```

```java
@TestConfiguration(proxyBeanMethods = false)
@ImportTestcontainers(OracleContainerConfiguration.class)
public class LocalDevelopmentContainersConfiguration {}
```

```java
public class MyApplicationWithContainer {

  public static void main(String[] args) {
    SpringApplication.from(MyApplication::main)
        .withAdditionalProfiles("integration-test-oracle")
        .with(LocalDevelopmentContainersConfiguration.class)
        .run(args);
  }
}
```
When running the application, I noticed that the data source configuration is executed **before** the `@DynamicPropertySource`, which results in the application picking up the properties defined in my application.yml.

In contrast, during an integration test, the behavior is reversed: the values from the `@DynamicPropertySource` are processed **first**, and only then is the data source configured.

Is this the expected behavior, or could it be a bug when using Testcontainers for local development?

Please let me know if anything is unclear.

Thank you very much!

**Comment by wilkinsona** [comment]
It's hard to say for sure what's happening as there are some parts of your app that you haven't shared. For example, we can't see how the `my-custom.datasource.*` properties are consumed. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by AlbertoCortina** [comment]
Hello @wilkinsona, thank you for looking into the issue.

While creating a minimal example to reproduce the error, I discovered that the cause of the problem was having the dependency `implementation("org.springframework.boot:spring-boot-devtools")` in my `build.gradle.kts`. After removing it, everything worked as expected.

I'm not sure if this behavior is intentional or not. If you'd like, I have a small project where the issue can be reproduced.

**Comment by wilkinsona** [comment]
Yes please, @AlbertoCortina.

**Comment by AlbertoCortina** [comment]
Here is the repository -> https://github.com/AlbertoCortina/demo-bug-testcontainers-dynamicpropertysource

To reproduce the error just try to run the application in the `test` folder, you will see that it goes first to the data source configuration classes and the to the `@DynamicPropertySource`.

Please let me know if you don't manage to reproduce the error

**Comment by philwebb** [comment]
Thanks for the sample, this appears to be because the `H2ConsoleAutoConfiguration` is triggering `DataSource` bean initialization from a `ServletRegistrationBean`. As a work around you can add the following to your `application.yml`:

```yaml
spring:
  h2:
    console:
      enabled: true
```

**Comment by quaff** [comment]
> Thanks for the sample, this appears to be because the `H2ConsoleAutoConfiguration` is triggering `DataSource` bean initialization from a `ServletRegistrationBean`. As a work around you can add the following to your `application.yml`:
> 
> ```yaml
> spring:
>   h2:
>     console:
>       enabled: true
> ```

It should be `false` to disable `H2ConsoleAutoConfiguration`, am I missing something?

**Comment by philwebb** [comment]
@quaff Thanks. Typo on my side.
