### ISSUE TITLE
Reference documentation incorrectly uses 'disabled' rather than 'none' for access restrictions

### ISSUE THREAD

**Issue by lincze** [spring-projects/spring-boot#43351]
i've installed spring boot 3.4.0, and tried to migrate to the new actuator configuration.

e.g. [according to the docs](https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.controlling-access):

```
management.endpoints.access.default=disabled
management.endpoint.loggers.access=read-only
```
(copy-pasted)

but when i use this, will get an exception:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [hu.f400.lifews.api.Application]: Error processing condition on org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration
...
Caused by: java.lang.IllegalArgumentException: No enum constant org.springframework.boot.actuate.endpoint.Access.disabled

```

and indeed, at [Access.java](spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Access.java) you see:

``` java
...
public enum Access {

	/**
	 * No access to the endpoint is permitted.
	 */
	NONE,

	/**
	 * Read-only access to the endpoint is permitted.
	 */
	READ_ONLY,

	/**
	 * Unrestricted access to the endpoint is permitted.
	 */
	UNRESTRICTED;
...
```

using these values in my config:

```
management.endpoints.access.default=NONE
management.endpoint.health.access=READ_ONLY
...
```

it just works.

**Comment by philwebb** [comment]
Also raised in https://github.com/spring-projects/spring-boot/issues/43302#issuecomment-2503531224
