### ISSUE TITLE
Undertow enable followLinks

### ISSUE THREAD

**Issue by peruzzo** [spring-projects/spring-boot#4340]
Hi,

I would like to be able to enable followLinks and safePaths for FileResourceManager class in Undertow.

Below is an example of where change to work on my project, of course the idea was to be able to set the variables  followLinks and safePaths.

```
private ResourceManager getDocumentRootResourceManager() {
    File root = getValidDocumentRoot();
    if (root != null && root.isDirectory()) {
        return new FileResourceManager(root, 0, true, true, new String[]{}); //HERE!!!
    }
    if (root != null && root.isFile()) {
        return new JarResourcemanager(root);
    }
    return ResourceManager.EMPTY_RESOURCE_MANAGER;
}

```

**Comment by wilkinsona** [comment]
Interesting. Can you expand a bit on how you're running your application please? I guess you're using an exploded archive as, otherwise, a `JarResourceManager` will be used.

**Comment by peruzzo** [comment]
My application uses the bower to manage the dependencies of the frontend and one of the dependencies called tivea-ui is an internal project of my business where development takes place in parallel.

To facilitate this development is used the bower link, so it makes a symbolic link from the directory where my project and I can develop both projects at the same time.


```
/opt/workspace/my-boot-project/bower link tivea-ui /opt/workspace/tivea-ui
```

.bowerrc  (my-boot-project)
```
{
    "directory": "src/main/webapp/bower_components",
    "allow-root": "1"
}
```

index.html (my-boot-project)
```
<script defer src="/bower_components/tivea-ui/dist/js/tivea-ui.js"></script>
```

**Comment by wilkinsona** [comment]
Thanks

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
