### ISSUE TITLE
Spring Boot 3.4.0， There is an inexplicable occurrence in Zhonghui where the get parameter of the host is automatically bound, similar to the problem in 3.4.1

### ISSUE THREAD

**Issue by twelvet-s** [spring-projects/spring-boot#43459]
As the title suggests, I did not transmit the query parameter 'host' during the get request, but he inexplicably bound a host for me
![97d66415bd2c4019d4e313de5b794bf](https://github.com/user-attachments/assets/26dc57e0-774c-4985-b590-c32183d6a14b)
![7b91297bc4883b17b9995caa86acbae](https://github.com/user-attachments/assets/a0c487b0-36e5-455a-abd3-da6d39f3bf96)

**Comment by twelvet-s** [comment]
I only switched back to Spring Boot 3.3.6 without any other changes, and this issue disappeared. Can it be considered a parameter binding bug in 3.4.0

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/34039
