### ISSUE TITLE
Spring Security 4.0.3 snapshots break Boot's default security configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4345]
`SecurityAutoConfigurationTests` is a bit fragile as it's checking for the number of filters in the security filter chain rather than checking than the one we expect are there. 

In particular, when Boot's default is disabled, it's expecting a certain fixed state that might change in Spring Security at any time (like this morning). Instead we should probably check that Boot's default was not applied rather than assuming what the state is with a default Spring Security setup.

**Comment by dsyer** [comment]
That test fails for me now. Why is it passing for you? There really only should be one filter chain.

**Comment by wilkinsona** [comment]
I think you'll need to force a new Spring Security snapshot

**Comment by wilkinsona** [comment]
Getting a whole extra filter chain is weird. I thought it was just the number of filters in a chain that had changed.

**Comment by snicoll** [comment]
I guess that's another issue than this one in any case. Yes, if you are on yesterday's snapshot it will work as it seems to be a regression in Spring Security.

**Comment by wilkinsona** [comment]
`testWebConfiguration` has 4 filters for static content and one for everything else:

```
[ Ant [pattern='/css/**'], []]
[ Ant [pattern='/js/**'], []]
[ Ant [pattern='/images/**'], []]
[ Ant [pattern='/**/favicon.ico'], []]
[ OrRequestMatcher [requestMatchers=[Ant [pattern='/**']]], [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@46ab18da, org.springframework.security.web.context.SecurityContextPersistenceFilter@67ef029, org.springframework.security.web.header.HeaderWriterFilter@2187fff7, org.springframework.security.web.authentication.logout.LogoutFilter@5398edd0, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@9cd25ff, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@2755d705, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5fe8b721, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@790174f2, org.springframework.security.web.session.SessionManagementFilter@9f46d94, org.springframework.security.web.access.ExceptionTranslationFilter@2a76b80a, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@60094a13]]
```

`testDisableIgnoreStaticApplicationPaths` has two chains, the first of which is wrong:

```
[ Ant [pattern='/**'], []]
[ OrRequestMatcher [requestMatchers=[Ant [pattern='/**']]], [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@687a762c, org.springframework.security.web.context.SecurityContextPersistenceFilter@6e57e95e, org.springframework.security.web.header.HeaderWriterFilter@21d5c1a0, org.springframework.security.web.authentication.logout.LogoutFilter@758f4f03, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@db44aa2, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@740abb5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@578524c3, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@1a2e2935, org.springframework.security.web.session.SessionManagementFilter@2e77b8cf, org.springframework.security.web.access.ExceptionTranslationFilter@2f4854d6, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@10b892d5]]
```

Assuming that this ordering reflects the chains' ordering, setting `security.ignored:none` will have the effect of switching off security entirely.

**Comment by wilkinsona** [comment]
For reasons I don't understand yet, having the error controller prevents the `[ Ant [pattern='/**'], []]` chain from being configured. However, if you disable the error controller and set `security.ignored:none` it does switch off security entirely.

@rwinch Something appears to have changed in the latest Spring Security 4.0.3 snapshots that has broken Boot's security configuration.

**Comment by rwinch** [comment]
This should be fixed on Spring Security's side now
