### ISSUE TITLE
Inconsistent double slashes in generated Javadoc URLs

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#43518]
As discovered @ngocnhan-tran1996 in #43512, the generated Javadoc URLs are currently inconsistent. Some have double slashes and some don't. For instance, [the section on configuring multiple datasources](https://docs.spring.io/spring-boot/3.3-SNAPSHOT/how-to/data-access.html#howto.data-access.configure-custom-datasource) has two slashes for `DataSource` but only one for `@Bean` yet both have a slash at the end in the configuration.

**Comment by philwebb** [comment]
I think the original PR covered some of the cases, but not all. The Asciidoctor extension tries to deal with this, but for the DataSource case we're the ones [concatenating things](https://github.com/spring-projects/spring-boot/blob/cc877987a4c2cf959882cf6e8b5552a490d0bd80/buildSrc/src/main/java/org/springframework/boot/build/antora/AntoraAsciidocAttributes.java#L206).
