### ISSUE TITLE
Consider migrating spring-cloud-context into Spring Boot

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#4353]
It'll be much easier to use such options like properties encryption directly, especially they are not related with cloud coordination.

**Comment by spencergibb** [comment]
Features of spring-cloud-context.

- Bootstrap application context (`bootstrap.{yml|properties}`): useful for pulling configuration from external sources.
- Encryption (as mentioned above).
- `@RefreshScope`.
- Child context utilities for creating a named child context (See `@RibbonClient` and `@FeignClient`).

**Comment by wilkinsona** [comment]
Duplicates #2182
