### ISSUE TITLE
Unable to disable the Spring Boot banner in 3.4.0, either programmatically or in application.properties.

### ISSUE THREAD

**Issue by HarshaVardhanAcharyAthaluri** [spring-projects/spring-boot#43538]
```
@SpringBootApplication 
public class SpringwebdemoApplication {
public static void main(String[] args) {
    SpringApplication app  = new SpringApplication(SpringwebdemoApplication.class);
    app.setBannerMode(Banner.Mode.OFF);
    app.run(args);
}}
```

(or)

`spring.main.banner-mode=off`
![springboot banner](https://github.com/user-attachments/assets/8b4b644a-6504-4ff2-807d-38ea94ae6693)

**Comment by mdeinum** [comment]
Stackoverflow thread for the same: https://stackoverflow.com/questions/79287083/unable-to-disable-springboot-banner-in-3-4-0

**Comment by bclozel** [comment]
Thanks for the link Marten, let's close this issue in favor of the StackOverflow question and we can reopen it if it turns out there's a bug.
