### ISSUE TITLE
Actuator publishes three authentication success audit events

### ISSUE THREAD

**Issue by charlesrgould** [spring-projects/spring-boot#4355]
Created a simple project that demonstrates this fact. Is this expected behavior?

https://github.com/charlesrgould/authentication-audit/tree/master

TL;DR

The class [`AuthenticationAuditListener`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/security/AuthenticationAuditListener.java#L80) listens for `AbstractAuthenticationEvent`. When you log in, three such events are generated:

1. `AuthenticationSuccessEvent`
2. `SessionFixationProtectionEvent`
3. `InteractiveAuthenticationSuccessEvent`

So Actuator publishes three audit events. Here is a printout:

```
AuditApplicationEvent[source=AuditEvent [timestamp=Fri Oct 30 12:34:48 EDT 2015, principal=user, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@380f4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: E5F6D15AA02D054DE93E4B56EF10ADCC}]]
AuditApplicationEvent[source=AuditEvent [timestamp=Fri Oct 30 12:34:48 EDT 2015, principal=user, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@380f4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: E5F6D15AA02D054DE93E4B56EF10ADCC}]]
AuditApplicationEvent[source=AuditEvent [timestamp=Fri Oct 30 12:34:48 EDT 2015, principal=user, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@380f4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: E5F6D15AA02D054DE93E4B56EF10ADCC}]]
```

**Comment by dsyer** [comment]
All three events are `AbstractAuthenticationEvent` so I guess it is expected. It doesn't seem to be adding a lot of value though, so would you like to suggest a change? Maybe we should log the event type as part of the audit.

**Comment by charlesrgould** [comment]
Whoops. Thanks for referencing that JHipster issue. I only searched for duplicates in this project.

> Maybe we should log the event type as part of the audit.

If the listener isn't smart enough to send one authentication success event, then that would help to distinguish them.

**Comment by charlesrgould** [comment]
Awesome! Thanks.
