### ISSUE TITLE
Documentation still has references to 'layertools'

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#43565]
We changed 'layertools' to 'tools' but some of our docs still reference the old name.

**Comment by ngocnhan-tran1996** [comment]
Can I get this issue?

**Comment by mhalbritter** [comment]
@ngocnhan-tran1996 Sure, go ahead.

**Comment by ngocnhan-tran1996** [comment]
@mhalbritter 

I found `layertools` keyword and it only appears in [Dockerfiles](https://docs.spring.io/spring-boot/reference/packaging/container-images/dockerfiles.html)

I am not sure this reference need to be change. Please tell me if I am misunderstanding

**Comment by philwebb** [comment]
Yes, that's the one. "that is intended to be used with layertools" should be something like "that is intended to be used with the `extract` tools mode command"

**Comment by snicoll** [comment]
Closing in favor of PR #43601
