### ISSUE TITLE
Recommendations for new behavior of PropertySourcesPlaceholderConfigurer

### ISSUE THREAD

**Issue by diegomarquezp** [spring-projects/spring-boot#43579]
### Overview

Hello, I'm a maintainer of the [Spring Framework on Google Cloud](https://github.com/GoogleCloudPlatform/spring-cloud-gcp). We have recently been working on upgrading Spring Cloud to 2024.0 and Spring Boot to 3.4. So far, so good, except for our `secretmanager` [integration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/test-spring-cloud-2024/spring-cloud-gcp-secretmanager).

The way we support bean injections for this integration is by specifying properties with the syntax `${sm://secret_id}`, implying a request to the Secret Manager service.

Unfortunately, the colon `:` character is now being interpreted differently since https://github.com/spring-projects/spring-framework/commit/00e05e603d4423d33c99dadeb52fef26be71dfb8, with the resulting behavior being to interpret it as "property `sm` with fallback value of `//secret_id`". We have confirmed this in our [code sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/test-spring-cloud-2024/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample).

### What have we tried so far
We have tried introducing our own `static PropertySourcesPlaceholderConfigurer` bean (see [bean declaration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0feea0d16cd5fbdd5f38af5a5596e3cdd2e9ac1b/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java#L95-L100), see [source](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/test-spring-cloud-2024/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerPlaceholderConfigurer.java#L24)), set up to be [configured before](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0feea0d16cd5fbdd5f38af5a5596e3cdd2e9ac1b/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java#L48) the default `PlaceholderConfigurer` autoconfiguration.

Interestingly, this works perfectly for `@Value` annotations such as `@Value("${sm://my_secret}")` (see [example](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0feea0d16cd5fbdd5f38af5a5596e3cdd2e9ac1b/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretManagerWebController.java#L51)), but not for `@Configuration` classes that reference a properties file (in [our case](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0feea0d16cd5fbdd5f38af5a5596e3cdd2e9ac1b/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretConfiguration.java#L22-L24), simply `application.properties`). I confirmed that the following code has the default `PropertySourcesPlaceholderConfigurer` (`this.placeholdersResolver` in `Binder.java`) when debugging my application:

https://github.com/spring-projects/spring-boot/blob/60e0de79ea9de2989ab03e9a193ae95de1cfcbf0/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L459-L465

### More context

 * We use a [custom config data location resolver](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/test-spring-cloud-2024/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java). I suspect this may have to do with how the properties file decides to resolve its placeholder.

### Alternatives considered

We are also thinking of _additionally_ supporting the `${sm//my_secret}` syntax (without the colon) as a workaround to escape the colon with a backslash, however we would like to avoid our users changing their code as much as possible.

### Questions

**My first question is**: Why would the properties file be parsed with a different `PlaceholderConfigurer` than what's specified in the `static` bean? I believe this bean is meant to be a singleton, so I'm not sure where in the application it's decided to associate the default configurer to this configuration.

**My second question is**: Is there a preferred way to adapt to this new behavior?

**Comment by philwebb** [comment]
Thanks for the report, but I think someone from the Spring Framework team will be better placed to help. Unfortunately, I can't transfer issues but @bclozel or @snicoll can. Alternatively you can close this one and raise it again at https://github.com/spring-projects/spring-framework/issues

**Comment by diegomarquezp** [comment]
Thank you. I have closed this one and transferred it to https://github.com/spring-projects/spring-framework/issues/34124
