### ISSUE TITLE
Build info timestamp is truncated to seconds

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#43581]
We use a custom timestamp for the build-info maven goal like this:
```xml
...
<properties>
        <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss.SSS'Z'</maven.build.timestamp.format>
....

<plugins>
...
                        <configuration>
                            <time>${maven.build.timestamp}</time>
                        </configuration>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
...
```

As you can see, the timestamp has sub-second precision and was also printed to the build properties like this:
```
build.time=2024-12-19T19\:59\:39.040Z
```

Since Spring Boot 3.3.6 ([with this commit](https://github.com/spring-projects/spring-boot/commit/491515e6e34c866b768842a5e798b54f283f9c7c)), this is effectively truncated to seconds:
```
build.time=2024-12-19T19\:59\:39Z
```

This turns out to be a breaking change for us. We can fix our problem by reconfiguring `maven.build.timestamp.format` 
to second precision.

So, I don't really expect a fix here, but you may want to add these to the release notes, as this might cause problems when updating.

**Comment by snicoll** [comment]
Sorry we broke you, closing in favor of PR #43612
