### ISSUE TITLE
No such bean exception.No bean Named xxxx available.

### ISSUE THREAD

**Issue by Swachithreddy** [spring-projects/spring-boot#43585]
I am upgrading from java 11 to 21 and Spring boot 2.7.5 to 3.2.9 and I'm facing this issue while running the test cases compilation is fine and also assertions have been failing expected 404 but actual is 500 internal server error.Please help me on this I was strucked here from few days.TIA.

**Comment by bclozel** [comment]
2.7.5 to 3.2.9 is too much of a gap to perform at once.

You should start migrating to 3.0, then 3.1 and follow the upgrade guides. [Start with this one](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide).

If you hit a problem, please ask a question on StackOverflow as this issue tracker is for bugs and enhancements only.
