### ISSUE TITLE
Managed Dependency Coordinates lists Spock and OkHttp dependencies that are not managed

### ISSUE THREAD

**Issue by yangyaofei** [spring-projects/spring-boot#43584]
I found `okhttp` not in `spring-boot-dependencies`([pom](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.4.1/spring-boot-dependencies-3.4.1.pom)) 3.4.X .

But in the 3.4.1 [document](https://docs.spring.io/spring-boot/3.4.1/appendix/dependency-versions/coordinates.html), the okhttp lib still in `Managed Dependency`.

I think maybe it cause in this commit: https://github.com/spring-projects/spring-boot/commit/6161ef7581d55a283c4d5b0eedc9bc18d17f4fc2

**Comment by bclozel** [comment]
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#okhttp-dependency-management-removed

**Comment by bclozel** [comment]
Wait, this probably shouldn't be listed in our reference docs anymore. Reopening.

**Comment by yangyaofei** [comment]
@bclozel ok, it's the wrong doc, thank you, it helps.
