### ISSUE TITLE
Lombok Not Working as Expected in IntelliJ with Maven Configuration (Spring Boot 3.4.1)

### ISSUE THREAD

**Issue by sumitverma77** [spring-projects/spring-boot#43593]
I am facing an issue where Lombok annotations such as @Getter, @Setter, etc., are not being processed correctly in my project using Spring Boot 3.4.1. I have added the necessary Lombok dependencies and configured the maven-compiler-plugin for annotation processing, but IntelliJ IDEA doesn't seem to recognize the Lombok annotations or generate the corresponding getter and setter methods.

Even it is giving suggestions also while writing the code but gives error (cannot find symbol) after Running the code.
![image](https://github.com/user-attachments/assets/d253a29f-2003-4a15-b6e1-9db4db953a7b)

**Comment by sumitverma77** [comment]
**_Fixed:_**
1. Moved to Spring Boot stable version 3.2.3.
2. Removed the version tag from the Lombok dependency in pom.xml.
3. Invalidated IntelliJ IDEA cache by selecting all available options.

**Comment by Progambler227788** [comment]
I was facing same issue, I added latest version in pom.xml.

**My Spring Boot version:**

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```


**Make sure to add version in dependency**
```
	<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.36</version>
		</dependency>
```

**Make sure to add version in plugin** 

```
<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.36</version>
						</path>
					</annotationProcessorPaths>
<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.36</version>
						</exclude>
					</excludes>
```

If you **skip any version**, it will not work. I missed to place version in annotationProcessorPath and it was not working.


**Note:**
Secondly, make sure you have **enabled** the lombok plugin and also 
File → Settings → Build, Execution, Deployment → Compiler → Annotation Processors
Check ✅ the box Enable annotation processing
