### ISSUE TITLE
In the systemEnvironment, if we have two keys with different capitalization and want to take the lowercase key, but due to capitalization issues, we will not be able to obtain the correct value

### ISSUE THREAD

**Issue by 1090064154** [spring-projects/spring-boot#43602]
In the systemEnvironment, if we have two keys with different capitalization and want to take the lowercase key, but due to capitalization issues, we will not be able to obtain the correct value。

if we have key  "env"=qa  and key "ENV"=QA

```
// env=qa ENV=QA
System.out.println(applicationContext.getEnvironment().getProperty("env"));//QA
System.out.println(System.getenv("env"));//qa
```
if we use use System.getenv("env") will get the right value 
but if applicationContext.getEnvironment().getProperty("env") will get the wrong value 'QA'

our springboot version is 2.5.12

I thought it was a problem with the SystemEnvironmentPropertyMapper, which tends to take uppercase keys, resulting in missing the correct key.

![image](https://github.com/user-attachments/assets/9acc85bd-c4a9-4b27-8a3c-937e7c7a2dc8)
![image](https://github.com/user-attachments/assets/4bbd8198-940e-4193-a36a-20a0753d3eba)

**Comment by snicoll** [comment]
I am afraid this is working as designed. Environment variables must be upper case and dash separated on most OSes and those keys need to be mapped to regular properties using the canonical format.

If you need such specific handling of variables, you should call the underlying API directly as you're doing in your example.
