### ISSUE TITLE
@EnableOAuth2Sso does not work nice with spring-session

### ISSUE THREAD

**Issue by sloppycoder** [spring-projects/spring-boot#4360]
Searched the issues and SO and couldn't find anything similar, so I posted  a new question :

http://stackoverflow.com/questions/33458696/spring-boot-1-3-m5-oauth2-sso-does-not-work-with-spring-session

Appreciate anyone can look into this and give me some suggestions on how to troubleshoot further.

**Comment by snicoll** [comment]
Please do not cross-post, this is a waste of time for everybody. 

I can see that someone replied to your SO thread and #4270 is also related.

**Comment by sloppycoder** [comment]
sorry I failed to see how #4270 is related. I'll keep an eye on this one and re-test when fix it out.
thanks.

**Comment by snicoll** [comment]
you're right, #4270 isn't related (it broke in RC1 and we fixed it in master). What about the answer you got on the SO thread?

**Comment by sloppycoder** [comment]
the SO solution worked! my commit for your reference  4bcf5df70c718845f39ac5765cd1425b36edd525
maybe it's related to #4270 after all?

**Comment by sloppycoder** [comment]
just tried latest BUILD-SNAPSHOT, works fine without additional filter ordering code. Looks like the issue has been fixed in master already. Cool!
