### ISSUE TITLE
It looks like the eventId and parentId of the JFR events generated by 'FlightRecorderApplicationStartup' do not match. 

### ISSUE THREAD

**Issue by youngledo** [spring-projects/spring-boot#43615]
It looks like the eventId and parentId of the JFR events generated by 'FlightRecorderApplicationStartup' do not match.
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/a60848fd-0962-4a94-b926-bcc163f7df6c" />
<img width="417" alt="image" src="https://github.com/user-attachments/assets/6ade888c-979c-4a27-8f95-ece50d6d8754" />

I don't know if I did something wrong?

Here is my sample code and JVM parameters:
```java
@SpringBootApplication
public class StartApplication {

    public static void main(String[] args) {
        SpringApplication springApplication = new SpringApplication(StartApplication.class);
        springApplication.setApplicationStartup(new FlightRecorderApplicationStartup());
        springApplication.run(args);
    }
}
```

```shell
-XX:StartFlightRecording:filename=/data/app.jfr,duration=30s -XX:FlightRecorderOptions=stackdepth=192
```

### Additional
Spring Boot Version: 2.5.15、

I tried to use the '3.4.1 'version, and it seems to be the same:

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/cb06382a-a4df-4805-a0eb-817c9498efc3" />

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/34128
