### ISSUE TITLE
The logging.config does not support configuring URLs that do not end with ".xml".

### ISSUE THREAD

**Issue by JecketLiao** [spring-projects/spring-boot#43620]
My Spring Boot version is 3.2.7. The `logging.config` is set to a URL that can load an XML file, but the URL address does not end with ".xml", which causes the project to fail to start. The error occurs at the `if (url.getPath().endsWith(".xml"))` line in the `LogbackLoggingSystem`'s `configureByResourceUrl` method. By comparing the source code, I found that in previous versions, the judgment code here was not through `getPath()`, but `toString()`. Can the source code be modified to support URLs whose paths do not end with ".xml"?

**Comment by nosan** [comment]
It has already been fixed

https://github.com/spring-projects/spring-boot/pull/42986

**Comment by JecketLiao** [comment]
thanks！
