### ISSUE TITLE
Is there a contingency plan if LiveReload extension is either removed or deprecated at Google Chrome?

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#43639]
Hello

About [DevTools](https://docs.spring.io/spring-boot/reference/using/devtools.html), it works with [LiveReload](https://docs.spring.io/spring-boot/reference/using/devtools.html#using.devtools.livereload), I use it both, the former through STS4 and the latter through Google Chrome.

If you open the following link to install the extension in Google Chrome (it in other machine):

https://chromewebstore.google.com/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en-US

It contains the following message:

> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions

Even when this situation does not belong to Spring Boot itself. Just being curious

Is there a contingency plan if this extension is either removed or deprecated?

**Note**: I am _not_ doing this question at SO because it is an opinionated question.

Thanks for your understanding

**Comment by snicoll** [comment]
Please search the issue tracker before submitting. Duplicate #32111
