### ISSUE TITLE
Is it possible to use management port to display app UI?

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#4364]
Now I use Vaadin to build a monitor UI for Spring Boot app, but I want to visit the UI from management port not server port because of security problem. Nginx uses server.port to display content for end user, and admin uses management to access the rest api and admin UI.

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).
