### ISSUE TITLE
DevTools and JRebel

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#4366]
Hi there,

I've been using Spring Boot with JRebel inside NetBeans IDE Debug mode for quite a while. Works good.

@snicoll told me that Spring Boot DevTools 1.3.0 should go out of the way if JRebel or similar is present.

So i added them to the POM for the colleagues who don't have a JRebel license.

Now i'm noticing that DevTools class reloading kicks in before JRebel got a chance. 

Stack:
JRebel Agent 6.2.4
Spring Boot 1.3.0.M5
NetBeans 8.0.2
Java 1.8u66

The issue i'm seeing is

```
2015-11-02 15:14:16 JRebel: Reloading class 'de.enerko.ensupply.angebote.LastgangpreisrechnerController'.
2015-11-02 15:14:20 JRebel: Reconfiguring bean 'lastgangbepreisungsservice' [de.enerko.ensupply.angebote.Lastgangbepreisungsservice]
2015-11-02 15:14:21.084  INFO 8784 --- [      Thread-18] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3d62bf11: startup date [Mon Nov 02 15:12:34 CET 2015]; root of context hierarchy
[OMITTED]
2015-11-02 15:14:22.535  INFO 8784 --- [  restartedMain] de.enerko.ensupply.Application  
```

So JRebel kicks in, reloads changed classes and after that DevTools restarts the application.

DevTools are added as optional dependency

```xml
<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-devtools</artifactId>
	    <optional>true</optional>
	</dependency>
```

**Comment by snicoll** [comment]
Ooos?

**Comment by michael-simons** [comment]
Sure.

I'm generating the rebel.xml via Maven plugin

```xml
<plugin>
		<groupId>org.zeroturnaround</groupId>
		<artifactId>jrebel-maven-plugin</artifactId>
		<version>1.1.5</version>
		<configuration>
		    <alwaysGenerate>true</alwaysGenerate>
		</configuration>
		<executions>
		    <execution>
			<id>generate-rebel-xml</id>
			<phase>process-resources</phase>
			<goals>
			    <goal>generate</goal>
			</goals>
		    </execution>
		</executions>
	    </plugin>
```

Leads to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.zeroturnaround.com" xsi:schemaLocation="http://www.zeroturnaround.com http://www.zeroturnaround.com/alderaan/rebel-2_0.xsd">

        <classpath>
                <dir name="/Users/msimons/Development/de.enerko.ensupply/EnSupply-Web/target/classes">
                </dir>
        </classpath>

</application>
```

Application runs in NetBeans Debug Mode with JRebel Plugin 6.2.4.

**Comment by michael-simons** [comment]
Didn't now that you would answer me, Stéphane, so i wrote the original post without calling names :) Changed that.

**Comment by snicoll** [comment]
We're checking for the presence of `org.zeroturnaround.javarebel.ReloaderFactory` - Maybe that's a lousy check in your case?

**Comment by michael-simons** [comment]
Don't know. I'm actually doing nothing special here. The Maven plugin is actually superfluous when using the IDE Integration which itself uses the JRebel Agent like one would do from command line.

Some guy or gal from the JRebel Stuff recommends checking for org.zeroturnaround.javarebel.Integration, see http://zeroturnaround.com/forums/topic/multiple-javaagents/#post-20757

**Comment by snicoll** [comment]
ping @philwebb

**Comment by philwebb** [comment]
I've added `org.zeroturnaround.javarebel.Integration` to the detection list and also checked with more classloaders. Can you give the latest snapshot a go and see if that solves things?

**Comment by michael-simons** [comment]
Hi Phil,

updated to 1.3.0.BUILD-SNAPSHOT as of 2015/11/12 9:00, still running in NetBeans 8.0.2 with 6.2.4 and the issue is gone. Thanks a lot!

**Comment by philwebb** [comment]
Great. Thanks for testing.
