### ISSUE TITLE
WebApplicationContextUtils.getWebApplicationContext(ServletContext) always returns null in @WebAppConfiguration-annotated test

### ISSUE THREAD

**Issue by frankoid** [spring-projects/spring-boot#4370]
`WebApplicationContextUtils.getWebApplicationContext(ServletContext)` always returns null when called from tests in my Spring Boot 1.2.7 based app, even when they are annotated with `@WebAppConfiguration`.

`WebApplicationContextUtils.getWebApplicationContext(ServletContext)` successfully returns the context in similar tests in a different *non-Spring-Boot* application that I have (Spring 4.1.2).

Using a debugger I have compared what happens when running the tests in the Spring Boot and non-Spring Boot application and the difference seems to be that the `WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE` attribute gets set when `org.springframework.test.context.web.WebDelegatingSmartContextLoader` loads the context in the non-Spring Boot application but it does *not* get set when `org.springframework.boot.test.SpringApplicationContextLoader` loads the context in the Spring Boot application.

I have been able to work around this by adding the following code to my test, but it would be nice if this extra code was not needed:
```
	@Inject
	private WebApplicationContext webApplicationContext;

	@Inject
	private ServletContext servletContext;

	@Before
	public void springBootWebApplicationContextWorkaround() throws Exception
	{
		servletContext.setAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE, webApplicationContext);
	}
```

**Comment by frankoid** [comment]
OS: Mac OS X 10.10.5
JVM: Oracle Java 1.8.0_66

**Comment by snicoll** [comment]
In Spring Boot, `@WebAppConfiguration` does not load the container at all, `@WebIntegrationTest` does. That being said, I assume we should set the value as well when only `@WebAppConfiguration` is present.

**Comment by frankoid** [comment]
I should have mentioned that I'm using `org.springframework.mock.web` in this test rather than starting up a full container - i.e. `servletContext` is a `MockServletContext`.

**Comment by snicoll** [comment]
I've just added a few tests that work out of the box for me. Can you please share a sample project that reproduces the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by frankoid** [comment]
Thanks for adding the test @snicoll and sorry for the delay, I didn't see your message.

I've made a sample project that reproduces the problem available at https://github.com/brightinteractive/spring-boot-web-app-context-repro

**Comment by wilkinsona** [comment]
This test fails:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration
@SpringApplicationConfiguration(classes=TestConfiguration.class)
public class WebApplicationContextAvailabilityTests
{
	@Autowired
	private ServletContext servletContext;

	@Test
	public void webApplicationContextHasBeenSet() {
		assertThat(WebApplicationContextUtils.getWebApplicationContext(servletContext), is(notNullValue()));
	}

	@Configuration
	static class TestConfiguration {

	}

}
```

This test passes:

```
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration
@ContextConfiguration(classes = TestConfiguration.class)
public class WebApplicationContextAvailabilityTests
{
	@Autowired
	private ServletContext servletContext;

	@Test
	public void webApplicationContextHasBeenSet() {
		assertThat(WebApplicationContextUtils.getWebApplicationContext(servletContext), is(notNullValue()));
	}

	@Configuration
	static class TestConfiguration {

	}

}
```

The only change is the use of `@ContextConfiguration` in place of `@SpringApplicationConfiguration`

**Comment by wilkinsona** [comment]
This problem doesn't occur in 1.4 thanks to the changes made in [this commit](https://github.com/spring-projects/spring-boot/commit/7dffb702b5a2517b8135db6493ae073eaffeb146).
