### ISSUE TITLE
Custom ObjectMapper doesn't work after Extened WebMvcConfigurationSupport

### ISSUE THREAD

**Issue by evlstyle** [spring-projects/spring-boot#4372]
Hi, 
I think I need some help here to enable the Custom ObjectMapper and the extension of WebMvcConfingurtionSupport.  

The reason why I need to extend the WebMvcConfigurtionSupport is because I need to support a versioned Restful API layer kind of described in this post (http://stackoverflow.com/questions/20198275/how-to-manage-rest-api-versioning-with-spring) basically  the idea is to replace the "RequestMappingHandlerMapping" 

The reason why I need to customize the ObjectMapper is because I need to config the "enableDefaultTypingAsProperty"  as some of the Objects we are transferring between the layers are wrapped in generic Lists.  

I intended to override the Default ObjectMapper bean by defining a new one with Primary Annotation, it worked when I commented out the code that exptended the WebMvcConfigurationSupport however it stopped working once I turn the code back on.  I understand extending WebMvcConfingurtionSupport will disable auto-config therefore any override to the ObjectMapper bean will not work.  But the problem is that I need them both,  please comment how can I resolve this . 

thanks 
Evan

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

**Comment by evlstyle** [comment]
Actually  this is a bug  or feature ask in case you guys don't think this meets the bug bar .  The config "enableDefaultTypingAsProperty" is not exposed via the application properties therefore there is no way for user to change that without replacing the whole ObjectMapper object.  In that case I think this is at least a feature ask.

**Comment by snicoll** [comment]
I checked before closing this issue and @sdeleuze said he would look at your SO thread. But you need to create one first. I believe there is a way to configure things as you wish but you need to provide more details and this tracker is not the place for that. 

If we find that there is no satisfactory way, we'll come back here. Don't worry.
