### ISSUE TITLE
application.properties is not ok!

### ISSUE THREAD

**Issue by twogoods** [spring-projects/spring-boot#4373]
`spring.mvc.view.prefix: /WEB-INF/jsp/`   can not done 

`spring.view.prefix: /WEB-INF/jsp/ `   this is ok, why???

**Comment by novaeye** [comment]
spring.mvc.view.prefix => 1.2.x
spring.view.prefix => 1.3

**Comment by snicoll** [comment]
As @novaeye explained, `spring.view.*` properties have moved to `spring.mvc.view.*` in 1.3. It looks like you're looking at the 1.3 documentation (or sample) and use the properties with 1.2 (which obviously will not work).

Besides, [as described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).
