### ISSUE TITLE
Out of memory exception with 1.3.0.RC1

### ISSUE THREAD

**Issue by fawzyj** [spring-projects/spring-boot#4376]
Hi

My spring boot application works fine in version 1.2.7

When switch to 1.3.0-RC1 i got outOfMemory Exception.

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:55)
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.log(Logger.java:788)
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.error(SLF4JLocationAwareLog.java:216)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1085)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1074)
	at org.commerceforge.estore.EstoreApplication.main(EstoreApplication.java:32)
```

**Comment by fawzyj** [comment]
BTW: In my spring boot 1.2.7, i already use spring spring 4.2.2 and spring security 4.0.2 and everything is ok.

**Comment by snicoll** [comment]
What exact java version are you using and how do you start you app?

**Comment by fawzyj** [comment]
Java version jdk1.7.0-u25 (I am stick with java 7 because this is what we use for deployment)
I am using the maven plugin to run the application.
tested with maven 3, 3.1, 3.3 all with the same result (outOfMemory ex.)
I am using quad core i7 machine with 8GB of RAM



In a few times, it did not produce the exception but the application hang on the first request with this error message:
`SEVERE:Memory usage is low, parachute is non existent, your system may start failing.`
`[WARNING]`
`Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8080-exec-1"
SEVERE:Memory usage is low, parachute is non existent, your system may start failing.
[WARNING]
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ContainerBackgroundPro
cessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]"`


I tested it with java version 1.8 u60 with the command line "java -jar app.jar", and with the maven plugin on java 1.8u60, it runs fine, but it consumes about 1GB of ram, compared to about 500MB when using boot version 1.2.7, Is this normal?
I can accept that if this is normal as we are using cluster of 4GB Ram servers for deployment

**Comment by fawzyj** [comment]
OK, I think i got it..
setting java options -XX:PermSize=128m -XX:MaxPermSize=512m solve the problem
it seems that the new 1.3 release utilize much more permgen space than the 1.2.x
I think it is better to document this if the core team confirm that

Thanks

**Comment by RobMaskell** [comment]
For what it's worth, and it's very unscientific I realise that, but the first time I pushed my app to PWS after upgrading to Spring boot 1.3 I had to increase the the memory on the instance from 500Mb to 1Gb as the app breached the 500Mb limit on startup. I had made some changes between pushes so I know it's a very bad test.

**Comment by philwebb** [comment]
@RobMaskell @fawzyj Some changes have been made recently in Spring Framework that might help with this. If you get a chance could you let me know if the latest 1.3 SNAPSHOT improves things?

**Comment by RobMaskell** [comment]
Sure, memory stats after pushing both versions to PWS

Version | Mem
------------ | -------------
1.3.0.RC1 | 672Mb
1.3.0.BUILD-SNAPSHOT | 646Mb

**Comment by philwebb** [comment]
@RobMaskell Out of interest, how are you measuring those stats? Do you have any figures for 1.2.x?

**Comment by RobMaskell** [comment]
Very unscientifically reading them off the PWS Status screen :)

**Comment by philwebb** [comment]
I've been profiling the latest SNAPSHOT and I haven't been able to really replicate the problem. The simple web samples that we have appear to consume a similar amount of memory to 1.2.x.

There has been some changes to the Spring Framework snapshots to improve the annotation processing performance. It's possible that this has had an impact in reducing the number of synthesized annotation classes that were created.

@fawzyj Are you able to try your application with the latest SNAPSHOT? It would also be helpful if there's anyway you can provide a demo app that shows the problem. It's entirely possible that some third-party jar update is causing issues and perhaps the simple apps I'm trying just haven't triggered the problem.

@RobMaskell are you also able to try the latest SNAPSHOT with a 500Mb VM. Unfortunately I don't think the PWS status screen will provide accurate enough statistics. Spring uses a lot of caches that may consume space if it's available. I'm very interested to know why the version upgrade causes you to need a bigger instance. Are you using any specific libraries in your app?

**Comment by RobMaskell** [comment]
Tested RC1 & BUILD_SNAPSHOT pushing to PWS with a 500Mb VM, both will start, but both crash on first request from browser (as Thymeleaf is doing it's thing on first request). Although I had run my app on 1.2 and maybe even an early version of 1.3 successfully on PWS in a 500Mb VM I had also continued development before I tried again with RC1 so it could be that the app just needs more memory now. It just happened that I had to increase the VM memory on the same day I saw this post.

**Comment by philwebb** [comment]
@RobMaskell Thanks for testing. The first request info is useful, I hadn't profiled much beyond startup.

**Comment by madorb** [comment]
Just one thought - is it possible to grab an old tag or commit version from version control from before you upgraded to 1.3 and deploy that and see memory usage? then changing nothing else, change the boot version to 1.3 and see if that makes a material difference?

**Comment by RobMaskell** [comment]
Good idea, I can try that tomorrow

**Comment by philwebb** [comment]
I'm going to push this back to 1.3.1. I don't think it's a showstopper anymore for 1.3.0.RELEASE

**Comment by philwebb** [comment]
We've made some more memory refinements in Spring Framework that will be picked up in 1.3.1. I'm going to close this issue but if anyone finds examples of excessive memory usage please open a new issues.

You can also check out [this blog post](https://spring.io/blog/2015/12/10/spring-boot-memory-performance) for details of some of the memory analysis that was done.
