### ISSUE TITLE
launch.script kill -HUP (in do_stop method) isn't always shutting down the application

### ISSUE THREAD

**Issue by pmvilaca** [spring-projects/spring-boot#4378]
The do_stop method uses ```kill -HUP ...``` to trigger the shutdown of the application. Although (and I don't know why) for applications that are running for a while, that signal is being ignored. Because of #4371, the first run of stop command fails, the pid file is deleted and we end up with a zombie process. 

The weird thing is that after the failure, if I use the kill (without arguments; the default signal is TERM) the application stops properly.  

Here is the sequence of the events described above:

```
[ec2-user@ip-10-0-30-255 ~]$ sudo service proxy-service status
Running [12967]
[ec2-user@ip-10-0-30-255 ~]$ cat /var/run/proxy-service/proxy-service.pid
12967
[ec2-user@ip-10-0-30-255 ~]$ sudo service proxy-service stop
Unable to kill process 12967
[ec2-user@ip-10-0-30-255 ~]$ ps aux | grep java
root     12967  0.0 21.6 3007908 221208 ?      Sl   Nov02   1:11 java -jar -Dsun.misc.URLClassPath.disableJarChecking=true -Xmx1024M /var/proxy-service/proxy-service.jar --spring.profiles.active=dev
ec2-user 17876  0.0  0.2 110460  2208 pts/0    S+   13:55   0:00 grep --color=auto java
[ec2-user@ip-10-0-30-255 ~]$ sudo kill 12967
[ec2-user@ip-10-0-30-255 ~]$ sudo service proxy-service start
Started [17932]
[ec2-user@ip-10-0-30-255 ~]$ sudo service proxy-service stop
Stopped [17932]
[ec2-user@ip-10-0-30-255 ~]$ sudo service proxy-service start
Started [18026]
```
If we check the logs, nothing happens after the ```sudo service proxy-service stop``` and after the ```kill 12967``` we can see the usual shutdown log messages.

The is any particular reason to use the -HUP signal to stop the application?

**Comment by pmvilaca** [comment]
If there is no special reason to use the HUP signal, I would suggest to just use a normal kill (with the TERM signal) to shutdown the application (using the same command that is described to stop an application running on Openshift, for example).

http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#cloud-deployment-openshift

**Comment by dsyer** [comment]
HUP gives the application a chance to respond to the signal (release resources, close thread pools etc.). It is not really ideal to use TERM. Maybe your app was responding slowly, or had a resource that could not be released (socket timeout or something). If you can get it into the same state again get a thread dump (kill -3).

**Comment by pmvilaca** [comment]
@dsyer but with the kill command without arguments (that is sending the TERM signal) the application is also shutting down properly.

Here is a thread dump - https://gist.github.com/pmvilaca/183536827f99d9950c2f

**Comment by dsyer** [comment]
The thread dump looks clean. Sign TERM actually looks like it does what we need anyway (as opposed to KILL). Can anyone explain why we use HUP?

**Comment by pmvilaca** [comment]
@dsyer should I send a PR for this?

**Comment by dsyer** [comment]
Sure. You signed the CLA already right?

**Comment by pmvilaca** [comment]
@dsyer yes, it's signed. So, I'll send the PR for this one.

**Comment by philwebb** [comment]
We probably used HUP because some random script somewhere on the internet contained it :)

**Comment by pmvilaca** [comment]
@philwebb @dsyer could you please add this to 1.3.0 milestone? :)

**Comment by philwebb** [comment]
@pmvilaca It's already targeted to 1.3 (4 days ago)

**Comment by pmvilaca** [comment]
@philwebb sorry.. the milestone was just missing on the PR

**Comment by philwebb** [comment]
Ahh yes, I was working though my inbox and just got to that :)  Thanks for the prompt.
