### ISSUE TITLE
Maven Latest Spring-Boot dependencie breaks Spring Social

### ISSUE THREAD

**Issue by cescoferraro** [spring-projects/spring-boot#4381]
I really do not know who's issue this is. So I am posting everywhere, because I really need some help.

https://github.com/spring-projects/spring-social-facebook/issues/176

**Comment by snicoll** [comment]
Please don't do that. Cross-posting is a waste of time for everyone. It would be nice to provide more details on the spring social issue you've created.

**Comment by cescoferraro** [comment]
@snicoll All right, I was not sure who should deal with this. I have just added another comment there with an [SO question](http://stackoverflow.com/questions/33498827/spring-social-facebook-tuturial-error) containing the error I am getting. Which was a `java.lang.NullPointerException`after debuggin I've realized that was because `Cannot evaluate com.sun.proxy.$Proxy42.toString()`.
