### ISSUE TITLE
_links property appears more than once in Spring Data Rest JSON

### ISSUE THREAD

**Issue by eepstein** [spring-projects/spring-boot#4382]
I've a simple REST micro-service that uses spring boot's starter data rest package.   Version is 1.2.7.RELEASE.  When objects are deserialized there are multiple _links properties in the JSON and the first one is always empty.

For example:

```
{
  "version" : 1,
  "createdAt" : "2015-11-03T01:07:12.091319Z",
  "updatedAt" : "2015-11-03T01:07:12.091319Z",
  "id" : 1,
  "name" : "ROOT",
  "longName" : null,
  "description" : "Root of all accounts.",
  "type" : "PROD",
  "_links" : { },
  "_embedded" : { },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8081/api/accounts/1",
      "templated" : false
    },
    "owner" : {
      "href" : "http://localhost:8081/api/accounts/1/owner",
      "templated" : false
    },
    "subAccounts" : {
      "href" : "http://localhost:8081/api/accounts/1/subAccounts",
      "templated" : false
    }
  }
}
```

I think this is a bug.

**Comment by snicoll** [comment]
Given the output, it looks like you're not using SD rest's default. There's not enough context in your report to figure out what could be wrong. Can you share a sample project that reproduces the problem please?

**Comment by eepstein** [comment]
Sure.  What's the best way to share such a project?

**Comment by eepstein** [comment]
I think I found the cause.  I'm using a more recent version of Jackson as I want its serialization of JSR310 date-time values and the current release is 2.6.3 while Spring Boot is using 2.4.6

I had shifted all to 2.6.3 (Spring Boot's build logic automatically excluded its versions at that point) and it seems doing so produced the side-effect I saw.

Not sure why upping the versions of the Jackson packages had that effect, but since v 2.4.6 works for my needs, I'm using that.

```
{
  "version" : 1,
  "createdAt" : "2015-11-03T01:07:12.091319Z",
  "updatedAt" : "2015-11-03T01:07:12.091319Z",
  "id" : 1,
  "name" : "ROOT",
  "longName" : null,
  "description" : "Root of all accounts.",
  "type" : "PROD",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8081/api/accounts/1"
    },
    "subAccounts" : {
      "href" : "http://localhost:8081/api/accounts/1/subAccounts"
    },
    "owner" : {
      "href" : "http://localhost:8081/api/accounts/1/owner"
    }
  }
}
```

**Comment by snicoll** [comment]
whatever works for you but a github repo is the easiest.
