### ISSUE TITLE
Switch to TestPropertySourceUtils for property parsing

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#4384]
We would like to do something like:
````java
@WebIntegrationTest({"script=script.groovy", "variables=foo=FOO\n bar=BAR"})
````
https://github.com/spring-cloud/spring-cloud-stream-modules/issues/56.

Unfortunately, the `SpringApplicationContextLoader.extractEnvironmentProperties` does this:
````java
String content = StringUtils.arrayToDelimitedString(values, LINE_SEPARATOR);
Properties properties = new Properties();
try {
     properties.load(new StringReader(content));
     return asMap(properties);
}
````
So, we end up with the result:
```
0 = {Hashtable$Entry@1327} "org.springframework.boot.test.IntegrationTest" -> "true"
1 = {Hashtable$Entry@1328} "script" -> "script.groovy"
2 = {Hashtable$Entry@1329} "bar" -> "BAR"
3 = {Hashtable$Entry@1330} "variables" -> "foo=FOO"
```
instead of expected `variables" -> "foo=FOO\n bar=BAR"`.

The solution is in the `TestPropertySourceUtils`:
````java
public static Map<String, Object> convertInlinedPropertiesToMap(String[] inlinedProperties) {
		Assert.notNull(inlinedProperties, "inlinedProperties must not be null");
		Map<String, Object> map = new LinkedHashMap<String, Object>();

		Properties props = new Properties();
		for (String pair : inlinedProperties) {
			if (!StringUtils.hasText(pair)) {
				continue;
			}

			try {
				props.load(new StringReader(pair));
			}
			catch (Exception e) {
				throw new IllegalStateException("Failed to load test environment property from [" + pair + "].", e);
			}
			Assert.state(props.size() == 1, "Failed to load exactly one test environment property from [" + pair + "].");

			for (String name : props.stringPropertyNames()) {
				map.put(name, props.getProperty(name));
			}
			props.clear();
		}

		return map;
	}
````
In other words: load each `values` pair to the target map separately.

**Comment by philwebb** [comment]
Switching to `TestPropertySourceUtils` seems like a sensible change but unfortunately it doesn't solve your issue. I added a test case and the "Failed to load exactly one test environment property" error gets thrown.

I'll switch Boot code so that it's consistent with Spring Framework but you'll have to lobby @sbrannen if you want `TestPropertySourceUtils` changed.

**Comment by artembilan** [comment]
Thank you, @philwebb, for taking care about that!

Yes, I'm forced to confirm that we should `escape` the value to bypass properties extraction for the whole line during `Properties.load()`: https://github.com/spring-cloud/spring-cloud-stream-modules/pull/63

**Comment by sbrannen** [comment]
Relates to #2505.
