### ISSUE TITLE
No PID file generate when ln the same jar to another name in init.d

### ISSUE THREAD

**Issue by GrapeBaBa** [spring-projects/spring-boot#4385]
Hi
when i setup a linux service, it works fine according to the document. But when i change some code and repackage. i use ln command to another name service, there is no pid and log file generate.

**Comment by snicoll** [comment]
Please [do not cross post](http://stackoverflow.com/questions/33515591/no-pid-file-generate-when-reinstall-spring-boot-executable-jar), this is a waste of time for everybody.
