### ISSUE TITLE
spring-boot-gradle-plugin - publishIvyJavaPublicationToIvyRepository does not publish boot-jar

### ISSUE THREAD

**Issue by jjohn26** [spring-projects/spring-boot#4386]
Hi,

I am using a spring-boot-gradle-plugin in a multi-project build, which will publish the artifacts to an ivy-repository. I am using gradle 'ivy-publish' plugin (https://docs.gradle.org/current/userguide/publishing_ivy.html) for publish.

Expected result: gradle publish boot-jar (the fat jar file with all dependencies under lib dir, and classes only contain spring-boot classes)
Actual result : gradle publish jar created by jar task (which contains no dependencies)

my config looks like
```groovy    
publishing {
        publications {
            ivyJava(IvyPublication) {
                from components.java
            }
        }
        repositories {
            ivy <ivy_repo_url>
        }
    }
```

**Comment by wilkinsona** [comment]
You need to ensure that the creation of the fat jar as occurred prior to trying to publish it:

```groovy
publish {
	dependsOn bootRepackage
}
```
