### ISSUE TITLE
.properities and .yml

### ISSUE THREAD

**Issue by twogoods** [spring-projects/spring-boot#4387]
in springboot `.properities` will cover `.yml`,right? if you use properities you can `mvn spring-boot:run`，but if you use .yml you must `mvn package` and `java -jar -Dspring.profiles.active=development target/...`,`mvn spring-boot:run` can not get config

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

Properties and YAML configurations are supported in the exact same way and both are working using `mvn spring-boot:run`. When you create the SO thread, I'd advise to provide more details about your particular setup (project structure, file name, etc).
