### ISSUE TITLE
CacheAutoConfiguration tries to configure CacheManager before Hazelcast is started

### ISSUE THREAD

**Issue by aahlenst** [spring-projects/spring-boot#4389]
If I configure `spring.cache.type=hazelcast` in my application.properties, my Boot application using Spring Boot 1.3.0.RC1 cannot load and Spring exits with the following exception pretty much immediately after starting, although Hazelcast is on the classpath and started successfully if I omit the configuration setting (I get a `GuavaCacheManager` in this case instead): 

    Caused by: java.lang.IllegalArgumentException: No cache manager could be auto-configured, check your configuration (caching type is 'HAZELCAST')
        at org.springframework.util.Assert.notNull(Assert.java:115)
        at org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheManagerValidator.checkHasCacheManager(CacheAutoConfiguration.java:137)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        ... 59 more

The problem seems to be that Hazelcast is started after JPA/Hibernate and the `CacheManager` is verified even before JPA/Hibernate is started. The problem goes away as soon as I add `@AutoConfigureAfter({RedisAutoConfiguration.class, HazelcastAutoConfiguration.class})` to Boot's `CacheAutoConfiguration` or I explictly start Hazelcast myself:

    @Bean
    public HazelcastInstance hazelcastInstance(Config config) {
        return Hazelcast.newHazelcastInstance(config);
    }

I tried to reproduce it in a test case and to create a sample application – both unsuccessfully.

**Comment by snicoll** [comment]
Are you sure that you are using `1.3.0.RC1` because it looks exactly the same thing as #4158 and the reported confirmed the fix worked for him. That being said, I see that I have put the ordering on `HazelcastCacheConfiguration` which is plain wrong since it's not an auto-configuration. 

Let's try to fix that. Would you be so kind to test a snapshot?

**Comment by aahlenst** [comment]
I'm pretty sure it's 1.3.0.RC1 because other bugs from the previous milestone are gone and the Spring Boot badge on startup displays 1.3.0.RC1 :)

Have you already committed any changes related to this issue? As soon as you have I'll test.

**Comment by snicoll** [comment]
That's fine, I just wonder what I missed since I had an explicit test for that in the initial fix. I am going to revisit this now.

**Comment by aahlenst** [comment]
The issue is not really about JPA. `CacheAutoConfiguration` happens before Hibernate/JPA is configured because of `@AutoConfigureBefore(HibernateJpaAutoConfiguration.class)` and that's ok. The problem is that `HazelcastAutoConfiguration` is performed even after Hibernate/JPA is configured (at least in my case, but I wasn't able to reproduce it separately) and that's too late for `CacheAutoConfiguration`. For Redis there's `@AutoConfigureAfter(RedisAutoConfiguration.class)` on `CacheAutoConfiguration` and that ensures that Redis is ready before a `CacheManager` is configured.

**Comment by vpavic** [comment]
#4158 fix works for our use case however we don't have Spring cache abstraction in the mix.

I'll try to test such configuration in our project and see if it's also affected.

**Comment by snicoll** [comment]
@aahlenst can you please describe your actual setup rather than debugging the code please? I'll try to reproduce the problem today but since you were unable to, I am afraid it might take more time than I initially thought. If you can't share a project, sharing a minimal config and your classpath would help.

**Comment by snicoll** [comment]
I think I got it. when you set `spring.hazelcast.type=hazelcast` you actually need the Hazelast spring integration. Could it be that you don't have `hazelcast-spring` on your classpath?

**Comment by vpavic** [comment]
@snicoll I reproduced the issue in our project.

You can use my sample project from #4158 together with this patch:

```patch
diff --git build.gradle build.gradle
index 615f51b..f9d7cea 100644
--- build.gradle
+++ build.gradle
@@ -1,6 +1,6 @@
 buildscript {
 	ext {
-		springBootVersion = '1.3.0.M5'
+		springBootVersion = '1.3.0.RC1'
 	}
 
 	repositories {
@@ -28,7 +28,8 @@ dependencies {
 	compile 'org.springframework.boot:spring-boot-starter-data-jpa'
 	compile 'org.springframework.boot:spring-boot-starter-cache'
 
-	compile 'com.hazelcast:hazelcast-hibernate4:3.5.2'
+	compile 'com.hazelcast:hazelcast-hibernate4'
+	compile 'com.hazelcast:hazelcast-spring'
 	compile 'com.h2database:h2'
 
 	testCompile 'org.springframework.boot:spring-boot-starter-test'
diff --git src/main/java/demo/DemoApplication.java src/main/java/demo/DemoApplication.java
index 96a15ed..ce36ba2 100644
--- src/main/java/demo/DemoApplication.java
+++ src/main/java/demo/DemoApplication.java
@@ -3,6 +3,7 @@ package demo;
 import com.hazelcast.config.Config;
 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.cache.annotation.EnableCaching;
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.DependsOn;
 import org.springframework.context.annotation.Profile;
@@ -11,6 +12,7 @@ import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
 
 import javax.sql.DataSource;
 
+@EnableCaching
 @SpringBootApplication
 public class DemoApplication {
 
diff --git src/main/resources/application.properties src/main/resources/application.properties
new file mode 100644
index 0000000..7b96b1c
--- /dev/null
+++ src/main/resources/application.properties
@@ -0,0 +1 @@
+spring.cache.type=hazelcast
```

**Comment by snicoll** [comment]
you're the man, thanks a lot!

**Comment by aahlenst** [comment]
Works like a charm. Thanks a lot.

**Comment by snicoll** [comment]
Thanks for testing!

**Comment by johanvdb** [comment]
I have picked up the same issue but on Spring Boot 1.4.0-RELEASE. I can see the changes of https://github.com/spring-projects/spring-boot/commit/2c4f88e221afa376661c474285e86f53c0dd4f0b.

I set

```
spring.cache.type=hazelcast
```

But I get the following in the log if I do so

```
 No cache manager could be auto-configured, check your configuration (caching type is 'HAZELCAST')
```
 
I import spring-cloud-cluster-hazelcast, and if I don't force the cache type in properties as above, then Hazelcast starts up, autoconfigures, and leadership election via it works fine. If I then autowire a CacheManager, I get the simple concurrent one.

Am I doing something wrong?

**Comment by snicoll** [comment]
@johanvdb this issue is closed. If you can't reproduce this without `spring-cloud-cluster-hazelcast` could you please open an issue in [their tracker](https://github.com/spring-cloud/spring-cloud-cluster/issues) and mention me? We can take it from there.

If you can reproduce without spring cloud, please create a new issue here with the sample that reproduces the problem. Thanks!
