### ISSUE TITLE
Maven wrapper generated by `spring init foo` should be executable.

### ISSUE THREAD

**Issue by spilth** [spring-projects/spring-boot#4392]
I'm using Spring CLI v1.2.7.RELEASE on a Mac.

When I run `spring init foo`, the `mvnw` script that's generated isn't executable so I have to manually run `chmod u+x mvnw` myself, which seems low-level and defeats the purpose of the convenience. It would be nice if the `init` command did this for me.

**Comment by snicoll** [comment]
Ah, yet another occurence of that bug :(

[Intellij IDEA](https://youtrack.jetbrains.com/issue/IDEA-147346) and [STS](https://issuetracker.springsource.com/browse/STS-4260) are affected as well. 

Thanks for the report.

**Comment by philwebb** [comment]
@snicoll Is this an Spring Initializr issue? Should we do something in Boot of does the generated zip file need fixing?

**Comment by snicoll** [comment]
The thing that Unzip the archive is unable to read permissions properly. The fix is to apply the execute flag on known type. That's what Jetbrains did this morning unless someone has a better idea. 

The service generate a proper zip. I can fix that tomorrow if you agree with the fix.

**Comment by philwebb** [comment]
I guess we have the same thing with gradlew as well
