### ISSUE TITLE
Support several @ConfigurationProperties auto-created beans with the same prefix

### ISSUE THREAD

**Issue by stromnet** [spring-projects/spring-boot#4395]
I got a project with multiple Autoconfiguration-style pieces. 

I have something similar to this:
````java
@Configuration
@EnableConfigurationProperties(Config1.class)
public class AC1  {
@Autowired
private Config1 cfg;
}

@Configuration
@EnableConfigurationProperties(Config2.class)
public class AC2  {
@Autowired
private Config2 cfg;
}

@ConfigurationProperties(prefix="myconfig")
public class Config1 {
}

@ConfigurationProperties(prefix="myconfig")
public class Config2 {
}
````

For some reason it totally refused to instantiate Config2.. After tearing my hair for a few hours I finally found out that changing the prefix on Config2's annotation resolved the issue, both Config classes are now resolved properly.

org.springframework.boot:spring-boot-starter:jar:1.2.7.RELEASE
org.springframework.boot:spring-boot-autoconfigure:jar:1.2.7.RELEASE
 (also tested in 1.2.3)

**Comment by snicoll** [comment]
The bean are registered using their prefix + `.CONFIGURATION_PROPERTIES` that's why it does not work. Admittedly, I would strongly advice you not doing that: two POJOs sharing the same prefix is asking for trouble, really.

You can easily workaround for now with the following:

```
@Configuration
public static class AC1 {
	@Autowired
	private Config1 cfg;
}

@Configuration
public static class AC2 {
	@Autowired
	private Config2 cfg;
}

@Configuration
public class Config1Configuration {

	@Bean
	@ConfigurationProperties(prefix = "myconfig")
	public Config1 config1() {
		return new Config1();
	}
}

@Configuration
public class Config2Configuration {

	@Bean
	@ConfigurationProperties(prefix = "myconfig")
	public Config2 config2() {
		return new Config2();
	}
}

public class Config1 {
}

public class Config2 {
}
```

**Comment by snicoll** [comment]
The new name would be a breaking change so I am wondering what we should do. Surely, adding the simple name of the target class could help but not resolve things permanently. Maybe the default bean name  could be `myconfig.Config1.CONFIGURATION_PROPERTIES` and  `myconfig.Config2.CONFIGURATION_PROPERTIES`. That's a bit dumb if there is only one bean for a given prefix (as it should be).

**Comment by snicoll** [comment]
Let's go for the full form then `fully.qualified.class.name.prefix.CONFIGURATION_PROPERTIES`
