### ISSUE TITLE
@ConfigurationProperties metadata generation issue with Lombok in nested classes

### ISSUE THREAD

**Issue by CalamarBicefalo** [spring-projects/spring-boot#4397]
If you create @ConfigurationProperties class which contains a nested class, using Lombok instead of regular getters / setters, the generated metadata.json, won't contain any traces of the nested object (nor its properties).

e.g.

```java
@Data
@org.springframework.boot.context.properties.ConfigurationProperties(prefix = "bug")
public class ConfigPropsLombok {
    private String iAmAProperty;

    private NestedProperty nestedProperty;

    @Data
    public static class NestedProperty {
        private String iAmANestedPropertyInANestedClass;
    }
}
```

produces

```json
{
  "groups": [{
    "name": "bug",
    "type": "io.pivotal.ConfigPropsLombok",
    "sourceType": "io.pivotal.ConfigPropsLombok"
  }],
  "properties": [{
    "name": "bug.i-am-aproperty",
    "type": "java.lang.String",
    "sourceType": "io.pivotal.ConfigPropsLombok"
  }]
}
```

This is using Java 8u65 & IntelliJ 15 (IU 143.381)

**Comment by CalamarBicefalo** [comment]
Have a repro case for this if needed.

**Comment by sthzg** [comment]
@CalamarBicefalo in your case, does it work with regular getters / setters? I am facing the same problem in `1.3.0.RC1`, but changing from Lombok to getters / setters does not change the generated file in my case.

**Comment by snicoll** [comment]
@sthzg looks like unrelated to this issue. If the `NestedProperty` is not an inner class, you need to annotated the field with `@NestedConfigurationProperty` to let the meta-data processor that it shouldn't consider that field as a scalar value. If you're having an issue without Lombok, I'd create a separate issue.

**Comment by sthzg** [comment]
@snicoll thanks for your reply, I will try to recreate it on a fresh setup and report a new issue if I can recreate it there.

**Comment by CalamarBicefalo** [comment]
Indeed, @sthzg, it is working with getter and setters in 1.3.0.RC1.I think @snicoll is right. I tried nested public static classes and it works fine for me, haven't tried external classes though.

**Comment by sthzg** [comment]
@CalamarBicefalo the getters/setters not working for me were because of an error on my side. thanks for checking and sorry for the noise.
