### ISSUE TITLE
EndpointHandlerMapping could enforce some rules about path matching with extensions

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4402]
`EndpointHandlerMapping` extends `RequestMappingHandlerMapping` and so inherits a lot of its behaviour, including the default of matching all paths after removing file extensions. This means that (for example) /trace and /trace.exe both match the trace endpoint (bad idea and we really don't need the second match at all). See https://jira.spring.io/browse/SPR-13587 for background chat.

**Comment by dsyer** [comment]
Re-opened because if we are going to make a change we might as well make one that works (the flag in 09b5222 is ignored).

**Comment by philwebb** [comment]
Why is the flag ignored?

**Comment by dsyer** [comment]
Because we create our own `PatternsRequestCondition` and don't use the value.
