### ISSUE TITLE
Make spring.resource.chain.enabled=true by default if webjars-locator is present

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4403]
We probably should make `spring.resource.chain.enabled=true` by default if webjars-locator is present (if it's there then obviously there has to be a resource chain for it to be doing anything).

**Comment by snicoll** [comment]
@wilkinsona suggested to split the auto-configuration that uses the boolean flag so that we can use `@ConditionalOnResoureChain` as well. That would leave with an "incomplete" boolean attribute that we could document (or maybe the whole enabled business should go in the condition implementation)
