### ISSUE TITLE
Gradle force downgrading hibernate with 1.3.0.RC1

### ISSUE THREAD

**Issue by ethankhall** [spring-projects/spring-boot#4410]
I am trying to use hibernate in my project and am using 5.0.1 and everything working as expected. When I tried to upgrade to 1.3.0.RC1 the plugin is forcing hibernate down to 4.3.11.Final and it's causing issues with app when running.

Here is `gradle dI --configuration compile --dependency hibernate-core` using 1.2.7.RELEASE
```
:web-service:webapp:dependencyInsight
org.hibernate:hibernate-core:5.0.1.Final
+--- org.hibernate:hibernate-entitymanager:5.0.1.Final
|    +--- compile
|    +--- project :web-service:database
|    |    \--- compile
|    \--- org.springframework.boot:spring-boot-starter-data-jpa:1.2.7.RELEASE
|         \--- project :web-service:database (*)
\--- org.hibernate:hibernate-java8:5.0.1.Final
     +--- compile
     \--- project :web-service:database (*)
```

Here is `gradle dI --configuration compile --dependency hibernate-core` using 1.3.0.RC1
```
:web-service:webapp:dependencyInsight
org.hibernate:hibernate-core:4.3.11.Final (selected by rule)

org.hibernate:hibernate-core:5.0.1.Final -> 4.3.11.Final
+--- org.hibernate:hibernate-entitymanager:5.0.1.Final
|    +--- compile
|    +--- project :web-service:database
|    |    \--- compile
|    \--- org.springframework.boot:spring-boot-starter-data-jpa:1.3.0.RC1
|         \--- project :web-service:database (*)
\--- org.hibernate:hibernate-java8:5.0.1.Final
     +--- compile
     \--- project :web-service:database (*)
```

Between those two runs the only change I did was change the plugin version.

**Comment by wilkinsona** [comment]
That's by design. Spring Boot's dependency management with Gradle is now more closely aligned to how things work with Maven. If you want to use Hibernate 5, then you should override the `hibernate.version` property as [described here](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-dependency-versions).

**Comment by ethankhall** [comment]
Can you add it to the release notes before the release? I scanned the documentation before I made the issue and it didn't jump out.
