### ISSUE TITLE
Cannot serve PDF documents correctly in 1.3.0.RC1 

### ISSUE THREAD

**Issue by MikeBull94** [spring-projects/spring-boot#4412]
I am using the following mapping to serve a PDF document from a repository. In 1.3.0.M5 this works perfectly fine (serves them as the correct `application/pdf` content type and allows viewing of the file in a browser), however in 1.3.0.RC1 files are being incorrect served with a content type of `text` and being downloaded to the user's file system as `f.txt`.

Using `wget` on the resource in 1.3.0.RC1 fetches it correctly (downloads as type `application/pdf` with the correct file name) but attempting to visit the link in a browser (tested in both Firefox & Chrome) does not (downloads as type `text` with file name `f.txt`).

```java
	@ResponseBody
	@RequestMapping(path = "/articles/{alias}", method = RequestMethod.GET, produces = "application/pdf")
	public byte[] pdf(@PathVariable("alias") String alias) throws IOException {
		return repository.findByAlias(alias).orElseThrow(NoSuchEntityException::new).getPdf().read();
	}
```

**Comment by snicoll** [comment]
Duplicates #4220
