### ISSUE TITLE
Clearly document the limitations of @Value with respect to relaxed binding

### ISSUE THREAD

**Issue by johanhaleby** [spring-projects/spring-boot#4413]
Suppose I have a property like this:

```java
@Value("${something.with-dash}")
private String mySomething;
```

It's hard to make Spring map hyphens like `with-dash` from an environment variable. Let's say I've built my spring onejar then I can't just provide an environment variable like this (bash):

```bash
$ SOMETHING_WITH-DASH=Something java -jar my-spring-onejar.jar
```

You need to use a work-around like this:

```bash
$ env 'SOMETHING_WITH-DASH=Something' java -jar my-spring-onejar.jar
```

But in certain frameworks such as [Kubernetes](https://github.com/kubernetes/kubernetes) you cannot use a hyphen in environment variables since they use the C_IDENTIFIER format as the lowest common denominator. I've aded an [issue](https://github.com/kubernetes/kubernetes/issues/16863) for this in Kubernetes but I'm not sure if they're willing to change it. 

So I wonder if instead Spring could enhance its way that hyphens are treated in environment variables when matching the `@Value` annotation? For example if `SOMETHING_WITH_DASH` could map to `something.with-dash`?

**Comment by snicoll** [comment]
Are you aware that [we are already supporting this with `@ConfigurationProperties`](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding)? I'd argue that it [is far more superior than the basic `@Value` approach](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) so you might just as well give that a try. `@Value` is a core framework feature and the _relaxed_ binding is not available there.

**Comment by johanhaleby** [comment]
Hmm I think at least some of the relaxed binding properties work for `@Value` as well. But why shouldn't the same relaxed binding properties work for both `@ConfigurationProperties` and `@Value`?

**Comment by snicoll** [comment]
Yes, there are some basic relaxed binding in the core framework as well. 

Advanced relaxed binding is a spring boot feature and is quite opinionated so it does not belong in the core framework IMO. `@Value` is a core framework feature. I think we could improve the core feature (to some extend) but regardless of that I'd *strongly* advice not to use `@Value` with Spring Boot as a better solution exists already (see link in my first answer).

WDYT @dsyer @wilkinsona ?

**Comment by johanhaleby** [comment]
Ah I see. Perhaps the documentation can be even more clear that the same rules/properties does not apply to the `@Value` annotation since it's in core? I think that for a casual user like myself it can be a bit confusing to have a different set of rules for relaxed binding. It's sometimes hard to know what's in "core" and what's in "spring boot" since you typically just include a `spring-boot-starter-x` in your pom/build.gradle file. But I do understand that you want to have a clean separation between core and boot as well.

**Comment by snicoll** [comment]
> You need to use a work-around like this:

I've just built a small example with `SOMETHING_WITH-DASH` and your code above with `@Value` breaks for me.

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'something.with-dash' in string value "${something.with-dash}"```

On a second though and checking the core framework again we don't have any such transformation of the key. I am busy documenting the differences between `@Value` and `@ConfigurationProperties` in #4892 anyway
