### ISSUE TITLE
JCache with Infinispan doesnt work

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#4418]
Hi,

When I create the infinispan.xml file in my resources directory, and specify `spring.cache.infinispan.config=infinispan.xml` the code doesnt work when packaged as jar (I'm using Infinispan 7.2.5) because the below code gets invoked from `org.infinispan.commons.util.AbstractFileLookup`.

	   @Override
	   public InputStream lookupFileStrict(URI uri, ClassLoader cl) throws FileNotFoundException {
		  return new FileInputStream(new File(uri));
	   }

This is because Spring Boot passes the URI. But, Infinispan doesnt use the classloader to load from URI.

If I create an override as below, it works

		@Override
		public InputStream lookupFileStrict(URI uri, ClassLoader cl) throws FileNotFoundException {
			return lookupFileStrict("infinispan.xml",cl);
		   /* return new FileInputStream(new File(uri));*/
		}

So, either Spring Boot would have to just pass the filename instead of URI, along with the classLoader or there must be a bug Infinispan which would have it use the classloader for URI.

**Comment by snicoll** [comment]
I don't get it. If you set this property [we're passing an `Inpustream` to infinispan](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/InfinispanCacheConfiguration.java#L83). Since you have debugged that already, what code path in Spring Boot leads to this call exactly?

**Comment by tollrakesh** [comment]
The code you are referring doesnt get invoked. It rather uses the JCache provided by Infinispan

Below are the beans

	{
		  "bean" : "org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration",
		  "scope" : "singleton",
		  "type" : "org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$31ae4305",
		  "resource" : "null",
		  "dependencies" : [ "spring.cache.CONFIGURATION_PROPERTIES" ]
		}, {
		  "bean" : "cacheManager",
		  "scope" : "singleton",
		  "type" : "org.springframework.cache.jcache.JCacheCacheManager",
		  "resource" : "class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]",
		  "dependencies" : [ "jCacheCacheManager" ]
		}, {
		  "bean" : "jCacheCacheManager",
		  "scope" : "singleton",
		  "type" : "org.infinispan.jcache.embedded.JCacheManager",
		  "resource" : "class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]",
		  "dependencies" : [ ]
		}, {
		  "bean" : "org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration",
		  "scope" : "singleton",
		  "type" : "org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$$EnhancerBySpringCGLIB$$2b8bfc3e",
		  "resource" : "null",
		  "dependencies" : [ ]
		}, {
		  "bean" : "cacheAutoConfigurationValidator",
		  "scope" : "singleton",
		  "type" : "org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheManagerValidator",
		  "resource" : "class path resource [org/springframework/boot/autoconfigure/cache/CacheAutoConfiguration.class]",
		  "dependencies" : [ "spring.cache.CONFIGURATION_PROPERTIES", "cacheManager" ]
		}, {
		  "bean" : "spring.cache.CONFIGURATION_PROPERTIES",
		  "scope" : "singleton",
		  "type" : "org.springframework.boot.autoconfigure.cache.CacheProperties",
		  "resource" : "null",
		  "dependencies" : [ ]
		}, {
		  "bean" : "org.springframework.boot.actuate.autoconfigure.CacheStatisticsAutoConfiguration$NoOpCacheStatisticsConfiguration",
		  "scope" : "singleton",
		  "type" : "org.springframework.boot.actuate.autoconfigure.CacheStatisticsAutoConfiguration$NoOpCacheStatisticsConfiguration$$EnhancerBySpringCGLIB$$6e0e480b",
		  "resource" : "null",
		  "dependencies" : [ ]
		}


Below is the dependency list from my build.gradle (infinispanVersion = 7.2.5)

		compile("org.infinispan:infinispan-core:$infinispanVersion")
		compile("org.infinispan:infinispan-query:$infinispanVersion")
		compile("org.infinispan:infinispan-jcache:$infinispanVersion")

**Comment by snicoll** [comment]
Ah, JCache I see, thanks. well I am using what the spec tells me to do (I think) so I am not sure I could do anything about it, really. I'll have a look at the API and how I could eventually workaround it

Your key is useless then, the JCache support is kicking in so it only reads `spring.cache.jcache.*`

Can you maybe add `spring.cache.type=infinispan` to your config to force the native support rather than the JSR-107 one?

**Comment by tollrakesh** [comment]
The key `spring.cache.infinispan.config=infinispan.xml` doesnt take a path to the file either. I will give `spring.cache.type=infinispan` a spin and let you know how it goes..

**Comment by tollrakesh** [comment]
Adding `spring.cache.type=infinispan` does resolve the issue (After adding infinispan-spring4 module on build.gradle). But, it isnt an ideal fix bcoz of three reasons:
1. I was planning to have a JCache based implementation.
2. After switching to EmbeddedCacheManager, the JMX statistics dont appear under the right hierarchy (But they still show up under cachenames, as a concatenated string).
3. I'm also using Infinispan as Hibernate's Second Level Cache provider. There seems to be a conflict here which might eventually lead to two config files (Not sure, need to investigate).

**Comment by snicoll** [comment]
It wasn't a long term solution but just to prove that Spring Boot is calling the proper API. If Infinispan is not using the proper classloader, I guess a fix there is in order. As I said, I'll have a look at the API and how I could eventually workaround it.

**Comment by snicoll** [comment]
I don't see any way to workaround that at this point and I've created [an Infinispan issue for you](https://issues.jboss.org/browse/ISPN-5949)
