### ISSUE TITLE
[v1.2.7.RELEASE] spring.profiles.active can not refer back to previously defined values in same deafult properties file

### ISSUE THREAD

**Issue by Robin7Ma** [spring-projects/spring-boot#4422]
Spring Boot Version: 1.2.7.RELEASE

``spring.profiles.active`` can not refer back to previously defined values in same deafult properties file.

e.g. 
1. application.properties
```properties
something.type=type1
spring.profiles.active=${something.type}
```

2. Type1Configuration:
```java
@Profile("type1")
@Configuration
public class Type1Configuration {
	@Bean
	@Primary
	public Service service() {
		return new Type1Service();
	}
}

```

When startup, Spring cant not find the bean of type [``Service``] define in ``Type1Configuration``,
But when set the environment to override ``something.type`` before start up the executable jar, It works:

```cmd
set SOMETHING_TYPE=type1
java -jar myapp.jar
```

**Comment by philwebb** [comment]
This is a known limitation of the processing logic. It's not possible for us to refer to a property in the same file because it's not get been processed when the property is parsed.
