### ISSUE TITLE
Spring boot is truncating cookie values at the first '=' character

### ISSUE THREAD

**Issue by mtessler-fmcc** [spring-projects/spring-boot#4425]
When a cookie value is submitted to a rest controller, the value is truncated at the first '=' character.
for example, if I have a cookie: named fooCookie with the value "a==4=2==1" then the cookie value passed to the rest controller is "a".
This causes problems when base-64 values are submitted as cookie values.

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value="/sampleGet", method=RequestMethod.GET)
    public String cookieProcess(@CookieValue(value="fooCookie", required=false) String fooCookie, HttpServletRequest request) {
        //At this point fooCookie is truncated 
        for (Cookie cookie : request.getCookies()) {
            if (cookie.getName().equals("fooCookie")) {`
                //this cookie value is truncated as well`
        }
    }

**Comment by philwebb** [comment]
Spring Boot isn't directly processing cookies so this is a Servlet container issue. Assuming you're using Tomcat you might want to look at this: http://thenitai.com/2013/05/02/tomcat-truncating-cookies-with-values/.

I'd recommend not using `=` characters inside your cookie values if at all possible.

**Comment by rjain15** [comment]
How do set the tc server properties in cf (buildpack). 

org.apache.tomcat.util.http.ServerCookie.ALLOW_EQUALS_IN_VALUE=true
org.apache.tomcat.util.http.ServerCookie.ALLOW_HTTP_SEPARATORS_IN_V0=true

**Comment by philwebb** [comment]
I don't know, you'd have to ask them,

**Comment by philwebb** [comment]
Or try asking on stackoverflow.com
