### ISSUE TITLE
Permit to configure the Cassandra cluster credentials (user/password) 

### ISSUE THREAD

**Issue by cornelcreanga** [spring-projects/spring-boot#4431]
Right now there is no way to configure the user/password in case you want to connect to a Cassandra cluster using `PlainTextAuthProvider`. The missing properties should be added in  `org.springframework.boot.autoconfigure.cassandra.CassandraProperties` and used inside  `CassandraAutoConfiguration`.

**Comment by cornelcreanga** [comment]
see https://github.com/spring-projects/spring-boot/pull/4432

**Comment by philwebb** [comment]
Thanks, have you signed the CLA?

**Comment by cornelcreanga** [comment]
welcome. yes - confirmation number 111620150306032554.
