### ISSUE TITLE
Support JWK Set responses in spring.oauth2.resource.jwt.keyUri

### ISSUE THREAD

**Issue by william-tran** [spring-projects/spring-boot#4437]
Moved from https://github.com/spring-cloud/spring-cloud-security/issues/76

This is a standard response defined by RFC-7517 and though UAA's /token_key endpoint doesn't emit its key in this format (edit: as of UAA 2.6.1 it does this with /token_keys) Google does: https://www.googleapis.com/oauth2/v3/certs. We should support the standard but keep existing behaviour for backwards compatibility.

**Comment by sdoxsee** [comment]
@william-tran agree this would be nice. +1

**Comment by ncouse** [comment]
I think this is critical to support OpenID Connect. The JWK endpoint will (as in Google's case) report multiple keys.

Looking at the code though, there would also be changes to spring-security-oauth and spring-security-jwt, as these do not support multiple keys, and the encoding algorithm seems to be hardcoded. Also the verify mechanism does not seem to look the kid, to decide which key to verify against.

I think for a scalable system, proper JWT support is necessary, to avoid introspection.

In theory the auth server should be able to change keys, so there would be some mechanism needed to re-read keys also.

**Comment by ohr** [comment]
+1
For the time being I worked around this by obtaining the JWK Set and converting the first JWK into a PEM public key as expected by the JwtAccessTokenConverter. I used http://connect2id.com/products/nimbus-jose-jwt for this (ASL2). Note that this lib can also re-read the keys (RemoteJWKSet).

As said before, the core issues would have to be addressed in spring-security-oauth and spring-security-jwt. Somehow related, I found [#865](https://github.com/spring-projects/spring-security-oauth/issues/865) there.

**Comment by william-tran** [comment]
Bump, this is going to be a requirement for PWS, whose UAA will be rotating keys no sooner than Jan 20th: https://github.com/cf-tm-bot/capi/issues/696

**Comment by jgrandja** [comment]
@william-tran @mbhave Can you please confirm the JWT issued by UAA uses the Header Parameter `kid` _(Key ID)_ for correlating the PK used for verification in the `/token_keys` endpoint?

**Comment by mbhave** [comment]
@jgrandja yes, the `kid` in the token header can be used for looking up the key value from the `/token_keys` endpoint.

**Comment by jgrandja** [comment]
This issue has been addressed with a new `TokenStore` implementation supporting JWK.
See [gh-977](https://github.com/spring-projects/spring-security-oauth/issues/977)
