### ISSUE TITLE
@RestControllerAdvice

### ISSUE THREAD

**Issue by pkafel** [spring-projects/spring-boot#4439]
Hey Spring folks,

I would like to propose really small enhancement but maybe you will find it worth spending a moment. 

In the same way `@RestController` removed a need to add to every method `@ResponseBody` maybe it would be worth to add `@RestControllerAdvice` ? This should be pretty easy to do. The motivation for this is that every Spring project (that is exposing REST API) I've seen so far always uses `@ControllerAdvice` with combination with `@ResponseBody`...

**Comment by philwebb** [comment]
Seems like a sensible addition but it should probably be handled in Spring Framework rather than Spring Boot (since the `@RestController` annotation is there). 

I've raised [SPR-13673](https://jira.spring.io/browse/SPR-13673), please track that issue for updates.
