### ISSUE TITLE
Support error-code.html convention

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4441]
It would be nice if you could map error codes to views or static pages using conventions. 

e.g.

`/src/main/resources/static/error/404.html` implies automatic mapping for 404 codes.

**Comment by snicoll** [comment]
Sagan already kind of does that so maybe we can poke in that codebase for inspiration (cc @bclozel)

**Comment by chrylis** [comment]
I have an entire Groovy class that does nothing but collect the available pages and register them specifically to do this.

+2

**Comment by philwebb** [comment]
Duplicates #2691
