### ISSUE TITLE
Add "auto-configured" flag to actuator /beans

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4442]
Although we have the auto-configuration report, it would be nice if actuators `/beans` showed when a bean definition was the result of an auto-configure.

**Comment by philwebb** [comment]
Actually this seems of relatively little value. Looking for `.autoconfigure.` in the `type` is enough to tell where the bean comes from.

**Comment by spencergibb** [comment]
For boot classes, yes. But not for others

**Comment by philwebb** [comment]
I think this issue predates the auto-configuration report which should hopefully provide enough details. There hasn't been a strong demand for this so I'm going to close it.
