### ISSUE TITLE
Misleading documentation about `<springProfile>` with multiple profile names

### ISSUE THREAD

**Issue by occho** [spring-projects/spring-boot#4445]
The line below separates two profile names with comma and space.
https://github.com/spring-projects/spring-boot/commit/9f9f21207f5454f6761fd0d4331e8927579a7990#diff-7b7c6a9ef59628a2f86e46445d4ca79bR1086

However, in that example, active profile of `staging` will not be caught by the if-clause.
That is because the following function doesn't care spaces.
https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/logback/SpringProfileAction.java#L69

**Comment by philwebb** [comment]
Fixed in bd709f30c5686d396b53ed2247ef4c52f0a53836
