### ISSUE TITLE
Servlet Filters not Processed Correctly

### ISSUE THREAD

**Issue by kenwdelong** [spring-projects/spring-boot#4450]
When I create a bean in Spring Boot using FilterRegistrationBean, it does not get processed correctly by the container.

For example, with a filter defined like so:

	@Bean
	public FilterRegistrationBean requestInfoFilter()
	{
		FilterRegistrationBean registration = new FilterRegistrationBean();
		RequestInfoFilter filter = new RequestInfoFilter();
		registration.setFilter(filter);
		registration.setName("requestInfoFilter");
		registration.setDispatcherTypes(EnumSet.of(DispatcherType.REQUEST));
		registration.addUrlPatterns("/*");
		registration.setOrder(Ordered.HIGHEST_PRECEDENCE + 1);
		return registration;
	}

The RequestInfoFilter does not have it's attributes Autowired.  However, if you just do this:

	@Bean
	public RequestInfoFilter requestInfoFilter()
	{
		RequestInfoFilter filter = new RequestInfoFilter();
		return filter;
	}

then the Autowiring is done correctly.  However, now one cannot control the ordering. If you add @Ordered annotation to the method, it is ignored.

Similarly, if you have a Filter bean that is a JMX @ManagedResource, it does not get registered into the MBean server. If you create a simple bean, like above, then it is correctly exported into JMX - but again, you cannot control the order.

I need to be able to control the order of my filters, but also have them processed correctly by the container.

Using Boot 1.2.7, Java 8_51

**Comment by philwebb** [comment]
You can't add `@Ordered` to `@Bean` methods, however, If you control `RequestInfoFilter` you should be able to annotate directly:

```java
@Ordered(...)
public class RegestInfoFilter implements Filter {
    //...
}
```

You can also use `FilterRegistrationBean` in combination with other `@Bean` methods:

```java
@Bean
public FilterRegistrationBean requestInfoFilter()
{
    FilterRegistrationBean registration = new FilterRegistrationBean();
    registration.setFilter(requestInfoFilter());
    registration.setName("requestInfoFilter");
    registration.setDispatcherTypes(EnumSet.of(DispatcherType.REQUEST));
    registration.addUrlPatterns("/*");
    registration.setOrder(Ordered.HIGHEST_PRECEDENCE + 1);
    return registration;
}

@Bean
public RequestInfoFilter requestInfoFilter()
{
    RequestInfoFilter filter = new RequestInfoFilter();
    return filter;
}
```
