### ISSUE TITLE
Add WLS integration test

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4452]
We probably can't run it as part of the main build, but it would be very useful if we had a WLS integration test in the same way as we have tests for Wildfly, Payara and TomeEE.

**Comment by snicoll** [comment]
The problem is that we either need to have a copy of WLS installed somewhere or we should install the server in some private repository (making it hard for anyone to run this)

[this page](https://developer.ibm.com/wasdev/docs/maven/) has some tips and tricks.

**Comment by philwebb** [comment]
Yeah, this would need to be internal. Probably a different repo and CI job that's triggered from an upstream build.

**Comment by snicoll** [comment]
I just realized that I was referring to Websphere Liberty Profile (WLS) and not Weblogic. Ignore me :)

**Comment by asaikali** [comment]
There is a CloudFoundry WebLogic Buildpack its a hack but it will let you do cf push see details at https://github.com/pivotal-cf/weblogic-buildpack cloud a be a good compromise for being able to run the integration test on a regular basis.

**Comment by wilkinsona** [comment]
@asaikali Thanks, but that doesn't help. You still need to [download the WebLogic binary from somewhere](https://github.com/pivotal-cf/weblogic-buildpack/blob/master/docs/container-wls.md#requirements).

**Comment by davidkarlsen** [comment]
https://www.ibm.com/support/knowledgecenter/SS8PJ7_9.1.1/com.ibm.etools.maven.doc/topics/localrepo.html might come in handy - you can run in as a maven plugin, or add code and run embedded afaik.

**Comment by philwebb** [comment]
Given we don't easily have a way to get WLS and it appears that only a relatively small number of our users deploy Boot apps to it I'm going to close this one.
