### ISSUE TITLE
FilterRegistrationBean set invalid DispatcherTypes by default

### ISSUE THREAD

**Issue by 9you** [spring-projects/spring-boot#4462]
Class `org.apache.tomcat.util.descriptor.web.FilterMap` indicate that a filter's `dispatcherMapping` value is default to `REQUEST` if not set. But `FilterRegistrationBean` will set this value to `FilterRegistrationBean.ASYNC_DISPATCHER_TYPES` or `FilterRegistrationBean.NON_ASYNC_DISPATCHER_TYPES` if not specify. This cause me a trouble since `FORWARD` request such as render JSP view will be passed to `springSecurityFilterChain` again and it fail. I think we shoud make `FilterRegistrationBean` register filters same as we declare filters in web.xml.

    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.DispatcherServlet - DispatcherServlet with name 'dispatcherServlet' processing GET request for [/500]
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.handler.AbstractHandlerMethodMapping - Looking up handler method for path /500
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.handler.AbstractHandlerMethodMapping - Did not find handler method for [/500]
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.handler.AbstractHandlerMethodMapping - Looking up handler method for path /500
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.handler.AbstractHandlerMethodMapping - Returning handler method [public org.springframework.web.servlet.ModelAndView com.thanh.rest.Home.get500Page()]
    13.11.2015 19:06:48 DEBUG org.springframework.beans.factory.support.AbstractBeanFactory - Returning cached instance of singleton bean 'home'
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.DispatcherServlet - Last-Modified value for [/500] is: -1
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.view.ContentNegotiatingViewResolver - Requested media types are [text/html, application/xhtml+xml, image/webp, application/xml;q=0.9, */*;q=0.8] based on Accept header types and producible media types [*/*])
    13.11.2015 19:06:48 DEBUG org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory - Invoking afterPropertiesSet() on bean with name '500'
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.view.ContentNegotiatingViewResolver - Returning [org.springframework.web.servlet.view.JstlView: name '500'; URL [/WEB-INF/jsp/500.jsp]] based on requested media type 'text/html'
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.JstlView: name '500'; URL [/WEB-INF/jsp/500.jsp]] in DispatcherServlet with name 'dispatcherServlet'
    13.11.2015 19:06:48 DEBUG org.springframework.beans.factory.support.AbstractBeanFactory - Returning cached instance of singleton bean 'requestDataValueProcessor'
    13.11.2015 19:06:48 DEBUG org.springframework.web.servlet.view.InternalResourceView - Forwarding to resource [/WEB-INF/jsp/500.jsp] in InternalResourceView '500'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/web-inf/jsp/500.jsp'; against '/css/**'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/web-inf/jsp/500.jsp'; against '/js/**'
    ...
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.util.matcher.OrRequestMatcher - No matches found
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 1 of 14 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 2 of 14 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - No HttpSession currently exists
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: null. A new one will be created.
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 3 of 14 in additional filter chain; firing Filter: 'HeaderWriterFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.header.writers.HstsHeaderWriter - Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@19a2be89
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 4 of 14 in additional filter chain; firing Filter: 'CsrfFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 5 of 14 in additional filter chain; firing Filter: 'LogoutFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Request 'GET /web-inf/jsp/500.jsp' doesn't match 'POST /logout
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 6 of 14 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Request 'GET /web-inf/jsp/500.jsp' doesn't match 'POST /login
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 7 of 14 in additional filter chain; firing Filter: 'DefaultLoginPageGeneratingFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 8 of 14 in additional filter chain; firing Filter: 'BasicAuthenticationFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 9 of 14 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 10 of 14 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 11 of 14 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.authentication.AnonymousAuthenticationFilter - Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@9055c2bc: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 12 of 14 in additional filter chain; firing Filter: 'SessionManagementFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.session.SessionManagementFilter - Requested session ID 6A0A965A2F1D4A114DC63DA031056CFE is invalid.
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 13 of 14 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.FilterChainProxy$VirtualFilterChain - /WEB-INF/jsp/500.jsp at position 14 of 14 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
    13.11.2015 19:06:52 DEBUG org.springframework.security.access.intercept.AbstractSecurityInterceptor - Secure object: FilterInvocation: URL: /WEB-INF/jsp/500.jsp; Attributes: [authenticated]
    13.11.2015 19:06:52 DEBUG org.springframework.security.access.intercept.AbstractSecurityInterceptor - Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@9055c2bc: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
    13.11.2015 19:06:52 DEBUG org.springframework.security.access.vote.AffirmativeBased - Voter: org.springframework.security.web.access.expression.WebExpressionVoter@5899d4af, returned: -1
    13.11.2015 19:06:52 DEBUG org.springframework.beans.factory.support.AbstractBeanFactory - Returning cached instance of singleton bean 'authorizationAuditListener'
    13.11.2015 19:06:52 DEBUG org.springframework.beans.factory.support.AbstractBeanFactory - Returning cached instance of singleton bean 'delegatingApplicationListener'
    13.11.2015 19:06:52 DEBUG org.springframework.beans.factory.support.AbstractBeanFactory - Returning cached instance of singleton bean 'auditListener'
    13.11.2015 19:06:52 INFO  org.springframework.boot.actuate.audit.listener.AuditListener - AuditEvent [timestamp=Fri Nov 13 19:06:52 ICT 2015, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
    13.11.2015 19:06:52 DEBUG org.springframework.security.web.access.ExceptionTranslationFilter - Access is denied (user is anonymous); redirecting to authentication entry point
    org.springframework.security.access.AccessDeniedException: Access is denied

**Comment by philwebb** [comment]
I don't want to change the default for `FilterRegistrationBean`, this will break back compatibility. The `FilterRegistrationBean` Javadoc does indicate that this is expected behavior.

If you want to override the registration bean for your use-case use `FilterRegistrationBean.setDispatcherTypes(...)`.
