### ISSUE TITLE
Request: managed jackson-datatype-guava dependency

### ISSUE THREAD

**Issue by Shredder121** [spring-projects/spring-boot#4490]
It would be nice to (1) add a managed version of the `jackson-datatype-guava` dependency, and maybe (2) some autoconfiguration.

- [ ] add version
- [ ] add autoconfiguration

**Comment by Shredder121** [comment]
It's very clearly an [`enhancement`].

**Comment by philwebb** [comment]
As a general rule we've been trying to avoid adding Guava as a managed dependency. Unfortunately it has a habit of not retaining back compatibility between releases which makes things very hard for us to manage.

**Comment by Shredder121** [comment]
Oh, that's a shame.
I only noticed with adding `jackson-datatype-*` dependencies that all (`jsr310`, `jdk8`) were managed, and the `guava` one wasn't.
Also, the registering now looks like this in my `Module`:

```java
@Override
public void setupModule(SetupContext context) {
    super.setupModule(context);
    // https://github.com/spring-projects/spring-boot/issues/4490
    new GuavaModule().setupModule(context);
}
```

So it feels a little hacky, much less beautiful than adding it to the classpath and done.

(This module follows the same numbering as the main jackson modules).

**Comment by Shredder121** [comment]
You can close it if you're not resolving it, I understand.

**Comment by philwebb** [comment]
I'll let the rest of the team have a say before I close it. @wilkinsona manages the platform so he has the most interest.

**Comment by Shredder121** [comment]
Just noticed that the spring.io platform BOM [does have a managed Guava version](https://github.com/spring-io/platform/blob/master/platform-bom/pom.xml#L344-L348).

But we'll wait for @wilkinsona to chime in.
It would at least help if just the autoconfiguration was added.

N.B. I couldn't quite think of a way to not have Guava in the dependencies (optional, excluded) and then still have a way to make it compile, so I think it would need to be instantiated via reflection and then just declared as a `Module`.

**Comment by wilkinsona** [comment]
I would dearly love the Platform not to have a managed Guava version, but it needs to be there as it's an optional dependency of Spring Framework.

Boot itself actually already has a dependency on Guava, but we've [deliberately hidden the dependency management](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RELEASE/spring-boot-parent/pom.xml#L45-L49). If we can do the same here (I see no reason why not) and leave the fool's errand of finding a version of Guava that works with all of an application's dependencies as an exercise for the user, I don't have any strong objections to adding this.

**Comment by Shredder121** [comment]
Yes, I know my way around `dependency-tree`, `effective-pom`, so I also see no issue.

It _might_ help to at least put a notice up / mention in the documentation that the version of Guava then isn't really a hard dependency, or does that sound stupid?

**Comment by Shredder121** [comment]
Just wondering, will there also be autoconfiguration for the module?

**Comment by snicoll** [comment]
Nope. That's request for dependency management and that's as far as we want to go regarding Guava.

**Comment by Shredder121** [comment]
Fair enough, thank you very much though!
