### ISSUE TITLE
Typo in Wiki page 'Spring-Boot-1.3-Release-Notes'

### ISSUE THREAD

**Issue by af-not-found** [spring-projects/spring-boot#4494]
I found a typo in the following Wiki page.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes

'Miscellaneous' section, 
wrong : spring.devtools.devtools.proxy.*
right : spring.devtools.remote.proxy.*

**Comment by snicoll** [comment]
Good catch, thanks.
