### ISSUE TITLE
DispatcherType for SecurityFilterAutoConfiguration 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#4505]
I am migrating our codebase to Spring 1.3 and I am trying to remove all duplicated parts as much as possible. The default dispatcher type for registration beans is defaulted to

```
	static final EnumSet<DispatcherType> ASYNC_DISPATCHER_TYPES = EnumSet.of(
			DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST,
			DispatcherType.ASYNC);

	static final EnumSet<DispatcherType> NON_ASYNC_DISPATCHER_TYPES = EnumSet
			.of(DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST)
```

But in our JSP project I am overwriting dispatcher types for Spring Security to `DispatcherType.REQUEST, DispatcherType.ERROR`. What is the proper dispatcher types for a Spring Security Application?  Is it a good idea to add options for dispatcher types in `securityProperties`?

ping @rwinch

**Comment by rwinch** [comment]
@cemo Thanks for the report!

I don't know that there is a "right" answer as users will likely have different requirements to this. I think the most common scenario would be `REQUEST`, `ERROR`, and `ASYNC`. That said, we should likely update our default configuration to reflect his.

> What is the proper dispatcher types for a Spring Security Application? Is it a good idea to add options for dispatcher types in securityProperties?

I think adding security properties configuration for this might be a bit much, but this might be better for the Spring Boot team to answer. You should be able to customize this with a single bean definition. For example, in Boot 1.3+ you can do something like this:

```java
@Bean
@ConditionalOnBean(name = DEFAULT_FILTER_NAME)
public DelegatingFilterProxyRegistrationBean securityFilterChainRegistration(
		SecurityProperties securityProperties) {
	DelegatingFilterProxyRegistrationBean registration = new DelegatingFilterProxyRegistrationBean(
			DEFAULT_FILTER_NAME);
	registration.setOrder(securityProperties.getFilterOrder());
	registration.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ERROR,
				DispatcherType.ASYNC);
	return registration;
}
```

**Comment by cemo** [comment]
Thanks @rwinch. I had already done an implementation as you suggested. However In our case I am trying to remove unnecessary auto configurations which seems good a candidate. What I do not like  about this configuration is that I have to overwrite `autoconfigurations` in many many places. I prefer sensible defaults and best practices. Current implementation made me think that I am making something wrong. Thanks for clarification. 

Do you think that this configuration is buggy? I am asking this because a user can easily has performance issue in a project using `DispatcherType.INCLUDE` such as JSP projects. Each INCLUDE request is causing another request in Spring Security Filter Chain. What do you think?

**Comment by philwebb** [comment]
After some discussion I think we'll add a property to configure this in 1.3.1. We don't really want to change the defaults in a maintenance release so we'll open a new issue to address this in 1.4.

**Comment by wilkinsona** [comment]
Reopening as the change I made breaks applications that use Spring Security but do not have the servlet API on the classpath.

**Comment by php-coder** [comment]
Maybe we should mention about this property in migration guide/configuration changelog?

**Comment by php-coder** [comment]
Also I think that the documentation also could be updated: http://docs.spring.io/spring-boot/docs/1.3.6.RELEASE/reference/htmlsingle/#boot-features-error-handling
