### ISSUE TITLE
ConditionalOnDevelopment 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#4507]
@philwebb  Please finish your experimental work in https://github.com/spring-projects/spring-boot/issues/296  :) 

I have dummy implementation which is specialised for our workflow. I am checking classpath resource count which is pretty big for development environment because of working in multi module exploded environment in IDE.

**Comment by linux-china** [comment]
+1. @ConditionalOnDevelopment  for devtools enabled.

**Comment by snicoll** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
