### ISSUE TITLE
Changed behavior of maven failsafe plugin 2.19

### ISSUE THREAD

**Issue by kreyssel** [spring-projects/spring-boot#4510]
Today I tried to switch my project to `maven-failsafe-plugin` 2.19.  My project is a simple spring-boot SPA (it use `starter-web`, `starter-thymeleaf`, `starter-data-rest`, `starter-data-jpa`) with java 8 and maven to build.

I have a few unit and integration tests. At build time the unit tests are executed via `maven-surefire-plugin` and integration tests are executed via `maven-failsafe-plugin`.

After the switch I struggling on massive increase of time to finish the integration tests (unit tests are fine). After some investigations I detect the difference between `maven-failsafe-plugin` 2.18.1 and 2.19.

Up to 2.18.1 the boot classpath for running the tests use the `target/classes` and `target/test-classes` folder. In 2.19 the boot classpath use the attached artifact jar (see [SUREFIRE-855](https://issues.apache.org/jira/browse/SUREFIRE-855) and https://github.com/apache/maven-surefire/commit/0eb85f7a2f971968a9293307616818a0d85f2ee8).

And now we need to look at the `spring-boot-maven-plugin`. It repackaged by default the war/jar in the maven "package" build phase to create the "runnable jar/war". The `maven-failsafe-plugin` executes the IT cases in the maven lifecycle phase "integration-test" - the phase after "package". Up to maven-`failsafe-plugin` 2.18.1 this is no problem because it use the `target/classes` folder for boot classpath. In 2.19 now it use the repackaged fully assembled jar to run the IT cases. This cause in my case some trouble.

I didn't know any workaround - but i would let you know it.

**Comment by philwebb** [comment]
Are you able to share any code that replicates the issue. I curious why using the jar as opposed to the classpath would make things so much slower.

It might also be worth asking the shurefire team to add an option so that the old behavior can be restored. It seems a bit odd that `IntegrationTestMojo.getClassesDirectory` doesn't offer an escape hatch to not use the jar.

**Comment by snicoll** [comment]
I have created [SUREFIRE-1198](https://issues.apache.org/jira/browse/SUREFIRE-1198) and will follow up with them to get it resolved.

**Comment by snicoll** [comment]
> it use the repackaged fully assembled jar to run the IT cases. This cause in my case some trouble.

Can you be a bit more specific? Or comment on the surefire issue please?

**Comment by kreyssel** [comment]
Sorry @snicoll, i cannot reproduce this in a simple test project.

Maybe it is only in my setup. Will try to find the problem. In the meantime I close the issue.

**Comment by snicoll** [comment]
oh well. Please follow on the surefire issue then please. I still think that they should have introduced an option at least but they obviously disagree with that.

**Comment by kreyssel** [comment]
Okay @snicoll. I can reproduce it. I have made a little testset to reproduce it. Have a look on. https://github.com/kreyssel/spring-boot-failsafe-plugin-console-hang-test-set

The project builds two modules with one integration test in each module. The "slow down" only occurs within the failsafe-2_19 module on Windows 2003 (maybe also XP), the failsafe_2_18_1 runs always fast - both modules runs fine on my windows 7 box. In the failsafe-2_19 module the build, integration tests and console seems fast until the spring boot banner is printed. After printing out the banner it runs soooo sloooow. I found a similar issue documented with JBoss - see https://developer.jboss.org/thread/199496

I figured out that the "slow down" maybe occures in the java.io.Console.istty() method (see attached visualvm sampler image). Its called by java.lang.System.console() - and this is called by org.springframework.boot.ansi.AnsiOutput.detectIfEnabled(). But I do not fully understand why it only occured on failsafe 2.19 and not occured on failsafe 2.18.1.

![maven](https://cloud.githubusercontent.com/assets/434996/11424021/d4e26c80-9449-11e5-8ebb-85bcab72e48d.png)

We should also have a look on org.springframework.boot.ansi.AnsiOutput.isEnabled(). Should not the result of the detectIfEnabled() call cached? If not (and today it is not) it will always call System.console(). And this is maybe the "slow down".

My test env is:

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_55\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

If you have such a good old windows oldtimer can you reproduce it? If you can reproduce it we can reopen the issue?

**Comment by kreyssel** [comment]
@snicoll Is it possible to disable the AnsiOutput by an property?

**Comment by snicoll** [comment]
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logging-console-output

**Comment by kreyssel** [comment]
Thanks. spring.output.ansi.enabled=NEVER fixed the "slow down".

But IMHO the call of detectIfEnabled() should be cached. :+1:

**Comment by Tibor17** [comment]
@kreyssel 
We changed only reads from std/in only. I guess `System.console()` is using the same std/in.
If you just dump the Threads do you see where the main Thread hangs?
Is is the native console or surefire?
Interesting to me is the timeout 200 or sometimes 290 seconds. Where it comes from?

**Comment by philwebb** [comment]
Caching `detectIfEnabled()` seems sensible

**Comment by Tibor17** [comment]
ok if it is only Spring caching problem, you can just close it. I don't complain.
