### ISSUE TITLE
Spring Boot suddently requires PlatformTransactionManager

### ISSUE THREAD

**Issue by dilgerma** [spring-projects/spring-boot#4516]
It think it depends on : https://github.com/spring-projects/spring-boot/pull/2809

Spring Boot 1.3

With these Depdendencies:

```
dependencies {
    compile "org.projectlombok:lombok:1.16.4"
    compile "com.google.guava:guava:17.0"
    compile("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    compile("org.springframework.boot:spring-boot-starter-jetty")
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.springframework.cloud:spring-cloud-starter-eureka")

    compile("commons-io:commons-io:2.4")
    compile('commons-fileupload:commons-fileupload:1.3.1')
    compile("de.codecentric:spring-boot-admin-starter-client:1.2.3")
    compile("org.springframework.data:spring-data-mongodb") {
    }

    testCompile("org.springframework.boot:spring-boot-starter-test")

}
```

Suddenly requires a PlatformTransactionManager.

This is due to the fact that spring-boot-starter-mongo brings in spring-tx that enables TransactionAutoConfiguration.

**Comment by wilkinsona** [comment]
TransactionAutoConfiguration is conditional on a single PlatformTransactionManager bean so it shouldn't be switched on in the scenario you have described. What's the full stacktrace of the failure that you are seeing?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
