### ISSUE TITLE
Spring boot grade plugin : Unable to refresh project after upgraded to 1.3.0.RELEASE 

### ISSUE THREAD

**Issue by mkgit007** [spring-projects/spring-boot#4517]
Recreated from Issue #4514 as it was closed

Please find below the link of test project to reproduce the issue

https://github.com/mkgit007/test

**Comment by spencergibb** [comment]
[This line](https://github.com/mkgit007/test/blob/master/build.gradle#L22) looks [bad](https://github.com/spring-projects/spring-boot/issues/4514#issuecomment-157204300).

**Comment by mkgit007** [comment]
This configuration worked fine with 1.2.7 and 1.3.0 RC releases.
Any recent change caused this type of configuration to be invalid.

**Comment by mkgit007** [comment]
Thanks. that worked. Just curious what changed as we will be migrating more projects to latest spring boot version

**Comment by wilkinsona** [comment]
> Recreated from Issue #4514 as it was closed

There's no need to open a duplicate; you can still comment on an issue once it's been closed

> This configuration worked fine with 1.2.7 and 1.3.0 RC releases.

That doesn't appear to be the case. The sample project you've provided also fails when configured to use 1.3.0.RC1:

```
> Could not find org.springframework:spring-framework-bom:{data={version=1.3.0.RC1}}.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/{data={version=1.3.0.RC1}}/spring-framework-bom-{data={version=1.3.0.RC1}}.pom
      https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/{data={version=1.3.0.RC1}}/spring-framework-bom-{data={version=1.3.0.RC1}}.pom
      https://repo.spring.io/libs-milestone/org/springframework/spring-framework-bom/{data={version=1.3.0.RC1}}/spring-framework-bom-{data={version=1.3.0.RC1}}.pom
      https://repo.spring.io/libs-milestone/org/springframework/spring-framework-bom/{data={version=1.3.0.RC1}}/spring-framework-bom-{data={version=1.3.0.RC1}}.pom
  Required by:
      com.mycompany.:test-service:unspecified
```

> Just curious what changed as we will be migrating more projects to latest spring boot version

As [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#dependency-management), Spring Boot 1.3 uses a the [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) which brings Maven's superior dependency management to Gradle. The [spring-boot-dependencies bom](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RELEASE/spring-boot-dependencies/pom.xml#L131) uses the `spring.version` property to control the version of Spring Framework that's used. Your `build.grade` is overriding this property with a value of `1.3.0.RELEASE`.
