### ISSUE TITLE
commons-collections upgraded to 3.2.2

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#4520]
Because security problem. http://commons.apache.org/proper/commons-collections/release_3_2_2.html

**Comment by joshiste** [comment]
@linux-china the security problem is not in apache commons collections. Its because of Websphere, Jboss and co are deserializing Java-Objects from untrusted sources without checking.

**Comment by michael-mccutcheon** [comment]
Will this upgrading of the commons-collections also be in spring-boot 1.3?

**Comment by wilkinsona** [comment]
> Will this upgrading of the commons-collections also be in spring-boot 1.3?

Yes, it'll be in 1.3.1
