### ISSUE TITLE
Spring boot application may fail to start with init.d due to race condition in start-stop-daemon

### ISSUE THREAD

**Issue by choene** [spring-projects/spring-boot#4524]
Hello,

I am starting a spring boot application as a service with /etc/init.d/<name>

However, the init.d script stops with return code 1 and the message "failed to start".

To my understanding, the start-stop-daemon does not produce the pid file immediately. 

Thus,  "pid=$(cat "$pid_file")" is returning an empty string. I added a sleep 1 before this line, that helps for the moment.

**Comment by wilkinsona** [comment]
@choene What OS are you running on?

**Comment by choene** [comment]
Ubuntu 14.04, 64 bit

Linux tuebingen03 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23
UTC 2015 x86_64 x86_64 x86_64 GNU/Linux



> Andy Wilkinson <notifications@github.com> hat am 17. November 2015 um 13:34
> geschrieben:
> 
> 
> @choene What OS are you running on?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spring-projects/spring-boot/issues/4524#issuecomment-157359444

--
Symonics GmbH
Sand 13
72076 Tübingen
Tel +49 7071 5681302
Fax +49 7071 5681309
Email: christian.hoene@symonics.com
Geschäftsführer/President: Dr. Christian Hoene 
Sitz der Gesellschaft/Place of Business: Tübingen
Registereintrag/Commercial Register: Amtsgericht Stuttgart, HRB 739918

**Comment by wilkinsona** [comment]
Thanks. I'm surprised we haven't seen this in our testing, I guess we've just got lucky with the timings and never managed to trigger the race condition. This would appear to be a [known issue](https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1036899) when `--make-pidfile` and `--background` are used together.

**Comment by vpavic** [comment]
Is this limited to Debian-based OS's?
One of our test systems is running Ubuntu 14.04.3 LTS, but I also didn't happen to hit this in testing.

**Comment by ukjbrown** [comment]
Also experiencing this issue.
Ubuntu 14.04.3 LTS
Linux (...) 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 
UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hypery2k** [comment]
same issue with Debian: 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux

**Comment by pmvilaca** [comment]
I was using the launch script with Amazon linux and it was working fine. I can confirm the issue with ubuntu 14.04 as well

**Comment by wilkinsona** [comment]
Reopening to fix some issues reported by Shellcheck. Thanks, @php-coder

**Comment by jasperblues** [comment]
Is there a way to apply the fix to current versions of boot via gradle?

**Comment by vpavic** [comment]
Check the [documentation on repackage configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-repackage-configuration).

You could include the current version of the script in your project and use ```embeddedLaunchScript``` option to point to it.

**Comment by jasperblues** [comment]
Thank you @vpavic
