### ISSUE TITLE
1.3.0.release causes jms.InvalidClientIDException after devtools restart

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#4526]
Works on initial start, but not after a devtools restart. Seems `JmsTemplate` is not disconnecting the previous connection as part of the restart. I am setting the clientID, and now have added a `System.currentTimeMillis` to the end of the `clientID` I am setting as a workaround. 

So while i am getting a nice devtools restart, I did confirm connections are increasing (via active mq console) that every time devtools restart occurs , another connection is getting added.  

Ideally - devTools should be removing the old connection and construct a new one.

```java
SingleConnectionFactory connectionFactory = new SingleConnectionFactory();
		connectionFactory.setReconnectOnException( true );
		connectionFactory
				.setClientId( ... + System.currentTimeMillis() );
```

Without adding a `currentTimeMillis` to get a unique client id, the following exception will occur on restarts; but as noted above - connections are leaking when this is done.

```
org.springframework.jms.InvalidClientIDException: Broker: localhost - Client: MyDesktop-MYPC-JMS-SENDER already connected from tcp://10.116.103.99:55631; nested exception is javax.jms.InvalidClientIDException: Broker: localhost - Client: MyDesktop-MYPC-JMS-SENDER already connected from tcp://10.116.103.99:55631
	at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:282) ~[spring-jms-4.2.3.RELEASE.jar:4.2.3.RELEASE]
```

**Comment by snicoll** [comment]
Thanks for the report, I'll look into it.

**Comment by snicoll** [comment]
It works for me and I think the key is that `SinngleConnectionFactory` should be exposed as a `@Bean` so that we have a chance to actually destroy it when the application is restarted. Can you double check that and share a sample project if that still does not work?

**Comment by peterdnight** [comment]
That makes sense .... but when i added it as a bean I get the non-unique bean exception. I noticed there is not a qualifier on the connection factory.

Recommendation? I really like using the Boot constructed DefaultJmsListenerContainerFactory, but  how to handle multiple connection factories..




```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jmsListenerContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/jms/JmsAnnotationDrivenConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.jms.ConnectionFactory]: : No qualifying bean of type [javax.jms.ConnectionFactory] is defined: expected single matching bean but found 2: getJmsListenersConnectionFactory,getSenderFactory; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [javax.jms.ConnectionFactory] is defined: expected single matching bean but found 2: getJmsListenersConnectionFactory,getSenderFactory

**Comment by snicoll** [comment]
If you're not exposing this as a bean, there is no way for us to properly shutdown things when the context is restarted. I have no view on your project and there are many ways to do it (stackoverflow is your friend) but what I'd do I think is keep the reference of your `SingleConnectionFactory` in some bean of yours and close the connection factory when your bean is destroyed.

Here [is a concrete example](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/HazelcastCacheConfiguration.java#L115-L130) (based on `CacheManager)

**Comment by peterdnight** [comment]
That i can do. General comment for consideration: 
-  consider updating JmsAnnotationDrivenConfiguration as shown below to include a qualifier on the connection factory being injected.

```
	@Bean
	@ConditionalOnMissingBean(name = "jmsListenerContainerFactory")
	public DefaultJmsListenerContainerFactory jmsListenerContainerFactory(
			ConnectionFactory connectionFactory) {

```
	@Bean
	@ConditionalOnMissingBean(name = "jmsListenerContainerFactory")
	public DefaultJmsListenerContainerFactory jmsListenerContainerFactory(
			@Qualifier("jmsListenerFactory") ConnectionFactory connectionFactory) {

**Comment by snicoll** [comment]
Good catch! I've created #4652
