### ISSUE TITLE
Spring Boot 1.3.0.RELEASE with devtools ClassLoader issue

### ISSUE THREAD

**Issue by eugene-kamenev** [spring-projects/spring-boot#4529]
I am trying to migrate our apps that are using jax-ws based communication between services, and i found that simply enabling devtools causes exception related to ClassLoader, that is returned to jax-ws handler by spring app, to find web-service interface in classpath, the exception message i got was:

interface com.app.PrincipalWebService is not visible from class loader

Do i need to provide more information?

**Comment by cemo** [comment]
The jars you are having issues must be loaded Spring DevTools ClassLoader. You need to provide a `spring-devtools.properties` inside `resources/META-INF` folder. Inside this fill the jar names you are having issues in this format:

```
restart.include.ttt=/ttt-.*.jar
restart.include.zzzz=/zzz-.*.jar
```

This will let the devtools to load necessary classes by `Spring DevTools ClassLoader`

**Comment by eugene-kamenev** [comment]
@cemo thanks, this can be a reason, but then, if my classes are inside project submodule, do i still need to define something like this? If yes, what path expression should be?

**Comment by wilkinsona** [comment]
@eugene-kamenev It's impossible to give concrete advice without seeing the structure of your project, the names of the jar files involved, etc. Can you create a small sample that reproduces the problem?

**Comment by eugene-kamenev** [comment]
I am sorry guys, i tried to reproduce this behavior with sample multimodule gradle app and it worked fine, but with our project it still throws exception, for now i think we can close this, i will keep posted if something will change. Thanks.
