### ISSUE TITLE
Make BasicBatchConfigurer public again

### ISSUE THREAD

**Issue by sddakoty** [spring-projects/spring-boot#4533]
In `spring-boot.1.3.0.RELEASE` the `BasicBatchConfigurer` has been declared as a `protected` class.

As we `extends BasicBatchConfigurer` to override only the `JobRepository` and `JobExplorer` to provide our own. The rest is inherited.

We'd like to keep this up, but unfortunately as the class is protected now, this is not possible anymore.

Any chance this is getting `public` again in future?

**Comment by snicoll** [comment]
See #2132

**Comment by philwebb** [comment]
Commit e0f59d8a7408b6a0faae2b77744639ed1c1f58af changed that, I don't see any compelling reason why it can't be public again.
