### ISSUE TITLE
Make SpringApplication.selectBanner protected so it can be overridden

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#4534]
Or is there recommended way to set the default banner when extending `SpringApplication`?

We have a `CompanyNameSpringApplication` (which extends `SpringApplication`) and we want to override the default banner.

**Comment by marceloverdijk** [comment]
Hmm, looking at further code I don't think extending `SpringApplication` is that convienient at all.
E.g it's `run

**Comment by philwebb** [comment]
You should be able to override `SpringApplication` without issue. The `printBanner` method can be overridden or you could call `setBanner` with a custom `Banner` implementation.

**Comment by marceloverdijk** [comment]
@philwebb thx for feedback, but I think the 'problem' is with:

```
	public static ConfigurableApplicationContext run(Object[] sources, String[] args) {
		return new SpringApplication(sources).run(args);
	}
```
 in `SpringApplication`.

So entending this `SpringApplication` by using something like:

```
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        MyCompanyApplication.run(Application.class, args);
    }
}
```

does not work when I override `printBanner` as the actual `MyCompanyApplication.selectBanner` is never invoked but the `SpringApplication.selectBanner` is.

Any thoughts?

**Comment by snicoll** [comment]
uh ?

```java
public class MyCompanyApplication extends SpringApplication {

    public MyCompanyApplication(Object... sources) {
		super(sources);
                setBanner(foobar);
	}

}
```

**Comment by marceloverdijk** [comment]
@snicoll yes but there is more to get this accomplished.
Basically I have to copy/hide the static `run` and `main` methods. And also override all constructors.
Note this was working.

But when running mockmvc tests using `@SpringApplicationConfiguration` again the `SpringApplication ` is used. Off course I can create my own `SpringApplicationConfiguration`, override `getSpringApplication` in `SpringApplicationContextLoader` but I don't think it's worth it to just display the company banner if the app has no custom banner.
I think I should try to find another way to do this (if possible).

**Comment by snicoll** [comment]
I am just confused about the title. You want to be able to override something so yes you have to do something about that static methods. And while you're doing that you could just as well create the instance and set the default banner there. 

I just don't get what you'd get if we make that protected. All you have to do now would still be necessary.

**Comment by marceloverdijk** [comment]
@snicoll yes true that I still have to do the same; that's why I closed the issue right after opening it as it's not so convenient to set a default banner this way :-)
