### ISSUE TITLE
logging.config properties in 1.3.0.BUILD-SNAPSHOT have a error

### ISSUE THREAD

**Issue by jameBoy** [spring-projects/spring-boot#4535]
I use spring-boot with 1.3.0.BUILD-SNAPSHOT and my application.properties is this.
```xml
logging.config = config/logback.xml
logging.file　= log/demo_logging.log
logging.level.org.springframework.web　= DEBUG
```
I use to run Application, but a error hava . The error is that cant find  config/logback.xml .But when i use 1.2.1.RELEASE. It work good.

So  I want to know that the log properties in application.properties should be what?

**Comment by snicoll** [comment]
This is described [in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#initialization-failures)
