### ISSUE TITLE
1.3.0 build takes longer due to Resolving Conflicts

### ISSUE THREAD

**Issue by chris-shepperd** [spring-projects/spring-boot#4538]
Yesterday I changed our multi-project build from 1.2.3.RELEASE to 1.3.0.RELEASE.  Once I did this I saw in increase in build times when nothing was changed, eg a **gradle build** made one of the subprojects go from 5-6 seconds to 27-28 seconds consistently.  I now see a Resolving Conflicts message several times during the build and when running debug I see the following line literally 14,877 times in a row amongst other consistent logs:

`*09:45:36.685 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.DependencyGraph] Excluding commons-logging:commons-logging from org.springframework:spring-core due to dependency management exclusion`

followed by 

```
09:45:36.688 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction] Initial dependency graph:
09:45:36.688 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction] avprm.engines:avprm-bom
09:45:36.689 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]     log4j:log4j
...
```

Is there some way to speed the build back up?  We want to take advantage of the executable jar file in 1.3.0 but don't want to add anything to an already long build time.  Thanks.

**Comment by wilkinsona** [comment]
This is a side-effect of the new [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) apply the exclusions in the poms correctly (which Gradle doesn't do by default). I've seen it slow builds down a little but not the 4-5x that you're seeing. Can you provide a sample `build.gradle` that illustrates the problem?

You can also switch of the plugin's exclusion configuration:

```groovy
dependencyManagement {
    applyMavenExclusions false
}
```

**Comment by chris-shepperd** [comment]
I tried the switch you gave and it's back to 5-6 seconds which works for me for now...

It's a pretty large *build.gradle* file with some 46 sub projects.  I will try to simplify it a bit while maintaining the time lag so I can submit something.

**Comment by wilkinsona** [comment]
Thanks

**Comment by chris-shepperd** [comment]
Ok, spent a little time trying to whittle down our project to something that conveys the problem.  At https://github.com/chris-shepperd/springboot-gradle-slowdown you'll find a project with 14 sub projects and their dependence on each other.  I've removed all source code to make it palatable, and removed all dependencies except Spring Boot.  I did the following 8 timings (combinations of your exclusion tip and I found that adding classifier into the mix also affected the timings as you can see below)

.  Let me know any other info you could need to reduce the impact.  

**with maven exclusions, no classifier**
```
> gradle clean build 
Total time: 10.319 secs
```
**with maven exclusions, with classifier**
```
> gradle clean build 
Total time: 9.074 secs
```
**ignoring maven exclusions, no classifier**
```
> gradle clean build 
Total time: 1.069 secs
```
**ignoring maven exclusions, with classifier**
```
> gradle clean build 
Total time: 1.128 secs
```
**with maven exclusions, no classifier**
```
> gradle engines:avprm-bom:clean engines:avprm-bom:build 
Total time: 5.538 secs
```
**with maven exclusions, with classifier**
```
> gradle engines:avprm-bom:clean engines:avprm-bom:build 
Total time: 9.628 secs
```
**ignoring maven exclusions, no classifier**
```
> gradle engines:avprm-bom:clean engines:avprm-bom:build 
Total time: 0.858 secs
```
**ignoring maven exclusions, with classifier**
```
> gradle engines:avprm-bom:clean engines:avprm-bom:build 
Total time: 0.899 secs
```

**Comment by chris-shepperd** [comment]
Forgot to give gradle version info in case it helps...
````
> gradle -version

------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.11.1 x86_64
```

**Comment by wilkinsona** [comment]
@chris-shepperd Are you using Gradle's daemon? Without it I see much smaller time differences: 9 seconds with Maven exclusions and 5 seconds without. Still a bigger delta than I would like, but nothing like the 10x difference that you're seeing.

**Comment by chris-shepperd** [comment]
Yes we are using the daemon.  The difference without the daemon of course is smaller, but the time it takes with exclusions is the same in both cases... ~9-10 seconds

**Comment by wilkinsona** [comment]
@chris-shepperd Thanks again

**Comment by wilkinsona** [comment]
@chris-shepperd A new snapshot of the plugin is available that should speed things up quite significantly. With Maven-style exclusions the build time was down to ~2 seconds. Can you please give it a try? To use it with Spring Boot, you'll need to  update your `buildscript` configuration:

```
buildscript {
   List springBootPlugin = ["org.springframework.boot:spring-boot-gradle-plugin:1.3.0.RELEASE"]

   repositories {
      maven { url 'https://repo.spring.io/plugins-snapshot' }
      mavenCentral()
   }

   dependencies {
      classpath springBootPlugin
      classpath "io.spring.gradle:dependency-management-plugin:0.5.4.BUILD-SNAPSHOT"
   }
}
```

**Comment by chris-shepperd** [comment]
@wilkinsona  Tried this out on the example I gave you since I reverted all my other changes to 1.3.0 for now due to a variety of reasons mostly dealing with dependencies.  This seemed to drastically reduce the timings on the example, so I'll assume they'll do the same on the full project.  Appreciate the work/responses!

Thanks!

**Comment by wilkinsona** [comment]
Thanks for testing, @chris-shepperd. We'll get a new, speedier version of the plugin into 1.3.1
