### ISSUE TITLE
file upload complete rename the name  img tag src 404 

### ISSUE THREAD

**Issue by liyang1025** [spring-projects/spring-boot#4539]
JSONObject result = new JSONObject();
				byte[] bytes = file.getBytes();
				String filename = file.getOriginalFilename();
				String Newfilename=java.util.UUID.randomUUID().toString().replace("-",
				 "")+filename;
				String path = IMAGE_PATH + filename;
				BufferedOutputStream stream = new BufferedOutputStream(new FileOutputStream(new File(path)));
				stream.write(bytes);
				stream.close();
				File oldfile =new File(path);
				File newfile=new File(IMAGE_PATH + Newfilename);
				oldfile.renameTo(newfile);
				result.put("code", 0);
				result.put("filepath", "/uploadfile/image/" + Newfilename);
				return result.toJSONString();

my code is upload the image rename and then response the path to browser  but if  i change the getOriginalFilename to unique name  the browser is 404 but the file is exists in the disk what name is the  changed name

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)

**Comment by liyang1025** [comment]
ok
