### ISSUE TITLE
Include Spring Data REST endpoints in /mappings

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4541]

**Comment by htynkn** [comment]
I check the related code and I find the reason spring data rest endpoint didn't show in mappings is `RepositoryRestHandlerMapping` is not export as a bean. If it export as a bean, `RequestMappingEndpoint` can get all the information by `extractMethodMappings` method.

The only instance of `RepositoryRestHandlerMapping` is created by`RepositoryRestMvcConfiguration`, but this file is out of spring-boot. It's a part of `spring-data-rest-webmvc`.

If we can ask them to export `RepositoryRestHandlerMapping` as a bean, it will be easy for us. Or we can treat Spring Data REST endpoints as an exceptional case and add some code of it in `RequestMappingEndpoint`.

Do you have any advice? @wilkinsona

**Comment by wilkinsona** [comment]
Spring Data REST already exposes its handler mapping as a bean, but it's a `DelegatingHandlerMapper` rather than one of the types the the Actuator can already introspect. `RepositoryRestHandlerMapper` is one of the delegates so I don't think it can be exposed as a bean as, if it was, some of the mappings would be exposed twice.

We either need to use reflection to look inside `DelegatingHandlerMapping` or we need an official API for accessing its delegates.

**Comment by wilkinsona** [comment]
I've opened [DATAREST-1136](https://jira.spring.io/browse/DATAREST-1136) to hopefully get an official API for accessing the delegates.

**Comment by wilkinsona** [comment]
As of https://github.com/spring-projects/spring-boot/issues/9979, mappings from Spring Data REST are now available.
