### ISSUE TITLE
TomcatEmbeddedServletContainerFactory should not create a StandardManager object unconditionally

### ISSUE THREAD

**Issue by zeodtr** [spring-projects/spring-boot#4543]
In `TomcatEmbeddedServletContainerFactory.configureSession()`, a `StandardManager` object is created if `this.manager` is `null`. But it is not needed if `isPersistSession()` is `false`.

This superfluous creation has somewhat bad effect when another manager is needed for the context. For example, when configuring tomcat session clustering, a `DeltaManager` is needed instead of `StandardManager`. an application programmer can replace the manager by adding a `TomcatContextCustomizer` that's called later, but it was not needed on previous versions of Spring Boot (since the manager would be created automatically later) thus breaking compatibility.

On [the first commit](https://github.com/spring-projects/spring-boot/commit/08d1f6daf5b29af880de214e31543debe49a33f1) that's related this issue, it had been properly done - that is, a `StandardManager` is created only when `isPersistSession()` is true. But on a [commit later](https://github.com/spring-projects/spring-boot/commit/1a764d9c06f2a96722c04b8d8bb1edf89e424628), it was changed to current form. I think the first commit's code is better.

**Comment by philwebb** [comment]
We need to ensure that `StandardManager` is set so that the `disablePersistSession` code works. Perhaps we can shift this to a later point.
