### ISSUE TITLE
How to exclude lib-privide in war?

### ISSUE THREAD

**Issue by liangjw** [spring-projects/spring-boot#4545]
Follow spring boot doc, run  mvn  package  with spring-boot-maven-plugin.
But a  lib-privide folder is packaged in war/WEB-INF

How to exclude lib-privide in war?

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
