### ISSUE TITLE
1.3 release notes: mention @Order changes

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#4546]
I've been using `@Order` to manage ordering between auto-configuration classes that sequentially attempt to provide a missing bean but really shouldn't have any direct knowledge of each other. It appears that 1.3 stopped paying attention to the priority, and I got a no-unique failure the first time I tried to deploy to production. This should probably be mentioned in the release notes.

**Comment by philwebb** [comment]
Good point. Commit 7a73c5883f857f7dfb56d73410af96eae04a0e63 added a new `@AutoConfigureOrder` annotation which is now used. This was needed due to Spring Framework now respecting `@Order` on `@Configuration` classes.

**Comment by philwebb** [comment]
We should also check the reference docs

**Comment by snicoll** [comment]
I've [updated the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#auto-configuration-order). The developer guide [already has a section about these two new annotations](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-locating-auto-configuration-candidates)

**Comment by snicoll** [comment]
oh my, I have mixed thing with `@AutoconfigureBefore`/`After`.
