### ISSUE TITLE
unable to customize the ‘whitelabel’ error page using code customizations 

### ISSUE THREAD

**Issue by EasyLearnJava** [spring-projects/spring-boot#4547]
Please show me a sample code to customize the whitelable error code in java code.
basically need to redirect to a default page like mycustomeerrorpage.html or mycustomerrorpage.jsp when /error occurs in the application

**Comment by wilkinsona** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
