### ISSUE TITLE
HttpServletRequest.isUserInRole does not work after upgrade to boot 1.3

### ISSUE THREAD

**Issue by michaelm001** [spring-projects/spring-boot#4549]
I'm using Java 8, Spring boot 1.3, embedded Tomcat with an executable war file.

HttpServletRequest.isUserInRole does not return true when principal shows I have a role.

The following code worked perfectly in Spring Boot 1.2.7:

```
@Override
protected final void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
{
	Principal principal = request.getUserPrincipal();
	if(principal!=null) {
		if(request.isUserInRole("app_user")) {
			authenticatedDoGet(request, response);
			return;
		}
	} 
	this.handleRedirect("noaccess.html", response);
}
```

However, since updating to Spring Boot 1.3, request.isUserInRole does not work...it returns false when the principal shows I have the "app_user" role.

When I debug this code, I see that the principal object is created, and it has a property called "authorities" which is a collection of roles.  It shows that I have the role "app_user" in element zero.  It is an instance of SimpleGrantedAuthority.  Additionally, the request object is an instance of XSSRequestWrapper.

I don't understand how I can get the principal from the request, and it shows that I have that role, but request.isUserInRole returns false for that same role.

I would appreciate if someone could take a look at this because request.isUserInRole is one of the most important methods on the whole request.

**Comment by wilkinsona** [comment]
There are a few things that could be affecting the behaviour here. Can you please provide a small sample that reproduces the problem so that we can be sure that we're looking at the right combination?

**Comment by michaelm001** [comment]
The issue was that I had to go into the 'authorities' table and prefix all of the roles in the 'authority' column with 'ROLE_'.  This seems idiotic given that Spring reads the role from table and already knows that it is a role...or is Spring expecting things other than a role in that column?

It is problematic if I want to use those roles elsewhere in the app because I have to then trim off the redundant 'ROLE_'.  Seems like needless complexity.

But I'm glad I got it working and thanks for listening!

**Comment by wilkinsona** [comment]
@michaelm001 Glad to hear you got to the bottom of the problem. Your complaint about the ROLE_ prefix is a Spring Security concern that @rwinch may be interested in. You may be interested in the [relevant section of the migration guide](http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-jc.html#m3to4-role-prefixing) which includes information about how to disable it.

**Comment by michaelm001** [comment]
How can I leave a message with @rwinch?  I can't message him via github and the spring-security project has no 'issues' page where one can mention these things.

**Comment by philwebb** [comment]
@michaelm001 He'll get an email from the @rwinch mention, but if you want to raise an issue the Spring Security project uses [JIRA](https://jira.spring.io/browse/SEC/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).

**Comment by rwinch** [comment]
@michaelm001 Sorry I did not reply. I had thought that the link to the migration guide would have covered it for you. If you need to report an issue please post to JIRA as indicated by Phil.
