### ISSUE TITLE
Regex support on /metrics returns "not found" if metrics value is null

### ISSUE THREAD

**Issue by fguerout** [spring-projects/spring-boot#4552]
Regex support added in boot v1.3 does not handle correctly null metrics value due to :

https://github.com/spring-projects/spring-boot/blob/8ca5635b69109fba898a094abd5970c906d29060/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/MetricsMvcEndpoint.java#L75

Consequently, it results in a 404 HTTP error code.

**Comment by wilkinsona** [comment]
The environment endpoint has the same problem
