### ISSUE TITLE
OAuth2 resource server configuration breaks contract of RestTemplate interceptors

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4553]
It uses `setInterceptors()` and then sets a value which is an unmodifiable list, whereas the `RestTemplate` is supposed to allow its interceptors to be mutated.

**Comment by baspet** [comment]
please, remove WorkaroundRestTemplateCustomizer from oauth2-ui project if not needed any more

**Comment by dsyer** [comment]
Do you have a link to this `WorkaroundRestTemplateCustomizer`? I didn't see it anywhere in Spring Boot.

**Comment by baspet** [comment]
oauth2/ui/src/main/java/demo/UiApplication.java --> line 83

**Comment by dsyer** [comment]
I think you mean here: https://github.com/spring-guides/tut-spring-security-and-angular-js. It's fixed.
