### ISSUE TITLE
How to Implement Multi tenancy Database with spring boot.

### ISSUE THREAD

**Issue by winkumar** [spring-projects/spring-boot#4555]
our application structure is multi-tenant with database. each customer has their own database. i have store all tenant information in separate database. when user request api i need connect specific database. how to implement in spring boot. i am using mysql database. Now my api ready with single database. i need to switch specific db connection at run time. thanks.

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)
