### ISSUE TITLE
1.3 GA ignores custom filter when requesting protected resource by anonymous user

### ISSUE THREAD

**Issue by zxkane** [spring-projects/spring-boot#4559]
I have a custom filter to add CORS headers for the Restful APIs. It will always be called when using spring boot 1.2.6 while requesting the protected resource by anonymous user. However below filter is not called after upgrading boot to 1.3.0 GA when requesting a protected resource by anonymous user.

Is it a regression of boot 1.3 GA or something improper configuration of custom filter?

The CORS filer looks like below,

```java
@Component
public class SimpleCORSFilter extends OncePerRequestFilter {

	@Resource
	CORSSettings corsSettings;

	static final String ORIGIN = "Origin";

	boolean matchCORSSettings(String origin) {
		for (String allowedOrigin : corsSettings.getOrigin()) {
			if (origin.contains(allowedOrigin))
				return true;
		}
		return false;
	}

	@Override
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
		final String origin = request.getHeader(ORIGIN);
		if (origin != null && matchCORSSettings(origin)) {
			response.setHeader("Access-Control-Allow-Origin", origin);
			response.setHeader("Access-Control-Allow-Credentials", "true");
			response.setHeader("Access-Control-Allow-Headers", request.getHeader("Access-Control-Request-Headers"));
			response.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS");
		}
		if (request.getMethod().equals("OPTIONS")) {
			try {
				response.getWriter().print("OK");
				response.getWriter().flush();
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			filterChain.doFilter(request, response);
		}
	}

}
```

**Comment by wilkinsona** [comment]
Spring Framework 4.2 has built-in CORS support so you probably don't need your own filter any more.

If you do, I would guess that the problem is that it's not ordered so it's running after Spring Security's filter - filters are logged at startup in the order in which they'll be called. Try ordering your filter with a higher precedence then the security filter.
