### ISSUE TITLE
@ConfigurationProperties requires class to be mutable in Kotlin

### ISSUE THREAD

**Issue by jasperblues** [spring-projects/spring-boot#4563]
Is it possible to get `@ConfiguraitonProperties` to inject a matching constructor? Otherwise in Kotlin it is necessary to declare the configured properties as public and mutable, which is not ideal. 

Also, in Kotlin, the @Value annotation is a little ugly, since "${something}" is a language feature and must be escaped. 

I generally love using Spring Boot and Kotlin together - what could be more fun? But things get a little ugly when it comes to external configuration.

**Comment by snicoll** [comment]
What's Kotlin specific exactly? `@ConfigurationProperties` requires a regular "POJO" with public properties. Isn't that the exact same thing? What do you mean by a _matching constructor_?

**Comment by jasperblues** [comment]
It is my understanding that in Java we can make the `@ConfigurationProperties` object immutable, by: 

- Having private fields
- Including public getters

. . and that the object will be configured using reflection. In Kotlin, this didn't work. The properties had to be mutable. (I'll attach a sample in a moment). 

>What do you mean by a matching constructor? 

- I mean that rather that set fields by reflection, look for a constructor whose parameter names match required properties and inject that. Ah, but I recall now that in Java/JVM languages constructors don't provide parameter-name reflection, right? So only type-signature matching would be possible, with isn't very practical in the case of a configuration holder (likely lots of strings, etc).

**Comment by snicoll** [comment]
> It is my understanding that in Java we can make the @ConfigurationProperties object immutable

No. As I said, in Java you need a regular JavaBean property (public getter/setter). We don't support anything else at the moment and your request is not kotlin specific either (unless I am mistaken).

Duplicates #1254

**Comment by jasperblues** [comment]
Ah, I see! I assumed config objects would naturally lean towards being immutable. 

:+1: on 1254 for myself as well then :) 

Thank you.

**Comment by sdeleuze** [comment]
@jasperblues Do you have any Kotlin `@Value` usage example to share?

**Comment by jasperblues** [comment]
Sure: 

```kotlin

@Component
class TokenAuthenticationProvider : AuthenticationProvider
{
    val profileRepo : ProfileRepository
    val config : TokenAuthenticationConfig

    //---------------------------------------------------------------------------------------
    //MARK: - Constructors
    //---------------------------------------------------------------------------------------

    @Autowired constructor(profileRepo: ProfileRepository, config: TokenAuthenticationConfig)
    {
        this.profileRepo = profileRepo
        this.config = config
    }

    //etc . . . 
```

Unfortunately as `"${something}"` is a language feature in Kotlin, it needs to be escaped. I asked on Stackoverflow for a quick/easy way to customer the property placeholder prefix and suffix in Spring Boot - waiting for advice.

**Comment by sdeleuze** [comment]
@jasperblues Could you try with `#{something}` instead of `${something}`?

**Comment by jasperblues** [comment]
@sdeleuze Out of the box, with standard Spring Boot, that does not work. However, I suspect if you changed the `PropertyPlaceholderConfigurer` with to one that had appropriate prefix and suffix it would.

**Comment by sdeleuze** [comment]
@jasperblues In fact, using `#` is probably not good idea since this prefix is already used for evaluating SpEL expressions, but it is indeed possible to customize the prefix used by declaring the following bean in your configuration (be careful this is `PropertySourcesPlaceholderConfigurer`, not `PropertyPlaceholderConfigurer`):

```kotlin
@Bean
 open fun propertyConfigurer() : PropertySourcesPlaceholderConfigurer {
    val propertyConfigurer = PropertySourcesPlaceholderConfigurer()
    propertyConfigurer.setPlaceholderPrefix("&{")
    return propertyConfigurer
}
```

if you have any existing code (like Spring Boot actuators) that is using the `${...}` syntax, you should declare:

```kotlin
@Bean
open fun kotlinPropertyConfigurer() : PropertySourcesPlaceholderConfigurer {
    val propertyConfigurer = PropertySourcesPlaceholderConfigurer()
    propertyConfigurer.setPlaceholderPrefix("&{")
    propertyConfigurer.setIgnoreUnresolvablePlaceholders(true)
    return propertyConfigurer
}

@Bean
open fun defaultPropertyConfigurer() : PropertySourcesPlaceholderConfigurer {
    return PropertySourcesPlaceholderConfigurer()
}
```

**Comment by jasperblues** [comment]
@sdeleuze Thank you, sir :)
