### ISSUE TITLE
Spring Boot DevTools ClassCast exception during session object deserialization.

### ISSUE THREAD

**Issue by konrad-nowicki** [spring-projects/spring-boot#4565]
I have just switched my code to boot 1.3 to try out devtools. 

I'm using Redis to hold session data of my users.
* spring-session-data-redis

And during deserialization of session object i have got class cast exception.
java.lang.ClassCastException: app.SessionData cannot be cast to app.SessionData

After I read this http://stackoverflow.com/a/2371991/4888004 I removed devtools and it works fine.

Regards
K

**Comment by wilkinsona** [comment]
Duplicates #3805
