### ISSUE TITLE
Missing async option for spring.http.encoding

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#4566]
Hi all,

Either we add the property 'spring.http.encoding.charset' or not into application.properties, Spring Boot loads automatically the filter CharacterEncodingFilter, but does not allow to set an option into filter telling if we want this filter as async, once my Servlet is using async as true.

It would be nice to have a property to inform this option, such as:
```
spring.http.encoding.async=true
```

Another option is to change the class HttpEncodingAutoConfiguration to create a CharacterEncodingFilter using DelegatingFilterProxyRegistrationBean which has async as true by default as many others AutoConfiguration classes are doing.

**Comment by wilkinsona** [comment]
The async dispatcher type is [enabled by default](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RELEASE/spring-boot/src/main/java/org/springframework/boot/context/embedded/RegistrationBean.java#L43) so there's no need for a configuration option to enable it. If you need more control then you can declare your own `FilterRegistrationBean` `@Bean` for the auto-configured `CharacterEncodingFilter` and customise it as required.
