### ISSUE TITLE
ConfigurationProperties error "Could not bind properties to [unknown]"

### ISSUE THREAD

**Issue by dhay** [spring-projects/spring-boot#4567]
In Spring Boot 1.2.6, it appears that if there is a problem binding properties in the ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization, a BeanCreationException is thrown with the error: "Could not bind properties to [unknown] (...)".

Looking at the code, the targetClass variable is never updated from it's default value.  It looks like an assignment is missing in the "if" condition:

		catch (Exception ex) {
			String targetClass = "[unknown]";
			if (target != null) {
				ClassUtils.getShortName(target.getClass());  // <---- Assign to targetClass here???
			}
			throw new BeanCreationException(beanName, "Could not bind properties to "
					+ targetClass + " (" + getAnnotationDetails(annotation) + ")", ex);
		}

**Comment by wilkinsona** [comment]
Thanks. This is already been fixed in 1.3 (https://github.com/spring-projects/spring-boot/commit/398d06e326b8e00897a4cb0ccaf9c89a217f1260). We need a similar change in 1.2.x
