### ISSUE TITLE
Adding additional info to /info endpoint

### ISSUE THREAD

**Issue by jlorenzen** [spring-projects/spring-boot#4568]
I noticed we can override the `InfoEndpoing` bean, but this completely replaces the existing info information. It would be really nice if we could just extend it to provide additional runtime information to the info endpoint. Would that be possible? Or perhaps this already exists and I just don't see how to do it?

**Comment by spencergibb** [comment]
You just need to add properties that start with `info.` to the spring `Environment`.

**Comment by jlorenzen** [comment]
@spencergibb Sorry for the stupid question but how do you do that?

**Comment by spencergibb** [comment]
Something like:
```
@Autowired
ConfigurableApplicationContext context;

//later
HashMap<String, Object> map = new HashMap<>();
map.put("info.foo", "bar");
MapPropertySource mysource = new MapPropertySource("mysource", map);
context.getEnvironment().getPropertySources().addFirst(mysource); // or addLast
```

**Comment by jlorenzen** [comment]
Ok just saw a sample posting similar to that. We are on spring boot 1.2.5.RELEASE and my `ConfigurableApplicationContext` does not have a `getEnvironment` method.

**Comment by spencergibb** [comment]
From what I can tell, it's been there since 2010: https://github.com/spring-projects/spring-framework/blame/master/spring-context/src/main/java/org/springframework/context/ConfigurableApplicationContext.java

**Comment by jlorenzen** [comment]
I can call `context.getPropertySources()` but when I do that and add my info map to it, I don't see any new properties on the `/info` endpoint. I'm doing this as a `@Bean` in my `SpringConfiguration` class so my `//later` part might not be working as expected.

**Comment by snicoll** [comment]
Duplicates #3492

**Comment by snicoll** [comment]
@jlorenzen we're going to have a better API in 1.4. Regarding your attempt to change the environment programmatically, you are changing the environment too late; listening to `ApplicationEnvironmentPreparedEvent` would work better. If you need further help, please ask on StackOverflow.

**Comment by cemo** [comment]
@jlorenzen  I have added our implementation. Hope it helps.
