### ISSUE TITLE
Gradle installApp fail

### ISSUE THREAD

**Issue by laxika** [spring-projects/spring-boot#4570]
Gradle's installApp fail on 1.3.x while it was working with 1.2.x.

	C:\Development\swords-server>gradle installApp

	FAILURE: Build failed with an exception.

	* What went wrong:
	Task 'installApp' not found in root project 'swords-server'.

	* Try:
	Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or                                                                                                                     --debug                                                                                                                  option to get more log output.

	BUILD FAILED

	Total time: 6.466 secs

My gradle version:

	------------------------------------------------------------
	Gradle 2.7
	------------------------------------------------------------

	Build time:   2015-09-14 07:26:16 UTC
	Build number: none
	Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

	Groovy:       2.3.10
	Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
	JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
	OS:           Windows 10 10.0 amd64

This change is intended? I know installApp is deprecated but installDict also not supported and this change is not listed in the release notes.

**Comment by wilkinsona** [comment]
This is due the [the application plugin no longer being applied by default](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#application-plugin). You should apply it yourself if you want to use its functionality.
