### ISSUE TITLE
root actuator endpoint with management.context-path property does not resolve if it ends with a slash

### ISSUE THREAD

**Issue by sixrandanes** [spring-projects/spring-boot#4575]
Hello,

I use spring-boot 1.3.0.
I add these properties to my project :
```
management:
 port: 8084
 address: 127.0.0.1
 context-path: /admin
```
With this url : `http://localhost:8084/admin/{{endpoint}}` everything works fine with all endpoints except `/actuator`. (404 error)

With this url: `http://localhost:8084/admin/`, I've got 
```
{
"links": []
}
```
When I remove these properties (management.*), the endpoint /actuator is fine.

When I apply this property (management.context-path) against my project, /actuator endpoint is never displayed in my logs (I use logback with your pattern logback-spring.xml)

Thanks for your answer,

**Comment by yurilo** [comment]
@sixrandanes probably it's because of the https://github.com/spring-projects/spring-boot/issues/4401

**Comment by wilkinsona** [comment]
@yurlio #4401 is unrelated as @sixrandanes isn't customising the server's context path just the management context path.

**Comment by wilkinsona** [comment]
> With this url : http://localhost:8084/admin/{{endpoint}} everything works fine with all endpoints except /actuator. (404 error)

This is the expected [and documented](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoint-hypermedia) behaviour:

> When a custom management context path is configured, the “discovery page” will automatically move from `/actuator` to the root of the management context. For example, if the management context path is `/management` then the discovery page will be available from `/management`.

That leaves the problem with the links:

> With this url: http://localhost:8084/admin/, I've got

> ```
{
"links": []
}
```

The problem appears to be that `/admin/` and `/admin` are treated differently. With Spring HATEOAS on the classpath, `/admin/` gives me an empty array of links, however, `/admin` gives me a response with all the expected links to the actuator's other endpoints:

```
$ curl -i localhost:8084/admin
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 24 Nov 2015 10:18:08 GMT

{"links":[{"rel":"self","href":"http://localhost:8084/admin"},{"rel":"trace","href":"http://localhost:8084/admin/trace"},{"rel":"env","href":"http://localhost:8084/admin/env"},{"rel":"autoconfig","href":"http://localhost:8084/admin/autoconfig"},{"rel":"dump","href":"http://localhost:8084/admin/dump"},{"rel":"configprops","href":"http://localhost:8084/admin/configprops"},{"rel":"mappings","href":"http://localhost:8084/admin/mappings"},{"rel":"metrics","href":"http://localhost:8084/admin/metrics"},{"rel":"health","href":"http://localhost:8084/admin/health"},{"rel":"beans","href":"http://localhost:8084/admin/beans"},{"rel":"error","href":"http://localhost:8084/admin/error"},{"rel":"shutdown","href":"http://localhost:8084/admin/shutdown"},{"rel":"info","href":"http://localhost:8084/admin/info"}]}
```

**Comment by sixrandanes** [comment]
OK thank you for your answer.

That's why I didn't see /actuator in my logs when I applied the management.* properties but :
Mapped "{[/admin || /admin.json],produces=[application/json]}" onto public....

So do you think we should have a different behavior between /admin and /admin/ ?

Anyway, thanks a lot for the last release 1.3.0, that's great !

**Comment by wilkinsona** [comment]
We need to redirect `/admin/` to `/admin`.
