### ISSUE TITLE
Register Thymeleaf's Java8TimeDialect by default if on the classpath

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#4576]
Thymeleaf has a special dialect to format Java 8 date/time types just as it supports legacy `Date` instances out of the box.

Currently `thymeleaf-extras-java8time` has to be included manually (Boot doesn't have a managed version for that) and a Spring bean of type `Java8TimeDialect` has to be registered explicitly. Would be cool if that was registered out of the box.

**Comment by shakuzen** [comment]
:+1:
