### ISSUE TITLE
Default Spring profile always deactivated with spring.profiles.include

### ISSUE THREAD

**Issue by nwoike** [spring-projects/spring-boot#4578]
Just looking for verification if this is intended behavior. It appears that using additional profile inclusion from application properties always deactivates the default profile. Tested in 1.3.0.RELEASE.

Perhaps we are just abusing the default profile a bit here.

```
spring.profiles.include: extra
```
[INFO] The following profiles are active: extra

```
spring.profiles.active: default
spring.profiles.include: extra
```
[INFO] The following profiles are active: extra

```
spring.profiles.active: production
spring.profiles.include: extra
```

[INFO] The following profiles are active: extra,production

**Comment by snicoll** [comment]
> Just looking for verification if this is intended behavior.

[Yes](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-profile-specific-properties)
