### ISSUE TITLE
After Upgrade to spring boot 1.3.0 - No Such Bean Exception

### ISSUE THREAD

**Issue by dilgerma** [spring-projects/spring-boot#4581]
Hi have a really strange behavior.
After upgrading to Boot 1.3.0 - the application fails at various points with No Such Beans-Exception whereas the Application worked perfectly in 1.2.7.

I have a demo project, that shows the behavior (nothing fancy... just plain)
Obviously I´m missing something. Maybe you could point me to the correct direction.

The Project is here: https://github.com/dilgerma/spring-boot-1.3.git

There are 2 branches - 
 boot-1.2.7
 boot-1.3.0

In Boot 1.2.7 Build is green, in Boot 1.3.0 Build is red because the Configiured Rest-Template cannot be autowired.

why?

Thanks!

**Comment by dilgerma** [comment]
Its a Spring Cloud Brixton.M3 Problem

**Comment by snicoll** [comment]
I was about to say that. Whenever you provide a sample here, please reduce the dependencies to only what is required. (I did and the error went away).
