### ISSUE TITLE
tomcat.version setting invalid when use dependencyManagement

### ISSUE THREAD

**Issue by wcnjeusr** [spring-projects/spring-boot#4583]
I set tomcat version to 7.0.59 but the tomcat version in war is still 8.0.28
`
<tomcat.version>7.0.59</tomcat.version>
`
dependencyManagement config:
`
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
`
spring-boot.version is 1.3.0.RELEASE

**Comment by wilkinsona** [comment]
[As described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven-without-a-parent) Maven doesn't support overriding properties in a bom when you import it.
