### ISSUE TITLE
LoggingApplicationListener.LOGGING_SYSTEM_BEAN_NAME should be made public

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#4584]
`LoggingApplicationListener.LOGGING_SYSTEM_BEAN_NAME` should be made public so other can reference the final property instead of copy/paste the bean name.

**Comment by snicoll** [comment]
Why? You can inject a bean of type `LoggingSystem` right?

**Comment by brenuart** [comment]
I need to access the configured LoggingSystem inside an ApplicationListener. The auto wiring is not yet available at this point. The original use case that lead to the registration of the LoggingSystem inside the application context is to allow one to implement his own shutdown logic.

**Comment by snicoll** [comment]
gotcha.

**Comment by brenuart** [comment]
We forced a custom LoggingSystem implementation via the `-Dorg.springframework.boot.logging.LoggingSystem` environment property. Our version implements the standard Spring `Lifecycle` interface and I first though the lifecycle methods would be called (at least stop()) simply because you added it as singleton bean into the BeanFactory. Not the case unfortunately.

**Comment by brenuart** [comment]
A second point is you register the LoggingSystem with the BeanFactory upon reception of the `ApplicationPreparedEvent` event which happens _long_ after the logging system has actually been initialised (which occurs at `ApplicationEnvironmentPreparedEvent`).

Some systems like Logback requires to be explicitly started and stopped (some plugins/appenders do require that proper lifecycle). So we implemented our own extension of the `LogbackLoggingSystem` to expose start/stop methods.

Ideally, `start()` should be called immediately after initialisation, i.e. in reaction to the `ApplicationEnvironmentPreparedEvent`. Unfortunately, the logging system is not yet register with the BeanFactory at that moment... So we can't use that feature I'm afraid. Waiting for the `ApplicationPreparedEvent` is not an option as it would delay the final initialisation of the logging system. We could however start the logging system inside the `LogbackLoggingSystem.initialize()` method...

For `stop()`, we listen for `ContextClosedEvent` and `ApplicationFailedEvent` events and make sure they originate from the same ApplicationContext that created our listener. For this, we could lookup the actual implementation by querying the context by bean name or type.
