### ISSUE TITLE
HttpEncodingAutoConfiguration does not implement a RegistrationBean

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#4585]
Hi @wilkinsona,

As discussed in post #4566, the class HttpEncodingAutoConfiguration does not implement a RegistrationBean for the CharacterEncodingFilter.

So this way, the filter is not async by default what could generate issues.

Please see the current code in SpringBoot 1.3.0:
```
@Configuration
@EnableConfigurationProperties(HttpEncodingProperties.class)
@ConditionalOnClass(CharacterEncodingFilter.class)
@ConditionalOnProperty(prefix = "spring.http.encoding", value = "enabled", matchIfMissing = true)
public class HttpEncodingAutoConfiguration {

	@Autowired
	private HttpEncodingProperties httpEncodingProperties;

	@Bean
	@ConditionalOnMissingBean(CharacterEncodingFilter.class)
	public CharacterEncodingFilter characterEncodingFilter() {
		CharacterEncodingFilter filter = new OrderedCharacterEncodingFilter();
		filter.setEncoding(this.httpEncodingProperties.getCharset().name());
		filter.setForceEncoding(this.httpEncodingProperties.isForce());
		return filter;
	}
}
```

**Comment by wilkinsona** [comment]
Please don't deliberately raised duplicate issues.

There's no need for `HttpEncodingAutoConfiguration` to use a registration bean. Any `Filter` bean will be registered automatically using a `FilterRegistrationBean`. As I already explained in #4566, that will mean that async support is enabled by default.
