### ISSUE TITLE
Spring ignoring configurations on properties

### ISSUE THREAD

**Issue by luizkowalski** [spring-projects/spring-boot#4589]
I have a RabbitMQ server like this  
[![enter image description here][1]][1]

When I try to connect to this server via Spring Boot amqp, I see `com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.`

My configs are this one

    # Message
    spring.activemq.broker-url=tcp://127.0.0.1:5672
    spring.activemq.user=test
    spring.activemq.password=test

Yes, the user test can access Virtual Hosts on / and yes, I can login with test/test on RabbitMQ GUI

Looking at the rabbitmq logs, I saw this

    {handshake_error,starting,0,
                 {amqp_error,access_refused,
                             "PLAIN login refused: user 'guest' - invalid credentials",
                             'connection.start_ok'}}

seems like Spring is ignoring my configs and trying to connect with `guest`

  [1]: http://i.stack.imgur.com/HgGW9.png

**Comment by krm1312** [comment]
Shouldn't those properties be spring.rabbitmq prefixed not spring.activemq?

**Comment by luizkowalski** [comment]
you are damn right!

**Comment by wilkinsona** [comment]
Thanks, @krm1312

**Comment by snicoll** [comment]
@luizkowalski don't you have content assistance in your IDE to show you that?

**Comment by snicoll** [comment]
Also @luizkowalski, [do not cross post](http://stackoverflow.com/questions/33880410/spring-boot-cannot-connect-to-rabbitmq) as this is a waste of time for everybody.

**Comment by luizkowalski** [comment]
sorry @snicoll this question was supposed to be closed, actually. Don't know what happened
