### ISSUE TITLE
Inconsistent thread synchronization in EmbeddedWebApplicationContext.java

### ISSUE THREAD

**Issue by mbreslow** [spring-projects/spring-boot#4593]
FindBugs identified an inconsistent thread synchronization issue for spring-boot in the EmbeddedWebApplicationContext class. When finishRefresh() is unsynchronized, it is possible for embeddedServletContainer to be set to null before publishEvent() was called. Synchronizing the method makes all accesses of this field consistent.

**Comment by philwebb** [comment]
Closing in favor of PR #4594
