### ISSUE TITLE
Spring boot 1.3 Actuator problem

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-boot#4596]
When I try to use server context path  with different value than "/" (pizza) Spring actuator does not work fine:

- With /pizza context-path, actuator response is empty (404)

<img width="1440" alt="context_pizza" src="https://cloud.githubusercontent.com/assets/7360956/11366295/a4bbee94-92ac-11e5-8582-984cfc510bed.png">

<img width="1440" alt="error1" src="https://cloud.githubusercontent.com/assets/7360956/11366205/1a850e36-92ac-11e5-8b50-cd9b3e7fe9ad.png">
<img width="1440" alt="error2" src="https://cloud.githubusercontent.com/assets/7360956/11366209/209fbe2e-92ac-11e5-81cb-c869a282b411.png">

- With "/" context-path, actuator response  is 200 ok.

<img width="1440" alt="contextcorrecto" src="https://cloud.githubusercontent.com/assets/7360956/11366296/a4be6570-92ac-11e5-8624-48d649dd29b6.png">
<img width="1471" alt="ok1" src="https://cloud.githubusercontent.com/assets/7360956/11366211/25a4ace0-92ac-11e5-8139-00fe163c1484.png">
<img width="1440" alt="ok2" src="https://cloud.githubusercontent.com/assets/7360956/11366212/25e4e062-92ac-11e5-901f-996d8bc7cdcd.png">

Is there any additional config to be able to use this Spring Boot property in 1.3.0 Version?

My github branch code here:

https://github.com/cristianprofile/spring-boot-mvc-complete-example/tree/developfix_actuator_server_context_path

A lot of thanks for your time!!!!

**Comment by wilkinsona** [comment]
Duplicates #4401

**Comment by cristianprofile** [comment]
@wilkinsona I think this is another issue. I am trying to set server context path . If a put an empty path value app and actuator work fine but when i put a value to server context property ("pizza") actuator does not work.

**Comment by wilkinsona** [comment]
The sample project you've provided doesn't match the screenshots, and there's also an awful lot of it. As far as I can tell the problem that you're seeing is that with both the management context path and the server context path configured, the actuator's using both even when you have the actuator on a separate port. That's the problem described in #4401. If that's not the problem you're seeing, can you please describe it more clearly? Ideally with a _simple_ sample project that illustrates the problem.

**Comment by cristianprofile** [comment]
Sorry @wilkinsona  I have put bad url repo, the is the correct one:
