### ISSUE TITLE
provide documentation for spring-boot-actuator-docs

### ISSUE THREAD

**Issue by cforce** [spring-projects/spring-boot#4597]
What is the project used for?
What features does it provide additionally to spring-boot-actuator?

**Comment by wilkinsona** [comment]
The new functionality is described [in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#actuator-docs-endpoint). It should probably be described in the reference documentation as well. Pull requests welcome.
