### ISSUE TITLE
spring.main.banner-mode=off doesn't work with yml configuration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4600]
This could be an ordering issue and perhaps it's something we can't fix. We should at the very least update the docs.

**Comment by philwebb** [comment]
See #4001 for original feature details.

**Comment by jadekler** [comment]
@philwebb I'm unable to reproduce - see https://github.com/jadekler/git-misc-2/tree/master/boot-banner-properties-off for a super simple spring-boot app that gets its banner turned off [with a properties file](https://github.com/jadekler/git-misc-2/blob/master/boot-banner-properties-off/src/main/resources/application.properties#L1).

(above app is basic start.spring.io app + props file added)

**Comment by snicoll** [comment]
funny. I can't reproduce with a `.properties` file but I can with a `.yml` file.

**Comment by snicoll** [comment]
looks like we'll have to do something similar as https://github.com/spring-projects/spring-boot/commit/c3571d416ad4e4bec688f7272e3840b1d758edef

**Comment by snicoll** [comment]
Unfortunately this is backed by an enum and part of the `SpringApplication` API so there is not much we can do (this is a YAML "issue", really). I've added a dedicated section in the doc instead.

**Comment by Shredder121** [comment]
First of all sorry for not finding this sooner, I only found this after opening #5746  (only searched for `bannerMode`, my bad).
Indeed, this is a [YAML 'issue'](http://yaml.org/type/bool.html), the way booleans are handled clashes directly with the `Banner.Mode.OFF` enum constant.
That is quite unfortunate though.

**Comment by jamesbates** [comment]
actually, this does work, in application.yml:

```
spring:
  main:
    banner-mode: 'off'
```

**Comment by snicoll** [comment]
@jamesbates this very issue was about documenting that, see https://github.com/spring-projects/spring-boot/commit/43b8e65eee7c23a7f7c3b61f8a436dc9cbfe5b96
