### ISSUE TITLE
spring-boot-starter-data-gemfire starts Jetty

### ISSUE THREAD

**Issue by pawelantczak** [spring-projects/spring-boot#4601]
Hello.
In ```1.2.4```, having  ```spring-boot-starter-data-gemfire``` was not triggering embedded server to start.
Now, in ```1.3.0```, when I'm starting app with ```spring-boot-starter-data-gemfire``` in ```pom.xml```, Jetty is bootstrapped. 
Is it intended behavior?

**Comment by philwebb** [comment]
It looks like Gemfire 8.1.0 now has a dependency on Jetty for some reason, this wasn't the case with Gemfire 7.0.2. Actually it looks like Gemfire 8.1.0 now pulls in a whole host of [new dependencies](https://maven-repository.com/artifact/com.gemstone.gemfire/gemfire/8.1.0/pom).

Gemfire 8.2.0 seems to have [restored some sanity](https://maven-repository.com/artifact/com.gemstone.gemfire/gemfire/8.2.0/pom) by making most dependencies optional.

**Comment by philwebb** [comment]
@jxblum Do you know anything about these changes? @wilkinsona Is an upgrade to 8.2.0 going to cause problems with the platform?

**Comment by philwebb** [comment]
@panchenko Can you try upgrading to Gemfire 8.2.0 or excluding the Jetty dependency?

**Comment by pawelantczak** [comment]
If last message was to me, sure. Excluding ```Jetty``` helps.

**Comment by philwebb** [comment]
@pawelantczak Sorry, managed to auto-complete the wrong GitHub handle. It was indeed meant for you, I've updated the comment.

**Comment by jxblum** [comment]
@philwebb - Yes, [GemFire 8.1.0](http://gemfire81.docs.pivotal.io/latest/userguide/index.html#relnotes/release_notes.html#topic_5mbwjl__section_s55_535_v4) switched from *Tomcat* to *Jetty* as it's embedded HTTP container for hosting the web services (Developer and Management REST APIs and Pulse, the management/monitoring webapp-based tool).

Now that *Spring Boot* **1.3** is on *GemFire 8.1.0* ([here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L71)) and also ([here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L135)), which corresponds to [SDG 1.7](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Gosling#spring-data-gemfire---17) that is based on *GemFire 8.1.0* ([here](https://github.com/spring-projects/spring-data-gemfire/blob/1.7.1.RELEASE/gradle.properties#l4)), SB will pick up the switch.

[Previously](https://github.com/spring-projects/spring-boot/blob/v1.2.7.RELEASE/spring-boot-dependencies/pom.xml#L66), *Spring Boot* (1.2.x) was tied to *GemFire 7.0.2*, also derived from [spring-data-evans-SR4](https://github.com/spring-projects/spring-boot/blob/v1.2.7.RELEASE/spring-boot-dependencies/pom.xml#L118), which includes [SDG 1.5](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Evans#spring-data-gemfire---15) that is based on [GemFire 7.0.2
(https://github.com/spring-projects/spring-data-gemfire/blob/1.5.4.RELEASE/gradle.properties#L4).

**Comment by philwebb** [comment]
@jxblum The odd thing is that the Tomcat dependency in 7.0.2 used to be optional where as the Jetty dependency is not. I wonder if this is a simple mistake in the POM since Jetty is only really needed if you want to run the hosted web services?

**Comment by jxblum** [comment]
@philwebb Hmm, well, I am showing the dependency in the [GemFire 8.1.0 POM](http://dist.gemstone.com/maven/release/com/gemstone/gemfire/gemfire/8.1.0/gemfire-8.1.0.pom) file as...

````xml
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-webapp</artifactId>
      <version>${jetty.version}</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
````

**Comment by jxblum** [comment]
@philwebb Here is a dependency graph on an application that only pulls in GemFire...

````
INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ example-gemfire-app ---
[INFO] com.example:example-gemfire-app:jar:1.0.0.BUILD-SNAPSHOT
[INFO] \- com.gemstone.gemfire:gemfire:jar:8.1.0:compile
[INFO]    +- antlr:antlr:jar:2.7.7:runtime
[INFO]    +- commons-io:commons-io:jar:2.3:runtime
[INFO]    +- commons-logging:commons-logging:jar:1.1.1:runtime
[INFO]    +- org.apache.logging.log4j:log4j-api:jar:2.1:compile
[INFO]    +- org.apache.logging.log4j:log4j-core:jar:2.1:compile
[INFO]    +- org.eclipse.jdt.core.compiler:ecj:jar:3.7.2:runtime
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.2.0:runtime
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.2.0:runtime
[INFO]    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.2.0:runtime
[INFO]    +- net.sourceforge.jline:jline:jar:1.0.S2-B:runtime
[INFO]    +- org.eclipse.jetty:jetty-webapp:jar:9.2.3.v20140905:runtime
[INFO]    |  +- org.eclipse.jetty:jetty-xml:jar:9.2.3.v20140905:runtime
[INFO]    |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.3.v20140905:runtime
[INFO]    |  \- org.eclipse.jetty:jetty-servlet:jar:9.2.3.v20140905:runtime
[INFO]    |     \- org.eclipse.jetty:jetty-security:jar:9.2.3.v20140905:runtime
[INFO]    |        \- org.eclipse.jetty:jetty-server:jar:9.2.3.v20140905:runtime
[INFO]    |           +- javax.servlet:javax.servlet-api:jar:3.1.0:runtime
[INFO]    |           +- org.eclipse.jetty:jetty-http:jar:9.2.3.v20140905:runtime
[INFO]    |           \- org.eclipse.jetty:jetty-io:jar:9.2.3.v20140905:runtime
[INFO]    +- org.fusesource.jansi:jansi:jar:1.8:runtime
[INFO]    +- org.xerial.snappy:snappy-java:jar:1.0.4.1:runtime
[INFO]    +- org.springframework.shell:spring-shell:jar:1.0.0.RELEASE:runtime
[INFO]    |  \- cglib:cglib:jar:2.2.2:runtime
[INFO]    |     \- asm:asm:jar:3.3.1:runtime
[INFO]    +- org.springframework:spring-web:jar:3.2.11.RELEASE:runtime
[INFO]    |  +- org.springframework:spring-aop:jar:3.2.11.RELEASE:runtime
[INFO]    |  |  \- aopalliance:aopalliance:jar:1.0:runtime
[INFO]    |  +- org.springframework:spring-beans:jar:3.2.11.RELEASE:runtime
[INFO]    |  +- org.springframework:spring-context:jar:3.2.11.RELEASE:runtime
[INFO]    |  |  \- org.springframework:spring-expression:jar:3.2.11.RELEASE:runtime
[INFO]    |  \- org.springframework:spring-core:jar:3.2.11.RELEASE:runtime
[INFO]    \- xom:xom:jar:1.2.5:runtime
````

**Comment by philwebb** [comment]
I'm very confused, there seems to be a difference in the two published POMs

```
$ curl http://repo.spring.io/gemstone-release-cache/com/gemstone/gemfire/gemfire/8.1.0/gemfire-8.1.0.pom | grep --context=5 jetty

      <artifactId>jline</artifactId>
      <version>${jline.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-webapp</artifactId>
      <version>${jetty.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.fusesource.jansi</groupId>
      <artifactId>jansi</artifactId>
```

```
$ curl http://dist.gemstone.com/maven/release/com/gemstone/gemfire/gemfire/8.1.0/gemfire-8.1.0.pom | grep --context=5 jetty

      <version>${jackson.version}</version>
      <scope>compile</scope>
    </dependency>
    <!-- org.fusesource.jansi:jansi:1.8; GemFire Gfsh "optiona", "runtime" dependency -->
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-webapp</artifactId>
      <version>${jetty.version}</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.jline</groupId>

```

**Comment by philwebb** [comment]
@jxblum The dependency graph that you added also shows Jetty as non-optional.

**Comment by jxblum** [comment]
@philwebb I suppose since *Jetty* is an "optional", "runtime" dependency, and not explicitly declared as a dep with scope "provided", that Maven is going to include it (doh).  Any additional exclusions needed by GemFire can be added [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/spring-boot-starter-data-gemfire/pom.xml#L25-L34) in the *spring-boot-starter-data-gemfire*.

As side note, I am also wondering if the GemFire dependency in the *spring-boot-starter-data-gemfire* should just be on SDG itself?

**Comment by philwebb** [comment]
If it's `optional` it will be ignored by Maven. The problem seems to be that it's only marked as optional at `dist.gemstone.com`. The copy on `repo.spring.io` is missing `<optional>true</optional>. (see above).

**Comment by jxblum** [comment]
@philwebb Yeah, I am not intimately familiar with how the repo.spring.io "refreshes" from the source (dist.gemstone.com).  I thought this to be automatic, but perhaps it needs a push (errr, rather, (manual) pull/update).  However, the GemFire cache in repo.spring.io is just a mirror, AFAIK.

**Comment by philwebb** [comment]
Unfortunately I don't think a refresh is going to work since release POMs could already be cached locally. It's a very odd situation, I can only assume that the 8.1.0 POM on `dist.gemstone.com` was published more than once.

**Comment by philwebb** [comment]
@pawelantczak We've managed to reset `repo.spring.io` which had somehow managed to cache the old version. Does clearing out your local `~/m2/repository/com/gemstone` cached copy and rebuilding fix things?

**Comment by philwebb** [comment]
@jxblum Thanks for the help tracking down the discrepancy. Trevor has reset the `repo.spring.io` copy and things seem to be back in sync. Anyone with a locally cached version will need to manually clear it.

**Comment by pawelantczak** [comment]
@philwebb yep. Thanks, all of you, for engagement and instant fix.

**Comment by philwebb** [comment]
Cool. Thanks for testing.
