### ISSUE TITLE
Document health indicator names and possibly provide override support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4602]
I don't think we currently document that the names used in the health indicator endpoint are bean named (with `HealthIndicator` removed). We might also want to consider a way for users to override the name directly.

**Comment by snicoll** [comment]
:+1:

**Comment by snicoll** [comment]
I went ahead with a documentation update only. The names are currently computed in the constructor of `HealthEndpoint` so making `getKey` protected is wrong. If the need should arise (I haven't seen anybody complaining so far), we should probably replace the `Map<String, HealthIndicator> healthIndicators` argument by some new API that wrap the collections and the logic to compute the name.
