### ISSUE TITLE
annotation aspect is not working spring boot using compile time weaving.

### ISSUE THREAD

**Issue by prabhabisht** [spring-projects/spring-boot#4610]
In my project I m using some aspect as part of my project and some as part of common library, the first request take time of 10 second as we are using default weaving concept of spring boot so we try to switch on CTW(compile time weaving) using aspectj-maven-plugin(1.7).
The time has been reduced , aspects with execution ( @Around("execution(public com.XXXX.XXXXX.common.XXXX.APIErrorResponse *(..))")) is working but the aspect on annotation ( @Around("@annotation(com.xxxxxx.XXX.common.xxx.Loggable)")) is not working(as I have create Loggable annotation to apply entry exit logging), & while compiling I get following warning as well.

[WARNING] advice defined in com.xx.xx.xx.xx.LoggerAspect has not been applied [Xlint:adviceDidNotMatch]

I am using following configuration plugin in my pom.xml
ajc (1.8.1) and compliance level 1.8. 

Any help will be appreciated.

**Comment by snicoll** [comment]
Please [do not cross post](http://stackoverflow.com/questions/33917818/annotation-aspect-is-not-working-spring-boot-using-compile-time-weaving) as this is a waste of time for everybody.

**Comment by prabhabisht** [comment]
Sorry snicoll :( , Iwas jus adding more details.. do you have any idea about this problem. :)
