### ISSUE TITLE
spring boot should log default profile(s) being used if no other profile is active 

### ISSUE THREAD

**Issue by philnate** [spring-projects/spring-boot#4612]
Spring boot currently logs `No profiles are active` if no active profiles are found. This is a bit misleading if a default profile is set, as this will not be outputed. This leads to the suspicion that no profile is active, at all.
I think it would be better to log something along `No active profile set, falling back to default profiles {}` in case default profiles are set.

**Comment by vpavic** [comment]
:+1:
