### ISSUE TITLE
Invalid regex RelaxedNames.Manipulation#CAMELCASE_TO_UNDERSCORE

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4613]
IntelliJ IDEA is using `RelaxedNames.Manipulation#CAMELCASE_TO_UNDERSCORE` and managed to get the following exception

```
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
```

I don't have more details but we should double check that regexp.

**Comment by dsyer** [comment]
You would get this from trying to create `RelaxedNames` for a property with a "$" followed by a capital letter. Example:

```
		Matcher matcher = CAMEL_CASE_PATTERN.matcher("foo$Bar");
		StringBuffer result = new StringBuffer();
		while (matcher.find()) {
			matcher.appendReplacement(result, matcher.group(1) + '_'
					+ StringUtils.uncapitalize(matcher.group(2)));
		}
		matcher.appendTail(result);
		assertEquals("foo$_bar", result.toString());
```

**Comment by dsyer** [comment]
I guess this would fix it:

```
matcher.group(1) -> matcher.group(1).replace("$","\\$")
```

Is it worth the extra runtime processing cost?

**Comment by snicoll** [comment]
as long as it does not fail on heap, I am fine with not supporting that use case.

**Comment by snicoll** [comment]
> Is it worth the extra runtime processing cost?

Probably not.
