### ISSUE TITLE
db table creation failed because reserved word

### ISSUE THREAD

**Issue by dubu** [spring-projects/spring-boot#4614]
module:
spring-boot-sample-data-jpa 

```
HHH000389: Unsuccessful: create table review (id bigint not null auto_increment, check_in_date date not null, details varchar(5000) not null, index integer not null, rating integer not null, title varchar(255) not null, trip_type integer not null, hotel_id bigint not null, primary key (id))
```

when jpa create hibernate ddl auto  in mysql
"review"  table creation failed because of reserved word "index"

Reference : 
Table 9.2 Keywords and Reserved Words in MySQL 5.0
http://dev.mysql.com/doc/refman/5.0/en/keywords.html

**Comment by snicoll** [comment]
Thanks, have you signed the CLA?

**Comment by snicoll** [comment]
@dubu are you going to submit a PR for this?

**Comment by dubu** [comment]
The issue has already been resolved
close.

**Comment by snicoll** [comment]
Duplicates #752

**Comment by snicoll** [comment]
Indeed, over a year ago!
