### ISSUE TITLE
Possibility to disable hypermedia for actuator endpoints

### ISSUE THREAD

**Issue by lbeuster** [spring-projects/spring-boot#4616]
It would be nice if it was possible to disable the hypermedia feature for the actuator endpoints.

Currently this behavior is implemented by 
`EndpointWebMvcHypermediaManagementContextConfiguration.MvcEndpointAdvice`, and I couldn't find a possibility to disable only this advice. 

I have hateoas in the classpath (because of swagger) and like the /actuator endpoint, but not the modified output of the other actuator endpoints. Not all clients can work with the new output.

Or did I miss something?

**Comment by philwebb** [comment]
This looks like an oversight on our part, I think we should offer a way to disable this. We'll try to add something for 1.3.1.

**Comment by wilkinsona** [comment]
We discussed this a little bit on Slack a week or so ago and came to the conclusion that, at least for the endpoints where adding the links changes the response from an array to a map, this needs to be disabled by default.

**Comment by dsyer** [comment]
I think I'm going to switch all the hypermedia off in the endpoints by default (except /actuator). It doesn't add anything IMO (unfinished work really).
