### ISSUE TITLE
spring-boot-maven-plugin should kill forked JVM when parent build process dies

### ISSUE THREAD

**Issue by oliverdennis** [spring-projects/spring-boot#4620]
It would be very useful when spring-boot:start is used if the forked child process was killed when/if the parent maven build process dies. This is particularly important when a build fails during integration test as the post-integration-test stop step is never executed.

I have a version of the code that does this very simply by registering a shutdown hook when the child is started;

In StartMojo, runProcess;

```
final RunProcess runProcess = new RunProcess(new JavaExecutable().toString());
runProcess.run(false, args.toArray(new String[args.size()]));
Runtime.getRuntime().addShutdownHook(new Thread() {
    @Override
    public void start() {
        runProcess.kill();
    }
});
return runProcess;

```

**Comment by snicoll** [comment]
Interesting. Can you submit a PR and sign the CLA please?

**Comment by oliverdennis** [comment]
Hi Stéphane,

I have created a pull request for this, not sure what you meant by sign the CLA though? Sorry I'm a first timer

**Comment by snicoll** [comment]
Olivier,
>  This is particularly important when a build fails during integration test as the post-integration-test stop step is never executed.

You meant _dies_ and not _fails_ right? If the `integration-test` phase fails (whatever the reason) Maven will execute the `post-integration-test` phase. Can you provide a concrete example of what's happening?

**Comment by oliverdennis** [comment]
We run protractor E2E testing as part of our integration-test phase, it seems that when some of these tests fail, particularly if the error is some type of angular timeout rather than a genuine assertion failure that the maven build terminates without running the post-integration-test phase.

I have signed the CLA now by the way :-)

**Comment by snicoll** [comment]
Sounds like more an issue to fix on the Maven side IMO. Can you be a bit more specific about the error please?

**Comment by oliverdennis** [comment]
Actually I have just created a very simple example using the surefire plugin. It seems the post-integration-test phase is never run if the integration-test phase has failures. If you see the attached pom this project runs a single test (which fails) and then tries to load some properties from a file. As you can see from the attached build log the properties file is never read

[pom.txt](https://github.com/spring-projects/spring-boot/files/45094/pom.txt)
[buildlog.txt](https://github.com/spring-projects/spring-boot/files/45095/buildlog.txt)

**Comment by oliverdennis** [comment]
Sorry ignore that, just realised it's being picked up as a unit test. Will come back with an example shortly

**Comment by oliverdennis** [comment]
OK, see the updated files attached. Slightly modified pom but the effect is the same

[buildlog.txt](https://github.com/spring-projects/spring-boot/files/45100/buildlog.txt)
[pom.txt](https://github.com/spring-projects/spring-boot/files/45099/pom.txt)

**Comment by snicoll** [comment]
@oliverdennis that's not how integration tests are supposed to be executed. You should use the `maven-failsafe-plugin` and it will properly honour the phase. I am closing this for now, feel free to reopen if you're still having the issue with the failsafe plugin (but then provide the link to a sample project please).

**Comment by oliverdennis** [comment]
For E2E testing we cannot use the failsafe plugin. We have to use gulp to execute our protractor tests

**Comment by snicoll** [comment]
I am afraid there is nothing I can do for you, this is how you're supposed to run integration tests with Maven. I fail to see what the problem might be with failsafe though but that's a discussion for the Maven mailing list.
