### ISSUE TITLE
provide spring-boot-example to show how to use different databases at runtime. 

### ISSUE THREAD

**Issue by winkumar** [spring-projects/spring-boot#4633]
I have meta database it contain all resource database connectivity information. when request came from use i need check database connection from meta database. get database connection from meta database and create new resource database connectivity and access user data. how to achieve use spring boot and spring-data-jpa. thanks.

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues) (and we reminded you in #4555 already!), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)

**Comment by winkumar** [comment]
I need some help about multi tenant with spring boot. i not get any clear idea.
