### ISSUE TITLE
A classloader problem of spring boot devtools

### ISSUE THREAD

**Issue by zhugw** [spring-projects/spring-boot#4636]
Latest I encountered a problem when develop with devetools, that is I hava a `@RequestBody GoodsForm form`, then in controller it will convert to `Goods` Entity by dozer.
```
GoodsForm:
List<GoodsPriceForm> priceList;

Goods:
List<GoodsPrice> priceList; 

Controller:
Goods goods = BeanMapper.map(goodsForm, Goods.class);
``` 
In service after saving goods, iterate goods price list to populate goodsId,
```
goods.getPriceList().forEach(p->p.setGoodsId(goods.getId()));
```
this step it throws exception,
```
java.lang.ClassCastException: com.foo.goods.model.GoodsPrice cannot be cast to com.foo.goods.model.GoodsPrice
at com.foo.goods.service.GoodsService$$Lambda$11/310447431.accept(Unknown Source) ~[na:na]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_51]
at com.foo.goods.service.GoodsService.saveGoods(GoodsService.java:34) ~[classes/:na]
```
After trying some way to solve this problem, I got the reason is used devtools. For example in eclipse debug mode's expression view, I outputed the classloader name,
```
Goods: org.springframework.boot.devtools.restart.classloader.RestartClassLoader@41aa15ea
GoodsPrice:  sun.misc.Launcher$AppClassLoader@58644d46
```
they are loaded by diff classloader.

And if I commented devtools in pom.xml there is no above exception. So if I want to keep devtools in pom, how to solve this?

**Comment by snicoll** [comment]
Please check [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload)

Duplicates #3316

**Comment by zhugw** [comment]
Hey, I tried put a META-INF/spring-devtools.properties in my project classpath, the content is
```
restart.include.dozer=/dozer-5.5.1.jar
```
but sttill have this exception, what I miss?

**Comment by zhugw** [comment]
After putting `META-INF/spring-devtools.properties` inside resources foleder, solve that problem.

**Comment by zhugw** [comment]
@snicoll Thanks for your replying. I post this problem at stackoverflow, it's url 
http://stackoverflow.com/questions/33955542/a-dozer-map-exception-related-to-spring-boot-devtools
