### ISSUE TITLE
upgrade elastic search dep to 1.7.x

### ISSUE THREAD

**Issue by vijayrawatsan** [spring-projects/spring-boot#4646]

**Comment by wilkinsona** [comment]
We align our Elasticsearch dependency with that of Spring Data Elasticsearch. Spring Boot currently uses Spring Data Elasticsearch 1.3.1 which uses Elasticsearch 1.5.2. We'll upgrade our Elasticsearch dependency as a matter of course when we move to a new version of Spring Data Elasticsearch.
