### ISSUE TITLE
Does still exist more convenient manner to create blank spring boot project

### ISSUE THREAD

**Issue by zhugw** [spring-projects/spring-boot#4648]
Although create a blank web project or non-web project online(https://start.spring.io/) is easy, you still have to access web, unzip, import to IDE. So does still exist more convenient manner to create blank spring boot project? e.g. in shell command.

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com)

Having said that, check the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#cli-init)
