### ISSUE TITLE
devtools and spring-session problem

### ISSUE THREAD

**Issue by xia5271** [spring-projects/spring-boot#4649]
now i have a problem and i create a simple project https://github.com/xia5271/demo-devtools-restart ,when i use spring-boot-devtools and spring-session at the same time,@AuthenticationPrincipal cant work(https://github.com/xia5271/demo-devtools-restart/blob/master/src/main/java/com/github/xia5271/devtools/security/LoginController.java#L18 ),i track problem in spring-security-web-4.0.3.RELEASE-sources.jar!/org/springframework/security/web/method/annotation/AuthenticationPrincipalArgumentResolver.java:115 ,how can i fix it

**Comment by snicoll** [comment]
I guess it duplicates #3805 - can you confirm this is the same stacktrace?

**Comment by wilkinsona** [comment]
@snicoll I think this is a different problem. The comment in `LoginController` says the the user is `null`. That would suggest that it's not blowing up with an exception.

**Comment by snicoll** [comment]
for some reason (sub-text: lack of coffee), I missed the comment :( Thank you

**Comment by xia5271** [comment]
in  spring-security-web-4.0.3.RELEASE-sources.jar!/org/springframework/security/web/method/annotation/AuthenticationPrincipalArgumentResolver.java:115  parameter.getParameterType().isAssignableFrom(principal.getClass()) return false,because parameter.getParameterType() loaded by RestartClassLoader and principal.getClass() is Launcher$AppClassLoader ,so its the same problem,tks

**Comment by wilkinsona** [comment]
@xia5271 There's also some similarity to #3316. Please see the discussion in that issue and [this section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload) for some further information.
