### ISSUE TITLE
When a YAML collections accessor calls a copy constructor, the resulting collection appears empty

### ISSUE THREAD

**Issue by adamburleybarclays** [spring-projects/spring-boot#4650]
If you have an accessor (getter) in a `@ConfigurationProperties`-annotated class to retrieve a collection, and if you call the copy constructor in that accessor, the returned collection appears to be empty.

Example YAML file ("example.yml"):

```
one:
   two:
      - three
      - four
      - five
```

Example Spring Controller:

```java
@RestController
public class ExampleController {
    @Autowired
    private ExampleYamlStore exampleYamlStore;

    @RequestMapping({"/*"})
    public String index() {
        List<String> two = exampleYamlStore.getTwo();
        String str;
        if (two.size() == 0) {
            str = "Size was zero";
        } else {
            str = two.get(0) + ","
                    + two.get(1) + ","
                    + two.get(2);
        }
        return "RESULT: " + str;
    }
}
```

Example YAML store (without copy constructor in accessor):

```java
@Component
@ConfigurationProperties(locations = "classpath:/example.yml", prefix = "one")
public class ExampleYamlStore {
    private List<String> two = new ArrayList<>();

    public List<String> getTwo() {
        return two; // ***MARKED LINE***
    }

    public void setTwo(List<String> two) {
        this.two = new ArrayList<>(two);
    }
}
```

Running this code and hitting http://localhost:8080/foo will give the response "RESULT: three,four,five" as expected.

However if you change the marked line above to:

```java
return new ArrayList<>(two);
```

Then hit http://localhost:8080/foo - you will get the response "RESULT: Size was zero".

Spring Boot should allow consumers to return a copy of a collection, to prevent any caller from modifying the internal collection. Are you retrieving the list somewhere internally and then modifying it but not setting it back onto the `@ConfigurationProperties`-annotated class?

I am using the latest version of Spring Boot (1.3.0) and Java 1.7.

**Comment by philwebb** [comment]
Binding is actually handled by the core Spring Framework. You can raise an issue at [jira.spring.io](http://jira.spring.io) but I believe the current behavior is by design. Specifically if you look at `AbstractNestablePropertyAccessor.setPropertyValue()` you can see that the code is designed to mutate an existing collection, rather then replace it.
