### ISSUE TITLE
Support to filter/query the Actuator Metric Endpoint

### ISSUE THREAD

**Issue by RobWin** [spring-projects/spring-boot#4654]
It would be nice, if you could query the Metrics Endpoint and just retrieve a subset of the data based on a filter.

Something like `curl -XGET 'http://localhost:8080/metrics?fields=heap,heap.committed'`

RegEx support would be great. Maybe similar to a ElasticSearch regexp query.

It would be useful, if you could group Metrics and then filter for `?groups=jvm,mem`

**Comment by wilkinsona** [comment]
1.3 already has [regex support for the metrics and env endpoints](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#regex-support-for-env-and-metrics)

**Comment by RobWin** [comment]
Thx. Can I also query multiple fields with it?

**Comment by wilkinsona** [comment]
The regex matches against the metric name. For example, all metrics that begin with `heap` can be retrieved with `heap.*`

**Comment by RobWin** [comment]
But isn't it a bit complex, if you just want to retrieve multiple fields like heap, mem. For example just all system Metrics. 
See #4655 for my reason.

**Comment by philwebb** [comment]
It seems like it might be a sensible addition, although I'm a little nervous that we might be adding too many ways of doing the same thing. In the context of #4655 it does make more sense.

I've re-opened marked it for some more discussion.

**Comment by RobWin** [comment]
Thx.

**Comment by RobWin** [comment]
If you think its a good idea, I could contribute it.

**Comment by philwebb** [comment]
We discussed this a little today and the general feeling is that this might be adding too much to the existing endpoint. Specifically we already have path based filtering, so adding query parameters as well is a little confusing.

One option that might for your instance is pipe the output though to a different unix tool to do the filtering. Dave's provided a sample with the JSON output [here](https://github.com/spring-projects/spring-boot/issues/4655#issuecomment-161335898).

**Comment by RobWin** [comment]
Yes. Thx for your answer.
