### ISSUE TITLE
Support to output Metrics in Linux format

### ISSUE THREAD

**Issue by RobWin** [spring-projects/spring-boot#4655]
ElasticSearch has a nice Cat API which is useful to monitor a node via Linux tools like curl, grep, awk, sed. https://www.elastic.co/guide/en/elasticsearch/reference/1.4/cat.html

I think it would be a nice feature for the Actuator Metrics Endpoint as well. 
Combined with #4654 it could be

`curl -XGET 'HTTP:localhost:8080/metrics?format=cat&fields=heap,heap.committed'`
```
heap heap.committed
7656473 3241526
```

You could pipe other commands like sort, grep if you wish.

**Comment by philwebb** [comment]
Nice idea.

**Comment by RobWin** [comment]
Should the `format` be a query Parameter or Media Type header.

**Comment by philwebb** [comment]
Feels like content negotiation might be the better way of triggering it. Perhaps

```
ACCEPT: text/plain
```

would be enough?

**Comment by dsyer** [comment]
I'm quite happy to push this down to the client. E.g.

```
$ curl localhost:8080/metrics | jq -r '"heap heap.used\n\(.heap) \(.["heap.used"])"'
heap heap.used
784896 364304
```

**Comment by RobWin** [comment]
Ok. Thx. I have a look at jq.

**Comment by philwebb** [comment]
Let us know if that works for you, It might be the simplest solution in the end and save us adding extra logic to the endpoints.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by RobWin** [comment]
Yes it helps. Thx.

**Comment by wilkinsona** [comment]
Thanks for letting us know, @RobWin.
