### ISSUE TITLE
Drops CONFIG and FINER log levels of java.util.logging

### ISSUE THREAD

**Issue by joshattr** [spring-projects/spring-boot#4663]
Spring boot appears to drop log statements logged with a `CONFIG` or `FINER` level using java.util.logging. I might be reading the source wrong here, and I'm unsure how to confirm this because it also [doesn't let you log lower than `INFO`](https://github.com/spring-projects/spring-boot/issues/2923), as I understand it (I have been able to confirm this be adding `log.levels.ROOT=DEBUG` to my `application.properties` and not seeing my logs with a level of `FINE`/`FINER`/`FINEST`).

Here's where I think the problem is: https://github.com/spring-projects/spring-boot/blob/0088300ecaad0e9ed389ef974983d723eaa72ead/spring-boot/src/main/java/org/springframework/boot/logging/java/JavaLoggingSystem.java#L51-L57

As an aside, wouldn't it be good if log levels were respected across logging libraries? That way you could still configure all libraries to use a certain level, but you could configure your specific library to behave the way you expect, given the logging library it's using. By defining your own levels that don't at least translate 1-1 with the library that has the most logging levels (which appears to be java.util.logging, but might be something else), you necessarily lose precision, and probably get more/less logging than you expected when using that library. This is a separate issue than the above two paragraphs.

**Comment by snicoll** [comment]
I'd rather go with the second part of the issue than the first unless I misunderstood it. The fact that you don't get `CONFIG` and `FINER`level with the abstraction sounds "alright" to me. The abstraction goes with a reasonable amount of logging levels that match pretty much every logging library out there (sic) but for some reason JUL decided to go crazy about this.

That's said, if you write `logging.level.com.acme.foo=CONFIG` we might translate that properly for JUL but then you're using that infrastructure for configuration purposes and not for the abstraction.

**Comment by joshattr** [comment]
The config v abstraction makes sense to me. Less control over your logging library is fine, but I don't think dropping logs is. How about merging `CONFIG` into `DEBUG` and `FINER` into `TRACE`?

**Comment by snicoll** [comment]
On a more closer look (thanks @wilkinsona), `CONFIG` is between `INFO` and `FINE` and `FINER` is between `FINE` and `FINEST`. Since we map `FINEST` (to `TRACE`), I don't really see how we could "drop logs".  Can you please  share an example that shows that logs are dropped.

As for allowing logging library specific log level in the abstraction we decided not to do that for the reason I mentioned (using the infrastructure for configuration purposes).

**Comment by joshattr** [comment]
I'll try to spin up an example sometime in Jan when my projects calm down a bit. I might be wrong :smile:

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
