### ISSUE TITLE
Prevent an auto-configured bean definition from overriding a user's bean definition

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4667]
When we add a new bean definition in an auto-configuration class we run the risk of that new definition inadvertently overriding a user's bean definition. This can cause unexpected behaviour, such as the auto-configured bean being used when the user-configured bean should have switched it off. See #4664 for an example.

I can't think of a scenario where you'd want an auto-configured bean to override a user-configured bean, particularly when they're of the same type. Perhaps there is one and I'm just not being sufficiently imaginative. Either way, the current behaviour is surprising and relatively hard to diagnose as the log message about a bean being overridden is logged at `INFO` level so it's easy to miss it.

**Comment by wilkinsona** [comment]
I wonder if we could use a custom strategy for naming beans that are created via auto-configuration? That might then go some way to addressing #4442 as well.

**Comment by philwebb** [comment]
Duplicates #13609 which was fixed in 2.0.0
