### ISSUE TITLE
spring-boot-devtools: restart doesn't happen if project is named spring-boot

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-boot#4673]
Given the following maven project (for file content see: https://gist.github.com/mvitz/4965eb1db68a0ffa63bf) : 
```
$ tree
.
├── pom.xml
└── src
    └── main
        └── java
            └── com
                └── FoobarApplication.java

4 directories, 2 files

$ pwd
/tmp/foobar
```

If this project is imported into eclipse and run from there everything works as expected.

But if
```
$ pwd
/tmp/foo-bar
```
restart of the application after a change doesn't work any longer.

Took me multiple hours to find out why my project didn't work.

**Comment by mvitz** [comment]
Hm. After another test it's not the dash that's producing the failure...

**Comment by wilkinsona** [comment]
I didn't think it would be. Our sample for DevTools is named `spring-boot-sample-devtools` and it works fine. If you can provide a sample that shows the restart not happening we can take a look.

**Comment by mvitz** [comment]
Steps I did:
```
$ cd /tmp
$ git clone git@github.com:mvitz/notejam.git
$ cd notejam
$ git co spring-boot
```

In Eclipse:
- Import -> Existing Maven Project -> /tmp/notejam/spring-boot
- Run com.github.komarserjio.notejam.springboot.NotejamApplication as 'Java Application'

Result:
- Application is running
- When I change anything the restart isn't triggered

**Comment by mvitz** [comment]
I'm currently trying some things:

After the following steps everything worked:
```
$ cd /tmp/notejam
$ rm -rf spring-boot/{.project,.classpath,.settings,target}
$ git mv spring-boot springboot
```

In Eclipse:
- Import -> Existing Maven Project -> /tmp/notejam/springboot
- Run com.github.komarserjio.notejam.springboot.NotejamApplication as 'Java Application'

Result:
- Application is running
- When I change anything the restart __is__ triggered

This is why I thought the dash was the problem.

**Comment by mvitz** [comment]
Next guess: Doesn't work if the folder is named `spring-boot`.

If you put the example given in https://github.com/spring-projects/spring-boot/issues/4673#issue-120197050 into `/tmp/spring-boot` it doesn't work. The sample example in `/tmp/foo-bar` works.

**Comment by mvitz** [comment]
I found it: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/server/DefaultSourceFolderUrlFilter.java#L44
Maybe a note that these folder names aren't working somewhere would have saved me a few hours of digging around... ;-)

**Comment by wilkinsona** [comment]
Yes, that's it. DevTools deliberately ignores a number of Spring Boot modules:

```
	private static final Set<String> SKIPPED_PROJECTS = new HashSet<String>(
			Arrays.asList("spring-boot", "spring-boot-devtools",
					"spring-boot-autoconfigure", "spring-boot-actuator",
					"spring-boot-starter"));
```

Sorry, it doesn't look like this is documented. We'll use this issue to correct that.
