### ISSUE TITLE
SpringApplication should log exception *before* RunListener.finished() method is invoked

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#4680]
It would be nice if `SpringApplication.handleRunFailure()` logs the exception *before* invoking the registered `SpringApplicationRunListener` to notify them about the `finished` event.

As per the javadoc:
```
        /**
	 * Called immediately before the run method finishes.
	 * @param context the application context
	 * @param exception any run exception or null if run completed successfully.
	 */
	void finished(ConfigurableApplicationContext context, Throwable exception);
```

Logging the exception before invoking the listeners for the last time would allow us to - for instance - to properly shutdown the logging system at that moment. Unfortunately doing so is not possible since it would discard the log with the exception message.

**Comment by jadekler** [comment]
@brenuart Is [this](https://github.com/spring-projects/spring-boot/pull/4686) what you were thinking?

**Comment by brenuart** [comment]
Yes. That would be perfect imho.
