### ISSUE TITLE
Add Spring Boot Resource Handling support for GzipResourceResolver

### ISSUE THREAD

**Issue by mnhock** [spring-projects/spring-boot#4683]
There is a pretty good spring boot resource handling support with the `spring.resources.chain.*` configuration available already.

It would be great if there were a new configuration to add the GzipResourceResolver 
with `spring.resources.chain.gzip.enabled=true` to the begining of the resource chain.

**Comment by snicoll** [comment]
ping @bclozel

**Comment by bclozel** [comment]
Makes sense.
I didn't put that into my initial PR because I wondered if developers would prefer this property or they would rather configure all this "manually" to better fit their needs.

I can prepare a new PR if it's alright with you!

**Comment by snicoll** [comment]
:+1:

**Comment by mnhock** [comment]
:+1:

**Comment by chrylis** [comment]
:+1:

**Comment by snicoll** [comment]
Closing in favour of the PR #5171
