### ISSUE TITLE
SpringApplicationContextLoader ignores properties files configured via @TestPropertySource

### ISSUE THREAD

**Issue by gustavolira** [spring-projects/spring-boot#4689]
Hi,

This issue #2198 describe the problem, but this problem appears again at Spring Boot 1.3.0

**Comment by wilkinsona** [comment]
We have [an integration test](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RELEASE/spring-boot/src/test/java/org/springframework/boot/test/SpringApplicationIntegrationTestPropertyLocationTests.java) for this that's passing so this should work. Can you please provide a small sample project that illustrates the problem?

**Comment by gustavolira** [comment]
I figured out what was happening.
I put @TestPropertySource pointing to test.properties but application.properties was loading their attributes too. So what I did was:
1 - change application.properties to application-default.properties
2 - Activate only the profile that I want with @ActiveProfiles(inheritProfiles=false, profiles="test")

Sorry for any inconvenience

**Comment by wilkinsona** [comment]
Glad to hear you figured it out and thanks for letting us know
