### ISSUE TITLE
Stackoverflow badge on spring.io/projects/spring-boot

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4693]
Seems to have gone for some reason. We should restore it.

**Comment by snicoll** [comment]
It's there for me now.

**Comment by philwebb** [comment]
<img width="704" alt="screen shot 2015-12-09 at 10 31 40 am" src="https://cloud.githubusercontent.com/assets/519772/11683017/21fba37c-9e60-11e5-8a13-3d981622048b.png">

**Comment by philwebb** [comment]
Still missing for me. It should be next to the GitHub icon.

**Comment by snicoll** [comment]
I had a chat with @bclozel and we both think that there was never such a badge there. See https://github.com/spring-projects/spring-boot/blob/gh-pages/_includes/billboard.html

**Comment by Youmoo** [comment]
The conversation scares me...

**Comment by philwebb** [comment]
@snicoll Huh, thought we had one similar to Spring Cloud http://projects.spring.io/spring-cloud/

**Comment by bclozel** [comment]
@philwebb that link/icon were previously used for the (now retired) forums.

**Comment by philwebb** [comment]
OK, that was the forum badge. Closing.
