### ISSUE TITLE
ErrorPageFilter handleException status

### ISSUE THREAD

**Issue by gseifert** [spring-projects/spring-boot#4694]
When an unhandled exception occurs and the `ErrorPageFilter` forwards to the error page, the status of the actual response is `200` instead of `500`. `response.reset()` is called and then `response.sendError()` but the `ErrorWrapperResponse` overrides `sendError()` and so the actual response status is still `200`.  The `handleErrorStatus()` method calls `response.setStatus()` with the error status but `forwardToErrorPage()` does not.  So when an ajax call is made for example and an unhandled exception occurs, my ajax success handler is being invoked instead of my ajax error handler since the response status is `200` (OK).  When running with the Spring boot plugin and the tomcat embedded container, the response status returned is `500`.  Should the `forwardToErrorPage()` method be updated to also call `response.setStatus(500)`?

**Comment by wilkinsona** [comment]
The problem's actually in `BasicErrorController` and is specific to HTML responses. `BasicErrorController.error` sets the response status using the `javax.servlet.error.status_code` attribute that's set by `ErrorPageFilter`, but `BasicErrorController.errorHtml` does not. This results in `text/html` error responses have a status of `200 OK`.

**Comment by gseifert** [comment]
Thank you, that fixes my issue.  Just wondering, is there a reason `ErrorPageFilter.forwardToErrorPage` should not set the actual response status like `ErrorPageFilter.handleErrorStatus` does?

**Comment by wilkinsona** [comment]
That was quick. Thanks for testing that change.

>  is there a reason ErrorPageFilter.forwardToErrorPage should not set the actual response status like ErrorPageFilter.handleErrorStatus does?

It [already calls `sendError`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/web/ErrorPageFilter.java#L187) prior to performing the forward.

**Comment by gseifert** [comment]
The response object passed to the `forwardToErrorPage` method is the wrapped object `ErrorWrapperResponse` which overrides `sendError` which does not set the status of the underlying response and so the actual response status I was getting was still `200 OK`.

**Comment by wilkinsona** [comment]
So it is, thanks. Is your concern purely theoretical? `ErrorPageFilter` is rather delicate so I'd prefer not to change it if your problem's been solved.

**Comment by gseifert** [comment]
Yes, my issue has been solved so its no problem, just wanted to make sure I was understanding things correctly.  Thanks!
