### ISSUE TITLE
AuthenticationAuditListener does not handle InteractiveAuthenticationSuccessEvent and AuthenticationSwitchUserEvent

### ISSUE THREAD

**Issue by toughpheeckouse** [spring-projects/spring-boot#4695]
spring boot version 1.3.0

org.springframework.boot.actuate.security.AuthenticationAuditListener handle all Fialure events
(check if (event instanceof AbstractAuthenticationFailureEvent))
but handle only AuthenticationSuccessEvent and does not handle InteractiveAuthenticationSuccessEvent and AuthenticationSwitchUserEvent, but it did in version 1.2.5

**Comment by vpavic** [comment]
See #4355 for background on this change of behavior in ```1.3.0.RELEASE```.

Also note that with ```1.3.0.RELEASE``` you can easily customize publishing of authentication/authorization events (see #4406).

**Comment by toughpheeckouse** [comment]
Oh! I see.

Thank you!

**Comment by wilkinsona** [comment]
@toughpheeckouse It looks like @vpavic has addressed the problem you were having (thanks, Vedran) so I'm going to close the issue. If that's not the case please let us know what's still causing you trouble and we can reopen the issue.

**Comment by toughpheeckouse** [comment]
https://github.com/wilkinsona, yes. Please close the issue.
