### ISSUE TITLE
Default filter registration for non-async dispatchers does not register ERROR dispatcher

### ISSUE THREAD

**Issue by josetesan** [spring-projects/spring-boot#4696]
Hello,

We are using spring-security in our spring-boot-mvc application, (1.3.0.RELEASE ) and looks like ERROR requests are not been properly handled by the default spring security filter chain.

Looks like **org.springframework.boot.context.embedded.AbstractFilterRegistrationBean** only registers filters for 
```  
static final EnumSet<DispatcherType> NON_ASYNC_DISPATCHER_TYPES = EnumSet
			.of(DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST);
```
but is not allowing DispatcherType.ERROR as non-async type.

Is there any reason to exclude it ? how can it be overriden ?

Thanks.

**Comment by wilkinsona** [comment]
1.3.1 will add a new property, `security.filter-dispatcher-types`, that can be used to configure the security filter's dispatcher types. In the meantime you can provide your own registration bean for the filter to take complete control of the filter's configuration. Please see #4505 for further details, including [an example of overriding the configuration[(https://github.com/spring-projects/spring-boot/issues/4505#issuecomment-157072267) to configure the dispatcher types.

**Comment by josetesan** [comment]
Thanks, +1 for spring-boot team !
