### ISSUE TITLE
Counters dont reset in StatsdMetricWriter

### ISSUE THREAD

**Issue by vishalmodak** [spring-projects/spring-boot#4700]
I have been testing writing dropwizard metrics to statsd using StatsdMetricWriter. I noticed that when I create a counter (with name having "counter."), its value wasn't reset after metric was written to statsd. As a result, it always a cumulative metric.
This causes a problem with my metrics reporting since I am unable to get the correct count  of requests per second. 

I looked thru the git history for StatsdMetricWriter. It seems like an earlier version of the code had the reset() method implemented. Is this intentional? Seems like a bug to me.

Regards,
Vishal

**Comment by vishalmodak** [comment]
This applies to "count" metric as a part of any "timer" metric.

**Comment by dsyer** [comment]
AFAIK there is no API in statsd to reset a counter. If that's wrong we can add a reset implementation.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by singram** [comment]
There is no reset counter functionality in statsd.
I believe the request is to reset 'counter.*' metrics to 0 within sprint boot actuator whenever they are exported to statsd.
This behavior would provide an accurate representation of counts per export interval rather than a single running cumulative count.  This behavior is desirable when measuring API endpoint activity, it may not be desirable for all counter.* metrics.

**Comment by dsyer** [comment]
Sorry, I didn't understand that. If there is an API to reset in statsd what is it, and which counters do you think it would be desirable for (how could we tell the difference)?

**Comment by vishalmodak** [comment]
So in my original implementation, I didn't realize that metric name has to have prefix "counter."
So my counter was not truly a counter but more a "gauge". As a result, I was getting a cumulative count.
After renaming my metric to use prefix, I was started getting a snapshot count.

However, I still have the issue when I am using a timer metric with correct prefix of "timer.".
For example, I have a method handleMessage() for which I have a timer metric named "timer.handleMessage". I get the following set of metrics
timer.handleMessage.count.timer.count (This is a cumulative count)
timer.handleMessage.count.timer.xxxx
timer.handleMessage.count.timer.xxxx

I also get snapshot metrics such as
timer.handleMessage.snapshot.max.timer.count (this is also a cumulative count of max latency requests)
timer.handleMessage.snapshot.min.timer.count
timer.handleMessage.snapshot.mean.timer.count

As a result, I cannot an accurate throughput metric.

I dont know if this is limitation of the statsd api or spring boot dropwizard metrics issue.

**Comment by dsyer** [comment]
I'm not sure I'm fully on the same page yet. I think what you are saying is that you actually don't care about the reset operation, you just want your Dropwizard metrics to be exported in a way that makes sense? Did you know that Dropwizard has native support for exporting metrics (might be a better choice given that there is structure beneath the timers)?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
