### ISSUE TITLE
Allow easy opt-out of using the start-stop-daemon in the launcher

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4732]
See https://github.com/spring-projects/spring-boot/pull/4618 for background. Rather than trying to parse the version number we could just offer a quick property to opt-out.

**Comment by philwebb** [comment]
We should also update the docs.

**Comment by trondgzi** [comment]
I think this was broken with commit 81a47639407ce5cdf2798c34f7122690c9739b38?

**Comment by wilkinsona** [comment]
Damn it. Thank you, @trondgzi.
