### ISSUE TITLE
Provide a way to overwrite default DispatcherTypes

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#4739]
The default DispatcherTypes currently is not configurable. 

```
    static final EnumSet<DispatcherType> ASYNC_DISPATCHER_TYPES = EnumSet.of(
            DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST,
            DispatcherType.ASYNC);

    static final EnumSet<DispatcherType> NON_ASYNC_DISPATCHER_TYPES = EnumSet
            .of(DispatcherType.FORWARD, DispatcherType.INCLUDE, DispatcherType.REQUEST);
```

I think that `INCLUDE` should not be in these default sets. A JSP project can easily has performance issues or unpredictable behaviours. For example, Spring Security AutoConfiguration has caused some trouble to me. (Also FORWARD might be not included in these sets)

Changing these default sets is unfortunately a breaking change but a configuration option can mitigate issue.

**Comment by philwebb** [comment]
See also #4505

**Comment by philwebb** [comment]
@cemo Are you able to provide some more details of the problems you're seeing with the defaults, especially the Spring Security issue?

Changing the default `DispatcherTypes` makes me a bit nervous, I'd rather take individual filter registrations on a one-by-one basis. One option that you could try if you want all your beans to have a different value is to use a `BeanPostProcessor`. You should be able to get all `FilterRegistrationBeans` and call `setDispatcherType` on them manually before they're used.

**Comment by cemo** [comment]
`INCLUDE` is usually used by JSP projects and maybe some of other view technologies. A page with `INCLUDE` directives is creating new internal requests and this is causing to trigger again filter chain. A filter chain can include Spring Security, Spring Session and many filters such as Encoding Filter, Request Context Filter. None of them requires actually a `INCLUDE` dispatcher type. I can not find really helpful  `INCLUDE` in default list. A view technology with supporting `INCLUDE` request can easily has trouble. I had fell into a few times before. First with Spring Security then Spring Session. The first one created problems can not be easily detected because it was not creating errors in a consistent way. The second one also created big performance problems because again and again I tried to fetch session from datasource.    

I have already overwrite some of filters with default values but I can not be sure for all of them. A new filter can easily put me into trouble.

**Comment by wilkinsona** [comment]
> I have already overwrite some of filters with default values but I can not be sure for all of them. A new filter can easily put me into trouble.

Hence the suggestion to use a `BeanPostProcessor` so that you can be sure you have set the dispatcher types for every filter.

**Comment by cemo** [comment]
I am pretty sure this will create other issues as well. If I would like to stay with current defaults, It will cause other issues.

**Comment by cemo** [comment]
I am also not sure about `DispatcherType.FORWARD` as well. It seems me not correct as a default. What do you think about `RequestContextFilter` with `DispatcherType.FORWARD` configuration? Is there any filter which needs `DispatcherType.FORWARD as a default configuration?

**Comment by rupert654** [comment]
I have a problem with Spring Security's filter chain being registered on DispatcherType.FORWARD.

I'm using Tiles and have discovered that the layout is retrieved by Tiles by dispatching a forward see `org.apache.tiles.request.AbstractClientRequest::dispatch` on some JSP in my WEB-INF directory e.g. /WEB-INF/view/layout/layout.jsp

Since I have Spring Security securing all URLs by default, I have no rule that matches /WEB-INF/view/layout/layout.jsp, and so I get an authentication error. Furthermore, I'm not sure if it is very efficient or necessary for the security filter chain to get triggered twice on every request, once for the original page and then again for the layout.

**Comment by cemo** [comment]
I think that this issue can be considered a duplication of https://github.com/spring-projects/spring-boot/issues/7467 anymore. 

But still believe `Request` and `Error` should be default. :-)
