### ISSUE TITLE
Add getResource(String name) method to Archive Class?

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#4740]
org.springframework.boot.loader.archive.Archive

```java
    /**
     * Get resource URL from archive.
     * @return
     * @throws MalformedURLException
     */
    public abstract URL getResource(String name);
```

**Comment by snicoll** [comment]
Can you please explain what you're trying to achieve instead?

**Comment by hengyunabc** [comment]
I want to read resource from an archive, such as xxx.properties. There is not an easy to read resource from an archive.

**Comment by wilkinsona** [comment]
I wouldn't recommend writing a Spring Boot application that interacts directly with `Archive`. You should be able to load resources from the archive using the class loader by calling `ClassLoader.getResource(String)`. Have you tried that approach?

**Comment by hengyunabc** [comment]
Spring boot loader support jar in jar, it is a very good feature. I want to use it to build a plugin system.
A plugin can be load from a file directory or a fat jar. The plugins have their own resource files. 
So I need to load resource from an archive. 

I hope that spring boot loader can support it, thanks.

**Comment by philwebb** [comment]
The `Archive` class isn't really designed to provide direct access to individual resources. It's main job is to return a `URL` which can be used with the classloader.

You might be able to get somewhere by building a URL to access the resource:

```java
URL archiveUrl = archive.getUrl();
URL resourceUrl = new URL(archiveUrl, "xxx.properties");
```

I can't remember the exact format of the `name`, but if you look at `URLClassLoader` you can probably see how that does things.

**Comment by philwebb** [comment]
I'm afraid that I don't want to change the existing design of `Archive` so adding a new method isn't really an option.
