### ISSUE TITLE
Custom error attributes in DefaultErrorAttributes

### ISSUE THREAD

**Issue by mnhock** [spring-projects/spring-boot#4741]
I want propose a new feature and ask if there a need for.

For me it would be great if I had the possibility to set a comma separated list of request and session attributes names like `server.error.include-attributes=foo, bar`. 

Then the `DefaultErrorAttributes` or the `BasicErrorController` implementation would look for this attributes here `foo` and `bar` in the request and/or session scope and include them after calling `toString()` on the object to the `errorAttributes` `LinkedHashMap`.

So it would be very easy to include custom attributes to the error report.

**Comment by kimsaabyepedersen** [comment]
Hi

I have made at pull request for this (sorry I needed two extra commits in it. I had some problems with checks rule locally).

My solution allows you to give a list of which scope variables you want emitted in case of error. And likewise for session variables.

Best regards
Kim

**Comment by bclozel** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

The companion PR #6745 implements this feature, but I think this has a few flaws:
* simply adding attributes to the map without formatting them might cause serialization/rendering issues. If a transformation is required, a custom `ErrorAttributes` bean would still be the best solution
* adding a new method to the `ErrorAttributes` interface would require all developers with an existing custom bean to implement that new method.

@kimsaabyepedersen Thanks for this PR, and sorry for not accepting this after marking that issue as ideal for contribution. Hope you'll consider contributing again. Thanks!
