### ISSUE TITLE
Add a note to ApplicationPidListener with the new class name

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4743]
See https://github.com/spring-projects/spring-boot/issues/1673#issuecomment-163593539

**Comment by jasperblues** [comment]
@philwebb Awesome, thank you sir.

**Comment by snicoll** [comment]
@jasperblues I am confused. `ApplicationPidListener` is gone on master and the `1.2.x` version has [this note](https://github.com/spring-projects/spring-boot/blob/1.2.x/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/system/ApplicationPidListener.java#L33). Maybe I misunderstood what you're asking?

**Comment by jasperblues** [comment]
@snicoll Sincere apologies. I must've googled up the wrong API doc version for `ApplicationPidListener`, which I discovered after reading some (must be older) articles about devops. I was looking for the best way to push new builds to AWS from our build server, triggered by pushing to a particular branch.

**Comment by snicoll** [comment]
That's alright, as long as we got it covered ;)
