### ISSUE TITLE
Make the build faster

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4747]
CI builds currently take ~40 minutes which is rather painful. I'd like to explore making it faster, ideally without losing anything. For example, it should be possible to build and test all of the samples in parallel. Doing so on my machine reduces the build time for them from ~5.5 minutes to ~3.5 minutes.

**Comment by snicoll** [comment]
Moving some stuff such as `spring-boot-tools` would help as well but would make the release more complex. I like the fact that the build plugin is aligned with a the Spring Boot version: only one thing to remember.
