### ISSUE TITLE
NPE fails spring-boot-maven-plugin jar-custom-launcher IT

### ISSUE THREAD

**Issue by mbenson** [spring-projects/spring-boot#4758]
https://github.com/spring-projects/spring-boot/commit/8e0b8750c05e788c76bcf1298e2856adc53b4ce6

**Comment by wilkinsona** [comment]
This appears to be Windows-specific. It's failing on Windows CI too: https://build.spring.io/browse/BOOT-WIN-482/log

**Comment by mbenson** [comment]
strange; why would the description be `null` only on Windows?

**Comment by wilkinsona** [comment]
@mbenson Strange indeed. CI on Linux is green and that test passes happily on my machine (OS X) as well.

**Comment by mbenson** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/34b31f1abccb7ca79c54590a29cc33d44dafffee

**Comment by philwebb** [comment]
Tests failed for me locally, perhaps it's a Maven version issue. Anyway now fixed. Thanks for reporting!
