### ISSUE TITLE
maven-invoker-plugin needs upgrade to work with later versions of Maven on Windows

### ISSUE THREAD

**Issue by mbenson** [spring-projects/spring-boot#4759]
Newer versions of Maven use mvn.cmd but maven-invoker-plugin 1.9 invokes mvn.bat .

**Comment by snicoll** [comment]
Closing in favour of the PR #4760

**Comment by mbenson** [comment]
Should I infer then that I should submit an issue only if I don't intend to submit a PR?

**Comment by snicoll** [comment]
a PR only is fine. There is not much of a difference between the two on github and if you have an issue and a PR, one of them ends up being a duplicate anyway.
