### ISSUE TITLE
Undertow test failures on Windows

### ISSUE THREAD

**Issue by mbenson** [spring-projects/spring-boot#4765]
Using Oracle JDK 1.8.0_65, `java.io.tmpdir` may be set as a tilde-compressed Windows pathname (remarkably, `user.home` is not compressed in this manner). Meanwhile, Undertow uses `File#getCanonicalFile()` to determine whether a resource has been requested using the proper case. The upshot is that when the server is in case-sensitive mode, it rejects requests for resources under `java.io.tmpdir`. This causes numerous failures in `org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactoryTests`. Since `org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory` includes code that defaults to creating a resource root via `java.io.File#createTempFile()` it would seem that there is a real threat that spring-boot users could be affected by this. Arguably Undertow's case-sensitivity checks should be relaxed to only checking the portion of the path that was actually requested by the user, but it's probably fairly rare that someone sets up an Undertow server with other than the canonical path set as the resource root.

**Comment by philwebb** [comment]
I made a few comments on the PR to see if we could isolate the changes to just Undertow.
