### ISSUE TITLE
Possible pitfall when using RememberMeServices

### ISSUE THREAD

**Issue by nikosk** [spring-projects/spring-boot#4773]
_the issue_

When your RememberMe service does not implement LogoutHandler the RememberMeConfigurer sets a null logout handler [(RememberMeConfigurer:287)](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java#L287) and the LogoutFilter accepts it just fine [(LogoutConfigurer:87)](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.java#L87) later causing an NPE when executing the handlers [(LogoutFilter:111)](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/logout/LogoutFilter.java#L111). This is definitely not expected behaviour.

_Steps to reproduce:_

1) Create a spring boot app
2) Create a class that implements RememberMeServices but not LogoutHandler
3) Configure HttpSecurity to use it:
```java
protected void configure(HttpSecurity http) throws Exception {
http()
				.rememberMe()
				.rememberMeServices(rememberMeServices()) 
```
4) Try to login then logout of your app. 

_Proposed solution_

LogoutConfigurer should never accept null handlers. A null check in the addLogoutHandler method should be sufficient. Also make RememberMeServices extend LogoutHandler so that users are aware of the dependency later on.

```java
public LogoutConfigurer<H> addLogoutHandler(LogoutHandler logoutHandler) {
                Assert.notNull(logoutHandler, "logoutHandler cannot be null");
		this.logoutHandlers.add(logoutHandler);
		return this;
}
```

**Comment by dsyer** [comment]
Neither `LogoutConfigurer` nor `RememberMeServices` are part of Spring Boot. Did you mean to raise an issue with Spring Security (https://jira.spring.io/browse/SEC)?

**Comment by nikosk** [comment]
@dsyer I am sorry. I was under the impression that the *Configurer classes are part of Spring-Boot (-Security Starter) project. I'll file a new one in Jira then.
