### ISSUE TITLE
ignoreUnknownFields=false causes ConfigurationProperties from SystemEnvironment not to be bound

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#4775]
I have a `@ConfigurationProperties(prefix="test.env", ignoreUnkownFields=false)` with property `foo-bar` and the environment variable `TEST_ENV_FOO_BAR` will not be bound by the relaxed binding when running the application with `env TEST_ENV_FOO_BAR="Hallo" mvn clean spring-boot:run`.

All of configuring by application.yml, changing the `ignoreUnkownFields` to `true` or changing the `prefix` to `test` works.

sample code
```java
@SpringBootApplication
@EnableConfigurationProperties({ TestProps.class })
@Configuration
public class DemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args).getBean("runner", Runnable.class).run();
	}

	@Autowired
	private TestProps test;

	@Bean
	public Runnable runner() {
		return new Runnable() {
			@Override
			public void run() {
				System.out.println(test.getFooBar());
			}
		};
	}

	@ConfigurationProperties(prefix = "test.env", ignoreUnknownFields = false)
	public static class TestProps {
		private String fooBar;

		public String getFooBar() {
			return fooBar;
		}
		public void setFooBar(String fooBar) {
			this.fooBar = fooBar;
		}
	}
}
```

**Comment by snicoll** [comment]
essentially, you're saying that `TEST_ENV_FOO_BAR` does not map to `test.env.foo-bar` right?

**Comment by joshiste** [comment]
yes.

**Comment by wilkinsona** [comment]
@joshiste Thanks for the sample code, I've reproduced the problem.

**Comment by wilkinsona** [comment]
When `ignoreUnknownFields=false`, the problem appears to be in `DefaultPropertyNamePatternsMatcher`. It's trying to match `TEST_ENV` with `test.env`. It correctly matches `TEST` with `test` but then gets to the delimiters and fails to match `_` with `.`.

**Comment by wilkinsona** [comment]
Based on its javadoc, `DefaultPropertyNamePatternsMatcher` seems to be working as designed:

> `PropertyNamePatternsMatcher` that matches when a property name exactly matches one of the given names, or starts with one of the given names followed by a delimiter.

**Comment by wilkinsona** [comment]
An alternative is to change `DefaultPropertyNamePatternsMatcher` so that it considers to different delimiters as being a match:

```diff
diff --git a/spring-boot/src/main/java/org/springframework/boot/bind/DefaultPropertyNamePatternsMatcher.java b/spring-boot/src/main/java/org/springframework/boot/bind/DefaultPropertyNamePatternsMatcher.java
index 859d57b..c968d20 100644
--- a/spring-boot/src/main/java/org/springframework/boot/bind/DefaultPropertyNamePatternsMatcher.java
+++ b/spring-boot/src/main/java/org/springframework/boot/bind/DefaultPropertyNamePatternsMatcher.java
@@ -100,8 +100,11 @@ class DefaultPropertyNamePatternsMatcher implements PropertyNamePatternsMatcher
        }

        private boolean isCharMatch(char c1, char c2) {
-               if (this.ignoreCase) {
-                       return Character.toLowerCase(c1) == Character.toLowerCase(c2);
+               if (isDelimiter(c1) && isDelimiter(c2)) {
+                       return true;
+               }
+               if (this.ignoreCase && Character.toLowerCase(c1) == Character.toLowerCase(c2)) {
+                       return true;
                }
                return c1 == c2;
        }
```

This changes the documented behaviour of the matcher but I think it'll perform better.
