### ISSUE TITLE
spring.profiles.active value could not be resolved to another config key

### ISSUE THREAD

**Issue by nmquyet** [spring-projects/spring-boot#4778]
I want to config spring active profile by using other config key but it did not work.

```
microservice.environment=${env:local}
spring.profiles.active=${microservice.environment}
```

The debug log say that my active profile is `${microservice.environment}`

**Comment by philwebb** [comment]
This is a known limitation of the processing logic. It's not possible for us to refer to a property in the same file because it's not get been processed when the property is parsed.

**Comment by philwebb** [comment]
Duplicates #4422
