### ISSUE TITLE
Improve parity between Eclipse and IntelliJ

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4785]
We have a bunch of eclipse settings that are currently hard to replicate in IntelliJ.

**Comment by philwebb** [comment]
One idea that's been considered in the past is to use https://github.com/revelc/formatter-maven-plugin/ to apply the eclipse formatter rules from Maven.

**Comment by snicoll** [comment]
Closing in favour of https://github.com/spring-io/spring-javaformat
