### ISSUE TITLE
Allow launch script defaults to be overriden at build time

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4787]
We should discuss file based logging driven from #4506

**Comment by philwebb** [comment]
Outcome is that we should allow defaults to be customized in the build plugin. i.e.:

```
[[ -z "$LOG_FOLDER" ]] && LOG_FOLDER="{{logFolder:/var/log}}"
```

Would allow

```
<embeddedLaunchScriptProperties>
  <logFolder>foo</logFolder>
</embeddedLaunchScriptProperties>
```

**Comment by vpavic** [comment]
@philwebb, please take note that these defaults are not actually applicable if one uses ```systemd```. I'm stressing this because it should be properly documented to avoid any further confusion regarding the ```init.d``` vs ```systemd``` differences - see #4334 and linked issues.
