### ISSUE TITLE
Undertow doesn't shut down properly when context is closed

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4793]
Creating the `AccessLogHandler` creates a new XNIO worker that's never stopped so its thread are left running. They're non-daemon threads so they prevent the JVM from exiting.

**Comment by philwebb** [comment]
I've made an attempt to fix this I'm too tired to know if it's the best way.

I added a `ServletContextListener` to track `contextDestroyed` then close the `AccessLogReceiver` and `XnioWorker`. Interestingly, these listeners arent currently triggered, it appears that we need to call `undeploy` after `stop` to actually get them to fire.

The change does appear to fix the problem, but it causes another issue. Calling `DefaultAccessLogReceiver.close()` causes an NPE on the next `run()` when no file is currently open. This looks like an Undertow bug to me.

https://github.com/philwebb/spring-boot/tree/gh-4793
