### ISSUE TITLE
Try to find a better way to bind ServerProperties not bound to application.properties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4797]
Commit 471947b4007e612fe2f31e4bf32435cc03f527b6 which fixes #4631 uses a temporary bean to load the properties. It would be nice if we could find an alternative way to do this.

**Comment by snicoll** [comment]
If we remove the feature as described in #8108 all that code should go away as well.

**Comment by snicoll** [comment]
The feature has been removed so this is no longer relevant (see 6af6e8e)
