### ISSUE TITLE
Log4j2 prints error when log4j2-spring.xml is used

### ISSUE THREAD

**Issue by cforce** [spring-projects/spring-boot#4809]
According to doc https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html the name shall work with "log4j2-spring.xml". but only does with "log4j2.xml"

as proposed from https://github.com/spring-cloud/spring-cloud-commons/issues/72#issuecomment-165822704

**Comment by snicoll** [comment]
It does work but produces this exception on startup 

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

I assume that's what confused you in the first place, I don't know if this is new or not at this point but that extra statement is the only problem as far as I can see.

**Comment by yairogen** [comment]
Any updates? I could only suppress this error print by adding:
-Dlog4j.configurationFile=log4j2-spring.xml

**Comment by RTM945** [comment]
```java
@RestController
@EnableAutoConfiguration
@SpringBootApplication

public class Example {

	@RequestMapping("/")
	String home() {
		return "Hello World!";
	}


	public static void main(String[] args) throws Exception {
		new SpringApplicationBuilder(Example.class).listeners(new LoadAdditionalProperties()).run(args);
	}

	@Bean
	public EmbeddedServletContainerFactory servletContainer() {
		JettyEmbeddedServletContainerFactory factory = new JettyEmbeddedServletContainerFactory("/project", 9000);
		factory.addErrorPages(new ErrorPage(HttpStatus.NOT_FOUND, "/notfound.html"));
		return factory;
	}

}

//copy from https://github.com/spring-projects/spring-boot/issues/6220
@Component
public class LoadAdditionalProperties implements ApplicationListener<ApplicationEnvironmentPreparedEvent> {

	private ResourceLoader loader = new DefaultResourceLoader();

	@Override
	public void onApplicationEvent(ApplicationEnvironmentPreparedEvent event) {
		try {
			Resource resource = loader.getResource("file:conf/project/application.yml");
			PropertySource<?> propertySource = new PropertySourcesLoader().load(resource);
			event.getEnvironment().getPropertySources().addLast(propertySource);
		} catch (IOException ex) {
			throw new IllegalStateException(ex);
		}
	}

}
```

My application.yml:
```yml
logging: 
    config: file:conf/project/log4j2.xml
```

my log4j.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration monitorInterval="60">
    <Appenders>
        <Console name="Console-Appender" target="SYSTEM_OUT">
            <PatternLayout>
                <pattern>
                    %d{ABSOLUTE} %5p %t %c{2}:%L - %m%n
                </pattern>>
            </PatternLayout>
        </Console>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="Console-Appender"/>
        </Root>
    </Loggers>
</Configuration>
```

run with this error on startup:

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

and use default logger like:

> INFO 50608 --- [           main] c.w.a.Example                            : Starting Example on....

then I set properties to springApplicationBuilder:
```java
new SpringApplicationBuilder(Example.class)
.properties("logging.config=file:conf/project/log4j2.xml")
.listeners(new LoadAdditionalProperties()).run(args);

```
log4j2 works but also the same error on startup:
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

**Comment by wilkinsona** [comment]
If you don't want to use a system property, you can suppress the error with a file named `log4j2.component.properties` with the contents:

```
log4j.configurationFile=log4j2-spring.xml
```

**Comment by wilkinsona** [comment]
@philwebb Perhaps we could include such a properties file in our log4j2 starter? The value can be a comma-separated list so it could be:

```
log4j.configurationFile=log4j2.xml,log4j2-spring.xml
```

**Comment by philwebb** [comment]
@wilkinsona That would be nice. I'll target this to 1.5 to investigate since it seems to be causing grief for people.

**Comment by yeta-io** [comment]
Hello,

After this patch my `log4j2.xml` project file configuration is ignored by spring, I see nothing in console. Only after rename log4j2.xml to log4j2-spring.xml it started work again. So, it's looks like regression introduced by this patch.

**Comment by philwebb** [comment]
@yeta-io Thanks, we discovered this ourselves today (see #7783). I've got a different fix I'm about to commit.

**Comment by philwebb** [comment]
@yeta-io If you've got time to test the latest snapshot, I'd appreciate it.

**Comment by jarvan4dev** [comment]
let me final this question! 😄 

We know that log4j2 will load the configuration file with default name, the rule is the following:

1. Log4j will inspect the "log4j.configurationFile" system property and, if set, will attempt to load the configuration using the ConfigurationFactory that matches the file extension.
2. If no system property is set the properties ConfigurationFactory will look for log4j2-test.properties in the classpath.
3. If no such file is found the YAML ConfigurationFactory will look for log4j2-test.yaml or log4j2-test.yml in the classpath.
...
 you could find the rule at https://logging.apache.org/log4j/2.x/manual/configuration.html

in the doc of SpringBoot, it recommends that you should name the log configuration file after 'log4j2-spring.xml', it will be loaded automatically, but log4j2 won't find it. So that you will see an error like `ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.` 

you could upgrade springboot to 1.5.0.RELEASE or name the log4j2 configuration file after 'log4j2.xml'
