### ISSUE TITLE
https for main app, http for actuator endpoints

### ISSUE THREAD

**Issue by billkoch** [spring-projects/spring-boot#4810]
Similar to https://github.com/spring-projects/spring-boot/issues/3509, and to a question on [StackOverflow](http://stackoverflow.com/questions/34330018/spring-actuator-http-but-embeded-servlet-https).

I would like to have my main Spring Boot app listening on 8443 over https, and run actuator on a different port (say, 8080) over http.

**Comment by JeffreyTaylor** [comment]
+1
