### ISSUE TITLE
server.* defines non embedded configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4818]
See #4816 

Our documentation states _EMBEDDED SERVER CONFIGURATION_ for the `server.*` namespace but we have keys that work with a traditional war deployment (`servlet-path`typically). 

If we draw the line more properly it would probably reduce the confusion between what is supposed to work with the embedded container only vs. war deployment. 

Current list:

* `getPathsArray`
* `servlet-path`

**Comment by snicoll** [comment]
I seriously doubt we'll have the time to do this in  the 1.4 timeframe. Switching to 2.0

**Comment by snicoll** [comment]
One way to mitigate this problem would be to remove the `Embedded` part in the documentation and add something in the doc for the properties that are also taken into account with traditional war deployment. `servlet-path` is now `server.servlet.path`. Looking at other stuff in `server.servlet`, I am not sure there is a clean way to separate things that work with both an embedded server and a traditional war deployment. Regardless, it's a bit late in the 2.0 cycle to look at this IMO.

**Comment by wilkinsona** [comment]
We've concluded that there's nothing we can really do about this. Our primary target audience are developers using embedded containers and we should optimise property names for that. We don't have any external-container-specific properties, so we'd have to change the names of the embedded-container-specific properties to indicate that's what they are. `server.embedded.port` would be one example. This is the exact opposite of optimising for our primary target audience as it's inflicting longer, more cumbersome property names on them solely for the benefit of the secondary audience who are deploying to an external container.
