### ISSUE TITLE
Service script no longer working with Spring Boot 1.3.1

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#4820]
See my SO question: http://stackoverflow.com/questions/34392205/syntax-error-near-unexpected-token-when-running-spring-boot-jar-as-service

When tested with Spring Boot 1.3.0, it does work.

**Comment by snicoll** [comment]
Looks like a regression introduced by #4506

**Comment by joshiste** [comment]
@wimdeblauwe which bash version are you using?

**Comment by wimdeblauwe** [comment]
This is the bash version:

    [root@appdev02 ~]# bash --version 
    GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
    Copyright (C) 2005 Free Software Foundation, Inc.

**Comment by joshiste** [comment]
I think the syntax used is version 4+. We should use `>> "$log_file" 2>&1` to support older bash versions

**Comment by philwebb** [comment]
Thanks for the PR @joshiste! @wimdeblauwe You can probably define your own custom launcher script with 1.3.1 until we get this fixed.

**Comment by wimdeblauwe** [comment]
@philwebb How do I do this?

**Comment by philwebb** [comment]
@wimdeblauwe You can use the `embeddedLaunchScript` option to specify your own file. Maven details are [here](http://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html#embeddedLaunchScript) or if you're on Gradle it's [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-repackage-configuration).

You can take [the patched version](https://github.com/joshiste/spring-boot/blob/a9f07a32aa7b6c69a989c32363035b8f1fb6a77d/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script) that @joshiste provided as your source.

**Comment by wimdeblauwe** [comment]
Thx. I just tested and I can confirm that the patched version works on my server.
