### ISSUE TITLE
Adding additional properties from git.properties in the /info endpoint

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#4832]
Would it be possible to make it easy to add additional properties from the `git.properties` file to the /info endpoint?

One possibility is to make a user add something like the following to `application.properties`:

    info.git.commit.message.full=enabled

If he wants the 'git.commit.message.full' property in the /info endpoint.

This is related to #3492 and #4568

**Comment by snicoll** [comment]
And it duplicates #2644 :)
