### ISSUE TITLE
Spring Boot Actuator Health endpoint: hardcoded ROLE_ADMIN

### ISSUE THREAD

**Issue by mrs2207** [spring-projects/spring-boot#4833]
I try to use spring boot actuator with my own custom spring security configuration. Most endpoints works but the health endpoints returns only the status without details (even with an authenticated user and endpoints.health.sensitive set to false).
After looking at the source code i know the reason: the user must have the role ROLE_ADMIN.
Is it possible to change the implementation to be more flexible? 

Regards,
Michael

**Comment by philwebb** [comment]
Setting `endpoints.health.sensitive` to `false` should be enough to return all details. What version of Spring Boot are you using? 

You could try adding a breakpoint to `HealthMvcEndpoint.exposeHealthDetails(...)` to see if it returns `true`. If you have no luck with that, could you please provide a sample application that demonstrates the problem?

**Comment by snicoll** [comment]
`management.security.role` allows you to change the name of the role if that's what you're asking.

**Comment by mrs2207** [comment]
Hi Stéphane,
you're right! That is exactly what I had been searching for.
Regards,
Michael
