### ISSUE TITLE
Question :  Docs compatible to Spring boot 1.2.7 ?

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-projects/spring-boot#4834]
Is below docs compatible to above spring version ?

http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html

I tried to use below proeprty from eureka and it is not working 

eureka:
  client:
    healthcheck:
      enabled: true

**Comment by spencergibb** [comment]
@pradeepkusingh wrong repo to ask this question. The docs you're looking for are [here](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html). @aclement, @snicoll, @philwebb or @dsyer this can be closed.
