### ISSUE TITLE
Clarify that "spring.config.*" properties doesn't work in configuration files

### ISSUE THREAD

**Issue by jcagarcia** [spring-projects/spring-boot#4838]
Hi,

I've created a [question](http://stackoverflow.com/questions/34438921/custom-config-location-and-config-name-on-spring-boot/34439157) on StackOverflow before to create this issue related with `spring.config.location` and `spring.config.name` properties.

After some asks, I think that is better to create this issue for team discussion...

I'm trying to customize Spring Boot config location and config name using `spring.config.name` and `spring.config.location` properties as I've saw on [Spring Boot reference guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties)

I've created an [Spring Boot basic application][1] to test it.

I'm able to customize it using OS environment variable like `export SPRING_CONFIG_NAME=custom` and/or `export SPRING_CONFIG_LOCATION=classpath:/custom/location.properties`. That works fine!

But If I try to define `spring.config.name=custom` on default `application.properties` and then create a `custom.properties` file where create all application configuration properties, it's not working.

I supose that `spring.config.name` and `spring.config.location` could be defined as environment variables only... but on [Spring Boot - Common application properties](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties) section, these properties appear like possible properties to include on `application.properties`/`application.yml` files...so:

* Maybe an Spring Boot reference guide update to prevent these errors?
* Maybe an update of Spring Boot code to detect if `spring.config.name` or `spring.config.location` are defined on [default locations](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files). If are defined, then use these property values to locate the other defined properties?

Regards,

  [1]: https://github.com/DISID/disid-proofs/tree/master/spring-boot-application-different-config-location

**Comment by snicoll** [comment]
The tread on stackoverflow sums it all already and the documentation is already explicit about it. 

You've found another place where we define the property without reminding you _again_ that it only works as an environment property. I guess we can do something there to reduce the confusion.

**Comment by jcagarcia** [comment]
Hi @snicoll and thanks for your answer,

Sure! I was reading Spring Boot reference guide and my first way was to create a environment variable (as you could see on my sample application provided above), but when I've saw them on common properties section too, I think that maybe exists the possibility of use them on my `application.properties` file...

Anyway, I think that is interesting to define `SPRING_CONFIG_NAME` env var on production servers to externalize properties... but in development mode? Is not interesting to be able to define new name or location to my application properties without define environment variables?

Regards and thanks so much for your support!
