### ISSUE TITLE
Running `spring init ...` generates a project with Lombok dependency not being compiled

### ISSUE THREAD

**Issue by ir73** [spring-projects/spring-boot#4842]
When I run a `spring init ...` command and specify `lombok` as one of my dependencies, I get the following gradle file:

    dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.boot:spring-boot-starter-web')
    runtime('com.h2database:h2')
    runtime('mysql:mysql-connector-java')
    providedRuntime('org.projectlombok:lombok:1.16.6')
    testCompile('org.springframework.boot:spring-boot-starter-test') 
    }

When I run `gradle bootRun` I see Java compiler errors that it cannot resolve lombok annotations. 

The workaround is to change `providedRuntime('org.projectlombok:lombok:1.16.6')` to `compile('org.projectlombok:lombok:1.16.6')` - in this case everything works fine, however, the lombok gets compiled into the code as well, which is not very good either.

**Comment by snicoll** [comment]
This has nothing to do with `spring init` actually. The CLI command uses start.spring.io behind the scenes to generate the project. I've created https://github.com/spring-io/initializr/issues/171 to track this issue.
