### ISSUE TITLE
spring boot 1.3.1.RELEASE - unable to load main class when started as unix init.d service

### ISSUE THREAD

**Issue by tpenakov** [spring-projects/spring-boot#4843]
I have a spring-boot application which is started on ubuntu 14.04 as an init.d service. When I upgraded the application to version 1.3.1.RELEASE it stopped to work - the error in /var/log/application_name.log file is:
Error: Could not find or load main class

When I switched back to 1.3.0.RELEASE the application was able to be started as init.d service. I am attaching my pom.xml file. 

Let me know if you need an additional info.

[Uploading pom.xml.zip…]()

**Comment by snicoll** [comment]
Your link does not work (and rather than a pom I'd prefer a simple project). Also attach the full stacktrace instead of just the header please.

**Comment by tpenakov** [comment]
[demo.zip](https://github.com/spring-projects/spring-boot/files/72954/demo.zip)

Demo project is attached. On ubuntu 14.04 with java 8 it should produce executable jar file after 'mvn package' command. Once after the jar file is created do the following:

sudo bash
sudo useradd tomcat
cp /path_to_jar_file/demo-0.0.1-SNAPSHOT.jar /opt/demo.jar
sudo chown tomcat:tomcat /opt/demo.jar
echo JAVA_OPTS=\"     -Xms4096M -Xmx4096M     -Dspring.profiles.active=prod     -Dlogging.level.com.wacom=DEBUG \" >/opt/demo.conf
rm /etc/init.d/demo
ln -s /opt/demo.jar /etc/init.d/demo
sudo /etc/init.d/demo restart

Once after the project is started the error in /var/log/demo.log file is :
Error: Could not find or load main class  -Xms4096M -Xmx4096M -Dspring.profiles.active=prod -Dlogging.level.com.wacom=DEBUG

There is no stack trace in log file.

Now go to the project pom.xml file and change the parent tag like this:
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.0.RELEASE</version>
		<relativePath/> 
	</parent>
rebuild the jar file and install it as unix service in the same way:

mvn clean package
sudo bash
sudo useradd tomcat
cp /path_to_jar_file/demo-0.0.1-SNAPSHOT.jar /opt/demo.jar
sudo chown tomcat:tomcat /opt/demo.jar
echo JAVA_OPTS=\"     -Xms4096M -Xmx4096M     -Dspring.profiles.active=prod     -Dlogging.level.com.wacom=DEBUG \" >/opt/demo.conf
rm /etc/init.d/demo
ln -s /opt/demo.jar /etc/init.d/demo
sudo /etc/init.d/demo restart

Now the service is stared normally and there is not an error in the /var/log/demo.log file

**Comment by wilkinsona** [comment]
Duplicates #4866
