### ISSUE TITLE
Extend Actuator's info endpoint with MANIFEST.MF properties

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#4845]
When setting the property ```addDefaultImplementationEntries``` to ```true``` for the [Maven Archiver Plugin](https://maven.apache.org/shared/maven-archiver/examples/manifest.html), the MANIFEST.MF file gets most of the information, that is mentioned in the Spring Boot Reference documentation [here]
(https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-automatic-expansion-maven).
An interesting feature would be to read the MANIFEST.MF file and show the most relevant information similar to the ```git.properties``` feature of the infor endpoint, as described [here](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-git-commit-information)

With this feature it would be possible to provide the same information consistently at the info endpoint by adding some build configuration to a parent POM. This would be impossible to achieve consistently with a large set of microservices, developed by different teams. Each team would have to copy&paste the same properties section to either ```application.properties``` or ```application.yml```.

**Comment by snicoll** [comment]
This one may be part of a theme around the info endpoint for 1.4 (see #3492). Thanks for sharing the idea!

**Comment by mrumpf** [comment]
Moved info to #2559

**Comment by snicoll** [comment]
I don't see why we should. #2559 is pretty explicit (information retrieved at build time) and is not really related to your proposal of loading content from `MANIFEST.MF`. Unless I misunderstood the link between your proposal and #2559?

**Comment by snicoll** [comment]
@mrumpf I'd be more interested by what you consider sensible defaults. What should we read from `MANIFEST.MF` and how should it translate to properties? Should we simply expose the whole content as is?

**Comment by mrumpf** [comment]
OK, I thought #2559 is the "plugin mechanism" and this will be just one implementation of a "info endpoint plugin". When I set the ```addDefaultImplementationEntries``` to true I get the following ```MANIFEST.MF``` inside the final JAR file:
```
Manifest-Version: 1.0
Implementation-Title: config-server
Implementation-Version: 
Archiver-Version: Plexus Archiver
Built-By: mrumpf
Implementation-Vendor-Id: com.daimler.daivb
Specification-Title: config-server
Implementation-Vendor: Company
Implementation-Revision: 
Implementation-Build: 
Created-By: Apache Maven 3.3.3
Build-Jdk: 1.8.0_66
Specification-Version: 1.0.1-SNAPSHOT
Timestamp: 2015-12-23T15:17:37Z
```

I would suggest to simply add everything! You can configure the Maven Archiver Plugin to add more custom properties. I you have a whitelist of properties being shown by the info endpoint, those custom properties would be left out, unless you make the whitelist configurable.
We want to use this feature to gather information on the deployed microservices in the different environments via Eureka. Therefore we need to be sure that each microservice exposes certain information under the same key, e.g. ```manifest { "Implementation-Version", "1.0.0", ... }```

**Comment by snicoll** [comment]
Actually #3492 is the plugin mechanism but I think it's interesting to keep all three issues open to collect respective feedback on what the implementation should do by default. Thanks for sharing your thoughts, very helpful!

**Comment by snicoll** [comment]
We were discussing this one during our team meeting and we're not keen on exposing stuff from the Manifest. But as I already mentioned, #3492 is going to provide a mechanism that makes it easy for you to do.

**Comment by mrumpf** [comment]
All the info endpoint plugins should still be opt-in. There should be some sort of property to enable each plugin (similar to the way you can enable or disable Actuator endpoints). With such a feature I do not see an issue to provide a MANIFEST.MF info endpoint plugin as part of Spring Boot as people need to enable it explicitly. Or are there other concerns on making the content of MANIFEST.MF available through the info endpoint?

**Comment by snicoll** [comment]
The latter.
