### ISSUE TITLE
Document how to combine AspectJ compile time weaving with our annotation processor

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4847]
Looks like folks are getting confused as how they should combine AspectJ with our annotation processor, see [this thread](http://stackoverflow.com/questions/34470682/configurationproperties-aspectj-maven-plugin-conflict) and #4825

**Comment by dilbertside** [comment]
I'm curious what I'm confused at.

I'm in the midst of upgrading a project in the Boot 1.2x line to the latest 1.3.1
I did a successful upgrade with a very classical webapp JPA, Thymeleaf, without aspectj
This one is a neo4j and a maven multi modules. And it is running fine in production in 1.2.x version.

I copied over from the JPA project the following
```
@ConfigurationProperties(prefix = "app", ignoreUnknownFields = false)
public class AppProperties {}
```
In the 1.2.x line I had:
```
@Configuration
@Profile("JMS")
@EnableJms
@EnableConfigurationProperties({ ActiveMQProperties.class})
@ComponentScan(basePackageClasses = JmsService.class)
public class ConfigJMS implements JmsListenerConfigurer{}
```
So naturally I added 
```
@EnableConfigurationProperties({ AppProperties.class, ActiveMQProperties.class})
```

mvn compilation failed, when I wanted to run the app from command line
I joined the 2 logs.
From my investigation and the fortunate discovery of this thread, removing the line
```
@ConfigurationProperties(prefix = "app", ignoreUnknownFields = false)
```
put back the compilation on a good footing.
I did try the missing elements suggested in #4825 to no avail.

my config AJC config is:
```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>aspectj-maven-plugin</artifactId>
        <version>1.8</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.0.0</version>
          </dependency>
          <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
          </dependency>
          <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>${aspectj.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <showWeaveInfo/>
          <forceAjcCompile>true</forceAjcCompile>
          <Xlint>ignore</Xlint>
          <outxml>true</outxml>
          <weaveDirectories>
            <weaveDirectory>${project.build.directory}/classes</weaveDirectory>
          </weaveDirectories>
          <aspectLibraries>
            <aspectLibrary>
              <groupId>org.springframework</groupId>
              <artifactId>spring-aspects</artifactId>
            </aspectLibrary>
            <aspectLibrary>
              <groupId>org.springframework.data</groupId>
              <artifactId>spring-data-neo4j</artifactId>
            </aspectLibrary>
          </aspectLibraries>
          <complianceLevel>${java.version}</complianceLevel>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
```
java.version is 1.7
aspectj.version is 1.8.7

For moment I have a workaround, I will use the 
```
environment.getProperty()
```
However, I'm curious what will be the documentation addition I miss for this config.

[compile-fail.txt](https://github.com/spring-projects/spring-boot/files/76273/compile-fail.txt)
[compile-ok.txt](https://github.com/spring-projects/spring-boot/files/76274/compile-ok.txt)

**Comment by snicoll** [comment]
It's a different exception. Can you share a sample that shows this problem?

**Comment by dilbertside** [comment]
As requested I put up a small project to reproduce the problem.
Code is in my [sandbox](https://github.com/dilbertside/sandbox/tree/master/AJC-4847)
I got same behaviour fortunately, but depending on the source code (with entities or not) the exception will show different classes failing with no apparent relation to the problem.

**Comment by anaram** [comment]
I believe issue is caused by the processor being triggered more than once during the compilation and failing due to the target file classes/META-INF/spring-configuration-metadata.json being present. It's basically triggered by both maven-compiler-plugin and aspectj-maven-plugin.

Removing spring-boot-configuration-processor from project dependencies and adding it as maven-compiler-plugin dependency should allow it to complete successfully on clean builds as it will only trigger once. Alternatively one could probably disable maven-compiler-plugin from the project or set <proc>none</proc> for maven-compiler-plugin. I'm unsure what's the cleanest option, and if the solutions have some side effects, though. Best would be if the processor was updated to avoid this kind of behaviour.

**Comment by dilbertside** [comment]
Correct, I just tried and by commenting
spring-boot-configuration-processor, compilation error disappeared.

However removing this compiler remove the benefit of properties file
edition as stated in
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor
And now I have a warning as such "'app.async.corePoolSize' is an unknown
property."

Removing the maven-compiler-plugin is a dead end in my case, if you miss
that plugin in your pom you may have a warning while running maven and
the eclipse import project may set the wrong compiler version, which is
a configuration waste of time when a new developer join the team.

I dig in the spring-boot-configuration-processor as a maven-compiler-plugin.

**Comment by snicoll** [comment]
okay looks like it's not only a documentation issue now. I'll look into it.

**Comment by dilbertside** [comment]
Could that issue be in any case a way out, after all this spring-boot-configuration-processor is useful only during development time, correct?!
Improve development time experience #3082

**Comment by snicoll** [comment]
I don't see the link with #3082. You always need the `spring-boot-configuration-processor`: that's the thing that generates the `META-INF/spring-configuration-metadata.json` file for your `@ConfigurationProperties` bean. It's useful "everywhere". In any case, we'll find a way to make sure it works with AspectJ as well.

**Comment by snicoll** [comment]
@dilbertside I had a look to your project and you didn't apply the proposal of #4825 a `<sources/>` element was missing. If don't know if you need to scan the source files or not in that particular project.

In any case, you can also fix the issue with your current project and the following configuration:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.3</version>
  <configuration>
    <source>${java.version}</source>
    <target>${java.version}</target>
    <proc>none</proc>
  </configuration>
</plugin>
```

I had a look to the API that the annotation processor provides and it does not provide an obvious way to retrieve an existing file for the purpose of writing in it.  I have updated the documentation with a few suggestions.

**Comment by dilbertside** [comment]
Yes you are right.

Either solution works.
I indeed missed the  `<sources/>` in aspectj-maven-plugin proposed in #4825

or adding `<proc>none</proc>` in maven-compiler-plugin

or adding both of them together.

Thank you for your investigation and solution.

**Comment by aurambaj** [comment]
I've been running into the same issue. `<sources/>` is not an option as the code contains aspects.  `<proc>none</proc>` fixes the build but then `spring-boot:run` won't work.

For now I ended up creating a profile enabled by default that contains the `spring-boot-configuration-processor` and the `<proc>none</proc>`. I disable it when running `spring-boot:run`.

This looks like a nasty workaround. Any better idea or plan to address this?

Thanks!

**Comment by mohanr** [comment]
> [INFO] --- aspectj-maven-plugin:1.8:compile (default) @ enterprise ---
> [WARNING] No sources found skipping aspectJ compile
If I specify <sources/> this is what I get. And if I specify "/src/main/java" as <source> then I get the original error.

**Comment by t-beckmann** [comment]
The field value processing warning is caused by the configuration processor using implementation details of javac. It checks and emits the warning. Since the internal bits are not available field initializers can not be processed and thus configuration details will be missing.

The failure of writing metadata is the consequence of https://bugs.eclipse.org/bugs/show_bug.cgi?id=530665.

**Comment by smil2k** [comment]
Just to help the future generations. The following changed made it possible to use spring-metadata-configuration annotation processor and lombok with aspectj compile time waiving supported transaction management together:

Changes needed:
1. spring-context.xml : 
<tx:annotation-driven **mode="aspectj"**/>
(This can be achieved by using the @EnableTransactionManagement(mode = AdviceMode.ASPECTJ)


2. Add maven dependency
  <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjrt</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-aspects</artifactId>
    </dependency>    

3, Compile-time waiver in the plugin section:
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>aspectj-maven-plugin</artifactId>
        <version>1.11</version>
        <configuration>
            
            <sources/>
            
            
            <forceAjcCompile>true</forceAjcCompile>
            
            <weaveDirectories>
              <weaveDirectory>${project.build.directory}/classes</weaveDirectory>
            </weaveDirectories>
            <aspectLibraries>
                <aspectLibrary>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-aspects</artifactId>
                </aspectLibrary>
            </aspectLibraries>
            
            <showWeaveInfo>true</showWeaveInfo>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>compile</goal>
                </goals>
            </execution>
        </executions>
      </plugin> 


ps. the OP had effectively <sources/> inside the call, because <source> is not for setting the source compliancy level!
