### ISSUE TITLE
Reflect DispatcherServlet configuration in TestDispatcherServlet automatically in a Spring Boot/MVC Test

### ISSUE THREAD

**Issue by ksokol** [spring-projects/spring-boot#4850]
In a Spring Boot application we can register a preconfigured DispatcherServlet. For example:

    @SpringBootApplication
    public class Application {

        @Bean
        public Servlet dispatcherServlet() {
            final DispatcherServlet dispatcherServlet = new DispatcherServlet();
            dispatcherServlet.setDispatchOptionsRequest(true);
            return dispatcherServlet;
        }
    }

In Spring Boot/MVC Test we must call dispatchOptions(true) in order to mimic the same behaviour as in DispatcherServlet:

    @RunWith(SpringJUnit4ClassRunner.class)
    @SpringApplicationConfiguration(classes = Application.class)
    @WebIntegrationTest
    public abstract class IntegrationTest {

        private MockMvc mockMvc;

        @Autowired
        private WebApplicationContext wac;

        @Before
        public void before() throws Exception {
            mockMvc = webAppContextSetup(wac)
                    .dispatchOptions(true)
                    .build();
        }
    }

This might lead to irrelevant or confusing test results because DispatcherServlet and TestDispatcherServlet configuration may be out of sync.

The question is whether it is feasible in a Spring Boot/MVC Test to reflect DispatcherServlet configuration in TestDispatcherServlet automatically.

**Comment by wilkinsona** [comment]
This is the sort of thing that #2708 is intended to cover. @ksokol I'm going to close this as a duplicate. Please feel free to comment on #2708.
