### ISSUE TITLE
Auto registration of HandlerMethodArgumentResolvers and HandlerInterceptorAdapters

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-boot#4852]
In my project I currently something like this:

```java
@Configuration
public class WebConfiguration extends WebMvcConfigurerAdapter {

    @Autowired
    private List<HandlerMethodArgumentResolver> handlerMethodArgumentResolvers;

    @Autowired
    private List<HandlerInterceptorAdapter> handlerInterceptorAdapters;

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        handlerInterceptorAdapters.forEach(registry::addInterceptor);
    }

    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
        argumentResolvers.addAll(handlerMethodArgumentResolvers);
    }
}
```

It would be great if this functionality was provided by spring boot.

**Comment by snicoll** [comment]
We just discussed this and while it's a sensible change we need to draw a line somewhere. This use case may not represent something that a lot of users are doing and your own code above is 6 lines of code (once you move the autowired fields to method parameters). Spring MVC has many feature and we can't auto-configure them all.

**Comment by lpandzic** [comment]
Ok, I'll close the PR then.

**Comment by laxika** [comment]
So I should code this myself for every project? It is an useful feature. At least try to provide something like FilterRegistrationBean.

**Comment by lpandzic** [comment]
Also,

> once you move the autowired fields to method parameters

this is not possible as those methods are overrides from parent class, `WebMvcConfigurerAdapter`.
