### ISSUE TITLE
Cannot override dependency version

### ISSUE THREAD

**Issue by skuppa** [spring-projects/spring-boot#4855]
I have multi project setup using gradle.   First module is a cassandra module and it does not have any spring boot dependency; it uses `cassandra-driver-core:3.0.0-beta1`.  The dependency graph shows that it is using the `3.0.0-beta1` and it works correctly within this module.

The second module is a core module and it includes the cassandra module and it is a `spring-boot-starter-web` project.  It also uses the gradle plugin `spring-boot-gradle-plugin`.  The gradle plugin manages the dependency and it includes the `cassandra-driver-core:2.1.9` hence my cassandra module does not work inside the core module.  Now my question is, how do I override the cassandra version which is managed by `spring-boot-gradle-plugin`.

BTW.. I am not using the `sping-boot-data-cassandra`

Here is some gradle log
```
14:27:29.728 [INFO] [io.spring.gradle.dependencymanagement.DependencyManagement] Resolved versions: {org.springframework:spring-core=4.2.4.RELEASE, .....  com.datastax.cassandra:cassandra-driver-core=2.1.9, ...}
....
....
14:27:29.841 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency onepush:repository:unspecified(default) -> com.datastax.cassandra:cassandra-driver-core:3.0.0-beta1(compile)
14:27:29.841 [DEBUG] [io.spring.gradle.dependencymanagement.VersionConfiguringAction] Processing dependency 'com.datastax.cassandra:cassandra-driver-core:3.0.0-beta1'
14:27:29.841 [DEBUG] [io.spring.gradle.dependencymanagement.DependencyManagementContainer] Found managed version '2.1.9' for dependency 'com.datastax.cassandra:cassandra-driver-core' in global dependency management
14:27:29.841 [INFO] [io.spring.gradle.dependencymanagement.VersionConfiguringAction] Using version '2.1.9' for dependency 'com.datastax.cassandra:cassandra-driver-core:3.0.0-beta1'
14:27:29.841 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.datastax.cassandra:cassandra-driver-core:2.1.9
....
```

Thanks,
-Sridharan

**Comment by skuppa** [comment]
adding the dependency explicitly in the core module should override the global dependency managed by plugin.

`cassandra/build.gradle`
```
...

dependencies {
  compile "com.datastax.cassandra:cassandra-driver-core:3.0.0-beta1"
}

...
```

`core/build.gradle`
```
....

dependencies {
  compile project(':cassandra')

  compile "com.datastax.cassandra:cassandra-driver-core:3.0.0-beta1"
}

...
```

This solves the problem but still I believe that the plugin should provide configuration to override such managed version otherwise it will be a big issue to troubleshoot and figure out the issue.

Thanks,
-Sridharan

**Comment by wilkinsona** [comment]
The plugin already supports this. Please see the [relevant section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions)

**Comment by skuppa** [comment]
Thank you very much for pointing out the right place.
