### ISSUE TITLE
Default maven filtering only apply to default configuration

### ISSUE THREAD

**Issue by caipanjin** [spring-projects/spring-boot#4856]
Both in my application.properties and  application-test.properties, I add the config spring.application.name=@pom.artifactId@ 
it works, and the value equals which in pom.xml
However if I add --spring.config.name=application-test in my bootstrap shell, i doesn't work, the value isn't filtered.

**Comment by snicoll** [comment]
What is the relationship between the two? I am sorry but I didn't get that. Filtering happens at build time so `--spring.config.name=application-test` is irrelevant to that.

**Comment by caipanjin** [comment]
I suppose both application.properties and application-test.properties should be filtered, while it's not. Is there any solution for it?

**Comment by caipanjin** [comment]
after packaging，the result is as following:
application.properties:
info.version=1.0.0
spring.application.name=auth

application-test.properties:
info.version=@project.version@ (not filtered)
spring.application.name=@pom.artifactId@ (not filtered)

**Comment by caipanjin** [comment]
@spring-issuemaster maybe you are right! But that means if we use different config file, the maven filtering is not working. What your opinion for that?

**Comment by snicoll** [comment]
This is a build tool configuration convenience, really. You should look at what you're using and tune it according to your needs. 

This is what the `spring-boot-starter-parent` provides:

```xml
<!-- Turn on filtering by default for application properties -->
<resources>
	<resource>
		<directory>${basedir}/src/main/resources</directory>
		<filtering>true</filtering>
		<includes>
			<include>**/application.yml</include>
			<include>**/application.properties</include>
		</includes>
	</resource>
	<resource>
		<directory>${basedir}/src/main/resources</directory>
		<excludes>
			<exclude>**/application.yml</exclude>
			<exclude>**/application.properties</exclude>
		</excludes>
	</resource>
</resources>
```

It only filters the main configuration and not the profiles. Maybe it should but in your case it does not matter as `spring.config.name` is usually used to refer to completely different names (`dev`, `staging`, `production` etc).

You can update the configuration according to your needs.

Having said that, I wonder if we shouldn't _also_ filter profile-specific files. Thoughts @wilkinsona, @philwebb ?

**Comment by snicoll** [comment]
> if we use different config file, the maven filtering is not working. What your opinion for that?

It's a sensible default. If your project has different semantics you're not using the default. If you want filtering, just tune the build config. We couldn't possibly anticipate all the names that any user may choose. And we're not going to scan all yml or properties file to filter them by default!

**Comment by caipanjin** [comment]
@snicoll Thanks a lot for replying! This is just a tool for convenience, and We can find some other way to solve it.

**Comment by wilkinsona** [comment]
@snicoll Filtering `application-*.properties` and `application-*.y(a)ml` by default makes sense to me

**Comment by snicoll** [comment]
Me too. So maybe we can just go ahead and make that change. But probably not until 1.4?

**Comment by wilkinsona** [comment]
Agreed on not doing it till 1.4
