### ISSUE TITLE
Please support PropertiesBeanDefinitionReader style configuration

### ISSUE THREAD

**Issue by jwaterloo** [spring-projects/spring-boot#4861]
Please support PropertiesBeanDefinitionReader style configuration in property files, command line and yaml files.
The spring boot documentation on externalized configuration doesn't mention use of ".(class)", ".(abstract)", ".(parent)", ".(lazy-init)", ".(ref)" and ".(scope)" while configuring. See below for examples taken from org.springframework.beans.factory.support.PropertiesBeanDefinitionReader documentation. The most important are ",(class)" and then ".(ref)". The use case is the strongly typed code based property declaration is an interface instead of a concrete class such as DataSource. The type of datasource injected is completely decided at runtime so I need to specify the class so you know what default constuctor to call. ".(ref)" would be useful as I could reference the same bean, preferably POJO, in multiple places. If this is already supported somehow, please revise documentation and examples to prove that non XML configuration has less of a feature gap than the XML configuration.

```
 employee.(class)=MyClass       // bean is of class MyClass
 employee.(abstract)=true       // this bean can't be instantiated directly
 employee.group=Insurance       // real property
 employee.usesDialUp=false      // real property (potentially overridden)

 salesrep.(parent)=employee     // derives from "employee" bean definition
 salesrep.(lazy-init)=true      // lazily initialize this singleton bean
 salesrep.manager(ref)=tony     // reference to another bean
 salesrep.department=Sales      // real property

 techie.(parent)=employee       // derives from "employee" bean definition
 techie.(scope)=prototype       // bean is a prototype (not a shared instance)
 techie.manager(ref)=jeff       // reference to another bean
 techie.department=Engineering  // real property
 techie.usesDialUp=true         // real property (overriding parent value)

 ceo.$0(ref)=secretary          // inject 'secretary' bean as 0th constructor arg
 ceo.$1=1000000                 // inject value '1000000' at 1st constructor arg
```

**Comment by wilkinsona** [comment]
Spring Boot's external configuration is intended for configuring properties that are then bound into classes annotated with `@ConfigurationProperties`. It's not designed to be used to define beans.

The preferred mechanism for defining beans in Spring Boot is to use Java-based configuration. XML-based configuration is also supported. My understanding is that both of those mechanisms can do everything that properties-based bean definitions can do and a whole lot more. If that's not the case, then you should raise a Spring Framework issue as it's the core Framework that provides this functionality.
