### ISSUE TITLE
Using Spring Boot application.properties to configure parameterName for content negotiation

### ISSUE THREAD

**Issue by cabbonizio** [spring-projects/spring-boot#4864]
Hi,

In our Application.java files for each of our Spring Boot applications, we create a Bean for the WebMvcConfigurerAdapter to override the configureContentNegotiation() method.  We do this mainly to override the parameterName property to "media-type" since this is a corporate standard where I work.   The default I believe is "format".  I see there's a way to specify media types via application.properties (spring.mvc.media-types.*) but curious if we can have a way to override the parameterName in similar fashion?   (spring.mvc.content-negotiation.parameter-name).......something like that?

```java
@Bean
	public WebMvcConfigurerAdapter webMvcConfigurerAdapter() {
		WebMvcConfigurerAdapter webMvcConfigurerAdapter = new WebMvcConfigurerAdapter() {
			@Override
			public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
				configurer.favorPathExtension(true).favorParameter(true).parameterName("media-type").ignoreAcceptHeader(false).useJaf(false)
						.defaultContentType(MediaType.APPLICATION_JSON).mediaType("xml", MediaType.APPLICATION_XML)
						.mediaType("json", MediaType.APPLICATION_JSON);
			}
		};
		return webMvcConfigurerAdapter;
	}
```

Thanks for having a look and a happy new year to all of you!

**Comment by wilkinsona** [comment]
This feels like programming by properties to me (as did `spring.mvc.media-types` when it was added). We'll need to draw the line somewhere.

**Comment by cabbonizio** [comment]
Fair enough @wilkinsona and I do see what you mean about programming by properties.  We are just trying to remove all of the canned configuration code from our Application.properties files and this is one of the last things remaining.  There are other ways without needing what I requested to get this done just thought it would be helpful to provide a way to configure the complete content negotiation via Spring Boot application properties.  Either way thanks for your response.

**Comment by wilkinsona** [comment]
Thanks again for the suggestion. We've decided not to implement this. Using a `WebMvcConfigurerAdapter` is the recommended approach.
