### ISSUE TITLE
RUN_ARGS in executable config not working anymore

### ISSUE THREAD

**Issue by cbornet** [spring-projects/spring-boot#4866]
With SB 1.3.1.RELEASE, the RUN_ARGS of executable war is not taken into account.
Here is the command which is launched
```shell
+ start-stop-daemon --start --quiet --chuid myapp --name myapp --make-pidfile --pidfile /var/run/myapp/myapp.pid --background --no-close --startas /usr/bin/java --chdir /usr/share/myapp/lib -- -Dsun.misc.URLClassPath.disableJarChecking=true -jar /usr/share/myapp/lib/myapp-0.0.1-SNAPSHOT.war '--spring.profiles.active=prod --logging.file=/var/log/myapp/myapp.log'
```
I think it fails because of the quotes that are surrounding the RUN_ARGS.
It is a regression since it was working with 1.3.0.RELEASE (the quotes are not there with 1.3.0.RELEASE)
Probably comes from 81a4763.

**Comment by westse** [comment]
For what its worth, I was unaware of this issue and had created a sample project to demonstrate the problem: https://github.com/westse/launcher-java-opts-bug

Glad to see it fixed!

**Comment by wilkinsona** [comment]
Reopening as my change introduced a Spellcheck warning for the lack of quoting on `$arguments`. We need to use an array instead.
