### ISSUE TITLE
javaagent could not work normally when application is started as a uber executable jar 

### ISSUE THREAD

**Issue by segeon** [spring-projects/spring-boot#4868]
I'm trying to instrument a spring boot application using javaagent. My agent works fine when started from my ide by running my main method. However, when I package my app into an executable jar using `spring-boot-maven-plugin`,  my agent fails due to some classloading issues. Detail problem description can be found here [https://github.com/raphw/byte-buddy/issues/87](https://github.com/raphw/byte-buddy/issues/87)

After a probe into spring boot's source code, I found the root cause of this problem. When starting a uber jar, spring boot uses a dedicated classloader named LaunchedURLClassLoader to load resources from the uber jar. This classloader does not respect the normal convention of classloading process. It delegates classloading task to ExtClassloader instead of default system classloader. Moreover, it excludes javaagent jars out of its classpath URLs. Consequently java agent classes are invisible to my application classes and java agent classes can't reference third party classes that packaged in the uber jar neither.

One solution is to package the agent into uber jar too. But it's not so elegant. 

What puzzles me is why spring boot doesn't respect the normal classloading semantics and skip default system classloader during class loading process and why should the LaunchedURLClassLoader ignore javaagent jars. 

Pls help me understand spring boot's considerations. Thanks a lot!  

FYI, I'm using spring boot 1.3.1.RELEASE

**Comment by wilkinsona** [comment]
If launched correctly, Java Agents should work as far as we know. For example, AspectJ load-time weaving is known to work. Can you please provide a sample project that illustrates the problem along with exact details of how to launch your failing application?

**Comment by segeon** [comment]
@wilkinsona here is a sample project git@github.com:segeon/agent-example.git. This sample project contains two modules, one is the agent and the other is testapp. When launched from testapp's main method, the agent works fine. However, when launched from an executable jar, the agent fails.

**Comment by wilkinsona** [comment]
@segeon Thanks for the sample. Can you please provide _exact_ details of how you are running the app when you use the main method and when you use the executable jar?

**Comment by segeon** [comment]
@wilkinsona I've added two scripts in script dir. start_from_exec_jar.sh is for starting the testapp as a spring boot uber jar, while the other script is for starting testapp from it's main method directly, imitating the way running an application from an IDE like Idea. When started using the former method, the agent fails. However, it's ok to start using the latter way. Pls have a try

**Comment by segeon** [comment]
@wilkinsona I've added two scripts in script dir. start_from_exec_jar.sh is for starting the testapp as a spring boot uber jar, while the other script is for starting testapp from it's main method directly, imitating the way running an application from an IDE like Idea. When started using the former method, the agent fails. However, it's ok to start using the latter way. Pls have a try

**Comment by segeon** [comment]
@wilkinsona I've added two scripts in script dir. start_from_exec_jar.sh is for starting the testapp as a spring boot uber jar, while the other script is for starting testapp from it's main method directly, imitating the way running an application from an IDE like Idea. When started using the former method, the agent fails. However, it's ok to start using the latter way. Pls have a try

**Comment by segeon** [comment]
@wilkinsona I've added two scripts in script dir. start_from_exec_jar.sh is for starting the testapp as a spring boot uber jar, while the other script is for starting testapp from it's main method directly, imitating the way running an application from an IDE like Idea. When started using the former method, the agent fails. However, it's ok to start using the latter way. Pls have a try

**Comment by segeon** [comment]
@wilkinsona I've added two scripts in script dir. start_from_exec_jar.sh is for starting the testapp as a spring boot uber jar, while the other script is for starting testapp from it's main method directly, imitating the way running an application from an IDE like Idea. When started using the former method, the agent fails. However, it's ok to start using the latter way. Pls have a try

**Comment by wilkinsona** [comment]
@segeon Thanks again

**Comment by wilkinsona** [comment]
@segeon I don't think we'll be able to do anything about this in 1.3.x, but I believe we can simplify things in 1.4.

I've [prototyped](https://github.com/wilkinsona/spring-boot/tree/gh-4897) some changes for #4897 which dramatically simplifies Boot's custom class loader, allowing it to use standard delegation to the app/system class loader. With these changes in place, you executable jar sample works, albeit with one change. I had to remove `<scope>provided</scope>` from the HTTP client dependency in the agent so that it's included in the jar. That seems reasonable to me as the agent should be self-contained and it relies directly upon HTTP client classes.
