### ISSUE TITLE
All dropwizard-gauges are called synchronously during startup

### ISSUE THREAD

**Issue by lbeuster** [spring-projects/spring-boot#4874]
The MetricRegistryMetricReader.onGaugeAdded() is called during startup for each dropwizard gauge. This method gets the value of the gauge just to check if the value is a number. Unfortunately this is done synchronously during startup.

Since the calculation of the value may take some time (because of a remote call - that's why they have a CachedGauge), this can slow down the startup.

Any thoughts?

**Comment by wilkinsona** [comment]
@lbeuster Is your only concern here the impact on startup time? On initial inspection, it looks as if it would be safe to queue up gauge addition and removal and process them on a background thread.

/cc @dsyer

**Comment by wilkinsona** [comment]
The call to `getValue` was added to fix #2593. That fix could be reworked to filter out non-number gauges  during read rather than write.

**Comment by lbeuster** [comment]
Yes, for me it's only startup time.

**Comment by wilkinsona** [comment]
Thanks, @lbeuster. 00f4538 defers calling `gauge.getValue()` until we're actually trying to produce a Metric from the Gauge so it will no longer happen during startup.
