### ISSUE TITLE
ConfigFileApplicationContextInitializer implementation initializes object to call instance method

### ISSUE THREAD

**Issue by binkley** [spring-projects/spring-boot#4879]
Peculiar implementation for `ConfigFileApplicationContextInitializer`.  It creates a new `ConfigFileApplicationListener` only to call `apply()` and discard the new object.  Would it be reasonable to provide a static method to use for this purpose?  I admit there's a lot going on in `ConfigFileApplicationListener`, though it has no default constructor so it should not be too hard to refactor the call.

**Comment by wilkinsona** [comment]
It's not just calling `apply`. It's also subclassing `ConfigFileApplicationListener` and overriding `apply` so that it can call the protected `addPostProcessors` and `appPropertySources` methods.
