### ISSUE TITLE
Add an API for manipulating well-known property sources

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4884]
There are a few places in the `Environment` where libraries (and apps) often need to add properties. At the moment they don't have any higher level APIs, just the `MutablePropertySources`, which isn't even the default type for an `Environment`. It would be useful to be able to non-destructively append properties in a handful of "well known" positions: default properties, in between application.properties and environment variables and in between system properties and command line properties are the most obvious candidates. Maybe we could do this via simply cataloguing the names and types of well-known property sources.

**Comment by philwebb** [comment]
Duplicates #3783
