### ISSUE TITLE
Provide property to set CassandraSessionFactoryBean.schemaAction

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#4886]
In `CassandraDataAutoConfiguration`, this property is hard-coded to `SchemaAction.NONE`.
Please add this property to `CassandraProperties` so it can be easily changed.

**Comment by mp911de** [comment]
`CassandraSessionFactoryBean` requires an initial set of entities to perform schema actions. Spring Data Cassandra has [_some_](https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/config/java/AbstractCassandraConfiguration.java#L97) support for it but it's an ugly solution. The `initialEntitySet` of [BasicCassandraMappingContext](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/cassandra/CassandraDataAutoConfiguration.java#L65) is not set so `SchemaAction` would not create any tables at all. The initialization of `BasicCassandraMappingContext` would require an entity scan similar to [MongoDataAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.java#L154).

**Comment by snicoll** [comment]
Closing in favour of the PR #5855
