### ISSUE TITLE
spring-boot 1.3.1 with  maven-resources-plugin

### ISSUE THREAD

**Issue by qk4089** [spring-projects/spring-boot#4887]
According Filtering usage ```maven-resources-plugin```  documentation given,If I want to replace the variable,I will follow the example configuration pom.
```   
   <build>
        ...
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.xml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>**/*.xml</exclude>
                </excludes>
            </resource>
        </resources>
       ...
    </build>
```
In version 1.2.6 everything works, but when I use 1.3.1 , variable substitution fail, why? 

Thanks for answering my question, forgive my English is not standard

**Comment by snicoll** [comment]
Have you [read the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering)?

**Comment by qk4089** [comment]
oh,I'm sorry, I did not, thank you for your patience answer
