### ISSUE TITLE
Make it easier to test auto-configured subsystems

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4901]

**Comment by rwinch** [comment]
Some ideas for this:

* [ ] Consider moving logic from [MockMvcAutoConfiguration](https://github.com/philwebb/spring-boot/blob/6b9780e05bb8608ef6693ed116889dccb5f42272/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/web/servlet/MockMvcAutoConfiguration.java#L57) into a `MockMvcConfigurer`. This would allow users to have more fine grained control over what is configured.
* [ ] Consider allowing users to define what they want as mocks (i.e. using MockBean) vs being opinionated.
* [ ] Provide easy mechanism for `MockMvcBuilders.webAppContextSetup(this.context).alwaysDo(print())`
* [ ] Look into integration tests with `HtmlUnit` based tests (i.e. `HtmlUnit`, `WebDriver`, etc). This would provide a default host so users don't need to configure localhost, the port, or context root (if used).
