### ISSUE TITLE
Enable connection validation by default in auto-configured pooled data sources

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4906]
Hikari already calls `Connection.isValid` when a connection is borrowed from the pool by default. We should try to configure the other connection pools (Tomcat JDBC, Commons DBCP(2)) to have the same default behaviour.

**Comment by snicoll** [comment]
Some more information:

* Commons DBCP2 does that by default as well (unless a _validation query_ is provided).
* Commons DBCP does not have such support and a _validation query_ must be provided
* Tomcat also requires a validation query as far as I know and `test-on-borrow` must be set
