### ISSUE TITLE
Add initial support for reactive web

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4908]

**Comment by anandshah123** [comment]
@philwebb Can you explain bit more on this, so I can submit PR?

**Comment by philwebb** [comment]
@anandshah123 Thanks for the offer, but unfortunately behind the innocuous title there is quite a bit of work here. Spring Framework 5 is working on a reactive web stack and this issue is a placeholder for all the work required to get that effort into Spring Boot. It's likely that the effort will take quite some time and involve quite a lot of changes as the Spring Framework 5 effort continues.

If it's an area that interests you we'd very much appreciate feedback when the work starts in earnest. You can already see the core framework changes progressing here: https://github.com/spring-projects/spring-reactive.

/cc @rstoyanchev @bclozel @sdeleuze

**Comment by bclozel** [comment]
The `spring-reactive` repo has now been merged into Spring Framework and is available as the `5.0.0.BUILD-SNAPSHOT` version. We're working on Spring Boot 1.4 and 1.5 - this feature is in the Boot 2.0 milestone.

In the meantime, you can check the [experimental Boot Starter project](https://github.com/bclozel/spring-boot-web-reactive).

**Comment by pabloa** [comment]
Is is possible to have a version working with spring-boot 1.4.x? Or more in general is it possible to have a version that works right now? I tried current version and it does not work. I followed instructions here: https://spring.io/blog/2016/07/20/notes-on-reactive-programming-part-iii-a-simple-http-server-application

**Comment by bclozel** [comment]
@pabloa Could you take a look at the [dedicated Boot Starter](https://github.com/bclozel/spring-boot-web-reactive)? The README explains everything you need to get started.

This starter currently works with Boot 1.4, so I don't understand what you mean. Please open an issue there if you've found a problem. Don't forget to add all the necessary details or a repro project.

**Comment by bclozel** [comment]
Initial support has been merged in master, the [Spring Boot experimental starter](https://github.com/bclozel/spring-boot-web-reactive) is now closed.
