### ISSUE TITLE
Metrics theme

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4909]
Metrics
- Consider splitting out into a new module
- Look at integration with SaaS (Datadog etc)
- Support multi dimensional metrics
- Look at Dropwizard 3rd party offerings, can we support them? (https://dropwizard.github.io/metrics/3.1.0/manual/third-party/)
- Investigate:
  - https://info.typesafe.com/TRL-20XX-Monitoring-Trial_LP.html
  - https://www.takipi.com/
  - https://github.com/kamon-io/docker-grafana-graphite/
  - http://prometheus.io/
  - https://influxdata.com/
  - https://www.librato.com/
  - http://grafana.org/
  - http://www.hawkular.org/
  - New Relic
  - Atlas

**Comment by jiming** [comment]
At client side, I prefer a good point of netflix spectator-api. Which is name and Tag are immutable constants, when I add a new tag to an existing metric, spectator simply create a brand new metric with previous tags and new tags. Which could save a lot of memory for huge data.

Looking forward to the release of spring boot 2 ...

Thanks!

**Comment by iNikem** [comment]
Can I offer more item to your "Investigate" list? [Plumbr](https://plumbr.eu)

**Comment by holgerstolzenberg** [comment]
I´d definetly appreciate some nice integration with Prometheus. Together with Grafana, it is our upcoming preferred stack. Also, Docker engine now has an experimental feature exposing an Proemtheus HTTP endpoint publishing Docker engine/container metrics. Some neat synergies may arise here. 😎

**Comment by wilkinsona** [comment]
This is now being covered by the Micrometer project which replaced Boot's own metrics in 2.0 M4
