### ISSUE TITLE
Spring's load-time weaving doesn't work with `PropertiesLauncher`

### ISSUE THREAD

**Issue by FaboSc** [spring-projects/spring-boot#4911]
Hello, 

I've recently encountered a problem with loading a javaagentfile while using spring-boot zip-layout.
The startup fails, because the LoadTimeWeaver is not specified.
I started the same Application without zip-layout and it worked.

I created a minimal example, which encounters the same Problem.
[https://github.com/FaboSc/Spring_boot](https://github.com/FaboSc/Spring_boot)

Am I doing something wrong here, or is there a problem?

**Comment by wilkinsona** [comment]
Thanks for the sample project. This is a bug in the `PropertiesLauncher`. It's essentially the same problem as was fixed in `JarLauncher` in #863.

**Comment by FaboSc** [comment]
Thanks for the reply and the fast solution.

**Comment by knacht** [comment]
@wilkinsona This bug is filled under the 1.2.9 Milestone. Are those fixes also merged into the 1.3.X Branch?
I could not find something in the Release Notes for Version 1.3.2
Regards

**Comment by wilkinsona** [comment]
@knacht Yes. This fix is in 1.3.2. It was merged from 1.2x into master in https://github.com/spring-projects/spring-boot/commit/89beef4099171ea86a67d5b79b03e9ef325f5e99.

**Comment by knacht** [comment]
Thanks!
