### ISSUE TITLE
Allow MetricsFilter to be configured to include HTTP method in metric name

### ISSUE THREAD

**Issue by sebastiankirsch** [spring-projects/spring-boot#4913]
We're providing an REST API that uses the same URI with different methods (GET, POST, PUT, DELETE).
By coincidence we chose status codes allowing us to distinguish between those methods (200, 201, 204), but that is certainly not the case for similar applications. Although this helps with counter metrics, the gauge metric is reported without the status being included in the metric name, such that distinguishing the execution time fails even for our lucky status choices.

So it would be great to have a property with which to enable that. I'd come up with a PR if you're supportive of the idea.

**Comment by wilkinsona** [comment]
That sounds reasonable to me. @dsyer may well have an opinion too. As you've suggested, it would need to be enabled via a property so that the existing behaviour can be preserved for those who want it.

**Comment by sebastiankirsch** [comment]
So that sounds like it should be configurable if the old gauge metric is reported or the new ones, i.e. XOR and no AND?
Also, I'd assume the metric name to be reported like "response.GET.api.foo.fooId", similar to the counters that look like "status.201.api.foo.fooId"?
And wouldn't it make sense to expand that to the status metrics as well? Although we currently don't support it, one could think of an endpoint /api/foo/{fooId} returning a 204 for both PUT and DELETE.

At first glance, I didn't find a test for the MetricsFilter. Is there something I missed?

**Comment by wilkinsona** [comment]
> At first glance, I didn't find a test for the MetricsFilter. Is there something I missed?

Take a look at [MetricFilterAutoConfigurationTests](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/MetricFilterAutoConfiguration.java).

**Comment by sebastiankirsch** [comment]
Didn't get feedback for my other questions, so I just gave it a shot: [see my fork](https://github.com/spring-projects/spring-boot/compare/master...sebastiankirsch:master)

Will do code formatting and other contributing stuff if we've agreed on the best approach...

**Comment by wilkinsona** [comment]
@sebastiankirsch Thanks, and sorry for not replying to all of your questions earlier.

> So that sounds like it should be configurable if the old gauge metric is reported or the new ones, i.e. XOR and no AND?

We discussed this a bit and think that the best approach might to offer the metrics in a few different forms depending on a configuration setting. The current metric can be thought of as a roll up of the more finely-grained metrics that you are proposing. The current behaviour is to only have the rolled up metric. We think there could be value in offering the more finely grained metrics and the roll up or only offering the more finely grained metrics.

> Also, I'd assume the metric name to be reported like "response.GET.api.foo.fooId", similar to the counters that look like "status.201.api.foo.fooId"?

Looks good to me.

> And wouldn't it make sense to expand that to the status metrics as well?

Yes, I think so.

Would you be interested in making the changes described above?

**Comment by sebastiankirsch** [comment]
So I added the changes you were proposing: recording the fine-grained and rolled-up metrics is now configurable. I thought about issuing a warning if neither metrics are to be recorded, but alas... you gotta know what you do, right?
So the fine-grained metrics look like "status.GET.201.api.foo.fooId" (over "status.201.GET.api.foo.fooId") - is that okay?

Unfortunately I screwed rebasing (still no git pro), so there's a bunch of other commits, but the file comparison shows the important stuff: https://github.com/spring-projects/spring-boot/compare/master...sebastiankirsch:master

**Comment by wilkinsona** [comment]
Looks good, @sebastiankirsch. Thank you. Would you like to turn your changes into a PR now?

**Comment by sebastiankirsch** [comment]
See #5094

**Comment by philwebb** [comment]
The updated PR is #5102

**Comment by philwebb** [comment]
Closing in favor of the PR which was fixed in a15684e67e52b73e3bd67f830cfed1cf589b7185
