### ISSUE TITLE
PropertiesConfigurationFactory stopped supporting properties with snake_case setters

### ISSUE THREAD

**Issue by Hartimer** [spring-projects/spring-boot#4915]
Considering a properties class such as

```Java
public class Foo {
    private String bar;
    private void setMY_BAR(String bar) { this.bar = bar; }
    private String getMY_BAR() { return this.bar; }
}
```
A property named `MY_BAR` in a property source will not be picked up and used for that attribute.
This seems to have changed on version 1.3.0.M3 with commit https://github.com/spring-projects/spring-boot/commit/12b876fbfa2de81f18dba9d3c6dbe530fc81782d. The issue is related to which method of building [RelaxedNames](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/bind/RelaxedNames.java) is used.

```Java
String someProp = "MY_BAR";
new RelaxedNames(someProp).values.contains(someProp); // TRUE
RelaxedNames.forCamelCase(someProp).values.contains(someProp); //FALSE
```
I found this while trying to run [TweetTransformerIntegrationTest](https://github.com/spring-projects/spring-xd-samples/blob/master/tweet-transformer-processor/src/test/java/my/custom/transformer/TweetTransformerIntegrationTest.java) from the Spring XD project while updating Spring Boot from version 1.2.3 to 1.3.x. The properties class that fails is [SingleNodeOptions](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/server/options/SingleNodeOptions.java).

I'm submitting a PR shortly that addresses this issue for your consideration.

**Comment by wilkinsona** [comment]
We don't want to change this. Please see my comment on #4916 for the rationale
