### ISSUE TITLE
Autoconfiguration support for Hazelcast clients

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#4918]
`org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration.java` currently only provides support for Hazelcast server instances.

This could be extended to support Hazelcast client instances.

Hazelcast servers are configured if a `com.hazelcast.core.Config`
Hazelcast clients can be configured with a `com.hazelcast.client.config.ClientConfig`

**Comment by snicoll** [comment]
> This could be extended to support Hazelcast client instances.

Use cases please? I'd rather not add anything unless I have a clear picture of what you would do with this. Thanks.

**Comment by neilstevenson** [comment]
See http://docs.hazelcast.org/docs/latest-dev/manual/html/hazelcasttopology.html, for an outline of Hazelcast deployment topologies.

Is that sufficient justification or do you need more information ?

The key part here is that the Hazelcast Java client could be mostly Spring Boot enabled, but since it is instantiated using `com.hazelcast.client.config.ClientConfig` (and this isn't an instance of `com.hazelcast.core.Config`) it wouldn't be autoconfigured.

**Comment by snicoll** [comment]
More or less: this is still very vague. I understand that you would define a bean of type `ClientConfig` and we would detect that.  If you have a more precise idea, it would be nice to be more specific. A PR is also welcome.

**Comment by gAmUssA** [comment]
@snicoll since there is no distinction between
`Hazelcastinstalce hzInstance = Hazelcast.newHazelcastinstance()` and `HazelcastInstance hzInstance = HazelcastClient.newHazelcastClientInstance()` from API standpoint, for example, https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/springboot-caching/src/main/java/com/hazelcast/springboot/caching/BootifulClient.java#L82, following conditions might can be taken into consideration:

- existence of `HazelcastClient` class in the classpath
- A `ClientConfig` bean defined.
- A `hazelcast-client.xml` is in classpath

What do you think?

**Comment by snicoll** [comment]
I guess I like that. I still need to figure out which takes precedence (probably the server)

**Comment by neilstevenson** [comment]
It wouldn't be normal usage for a process to be both a client and a server, to have both the `ClientConfig` and `Config` beans. It's not unknown, in integration tests for example. 

An XOR test might align better with the notion that autoconfiguration takes over when it's obvious what is needed.

Creating the server instance would be backwards compatible, so would be slightly preferable for that reason.

**Comment by snicoll** [comment]
I find the hazelcast config complex enough already (with the separate instance for the caching support) so the only thing I am ok to add is if the server is not present then auto-configure the client with the hints provided above.

**Comment by vpavic** [comment]
@snicoll what exactly do you mean by "server is not present"?

Having ```com.hazelcast:hazelcast-client``` in your dependency management will also pull in ```com.hazelcast:hazelcast``` as a transitive dependency.

**Comment by snicoll** [comment]
seriously? I meant having only the client library in your classpath (i.e. not having the classes to start a server).

**Comment by vpavic** [comment]
Yeah, see [here](https://search.maven.org/remotecontent?filepath=com/hazelcast/hazelcast-client/3.5.4/hazelcast-client-3.5.4.pom).

I also have some interest in this feature, and have started some work on a PR a week ago but didn't particularly like it due to this dependency link.

**Comment by snicoll** [comment]
Maybe @serkan-ozal can explain the reasoning behind that link and what we could do to offer a default experience that makes sense?

**Comment by gAmUssA** [comment]
@snicoll As I mentioned earlier in this thread, `HazelcastClient` factory creates `HazelcastInstance` instance. `HazelcastInstance` comes from `hazelcast.jar`. That is why there is a dependency to it.

**Comment by snicoll** [comment]
I know that. I am sorry that doesn't explain why the client has a dependency on the server. Unless there is an additional jar that represents the server?

**Comment by jerrinot** [comment]
Hi @snicoll,

it's partially a historical legacy and partially a convenience for our users. 

It makes deployment rules simple:
- everytime you want to use Hazelcast you have to place hazecast.jar on your classpath
- clients have to include hazelcast-client.jar on top of that

The truth is the main Hazelcast JAR is becoming a bit bulky -> We are discussing a true separation so the server-related class would required on a client.  This will allow us to offer thin JARs and let users to compose them as they need.

**Comment by vpavic** [comment]
Hi @jerrinot,

Is there an issue ticket where the development on this separation topic could be tracked?

**Comment by jerrinot** [comment]
@vpavic: not that I know of. no formal artefact has been created. 
please feel free to open a new issue to make it trackable.

**Comment by vpavic** [comment]
I've opened hazelcast/hazelcast#7448.

**Comment by neilstevenson** [comment]
Do we have a determination yet of how this should be solved ? Or would you wish someone to submit a PR with a solution ?

**Comment by vpavic** [comment]
@neilstevenson I've just re-visited this few days ago and have started to sketch something that'll hopefully result in a PR some time next week. Funny how you bumped this one up at nearly the same time :smile:

**Comment by neilstevenson** [comment]
How do you plan to fix ?

I'm thinking

1. If there is `hazelcast.xml`, Hazelcast jars and no instance, create a server instance.
2. If there is `hazelcast-client.xml`, Hazelcast client jars and no instance, create a client instance

**Comment by vpavic** [comment]
Well, if server instance isn't configured and user has provided a way to configure client instance (`ClientConfig` bean or XML config either via config property or default location), then create client `HazelcastInstace`. This should be backward compatible with the current Hazelcast auto-config support.

**Comment by neilstevenson** [comment]
@vpavic What do we need to do to progress this ticket ? Do you need me to review a solution ? Provide a solution ?

**Comment by snicoll** [comment]
@neilstevenson I am more in the camp on not doing anything until Hazelcast provides better modularity for their infrastructure. The auto-configuration is already quite complicated so I am not keen to add further complication there. If you want to give it a try, a PR is most certainly welcome!

**Comment by vpavic** [comment]
@neilstevenson Sorry for not following up on this, I have most of the implementation done for some time now, but prioritization between server and client mode is a bit tricky so I didn't submit the PR yet. @snicoll  I can open the PR with the code I have ATM so you can take a look and see if the approach is something you'd be willing to consider.

Hazelcast client is an important use case for many, so having auto-config support for it would surely be nice. I doubt Hazelcast team will split their core any time soon since it's a major effort.

**Comment by snicoll** [comment]
@vpavic your work on this is much appreciated. Just give me a link to a branch or something and I am more than happy to have a look. You can also submit a partial PR here

**Comment by vpavic** [comment]
Thanks @snicoll, I'll submit the PR later today.

**Comment by miztli** [comment]
If you're currently using SpringBoot, you can configure the client by yourself this way:

1.- Exclude HazelcastAutoConfiguration.class:
`@SpringBootApplication(exclude = {
        HazelcastAutoConfiguration.class
})`

2.- Declare a Configuration class:
`
@Configuration
public class HazelcastClientConfig { 
   
    @Bean
    public HazelcastInstance getHazelcastClientInstance() throws IOException {        
        ClientConfig clientConfig = new ClientConfig();
        clientConfig = new XmlClientConfigBuilder("hazelcast-client-dev.xml").build();
        HazelcastInstance hazelcastInstance=  HazelcastClient.newHazelcastClient(clientConfig);
        return hazelcastInstance;
    }    
}
`

_Use an XML to configure the client, this way if you need to add more configuration, you only add it to the XML and not directly into the code_

3.- Inject it know wherever it suits you best:

`
@Autowired
    private HazelcastInstance hazelcastInstance;
`

**Comment by snicoll** [comment]
@miztli step2 is not necessary. If you expose a `HazelcastInstance` bean (as defined in your third  step) the auto-configuration will backoff automatically.

**Comment by snicoll** [comment]
Closing in favour of pr #7469
