### ISSUE TITLE
Maven resource filtering is broken in 1.3.1.RELEASE

### ISSUE THREAD

**Issue by britter** [spring-projects/spring-boot#4920]
I have a small [demo application](https://github.com/britter/spring-boot-heroku-demo), that I use to show case Spring Boot on Heroku. I'm using maven resource filtering to write build time information to messages.properties (for more information what I'm doing with filtering have a look at my [blog post](https://blog.codecentric.de/en/2016/01/how-to-add-a-github-commit-link-to-a-web-application/)). After updating from 1.2.6.RELASE to 1.3.1.RELEASE the resource filtering does not work anymore.

Steps to reproduce:

```
$ git clone https://github.com/britter/spring-boot-heroku-demo.git
$ cd spring-boot-heroku-demo

$ git checkout 0.2.4
$ mvn clean install
$ cat target/classes/messages.properties
git.commit.hash=de274e6e1683cce1425e7bf787308f0af3ca2327
git.commit.link=https://github.com/britter/spring-boot-heroku-demo/commit/de274e6e1683cce1425e7bf787308f0af3ca2327
project.version=0.2.4

$ git checkout 0.2.5
$ mvn clean install
$ cat target/classes/messages.properties
git.commit.hash=${buildNumber}
git.commit.link=${git.commit.link}
project.version=${project.version}

$ git diff 0.2.4 0.2.5
diff --git a/pom.xml b/pom.xml
index 1371acb..84634fc 100644
--- a/pom.xml
+++ b/pom.xml
@@ -20,12 +20,12 @@

     <groupId>com.github.britter</groupId>
     <artifactId>spring-boot-heroku-demo</artifactId>
-    <version>0.2.4</version>
+    <version>0.2.5</version>

     <parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
-        <version>1.2.6.RELEASE</version>
+        <version>1.3.1.RELEASE</version>
     </parent>

     <dependencies>
```

I didn't have the time yet to dig into what is causing the problem, but since the only difference between the two code bases is the spring boot version, I suspect it has something to do with the spring-boot-maven-plugin.

**Comment by wilkinsona** [comment]
You are using the wrong delimiter. Please see the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering) for further information.

**Comment by britter** [comment]
Thank you!
