### ISSUE TITLE
Can't change html when using "spring-boot-starter-mustache" with Eclipse.

### ISSUE THREAD

**Issue by kurofune** [spring-projects/spring-boot#4921]
I want to use SpringBoot, SpringDevtool, Mustache, Gradle, and Eclipse on Windows10.
But not work.

0. I run as "Spring Boot app" at Eclipse, and Tomcat start.
0. I can change html in "src/main/templates"
0. I access "localhost:8080" by chrome browser.
0. I change html, then Eclipse error `The project was not built due to "Could not delete '/${projectname}/bin/templates'.". Fix the problem, then try refreshing this project and building it since it may be inconsistent` occurred, so "localhost:8080" return error.

Are SpringBoot and Mustache and Eclipse bad combination?

My build.gradle is ...

```
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'spring-boot' 

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
}

buildscript {
	repositories {
	    mavenCentral()
	}
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.1.RELEASE")
    }
}

dependencies {
	compile 'org.springframework.boot:spring-boot-starter-web:1.3.1.RELEASE'
	compile 'org.springframework.boot:spring-boot-starter-mustache:1.3.1.RELEASE'
}
```

**Comment by wilkinsona** [comment]
It sounds like something has opened a file in `bin/templates` and hasn't closed it. Unlike UNIX-like Platforms, Windows refuses to delete such files. I can't be more specific than that with the information you have provided. Can you provide a small sample that reproduces the problem?

**Comment by kurofune** [comment]
I created sample. "https://github.com/kurofune/spring-boot-sample"

I tried 2 ways.

1. from Gradle
  + I execute `gradlew bootRun`.
  + I can change templates/index.html after accessing http://localhost:8080
  + But in this way, I can not  proceed to next springboot devtool.  (ex.  http://stackoverflow.com/questions/32572784/cant-get-spring-boot-devtools-auto-restart-get-to-work-with-1-3m5-with-eclipse)

2. from Eclipse
  + I import this project to Eclipse using `gradlew eclipse`.
  + I execute `Run as Spring Boot App` from Eclipse.
  + I can change templates/index.html before accessing http://localhost:8080.
  + I can NOT change templates/index.html after accessing http://localhost:8080, and Eclipse said `The project was not built due to "Could not delete '/spring-boot-sample/bin/templates'.". Fix the problem, then try refreshing this project and building it since it may be inconsistent`.

Tell me if need more information.

**Comment by wilkinsona** [comment]
Thanks for the sample project, @kurofune. I've found the problem: Spring Boot's `MustacheViewResolver` was not closing the `Reader` used to read the template when it's being compiled. This open file handle prevents `bin/templates/index.html` from being deleted on Windows.
