### ISSUE TITLE
Maven filtering doesn't work since 1.3.0.RELEASE

### ISSUE THREAD

**Issue by gkislin** [spring-projects/spring-boot#4928]
pom.xml
```
    <properties>
        <config.dir>qwerty</config.dir>
    </properties>
```
application.properties
   `app.config.dir: ${config.dir}`

filtering OK in 1.2.8.RELEASE, but broken since 1.3.0.RELEASE
Reason is `<useDefaultDelimiters>false</useDefaultDelimiters>` in `maven-resources-plugin` of
spring-boot-starter-parent-1.3.0.RELEASE.pom.

Without this line filtering work ok.

**Comment by wilkinsona** [comment]
You are using the wrong delimiter. Please see the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering) for further information.
