### ISSUE TITLE
Reloading of static files not work in spring-boot-starter-parent 1.3.*

### ISSUE THREAD

**Issue by qqiangwu** [spring-projects/spring-boot#4933]
I'm using maven 3.0.5, Intellij 15.0.1, Java 8, Ubuntu 14.04. When I use `spring-boot-starter-parent 1.3.*`, the static files will not be reloaded after I changed it. However when I change back to `spring-boot-starter-parent 1.2.*`, the reloading works again. So is this a bug?

**Comment by wilkinsona** [comment]
Duplicates #4692
