### ISSUE TITLE
Allow setting of addition properties for spring.datasource like spring.jpa.

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#4943]
Some JDBC vendors have specific configuration features, some of which might be set through the URL others are prohibited (Oracle is a good example for this). It would be nice if a the `spring.datasource` section would allow and use `spring.datasource.properties` just like in the case of `spring.jpa.properties` and `spring.mail.properties`. 

That way there would be a generic way of providing additional, vendor specific properties. 

See also [this SO question](http://stackoverflow.com/questions/34789220/optimizing-jdbc-fetch-size-by-use-of-spring-boots-application-properties).

**Comment by snicoll** [comment]
Is it related [to this SO question](http://stackoverflow.com/questions/34789220/optimizing-jdbc-fetch-size-by-use-of-spring-boots-application-properties)? If so, @mdeinum please make sure to include the link as it contains additional useful information.

**Comment by mdeinum** [comment]
Added to the issue (although it was already in your comment). Implementing this might be a challenge with all the different datasources available.

**Comment by mdeinum** [comment]
Instead of making it a general solution it might be easier (or better?) to add some documentation how to add additional configuration properties. (See http://stackoverflow.com/questions/34856811/how-to-set-custom-connection-properties-on-datasource-in-spring-boot-1-3-x-with?noredirect=1#comment57481391_34856811) this works because of the `RelaxedBinder` working on the actual `DataSource` implementation.

**Comment by mdeinum** [comment]
I guess the improved documentation added with gh-2183 would fix this. As it is now clear how to set non generic properties. So I suggest closing this issue as well.

**Comment by snicoll** [comment]
Indeed, thanks for the heads up.
