### ISSUE TITLE
executable jar - add log rotation feature

### ISSUE THREAD

**Issue by ivnik** [spring-projects/spring-boot#4944]
It would be nice to be able to log file rotation with cronolog or similar tool.

for example:
```diff
-  >> "$log_file" 2>&1
+ 2>&1 | cronolog --link "$log_file".log  "$log_file".%Y-%m-%d.log  
```

where $log_file symlink to current log file (logname.log -> logname.2016-01-14.log)

**Comment by wilkinsona** [comment]
I don't think this belongs in the default launch script. `cronolog` doesn't appear to be installed by default so it'll risks breaking the script for some people. I think you should either configure log rotation separately, or configure your executable jar to use a custom launch script.

**Comment by ivnik** [comment]
It may be worth making a env variable to select the method of log-rotation? 

$log_rotatione = none | cronolog | multilog | xxx..

**Comment by wilkinsona** [comment]
Sorry, but I still don't think it's a good idea. Not all log rotation tools accept input from stdin, i.e. piping in the application's output may not work. We'll end up heading down the route of people coding a chunk of Bash in an environment variable which I'd rather avoid.
