### ISSUE TITLE
Use existing JdbcTemplate for NamedParameterJdbcTemplate

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#4945]
Currently in the [`JdbcTemplateConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration.java#L133) both a `JdbcTemplate` as well as a `NamedParameterJdbcTemplate` are created based on a `DataSource`. This effectively results in creating 2 `JdbcTemplate` instances. Wouldn't it be better to create the `NamedParameterJdbcTemplate` using the existing `JdbcTemplate`?

**Comment by wilkinsona** [comment]
There are some subtleties here that we need to consider:

- changing `NamedParameterJdbcTemplate` to be created with an injected `JdbcTemplate` will require there to be a single `JdbcTemplate` bean (or multiple with one that's `@Primary`)
- the behaviour of the auto-configured `NamedParameterJdbcTemplate` may change as it'll be using a different `JdbcTemplate` under the covers. 

A user could avoid the latter by declaring their own `NamedParaeterJdbcTemplate`. The former should perhaps be tackled by using `@ConditionalOnSingleCandidate`.
