### ISSUE TITLE
reference versions for maven plugins in spring-boot-starter-parent

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#4952]
so for example we have `maven-surefire-report-plugin` and it needs? to be on the same version as `maven-surefire-plugin`, which now has its version supplied by the BOM. Now I don't mind not having the report plugin version supplied by the BOM (have this with `hamcrest-integration` but I'd like to be able to reference the version in the BOM like I do with `hamcrest` for `hamcrest-integration`

**Comment by tsachev** [comment]
:+1: on having properties for the versions of maven plugins. Ideally I would love to be able to update the versions of all the plugins declared in maven's super pom, `spring-boot-dependencies` and `spring-boot-starter-parent`. I agree with @xenoterracide that `<reporting>` is not very popular these days, and if someone really needs versions for those plugin could do it by himself, but for compiler, javadoc, antrun, resources, buildhelper, etc  boot should provide properties for their versions.
