### ISSUE TITLE
Allow spel expressions to control the access to actuator endpoints

### ISSUE THREAD

**Issue by pmvilaca** [spring-projects/spring-boot#4962]
It would be nice if we could use a spel expression to control the access to the actuator endpoints.

This idea come from the need to restrict the access to the endpoints only for requests from the same network (e.g. 10.0.0.0/16).

After discussing this in spring-boot gitter channel, @dsyer suggested that we could have a property like `management.security.access` that can accept a spel expression if `management.security.role` isn't defined.

**Comment by philwebb** [comment]
We'd rather not increase the complexity here. You can write your own config if you want custom security.

**Comment by shakuzen** [comment]
@philwebb Did you intend to close this issue, also?

**Comment by snicoll** [comment]
Yes. Thanks tommy!
