### ISSUE TITLE
Error message for overriding logback.xml configurationFile is incorrect

### ISSUE THREAD

**Issue by jvwilge** [spring-projects/spring-boot#4969]
When I want to override my logback.xml and start my application with
`java -Dlogback.configurationFile=config/logback.xml -jar harrie-boot.jar` I get the following message :
`Ignoring 'logback.configurationFile' system property. Please use 'logging.path' instead.`

`logging.path` is the location of the logging output, not the config path.

`logging.path` should be changed to `logging.config`

The error message is located in the class `org.springframework.boot.logging.logback.LogbackLoggingSystem` in the `initialize` method

More information can be found at http://stackoverflow.com/questions/21723324/dlogback-configurationfile-logback-xml-ignored-when-running-spring-boot

**Comment by snicoll** [comment]
Oh wow, good catch! I realize now that the Javadoc of `LogFile` is completely wrong.

**Comment by snicoll** [comment]
See #2382
