### ISSUE TITLE
Harmonize LoggingApplicationListener constants

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4970]
`LoggingApplicationListener` defines a bunch of unused public constants.

**Comment by snicoll** [comment]
See #2068

**Comment by snicoll** [comment]
Rather than having a duplicate, we can move the actual values in `LoggingApplicationListener` and use them from there.

**Comment by mbhave** [comment]
[comment above](https://github.com/spring-projects/spring-boot/issues/4970#issuecomment-263913917) `PATH_PROPERTY` and `FILE_PROPERTY` mentioned in #2068 don't look like they are used anymore and maybe we can deprecate them.

**Comment by snicoll** [comment]
Good catch @mbhave!
