### ISSUE TITLE
Investigate Hashicorp HCL as a config format

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#4974]
https://github.com/hashicorp/hcl

see #3558 

Would bring in JSON as a config format as well.

> HCL is also fully JSON compatible. That is, JSON can be used as completely valid input to a system expecting HCL. This helps makes systems interoperable with other systems.

Could be useful for folks using Spring Cloud Consul and other hashicorp tools (vault, etc...).

HCL in java https://github.com/VladRassokhin/intellij-hcl

**Comment by snicoll** [comment]
Adding my usual warning regarding tooling support.

**Comment by philwebb** [comment]
We already hit some problems supporting yaml and properties so I'd rather not add another one to the mix. It's possible to define your own `PropertySourceLoader` if you want to support a different format outside of Spring Boot.
