### ISSUE TITLE
executable property missing from bootRepackage gradle task

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#4978]
According to the documentation at http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-repackage-configuration, the bootRepackage task has a property named ```executable```. This is not the case. The ```executable``` property currently only exists on the parent ```springBoot``` configuration.

**Comment by wilkinsona** [comment]
Three other properties are also missing:

- embeddedLaunchScript
- embeddedLaunchScriptProperties
- excludeDevtools
