### ISSUE TITLE
gradle customConfiguration not working properly

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#4979]
According to the documentation at http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-repackage-configuration, ```customConfiguration``` can be used to specify a custom configuration for dependencies included. I would like to only include runtime dependencies and not compile dependencies. I tried using 

    springBoot {
        customConfiguration = 'runtime'
    }

but I still get compile dependencies that are not included in runtime. I am using the [gradle-extra-configurations-plugin] (https://github.com/nebula-plugins/gradle-extra-configurations-plugin) for its provided configuration that includes dependencies in compile and not runtime.

**Comment by wilkinsona** [comment]
I believe this is working as designed. The `runtime` configuration inherits from the `compile` configuration so it contains its own dependencies and those in the `compile` configuration. You need to define your own configuration that only contains the dependencies that you want, i.e. the dependencies in runtime minus those in compile.
