### ISSUE TITLE
@RequestBody is null

### ISSUE THREAD

**Issue by zhuxinjun** [spring-projects/spring-boot#4982]
Spring Boot version is 1.3.1,when i  receive parameters by useing @ResquestBody, the value is null. however,@RequestParam is ok.

**Comment by wilkinsona** [comment]
You haven't provided anywhere near enough information to diagnose the problem. If you would like us to investigate, please provide a small sample that reproduces the problem.

**Comment by qiuxiaoj** [comment]
You must setting http request header:
```
contentType: application/json
dataType: json
```

**Comment by zhuxinjun** [comment]
this is the request:
![image](https://cloud.githubusercontent.com/assets/7918671/12501286/5b61be36-c0f6-11e5-9058-59127eb35561.png)
and ther controller is like this:
       @RequestMapping(value = "/model/{modelId}/save", method = RequestMethod.PUT)
       @ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody void saveModel(@PathVariable String modelId,
			@RequestBody MultiValueMap<String, String> valuesByBody) {
        }
![image](https://cloud.githubusercontent.com/assets/7918671/12501334/ba9b51be-c0f6-11e5-8347-fd5fe695af2b.png)

**Comment by wilkinsona** [comment]
@zhuxinjun Thanks, but a screenshot isn't very helpful as it doesn't give me a complete view of the problem. As I said above, please provide a small sample that reproduces the problem.

That said, using `@RequestBody` with an `application/x-www-form-urlencoded` request is rather strange. When you `POST` form data, the posted data is available as request parameters. As you've noted, you can access those using `@RequestParam`. Along with a small sample, perhaps you can also explain what you're trying to do?

**Comment by zhuxinjun** [comment]
@wilkinsona  ok, i also think is strang to using @RequestBody. actruly the code is from another project named activiti. now i tested a small sample,but the same error occurred. however,if change PUT to POST, it will be ok.

**Comment by wilkinsona** [comment]
Spring Boot auto-configures an `HttpPutFormContentFilter` for you. From its javadoc:

> `javax.servlet.Filter` that makes form encoded data available through the `ServletRequest.getParameter*()` family of methods during HTTP PUT or `PATCH` requests.

> The Servlet spec requires form data to be available for HTTP POST but not for HTTP PUT or PATCH requests. This filter intercepts HTTP PUT and PATCH requests where content type is `application/x-www-form-urlencoded`, reads form encoded content from the body of the request, and wraps the ServletRequest in order to make the form data available as request parameters just like it is for HTTP POST requests.

You should use `@RequestParam`, or `ServletRequest.getParameter*()` to access request parameters for `POST`, `PUT`, and `PATCH` requests.
