### ISSUE TITLE
logback-spring.xml vs. spring-logback.xml

### ISSUE THREAD

**Issue by rakk** [spring-projects/spring-boot#4986]
Hi,

We can find **spring-logback.xml** in the documentation:
[github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc)
( [docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html) )

and **logback.xml-spring** in the this documentation:
[github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc)
( [docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html) )

For me works only **logback-spring.xml** and it seems that the documentation is inconsistent.
Could you please take a look and confirm?

Pull request created: https://github.com/spring-projects/spring-boot/pull/4987

**Comment by snicoll** [comment]
Closing in favour of the PR #4987
