### ISSUE TITLE
Spring-boot 1.3 spring.dao.exceptiontranslation.enabled set to false doesn't disable the feature

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#4991]
Hi,

The following property 'spring.dao.exceptiontranslation.enabled' seems to be unused. When I look the code of MongoDataAutoConfiguration which instantiate mongoDbFactory I see

<pre><code>
	@Bean
	@ConditionalOnMissingBean(MongoDbFactory.class)
	public SimpleMongoDbFactory mongoDbFactory(MongoClient mongo) throws Exception {
		String database = this.properties.getMongoClientDatabase();
		return new SimpleMongoDbFactory(mongo, database);
	}
</code></pre>

And then the SimpleMongoDbFactory constructor set a exceptionTranslator : MongoExceptionTranslator

<pre><code>
	private SimpleMongoDbFactory(MongoClient client, String databaseName, boolean mongoInstanceCreated) {

		Assert.notNull(client, "MongoClient must not be null!");
		Assert.hasText(databaseName, "Database name must not be empty!");

		this.mongo = client;
		this.databaseName = databaseName;
		this.mongoInstanceCreated = mongoInstanceCreated;
		this.exceptionTranslator = new MongoExceptionTranslator();
		this.credentials = UserCredentials.NO_CREDENTIALS;
		this.authenticationDatabaseName = databaseName;
	}
</pre></code>

Is this property doesn't supported ?

Thanks,

**Comment by RaphC** [comment]
After some investigation it appears the PersistenceExceptionTranslationAutoConfiguration is only enable/disable when the property is defined whatever the value set

<pre><code>
	@Bean
	@ConditionalOnMissingBean(PersistenceExceptionTranslationPostProcessor.class)
	@ConditionalOnProperty(prefix = "spring.dao.exceptiontranslation", name = "enabled", matchIfMissing = true)
	public static PersistenceExceptionTranslationPostProcessor persistenceExceptionTranslationPostProcessor() {
		PersistenceExceptionTranslationPostProcessor postProcessor = new PersistenceExceptionTranslationPostProcessor();
		postProcessor.setProxyTargetClass(true);
		return postProcessor;
	}
</pre></code>

**Comment by snicoll** [comment]
I am confused. Are you trying to disable Mongo's exception translator? If so, that property you referenced was never meant to do that. It would be easier if you'd explain what you're trying to do.

**Comment by RaphC** [comment]
Hi,

I wanted to test the behavior of my application with translator enabled then disabled when the app faced a mongo read timeout in order to compare the difference between.

Regards

**Comment by wilkinsona** [comment]
Thanks for describing what you're trying to do. As @snicoll explained above, the property that you're using isn't intended to disable exception translation for Mongo. `spring.dao.exceptiontranslation.enabled` controls exception translation for your application's own data access objects via the use of `PersistenceExceptionTranslationPostProcessor`.

If you'd like to be able to configure the exception translator in `SimpleMongoDbFactory`, you'll need to raise a requirement with the Spring Data MongoDB project as it's not possible at the moment (without resorting to reflective hacks). You can do so by [opening a JIRA](https://jira.spring.io/browse/DATAMONGO).

**Comment by RaphC** [comment]
Thanks for your response. The property name is just a bit confusing.

Regards
