### ISSUE TITLE
RequestContext.getMessage failed in spring-boot:1.3.2

### ISSUE THREAD

**Issue by AceBear** [spring-projects/spring-boot#5005]
RequestContext.getMessage(...) succeed in spring-boot:**1.3.1**
But failed in **spring-boot:1.3.2** 

Is there a break change in spring-boot 1.3.2 ?

---- below is the details ---

My project worked fine these days
but just few hours ago, after I executed the `gradle build` command, it reported an error:
`no message found under code 'title' for locale 'zh_CN'.`

I noticed that the spring boot was upgrade from 1.3.1 to 1.3.2.
And after modified the build.gradle file to force to use 1.3.1, all thing is ok.

```java
@Controller
public class HomeController{
    @RequestMapping(path="/")
    public ModelAndView HomePage(HttpServletRequest request){
        RequestContext reqCtx = new RequestContext(request);
        reqCtx.getMessage("title");  // <====This line failed in 1.3.2
    }
}

// All configuration is come from auto config of spring boot application
@SpringBootApplication
public class Application {
    public static void main(String[] args){
        appCtx = SpringApplication.run(Application.class, args);
    }
    ....
}
```

build.gradle
```groovy
dependencies {
    compile("org.springframework.boot:spring-boot-starter-freemarker:1.3.1.RELEASE")
}
```

`title` is a key in message bundler
src/main/resources/message_en_US.properties
src/main/resources/message_zh_CN.properties
```
title = \u9996\u9875
```

**Comment by wilkinsona** [comment]
Sorry to hear that you've had trouble upgrading.

> Is there a break change in spring-boot 1.3.2 ?

Yes, if you have `messages_<locale>.properties` files but do not have a default `message.properties` file in place. From the [release announcement](https://spring.io/blog/2016/01/22/spring-boot-1-3-2-released):

> If you are upgrading from 1.3.1 there is one potentially breaking change; we now only search for `messages.properties` (and not `messages*.properties`) to enable auto-configuration of a message source. If you previously had a message file of the form `messages_en.properties` and you didn’t include a default `messages.properties` file, you will now need to add one.

**Comment by AceBear** [comment]
Thanks. This resolved my problem.
