### ISSUE TITLE
Support restart.exclude.* in ~/.spring-boot-devtools.properties

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#5008]
Currently to exclude classes from the restart classloader you have to put a cryptic pattern in META-INF/spring-devtools.properties. I.e. it has to go in the application code itself which kind of sucks. I would have assumed that ~/.spring-boot-devtools.properties would be a valid place for this as well, but apparently it doesn't work. Is there a reason for that?

**Comment by snicoll** [comment]
> it has to go in the application code itself which kind of sucks

Can you clarify what you mean by that? What you exclude is typically application dependent isn't it?

**Comment by dsyer** [comment]
It's hard to remember what I was doing 2 years ago. Probably I didn't like packaging `spring-devtools.properties` in the app jar file (I can't think of anything else that might have been bothering me).

**Comment by snicoll** [comment]
You don't have to (you can exclude the resource). IMO it feels a bit unnatural to specify that property in user settings so I am going to close this. We can reopen it if you remember why it bugged you.
