### ISSUE TITLE
Allow adding to the default SkipPatternJarScanner tomcat tld skip list rather than just overwriting.

### ISSUE THREAD

**Issue by davidmelia** [spring-projects/spring-boot#5010]
Hi,

Tomcat TLD scanning is adding significant time to our start up time due to our large number of dependencies.  Spring Boot 1.3.1 has the ability to `setTldSkip` pattern via `TomcatEmbeddedServletContainerFactory` but this overwrites the default set of helpful tld skip JARS maintained in the class `org.springframework.boot.context.embedded.tomcat.SkipPatternJarScanner`.  

Would it be possible to suggest an improvement to allow adding additional tld skip jars to the default list in `SkipPatternJarScanner` rather than just overwriting?

Thanks

**Comment by ptahchiev** [comment]
+ 100 this is a really a must.
