### ISSUE TITLE
@EnableOAuth2Sso OAuth2ClientAuthenticationProcessingFilter is not publishing InteractiveAuthenticationSuccessEvent

### ISSUE THREAD

**Issue by golonzovsky** [spring-projects/spring-boot#5012]
I'm using basic SSO setup (with `@EnableOAuth2Sso`) with Google provider. I'm trying to intercept success authentication in a clean way to maintain internal profile entities. 
Noticed that `InteractiveAuthenticationSuccessEvent`, which looks like good candidate, is not fired. Please see below investigation:

`OAuth2ClientAuthenticationProcessingFilter` is created manually in `SsoSecurityConfigurer` therefore its not processed by `ApplicationContextAwareProcessor` and its superclass -aware interfaces are not set. 

This causes an issue with `InteractiveAuthenticationSuccessEvent` not being fired by `AbstractAuthenticationProcessingFilter` due to null `ApplicationEventPublisher`. 

Could you please clarify if I'm not missing something? Suggestion is either to set manually eventPublisher, or create this filter as a `@Bean`, or call `AutowireCapableBeanFactory.initialize` on it..

**Comment by dsyer** [comment]
I wouldn't like to add it as a bean unless it is obviously the only wa forward (you'd have to also add a filter registration to make sure it didn't get registered as a servlet filter). But go ahead and propose a change via a pull request if you have something working already.

**Comment by golonzovsky** [comment]
seems to be fixed under [5853](https://github.com/spring-projects/spring-boot/issues/5853)  with [6f4ec4e](https://github.com/spring-projects/spring-boot/commit/6f4ec4e741b4bd0ce79d610b1558ae149bec6e6a)

AuthenticationSuccessEvent is available with all necessary information
