### ISSUE TITLE
Spring Web Flow starter

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-boot#502]
Create a starter for SWF to be able to easily integrate SWF configs into Boot apps. Not sure what it would look like, but creating an issue so it could be considered.

**Comment by dima767** [comment]
Old thread. I know, I know. But just for the record. Here's what currently requires at minimum for config to get the Boot going with SWF and Thymeleaf:

```java
@Configuration
public class WebFlowConfig extends AbstractFlowConfiguration {

    @Autowired
    private WebMvcConfig webMvcConfig;

    @Autowired
    private List<ViewResolver> viewResolvers;

    @Bean
    public FlowExecutor flowExecutor() {
        return getFlowExecutorBuilder(flowRegistry())
                .addFlowExecutionListener(new SecurityFlowExecutionListener(), "*")
                .build();
    }

    @Bean
    public FlowDefinitionRegistry flowRegistry() {
        return getFlowDefinitionRegistryBuilder(flowBuilderServices())
                .setBasePath("classpath*:/templates")
                .addFlowLocationPattern("/**/*-flow.xml")
                .build();
    }

    @Bean
    public FlowBuilderServices flowBuilderServices() {
        return getFlowBuilderServicesBuilder()
                .setViewFactoryCreator(mvcViewFactoryCreator())
                .build();
    }

    @Bean
    public MvcViewFactoryCreator mvcViewFactoryCreator() {
        viewResolvers.add(this.webMvcConfig.ajaxThymeleafViewResolver());

        MvcViewFactoryCreator factoryCreator = new MvcViewFactoryCreator();
        factoryCreator.setViewResolvers(viewResolvers);
        factoryCreator.setUseSpringBeanBinding(true);
        return factoryCreator;
    }

}
```

```java
@Configuration
public class WebMvcConfig extends WebMvcConfigurerAdapter {

    @Autowired
    private WebFlowConfig webFlowConfig;

    @Autowired
    private SpringTemplateEngine springTemplateEngine;

    @Bean
    public FlowHandlerMapping flowHandlerMapping() {
        FlowHandlerMapping handlerMapping = new FlowHandlerMapping();
        handlerMapping.setOrder(-1);
        handlerMapping.setFlowRegistry(this.webFlowConfig.flowRegistry());
        return handlerMapping;
    }

    @Bean
    public FlowHandlerAdapter flowHandlerAdapter() {
        FlowHandlerAdapter handlerAdapter = new FlowHandlerAdapter();
        handlerAdapter.setFlowExecutor(this.webFlowConfig.flowExecutor());
        handlerAdapter.setSaveOutputToFlashScopeOnRedirect(true);
        return handlerAdapter;
    }

    @Bean
    public AjaxThymeleafViewResolver ajaxThymeleafViewResolver() {
        AjaxThymeleafViewResolver viewResolver = new AjaxThymeleafViewResolver();
        viewResolver.setViewClass(FlowAjaxThymeleafView.class);
        viewResolver.setTemplateEngine(springTemplateEngine);
        return viewResolver;
    }
}
```

As one could imagine this boilerplate will be needed in every Boot/SWF/Thymeleaf project. So perhaps a starter which will contribute an autoconfigure for this minimum set of beans or may be an explicit `@EnableSpringWebFlow`.

Just a food for thought.

Cheers,
D.

**Comment by chrylis** [comment]
+1 for adding the starter. Web Flow may be out of fashion, but it looks like it's exactly the tool I need for handling some workflow wizards, and Spring Session just made the keep-partial-transactions-in-session-state model workable again. The configuration above, cleaned up a tad a Bootified, would be very helpful as a starter config. I'd be up for building a starter if there was a likelihood it'd be added.

**Comment by dima767** [comment]
@chrylis Go for it. What's the worst that could happen? If it doesn't get included in Boot's core, this could always be packaged and released as a sep. dependency, etc.

**Comment by chrylis** [comment]
@dima767 There's a lot of subtlety regarding view and resource resolvers that I don't understand. (For example, using relative view paths Just Doesn't Work, and while I've read the code and see why it doesn't work, I don't understand why the code if written that way.) I have a configuration that works-for-me, but something suitable for general consumption would need specific review.

**Comment by eruiz** [comment]
Just fyi,

Spring Roo 2.0.0.M3 generates Spring Boot applications and integrates Spring Web Flow easier than ever. 

The [reference guide](http://docs.spring.io/spring-roo/docs/2.0.x/reference/html/) includes detailed descriptions of all the features.

**Comment by liudonghua123** [comment]
Glad to see this feature.

**Comment by eroispaziali** [comment]
Would really love if this could be reconsidered. Web Flow is a very good solution to a problem that is still relevant today, it would be great to have an official starter for it.

**Comment by usharik** [comment]
Please reopen it if possible.

**Comment by JPCui** [comment]
now?

**Comment by philwebb** [comment]
Although Spring Web Flow still serves a purpose and is being maintained, we don't feel like it's a good candidate to have support out of the box in Spring Boot. We're mainly seeing developers opt for richer Javascript frameworks when they need flow style applications, and we'd rather encourage that direction.

Sorry to everyone that's tracking the issue, but we have no plans to add Spring Web Flow support.

**Comment by frozar** [comment]
@philwebb Hi, I have a simple question : Is Spring Web Flow becoming a deprecated solution/framework?

**Comment by philwebb** [comment]
@frozar The project has not been deprecated, but these days we are seeing more javascript frameworks being used to provide web flow type functionality in green field projects. We’ll continue to maintain Spring Web Flow, but we won’t be adding any new features to it.
