### ISSUE TITLE
Using log4j issues

### ISSUE THREAD

**Issue by dagnelies** [spring-projects/spring-boot#5024]
Hi,

I'm trying to use log4j as shown here:

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

```
  <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>1.3.1.RELEASE</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
        <version>1.3.1.RELEASE</version>
        <exclusions>
            <exclusion>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-logging</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-log4j</artifactId>
        <version>1.3.1.RELEASE</version>
    </dependency>
```

However, it fails when building it with maven:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
```

Any idea?

**Comment by wilkinsona** [comment]
The [Actuator Log4j](https://github.com/spring-projects/spring-boot/tree/v1.3.1.RELEASE/spring-boot-samples/spring-boot-sample-actuator-log4j) sample essentially does the same thing without any problems. There must be something different in your case, but I can't tell what that is from the pom snippet that you've shared above. If you'd like us to investigate, please provide a complete sample project that illustrates the problem.

**Comment by snicoll** [comment]
Side note: log4j 1.x is EOL and will be removed in Spring Boot 1.4 (good thing that @wilkinsona gave you a link pointing to a tag!). You may want to consider upgrading to Log4j 2

**Comment by dagnelies** [comment]
@snicoll I simply can't because of legacy dependencies.

Btw, I solved my issue. Somehow, the way srping-boot initializes overrode my settings. I managed to re-override it though:
```
public class Whatever extends SpringBootServletInitializer {
    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
           super.onStartup(servletContext);
           PropertyConfigurator.configure(...);
```

I know it's a hack. But after having spent nearly a week getting it to work without success, I was close to going nuts.

**Comment by wilkinsona** [comment]
@dagnelies The error that you mentioned initially (`Failed to load class "org.slf4j.impl.StaticLoggerBinder"`), indicates that the classpath is wrong. I don't understand how the `SpringBootServletInitializer` subclass above could fix that.

While Spring Boot's Log4j support is going away in 1.4, we still want it to work well in 1.3. Can you please provide us with a sample project that demonstrates the problem you were having? We'll then take a look and see if we can improve things.

**Comment by dagnelies** [comment]
PS: that's why I mentioned it's probably two unrelated issues.

The initial one `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".` (which I assumed was the source of my issue) might be related to some other stuff, like:
http://stackoverflow.com/questions/11916706/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder-error
...running maven through the command line worked fine. However, not aware of this, it caught my attention for quite a while.

The other issue is that I have dynamically set  Log4J's settings during initialization through `PropertyConfigurator.configure(...);`, the properties file path being provided in the servlet's context. But I apparently have done that at the wrong place (in `configure()`) since it was somehow overridden afterwards.

**Comment by snicoll** [comment]
> @snicoll I simply can't because of legacy dependencies.

You know you can [redirect log4j calls to slf4j](http://www.slf4j.org/legacy.html) and then do whatever you like, right? Why don't you [use the features](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logging) that Spring Boot exposes for configuration ? It feels to me you're hacking your own thing and expect Spring Boot to figure that out...

**Comment by dagnelies** [comment]
Well, if you have a better way to show me how I should do it, gladly.

First, as pointed out by the first post, the SLF4J error was a misleading due to an error in maven's eclipse plugin, probably. The java logging landscape is a bit of a mess with all this implementations, bridges and facades. I confess I find it quite difficult to make different dependencies work together properly.

At the moment, one of my dependencies expects me to configure the logger with a `log4j.properties` file dynamically computed upon servlet initialization (with the help of the servlet's context). Is there a way to do that other than with `PropertyConfigurator.configure(...);`? And where to place the code ideally?

As for the logging itself, I don't care which lib does it, I just care that the proper `log4j.properties` is applied. I can gladly adjust the dependencies.

**Comment by wilkinsona** [comment]
1.3 is dormant now, and 1.4 doesn't support Log4j. This issue has run its course.
