### ISSUE TITLE
Normal with higher CPU running as JAR vs WAR?

### ISSUE THREAD

**Issue by abaculus** [spring-projects/spring-boot#5029]
Hi

Is it normal to experience that the exact same web application using lots more CPU when run as JAR with Tomcat Embedded than Standalone Tomcat with app as WAR (on the same server)?

**Comment by snicoll** [comment]
How could we tell with the information that you provided so far? Are the VM settings similar for a start?

**Comment by abaculus** [comment]
Default installation of Tomcat, nothing configured for either standalone or
embedded - everything's "by default".
Den 26 jan. 2016 4:48 em skrev "Stéphane Nicoll" <notifications@github.com>:

**Comment by abaculus** [comment]
Same goes for JVM.
Den 26 jan. 2016 4:57 em skrev "Andreas Eriksson" <
andreas.lc.eriksson@gmail.com>:

**Comment by wilkinsona** [comment]
@abaculus Perhaps you can provide a sample project that illustrates the problem and describes how you are measuring the CPU usage?

There are  some differences between running as an executable jar and as a war deployed to Tomcat. For example, in Tomcat's default configuration it unpacks a war file when it's deployed but when running as a jar that doesn't happen and everything is read straight from the jar. Whether or not that has a big effect on performance will depend on what your application's doing.

**Comment by abaculus** [comment]
I'm measuring the CPU using JVisualVM and task manager. Running JMeter 20 threads and a Constant Throughput Timer of 3000 samples/minute.

I just ran a simple `HelloWorldController` (i.e. @RestController) application and experiencing the same thing (though Spring Boot app has smaller memory footprint than Tomcat). In the task manager the Spring Boot app requires ~5% to 10% more CPU than the WAR deployed in Tomcat standalone (same computer) and in JVisualVM a difference in ~3% to 4%.

The real Spring Boot app uses multiple Feign clients, Hystrix commands etc and is pretty thread intensive. Are there any particular characteristics of an application that isn't suitable for Spring Boot with Tomcat embedded due to the reading straight from the jar?

**Comment by wilkinsona** [comment]
Before comparing numbers from the two environments, it's important to check that they're configured identically. We've covered Tomcat version (both 8.0.30) and JVM. There are many other variables, though. For example, have you verified that Tomcat's using the same number of threads in each case? I don't know if embedded Tomcat has the same defaults as a standalone Tomcat configured via server.xml.

> Are there any particular characteristics of an application that isn't suitable for Spring Boot with Tomcat embedded due to the reading straight from the jar?

I'm not aware of anything that would make an application unsuitable for running from a jar. I was thinking of a scenario, entirely hypothetical at this stage, where the application does _a lot_ of file IO and never caches anything. It's possible that such a scenario would be slower when running from a jar. It may well not be though.

**Comment by abaculus** [comment]
I thought the defaults were the same, my bad! I'll go through them and verify!

Aha, that's interesting you got that feeling since our application is very I/O intensive and doesn't cache any files. One use case is serving files from disk (many hundreds/thousands of files).

Sorry for the buzz but I had to ask if it was known to be any difference. I'll dig into default configurations and check differences.

**Comment by abaculus** [comment]
Another major characteristics of the application is lots of new instances, i.e. one request = new instance of a particular bean (@Scope("prototype")).

@wilkinsona I'm curious about your hypothetical reasoning about why an application with lot of file IO and no caches would be "bad" for running JAR w embedded Tomcat?

**Comment by wilkinsona** [comment]
> Is there any easy way of finding out which default you've set for embedded Tomcat except those found in http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties ?

We almost entirely rely on Tomcat's defaults for when it's configured programatically. I'm not sure if Tomcat documents them anywhere.

> Another major characteristics of the application is lots of new instances, i.e. one request = new instance of a particular bean (@Scope("prototype")).

I would be surprised if that made a difference, but never say never.

> I'm curious about your hypothetical reasoning about why an application with lot of file IO and no caches would be "bad" for running JAR w embedded Tomcat?

Assuming that the files you are reading are being read from within the jar file, there may be an extra overhead incurred while they're decompressed versus reading them straight off disk from an unpacked WAR file. However, that overhead could be eliminated by caching or memory-mapping at a level beneath your application.

I think we need some concrete data to make any progress on this. I'll try with a Hello World REST controller. It would also be very useful to have a more real world sample that exhibits the problem.

**Comment by wilkinsona** [comment]
I've tested this with a _very_ simple hello world application:

```
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class Gh5029Application {

	public static void main(String[] args) {
		SpringApplication.run(Gh5029Application.class, args);
	}

	@RestController
	private static final class MyController {

		@RequestMapping("/")
		public String test() {
			return "Hello, world!";
		}

	}
}
```

Using Tomcat 8.0.30 in its default configuration and Spring Boot 1.3.2 in its default configuration I see an executable war consuming 5-10% _less_ CPU than the same war deployed to Tomcat. This was tested on an 8 core rMBP using the same JMeter configuration as described above (20 users and a 3000 req/minute constant throughput).

@abaculus To make any progress on this we're going to need a sample application that demonstrates the performance difference and a detailed description of your test environment.

**Comment by abaculus** [comment]
I'll try to cook something up that acts like the real application (I cannot submit the real application for obvious legal reasons).

Until then you could close this issue and I'll create a new one when I have something to show.

Thanks for all your feedback.

**Comment by GeorgeBarbosa** [comment]
@abaculus Did you open another ticket issue?

**Comment by huanzhang** [comment]
@abaculus do you still have such issue?

**Comment by wilkinsona** [comment]
Reading files from the packaged jar.
