### ISSUE TITLE
Custom CharsetProvider not working in executable JAR

### ISSUE THREAD

**Issue by dstrelec** [spring-projects/spring-boot#5036]
A java.io.UnsupportedEncodingException is thrown when include a JAR file with custom charset implementation classes and a META-INF/services/java.nio.charset.spi.CharsetProvider into Spring Boot fat JAR.

I guess that Spring Boot fat JAR has a problem with loading charset implementations defined in META-INF/services/java.nio.charset.spi.CharsetProvider from included JAR files.

**Comment by wilkinsona** [comment]
@dstrelec We've never considered custom charsets in the executable jar support. The javadoc states that "charset providers are looked up via the current thread's context class loader". Assuming that Boot's `LaunchedURLClassLoader` is the TCCL at the time of the look up (it should be), I'm surprised that this doesn't just work.

Can you please provide a sample that illustrates the problem?

**Comment by dstrelec** [comment]
Thank you for a quick response.

I have digg more deeper into the problem. Found that charset providers are not loaded via TCCL as stated in the JavaDoc but via `ClassLoader.getSystemClassLoader()`.

`java.nio.charset.Charset.forName(String charsetName)` loads service CharsetProviders via `ClassLoader.getSystemClassLoader()`.

So, there is no any problem with Spring Boot class loading. I am closing the issue.

**Comment by philwebb** [comment]
That's a shame, unfortunately I don't think there's much to can do to change the logic there. It might be worth raising a JDK bug since the Javadoc and implementation don't agree with each other.

**Comment by gebhardt** [comment]
Is there any workaround to register a custom Charset in a Spring Boot application when using the fat JAR?

**Comment by wilkinsona** [comment]
Given the use of the system class loader, packaging the provider in the root of the jar would work I think. See #6626 for some details on that approach. Another, more invasive, option would be to add the provider to your installation of the JDK.
