### ISSUE TITLE
Gradle Plugin does not produce TAR archives anymore

### ISSUE THREAD

**Issue by fritzrichter** [spring-projects/spring-boot#5037]
After updating to Spring Boot 1.3.2, the gradle plugin no longer generates the "distribution" folder/tar archives anymore. As I was using the result in the docker image generation phase, I am wondering 

a) How can I reenable the generation of tar archives again?
b) What is the best approach to put the JAR into a docker container, I always thought that extracting the TAR to the docker container and start the spring boot app with the shell script is the fastest way, as nothing has to be unpacked.

**Comment by wilkinsona** [comment]
What version of Spring Boot did you upgrade from?

**Comment by fritzrichter** [comment]
1.2.7

**Comment by wilkinsona** [comment]
This is covered in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#application-plugin). The application plugin produces the tar file. It's no longer added automatically as not everyone needs it. If you want to use it you'll need to apply it.
