### ISSUE TITLE
Add support for configuration the auto-configured cache manager

### ISSUE THREAD

**Issue by gauravlanjekar** [spring-projects/spring-boot#5039]
Hello guys,

I was trying to use the auto configuration for redis cache and found out that there is no support for specifying expiry for a cache. To get around this right now we create a ```RedisCacheManager``` Bean and configure it. But it will be cool to have these features out of the box.

I had a look at the ```RedisCacheConfiguration``` and found out that only the cache-names properties are applied. So I was thinking of maybe introducing a few redis specific properties and then apply these properties so that the ```RedisCacheManager``` can be initialized with these properties

namely 
```
spring.cache.redis.expires.<mycachename>=300
spring.cache.redis.expires.<myothercachename>=3000
spring.cache.redis.simple-cache-prefix=someprefix
```

I was also thinking of introducing a simple implementation of the ```RedisCachePrefix``` which will simply prepend the prefix to the cachename using a delimiter  so something like this

```
public byte[] prefix(String cacheName) {
   return this.serializer.serialize(this.cachePrefix
					.concat(this.delimiter)
					.concat(cacheName)
					.concat(this.delimiter));
		}
```

I will soon create a pull request for the changes mentioned. 

What do you guys think ?

Regards,
Gaurav Lanjekar

**Comment by snicoll** [comment]
Good catch, thanks for the suggestion! I am not a huge fan of using maps for our own configuration. How about some kind of `RedisCacheManagerCustomizer` that you could implement to alter the configuration? Or an object of some sort that would gather that config?

**Comment by snicoll** [comment]
As for the cache prefix, I wonder why the default of the `RedisCacheManager` doesn't do something of the kind. @christophstrobl any idea?

**Comment by gauravlanjekar** [comment]
@snicoll thanks for your feedback. 
so you are thinking something like this
```
public interface JCacheManagerCustomizer {

	/**
	 * Customize the cache manager.
	 * @param cacheManager the {@code javax.cache.CacheManager} to customize
	 */
	void customize(CacheManager cacheManager);

}
```
just to provide the consumer of the library with a hook and he can do what ever he wants to do with it ?

**Comment by snicoll** [comment]
Yes. We could also provide some complex configuration options for JCache and we didn't. 

Maybe we could use a generic `CacheManagerCustomizer` that takes a `o.s.cache.CacheManager` implementation? That way we could update other auto-config if the cache manager implementation supports some customizations.

**Comment by gauravlanjekar** [comment]
So something like what is already done in the ```JCacheCacheConfiguration```  but on a generic level. So all the configurations will  have something similar to 

```
private void customize(CacheManager cacheManager) {
		if (this.cacheManagerCustomizers != null) {
			AnnotationAwareOrderComparator.sort(this.cacheManagerCustomizers);
			for (CacheManagerCustomizer customizer : this.cacheManagerCustomizers) {
				customizer.customize(cacheManager);
			}
		}
}
``` 

I was thinking about the prefix as a property because it seemed pretty specific to redis. just like the spec property for guava. and implementing an customizer bean takes away the fun having the cache autoconfigured just by adding ```@EnableCaching``` and some properties

**Comment by christophstrobl** [comment]
@snicoll the `RedisCacheManager` uses a `RedisCachePrefix` that is defaulted to `DefaultRedisCachePrefix` which does `delimiter != null ? cacheName.concat(delimiter) : cacheName.concat(":")`. Still you're able to set the `delimiter`. Feel free to open an issue to support different prefix strategy.

**Comment by snicoll** [comment]
@gauravlanjekar if you want to go ahead with a PR, please do so. Otherwise I think I have a precise idea of what I would do so let me know. You can join us on Gitter if you want to chat.

**Comment by gauravlanjekar** [comment]
@snicoll I would love to contribute. but I am not sure how to proceed on it.  A generic ```CacheManagerCustomizer``` way or adding properties for prefix ?

**Comment by snicoll** [comment]
I'd like to focus on the customizer first. You can do whatever you want with the customizer anyway (including changing the prefix).

**Comment by snicoll** [comment]
@gauravlanjekar are you working on this?

**Comment by gauravlanjekar** [comment]
@snicoll yes.. Sorry for got to update the ticket.

**Comment by snicoll** [comment]
I've requalified this issue to focus on customizing the cache manager. This should give you all what you need to customize the expiration and the prefix. As for improving the defaults for redis we already have another issue for that.
