### ISSUE TITLE
Cannot modify web security without overwriting auto-configured security.

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#5046]
Despite what [the docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-security.html) say

> To override the access rules without changing any other auto-configured features add a `@Bean` of type `WebSecurityConfigurerAdapter` with `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)`

adding such a bean reverts everything to the spring-security defaults, ignoring any application properties. It does this even if it doesn't even override any `configure` methods.

As a non-exhaustive list: csrf is enabled, sessions are created, basic auth is disabled

**Comment by OrangeDog** [comment]
Likewise, any configurer running after boot's is ignored.
E.g. with `@Order(SecurityProperties.BASIC_AUTH_ORDER + 1)`

**Comment by wilkinsona** [comment]
@OrangeDog I can't reproduce the behaviour that you have described. For example, adding an empty `WebSecurityConfigurerAdapter` bean to `SampleActuatorApplication` has no effect on the security configuration. For example, the Actuator's endpoints are still secured with basic auth. These are the changes that I made:

```diff
diff --git a/spring-boot-samples/spring-boot-sample-actuator/src/main/java/sample/actuator/SampleActuatorApplication.java b/spring-boot-samples/spring-boot-sample-actuator/src/main/java/sample/actuator/SampleActuatorApplication.java
index 5e50ddb..dabf723 100644
--- a/spring-boot-samples/spring-boot-sample-actuator/src/main/java/sample/actuator/SampleActuatorApplication.java
+++ b/spring-boot-samples/spring-boot-sample-actuator/src/main/java/sample/actuator/SampleActuatorApplication.java
@@ -20,6 +20,10 @@ import org.springframework.boot.SpringApplication;
 import org.springframework.boot.actuate.health.Health;
 import org.springframework.boot.actuate.health.HealthIndicator;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.boot.autoconfigure.security.SecurityProperties;
+import org.springframework.context.annotation.Bean;
+import org.springframework.core.annotation.Order;
+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

 @SpringBootApplication
 public class SampleActuatorApplication implements HealthIndicator {
@@ -29,8 +33,18 @@ public class SampleActuatorApplication implements HealthIndicator {
                return Health.up().withDetail("hello", "world").build();
        }

+       @Bean
+       public WebSecurityConfigurerAdapter customSecurity() {
+               return new CustomSecurity();
+       }
+
        public static void main(String[] args) throws Exception {
                SpringApplication.run(SampleActuatorApplication.class, args);
        }

+       @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
+       private static class CustomSecurity extends WebSecurityConfigurerAdapter {
+
+       }
+
 }
```

Can you please provide a small sample that reproduces the behaviour that you have described?

**Comment by OrangeDog** [comment]
I think you won't see it for actuators, as the filter chain for those is separated at a higher level.
I'll see if I can get you an example based on on a default Initializr project.

**Comment by OrangeDog** [comment]
Here's the entire application:

```java
@SpringBootApplication
public class Application {

  public static void main(String[] args) {
    new SpringApplicationBuilder(Application.class).run(args);
  }
    
  @Configuration
  @ConditionalOnProperty(name = "overrideEnabled", havingValue = "true")
  @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
  public static class WebSecurityConfig extends WebSecurityConfigurerAdapter { }

}
```

Project inherits spring-boot-starter-parent 1.3.2.RELEASE and includes spring-boot-starter-security and spring-boot-starter-web.

```bash
$ java -Dsecurity.headers.xss=false -jar application.jar &
[1] 13220
$ curl -is http://localhost:8080 | grep XSS
$ kill 13220
$ java -Dsecurity.headers.xss=false -DoverrideEnabled=true -jar application.jar &
[1] 10276
$ curl -is http://localhost:8080 | grep XSS
X-XSS-Protection: 1; mode=block
```

**Comment by OrangeDog** [comment]
I think [this SO poster](http://stackoverflow.com/q/25674638/476716) is having similar problems.

**Comment by wilkinsona** [comment]
Thanks, but that's a different problem (and is from September '14). In the case on SO, the `WebSecurityConfigurerAdapter` has been used to configure security for various paths. That _will_ switch off any configuration by Boot for those paths as the order on the configurer means its rules take precedence over Boot's defaults.

**Comment by wilkinsona** [comment]
Somewhat to my surprise, Spring Security's default configuration uses an `AnyRequestMatcher`. When you create an empty `WebSecurityConfigurerAdapter` subclass you're saying that you want any request that reaches that adapter's security filter chain to be handled with Spring Security's default configuration. As you've ordered the `WebSecurityConfigurerAdapter` to come before Boot's adapter, the effect is that all of Boot's security configuration is switched off. The Actuator's security is unaffected is it's ordered with higher precedence than `SecurityProperties.ACCESS_OVERRIDE_ORDER`.

It looks like we need to improve the documentation.

**Comment by OrangeDog** [comment]
So how do you actually add to boot's config without a) completely overriding it or b) being completely overridden?

**Comment by wilkinsona** [comment]
Unfortunately, that's not how Spring Security works. Once a `WebSecurityConfigurer` adapter has claimed a particular path (via its configured matchers), it's only that configurer's configuration that will apply to that path. There's no way for one configurer to add to the configuration of another.

If you want to make use of the `security.*` configuration in your own configurer, then you can inject `SecurityProperties` into your configurer, but you'll have to write some code to apply the properties. There are some static methods on `SpringBootWebSecurityConfiguration`, such as `configureHeaders()`, that can help with that.

**Comment by OrangeDog** [comment]
So the documentation in question is a complete fabrication, not just slightly wrong, and `ACCESS_OVERRIDE_ORDER` is useless?

**Comment by wilkinsona** [comment]
I don't think it's complete fabrication, but it is a little unclear. When the documentation says "to override the access rules without changing any other auto-configured features", it's taking about the auto-configuration of Spring Security's servlet filter, etc. The "access rules" are anything that you'd configure via a `WebSecurityConfigurer` and are what you are switching off with your empty `WebSecurityConfigurerAdapter` that has higher precedence as it matches any path.

I don't think that `ACCESS_OVERRIDE_ORDER` is useless. It allows you to provide a `WebSecurityConfigurer` that changes Spring Security's configuration for certain paths. Any path for which you do not provide any configuration will still fall back to Spring Boot's default configuration.

**Comment by philwebb** [comment]
@wilkinsona do you have any documentation updates in mind for this one?

**Comment by wilkinsona** [comment]
I can probably come up with something based on my comments above
