### ISSUE TITLE
Access environment properties from logback.groovy

### ISSUE THREAD

**Issue by gmathias** [spring-projects/spring-boot#5051]
in a nutshell, the equivalent of `springProperty`(in logback-spring.xml) ; because i thought spring could be XML-free ;)

**Comment by philwebb** [comment]
The XML support is currently provided in `LogbackLoggingSystem.configureByResourceUrl` and works by plugging in `SpringBootJoranConfigurator` instead of Logback's default `JoranConfigurator`.

It looks like Groovy support is provided by [GafferConfigurator](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/groovy/ch/qos/logback/classic/gaffer/GafferConfigurator.groovy) and I'm not sure how we'd hook into that.

In an ideal world, how would you like to see environment properties accessed from `logback.groovy`?

**Comment by gmathias** [comment]
I would expect a variable `$environment` or even `$springProperties`

**Comment by philwebb** [comment]
I can't see an easy way to offer that unfortunately. Perhaps someone with more knowledge of Logback will have some suggestions.

**Comment by kiview** [comment]
Would it be possible to access environment variables from `logback.groovy` with vanilla groovy?
Something like this maybe:
```groovy
def env = System.getenv()
def profiles = env["SPRING_PROFILES_ACTIVE"]
```

**Comment by wilkinsona** [comment]
@kiview Those are environment variables from the OS. We're interested in getting properties from Spring's [`Environment`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/Environment.html) abstraction.

**Comment by mohdaliiqbal** [comment]
+1

**Comment by jcvillalta03** [comment]
+1 - same situation as @mohdaliiqbal

**Comment by izhangzhihao** [comment]
+1

**Comment by jcvillalta03** [comment]
As a workaround, I have used a Custom converter and conversion rule to pull out properties in classpath respurce (i.e. application.properties):

In logback.groovy:
``` 
conversionRule('springApplicationName', CustomSpringApplicationNameConverter)

def patternExpression = '%green([%d{YYYY-MM-dd HH:mm:ss.SSS}]) [%t] %highlight(%-5level) %magenta([%springApplicationName]) - %cyan(%logger{36}) -- %msg%n'
```
and then 'patternExpression' used in desired appender

and my custom converter class (in groovy):
```
class CustomSpringApplicationNameConverter extends ClassicConverter {

    @Override
    String convert(ILoggingEvent event) {
        ClassPathResource classPathResource = new ClassPathResource('application.properties')

        Properties applicationProperties = new Properties()
        applicationProperties.load(classPathResource.inputStream)

        String springApplicationName = applicationProperties.getProperty('spring.application.name')
        if (!springApplicationName) {
            System.err.println('Could not find entry for \'spring.application.name\' in \'application.properties\'')
        }

        springApplicationName
    }
```

**Comment by mikelee3** [comment]
+1

**Comment by brp-magnusd** [comment]
+1

**Comment by bygui86** [comment]
+1

**Comment by Ariam-Abraham** [comment]
+1

**Comment by jcvillalta03** [comment]
UPDATE: another workaround for this is to create a filter (wire in spring's filter chain), and inject property into MDC https://logback.qos.ch/manual/mdc.html. I haven't implemented this yet, but will attempt it soon

**Comment by philwebb** [comment]
I'm going to close this issue since there's no obvious way for us to implement this. If anyone has success and wishes to contribute a PR we'll certainly consider it.
