### ISSUE TITLE
Security filters are overlapping

### ISSUE THREAD

**Issue by yrdsf** [spring-projects/spring-boot#5054]
When multiple filters are added to the `HttpSecurity` configure method, they seem to be overlapping because only one works at the time (the csrf filter never works unless I comment out the sso filter).

This is the configure method:

```java
    @Override
     public void configure(HttpSecurity http) throws Exception {
         http
                 .logout().and().antMatcher("/**")
                 .addFilterBefore(ssoFilter(), RequestHeaderAuthenticationFilter.class)
                 .authenticationProvider(preauthAuthProvider())
                 .authorizeRequests()
                 .antMatchers("/index.html", "/home.html", "/", "/login").permitAll()
                 .anyRequest().authenticated().and().csrf()
                 .csrfTokenRepository(csrfTokenRepository()).and()
                 .addFilterAfter(csrfHeaderFilter(), CsrfFilter.class);
     }
```

I've tried to specify the order but the issue still persists:

```java
     @Bean
     public FilterRegistrationBean securityFilterChain(@Qualifier(AbstractSecurityWebApplicationInitializer.DEFAULT_FILTER_NAME) Filter securityFilter) {
         FilterRegistrationBean registration = new FilterRegistrationBean(securityFilter);
         registration.setOrder(Integer.MAX_VALUE - 2);
         registration.setName(AbstractSecurityWebApplicationInitializer.DEFAULT_FILTER_NAME);
         return registration;
     }
     
     @Bean
     public FilterRegistrationBean ssoFilterRegistrationBean() throws Exception {
         FilterRegistrationBean registrationBean = new FilterRegistrationBean();
         registrationBean.setFilter(ssoFilter());
         registrationBean.setOrder(Integer.MAX_VALUE-1);
         return registrationBean;
     }

     @Bean
     public FilterRegistrationBean csrfFilterRegistrationBean() throws Exception {
         FilterRegistrationBean registrationBean = new FilterRegistrationBean();
         registrationBean.setFilter(csrfHeaderFilter());
         registrationBean.setOrder(Integer.MAX_VALUE);
         return registrationBean;
     }
```

I've followed the following thread with no success.

https://github.com/spring-projects/spring-boot/issues/1640
https://github.com/spring-projects/spring-boot/issues/677

Any help will be appreciated.

**Comment by philwebb** [comment]
Do you have the above code available as a project that you could share on GitHub? That would help give us a head start on diagnosing the problem.

/cc @rwinch

**Comment by rwinch** [comment]
You should disable the registration of the Filter if you are including it in Spring Security's `HttpSecurity`. Right now you appear to have a Filter order of:

* CsrfHeaderFilter
* SsoFilter
* SpringSecurityFilterChain
  * ... filters that also include CsrfHeaderFilter and SssoFilter ...

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
