### ISSUE TITLE
@ConditionalOnMissingBean with JndiObjectFactoryBean

### ISSUE THREAD

**Issue by Alvise88** [spring-projects/spring-boot#5055]
In the following particular case , when jndi datasource is present and it is returned as JndiObjectFactoryBean bean , it isn't available for injection. Otherwise if i instantiate a true datasource using JndiObjectFactoryBean all works perfectly.  Sorry if i misunderstood something. Seeing org.springframework.boot.autoconfigure.condition.OnBeanCondition.java i don't find anything about this situation.

[MyDatasourceAutoconfiguration.txt](https://github.com/spring-projects/spring-boot/files/110719/MyDatasourceAutoconfiguration.txt)

**Comment by snicoll** [comment]
I am sorry, I don't understand what you're trying to do. Why are you creating your own datasource auto-configuration exactly? (BTW `AutoConfigureAfter` could only be set on an auto-configuration, not an inner `@Configuration` class).

**Comment by Alvise88** [comment]
Ok I understand what you mean. Yo can close the issue. I verified and now all works perfectly. Sorry for my mistake

**Comment by snicoll** [comment]
No worries, thanks for the feedback.
