### ISSUE TITLE
Hot swapping static content is not working after version switch from 1.2.x to 1.3.x

### ISSUE THREAD

**Issue by richardmz** [spring-projects/spring-boot#5058]
I'm using spring-boot:run command to start my app with following maven configuration:
`			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<jvmArguments>
						-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
					</jvmArguments>
				</configuration>
			</plugin>`
After I switch the version of Spring Boot from 1.2.6 to 1.3.2, the app no longer reload static files unless I rerun 'spring-boot:run'.
My static files are under '../src/main/resources/static' directory.

**Comment by snicoll** [comment]
From the release notes on the wiki. 

>The Spring Boot Maven plugin no longer adds src/main/resources directly to the classpath when using spring-boot:run. If you want live, in-place editing we recommend using Devtools. The addResources property can be set in your pom.xml if you want to restore Spring Boot 1.2. behavior.

**Comment by richardmz** [comment]
Thx

**Comment by richardmz** [comment]
Well, it works fine after I added the addResources property. But when I try to run with the main class or run as Spring Boot Application in IntelliJ Idea, it's still not working. Is additional configurations required?

**Comment by snicoll** [comment]
It never did. That's why we change the behaviour of the plugin. 

You should consider using devtools that is far more superior than this solution.

**Comment by richardmz** [comment]
But as it shows in this [video ](https://www.youtube.com/watch?v=A70NMxV13TI) (DevTools in Spring Boot 1.3), static content hot reload works before the devtools dependency is not commented. Is it because the IDE is Eclipse?

**Comment by richardmz** [comment]
Hi Stéphane, thanks for you replies. I've tried adding the devtools dependency in my pom.xml file, but it still not works :(

**Comment by philwebb** [comment]
@richardmz We need a little more to go on. Are you following the advice in the ["trigger a restart" section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart)?

**Comment by richardmz** [comment]
@philwebb Yes, it works now. Thank you :)

**Comment by philwebb** [comment]
Cool :smile:
