### ISSUE TITLE
Graceful shutdown of Cassandra Cluster object as part of CassandraAutoConfiguration

### ISSUE THREAD

**Issue by LtTempletonPeck** [spring-projects/spring-boot#5063]
`CassandraAutoConfiguration` conditionally creates a `com.datastax.driver.core.Cluster` bean if it is missing from the BeanFactory.

To gracefully shutdown a Cassandra cluster the close method should be called as part of closing the application context, this is not currently being done.

Spring Data Cassandra classes [CassandraCqlClusterFactoryBean](https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-cql/src/main/java/org/springframework/cassandra/config/CassandraCqlClusterFactoryBean.java) and [CassandraCqlSessionFactoryBean](https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-cql/src/main/java/org/springframework/cassandra/config/CassandraCqlSessionFactoryBean.java) handle this by implementing the `DisposableBean` interface and calling close. Here we can just add it to the destroyMethod of the bean annotation for cluster.

**Comment by wilkinsona** [comment]
> To gracefully shutdown a Cassandra cluster the close method should be called as part of closing the application context, this is not currently being done.

As far as I can tell, this is being done. A breakpoint in `Cluster.close()` triggers when the application context is closed when running `CassandraAutoConfigurationTests`. Running the SampleCassandraApplication with debug logging enabled also shows the cluster being closed:

```
2016-02-01 17:25:07.004 DEBUG 62055 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invoking destroy method 'close' on bean with name 'cluster'
```

This is the behaviour that I would expect. If a bean has a `close()` method, it will be called when the application context closes, without having to implement `DisposableBean` or configure a custom destroy method.

If you've observed `close()` not being called on a `Cluster` bean, can you please provide a small sample that illustrates the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
