### ISSUE TITLE
Change our recommendation regarding the use of `spring-boot-starter-parent`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5065]
We are facing many dependencies management problem integrating various Bill of Materials in a project that boils down to the use of a parent having a `dependencyManagement` section. We found a way to reliably fix those issues by having only our boms in the project and in a well-defined order.

Maven does not seem to reliably allow a project to override a dependency via a BOM import if said dependency is already defined by the parent. We are considering moving to a parent-less project on start.spring.io and could only do so if our recommendations are aligned here.

**Comment by deki** [comment]
+1

**Comment by snicoll** [comment]
Nice reminder, I should have closed it as won't fix last week. Can you share a bit more why you'd like to see this?

**Comment by deki** [comment]
I've seen several projects where parent was causing confusion so I would recommend to start with a parent-less project.

**Comment by snicoll** [comment]
Can you share a bit more details?

**Comment by deki** [comment]
The dependency resolution of Maven is not always deterministic and sometimes varies between the versions. I always recommend usage of one Maven version for all developers (prerequisites/ enforcer-plugin rule) so this can be avoided.

Another reason are breaking changes from the parent (e.g. resource.delimiter change). Of course a good developer will read the release notes before updating ;-)

So no killer arguments, just personal preference to avoid confusion.

**Comment by snicoll** [comment]
Sorry but none of these have really something to do with parent/no parent. I am closing this one as we decided to stick with what we have: switching to parent-less removes quite a lof of features (the plugin management typically) and we've also created an issue in Maven to try to fix the issue we're having currently.
