### ISSUE TITLE
Allow placeholders in `spring.datasource.url` property

### ISSUE THREAD

**Issue by Youmoo** [spring-projects/spring-boot#5068]
I use `1.3.2.RELEASE`, the property `spring.datasource.url=jdbc:hsqldb:file:#{systemProperties['user.home']}/db/data` in `application.properties` has an unwanted effect.

**Comment by snicoll** [comment]
From [the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties)

> Contrary to `@Value`, SpEL expressions are not evaluated prior to injecting a value in the relevant `@ConfigurationProperties` bean.

Please consider asking such questions to stackoverflow in the future. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
