### ISSUE TITLE
spring.jackson.serialization.indent_output=true does not work

### ISSUE THREAD

**Issue by karayv** [spring-projects/spring-boot#5069]
Hi,

`spring.jackson.serialization.indent_output` property does not have an impact on `ObjectMapper` instance that lives inside `MappingJackson2HttpMessageConverter`. This property affects `ObjectMapper` context bean, but in my case it's different instance. So no indentation in web response.

Thank you.

**Comment by wilkinsona** [comment]
>  This property affects ObjectMapper context bean, but in my case it's different instance. So no indentation in web response.

That's not the case if you use Boot's default configuration. `JacksonHttpMessageConvertersConfiguration` creates a `MappingJackson2HttpMessageConverter` that uses the auto-configured `ObjectMapper`. `HttpMessageConvertersAutoConfiguration` then configures Spring MVC to use this converter.

Without knowing more about your application, it's impossible to say why you're seeing different configuration. Can you please provide a small sample project that illustrates the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by turing85** [comment]
I found a possible cause for the behaviour. the configuration `spring.jackson.serialization.INDENT_OUTPUT=true` is somehow overwritten as soon as one class within the project ist annotated with `@EnableWebMvc`.

**Comment by bclozel** [comment]
Adding `@EnableWebMvc` to your application signals Spring Boot that you'd like to disable the web auto-configuration and deal with that yourself. So [this works as expected and documented](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-auto-configuration).
