### ISSUE TITLE
Incorrect jms health status when using UserCredentialsConnectionFactoryAdapter

### ISSUE THREAD

**Issue by sesto** [spring-projects/spring-boot#5070]
In our setup we are getting the `QueueConnectionFactory` from the `Context` by JNDI name look up. Then we inject it as the `targetConnectionFactory` into `UserCredentialsConnectionFactoryAdapter`. The adapter provides the user credentials and makes the actual connection.
The problem is that the both are instances of the `ConnectionFactory` and 2  health checks are done for the both instances instead of only 1 for `UserCredentialsConnectionFactoryAdapter`. Obviously, the call for `UserCredentialsConnectionFactoryAdapter` is successful because it is made with the user credentials and the call for `QueueConnectionFactory` returns javax.jms.JMSSecurityException: Inauthentic Client:
`"jms":{"status":"DOWN",
"userCredentialsConnectionFactoryAdapter":{"status":"UP","provider":"SonicMQ/Java"},
"connectionFactory":{"status":"DOWN","error":"javax.jms.JMSSecurityException: Inauthentic Client"}}`
Thus, the final status is "DOWN" instead of "UP".
Is there any solution/workaround for this problem?

**Comment by snicoll** [comment]
You are basically exposing a _faulty_ `ConnectionFactory` in the context so I'd say, no, there is nothing we can do about it. Why is this exposed as a `@Bean` in the first place? You could perfectly do that lookup and only expose the real `ConnectionFactory`.

**Comment by sesto** [comment]
Yes, indeed, our bad. Thank you for pointing it out! Closing the issue.
