### ISSUE TITLE
@AuthenticationPrincipal not working with devtools enabled

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#5071]
See http://stackoverflow.com/questions/35156390/authenticationprincipal-with-spring-boot-not-working for the full details.

I would be most grateful if there could be a workaround since my front-end dev will not be very happy if he is going to have to restart manually from now on.

**Comment by philwebb** [comment]
We've hit a few corner cases like this before where classes are accidentally loaded using the wrong classloader. My guess is that we need to update Spring Security to ensure that `principal` is created using the `RestartClassLoader`.

Do you have a small sample application that you could share on GitHub that demonstrates the issue? It looks like you've already created something for the stack-overflow post, so if we can just run that it will help us a lot.

**Comment by rwinch** [comment]
@philwebb I'm guessing you are right it is the classloading issue that will be resolved once RestartClassloader is used for SecurityContext, Authentication, UserDetails, User, etc.

**Comment by philwebb** [comment]
@rwinch Is there another issue open already for that?

**Comment by wimdeblauwe** [comment]
@philwebb I tried to create a small sample, but it seems I don't have it there. I do have it in my actual application, but I cannot share that unfortunately.

**Comment by wilkinsona** [comment]
I can't reproduce this in a simple project either.

@wimdeblauwe How is your actual application structured? Specifically, are `User` and `CustomUserDetails` in the same project? If they're in separate projects, are both projects open in your IDE, or is one just a jar file on the classpath of the other?

**Comment by wimdeblauwe** [comment]
Both are in the same project. It is a multi-module Maven project where one module contains all the Java/Spring Boot stuff and the other module contains the AngularJS front-end. 

+ myapp
++ myapp-server
++ myapp-admin-client

I do have this in my `application.properties`, but I don't think it matters:

    spring.resources.static-locations=classpath:/static/,file:myapp-admin-client/src/main/,file:myapp-admin-client/bower_components/

    spring.devtools.restart.additional-paths=myapp-admin-client/src/main/,myapp-admin-client/bower_components/
    spring.devtools.restart.additional-exclude=**/*.js,**/*.css

I am not using Spring Boot as parent pom, I use the dependency management (in the pom of `myapp-server`):

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
        </dependencyManagement>

**Comment by philwebb** [comment]
@wimdeblauwe It's going to be quite hard to solve this without being able to reproduce it locally :cry:

You might want to try debugging your application to see where the `principal` object is created. It's also worth comparing the classloaders that created the objects in sample you have that works. Specifically, in your stackoverflow post you say:

> The classloader of parameter.getParameterType() is an instance of RestartClassloader, while principal.getClass() has a classloader that is an instance of Launcher$AppClassLoader.

I assume this isn't the case with the working sample? Are both objects there created with the `RestartClassloader`?

**Comment by rwinch** [comment]
@philwebb Not as far as I know. There use to be an issue for Spring Session that would cause this. However, @wilkinsona fixed it

**Comment by wimdeblauwe** [comment]
@philwebb I can confirm that in the small sample I created both objects are created with the `RestartClassLoader`

**Comment by wimdeblauwe** [comment]
I debugged in `DaoAuthenticationProvider`. The `retrieveUser` method calls into my `UserDetailsService`. The object returned is an instance of `CustomUserDetails` and the classloader of that class is the `RestartClassLoader`. So that looks good at that point.

A bit further, my principal gets wrapped in a `UsernamePasswordAuthenticationToken` (in the `createSuccessAuthentication` method of `AbstractUserDetailsAuthenticationProvider`), The classloader of the `UsernamePasswordAuthenticationToken` is the `Launcher$AppClassloader`.

Later, in the `OAuth2AuthenticationManager`, the `OAuth2Authentication` object is loaded via `tokenServices.loadAuthentication(token)`. The return type contains my principal object (`CustomUserDetails`), but this time, the classloader is the wrong `Launcher$AppClassloader`.  So it seems it goes wrong at that point.

Hopefully, this information helps you find the issue?

**Comment by wimdeblauwe** [comment]
Good news. I have found out that the issue does NOT happen if you use an `InMemoryTokenStore`. It does happen with a `JDBCTokenStore`. Based on this, I managed to create a sample boot project that has the issue. See https://github.com/wimdeblauwe/spring-boot-issue-5071

**Comment by wilkinsona** [comment]
@wimdeblauwe Thank you for digging into this. It's hugely helpful. I've reproduced the problem with your sample application.

**Comment by wilkinsona** [comment]
The root cause of the problem is in Spring Security OAuth2's `SerializationUtils`. It needs to be updated to use Spring Framework's `ConfigurableObjectInputStream` and use the thread context class loader during deserialisation. 

@wimdeblauwe You can work around this problem by declaring the following custom `JdbcTokenStore` in your app:

```
@Bean
public TokenStore tokenStore() {
	return new JdbcTokenStore(dataSource) {
		@Override
		protected OAuth2Authentication deserializeAuthentication(byte[] authentication) {
			ObjectInputStream input = null;
			try {
				input = new ConfigurableObjectInputStream(
						new ByteArrayInputStream(authentication),
						Thread.currentThread().getContextClassLoader());
				return (OAuth2Authentication)input.readObject();
			} catch (Exception ex) {
				throw new IllegalArgumentException(ex);
			} finally {
				if (input != null) {
					try {
						input.close();
					} catch (IOException ex) {
						// Continue
					}
				}
			}
		}
	};
}
```

**Comment by wimdeblauwe** [comment]
@wilkinsona I can confirm that the custom JdbcTokenStore fixes the problem in my actual application as well.

**Comment by wilkinsona** [comment]
@wimdeblauwe Excellent. Thanks for trying it. I've submitted a PR to Spring Security OAuth that fixes the problem properly.

**Comment by philwebb** [comment]
Closing here as we should pick the Spring Security OAuth fix up in due course.
