### ISSUE TITLE
Logging-related System properties are not set

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5073]
The [documentation claims](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-log-levels) that a number of system properties are set based on properties in the environment. In reality, that's not the case. This method:

```java
@PostConstruct
public void test() {
	System.out.println(System.getProperty("CONSOLE_LOG_PATTERN"));
	System.out.println(System.getProperty("FILE_LOG_PATTERN"));
	System.out.println(System.getProperty("LOG_EXCEPTION_CONVERSION_WORD"));
	System.out.println(System.getProperty("LOG_FILE"));
	System.out.println(System.getProperty("LOG_LEVEL_PATTERN"));
	System.out.println(System.getProperty("LOG_PATH"));
	System.out.println(System.getProperty("PID"));
}
```

Produces this output:

```
null
null
%wEx
null
null
null
72125
```

This causes problem when trying to reuse Boot's XML-based Logback configuration (by including `base.xml`, for example) as properties like `logging.pattern.console` have no effect.

**Comment by shakuzen** [comment]
I ran into this issue and it was unexpected for me as well. I meant to report it but have been busy. In particular, I wanted to use `logging.pattern.level` (for Spring Cloud Sleuth integration) with our custom `logback.xml` that includes `defaults.xml`.

**Comment by wilkinsona** [comment]
The current behaviour across the latest release in the 1.1.x, 1.2.x, and 1.3.x lines is:

| Property | 1.1.10 | 1.2.8 | 1.3.2
|------------|---------|--------|--------|
| `CONSOLE_LOG_PATTERN` | N/A | N/A | No |
| `FILE_LOG_PATTERN` | N/A | N/A | No |
| `LOG_EXCEPTION_CONVERSION_WORD` | N/A | N/A | Yes |
| `LOG_FILE` | Yes | Yes<sup>1</sup> | Yes<sup>1</sup> |
| `LOG_LEVEL_PATTERN` | N/A | N/A | No |
| `LOG_PATH` | Yes | Yes<sup>1</sup> | Yes<sup>1</sup>
| `PID` | Yes | Yes | Yes |

<sup>1</sup>Only if `logging.config` is set

The three `*_PATTERN` properties were introduced between 1.3.0.M5 and 1.3.0.RC1 in [this commit](https://github.com/spring-projects/spring-boot/commit/cad266652246ae92e57f48539e9ddf7f8d890313). They have never been exposed as system properties as far as I can tell.

The change to only exposing `LOG_FILE` and `LOG_PATH` system properties when `logging.config` has been specified seems like a step backwards. You could use one of those properties in a logback.xml that's discovered in its default location.
