### ISSUE TITLE
Consider removing DriverClassNameProvider

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#5076]
```DriverClassNameProvider``` apparently isn't used anywhere in the project since ```1.2.0```.

If you decide to keep this class, it should be refactored to avoid duplication since it contains hardcoded driver class names, similar to ```DatabaseDriver``` enum.

**Comment by snicoll** [comment]
And there are drivers out there that haven't move to `DatabaseDriver` for some reason.

**Comment by snicoll** [comment]
See also #2843
