### ISSUE TITLE
${local.server.port} not resolved in application.properties

### ISSUE THREAD

**Issue by hohwille** [spring-projects/spring-boot#5077]
I can set this in ```src/test/resources/config/application.properties``` to get a free random port:
```
server.port=0
```

Also I can get the actual random port injected into my test case like this:
```
@Value("${local.server.port}")
private int port;
```

However, I need the port in an URL defined in ```src/test/resources/config/application.properties```:
```
service.url=http://localhost:${local.server.port}/services/rest/myservice
```
When this property is bound to my @Configuration class, the variable ${local.server.port} does not get resolved by spring.

IMHO this is a bug.

**Comment by snicoll** [comment]
No it's not. The actual (free/random) port is determined by the servlet container(when the container actually starts. All the configuration should be bound at this point (as it should). You just can't refer to that value in a configuration since it is determined at runtime.

See also [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-discover-the-http-port-at-runtime)

**Comment by hohwille** [comment]
```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private int foo.MyConfigurationProperties.port; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'local.server.port' in string value "${local.server.port}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
```

So you are basically saying that spring boot does not want to solve such problem?
There is no solution then except rewriting the entire code and get rid of @Configuration then?
My Test-Case is using a component (spring bean) that itself has a configuration inject to dynamically create a service proxy. Then I can not test this with spring test?

**Comment by wilkinsona** [comment]
> So you are basically saying that spring boot does not want to solve such problem?

I can't see how we can solve this problem in the way that you are suggesting. The value of `local.server.port` isn't known when placeholder is being resolved.

> There is no solution then except rewriting the entire code and get rid of `@Configuration` then?

There are other solutions. For example, you could add some test-specific logic to update the URL with the port once it's known.

**Comment by hohwille** [comment]
too bad. Thanks for the quick responses. I will dig my way through the components to tweak this from my test.
