### ISSUE TITLE
Auto-configure a MessageConverter for Rabbit if one exists in the context

### ISSUE THREAD

**Issue by msalman86** [spring-projects/spring-boot#5088]
Hey there,

This is a feature request. Could you please add a property i.e., `spring.rabbitmq.message-converter` and use it to set message converter on rabbit template and listener when auto configuring them. Thank you

**Comment by wilkinsona** [comment]
I'm not keen on using a property to configure a `MessageConverter` as it's not clear how the converter would be created. For example, what would happen if you want to use a `ContentTypeDelegatingMessageConverter`? How would you set its default converter or its delegates?

If you want to create a `RabbitTemplate` with a specific converter, you should declare your own `@Bean` for it. You can still use the auto-configured `ConnectionFactory`:

```java
@Bean
public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
	RabbitTemplate template = new RabbitTemplate(connectionFactory);
	template.setMessageConverter(…);
	return template;
}
```

It's not so easy to configure a converter on the listener container as creating it isn't as straightforward. You could post process the `SimpleRabbitListenerContainerFactory` bean, but that's not a very elegant solution. Perhaps there's something we can do to make it easier to customize. /cc @snicoll

**Comment by snicoll** [comment]
There is the same request for the JMS support and I was waiting for `@ConditionalOnSingleCandidate` to actually land in our code base first. The deal is that if there is only one `MessageConverter` we automatically associate it to the component _we_ create.

How does that sound?

**Comment by snicoll** [comment]
See #4284

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
I'll take that as a yes. I don't like the idea of providing a configuration entry for that anyway.

**Comment by msalman86** [comment]
@snicoll when you say a `MessageConverter` is available, I'm assuming you mean `MessageConverter` bean is available. I supposes it's a good work around. Thanks

**Comment by snicoll** [comment]
Yes. I don't really see what you mean by workaround though.

**Comment by msalman86** [comment]
I was alluding towards the difference between configuring with a property vs creating a `MessageConverter` bean.

**Comment by snicoll** [comment]
In that case, I think configuring via a property is a bad idea (programming by properties). Note that as of `1.3.3` there is a new service you can use to quickly create your own container factory, see `RabbitListenerContainerFactoryConfigurer`

**Comment by msalman86** [comment]
When you say configuring/programming via property is a bad idea, are you referring to this particular case or is that your take in general? 

Thanks for pointing out `RabbitListenerContainerFactoryConfigurer` - it was helpful. 

While configuring my own `SimpleRabbitListenerContainerFactory`, I noticed that `RabbitAnnotationDrivenConfiguration` is checking, whether this bean is missing, by name. Don't you think it would be better to use class reference (`SimpleRabbitListenerContainerFactory.class`) instead?

**Comment by snicoll** [comment]
Let's not start a chat here please, there's gitter for that. The check on name is on purpose as we are configuring the _default_ factory and that's [how the implementation looks it up](http://docs.spring.io/spring-amqp/docs/1.5.4.RELEASE/reference/htmlsingle/#async-annotation-driven-enable) .
