### ISSUE TITLE
Modify WebRequestTraceFilter to only read request parameters when they're included in the trace 

### ISSUE THREAD

**Issue by matthews614** [spring-projects/spring-boot#5089]
I have a servlet that reads the HTTP POST request entity using _HttpServletRequest.getInputStream()_.  In Spring Boot 1.2.x, this works fine.  When I try to upgrade to Spring Boot 1.3.x, the _InputStream_ is already empty. I narrowed the cause down to changes made to _WebRequestTraceFilter_ in Spring Boot 1.3.  _WebRequestTraceFilter_ calls _HttpServletRequest.getParameterMap()_ which causes the request entity to be unavailable using the _HttpServletRequest.getInputStream()_ method.

Spring Boot allows configuration of what properties are recorded using the _management.trace.include_ property. By default, request parameters are excluded.  However, the _WebRequestTraceFilter_ always calls _HttpServletRequest.getParameterMap()_ even if request parameters are not included in the trace. 

I think a workaround is to only call _HttpServletRequest.getParameterMap()_ **if** the filter is configured to include request parameters.  For example, in _WebRequestTraceFilter_, replace:

`	
add(trace, Include.PARAMETERS, "parameters", request.getParameterMap());
`	
with:

```
if(isIncluded(TraceProperties.Include.PARAMETERS)) {
    trace.put("parameters", request.getParameterMap());
}	
```

A workaround is to add a filter that executes before _WebRequestTraceFilter_ and caches the HTTP POST request entity.  My servlet than reads this cached value.

**Comment by wilkinsona** [comment]
@matthews614 Thanks for the detailed analysis
