### ISSUE TITLE
missing org/springframework/asm/ClassVisitor while running mvn package

### ISSUE THREAD

**Issue by nmorado** [spring-projects/spring-boot#5090]
I am using sample app of spring-boot-start-websocket 1.3.2.RELEASE.

it compiles fine in mac OS X but running into windows 7 is running into the below.

this is the windows machine i am running into this problem:

![screen shot 2016-02-04 at 9 52 11 pm](https://cloud.githubusercontent.com/assets/1273622/12836751/97ab0d78-cb89-11e5-895c-b43d7d4bc841.png)

![screen shot 2016-02-04 at 9 50 04 pm](https://cloud.githubusercontent.com/assets/1273622/12836729/5d5e1cfa-cb89-11e5-9ade-5d391fa4a8ff.png)

content of pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.nm</groupId>
    <artifactId>myapp</artifactId>
    <version>0.0.1.0-SNAPSHOT</version>
    <name>Application</name>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.2.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-messaging</artifactId>
        </dependency>
    </dependencies>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by snicoll** [comment]
I'd say your local maven repository is corrupted. Can you remove `%HOME%/.m2/repository/org/springframework` and try again?

**Comment by nmorado** [comment]
I did several states times all to naught.

**Comment by wilkinsona** [comment]
@nmorado I would guess that the jar's getting corrupted again. Perhaps you're behind a proxy that's cached a corrupted copy of the jar? The class in question should be loaded from `spring-core`. Have you verified that the jar in your Maven cache is valid? What does `jar -tvf` output for it?

**Comment by nmorado** [comment]
some jars were out of sync - corrected and problem fixed.

thanks
