### ISSUE TITLE
Improve documentation for ApplicationContextInitializer registration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5091]
It wasn't obvious when I searched for that interface in the doc. See http://stackoverflow.com/questions/35217354/how-to-add-custom-applicationcontextinitializer-to-a-spring-boot-application/35217768#35217768

**Comment by snicoll** [comment]
This is already documented [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-environment-or-application-context)

**Comment by wimdeblauwe** [comment]
Correct link is now https://docs.spring.io/spring-boot/how-to/application.html#howto.application.customize-the-environment-or-application-context I believe.
