### ISSUE TITLE
datasource connection pool size autoconfiguration bug

### ISSUE THREAD

**Issue by fkowal** [spring-projects/spring-boot#5097]
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

according to the above url 
```
spring.datasource.max-active= # For instance 100
spring.datasource.max-idle= # For instance 8
spring.datasource.min-idle=8
```
are available

in fact there are no such properties in DataSourceProperties
and the poolsize are in fact set to default of a chosen provider.

it would be nice if the pool sizes would be configurable
or the inexistent properties should be removed from 
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

Datasource auto configuration makes no sense if one cannot choose the poolsize.

**Comment by shakuzen** [comment]
I believe you are describing the same thing covered by issue #2183, which will be fixed in 1.4 M1 (available in latest 1.4 SNAPSHOTS now) and is described in the [1.4.0 M1 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M1-Release-Notes#datasource-binding).

The properties you mentioned are available in 1.3.x if your DBCP implementation supports them. Which DBCP are you using?

**Comment by fkowal** [comment]
I am using hikaricp these properties are supported but they are not in datasourceproperties so i dont see how they can be passed to the datasource

**Comment by wilkinsona** [comment]
@fkowal Spring Boot maps the properties straight onto the `DataSource` implementation. This is done via the `@ConfigurationProperties` annotation on the `DataSource` bean:

```java
@Bean
@ConfigurationProperties(prefix = DataSourceProperties.PREFIX)
public DataSource dataSource() {
    // …
}
```

You need to use the properties that match the connection pool that you're using. Hikari's property for configuration the minimum number of idle connections is called `minimumIdle` so the property should be:

```
spring.datasource.minimum-idle: 8
```

**Comment by fkowal** [comment]
SWEET!!!

that's Awesome!
thanks!
