### ISSUE TITLE
Add Jersey load-on-startup configuration property

### ISSUE THREAD

**Issue by psamsotha** [spring-projects/spring-boot#5100]
I would like to be able to set the `load-on-startup` value for the Jersey sevlet, without the need to override the `ServletRegistrationBean`. A simple configuration property should do the trick. It's a pretty simple fix (add one property in the `JerseyProperties`, and `setLoadOnStartup` in the Jersey `ServletRegisteationBean` with that property). I could add a PR, unless there is already some other way I don't know about to set the `load-on-startup` (without having to override the `ServletRegistrationBean`).

**Comment by philwebb** [comment]
Is there any specific reason that you need to set `loadOnStart`? I'm not too keen to add a new property if there's not a strong reason why many developers would want to use it.

**Comment by psamsotha** [comment]
The Jersey runtime doesn't start on application load until the first request. Setting the load on startup to something other than a negative number allows the application to load. If you make the default value for the property -1, then if the property is not set, than it will behave as it normally would, i.e. no affect, so not setting the property would just be business as usual.

The main thing that I was working on that caused me to raise this issue, what the use of Jersey application even listeners, where all the listeners would not fire up unless the application was loaded, and this doesn't happen until the first request, which is a burden. Just aside from the listeners just the fact the application doesn't load until the first request is a burden.

You can see an example of what I mean [in this project](https://github.com/psamsotha/jersey-boot-loadonstartup)
