### ISSUE TITLE
Upgrade to Hazelcast 3.7.1

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#5101]
```3.5.5``` and ```3.6.0``` were released recently.

I guess ```1.3.x``` branch will get the ```3.5.5``` update and ```master``` should start building against the ```3.6.0``` release.

However, since Boot should get [Hibernate 5 support](https://github.com/spring-projects/spring-boot/issues/2763) from ```1.4.0.M2``` it's worth noting that Hazelcast 3.6 still does not have support for Hibernate 5 which is an important use case for many users. Hazelcast 3.7 will have this support (see hazelcast/hazelcast#7021) and it's scheduled for [Feb 29th](https://github.com/hazelcast/hazelcast/milestones) ATM which should be OK considering the ```1.4.0``` release schedule.

**Comment by wilkinsona** [comment]
Thanks, @vpavic. I've modified this issue a little bit so that it's specifically for the upgrade to 3.7. I've scheduled it for inclusion in 1.4.0.M2.

1.3.x will upgrade to the latest 3.5.x as part of the the dependency upgrades that I do prior to each release.

**Comment by vpavic** [comment]
Hazelcast 3.7 was pushed back to [May 2nd](https://github.com/hazelcast/hazelcast/milestones).

**Comment by snicoll** [comment]
I guess it will be pushed back again considering there are still 200-ish issues open.

**Comment by vpavic** [comment]
Their milestones page is outdated, it also shows 3.6.1 and 3.6.2 releases as still open.
I've asked on their gitter what's the place to track releases.

**Comment by vpavic** [comment]
Pushed back to [June 19th](https://github.com/hazelcast/hazelcast/milestones).

**Comment by vpavic** [comment]
Early access release ```3.7-EA``` has been released:
http://docs.hazelcast.org/docs/release-notes/

However, I do not see the Hibernate modules available ATM.

**Comment by vpavic** [comment]
Some useful info from @jerrinot is available on [Hazelcast gitter](https://gitter.im/hazelcast/hazelcast?at=57599fcb1cf76dd645359ee4), apparently there is now a separate repo with an independent lifecycle for [Hibernate support](https://github.com/hazelcast/hazelcast-hibernate).

**Comment by vpavic** [comment]
[```com.hazelcast:hazelcast-hibernate5:1.0```](https://search.maven.org/#artifactdetails%7Ccom.hazelcast%7Chazelcast-hibernate5%7C1.0%7Cjar) module was released recently.

**Comment by snicoll** [comment]
@vpavic we can't update to the early access unfortunately. I've asked @noctarius if we can expect 3.7 final for 1.4

**Comment by vpavic** [comment]
@snicoll I'm aware that 3rd party dependencies are not updated to pre-release versions, I was just posting relevant info on the development around this issue since it might be useful for people who track this.

**Comment by vpavic** [comment]
This could be targeted at 1.5 but things are not so straightforward.

Dependency management for new `hazelcast-hibernate5` requires new version property, but news with Hazelcast 3.7 is an independent release cycle for all Hibernate integration modules, meaning `hazelcast-hibernate4` (which Boot provides dependency management for) is no longer in sync with Hazelcast core version.

I don't know what are the plans for Hibernate 4.x support in Boot 1.5+, but something [like this](https://github.com/vpavic/spring-boot/commit/727cebe799759a8f21fcd35b9719b2e15dc0383b#diff-083b496f7d7090ebebfb261636fbe139) will be necessary to provide dependency management for Hazelcast's Hibernate modules.

**Comment by snicoll** [comment]
Closing in favour of the PR #7023
