### ISSUE TITLE
command line args are not sent to parent SpringApplicationBuilder.configureAsChildIfNecessary in 1.3.2

### ISSUE THREAD

**Issue by shalom938** [spring-projects/spring-boot#5103]
Hi
trying to upgrade from spring boot 1.2.6 to 1.3.2 our configuration files are not loaded. we change the name of properties files with spring.config.name as command line arg. 
we are building a parent/child context hierarchy in our boot application and we rely heavily on that. our overall design is a bit different because we are actually migrating a legacy app to spring boot and there where many issues to consider, parent/child hierarchy solved a few issues for us.

the code that builds the boot application looks like that, many details removed for clarity:

`

         public ConfigurableApplicationContext setupSpring(String[] args){
                SpringApplicationBuilder application = new SpringApplicationBuilder();
                ConfigurableApplicationContext applicationContext = application
                .sources(DataSourceConfig.class)
                .web(false)

                .child(FrameworkConfig.class)
                .bannerMode(Banner.Mode.OFF)
                .web(false)

                .child(TrcConfiguration.class)
                .bannerMode(Banner.Mode.OFF)
                .run(args);
        return applicationContext;
    }
`

our command line args contain --spring.config.name=someName

before 1.3.2 SpringApplicationBuilder.run used to call the parent SpringApplicationBuilder like:
`initializers(new ParentContextApplicationContextInitializer(
					this.parent.run(args)));`

in 1.3.2 there is the new method configureAsChildIfNecessary that calls the parent but without passing the command line args. as a result, while initializing the parent contexts, the args are not added to the environment and ConfigFileApplicationListener.Loader#getSearchNames returns the default 'application' and our properties files are not loaded.

I opened an issue because couldn't find any clue about that. and it feels like sending args to configureAsChildIfNecessary and then to the parent  SpringApplicationBuilder.run will bring back the old behavior.
I actually compiled spring-boot with this fix and it seems to solve my issue.

Thank you

**Comment by wilkinsona** [comment]
This is a regression introduced in https://github.com/spring-projects/spring-boot/commit/ee3d4b34a0b232cb5f72f900462594ad9c70998a
