### ISSUE TITLE
Setting Actuator Endpoint Paths doesn't seem to work

### ISSUE THREAD

**Issue by lewisheadden** [spring-projects/spring-boot#5105]
It looks like setting `endpoints.health.path` for MVC Endpoints does not work in Spring Boot 1.3.2. 

As such it seems like Section 46.2 in the documentation - https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html - is misleading because it states that

`For example, to change the location of the /health endpoint to /ping/me you can set endpoints.health.path=/ping/me.`

In `MvcEndpoints` there seems to be some code to set paths for endpoints based on the `endpoints.[id].path` configuration but for `health`, `env`, and `metrics` these all seem to be skipped because they are in the `customTypes` array and are therefore not generic endpoints (as determined by `isGenericEndpoint`).

Equally setting the path on things not in the `customTypes` array causes the binder to throw an error on startup trying to bind `endpoints.[id].path` to the bean. 

Am I misunderstanding how this should work or where configuration should be occurring?

**Comment by wilkinsona** [comment]
See gh-2790 and the fix for it made in https://github.com/spring-projects/spring-boot/commit/972557851a4b2634a61d37d5d2586b833953e488.

**Comment by wilkinsona** [comment]
It doesn't work for many of the generic endpoints either. For example, trying to set the env endpoint's path fails as `EnvironmentEndpoint` uses `@ConfigurationProperties(prefix = "endpoints.env", ignoreUnknownFields = false)` and it doesn't have a setter for `path` as that's on `EnvironmentMvcEndpoint`.
