### ISSUE TITLE
Healthcheck fails with Elasticsearch 2.2.0

### ISSUE THREAD

**Issue by jloisel** [spring-projects/spring-boot#5106]
In Elasticsearch 2.2.0, ClusterHealthStatus has been moved to package org.elasticsearch.cluster.health which breaks the health check indicator:

> java.lang.ClassNotFoundException: org.elasticsearch.action.admin.cluster.health.ClusterHealthStatus
2/8/2016 6:15:05 PM	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
2/8/2016 6:15:05 PM	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
2/8/2016 6:15:05 PM	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178) ~[app.jar!/:na]
2/8/2016 6:15:05 PM	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[app.jar!/:na]
2/8/2016 6:15:05 PM	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
2/8/2016 6:15:05 PM	at org.springframework.boot.actuate.health.ElasticsearchHealthIndicator$1.<clinit>(ElasticsearchHealthIndicator.java:54) ~[spring-boot-actuator-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]

A simple upgrade should do the trick :+1:

**Comment by wilkinsona** [comment]
Spring Boot doesn't support Elasticsearch 2.x at the moment. We'll upgrade to 2.x as and when we're using a version of Spring Data Elasticsearch which supports 2.x. In the meantime, you health indicator can be disabled by setting `management.health.elasticsearch.enabled=false`.
