### ISSUE TITLE
Allow Optional binding of @ConfigurationProperties

### ISSUE THREAD

**Issue by enric-sinh** [spring-projects/spring-boot#5110]
It would be useful to be able to bind properties wrapped in Optional, like this:
```java
@ConfigurationProperties(prefix = "hello")
public class SomeProperties {

  private Optional<String> anOptionalString;

  private Optional<File> someOptionalFile;

  // getters & setters

}
```
I think that right now the property value remains `null` when it doesn't exist in the environment, which requires the developer to remember it is a nullable property (and to check for it).

In order to avoid this issue, one can specify a default value (e.g. `private String fruit = "banana"`).

However, there are cases where it doesn't make sense to have a default, and with some types it feels wierd (e.g. default value for a `File` property).

**Comment by snicoll** [comment]
That part of the binding is in the core framework and I am surprised it doesn't work already. You could initialize your own field with `Optional.EMPTY`. What's wrong with that?

**Comment by enric-sinh** [comment]
Thank you for your reply Stéphane. I tested this again and now I feel ashamed: it does work when the property exists.

**However**, when the property does not exist the field remains `null` instead of an empty `Optional`.

Of course you are right in that the field could be manually initialized with `Optional.EMPTY`, but I think it might be an improvement if it was handled by the framework as a proper Optional, in a similar manner than with request parameters in Spring MVC, e.g:
```java
@RequestMapping("/hello")
public @ResponseBody String sayHello( @RequestParam Optional<String> name ) {
  return "Hello " + name.orElse("world");
}
```
In the example, name will never be null: when the name parameter is not present, the passed in variable is an empty `Optional`.

**Comment by snicoll** [comment]
That makes sense. I've created [SPR-13933](https://jira.spring.io/browse/SPR-13933) for you. Please watch it for updates. Thanks!
