### ISSUE TITLE
Make it easier to bind alias from the environment

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5113]
Even when #3783 is resolved, it feels that we could make the following scenario easier.

Assume you need a reference to some service so you create a property of your own `app.foo.url` or something. That service is also supported by your favorite cloud provider and it injects a `vcap.services.foo.credentials.uri` property with the value to use for that particular app. You only want to deal with `app.foo.url` and ideally you'd like the cloud provided value to override any value provided by configuration (And I imagine for other cases you'd want the reverse).

To achieve this behaviour today, you may annotate the field with `@Value` and the name of the "cloud" property. Which means you need to hardcode the name of the service somehow. 

It would be nice if we could extend the concept of alias so that a particular property may be overridden with an arbitrary number of keys. 

Added bonus: sometimes the key provided by the cloud provider has a different structure so you may want a callback to extract the bits that you need. 

See [this example](https://github.com/snicoll/initializr/blob/gh-185/initializr/src/main/groovy/io/spring/initializr/config/CloudfoundryEnvironmentPostProcessor.groovy) for a concrete use case.

**Comment by wilkinsona** [comment]
Sounds like there's some overlap with `@ConfigurationPropertyValue` that's proposed for 2.0

**Comment by philwebb** [comment]
I kind of like the existing solution of sticking `app.foo.url=${vcap.services.foo.credentials.uri}` in your `application.properties` for dealing with this.

**Comment by snicoll** [comment]
That doesn't help if you want to set the value for local dev and expect the cloud stuff to override it.

**Comment by snicoll** [comment]
On a second look this is mostly a duplicate of #7986
