### ISSUE TITLE
Don't export an MBean for HikariDataSource when it has already exported itself

### ISSUE THREAD

**Issue by matsumana** [spring-projects/spring-boot#5114]
I want to monitor HikariCP's connection pool.
But only HikariDataSource is registered.

I think that it should entrust HikariCP.

FYI
https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.4.3/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L219-L246

<br>

Can I send Pull Request?

https://github.com/matsumana/spring-boot/commit/1c218a225f1748e4c310c698b983f386151bc48e

**Comment by wilkinsona** [comment]
A pull request would be most welcome, but can we please take a step back and make sure that we've identified the problem and the best way to fix it first of all?

Am I right in thinking that you've configured Hikari to register its MBeans and that you're then seeing a failure as an attempt is made to register an MBean that's already been registered?

Assuming that the above is correct, we should probably address it in a similar way to how `JndiDataSourceAutoConfiguration` does it. It calls `mbeanExporter.addExcludedBean` so that the exporter doesn't try to export the `DataSource`. Spring Boot's configuration for Hikari could do something similar if it detects that Hikar's MBean registration has been enabled.

**Comment by matsumana** [comment]
> Am I right in thinking that you've configured Hikari to register its MBeans and that you're then seeing a failure as an attempt is made to register an MBean that's already been registered?

Yes.
I will call `hikariDataSource.setRegisterMbeans(true);` MBean registration fail.

First, Spring Boot register HikariDataSource.
Next, HikariCP register HikariDataSource. However, it fails.

> Assuming that the above is correct, we should probably address it in a similar way to how JndiDataSourceAutoConfiguration does it. It calls mbeanExporter.addExcludedBean so that the exporter doesn't try to export the DataSource. Spring Boot's configuration for Hikari could do something similar if it detects that Hikar's MBean registration has been enabled.

Thank you for Information.
I will read `JndiDataSourceAutoConfiguration` source.

**Comment by matsumana** [comment]
I read `JndiDataSourceAutoConfiguration` source.

My opinions are

1. Should check the dataSource is MBean
2. `hikariDataSource.setRegisterMbeans` and `hikariDataSource.setPoolName` call only when `hikariDataSource.isRegisterMbeans == false`

https://github.com/matsumana/spring-boot/commit/254f50bdffd70f155e915d49087643885dd775ff

How does that look?

**Comment by wilkinsona** [comment]
> How does that look?

That's not really what I had in mind. There shouldn't be a custom MBean exporter just because Hikari is on the classpath. Instead, the existing MBean exporter needs to be told not to export the Hikari MBean by calling `addExcludedBean`.

**Comment by matsumana** [comment]
Thanks for your reply.
I'll have a think about it.

**Comment by matsumana** [comment]
How does that look?

https://github.com/matsumana/spring-boot/commit/3708f1f007c6b97210846dedc8531a7f556144aa

Do nothing at JmxAutoConfiguration.
And do at DataSourceAutoConfiguration.

**Comment by wilkinsona** [comment]
That's getting there, but you can't return `null` from a `@Bean` method. Instead, I'd probably `@Autowire`  `HikariDataSource` and `MBeanExporter` as fields into `HikariDataSourceJmxConfiguration` and then using a `@PostConstruct` method to exclude the MBean if necessary.

**Comment by matsumana** [comment]
Thank you for reply.

I see.
How does that look?

https://github.com/matsumana/spring-boot/commit/c6f263ae6d1a1d6e9b176c6ca1d6e8836ac8cab6

**Comment by wilkinsona** [comment]
That won't work. The `MBeanExporter` excludes by bean name and there's no guarantee that the name of the `HikariDataSource` bean with be `dataSource`.

**Comment by matsumana** [comment]
How does that look?

https://github.com/matsumana/spring-boot/commit/9e9b6286d3751432ed53d098d562d2bff3f4c1a7

Can I send pull request?

I want to discuss more on the pull request.

**Comment by snicoll** [comment]
@wilkinsona good call. The problem with backing off is that we don't. We will expose whatever jax bean is defined in the context and Hikari does that already if the property is set. So it's more about us being aware of a feature and reacting to it when that makes sense IMO. Having said that we can go with auto config only and expand if necessary.

**Comment by wilkinsona** [comment]
> We will expose whatever jmx bean is defined in the context and Hikari does that already if the property is set. 

That's the same as we have now for a DataSource looked up from JNDI in some user configuration rather than using the auto-config.

> Having said that we can go with auto config only and expand if necessary

In the interests of consistency, that sounds good to me for now at least.
