### ISSUE TITLE
Allow Spring Boot to be used in environments where the security policy prevents system properties from being set

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5115]
SpringApplication always tries to set `java.awt.headless`. We also always set certain system properties to do with logging, and may soon set more of them, although they are less likely to be locked down.

See http://stackoverflow.com/questions/35297491/is-there-a-way-to-prevent-spring-boot-initializer-from-setting-java-system-prope

**Comment by dfernandezm** [comment]
Is there anything new about this issue in a mid-term future? I would like to push a set of projects to move to Spring Boot, but they are likely to be deployed into large companies with very restrictive policies regarding System.properties.

 As a starting point, a list of all the calls to `System.setProperty() ` would be really helpful.

**Comment by imgx64** [comment]
@wilkinsona Would a patch that catches `SecurityException` in `configureHeadlessProperty` and logs a warning be accepted?

**Comment by wilkinsona** [comment]
@imgx64 That would be one approach that we could take. We would need to do the same for other places where properties are set. An alternative may be to use `doPrivileged` although I don't know if that would address @dfernandezm's situation. In short, I don't think we're quite ready for a patch that takes a particular approach.

**Comment by imgx64** [comment]
This particular call to `System.setProperty()` is blocking our use of Spring Boot on a jnlp-deployed application. I realize there isn't a decision on the bigger approach yet, but I just want a short-term solution for this instance.

How about calling `System.setProperty()` only if it changes java.awt.headless? Right now the code always calls it, even if java.awt.headless is already set. This could be a suitable workaround until the bigger problem is solved.

**Comment by dfernandezm** [comment]
Just to clarify it further, my situation would be fixed if basically *any* `System.setProperty()` call could be disabled on demand. The flexibility to control every `System.setProperty()` setting would allow running Spring Boot with a fixed security policy, by ensuring Spring Boot does not set the forbidden properties. @wilkinsona If you want to give me any guidance to start working on a pull request, I could work on it if it is appropriate.

**Comment by imgx64** [comment]
After further investigations, this is just the tip of the iceberg blocking running Spring Boot on jnlp applications. There are many other things that throw SecurityException when run in the Java Web Start sandbox.

As much as I hate it, looks like we'll just resort to asking for <all-permissions> in the jnlp (which is ok since the users are all in-house).

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
