### ISSUE TITLE
@Profile not respected on autoconfiguration (or imported) classes

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#5116]
I am preparing a major UI migration on a CI project, and I tried to use a Spring profile to switch between the old and new versions:

```
@Profile('newui')
@Configuration
class NewUiAutoConfiguration {
    ...
}
```

However, the autoconfiguration class is activated regardless of whether I use the `newui` profile. Changing the specification to `!newui` makes no difference, nor does moving the profile onto an `@Import`ed configuration class.

Standard profile inclusion/exclusion semantics should be observed on autoconfiguration classes; if there's a particular reason why it's not feasible, then the presence of a profile annotation on one should log a warning.

**Comment by philwebb** [comment]
I'm surprised this doesn't work as under the hood `@Profile` is implemented with a `@Conditional` (and we know those work). Do you have a sample application that reproduced the problem?

**Comment by chrylis** [comment]
I can reproduce the issue at will in my production application (which is composed of about 20 Maven modules, mostly wired through autoconfiguration, and polyglot Java/Groovy; the configuration class in question was in Groovy for convenient map creation), but I cannot make a base Java 8 Initializr project replicate. If I figure out a way, I'll reopen.

**Comment by philwebb** [comment]
Thanks. You can try adding a breakpoint to `org.springframework.context.annotation.ProfileCondition` in your production app if you want to debug things locally.
