### ISSUE TITLE
Transform Actuator docs so that URLs match the host's scheme, host, port and context path

### ISSUE THREAD

**Issue by shavo007** [spring-projects/spring-boot#5117]
Hi,

Just wanted to say I'm a big fan of spring boot. Have been using it commercially for the last two years.

I recently upgraded to spring boot 1.3.2.RELEASE.

I was playing around with new actuator endpoints.
I have defined in the config the management context path to be _admin.

```
management.context-path: "/_admin"

```

So I access locally the docs at:

```

http://localhost:8080/_admin/docs/
```

Is there anyway to dynamically change the endpoint URLS in the doc to _admin/<endpoint>?

For example, the curl request for autoconfig in the docs is 

```
curl 'http://localhost:8080/autoconfig' -i -H 'Accept: application/json'
```

I want it to be:

```
curl 'http://localhost:8080/_admin/autoconfig' -i -H 'Accept: application/json'

```

**Comment by wilkinsona** [comment]
> Is there anyway to dynamically change the endpoint URLS in the doc to _admin/?

No, not at the moment. We do already do some transformation for the HAL browser in `HalBrowserMvcEndpoint.InitialUrlTransformer`. This would be similar, albeit quite a big bigger.

**Comment by shavo007** [comment]
Cheers for the reply @wilkinsona . 

We currently use swagger for endpoint doc and i want to move away from it to using actuator docs.

if the hosts URL can change dynamically, that would really help. 

Thanks,
Shane.

**Comment by wilkinsona** [comment]
We're going to drop this (#9899)
