### ISSUE TITLE
Dupe /tmp/spring.log problem in at least 1.3.1 and 1.3.2

### ISSUE THREAD

**Issue by bmsantos** [spring-projects/spring-boot#5124]
I've noticed that when using RHEL/CentOS 6.7 two spring.log files are generated.
JDKs used: 1.7.0_91 and 1.7.0_95

When deployed in Linux (Red Hat Enterprise Linux Server release 6.7 or CentOS 6.7), the extra file is generated. The best solution I found so far was to remove the logback.xml file from classpath and pass it at command line: java -jar spring-boot-app.jar --logging.config=./logback.xml. This prevents a second log file from being generated.

Here's a sample maven project describing the issue - deploy it in a CentOS or RHEL 6.7 VM:
https://drive.google.com/file/d/0B6mOKQtZM9hxWTF5Vm9CMUVjaDA/view?usp=sharing

**Comment by wilkinsona** [comment]
Thanks for the sample project.

I'm a little bit confused by the description of the problem here and in the [comment on #4489](https://github.com/spring-projects/spring-boot/issues/4489#issuecomment-181977629).

The comment mentions the use of `logging.file` in `application.properties` but your sample project attached above doesn't contain an `application.properties` file. The comment also suggests that the problem only occurs on CentOS, however, when I run the sample project on OS X or CentOS 6.7, I see two files created in the temp directory. For example:

```
-rw-r--r--     1 awilkinson  staff     3632 25 Feb 13:56 logbackbug-14091.log
-rw-r--r--     1 awilkinson  staff        0 25 Feb 13:56 logbackbug-PID_IS_UNDEFINED.log
```

Can you please clarify that problem that you're reporting?

**Comment by wilkinsona** [comment]
I should also have noted above that the `logbackbug-PID_IS_UNDEFINED.log` file is created due to a configuration error. You're trying to use the `PID` system property before Spring Boot has had a chance to set it.

**Comment by bmsantos** [comment]
@wilkinsona, the app I'm working on ends-up being deployed in a RHEL system. So, when first deployed it, I was using the logging.file property. Everything worked just fine on OSX but not in RHEL..

Then I moved on to other options in the hope of finding a workaround for the issue and ended-up finding that the exact same issue happened when using my own logback.xml file.

Now, from your comments I can interpolate that this is a configuration issue. If so, how would you reconfigure the provided example so that a single file is created?

**Comment by bmsantos** [comment]
By the way, I just followed the setup details mentioned [here](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html#howto-configure-logback-for-logging).

**Comment by wilkinsona** [comment]
> Now, from your comments I can interpolate that this is a configuration issue. If so, how would you reconfigure the provided example so that a single file is created?

One option is to rename your logback.xml to logback-spring.xml. That will ensure that the configuration is only used once Spring Boot has had a chance to set all of the System properties (such as PID).

**Comment by welcor** [comment]
Another option (for future reference) could be to add 
`<property name="LOG_TEMP" value="./logs"/>`
at the top of logback.xml (or another path relative to the app file.)

Apparently, using logging.file in application.properties isn't enough as logback still touches the spring.log file. The file is touched, but never written to. This only fails if multiple apps run on the same machine as different users.

**Comment by Gritch69** [comment]
Same problem with --logging.file option. Only one apps can be run per machine.
