### ISSUE TITLE
Devtools doesn't work with classpath file mode in Idea

### ISSUE THREAD

**Issue by mraszplewicz** [spring-projects/spring-boot#5127]
We have very long classpath in our application so Idea can't run it without switching to "classpath file mode" (`dynamic.classpath=true` in `.idea/workspace.xml`). When I enable this mode devtools doesn't work.

Idea generates temporary jar file with Class-Path in `MANIFEST.MF` (`C:\Users\USER_NAME\AppData\Local\Temp\classpathX.jar`).

I was trying to debug the problem. This generated jar is treated as non reloadable in `org.springframework.boot.devtools.restart.ChangeableUrls` class.

**Comment by philwebb** [comment]
I'm not that familiar with this technique. Does `classpathX.jar` only contain a `MANIFEST.MF` file? Are there any other URLs passed to the `ChangeableUrls` constructor?

**Comment by snicoll** [comment]
ping @yanncebron

**Comment by akozlova** [comment]
classpathX.jar contains a manifest with Class-Path attribute which contains all the urls of the initial classpath. That's the official way to collapse too long classpaths from Oracle: e.g. https://docs.oracle.com/javase/tutorial/deployment/jar/downman.html. It's possible to force IDEA to switch back to the CommandLineWrapper with urls written to the file but this could add another problems with classloaders so I would advise not to do that if anyhow possible.
Anna

**Comment by mraszplewicz** [comment]
I've created sample project: https://github.com/mraszplewicz/springboot-dynamic-classpath
You have to open it in IntelliJ Idea, refresh gradle projects and run.

I have breakpoint in line 42 of class ChangeableUrls. There are only two urls passed to constructor: classpath47.jar and gragent.jar (something added by Idea).

Please find classpath47.jar attached.
[classpath47.zip](https://github.com/spring-projects/spring-boot/files/147979/classpath47.zip)

**Comment by akozlova** [comment]
@mraszplewicz 
And the manifest contains the whole classpath in the Class-Path attribute. My comment was adressed to @philwebb, sorry if I confused you

**Comment by mraszplewicz** [comment]
@akozlova Yes it does contain whole classpath. I'm not confused:) I am responding to @philwebb first comment. I'm not as fast as You are:)

**Comment by philwebb** [comment]
Thanks for the feedback. It looks like the current way we obtain the classpath (via `URLClassLoader`) isn't enough when using the `META-INF/MANIFEST.MF` technique.

**Comment by wilkinsona** [comment]
@mraszplewicz Thanks for the sample. Unfortunately, it doesn't reproduce the problem for me. I'm using IDEA 15. With `dynamic.classpath` set to `true` DevTools doesn't get loaded at all, let alone fail to detect that the context should have restarted. As far as I can tell IDEA is omitting it from the classpath. If I set `dynamic.classpath` to `false` then everything works as expected: DevTools loads when the application launches and restarts the context when make a change and build the project. What have I missed?

**Comment by wilkinsona** [comment]
When I start with `dynamic.classpath=true` the JVM is launched with:

```
-Didea.launcher.port=7536 -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15.app/Contents/bin -classpath /Applications/IntelliJ IDEA 15.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA 15.app/Contents/lib/util.jar -Dfile.encoding=UTF-8 com.intellij.rt.execution.CommandLineWrapper /private/var/folders/zq/v6xkr2696kv05jbf3bddt9680000gn/T/classpath0.tmp com.intellij.rt.execution.application.AppMain hello.Application --spring.output.ansi.enabled=always
```

It isn't using a jar file for the classpath, but instead seems to be using a temporary file. It looks like that file is read and deleted very quickly as it doesn't exist by the time I've had a chance to examine it.

**Comment by wilkinsona** [comment]
A penny may have dropped. I guess this only happens on Windows?

**Comment by mraszplewicz** [comment]
@wilkinsona I didn't have enough time to answer your questions. Thank you for solving the problem! I can't wait for the 1.3.4 release:)

**Comment by wilkinsona** [comment]
No problem. I've reproduced the problem and tested the fix on Windows, but if you have a chance to double-check that'd be great. You can grab a 1.3.4 snapshot from https://repo.spring.io/libs-snapshot.
