### ISSUE TITLE
Deprecate `@ConfigurationProperites#locations`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5129]
I really wonder why we're having a way to bind _one_ particular POJO to a different configuration. IMO this breaks  the nice "configuration environment" story in Spring Boot by adding something on the side that doesn't play well with the rest.

And [people got confused](https://github.com/spring-projects/spring-boot/issues/5111).

**Comment by wilkinsona** [comment]
People also got confused about the configuration being totally isolated so we added the `merge` attribute. With hindsight, I think that was a mistake. I'm in favour of getting rid of `locations`.

**Comment by wilkinsona** [comment]
Related to #2750

**Comment by philwebb** [comment]
+1, but we should probably just deprecate in 1.4 then drop in 2.0
