### ISSUE TITLE
Odd incompatibility from BufferedInputStream and RandomAccessDataFile::DataInputStream

### ISSUE THREAD

**Issue by sakanaou** [spring-projects/spring-boot#5130]
We faced the issue that some class file lead to a ClassFormatException from BCEL which is inside of AspectJ Weaver upon class loading via spring-boot. Oddly, if the class was extracted from the jar everything was fine.
Debugging deeply I found out that the culprit is a wrapping BufferedInputStream around the given InputStream, which is a RandomAccessDataFile::DataInputStream.
If the BufferedInputStream is removed the class bytecode can be loaded and validated flawlessly.

We use spring-boot 1.2.8 and aspectj 1.8.8 with Oracle JDK 7u80 and 8u66

**Comment by wilkinsona** [comment]
@sakanaou Can you please provide a small sample that reproduces the problem?

**Comment by sakanaou** [comment]
Hi. Sorry for replying so late and the confusing - I was busy hunting the issue.
I can now confirm that the issue is not related to spring-boot. I could isolate the issue in a small test program that loads the "broken" class file outside of spring-boot.
It seems to be an issue in the the BCEL version embedded into AspectJ.

**Comment by wilkinsona** [comment]
No problem! Thanks for letting us know

**Comment by sakanaou** [comment]
In case that anyone is interested: I reported the issue with a patch to the AspectJ team - https://bugs.eclipse.org/bugs/show_bug.cgi?id=487927
