### ISSUE TITLE
Documentation needs improving for maven plugin start/stop goals to explain that spring.application.admin=true is needed

### ISSUE THREAD

**Issue by paulnuk** [spring-projects/spring-boot#5132]
The start/stop goals rely on the admin mbean being active so that the plugin can shutdown a container after the integration tests have run, however the documentation doesn't mention this.

The documentation could be improved to say that if you want to use the start/stop goals, spring.application.admin should be set to true for the container that is being started

**Comment by snicoll** [comment]
I am confused. The plugin does start the admin mbean behind your back so that you don't have to know about it! 

How did you manage to be in a situation where it wasn't available? Sharing a sample would help.

**Comment by paulnuk** [comment]
I've only just got this working with what is a fairly massive app, so I'll try and cut this down into a simple pom/class and post that. That may take me a couple of days due to other work.

**Comment by snicoll** [comment]
The plugin configuration for the `spring-boot-maven-plugin` (when it does not work) and the log output would be a good start.

**Comment by paulnuk** [comment]
Apologies for this - the (as it turns out false) requirement to add this property was a result of confusion elsewhere caused by the missing out of fork=true. It works fine without having to manually add this. Closing the issue.
