### ISSUE TITLE
Propertysources precedence when merging the property source from `@ConfigurationProperties`' locations

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-projects/spring-boot#5135]
When the `merge` attribute for `@ConfigurationProperties` is set to **true** to merge the environment property sources along with the property sources specified in the `locations`, the property sources from the `locations` attribute [gets the **highest** precedence] (https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessor.java#L407).

Is this precedence level set for a reason? I was expecting the property source from `locations` getting the **lowest** precedence.

For instance, if I have a `commandLine` args for the application, wouldn't I expect this args override all the other property source including the one specified in `locations` attribute of `ConfigurationProperties` annotation.

**Comment by wilkinsona** [comment]
@ilayaperumalg Originally, the location attribute ignored the rest of the environment completely. The `merge` attribute was added as that surprised people. They wanted their custom location to override the environment. You want it to be overridden by the environment. Satisfying both camps will, IMO, make things too complex. We're actually considering getting rid of `locations` altogether (see #5129). Please comment on that issue if you feel strongly that it should be retained and have a compelling use case for the added complexity.

**Comment by ilayaperumalg** [comment]
@wilkinsona I see. I agree that it makes sense to keep one way of support and less complexity. Would be nice if we add Javadoc that says the `precedence` order on `merge`.

Thanks!

**Comment by wilkinsona** [comment]
As it happens, @snicoll improved the javadoc yesterday. See https://github.com/spring-projects/spring-boot/commit/594c8910c569961f1ea63d77e1156566c6f67d37

**Comment by ilayaperumalg** [comment]
Cool! :+1:
