### ISSUE TITLE
'shell.auth*' family of configuration properties hard to assign from valid yaml

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#5139]
There is a configuration property with key 'shell.auth' which expected to be set to a atomic value ('simple', 'jaas' etc.).

At the same time there are also related properties that act like subproperties of 'shell.auth'. For example 'shell.auth.key.path'. To assign a value to both of these simultaneoulsy in yaml one would have to write something like this:

      shell:
        auth: simple
        auth:
          key:
            path: something

This is not technically 'valid' yaml. The yaml spec says that 'mapping keys must be unique'. One might be able to parse and process yaml with these kind of 'invalid' structures in them but the meaning of them isn't defined. A good library might flag it as an error. A less picky library might instead overwrite one value of the key with another during processing instead.

As a user, you can probably work around this (I think) by using yaml 'document markers' to split up the yaml file into multiple sub documents (i.e. separated by '---'). But I think that is awkward as it forces you to make assignments to related things (all related to shell.auth) far away from eachother in your yaml file.

**Comment by wilkinsona** [comment]
It looks like `auth` should be renamed, perhaps to `auth-type`. We could retain the old property for backwards compability if needs be.

**Comment by snicoll** [comment]
I guess you mean `shell.auth.type`, right?

**Comment by wilkinsona** [comment]
No, not necessarily. That would risk a (very unlikely) clash with an authentication type that's called `type` as it's configuration properties would presumably want to be named `shell.auth.type.*`.

**Comment by snicoll** [comment]
Oh my, I haven't seen that :(

**Comment by kdvolder** [comment]
Calling one thing 'shell.auth-type' and another 'shell.auth.type' is perhaps also a bad idea because of spring-boot relaxed name binding I can imagine that's a little ambiguous as well.

For example in upper-case underscore form (typical for use in environment variables) they both become

'SHELL_AUTH_TYPE'.
