### ISSUE TITLE
Freemarker and spring-mobile: No mobile detection

### ISSUE THREAD

**Issue by jochen777** [spring-projects/spring-boot#5140]
I tried to run the following guide with the freemarker template engine:
http://spring.io/guides/gs/serving-mobile-web-content/

**This is not working as expected: Even on a mobile device, the desktop-template will be shown.**

I debugged a little bit and discovered this:
1.) Ordering of `view-Resolvers` in `DispatcherServlet`
In the `org.springframework.web.servlet.DispatcherServlet`: 
The list of avail `viewResolvers` is:

Freemarker-Project:
```
[ContentNegotiatingViewResolver, BeanNameViewResolver, **FreeMarkerViewResolver**, **LiteDeviceDelegatingViewResolver**, ViewResolverComposite, InternalResourceViewResolver]
```
Thymeleaf-Project:
```
[ContentNegotiatingViewResolver, BeanNameViewResolver, **LiteDeviceDelegatingViewResolver**, **ThymeleafViewResolver**, ViewResolverComposite, InternalResourceViewResolver]  
```

Note the ordering of the `view-resolvers`. Where it works, the `DeviceDelegatingViewResolver` is **before** the `TemplateEngineViewResolver`. I don't know, if this is the root of the problem...

2.) `DeviceDelegatingViewResolverAutoConfiguration` just for Thymeleaf
The Source of `DeviceDelegatingViewResolverAutoConfiguration` only holds configurations for Thymeleaf - as far as I can see. Perhaps Freemarker configuration is just missing here?

Thank you for Spring and Spring-Boot!! Great projects.

See example Project here:
https://github.com/jochen777/spring-boot-freemarker-mobile

**Comment by snicoll** [comment]
Indeed your project works fine with thymeleaf. It looks like the auto-config only takes care of that template engine at the moment.

**Comment by snicoll** [comment]
@royclarkson the current auto-configuration expects only one `LiteDeviceDelegatingViewResolver` (especially since `enableFallback` is exposed as a property). Is that on purpose?  What if you have both freemarker and thymeleaf in your app and you want to use that infrastructure?

My move was to refactor things a bit and expose one bean per template engine that we support. But I guess that means we should remove that `enableFallback` property. Thoughts?

**Comment by royclarkson** [comment]
Indeed, the current implementation only supports Thymeleaf and JSP. It was introduced prior to Boot 1.0, and was never fully baked. @snicoll that sounds like a good strategy. I'm reviewing it now.

**Comment by royclarkson** [comment]
@snicoll I added an implementation in the PR for FreeMarker support. I'm concerned about making this more generic and applying it to all ViewResolvers, because I don't think it makes sense to create a  `DeviceDelegatingViewResolver` bean for each one. If you have a better strategy in mind, then feel free to ignore my PR.

**Comment by snicoll** [comment]
Not all view resolvers but the one that we support. I fail to see why we would support thymeleaf and not mustache for instance. It should also be super easy for someone to create its own so I was thinking about some public SPI to create the interceptor and have auto-configuration for each rendering engine we support. What's wrong with that?

**Comment by royclarkson** [comment]
Nothing's wrong with that. :) Mustache and GroovyMarkup are also good candidates.

**Comment by snicoll** [comment]
@jochen777 your sample app works fine with `1.4.0.BUILD-SNAPSHOT` now.

**Comment by psabharwal123** [comment]
how would i make this work for handlebars template? i am using https://github.com/allegro/handlebars-spring-boot-starter.

**Comment by snicoll** [comment]
@psabharwal123 better ask them I guess.

**Comment by psabharwal123** [comment]
from the above it seems the fix needs to be made on spring-mobile and not handlebars-spring-boot-starter

**Comment by wilkinsona** [comment]
@psabharwal123 Can we please stop discussing the same thing on two separate issues. I've already pointed you to the relevant section of the Spring Mobile documentation in the issue that you opened. There's no fix to be made here.

**Comment by FlowerWrong** [comment]
I am using spring boot 1.5.2, it still not work with freemarker in auto-config mode. :sad:

**Comment by wilkinsona** [comment]
@FlowerWrong If you believe you still have the problem described here, please open a new issue with a small sample project that reproduces the problem.
