### ISSUE TITLE
Integration tests don't clean up after themselves

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5141]
Trying to fix #2308 has revealed that the tests in `spring-boot` don't clean up after themselves very well. This is, in part at least, due to the caching performed by the test framework. We very rarely use the same context configuration across different tests classes so caching for the lifetime of the JVM almost certainly isn't buying us very much, and appears to be doing some harm.

The fix for #2308 sets Tomcat's web app class loader as the main thread's context class loader when Tomcat starts and resets it when Tomcat stops. Due to the caching in the test framework, we have several Tomcat instances that are started and then aren't stopped until the JVM exits and the context's shut down hook runs. This pollutes the main thread's context class loader as it's not getting reset.

At the end of running all of the tests in `spring-boot` there are 69 live threads (37 are daemon threads). Looking at these threads, there are Undertow, Bitronix and Apache HTTP client instances that also haven't been cleaned up. Furthermore, 1250MB of heap is in use although this does drop substantially upon forcing the garbage collector to run.

**Comment by wilkinsona** [comment]
@sbrannen Is there any easy way to switch the cache off, at least as an experiment? I was looking for something like a system property but didn't find anything when looking through the test framework code. I know I could use `@DirtiesContext`, but that would be spread out over several classes. Even if it's a horrible reflective hack, it'd like to try it to see what effect, if any, it has.

**Comment by sbrannen** [comment]
@wilkinsona,

No, there is currently no easy way to switch off caching, but we are planning on adding support along these lines for 4.3, time permitting:

- https://jira.spring.io/browse/SPR-8055
- https://jira.spring.io/browse/SPR-11576 (closed, but related)

The only way to turn off caching currently is to implement your own `CacheAwareContextLoaderDelegate`, which would have to be returned from your own `BootstrapContext`, which would have to be set in the `TestContextBootstrapper` used by the `TestContextManager` (which is loaded by Spring's JUnit runner and rules).

Yes, I know.... that's rather convoluted but primarily because it's considered to be a very advanced, low-level extension point.

The easiest way to _experiment_ would be to _shadow_ the `DefaultContextCache` in the `spring-test` JAR (e.g., create a `org.springframework.test.context.cache.DefaultContextCache` in your own module (that loads first in the classpath) that doesn't actually do any caching or limits the cache size).

Hope this helps!

**Comment by sbrannen** [comment]
For your "horrible reflective hack," you could replace `org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.defaultContextCache` with your own non-caching Cache. :wink:

**Comment by sbrannen** [comment]
Actually, now that I think about it, the easiest/most transparent way to achieve this would be to implement a `TestExecutionListener` that simply always marks the context as _dirty_ after every test class (or test method if you prefer). It would do the same thing as the `DirtiesContextTestExecutionListener` except that it would not check for the presence of `@DirtiesContext`. You could then have that custom `TestExecutionListener` auto-registered via the `SpringFactoriesLoader` mechanism.

Good luck, and let me know how it works out.

**Comment by garyrussell** [comment]
FWIW, in Spring Integration we have been systematically adding class-level `@DirtiesContext` everywhere - as I say in the comment to SPR-11576. we generally __want__ caching within a class but generally never across classes.

We're probably close to being done (just in time for the new feature in 4.3 and we can start removing them again :smile: ).

**Comment by wilkinsona** [comment]
@sbrannen

> You could then have that custom TestExecutionListener auto-registered via the SpringFactoriesLoader mechanism.

Thanks for the suggestion. Unfortunately, this approach doesn't work for the vast majority of our tests as they are annotated with Spring Boot's `@IntegrationTest` which is meta-annotated with `@TestExecutionListeners`. As you know, this means that any listeners configured via `spring.factories` aren't picked up.

Inspired by the suggestion to shadow `DefaultContextCache`, I've shadowed `DirtiesContextBeforeModesTestExecutionListener` and overridden `afterTestClass(TestContext)` instead. 

With this change in place heap usage is reduced by 250MB, and there are 29 fewer live threads. There doesn't appear to be any noticeable impact on test execution time with the tests in `spring-boot` taking ~26 seconds both with and without the hack to disable caching.

**Comment by sbrannen** [comment]
Ahhhh, yes, if you're primarily using `@IntegrationTest` then that suggestion of course wouldn't work.

I was in a bit of a rush when I composed those responses (waiting to board a flight), so I didn't think through your exact use case and the implications of `@IntegrationTest` -- sorry about that.

In any case, I'm glad you worked out a solution with the shadowed `DirtiesContextBeforeModesTestExecutionListener`, and ... it sounds like you achieved your goals regarding threads and heap usage.

**Comment by philwebb** [comment]
I'd like to fix `@IntegrationTest` to remove the direct set of listeners. See #5230.
