### ISSUE TITLE
Description Atomikos properties unclear

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#5143]
When configuring an application with Atomikos for JTA (more specifically setting up the transaction timeout), I turned to the spring boot documentation for available properties. The spring boot documentation states the following with regard to JTA properties:
```
# JTA (JtaAutoConfiguration)
spring.jta.*= # technology specific configuration
spring.jta.log-dir= # Transaction logs directory.
```

And then some Atomikos-specific settings for connectionfactory and datasource. However, when you look in the Atomikos documentation ([here](http://www.atomikos.com/Documentation/JtaProperties)), the specific property I was looking for (amongst others) is called 

> com.atomikos.icatch.default_jta_timeout

Hence, I would expect that setting a property of spring.jta.com.atomikos.icatch.default_jta_timeout would allow me to specify the transaction timeout. Unfortunately, if you look at the source of the [AtomikosJtaConfiguration.java](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/transaction/jta/AtomikosJtaConfiguration.java) you can see that the method atomikosProperties() specifies a properties prefix of spring.jta. This means that the property for default_jta_timeout will be picked up from the property spring.jta.default-jta-timeout.

Regardless of what the properties need to be, I believe the documentation is not in line with how it works at the moment.

**Comment by snicoll** [comment]
Yes, indeed we have out-of-the-box support for several properties and these are not well documented in the developer guide. I would argue that we've made the same mistake as for the `spring.datasource` namespace by merging those specific settings in `spring.jta`. 

If you are using IDE assistance though, you get the expected key (see [this screenshot](http://prntscr.com/a3wdc2)).

**Comment by snicoll** [comment]
The doc has been improved in 1.3 and I've reworked the namespace and the documentation in 1.4 to make it easier to figure out which property belongs to which implementation (see #5165)
