### ISSUE TITLE
spring-boot-starter-web-base instead of excluding tomcat

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#517]
I wonder if it wouldn't be nicer if instead of excluding the tomcat starter from `starter-web` we could create a new module that would bring everything _but_ the container, something like `spring-boot-starter-web-base`.

Using Jetty (or X) instead of Tomcat would then be a matter of importing the base project + the starter project for the container of your choice.

I can draft something if you guys think it's a good idea.

**Comment by edudar** [comment]
We always use `jetty` with `spring-boot` so have to exclude `tomcat` from `web` in every single build file which at some points gets pretty annoying. Having `starter-[ mvc | jersey ]` + `starter-[ tomcat | jetty | undertow ]` separately would be much appreciated. Yes, this complicates things a little bit at maybe defeats the purpose of being as simple as possible, so leaving `web` as is - `mvc+tomcat` might still work with more specific starters for advanced usage.

**Comment by denon82** [comment]
I agree!
Em 30/04/2015 22:17, "Eduard Dudar" <notifications@github.com> escreveu:

**Comment by wilkinsona** [comment]
@edudar @denon82 Do you use Maven or Gradle? I've been thinking about some Gradle plugin enhancements that would make this easier but I'm not sure that the same is possible with Maven

**Comment by edudar** [comment]
@wilkinsona Gradle

**Comment by denon82** [comment]
In general I use maven!

On Fri, May 1, 2015 at 3:24 AM, Eduard Dudar <notifications@github.com>
wrote:

> @wilkinsona <https://github.com/wilkinsona> Gradle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-boot/issues/517#issuecomment-98057547>
> .
>



-- 
Flávio Oliva
+55 61 83194588
ffroliva@gmail.com

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/2933 to discuss an alternative solution to this problem, but I think it may only be possible with Gradle.

**Comment by snicoll** [comment]
There hasn't been much activity on this one for quite some time and the team consensus is not to move forward with this.
