### ISSUE TITLE
Support authentication other than HTTP Basic

### ISSUE THREAD

**Issue by ShijunK** [spring-projects/spring-boot#5172]
I'd like to propose a feature that allow users to plugin authentication method other than HTTP Basic for default web security config (`org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration.ManagementWebSecurityConfigurerAdapter`  and `org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration.ApplicationWebSecurityConfigurerAdapter`)

As of 1.3.2.RELEASE, HTTP basic is the default and hardcoded authentication method. Unfortunately, I need to use customized pre-authentication, but still want to keep as much as default security behaviors provided by Spring Boot. For now, the only options are: 1) fork spring boot  2) Replace `ManagementWebSecurityAutoConfiguration` and `SpringBootWebSecurityConfiguration`), keep everything else but the HTTP basic authentication part. Either one is a heavy weight solution. 

If I missed any easier way to do so, please let me know.

**Comment by wilkinsona** [comment]
See also #1901

**Comment by wilkinsona** [comment]
This has been superseded by the [security simplifications in M4](https://spring.io/blog/2017/09/15/security-changes-in-spring-boot-2-0-m4).
