### ISSUE TITLE
Investigate RedisCache and RedisCacheManger defaults and configuration.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-boot#5175]
_Opened for discussion on both Spring Boot and Spring Data side._

Having a look at the caching in spring-data-redis - the defaults of `RedisCache` and `RedisCacheManager`, though described in the javadoc, can cause issues.

Generally speaking without any configuration (JdkSerializer / No CachePrefix) the generated keys look pretty bad. 

```java
@Service
@CacheConfig(cacheNames = "this")
public class ThisService {

	@Cacheable
	public String get(String string) {
		return string;
	}

}

@Service
@CacheConfig(cacheNames = "that")
public class ThatService {

	@Cacheable
	public String get(String string) {
		return string;
	}

}

thisService.get("this");
thatService.get("that");
```

The above would generate keys like `\xac\xed\x00\x05t\x00\x04this` and `\xac\xed\x00\x05t\x00\x04that`. 
And yes the services would have overlapping keys and be likely to return invalid values.

```bash
1455784392.204538 [0 127.0.0.1:56254] "MULTI"
1455784392.204559 [0 127.0.0.1:56254] "SET" "\xac\xed\x00\x05t\x00\x04this" "\xac\xed\x00\x05t\x00\x04this"
1455784392.204571 [0 127.0.0.1:56254] "ZADD" "this~keys" "0.0" "\xac\xed\x00\x05t\x00\x04this"
1455784392.204587 [0 127.0.0.1:56254] "EXEC"

1455784392.213306 [0 127.0.0.1:56254] "MULTI"
1455784392.213322 [0 127.0.0.1:56254] "SET" "\xac\xed\x00\x05t\x00\x04that" "\xac\xed\x00\x05t\x00\x04that"
1455784392.213333 [0 127.0.0.1:56254] "ZADD" "that~keys" "0.0" "\xac\xed\x00\x05t\x00\x04that"
1455784392.213347 [0 127.0.0.1:56254] "EXEC"
```

A configuration using Jackson2 like below

```java
public @Bean RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory connectionFactory) {

	RedisTemplate<Object, Object> template = new RedisTemplate<>();
	template.setConnectionFactory(connectionFactory);
	template.setDefaultSerializer(new GenericJackson2JsonRedisSerializer());
	return template;
}

public @Bean CacheManager cacheManager(RedisTemplate<Object, Object> redisOperations) {

	RedisCacheManager cm = new RedisCacheManager(redisOperations);
	cm.setUsePrefix(true);
	return cm;
}
```
 produces the following:

```bash
1455784748.065626 [0 127.0.0.1:56347] "MULTI"
1455784748.065644 [0 127.0.0.1:56347] "SET" "this:\"this\"" "\"this\""
1455784748.065655 [0 127.0.0.1:56347] "EXEC"

1455784748.072581 [0 127.0.0.1:56347] "MULTI"
1455784748.072595 [0 127.0.0.1:56347] "SET" "that:\"that\"" "\"that\""
1455784748.072605 [0 127.0.0.1:56347] "EXEC"
```

**Comment by snicoll** [comment]
I am considering fixing this in the 1.3 line still which would bust all existing caches. @bclozel maybe you could share what you've customized in Sagan.

@philwebb how do you feel about changing the default key strategy in 1.3 still?

**Comment by philwebb** [comment]
Have we had any users complain? Seems like a slightly risky thing to do in 1.3

**Comment by snicoll** [comment]
Put it this way: If they don't use the feature they won't complain. The default right now means that if you have two methods on two different caches with the same arguments, they will have the same key in redis ( = ClassCastException if the wrong value is in it when the method is invoked). I agree it's risky for 1.3. Maybe we should document that limitation and fix it in 1.4?

**Comment by philwebb** [comment]
Ahh, OK. If the scope's limited then 1.3 might be better.

**Comment by snicoll** [comment]
I was writing the work-around in the doc and it made no sense to me. It's like writing in the doc: "the default in Spring Boot is likely to fail" so I would like to reconsider breaking this in 1.3 

That means that the cache will be emptied on upgrade since the key structure will change.

**Comment by snicoll** [comment]
I have a proposal in https://github.com/snicoll/spring-boot/commit/b4a6aafa9b247d185b7f7058a08a43359da5ef36

@wilkinsona @christophstrobl I created a property that match the name of the property in `RedisCacheManager` but I am wondering if that's a good idea. I can see this property disappearing and check if the `RedisCachePrefix` is `null` instead). Also `usePrefix` is not very clear as it applies a prefix on the key entry. Maybe we should find a better name for our own configuration?

**Comment by wilkinsona** [comment]
`RedisCachePrefix` is non-null by default, so I can't see how checking for `null` would help there. Have I missed something?

I'm not sure that, even with a property, we should change the default in 1.3.3. Anyone who hits the problem can configure their own `RedisCacheManager` bean can't they?

**Comment by snicoll** [comment]
> RedisCachePrefix is non-null by default, so I can't see how checking for null would help there. Have I missed something?

It is. Sorry I was thinking out loud what could happen in the revised version of the `RedisCacheManager` where this property would dissapear

> Anyone who hits the problem can configure their own RedisCacheManager bean can't they?

Yes. I started this issue by documenting that fact. And I was really not confortable with it. It's like I am documenting something in the doc that states it breaks by default.

**Comment by wilkinsona** [comment]
> Yes. I started this issue by documenting that fact. And I was really not confortable with it. It's like I am documenting something in the doc that states it breaks by default.

How likely is it to break by default? If you have a Redis instance that's storing a single cache everything will just work, won't it? Unfortunately, I have no idea how common that configuration might be.

**Comment by snicoll** [comment]
Having multiple caches is very common. Storing things that have identical ID may be not.

**Comment by snicoll** [comment]
@christophstrobl I have "fixed" the issue for the time being by adding a prefix but we need to discuss on the `spring-data-redis` side how we could improve the API. I know that @bclozel has some interesting customizations in Sagan. Maybe we should look at that and see how we can integrate them?

**Comment by christophstrobl** [comment]
@snicoll agree. I'll get back to you and @bclozel once we've Hopper RC1 out.
