### ISSUE TITLE
Add caching support for Couchbase

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5176]
We have now support for Couchbase and regular Spring Data repository. Couchbase has also a cache manager implementation that we could auto-configure when it's present.

**Comment by eddumelendez** [comment]
@snicoll are you already working on that? If not, I will work on that this weekend.

**Comment by snicoll** [comment]
I'd love you to but it's more than integrating `CouchbaseCacheManager` I am afraid. They are things that we need to change in the implementation first and I had a lengthy discussion with Simon about what to do. Maybe I can do that and we can have a chat on the side for the remaining pieces if you want to give it a try?

**Comment by eddumelendez** [comment]
I understand. Sure, I would like to try.

**Comment by snicoll** [comment]
Sorry @eddumelendez I was working on the couchbase side and forgot you offered to help. I've pushed an initial implementation waiting on `couchbase-spring-cache` to be released. Let me know if you find any issue in the current proposal. Thanks!

**Comment by eddumelendez** [comment]
cool to see this in master branch. I will take a look this weekend. kudos to @snicoll
