### ISSUE TITLE
documentation for value and prefix is mixed in org.springframework.boot.context.properties.ConversionService

### ISSUE THREAD

**Issue by oneiros-de** [spring-projects/spring-boot#5177]
From org.springframework.boot.context.properties.ConversionService in 1.3.2.RELEASE:
```
	/**
	 * The name prefix of the properties that are valid to bind to this object. Synonym
	 * for {@link #prefix()}.
	 * @return the name prefix of the properties to bind
	 */
	String value() default "";

	/**
	 * The name prefix of the properties that are valid to bind to this object. Synonym
	 * for {@link #value()}.
	 * @return the name prefix of the properties to bind
	 */
	String prefix() default "";
```
The documentation is mixed up and the first sentence is repeated.
Or does `value` really specify the _prefix_ and `prefix` the _value_?

**Comment by wilkinsona** [comment]
Both attributes allow you to configure the same thing, with `value` being a synonym for `prefix`. All annotations have to have a `value` attribute but the `prefix` synonym allows your annotation to be more readable when you're configuring multiple attributes.

Consider

```
@ConfigurationProperties(value="com.example.foo", ignoreInvalidFields=true)
```

Versus

```
@ConfigurationProperties(prefix="com.example.foo", ignoreInvalidFields=true)
```

Both are providing the exact same configuration, but the latter is more readable as it's clear that `com.example.foo` is the prefix.

**Comment by philwebb** [comment]
Also worth noting that `value` has special meaning with java annotations as it can be omitted if it's the only attribute. i.e.

```java
@ConfigurationProperties("com.example.foo")
```
