### ISSUE TITLE
Automatic Validator for Couchbase AutoConfig

### ISSUE THREAD

**Issue by ldoguin** [spring-projects/spring-boot#5178]
I would love to have automatic validation just by adding an annotation on an entity. As a developer I expect to write only 'significant' code.

If I have 

```
@NotNull
private String someField
```

I expect it to be the only code I have to write to make sure this field will never be persisted as null.

Currently I have to add a validator bean like so:

```
@Bean
public Validator validator() {
    return new LocalValidatorFactoryBean();
}
```

I know it's not a lot to add, but from a devex perspective, I would find it easier to have it directly set in CouchbaseAutoconfiguration.

That being said I might not realize fully what having a validator declared implies other than making sure your annotation will be taken into account.

**Comment by philwebb** [comment]
Probably worth following the same pattern as `ConfigurationPropertiesBindingPostProcessor`

**Comment by snicoll** [comment]
We should probably improve `ValidationAutoConfiguration` (#6228 ) to expose a `Validator` then. Right now, we don't use any of the logic in `ConfigurationPropertiesBindingPostProcessor`
