### ISSUE TITLE
App launched from an IDE with spring-boot:run with forking enabled doesn't get shut down properly

### ISSUE THREAD

**Issue by nithinmeshram** [spring-projects/spring-boot#5185]
I am using Linux Mint 17.2, JDK 1.7 (Oracle) and Eclipse Mars with Maven 3.1.0-alpha-1.  When using a Spring Boot application (version 1.3.1 RELEASE) and corresponding Spring Boot Dev Tools, the Tomcat Embedded Container doesn't shutdown when the running instance is stopped from within the Eclipse IDE (using the red square button on the Eclipse Console view).  Having a LiveReload server enabled or disabled doesn't seem to show any difference in the behavior.  I have to manually open a shell and kill the corresponding Tomcat Instance.  However, the "restartedMain" thread works fine meaning, all the resources (Java Classes, JS, CSS, HTML) reload perfectly fine.  It's just that the Tomcat instance doesn't gracefully shutdown.  Is this normal / expected?

And I run my application from within the IDE, using 'clean install spring-boot:run'. Forgot to mention in the first comment.

I created a sample application just for anyone interested to reproduce the issue.  Here is the link: https://github.com/nithinmeshram/spring-boot-thymeleaf-form-validation

I would like to know if there is any workaround.  Thanks!

**Comment by philwebb** [comment]
Is there any particular reason that you're running the application using `clean install spring-boot:run` from within the IDE? I've most seen people just use the standard eclipse `run -> as java app` to launch applications.

**Comment by nithinmeshram** [comment]
Thanks for the response.

I ran my application using Run as a Java Application and indeed the Tomcat Container shuts down properly.  I think, I can live with that.  My application doesn't have a lot of customizations in POM and ince the project was a Maven project, I habitually ran it using Maven goals.  

But then just for my knowledge, does this mean that a Spring Boot application must always be run as a Java Application even if its a Maven/Gradle project?

**Comment by wilkinsona** [comment]
With forking enabled, when the IDE (I don't think this is restricted to Eclipse) stops the parent process (the Maven build) it fails to also terminate the child process (the application) and leaves it orphaned. When launched in a shell and terminated with CTRL+C the child isn't orphaned.

If possible, we should avoid relying on the child automatically being killed when the parent is killed and make sure that `spring-boot:run` cleans up the forked process when it exits.

**Comment by philwebb** [comment]
We might be able to add a shutdownHook to do that. Certainly worth investigating.

**Comment by wilkinsona** [comment]
Closed by 310be23.
