### ISSUE TITLE
UserInfoTokenServices.PRINCIPAL_KEYS should be configurable or replaceable

### ISSUE THREAD

**Issue by patope** [spring-projects/spring-boot#5186]
Principal id for session is chosen based on fixed list here:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/UserInfoTokenServices.java#L49

I have problem with CloudFoundry's uaa server where username attribute key has slightly different format than on list and spring uses user_id for a user's pricipal id. On uaa user_id is UUID that is not very informative.

https://github.com/cloudfoundry/uaa/blob/3.1.0/model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/ClaimConstants.java#L27

Authorizations are extracted from user info using AuthoritiesExtractor, maybe there could be PrincipalExtractor for principal?

**Comment by philwebb** [comment]
See also #5053 which made the method protected. I still think a `PrincipalExtractor` is a good idea.
