### ISSUE TITLE
Better support for TcServer tomcat features

### ISSUE THREAD

**Issue by mdiskin** [spring-projects/spring-boot#5189]
As a customer and user of the tcserver branded tomcat (Pivotal App Suite) it would be great if the out of the box experience with Spring Boot was enhanced.

Here's a few items I can think of:
- Property Placeholder enhancements to leverage (com.springsource.tcserver.properties.SystemProperties)
- Obfuscate/Encryption of Properties (com.springsource.tcserver.security.PropertyDecode)
- Gemfire Session and Hibernate Cache detection and autoconfig.
- tcserver MBean (tcserver.Serviceability) via existing/new Actuators.

Let me know if it's something you'd like me to do some more detailing out to use cases, etc..

Thanks
Mark

**Comment by wilkinsona** [comment]
There's no support for tc Server in Spring Boot itself. I believe tc Server provides a separate starter that allows tc Server to be used with Spring Boot. I think that would be a better place for these new features.

/cc @wesschlichter @jkonicki

**Comment by jkonicki** [comment]
Hi Mark,

Andy is correct, the tc Server team provides the spring boot starter for tc Server.  

Thank you for requests, we will add them to our feature backlog for prioritization.  

-Jason

**Comment by mdiskin** [comment]
Thanks – can you add to this case and also for my benefit (maybe others looking for it since I did not know one existed) where to find this starter.


Mark Diskin
Enterprise Application Architect
+1.813.612.3010 | office & fax
+1.813.760.5019 | mobile
arc mdiskin@arccorp.com<mailto:lgao@arccorp.com>
12470 Telecom Drive, Suite 400 W
Temple Terrace, FL 33637

WE POWER TRAVEL

Send me a secure message<https://securecontact.me/mdiskin@ARCCorp.com>

**Comment by jkonicki** [comment]
Sure.  Here is the link to the example, which shows how to access the starter (currently just substitutes tc Server jars in the starter). Let me know if you have any questions. https://github.com/appsuite/spring-boot-starter-tcserver-example
