### ISSUE TITLE
Revisit fix for gh-4980 once changes to @Lazy and @Autowired(required=false) are available

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5191]
https://jira.spring.io/browse/SPR-13967

**Comment by wilkinsona** [comment]
It looks like we might get a fix for this in 4.2.5 so I'm tentatively targeting 1.3.3 now

**Comment by snicoll** [comment]
Actually we just fixed the exception. `@Lazy` on field is a bit weird. How about using an `ObjectFactory` instead.

**Comment by wilkinsona** [comment]
I had wrongly anticipated that the combination of `@Lazy` and `@Autowired(required=false)` would be changed to result in a `null` field. I don't think that moving to an `ObjectFactory` from calling `getBean` on the context is worth it so I'm going to close this.
