### ISSUE TITLE
Unable to force my application to use external (CF provided) Tomcat

### ISSUE THREAD

**Issue by ashwgupt** [spring-projects/spring-boot#5192]
It has been quite a challenge so far to get my application download and use our CF provided Tomcat instead of the embedded one but no success in sight yet.

I am developing a spring boot (1.3.2) application of hello world type, and have below starters in my POM (using Maven to build/pkg).

> <parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.3.2.RELEASE</version>

> </parent>

> <dependency>

		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-cloud-connectors</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-tomcat</artifactId>
			</exclusion>
		</exclusions>
	

> </dependency>

		
	

> <dependency>

		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
		<exclusions>
			<exclusion>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-tomcat</artifactId>
			</exclusion>
		</exclusions>
	

> </dependency>

	

> <dependency>

		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-tomcat</artifactId>
			</exclusion>
		</exclusions>
	

> </dependency>

> <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-tomcat</artifactId>
		<scope>provided</scope>
	

> </dependency>

The spring-boot-maven-plugin also is used to make it a good application.

As you see, I've ensure to mark the exclusion of embedded tomcat from all starters, and have decalred the scope of tomcar-starter as 'provided' to ensure I get it from the platform but that doesn't help.

In my cf push logs, I never get the 'Downloading Tomcat' logs, and at the end can clearly see the tomcat jar (tomcat-embed-el-8.0.30.jar only) packaged in WEB-INF/lib folder on the deployed app.

Also to add, the only difference that I see when the scope is swapped from 'provided' to 'complie' or default, is more tomcat-embed jar file going into the packaged and ultimately in lib folder.

** For scope: compile or default
$cf files demo app/WEB-INF/lib
tomcat-embed-core-8.0.30.jar              2.7M
tomcat-embed-el-8.0.30.jar              232.4K
tomcat-embed-logging-juli-8.0.30.jar      39.9K
tomcat-embed-websocket-8.0.30.jar       240.2K

** For scope: provided
$cf files demo app/WEB-INF/lib
tomcat-embed-el-8.0.30.jar              232.4K

Is there a way to fix this behavior such that platform provided tomcat can be used? Or is it a complusion to use embedded tomcat with Spring Boot (which am sure not the case)?

**Comment by philwebb** [comment]
Have you tried just building a standard war file? I.e. not using the `spring-boot-maven-plugin` at all?

**Comment by ashwgupt** [comment]
Yes, I've tried but that fails to find the main method, despite the fact that below main/start class pointers are defined in my POM, and hence fails to start.

`<properties>`
	`<start-class>com.abc.Application</start-class>`
	`<Main-Class>com.abc.Application</Main-Class>`
`</properties>`

Can this be related?

**Comment by snicoll** [comment]
You're building a `war` right? Does it work when you deploy it in a local tomcat?

**Comment by ashwgupt** [comment]
I've been trying both, war and jar, and the behaviour has been same for both when pushing to CF.

The app launches nicely and neatly on my local embedded tomcat using eclipse. It works all fine be run as jar or war.

**Comment by ashwgupt** [comment]
Further to add - If the tomcat dependency is completely removed from POM, the application simply fails to start, as it never attempts to download the platform provided Tomcat.

Can it be issue with the CF is handling this particular case?

2016-02-23T14:14:57.70+0000 [App/1]   OUT 2016-02-23 14:14:57.707  INFO 29 --- [           main] edisCloudServiceBeanFactoryPostProcessor : Skipping auto-reconf
iguring beans of type org.springframework.data.redis.connection.
2016-02-23T14:14:57.99+0000 [App/1]   OUT 2016-02-23 14:14:57.993  INFO 29 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-02-23T14:14:58.00+0000 [App/1]   OUT 2016-02-23 14:14:58.006  INFO 29 --- [           main] com.fil.Application                      : Started Application in 2.186 seconds (JVM running for 2.755)
2016-02-23T14:14:58.00+0000 [App/1]   OUT 2016-02-23 14:14:58.008  INFO 29 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@45feab1f: startup date [Tue Feb 23 14:14:56 UTC 2016]; root of context hierarchy                  
2016-02-23T14:14:58.01+0000 [App/1]   OUT 2016-02-23 14:14:58.010  INFO 29 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown                                                                                
2016-02-23T14:14:58.01+0000 [App/1]   ERR
2016-02-23T14:14:58.04+0000 [DEA]     ERR Instance (index 1) failed to start accepting connections

**Comment by wilkinsona** [comment]
> I've been trying both, war and jar, and the behaviour has been same for both when pushing to CF.

A jar file is supposed to be self-contained, so it's never going to use the Platform-provided Tomcat. On the other hand, it should be possible to have a war file deployed to the Platform-provided Tomcat.

> Further to add - If the tomcat dependency is completely removed from POM, the application simply fails to start, as it never attempts to download the platform provided Tomcat.

That sounds like a bug/limitation in the Java buildpack's logic for auto-detecting how the application should be run. I wondered if there was an environment variable that could be set to force a particular type of deployment, but there doesn't seem to be. I may have missed something though. Can you help please @cgfrost and @nebhale?

**Comment by cgfrost** [comment]
We've opened an issue on our tracker for this.

https://www.pivotaltracker.com/story/show/114321345

**Comment by wilkinsona** [comment]
Thanks, @cgfrost. I'm closing this in favour of the issue in the Java buildpack tracker

**Comment by nebhale** [comment]
As you can see in [the documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md), the only way to get an application to run within a buildpack provided Tomcat container is that the application has a `WEB-INF` folder **and** is not a Java Main style application.  Looking at the [Java Main documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-java_main.md) you can see that the likely condition making your application run without the buildpack provided Tomcat container is the existence of a `Main-Class` manifest entry.

Given ambiguity in the submitted artifact, we always favor the Java Main style applications as we view it as the more cloud native style of application.  If you ensure that your artifact is not ambiguous the buildpack will correctly select the proper container type.
