### ISSUE TITLE
OAuth2 method security expression not working with client credentials tokens

### ISSUE THREAD

**Issue by marcioaug** [spring-projects/spring-boot#5193]
In UserInfoTokenService (org.springframework.boot.autoconfigure.security.oauth2.resource)

``` java
private OAuth2Authentication extractAuthentication(Map<String, Object> map) {
...
        UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(
                principal, "N/A", authorities);
        token.setDetails(map);
        return new OAuth2Authentication(request, token);
```

org.springframework.security.oauth2.provide.OAuth2Authentication:

``` java
    public OAuth2Authentication(OAuth2Request storedRequest, Authentication userAuthentication) {
        super(userAuthentication == null ? storedRequest.getAuthorities() : userAuthentication.getAuthorities());
        this.storedRequest = storedRequest;
        this.userAuthentication = userAuthentication;
    }
```

Always sends the userAuthentication , even when the token is obtained by client_crendetials grant type. This causes a fail in OAuth2Authentication

``` java
    public boolean isClientOnly() {
        return userAuthentication == null;
    }
```

Since the userAuthentication will never be null.

**Comment by dsyer** [comment]
I guess `UserInfoTokenServices` is completely not designed to handle client credentials tokens (which seems reasonable on the face of it). Maybe it should fail more spectacularly? Can you explain why you need to do this?

**Comment by edp0** [comment]
I'm facing the same issue, using the following setup : I have an API gateway based on spring cloud netflix / zuul and I need to check if a request is made by an end user or an application (using the client credentials flow). Currently, the `Authentication `is always set as a user authentication.
 Do I need to subclass `UserInfoTokenServices `or could this be fixed in a future version ?

**Comment by snicoll** [comment]
@edp0 as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask your question on StackOverflow.
