### ISSUE TITLE
JarLauncher does not filter as the documentation states.

### ISSUE THREAD

**Issue by jhitt25** [spring-projects/spring-boot#5195]
The JarLauncher blindly attempts to load all files under /lib as if they are JAR files.  The documentation states that the filter is "/lib/*.jar", which is incorrect.  Attempting to place native resources under /lib/native, for instance, results in an IllegalStateException:
`java.lang.IllegalStateException: Unable to open nested entry 'lib/native/testNative.dll'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
`
We cannot relocate the native library as it is being targeted by a specific relative path (unfortunate third-party design choice), so it would be nice if JarLauncher either a) worked as advertised or b) provided a mechanism to configure the filter differently.

**Comment by philwebb** [comment]
We're actually changing the format of executable jars in 1.4 to load items from `boot-inf/lib` so you might things aren't a problem with 1.4.

I don't want to change the logic in 1.3 because people may be relying on the existing behavior.

**Comment by philwebb** [comment]
We need to fix the docs in 1.4 anyway.
