### ISSUE TITLE
DataSourcePublicMetrics does not find data sources in parent context

### ISSUE THREAD

**Issue by shalom938** [spring-projects/spring-boot#5196]
we have a context hierarchy and the data sources are in a parent context.
DataSourcePublicMetrics retrieves DataSource's like that:

```
for (Map.Entry<String, DataSource> entry : this.applicationContext
                .getBeansOfType(DataSource.class).entrySet()) {
```

it does not find the DataSource's in parent contexts,
I had to copy the code and change this line to :

`for (Map.Entry<String, DataSource> entry :                    BeanFactoryUtils.beansOfTypeIncludingAncestors(applicationContext.getBeanFactory(),DataSource.class).entrySet()) { 
`

**Comment by snicoll** [comment]
See #5188

**Comment by wilkinsona** [comment]
This problem has been superseded by the move to Micrometer-based metrics in Boot 2.0
