### ISSUE TITLE
Support overriding Reservoir for DropWizard timers and histograms

### ISSUE THREAD

**Issue by sslavic** [spring-projects/spring-boot#5199]
Spring Boot out of the box collects various metrics and if DropWizard is on the classpath those metrics are available in DropWizard MetricRegistry. Currently, Spring Boot 1.3.2, Timer and Histogram metrics get registered in registry with default Reservoir implementation.

It would be nice to be able to override Reservoir per metric, or at least for a start to be able to override global one.

If it's possible already, please have it documented. If it's not possible, please support it and have it documented.

One different Reservoir I'd like to use is HdrHistogramResetOnSnapshotReservoir, see more details on the use case and that reservoir implementation in https://github.com/dropwizard/metrics/issues/143#issuecomment-85428445 and in https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir/

**Comment by johnrengelman** [comment]
+1

**Comment by lucassaldanha** [comment]
Looks like that the feature of registering a custom Reservoir implementation is planned for their [4.0.0](https://github.com/dropwizard/metrics/milestone/11) release (take a look into https://github.com/dropwizard/metrics/issues/730).

A way to solve that using the current version would be changing `DropwizardMetricServices` to accept a Reservoir implementation as configuration. I thought maybe `MetricsDropwizardAutoConfiguration` can check for the presence of a `Reservoir` bean and use it to configure `DropwizardMetricServices`.

Later, `DropwizardMetricServices` can use the `Reservoir` implementation when creating the Timers, Histograms...

If really desirable, we can aim to allow a custom mapping of metrics and the Reservoir implementation, that will be used for enabling the customization of one Reservoir implementation per metric.

I can give it a shot and try to implement this approach. My only concern is if it is worth it to work on that now and not wait for https://github.com/dropwizard/metrics/issues/730 (that is going to make things easier).

Any opinions on that?

**Comment by johnrengelman** [comment]
I don't think we'll see metrics 4 released anytime soon, so a stop gap measure would be nice.

**Comment by lucassaldanha** [comment]
> I don't think we'll see metrics 4 released anytime soon, so a stop gap measure would be nice.

Well, maybe we can at least have the simple approach of at least specify the Reservoir that should be used when creating Timer and Histogram on DropwizardMetricServices. 

I'm finishing a PR with my proposal. We can discuss and see if it helps.
