### ISSUE TITLE
Revisit condition to create a OAuth2RestTemplate

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5202]
The doc currently states:

> To make your webapp into an OAuth2 client you can simply add @EnableOAuth2Client and Spring Boot will create an OAuth2RestTemplate for you to @Autowire.

That's actually inaccurate. The mere presence of `security.oauth2.client.*` is enough to create the template. If you have those settings on the side in case you want to test OAuth, you can easily become in a situation where OAuth is "half-configured". 

Also, the documentation should clearly explain the impacts of having such template as it is flagged `@Primary` and would replace any vanilla `RestTemplate` that was configured by the user.

**Comment by dsyer** [comment]
Actually there are 2 conditions: one on the `security.oauth2.client.*` properties and one on the classpath (to ensure that OAuth2 is available).

To narrow the condition we would need to detect any intention by the user to have an `OAuth2ClientContext`. One signal for that would be a user config bean with `@EnableOAuth2Client` (or `@EnableOAuth2Sso`). Another would be the use of `@EnableResourceServer` when a `UserInfoTokenServices` was going to be used to validate tokens. There is an existing condition that detects that, so probably it can all work out if the configs are ordered properly.

The `@Primary` thing is strange, but I guess we should keep it for consistency (and document it).

**Comment by dsyer** [comment]
I can't find the discussion now, but I'm sure we talked about it the other day, so this is what I remember: Spring Cloud stopped creating `@Beans` of type `RestTemplate` (the user has to choose to create one, and it will then be enhanced if it is annotated). We should do the same here (if the user creates a `@Bean` of type `OAuth2RestTemplate`, maybe with an annotation, we can enhance it). The `@Primary` thing was a mistake.

**Comment by snicoll** [comment]
I went ahead and removed the 2 lines bean definition. If a user needs that infrastructure, he can create it easily in its own config. 

When #5507 is implemented we should revisit this change to provide something similar for `OAuth2RestTemplate`.
