### ISSUE TITLE
Launch script should make location of .conf File configurable

### ISSUE THREAD

**Issue by uweschaefer** [spring-projects/spring-boot#5203]
[This is about the launch Script of a Spring Boot application.]

For OPS reasons, we have the requirement, that .conf-Files reside apart from the boot-generated jar file in a separate folder.

To achive this, it'd be nice to be able to provide an optional ENV Variable to the launch script, say 'CONF_FOLDER' (that defaults to the jar folder, if not set) to point to the location to look for a .conf file.

**Comment by uweschaefer** [comment]
see PR #5204

**Comment by philwebb** [comment]
Thanks, seems like a sensible addition. We should also update the documentation when this is merged.

**Comment by uweschaefer** [comment]
updated docs.
