### ISSUE TITLE
HTTPS listener with key store / trust store objects created on the fly

### ISSUE THREAD

**Issue by dankraw** [spring-projects/spring-boot#5208]
Hi,

This issue is related to Undertow, as I'm not sure if it's possible in other embedded servlet containers.

Here's the point:
I am looking for a possibility to start an app having an HTTPS listener with key store and trust store created on the fly (in-memory) using some injected private key / certificate, etc. This scenario may be quite important when deploying app on Mesos (having no disk access), or when using [Vault PKI](https://www.vaultproject.io/docs/secrets/pki/). 

In `UndertowEmbeddedServletContainerFactory` we have 
```java
if (getSsl() != null && getSsl().isEnabled()) {
    configureSsl(getSsl(), port, builder);
}
else {
    builder.addHttpListener(port, getListenAddress());
}
```
So, in this step we have one listener added to Undertow already.

However, we can add a **secondary** listener to Undertow (as I can't remove the one previously added using Undertow's `Builder` class), for example: setting `server.ssl.enabled=false`, and then doing some custom configuration like:
```java
@Bean
public EmbeddedServletContainerFactory embeddedServletContainerFactory() {
    UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
    if (properties.isWebSecurityEnabled()) {
        factory.addBuilderCustomizers(builder -> {
            builder.addHttpsListener(properties.getSsl().getPort(), null, sslContextFactory.getSslContext());
            builder.setSocketOption(Options.SSL_CLIENT_AUTH_MODE, SslClientAuthMode.REQUESTED);
        });
    }
    return factory;
}
```

The problem is we have **two listeners**, one of which we would like to get rid of. Plus, we need to have another property to specify `server.port`.

An elegant possibility would be introducing some `SslContextFactory` interface and using it in `configureSsl()` method of `UndertowEmbeddedServletContainerFactory`, that could be easily overridden by a user. Using custom `UndertowEmbeddedServletContainerFactory` is too much in my opinion. :)

What do you guys think - I'm not sure if I miss something, and if there is another way to implement this case?

**Comment by philwebb** [comment]
We could extract the `SslContextFactory` creation to a protected factory method, then you could just subclass `UndertowEmbeddedServletContainerFactory` and override. The downside is you don't get any of our auto-configuration being applied.

I would be tempted to go a slightly more hacky route. You could implement a `UndertowBuilderCustomizer` then use some reflection trickery to get access to the internal `listeners`.

I guess long term, a `SslContextFactory` or `SslContextCustomizer` wouldn't be too bad. Do you have time to put together a pull-request?

**Comment by dankraw** [comment]
Thanks for the feedback, I will be happy to add some contribution - maybe focusing on the `SslContextFactory`/`SslContextCustomizer` thing as this looks like the most pure solution. :)

**Comment by philwebb** [comment]
:+1:

**Comment by philwebb** [comment]
There's now a `SslStoreProvider` that you can use to provide the trust/key stores. You can use a `EmbeddedServletContainerCustomizer` to register it. Let me know if it doesn't work.

**Comment by dankraw** [comment]
Nice! We will look at the new solution, thanks!
