### ISSUE TITLE
SpringBootServletInitializer and Spring 4.2.4.RELEASE

### ISSUE THREAD

**Issue by HagarJNode** [spring-projects/spring-boot#5225]
I made a spring-boot war that runs in a Tomcat using the spring-boot-reference manual and found something puzzling me a lot... 

If I use Spring Boot 1.3.1 and the Spring 4.2.3 version I get the nice Spring Boot ascii and my application starts fine, but shifting to 4.2.4 it looks like my SpringBootServletInitializer isn't called and no ascii is printed. 

Testing both Spring versions with Spring Boot 1.3.2 gives the same result with no running application.

Is there anyone who can confirm the same behavior?

Regards,
Hagar

**Comment by wilkinsona** [comment]
I'm not aware of any problems with `SpringBootServletInitializer` and Spring Framework 4.2.4.RELEASE.

Can you please provide a sample project that demonstrates the behaviour that you've described?

**Comment by HagarJNode** [comment]
Making a test example sure helped - turned out it was a Tomcat configuration issue inside my IntelliJ project that caused the problem - maven build and all the Spring Boot configuration was fine. 

Thanks for your time,
Hagar
