### ISSUE TITLE
Actuator Endpoints should support application/hal+json

### ISSUE THREAD

**Issue by jochenchrist** [spring-projects/spring-boot#5228]
The issue in #2449 with @wilkinsona's commit https://github.com/spring-projects/spring-boot/commit/2109559f37095fd2fcfec4868db8d52fc0c92e59 ensures that all actuator endpoints produce `application/json` format.

However this fails when the consumer asks for `Accept: application/hal+json` or even worse when the `org.springframework.web.servlet.config.annotation.ContentNegotiationConfigurer#defaultContentType` is set to `org.springframework.hateoas.MediaTypes#HAL_JSON` with a `HttpMediaTypeNotAcceptableException`.

In this case the consumer always has to set the `Accept` Header to `application/json`.

I suggest to support `application/hal+json` in the `produces` statements of the actuator `RequestMapping`s.

**Comment by wilkinsona** [comment]
> I suggest to support application/hal+json in the produces statements of the actuator RequestMappings.

I like the end goal but, unfortunately, it's not quite that simple as the endpoints can only produce `application/hal+json` when Spring HATEOAS is on the classpath. Furthermore, some of the endpoints will never produce `application/hal+json` (the Metrics endpoint, for example).

**Comment by otrosien** [comment]
It's also not correct from a purist's POV: You can only say you produce hal-json if what you produce is actually hal-json. ;-) So basically a client, who asks for application/hal+json must be rejected, unless you're saying "we produce hal-json, just without the links"

**Comment by wilkinsona** [comment]
We've discussed this and decided that we don't want to make this change. All of the endpoints can and do return `application/json` so that's what we want them to state that they produce. The added complexity of also accurately accepting `application/hal+json` JSON requests outweighs the benefits.

**Comment by jochenchrist** [comment]
OK, agree.
