### ISSUE TITLE
H2ConsoleAutoConfiguration should support WebServer args

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-boot#5232]
H2's `WebServlet` allows passing init args to `WebServer` via servlet init params. There should be a new property added to `H2ConsoleProperties` to pass these args to the servlet

**Comment by wilkinsona** [comment]
Sounds like a nice enhancement. Pull requests gratefully received.

**Comment by sfussenegger** [comment]
@wilkinsona Pull request gratefully provided. Ignore the first commit listed above, I've merged two commits for the PR

**Comment by philwebb** [comment]
Closing in favor of the PR. Thanks!
