### ISSUE TITLE
Make DefaultErrorAttributes.ERROR_ATTRIBUTE accessible

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#5233]
If not public, then at least protected so subclasses can see it.

Currently anything else that wants to get or set the resolved exception needs to poke around the implementation details.

Most other libraries expose their response attributes, `o.s.w.s.DispatcherServlet`, `o.s.w.f.OncePerRequestFilter`, `j.s.RequestDispatcher`, etc.

**Comment by philwebb** [comment]
Can you use `ErrorAttributes.getError`? The attribute is currently intentionally internal and the `getError` implementation also deals with standard servlet exceptions:

```java
	@Override
	public Throwable getError(RequestAttributes requestAttributes) {
		Throwable exception = getAttribute(requestAttributes, ERROR_ATTRIBUTE);
		if (exception == null) {
			exception = getAttribute(requestAttributes, "javax.servlet.error.exception");
		}
		return exception;
	}
```

**Comment by OrangeDog** [comment]
It happens that in this case I can, but in general I see no reason why I must have an instance of the object in order to get and set the attribute.

It tends to mean I end up needing to create a whole application context to wire them up just to test a single filter or interceptor.

**Comment by wilkinsona** [comment]
> As I pointed out, most other Spring classes expose the attribute names they're using.

The attributes in most other Spring classes aren't considered to be an implementation detail.

> It tends to mean I end up needing to create a whole application context to wire them up just to test a single filter or interceptor.

Why do you need a whole application context? Could you not inject an `ErrorAttributes` mock that returns an appropriate response from calls to `getError()`?

**Comment by OrangeDog** [comment]
I'll phrase it another way then.
Why is the fact that a request attribute is being used considered an implementation detail, when a) it's clear by the naming of the class/methods, and b) no other Spring classes have the same consideration.

By "whole application context" I mean any application context at all.
And if I mocked the DefaultErrorAttributes I wouldn't be testing my interaction with it very well.

**Comment by wilkinsona** [comment]
> Why is the fact that a request attribute is being used considered an implementation detail, when a) it's clear by the naming of the class/methods

The `Attributes` in `ErrorAttributes` refers to the map that's returned from `getErrorAttributes`.

> By "whole application context" I mean any application context at all. And if I mocked the DefaultErrorAttributes I wouldn't be testing my interaction with it very well.

You don't need an application context. See [this test](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/trace/WebRequestTraceFilterTests.java#L169-L184) for one example of testing a filter that uses an `ErrorAttributes` implementation without one.

This test could just has easily been implemented using an `ErrorAttributes` mock without losing anything. The interaction is with the contract of the interface, not the implementation.

**Comment by OrangeDog** [comment]
> The `Attributes` in `ErrorAttributes` refers to the map that's returned from `getErrorAttributes`.

But the `RequestAttributes` in `getErrorAttributes` refers to the request attributes.

> See this test for one example of testing a filter that uses an ErrorAttributes implementation without one.
It doesn't test whether anything is read from `ERROR_ATTRIBUTE` only the standard attribute, and if the standard attribute is used then the servlet container will override the status code to 500.

**Comment by philwebb** [comment]
> But the RequestAttributes in getErrorAttributes refers to the request attributes.

The `ErrorAttributes.getErrorAttributes` method provides access to `RequestAttributes` for implementations to use, but makes no assumptions about how it is used.

I'd rather keep `DefaultErrorAttributes.ERROR_ATTRIBUTE` private to make it clear that we don't encourage people to use it directly.
