### ISSUE TITLE
Upgrade to Hazelcast 3.6

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5237]

**Comment by vpavic** [comment]
@wilkinsona you'll need the fix from #5205.

**Comment by wilkinsona** [comment]
@vpavic Noted. Thank you.

**Comment by vpavic** [comment]
Seems [two](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/test/resources/org/springframework/boot/autoconfigure/cache/hazelcast-specific.xml) config [files](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/test/resources/org/springframework/boot/autoconfigure/hazelcast/hazelcast-specific.xml) were left with 3.5 schema declaration.

Try with this (from project root):

```bash
$ find . -type f -path "*/src/*/resources/*" -name "*hazelcast*.xml" -print0 | xargs -0 sed -i "s/hazelcast-config-3.5.xsd/hazelcast-config-3.6.xsd/g"
```

**Comment by snicoll** [comment]
@vpavic thank you so much, I've fixed that in https://github.com/spring-projects/spring-boot/commit/ebf82e4c20e0205bf2bfcdf299f56e5295ac311f

**Comment by wilkinsona** [comment]
:+1:
