### ISSUE TITLE
EmbeddedMongoAutoConfiguration support for spring.data.mongodb.uri

### ISSUE THREAD

**Issue by jochenchrist** [spring-projects/spring-boot#5257]
Currently `EmbeddedMongoAutoConfiguration` reads the host / port from 

```
spring.data.mongodb.host
spring.data.mongodb.port
```

MongoAutoConfiguration ( `org.springframework.boot.autoconfigure.mongo.MongoProperties#createMongoClient`) also support `spring.data.mongodb.uri`to extract host / port / database / collection.

Please provide support for `spring.data.mongodb.uri` in `EmbeddedMongoAutoConfiguration` if port and host are not explicitly set.

**Comment by philwebb** [comment]
I'm not sure how that would work. I think the embedded `MongodConfigBuilder` only supports `host` and `port`. Can you provide some more details of what the extraction process would look like and what methods should be called on `MongodConfigBuilder`?

**Comment by jochenchrist** [comment]
Sure.

The 

Have a look at ´org.springframework.boot.autoconfigure.mongo.MongoProperties#createMongoClient´ there is a check ´org.springframework.boot.autoconfigure.mongo.MongoProperties#hasCustomAddress´ which returns if there is an explicit host or port set (which is typically not, when using uri format):
```
		try {
			if (hasCustomAddress() || hasCustomCredentials()) {
                                // ...
				return new MongoClient(Arrays.asList(new ServerAddress(host, port)),
						credentials, options);
			}
			// The options and credentials are in the URI
			return new MongoClient(new MongoClientURI(this.uri, builder(options)));
```

In our case with _The options and credentials are in the URI_ the Constructor `com.mongodb.MongoClientURI#MongoClientURI(java.lang.String, com.mongodb.MongoClientOptions.Builder)` does the extraction process to get the serverPart from the URI.

**Comment by wilkinsona** [comment]
@jochenchrist What's your use case for embedded Mongo?

Our expectation is that Embedded Mongo will primarily be used for testing. In such scenarios I'd expect test-specific configuration for the embedded Mongo port to be used. This could be achieved via a test-specific profile and an `application-test.properties` file, for example. We also don't want to duplicate the URI parsing logic, and, even if we did, it feels like it would be confusing to only support for host and port from the uri, particularly as the host has to be a local address.

**Comment by jochenchrist** [comment]
Use case for embedded mongo is testing and mocking the production mongo.

I guess that most people will have to use the uri style configuration for mongo in productive environments to provide additional options to mongo.

Defining the port in the application-test.properties is a valid workaround.

The issue is basicly that MongoAutoConfiguration supports the uri style, while EmbeddedMongoAutoConfiguration does not, which is quite unexpected,

**Comment by wilkinsona** [comment]
@jochenchrist Thanks for the quick reply

> The issue is basicly that MongoAutoConfiguration supports the uri style, while EmbeddedMongoAutoConfiguration does not, which is quite unexpected,

That's actually by design. The URI lets you specify a lot of things that embedded Mongo, or our auto-configuration of it, do not support. The only options that are supported at the host and the port so we feel that it's clearer to require the use of the host and port properties to configure them.

**Comment by fabriziocucci** [comment]
I was about to open an issue but, luckily, I came across this.

> The URI lets you specify a lot of things that embedded Mongo, or our auto-configuration of it, do not support.

@wilkinsona I do understandand that but still, from a user perspective, it is a bit confusing discovering that all of the following work as expected:

```yaml
spring.data.mongodb.database: "..."
spring.data.mongodb.host: "..."
spring.data.mongodb.port: "..."
```

but this doesn't:

```yaml
spring.data.mongodb.uri: "..."
```

Would you guys be open to accept a pull request for a documentation enhancement (specifically [here](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-mongo-embedded))?

**Comment by wilkinsona** [comment]
@fabriziocucci Yes, a pull request to add some extra details to the documentation would be most welcome. Thank you.
