### ISSUE TITLE
Option for maven plugin to not overwrite the final artifact name

### ISSUE THREAD

**Issue by jkirsch** [spring-projects/spring-boot#5258]
This is a small feature request

when building a fat jar with the maven plugin, the bundled jar is attached as a new artifact

[Using the classifier Option](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/RepackageMojo.java#L216)

or the final name is overwritten - when final name is set.

[Using the final name](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/RepackageMojo.java#L220)

It would be nice to have the option to only build the bundled jar but not to overwrite the final name.
Such that a maven install will not upload the fat jar, but the small one.

**Comment by philwebb** [comment]
Something like a `replaceMainArtifact` option.

**Comment by jkirsch** [comment]
Indeed, or a more simpler form of `skipArtifactAttachement` which could work in both cases (classifier and final name) as well.

**Comment by philwebb** [comment]
That's a better name indeed.

**Comment by snicoll** [comment]
The [build helper plugin](http://www.mojohaus.org/build-helper-maven-plugin/usage.html) has an `attach-artifact` goal so how about an `attach` flag on the `Repackage` goal that would be `true` by default?

**Comment by jkirsch** [comment]
I guess `attach` works quite well.
That was my original use case, creating the "fat" jar, but only deploying the "small" jar into a maven repo in one step.
