### ISSUE TITLE
gradle task bootRepackage does not run war task it depends on

### ISSUE THREAD

**Issue by 166MMX** [spring-projects/spring-boot#5259]
executing `./gradlew bootRepackge` without prior execution of `./gradlew build` does not build the same artifact

I have created a small demo project here: `https://github.com/166MMX/bugnest/tree/master/gradle-war-dep-001`

steps to reproduce:

```
git clone https://github.com/166MMX/bugnest.git
cd bugnest/gradle-war-dep-001
# runtime => NPE
./gradlew clean
./gradlew ':wrap' bootRepackage
java -jar wrap/build/lib/wrap.jar

# works
./gradlew ':wrap' build
java -jar wrap/build/lib/wrap.jar

# now works too
./gradlew ':wrap' bootRepackage
java -jar wrap/build/lib/wrap.jar

# list all tasks with task dependencies
./gradlew ':wrap:tasks' --all
```

Listing all tasks makes me wonder about two things:
- the `bootRepackage` task depends on project task `':custom:jar'`
- the `bootRun` task depends on project task `':custom:war'`

Could it be that `bootRepackage` should depend on `':custom:war'` but not on `':custom:jar'`

**Comment by philwebb** [comment]
We've probably not considered the repackage war scenario.

**Comment by 166MMX** [comment]
It might be that this is related to runtime project dependencies that are going to be resolved after the compile "stage".

**Comment by hoeckxer** [comment]
Typo in title: dose should be does
