### ISSUE TITLE
Release process doesn't update spring-boot-dependencies pom.xml properly

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5261]
From @joshiste on Gitter:

> the spring-boot-dependencies 1.4.0.M1 references the 1.4.0.BUILD-SNAPSHOT for the spring-boot-maven-plugin was this on purpose?

**Comment by snicoll** [comment]
Ah, that's a regression from the removal of `spring-boot.version` I am afraid.

**Comment by wilkinsona** [comment]
I have a fix for the XSLT:

```diff
diff --git a/pom.xml b/pom.xml
index 798fd20..701e33b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -195,7 +195,7 @@
        </xsl:template>

        <xsl:template
-               match="m:properties/m:spring-boot.version/text()">
+               match="m:build/m:pluginManagement/m:plugins/m:plugin[m:groupId/text() = 'org.springframework.boot']/m:version/text()">
                <xsl:value-of select="/m:project/m:version/text()"/>
        </xsl:template>
 </xsl:stylesheet>
```

However, I wonder if we should consider a broader change here.

Arguably, this version should have been updated by the Artifactory Maven plugin that runs on Bamboo. It updates all of the versions in the `<dependencyManagement>` section, but doesn't appear to update versions in the `<pluginMangement>` section. This is one of several, mostly minor, problems that we've hit with Artifactory and its Maven and Bamboo integration. It's starting to feel like death by 1000 cuts.

I propose that we rework the release process so that performing a release isn't dependent on the CI infrastructure. While it should be possible to perform a release on the CI servers, it shouldn't be a requirement.

This is somewhat related to #4747. If we change the release process so that it isn't reliant on Artifactory's bamboo integration, it should be possible to split the build up as we see fit, and even use different build systems for different pieces (building our Gradle plugin with Gradle would have some significant benefits).

**Comment by philwebb** [comment]
:(  Perhaps worth moving M2 forward?

**Comment by philwebb** [comment]
Actually we can't because we don't have a framework release. Gahh!

**Comment by philwebb** [comment]
The XSLT probably won't help because it's not run during the release process.

**Comment by wilkinsona** [comment]
> The XSLT probably won't help because it's not run during the release process.

I believe it does run as part of the release process. Here's an excerpt from the logs for 1.4.0.M1:

```
uild	26-Feb-2016 03:49:10	[INFO] --- maven-antrun-plugin:1.7:run (fixup-dependencies-pom) @ spring-boot-build ---
build	26-Feb-2016 03:49:10	[INFO] Executing tasks
build	26-Feb-2016 03:49:10	
build	26-Feb-2016 03:49:10	main:
build	26-Feb-2016 03:49:10	     [xslt] Processing /opt/bamboo-home/xml-data/build-dir/BOOT-PUB-JOB1/spring-boot-dependencies/pom.xml to /opt/bamboo-home/xml-data/build-dir/BOOT-PUB-JOB1/spring-boot-dependencies/pom.xml.new
build	26-Feb-2016 03:49:10	     [xslt] Loading stylesheet <xsl:stylesheet version="2.0"
build	26-Feb-2016 03:49:10	     [xslt] 	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:m="http://maven.apache.org/POM/4.0.0"
build	26-Feb-2016 03:49:10	     [xslt] 	exclude-result-prefixes="m">
build	26-Feb-2016 03:49:10	     [xslt] 
build	26-Feb-2016 03:49:10	     [xslt] 	<xsl:template match="node()|@*">
build	26-Feb-2016 03:49:10	     [xslt] 		<xsl:copy>
build	26-Feb-2016 03:49:10	     [xslt] 			<xsl:apply-templates select="node()|@*" />
build	26-Feb-2016 03:49:10	     [xslt] 		</xsl:copy>
build	26-Feb-2016 03:49:10	     [xslt] 	</xsl:template>
build	26-Feb-2016 03:49:10	     [xslt] 
build	26-Feb-2016 03:49:10	     [xslt] 	<xsl:template
build	26-Feb-2016 03:49:10	     [xslt] 		match="m:properties/m:spring-boot.version/text()">
build	26-Feb-2016 03:49:10	     [xslt] 		<xsl:value-of select="/m:project/m:version/text()"/>
build	26-Feb-2016 03:49:10	     [xslt] 	</xsl:template>
build	26-Feb-2016 03:49:10	     [xslt] </xsl:stylesheet>
build	26-Feb-2016 03:49:11	     [move] Moving 1 file to /opt/bamboo-home/xml-data/build-dir/BOOT-PUB-JOB1/spring-boot-dependencies
build	26-Feb-2016 03:49:11	     [move] Moving 1 file to /opt/bamboo-home/xml-data/build-dir/BOOT-PUB-JOB1/spring-boot-dependencies
build	26-Feb-2016 03:49:11	   [delete] Deleting: /opt/bamboo-home/xml-data/build-dir/BOOT-PUB-JOB1/spring-boot-dependencies/pom.xml.old
build	26-Feb-2016 03:49:11	[INFO] Executed tasks
```

**Comment by philwebb** [comment]
I stand corrected. Perhaps I was getting confused with the Gradle fixup which we always do manually after a release.

**Comment by philwebb** [comment]
I'm reopening this one to remind us to double check the staged release XML before we hit promote.

**Comment by snicoll** [comment]
The pom in `lib-release-local` is correct now:

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<version>1.4.0.M2</version>
</plugin>
```
