### ISSUE TITLE
Upgrade to Solr 5.4

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#5266]
Boot 1.4 M1 ships with a Solr 5.3 while the most recent version is 5.4. Should we upgrade to that?

**Comment by wilkinsona** [comment]
FWIW, I went with 5.3.x as that is what Spring Data Solr builds against. Happy to upgrade to 5.4.x if that makes sense from a Spring Data perspective

**Comment by olivergierke** [comment]
Ah, I see. The examples use 5.4.1 already. That's why I was puzzled. Nothing terribly important, I just wanted to plug a reference for discussion and see whether there were any other reasons playing into this. I'll ping Christoph to see whether we can upgrade Spring Data Solar.

**Comment by wilkinsona** [comment]
Looks like Data Solr is using 5.5 now. We should align.

**Comment by wilkinsona** [comment]
And @snicoll already took care of it in https://github.com/spring-projects/spring-boot/commit/b8bc4f66e5aa78c7906129ffa0d6db5af706c410.
