### ISSUE TITLE
Improve the documentation of the starters

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5267]
Via some feedback from @dcoxall, we could do a better job of documenting the starters. I think we're guilty of assuming that people will look in the poms to figure out what each starter does.

A couple of ideas to improve the documentation:

 - List each starter with a description of what it contains and when you'd use it
 - Add an opinionated section that says if you are building X then you should use starter Y

**Comment by dcoxall** [comment]
:+1: This would be incredibly helpful!

**Comment by snicoll** [comment]
I wonder if we couldn't do something about that on `start.spring.io`?

**Comment by wilkinsona** [comment]
> I wonder if we couldn't do something about that on start.spring.io as well

+1
