### ISSUE TITLE
Client side failover reading configuration from cloud config servers

### ISSUE THREAD

**Issue by uweschaefer** [spring-projects/spring-boot#5270]
[suggestion for enhancement/discussion]

We're using a cloud config server. In order to be resilient to failure of the server, we have multiple instance behind a load balancer. However, in case the load-balancer fails, we'd need some IP-Level failover setup to guarantee access to the config servers.

We were wondering, if it would be easier to allow multiple endpoints for configuration via
spring.cloud.config.uri or a similar property, so that the client can try to configure itself with a secondary uri if the first fails.

Is this something considered of value? if so, we'd like to work on it with a little help.

**Comment by wilkinsona** [comment]
@uweschaefer Unfortunately, this repository is the wrong place for this issue. The Spring Cloud Config Client (and server) is managed in https://github.com/spring-cloud/spring-cloud-config. Please open an issue there.

**Comment by uweschaefer** [comment]
will do. thanks.
