### ISSUE TITLE
Log4J2LoggingSystem.FILTER causes some exceptions to be lost from the log

### ISSUE THREAD

**Issue by shalom938** [spring-projects/spring-boot#5271]
`Log4J2LoggingSystem.beforeInitialize` installs a log4j2 filter that denies all, and removes the filter in initialize method.
if there is a multi profile yaml that contains a typo the application fails and the exception is not logged.
In this case its  `ConfigFileApplicationListener` that fails while the filter is installed, if another listener will fail then its exception will be lost too.

to recreate run `sample.actuator.log4j2.SampleActuatorLog4J2Application` with this `application.yml`:

```
---
spring:
    profiles:
         active: local
---
spring:
    profiles: local
a=test
```

**Comment by shalom938** [comment]
BTW, if there is the same typo in a yaml file but not in a profile then nothing fails and the property does not exist. maybe loading of the yaml property source should fail.

**Comment by snicoll** [comment]
See #2125
