### ISSUE TITLE
upgrade assertj to 3.3.0

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#5272]
now the version is 2.3.0 in 1.4.0.M   http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.3.0

**Comment by wilkinsona** [comment]
As I already explained in the IO Platform issue that you opened, AssertJ 3.x requires Java 8. We want Spring Boot to be compatible with Java 7 so we can't upgrade to 3.3.

You can override the dependency management if you want to use 3.x.
