### ISSUE TITLE
Deprecate our Velocity support as it's deprecated in Spring Framework 4.3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5276]
We also need to tidy up all the deprecation warnings in and around `VelocityAutoConfiguration`.

**Comment by acdcjunior** [comment]
I realise this may not be the best place to ask, but can you provide any link or source to that deprecation of Velocity by Spring 4.3? Is it being deprecated in favor of some other technology?

**Comment by snicoll** [comment]
See [SPR-13235](https://jira.spring.io/browse/SPR-13235)
