### ISSUE TITLE
Make use of new `@GetMapping`, `@PostMapping` etc annotations in Spring Framework 4.3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5277]
They're not available yet. See https://jira.spring.io/browse/SPR-13992 for details.

**Comment by wilkinsona** [comment]
They're now available in the latest snapshots but are proving rather controversial

**Comment by snicoll** [comment]
Are we doing this after all?

**Comment by philwebb** [comment]
I think they're here to stay in the framework so we probably should.
