### ISSUE TITLE
SLF4J ILoggerFactory implementations seem broken with LoggingSystem?

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-boot#5285]
I am looking into what appears to be an issue with LoggingSystem and how the classloader behaves for custom ILoggerFactories. 

The conditions are: an application has a custom ILoggerFactory for Slf4J. Slf4J relies on `StaticLoggerBinder.getSingleton();` to locate the ILoggerFactory. When the runtime classpath is "scanned", Log4J2 is automatically loaded due to static references in the Log4j LoggingSystem. As a result, `StaticLoggerBinder.getSingleton();` always returns the ILoggerFactory instance that belongs to Log4J2 and never the application's.

**Comment by wilkinsona** [comment]
In the absence of the `org.springframework.boot.logging.LoggingSystem` system property being set, `LoggingSystem` will load the implementation that's appropriate for whatever system you have on the classpath.

Have you tried providing a custom `LoggingSystem` using the system property?

**Comment by mmoayyed** [comment]
I did yes but that had no affect, as far as I can tell. SLF4J will always attempted to statically load the native ILoggerFactory that was provided by slf4j-impl module for Log4J2. Never the one I had as in the project. I made sure mine was put into the appropriate package, and this is the configuration that worked perfectly before the addition of spring boot. It may also have something to do with the embedded tomcat container I use to run the executable war. 

My best guess at this point is that because boot's log4j2 logging system has static references to log4j2, that causes the wrong static binder to load first. Somehow. 

I should mention that the only reason I have a custom ILoggerFactory is because I wanted to be able to modify log messages via the factory without writing a specific plugin against the log4j2 API. I may have to do that eventually, but would rather not to.

**Comment by wilkinsona** [comment]
If you have Log4J2 on the classpath and your own `ILoggerFactory` implementation, then the one that's loaded by SLF4J entirely depends on the ordering of the classpath – the first implementation will win. Spring Boot doesn't change that.

I'd strongly recommend against any solution that's reliant on the ordering of the classpath.

**Comment by mmoayyed** [comment]
Thanks, that's what I figured. It does appear to the recommended approach by Slf4J though, but it simply does not work as much as I have tested. I'll likely resort to writing something against log4j2 for now.
