### ISSUE TITLE
DependencyManagementBomTransformation should support multiple values per node

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#5288]
`DependencyManagementBomTransformation` should support multiple values per node because a library could add one, and the user adds another, or two libraries might add them. We know that multiple BOMs can be problematic, but we believe we have a sane set across Spring Cloud / Boot now, so it should be possible to support them all.

**Comment by wilkinsona** [comment]
We are not planning to make any further enhancements to the CLI
