### ISSUE TITLE
Allow `and` based `@ConditionalOnBean`

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5291]
This:

``` java
    static class DevToolsDataSourceCondition extends AllNestedConditions {

        DevToolsDataSourceCondition() {
            super(ConfigurationPhase.REGISTER_BEAN);
        }

        @ConditionalOnBean(DataSource.class)
        static final class DataSourceBean {

        }

        @ConditionalOnBean(DataSourceProperties.class)
        static final class DataSourcePropertiesBean {

        }

    }
```

Could be nicer if `@ConditionalOnBean` had an attribute to pick if all beans or any beans are required.

**Comment by wilkinsona** [comment]
See also #5279 which would possibly change the default

**Comment by philwebb** [comment]
Looking at `SpringBootCondition` I'm not convinced that we should add more complexity.

**Comment by wilkinsona** [comment]
We changed the default in #5279. As part of that, we also discussed and rejected the possibility of providing an attribute that lets you decide if it should be an and or an or.
