### ISSUE TITLE
Allow @ImportAutoConfiguration to be used as a meta-annotation

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5298]
Currently the import selections are only processed and sorted once. We need to allow it to be used multiple times.

**Comment by joshiste** [comment]
What's the difference from doing an `@ImportAutoConfiguration` to adding another deferredImportSelector? Is there maybe an overlap to this [Spring Framework PR](https://github.com/spring-projects/spring-framework/pull/893)?

**Comment by philwebb** [comment]
@joshiste  `@ImportAutoConfiguration` applies the same sorting logic (respecting `@AutoConfigureBefore`/`@AutoConfigureAfter`. I don't think there is overlap with SPR-13583.

**Comment by philwebb** [comment]
Fixed in 47f801d5359ebc1ea9330979e4d2e8188952415a
