### ISSUE TITLE
Define a set of well-known profiles

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-boot#5301]
This idea is inspired by [spring-composed](https://github.com/sbrannen/spring-composed/issues/15). It might be somewhat of a reach but I felt I could bring it up here (too). 

It would be cool if spring-boot would define a set of well-known profiles that can be enabled and disabled to change auto-configuration behavior. This becomes extremely handy if spring-boot based libraries adopt this as well (spring-cloud etc.).

Obvious choices may be "production", "development" and "testing" - which is what we started using in our internal projects. We found out though that it's easier to compose these from profiles with narrower semantics. "standalone" is an example - no external dependencies allowed like databases, queues or AWS.

spring-boot users could then use their bootstrap configuration to compose their "production", "development" and "testing" configurations by including these profiles.

Since the idea is inspired by `spring-compose` it would of course be nice to have composed annotations for these profiles (`@StandaloneConfiguration`, `@TestingBean`, `@ProductionService`, ...)

**Comment by wilkinsona** [comment]
I think this might be a duplicate of, or at least overlap heavily with, #785

**Comment by sfussenegger** [comment]
@wilkinsona you're right, sorry about that. I've added my thoughts to the other ticket.

**Comment by wilkinsona** [comment]
@sfussenegger Thanks
