### ISSUE TITLE
Add channelCacheSize Property etc. to RabbitMQ AutoConfig

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#5302]
In XD/SCSt with high volume, channels can be churned frequently due to the default `channelCacheSize` being 1.

In order to reduce this churn and cache publisher channels, we should expose this as a standard boot property.

Also consider exposing `cacheMode` (CHANNEL or CONNECTION) as well as `connectionCacheSize` and `channelCheckoutTimeout`. 

By default, channels are created on-demand; when the checkout timeout is > 0, the `channelCacheSize` becomes an overall limit on how many channels (per connection) are allowed.

**Comment by snicoll** [comment]
Resolving in favour of the PR #5303
