### ISSUE TITLE
Document how to use io.spring.platform dependencies with Maven/Gradle

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#5308]
I think it would be nice to explicitly document how to use io.spring.platform dependencies with Maven and Gradle.

**Comment by wilkinsona** [comment]
It's already covered in the Platform's documentation: http://docs.spring.io/platform/docs/current/reference/htmlsingle/#getting-started-using-spring-io-platform. If changes are necessary, they should be made there rather than here.

**Comment by marceloverdijk** [comment]
Maybe a reference then form Boot documentation?

Regarding http://docs.spring.io/platform/docs/current/reference/htmlsingle/#getting-started-using-spring-io-platform the Gradle example does not contain Boot at all.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-io/platform/issues/328
