### ISSUE TITLE
IntegrationAutoConfiguration.mbeanServer() called although JMX disabled

### ISSUE THREAD

**Issue by deradam** [spring-projects/spring-boot#5309]
I want to deploy my a Spring Boot application with Spring Integration on WebSphere and we cannot use JMX. Following the manuals I disabled JMX by setting this in my properties:

`spring.jmx.enabled=false`

The JmxAutoConfiguration.class is correctly skipped during the auto configuration process. However the mbeanServer method of the IntegrationAutoConfiguration.class is called and creates an exception. From my understanding this should also be annotated with the condition:

`@ConditionalOnProperty(prefix = "spring.jmx", name = "enabled", havingValue = "true", matchIfMissing = true)`

**Comment by snicoll** [comment]
Indeed and the `new JmxAutoConfiguration().mbeanServer()` looks quite suspicious!

**Comment by snicoll** [comment]
Ouch, that class is doing both general integration stuff _and_ JMX-related stuff.
