### ISSUE TITLE
Support for environment variables with square brackets

### ISSUE THREAD

**Issue by jrglee** [spring-projects/spring-boot#5315]
The ability to define keys in an array format like `service.server[0]=http://server1` is is great when used in conjunction with `@ConfigurationProperties`.

Unfortunately the square brackets are considered special characters for environment variable names.
- When using Docker, I can use the `-e` flag to define `SERVICE_SERVER[0]=http://server1` and it works
- When using Bash's `export` like `export SERVICE_SERVER[0]=http://server1` I get a `not a valid identifier` error
- In Kubernetes I can only set environment variables in the C_IDENTIFIER format with is the regexp `[A-Za-z_][A-Za-z0-9_]*`. There is a related discussion about dashes vs underscores kubernetes/kubernetes#16863

I chatted with @philwebb yesterday about this issue. While I can find other ways to pass those values to the application, i.e.: use an environment variable to define application args and let the entrypoint in Docker take care of it; it would be great if Spring could handle that out-of-the-box. One idea I discussed with Phil is to use double `_` around the index like `SERVICE_SERVER__0__`.

**Comment by philwebb** [comment]
I think this is something we should consider around 2.0 when we try to rationalize relaxed binding.

**Comment by mbhave** [comment]
The new binder supports this by allowing environment variables to be specified using `_` for indexes. For eg: `HOST_0` is equivalent to `host[0]`.

**Comment by mikeloll** [comment]
For anyone interested, here are the release notes for the new data binding:

https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0
