### ISSUE TITLE
YAML Editor with List or Array inside of HashMap Object

### ISSUE THREAD

**Issue by indaduke** [spring-projects/spring-boot#5316]
I'm having an issue when using the Spring YAML Properties Editor when trying to have a configuration where there is a List or and Array under a HashMap Object.

The error I get in the yaml file is "Expecting a 'com.wellsfargo.lendingplatform.web.config.TestObjectWithList' but got a 'Sequence' node"

The error always seems to point back to the object that the HashMap contains.

I made the simple example below to show the issue.  If I'm doing something wrong please let me know, but it appears that this issue only appears in this situation.  If I have the same list objects inside a normal object it works fine.

Object with Map:
```
package com.wellsfargo.lendingplatform.web.config;

import java.util.LinkedHashMap;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties
public class TestMap {
	
	private LinkedHashMap<String, TestObjectWithList> testMap;

	public LinkedHashMap<String, TestObjectWithList> getTestMap() {
		return testMap;
	}

	public void setTestMap(LinkedHashMap<String, TestObjectWithList> testMap) {
		this.testMap = testMap;
	}
	
}
```
Object with List
```
package com.wellsfargo.lendingplatform.web.config;

public class TestObjectWithList {
	private String[] stringList;

	public String[] getStringList() {
		return stringList;
	}

	public void setStringList(String[] stringList) {
		this.stringList = stringList;
	}
}
```
YAML file contents
```
test-map:
  test-list-object:
    string-list:
      - "test"
      - "test"
```

**Comment by snicoll** [comment]
Did you meant to close this?

**Comment by wilkinsona** [comment]
I would guess so. It's been opened here now: https://issuetracker.springsource.com/browse/STS-4335

**Comment by indaduke** [comment]
Yeah sorry I went to the wrong issue tracker.  This was for Spring tool
suite yaml editor.

Thanks for the followup.
