### ISSUE TITLE
1.3.3 + Security + webjars = no cache

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#5317]
As soon as security is enabled in 1.3.3 - webjars are getting cache control to no cache:
`Cache-Control:	no-cache, no-store, max-age=0, must-revalidate`

1.3.3 with security disabled ( love this boot feature) , or 1.3.2 with/without security
`Cache-Control	max-age=31536000`

I tried the following, still no luck in 1.3.3
```
        registry.addResourceHandler( "/webjars/**", "/**/*.js", "/**/*.css", "/**/*.less", "/**/*.png", "/**/*.gif", "/**/*.jpg", "/**/*.map" )
                .addResourceLocations( "classpath:/META-INF/resources/webjars/", "classpath:/static/", "classpath:/public/" )
                .setCachePeriod( ONE_YEAR_SECONDS )
                .resourceChain( true )
                .addResolver( versionResolver );
```
i have the following security:
```
			httpSecurity
					.authorizeRequests()
					// do not run security against opensource jars
					.antMatchers( "/webjars/**" )
					.permitAll()

**Comment by snicoll** [comment]
ping @bclozel @rwinch

**Comment by bclozel** [comment]
It's been fixed in Spring Framework with [SPR-14005](https://jira.spring.io/browse/SPR-14005).
In the meantime, you can disable Spring Security HTTP headers for the relevant path like this:

```java
  @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
                .antMatchers("/webjars/**");
    }
```

**Comment by snicoll** [comment]
Thanks Brian, we will integrate that in the next maintenance release, see #5322

**Comment by rwinch** [comment]
@peterdnight @bclozel 

[The workaround](https://github.com/spring-projects/spring-boot/issues/5317#issuecomment-191656906) is rather aggressive as it disables all security related features for `/webjars/**`. Although not as concise, you are probably better off doing something like:

```java
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.headers()
			.cacheControl().disable()
			.addHeaderWriter(notWebjarsCacheControl())
			.and()
		...
}

private HeaderWriter notWebjarsCacheControl() {
	RequestMatcher webjarsMatcher = new AntPathRequestMatcher("/webjars/**");
	RequestMatcher notWebjarsMatcher = new NegatedRequestMatcher(webjarsMatcher);
	CacheControlHeadersWriter cacheHeader = new CacheControlHeadersWriter();
	return new DelegatingRequestMatcherHeaderWriter(notWebjarsMatcher, cacheHeader);
}
```
