### ISSUE TITLE
Provide LoggingEndpoint

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#5321]
This is driven by discussion in #4486.

I've started some work on a PR but would like to use this issue to discuss the operations this endpoint would provide as well as some implementation details.

This endpoint would be based on Boot's logging abstraction (```LoggingSystem```) and would provide the following operations:

- get a list all known loggers
- get a logger details by its name
- set level for a give logger

ATM ```LoggingSystem``` implementations internally keep their mappings between Boot's ```LogLevel``` and their native log levels. This is used when setting the log levels, which is already supported by logging abstraction. However, with this PR logging abstraction would also need to support ```get``` operations which in turn requires resolution of log levels in other direction (resolve ```LogLevel``` for given native log level).

I've originally considered making the level mappings bi-directional but this isn't possible since the mappings are not one-on-one in ```LogbackLoggingSystem``` and ```JavaLoggingSystem``` (see ```LogLevel.FATAL```). Other idea would be to keep the cache of Boot's ```LogLevel```s for each registered logger. This cache would be initially populated during initialization of ```LoggingSystem```.

@snicoll any thoughts on this?

**Comment by snicoll** [comment]
That is pretty much what I had in mind, a `LoggingEndpoint` that is exposed both via JMX and an MVC endpoint if that's available. The log level is a bit tricky indeed but a bi-directional mapping should be possible in some form. 

I would also expose: 

* The URL of the logging configuration (if any)
* If that's available, a `refresh` operation that would reload the configuration file. Not all logging system supports that so we can react with a proper exception/status code.

**Comment by vpavic** [comment]
> The log level is a bit tricky indeed but a bi-directional mapping should be possible in some form.

@snicoll but how exactly would you resolve ```LogLevel``` from Logback's ```Level.ERROR``` having [this](https://github.com/vpavic/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L69-L70) in mind? Similar is with [JUL](https://github.com/vpavic/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/java/JavaLoggingSystem.java#L55-L56).

> My only concern at this point is time as the roadmap for 1.4 is quite full already.

If your are happy with 3 operations listed in my original message for the initial implementation, I've basically got everything implemented (including tests and configurations) with the exception of this mapping thing. We can expand it with other operations at some later stage.

**Comment by vpavic** [comment]
Here's what I've got so far:
https://github.com/vpavic/spring-boot/tree/logging-endpoint

@snicoll if you think this is the right direction I can create the PR off this branch.

**Comment by snicoll** [comment]
Actually there are similar features in Spring Cloud that we would like to reintegrate here for Spring Boot 2.0. Maybe you could give that a try and let us know what you think?

**Comment by vpavic** [comment]
Thanks for your feedback.

This was also mentioned in #4486, [I've asked](https://github.com/spring-projects/spring-boot/pull/4486#issuecomment-179062391) for a reference to this Spring Cloud feature but received no feedback.

Is [this](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_environment_changes) the feature you are referring to?

**Comment by snicoll** [comment]
partially, I thing @dsyer mentioned another feature but I can't remember right now.

**Comment by dsyer** [comment]
Yes, that's it (coupled with the fact that the /env endpoint accepts a POST).

**Comment by vpavic** [comment]
Are there any plans to support reading the current level of a logger and reloading the default configuration?

**Comment by dsyer** [comment]
No, but there would be no opposition to those features (here or in Spring Cloud). I guess those are arguments for having a dedicated endpoint.

**Comment by vpavic** [comment]
Spring Cloud's ability to react to environment changes is a nice feature, however I don't think it reduces the need and justification for a dedicated logging endpoint just because log levels are a thing that could be updated via ```EnvironmentChangedEvent```s. Other useful logging operations would be harder to fit to this approach.

Personally I don't remember the last time I've worked on a project (other than hobby ones) that didn't require the ability to change the log levels during runtime, since it is a very important tool in troubleshooting, especially once you hit the production environments. And IMO this is something Boot's default ```LogbackLoggingSystem``` is really missing (especially since Log4j2 and JUL enable JMX configuration by default, as noted [here](https://github.com/spring-projects/spring-boot/pull/4486#issuecomment-156689642)) and was motivation for #4486 and subsequently this issue.

**Comment by jgoldhammer** [comment]
Any chance to get this into Spring Boot 1.4? Looks very interesting...

**Comment by snicoll** [comment]
> Any chance to get this into Spring Boot 1.4? Looks very interesting...

No. As we've discussed in this thread, we're aiming at integrating the Spring Cloud feature in 2.0

**Comment by snicoll** [comment]
Closed in favour of #7086 - Thanks @vpavic !
