### ISSUE TITLE
display autoconfiguration report/info on failed application launch

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#5325]
I'm trying to debug an application with a missing bean. The bean in question is supposed to be provided by an autoconfiguration class that's on the classpath and not disabled, but for some reason it's not being registered. Presumably I have some sort of problem with my autoconfiguration conditions or environment, but the resulting `BeanCreationException` aborts the context launch and prevents the output of the autoconfiguration report.

Is there any feasible way to print at least some information out of the report even if the actual context launch fails?

**Comment by snicoll** [comment]
You've tried `--debug` already, right?

**Comment by wilkinsona** [comment]
I hit a similar problem the other day, but I can't remember what I did to make the report unavailable. `--debug` didn't help. Thanks for opening the issue @chrylis.

**Comment by wilkinsona** [comment]
Proposed fix: https://github.com/wilkinsona/spring-boot/tree/gh-5325. We need to decide if this should go in 1.3.x or just in master.
