### ISSUE TITLE
Consistent visibility of configuration classes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5334]
We use a mixture of public, protected and package-private visibility for our configuration classes. Auto-configuration classes are (almost?) all public, but plain configuration classes are a mixture of all three. 

Given that the configuration classes are rarely designed to be extended and that proxying prevents us from making them final, I think we may benefit from making the visibility consistent, and using protected or package-private visibility by default.

Where there is logic in a configuration class that we think is generally useful, we should consider adjusting its visibility or, perhaps better, factoring it out into a separate class that's specifically designed for reuse and, if appropriate, extension.

**Comment by snicoll** [comment]
:+1: 

> Where there is logic in a configuration class that we think is generally useful,

Unfortunately, I don't think that'll be enough: I've seen _crazy_ use cases out there where an app extends our auto-configuration (sometimes for very bad reasons). I am all for making our configuration package-private by default but I don't think we can anticipate how many uses case that would break. 

I'd also document that consistency somewhere to avoid reintroducing inconsistencies later on.
