### ISSUE TITLE
Auto-configure couchbase even if spring-data-couchbase isn't available

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5347]
The initial support for Couchbase in M1 requires Spring Data Couchbase. There is a need to auto-configure a `Bucket` and a `Cluster` for those who are not using the repositories infrastructure: they could only use caching (thought we're not supporting that yet) or spring session (coming soon). 

Some changes are required in `spring-data-couchbase` to separate the "core" infrastructure for the repositories setup. This is work in progress in the [draft/separateConfigConcerns](https://github.com/spring-projects/spring-data-couchbase/tree/draft/separateConfigConcerns) branch.

**Comment by snicoll** [comment]
@wilkinsona if we want to support "core" couchbase use case, we need to add a `dependencyManagement` section for the couchbase SDK:

```
<dependency>
  <groupId>com.couchbase.client</groupId>
  <artifactId>java-client</artifactId>
  <version>2.2.3</version>
</dependency>
```

Any objection?

**Comment by wilkinsona** [comment]
Nope. That exact dependency is already part of the Platform.
