### ISSUE TITLE
Allow Tomcat's minimum threads to be configured via the environment

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5348]
See #5314.

> Tomcat's `AbstractProtocol` also supports configuring the minimum number of spare threads for which we do not have a property.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#5572).

**Comment by izeye** [comment]
@wilkinsona It looks `Comment` button has been pressed instead of `Close issue` button.

**Comment by snicoll** [comment]
@izeye Nope, Andy close this one in favour of a pull request, see #5572

**Comment by snicoll** [comment]
Oh my, I read the comment backwards @izeye sorry 😢

**Comment by izeye** [comment]
@snicoll That's okay 😄
