### ISSUE TITLE
Documentation Flyway property incorrect

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#5352]
The documentation states that the property for setting the baseline version for flyway is
flyway.baseline-version

However, the property that should be used (the previous one is deprecated by flyway) is:
flyway.baselineVersionAsString

**Comment by snicoll** [comment]
which version are you using?

**Comment by hoeckxer** [comment]
I noticed this in 1.3.2.RELEASE, but after checking saw that its currently also the case in the latest 1.4.0 milestone

**Comment by snicoll** [comment]
On a second look, I don't see any problem. Flyway has indeed deprecated the setter that takes a `String` but there is a setter that takes a `MigrationVersion` (and that's what the meta-data advertizes). We've supported that since 1.3.2 (see #4981).
