### ISSUE TITLE
Regression: An empty default spring.log file is still created when the logging.file or logging.path property is set

### ISSUE THREAD

**Issue by apahne** [spring-projects/spring-boot#5356]
I think that we found a regression of #303 

Spring Boot creates /tmp/spring.log

Configuration:
...
logging.config=classpath:logback-qa.xml
...

Spring Boot Version: 1.3.2.RELEASE

**Comment by wilkinsona** [comment]
It's impossible to say without knowing what's in your `logback-qa.xml` file. Please provide a small sample that reproduces the problem.

**Comment by apahne** [comment]
Please disregard this report. It was a mistake on our side. Thanks anyway for the quick reply.
