### ISSUE TITLE
Revisit MetricExportPropertiesConfiguration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5364]
The `MetricExportProperties` bean is a little odd, perhaps there's a better way to do it.

**Comment by snicoll** [comment]
That's also the only `@ConfigurationProperites` type with a `Map` to pojo as far as I know. If we could avoid that, that'd be great.

**Comment by dsyer** [comment]
Using a `Map` of String to POJO is pretty common across all of Spring Cloud.

**Comment by philwebb** [comment]
I was specifically referring to this code:

```java
	@Configuration
	protected static class MetricExportPropertiesConfiguration {

		@Value("${spring.application.name:application}.${random.value:0000}")
		private String prefix = "";

		private String aggregateKeyPattern = "k.d";

		@Bean(name = "spring.metrics.export-org.springframework.boot.actuate.metrics.export.MetricExportProperties")
		@ConditionalOnMissingBean
		public MetricExportProperties metricExportProperties() {
			MetricExportProperties export = new MetricExportProperties();
			export.getRedis().setPrefix("spring.metrics"
					+ (this.prefix.length() > 0 ? "." : "") + this.prefix);
			export.getAggregate().setPrefix(this.prefix);
			export.getAggregate().setKeyPattern(this.aggregateKeyPattern);
			return export;
		}

	}
```

**Comment by dsyer** [comment]
I suppose you could put some of that in a `@PostConstruct`. The reason it's like that, though, is so there's an escape hatch, and the user can provide his own defaults if needed.

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
