### ISSUE TITLE
Using Jetty BasicErrorController doesn't work for PUT/DELETE requests

### ISSUE THREAD

**Issue by kohanyirobert** [spring-projects/spring-boot#5367]
I've noticed that when Spring Boot uses Jetty instead of Tomcat when I do a request on a resource and an exception is thrown on the server side for GET/POST requests the usual JSON formatted error comes back (with the timestamp, error, message, etc. fields), however for PUT/DELETE it's empty. I've tried using a custom `ErrorAttributes` implementation, but it had no effect on this behaviour.

[Minimal working example](https://gist.github.com/kohanyirobert/0b5fbbe151a9956443e2/raw/b282820c6a584a0b78c55b31ef8b33ee331d2bf9/demo.zip).

Unzip it. Do `./gradlew bootRun`. Goto [http://localhost:8080/index.html](http://localhost:8080/index.html). Click the `POST` button to POST to the `/demo` resources (always throws an `IllegalStateException`), the result is `{foo: "bar"}` (supplied by the custom `ErrorAttribute` bean).

Clicking on `PUT` essentially does the same (does a `PUT` to `/demo`) and should result in the same `{foo: "bar"}` value, however nothing is returned, the error response is empty.

Using Tomcat everything works as expected. I've tried it with version `1.3.2.RELEASE` and `1.3.3.RELEASE`.

**Comment by philwebb** [comment]
Thanks for the sample application. It looks like Jetty explicitly only forwards `GET`, `POST` and `HEAD` requests to the error page. See [ErrorHandler](https://github.com/eclipse/jetty.project/blob/jetty-9.3.3.v20150827/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L72).

We'll need to dig a bit more to to work out why, perhaps we'll need a different `Handler`.
