### ISSUE TITLE
Abort all integration tests on test case failure

### ISSUE THREAD

**Issue by tollrakesh** [spring-projects/spring-boot#5370]
Hi,

This issue being opened as an enhancement request. 

I have a spring boot based web application and also have couple of integration tests.

I faced a typical scenario where I had a bug in my code that would trigger a `BeanCreationException` in a particular profile and thus obviously that test case fails.

The problem here is, since the application context wasn't initialized at all, why should other tests sharing the same profile start attempting to re-create the context?

As per Spring's documentation, Spring’s test framework will cache application contexts between tests, to which my understanding is that the context would be re-used for other test cases having the same profile. So, if there is a way to immediately mark other test cases as failed instead of re-attempting to create the context again, it could save a lot of CPU cycles and time.

I originally posted the question on stackoverflow [here](http://stackoverflow.com/questions/35803789/abort-all-spring-boot-integration-tests-on-test-case-failure)

**Comment by wilkinsona** [comment]
Issues for Spring's test framework are managed in [JIRA](http://jira.spring.io/browse/SPR). Please open an issue there.
