### ISSUE TITLE
LogbackLoggingSystem gives wrong hint when logback.configurationFile system property is present

### ISSUE THREAD

**Issue by avallen** [spring-projects/spring-boot#5373]
org.springframework.boot.logging.logback.LogbackLoggingSystem#initialize detects the presence of the system property `logback.configurationFile` which logback itself uses for specification of the location of its configuration file, then warns the user that it is being ignored, suggesting the use of `logging.path`. Correct would be: `logging.config`.

**Comment by snicoll** [comment]
Duplicates #4969
