### ISSUE TITLE
Don't pre-emptively authenticate in JWT keyUri request

### ISSUE THREAD

**Issue by william-tran** [spring-projects/spring-boot#5376]
https://github.com/spring-projects/spring-boot/blob/v1.4.0.M1/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L285

UAA will always check the client for uaa.resource authority if credentials are in the request to uaa/token_key, even if a request with no credentials would return 200, which happens when the verification key is a public key. If we tried the request without authentication first and then retry with credentials only if challenged, we could get around this behaviour in UAA.

**Comment by william-tran** [comment]
FYI the issue on the UAA side will be dealt with as well: https://www.pivotaltracker.com/story/show/115352179

**Comment by wilkinsona** [comment]
Judging by the description, I'm not sure that this is a good idea if it's purely to work around the UAA's behaviour. Possibly requiring two requests (one without credentials and one with) when one would have worked (with credentials) is sub-optimal. Unless there's a pressing need to change this, I'd rather wait for the UAA fix to be available (assuming that it isn't already).

I wonder if @dsyer agrees

**Comment by dsyer** [comment]
The UAA behaviour makes no sense to me, so unless someone can explain it, I'd say we shouldn't do anything. What is the default behaviour of the token key endpoint in a vanilla (no-UAA) auth server? Probably not that complicated - a public key is public.

**Comment by william-tran** [comment]
The UAA fix will be in the next release: https://github.com/cloudfoundry/uaa/commit/5a7b27cdf948a592d021ed23bc2c426fc6c98ca5 I'm fine with waiting for the fix and closing this.
