### ISSUE TITLE
Spring Boot- HikariCP--Class Not Found org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by nandhusriram** [spring-projects/spring-boot#5383]
I am running spring boot 1.3.3 on a external tomcat container , configured to use HikariCP version 2.4.4 with my own datasource definition. I am getting class not found , looking for SLF4J LoggerFactory which is there under my exploded web-inf/lib

<img width="834" alt="screen shot 2016-03-09 at 3 17 16 pm" src="https://cloud.githubusercontent.com/assets/2879342/13655193/3618af48-e623-11e5-8b87-6d03776b4e1c.png">
<img width="937" alt="screen shot 2016-03-09 at 3 16 50 pm" src="https://cloud.githubusercontent.com/assets/2879342/13655194/361a8688-e623-11e5-9178-d2227824553f.png">

**Comment by snicoll** [comment]
I am afraid a screenshot isn't very useful. What is the stracktrace? What is the output of `mvn dependency:list -Dsort`? (if you're using Maven)

**Comment by nandhusriram** [comment]
Here is the stacktrace, FYI I have  the HikariCP under catalina/lib.


Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[HikariCP-2.4.4.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_60]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_60]
        at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_60]
        at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:78) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceBuilder.build(DataSourceBuilder.java:69) ~[spring-boot-autoconfigure-1.3.3.RELEASE.jar:1.3.3.RELEASE]
        at org.januslabs.consul.tester.util.VaultSpelFunctions.datasource(VaultSpelFunctions.java:73) ~[classes/:0.0.1-SNAPSHOT]
        ... 45 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
        ... 54 common frames omitted
++++++++++++++++++++++++++++++++++++


Deps list

[INFO] 
[INFO] The following files have been resolved:
[INFO]    aopalliance:aopalliance:jar:1.0:compile
[INFO]    ch.qos.logback:logback-classic:jar:1.1.5:compile
[INFO]    ch.qos.logback:logback-core:jar:1.1.5:compile
[INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.7.1:compile
[INFO]    com.fasterxml.jackson.core:jackson-core:jar:2.7.1:compile
[INFO]    com.fasterxml.jackson.core:jackson-databind:jar:2.7.1:compile
[INFO]    com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.6.3:compile
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.7.1:compile
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.7.1:compile
[INFO]    com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.1:compile
[INFO]    com.fasterxml:classmate:jar:1.1.0:compile
[INFO]    com.github.stefanbirkner:system-rules:jar:1.16.0:test
[INFO]    com.google.guava:guava:jar:18.0:compile
[INFO]    com.oracle:ojdbc7:jar:12.1.0.2:provided
[INFO]    com.orbitz.consul:consul-client:jar:0.10.0:compile
[INFO]    com.zaxxer:HikariCP:jar:2.4.4:provided
[INFO]    javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO]    javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO]    joda-time:joda-time:jar:2.8.2:compile
[INFO]    junit:junit:jar:4.12:test
[INFO]    org.apache.commons:commons-lang3:jar:3.0:compile
[INFO]    org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.32:provided
[INFO]    org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.32:provided
[INFO]    org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.32:provided
[INFO]    org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.32:provided
[INFO]    org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2.external:asm-all-repackaged:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:class-model:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:config-types:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-api:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-config:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-core:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-locator:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-runlevel:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2-utils:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:hk2:jar:2.4.0-b34:compile
[INFO]    org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO]    org.glassfish.hk2:spring-bridge:jar:2.4.0-b34:compile
[INFO]    org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.core:jersey-client:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.core:jersey-common:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.core:jersey-server:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.ext:jersey-bean-validation:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.ext:jersey-spring3:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.2:compile
[INFO]    org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.2:compile
[INFO]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    org.hamcrest:hamcrest-library:jar:1.3:test
[INFO]    org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO]    org.immutables:value:jar:2.0.16:compile
[INFO]    org.januslabs:consul-starter:jar:0.0.1:compile
[INFO]    org.januslabs:vault-starter:jar:0.0.1:compile
[INFO]    org.javassist:javassist:jar:3.18.1-GA:compile
[INFO]    org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO]    org.jvnet:tiger-types:jar:1.4:compile
[INFO]    org.mockito:mockito-core:jar:1.10.19:test
[INFO]    org.objenesis:objenesis:jar:2.1:test
[INFO]    org.projectlombok:lombok:jar:1.16.6:provided
[INFO]    org.slf4j:jcl-over-slf4j:jar:1.7.16:compile
[INFO]    org.slf4j:jul-to-slf4j:jar:1.7.16:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.16:compile
[INFO]    org.springframework.boot:spring-boot-actuator:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-autoconfigure:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-actuator:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-jersey:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-logging:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-test:jar:1.3.3.RELEASE:test
[INFO]    org.springframework.boot:spring-boot-starter-tomcat:jar:1.3.3.RELEASE:provided
[INFO]    org.springframework.boot:spring-boot-starter-validation:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-web:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot:jar:1.3.3.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-commons:jar:1.0.5.RELEASE:compile
[INFO]    org.springframework:spring-aop:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-beans:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-context:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-core:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-expression:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-test:jar:4.2.5.RELEASE:test
[INFO]    org.springframework:spring-web:jar:4.2.5.RELEASE:compile
[INFO]    org.springframework:spring-webmvc:jar:4.2.5.RELEASE:compile
[INFO]    org.yaml:snakeyaml:jar:1.16:runtime
[INFO]    se.jhaals:vault-java:jar:0.0.1:compile

**Comment by snicoll** [comment]
> FYI I have the HikariCP under catalina/lib.

Well that's the problem then and it has nothing to do with Spring Boot. If you place hikary in that location, it can't see any classes of your application.
