### ISSUE TITLE
Add @Conditional annotation for reusing a Property class attributes/methods

### ISSUE THREAD

**Issue by ByteFlinger** [spring-projects/spring-boot#5390]
Consider the following scenario

A Property class like this (Let's class it MyProperties.class)

```java
@ConfigurationProperties(prefix = "mylib.component")
public class ComponentProperties {
    private Boolean enabled = true;

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
```

And a configuration class
```java
@Configuration
@EnableConfigurationProperties(MyProperties.class)
public class MyConfiguration {

    @Bean
    @ConditionalOnProperty(prefix = "mylib.component.beana", name = "enabled", havingValue = "true", matchIfMissing = true)
    public void createBeanA() {
        ....
    }

    @Bean
    @ConditionalOnProperty(prefix = "mylib.component.beanb", name = "enabled", havingValue = "true", matchIfMissing = true)
    public void createBeanB() {
        ....
    }
}
```

It would be really nice not to have to hardcode the prefix (mylib.component) several times in the @Conditional annotations given that it is already found inside the Property class specified at the top.

I guess I am thinking of something of the sort

```java
@ConditionalOnBeanProperty( propertyClass = MyClass.class, propertyName = "beana.enabled")
```

Which would cause the condition to pass only if `mylib.component.beana.enabled` is true

One could think of going further and being able to omit the `propertyClass = MyClass.class` inthe annotation since it is already specified at the top but that might be complicating things

**Comment by philwebb** [comment]
I'm not personally convinced that we should support this, especially not as a new annotation. I can see the point, but I like the simplicity of the existing annotation.

**Comment by ByteFlinger** [comment]
Actually I have been thinking,  what about adding support on the existing annotation for supplying a properties class instead of a string in the prefix? 

That might be simpler and more concise, something like 

@ConditionalOnProperty(prefix = Component properties.class , name = "beana.enabled", havingValue = "true", matchIfMissing = true)

**Comment by wilkinsona** [comment]
`prefix` would have to be typed as an Object. I'm not keen on that.

Setting `beana.enabled` as the name isn't a good idea as it won't fully support relaxed binding. The prefix really needs to be `mylib.component.beana` as you had in the original properties. That means that just referencing the prefix from your properties class won't work in all cases.

If you want to avoid hardcoding the same value, I think the best bet is to use a constant:

```java
@ConfigurationProperties(ExampleProperties.PREFIX)
static class ExampleProperties {

	public static final String PREFIX = "mylib.component";

	// …

}

@Configuration
static class ExampleConfiguration {

	@ConditionalOnProperty(prefix = ExampleProperties.PREFIX + ".beana", name = "enabled", havingValue = "true", matchIfMissing = true)
	public Foo someFoo() {
		return new Foo();
	}

}
```

**Comment by snicoll** [comment]
I think what would be much more interesting is something that would be strongly linked to `@ConfigurationProperites` somehow. There are cases (maybe a vast majority) where you don't want the value of the environment but what the configuration pojo returns. A typical use case is a an enablity flag that is conditional to other properties.

If we could have a `@ConditionalOnProperty` that would refer to a `@ConfigurationProperties` annotated class we could:

* Read the prefix automatically
* Use the actual `bean` as the source of the property (rather than the _raw_ value in the environment). 
* Relaxed binding would be "irrelevant" since we would use the actual path in the pojo (in case of nested properties).

**Comment by philwebb** [comment]
We have to be a bit careful about triggering early initialization of beans.

**Comment by philwebb** [comment]
I think for now we should leave the existing solution as it is. Perhaps this is something that we can revisit in 2.0 when we start to tighten up the rules for `@ConfigurationProperties`. The main reason that I want to keep it out for now is to keep it clear that `@ConditionalOnProperty` is about testing properties in the `Environment` and `@ConfigurationProperties` are just one way that they could get there.
