### ISSUE TITLE
PID and LOGPATH inconsistency in service script

### ISSUE THREAD

**Issue by Schaka** [spring-projects/spring-boot#5391]
By default: 
the PID is written to `/var/run/\<appname\>/\<appname\>.pid`
the log file(s) is/are written to `/var/log/\<appname\>.log`

From my understanding, this should be unified. Other applications (e.g. apache) also log to `/var/log/\<appname\>/\<logfile\>.log`. It makes sense to not have these inconsistencies in future versions.

**Comment by wilkinsona** [comment]
Here's what the [standard](http://www.pathname.com/fhs/pub/fhs-2.3.html) says:

##### `/var/log`

> Most logs must be written to this directory or an appropriate subdirectory.

##### `/var/run`

> Programs may have a subdirectory of /var/run; this is encouraged for programs that use more than one run-time file.

> /var/run should be unwritable for unprivileged users (root or users running daemons); it is a major security problem if any user can write in this directory.

Given the recommendation against `/var/run` itself being writable I think the default for `PID_FOLDER` makes sense. We only produce a single log file (it's redirected standard out) so there's not much benefit to using an app-specific subdirectory for that one file. There's some cost to changing the default and it would be a breaking change for some. I don't think the minimal benefits are worth it.
