### ISSUE TITLE
grails 3.1.3, war plugin, pathingJar enabled, bootRepackage picks up incorrect output file name

### ISSUE THREAD

**Issue by wboyle01** [spring-projects/spring-boot#5393]
Using grails 3.1.3, with war plugin applied and pathingJar enabled, bootRepackage picks up the name of the last Jar task registered and sets that as the output file for the repackage task and not the war file.

Possible solution could be:

When repackage action occurs, the output file name is generated based upon archive file found for the Jar task matched with the "withJarTask".

**Comment by wilkinsona** [comment]
@wboyle01 I'm not familiar with `pathingJar`. It looks like it might be a jar that uses the manifest to specify the classpath to avoid problems with command-line length on Windows. Correct?

Could you provide a sample project that reproduces the problem?

**Comment by wboyle01** [comment]
@wilkinsona Correct. The pathingJar was used to avoid issues with the command line on Windows. It is a option that can be enabled since grails 3.1.2 and seems to be using the jar tasks. 

Let me work on a sample project and will let you know shortly.

**Comment by wboyle01** [comment]
I have created a sample application that demonstrates the issue. It can be found at: 

https://github.com/wboyle01/issues/tree/master/grails313

**Comment by wilkinsona** [comment]
This is tied into the repackage task trying to be too clever for its own good. Unfortunately, straightening it out is going to have to wait till 1.4 (at the earliest). See #5861 for all of the gory details.
