### ISSUE TITLE
springboot 1.3.2-1.3.3 with thymeleaf , i18n fail

### ISSUE THREAD

**Issue by fabletang** [spring-projects/spring-boot#5398]
the bug involve springboot 1.3.2-1.3.3 1.3.4-snapshot 1.40M1。
thymeleaf fail getting i18n meassge.

ex:
\<p  th:text="#{login.title}">login\</p>

**Comment by snicoll** [comment]
This is very hard for us to help you with so little details. Let me try to guess: it used to work before 1.3.2? Are you aware that, as of 1.3.2, you need to have a `messages.properties` to kick-in i18n support? See [the release announcement for more details](https://spring.io/blog/2016/01/22/spring-boot-1-3-2-released)

**Comment by fabletang** [comment]
This is a compatibility issues.
Anything is right on thymeleaf with springboot 1.3.1. 
The bug happended when I had try to upgrade to springboot 1.3.2/1.3.3.
Thanks.

**Comment by fabletang** [comment]
Sorry.
My fault!
everything is right after I add a messages.properties.
