### ISSUE TITLE
Set URI encoding for embedded containers to UTF-8

### ISSUE THREAD

**Issue by sbuettner** [spring-projects/spring-boot#540]
Please set the default encoding for the embedded containers to UTF-8. Otherwise there are issues with extracting characters like german umlauts from the uri for example when using the @RequestParam annotation. Currently i have to register my own connector customizer:

```
new TomcatConnectorCustomizer() {
  @Override
  public void customize(Connector connector) {
    connector.setURIEncoding("UTF-8");
  }
}
```

**Comment by Farzan6118** [comment]
if you are using MYSQL check the following link:
https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html
