### ISSUE TITLE
Enhance @EntityScan to work for multiple EntityManagerFactories

### ISSUE THREAD

**Issue by andyRokit** [spring-projects/spring-boot#5401]
Spring Boot makes it really easy to include a single, default data source. It auto-configures all the required components (TransactionManager, EntityManagerFactory, JpaVendorAdapter, Datasource...).

The existing @EntityScan is great in that it it allows you to effectively loosely-couple your persistence implementation. Without it, you'd need to hard-code your packagesToScan.
My issue comes when you want to use multiple datasources. It's not that hard to create the beans manually. However, it does have one unfortunate side-effect; it means that we can't use @EntityScan. So we're back to hard-coding the [packagesToScan](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/jpa/LocalContainerEntityManagerFactoryBean.html#setPackagesToScan-java.lang.String...-) parameter.
Would it be possible to do the following:
## Add an annotation for auto-configuring multiple data sources
The annotation should trigger behaviour exactly like Spring Boot does with a single data source, but for multiple data sources.
E.g.
### MyDatasourceConfig.java
```
@Configuration
@EnableDataSource(name = "red", prefix = "my.red", primary = true)
@EnableDataSource(name = "blue", prefix = "my.blue")
```
### application.properties
```
my.red.spring.datasource.username=red_database_user
my.red.spring.jpa.hibernate.ddl-auto=create
my.red.spring.jpa.database=sql-server
...
my.blue.spring.datasource.username=blue_database_user
my.blue.spring.jpa.hibernate.ddl-auto=validate
my.blue.spring.jpa.database=oracle
...
```
Would create the following beans:

- redTransactionManager
- redEntityManagerFactory
- redDatasource
- blueTransactionManager
- blueEntityManagerFactory
- blueDatasource

The @EntityScan could then be enhanced to only configure the primary EntityManager (which should help make this change backwards-compatible with existing code).
An additional parameter: "entityManagerFactoryRef" could be added to specify which EntityManagerFactory to use. E.g.
### MyAppRedConfig.java
```
@Configuration
@EnableJpaRepositories(
	basePackages = { "my.red.data.access" },
	entityManagerFactoryRef = "redEntityManagerFactory",
	transactionManagerRef = "redTransactionManager"
)
 
@EntityScan(
	basePackages = { "my.red.data.model" },
	entityManagerFactoryRef = "redEntityManagerFactory"
)
```
..it'd also be nice if @EnableJpaRepositories was @Repeatable so we don't have to create separate config files for the red and blue datasources, but it's a minor issue.

**Comment by snicoll** [comment]
See #5412 for a somewhat similar request for Redis.

**Comment by snicoll** [comment]
After a careful consideration we've decided not to implement this. That annotation proposal of yours is a mix of configuration key prefix, bean prefix and other bean-related settings. While it sounds appealing on paper, it would be quite hard to implement and probably even harder to keep it consistent with user's customizations.

**Comment by andyRokit** [comment]
You're right.  It doesn't seem clean, does it?

What about:

```
spring.persistence-unit[0].unit-name=red
spring.persistence-unit[0].primary=true
spring.persistence-unit[0].datasource.username=red_database_user
spring.persistence-unit[0].jpa.hibernate.ddl-auto=create
spring.persistence-unit[0].jpa.database=sql-server
...
spring.persistence-unit[1].unit-name=blue
spring.persistence-unit[1].datasource.username=blue_database_user
spring.persistence-unit[1].jpa.hibernate.ddl-auto=validate
spring.persistence-unit[1].jpa.database=oracle
...
```

That would avoid the need for an additional annotation to pick up the different units as well as allowing the DataSourceProperties to be hard-coded (rather than dynamic like my 1st example).

**Comment by philwebb** [comment]
@andyRokit Unfortunately the issue of supporting multiple persistence units throughout the codebase remains. We're primarily worried that supporting and documenting the additional complexity would ultimately cause more problems than benefits.

We're really trying hard to keep Spring Boot simple for 80% of use-cases, and whilst people certainly do occasionally want more than one persistence unit, the majority seem to use just one.

**Comment by andyRokit** [comment]
@philwebb Thanks for the reply!  I understand and agree with the principle of keeping Spring Boot simple.  I just have a question about your comment:

You mention the "issue of supporting multiple persistence units throughout the codebase".  Are you suggesting that this change would have ramifications beyond the auto-configuration of the persistence units?  I had imagined that the Spring Boot-initiated units would look identical to those [created manually](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-use-two-entity-managers).  Am I missing something?

**Comment by philwebb** [comment]
@andyRokit I've not looked too deeply but I assumed there might be some effect on the actuator module. I guess the complexity for users was my primary concern.

**Comment by andyRokit** [comment]
@philwebb Sorry Phil - I wasn't suggesting that we remove the existing property-based method for auto-configuring a single persistence unit.

As I picture it, if they were running a single database, this change would have no effect.
If they are running multiple databases, this chance would simplify the implementation.

**Alternative Suggestion**
If it was possible (and I'm not saying it is) to change the nature of @EntityScan so that it sets the packagesToScan _after_ the persistence unit is initialized then it would allow you to declare your persistence units manually (including naming the beans manually) and still use @EntityScan to inject the packagesToScan into them (assuming that you add the "entityManagerFactoryRef" attribute).

**Apology**
Sorry if these suggestions aren't in line with the correct way of doing things in Spring Boot.  My general thinking is:

- Wiring up one datasource is very, very easy using Spring Boot
- Wiring up multiple datasource is hard and potentially hacky (due to the need to hard-code packagesToScan)
- If Spring Boot can simplify wiring up a single datasource for you, then surely it isn't a million miles away from wiring multiple.

**Comment by snicoll** [comment]
I think what we're trying to say is that if we support multiple datasources, one datasource is just one occurence of such support. It's very easy right now but would become clunky: we would need to move our support for "only a datasource" to "one or more datasource". The first impact is moving all configuration from `spring.datasource.*` to something else. Your suggestion with `@EntityScan` breaks the meta-data as we need a natural place where to harvest the properties that are exposed. 

If we keep the current code for "one datasource" case a new way for several data sources it's worse because you have two ways of doing similar things. And it's not about several datasources anyway but potentially several persistence units (which brings a lot of other issues). 

I agree there's a bit of work to configure multiple datasources (that I tried to summarize [in this sample](https://github.com/snicoll-demos/demo-multi-entity-managers)) but I disagree that it is hacky. 

Having said that, I think there are many ways we could mitigate those use cases: I just don't think that an out-of-the-box full support for several datasources/persistence units is one of them.

**Comment by andyRokit** [comment]
@snicoll I fully appreciate the need for consistency.  I don't like the fact that my suggestion alters the  prefixes.  My first suggestion of the dynamic prefix was pretty awful (as you pointed out)!  I like the `persistence-unit[0]` approach better as it allows the property-syntax to be hard-coded.  I've done my best to keep the syntax as close as possible to the existing one.

With regards support, I'd imagine that all the auto-configuration code would be changed to deal with multiple persistence units.  The single-database syntax would then be interpreted as one instance of the multi-database syntax.

I.e.

```
spring.datasource.username=my_database_user
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=sql-server
```

Would effectively be interpreted as:

```
spring.persistence-unit[0].unit-name=default
spring.persistence-unit[0].primary=true
spring.persistence-unit[0].datasource.username=my_database_user
spring.persistence-unit[0].jpa.hibernate.ddl-auto=create
spring.persistence-unit[0].jpa.database=sql-server
```

..and a common mechanism would handle the auto configuration from there.

As for your example, it creates tight-coupling between the `EntiryManagerFactory` and the entities because of this line:

.packages(Customer.class)

..something which the use of `@EntityScan` avoids.

**Comment by snicoll** [comment]
> The single-database syntax would then be interpreted as one instance of the multi-database syntax.

Yeah well, that's exactly my point. I have _no_ idea how to do that and regardless of the fact that you allow the single datasource use case to remain untouched you have _effectively_ two ways of doing the same thing. And we don't want that (At least I don't).

**Comment by andyRokit** [comment]
You'd just have two different @ConfigurationProperties.  One for the single, one for the multiple.  Something like:

```
@ConfigurationProperties(prefix = "spring")
public class SingleDataSourceProperties
...
private DataSourceProperties datasource;
```

```
@ConfigurationProperties(prefix = "spring")
public class MultipleDataSourceProperties
...
private List<PersistenceUnit> persistenceUnit;

private static class PersistenceUnit {
	private DataSourceProperties datasource;
```

Your configuration would collect them both and create an array of DataSourceProperties.  Everything would be common from that point on.

I understand that the prefixes for the settings would be slightly different.  Surely that's not a rule-breaker though, right?  I mean `spring.jpa.generate-ddl` does pretty much the same thing as `spring.jpa.hibernate.ddl-auto`.
