### ISSUE TITLE
Execute database schema and data sql with different users

### ISSUE THREAD

**Issue by Turbots** [spring-projects/spring-boot#5402]
At our current client, we have the restriction of using two different database users (on Oracle):

- DDL user for schema and table modifications
- DML user for data modifications

It would be very useful to have the option of defining both a DDL user for executing the default schema-{platform}.sql files and a DML user for executing the data-{platform}.sql files.

The application itself should preferably run with the DML user for data modifications.

I know this is an annoying restriction to work with or might seem like a ridiculous request, but this isn't the first client that works this way, the old school DBAs at this place don't really bother with innovation and can't even imagine creating & dropping your database schema every time the application boots, not even on a development environment. :disappointed: 

Would it be appropriate if I create a pull request to add this to Spring Boot myself? Suggestions?

**Comment by snicoll** [comment]
> I know this is an annoying restriction to work with or might seem like a ridiculous request,

It doesn't sound ridiculous to me at all. It looks like you've been looking at this quite extensively already so if you could contribute a PR, we can start from there. Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
@Turbots I've removed the waiting for feedback part for now. Are you going to submit a PR?

**Comment by Turbots** [comment]
I will, I suppose the sooner the better, but do you have some kind of deadlines for these kind of things? This way I can prioritize my work :-)

**Comment by snicoll** [comment]
I am not in a hurry at all, you're the one asking. Don't expect this to be added to 1.4 if you submit a PR after RC1.

**Comment by Turbots** [comment]
Holy smokes, I totally forgot about this request of mine, but I do still need it. Thanks for the much appreciated contribution @eddumelendez , this community is amazing!
