### ISSUE TITLE
Customize the CouchbaseEnvironment

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5403]
The `CouchbaseEnvironment` has plenty of settings that we may want to externalize via `CouchbaseProperties`, something like `spring.couchbase.env.*`. It's not clear at this point which ones we would want to expose.

**Comment by simonbasle** [comment]
As a base for discussion, here is an already filtered list of tunings on the `CouchbaseEnvironment`, divided into 3 categories:

1. **sync API default timeouts**: `queryTimeout`, `viewTimeout`, `kvTimeout`, `connectTimeout` (all millisecond durations, `long`)
2. **I/O perf tuning**: `kvEndpoints`, `viewEndpoints`, `queryEndpoints` (all `int`, number of connections to open for each service)
3. **SSL**: (sslEnabled), `sslKeystoreFile`, `sslKeystorePassword` (`boolean`, `String` and `String` respectively)

`sslEnabled` can be inferred to be true as soon as a property is set for sslKeystoreFile and sslKeystorePassword.
