### ISSUE TITLE
Allow setting the webAllowOthers from the application.properties

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#5416]
I work for different clients and it is handy to have the H2 Console at hand to work with the embedded database. However I use a lot of VMs (using Vagrant for instance) and when accessing the h2console it gives an exception that you cannot connect. Setting the `webAllowOthers` to `true` fixes this.

However it requires to either re-register the bean or define a `BeanPostProcessor` to be able to set this property. If would be nice if we could add `spring.h2.console.web-allow-others=true` (default would be `false) and that it then would be set as an init parameter for the servlet.

**Comment by snicoll** [comment]
Closing in favour of the PR #5417 - @mdeinum if you intend to submit a PR, you don't need to create an issue. Thanks.
