### ISSUE TITLE
Allow to disable core JNDI support

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5419]
Spring Framework `4.3` brings the ability to disable JNDI altogether (see [SPR-14026](https://jira.spring.io/browse/SPR-14026)). 

It would be nice if we could integrate that in Spring Boot somehow, especially in embedded containers where we know JNDI won't be used at all.

**Comment by philwebb** [comment]
Running the tomcat sample it appears that the JNDI property source is not added. The `isDefaultJndiEnvironmentAvailable()` method is called 6 times so I doubt there's much of a performance hit.

**Comment by christopheml** [comment]
I am currently working on a project where I could benefit from this enhancement. When packaged in a war and running on a tomcat server, our application makes around 80 JNDI lookups for logging-related properties, before the application actually starts.

The logs look like this > https://gist.github.com/christopheml/143e32bead7a35ca409fc1e944a5dcda

200ms of unnecessary JNDI lookups isn't that bad, but it's cluttering our logs and we actually don't need JNDI at all for this application.

**Comment by wilkinsona** [comment]
@christopheml Did you look at [SPR-14026](https://jira.spring.io/browse/SPR-14026) that's linked above? You can already disable JNDI using a `spring.properties` file:

>  specify `spring.jndi.ignore=true` in a `spring.properties` file at the root of the Spring library classpath level

This issue is tracking the possibility of somehow doing the automatically when we can be certain that JNDI isn't being used.

**Comment by zhugw** [comment]
Recently I met this problem, that is when I start my app by Application class it's ok  but start it in tomcat , I got below error
```
Caused by: java.lang.IllegalArgumentException: PropertyName must not be empty
	at org.springframework.util.Assert.hasLength(Assert.java:233)
	at org.springframework.boot.origin.PropertySourceOrigin.<init>(PropertySourceOrigin.java:41)
```

because in this case it has this `JndiPropertySource {name='jndiProperties'}`

So I have to disable jndi explicitly by add a spring.properties in classpath with `spring.jndi.ignore=true`

###Background
field_2_zh_name.properties
```
field2ZhNameMap.platform=平台
```
```
@Component
@PropertySource("classpath:field_2_zh_name.properties")
@ConfigurationProperties
@EnableConfigurationProperties
@Data
public class Field2ZhNameProperties {
    private HashMap<String,String> field2ZhNameMap;
}
```

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
