### ISSUE TITLE
ThymeleafProperties fail,  Spring Boot 1.3.3

### ISSUE THREAD

**Issue by ronielhcuervo** [spring-projects/spring-boot#5421]
When i have a property with white spaces after value in application.properties ThymeleafAutoConfiguration fail. 

Example:
 
`spring.thymeleaf.mode=LEGACYHTML5 (white space here)`

I recommend removing the white spaces in the value of properties. One way to handle String manipulations is StringUtils from Spring Framework `org.springframework.util.StringUtils`.

**Comment by snicoll** [comment]
Duplicates  #4106
