### ISSUE TITLE
application.properties loading race condition when multiple on path

### ISSUE THREAD

**Issue by StephenDillon** [spring-projects/spring-boot#5422]
When a spring boot app loads a dependency which contain's a application.properties it creates a race condition where it will load the first one encountered. (In this case it was empty) and you get logging like below (improved by spring-boot issue 3129).
While the file shouldn't be in dependencies it is probably possible to handle this in a better way by warning if there is multiple files detected fairly easily.

```
DEBUG o.s.b.c.c.ConfigFileApplicationListener - Skipped (empty) config file 'classpath:/application.properties'
DEBUG o.s.b.c.c.ConfigFileApplicationListener - Skipped (empty) config file 'classpath:/application.properties' for profile default
```

https://github.com/spring-projects/spring-boot/issues/3129

**Comment by wilkinsona** [comment]
I don't consider this to be a race condition. There's only a single thread involved so there's no race, it's just a classpath ordering problem.

Scanning the entire classpath to find every `application.properties` file can take a long time. Every application would have to pay that cost, even if they only contained a single `application.properties` file. Unfortunately, I think that means that we can't implement your suggestion.

It might be possible for us to further improve the logging, though. For example, rather than looked `classpath:/application.properties` we could perhaps log the actual location of the file, e.g. its URL.

**Comment by StephenDillon** [comment]
Thinking further about this over the weekend what might be sufficient is as you mentioned, updating the logging to log the location rather then just the regex would quickly identify the offending jar.

The class path ordering issue occurred every other pcf deployment/restart

**Comment by wilkinsona** [comment]
> The class path ordering issue occurred every other pcf deployment/restart

That's not good. The ordering should really be consistent. PCF is a special case as it unpacks an executable jar before running it. Have you observed the same variable order locally?

**Comment by StephenDillon** [comment]
Just done some additional testing to ensure i have it right.

Using the STS Boot Dashboard or java -jar on repackaged spring boot jar, it reliably loads the internal application.properties.
On PCF deploy and on all restarts it reliably loads the application.properties in one of our dependencies jars.
However, turning on debug logging caused it to sometimes load the internal application.properties on PCF restarts (about 30% of 10+ restarts) which possibly points to performance having a impact on it. 
(It is a fairly simple micro service which doesn't have anything specific to debug logging)

I can gather additional information if you need or i could try replicate a sample project on github if it would be useful.

**Comment by philwebb** [comment]
I've seen some issues like this before related to the order that files are listed on disk. We've updated the code to sort entries alphabetically now, at least that way any failure should be consistent rather than random.
