### ISSUE TITLE
Use @EnableTransactionManagement(proxyTargetClass = true)

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5423]
We should use `@EnableTransactionManagement(proxyTargetClass = true)` to prevent nasty proxy issues when people aren't using interfaces.

**Comment by snicoll** [comment]
I don't think that's the only one that's involved here. `@EnableCaching` is in the same camps (and probably others). Do we really want to do that switch unconditionally? Maybe we should improve the error message instead?

**Comment by philwebb** [comment]
Switching it on by default shouldn't have any side-effects, especially since cglib is repackaged as part of Spring anyway.

**Comment by olivergierke** [comment]
Unfortunately it has :(. See [SPR-14322](https://jira.spring.io/browse/SPR-14322) for details.

**Comment by philwebb** [comment]
@olivergierke Looks like SPR-14322 isn't going to be fixed in 4.x. I'm still tempted to leave `proxyTargetClass` as the new default. Do you think we need to reconsider that decision?

**Comment by vipseixas** [comment]
I have a web project that uses Spring and needed to make a batch module for it so I decided to go with Spring Boot and reused my services module from the bigger project. The services module has a ton of final methods and does not go well with cglib and it took me 2 days to understand and fix why cglib proxies where being used despite the fact that all services implemented interfaces.

I also tried changing spring.aop.proxy-target-class in properties but it was ignored (#8434).

It seems to me that changing the default was a bad call. It breaks a well known behavior of Spring.

**Comment by chasingpavement111** [comment]
> I have a web project that uses Spring and needed to make a batch module for it so I decided to go with Spring Boot and reused my services module from the bigger project. The services module has a ton of final methods and does not go well with cglib and it took me 2 days to understand and fix why cglib proxies where being used despite the fact that all services implemented interfaces.
> 
> I also tried changing spring.aop.proxy-target-class in properties but it was ignored (#8434).
> 
> It seems to me that changing the default was a bad call. It breaks a well known behavior of Spring.

so what is your reason for spring using cglib proxies despite the fact that all services implemented interfaces... ...i am still trying to figure it out
