### ISSUE TITLE
Redirect stdout of the started Spring Boot application when started via spring-boot-maven-plugin

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#5432]
There is currently no option to redirect the standard output of the started application in the start goal of the spring-boot-maven-plugin. The plugin should provide a parameter to redirect output channels (OUT,ERR) into a file.

**Comment by snicoll** [comment]
isn't that what the logging configuration is supposed to do? Why would you want to duplicate that info in the plugin?

**Comment by mrumpf** [comment]
Yes, my application contains a log4j.properties file and that logs to STDOUT.
So you say that I need to provide a test specific log4j.properties via logging.file and logging.path?

**Comment by snicoll** [comment]
Yes. That's what you would do if you start the app yourself so why should we create yet another mechanism for the plugin. I am really not keen of creating such duplication. Does that make sense?

**Comment by mrumpf** [comment]
OK, I will try that. The issue is that you might be testing a 3rd party application and you would need to extract the logging config file from the JAR file and adapt it to just avoid and redirect console output.

I'm migrating away from a Cargo Tomcat test setup. There was such a property to create a cargo_output.log

**Comment by snicoll** [comment]
I am closing this for now but I am still confused. You could pass a `logging.config` property with whatever configuration file you want and be done with it. I really don't see why you'd need something in the plugin for that.

**Comment by mrumpf** [comment]
Specifying a log4j.properties via parameter logging.config  works except for early init stuff where the logging sub-system has not been initialized.

For example when you specify -Dlog4.debug, the output will be written to stdout (or stderr?), no matter what your logging configuration looks like.

IMHO, in order to catch output from libraries that are not behaving correctly or where the logging framework has not been redirected correctly, the option would still be worth adding....

**Comment by snicoll** [comment]
Sorry, I am not keen on adding yet another way to configure logging.
