### ISSUE TITLE
spring-boot-maven-plugin should dump different classpaths when running in debug mode

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#5433]
When running Maven in debug mode (-X) the `spring-boot-maven-plugin` should dump the classpath. When the parameter testClasspath is set to true, the test classpath should also be dumped.

**Comment by snicoll** [comment]
On a second thought @mrumpf I don't get this. When running maven in debug mode, the output of `"Classpath for forked process: "` will change according to the `testClasspath` property. 

If you're referring to `Dependency collection stats`, this is done by Maven, not by us.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
