### ISSUE TITLE
Add support for repositories that are new in Spring Session 1.2

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#5435]
The ```1.2.0``` is [scheduled for March 31st](https://github.com/spring-projects/spring-session/milestones).

---

**Update:**

Spring Session ```1.2.0.RC1``` [was released](https://spring.io/blog/2016/03/17/spring-session-1-2-0-rc1-released) today, adding support for MongoDB and JDBC based ```SessionRepository``` implementations.

I'd like to contribute auto-configuration for the new features, however this is also dependent on merging the #5158.

**Comment by snicoll** [comment]
@vpavic fyi we are doing this analysis of making sure we use the right version for the components that we integrate so there is no need to create such issue unless there is some more context attached to it. Thanks!

**Comment by vpavic** [comment]
@snicoll the context is that ```1.2.0``` adds support for MongoDB and JDBC based ```SessionRepository``` implementations. It would be nice to have auto-coniguration for those two, and I'd like to contribute however there are 2 prerequisites - this issue, and #5158.

For that reason I thought opening this issue would generate feedback regarding targeted Spring Boot milestone.

**Comment by snicoll** [comment]
@vpavic then say so :) An issue to upgrade to X doesn't tell anything other than upgrading the dependency. Can you update this issue then? Thanks for the reminder for #5158, I meant to look at it for a couple of weeks now.

**Comment by vpavic** [comment]
@snicoll sorry, I should've been more descriptive.
I'll update the opening comment with more details.

**Comment by vpavic** [comment]
This was covered by #5158.
