### ISSUE TITLE
Servlet filter executing twice

### ISSUE THREAD

**Issue by kalyanmulampaka** [spring-projects/spring-boot#5440]
Hi,
I have a spring boot saml application with servlet filters in the application context file. When I run the application I see that the filter instance is created twice and during execution the filter is applied twice for every request.
I tried the workaround - register the bean with my filter and disable it as below. But that did not work.

```
@Bean
public FilterRegistrationBean registration(ServletFilter myFilter) {
    FilterRegistrationBean registration = new FilterRegistrationBean(myFilter);
    registration.setEnabled(false);
    return registration;
} 
```

Any ideas?

Thanks
Kalyan

**Comment by wilkinsona** [comment]
Can you share a sample project that illustrates the problem?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
