### ISSUE TITLE
Default Launch script is Linux only and no warning in docs

### ISSUE THREAD

**Issue by laffer1** [spring-projects/spring-boot#5446]
The spring boot "init.d" startup does not work properly on FreeBSD. While I've found a few other issues that reference not supporting BSD, it is still implied that it works on generic UNIX systems which is not true in the documentation. Please either fix the script or modify the documentation with a warning and preferably a rc.d script that actually works on some BSD systems.

**Comment by wilkinsona** [comment]
The [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-service) currently says:

>  "Spring Boot application can be easily started as Unix/Linux services using either init.d or systemd". 

That's pretty clear, in my opinion.

However, the [previous section](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-install) says:

> it is also possible to make fully executable applications for Unix systems (Linux, OSX, FreeBSD etc). … As long as you are generating ‘fully executable’ jars from your build, and you are not using a custom embeddedLaunchScript, the following techniques can be used

This is misleading as you have to use a custom script on OS X and FreeBSD.
