### ISSUE TITLE
Support for `defaultValue` with the LogBack `SpringPropertyAction`

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-boot#5447]
`<springProperty>` is very useful in LogBack. However currently if a property isn't set in the environment, it takes several lines to set a default value, and requires that the user add in an extra lib to have the capability (Janino lib).

Example:
````
<springProperty scope="context" name="ENABLE_CONSOLE_APPENDER" source="enableConsole"/>
<if condition='isNull("ENABLE_CONSOLE_APPENDER")'>
    <then>
        <property scope="context" name="ENABLE_CONSOLE_APPENDER" value="true"/>
    </then>
</if>
````

I would love it if I could shorten that to:
````
<springProperty scope="context" name="ENABLE_CONSOLE_APPENDER" source="enableConsole" defaultValue="true"/>
````

**Comment by linux-china** [comment]
nice feature :+1:

**Comment by snicoll** [comment]
Closing in favour of the PR #5521
