### ISSUE TITLE
IAE when reading ConditionalOnMissingBean on ArtemisEmbeddedServerConfiguration

### ISSUE THREAD

**Issue by thiagokronig** [spring-projects/spring-boot#5452]
Misusage of `@ConditionalOnMissingBean` on `ArtemisEmbeddedServerConfiguration` throws `IllegalArgumentException` when trying to run Artemis embedded withing Spring Boot.

You can trigger this bug by creating a bare application class annotated with `@EnableAutoConfiguration`, `@EnableJms` and with `spring-boot-starter-artemis` and `org.apache.activemq:artemis-server` in the classpath.

Stacktrace:
```
00:08:45.002 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.jms.artemis.ArtemisEmbeddedServerConfiguration.artemisConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

This is true for 1.3.3.RELEASE and also for current master branch.

**Comment by snicoll** [comment]
There is no dependency management for `artemis-server` which should be a hint that something isn't right. The proper artifact is `artemis-jms-server` and if I add that the project runs fine (BTW, if you have a sample, sharing it next time would speed things up a bit).

I guess `artemis-server` has some classes that trigger the support and it shouldn't really. We should probably add a condition on a class that sits in `artemis-jms-server`.

**Comment by thiagokronig** [comment]
Thank you for clearing that up @snicoll. I confirmed here in my setup your solution and it just works!

I missed the information at the HornetQ page.

Maybe we can add the following information at the [Artemis page](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-activemq).

> If you are using spring-boot-starter-activemq the necessary dependencies to connect to an existing Artemis instance are provided, as well as the Spring infrastructure to integrate with JMS. Adding org.apache.activemq:artemis-jms-server to your application allows you to use the embedded mode.
