### ISSUE TITLE
Support starting/stopping the JAR/WAR file with the Spring Boot Maven plugin

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#5457]
When there is a separate Maven sub-modules with integrations tests which runs after the Maven module where the JAR or WAR file has been created, the classpath has to be re-created for the Spring Boot Maven plugin top work.
There should be an easy way to run the JAR (or WAR) file instead of having to re-assemble the classpath in the integration test Maven sub-module.

I'm currently struggeling with trying to make the classpath of the integration test Maven project look the same as the classpath that has already been assembled as part of the full JAR file.

The Spring Boot Maven plugin should have 2 modes:
- Run the tests in the same location where the full JAR file is packaged: Use the classpath, as defined by the Maven POM of the current project
- Run integration tests as part of another Maven module: Just run the JAR file, that has been built before, no need to specify a classpath because the JAR file contains everything needed to run the application.

**Comment by philwebb** [comment]
Which specific [Spring Boot goals](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/) are you looking to change?

I'm afraid that I haven't done much with multi-module integration tests so it's not particularly clear to me what needs to be done. Are you able to share an example project that shows what you mean?

**Comment by mrumpf** [comment]
Both the start and the stop goals. The current implementation is fine for a single Maven module project where test-cases and the actual code live in the same project.

When you have something like this:

- myboot
 - myboot-app       -- executable jar
 - myboot-citests  -- integration tests
 - ...

When you have one Maven sub-module that creates your executable JAR file and another one where your integration tests are, you are forced to recreate the classpath of your JAR project in order to run the application with the Spring Boot Maven plugin as part of the `myboot-citests`.

I think there should be a second mode, a multi-module mode, where it is possible to specify a `jarFile` instead of a `mainClass`:

````
        <profile>
            <id>CIBOOT</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>1.3.3</version>
                        <executions>
                            <execution>
                                <id>pre-integration-test</id>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>post-integration-test</id>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <maxAttempts>600</maxAttempts>
                            <fork>true</fork>
                            <jarFile>${basedir}\..\myboot-app\target\myboot-app-${project.version}.jar</jarFile>
                            <jvmArguments>-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dlogging.config=${project.basedir}/log4j.properties
                                -Dlog4j.debug -Dspring.profiles.active=ci</jvmArguments>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
````

I do not have a good idea right now how both interfaces could be supported at once. The best solution would probably be to have different goals to avoid mixing parameters which make no sense for one or the other mode. An example would be `<fork>`. In single module mode this makes parameter sense, whereas in multi module mode only "true" would be a reasonable choice.

**Comment by mrumpf** [comment]
I have currently commented out the stop goal and I'm using the Jenkins ProcessTreeKiller feature (https://wiki.jenkins-ci.org/display/JENKINS/ProcessTreeKiller) to get rid of the process at the end of the CI build.
I had some issues with the stop goal and the JMX connection. 2 out of 10 builds just hung and never came back from trying to stop the application. So there might be another issue with the stop code but I cannot reliably reproduce this behavior. I logged on to the Windows server and I was able to connect to the VM using JConsole but even manually executing the shutdown operation did not shutdown the VM. 
In case I have more information on this I will create a new ticket. However a maxAttempt parameter or a timeout for the stop goal would be nice so that the operation does not hang forever.

**Comment by snicoll** [comment]
>  even manually executing the shutdown operation did not shutdown the VM.

There's not much we can do at the level of the plugin I am afraid. You should have something in your context that prevents the context to shutdown gracefully. Calling `close` several times has no effect so a `maxAttempt` won't help either.

**Comment by mrumpf** [comment]
The stop is requested on a forked application, so it should be possible to come back from a remote (RMI) operation when a timeout is reached. Using the PID writer it would even be possible to kill the application as part of the plugin in case it does not react on a normal stop request.

**Comment by mrkambam** [comment]
@mrumpf . I ran into the same use-case as yours. Since spring-boot-maven-plugin doesn't have support for starting/stoping springboot app from arbitary location, I had to research and come up with below pom(thanks to bazaarvoice for plugin) as part of my integration-test module.
<plugin>
                <groupId>com.bazaarvoice.maven.plugins</groupId>
                <artifactId>process-exec-maven-plugin</artifactId>
                <version>0.7</version>
                <executions>
                    <execution>
                        <id>start-service</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <name>service</name>
                            <workingDir>service</workingDir>
                            <waitForInterrupt>false</waitForInterrupt>
                            <healthcheckUrl>http://localhost:8090/health</healthcheckUrl>
                            <arguments>
                                <argument>java</argument>
                                <argument>-jar</argument>
                                <argument>${basedir}/../service/target/spring-embedded-app.jar</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>stop-service</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop-all</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by kenshinji** [comment]
I think this is what we are looking for. @mrumpf

**Comment by snicoll** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
