### ISSUE TITLE
Should CharacterEncodingFilter apply to all assets?

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#5459]
`CharacterEncodingFilter` is auto-configured such that it appends a charset to all resources. The trouble is that this adds charset to resources such as png files. This causes confusion for people debugging their apps.

I've overridden it like below, but wondering if there's a smarter way to address this.

```java

  /**
   * This opts out of adding charset to png resources.
   *
   * <p>By default, {@linkplain CharacterEncodingFilter} adds a charset qualifier to all resources,
   * which helps, as javascript assets include extended character sets. However, the filter also
   * adds charset to well-known binary ones like png. This creates confusing content types, such as
   * "image/png;charset=UTF-8".
   */
  @Bean
  @Order(Ordered.HIGHEST_PRECEDENCE)
  public CharacterEncodingFilter characterEncodingFilter() {
    CharacterEncodingFilter filter = new CharacterEncodingFilter() {
      @Override
      protected boolean shouldNotFilter(HttpServletRequest request) {
        return request.getServletPath().endsWith(".png");
      }
    };
    filter.setEncoding("UTF-8");
    filter.setForceEncoding(true);
    return filter;
  }
```

**Comment by philwebb** [comment]
Relates to #1182

**Comment by philwebb** [comment]
I wonder if we can check if the mime type starts with `IMAGE_`? If not we could definitely provide a property for this.

**Comment by bclozel** [comment]
I've created [SPR-14126](https://jira.spring.io/browse/SPR-14126) to track this.

**Comment by bclozel** [comment]
I've just resolved [SPR-14126](https://jira.spring.io/browse/SPR-14126) as won't fix, as I can't find any way to address this issue (I couldn't even get to a workaround). The only possible solution I can think of involves wrapping/caching responses, just like the `ShallowEtagHeaderFilter` does - but it's a huge performance toll.

I know that the encoding situation has been discussed many times in this bug tracker - and that there is no "sane default" as it all depends on the application, the culture of the app users, etc. Setting the `forceEncoding` option is rather agressive.

Of course, we can discuss further options with the MVC team.

**Comment by bclozel** [comment]
In the meantime, and as suggested by @wilkinsona - I've created and solved [SPR-14240](https://jira.spring.io/browse/SPR-14240), adding options to selectively force encoding on the request only.

I believe changing the defaults in Boot to only use `setForceRequestEncoding(true)` would solve this issue.

**Comment by wilkinsona** [comment]
We need to update the javadoc on `HttpEncodingProperties` to reflect the new behaviour. It's also no longer possible to use `application.properties` to enforce request and response encoding should a user wish to do so.
