### ISSUE TITLE
Add 'token' to the Sanitizer defaults

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#5462]
add `token` to the list of Sanitizer defaults in https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Sanitizer.java#L38

The `TOKEN` part is used in many ENV variables for communicating with tools like Hashicorp Consul, Atlas or Vault, which rely on `VAULT_TOKEN` env variable, for example, as a default place to get the auth token from.  `CONSUL_TOKEN` or `ATLAS_TOKEN` serve a similar purpose when connecting with credentials to those services.

Here is their list for reference - https://www.vaultproject.io/docs/commands/environment.html

**Comment by spencergibb** [comment]
As a workaround you can set `endpoints.configprops.keys_to_sanitize`. Possibly `endpoints.configprops.keys_to_sanitize=password,secret,key,.*credentials.*,vcap_services,token`.

**Comment by aantono** [comment]
I can do that as a short-term fix, but that is not really manageable IMHO, as I would have to do that for not only `configprops`, but also for `env` and all the other endpoints that potentially expose this data.  And I would have to do that in every single application config, and make sure that nothing is missed.  It seems like this would be a better fix, if done in Spring Boot and provided for every use case within by default.

**Comment by spencergibb** [comment]
I agree that `token` would be useful. Just saying, you have a short term workaround.

**Comment by snicoll** [comment]
Also that sanitizer is a convenience. If you can't expose such data, don't and secure accordingly.

**Comment by aantono** [comment]
@snicoll I totally agree with your point, unfortunately with the current Docker style deployments, one would have a very hard time to avoid using ENV variables to pass tokens, passwords, etc, as it is the conventional, defacto recommended way of doing it. :(  So having such an amazing convenience helper is GREAT!!!

**Comment by snicoll** [comment]
I think you misunderstood me. I meant to say that if you don't want to show stuff from `/env`, secure the endpoint accordingly. Or is it showing somewhere else?
