### ISSUE TITLE
Default Tomcat Trusted proxies should contain IPv6 addresses

### ISSUE THREAD

**Issue by jcarvalho** [spring-projects/spring-boot#5468]
When Spring Boot sets up Tomcat's `RemoteIpValve` (so that applications can be run behind a proxy server), it sets up the IP ranges of the proxies that are to be trusted, and provides some sensible defaults, as per [this](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-tomcat-behind-a-proxy-server) section of the documentation.

These defaults however, only specify IPv4 address ranges, requiring manual configuration when the proxy server talks to the application over IPv6.

I stumbled upon this issue when trying to setup NGINX to load-balance between 3 test instances of a Spring Boot application (configured with the `server.use-forward-headers` property set to true), with the following NGINX configuration:

```
upstream foo_backend {
    server localhost:8070;
    server localhost:8080;
    server localhost:8090;
}
```

As the machine was IPv6 capable, NGINX was connecting to the applications using IPv6 (specifically the `0:0:0:0:0:0:0:1` address). As that IP is not in the default range, the `RemoteIpValve` was ignoring the `X-Forwarded-For` headers, and marking every request as coming from the localhost.

Forcing NGINX to connect via IPv4 (by specifying `127.0.0.1` instead of `localhost`) fixed the issue, but it would be nice to have IPv6 support by default.

The full list of Reserved IP addresses can be found in this Wikipedia page (all the default IPv4 addresses are on this list):
https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6

**Comment by wilkinsona** [comment]
We deliberately align with Tomcat's own defaults which do not include IPv6 addresses. We accidentally diverged in the past which caused problems (see #2699). It would appear that we can't please everyone here so I think we should stick with the current approach.
