### ISSUE TITLE
Actuate ChildManagementContext starts on a different EmbeddedServletContainer than the parent

### ISSUE THREAD

**Issue by alwaysastudent** [spring-projects/spring-boot#5474]
I have both Tomcat and Jetty in the class-path. The Jetty libraries are pulled transitively by one of my project dependencies. 

I make sure Tomcat as my embedded servlet container, by explicitly declaring my own TomcatEmbeddedServletContainerFactory bean and configuring the same before the 'EmbeddedServletContainerAutoConfiguration'.

All good so far. The issue starts here

I have spring-boot-actuator in my starters and have the management context listening to a different port. 
When I start the application, the web application context starts with the Tomcat container but the management context starts with Jetty.

When I see in the logs and debug more I could see the ChildManagementContext is created explicitly by the EndpointWebMvcAutoConfiguration and it statically registers the following auto configurations

```
org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(){
final AnnotationConfigEmbeddedWebApplicationContext childContext = new AnnotationConfigEmbeddedWebApplicationContext();
		childContext.setParent(this.applicationContext);
		childContext.setNamespace("management");
		childContext.setId(this.applicationContext.getId() + ":management");
		childContext.register(EndpointWebMvcChildContextConfiguration.class,
				PropertyPlaceholderAutoConfiguration.class,
				EmbeddedServletContainerAutoConfiguration.class,
				DispatcherServletAutoConfiguration.class);
		CloseEventPropagationListener.addIfPossible(this.applicationContext,
				childContext);
		childContext.refresh();
		managementContextResolver().setApplicationContext(childContext);
}
```

The above practice disallows us from adding any of our custom auto configurations up front of them. 
I tried adding my custom configuration which explicitly declares the TomcatEmbeddedServletContainerFactory to the following key in the spring.factories, 

`org.springframework.boot.actuate.autoconfigure.ManagementContextConfiguration=\
custom.EmbeddedContainerAutoConfiguration`

but that won't help either since classes under the above key will deduced as imported configs by the 'ManagementContextConfigurationsImportSelector' for the EndpointWebMvcChildContextConfiguration. 

But these imported configurations are ordered to the last among all the explicitly registered  auto-configurations.
`
org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(BeanDefinitionRegistry){
...
parser.parse(candidates);
Set<ConfigurationClass> configClasses = new LinkedHashSet<ConfigurationClass>(parser.getConfigurationClasses());
...
}
`
Either provide hooks to add auto configurations while creating ChildManagementContext or please fix the ordering.

**Comment by wilkinsona** [comment]
> Either provide hooks to add auto configurations while creating ChildManagementContext or please fix the ordering.

I'm not sure we need to do either of these. It should hopefully be sufficient to look in the parent context for an `EmbeddedServletContainerFactory` bean and add a bean of the same type to the child context.

**Comment by alwaysastudent** [comment]
That works for me. Suggested that for only if someone else wants still the ability to run the child context in a separate container or want to override other such auto configurations.

**Comment by philwebb** [comment]
You might also want to try excluding Jetty to see if it's really need by whatever is pulling it in.

**Comment by philwebb** [comment]
@wilkinsona You marked this as a bug, does that still stand?

**Comment by alwaysastudent** [comment]
It still stands as a bug IMHO. I know I can exclude the jetty and work around but in cases we may not be able to and other times where it is there on the path due to negligence of one of our consumers.

**Comment by wilkinsona** [comment]
@philwebb I still think it's a bug. I've seen cases where Jetty can't be excluded. In such cases, I think  the fact that we use a second container when a different port is used should, wherever possible, be an implementation detail that doesn't affect users.
