### ISSUE TITLE
the groupId and artifactId is too long

### ISSUE THREAD

**Issue by sunlin901203** [spring-projects/spring-boot#5475]
the groupId and artifactId is too long,for example,
`<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>`
why not use 
`<dependency>
        <groupId>org.spring.boot</groupId>
        <artifactId>starter-web</artifactId>
    </dependency>`

**Comment by AlexejK** [comment]
I must ask: too long for what?

**Comment by sunlin901203** [comment]
the word number is too long , spring boot starter web

**Comment by snicoll** [comment]
I am afraid that's not an argument. Modules are always qualified with the project name for consistency and it's a very good thing IMO.

**Comment by AlexejK** [comment]
And what problem does this cause? Currently it seemed to follow a naming convention throughout all of spring projects. 

What issues does this cause in its current state?
