### ISSUE TITLE
Hazelcast Actuator Endpoint

### ISSUE THREAD

**Issue by RobWin** [spring-projects/spring-boot#5478]
Hello,

we have written a Hazelcast Spring Actuator Endpoint which uses the Hazelcast Cluster API to lists all cluster members and to shutdown the Hazelcast instance.

The following endpoint list all members:

`curl http://localhost:8181/management/hazelcast`

The following endpoint shuts the instance down:

`curl http://localhost:8181/management/hazelcast/shutdown`

The shutdown endpoint is interesting when you have to create a heap dump of the current Spring Boot instance and don't want to impact the cluster by an unresponsive member.

Interested in adding such an Hazelcast Endpoint to Spring Boot Actuator directly?

**Comment by RobWin** [comment]
I just saw that Hazelcast 3.6 adds a [REST API for Cluster Management](http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#using-rest-api-for-cluster-management).

The Spring Actuator Hazelcast Endpoint could provide similar API. The charm would be that the Endpoint could be added to [Spring Boot Admin](https://github.com/codecentric/spring-boot-admin).

/cc @joshiste

**Comment by snicoll** [comment]
We're not keen on extending the actuator to add such an endpoint but we're considering adding an `HealthIndicator` for it. Regarding that REST API, we shouldn't duplicate it here, really. Thanks!
