### ISSUE TITLE
Failure to start embedded servlet container does not cleanly destroy ApplicationContext

### ISSUE THREAD

**Issue by ksperling** [spring-projects/spring-boot#5480]
If `EmbeddedWebApplicationContext.startEmbeddedServletContainer` fails to start the embedded servlet container (common case: port is in use because another instance is running), the `ApplicationContext` isn't destroyed cleanly. In particular `destroy()` / `@PreDestroy` isn't called on any beans.

In my particular case this is causing problems because I have a `SmartLifeCycle` bean that starts some threads. Because the bean isn't destroyed those threads aren't stopped, and the process doesn't quit even though the application failed to start and the main thread was terminated by the uncaught exception.

One simple approach to fixing this would be to wrap exceptions thrown in `startEmbeddedServletContainer()` in an `ApplicationContextException`, or having `EmbeddedServletContainerException` derive from that class, as `AbstractApplicationContext` handles those types of startup errors correctly by itself.

**Comment by snicoll** [comment]
See also #5388

**Comment by philwebb** [comment]
At first glace using `ApplicationContextException` seems like a sensible suggestion.

**Comment by philwebb** [comment]
@ksperling I'm having some trouble replicating this issue and working out why/when `@PreDestroy` methods should be called. Usually `startEmbeddedServletContainer` is called early in the lifecycle and before regular beans are created. Perhaps you could provide a sample that shows what you need.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ksperling** [comment]
Just re-tested this using `spring-boot-1.3.5.RELEASE` and the behaviour is still as before.

SmartLifecycle beans are auto-started via DefaultLifecycleProcessor.onRefresh(), which is called from finishRefresh() startEmbeddedServletContainer() is then called from EmbeddedWebApplicationContext.finishRefresh() after super.finishRefresh().

The EmbeddedServletContainerException that results from a startup failure isn't caught in AbstractApplicationContext.refresh() as it only catches BeansException, so destroyBeans() isn't called.

I'll try with the 1.4.x branch.

**Comment by ksperling** [comment]
Using 1.4.0.M3 the behaviour is different. For some reason SpringAllocation.handleRunFailure() gets passed the non-null context in this version, whereas in 1.3.x context was null and so didn't get closed.

It seems to be related to this change: https://github.com/spring-projects/spring-boot/commit/474aed054162b06650f4c4af4e9f47949dfa0f9a

**Comment by snicoll** [comment]
I am confused. Are you saying you can't reproduce the issue with 1.4 anymore?

**Comment by ksperling** [comment]
Yes, it appears to be no longer an issue in 1.4
