### ISSUE TITLE
Wildfly 8.2.1

### ISSUE THREAD

**Issue by ednilsoncampos** [spring-projects/spring-boot#5481]
After deploy in Wildfly Autowired not working in Endpoint.
In the link [spring boot jersey](http://docs.spring.io/spring-boot/docs/1.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-jersey) it is said to configure jersey 2.x you just have to add _spring-boot-starter-jersey_ and register all the endpoints, so you can use @Autowired dependencies. Its ok workin in wildfly, but  if you do this _you can change the mapping by adding @ApplicationPath_ the Autowired not working in Endpoit. I configured so @ApplicationPath("/services").
Thanks.

**Comment by wilkinsona** [comment]
@ednilsoncampos You haven't provide anywhere near enough information to diagnose the problem. It's not even clear why you think this is a problem with Spring Boot rather than Wildfly or your own code. If you'd like us to investigate further, please take the time to provide a small sample application that reproduces the problem.

**Comment by ednilsoncampos** [comment]
Instead of `@Application` for alter url pattern I used `application.properties` and add
`spring.jersey.applicationPath=services`, its workink with wildfly.

**Comment by wilkinsona** [comment]
@ednilsoncampos Thanks for editing the description to provide some more details. I'm pleased to hear you've found a workaround. If you'd like us to investigate the problem when `@ApplicationPath` is used, a sample project that reproduces the problem would still be useful

**Comment by ednilsoncampos** [comment]
The project was created on github follow the [link](https://github.com/ednilsoncampos/spring-boot-wildfly).

**Comment by wilkinsona** [comment]
By default, Wildfly uses RESTEasy as the default JAX-RS implementation. When you deploy your application in Wildfly with its default configuration, you can see RESTEasy getting involved:

```
11:26:43,521 INFO  [org.jboss.resteasy.spi.ResteasyDeployment] (MSC service thread 1-3) Deploying javax.ws.rs.core.Application: class com.example.JerseyConfig
11:26:43,524 INFO  [org.jboss.resteasy.spi.ResteasyDeployment] (MSC service thread 1-3) Adding class resource com.example.Endpoint from Application class com.example.JerseyConfig
```

You need to switch RESTEasy off, either for this one application or for the entire server.

**Comment by ednilsoncampos** [comment]
In another [post](https://github.com/spring-io/platform/issues/305) "I find last night" you talk about add dependencyManagement for jackson-jaxrs-base, jackson-jaxrs-json-provider and jackson-module-jaxb-annotations, dependencyManagement  along with spring.jersey.applicationPath I solved my problem.
Thanks.
