### ISSUE TITLE
Regression in logging System properties with Spring Cloud Config

### ISSUE THREAD

**Issue by shakuzen** [spring-projects/spring-boot#5491]
Related: #5073 

The logging System properties are not being set **when using Spring Cloud Config** and setting properties `logging.file` and `logging.config` in a configuration file in the Spring Cloud Config repository.
This was working with Spring Boot 1.3.2 and Spring Cloud Brixton M4 but has stopped working since Spring Boot 1.3.3. PID is still set, however.

### Tested with

      Spring Boot      | Spring Cloud | Working?
------------------------ | ---------------- | ------------
              1.3.2         |   Brixton.M4  |      Yes
              1.3.3         |   Brixton.M4  |      No
1.3.4.BUILD-SNAPSHOT  |   Brixton.M5  |    No
1.3.4.BUILD-SNAPSHOT  |  Brixton.RC1  |    No

### Expected 

Setting `logging.file` and `logging.config` in Spring Cloud Config for an app should result in System property `LOG_FILE` (and others) being set for that app and therefore usable in Logback configuration.

The custom Logback configuration being used (via `logging.config` from cloud config):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/defaults.xml" />

	<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<encoder>
			<charset>UTF-8</charset>
			<pattern>${FILE_LOG_PATTERN}</pattern>
		</encoder>
		<file>${LOG_FILE}</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<fileNamePattern>${LOG_FILE}.%d{yyyyMMdd}</fileNamePattern>
		</rollingPolicy>
	</appender>

	<root level="INFO">
		<appender-ref ref="FILE" />
	</root>
</configuration>
```

### Actual

Only the `PID` System property is set. `LOG_FILE` is not set and therefore its value becomes `LOG_FILE_IS_UNDEFINED` causing a log file by the same name to become the logging output.

### Additional info

Note that taking Spring Cloud Config out of the picture and setting `logging.file` and `logging.config` in `application.yml` results in the expected behavior (as there are unit tests to prove). I wanted to try writing a unit test that would fail but I was not sure how to simulate properties being loaded from Spring Cloud Config in a unit test. I tried debugging some, but was not able to determine the exact cause of the different behavior when using Spring Cloud Config upon upgrading Spring Boot to 1.3.3+.

#### Spring Cloud Config plain text file support
If the custom logging configuration is added to the configuration repo and served by the config server as a plain text file, the Spring environment properties can be used directly in the file. That is, instead of `${LOG_FILE}` one could directly use `${logging.file}` which will be resolved by the config server for the requested application.

#### Environment properties via springProperty (Logback only)
Since I am using Logback, the `springPropety` tag can be used to remove the need to use System properties and instead use the environment properties directly.

_________

While either of the above workarounds will work with the latest version of Spring Boot, the previously existing functionality has stopped working, and therefore I think it would be best to either document or restore that functionality.

Let me know if the description above is not sufficient. I can try putting together simple projects to reproduce the problem, but there is inherent complexity as it would involve 3 projects (config repo, config server, config client app).

**Comment by philwebb** [comment]
@shakuzen Are you able to share the application you used to test this? It would give us a jumpstart on finding a fix.

**Comment by dsyer** [comment]
The order of the listeners hasn't changed as far as I can tell (bootstrap, configfile, logging). But the logging listener implementation changed a lot between Spring Boot 1.3.0 and 1.3.3, so my guess is the difference is there somewhere. To reproduce the issue without Spring Cloud all you need is an `ApplicationListener<ApplicationEnvironmentPreparedEvent>` that runs before the configfile listener and sets the `logging.file`.

**Comment by wilkinsona** [comment]
> To reproduce the issue without Spring Cloud all you need is an ApplicationListener<ApplicationEnvironmentPreparedEvent> that runs before the configfile listener and sets the logging.file.

@dsyer Was that a suggestion, or have you successfully reproduced the issue? I have been unable to reproduce it with a listener with highest precedence.

**Comment by dsyer** [comment]
Just a suggestion. The other feature of the config client is that it adds a property source with high priority. I'm not sure why that would make a difference.

**Comment by shakuzen** [comment]
Please check the [reproduction repository](https://github.com/shakuzen/boot-issue-5491) I just made. Let me know if anything is unclear. I can usually be reached on Gitter if you mention me.

**Comment by philwebb** [comment]
Thanks for project, I've tracked down the problem.

**Comment by shakuzen** [comment]
@philwebb Thank you so much. Working like a charm now with SNAPSHOTs.
