### ISSUE TITLE
Rename duplicate classes in testutils

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5492]
We needed to duplicate a few classes when we extracted the new test jar but it's easy to accidentally use them. We need to make it clear that these are internal.

**Comment by snicoll** [comment]
If it's about `EnvironmentTestUtils` only maybe we can move it to `spring-test`?

**Comment by philwebb** [comment]
There's already a `TestPropertySourceUtils` so I've tweaked that and used it for `spring-boot` tests. The others are fine because they can use the real one.
