### ISSUE TITLE
MongoPersistentEntityIndexCreator is used event if MongoRepositories are disabled

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#5496]
We can use `spring.data.mongodb.repositories.enabled: false` property to disable Mongo repositories in Boot, but when you annotate any document class with `@Indexed` then context will fail to start due because it won't find Mongo. I think all Mongo related beans should be disabled by this property

**Comment by philwebb** [comment]
I'm not sure that that's a sensible idea. The current property allows you to use regular Mongo but disable repositories. If we change that then it's likely to break existing code.

Why do you have Mongo on your classpath if you don't want to use it?

**Comment by jkubrynski** [comment]
The problem is in tests. I want to exclude Mongo from tests and I can simply do it by specifying this property. However after adding @Indexed it tries to connect to Mongo using default properties. To solve it I need to provide fake MongoDbFactory but it's not very clean solution.

**Comment by philwebb** [comment]
What if you exclude `MongoAutoConfiguration` in your tests? You can do that on both the annotation and using the `spring.autoconfigure.exclude` property.

Another option might be for us to add a `spring.data.mongodb.enabled` property.

**Comment by jkubrynski** [comment]
Great! `spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration` does the job.

I think nice feature would be to have `excludedAutoConfigurations` attribute on `@SpringApplicationConfiguration`. That'll be something simplifying integration testing with Boot.

**Comment by philwebb** [comment]
I tend to often go the other way with tests and use `@ImportAutoConfiguration` to only load the bits I need. There's a bunch of test improvements in 1.4 so I'd rather wait for feedback on those before adding an exclude option.
