### ISSUE TITLE
Deserialising of Set<GrantedAuthority> caused an Unauthorised Access when try to get Credentials from AccessToken

### ISSUE THREAD

**Issue by caelwinner** [spring-projects/spring-boot#5499]
I am having a deserialization issue when my Api is trying to consume a response that is coming from my spring oauth2 server that is exposed by a REST endpoint.
```
@RequestMapping("/user")
public Principal user(Principal user) {
return user;
}
```
In the API App, once it get an access token, next try to get the User details invoking the previous endpoint. it is doing all of this by setting this spring boot configuration:
```
security:
    oauth2:
          resource:
          userInfoUri: http://127.0.0.1:8080/sso/user
```
This is the Json that the API is getting:

```
{  
   "username":"randomUser",
   "password":":>7/1,%G(<pU5?-s?KhQ4KZ_'91w!J",
   "userUUID":"78d545d3-196e-4f8e-a439-2a41cd6048b3",
   "authorities":[  
      {  
         "authority":"ROLE_CLIENT"
      }
   ],
   "accountNonExpired":true,
   "accountNonLocked":true,
   "credentialsNonExpired":true,
   "enabled":true
}
```
So far this is what I found, The API, spring boot security in fact, use UserInfoTokenServices class in order to get that json and convert it to a Map.

```
@Override
public OAuth2Authentication loadAuthentication(String accessToken)
throws AuthenticationException, InvalidTokenException {
Map map = getMap(this.userInfoEndpointUrl, accessToken);
if (map.containsKey("error")) {
this.logger.debug("userinfo returned error: " + map.get("error"));
throw new InvalidTokenException(accessToken);
}
return extractAuthentication(map);
}
```

The extractAuthentication method:

```
private OAuth2Authentication extractAuthentication(Map map) {
Object principal = getPrincipal(map);
List authorities = this.authoritiesExtractor
.extractAuthorities(map);
OAuth2Request request = new OAuth2Request(null, this.clientId, null, true, null,
null, null, null, null);
UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(
principal, "N/A", authorities);
token.setDetails(map);
return new OAuth2Authentication(request, token);
}
```

is extracting the authorities by using the AuthorityExtractor class that create a SimpleGrantedAuthority instance with the Role value
{authority: ROLE_CLIENT}

This feature was working fine until I upgraded Spring Boot to the version 1.3 and remove spring cloud security.

Here you have the dependencies for oauth2 server and api

oauth2 server:

Spring Boot Version=1.2.7.RELEASE
Spring Security Oauth2=2.0.7.RELEASE
Jackson Databind Version=2.4.5

API Server:

Spring Boot Version=1.3.3.RELEASE
Spring Security Oauth2 Version=2.0.9.RELEASE
jackson Databind Version=2.6.5

QUESTION 1: Is the Oauth2 Server producing a valid Json?
QUESTION 2: if the json is valid, why is Spring boot is behaving like this?

**Comment by philwebb** [comment]
Duplicates #5482
