### ISSUE TITLE
The index.html in spring-boot-sample-web-static is in the wrong directory

### ISSUE THREAD

**Issue by saltnlight5** [spring-projects/spring-boot#5504]
The sample provided in spring-boot/spring-boot-samples/spring-boot-sample-web-static has added index.html in src/main/webapps. This happens to pass the SampleWebStaticApplicationTests, but when running the sample, we can't see the home page being served!

A workaround fix is simply move the src/main/webapps/index.html into src/main/resources/public

Hope this helps in improving the samples.

**Comment by philwebb** [comment]
Thanks for reporting, probably a copy-paste error.
