### ISSUE TITLE
UndertowEmbeddedServletContainerFactory with Java config -- Not picking up my values

### ISSUE THREAD

**Issue by nandhusriram** [spring-projects/spring-boot#5515]
I have my spring boot application running  within undertow container and configuration  are done via `UndertowEmbeddedServletContainerFactory` . For example I have access log enabled but its not picking it up , same works if its configured via application.properties.

```java
  @Bean
  public EmbeddedServletContainerFactory embeddedServletContainerFactory() {
    UndertowEmbeddedServletContainerFactory factory=new UndertowEmbeddedServletContainerFactory();
    factory.setAccessLogDirectory(new File(System.getProperty("user.dir")));
    factory.setAccessLogEnabled(true);
    factory.setAccessLogPattern("%I %q %m %h %a %l %u %t \"%r\" %s %b (%D ms) %U \"%{i,Referer}\" \"%{i,Host}\" \"%{i,User-Agent}\" \"%{o,Content-Type}\" \"%{o,Content-Length}\"");
    factory.setBufferSize(16000);
    factory.setBuffersPerRegion(20);
    factory.setDirectBuffers(true);
    factory.setIoThreads(10);
    factory.setWorkerThreads(100);
    factory.addBuilderCustomizers(
        builder -> builder.setServerOption(UndertowOptions.ENABLE_HTTP2, true),
        builder -> builder.setServerOption(UndertowOptions.ENABLE_STATISTICS, true),
        builder -> builder.setServerOption(UndertowOptions.RECORD_REQUEST_START_TIME, true));
         
    return factory;
  }
```

**Comment by philwebb** [comment]
We're going to need a bit more to go on. Any chance you could [share a project](https://github.com/spring-projects/spring-boot-issues) that demonstrates the issue?

**Comment by nandhusriram** [comment]
Yes I could do that , does github url suffice the need?

**Comment by philwebb** [comment]
Yeah, a link to a project on GitHub would be perfect!

**Comment by nandhusriram** [comment]
Thanks https://github.com/januslabs/ansible-http.git

**Comment by philwebb** [comment]
OK, I've got to the bottom if it. Turns out the `ServerProperties` class implements a `EmbeddedServletContainerCustomizer` which is applied to the `EmbeddedServletContainerFactory`. This unfortunately means that the property `server.undertow.accesslog.enabled` is always applied in preference to the one you set yourself.

We probably need to make it a `Boolean` rather than a `boolean` so we can tell when the property has actually been specified.

In the meantime your easiest fix is to add `server.undertow.accesslog.enabled=true` in your `application.properties`.

**Comment by nandhusriram** [comment]
Thanks for the explanation, meanwhile I will add it to application. properties

**Comment by nandhusriram** [comment]
Just to clarify one more thing, does this affect just the access log  enable property or other undertow server properties as well , BTW I just ran a test  again with server.undertow.accesslog.enabled set to true in application , my other properties like logdir , access log pattern are not getting picked from the EmbeddedContainerFactory.

**Comment by philwebb** [comment]
Annoyingly it looks like it effects all of them at the moment :(

**Comment by philwebb** [comment]
Specifically [these lines](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L1056-L1067) should have if not `null` checks.

**Comment by nandhusriram** [comment]
Thanks , I see it now.
