### ISSUE TITLE
MessageChannelMetricWriter and @ExportMetricWriter

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#5517]
The `MessageChannelMetricWriter` `@Bean` in the `MetricsChannelAutoConfiguration` must be marked with the `@ExportMetricWriter`, otherwise it is skipped by the `MetricExportAutoConfiguration`:
````java
@Autowired(required = false)
@ExportMetricWriter
private Map<String, GaugeWriter> writers = Collections.emptyMap();
````
After declaring the former in my own config:
````java
@Bean
public MessageChannel metricsChannel() {
	return new DirectChannel();
}

@Bean
@ExportMetricWriter
public MessageChannelMetricWriter messageChannelMetricWriter() {
	return new MessageChannelMetricWriter(metricsChannel());
}

@Bean
@ServiceActivator(inputChannel = "metricsChannel")
public MessageHandler metricsHandler() {
	return System.out::println;
}
````
The metrics are started to appear in the STDOUT periodically as it is declared by the `MetricExportProperties`.

Also see http://stackoverflow.com/questions/36272482/write-out-spring-boot-metrics-to-stdout-or-aggregator.

**Comment by wilkinsona** [comment]
@artembilan You've labelled this as a regression. Can you please provide some more details? With what version did it work correctly?

**Comment by artembilan** [comment]
Sure @wilkinsona !

That worked prior Spring Boot `1.3`. The `MessageChannelMetricWriter` was declared in the `MetricRepositoryAutoConfiguration`.
Plus the `metricsChannel` has been declared there as well. 
That's why my old answer on SO is pretty simple: http://stackoverflow.com/questions/29627061/subscribe-to-spring-metrics-channel.

Not sure that it was a good idea to declare a channel as an out-of-the-box feature with its own `TaskExecutor`. So, I don't see reason to reinstate it. From one hand we are already far away from `1.2`, from other the Doc clarifies what to do http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-metrics-message-channel-integration:

> If a MessageChannel bean called metricsChannel exists, 
 
I think `MetricExportAutoConfigurationTests#defaultExporterWhenMessageChannelAvailable()` should ensure that `MessageChannelMetricWriter` is present in the `MetricExporters`.

**Comment by khoubyari** [comment]
Thank you. I will update my sample project and confirm when I upgrade it: https://github.com/khoubyari/spring-boot-metrics

**Comment by artembilan** [comment]
@philwebb I wonder what was wrong with my PR on the matter #5525 ...

**Comment by wilkinsona** [comment]
@artembilan Sorry, I would guess Phil probably just forgot about it.

However, one thing that was wrong with it was that the change was against `master` whereas the issue needed to be fixed in `1.3.x`. Boot doesn't cherry-pick fixes backwards, instead we fix them in the oldest version where the fix is needed and then merge them forwards (more info [here](https://github.com/spring-projects/spring-boot/wiki/Working-with-Git-branches)). Sometimes it's easier to redo a change in 1.3.x rather than dealing with merge conflicts while trying to move the change to the correct branch.

**Comment by artembilan** [comment]
Thank you, @wilkinsona !

That's great explanation and really helpful for my future fixes for Boot, rather than just silent ignore :wink:

**Comment by philwebb** [comment]
@artembilan Damn, I totally missed the PR. What a waste of time. Sorry.

**Comment by zhiyli** [comment]
When I run khoubyari example, the stdout only includes a small set of metrics. 

Header: metricName=gauge.response.metrics
Header: id=7bf0b165-8b66-7763-29e8-4eb41a0db89d
Header: timestamp=1492811958295
Payload: Metric [name=gauge.response.metrics, value=56.0, timestamp=Fri Apr 21 17:59:13 EDT 2017]
Header: metricName=counter.status.200.metrics
Header: id=2e698682-7824-facd-f53d-5b3409705875
Header: timestamp=1492811958296
Payload: Metric [name=counter.status.200.metrics, value=1, timestamp=Fri Apr 21 17:59:13 EDT 2017]

Not like the output to the browser, which has far more metrics. 

{"mem":549171,"mem.free":240535,"processors":8,"instance.uptime":5663,"uptime":8776,"systemload.average":-1.0,"heap.committed":497152,"heap.init":524288,"heap.used":256616,"heap":7431168,"nonheap.committed":52928,"nonheap.init":2496,"nonheap.used":52021,"nonheap":0,"threads.peak":19,"threads.daemon":15,"threads.totalStarted":21,"threads":19,"classes":6274,"classes.loaded":6274,"classes.unloaded":0,"gc.ps_scavenge.count":2,"gc.ps_scavenge.time":21,"gc.ps_marksweep.count":1,"gc.ps_marksweep.time":30,"httpsessions.max":-1,"httpsessions.active":0}

Is this expected? How to have all metrics to be print at stdout?

**Comment by snicoll** [comment]
@zhiyli this issue is closed and we don't use the tracker for questions. Join us on Gitter if you want to chat or ask on StackOverflow.
