### ISSUE TITLE
Rename the new `buildInfo` task so that it's namespaced (as much as Gradle permits)

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5518]
It should be `bootBuildInfo` rather than `buildInfo`.

**Comment by snicoll** [comment]
Some [doc update required](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-build-info) as well maybe?

**Comment by wilkinsona** [comment]
The docs are fine as the DSL will be unaffected. We just need to change the name of the task that the DSL creates.
