### ISSUE TITLE
Actuator cannot run on alternate port in WAR deployment

### ISSUE THREAD

**Issue by hoserdude** [spring-projects/spring-boot#552]
In embedded mode, configuring an alternate port for the Actuator management endpoints works fine.  In a WAR deployment, with Tomcat `server.xml` configured with a connector on 8081, you cannot specify this in the application configuration (application.yml)
```
management:
  port: 8081
```
To reproduce, upgrade the `gs-convert-jar-to-war` to RC5 and add the actuator to the depenencies:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
```
The add an application.properties or application.yml to the resources with the configuration above.  

The following stack should appear:
```
2014-03-22 22:22:46.306  INFO 16836 --- [on(2)-127.0.0.1] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@20dd8fd: startup date [Sat Mar 22 22:22:46 PDT 2014]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@c90828
2014-03-22 22:22:46.394  INFO 16836 --- [on(2)-127.0.0.1] .t.TomcatEmbeddedServletContainerFactory : Server initialized with port: 8081
Mar 22, 2014 10:22:46 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 22, 2014 10:22:46 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52
Mar 22, 2014 10:22:46 PM org.apache.catalina.loader.WebappLoader startInternal
SEVERE: LifecycleException 
java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader
```

**Comment by rpomeroy** [comment]
+1 on this.  Need to allow customer to configure the actuator port in our spring-boot based product.  We deliver a single war artifact that is also executable.

**Comment by wilkinsona** [comment]
@rpomeroy If you're deploying a Spring Boot application as a war file to a servlet container, there's no way for Boot to instruct the container to listen on another port. If you want your customer's to be able to configure the actuator's port, you should advise them to run your product as an executable war with `java -jar`.

**Comment by rpomeroy** [comment]
I see your point. But contrary to the "doomed to failure" statements above a compromise is perfectly acceptable and workable. If we could configure the actuator port we can provide guidance to our customer open the port in JBoss. What am I missing here? This seems like a perfectly reasonable thing to have.

**Comment by wilkinsona** [comment]
When you're deploying to JBoss (or any other standalone servlet container for that matter), the ports that are used and how requests received on those ports are routed to the application are totally outside of Boot's control. It may be possible to configure JBoss to open another HTTP port and limit requests on that port to the actuator's endpoints, but the configuration will have to be done in JBoss, not Spring Boot.

**Comment by rpomeroy** [comment]
Right. I'm fine with that. Will the actuator port configuration be respected by spring-boot in the war deployment scenario?

**Comment by wilkinsona** [comment]
The actuator port configuration is respected when you use an embedded container, i.e. it'll work as long as you don't deploy your application to a servlet container.

**Comment by rpomeroy** [comment]
Ah the dangers of posting before coffee. Disregard that last question. It doesn't make sense. As long as the sertlets serving up actuator boot up ok we should be able to manage the whole thing via security configuration externally. "Should" ;-)

**Comment by aayushgupta** [comment]
if there is no way for Boot to trigger external container to run management interfaces on different port, but is there any way to configure the same on external container explicitly. Is it the same way boot configures the embedded container. Is there any documentation to get the insight.

**Comment by dsyer** [comment]
There is no way to get actuator endpoints on a different port with a non-embedded container. Containers just don't work like that. You get JMX though, usually.

**Comment by sunilsamal4commit** [comment]
what is the final solution?and how we can get the actuator details if we are deploying war in external server?

**Comment by snicoll** [comment]
@sunilsamal4commit please review [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
