### ISSUE TITLE
Provide dependency management for more of Selenium

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5520]
Originally raised against the Platform (see spring-io/platform#309), we should probably provide dependency management for (at least) the dependencies of `selenium-htmlunit-driver`.

**Comment by snicoll** [comment]
@wilkinsona would you consider the addition of the drivers (i.e. `selenium-firefox-driver`) a good idea?

**Comment by wilkinsona** [comment]
It's certainly not a bad idea. Anything that's released each time Selenium is released could be included. Proactively adding the drivers for the major browsers seems reasonable to me.
