### ISSUE TITLE
Add Spring MVC load-on-startup configuration property

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5522]
With #5100 we are now exposing a `load-on-startup` property to make sure the application fully initializes on startup. There is no such feature for the regular Spring MVC integration so maybe we should update `DispatcherServletAutoConfiguration` for consistency?

**Comment by philwebb** [comment]
I'm not sure that we should, at least not until someone asks for it with a compelling use-case.

**Comment by snicoll** [comment]
Unless I am missing something, the uses cases that were raised for Jersey are exactly the same here. Having said that, I agree that we don't need to add it unless someone asks for it.

**Comment by snicoll** [comment]
Unless I am missing something, the uses cases that were raised for Jersey are exactly the same here. Having said that, I agree that we don't need to add it unless someone asks for it.

**Comment by snicoll** [comment]
Duplicates #2481
