### ISSUE TITLE
Add description to first line of LoggingFailureAnalysisReporter log

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5526]
https://github.com/spring-projects/spring-boot/issues/4907#issuecomment-198415455

**Comment by wilkinsona** [comment]
I don't mind the end goal, but I don't like the suggestion of including the first line of the description. The analysis is supposed to remove duplication and be easy to read. The suggestion will hurt one or perhaps even both of these.

**Comment by philwebb** [comment]
After some consideration we've decided there's not an easy way to do this. We really want to keep multi-line descriptions.
