### ISSUE TITLE
Use proxyTargetClass in @EnableCaching

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5527]
See https://github.com/spring-projects/spring-boot/issues/5423#issuecomment-197199948

**Comment by Qkyrie** [comment]
Is this supposed to be changed in the tests and sample applications? As far as I know @EnableCaching isn't automatically provided somewhere in a configuration class?

**Comment by snicoll** [comment]
You're absolutely right! Thanks for spotting that. 

@philwebb maybe all we need is a doc update/reminder/warning?
