### ISSUE TITLE
UndertowEmbeddedServletContainerFactory  -- EnableHttp2 - Clarification

### ISSUE THREAD

**Issue by nandhusriram** [spring-projects/spring-boot#5531]
I am running a simple application , Spring Boot Version 1.33, with undertow container and doesn't seem to enabling Http2.
` @Bean
  public EmbeddedServletContainerFactory embeddedServletContainerFactory() {

    UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
    factory.addBuilderCustomizers(
        builder -> builder.setServerOption(UndertowOptions.ENABLE_HTTP2, Boolean.TRUE),
        builder -> builder.setServerOption(UndertowOptions.ENABLE_SPDY, Boolean.TRUE),
        builder -> builder.setServerOption(UndertowOptions.ENABLE_STATISTICS, Boolean.TRUE),
        builder -> builder.setServerOption(UndertowOptions.RECORD_REQUEST_START_TIME, Boolean.TRUE),
        builder -> builder.addHttpListener(11081, "localhost"));
    return factory;
  }
`

I am running my application with xbootclasspath

`java -Xbootclasspath/p:/Users/nandhuAEB/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar  -server -jar ./target/ansible-http-0.0.1.jar
`

When I run curl --http2 -I -k -v https://localhost:11080/ansiblehttp/apis/execute/hello , I am seeing http 1.1

> 

> curl --http2 -I -k -v  https://localhost:11080/ansiblehttp/apis/execute/hello
> *   Trying ::1...
> * Connected to localhost (::1) port 11080 (#0)
> * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate: localhost
> > HEAD /ansiblehttp/apis/execute/hello HTTP/1.1
> > Host: localhost:11080
> > User-Agent: curl/7.48.0
> > Accept: */*
> > 
> < HTTP/1.1 200 OK
> HTTP/1.1 200 OK
> < Connection: keep-alive
> Connection: keep-alive
> < Content-Length: 12
> Content-Length: 12
> < Content-Type: text/plain; charset=UTF-8
> Content-Type: text/plain; charset=UTF-8
> < X-Application-Context: ansible-http:11080
> X-Application-Context: ansible-http:11080
> < Date: Wed, 30 Mar 2016 02:10:20 GMT
> Date: Wed, 30 Mar 2016 02:10:20 GMT

Sample github project is https://github.com/januslabs/ansible-http.git

**Comment by wilkinsona** [comment]
Thanks for the sample project. It works for me:

```
$ curl --http2 -I -k -v https://localhost:11080/ansiblehttp/apis/execute/hello
*   Trying ::1...
* Connected to localhost (::1) port 11080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
* 	 subject: C=US; ST=KS; L=Overland Park; O=Januslabs; OU=IT; CN=localhost
* 	 start date: Mar 29 01:53:45 2016 GMT
* 	 expire date: Jun 27 01:53:45 2016 GMT
* 	 issuer: C=US; ST=KS; L=Overland Park; O=Januslabs; OU=IT; CN=localhost
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb3d980f000)
> HEAD /ansiblehttp/apis/execute/hello HTTP/1.1
> Host: localhost:11080
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/2.0 200
HTTP/2.0 200
< content-length:12
content-length:12
< content-type:text/plain; charset=UTF-8
content-type:text/plain; charset=UTF-8
< x-application-context:ansible-http:11080
x-application-context:ansible-http:11080
< date:Wed, 30 Mar 2016 14:26:09 GMT
date:Wed, 30 Mar 2016 14:26:09 GMT

<
* Connection #0 to host localhost left intact
```

The JVM won't complain and Undertow will fall back to HTTP 1.1 if the jar added to the boot classpath doesn't exist. Are you sure that `/Users/nandhuAEB/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar` is the right path for the ALPN jar?

**Comment by nandhusriram** [comment]
Jar file  is in the correct path , sounds more its my environment issue. Thanks
