### ISSUE TITLE
Add properties alias for `WebIntegrationTest`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5534]
If you need to enable random port and some properties (quite common) you have to do this now

```
@WebIntegrationTest(randomPort = true, value = "spring.jersey.type=filter")
```

It would be nicer if we had something along the lines of

```
@WebIntegrationTest(randomPort = true, properties = "spring.jersey.type=filter")
```

**Comment by philwebb** [comment]
@wilkinsona has done some work on #5477 that will cover this.
