### ISSUE TITLE
DevToolsDataSourceAutoConfiguration fails if more than one embedded databases are used

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#5540]
`DevToolsDataSourceAutoConfiguration` assumes a single `DataSource` bean being present in the `ApplicationContext`, which might not necessarily be the case.

**Comment by wilkinsona** [comment]
I think it really needs to look for a single `DataSource` that's been auto-configured, i.e. we need to be sure that it's been configured using `DataSourceProperties` as that's how we figure out what sort of `DataSource` it is and whether or not we need to shut it down across restarts.
