### ISSUE TITLE
Set random management port for tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5548]
I think we should set a random management port when `WebEnvironment.RANDOM_PORT` is used. We should probably also have something similar to `@LocalServerPort`.

**Comment by snicoll** [comment]
I don't think we should do that. The default is to use the same tomcat context than the one of the server. If you trigger `management.port=0` it'll start a separate context which isn't what you want. What did you had in mind with regards of detecting that a separate context was required? The other downside is that you bring an actuator specific knowledge in `spring-boot-test`.

**Comment by snicoll** [comment]
I've added `@LocalManagementPort` in f364d71 - Maybe that's enough for this issue?

**Comment by philwebb** [comment]
Yup, that makes sense. It was a daft idea :)
