### ISSUE TITLE
When run as a war, spring boot loader .class files can be accessed through http. 

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#5550]
Start a spring boot war, then 

``` bash
wget http://localhost:8080/org/springframework/boot/loader/archive/Archive.class
```

When run as a war, the Tomcat context's docBase is set to `.war` path, so the `ServletContext` can getResource from tomcat's `WebResourceRoot`.

``` java
//AbstractEmbeddedServletContainerFactory.java
    /**
     * Returns the absolute document root when it points to a valid directory, logging a
     * warning and returning {@code null} otherwise.
     * @return the valid document root
     */
    protected final File getValidDocumentRoot() {
        File file = getDocumentRoot();
        // If document root not explicitly set see if we are running from a war archive
        file = file != null ? file : getWarFileDocumentRoot();
        // If not a war archive maybe it is an exploded war
        file = file != null ? file : getExplodedWarFileDocumentRoot();
        // Or maybe there is a document root in a well-known location
        file = file != null ? file : getCommonDocumentRoot();
        if (file == null && this.logger.isDebugEnabled()) {
            this.logger
                    .debug("None of the document roots " + Arrays.asList(COMMON_DOC_ROOTS)
                            + " point to a directory and will be ignored.");
        }
        else if (this.logger.isDebugEnabled()) {
            this.logger.debug("Document root: " + file);
        }
        return file;
    }

    private File getWarFileDocumentRoot() {
        return getArchiveFileDocumentRoot(".war");
    }
```

In a traditional war file, all classes/jars are under `/WEB-INF`, can not bd accessed through http. But spring boot maven plugin put spring boot loader classes files into  war `/` path.

**Comment by philwebb** [comment]
Unfortunately the loader classes need to be accessible in order for `java -jar` to work. If you need a fully executable jar you can set `executable` to `false` in Spring Boot's Maven or Gradle plugin.

**Comment by hengyunabc** [comment]
It may cause security problems? 

When service run as `java -jar ./demo.war`, people can access spring boot loader .class files through http. So they can know the service is a spring boot service, and the spring boot version.

**Comment by philwebb** [comment]
@hengyunabc

**Comment by wilkinsona** [comment]
I think you could add a Valve that 404s requests for the loader classes

**Comment by philwebb** [comment]
I wonder if we can do that automatically?

**Comment by wilkinsona** [comment]
Some prototyping I did earlier today says yes. It also made me realise it might not be totally straightforward. To 404 anything under `org/springframework/boot/loader` we need to be sure the path had been decoded, didn't contain any `..`, etc. Nothing insurmountable but it'll take a bit of care.

**Comment by paolodenti** [comment]
@hengyunabc 
instead of configuring servlet container you can manage it in the applicationcreating a controller like this

`
@ResponseStatus(value = HttpStatus.NOT_FOUND)
class ResourceNotFoundException extends RuntimeException {
	private static final long serialVersionUID = 1L;
}

/*
 * needed to forbid access to the spring boot loader classes in
 * org.springframework.boot.loader deployed in war root
 */

@Controller
public class ForbiddenController {

	private final Logger logger = LoggerFactory.getLogger(ForbiddenController.class);

	@RequestMapping("/org/**")
	public String org() {
		logger.warn("access to /org is forbidden");
		throw new ResourceNotFoundException();
	}
}
`

**Comment by wilkinsona** [comment]
I think I've figured out how to do this down at the resource level, so there's no need for a `Filter`.
