### ISSUE TITLE
The new @SpringApplicationTest should provide "merge" for properties when we extend test class for particular case

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#5555]
The new `@SpringApplicationTest` replaces `@IntegrationTest` and `@WebIntegrationTest`.

Since we can't (still) use all of them on the method level we are forced to move common configuration to the super class and extend it for the particular test-case in the inheritor.
The common use-case is Spring Cloud Stream Modules, where we customize the application via `@IntegrationTest` properties, but still would like to get a gain of the common inherited properties. For example: https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/cassandra-sink/src/test/java/org/springframework/cloud/stream/module/cassandra/sink/CassandraSinkIntegrationTests.java

For the inheritance we use one annotation on the super class and another on the target child. With that we have a `merge` of properties in the target `Environment` for the particular test.

Only single  `@SpringApplicationTest` prevent to do that, therefore we are forced to copy/paste all common properties for each test-case.

The simple class to reproduce and figure out our wishes (at least until we don't support  `@SpringApplicationTest` on the method level):
````java
@SpringApplicationConfiguration
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationTest("foo = foo")
public abstract class SpringApplicationTestInheritanceTests {

	@SpringApplicationTest("bar = bar")
	public static class SpringApplicationTestInheritanceExtensionTests extends SpringApplicationTestInheritanceTests {

		@Autowired
		private Environment environment;

		@Test
		public void testIt() {
			assertNotNull(environment.getProperty("bar"));
			assertNotNull(environment.getProperty("foo"));
		}

	}

	@SpringBootApplication
	public static class Config {

	}

}
````

**Comment by wilkinsona** [comment]
Using multiple `SpringApplicationTest` annotations in a class hierarchy doesn't make much sense to me. For example, what would happen if they had conflicting `webEnvironment` configuration?

Given your requirements, I think I'd use `@TestPropertySource` on `SpringApplicationTestInheritanceExtensionTests`. Have I missed something that means that doesn't work?

**Comment by artembilan** [comment]
Fair enough, @wilkinsona !

Really, placing the `@TestPropertySource(properties = )` instead of `@WebIntegrationTest` on those particular cases in the `CassandraSinkIntegrationTests` makes me happy again. :smile: 
Or vice versa, by the way. 

So, we still can have a common properties or common environment, depending of the place of the `@WebIntegrationTest`.

I will share that with SCSt team and something like this our discussion may should have some short paragraph in the Manual do not confuse other people.

Thank you for your quick and wise feedback!

**Comment by wilkinsona** [comment]
I'm going to close this one. Our preferred approach is to use a single `@SpringBootTest` annotation in a class hierarchy. `@TestPropertySource` should be used for advanced property configuration.

**Comment by artembilan** [comment]
Thank you @wilkinsona ! Fair enough!

Cheers and sorry for the noise :smile:
