### ISSUE TITLE
Log output from bootRun at times unpredictably hangs

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-boot#5558]
Running the project from command-line with the bootRun task at times exhibits a strange behavior where console log output is not displayed. The same output is correctly written to the log file, but not the console. This is with the latest version of the boot gradle plugin and boot itself, on the latest version of Oracle JDK 8 with the embedded tomcat configuration.

If I simply shut down the app and run the same command again, the output starts to appear in the console.

**Comment by wilkinsona** [comment]
Can you please explain why you believe this to be a problem with Spring Boot and its Gradle plugin?`bootRun` is just a Gradle `JavaExec` task and it doesn't do anything special with System.out. It relies on Gradle's standard mechanism for running a new Java process, and to capture the output from it and route it to the console of the build's process.

**Comment by mmoayyed** [comment]
I guess my inclination was that I only see the behavior when I run the `bootRun` task. Running other gradle tasks appear to produce output logs correctly, and running the app directly an executable war also shows logs correctly. Are you suggesting this might be an issue with Gradle? I am on v2.12 and I think I saw the same symptoms with 2.11.

**Comment by wilkinsona** [comment]
> Running other gradle tasks appear to produce output logs correctly

The `JavaExec` task (which is what `bootRun` is) is unlike most other Gradle tasks as it forks a new JVM. The output from that JVM then needs to be read by the build's JVM and output to its console.

> running the app directly an executable war also shows logs correctly

That would suggest that both Spring Boot itself and whatever logging framework you are using are working as expected.

> The same output is correctly written to the log file, but not the console.

Again, that suggests that Boot itself is working as expected.

> Are you suggesting this might be an issue with Gradle?

Yes, that's my best guess based on the information you have provided.

**Comment by mmoayyed** [comment]
Thanks for the update Andy. I'll take this to gradle forums and see what comes out.
