### ISSUE TITLE
Upgrade to Atomikos 4.0.4

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5591]
Atomikos 4.0 is out. We should look at out how big a change it is from 3.9.x and figure out if/when we want to upgrade.

**Comment by wilkinsona** [comment]
> if/when we want to upgrade.

The answer is not yet. The latest version in the [release notes](https://www.atomikos.com/Main/ReleaseNotes) is 4.0.1 and it's listed as a beta.

**Comment by wilkinsona** [comment]
4.0.x no longer appears to be beta. 4.0.4 is the latest.

**Comment by snicoll** [comment]
4.0 also has a `transactions-defaults.properties`  in the classpath with default values. Currently our test is accessing a private API with reflection to assert default value.
