### ISSUE TITLE
Spring boot reference -  executable-jar-jarfile

### ISSUE THREAD

**Issue by paulvi** [spring-projects/spring-boot#5620]
In Spring boot reference
http://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-jarfile
there is possibly mistake as `B.class` is shown twice in the same .jar file

Where is reference source repository?

**Comment by wilkinsona** [comment]
As luck would have it, I fixed that yesterday in https://github.com/spring-projects/spring-boot/commit/fc6c57413ba3576cfe4098728d2f9c66025d1971
