### ISSUE TITLE
Support compressed JarEntries

### ISSUE THREAD

**Issue by bbc-tomfitzhenry** [spring-projects/spring-boot#5630]
The problem:
https://github.com/spring-projects/spring-boot/blob/6121d105fc56c57636b98ecc7504caff978bcd14/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFile.java#L277-L282 will throw an exception if a JarEntry is compressed (e.g. of type ZipEntry.DEFLATED).

Though the spring boot maven plugin will make sure that JAR entries are not compressed, other tools repackage JARs, compressing them along the way, such as Centos's `rpmbuild`, which uses [brp-java-repack-jars](https://gist.github.com/bbc-tomfitzhenry/1eb449af8bcc91466a49a497e3c64b3b).

A workaround is to stop rpmbuild repacking JARs (`%define __jar_repack 0`), but it'd be nice if Spring Boot supported all valid JAR files (including those with compressed JarEntries).

**Comment by philwebb** [comment]
Unfortunately we need nested entries to be stored uncompressed so that we can directly access content without needing to unpack the Uber JAR. Some details about why are in the [reference docs](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#executable-jar-jarfile).
