### ISSUE TITLE
Allow overriding logback's CONSOLE_LOG_PATTERN in a convenient way

### ISSUE THREAD

**Issue by teosarca** [spring-projects/spring-boot#5632]
At the moment, if i have to configure logback's `CONSOLE_LOG_PATTERN`, basically i have to copy the whole `org/springframework/boot/logging/logback/base.xml` file.

It would be nice if i could only set the `CONSOLE_LOG_PATTERN`  and then import the `base.xml`

Basically, in `defaults.xml` we shall check if the `CONSOLE_LOG_PATTERN`  was already defined.
i.e.

```xml
<property name="CONSOLE_LOG_PATTERN" value="${CONSOLE_LOG_PATTERN:- ... what we have now... }" />
```

**Comment by philwebb** [comment]
Does using an `<include>` then redefining the property work? Something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/base.xml" />
        <property name="CONSOLE_LOG_PATTERN" value="..." />
</configuration>
```

BTW: If you _only_ want to define the pattern you can delete your `logback.xml` and use `logging.pattern.console=...` in your `application.properties`.

**Comment by boriswaguia** [comment]
Hi @philwebb  I've just added a commit referring to @teosarca 's solution. Can you please have a look on it and let me know what you think ? Thx.

**Comment by aholbreich** [comment]
@philwebb 
It somehow not working when overriden like this. Spring boot: 1.5.2.RELEASE
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/base.xml" />

	<property name="CONSOLE_LOG_PATTERN" value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%5.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
	
	<logger name="com.example" level="${LOG_LEVEL_LM:-DEBUG}" additivity="false">
		<!--  <appender-ref ref="STDOUT" />-->
	</logger>
	<root level="${LOG_LEVEL:-INFO}">
        <appender-ref ref="CONSOLE" />
    </root>
</configuration>
```
Actually CONSOLE_LOG_PATTERN patter is not applyed.
Any ideas?

**Comment by snicoll** [comment]
@aholbreich we don't use the tracker for questions. Join us on Gitter or ask on Stackoverflow please.
