### ISSUE TITLE
Adding spring-cloud dependency changes logback-spring.xml custom configuration behavior

### ISSUE THREAD

**Issue by ssherwood** [spring-projects/spring-boot#5639]
I am attempting to use the logback-spring.xml to configure a custom appender with a parameterized name using the springProperty tag in order to leverage profile configuration in the application.yml.  Everything works as expected until I add a Spring Cloud dependency (in my case spring-cloud-starter-hystrix).

It appears that the the lifecycle changes introduced by Spring Cloud cause the properties that were formerly provided via the application.yml to be null/empty at the point that Spring Cloud is initializing.  After Cloud bootstraps, it looks like logback is re-initialized with the expected configuration.  In my demo application, this yields two distinct log files (one with logback's logfile_IS_UNDEFINED.log clearly indicating that null was provided).

Later, I realized that I could move the properties that I needed to the bootstrap.yml, but its clear that this still has some initialization issues: https://github.com/ssherwood/spring-boot-logging-withcloud

In my specific case, we have a custom appender that needs a server configuration per profile and the undefined case is preventing the app from starting up (when it works just fine without the cloud dependency).  It seems like this behavior needs to be more consistent.

**Comment by spencergibb** [comment]
Should this go in https://github.com/spring-cloud/spring-cloud-commons/issues?

**Comment by snicoll** [comment]
I think so yes, @ssherwood could you please move your issue there? We can certainly resume here if that's necessary.
