### ISSUE TITLE
Couchbase tests keep breaking the Windows CI

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5651]
See https://build.spring.io/browse/BOOT-WIN-577 for an example.

**Comment by snicoll** [comment]
You mean couchbase right?

**Comment by snicoll** [comment]
This is what we get when couchbase is _not_ present: `Connection refused: localhost/127.0.0.1:8091`

On the Windows build we get `connection timed out: localhost/127.0.0.1:8091`. The connect timeout is 5sec so it looks like we have a (very) slow couchbase instance on that environment. Maybe @trevormarshall knows?

**Comment by snicoll** [comment]
#5667 fixed it
