### ISSUE TITLE
logging.pattern.console specific to logback

### ISSUE THREAD

**Issue by lanoxx** [spring-projects/spring-boot#5653]
It seems that specifying `logging.pattern.console` in application.properties can only be used to override the logging pattern when using logback and it has no effect when using Log4j2, [the documentation][1] mentions that `logging.pattern.level` is only supported for logback, maybe it should say the same for `logging.pattern.console` and `logging.pattern.file`?

Looking at `spring-configuration-metadata.json` seems to confirm this.

[1]: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

**Comment by philwebb** [comment]
This might be an error in out `Log4J2.xml` file. It looks like we set a `CONSOLE_LOG_PATTERN` property but use `${LOG_PATTERN}` in the XML.

**Comment by lanoxx** [comment]
Thanks for the quick reply. I am looking forward to see this fixed. Currently I have copied the included log4j2.xml from spring-boot into my project and adjusted the log pattern there, but that seems overkill if I only want to change the log pattern.

Btw. would it be reasonable to ask to document the default log pattern that spring boot is using in the manual? I spend quite some time trying to find it today and looking through various spring boot auto-configuration classes and the like until I realized that spring-boot is actually shipping its own log4j2.xml (I even opened a question on SO: http://stackoverflow.com/questions/36544980/default-spring-boot-log4j2-log-pattern).

**Comment by snicoll** [comment]
We effectively support `logging.pattern.*` for Logback at the moment so it is a documentation issue at this point I am afraid. I can improve the doc and include the default value in the meta-data but I won't add log4j2 support at this point.

@philwebb maybe we could create a separate issue for the log4j2 support?

**Comment by snicoll** [comment]
@lanoxx I don't know which version you're using but it is documented as a logback specific feature since `1.3.0.M3` (see #3405).

**Comment by lanoxx** [comment]
I am fine with the change, thank you.
