### ISSUE TITLE
Allow Flyway to repair the database if a configuration flag is set

### ISSUE THREAD

**Issue by wedrive-rb26** [spring-projects/spring-boot#5654]
Currently, flyway autoconfiguration is enabled or disabled via properties, but there are no configuration options available for whether Flyway should attempt to repair the database.

**Comment by wilkinsona** [comment]
We provide the `FlywayMigrationStrategy` strategy interface for this sort of thing. If you add a bean that implements `FlywayMigrationStrategy` to your application, its `migrate` method will be called at which point you can call `Flyway.repair()` and/or `Flyway.migrate()` as appropriate.

**Comment by wedrive-rb26** [comment]
Can you point me to a place in the documentation for that?  Thanks, that should work for our case.

**Comment by wilkinsona** [comment]
It was introduced in #1814 and then became an interface in #3217, however it doesn't look like it ever made it into the reference documentation. Thanks for pointing out the problem. I've opened #5656 so that was can improve the docs.
