### ISSUE TITLE
Expose way to add custom data to Trace objects from WebRequestTraceFilter

### ISSUE THREAD

**Issue by geoffwa** [spring-projects/spring-boot#5660]
It'd be really awesome if there was some way to add application data to traces generated by WebRequestTraceFilter - it could be used a the basis for some cheap server-side profiling.

Could this be done via a request-scoped bean or is there a better approach?

**Comment by jgoldhammer** [comment]
+1. 
I have written my own tracefilter which logs the request body, session/request attributes and some other stuff which are tracked in my application...

Thanks,
Jens

**Comment by wilkinsona** [comment]
@geoffwa You can add a `@Bean` that subclasses `WebRequestTraceFilter` and overrides `getTrace` and/or `enhanceTrace`. You're then free to add data to the traces via whatever means you choose be it request-scoped beans, request attributes, or something else entirely.

One gotcha at the moment is that you'll need to exclude `TraceWebFilterAutoConfiguration` as it currently creates its `WebRequestTraceFilter` unconditionally. We could certainly change that though.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
