### ISSUE TITLE
`CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` doesn't work when using `@AllArgsConstructor` in Spring Boot 1.4.0.M2

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#5687]
`CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` works regardless of using `@AllArgsConstructor` in Spring Boot 1.4.0.M1 but after upgrading to 1.4.0.M2, it doesn't work when using `@AllArgsConstructor`. By the way, with a manually created constructor having all arguments it works.

This is a sample project reproducing it: https://github.com/izeye/spring-boot-throwaway-branches/tree/rest-and-jackson

Especially this test class is showing the problem: https://github.com/izeye/spring-boot-throwaway-branches/blob/rest-and-jackson/src/test/java/com/izeye/throwaway/ObjectMapperTests.java

Downgrading to Jackson 2.6.5 makes it work again.

**Comment by wilkinsona** [comment]
I don't think this has anything to do with Spring Boot. The following test exhibits the same behaviour:

```
package com.izeye.throwaway;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;

import org.junit.Test;

/**
 * Created by izeye on 16. 4. 14..
 */
public class ObjectMapperTests {
	
	@Test
	public void test() throws JsonProcessingException {
		LombokAllArgsConstructorDomain lombokDomain = new LombokAllArgsConstructorDomain();
		lombokDomain.setSomeProperty("test");
		System.out.println(new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE).writeValueAsString(lombokDomain));
		
		ManualAllArgsConstructorDomain manualDomain = new ManualAllArgsConstructorDomain();
		manualDomain.setSomeProperty("test");		
		System.out.println(new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE).writeValueAsString(manualDomain));
	}
	
}
```

The problem appears to be that Jackson 2.7.2 considers the properties of `LombokAllArgsConstructorDomain` to be explicitly named so it doesn't apply the property naming strategy to them. A workaround is to enable explicit property renaming:

```
LombokAllArgsConstructorDomain lombokDomain = new LombokAllArgsConstructorDomain();
		lombokDomain.setSomeProperty("test");
		System.out.println(new ObjectMapper().enable(MapperFeature.ALLOW_EXPLICIT_PROPERTY_RENAMING)
				.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE).writeValueAsString(lombokDomain));
```

@izeye Can you please raise a bug against Jackson Databind and link to it from here?

**Comment by izeye** [comment]
@wilkinsona Thanks! I filed the issue there: https://github.com/FasterXML/jackson-databind/issues/1197
