### ISSUE TITLE
Support installing spring boot applications as windows service using jna library

### ISSUE THREAD

**Issue by maol74** [spring-projects/spring-boot#5693]
Would be nice to support installing spring boot app as windows service using jna library, see for example the code https://github.com/java-native-access/jna/blob/master/contrib/ntservice/src/jnacontrib/win32/Win32Service.java how to do this easily.
By adding specific properties in application.properties the developer can control the service for example setting the service name, account and pwd etc

1) installing service could then perhaps be

`java -jar myapp.jar --install-service`  - installs service call myapp

2) uninstall service could then perhaps be

`java -jar myapp.jar --uninstall-service`

**Comment by philwebb** [comment]
It's an interesting idea, but I'm not too keen to add direct integration with jna. We already offer windows service support via [wins](https://github.com/kohsuke/winsw). See [the reference docs for details](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#deployment-window)
