### ISSUE TITLE
Dependency convergence error for com.fasterxml:classmate in 1.4.0.M2

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#5697]
Hi,

i'm using the maven-enforcer-plugin (1.4.1) to check for convergence errors. When using "spring-boot-starter-web" and "spring-boot-starter-data-jpa" i end up with a convergence error for com.fasterxml:classmate:

```
Dependency convergence error for com.fasterxml:classmate:1.1.0 paths to dependency are:
+-eu.michael-simons:biking2:2.1.5-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-web:1.4.0.M2
    +-org.hibernate:hibernate-validator:5.2.4.Final
      +-com.fasterxml:classmate:1.1.0
and
+-eu.michael-simons:biking2:2.1.5-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-data-jpa:1.4.0.M2
    +-org.hibernate:hibernate-entitymanager:5.1.0.Final
      +-org.hibernate:hibernate-core:5.1.0.Final
        +-com.fasterxml:classmate:1.3.0
```

Thanks,
Michael.

**Comment by wilkinsona** [comment]
Looks like we should provide dependency management for `com.fasterxml:classmate`. Gradle users will be getter 1.3 anyway as it picks the highest version by default.

@michael-simons  It looks like Hibernate Validator 5.3 snapshots are still using 1.1. It might be worth also raising an issue against Hibernate Validator to see if they'll align the version of the Classmate dependency with Hibernate.

**Comment by michael-simons** [comment]
@wilkinsona Thanks! I wouldn't have bothered you with this but as a user i expect that including those starters don't lead to convergence errors. The hibernate issue already exists: https://hibernate.atlassian.net/browse/HV-1038

**Comment by cemo** [comment]
@wilkinsona see https://hibernate.atlassian.net/projects/HV/issues/HV-1038
