### ISSUE TITLE
Flyway REST Endpoint - java.lang.NullPointerException

### ISSUE THREAD

**Issue by czerpak** [spring-projects/spring-boot#5700]
I my project we use 1.3.3 Spring Boot version with Flyway. But when I try use Flyway REST endpoint I receive java.lang.NullPointerException. It is caused by "repeatable flyway scripts" which doesn't set version in schema_version table. This error occurs in  FlywayMigration.java in constructor: this.version = info.getVersion().toString();

You should check if version is null because it is possible.

**Comment by wilkinsona** [comment]
@czerpak Just to help me understand the scope of the problem, are you using Flyway 4.0? AFAICT, repeatable scripts are new in 4.0 and Boot only supports 3.x at the moment.

**Comment by czerpak** [comment]
@wilkinsona I'm using Flyway 4.0 with Spring Boot  1.3.3

**Comment by wilkinsona** [comment]
Thanks. Please see #5296 for official support of 4.0. In the meantime, I see no reason why we can't tolerate the `null` version.
