### ISSUE TITLE
Auto-configure MockMvc with Spring Security's TestSecurityContextHolderPostProcessor

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5702]
See https://github.com/spring-projects/spring-boot/issues/2708#issuecomment-210487687

It would perhaps be easiest to just call `springSecurity()` but we'd need to be careful to avoid Security's Filter being registered twice.

**Comment by jgoldhammer** [comment]
Please also consider that spring restdocs can also be configured this way (with apply)...

http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-documentation-snippets-setup

Thanks,
Jens

**Comment by wilkinsona** [comment]
@jgoldhammer We already have `@AutoConfigureRestDocs` for that

**Comment by wilkinsona** [comment]
Duplicates #5476
