### ISSUE TITLE
Decide what to do about the ws starter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5711]
Rename or revert?

**Comment by wilkinsona** [comment]
Another option while I remember: keep both, deprecate `-ws` and make it depend on `-webservices`

**Comment by snicoll** [comment]
I'd rather keep it as it is now, `spring-ws` is the name of the project after all.

**Comment by wilkinsona** [comment]
> `spring-ws` is the name of the project after all.

I don't think it is. It's the name of the GitHub repository, but in lots of other places (reference docs, project page, etc) the project is referred to as `Spring Web Services`. Arguably, that means that the starter should be called `-web-services`.

**Comment by vpavic** [comment]
What @wilkinsona said plus having just ```-ws``` is IMO just too ambiguous.

**Comment by snicoll** [comment]
FYI, we can freely chose the name of the starter and it won't broke start.spring.io as I've implemented better mappings for dependencies (https://github.com/spring-io/initializr/commit/2d9ac9bd5abda013a44a22af2d276e5c2fdfb526). See [what was done for the redis starter](https://github.com/spring-io/initializr/blob/2d9ac9bd5abda013a44a22af2d276e5c2fdfb526/initializr-service/application.yml#L269-L278).

**Comment by philwebb** [comment]
We should also consider the package name. As @snicoll mentioned the PR plurals in package names are yuk.

**Comment by wilkinsona** [comment]
We've decided: the old starter will be deprecated in favour of a new starter named `spring-boot-starter-web-services`
