### ISSUE TITLE
lockfree algorithm for InMemoryTraceRepository with EvictingQueue or Caffeine...

### ISSUE THREAD

**Issue by jgoldhammer** [spring-projects/spring-boot#5712]
I am using the tracerepository and have noticed the synchronized block in

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/InMemoryTraceRepository.java#L70

Please use an EvictingQueue (http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/EvictingQueue.html) or Caffeine (https://github.com/ben-manes/caffeine) to get rid of the synchronized blocks...

Thanks,
Jens

**Comment by wilkinsona** [comment]
@jgoldhammer How did you notice the synchronized block? Was it by inspecting the code, or has it shown up as a hot spot when profiling? If it's the latter, can you please provide some more details about the workload that you profiled.

**Comment by philwebb** [comment]
We definitely can't add a mandatory Guava or Caffeine dependency so if this is a real performance issue we'll need to find another way to fix it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
