### ISSUE TITLE
Support placeholder in outputDir of @AutoConfigureRestDocs

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#5713]
For some cases it's useful to e.g. use a system property that defines the outputDir of the generated snippets.
Currently with `@AutoConfigureRestDocs` the outputDir can only configured via the annotation itself which only supports a 'hard' value.
It would be nice to support placeholders in the outputDir.

**Comment by marceloverdijk** [comment]
ps: don't give this high priority just for me; I decided to define the path in the test class itself

**Comment by wilkinsona** [comment]
As I said on Gitter, my concern with supporting a placeholder is that it'll be an inconvenience when running the tests in an IDE. To avoid that, we could support a placeholder that also lets you configure a default. I'm yet to be convinced that it's worth it, but let's see what others think.

**Comment by wilkinsona** [comment]
Others aren't convinced it's worth it either.
