### ISSUE TITLE
Documentation: Typo on 1.4.0 M3 ReleaseNotes

### ISSUE THREAD

**Issue by bountin** [spring-projects/spring-boot#5717]
There's a small typo/copy-paste-error on https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M3-Release-Notes: The second bullet point should be "v1.4.0 M2" and not "v1.4.0 M1" (Its URL is correct).

**Comment by snicoll** [comment]
Fixed, thanks!
