### ISSUE TITLE
Redis auto-configuration requires commons-pool2

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#5718]
`JedisConnectionFactory` creates a `JedisPoolConfig` which in turn results in a `JedisPool` which in turn uses Apache Commons Pool 2 and the `GenericObjectPool` is used there. Plus, `usePool` is true in `JedisConnectionFactory`, by default, and I don't see a property to change it.  

So, i'd have to create a `@Bean` to set usePool to be false, in which case the `@Bean` that's provided by the auto-config that tests for the availability of the `GenericObjectPool` is moot, anyway. And unless I do something like that, it's going to call code that requires the `GenericObjectPool`. 

I think.

**Comment by joshlong** [comment]
i ran into this by excluding Apache Commons Pool2:

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
                <version>${commons-pool2.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

```

**Comment by snicoll** [comment]
`JedisConnectionFactory` _does_ require `commons-pool2`. 

@christophstrobl is that new? We have specific branches for "commons-pool2` is not on the classpath and that looks completely useless now. Is that a reason why you absolutely require `commons-pool2`? If so, we need to update the auto-configuration to require it. Thoughts?

**Comment by christophstrobl** [comment]
We switched to `commons-pool2` [DATAREDIS-261](https://jira.spring.io/browse/DATAREDIS-261) included in Dijkstra M1. So that should not be new.
Cluster support (new in Hopper) uses the `JedisPoolConfig` which is a `GenericObjectPoolConfig` in `JedisConnectionFactory`.

**Comment by snicoll** [comment]
> i ran into this by excluding Apache Commons Pool2:

@joshlong: why have you done that? Anything else that forced you to do it?

**Comment by snicoll** [comment]
After looking at the code, we should simply remove the code that tries to does something if commons-pool2 is not present. It's not realistic.

**Comment by caneraydinbey** [comment]
Closed?

**Comment by snicoll** [comment]
No.
