### ISSUE TITLE
Hibernate Validator initialize class error

### ISSUE THREAD

**Issue by matty** [spring-projects/spring-boot#5723]
Spring Boot upgrade from 1.2.6 > 1.3.3 breaks because of Hibernate Validator?

The error I am getting is

```
2:43:39.221 [main] WARN  com.caucho.server.webapp.WebApp - java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:31)
```

**Comment by wilkinsona** [comment]
We have several samples that happily use Hibernate Validator in 1.3.3. Can you please provide some more details about you app? A sample that reproduces the problem would be ideal.

**Comment by matty** [comment]
The app is using Spring Boot 1.3.3, and attempting to deploy the war file on Resin Caucho, http://caucho.com/.

I am simply using these dependencies

```
compile("org.springframework.boot:spring-boot-starter-web:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-freemarker:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-security:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-mail:${springBootVersion}")
```

The Tomcat Embed works just fine, maybe its a Resin issue?

**Comment by snicoll** [comment]
Check if `hibernate-validator` isn't already provided by resin or something.

**Comment by matty** [comment]
It appears that it actually is, hibernate-validator is included in Resin but removing the .jar from the libs folder doesn't seem to resolve the issue.

**Comment by wilkinsona** [comment]
Duplicates #4025
