### ISSUE TITLE
Make added X-Application-Context header name a constant

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#5726]
Change `EndpointWebMvcAutoConfiguration` `X-Application-Context` header to a public constant.
This way it would be more easier and robust to e.g. remove it from Spring REST Docs snippet generation.

**Comment by philwebb** [comment]
I'm tempted to make `ApplicationContextHeaderFilter` a top level class, move it to `spring-boot.jar` and add the constant there. Adding it to `EndpointWebMvcAutoConfiguration` doesn't feel right.

**Comment by marceloverdijk** [comment]
thx!
