### ISSUE TITLE
Review of info contribution infra

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5734]
I think we should review these points and make sure that it's the right approach:

1. I am not sure that `Info.Builder` is right. It has only 2 methods for now, let’s make sure it has the right design
2. If you add additional properties in the `build-info` build task, they won’t show up until you switch the mode to “full”. I am not sure that it’s such a great idea. Maybe the default of that one should be full?
3. It generates a file in `META-INF/boot/build.properties`. Maybe `META-INF/spring/build.properties` is more appropriate ?

**Comment by philwebb** [comment]
We could try and make similar to the way that `HealthIndicators` work. The `InfoContributor` could be an `InfoProvider` that returns a `Map`. The `Info` class would then be an internal concern of `InfoEndpoint` and the `Builder` would go away.

I'm not sure that that's necessarily better than the existing design, although the parity with other parts of the system is quite nice.

**Comment by philwebb** [comment]
* If we don't change the contributor design the `Info` class should probably be fully immutable. It looks like `getDetails` currently returns a mutable map.
* Default mode being full seems fine, unless there's anything especially sensitive in the file.
* Something more generic for `build.properties` seems sensible. Perhaps `META-INF/build-info.properties`.

**Comment by snicoll** [comment]
`META-INF/build-info.properties` came to mind quickly but I didn't want to steal such a generic name. If we feel that's fine, let's do that. I also though of `InfoProvider` but I really have a problem returning a `Map`. The other downside is that you compartiment providers (what do we do with the maps from various providers? do we merge them or do we namespace them? If we want to be consistent with health we should use option 2 which isn't great IMO).

**Comment by dsyer** [comment]
I think exposing `Info` externally is a mistake for 2 reasons: 1) it breaks binary compatibility with 1.3 (anyone that actually took our advice in the user guide and created their own `InfoEndpoint` will now not be able to compile against 1.4), 2) it makes the endpoint unconsumable from a dumb JMX client (like JConsole). We could solve 2) using some kind of adapter layer for JMX resources (but that seems like a big change for 1.4 at this stage). 1) would still be a problem, so I move to go back to `Map<String,Object>` as the return type for `invoke()`.

**Comment by dsyer** [comment]
Actually I think we already have a JMX adapter layer, otherwise how does `HealthEndpoint` work? I'm still concerned about the binary compatibility.

**Comment by cemo** [comment]
More improvements:

1.) Spring.io's date is formatted whereas `info`'s date is not. It is better to see with a sensible formatted date by default instead of milliseconds.
2) Started time of the server is also good candidate for info.

**Comment by snicoll** [comment]
@cemo it's a `Date` so anything you tell jackson to do will be applied there.

**Comment by dsyer** [comment]
Also there are no `Dates` in the info endpoint by default. Maybe you mean metrics?

**Comment by snicoll** [comment]
There are dates: the build time and the git commit timestamp. Both are set as `java.util.Date` and Jackson can serialize that if you teach it.

**Comment by dsyer** [comment]
Right, roger that (it's not there by default though). The start time (up time actually) of the server is in /metrics for better or for worse. It can't be a `Date` really because metrics only have numerical values.

**Comment by snicoll** [comment]
you need to enable the git and `build-info` build tasks to actually enable those. And +1 with the start time that's in metrics now. It may no be the perfect place for this but then a bunch of other properties could move for the same reason and I don't think that's a good idea.

**Comment by cemo** [comment]
What I was suggesting is that using a timestamp like `started-time: "2016-05-03 19:25`. I don't think so much that this is a metric. 
However elapsed time is a metric and it should definitely inside metrics.

**Comment by snicoll** [comment]
Once again. It's a date. If it renders as epoch time (long) that's because it's jackson's default. If you don't like that, configure Jackson.

**Comment by cemo** [comment]
@snicoll 

> The start time (up time actually) of the server is in /metrics for better or for worse. It can't be a Date really because metrics only have numerical values.

I was referring this statement. `Info` is a quick view of the server. `Start time and up time are different concepts.
