### ISSUE TITLE
Perform failure analysis of BindException

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5738]
Raised by @ByteFlinger on Gitter:

> Hi. I am trying to to use jsr-303 in properties in a `@Component class` like so

> ```
> @Component
> @ConfigurationProperties
> public class MyClazz implements ApplicationRunner {
> 
>     @NotEmpty(message = "--prop is required")
>     private String prop;
> 
> }
>  ```
And it works except the exception thrown in the console if the user does not supply `--prop` is quite ugly. What would be the best way to maybe catch that and display only the message printed in the `@NotEmpty` annotation or some other message?

> What I see if something like this:

>
> ```
> ... Caused by: org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors Field error in object 'target' on field 'prop': rejected value [null]; codes [NotEmpty.target.prop,NotEmpty.prop,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [target.prop,prop]; arguments []; default message [prop]]; default message [--prop is required]
> ```

**Comment by ByteFlinger** [comment]
Thank you @wilkinsona

Thought maybe I was missing something. This issue was found on version 1.3.3
