### ISSUE TITLE
Friendlier default for OPTIONS

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-boot#5739]
I would like to request a more friendly version of the default behavior of an HTTP `OPTIONS` request. Consider a resource that supports only `GET` and `PUT`.

If I set `spring.mvc.dispatch-options-request=false` and request `OPTIONS`, I receive a `200 OK` and the header `Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH`. The list of options is not correct for that resource.

If I set `spring.mvc.dispatch-options-request=true` and request `OPTIONS`, I receive a `405 Method Not Allowed` and the header `Allow: GET, PUT`. The list of options is correct for that resource, but the response is an error.

Desired behavior: I can configure Boot to respond with a `200 OK` containing the correct list of options, e.g. `Allow: GET, PUT` without having to implement an options endpoint for each controller. It appears Spring has all the info it needs to do this.

I am using 1.3.3.RELEASE, Tomcat as the embedded webserver.

**Comment by wilkinsona** [comment]
This is coming in Spring Framework 4.3 and, therefore, Spring Boot 1.4. See https://jira.spring.io/browse/SPR-13130 for details. You should be able to try it out using Spring Boot 1.4.0.M2.
