### ISSUE TITLE
JerseyWebApplicationInitializer loading when I've told it not to

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#5740]
I have set this on our config

```@EnableAutoConfiguration( exclude = JerseyAutoConfiguration.class )```

and yet I'm getting this error
http://stackoverflow.com/q/36722397/206466

which is obviously coming from 

```	@Order(Ordered.HIGHEST_PRECEDENCE)
	public static final class JerseyWebApplicationInitializer
			implements WebApplicationInitializer {

		@Override
		public void onStartup(ServletContext servletContext) throws ServletException {
			// We need to switch *off* the Jersey WebApplicationInitializer because it
			// will try and register a ContextLoaderListener which we don't need
			servletContext.setInitParameter("contextConfigLocation", "<NONE>");
		}

	}```

**Comment by wilkinsona** [comment]
You are trying to use Spring Boot DevTools without using Spring Boot. That isn't supported. You are also using a ContextLoaderListener with Spring Boot which also isn't supported.

**Comment by xenoterracide** [comment]
I'm pretty sure this can be reproduced in SpringBoot, since the exception is emitted from XmlWebApplicationContext, and JerseyAutoConfiguration is loaded because javax.servlet.ServletRegistration is on our classpath even though Jersey isn't

**Comment by wilkinsona** [comment]
Spring Boot doesn't use `XmlWebApplicationContext` so it isn't really relevant here. We'll happily re-open the issue and investigate if you can provide a sample Spring Boot application that reproduces the problem.

**Comment by xenoterracide** [comment]
so I'm `XmlWebApplicationContext` wouldn't be supported in Spring Boot either. I know it's not the default but I thought you could use it... yeah we're going to give up on this until we are further into our JavaConfig migration.

**Comment by hengyunabc** [comment]
We encountered the same problem. 

Can you provide a way to disable `JerseyWebApplicationInitializer`?  

`JerseyWebApplicationInitializer` should be more flexible?
