### ISSUE TITLE
Possible problem with registering of shutdown hooks

### ISSUE THREAD

**Issue by AndreyPleskach** [spring-projects/spring-boot#5744]
We use spring boot 1.3.3
and it seems that ApplicationContext initialize wrong.
So in our case initialization stops on refresh method (application starts undertow container and Kafka consumers) and as result shutdownHooks do not register properly. Class org.springframework.boot.SprinApplication line #361:
```java
// Refresh the context
		refresh(context);
		if (this.registerShutdownHook) {
			try {
				context.registerShutdownHook();
			}
			catch (AccessControlException ex) {
				// Not allowed in some environments.
			}
		}
		return context;
```
As result spring application does not close gracefully.
Any suggestions?

**Comment by wilkinsona** [comment]
AFAIK, `refresh` should always return and we only want to register the hook once we know the context is up and running. If `refresh` isn't returning then there's a bug in your code or ours. Can you please provide a sample project that shows the problem?

**Comment by AndreyPleskach** [comment]
I think that the problem could be on our side as well, but I will try provide you working example. Otherwise I will close this issue asap.

**Comment by AndreyPleskach** [comment]
Yes problem on our side. Thanks for your help
