### ISSUE TITLE
Spring Boot Gradle Plugin Includes Duplicate Jars

### ISSUE THREAD

**Issue by JamesPoli** [spring-projects/spring-boot#5749]
Our company is seeing duplicate jars in the "lib" folder of an executable jar(s).  The problem appears to be at [ProjectLibraries:doWithLibraries](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/repackage/ProjectLibraries.java#L83)

The code tries to "difference" the gradle configurations, but doesn't have a strategy for removing duplicate dependencies with the same group and name but at different versions.  This means if a project has a direct dependency on **b** version 1 at **runtime** and a transitive dependency on **b** version 2 at **compile** then spring boot puts both 1 and 2 into the executable jar.  This can cause issues depending on the order that the jars are included on the classpath.

We've worked around the issue by applying the following DSL:

bootRepackate (
   customeConfiguration = 'runtime'
}

**Comment by wilkinsona** [comment]
Given that the runtime configuration extends the compile configuration, I'm not sure why we're looking at both. We might be able to just use the runtime configuration.

Could you provide a sample project that reproduces the problem? It'll help us to figure out what's going on and to verify that we've solved your problem.

**Comment by JamesPoli** [comment]
Will do, I'm creating the test case right now.

**Comment by JamesPoli** [comment]
Ok, Andy, I've created the pull request, hopefully, I did it right ;).  Jim

**Comment by wilkinsona** [comment]
The fundamental problem is that your build is configured to use two different versions of the same dependency. As things stand, you'll be compiling against one version of the dependency and running your tests against another version. The duplicate jars appearing in the repackaged jar is really just a symptom of that configuration.

That said, an executable jar is intended to contain all of the jars that are required at runtime. In Gradle, that's the contents of the runtime configuration. The runtime configuration extends the compile configuration, so there's no need for us to include both. This is a slightly risky change so I'm only going to make it in 1.4. While you're on 1.3, you should fix your build to use consistent dependency versions across dependencies. You can use a resolution strategy or we have [a plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) that can help which Boot's Gradle Plugin uses and has already applied for you.

**Comment by JamesPoli** [comment]
Thanks Andy for the quick turn-around on this!  Do you know when you'll be publishing 1.4.0.M3?  It currently isn't in http://repo.spring.io/milestone/org/springframework/boot/spring-boot-gradle-plugin/.  Agreed I'll look at a resolution strategy to help identify the exposure of this issue.
Thanks in advance,
Jim

**Comment by wilkinsona** [comment]
Mid-May: https://github.com/spring-projects/spring-boot/milestones

**Comment by JamesPoli** [comment]
Ok, i pulled the latest code and verified Andy's fix works with my use case.

**Comment by JamesPoli** [comment]
Hi Andy, I was waiting for 1.4.0.M3 but never saw it promoted?  Can you tell me if/when this fix will be released?  Thanks in advance, Jim

**Comment by snicoll** [comment]
M3 was released yesterday.

**Comment by JamesPoli** [comment]
Ok thanks, I didn't see it at http://repo.spring.io/libs-release/org/springframework/boot/spring-boot-gradle-plugin/ , where is it at?

**Comment by snicoll** [comment]
That's the release repository not the milestone repository. Check projects.spring.io/spring-boot
