### ISSUE TITLE
Placeholders not replaced in logging configuration

### ISSUE THREAD

**Issue by ufoscout** [spring-projects/spring-boot#5756]
Hi all,

we are using spring-boot 1.3.3. With this logging configuration, the my.logging.level is not resolved if declared in an external properties file, the application.yml file is:
```
logging:
    level:
        ROOT:                WARN
        package1:          ${my.logging.level}
        package2:          ${my.logging.level}
        package3:       ${my.logging.level}
```

The "my.logging.level" value is defined in a properties file loaded by the application through the @PropertySources annotation:
```
@SpringBootApplication
@ComponentScan(basePackageClasses={...})
@PropertySources({
    @PropertySource(value = "file:${pathOnFileSystem}/myExternalConfig.properties"
    , ignoreResourceNotFound = false)
})
@EnableAutoConfiguration
@EnableConfigurationProperties
public class MyApplication {
	public static void main(String[] args) {
		SpringApplication app = new SpringApplication(MyApplication.class);
		app.run(args);
	}
}
```

the myExternalConfig.properties is loaded properly, however, the logging level is not set to what expected and this error is present in the startup output:
```
2016-04-21 09:25:26.007 ERROR 4588 --- [           main] o.s.b.l.LoggingApplicationListener       : Cannot set level: ${my.logging.level} for 'package1'
2016-04-21 09:25:26.008 ERROR 4588 --- [           main] o.s.b.l.LoggingApplicationListener       : Cannot set level: ${my.logging.level} for 'package2'
2016-04-21 09:25:26.008 ERROR 4588 --- [           main] o.s.b.l.LoggingApplicationListener       : Cannot set level: ${my.logging.level} for 'package3'
```

It seems that spring boot initializes the logger before the ${my.logging.level} placeholder is resolved. The issue does not exist if the my.logging.level is defined in the application.yml file; however, in our case it is required to configure the logger in an external file (e.g. not packaged into the embedded jar).
In addition, if all the logging.level entries are moved from the application.yml to the myExternalConfig.properties they are completely ignored.

**Comment by wilkinsona** [comment]
As you have observed, configuration provided via `@PropertySource` is processed too late to influence the logging system's configuration.

> in our case it is required to configure the logger in an external file 

You don't have to use `@PropertySource' to load configuration for an external file. Boot will automatically look for external `application.properties` and `application.yml` files as well. Please see the [externalized configuration documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) for further details.
