### ISSUE TITLE
Upgrade to a version of Spring HATEOAS that's fully compatible with Jackson 2.7

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5759]
See https://github.com/spring-projects/spring-hateoas/issues/438

/cc @olivergierke

**Comment by snicoll** [comment]
This is actually fixed in https://github.com/spring-projects/spring-hateoas/issues/455 so we need Hopper SR2 for this one as well.

**Comment by destan** [comment]
in which version is this solved? currently spring-boot-starter-parent 1.4.0.M3 they are not compatible.

**Comment by wilkinsona** [comment]
As indicated by this issue's milestone, it'll be in 1.4.0.RC1.

**Comment by destan** [comment]
@wilkinsona sorry, I saw the milestone and deleted my comment but you are fast :)
