### ISSUE TITLE
Cannot use spring-boot-devtools if custom spring-session default RedisSerializer.

### ISSUE THREAD

**Issue by FalconIA** [spring-projects/spring-boot#5760]
I use spring-boot 1.3.3 & spring-session 1.1.0.

I custom the default `RedisSerializer` to `GenericJackson2JsonRedisSerializer`.
But `LocalDevToolsAutoConfiguration$RedisRestartConfiguration$RedisRestartConfiguration` replaced all serializer with `RestartCompatibleRedisSerializer`.
Actually it uses `JdkSerializationRedisSerializer` to serialize session data and store in redis.

Now, the only thing i can do it's that to exclude `LocalDevToolsAutoConfiguration` from auto-configuration. Is there any other way to handle this?

**Comment by wilkinsona** [comment]
We might be able to remove `RestartCompatibleRedisSerializer` in 1.4 now that https://jira.spring.io/browse/DATAREDIS-427 has been fixed.

**Comment by wilkinsona** [comment]
DATAREDIS-427 doesn't fix the problem, it just reduces the amount of code we need to write to work around the deserialization problem. We could get rid of the workaround entirely if the default `JdkSerializationRedisSerializer` used the application context's class loader by default.

**Comment by wilkinsona** [comment]
I've opened [DATAREDIS-501](https://jira.spring.io/browse/DATAREDIS-501)

**Comment by philwebb** [comment]
Looks like DATAREDIS-501 has been fixed.

**Comment by snicoll** [comment]
I asked @olivergierke a Hopper SR2 before the RC1. Looks like it can happen.
