### ISSUE TITLE
`autoConfigurationReport` bean doesn't appear in `/beans` endpoint

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#5761]
`autoConfigurationReportEndpoint` bean depends on `autoConfigurationReport` bean and it's included in `/beans` endpoint:

```
  }, {
    "bean" : "autoConfigurationReportEndpoint",
    "scope" : "singleton",
    "type" : "org.springframework.boot.actuate.endpoint.AutoConfigurationReportEndpoint",
    "resource" : "class path resource [org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.class]",
    "dependencies" : [ "autoConfigurationReport" ]
  }, {
```

but `autoConfigurationReport` bean doesn't appear in `/beans` endpoint.

This is the project I used to see the `/beans` endpoint: https://github.com/izeye/spring-boot-throwaway-branches/tree/rest-and-actuator

**Comment by snicoll** [comment]
That bean is registered via `beanFactory.registerSingleton(BEAN_NAME, report);` so maybe we're not getting such beans?

**Comment by wilkinsona** [comment]
We're just using `LiveBeansView` so this probably needs to be raised against Spring Framework

**Comment by wilkinsona** [comment]
Test confirming that programmatically registered singletons are not included in the JSON returned by `LiveBeansView`:

```java
@Test
	public void programaticallyRegisteredSingletonsAreIncludedInLiveBeansView() {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
		context.getBeanFactory().registerSingleton("test", new MyBean());
		context.refresh();

		LiveBeansView view = new LiveBeansView();
		view.setApplicationContext(context);

		assertThat(view.getSnapshotAsJson(), containsString("test"));
	}

	private static class MyBean {

	}
```

It fails with:

```
java.lang.AssertionError: 
Expected: a string containing "test"
     but: was "[
{
"context": "org.springframework.context.annotation.AnnotationConfigApplicationContext@67b64c45",
"parent": null,
"beans": [
]
}]"
```

@izeye Can you please raise a [Spring Framework JIRA](https://jira.spring.io/browse/SPR)?

**Comment by izeye** [comment]
@wilkinsona Sure, I reported it with your test there: https://jira.spring.io/browse/SPR-14199

**Comment by wilkinsona** [comment]
Thanks. We'll pick up the fix as part of our regular dependency updates.
