### ISSUE TITLE
Add property for setForceFirstAndLastRels in application properties

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#5763]
Would it be possible to provide a `spring.hateoas.*` property for setting the `PagedResourcesAssembler ` 	`setForceFirstAndLastRels`?

**Comment by wilkinsona** [comment]
Possibly, although the property should probably be `spring.data.web.*` as it's `@EnableSpringDataWebSupport`, auto-configured by `SpringDataWebAutoConfiguration` that creates the `PagedResourcesAssembler` bean. That said, the property would only be of marginal benefit – it's a one-liner in your own code to call the setter.

**Comment by wilkinsona** [comment]
We've decided not to add a property for this. When using Spring Data REST, `PagedResourcesAssembler` is available as a bean. You can inject that bean, in a configuration class for example, and set the property.
