### ISSUE TITLE
`DataJpaTest` does not invoke flyway

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5766]
I have a project that uses flyway for database initialization. I have the following in my config:

```
spring.jpa.hibernate.ddl-auto=none
```

Now, I want to write a `DataJpaTest` for it. If I try to write a test with such arrangement, I get an SQL exception because the target table does not exist. Poking in the doc, I add the following to my test:

```
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
```

The database is still not initialized. Maybe flyway (and liquibase) should run if we disable the replacement of the datasource. If we don't, maybe the tests should override the `spring.jpa.hibernate.ddl-auto` property.

**Comment by wilkinsona** [comment]
Duplicates #5716
