### ISSUE TITLE
Adding new features section in Spring Boot Documentation

### ISSUE THREAD

**Issue by alimate** [spring-projects/spring-boot#5767]
Spring Framework's documentation has this nice feature that introduces new features of recent versions. This way with a quick glance, we can see what are the new features and how can we use them. This is extra useful for geeks that read the documentation already. With current format of Boot documentation, we either should scroll the documentation all the way down to find a new feature or read the Spring Blog every week.

**Comment by wilkinsona** [comment]
We've deliberately decided not to include a new features section in the documentation. Instead, we publish extensive release notes on the wiki: https://github.com/spring-projects/spring-boot/wiki

**Comment by alimate** [comment]
@wilkinsona Thanks..I wasn't aware of those release notes in the wiki
