### ISSUE TITLE
Actuator: support running multiple MetricsServices (aka consul/hystrix prevents dropwizard from loading)

### ISSUE THREAD

**Issue by joshwand** [spring-projects/spring-boot#5768]
I encountered a curious behavior where when I included spring-cloud-starter-consul-discovery, my dropwizard metrics did not work. This is because the consul module required hystrix, which required servo, which loaded before `MetricsDropwizardAutoConfiguration`, and therefore prevented it from loading since there was already a bean of CounterService.class and GuageService.class loaded. 

All the interfaces in actuator seems to assume only one Counter/Gauge service is available. Instead it would be good to have a Counter/Guage registry and dispatch to all active Counter/Gauge services, so I can use features like hystrix/consul without preventing me from using the metrics library of my choice as well.

**Comment by spencergibb** [comment]
As far as I know consul doesn't require hystrix. It does require spring-cloud-netflix-core which brings in servo. You could disable `org.springframework.cloud.netflix.metrics.servo.ServoMetricsAutoConfiguration` via boot

```
@EnableAutoConfiguration(exclude={ServoMetricsAutoConfiguration.class})
```

I wonder if this is a boot bug or a spring-cloud-netflix one?

**Comment by joshwand** [comment]
It is probably also a spring-cloud-consul bug, but I'd still like the option to use multiple metrics providers anyways (servo for circuit breakers, graphite or datadog for business metrics/alerting, etc).

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
