### ISSUE TITLE
@JsonComponent does not work if I customized Jackson2ObjectMapperBuilder

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#5775]
When I created a custom `Jackson2ObjectMapperBuilder` bean, the `@JsonComponent` does not work. 

I am using Spring Boot 1.4.0M2.

There is a **1.4-upgrade** branch in [my sample codes](https://github.com/hantsy/angularjs-springmvc-sample-boot).

The custom `Jackson2ObjectMapperBuilder` is located in the `Application` class.

[https://github.com/hantsy/angularjs-springmvc-sample-boot/blob/1.4-upgrade/src/main/java/com/hantsylabs/restexample/springmvc/Application.java](https://github.com/hantsy/angularjs-springmvc-sample-boot/blob/1.4-upgrade/src/main/java/com/hantsylabs/restexample/springmvc/Application.java)

The [LocalDateTimeJsonComponent](https://github.com/hantsy/angularjs-springmvc-sample-boot/blob/1.4-upgrade/src/main/java/com/hantsylabs/restexample/springmvc/LocalDateTimeJsonComponent.java) 

The test codes is [LocalDateTimeJsonComponentTest](https://github.com/hantsy/angularjs-springmvc-sample-boot/blob/1.4-upgrade/src/test/java/com/hantsylabs/restexample/springmvc/test/LocalDateTimeJsonComponentTest.java). The `@JsonComponent` is only recognized by Spring when I removed `Jackson2ObjectMapperBuilder`.

**Comment by wilkinsona** [comment]
If you have configured your own `JacksonObjectMapperBuilder` then you're telling Spring Boot's Jackson auto-configuration to (largely) back off. As explained in the javadoc for `@JsonComponent` it takes effect "when `JsonComponentModule` is in use". You haven't configured your object mapper builder with `JsonComponentModule` so it isn't in use. Therefore, `@JsonComponent` has no effect.

You should either remove your own `JacksonObjectMapperBuilder` bean and configure things using `application.properties`, or you should configure the builder with `JsonComponentModule`.

**Comment by hantsy** [comment]
@wilkinsona But the `JacksonObjectMapperBuilder` can load other Modules by default, I also added Java8/JSR310 Module in classpath.

**Comment by hantsy** [comment]
I registered `JsonCompomentModule` **manually**  in my `Jackson2ObjectMapperBuilder` via `modulesToInstall(jsonComponentModule)` and make it works finally.

But I think it is the responsibility of Spring Boot, it should detect the existence of `Jackson2ObjectMapperBuilder`, and install the `JsonCompomentModule`.

The most popular feature of the Spring Boot is **automatic** configurations.

**Comment by wilkinsona** [comment]
Another popular feature of Spring Boot is that the automatic configuration switches off as soon as you indicate that you want to configure something yourself. That's what's happening here.

You have created your own `Jackson2ObjectMapperBuilder` so Spring Boot has stopped creating and configuring one for you. This means that you now get the default behaviour and configuration for a  `Jackson2ObjectMapperBuilder`. As explained in its [javadoc](https://docs.spring.io/spring/docs/4.3.0.RC1/javadoc-api/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.html), it registers the following well-known modules if they are detected on the classpath:

 - jackson-datatype-jdk7
 - jackson-datatype-jdk8
 - jackson-datatype-jsr310
 - jackson-datatype-joda
 - jackson-module-kotlin

If you want to configure your own `Jackon2ObjectMapperBuilder` and you want any other modules to be registered then you will have to do so manually.
