### ISSUE TITLE
@Bean and @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER) on  WebSecurityConfigurerAdapter customizer failed.

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#5777]
I am trying to create `@Bean` and used `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` to declare a `WebSecurityConfigurerAdapter` to customize the Spring Security configuration.

1. Declare a POJO to customzie `WebSecurityConfigurerAdapter `.

               protected static class ApplicationSecurity extends WebSecurityConfigurerAdapter {}

2. Delcare it as a  `@Bean` and used `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` .

		public WebSecurityConfigurerAdapter securityConfig(UserRepository userRepository, PasswordEncoder passwordEncoder) {
			return new ApplicationSecurity(userRepository, passwordEncoder) {};
		}

It will fail and it will report the duplicated bean in the order.

But i the current codes in the `Application` works. It uses tranditional `@Configuration` with `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)`

[Application](https://github.com/hantsy/angularjs-springmvc-sample-boot/blob/1.4-upgrade/src/main/java/com/hantsylabs/restexample/springmvc/Application.java)

The sample is hosted on my github, there is a 1.4-upgrade branch to taste Spring Boot 1.4.0M2/Spring Security 4.1.0.RC2.

**Comment by philwebb** [comment]
You can't use `@Order` on `@Bean` methods, it has to be used on the actual bean class.

So if you're saying you have this:

```java
@Bean
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
public WebSecurityConfigurerAdapter securityConfig(UserRepository userRepository, PasswordEncoder passwordEncoder) {
    return new ApplicationSecurity(userRepository, passwordEncoder) {};
}
```

You need to move that `@Order` annotation directly to your `ApplicationSecurity` class.

**Comment by aCoder2013** [comment]
But my bean is from 3rd library,so it's not possible to do that.
I had a ugly way,though,register the bean in a class that implements ApplicationListener
