### ISSUE TITLE
spring boot create a Jersey info when starting server, although no Jersery was used

### ISSUE THREAD

**Issue by winterelf** [spring-projects/spring-boot#5778]
This issue is related to StackOverflow issue i posted:
http://stackoverflow.com/questions/36797161/why-jersey-is-showing-on-my-spring-boot-mvc/36798699?noredirect=1#comment61197131_36798699

I have nothing else to add. I can provide the full startup log.

**Comment by philwebb** [comment]
The log message comes from Spring's `SpringServletContainerInitializer`, it's harmless but a little confusing. I've raised [SPR-14213](https://jira.spring.io/browse/SPR-14213) to see if we can offer conditional support for `WebApplicationInitializers`.

**Comment by wilkinsona** [comment]
A change has been made in Spring Framework 4.2.6 (and 4.3). We'll pick that up as part of #5322.
