### ISSUE TITLE
Spring Boot OAuth2 sample will not accept what Developer Guide suggests

### ISSUE THREAD

**Issue by DelGatos** [spring-projects/spring-boot#5781]
This <a href="https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2"> Spring Boot Oauth2 sample app</a> breaks when a `GlobalAuthenticationConfigurerAdapter` is used to connect a custom `UserDetailsService` to it.  This is a bug in either:  
  
    1.) the Spring Boot Oauth2 binaries  
    2.) the documentation
    3.) the sample apps  
    4.) or some combination thereof.  
  
The <a href="http://projects.spring.io/spring-security-oauth/docs/oauth2.html#grant-types">Spring Boot OAuth2 Developer Guide</a> says to use a `GlobalAuthenticationManagerConfigurerAdapter` to hook up a custom `UserDetailsService`, but does not explain how to do so, and does not provide any examples.    
  
Similarly, the sample apps do not provide any examples, because the <a href="http://projects.spring.io/spring-security-oauth/docs/oauth2.html#grant-types">tut-spring-security-and-angular-js</a> samples, and the <a href="https://github.com/spring-projects/spring-security-oauth/tree/master/samples">sprklr and tonr example apps</a> do not use custom `UserDetailsService`, so there are no examples on the web of Spring Boot OAuth2 apps that successfully use `GlobalAuthenticationManagerConfigurerAdapter`s to hook up custom `UserDetailsService`s.  
  
When I try to use a `GlobalAuthenticationManagerConfigurerAdapter` to connect a custom `UserDetailsService` to the <a href="https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2/authserver">authserver sample app</a>, the following compilation error results when I try to launch the revised app using `mvn spring-boot:run`:  
   
    nested exception is java.lang.NoSuchMethodException:    
    demo.AuthserverApplication$WebSecurityConfiguration$$EnhancerBySpringCGLIB$$43683c11.<init>()   
  
The <a href="https://jumpshare.com/v/fBM6hYgwVi0i90a9lD2Z">complete log from the Spring Boot console is several pages long and is too long to post here, but can be read in its entirety at a file sharing site by clicking on this link</a>.  

The steps for reproducing this problem are:  
  
1.) Download the Spring Oauth2 sample apps onto your computer by typing:  
  
    git clone https://github.com/spring-guides/tut-spring-security-and-angular-js/  
    
2.) Navigate to `tut-spring-security-and-angular-js/tree/master/oauth2/authserver`.  This is the app that is breaking.  When you type `mvn spring-boot:run` without making any changes, it should launch correctly.  But then make the following changes to re-create the problem:  
  
3.) Added the following to `AuthserverApplication.java` to connect a custom `UserDetailsService`:  
  
    @Configuration
    class WebSecurityConfiguration extends GlobalAuthenticationConfigurerAdapter {
    
        @Autowired
        Users users;
  
        @Override
        public void init(AuthenticationManagerBuilder auth) throws Exception {
            auth.userDetailsService(users);
        }
  
    }
  
4.) Add the following `Users.java` class to <a href="https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2/authserver/src/main/java/demo">the `demo` package of the `authserver` app</a>, so that the `GlobalAuthenticationConfigurerAdapter` from **3** above points to a real custom `UserDetailsService`.  Note that I unhooked the JDBC so that there is no database dependency in this code sample:  
  
    package demo;

    import java.util.List;
    import org.springframework.security.core.GrantedAuthority;
    import org.springframework.security.core.authority.AuthorityUtils;
    import org.springframework.security.core.userdetails.UserDetails;
    import org.springframework.security.core.userdetails.UsernameNotFoundException;
    import org.springframework.security.provisioning.UserDetailsManager;
    import org.springframework.stereotype.Service;

    @Service
    class Users implements UserDetailsManager {

        @Override
        public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
            String password;
            List<GrantedAuthority> auth = AuthorityUtils.commaSeparatedStringToAuthorityList("ROLE_USER");
            if (username.equals("Samwise")) {
                auth = AuthorityUtils.commaSeparatedStringToAuthorityList("ROLE_HOBBIT");
                password = "TheShire";
            }
            else if (username.equals("Frodo")){
                auth = AuthorityUtils.commaSeparatedStringToAuthorityList("ROLE_HOBBIT");
                password = "MyRing";
            }
            else{throw new UsernameNotFoundException("Username was not found. ");}
            return new org.springframework.security.core.userdetails.User(username, password, auth);
        }

        @Override
        public void createUser(UserDetails user) {// TODO Auto-generated method stub
        }

        @Override
        public void updateUser(UserDetails user) {// TODO Auto-generated method stub
        }

        @Override
        public void deleteUser(String username) {// TODO Auto-generated method stub
        }

        @Override
        public void changePassword(String oldPassword, String newPassword) {
            // TODO Auto-generated method stub
        }

        @Override
        public boolean userExists(String username) {
            // TODO Auto-generated method stub
            return false;
        }
    }
  
The complete code of the modified `AuthserverApplication.java`, including the new `GlobalAuthenticationConfigurerAdapter` <a href="https://jumpshare.com/v/Xu2yl7qnvFWxzWuklp2N">can be found at a file sharing site by clicking on this link</a>.
  
5.) Type `mvn spring-boot:run` to try to launch the `authserver` app.  This will trigger the `nested exception is java.lang.NoSuchMethodException: demo.AuthserverApplication$WebSecurityConfiguration$$EnhancerBySpringCGLIB$$43683c11.<init>()` error described above.    
    
_**What specific changes need to be made to the code above in order for a custom UserDetailsService to be successfully connected to the `authserver` sample app?**_   This functionality should also be demonstrated in the Developer Guide and Sample Apps in the links above, because a custom UserDetailsService is necessary for any real world implementation of these APIs.

**Comment by snicoll** [comment]
There is an [issue tracker](https://github.com/spring-guides/tut-spring-security-and-angular-js/issues) for this project. Please move your issue there.
