### ISSUE TITLE
RoleHierarchy is ommited in OAuth2ExpressionHandlerInjectionPostProcessor

### ISSUE THREAD

**Issue by miyamoto-daisuke** [spring-projects/spring-boot#5785]
`RoleHierarchy` is omitted when the `OAuth2ExpressionHandlerInjectionPostProcessor` replace `DefaultMethodSecurityExpressionHandler` to `OAuth2MethodSecurityExpressionHandler`.

[See OAuth2MethodSecurityConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/method/OAuth2MethodSecurityConfiguration.java#L93)

`bean`'s `roleHierarcy` object should be copied to `handler` same as `PermissionEvaluator` as following:

```java
handler.setExpressionParser(bean.getExpressionParser());
handler.setRoleHierarcy(bean.getRoleHierarchy());
```

**Comment by philwebb** [comment]
@rwinch Is there any reason why `AbstractSecurityExpressionHandler.getRoleHierarchy()` is (or has to be) `protected`?

**Comment by rwinch** [comment]
Is there a reason you need it to be public? Typically I would recommend keeping a reference to `RoleHiearchy` and setting that on every pojo vs trying to use an accessor from a particular bean (which can lead to eager instantiation issues).

**Comment by philwebb** [comment]
Thanks @rwinch, we'll grab it from the context.

**Comment by wilkinsona** [comment]
The `RoleHierarchy` is already set when there is a `RoleHierarchy` bean in the context. This is done in `afterSingletonsInstantiated` on `GlobalMethodSecurityConfiguration`. Furthermore, it also sets the `PermissionEvaluator` using the bean in the context so there's some redundant logic in `OAuth2ExpressionHandlerInjectionPostProcessor`.
