### ISSUE TITLE
@ConditionalOnProperty annotation is not @Documented

### ISSUE THREAD

**Issue by vincent-vieira** [spring-projects/spring-boot#5786]
Hello folks,

Just noticed while generating my javadocs that the [@ConditionalOnProperty](https://github.com/spring-projects/spring-boot/blob/1.3.x/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java) annotation is not currently annotated with [@Documented](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Documented.html). 

That a very very trivial problem but also kinda problematic as it's important to document this annotation when using meta-annotation based configuration imports with Spring Boot.

Saw the same problem using **Spring Boot 1.3.2.RELEASE and upper versions** with [@ConditionalOnExpression](https://github.com/spring-projects/spring-boot/blob/1.3.x/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnExpression.java) too.

All other annotations based on @ConditionalOn... Are properly annotated.

Have a nice day,
Vincent

**Comment by philwebb** [comment]
Thanks for reporting.
