### ISSUE TITLE
Add AnnotationIntrospector customization to ObjectMapper

### ISSUE THREAD

**Issue by poznachowski** [spring-projects/spring-boot#5787]
I'd like to be able to provide custom `AnnotationIntrospector` to ObjectMapper, while keeping all the `Jackson2ObjectMapperBuilder` default configuration goodies. Currently, it seems that I'm forced to copy whole definition of `@Bean jacksonObjectMapperBuilder` and set annotationIntrospector there.

If I'm not missing anything, I'd be glad to contribute. My idea is to make autoconfigured `Jackson2ObjectMapperBuilder` pick up and use `AnnotationIntrospector @Bean` (if provided).
Or more generic approach by providing a customizer (similar to Jersey's `ResourceConfigCustomizer`), which would pop in after all default configuration.

**Comment by philwebb** [comment]
A contribution would be most welcome. I like the `Jackson2ObjectMapperBuilderCustomizer` idea the best.

**Comment by poznachowski** [comment]
Ok, I'll work on that.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#5803).
