### ISSUE TITLE
Hook Logback with sentry programatically

### ISSUE THREAD

**Issue by thefallentree** [spring-projects/spring-boot#5795]
Hi,

We are trying to hook Logback in spring-boot with Sentry (it has a logback appender) and we have been successful using logback.xml.

However, we want to use programmatic configuration instead of XML (because we are implementation this in a library used by all our servers.)  We are having several problems:

1. Attempting to configure LogBack context before SpringBoot initialization has no effect, because spring boot will clear out ROOT logger's appender. 

2. We then added a AppliecationReady/ ContextRefreshed event to attempt reconfigure Logback with additional Sentry appender after spring boot initialization, but was surprised to find it doesn't work either, the appender is there, but is not sending log.

What  is the preferred and correct way to hook into springboot's LogBackLoggingSystem initialization? There has been no such hook provided and  we don't really need to get access to LoggingSystemContext, we can simply  use getLoggerFactory() ourselves to grab the running logback instance.

Thanks

**Comment by philwebb** [comment]
We do initialization in the `LoggingApplicationListener`, perhaps that can give you some hints. You might also want to look at `DefaultLogbackConfiguration` which programmatically adds appenders. Since your appender has been added, I wonder if there is something wrong with the way you're registering it?

**Comment by thefallentree** [comment]
We've solved the issue,  we are currently using  ApplicationPrepared Event  same way as LoggingApplicationLIstenr to configure logback. 

Thanks for the information.
