### ISSUE TITLE
Spring Boot + JSF packaging as a JAR (Not as a WAR)

### ISSUE THREAD

**Issue by mtbadi39** [spring-projects/spring-boot#5799]
Hi;
There are many examples for Spring Boot + JSF packaged as **WAR** provided [Here](https://github.com/stephanrauh/JSF-on-Spring-Boot) and [here](https://github.com/rajjaiswalsaumya/SpringBootPrimeFaces) and [here](https://github.com/dasAnderl/SpringBootPrimefacesGradle).
but when trying to package them as **JAR,** things doesnt works !
The main problem was described [here](http://stackoverflow.com/questions/29461109/spring-boot-jsf-packaging-as-a-jar).
Our main goal to do this was **Wrapping our application as a Windows Service**.
Thanks !

**Comment by philwebb** [comment]
I'm afraid we don't currently support JSF officially with Spring Boot.

**Comment by mtbadi39** [comment]
I know thats [JSF and Spring MVC are are fully competitors. we cannot mix them and we should choose the one or the other.](http://stackoverflow.com/questions/18744910/using-jsf-as-view-technology-of-spring-mvc#18745266)
But may be its time for Spring Boot to support some components based frameworks [out of the box](https://en.wikipedia.org/wiki/Out_of_the_box_(feature))  (ex : PrimeFaces, ICEFaces, ...etc)

**Comment by wilkinsona** [comment]
@mtbadi39 Given that it works when packaged as a war, why not do that? You can build an executable war and then run it in the same way as you'd run an executable jar (`java -jar`).

**Comment by mtbadi39** [comment]
@wilkinsona thanks for interest
Maybe you should look [here](https://github.com/spring-projects/spring-boot/issues/519) and [here](http://stackoverflow.com/questions/24124062/spring-boot-jar-as-windows-service) and [here](http://www.develmagic.com/2016/02/25/spring-boot-running-as-a-windows-service) : Its working with **Jar** but not with **War**

**Comment by persapiens** [comment]
Hi @mtbadi39 ,

There is no built in Spring Boot Starter to integrate JSF, but Spring Boot references [one Community Contribution](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters) called [JoinFaces](http://joinfaces.org).

You could try [JoinFaces Example](https://github.com/joinfaces/joinfaces-example) also.

**Comment by mtbadi39** [comment]
thanks  @persapiens , i will try it
