### ISSUE TITLE
Upgrading to tomcat-embeded-websocket-8.5.x dependency

### ISSUE THREAD

**Issue by katyatalluri** [spring-projects/spring-boot#5813]
I am looking for a spring-boot-starter-web module that uses tomcat-embeded-websocket-8.5.x. I see that even the latest version of spring-boot-starter-web, still uses 8.0.x. 

For my requirements, I need work around a proxy to post websocket data--an enhancement that was introduced only in tomcat-embeded-websocket-8.5.x and not lower. 

I tried several work arounds, but find that even the latest version of spring-boot-starter-web is not compatible with the 8.5.x version of tomcat-embeded-websocket.

**Comment by philwebb** [comment]
According to http://tomcat.apache.org/whichversion.html version 8.5.0 is a beta release so it's unlikely that we'll support it officially in Spring Boot just yet.

What specific problems are you seeing with Tomcat 8.5?

**Comment by katyatalluri** [comment]
Hi Phil,
Thanks for your response. To give you further context....
I have a utility java application that uses Tomcat 8.5 for posting websocket data through a proxy. I am able to configure the proxy only using Tomcat 8.5 as previous versions of Tomcat don't support proxy. I am able to post websocket data without any difficulty through this app by itself (through test cases).
I have a spring boot application that uses the above mentioned utility java application as a dependency (through which it posts websocket data). However, when the Spring boot application loads, it loads the tomcat 8.0 version jar with it. I tried to override it with 8.5, but that causes issues. Spring boot references specific methods in the tomcat 8.0 version that are not present in 8.5. So I get "method not found" exception. 
Thanks,Katya 

    On Wednesday, April 27, 2016 11:50 AM, Phil Webb <notifications@github.com> wrote:
 

 According to http://tomcat.apache.org/whichversion.html version 8.5.0 is a beta release so it's unlikely that we'll support it officially in Spring Boot just yet.What specific problems are you seeing with Tomcat 8.5?—

**Comment by jhoeller** [comment]
This is probably the same issue that we're tracking here: https://jira.spring.io/browse/SPR-14078 - essentially, Tomcat 8.5.0 accidentally removed some API which will be re-introduced in 8.5.1.

**Comment by katyatalluri** [comment]
Yes, that appears to the same issue.
Thanks,Katya 

    On Wednesday, April 27, 2016 12:18 PM, Juergen Hoeller <notifications@github.com> wrote:
 

 This is probably the same issue that we're tracking here: https://jira.spring.io/browse/SPR-14078 - essentially, Tomcat 8.5.0 accidentally removed some API which will be re-introduced in 8.5.1.—
