### ISSUE TITLE
@ConditionalOnMissingBean specifies no bean in EmbeddedMongoAutoConfiguration.java

### ISSUE THREAD

**Issue by beckyb8** [spring-projects/spring-boot#5817]
I'm using Spring-Boot 1.3.3 and Spring 4.2.5. I have a unit test that fails because an `@ConditionalOnMissingBean` in `EmbeddedMongoAutoConfiguration.java` does not specify any bean.

```
java.lang.IllegalStateException: Error processing condition on
org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoRuntimeConfig
...
Caused by: 
java.lang.IllegalArgumentException: @ConditionalOnMissingBean 
    annotations must specify at least one bean (type, name or annotation)
```

If we open `EmbeddedMongoAutoConfiguration.java` and search for `embeddedMongoRuntimeConfig()` we see:

```
	@Bean
	@ConditionalOnMissingBean
	@ConditionalOnClass(Logger.class)
	public IRuntimeConfig embeddedMongoRuntimeConfig() {
```

Note that `@ConditionalOnMissingBean` is not specifying anything at all. There are three such cases in the file.

**Comment by wilkinsona** [comment]
You don't actually need to specify a bean or a type as should be deduced from the method's return type. In this case that means that it's conditional on there being no `IRuntimeConfig` bean. What the error message is actually trying to say is that the deduction failed. It's been improved in https://github.com/spring-projects/spring-boot/issues/4934 to make that clearer and to include details of the deduction failure.

In the meantime, enabling debug logging will let you see the deduction failure. It'll be logged with a message beginning "Unable to deduce bean type for". If you let us know what that message says, it should give us enough info to figure out what's going wrong in your test.

**Comment by beckyb8** [comment]
I followed your advice and saw the missing class; once I knew that, a fix was trivial and I successfully executed my test.

Thank you for the speedy and effective response. I look forward to 1.4!

**Comment by johnnybionic** [comment]
Hi, I had the same problem, it was because I hadn't included the 'de.flapdoodle.embed.mongo' artifact :) That wasn't entirely obvious, so I thought I'd comment in case anyone else did the same. Cheers!
