### ISSUE TITLE
Use jetty 9.3.x as default version

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#5825]
The jetty team has announced that 9.2.x will be EOL as of May 2016.
https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02726.html

It seems reasonable the default version supported by spring-boot to become 9.3.x. There are already samples for 9.3.x so this should be easy.

Jetty 9.3.x brings support for http/2, but also requires java 8 (while 9.2 was java 7).

The only issue so far that I have experienced with jetty 9.3 is that classpath keystores are not working with spring boot loader. I have raised eclipse/jetty.project#518 to address this.

**Comment by cemo** [comment]
It required jdk8 (Spring Boot supports JDK7) . There are some other news as well in Jetty land:


> Greg Wilkins:
> 
> So we now have come up with a release plan, that unless we receive howls of complaint will be enacted:
> The master branch will be forked to a jetty-9.4.x branch with it's current feature set.
> A 9.4.0.M0 release will be made in the next week, RC releases next month with the plan for a GA release end of the quarter!
> master branch will be updated to build 10.0.0-SNAPSHOT
> Servlet 4.0, websocket and config changes will happen in 10.0.x
> We would expect 10.0.0-M0 releases toward the end of the calendar year
> We plan to create the 9.4.x branch by the end of the week, but will first re-review the outstanding pull requests to merge anything that should be merged against master first.

**Comment by wilkinsona** [comment]
> keystores are not working with spring boot loader. I have raised eclipse/jetty.project#518 to address this.

Thanks for raising the Jetty issue. Ignoring any other concerns, that's a blocker on making 9.3 the default.

**Comment by wilkinsona** [comment]
The Jetty issue has been fixed and will be in 9.3.9. Placing this on hold until it's available.

**Comment by tsachev** [comment]
@wilkinsona  9.3.9 was released today

**Comment by wilkinsona** [comment]
Thanks

**Comment by bclozel** [comment]
I'll merge #5290 right after that one, since I believe jetty examples should be renamed from "jetty" and "jetty93" to "jetty92" and "jetty", 9.3 being the new default version.

**Comment by wilkinsona** [comment]
@bclozel Feel free to merge yours first
