### ISSUE TITLE
Duplicate entries in Appendix E. Dependency versions

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#5827]
In Appendix E. Dependency versions, the following entries are duplicate:

```
spring-orm
spring-boot
spring-boot-test
```

See http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#appendix-dependency-versions

**Comment by wilkinsona** [comment]
Thanks, @izeye. `spring-orm` isn't a duplicate as far as I can tell. There's `spring-orm` and `spring-oxm`. I suspect the other two are due to classifiers.

**Comment by izeye** [comment]
@wilkinsona Oops, you're right.
