### ISSUE TITLE
Upgrade to Cassandra Driver 3

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#5835]
People are starting to upgrade their servers to Cassandra 3, even 3.5. The current version of the Datastax driver limits servers to 2.2. Zipkin recently had to update the driver due to demand for running newer versions of Cassandra.

If people are using CQL, driver version 3 works with at least 2.2-3.5. There's compatibility notes, if folks are using the raw protocol.

http://www.datastax.com/dev/blog/datastax-java-driver-3-0-0-released

**Comment by philwebb** [comment]
@wilkinsona thoughts for 1.4?

**Comment by adriancole** [comment]
3.0.1 just off the press :)

https://github.com/datastax/java-driver/tree/3.0.1/changelog

**Comment by adriancole** [comment]
ps the file that coerced to an older version was the bom here: https://github.com/spring-projects/spring-boot/blob/322b1b2f658c99ba0999841505fddcf9446160f2/spring-boot-dependencies/pom.xml#L55

**Comment by wilkinsona** [comment]
As with all other Spring Data modules, I think we should follow Spring Data Cassandra's lead. It's still using 2.x.

**Comment by adriancole** [comment]
Looks like this is the issue from there:
https://jira.spring.io/browse/DATACASS-271

**Comment by wilkinsona** [comment]
Thanks, @adriancole. Judging by the labels that issue is targeted at Spring Data Ingalls so we'll upgrade the Cassandra driver as part of that upgrade. It'll be post 1.4, though. There has been some discussion about a Boot 1.5 to pick up Ingalls.

**Comment by mp911de** [comment]
The upgrade of Spring Data Cassandra to 3.0 does not impose breaking changes for now. Tested the upgrade with Boot 1.3.3 and 1.4.0-SNAPSHOT.
