### ISSUE TITLE
Document possible for Application Properties

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#5839]
At the moment it is not easy to know possible values for certain [Application Properties](http://docs.spring.io/spring-boot/docs/1.4.0.M2/reference/htmlsingle/#common-application-properties) if your IDE does not support auto completion (i.e. Standard Eclipse, Community version of IntelliJ, etc).

Some properties already document the possible values (i.e. `security.headers.hsts`), but others don't (i.e. `spring.session.store-type`). It would be nice if enumerated values were always documented in the the appendix.

**Comment by wilkinsona** [comment]
I'm not convinced (yet) that we should do this. Before we could consider it, I think we'd need to be auto-generating the appendix from the metadata.

**Comment by philwebb** [comment]
I'm not keen in general, I have the feeling that throwing everything in the appendix will ultimately make it less useful.

**Comment by snicoll** [comment]
I share that sentiment. Especially with the current format, listing all possible values can actually bloat the whole thing.

**Comment by philwebb** [comment]
I'm afraid the general consensus is that this will probably make things worse. We'll can try to improve discoverability if we ever manage to get that section auto-generated.
