### ISSUE TITLE
spring-boot-dependencies jackson version incorrect for jackson-datatype-jdk7

### ISSUE THREAD

**Issue by ergh99** [spring-projects/spring-boot#5840]
The `1.4.0.BUILD-SNAPSHOT` version of `spring-boot-dependencies/pom.xml` uses the `jackson.version` property for the version of all jackson artifact dependencies.  However, `jackson-datatype-jdk7` doesn't appear to have had a release past `2.6.6` according to [mvnrepository.com](http://mvnrepository.com/artifact/com.fasterxml.jackson.datatype).  This causes the build to break during dependency marshaling.

**Comment by philwebb** [comment]
My guess is because Jackson 2.7 [now has JDK 7 as a baseline](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7#changes-compatibility). We should probably just drop this one as a managed dependency.

**Comment by wilkinsona** [comment]
This should have broken the Platform's build (it checks that every managed dependency can be resolved). I'd like to understand why that didn't happen before fixing this issue.

**Comment by wilkinsona** [comment]
The culprit was what should have been a temporary workaround for https://github.com/FasterXML/jackson-datatype-jdk7/issues/6. I've removed that and the Platform build now breaks as expected.

**Comment by wilkinsona** [comment]
Fixed in 5a730a916c1e79c47d8e714638ad67630833bd19
