### ISSUE TITLE
DataSourcePublicMetrics reporting wrong values for "usage"

### ISSUE THREAD

**Issue by sebastiankirsch** [spring-projects/spring-boot#5845]
We're using `DataSourcePublicMetrics` to report metrics to statsd.
We found that the reported value is unrealistically high (at times reporting a usage of 50%, when max pool size is constantly at 100 and DB has merely 8 connections open in total), and implemented our own metric that comes closer to reality (at least as we perceive it).

At first glance, our custom implementation does practically the same as the `DataSourcePublicMetrics`:

    static class DataSourceMetrics implements PublicMetrics {
        private final DataSource tomcatDataSource;
        public DataSourceMetrics(javax.sql.DataSource dataSource) {
            if (!DataSource.class.isInstance(dataSource)) {
                log.warn("We are not using tomcat-jdbc for connection pooling (found class {}), cannot register datasource metrics!",
                        dataSource.getClass().getName());
                tomcatDataSource = null;
            } else {
                tomcatDataSource = DataSource.class.cast(dataSource);
            }
        }
        @Override
        public Collection<Metric<?>> metrics() {
            if (tomcatDataSource == null) {
                return Collections.emptyList();
            }
            return Arrays.asList(
                    new Metric<>("datasource.my.usage", (float) tomcatDataSource.getActive() / tomcatDataSource.getMaxActive()),
                    /* */);
        }
    }

I'm sorry I can't come up with a test case or something. The way we integrate the `DataSourcePublicMetrics` is:

    /**
     * Exports the {@link org.springframework.boot.actuate.endpoint.PublicMetrics} that are automatically set up by
     * {@link PublicMetricsAutoConfiguration}.
     */
    @Autowired
    @Bean
    public MetricsEndpointMetricReader metricsEndpointMetricReader(MetricsEndpoint metricsEndpoint) {
        return new MetricsEndpointMetricReader(metricsEndpoint);
    }

**Comment by snicoll** [comment]
Just to make things clear. You have a custom implementation of the metrics that doesn't work and you're thinking our is wrong as well. Am I getting this right? How are we supposed to investigate with no further details?

**Comment by sebastiankirsch** [comment]
Sorry if I put that wrong: our custom implementation seems to be reporting the correct value.

**Comment by snicoll** [comment]
Ah, ok. Alright, let's see what the differences are then...

**Comment by snicoll** [comment]
I had a look and though our code is using `datasource.getPool().getActive()` and yours is using `datasource.getActive()` it turns out to call the exact same method. I would completely remove statsd from the picture and use the `metrics` actuator endpoint. I fail to see why your solution is "better" than what we currently have. Can you share an example that demonstrates this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sebastiankirsch** [comment]
Sorry, we're not using the endpoint, thus it took me some time to make it available.
Actually, the endpoint seems to provide identical results for both metrics. I've been comparing it for a few hours now; from what I remember, the difference was showing up at least every five minutes.
So I went back to statsd/grafana and the data there turned out be identical as well for the last week. Unfortunately, we dump data older than one week, so I cannot provide you the numbers that have started this quest in the first place :/
It feels awkward to say, but I can't provide you with any data right now. Given that there's no difference anymore, I'll get rid of our custom implementation and get back to you as soon this seemingly unrealistic behaviour shows up again. Thanks for your time.
