### ISSUE TITLE
`@WebMvcTest` does not initialize the logging system

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5847]
If I use `@WebMvcTest` I can see a lot of debug logs in a vanilla project. That's not happening with `@DataJpaTest`. It looks like the former doesn't initialize the `LoggingSystem` while the later does.

**Comment by wilkinsona** [comment]
`@DataJpaTest` is bootstrapped by `SpringBootTestContextBootstrapper` with uses `SpringBootContextLoader` as the default context loader. `@WebMvcTest` is bootstrapped by `WebMvcTestContextBootstrapper` (a `SpringBootTestContextBootstrapper` subclass) and overrides the default to be `WebDelegatingSmartContextLoader`. 

Removing the override such that `WebMvcTestContextBootstrapper` uses `SpringBootContextLoader` as its default context loader seems to work – the logging system is initialized and `spring-boot-test-autoconfigure` still builds cleanly. I may well be missing something though.
