### ISSUE TITLE
InteractiveAuthenticationSuccessEvent is not handled

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5850]
See https://github.com/spring-projects/spring-security/issues/3857

We should fix Spring Boot where it expects an `AuthenticationSuccessEvent` to _also_ take that event type into account if the spring security team confirms this is an issue.

**Comment by snicoll** [comment]
Actually it turns out to be an unfortunate name issue rather than something we should be dealing with.

**Comment by webcane** [comment]
InteractiveAuthenticationSuccessEvent handled by UsernamePasswordAuthenticationFilter only.
