### ISSUE TITLE
<springProfile> logback element with a list of excluded names not working as expected

### ISSUE THREAD

**Issue by gyszalai** [spring-projects/spring-boot#5851]
I use Spring-Boot 1.3.2 with Oracle Java8u31.

I would like my application to log to the standard output if local or ci profiles are active and to log to a
daily rolled logfile otherwise. I have the following configuration:

```xml
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <springProfile name="local, ci">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
           ...
        </appender>
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
    </springProfile>

    <springProfile name="!local, !ci">
        <appender name="ROLLINGFILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            ...
        </appender>
        <root level="INFO">
            <appender-ref ref="ROLLINGFILE"/>
        </root>
    </springProfile>

</configuration>
```

It seems that if I specify multiple excluded profile names (!local, !ci) both the STDOUT and 
ROLLINGFILE appenders are printing logs. Is it a bug or I misunderstand the documentation?

**Comment by wilkinsona** [comment]
`!local, !ci` is saying that you want the rolling appender to be enabled if the local profile is not active or the ci profile is not active. This behaviour matches Spring Framework's standard profile behaviour. See [`Environment.acceptsProfiles`](http://docs.spring.io/spring-framework/docs/4.2.5.RELEASE/javadoc-api/org/springframework/core/env/Environment.html#acceptsProfiles-java.lang.String...-) for more details.

**Comment by gyszalai** [comment]
Oh, thanks! I was unaware that its OR and not AND. I'll read the docs more carefully.
