### ISSUE TITLE
Open-source serious and complete websites created with Spring as a server-side framework

### ISSUE THREAD

**Issue by dossan** [spring-projects/spring-boot#5856]
Hi!

I was looking for open-source serious and complete websites created with Spring(Boot) as a server-side framework. I need to have a look at the source code, since I'm very confused about a few things. If I ask this on SO, they would just down-vote or close my question, so that's why I'm asking here.

Thanks.

**Comment by wilkinsona** [comment]
spring.io is open source: https://github.com/spring-io/sagan. You might also like to ask on Gitter.
