### ISSUE TITLE
Allow customization of RestTemplate in JwtTokenServicesConfiguration

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-boot#5859]
I want to use a load balanced (Ribbon) client to fetch the JWT key from another service. However, the `RestTemplate` used is [`JwtTokenServicesConfiguration.keyUriRestTemplate`](https://github.com/spring-projects/spring-boot/blob/19d8c5e6f649987a54f4d1834de57b6dfb18b969/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L254) which can't be configured.

I'd be willing to submit a patch but what's the way to go here? Add a `JwtTokenServicesConfigurer` just like [`JwtAccessTokenConverterConfigurer`](https://github.com/spring-projects/spring-boot/blob/19d8c5e6f649987a54f4d1834de57b6dfb18b969/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/JwtAccessTokenConverterConfigurer.java)?

There is a similar option for [`UserInfoRestTemplateConfiguration`](https://github.com/spring-projects/spring-boot/blob/19d8c5e6f649987a54f4d1834de57b6dfb18b969/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L89) using [`UserInfoRestTemplateCustomizer`](https://github.com/spring-projects/spring-boot/blob/19d8c5e6f649987a54f4d1834de57b6dfb18b969/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/UserInfoRestTemplateCustomizer.java) that is used by [`OAuth2LoadBalancerClientAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-security/blob/0fbadd3a7300035cb3af25ab56a889086fcbb09c/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/client/OAuth2LoadBalancerClientAutoConfiguration.java) ([spring-cloud-security](https://github.com/spring-cloud/spring-cloud-security)) to add the `LoadBalancerInterceptor`.

There is no such option for the `@Primary OAuth2RestTemplate` which is configured in [`OAuth2RestOperationsConfiguration`](https://github.com/spring-projects/spring-boot/blob/19d8c5e6f649987a54f4d1834de57b6dfb18b969/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2RestOperationsConfiguration.java#L73). But at least this one can be injected.

**Comment by philwebb** [comment]
Probably a question for @dsyer.

**Comment by dsyer** [comment]
How would you want to customize it (what's the use case)? The token key should be public.

**Comment by sfussenegger** [comment]
While it should be public it certainly wouldn't hurt to be available in a load-balanced fashion internally. Services might be firewalled so accessing the key through its public URL might not be allowed further complicating the matter. 

But even if it is, it's just simpler to rely on existing service registration. Assume the JWT key URL could be `security.oauth2.resource.jwt.key-uri=http://auth/oauth/token_key`. Now this URL does not have to change across staging or production environments etc. 

To make this possible, I believe all it would take is something like this:

    @Configuration
    @ConditionalOnBean(LoadBalancerInterceptor.class)
    @ConditionalOnProperty(prefix = "security.oauth2.resource.jwt", value = "load-balanced", havingValue = "true", matchIfMissing = true)
    public static LoadBalancedJwtKeyTemplate implements JwtAccessTokenTemplateConfigurer {

      @Autowired
      private LoadBalancerInterceptor loadBalancerInterceptor;

      public void configure(RestTemplate template) {
        List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>(template.getInterceptors());
        interceptors.add(loadBalancerInterceptor);
        template.setInterceptors(interceptors);
      }

    }

And of course the customizing code in `JwtTokenServicesConfiguration`:

    @Autowired(required = false)
    private List<JwtAccessTokenTemplateConfigurer> templateConfigurers = Collections.emptyList();

    private String getKeyFromServer() {
      RestTemplate keyUriRestTemplate = new RestTemplate(); // no need to keep alive afterwards
      AnnotationAwareOrderComparator.sort(this.templateConfigurers);
      for (JwtAccessTokenTemplateConfigurer configurer : this.templateConfigurers) {
        configurer.configure(converter);
      }
      // SNIP: existing code from getKeyFromServer()
    }

**Comment by dsyer** [comment]
I see. So this is a Spring Cloud feature really (the load balancing), enabled by a new one here (the customizers). I don't think I would add it by default in Spring Cloud though, so your first snippet is user code, and the second is a proposal for a change in Spring Boot. Does that make sense?

**Comment by sfussenegger** [comment]
makes perfect sense

**Comment by philwebb** [comment]
The name of the callback interface should probably be `JwtAccessTokenConverterRestTemplateCustomizer` rather than `JwtAccessTokenTemplateConfigurer` and the method should be `customize`. This will align with `UserInfoRestTemplateCustomizer`.

**Comment by philwebb** [comment]
Closing in favor of PR #8268 (thanks @eddumelendez)
