### ISSUE TITLE
java.lang.NoSuchMethodError: org.springframework.web.filter.CharacterEncodingFilter.setForceRequestEncoding(Z)V

### ISSUE THREAD

**Issue by CatPlanet** [spring-projects/spring-boot#5862]
Due to some changes in recent 6 days in Spring Boot SNAPSHOT my application stopped working

Main class: http://pastebin.com/w8Rk94fH
pom.xml: http://pastebin.com/WUpmbJ2y
Log: http://pastebin.com/raw/uReEJKn1

I would gladly take suggestion how to fix it, it worked perfectly for months

**Comment by wilkinsona** [comment]
You need to use an up-to-date Spring Framework 4.3 snapshot. Try building with `mvn -U`.

**Comment by CatPlanet** [comment]
Thanks, it worked. Sorry for troubles and have a nice day :)

**Comment by IamGabrielWu** [comment]
thank you. you saved my day
