### ISSUE TITLE
Simply including HikariCP on the classpath does not enable it as the default connection pool

### ISSUE THREAD

**Issue by donovanmuller** [spring-projects/spring-boot#5863]
As per the [docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connect-to-production-database):

> * We prefer the Tomcat pooling DataSource for its performance and concurrency, so if that is available we always choose it.
> * If HikariCP is available we will use it.
> * ...

This might be my misunderstanding but from reading the above it implies that simply including HikariCP as a Maven dependency for example:

```
...

<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
        <groupId>com.zaxxer</groupId>
        <artifactId>HikariCP</artifactId>
    </dependency>

    ...
```

will result in my app using Hikari as the connection pool and *not* the default Tomcat pool.
However, this is not the case. With the above config, Tomcat pool is still used.

To switch to Hikari you need to exclude Tomcat pool:

```
...

<dependencies>
  <dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-data-jpa</artifactId>
     <exclusions>
         <exclusion>
             <groupId>org.apache.tomcat</groupId>
             <artifactId>tomcat-jdbc</artifactId>
         </exclusion>
     </exclusions>
   </dependency>
   <dependency>
     <groupId>com.zaxxer</groupId>
     <artifactId>HikariCP</artifactId>
   </dependency>

   ...
```

I realise the note section: "*You can bypass that algorithm completely and specify the connection pool to use via the spring.datasource.type property. ...*" achieves the same without excluding `tomcat-jdbc` explicitly but it's just that the wording in the docs, at least in my opinion, is misleading and should maybe include a note around excluding `tomcat-jdbc` if you choose to use Hikari that way.

**Comment by snicoll** [comment]
One line after that section and before the warning you have the following

> If you use the spring-boot-starter-jdbc or spring-boot-starter-data-jpa ‘starter POMs’ you will automatically get a dependency to tomcat-jdbc.

I am not sure what else we can do. The exclude part is unrelated to forcing the type IMO. If you feel differently, a PR is welcome to suggest an improvement in the doc.

**Comment by donovanmuller** [comment]
@snicoll Created https://github.com/spring-projects/spring-boot/pull/5864 as a suggestion.
