### ISSUE TITLE
MetricsFilter may create an unbounded number of metrics for requests with a templated URI that are not handled by Spring MVC

### ISSUE THREAD

**Issue by heroicefforts** [spring-projects/spring-boot#5875]
The MetricsFilter is unsuitable for REST microservices that are backing a large number of entities.  In our case, it was trying to generate gauges and counters for /widget/1 to /widget/60000000.  It eventually soaks the heap and causes the server to slow to a crawl as it spends most of its CPU cycles in GC.  There should be a big red "caveat" bubble in the documentation that details this scenario.  

Ideally, a Spring MVC controller metrics controller should be implemented that works similar to the DropWizard Jersey 2 implementation (plus some RequestMapping introspection), then the MetricsFilter could be disabled by default.

**Comment by wilkinsona** [comment]
The behaviour you've described isn't intended, and it doesn't match what's tested.

In [one of the tests](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/autoconfigure/MetricFilterAutoConfigurationTests.java#L108-L121) there's a request mapping like this: `@RequestMapping("templateVarTest/{someVariable}")`. It's called with `/templateVarTest/foo` which results in `status.200.templateVarTest.someVariable` and `response.templateVarTest.someVariable` being updated. As you can see, it's the name of the variable in the request mapping rather than the value in the request URI that's used.

Can you please provide a sample or testcase that illustrates the behaviour you have described?

**Comment by heroicefforts** [comment]
Then, perhaps, it is a consequence of using Jersey with SpringBoot (don't get me started on why...):

```
@GET
@Path("/parent/{pid}/child/{cid}")
@Produces("application/json")
@Timed(name="child.reads")
public Response readChild(@Context UriInfo uriInfo, @PathParam("pid") String parentId,
        @PathParam("cid") String childId) { ... } 
```

**Comment by wilkinsona** [comment]
Thanks. That'll be it. We need to use Jersey's equivalent of Spring MVC's best matching pattern attribute (assuming it has such a thing).

**Comment by beckje01** [comment]
So does that mean https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/MetricsFilter.java#L104 needs to become pluggable?

**Comment by wilkinsona** [comment]
@beckje01 No, I don't think so. It's something similar to [this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/MetricsFilter.java#L147-L148) that we need to do for JAX-RS.

**Comment by beckje01** [comment]
Ok so we just need to make sure things are putting that attribute in, this same issue effect Grails 3 as well. So that way anything built on boot the metrics will work for assuming the attribute is set.

**Comment by jbellmann** [comment]
Hi,
maybe [this snippet](https://github.com/zalando/zmon-actuator/blob/master/zmon-actuator-jaxrs-jersey/src/main/java/org/zalando/zmon/jaxrs/jersey/BestMatchingPatternFilter.java) could help here?

**Comment by pdavidson** [comment]
I just ran into this with jersey as well.  It didn't saturate our jvm.  Just filled up 380GB on our graphite server.  I'm disabling the filter using:

```
endpoints:
  metrics:
    filter:
      enabled: false
```

**Comment by wilkinsona** [comment]
Adding the following bean to an application will correct the metrics for requests handled by Jersey:

```java
@Bean
public ResourceConfigCustomizer bestMatchingPatternResourceConfigCustomizer(
		final JerseyProperties jerseyProperties) {
	return new ResourceConfigCustomizer() {

		@Override
		public void customize(ResourceConfig config) {
			String applicationPath = determineApplicationPath(jerseyProperties,
					config);
			config.register(new BestMatchingPatternContainerRequestFilter(
					applicationPath));
		}

		private String determineApplicationPath(JerseyProperties jerseyProperties,
				ResourceConfig config) {
			if (StringUtils.hasText(jerseyProperties.getApplicationPath())) {
				return jerseyProperties.getApplicationPath();
			}
			ApplicationPath applicationPath = AnnotationUtils
					.findAnnotation(config.getClass(), ApplicationPath.class);
			return applicationPath == null ? "" : applicationPath.value();
		}

	};

}

/**
 * A {@link ContainerRequestFilter} that sets the
 * {@link HandlerMapping#BEST_MATCHING_PATTERN_ATTRIBUTE} request attribute.
 */
private static final class BestMatchingPatternContainerRequestFilter
		implements ContainerRequestFilter {

	private final String applicationPath;

	private BestMatchingPatternContainerRequestFilter(String applicationPath) {
		this.applicationPath = applicationPath.startsWith("/") ? applicationPath
				: "/" + applicationPath;
	}

	@Override
	public void filter(ContainerRequestContext requestContext)
			throws IOException {
		String matchingPattern = extractMatchingPattern(requestContext);
		requestContext.setProperty(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE,
				matchingPattern);
	}

	private String extractMatchingPattern(
			ContainerRequestContext requestContext) {
		ExtendedUriInfo extendedUriInfo = (ExtendedUriInfo) requestContext
				.getUriInfo();
		List<String> templates = new ArrayList<String>();
		for (UriTemplate matchedTemplate : extendedUriInfo
				.getMatchedTemplates()) {
			String template = matchedTemplate.getTemplate();
			templates.add(template.startsWith("/") ? template : "/" + template);
		}
		if (StringUtils.hasText(this.applicationPath)) {
			templates.add(this.applicationPath);
		}
		Collections.reverse(templates);
		return StringUtils.collectionToDelimitedString(templates, "");
	}

}
```

Some caveats:

 - I don't like that it uses Spring MVC's request attribute (see #7505)
 - Regular expressions in `@Path` don't work particularly well (see #7503)

**Comment by soldierkam** [comment]
The same happens for almost every HttpServlet used in Spring Boot application. MetricsFilter should create new keys only if it knows what mapping was used.

**Comment by r0nin** [comment]
@wilkinsona Just as a comment. I used this bean and it indeed solved the problem, but i got strange gauge metrics a la "gauge.response..v1.controllerName.apiEndPoint", because the Jersey application path is "/", the Controller has a @Path("/controllerName") and the method has a @Path("apiEndPoint"). The problem is probably on our side since the "/controllerName" might be slightly incorrect, but anyway in the returned concatenation of matching templates this leads to "//v1/controllerName/apiEndPoint" which obviously causing the ".." part in the gauge metric. So to be safe against that, I simply replaced "//" by "/" before returning the result.

**Comment by deki** [comment]
The title of this issue should be changed as this also affects Apache CXF and other frameworks.

**Comment by wilkinsona** [comment]
The planned move to [Micrometer](http://micrometer.io)-based metrics will get rid of the metrics filter.

**Comment by wilkinsona** [comment]
We've decided to align 1.5.x with 2.0's current behaviour and fallback to `unmapped` when we can't get the best matching pattern from Spring MVC. This will avoid requests that aren't handled by Spring MVC from causing a potentially unbounded number of metrics to be created.

**Comment by deki** [comment]
Great improvement for those who still stick to that version...
