### ISSUE TITLE
Hibernate 5 custom naming strategy generates inconsistent table name for @ManyToMany

### ISSUE THREAD

**Issue by maol74** [spring-projects/spring-boot#5880]
When running spring-boot-sample-jpa insert errors occures. The import.sql file try to insert into note_tags table but the table that´s get created is note_tag (without s)

**Comment by snicoll** [comment]
This is due to the Hibernate 5 migration: the naming strategy with H4 creates a `note_tags` table while H5 creates `note_tag`.

**Comment by wilkinsona** [comment]
@snicoll convinced me we should try to customise the implicit naming strategy to align with Boot 1.3's behaviour
