### ISSUE TITLE
@WebMvcTest does not configure spring.mvc properties on TestDispatcherServlet

### ISSUE THREAD

**Issue by pleimann** [spring-projects/spring-boot#5891]
I'm attempting to test a `@ControllerAdvice` component with a, exception handler method for `NoHandlerFoundException`. I've set `spring.mvc.throw-exception-if-no-handler-found` to true in application.yml. When running the application as normal the `DispatcherServlet` throws the exceptions and they're handled appropriately. However, when attempting to test it with a `@MockMvcTest`, the `NoHandlerFoundException` is never thrown. 

`MockMvcBuilderSupport`'s constructor doesn't set the `spring.mvc` properties on the `TestDispatcherServlet` as `DispatcherServletAutoConfiguration#DispatcherServletConfiguration` does when building the `DispatcherServlet`. Because it's passed to the `MockMvc` constructor without adding to the `ApplicationContext` and the `TestDispatcherServlet` isn't accessible there's no way to set this property.

Using spring-boot v1.4.0 SNAPSHOT

```
@RunWith(SpringRunner.class)
@WebMvcTest(controllers = { RootController.class, ExceptionHandlerAdvice.class })
public class RootControllerTest {
    @Autowired
    private MockMvc mockMvc;

    @Test
    public void testNoHandler() throws Exception {
        this.mockMvc.perform(get("/FOO"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value(startsWith("Invalid Request")));
    }
}
```

```
@RestControllerAdvice
class ExceptionHandlerController {
    @ExceptionHandler(NoHandlerFoundException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorData noHandlerFoundHandler(NoHandlerFoundException e, HttpServletRequest request) {
        String message = String.format("Invalid Request: %s", e.getMessage());

        log.info(message);

        return new ErrorData(e.getClass(), message, request.getRequestURL().toString());
    }

    @Data
    public static class ErrorData {
        private final Instant timestamp = Instant.now();
        private final Class<? extends Exception> type;
        private final String message;
        private final String requestUrl;
    }
}
```

**Comment by wilkinsona** [comment]
Short of using reflection, I don't think there's much we can do about this without some changes in Spring Framework. Spring Boot creates a `DefaultMockMvcBuilder` to build the `MockMvc` instance. It inherits from `MockMvcBuilderSupport`, the `createMockMvc` method of which creates the `TestDispatcherServlet`. Unfortunately that method is `final` so we can't subclass `DefaultMockMvcBuilder` and override it.

@rstoyanchev have I missed something? Is there a way for us to configure `setThrowExceptionIfNoHandlerFound` and the like on the `MockMvc` `TestDispatcherServlet` instance?

**Comment by penguin944** [comment]
I realized after looking at it again that `MockMvcBuilderSupport` is in spring-test. I can open the issue there and see what happens. Thanks for looking into it.

**Comment by rstoyanchev** [comment]
Yes we can make that easier on the Spring Framework side. @penguin944 please do create a ticket.

**Comment by sbrannen** [comment]
To be addressed in https://jira.spring.io/browse/SPR-14277

**Comment by snicoll** [comment]
There's still something to be done in Boot once the framework issue is fixed. We should probably get the DispatcherServlet customizations and apply them here as well.

**Comment by snicoll** [comment]
ping @philwebb @wilkinsona

**Comment by wilkinsona** [comment]
What is the ping for, @snicoll? Customising the test dispatcher servlet to match the customisations on the main dispatcher servlet sounds like a good idea to me.
