### ISSUE TITLE
Bugreport: 1.3.4.RELEASE indirectly refers to unavailable spring-data-keyvalue:pom:1.0.4.RELEASE

### ISSUE THREAD

**Issue by ascheman** [spring-projects/spring-boot#5894]
When generating a Maven site with the following parent
```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.4.RELEASE</version>
	</parent>
```

I receive warnings like this:
```
[WARNING] Unable to create Maven project for org.springframework.data:spring-data-keyvalue:pom:1.0.4.RELEASE from repository.
org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: Failure to find org.springframework.data:spring-data-keyvalue:pom:1.0.4.RELEASE
```

But ```org.springframework.data:spring-data-keyvalue:pom:1.0.4.RELEASE``` is not available from Maven Central. 

This seems due to the following inheritance chain:
- spring-boot-starter-parent:1.3.4.RELEASE
- <- ...
- <- spring-boot-dependencies:1.3.4.RELEASE
- <- spring-data-releasetrain:Gosling-SR4
- <- spring-data-keyvalue:pom:1.0.4.RELEASE

Isn't it possible to switch to a newer / publicly available Spring Data Release?

**Comment by snicoll** [comment]
We haven't updated that dependency in a while and something seems definitely wrong but it is unrelated to Spring Boot, really. @olivergierke `spring-data-keyvalue` 1.0.4 does not seem available from Maven central. Any idea what is going on?

**Comment by ascheman** [comment]
Thanks for the fast reply. We do not even use Spring Data in this project and only ran into this problem when starting to generate sites ... So currently it is only an ugly warning during build (however, I always try to minimize those).

**Comment by wilkinsona** [comment]
@ascheman Thanks for making us aware of the problem. I've let the Spring Data team know. There would appear to have been a problem with syncing the release artifacts to Maven Central and Bintray. While the Spring Data team investigate and resolve the problem, the release artifacts are available from https://repo.spring.io/release. There's nothing we can do in Spring Boot to address this so I'm going to close this issue.
