### ISSUE TITLE
If you have `banner.txt` and banner.png` in a project, both banners are displayed.

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5895]
Conference-driven testing ...

**Comment by wilkinsona** [comment]
IMO, you can never have too many banners. This should be closed as won't fix.

**Comment by snicoll** [comment]
Here we go again....

**Comment by wilkinsona** [comment]
Displaying both banners is intentional. You may want to use an image banner to display a logo and a text banner to display some text.

**Comment by philwebb** [comment]
What Andy said. The primary use-case was an image banner + version details text.
