### ISSUE TITLE
ConfigurationMetadataRepositoryJsonBuilder silently dropping relevant information

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#5905]
I have a project which defines a property "my.welcome.path" of type String using annotations.

Then I also created a file with additional metadata like this:

```{
    "hints": [
        {
            "name": "my.welcome.path",
            "providers": [
                {
                    "name": "handle-as",
                    "parameters": {
                        "target": "org.springframework.core.io.Resource"
                    }
                }
            ]
        }
    ]
}```

When we call the builder to first parse the 'main' json file and then the one with additional info... I think we would expect that the 'handle-as' provider be added as a hint to the metadata from the existing property (parsed from the first file).

However this does not happen because the property is defined in a separate file (and the processing of hints only tries to add the data to existing property definitions it parsed from the same file).

At the very least the builder should merge data into data files parsed before. Arguably, a 'nice' implementation of the builder should even merge the data properly regardless of the order in which it is presented with the files to parse.

**Comment by kdvolder** [comment]
I'm trying to get to the bottom of this. I'm not so sure now that this is problem with ConfigurationMetadataRepositoryJsonBuilder. 

As I 'fixed' the perceived problem, I noticed that I started getting duplicate results in STS for hints that are provided via metadata enclosed inside jar files.

Upon closer inspection, I see that the metadata inside the jar files at:
/META-INF/spring-configuration-metadata.json

already include the data from 
/META-INF/additional-spring-configuration-metadata.json

So by fixing what I though was a 'bug', merging the data from both these files actually results in duplicate information.

There's definitely still a bug here I think. But perhaps the bug is in the annotation processor instead. I.e. similar to how it previously misbehaved on incremental builds.

When the annotation processor is run from inside Eclipse, it appears not to merge the 'additional' metadata. However, when I run it from the commandline via maven then it does.

So the problem that I'm seeing with the missing content assist should probably blamed on improper merging of additional metadata by the processor rather than the JsonBuilder. (But I think its still a bug, just not in the place where I first thought it was)

**Comment by kdvolder** [comment]
Debugging it now. 

This is the bit that doesn't work:

		FileObject fileObject = this.environment.getFiler()
				.getResource(StandardLocation.CLASS_OUTPUT, "", ADDITIONAL_METADATA_PATH);
		File file = new File(fileObject.toUri());
   
Although it appears to be looking for the file in the right place... at the time when the processor runs, the additiona-metadata has not been copied to that location *yet* (the build is currently in progress and its the build that copies the resources as well as compile the java code).

**Comment by snicoll** [comment]
You shouldn't be messing with additional meta-data _at all_. The annotation processor is meant to merge those in the single `META-INF/spring-configuration-metadata.json`. If you are reading that file yourself, you are basically re-doing the merge work that the annotation processor is doing. This is definitely not  the right direction IMO.

**Comment by snicoll** [comment]
@kdvolder can you provide a sample that shows what the repository does not expose properly please? If that's related to incremental compilation, I am afraid there is nothing that can be done at the level of the repository ....

**Comment by kdvolder** [comment]
The problem is not related to incremental compilation. The problem is that the annotation processor is trying to find the 'additional metadata file' in the project output folder so that it can merge the additional data into the generated data.

However, this makes the implicit assumption that additional metadata file resource has already been copied there prior to the execution of the processor. This is not guaranteed in the Eclipse workspace build. 

When I was debugging the processor and stepping through it, I could see it was looking in the right place but the file was not *yet* there. Therefore processor concluded there was no additional data and it didn't get merged. 

> can you provide a sample that shows what the repository does not expose properly

Not sure what you are asking for. Do you want a sample project?

This is one I used for a regression test:
https://github.com/spring-projects/spring-ide/tree/fix-dropped-metadata/plugins/org.springframework.ide.eclipse.boot.properties.editor.test/workspace/demo-with-resource-prop

It has an additional metadata file. This data is merged correctly when running 'mvn clean package' but its not being merged when I ran the annotation processor directly from Eclipse.

Furthermore, even if we use the repository json builder to merge the two files (yes I understand we shouldn't have to do this if the processor worked correctly) it doesn't merge in the extra hints correctly either and just drops it.

Is that the example you wanted?

**Comment by snicoll** [comment]
No, it's not the example I wanted with regards to the issue you've opened.

It is still not clear if there is a bug in the repository
(`spring-configuration-metadata` module) or if the problem is about
incremental compilation. Can you please clarify that?

**Comment by kdvolder** [comment]
Okay with what I know now. I'd say the bug is in the annotation processor. When its trying to merge the data, it is making an assumption about the order that things happen in:

 1. copy resource
 2. compile java code (including executing the annotation processor)

What happens in Eclipse is that this order is not guaranteed. Copy-resources and compiling java code is done by one and the same builder and this builder doesn't guarantee what order its going to do these things in.


Since I gather the builder was never really meant to be used to merge the data in the way I was trying to use it, and knowing what I know now, I don't think I'd still call it a bug in the repository builder. It simply works as designed on the broken input data.

**Comment by snicoll** [comment]
That's what I thought, thanks for clarifying that. Let's see if we can make the annotation processor smarter about that stuff then.  `getAdditionalMetadataStream` does some stuff with Gradle, I am sure we can try something to make eclipse happy.
