### ISSUE TITLE
BasicJsonTester.from() with a JSON file doesn't work with Gradle

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#5907]
`BasicJsonTester.from()` with a JSON file works with IDE (InteilliJ) but doesn't work with Gradle.

`FileNotFoundException` occurs as follows:

```
learningtest.org.springframework.boot.test.json.BasicJsonTesterTests > test FAILED
    java.io.FileNotFoundException at BasicJsonTesterTests.java:19
```

This is a sample test reproducing the situation: https://github.com/izeye/spring-boot-throwaway-branches/blob/master/src/test/java/learningtest/org/springframework/boot/test/json/BasicJsonTesterTests.java

I used the following command to run the test in Gradle:

```
./gradlew clean test --tests *BasicJsonTesterTests.test
```

**Comment by snicoll** [comment]
`test.json` is in `src/test/java`. My guess is that it's not copied over by gradle (and shouldn't probably by your IDE either).

**Comment by izeye** [comment]
@snicoll You're right. Moving the JSON file to `src/test/resources` makes it work in Gradle and I think it makes sense. Although I'm not sure whether working in IntelliJ 13.1.6 is a bug or not, it's irrelevant to Spring Boot, so I'm closing this. Thanks for the comment!

**Comment by snicoll** [comment]
> Although I'm not sure whether working in IntelliJ 13.1.6 is a bug or not

I don't think it does that by default, you probably have tuned the compiler settings to add `.json` to the accepted patterns.

**Comment by izeye** [comment]
@snicoll IIRC, I didn't set anything related to it...
