### ISSUE TITLE
spring-boot-configuration-processor doesn't merge additional metadata when run from eclipse

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#5908]
See https://github.com/spring-projects/spring-boot/issues/5905

It has been explained in detail there.

Summary: the processor assumes resources are copied prior to its execution. This is not the case.
The result of this faulty assumption is the 'additional metadata' is not found in the expected place and is not properly merged.

**Comment by kdvolder** [comment]
Thought the problem a bit more. A hack similar to what was done for gradle can be implemented somehow I think, but... that will only fix the problem on a 'full' build not an incremental one.

The problem on incremental builds... I don't know if it can be fixed at all.

The reason is that the eclipse builder will not trigger java compilation and therefore annotation processor to run when the user only edits a copied resource. This is logical, since normally resource do not affect compilation outcomes. So all that the incremental builder will do in such a scenario is make a fresh copy of the changed resource. 

Therefore, its simply impossible for the annotation processor do anything at all in this scenario.

**Comment by snicoll** [comment]
>  A hack similar to what was done for gradle can be implemented somehow I think

And what would that be exactly? Can you submit a PR for this please?

**Comment by kdvolder** [comment]
I don't think its worth the effort. It doesn't really fix anything because

> ... that will only fix the problem on a 'full' build not an incremental one.

STS patches over this imperfection in the annotation processor by doing the merge itself. Basically the assumption that the annotation processor merges the data is what is 'broken' here.

So the only way to fix it for real is to change this contract and assume that its not up to the annotation processor to merge the data, but up to consumer of the data (i.e. the IDE).

**Comment by snicoll** [comment]
Thank you for the feedback! 

I am afraid that's not going to happen so I am going to close this issue. Feel free to reopen if there is anything else we can do.

**Comment by kdvolder** [comment]
Won't reopen the ticket. But, there is one thing that boot can do yes. Namely help with this:

> STS patches over this imperfection in the annotation processor by doing the merge itself.

I.e. provide a reliable/correct method to merge the data. I've cobled something together by changing my copy of ConfigurationMetadataRepositoryJsonBuilder.

My confidence on whether it actually does this correctly isn't very high however.
