### ISSUE TITLE
SpringApplicationContextLoader does not override properties specified in @TestPropertySource files

### ISSUE THREAD

**Issue by rocketraman** [spring-projects/spring-boot#5916]
As per https://github.com/spring-projects/spring-boot/issues/2198 `@TestPropertySource` now loads configuration files via the `location` attribute. However, `@TestPropertySource` does not seem to *override* properties set via the `location` attribute.

I noticed the [integration test](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RELEASE/spring-boot/src/test/java/org/springframework/boot/test/SpringApplicationIntegrationTestPropertyLocationTests.java) does not test overriding any value in the underlying application configuration -- it only sets a new configuration value.

One can work around this using an explicit test profile or via setting the property via the `properties` attribute of `@TestPropertySource` but neither approach should be necessary.

**Comment by rocketraman** [comment]
Although perhaps this is fixed by https://github.com/spring-projects/spring-boot/issues/4828 and https://github.com/spring-projects/spring-boot/commit/69b08291992795ccea46b03dfc8bce53dd82174e. I noticed that commit only appears in milestone 1.4 -- it seems important enough that it should be backported to 1.3.

**Comment by wilkinsona** [comment]
It was a deliberate decision to only fix #4828 in 1.4. Changing the order in 1.3.x is too big a change for a maintenance release. Unfortunately, that means you'll have to live with things as they are in 1.3.
