### ISSUE TITLE
WebMvcConfigurerAdapter#configureMessageConverters Does Not Follow Contract 

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-boot#5917]
Spring Boot 1.3.3.RELEASE

We are using a `WebMvcConfigurerAdapter` to customize the list of HTTP message converters in our app - Boot is registering a bunch we don't actually want and one of them is causing problems. The javadoc on the interface, `WebMvcConfigurer`, indicates that we should override `configureMessageConverters`:

> If no converters are added, a default list of converters is registered 
> Note that adding converters to the list, turns off default converter registration.
> To simply add a converter without impacting default registration, consider using the method `extendMessageConverters` instead.

It turns out this documentation is not true. There is no functional difference between `configureMessageConverters` and `extendMessageConverters`. After stepping through with a debugger I can see there is a composite of many `WebMvcConfigurer`s and one of them, from Boot, is registering all the default/autodetected converters regardless.

Searching through the code I did spot a workaround. `HttpMessageConvertersAutoConfiguration` defines a conditional `messageConverters` bean. That is the bean that appears to be triggering all the defaults to load. I simply redefined it in my configuration as follows and voilà:
```
@Bean
public HttpMessageConverters messageConverters() {
    return new HttpMessageConverters(false, new ArrayList<>());
}
```

**Comment by wilkinsona** [comment]
That's not really a workaround, that's the right way to do what you want. From [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-message-converters):

> If you need to add or customize converters you can use Spring Boot’s HttpMessageConverters class

The documentation that you have quoted is from Spring _Framework_, but you're also using Spring Boot so some behaviour has changed. The configuration that you have means that you're adding to Spring Boot's auto-configuration of Spring MVC. Again, from [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration):

>  If you want to keep Spring Boot MVC features, and you just want to add additional MVC configuration (interceptors, formatters, view controllers etc.) you can add your own `@Bean` of type `WebMvcConfigurerAdapter`, but without `@EnableWebMvc`.

I think the key word there is "additional". As you have observed, you can keep Spring Boot's auto-configuration of Spring MVC and still have complete control over the HTTP message converters using an `HttpMessageConverters` bean.

**Comment by SingleShot** [comment]
Thanks.
