### ISSUE TITLE
Integration test class execution not stopping application immediately

### ISSUE THREAD

**Issue by rvcoutinho** [spring-projects/spring-boot#5919]
Bug report - 1.3.3.RELEASE

SpringJUnit4ClassRunner seems to only stop test application instances after all test classes have been executed. In most cases, it has no influence in tests.
 
But, we got an issue when testing topics, as there are multiple instances of the same beans (each in a different Spring Boot app instance) which creates multiple (unwanted) listeners with the same behavior.

Seems like the best solution would be to stop Spring boot applications after each test class execution.

**Comment by wilkinsona** [comment]
The behaviour you have described isn't a bug. It's due to [context caching](http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/htmlsingle/#testcontext-ctx-management-caching) in Spring Framework's testing support. You can use `@DirtiesContext` to turn caching off.

**Comment by rvcoutinho** [comment]
Thank you, @wilkinsona. It worked.
