### ISSUE TITLE
Exit Code in 1.3.x is always 0 when Boot app launched with java -jar

### ISSUE THREAD

**Issue by KramKroc** [spring-projects/spring-boot#5922]
With the exit code enhancements in 1.3.2 the Boot Launcher no longer returns a non-zero exit code by default when an exception causes the application to exit.

See example project here:

https://github.com/KramKroc/nonzeroexit

**Comment by KramKroc** [comment]
@wilkinsona awesome. When do you think 1.3.6 will be released?

**Comment by wilkinsona** [comment]
We don't have a date in mind at the moment. It'll be a few weeks as we've only just released 1.3.5.
