### ISSUE TITLE
Classpath files not found in Undertow after migrating to Spring Boot 1.3.5

### ISSUE THREAD

**Issue by hromovyi** [spring-projects/spring-boot#5926]
Hi!
After migration from spring boot 1.2.5 to 1.3.5 our classpath files could not be found in undertow.
My files located in /src/main/java/resourses folder in project.
And undertow's DefaultServlet could not find this files.
I made small investigation and it seems to me that the cause of problem is that in spring boot 1.3.5 to undertow is bypassed FileResourseManager instead of ClassPathResourceManager(as in 1.2.5).

So i have a piece of code from 1.2.5 (org.springframework.boot.context.embedded.
undertow.UndertowEmbeddedServletContainerFactory#getDocumentRootResourceManager)
	
	private ResourceManager getDocumentRootResourceManager() {
		File root = getValidDocumentRoot();
		if (root != null && root.isDirectory()) {
			return new FileResourceManager(root, 0);
		}
		if (root != null && root.isFile()) {
			return new JarResourcemanager(root);
		}
		if (this.resourceLoader != null) {
			return new ClassPathResourceManager(this.resourceLoader.getClassLoader(), "");
		}
		return new ClassPathResourceManager(getClass().getClassLoader(), "");
	}
In this case i had documentRoot as null, so i got ClassPathResourseManager and everything worked fine.

But now in 1.3.5 is
	
	private ResourceManager getDocumentRootResourceManager() {
		File root = getCanonicalDocumentRoot();
		if (root.isDirectory()) {
			return new FileResourceManager(root, 0);
		}
		if (root.isFile()) {
			return new JarResourceManager(root);
		}
		return ResourceManager.EMPTY_RESOURCE_MANAGER;
	}

	/**
	 * Return the document root in canonical form. Undertow uses File#getCanonicalFile()
	 * to determine whether a resource has been requested using the proper case but on
	 * Windows {@code java.io.tmpdir} may be set as a tilde-compressed pathname.
	 * @return the canonical document root
	 */
	private File getCanonicalDocumentRoot() {
		try {
			File root = getValidDocumentRoot();
			root = (root != null ? root : createTempDir("undertow-docbase"));
			return root.getCanonicalFile();
		}
		catch (IOException e) {
			throw new IllegalStateException("Cannot get canonical document root", e);
		}
	}

So i still have document root as null, but now some temp directory is created and i have FileResourceManager, that could now see my files in /src/main/java/resourses.

As far as i understood, those changes where made in https://github.com/spring-projects/spring-boot/commit/c804299c8d58e62d470ff8573a8e1b61df985050 and https://github.com/spring-projects/spring-boot/commit/89f8af4e6e7057bfaeb1ff01701fe191e7b7e1c8

Am i doing smth wrong or should i specify extra properties in my spring boot configuration?

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/commit/c804299c8d58e62d470ff8573a8e1b61df985050 fixed a security vulnerability where everything on the classpath was being served by Undertow. You almost certainly don't want to add your own configuration to reintroduce that behaviour.

`src/main/java/resources` is a strange location to be using. Let's take a step back. Rather than talking about the specifics of Undertow, what are you trying to achieve?

**Comment by hromovyi** [comment]
I'm trying to serve static content via rest controllers. I have rest controller with mapping for "/**". This controller returns /portal/index.html file. To avoid infinite loops (cause the request for /portal/index.html will be also processed with this controller) - i have filter, that redirects all requests, that ends on ".html" to DefaultServlet from undertow, and all others - to spring servlet. As far as i understood - that what actually happens if i have some rest controller for mapping "/hello" and who returns string "/portal/index.html".

So i'm just serving html file with rest controller.

**Comment by wilkinsona** [comment]
If you want to make us of the embedded container's support for serving static content (rather than using Spring MVC's static resource support), you should package your application as a war file. Any content in the root of the war, i.e. not in `WEB-INF/lib` or `WEB-INF/classes` will then be served.
