### ISSUE TITLE
Repackage does not honor 'provided' scope

### ISSUE THREAD

**Issue by tomas-forsman** [spring-projects/spring-boot#5928]
Dependencies in scope 'provided' is expected to be excluded from packaged artifacts, spring-boot-maven-plugin (version 1.2.5.RELEASE) ignores the scope and package all dependencies.

**Comment by snicoll** [comment]
This is working as designed and [explained in the documentation](http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/exclude-dependency.html)
