### ISSUE TITLE
PropertiesConfigurationFactory.setProperties(Properties) is only used in tests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5930]
Should we deprecate/remove it?

**Comment by philwebb** [comment]
I'm guessing since we removed `@ConfigurationProperties.locations` we don't need it. I vote yes.

**Comment by wilkinsona** [comment]
FWIW, we only deprecated `locations` so I don't think that's what was using it.

**Comment by philwebb** [comment]
Hmm, I wonder why it was added. I'm still in favor of deprecating it if we're not using it ourselves.
