### ISSUE TITLE
Add caching to DefaultErrorViewResolver

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5933]
See https://github.com/spring-projects/spring-boot/issues/2691#issuecomment-217127932

**Comment by chrylis** [comment]
Basically, the reason behind the question is that the current implementation re-resolves error templates every time a page render is required; it seems to me (not having profiled anything, just by intuition) that the search performed is rather expensive and that the template mapping is unlikely to change over the lifetime of the application. 404 and 403 errors in particular, by contrast, are likely to occur frequently, and it would seem that once a `404.html` has been discovered that the result should be cached.

**Comment by philwebb** [comment]
Reducing the calls to `templateAvailabilityProvider.isTemplateAvailable` seems sensible but the actual `ModelAndView` caching remains the job of Spring MVC. We can't directly cache the `ModelAndView` response anyway since the `Model` will change.
