### ISSUE TITLE
Add parameter to change spring boot maven plugins artifact file names

### ISSUE THREAD

**Issue by mnhock** [spring-projects/spring-boot#5944]
With the spring boot maven plugin it is possible to specify a classifier. 
If specified with `exec ` the two artifacts will be created/installed/deployed accordingly:

- `app.jar` (only classes)
- `app-exec.jar` (classes and dependencies)

For me it would be great if i could do something with an configuration parameter and customizeable value like `original`:

- `app.jar` (classes and dependencies)
- `app-original.jar` (only classes)

They should be created/installed/deployed accordingly as well.

**Comment by snicoll** [comment]
Thanks for sharing the idea but I am not keen on doing that. For one that would make the available options quite convoluted (there are already two options that affect how the jars is packaged, I don't want to add a third).

I think it's fine that we "erase" the main artifact with that repackaged jar if the user is only interested by that. If the user wants both, as you, then the main artifact should remain what the default Maven lifecycle produces.
