### ISSUE TITLE
trigger-file doesn't work

### ISSUE THREAD

**Issue by mgorniew** [spring-projects/spring-boot#5948]
Hi,

I'm trying to configure devtools to restart on trigger file. I have following configuration:

`spring.devtools.restart.additional-paths=../../trigger/`
`spring.devtools.restart.trigger-file=.reloadtrigger`

But when I touch '.reloadtrigger' spring will not restart. 

In debug I see that `LocalDevToolsAutoConfiguration` has trigger file configured. Also `FileSystemWatcher.updateSnapshots` is aware of change, but `FolderSnapshot.getChangedFiles` return empty `ChangedFiles`. This is because trigger file is filtered by `FolderSnapshot.acceptChangedFile`:

```java
	private boolean acceptChangedFile(FileFilter triggerFilter, FileSnapshot file) {
		return (triggerFilter == null || !triggerFilter.accept(file.getFile()));
	}
```

What I missing here? Did I misconfigured something?

Thanks,
Michal

**Comment by philwebb** [comment]
So `TriggerFileFilter.accept` is returning `false`? Are you able to step into the filter and inspect `name` and `file` and report them here? Do the values look sensible? Is the correct case used?

**Comment by mgorniew** [comment]
`TriggerFileFilter.accept` is returning `true` and it looks like I made wrong assumption about how trigger-file exactly works. I see now that `spring.devtools.restart.trigger-file` will trigger restart if both conditions are meet: trigger files is touched and at least one of files (other than trigger file) in classpath directories is changed. 

But I have .jar file in classpath (added also to `restart.include` in `META-INF\spring-devtools.properties`) and I would like to trigger restart if this file is changed - even if no other .class file is changed classpath directories. Is this possible?

Thanks,
Michal

**Comment by philwebb** [comment]
Yes, you should be able to just drop the `triggerfile` property and rely on the `additional-paths`. One additional thing you might need to do is add `restart.include` settings to ensure that your additional `.jar` is in the correct classloader. See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload.
