### ISSUE TITLE
Switch default for dispatchOptionsRequest from false to true

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-boot#5965]
Spring Framework 4.3. provides default handling for HTTP OPTIONS and HTTP HEAD ([see docs](http://docs.spring.io/spring/docs/4.3.0.BUILD-SNAPSHOT/spring-framework-reference/htmlsingle/#mvc-ann-requestmapping-head-options)) and the `dispatchOptionsRequest` property of the `FrameworkServlet` is set to true in the constructor of the `DispatcherServlet`.

However in Spring Boot this property is controlled separately via `WebMvcProperties` which sets it to `false` by default. Consider changing that to `true` in 1.4.

**Comment by wilkinsona** [comment]
Thanks, @rstoyanchev. I agree that we should align with Spring Framework 4.3's default.
