### ISSUE TITLE
bootRepackage task always runs, even if nothing changed

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#5970]
I'm using 1.3.3.RELEASE. My project consists of multiple modules, and a last one aggregates all the rest with bootRepackage (default configuration).
When I execute a new build, with './gradlew clean build', all is built, of course. Now, I execute './gradlew assemble', and then again, and again, with no code changes at all. In the Gradle output I see all the tasks being UP-TO-DATE, except for the following tasks:

findMainClass
jar
bootRepackage
assemble

Could the plugin be improved such that it doesn't perform unnecessary work when nothing has changed? For example, it could by default include something equivalent to:

    bootRepackage {
        onlyIf {
            jar.didWork
        }
    }

**Comment by philwebb** [comment]
Indeed it could and we plan to tackle it in #5861. Unfortunately we don't have enough time to do this before 1.4.
