### ISSUE TITLE
Add ability to filter `Cookies` in or out of Trace data in TraceProperties

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#5982]
Currently, by including `REQUEST_HEADERS` all the headers, including a highly-sensitive `Cookies` gets displayed.  Would be great to support a setting that allows display of all request/response headers but exclude the `Cookie` and `Set-Cookie*` headers from that list.  This would be a huge help to allow to be PCI compliant!

**Comment by jgoldhammer** [comment]
+1 - absolut necessary!!

**Comment by snicoll** [comment]
Closing in favour of the pr #6018
