### ISSUE TITLE
Fully Executable Jar doesn't start on Ubuntu 15.10

### ISSUE THREAD

**Issue by kpb** [spring-projects/spring-boot#5983]
Not sure this isn't my error...

``` bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10

$ spring --version
Spring CLI v1.3.5.RELEASE

$ spring init --build=gradle foo
```
- modify build script to create fully executable jar
- Build jar

``` bash
$ ln -s /tmp/bar/build/libs/foo-0.0.1-SNAPSHOT.jar /etc/init.d/foo
$ service foo start
Failed to start foo.service: Unit foo.service failed to load: No such file or directory.
```

The service WILL start with `/etc/init.d/foo start`

Same jarfile and procedure works on Redhat and CentOS (using the `service` command).

**Comment by snicoll** [comment]
Does https://github.com/influxdata/influxdb/issues/3989 help?

**Comment by kpb** [comment]
It's the same issue. However, Ubuntu 15.10 does have lots of init.d scripts that do work with the service command.

**Comment by kpb** [comment]
Also, following the spring-boot ref docs for systemd:

```bash
$ systemctl start foo.service
$ systemctl status foo.service
● foo.service - foo
   Loaded: loaded (/etc/systemd/system/foo.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-05-18 09:32:13 MDT; 2s ago
  Process: 6755 ExecStart=/home/kbowen/foo-0.0.1-SNAPSHOT.jar (code=exited, status=203/EXEC)
 Main PID: 6755 (code=exited, status=203/EXEC)

May 18 09:32:13 dev systemd[1]: Started foo.
May 18 09:32:13 dev systemd[1]: Starting foo...
May 18 09:32:13 dev systemd[1]: foo.service: main process exited, code=exited, status=203/EXEC
May 18 09:32:13 dev systemd[1]: Unit foo.service entered failed state.
May 18 09:32:13 dev systemd[1]: foo.service failed.
```

**Comment by kpb** [comment]
Oddly, there's some sys V -- systemd compatabiltiy issue on Ubuntu 15.04. The jar works fine on redhat 7.2, without a .service file. Does not work on Ubuntu 15.04. 

Not sure the systemd debacle is spring-boot's problem, although this feature (executable jar) makes our CI much easier.

**Comment by selimok** [comment]
Unfortunately I have same problem with Ubuntu 16.04. I tried both SystemV and systemd methods described in the documentation here: http://docs.spring.io/spring-boot/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#deployment-service

If I tried to start service I got following error: 

```
selimok@Ubuntu-1604-xenial-64-minimal:/etc/init.d$ service myapp start
Failed to start myapp.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status myapp.service' for details.
```

And i got following details about the execution: 

```
selimok@Ubuntu-1604-xenial-64-minimal:/etc/init.d$ sudo systemctl status myapp.service
● myapp.service - myapp
   Loaded: loaded (/etc/systemd/system/myapp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-10-14 00:09:53 CEST; 20s ago
  Process: 28938 ExecStart=/opt/deploy/myapp/application.jar (code=exited, status=1/FAILURE)
 Main PID: 28938 (code=exited, status=1/FAILURE)

Oct 14 00:09:53 Ubuntu-1604-xenial-64-minimal systemd[1]: Started myapp.
Oct 14 00:09:53 Ubuntu-1604-xenial-64-minimal systemd[1]: myapp.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 00:09:53 Ubuntu-1604-xenial-64-minimal systemd[1]: myapp.service: Unit entered failed state.
Oct 14 00:09:53 Ubuntu-1604-xenial-64-minimal systemd[1]: myapp.service: Failed with result 'exit-code'.
``` 

Thanks.

**Comment by wilkinsona** [comment]
@selimok Thanks for the information. We have integration tests that verify the launch script works with System V. Those tests run successfully on Ubuntu Xenial. The error message suggests a permissions problem. See http://unix.stackexchange.com/questions/158494/the-name-org-freedesktop-policykit1-was-not-provided-by-any-service-files, for example.

**Comment by seko111** [comment]
I had the same problem, and chmod +x myfile.jar fixed it. Running Centos 7.

**Comment by wilkinsona** [comment]
Unless I've missed something, I think this was just a permissions problem. Please correct me if I'm mistaken.

**Comment by dit-j** [comment]
Still not working for me Ubuntu 18.04.

Why closed?

**Comment by wilkinsona** [comment]
> Why closed?

Because, as mentioned in the comment immediately above yours, it was a permissions problem. If you think that's not the problem in your case, please open a new issue with a minimal sample and precise instructions of how to reproduce the problem.

**Comment by kpb** [comment]
There was both a perms issue and an Ubuntu 15.04 systemd issue. 

On updated systems, we are running 40+ spring boot services using systemd. (All praise systemd).
