### ISSUE TITLE
i hope add a executors in spring-boot-autoconfigure ,  i can config the thread pool in application.properties.

### ISSUE THREAD

**Issue by sunlin901203** [spring-projects/spring-boot#5985]
i hope add a executors in spring-boot-autoconfigure ,  i can config the thread pool in application.properties.

**Comment by snicoll** [comment]
Duplicates #5082

@sunlin901203 if you want to understand how to configure a thread pool using Spring Boot, please consider asking on StackOverflow.

**Comment by sunlin901203** [comment]
@snicoll  you mean use @Scheduled or <task:scheduler id="scheduler" pool-size="2"/> to config thread pool?
