### ISSUE TITLE
launch.script: pid folder subdirectory might be missing

### ISSUE THREAD

**Issue by leflamm** [spring-projects/spring-boot#5986]
We're using packaged jars to deploy our applications and run them in "service"-mode.

I was going to set the environment variable ``$APP_NAME`` to (amongst other things) specify the pid and log file name. Starting the service then fails because in ``$PID_FOLDER`` there's no subdirectory ``$APP_NAME``. If I create it manually the service starts fine.

```
~/git/boot/some.app/target$ export MODE="service"
~/git/boot/some.app/target$ export PID_FOLDER="/tmp"
~/git/boot/some.app/target$ export LOG_FOLDER="/tmp"
~/git/boot/some.app/target$ export APP_NAME="foo"
```
```
~/git/boot/some.app/target$ ./some.app.jar start
Operation not permitted (cannot access pid file)
```
```
~/git/boot/some.app/target$ mkdir ${PID_FOLDER}/${APP_NAME}
~/git/boot/some.app/target$ ./some.app.jar start
Started [29132]
```
I learned from the last issue to discuss first whether this is defective or intended behavior before providing any PRs.

**Comment by leflamm** [comment]
Reason for the missing pid folder subdir is a special treatment in lines _111_-_113_ and the resulting value of ``$PID_FOLDER``
```
110 # Build the pid and log filenames
111 if [[ "$identity" == "$init_script" ]] || [[ "$identity" == "$APP_NAME" ]]; then
112   PID_FOLDER="$PID_FOLDER/${identity}"
113 fi
114 pid_file="$PID_FOLDER/${identity}.pid"
115 log_file="$LOG_FOLDER/$LOG_FILENAME"
```

**Comment by ppawel** [comment]
I just wasted some time on figuring out why the init script reports `Operation not permitted (cannot access pid file)` while it just tried creating the file in a directory that does not exist and yet you still report it as permission denied?!

**Comment by hotzen** [comment]
wondering how to avoid this pid-identity-subdirectory... https://stackoverflow.com/questions/45634262/spring-boot-launch-script-how-to-avoid-pid-folder-identity-subdirectory
