### ISSUE TITLE
Potentially useless @Order annotation on IgnoredPathsWebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by berniegp** [spring-projects/spring-boot#5990]
Spring Boot version: 1.3.5

I spent some time trying to understand how bean wiring and autoconfiguration works when Spring Security is on the class path. During my investigation, I think I found two usages of `@Order` which do nothing.

Here are the relevant snippets:
1.

	@Configuration
	@ConditionalOnWebApplication
	@ConditionalOnClass({ EnableWebSecurity.class })
	@AutoConfigureAfter(SecurityAutoConfiguration.class)
	@AutoConfigureBefore(FallbackWebSecurityAutoConfiguration.class)
	@EnableConfigurationProperties
	public class ManagementWebSecurityAutoConfiguration {

		// snip

		// This is the bean with id "ignoredPathsWebSecurityConfigurerAdapter" which is used
		// when both the actuator and Spring-Security are on the classpath.
		@Bean
		@ConditionalOnMissingBean({ IgnoredPathsWebSecurityConfigurerAdapter.class })
		public IgnoredPathsWebSecurityConfigurerAdapter ignoredPathsWebSecurityConfigurerAdapter() {
			return new IgnoredPathsWebSecurityConfigurerAdapter();
		}

		// snip

		// Get the ignored paths in early
		@Order(SecurityProperties.IGNORED_ORDER + 1)
		// ^^ If I understand correctly, @Order only has any effect when placed on other annotated
		// elements (beans, configuration, event listeners, etc.) In this instance, shouldn't the
		// @Order annotation be placed in the @Bean provider method? (or just removed since it has
		// no effect)
		private static class IgnoredPathsWebSecurityConfigurerAdapter
				implements WebSecurityConfigurer<WebSecurity> {

				// snip
		}

		// snip
	}

2.

	@Configuration
	@EnableConfigurationProperties
	@ConditionalOnClass({ EnableWebSecurity.class, AuthenticationEntryPoint.class })
	@ConditionalOnMissingBean(WebSecurityConfiguration.class)
	@ConditionalOnWebApplication
	@EnableWebSecurity
	public class SpringBootWebSecurityConfiguration {

		private static List<String> DEFAULT_IGNORED = Arrays.asList("/css/**", "/js/**",
				"/images/**", "/**/favicon.ico");

		@Bean
		@ConditionalOnMissingBean({ IgnoredPathsWebSecurityConfigurerAdapter.class })
		public IgnoredPathsWebSecurityConfigurerAdapter ignoredPathsWebSecurityConfigurerAdapter() {
			return new IgnoredPathsWebSecurityConfigurerAdapter();
		}

		// snip
		
		// Get the ignored paths in early
		@Order(SecurityProperties.IGNORED_ORDER)
		// ^^ same comment as above
		private static class IgnoredPathsWebSecurityConfigurerAdapter
				implements WebSecurityConfigurer<WebSecurity> {

			// snip
		}
	}

If I'm right, this is pretty innocuous, but it can confuse developers who look at the code (it did for me!).

**Comment by philwebb** [comment]
@rwinch can probably answer this. I'm guessing that `WebSecurityConfigurer` are sorted by Spring Security.

**Comment by wilkinsona** [comment]
>  I'm guessing that WebSecurityConfigurer are sorted by Spring Security.
That are indeed. See [this section of the documentation](http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#multiple-httpsecurity) for example.
