### ISSUE TITLE
full git details not showing in info endpoint using 1.4.0.M3

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#5991]
I am testing Spring Boot 1.4.0.M3 to have the full git commit details on the /info endpoint. In my Spring Boot 1.3.x apps, I am using the `git-commit-id-plugin` to generate a `git.properties` file. From the release notes, it seems that I just need to add this to my `application.properties` to have the same:

    management.info.git.mode=full

However, when I tried this, there was no git info on the endpoint. All I saw was the info I put in there via the `info.xxx` properties:

    info.name=Test Application
    info.version=@project.version@

I also tried adding `management.info.git.enabled=true` but that did not change anything.

**Comment by snicoll** [comment]
If you don't see anything related to git Wim, something else is wrong. `git.properties` is supposed to be at the root of the classpath. Can you check that? If that's the case, please share a sample project that reproduces the issue because it should work.

**Comment by wimdeblauwe** [comment]
Do you mean that the `git-commit-id-plugin` is still needed when using this?

**Comment by snicoll** [comment]
Of course it is. Nothing in the doc or the release notes state that it's no longer required. If you feel we can improve the doc, please submit a PR or share what you found confusing.

**Comment by wimdeblauwe** [comment]
Sorry about that. Did not read the docs properly I guess. The actual text is quite clear as is:

> Full or partial Git information generated **from a build plugin** (set management.info.git.mode=full to expose full details)

**Comment by snicoll** [comment]
I just changed it to explicitly reference the existing Maven/Gradle plugin. If you follow the link to the documentation, it's [even more explicit](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-application-info) IMO
