### ISSUE TITLE
@ConditionalOnProperty could be enhanced for map-like properties

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-projects/spring-boot#5995]
When using `@ConditionalOnProperty` there is no easy way to check if a map-like property (eg. `zuul.routes.*`) has any value defined.
If for example I want to only register my bean if any zuul route is explicitly configured, I'd need to write custom logic that inspects the ZuulProperties, fetches the routes map and asserts that it is not empty.
Zuul routes are of course just one example.

A solution could be to extent `@ConditionalOnProperty` with an `isMap` attribute, which would trigger a lookup via `RelaxedPropertyResolver#getSubProperties()`, or introduce a separate `@ConditionalOnMapProperty` annotation.

**Comment by snicoll** [comment]
Can you do that without a map? I think it falls in the category of "do something if property X isn't defined" and this is something we've rejected several times. Thoughts @philwebb @wilkinsona ?

**Comment by KamikaZeeFu** [comment]
Well the logic is 'do something if property X **is** defined' but due to it being a map, I don't know X at compile time, only at runtime through configuration.

I could have `zuul.routes.foo= /path/**` and `zuul.routes.bar= /another-path/**`but I don't know either foo nor bar when writing my component. That is determined at configuration time.
The property is a map because I semantically map X to Y via configuration.

**Comment by snicoll** [comment]
Oh, right. That's interesting. I'll dig a bit more, sorry about the confusion.

**Comment by philwebb** [comment]
My initial feeling is that this might add a lot of complexity to `OnPropertyCondition` for a fairly unusual use-case. The current implementation calls `PropertyResolver.containsProperty` which isn't going to work with `Map` properties.

**Comment by snicoll** [comment]
We've discussed this one and we recommend to write your own configuration for it. Thanks.
