### ISSUE TITLE
UserInfoRestTemplateFactory does not use factory bean to get a OAuth2RestTemplate instance

### ISSUE THREAD

**Issue by lfischer** [spring-projects/spring-boot#5996]
```
spring-boot version 1.4.0.M3
```

I need to extend OAuth2RestTemplate and have instances of my class used. But UserInfoRestTemplateFactory#getTemplate calls 

```
if (this.oauth2ClientContext == null) {
    return new OAuth2RestTemplate(details);
}
return new OAuth2RestTemplate(details, this.oauth2ClientContext);
```

Is it possible to also fetch an instance of OAuth2RestTemplate from a factory bean, so that I will be able to provide my own implementation?

**Comment by snicoll** [comment]
Context from here: http://stackoverflow.com/questions/37322934/extended-oauth2resttemplate-can-not-be-wired/37324046?noredirect=1#comment62170025_37324046

@dsyer said this was an internal implementation and you're not supposed to override it. Can you explain why you need to. 

(I already replied on SO how you could define your own for the time being)

**Comment by lfischer** [comment]
I have the requirement to support an extended OAuth flow.
The client credential secret will change after some time and I found no better way to refresh the value then to check this in the acquireAccessToken method of the OAuth2RestTemplate.
But this requires that my extended class is used everywhere.

**Comment by snicoll** [comment]
Let's inject `ObjectProvider<OAuth2RestTemplate>` in those areas and create a template internally if none is provided by the users. That way, if you define such a bean, it will be transparently used.

**Comment by snicoll** [comment]
Looking at the code, I've changed my mind and updated the documentation accordingly. You can now define your own bean of type `UserInfoRestTemplateFactory` (it's an interface now) and you can take full control.

In your case, it should be as easy as returning a lambda that returns your custom `OAuth2RestTemplate`. Let me know if I am missing anything.
