### ISSUE TITLE
Typo in 50.8.3 Example: Export to Statsd documentation

### ISSUE THREAD

**Issue by LtTempletonPeck** [spring-projects/spring-boot#5999]
There's a minor typo in the documentation for statsd ([50.8.3 Example: Export to Statsd](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-metric-writers-export-to-statsd)) which gives the following example:

```
@Bean
@ExportMetricWriter
MetricWriter metricWriter() {
	return new StatsdMetricWriter(prefix, "localhost", "8125");
}
```

The port parameter of the StatsdMetricWriter constructor takes an int not a String. So the port argument should be 8125 not "8125".

**Comment by snicoll** [comment]
Good catch, thanks!
