### ISSUE TITLE
Allow an auto-configuration to indicate that it should be included in particular test slice

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6001]
Currently, `@WebMvcTest` and `@DataJpaTest` pull in the auto-configurations that they want to include. This is somewhat limiting. For example, it means that a third-party starter can't add itself to a slice. This means that the user needs to use `@ImportAutoConfiguration`. I think it could be useful to provide a mechanism by which an auto-configuration can opt in to a particular test slice.

**Comment by philwebb** [comment]
One idea I tried initially in the design was to use `spring.factories` with the key being the annotation class name. It worked but resulted in lots of duplication in the imported auto-configuration entries. In the end I preferred the more explicit meta-annotations.

**Comment by wilkinsona** [comment]
I think there's always going to be duplicate references to the auto-configuration classes, either in something like `spring.factories` or in an `@ImportAutoConfiguration` annotation. The benefit of the former is that it makes a slice extensible as the imports are no longer hard-coded. I think that's important and provides a nice symmetry with the extensibility of `@EnableAutoConfiguration`.

**Comment by wilkinsona** [comment]
Here's a possible implementation: https://github.com/wilkinsona/spring-boot/tree/gh-6001. It extends `@ImportAutoConfiguration` to look in `spring.factories` using the name of the annotated class as the key when the `value` attribute isn't used.
