### ISSUE TITLE
Create an ActiveMQ starter

### ISSUE THREAD

**Issue by ewolff** [spring-projects/spring-boot#6003]
There are starters for HornetQ and Artemis but no starter for ActiveMQ. This would just include the dependencies to ActiveMQ to make sure Spring Boot configures ActiveMQ accordingly. This seems like an obvious idea - I am not sure why it's not implemented.

**Comment by snicoll** [comment]
I actually don't think it's an oversight. Historically we wanted one starter for JMS (and have an opinionated view on this) and we chose HornetQ. It turns out HornetQ has been donated to the Apache software foundation and Artemis came along. I'd be in favour of deprecating the HornetQ starter and only keep artemis.

**Comment by ewolff** [comment]
Because it seems so easy to do I was wondering why it hasn't been done...
However, I feel such a starter would be helpful. People will look for a
starter to see if there is support. If there is no starter, they might miss
that in fact it is supported. What do you think?

**Comment by snicoll** [comment]
> Because it seems so easy to do I was wondering why it hasn't been done...

I think I just answered to that, didn't I? It's hard to draw the line but I can see we've done that for the JTA support as well (one starter for Atomikos and one for Bitronix). Given that ActiveMQ is superseded by Artemis, I am really not keen of adding a starter for it _now_. I've added the `for-team-discussion` label to raise it during our next team meeting.

**Comment by ewolff** [comment]
Yip, clear to me - thanks for explaining! Let me know what the result of the discussion is. :-)

**Comment by jmkgreen** [comment]
I've just worked on a project with about a dozen spring-boot artefacts that connect to ActiveMQ. I added `@EnableJMS` and specified a `--spring.activemq.broker-url`. I also had to write a class to wrap the resultant `ConnectionFactory` into a `JmsConfiguration` (then inside a `ActiveMQComponent` for Camel's use).

Is the above to be made simpler or am I mis-reading things?

**Comment by snicoll** [comment]
Yes you're mis-reading things. The starter is about collecting the dependencies for Foo (here activemq). If you feel we can be smarter (the wrapping thing) a PR is welcome or a separate issue that explains in details what you had to do and what you feel boot should do for you.

**Comment by snicoll** [comment]
Closing in favor of the PR #6010
