### ISSUE TITLE
Document @SpringBootTest and autowiring MockMvc

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6008]
Empirically I can only autowire a `MockMvc` if I use `@WebTest` (and that doesn't work at all for some applications, which is a separate topic). Surely if I have a `@SpringBootTest` it can make a `MockMvc` for me? Or am I missing something?

**Comment by philwebb** [comment]
You can use `@AutoConfigureMockMvc`. See `UserVehicleControllerApplicationTests` for an example.

**Comment by dsyer** [comment]
Thanks. Didn't see that in the user guide or in javadocs, hunting around for about 30mins.

**Comment by philwebb** [comment]
That tells me our docs need work :)

**Comment by snicoll** [comment]
I don't know if the documentation has changed much (doesn't look like it) but the Javadoc of `MockMvcTest` states:

> If you are looking to load your full application configuration and use MockMVC, you should consider @SpringBootTest combined with @AutoConfigureMockMvc rather than this annotation.

There is also something in the documentation about it though it can be more explicit. I'll rephrase and add a `TIP` to make it a bit more obvious.
