### ISSUE TITLE
Statsd MetricWriter AutoConfiguration causes circular bean references with Exporters that use MetricWriter

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-projects/spring-boot#6012]
(Using spring boot 1.3.5.RELEASE)
I have a custom Exporter that takes some PublicMetrics (like the SystemPublicMetrics) and writes them to a MetricWriter.

My bean declaration looks like this
```java
@Bean
@ConditionalOnBean({CacheStatisticsProvider.class})
public Exporter cachePublicMetricsMetricReader(CachePublicMetrics publicMetrics, MetricWriter metricWriter) {
    return new PublicMetricsExporter(publicMetrics, metricWriter);
}
```
When I register my own MetricWriter, everything is fine and the Exporter is hooked up via the `MetricExportAutoConfiguration`. When I try to use the autoconfigured StatsdMetricWriter (by setting the `spring.metrics.export.statsd.host` property) I get a `BeanCurrentlyInCreationException`.

I suspect the issue is that the StatsdMetricWriter is declared in `MetricExportAutoConfiguration` and not in it's own configuration class. So when the container tries to resolve my dependency on a MetricWriter, it triggers the rest of `MetricExportAutoConfiguration` which in turn tries to inject my Exporter that is currently in creation.

My current workaround is to declare the StatsdMetricWriter myself. If needed, I can provide a sample project that highlights the issue.

**Comment by snicoll** [comment]
`@ConditionalOnBean({CacheStatisticsProvider.class})`

Is your configuration an `auto-configuration`? That is a `@Configuration` class registered in `META-INF/spring.factories` with the proper `@AutoconfigureAfter` declaration. You can't use `@ConditoinalOnBean` in "regular" `@Configuration` class (see the Javadoc). If that still doesn't help, a sample  would be nice.

**Comment by KamikaZeeFu** [comment]
The configuration is an `auto-configuration`. Your pointer about `@AutoconfigureAfter` lead me to the solution, I had to include `MetricExportAutoConfiguration.class` in `@AutoconfigureAfter`. I had it in `@AutoconfigureBefore` because I assumed that since I provide Exporters, my config had to come first.
Seems like I still don't fully grasp the whole auto-config ordering.

Thanks for pointing me in the right direction :)
