### ISSUE TITLE
Use default security user and password with TestRestTemplate

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#6014]
If I use default security user and password, I can't utilize the new feature of `TestRestTemplate`.

I had to use the old way with it as follows: https://github.com/izeye/spring-boot-throwaway-branches/blob/rest-and-restdocs-with-security/src/test/java/com/izeye/throwaway/PersonControllerTests.java

So it would be nice to use default security user and password with `TestRestTemplate`.

**Comment by philwebb** [comment]
Possibly to consider in combination with #5509. Not sure we should do this by default but we could make it easier.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by philwebb** [comment]
We generally feel that setting a specific password in the tests, rather than using a random one is the best way to solve this.
