### ISSUE TITLE
1.4.0.M1 -> 1.4.0.M2 Migration : issue serving custom static content with WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter

### ISSUE THREAD

**Issue by jceloi** [spring-projects/spring-boot#6019]
Hello,

I'm using a specific configuration to serve some static content in my application (which is mainly a rest services app), as seen on that tutorial https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot

```
@Configuration
    @AutoConfigureAfter(DispatcherServletAutoConfiguration.class)
    public class SwaggerUiResourceConfiguration extends WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter {

    private static final String[] SWAGGERUI_RESOURCE_LOCATIONS = {"classpath:/static/swaggerui/" };

    @Override
        public void addResourceHandlers(ResourceHandlerRegistry registry) {
            registry.addResourceHandler("/swaggerui/**").addResourceLocations(SWAGGERUI_RESOURCE_LOCATIONS);
        }
    }
```

I'm encountering an problem migrating this code from M1 to M2 : the implicit default constructor disappear as this constructor now has been introduced in M2 :

```
	public WebMvcAutoConfigurationAdapter(ResourceProperties resourceProperties,
				WebMvcProperties mvcProperties, ListableBeanFactory beanFactory,
				HttpMessageConverters messageConverters,
				ObjectProvider<ResourceHandlerRegistrationCustomizer> resourceHandlerRegistrationCustomizerProvider)
```

Now, I can't simply declare this constructor in my code, an call the parent constructor because **WebMvcAutoConfiguration.ResourceHandlerRegistrationCustomizer** is in a package reach and is not accessible from my code.

Did I miss something in the migration process doc or in my overall implementation / use and resource handler declaration ?

Thank you !

**Comment by bclozel** [comment]
Just a question — why aren't you using a regular  Spring MVC `WebMvcConfigurerAdapter` here?

```
@Configuration
public class SwaggerUiResourceConfiguration extends WebMvcConfigurerAdapter {

  private static final String[] SWAGGERUI_RESOURCE_LOCATIONS = {"classpath:/static/swaggerui/" };

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/swaggerui/**")
            .addResourceLocations(SWAGGERUI_RESOURCE_LOCATIONS);
  }
}
```

I don't think you're supposed to extend from Spring Boot's existing Auto-Configuration classes.
I other words, could you elaborate a bit on what you're trying to achieve with this auto-configuration?

**Comment by jceloi** [comment]
Thank you for your answer, the same idea was emerging in my mind...
This code has quite some age and I can't find any good reason for this specific choice in fact. It looks silly now that you highlight it.

Directly extending WebMvcConfigurationAdapter is the way to go and achieves the goal ! Thanks ! This can be closed safely.

**Comment by jihao** [comment]
Had the same question, referred to the tutorial.
I also extended WebMvcAutoConfigurationAdapter before.

Then I read the latest document http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration

> If you want to keep Spring Boot MVC features, and you just want to add additional MVC configuration (interceptors, formatters, view controllers etc.) you can add your own @Bean of type WebMvcConfigurerAdapter, but **without** @EnableWebMvc. If you wish to provide custom instances of RequestMappingHandlerMapping, RequestMappingHandlerAdapter or ExceptionHandlerExceptionResolver you can declare a WebMvcRegistrationsAdapter instance providing such components.
