### ISSUE TITLE
Support ResourceTransformer style transformations for Spring Boot Plugin

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#6024]
Maven Shade Plugin has a mechanism to transform shaded entries. This is quite useful for pre-processing resources to transform or replace with something else. 

I also checked EntryTransformer part of Spring Boot and seems a good candidate to me expose as an API. 

What do you thing about providing something similar to shade plugin for Spring Boot plugin?

**Comment by snicoll** [comment]
Is that solving an actual use case? I'd rather hear from that before anything else.

**Comment by cemo** [comment]
We have been using Shade plugin currently with transformers. Our JSP files are pre-processed in build time with some transformers. 

In our development environment links starting with `/assets/` are pointing our local environment. However in production environment they are replaced by their CDN counterpart. These resources are fixed at build time.

**Comment by wilkinsona** [comment]
I don't think that support for such transformations should be part of Spring Boot's Maven plugin as they're not specific to Boot.

The Boot plugin simply repackages an existing jar. Is there not another plugin in the Maven ecosystem that can perform the transformations prior to repackaging?

**Comment by cemo** [comment]
Spring Boot Maven has already some transformers such as [PropertiesMergingResourceTransformer]. Spring Boot also a mechanism similar to Maven Shade Resource Transformers at [here]. I think that this might be converted to an API and we can register our custom hooks to modify repackaged JAR at build time. 

Having transformation before repacking before `built time` is not something we want. The problem is that the processed files can be in 3rd party jars which are built before ours. In build time we need to stamp that build with the latest `assets project`. I do not know other solutions prior to repacking in default maven lifecycle. 

Another way would be accessing jar file before uploading somewhere and enhancing it. This will be useful only for us. But I am inline to something similar to Maven Shade Resource is doing. In this way maven shade plugin existing resource transformations  can be easily implemented in Spring Boot way.
  
[here]: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/Repackager.java#L330-L398
[PropertiesMergingResourceTransformer]: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/PropertiesMergingResourceTransformer.java

**Comment by wilkinsona** [comment]
The `PropertiesMergingResourceTransformer` is for use Maven's shade plugin: it merges `spring.factories` and the like. The other mechanism that you've linked to is Boot-specific and is used to ensure that the layout of the repackaged jar is correct.

Unlike the Shade plugin, there are no common transformations (other than the layout) that need to be applied to a repackaged jar – that's one of the primary benefits of nested jars versus shading – so I don't think that Spring Boot's Maven plugin is the right place to solve your problem.
