### ISSUE TITLE
Developer tools: Restarting with holding state of some objects

### ISSUE THREAD

**Issue by MirekSz** [spring-projects/spring-boot#6025]
Hello,
during restart spring removes all objects and creates new ones. Maybe you could add some feature to prevent some object states during restart. For example in our app most of the time takes building SessionFacotry (2000 entities about 30 sec). But we very rarely change something in it.

If this is possible? There could be more examples for it

**Comment by wilkinsona** [comment]
I think that's really beyond the scope of what we've tried to achieve with DevTools. If you're looking for more sophisticated support then I'd recommend looking at something like JRebel.
