### ISSUE TITLE
enhancement: visibility of DefaultErrorAttributes#extractBindingResult

### ISSUE THREAD

**Issue by Kidlike** [spring-projects/spring-boot#6026]
Hi,

Method in question is here:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/DefaultErrorAttributes.java#L151

In an attempt to write a custom ErrorAttributes#getErrorAttributes method,
the extractBindingResult seemed to be crucial to my implementation.

It feels dirty to have to copy and paste the default implementation.

I don't know which would be the ideal solution; It doesn't really belong in ErrorAttributes because it's implementation specific, but maybe could be public in DefaultErrorAttributes ?

I hope I'm not missing something :)

Cheers

**Comment by philwebb** [comment]
Are you extending `DefaultErrorAttributes` for your implementation? Would making it `protected` work? Alternatively perhaps we could create an `AbstractErrorAttributes` class with useful methods pulled up.

I'm not too keen to extract `extractBindingResult` to it's own class.

What's your custom `ErrorAttributes` implementation doing? Perhaps you can share something so we can see which parts of `DefaultErrorAttributes` are generally useful.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Kidlike** [comment]
I ended up taking a different approach because I didn't want to copy code from Spring.

Making it `protected` would definitely be an easy improvement.

Since there's no much interest for the moment I wouldn't bother with `AbstractErrorAttributes`.

Thanks :)

**Comment by snicoll** [comment]
@Kidlike there is an interest but you're not really answering any of our questions. If we have more context, maybe we'll be able to provide something that helps you and help others. Can you please reply to the questions above? Thanks.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
