### ISSUE TITLE
Spring-Boot application launched as service on Linux should source the systems locale

### ISSUE THREAD

**Issue by ClemensSchneider** [spring-projects/spring-boot#6028]
I ran into an issue when having registered a Spring-Boot application to launch at system-startup using init.d (Ubuntu Server 14.04 LTS) [Docs](http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-initd-service)
The application listens to changes in the filesystem and processes the changed files. The filenames may contain arbitrary non-ascii characters (ß, äöü, é, ..).
When being launched at system startup, the application was not able to access the files, as the characters were incorrectly reported by the OS. Manually restarting the application via an interactive ssh-session solved the issue so that all files could be read.

I investigated the environment-variables that were set for the process and compared 'launched-at-boot-time' with 'launched-manually'. I noticed, that there was no `LANG` environment-variable being set for the process launched at boot-time in contrast to the manually launched process.
Further research lead me to a tomcat launch-script (https://gist.github.com/FrankGrimm/1480319) where `/etc/default/locale` is sourced to export the `LANG` environment-variable before launching the JVM.

I then did the same using a `.conf`-file for my application ([Docs](http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-script-customization-conf-file)) with the following content:

    if [ -r /etc/default/locale ]; then
      . /etc/default/locale
      export LANG
    fi

Now the application behaves as expected and is able to process arbitrary named files even after being launched at system-boot.

Would be nice if this behavior would be provided by Spring Boot out of the box.

**Comment by wilkinsona** [comment]
The `LANG` environment variable is one of the few that `service` does not strip out. When you launch the application as a service, what user are you using? How is the `LANG` environment variable being set for that user?

**Comment by ClemensSchneider** [comment]
I tried launching the application both as root and regular user (ubuntu on AWS EC2) with the same result. I'm not exactly sure where it is regularily being set for the user and was expecting the application (when launched with the user-account) to use the same locale-settings as if being connected via shell, where `locale` prints:

>
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

Seems that I was wrong?

**Comment by wilkinsona** [comment]
It may well be getting set as part of setting up your shell's profile. AFAIK, that won't happen when launching a service with `start-stop-daemon`. Having thought about this some more, I think this is rather academic anyway as I don't think that Boot should run `/etc/default/locale` automatically.

There's no saying that `/etc/default/locale` will provide the desired configuration for the service and it may override some configuration that's already been set. That means we'd need to provide a switch to turn off the behaviour. At that point, it's easier just to configure `LANG` and any other environment variables that you need in the `.conf` file that accompanies your jar.

**Comment by ClemensSchneider** [comment]
Okay, then the issue will at least help others running into similar issues.
Maybe it's worth a note in the documentation that it's advisable to set (or at least consider setting) the `LANG` for your application because it took me quite some time to figure out what the cause was and why there was no `LANG` set?

Other references: 
[StackOverflow](https://stackoverflow.com/questions/13415975/cant-read-utf-8-filenames-when-launched-as-an-upstart-service)
[Launchpad - the official ubuntu tomcat-package runs /etc/default/locale for this reason](https://bugs.launchpad.net/ubuntu/+source/tomcat5.5/+bug/153672)

**Comment by zend** [comment]
@ClemensSchneider 
There is a solution for your case. You can create a conf file in the same directory as the jar file, and put your environment variables in. It will be sourced automatically. 

See the code:
`[[ -r "${CONF_FOLDER}/${configfile}" ]] && source "${CONF_FOLDER}/${configfile}"`
