### ISSUE TITLE
Improve Maven repositories declaration

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6031]
The observations are summarized here: https://github.com/scratches/maven-library-tests. It's mystifying to me, because I can't yet reproduce it with a toy project, but spring-boot-starter-parent seems to pollute user builds with references to repo.spring.io.

**Comment by snicoll** [comment]
It doesn't for me and we figured it out. Dave had a `~/.m2/local-settings.xml` that was bringing the repo definition.

**Comment by snicoll** [comment]
I found an extra `gradle` repository that is hard-coded in the gradle module (and the tests). We should probably fix that. Using the trick of property negation, the profile is active unless a given property is set so we can remove the copy/paste in each profile. I am working on a proposal now.

**Comment by snicoll** [comment]
@wilkinsona @dsyer I have a proposal in 3fd235b - I've tested that the prepare goal still works as expected and that the "ci" profile still removes the profile definition. It's not a huge change but things look more consistent and we have no more crazy duplications in profile definitions. 

Thoughts?

**Comment by dsyer** [comment]
LGTM

**Comment by snicoll** [comment]
One improvements would be to include the gradle repo only for the two gradle modules.

**Comment by snicoll** [comment]
For some reason, this change seems [to break the build](https://build.spring.io/download/BOOT-PUB-JOB1/build_logs/BOOT-PUB-JOB1-4253.log)

**Comment by snicoll** [comment]
@philwebb I have reverted. It seems that our build relies on some weird use of modules definition combined with a _default_ profile. I'd like to understand how it works since `-Pfull` does not trigger anything in the reactor as far as I can see (this can't be right given the name).

**Comment by snicoll** [comment]
The original issue has been identified and we may want to revisit profile management when switching to another CI.
