### ISSUE TITLE
Add support for Jest

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6032]

**Comment by snicoll** [comment]
The current elasticsearch auto-config relies on Spring Data elasticsearch that has several limitations. The [Jest client](https://github.com/searchbox-io/Jest) is quite nice and auto-configuring that if it's available on the classpath would be nice.

We have some configuration in `spring.data.elasticsearch` and I'd like something Spring Data independent from `spring.elasticsearch` if possible. Having both Jest and the Spring Data support at the same time sounds challenging, the best would be that the latter reuses what the former has configured.

**Comment by philwebb** [comment]
Just wondering if this should live under an Elasticsearch namespace?

**Comment by snicoll** [comment]
I had the exact same reasoning. The current spring data support doesn't pair (you can't specify an url now). So you'd have a `spring.elasticsearch.uris` that wouldn't be used at all by Spring Data elasticsearch. Seems weird to me.

**Comment by philwebb** [comment]
We're thinking `spring.elasticsearch.jest` for the property name and something similar for the java package.
