### ISSUE TITLE
Elasticsearch documentation is 404

### ISSUE THREAD

**Issue by jmkgreen** [spring-projects/spring-boot#6033]
Ref http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

Scroll to `ELASTICSEARCH` and click the link. 404 on GitHub.

**Comment by jmkgreen** [comment]
Ping @philwebb ?

**Comment by snicoll** [comment]
No need to ping Phil @jmkgreen - That's a typo in the doc.
