### ISSUE TITLE
Polish FileSystemWatcher

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6039]
While looking into #6038, I noticed a few issues with `FileSystemWatcher`:

 - It uses synchronised methods, thereby exposing the lock that's used (the `FileSystemWatcher` instance) to the class's callers which could lead to deadlock if not used carefully
 - Access to `listeners` isn't thread-safe – it's written to while holding a lock but is read without holding a lock
 - Access to `folders` isn't thread-safe – it's written to while holding a lock but is read without holding a lock
 - `watchThread` is a `Thread` subclass rather than a plain `Thread` that's created with an implementation of `Runnable`

**Comment by wilkinsona** [comment]
@philwebb Does `folders` need to be ordered (a `LinkedHashMap`)? If not, and if we can avoid storing `null`, it could be a `ConcurrentHashMap` instead.

**Comment by philwebb** [comment]
That code was garbage collected from my brain ages ago :)  I can't see any reason why it needs to be a `LinkedHashMap`.
