### ISSUE TITLE
JettyEmbeddedServletContainerFactory cipher configuration

### ISSUE THREAD

**Issue by ksperling** [spring-projects/spring-boot#6041]
When ciphers are configured manually via `server.ssl.ciphers` they are passed to `SslContextFactory.setIncludeCipherSuites()`, however the excluded cipher list remains at whatever is the default in Jetty, and the excludes list overrides the include list (for example since 9.3.7 Jetty excludes all SHA1 and MD5 cipher suites https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb, see also https://github.com/eclipse/jetty.project/issues/497)

I think an appropriate behaviour would be for JettyEmbeddedServletContainerFactory to clear the exclude list when a non-empty cipher list is set, so that whatever I configure in `server.ssl.ciphers` is what I get (modulo JCE/JSSE provider policy of course, but that's outside the scope of either Spring or Jetty to configure).

The code also doesn't handle an empty list of ciphers correctly currently -- Jetty treats an empty list to mean the default configuration with all available ciphers (minus excludes), so in that case we definitely don't want to clear the exclude list. The easiest way to make this aspect correct and consistent might be to change `org.springframework.boot.context.embedded.Ssl.getCiphers()` to return `null` when `ciphers` is non-null but empty.

This issue affects both 1.3.x and 1.4.x

**Comment by snicoll** [comment]
It looks like this change only impacts Jetty 9.3 - Spring Boot still builds with 9.2 which makes this hard to test :(

**Comment by philwebb** [comment]
Reopening to consider https://github.com/spring-projects/spring-boot/commit/6cf878424f9d897a68cc8893b4ed5e7629bbaa5d#commitcomment-17826230

**Comment by snicoll** [comment]
I already fixed it in https://github.com/spring-projects/spring-boot/commit/5250fb127a131b5970ac0f9da6bee972184691b2
