### ISSUE TITLE
BeanCurrentlyInCreationException error depends on @ComponentScan basePackages values order

### ISSUE THREAD

**Issue by patoi** [spring-projects/spring-boot#6045]
We have an issue with 'circular reference' error. When I started my Spring Boot app on my Ubuntu 16.04 desktop OS, the issue is not showing up. If I running the app on the Ubuntu 16.10 Server OS, then I get an error:

    Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'exampleService': Requested bean is currently in creation: Is there an unresolvable circular reference?

If I change
```java
@ComponentScan(basePackages = "org.springframework.boot.issues.ghXXXX")
```
to
```java
@ComponentScan(basePackages = {"org.springframework.boot.issues.ghXXXX.server", "org.springframework.boot.issues.ghXXXX.service", "org.springframework.boot.issues.ghXXXX"})
```
then I don't get BeanCurrentlyInCreationException on Ubuntu 16.10 Server OS.

I can reproduce the issue with a maven project. The code is failing on same OS, if I change @ComponentScan basePackages order.

**Comment by wilkinsona** [comment]
Thanks for the sample project. There's a circular dependency between `MyServer` and `ExampleService`. `MyServer` uses field injection for its `ExampleService` dependency. `ExampleService` uses constructor injection for its `MyServer` dependency.  For this to work at all, Spring Framework must be doing the following:

1. Creating an instance of `MyServer` by calling its default constructor
2. Creating an instance of `ExampleService`, passing `MyServer` to its constructor
3. Set the `exampleService` field on `MyServer`

Step 2 is problematic as it means that a partially-initialised `MyServer` instance is being injected into `ExampleService`. In some ways it's impressive that Spring Framework manages to wire this together at all. That said, I'd expect it to either work or fail consistently, irrespective of the OS.

Unfortunately, there's nothing that we can do in Spring Boot to address this. You may want to raise an [SPR JIRA ticket](https://jira.spring.io/browse/SPR).

**Comment by krishna81m** [comment]
While we can solve with correct injection or lazy, I am still curious based on stackoverflow and personal experience, why would this be a different behavior with spring boot, i.e., it does not happen if we use traditional spring non-boot application?
