### ISSUE TITLE
ApplicationReadyEvent not listened to when declaring your own EventMulticaster

### ISSUE THREAD

**Issue by kabadisha** [spring-projects/spring-boot#6048]
Spring boot: v1.3.5.RELEASE

I've found an issue that I think is a bug:

**In a nutshell:**
If you declare your own 'applicationEventMulticaster' bean then the **ApplicationReadyEvent** will be published but no listeners will be triggered.

**In detail:**
The class **EventPublishingRunListener** instantiates an instance of **SimpleApplicationEventMulticaster** for itself in its constructor and holds it as a private property.

Once the context is prepared,  it then registers its instance of **SimpleApplicationEventMulticaster** as the bean 'applicationEventMulticaster'.

The problem occurs when you declare that bean yourself in order to provide an alternative **TaskExecutor** (for example if you want to use an asynchronous implementation). Something like this:
```
/**
 * Set up multicast for the events so that they execute asynchronously.
 * @return
 */
@Bean(name = "applicationEventMulticaster")
public ApplicationEventMulticaster simpleApplicationEventMulticaster() {
	SimpleApplicationEventMulticaster eventMulticaster = new SimpleApplicationEventMulticaster();
	eventMulticaster.setTaskExecutor(new SimpleAsyncTaskExecutor());
	return eventMulticaster;
}
```
If you do this it will work fine for almost all events, which is probably how this has gone unnoticed. However any events published by **EventPublishingRunListener** are published to the original ApplicationEventMulticaster that it still holds a reference to as a private property. The problem is that all the listeners are registered with your freshly declared multicaster and so they never receive these events.

This problem can be demonstrated by installing the Spring Boot Admin Client on a vanilla Spring Boot application where the only customisation is to implement your own 'applicationEventMulticaster' bean.
The client listens for **ApplicationReadyEvent** to trigger its self registration process. This never happens.

**A workaround:**
I implemented the following workaround which fetches the existing event multicaster and simply changes its task executor:
```
@Configuration
public class Loader implements ApplicationListener<ContextRefreshedEvent> {

	public void onApplicationEvent(ContextRefreshedEvent event) {
		SimpleApplicationEventMulticaster originalEventMulticaster = event.getApplicationContext().getBean(AbstractApplicationContext.APPLICATION_EVENT_MULTICASTER_BEAN_NAME, SimpleApplicationEventMulticaster.class);

		originalEventMulticaster.setTaskExecutor(threadPoolTaskExecutor());
	}

	@Bean
	public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
		return new ThreadPoolTaskExecutor();
	}
}
```

**A suggested fix:**
I'm new to Spring Boot, but I would suggest that the fix is to make the **publishEvent** method of **EventPublishingRunListener** fetch the multicaster from the context (if it exists). That way it will publish to our new one.

**Comment by snicoll** [comment]
I got a bit confused by the original report and I think a sample would be nice if you want to make sure we're talking about the same problem.

The issue is that we don't care whether there is a custom mutlicaster or not. We register our own as a singleton and Spring Framework latter do its magic and doesn't find it because of the way it is registered.

**Comment by kabadisha** [comment]
Yeah, I think you've got it.
**EventPublishingRunListener** holds a private reference to the multicaster it created in its constructor. 
When you register your own multicaster later in the startup, **EventPublishingRunListener** still publishes its events to the original multicaster that it still holds a reference to.

Unfortunately, all of the listeners are registered with the custom defined multicaster and so never get the events that **EventPublishingRunListener** publishes.

**Comment by snicoll** [comment]
@kabadisha thanks for the report, I'd appreciate if you could validate that the upcoming `1.4.0.BUILD-SNAPSHOT` works for you. It should be available in an hour or something.

**Comment by kabadisha** [comment]
Awesome - thanks for picking it up. I've taken a look at your change and it looks like you've solved the issue. I will try and test tomorrow if I get the chance.

Thanks 👍
