### ISSUE TITLE
spring init --dependencies takes any value and generates invalid pom.xml 

### ISSUE THREAD

**Issue by kevinhooke** [spring-projects/spring-boot#6061]
This may be by design to allow for supporting new starter dependencies, but the --dependencies option on spring init cli will take any invalid value and generate a maven dependency following the pattern:

spring-boot-starter-dependencyvaluehere

If you mistype a valid value like web as wbb, you'll get a dependency generated for an invalid dependency, like

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-wbb</artifactId>
		</dependency>
```
This is tricky to work out what's wrong if you don't notice that you mistyped the dependency name.

It would be a useful improvement if the dependency value could be validated against known available dependencies.

**Comment by snicoll** [comment]
This is indeed by design. The service does that as well so if there is anything to fix it should be done there. But I don't think we should.

**Comment by snicoll** [comment]
@kevinhooke I've created https://github.com/spring-io/initializr/issues/234
