### ISSUE TITLE
Enhancement: add timeout to the EmbeddedMongoAutoConfiguration

### ISSUE THREAD

**Issue by ydemartino** [spring-projects/spring-boot#6062]
I am using a very slow machine for my CI environment, starting up embedded mongo takes a lot of time and results in a timeout.

I would like to pass the timeout for the embedded mongo like this:
`spring.mongodb.embedded.timeout=30000`

For now I duplicated the `EmbeddedMongoAutoConfiguration` class to add the timeout in the `embeddedMongoConfiguration()` method and it fixes the issue on my machine.

**Comment by philwebb** [comment]
@ydemartino Did you mean to close this issue?

**Comment by ydemartino** [comment]
Yes, for some reasons, I did not manage to put the configuration file in the src/test folder at first. But now it's working and I don't mind having more config files under src/test.
