### ISSUE TITLE
Add Maven Archetype Catalog to CI

### ISSUE THREAD

**Issue by edwardbeckett** [spring-projects/spring-boot#6063]
Continuing on the [prior request](https://github.com/spring-projects/spring-boot/issues/282) to update the Spring Boot maven archetype catalogs, possibly consider creating a CI trigger to republish the maven archtypes in sync with the builds.

**Comment by snicoll** [comment]
May I ask why? Have you looked at start.spring.io (it has support for `spring init`, the IDE, curl, httpie)? Any reason it does not suit your needs?

**Comment by EdwardBeckett** [comment]
@snicoll For convenience really...I typically import a maven catalog into Intellij IDEA 

![snap-5-28-2016-00](https://cloud.githubusercontent.com/assets/949373/15629009/9b7d2244-24dd-11e6-84cf-4d5f4fa4a321.png)
---

or use them at the maven cli ... ( I.E. `mvn archetype:generate -Dfilter=org.springframework.boot: ...` 

![snap-5-28-2016-01](https://cloud.githubusercontent.com/assets/949373/15629015/ca10ceb2-24dd-11e6-9484-e21e62b4b6be.png)

**Comment by philwebb** [comment]
We're not keen to invest in this. The start.spring.io API appears to working well for most people.

**Comment by edwardbeckett** [comment]
@philwebb ~ Guess it didn't draw much interest... np.
