### ISSUE TITLE
Please update jOOQ version > 3.8.0

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#6064]
Currently Boot depends on jOOQ 3.8.0 which has a severe performance issue during compilation of Java code.
See http://stackoverflow.com/questions/34223249/slow-compilation-with-jooq-3-6-plain-sql-and-the-javac-compiler

**Comment by lukaseder** [comment]
I can confirm this. While this only affects *some* users who use jOOQ's API in a specific way (embedded plain SQL), for those users, the experience can really turn very bad.

Version 3.8.1 fixed this issue. The current version is 3.8.2

**Comment by marceloverdijk** [comment]
Yes I was using plain SQL ;-). Some background: https://discuss.gradle.org/t/gradle-compilejava-very-slow-90s-for-very-small-project/17743

**Comment by marceloverdijk** [comment]
Other users experiencing this issue can easily upgrade the version, by overriding the version `build.gradle` like:

`ext["jooq.version"] = "3.8.2"`

But off course good to update the default Boot jOOQ version.

**Comment by marceloverdijk** [comment]
Thx!
