### ISSUE TITLE
Review fix for #5819 in light of SPR-14257

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6076]
I have a suspicion that the fix for #5819 may need to be modified or could even be redundant due to [SPR-14257](https://jira.spring.io/browse/SPR-14257).

**Comment by snicoll** [comment]
The fix was applied in the 1.3.x branch as well. I guess we don't want to touch that? `4.2.7` isn't out yet.

**Comment by wilkinsona** [comment]
I was wrong; the fix is still required
