### ISSUE TITLE
Social: make SocialProperties and SocialAutoConfigurerAdapter public

### ISSUE THREAD

**Issue by Exordian** [spring-projects/spring-boot#6078]
It should be pretty common to extend at least SocialProperties when adding more OAuth2 providers. There are some unofficial or not yet released APIs (spring-social-google, spring-social-github) that currently requires copy-pasting those classes to use them, especially SocialProperties. IMO it does not make sense to leave those classes package local.

**Comment by philwebb** [comment]
Sold!
