### ISSUE TITLE
Jetty version 9.2.16.v20160414 has bug affecting use of HTTP proxy for HTTPS tunnels

### ISSUE THREAD

**Issue by sirlatrom** [spring-projects/spring-boot#6079]
Fixed in version 9.2.17.v20160517.

    1 jetty-9.2.17.v20160517 - 17 May 2016
    2  + 560 Jetty Client Proxy Authentication does not work with HTTP Proxy
    3    tunneling
    4  + 571 AbstractAuthentication.matchesURI() fails to match scheme
Source: https://fossies.org/diffs/jetty-distribution/9.2.16.v20160414_vs_9.2.17.v20160517/VERSION.txt-diff.html

**Comment by philwebb** [comment]
Fixed in #6088
