### ISSUE TITLE
Consider adding Spring Session starter

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#6082]
Since Spring Boot provides auto-configuration capabilities for Spring Session, it might be useful to add a starter module.

See vpavic/spring-boot@947fbbc. If this approach is acceptable I can submit the PR based on this commit.

Alternatively, vpavic/spring-boot@a2e8453 adds multiple starters, one for each supported repository backend, however IMO a single starter is better and much simpler option.

**Comment by philwebb** [comment]
I'm not convinced that we really need one for `spring-session` since it's a one-line dependency anyway. I'll tag this as `waiting-for-votes` to see what the general feeling is.

**Comment by vpavic** [comment]
> I'm not convinced that we really need one for spring-session since it's a one-line dependency anyway.

You do need the web stack as well, hence also the ```spring-boot-starter-web``` dependency.

Anyway, I wasn't sure myself that merits the starter but since there are quite a few starters that pull the same amount of dependencies (or even less) and that all Spring projects Boot provides auto-configuration for do have their own starters, I've proposed this one for consistency sake.

**Comment by snicoll** [comment]
With the modules split, I think it's pretty clear we won't add a starter. We've discussed this today so I am closing this, we can reopen if I missed something.

**Comment by vpavic** [comment]
Agreed - I was about to close this myself today.
