### ISSUE TITLE
Expose default locale for AcceptHeaderLocaleResolver as application property

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6083]
[SPR-14312](https://jira.spring.io/browse/SPR-14312) has introduced the ability to define a default `Locale` for the `AcceptHeaderLocaleResolver` (read up on the JIRA ticket for more details) which is registered with Spring MVC by default. It would be cool if that default `Locale`could be defined as application property (e.g. `spring.mvc.default-locale`) just like `spring.mvc.locale` can be defined already but the latter switching the resolver to a `FixedLocaleResolver`.

**Comment by snicoll** [comment]
@olivergierke & al, looking [at the code](https://github.com/spring-projects/spring-boot/pull/6084/files#r66451312) I am wondering why we need to have two value for the locale. Wouldn't it be better if a single value was used and a boolean flag determines if we "force" the locale or not (something like `spring.mvc.locale` and `spring.mvc.force-locale`).

**Comment by olivergierke** [comment]
Personally I'd be fine with that. However, that basically changes the semantics of the configuration property and thus might alter existing applications in a way that's not anticipated by users.

I agree that defining both properties is an invalid state (I guess we could detect that and throw an exception). The approach with the two dedicated properties is that I have to set exactly one property for each scenario. With the change as you suggest it, what has previously been a single property configuration now requires configuring two properties.

**Comment by snicoll** [comment]
>  what has previously been a single property configuration now requires configuring two properties.

Only for this new feature. For the existing one (`spring.mvc.locale`) everything work as before. For this new feature, you have to set the locale _and_ configure that override is allowed. We have other places in Boot that does exactly that. An enum would probably be more explicit if we find a good name for it.

**Comment by bclozel** [comment]
If I understand correctly, we're talking here about two different things:

1. Forcing the locale no matter what the HTTP client gives in the `Accept-Language` header (which is the current behavior)
2. Providing a default locale in case the HTTP client didn't provide one

What are the main use cases/typical examples for both?
I could see 1) happening for in-house applications (although it's quite strange) and 2) seems OK but probably limited to headless clients such as Curl, `RestTemplate`...

I agree `spring.mvc.locale` and `spring.mvc.force-locale` proposal, but I'm not sure which should be the default case. For backwards compatibility reasons we could argue 1), but I'm wondering if developers use 1) while they really need 2), which is more flexible.

**Comment by olivergierke** [comment]
Here's the story behind the request: Spring RESTBucks has [added support](https://github.com/olivergierke/spring-restbucks/commit/7ed1c2bf85493af9c089079570c07761ee36f5ff) for rendering `Money` values in a `Locale` dependent way, which is quite cool as clients can just send a language header and can just present the values returned to its users.

For test cases, however, I now would have to explicitly add the `Accept-Language` to make them work on both my machine (Germän) and the CI server. And instead of working with an explicit value in the test I thought it would be cool if I could just default the value on the server.

So I looked up what I could already configure in Boot, found the `spring.mvc.locale`, tried it and quickly realized it essentially fixes the locale by configuring the corresponding `LocaleResolver`. That then lead to my enhancement request in Spring Framework and ultimately this one. Assuming that we don't want to change the semantics of already existing properties, I thought adding a `default-locale` would offer a symmetric addition clearly expressing the difference to `locale`. We'd just have to add the new property and reject the simultaneous usage of both properties (or at least log a warning).

With the `force-locale` approach we'd basically either change the current semantics (if it defaulted to `false`) and require users of the existing semantics to add an additional property. If it defaulted to `true`, users with my use case would have to configure two properties instead of one. That combined was the reason I thought `default-locale` is better: you use only one of the two, depending on which semantics you're trying to achieve.

**Comment by snicoll** [comment]
There was a very long conversation behind the scenes about that one and one idea that came to mind was to group them to make this less confusing, that is `spring.mvc.locale.fixed` and `spring.mvc.locale.accept-header-default`. The problem is that we would be deprecating `spring.mvc.locale` to `spring.mvc.locale.fixed` to ensure backward compatibility and deprecating a property that is now a "group" doesn't work very well (especially with yaml).

I am leaning towards an enum and the current property even it can be a bit confusing. The main reason is that if you set `spring.mvc.locale` in a certain profile, it's hard to "undo" it and having a property that controls what happens is much better from that perspective since you're overriding a single value.
