### ISSUE TITLE
Spring Boot Autoconfig of Redis should be @ConditionalOnProperty(spring.redis.host)

### ISSUE THREAD

**Issue by zampettim** [spring-projects/spring-boot#6103]
With Spring Boot 1.3.5, (and 1.3.x in general), Redis Auto configuration always tries to configure a Redis connection if Redis is in the classpath. This causes issues when an app wishes to use its own Auto Configuration to enable or disable Redis. For example, if dev, I want to use the local Session implementation, but in production, I want to use Redis. I have auto configuration that keys off of the existence of the "spring.redis.host" property. This may also apply to the case where when running unit tests, want to use in-memory local session.

Right now, as soon as RedisAutoConfiguration is used, it attempts to create a JedisConnectionFactory, which in turn fails because no host information is configured.

I think just need to add 
```@ConditionalOnProperty(prefix = "spring.redis", name = "host", matchIfMissing=false)```
to RedisAutoConfiguration to resolve this.

**Comment by philwebb** [comment]
I'm not sure we can simply add the `@ConditionalOnProperty`. The `RedisProperties` class has a default `host` value of `localhost`. This won't be set as a property but it will be used when `RedisAutoConfiguration` runs.

> This causes issues when an app wishes to use its own Auto Configuration to enable or disable Redis

Are you saying that you have some additional auto-configuration that needs to disable Redis all together? Perhaps you can set or modify a `spring.autoconfigure.excludes` property in the Spring `Environment` to skip `org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration`. Either that or we could consider adding `spring.redis.enabled` support.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
