### ISSUE TITLE
Spring Boot unit-test fails when building master due to translation of a message with not expected locale

### ISSUE THREAD

**Issue by jgoldhammer** [spring-projects/spring-boot#6106]
**Problem / First analysis**

When building spring boot via mvn test, I got test failures. It seems to be a locale-related issue because the translated reason is printed in german, but was expected to be english...

**Occured Exception**

Results :

```
Failed tests:
  BindFailureAnalyzerTests.bindExceptionDueToValidationFailure:44
Expecting:
 <"Binding to target org.springframework.boot.diagnostics.analyzer.BindFailureAnalyzerTests$ValidationFailureProperties@4ea505e2 failed:

    Property: test.foo.value
    Value: 0
    Reason: at least five

    Property: test.foo.foo
    Value: null
    Reason: darf nicht null sein

    Property: test.foo.nested.bar
    Value: null
    Reason: darf nicht null sein
">
to contain:
 <"Property: test.foo.foo
    Value: null
    Reason: may not be null">

Tests run: 1298, Failures: 1, Errors: 0, Skipped: 2
```

**Environment**

mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"

**Possible solutions**

- I could switch my system to english (not everybody wants to do that)
- Fix the test (e.g. to set the default locale in the test)
- Modify the maven surfire task to start the forked tests with en locale

What are your suggestions here, Spring Boot team? Should I open a bug in github? As suggested in the stackoverflow ticket i have created a ticket.

Thanks, Jens

**Comment by philwebb** [comment]
I've changed the test to set Locale in `@Before` and reset it `@After`. Hopefully that should do the trick. Thanks for reporting the problem.

**Comment by jgoldhammer** [comment]
Hi Phil, thanks for looking at my issue.
This is a microfix now and you are aware that this could happen again with other tests as well,right? So no global solution possible? Thanks Jens

**Comment by philwebb** [comment]
@jgoldhammer I couldn't think of an easy way to fix this globally _and_ have it also work if individual tests are launched in the IDE. A microfix seemed like the best use of time.
