### ISSUE TITLE
Setting spring.resources.static-locations to relative jar url does not work

### ISSUE THREAD

**Issue by goranmagdic** [spring-projects/spring-boot#6109]
Example of value:
`spring.resources.static-locations=jar:file:lib/abc.jar!/static/`
So lib/abc.jar is relative path to jar file.
Request for static content will result in 404 with errors in stack trace: 
```
java.io.IOException: no entry name specified
        at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:187) 
```
Debugging JarURLConnection.getInputStream reveals that line:
```
		String spec = getNormalizedFile(url)
				.substring(jarFile.getUrl().getFile().length());
```
Does not work correctly for relative paths because `getNormalizedFile(url)` will return relative path, but `jarFile.getUrl().getFile()` will return absolute path, so String spec will end up being just part of the file name or it will throw `StringIndexOutOfBoundsException`.

**Comment by wilkinsona** [comment]
Reopening as the new tests fail on Windows

**Comment by philwebb** [comment]
@wilkinsona  could you review bdb0eb29a35680e3892cb8a3d956790aa8e79f32 and see if you think it's a sane fix?

**Comment by wilkinsona** [comment]
@philwebb I've taken a different approach (see 0d207d4) which seems to be quicker than using the cache

**Comment by philwebb** [comment]
Sweet, I knew you'd find a better way :)
