### ISSUE TITLE
Possible issue with Spring Boot 1.3.3 and PostgreSQL 9.1-901-1.jdbc4

### ISSUE THREAD

**Issue by MuriLOCo** [spring-projects/spring-boot#6110]
Hi, I was developing a Spring Boot Application using PostgreSQL 9.1-901-1.jdbc4 and I found something that might cause some headache. I have a `Form.java` annotated with `@Entity` and Spring Boot is creating the table for me. One of the fields were too big so PostgreSQL sent a `WARNING` saying that some fields would be truncated. Then Spring Boot send an error saying that the table was not found.

The problem that took me almost 1 day to figure out is that even is it's a WARNING Spring Boot fails to create the table. So I have to truncate the name of the fields by myself.

I hope this information help someone.

**Comment by philwebb** [comment]
Thanks for the info, hopefully it will help anyone that hits the same problem. I don't think there's much we can do in Spring Boot itself to improve the situation as Hibernate is responsible for handling all of this.
