### ISSUE TITLE
@EnableAspectJAutoProxy can't set 'expose-proxy' property.

### ISSUE THREAD

**Issue by LightError** [spring-projects/spring-boot#6113]
hi. i was working with spingboot. but I found I can't set 'expose-proxy' property.

In spring. We can set <aop:aspectj-autoproxy expose-proxy="true"/> to use AopContext.currentProxy(). but when I want to set with annotation. I can not found any class to set .

In class AspectJAutoProxyRegistrar. It's no method to set . and in AopConfigUtils, the method forceAutoProxyCreatorToExposeProxy() is package.

so I want this imformation can help.

and I found same problem. https://jira.spring.io/browse/SPR-10454

**Comment by philwebb** [comment]
@LightError This would need to be fixed in Spring Framework, please add your comments to [SPR-10454](https://jira.spring.io/browse/SPR-10454).
