### ISSUE TITLE
ConfigFileApplicationContextInitializer, JUnit and YAML file

### ISSUE THREAD

**Issue by ctranxuan** [spring-projects/spring-boot#6120]
Hi,
I am trying to test a subset of a SpringBoot app with JUnit. As stated in the documentation ([here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-configfileapplicationcontextinitializer-test-utility)), we should be able to use `ConfigFileApplicationContextInitializer`.
 
In a JUnit test-case, I am trying to inject a some `@Value` properties from a `application-dev.yml` file (e.g. `@Value("${my.pojo.name}") String name;`). But these values are not injected (I've got the String `"${my.pojo.name}"` injected) when using `ConfigFileApplicationContextInitializer` and the annotation `@ContextConfiguration` while it seems to work when using `@SpringApplicationConfiguration` with a SpringApplication.

**Context**
Given a configuration class and a JUnit class:

```java 
@Configuration
public class PojoConfiguration {
    @Value("${my.pojo.name}")
    public String name;

  @Bean
    public Pojo pojo() {
        return new Pojo(name);
    }
 }

@RunWith(SpringJUnit4ClassRunner.class)
@ActiveProfiles("dev") 
@ContextConfiguration(classes = { PojoConfiguration.class }, initializers = ConfigFileApplicationContextInitializer.class)
public class PojoTest {
    @Autowired
    private Pojo myPojo;

    @Test
    public void testValue() {
        Assert.assertEquals(myPojo.getName(), "Arthur Accroc");
    }
}
```
and a ```application-dev.yml```:
```yaml 
my:
    pojo:
        name: Arthur Accroc
```

**Obtained**: ```PojoConfiguration.name``` has the value ```${my.pojo.name}```
**Expected**: ```PojoConfiguration.name``` has the value defined in the ```application-dev.yml```

You can reproduce the issue with the demo.tar.gz in attachment.

I've tested with SpringBoot version 1.2.7.RELEASE and 1.3.5.RELEASE.

It looks like other people have this issue ([here](http://stackoverflow.com/questions/33815563/using-configfileapplicationcontextinitializer-does-not-resolve-default-values-fo))

Thanks in advance,

Cédric.

[demo.tar.gz](https://github.com/spring-projects/spring-boot/files/300970/demo.tar.gz)

**Comment by wilkinsona** [comment]
There's no `PropertySourcesPlaceholderConfigurer` in your test configuration so the placeholder remains unresolved. You need to add some configuration that publishes one as a bean. If you use `@SpringApplicationConfiguration` then one will typically be auto-configured for you.

We should improve the docs.

**Comment by ctranxuan** [comment]
Thanks for the response! 
Indeed a note in the doc is a great idea. Thanks!
