### ISSUE TITLE
OracleDataSource created by DataSourceBuilder

### ISSUE THREAD

**Issue by cichockimc** [spring-projects/spring-boot#6124]
Spring boot version: 1.2.3.RELEASE
Language: Groovy, 2.4.3
Oracle driver: ojdbc 14 

When an _Oracle_ datasource is created it seems to be missing the username. 
```
OracleConnectionPoolDataSource oracleDataSource  = DataSourceBuilder
      .create()
      .type(OracleConnectionPoolDataSource)
      .driverClassName('oracle.jdbc.OracleDriver')
      .url('jdbc:oracle:thin:@localhost:1521:xe')
      .username('repository')
      .password('********')
      .build()


```
Root cause of that is that _calculateMatches_ method _BeanPropertyMatches_ class is unable to link 'user' (which is expected by OracleDataSource) with 'username' which is provided by DataSourceBuilder. 

Simplest workaround:

```
private DataSource createNewDataSource(DatasourceConnectionDetails details) {
    OracleConnectionPoolDataSource oracleDataSource  = DataSourceBuilder
      .create()
      .type(OracleConnectionPoolDataSource)
      .driverClassName(details.driverClassName)
      .url(details.url)
      .password(details.password)
      .build()
    oracleDataSource.user = 'repository'
    oracleDataSource
  }
```

**Comment by philwebb** [comment]
Looks similar to #1384 and I think we should just be able to change:

```java
new RelaxedDataBinder(result).withAlias("url", "jdbcUrl").bind(properties);
```

to include `withAlias("username", "user")`.

**Comment by shakuzen** [comment]
Related to #6027

**Comment by philwebb** [comment]
Thanks @shakuzen, looks like we might have closed #6027  too soon.

**Comment by snicoll** [comment]
@philwebb unless I am missing something obvious, I disagree. This issue is about `OracleConnectionPoolDataSource` that has setter methods. If you look at #6027 the user is trying to bind to `oracle.jdbc.pool.OracleDataSource` and that one does not have any setter as far as I can see.

Maybe we should at least drop a note in the documentation about the oracle data source implementations?

**Comment by vpavic** [comment]
@snicoll I don't know if we're looking at the same thing, but [```oracle.jdbc.pool.OracleConnectionPoolDataSource```](https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/pool/OracleConnectionPoolDataSource.html) actually extends the [```oracle.jdbc.pool.OracleDataSource```](https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/pool/OracleDataSource.html) and inherits all the setters from there.

So this issue applies to both.

**Comment by snicoll** [comment]
Wow, what happened back then?! Thanks for pointing that out @vpavic !
