### ISSUE TITLE
Profile specific loader.path property doesn't work

### ISSUE THREAD

**Issue by dkirrane** [spring-projects/spring-boot#6127]
I have two profiles `development` and `production` and I'm running my app with `org.springframework.boot.loader.PropertiesLauncher`

My `application.properties`:
`spring.main.banner_mode=off`

My `application-development.properties`:
`loader.path=lib,target/shared`

My `application-production.properties`:
`loader.path=lib,/opt/lib/shared/`

Running:
 `java -jar -Dspring.profiles.active=development target\my-app-1.0-SNAPSHOT.jar`
  java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

slf4j is an external shared jar provided by `loader.path`

spring-boot version: `1.3.5.RELEASE`

NOTE: if I copy `loader.path=lib,target/lib-provided` to `application.properties` it works

**Comment by philwebb** [comment]
Unfortunately `loader.path` cannot be used with profile specific `application.properties`. The reason for this is that the `PropertiesLauncher` needs to configure the classpath before the application starts (and the profile specific logic gets applied).

I'd generally recommend running `development` and `production` with the same classpath anyway if at all possible.
