### ISSUE TITLE
spring-boot-maven-plugin does not act transitively when excluding dependency

### ISSUE THREAD

**Issue by dkirrane** [spring-projects/spring-boot#6139]
Using Spring-boot `1.3.5.RELEASE`

I'm using `org.springframework.boot.loader.PropertiesLauncher` to pick up some dependencies provided by the platform so I don't want them bundled in the jar.
So i'm trying to exclude a single dependency and _all_ of it's transitive dependencies.

1. Marking the dependency as `<scope>provided</scope>` does not exclude it or any of it's transitive dependencies. (But I understand this is by design)

2. Marking the dependency as `<optional>true</optional>` does not exclude it or any of it's transitive dependencies.

3. Using `spring-boot-maven-plugin` configuration to exclude the dependency works but it does _NOT_ exclude any of it's transitive dependencies.
```
                    <excludes>
                        <exclude>
                            <groupId>com.mycompany</groupId>
                            <artifactId>foo</artifactId>
                        </exclude>
                    </excludes>    
```

There doesn't seem to be a `spring-boot-maven-plugin` option to act transitively when excluding??

**Comment by snicoll** [comment]
Duplicates #3602, #3426

**Comment by dkirrane** [comment]
Can this be reopened as an enhancement/feature request. Add an exclude transitive option

**Comment by snicoll** [comment]
I explicitly gave a link to two other duplicates to stress that it's not supported and we don't intend to support it either.

**Comment by Karthik-Rangasamy** [comment]
Wondering why it is not supported?
What is the point of including the transitive dependencies when its parent is not included?

**Comment by Aaaaaaron** [comment]
confused too.
