### ISSUE TITLE
Streamline semantics and operation of @EntityScan

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6142]
`@EntityScan` was introduced to scan for JPA entities to configure the JPA infrastructure easily. That's why it's located in Boot's `orm.jpa` package. However, the semantics of entity is not tied to JPA only and actually the packages registered through it are already used to scan for domain types backed by other stores (e.g. `MongoAutoConfiguration`).

That slight inconsistency has caused related annotations to show up recentely (e.g. `@NodeEntityScan` for Neo4j) which don't seem to be necessary actually. The store infrastructure usually takes a set of classes to work with. The Spring Data repository infrastructure uses the annotations on the entity type to map the repository to the correct store, so that even in situations with multiple stores on the classpath, the setup should work fine.

After some discussion with @mp911de we'd suggest to change the situation to the following:

- Introduce a new annotation (i.e. a copy of the current) `@EntityScan` in a JPA (ideally even ORM) unrelated package. Let that annotation also populate the auto-configuration package as the old one does.
- Deprecate the old annotation in favor of the new one for removal in 1.5
- Let the auto-configuration for the different stores use the registered package, scan those for the annotations specific to the stores entities and hand them to the store infrastructure.
- Remove the specialized annotations previously introduced.

Downstream we can make sure, Spring Data provides the necessary APIs so that we can move the knowledge about which annotations to the store modules entirely so that Boot effectively only has to provide the packages.

**Comment by philwebb** [comment]
> @EntityScan was introduced to scan for JPA entities to configure the JPA infrastructure easily. That's why it's located in Boot's orm.jpa package. However, the semantics of entity is not tied to JPA only and actually the packages registered through it are already used to scan for domain types backed by other stores (e.g. MongoAutoConfiguration).

That's not strictly true. Currently `@EntityScan` is very tied to JPA, It's sole job is to replace `packagesToScan` in the `LocalContainerEntityManagerFactoryBean` with whatever has been configured. It's not used by `MongoAutoConfiguration` and in fact it's not even aware of auto-configuration concepts at all (that's why it's in `spring-boot.jar`).

> That slight inconsistency has caused related annotations to show up recently (e.g. @NodeEntityScan for Neo4j) which don't seem to be necessary actually.

`@NodeEntityScan` does a similar job, but post-processes `org.springframework.boot.neo4j.SessionFactoryProvider` and not `LocalContainerEntityManagerFactoryBean`. I'm not sure why it's not necessary (could you open a new issue for that).

> Introduce a new annotation (i.e. a copy of the current) @EntityScan in a JPA (ideally even ORM) unrelated package. Let that annotation also populate the auto-configuration package as the old one does.

We could try to unify `@EntityScan` and `@NodeEntityScan` but the registrar would then need to be aware of all data types. We could probably use some strategy and check for relevant classes I guess. We can't really populate "the auto-configuration package" because `spring-boot.jar` should not have any awareness of `spring-boot-autoconfigure.jar`.

> Let the auto-configuration for the different stores use the registered package, scan those for the annotations specific to the stores entities and hand them to the store infrastructure.

I think we already have support for this with the `@AutoConfigurationPackage` annotation and the `AutoConfigurationPackages` class. Existing auto-configurations use `AutoConfigurationPackages` to scan from a sensible place. Pretty much all the existing auto-configurations use this technique, with `@EntityScan`, `@EnableJpaRepositories` etc only being used as an escape hatch.

> Downstream we can make sure, Spring Data provides the necessary APIs so that we can move the knowledge about which annotations to the store modules entirely so that Boot effectively only has to provide the packages.

Something similar to `AbstractRepositoryConfigurationSourceSupport.getBasePackages()`?

**Comment by olivergierke** [comment]
Okay, I think I mistakenly assumed `@EntityScan` just to populate auto-configuration packages.

Wouldn't it simplify things if basically added a copy of the way the auto-configuration packages work for domain types and let a new `@EntityScan` populate exactly that so that the store specific auto-configurations could just use those packages to scan for domain types? That should be an approach uniquely applicable to all stores, shouldn't it?

Taking a step back from the implementations details, I think we should broaden whatever becomes the new `@EntityScan` to scan for entities in the more DDD sense (in our case: types persisted by individual stores) and step away from the very JPA centric notion of an entity (which actually is a quite broken one compared to its original definition).

**Comment by snicoll** [comment]
@philwebb if we decide to ditch `@NodeEntityScan` I'd do that before RC1 since it was introduced in a 1.4 milestone....

**Comment by philwebb** [comment]
@snicoll My feeling is that we should leave things as they are for 1.4 and consider this in 1.5.

**Comment by olivergierke** [comment]
Introduce API in 1.4 that we deprecate in 1.5? 🤔 TBCH, 1.4 is kind of opening a can of worms with a lot of store specific annotations (`@DataJpaTest`) that are unprecedented and don't feel very Spring like, more like leaky abstraction. My vote for not making that precedent and then roll things back later.

If time is an issue and the data team can help out in some way, I'd be happy to volunteer.

**Comment by philwebb** [comment]
I don't really see what `@DataJpaTest` has to do with this issue, and I don't consider it any less leaky than `@EnableJpaRepositories`. It's a test-only annotation that indicates you want a test with auto-configuration of JPA. AFAICT the only other store specific annotation we've added is `@NodeEntityScan`.

We should have a chat about a general purpose `@EntityScan` annotation, what it would achieve and if it would make sense in 1.4 (possible with another delay) or 1.5.

**Comment by wilkinsona** [comment]
@olivergierke The whole point of `@DataJpaTest` is to auto-configure just enough of the application to run a test that relies upon Spring Data JPA. If it knew nothing of the different store types then it couldn't achieve that goal as it would have no choice but to auto-configure everything that's Data-related.

An alternative could be a `@DataTest` annotation with a `store` attribute that allows you to control which store types are auto-configured. Perhaps if you don't specify anything then all Data-related auto-configuration would be enabled. That's really just a different way of expressing what we already have, though, and would still require the different store types to leak out.

**Comment by olivergierke** [comment]
> If it knew nothing of the different store types then it couldn't achieve that goal as it would have no choice but to auto-configure everything that's Data-related.

But why is the latter considered a bad thing? If my app uses MongoDB, it would bootstrap that, if it's using JPA then that. Based on the class path, just like the production code does. What's the reason we want to be so explicit about it here?

**Comment by wilkinsona** [comment]
> But why is the latter considered a bad thing? 

The intention of the `@…Test` annotations is to speed things up by auto-configuring just enough to run a particular test. When an application uses multiple store types that falls down if there's no way to express which store(s) the test will use.

**Comment by olivergierke** [comment]
But in the most common case — one persistence technology in the app — this is the case without repeating what you already expressed through your classpath, isn't it? So there's actually no difference at all. In all the other cases I wonder whether it's really a an issue to bootstrap all stores that are used. Did anyone identify this as problem?

In the mixed stores case, what if my test *needs* repositories from either store? Can I still use `@DataJpaTests` or do I need to switch back to `@SpringBootTests`? In case an `@DataMongoDbTests` will ever exist, could I use both of them together?

*If* the app uses multiple persistence technologies, it's highly likely that there will be tests for repositories of all of the stores. So if an `@DataAccessTests` bootstraps multiple stores, that AC will be reused for all of tests that are run and no additional bootstrap is needed. If we bootstrap per store, an additional bootstrap will need to happen. Given that it's a very special case anyway, I wonder how much benefit that very specific optimization has, or if that specialization effort we create ends up being eaten by the test context caching.

Another aspect: The repositories abstract the concrete persistence technology, so it's awkward to then have the client in this case specify the persistence technology in place. If I autowire a repository that's backed by MongoDB into an `@DataJpaTest` that'll fail and force the user to either use a hypothetical `@DataMongoDbTests` or remove the repository. My point is: there's a 1:1 connection between the repository interface and the store used, so all we achieve is basically the user having to repeat herself no matter what repository testing situation she is in. So why would we want to expose the user to a situation, she is forced to give the one and only answer herself?

I wonder if we should be so overly specific here, as on the downside we create an asymmetry — and thus inconsistency — between the stores supported in production code and what and how we support them in the test area. Going forward, do we really want to go ahead and create those additional annotations to re-instantiate that symmetry? I really think we're complicating the matter to solve a problem I am not sure is worth solving at that particular level of granularity?

**Comment by philwebb** [comment]
After some discussion we've decided to look at adding a generic `@EntityScan` annotation. We'll leave the `@DataJpaTest` annotation as it is for now. If we add more data tests in 1.5 we can consider creating a general purpose `@DataTest` annotation if it makes sense.

**Comment by philwebb** [comment]
@olivergierke Could you take a look at 654801083b3e56cb7307324de61b4e2e06936ea9 and let me know if it looks sane from a Spring Data point of view. The scanning for `@org.springframework.data.annotation.Persistent` annotation seems to match what Spring Data does, but I'm not sure I totally understand it.
