### ISSUE TITLE
PropertiesLauncher ignores devtools restart

### ISSUE THREAD

**Issue by tree-chutes** [spring-projects/spring-boot#6152]
Hello! I am trying to accomplish the following: have PropertiesLauncher restart when there is a change in the class folder passed as -Dloader.path=.....

The framework does have the folder in its class path because I can verify its use. I can verify devtools is in  jar->/lib/. 

I have tried automatic restarts and triggered restarts (passing those as -D or in application.properties)

Nothing happens. Is there a limitation on this launcher?

Thanks a lot!

**Comment by tree-chutes** [comment]
I am using 1.3.5, java 1.8, OS X

**Comment by wilkinsona** [comment]
DevTools isn't intended for use with a packaged application. It's designed to be used when you're running your application's main method directly in your IDE.

**Comment by tree-chutes** [comment]
So it will not kick in? I am working on a test automation plugin that runs in the background,hence the packaging. So no chance kick in? Full restart?
