### ISSUE TITLE
SpringApplication.setBeanNameGenerator doesn't work for scanned components

### ISSUE THREAD

**Issue by romainmoreau** [spring-projects/spring-boot#6160]
The bean name generator is first set by Spring Boot here: https://github.com/spring-projects/spring-boot/blob/v1.4.0.M3/spring-boot/src/main/java/org/springframework/boot/BeanDefinitionLoader.java#L96

But, it's overwritten later by Spring here: https://github.com/spring-projects/spring-framework/blob/v4.3.0.RC2/spring-context/src/main/java/org/springframework/context/annotation/ComponentScanAnnotationParser.java#L94

The issue exists with all the following tested versions: 1.2.8, 1.3.5 and 1.4.0 M3.

You can find a reproduction case here: https://github.com/romainmoreau/bean-name-repro

**Comment by philwebb** [comment]
Looks like we don't call `setBeanNameGenerator` on the created `ApplicationContext`.

**Comment by wilkinsona** [comment]
We do call it, but with some weird criteria:

```java
if (this.webEnvironment) {
	if (context instanceof ConfigurableWebApplicationContext) {
		ConfigurableWebApplicationContext configurableContext = (ConfigurableWebApplicationContext) context;
		if (this.beanNameGenerator != null) {
			configurableContext.getBeanFactory().registerSingleton(
							AnnotationConfigUtils.CONFIGURATION_BEAN_NAME_GENERATOR,
					this.beanNameGenerator);
		}
	}
}
```
