### ISSUE TITLE
Incompatible versions of jackson-databind and spring-hateoas in starter-parent 1.4.0.M3 and silent failure

### ISSUE THREAD

**Issue by destan** [spring-projects/spring-boot#6168]
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.0.M3</version>
</parent>

<dependencies>

...

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-ribbon</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-hateoas</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

...

</dependencies>
```

above `pom.xml` brings following libraries:

* com.fasterxml.jackson.core:jackson-databind:2.7.4
* org.springframework.hateoas:spring-hateoas:0.19.0.RELEASE

However when using `@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)` and trying to deserialize a `PagedResources<>` as follows:

```
PagedResources<MyEntity> pr = feignClient.getMyEntities();
```

the content is empty. (just like in #2350) There is no error not even a warning in console.

But if I change my feign client's return type to string and try to parse the json myself like following:

```
String json = feignClient.getMyEntities();
PagedResources<Customer> cu = objectMapper.readValue(json, PagedResources.class);
```

There is an exception:

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase: method <init>(Ljava/lang/Class;)V not found
  at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesDeserializer.<init>(Jackson2HalModule.java:594) ~[spring-hateoas-0.19.0.RELEASE.jar:na]
  at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesDeserializer.<init>(Jackson2HalModule.java:584) ~[spring-hateoas-0.19.0.RELEASE.jar:na]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
```

### Solution

explicitly setting latest version to spring-hateoas solves the problem:

```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-hateoas</artifactId>
            <version>0.20.0.RELEASE</version>
        </dependency>
```

### Problems

I think there are 2 problems:

1. `spring-boot-starter-parent` version 1.4.x should bring `0.20.0` version of `spring-hateoas`.
2. In the former case where the hateoas response's content is empty there should be some feedback in console.

Are those really issues or did I miss something?

**Comment by wilkinsona** [comment]
Duplicates #5759

**Comment by destan** [comment]
@wilkinsona I searched open issues for hateoas but couldn't find the related ones because they were closed, sorry.

anyways don't you think silent failure is a problem as well?

**Comment by wilkinsona** [comment]
Yes, it's a problem, but it's been fixed. It's basically impossible to predict and provide diagnostics for every failure that may be caused by a breaking API change in third-party code so I don't think there's anything more that can be done here.

**Comment by destan** [comment]
I don't think so. Of course it's impossible to predict such failures however in this particular case it feels like an exception is consumed silently instead of re-throwing or at least logging it.

**Comment by wilkinsona** [comment]
If you feel strongly about it perhaps you could spend some time tracking down the cause and then contribute a pull request to the relevant project?

**Comment by destan** [comment]
@wilkinsona you are right however that's all the time I could spent for now on this issue. The rest is up to spring team.

thanks for your time

**Comment by tonghuajianghan** [comment]
it cann't be find.however

**Comment by dombo3** [comment]
bro
