### ISSUE TITLE
@ConfigurationProperties classpath  location with  asterik character support

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-boot#6169]
Hello
Currently, specifying the asterik character in the `classpath` locations doesn't work :
````
@Configuration
public class Config{
    @Bean
    @ConfigurationProperties( locations = "classpath*:pckg/files-*.yml")
    public SomeSettings someSettings(){
        return new SomeSettings ();
    }

}
````
The `ConfigurationPropertiesBindingPostProcessor::loadPropertySources` simply loads the resource as is.
Please support such case.
Thanks

**Comment by wilkinsona** [comment]
Sorry, but the `locations` attribute is deprecated in 1.4 so we won't be enhancing its functionality.

**Comment by t-hong** [comment]
Why don't you support

**Comment by t-hong** [comment]
Are there any solutions to this problem?
