### ISSUE TITLE
MongoClientOptions not being set in MongoProperties

### ISSUE THREAD

**Issue by magiccrafter** [spring-projects/spring-boot#6175]
The following `MongoClientOptions`'s options are not being set in `MongoProperties` when constructing the `MongoClient`:
```
minConnectionsPerHost
maxConnectionIdleTime
maxConnectionLifeTime
heartbeatFrequency
minHeartbeatFrequency
heartbeatConnectTimeout
heartbeatSocketTimeout
localThreshold
requiredReplicaSetName
```

Instead of the overwrites, the default values are being used.

**Comment by snicoll** [comment]
Closing in favour of the PR #6176
