### ISSUE TITLE
Servlet Container Beans (i.e. Filter, Servlet, etc) are instantiated too soon

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#6178]
Spring Boot 1.4.0.M3 (and prior versions) initialize Servlet Filters too eagerly. This can lead to inconsistencies between running tests and integration tests (i.e. https://github.com/spring-projects/spring-data-examples/issues/189). It can also lead to ordering issues when working with AOP (i.e. #2578 behaves differently between test and integration test). 

The problem is cause by:

* [AbstractApplicationContext](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L535) invokes onRefresh
* [EmbeddedWebApplicationContext](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M3/spring-boot/src/main/java/org/springframework/boot/context/embedded/EmbeddedWebApplicationContext.java#L134) implements `onRefresh` by invoking [createEmbeddedServletContainer](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M3/spring-boot/src/main/java/org/springframework/boot/context/embedded/EmbeddedWebApplicationContext.java#L134)
* When using Tomcat, [TomcatEmbeddedServletContainer](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M3/spring-boot/src/main/java/org/springframework/boot/context/embedded/tomcat/TomcatEmbeddedServletContainer.java#L91) will start Tomcat
* This causes all the Servlet Container Beans (i.e. Filter, Servlet, etc) to be instantiated eagerly in [getServletContextInitializerBeans](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M3/spring-boot/src/main/java/org/springframework/boot/context/embedded/EmbeddedWebApplicationContext.java#L241).

This is not ideal because these Beans might depend on a lot of other Beans (i.e. Servlet initializes all of Spring MVC, Filter initializes Spring Security, etc) and cause all sorts of ordering issues due to the eager initialization of the Beans. It should be noted that while `DelegatingFilterProxy` is used, the servlet container initializes the `DelegatingFilterProxy` which in turn initializes the `Filter` that is marked as a Bean.

As it stands [onRefresh](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L535) initializes every Bean rather than "special Beans" (as is intended).

What is expected is that the Servlet Container Beans would be initialized in [finishBeanFactoryInitialization](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L541).

**Comment by philwebb** [comment]
It's unfortunately not possible to call `ServletInitializer` beans in `finishBeanFactoryInitialization` because it's too late at that point. Tomcat throws the following exception:

```
java.lang.IllegalStateException: Servlets cannot be added to context  as the context has been initialised
	at org.apache.catalina.core.ApplicationContext.addServlet(ApplicationContext.java:843) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
```

**Comment by philwebb** [comment]
I've made a couple of changes which when combined with [these updates](https://github.com/philwebb/data-jpa-preautorize-sample/tree/spring-boot-6178) to the sample application appear to fix the problem. I'm not keen to backport this to 1.3, so we'll probably leave it as a 1.4 only fix.
