### ISSUE TITLE
Rework IntegrationJmxConfiguration to use JavaConfig instead of @EnableIntegrationMBeanExport

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#6183]
Currently we have a code:
````java
@EnableIntegrationMBeanExport(defaultDomain = "${spring.jmx.default-domain:}", server = "${spring.jmx.server:mbeanServer}")
protected static class IntegrationJmxConfiguration {
}
````
which doesn't allow to use `RelaxedPropertyResolver` and therefore we can't use the property from ENV like:
```
SPRING_JMX_DEFAULT_DOMAIN=org.foo
```

**Comment by snicoll** [comment]
Closing in favour of the PR #6184 

@artembilan no need to create an issue. PRs and issues are participating at the same level on github.
