### ISSUE TITLE
Add support for Eclipselink

### ISSUE THREAD

**Issue by Alvise88** [spring-projects/spring-boot#6195]
Can Spring Boot supports natively also Eclipselink ?. I'm struggling with hibernate because it doesn't really support composite keys (a.k.a Natural keys). For example if i try queries like these:

```
select count(distinct e) from entity as e --> select count(distinct **id_part1, id_part2**) from entity
select e from entity where e exists (select ee from entity as ee) --> select id_part1, id_part2 from entity where (id_part1, id_part2) exists (select **(**id_part1, id_part2**)** from entity)
```

and many others. Surrogate keys aren't a solution, only a workaround. Also the lack of support by Red-hat, for example issue [https://hibernate.atlassian.net/browse/HHH-1615](group by issue)

``` java
@Data//lombok
@IdClass(EntityPK )
public class Entity {
    @Id
    String id_part1;
    @Id
    String id_part2

  @Data//lombok
  public static class EntityPK {
    @Column
    String id_part1;
    @Column
    String id_part2;
  }
}
```

**Comment by philwebb** [comment]
I'm afraid we don't current have auto-configuration for Eclipselink but it is supported by Spring Data and Spring Framework. It looks like @dsyer has already put together an [example project](https://github.com/dsyer/spring-boot-sample-data-eclipselink) that shows how you can use it.

**Comment by snicoll** [comment]
There is also a starter (whose naming and namespace should change): https://github.com/zalando-stups/booties/tree/master/spring-boot-starter-data-jpa-eclipselink

**Comment by Alvise88** [comment]
I had already found these solutions. I look inside Hibernate sources and nowadays Red-Hat must do a big effort to improve antlr 2.7 parser. I prefer Spring has at least two Jpa implementations. I'll improve the Zalando project, there is opportunity for pull requests on this topic ?

**Comment by jbellmann** [comment]
@snicoll I renamed all the starters created so far in that repository. Sorry for not reading all parts of the documentation ;-)
But wouldn't it better to have the Eclipselink-Starter in the 'spring-boot'-project? It's currently one source file only. Or should we try to improve the starter at the current repository and move it maybe after release of 1.4.0? Maybe you have a lot of work to do to get the final release done.
Let me know what you think.

@Alvise88 Please let me know what you want to have in the starter. [Create some tickets](https://github.com/zalando-stups/booties/issues) if you want.

**Comment by philwebb** [comment]
We can certainly consider adding EclipseLink support, although we most likely wont get to it in 1.4. It probably makes sense for @Alvise88 and @jbellmann to iterate in the https://github.com/zalando-stups/booties/tree/master/data-jpa-eclipselink-spring-boot-starter to see what issues they find.

**Comment by snicoll** [comment]
I agree and there's nothing wrong with having eclipselink support in a third party starter.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
