### ISSUE TITLE
Drop back to Hibernate 5.0.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6198]
After much discussion, we've decided to go with Hibernate 5.0.x as the default version for 1.4, while also providing samples and documentation showing how to use 5.2.x.

**Comment by rakpan** [comment]
This is a very good decision in my opinion..

**Comment by zhanhb** [comment]
It seems hibernate 5.2.0 is a mistake. hibernate entitymanager 5.2.1 is availiable from maven central.
