### ISSUE TITLE
EmbeddedMongoAutoConfiguration implicitly uses spring data mongodb

### ISSUE THREAD

**Issue by julien-may** [spring-projects/spring-boot#6200]
Hi

The class `EmbeddedMongoAutoConfiguration.EmbeddedMongoDependencyConfiguration` is annotated with `@ConditionalOnClass(MongoClient.class)` whereby IMO it should be annotated with `@ConditionalOnClass({MongoClient.class, MongoClientFactoryBean.class})` as the inherited class `MongoClientDependsOnBeanFactoryPostProcessor` is providing the `MongoClientFactoryBean.class` as the factory bean class for the post processing to ensure that `MongoClient` beans depend on the embedded server.

This leads to a runtime error when wanting to use the `EmbeddedMongoAutoConfiguration` without the use of spring data mongo.

When you agree, i can submit a patch for that

**Comment by snicoll** [comment]
Yep, we had the same issue with another auto-configuration in the past. Can you share a PR? We intend to release quite soon....

**Comment by julien-may** [comment]
here you go: https://github.com/spring-projects/spring-boot/pull/6201

**Comment by snicoll** [comment]
Closing in favour of the PR #6201
