### ISSUE TITLE
spring-boot-maven-plugin can't hot refresh while allowing filtering of application.properties

### ISSUE THREAD

**Issue by jericbryledy** [spring-projects/spring-boot#6209]
I've set the maven plugin to allow hot refreshing of resources
```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<addResources>true</addResources>
	</configuration>
</plugin>
```

but as stated in http://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html filtering won't work as a side effect.

It is important to not commit database credentials such as spring.datasource.username and spring.datasource.password in application.properties.

The work around I'm doing now is entering the username and password directly to application.properties and undoing the changes before I commit. There should be a safer way of doing this?

I'm not sure if I'm missing something...

**Comment by snicoll** [comment]
Duplicates #5136
