### ISSUE TITLE
Regression in executable jar startup performance

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6215]
This problem was discovered while investigating #6177 which is looking into the difference between launching a 1.3.x app in the IDE vs an executable war. This issue is to cover a regression in startup performance between a 1.3.x app and a 1.4.0 app when launched as an executable jar or war.

I've used an executable jar to gather some numbers. These numbers are not directly comparable to those in #6177 as this app had Jasper on the classpath this time which slows things down as more work's being done during startup. The time is the JVM running time that's logged once the app's started. Each entry in the table is the average of 10 runs:

Version | JVM running time (seconds)
-----------|----------------------
1.4 (b03d8a5) | 14.725
1.4 (bdb0eb2) | 9.361
1.3.5 (SFW 4.3.0) | 8.3102
1.3.5 | 7.660

Some conclusions:

 - The original fix for #6109 was a performance disaster (first row) but the caching optimisation has improved things quite a bit (second row)
 - With Spring Framework 4.3.0 a 1.3.5 app is ~10% slower to start than with Spring Framework 4.2.6 so, without changes to Spring Framework, it's going to be hard to get 1.4 back to where 1.3.5 is.

**Comment by wilkinsona** [comment]
The fix for #5411 hasn't helped matters. 984000 `JarURLConnection` instances are created so 984000 `FilePermission` instances are also being created. They're only needed when running with a security manager which is atypical. They should be created lazily instead.

**Comment by wilkinsona** [comment]
With lazy creation of the `FilePermission` in place, 1.4 now starts in an average of 8.549 seconds.

**Comment by wilkinsona** [comment]
The changes in 0d207d4 bring the average time down to 8.295 seconds which is near enough the same as 1.3.5 with Spring Framework 4.3.0.

**Comment by philwebb** [comment]
I think that's good enough, we can probably close this one.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/commit/a5cddf79a801344588f4469b102d65f8bb0d8f62 seems to have provided a nice boost. That change combined with the latest Spring Framework 4.3.1 snapshot (no known improvements there, just an unwanted side effect of 1.4 using snapshots at the moment) reduces the average start time to 8.062 seconds.
