### ISSUE TITLE
Update Jackson to 2.7.x in the 1.3.x branch.

### ISSUE THREAD

**Issue by testark** [spring-projects/spring-boot#6218]
I came across this bug in Jackson 2.6 which basically prevents Spring Boot to be hable to handle more than a handful of concurrent requests:

https://github.com/FasterXML/jackson-databind/issues/1275
http://stackoverflow.com/questions/37978110/threads-getting-blocked-in-jacksons-serializercache

TL;DR the only way to fix this is to migrate to Jackson 2.7, but Spring Boot 1.3.5 is stuck with 2.6.x. Is there any possibility that Jackson 2.7 support is added to the 1.3.x branch?

**Comment by wilkinsona** [comment]
No, unfortunately not. We can't move to a new minor version of a dependency in a maintenance release. It's particularly bad in this case as there are a number of breaking API changes in Jackson 2.7 which means that it isn't fully compatible with Spring Framework 4.2.x, i.e. we'd need to move to Spring Framework 4.3.x as well.

Perhaps you could use a custom `AbstractJackson2HttpMessageConverter` subclass that does some of its own caching in `canWrite`? You may also want to raise a [Spring Framework JIRA](https://jira.spring.io/browse/SPR) ticket to see if there's anything that can do done in Spring Framework 4.2.x to work around Jackson's caching deficiencies.

**Comment by jhoeller** [comment]
From a core perspective, we did some fine-tuning for better compatibility with Jackson 2.7 for Spring Framework 4.2.5: https://jira.spring.io/browse/SPR-13853 ... That said, we indeed recommend an upgrade to Spring Framework 4.3 for proper Jackson 2.7/2.8 support.

Is anything preventing a manual override to Jackson 2.7 with Spring Framework 4.2.6 / Boot 1.3.5 here?

**Comment by testark** [comment]
@jhoeller from what @wilkinsona says,

> It's particularly bad in this case as there are a number of breaking API changes in Jackson 2.7 which means that it isn't fully compatible with Spring Framework 4.2.x, i.e. we'd need to move to Spring Framework 4.3.x as well.

**Comment by jhoeller** [comment]
I mean some kind of hard ties in Boot itself. Because from a Spring Framework 4.2.5+ perspective, we keep using old Jackson APIs there but this is fine-tuned to work with Jackson 2.7 as well to a large degree (as of SPR-13853). So as far as I can tell, a manual override to Jackson 2.7.x should work fine.

Why not simply override to Jackson 2.7.5 with Boot 1.3.5 and see how it goes for your purposes?

**Comment by wilkinsona** [comment]
I do not believe that there are any hard ties in Boot itself. We had a few problems when we upgraded to Jackson 2.7 but, IIRC, none of those were in Boot itself.

Judging by the above, I've overstated the problems with the 2.7.x and 4.2.x combination (SPR-13853). @testark I second Jürgen's suggestion of using Boot 1.3.5 and overriding `jackson.version`.
