### ISSUE TITLE
Spring Boot fails to load a <springProperty> value in logback-spring.xml when property is not set in application.properties

### ISSUE THREAD

**Issue by ltsallas** [spring-projects/spring-boot#6219]
Hi, 
 I have a Spring Boot 1.3.5 app and it  fails to load a <springProperty> in logback-spring.xml from a custom.properties file set via a @PropertySource. When the property is set in application.properties, it works as expected.
I realized that when `org.springframework.boot.logging.logback.SpringPropertyAction.getValue(String source) ` method is executed, the environment does not contain the custom.properties source in propertySourceList. This is the reason that it fails to load the value.

**Comment by wilkinsona** [comment]
This is working as designed. The logging system is, by necessity, initialized very early and before any `@PropertySource` annotations have been processed. You should use `application.properties` to configure the property. Alternatively, you could implement your own `EnvironmentPostProcessor` to load the configuration from an alternative location.

**Comment by ltsallas** [comment]
Thanks for the feedback :)
