### ISSUE TITLE
Add control about time conversion of BuildProperties

### ISSUE THREAD

**Issue by carlmoser** [spring-projects/spring-boot#6221]
I like the brand new `BuildProperties` class, but I'm confused about the conversion of the pretty formatted `time` property into a `java.uti.Date` Object. When the `/info` endpoint is invoked, the server now returns a timestamp in milliseconds as the value of `time`. This value doesn't contain any timezone information anymore. The original (ISO 8601 formatted) string value from `META-INF/build-info.properties` is machine and human readable. So I prefer a switch to turn off the automatic conversion in `org.springframework.boot.info.BuildProperties.coerceDate()`.

Maybe there also could be added a feature to configure the timezone which is used for the `time` value in the  `META-INF/build-info.properties` file. Actually the timezone of the build server seems to be used by default.

**Comment by snicoll** [comment]
>When the /info endpoint is invoked, the server now returns a timestamp in milliseconds as the value of time.

It returns whatever you've asked Jackson to do. If you want to return a date in a specific format, just [configure Jackson accordingly](http://wiki.fasterxml.com/JacksonFAQDateHandling). IMO, it is much better than imposing a given date format to everyone.
