### ISSUE TITLE
Remove mentions of /dev/urandom from docs as they are no longer necessary

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6229]
Tomcat has been configured to initialise its session id generator lazily so there should be no need to use /dev/urandom to speed up startup

**Comment by philwebb** [comment]
Although it still could be useful to use `/dev/urandom` speed up generation.

**Comment by wilkinsona** [comment]
The theory is that the startup process will generate sufficient entropy that it's no longer a problem. Given that we haven't seen any complaints with Jetty or Undertow hanging on first request for a session ID, that appears to be the case in practice too.

**Comment by philwebb** [comment]
I missed a bit.
