### ISSUE TITLE
Register Tomcat valves at the engine container level

### ISSUE THREAD

**Issue by qerub** [spring-projects/spring-boot#6231]
In Tomcat, a valve can be active at a {engine, host, context} container level.

Spring Boot allows activation of {`AccessLogValve`, `RemoteIpValve`} through properties and activates them at a context container level.

Given that Spring Boot can only activate a single {`AccessLogValve`, `RemoteIpValve`}, wouldn't it be better to add them at the top of the container hierarchy (i.e. the engine)?

For `RemoteIpValve`, the Tomcat documentation states:

> Normally, this Valve would be used at the Engine level.

For `AccessLogValve`, the Tomcat documentation states:

> Where Tomcat cannot identify the Context that would have handled the request, e.g. in cases where the URL is invalid, Tomcat will look first in the Engine, […] for an AccessLog implementation.

Why bother? Well, I noticed that Spring Web MVC's `/error` action is invoked outside the scope of the `RemoteIpValve` (as configured by default), making my application capture the wrong IP addresses. Moving the `RemoteIpValve` to the engine resolves that issue.

I'd be happy to provide a patch if you think this is a change worth making.

**Comment by philwebb** [comment]
On the surface it sounds sensible, we'll discuss it at our next meeting. If the code isn't too involved a patch would be most welcome, if it's going to eat a lot of your time then it's best to wait until we've talked about it.

**Comment by wilkinsona** [comment]
When a failure occurs Tomcat forwards the request to our error page, `/error`. This is done in `StandardHostValve`. As its name would suggest, this `Valve` is configured on the `Host`.

`RemoteIpValve` follows this basic pattern:

```
Store request's original settings
Update request based on X-Forwarded-* headers
try {
    Call the next valve
} 
finally {
    Restore the request's original state
}
```

When it's operating at the context level, this means that the finally block runs before `StandardHostValve` catches the exception and forwards the request to `/error` so the error controller is called with the request in its original state so it doesn't see the changes that resulted from processing the `X-Forwarded-*` headers.

**Comment by wilkinsona** [comment]
Duplicates #6311
