### ISSUE TITLE
Tomcat context redirect ignores forward headers

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-boot#6232]
This issue is a follow up on #2603. The problem is that a app configured with `server.use-forward-headers: true` and `server.context-path: /context` performs a redirect from `/context` to `/context/` without checking the forward headers (`X-Forwarded-Port`, `X-Forwarded-Proto`, ...) thus redirecting to a non-reachable location. This is caused by the request not being processed by `RemoteIpValve`.

**Comment by sfussenegger** [comment]
added test case:

```bash
#!/bin/bash

# HTTP/1.1 302 Found
# Actual:    Location: https://127.0.0.1/context/
curl -si \
 -H "X-Forwarded-Proto: https" \
 -H "X-Forwarded-Port: 443" \
127.0.0.1:8080/context/redirect

# HTTP/1.1 302 Found
# Actual:    Location: http://127.0.0.1:8080/context/
# Expected:  Location: https://127.0.0.1/context/
curl -si \
 -H "X-Forwarded-Proto: https" \
 -H "X-Forwarded-Port: 443" \
 127.0.0.1:8080/context
```

[spring-boot-6232.zip](https://github.com/spring-projects/spring-boot/files/334501/spring-boot-6232.zip)

**Comment by wilkinsona** [comment]
As far as I can tell, this is Tomcat's standard behaviour. Tomcat's `Mapper` instigates the redirect before any Valves are processed. I'm not sure that we can work around it in Spring Boot and, even if we could, I'm not sure that we should as we try to stick as closely as possible to the default behaviour.

One workaround, that won't be generally applicable, is to use a context customiser and calling `context.setMapperContextRootRedirectEnabled(false)` which will prevent the redirect from happening. Another would be to switch to Jetty or Undertow as neither of them seem to be affected. And another would be to rewrite the response in the proxy to correct the `Location` header.

@markt-asf What's your take on this from a Tomcat perspective?

**Comment by wilkinsona** [comment]
Undertow's support is only partial. It gets the protocol correct, but doesn't change the port. Jetty gets the correct protocol and port in the redirect.

**Comment by markt-asf** [comment]
Tomcat is unlikely to change the current behaviour. 'mapperContextRootRedirectEnabled' is what first came to mind as I read this. If there is only one reverse proxy in front of Tomcat, you can also configure this via the Connector.

**Comment by wilkinsona** [comment]
Thanks, @markt-asf.


Here's an example of programatically configuring the `Connector` in Boot:

```java
@Bean
public EmbeddedServletContainerCustomizer proxyCustomizer() {
	return (container) -> {
		((TomcatEmbeddedServletContainerFactory)container).addConnectorCustomizers((connector) -> {
			connector.setScheme("https");
			connector.setProxyName("example.com");
			connector.setProxyPort(443);
		});
	};
}
```

**Comment by wilkinsona** [comment]
I've opened [UNDERTOW-756](https://issues.jboss.org/browse/UNDERTOW-756) for Undertow's inconsistent handling of the three headers. We also have #6248 which will make it easy to switch of Tomcat's root context redirect.

I don't think there's anything more that we can/should do in Boot. Hopefully the Undertow issue will be fixed bringing its functionality to the level of Jetty's. Sadly, it looks like Tomcat isn't going to change so it'll be necessary to disable the root context redirect.
