### ISSUE TITLE
Expose CRaSH web connector

### ISSUE THREAD

**Issue by ezraroi** [spring-projects/spring-boot#6233]
It will be very nice to enable in configuration the CRaSH web UI in the same way as H2 Console.

**Comment by snicoll** [comment]
You mean [the web connector](http://www.crashub.org/1.3/reference.html#_web_connector)?

**Comment by ezraroi** [comment]
yes

**Comment by agebhar1** [comment]
@wilkinsona due to #7006 - is it obsolete?

**Comment by snicoll** [comment]
@agebhar1 yes, good catch.

**Comment by snicoll** [comment]
Support for the remote shell is going to be removed in 2.0 (#7006).

**Comment by wilkinsona** [comment]
Thanks @agebhar1.

**Comment by agebhar1** [comment]
Don't mention it.
