### ISSUE TITLE
List type configuration property bug

### ISSUE THREAD

**Issue by mkopylec** [spring-projects/spring-boot#6235]
I have a configuration class:
```java
@ConfigurationProperties("sample")
public class SampleProperties {

    private List<String> types = new ArrayList<>(asList("type1", "type2"));

    public List<String> getTypes() {
        return types;
    }

    public void setTypes(List<String> types) {
        this.types = types;
    }
}
```
and _application.yml_ file (note the notation with `-`):
```yaml
sample.types: 
    - type3
```
Now I expect that `sampleProperties.getTypes()` will return `["type3"]` but what it really returns is `["type3", "type2"]`. Just the first element of the list has been overriden.
I suppose that `List` config properties are not overridable like the other ones (String, primitives, etc.)
In my opinion it is a bug.
I'm using **1.3.5.RELEASE** version.

Different things happen in the list of `Class`es:

```java
@ConfigurationProperties("sample")
public class SampleProperties {

    private List<Class> types = new ArrayList<>(asList(IOException.class, TimeoutException.class));

    public List<Class> getTypes() {
        return types;
    }

    public void setTypes(List<Class> types) {
        this.types = types;
    }
}
```
and _application.yml_ file (note the notation without `-`):
```yaml
sample.types: java.lang.RuntimeException, java.lang.Exception
```
Now I expect `types` to be `[java.lang.RuntimeException, java.lang.Exception]` but they are `[IOException.class, TimeoutException.class]`

**Comment by wilkinsona** [comment]
I can't reproduce the behaviour you have described with either 1.3.5.RELEASE or the latest 1.4 snapshots. Can you please provide a complete sample that reproduces the problem?

**Comment by mkopylec** [comment]
I cannot reproduce it either in new sample project, but it occurs in our production code at work. I'll try figure out what causes this strange behaviour and then let you know.

**Comment by mkopylec** [comment]
I have updated my first post, if you still cannot reproduce the problem I can provide some sample project.

**Comment by snicoll** [comment]
Please don't create meta-issue as it makes it very hard to track what we're talking about. The "other" issue should go in a separate issue.

**Comment by mkopylec** [comment]
Do you mean the second part of my first comment should be another issue?

**Comment by snicoll** [comment]
> Different things happen when in the list of Classes:

The type and the configuration sample is completely different. I fail to see how that one would fail by the way so when you create another issue, make sure to attach a sample please.

**Comment by wilkinsona** [comment]
The first part of the problem is working as designed. When you use:

```
sample.types: 
    - type3
```

You are configuring the first element in the list to be `type3`. The equivalent properties-based configuration would be:

```
sample.types[0] = type3
```

If you want to replace the contents of the whole list you should use the following:

```
sample.types: type3
```

I can't reproduce the second problem and, as @snicoll has already said, it should really be raised separately. If you'd like us to spend any more time investigating please open a new issue and take the time to provide a small sample that reproduces the issue.

**Comment by mkopylec** [comment]
Thanks, for the explanation.
Ok, I will create a separate issue and provide a sample project.
