### ISSUE TITLE
spring-boot-1.4.0-RC1 release date?

### ISSUE THREAD

**Issue by connollyst** [spring-projects/spring-boot#6236]
Hi there,

Sorry in advance for posting a general question here, but it is too vague for SO. It really belongs in a chat or email but I don't know which.

That said, just wanted to find out when [Spring Boot 1.4.0 RC1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-RC1-Release-Notes) is slated for release?

I'm currently jumping through some hoops to use the latest MongoDB driver with Spring Boot and am super excited to see 1.4.0 RC1 takes care of this. Is it days/weeks/months out?

Thanks & sorry again!

-Sean

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-boot/milestones

**Comment by connollyst** [comment]
Excellent, I didn't know about that page. Thanks Spencer!

**Comment by snicoll** [comment]
@connollyst you can ping [us on twitter](https://twitter.com/springboot) for "vague" questions and if you want to chat, we're [on gitter](https://gitter.im/spring-projects/spring-boot)
