### ISSUE TITLE
Update Javassist

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6242]
Maybe this just needs to wait until the next major version, but we just ran into this bug using Java 8 `Predicate.isEqual` http://stackoverflow.com/a/37217871/206466, and updating to javassist 3.20.0-GA fixed the issue. If it doesn't cause issues perhaps the version could be bumped in the next BOM dot release for platform 2.0.x

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/2953
