### ISSUE TITLE
Spring-boot-maven-plugin - run/start - Possibility to set working directory

### ISSUE THREAD

**Issue by rmemoria** [spring-projects/spring-boot#6243]
I found it quite useful in integration tests. The application, by default, consider the working directory as the place to generate and read external resources (the application.properties file, for example).

During test executions, these resources are located in target/test folder.

But within spring-boot-maven-plugin I didn't figure out  a way to set the working directory the application will start on. So the application always starts in the project root directory.

It would be nice if I have a way to set the working directory in maven configuration.

**Comment by snicoll** [comment]
I like that. You are aware it will only work if you enable forking, right? (that's not the default).

**Comment by rmemoria** [comment]
Yes... Probably create a new property in <configurations> called <workingDirectory>, and if this property is set, spring-boot-plugin would automatically fork the process.

**Comment by lithium147** [comment]
+1

**Comment by snicoll** [comment]
Closing in favour of PR #6645
