### ISSUE TITLE
Spring boot 1.3.5 ignores spring.data.rest.base-uri property

### ISSUE THREAD

**Issue by dzmitryviarzhbitski** [spring-projects/spring-boot#6250]
Hi, all. 
Seems like spring boot  1.3.5  ignores  spring.data.rest.base-uri property. 

I downloaded example from https://spring.io/guides/gs/accessing-data-rest/. This example has PersonRepository rest resource. I  created  application.properties and added following entries:

server.port=8888
server.contextPath=/test
spring.data.rest.base-uri=/admin/api

As a result I can access resource using **http://localhost:8888/test/people** 
**spring.data.rest.base-uri=/admin/api was ignored**

I am using spring-boot 1.3.5.RELEASE
If I downgrade to 1.2.5.RELEASE I can access resource by correct http://localhost:8888/test/admin/api/people url. 
Seems like something is broken in 1.3.5.RELEASE.  

My example : https://github.com/dzmitryviarzhbitski/spring-data-ignore-application-properties.git

Could you address this issue or provide a workaround?

Thanks, Dzmitry.

**Comment by wilkinsona** [comment]
The underlying property in Spring Data REST changed name. You should configure  `spring.data.rest.base-path`
