### ISSUE TITLE
Upgrade to Freemarker 2.3.24-incubating

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6270]
The `-incubating` suffix is purely because the project is undergoing ASF incubation. From the [Freemarker website](http://freemarker.org/freemarkerdownload.html):

> This is a stable, final release. The "incubating" suffix is required by the Apache Software Foundation until the project becomes a fully accepted (graduated) Apache project.

**Comment by andrei-ivanov** [comment]
2.3.25 is already out :)
http://freemarker.org/builds/2.3.25-incubating-voted/documentation/_html/versions_2_3_25.html

**Comment by wilkinsona** [comment]
It looks like they've initiated the release vote but haven't actually done the release yet. For example, it's not in Maven Central: http://central.maven.org/maven2/org/freemarker/freemarker/.

**Comment by andrei-ivanov** [comment]
Hmm, didn't notice that, my Nexus managed to find it somewhere :)
