### ISSUE TITLE
Jersey, JAXB and Jackson ignore XmlTransient in 1.4 but honour it in 1.3.5

### ISSUE THREAD

**Issue by jasoncarreira** [spring-projects/spring-boot#6310]
In upgrading from spring-boot 1.3.5 including the spring-boot-starter-jersey it went from working to getting this exception:

    org.glassfish.jersey.server.internal.process.MappableException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion

due to my User > accounts > owner > accounts etc. recursion

In 1.3.5 it honors @XmlTransient but with 1.4.0.SNAPSHOT it doesn't 

According to this: http://wiki.fasterxml.com/JacksonJAXBAnnotations

the jackson-xc library should be added and the JAXB annotation introspector should be registered

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem?

**Comment by jasoncarreira** [comment]
I simplified this a bit too much to get the stack trace, but if you look at the JSON output from calling http://localhost:8080/organizations first with the 1.3.5 then with the 1.4.0 you can see that @XmlTransient is not being honored. Just switch the comments on the spring-boot-version property and parent version in the top-level maven pom.xml. 

Here's some SQL to create sample data:

INSERT INTO `sample`.`organizations` (`id`, `name`) VALUES ('a', 'a');
INSERT INTO `sample`.`organizations` (`id`, `name`, `parent_id`) VALUES ('b', 'b', 'a');
INSERT INTO `sample`.`organizations` (`id`, `name`, `parent_id`) VALUES ('c', 'c', 'a');
INSERT INTO `sample`.`organizations` (`id`, `name`, `parent_id`) VALUES ('d', 'd', 'b');
INSERT INTO `sample`.`organizations` (`id`, `name`, `parent_id`) VALUES ('e', 'e', 'c');

[api-sample.zip](https://github.com/spring-projects/spring-boot/files/345103/api-sample.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. With 1.4, I get this JSON:

```json
[{"mapName":null,"id":"c","organizationId":null,"parentId":"a","parentOrganization":null,"childOrganizations":null,"name":"c"},{"mapName":null,"id":"a","organizationId":null,"parentId":null,"parentOrganization":null,"childOrganizations":null,"name":"a"},{"mapName":null,"id":"b","organizationId":null,"parentId":"a","parentOrganization":null,"childOrganizations":null,"name":"b"},{"mapName":null,"id":"e","organizationId":null,"parentId":"c","parentOrganization":null,"childOrganizations":null,"name":"e"},{"mapName":null,"id":"d","organizationId":null,"parentId":"b","parentOrganization":null,"childOrganizations":null,"name":"d"}]
```

1.3.5 gives me this:

```json
[{"id":"b","parentId":"a","name":"b"},{"id":"d","parentId":"b","name":"d"},{"id":"a","parentId":null,"name":"a"},{"id":"c","parentId":"a","name":"c"},{"id":"e","parentId":"c","name":"e"}]
```

> the jackson-xc library should be added and the JAXB annotation introspector should be registered

What's the basis for this assertion? I don't understand why it would be necessary in 1.4 but not in 1.3.5. Can you please share your reasoning?

**Comment by wilkinsona** [comment]
Here's a significantly simpler application that I believe reproduces the problem:

```java
package com.example;

import java.util.Arrays;
import java.util.Collection;
import java.util.Set;
import java.util.UUID;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.glassfish.jersey.server.ResourceConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

@SpringBootApplication
public class Gh6310Application extends ResourceConfig {

	public Gh6310Application() {
		register(OrganizationService.class);
	}

	@Component
	@Path("/organizations")
	@Produces("application/json")
	@Consumes("application/json")
	public static class OrganizationService {

		@GET
		public Collection<Organization> getAll() {
			return Arrays.asList(new Organization());
		}

	}

	@XmlRootElement
	@XmlAccessorType(XmlAccessType.FIELD)
	static class Organization {

		public static final String MAP_NAME = "organizations";

		private String id = UUID.randomUUID().toString();

		@XmlTransient
		private String organizationId;

		private String parentId;

		@XmlTransient
		private transient Organization parentOrganization;

		@XmlTransient
		private transient Set<Organization> childOrganizations;

		private String name;

		public String getId() {
			return id;
		}

		public String getOrganizationId() {
			return organizationId;
		}

		public String getName() {
			return name;
		}

		public String getParentId() {
			return parentId;
		}

		public Organization getParentOrganization() {
			return parentOrganization;
		}

		public Set<Organization> getChildOrganizations() {
			return childOrganizations;
		}

	}

	public static void main(String[] args) {
		SpringApplication.run(Gh6310Application.class, args);
	}

}
```

1.4 output:

```json
[{"id":"5997d796-4947-4528-a5ba-e867861ac9ec","organizationId":null,"parentId":null,"parentOrganization":null,"childOrganizations":null,"name":null}]
```

1.3 output:

```json
[{"id":"ade141ea-19f4-433b-bdfa-3c627f17937b","parentId":null,"name":null}]
```

**Comment by wilkinsona** [comment]
This is a regression caused by https://github.com/spring-projects/spring-boot/commit/5776d6a8d71feb2cdfd706262f8eb3c8e0a766a6 (see #4131) which results in Jersey being configured with an `ObjectMapper` that ignores JAXB annotations.

**Comment by jasoncarreira** [comment]
Cool, thanks! I just looked for why Jersey wouldn't honor JAXB annotations and that was what came up. As long as it produces the same as 1.3.5 I'll be happy.
