### ISSUE TITLE
Health Indicator sample missing import statement

### ISSUE THREAD

**Issue by jbayer** [spring-projects/spring-boot#6312]
The code example in [45.6.2 Writing custom HealthIndicators](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_writing_custom_healthindicators) is missing an import for Health on the spring boot documentation.

the full import list should look like:

```
import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthIndicator;
import org.springframework.stereotype.Component;
```

**Comment by philwebb** [comment]
Thanks!
