### ISSUE TITLE
Use runnable code to generate documentation samples

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6313]
We should look at using running sample code imported into our `.adoc` files to prevent issues like #6312. Spring Security has done this already.

**Comment by snicoll** [comment]
That and actually testing them would be nice to ensure backward compatibility.

**Comment by wilkinsona** [comment]
I've done it in REST Docs too. It's not too arduous.

**Comment by wilkinsona** [comment]
I've made a (tiny) start on this. See in ccaa19d.

**Comment by philwebb** [comment]
Marking this one as complete but we might need to do the same with Gradle/Maven docs.
