### ISSUE TITLE
Investigate performing "proxying" when classes are loaded, rather than relying on CGLib

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6317]
When an application is running as an executable jar or war, we have control over its ClassLoader. This would allow us to transform classes when they're loaded rather than subsequently relying on the creation of CGLib proxies. This would reduce the number of classes that are loaded (CGLib proxies load both the original class and the proxy) and would, presumably, perform better. A considerable downside would be that an executable archive would drive a different code path to an IDE, mvn spring-boot:run, etc.

**Comment by philwebb** [comment]
I think we'd rather look at doing this at compile time.
