### ISSUE TITLE
Confusing resource filtering

### ISSUE THREAD

**Issue by ufoscout** [spring-projects/spring-boot#6322]
By default spring-boot enables filtering for the application properties in the spring-boot-starter-parent pom.xml file:

```
		<resources>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/application.yml</include>
					<include>**/application.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<excludes>
					<exclude>**/application.yml</exclude>
					<exclude>**/application.properties</exclude>
				</excludes>
			</resource>
		</resources>
```

However, application properties specific of a spring profile are not filtered.
So, if you have the following two files in src/main/resources:
- application.yml
- application-MY_PROFILE.yml

the first file is filtered but the second one is not.
This behaviour is confusing and error prone; I expected all the files to be filtered or not filtered in block.

**Comment by wilkinsona** [comment]
We agree and have changed this in 1.4. See #4856.
