### ISSUE TITLE
STS generated spring starter project loads deprecated SpringBootServletInitializer class 

### ISSUE THREAD

**Issue by rajadileepkolli** [spring-projects/spring-boot#6327]
I have generated a new spring starter project and I want to try spring boot 1.4.0.RC1 and after selecting all necessary modules a project was generated but it contains deprecated SpringBootServletInitializer class(Due to changes in 1.4.0), I feel spring generated base project shouldn't contain deprecated classes, this cause user to search and fix which is not the intended purpose of spring starter project.

**Comment by wilkinsona** [comment]
Thanks for raising this, but it needs to be fixed in Spring Initializr rather than in Spring Boot. I've opened https://github.com/spring-io/initializr/issues/243.
