### ISSUE TITLE
OkHttp 3.3.1 library

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#6330]
It would be nice having **OkHttp** library to Spring Boot dependencies.

```
<dependency>
	<groupId>com.squareup.okhttp3</groupId>
	<artifactId>okhttp</artifactId>
	<version>${okhttp.version}</version>
</dependency>
```

**Comment by wilkinsona** [comment]
Spring Boot only provides dependency management for libraries that it depends upon or for which we provide auto-configuration. OkHttp doesn't fall into either category. On the other hand, the [IO Platform](http://platform.spring.io/platform/) provides dependency management for a broader set of dependencies, including OkHttp. 2.0 provides dependency management for OkHttp 2 and the forthcoming Athens release (formerly 2.1) adds OkHttp 3.
