### ISSUE TITLE
Proxy property for RestTemplate object

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#6331]
It would be nice having a property to inform what is the **proxy / port / nonproxyhosts** when we get the default **RestTemplate** object created by Spring Boot.

Nowadays we only can set proxy for other resources.

**Comment by snicoll** [comment]
See also #6332

**Comment by ofbizbrazil** [comment]
Hi @snicoll, I guess this other post is more focused on Jest. Cause RestTemplate can receive many client request factories as HttpClient, OkHttp and each one of these  should be able to find out the proxy properties set in Spring Boot. How is nowadays RestTemplate being created?

**Comment by wilkinsona** [comment]
I'm confused by this issue. Spring Boot doesn't create auto-configure a `RestTemplate` bean. @ofbizbrazil Are you using Spring Cloud? It provides a `RestTemplate` bean at one point, although I believe it's stopped doing so now (@spencergibb?).

FYI, 1.4 has introduced `RestTemplateBuilder` that can be used to create a `RestTemplate` and can be fine-tuned using one or more `RestTemplateCustomizer` beans.

**Comment by ofbizbrazil** [comment]
Yes,  that's true I am using Spring Cloud Eureka. If I create onother RestTemplate in my project I get ambiguous bean. Is there any way to set a proxy for the default bean?

**Comment by wilkinsona** [comment]
@ofbizbrazil I don't know. You'd have to ask the Spring cloud team.

**Comment by wilkinsona** [comment]
We're going to add some documentation showing how to do this with a `RestTemplateCustomizer`

**Comment by ofbizbrazil** [comment]
@wilkinsona, Will **RestTemplateCustomizer** manage the default configurations of RestTemplate created by Spring Boot Cloud? Is there a property to set the proxy property too?

**Comment by wilkinsona** [comment]
Once again, that's really a Spring Cloud question. AFAIK, they've removed their auto-configuration of a `RestTemplate` bean.

We have no plans to add any properties for proxy configuration at the moment as there's a huge amount of variety in the configuration that's possible across all the different `ClientHttpRequestFactory` implementations in Spring Framework.

**Comment by spencergibb** [comment]
@wilkinsona is correct, in Brixton we no longer create `RestTemplate` beans.

**Comment by ofbizbrazil** [comment]
Right, tks everybody!
