### ISSUE TITLE
Downgrade Maven Compiler to work around issue MCOMPILER-271

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6334]
https://issues.apache.org/jira/browse/MCOMPILER-271

**Comment by snicoll** [comment]
@wilkinsona, @philwebb fixed this in f26bdd3 but I thought we said a _real_ revert (back to 3.1). Thoughts?

**Comment by philwebb** [comment]
They have update MCOMPILER-271 to indicate it's a bug. Hopefully we'll get an update in the future that fixes it.

**Comment by philwebb** [comment]
For context reverting down to 3.1 might be required due to [MCOMPILER-240](https://issues.apache.org/jira/browse/MCOMPILER-240)
