### ISSUE TITLE
Maven resource filtering not working

### ISSUE THREAD

**Issue by farrukhmpk** [spring-projects/spring-boot#6336]
Bug report

When building using Maven 3.1.1 on JDK 7 and JDK 8, Spring boot starter parent 1.3.6.RELEASE and 1.3.8.RELEASE, resource filtering does not work.
The issue was not present upto version 1.2.8.RELEASE.
Due to this issue, had to downgrade spring-boot-starter-parent version from 1.3.6.RELEASE to 1.2.8.RELEASE

Selected pom.xml
---------------------------------
<code>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.6.RELEASE</version>
	</parent>
	<packaging>war</packaging>
	<build>
		<finalName>${project.artifactId}</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<skipTests>${test.skip}</skipTests>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j</artifactId>
		</dependency>

		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>
	<properties>
		<test.skip>true</test.skip>
		<application.debug>true</application.debug>
		<java.version>1.8</java.version>
	</properties>
</code>

src/main/resources/application.properties
-----------------
<code>
application.debug = ${application.debug}
</code>

**Comment by snicoll** [comment]
Please read the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering) when upgrading.
