### ISSUE TITLE
@EntityScan value attribute not evaluated anymore

### ISSUE THREAD

**Issue by gbauer** [spring-projects/spring-boot#6337]
Hello,

When upgrading to Spring Boot 1.4.0.RC1 from MS3, the value attribute of the org.springframework.boot.autoconfigure.domain.EntityScan annotation is not evaluated as expected.

This results in an exception:
```java
@Configuration
@EntityScan(value = "my.base.entity.package")
public class PersistenceConfiguration {
  //...
}
```
However, this works:
```java
@Configuration
@EntityScan(basePackages = "my.base.entity.package")
public class PersistenceConfiguration {
  //...
}
```

Exception cause is:
```
Caused by: java.lang.IllegalArgumentException: Not a managed type: class my.base.entity.package.MyEntity
	at org.hibernate.jpa.internal.metamodel.MetamodelImpl.managedType(MetamodelImpl.java:210) ~[hibernate-entitymanager-5.0.9.Final.jar:5.0.9.Final]
	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:68) ~[spring-data-jpa-1.10.2.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:67) ~[spring-data-jpa-1.10.2.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:152) ~[spring-data-jpa-1.10.2.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:99) ~[spring-data-jpa-1.10.2.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:81) ~[spring-data-jpa-1.10.2.RELEASE.jar:na]
```

From a quick debugging session, it seems to me that the evaluation of the value attribute is missing in org.springframework.boot.autoconfigure.domain.EntityScanPackages.Registrar#getPackagesToScan

**Comment by snicoll** [comment]
@gbauer it isn't as there is an `@AliasFor` that is handled. There is also a [test that explicitly validates that it works](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/domain/EntityScanPackagesTests.java#L106-L112). Could you please double check or share a project that reproduces the issue?

**Comment by gbauer** [comment]
@snicoll I created a test project and pushed it to https://github.com/gbauer/jpa-test. I could reproduce the error both with `gradle test` as well as with running the application (though the exception is different).

The package structure reflects the packaging from the real-world project I'm working on somewhat. A colleague of mine could reproduce the problem on a different environment as well.

**Comment by snicoll** [comment]
@sbrannen is there something we need to be aware of regarding the support of `@AliasFor` [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/domain/EntityScanPackages.java#L156-L160). We have tests that validate `value` and `basePackages` produce the expected result but this sample project exhibits a different behaviour.

I can see the map contains something for `value` and when that `basePackages` array is empty (that's not the case in the tests).

**Comment by snicoll** [comment]
See #5187

**Comment by wilkinsona** [comment]
It appears to be a difference in behaviour between `StandardAnnotationMetadata` and `AnnotationMetadataReadingVisitor`. The former appears to honour `@AliasFor` whereas the latter does not.

**Comment by snicoll** [comment]
That helps, thanks. I've created https://jira.spring.io/browse/SPR-14437

**Comment by philwebb** [comment]
I have a feeling that SPR-14437 might be a known limitation.

**Comment by sbrannen** [comment]
There are certainly (countless) situations where `@AliasFor` is _not_ honored when using ASM.

This may well be one of those cases.

Out of curiosity (since I haven't cloned Boot 1.4 and tried it myself), what happens if you invoke `getAliasedStringArray()` instead of `getStringArray()` on the `AnnotationAttributes`?

**Comment by sbrannen** [comment]
> I can see the map contains something for `value` and then that `basePackages` array is empty (that's not the case in the tests).

That sounds like the `AnnotationAttributes` was constructed straight from a map instead of from a _synthesized_ annotation, which leads me to believe that my previous tip regarding `getAliasedStringArray()` might solve your problem.

**Comment by snicoll** [comment]
It does, thanks. Upgrading our codebase to that where it makes sense.

**Comment by snicoll** [comment]
@gbauer your sample works again with `1.4.0.BUILD-SNAPSHOT`. Could you please give that a try in a couple of hours once an updated snapshot will be available? Thanks!

**Comment by sbrannen** [comment]
@snicoll,

> It does, thanks. Upgrading our codebase to that where it makes sense.

Great! I'm glad that solved your issue. 👍

**Comment by gbauer** [comment]
@snicoll Thanks for fixing this so quick. I'll test it on Monday on the real-world project.

**Comment by philwebb** [comment]
Reopening given the latest Spring Framework changes:

> The latest 4.3.2 snapshots contain a revision of ASM-based annotation handling, with implicit alias processing for loadable annotation types

**Comment by bojan-milojkovic** [comment]
If you copy-pasted persistence configuration from another project, you must set the entity scan in EntityManagerFactory manually : 

@Bean
public EntityManagerFactory entityManagerFactory() throws PropertyVetoException {
    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setPackagesToScan("**misspelled.package.path.to.entities**");
    .....
}
