### ISSUE TITLE
Spring Security Test 4.1.0 changes the order of `WithSecurityContextTestExecutionListener`

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [spring-projects/spring-boot#6338]
I updated an app I develop to Spring Boot 1.4.0.RC1.

Since the update to Spring Security Test 4.1.0 the order of `WithSecurityContextTestExecutionListener` is now implemented with the `Ordered` interface instead of `@Order`, see https://github.com/spring-projects/spring-security/issues/2933.

I understand the order did not work as intended before this bugfix. But now that it is evaluated the behaviour of some of my tests changes so they break. `SqlScriptsTestExecutionListener` has a priority of 5000, so it is executed after the security listener. I load the Spring Security users into the database via `@Sql` and set them on test methods via `@WithUserDetails`, but this is now broken because the SQL files are not evaluated yet (so I get a `UsernameNotFoundException`).

I'm not sure where to report this, I guess this is not a bug or a question. But maybe it helps other people to understand this problem as well. For now I don't have a good migration solution to circumvent this.

**Comment by wilkinsona** [comment]
@FrontierPsychiatrist Thanks for making us aware of the problem. Unfortunately, given that `SqlScriptsTestExecutionListener` is part of Spring Framework and `WithSecurityContextTestExecutionListener` is part of Spring Security I'm not sure that there's anything that we could or should do to address this in Spring Boot.

Given Spring Security's support for using JDBC, I'm a little surprised by the relative ordering of the two listeners that are involved here. Perhaps @rwinch can fill is in on the background and suggest a good solution for you.

**Comment by rwinch** [comment]
Thanks for the report @FrontierPsychiatrist! I'm closing this in favor of https://github.com/spring-projects/spring-security/issues/3962

**Comment by FrontierPsychiatrist** [comment]
@rwinch Thanks a lot!

**Comment by rwinch** [comment]
@FrontierPsychiatrist Not a problem thanks for the timely report! In fact, I'm about to push a fix (as soon as the build passes locally) and then I will be doing a release of Spring Security 4.1.1

**Comment by rwinch** [comment]
@FrontierPsychiatrist Just as an FYI, Spring Security 4.1.1.RELEASE is available in Maven Central and resolves this.

**Comment by FrontierPsychiatrist** [comment]
Can confirm it works now.
