### ISSUE TITLE
Upgrade to Jackson 2.8

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6343]
Jackson 2.8 was [recently released](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8) and we need to consider if we should try to sneak this into Spring Boot 1.4 or leave it for 1.5.

**Comment by jhoeller** [comment]
+1 for trying to sneak it into Boot 1.4 GA. We claim compatibility with Jackson 2.8 in Spring Framework 4.3 (against the RCs originally), and build against Jackson 2.8 GA now ourselves.
