### ISSUE TITLE
Add setConnectTimeout and setReadTimeout methods in RestTemplateBuilder

### ISSUE THREAD

**Issue by yanglifan** [spring-projects/spring-boot#6346]
I noticed that Spring Boot 1.4.0 brought in a great tool - RestTemplateBuilder. It provide lots of methods which help to customize `RestTemplate`. But I hope that `RestTemplateBuilder` could have methods to customize timeout values for `RestTemplate`, like the connect timeout and read timeout. Since these configurations are very helpful to keep the thread invoke `RestTemplate` from being hung up by IO timeout for a long time.

Of course, via `ClientHttpRequestFactory` implementations, these timeouts can be configured. But let `RestTemplateBuilder` has this ability can make this work to be simplified and standardized.

Before Spring Boot 1.4.0, I created my own `RestTemplateBuilder`. It has abilities to configure such as the connect timeout and the read timeout. The usage is like following:

    RestTemplateBuilder.create()
                .withClientKey("myRestTemplate")
                .implementation(HttpClientImplementation.OK_HTTP)
                .clearMessageConverters()
                .setMessageConverter(new MappingJackson2HttpMessageConverter(), MediaType.TEXT_PLAIN)
                .enableAutoQueryParams()
                .connectTimeout(100)
                .readTimeout(200)
                .header(HttpHeaders.USER_AGENT, "MyAgent")
                .build();

Methods `connectTimeout` and `readTimeout` can set timeout for all `ClientHttpRequestFactory` implementations provided by spring-web.

**Comment by philwebb** [comment]
It's a neat idea, especially if we can find a common set of properties that work across all `ClientHttpRequestFactory` implementations. Thanks for the suggestion.

**Comment by yanglifan** [comment]
Though in `ClientHttpRequestFactory` there is no setConnectTimeout and setReadTimeout declaration,  but implementations of `ClientHttpRequestFactory` do have these two methods. So these two properties can be configured via reflection. That is the way my `RestTemplateBuilder` implemented.

So an implementation of `RestTemplateCustomizer` can be created to configure the common properties of `ClientHttpRequestFactory`. The following is the main code:

    Class<? extends ClientHttpRequestFactory> factoryClass = clientHttpRequestFactory.getClass();

        Method setConnectTimeoutMethod = ReflectionUtils.findMethod(factoryClass,
                SET_CONNECT_TIMEOUT_METHOD_NAME, int.class);
        if (setConnectTimeoutMethod != null && connectTimeout != 0) {
            try {
                invokeMethod(setConnectTimeoutMethod, clientHttpRequestFactory, connectTimeout);
            } catch (Exception e) {
                // ClientHttpRequestFactory does not have setConnectTimeout method
                e.printStackTrace();
            }
        }

        Method setReadTimeoutMethod = ReflectionUtils.findMethod(factoryClass,
                SET_READ_TIMEOUT_METHOD, int.class);
        if (setReadTimeoutMethod != null && readTimeout != 0) {
            try {
                invokeMethod(setReadTimeoutMethod, clientHttpRequestFactory, readTimeout);
            } catch (Exception e) {
                // ClientHttpRequestFactory does not have setReadTimeout method
                e.printStackTrace();
            }
        }

The full code is [here](https://github.com/yanglifan/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/web/client/CommonClientHttpRequestFactoryCustomizer.java) in my fork.
