### ISSUE TITLE
Tomcat redirects on localhost instead of full domain name

### ISSUE THREAD

**Issue by jecuendet** [spring-projects/spring-boot#6348]
We have a spring-boot 1.3.5 webapp (tomcat). It's configured on /application/context/

When I call the application with: domain.com/application/context (without slash)
tomcat redirects on /application/context/ (with the slash)
It's done in org.apache.catalina.connector.Response.sendRedirect()
> 
>             String locationUri;
>             // Relative redirects require HTTP/1.1
>             if (getRequest().getCoyoteRequest().getSupportsRelativeRedirects() &&
>                     getContext().getUseRelativeRedirects()) {
>                 locationUri = location;
>             } else {
>                 locationUri = toAbsolute(location);
>             }
>             setStatus(status);
>             setHeader("Location", locationUri);

If getSupportsRelativeRedirects() returns false (which it does by default), then Location is http://loc alhost:<port>/application/context/ (with the slash)
The problem is that localhost is not accessible to my client, it needs to be redirected to https://domain.com/application/context/

My idea is to set StandardContext.setUseRelativeRedirects(true) but there is no way to do it in spring boot (TomcatEmbeddedServletContainerFactory.prepareContext())

How do I change that behaviour?

**Comment by wilkinsona** [comment]
I believe that particular redirect is actually handled much earlier, in Tomcat's `Mapper` class:

```java
if(mappingData.wrapper == null && noServletPath) {
    // The path is empty, redirect to "/"
    mappingData.redirectPath.setChars
        (path.getBuffer(), pathOffset, pathEnd-pathOffset);
    path.setEnd(pathEnd - 1);
    return;
}

This is standard Tomcat behaviour. It's not clear to me why you've opened an issue against Spring Boot. Can you please explain?

**Comment by jecuendet** [comment]
I opened this issue because the solution I wanted to use (StandardContext.getUseRelativeRedirects()) needs to be configured through Spring-Boot
I found the solution: inherit from TomcatEmbeddedServletContainerFactory and call setUseRelativeRedirects(true)

**Comment by wilkinsona** [comment]
Thanks for following up. For future reference, I didn't see the edit that you made to your original post after I'd commented as GitHub doesn't send any notifications for an edit. A separate comment would have avoided that (and made the issue's history a lot clearer).
