### ISSUE TITLE
Possible v.1.4.0 @PropertySource regression?

### ISSUE THREAD

**Issue by Bragolgirith** [spring-projects/spring-boot#6349]
In Spring Boot 1.3 (using .war deployment) I could provide a @PropertySource value outside the classpath but relative to the application root, like this:
```
@SpringBootApplication
@PropertySource(value = {"WEB-INF/conf/application.properties"})
public class MyApplication {
        public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}
```
After updating to v 1.4.0.RC1 that no longer seems to work and the following exception gets thrown:

> Failed to parse configuration class [com.example.MyApplication]; nested exception is java.io.FileNotFoundException: class path resource [WEB-INF/conf/application.properties] cannot be opened because it does not exist

**Comment by wilkinsona** [comment]
Can you please provide a sample that demonstrates the problem?

**Comment by snicoll** [comment]
Looks like there is [also a thread on SO](http://stackoverflow.com/questions/38243212/spring-boot-loading-a-properties-file-from-web-inf-folder)

**Comment by Bragolgirith** [comment]
I've created two minimal demos for the issue:

https://github.com/Bragolgirith/spring-boot-demo-1.3
https://github.com/Bragolgirith/spring-boot-demo-1.4

(Try running the unit tests for both.)

Result is that the `spring-boot-demo-1.4` can't seem to be able to find the 'WEB-INF/application.properties' file and throws an exception.

**Comment by wilkinsona** [comment]
Thanks for the two samples. Interestingly the 1.4 app works fine once it's been packaged, i.e. ` java -jar target/demo-0.0.1-SNAPSHOT.war` works. Running the tests and `mvn spring-boot:run` both fail, however.

**Comment by wilkinsona** [comment]
`mvn spring-boot:run` also fails for 1.3. Here's the status of the two versions:

 | `mvn spring-boot:run` | Tests | `java -jar`
------|------------------------------|---------|-------------
1.3  | :x: | ✅ | ✅ 
1.4  | :x: | :x: | ✅ 

I've opened #6371 for the change in behaviour of the tests.

We can keep this issue to decide what to do about the behaviour of `spring-boot:run` (or launching the main method directly in an IDE).

**Comment by philwebb** [comment]
Issue #6371 is now fixed giving the results:

 | `mvn spring-boot:run` | Tests | `java -jar`
------|------------------------------|---------|-------------
1.3  | :x: | ✅ | ✅ 
1.4  | :x: | ✅ | ✅

**Comment by wilkinsona** [comment]
I had thought that it was being loaded as a servlet context resource, but that's not the case for `java -jar`. In that case it's a class path resource. It's a class path resource because the root of the war is on the class path and the requested location `WEB-INF/application.properties` matches an entry in the war.
