### ISSUE TITLE
spring jar & war places resources alongside the groovy script at the root

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6351]
Assume a script and a `application.yml` in a directory

`spring jar foo.jar myscript.groovy` -> the yml file is at the root of the jar and therefore available in the classpath

`spring war foo.war myscript.groovy` -> the yml file is at the root of the war (instead of in `WEB-INF/classes` and not available in the classpath.

**Comment by wilkinsona** [comment]
Arguably the jar is wrong too. The resources should go in `BOOT-INF/lib` rather than the root.

**Comment by snicoll** [comment]
It works properly for the `spring jar` command. For the `war` we should move it to the classpath, otherwise any file that's present alongside the script is served by http.
