### ISSUE TITLE
Replace security antMatcher calls with mvcMatchers when possible

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6353]
We should replace spring security `antMatcher` calls with the new `mvcMatchers` method.

**Comment by philwebb** [comment]
@rwinch I might need some help with this, I'm not sure how to convert code [like this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/security/oauth2/sso/CustomOAuth2SsoConfigurationTests.java#L111-L112) that uses `HttpSecurity.antMatcher`.

**Comment by philwebb** [comment]
Actually, I don't even understand what the code is trying to do.

```java
			http.antMatcher("/ui/**").authorizeRequests().antMatchers("/ui/test")
					.permitAll().anyRequest().authenticated();
```

seems to be the same as the Javadoc example of what not to do:

> Note that the matchers are considered in order. Therefore, the following is invalid because the first matcher matches every request and will never get to the second mapping:
> `http.authorizeRequests().antMatchers("/**").hasRole("USER").antMatchers("/admin/**").hasRole("ADMIN")` 

/cc @dsyer

**Comment by dsyer** [comment]
Look at the methods that are called. The first snippet has `http.antMatcher("/ui/**")`. The second one does not (so it has an implicit `antMatcher("/**")`).

**Comment by philwebb** [comment]
Some issues, but in progress @ https://github.com/philwebb/spring-boot/tree/gh-6353

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-security/issues/3969

**Comment by philwebb** [comment]
Removing from 1.4 since Spring Security 1.4.2  won't be out. The antPathMatcher calls strip whitespace in URLs anyway so there's no urgency.

**Comment by wilkinsona** [comment]
@philwebb I thought Spring Security 4.1.2 was scheduled for 20 July. Is that no longer the case? /cc @rwinch

**Comment by philwebb** [comment]
@wilkinsona Rob's on vacation and there's another issue that he'd like to address so it's unlikely to happen.

**Comment by wilkinsona** [comment]
There's only a single call to `antMatcher` in master now: https://github.com/spring-projects/spring-boot/blob/389422938136c880b638140c9a79341a68c79148/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/h2/H2ConsoleAutoConfiguration.java#L98-L100

As mentioned by @philwebb above, Spring MVC may not be on the class path so moving to `mvcMatcher` isn't an option. I think we can leave this as-is.

**Comment by philwebb** [comment]
The security simplifications removed the need for this.
