### ISSUE TITLE
Fix package tangle in gradle plugin

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6355]
![screen shot 2016-07-07 at 2 23 50 pm](https://cloud.githubusercontent.com/assets/519772/16670315/89f08116-444e-11e6-861c-15321e1f007e.png)

**Comment by wilkinsona** [comment]
The simplest fix seems to be to move `SpringBootPlugin` into a separate package: https://github.com/wilkinsona/spring-boot/tree/gh-6355
