### ISSUE TITLE
Authenticated health endpoint access also cached

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#6358]
According to the documentation:

46.6 HTTP health endpoint access restrictions
...
Furthermore, **when accessed anonymously**, the response is cached for a configurable period to prevent the endpoint being used in a denial of service attack. The endpoints.health.time-to-live property is used to configure the caching period in milliseconds. It defaults to 1000, i.e. one second.

My experience with version 1.3.6 is that also authenticated access caches the responses, so either the code is wrong or the documentation is not clear enough.

**Comment by snicoll** [comment]
The documentation is wrong, good catch!

**Comment by marcingrzejszczak** [comment]
@wujek-srujek - I love your account name :)

**Comment by wujek-srujek** [comment]
@marcingrzejszczak Thanks, I put a lot of thinking into it ;d
