### ISSUE TITLE
Provide a STOMP starter

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6359]
`spring-boot-starter-websocket` provides what's needed for basic WebSockets and getting started with STOMP. However, if a user wants to use the broker relay (as seems to be recommend for any serious usage of STOMP) they have to add both Reactor's `reactor-net` module and Netty.

**Comment by ugultopu** [comment]
#4522

**Comment by ugultopu** [comment]
It seems like there is no progress on this, right? When I wanted to use a broker relay, I needed to add the following dependencies to my `pom.xml`:

```XML
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-net</artifactId>
</dependency>
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.17.Final</version>
</dependency>
```

**Comment by jeffie9** [comment]
I added this to my pom (spring-boot 2.0.0.RELEASE) :

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-reactor-netty</artifactId>
        </dependency>

```

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
