### ISSUE TITLE
ShutdownEndpoint does not reset the interrupted flag when it catches InterruptedException

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6360]

**Comment by philwebb** [comment]
There are quite a few others:
* `HeapdumpMvcEndpoint`
* `FileWatchingFailureHandler`
* `FileSystemWather.Watcher`
* `DelayedLiveReloadTrigger`
* `TunnerlClient`
* `HttpTunnelServer`
* `RemoteSpringApplication`

I had a great deal of trouble with `HeapdumpMvcEndpoint` recently, when I reset the interrupted flag later tests started to fail. I never really got to the bottom of it.

**Comment by wilkinsona** [comment]
I believe it's because JUnit reuses the same thread across tests and doesn't clear the interrupted flag in between. Any test that's testing interrupt logic needs to make sure that it clears the flag.
