### ISSUE TITLE
A child SpringApplication can cause SpringApplicationAdmin MBean to indicate that the application is ready when it's not

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#6362]
STS boot dash uses the lifecycle JMX admin bean (i.e by passing VM arg -Dspring.application.admin.enabled=true") to determine 

a) when a app is 'READY'.
b) determine server port and managment port.

The problem is this. Sometimes the app passes the 'READY' check, yet aparantly the port(s) are not yet set.

This creates a race condition for STS (See https://www.pivotaltracker.com/story/show/125728671)
because STS waits until the app is 'READY' and then tries to determine the port its running on. But because of the slight delay... this means STS sometimes gets 'unknown' (actually 'null').

I've addressed it on our end by adding a wait loop that polls the port after app enters ready state.

I'm not sure its really a bug, but it seems like one to me because...  I'd assume that 'READY' state for the app means it is fully started and is in fact ready to respond to requests on its port. If so then I would also expect that asking the app what the port is, should already work.

I mean why else is there a 'READY' state if it doesn't actually mean the app is truly 'READY'?

Anyhoo... if you do not think its a real bug or not worth fixing, that is fine. But I thought I'd at least report it and let you decide what to do about it (if anything). 

Further useful info: I'm not sure this affects all versions of boot. I have seen strange test failures in our CI builds that *might* be attributed to this (so also Boot 1.3.x). But I only recently found a reliable way to reproduce and debug (and fix) it with a set of apps that I can only run properly when using Boot 1.4 BUILD-SNAPSHOT. In other words I have only really been able to observe the problem with Boot 1.4.

**Comment by snicoll** [comment]
The flag flips when `ApplicationReadyEvent` is fired and that happens as late as possible. If you experience that the port hasn't been allocated yet when this returns, the only possible reason is that the container starts up asynchronously. 

Looking at the code, I really don't see how that's possible. What container is this? Tomcat has a `checkThatConnectorsHaveStarted` and an log of the allocated port "Tomcat started on port(s):".  All this happens before `refresh` completes.

Maybe @wilkinsona has an idea?

**Comment by wilkinsona** [comment]
Sorry, I don't. No matter which container you use, `refresh` should not complete until the container is started and listening on the configured port(s).

> But I only recently found a reliable way to reproduce and debug (and fix) it with a set of apps that I can only run properly when using Boot 1.4 BUILD-SNAPSHOT

@kdvolder Can you please share one of those apps so that we can investigate?

**Comment by kdvolder** [comment]
These are the apps where I started seeing it quite frequently: 
https://github.com/kdvolder/chatter

> ...  `refresh` should not complete until the container is started and listening on the configured port(s).

That may very well be true. I don't know. But the issue is not whether the app is listening on the port, but whether asking what the port is from the admin bean returns the number of the port rather than 'null'.

Is it possible that the app starts listening first and then makes that port known to the admin bean asyncly?

**Comment by kdvolder** [comment]
> If you experience that the port hasn't been allocated yet ...

Let me be absolutely clear. I do *not* experience that. The port may, or may not be allocated yet. I have no way to tell that. What I experience is that the admin bean tells me 'null' when I ask for the port. Maybe that is subtly different. I.e. it may very well be that the port is already being listened on, but the admin bean doesn't yet know about it.

**Comment by wilkinsona** [comment]
Thanks, @kdvolder. I can reproduce the problem with STS 3.8.0.RELEASE and just the chatter-web-ui app if I try often enough. The problem with this particular app is that the are multiple application contexts involved and the same `SpringApplicationAdminMXBeanRegistrar` is registered with each of them. This can lead to this sequence of events:

1. Child context sends `ApplicationReadyEvent`
2. `ready` is set to `true`
3. STS calls the MBean and is told the app is ready
4. STS attempts to retrieve the port and gets `null`
5. Parent context sends `EmbeddedServletContainerInitializedEvent`
6. Server ports are set in the environment
7. Parent context sends `ApplicationReadyEvent`
8. `ready` is set to `true` again

**Comment by wilkinsona** [comment]
I think the fix is as simple as ignoring events that come from contexts other than the registrar's own:

```diff
diff --git a/spring-boot/src/main/java/org/springframework/boot/admin/SpringApplicationAdminMXBeanRegistrar.java b/spring-boot/src/main/java/org/springframework/boot/admin/SpringApplicationAdminMXBeanRegistrar.java
index 81dbf54..fc11c44 100644
--- a/spring-boot/src/main/java/org/springframework/boot/admin/SpringApplicationAdminMXBeanRegistrar.java
+++ b/spring-boot/src/main/java/org/springframework/boot/admin/SpringApplicationAdminMXBeanRegistrar.java
@@ -80,7 +80,9 @@ public class SpringApplicationAdminMXBeanRegistrar

        @Override
        public void onApplicationEvent(ApplicationReadyEvent event) {
-               this.ready = true;
+               if (this.applicationContext.equals(event.getApplicationContext())) {
+                       this.ready = true;
+               }
        }

        @Override
```

@snicoll Does that seem reasonable to you?

**Comment by snicoll** [comment]
I didn't do that already? Wow, that's bad... +1 to do that.
