### ISSUE TITLE
Enhance WebRequestTraceFilter to allow excluding capture of certain request paths(eg /management)

### ISSUE THREAD

**Issue by lowzj** [spring-projects/spring-boot#6368]
The `WebRequestTraceFilter` captures and stores all requests currently.

Sometimes, I just want to trace the request mapped in my own Controller, and exclude others that I don't care about. Based on this feature, it's easier to integrate more useful features. For a simple example, only captures real user's request, assigns or get a request-id, then calculates response time, and store the trace result.

I currently defined a `TraceRepository` bean, rewrite the `TraceRepository.add` method to exclude certain request paths.  But I think it's better to enhance `WebRequestTraceFilter`. I would propose adding a collection named 'excludedPaths' to `TraceProperties`, and checking against in `WebRequestTraceFilter.doFilterInternal()`

**Comment by wilkinsona** [comment]
If you want to control the paths to which `WebRequestTraceFilter` is applied, you should use a `FilterRegistrationBean`:

```java
	@Bean
	public FilterRegistrationBean webRequestTraceFilterRegistration(
			WebRequestTraceFilter filter) {
		FilterRegistrationBean registration = new FilterRegistrationBean(filter);
		registration.setUrlPatterns(Arrays.asList("/foo", "/bar"));
		return registration;
	}
```

**Comment by lowzj** [comment]
@wilkinsona thanks for your response, it's very useful for me.

**Comment by lowzj** [comment]
@wilkinsona I tried the solution you mentioned, If I want to exclude `/foo` contained in `/*`, I have to enumerate all the other paths that I want to be filtered. It's not a convenient or sufficient solution when I have a lot of paths.

**Comment by wilkinsona** [comment]
Thanks to the changes made for #6309 you can declare your own custom `WebRequestTraceFilter` bean in 1.4. You can subclass `WebRequestTraceFilter` and override `shouldNotFilter` to exclude certain paths.

**Comment by lowzj** [comment]
great, thanks.
