### ISSUE TITLE
Provide dependency management for modules that are new in Jackson 2.8

### ISSUE THREAD

**Issue by Dichotomia** [spring-projects/spring-boot#6369]
New in Jackson 2.8.

 Maven coordinates :

<groupId>com.fasterxml.jackson.datatype</groupId>
 <artifactId>jackson-datatype-jaxrs</artifactId>

Github : 
https://github.com/FasterXML/jackson-jaxrs-providers

**Comment by wilkinsona** [comment]
@Dichotomia Can you expand on what you mean by "support" please? We can easily add dependency management for the new module. Are you looking for more than that?

**Comment by Dichotomia** [comment]
The dependency management is a good first step. It avoids me to add a "jackson.version" maven property.

Secondly, how spring boot register the jackson modules?

**Comment by wilkinsona** [comment]
> Secondly, how does spring boot register the jackson modules? I think it would be a good idea to register this module automatically.

Generally speaking, that's done by Spring Framework's `Jackson2ObjectMapperBuilder`. Spring Boot will also automatically register any `Module` beans with the auto-configured `ObjectMapper` that's built using the aforementioned builder.

We'll use this issue to add dependency management for `com.fasterxml.jackson.jaxrs:jackson-datatype-jaxrs`

**Comment by wilkinsona** [comment]
See also #6343

**Comment by Dichotomia** [comment]
Ok thank you.
