### ISSUE TITLE
Move sample tests to real integration tests

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6370]
This is a follow-up of  #6357 

Lots of samples are in between samples to demonstrate features to newcomers and integration tests. This has the unfortunate side effect to make some sample much more complex than they should be. The purpose of this issue is to revisit our samples and move such code that a dedicated integration tests infrastructure.

**Comment by philwebb** [comment]
The following are candidates (edit this comment to add more)

- [ ] spring-boot-sample-test-nomockito

**Comment by jmcshane** [comment]
I'd like to help with this, as I use spring boot fairly heavily and would like to help improve the integration tests.  I'm building up PR #8405 with some of the modules listed above by @philwebb.  Feel free to add comments on the PR

**Comment by philwebb** [comment]
@jmcshane Cool. Thanks.

**Comment by snicoll** [comment]
This one is superseded now that we've moved all of them to smoke tests, see #17197.
