### ISSUE TITLE
spring-boot-autoconfigure: add support to connect to Hornetq clusters

### ISSUE THREAD

**Issue by leflamm** [spring-projects/spring-boot#6376]
Our Spring Boot applications need to connect to Hornetq clusters. Currently we're adding the following extra configuration class. It creates an array of ``TransportConfiguration`` using a custom property (here called) ``foo.bar.authorities`` containing a list of comma-separated Hornetq hosts.

Class has been simplified, e. g. authorization has been intentionally left out here to keep it simple.

```java
@Configuration
public class JmsConfig {
    @Bean
    HornetQJMSConnectionFactory hornetqFactory(
            @NonNull @Value("${foo.bar.authorities}") String authorities) {
        List<TransportConfiguration> configs = Arrays.stream(authorities.split(",")).map(
                String::toLowerCase).map(String::trim).map(JmsConfig::fromAuthority).collect(
                        Collectors.toList());

        return new HornetQJMSConnectionFactory(true, Iterables
                .toArray(configs, TransportConfiguration.class));
    }

    static TransportConfiguration fromAuthority(@NonNull String authority) {
        String[] hostAndPort = authority.split(":");
        checkState(hostAndPort.length == 2);
        checkState(!hostAndPort[0].isEmpty());
        checkState(!hostAndPort[1].isEmpty());
        return new TransportConfiguration(NettyConnectorFactory.class.getName(), ImmutableMap.of(
                "host", hostAndPort[0], "port", hostAndPort[1]));
    }
}
```
I'd like to provide a PR to add support to spring-boot-autoconfigure (``HornetQProperties`` and ``HornetQConnectionFactoryFactory``) to make this work out of the box. I have a couple of questions regarding this:
- is there another solution for what I try to solve
- is it possible to introduce a new property like ``spring.hornetq.authorities``
- does it make sense to provide PRs for ``org.springframework.boot.autoconfigure.jms.hornetq`` or is this pretty much dead?

Thanks Christian.
Using ``spring-boot-starter-hornetq`` in version ``1.3.5.RELEASE``

**Comment by snicoll** [comment]
@leflamm HornetQ is actually deprecated in Spring Boot 1.4 so I am not sure we're going to change the support any further. What is stopping you to migrate to Artemmis

**Comment by leflamm** [comment]
HI @snicoll, do you mean (a) migrate our JMS infrastructure or (b) use `spring-boot-starter-artemis`` to connect to our HornetQ cluster?

(a) just nothing I can quickly do
(b) does that work?

Thanks, Christian

**Comment by snicoll** [comment]
I mean HornetQ is deprecated (the project itself is no longer maintained). We're willing to consider that feature for Artemis though.

**Comment by leflamm** [comment]
Just to cross this off the list - can you also comment on (b) please?

**Comment by snicoll** [comment]
No it doesn't. the HornetQ client connects to HornetQ and the artemis client connects to Artemis.

**Comment by wilkinsona** [comment]
For background, here's the [announcement of the switch to Artemis](http://hornetq.blogspot.co.uk/2015/06/hornetq-apache-donation-and-apache.html). The last HornetQ release (2.4.7) was in April 2015.

**Comment by leflamm** [comment]
Thanks!

**Comment by leflamm** [comment]
Closing HornetQ-specific issue.
