### ISSUE TITLE
Regression in spring-boot 1.3.6 on log properties

### ISSUE THREAD

**Issue by llappall** [spring-projects/spring-boot#6380]
I'm seeing the same problem with the previous regression (see issue  #5274) in 1.3.6. 
The fix mentioned in #5274 still works. For reference:
"You can work around the problem by calling System.setProperty("PID", new ApplicationPid().toString()) before you call SpringApplication.run()."
And add a @BeforeClass in tests if needed.

**Comment by wilkinsona** [comment]
A test was added when the regression was fixed so I suspect this must be subtly different. Can you please provide a sample project that fails with 1.3.6 but works with an earlier version?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
