### ISSUE TITLE
POST on /env works when endpoints.env.enabled=false in springboot 1.3.6.RELEASE

### ISSUE THREAD

**Issue by upasanamehta** [spring-projects/spring-boot#6383]
While working with spring-cloud-config-client , and springboot 1.3.6.RELEASE , on adding endpoints.env.enabled=false in application properties file GET call on /env of springboot-actuator responded with 500 error , while POST call on /env responded with a 200 Ok response.
Is this the expected behaviour? Shouldnt the POST call also respond with an error ?

**Comment by wilkinsona** [comment]
This is out of Spring Boot's control. `spring-cloud-config-client` pulls in `spring-cloud-context` which provides its own `/env` endpoint: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentManagerMvcEndpoint.java
