### ISSUE TITLE
init.d script doesn't check return code

### ISSUE THREAD

**Issue by dkirrane** [spring-projects/spring-boot#6388]
I have my spring-boot app installed as an init.d service on RHEL

My app returns the following error code

```           
System.exit(SpringApplication.exit(applicationContext, new ExitCodeGenerator() {
                @Override
                public int getExitCode() {
                    return 1;
                }
}));
```

However, when I start the app `service app start` it just prints `Started [17051]` as if everything is fine.

I took a look at the init.d script created and the `do_start()` only checks if the pid file was created. 
It currently doesn't check the apps return code. Adding an option to check the return code would be useful.

```
    checkPermissions || return $?
    $command >> "$log_file" 2>&1 &
    pid=$!
    disown $pid
    echo "$pid" > "$pid_file"

    [[ -z $pid ]] && { echoRed "Failed to start"; return 1; }
    echoGreen "Started [$pid]"
```

**Comment by wilkinsona** [comment]
That's an unusual app to be running as a service. Typically, I'd expect an app that's run via init.d to be a long-running service that doesn't exit until it's stopped.

`start` can't wait for an exit code from the process as there's no way of knowing how long it should wait, i.e. it'd have to wait indefinitely. For apps that are long-running, that would mean that `start` never returned.
