### ISSUE TITLE
JRuby cannot read gems from an embedded jar

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#639]
There's a long discussion on the Sagan issue tracker about this: https://github.com/spring-io/sagan/pull/191. No-one fingered Boot as the culprit there but it looks like the JRuby classloader can't find a gem inside a jar that the Boot classloader is aware of. It took a lot of effort to reproduce this [see here](https://github.com/scratches/jruby-gem-sample), but I'm not quite sure of the internal details yet so can't suggest a fix. It looks to me from the debugger like RUBY_HOME is OK (inside the jruby jar), but the additional gem (hello) is never added. It works when you run from Maven or from the IDE, and in that case I think there is a Ruby script running that adds the dependency JAR to the Ruby LOAD_PATH. It's that step which isn't happening in the "java -jar ..." case.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-boot/issues/1070 which added support for unpacking certain nested jars.
