### ISSUE TITLE
Upgrade Maven Compiler plugin when MCOMPILER-271 is fixed.

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6391]
See #6334 and https://issues.apache.org/jira/browse/MCOMPILER-271

**Comment by agebhar1** [comment]
This issue should be closed, the current version of Maven Compiler Plugin is 3.8.0.

* upgrade to 3.8.0 by 193b2f187b904fbea4da5b810e831a21ee4273f8 (current version)
* upgrade to 3.7.0 by 43086c07083b6329d6609ba1c7ed63df5a5ccc6f
* upgrade to 3.6.2 by 0ba63424a759f5c76c78237ba54f815f4580a184
* upgrade to 3.6.1 by 62d70dacf0c4202df8165284c19d85a26b367ca7 marked as affected by [MCOMPILER-271](https://issues.apache.org/jira/browse/MCOMPILER-271) beside of 3.5.1
* downgrade to 3.1 by 7969d97f40b7a762bcb3f0b3d93d494a01ec9988
* downgrade to 3.5 by f26bdd32ff31ac4dae27c82da6cb43d72165f84b which closed this issue some times ago
* upgrade to 3.5.1 by b8ee1f769ca6fa4948a4f13cc0b648439fc9689d (from 3.1)

**Comment by wilkinsona** [comment]
Thanks. I suspect we forgot about this issue when we moved to 3.6.1 during 2.0's development. No one appears to have been affected by that move so I guess we can close this one.
