### ISSUE TITLE
Provide a convention-based mechanism for configuring response expectations on MockRestServiceServer

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6393]
I'd like to reduce the boilerplate that's involved in configuring expectations on a MockRestServiceServer, particularly for provide a response to a request. It's quite common for such responses to be loaded from a file so you end up doing something like this:

``` java
@Test
public void getVehicles() {
    this.server.expect(requestTo("https://api.example.com/vehicles"))
                .andRespond(MockRestResponseCreators.withSuccess()
                    .body(new FileSystemResource(
                            "src/test/resources/com/example/api/getVehicles.json"))
                    .contentType(MediaType.APPLICATION_JSON));
    // …
}
```

Based on some conventions for the location of the file using the name of the test class and the name of the test method, I'd like to reduce this to something like this:

``` java
@Test
public void getVehicles() {
    this.server.expect(requestTo("https://api.example.com/vehicles"))
                .andRespond(this.jsonResponse);
    // …
}
```

Where `this.jsonResponse` is an `@Autowired` `ResponseCreator` that's aware of the current test class and test method and looks up the file the contains the response's body. For example if the test class is `com.example.api.VehiclesTests` and the test method is named `getVehicles` the contents of the file in `src/test/resources/com/example/api/VehiclesTests-getVehicles.json` would be used as the body of the response.

The example described above is JSON-specific, but it need not be. For example, the content type of the response could be inferred from the file extension.

**Comment by wilkinsona** [comment]
Here's a rudimentary implementation of what I had in mind: https://github.com/wilkinsona/spring-calendar/commit/953478fd2ac8c693213af67d6a961ccece718a1b

**Comment by wilkinsona** [comment]
I'm undecided on the best way to implement this. [This branch](https://github.com/wilkinsona/spring-boot/tree/gh-6393) contains a couple of options, both of which are JUnit rules and resolve resources using a pattern based on the current test class and test method.

`TestMethodResponseCreators` is an alternative to `MockRestResponseCreators`. Unlike `MockRestResponseCreators`, its methods aren't static as it is stateful. It uses the resolved resource to automatically configure the body (and, if the resource filename as a recognised file extension, the content type) of the created response. Using it looks like this:

```java
@Rule
public TestMethodResponseCreators response = new TestMethodResponseCreators();

@Test
public void getProjects() {
	this.server.expect(requestTo("https://jira.spring.io/rest/api/2/project"))
			.andRespond(this.response.withSuccess());
	// …
}
```

`TestMethodResource` is more general purpose. It's a `Resource` that acts as a proxy for a resource that's resolved based on the current test class and test method. Using it looks like this:

```java
@Rule
public TestMethodResource body = new TestMethodResource();

@Test
public void getProjects() {
	this.server.expect(requestTo("https://jira.spring.io/rest/api/2/project"))
			.andRespond(withSuccess(this.body, MediaType.APPLICATION_JSON));
	// …
```

In this case, `withSuccess` is the static method on `MockRestResponseCreators`. The approach taken by `TestMethodResource` feels more flexible, but loses the ability to automatically set the response's content type.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
