### ISSUE TITLE
Consider moving ApplicationPidFileWriter to spring-boot

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#6398]
`ApplicationPidFileWriter` lives in `spring-boot-actuator`. I don't know why `ApplicationPidFileWriter` lives there. It is generally useful to me regardless of Spring Boot Actuator. Does it make sense to move `ApplicationPidFileWriter` to `spring-boot`?

**Comment by wilkinsona** [comment]
The same logic could be applied to `EmbeddedServerPortFilterWriter` as well

**Comment by michaeltecourt** [comment]
@philwebb the class from the actuate module has been removed in Spring Boot 1.5, is it possible to update the release notes accordingly ? (I don't think I can send PRs for the Wiki)

**Comment by wilkinsona** [comment]
@michaeltecourt We don't list the classes individually, but there's a general statement at the top of the release notes covering all classes that were deprecated in 1.4:

> Classes, methods and properties that were deprecated in Spring Boot 1.4 have been removed in this release. Please ensure that you aren’t calling deprecated methods before upgrading.

**Comment by michaeltecourt** [comment]
Oh sorry didn't even notice, thanks for the reply.
