### ISSUE TITLE
Add dependency management for Querydsl

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6399]
As Querydsl is an often used third-party dependency with Spring Data projects, it would be cool if users wouldn't have to have to manually declare versions.

Also, the MongoDB variant of it currently pulls in the legacy MongoDB java driver, so that if the Spring Data MongoDB starter is used and no manual exclusion for the legacy driver is declared on the dependency declaration for Querydsl, you end up with both drivers on the classpath. Would be cool if those exclusions could be added to the dependency management section in Boot.

**Comment by wilkinsona** [comment]
The Platform already has dependency management for QueryDSL. We should move it all into Boot.
