### ISSUE TITLE
Prepare reactor versions split

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6409]
The next reactor version will have a split between core and 3rd party integration. Right now, Spring Boot defines a `reactor.version` that will no longer be relevant. 

Maybe we can anticipate that a bit by introduction a `reactor-core.version` that provides the value for `reactor-core` and have a `reactor.version` that would alias to it. This would [make it easier to  to integrate reactor 3 based on Spring 1.4](https://github.com/bclozel/spring-boot-web-reactive/blob/master/spring-boot-autoconfigure-web-reactive/pom.xml#L22-L23).

**Comment by snicoll** [comment]
We'll have a BOM for the next version so there is no need to do this.

**Comment by smaldini** [comment]
Confirmed that we will provide a BOM once the main dependencies reach stable version (reactor core 3.0 will be stable but not reactor netty 0.5 until 1.0)
