### ISSUE TITLE
`/beans` endpoint doesn't look considering FactoryBean.isSingleton() properly

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#6411]
I created a prototype-scoped `FactoryBean` as follows:

```
public class PrototypeObjectFactoryBean implements FactoryBean<PrototypeObject> {
	
	@Override
	public PrototypeObject getObject() throws Exception {
		return new PrototypeObject();
	}

	@Override
	public Class<?> getObjectType() {
		return PrototypeObject.class;
	}

	@Override
	public boolean isSingleton() {
		return false;
	}
	
}
```

and registered it as follows:

```
@Configuration
public class AppConfig {
	
	@Bean
	public PrototypeObjectFactoryBean prototypeObject() {
		return new PrototypeObjectFactoryBean();
	}
	
}
```

I got the following result from `/beans` endpoint:

```
  }, {
    "bean" : "prototypeObject",
    "scope" : "singleton",
    "type" : "com.izeye.throwaway.config.PrototypeObject",
    "resource" : "class path resource [com/izeye/throwaway/config/AppConfig.class]",
    "dependencies" : [ ]
  }, {
```

I expected it to be `prototype`, not `singleton`.

This is a sample project reproducing the problem: https://github.com/izeye/spring-boot-throwaway-branches/tree/rest-and-actuator

**Comment by philwebb** [comment]
I'm pretty sure that the `FactoryBean.isSingleton()` doesn't actually affect the `scope`. From the javadoc:

> This method returning `false` does not necessarily indicate that returned objects are independent instances. An implementation of the extended `SmartFactoryBean` interface may explicitly indicate independent instances through its `SmartFactoryBean.isPrototype()` method.

@jhoeller can probably confirm. Either way, I'm afraid it's a Spring Framework issue since Boot just delegates to `org.springframework.context.support.LiveBeansView`.

**Comment by izeye** [comment]
@philwebb Okay, thanks! I created an issue on the Spring Framework issue tracker: https://jira.spring.io/browse/SPR-14482
