### ISSUE TITLE
Consistently use bytes as the unit for all memory-related metrics

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#6413]
Enhancement request:
Provide ability to specify the unit of measurement for memory metrics.
Currently all the metrics extracted via `MemoryUsage` mBean are automatically converted to Kb unit of measurement, instead of original `bytes`, which causes issues for migrated applications, that used to rely on Dropwizard JVM `MemoryUsageGaugeSet` to export the same metrics, which used `bytes` as a unit of measurement. (Also, IMHO, it would be beneficial for others, who choose/want/need to get memory metrics in bytes instead of Kb).  

Maybe adding a property (something along the lines of `memoryMetricUnitMultiplier`) with default value of `1024`, but externally configurable, to allow custom selection of units?

**Comment by wilkinsona** [comment]
IMO, bytes should be the default unit. It seems strange to use a default that causes a loss of precision

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
