### ISSUE TITLE
Drop support for Tomcat 7

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6416]
Drop support for Tomcat 7 and remove `StoreMergedWebXmlListener`.

**Comment by htynkn** [comment]
hey @philwebb , Tomcat 7 support java 6 and later and Tomcat java 7 and later. If we drop support for tomcat 7, that means if spring boot user choose tomcat and they must use java 7 and later.

I see this task only marked as `enhancement` without any milestone information, can I ask which spring boot version plan to drop support for tomcat 7?

**Comment by snicoll** [comment]
@htynkn Spring Boot 2.0 will require java 8 by default (as does Spring 5).
