### ISSUE TITLE
spring-boot-actuator class RedisHealthIndicator not support redis cluster.

### ISSUE THREAD

**Issue by z00194267** [spring-projects/spring-boot#6430]
Bug report

version:
spring-boot-actuator 1.3.5.RELEASE
spring-data-redis   1.7.2.RELEASE

Class: RedisHealthIndicator , method: doHealthCheck
builder.up().withDetail("version", info.getProperty("redis_version"));

check the status of the redis cluster，the info properties of redis is 
redis_version : 3.0.7,
but redis cluster is 
10.10.10.10:6379.redis_version : 3.0.7,
so it not match, then health check failed.

**Comment by vpavic** [comment]
See #6059 - this was merged recently and will be available in the upcoming ```1.4.0``` release of Spring Boot.

**Comment by wilkinsona** [comment]
Thanks, @vpavic
