### ISSUE TITLE
Spring Security allow a static resources for html, and webjars

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6435]
it seems strange to me that

> `/css/**`, `/js/**`, `/images/**` and `**/favicon.ico`

are the only paths allowed by default. Maybe there should be an insecure path? also seems like maybe it should be `/css/**/*.css` to validate that it is what it says it is.

`/public` would make sense, but I don't know if there's a way for security to validate things were found in the `resources/public` even though they aren't served at `/public` but just `/` that said if backwards compatibility has to be maintained maybe a new directory could be allowed. Also `/webjars/**` should be allowed if they are detected

**Comment by wilkinsona** [comment]
> /public would make sense, but I don't know if there's a way for security to validate things were found in the resources/public even though they aren't served at /public but just /

There isn't. Spring Security's filter works at the servlet level so it doesn't know anything about Spring MVC's static resource handling. If `/public` was an allowed path then the request path would have to begin `/public` as well.

>  Also /webjars/** should be allowed if they are detected

Agreed. We've added this in 1.4. See https://github.com/spring-projects/spring-boot/issues/2460.

> Maybe there should be an insecure path? also seems like maybe it should be /css/**/*.css to validate that it is what it says it is.

Both of these would be breaking changes with minimal, if any, benefit. The defaults can be easily customised using `security.ignored` so I would recommend using that if you want to fine-tune things to your specific requirements.

**Comment by xenoterracide** [comment]
> Both of these would be breaking changes with minimal, if any, benefit.

there's the possibility of accidental exposure, should someone place something in those directories they didn't intend to be served. But that risk is minimal.

**Comment by xenoterracide** [comment]
maybe there could be properties to configure which routes are secure.

Just trying to resolve the issue of there are no public routes for html files by default, and overriding the defaults in code seems like overkill, this makes it harder to server up static ui for frameworks like angular.
