### ISSUE TITLE
Provide main()  method that allows you to shutdown running context

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#644]
main() method which get's running jvm pid and shutdowns context. @dsyer Any ideas about location? loader-tools already has some required stuff for that

**Comment by snicoll** [comment]
@jkubrynski Spring Boot 1.3 has an admin feature that you can enable to remotely shutdown the application via JMX. We use that in the Maven plugin to offer a start/stop goals. Would that help your use case? See [the documentation](http://docs.spring.io/spring-boot/docs/1.3.0.M2/reference/htmlsingle/#boot-features-application-admin) for more details.

**Comment by jkubrynski** [comment]
@snicoll I think yes - it solves this issue

**Comment by snicoll** [comment]
See #3179 - Thanks for the feedback @jkubrynski
