### ISSUE TITLE
Support @ConditionalOnSingleCandidate for JdbcTemplate and DataSourceTransactionManager

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-boot#6448]
I hope to support `@ConditionalOnSingleCandidate(DataSource.class)` on auto configuration of  `JdbcTemplate` and `DataSourceTransactionManager` for multiple data source. What do you think ?

I will submit a PR for this issue at later.

**Comment by snicoll** [comment]
Duplicates #6449
