### ISSUE TITLE
Allow JSON Testers to be `@Autowired`

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6451]
It is mentioned in passing as being useful if "you need to configure elements of the auto-configuration", but there is no hint as to what that means. In addition, it is not mentioned that it will wire up fields of type `BasicJsonTester` (etc.), but *not* if they are `@Autowired`. (Actually it might be useful and less confusing to simply support `@Autowired` as well.)

**Comment by snicoll** [comment]
My vote would be to only support them when they are `@Autowired` if we can. It would also avoid a specific case in IDEs support (the field is currently flagged with a violation because nothing sets the value).

**Comment by philwebb** [comment]
I don't think `@Autowire` is appropriate for `JacksonTester` fields since they're not actually beans.

**Comment by dsyer** [comment]
Isn't that just too confusing (for users and for IDEs apparently)? If there is an application context there could be beans.

**Comment by snicoll** [comment]
I agree. They can't be beans because they're just too many instances of them. Lazy bean resolution? Instead of injecting a `JsonTester<Foo>` maybe you could have one bean that allows you to build them  `JsonTesterFactory#getJsonTester(Foo.clas)`.

Do we have anywhere in the codebase something that sets the value of all field of a certain type with no marker at all?

**Comment by philwebb** [comment]
> Isn't that just too confusing (for users and for IDEs apparently)? If t

What's confusing the IDE? The way it should work is any non instantiated `JacksonTester` fields in your test class are created for you when the test runs. You shouldn't add `@Autowired` at all.

> Lazy bean resolution? Instead of injecting a JsonTester<Foo> maybe you could have one bean that allows you to build them JsonTesterFactory#getJsonTester(Foo.clas)

I tried a few ideas around that but it just became really hard to use. The testers really aren't Beans, and shouldn't be considered as such. They're more like assertions, or rules. The `@JsonTest` annotation just automatically triggers a call to `JacksonTester.initFields`.

**Comment by wilkinsona** [comment]
> What's confusing the IDE?

I think IDEA complains about an unassigned field being used
