### ISSUE TITLE
Add Locale to Charset Mapping support for servlet containers

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#6453]
Setting the `Locale` on a given HTTP servlet response, depending on the servlet container, may trigger the character encoding attribute to be set on that response.

This means that the response may have a `Content-Type: text/html;charset=ISO-8859-1` header if the `ISO-8859-1` charset is the default value for the given locale, even if that encoding is not the one we want for our application.

Spring Boot should support new configuration keys:

```
spring.http.encoding.mapping.<locale>=<charset>
```

**Comment by snicoll** [comment]
Do we really want to change the charset according to the locale? Isn't the issue about making sure we have the right encoding? If so, a single value should work.

**Comment by wilkinsona** [comment]
If you don't want to do it per-locale, then you can use `spring.http.encoding.force-response: true`. I think we still need something more here to cover a couple of things:

1. The different embedded containers have different default mappings
2. We don't have an equivalent of web.xml's `<locale-encoding-mapping-list>`

**Comment by KarkiSundaram** [comment]
Spring Boot should support new configuration keys:

spring.http.encoding.mapping.<locale>=<charset> Please provide sample for the

**Comment by snicoll** [comment]
@KarkiSundaram please don't request features on closed issues. If you're looking to get support, ask your question on StackOverflow.
