### ISSUE TITLE
JmsListenerContainerFactory doesn't back off with two ConnectionFactory beans

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6463]
Follow up of #2784 

See also [this thread](http://stackoverflow.com/questions/38584393/exception-on-multiple-queueconnectionfactory)

**Comment by cvienot** [comment]
In my understanding, this issue is a duplicate of issue [12700](https://github.com/spring-projects/spring-boot/issues/12700) and was fixed in this [pull request](https://github.com/spring-projects/spring-boot/commit/75937f5b5c1450b6f7af1211d52f9e9787df6f70).

**Comment by snicoll** [comment]
@cvienot good catch, thank you.

Duplicate of #12700
