### ISSUE TITLE
Autoconfiguration of standalone servlet context

### ISSUE THREAD

**Issue by T3rm1** [spring-projects/spring-boot#6464]
Spring Boot 1.3.5
Application is packaged as war and deployed in Tomcat 7 server.

The property `server.session.tracking-modes=cookie` configures the servlet context. This does work when the application is started as a spring boot application with embedded tomcat.

It does not work when it is deployed in a Tomcat 7 standalone servlet container.

Workaround: I have to set it manually in `onStartup()` of `SpringBootServletInitializer`.

**Comment by wilkinsona** [comment]
> It does not work when it is deployed in a Tomcat 7 standalone servlet container.

Can you please provide some more details? How have you identified that it doesn't work?

**Comment by T3rm1** [comment]
``org.springframework.boot.autoconfigure.web.ServerProperties.SessionConfiguringInitializer.onStartup(ServletContext)`` does not get called with standalone server.

In addition I see all my urls prepended with ``;jessionId=``. This does not happen if I set the tracking mode manually to cookie or if I start with embedded tomcat.

**Comment by wilkinsona** [comment]
Thanks, we're on the same page now.

The vast majority of the `server.*` properties only affect an embedded container, although there are one or two exceptions which we'd like to straighten out (see #4818). I think the servlet context's lifecycle is such that we could set the session tracking modes, but I'm not sure that we'd want to. Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
We intend to deal with this as part of #4818
