### ISSUE TITLE
Cache limit for destination cache in SimpleBrokerMessageHandler can't be altered

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#6483]
Hey,

I'm currently working on a project in which we use websockets to notify the user about (a lot of) changes. We currently test with 5000 concurrent users and the websocket layer seems to be a bottleneck. When you look at the following screenshots from a 5 minute profile, you will notice two things:

1. A high lock contention in **org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry$DestinationCache**
2. Rather slow performance of AntPathMatcher

**Lock Contention**
![subscription-cache-lock-contention](https://cloud.githubusercontent.com/assets/6304496/17167587/37527596-53de-11e6-988e-6bebeb614237.jpg)

**Hot Methods**
![subscription-cache](https://cloud.githubusercontent.com/assets/6304496/17167588/3a37f59c-53de-11e6-9e33-be5102303bce.jpg)

A little bit of research showed that DefaultSubscriptionRegistry offers a method to set the cache limit, which currently is at a default value of 1024. Due to that in our case "older" subscriptions are removed whenever the cache is altered, which ultimately leads to the need of going through 1) the synchronization of the cache and 2) the rather expensive path matching process again and again.

I wanted to increase this cache limit to prevent this expensive roundtrips, but found no way to access the DefaultSubscriptionRegistry as I e.g. can't override the MessageBrokerRegistry to enhance the creation of the SimpleBrokerMessageHandler.

Since the PathMatcher can be customized already, I would have preferred something like this:

```
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractSessionWebSocketMessageBrokerConfigurer<ExpiringSession> {

	@Override
	public void configureMessageBroker(MessageBrokerRegistry config) {
		config.enableSimpleBroker("/queue/", "/topic/").setTaskScheduler(new ConcurrentTaskScheduler());
		config.setPathMatcher(new CustomPathMatcher());
		config.setCacheLimit(8192);
		config.setApplicationDestinationPrefixes("/app");
	}

}

```

I don't know if this is maybe even a Spring-Framework issue, but since the DefaultSubscriptionRegistry offers a setCacheLimit method already, I opened this issue here.

As a last resort I would switch to a full broker, but the additional dependency on RabbitMQ is something I want/need to prevent in our case.

I'd be glad if you could offer a solution to our problem. Maybe even a workaround for now.

Cheers,
Christoph

**Comment by snicoll** [comment]
Which version have you used for this? Can you try with `1.4.0.SNAPSHOT` to confirm that problem still exists in that version?

**Comment by dreis2211** [comment]
Sorry, forgot to include that. We're currently using 1.3.5.RELEASE and will test with 1.4.0 as soon as GA is available tomorrow(?). ;-)

**Comment by snicoll** [comment]
May I ask you to test with the snapshot now if possible? Check [the project page](http://projects.spring.io/spring-boot/) for setup instruction. If there is anything we can do today about this, I'd rather now asap.

**Comment by snicoll** [comment]
@dreis2211 scratch that. I missed some part of the original request. That's indeed a SPR only issue. I've created [SPR-14516](https://jira.spring.io/browse/SPR-14516) and we'll try to address this today still. Please watch the other issue. Thanks!

**Comment by dreis2211** [comment]
Thanks for the quick reply @snicoll !
