### ISSUE TITLE
AutoConfiguration to support creating multiple dynamic named beans

### ISSUE THREAD

**Issue by davsclaus** [spring-projects/spring-boot#6484]
AutoConfiguration is awesome for setting up beans you typically only need one instance, such as a DataSource etc.

I am looking for a way of allowing the end user to

- allow to specify the name of the bean, such as from application.yml / .properties file
- create multiple bean instances of same type but with different names

For example in your application.properties file you can setup two beans of `Dude` type being named `foo` and `bar` as follows:

```
dude.foo.timeout=10000
dude.foo.verbose=false

dude.bar.timeout=20000
dude.bar.verbose=true
```

In this example there is an AutoConfiguration that can create beans of Dude type. 
```
    @Bean
    public Dude configureDude(DudeConfiguration configuration) throws Exception {
      ...
    }
```

What I would like to see possible is somehow to tell Spring Boot that the `DudeConfiguration` supports dynamic name, where you can specify this in the `prefix` such as:

For example using an `.*` to denote a dynamic name 
```
@ConfigurationProperties(prefix = "dude.*")
public class DudeConfiguration {
```

or maybe better to use a REST like binding using `{id}` style

```
@ConfigurationProperties(prefix = "dude.{name}")
public class DudeConfiguration {
```

The `DudeAutoConfiguration` class would then need to support `{name}` for example as a parameter in the method signature of the `@Bean` that can create the beans, such as `String name` below:

```
    @Bean
    public Dude configureDude(DudeConfiguration configuration, String name) throws Exception {
      ...
    }
```

There is maybe a better way. But its important that the value of the `name` is available in the configure method so we can use that in the code to create the configured dude instance to be returned.

Also maybe `@Bean` needs to highlight that the method creates dynamic named beans, so you should maybe specify this as `Bean(name = "{name}")` or something.

For more background details then I work on Apache Camel where we are adding much love for Spring Boot to allow to configure Camel using Spring's AutoConfiguration. The missing piece we need is to be able to let end users configure Camel endpoints, where you can have multiple endpoints of the same type (eg JMS, File, RabbitMQ) but configured differently. And the name of these endpoints is a name that the end users specify.

We discussed this in the Camel ticket at: https://issues.apache.org/jira/browse/CAMEL-10031

We have looked at an out of the box solution with current Spring Boot and could not find one, either does the Map/List type in AutoConfiguration not work well. Tooling in IDEA,Eclipse etc. does neither work well with them as they do not provide auto completion / default values / documentation. We could not find any existing ticket reported about this enhancement. A related ticket we could find was: https://github.com/spring-projects/spring-boot/issues/2687

**Comment by snicoll** [comment]
Both are not an option at this point I am afraid. Your suggestion would require a new feature in the meta-data to express a variable bit in the key. Even if we did that, that still doesn't explain how beans are going to be magically created: `@ConfigurationProperties` must remain a bridge to the environment and I am not keen on adding more responsibility to them. You'd have to loop over the created `@ConfigurationProperty` instances (assuming we would do that) and create a `Bean` per instance. You can't do that either as far as I know (but I've seen something in the 5.0 backlog about that).

I also feel that having a configuration key triggering the creation of a bean is weird. But that might just be me. I'll make sure we discuss this at our next team meeting.

**Comment by wilkinsona** [comment]
@davsclaus setting aside the metadata for the moment, have you looked at `@Import` and `ImportBeanDefinintionRegistrar`? A typical pattern is an `@Enable…` annotation with an accompanying registrar. For example, you could have `@EnableCamel` and a `CamelRegistrar` that implements `ImportBeanDefinitionRegistrar`. Your registrar can then register as many beans as you like with whatever names you want. On the one hand, it's more leg work than what you've described, but, one the other hand, it'll let you achieve your two goals (specifying the name of the beans and creating multiple instances of the same type with different bean names) today.

**Comment by davsclaus** [comment]
Thanks you @wilkinsona for the suggestions.

We would really like to see that the end user can assign the bean name dynamically from the application.yml/properties, and let it be out of the box, so tooling and whatnot is able to support this.

The big win is the easy of use for end users where they got the metadata documentation at their fingertips and can use code assistance.

Thanks for the feedback and taking up a discussing on this in your team.

**Comment by wilkinsona** [comment]
We discussed it yesterday and agreed that this isn't something that we want to support out of the box. A major drawback is the complexity that it would introduce to the metadata and the work that would have to be done by IDE developers to support the more complex format. We don't feel that the benefits are worth that added complexity.

Note that you can still make use of configuration from application.yml/properties in an `ImportBeanDefinitionRegsitrar`. Your registrar should implement `EnvironmentAware` and it can then use `RelaxedPropertyResolver` in tandem with the injected environment to read the configuration.

**Comment by davsclaus** [comment]
@wilkinsona in your tweet: https://twitter.com/ankinson/status/758598696456032256

Would you be able to comment a bit more here what you mean? I do not understand what you mean by "value".

**Comment by wilkinsona** [comment]
I meant value, as in the value of a property. It's really about how you structure your properties or YAML. To be tooling friendly, you want the keys to be finite and well-known. In other words, by not having part of a key by a name that a user can choose. Concretely, rather than:

```
dude.foo.timeout=10000
dude.foo.verbose=false

dude.bar.timeout=20000
dude.bar.verbose=true
```

You'd have something like:

```
dude[0].name=foo
dude[0].timeout=10000
dude[0].verbose=false

dude[1].name=bar
dude[1].timeout=20000
dude[1].verbose=true
```

**Comment by nicolaferraro** [comment]
@wilkinsona the solution you are suggesting works and indeed it is one of the options we took into consideration in https://issues.apache.org/jira/browse/CAMEL-10031.
The support for lists in the tooling (I tested it in IntelliJ Idea) is not perfect though. The IDE displays the fields (eg. name, timeout, verbose) but not their descriptions or default values.

Is this something that will be improved in future versions of the tooling?

**Comment by davsclaus** [comment]
Is it not Jetbrains that maintain the IDEA plugin for Spring? So its maybe them we or Pivotal should get in touch with to report this issue.

**Comment by davsclaus** [comment]
Just a few screenshots of a prototype.

Without the List then the tooling works with documentation and also using dash style for the property names (eg allow-java-serialized-object vs allowJavaSerializedObject)

![screen shot 2016-08-02 at 10 54 20 am](https://cloud.githubusercontent.com/assets/477100/17322809/a6d98650-589f-11e6-8201-b1ef00b0f23b.png)

And the below is the List[] where the properties in the tooling has no description, and the dash style is not in use

![screen shot 2016-08-02 at 10 54 36 am](https://cloud.githubusercontent.com/assets/477100/17322821/ba649070-589f-11e6-96ab-1d543fb1c6dc.png)

And the generated spring-configuration-medatadata.json is as follows:
```
{
  "groups": [
    {
      "name": "camel.component.ahc",
      "type": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.endpoint.ahc",
      "type": "org.apache.camel.component.ahc.springboot.AhcEndpointConfiguration",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointConfiguration"
    },
    {
      "name": "camel.endpoint.ahc",
      "type": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    }
  ],
  "properties": [
    {
      "name": "camel.component.ahc.allow-java-serialized-object",
      "type": "java.lang.Boolean",
      "description": "Whether to allow java serialization when a request uses\n context-type=application/x-java-serialized-object This is by default\n turned off. If you enable this then be aware that Java will deserialize\n the incoming data from the request to Java and that can be a potential\n security risk.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration",
      "defaultValue": false
    },
    {
      "name": "camel.component.ahc.binding",
      "type": "org.apache.camel.component.ahc.AhcBinding",
      "description": "To use a custom AhcBinding which allows to control how to bind between\n AHC and Camel.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.component.ahc.client",
      "type": "org.asynchttpclient.AsyncHttpClient",
      "description": "To use a custom AsyncHttpClient",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.component.ahc.client-config",
      "type": "org.asynchttpclient.AsyncHttpClientConfig",
      "description": "To configure the AsyncHttpClient to use a custom\n com.ning.http.client.AsyncHttpClientConfig instance.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.component.ahc.header-filter-strategy",
      "type": "org.apache.camel.spi.HeaderFilterStrategy",
      "description": "To use a custom HeaderFilterStrategy to filter header to and from Camel\n message.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.component.ahc.ssl-context-parameters",
      "type": "org.apache.camel.util.jsse.SSLContextParameters",
      "description": "Reference to a org.apache.camel.util.jsse.SSLContextParameters in the\n Registry. Note that configuring this option will override any SSL/TLS\n configuration options provided through the clientConfig option at the\n endpoint or component level.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcComponentConfiguration"
    },
    {
      "name": "camel.endpoint.ahc.allow-java-serialized-object",
      "type": "java.lang.Boolean",
      "description": "Whether to allow java serialization when a request uses\n context-type=application/x-java-serialized-object This is by default\n turned off. If you enable this then be aware that Java will deserialize\n the incoming data from the request to Java and that can be a potential\n security risk.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties",
      "defaultValue": false
    },
    {
      "name": "camel.endpoint.ahc.binding",
      "type": "org.apache.camel.component.ahc.AhcBinding",
      "description": "To use a custom AhcBinding which allows to control how to bind between\n AHC and Camel.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    },
    {
      "name": "camel.endpoint.ahc.client",
      "type": "org.asynchttpclient.AsyncHttpClient",
      "description": "To use a custom AsyncHttpClient",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    },
    {
      "name": "camel.endpoint.ahc.client-config",
      "type": "org.asynchttpclient.AsyncHttpClientConfig",
      "description": "To configure the AsyncHttpClient to use a custom\n com.ning.http.client.AsyncHttpClientConfig instance.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    },
    {
      "name": "camel.endpoint.ahc.endpoints",
      "type": "java.util.List<org.apache.camel.component.ahc.springboot.AhcEndpointProperties>",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointConfiguration"
    },
    {
      "name": "camel.endpoint.ahc.header-filter-strategy",
      "type": "org.apache.camel.spi.HeaderFilterStrategy",
      "description": "To use a custom HeaderFilterStrategy to filter header to and from Camel\n message.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    },
    {
      "name": "camel.endpoint.ahc.id",
      "type": "java.lang.String",
      "description": "Endpoint id (mandatory)",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    },
    {
      "name": "camel.endpoint.ahc.ssl-context-parameters",
      "type": "org.apache.camel.util.jsse.SSLContextParameters",
      "description": "Reference to a org.apache.camel.util.jsse.SSLContextParameters in the\n Registry. Note that configuring this option will override any SSL/TLS\n configuration options provided through the clientConfig option at the\n endpoint or component level.",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointProperties"
    }
  ],
  "hints": []
}
```

**Comment by nicolaferraro** [comment]
The point is that for the property `camel.endpoint.ahc.endpoints` the only generated metadata is:

```
...
  {
      "name": "camel.endpoint.ahc.endpoints",
      "type": "java.util.List<org.apache.camel.component.ahc.springboot.AhcEndpointProperties>",
      "sourceType": "org.apache.camel.component.ahc.springboot.AhcEndpointConfiguration"
    },
...
```

This is more evident if you don't use the generic type of the list (`AhcEndpointProperties`) in other "standard" properties. The configuration processor does not generate metadata for the generic type of the list, so the tooling should make suggestions by other means.

**Comment by snicoll** [comment]
We're not dealing with IntelliJ IDEA (nor any other IDEs) in this tracker. Please report that at the appropriate place. @nicolaferraro this is perfectly normal. What would you use expect us to do, we'd have an infinite number of keys. There is already several requests to support browsing POJOs from list and maps so search in their tracker.
