### ISSUE TITLE
(Maybe) Spring logging bug

### ISSUE THREAD

**Issue by aBnormaLz** [spring-projects/spring-boot#6485]
We are using jHipster to generate our spring project. I got the following error while uploading a multipart-form:

```
2016-07-27 11:05:27.787 DEBUG 8732 --- [nio-8080-exec-3] c.s.backend.aop.logging.LoggingAspect    : Enter: com.wanari.backend.web.rest.errors.ExceptionTranslator.processRuntimeException() with argument[s] = [org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'file' is not present]

2016-07-27 11:05:27.793 DEBUG 8732 --- [nio-8080-exec-3] c.s.backend.aop.logging.LoggingAspect    : Exit: com.wanari.backend.web.rest.errors.ExceptionTranslator.processRuntimeException() with result = <500 Internal Server Error,com.wanari.backend.web.rest.errors.ErrorDTO@ca2d2e9,{}>
```

I'm not sure if it's Spring bug or jHipster generator bug. We are using the following (generated) LoggingAspect

```
	package com.wanari.backend.aop.logging;

	import com.wanari.backend.config.Constants;
	import org.aspectj.lang.JoinPoint;
	import org.aspectj.lang.ProceedingJoinPoint;
	import org.aspectj.lang.annotation.AfterThrowing;
	import org.aspectj.lang.annotation.Around;
	import org.aspectj.lang.annotation.Aspect;
	import org.aspectj.lang.annotation.Pointcut;
	import org.slf4j.Logger;
	import org.slf4j.LoggerFactory;
	import org.springframework.core.env.Environment;

	import javax.inject.Inject;
	import java.util.Arrays;

	@Aspect
	public class LoggingAspect {

		private final Logger log = LoggerFactory.getLogger(this.getClass());

		@Inject
		private Environment env;

		@Pointcut("within(com.wanari.backend.repository..*) || within(com.wanari.backend.service..*) || within(com.wanari.backend.web.rest..*)")
		public void loggingPointcut() {
		}

		@AfterThrowing(pointcut = "loggingPointcut()", throwing = "e")
		public void logAfterThrowing(JoinPoint joinPoint, Throwable e) {
			if (env.acceptsProfiles(Constants.SPRING_PROFILE_DEVELOPMENT)) {
				log.error("Exception in {}.{}() with cause = {} and exception {}", joinPoint.getSignature().getDeclaringTypeName(),
					joinPoint.getSignature().getName(), e.getCause(), e);
			} else {
				log.error("Exception in {}.{}() with cause = {}", joinPoint.getSignature().getDeclaringTypeName(),
					joinPoint.getSignature().getName(), e.getCause());
			}
		}

		@Around("loggingPointcut()")
		public Object logAround(ProceedingJoinPoint joinPoint) throws Throwable {
			if (log.isDebugEnabled()) {
				log.debug("Enter: {}.{}() with argument[s] = {}", joinPoint.getSignature().getDeclaringTypeName(),
					joinPoint.getSignature().getName(), Arrays.toString(joinPoint.getArgs()));
			}
			try {
				Object result = joinPoint.proceed();
				if (log.isDebugEnabled()) {
					log.debug("Exit: {}.{}() with result = {}", joinPoint.getSignature().getDeclaringTypeName(),
						joinPoint.getSignature().getName(), result);
				}
				return result;
			} catch (IllegalArgumentException e) {
				log.error("Illegal argument: {} in {}.{}()", Arrays.toString(joinPoint.getArgs()),
						joinPoint.getSignature().getDeclaringTypeName(), joinPoint.getSignature().getName());

				throw e;
			}
		}
	}
```

```
	package com.wanari.backend.config;

	import com.wanari.backend.aop.logging.LoggingAspect;
	import org.springframework.context.annotation.*;

	@Configuration
	@EnableAspectJAutoProxy
	public class LoggingAspectConfiguration {

		@Bean
		@Profile(Constants.SPRING_PROFILE_DEVELOPMENT) // equals "dev"
		public LoggingAspect loggingAspect() {
			return new LoggingAspect();
		}
	}
```

`LoggingAspect.logAround()` is the function that prints the log that I'm copy-pasted.

If I remove the logging aspect nothing shows up on console.

Is this spring related bug?

(additionally sorry if it's not spring related, we thought it is)

**Comment by wilkinsona** [comment]
Sorry, but I don't understand what it is that you consider to be a possible bug.

> If I remove the logging aspect nothing shows up on console.

What did you expect to show up on the console? Without the aspect it's possible that nothing would show up. What does `ExceptionTranslator.processRuntimeException()` do?

If you'd like us to help, please describe in as much detail as possible the behaviour that you'd expect to see and the behaviour that you actually see along with a simple sample application that reproduces the behaviour you are seeing.

**Comment by aBnormaLz** [comment]
I pushed an initial project (generated with jHipster https://github.com/aBnormaLz/jhipster-test
 ) to my github repo, and added the api which creates the log i gave you before. 

you should POST to /api/maybebug with herder:
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTQ3MjIxMzE5OH0.xJ7Kmaz8jRuz5iPvKY6_3Xf1J-9gZ-KDpPNP_TfRCA3e0MasXQRnVvbHkVUzY5PR-BShzK1Z8yC3dSOFmc0M1Q

https://github.com/aBnormaLz/jhipster-test/blob/master/src/main/java/com/wanari/web/rest/UserResource.java

UserResource.createUserTask() is the function

**Comment by wilkinsona** [comment]
Thanks. Before someone takes a look at your app, please describe in as much detail as possible the behaviour that you'd expect to see and the behaviour that you actually see.

**Comment by aBnormaLz** [comment]
If you call the API I defined below the log is the following:

2016-07-27 11:05:27.787 DEBUG 8732 --- [nio-8080-exec-3] c.s.backend.aop.logging.LoggingAspect    : Enter: com.wanari.backend.web.rest.errors.ExceptionTranslator.processRuntimeException() with argument[s] = [org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'file' is not present]

2016-07-27 11:05:27.793 DEBUG 8732 --- [nio-8080-exec-3] c.s.backend.aop.logging.LoggingAspect    : Exit: com.wanari.backend.web.rest.errors.ExceptionTranslator.processRuntimeException() with result = <500 Internal Server Error,com.wanari.backend.web.rest.errors.ErrorDTO@ca2d2e9,{}>

i expect some stack trace or at least some ERROR message (not DEBUG).

**Comment by wilkinsona** [comment]
That's Spring MVC's default behaviour for an exception that's been handled (as it has in this case by your `ExceptionTranslator`). You can, of course, log your own error message in your exception handler if you wish. Alternatively, you tell Spring MVC to log and Spring Boot 1.4 will make this easier. See #2176 for details.

**Comment by aBnormaLz** [comment]
Thanks for your fast help.
