### ISSUE TITLE
Issue with SpringApplicationBuilder example in docs

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#6488]
Bug report

If you add SpringApplicationBuilder as per docs 
```
new SpringApplicationBuilder()
    .bannerMode(Banner.Mode.OFF)
    .sources(Parent.class)
    .child(Application.class)
    .run(args);
```

This wont trigger banner off as it is trying to switch banner off on parent. It should be on child and not parent.

On other hand, 

If we do like below,
``` 
new SpringApplicationBuilder()
    .sources(Parent.class)
    .child(Application.class)
    .bannerMode(Banner.Mode.OFF)
    .run(args);
```
It switches banner off. 

Therefore, it should be documented properly somewhere as example is misleading and somewhere someone may get confused why banner is not switching off.

**Comment by wilkinsona** [comment]
@rajjaiswalsaumya As we discussed on Gitter, are you going to open a pull request for this?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
