### ISSUE TITLE
Type-level @RequestMapping required when it shouldn't be

### ISSUE THREAD

**Issue by Kaef** [spring-projects/spring-boot#6489]
I have encountered an issue with MVC controllers where the @RequestMapping annotations seems to be required at the type level, even though method annotations provide all necessary information. Adding e.g. `@RequestMapping(method = POST)` fixes this issue, even though the method is defined in the method annotation.

I'm attaching a minimal project to reproduce this issue.

[spring-mvc-bug.zip](https://github.com/spring-projects/spring-boot/files/385944/spring-mvc-bug.zip)

**Comment by wilkinsona** [comment]
This is working as designed. To be considered for request mapping, Spring MVC (specifically `RequestMappingHandlerMapping`) [requires a controller class to be annotated (directly or indirectly) with either `@Controller` or `@RequestMapping`](https://github.com/spring-projects/spring-framework/blob/v4.2.7.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.java#L170-L173).
