### ISSUE TITLE
hibernate 5 and AbstractRoutingDataSource

### ISSUE THREAD

**Issue by patrickmcmichael** [spring-projects/spring-boot#6491]
We have a legacy DB for which we need to use `AbstractRoutingDataSource`.  This was playing fine in Spring Boot 1.3, but in 1.4, hibernate 5 detects @SecondaryTable annotations on entities and automatically wants to go and generate Id tables.  This results in a getConnection call during launch of the spring boot app which is BEFORE an appropriate key would be available to

` protected Object determineCurrentLookupKey()`

And due to our business needs, we have to initialize our `AbstractRoutingDataSource` bean with lenientFallback = false, as there is no appropriate "default" datasource.  

Not sure if there's a config flag to turn off id table creation and bypass this.  Right now the code in hibernate that is automatically running this creation at launch time is:

```
org.hibernate.hql.spi.id.IdTableHelper

public boolean needsIdTable(PersistentClass entityBinding) {
		// need id table if the entity has secondary tables (joins)
		if ( entityBinding.getJoinClosureSpan() > 0 ) {
			return true;
		}
.
.
.
```

**Comment by wilkinsona** [comment]
1.4 still supports Hibernate 4.3, although it's no longer the default. What happens if you override `hibernate.version` and drop back to 4.3.11?

**Comment by patrickmcmichael** [comment]
That's my next option, though they won't be supporting it past 1.4, so I'm seeking a longer term solution.  Have dug a bit further and the code snippet above is called in relation to `GlobalTemporaryTableBulkIdStrategy`.  My hunch is that this is tied to Oracle dialect, but noticed there's a per db session variant, `LocalTemporaryTableBulkIdStrategy` that might do the trick for us.  We're using this DB in read-only fashion for now, so we don't care about this strategy for bulk update/delete performance reasons.  

Wondering how to override which strategy gets used and if this would do the trick for us.

**Comment by patrickmcmichael** [comment]
Looks like it gets default from dialect, but may be overridable with hibernate.hql.bulk_id_strategy.

If that works and `LocalTemporaryTableBulkIdStrategy` gets me past my problem, I'll be back in business, but think this means that `AbstractRoutingDataSource` without lenientFallback true, and hibernate 5, may be brittle.

**Comment by patrickmcmichael** [comment]
that seems to have worked...
