### ISSUE TITLE
Spring Boot Packaging Error when multiple main methods exist

### ISSUE THREAD

**Issue by dmfrey** [spring-projects/spring-boot#6496]
A Spring Boot application cannot be packaged when multiple classes contain a main method.

Here is a sample project that demonstrates the issue:
https://github.com/dmfrey/spring-boot-package-error

Desired outcome: The main method from a class decorated with `@SpringBootApplication` should be used by default, or when there are any other conflicts.

**Comment by philwebb** [comment]
Nice idea!

**Comment by dmfrey** [comment]
@philwebb Would this be an issue in Boot itself or is it related to the maven and gradle plugins? If you can provide me some direction, I will take a look at resolving it.

**Comment by techlogix** [comment]
This makes a lot of sense - this 'bug' has caught us a few times. Unannotated classes that have a Main method should be ignored.

**Comment by wilkinsona** [comment]
@dmfrey The logic's all in [`MainClassFinder`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/MainClassFinder.java) and is used by both the build plugins.

**Comment by WispZhan** [comment]
I found the same question.
in Spring Boot 1.5.x, I use `@SpringCloudApplication` annotation. Cannot be packaged too.
Finally, I must switch `@SpringBootApplication`, or remove other main methods.
