### ISSUE TITLE
Enhance WebSockets auto-configuration to notice messaging

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#65]
Currently, the websockets auto-configuration simply notices the registration of `WebSocketHandler`s.  This is a good start, but a common (possibly more common) use of WebSockets will be with some messaging on top.  It'd be nice if Boot would notice the registration of beans that have been annotated with Spring Messaging annotations (e.g. `@SubscribeEvent`, `@MessageMapping`) and eliminate the boilerplate configuration.

The boilerplate configuration I'm currently having to embed looks like the following:

``` java
@Configuration
@EnableWebSocketMessageBroker
static class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/websocket");
    }

    @Override
    public void configureMessageBroker(MessageBrokerConfigurer configurer) {
        configured.setAnnotationMethodDestinationPrefixes("/app");
    }

}
```

As you can see it's simple configuration that would work for most users of Boot (if we were willing to be opinionated on some endpoint names, etc.).  I've had a quick chat with @wilkinsona about this, so he and @rstoyanchev might be able to give you a bit more insight into how much automation can be done here.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by filiphr** [comment]
This has been closed due to inactivity. However, we are currently using websockets with STOMP a lot and have build our own auto configuration with it. Will the Spring Boot team be interested in having such auto configuration? If yes I can prepare something and provide a PR.

There is also an example of Spring Boot and Websockets at https://github.com/salmar/spring-websocket-chat which goes even further and provides some nice actuator endpoints

**Comment by wilkinsona** [comment]
@filiphr We still haven't seen too much demand, but it would certainly be interesting to see what you've got in terms of auto-configuration. Is it somewhere that we could look at it without you having to go to too much effort?
