### ISSUE TITLE
Hello, will spring boot has other language instruction ? 

### ISSUE THREAD

**Issue by weiyujia** [spring-projects/spring-boot#6501]
Hello, will spring boot has other language instruction ?

**Comment by bclozel** [comment]
If you're asking about supported programming languages, you can already write Boot applications with Groovy and [Kotlin](https://spring.io/blog/2016/02/15/developing-spring-boot-applications-with-kotlin).

Or are you asking if the documentation will be translated in other languages? In that case, I'm not aware of any project like that. Maintaining the documentation is already quite time consuming... If you feel like some parts of the documentation aren't easy to understand for non-native speakers, don't hesitate to point those out!

**Comment by weiyujia** [comment]
Thanks, Sorry for my bad english

**Comment by bclozel** [comment]
Hey it's not bad - just wanted to make sure I understood well.

Don't hesitate to reopen this issue if you've got more questions on this.
Thanks!
