### ISSUE TITLE
Provide instructions for downgrading to Hibernate 4.3 when using Gradle

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-boot#6507]
The documentation explains how to [downgrade to Hibernate 4.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#downgrading-to-hibernate-43) for Maven, but not for Gradle. I tried excluding `hibernate-core` and `hibernate-entitymanager` from `data-jpa` and many other dependencies, but it doesn't work. What's the magic formula? 🤔

**Comment by rajadileepkolli** [comment]
You can downgrade by using below in gradle

plugins {
    id "io.spring.dependency-management" version "0.6.0.RELEASE"
}
/* Above plugin is used to override default version in spring boot */
ext['hibernate.version'] = '4.3.11.Final'

This way you can downgrade or upgrade any version

**Comment by snicoll** [comment]
Indeed, thanks @rajadileepkolli - I've upgraded the release notes Matt.
