### ISSUE TITLE
smartly detect cache-control

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6510]
This may be an MVC or a Security issue.

although there's a working workaround, if I specify `cacheControl` in my MVC route, the default security headers for that route should not be applied. I can turn off security headers globally with spring boot but then that's global and those default headers don't get applied to anything regardless of whether or not it's defined.

http://stackoverflow.com/q/38557951/206466

**Comment by wilkinsona** [comment]
I think this is a Spring Security issue. Spring MVC doesn't know anything about Spring Security and it feels like functionality that might be generally useful, rather than just of interest to people using Spring Boot.
