### ISSUE TITLE
Actuator BufferGaugeService discards all but most recent "timer" values

### ISSUE THREAD

**Issue by 56quarters** [spring-projects/spring-boot#6511]
Spring Boot Version: 1.4.1.BUILD-SNAPSHOT

## Description

Let me preface this by saying I'm not sure if it's a bug and I've worked around it by using `DefaultGaugeService`.

The seemingly correct way to submit timing metrics in Spring Boot Actuator appears to be using `GaugeService` and prefixing the metric name with "timer" (this might be an incorrect conclusion on my part).

In my application, I'm sending metrics to Statsd and JMX. When using `DefaultGaugeService`, "timer" metrics are immediately written to `StatsdMetricWriter` and then sent to Statsd and everything is good.

However, when using `BufferGaugeService`, metrics are buffered for `spring.metrics.export.delay-millis` milliseconds. This buffering (combined with the semantics of gauges) means that only the most recent value for each particular metric is sent. This is desireable and makes sense for gauge metrics. However, this is not great for timers. This means that only a single timing is send to Statsd per  `spring.metrics.export.delay-millis` period.

## To Reproduce

You can replicate this behavior by...

Running this Spring Boot project:

https://github.com/56quarters/metric-demo

Running netcat as a local UDP server:

```
netcat -l -u -p 8125
```

Hitting the index of the demo project a few times:

```
curl http://localhost:8080/
curl http://localhost:8080/
curl http://localhost:8080/
```

Observe that when metrics are flushed to the netcat server, only a single value for `metric-demo.timer.test` is sent.

## Expected

I expected multiple timer values for the timer to be sent to Statsd

## Actual

Only a single timer value (the most recent) was sent to Statsd.

Thanks!

**Comment by snicoll** [comment]
I don't want to give you a definitive answer (@dsyer surely knows better) but this seems to be working as advertized. The `GaugueService` records "one" value for a given metric. If you configure a delay in the export, this seems absolutely normal to me that only the last value is exported.

**Comment by dsyer** [comment]
Yes, a `GaugeService` only has to save the last value of every metric. If the `DefaultGaugeService` does something different I'm pretty surprised. The `DropwizardMetricServices` does treat `timer.*` in a special way (delegating to the underlying `Timer` data type), so maybe you are actually using that and didn't realize, if you are seeing something different.

**Comment by 56quarters** [comment]
I'm sure I'm using the `BufferGaugeService`, I was just expecting things prefixed with `timer.*` would be handled in a special way by all implementations of `GaugeService`. It sounds like that isn't part of the contract with `GaugeService`. Thank you for the feedback!
