### ISSUE TITLE
Upgrade Jackson to fix CVE 

### ISSUE THREAD

**Issue by benkiefer** [spring-projects/spring-boot#6512]
Can the Boot 1.3.x series update to at least jackson 2.7.4 to pull in their fix for a CVE?

For reference,
https://github.com/FasterXML/jackson-core/issues/292

**Comment by wilkinsona** [comment]
Unfortunately not. It's too big a change to jump from 2.6.x to 2.7.x in Boot 1.3.x. If you want to use a later version you should either override the `jackson.version` property in your pom or build.gradle or upgrade to Spring Boot 1.4 which was released yesterday.
