### ISSUE TITLE
HttpPutFormContentFilter and ServletServerHttpRequest.getBody() don't play nicely together

### ISSUE THREAD

**Issue by tapina** [spring-projects/spring-boot#6519]
`HttpPutFormContentFilter` makes PUT requests behave like POST requests with respect to parameters, and is enabled by default (https://github.com/spring-projects/spring-boot/issues/3643). This causes the body to be read in the filter.

`ServletServerHttpRequest.getBody()` treats POST requests specially and reconstructs a body from the parameters. But not for PUT (https://jira.spring.io/browse/SPR-8688).

If you map a form encoded PUT to a controller method (such as this one in Activiti) with `@RequestBody`, the body is null because the input stream has been read already and the PUTted parameters are not used to reconstruct a new one. This makes the controller useless in a Spring Boot 1.3+ environment.

`org.activiti.rest.editor.model.ModelSaveRestResource:`

```java
    @RequestMapping(
        value = {"/model/{modelId}/save"},
        method = {RequestMethod.PUT}
    )
    @ResponseStatus(HttpStatus.OK)
    public void saveModel(@PathVariable String modelId, @RequestBody MultiValueMap<String, String> values) {
```

Is there a way of disabling `HttpPutFormContentFilter`, or causing the request body to still be available even if it's there?

**Comment by philwebb** [comment]
There isn't currently a property to disable the `HttpPutFormContentFilter`. We'll add one.

**Comment by philwebb** [comment]
@tapina One more though, the `HttpPutFormContentFilter` is `@ConditionalOnMissingBean`. You could register your own `HttpPutFormContentFilter` subclass as a bean with an implementation that just calls `filterChain.doFilter(request, response);`

**Comment by wilkinsona** [comment]
A property would be more convenient, but you can already use a filter registration bean to disable it: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-disable-registration-of-a-servlet-or-filter

**Comment by tapina** [comment]
Andy - Thanks for the tip (and Phil, thanks for planning to add the flag). However, on reflection it does seem to me that the out of the box behaviour either ought to work completely for PUT (by having the filter set a flag on the request context which `ServletServerHttpRequest.getBody` then picks up and treats the same as a POST, or at the very least there ought to be a warning log output when controller methods are scanned (for any method which has the potential to receive a PUT `application/x-form-www-urlencoded` with a `@RequestBody` parameter). 

If the flag sounds reasonable I'll submit a pull request.
