### ISSUE TITLE
Add a hint that the exec jar main class is different

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#6522]
Spring boot 1.4's enhanced jar layout doesn't explicitly say that the main class is different than before. Ex it talks about moving the classes, but not the impact, which is the main class is now a constant value of `org.springframework.boot.loader.JarLauncher`

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#executable-jar-layout

This impacts those working around issues, who were unzipping the jar and executing the entrypoint of their application class, or otherwise using the exec jar in a classpath. Specifically, they need to change that code to the new `org.springframework.boot.loader.JarLauncher` entrypoint.

I could pretty quickly figure out what was wrong, and it made sense, but yeah. maybe we can be more explicit or link to something more explicit about this.

**Comment by philwebb** [comment]
I'm not sure I follow. The `org.springframework.boot.loader.JarLauncher` class hasn't moved and it should be possible to execute fat jars by unpacking them and running whatever the manifest MAIN-CLASS entry points to. What issues were you trying to work around? Can you point us at some code to show what you mean?

**Comment by adriancole** [comment]
well.. my only change to the build was updating the spring boot version,
and now my main class isn't under / (rather under BOOT-INF/classes/). So,
it broke the ability to reference the main class (as a normal jar, since a
normal classloader won't read BOOT-INF/classes/)

Ex. here I had to refactor the approach to find the "exec jar"
https://github.com/openzipkin/zipkin/commit/27686c6ec9bed77e254c2b0d527db25897d0e205#diff-99a5f5add3c99e64909ef92c5932977fR45

and here I had to change my Dockerfile
https://github.com/openzipkin/docker-zipkin/commit/cb16d351c89277425f67e9d0c3bcf94786efc03d

**Comment by wilkinsona** [comment]
The change to the Dockerfile needn't have modified the main class that's called. It could have continued to use `zipkin.server.ZipkinServer` and modified the class path to include `BOOT-INF/classes` and `BOOT-INF/lib/*`. Both those changes should be covered by the already documented changes to the jar layout.

The change to `ExecJarRule` feels like an edge case. You need to have a Spring Boot fat jar on the classpath (no really recommended) and be trying to get its location on the filesystem via the protection domain of the application's main class. I can't see how we can document this without confusing people by getting down into the weeds too much.

**Comment by adriancole** [comment]
fair enough. I mainly opened this as I experienced a break, not because I couldn't figure out how to work around it.
