### ISSUE TITLE
Release 1.4.0. Sample spring-boot-sample-actuator-log4j2 works but not as expected

### ISSUE THREAD

**Issue by DmitriBoulanger** [spring-projects/spring-boot#6523]
I am running your sample spring-boot/spring-boot-samples/**spring-boot-sample-actuator-log4j2**/,
**release 1.4.0**. The sample is git-cloned from your repository. So, i hope it exactly as it should be.
But i am getting always

**ERROR** StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

I have checked that all required dependencies are there. 
Could you please check or explain ....
And some relevant question.
Release 1.3.7.RELEASE had the artifact **org.springframework.boot:spring-boot-starter-log4j**
I cannot find similar one in the the RELEASE.1.4.0.  Are your not supporting **Log4j12** in the release 1.4.0?

Thank you so much
Dmitri Boulanger

**Comment by philwebb** [comment]
@DmitriBoulanger See the [release notes on the WIKI](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#deprecations-from-spring-boot-13
). Specifically:

> Log4j 1 support has been removed following Apache EOL announcement.

**Comment by philwebb** [comment]
As for `SampleActuatorLog4J2Application`, it appears to be working both on our CI system and locally within my IDE. Can you explain the exact steps to reproduce the problem?

**Comment by DmitriBoulanger** [comment]
Sorry for  a large delay with this answer. 
Even more, i bag your pardon for disturbances: the problem was at my local host.
I had a very dirty maven local repository.  I have cleaned it up, a now i have no problems any more
Please close the issue, and again, sorry for disturbances
