### ISSUE TITLE
Wrong new class reference in ServletRegistrationBean

### ISSUE THREAD

**Issue by ufoscout** [spring-projects/spring-boot#6524]
The org.springframework.boot.context.embedded.ServletRegistrationBean class was deprecated in Spring boot 1.4.0. The doc says:

> @deprecated as of 1.4 in favor of org.springframework.boot.web.ServletRegistrationBean

However, the correct path for the new class should be:
org.springframework.boot.web.servlet.ServletRegistrationBean

**Comment by snicoll** [comment]
Duplicates #6518
