### ISSUE TITLE
Spring Boot v1.4.0.RELEASE: Configuration for maven shade plugin references SNAPSHOT dependency

### ISSUE THREAD

**Issue by isarantidis** [spring-projects/spring-boot#6527]
The spring-boot-starter-parent pom.xml in v1.4.0.RELEASE includes a configuration for maven-shade-plugin with dependency on a SNAPSHOT version of spring-boot-maven-plugin.

**Comment by wilkinsona** [comment]
I believe I've fixed this in https://github.com/spring-projects/spring-boot/commit/a96af058820ed60a987072ae658d056292376680. Leaving this open as we should double-check during the release. We also need to remember to update it to 1.4.2.BUILD-SNAPSHOT as part of the manual post-release version updates.

**Comment by snicoll** [comment]
> We also need to remember to update it to 1.4.2.BUILD-SNAPSHOT as part of the manual post-release version updates.

It's not manual, it's automatic. `mvn  -P snapshot,prepare install -DskipTests` should re-apply the new version once the release is done. That step is part of the release check list so we should be fine.

**Comment by snicoll** [comment]
The shade plugin has the proper version in the staging area.

**Comment by snicoll** [comment]
[Looks good now](https://github.com/spring-projects/spring-boot/commit/97083300d74b463b8f176a51b752ff9dc067a9a2#diff-edb0abc04bb3963027a99f413bb26bebR173)
