### ISSUE TITLE
Invalid If-None-Match header results in stacktrace after 1.4 upgrade

### ISSUE THREAD

**Issue by tinexw** [spring-projects/spring-boot#6531]
Hi,

the behavior regarding ETag/If-None-Match header was changed in https://github.com/spring-projects/spring-framework/commit/55dae618a64da520d9154fe17f1529acab45873a

This leads to changed behavior in spring boot:
If a request contains an invalid entity tag in the If-None-Match header (e.g. without leading and trailing `"`) and results in an unrelated error, the stacktrace of this error is returned in 1.4.0.  In 1.3.7 the error was nicely formatted as a JSON object. 

### 1.3.7
````
curl -H "If-None-Match:bar" 'http://localhost:8080/foo'
```

````
{"timestamp":1470120731145,"status":404,"error":"Not Found","message":"No message available","path":"/foo"}
```

### 1.4.0
````
curl -H "If-None-Match:bar" 'http://localhost:8080/foo'
```

````
<!DOCTYPE html>
<html>
   <head>
      <title>Apache Tomcat/8.5.4 - Error report</title>
      <style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style>
   </head>
   <body>
      <h1>HTTP Status 404 - </h1>
      <div class="line"></div>
      <p><b>type</b> Status report</p>
      <p><b>message</b> <u></u></p>
      <p><b>description</b> <u>The requested resource is not available.</u></p>
      <hr class="line">
      <h3>Apache Tomcat/8.5.4</h3>
   </body>
</html>```

**Comment by bclozel** [comment]
I've created a [dedicated issue in Spring Framework for this|https://jira.spring.io/browse/SPR-14559], as Spring MVC should always respond with an HTTP 400 response in those cases, telling the client that the request is invalid.

I'm closing this issue now, as this will be fixed with #6561

Thanks for the report!
