### ISSUE TITLE
Auto-Configured JdbcSessionDatabaseInitializer initialization fails when using MSSQL

### ISSUE THREAD

**Issue by msal98** [spring-projects/spring-boot#6533]
Spring Boot Version: 1.4.0.RELEASE

I'm trying to use Spring Sessions to manage sessions, and when I use a MSSQL JDBC connection the session initializer fails. I am seeing the following error:

```
java.io.FileNotFoundException: class path resource [org/springframework/session/jdbc/schema-microsoft sql server.sql]
```

It looks like the initializer is attempting to create a `SPRING_SESSION` table in the database by running an external SQL script. The target script to be ran is determined dynamically based on the platform name. On my end the platform name is being returned as `microsoft sql server`. However, I only see a `schema-sqlserver.sql` script available.

Relevant code from the initializer:
```
// org.springframework.boot.autoconfigure.session.JdbcSessionDatabaseInitializer.java
...
String schemaLocation = this.properties.getJdbc().getSchema();
schemaLocation = schemaLocation.replace("@@platform@@", getPlatform());
populator.addScript(this.resourceLoader.getResource(schemaLocation));
...
```

There is a static map of database alias names in the initializer. I would think adding the the line below to the aliases would solve my issues:
```
...
aliases.put("microsoft sql server", "sqlserver");
...
```

**Edited, I didn't realize there was already a `schema-sqlserver.sql` script initially.

**Comment by vpavic** [comment]
@msal98 Thanks for the report - after taking a better look at this it seems I missed a few others besides SQL Server.

Will create a PR to address this soon.

**Comment by snicoll** [comment]
Closing in favour of the PR #6534
