### ISSUE TITLE
Documentation about testing with Spock is missing information

### ISSUE THREAD

**Issue by bendh** [spring-projects/spring-boot#6538]
Documentation enhancement
In the testing section it is said that Spock works with the `@SpringbootTest` annotation. This is not working with Spock 1.0. I created a sample project to demonstrate the issue and two solutions (with help from @dsyer). One solution is to use Spock 1.1 (Only RC available) or using deprecated test annotations and creating a `TestRestTemplate` bean as in `SpringBootTestContextCustomizer`.

Reproduction project:
https://github.com/bendh/springtestspockissue

I updated the documentation and can submit a pull request about this issue.

**Comment by philwebb** [comment]
Closing in favor of PR #6539

**Comment by philwebb** [comment]
Thanks!
