### ISSUE TITLE
Thymeleaf 3 template mode changed to HTML by default

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#6552]
please use HTML as default template mode if Thymeleaf 3 introduced. 

 [ main] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.

**Comment by wilkinsona** [comment]
Unfortunately, there's no easy way for us to differentiate between a user specifically setting `HTML5` and it simply being the default. That makes it tricky to know to change the default when Thymeleaf 3 is in use. I think our best option is to document that the mode should be explicitly configured to avoid the WARN message being produced and update our Thymeleaf 3 sample accordingly.
