### ISSUE TITLE
ErrorAttributes.getErrorAttributes is too restrictive

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#6555]
This is probably an Enhancement request.

The method `ErrorAttributes.getErrorAttributes(RequestAttributes requestAttributes, boolean includeStackTrace)` is a bit too restrictive for some uses. For example, I want to set a localized message in my custom `ErrorAttributes`. For that, I need the request locale, and to get the locale I need the `HttpServletRequest` itself, not just a `RequestAttributes`.

The best way to do what I want is to create a custom filter, call `request.setAttribute(..., locale)` from it, and get the locale back from `RequestAttributes.getAttribute(...)` inside `getErrorAttributes(...)`. But creating a filter for such a trivial case a bit too cumbersome.

I could also cast the `RequestAttributes` to `ServletRequestAttributes` and extract the request from it, but I'm not sure if that's supported or if it might break in the future:

```
if (requestAttributes instanceof ServletRequestAttributes) {
    locale = ((ServletRequestAttributes) requestAttributes).getRequest().getLocale();
}
```

I'm not sure how to best improve this without breaking backwards compatibility. I prefer it if the method had `HttpServletRequest` argument instead of `RequestAttributes`, but that's backwards-incompatible. Another idea is to add the `HttpServletRequest` as an attribute of `RequestAttributes`.

**Comment by mdeinum** [comment]
Wouldn't `((WebRequest) requestAttributes).getLocale()` achieve the same? It even has the benefit of plugging into the spring I18N support with the `LocaleResolver`, or simply doing `LocaleContextHolder.getLocale()` which would do the same. Both plug into the I18N support of Spring, whereas using only the request might even bypass that (imagine someone selected English but as you are using the local he gets his OS/browers preferred local which might be something else).

**Comment by imgx64** [comment]
The `RequestAttributes` instance I get is a `ServletRequestAttributes`, which is not a `WebRequest`. I'm not even sure it's safe to always cast it to `ServletRequestAttributes` or if it might break in the future.

`LocaleContextHolder` is an idea I haven't considered, but I prefer to use explicit arguments. Also, I think it doesn't work with async (I don't use async, but I might do so someday).

`MessageSource` still needs a `Locale` to actually get the message.

**Comment by philwebb** [comment]
I think ideally we'd pass in `WebRequest` rather than `RequestAttributes` but that will break back compatibility.

**Comment by philwebb** [comment]
@imgx64 We'll reconsider this around the 2.0 timeline but we're probably not going to want to change the `ErrorAttributes` interface in 1.x.

I would suggest you continue downcasting `RequestAttributes` to `ServletRequestAttributes`. That isn't likely to break in the foreseeable future and it will likely continue to work indefinitely as long as you are running on a Servlet container. The only problem you're likely to face is if you change to a different runtime once we've added support for Spring 5.0 reactive web module.
