### ISSUE TITLE
RichGauge Buffers implementation in spring-actuator metrics for Java8

### ISSUE THREAD

**Issue by countrogue** [spring-projects/spring-boot#6558]
In MetricRepositoryAutoConfiguration, there is a conditional for Java 8 which tells spring to create its own Buffers implementation instead of the legacy MetricsRepository. Is there a direct way of using RichGauge with Buffers or do we have to use the legacy repository for this?

**Comment by dsyer** [comment]
There is no Java8 native implementation of `RichGaugeRepository`, so there is no "legacy" as such. It's the same as it always was.
