### ISSUE TITLE
Consider adding DataJdbcTest

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6563]
Someone [asked on stackoverflow](http://stackoverflow.com/questions/38746788/what-is-the-equivalent-of-datajpatest-if-i-just-want-to-test-jdbctemplate-code) how to create their own test annotations. 

Looking around I could see at least that we could share the exclude filter. Maybe we could also include the jdbc template support itself? I am not sure if that's a common pattern.

**Comment by philwebb** [comment]
In the meantime it would make a great blog post!

**Comment by snicoll** [comment]
OK, I'll work on that.

**Comment by izeye** [comment]
Just out of curiosity, I thought with `@DataJpaTest` `Data` implies the Spring Data project but it looks I misunderstood as with `@DataJdbcTest` `Data` actually means a general word 'data', right?

**Comment by snicoll** [comment]
You're right Johnny, maybe the name of the annotation should change. I'll take that into consideration. Thanks!

**Comment by snicoll** [comment]
How about `JdbcTest` ?

**Comment by snicoll** [comment]
Alright I have a working solution but before I merge we need to discuss something a bit annoying

@philwebb @wilkinsona `AutoconfigureTestDatabase` is in the `orm.jpa` package and my `JdbcTest` is in the `jdbc` package. This commit has now a direct dependency to `orm.jpa`. Arguably, `AutoconfigureTestDatabase` would be better placed in the `jdbc` package (see `spring-boot-autoconfigure`) but that's quite a breaking change.

Thoughts?

**Comment by philwebb** [comment]
Seeing how `AutoConfigureTestDatabase` imports `org.springframework.boot.autoconfigure.jdbc.EmbeddedDatabaseConnection` I'd say you're right. We should move that annotation and deprecate it in 1.5.

We might be able to get away with meta-annotating the deprecated annotation with the new one.

**Comment by snicoll** [comment]
Reopen to remove deprecated code on master
