### ISSUE TITLE
1.4.0.RELEASE: TestRestTemplate has no methods for PATCH requests

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#6578]
TestRestTemplate has methods for GET, POST, PUT, DELETE, ...
However, I cannot find any method to test my RESTful PATCH interface.

**Comment by wilkinsona** [comment]
`TestRestTemplate` is modelled after Spring Framework's `RestTemplate` which also does not have any methods specifically for `PATCH` requests. I don't think we should break that consistency by adding Spring Boot-specific methods for `PATCH` requests.

If you need to make a `PATCH` request you should use `exchange` or `execute`.

**Comment by juergenzimmermann** [comment]
@wilkinsona a `PATCH` operation is added to `RestTemplate` in Spring 5.0.0.M4: https://jira.spring.io/browse/SPR-14857.
Do you see a chance to also add a `PATCH` operation to `TestRestTemplate` in a future release of Spring Boot?

**Comment by wilkinsona** [comment]
Yes, I do. In fact I've already done it: https://github.com/spring-projects/spring-boot/issues/7412
