### ISSUE TITLE
Upgrade to Spring Data Hopper SR3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6583]
It'll fix gh-6567.

**Comment by chrisburrell** [comment]
Will this fix https://jira.spring.io/browse/DATAJPA-938 If not, should I raise a new ticket in Spring boot as well to track this?

**Comment by wilkinsona** [comment]
That entirely depends on whether or not DATAJPA-938 is fixed in Hopper SR3. Either way, there's no need for a Spring Boot ticket.

**Comment by chrisburrell** [comment]
@wilkinsona cool - so long as people understand that upgrading to Spring 1.4 will break their code if they are using the 'new' constructor in JPA queries. I simply thought a separate ticket/this ticket would be helpful to track the fact there is a blocker in Spring boot
