### ISSUE TITLE
Back port 4352707e to 1.3.x for compatibility with Spring Framework 4.3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6592]
A user is hitting an NPE when trying to use Spring Framework 4.3 with Spring Boot 1.3: https://github.com/spring-io/platform/issues/414#issuecomment-238497715

**Comment by philwebb** [comment]
@wilkinsona Did you mean to close this one?

**Comment by wilkinsona** [comment]
Nope! Thanks
