### ISSUE TITLE
The "Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)" message is ambiguous.

### ISSUE THREAD

**Issue by agnul** [spring-projects/spring-boot#6593]
When running a spring-boot application with the maven plugin, an invalid configuration/missing dependency prints out the message 

    Error starting ApplicationContext. To display the auto-configuration 
    report enable debug logging (start with --debug)

so, of course, i re-run it adding the `--debug` flag on the command line. I get *tons* of debug information from the jvm and maven, but the spring error message stays the same and there's no auto-configuration report to be seen. Some time later I figure it out, set the logging level to `DEBUG`, get the report along with *lots* of other noise, and can go looking for the real issue thinking the error message could be clearer ;-)

(details: linux, java 1.8, maven 3.2, spring-boot 1.4)

**Comment by snicoll** [comment]
@agnul it's unfortunate. `--debug` was meant to "our" bootstrap (`java -jar`). It's actually a hint to set the "debug" property. We'll change the error message.

**Comment by philwebb** [comment]
I've slightly tweaked the error message to remove the link to the documentation. I think it's probably better not to include the documentation URL. Hopefully it will be quite natural for people to search the documentation if they don't understand the message.

**Comment by KhayelihleS** [comment]
Hi. I got the similar error but i cant solve it Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-06-06 13:59:03.960 ERROR 9188 --- [ main] o.s.boot.SpringApplication    : Application run failed
