### ISSUE TITLE
Spring boot supports Java 6, yet the the dependency management plugin doesn't

### ISSUE THREAD

**Issue by sancho21** [spring-projects/spring-boot#6594]
Even though Spring boots support Java 6. Why the dependency management on spring-boot plugin is compiled into Java 7? There's no point this way.

When I compiled my code with Java 6, I got this:

```
* What went wrong:
A problem occurred evaluating root project 'hello-calculator'.
> io/spring/gradle/dependencymanagement/exclusions/Exclusions : Unsupported major.minor version 51.0
```

**Comment by wilkinsona** [comment]
We could certainly look at dropping the dependency management plugin's Java version to Java 6. However, is there anything stopping you from using Java 7 (or later) at build time with the source and target compatibility set to 1.6?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sancho21** [comment]
That means, I still have to specify my bootclasspath pointing to Java 6,
right?

**Comment by wilkinsona** [comment]
No, you don't have to, although Gradle will output a warning.

**Comment by sancho21** [comment]
But, that's considered dangerous. I might use non-existent methods or
classes.

**Comment by aravindmangu** [comment]
Hi, is it possible to drop the dependency management plugin's Java version to Java 6 as it is mandatory for us to use Java 6 in out project ?

**Comment by wilkinsona** [comment]
Yes. See https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/106

**Comment by philwebb** [comment]
We'll pick this up when #6810 is fixed and we upgrade.
