### ISSUE TITLE
Spring Boot profiles not active when set with maven plugin

### ISSUE THREAD

**Issue by Siflei** [spring-projects/spring-boot#6595]
Hi,
I'm trying to set spring profiles when starting Tomcat for integration tests in maven like this:

    ...
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
      <executions>
        <execution>
          <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
            <configuration>
              <profiles>
                <profile>testProfile</profile>
              </profiles>
            </configuration>
    ...

The profile is definitely not active.

On the other hand the following does work and the requested profile is active:
    `<jvmArguments>-Dspring.profiles.active=testProfile</jvmArguments>`
The problem here is that we can't stop the server, which is a problem when running automated integration tests.

I'm using spring boot "1.4.0.RELEASE".

Did we find a bug here?

**Comment by php-coder** [comment]
You question is very similar to mine own a couple month ago: http://stackoverflow.com/questions/34687154/application-test-properties-isnt-loaded-when-activating-profiles-with-profiles Most likely it's the same and it's not a bug.

**Comment by Siflei** [comment]
Thank you for your hint. Sadly that's not case here. I'm not trying to run the tests but the app with the profile. And the app is run with "<goal>start</goal>".

**Comment by wilkinsona** [comment]
@Siflei If you are literally running `mvn spring-boot:start` then that's not going to work as the profile configuration in your pom will have no effect. You need to run `mvn integration-test` or similar. If that's already what you are doing then please provide a small sample that reproduces the problem.

**Comment by Siflei** [comment]
I'm running "mvn install -P ITest" (where ITest is my maven profile).
This is an extract of my pom:

<profiles>
        
        <profile>
            <id>ITest</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <groups>de.mnet.pallas.category.IntegrationTests</groups>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>pre-integration-test</id>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                                <configuration>
                                    <profiles>
                                        <profile>testProfile</profile>
                                    </profiles>
                                    
                                </configuration>
                            </execution>
                            <execution>
                                <id>post-integration-test</id>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

Does this help? What else do you need?

**Comment by wilkinsona** [comment]
> Does this help?

Not really, no. If I add your profile to one of our samples, it works as expected:

```
$ mvn install -PITest
…
[INFO] --- spring-boot-maven-plugin:1.4.0.RELEASE:start (pre-integration-test) @ spring-boot-sample-web-freemarker ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2016-08-09 13:34:50.333  INFO 85880 --- [lication.main()] s.f.SampleWebFreeMarkerApplication       : Starting SampleWebFreeMarkerApplication on aw-rmbp.home with PID 85880 (/Users/awilkinson/dev/spring/spring-boot/master/spring-boot-samples/spring-boot-sample-web-freemarker/target/classes started by awilkinson in /Users/awilkinson/dev/spring/spring-boot/master/spring-boot-samples/spring-boot-sample-web-freemarker)
2016-08-09 13:34:50.336  INFO 85880 --- [lication.main()] s.f.SampleWebFreeMarkerApplication       : The following profiles are active: testProfile
…
```

> What else do you need?

As I said above, a small sample that reproduces the problem.

**Comment by Siflei** [comment]
[profileTest.zip](https://github.com/spring-projects/spring-boot/files/408958/profileTest.zip)
Here's a fragment of my app. You can easily see which profile is used by checking what banner.txt is shown.
The only (real) difference in the property files right now is the line:
spring.application.admin.enabled=true
We need this to be true in integration tests, otherwise false. So when running `mvn install -P ITest` the tests runs into a timeout because spring.application.admin.enabled is false (because testProfile instead of itestProfile is actve).

I'm really curious if you can reproduce this problem.
Thank you very much for your help!

**Comment by wilkinsona** [comment]
Your main method is ignoring the arguments that are passed into the app so it's ignoring the active profile. You need to pass the args into the call to `SpringApplication.run`:

```java
public static void main(String[] args) throws Exception {
    SpringApplication.run(RunServer.class, args);
}
```

**Comment by Siflei** [comment]
That simple! I feel stupid now. :-)
I'm glad it's not a bug in Spring!
Thank you very much for your help!

**Comment by philwebb** [comment]
@Siflei for what it's worth I've made the same mistake once or twice myself during demos.
