### ISSUE TITLE
Charset support in JsonLoader

### ISSUE THREAD

**Issue by danielrohe** [spring-projects/spring-boot#6597]
The class `JsonLoader` (`org.springframework.boot.test.json.JsonLoader`) creates an `InputStreamReader` without charset to read the json file. This causes problems where the system encoding is different. This causes test cases with special characters in the json file to fail on systems where the default encoding is e.g. `ISO-8859-1`. Can you either provide methods to define the charset or use a predefined charset?

**Comment by wilkinsona** [comment]
AFAIK, JSON is specified as always being UTF-8 so would should be able to hardcode it.

**Comment by wilkinsona** [comment]
Nope, [it can also be UTF-16 or UTF-32](https://tools.ietf.org/html/rfc7159#section-8.1). UTF-8 is just the default.

**Comment by danielrohe** [comment]
thanks for fixing it, we are awaiting the new version :+1:
