### ISSUE TITLE
Spring Boot 1.4 upgrade results in sun.misc.InvalidJarIndexException

### ISSUE THREAD

**Issue by markathomas** [spring-projects/spring-boot#6601]
Hello, I upgraded Spring Boot from 1.3.7 to 1.4.0 today.  The upgrade went smoothly until I attempted to run the Jar file (e.g. java -jar foo.jar).  Attempting to run the code resulted in `sun.misc.InvalidJarIndexException: invalid index`.  I reverted back to 1.3.7 and the problem went away,.

**Comment by markathomas** [comment]
For reference, I am running 64-bit Linux with 

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by wilkinsona** [comment]
Do you have a `META-INF/INDEX.LIST` file in the jar? If you do, I guess it could be a side-effect of repackaging in 1.4 moving classes from the root of the jar into `BOOT-INF/classes`. Assuming my hunch is correct, switching off the creation of the index should avoid the problem.

**Comment by markathomas** [comment]
yes, that did it! thanks for the help!

**Comment by philwebb** [comment]
Might be worth throwing a tip in the docs about this.

**Comment by wilkinsona** [comment]
For reference, here's the documentation for a jar index: http://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#JAR_Index. It sounds like it won't have any benefit in a Spring Boot app. I wonder if we could update the repackager to automatically remove the index?

**Comment by snicoll** [comment]
Given the exception that arises, I think we should do it.

**Comment by philwebb** [comment]
+1 to removing it automatically.
