### ISSUE TITLE
commons-lang in spring-boot-dependencies

### ISSUE THREAD

**Issue by Tomschi** [spring-projects/spring-boot#6603]
Is it possible to add commons-lang to spring-boot-dependencies?

**Comment by wilkinsona** [comment]
Spring Boot only provides dependency management for projects that it uses or provides auto-configuration for. Commons Lang doesn't satisfy those criteria. If you're interested in broader dependency management then take a look at the Spring IO Platform. It contains a superset of Boot's dependency management and includes `commons-lang`.
