### ISSUE TITLE
Possibility to specify custom dataSource configuration for liquibase only

### ISSUE THREAD

**Issue by mariuszs** [spring-projects/spring-boot#6604]
Please add an option to `LiquibaseProperties` to specify custom `dataSource` configuration for liquibase only, currently there is only way to specify url or username and password.

**Comment by snicoll** [comment]
> custom dataSource configuration

What custom configuration do you have in mind?

**Comment by mariuszs** [comment]
Company infra requires maximum pool size setted to 1 for liquibase connection

    dataSource.setMaximumPoolSize(1);

**Comment by philwebb** [comment]
I'm not keen to add more properties to Liquibase but it would be good to support a programmatic way to configure this. Perhaps we should consider something like the `@FlywayDataSource` annotation.

**Comment by mariuszs** [comment]
:+1: Good idea, this is what Im trying to do now, specify second datasource with qualifier and inject into springLiquibase bean.
