### ISSUE TITLE
Register MessageSourceAutoConfiguration for @WebMvcTest

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6608]
See http://stackoverflow.com/questions/38876235/unit-testing-of-spring-boot-application-with-freemarker-throws-nosuchmessageexce

I think the root cause is we don't register `message.properties` support.

**Comment by Irgalin** [comment]
[https://github.com/Irgalin/klarigo/tree/unit-testing-ussue](Here) I created branch which fixed the state of my simple project that replicates this issue.  The `src/test/java/ru/klarigo/controllers/VideoControllerTest.java` won't pass if `MessageSourceAutoConfiguration` is not explicitly imported.

**Comment by philwebb** [comment]
Thanks @Irgalin!
