### ISSUE TITLE
NoUniqueBeanDefinitionException when trying to use the Actuator with multiple Flyway or Liquibase beans

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6609]
http://stackoverflow.com/questions/38876430/spring-boot-actuator-flywayendpoint-doesnt-work-with-multiple-flyway-beans.

The endpoint requires a single `Flyway` bean and even when the endpoint is disabled (`endpoints.flyway.enabled=false`) the bean itself is still created and it fails with a `NoUniqueBeanDefinitionException`.

We should consider making it `@ConditionalOnSingleCandidate` in 1.4.x and then perhaps supporting multiple Flyway beans in 1.5.

**Comment by wilkinsona** [comment]
The Liquibase endpoint has the same problem

**Comment by dnno** [comment]
May I say that you folks rock! :-) Thanks for the fix, I'm looking forward to the next release! Keep up the good work!
