### ISSUE TITLE
SpringSecurityDialect not added automatically

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#661]
When having dependency to both spring-boot-starter-security and spring-boot-starter-thymeleaf starters I would expect the SpringSecurityDialect  is autoconfigured, but this is not the case.

**Comment by zsy056** [comment]
SpringSecurityDialect not added automatically when use with thymeleaf-extras-springsecurity4

**Comment by dsyer** [comment]
This issue has been closed for almost a year. If you need a new feature, please open a new one or (better still) a pull request.
