### ISSUE TITLE
Support multiple beans in the Flyway and Liquibase endpoints

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6610]
See http://stackoverflow.com/questions/38876430/spring-boot-actuator-flywayendpoint-doesnt-work-with-multiple-flyway-beans and #6609

**Comment by eddumelendez** [comment]
@wilkinsona I have submitted #6613 but I think that we can extract Flyway and Liquibase Configuration from `EndpointAutoConfiguration` and create a dedicated classes for those. It is something similar to `JolokiaAutoConfiguration`.

WDYT?

**Comment by wilkinsona** [comment]
In my opinion, given that it's only a single method, there's no need for a dedicated class

**Comment by snicoll** [comment]
Closing in favour of the PR #6613
