### ISSUE TITLE
Access log issue after rotate

### ISSUE THREAD

**Issue by ulisses79** [spring-projects/spring-boot#6618]
My application uses two undertow containers. One for regular business logic and the second one for actuators. There are two listeners at ports: 8080 and 8090 (actuators set via `management.port` property).

Observed behavior: in the access log we can see entries coming from both containers. Regular traffic and requests for `/health` resources that come from load-balancer.

Issue: at midnight when access log rotation takes place (at least we observe that at midnight) we ended up with three files: `access.log`, `access-log.{date}.log` and `access-log.{date}-1.log`.

Health entries are still visible in access.log and the file is growing. Regular traffic entries go to the last file. 

It seems like there's a race condition when two containers attempt to rotate one common access.log file.

Spring version 1.3.0.RC1 and Undertow-core-1.3.0.Final

**Comment by philwebb** [comment]
Spring Boot 1.3.0.RC1 is quite old, have you seen the same problem with the latest 1.3 release?

**Comment by ulisses79** [comment]
Recently we have upgraded Spring Boot to 1.3.6.RELEASE and we observe the same results. Access.log stops recording the regular traffic.

**Comment by wilkinsona** [comment]
I think the root of the problem is that we have two Undertow deployments using the same access log file. When the Actuator's running on a separate port it needs to use a separate access log file too. Also, as far as I can tell, Tomcat has the same problem too.

**Comment by wilkinsona** [comment]
The current logic to reuse the same access log appears to be deliberate (see #1581) but I don't think it makes sense. I think we should use the same directory, but not the exact same file names.

**Comment by ulisses79** [comment]
Ok, Looking forward to seeing this issue resolved in the upcoming releases.

**Comment by wilkinsona** [comment]
@ulisses79 I've fixed this in 1.4.1 (it uses the new properties added in #6652. That change was a bit too big for 1.3.x). If you want to stick on 1.3.x and avoid the problem, you can do so by configuring access logging manually. To do so, don't set `server.undertow.accesslog.enabled` and use an `UndertowDeploymentInfoCustomizer` instead to configure the access log.

**Comment by ulisses79** [comment]
Thank you!
