### ISSUE TITLE
Banner application properties not injected when running "mvn spring-boot:run"

### ISSUE THREAD

**Issue by ajmair01** [spring-projects/spring-boot#6619]
When running a Spring Boot application via the maven command `mvn spring-boot:run`, or from the autoconfigured IntelliJ run configuration, the properties `application.title`, `application.version`, etc. are not injected into my banner.txt.

They are correctly injected if I run the project via `java -jar myPackagedJarOrWar`.

**Comment by philwebb** [comment]
I'm afraid that's a known limitation of the build system and IDE. Those values are taken from `META-INF/MANIFEST.MF` which is usually only written when the jar is packaged.
