### ISSUE TITLE
Revisit complex type merge logic

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6620]
In #4313 we changed the way that complex types are merged but this has an impact on the legitimate use-case described in https://github.com/spring-cloud/spring-cloud-config/issues/466.

We need to rethink things again.

**Comment by marcellodesales** [comment]
@philwebb thanks for looking into this...

**Comment by marcellodesales** [comment]
Here's another bug that I opened a while ago... When complex types are used, all values MUST have encryption or else it fails.

https://github.com/spring-cloud/spring-cloud-config/issues/452

**Comment by philwebb** [comment]
I don't think there's a way for us to fix this without introducing regressions. I've reopened the Spring Cloud issue to see if we can fix it there.

**Comment by marcellodesales** [comment]
@philwebb thanks for looking into this... I will keep an eye on  https://github.com/spring-cloud/spring-cloud-config/issues/466
