### ISSUE TITLE
@RequestBody Mono<Type> t and @RequestBody Type t parameters not working

### ISSUE THREAD

**Issue by FWiesner** [spring-projects/spring-boot#6625]
I followed the example under https://github.com/bclozel/spring-boot-web-reactive and got a reactive service working yesterday.

I then extended the example today to also take a Person object as parameter or body content. This leads to the problem that the method is no more called and internal logs from reactor pop up:

https://gist.github.com/FWiesner/79b56b269137925812ee827b7d74acf8

Here's the method I wrote (Person is a simple POJO):
https://gist.github.com/FWiesner/5e70b355c5f69206684aa2ff3c4a591e

The issue occurs both with Tomcat and Netty and also when I do not wrap the person parameter in a Mono.

**Comment by FWiesner** [comment]
oh and not reusing the parameter Mono does not make a difference.

return Mono.just(new Person(..));

also shows the same behavior

**Comment by snicoll** [comment]
Duplicates https://github.com/bclozel/spring-boot-web-reactive/issues/16
