### ISSUE TITLE
Improve property validation example to not use static runner class

### ISSUE THREAD

**Issue by lnunno** [spring-projects/spring-boot#6627]
It would be nice if the [Spring property validation example here.](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-property-validation/src/main/java/sample/propertyvalidation/SamplePropertyValidationApplication.java)

Did not use a static runner class to demonstrate whether or not this is required. I have a StackOverflow question [here that documents the issues I've been having.](http://stackoverflow.com/questions/38899990/spring-boot-autowired-configuration-only-null-when-validator-bean-used)

**Comment by philwebb** [comment]
I've answered your stackoverflow question but we should also make some updates here. I think the sample should use a static `configurationPropertiesValidator` bean method and we should add some warnings to the documentation.
