### ISSUE TITLE
certain RestController PathVariable expressions may be broken with spring-cloud-starter-eureka

### ISSUE THREAD

**Issue by bitsofinfo** [spring-projects/spring-boot#6629]
Not sure the best folks to tackle this, but its a blocker for me right now:

https://github.com/bitsofinfo/spring-boot-cloud-eureka-path-variable-issue

I have a `@RestController` that looks like this:

```
@RestController
public class TestRESTController {

	@RequestMapping(value="/my/custom/path/{id:.+}", 
			method=RequestMethod.GET,
			produces=MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<? extends Object> resolveAccessor(@PathVariable String id) {
		return new ResponseEntity<String>("i got here " + id,HttpStatus.OK);
	}
	
}
```

When my project includes `compile 'org.springframework.cloud:spring-cloud-starter-eureka'`

I get a 406 back, when the PathVariable contains an email address.

When my project does not include `spring-cloud-starter-eureka` I get the expected response back

See this simple example for a runnable version. README has the details

https://github.com/bitsofinfo/spring-boot-cloud-eureka-path-variable-issue

**Comment by philwebb** [comment]
I see you've also raised it on the spring-cloud issue tracker. That feels like the best place so I'll close this one for now. If it turns out to be a Boot issue we'll reopen it.
