### ISSUE TITLE
Builder support for OAuth2RestTemplate

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6631]
OAuth2 support has a specialized `OAuth2RestOperations` that we no longer auto-configure (as a general alignement on the new `RestTemplateBuilder` stuff). 

There's no way to easily create an instance of that thing. Maybe we should provide a specialized builder? In an ideal world, we wouldn't have a dedicated rest template only for oauth opreations (the extended interface has 3 getters so maybe it could go somewhere else?).

ping @dsyer

**Comment by dsyer** [comment]
> no way to easily create an instance of that thing

Actually I'd say it was pretty easy to create (there's a constructor that accepts things that can be auto-wired in a Boot app). But I think you actually mean: once an instance is created from the constructor, there's no way for it to participate in the general 'customization' that Boot applies to `RestTemplates` created by the builder we provide.

The 3 extra methods in the interface don't provide huge value really, and aren't commonly used. If a user needs access to those objects he usually has the option to inject them. That's true for 2 out of 3 anyway (the exception is `getAccessToken()` but I'd argue that was even less commonly used). If there's a way to provide a `RestOperations` (or `RestTemplate`) in a uniform way that harmonises with the "normal" usage of the builder, I'd say it's worth doing. The builder lives in Spring Boot, and there's no natural dependency on OAuth2 there, so I suppose the hard question is how to finesse the API without introducing unnecessary dependencies.

**Comment by snicoll** [comment]
> I think you actually mean

Yes and no. First of all, you need to be aware there's such thing as `OAuth2RestTemplate` and then figure out that you actually can autowire the 2 dependencies. If you compare that with the developer experience you get with `RestTemplateBuilder` it's not nothing IMO. But you are also right, the biggest issue is that oauth2 doesn't participate in the global customizations that boot provide.

One thing we could do then is to improve the `RestTemplateBuilder` auto-configuration to be aware of OAuth2 and offer a `enableOAuth2` builder method?

**Comment by dsyer** [comment]
Wouldn't `enableOAuth2()` have to be defined in a class that doesn't naturally depend on OAuth2? If you can find a way to handle that cleanly, I think it would be a nice feature (the builder would still return a normal `RestOperations`).

**Comment by wilkinsona** [comment]
Boot's OAuth support has been removed in 2.0 in favour of the OAuth support that's coming in Spring Security 5.x.
