### ISSUE TITLE
HealthMvcEndpoint only use deprecated property "role"

### ISSUE THREAD

**Issue by renierr** [spring-projects/spring-boot#6632]
Spring Boot 1.4.0.RELEASE

in health endpoint the checks only the deprecated management.security "role" property instead of the new "roles"

in class: HealthMvcEndpoint
line: 187
`String role = this.roleResolver.getProperty("role", "ROLE_ADMIN");`

**Comment by wilkinsona** [comment]
Duplicates #6540
