### ISSUE TITLE
CaffeineCacheConfiguration does not load Caffeine

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#6656]
If a project add the dependency to Caffeine, CaffeineCacheConfiguration does not detect Caffeine libraries in the classpath and SimpleCacheConfiguration is started as default cache. 

CaffeineCacheConfiguration should be enabled during startup.

**POM**
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
		</dependency>
```

**Comment by snicoll** [comment]
Which version of Spring Boot are you using? I have several samples with that exact same pom and they work out-of-the-box.

**Comment by ofbizbrazil** [comment]
The last one, I mean 1.4.0

**Comment by snicoll** [comment]
And I get it now. You probably don't have `@EnableCaching` on your app. [Reading the doc should help](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_supported_cache_providers). And please share an example (or more details) right the way next time.

**Comment by ofbizbrazil** [comment]
No, I have it @EnableCaching. Could you verify?

**Comment by snicoll** [comment]
Nope sorry. You're not giving us anything to investigate. Share a minimal sample that reproduces the problem and we'll have a look.

**Comment by ben-manes** [comment]
[spring-boot-sample-cache](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache) works for me. I added Caffeine to the pom.xml (accidentally not listed) and when running `mvn test` the following message appears,
```
=========================================================
Using cache manager: org.springframework.cache.caffeine.CaffeineCacheManager
=========================================================
```

The test runs successfully. If I set the configuration to,
```properties
spring.cache.caffeine.spec=expireAfterAccess=0s
```
Then the test fails because the value wasn't cached.

So the only change to the sample that you need is to add the dependency to the pom.
```xml
<dependency>
  <groupId>com.github.ben-manes.caffeine</groupId>
  <artifactId>caffeine</artifactId>
  <version>2.3.2</version>
</dependency>
```

**Comment by snicoll** [comment]
@ben-manes good catch Ben, thanks! I've added a reference to caffeine in https://github.com/spring-projects/spring-boot/commit/96d5def17de4cf4dbeaa3d8e744230cf22d2e93e (you don't need to specify any version, boot is taking care of that).

**Comment by ofbizbrazil** [comment]
Do I need to add JCache for Caffeine to work? EHcache3 needs for it and in current example, this not clear.

**Comment by snicoll** [comment]
@ofbizbrazil this issue tracker is not a support forum. You already got several indications that the caffeine support should work given the information you've provided. Feel free to share a sample that breaks and we'll have a look.
