### ISSUE TITLE
How to test a controller with the validation at Spring Boot 1.4+

### ISSUE THREAD

**Issue by WildDeveloper** [spring-projects/spring-boot#6658]
#Question

Spring Boot 1.4 has a number of fine features including `@DataJpaTest` annotation that automatically wakes up the classpath embedded database for the test purposes. As far I know, it won't work in conjuction with `TestRestTemplate` in bounds of the same class.

The following test won't work:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@DataJpaTest
public class PersonControllerTest {

    private Logger log = Logger.getLogger(getClass());

    private Category category;

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    private TestEntityManager entityManager;

    @Before
    public void init() {

        log.info("Initializing...");

        category = entityManager.persist(new Category("Staff"));
    }

    @Test
    public void personAddTest() throws Exception {

        log.info("PersonAdd test starting...");

        PersonRequest request = new PersonRequest("Jimmy");

        ResponseEntity<String> response = restTemplate.postForEntity("/Person/Add", request, String.class);
        assertEquals(HttpStatus.OK, response.getStatusCode());

        log.info("PersonAdd test passed");
    }
```

During startup of the test an exception will be thrown:

`Unsatisfied dependency expressed through field 'restTemplate': No qualifying bean of type [org.springframework.boot.test.web.client.TestRestTemplate]`

Then guessing to switch to the recommended mock based _slice_ approach but it won't work there because the controller looks like this:

```
@RequestMapping(value="/Person/Add", method=RequestMethod.POST)
public ResponseEntity personAdd(@Valid @RequestBody PersonRequest personRequest, Errors errors) 

     personValidator.validate(personRequest, errors):

     if (errors.hasErrors())
         return new ResponseEntity(HttpStatus.BAD_REQUEST);

     personService.add(personRequest);

     return new ResponseEntity(HttpStatus.OK);
}
```
... it's easy to mock the `personService` as the documentation suggests but how to be with the `errors` object which is not mockable in this case? As far I know, there's no ways to mock it since it isn't class field or a returned value of a method.

So, I'm unable to test the code above using neither _slice_ approach nor integration one since `@DataJpaTest` should not be used with a controller.

Is there a way to test the controller with such architecture using Spring Boot 1.4 testing features?

**Comment by snicoll** [comment]
You lost me. Your test doesn't show the use of `TestRestTemplate`  at all. And `@DataJpaTest` should not be used with a controller. Can you please rephrase the problem because the title doesn't match the description IMO.

**Comment by WildDeveloper** [comment]
Have added the test example and several addional details.

Actually, the only I want is to test the controller I've shown above without touching a real (not-embedded) database but have no idea how.

**Comment by snicoll** [comment]
`@DataJpaTest` is meant to test the data layer. You're trying, in the same test, to invoke a controller. That's not slicing at all. You need to separate those tests or mark that test with `@SpringBootTest` and not use slicing.

Please consider asking questions on stackoverflow next time: we prefer to use this tracker for enhancements and bug reports.
