### ISSUE TITLE
Add beans created using `@MockBean` as singletons rather than via a bean definition

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6664]
When registered via a bean definition the mock is subject to post-processing. This includes creation of proxies for caching and async processing. It also means that the container attempts to autowire the mock's fields (if it was created from a class rather than an interface). We could avoid this by adding the bean to the bean factory as a singleton.

**Comment by wilkinsona** [comment]
I think registering as a singleton would mean that we need a different fix for #6602

**Comment by wilkinsona** [comment]
Other than #6602, this approach looks quite fruitful. Here's [a prototype](https://github.com/spring-projects/spring-boot/compare/master...wilkinsona:gh-6664) that addresses numerous `@MockBean`-related issues. See the commit comments for details.

**Comment by snicoll** [comment]
Fixed in https://github.com/spring-projects/spring-boot/commit/0e00a49dcc246893fcaf1c7a0497fac6dcbc7454
