### ISSUE TITLE
Make "MaxSwallowSize" more easily configurable

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-boot#6669]
This is relevant for larger file-uploads and is hard to trace and may cause errors in your browser like `The connection was reset.`

The following StackOverflow post provides a solution:

http://stackoverflow.com/questions/35748022/multipart-file-maximum-size-exception-spring-boot-embbeded-tomcat

It would be good if Spring Boot would support this out of the box using:

`spring.http.multipart.max-swallow-size`

Ideally, the Boot `MultipartProperties` should also be smart enough so that a `max-file-size` or `max-request-size` that is larger than the `max-swallow-size` will either throw an error/warning or implicitly increase the `max-swallow-size` (Not sure if there are edge-cases against it, though.)

Also,  document the issue in the reference guide.

**Comment by wilkinsona** [comment]
The swallow size isn't specific to file uploads. It's for any request with a large body. From the Tomcat docs:

> The maximum number of request body bytes (excluding transfer encoding overhead) that will be swallowed by Tomcat for an aborted upload. An aborted upload is when Tomcat knows that the request body is going to be ignored but the client still sends it. If Tomcat does not swallow the body the client is unlikely to see the response. If not specified the default of 2097152 (2 megabytes) will be used. A value of less than zero indicates that no limit should be enforced.

As such, it doesn't make sense for it to be a multipart property

Note that it's also only for an aborted upload so I'm not sure that it necessarily makes sense to enforce any relationship between the swallow size and the max file/request sizes for multipart uploads.

**Comment by philwebb** [comment]
We could add this under `server.tomcat.` but it's a balance of how many of those we should add. You can do this with a `TomcatConnectorCustomizer` already.

**Comment by snicoll** [comment]
Closing in favour of PR #13966
