### ISSUE TITLE
Can spring cloud config merge arrays from different property sources into a single one?

### ISSUE THREAD

**Issue by soiff** [spring-projects/spring-boot#6670]
This question is moved from Spring SC Config issues. Please have a look, thanks ahead!

As I mentioned in the title.

Typically, I got several configurations, for example one.yml and two.yml, both defined key rpc.consumers, which is an array of objects.

For example:

# one.yml
rpc:
  consumers:
    - type: a.b.c.Consumer0

# two.yml
rpc:
  consumers:
    - type: x.y.z.Consumer0

Actually, I need merge these two arrays into a single one, could spring cloud config achieve this?

**Comment by wilkinsona** [comment]
Duplicates #6620

**Comment by wilkinsona** [comment]
Not at the moment, although we're looking at a way to make it work. See the duplicate issue and other issues it references for details.

**Comment by soiff** [comment]
Ok, thanks!
