### ISSUE TITLE
Consider using DriverManager.getDriver(jdbcUrl) to detect the driver to use

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6675]
See https://github.com/brettwooldridge/HikariCP/issues/701#issuecomment-240415748

**Comment by philwebb** [comment]
Keyworkds: driver jdbc url

**Comment by philwebb** [comment]
We're worried that this would cause side effects or break existing users.

**Comment by nmck257** [comment]
I'd like to re-raise this for consideration. The JDK `DriverManager` model seems well-established for this exact purpose, and HikariCP has been using it successfully for years.

Previous comments on this issue were brief; do we recall more-specific potential side effects?
From my perspective, the effort of the change would be small, and the breaking change in behavior doesn't seem unreasonable for a future release line upgrade.

**Comment by wilkinsona** [comment]
In the 8 years since Brett's comment, the hypothetical concern that it raises hasn't, to our knowledge, been a problem. As such, with no known benefits to changing, it's very hard to justify doing so.

**Comment by wilkinsona** [comment]
While Hikari's the default connection pool, we support others. As such, we can't always defer the setup logic to Hikari and I don't think we'd want to do so some of the time as the change in behavior when changing the connection pool would be confusing. I continue to believe that maintaining the status quo is the best option here.
