### ISSUE TITLE
1.4 breaks Tomcat Loadbalancing

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#6679]
To support Tomcat  AJP with modjk (sticky sessions with LB), current practice is shown below.  To quickly verify - it is as simple as looking at JSESSIONID cookie in the browser - the cookie value is appended with the JVM_ROUTE.  Apache httpd/modjk fails to route to jvm (it basically sees no cookie and round robins).

Works in all preceding SpringBoot versions, but broken in Boot 1.4. 

````
@Bean
public EmbeddedServletContainerFactory servletContainer() {
	TomcatEmbeddedServletContainerFactory tomcatFactory = new TomcatEmbeddedServletContainerFactory();

	logger.debug( "Customizing tomcat factory" ); 

	// https://tomcat.apache.org/tomcat-8.0-doc/config/http.html
	tomcatFactory.addAdditionalTomcatConnectors( createAjpConnector() );
...
}

private Connector createAjpConnector() {

	String jvmRouteForModJk = getContextPath() + "_" + getHttpPort() + HOST_NAME  ;

	System.setProperty("jvmRoute", jvmRouteForModJk);
	logger.debug( webServerInfo.toString() );

	Connector connector = new Connector( "org.apache.coyote.ajp.AjpNio2Protocol" );
	connector.setScheme( "http" ); // this is used in redirects - and spring security only supports http(s)
````

**Comment by peterdnight** [comment]
After reviewing the notes: i am once again able to enjoy the 1.4 goodness. I am suspecting the new tomcat 8.5 connectors forgot support for the -DjvmRoute as noted at https://tomcat.apache.org/tomcat-8.5-doc/config/engine.html 

````
	<properties>
		<!-- Defaults from csap-starter to java 8 -->
		<tomcat.version>8.0.33</tomcat.version>
	</properties>

<dependency>
        <groupId>org.apache.tomcat</groupId>
        <artifactId>tomcat-juli</artifactId>
        <version>${tomcat.version}</version>
    </dependency>
````

**Comment by wilkinsona** [comment]
@peterdnight Thanks for the analysis. Look like we can fix this by setting the session id generator on the manager earlier. That way it'll be configured when `ManagerBase.startInternal()` is called and will have the various attributes configured on it.

**Comment by wilkinsona** [comment]
I think this bean will work around the problem in 1.4.0:

```java
@Bean
public EmbeddedServletContainerCustomizer tomcatCustomizer() {
	return (container) -> {
		if (container instanceof TomcatEmbeddedServletContainerFactory) {
			((TomcatEmbeddedServletContainerFactory) container)
					.addContextCustomizers((context) -> {
				context.addLifecycleListener((event) -> {
					if (event.getType().equals(Lifecycle.START_EVENT)) {
						((Context) event.getSource()).getManager()
								.getSessionIdGenerator()
								.setJvmRoute(((ManagerBase) context.getManager())
										.getJvmRoute());
					}
				});
			});
		}
	};
}
```

**Comment by peterdnight** [comment]
Confirm that it works in my scenario - many thanks for posting!  I have already invested quite a bit in the boot 1.4 APIs affecting dozens of files. (Thymeleaf 3, @GetMapping, etc.)
