### ISSUE TITLE
@WebServlet registered with ServletComponentScan does not honor @MultipartConfig annotation

### ISSUE THREAD

**Issue by torerefsnes** [spring-projects/spring-boot#6680]
I have recently migrated an war-application to Spring Boot 1.4. The servlets are registered using ServletComponentScan.

The servlets that are annotated with @MultipartConfig do not decode multipart data. It seems the @MultipartConfig annotation is not honored for servlets registered through ServletComponentScan.

**Comment by wilkinsona** [comment]
That sounds more than likely. What behaviour have you observed that made you realise that `@MultipartConfig` isn't being honoured?

**Comment by torerefsnes** [comment]
HttpServletRequest.getParts() returns null, and
HttpServletRequest.getParameter() return null when multipart-data is
posted, and the servlet has been added through ServletComponentScan.

If I remove the @WebServlet and @MultipartConfig annotation and add the
servlet as a @Bean in my Application class, it works as expected.

tor. 18. aug. 2016 kl. 10.45 skrev Andy Wilkinson <notifications@github.com

**Comment by wilkinsona** [comment]
Interesting. That's not what I expected. In both cases the `Servlet` is registered using a `ServletRegistrationBean` so I would have guessed that only things configured via the `@MultipartConfig` attributes would not be honoured. Can you please create a small sample that shows the two different behaviours that you're seeing?

**Comment by torerefsnes** [comment]
Yes, but I have to add this line when registering the servlet in the
Application class to make it work:

        servletRegistrationBean.setMultipartConfig(new
MultipartConfigElement((String) null));

I suspect the annotation on the servlet class does not cause this
MultipartConfig to be added to the ServletRegistrationBean..

I'll provide a test case if you can't see any obvious errors in the code.
Thanks!

tor. 18. aug. 2016 kl. 11.47 skrev Andy Wilkinson <notifications@github.com

**Comment by wilkinsona** [comment]
No, that's fine. Thanks. I think I have all the info I need now
