### ISSUE TITLE
Consider adding PlusConfiguration and AnnotationConfiguration to jetty WebAppContext

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-boot#6681]
Since `jetty-annotations` and `jetty-plus` dependencies are available via websocket, `AnnotationConfiguration` and `PlusConfiguration` can be added in `JettyEmbeddedServletContainerFactory`. This will enable, for example, annotations like `@MultipartConfig` are picked up and registered by jetty.

**Comment by wilkinsona** [comment]
Unfortunately, I don't think we should do this. As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-embedded-container-context-initializer):

> Embedded servlet containers will not directly execute the Servlet 3.0+ javax.servlet.ServletContainerInitializer interface, or Spring’s org.springframework.web.WebApplicationInitializer interface.

> This is an intentional design decision intended to reduce the risk that 3rd party libraries designed to run inside a war will break Spring Boot applications.

You can use Boot's own `@ServletComponentScan` to have it scan for and automatically register `@WebServlet`, `@WebFilter` and `@WebListener` beans with the container. Now that #6680 has been fixed, it'll also honour `@MultipartConfig`.
