### ISSUE TITLE
RandomAccessDataFile should use Semaphore.acquireUninterruptibly

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#6682]
In `org.springframework.boot.loader.data.RandomAccessDataFile` , when read file, it will call `Semaphore.acquire`. When the current thread state is `interrupted`, it will throw `InterruptedException`. The thread will failed to read file.

```java
// java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int arg
    public final void acquireSharedInterruptibly(int arg)
            throws InterruptedException {
        if (Thread.interrupted())
            throw new InterruptedException();
        if (tryAcquireShared(arg) < 0)
            doAcquireSharedInterruptibly(arg);
    }
```

Consider the following case:

0. A executor submit a Runnable task, then call `FutureTask.cancel` to cancel it.
0. The Runnable task thread state is marked as interrupted, but it will continue running.
0. The Runnable task thread try to load class `A`, the spring boot classloader will use `RandomAccessDataFile` to read A.class file from fat jar. But `RandomAccessDataFile` will  throw  `IOException`, because the current thread state is interrupted. 
0. The clsssloader thow `NoClassDefFoundError`

**Comment by wilkinsona** [comment]
Closing in favour of #6683
