### ISSUE TITLE
Documentation for neo4j mentions @NodeEntityScan not @EntityScan

### ISSUE THREAD

**Issue by afaulconbridge** [spring-projects/spring-boot#6687]
Documentation for [using neo4j](http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#boot-features-neo4j) talks about using @NodeEntityScan annotation. For 1.4.0.RELEASE this annotation was replaced with the more general @EntityScan annotation and the documentation needs to be updated accordingly.

**Comment by snicoll** [comment]
Good catch, thanks.
