### ISSUE TITLE
Spring Boot 1.4.0 does not append jvmroute to jsessionid

### ISSUE THREAD

**Issue by glyoder** [spring-projects/spring-boot#6689]
When I set the "jvmRoute" property, Spring boot 1.4.0 is not appending it to the jsessionid. We need this in order to support sticky sessions. When I down grade to spring boot 1.3.7, it behaves as expected. In both cases, I'm using tomcat 8.x.

I'm pretty sure this is not a tomcat issue because this still doesn't work with spring boot 1.4.0 even when I downgrade to tomcat 7. Also, I've debugged the apache StandardEngine class and can see the jvmroute property being applied. Yet somehow the jseesionid cookie isn't getting the correct value.

Here's a sample app that demonstrates the problem:
https://github.com/glyoder/springboot-tomcat-jvmroute

The new testing support added in Spring Boot 1.4.0 is awesome, and we don't want to have to downgrade! :)

**Comment by wilkinsona** [comment]
Duplicates #6679
