### ISSUE TITLE
Spring Boot AutoConfiguration doesn't support Neo4J bolt driver

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6690]
Enhancement

https://neo4j.com/blog/spring-data-neo4j-4-1-milestone-1/ suggests that Spring Data does support it, though I can't find a reference in the spring data docs, so maybe not.

I can't find anything in spring boot docs either. This is the error I get on the server when configuring with a `bolt://` uri. If I need to produce an example product I can.

I did add this to my dep list

```xml
<dependency>
    <scope>runtime</scope>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-bolt-driver</artifactId>
    <version>${neo4j-ogm.version}</version>
</dependency>
```

```
[rpf-4b2e34af-1]2016-08-19T02:24:38.321095190Z 2016-08-19 02:24:38.320  WARN 5 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.neo4j.Neo4jDataAutoConfiguration$SpringBootNeo4jConfiguration': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'configuration' defined in class path resource [org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.neo4j.ogm.config.Configuration]: Factory method 'configuration' threw exception; nested exception is java.lang.IllegalArgumentException: Could not deduce driver to use based on URI 'bolt://localhost:7687'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configuration' defined in class path resource [org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.neo4j.ogm.config.Configuration]: Factory method 'configuration' threw exception; nested exception is java.lang.IllegalArgumentException: Could not deduce driver to use based on URI 'bolt://localhost:7687' 
```
the short `Could not deduce driver to use based on URI 'bolt://localhost:7687`

since bolt is the binary protocol driver it would be nice to support it by configuring `spring.data.neo4j.uri=bolt://...`

In the event this is a documentation oversight, please add some 

http://stackoverflow.com/q/39030390/206466

**Comment by wilkinsona** [comment]
Please show us what you've tried.

Boot can't deduce the driver to use for a `bolt://` URI. That should be clear from the code that's throwing the exception.

Have you tried explicitly configuring the driver too?

**Comment by vince-bickers** [comment]
@xenoterracide: Please see my response on SOF.

**Comment by philwebb** [comment]
Perhaps we can drop that exception if the `DriverConfiguration` can deduce the driver type from the URL.

**Comment by snicoll** [comment]
There was a reason why I didn't support bolt initially but I don't remember right now what it was. I'll have a look to the code again.

**Comment by xenoterracide** [comment]
I could look into implementing this, but ... where is the code that actually does this?

**Comment by snicoll** [comment]
`Neo4jProperties`: if you can give that a try and submit a PR that'd be nice.

**Comment by snicoll** [comment]
Closing in favour of the PR #6746

**Comment by BrentonPoke** [comment]
> @xenoterracide: Please see my response on SOF: http://stackoverflow.com/questions/39030390/how-can-i-use-the-bolt-driver-with-spring-boot-data-neo4j

I imagine this has changed since you posted, since I am getting this same error. This is the Neo4J-related part of my pom:
```
                <dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j</artifactId>
			<version>3.5.5</version>
		</dependency>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-ogm-embedded-driver</artifactId>
			<version>${neo4j-ogm.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-ogm-bolt-driver</artifactId>
			<version>${neo4j-ogm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-neo4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
```
My URI in the properties file is not a localhost URI, but a bolt URI in the form of bolt://user:password@IPAddress:Port I tried using your config Bean, but it looks like the API has changed.
