### ISSUE TITLE
Allow WebMvcTest to be used as a meta-annotation

### ISSUE THREAD

**Issue by the4yeast** [spring-projects/spring-boot#6691]
I think the title says it all.

I'd like to use WebMvcTest as a meta-annotation, so my custom annotation can be meta-annotated with WebMvcTest and all of its attributes that I share across tests. The only attribute - obviously - I would like to override is the controller under test.

**Comment by snicoll** [comment]
Have you tried? I see no reason why it wouldn't work. I just created a dummy `MyWebMvcTest` in a sample project and it worked.

**Comment by maciejdrozdzowski** [comment]
I did, before actually creating this issue.

I had a custom annotation, with aliases to `WebMvcTest` for `value` and `controllers`. It was meta-annotated with `ActiveProfiles` and `WebMvcTest`. I can't remember the exact exception thrown, but it indicated faulty setup, so I undid my changes.

Which Boot version did you try with? I'm using 1.4.0.RELEASE at the moment.

**Comment by snicoll** [comment]
Me too. I did the same thing (without the `ActiveProfiles` thing). I am afraid you'll have to share a sample that reproduces the problem at this point.

**Comment by maciejdrozdzowski** [comment]
I'll need to recreate and see how I go.

**Comment by maciejdrozdzowski** [comment]
Ooops, sorry for any confusion, both these accounts (the4yeast and maciejdrozdzowski) are the same person, I didn't realise I was on a different account.

**Comment by maciejdrozdzowski** [comment]
Here's a sample, trying to replicate what you did - without `@ActiveProfiles` on the annotation.

```
@ActiveProfiles("local")
@RunWith(SpringRunner.class)
@MyWebMvcTest(controllers = MyController.class)
public class DummyTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    public void test() {

    }
}
```

```
@WebMvcTest(secure = false,
    excludeFilters = @Filter(type = FilterType.ASSIGNABLE_TYPE, classes = SecurityConfig.class)
)
public @interface MyWebMvcTest {

    /**
     * @see WebMvcTest#value
     */
    @AliasFor(annotation = WebMvcTest.class, attribute = "value")
    Class<?>[] value() default {};

    /**
     * @see WebMvcTest#controllers
     */
    @AliasFor(annotation = WebMvcTest.class, attribute = "controllers")
    Class<?>[] controllers() default {};

}
```
It can't find `MockMvc` for injection.

**Comment by wilkinsona** [comment]
You haven't configured `@MyWebMvcTest`'s retention so it won't be available when the tests run. You need:

```java
@Retention(RetentionPolicy.RUNTIME)
```

With that added, your sample above works for me. If it doesn't fix it for you, please problem a complete, minimal example that reproduces the problem and we can re-open this and take another look.

**Comment by maciejdrozdzowski** [comment]
Wow, that's embarrassing... I forgot how to write annotations.
Thanks for youe help!
