### ISSUE TITLE
Release notes doesn't mention the new default for 'proxyTargetClass'

### ISSUE THREAD

**Issue by tadaskay** [spring-projects/spring-boot#6693]
#5423 sets `proxyTargetClass=true` as the new default, effectively breaking it down for people using `@Transactional` on the interfaces. As I have later found out, the suggested way is to use it on the classes (even though in my opinion it makes more sense to be put in the contract = interface).

Do you think this change might be worth mentioning in the release notes so that people upgrading to 1.4 (like myself) might save a few hours of debugging?

**Comment by snicoll** [comment]
> even though in my opinion it makes more sense to be put in the contract = interface

I am not sure I agree, though I see what you mean. I am not sure we expected that change to break  your project. Note that we're considering flipping that attribute to `true` by default in Spring 5.

Ping @philwebb

**Comment by philwebb** [comment]
We should definitely add some release notes about this. I think the root cause is [SPR-14322](https://jira.spring.io/browse/SPR-14322) which won't get fixed until Spring 5.

I'd still like to leave `proxyTargetClass=true` as the default.

**Comment by snicoll** [comment]
Added [a section in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#transactional-default-to-cglib-proxies)
