### ISSUE TITLE
Custom data source type is no longer honoured 

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6695]
Interesting [use case reported on stackoverflow](http://stackoverflow.com/questions/39032368/not-able-to-set-spring-datasource-type-in-spring-boot-1-4/39034066#39034066).

In 1.3 we would map _any_ `DataSource` created via auto-config on `spring.datasource`. It means that a user could use any specific setting and still use the auto-configuration. We don't support that use case anymore.

Looking at the code a bit deeper, we don't seem to handle a custom type either. So we broke `spring.datasource.type`.

We should make it easier for someone to reuse that code and create a `DataSource` exactly like we do and map that to their own namespace (i.e. `app.datasource`)

**Comment by happyangellxq** [comment]
I konw the spring boot in 1.2 can not support, but in 1.3 support it, why cancel the support in 1.4 ?

**Comment by snicoll** [comment]
There's a "blocker" and "regression" label on this issue that indicates we didn't intend to do that. We'll fix it for 1.4.1

**Comment by happyangellxq** [comment]
@snicoll  Thanks!

**Comment by snicoll** [comment]
@happyangellxq this is now fixed. Can you try with `1.4.1.BUILD-SNAPSHOT` in a couple of hours once a new snapshot is available? Thanks!

**Comment by Infrag** [comment]
This property doesn't work in Spring Boot 1.5.6.RELEASE. It just picks first known pool implementation on classpath. `spring.datasource.type is ignored`

**Comment by snicoll** [comment]
@Infrag this issue is closed and none of our tests exercising `spring.datasource.type` broke. If you believe you've found an issue, please open a separate issue with a sample that we can run. Thanks!
