### ISSUE TITLE
EhCache 3.1.1.jar corrupted in repository

### ISSUE THREAD

**Issue by Canos** [spring-projects/spring-boot#6696]
I've just found that ehcache-3.1.1.jar is broken given a java.util.zip.ZipException: invalid LOC header (bad signature) while starting Spring Boot application.
JAR file is opened nicely from a standalone application in my desktop but contained MANIFEST file is broken or corrupt.

Workaround: replace manually the jar file from ehcache github
https://github.com/ehcache/ehcache3/releases/tag/v3.1.1

I haven't studied deeper but jar sizes are oddly different. 2.2Mb repository jar vs 1.6Mb from ehcache github.

**Comment by snicoll** [comment]
What repository are you talking about? Spring Boot doesn't have any kind of repository (I guess you mean Maven repository) and we don't host libraries ourselves. I guess you had a corrupted download from Maven central or something. 

Feel free to reopen if I misunderstood with some details on how I could reproduce the issue.
