### ISSUE TITLE
Documentation: use security.filter-dispatcher-types in "Mapping error pages outside of Spring MVC" example

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#6697]
(Extracted from https://github.com/spring-projects/spring-boot/issues/4505#issuecomment-233176246)

I believe that documentation should be updated to use `security.filter-dispatcher-types` in the example [here][1].

[1]: http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#boot-features-error-handling-mapping-error-pages-without-mvc

**Comment by wilkinsona** [comment]
I disagree. The example is for any Filter, whereas `security.filter-dispatcher-types` is specifically for configuring the dispatcher types for Spring Security's Filter.

**Comment by php-coder** [comment]
Sounds fair.

But maybe we can mention that's for configuring Spring Security's Filter there is `security.filter-dispatcher-types` property? Because IMHO it's most common case.

**Comment by wilkinsona** [comment]
I think that'd need to go in a different place as you could be using Spring MVC for error pages.
