### ISSUE TITLE
Consider adding support for multiple DB vendors in Flyway auto-config

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#6700]
Consider an app that uses Flyway for migrations, and at the same needs to support multiple DB vendors. To support such an use case, one would place migrations in separate directory for each vendor, for example `db/migration/postgresql` for PostgreSQL, `db/migration/mysql` for MySQL, etc. Currently this requires resorting to profiles to set different value for `flyway.locations` configuration property for each DB vendor.

IMO it would make sense to enhance Flyway auto-config to support such use case by introducing a configuration property which, if enabled, would append vendor directory to the configured `flyway.locations` value based on the vendor resolved from JDBC URL of `DataSource` in use.

Thoughts? I've started sketching something like this and would like to submit a PR you think this makes sense.

**Comment by philwebb** [comment]
Seems like a nice idea to me. I've flagged it for team discussion and we'll talk about it on our next call.

**Comment by wilkinsona** [comment]
We already do something similar in `DataSourceInitializer` and `spring.datasource.platform`, albeit without determining the platform automatically.

**Comment by snicoll** [comment]
closing in favour of PR #6900
