### ISSUE TITLE
DataSourceInitializedPublisher doesn't fire DataSourceInitializedEvent in Cloud Foundry environment with Spring Auto Reconfiguration

### ISSUE THREAD

**Issue by making** [spring-projects/spring-boot#6708]
I'd like to generate the schema by Hibernate and populate initial data with `data.sql`.
In the local environment it works, but in case of Cloud Foundry it does't work.
When using CF and Spring Auto Reconfiguration, `data.sql` under classpath is not called.
### Reason

Because [AbstractCloudServiceBeanFactoryPostProcessor](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/blob/master/auto-reconfiguration/src/main/java/org/cloudfoundry/reconfiguration/spring/AbstractCloudServiceBeanFactoryPostProcessor.java) is enabled, [`DataSourceInitializedPublisher.dataSource`](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L62) should be `null` and [`DataSourceInitializedEvent` won't be fired](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L67-L71).

This occurs unless `schema.sql` exists because if there is `schema.sql` [`DataSourceInitializer` will fire the event](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceInitializer.java#L87-L88).
### Possible solutions

I don't think `DataSource` is necessary to check [whether database should be initialized](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L79-L80). `DataSource` is used only if it's embedded in [`JpaProperties.Hibernate#getDefaultDdlAuto`](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/JpaProperties.java#L224-L226).

One solution might be removing null check from [L67](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L67) and modifying [`JpaProperties.Hibernate#getDefaultDdlAuto`](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/JpaProperties.java#L223-L228) like following:

``` java
        private String getDefaultDdlAuto(DataSource dataSource) {
            if (dataSource != null && EmbeddedDatabaseConnection.isEmbedded(dataSource)) {
                return "create-drop";
            }
            return "none";
        }
```

`DataSource` can be actually injected, so `ObjectProvider<DataSource>#getIfAvailable` might be used in [`DataSourceInitializedPublisher#postProcessAfterInitialization`](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L67-L71) as an another solution. 

I'm using Spring Boot 1.4. but It will also happen with other versions.

**Comment by making** [comment]
https://github.com/making/hajiboot-samples/tree/1.4.x/chapter04/4.6.1_hajiboot-rest
is a reproducible project.

On PWS, 

``` console
$ ./mvnw clean package -DskipTests=true 
$ cf push hajiboot-rest -p target/hajiboot-rest-0.0.1-SNAPSHOT.jar -m 512m -b java_buildpack --no-start
$ cf create-service cleardb spark customer-db
$ cf bind-service hajiboot-rest customer-db
$ cf start hajiboot-rest
```

You can see `data.sql` is not called from `cf logs hajiboot-rest --recent`

**Comment by philwebb** [comment]
Feels like whatever fix we do could be risky so I think we'll leave this as a known issue in 1.3.x

**Comment by philwebb** [comment]
I think this might actually be expected behavior. If you're running the application locally, using an embedded database then it's safe to run the `data.sql` script (since the database is fresh). When you push an application to Cloud Foundry the database is provided so we can't be sure that it's safe to run `data.sql`.

I think the recommended approach to running data scripts on Cloud Foundry would be to use flyway.

**Comment by philwebb** [comment]
@making Do you agree with the comment above, I'm not totally sure if I've followed everything in your original description?

**Comment by making** [comment]
@philwebb I agree using flyway is recommended. I intended to use `data.sql` for the demo purpose only. Actually, using `import.sql` instead of `data.sql` or using spring-cloud-connector instead of buildpack's auto-reconfigure could be alternative.

**Comment by philwebb** [comment]
I think the current behavior is correct and using flyway would be the right way to deal with this.
