### ISSUE TITLE
Liquibase doesn't respect logging configuration

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#6713]
This issue is the same as #3470: liquibase doesn't use logging configuration -- it prints INFO messages when I want to see only warnings and its messages have a different format.

### Steps to reproduce
```console
$ git clone https://github.com/php-coder/mystamps.git
$ cd mystamps
$ git checkout b2f1c612d9eba7a957edc602c3431de848fd55e1
$ mvn clean spring-boot:run
```

### Observable behavior
```
...
[2016-08-21 12:36:50.686] boot - 3174  INFO [main] --- RequestMappingHandlerAdapter: Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@63dde5e5: startup date [Mon Aug 21 12:36:46 CEST 2016]; root of context hierarchy
INFO 8/21/16 12:36 PM: liquibase: Successfully acquired change log lock
INFO 8/21/16 12:36 PM: liquibase: Creating database history table with name: PUBLIC.DATABASECHANGELOG
INFO 8/21/16 12:36 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
...
INFO 8/21/16 12:36 PM: liquibase: Successfully released change log lock
[2016-08-21 12:36:53.115] boot - 3174  INFO [main] --- application: Initializing Spring FrameworkServlet 'dispatcherServlet'
...
```

### Expected behavior
I shouldn't see all of these messages from Liquibase because I'm interesting only in warnings:
```console
$ grep liquibase src/main/resources/application-test.properties
liquibase.contexts: scheme, init-data, test-data
liquibase.change-log: classpath:/liquibase/changelog.xml
logging.level.liquibase: WARN
```

### Workaround
Also I found out that it was working in Spring Boot 1.3.0.RELEASE but broken since 1.3.1.RELEASE. To test it you can downgrade the version and test that it works:
```console
sed -i 's|1.3.7.RELEASE|1.3.0.RELEASE|;s|9.2.18.v20160721|9.2.11.v20150529|' pom.xml
```

Let me know if you need more information.

**Comment by wilkinsona** [comment]
Interestingly, it does respect the logging configuration when run using `java -jar`

**Comment by wilkinsona** [comment]
It works with an executable archive as it prevents Liquibase from loading its logger implementation until we've installed our `SpringPackageScanClassResolver` at which point our custom logger is used instead.

**Comment by wilkinsona** [comment]
We need to reinstate the work around from [this commit](https://github.com/spring-projects/spring-boot/commit/255764f1a0080122b15e8be95acae7963d9055cc) and a test to ensure that it doesn't get broken again.

**Comment by php-coder** [comment]
@wilkinsona Thank you for the fast feedback and the fix!

Will it be fixed in 1.4.x or this version doesn't need it?

**Comment by wilkinsona** [comment]
The fix is in 1.3.x and master (1.4.x).

**Comment by prerakalw** [comment]
Refer https://github.com/prerakalw/liquibase-with-logs

**Comment by snicoll** [comment]
@prerakalw thanks for sharing but this issue has been fixed over 2 years ago and both Spring Boot 1.3 and 1.4 are EOLed by now. Please upgrade.

**Comment by prerakalw** [comment]
@snicoll i was using liquibase 3.6.2 binary for database change sets deployment, and during deployment it does not logs anything. Sorry but can you please elaborate where should i upgrade spring boot.

**Comment by snicoll** [comment]
@prerakalw I don't know, really. Except for a link, you haven't shared much. If you can reproduce the problem with a supported version of Spring Boot, please create a separate issue with a small sample that reproduces the problem. My point was that commenting on a 2 years-old issue wasn't the right way to get support (if that's what you're asking here).

**Comment by peterlitvak** [comment]
I know this is very old issue but I'm having the same issue with Sprint boot 2.0.3, what could be the problem here?

**Comment by wilkinsona** [comment]
@peterlitvak it’s impossible to say without some more information. Spring Boot 2.0.x is no longer supported. Please upgrade to 2.1.x or 2.2.x. If the problem still occurs, please open a new issue, attaching a minimal sample that reproduces the problem.
