### ISSUE TITLE
No cache manager could be auto-configured, check your configuration (caching type is 'HAZELCAST')

### ISSUE THREAD

**Issue by johanvdb** [spring-projects/spring-boot#6714]
Please see https://github.com/johanvdb/spring-boot-hazelcast-test for an example of a clean web starter application, that only imports hazelcast-spring, uses @EnableCaching and sets the property spring.cache.type=hazelcast. The application fails to start up. 

Interestingly, if you comment the property spring.cache.type, it starts up, but the CacheManager that is injected is org.springframework.cache.concurrent.ConcurrentMapCacheManager even though hazelcast and hazelcast-spring 3.6.4 are on the classpath.

It seems to be related to #4389.

I originally saw the problem on another spring boot 1.4.0 release application that was making use of hazelcast successfully for leadership election, but was unable to use it for caching.

**Comment by johanvdb** [comment]
@snicoll

**Comment by snicoll** [comment]
A clean web app with war packaging? ;-) Looking at it now.

**Comment by snicoll** [comment]
Thanks for the sample project but .... where is your Hazelcast config? There's nothing in this project beside the dependency. There's nothing that helps us configuring Hazelcast: there isn't a `HazelcastInstance` bean.  There isn't a `hazelcast.xml` at the default location. There isn't `spring.hazelcast.config` property set. See [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-hazelcast)

What did you expect exactly? I've added a minimal `hazelcast.xml` in src/main/resources and the cache manager was configured properly.

**Comment by johanvdb** [comment]
Doh. Sorry for the waste of resources and greatly appreciate the guidance. :) The fact that it just worked for spring cloud threw me off...
