### ISSUE TITLE
Allow Undertow's server and socket options to be configured via the environment

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6715]
Something like:

```
server.undertow.options.socket.whatever: foo
server.undertow.options.server.whatever: bar
```

`whatever` is then coerced into one of the constants on `UndertowOptions`, ideally with relaxed binding. A concrete example:

```
server.undertow.options.server.enable-http2: true
```

See #3350 which this issue probably supersedes.

**Comment by snicoll** [comment]
`Enum` has already some kind of relaxed bindings and you'll need to make a `Map<UndertowOptions, Object>` to make that work.

**Comment by wilkinsona** [comment]
If only `UndertowOptions` were an `Enum`

**Comment by ofbizbrazil** [comment]
I really missed this property for a long while. Please add this ASAP!!!

**Comment by ofbizbrazil** [comment]
I really missed this property for a long while. Please add this ASAP!!!

**Comment by mbhave** [comment]
Closing in favor of PR #17356.
