### ISSUE TITLE
Make TestAutoConfigurationPackage annotation public

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#6718]
Hi,

I have created a [new project](https://github.com/eddumelendez/ldap-spring-boot) in order to provide ldap auto-configuration as a third party starter.

The following annotation `TestAutoConfigurationPackage` and the class
`TestAutoConfigurationPackageRegistrar` have been very useful to test spring data projects inside of spring boot. So, I would like to apply the same in my new project. I was wondering if there are any way to move these classes from test source in order to make them public?

Thanks in advance

**Comment by philwebb** [comment]
It's tricky. We can't move them to `spring-boot-test` since that doesn't know about auto-configuration. We could copy them to `spring-boot-test-autoconfigure`, but we can't move them because `spring-boot-autoconfigure` can't depend on `spring-boot-test-autoconfigure`.

**Comment by philwebb** [comment]
I have a feeling that copy/paste might be the least bad option here.

**Comment by eddumelendez** [comment]
@philwebb thanks to explain, very tricky indeed. any issue with the license? I'll keep the authors.

From my side, the issue can be closed if it is not feasible.

**Comment by philwebb** [comment]
After some discussion we don't think there's an easy way to fix this on our side. Much as I hate to recommend it, copy/paste is the way to go with this one.
