### ISSUE TITLE
UndertowEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by jiaojing** [spring-projects/spring-boot#6720]
UndertowEmbeddedServletContainerFactory 

``` java
AccessLogReceiver accessLogReceiver = new DefaultAccessLogReceiver(
					createWorker(), this.accessLogDirectory, prefix,
					this.accessLogSuffix);
```
createWorker() here, more overhead. just need one fixed thread executor.

**Comment by wilkinsona** [comment]
The worker does use a fixed number of threads, it's also [exactly what Wildfly uses](https://github.com/wildfly/wildfly/blob/10.1.0.Final/undertow/src/main/java/org/wildfly/extension/undertow/AccessLogService.java#L56) and the main author of that code is also the main author of Undertow. I think we should leave this as it is.
