### ISSUE TITLE
Provide a way to derive a TestRestTemplate that uses basic auth from the auto-configured one

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6732]
You may want to test a mixture of endpoints that do and do not require basic authorisation, or that require users with different roles. The auto-configured `TestRestTemplate` doesn't use basic auth. Currently, if you want one that does you can either go back to `new TestRestTemplate(user, password)`, injecting the local server port and creating URLs yourself (`"http://localhost" + this.port + "/whatever"`), or do a dance with adding and removing the basic auth interceptor in each test:

```
BasicAuthorizationInterceptor basicAuthInterceptor = new BasicAuthorizationInterceptor(
				"user", "user");
this.restTemplate.getRestTemplate().getInterceptors().add(basicAuthInterceptor);
try {
	ResponseEntity<String> entity = this.restTemplate.getForEntity("/beans",
			String.class);
	assertThat(entity.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
}
finally {
	this.restTemplate.getRestTemplate().getInterceptors()
			.remove(basicAuthInterceptor);
}
```

It'd be nice to be able to do something like this instead:

```
ResponseEntity<String> entity = this.restTemplate.withBasicAuth("user", "user")
		.getForEntity("/beans", String.class);
assertThat(entity.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
```

Where `withBasicAuth(String, String)` returns a new `TestRestTemplate` that is the same as the one on which the method was called except that the basic auth interceptor has been added to it.

**Comment by snicoll** [comment]
That would be consistent with the `RestTemplateBuilder` that creates another instance every time you apply a customization to it.
