### ISSUE TITLE
Divorce Spring Versions from the Gradle Plugin Version

### ISSUE THREAD

**Issue by Blacktiger** [spring-projects/spring-boot#6734]
Currently we are supposed to get the spring dependency versions set by which version of the gradle plugin we use. This can be overridden by using the dependency management section to pull in a different spring BOM. For example, I can use the cloud config bom.
```
dependencyManagement {
  imports {
    mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Brixton.SR4'
  }
}
```

However this isn't real intuitive in my opinion. If a newer version of the gradle plugin supports new features or fixes, I can't upgrade to it without upgrading my spring version or declaring a new BOM to override the spring version provided by the plugin. Since the plugin might have bugfixes that aren't tied to a spring release it really doesn't make sense for the plugin to provide a spring version.

Personally, I think the spring-boot-gradle plugin should be divorced from spring-boot itself; if you list out the concerns of this plugin you'll quickly see that it has very little to do with spring and the parts that _are) spring-specific are not really tied to any particular spring versions:

* Repackage war/jar as executable with correct main class
** Spring specific only in that it moves providedRuntime dependencies to provided-lib
* Provide bom-based dependency management
* Provide default spring-versions (spring-related, but easily done with dependencyManagement BOMs)

Maybe we want to keep the plugin providing a default spring version like it does now, but if so it should be made clear in the documentation exactly how to change the version. There should at least be an example of providing a specific spring bom version to make it clear how to change the version. 

Here is the relevant section of the docs:

> The version of the spring-boot gradle plugin that you declare determines the version of the spring-boot-starter-parent bom that is imported (this ensures that builds are always repeatable). You should always set the version of the spring-boot gradle plugin to the actual Spring Boot version that you wish to use. Details of the versions that are provided can be found in the appendix.

**Comment by snicoll** [comment]
So if your project has been affected by a Spring Boot bug it is ok to upgrade but it isn't ok to upgrade when you want to benefit from an improvement in a specific area?  Actually, there's a few critical features in the plugin that are strongly linked to the Spring Boot version you're using. Repackage is the most common one: the layout of the fat jar has changed between 1.3 and 1.4. There's no way you could upgrade the plugin and still run boot 1.3 with it.

I like the current situation actually: you provide a version for the plugin and you know you'll get that  same Spring Boot version. This makes sure things are aligned and consistent. 

What you said about the plugin can be said about any module. The actuator may have feature XYZ so you may want to just upgrade that. No, you can't. I don't see why it should be any different for the plugin. The reason why there's no example for what you're asking is that we don't want you do that. That's simple.

I am tempted to close this one but I'd like you and @wilkinsona to confirm I am not missing anything. Thanks.

**Comment by wilkinsona** [comment]
I agree with your analysis, @snicoll. This is no different to the requests we've had in the past to allow `spring-boot.version` to be overridden in Maven when using the parent. It would let people get into a situation where they have an untested combination of versions and we don't want to do that.
