### ISSUE TITLE
Make it easier to know what the unit of a metric is

### ISSUE THREAD

**Issue by kelapure** [spring-projects/spring-boot#6736]
The metrics endpoint today is a raw JSON body with numbers. This is cumbersome to read and interpret, as a developer has to invariably make their way to the spring boot reference guide and _figure out that_ 

- The total system memory in KB (mem)
- The amount of free memory in KB (mem.free)
- The number of processors (processors)
- The system uptime in milliseconds (uptime)
-  _yada yada yada_

I suggest that the JSON response be amended to include the type of metric.
```
"mem": 986624 KB,
"mem.free": 933858 KB,
```

If `/metrics` cannot be touched can we please introduce a new human readable endpoint called `/readablemetrics`

**Comment by wilkinsona** [comment]
`"mem": 986624 KB` isn't valid JSON. It could be changed to `"mem": "986624 KB"`, but that would require clients to parse the string to strip off the unit. I don't think that's a good idea.

If we want an entry in `/metrics` to convey its unit, I think it would be more appropriate for that to be included in the name. `mem` could become `memKB`, for example. This would be a breaking change and would need to wait for 2.0.

/cc @dsyer

**Comment by kelapure** [comment]
@wilkinsona You understood the intent of my feature request. The need to convey the metric *type* or the *unit* of the metric in the JSON payload from `/metrics'.   How this is implemented is upto the Spring Boot team

**Comment by kelapure** [comment]
👍

**Comment by bclozel** [comment]
We've decided to fix this with #6413 and use consistent units for all metrics.
Thanks!
