### ISSUE TITLE
Spring Security documentation slightly wonky / old

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6741]
> To also switch off the authentication manager configuration
> you can add a bean of type `AuthenticationManager`, or else configure the
> global `AuthenticationManager` by autowiring an `AuthenticationManagerBuilder` into
> a method in one of your `@Configuration` classes.

I think that's wrong now (since Spring Security 4.1) - or maybe it's right and there's another bug, because I tried it and the app blew up. And you can also create a `@Bean` of type `UserDetailsService` and that works in some way, but I'm not sure how much of the Boot conifguration that switches off.

**Comment by plamentotev** [comment]
Actually autowiring an `AuthenticationManagerBuilder` works for me(or at least so it seems):

```java
@Configuration
@EnableGlobalMethodSecurity(securedEnabled = true)
public class AuthConfiguration extends WebSecurityConfigurerAdapter {

    @Autowired
    public void configureAuthManager(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .inMemoryAuthentication()
                    .withUser("ustudent").password("pstudent").roles("STUDENT")
                        .and()
                    .withUser("uteacher").password("pteacher").roles("TEACHER");
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .anyRequest().authenticated()
                    .and()
                .httpBasic();
    }
}
```

So at least in some cases it does the job. I'm not 100% sure that this switches off the auto-configuration completely , but at least the application does not "blew up" in any visible way.

**Comment by wilkinsona** [comment]
I can't make this blow up with a custom `AuthenticationManager` bean. The advice about `AuthenticationManagerBuilder` seems a bit odd. As @plamentotev has shown about, I'd expect a `WebSecurityConfigurerAdapter` to be used via its `configureAuthManager` method.

@dsyer Can you recall what you did that made it blow up?

**Comment by dsyer** [comment]
I think @plamentotev's `configureAuthManager` is a custom method, not an override (maybe you are confused by the presence of a `configure(AuthenticationManagerBuilder)` method, @wilkinsona?). I don't see anything blowing up in an otherwise empty app, so I'll have to go away and try and come up with a sample.

The hint about the `UserDetailsService` bean is probably worth dropping into the documentation though, since I think it is the preferred way to override the parent auth manager in Spring Security now.

**Comment by wilkinsona** [comment]
> maybe you are confused by the presence of a configure(AuthenticationManagerBuilder) method, @wilkinsona?

Oops. I was indeed.

**Comment by mbhave** [comment]
@wilkinsona @dsyer As far as I can tell, the only thing wrong with this documentation is that autowiring a `AuthenticationManagerBuilder` does not completely switch off the authentication manager configuration, only configuring a bean of type `AuthenticationManager` does. Is that the only thing we need to change or is there something more that's wonky that I'm not seeing?

**Comment by wilkinsona** [comment]
@mbhave I think the only other thing was possibly documenting creating a `UserDetailsService` bean but @dsyer said it "works in some way, but I'm not sure how much of the Boot conifguration that switches off". We'd need to be a lot more precise before documenting something. Right now, I'm not sure it's worth it.

**Comment by mbhave** [comment]
@wilkinsona agreed. We can revisit this in 2.0 when we start making changes in the security theme.

**Comment by mbhave** [comment]
The `AuthenticationManagerConfiguration` in 2.0 backs off if a bean of type `AuthenticationManager`, `AuthenticationProvider` or `UserDetailsService` is provided, as the documentation states.
