### ISSUE TITLE
Spring Boot 1.3.x incompatibility with latest Java Buildpack (currently Version: 5697f96)

### ISSUE THREAD

**Issue by poprygun** [spring-projects/spring-boot#6751]
Getting ERR Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
deploying Spring Boot 1.3.5 app to PCF ERT 1.7.  Had to upgrade to SB 1.4 to fix the error.  Upgrading SB in sync with JBP might not be a possibility for some customers.

**Comment by wilkinsona** [comment]
@poprygun Can you please provide some more information. Specifically, why do you think this is a problem with Spring Boot rather than with the Java Buildpack?

**Comment by wilkinsona** [comment]
Closing in favour of https://github.com/cloudfoundry/java-buildpack/issues/323
