### ISSUE TITLE
Support qualifiers to @MockBean

### ISSUE THREAD

**Issue by willianconsta** [spring-projects/spring-boot#6753]
I'm trying to mock a `RestTemplate` annotated with [LoadBalanced](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalanced.java) using `@MockBean` and got:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.web.client.RestTemplate] found for dependency [org.springframework.web.client.RestTemplate]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.cloud.client.loadbalancer.LoadBalanced()}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 43 more
```

But found no way to give to the mock the `@LoadBalanced` qualifier.
Can we have qualifiers support to `@MockBean`?

**Comment by snicoll** [comment]
That doesn't feel right. You shouldn't care about load balancing on a mock. Are you injecting that `RestTemplate` somewhere with the qualifier maybe? A bit more info about your project is required to better understand the problem.

**Comment by wilkinsona** [comment]
I think I understand the problem. This test will fail:

```java
package org.springframework.boot.test.mock.mockito;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.mockito.Mockito.verify;

@RunWith(SpringRunner.class)
public class MockBeanForExistingBeanWithQualifierIntegrationTests {

	@MockBean
	private ExampleService service;

	@Autowired
	private MyController controller;

	@Test
	public void testMocking() throws Exception {
		this.controller.foo();
		verify(this.service).doSomething();
	}

	@Qualifier
	@Retention(RetentionPolicy.RUNTIME)
	@interface MyQualifier {

	}

	@Configuration
	static class TestConfig {

		@Bean
		public ExampleService service() {
			return new StandardExampleService();
		}

		@Bean
		public MyController controller(@MyQualifier ExampleService service) {
			return new MyController(service);
		}

	}

	interface ExampleService {

		void doSomething();

	}

	@MyQualifier
	static class StandardExampleService implements ExampleService {

		@Override
		public void doSomething() {

		}

	}

	static class MyController {

		private final ExampleService service;

		public MyController(ExampleService service) {
			this.service = service;
		}

		public void foo() {
			this.service.doSomething();
		}

	}

}
```

The problem is that the `ExampleService` mock doesn't have the `MyQualifier` qualifier so the injection into the `controller` bean method fails.

**Comment by willianconsta** [comment]
Sorry being unclear, but @wilkinsona got the idea.
The problem I faced is exactly what he showed.

**Comment by snicoll** [comment]
OK I am working on this one and it's a bit harder than I thought. Several things:

* `@MockBean` can be specified on `@Configuration` classes so in that case we'll have no  way to qualify the change
* There is no SPI or utility to collect the qualifier values from the injection point so I'll have to duplicate that logic in boot
* If several beans of the same type are present (that's usually why you use qualifiers in the first place), we need to identify which instance matches the qualifier specified on the injection point. Fortunately, there seem to be an API for that

It's quite a large change but I want to give that a go and then we can decide if we can afford to add that to 1.4.1.

**Comment by snicoll** [comment]
This requires a change in Spring Framework, I am tackling that in [SPR-14725](https://jira.spring.io/browse/SPR-14725)

**Comment by philwebb** [comment]
Unfortunately I think this change might introduce context cache issues. The `Definition` items are used as the `MockitoContextCustomizer` hashcode/equals check. If we use the `field` as part of the key then all tests will get a new context, if we don't then it's possible that two different tests that have the same `@MockBean` definition but a different `@Qualifier` will accidentally get the wrong mock.

I'm experimenting with some ideas, but so far the fix doesn't look obvious.

**Comment by snicoll** [comment]
Arg. I see what you mean, I did all that to explicitly avoid scanning the qualifiers myself.

**Comment by philwebb** [comment]
I think I've got a fix. Will commit later.
