### ISSUE TITLE
Add support for automatically instrument methods/classes annotated with Dropwizard Annotations

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#6754]
Dropwizard Metrics provides a nice set of various [annotations](https://github.com/dropwizard/metrics/tree/master/metrics-annotation/src/main/java/io/dropwizard/metrics/annotation) to mark classes/fields/methods that should be instrumented.

It would be great, if Spring Boot would auto-configure CGLIB proxy AOP interceptors to automatically instrument the annotated elements if Dropwizard library is present (just like creating the Dropwizard-friendly registry instead of the default one.

**Comment by wilkinsona** [comment]
Sounds like you're proposing auto-configuration for [metrics-spring](https://github.com/ryantenney/metrics-spring)?

**Comment by aantono** [comment]
If you think that it looks good and does things "the spring way" ;)

One thing I found missing in there is having to manually annotate every monitored method with 2 annotations, one doing the counting/timing, etc and another for exceptions to monitor method failures.  Would be nice to always get success and fail reported.  Also the SPeL support and meta-annotations are missing...  The same goes for inability to monitor internal (inside same class) calls to `this.foo()` as the proxy is not handling it via cglib (like spring config classes do) for some reason.

**Comment by wilkinsona** [comment]
I'd rather see improvements being made to `metrics-spring` (if any are needed) than us reinventing the wheel.

>  The same goes for inability to monitor internal (inside same class) calls to this.foo() as the proxy is not handling it via cglib

It uses Spring to create the proxies so it should work as long as `proxyTargetClass` is `true`.

**Comment by aantono** [comment]
@wilkinsona that sounds like a good approach, if that library can be improved and enhanced.  I see the option for `proxyTargetClass` to be set on the annotation, but for some reason it is `false` by default - https://github.com/ryantenney/metrics-spring/blob/v3.2-development/src/main/java/com/ryantenney/metrics/spring/config/annotation/EnableMetrics.java#L65.  Do you know of any reason why that can't be made always `true`?

**Comment by wilkinsona** [comment]
> but for some reason it is false by default

That aligns with Spring Framework's default for its proxy creation.

> Do you know of any reason why that can't be made always true?

There are some subtle differences in behaviour between JDK proxies and CGLib proxies. That means that changing the default may be a breaking change for some. FWIW, a change to Spring Framework's default is being considered for 5.0

**Comment by wilkinsona** [comment]
Our recommendation is to use https://github.com/ryantenney/metrics-spring.
