### ISSUE TITLE
Harmonize `ConditionOutcome#message`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6756]
`NoSuchBeanDefinitionFailureAnalyzer` is reusing the auto-configuration report to find beans that could have matched. The only thing it can do when it find one really is to use the `message` that was generated for the auto-configuration report.

The messages are somewhat consistent but should be improved if we want to use them elsewhere. 

For one, most messages start with the annotation and the auto-configuration automatically adds the `Condition` that was checked. In the json version we have this.

```
EndpointWebMvcHypermediaManagementContextConfiguration.MvcEndpointAdvice: [
  {
    condition: "OnPropertyCondition",
    message: "@ConditionalOnProperty missing required properties endpoints.hypermedia.enabled"
  }
]
```

I find the annotation to be more useful (in the text format) than the condition that is an implementation detail. For instance `OnBeanCondition` is used by many annotations that have a higher-level semantic so you don't know if that condition is about a missing bean, a unique bean or a the presence of a bean until you parse the message yourself. That's probably why we add the annotation types at the beginning of the message.

If we look how that would look like in an auto-configuration report:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$StringHandler required a bean of type 'java.lang.String' that could not be found:
	- @ConditionalOnProperty missing required properties endpoints.hypermedia.enabled: disabled on method 'string' in 'org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$TestPropertyAutoConfiguration'


Action:

Consider revisiting the conditions above or defining a bean of type 'java.lang.String' in your configuration.
```

I've started to revisit this condition in my branch for #6612 that gives something like this:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$StringHandler required a bean of type 'java.lang.String' that could not be found:
	- missing required property 'spring.string.enabled': disabled on method 'string' in 'org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$TestPropertyAutoConfiguration'


Action:

Consider revisiting the conditions above or defining a bean of type 'java.lang.String' in your configuration.
```

Maybe we could add an extra (optional) parameter on `ConditionOutcome` that would be the annotation type and use that instead? That way, we could remove the hard-coded annotation at the beginning of every message and use the annotation (if present) rather than the condition in the textual format.

**Comment by philwebb** [comment]
I have [something](https://github.com/philwebb/spring-boot/tree/gh-6756) ready to go for this but it touches a lot of files so could do with a review before we merge.

**Comment by snicoll** [comment]
I've pushed a rebased version of the `NoSuchBeanDefinitionFailureAnalyzer` on my fork. Here are a couple of examples with the new infrastructure:

```
Parameter 0 of constructor in org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$StringHandler required a bean of type 'java.lang.String' that could not be found:
	- @ConditionalOnProperty spring.string.enabled did not find property spring.string.enabled: disabled on method 'string' in 'org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$TestPropertyAutoConfiguration'
```

It looks like that the property is duplicated in this message. How about `@ConditionalOnProperty did not find required property 'spring.string.enabled'`. I'd quote any such key (property, class, etc).


```
Constructor in org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$StringNameHandler required a bean named 'test-string' that could not be found:
	- @ConditionalOnBean (types: java.lang.Integer; SearchStrategy: all) did not find any beans: disabled on method 'string' in 'org.springframework.boot.autoconfigure.diagnostics.analyzer.NoSuchBeanDefinitionFailureAnalyzerTests$TestMissingBeanAutoConfiguration'
```

I think that one is quite good and the harmonization really helps 👍

**Comment by philwebb** [comment]
Note to self: fix comments made in the commit on my branch.
