### ISSUE TITLE
Remove "springBanner" and "springApplicationArguments" singleton

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6758]
commit https://github.com/spring-projects/spring-boot/commit/b9104c9337babdca6b2c0be5b7f68eb34a69755b has introduced `ApplicationInfo` wrapping the banner and the application arguments. We should remove those two singletons that are exposing the same information.

It's a breaking change so we need to wait for the next major release.

**Comment by philwebb** [comment]
I quite like the single purpose beans.

**Comment by snicoll** [comment]
Do I understand you'd prefer to expose the banner and arguments individually? If so, I can see the argument but I'd rather not register too many singletons that way. Having one bean that represents the current application is nice IMO, it's in the same direction as `BuildInfo` and `GitInfo`.

**Comment by philwebb** [comment]
I'm undecided, but it's quite nice that users can currently inject the `Banner` or `ApplicationArguments` without needing to go via a different bean.

**Comment by snicoll** [comment]
I already changed the code [in the remote shell](https://github.com/spring-projects/spring-boot/commit/b9104c9337babdca6b2c0be5b7f68eb34a69755b#diff-8db7f2c6da99858a01917f2477dfe6a7R14) and I can relate to that argument indeed...
