### ISSUE TITLE
Upgrade to spring-data-jpa 1.10.3

### ISSUE THREAD

**Issue by chrisburrell** [spring-projects/spring-boot#6760]
There a few bugs that would be worth bringing in as they prevent current use of Spring Boot 1.4.x currently. Notably DATAJPA-938 (https://jira.spring.io/browse/DATAJPA-938)

According to the JIRA instance, 1.10.3 is waiting release with the last bug already fixed (but wrong status?) 

Please could we upgrade to the latest release as soon as it's officially released?
Thanks
Chris

**Comment by wilkinsona** [comment]
Duplicates #6583
