### ISSUE TITLE
Support better testing for Spring Data

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6767]
Enhancement

I wrote this controller

```
@RestController( "registration" )
class RegistrationController {

    private final PasswordCredentialsRepository passwordCredentialsRepository;
    private final RepositoryEntityLinks entityLinks;


    RegistrationController(
        final PasswordCredentialsRepository passwordCredentialsRepository,
        final RepositoryEntityLinks entityLinks ) {
        this.passwordCredentialsRepository = passwordCredentialsRepository;
        this.entityLinks = entityLinks;
    }

    @RequestMapping( method = RequestMethod.POST )
    ResponseEntity<?> register( @Valid @RequestBody final PasswordCredentials passwordCredentials ) {
        User user = passwordCredentialsRepository.save( passwordCredentials.toRegisterEntity() ).getUser();

        Link link = entityLinks.linkToSingleResource( user.getClass(), user.getId() );
        return ResponseEntity.created( URI.create( link.getHref() ) ).build();
    }
}
```

and this test

```
@RunWith( SpringRunner.class )
@WebMvcTest( RegistrationController.class )
public class RegistrationControllerTest {

    @Autowired private MockMvc mvc;
    @Autowired private Gson gson;
    @MockBean private PasswordCredentialsRepository repository;
    @MockBean private RepositoryEntityLinks entityLinks;

    @Test
    public void validLogin() throws Exception {
        com.xenoterracide.rpf.security.dto.PasswordCredentials creds
            = new com.xenoterracide.rpf.security.dto.PasswordCredentials( "admin", "password123" );
        Class<PasswordCredentials> clazz
            = PasswordCredentials.class;

        when( repository.save( any( clazz ) ) ).then( invocation -> {
            PasswordCredentials argumentAt = spy( invocation.getArgumentAt( 0, PasswordCredentials.class ) );
            when( argumentAt.getId() ).thenReturn( 2L );
            argumentAt.setUser( spy( argumentAt.getUser() ) );
            when( argumentAt.getUser().getId() ).thenReturn( 1L );
            return argumentAt;
        } );

        when( entityLinks.linkToSingleResource( any( Class.class ), anyLong() ) )
            .thenReturn( new Link( "http://localhost:8080/users/1L" ) );

        String json = gson.toJson( creds  );

        this.mvc.perform(
            post( "/registration" )
                .contentType( MediaType.APPLICATION_JSON )
                .accept( MediaType.APPLICATION_JSON )
                .content( json ) )
            .andExpect( status().is2xxSuccessful() )
            .andExpect( status().isCreated() );
    }
}
```

I feel like the test is actually mocking much more than it should be. I can see mocking the repository itself since that is an interface to the database, but having to mock `RepositoryEntityLinks` I feel takes out testing of some very important parts of the controller (my new link could not remotely resemble a real link and I'd never catch it).

it might also be possible to auto-mock the repository save with auto setting of ids... 

obviously there are other ways to test this and I probably will, but I think this use case could be improved. 

maybe there could be an @TestSpringDataRest, and/or maybe a mockito test class that has a `returnFirstArgWithIds`. 

just suggestions, communicating a less than optimal situation. Perhaps there are better solutions than what I'm suggesting here.

**Comment by wilkinsona** [comment]
Neither the problem nor the solutions that you have suggested are specific to Spring Boot. If a solution is necessary, I think it would be better if it were provided by Spring Data REST. Please open a DATAREST JIRA if you wish to pursue this.

**Comment by xenoterracide** [comment]
Except that they only exist in a reduced context related specifically to `@WebMvcTest` but sure...

**Comment by wilkinsona** [comment]
Not in the example you've shown. You've mocked both your controller's dependencies, something that's easy without `@WebMvcTest`, and described a problem with that approach.

**Comment by xenoterracide** [comment]
well if I wasn't using `@WebMvcTest` I probably wouldn't be mocking them. If there were an alternative to mocking `RepositoryEntityLinks` I definitately wouldn't do that. I don't need database access to test this controller but I do need that to work properly, by mocking it, I've ensured that any testing of the `Location` header isn't good, because the `Location` header value I provide is `static`, meaning if I introduced a regression in my repository, this wouldn't catch it.

I mean I suppose there may be need for upstream support here but I have no idea what that need is.

It's not really worth arguing over, if you don't want to add more support to spring boot's special annotations for Spring Data * I can't make you. But saying that hateoas/data/data rest should add support for spring boot annotations... I suspect I already know what they'll say on that.

**Comment by wilkinsona** [comment]
> well if I wasn't using `@WebMvcTest` I probably wouldn't be mocking them

Then why are you using it? You've created a problem for yourself by trying to take a purely web-based approach to testing something that doesn't really have that separation.

>  having to mock RepositoryEntityLinks I feel takes out testing of some very important parts of the controller (my new link could not remotely resemble a real link and I'd never catch it).

That's always a problem with a Mock-based approach. You're purely testing the controller's interaction with the mock. That's what could, perhaps, be improved in Spring Data by providing something lighter weight that was known to work exactly as the real thing. Spring Data would be the best place for it so that the functionality can evolve together.

> But saying that hateoas/data/data rest should add support for spring boot annotations... I suspect I already know what they'll say on that.

That's not what I suggested. As I said above, there's nothing specific to Spring Boot about what you've tried. You could use pure MockMvc, standaloneSetup, and a couple of manually created mocks instead and have the same problem.
