### ISSUE TITLE
Inner-class @Configuration within a test without a test method is not excluded from scanning

### ISSUE THREAD

**Issue by plamentotev** [spring-projects/spring-boot#6768]
Hi,

I'm using Spring Boot 1.4.0 with `spring-boot-starter-web` and `spring-boot-starter-test` starters and the I think the test configuration exclusion is not working as [documented](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-excluding-config). Or at least the documentation is not clear enough.

I've created a [sample application](https://github.com/plamentotev/issues/tree/master/test-config) that demonstrates the issue.

It's a pretty simple Spring Boot application with only three classes. `Application` - the main class, `Config` - containing the application configuration. In this case it just makes a single bean (`ProductionService`) available for injection. Also I have nested `@Configuration` class inside abstract test class that makes a single bean (`TestService`) available for injection. :

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public abstract class AbstractTest {

    /*@Test
    public void test()
    {
    }*/

    @Configuration
    static class InnerConfiguration {

        @Bean
        TestService getTestService() {
            return new TestService();
        }
    }
}
```

and one test class that uses both `ProductionService` and `TestService`:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class ConfigTest {

    @Autowired
    private ProductionService service;

    @Autowired
    private TestService testService;

    @Test
    public void test() {
        assertNotNull(service);
        assertNotNull(testService);
    }

}
```

The interesting thing is that the test passes! But how? We don't have `TestSevice` bean configured. It looks like the nested `InnerConfiguration ` from `AbstractTest` is picked up. According to the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-excluding-config):

>`@TestComponent` and `@TestConfiguration` are only needed on top level classes.
>If you define `@Configuration` or `@Component` as inner-classes within a test,
>they will be automatically filtered.

Now if you remove the comment around
```
    /*@Test
    public void test()
    {
    }*/
```
inside `AbstractTest` then `ConfigTest` would fail as expected - the `TestService ` instance will not be available for autowiring:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [testconfig.service.TestService] found for dependency [testconfig.service.TestService]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
        ... 35 more
```

While the documentation is not very explicit what is considered "inner-classes within a test", I think the fact that the class is annotated with `SpringBootTest` make it a test class. Or at least the documentation should be explicit that test class is a class with at least one test method. But I consider the second option less natural. I mean when you have class annotated with `*Test` annotation you expect to be considered as test class even if there are no test methods - especially if it's abstract.

**Comment by philwebb** [comment]
Thanks for the detailed analysis. I think we need to extended the logic in `TestTypeExcludeFilter.isTestClass` so that as well as checking for `@Test` methods we also check for `@RunWith`.

**Comment by sbrannen** [comment]
@philwebb, I'd suggest we not limit the `isTestClass` logic to JUnit 4 only.

For example, the Spring TestContext Framework has supported TestNG since Spring Framework 2.5, and Spring Framework 5.0 milestones already support the JUnit Jupiter programming model in JUnit 5.

With that in mind, I'd recommend as a bare minimum checking for the presence of any of the following annotations.

- `org.junit.Test`
- `org.testng.annotations.Test`
- `org.junit.jupiter.api.Test`
- `org.junit.jupiter.api.TestFactory`

In general, Boot should also consult `org.springframework.core.type.ClassMetadata.isAbstract()`, since an `abstract` class is technically never a _test class_.

**Comment by sbrannen** [comment]
In case it wasn't clear in my previous comment, checking for the presence of `@RunWith` would limit Boot's testing support to JUnit 3 and JUnit 4, which is something we want to avoid.

**Comment by philwebb** [comment]
I've opened #6898 to deal with JUnit 5 additions (we won't do it just yet since it isn't officially supported)

**Comment by philwebb** [comment]
> In general, Boot should also consult org.springframework.core.type.ClassMetadata.isAbstract(), since an abstract class is technically never a test class.

We're trying to filter out config that's part of a test so we can't rely on abstract.

**Comment by eddiewebb** [comment]
Im sorry, perhaps being daft, but I don't understand why this was implemented as is.

If i have an abstract class to consolidate the testServices required across a set of classes:
```
@SpringBootTest(webEnvironment= SpringBootTest.WebEnvironment.RANDOM_PORT)
@RunWith(SpringRunner.class)
public abstract class AbstractWebTests {

    @LocalServerPort
    private int serverPort;
    @Autowired
    WebDriver webDriver;

    protected String getBaseUrl() {
        return "http://localhost:" + serverPort;
    }

    @org.springframework.boot.test.context.TestConfiguration
    static class TestConfiguration {
        @Bean
        public WebDriver webDriver(){
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setJavascriptEnabled(true);
            return new PhantomJSDriver(capabilities);
        }
    }
}
```

And extend that through specific implementations:
```
public class HomePageTests extends AbstractWebTests {

    @Test
    public void testHomePageLoads() throws Exception {
        webDriver.get(getBaseUrl());
        assertThat("Did not find welcome text",webDriver.findElement(By.id("welcome")).getText(),containsString("Hello Circle CI!"));
    }
```

Why is that not a valid pattern? As is it will fail with:
`rror creating bean with name 'com.edwardawebb.circleci.demo.HomePageTests': Unsatisfied dependency expressed through field 'webDriver'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.openqa.selenium.WebDriver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`



But as it stands you have to repeat the TestConfiguration in every subclass.

**Comment by philwebb** [comment]
@eddiewebb That's the standard behavior of Spring Frameworks `AnnotationConfigContextLoaderUtils.detectDefaultConfigurationClasses`. It doesn't search the class hierarchy. 

Try using the `classes` attribute of `@SpringBootTest`:

```java
@SpringBootTest(webEnvironment= SpringBootTest.WebEnvironment.RANDOM_PORT, classes=AbstractWebTests.TestConfiguration.class)
@RunWith(SpringRunner.class)
public abstract class AbstractWebTests {

    @LocalServerPort
    private int serverPort;
    @Autowired
    WebDriver webDriver;

    protected String getBaseUrl() {
        return "http://localhost:" + serverPort;
    }

    @org.springframework.boot.test.context.TestConfiguration
    static class TestConfiguration {
        @Bean
        public WebDriver webDriver(){
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setJavascriptEnabled(true);
            return new PhantomJSDriver(capabilities);
        }
    }
}
```

If you have further questions please as on stackoverflow.com as we prefer to keep the issue tracker for bugs and enhancements only.

**Comment by torsten-github** [comment]
Same pitfall for me. Thanks.

Why does Spring not search in the class hierarchy for nested Configurations, but does for other annotations, like `@SpringBootTest` and `@ActiveProfiles` etc. That's really wired.

**Comment by snicoll** [comment]
@torsten-github the reason why is explained in the comment just above yours. As for `@Import`, if you're explicitly requesting a class to be added, I don't see anything weird that it's being added.

The comment just above yours also state that questions must be asked on StackOverflow. So if you need more help, please do that.
