### ISSUE TITLE
Filter installed ahead of spring security filters

### ISSUE THREAD

**Issue by ageery** [spring-projects/spring-boot#677]
In EmbeddedWebApplicationContext.getServletContextInitializerBeans(), beans are ordered within their type but not across types, even if the underlying types are the same.  This causes a problem if FilterRegistrationBean is used to define a filter (e.g., a Wicket filter).  Because FilterRegistrationBean implements ServletContextInitializer, its filter is added to the list of initializers before the spring security filters, which are added as regular filters.  When the application launches, the spring security filters are added after the other filters.

**Comment by ceefour** [comment]
I also got this problem. Static resources are Spring Security-ized just fine, but Wicket pages are not Spring Security-secured at all. Even saving {{SecurityContextHolder.getContext()}} to the {{HttpSession}} doesn't help, as there's no filter to retrieve the (existing) {{SecurityContext}} from the {{HttpSession}} on the next request.

**Comment by ceefour** [comment]
Maybe an additional annotation such as `@RequiresSecurity` that can be added to the `FilterRegistrationBean` ?

**Comment by ceefour** [comment]
Info: `springSecurityFilterChain` bean is defined by `org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration`

**Comment by dsyer** [comment]
That's not a workaround. That's just the way you have to register the filters if you want a custom order. Maybe you should avoid using `@EnableWebSecurity` if you don't want to have to do that?

**Comment by ceefour** [comment]
So to use Spring Boot, I must disable `@EnableWebSecurity` when using my own `WebSecurityConfigurer`? (so I can use my own `AuthenticationManager`)

**Comment by dsyer** [comment]
I'm not sure what you mean by "disable". You either use it (and accept the defaults provided by Spring Boot), or you don't (and provide your own configuration).

**Comment by ceefour** [comment]
What I mean is that I'd like to use Spring **Boot**'s security configuration (which sets `springSecurityFilterChain` order to 0 instead of Spring **Security**'s default of `LOWEST_PRECEDENCE`) *except* for `AuthenticationManager` which I will provide myself.

In my understanding from what you said before:

> Maybe you should avoid using `@EnableWebSecurity` if you don't want to have to do that?

`@EnableWebSecurity` is only used by _Spring Security_, not _Spring Boot_, is that right ? So I should remove `@EnableWebSecurity` from my `WebSecurityConfigurer` ?

**Comment by dsyer** [comment]
> So I should remove @EnableWebSecurity from my WebSecurityConfigurer ?

Like I said, it's up to you. That's what I would do (allow Boot to do as much as it wants).

**Comment by nickspacek** [comment]
I'm a little late to the party, but I wanted to voice some support for the issue that @ceefour raised, and that in fact a fix seems to be on the plate for Spring Boot 1.3.0: #3703

**Comment by dsyer** [comment]
This issue is closed. As far as I know there is nothing concrete outstanding and I didn't see the relevance of #3703. Maybe you could open a new issue if you have a feature request or a problem?

**Comment by nickspacek** [comment]
I arrived here from Google when trying to figure out how to change only the Spring Security Filter Chain's `@Order`, and issue #3703 has the answer. I believe this is also what @ceefour was asking about in his last reply.

**Comment by dsyer** [comment]
#3703 is closed and marked for 1.3, so I guess if it has the change you want then it is available now. I don't think @ceefour really cared about the filter order in the container.

**Comment by tony19870604** [comment]
i want custome FilterInvocationSecurityMetadataSource in spring security boot ..

**Comment by dsyer** [comment]
This issue is closed. If you have a new requirement, please open a new ticket. If you have a usage question, please go to StackOverflow.
