### ISSUE TITLE
Add builder methods on ServletRegistrationBean / FilterRegistrationBean to allow chaining

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#6771]
To reduce noise in `@Configuration` classes, it would be nice if this methods could be chainable in a fluent style. For example, the following:

``` java
  @Bean
  public FilterRegistrationBean urlRewrite() {
    val urlRewrite = new FilterRegistrationBean();
    urlRewrite.setOrder(0);
    urlRewrite.setFilter(new UrlRewriteFilter());
    urlRewrite.addInitParameter("confPath", "urlrewrite.xml");
    urlRewrite.addInitParameter("statusEnabled", "false");

    return urlRewrite;
  }
```

could instead be written as:

``` java
  @Bean
  public FilterRegistrationBean urlRewrite() {
    return new FilterRegistrationBean();
       .order(0)
       .filter(new UrlRewriteFilter())
       .initParameter("confPath", "urlrewrite.xml")
       .initParameter("statusEnabled", "false");
  }
```

**Comment by philwebb** [comment]
I don't think that we should change the existing beans since the setter style tends matches with the rest of Spring. I'd rather introduce a dedicated builder if we want a fluent style API.

**Comment by btiernay** [comment]
Ya, that might be best. Could be a static method on `FilterRegistrationBean` for example.

**Comment by ayudovin** [comment]
@philwebb, what do you think about creating additional class like `FilterRegistrationBeanBuilder` and `ServletRegistrationBeanBuilder` ?

**Comment by philwebb** [comment]
Thanks for offer @ayudovin.

Looking at this issue again, given the limited number of votes and the limited number of servlet/filter registrations in most apps I think we should just close this one.
