### ISSUE TITLE
Add support for spring-boot-configuration-processor to create markdown file for configuration properties.

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#6772]
It would be great if there was the ability to instruct the `spring-boot-configuration-processor` to generate a markdown file (perhaps `CONFIG.md` by default) for all configuration properties detected in the current project. This could then be linked to from a `README.md` in Github, etc. In a sense, this is similiar in spirit to the REST docs project, but applied to configuration params. The benefit is that the developer doesn't need to maintain 2 sets of documentation resources to describe configuration properties defaults, etc.

**Comment by philwebb** [comment]
I'm not too keen on complicating the annotation processor. We've done some work already to extract details from the meta-data json file and create asciidoctor snippets. I generally prefer this approach since all the information is in the meta-data file anyway.

**Comment by btiernay** [comment]
@philwebb Could you point me toward that work? 

I was hoping not to have to add a custom build processor to add what seems like a universally useful feature.

**Comment by philwebb** [comment]
I think it was either @snicoll or @wilkinsona that wrote it.

BTW: I agree that it might be universally useful, I'm just not sure that we should add it directly to Spring Boot if it can live elsewhere.

**Comment by snicoll** [comment]
First of all, a build processor is the wrong tool for the job IMO. I am guessing you'd like that `CONFIG.md` file to be placed alongside the `README.md` at the root of the project. Annotation processors are meant to create resources in the compilation directory only.

We have all that's needed to make that work however. First of all, we need to be able to parse the meta-data to get some repository, see [spring-boot-configuration-metadata](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-tools/spring-boot-configuration-metadata). I've built a project with a bunch of tools around that, see https://github.com/snicoll-scratches/spring-boot-config

I am using that project to generate the [configuration changelog page on the wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Configuration-Changelog) but also as a management tool to check the consistency between the doc and the meta-data. Ultimately, we want to generate the appendix based on the meta-data but we're not there yet. Perhaps you could help?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
