### ISSUE TITLE
Add @ConfigurationDescription annotation for adding a descriptive message to configuration metadata.

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#6774]
The idea is to avoid having to write a `additional-spring-configuration-metadata.json` file to provide a description for a configuration element on a `@ConfigurationProperties` annotated class. This feature is similar in spirit to the core `org.springframework.context.annotation.Description` annotation.

**Comment by snicoll** [comment]
> avoid having to write a additional-spring-configuration-metadata.json file to provide a description for a configuration element

Why would you have to do that? The documentation states that adding a javadoc on the field will pick up that as a description.

**Comment by btiernay** [comment]
> The processor will pick up both classes and methods that are annotated with @ConfigurationProperties. The Javadoc for field values within configuration classes will be used to populate the description attribute.

Must have missed that. Apologies!
