### ISSUE TITLE
Upgrade to spring-amqp 1.6.2 

### ISSUE THREAD

**Issue by chrisburrell** [spring-projects/spring-boot#6788]
Hi

Please can we upgrade to spring-amqp 1.6.2 in Spring boot 1.4.1.  In particular AMQP-633 is a blocker for us  https://jira.spring.io/browse/AMQP-633

Thanks
Chris

**Comment by wilkinsona** [comment]
1.6.2 isn't out yet

**Comment by snicoll** [comment]
I just asked @garyrussell and he's going to release it in the coming days.

**Comment by garyrussell** [comment]
1.6.2 is in https://repo.spring.io/release and should be in maven central within a few hours.
