### ISSUE TITLE
Actuator - HTTP Status Line Missing Reason-Phrase

### ISSUE THREAD

**Issue by stevelaw** [spring-projects/spring-boot#6789]
Prior to Spring Boot 1.4.0 the the Actuator health endpoint would return an "OK" reason-phrase after the HTTP status line, however after that point it was dropped.  See below for examples:

**Spring Boot 1.3.4**

curl -i localhost:8080/manage/health                                                                                                                         
HTTP/1.1 200 OK

**Spring Boot 1.4.0**

curl -i localhost:8080/manage/health                                                                                                                       
HTTP/1.1 200

**Comment by wilkinsona** [comment]
This is standard behaviour for Tomcat 8.5. See #6548.
