### ISSUE TITLE
ConfigurationProperties overwrites with list behaves oddly

### ISSUE THREAD

**Issue by cleiter** [spring-projects/spring-boot#6793]
I have an application.yml:

```
service:
  hosts:
    - a
```

And the configuration:

```
@Component
@ConfigurationProperties("service")
class Config {
    private List<String> hosts;

    public List<String> getHosts() { return hosts; }

    public void setHosts(List<String> hosts) { this.hosts = hosts; }
}
```

When i set the environment variable `SERVICE_HOSTS=b,c` the result in my `Config` is actually `[a, c]` when I expected `[b, c]`. I tried if this is specific to lists but the same happens with arrays. Same behavior in 1.4.0.RELEASE and current 1.4.1.BUILD-SNAPSHOT.

**Comment by cleiter** [comment]
I had a closer look, the list gets initially set to `[b, c]` and then later element 0 is overwritten in `AbstractNestablePropertyAccessor#setPropertyValue:378` by calling `list.set(index, convertedValue)`.

**Comment by snicoll** [comment]
It's another incarnation of #4313 - @philwebb I think the `PropertySource` check did not take system properties into account maybe?

**Comment by philwebb** [comment]
Possibly also related to #6620

**Comment by snicoll** [comment]
@philwebb you closed #6620. How about this one?

**Comment by philwebb** [comment]
@snicoll I think it's different so can't be closed just yet.

**Comment by philwebb** [comment]
I have a feeling this is going to be pretty hard for us to fix until we can cleanup how flexible binding works (schedule for Spring Boot 2.0). The problem is `PropertySourcesPropertyValues` is not able to apply the same rules that it uses to detect collection.

What you effectively end up with are the value:
```
SERVICE_HOSTS=b,c
service.hosts[0]=a
```

The first property is applied and converted to a list, then the second one replaces the first item.

The horrible workaround for now is to change your yaml to:

```
service:
  hosts: a
```

**Comment by cleiter** [comment]
Thanks for your response. My workaround is to use a simple string and split it myself.

I understand this is probably not possible to fix without breaking things for someone else. I'd recommend though that there should be a big warning in the docs that elements of lists/arrays get merged element wise and are not overwritten as a whole. Depending on the nature of the lists this effect could be really bad and it will only show up when you actually overwrite list properties, worst case in production.

**Comment by philwebb** [comment]
@cleiter Good point, I've raised #6911 to address that.

**Comment by mbhave** [comment]
[Test case](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/CollectionBinderTests.java#L244) for the fix.
