### ISSUE TITLE
Simple implementations for CounterService and GaugeService

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-boot#6794]
I'd like to propose a minor improvement, inspired by this question:
http://stackoverflow.com/questions/39225963/testing-that-custom-spring-boot-autoconfiguration-is-valid

I use Spring Boot with different counters implemented with Spring Actuator. So my application strongly depends on `CounterMetrics` and `GaugeService` and cannot run without them - even for tests, for example.

To solve this I've created minimalistic implementations of these two services - they just log each method call, nothing else. Now I use these implementations to create test beans and everything works great.

So the question is... Maybe such implementations should be in Spring Actuator itself? Maybe even their instances should be created automatically when you use `@SpringBootTest`?

**Comment by wilkinsona** [comment]
I don't think there's any need for Boot to provide dummy implementations of those interfaces. If you need the beans to be there and don't want to use the Actuator's implementations I'd recommend using mocks instead. Given that you're testing some auto-configuration using `@SpringBootTest` and `@MockBean` probably isn't appropriate. You can return a manually created mock from a `@Bean` method instead.
