### ISSUE TITLE
Jackson XML serialization ignoring application.configuration properties

### ISSUE THREAD

**Issue by jordanms** [spring-projects/spring-boot#6796]
Hi,

I'm using RestTemplate to access a service which consumes XML. I have added jackson-dataformat-xml, jackson-datatype-jsr310 and jackson-module-parameter-names to my pom (all versions coming from parent pom). Also have configured the parameter names module as follow:
```java
@Bean
public Module parameterNamesModule() {
    return new ParameterNamesModule(JsonCreator.Mode.PROPERTIES);
}
```
In my application.properties I have the following configuration:
```
spring.jackson.serialization.write_dates_as_timestamps=false
spring.jackson.serialization-inclusion=non_null
```
The problem is that those parameters are ignored when serializing my Objects to XML. It works fine when serializing to JSON. I have done some debugging and noticed that many XmlMapper are instantiated, but only 2 of them have the properties set as expected and none of them are used to serialize my Objects.

I also have tried to define my own XmlMapper bean, which was also not used in the serialization:
```java
    @Bean
    @Primary
    public XmlMapper xmlMapper() {
        XmlMapper xmlMapper = new XmlMapper();
        xmlMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        return xmlMapper;
    }
```

To bypass the first problem I had to write my own JsonSerializer for OffsetDateTime and use *@JsonInclude(NON_NULL)* in my classes for the second.

Spring boot version: 1.4.0.RELEASE

**Comment by wilkinsona** [comment]
Sounds like you've got quite a few moving parts involved. Can you please provide a small sample that reproduces the problem so that we can be sure we're looking at the right thing?

**Comment by jordanms** [comment]
Thanks for the answer @wilkinsona 

I'm writing the example that you asked. Just to add a missing part from my description, I also create the RestTemplate bean as follow:
```java
   @Bean
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }
```
For some reason I think that the problem is related to that :)

**Comment by wilkinsona** [comment]
Yes, that'll be (part of) the problem. If you create your own `RestTemplate` it'll be using the default message converters that don't know anything about your customised mapper. If you use the auto-configured `RestTemplateBuilder` to create your `RestTemplate` you should get the behaviour you were hoping for as it will use the auto-configured message converters that do know about your customised mapper.

**Comment by jordanms** [comment]
Thanks once again! Problem solved!

I inject RestTemplateBuilder and then I build the RestTemplate as follow:
```java
    @Inject
    private RestTemplateBuilder builder;

    @Bean
    public RestTemplate restTemplate() {
        return builder.build();
    }
```
One thing that I don't understand is why RestTemplate is not inject out of the box. If I remove the bean declaration I get:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.web.client.RestTemplate] found for dependency [org.springframework.web.client.RestTemplate]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
```
But this is another problem ;)

**Comment by wilkinsona** [comment]
We don't directly auto-configure a `RestTemplate` bean as it's very common that people will want to customise it in some way. `RestTemplateBuilder` is intended to make that customization as straight forward as possible.

**Comment by caporeinf** [comment]
Try:
```

@Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder.build();
    }
```
Have a nice day!
