### ISSUE TITLE
Spring Data Repository cannot be spied on using @SpyBean

### ISSUE THREAD

**Issue by maverick1601** [spring-projects/spring-boot#6797]
Bug Report/Enhancement

Since Spring Boot 1.4.0 @SpyBean can be used to spy on beans within the ApplicationContext. Unfortunately, Spring Data Reposity Beans seem to be added to the BeanFactory too late, for the MockitoPostProcessor to find the bean reference. Thus, it tries to add a new RootBeanDefinition for the spied Repository interface, which results in an instantiation error.

**Comment by wilkinsona** [comment]
Duplicates #6541
