### ISSUE TITLE
ServletContext.getRealPath does not return proper path with static-locations resources

### ISSUE THREAD

**Issue by ekfliu** [spring-projects/spring-boot#6799]
with settings
```
spring:
  resources:
    static-locations: /public/
```
and code
```
request.getServletContext().getRealPath("/css/style.css");
```
Expects  "..../public/css/style.css" but got "..../css/style.css"

It looks like getRealPath does not take static-locations settings into account when obtaining the real path. Unfortunately some third party library uses it and sort of break the functionality of it.

**Comment by wilkinsona** [comment]
That's to be expected. The servlet container doesn't know anything about serving static resources from the classpath as that's a Spring MVC feature. Furthermore, you can't really rely of `getRealPath` to return anything particularly sensible. A common interpretation of the spec is that it should return a path to a file that doesn't exist (see https://issues.jboss.org/browse/UNDERTOW-373 for details). That's essentially what's happening here. As far as the servlet container is concerned there's no `/css/style.css` file yet it's still returning a path for it.
