### ISSUE TITLE
JpaRepositories scanning only takes the package name of the Application class

### ISSUE THREAD

**Issue by raymondchen625** [spring-projects/spring-boot#6800]
If my `JpaRepositories` classes are not under the package of the main Application class of Spring Boot application, I have to add an annotation `@EnableJpaRepositories` like this: 

```java
@SpringBootApplication
@EnableJpaRepositories(basePackages="com.package.jpalocation")
```

I can't do it by setting the `scanBasePackages` attribute of `@SpringBootApplication`. I think Spring Boot somehow only takes the package name of the startup class, unless there is explicit definition in `@EnableJpaRepositories`.

**Comment by philwebb** [comment]
That's correct and one reason why we [recommend the following code structure](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-structuring-your-code). If you deviate from those options you need to specify explicit packages for Spring Data (as you're doing). The `scanBasePackages` attribute is for component scanning, it isn't picked up by Spring Data.

**Comment by philwebb** [comment]
This type of question is best asked on stackoverflow in the future.
