### ISSUE TITLE
Servlet context initialization parameter for spring.config.location is ignored

### ISSUE THREAD

**Issue by skidr0w** [spring-projects/spring-boot#6801]
I'm using Spring Boot 1.4.0 deployed as a war file to Tomcat 8.5. According to the documentantion, I should be able to configure the spring.boot.location configuration parameter by passing it via Servlet context initialization parameter.

> If you are running in a container then JNDI properties (in java:comp/env) or servlet context initialization parameters can be used instead of, or as well as, environment variables or system properties.
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

When I add this line to my context.xml file in Tomcat
`<Parameter name="spring.config.location" value="file:/some/path/" />`
the application.properties file at this path is ignored and not read.

If I however use a JNDI entry like
`<Environment name="spring.config.location" value="file:/some/path/" type="java.lang.String" />`
the application.properties file is read and will be used.

**Comment by philwebb** [comment]
Out of interest is this something that was previously working with Spring Boot 1.3?

**Comment by wilkinsona** [comment]
I don't think this has ever worked. Unless you're using `ContextLoader`, `StandardServletEnvironment` servlet-based property sources aren't initialized until `prepareRefresh` is called on the web application context which is too late for `ConfigFileApplicationListener` to make use of their properties.

**Comment by wilkinsona** [comment]
To initialise the environment with the servlet context early enough (before `ConfigFileApplicationListener`, it needs to be done in a `SpringApplicationRunListener`. As it stands, they're only loaded via `spring.factories` which makes passing accessing the servlet context tricky (we'd have to use thread local or similar).
