### ISSUE TITLE
Upgrade to Hopper SR3 snapshots

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6805]
It would be cool if Boot could already upgrade to Spring Data Hopper SR3 snapshots as we ship a fix that in turn relies on a [fix in Spring Framework](https://jira.spring.io/browse/SPR-14648) about to be shipped with 4.3.3 and 4.2.8.

The release dates for Spring Framework 4.3.3 and Boot 1.4.1 look quite close to each other and I want to avoid any surprises if we have to squeeze our Hopper SR1 release in between.

**Comment by wilkinsona** [comment]
We've been building against Hopper snapshots since early August: https://github.com/spring-projects/spring-boot/commit/a729d48bd35860c8a9c39a53341560c46fb75d23

**Comment by olivergierke** [comment]
Awesome, @philwebb wasn't sure in the call we just had, that's why I created the ticket :).
