### ISSUE TITLE
Filter any AbstractRoutingDataSource from dbHealthIndicator

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6806]
The current `dbHealthIndicator` currently includes all `DataSource` beans, however, `AbstractRoutingDataSource` almost never needed directly. By default we should probably filter it out.

**Comment by natetyler** [comment]
@philwebb I'm putting multiple datasources behind an AbstractRoutingDataSource, but they are not registered as beans because they are instantiated dynamically at run time. Does actuator have any "out of the box" way to handle this scenario?

**Comment by vpavic** [comment]
@natetyler There is an existing PR to provide functionality that will allow you to register `HealthIndicator`s in runtime - take a look at #4894 and #4965.

**Comment by snicoll** [comment]
@natetyler how about exposing your own `HealthIndicator` that uses your `AbstractRoutingDataSource` and provides the desired feature? `DataSourceHealthIndicator` is public API so you could create an instance for each of your data source and combine the results yourself (`CompositeHealthIndicator` can help with that).

**Comment by natetyler** [comment]
@vpavic @snicoll Thanks for the prompt replies. I ended up going with `CompositeHealthIndicator` grouping multiple `DataSourceHealthIndicator` and it's perfect.
