### ISSUE TITLE
Provide a way to flag `DataSource` beans as essential or non-essential for the `dbHealthIndicator`

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6807]
If the `dbHealthIndicator` is being used to show results from multiple datasources, it's possible that some may be critical to operation, where as others don't actually prevent a service from running if they are down. It would be nice if the aggregate `dbHealthIndicator` could have more smarts about knowing when a `DataSource` is really critical or not.

**Comment by wilkinsona** [comment]
Superseded by #14022.
