### ISSUE TITLE
Spring Tool Suite Maven Integration breaks when using Version 1.4.0.Release of spring-boot-starter-parent

### ISSUE THREAD

**Issue by kmb385** [spring-projects/spring-boot#6814]
Disclaimer:  This may be a Spring Boot Issue or it may be a Spring Tool Suite Issue.

**Summary**

When I build a New Spring Starter Project within Spring Tool Suite using Boot Version 1.4.0 I cannot add any dependencies managed by boot to the project using the Maven Integration within the IDE.  If I modify the pom.xml file to refer to version 1.3.6.RELEASE of the spring-boot-starter-parent artifact the issue is resolved.

**Steps to Recreate within STS 3.8.0 Release Build Id:  201606301029**

1.  Click File > New > Spring Starter Project
2.  Create a new Maven project
3.  Select Boot Version 1.4.0
4.  Click Finish to build the project
5.  Open the projects pom.xml file
6.  Navigate to the dependencies tab
7.  Click add to open the dialog, then type "org.springframework.integration"
8.  Select any dependency tagged as "(managed") and they will not populate the artifact and group id

**Work Around**

Within the pom.xml file change:

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

to
```

       <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.6.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

**Comment by snicoll** [comment]
@kmb385 please report that against the [Spring Tool Suite issue tracker](https://issuetracker.springsource.com/browse/STS)
