### ISSUE TITLE
Add XADataSourceBuilder

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6824]
There are lots of super features in `XADataSourceAutoConfiguration` that are basically unreachable unless you use the auto config. In particular if you need more than one `DataSource` it's useful to have a Java API, as opposed to a config file.

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
