### ISSUE TITLE
Expose autoconfigured JmsTemplate to @ConfigurationProperties

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6825]
The `@Bean` method that creates a `JmsTemplate` in `JmsAutoConfiguration` is actually pretty complicated, so I don't really want to copy it to customize something simple like setting the receive time out. Any problem adding `@ConfigurationProperties("spring.jms.template")` to that `@Bean`? Or something?

To work around this I have ended up adding a `BeanPostProcessor` (yuck). If `@ConfigurationProperties` isn't the right tool, maybe a customizer bean?

**Comment by snicoll** [comment]
We're not keen to bind such type directly (see https://github.com/spring-projects/spring-boot/issues/3659#issuecomment-173561580). In the case of `JmsTemplate` we already set `pubSub` and `messageConverter` via auto-configuration so exposing a property for that would be weird.

Having said that, Spring AMQP has a `spring.rabbitmq.template` and we should do the same for JMS.
