### ISSUE TITLE
Mockito fails to verify mocked @Service when service contains @Retryable methods

### ISSUE THREAD

**Issue by pearj** [spring-projects/spring-boot#6828]
I'm using `spring-boot 1.4.0.FINAL` and I'm having trouble when I have a mocked `@Service` which has `@Retryable` annotations in the class.   When I call `Mockito.verify()` I get an `UnfinishedVerificationException` exception:

```
12:05:36.554 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - After test method: context [DefaultTestContext@5ec0a365 testClass = MockBatchTestWithRetryVerificationFailures, testInstance = sample.batch.MockBatchTestWithRetryVerificationFailures@5abca1e0, testMethod = batchTest@MockBatchTestWithRetryVerificationFailures, testException = org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at sample.batch.service.MyRetryService$$FastClassBySpringCGLIB$$7573ce2a.invoke(<generated>)

Example of correct verification:
    verify(mock).doSomething()
```

This looks very similar to #5837, in fact, I managed to hack to workaround based off that issue:

See: `sample.batch.MockBatchTestWithRetryVerificationFailuresWorkaround.batchTest()`
```java
@Test
public void batchTest() throws Exception {
    service.process();

    if (service instanceof Advised) {
        service = (MyRetryService) ((Advised) service).getTargetSource().getTarget();
    }

    verify(service).process();
    validateMockitoUsage();
}
```

I have put an example project together here that reproduces this issue: https://github.com/pearj/spring-boot-batch-retry-issue
For the failure case see: `sample.batch.MockBatchTestWithRetryVerificationFailures.batchTest()`

Is it possible for a transparent fix somehow?

I also have this on [stackoverflow](http://stackoverflow.com/q/39341119/359999)

**Comment by philwebb** [comment]
Could you please give the latest SNAPSHOT version a quick try as we've recently fixed a number of very similar issues.

**Comment by pearj** [comment]
How recent? I tried 1.41.SNAPSHOT today

**Comment by pearj** [comment]
1.41.BUILD-SNAPSHOT that is

**Comment by philwebb** [comment]
That's the most recent. Thanks for giving it a go.

**Comment by wilkinsona** [comment]
Looks like the build's broken so the latest snapshot is stale. Something to do with the Bamboo upgrade?

**Comment by philwebb** [comment]
I don't think there's much we can do automatically when the `mock` method is directly used, however, if you use `@MockBean` with the latest snapshot then I think things will work:

```java
@ActiveProfiles("Test")
@ContextConfiguration(classes = { SampleBatchApplication.class }, loader = AnnotationConfigContextLoader.class)
@RunWith(SpringRunner.class)
public class MockBatchTestWithRetryVerificationFailures {

	@MockBean
	MyRetryService service;

	@Test
	public void batchTest() {
		service.process();
		verify(service).process();
		validateMockitoUsage();
	}

}
```

**Comment by pearj** [comment]
Thanks, Phil, you're right, `@MockBean` does seem to solve the problem in my example project using `1.4.0.RELEASE` (doesn't appear to require the latest snapshot).  Although in my actual project it didn't help for some reason, but it changed the exception from `UnfinishedVerificationException` to `UnfinishedVerificationException` when using `@MockBean`.  But both can be solved by unwrapping Aop.

I have a helper method to unwrap aop, so I'll just use that for the moment, it's not too bad.

**Comment by sbrannen** [comment]
@pearj, there's no need to maintain your own helper method for that. See `AopTestUtils` from `spring-test`. 😉

**Comment by pearj** [comment]
@sbrannen thanks for that, although, it seems the generics in that method doesn't agree with eclipse, and it thinks the type is of type `Object` instead of the original type.

The signature is:
```java
public static <T> T getTargetObject(Object candidate)
```

But I think it should be
```java
public static <T> T getTargetObject(T candidate)
```

That way you can use it inline with `verify` without having to do any casting unless I'm missing something?

Otherwise it seems you have to do this:
```java
((MyAopWrappedBean)verify(AopTestUtils.getTargetObject(mybean))).theMethod();
```

instead of just

```java
verify(AopTestUtils.getTargetObject(mybean)).theMethod();
```
