### ISSUE TITLE
CLI extensions cannot load AST transformations

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6829]
This change made a special case for loading `Command` instances: 270530c4. But I think it neglected to take into account that `ServiceLoader` is used for other things (AST transformations for instance, and compiler autoconfigurations).  Consequently, extensions can install commands, but none of the other things. Probably the classloader that we built for the commands needs to be made available in the GroovyCompiler more generally?

**Comment by philwebb** [comment]
The commit message included /cc @wilkinsona but I'm not sure that triggers a notification. Re-opening just to confirm the change is OK.

**Comment by wilkinsona** [comment]
It looks OK to me.
