### ISSUE TITLE
Add concise way of adding second/third datasource with second/third JPA EntityManager

### ISSUE THREAD

**Issue by cesnek** [spring-projects/spring-boot#6830]
Please support concise way of adding second/third datasource with second/third JPA `EntityManager`.

We have independent module with second db connection and second JPA `EntityManager`.
This module is not easily plugged into boot application.

- First - it shuts off auto-configuration of main datasource and main `EntityManager`.
- Second - there is classes looking for `EntityManager` and `LocalContainerEntityManagerFactoryBean` ignoring `@ Primary`
 
My working hack is:
- extra define main datasource and main `LocalContainerEntityManagerFactoryBean` with `@ Primary`
- modify `PersistenceAnnotationBeanPostProcessor`, `EntityManagerBeanDefinitionRegistrarPostProcessor`, `EntityScanRegistrar` to respect `@Primary`

I think there should be more straightforward way.

**Comment by philwebb** [comment]
I assume that you've followed the [advice in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources)? Are you able to provide a sample project showing the modifications that you made? 

Modifying `EntityScanRegistrar` is especially unusual since you'd normally define the scanned packages directly on the `EntityManagerFactoryBuilder` using the `packages` method.

**Comment by cesnek** [comment]
The main problem is with existing code:

`@Autowired private EntityManager em;` - fail with "not single bean", not respecting @ Primary
`@PersistenceContext EntityManager em;` - existing code fail, because not specified "unitName"
`@EntityScan` - erase and overwrite "PackagesToScan" on all  defined LocalContainerEntityManagerFactory (we use many @EntityScan in many modules)

**Comment by philwebb** [comment]
I'm not sure where that code exists. I think we're going to need a complete sample application to really understand what can be improved.

**Comment by snicoll** [comment]
@philwebb we have one already: https://github.com/snicoll-demos/demo-multi-entity-managers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by cesnek** [comment]
OK, I push sample https://github.com/cesnek/secondJpaManager with comments.

**Comment by philwebb** [comment]
I'm not sure what we could do in Boot to make things easier. I think your use cause is fairly unusual and anything that we add to Boot is likely to add complexity.

**Comment by cesnek** [comment]
In fact it is not that hard.

Just add one line to EntityManagerBeanDefinitionRegistrarPostProcessor.java
`emBeanDefinition.setPrimary(definition.getBeanDefinition().isPrimary());`

And modify one line in PersistenceAnnotationBeanPostProcessor.java to
`private transient String defaultPersistenceUnitName = "##default";`
