### ISSUE TITLE
Setting additional JavaMail properties in yml file does not work

### ISSUE THREAD

**Issue by elbitoy** [spring-projects/spring-boot#6834]
I'll try to set additional JavaMail properties in my application yaml file as described in here (property spring.mail.properties.*):
    http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

I set the values like this:
```
spring:
    mail:
       host: host
       port: port
       username: user      
       password: pass
       properties.mail.smtp:
                 auth: true
                 starttls.enable: true
```

However, when using the JavaMailSender the additional properties are not set: mail sending fails because starttls.enable is set to false (against SMTP server that requires it to be set) and if I read the java mail properties from the JavaMailSenderImpl I get default values

```
Properties props = ((JavaMailSenderImpl)javaMailService).getJavaMailProperties();        
for ( Object key : props.keySet()) {    
    log.info("KEY: " + key.toString() + " VALUE " + props.getProperty(key.toString()));
}

Prints:
KEY: mail.smtp.starttls.enable VALUE false
KEY: mail.smtp.auth VALUE false
...
```
I can't find any documentation for setting these values from yml file so my format might be off but I assume that I have set those correctly. If this is not a bug (just wrong used properties) then this needs some additional documentation because it should be pretty common use case to use TLS in production app for sending emails.

I am using Spring boot version 1.4.0.RELEASE with the spring-boot-starter-mail as a dependency. 

As a workaround I set these settings manually from property file in my MailService via @Value annotations but that just feels wrong.
```
    @Value("${mail.smtp.starttls.enable}")
    private String tls;
...
    @PostConstruct
    private void setJavaMailProperties() {
        Properties props = ((JavaMailSenderImpl)javaMailService).getJavaMailProperties();
        props.setProperty("mail.smtp.starttls.enable",tls);
        props.setProperty("mail.debug",debug);
        props.setProperty("mail.smtp.auth",auth);
    } 
```

**Comment by philwebb** [comment]
I just tried a small sample application and put a breakpoint on `JavaMailSenderImpl.setJavaMailProperties`. With your YAML I see the following value:

```
{mail.smtp.starttls.enable=true, mail.smtp.auth=true}
```

Do you see the same result if you debug your code? Perhaps you could provide a small project that demonstrates the problem?

**Comment by elbitoy** [comment]
This is embarassing and the issue can be closed. Found hard coded set for those mail settings from our code base. Should have debugged the setter first instead of the getter. Sorry for inconvenience

**Comment by philwebb** [comment]
No worries, I'm glad you fixed it!
