### ISSUE TITLE
Provide actuator endpoint to change loglevel at runtime

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6837]

**Comment by spencergibb** [comment]
:-) we add a post to `/env` in [EnvironmentManagerMvcEndpoint](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentManagerMvcEndpoint.java). If there are logging properties, the logging system is updated.

**Comment by vpavic** [comment]
Somewhat related to #5321.

**Comment by snicoll** [comment]
I agree. #5321 is maybe a bit more ambitious but has quite a lot of context as well.

**Comment by philwebb** [comment]
This was fixed as part of #7086
