### ISSUE TITLE
Servlet error supersedes Exception.getMessage

### ISSUE THREAD

**Issue by michael-gillette** [spring-projects/spring-boot#6840]
Without going too far out of the way with `ControllerAdvice` classes or custom `ExceptionHandlers`, I started investigating why the `getMessage` method wasn't the value set in the default exception handler.

Expected: when an exception is thrown then the "message" attribute should be the value set in `DefaultErrorAttributes#addErrorMessage`
Actual: when the attribute `javax.servlet.error.message` is part of the request, that value is used in lieu of the "message" attribute already having been set.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/DefaultErrorAttributes.java#L127

**Comment by philwebb** [comment]
The current implementation intentionally doesn't include the exception message when a `javax.servlet.error.message` is included. I'm not sure that we really want to change that behavior.
