### ISSUE TITLE
“PermGen space”  create by  running my project Embedded tomacat，increase PermSize and MaxPermSize  this error create yet

### ISSUE THREAD

**Issue by yxjshenzhen** [spring-projects/spring-boot#6841]
“PermGen space”  create by  running my project Embedded tomacat，increase PermSize and MaxPermSize  this error create yet:
2016-09-07 18:43:35,917 [http-nio-30000-exec-142] ERROR org.apache.tomcat.util.net.NioEndpoint - 
java.lang.OutOfMemoryError: PermGen space

**Comment by philwebb** [comment]
PermGen settings are specified at the JVM level and are out of our control. Try adding `-XX:MaxPermSize=...` arguments when you start your application. You might also find [this article](http://www.integratingstuff.com/2011/07/24/understanding-and-avoiding-the-java-permgen-space-error/) useful.
