### ISSUE TITLE
Prevent CastCastException when RootUriRequestExpectationManager is used with @RestClientTests

### ISSUE THREAD

**Issue by dariuszlesniak** [spring-projects/spring-boot#6845]
HI having problems using `ContentRequestMatchers` from spring-test with spring-boot-test `MockServerRestTemplateCustomizer`. 

```java
        this.server
                .expect(requestTo("/someUrl"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(content().string("some_body"))`
```

following exception thrown:
```
java.lang.ClassCastException: org.springframework.boot.test.web.client.RootUriRequestExpectationManager$ReplaceUriClientHttpRequest cannot be cast to org.springframework.mock.http.client.MockClientHttpRequest
```

**Comment by philwebb** [comment]
Can you please provide the complete stacktrace, or better still a sample that demonstrates the issue.

**Comment by omeryounus** [comment]
@dariuszlesniak 
can you please send some more details ?thnx

**Comment by dariuszlesniak** [comment]
hi Guys
sorry for late reply, i created a small [demo](https://github.com/dariuszlesniak/issue_544) , if you run the test you will get java.lang.ClassCastException with full stacktrace
