### ISSUE TITLE
Gradle plugin task bootRepackage does not declare output when classifier is missing

### ISSUE THREAD

**Issue by seakayone** [spring-projects/spring-boot#6846]
Bug report

SpringBoot version:  1.4.0

`bootRepackage.outputs.files` is empty if `bootRepackage.classifier` is not set although an output exists.

The [setupInputOutputs](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/repackage/RepackagePluginFeatures.java#L141) method is only called [if a classifier is set](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/repackage/RepackagePluginFeatures.java#L135).

**Comment by philwebb** [comment]
I have a feeling this is related to #5861 and may not be something that we can address until Spring Boot 2.0.

**Comment by wilkinsona** [comment]
@philwebb Agreed. This should wait till 2.0.

**Comment by seakayone** [comment]
Yes, I agree that #5861 would address this problem. My current workaround is setting a classifier for the bootRepackge task.
