### ISSUE TITLE
Investigate FilterRegistrationBean requirement needed for Jetty but not Tomcat

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6850]
See https://github.com/spring-cloud/spring-cloud-sleuth/issues/394#issuecomment-245653840

**Comment by dsyer** [comment]
Test project: https://github.com/spring-projects/spring-boot-issues/tree/master/gh-6850. There are two filters ("oneFilter" and "twoFilter") with order 1,2 respectively. OneFilter is registered with all dispatch types, and TwoFilter uses the defaults.

Results scraped from console ("OK" is a 200 response, "Not OK" is a 404). Notice the difference in the 404 with Jetty.

Tomcat:

```
OK: [before:oneFilter, before:twoFilter, after:twoFilter, after:oneFilter]
Not OK: [before:oneFilter, before:twoFilter, after:twoFilter, after:oneFilter, before:oneFilter, after:oneFilter]
```

Undertow

```
OK: [before:oneFilter, before:twoFilter, after:twoFilter, after:oneFilter]
Not OK: [before:oneFilter, before:twoFilter, after:twoFilter, after:oneFilter, before:oneFilter, after:oneFilter]
```

Jetty:

```
OK: [before:oneFilter, before:twoFilter, after:twoFilter, after:oneFilter]
Not OK: [before:oneFilter, before:twoFilter, before:oneFilter, after:oneFilter, after:twoFilter, after:oneFilter]
```

**Comment by dsyer** [comment]
It looks to me as if the implementation of the filter chain dispatch is different in Jetty. It puts the error dispatch in the same chain as the main dispatch: "(before:oneFilter, after:oneFilter)" stuffed in the middle there. But the thing with the dispatch type is surely simply a bug in Jetty?

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
