### ISSUE TITLE
JPA not detecting valid table names in 1.4.0.RELEASE 

### ISSUE THREAD

**Issue by fedepia** [spring-projects/spring-boot#6856]
Hi, 

We are using 1.3.3.RELEASE version and when I decided to migrate to 1.4.0.RELEASE I found very weird errors in JPA.

I cannot provide right now a sample application but will try to describe the most important things related to this problem.

We have 2 environments 'default' and 'test', in the default we use hibernate to create the schema and everything goes well. However, in the 'test' we are using Flyway to handle our scripts and hibernate to validate the schema. We are using these properties in the 'test' profile:

```
# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/catalog
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driverClassName=com.mysql.jdbc.Driver

# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.EJB3NamingStrategy

# Flyway configuration (only in test, default has false)
flyway.enabled=true
```

Our physical table name in the db is `CreditCard`. The another important comment is that, this is our JPA mapping:

```java
@Entity
public class CreditCard
```

In version 1.3.3.RELEASE everything works like a charm, but when I migrated to 1.4.0.RELEASE I see this error:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'catalog.credit_card' doesn't exist
```

I guest that 1.4 version had changed something, so I explicitly updated the mapping to this:

```java
@Entity
@Table(name="CreditCard")
public class CreditCard
```

But no luck, I still cannot start up the application since the same error is shown, no matter what I do. I also tried changing the `spring.jpa.hibernate.naming-strategy` to different strategies, also I tried removing `spring.jpa.hibernate.naming-strategy` it but nothing... always the same error. However, when I rollback to version 1.3.3.RELEASE everything works perfectly well. 

So I guess this might be a bug. What do you think?

Regards

**Comment by philwebb** [comment]
Your problems are most likely related to the Hibernate 5.0 upgrade and specifically the `NamingStrategy` changes that Hibernate have made. Take a look at [this section of the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#hibernate-5) and [these property changes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#property-renames).

Specifically this line:
> `spring.jpa.hibernate.naming-strategy` should be replaced with `spring.jpa.hibernate.naming.strategy`.

**Comment by juzerali** [comment]
@philwebb Even after making the property name change, it doesn't work.

**Comment by philwebb** [comment]
@juzerali If you think you've found a bug could you please open a new issue and provide a sample project that shows it. If you've got a general configuration problem, the best place to ask questions is stackoverflow.com.
