### ISSUE TITLE
Using a custom DataSource prefix requires a different property than the default one

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#6860]
If I use a custom `DataSource` prefix like `my.datasource` instead of the default prefix (`spring.datasource`), it requires a different property than the default one. For example, for `tomcat.test-on-borrow` with `spring.datasource` it works with `spring.datasource.tomcat.test-on-borrow` but with `my.datasource` it doesn't work with `my.datasource.tomcat.test-on-borrow`. In case of `my.datasource`, `my.datasource.test-on-borrow` works.

It looks inconsistent to me unless if I missed anything.

This is a sample project to demonstrate this issue: https://github.com/izeye/spring-boot-throwaway-branches/commits/jdbc-mysql-custom-datasource

Running `ApplicationTests.testDataSource()` works with `my.datasource.test-on-borrow` but doesn't work with `my.datasource.tomcat.test-on-borrow`.

**Comment by snicoll** [comment]
It's not inconsistent. You are creating your own datasource so you're essentially asking boot to back off. We actually bind 4 datasources for each type we support on a different namespace. 

What you have is work as advertised. Maybe you could share what you're trying to do?

**Comment by izeye** [comment]
@snicoll `test-on-borrow` is prefixed with `tomcat` since Spring Boot 1.4.0, so I thought `my.datasource.test-on-borrow` has to change to `my.datasource.tomcat.test-on-borrow`.

**Comment by snicoll** [comment]
Nope. Does that help?

**Comment by izeye** [comment]
Based on your comment, it looks I misunderstood `tomcat` part. After reading [the release note](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M1-Release-Notes#datasource-binding) again, it looks intended for implementation-specific auto-completion of the auto-configured `DataSource`, am I understanding right?

**Comment by izeye** [comment]
After looking into [the source](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java), it's clear that I misunderstood in the first place.

@snicoll Sorry!
