### ISSUE TITLE
Misleading instruction on how to exclude SpringBootWebSecurityConfiguration.java from context

### ISSUE THREAD

**Issue by sofiaguyang** [spring-projects/spring-boot#6861]
[Javadoc says says that `SpringBootWebSecurityConfiguration` can be excluded by specifying it in the exclude list of `EnableAutoConfiguration#exclude()`. ](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SpringBootWebSecurityConfiguration.java#L69)

However, it turns out that `SpringBootWebSecurityConfiguration` is not an autoconfiguration. Instead, it is imported by `SecurityAutoConfiguration`. Therefore to exclude `SpringBootWebSecurityConfiguration` from the context, `SecurityAutoConfiguration` must be the one to be excluded. 

This caused some trouble for me. `@EnableWebSecurity` imports`WebSecurityConfiguration` which defines a `FilterChainProxy` called `springSecurityFilterChain` that was conflicting with my xml-based `FilterChainProxy` -- my filter chain was being called twice every request. So, I was trying to exclude all the configurations which had `@EnableWebSecurity` annotation. `SpringBootWebSecurityConfiguration` was one of those which had the annotation among others. So I specified them in the exclude list but didn't realize immediately why `SpringBootWebSecurityConfiguration` couldn't be excluded and kept showing up in ` GET /beans`. ~~Also realized that only `SecurityAutoConfiguration` needs to be excluded and the rest would be disabled.~~ To disable auto configuration completely, both `SecurityAutoConfiguration` & `SecurityFilterAutoConfiguration` need to be excluded.

I am using Spring Boot 1.3.4. But this concerns versions up to 1.4.0.

**Comment by snicoll** [comment]
It's actually a bit worse since `SecurityFilterAutoConfiguration` has a `AutconfigureAfter` that isn't going to be honoured. Good catch!

**Comment by snicoll** [comment]
tentatively adding 1.4.1 even though it's broken since 1.0! (see #202)

**Comment by sofiaguyang** [comment]
Thanks @snicoll and team 👍

**Comment by snicoll** [comment]
I question the fact `SecurityFilterAutoConfiguration` is an auto-configuration (#3703) adds an `AutoconfigureAfter` on something that's not an auto-configuration. We could just as well add it as an import after in `SpringBootWebSecurityConfiguration` in `SecurityAutoConfiguration`. 

That way, excluding `SpringSecurityAutoConfiguration` would be enough to exclude everything. Right now, we have to exclude both `SpringSecurityAutoConfiguration` and `SecurityFilterAutoConfiguration`.

@rwinch is there a reason why this was created as a separate auto-configuration? Putting it at the right place in the `@Import` declaration does what your `AutoconfigureAfter` was meant to do.

**Comment by snicoll** [comment]
@rwinch never mind, @wilkinsona just replied me.

**Comment by snicoll** [comment]
I've fixed the doc but I believe that we still should do something about the fact these are two separated auto-configuration. I've opened #6905 and I have a draft commit that needs some more work that I'll push in a minute.

**Comment by rwinch** [comment]
@snicoll The reason there is two auto configurations is that we still want the FilterRegistrationBean to be created even if a user defines their own Spring Security configuration. Otherwise the Spring Security Filter Chain will not be registered with the correct dispatcher types.

**Comment by wilkinsona** [comment]
@rwinch There are no conditions on `SecurityAutoConfiguration` that would prevent that:

```java
@Configuration
@ConditionalOnClass({ AuthenticationManager.class,
		GlobalAuthenticationConfigurerAdapter.class })
@EnableConfigurationProperties
@Import({ SpringBootWebSecurityConfiguration.class,
		AuthenticationManagerConfiguration.class,
		BootGlobalAuthenticationConfiguration.class, SecurityDataConfiguration.class })
public class SecurityAutoConfiguration
```

**Comment by snicoll** [comment]
Exactly. Let's move that conversation (if need to be) in #6905.
