### ISSUE TITLE
Add Thymeleaf with dialect

### ISSUE THREAD

**Issue by dtrunk90** [spring-projects/spring-boot#6862]
It would be great to add the with dialect of Thymeleaf to the artifact `spring-boot-dependencies` in order to omit the version in a projects dependencies like its the case for other dialects as well as a bean in [ThymeleafAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafAutoConfiguration.java).

**Comment by wilkinsona** [comment]
I'd never heard of the with dialect before. I assume you're referring to [this project](https://github.com/Antibrumm/thymeleaf-extras-with-dialect)? If so, it doesn't appear to be particularly active or popular. As such, I'm not sure that it's a good candidate for supporting in Boot (at the moment anyway).

**Comment by dtrunk90** [comment]
Yes, that's the project I'm referring to. I don't like the comma separated `th:with` as it gets cluttered very fast. It's also [mentioned on the official Thymeleaf page](http://www.thymeleaf.org/ecosystem.html#thymeleaf-with-dialect).

**Comment by wilkinsona** [comment]
Thanks for the confirmation. This feels like a good candidate for a third-party starter at the moment. If you or someone else creates a `thymeleaf-with-dialect-spring-boot-starter` we'd be happy to add it to the [list of third-party starters](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters#community-contributions).
