### ISSUE TITLE
BeanCreationException when app restarts with spring-boot-devtools

### ISSUE THREAD

**Issue by RbkGh** [spring-projects/spring-boot#6864]
When `spring.devtools.restart.enabled=true` is set in `application.properties` file,
Application restart initiates successfully when a make or build is triggered with either "Make Project" or "Ctrl+F9" shortcut in intellij, but a `BeanCreationException` is always thrown thus application restart fails even after checking to see that this has been fixed in 1.3.0 of spring boot.

**Comment by snicoll** [comment]
You haven't given us much to investigate. Please share a project that reproduces the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
