### ISSUE TITLE
Check excluded auto-configuration classes are actually auto-config

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6865]
See #6861 for one example where this would help. We could check that if the class exists, it should be in the list that would be otherwise included.

**Comment by snicoll** [comment]
`@AutoconfigureAfter/Before` is another candidate. I've seen a few user trying to use that thing on regular configuration classes.

**Comment by wilkinsona** [comment]
I've merged #7407 but left this open so that we can look at doing something similar for `@AutoConfigureBefore` and `@AutoConfigureAfter`

**Comment by mbhave** [comment]
@philwebb For the `@AutoConfigureBefore` and `@AutoConfigureAfter`, I see two ways in which it could be incorrectly used:
1. The annotation is used on a class that is not auto-config
2. The annotation value contains a class that exists but is not auto-config.

Point 2. could be taken care of in the `AutoConfigurationSorter` but I'm not sure if we also want to fail hard on Point 1. Thoughts?

**Comment by philwebb** [comment]
Closing this one as fixed. We'll take on `AutoConfigureBefore`/`AutoConfigureAfter` in #7697 which we might slip.
