### ISSUE TITLE
@SessionAttributes("user") not working with spring boot 1.4.0

### ISSUE THREAD

**Issue by yaoshenghong** [spring-projects/spring-boot#6866]
Cannot create a session after the response has been committed

**Comment by wilkinsona** [comment]
@yaoshenghong If you'd like us to spend some time on your problem, please spend some time providing a reasonable amount of information. An explanation of why you think this is a bug in Spring Boot and a small sample project that reproduces the problem would be ideal.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
