### ISSUE TITLE
BDDMockito does not seem to be able to mock void methods

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6869]
In https://github.com/spring-projects/spring-boot/commit/b88cb35ea231fffa807a9f1d97b6b38e412bb34b I had to mock a void method (throw an exception if it's invoked). I haven't found a way to do that with the bdd imports so I've tricked by a full import. 

What am I missing? We need to fix that commit with the proper way of doing this or change the checkstyle rules.

**Comment by wilkinsona** [comment]
You need something like this:

```java
willThrow(new JMSException("Could not start", "123")).given(connection).start();
```

**Comment by snicoll** [comment]
That's what I am doing right now.
