### ISSUE TITLE
add a `watch` plugin for the Spring Boot Remote Shell

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-boot#6875]
I'm with a large internet company in China and they have a really cool sort of shell-like thing that lets them, among other things, setup a `watch` command on method invocations and then debug the parameters on this invocations as they happen. I imagine this would be a fairly trivial AspectJ/AOP/agent project in the simple case. Something like:

```
watch my.bean.in.SpringImpl someMethodName --parameters String int 
```

Very useful for debugging in a production-like environment.

**Comment by philwebb** [comment]
Sounds interesting, although I'm a little worried about using AspectJ or an agent out of the box.

**Comment by wilkinsona** [comment]
Support for the remote shell is going to b removed in 2.0 (#7044).
