### ISSUE TITLE
Spring Data MongoDB auto-configuration sets up MappingContext incompletely

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6881]
`MongoMappingContext` needs to get the `SimpleTypeHolder` set that a `CustomConversion` instance, potentially declared in an `ApplicationContext`, exposes. The general pattern can be seen in `AbstractMongoConfiguration`. See how [this line](https://github.com/spring-projects/spring-data-mongodb/blob/7effc0e10f425bae01307b6a80d1766eef42df26/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/config/AbstractMongoConfiguration.java#L174) does that.

I guess that will also need `MongoDataAutoConfiguration` to also provide a default `CustomConversion` in case none has been configured. Note, that that `CC` instance should be the one set on the `MappingMongoConverter`, too.

That missing causes [issues](https://jira.spring.io/browse/DATAREST-888) in Spring Data REST when used with Spring Boot.

**Comment by snicoll** [comment]
Closing in favour of PR #6882
