### ISSUE TITLE
Move all actuator beans under `/application`

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6886]
The current situation of many top-level actuator URLs makes many things hard (security being the most obvious). It would be better to move them all under a single location, e.g:
- `/application/health`
- `/application/metrics`
- `/application/env`
- `/application/beans`

etc.

**Comment by snicoll** [comment]
Don't we have `/actuator` right now in some cases already? I am not against `/application` (it sounds better actually).

**Comment by bclozel** [comment]
Should we prefix to avoid path collisions with the actual application, like `/_application`? Or maybe providing a property to customize that is enough.

**Comment by philwebb** [comment]
@snicoll We do currently have `/actuator` but I would like to change that to `/application`.

@bclozel We'll need a property to configure it. It might clash, but probably no more likely than the current state of affairs (`/env`, `/health` etc).

**Comment by cah-andrewfitzgerald** [comment]
Is another property really necessary?
Shouldn't changing the default value of management.context-path handle it?

**Comment by philwebb** [comment]
@cah-andrewfitzgerald 

> We'll need a property to configure it

I didn't say it should be a new one :) Hopefully we can use `management.context-path`

**Comment by mbhave** [comment]
Reopening to update the docs.
