### ISSUE TITLE
Provide hateoas discoverabilty of actuator endpoints without spring-hateoas

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6887]
It would be nice if the current `/actuator` endpoint worked even if spring-hateoas isn't in use. Particularly if systems are in place that want to know what endpoints are available without hitting each one individually.

**Comment by philwebb** [comment]
Related to #6886 which would be the obvious place to put this endpoint.

**Comment by mbhave** [comment]
Done as part of #7108. The  `CloudFoundryDiscoveryEndpoint` returns a HAL response for the Cloud Foundry actuators even when spring-hateoas is not in use.

**Comment by philwebb** [comment]
I think we only did this for the `CloudFoundryDiscoveryEndpoint`, we should consider if we want it also for the regular actuators endpoint.

**Comment by mbhave** [comment]
Good point. I suppose we can add support for this in the `HalJsonMvcEndpoint`. The `HalBrowserMvcEndpoint`, I think, would still require spring-hateoas.

**Comment by wilkinsona** [comment]
Duplicate of #9901
