### ISSUE TITLE
Provide first class security support for actuator enpoints

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6888]
We need a way to secure actuator endpoints without necessarily needing Spring Security. The current situation of needing to make Spring Security directly aware of actuator URLs is quite problematic.

**Comment by philwebb** [comment]
The solution should be pluggable so that people can develop their own strategies.

**Comment by philwebb** [comment]
Changing `EndpointHandlerMapping.extendInterceptors` to add a `HandlerInterceptor` or `WebRequestInterceptor` may work. We could use the `request.hasRole` method to ensure that something has setup security.

**Comment by mbhave** [comment]
@philwebb the pluggable strategies solution will be for 2.0, right? Protecting actuators out of the box for 1.5 will be taken care of as part of in #6889.

**Comment by philwebb** [comment]
I think #6889 alone will be enough to support pluggable security. As long as the `hasRole` method is supported somehow then any security should work.
