### ISSUE TITLE
Update TestTypeExcludeFilter to support TestNG types

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-boot#6901]
## Overview

This issue picks up where #6768 left off. See https://github.com/spring-projects/spring-boot/issues/6768#issuecomment-243093363 for details.
## Related Issues
- #6768 
- #6898 
## Deliverables
- [ ] Support `org.testng.annotations.Test` in both `CLASS_ANNOTATIONS` and `METHOD_ANNOTATIONS` in `TestTypeExcludeFilter`

**Comment by philwebb** [comment]
Closing in favor of PR #7630

**Comment by izeye** [comment]
@philwebb Closed?
