### ISSUE TITLE
spring.data.mongodb.uri with credentials is exposed by /configprops endpoint

### ISSUE THREAD

**Issue by Dichotomia** [spring-projects/spring-boot#6903]
The property to configure the access to MongoDB (spring.data.mongodb.uri) contains login and password.

I think it could be a good idea to mask the login and the password (or the entire uri) because it contains confidential information.

I know we can create a custom mask endpoints.configprops.keys-to-sanitize property, but in that case it could be a default behavior.

**Comment by snicoll** [comment]
Duplicates #6876
