### ISSUE TITLE
Make health endpoint visibility configurable with SpEL statement

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [spring-projects/spring-boot#6906]
Problem: We are securing our endpoint with OAuth, and would like to be able to restrict access based off of scope, which does not currently appear to be possible.

Enhancement: Currently the health endpoint has its access managed by a list of security roles.
It would be nice if you could instead pass in a SpEL string to customize access further.

**Comment by philwebb** [comment]
We'd prefer not to add SpEL expression support to the Health endpoint roles but perhaps we could add an extension point instead. One idea would be an interface that you could implement and register as a bean. Could you open a new issue if you think this is worth perusing with a bit more background about what you're trying to do, and which Spring Boot classes you feel need to change.

Thanks.
