### ISSUE TITLE
Hikari datasource cannot initialize automatically with .hikari properites

### ISSUE THREAD

**Issue by green-leaves** [spring-projects/spring-boot#6907]
I have tried using hikari datasource configuration as following:

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.jdbc-url=jdbc:oracle:thin:@//localhost:1521/sandbox
spring.datasource.hikari.username=tiep
spring.datasource.hikari.password=123456

And when I start appilication with --debug, it gives me this exception:

**org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:218) ~[spring-boot-autoconfigure-1.4.0.RELEASE.jar:1.4.0.RELEASE]**

After few debug investigations, I found out that at line 76 in **DataSourceConfiguration.java** the DataSourceProperties is not instantiate using **spring.datasource.hikari** properties but **spring.datasource**

**Comment by snicoll** [comment]
You get that error message because no connection pool was found in the classpath. Are you sure your project has hikari on the classpath? Also, that configuration is 1.4 and you should get a proper message from a failure analyzer. 

Check that you are running with spring boot 1.4 and that hikari is on the classpath.

Also, no need to use that namespace for such standard properties, this will work once you add hikari to the classpath.

```
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/sandbox
spring.datasource.username=tiep
spring.datasource.password=123456
```

**Comment by green-leaves** [comment]
@snicoll I have re-checked, hikari is on my classpath.

Here is my pom.xml:

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.greenleaves</groupId>
    <artifactId>play-boot</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>play-boot</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.7</java.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.0.RELEASE</version>
    </parent>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP-java7</artifactId>
            <version>2.4.8</version>
        </dependency>

        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc7</artifactId>
            <version>12.1.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.9</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by snicoll** [comment]
Please share a sample that I can run to reproduces the issue.

**Comment by green-leaves** [comment]
Please refer to this repo https://github.com/green-leaves/my-boot

**Comment by snicoll** [comment]
@green-leaves `spring.datasource.url` is the thing that triggers the creation of a connection pool and I can see that [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connect-to-production-database) could benefit from stating that explicitly.

I've changed your configuration to comply with what I wrote already above and the error goes away.

**Comment by green-leaves** [comment]
It works now. Thank you snicoll.

**Comment by snicoll** [comment]
@green-leaves I want to improve the documentation, this issue shouldn't be closed.
