### ISSUE TITLE
Includes WebSecurityConfigurer in auto configuration for tests with @WebMvcTest

### ISSUE THREAD

**Issue by marcoasp** [spring-projects/spring-boot#6920]
Enhancement

It should be a good idead to include the WebSecurityConfigurer in the auto configuration scanning for @WebMvcTest tests, since the security enabled by default in this case, configures the default authentication. It can make some confusion when you already have a WebSecurityConfigurer for your web layer as it is not picked unless used with another annotation @ContextConfiguration in which you may include all your other configuration classes, for example

```
@RunWith(SpringRunner.class)
@WebMvcTest
@ContextConfiguration(classes={Application.class, MvcConfig.class, SecurityConfig.class})
public class MyTest {
    @Autowired
	WebApplicationContext context;
	
	MockMvc mockMvc;

	@Before
	public void setUp() {
		this.mockMvc = MockMvcBuilders
						.webAppContextSetup(context)
						.apply(springSecurity())
						.build();
	}
}
```

**Comment by wilkinsona** [comment]
Duplicates #6514
