### ISSUE TITLE
Tomcat native APR java.lang.IllegalStateException: No key manager found

### ISSUE THREAD

**Issue by davidmelia** [spring-projects/spring-boot#6925]
Hi,

I'm testing Spring Boot 1.4 (Ubuntu 64bit/Oracle JDK 8), Tomcat native (1.2.8) and APR (1.5.2) and get the following error:
```
java.lang.IllegalStateException: No key manager found
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.chooseKeyManager(OpenSSLContext.java:348) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.init(OpenSSLContext.java:273) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:101) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:81) [tomcat-embed-core-8.5.4.jar:8.5.4]
```

Looking at OpenSSLContext line 348 it seems it's looking for an instanceof JSSEKeyManager however my key manager is SunX509KeyManagerImpl

**Downgrading to Spring Boot 1.3.6 everthing works fine which is why I think it's a bug.**

I have a very simple example of the issue on [Bit Bucket Example](https://davidmelia@bitbucket.org/davidmelia/spring-boot-ssl-issue.git)

In order to recreate the issue you have to install the tomcat native APR libs and start the above with the location of the library i.e. 
`java -jar -Djava.library.path=/usr/local/apr/lib target/spring-boot-ssl-issue-0.0.1-SNAPSHOT.jar `

making sure the APR is loaded in the log
`Loaded APR based Apache Tomcat Native library 1.2.8 using APR version 1.5.2`
otherwise you won't get the bug

Thanks

**Comment by wilkinsona** [comment]
I believe this is a bug in Tomcat 8.5.4 where `OpenSSLContext.chooseKeyManager` looks like this:

```java
    private static JSSEKeyManager chooseKeyManager(KeyManager[] managers) throws Exception {
        for (KeyManager manager : managers) {
            if (manager instanceof JSSEKeyManager) {
                return (JSSEKeyManager) manager;
            }
        }
        throw new IllegalStateException(sm.getString("openssl.keyManagerMissing"));
    }
```

I believe it's been fixed in 8.5.5 (which Boot 1.4.1 snapshots are already using) where the method now looks like this:

```java
    private static X509KeyManager chooseKeyManager(KeyManager[] managers) throws Exception {
        for (KeyManager manager : managers) {
            if (manager instanceof JSSEKeyManager) {
                return (JSSEKeyManager) manager;
            }
        }
        for (KeyManager manager : managers) {
            if (manager instanceof X509KeyManager) {
                return (X509KeyManager) manager;
            }
        }
        throw new IllegalStateException(sm.getString("openssl.keyManagerMissing"));
    }
```

@davidmelia You can try 8.5.5 with Boot 1.4.0 by setting `<tomcat.version>8.5.5</tomcat.version>` in the `<properties>` section of your pom.
