### ISSUE TITLE
Add ttransactions-hibernate4 dependency for Atomikos

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#6926]
Hi,

To set up Atomikos JTA we must into Hibernate property a class in charge of it:
**hibernate.transaction.jta.platform=**

Nowadays spring boot atomikos dependency does not include a dependency who has a specific class for it:
```
		<dependency>
			<groupId>com.atomikos</groupId>
			<artifactId>transactions-hibernate4</artifactId>
		</dependency>
```

In the end we would have this:
**hibernate.transaction.jta.platform=com.atomikos.icatch.jta.hibernate4.AtomikosPlatform**

**Comment by wilkinsona** [comment]
There are a couple of problems here:

 - We're using Atomikos 3.9 which doesn't have the `transactions-hibernate4` module
 - We're using Hibernate 5 by default and there doesn't appear any version of Atomikos that provides a `transactions-hibernate5` module.

Given the above, there's nothing that we can do here.

**Comment by ofbizbrazil** [comment]
If you look **transactions-hibernate4** is just the name of the library, what matters is the class which manages the JTA called AtomikosPlatform.

What value should I place in **hibernate.transaction.jta.platform** ?
