### ISSUE TITLE
Upgrade to Hibernate ORM 5.1.2

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#6953]
https://hibernate.atlassian.net/projects/HHH/versions/24051/tab/release-report-all-issues

**Comment by wilkinsona** [comment]
We plan to stick with 5.0.x for the foreseeable future. Its long-term maintenance is clearer than 5.1.x as 5.0.x is used in JBoss EAP. We'll re-evaluate the Hibernate version in Boot 2.0 where we may move to 5.2 or later.

**Comment by Polve** [comment]
You can change the title to upgrade to 5.0.11 then (released today), since the defined version in boot is 5.0.9

**Comment by wilkinsona** [comment]
There's no need for that. See #6944
