### ISSUE TITLE
spring.factories in one app is being picked up by other apps deployed to the same JBoss EAP 6.4.4 instance.

### ISSUE THREAD

**Issue by asegarra** [spring-projects/spring-boot#6963]
I am noticing some odd behavior when multiple Spring Boot apps are deployed to a shared JBoss container, in this case EAP 6.4.4. One app is packaged with spring.factories, specifically a EnvironmentPostProcessor that is also being picked up by other apps. Most apps are running 1.3.0 or greater.

**Comment by wilkinsona** [comment]
The `spring.factories` mechanism is part of Spring Framework rather than Spring Boot. The files are found by checking the classpath. If files from one app are being found by another then either one has been installed as a shared library or there's a bug in JBoss.
