### ISSUE TITLE
Replace TomcatEmbeddedServletContainerFactory.addServletMapping deprecated calls

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6965]
Tomcat deprecated `addServletMapping`, we should migrate for Tomcat 9 compat.

**Comment by wilkinsona** [comment]
The replacement method, `addServletMappingDecoded` is new in 8.0.37 and 8.5.5 where `addServletMapping` has been deprecated. That means we have warnings in 1.3.x and later. How do we want to handle this? Seems like a good time to consider reducing the range of Tomcat versions that we try to support.

**Comment by wilkinsona** [comment]
We'll need to wait for 2.0 before we can drop Tomcat 7 as it's the latest version that supports Java 6.

**Comment by wilkinsona** [comment]
Fixed in https://github.com/spring-projects/spring-boot/commit/445344211d76289651b261fc5f27cd3bffb26fd8
