### ISSUE TITLE
Remove deprecated 1.4 code

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6971]
Remove code that was deprecated in 1.4

**Comment by wilkinsona** [comment]
Looks like we missed HornetQ

**Comment by snicoll** [comment]
We didn't. I think we said we would remove it in 2.0. Lots of people haven’t jumped to the artemis wagon yet. I am happy to revisit that decision but given that 1.5 is a shorter iteration, I don’t see a compelling reason to break users there.

**Comment by wilkinsona** [comment]
It seems very strange to me to give special treatment to HornetQ. I'd rather that we removed deprecated things consistently.

**Comment by snicoll** [comment]
Works for me. Go.
