### ISSUE TITLE
Auto configure jOOQ code generator in the presence of the Flyway migration plugin

### ISSUE THREAD

**Issue by lukaseder** [spring-projects/spring-boot#6975]
I was talking to @michael-simons who will soon deliver an interesting talk about a jOOQ+Spring Boot+Flyway integration at the DOAG conference, and it struck me that perhaps, Spring Boot could add even more value to setting up projects in the presence of jOOQ *and* Flyway.

The jOOQ documentation for the code generator mentions the `<schemaVersionProvider>` flag (since jOOQ 3.8 there's also a <catalogVersionProvider>`):
http://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced

In the case of usage with Flyway, we can now specify:

```xml
 <schemaVersionProvider>SELECT :schema_name || '_' || MAX("version") FROM "schema_version"</schemaVersionProvider>
```

... where `"schema_version"` (in lower case, case sensitive letters) is Flyway's migration history table.

This query will be executed to produce a "schema version", which will be put in jOOQ's generated classes. Whenever the jOOQ code generator encounters the same schema version string, it will skip code generation for this schema, which can save a lot of time when generating large schemas.

Is this something that could be auto-configured in Spring Boot as soon as both dependencies are available?

**Comment by wilkinsona** [comment]
I'm not sure how this could be achieved using Spring Boot's auto-configuration. My understanding of jOOQ's code generation is that it runs at build time, often via Maven or Gradle. On the other hand, Spring Boot's auto-configuration runs at runtime when the app is starting up.

How had you envisaged that Boot would automatically customize jOOQ's code generation configuration?

**Comment by michael-simons** [comment]
I think it's actually fine the way it is. 

jOOQs generator is usually used during `generate-sources` phase. One can just use Flyway as build plugin in the same phase before hand, filling the version table correctly. 

When Boot detects Flyway as dependency, it executes as well which is fine both during development (nothing happens, because usually DB has been migrated during build) and prod (here I want the migration to happen). 

I'll post the snippets of my demo this week to show the usage. It's more of a documentation idea, which I could add if it's interesting.

**Comment by lukaseder** [comment]
Thanks for chiming in @michael-simons. Looking forward to those samples.

@wilkinsona: At this stage, I was just thinking out loud. You're right, jOOQ's code generation (just like Flyway's migration) runs at build type via Maven or Gradle.

However, my recent interactions with the folks at Gradle who maintain the [gradle-jOOQ-plugin](https://github.com/etiennestuder/gradle-jooq-plugin) made me think. Their plugin adds quite a bit of convenience on top of the out-of-the-box jOOQ code generation plugin, with opinionated defaults, which makes Gradle configurations much simpler than Maven configurations, for the jOOQ code generator.

Spring Boot also applies opinionated defaults. So, I was thinking that Spring Boot could perhaps offer code generation "starters" and schema migration "starters" that somehow magically interact with each other by default. I'm not seeing the full picture yet, but I feel there might be some low hanging fruit here (perhaps not just for jOOQ+Flyway, but also for things like XJC, Hibernate and other code generators)

**Comment by michael-simons** [comment]
So this is basically the build script I prefer when working with Spring Boot, Flyway and jOOQ:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <!-- Configure development db inside pom... gonna be used in application.properties for Boot, see below -->
  <properties>
    <db.url>jdbc:oracle:thin:@//localhost:1521/ORCLPDB1</db.url>
    <db.username>foo</db.username>
    <db.password>bar</db.password>
    <db.schema>bazbar</db.schema>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <version>${flyway.version}</version>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>migrate</goal>
            </goals>
          </execution>
          <configuration>
          <url>${db.url}</url>
          <user>${db.username}</user>
          <password>${db.password}</password>
          <locations> 
            <!-- Configure to the same location as configured in Spring Boot.. -->
            <location>filesystem:src/main/resources/db/migration</location>
          </locations>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jooq.pro</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <jdbc>
            <driver>oracle.jdbc.OracleDriver</driver>
            <url>${db.url}</url>
            <user>${db.username}</user>
            <password>${db.password}</password>
          </jdbc>
          <generator>
            <database>
              <name>org.jooq.util.oracle.OracleDatabase</name>
              <!-- Retrieve schema version from Flyway info table -->
              <schemaVersionProvider>SELECT :schema_name || '_' || MAX("version") FROM "schema_version"</schemaVersionProvider>
              <includes>.*</includes>
              <excludes>schema_version</excludes>
              <schemata>
                <schema>
                  <inputSchema>${db.schema}</inputSchema>
                  <outputSchemaToDefault>true</outputSchemaToDefault>
                </schema>
              </schemata>
            </database>
            <generate>
              <deprecated>false</deprecated>
              <pojos>true</pojos>
              <immutablePojos>true</immutablePojos>
            </generate>
            <target>
              <packageName>ac.simons.doag2016.db</packageName>
              <directory>target/generated-sources/jooq</directory>
            </target>
          </generator>
        </configuration>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>application.properties</include>
        </includes>
      </resource>
    </resources>
  </build>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jooq</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <!-- Recognized by Boot, automatically executed during startup. Uses the same path as in generate sources
         Benefit: You don't run into the danger that the jOOQ code doesn't fit the database -->
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
    </dependency>
  </dependencies>
</project>
```

**Comment by wilkinsona** [comment]
> Spring Boot also applies opinionated defaults. So, I was thinking that Spring Boot could perhaps offer code generation "starters" and schema migration "starters" that somehow magically interact with each other by default

That's certainly possible with Gradle, but I don't think it can be done with Maven. I'm also not sure that it's something that we want to get into in Boot. I'll see what the rest of the team think.

**Comment by wilkinsona** [comment]
As suspected this would be Gradle only. We're also in agreement that this isn't something that we want to get into in Boot. Thanks for the suggestion.

**Comment by lukaseder** [comment]
OK, thanks a lot for the feedback!
