### ISSUE TITLE
Build against Spring Framework 5

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6977]
Spring Boot 2.0 is based on Spring Framework 5 that is Java8 only. We need to reflect that in our build for 2.0

**Comment by rajadileepkolli** [comment]
As Java 9 is pushed back by 4 months, do we see spring 5 and spring-boot 2.0 too pushing back till July 2017? 

I am eagerly awaiting for spring-boot 2.0

**Comment by spencergibb** [comment]
No, full java 9 support will just come later.

**Comment by snicoll** [comment]
@spencergib I think @rajadileepkolli asked that question more in the context of the release schedule since we aimed initially at realising spring 5 when JDK9 ga is out.  

We haven't change the date, still march 2017. We'll release it ahead like we did for spring 4 and java 8

**Comment by rajadileepkolli** [comment]
@snicoll, thanks for the update , I am looking for the answer which you gave. 

This might find out of context but this is from performance perspective, are we going to support the parallel processing which Java 8 supports from spring boot 2.0 which means a more like rewriting code?
