### ISSUE TITLE
Add the ability to mark a meter metric by a value

### ISSUE THREAD

**Issue by milanbrahmbhatt** [spring-projects/spring-boot#6984]
I would like to measure mean throughput, and one-, five-, and fifteen-minute weighted moving average throughput for a particular metric in my application.  This metric can increment or decrement by more than just 1 (as provided by [DropWizardMetricServices class](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/dropwizard/DropwizardMetricServices.java)).  
I would presume the signature of these methods to be
```java
public void increment(String name, long value);
public void decrement(String name, long value);
```

thanks

**Comment by wilkinsona** [comment]
Have you seen `CounterWriter.increment(Delta)`? The delta encapsulates both the name of a metric and the amount by which its value should change. A negative value can be used for decrementation.

**Comment by milanbrahmbhatt** [comment]
@wilkinsona Thanks for the suggestion, it's precisely what I need. However, it wasn't obvious to me how the ```CounterWriter``` tracked metrics can be surfaced over http or jmx.  I'm on java 8 with spring boot 1.4.0 release.

**Comment by wilkinsona** [comment]
@milanbrahmbhatt They are no different to any other metrics and can be accessed over HTTP of JMX using the metric endpoints.
