### ISSUE TITLE
Some metrics-related beans are only created when using Java 7

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6985]
Beyond the Java 8-specific implementations, there are some differences in the metrics-related beans that are created when using Java 7 versus Java 8:
- `InMemoryMetricRepository` is only created when using Java 7 but the javadoc states that "An `InMemoryMetricRepository` is always created unless another `MetricRepository` provided by the user"
- An `@ActuatorMetricWriter`-qualifed bean is only created when using Java 7

This relates to #6982 as it's not clear what should and should not be removed for Boot 2.0 where we require Java 8.

@dsyer Can you remember what the intention was here?

At the least, I think we need to update the javadoc for the auto-configuration.

**Comment by eddumelendez** [comment]
I just was working on that and stop there.

**Comment by joshiste** [comment]
I think it somehow relates to PR #4951 (which should better be an issue...)

**Comment by dsyer** [comment]
I think the javadoc is just mouldy (it describes the behaviour prior to the Java 8 support being added). Maybe there needs to be an extra bean in Java8 (and also with Dropwizard if I catch @joshiste's drift) so there is always a `@ActuatorMetricWriter`?

**Comment by wilkinsona** [comment]
Following a helpful chat with @dsyer I now have a much better understand of the intent here. `InMemoryMetricRepository` is, largely, an internal of the Actuator's metrics support. Application code should deal with `GaugeService` and `CounterService`, both of which are present with both Java 7 and Java 8. The javadoc needs to be updated on `MetricRepositoryAutoConfiguration` to reflect this.
