### ISSUE TITLE
Deprecate ConfigurationPropertiesBindingPostProcessor being `ResourceLoaderAware`

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6986]
The resource loader isn't needed once we've removed support for the `locations` attribute on `@ConfigurationProperties`. We deprecated the `locations` attribute in 1.4, so we should apply this deprecation in 1.4.2 and them remove it in 1.5.

**Comment by snicoll** [comment]
FYI `ResourceLoaderAware` was already removed in 1.5
