### ISSUE TITLE
Add array support for spring.profiles.include.

### ISSUE THREAD

**Issue by tokuhirom** [spring-projects/spring-boot#6995]
I'm writing my configuration file like following:

```

---
spring.profiles: default
spring.profiles.active: local

---
spring.profiles.include: "\
  logging-devel,\
  mybatis-common,\
  freemarker-devel,\
  freemarker-common
"

---
spring.profiles: release
spring.profiles.include: "\
  mybatis-common,\
  freemarker-release,\
  freemarker-common
"
```

But this style is hackish. I want to write my configuration in following style:

```

---
spring.profiles: default
spring.profiles.active: local

---
spring.profiles.include:
  - logging-devel
  - mybatis-common
  - freemarker-develo
  - freemarker-common

---
spring.profiles: release
spring.profiles.include:
  - mybatis-common
  - freemarker-release
  - freemarker-common
```

**Comment by snicoll** [comment]
`spring.profiles.include` is [a `java.lang.String` in the meta-data](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L189) so it makes sense that you can't write it that way. But I guess it would be better if it was a list indeed.

**Comment by nathansgreen** [comment]
Will this cover the following case?

```YAML
spring:
  profiles: [ default, develop ]
```

This is more intuitive than having to use `'default,develop'`, which will fail if there's whitespace after the comma.

**Comment by wilkinsona** [comment]
@nathansgreen No, this issue is specifically about `spring.profiles.include`. The associated PR (#7175) also covers `spring.profiles.active`. A separate change would have to be made (to `SpringProfileDocumentMatcher`, I believe) to allow a list to be used when configuring `spring.profiles`. If that's something you'd like to see, please open a separate issue.
