### ISSUE TITLE
Error handler for beans of type added in 1.4.1 should give better advice for collections

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6996]
The error handler giving more detailed instructions in case of a `NoSuchBeanDefinitionException` is pretty helpful. However it reports references to collections of a type just as it does for a single missing type.

Referring to a collection of a certain type is an indicator to the framework that at least one bean of that type is required. By no means should the user go ahead and declare a bean of the collection type.

This originally came up [here](https://jira.spring.io/browse/DATAJPA-967).

**Comment by mbhave** [comment]
The `NoSuchBeanDefinitionException` gets thrown in the Spring Framework and we don't have access to the type of Collection when the message gets generated [here] 
(https://github.com/spring-projects/spring-boot/blob/b450fece2e592618a6ab2287039c9d2b60307435/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/diagnostics/analyzer/NoSuchBeanDefinitionFailureAnalyzer.java#L97). In cases where the `cause.getBeanType` is a Collection/Map, we could just display the `cause.detailedMessage` which would look something like `No qualifying bean found for dependency [java.util.Set<org.springframework.boot.cloud.CloudPlatform>]: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`. It's slightly lengthy but less ambiguous. @wilkinsona thoughts?

**Comment by wilkinsona** [comment]
That's certainly an improvement on the current message. However, before we go down that road, I think we should [open JIRA](https://jira.spring.io/browse/SPR) asking the framework team if they could make more type information available on `NoSuchBeanDefinitionException`. They've made similar changes for us in the past to let us improve our failure analysis.

The `org.springframework.core.MethodParamter` that's available when the `NoSuchBeanDefinitionException` is being created has the information that we need. Hopefully it can be extracted from there and added to the exception.

**Comment by mbhave** [comment]
Thanks @wilkinsona. Jira issue can be tracker [here](https://jira.spring.io/browse/SPR-14831)

**Comment by snicoll** [comment]
@mbhave I've started to work on the framework side of things and then tried to integrate that here. Feel free to use 958957f as a source of inspiration (we could be more smart about the error message depending on whether it's a collection/map or a single instance).
