### ISSUE TITLE
spring-boot-gradle-plugin downgrades flyway version 

### ISSUE THREAD

**Issue by karayv** [spring-projects/spring-boot#7001]
Hello,

spring-boot-gradle-plugin downgrades flyway version from 4.0.3 to 3.2.1. This produces discrepancies in between modules that are using or not spring-boot-gradle-plugin.  Note that flyway uses different schema in version 3 and 4.

The sample app is attached. 
[sample-boot-flyway-issue.zip](https://github.com/spring-projects/spring-boot/files/488477/sample-boot-flyway-issue.zip)
In the root module folder please run

`gradle :sample-web:dependencies`

ER
Both modules having version 4.0.3

AR 
sample-web has 3.2.1
```
$ gradle :sample-web:dependencies
:sample-web:dependencies

------------------------------------------------------------
Project :sample-web
------------------------------------------------------------

archives - Configuration for archive artifacts.
No dependencies

compile - Compile classpath for source set 'main'.
\--- project :sample-data
     \--- org.flywaydb:flyway-core:4.0.3 -> 3.2.1

default - Configuration for default artifacts.
\--- project :sample-data
     \--- org.flywaydb:flyway-core:4.0.3 -> 3.2.1

runtime - Runtime classpath for source set 'main'.
\--- project :sample-data
     \--- org.flywaydb:flyway-core:4.0.3 -> 3.2.1

testCompile - Compile classpath for source set 'test'.
\--- project :sample-data
     \--- org.flywaydb:flyway-core:4.0.3 -> 3.2.1

testRuntime - Runtime classpath for source set 'test'.
\--- project :sample-data
     \--- org.flywaydb:flyway-core:4.0.3 -> 3.2.1

```

**Comment by eddumelendez** [comment]
@karayv spring dependency management is in charge of ensure you are using the right version, in this case is flyway 3.2.1 you can see [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L74). So,  if you want to upgrade one existing dependency just override the `flyway.version` property to `4.0.3`

In gradle you can do this:

```
ext['flyway.version'] = '4.0.3'
```

**Comment by wilkinsona** [comment]
Thank you, @eddumelendez.

**Comment by karayv** [comment]
Thank you, @eddumelendez.

@wilkinsona I would not be sure that this is invalid request. Silently lowering version of transitive dependency is not something you would expect. Especially for flyway.

As a workaround using @eddumelendez suggestion for the sample app, I changed dependency declaration

/sample-data/build.gradle
`compile group: 'org.flywaydb', name: 'flyway-core', version: property("flyway.version")`

Added line in /gradle.properties
`flyway.version=4.0.3`

**Comment by wilkinsona** [comment]
> Silently lowering version of transitive dependency is not something you would expect

Given Spring Boot's dependency management, it's what should be expected.

The intention is that, by default, all of the dependencies of a project that uses Spring Boot will have versions that are compatible with the version of Spring Boot that's being used. Spring Boot only supports Flyway 3 at the moment, so it ensures that you're using a compatible version of it. Flyway 4 may work, and, as @eddumelendez has described, you can override the version of you wish.

There's more information about dependency management in the documentation, both in [general terms](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-dependency-management) and [specifically for Gradle](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-dependency-management). The section on Gradle links to the [README for the dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) as well.

**Comment by karayv** [comment]
@wilkinsona thank you
