### ISSUE TITLE
Spring boot remote shell : save imports in Groovy repl

### ISSUE THREAD

**Issue by cbornet** [spring-projects/spring-boot#7005]
Spring boot version: 1.4.0

When using the remote shell in Groovy REPL mode, the imports don't seem to persist:
```
> repl groovy
Using repl groovy
> import java.time.ZonedDateTime 

> d = ZonedDateTime.now()        
d = ZonedDateTime.now(): exception: No such property: ZonedDateTime for class: Script7
```
This is annoying because we need to always use the full package name:
```
> d = java.time.ZonedDateTime.now()
2016-09-23T12:11:01.477+02:00[Europe/Paris]
```

**Comment by wilkinsona** [comment]
@cbornet Did you forget to add a description to this issue? It doesn't mean much to me at the moment

**Comment by cbornet** [comment]
I edited the description (did it before your comment, strange you didn't see it...)

**Comment by wilkinsona** [comment]
The Groovy REPL is provided by [CRaSH](http://www.crashub.org) and I would guess that the behaviour you're seeing is a limitation of the REPL. As such any improvement would need to be made in CRaSH.

Note that the CRaSH project is largely dormant. This has caused us [other problems](https://github.com/spring-projects/spring-boot/pull/6577#issuecomment-238838583) and, as I said in that comment, I think we should consider removing support for it.

**Comment by cbornet** [comment]
Too bad. It's really cool to have a REPL shell for developpement !
