### ISSUE TITLE
Remove support for the remote shell

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7006]
The CRaSH project is dormant and we're regularly hitting its limitations. Rather than limp on with something that isn't being maintained, I think we should remove our support for it in 2.0.

**Comment by wilkinsona** [comment]
The removal was done in c5cc626d48d7167095f37b3ba938bf9a6167a734.

**Comment by aantono** [comment]
Are there any plans to extract the auto-configuration/starter part for Crash and move it to a separate repo?  There are a number of current users that heavily use it with 1.x of SB, and it would be nice to be able to use it and upgrade to SB 2.0 as well (even though there is no official support from SB).

**Comment by philwebb** [comment]
@aantono There are no plans by us, but the 1.5.x code is Apache licensed so if someone wants to take it on as a community project that would be fine by us (as long as the license isn't changed).

**Comment by anand1st** [comment]
FYI. There's a new project providing support for SSH with spring boot 2.x. You can find it at [https://github.com/anand1st/sshd-shell-spring-boot](https://github.com/anand1st/sshd-shell-spring-boot). It's not compatible with spring-boot-remote-shell implementations but it should be not be too difficult to migrate.

P.S. I am the author. If there are any suggestions, please do let me know.

**Comment by snicoll** [comment]
@anand1st no need to add the same comment in multiple places, your starter is already referenced in the [3rd party starters list](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/README.adoc)

**Comment by anand1st** [comment]
@snicoll Sorry... didn't know this. Thanks for letting me know.
