### ISSUE TITLE
Default launch.script to support setting the run levels for chkconfig

### ISSUE THREAD

**Issue by TuireHolappa** [spring-projects/spring-boot#7008]
The default launch script does not provide replacement pattern for the LSB compliant init scripts with Default-Start and Default-Stop 
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script

https://linux.die.net/man/8/chkconfig
chkconfig also supports LSB-style init stanzas, and **will apply them in preference** to "chkconfig:" lines where available. 

According to this the Maven plugin supported initInfoChkconfig does not override the Default-Start and due to this we need to define own launch.script template.

Enhancement suggestion:
change the launch.script to contain replacement patterns for Default-Start and Default-Stop to ease the 
executable jar development

**Comment by philwebb** [comment]
I'm not sure I totally follow. Do you mean change these lines in the template:

```
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
```

to something like this

```
# Default-Start:     {{defaultStart:2 3 4 5}}
# Default-Stop:      {{defaultStop:0 1 6}}
```

so that they can be replaced easily by the user?

**Comment by TuireHolappa** [comment]
That exactly was my wish.

19.10.2016 9.05 PM "Phil Webb" <notifications@github.com> kirjoitti:

**Comment by AlexFalappa** [comment]
Just made a PR implementing this enhancement request.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#7902)
