### ISSUE TITLE
DevTools impact on http cache headers in production

### ISSUE THREAD

**Issue by fracoon** [spring-projects/spring-boot#7014]
If devtools is included in the packaged jar and you run it with `java -jar ...` cache headers behave differently than without devtools.

How to reproduce:
- `mvn install` the attached project.
- run app with `java -jar`
- open in browser (authenticate with default password)
- refresh page
  The javascript file loaded by `index.html` is cached by the browser. CORRECT.

Now remove `<excludeDevtools>true</excludeDevtools>` from `pom.xml`, rebuild and try again.

The javascript file is no longer cached because the server response headers disallows caching.

The docs of spring boot dev tools states that devtools is disabled when run as `java -jar` .... 

"Developer tools are automatically disabled when running a fully packaged application."

So there should be no impact by having spring boot dev tools on classpath in production?!?

[devtoolscache.zip](https://github.com/spring-projects/spring-boot/files/491744/devtoolscache.zip)

**Comment by philwebb** [comment]
The `DefaultRestartInitializer` currently performs the checks to see if devtools restart is enabled, but we've not extended this to `DevToolsPropertyDefaultsPostProcessor`. I'm not sure if changing this logic will break remote devtools support. We may just need to fix the documentation.

**Comment by fracoon** [comment]
#7170 changes the default behavior.. so maybe only the documentation needs to state that enabling it has several impacts even if run as java -jar?!

IMHO its a bit more complex. Normally i would like to use the exactly same JAR in test,qa and production. Thats not possible at the Moment if i want to use remote dev tools support in test/qa but not in production. For that i would prefer to be able to enable or disable devtools based on the environment the application is run in. But that would presume that disabled MEANS disabled!

**Comment by wilkinsona** [comment]
@fracoon Why do you want to use remote dev tools support in test/QA?

**Comment by fracoon** [comment]
I don't at the moment... And if I think about it again.. There's no reason to
