### ISSUE TITLE
spring.autoconfigure.exclude ignores the last element when list ends with hash

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#7020]
When I'm specifying `spring.autoconfigure.exclude` in list like this:
```yml
spring.autoconfigure.exclude: \
    org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration \
    , org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration \
    #
```
The last autoconfiguration class gets ignored:
```
Negative matches:
-----------------
   XADataSourceAutoConfiguration did not match
	  - @ConditionalOnClass did not find required class 'javax.transaction.TransactionManager' (OnClassCondition)

Exclusions:
-----------
	org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration #
```
This looks like a bug because I even don't see any warnings about incorrect configuration.

**Comment by snicoll** [comment]
> This looks like a bug

This looks like more a formatting issue to me. You can exclude things that are not in the classpath so we couldn't really check if the string you're providing us refer to an actual class. It's `#` in your case but it could be anything really.

**Comment by php-coder** [comment]
And this is expected that Spring Boot tries to exclude "org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration #" instead of [ "org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration", "#"] ?

**Comment by snicoll** [comment]
That's not what you wrote. The last `\` means that you essentially wrote `org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration #`

**Comment by php-coder** [comment]
Ok, thank you for your time!
