### ISSUE TITLE
jar URLs created using a context URL with our Handler point to the root of the jar rather than an entry

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7021]
When added to `JarURLConnectionTests`, this test will fail:

```java
@Test
public void connectionToEntryInNestedJarFromUrlThatUsesExistingUrlAsContext()
		throws Exception {
	URL url = new URL(new URL("jar", null, -1,
			"file:" + getAbsolutePath() + "!/nested.jar!/", new Handler()), "/3.dat");
	JarFile nested = this.jarFile
			.getNestedJarFile(this.jarFile.getEntry("nested.jar"));
	assertThat(JarURLConnection.get(url, nested).getInputStream())
			.hasSameContentAs(new ByteArrayInputStream(new byte[] { 3 }));
}
```

Note that the `Handler` is a `org.springframework.boot.loader.jar.Handler`. If it is a `sun.net.www.protocol.jar.Handler` then the test passes. The key difference is what's returned from `getFile()` of the URL.

Handler | getFile()
---------| ---------
Ours | `/import.sql`
JDK's | `file:/Users/awilkinson/dev/spring/spring-boot/1.4.x/spring-boot-tools/spring-boot-loader/target/junit8413793381285871673/junit3981300331907567187.tmp!/nested.jar!/import.sql`

This difference throws out the spec-related logic in `JarURLConnection`. The lack of a `!/` leaves the `JarURLConnection` with an empty `jarEntryName`, i.e. pointing to the root of the nested jar. As a result, the attempt to get the input stream fails:

```
java.io.IOException: no entry name specified
	at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:164)
	at org.springframework.boot.loader.jar.JarURLConnectionTests.connectionToEntryInNestedFromUrlThatUsesExistingUrlAsContext(JarURLConnectionTests.java:136)
	…
```

**Comment by wilkinsona** [comment]
Possible fix: https://github.com/wilkinsona/spring-boot/tree/gh-7021

@philwebb Could you please cast an eye over this one as well?

**Comment by snicoll** [comment]
@philwebb could you please put that review higher on your stack? If we manage to resolve this, #6983 is probably going to be a non-issue and we'll be able to remove the code we've added in 1.4.1 to workaround the fact that `classpath:` doesn't work with fat jars. Thanks!

**Comment by philwebb** [comment]
I think this is good, although it's pretty hard to be 100% confident. I've merged it.

**Comment by wilkinsona** [comment]
And… it broke stuff

**Comment by philwebb** [comment]
This was without doubt one of my most useless reviews ever. I knew I'd probably messed it up, but panicked because the issue had been open so long and committed it anyway. To make matters worse I did `git commit --amend`, you couldn't tell what had changed and it looked you were the author. 

Sorry about that :(
