### ISSUE TITLE
Expand the range of events from which ApplicationPidFileWriter Will retrieve the environment

### ISSUE THREAD

**Issue by youngm** [spring-projects/spring-boot#7027]
With the `ApplicationPidFileWriter`, environment properties are ignored when using an event such as `ApplicationReadyEvent`. 

This is because getEnvironment method only actually supports 2 events `ApplicationEnvironmentPreparedEvent` and `ApplicationPreparedEvent`.  GetEnvironment should support more events.  Many of the events simply have a `getApplicationContext()` method.  Perhaps reflection can be used for all events that have this method?

https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/system/ApplicationPidFileWriter.java#L226

**Comment by wilkinsona** [comment]
This isn't a bug. From the javadoc:

> Note: access to the Spring Environment is only possible when the triggerEventType is set to ApplicationEnvironmentPreparedEvent or ApplicationPreparedEvent.

Why do you want to wait till the application ready event is published before writing the pid file?

**Comment by youngm** [comment]
Thanks for the response @wilkinsona.

You're right when I first read through that I assumed it was just warning trying to use an earlier event type where environment might not be available.  But you are right it is functioning as documented.

My use case is that I am writing applications deployed by bosh (http://bosh.io) which uses monit to determine when a vm's processes have finished starting up.  If I write the pid early in the spring lifecycle then monit, and subsequently bosh, will think my application is done starting up.  When in fact it is possible that some startup task, like a db migration, might end up failing app startup.

I'd rather wait until spring is completely done initializing so that I don't send monit any messages indicating the application has started when in fact it has not.

Does that help?

**Comment by wilkinsona** [comment]
> Does that help?

Yes, it does. Thank you. It also seems reasonable assuming that you have some other mechanism available for killing the process before the PID file is written.

**Comment by youngm** [comment]
@wilkinsona Exactly.  If I cannot come up with a good solution to timeout the process I'll let you know.  As that may reduce the priority of the enhancement.

Thanks.

**Comment by youngm** [comment]
For posterity here is the function I'm using to kill the process if the pid file isn't created before the monit start timeout.  Timeout should be a number (10 or so?) seconds smaller than the monit start timeout.

```
function run_java() {
    declare timeout="$1" pidfile="$2" command="$3"

    (eval "$command") &
    echo "$(date -Iseconds): Starting application.  Will wait $timeout seconds for process to start."
    start=$SECONDS
    while kill -0 $! >/dev/null 2>&1
    do
        duration=$(( SECONDS - start ))
        if [ -f $pidfile ] ; then
            wait $!
            EXIT_STATUS=$?
            echo "$(date -Iseconds): Pid $! exited with status $EXIT_STATUS"
            exit $EXIT_STATUS
        fi

        if [ $duration -gt $timeout ]; then
            echo "$(date -Iseconds): Forcefully killing $! because it failed to write pid file after ${timeout}s."
            kill -9 $! > /dev/null 2>&1
            exit 1
        fi

        sleep 2
    done
}
```
