### ISSUE TITLE
Provide a repackaging configuration option that keeps certain resources in the root of the jar

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7035]
Cloud Foundry supports [pre-runtime hooks](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile) that need to be placed in the root of an application's directory. When you're deploying a fat jar or war archive, that means they need to go in the root of the archive. This has always been a problem with wars (where resources end up in `WEB-INF/classes)` and, since the move to `BOOT-INF/classes` in 1.4, it's now a problem with jars too.

We should provide a repackaging configuration option that allows certain resources to remain in the root of the archive.

**Comment by kelapure** [comment]
For standalone deployable war files you can create the custom top level folder in  `/src/main/webapp/` like `/src/main/webapp/.profile.d`

**Comment by wilkinsona** [comment]
Ah, yes. Of course you can. Thanks, @kelapure.

**Comment by wilkinsona** [comment]
It's just occurred to me that this is really the same requirements as #6626.
