### ISSUE TITLE
DefaultNamingStrategy ignored after upgrade from spring boot 1.3.5 to 1.41

### ISSUE THREAD

**Issue by unaor** [spring-projects/spring-boot#7038]
After upgrading to version 1.4.1.RELEASE i noticed that im getting errors on my sql queries
column name was clientId and the error complained about client_id not valid
i had this error before so i was supprised
i have this line in application properties
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultNamingStrategy

In 1.3.5 its working fine
upon upgrade to 1.4.1 its broken
i also tried the ImprovedNamingStrategy but its giving the  same error

**Comment by magJ** [comment]
Spring boot 1.4.0 switch to hibernate 5, you might want to see [the hibernate migration guide.](https://github.com/hibernate/hibernate-orm/blob/5.0/migration-guide.adoc#naming-strategies)

**Comment by wilkinsona** [comment]
Thank you @magJ. @unaor This is also covered in 1.4's release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#hibernate-5
