### ISSUE TITLE
Disable JspServlet's development mode by default

### ISSUE THREAD

**Issue by hennr** [spring-projects/spring-boot#7039]
As noted in #2825 spring-boot recompiles JSPs periodically leading to an unacceptable performance loss in production environments.
This behaviour is counter intuitive and hard to find.
 
The recompilation is behind a switch now but it's turned on (means it's in dev mode all the time).
I suggest to turn it off by default and enable it via the spring-boot-devtools.

The switch I am talking about is:

`server.jsp-servlet.init-parameters.development`

**Comment by hennr** [comment]
Thanks @wilkinsona !

**Comment by php-coder** [comment]
@philwebb @wilkinsona I don't see this change in the 1.5 release notes/migration procedure.

**Comment by wilkinsona** [comment]
@php-coder It is now: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#jsp-servlet
