### ISSUE TITLE
Documentation about migrate WAR to executable Spring Boot is misleading

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#7040]
Documentation [howto-convert-an-existing-application-to-spring-boot](http://docs.spring.io/spring-boot/docs/1.3.8.RELEASE/reference/htmlsingle/#howto-convert-an-existing-application-to-spring-boot ) suggests that if you want to migrate your WAR to executable Spring Boot application in first step `SpringBootServletInitializer ` should be implemented with method `configure`. In second step `main` method should be added.

It looks that recommended way is implement method `configure`, but [the method is not called in standalone application] (http://stackoverflow.com/questions/39729012/springbootservletinitializerconfigure-is-not-called-for-executable-war) (when application starts from `main`, not as WAR on servlet container)

**Comment by wilkinsona** [comment]
The documentation is clear to me, so it's difficult to know how we could improve it. Perhaps you could make a concrete suggestion as to what would have made it clearer for you?

As things stand the documentation says:

> Spring MVC web applications are generally amenable to first creating a deployable war application, and then migrating it later to an executable war and/or jar

So, the first step (`SpringBootServletInitializer`) is showing how to create a deployable war and the second step (main method) is showing how to make the war executable so that it can be run with `java -jar`.

**Comment by michaldo** [comment]
Misleading is the following chain:
First
> protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        // Customize the application or call application.sources(...) to add sources

Then
> Once the war is working we make it executable by adding a main method to our Application

But WAR executed standalone lost customization defined in configure

I will think how to modify documentation to avoid misleading

**Comment by wilkinsona** [comment]
Thanks, I see where the confusion arose now.

**Comment by ChodipalliSatish** [comment]
Can we Migrate Existing Portlet project to SpringBoot?

**Comment by philwebb** [comment]
@ChodipalliSatish this issue has been closed for over a year and we prefer to keep the issue tracker to just bugs and enhancement requests. Please ask any questions on stackoverflow.com.
