### ISSUE TITLE
Deprecate support for the remote shell

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7044]
It's going to be removed in 2.0 (#7006)

**Comment by gnuphie** [comment]
Are there any plans for a replacement? I have really found this feature useful.

**Comment by wilkinsona** [comment]
Sorry, not at the moment. Based on the stats we have, it would appear that the remote shell isn't very widely used. For example, comparing Maven Central downloads for August, the remote shell starter had 2% of the downloads that the web starter had in August. That means that it's unlikely to be worth investing significant effort in a replacement.

**Comment by philwebb** [comment]
@gnuphie Out of interest, what do you find useful about the feature? What keeps you using it over the web endpoints or JMX?

**Comment by aligit** [comment]
is it possible to use jshell with spring boot as a replacement?

**Comment by philwebb** [comment]
@aligit you mean the REPL shipped with Java 9? If so they're different things. This issue was specifically about embedded ssh support.

**Comment by anand1st** [comment]
FYI. There's a new project providing support for SSH with spring boot 2.x. You can find it at [https://github.com/anand1st/sshd-shell-spring-boot](https://github.com/anand1st/sshd-shell-spring-boot). It's not compatible with spring-boot-remote-shell implementations but it should be not be too difficult to migrate.

P.S. I am the author. If there are any suggestions, please do let me know.

**Comment by bkahlerventer** [comment]
sshd-shell-spring-boot appears to have died with spring-boot 2.3 the last version supported...
