### ISSUE TITLE
@ConfigurationProperties classes with default list property values don't replace the default value with configured values.

### ISSUE THREAD

**Issue by AlexanderPruss** [spring-projects/spring-boot#7055]
# Bug Report

## Spring Boot 1.4.0 and 1.4.1

Sample application: https://github.com/AlexanderPruss/JestPropertiesBug/tree/ConfigurationPropertiesDefaultListValueBug 
(See the test.)

Inspired by https://github.com/spring-projects/spring-boot/issues/7045.

`@ConfigurationProperties` classes that have a configured `List` property with a default value don't correctly overwrite the default value. If a value is configured, the value is `put()` into the pre-existing default `List` rather than overwriting it. 

This can lead to several kinds of errors. If, as in Related to https://github.com/spring-projects/spring-boot/issues/7045, the default value is an immutable list, the application crashes then and there. The test case in my repo demonstrates another fun situation:

1. The configured list in application.yml is a list with a single element, {"bar"}.
2. The default value of the list in the `@ConfigurationProperties` class is a list with two elements : {"foo", "foo"}
3. Instead of replacing the default value, the configured list is put into the beginning of the list.
	 * Result: {"bar", "foo"}. 

The first type of error at least fails immediately; this second type of error could result in some very confusing bugs that only appear later.

Bug or feature? :)

**Comment by AlexanderPruss** [comment]
Derp, this is a duplicate of https://github.com/spring-projects/spring-boot/issues/7015.

**Comment by wilkinsona** [comment]
No problem, @AlexanderPruss.

**Comment by ingwarsw** [comment]
@AlexanderPruss @wilkinsona Actually is not a duplicate...
This should be fixed in Spring itself.. because it have nothing to do with way YAMLs are parsed and merged.

This one say that you can't override default list values from java file.
It should override whole list not element by element..
