### ISSUE TITLE
Define all plugin versions as properties in spring-boot-dependencies

### ISSUE THREAD

**Issue by rupert654** [spring-projects/spring-boot#7058]
Currently, it is difficult to define configuration for plugins in our own plugin management sections for plugins that have their versions defined in the spring-boot-dependencies pom.

To do this, a version must be specified for the plugins but then these versions need to be kept manually in sync with those defined in Spring Boot.

If these versions were externalised as properties, then they would also be referred to in projects, removing the duplication.

**Comment by wilkinsona** [comment]
Duplicates #4952
