### ISSUE TITLE
Enhancement - SPEL for server.ssl.* properties

### ISSUE THREAD

**Issue by flavouski** [spring-projects/spring-boot#7059]
I was setting up a project for HTTPS and thought it would be nice to use SPEL to dynamically bring in the file and password (as I am not going to keep these in the JAR for deployment).

I set:
`server.ssl.key-store-password=#{T(org.apache.commons.io.FileUtils).readFileToString(T(org.springframework.util.ResourceUtils).getFile('C:/Users/SomeUser/Documents/test/app-service/src/main/resources/dev.pw'))}`

When I ran it, it said: 

- java.io.IOException: Keystore was tampered with, or password was incorrect
- Caused by: java.security.UnrecoverableKeyException: Password verification failed

When I loaded it onto a normal variable:
```
    @Value("${someVar}")
    public String someVar(String value) {
        return value;
    }
```
I received the password.
I am assuming this would be true also for `server.ssl.key-store`, but I haven't tried it.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but it would add a huge amount of complexity to Boot's configuration support to allow SpEL to be used in `application.properties`. If you want to externalise your key store password, there are [lots of existing ways](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) to do so.

**Comment by flavouski** [comment]
As a sidenote, which I have no idea to the purpose or meaning, just accidental finding:

`@PostConstruct` will work to allow injection of server.ssl.key-store/server.ssl.key-store-password 
***only if*** I also hijack the messageSource:
    ```
@Bean
    public MessageSource messageSource() {
```
