### ISSUE TITLE
HTTPS Tomcat connector fails to start with 1.4.1

### ISSUE THREAD

**Issue by smithap** [spring-projects/spring-boot#7069]
java.lang.IllegalArgumentException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

was OK with 1.4.0.

I have code very similar to that described at http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/htmlsingle/#howto-enable-multiple-connectors-in-tomcat

**Comment by wilkinsona** [comment]
This is only educated guess as you haven't provided many details, but I think this is due to a change in Tomcat. Your trust or key store doesn't contain any X509 certificates which Tomcat now requires.

**Comment by smithap** [comment]
Can you provide more details of this please? Is there any documentation anywhere?

**Comment by smithap** [comment]
OK, so I have stopped setting my keystore as the truststore and that seems to fix it.
