### ISSUE TITLE
JsonIgnore behavior change in 1.4.1

### ISSUE THREAD

**Issue by seblange** [spring-projects/spring-boot#7070]
In Spring boot 1.4.0, the entity hereafter, when exposed through Rest, does not expose fields marked as `@JsonIgnore` (expected behavior), but nevertheless it makes such fields reusable by sort queries.
E.g.: query herafter returns items in expected order
http://myhost/productions?sort=creationtime,desc

However, since 1.4.1, the field is also ignored by sort queries... and ites are not returned in the expected order anymore.

Is it a bug in 1.4.1? Or is it the normal behavior now in 1.4.1?
In the latter case, is there any way to achieve the same behavior than 1.4.0, including creationtime must be filled in only by backend (not through a http post).

```java
import com.fasterxml.jackson.annotation.JsonIgnore
import groovy.transform.ToString
import groovy.transform.TypeChecked
import org.hibernate.annotations.GenericGenerator

import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id
import java.time.LocalDateTime

@Entity
@TypeChecked
@ToString
class Production {
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    UUID id
    
    @Column(name = "production_name", nullable = false, length = 100)
    String name

    @JsonIgnore // ignore this field as far as REST POST/GET is concerned. Yet, it is accessible for sorting but only until Spring Boot <= 1.4.0)
    LocalDateTime creationtime = LocalDateTime.now();
}`
```

**Comment by philwebb** [comment]
That's probably a question for the Spring Data Rest team. @olivergierke might know off the top of his head, but if you think it's a bug please raise an issue at https://jira.spring.io/browse/DATAREST

**Comment by olivergierke** [comment]
That is expected. To an API consumer, the field doesn't exist. The client being able to sort after those field might cause a security risk, as it's able to find out about the internal structure of the domain type, something a client shouldn't be aware of. It deals with the representation it gets, nothing else.

We unfortunately had to roll back this filtering behavior as it cause issues in other places for the just released Hopper SR4 but we will ultimately re-instantiate that for Ingalls (i.e. Boot 1.5).
