### ISSUE TITLE
Clarify that the JCache support requires "spring-boot-starter-cache"

### ISSUE THREAD

**Issue by maspen** [spring-projects/spring-boot#7071]
I have been trying to get ehcache 3.1.2 to work with spring boot. i first tried w/ the current 1.4.1.RELEASE and then with this build. I followed `/spring-boot-samples/spring-boot-sample-cache` and re-created the sample test. When i run my sample application, the expected method does not cache the results. When i run my test, it fails for the same reason.

All the documentation stating that spring boot supports ehcache 3.x needs to be revised; clearly states that if you use JCache and add the ehcache dependency it should work 'out of the box'. Not true.

When will ehcache 3.x be supported by spring boot?

**Comment by philwebb** [comment]
> All the documentation stating that spring boot supports ehcache 3.x needs to be revised; clearly states that if you use JCache and add the ehcache dependency it should work 'out of the box'. Not true.

This isn't a particularly good way to start an issue report. You've provided very little detail and already made the assertion that EhCache isn't supported.

Please provide a sample application that clearly shows the problem. We can then start to diagnose what the issue might be, and where we might need to improve the documentation.

**Comment by maspen** [comment]
You're absolutely correct; my appologies. Here's a link to a sample project that i created. The readme describes what i've tried/experienced: [https://github.com/maspen/boot-1.4.1-ehcache3-demo-Product-annotations/blob/master/README.md](https://github.com/maspen/boot-1.4.1-ehcache3-demo-Product-annotations/blob/master/README.md)

As far as the 'documentation' goes, [http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-jcache](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-jcache) states:

"JCache is bootstrapped via the presence of a javax.cache.spi.CachingProvider on the classpath (i.e. a JSR-107 compliant caching library). There are various compliant libraries out there and Spring Boot provides dependency management for Ehcache 3, Hazelcast and Infinispan). Any other compliant library can be added as well."

Please let me know if I can provide any more detail to help.

**Comment by snicoll** [comment]
The README of your project indicates you are aware of the auto-config report and how to read it. It's a shame that you didn't look for the `JCacheCacheManager` since that's what you want to use. If you did you'd have something along those lines:

```
JCacheCacheConfiguration did not match
      - @ConditionalOnClass did not find required class 'org.springframework.cache.jcache.JCacheCacheManager' (OnClassCondition)
```

Check the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_supported_cache_providers)

> Use the spring-boot-starter-cache ‘Starter’ to quickly add required caching dependencies. If you are adding dependencies manually you should note that certain implementations are only provided by the spring-context-support jar.

It's hard to state the same thing for every cache provider but on the other hand that sentence you references is incomplete. This is also a typical situation where reading the autoconfig report allows you to easily spot what is going on. Why did you read it for certain things and not the thing that matters? 

I added `spring-boot-starter-cache` to your app and I got

```
2016-10-04 10:55:39.285  INFO 63254 --- [           main] org.ehcache.xml.XmlConfiguration         : Loading Ehcache XML configuration from /Users/snicoll/Downloads/boot-1.4.1-ehcache3-demo-Product-annotations-master/target/classes/ehcache3.xml.```

**Comment by maspen** [comment]
I had a great professor in college who said that its essential for everyone wishing to teach to take a class in a subject they know nothing about at least once a year. This serves as a reminder about what its like to be a student; someone that knows less than the 'expert'. It reminds the teacher to be humble & compassionate towards those who wish to learn but have not 'arrived'.

Its wonderful what you Gurus has created the whole Spring phenomenon. We 'students' are truly grateful. However, I encourage you to reflect on my professor's suggestion & realize that we, the open-source community, the 'students', are not in your heads and arrive at using your wonderful tools from varying degrees of expertise.

Thank you for your help!
