### ISSUE TITLE
Support slim JAR deployment

### ISSUE THREAD

**Issue by ewolff** [spring-projects/spring-boot#7078]
http://product.hubspot.com/blog/the-fault-in-our-jars-why-we-stopped-building-fat-jars explains a problem with Fat JARs. While just very little of the system actually changes, the deployment still requires the full JAR with all dependencies to be copied to the server and stored in the repository. That add a lot of bloat. So maybe Spring Boot could support something like a slim JAR. The loader would load the classes of the application from the JAR and all dependencies from a repository. No dependencies are stored in the JAR itself. The dependencies would then be cached in a local .m2 so for the next deployment the dependencies wouldn't be downloaded again. Maybe it would also make sense to add a feature that just initializes the .m2 with the dependencies. That way a Docker base image could already provide the dependencies in an .m2 and the Docker image for the application would just contain the application classes.

**Comment by wilkinsona** [comment]
Duplicates #1813
