### ISSUE TITLE
SSL Ciphers missing when upgrading from Spring boot 1.3.X to 1.4.X 

### ISSUE THREAD

**Issue by blelem** [spring-projects/spring-boot#7083]
On a RHEL machine, upgrading from spring boot 1.3.X to 1.4X breaks SSL.

Environment : RHEL 7, OpenJDK1-8.

My project was working properly, using Spring boot 1.3 but when upgrading to Spring boot 1.4.1, the SSL connection is not configured properly anymore. Using an SSL online analyser tool, like https://globalsign.ssllabs.com/analyze.htm, I can see that after the upgrade all the elliptical curve ciphers reported by my spring boot web site have gone missing. 

Downgrading Tomcat to 8.0.37 fixes the issue.
Using Oracle JDK 1-8 instead of OpenJDK also fixes the issue.

The issue can be reproduced using the spring boot's official tomcat SSL sample:
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-tomcat-ssl

This seems to be related to RHEL and OpenJDK, as I don't experience this problem on the other configurations I use.

**Comment by bclozel** [comment]
Hi @blelem 
Thanks for reporting this, although I'm wondering how we can improve the situation since it seems to be a RHEL/OpenJDK issue. Did you create an issue on the Tomcat / OpenJDK trackers?
(I haven't found any issue looking like this one)

My guess is both Tomcat versions would work if using `tcnative`, so this is probably an issue with JSSE + RHEL. Maybe the Tomcat community can help you narrow down the issue? For that, you'll need a stripped down version of that sample app, with a simple Tomcat embedded instance, or more details on the SSL handshake.

I'm closing this issue as there's nothing we can do at the Boot level, but don't hesitate to report/link here what you've found - this is still very helpful to the community.

Thanks!

**Comment by blelem** [comment]
Thanks @bclozel for the quick response.

The 8.5.5 Tomcat logs are scattered with JSSE traces, while the 8.0.37 logs do not seem to mention it, which would confirm your guess .

I know very little about Tomcat, that's mainly thanks to Spring Boot doing all the hard work and working out of the box ;-)  To report to Tomcat folks, I would first need to understand how Spring boot configures Tomcat, while getting some basic understanding of embedded Tomcat. That's intriguing, so I might spend a night or two on it. But I do have a working solution (use Oracle JVM), I'll probably stick with it. I hope this report will help the few souls hitting the same issue, the workarounds are rather simple.

**Comment by bclozel** [comment]
Oh so you have stacktraces? I guess that's a pretty good start.
Can you share them here and/or with the [Tomcat users mailing list](https://tomcat.apache.org/lists.html#tomcat-users)?

**Comment by blelem** [comment]
Here is a stack trace of RHEL7 + Open JDK 1.8 + Spring Boot 1.4.4 + Tomcat 8.5
[newTomcat.log.zip](https://github.com/spring-projects/spring-boot/files/506278/newTomcat.log.zip)

It gets interesting towards the very end of the dump, 

> 2016-09-30 09:52:43.751 DEBUG 18085 --- [main] o.apache.tomcat.util.net.jsse.JSSEUtil   : The [ciphers] that are active are : [[TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA]]

No ECDHE made it to the list.

**Comment by bclozel** [comment]
Here's [a message to the Tomcat user list](http://www.mail-archive.com/users@tomcat.apache.org/msg123896.html) that could be relevant to this.

Maybe the JVM you're using doesn't support those ciphers?
