### ISSUE TITLE
Consider log in case of user supplied "spring.datasource.data" property and the file not found

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-boot#7088]
When user supply a file path for the property: `spring.datasource.data`, and spring boot auto-config cannot find the file, I think it will be much much more helpful if you can log a single line at level error indicating that.

**Comment by snicoll** [comment]
We could replace `spring.datasource.data` from `String` to `List<Resource>`. That way, the check can be done at the container level consistently.

**Comment by mhewedy** [comment]
as well as `spring.datasource.schema`
