### ISSUE TITLE
Custom ClientDetailsService not picked up by auto-configuration

### ISSUE THREAD

**Issue by bassemZohdy** [spring-projects/spring-boot#7090]
In `OAuth2AuthorizationServerConfiguration` it is auto-wiring `BaseClientDetails` but not search for `ClientDetailsService` in context, so it check for `ClientDetailsService` first and if its there should be used instead of creating in-memory one.

**Comment by snicoll** [comment]
Rather than creating an issue with what you think the code is doing, could you please explain what you're trying to do and how the current auto-configuration does not fit?

**Comment by bassemZohdy** [comment]
OK, I faced an issue when I tried to use JdbcClientDetailsService that I was creating ClientDetailsService bean with @Bean in main Spring boot configuration class, but I found that the Auto configuration not using my ClientDetailsService bean and instead it is creating inMemory with properties from application.properties and if it is not there it is generating client and use it.

what am thinking about that the Auto configuration have to search for ClientDetailsService in context if it is there have to use it, and if there is no ClientDetailsService it is OK to create inMemory one.

**Comment by snicoll** [comment]
The behaviour is working [as advertized](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-authorization-server). I'd assume that you should define a `AuthorizationServerConfigurer` bean instead.

What do you think @dsyer ?

**Comment by bassemZohdy** [comment]
sure I can make my own AuthorizationServerConfigurer and this way am using to work around it, but if we checked Spring-security project for example, if you create a UserDetailsService in context the Auto configuration is using it, so I was expecting the same behavior.

**Comment by dsyer** [comment]
Yeah, works as designed, but maybe some room for improvement in the design. (Autowiring UserDetailsService is a recent thing in spring security, by the way.)

**Comment by wilkinsona** [comment]
Boot's own OAuth support has been removed in favour of the OAuth support that's coming in Spring Security 5.x
