### ISSUE TITLE
init.d - Property 'pidFolder' Does Not Work With Relative Paths

### ISSUE THREAD

**Issue by PatrickTheFirst** [spring-projects/spring-boot#7092]
When I use the following gradle setting in the spring boot plugIn the pid file is not found when trying to stop the service:

```
springBoot {
    executable = true
    embeddedLaunchScriptProperties = [ pidFolder: './']
}
```

When running `sudo service myapp start` the pid file is generated correctly in a directory named after the app next to the jar and the system says **Started [1234]**.

When running `sudo service myapp stop` the system says **Not running (pidfile not found)**.

I expected it to shut down the service correctly.

**SYSTEM**
Linux Mint 17.3 64-bit
Kernel Linux 4.4.0-15-generic x86_64
MATE 1.12.0

Sprint Boot 1.4.1.RELEASE
Gradle 2.12

**NOTE:**
I experience the same problem with the **conf** file and property **PID_FOLDER**.
I also see this problem on my other machine with Ubuntu 14.04.1 LTS.

**Comment by philwebb** [comment]
I don't think we've considered the idea or relative folders with the launch script. I guess relative paths should be considered from the location of the jar file. We perhaps could set the working directory to the jar file location and expand full all paths.

If you're interested in having a go the launch script is [here](https://github.com/spring-projects/spring-boot/blob/097c64a91b9af23f9b83ad0d6ccf59cdb2a11c1d/spring-boot-tools/spring-boot-maven-plugin/src/it/jar-custom-launcher/src/launcher/custom.script).

**Comment by wilkinsona** [comment]
> We perhaps could set the working directory to the jar file location

We do this already, just not consistently. We do it for `start` and `run`, but not for `status` or `stop`. That looks like a bug to me.

**Comment by PatrickTheFirst** [comment]
@wilkinsona: That meets the observations in the initial description of this issue:

> When running `sudo service myapp start` the pid file is generated correctly in a directory named after the app next to the jar and the system says **Started [1234]**.

> When running `sudo service myapp stop` the system says Not running (pidfile not found).

Please keep in mind that the behavior for the console log is slightly different (see #7093). The log is not written at all.

**Comment by philwebb** [comment]
Thanks @wilkinsona. I've tagged it as a bug and targeted to 1.4.x.
