### ISSUE TITLE
init.d - Property 'logFolder' Does Not Work With Relative Paths

### ISSUE THREAD

**Issue by PatrickTheFirst** [spring-projects/spring-boot#7093]
When I use the following gradle setting in the spring boot plugIn the log file is written to the **/tmp** directory instead of the app home directory.

```
springBoot {
    executable = true
    embeddedLaunchScriptProperties = [ logFolder: './']
}
```
I use logback for logging and all logs except those for the console are written to the /log folder in the app directory where the jar resides. I would like to have the console log also in that folder which is currently not possible.

**SYSTEM**
Linux Mint 17.3 64-bit
Kernel Linux 4.4.0-15-generic x86_64
MATE 1.12.0

Sprint Boot 1.4.1.RELEASE
Gradle 2.12

**NOTE:**
I experience the same problem with the **conf** file and property **LOG_FOLDER**.
I also see this problem on my other machine with Ubuntu 14.04.1 LTS.

**Comment by snicoll** [comment]
I don't think a second issue is warranted at this point. Let's first discover what's going on with #7093 and then we can see if we need a separate issue for the `logFolder` property.

**Comment by PatrickTheFirst** [comment]
@snicoll :
Coming with a QA background I'm used to enter tickets for every occurring visible defect. For me it's a black box and I can't know the root cause and neither does anyone else at the moment AFAIK.

**2 things can happen now:**

1. The root cause is the same for #7092 and #7093. Then both tickets are fixed.
2. The root cause is different for #7092 and #7093. Probably only #7092 is fixed because this ticket is closed and labeled as **duplicate**.

These were my first 2 tickets in this project. Probably you already have ways how to handle the second scenario. I don't want to say which approach is better. I just wanted to elaborate my intension of creating two probably related tickets.

**Comment by snicoll** [comment]
I understand that, the surface area is close enough to avoid creating two separate tickets. We'll reopen this one if it happens to be a separate issue.
