### ISSUE TITLE
Added Neo4j Embedded Driver to Spring Boot.

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#7094]
In addition to testing on #7012, I believe that the embedded driver is licensed under the Apache 2.0 License see: https://repo1.maven.org/maven2/org/neo4j/neo4j-ogm-embedded-driver/2.0.5/neo4j-ogm-embedded-driver-2.0.5.pom. 

If there is a component that is AGPL, [my](http://opensource.stackexchange.com/a/2789/1060) 
 [understanding](http://programmers.stackexchange.com/q/107883/2331) of [that](https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation) is that 
> A separable portion of the object code, whose source code is excluded from the Corresponding Source as a System Library, need not be included in conveying the object code work.

because this is a driver, so long as you are not extending any classes (or directly using the drivers internal apis (meaning all you're doing is providing it with the path), and you could easily substitute the http or bolt drivers, that it can't be considered a derived work.

The purpose here is 2 fold, determine if we can provide dependency management for the driver/why or why not. If not improve the documentation to clarify and document the reason (I'll be happy to write that patch), or add it to the BOM, which I would also be happy to do.

I'm going to be reaching out the the FSF for clarification on the AGPL given what I've just said, and will request that they comment here. I'll also reach out to Neo4J

**Comment by xenoterracide** [comment]
https://neo4j.com/licensing/
> >> I’m using an Apache-licensed driver to access Neo4j. What does this mean for my application?
That’s great. Apache-licensed drivers allow you to redistribute your own code. Of course you still need to abide by the same Neo4j license terms as you normally would.

**Comment by snicoll** [comment]
@xenoterracide don't take this the wrong way but I want someone from Neo4j to confirm the license term here. There's a reason why we didn't ship the embedded driver after all.

**Comment by xenoterracide** [comment]
@snicoll I have emailed them, pending response

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by xenoterracide** [comment]
I did put in issues with both Neo4j Licensing, and FSF, but haven't heard from them obviously. Would it be possible to put a doc patch into the reference documentation explaining what the licensing concern/issue is?

**Comment by snicoll** [comment]
We have discussed this recently and we really have no intention to add dependency management for it. As for your question is concerned, this is something you should redirect to the Neo4j team. We're not providing dependency management for it, there's no reason to include any sort of documentation about it either.

If we hear back from them and it appears they've changed the licensing scheme we can reopen this issue and resume the discussion.

**Comment by xenoterracide** [comment]
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connecting-to-neo4j-embedded
> Neo4j’s embedded mode is subject to a different licensing, make sure to review it before integrating the dependency in your application.

I'm just referring to clarifying this sentence, because I was unable to discern exactly what license it was talking about (since the driver itself seems to be apache 2)

**Comment by wilkinsona** [comment]
I think we should remove the commentary on Neo4J's licence. I've opened #7214 to do so.
