### ISSUE TITLE
Maven's Failsafe Plugin Does Not Work With Spring Boot Maven Plugin's Repack Goal 

### ISSUE THREAD

**Issue by plamentotev** [spring-projects/spring-boot#7095]
Hi,

I have an Spring Boot project with integration tests that are written using `@SpringBootTest`. I'm using Maven and the Failsafe plugin to run the integration tests. Everything was working just fine until I've decided to use the repack goal of the Spring Boot Maven plugin. This broke my integration tests and I got the following error:

```
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
```

I've created a [project that reproduces the issue](https://github.com/plamentotev/issues/tree/master/repack-and-failsafe). The project consist of simple Spring Boot Application (`sample.Application`) and one integration test (`sample.SampleIT`). The integration test is run by the Maven Failsafe plugin. 

If you run:

```
mvn clean install
```

You'll see that the test is failing with an error. Comment the Spring Boot Maven plugin execution and try again. The test are passing.

I guess that this have something to do with the classpath but I'm not completely sure. 

p.s. I forgot to mention that I'm using version 1.4.1 for both Spring Boot and the Spring Boot Maven plugin.

**Comment by snicoll** [comment]
duplicates #6254 - Please make sure to read the release notes. If you override the version of the failsafe plugin you'll have to downgrade until the issue in the failsafe plugin is resolved.
