### ISSUE TITLE
Documentation for using Thymeleaf 3 only applies to projects using starter parent

### ISSUE THREAD

**Issue by ukjbrown** [spring-projects/spring-boot#7097]
The documentation for using **Thymeleaf 3** with Spring Boot 1.4 only works if using the **spring-boot-starter-parent**. It would be useful if the documentation also included how to override the dependencies when using **spring-boot-dependencies** in **dependencyManagement** instead.

**Comment by snicoll** [comment]
We don't do it for any other example and I think it would be quite tedious to copy/paste this information in the doc. If you are not using the parent but the bom, you can open `spring-boot-dependencies` and identify the block of dependencies that use that version and copy them in your own project, before the bom import. We could document that somewhere but I doubt you'll find that in the doc and it has nothing to do with Spring Boot, really.

**Comment by ukjbrown** [comment]
Fair enough, maybe the documentation should point out that it is relevant only IF you're using the parent bom. To save any possible confusion at least. The documentation is otherwise making a huge assumption on project structure.

**Comment by snicoll** [comment]
Indeed, good catch!
