### ISSUE TITLE
logging.config is not picked up if application has been bootstrapped

### ISSUE THREAD

**Issue by qerub** [spring-projects/spring-boot#7099]
The commit 43361e0ca5180f608513e6f26d29d93c3a40142c (by @wilkinsona) for #6688 that landed in 1.4.1 had a probably unintended consequence.

Let's say I have an app with `spring-cloud-context` on the classpath and that app has the `logging.config` property set in its `application.properties`. Then the application bootstrap (`BootstrapApplicationListener`) process will indirectly trigger initialization of `LogbackLoggingSystem` before the application properties have been read and then later the new `isAlreadyInitialized` check will disable reinitialization after the `logging.config` property has been set to its wanted value. The effect is that my `logging.config` property is not picked up.

**Comment by wilkinsona** [comment]
You need some changes in Spring Cloud too. See https://github.com/spring-cloud/spring-cloud-commons/issues/125.
