### ISSUE TITLE
Make in-memory database tests default to using random name

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7102]
See #7004 for background.

**Comment by snicoll** [comment]
@philwebb what did you have in mind for this. Do I understand we want to override the property when our test annotations are used? Somewhere in [`SpringBootTestContextBootstrapper#processPropertySourceProperties`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/context/SpringBootTestContextBootstrapper.java#L227-L240)  maybe?

**Comment by philwebb** [comment]
I didn't really have anything in mind, I just added the bug when #7004 was raised so we didn't forget about it. Perhaps we can add something to `AutoConfigureTestDatabase`?

**Comment by snicoll** [comment]
>  Perhaps we can add something to AutoConfigureTestDatabase?

It's already done (#7473) and it isn't the same thing IMO. If we want this to be transparent, it should apply regardless of the test slice. Arguably an integration test should have a fresh database per cached context as well. IMO the best place is the one I've referenced above but I am happy to be proven wrong.

**Comment by snicoll** [comment]
Let's stick with #7473 and let users enable that setting for integration tests as we need a way for them to opt-in.
