### ISSUE TITLE
Create an actuator RequestMatcher

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7103]
If a user wants custom security for actuator endpoints it would be helpful if they had a `RequestMatcher` that they could use. In 1.4 we have `ManagementWebSecurityAutoConfiguration.LazyEndpointPathRequestMatcher` but this could probably be simplified by delegating to `EndpointHandlerMapping` (assuming we don't get package tangles).

**Comment by philwebb** [comment]
We'll leave this for now since we'd like to revisit security in Boot 2.0

**Comment by twicksell** [comment]
+1 on this issue for Boot 2.0. Found myself needed the exact same thing today.
