### ISSUE TITLE
Feign Interceptor can't get the Authentication info when using SEMAPHORE as strategy

### ISSUE THREAD

**Issue by rmcruzv** [spring-projects/spring-boot#7109]
Question

Hi, recently I have migrated from 1.4.0 version (with Brixton.SR4). Everything looks Ok, but I have a little problem with my feign clients. When it is needed pass the security context, the interceptor obtains null as Authentication info.

Could you help me please?

This is the command definition:
`@HystrixCommand(fallbackMethod = "retrieveErrorFn", commandProperties = { @HystrixProperty(name = "execution.isolation.strategy", value = "SEMAPHORE") })`

An this is my Interceptor:

`
@Component
public class FeignClientInterceptor implements RequestInterceptor {

	private static final String AUTHORIZATION_HEADER = "Authorization";
	private static final String BEARER_TOKEN_TYPE = "Bearer";

	@Override
	public void apply(RequestTemplate template) {
		if (!template.headers().containsKey(AUTHORIZATION_HEADER)) {
			Authentication auth = SecurityContextHolder.getContext().getAuthentication();
			if (auth != null && auth.getDetails() instanceof OAuth2AuthenticationDetails) {
				OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) auth.getDetails();
				template.header(AUTHORIZATION_HEADER, String.format("%s %s", BEARER_TOKEN_TYPE, details.getTokenValue()));
			}
		}
	}
}
`

**Comment by spencergibb** [comment]
This is not a boot problem. Issue should be logged in https://github.com/spring-cloud/spring-cloud-netflix
