### ISSUE TITLE
Thymeleaf and Spring Security roles hierarchies not working in Spring Boot 1.4

### ISSUE THREAD

**Issue by Eridan46** [spring-projects/spring-boot#7114]
After upgrading a Spring Boot project from 1.3.8 to 1.4.1, Thymeleaf extras Spring Security `sec:authorize="hasAnyRole('SUB1', 'SUB2')` stopped working when accessing page with role `MASTER`.

My relevant Spring Security configuration is as follows:
```java
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    @Bean
    public RoleHierarchy roleHierarchy() {
        RoleHierarchyImpl roleHierarchy = new RoleHierarchyImpl();
        roleHierarchy.setHierarchy("ROLE_MASTER > ROLE_SUB1 ROLE_MASTER > ROLE_SUB2");
        return roleHierarchy;
    }

    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler() {
        DefaultMethodSecurityExpressionHandler expressionHandler = (DefaultMethodSecurityExpressionHandler) super.createExpressionHandler();
        expressionHandler.setRoleHierarchy(roleHierarchy());
        return expressionHandler;
    }

    @Bean
    public SecurityExpressionHandler webSecurityExpressionHandler() {
        DefaultWebSecurityExpressionHandler expressionHandler = new DefaultWebSecurityExpressionHandler();
        expressionHandler.setRoleHierarchy(roleHierarchy());
        return expressionHandler;
    }

}
```

And in the Thymeleaf template :
```html
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li sec:authorize="hasAnyRole('SUB1', 'SUB2')">
            <a th:href="@{/restricted-url}">
                <span th:text="#{restricted-url}">Restricted page</span>
            </a>
        </li>
    </ul>
</div>
```

The `<li></li>` tag is not rendered, but I still can access the page, which is itself protected at the controller level by a `@PreAuthorize("hasAnyAuthority('ROLE_SUB1', 'ROLE_SUB2')")` annotation.

**EDIT**: It actually works when running the packaged jar directly, but not when running from IDEs (tried with Spring Tool Suite 3.8.1, IDEA 2016.2.4)

**Comment by philwebb** [comment]
Are you able to share a sample project that replicates the issue?

**Comment by Eridan46** [comment]
I made a sample project here: https://github.com/Eridan46/thymeleaft-security.

Just by changing Spring Boot version from 1.4.1 to 1.3.8 you can see the sub-role link rendered:
*1.4.1*
![1 4 1](https://cloud.githubusercontent.com/assets/6002485/19182442/6ffc92d2-8c73-11e6-8c71-bcb41c862bf0.png)

*1.3.8*
![1 3 8](https://cloud.githubusercontent.com/assets/6002485/19182449/773ddc22-8c73-11e6-9897-084b3c8b7d52.png)

**Comment by wilkinsona** [comment]
@Eridan46 Thanks for the sample. Unfortunately, I can't reproduce the behaviour you've described. With both 1.3.8 and 1.4.1, the sub-role link isn't rendered when relying on the hierarchy. It is rendered if I update `SecurityConfiguration` and directly declare that the `master` user has the `SUB1` role as well as the `MASTER` role. I was logging in using `master/password`. Have I misunderstood how to reproduce the problem?

**Comment by wilkinsona** [comment]
The `WebSecurityExpressionRoot` that's used during Thymeleaf's expression evaluation has a `null` `RoleHierarchy` which would appear to explain why the `SUB1` role isn't being inherited.

**Comment by Eridan46** [comment]
Ok, I made some more tests. The more I look at it, the less I understand it...

At work, on a production project, I used this hierarchy configuration for some time without any issue. When I updated the project to Boot 1.4.1, the links using `sec:authorize="hasAnyRole('SUB1', 'SUB2')"` stopped showing when running from the IDE, but not when running the packaged JAR.
For information, I use Linux Mint 18 with JDK 1.8 and STS 3.8.2 (also tried with IDEA CE and Eclipse 4.6.1).

I just tried to reproduce my issue with the sample on my personal computer on Windows 10, JDK 1.8 and STS 3.8.2 and I can't reproduce it by running from the IDE nor by running the packaged JAR.

Now I'm wondering if my hierarchy configuration has ever been correct...

**Comment by wilkinsona** [comment]
> The thing that confuses me is that, even if the sub-page link isn't rendered, I still can access the page by going to http://localhost:8080/sub-role when logged in as master (with only MASTER role) although the SubRoleController has a @PreAuthorize("hasAnyAuthority('ROLE_SUB1', 'ROLE_SUB2')") annotation.
That means that Spring method security honors the hierarchy, shouldn't Thymeleaf do the same ?

For reasons unknown to me, it appears that Spring Security requires the role hierarchy to be configured in multiple places. I believe that you've configured it correctly for method security by overriding `createExpressionHandler` in your `MethodSecurityConfig` class. The same configuration needs to be applied to the expression handler that's used by Thymeleaf.

I don't think a `SecurityExpressionHandler` bean has any effect. Instead, I you need to configure the expression handler on the `WebSecurity` instance. Here I'm injecting the `RoleHierarchy` bean that's created by `MethodSecurityConfig`:

```diff
diff --git a/src/main/java/com/example/config/SecurityConfiguration.java b/src/main/java/com/example/config/SecurityConfiguration.java
index aa0dadb..62053e8 100644
--- a/src/main/java/com/example/config/SecurityConfiguration.java
+++ b/src/main/java/com/example/config/SecurityConfiguration.java
@@ -2,16 +2,25 @@ package com.example.config;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.context.annotation.Configuration;
+import org.springframework.security.access.hierarchicalroles.RoleHierarchy;
 import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
 import org.springframework.security.config.annotation.web.builders.HttpSecurity;
+import org.springframework.security.config.annotation.web.builders.WebSecurity;
 import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
 import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
+import org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler;
 import org.springframework.security.web.util.matcher.AntPathRequestMatcher;

 @Configuration
 @EnableWebSecurity
 public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

+       private final RoleHierarchy roleHierarchy;
+
+       public SecurityConfiguration(RoleHierarchy roleHierarchy) {
+               this.roleHierarchy = roleHierarchy;
+       }
+
        @Autowired
        public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
                auth.inMemoryAuthentication()
@@ -31,4 +40,13 @@ public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
                                .logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
                                .permitAll();
        }
+
+       @Override
+       public void configure(WebSecurity web) throws Exception {
+               DefaultWebSecurityExpressionHandler expressionHandler = new DefaultWebSecurityExpressionHandler();
+               expressionHandler.setRoleHierarchy(this.roleHierarchy);
+               web.expressionHandler(expressionHandler);
+       }
+
+
 }
```

With this change in place and using Spring Boot 1.4.1, your app behaves as desired with the `Access SUB role restricted page` link appears when logged in as master.

I'm going to close this issue as, once configured, everything appears to be working as designed.

/cc @rwinch Please correct any inaccuracies in the above.

**Comment by Eridan46** [comment]
@wilkinsona Thanks for your explanation !
