### ISSUE TITLE
@DataJpaTest in a  multimodule maven project  problem/enhancement (repository layer)

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-boot#7115]
I have just updated my Spring boot project to 1.4.1 released version. I was trying to use slice annotations enhancement (**@DataJpaTest**). 

My project is maven/gradle multimodule with this modules: controller--->service---->repository. I tried to use this new annotation in **@DataJpaTest** but my module does not have **@SpringBootApplication** because it  is only a repository library to be used for service layer. 

I did a workaround creating a class with this annotation but does not work properly because they did not "auto-scan" my test package. Now **@SpringBootApplication**  use this config with **@ComponentScan**

`@ComponentScan(excludeFilters = @Filter(type = FilterType.CUSTOM, classes = TypeExcludeFilter.class))`

Finally I have put a redundant annotation  @ComponentScan to rewrite value and it works fine. Here you have the code of the configclass

https://github.com/cristianprofile/spring-boot-mvc-complete-example/commit/af1871f3e9acc467ca61e2759e67c74721156ae9

This is a test class example:

https://github.com/cristianprofile/spring-boot-mvc-complete-example/commit/4d18e2eab8a1e10a2436f226766acb036d21940b

I do not know if is a bug in this test situation of perhaps i do not understand new @componentscan value inside **@SpringBootApplication** annotation .

**Enhancement**

It might be easier to to be able to run maven test modules without **@SpringBootApplication**  as a must. When i create multi modules i only put a class with this annotation  in controllers.

Thank you very much for your support.

**Comment by snicoll** [comment]
I don't understand what the actual problem is. If you are using a new feature, such new feature may have new requirement but there's no requirement to have `@SpringBootApplication` to use slicing. Can you please summarize what the proble actually is? 

[Have you read the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-config) and are you aware of `SpringBootConfiguration`?

**Comment by cristianprofile** [comment]
@snicoll  I have read your link and it was exactly what i needed. **@SpringBootConfiguration** allow my test to be run without @SpringBootApplication annotation. Thank you very much for your fast support.
