### ISSUE TITLE
WebClient and WebDriver Support when using @SpringBootTest

### ISSUE THREAD

**Issue by menostos** [spring-projects/spring-boot#7119]
Hi there, 

I was just wondering, using the @WebMvcTest Annotation I can get a MockMvc, WebClient or WebDriver injected.
However when I use @SpringBootTest Annoation for a test, I can't use them. I can see this, for example in MockMvcWebDriverAutoConfiguration, which only creates a WebDriver if it has a MockMvc.

Wouldn't it be nice if we could just use MockMvc, WebClient or WebDriver when using @SpringBootTest?
It seems all to be setup for it.

**Comment by wilkinsona** [comment]
You can use them with `@SpringBootTest`, but you need to enable auto-configuration of `MockMvc` using `@AutoConfigureMockMvc`. This is [mentioned in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-mvc-tests):

> You can also auto-configure MockMvc in a non-@WebMvcTest (e.g. SpringBootTest) by annotating it with @AutoConfigureMockMvc.

**Comment by alexbiddle** [comment]
Make sure the dependency also exists, e.g. for gradle
`` testCompile group: 'org.seleniumhq.selenium', name: 'selenium-htmlunit-driver', version: '2.52.0' ``
