### ISSUE TITLE
Make stop wait time in the launch script configurable

### ISSUE THREAD

**Issue by franko-s** [spring-projects/spring-boot#7121]
My application has an elaborate shutdown protocol. it sometimes takes longer than 60s for it to fully shutdown. This is a problem when using the executable jar feature of the spring boot plugin and when the app is installed as a service. The problem is that trying to stop the service fails because shutdown is not completed in the 60 seconds allotted in the launchscript included in the jar. 
Can a future enhancement for spring be to allow for a configurable wait time when stopping the the application in the launch script?

**Comment by philwebb** [comment]
I assume you specifically mean [this line](https://github.com/spring-projects/spring-boot/blob/daaa545d69a79b76913f9f41a0ddda46ae663770/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L191)?

**Comment by franko-s** [comment]
yes that's it.

**Comment by wilkinsona** [comment]
[This line](https://github.com/spring-projects/spring-boot/blob/daaa545d69a79b76913f9f41a0ddda46ae663770/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L193) would also have to change. See https://github.com/spring-projects/spring-boot/issues/4941 for details.

**Comment by ahirsh** [comment]
Hi, 

I came across this thread while trying to resolve a problem when upgrading our spring boot app, 
we now use it as a service , and after installation i found that sometimes it is impossible to stop the service , and i see the below message:
Unable to kill process <PID> 

while i see it running with (service myapp status):
Running <PID>

can you please help ? thank you !
