### ISSUE TITLE
FeignClientFactoryBean `@Autowired` doesn't work when devtools is on the classpath

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#7123]
In [FeignClientFactoryBean](https://github.com/spring-cloud/spring-cloud-netflix/commit/3991c8c5f78b6c2d781c5c4b0e86c961378e6fc9#diff-64a4e6a621013c45fbaf38bb644b38f7) I introduced an `@Autowired` dependency. It is instantiated via a [ImportBeanDefinitionRegistrar](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsRegistrar.java). When devtools is on the classpath the `@Autowired` field is null, like the bean was never autowired. It may very well be that the registrar is doing something wrong, but I'm unsure. Removing the `@Autowired` and getting the bean from the `ApplicationContext` later is the workaround.

The project linked here is a minimal one that reproduces the issue.
https://github.com/spring-cloud/spring-cloud-netflix/issues/1366#issuecomment-252024878

**Comment by wilkinsona** [comment]
`@Autowired` and `FactoryBean` don't play well together. See https://jira.spring.io/browse/SPR-9255 and https://jira.spring.io/browse/SPR-8704, for example. What you've described sounds like the latter to me.

**Comment by spencergibb** [comment]
Ok, should we just close this then?

**Comment by wilkinsona** [comment]
I think so. Even if we got it working somehow in this particular case, I wouldn't trust it not to break in the future. I just try to remember not to autowire dependencies into factory beans (and waste hours when I forget).

**Comment by spencergibb** [comment]
yeah, I added a big flag above the fields.
