### ISSUE TITLE
Check if a service can read read-only config

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7124]
When a service starts up, if the user owning the jar is different to config file, it should still be possible to load in read-only mode.

In other words given a service:

```
-r-x------. 1 happyfeet happyfeet 34846916 Oct  4 22:40 my-service.jar
```

With a config that applies `--spring.config.location=file:/opt/local/my-service/conf/my-service.properties`

The config 

```
-rw-r--r--. 1 root root 526 Oct  6 18:51 /opt/local/my-service/conf/my-service.properties
```

Should still get loaded.

```
/usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -jar /opt/local/my-service/bin/my-service.jar --spring.config.location=file:/opt/local/my-service/conf/my-service.properties
```

**Comment by wilkinsona** [comment]
I can't reproduce this on Ubuntu 14.04 LTS using either 1.4.1.RELEASE or 1.4.2 snapshots.
