### ISSUE TITLE
Application with SSL configured is consuming more than 100% CPU

### ISSUE THREAD

**Issue by green-leaves** [spring-projects/spring-boot#7126]
I have encountered this issue when deploy spring boot 1.4.0 with SSL configured with this java version:

java version "1.7.0_101"
OpenJDK Runtime Environment (rhel-2.6.6.4.el6_8-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

After deploying the application quickly consume more than 100% cpu. At first it is still able to serve incomming request but after a while it is not responding.

28646 xxxx  20   0 6681m 1.0g  12m S _**280.3**_  6.4 614:31.39 java

Bold is the % of spring boot cpu usage: 280.3%

This issue only happend when I applied the SSL. After switching to normal HTTP only, the app is running properly.

**Comment by wilkinsona** [comment]
CPU consumption is meaningless without knowing how many requests are being handled per second. Also, SSL will always have a CPU overhead and Spring Boot isn't really involved in that. Its only involvement is with configuring the embedded container to use SSL. Once that's done, the per-connection SSL handshake is performed by the embedded container.

If you have seen something that suggests CPU usage is excessive for the workload and that Spring Boot is responsible, please let us know what that is in as much detail as possible. Otherwise, the behaviour is either to be expected or will need to be reported to the developers of whichever container you're using.

**Comment by green-leaves** [comment]
There isn't any request being handled, the cpu usage is over 150% right after the application start.
Here is the application metrics:
With SSL: 	
>   "mem":645213,
> 	"mem.free":207150,
> 	"processors":4,
> 	"instance.uptime":49989,
> 	"uptime":61330,
> 	"systemload.average":0.94,
> 	"heap.committed":602624,
> 	"heap.init":255217,
> 	"heap.used":395473,
> 	"heap":3630080,
> 	"nonheap.committed":43264,
> 	"nonheap.init":24000,
> 	"nonheap.used":42589,
> 	"nonheap":219136,
> 	"threads.peak":36,
> 	"threads.daemon":34,
> 	"threads.totalStarted":40,
> 	"threads":36,
> 	"classes":6874,
> 	"classes.loaded":6874,
> 	"classes.unloaded":0,
> 	"gc.ps_scavenge.count":10,
> 	"gc.ps_scavenge.time":121,
> 	"gc.ps_marksweep.count":0,
> 	"gc.ps_marksweep.time":0,
> 	"httpsessions.max":-1,
> 	"httpsessions.active":0

Without SSL:
> "mem": 745073,
> "mem.free": 495970,
> "processors": 4,
> "instance.uptime": 170837,
> "uptime": 186399,
> "systemload.average": 1.3,
> "heap.committed": 705536,
> "heap.init": 255217,
> "heap.used": 209565,
> "heap": 3630080,
> "nonheap.committed": 40192,
> "nonheap.init": 24000,
> "nonheap.used": 39537,
> "nonheap": 219136,
> "threads.peak": 14,
> "threads.daemon": 11,
> "threads.totalStarted": 17,
> "threads": 13,
> "classes": 6478,
> "classes.loaded": 6478,
> "classes.unloaded": 0,
> "gc.ps_scavenge.count": 8,
> "gc.ps_scavenge.time": 116,
> "gc.ps_marksweep.count": 0,
> "gc.ps_marksweep.time": 0,
> "httpsessions.max": -1,
> "httpsessions.active": 0

I think the this problem caused by JDK, because I do not have this problem when running the application with java "1.7.0_111"

**Comment by wilkinsona** [comment]
> I think the this problem caused by JDK, because I do not have this problem when running the application with java "1.7.0_111"

Sounds like it. Thanks for following up.
