### ISSUE TITLE
springboot reference documentation does not have the vaadin related info.

### ISSUE THREAD

**Issue by justadev23** [spring-projects/spring-boot#7128]
springboot reference documentation does not have any vaadin related info.There is nothing mentioned about what needs to be put in application.properties file for configuring vaadin servlet.
e.g. These are 2 properties which works in application.properties:
vaadin.servlet.productionMode=true
vaadin.servlet.urlMapping=/config

I had to figure it out through getting into the code.Ideally it should be mentioned in the reference doc for springboot.

**Comment by snicoll** [comment]
> I had to figure it out through getting into the code

If you did, you must be aware that the Spring Boot integration is written by the Vaadin folks, not us. And [so is the doc](https://vaadin.com/docs/-/part/framework/advanced/advanced-spring.html)
