### ISSUE TITLE
spring-boot landing page is broken when visiting over https

### ISSUE THREAD

**Issue by abatkin** [spring-projects/spring-boot#7134]
If you visit the Spring Boot landing page over non-https (http://projects.spring.io/spring-boot/) it works fine.

If you visit the Spring Boot landing page over https (https://projects.spring.io/spring-boot/) it does not work fine.

The differences that I have noticed include:
* The box in the right-column titled "Spring Boot" with all of the various versions and Reference + API Links is missing
* The "Download" box in the "Quick Start" section is missing most of its content (it contains the paragraph "The recommended...Gradle." but no other content, plus the Version Selector and Maven/Gradle selectors are missing)

The content of the pages is identical, so this probably has something to do with a script that is supposed to format the content of the boxes.

**Comment by snicoll** [comment]
Thanks for the report but there's nothing in Spring Boot we can do about that. I've reported it to Sagan https://github.com/spring-io/sagan/issues/678

**Comment by dsyer** [comment]
Actually the code for that page is in this project (gh-pages). Other projects' landing pages work fine so it's probably a bug here.

**Comment by snicoll** [comment]
I didn't know that, thanks @dsyer
