### ISSUE TITLE
Gradle Plugin's new bootRepackage breaks features that rely on the SystemClassLoader

### ISSUE THREAD

**Issue by jgrand-Digi** [spring-projects/spring-boot#7135]
Hello,

I've recently tried to update my Spring-boot application from an 1.3.x version to the 1.4.1.RELEASE and stumbled upon an issue that stopped me from upgrading : 
I'm using Gradle and the Gradle Spring-boot plugin and noticed that the `bootRepackage` task has changed the executable JAR layout from 1.3.x versions.

As far as I can see, the new layout is closer to a WAR embedded in Tomcat JAR and might look more pleasant to some.
However, moving my classes and libraries to BOOT-INF made them unreachable by the standard ClassLoaders (which was warned in the changelog and you advised not to rely on the standard Classloaders). 
But, in my case, my application relies on a custom implementation of a FileSystem which is loaded by `java.nio.file.FileSystems.getDefault()` calling my custom FileSystemProvider set as default provider.
This implementation does not use the Spring-boot class loader and cannot resolve the BOOT-INF/libs(nor classes) issue, thus preventing me from executing the JAR with a `java -jar` command. Note that the `gradle bootRun` command works fine though (probably by loading all classes at start).

I made a stub project that illustrates my issue at https://github.com/jgrand-Digi/TestFSPDelegate . It shows a Spring-boot application built with Gradle which overrides its default FileSystemProvider with a custom one. Running it from an IDE or with a bootRun logs the line "It works!" to the console and executing the JAR throws an Exception.

I tried to add a gradle task after `bootRepackage` to repackage (again) the JAR and moving my Provider class back to the root of the JAR but failed to do so (I've got a limited knowledge of Gradle and it seemed I compressed the .class files twice).

My question(s) is(are) then this : 
Do you understand my issue ? 
Can you find an easy way around (I mean, without telling me to use a Spring-beaned factory instead of any Paths.get() or new File() in my code base )? 
Could the Gradle Spring boot plugin add a custom configuration for classes/libs that should not be moved to BOOT-INF ?

Thanks a lot.

**Comment by wilkinsona** [comment]
Duplicates #7110. See #6626 for an option to keep certain content in the root of the jar.
