### ISSUE TITLE
Upgrade to Spring Retry 1.2.0.RC1

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#7136]
Spring AMQP 2.0 is already based on the Spring Retry 1.2 and we can't build it against IO Cairo.
Spring Integration 5.0 will be based on Spring Retry 1.2 as well.

**Comment by wilkinsona** [comment]
See also #7053 (AMQP 2.0) and #7029 (Integration 5.0)

**Comment by wilkinsona** [comment]
@dsyer What are you plans for a 1.2.0 of Spring Retry? We could upgrade in 1.5 if the timing works out.

**Comment by artembilan** [comment]
@wilkinsona , looks like there are some breaking changes and Spring AMQP 1.6.x won't be compatible.

**Comment by wilkinsona** [comment]
That sounds unpleasant. @dsyer Is that intentional? Do we need to wait for 2.0 to upgrade to Retry 1.2?

**Comment by dsyer** [comment]
I was hoping it would get a berth in 1.5. Not aware of the incompatibility. Maybe @artembilan can link to an issue in spring-retry?

**Comment by artembilan** [comment]
@dsyer , together with @garyrussell you recently talked about something in the `key generation` and you plan some fix there.
Seems for me this issue is fully related https://github.com/spring-projects/spring-retry/issues/49

**Comment by garyrussell** [comment]
It's only a test and only in Spring AMQP 2.0 which is for boot 2.0 (SF 5) - we can work around it if needed. We are not planning on a Spring AMQP change for boot 1.5 (unless some requirement comes up).

**Comment by garyrussell** [comment]
@artembilan Why do you think it's an issue for 1.6.x?

**Comment by garyrussell** [comment]
Perhaps we should switch the IO Compatibility build to use the 1.6.x branch.

**Comment by artembilan** [comment]
I don't know. I will just quote you: https://github.com/spring-projects/spring-retry/issues/49#issuecomment-249040628 

Meanwhile I can run tests for S-A 1.6 against S-R 1.2...

**Comment by garyrussell** [comment]
No; S-A 1.6 uses s-r 1.1.x

[AMQP=647](https://jira.spring.io/browse/AMQP-647) is for 2.0 only.

**Comment by artembilan** [comment]
But @wilkinsona is going to make Boot 1.5 on S-R 1.2. S-A will be still 1.6

**Comment by artembilan** [comment]
Here we go in S-A 1.6 with S-R 1.2:
```

org.springframework.amqp.rabbit.retry.MissingIdRetryTests > testWithNoId FAILED
    java.lang.AssertionError at MissingIdRetryTests.java:102
                                                                               
org.springframework.amqp.rabbit.retry.MissingIdRetryTests > testWithId FAILED  
    java.lang.AssertionError at MissingIdRetryTests.java:142                                                             
```
!

**Comment by garyrussell** [comment]
Doh - yes, of course; that will be a problem - blame the medication.

We'll need to do a backport (conditional).

**Comment by garyrussell** [comment]
Maybe it will be simpler to create a 1.7.x branch for 1.5 to make life simpler.

**Comment by artembilan** [comment]
That makes S-A 1.x compatible with S-R 1.2. But there is no guaranty how it will be with many other applications. 
Or does that works, @wilkinsona , if we just fix our projects for whole IO compatibility ?

**Comment by wilkinsona** [comment]
Taking a step back, I assume there's no way to rework the change in Spring Retry such that it's backwards compatible?

> Or does that works, @wilkinsona , if we just fix our projects for whole IO compatibility ?

We need Spring AMQP 1.6.x to remain compatible with Spring Retry 1.1.x as that's what's in Boot 1.4.x.

We also need a version of Spring AMQP that's compatible with Spring Retry 1.2.x. Creating Spring AMQP 1.7.x just to accommodate Retry 1.2 seems  a bit extreme to me, but I'm aware I'm not aware of the details. From my perspective, if it's only Spring AMQP 2.0 that's compatible with Spring Retry 1.2 then so be it. The upgrade to Retry 1.2.x will just have to wait for Boot 2.0.

**Comment by garyrussell** [comment]
Spring AMQP used (Dave would probably say abused 😄 ) the retry state cache by clearing a key from it in some circumstances (thus canceling retry for a message).

Spring retry 1.2 made a necessary change to the nature of the cache key, preventing this mechanism from working any more, and causing a memory leak.

We came up with a much superior mechanism for the AMQP functionality with another small change to Spring Retry.

It's a rarely used feature but I do know that it's used (IIRC, VMW asked for it).

One solution might be to add a property to the interceptor to use the old key if it's set and we could use reflection to set it it Spring AMQP - it's not affected by the problem that required the change to the key strategy.

**Comment by dsyer** [comment]
You would need reflection so that Spring AMQP could work with retry 1.1 and 1.2, I guess? I think that's the best approach, since (as Gary pointed out) the change is transparent for "normal" users who aren't abusing the retry cache. Anyone who is abusing it would have an escape hatch if we add the flag.

**Comment by artembilan** [comment]
Spring Integration 4.3 works well with Spring Retry 1.2, btw.
So, what else depends of Spring Retry to be sure for Boot 1.5? Spring Batch ?

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-retry/pull/58

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-amqp/pull/476
