### ISSUE TITLE
Generate RPMs from Maven

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#714]
Marco Vermeulen's talk on micro services [1] mentions packaging applications as RPMs. Perhaps we can automate this from the maven/gradle build.

[1] http://greach.es/speakers/marco-vermeulen-building-micro-services-using-spring-boot-and-friends/

**Comment by ewolff** [comment]
See https://github.com/ImmobilienScout24/spring-boot-rpm-maven-plugin

**Comment by Polve** [comment]
Is there a plugin to create a .deb too?

**Comment by yilativs** [comment]
https://github.com/ImmobilienScout24/spring-boot-rpm-maven-plugin
is not actively developed and not in maven central
and also it has dependency on aws-cli and openjdk-1.7.0 (ie if u have oracle java installed it doesn't see it).
Would be nice if springboot/pivotal include such project under it's wing.
The plugin that can create deb files is needed as well.

**Comment by wilkinsona** [comment]
The support for init.d added in 1.3 addresses the underlying requirement. Closing as won't fix.
