### ISSUE TITLE
Make log_file and pid_file fully configurable via embeddedLaunchScriptProperties

### ISSUE THREAD

**Issue by koopsc** [spring-projects/spring-boot#7140]
We use Spring-Boot 1.4.x fat jars in service mode with a custom `logback.xml`. Our naming conventions should also be applied to the `log_file` and `pid_file` specified in the `launch.script`. We don't want to use environment variables, as logging specific configurations shall be delivered with the release of our application.
`EmbeddedLaunchScriptProperties` seem to be the perfect solution for this problem. Unfortunately, only `logFolder` and `pidFolder` can be set with this mechanism. The filenames are not available up to now.

**Comment by wilkinsona** [comment]
You can use `APP_NAME` configured in a `.conf` file to control the name of both the log file and the pid file. If you do that, `identity` is set to the value of `APP_NAME`:

```
[[ -n "$APP_NAME" ]] && identity="$APP_NAME"
```

`identity` is then used to set the name of both the log file and the pid file:

```
# Initialize log file name if not provided by the config file
[[ -z "$LOG_FILENAME" ]] && LOG_FILENAME="${identity}.log"
…
log_file="$LOG_FOLDER/$LOG_FILENAME"
```

```
pid_file="$PID_FOLDER/${identity}.pid"
```

We don't want to add complexity to the launch script without good reason. Can you please explain why the above doesn't meet your needs? You should be able to deliver the `.conf` file with your app.

**Comment by koopsc** [comment]
Right now it does not match our naming conventions very well, as the resulting log_file is not a real logFile anymore. It accumulates direct printings to stdout only. As a result we don't want to use `$identity` for this purpose. We prefer to set the folder and the filename directly via EmbeddedLaunchScriptProperties.
If you think, that there may be a chance of success, we can also try to add it ourselves and submit a PR. I think it should be possible without affecting any backwards compatibility.

**Comment by wilkinsona** [comment]
Thanks very much for the offer of a PR, but I don't think we're at that stage yet. Before we consider making any changes, I'd like to understand why what we already have doesn't meet your needs.

> Right now it does not match our naming conventions very well, as the resulting log_file is not a real logFile anymore. It accumulates direct printings to stdout only. As a result we don't want to use `$identity` for this purpose.

As I showed above, you don't have to use `identity`. You can set `LOG_FILENAME` to whatever you want. You can also set `LOG_FOLDER` if you want complete control over both the file's path and its name.

**Comment by koopsc** [comment]
Thank you for your feedback and you are absolutely right, that it is possible to set the variables via .conf files. I'd still like to set this specific configuration via launchScriptProperties for mainly two reasons:
1. We try to separate different aspects of configuration. The logFile-Handling from the launch.script is solely a launch.script functionality and does not affect the service in the jar. Hence, we configure it for every instance of a specific Service. The .conf file is used for a specific instance of a service and may vary if we launch it more than once. We produce overhead in these .conf files, if we introduce launch.script configuration. When I saw the nice feature of launch.script properties, I thought that this is a fantastic way to separate theses aspects of configuration and I was wondering why the folder is available, but the filname not.
2. Because of our corporate structure the `CONF_FOLDER` is still managed by operations to manage JVM-Properties considering the available physical resources. I know that this is specific to our infrastructure right now, but it gives a real example why we want to seperate general config of the jar and instance specific config of our services.

**Comment by wilkinsona** [comment]
Thanks, @koopsc. That's the kind of reason I was looking for.

**Comment by koopsc** [comment]
Hi @wilkinsona, are you interested in a PR for 1.5.0 or do you prefer to do it on your own?

**Comment by snicoll** [comment]
@koopsc if you'd like to work on a PR, feel free to do so! Keep in mind that M1 is around the corner so let us know when it'd be available.

**Comment by koopsc** [comment]
Thanks for the reply @snicoll. I'll try to submit it quickly

**Comment by koopsc** [comment]
@snicoll PR is submitted

**Comment by wilkinsona** [comment]
Closing in favour of the PR which has now been merged.
