### ISSUE TITLE
Upgrade to a Spring Integration 5 compatible version of Spring Integration Java DSL

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7143]
It doesn't appear to exist yet, even as snapshots.

/cc @artembilan

**Comment by wilkinsona** [comment]
See #7029

**Comment by artembilan** [comment]
Thank you , @wilkinsona , for the pointer.
We are going to release Java DSL 1.2 this week and then our plans to move DSL fully to the SI Core.
Will hope to have "compatible" version (SNAPSHOT) over a couple weeks since today.

**Comment by wilkinsona** [comment]
Sorry, @artembilan. I think you may we'll have already told me that. It makes this a duplicate of #7029.
