### ISSUE TITLE
metricFilter should be metricsFilter in chapter Traditional deployment 

### ISSUE THREAD

**Issue by ktong** [spring-projects/spring-boot#7147]
In Spring boot 1.4, the name of MetricsFilter changed from metricFilter to metricsFilter. But in [reference doc ](http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/howto-traditional-deployment.html#howto-servlet-2-5) it's still metricFilter.

**Comment by snicoll** [comment]
See #6835
