### ISSUE TITLE
Spring boot propery spring.data.mongodb.database is not picked up when coming from a dependent jar file.

### ISSUE THREAD

**Issue by megalucio** [spring-projects/spring-boot#7148]
Spring boot mongodb properties such as 

`spring.data.mongodb.database`
`spring.data.mongodb.uri`

are not picked up when coming from a dependent jar file. Overwriting is not honouring what is indicated in the [spring boot documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) where application properties packaged inside a jar should be loaded before default properties. 

Other properties from other spring boot projects do honor this order, for example `spring.batch.job.enabled`.

This is reproducible both in 1.4.0 and 1.4.1. Find attached a zip file([7148.zip](https://github.com/spring-projects/spring-boot/files/523135/7148.zip)) with a little example of this abnormal behaviour.

**Comment by snicoll** [comment]
Unfortunately, your analysis is inaccurate. It has nothing to do with mongodb keys or any other keys for that matter, your project structure is broken.

Spring Boot will read _a_ file named `application.properties` at the root of the classpath. Your project has two of them. We [won't read them both, we won't merge them](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files).  There's nothing in the doc that indicates we will override several application.properties at the root of the classpath.

**Comment by megalucio** [comment]
OhI understand now, I though the application.poperties will merge, will not that be considered as a posiible improvement? Also, that still does not explain why other properties such as `spring.batch.job.enabled` behave differently

**Comment by snicoll** [comment]
I don't believe that `spring.batch.job.enabled` behaves differently for the reason I explained above.  We have no intention to merge several `application.properties` at the root of the classpath: this feels a bit odd and Boot offers other solutions to combine your configuration. If you still have more questions, please ask them on stackoverflow.
