### ISSUE TITLE
Integration test get Error `java.net.SocketException: Too many open files`

### ISSUE THREAD

**Issue by tigerMoon** [spring-projects/spring-boot#7149]
the details of the problem in [stackoverflow](http://stackoverflow.com/q/39970668/6329620)

**Comment by philwebb** [comment]
Are you able to share a project that reproduces the issue?

**Comment by tigerMoon** [comment]
Finally  I find this problem caused by my custom Apache HttpClient for Spring RestTemplate . when i run with integration test, the second test class invoke this.

the following is my config:

```
@Bean
    @ConditionalOnProperty(value = "com.social.credits.infra.fiber.enabled", matchIfMissing = true)
    public HttpClient httpClient() {
        return FiberHttpClientBuilder.
                create(httpIoThread). // use io threads
                setMaxConnPerRoute(httpConnPerRoute).
                setMaxConnTotal(httpConnMax).build();
    }

    /**
     * set restTemplate http client
     * use Apache httpclient
     * if use restTemplate.getInterceptors().add(new ScClientHttpRequestInterceptor()); 
may get null from result
     */
    @Bean
    public RestTemplate restTemplate() {
        RestTemplate restTemplate = new RestTemplate();
        HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory(httpClient());
        factory.setConnectionRequestTimeout(connectionRequestTimeout);
        factory.setReadTimeout(readTimeout);
        // construct interceptor
        List<ClientHttpRequestInterceptor> interceptorList = new ArrayList<>();
        interceptorList.add(new ScClientHttpRequestInterceptor());
        InterceptingClientHttpRequestFactory interceptorFactory = new InterceptingClientHttpRequestFactory(new BufferingClientHttpRequestFactory(factory), interceptorList);
        restTemplate.setRequestFactory(interceptorFactory);
        return restTemplate;
    }

```

**Comment by wilkinsona** [comment]
Thanks, @tigerMoon. Unfortunately, that doesn't really give us enough to investigate further. We really need a complete sample that reproduces the problem so that we can be sure we're running the same things as you. For example, I can't tell from the above what `FiberHttpClientBuilder` is, or what values you've configured it with.

**Comment by tigerMoon** [comment]
Thank you for quick response.  I`m doing it now ,  after finishing it i`ll feedback

**Comment by tigerMoon** [comment]
it is the error of the ` FiberHttpClientBuilder ` which i use [one of implement of ApacheHttpClient  ](http://docs.paralleluniverse.co/comsat/)  , not spring boot bug. i`ll report this to others .  thank you for so much help. if interesting .here is the github project [Github](https://github.com/tigerMoon/springboot-fiberclient-integration-test)
