### ISSUE TITLE
Properties group for atomikos datasource in appendix A doesn't match implementation

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#7153]
Version: 1.4.1.RELEASE

The org.springframework.boot.jta.atomikos.AtomikosDataSourceBean specifies configuration properties under spring.jta.atomikos.datasource. However, the properties definition in appendix A specifies the property group as spring.jta.atomikos.connectionfactory. One of the two should be changed to make it consistent.

**Comment by snicoll** [comment]
Actually, we do have `spring.jta.atomikos.connectionfactory` as  well on `AtomikosConnectionFactoryBean`so both namespaces are valid actually. I am going to review the list but did you hit an actual issue?

**Comment by hoeckxer** [comment]
I double checked, and it looks like I've overlooked the correct properties in the documentation; I was mislead by the rename and missed the spring.jta.atomikos.datasource.* properties. Issue can be closed, sorry for the trouble!

Kind regards,

Erwin

Op 12 okt. 2016 om 17:34 heeft Stéphane Nicoll <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Actually, we do have spring.jta.atomikos.connectionfactory as well on AtomikosConnectionFactoryBeanso both namespaces are valid actually. I am going to review the list but did you hit an actual issue?
