### ISSUE TITLE
Enhancement: for Spring (5) Platform B

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#7163]
currently dealing with the "transient dependency" issue in our code, now that we've migrated to Spring Platform in our corporate codebase. The problem I've realized is that all deps are currently pulled in at `compile` time, and so people add them transiently.

It might be useful to have `platform` only import things as runtime by default, so if you depend on something that depends on something, the it doesn't initially result in anything other than a runtime dep.

this is my current workaround

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils</artifactId>
				<version>${commons-beanutils.version}</version>
				<scope>runtime</scope>
			</dependency>
```

then if you *actually* want a compile time on `beanutils`

```
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<scope>compile</scope>
		</dependency>
	</dependencies>
```

`velocity` is a good example of a package that pulls in other packages that you might want to be runtime only (`commons-lang:2.6` and `commons-collections:3.2.2`).

I think this is more in line with Java 9 functionality too. I can understand if `-starters` have to import as compile time, this is specifically referring to the platform bom.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I think what you are proposing would be confusing for users. Maven's default scope for a dependency is `compile` and if we overrode that to be `runtime` it would lead to unexpected compilation errors, particularly as we have no way of second guessing what a user wants to compile against and what they just need at runtime.

**Comment by xenoterracide** [comment]
eh, alright, I'm still waiting to find out how maven will facilitate jigsaw... don't know if they've published anything on that yet.

It occurred to me that this could be a `${defaultScope}` property or something, and set to compile, but then it would be easy for people to change; if they want to get on with preparing for the death of accidental transient deps. Note: don't really expect this to sway you.

**Comment by spencergibb** [comment]
Maven can tell you when you are using an undeclared transitive dependency in your project: http://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html Option to fail the build.
