### ISSUE TITLE
spring actuator is not working in spring boot v 1.4.1

### ISSUE THREAD

**Issue by shijazi88** [spring-projects/spring-boot#7167]
I tried to generate one spring boot project from spring initializr, I only added web and actuator modules, then run the project using STS, it is working fine but actuator is not working.

I changed the spring boot to version 1.3.5, actuator is working fine and i can see the info, health, and other information provided by actuator.
thanks

**Comment by snicoll** [comment]
That doesn't tell us much. Why do you think it's a bug? What does "not working" means? Please share more details, preferably a sample project that reproduces the problem. Since you've just created a new project, it shouldn't be hard.

**Comment by shijazi88** [comment]
Thanks for reply, please download attached project, and try the following steps:
1- open pom.xml, version of spring boot is 1.4.1, run the project and try to call http:/localhost:8080/health, default error page will be displayed

2- stop the project and go to pom file, then change the spting boot version to 1.3.5, then run the project and call same previous URL, you will find something similar to 

{status: "UP",
diskSpace: {
status: "UP",
total: 249769230336,
free: 8878161920,
threshold: 10485760}
}

also I attached 2 screenshots of log, please check the difference between them

<img width="1361" alt="log-v 14 1" src="https://cloud.githubusercontent.com/assets/14152601/19408673/e539b472-92cb-11e6-8584-243dca304520.png">
<img width="1366" alt="log-v1 3 5" src="https://cloud.githubusercontent.com/assets/14152601/19408674/e542cc10-92cb-11e6-9080-4650f1b6c456.png">

[actuator.zip](https://github.com/spring-projects/spring-boot/files/531046/actuator.zip)

**Comment by snicoll** [comment]
Your maven cache is corrupted. Some jar could not be downloaded properly or something. Try removing them from your local cache (`~/.m2/repository`) and try again.

**Comment by shijazi88** [comment]
thanks, i removed the maven cache, and it's working fine
