### ISSUE TITLE
Set excludeDevtools=true in spring-boot-starter-parent

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7170]
Or maybe change the default? Or maybe I don't know what it means (the docs are thin)?

I would like to not have it in my ueberjar by default in general (I know it tries to detect if it is running from the jar, but there are plenty of other reasons to exlcude code that isn't going to be used at runtime).

Possible complication: STS tooling support for devtools in CF might have to do something complicated to ensure the jar is available at runtime when the user is developing the code. This just highlights another problem really, that it isn't easy to detect when an app is "in development" and in some cases we need a steer from the user.

**Comment by dsyer** [comment]
UPDATE: I just tried it and the STS tooling ignores the Boot plugin configuration anyway, so you end up with devtools on the classpath in CF if you deploy that way (which makes perfect sense - I must be "in development" if I deployed my app from STS).

**Comment by snicoll** [comment]
it's a build packaging thing so I'd expect STS to ignore that as well.

**Comment by philwebb** [comment]
Reopening to check if we need some additional docs around "remote devtools" support.
