### ISSUE TITLE
AspectJ compile time weaving with our annotation processor

### ISSUE THREAD

**Issue by mohanr** [spring-projects/spring-boot#7176]
I think I followed the instructions of https://github.com/spring-projects/spring-boot/issues/4847 and also commented there. Since it is closed I am opening this. Hope it is alright.

> [INFO] --- aspectj-maven-plugin:1.8:compile (default) @ enterprise ---
> [WARNING] No sources found skipping aspectJ compile

If I specify `<sources/> `this is what I get. And if I specify "/src/main/java" as `<source>` then I get the original error(https://github.com/spring-projects/spring-boot/issues/4847).

Adding the maven compiler `<proc>none</proc>` shows the error still**.( I didn't have this section in my pom. Added to check.)**

_[INFO] --- aspectj-maven-plugin:1.8:compile (default) @ enterprise ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[WARNING] Field value processing of @ConfigurationProperty meta-data is not supp
orted
        <unknown source file>:<no line information>

[ERROR] Internal compiler error: java.lang.IllegalStateException: Failed to writ
e metadata at org.springframework.boot.configurationprocessor.ConfigurationMetad
ataAnnotationProcessor.writeMetaData(ConfigurationMetadataAnnotationProcessor.ja
va:385)
        D:\workspace-sts-3.7.3.RELEASE\Enterprise\src\main\java\com\pearson\next
gen\enterprise\web\rest\util\SecurityUtil.java:0_

               <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>aspectj-maven-plugin</artifactId>
                    <version>1.8</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <source>1.8</source>
                                <target>1.8</target>
                            </configuration>
                        </execution>
                    </executions>
                    <configuration>
                        <showWeaveInfo>false</showWeaveInfo>
                        <complianceLevel>1.8</complianceLevel>
 			 		<sources>
			            <source>
			              <basedir>src/main/java</basedir>
			              <includes>
			                <include>**/CourseServiceFakeAspect.java</include>
			                <include>**/LoggingAspect.java</include>
			              </includes>
			            </source>
			          </sources>
                   </configuration>
                </plugin>

**Comment by snicoll** [comment]
>  Since it is closed I am opening this. Hope it is alright.

It is but I am afraid I won't be able to help you with this. I need a way to reproduce the error and see what might be missing in the doc.

**Comment by mohanr** [comment]
What does `<sources/> do that could fix it ?`

**Comment by snicoll** [comment]
@mohanr we prefer to use this issue tracker for bugs and enhancements. Please share a project that reproduces the issue and use stackoverflow if you have questions.

**Comment by mohanr** [comment]
I will try stackoverflow. If the doc. mentions it I can read it too.

**Comment by t-beckmann** [comment]
The reason for this is that the configuration metadata processor attempts reading it's output resource using Filer.getResource and runs into the etc/ajc bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=530665 on Filer.createResource later on.
