### ISSUE TITLE
@MockBean does not work with AbstractTransactionalJUnit4SpringContextTests

### ISSUE THREAD

**Issue by raycursif** [spring-projects/spring-boot#7177]
Hi, I try to use @MockBean with AbstractTransactionlJUnit4SpringContextTests like code below :
```
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class Test1 extends AbstractTransactionalJUnit4SpringContextTests{

  @MockBean
  private Generator<String> idGen;
```
or 
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class Test1 extends AbstractTransactionalJUnit4SpringContextTests{

  @MockBean
  private Generator<String> idGen;
```

idGen can not be injected by Spring, it has value null.

But if I try this code:
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class Test1 {

  @MockBean
  private Generator<String> idGen;
```
idGen is mocked by Mockito, it works perfectly. But I need to use @Transactional or AbstractTransactionalJUnit4SpringContextTests to rollback my database operations after tests.

Is there a way to use MockBean and AbstractTransactionalJUnit4SpringContextTests ?

Regards

**Comment by raycursif** [comment]
Spring boot version used :
`org.springframework.boot:spring-boot-starter-test:1.4.1.RELEASE`

**Comment by snicoll** [comment]
I don't see right now why it wouldn't work. Why are you using that base class to begin with? You could just add `@Transactional` on your test class (the second example) and it should work just fine. Can you try that as a workaround for the moment?

**Comment by raycursif** [comment]
Hi, 
Thanks for the quick response.

For the base class, because I need to use the test-managed transaction to rollback database transactions automatically after tests and `AbstractTransactionalJUnit4SpringContextTests` has the annotation `TransactionalTestExecutionListener` allows me to do that.

```
@Transactional
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class Test1 {

  @MockBean
  private Generator<String> idGen;

  @Test
  public void test() {
    System.out.println("test");
  }
```
this injection of idGen works, but I don't have test-managed transaction.


I tried also this:
```
@Transactional
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
@TestExecutionListeners({TransactionalTestExecutionListener.class, SqlScriptsTestExecutionListener.class})
public class Test1 {

  @MockBean
  private Generator<String> idGen;

  @Test
  public void test() {
    System.out.println("test");
  }
```
this is equivalent to `extends AbstractTransactionalJUnit4SpringContextTests`


It seems that @MockBean does not work with `@TestExecutionListeners({TransactionalTestExecutionListener.class, SqlScriptsTestExecutionListener.class})`.

**Comment by snicoll** [comment]
>  I need to use the test-managed transaction to rollback database transactions automatically after tests 

Again, If you add `@Transactional` on your test, it will exactly do that. Can you please try:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
@Transactional
public class Test1 {

  @MockBean
  private Generator<String> idGen;
}
```

**Comment by raycursif** [comment]
This works perfectly.

Thanks again
regards

**Comment by philwebb** [comment]
The root cause of the problem is probably that `@TestExecutionListeners({TransactionalTestExecutionListener.class, SqlScriptsTestExecutionListener.class})` means that the `MockitoTestExecutionListener` won't get called. You'll need `mergeMode=MergeMode.MERGE_WITH_DEFAULTS` to make sure it's included but as @snicoll says, both `TransactionalTestExecutionListener` and `SqlScriptsTestExecutionListener` are registered by default so you shouldn't need `@TestExecutionListeners` at all.
