### ISSUE TITLE
@JsonIgnore does not work on property level after upgrading to Spring Boot 1.4.1

### ISSUE THREAD

**Issue by MichaelF25** [spring-projects/spring-boot#7182]
I've upgraded my application from Spring Boot 1.3.7 to Spring Boot 1.4.1. My application uses the `@JsonIgnore` annotation on property and method level in order to prevent these internal properties from being serialized for external views.

After upgrading to Spring Boot 1.4.1, `@JsonIgnore` only works on method level, but not on property level anymore. As a workaround I am using `@JsonIgnoreProperties` on class level which works as expected but is error prone since the property names have to be supplied as strings.

I've created a small demo project via Spring Boot Initialzr at https://github.com/MichaelF25/jsonignore-bug for demoing this issue. Just clone the repo and run the tests. There's a test in place which fails, because of ignored `@JsonIgnore` in `DemoEntity` class.

I am not sure if this is caused by jackson-core, jackson-annotation or maybe Spring Autoconfiguration for Jackson, therefore I am filing this one here.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem appears to be in Jackson. If I override the version to 2.6.7 (as used by Spring Boot 1.3.8) the sample's tests all pass.

**Comment by philwebb** [comment]
@MichaelF25 you can raise the issue with the Jackson team [here](https://github.com/FasterXML/jackson-core/issues).
