### ISSUE TITLE
Check that H2 console works out of the box when also using Spring Security

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7198]
http://stackoverflow.com/questions/40165915/why-does-the-h2-console-in-spring-boot-show-a-blank-screen-after-logging-in

**Comment by snicoll** [comment]
For the record, we have [this customization](https://github.com/snicoll-demos/cfp-example/blob/master/src/main/java/com/example/cfp/security/SecurityConfig.java#L39-L41) in a sample app.

**Comment by sashokbg** [comment]
Same problem here. I have .csrf().disable() and h2 console is white screen

**Comment by wilkinsona** [comment]
This is superseded by #10435.
