### ISSUE TITLE
Problem: Provide an option to disable spring-boot-gradle-plugin's dependency management?

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-boot#7199]
I have the spring boot gradle plugin 1.4.1.RELEASE configured inside an overlay project. This is where a war (that is already bootiful) is downloaded from maven archives and is then repackaged and massaged with additional dependencies. Effectively, all the overlay project needs is the ability to bootRun the project and not do anything else.

So I have:

```groovy
bootRepackage {
    enabled = false
}

springBoot  {
    mainClass = "org.springframework.boot.loader.WarLauncher"
}

bootRun {
    addResources = true
}
```

And this works "fine". 

The problem is that the war that is shipped as a dependency and downloaded by gradle has a bunch of dependencies inside it, which might interfere with spring-boot's dependency plugin applied automatically. For example, if the war ships with thymeleaf version 1, and boot's parent pom is set to enforce thymeleaf version 2, 2 is going to get applied automatically. There is no way to disable this behavior, other than putting a bunch of ext["xyz.version"] settings into the gradle overlay project to override versions enforced by the boot parent pom and stick to what the war may provide.

Could the plugin be massaged to disable that behavior optionally? I couldn't find a way to disable it in the documentation. In other words, is there a way to allow a project the choice of controlling its own dependencies? 

If you need an example, here it is: https://github.com/apereo/cas-gradle-overlay-template/tree/5.0

**Comment by wilkinsona** [comment]
Duplicates #3164

**Comment by mmoayyed** [comment]
Thank you for pointing me towards that other issue; However I am not sure (and don't think) that the #3164 addresses the problem described in this thread. Could you clarify please? or shall I take this to Stackoverflow?

**Comment by wilkinsona** [comment]
#3164 is requesting an option to disable dependency management when using Gradle. I believe you are asking for the same thing.

**Comment by mmoayyed** [comment]
Ah, excellent. Thanks. For some reason I got the impression that a fix is available by setting BOMs to bull or by adjusting the order of resolution strategies. Never mind :)
