### ISSUE TITLE
EntityManagerFactory is not getting created while upgrading from Spring boot 1.3.1 to 1.4.1

### ISSUE THREAD

**Issue by sangram210** [spring-projects/spring-boot#7200]
I am upgrading the project from spring boot 1.3.1 version to 1.4.1 version.After up gradation it is downloading hibernate 5.x version jars.So during start of the application "entityManagerFacory"  is not getting created and getting bean creation exceptions.
To avoid this issue I downgraded the hibernate version. 
Added ext['hibernate.version'] = '4.3.11.Final' in build.gradle file and works fine now.

**Comment by wilkinsona** [comment]
If you're using Spring Boot's auto-configuration, you'll still get an `EntityManagerFactory` been with 1.4.1 and Hibernate 5. There must be something special about your application.

If you'd like us to spend some time investigating, please spend some time preparing a sample project that illustrates the problem you're seeing.

**Comment by sangram210** [comment]
Hi @wilkinsona  Thanks for your quick reply.
Is this an issue with the new version spring boot(1.4.1)?

**Comment by snicoll** [comment]
@sangram210 Andy replied to that question already. It should work: if it does not for you and you want us to spend time investigating, please share a sample project that illustrates the problem you're seeing.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
