### ISSUE TITLE
ExceptionHandling NoHandlerFoundException doesn't work

### ISSUE THREAD

**Issue by Ozymandy** [spring-projects/spring-boot#7201]
I tried to configure own error page by handling NoHandlerFoundException using `ExceptionHandler`
```
@ControllerAdvice(basePackages` = {"org.tc.controllers"})
public class GlobalControllerAdvice {
    @ExceptionHandler({CourseNotFoundException.class,
            NumberFormatException.class})
    public ModelAndView unknownCourse(RuntimeException e) {
        //ModelAndView mav = new ModelAndView("classpath:views/unknown");
        //return mav;
        return new ModelAndView(new RedirectView("/unknown"));
    }
    @ExceptionHandler({NoHandlerFoundException.class})
    public ModelAndView handle404(Exception e) {
        return new ModelAndView(new RedirectView("/error"));
    }
}
```
I know, that dispatcher servlet doesn't throw NoHandlerFoundException by default, so I setThrowNoHandlerFound in application.properties. And now when I enter to, for example, page /qwerty I get whitelabel error page with `No handler found for GET /qwerty` and my page doesn't load. This request goes to `BasicErrorController`. What's going wrong? By the way exceptionHandler unknownCourse works clearly.

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the behaviour you're seeing?

**Comment by Ozymandy** [comment]
I found where is the trouble. I set `basePackages = {"org.tc.controllers"}` in `ControllerAdvice` when I delete this, it works, but why?

**Comment by wilkinsona** [comment]
Settings `basePackages` restricts the controllers to which your advice will apply to those that are in the back packages. When no handler is found there's no controller to match against so the base package restriction prevents your controller advice from applying.
