### ISSUE TITLE
Upgrade to liquibase 3.5.2 or later

### ISSUE THREAD

**Issue by SebastianDietrich** [spring-projects/spring-boot#7208]
Due to https://liquibase.jira.com/browse/CORE-2863 using liquibase includeAll directive does not work in spring-boot 1.4.0 or 1.4.1 (both using liquibase 3.5.1)

Please upgrade to liquibase 3.5.2 (09/2016) or 3.5.3 (10/2016).

**Comment by SebastianDietrich** [comment]
Thanks for the upgrade. Unfortunately this does not resolve https://liquibase.jira.com/browse/CORE-2863 (just for the records)

**Comment by philwebb** [comment]
Looks like the liquibase issue is waiting for more information and needs to be re-opened. We'll pick up any fix that they provide in the next round of dependency updates.
