### ISSUE TITLE
@AutoConfigureTestDatabase and Flyway don't work together as expected

### ISSUE THREAD

**Issue by Kernle32DLL** [spring-projects/spring-boot#7209]
Something I realized today, while I took a closer look at my tests. I'm using

```
@RunWith(SpringJUnit4ClassRunner.class)
@WebMvcTest(controllers = DatatableController.class, useDefaultFilters = false)
@AutoConfigureTestDatabase
```

That in itself works as expected. I can see auto configuration of the database that it set in my _application.properties_, it being replaced trough `@AutoConfigureTestDatabase`, and hibernate selecting the correct Dialect (e.g. `org.hibernate.dialect.H2Dialect`).

However, Flyway still uses the database config from _application.properties_. Reason being, that my _application.properties_ is set up as follows:

```
flyway.url=...
flyway.user=...
flyway.password=...

spring.datasource.url = ${flyway.url}
spring.datasource.username = ${flyway.user}
spring.datasource.password = ${flyway.password}
```

Looking at `FlywayAutoConfiguration` it is obvious what happens: The `flyway.*` properties take precedence over the overridden datasource.

While I can leave out the flyway.\* properties and set spring.datasource.\* directly (which makes the issue outlined above go away) I loose the ability to invoke mvn flyway:clean from the commandline, since it can't find any flyway config anymore:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building timeControl :: Module :: Model 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- flyway-maven-plugin:3.2.1:clean (default-cli) @ timecontrol.model ---
[INFO] Flyway 3.2.1 by Boxfuse
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.017 s
[INFO] Finished at: 2016-10-23T13:33:50+02:00
[INFO] Final Memory: 15M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:clean (default-cli) on project timecontrol.model: org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password! -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

So, possible solutions:

One could implement something like `AutoConfigureTestFlyway`, which invokes `AutoConfigureTestDatabase`, and uses a dependency injected datasource only (and overrides `FlywayAutoConfiguration`). Of course `AutoConfigureTestDatabase` could also bring its own flyway auto configuration. This might break other test scenarios tho I might imagine (depending on test expectations).

Another option could be to configure somewhere which properties (application.properties or injected datasource) take precedence. But this is probably counter intuitive, and implies wrong expectations (that this should be possible with all spring boot configs).

As a last resort I could always implement my own flyway configuration which ignores the flyway.\* properties, and only reacts to the datasource. But I would rather not.

Due to the nature of the problem, I cannot give a sample project.

**Comment by wilkinsona** [comment]
> Due to the nature of the problem, I cannot give a sample project

What is it about the problem that prevents you from providing a sample? Reading the description it sounds like it should be possible, so perhaps I've misunderstood. Can you please provide a sample or explain why you can't so that we can be sure we're looking at the same problem as you are describing.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
