### ISSUE TITLE
Kotlin Tests using @AutoConfigureMockMvc don't reuse ApplicationContext between test classes

### ISSUE THREAD

**Issue by kpdonn** [spring-projects/spring-boot#7210]
When using Spring Boot 1.4.1 with Kotlin 1.0.4, I'm running into an issue where tests using @AutoConfigureMockMvc result in the application context being recreated between each class instead of being reused as expected. 

I'm not sure what the cause is but it appears to be related to Kotlin in some way because I was unable to reproduce the issue using a pure Java project.

I have a minimal project reproducing the issue which I'll add to this issue shortly.

**Comment by snicoll** [comment]
Duplicates #7101
