### ISSUE TITLE
Upgrade to Janino 3.0.6

### ISSUE THREAD

**Issue by seanmmills** [spring-projects/spring-boot#7218]
Please update Janino to 3.0.6 to take advantage of latest bug fixes/enhancements in [changelog](http://janino-compiler.github.io/janino/changelog.html).

**Comment by wilkinsona** [comment]
The version of Janino in our dependency management is aligned with the version that's used by Logback. Logback 1.1.7 uses Janino 2.7.8 so our dependency management needs to stay as it is.

You can always override the managed version using the `janino.version` property if you wish.
