### ISSUE TITLE
Tighten up PropertiesLauncher's contract

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7221]
Fixing #7178 has shown that `PropertiesLauncher` is rather under specified. As a result the behaviour can be unpredictable and the documentation is misleading in places.

Some known problems (there may well be others):
1. Properties are loaded from `application.properties` but all of the locations supported by normal `application.properties` loading are not supported.
2. A `classpath:` config file location is supported, but it doesn't take into account `loader.path` which can customise the class path. 
3.  `loader.home` is described as "the directory location of an additional properties file" but it actually appears to be used purely to make relative paths absolute and to find a `META-INF/MANIFEST.MF` from an exploded archive
4. Placeholder replacement is described as being done from "System and environment variables plus the properties file itself on all values before use", however it's a bit more complicated than that. For example, the properties file is not used when resolving placeholders in system properties
5. No property placeholder resolution is performed for properties read from a manifest
6. The properties that can be customised using manifest entries seem rather arbitrary. For example `loader.config.name` and `loader.config.location` cannot be customised in this way.
7. The order of precedence for the various property locations isn't documented

Some proposed changes:
1. Don't use `application.properties` and look for `loader.properties` instead. This avoids setting the false expectation that normal `application.properties` behaviour will be available.
2. There's a chicken and egg problem here. If `loader.path` is used to configure possible locations for `loader.properties` then `loader.properties` can no longer configure `loader.path`. We probably just need to document the restriction.
3. I'm not sure what the "additional properties file" is supposed to be and I can't find any sign of it in the implementation or the tests. We should probably update its description.
4. Not sure yet
5. Perform placeholder replacement on values read from manifests
6. Expand the list of properties that can be configured in the manifest to cover all that make sense.
7. Document the order: Environment variables -> System properties -> loader.properties -> exploded manifest -> jar manifest

**Comment by dsyer** [comment]
I was poking around in there today. I noticed that `FilteredArchive` appears to be redundant (I deleted it and returned just the list of filtered archives from the method it was used instead, and all tests are green).
