### ISSUE TITLE
UserInfoTokenServices ignores OAuth2 scopes resulting in  @PreAuthorize("#oauth2.hasScope('xxx')") failures

### ISSUE THREAD

**Issue by paulnuk** [spring-projects/spring-boot#7222]
This issue is described [in detail here ](http://stackoverflow.com/questions/36777188/getting-insufficient-scope-for-this-resource-using-spring-boot-and-oauth2/40238544#40238544)

UserInfoTokenServices.extractAuthentication does not extract the authorised scopes the user has, and instead sets them to be null when creating a new OAuth2Request, which means that any PreAuthorize annotation that checks for scopes will always come back with insufficient_scope errors regardless of the actual authorised scopes.

**Comment by wilkinsona** [comment]
Duplicates #5096.
