### ISSUE TITLE
Allow using @AutoConfigureRestDocs with the restassured support of spring rest docs

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#7228]
I would like to be able to use `@AutoConfigureRestDocs` with the restassured support of Spring REST docs.

See also http://stackoverflow.com/questions/40259447/is-it-possible-to-use-autoconfigurerestdocs-with-restassured-instead-of-mockmvc

**Comment by wilkinsona** [comment]
If we decide to do this, I think we should wait for https://github.com/spring-projects/spring-restdocs/issues/262 so that Boot doesn't have to worry about two different versions of REST Assured.

**Comment by binkley** [comment]
You may consider this a separate issue.  When using spring-restdocs-mockmvc 1.1.2 against spring 5.0.0.M3 and spring-boot-starter-parent 1.4.2, I get a `NoSuchMethodError`.  It looks like `MediaType` has changed between Spring major versions

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.06 sec <<< FAILURE! - in hm.binkley.labs.ApplicationTest
shouldRespondCheerfully()  Time elapsed: 0.125 sec  <<< FAILURE!
java.lang.NoSuchMethodError: org.springframework.http.MediaType.getCharSet()Ljava/nio/charset/Charset;
        at hm.binkley.labs.ApplicationTest.shouldRespondCheerfully(ApplicationTest.kt:25)
```

**Comment by snicoll** [comment]
@binkley that `MediaType` call has already been fixed in RestDocs `1.2.x` (that's in restdocs by the way, not Spring Boot).

**Comment by dsyer** [comment]
The issue in RESTdocs is marked as fixed (I think that's in 1.2.0). Time to dust this one off?

**Comment by eddumelendez** [comment]
Currently there is one way to use `restassured` and it works perfectly fine. I found this meanwhile I was working with the current `spring-restdocs-restassured` dependency in this issue.

Add the dependency below:

```xml
<dependency>
	<groupId>io.rest-assured</groupId>
	<artifactId>spring-mock-mvc</artifactId>
	<version>3.0.2</version>
	<scope>test</scope>
</dependency>
```

Create test

```java
@RunWith(SpringRunner.class)
@WebMvcTest
@AutoConfigureRestDocs("target/generated-snippets")
public class GreetingDocumentationTest {

	@Autowired
	private MockMvc mockMvc;

	@Autowired
	private RestDocumentationResultHandler documentationHandler;

	@Test
	public void testHelloEndpoint() {
		given().mockMvc(this.mockMvc)
				.when()
				.get("/hello")
				.then()
				.apply(this.documentationHandler.document(
						responseFields(
								fieldWithPath("message").description("message from service"))));
	}

	@TestConfiguration
	static class ResultHandlerConfiguration {

		@Bean
		public RestDocumentationResultHandler restDocumentation() {
			return document("{method-name}");
		}

	}

}
```

**Comment by wilkinsona** [comment]
That's an excellent suggestion. Thank you, @eddumelendez. I regularly forget about REST Assured's `MockMvc` integration.

I think it may well still be worth also providing support for RestAssured making HTTP actual HTTP calls to the service that's being documented. @dsyer and @wimdeblauwe, do your uses cases require full-blown HTTP calls, or would using the RestAssured API on top of MockMvc give you what you want?

**Comment by dsyer** [comment]
In my case it has to be HTTP because the app is not MVC.

**Comment by philwebb** [comment]
Closing in favor of PR #9643
