### ISSUE TITLE
spring.test.database.replace property ignored

### ISSUE THREAD

**Issue by snowe2010** [spring-projects/spring-boot#7229]
Looking at the annotation `AutoConfigureTestDatabase`, I should be able to use the property `spring.test.database.replace` to avoid annotation based configuration for all of my tests (we are using custom postgres dialect and can't get hsqldb to work). Attempting to use this property does not work though. I will attempt to create a project showing the problem later.

**Comment by wilkinsona** [comment]
> Looking at the annotation `AutoConfigureTestDatabase`, I should be able to use the property `spring.test.database.replace` to avoid annotation based configuration for all of my tests

What did you see that caused you to draw that conclusion?

The `@PropertyMapping` annotation controls the mapping of annotation attributes into a `PropertySource`. This `PropertySource` is added in first place, thereby taking precedence over other  sources. This means that your `spring.test.database.replace` property is very unlikely to have any effect unless you're customising the environment with another property source and positioning it before the annotations-based property source.

**Comment by snowe2010** [comment]
Ah I was also getting some information from here, http://www.devthoughts.pl/2016/08/02/datajpatest-from-spring-boot/, but I guess that's wrong then. Is there any way to avoid the annotation based config? I'd rather not have to put an annotation on every test and instead use a property.

**Comment by philwebb** [comment]
There isn't currently a way to do this. I think it should be possible to create your own meta-annotation if that helps. Something like:

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@DataJpaTest
@AutoConfigureTestDatabase(replace=Replace.NONE_
public @interface MyDataJpaTest {
}
```

Doing something like we did for `@AutoConfigureMockMvc` might be a nice enhancement here. See #6455

**Comment by snowe2010** [comment]
Ah, darn, I thought that might be the only way. Ok, well thank you for the help then.

**Comment by snicoll** [comment]
Closing in favour of PR #7560
