### ISSUE TITLE
Possibility to set cache implementation by cache name via springboot properties

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-projects/spring-boot#7235]
I just explain my use case to use some cache with a implementation (and potentially a with some args) and some with another cache implementation

I configure some caches via in my spring-boot microservice.
Some are server side, some are client side via interface designed with feign/spring-cloud annotation and @Cacheable
For server side, I want always to use cache.
For client side, depending of my microservice, I want to activate or not some caches, for instance, on a spring-batch microservice I want to cache. Just for information, my different interface of my feign client with @Cacheable are shared between the different microservices via client jar of my microservice.

So my configuration in spring should be in some case like
```java
    @Bean
    public CacheManager cacheManager() {

        final SimpleCacheManager cacheManager = new SimpleCacheManager();
        cacheManager.setCaches(Arrays.asList(
                new NoOpCacheManager.NoOpCache("bar"),
                new ConcurrentMapCache("foo")));
        return cacheManager;
    }
```

I should be great to have something like (or closed) in springboot just via properties : 

My prefer one (because best configurable).
```
spring.caches[0].cache-names=bar

spring.caches[0].noopcache.spec=

spring.caches[1].cache-names=foo

spring.caches[1].caffeine.spec=maximumSize=500,expireAfterAccess=600s
```

or something like (need to repeat n times if you have n cache with the same)
```
spring.cache.cache-names=foo,bar

spring.cache.foo.caffeine.spec=maximumSize=500,expireAfterAccess=600s

spring.cache.bar.noopcache.spec=
```

or else configuration if you have better idea (don't hesitate)

noopcache is for NoOpCache explained in https://jira.spring.io/browse/SPR-14856

**Comment by snicoll** [comment]
That's programming by properties and I am not keen on doing that. Do you know that you can just expose individual caches as `@Bean`s and Spring Boot will automatically detect that and create a `CacheManager` for you?

Taking your example, that looks like:

```java
public NoOpCache barCache() { return new NoOpCache("bar"); }
public GuavaCache fooCache() { return new ... (); }
```

**Comment by alexandrenavarro** [comment]
I didn't know you can individual caches as @Beans and Spring Boot will automatically detect that and create a CacheManager. I understand your point with your comment and I agree with you. You can close my issue. Sorry for time I took you and thanks for adding NoOpsCache https://jira.spring.io/browse/SPR-14856
