### ISSUE TITLE
Debug output appearing during Groovy compilation

### ISSUE THREAD

**Issue by graemerocher** [spring-projects/spring-boot#724]
If you run 'gradle bootRun' with https://spring.io/guides/gs/accessing-data-gorm/

You will get a lot of debug output. The debug statements are coming from Grails' AST transforms, but boot shouldn't output these by default surely? Something the gradle Spring Boot plugin can configure?

**Comment by wilkinsona** [comment]
For the reasons described above, we think this should be fixed outside of Boot as the problems are not Boot specific
