### ISSUE TITLE
spring-aop does not proxy the beans annotated with spring-boot-test @MockBean 

### ISSUE THREAD

**Issue by andrewkandzuba** [spring-projects/spring-boot#7243]
Hello,

I've recently upgraded to 'spring-boot-starter-parent 1.4.1.RELEASE`. 
The upgrade has led to the issue with a compatibility between 'spring-boot-test' and 'spring-aop' components. 

I have a test with an instance of my custom service interface annotated with @MockBean. 

`...
    @MockBean
    private SmsService smsService;
...`

I also have an aspect class (annotated with @Aspect) which intercepts that service methods for logging and validation purposes. Since the upgrade from 'spring-boot-starter-parent 1.4.0.RELEASE`to 'spring-boot-starter-parent 1.4.1.RELEASE` the mocked service's instance has stopped been processed and proxied. 

I've made some debug and code analysis and seemed the issue is caused by refactoring of `org.springframework.boot.test.mock.mockito.MockitoPostProcessor`.  The **registerMock(ConfigurableListableBeanFactory beanFactory, BeanDefinitionRegistry registry, MockDefinition definition, Field field)** pushes mocked bean into singletons set and this action later prevents the instance from been extended by AOP. 

Please see reproduction of the error here: https://github.com/andrewkandzuba/spring-boot-test-mockbean-aop

**Comment by wilkinsona** [comment]
It's intentional that mocked beans are not proxied. See [this commit](https://github.com/spring-projects/spring-boot/commit/0e00a49dcc246893fcaf1c7a0497fac6dcbc7454#diff-9e24ce8382525ea4998e7f58a26cc81b) and the issues to which it links for the reasoning.

You haven't really described the problem that you're facing. Why do you care that your aspect is being called when you've replaced the service with a mock?

**Comment by andrewkandzuba** [comment]
In the beginning of the report I mentioned it works prior to the 1.4.1.RELEASE and even though it might be intentional the clear explanation of how-to make it works again having [these changes](https://github.com/spring-projects/spring-boot/commit/0e00a49dcc246893fcaf1c7a0497fac6dcbc7454#diff-9e24ce8382525ea4998e7f58a26cc81b) is still required. 

So far I see the only option to make it viable and it is about the instantiation of a "real" bean followed by playing with its content depending on the certain test scenario. However obviously it is absolutely the case Mockito have been invented for.  

Any other adviсe?

**Comment by wilkinsona** [comment]
> Any other advice?

Yes. Create your own mock and expose it as a bean as you would have done before `@MockBean` was introduced.

**Comment by andrewkandzuba** [comment]
That is what I've just meant and it wouldn't be so elegant as with `@MockBean`, you know )

**Comment by wilkinsona** [comment]
Unfortunately, I can't think of a way to satisfy all of the use cases. Yours is very much an edge case, particularly as you haven't described why you care that your aspect is not being called, so keeping the fix in place for the others takes priority.

The best that I can think of is to add an attribute to `@MockBean` that lets you control how the mock is registered, but that feels like exposing complexity to everyone that's only of interest to a few.

**Comment by andrewkandzuba** [comment]
The reason is clearly defined in the project I've pointed in the beginning of the thread. It is about an ability to test's cover an AOP based validation. Anyway, from what I've learned after AOP bean enhancement code's review the issue had been caused by the change from **default (prototype)** to **singleton** of "mocked bean" scope. Might it be a solution to support `bean-scope` (or just `scope`) attribute per `@MockBean` annotation?

**Comment by wilkinsona** [comment]
> Might it be a solution to support bean-scope (or just scope) attribute per @MockBean annotation?

This is basically what I was considering above when I said "that feels like exposing complexity to everyone that's only of interest to a few". The rest of the team share the same feeling. If the behaviour of `@MockBean` doesn't suit your unusual needs, then please create your own mock and expose it as a bean as you would have done in the past.
