### ISSUE TITLE
Add @Inherited to @AutoConfigureTestDatabase

### ISSUE THREAD

**Issue by sebastiankirsch** [spring-projects/spring-boot#7245]
Is there any reason why `AutoConfigureTestDatabase` is not inherited?
We like to define an abstract class with which to set up jpa tests, but with `@Inherited` missing, we need to add it in all child classes...

**Comment by wilkinsona** [comment]
> Is there any reason why AutoConfigureTestDatabase is not inherited?

I can't think of one.

None of the `@AutoConfigure…` annotations are `@Inherited`, but `@SpringBootTest`, `@WebMvcTest`, `@DataJpaTest` etc all are. I suspect that's just an oversight.

**Comment by snicoll** [comment]
Duplicate in favour of the PR #7326
