### ISSUE TITLE
Migrating from version 1.4.0 to 1.4.1

### ISSUE THREAD

**Issue by Damore** [spring-projects/spring-boot#7258]
[This](http://stackoverflow.com/questions/40283365/spring-boot-oauth2-not-working-properly-on-version-1-4-1) question is related to [this](https://github.com/silvanopessoa/bug-spring) repository.

In a nutshell, after migrating from version1.4.0 to 1.4.1 the spring security oauth2 is not working when requesting a token. The return is always "Bad client credentials".

**Comment by wilkinsona** [comment]
@Damore Thanks for the sample project, unfortunately it's not clear how to use it to recreate the problem as it's rather complex. (It also didn't compile till I added a dependency on Commons Lang 3).

If you'd like us to spend some time investigating, can you please spend some time producing a minimal sample and describing the steps to take to reproduce the problem.

**Comment by Damore** [comment]
@wilkinsona Thanks for your quick reply. I will add here what steps you should take to reproduce the problem:

1) Clone the sample project https://github.com/silvanopessoa/bug-spring.git

2) On Eclipse IDE import the project as an existing maven project

3) Install mongodb

4) Execute the below script on mongodb shell : 

`use autenticacao_dev

db.customClientDetails.insert(
{
    "_id" : "0",
    "enabled" : true,
    "scope" : [ 
        "read", 
        "write"
    ],
    "authorizedGrantTypes" : [ 
        "password", 
        "refresh_token", 
        "client_credentials"
    ],
    "clientSecret" : "$2a$10$QMoKwt2Wf0M11ne30ISVRehTQbxzdG0D7Z/b2yRxUmtkd39c0dgom",
    "refreshTokenValiditySeconds" : 900,
    "secretRequired" : true,
    "accessTokenValiditySeconds" : 500,
    "_class" : "customClientDetails",
    "resourceIds" : [],
    "authorities" : [ 
        {
            "_class" : "org.springframework.security.core.authority.SimpleGrantedAuthority",
            "role" : "ROLE_CLIENT"
        }, 
        {
            "_class" : "org.springframework.security.core.authority.SimpleGrantedAuthority",
            "role" : "ROLE_TRUSTED_CLIENT"
        }
    ],
    "name" : "autenticacao",
    "scoped" : true,
    "registeredRedirectUri" : []
})`

5) Install Postman and create a request with the following attributes:

# method: 
POST
# url: 
localhost:8080/oauth/token
# Header: 
{
Content-Type : application/x-www-form-urlencoded
}

# Body: 
{
client_id : 0
client_secret : 0b0feafc-a241-4e70-b107-62022e68acfa
grant_type : client_credentials
}

Below follows 2 links that shows the error happening on version 1.4.1 and working normally on version 1.4.0

[Version 1.4.1](https://drive.google.com/file/d/0B_I3gr3pfTVmM0ZHano5Z25kbG8/view?usp=sharing)
[Version 1.4.0](https://drive.google.com/file/d/0B_I3gr3pfTVmZ2stSUFLRnRNN2s/view?usp=sharing)

**Comment by wilkinsona** [comment]
Thanks for the more detailed instructions. It's not exactly minimal, but I was able to reproduce the problem.

It appears to be due to a change in Spring Security OAuth. Spring Boot 1.4.1 uses Spring Security OAuth 2.0.11, whereas Spring Boot 1.4.0 uses Spring Security 2.0.10. The request works with Spring Boot 1.4.1 if I override Spring Security OAuth's version to 2.0.10:

```diff
diff --git a/autenticacao/pom.xml b/autenticacao/pom.xml
index d009448..69e2975 100644
--- a/autenticacao/pom.xml
+++ b/autenticacao/pom.xml
@@ -15,6 +15,10 @@
                <version>1.4.1.RELEASE</version>
        </parent>

+       <properties>
+               <spring-security-oauth.version>2.0.10.RELEASE</spring-security-oauth.version>
+       </properties>
+
        <dependencyManagement>
                <dependencies>
                        <dependency>
```

I think we need to get the Spring Security OAuth team to take a look. I was going to suggest that you open a Spring Security OAuth issue, but it looks like someone else already has: https://github.com/spring-projects/spring-security-oauth/issues/896. Let's use that issue to track the problem for now.

**Comment by wilkinsona** [comment]
@Damore Now I look more closely, I can see that it was you that opened the other issue as well. Please don't deliberately report the same problem in two places as it just wastes peoples' time.

**Comment by Damore** [comment]
@wilkinsona Ok. So, What should I do? Just wait for the team of spring oauth security take a look at the problem?
