### ISSUE TITLE
Make is easier to use TestRestTemplate with a custom ResponseErrorHandler

### ISSUE THREAD

**Issue by MateuszRasinski** [spring-projects/spring-boot#7265]
Custom error handler set using `RestTemplateBuilder` bean or using the configuration `TestRestTemplateConfiguration` from [Spring Boot Reference Guide](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-with-spock) is overriden by `TestRestTemplate.NoOpResponseErrorHandler`.

Specifically, when using the following class:
````
class CustomResponseErrorHandler extends DefaultResponseErrorHandler {
    // implementation
}
````
in the configuration of the builder:
````
ResponseErrorHandler customErrorHandler = new CustomResponseErrorHandler();
RestTemplateBuilder builder = builderProvider.getIfAvailable()
                                             .errorHandler(customErrorHandler);
````
The following line is false:
````
new TestRestTemplate(builder.build()).getRestTemplate().getErrorHandler().equals(customErrorHandler)
````

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#7266).

**Comment by dallasvaughan** [comment]
Just a note about this: I discovered this issue when I called the method `TestRestTemplate.withBasicAuth(String username, String password)`. 

Inside that method is the call:

```
restTemplate.setErrorHandler(getRestTemplate().getErrorHandler());
```

But then later in the method the `TestRestTemplate` constructor is called which then (re-)sets the just-set `ResponseErrorHandler` back to `NoOpResponseErrorHandler`.

This logic, along with the description in the javadoc for this method (`Creates a new {@code TestRestTemplate} with the same configuration as this one`), implies that the RestTemplate config should be the same as it was coming in, but it sets it to `NoOpResponseErrorHandler` regardless of the previous state.

**Comment by philwebb** [comment]
Thanks @dallasvaughan, I've raised https://github.com/spring-projects/spring-boot/issues/7441 to fix this.

**Comment by bclozel** [comment]
We've discussed this during a team call and we've come to the conclusion that the `NoOpResponseErrorHandler` is part of the core contract behind `TestRestTemplate`.

`TestRestTemplate` is about testing server behavior, looking at the HTTP responses coming out of the server no matter what the response status is. So developers should always test the responses with assertions and not test for thrown exceptions.

We understand that developers are tempted to use `TestRestTemplate` as a shortcut to get a `RestTemplate` already bound to the test server, but we don't think this use case is really the goal here. Instead, developers should get injected with a `RestTemplateBuilder` and get the `@LocalServerPort` information to build a client instance if they wish to test the behavior of `RestTemplate` against the application.

**Comment by tkruse** [comment]
@bclozel : so how to make assertions on the result of `put()`, given that `TestRestTemplate.put()` just returns `void`? As an example, how to distinguish a 200 from a 404 error response in tests with that API?

**Comment by bclozel** [comment]
@tkruse you can use the `exchange` method and specify the PUT method.

**Comment by cs94njw** [comment]
TestRestTemplate doesn't actually offer what @bclozel describes.
I am writing my unit tests, using TestRestTemplate with a ResponseType of "UUID".
When I test BAD_REQUEST errors from my service, instead of my being able to inspect the ResponseEntity and check for status "401", TestRestTemplate throws an exception saying it can't decode the error message as a UUID.
I don't understand why TestRestTemplate is even attempting to decode the ResponseType when a 4xx error is returned.

**Comment by bclozel** [comment]
@cs94njw I don't understand how this is related. This looks like a different problem?
Could you report that separately with a sample project (something we can git clone or download) we can take a look at?
