### ISSUE TITLE
addResourceHandler for text files

### ISSUE THREAD

**Issue by CallMeXYZ** [spring-projects/spring-boot#7273]
it seems that spring doesn't support `/*.text` resource mapping pattern.
```java
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
//        this doesn't work
        if (!registry.hasMappingForPattern("/*.text")) {
            registry.addResourceHandler("/*.text").addResourceLocations("/static/text/");
        }
//        works like a charm
        if (!registry.hasMappingForPattern("/*.js")) {
            registry.addResourceHandler("/*.js").addResourceLocations("/static/js/");
        }
       /* if (!registry.hasMappingForPattern("/js*//**")) {
         registry.addResourceHandler("/js*//**").addResourceLocations("/static/js/");
         }
         if (!registry.hasMappingForPattern("/img*//**")) {
         registry.addResourceHandler("/img*//**").addResourceLocations("/static/img/");
         }*/
    }

```

**Comment by wilkinsona** [comment]
Neither mapping works for me, and I'm not sure I'd expect them to. Both of these mappings do work:

```java
registry.addResourceHandler("/*.text").addResourceLocations("classpath:/static/text/");
registry.addResourceHandler("/*.js").addResourceLocations("classpath:/static/js/");
```

If this doesn't solve your problem, please provide a small sample that illustrates the behaviour you've described above and we can take another look.

**Comment by CallMeXYZ** [comment]
Under your config,the static files are put under `src/main/resources/` and everything goes well.

**Comment by philwebb** [comment]
@CallMeXYZ are you creating a `war` file? You can't use `src/main/webapp/` if you're generating a jar.

**Comment by CallMeXYZ** [comment]
I deploy the `war` file on Tomcat,and the files under `src/main/webapp/` are under my root project folder.And come back to my question, `js`,`css`,`imgs`(png etc.) are accessible under  `src/main/webapp/` while `text` are not when using `addResourceHandler("/*.js")`, `addResourceHandler("/*.css")`,`addResourceHandler("/*.text")`
