### ISSUE TITLE
[spring-boot-gradle-plugin] Add support for environments in gradle

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#7274]
We have 3 properties file
> application.properties
> application-local.properties
> application-dev.properties

application.properties
`spring.profiles.active=@environment@`

build.gradle
```
if (! hasProperty("environment")) {
    ext.environment = "local"
}

processResources {
    exclude {
        it.file.name ==~ Pattern.compile("application-((?!$environment).)*\\.properties")
    }
    filter(ReplaceTokens, tokens: [environment: environment])
}
```

> ./gradlew -Penvironment=dev run

Please add something similar to this in plugin.

**Comment by wilkinsona** [comment]
Duplicates #1176.
