### ISSUE TITLE
Metrics report 500s for client disconnects

### ISSUE THREAD

**Issue by ericdahl-shutterfly** [spring-projects/spring-boot#7277]
When a client prematurely disconnects, the actuator metric endpoint reports the request as a 500 error, even if the response was 200. Our APIs that are consumed by mobile devices with spotty connections often have client disconnects, resulting in 500 metrics, causing us to be alarmed, only to find that they were not errors. Ideally, if client disconnects prior to downloading the entire payload, the actual response code provided should be recorded appropriately in the metrics, if possible (the status code should be first part of HTTP response?).

(Side note: logback-access logs show nothing for this case with jetty, but show an entry for tomcat)

*Steps to reproduce*
1. `git clone https://github.com/ericdahl/spring-boot-500s-disconnects.git`
2. `cd spring-boot-500s-disconnects`
2. `mvn spring-boot:run`
3. `curl -v --limit-rate 100 http://localhost:8080`
    - Note: this shows a 200 success response
4. `^C`
5. `curl 'http://localhost:8080/metrics/counter.status.*.root' ; echo`

Expected: no 500 errors -- preferably the actual response code if it was sent
Actual: 500 errors

<img width="1326" alt="screen shot 2016-11-02 at 7 40 16 pm" src="https://cloud.githubusercontent.com/assets/17730942/19954283/36954b26-a134-11e6-9d32-7c903ee77f61.png">

**Comment by wilkinsona** [comment]
@ericdahl-shutterfly Thanks for the sample and precise description of the problem
