### ISSUE TITLE
Provide auto-configuration for Reactor 3.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7302]
I'm not sure what, if any, auto-configuration we should have for Reactor 3.0 now that Reactor Spring is no more and all of the reactive stuff is in Spring Framework itself.

What we did have for Reactor 2.0 will be removed as part of #7301.

**Comment by bclozel** [comment]
We could provide properties that enable operator hooks on reactor core. Here's an example that enables operator stacktrace (very resource consuming):

`Hooks.onOperator(h -> h.operatorStacktrace());`

Note that this hook should be configured automatically when devtools is enabled.
