### ISSUE TITLE
enablescheduling annotation in MetricExportAutoConfiguration.java

### ISSUE THREAD

**Issue by running2** [spring-projects/spring-boot#7307]
Is there a way to disable enablescheduling annotation in MetricExportAutoConfiguration.java. When using spring actuator, if the project itself have some control on enablescheduling annotation, it would be useless.

**Comment by wilkinsona** [comment]
Is it causing a problem? Declaring the annotation more than once shouldn't make any difference.

**Comment by running2** [comment]
Since currently in the project the scheduler is only enabled under some profiles. When enable actuator, we are not able to do it.

________________________________
发件人: Andy Wilkinson <notifications@github.com>
发送时间: 2016年11月4日 16:45:10
收件人: spring-projects/spring-boot
抄送: running2; Author
主题: Re: [spring-projects/spring-boot] enablescheduling annotation in MetricExportAutoConfiguration.java (#7307)


Is it causing a problem? Declaring the annotation more than once shouldn't make any difference.

―

**Comment by snicoll** [comment]
Try to set `spring.metrics.export.enabled=false` for the cases where you don't want the scheduler to be active then.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
