### ISSUE TITLE
spring boot throw OutOfMemoryError:PermGen space when using velocity-tools

### ISSUE THREAD

**Issue by aftersss** [spring-projects/spring-boot#7309]
when using spring-boot, it throw OutOfMemoryError:PermGen space. the stacktrace is like:

```
java.lang.OutOfMemoryError: PermGen space
  at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:219)
  at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
  at org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityToolboxView.getToolboxConfigFileAwareServletContext(EmbeddedVelocityToolboxView.java:73) 
  ...
```

I read the source code at EmbeddedVelocityToolboxView.getToolboxConfigFileAwareServletContext:

    private ServletContext getToolboxConfigFileAwareServletContext() {
        ProxyFactory factory = new ProxyFactory();
        factory.setTarget(getServletContext());
        factory.addAdvice(new GetResourceMethodInterceptor(getToolboxConfigLocation()));
        return (ServletContext) factory.getProxy(getClass().getClassLoader());
    }
after debugged it, I found that every time spring-boot generate a velocity view, this method will be called, and a new java class will be created. so after a few minutes, it will throw OutOfMemoryError:PermGen space.

This appears to be a bug in spring boot.

**Comment by wilkinsona** [comment]
I can't recreate this. As far as I can tell, the same proxy class is returned each time `factory.getProxy(getClass().getClassLoader())` is called.

@aftersss If you'd like us to investigate further, can you please provide a small sample that reproduces the problem.

**Comment by aftersss** [comment]
I think you are right, but I can't recreate this now, If I do so, I will open this issue again,Thanks.
