### ISSUE TITLE
Auto-configure a Cassandra QueryLogger

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#7312]
See [Logging query latencies](https://github.com/datastax/java-driver/tree/2.1/manual/logging#logging-query-latencies).

It would be great if this feature were available out of the box, with some tuning/configuration via application properties.

**Comment by philwebb** [comment]
Perhaps a callback `ClusterCustomizer` interface might be more generally useful?

**Comment by snicoll** [comment]
Closing in favour of the PR #7320

**Comment by hartmut-co-uk** [comment]
if anyone still needs the query logger just add as a Bean and get the `Cluster` Autowired in:

```
@Bean
public QueryLogger queryLogger(Cluster cluster) {
    QueryLogger queryLogger = QueryLogger.builder()
            .build();
    cluster.register(queryLogger);
    return queryLogger;
}
```
(& obviously configure `QueryLogger.Builder` as required).

Don't forget to set log levels to _DEBUG_/_TRACE_ in your `application.yml`:
```
logging.level.com.datastax.driver.core.QueryLogger.NORMAL: DEBUG
logging.level.com.datastax.driver.core.QueryLogger.SLOW: TRACE
```

Voilà!
