### ISSUE TITLE
Support a user property for skipping the Maven run/start/stop goals

### ISSUE THREAD

**Issue by mjustin** [spring-projects/spring-boot#7313]
Issue #4922 provided a mechanism for skipping the run/start/stop goals from within the project itself.  However, it is often useful to arbitrarily tell an existing build to skip running those, ideally without having to manually bake them into every project that wants to provide this functionality.

The scenarios I've personally had is that I have Cucumber functional tests which execute during the functional-test step of the Maven lifecycle. Therefore, I run the spring-boot:start goal during my pre-integration-test phase, and spring-boot:stop goal during my post-integration-test phase.

However, I sometimes want to skip spinning up and tearing down the server. For instance, if I'm skipping tests, I would like to be able to tell Maven not to spin up the Spring Boot server. The other scenario I've run across is when there's some issue with starting up the app due to local issues (perhaps it could be due to a CI server not having all the infrastructure needed to starting up the app, or something weird with my local network), but I still want to run the "verify" Maven goal.

Other similar Maven goals by other parties typically provide such a property:
* [tomcat7:run](http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/run-mojo.html) - maven.tomcat.skip
* [cargo:run](https://codehaus-cargo.github.io/cargo/Maven2+Plugin+Reference+Guide.html) - cargo.maven.skip
* [jetty:run](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html) - jetty.skip

My request therefore is for a user property (perhaps named something like "maven.spring-boot.skip") that can be passed in at the command line to skip starting (and stopping!) the Spring Boot app.  This should apply to both the run/start, *and* the stop goals, so that no failure occurs if the start is skipped but the stop doesn't find a running process to stop.  The usage would be something like the following:

`mvn verify -Dmaven.spring-boot.skip`

**Comment by snicoll** [comment]
This is really about adding a `property` tag in `@Parameter(defaultValue = "false")` for the `skip` property.

Unfortunately, I can see that we haven't really used a unique prefix for our property so far (i.e. `useTestClasspath`) 😞 

I think I'd go with `spring-boot.skip`
