### ISSUE TITLE
devtools are NOT automatically disabled when running a fully packaged application.

### ISSUE THREAD

**Issue by kazuki-ma** [spring-projects/spring-boot#7328]
According to document, spring-boot-devtools are automatically disabled in fully packaged application. **But NOT.**

http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html
> Developer tools are automatically disabled when running a fully packaged application. If your application is launched using java -jar or if it’s started using a special classloader, then it is considered a “production application”.

Environment
----
```
org.springframework.boot:spring-boot-devtools:1.4.1.RELEASE
org.springframework.boot:spring-boot-starter-thymeleaf:1.4.1.RELEASE
```

Reproduce
----
I created a sample project.

Please checkout https://github.com/kazuki-ma/devtools-report.
and run `./gradlew clean assemble && java -jar ./build/libs/devtools-report-1.0-SNAPSHOT.jar`

This sample contains [a single bean](https://github.com/kazuki-ma/devtools-report/blob/master/src/main/java/myapp/Application.java) annotated `@SpringBootApplication` and has one method annotated `@PostConstruct`. In the method, just output `spring.thymeleaf.cache`'s value and `exit(0)` . 

After running assembled jar, we will see

```
spring.thymeleaf.cache = false
```

will be logged.
Expected is

```
spring.thymeleaf.cache = NOT_SET
```

Other
----
If I exclude spring-boot-devtools from fat jar by adding

```
springBoot {
    excludeDevtools = true
}
```

into `build.gradle`. `spring.thymeleaf.cache = NOT_SET` is logged as expected.

**Comment by snicoll** [comment]
Duplicates #7014

**Comment by kazuki-ma** [comment]
Thanks! We need fix documentation of `excludeDevtools = true` is default.

**Comment by snicoll** [comment]
It's already done.
