### ISSUE TITLE
`Restarter` could support multiple root contexts 

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-boot#7335]
`Restarter` currently assumes that during a load/reload process there will be a single root context created by the application. If multiple contexts are created, it will overwrite the stored `rootContext`. Unfortunately, this also means that if at any time there are multiple root contexts being created as part of the application (for example, managed by it), only one of them will be closed on restart. 

This leads to a particular issue noticed when combining Spring Cloud Stream, Spring Cloud Config and devtools, where restart fails because JMX beans are not unregistered. This can be further traced down to an application context that's not closed properly.  

Here's the (longer) excerpt from Slack:

> For one thing devtools assumes that during load/reload there will be one and only one root context created - otherwise, the rootContext property will be overwritten every time a new root context is created. On the other hand, SCSt creates a context for each binder instance - so that we could target multiple systems. All good so far, as the binder context will be created as a child of the ‘main’ application context. Throw Cloud Config into the mix, and BootstrapApplicationListener creates an additional context for the child - which eventually gets dropped since the binder context already has a parent, but throws off Devtools which ends up making the close() call on the wrong context - which results in a few things, including skipping JMX deregistration. That’s why devtools + Stream works, but devtools + config server doesn't. Also, since there are no child contexts until the binder is created, introducing Stream breaks Josh’s example. [...] here are [some] suggestions: a) devtools could support storing multiple root contexts in a collection between load/reload - since all it would do is to close them and flush the collection instead of setting `rootContext` to null before reload. This would be good in general, as you might have other cases where a root context gets created  (including in a corner use case in Stream that Josh didn’t trigger). b) BootstrapApplicationListener should not create a bootstrap context if the target context already has a parent.

Apart from the fact that this is caused by a stray context created by `BootstrapApplicationListener` I think it's better to account for the possibility of multiple root contexts being created.

**Comment by philwebb** [comment]
Closing in favor of PR #7336
