### ISSUE TITLE
Spring Boot as Linux service

### ISSUE THREAD

**Issue by ewolff** [spring-projects/spring-boot#734]
Hi,
just to let you know: I had someone talk to me about how a Spring Boot application can be run as a Linux service. I pointed him towards the Java service wrapper - but maybe this would be a cool new feature to build into Spring Boot?
Eberhard

**Comment by Robin479** [comment]
This is not done, yet. There' more to a linux daemon than just an init.d interface. See my comment:

https://github.com/spring-projects/spring-boot/issues/1073#issuecomment-106599734

A daemon should be started as root (eg. to bind to port 80), but drop to user privileges before initializing user's actual application context.
