### ISSUE TITLE
Default error/exception page is rendered outside of the filter chain 

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-boot#7350]
I need to extract something from the HttpRequest and be able to access this from my application. My current solution uses a Filter in conjunction with a ThreadLocal like: https://github.com/mvitz/spring-boot-exception-handling/blob/master/src/main/java/de/mvitz/spring/boot/thymeleaf/error/MyFilter.java

Unfortunately this does not work for error pages. The rendering of these happens outside the filter chain where this Filter is registered.

The example application at https://github.com/mvitz/spring-boot-exception-handling shows this. When opening `localhost:8080/bar` below the `h1` there is an paragraph containing `foo`. When opening `localhost:8080/foo` (which throws an exception) the paragraph is empty.

**Comment by wilkinsona** [comment]
By default, a filter isn't included in error dispatches. You need to provide a `FilterRegistrationBean` for your filter and customise the dispatcher types. Something like this:

```java
    @Bean
    public FilterRegistrationBean myFilterRegistration(MyFilter myFilter) {
        FilterRegistrationBean registration = new FilterRegistrationBean(myFilter);
        registration.setDispatcherTypes(EnumSet.allOf(DispatcherType.class));
        return registration;
    }
```
