### ISSUE TITLE
Allow 'server.port' to be defined for WebEnvironment.NONE

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-boot#7353]
I want to write an integration test for my service that does not use `WebApplicationContext` but starts a server (embedded Undertow) on its own to avoid servlets and to use handlers directly. 

In 1.3 and earlier I could use `@IntegrationTest({"server.port=12345"})` to start test context. It creates web-less app and allows my class to read proper port to use. Yes, I use standard `server.port` to unify configuration experience. 

In 1.4 I still can you `@IntegrationTest` but it's deprecated. New `@SpringBootTest`, however, uses `SpringBootContextLoader` that explicitly adds `server.port=-1` in `getInlinedProperties()` and overrides any properties passed outside through `value/properties`.

What if `SpringBootContextLoader` would check whether `server.port` is passed in or not and won't add its own in the former case?

**Comment by philwebb** [comment]
I think that should be possible. Can you share an example of your test so we can see exactly what you need?

**Comment by edudar** [comment]
There are two files in the [gist](https://gist.github.com/edudar/301de2a59285671e3146b112e752f23a.):  `boot_1_3` works fine while `boot_1_4` fails because of `server.port=-1`

**Comment by philwebb** [comment]
@edudar That link 404s for me.

**Comment by edudar** [comment]
Oops, updated link, left `.` inside

**Comment by philwebb** [comment]
@edudar Thanks. Are you able to provide a more complete sample? I see what the tests are doing but I'm interested in what you mean by "... starts a server (embedded Undertow) on its own to avoid servlets and to use handlers directly".

**Comment by edudar** [comment]
Updated [gist](https://gist.github.com/edudar/301de2a59285671e3146b112e752f23a) with one more file. It is not the very exact code I use but simpler version and gives an idea of what's happening. I have a component where `server.port` is wired into. Then I call `start()` when a context is fully initialized.

**Comment by philwebb** [comment]
Thanks!
