### ISSUE TITLE
Add org.apache.logging.log4j:log4j-web

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-boot#7355]
https://logging.apache.org/log4j/2.x/manual/webapp.html

The dependency is necessary if you have a spring-boot WAR deployment.

**Comment by wilkinsona** [comment]
Log4j2 has [a bom](http://central.maven.org/maven2/org/apache/logging/log4j/log4j-bom/2.7/log4j-bom-2.7.pom) we should probably just import that.
