### ISSUE TITLE
remote update using boot-devtools does not refresh RequestMapping

### ISSUE THREAD

**Issue by oak-tree** [spring-projects/spring-boot#7356]
Hey, We are using spring boot and we are trying to get to do reload itself with `spring-boot devtools` http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-devtools

The state we get:

the `client` says it get update: 

> 2016-11-09 17:32:39.855  INFO 1692 --- [   File Watcher] o.s.b.d.r.c.ClassPathChangeUploader      : Uploaded 1 class resource
> 2016-11-09 17:32:41.136  INFO 1692 --- [pool-1-thread-1] o.s.b.d.r.c.DelayedLiveReloadTrigger     : Remote server has changed, triggering LiveReload

The `server` reload it self

This work on static files, checked against simple html file. 

But when I tried to change/add requestMapping to a controller. It did trigger the message above but the mapping did not work remote. 

Note: the mapping does work locally
2nd Note: the server console does not show the mapping as well so I guess the issue can be 

1. Upload process 
2. Reload process 

Using:

        <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.1.RELEASE</version>
		<relativePath/> 
	</parent>
        
         IntelliJ IDEA 2016.2.3
         Build #IC-162.1812.17, built on August 30, 2016
         JRE: 1.8.0_101-b13 amd64
         JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

        note that we have `Jrebel` working on the local version

**Comment by philwebb** [comment]
Are you able to provide a sample that shows the problem?

**Comment by wilkinsona** [comment]
Duplicates #7379

**Comment by oak-tree** [comment]
Hey, this issue seems to be closed on `1.4.3` milestone. For some reason I cannot compile the snapshot for it but I can compile a snapshot for `2.0.0`.  The `remove dev tools` still buggy as it does not initialize new `requestMapping` even on existing class.

**Comment by wilkinsona** [comment]
> For some reason I cannot compile the snapshot for it but I can compile a snapshot for 2.0.0

There's no need to compile anything. Snapshots are available from https://repo.spring.io/libs-snapshot.

>  The remove dev tools still buggy as it does not initialize new requestMapping even on existing class.

We have integration tests for DevTools restart now (added in https://github.com/spring-projects/spring-boot/commit/918e122ddccae7cb1bf245269e49b40822114c42). Those tests are run as part of CI and all pass so I'm pretty confident that restart works, with standard configuration at least. If you'd like us to investigate, we'll need you to describe the precise steps that are necessary to reproduce the problem.
