### ISSUE TITLE
Add security property for content security policy

### ISSUE THREAD

**Issue by qerub** [spring-projects/spring-boot#7357]
Spring Security recently got support for content security policy with version 4.1 and it would be great if this functionality was exposed through Spring Boot via `SecurityProperties`.

**Implementation sketch:** Setting `security.headers.content-security-policy` should trigger a call to `http.headers().contentSecurityPolicy(…)` inside `SpringBootWebSecurityConfiguration.configureHeaders`.

I can work on a patch if you agree that this would be a good addition.

**Comment by qerub** [comment]
With the risk of hijacking my own issue, what is the proper way to invoke `http.headers().contentSecurityPolicy(…)` until support is implemented in Spring Boot? I'm thinking others who find this issue will be interested in a workaround until it is resolved.

I've discovered that adding the configuration below clashes with `SpringBootWebSecurityConfiguration` regardless of what `@Order` I give it.

```java
@Configuration
class ContentSecurityPolicyConfiguration extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.headers().contentSecurityPolicy("…");
    }
}
```

**Comment by philwebb** [comment]
Closing in favor of PR #7373
