### ISSUE TITLE
1.4.2版本application.properties配置项中有中文的话会乱码

### ISSUE THREAD

**Issue by eric39** [spring-projects/spring-boot#7361]
1.4.2版本application.properties配置项中有中文的话会乱码

**Comment by wilkinsona** [comment]
Translation courtesy of Google Translate:

> 1.4.2 version application.properties configuration items in the Chinese words will be garbled

**Comment by IndeedPlusPlus** [comment]
Translation by a human (me)
for version 1.4.2, if there are Chinese characters in `application.properties`, some garbled text will show up somewhere(should be clarified by the issue reporter) .

**Comment by IndeedPlusPlus** [comment]
The solution is pretty straight-forward. Unicode in `.properties` files should be escaped. For example
```
foo=测试
```
should be 
```
foo=\u6d4b\u8bd5
```
in `.properties` files. You can easily convert them with [native2ascii](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/native2ascii.html)

**Comment by wilkinsona** [comment]
See #5361 for some background on why `application.properties` doesn't use UTF-8 as its encoding.

**Comment by wilkinsona** [comment]
@IndeedPlusPlus Thank you for the human translation.
