### ISSUE TITLE
Urls for management endpoints context-path was not set under the same rule for eureka clients.

### ISSUE THREAD

**Issue by heymysweetheart** [spring-projects/spring-boot#7365]
Spring boot version: 1.4.1.RELEASE
For eureka clients settings, there are configurations like: 
- `server.port`,
- `server.context-path`
- `management.port`
- `management.context-path`

1. If we set  `management.port` with the same port as  `server.port`, then the actual management path would be `${server.context-path}${management.context-path}`. 
2. But on the contrary, if we set `management.port` with port value different from that of `server.port`, then the actual management path would be `${management.context-path}`.

In this case, when we set eureka configurations like status-page-url, health-check-url, and metadata-map.management.context-path, we have to **concatenate** the management path if we set the server.port the same value as management.port. On the other side, we should not add the `server.path` in the actual management path. This is really confusing. And it's impossible to use the same applicaton.yml for these two cases. Right now we use two profiles to achieve use the same settings file.

**Question:**
I suggest to use the same real management path to be `${server.context-path}${management.context-path}`, whether setting the `server.port` and `management.port` with the same value or not. So this would be less confusing and easy to use for developers.

**Comment by philwebb** [comment]
This would make it impossible to have a management context path that didn't include the servlet context path.
