### ISSUE TITLE
Add support for `server.tomcat.accesslog.request-attributes-enabled`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7367]
See https://stackoverflow.com/questions/40150891/how-to-set-the-property-requestattributesenabled-for-accesslogvalve-in-apache-to

Looks sensible to me even though we should draw a line somewhere. WDYT @wilkinsona ?

**Comment by wilkinsona** [comment]
Seems sensible enough to me too

**Comment by domi55** [comment]
very nice! thanks @snicoll
