### ISSUE TITLE
Command line spring.profiles.active ignored if is not overriding the same property in application.properties

### ISSUE THREAD

**Issue by PawelJagus** [spring-projects/spring-boot#7375]
I have created three profiles for my app: `dev`, `integration` and `prod`.
My `resources` folder looks like this

    application.properties
    application-dev.properties
    application-integration.properties
    application-prod.properties

Now I want to select the active profile by passing it as a command line argument for my app like this

    java -jar my-spring-boot-app.jar --spring.profiles.active=dev

Unfortunately it seems to be ignored completely.

It does however work if there is a corresponding `spring.profiles.active` in the `application.properties` file.

## application.properties ##
    spring.profiles.active=integration

Now, I did not find anything in the documentation that this property passed as a command line argument should overwrite an already defined one in the `application.properties` so it looks for me like a bug.

**Comment by snicoll** [comment]
I've created an empty application from start.spring.io, packaged it with no further change and launch it as follows:

```
java -jar demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev
```

And I got:

```
2016-11-13 13:01:37.273  INFO 87112 --- [           main] com.example.DemoApplication              : The following profiles are active: dev
```

Perhaps I am missing something from your original description but such an issue should be very easy to reproduce the way you describe it. Can you please share a sample that showcases it concretely?

**Comment by PawelJagus** [comment]
Sorry, my bad. The problem was actually coming from my unit tests. After refactoring my application.properties I simply did not change the parameters for `@SpringBootTest` annotation.

It was

    @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
while it should be

    @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT, properties = { "spring.profiles.active: dev" })

Sorry for bothering. I am closing this issue.
