### ISSUE TITLE
Use Tomcat APR connector for performance improvements

### ISSUE THREAD

**Issue by PeterJerald** [spring-projects/spring-boot#7376]
In apache tomcat uses apache portable runtime(APR) to provide better performance and scalability with native execution. APR uses system resources and execute natively. If we compare the execution performance BIO , NIO and APR connectors APR provides superior performance.

I have experience the same in my development phase. I created two sets of artifacts which is standalone Jar with spring boot  embedded tomcat and spring boot war file and deployed on "tomcat" both are same code base but APR configuration is only difference.

Spring boot by default all the threads execution based on “NIO”, so I have compiled APR libraries based on below link:-

https://tomcat.apache.org/tomcat-8.0-doc/apr.html

Executed Spring Boot Jar file with APR.  Now I can see performance results are exactly same.

**In our spring boot documentation does not have APR guide to add in embedded tomcat. If we add it will help other developers as well.**

**Comment by philwebb** [comment]
I think @bclozel may have been looking into this a little. It would be nice if we could somehow make this easier.

**Comment by PeterJerald** [comment]
@philwebb  Do you required any information from my side to continue further ?

**Comment by bclozel** [comment]
This is also related to using native libs for TLS support, which is very handy for http/2 support.

Quick questions @PeterJerald:
* how would you expect to enable those native bindings?
* how are you adding those libraries to your JVM library path? Are you adding those in a well-known location in your operating system? Or are you using a JVM argument such as `-Djava.library.path=/usr/local/lib/`?
* Are you using the native OpenSSL integration as well?

**Comment by PeterJerald** [comment]
@bclozel  Please find below for my answers

1. how would you expect to enable those native bindings?
      **If we enable under application common location that help us.** 
2. how are you adding those libraries to your JVM library path? Are you adding those in a well-known location in your operating system? Or are you using a JVM argument such as -Djava.library.path=/usr/local/lib/?
       **Currently I kept along with application and I have added  -Djava.library.path path variable in JVM. If we kept under OS also fine**
3. Are you using the native OpenSSL integration as well?
      **Yes. By default tomcat native lib(8 +) requires; OpenSSL 0.9.7+, so i have installed in OS**

**Comment by OrangeDog** [comment]
I guess it should work similarly to how `netty-transport-native-epoll` is detected.

**Comment by iNikem** [comment]
@PeterJerald are there some benchmark results comparing NIO and APR based applications?

**Comment by PeterJerald** [comment]
https://gist.github.com/andreldm/7f89a3279438467a0bd41e6c1249d014

Please refer above sample program to enable APR in spring boot.

**Comment by PeterJerald** [comment]
@iNikem we tested with business logic code and compared results. let me try with sample code and will share the results.

**Comment by candrews** [comment]
It doesn't look like using the APR connector is a good idea because:
* Its configuration is different (it doesn't support jks keystores, for example)
* Its not as performant (which is really the only reason to use it). Here's a nice presentation showing that: http://events.linuxfoundation.org/sites/events/files/slides/TomcatOpenSSL.pdf

However, enabling the use of tomcat-native/APR so the OpenSSL implementation is available to the non-APR connectors is a good idea (see the benchmarks in the aforementioned pdf). Notably, enabling APR also allows for the use of http/2.

**Comment by bclozel** [comment]
Closing this issue, see https://github.com/spring-projects/spring-boot/pull/10079#issuecomment-326970302.

We will consider tomcat-native for the TLS use case in #10043.

**Comment by FreezeSoul** [comment]
nice

**Comment by dbreaker36** [comment]
https://gist.github.com/andreldm/7f89a3279438467a0bd41e6c1249d014 - This link seems to be broken. Are there other examples for enabling APR in spring boot
