### ISSUE TITLE
Improve documentation on how to register ContextListeners & Filters

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-boot#7378]
The current documentation for  "Add a Servlet, Filter or Listener to an application" http://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/htmlsingle/#howto-add-a-servlet-filter-or-listener does not explain how to do basic things such as add a listener is that not marked with an `*Listener` annotation or is a spring bean. For example an application that I am porting to SpringBoot has the following listener defined in `web.xml `
```XML
<listener>
	<listener-class>org.springframework.security.web.session.HttpSessionEventPublisher</listener-class>
</listener>
```

`HttpSessionEventPublisher` is not a SpringBean and does not have any Servlet 3.0 annotations and is in the spring security jars so I can't modify it. How can such a listener be added to a SpringBoot fat jar application? 

I think this section of the docs should be enhanced to explain how to handle such a case as it is very common when porting an old spring .war app to a .jar app. I have googled around and found no examples of how to to do this.

**Comment by wilkinsona** [comment]
> does not explain how to do basic things such as add a listener is that not marked with an *Listener annotation or is a spring bean

It doesn't explain how to do that as it's not possible. The documentation you have linked to says:

> You can either provide Spring beans for them, or enable scanning for Servlet components.

As you've noted, scanning for Servlet components won't help you as there's no annotation on the class in question and you can't modify it. That leaves you with providing a Spring bean where the documentation says:

> To add a `Servlet`, `Filter`, or `Servlet` `*Listener` provide a `@Bean` definition for it

That seems pretty clear to me. We have to strike a balance between being concise and providing sufficient explanation. IMO, "provide a `@Bean` definition for it" gets that balance right as there's nothing special about it:

```java
@Bean
public HttpSessionEventPublisher httpSessionEventPublisher() {
	return new HttpSessionEventPublisher();
}
```
