### ISSUE TITLE
ErrorPageFilter: configurable logged message

### ISSUE THREAD

**Issue by stephanedaviet** [spring-projects/spring-boot#7380]
Currently, `ErrorPageFilter` only logs the path of the request without the query string. This part of the message is obtained by a call to [`ErrorPageFilter#getDescription`](https://github.com/spring-projects/spring-boot/blob/v1.4.1.RELEASE/spring-boot/src/main/java/org/springframework/boot/web/support/ErrorPageFilter.java#L190-L193). There's no way for customization or extensibility at this place, the method is private.

It would be great to be able to customize this message without having to proceed to a full rewrite of `ErrorPageFilter` to a homemade custom filter class.

**Comment by philwebb** [comment]
I don't see any problem with making that method protected.
