### ISSUE TITLE
Rename ApplicationStartedEvent to make it clear that the application is starting but has not started

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7381]
`ApplicationStartedEvent` causes some confusion as its name suggests that the application has started, i.e that startup has completed. The event is actually trying to convey that `run` has been called and the application has begun the process of starting up. Perhaps `ApplicationStartingEvent` would be less confusing?

**Comment by philwebb** [comment]
+1

we should add a new even and trigger both so that we can deprecate the old one and remove it in 2.0

**Comment by snicoll** [comment]
The doc wasn't updated
