### ISSUE TITLE
Some events are not documented in the list of application events

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7382]
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-application-events-and-listeners

It would be useful to list `ContextRefreshedEvent` so that users can see its position relative to the Spring Boot-specific events. We could perhaps also list `EmbeddedServletContainerIntializedEvent`. Neither `ContextRefreshedEvent` nor `EmbeddedServletContainerInitializedEvent` is a `SpringApplicationEvent` so we'll need to be careful not to confuse people.

**Comment by olivergierke** [comment]
We just wondered which of the events are re-thrown in case DevTools are in place. Might be worth adding a note on that as well.

**Comment by philwebb** [comment]
@olivergierke What do you mean by "which of the events are re-thrown"?

**Comment by wilkinsona** [comment]
@philwebb Ollie and I discussed this today on Slack. "re-thrown" meant events that are published when DevTools restarts the application. The answer is all of them.
