### ISSUE TITLE
Info Actuator Not "Relaxing" Environment Variable Sources

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#7388]
Currently, the Info Actuator renders the environment variable `INFO_ENVIRONMENT_DEPLOYMENT=blue` as the following:

```
{
  "ENVIRONMENT_DEPLOYMENT": "blue",
  "app": {
    "version": {
      "spring": "4.3.3.RELEASE",
      "java": "1.8.0_111"
    }
…
```

It also renders `INFO_environment.deployment=blue` as the following:

```
{
  "environment": {
    "deployment": "blue"
  },
  "app": {
    "version": {
      "spring": "4.3.3.RELEASE",
      "java": "1.8.0_111"
    }
  }
…
```

This behavior is inconsistent and should be updated so that info properties, regardless of where they are from and what their casing and dottting/underscoring, are always rendered in a consistent way.

**Comment by philwebb** [comment]
Tagging for team discussion to decide if we can work around this in 1.5 or if we should take this on in 2.0 as part of the broader relaxed binding changes.
