### ISSUE TITLE
Embedded database fail to perform UniqueKey check after upgrade to 1.4.1

### ISSUE THREAD

**Issue by ashwgupt** [spring-projects/spring-boot#7392]
This may qualify as bug but am raising it as question for now.

After upgrade to spring-boot 1.4.1.RELEASE a few test cases for my application, that uses hibernate (from spring-boot) with H2 (for testing), are failing.

The failed test cases are particularly the ones which should fail for unique key constraint when duplicate key is attempted to be inserted.

The application functions normally in runtime with MySql but not for the test cases, which hahve always passed with previously used spring-boot version 1.3.6

FYI : 
1. I attempted switching the testing DB to HSQL and those tests still fail.
1. The test cases pass as soon I downgrade the Hibernate to use 4.3.11 - `<hibernate.version>4.3.11.Final</hibernate.version>`

Can it be an issue with hibernate 5.0 to work with an embedded database or something else?

**Comment by wilkinsona** [comment]
> Can it be an issue with hibernate 5.0 to work with an embedded database or something else?

From what you've described, it certainly sounds like a Hibernate problem to me so I'm going to close this issue. Perhaps someone on the [Hibernate forum](https://forum.hibernate.org) may be able to help you. If it turns out to be a problem in Spring Boot after all then we can re-open this issue.

**Comment by ashwgupt** [comment]
@wilkinsona I am running some tests on a standalone Hibernate with the help of wonderful [Hibernate testing templates](https://github.com/hibernate/hibernate-test-case-templates). Shall inform back this issue with my findings in order to help others if any.

**Comment by ashwgupt** [comment]
As per the findings Hibernate seem to be working okay. The save operation to DB via hibernate for different objects with duplicate key fail as expected when run on a stand alone hibernate application using hibernate-core library.

So that sends me back to Spring Boot for more investigation on why the behaviour is different when using Spring Data Rest with Hibernate.

FYI: Below is simple code snippet that can be used to reproduce the issue.

POM:
```xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
</parent>

<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
        <!--<hibernate.version>4.3.11.Final</hibernate.version>-->
</properties>
```

Entity Class:
```java
@Entity
public class Frog {

    @Id
    @GeneratedValue
    private long id;

    @Column(unique = true, nullable = false)
    private String name;

    private String colour;

    public Frog() {
    }

    public String getColour() {
        return colour;
    }

    public String getName() {
        return name;
    }
}
```

Repository Class:
```java
@RepositoryRestResource(collectionResourceRel = "frogs", path = "frogs")
public interface FrogRepository extends PagingAndSortingRepository<Frog, Long> {
}
```

Unit test:
```java
@Test
public void createDuplicateFrogNotAllowed() throws Exception {
        mvc.perform(post("/frogs")
                .contentType(APPLICATION_JSON_UTF8)
                .content("{\"name\":\"Kermit\", \"colour\":\"green\"}"))
                .andExpect(status().isCreated());

		mvc.perform(post("/frogs")
				.contentType(APPLICATION_JSON_UTF8)
                .content("{\"name\":\"Kermit\", \"colour\":\"green\"}"))
				.andExpect(status().isConflict());
}
```

The test fails as the resulting HTTP code from second `post` operation is `201` instead of expected `409`.

The same test works as expected if downgraded Hibernate is used with spring boot 1.4.1.

@wilkinsona if you agree please reopen the issue for investigation.

**Comment by wilkinsona** [comment]
@ashwgupt Can you please provide a small sample application (as a zip or Git repository) that shows the code that works when using Hibernate directly and fails when using Spring Data REST?

**Comment by ashwgupt** [comment]
Please find below the projects to show the code.

1. [data-service.zip](https://github.com/spring-projects/spring-boot/files/597184/data-service.zip)
    This application uses spring-boot-jpa and spring-boot-rest from spring-boot 1.4.1
    The test case `duplicateFrogsFailToSaveTest` from `FrogResourceIT` test class shall be the one to watch out for.

    Also of interest would be to downgrade the Hibernate version by un-commenting the relevant properties entry in POM and run the test to see it passing with Hibernate 4.3.11

2. [hibernate-orm-5.zip](https://github.com/spring-projects/spring-boot/files/597185/hibernate-orm-5.zip)
    This has the test case based upon hibernate team's provided testcase template. The test to look out for is `duplicateRecordsFailToSaveTest` in `JPAUnitTestCase` test class. 
    
    Please note the Hibernate version used for the app is 5.0.11, same as that comes with spring-boot 1.4.1

I hope this helps in reaching to its root cause. Please let me know if any further information required.

**Comment by wilkinsona** [comment]
Thanks.

If I strip out all of your custom configuration of Hibernate and use Spring Boot's auto-configuration instead the expected `409` response is received. That tells me that the problem lies in your custom configuration of Hibernate. Unfortunately, I don't have time to pinpoint the mistake you've made but here's the simplified version of the app which shows the test passing: [simplified-data-service.zip](https://github.com/spring-projects/spring-boot/files/599752/simplified-data-service.zip).

**Comment by ashwgupt** [comment]
@wilkinsona, 
I understand that the custom code (*which in fact is not custom but required for the full use case of this application to connect to multiple datasources on PCF*) may have caused the issue but my point is the regressing behaviour that that's observed.

This is not a new application but one migrated from 1.3.6 to 1.4.1 and since then the test have started failing. And that is what my whole point is.

There is a change in behaviour in boot 1.4.1 which may be expected or may be not but surely needs documentation somewhere :-)

I hope you understand my point.

**Comment by wilkinsona** [comment]
> I understand that the custom code (which in fact is not custom but required for the full use case of this application to connect to multiple datasources on PCF) may have caused the issue but my point is the regressing behaviour that that's observed.

My point is that it's your code that's configuring Hibernate. If I remove that custom configuration and allow Spring Boot to configure Hibernate, the behaviour is corrected. In other words, the regressing behaviour is due to your custom configuration of Hibernate. 

> There is a change in behaviour in boot 1.4.1 which may be expected or may be not but surely needs documentation somewhere :-)

We have already documented that Spring Boot 1.4 moves from Hibernate 4.3 to 5 by default. It's not realistic for us to document every behaviour change which that may introduce. Hopefully Hibernate's documentation does that.
