### ISSUE TITLE
exclude devtools from war

### ISSUE THREAD

**Issue by shavo007** [spring-projects/spring-boot#7398]
Bug report

Hi,

This may or may not be an issue.

Spring boot version Im using is 1.3.2

I use spring boot dev tools for local development. For local dev, we use tomcat embedded container. Unfortunately on our envs we deploy as a classic war on external tomcat.

I added the below config for gradle plugin, but in my war I still see the devtools jar.

```java
dependencies {
 compile("org.springframework.boot:spring-boot-devtools")
}
bootRepackage {
    mainClass = 'au.com.devportal.App'
    excludeDevtools = true
}
```

Any clue?

Thanks,
Shane.

**Comment by philwebb** [comment]
I'm guessing that Gradle is generating the WAR file and devtools. Our plugin can only exclude devtools when it's responsible for adding it to archive.

Perhaps you can use the `providedRuntime` scope to prevent Gradle from adding the `spring-boot-devtools` jar?

**Comment by shavo007** [comment]
Hi,

Yes, i am using the war plugin.

providedRuntime unfortunately does not work for me.

If i inspect the war, certain jars are missing such as spring boot.
This is important as others may have the same structure.

Any advice?

**Comment by philwebb** [comment]
You may also need to mark it as `transitive = false` so that other jars don't get moved. Try this:

```
buildscript {
	ext {
		springBootVersion = '1.4.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

jar {
	baseName = 'demodt'
	version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	providedRuntime('org.springframework.boot:spring-boot-devtools') { transitive = false }
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```
