### ISSUE TITLE
Exception while creating PDF file from Asciidoctor

### ISSUE THREAD

**Issue by kkgv** [spring-projects/spring-boot#7399]
I am getting exception while creating pdf file from ascii doc files using the following libraries in Spring boot application.
        
    org.asciidoctor:asciidoctorj:1.6.0-alpha.3
    org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11
    org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.6
             
I found similar issues reported earlier tried by setting class loader but no success.

The exception shown is 

   ```
 org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor
            at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944) ~[jruby-core-9.1.2.0.jar!/:?]
            at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55) ~[?:?]
            at RUBY.<top>(<script>:9) ~[?:?]
```

My code looks like this. The path is the directory where ascii doc are stored. 

```
    final Asciidoctor asciidoctor = create();
    asciidoctor.renderDirectory(new AsciiDocDirectoryWalker(path), options().backend("pdf").get());
    asciidoctor.shutdown();

```
This issue raised with project 'asciidoctorj ' (https://github.com/asciidoctor/asciidoctorj/issues/532).  But the response I got from them is it is Spring boot class loader related.

**Comment by wilkinsona** [comment]
Asciidoctor and JRuby don't like being run from a nested jar file so you need to configure your build to unpack the nested jars to a temporary location. Here's an example from Sagan (http://spring.io): https://github.com/spring-io/sagan/blob/dc100df311a0aa0b7e09b6aae1ede2f06abcbc9c/sagan-site/build.gradle#L7

**Comment by kkgv** [comment]
Thanks for quick response. I tried with 'requiresUnpack' but still getting same exception.

**Comment by wilkinsona** [comment]
@kkgv Please provide a small sample application that reproduces the problem

**Comment by kkgv** [comment]
Configuration
`package uk.co.doc.config;

import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import static org.springframework.boot.SpringApplication.run;

@SpringBootApplication
@ComponentScan("uk.co.doc")
@EnableAutoConfiguration
@Configuration
public class PdfConversionApplication {

    public static void main(final String[] args) {
        run(PdfConversionApplication.class, args);
    }

}
`
Controller class
`
package uk.co.doc.controller;

import org.asciidoctor.AsciiDocDirectoryWalker;
import org.asciidoctor.Asciidoctor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.File;

import static org.asciidoctor.Asciidoctor.Factory.create;
import static org.asciidoctor.OptionsBuilder.options;

@RestController
public class PdfConversionController {
    private static final Logger LOGGER = LoggerFactory.getLogger(PdfConversionController.class);

    @RequestMapping(value = "/createPdfDocument", method = RequestMethod.GET)
    public void downloadApiDocument(final HttpServletResponse response) {
        LOGGER.info("Start of Download API method");
        try {
            generateSwaggerAPIPdfFiles();
        } catch (final Exception e) {
            LOGGER.error("Failed to generate pdf documents", e);
        }
    }

    private void generateSwaggerAPIPdfFiles() {
        final Asciidoctor asciidoctor = create();
        LOGGER.info("Asciidoctor instance created");
        final AsciiDocDirectoryWalker asciiDocDirectoryWalker = new AsciiDocDirectoryWalker("c:/output");
        for(final File file  : asciiDocDirectoryWalker.scan()) {
            LOGGER.info("File available in output folder " + file.getPath());
        }
        asciidoctor.renderDirectory(new AsciiDocDirectoryWalker("c:/output"), options().backend("pdf").get());
        asciidoctor.shutdown();
    }
}`

build.gradle
`
group 'uk.co.doc'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'spring-boot'

sourceCompatibility = 1.8

configurations {
    compile.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    testCompile.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}


jar {
    baseName = 'pdf-conversion'
}


buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.4.1.RELEASE")
    }
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-rest')
    compile('org.asciidoctor:asciidoctorj:1.5.4.1')
    compile('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11')
    compile('org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.6')
    compile('org.springframework.boot:spring-boot-starter-log4j2')
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

springBoot {
    mainClass = 'uk.co.doc.config.PdfConversionApplication'
    requiresUnpack = ['org.jruby:jruby-complete', 'org.asciidoctor:asciidoctorj']
}`

application.yaml

`
info:
  component: PDF conversion MicroServices

server:
  port: 8080
`

**Comment by wilkinsona** [comment]
@kkgv Thanks, but it's not very easy to piece together an application from a comment (especially when the formatting is wrong). Can you please share a zip file or Git repository containing an application that I can unzip/clone and run?

**Comment by kkgv** [comment]
[pdf-conversion.zip](https://github.com/spring-projects/spring-boot/files/594750/pdf-conversion.zip)

**Comment by wilkinsona** [comment]
Your `requiresUnpack` configuration is wrong. You're using `asciidoctorj-pdf` so that needs to be unpacked too:

```groovy
springBoot {
    mainClass = 'uk.co.doc.config.PdfConversionApplication'
    requiresUnpack = ['org.jruby:jruby-complete', 'org.asciidoctor:asciidoctorj', 'org.asciidoctor:asciidoctorj-pdf']
}
```

**Comment by kkgv** [comment]
Thank you very much for the solution.

**Comment by diguage** [comment]
I had the same problem. I followed the tips, then it was OK. Thanks a lot.
