### ISSUE TITLE
inproctester like feature?

### ISSUE THREAD

**Issue by ewolff** [spring-projects/spring-boot#74]
Would it make sense to add a feature like https://github.com/aharin/inproctester to Spring Boot? I.e. add some support for HtmlUnit, WebDriver or maybe Selenium?

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by philwebb** [comment]
We have added support for WebDriver and Selenium. It looks like the referenced project isn't maintained anymore.

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-boot/issues/5263.
