### ISSUE TITLE
Update to Spring JWT 1.0.7

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7405]
Released today (upgrades bouncy castle).

**Comment by wilkinsona** [comment]
Moving from Bouncycastle 1.47 to 1.55 is rather aggressive for a maintenance release, especially given Bouncycastle's track record for breaking changes. How much of Bouncycastle does Spring Security JWT touch? Is it still compatible with earlier versions?

**Comment by dsyer** [comment]
Do you know what broke in the past? We're already using 1.55 in Spring Security RSA (used in Spring Cloud and Spring Cloud Services) because it has significant security/crypto improvements over 1.47 (i.e. actual vulnerabilities patched I think). Spring JWT and RSA combined only use a tiny part of the API, and yes that is compatible.

**Comment by wilkinsona** [comment]
One example is Crash having to add some reflective hackery to work around breaking API changes. See #2425 for some details.

FWIW, the Platform's using 1.54 in Athens. I'll try to upgrade to the latest in Brussels.

**Comment by dsyer** [comment]
Sounds like we should upgrade then. Also there is now a new feature in 1.0.7.

**Comment by snicoll** [comment]
@dsyer unfortunately, Brussels is still on 1.54 and I have no idea how to upgrade and run all our tests so it'll have to wait I am afraid.

**Comment by wilkinsona** [comment]
Brussels will upgrade to 1.56: https://github.com/spring-io/platform/issues/472
