### ISSUE TITLE
Prefix values not working as expected for the Configuration properties  

### ISSUE THREAD

**Issue by SanjayGautam** [spring-projects/spring-boot#7408]
I am trying to inject the properties something like below and it is not injecting the values 

Question

**Properties file** 
```
spring.mf.datasource.url =
spring.mf.datasource.username=
spring.mf.datasource.password=
 ```

```

@Bean(name = "datasource")
@ConfigurationProperties("spring.mf.datasource")
public DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }


```

**Bug report**
Spring Boot 1.4.2 RELEASE 

**Same code use to work in 1.3.X version**

**Comment by snicoll** [comment]
There is something that you're not showing because that code of yours must work. It shouldn't be hard for you to create a sample with those two code snippets above that reproduce the issue. Can you do that please?

**Comment by SanjayGautam** [comment]
Yes , I was thinking myself to upload the sample code to reproduce the same, thanks for looking at the issue. wait for few minutes will upload the code

**Comment by SanjayGautam** [comment]
Please find the sample code to reproduce the problem . 

[mf-soa.zip](https://github.com/spring-projects/spring-boot/files/598091/mf-soa.zip)

**Comment by philwebb** [comment]
@SanjayGautam The sample doesn't build because the following dependencies are not available:

```
		<dependency>
			<groupId>caiso.common</groupId>
			<artifactId>domain</artifactId>
			<version>1.0.9</version>
		</dependency>

		<dependency>
			<groupId>oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>11.2.0</version>
		</dependency>
```

Looking at the code, I see you're using `@PropertySource(value = { "classpath:mfsoa.properties" }, ignoreResourceNotFound = false)`. That might be triggered too late for binding, I'd suggest using `application.properties` instead.

**Comment by philwebb** [comment]
Actually `@PropertySource(value = { "classpath:mfsoa.properties" }, ignoreResourceNotFound = false)` appears to work fine. If I add H2 to your sample and add the following:

```
@Import(MfServiceConfig.class)
public class MfSoaApplication {
```

Binding appears to work.

Your `MfServiceConfig` isn't being loaded because your `MfSoaApplication` class is in a lower package.

**Comment by SanjayGautam** [comment]
Sorry about that dependency which was local to our repo, why the code snippet which I quoted in the 1.3.x release , use to work without issue , my assumption is that if we provide the prefix **"spring.mf.datasource"** like that  builder will concatenate the prefix and **inject spring.mf.datasource.url** into the DatasourceBuilder build method and grab the values. 

if you see the attached code and log now it fails on the DriverClass not being found . 

Case 1, if i add the spring.datasource.url , spring.datasource.drive-name-class default properties keys in this mfsoa.properties it still works fine  , But if i add istead spring.mf.datasource.url , and try to use prefix it does not work. Same use to work in 1.3.x release.

[mf-soa.zip](https://github.com/spring-projects/spring-boot/files/598161/mf-soa.zip)
as the code is not able to inject drive name the spring boot errors out **" determine embedded database driver class for database "**

thanks for looking into this matter pomptly.

**Comment by SanjayGautam** [comment]
Sorry about that dependency which was local to our repo, why the code snippet which I quoted in the 1.3.x release , use to work without issue , my assumption is that if we provide the prefix "spring.mf.datasource" like that builder will concatenate the prefix and inject spring.mf.datasource.url into the DatasourceBuilder build method and grab the values.

if you see the attached code and log now it fails on the DriverClass not being found .

Case 1, if i add the spring.datasource.url , spring.datasource.drive-name-class default properties keys in this mfsoa.properties it still works fine , But if i add instead **spring.mf.datasource.url ,** and try to use prefix it does not work. Same use to work in 1.3.x release.

as the code is not able to inject drive name the spring boot errors out " determine embedded database driver class for database "

mf-soa-prj.zip
mf-soa-log.zip

thanks for looking into this matter promptly.

**Comment by SanjayGautam** [comment]
Thanks @philwebb for the suggestion it works, I think I believe this is how it was working/notworking.  when i used with out the prefix and provided the default spring boot keys for the url,driver class actually it just refered to the properties and start trying to use the defauil config internally and I was assuming that it is actually trying to load the myConfig file.  why spring boot is not intelligent enought to search for the config as there is already a annotation for that class , doest that mean that we have to manully mention the configuration class import ? I though if we have exclude certain config then we use them , probably. anyway thanks again and good learning !!
