### ISSUE TITLE
Auto Configure SSL context for Jest for HTTPS connections

### ISSUE THREAD

**Issue by vishalmanohar** [spring-projects/spring-boot#7409]
Jest needs to be configured so it can talk to elasticsearch instances running on HTTPS.
Given that managed ElasticSearch providers like AWS ElasticSearch run exclusively on HTTPS, this is desirable for auto-configuration.

[This section on Jest project page](https://github.com/searchbox-io/Jest/tree/master/jest#https--ssl) gives an basic example.

**Comment by snicoll** [comment]
> This section on Jest project page gives an basic example.

Thanks but if you have a specific sample in mind, please share it. We don't build auto-configuration based on "basic example" but rather on real-life scenario. If there is a common pattern, maybe we could expose that in a smarter way.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by snicoll** [comment]
FYI you can apply such configuration via a customizer now, see #7762
