### ISSUE TITLE
Make SpringPhysicalNamingStrategy easier to subclass

### ISSUE THREAD

**Issue by savinov** [spring-projects/spring-boot#7410]
Versions: spring-boot 1.4.1, hibernate5.

Perhaps `SpringPhysicalNamingStrategy` works wrong.
It's default physical naming strategy in a spring-boot-app and makes all the column names lowercased in a query. In most cases that's not a problem because usually databases is not case sensitive, but sometimes quotation is needed for columns. For example Oracle allow # hash-sign symbol in column names but only with double quotes. Oracle identifiers usually are uppercased, double quotes makes column names case sensitive to Oracle, so there is a problem: `SpringPhysicalNamingStrategy` makes quoted column names lowercased, but Oracle doesn't find them because the names in DB are uppercased.

Maybe `SpringPhysicalNamingStrategy` shouldn't lowercase column names?

**Comment by philwebb** [comment]
I think changing this now would likely cause compatibility issues for other users. I'd recommend plugging in your own `PhysicalNamingStrategy` implementation.

**Comment by savinov** [comment]
There is org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl which doesn't change column names at all, so it makes possible to use quotes having no problems with letter case mismatch.
However, SpringPhysicalNamingStrategy can be improved to work with quoted column names too. I don't think it's a good idea to set column name letter case without possibility to tweak it. Ideally SpringPhysicalNamingStrategy should check JDBC driver type and make decisions based on it.
Please consider some improvements in the future releases.

**Comment by abhijitsarkar** [comment]
I think I came across this issue with MySQL, and if my memory serves right, had to configure MySQL to use [ower_case_table_names](http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lower_case_table_names).

**Comment by philwebb** [comment]
> Ideally SpringPhysicalNamingStrategy should check JDBC driver type and make decisions based on it

We don't want to make `SpringPhysicalNamingStrategy` any more complex and we're not planning to change the default behavior. What we'll do is add a few protected methods so that it's easier to subclass then users can plug-in a custom strategy as needed.
