### ISSUE TITLE
The spring-boot-gradle-plugin will cause the error that Gradle can't download the latest SNAPSHOT dependency from maven nexus.

### ISSUE THREAD

**Issue by Leo-Lei** [spring-projects/spring-boot#7411]
I use spring boot in my project and my project is build by Gradle. The project also has some SNAPSHOT dependencies inner our own company. But while I build the project, Gradle can't download the latest SNAPSHOT jars from my company's nexus server.
If I remove spring boot from the project, Gradle can get the right latest jar.
I think this is a bug that will affect the building seriously. Could you help to look into this? Thanks.

I tried Gradle version of 2.14.1, 2.7 and 3. All of them have this problem. Spring boot gradle plugin is 1.4.2 or 1.4.1.

**Comment by Leo-Lei** [comment]
I already use the following configuration as the official website provide: 
configurations.all {
    // check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

But this configuration will only take affect while not use the spring boot. Once I use the spring boot, it will not take affect. This will not take affect. I have spent much much much time on troubleshooting, but have no result.....

**Comment by wilkinsona** [comment]
We can try to help, but we'll need some more information. A sample that reproduces the problem would be ideal.

**Comment by Leo-Lei** [comment]
OK, I will prepare a Sample ASAP and let you know. Thanks very much.

**Comment by Leo-Lei** [comment]
Please see the project.
https://github.com/Leo-Lei/test-spring-boot-gradle-plugin
The maven nexus repository can only be visit inner our company. So maybe your team need to test it in your own maven nexus server.

**Comment by wilkinsona** [comment]
Thanks, but that project doesn't reproduce the problem. Perhaps you can update it, making use of a public repository that contains snapshots? If you can't do that, then please describe the problem in much more detail. We need to know exactly what is happening and exactly what you expected to happen. Seeing some output from your build would help with that.

**Comment by Leo-Lei** [comment]
Below is my testing scenario:
1. There is a nexus server in our company.
2. There are 2 projects A and A. Both of them are in SNAPSHOT version. Project B depends on A.
3. Assume that currently I didn't use spring-boot or sprint-boot-gradle-plugin in project B.
4. I build project A to generate an A-1.0.0-SNAPSHOT.jar and publish it to nexus.
5. I build project B, Gradle will download the A-1.0.0-SNAPSHOT.jar from nexus during build process.
6. I add a method test1() to project a, rebuild it and publish the new SNAPSHOT jar to nexus.
7. I rebuild project B, and Gradle will get the latest SNAPSHOT jar from nexus with the method test1().
Gradle works fine and always get the latest A-SNAPSHOT jar from nexus, if there is no spring-boot or spring-boot-gradle-plugin in project.
8. Add spring-boot and spring-boot-gradle-plugin to project.
9. Rename the test1() to test2() in project A, rebuild it and publish it to nexus.
10. Rebuild project B, and I will find the dependency A-SNAPSHOT still has the old method test1(), not test2(). But the latest version of A in nexus has the method name of test2(), instead of test1(). So Gradle didn't get the correct latest A-SNAPSHOT.jar from nexus during the build process of project B.

In order to reproduce the problem, we need to update and publish a jar to some repository, we need read and write access, so it is hard to use of a public repository in the sample. Maybe setup a nexus repository in local is a good choice. Also I use the Intellij IDEA to build the project. I can see the exactly dependencies jars in the "External Libraries" window. If you don't use IDEA, maybe packing the project with all its dependencies to a JAR is a better choice to check if the latest SNAPSHOT jar is used or not.

It is late night in our time, I need to go home and have a rest.....Hope this update can clarify the problem. Thank you. Also I will update the sample tomorrow.

**Comment by Leo-Lei** [comment]
I have updated the sample. https://github.com/Leo-Lei/test-spring-boot-gradle-plugin

**Comment by wilkinsona** [comment]
Thanks. You've only configured `cacheChangingModulesFor` on the configurations, you also need to configure dependency management with the same:

```groovy
dependencyManagement {
    resolutionStrategy {
        cacheChangingModulesFor 0, 'seconds'
    }
}
```

**Comment by Leo-Lei** [comment]
thanks, wilkinsona. Could you please provide more details on where to add the configuration you provided. I try to add them in root place or in the dependencies block, but get the error "could not find method dependencyManagement()".

**Comment by Leo-Lei** [comment]
wilkinsona, sorry for my previous comment. I uncomment the spring-boot dependency stuff and have a try, it works. I have tried several times, and it seems now Gradle will get the latest snapshot jar. Thanks a lot. It resolve the problem and save me lot of time.
At last, I have a question why I can't find the configuration that you provided in the Gradle official website or spring-boot official website?

**Comment by Leo-Lei** [comment]
And if I don't use spring-boot, this configuration is not needed. So I recommend the spring boot website to add this configuration on its official website for clarification. This is my kindly advice.

**Comment by wilkinsona** [comment]
As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-dependency-management),
Spring Boot's Gradle plugin automatically applies the Dependency Management Plugin. We also link to its documentation where the configuration described above is [already documented](https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-the-dependency-management-resolution-strategy).

**Comment by Leo-Lei** [comment]
I got it, thanks for your help.

**Comment by isaacdong** [comment]
this really helps me, thanks!

**Comment by starflash** [comment]
thanks very mush.
I also have this problem ... until found this.
