### ISSUE TITLE
Add new PATCH methods to TestRestTemplate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7412]
https://github.com/spring-projects/spring-framework/commit/dbe81bef52e1bcaf802663d2bb3236c69f922512

**Comment by snicoll** [comment]
Those methods have just been backported to `4.3.x` so we need to backport this change as well.

**Comment by juergenzimmermann** [comment]
@wilkinsona, @snicoll 
The method variants for `patchForObject` are **public** in the Spring Framework: https://github.com/spring-projects/spring-framework/blob/v4.3.5.RELEASE/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L451.

However, the according methods in `TestRestTemplate` are **package private**: https://github.com/spring-projects/spring-boot/blob/v1.4.3.RELEASE/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/TestRestTemplate.java#L581

**Comment by snicoll** [comment]
Thanks @juergenzimmermann, I've created #7742
