### ISSUE TITLE
Enhancement request: Source . /lib/lsb/init-functions in the init script

### ISSUE THREAD

**Issue by oneiros-de** [spring-projects/spring-boot#7415]
We are using services created with Spring Boot on Debian 8, i.e. with systemd. We create unit files and deploy them along with the jar symlinked to `/etc/init.d/`, so systemd uses the unit files after a `systemctl enable`. 

But the init script is still there and can be used. But since it doesn't redirect to service or systemctl it does not know if the service was started by systemd and will start/stop a _second_ instance of the service if called with `start`/`stop`.

The solution for this employed by other init scripts seems to be source  `/lib/lsb/init-functions` early in the script as that will somehow redirect the script to systemd (I'm not an expert for systemd on Debian).

I could find no simple way to patch that into the init script during our build process and it seems to be a feature useful to others.

**Comment by wilkinsona** [comment]
> The solution for this employed by other init scripts seems to be source /lib/lsb/init-functions early in the script as that will somehow redirect the script to systemd (I'm not an expert for systemd on Debian).

Just sourcing `/lib/lsb/init-functions` doesn't really have any effect as all it does it to make a number of functions available to the rest of the script. If the rest of the script doesn't use those functions, as is the case with the launch script, then it won't do anything.

To make use of the functions in `init-functions`, the launch script would have to be fairly significantly re-written to call `start_daemon`, `pidofproc`, `killproc`, and `status_of_proc`. That's a fairly significant undertaking, and one that we're unlikely to have time for in the short term at least.

In the meantime, you can always [provide your own launch script](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-script-customization).

**Comment by oneiros-de** [comment]
> Just sourcing `/lib/lsb/init-functions` doesn't really have any effect as all it does it to make a number of functions available to the rest of the script. If the rest of the script doesn't use those functions, as is the case with the launch script, then it won't do anything.

It will also source `/lib/lsb/init-functions.d/40-systemd` which has this code block:
```
systemctl_redirect () {
    local s
    local rc
    local prog=${1##*/}
    local command=$2

    case "$command" in
        start)
            s="Starting $prog (via systemctl)"
            ;;
        stop)
            s="Stopping $prog (via systemctl)"
            ;;
        reload|force-reload)
            s="Reloading $prog configuration (via systemctl)"
            ;;
        restart)
            s="Restarting $prog (via systemctl)"
            ;;
    esac

    service="${prog%.sh}.service"

    # Don't try to run masked services. Don't check for errors, if
    # this errors, we'll just call systemctl and possibly explode
    # there.
    state=$(systemctl -p LoadState show $service 2>/dev/null)
    [ "$state" = "LoadState=masked" ] && return 0

    [ "$command" = status ] || log_daemon_msg "$s" "$service"
    /bin/systemctl $command "$service"
    rc=$?
    [ "$command" = status ] || log_end_msg $rc

    return $rc
}

if [ "$_use_systemctl" = "1" ]; then
    # Some init scripts use "set -e" and "set -u", we don't want that
    # here
    set +e
    set +u

    if  [ "x$1" = xstart -o \
        "x$1" = xstop -o \
        "x$1" = xrestart -o \
        "x$1" = xreload -o \
        "x$1" = xforce-reload -o \
        "x$1" = xstatus ] ; then

        systemctl_redirect $0 $1
        exit $?
    fi
fi

```
So it *has* an effect as it will call ` systemctl_redirect`.

**Comment by wilkinsona** [comment]
It's just occurred to me that we can't using `init-functions` due to the way implementations typically identify the pid of a process. For example, on Ubuntu if the pid file can't be found it falls back to calling `/bin/pidof` to check if the process is running. This simply checks that there's _any_ process running using a particular executable. This doesn't work will with Java where multiple different apps may be launched using the same `java` executable.
