### ISSUE TITLE
@Sql annotation on tests makes schema.sql executed twice

### ISSUE THREAD

**Issue by savinov** [spring-projects/spring-boot#7416]
Sample to reproduce: https://github.com/savinov/spring-boot-schema-twice

spring-boot 1.4.1, spring-data-jpa, hsqldb (for tests). There is `schema.sql` and `data.sql` in the test resources folder. Four test classese are annotated with `@RunWith(SpringRunner.class)`, `@DataJpaTest` and `@Sql`. One test class (`SchemaTwice3Test`) is annotated only with `@RunWith(SpringRunner.class)` and `@DataJpaTest`.

Run tests: `mvn test`

The problem is: `schema.sql` is executed twice somewhere between `SchemaTwice3Test` run and other tests run. If add (uncomment) `@Sql` annotation to the `SchemaTwice3Test` then there is no problems. If remove (comment) `@Sql` annotation from all the test-classes then there is no problems too.

Workarond with `spring.datasource.continueOnError=true` makes all the tests pass, but it's not a solution.

It seems that there is some initialization incompartability between `@Sql` annotation and `org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer`.

**Comment by philwebb** [comment]
This is almost certainly similar to #7524 and ##7101 in that the removal of the `@Sql` annotation causes a new cache key. Perhaps our `ImportsContextCustomizer` logic could be refined again.

**Comment by wilkinsona** [comment]
The problem doesn't occur with Spring Boot 1.4.3 because the two contexts no longer share an in-memory database. However, we believe that there shouldn't be two contexts in the first place as the SQL specified in `@Sql` is run in a transaction that's rolled back, i.e. it has no longer term effect on the context.

**Comment by wilkinsona** [comment]
We've opened #7953 to address the unnecessary creation of the second context. #7473 is the issue which means that the same database is no longer shared across the two contexts.
