### ISSUE TITLE
Don't publish JUnit runners

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7421]
Should we publish the jar or not. If not we need to test during the RC1 release.

**Comment by philwebb** [comment]
See #7420 for context

**Comment by spencergibb** [comment]
:+1: for publish. IIRC, Spring Cloud copied it and then published it.

**Comment by wilkinsona** [comment]
I'd preferr that we didn't publish them so that we have the freedom to change them however and whenever we like

**Comment by snicoll** [comment]
What Andy said.

**Comment by wilkinsona** [comment]
Erring on the side of caution, I've updated the build plan so that spring-boot-junit-runners is no longer published. As a result, the latest snapshot that's available should be from 21/11: http://repo.spring.io/libs-snapshot/org/springframework/boot/spring-boot-junit-runners/1.5.0.BUILD-SNAPSHOT/

**Comment by snicoll** [comment]
Added an explicit note in the release checklist about this.

**Comment by snicoll** [comment]
We've decided to rename that to `spring-boot-test-support`

**Comment by snicoll** [comment]
Bamboo build plan and release check list updated.
