### ISSUE TITLE
DevTools classloader loads incompatible classes from multi-module maven

### ISSUE THREAD

**Issue by verydapeng** [spring-projects/spring-boot#7422]
Sample project: https://github.com/verydapeng/spring-devtools-classloading-issue

We have a multi-module maven project. We put all the domain classes in a dedicated module

```java
public class SomeService {

    @Transactional
    public List<String> listAll() {
        return Collections.emptyList();
    }
}
```

then the spring-boot loader as another dedicated module

```java

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class);
    }
}

@Configuration
class Config {

    @Bean
    SomeService someService() {
        return new SomeService();
    }

    @Bean
    ApplicationRunner applicationRunner(SomeService service) {
        return args -> System.out.println("am = " + service);
    }
}
```

However, the class loaded are incompatible when we run the project from IDE (STS or IntelliJ)

![image](https://cloud.githubusercontent.com/assets/2149970/20454509/efb1da9c-ae7d-11e6-8332-a5896dedda6d.png)

![image](https://cloud.githubusercontent.com/assets/2149970/20454514/0ff6add2-ae7e-11e6-8f8e-621a4f2afec5.png)

> org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'someService' is expected to be of type [app.SomeService] but was actually of type [app.SomeService$$EnhancerBySpringCGLIB$$d68b0542]

We can reproduce the problem even using java cli with classpath manually setup, see the sample project for the actual commands 

Current findings 

0. ```mvn spring-boot:run``` works! 
1. ```mvn package, then java``` -jar works!
2. if we remove the devtools dependency, everything works, but this defeat the purpose, as we do want the auto restart feature 
3. if we *change* the project folder to anything other than ```spring-boot```, magic!

**Comment by verydapeng** [comment]
env
mac sierra 
java version 1.8.0_111
springboot 1.4.0, 1.4.2

**Comment by wilkinsona** [comment]
> if we change the project folder to anything other than spring-boot, magic!

That's not magic, that's the [documented behaviour](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart)

**Comment by verydapeng** [comment]
I have read ur link but I couldn't find anything related to about "you can not have a project lives inside a folder called 'spring-boot'" 

Can you be more specific? @wilkinsona

**Comment by wilkinsona** [comment]
That's the most specific link I can give you. In the linked section, it says:

> When deciding if an entry on the classpath should trigger a restart when it changes, DevTools automatically ignores projects named spring-boot, spring-boot-devtools, spring-boot-autoconfigure, spring-boot-actuator, and spring-boot-starter.

**Comment by verydapeng** [comment]
Okie thanks for the clarification, however I do feel "preventing" my application from starting is a bit more than "ignores" 

As right now our app keeps crashing on startup 

one more observation, if we remove the Transactional annotation then the app starts properly 

This is quite a surprise

**Comment by kennyk65** [comment]
Perhaps the documentation could be slightly more illuminating regarding this restriction on use of CGLib proxies: - "If you project is named "spring-boot" et al., you cannot use CGLib proxies".  After all, the issue reported is not directly about reloading, but as Dapeng says, it cannot start.
