### ISSUE TITLE
server.connection-timeout has no effect for main Tomcat connector

### ISSUE THREAD

**Issue by PostalBear** [spring-projects/spring-boot#7424]
Hello, 

I discovered that `server.connection-timeout` has no effect for Tomcat's main connector and default value of 60000 is always used.
I observed this behavior with Spring Boot 1.4. 
As far as I can see this happens because `org.springframework.boot.autoconfigure.web.ServerProperties.customizeConnectionTimeout` modifies only additional Tomcat connectors and keeping main one untouched. 

I also created [Demo project](https://github.com/PostalBear/SpringConnectionTimeout) to illustrate this problem. 

I hope this would be helpful to fix this problem. 
PS thanks for great framework :)

**Comment by snicoll** [comment]
Closing in favour of PR (#7425) @PostalBear if you intend to submit a PR right the way, you can just submit it, no need to create a separate issue for it.
