### ISSUE TITLE
spring init --list shows packageName as a parameter

### ISSUE THREAD

**Issue by rtteal** [spring-projects/spring-boot#7427]
Version: Spring CLI v1.4.1.RELEASE

`spring init --list`

Id | Description | Default value
----|----|----
packageName | root package | com.example 

As per #3716, the parameter should be package-name.

**Comment by snicoll** [comment]
`spring init --list` is the capabilities of the server (the output is what the service returns, the client has no control over it):

```
To list all the capabilities of the service:
        $ spring init --list
```

`spring help init` will give you the list of parameters that the client actually supports: the main purpose of the former is to give you the default value for each parameter (the id refers to a parameter, not the parameter you should use on the command line).
