### ISSUE TITLE
Replace our manual dependency management for Jackson with an import of its bom

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7432]
https://github.com/FasterXML/jackson-bom

**Comment by philwebb** [comment]
Be nice to try and get this into 1.5 but we should wait for the outcome of https://github.com/FasterXML/jackson-bom/issues/2

**Comment by bclozel** [comment]
That issue has been fixed - jackson-bom now manages `jackson-jaxrs-base`.

**Comment by wilkinsona** [comment]
We still need to wait for a release that contains the fix

**Comment by wilkinsona** [comment]
Closing in favour of the PR from @eddumelendez (#7436).
