### ISSUE TITLE
@MockBean doesn't work with FactoryBeans

### ISSUE THREAD

**Issue by rkawala** [spring-projects/spring-boot#7439]
We're using Spring Boot 1.4.2 and we're unable to use the `@MockBean` annotation with components that implement `FactoryBean`. Attached is a JUnit test that reproduces the issue.

[factorybeanissue.zip](https://github.com/spring-projects/spring-boot/files/604905/factorybeanissue.zip)

**Comment by philwebb** [comment]
I asked Rick to raise this after a brief slack discussion.

**Comment by rkawala** [comment]
Thanks again for your help! Will this be in Spring Boot 1.4.3?

Best,
Rick

**Comment by philwebb** [comment]
Yes. Mind you, the use-case is a little unusual so we should probably talk some more to see why it was needed in the first place.

**Comment by rkawala** [comment]
In the end, I changed that factory bean to a conventional autowired bean,
because that worked with @MockBean. The people who made that FactoryBean
are no longer on the project, so I don't know why they chose that approach.
But I really appreciate getting a fix in under 24 hours!

Best,
Rick
