### ISSUE TITLE
CustomSessionTemplate Never Called?

### ISSUE THREAD

**Issue by PowerBin** [spring-projects/spring-boot#7442]
I had implements the SqlSessionInterceptor class.
But it is allways call "org.mybatis.spring.SqlSessionTemplate" not "com.becool.base.spring.sqlSessionTemplate.CustomSqlSessionTemplate".
I do not know why?
Please help me,thank you very much!!!

The code on github url:https://github.com/PowerBin/spring-boot/wiki.

**Comment by snicoll** [comment]
@PowerBin we don't support Mybatis directly (see https://github.com/mybatis/spring-boot-starter). Regardless, this looks like a question so please ask it on stackoverflow.
