### ISSUE TITLE
Springboot remote shell : unable to manipulate logging for spring framework

### ISSUE THREAD

**Issue by evmin** [spring-projects/spring-boot#7444]
Springboot Remote Shell includes a command to manipulate the log level through java.util.logging - "jul". 

Yet springboot itself uses a different mechanism (logback?), so org.springframework classes are not visible and not reachable.

As a system administrator I would like to be able to adjust the logging level of the underlying springboot system through the remote shell.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, the [CRaSH project](http://www.crashub.org) that the remote shell uses is dead. As a result, Spring Boot's Remote Shell will be deprecated in 1.5 (#7044) and removed in 2.0 (#7006). Given this situation we have no plans to make any enhancements to the remote shell.
