### ISSUE TITLE
Remote or Local shell to operate the environment

### ISSUE THREAD

**Issue by evmin** [spring-projects/spring-boot#7445]
As a system administrator maintaining a number of systems based on Springboot I depend on the ability to logon to the running application and change system specific parameters on the fly using only the tooling available at the standard Unix/Linux boxes.

With impeding CRaSH Remote shell removal I need an alternative solution to continue to be able to  change the parameters dynamically.

The ideal outcome for me would be forking of the CRaSH code and embedding it into the Springboot.

**Comment by philwebb** [comment]
@evmin Unfortunately I don't think we'll have the resources to maintain CRaSH in addition to Spring Boot, it's just too much work.

I'm curious as to which system parameters you regularly update and why CRaSH is your preferred method. Have you considered using actuator REST endpoints or JMX?

**Comment by evmin** [comment]
One of the use cases for us is the Apache Camel based on Springboot that we run in the Docker containers.

Remote shell is the way to run a number of camel route administration commands (start, stop, info, rerun, etc). Also we have implemented a whole lot of the custom commands (reset flags, do operational maintenance on the persistence, etc). Quite often the troubleshooting process requires log set DEBUG and log tail.

Being a Docker container neither REST or JMX seem to be feasible alternative. The ports are not exposed due to security concerns. Plus the elaborate operation would be too cumbersome using set of curl calls and impossible with JMX - the operation needs to be carried out from the docker container shell itself (again, security).

Having the ability to shell into the running Application was one of the key requirements for us to adopt Springboot as the platform. I would say it is one of the key enablers that from my perspective separate Springboot from to the other app platforms. One of the core competitive advantages.

I am OK with replacing CRaSH with another solution as far as the following requirement holds:
- Ability to easily operate using standard linux/unix environment (ssh into was brilliant)
- Easy extensibility (groovy commands were godsend with Springboot - we were able to customise a lot)

Happy to provide an example (template) of such Camel implementation.
Again, this is more of the admin ease of use, rather than developers ease to code.

@davsclaus - thoughts?

**Comment by philwebb** [comment]
Thanks for the information.

I'm not sure I agree that CRaSH is necessarily more secure than a well managed REST or JMX endpoint. Possibly SSH'ing into your docker container and then calling your endpoints might be one option for you.

We've pretty much made up our minds about dropping CRaSH support. Whilst I appreciate that it might have been a factor in your decision to adopt Spring Boot, it's unfortunately not something that we can maintain going forward.

If you're still comfortable using CRaSH, and you want to continue beyond Spring Boot 1.5, you might be able to adapt [`CrshAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/CrshAutoConfiguration.java) for your own needs.

I'm sorry that difficult decisions like this are necessary, and removing functionality sometimes needs happen. Tying to balance the needs of users against the maintenance and development costs isn't always easy.

**Comment by evmin** [comment]
@philwebb Of course I am sad about the decision. I wish the ops were getting a tad more love - essentially that is the ultimate objective of the software.

I will try your suggestion about curl, thought I am skeptical - it would imply that at least two endpoints would need to be maintained - one external and one internal.

Also I see that the other case - https://github.com/spring-projects/spring-boot/issues/876 - is still open. Ironically, the suggestion there was exactly to use CRaSH.
