### ISSUE TITLE
Fat jar has two candidate URLs for `classpath*:**/` patterns, leading to resources duplication

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7449]
This is a follow-up of [SPR-14934](https://jira.spring.io/browse/SPR-14934). 

Assume we need to collect the resources matching the `classpath*:/**/*.xml` pattern in a Spring Boot application. As of 1.4, two root urls will be used for the search:

```
jar:file:/Users/foo/SPR-13685/target/SPR-13685-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/
jar:file:/Users/foo/SPR-13685/target/SPR-13685-0.0.1-SNAPSHOT.jar!/
```

The former is the one used by the `LaunchedUrlClassLoader` and the latter is used by the system classloader. Because we asked to search "everything", the system classloader finds the resource again, leading to a duplication. Arguably, the  system classloader must ignore anything in `BOOT-INF` since it is managed by the `LaunchedUrlClassLoader` already.

**Comment by philwebb** [comment]
@wilkinsona will be interested in this one. I hope we don't need to add filtering back to the system classloader.

**Comment by kazuki43zoo** [comment]
@wilkinsona @snicoll 

I tried spring boot 1.4.3 and spring 4.3.5 snapshot version, however this issue and SPR-14934 does not resolved in my repro project.

In my repro project is https://github.com/kazuki43zoo/repro-PathMatchingResourcePatternResolver.

```
$ ./mvnw -U clean package
$ $ java -jar target/path-demo-0.0.1-SNAPSHOT.jar
...
------resources1---------
jar:file:/Users/xxx/git/repro-PathMatchingResourcePatternResolver/target/path-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/my/mappers/BarMapper.xml
jar:file:/Users/xxx/git/repro-PathMatchingResourcePatternResolver/target/path-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/my/mappers/FooMapper.xml
jar:file:target/path-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes/my/mappers/BarMapper.xml
jar:file:target/path-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes/my/mappers/FooMapper.xml
...
```

It has been loaded twice from relative path and absolute path.

**Comment by snicoll** [comment]
@kazuki43zoo I am not sure the framework fix has been backported yet. @jhoeller any idea here?

**Comment by kazuki43zoo** [comment]
@snicoll  Oh... I will confirm it.

**Comment by wilkinsona** [comment]
It hasn't: https://github.com/spring-projects/spring-framework/commits/4.3.x/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java

**Comment by kazuki43zoo** [comment]
@snicoll @wilkinsona , thanks for quick replying !! I will try again after backporting to Spring 4.3.x line.
Thanks.

**Comment by kazuki43zoo** [comment]
Hi @snicoll @wilkinsona @jhoeller, I've tried latest snapshot version. This issue has been resolved !!

**Comment by wilkinsona** [comment]
@kazuki43zoo Thanks for the confirmation
