### ISSUE TITLE
Switch to thymeleaf 3

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7450]
We need to decided if we should upgrade in Boot 1.5 or 2.0.

**Comment by philwebb** [comment]
See also #6258

**Comment by wilkinsona** [comment]
Spring Social doesn't support Thymeleaf 3 at the moment. I suspect @habuma may not have time to tackle that in the 1.5 timeframe.

**Comment by philwebb** [comment]
We're going to target this to 2.0 to give Spring Social time to upgrade.

**Comment by danielfernandez** [comment]
This looks awesome, thanks a lot.

**Comment by rajadilipkolli** [comment]
@wilkinsona I still get  thymeleaf.version 2.1.5.RELEASE from latest 2.0.0-snapshot build , I think we need to upgrade it to 3.0.3 in dependencies , right now i am using 3.0.3 by overriding.
