### ISSUE TITLE
spring-boot-undertow session persistence clashes with spring-boot-devtools 

### ISSUE THREAD

**Issue by kuhnroyal** [spring-projects/spring-boot#7460]
`org.springframework.boot.context.embedded.undertow.FileSessionPersistence` uses an `ObjectInputStream` to load persistent sessions but should be using a `ConfigurableObjectInputStream`.

This lead to `java.lang.ClassCastException: com.example.AccountDetail cannot be cast to com.example.AccountDetail` when spring-boot-devtools are used.

See http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-known-restart-limitations

**Comment by kuhnroyal** [comment]
I have a PR ready for this, which branch/release do I target?

**Comment by snicoll** [comment]
`1.4.x` most probably. If you have a PR, no need for a separate issue, you can submit the PR directly.

**Comment by kuhnroyal** [comment]
Ok, good to know.

**Comment by snicoll** [comment]
Closing in favour of the PR #7462
