### ISSUE TITLE
Update version of hamcrest

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#7464]
Enhancement:

Update version of hamcrest used by `spring-boot-starter-test`. It is currently using an old version of hamcrest (1.3). There is a new 2.0.0 version that has been available for some time now. Note that the artifact names have changed. Instead of:
```
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-core</artifactId>
</dependency>
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-library</artifactId>
</dependency>
```

It is now:
```
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-java</artifactId>
</dependency>
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-junit</artifactId>
</dependency>
```

You might want to add exclusions for the old artifact names to avoid conflicts.

Thank you.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we use JUnit 4.12 which depends on Hamcrest 1.3 and we want to keep those versions in alignment.
