### ISSUE TITLE
Remove Spring Data GemFire starter and sample in favour of separate project

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7465]
Given that the auto-configuration for GemFire and Spring Data GemFire is going to be developed outside of Spring Boot, it doesn't make sense for us to have a starter and sample as they won't represent the recommended way of doing things. Instead, a starter and sample(s) should be provided by the new auto-configuration project for GemFire and Spring Data GemFire.

**Comment by wilkinsona** [comment]
I'm going to schedule this for 2.0 to give plenty of time for the new project to get established

**Comment by jxblum** [comment]
So, I am confused, will the existing Spring Boot Starter Data GemFire and Spring Boot Sample Data GemFire be removed or not?  I am prepared to move these into the separate project/repo to be developed, maintained, supported outside of Spring Boot.

**Comment by philwebb** [comment]
@jxblum They remain in the next Spring Boot release (1.5) but have been removed in Spring Boot 2.0 (but that won't be in people hands for a while).
