### ISSUE TITLE
Align AbstractFilterRegistrationBean dispatcher types with servlet spec

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7467]
The default dispatcher types defined in `AbstractFilterRegistrationBean` were originally copied from `AbstractDispatcherServletInitializer.getDispatcherTypes()` however they [continue to cause problems](https://github.com/spring-projects/spring-boot/issues/5737).

Rather than trying to pick our own set we should align with [the servlet spec](http://docs.oracle.com/javaee/6/api/javax/servlet/FilterRegistration.html#addMappingForServletNames(java.util.EnumSet,%20boolean,%20java.lang.String...)) and use `DispatcherType.REQUEST` as the default.

We will then need to check our own configuration of filters to see if specified dispatcher types are required for them.

**Comment by cemo** [comment]
It would be cool to be set default values from configuration files.

**Comment by wilkinsona** [comment]
This change will mean that `FORWARD`, `INCLUDE`, and `ASYNC` are removed from the default dispatcher types. The loss of `FORWARD` and `INCLUDE` appears to be inconsequential. The loss of `ASYNC` does have an effect: it means that the security context is now null within an async dispatch. I think we should change the default there.

**Comment by cemo** [comment]
@wilkinsona see https://github.com/spring-projects/spring-boot/issues/4505#issuecomment-157072267 please. I still believe that `ERROR`, `ASYNC` and `REQUEST` are suitable for default. These 3 dispatcher type are usually are the beginning of request chains. However `FORWARD` and `INCLUDE` are not used at the beginning of request, instead they are used after.

**Comment by wilkinsona** [comment]
Sorry, @cemo, but we're not going to change our decision to use `REQUEST` as the general purpose default as we want to align with the Servlet spec. Just to be clear, my comment above was specifically with regards to the default for the security filter.

**Comment by cemo** [comment]
Thanks @wilkinsona, really makes sense to align with spec.

**Comment by wilkinsona** [comment]
See #8288 and #8289 for exceptions to the new default of `REQUEST`.
