### ISSUE TITLE
Response message is missing

### ISSUE THREAD

**Issue by atom-x** [spring-projects/spring-boot#7468]
Spring boot version: 1.4.2.RELEASE

When I setup the simplest Spring Boot App and send HTTP request, HTTP responses don't contain response message appended to response code.
For instance, I expect to receive "HTTP/1.1 404 Bad Request" or "HTTP/1.1 200 OK" in the first line of response. But what I receive is "HTTP/1.1 404  " or "HTTP/1.1 200 ". Response message (Bad Request, OK or any other) is missing.

To reproduce the issue go to start.spring.io and choose Maven, 1.4.2 boot version and add Web dependency.

Please archived project for details:
[demo.zip](https://github.com/spring-projects/spring-boot/files/609995/demo.zip)

It might be tomcat issue. Unfortunately I didn't have time yet to go deeper.

**Comment by snicoll** [comment]
Duplicates #6789
