### ISSUE TITLE
Output generated by Gradle plugin's bootRun task isn't color-coded

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#747]
`spring-boot:run` in the Maven plugin produces color-coded output, whereas `bootRun` in the Gradle plugin does not

**Comment by kkonrad** [comment]
Is there any plan to fix this?

**Comment by wilkinsona** [comment]
Yes, although we don't consider it high priority. Contributions are most welcome.

**Comment by Nowheresly** [comment]
Issue #2331 seems similar to this one.

**Comment by nickgrealy** [comment]
This setting worked for me:

```Groovy
bootRun {
    jvmArgs = ["-Dspring.output.ansi.enabled=ALWAYS"]
}
```

**Source:** http://stackoverflow.com/questions/28783832/getting-spring-boot-color-console-logging-working-within-intellij

**Comment by binkley** [comment]
@nickgrealy Your JVM flag certainly works.  However, it's a problem when using Gradle to launch the program in a non-terminal environment, such as CI.

**Comment by antonrud** [comment]
@nickgrealy thx for advice!

However, if working with Kotlin you might need to add following to your **build.gradle.kts** :
```
tasks.bootRun {
    jvmArgs = listOf("-Dspring.output.ansi.enabled=ALWAYS")
}
```

Worked for my project: Gradle 5.4.1, Kotlin 1.3.21, Spring 2.1.6.RELEASE
