### ISSUE TITLE
Create @ConditionalOnMissingServletFilter

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#7475]
This Conditional annotation should: 
* look for a bean of a particular type
* if it doesn't find one, look for a `FilterRegistrationBean` that will register a Filter of a particular type

This condition should improve the auto-configuration of Servlet Filters.

We could go for a shorter name `@ConditionalOnMissingFilter`, but this could clash with a future similar annotation for Spring Web Reactive `WebFilters`.

**Comment by philwebb** [comment]
Fixed in 44a46f1514cb22b0b9e9b5b066ae63e4acf472fa but accidentally referenced the wrong issue number.
