### ISSUE TITLE
Settings endpoints.enabled=false does not globally disable all endpoints v1.4.1

### ISSUE THREAD

**Issue by loesak** [spring-projects/spring-boot#7477]
Bug report

more details: http://stackoverflow.com/questions/40617489/spring-boot-actuator-endpoint-configuration-doesnt-seem-to-be-working-as-expect

Using v1.4.1 of Spring Boot

When attempting to disable of all actuator endpoints, i set the property "endpoints.enabled" to "false". However i was still able to access many of the existing endpoints. To verify which endpoints were still enabled, i enabled just the actuator endpoint and invoked it. It showed that there were many endpoints still enabled (or at least still listed). Some of the endpoints would not get invoked when attempting to be called but some would still execute (may just have been the third party ones).

My expectation here was two fold. 1) if the endpoint is disabled, it should not be discoverable through the actuator endpoint and 2) all endpoints should be disabled regardless if their added by other libraries (i.e. zuul, hystrix, etc.)

**Comment by philwebb** [comment]
Looking at stackoverflow I think the first part of the question has been resolved in #7476. The `endpoints.enabled` flag not having an effect looks like a Spring Cloud issues. Other than `/health` all the endpoints are provided by Spring Cloud.

I just tried our actuator sample application and setting `endpoints.enabled=false` appears to switch off everything.

Please could you raise an issue with Spring Cloud to see if they could respect the flag.
