### ISSUE TITLE
Failed to execute goal on project spring-boot-integration-tests

### ISSUE THREAD

**Issue by timothyadam** [spring-projects/spring-boot#7480]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Validation Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-validation ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Jersey Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jersey ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Jetty Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jetty ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot JOOQ Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jooq ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Atomikos JTA Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jta-atomikos ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Bitronix JTA Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jta-bitronix ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Narayana JTA Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-jta-narayana ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Log4j 2 Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-log4j2 ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Mail Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-mail ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Mobile Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-mobile ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Mustache Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-mustache ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Actuator Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-actuator ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Starter Parent 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Security Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-security ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Social Facebook Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-social-facebook ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Social Twitter Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-social-twitter ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Social LinkedIn Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-social-linkedin ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Test Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-test ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Thymeleaf Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-thymeleaf ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Undertow Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-undertow ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot WebSocket Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-websocket ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Web Services Starter 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-starter-web-services ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Actuator Docs 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-actuator-docs ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot CLI 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spring-boot-cli ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Integration Tests 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/maven-metadata.xml
Downloaded: http://repo.spring.io/snapshot/org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/maven-metadata.xml (3 KB at 0.5 KB/sec)
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/spring-test-5.0.0.BUILD-20161124.173652-425.pom
Downloaded: http://repo.spring.io/snapshot/org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/spring-test-5.0.0.BUILD-20161124.173652-425.pom (9 KB at 2.4 KB/sec)
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-core/5.0.0.BUILD-SNAPSHOT/maven-metadata.xml
Downloaded: http://repo.spring.io/snapshot/org/springframework/spring-core/5.0.0.BUILD-SNAPSHOT/maven-metadata.xml (3 KB at 0.3 KB/sec)
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-core/5.0.0.BUILD-SNAPSHOT/spring-core-5.0.0.BUILD-20161124.173652-427.pom
Downloaded: http://repo.spring.io/snapshot/org/springframework/spring-core/5.0.0.BUILD-SNAPSHOT/spring-core-5.0.0.BUILD-20161124.173652-427.pom (4 KB at 0.3 KB/sec)
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/spring-test-5.0.0.BUILD-20161124.173652-425.jar
Downloading: http://repo.spring.io/snapshot/org/springframework/spring-core/5.0.0.BUILD-SNAPSHOT/spring-core-5.0.0.BUILD-20161124.173652-427.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Boot Dependencies ........................... SUCCESS [  0.584 s]
[INFO] Spring Boot Parent ................................. SUCCESS [  0.153 s]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.003 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [  0.001 s]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  0.002 s]
[INFO] Spring Boot Loader ................................. SUCCESS [  0.067 s]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [  0.002 s]
[INFO] Spring Boot Maven Plugin ........................... SUCCESS [  0.038 s]
[INFO] Spring Boot Gradle Plugin .......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Antlib ................................. SUCCESS [  0.001 s]
[INFO] Spring Boot ........................................ SUCCESS [  0.044 s]
[INFO] Spring Boot Test ................................... SUCCESS [  0.001 s]
[INFO] Spring Boot AutoConfigure .......................... SUCCESS [  0.002 s]
[INFO] Spring Boot Test Auto-Configure .................... SUCCESS [  0.001 s]
[INFO] Spring Boot Actuator ............................... SUCCESS [  0.002 s]
[INFO] Spring Boot Developer Tools ........................ SUCCESS [  0.001 s]
[INFO] Spring Boot Docs ................................... SUCCESS [  0.002 s]
[INFO] Spring Boot Starters ............................... SUCCESS [  0.001 s]
[INFO] Spring Boot Logging Starter ........................ SUCCESS [  0.004 s]
[INFO] Spring Boot Starter ................................ SUCCESS [  0.005 s]
[INFO] Spring Boot ActiveMQ Starter ....................... SUCCESS [  0.002 s]
[INFO] Spring Boot AMQP Starter ........................... SUCCESS [  0.000 s]
[INFO] Spring Boot AOP Starter ............................ SUCCESS [  0.001 s]
[INFO] Spring Boot Artemis Starter ........................ SUCCESS [  0.001 s]
[INFO] Spring Boot JDBC Starter ........................... SUCCESS [  0.000 s]
[INFO] Spring Boot Batch Starter .......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Cache Starter .......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Spring Cloud Connectors Starter ........ SUCCESS [  0.006 s]
[INFO] Spring Boot Data Cassandra Starter ................. SUCCESS [  0.001 s]
[INFO] Spring Boot Data Couchbase Starter ................. SUCCESS [  0.001 s]
[INFO] Spring Boot Data Elasticsearch Starter ............. SUCCESS [  0.001 s]
[INFO] Spring Boot Data GemFire Starter ................... SUCCESS [  0.001 s]
[INFO] Spring Boot Data JPA Starter ....................... SUCCESS [  0.001 s]
[INFO] Spring Boot Data MongoDB Starter ................... SUCCESS [  0.001 s]
[INFO] Spring Boot Data Neo4j Starter ..................... SUCCESS [  0.001 s]
[INFO] Spring Boot Data Redis Starter ..................... SUCCESS [  0.001 s]
[INFO] Spring Boot Tomcat Starter ......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Web Starter ............................ SUCCESS [  0.003 s]
[INFO] Spring Boot Data REST Starter ...................... SUCCESS [  0.001 s]
[INFO] Spring Boot Data Solr Starter ...................... SUCCESS [  0.001 s]
[INFO] Spring Boot FreeMarker Starter ..................... SUCCESS [  0.002 s]
[INFO] Spring Boot Groovy Templates Starter ............... SUCCESS [  0.001 s]
[INFO] Spring Boot HATEOAS Starter ........................ SUCCESS [  0.002 s]
[INFO] Spring Boot Integration Starter .................... SUCCESS [  0.001 s]
[INFO] Spring Boot Validation Starter ..................... SUCCESS [  0.001 s]
[INFO] Spring Boot Jersey Starter ......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Jetty Starter .......................... SUCCESS [  0.000 s]
[INFO] Spring Boot JOOQ Starter ........................... SUCCESS [  0.001 s]
[INFO] Spring Boot Atomikos JTA Starter ................... SUCCESS [  0.001 s]
[INFO] Spring Boot Bitronix JTA Starter ................... SUCCESS [  0.001 s]
[INFO] Spring Boot Narayana JTA Starter ................... SUCCESS [  0.003 s]
[INFO] Spring Boot Log4j 2 Starter ........................ SUCCESS [  0.001 s]
[INFO] Spring Boot Mail Starter ........................... SUCCESS [  0.001 s]
[INFO] Spring Boot Mobile Starter ......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Mustache Starter ....................... SUCCESS [  0.001 s]
[INFO] Spring Boot Actuator Starter ....................... SUCCESS [  0.001 s]
[INFO] Spring Boot Starter Parent ......................... SUCCESS [  0.001 s]
[INFO] Spring Boot Security Starter ....................... SUCCESS [  0.001 s]
[INFO] Spring Boot Social Facebook Starter ................ SUCCESS [  0.001 s]
[INFO] Spring Boot Social Twitter Starter ................. SUCCESS [  0.001 s]
[INFO] Spring Boot Social LinkedIn Starter ................ SUCCESS [  0.000 s]
[INFO] Spring Boot Test Starter ........................... SUCCESS [  0.001 s]
[INFO] Spring Boot Thymeleaf Starter ...................... SUCCESS [  0.000 s]
[INFO] Spring Boot Undertow Starter ....................... SUCCESS [  0.000 s]
[INFO] Spring Boot WebSocket Starter ...................... SUCCESS [  0.003 s]
[INFO] Spring Boot Web Services Starter ................... SUCCESS [  0.002 s]
[INFO] Spring Boot Actuator Docs .......................... SUCCESS [  0.001 s]
[INFO] Spring Boot CLI .................................... SUCCESS [  0.045 s]
[INFO] Spring Boot Integration Tests ...................... FAILURE [31:35 min]
[INFO] Spring Boot Gradle Integration Tests ............... SKIPPED
[INFO] Spring Boot Launch Script Integration Tests ........ SKIPPED
[INFO] Spring Boot Security Tests ......................... SKIPPED
[INFO] Spring Boot Security Tests - Web Hello World ....... SKIPPED
[INFO] Spring Boot Build .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:38 min
[INFO] Finished at: 2016-11-25T13:27:51+08:00
[INFO] Final Memory: 80M/273M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-boot-integration-tests: Could not resolve dependencies for project org.springframework.boot:spring-boot-integration-tests:pom:2.0.0.BUILD-SNAPSHOT: The following artifacts could not be resolved: org.springframework:spring-test:jar:5.0.0.BUILD-SNAPSHOT, org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT: Could not transfer artifact org.springframework:spring-test:jar:5.0.0.BUILD-20161124.173652-425 from/to spring-snapshots (http://repo.spring.io/snapshot): GET request of: org/springframework/spring-test/5.0.0.BUILD-SNAPSHOT/spring-test-5.0.0.BUILD-20161124.173652-425.jar from spring-snapshots failed: Read timed out -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-boot-integration-tests

**Comment by timothyadam** [comment]
I just download spring boot    then  I mvn clean  it   then  error  Failed to execute goal

**Comment by snicoll** [comment]
That's a glitch with `repo.spring.io`. I just tried and the build works for me.

**Comment by timothyadam** [comment]
thanks  really   snicoll
