### ISSUE TITLE
`@ConditionalOnProperty` does not handle lists properly

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7483]
We use a `List<String>` instead of a `String` in many places to allow YAML to configure the property with nested structure. `spring.couchbase.bootstrap-hosts` is one of these.

In `CouchbaseAutoConfiguration` we check if that property is set to auto-configure a `Bucket`. The following works: `spring.couchbase.bootstrap-hosts=localhost` but the following does not `spring.couchbase.bootstrap-hosts[0]=localhost`

**Comment by snicoll** [comment]
I've tried to fix this in 1bfd245 which works for most cases but breaks the case where no prefix is specified for a composite.

Basically what the code does know is effectively binding the environment for the given prefix (if the prefix is not set, it binds the full environment (!) ). That way, we get what the binder would do on the pojo. The rest of code looks pretty much the same.

Unfortunately it does so in a generic way and any element in the map leads to a new list. So for instance, `@ConditionalOnProperty("some.property")` does not work anymore as the map contains an entry for `some` that is a map with the content of `property`). So when the (unchanged) code checks for a key in `some.property` it does not find it.

Arguably that would be the same problem with any property that defines a dot in it (`@ConditionalOnProperty(prefix = "foo", value = "bar.biz")`).

We could fix that with a regex matching if there is no match. Having said that, if `PropertyResolver` was supporting that use case, no change in `OnPropertyCondition` would be required.

**Comment by philwebb** [comment]
I'm worried about speed issues trying to make `@ConditionalOnProperty` too smart. I'd love to rationalize all this stuff in 2.0 when we revisit properties.

**Comment by snicoll** [comment]
Discussing this a bit more with @jhoeller, I am not sure that rationalizing the properties stuff is going to change anything. Those two worlds aren't asymmetrical. You have properties on one hand and  there's nothing special about `spring.couchbase.bootstrap-hosts[0]` for the `PropertyResolver` (its contract is to check if a property is available, it has no notion of binding). On the other hand you have the binder that knows `[0]` is an indexed property. 

If we truly want this to be asymmetrical, we need a `PropertyResolver` of some kind that knows about binding. It should also have a property à la `ValueWrapper` that tells you in one go if a property is present and its value if it is. Right now, `RelaxedPropertyResolver` does its magic twice (one to check that the property exists and one to get its value).

**Comment by philwebb** [comment]
Let's document the limitation in Javadoc and suggest that a custom condition is used for such cases.

**Comment by snicoll** [comment]
reopening to backport and fix the package tangle

**Comment by snicoll** [comment]
Ignore me, got confused by Github's that lead me to think this commit was only on `master`
