### ISSUE TITLE
Spring Boot 1.4.2-RELEASE not loading mysql drivers

### ISSUE THREAD

**Issue by fedepia** [spring-projects/spring-boot#7488]
Hi guys,

I've created a very simple app skeleton with 1.4.1-release, however if I upgrade to 1.4.2-release version the app doesn't start because of following error with mysql drivers:

    Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

The same application works perfectly well if I use 1.4.1.. I've tried to upload here the .zip sample app but the uploader reject it, so you can download it from here:
[](https://drive.google.com/file/d/0BwVS6hr87wXgRDEtSzZaenF5cUE/view?usp=sharing)

Not sure whether this is a bug on the 1.4.2 version, but creating this ticket just in case.

**Comment by snicoll** [comment]
We've upgraded the mysql driver, maybe you've downloaded it for the first time and it got corrupted? 

Run `mvn dependency:purge-local-repository` and try again.

**Comment by fedepia** [comment]
Tested it with running the purge but still same problem.

I've run:

    mvn dependency:purge-local-repository 
    mvn -DskipTests=true clean install 
    java -jar -Dspring.profiles.active=test -Dspring.output.ansi.enabled=ALWAYS target/base-0.0.1-SNAPSHOT.jar

**Comment by snicoll** [comment]
> so you can download it from here:

It's missing the link. Can you please fix that?

**Comment by snicoll** [comment]
It should be noted I've just upgraded a mysql app from 1.4.1 to 1.4.2 and I got no issue so we really need your sample to move forward.

**Comment by fedepia** [comment]
Here you can find the link and the app as well.
[https://drive.google.com/file/d/0BwVS6hr87wXgRDEtSzZaenF5cUE/view?usp=sharing](sample app)

[service-demo.zip](https://github.com/spring-projects/spring-boot/files/615255/service-demo.zip)

Let me know anything you need.

**Comment by snicoll** [comment]
@fedepia that's not really a minimal sample. If I enable the `test`profile, the app is stuck after the Spring Boot banner so something is definitely wrong there. Please share a sample that allows me to reproduce the problem.

**Comment by fedepia** [comment]
@snicoll, the app is loading well, I used the exact config of my project, the output is being logged in service.log. There you will find the:

    Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

**Comment by snicoll** [comment]
Wow, it would have been nice to share that info, don't you think? 

So, as for my cfp app this application does not throw that exception and starts just fine. This must be a corrupted jar in your local repo. Please reopen if you have a way to reproduce that exception on another machine. When you do, please indicate the exact steps that are necessary.

**Comment by fedepia** [comment]
@snicoll, sorry... thought I had provided that, it was in a different thread. I have removed manually the .m2/mysq/mysql-connector-java/5.1.40 jar file from my repo, tested it again and it's starting.

I trusted `mvn dependency:purge-local-repository` did the trick but seems it didn't.

Thanks for the help.
