### ISSUE TITLE
Adding maven resource filter in application.properties breaks xml config during spring-boot:run

### ISSUE THREAD

**Issue by franz-see** [spring-projects/spring-boot#749]
Steps to reproduce:
1. Clone Demo app : https://github.com/franz-see/spring-boot-filtered-application-properties-with-xml
2. Setup your local settings.xml using settings.xml.sample
3. Execute `mvn clean spring-boot:run`

Expected: Application will run with no problem.
Actual: nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jdbcTemplate' is defined

However, if you do the following:
3b. Execute `mvn clean package && java -jar target/*war`

It starts to work.

Furthermore, if you do 
3b. Modify application.properties and remove all maven filtering and replace with hard-coded values

it starts to work as well.

**Comment by andidev** [comment]
Maybe the wrong place to ask but is the addResources configuration implemented for the Spring Boot Gradle Plugin as well?

**Comment by philwebb** [comment]
@andidev It doesn't look like we have an equivalent option in the Gradle plugin yet. Please raise a new issue if you need it, it shouldn't be a difficult change to make.

**Comment by andidev** [comment]
Thanks I'll do so then!
