### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by wang007** [spring-projects/spring-boot#7492]
when I setted logging in `application.properties` to don't output logs, but console always output logs

**Comment by snicoll** [comment]
@wang007 sorry I didn't get that. Could you please rephrase or explain the issue. If this is a question, please ask it on Stackoverflow (regardless we need more  details).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
