### ISSUE TITLE
Autoconfigure RabbitMQ Java Client metrics

### ISSUE THREAD

**Issue by acogoluegnes** [spring-projects/spring-boot#7498]
RabbitMQ Java Client 4.0 brings support for metrics collection through Dropwizard Metrics. This feature is disabled by default in the client, but it would make sense to enable it automatically in Spring Boot if all the condition are met (RabbitMQ Java Client 4.0 and Dropwizard Metrics on the classpath).

The metrics would also automatically be plugged on the actuator metrics HTTP endpoint.

**Comment by snicoll** [comment]
Closing in favour of the PR #7499 

@acogoluegnes no need to open both an issue and PR, thanks!
