### ISSUE TITLE
Add dependency management for Rabbit's client

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7509]
When we do we should also consider #7499

**Comment by wilkinsona** [comment]
IIRC, we just get it transitively from Spring AMQP. Boot 2.0 is using Spring AMQP 2.0, so we've already upgraded. We should, perhaps, introduce dependency management for the client. It's in the Platform at the moment.

**Comment by philwebb** [comment]
Thanks @wilkinsona, that means #7499 can't happen in 1.5.
