### ISSUE TITLE
Upgrade to maven-assembly-plugin to 3.1 +

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7513]
See #7226 and commit 4f7fffb127dd8b33e605c990b248a2f035c8d070.

Unfortunately the assembly plugin is currently broken due to https://github.com/codehaus-plexus/plexus-archiver/issues/53

**Comment by wilkinsona** [comment]
This is a bit of a mess. The required version of Commons Compress is out, but it [appears to require Java 7](https://github.com/codehaus-plexus/plexus-archiver/pull/55#issuecomment-272967766). That's holding up a PR to fix the Plexus Archiver issue. I doubt we're going to get this into 1.5, and perhaps wouldn't even want to if it cut of Java 6 support for users of the assembly plugin.

**Comment by michael-o** [comment]
Maven and Plexus developer here. The previous comment by @wilkinsona is treated very seriously, at least by me. There are too many consequences. I will try to raise other devs' attention. You might want to raise an issue with Commons Compress reverting this change for now.

**Comment by philwebb** [comment]
Thanks @michael-o! We'll probably need to stick with the older version for Spring Boot 1.5. Spring Boot 2.0 is going to require Java 8 anyway, so the Java 7  Commons Compress issue won't matter so much then.

**Comment by snicoll** [comment]
The [vote to release `maven-assembly-plugin` 3.1.0](https://www.mail-archive.com/dev@maven.apache.org/msg114496.html) has started.
