### ISSUE TITLE
Document that dev-tools has an influence on cache headers

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#7516]
When testing my application locally with devtools enabled, I was searching for ways to make the cache headers work ok for my CSS/JS and webjars. I tried various configuration changes in the application, but none of that was needed. I only needed to disable the dev-tools temporary so I could see the behaviour as it would be in production. It would be good to document this. I can do a proposal if you can tell me where in the reference documentation you would like me to add something? I was thinking about adding chapter 20.2.7 at http://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/htmlsingle/#using-boot-devtools-restart if that is ok?

**Comment by bclozel** [comment]
I think it's already documented [in section 20.1](http://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/htmlsingle/#using-boot-devtools-property-defaults)

**Comment by wimdeblauwe** [comment]
It could be more explicit about CSS/JS/webjars and HTTP cache headers I think.

**Comment by bclozel** [comment]
Is this more explicit?

> For example, template engines will cache templates to save repeatedly parsing template files. Spring MVC controllers can write HTTP caching headers. Whilst caching is very beneficial in production, it can be counter productive during development. 

Any specific ideas on how to better explain that?

**Comment by wimdeblauwe** [comment]
I would do:

> For example, [template engines](link to chapter 27.1.7 here) will cache templates to avoid repeatedly parsing template files. Spring MVC controllers can add HTTP caching headers to responses, CSS files and/or JavaScript files (Either your own or from webjars). Whilst caching is very beneficial in production, it can be counter productive during development. 
> For this reason, `spring-boot-devtools` will avoid as much caching as possible. Be sure to take this into account if you are testing the caching behaviour of your application from your IDE. You might want to disable it temporarely in that case by removing the jar from your classpath or running the application from a packaged jar file.
