### ISSUE TITLE
Consider adding additional plugin dependency management

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7517]
Commit https://github.com/spring-projects/spring-boot/commit/140379fc5a31ddb2a268c438d370f8dcb607edf8 added additional plugin dependency management in a sample. This version is managed by `spring-boot-parent` but the samples aren't using it. Perhaps this should be promoted to `spring-boot-dependencies` ?

**Comment by philwebb** [comment]
Yeah, seems sensible.
