### ISSUE TITLE
Actuator metrics should support tags

### ISSUE THREAD

**Issue by jiming** [spring-projects/spring-boot#7520]
Just like netflix servo does.

https://github.com/Netflix/servo/wiki/Getting-Started

Search "withTag" please, you can find the code example.

With tags, we can do much better metric record and report.

**Comment by philwebb** [comment]
Indeed it should. There are a lot of things that we'd like to do with metrics and tags (or multidimensional metrics is just one). See #4909 for a metrics refresh theme. Unfortunately, we may not get to this before Spring Boot 2.0.
