### ISSUE TITLE
Exclude TestConfiguration classes even when running outside a spring-test managed context

### ISSUE THREAD

**Issue by sirianni** [spring-projects/spring-boot#7525]
Spinoff of https://jira.spring.io/browse/SPR-9090 

IDEs such as Eclipse commingle `/src/test/java` and `/src/main/java` into a single classpath.  As such, `@TestConfiguration` classes can be picked up when running the `main` `SpringBootApplication` in Eclipse. 

Spring Boot Test already has the capability to exclude such configuration classes.  Unfortunately, that capability uses the `ContextCustomizer` hook which is only available inside a spring-test-managed context.    Would it be possible to migrate this capability into the core framework such that the `TypeExcludeFilters` could be leveraged when running a main application?

**Comment by philwebb** [comment]
> IDEs such as Eclipse commingle /src/test/java and /src/main/java into a single classpath. As such, @TestConfiguration classes can be picked up when running the main SpringBootApplication in Eclipse

This doesn't appear to happen for me. If I add the following to our simple sample application in `src/main/test`:

```java
@Configuration
public class TestConfig {

	@PostConstruct
	public void bang() {
		throw new RuntimeException("BOOM!");
	}

}
```

It loads just fine. Furthermore, if I refer to `TestConfig` from any code in `src/main/java` I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: sample/simple/TestConfig
	at sample.simple.SampleSimpleApplication.main(SampleSimpleApplication.java:45)
Caused by: java.lang.ClassNotFoundException: sample.simple.TestConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

@sirianni Do you have an example application we can look at, along with the steps needed to trigger this behavior in Eclipse?

**Comment by sirianni** [comment]
To be clear, this issue applies to running tests and main apps via Eclipse only.

Are you using any special Eclipse plugins?  Eclipse uses a single classpath for all launch targets within a project and does not differentiate `main` vs. `test`.

See:
* https://issuetracker.springsource.com/browse/STS-3882
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=224708
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=376616
* https://discuss.gradle.org/t/main-vs-test-compile-vs-runtime-classpaths-in-eclipse-once-and-for-all-how/17403/9

**Comment by philwebb** [comment]
> To be clear, this issue applies to running tests and main apps via Eclipse only.

I'm using Eclipse

> Are you using any special Eclipse plugins?

No, but perhaps m2e is being smart when tests are launched. What build system do you use? Have you got a small example that we can run?

**Comment by philwebb** [comment]
@sirianni That explains it, thanks. The sample I was running was Maven.

**Comment by philwebb** [comment]
After some consideration we've decided it's not a good idea for us to try and compensate for the shortcomings of the IDE. It might be worth investigating [buildship Gradle support](http://projects.eclipse.org/projects/tools.buildship) to see if that has more smarts about running tests with the correct classpath.

**Comment by sirianni** [comment]
> After some consideration we've decided it's not a good idea for us to try and compensate for the shortcomings of the IDE.

Thanks for the consideration and quick feedback.  I can't say I disagree with your decision.

**Comment by sirianni** [comment]
For future reference for anyone reading this thread, [here is the buildship bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482315) for separating runtime and test classpaths.

**Comment by sirianni** [comment]
And the [Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=105372) for supporting multiple classpaths per project.

**Comment by sirianni** [comment]
Sorry to be replying to a dead thread, but is there a way to use `TypeExcludeFilters` outside of a Spring Test scenario?  All of the code that detects and initializes them seems coupled to the spring-test framework (`ContextCustomizer`, etc.).  

Is there a way to activate `TypeExcludeFilters` in a normal (non-test) Spring Boot application context?

**Comment by philwebb** [comment]
@sirianni See `org.springframework.boot.context.TypeExcludeFilter`

Here's an example that uses an `ApplicationContextInitializer` to add a filter that prints out all classes (but doesn't actually filter):

```java
	public static void main(String[] args) throws Exception {
		SpringApplication app = new SpringApplication(SampleSimpleApplication.class);
		app.addInitializers(
				new ApplicationContextInitializer<ConfigurableApplicationContext>() {

					@Override
					public void initialize(
							ConfigurableApplicationContext applicationContext) {
						applicationContext.getBeanFactory().registerSingleton(
								"mytypefilter", new TypeExcludeFilter() {

							@Override
							public boolean match(MetadataReader metadataReader,
									MetadataReaderFactory metadataReaderFactory)
											throws IOException {
								System.err.println(
										metadataReader.getClassMetadata().getClassName());
								return false;
							}

						});
					}

				});
		app.run(args);
	}

```

**Comment by sirianni** [comment]
Thanks @philwebb .  The usage of `ApplicationContextInitializer` was the piece I was missing as all of the internal framework usage was via `ContextCustomizer`.

So all `TypeExcludeFilter` singletons need to get explicitly registered?  Is there a way for `TypeExcludeFilter`s themselves to get picked up via `@ComponentScan` in some sort of "2 pass" initialization (i.e. with a static `@Bean` method similar to property placeholder stuff)?

**Comment by philwebb** [comment]
> So all TypeExcludeFilter singletons need to get explicitly registered? Is there a way for TypeExcludeFilters themselves to get picked up via @ComponentScan in some sort of "2 pass" initialization

No, I'm afraid not. You can however register `ApplicationContextInitializer` in the `spring.factories` file which might help if you wanted to try an automatically apply filters in a bunch of projects.

**Comment by edeandrea** [comment]
The pattern I use to get around Eclipse is for any config classes I create for my tests I tag them with `@Profile("NameOfMyTestConfiguration")`, and then any test classes which use them I tag with `@ActiveProfiles("NameOfMyTestConfiguration")`. This ensures that when running my tests only my relevant test classes get picked up, and when running my application none of my test class configuration gets picked up.

The other trick I use is to always run my application in Eclipse using the Gradle Buildship plugin `bootRun` task. Gradle will make sure only the correct classes will be picked up.

Or you could switch to IntelliJ (which I've done over the past few months), then you don't need to worry at all about it!
