### ISSUE TITLE
Classloader issue when overiding RMIClassloader with 1.4.x

### ISSUE THREAD

**Issue by jschmied** [spring-projects/spring-boot#7536]
Hi!

I use a overriden RMIClassloader. It was working fine with Spring boot 1.3.x.

It puts a file into:
META-INF/services/java.rmi.server.RMIClassLoaderSpi
this file goes in in the fat jar in the root META-INF.

The class end up inside the application classes and is invisible for the system classloader.
If I put the class file manually along the org\springframework\boot\loader\ it works.

I understand, its not possible to make application classes visible to the system classloader (and this issue is similar to the problem with custom CharsetProvider).

Is it possible to modify the build process to put abitary classes or jar files (exploded) along the loader classes?

**Comment by wilkinsona** [comment]
Duplicates #6626
