### ISSUE TITLE
Broken Autoconfiguration for Couchbase Health Check

### ISSUE THREAD

**Issue by PatrickTheFirst** [spring-projects/spring-boot#7543]
The following SOF ticket describes a problem with the auto-configuration of the Couchbase health indicator:
http://stackoverflow.com/questions/40905089/spring-couchbase-health-indicator

**Short version:**
The health check does not provide Couchbase information, even when `spring-data-couchbase` is on the classpath and `application.properties` is configured correctly.

The problem seems to be in `HealthIndicatorAutoConfiguration.java`. When I remove `@ConditionalOnBean(CouchbaseOperations.class)` from the following code snippet it works:
```
        @Configuration
	@ConditionalOnClass({ CouchbaseOperations.class, Bucket.class })
	@ConditionalOnBean(CouchbaseOperations.class)
	@ConditionalOnEnabledHealthIndicator("couchbase")
	public static class CouchbaseHealthIndicatorConfiguration extends
			CompositeHealthIndicatorConfiguration<CouchbaseHealthIndicator, CouchbaseOperations> {

		private final Map<String, CouchbaseOperations> couchbaseOperations;

		public CouchbaseHealthIndicatorConfiguration(
				Map<String, CouchbaseOperations> couchbaseOperations) {
			this.couchbaseOperations = couchbaseOperations;
		}

		@Bean
		@ConditionalOnMissingBean(name = "couchbaseHealthIndicator")
		public HealthIndicator couchbaseHealthIndicator() {
			return createHealthIndicator(this.couchbaseOperations);
		}
	}
```
**NOTE:** I duplicated `CouchbaseHealthIndicatorConfiguration` because I didn't want to change existing spring code. 

My guess is that the `@AutoConfigureAfter` does not check for all Couchbase related classes that are necessary. That's where my investigation stopped because I didn't know how to continue.

**Comment by snicoll** [comment]
I can reproduce with the sample so something must have changed.

**Comment by snicoll** [comment]
@PatrickTheFirst thanks for the sample. The auto-config was refering to `CouchbaseAutoConfiguration` but the `CouchbaseTemplate` is provided by `CouchbaseDataAutoConfiguration`. I've just fixed that and the health entry now shows up.
