### ISSUE TITLE
Restructure org.springframework.boot.actuate.autoconfigure

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7545]
There are a small number of classes in the package that aren't really anything to do with auto-configuration:

- `LinksEnchancer`
- `MetricsFilter`
- `MetricsFilterSubmissions`

I think it may also benefit from having some sub-packages to split things up a bit.

**Comment by philwebb** [comment]
Shall we take this on in 2.0?

**Comment by wilkinsona** [comment]
That's my preference. I noticed it while working on #5875 and #7505. I think we'd be better deferring those issues till the restructuring's been done. If we tackle them now, we'll be adding APIs in 1.5 that we're then going to break in 2.0 as things change package. As far as I can tell, we can't add the new APIs in 1.5 and keep the existing code where it is without introducing a tangle.
