### ISSUE TITLE
Issue with JavaMailSender - Password always required even when is not

### ISSUE THREAD

**Issue by MuriLOCO** [spring-projects/spring-boot#7547]
Hello, I have been using JavaMailSender implementation of SpringBoot and it works well. But last month I found an "issue" with that. 

I have Postfix Relay-Server configured on my Linux server that is taking care of the Mail Sending features. To make the JavaMail connect to the Postfix I just need to inform the Port and the Address which is usually "localhost", I don't need to informa Username neither Password because the credentials are already on Postfix.

With normal JavaMail I can do that normally but with the SpringBoot implementation I am obliged to put a password, if I leave it blank it gives me an exception but if I put anything (does not matter because the Postfix is not using the JavaMail password anyway) it passes. It's an "annoying" bug, but no critical. But I want to report.

I tested with SpringBoot last version (2.0.0) and the bug is still there. Thank you.

**Comment by wilkinsona** [comment]
> but with the SpringBoot implementation

What do you mean by "SpringBoot implementation"? Spring Boot doesn't implement the JavaMail API.

Can you provide a sample that shows the two different behaviours that you've described?

**Comment by MuriLOCO** [comment]
You can use the library JavaMail, adding as a Dependency in your POM file or you can use the spring-boot-starter-mail and use the SpringBoot implementation of JavaMail which you already have some beans created and you specify the credentials, server, etc on your application.properties. This feature has this bug that I reported.

**Comment by snicoll** [comment]
@MuriLOCO I am afraid that's not helping. If you want us to investigate anything, we need to have a way to reproduce the problem. Again, there isn't a "Spring Boot implementation of JavaMail". 

So please provide the sample Andy requested.

**Comment by wilkinsona** [comment]
> You can use the library JavaMail, adding as a Dependency in your POM file or you can use the spring-boot-starter-mail and use the SpringBoot implementation of JavaMail

As I said above, there's no such thing as a Spring Boot implementation of JavaMail. Using the starter vs adding dependencies to your pom will make little difference and the auto-configuration will likely be activated in either case.

I suspect the difference here is due to different versions of the JavaMail implementation but I can't tell for sure as you haven't provided enough information. If you want us to spend time investigating, please spend the time to provide the requested sample.

**Comment by MuriLOCO** [comment]
1 - Add the Dependecy:

dependencies {
	compile("org.springframework.boot:spring-boot-starter-mail")   
}

2 - Insert those items on "application.properties"

spring.mail.host = "HOST"
spring.mail.username = "USERNAME"
spring.mail.password = "PASS" 

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.socketFactory.port = 587
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFatctory
spring.mail.properties.mail.smtp.socketFactory.fallback = false;


Ok, so now I can @Autowired a JavaMailSender bean and use.

Now I am using Postfix as a Relay-Server which all the credentials are inside the Postfix, not in the "application.properties" anymore. But anyway, I am OBLIGED to put the "spring.mail.password" even if I put ANY string, does not need to be the password because POSTFIX is not using the password provided by JavaMailSender but if I don't put a PASSWORD the application will fail at initialization saying that I have an Authentication problem. If I use PURE JavaMail, not the SpingBootImplementation I am able to do not input a password and it works fine. 

This is the issue which I found, it is not critical but is still an issue.

If you need more details please be more specific.

**Comment by wilkinsona** [comment]
@MuriLOCO Unfortunately, that's still not what I asked for. We need to see a complete sample that shows the configuration that requires a password and the configuration that does not require a password. Please provide the sample as a zip file (you can attach it to the issue) or Git repository.

**Comment by MuriLOCO** [comment]
@wilkinsona I am sorry, I don't usually report issues. I created an example of the implementation in the zip files attached. Note that using JavaMail I have a Bean implementation and using Spring-Boot-Starter-Mail I have my configurations on my "application.properties" which I need to Autowire a JavaMailSender to be able to use.

I am sorry I am not being clear enough, as I said I don't have much experience in reporting issues, I just wanted to contribute with the SpringBoot community.

Thank you
[JavaMailIssue.zip](https://github.com/spring-projects/spring-boot/files/624900/JavaMailIssue.zip)

**Comment by wilkinsona** [comment]
@MuriLOCO Thanks, but we're still not there yet. Neither of the Java files in the zip appears to be using Spring Boot.

What I'd really like to see is two small Spring Boot applications. One that shows things working without a password when you use "PURE JavaMail" and one that shows things failing without a password when you use Spring Boot's auto-configuration. In each case, an application created using `start.spring.io` would be a good starting point. Just add as little as possible to recreate your problem, zip the application back up again, and attach it here.

**Comment by MuriLOCO** [comment]
Ok, I will do it and upload. I just can't do right now. Don't close the topic yet :)

**Comment by MuriLOCO** [comment]
Hi, I was building the example files and actually I figured out what was wrong. Actually the problem was with me, I am so sorry.

The thing is:

If I write those information here:

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.socketFactory.port = 587
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFatctory
spring.mail.properties.mail.smtp.socketFactory.fallback = false;

I need to input a password, but this was a mistake because Postfix has all those information, so If it only specify like this:

spring.mail.host = localhost

and nothing else, it does not ask for a password and it works fine. I am sorry to take your time when actually the problem was in my code. I was only trying to help :-) Have a good day.
