### ISSUE TITLE
Entries from `META-INF` duplicated in FatJARs

### ISSUE THREAD

**Issue by jerrinot** [spring-projects/spring-boot#7550]
Hi,

There is a [project](https://github.com/bmudda/hazelcast-docker-spring-test) with Spring Boot 1.4.2.

The project has a dependency on Hazelcast. When Boot creates a [FatJAR](https://github.com/bmudda/hazelcast-docker-spring-test/blob/897db5a9c4a7a11de01071803bc71c2757fce9e7/build.gradle#L65) then `META-INF/services` entries from [hazelcast.jar](https://github.com/hazelcast/hazelcast/tree/ff826d352a1240d34b7e084b87872a1f9d48aea4/hazelcast/src/main/resources/META-INF/services) are copied into the `META-INF/services` of the FatJAR + the same entries are kept inside hazelcast.jar which is copied into `BOOT-INF/lib` of the FatJAR. 

When Hazelcast is starting it finds the duplicates and [fails to start](https://github.com/hazelcast/hazelcast/issues/9353). 

Is this duplication of entries from `META-INF` an intentional behavior?

**Comment by philwebb** [comment]
I think something else in your build is doing this. If I add the following to your `build.gradle`

```
bootRepackage {
    enabled = false
}
```

The `repackage` task doesn't run but service entries are still in the resulting jar:

```
unzip -l build/libs/hazelcast-docker-spring-test-1.0-RC1.jar | grep "META-INF/services"                                                                                                                                            ✭
        0  11-17-16 09:33   META-INF/services/
     1319  11-17-16 09:33   META-INF/services/com.hazelcast.DataSerializerHook
      277  11-17-16 09:33   META-INF/services/com.hazelcast.PortableHook
       44  11-17-16 09:33   META-INF/services/com.hazelcast.instance.NodeExtension
       71  11-17-16 09:33   META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory
       45  11-17-16 09:33   META-INF/services/javax.cache.spi.CachingProvider
       39  10-13-16 20:47   META-INF/services/com.fasterxml.jackson.core.JsonFactory
       42  02-17-16 16:15   META-INF/services/javax.validation.spi.ValidationProvider
       44  10-14-16 03:51   META-INF/services/com.fasterxml.jackson.core.ObjectCodec
       57  11-07-16 21:16   META-INF/services/javax.servlet.ServletContainerInitializer
      256  04-04-16 20:38   META-INF/services/org.apache.commons.logging.LogFactory
      837  10-06-16 21:16   META-INF/services/javax.servlet.ServletContainerInitializer
      844  10-06-16 21:16   META-INF/services/javax.websocket.ContainerProvider
      865  10-06-16 21:16   META-INF/services/javax.websocket.server.ServerEndpointConfig$Configurator
```

**Comment by jerrinot** [comment]
@philwebb you were right, it was caused by a buggy Gradle script as @vpavic identified!
