### ISSUE TITLE
Remove thymeleaf-layout-dialect from spring-boot-starter-thymeleaf

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7557]
As far as I can tell Groovy's optional (all my samples work without it), so it seems like a bad idea for it to be included in everyone's app if they don't need it.

**Comment by dsyer** [comment]
UPDATE: actually the layout dialect seems to need it (see for example spring-boot-sample-web-ui). We could ditch that now that thymeleaf 3 has more flexible fragment rendering.

**Comment by wilkinsona** [comment]
So we could consider doing this as part of upgrading to Thymeleaf 3 (see #7450)

**Comment by wilkinsona** [comment]
And by "this" I mean remove `thymeleaf-layout-dialect` from `spring-boot-starter-thymeleaf` so that people have to opt into using it
