### ISSUE TITLE
Use Http11Nio2Protocol for Tomcat were available

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#7559]
Is there any particular reason to be using `Http11NioProtocol` instead? 
It looks like it should be a simple change to update to the newer one if Java 8 is detected.

**Comment by wilkinsona** [comment]
> Is there any particular reason to be using Http11NioProtocol instead?

Yes. It's been around longer and is, therefore, considered to be more robust. There's also no real performance difference between the two. See [this thread](http://thread.gmane.org/gmane.comp.jakarta.tomcat.user/242253) from the Tomcat Users list. It's from last year, but I haven't heard anything that contradicts what's said there.
