### ISSUE TITLE
Unit Tests failing using surefire:test but not eclipse or mvn test

### ISSUE THREAD

**Issue by hghammoud** [spring-projects/spring-boot#7568]
Hello,

I am currently working on a multi-modules project where i place the application.yml in the config module and package it as a jar. The Jar is in the dependencies for all the other modules. I never had this problem using spring boot 1.3.7. Since i migrated to 1.4.2, i am encountering this issue.

My JUnit tests work perfectly in **eclipse** even using **mvn test** command. However, the **mvn install** or **mvn surefire:test** command fail to load the application.yml from the jar file and hence all the @value are empty and the application doesnt load.

Any idea what might be the cause of this issue?

thank you

**Comment by wilkinsona** [comment]
Duplicates #7451
