### ISSUE TITLE
Please add jsoup dependency

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-boot#7574]
_jsoup_ is an optional dependency of Hibernate Validator (since 4.2)

It is for the `@SafeHtml` validation.

https://docs.jboss.org/hibernate/validator/4.2/api/org/hibernate/validator/constraints/SafeHtml.html

http://docs.jboss.org/hibernate/validator/4.2/reference/en-US/html_single/#table-custom-constraints

**Comment by wilkinsona** [comment]
I don't think we should add this. We need to draw the line somewhere with the modules for which we provide dependency management and I think optional dependencies of third-party dependencies should be over that line.

**Comment by sdavids** [comment]
I agree with "I think optional dependencies of third-party dependencies should be over that line" but:

_@SafeHtml_ is **very** useful.

We use it to prevent JavaScript/XML/HTML/*-injection issues.

We use _@SafeHtml(whitelistType=NONE)_ on almost all String-properties of our Entities and Form-Beans -- that way stuff like "<script>alert(123)</script>" or "<!--" does not get into our database.

Ideally, it would even be mentioned on https://spring.io/guides/gs/validating-form-input/

**Comment by xenoterracide** [comment]
I'll plus 1, we use Jsoup and being able to safely protect against javascript injection is a huge thing. 

A side note though from recent expreriences, and having not used `@SafeHtml`, is I would definitely check to ensure that input like `<foo bar` still got into your database. As we we found Jsoup would clean that if you didn't escape `<>&` first. and in our case `<>&` are all considered valid and commonly used characters (of course `<script` isn't, our we have scientists inputting data so mathematical and scientific notations)

**Comment by wilkinsona** [comment]
We've decided not to do this for the reason I outlined above. Just to be clear, please note that Spring Boot not having dependency management for JSoup does not prevent you from using it with Spring Boot. You'll just have to specify a version when you declare the dependency.
