### ISSUE TITLE
Offer a way to easily create a ConversionService that matches the one Spring Boot uses internally

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-projects/spring-boot#758]
I have a use case of adding my own Converters. I was hoping to declare a ConversionService field and have it autowired in based on my implemented Converter's. I notice that the ConfigurationPropertiesBindingPostProcessor.getDefaultConversionService() does a similar thing but it is only for its class. For now I have this:

```
    @Bean
    public ConversionServiceFactoryBean conversionService() {
        ConversionServiceFactoryBean factoryBean = new ConversionServiceFactoryBean();

        @SuppressWarnings("rawtypes")
        Set<Converter> converters = new HashSet<Converter>();
        converters.add(new MyCustomConverter());
        converters.add(new MyOtherCustomConverter());
        factoryBean.setConverters(converters);

        return factoryBean;
    }
```

Thanks

**Comment by Raniz85** [comment]
+1

**Comment by ptahchiev** [comment]
+1

**Comment by caneraydinbey** [comment]
+1

**Comment by rajjaiswalsaumya** [comment]
I was searching for something and came to this thread and got confused after looking to http://stackoverflow.com/questions/35025550/register-spring-converter-programmatically-in-spring-boot If converters could be registered the way mentioned on stackoverflow, then was the autoconfiguration for Conversion Service needed ?

**Comment by philwebb** [comment]
We should consider `@ConfigurationPropertiesBinding` when we look at this.

**Comment by snicoll** [comment]
I have a feeling that exposing a `ConversionService` bean is going to bring a number of issues and I rather would prefer to expose a `ConversionServiceBuilder` that you can inject in code and/or configuration to expose what matches your expectations.

By  default, the builder would match the one that Spring Boot uses internally but additional converters could be added programmatically.

**Comment by wilkinsona** [comment]
2.0 now contains a new `ApplicationConversionService` designed for direct instantiation that is configured by default with converters and formatters appropriate for most Spring Boot applications. See https://github.com/spring-projects/spring-boot/issues/12095.
