### ISSUE TITLE
spring.datasource.tomcat.* properties does not work.

### ISSUE THREAD

**Issue by casparcao** [spring-projects/spring-boot#7583]
I found the **spring.datasource.tomcat.*** connection pool properties (such as **spring.datasource.tomcat.test-on-connect=true**) does not work when i try to use tomcat jdbc pool. 
however spring.datasource.test-on-connect=true worked. 
It's noncompliance to the reference description.
![image](https://cloud.githubusercontent.com/assets/5925561/20953458/e5543546-bc6e-11e6-8e35-46d8bae7ce34.png)
![image](https://cloud.githubusercontent.com/assets/5925561/20953560/991f0812-bc6f-11e6-84df-b13e0b5d8f1c.png)

**Comment by wilkinsona** [comment]
If you'd like us to spend some time trying to help you, you will have to spend some time describing your problem. A screenshot and "does not work" tells us very little. Please provide a small sample that reproduces the problem.

**Comment by kazuki43zoo** [comment]
Hi @casparcao, Which version do you use ? 1.3.x or under ?

**Comment by casparcao** [comment]
1.3.0.RELEASE

**Comment by kazuki43zoo** [comment]
`spring.datasource.tomcat.*` properties has been supported by 1.4.
For details see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#datasource-binding.

**Comment by casparcao** [comment]
@kazuki43zoo Oh~， Thank you for reminding me， yes, it's my fault. I read the 1.4.X reference docs, but use the 1.3.X release. Thank you.
