### ISSUE TITLE
Documentation is missing for how exactly PID_FOLDER/LOG_FOLDER variables initialized at Spring Boot startup script

### ISSUE THREAD

**Issue by maximkir** [spring-projects/spring-boot#7585]
According to documentation, the **PID_FOLDER/LOG_FOLDER** variables, which can be part of the environment or located at the config file, specify the root folder for process pid / logs folder respectively.

I inspected the the embedded launch.script that sets those variables:

```
# Initialize PID/LOG locations if they weren't provided by the config file
[[ -z "$PID_FOLDER" ]] && PID_FOLDER="{{pidFolder:/var/run}}"
[[ -z "$LOG_FOLDER" ]] && LOG_FOLDER="{{logFolder:/var/log}}"
! [[ "$PID_FOLDER" == /* ]] && PID_FOLDER="$(dirname "$jarfile")"/"$PID_FOLDER"
! [[ "$LOG_FOLDER" == /* ]] && LOG_FOLDER="$(dirname "$jarfile")"/"$LOG_FOLDER"
! [[ -x "$PID_FOLDER" ]] && PID_FOLDER="/tmp"
! [[ -x "$LOG_FOLDER" ]] && LOG_FOLDER="/tmp"
```

As I understand, the first two lines sets the variables to /var/run & /var/log in case no definition found not in environment nor in configuration file (which is stated at the documentation as default values).

The next 2 lines aren't clear to me, in case the variable set different that some values the folder will be set relatively to jar file location. What those values? Please add more detailed documentation.

**Comment by philwebb** [comment]
Those "next 2 lines" lines were added in 24f8c737fb4f543e70741f42916128274c3f5021. It's using pattern matches to find out if the path is relative or not. i.e. if `$PID_FOLDER` doesn't start with `/` then it's a relative path and we should consider it as location relative from the directory that contains the jar.

**Comment by philwebb** [comment]
I'm not sure there's much to be gained from adding that to the reference docs.
