### ISSUE TITLE
jvmArguments is ignored when fork is set to false

### ISSUE THREAD

**Issue by mtyurt** [spring-projects/spring-boot#7588]
For following pom file,

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>1.4.2.RELEASE</version>
    <configuration>
        <profiles>
            <profile>dev</profile>
        </profiles>
        <jvmArguments>-Dbase.dir=/Users/mt/dev/ops/maven-test</jvmArguments>
        <fork>false</fork>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

`null` is returned when I execute `System.getProperty("base.dir")` in the code. When I remove the `fork` configuration, the same property is set properly. I have read the documents that  the process is forked when `jvmArguments` or `agent` is specified, I somehow forgot the `fork` configuration and it took me quite a time to just remove the line. I expected `jvmArguments` to override `fork` configuration, or a simple error that would fail the build is also OK.

**Comment by SuperMohit** [comment]
When you do a fork, the process runs on separate JVM instance. Hence ur arguments are no longer visible.

**Comment by mtyurt** [comment]
I understand that. But the problem is I could see the `jvmArguments` configuration in pom.xml, I executed `run` successfully, in my code I couldn't find any system property I set before.

**Comment by philwebb** [comment]
>  I expected jvmArguments to override fork configuration, or a simple error that would fail the build is also OK

If you omit `<fork>` entirely the fact that `<jvmArguments>` are specified is enough to trigger forking. If you add `<fork>false</fork>` and `<jvmArguments>` you should see the following warning in your maven output:

```
Fork mode disabled, ignoring JVM argument(s) [...]
```

I'm not sure that there's much more that we could do here.
