### ISSUE TITLE
Remove unused protected method from SpringJtaPlatform

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#7592]
It doesn't look like the `hasTransactionManager` is used anywhere and can probably be removed.

**Comment by philwebb** [comment]
I wonder if an older version of Hibernate had that method and we kept it for compatibility. It doesn't appear to be in any versions that we currently support so it can probably go.

**Comment by ghostd** [comment]
(comment irrelevent with the the issue content)
@philwebb i think you have a typo in the milestone name: 1.50 RC1 -> 1.5.0 RC1

**Comment by wilkinsona** [comment]
Fixed, thanks @ghostd
