### ISSUE TITLE
CacheManagerJpaDependencyConfiguration is looking for a bean named "cacheManager" instead of type CacheManager

### ISSUE THREAD

**Issue by chengchen** [spring-projects/spring-boot#7594]
Hello,

Recently, I tried to add caffeine cache to our application with the help of spring-boot-starter-cache.
It works perfectly in your example: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache

However, it doesn't work when CacheManagerJpaDependencyConfiguration needs to be initialized. Because it's looking for a bean named "cacheManager" (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/CacheAutoConfiguration.java#L93), and CaffeineCacheConfiguration defines a CacheManager named "caffeineCacheManager". I believe the issue is more inside this CacheManagerJpaDependencyConfiguration, it should look for a bean typed CacheManager by default, and let you configure the choice when there are several.

This issue is also related to https://github.com/spring-projects/spring-boot/issues/6980, which for me is a workaround as well :)

Thank you very much in advance for the help!

**Comment by snicoll** [comment]
Thanks, I haven't realized that effect. I've reopened #6980 and will fix it in `1.4.3` rather than `1.5`.
