### ISSUE TITLE
JarLauncher configures the class path such that resources are found twice

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7595]
`JarLauncher` adds the URL for the root archive to the class path of `LaunchedURLClassLoader`. This means that the root archive is on the class path of both `LaunchedURLClassLoader` and its parent (the system class loader). This results in resources being found twice when they're found via `LaunchedURLClassLoader`.

**Comment by baspet** [comment]
moving to 1.4.3, our faces configuration broke resulting in something.jsp not found.
replacing just JarLauncher  with previous one solved the problem.
any help?

**Comment by wilkinsona** [comment]
@baspet If you believe you've found a bug, please open a new issue and provide a small sample project that reproduces the problem.
