### ISSUE TITLE
Upgrade to Jetty 9.4.0.v20161208

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#7599]
Note that `SessionManager` has been removed (changes are required in our support) and that spring-websocket support depends on [SPR-14940](https://jira.spring.io/browse/SPR-14940).

**Comment by snicoll** [comment]
We should probably provide at least forward computability in 1.5

**Comment by jhoeller** [comment]
Due to all the API refactoring in Jetty 9.4, support for both 9.3 and 9.4 is rather awkward. If you could streamline the arrangement in Boot 1.5 towards Jetty 9.4+, you'd have a much easier job.

Also, note that the Jetty team declared 9.3 as to be immediately superseded by 9.4:
> [jetty-9.3.x] this branch will be sunset once the first stable release of Jetty 9.4.0 is in the wild.
(http://jetty.4.x6.nabble.com/jetty-dev-Jetty-Release-Plan-for-9-4-x-and-10-0-x-tp4965500p4965522.html)

**Comment by bclozel** [comment]
The current arrangement seems to support Jetty 8/9.2/9.3.

**Comment by jhoeller** [comment]
The EOL'ed 8 still.. oh well. I see some reflection madness coming your way ;-)

At least in Boot 2.0, you'll finally be able to raise to Jetty 9.4+. Light at the end of the tunnel!

**Comment by philwebb** [comment]
I'm experimenting with this to see what's involved.

**Comment by bclozel** [comment]
I'm already working on it but feel free to take it from there.
The biggest changes I've noticed so far are about the session management overhaul. You'll find more details about this [here|https://www.eclipse.org/jetty/documentation/current/session-management.html]. Some reflection is required to support <9.4. The websocket support should be working with the latest Framework support, but you really need to exercise the websocket session to make sure of that.

**Comment by philwebb** [comment]
I have the server changes complete but our tests are failing due to https://github.com/eclipse/jetty.project/issues/1202
