### ISSUE TITLE
Simplify HealthMvcEndpoint security

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#7604]
With the introduction of the `MvcEndpointSecurityInterceptor`, the `HealthMvcEndpoint` does not need to look for the presence of Spring Security to determine whether to expose full health details. Health details can be exposed in two cases:

1. If the `request.isUserInRole()` returns true
2. If management security is entirely disabled.

**Comment by snicoll** [comment]
Duplicates #7852
