### ISSUE TITLE
Set failure message on response from MvcEndpointsSecurityInterceptor

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#7605]
In case of a 401 or 403, the appropriate error message needs to be set.

**Comment by philwebb** [comment]
As @dsyer pointed out on Slack it would be even better would be if we could trigger the `ErrorController` in the same way that Spring Security does.

**Comment by philwebb** [comment]
I reworked the message a bit so that it doesn't leave info back to the client. Details of what property to set are now only recorded in the log.
