### ISSUE TITLE
Bug Report: Jackson2ObjectMapperBuilderCustomizer and spring-web dependency

### ISSUE THREAD

**Issue by afaulconbridge** [spring-projects/spring-boot#7610]
The Jackson2ObjectMapperBuilderCustomizer interface uses the Jackson2ObjectMapperBuilder class. But it is easy to use Jackson2ObjectMapperBuilderCustomizer without importing org.springframework:spring-web which contains Jackson2ObjectMapperBuilder (e.g. in my case if your separating the model to a different maven sub-module from the spring data repositories etc). This gives very unclear warnings relating to compiled code references and it is not documented that importing org.springframework:spring-web is needed to use Jackson2ObjectMapperBuilderCustomizer.

Tested with Spring-boot 1.4.0.RELEASE & 1.4.1.RELEASE & 1.4.2.RELEASE &  2.0.0.BUILD-SNAPSHOT

**Comment by wilkinsona** [comment]
> This gives very unclear warnings relating to compiled code references

That sounds like a function of your IDE to me. Using Eclipse I get two errors that I think are pretty clear:

> The project was not built since its build path is incomplete. Cannot find the class file for org.springframework.http.converter.json.Jackson2ObjectMapperBuilder. Fix the build path then try building this project
> The type org.springframework.http.converter.json.Jackson2ObjectMapperBuilder cannot be resolved

Alternatively, compiling with Maven on the command line produces:

> [ERROR] /Users/awilkinson/tmp/gh-7610/src/main/java/com/example/Gh7610Application.java:[18,47] cannot find symbol
>    symbol: class Jackson2ObjectMapperBuilder

The javadoc for `Jackson2ObjectMapperBuilderCustomizer` also links to `Jackson2ObjectMapperBuilder`.

I don't think we should get into the business of documenting which module a particular class is in. This would be a big undertaking and would also have an ongoing cost as we'd have to ensure that it was kept up-to-date.

You can also configure your IDE to suggest modules to import when a class is not on the classpath. For example, Spring Boot's Eclipse tooling will suggest an import of `spring-boot-starter-web`. I believe IntelliJ IDEA has similar functionality.
