### ISSUE TITLE
WebEnvironment.RANDOM_PORT does not influence management.port

### ISSUE THREAD

**Issue by samized** [spring-projects/spring-boot#7611]
With the new SpringBootTest annotation we use the WebEnvironment.RANDOM_PORT to start the test-server with a random port. Unfortunately this doesn't influence the management.port which leads to `PortInUseException` during testing.

My current workaround for this looks like this
```
@SpringBootTest(
    classes = {
        RunApp.class,
        EmbeddedDatabaseConfiguration.class
    },
    webEnvironment=WebEnvironment.RANDOM_PORT,
    properties = { "management.port=0" } // Fix to use also random management port
)
```

**Comment by vpavic** [comment]
Looks like a duplicate #4424, considering `WebIntegrationTest` was deprecated in favor of `SpringBootTest`.

**Comment by philwebb** [comment]
Indeed. Thanks @vpavic. Let's consider this a duplicate of #4424 and use that one to discuss adding support to the new annotation.
