### ISSUE TITLE
set spring.jpa.properties.hibernate.id.new_generator_mappings=true by default

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#7612]
Hibernate has a tendency to throw these warnings in Hibernate 5

```
[WARN ] [11:58:26] [localhost-startStop-1] orm.deprecation - HHH90000014: Found use of deprecated [org.hibernate.id.SequenceGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
```

setting `spring.jpa.properties.hibernate.id.new_generator_mappings=true` will stop it and is good for new projects, and I believe fine for old projects in most cases. I believe this should be the default in the next major version of Spring Boot's autoconfig, and probably called out in upgrade documentation.

**Comment by wilkinsona** [comment]
I think this change has broken DataJpaTestIntegrationTests testEntityManagerPersistAndGetId

**Comment by mbhave** [comment]
@wilkinsona was about to fix it by adding `this.entities.flush()` but I guess this works too.

**Comment by wilkinsona** [comment]
That might be better, I don't know really. Feel free to change it to call `flush()` if you prefer.

**Comment by mbhave** [comment]
Reopening to fix the `SampleDataJpaApplicationTests`

**Comment by mbhave** [comment]
Reverting the change for now till we figure out what the best way to fix the tests is.

**Comment by philwebb** [comment]
I wonder if we should add the `spring.jpa.hibernate.use-new-id-generator-mappings=false` property to `application.properties`? I have a feeling that the samples now won't run outside of the tests.

The other option is we look at somehow updating the `insert.sql` file to trigger the new sequence generators.

**Comment by mbhave** [comment]
you're right, I'll give updating `insert.sql` a shot.

**Comment by snicoll** [comment]
It looks like the flyway sample is failing but the build doesn't. Could it be related to this issue?

**Comment by mbhave** [comment]
yes I believe it is. I have a fix for it on this [here](https://github.com/mbhave/spring-boot/commit/447950175e00e5f1ced8c0f30417a5a961162131). I wasn't totally sure about the best way to fix the samples, so waiting for a review to merge it in.

**Comment by LaurenceMommers** [comment]
Currently the documentation still states that the property defaults to false for backwards compatibility.
This change also leads to some weird behavior where by default a sequence table is used in mysql instead of the autoIncrement feature [HHH-11014](https://hibernate.atlassian.net/browse/HHH-11014)

`		/**
		 * Use Hibernate's newer IdentifierGenerator for AUTO, TABLE and SEQUENCE. This is
		 * actually a shortcut for the "hibernate.id.new_generator_mappings" property.
		 * When not specified will default to "false" for backwards compatibility.
		 */`
[line 157 of JpaProperties.java](https://github.com/spring-projects/spring-boot/blob/3fb86b261ea6b88de956c52968a759b99610c4ca/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/JpaProperties.java#L181)

**Comment by wilkinsona** [comment]
Thanks for spotting that, @LaurenceMommers. I've opened https://github.com/spring-projects/spring-boot/issues/11064.
