### ISSUE TITLE
SpyBean does not necessary spy on the primary bean when there are 2 instance

### ISSUE THREAD

**Issue by lsiu** [spring-projects/spring-boot#7621]
When there are 2 beans and one marked as `@Primary`, in normal auto-wiring, the Primary bean is used. However, in case of test code autowired via `@SpyBean`, this is not necessary the case. This cause unexpected behavior when using the spybean to mock responses on methods.

I have created a [sample project](https://github.com/lsiu/testspybean) which illustrate this. See the [test class](https://github.com/lsiu/testspybean/blob/master/src/test/java/com/github/lsiu/TestSpybeanApplicationTests.java) and the [same code](https://github.com/lsiu/testspybean/blob/master/src/main/java/com/github/lsiu/TestSpybeanApplication.java)

Looking more into the details. It appear which bean is spied on depends on the order the beans are returned from the method [`getExistingBeans` in MockitoPostProcessor](https://github.com/spring-projects/spring-boot/blob/e0dfff2b23faad006789bae4050e618914f8e40c/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L248) (the last bean return ends up being the one is spied on, since [the loop in `registerSpies`](https://github.com/spring-projects/spring-boot/blob/e0dfff2b23faad006789bae4050e618914f8e40c/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L316) essential overwrite previous spy registered). I would expect we always spy on the bean marked with `@Primary` similar to the normal auto-wiring behavior.

**Comment by philwebb** [comment]
Thanks for the sample project. There's certainly an issue here but I'm not sure that it's directly related to `@Primary`. The `MockitoPostProcessor` should throw an exception because there is more than one candidate bean, however, the `field` is `null`. It appears that a new `DefinitionsParser` is being created and the `field` mappings are being lost.

**Comment by lsiu** [comment]
Throwing an error is not an idea solution, since in production code, we do allow multiple beans and resolve using the @Primary bean annotation.

Resolving the Bean to mock or spy or should be same as how it is done in the production code. Is it possible to just reuse the same code? For example, I see [`DefaultListableBeanFactory.determineAutowireCandidate`](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java#L1302) is use to resolve when there are multiple autowire candidate.

I have not fully investigate this yet, but I would think instead of having its own logic to "pick" the bean, it should delegate to the `BeanFactory` to resolve it.

**Comment by philwebb** [comment]
@lsiu I see your point, but it's more than just picking the bean. It also needs to update the bean definition in the context. Let me have a think about the options.

**Comment by lsiu** [comment]
@philwebb - I have created 2 tests that illustrate the problem and a proposed fix with the above commit (9f5c777). It may not be the best place to fix it, but it does fix the issue and doesn't break the other tests.

**Comment by philwebb** [comment]
Thanks @lsiu! We discussed this a little on our regular team call and we think using the `@Primary` bean as the spy source is the best option.
