### ISSUE TITLE
Essential Property for Health Indicators

### ISSUE THREAD

**Issue by matias2681** [spring-projects/spring-boot#7626]
It would be nice to add an optional `essential` property to every configuration for a health indicator. This property will allow users to indicate if the service is `DEGRADED` instead of `DOWN`. This will help in some cases where for example, a service use the database occasionally (but it doesn't depend of it 100% of the time) and if the connection to the db fails the overall status of the service will be `DEGRADED` instead of `DOWN`. 

When `essential=true` that health indicator will behave as now. If `essential=false` the behavior for that health indicator will pass to `DEGRADED` instead of `DOWN`.

Probably the default behavior should be `essential=true`.

**Comment by philwebb** [comment]
Thanks for the suggestion but after some careful consideration we've decided that we'd prefer to keep things as they are. The current system is easy to understand and if non-essential `HealthIndicators` are needed the `HealthAggregator` interface can be used to implement a custom strategy.
