### ISSUE TITLE
Switch from Aether to Maven Resolver

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7627]
See https://projects.eclipse.org/projects/technology.aether/reviews/termination-review

Release tracking here:
https://issues.apache.org/jira/browse/MRESOLVER/fixforversion/12338256/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Comment by wilkinsona** [comment]
Moving from Aether to Maven Resolver also requires moving from Maven's Aether Provider to Maven's Maven Resolver Provider. Unfortunately, the latter depends on Guava which is 2.4MB. This is the biggest contributor to the CLI zip ballooning from 9.77MB to 13MB.

I'm not sure what we should do here as we seem to have two options and neither of them is very appealing:

1. Move to Maven Resolver and make the CLI zip 13MB
2. Stick with Aether and depend on something that, AFAIK, is no longer maintained.

**Comment by wilkinsona** [comment]
On closer inspect Maven's Aether Provider [has required Guava since 3.2.3](https://github.com/apache/maven/commit/61c374042560b2dc21c294886615931a888df597). We're currently using 3.2.1 so we're avoiding Guava more by luck than good measure.

**Comment by wilkinsona** [comment]
I've opened https://issues.apache.org/jira/browse/MNG-6306 to see if Maven Resolver Provider can drop its Guava dependency.

**Comment by michael-o** [comment]
Guava will be dropped by me this day...

**Comment by michael-o** [comment]
Issue has been fixed.

**Comment by wilkinsona** [comment]
@michael-o Thanks!

**Comment by philwebb** [comment]
Not sure if we'll have a `maven-resolver` release by then, but I'll stick this in RC1 since it would be nice to migrate for 2.0.

**Comment by slachiewicz** [comment]
New maven-resolver version 1.1.1 released by Maven Team 2017-02-15

**Comment by wilkinsona** [comment]
@slachiewicz That doesn't help us unfortunately. We need a release of `maven-resolver-provider` that contains [this change](https://github.com/apache/maven/commit/866582d296ed80f36f33e5293cd07647185e0e43#diff-d1e0854f3ab131d59607295341502b7d) that you authored. It looks like 3.5.3 has been tagged, but it's not available in Maven Central yet.

**Comment by philwebb** [comment]
Looks like [1.1.1](https://issues.apache.org/jira/projects/MRESOLVER/versions/12341378) has been released.

**Comment by michael-o** [comment]
Anyhow I can help?

**Comment by philwebb** [comment]
@michael-o Thanks for the offer but I think we've got everything we need now.

**Comment by philwebb** [comment]
There's unfortunately still a Guava dependency, but it appears to be unnecessary. I've raise https://issues.apache.org/jira/browse/MNG-6475
