### ISSUE TITLE
Missing dependency management for javax.validation:validation-api

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-boot#7641]
I've had issues with `javax.validation:validation-api` dependency - for some reason in my project it was resolved as `1.0.0.GA` instead of `1.1.0.Final` (expected by `org.hibernate:hibernate-validator`).

As of now I've added this dependency locally:
```xml
    <properties>
        ...
        <javax-validation.version>1.1.0.Final</javax-validation.version>
        ...
    </properties>

    <dependencyManagement>
        <dependencies>
            ...
            <dependency>
                <groupId>javax.validation</groupId>
                <artifactId>validation-api</artifactId>
                <version>${javax-validation.version}</version>
            </dependency>
            ...
        </dependencies>
    </dependencyManagement>
```
Is it reasonable to add the same to Spring Boot?

**Comment by wilkinsona** [comment]
Yeah, I think it's reasonable. We already have dependency management for various other Java EE APIs such as JTA and Caching.

**Comment by stepio** [comment]
Ok, I'll do pull request
