### ISSUE TITLE
Control Tomcat JMX ObjectNames from Spring Boot

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7642]
Spring Boot registers a bunch of MBeans and lets you control the object names in a standard Spring JMX way (plus configuration properties like `spring.jmx.default-domain`), but Tomcat registers a load of beans with the domain "Tomcat" and this is not configurable by the user. It causes issues when there are multiple Tomcat containers in the same JVM. Oddly Tomcat doesn't complain when it starts up, only when it stops, and the second container to stop finds that all its MBeans were removed by the first one. This only shows up as an exception in Boot 1.4, but it clearly is a problem going back to earlier versions (there is no exception, but the MBeans are still missing).

**Comment by dsyer** [comment]
Actually `TomcatEmbeddedServletContainer` already tries to control this, but it works by using a static counter to monitor the number of containers running. This fails when the containers are launched via different class loaders.

**Comment by dsyer** [comment]
Here's a workaround:

```
	@Bean
	public TomcatEmbeddedServletContainerFactory embeddedServletContainerFactory(
			Environment environment) {
		return new TomcatEmbeddedServletContainerFactory() {
			@Override
			protected void prepareContext(Host host,
					ServletContextInitializer[] initializers) {
				host.getParent().setName(environment
						.getProperty("server.tomcat.jmx.domain", "Tomcat-" + environment
								.getProperty("random.int(1000,10000)", "xxxx")));
				super.prepareContext(host, initializers);
			}
		};
	}
```

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
