### ISSUE TITLE
DatabaseDriver.UNKNOWN when using fromJdbcUrl for AS400

### ISSUE THREAD

**Issue by hepoiko** [spring-projects/spring-boot#7651]
I was trying to use the DatabaseDriver.fromJdbcUrl("jdbc:as400:.....") to obtain the DatabaseDriver.DB2_AS400

However it returns DatabaseDriver.UNKNOWN.

I have compared with the old version (from 1.3.x) that it has the different name to current version 

1.3.x : https://github.com/spring-projects/spring-boot/blob/bad8c1bee8e757ee3b144c1c7a046618f31d1287/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DatabaseDriver.java

1.4.2 : https://github.com/spring-projects/spring-boot/blob/7bb63238ab0f4c5975f0f5c26e0b468d4b31cd1c/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java

I wonder what is it the way I use it incorrectly or not.

Thanks in advance.

Chun

**Comment by snicoll** [comment]
I understand it works with 1.3 but doesn't work with 1.4? Is that what you're experiencing?

Looks like an unfortunate refactoring.

**Comment by hepoiko** [comment]
Thanks for the very prompt response, looking forward the fix. Thanks again

**Comment by snicoll** [comment]
You can try it out. Generate an app on start.spring.io with version 1.4.3.BUILD-SNAPSHOT
