### ISSUE TITLE
Provide an example of how to configure multiple datasources and configuration consumption

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#7652]
It seems that there are a couple of tricks needed to get a manual setup of multiple `DataSources` working nicely including the externalization of properties. Ideally the sample would show:

1. How to structure properties so that each `DataSource` has its own distinct configuration.
2. Show how to declare `@Bean` methods to that they pick up the configuration from the declared property sets.
3. Optionally (if possible and recommended), show how to share some of the properties declared (e.g. user and password) to avoid mistakes when configuration changes.

**Comment by philwebb** [comment]
Perhaps we can extend http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources

**Comment by olivergierke** [comment]
That's a nice find actually. When skimmed the docs, I quickly found http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-configure-datasource scrolled through it, reached the Spring Data JPA specific bits and thought that was it. I didn't even think there could be anything further below. Linking to the HowTo from the reference section would be very helpful.

**Comment by snicoll** [comment]
I am looking at building the sample and some things are bugging me. I can see others in the community are confused by it. 

Spring Boot advertizes that we can automatically detect the driver class name based on the URL and it will automatically provide an embedded URL if no url is provided. These are pretty interesting feature but we can't cleanly apply them when one wants to configure two datasources.

The main issue is that `DataSourceProperties` does it and it does more things: you can specify the jndi-name of the datasource (only used by the auto-configuration) and several attributes used to initialize the datasource. 

The main goal of such arrangement is to keep the auto-completion in the IDE for the custom namespaces. With the current design, a bunch of keys would be exposed that have no effect. I've start to [hack something in a branch](https://github.com/snicoll/spring-boot/commit/f4c800647beecf52cda445cfa4770f26136b11e9) and the end-result [is quite concise](https://github.com/snicoll/spring-boot/blob/f4c800647beecf52cda445cfa4770f26136b11e9/spring-boot-docs/src/main/java/org/springframework/boot/jdbc/TwoDataSourcesExample.java#L34) and only exposes the key that actually do something in practice.

Still, we're not there yet. `DataSourceAutoConfiguration` exposes a `DataSourceInitializer` almost unconditionally and the latter makes a weird link between `DatasourceProperties` and `DataSource`. We should fix that (typically not do anything at all if a custom `DataSource` is provided). 

All in all, I don't think that sample can go in `1.4`. ping @philwebb

**Comment by cptwunderlich** [comment]
As an affected user, I'd like to comment on this discussion. I was just trying to implement a feature using two datasources.

I found the documentation mentioned above, but it has two issues:

1. They use prefixes like 'datasource.primary', where the normal property is called spring.datasource.* (e.g., spring.datasource.initialize). So it looks like the resulting key would be 'spring.datasource.primary.*', but looking at other examples, it would be 'datasource.primary.datasource.*'?

2. There is one section called 'Configure Two DataSources' and later 'Use Two EntityManagers'. The latter references code from the first one. But if you try out the code like that, you'll find out that something else is missing.

In fact, the best source I've found, was a stackoverflow posting referencing the docs and this example: https://github.com/snicoll-demos/demo-multi-entity-managers

The docs should also mention, that when you configure an additional DataSource/EntityManager, the auto-configuration won't work anymore. I added a secondary DataSource+EntityManager like in the example, but now I get a warning "No bean named 'entityManagerFactory' available" and a follow-up Exception

**Comment by snicoll** [comment]
Thanks for the feedback.

I didn't get 1. If the prefix is `datasource.primary`, it is `datasource.primary` and none of the Spring Boot features apply since you're taking control over the configuration. It's a common principle in Spring Boot: if you configure things yourself, you are in control.

As of 2, I am actually keen on moving the sample from my repo to the main Spring Boot repo and reference it in the doc.

**Comment by cptwunderlich** [comment]
Ah, thanks. At first, I didn't even realize it was your example I found.

There seems to be duplicate issue: #3456

**Comment by snicoll** [comment]
Let's focus on showing how we can "reproduce" what Boot does for us (datasource properties, initializer, etc) and how an extra datasource can be added. #7942 will avoid a cast for the second datasource.
