### ISSUE TITLE
Call runners after ApplicationReadyEvent has been published

### ISSUE THREAD

**Issue by rupert654** [spring-projects/spring-boot#7656]
Spring Boot provides the very useful `ApplicationRunner` and `CommandLineRunner` for executing code immediately before the `SpringApplication.run` method finishes.

There are many articles and StackOverflow questions ([example 1](http://stackoverflow.com/questions/28199999/how-does-a-spring-boot-console-based-application-work), [example 2](http://stackoverflow.com/questions/39670535/when-is-my-business-code-actually-being-executed)) that advocate using these for the bulk of the logic within a Command Line application.

However, if you use one of these, then the "Started ApplicationName in X seconds" log message is output after the runners have finished. Additionally, the event `ApplicationReadyEvent` is called afterwards as well.

This implies that runners are only intended for initialisation work. You should not, in fact, be using them for work that should be considered part of _running_ the application and doing so is a misuse of their intended purpose.

Can we please have some clarity on the proper usage added to the documentation if this is indeed a misuse?

If it is not a misuse then can the runner execution get moved to after the `ApplicationReadyEvent`, and after the "Started" log message, to more clearly indicate that the application is already, in fact, ready, and now the runner execution is part of the application itself running?

**Comment by philwebb** [comment]
Thanks for raising this.

I think that they should probably happen after the `started` event, although that's not something we'll be able to do until Boot 2.0. I'll tag this for team discussion to see what others think.

**Comment by snicoll** [comment]
@wilkinsona this one has a side effect on a web application. If you use to run something in an `ApplicationRunner` to initialize something, then you may end up in a situation where the HTTP connector is started before the initializer completes. 

I think we need to make sure to update the release notes to:

1. Clearly describe that side effect
2. Provide alternatives (i.e. if you want to run something when everything has completed, _but_ before the connection actually starts

**Comment by wilkinsona** [comment]
IMO, an application runner shouldn't be used for initialisation. If you need to initialise something it should be done as part of application context refresh. If you need that initialisation to happen after something, then the standard dependency mechanisms offered by the Framework should be used. I'm struggling to think of a use case where a component's dependency would effectively be everything.

**Comment by frederikvanhoyweghen** [comment]
+1 on documenting that CommandLineRunner and ApplicationRunner should only be used for initialization work initialization and nothing more.
Found this out while testing spring-boot-admin. Clients just weren't registering with the admin server and it took quite a while to figure out that ApplicationReadyEvent just wasn't ever fired because of what we were doing inside a CommandLineRunner bean..

**Comment by snicoll** [comment]
@frederikvanhoyweghen this issue is closed so please do not comment here to suggest a change. Your use case is also quite specific to Spring Boot Admin so I'd rather ask there but if you have some ideas to generically improve the documentation, please create a separate issue.

**Comment by frederikvanhoyweghen** [comment]
Sorry, I didn't notice the issue was closed. I took it up with the spring boot admin maintainers, I'll create a separate issue if need be. Thanks!
