### ISSUE TITLE
Add support for Log4j2's ConfigurationFactory

### ISSUE THREAD

**Issue by mherz** [spring-projects/spring-boot#7658]
Hi,

within our current "normal" Spring applications we are using Log4j2 as logging framework and configuring it with the help of a [ConfigurationFactory](http://logging.apache.org/log4j/2.x/manual/customconfig.html). 

Now we started to use Spring Boot in some projects and since the ```Log4J2LoggingSystem``` class is only relying to File config, this doesn't work anymore. Even if we deploy the application as a war into a running Tomcat, the ```LoggingContext``` initialized via ```Log4jServletContainerInitializer``` gets more or less overriden by the ```LoggingContext``` provided via ```Log4J2LoggingSystem```.

So it would be nice to add Support for the ConfigurationFactory stuff within Spring Boot.

regards,
Markus

**Comment by wilkinsona** [comment]
Are you aware that you can disable Spring Boot's logging system so that you can configure Log4j2 using whatever mechanism you want? See [this section of the docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-log-configuration) for details.

**Comment by mherz** [comment]
Yes, I'm aware of this fact and actually this is exactly what we are doing currently. Since we are currently deploying the application only as a war file, it's enough for us to disable Spring Boots logging system. 

But I think it would be nice to add this directly to Spring Boots Log4j support, because within a "normal" Tomcat I wouldn't have to deal with it in this way, because its supported by Log4s normal initialization mechanism with the ```@Plugin``` annotation. So if there is already support for Log4j, I think it would be nice to support the configuration possibilities which are documented by Log4j.

If I get some time, I might try to add the support by myself and create an according pull request.

**Comment by thombergs** [comment]
I might give this one a try. 

To clarify the requirements: we want the `Log4JLoggingSystem` to back off when a Log4J `ConfigurationFactory` as described in the [Log4J docs](http://logging.apache.org/log4j/2.x/manual/customconfig.html) is available. In this case, we want to let Log4J do it's thing, right?

**Comment by wilkinsona** [comment]
I'm not sure that'll work. Log4j itself has four `ConfigurationFactory` implementations available out of the box:

- `JsonConfigurationFactory`
- `PropertiesConfigurationFactory`
- `XmlConfigurationFactory`
- `YamlConfigurationFactory`

I think that means that we can't just back off. Reading the description again from @mherz, I'm not exactly sure what form they expected this enhancement to take. I'm struggling to think of an approach that, fundmentally, is any different to using the system property to disable the logging system.

@mherz can you please expand on what you had in mind?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
