### ISSUE TITLE
Autoconfig for org.h2.server.web.WebServlet when using in memory databse

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#766]
It would be nice to automatically add an endpoint for org.h2.server.web.WebServlet when it is available on the classpath and using an in memory database.

**Comment by snicoll** [comment]
@philwebb can we review this with the developer tools story (I know we flip the templates caching already)

**Comment by philwebb** [comment]
Agreed, this would now be nice addition.

**Comment by wilkinsona** [comment]
I have the basics of this working, however it's proving more trouble than it's worth. Some problems that I've encountered:

 - It doesn't work out-of-the-box with basic auth. The console serves three empty frames.
 - Detecting the use of an embedded database is non-trivial. If the user has tomcat-jdbc, HikariCP, etc on the classpath, we'd have to reach inside the pool somehow to get the actual datasource. For databases that can be embedded or standalone (Derby, H2, etc) we'd then also have to figure out how it's being used.

In light of the above, we discussed this today and decided it's not worth implementing. For those that want to add the console to their own applications, they can do so with a dependency on H2 and four lines of code:

```java
@Bean
public ServletRegistrationBean h2WebConsole() {
    return new ServletRegistrationBean(new WebServlet(), "/h2-console/*");
}
```

**Comment by rwinch** [comment]
@wilkinsona Thanks for the feedback. Can we please consider reopening this?

> It doesn't work out-of-the-box with basic auth. The console serves three empty frames.

This is due to Spring Security's CSRF protection and the X-FRAME-OPTIONS being set. We could easily tell Spring Security to ignore this endpoint.

> Detecting the use of an embedded database is non-trivial. If the user has tomcat-jdbc, HikariCP, etc on the classpath, we'd have to reach inside the pool somehow to get the actual datasource. For databases that can be embedded or standalone (Derby, H2, etc) we'd then also have to figure out how it's being used.

How about if we toggle this on using the same logic we use for the dev tools being added to Boot 1.3?

**Comment by wilkinsona** [comment]
> How about if we toggle this on using the same logic we use for the dev tools being added to Boot 1.3?

That's what I did in my implementation that convinced me this was more trouble than it's worth.

The use of the dev tools doesn't may it any easier to figure out whether or not an in-memory database is being used. A connection pool may well still be involved and we'd have the same problem with identifying an embedded database as I described above.

> Can we please consider reopening this?

I think that's unlikely without something changing.

In addition to the problems I've already described, another problem is that a user may want to use the H2 console with embedded Derby or embedded HSQLDB. At that point, there are multiple embedded databases on the classpath which significantly complicates auto-configuration of a `Datasource`.

The conclusion that we came to is that supporting the H2 console automatically, i.e. add it to the classpath and it just works if you're using an in-memory database, is more trouble and effort than it's worth.

One thing that could change is to drop the requirement that the console is only enabled when an embedded database is being used. We may be able to tackle this if we can convince ourselves that if would be reasonable to enable the console when the following conditions are met:

 - H2 is on the classpath
 - `spring-boot-devtools` is on the classpath
 - It's a web application

**Comment by rwinch** [comment]
@wilkinsona Thanks for the reply.

> One thing that could change is to drop the requirement that the console is only enabled when an embedded database is being used. We may be able to tackle this if we can convince ourselves that if would be reasonable to enable the console when the following conditions are met:
> * H2 is on the classpath
> * spring-boot-devtools is on the classpath
> * It's a web application

This seems like a reasonable proposal to me. The issue was created before we had devtools, so triggering based on in memory database was the best idea I had at the time. Although not clear, triggering based on the conditions you mentioned above is what I had in mind when I said:

> How about if we toggle this on using the same logic we use for the dev tools being added to Boot 1.3?

**Comment by rwinch** [comment]
@wilkinsona Thanks for reconsidering and tackling this issue!

**Comment by php-coder** [comment]
Great! Thanks!

**Comment by hendisantika** [comment]
I am using Spring Boot 1.5.3.
It is said that is error.
```
[INFO] /Users/hendisantika/Documents/IdeaProjects/SpringScala/src/main/scala:-1: info: compiling
[INFO] Compiling 8 source files to /Users/hendisantika/Documents/IdeaProjects/SpringScala/target/classes at 1493939006294
[ERROR] /Users/hendisantika/Documents/IdeaProjects/SpringScala/src/main/scala/org/springscala/config/H2Config.scala:8: error: object h2 is not a member of package org
[ERROR] import org.h2.server.web.WebServlet
[ERROR]            ^
[ERROR] /Users/hendisantika/Documents/IdeaProjects/SpringScala/src/main/scala/org/springscala/config/H2Config.scala:15: error: type mismatch;
[ERROR]  found   : javax.servlet.annotation.WebServlet
[ERROR]  required: javax.servlet.Servlet
[ERROR]     val registrationBean = new ServletRegistrationBean(new WebServlet)
[ERROR]                                                        ^
[ERROR] two errors found
```

How to solve this?
Thanks

**Comment by snicoll** [comment]
@hendisantika we don't use the tracker for questions. Join us on Gitter or ask on stackoverflow.

**Comment by hendisantika** [comment]
OK. Nevermind @snicoll .
I already solved the issue.

**Comment by javatrending** [comment]
@hendisantika would you please post here how you solved your problem. Its a common courtesy that you should always tell here for the benefit of the community. Thanks
