### ISSUE TITLE
dependencies removed from platform BOM, but not documented

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#7661]
`commons-configuration`, `tomcat-embed-logging-juli` were removed in Athens. I'm ok with this removal (we are currently removing it). It is not listed in the removed section and should be.

http://docs.spring.io/platform/docs/current/reference/htmlsingle/#upgrading-dependency-management-removed

**Comment by philwebb** [comment]
Thanks, but that's a platform issue and not related to Spring Boot.

**Comment by xenoterracide** [comment]
I thought platform bugs were tracked here?

**Comment by philwebb** [comment]
@xenoterracide The GitHub repo is [here](https://github.com/spring-io/platform), but looks like issues aren't open. @wilkinsona Is there an issue tracker for the platform?

**Comment by xenoterracide** [comment]
Thanks, I see issues there...?

**Comment by philwebb** [comment]
Oh yeah, missed that somehow :)
