### ISSUE TITLE
Spring Boot 1.3.X, 1.4.X Glassfish Deployment Test crush down the Glassfish

### ISSUE THREAD

**Issue by pnowy** [spring-projects/spring-boot#7662]
Hi,

it's some kind of issue for bug report (but I would say on Glassfish side in my opinion but I'm not sure) and ask for help because I'm out of ideas.

I have to deploy my Spring Boot application to Glassfish server 4.1.1 (customer requirement). When the problem appears I thought that is some specific application problem but that I've tried with official Spring Boot Glassfish Deployment Test application from maven (https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-deployment-test-glassfish/1.4.2.RELEASE) and I've had the same situation.

The Spring Boot war application crush down the entire Glassfish server. The issue has been reported to the Glassfish team and you will find the details what's going on there: https://java.net/jira/browse/GLASSFISH-21641

It would be great if you could take a look on that ticket because I believe it is close related to some Boot dependencies (what I could add that described there situation doesn't exist on "normal" Spring MVC application). Maybe you know any trick or solution for this situation because I'm looking a solution for it a couple of days and still Glassfish with Boot doesn't work.

I will be grateful for any hints how to run the Boot on Glassfish (I've been trying all solutions suggested on Stackoverflow with web.xml and metadata-complete, glassfish-web.xml and beans.xml but it also did not help with the simplest boot application).

**Comment by snicoll** [comment]
Sorry but the tracker is not the place to ask for that sort of thing. Working on the same issue in two different issues (this one and GLASSFIXH-21641) isn't going to help anyone. 

We are [on gitter](https://gitter.im/spring-projects/spring-boot) if you want to chat.
