### ISSUE TITLE
Maven Jar plugin 3.0.2 seems to have issues

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7663]
A new project generated from start.spring.io with Spring Boot 2.0.0 snapshots seems to suffer from this problem: https://github.com/tesla/m2eclipse-mavenarchiver/issues/9 (angry errors in Eclipse, but it works on the command line). Downgrading the jar plugin to 3.0.0 fixes it.

**Comment by snicoll** [comment]
oh well.

**Comment by dsyer** [comment]
I don't see this any more with the latest STS. Looks like maybe it was fixed upstream.
