### ISSUE TITLE
Support spring-web-reactive in spring-boot-actuator

### ISSUE THREAD

**Issue by fayndee** [spring-projects/spring-boot#7664]
As mentioned in the current reference docs of `spring-boot`:

> Actuator HTTP endpoints are only available with a Spring MVC-based application.

In another word, it won't work with a Spring Web Reactive-based application. And it's actually not the case as the following setup won't have any effects and none of the actuators endpoints are available:

```
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-starter-web-reactive</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```

My question is: Is there any workaround for this? Or even better, is there any plan of supporting `spring-web-reactive` in `spring-boot-actuator`?

I'm totally aware of that Spring Web Reactive together with Spring Framework 5 is still in milestones and the whole support for these in Spring Boot 2 is still a 'work-in-progress'. I just want to know whether this specific feature is something we can expect when Spring Framework 5 and Spring Boot 2 go live. Thx!

**Comment by snicoll** [comment]
If you have a question, please join us on [gitter](https://gitter.im/spring-projects/spring-boot). 

We're tracking the integration of Spring 5 and the reactive effort in #4908
