### ISSUE TITLE
Make FilterRegistrationBean generic

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#7666]
While trying to fix #7475, it appears that early instantiation is currently the only way to get the type information about the Servlet filter that is about to be created by a `FilterRegistrationBean`. Doing so in a `Condition` can cause many initialization issues.

`FilterRegistrationBean` needs to be made generic, so as to look like `FilterRegistrationBean<MyServletFilter>`. This will make it easier to the type information without instantiating the bean and will make the registration more expressive about its intent.

**Comment by philwebb** [comment]
Whilst we're at it we should look at the others as well (`ServletRegistrationBean` for example).
