### ISSUE TITLE
Allow to configure Cassandra speculative execution

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#7669]
I discovered today that the only way to enable speculative execution is to define it on the builder.
[Enabling speculative executions](http://docs.datastax.com/en/developer/java-driver/2.1/manual/speculative_execution/#enabling-speculative-executions)

However, Spring Boot doesn't provide any way to get at the builder, so you have to re-implement the whole of `CassandraAutoConfiguration`. Perhaps instead it could look for an optional `SpeculativeExecutionPolicy` bean and apply it?

Related: #7320

**Comment by snicoll** [comment]
Would both of your use cases fit if we allow to tune the builder rather than then `Cluster` ?

**Comment by snicoll** [comment]
Note that if we have to change this, we must change it before 1.5.0.RC1 so I'd appreciate quick feedback on it.

**Comment by OrangeDog** [comment]
Yes, that should work too, though it seems less elegant.

**Comment by snicoll** [comment]
Well if you have an opinion on what would be elegant, please share it.

**Comment by OrangeDog** [comment]
... I did: if there are relevant policy beans in the context, add them.

Allowing anyone to make arbitrary changes to the builder would mean future additions wouldn't need to wait for a Spring Boot update to be used though. Maybe do both? Or whatever you want.

**Comment by snicoll** [comment]
Meh. Looks like crawling the context for too many things.

**Comment by snicoll** [comment]
#7320 needs to be reworked for that use case.
