### ISSUE TITLE
Support @MockBean on test fields with TestNG

### ISSUE THREAD

**Issue by qerub** [spring-projects/spring-boot#7689]
Using `@MockBean` on test fields is a very succinct way to mock components.

At the moment, it only works with JUnit tests via `SpringRunner`.

It would be great if it also worked with TestNG via `AbstractTestNGSpringContextTests`.

## Example

```java
@SpringBootTest
public class TestNGMockBeanTest extends AbstractTestNGSpringContextTests {

    @MockBean
    DemoComponent demoComponent;

    @Test
    public void mockBeanShouldWork() {
        assertTrue(demoComponent != null, "demoComponent is null");
        assertTrue(new MockUtil().isMock(demoComponent), "demoComponent is not a mock");
    }

}
```

**Desired behaviour:** Test passes.

**Current behaviour:** `"demoComponent is null"` assertion triggers.

**Comment by Krasnyanskiy** [comment]
I have the same problem. Unfortunately adding a name attribute to annotation `@MockBean` as suggested in [this](http://info.michael-simons.eu/2016/10/13/spring-boot-referencing-mockbeans-by-name/) blog post does not help.

**Comment by qerub** [comment]
@Krasnyanskiy: Consider using `@MockBean` like this instead as a workaround:

```java
@SpringBootTest
public class TestNGMockBeanWorkaroundTest extends AbstractTestNGSpringContextTests {

    @TestConfiguration
    static class Conf {
        @MockBean
        DemoComponent demoComponent;
    }

    @Autowired
    DemoComponent demoComponent;

    @Test
    public void mockBeanShouldWork() {
        assertTrue(demoComponent != null, "demoComponent is null");
        assertTrue(new MockUtil().isMock(demoComponent), "demoComponent is not a mock");
    }

}
```

**Comment by Krasnyanskiy** [comment]
Well, it's very weird workaround. In my case Spring is still cannot inject a bean.

**Comment by gpeel** [comment]
there is another workaround : just add @Autowired with @MockBeans and also add a manual reset since the automatic reset does not work 
So the following will work :
```
 @SpringBootTest(classes = AppConfig.class)
    public @Log class ServiceDrhImplTest_TestNG extends AbstractTestNGSpringContextTests {

        private @Autowired ServiceDrh serviceDrh;
        private @MockBean @Autowired EmployeDao employeDao;
        private @MockBean @Autowired SalaireDao salaireDao;

        @AfterMethod
        public void afterMethod() {
            Mockito.reset(employeDao, salaireDao);
        }
```

But i could not make @BeforeTest and @BeforeSuite work => in those cases I don't have any DI of spring beans

**Comment by sbrannen** [comment]
> But i could not make @BeforeTest and @BeforeSuite work => in those cases I don't have any DI of spring beans

That's expected.

Look at the source code of `AbstractTestNGSpringContextTests`. 

If you want to have DI _before_ the `@BeforeMethod` lifecycle callbacks, you will have to implement your own version of `AbstractTestNGSpringContextTests`.

**Comment by chanjarster** [comment]
@qerub I found another workaround. I changed ``WebMockTest`` which is in [Testing the Web Layer](http://spring.io/guides/gs/testing-web/) like this:

```java
@WebMvcTest(GreetingController.class)
@TestExecutionListeners(MockitoTestExecutionListener.class)
@Test
public class WebMockTestNg extends AbstractTestNGSpringContextTests {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private GreetingService service;

    @Test
    public void greetingShouldReturnMessageFromService() throws Exception {
        when(service.greet()).thenReturn("Hello Mock");
        this.mockMvc.perform(get("/greeting")).andDo(print()).andExpect(status().isOk())
                .andExpect(content().string(containsString("Hello Mock")));
    }
}
```

The key is to add ``@TestExecutionListeners(MockitoTestExecutionListener.class)``.

**Comment by uniquejava** [comment]
I met this same issue when use `@SpringBootTest` + JUnit5 + Mockito.

I found the above two solutions both work, thank you for your solutions. 

## Solution 1: Use MockBean + Autowired
```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
...
    @MockBean
    @Autowired
    private WorldService worldService;

    @Autowired
    private HelloService helloService;

    @Test
    public void testGetStrings() {
        Mockito.when(worldService.getWorlds("James")).thenReturn(Arrays.asList("Bob!!!!"));
        System.out.println(helloService.getStrings("James"));
```

## Solution 2: Use MockBean + MockitoTestExecutionListener
```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@TestExecutionListeners(MockitoTestExecutionListener.class)
...
    @MockBean
    private WorldService worldService;

    @Autowired
    private HelloService helloService;

    @Test
    public void testGetStrings() {
        Mockito.when(worldService.getWorlds("James")).thenReturn(Arrays.asList("Bob!!!!"));
        System.out.println(helloService.getStrings("James"));

```

**Comment by sbrannen** [comment]
@uniquejava, if you're writing your tests using JUnit Jupiter (i.e., JUnit 5), you ideally should **not** be extending `AbstractTransactionalJUnit4SpringContextTests` since that...

1. is designed for JUnit 4
2. overrides the default set of `TestExecutionListener`s including any of those provided by Spring Boot Test such as the `MockitoTestExecutionListener`

What happens if you completely remove the `@TestExecutionListeners` declaration, annotate your base test class with `@Transactional`, and stop extending `AbstractTransactionalJUnit4SpringContextTests`?

**Comment by sbrannen** [comment]
> The key is to add `@TestExecutionListeners(MockitoTestExecutionListener.class)`.

As of Spring Framework 6.0, it should no longer be necessary to register Spring Boot's `MockitoTestExecutionListener` explicitly when extending `AbstractTestNGSpringContextTests`.

- see https://github.com/spring-projects/spring-framework/issues/29149

Therefore, this issue may now be obsolete.

**Comment by wilkinsona** [comment]
Thanks, @sbrannen. The does indeed appear to be obsolete. I'll close it in favor of the already-implemented Framework enhancement.
