### ISSUE TITLE
Validate that AopAutoConfiguration backoff if a custom @EnableAspectJAutoProxy is present

### ISSUE THREAD

**Issue by zxj19951029** [spring-projects/spring-boot#7694]
Question

How can i configure spring aop as expose-proxy,It is missing on `org.springframework.boot.autoconfigure.aop.AopAutoConfiguration`

Because i'm on the same class call an other method,it is can't create Aspect Point.
But i not found something config on spring boot.please help me !

**Comment by zxj19951029** [comment]
I use spring boot version 1.4.0.RELEASE

**Comment by snicoll** [comment]
We don't expose that property but you should be able to workaround this as follows:

```java
@EnableAspectJAutoProxy(exposeProxy = true)
@Configuration
public class  YourSpringBootApp { ... }
```

And add the following to `application.properties``

```properties
spring.aop.auto=false
```

I think we should backoff if `@EnableAspectJAutoProxy` is defined in your own class, currently we don't.

Please report here that fixes your problem.

**Comment by zxj19951029** [comment]
Thank you for you answer.
Now, i'm use  @EnableAspectJAutoProxy(exposeProxy = true) in my project,
But the same class method call on other method,still not change.The first method can create a aspect point,
second method can't!
Why?

**Comment by snicoll** [comment]
This tracker is not meant to answer questions like these, please ask them on StackOverflow.

**Comment by snicoll** [comment]
Actually `spring.aop.auto` isn't necessary. We already back-off if a custom `@ EnableAspectJAutoProxy` is specified. I've just added a test to assert the current behaviour.
