### ISSUE TITLE
ServletContextInitializerBeans tries to initialize all servlets before servletContextListener

### ISSUE THREAD

**Issue by willamette** [spring-projects/spring-boot#7696]
It looks like in this section

```java
public ServletContextInitializerBeans(ListableBeanFactory beanFactory) {
	this.initializers = new LinkedMultiValueMap<Class<?>, ServletContextInitializer>();
	addServletContextInitializerBeans(beanFactory);
	addAdaptableBeans(beanFactory);
	List<ServletContextInitializer> sortedInitializers = new ArrayList<ServletContextInitializer>();
	for (Map.Entry<?, List<ServletContextInitializer>> entry : this.initializers
			.entrySet()) {
		AnnotationAwareOrderComparator.sort(entry.getValue());
		sortedInitializers.addAll(entry.getValue());
	}
	this.sortedList = Collections.unmodifiableList(sortedInitializers);
}
```

The `addAdaptableBeans` method is trying to convert all servlets into the `ServletRegistrationBean`s,
however, there might be an edge case, the controller needs sth set in `ServletContextListener`. In this scenario, the initialization would throw out BeanInstantiationException

sample code could be found in https://github.com/willamette/spring-boot-sample

**Comment by philwebb** [comment]
In you example you have the following class:

```java
@Controller
@RequestMapping("/test")
public class TestController extends HttpServlet {

    @Autowired
    public TestController(final ServletContext ctx) throws ServletException {
        Preconditions.checkNotNull(ctx.getAttribute(StartupListener.ATTR_NAME));
    }
}
```

Having a `@Controller` extend `HttpServlet` is very unusual and will cause these kinds of problems. All `Servlet` beans are instantiated in the `ServletContextInitializerBeans` class. Your `TestContoller` is being created before your listener has been invoked.

If you remove `extends HttpServlet` then the code works.

**Comment by willamette** [comment]
Gotcha, thanks!
