### ISSUE TITLE
spring-boot-maven-plugin:build-info triggering Eclipse refresh

### ISSUE THREAD

**Issue by ArloL** [spring-projects/spring-boot#7701]
When enabling `Refresh using native hooks or polling` in Eclipse and importing a Maven project that executes the `spring-boot-maven-plugin:build-info` goal a workspace refresh is triggered approximately every five seconds.

Disabling the native hooks refresh or changing the m2e lifecycle mapping to ignore helps.

My guess is that the BuildPropertiesWriter always overwrites the destination file instead of overwriting it only if the target content will change. I am not sure whether this is something one would want but I would like to get another opinion on this. Thanks in advance!

**Comment by snicoll** [comment]
The file contains the build time so I guess that's going to change every time. I am surprised nobody else reported the issue before. 

I am not using Eclipse myself so I can't tell.

**Comment by ArloL** [comment]
Thanks for the quick reply. You're right about the build time - I didn't think about that.

I have found a workaround that works for me. The lifecycle mapping in the plugin sets `runOnIncremental` to `true`. This causes the infinite loop: an incremental build triggers the file creation - which triggers the native hooks/polling - which triggers an incremental build.

According to http://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html setting `runOnIncremental` to `false` will execute the goal only during a full workspace build. I have confirmed that this works. This is fine for me. I can add the mapping to our parent pom.

Not sure whether it makes sense to change the plugin's default though.

**Comment by snicoll** [comment]
#6723 actually flipped that so I am not sure we want to disable it now. 

ping @kdvolder @wilkinsona

**Comment by ArloL** [comment]
As far as I can see #6723 and f41e62976006e0cfc4d1e27801e31336038a8bea respectively added the lifecycle mapping. I don't see a flip of `runOnIncremental` or am I missing something?

**Comment by snicoll** [comment]
Sorry, my mistake. I meant we added it to true explicitly (there was a reason why we did this) so flipping to false doesn't sound like something we're keen to do. That's why I've pinged others for feedback.

**Comment by kdvolder** [comment]
My thoughts, take with a grain of salt, I don't know precisely what's happening here. 

Assuming that you do want the plugin to execute on incremental builds (you say there is a reason, I don't know enough about it to know that reason, but I accept this at face value).

Then, to avoid these endless build cycles we have to find a way to either:

 - exclude the file that triggers it somehow from being considered as a 'input' on the build. I'm not sure if/how we can make eclipse/m2e exclude it but I could do some digging to figure out if that's somehow possible. Can someone furnish a test-project I can play around with and that exhibits the problem? Also a bit of background would help me. For example where exactly is that file that is written every 5 minutes?

 - spring-boot could avoid writing the file if its contents doesn't change as suggested earlier. You'll have to exclude the 'timestamp' from being counted as 'meaningful' to the 'did it change' check.

**Comment by ArloL** [comment]
To reproduce the problem:

1. Open any Eclipse installation
2. Ensure Window -> Preferences -> General -> Workspace -> `Refresh using native hooks or polling` is enabled
3. Open the progress view
4. Import any project that executes the spring-boot-maven-plugin:build-info goal. E.g. default start.spring.io project with this plugin section
    ~~~
    <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <executions>
            <execution>
                <goals>
                    <goal>build-info</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <!-- Output build-info in resources so we can look at it easily -->
            <outputFile>src/main/resources/build-info.properties</outputFile>
        </configuration>
    </plugin>
    ~~~~
5. Open the build-info.properties and see that it is constantly being updated like this ![spring-boot-inifinite](https://cloud.githubusercontent.com/assets/195367/21455222/bd31cee0-c91e-11e6-9f5d-62673f28e407.gif)

The m2e documentation actually contains a section that discusses this exact problem: http://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html#buildcontext

The important section is this

> Regardless of build type, all mojos mapped to MUST use plexus-build-api BuildContext to change workspace resources

There is also an easy solution to prevent the endless loop that I have successfully tested locally. I will create a PR to show you the code.

**Comment by philwebb** [comment]
Closing in favor of pull request #7741
