### ISSUE TITLE
spring-boot-cli : Content under the Eclipse Public License

### ISSUE THREAD

**Issue by sgustafsson** [spring-projects/spring-boot#7703]
**Question**
I am wondering which files exactly are governed by the EPL 1.0, as stated in https://github.com/spring-projects/spring-boot/blob/master/spring-boot-cli/src/main/content/legal/open_source_licenses.txt 👍 

"Unless otherwise indicated below, the Content is provided to you under
the terms and conditions of the Eclipse Public License Version 1.0 ("EPL").
A copy of the EPL is available in the file called license.txt."

The license.txt file at https://github.com/spring-projects/spring-boot/blob/master/spring-boot-cli/src/main/content/LICENCE.txt is not a copy of the EPL, but the Apache License 2.0

Maybe the content of the folders "bin" and "shell-completion" is subject to the EPL 1.0 ?

**Comment by philwebb** [comment]
That file is packaged up into the binary CLI distribution and I think that it needs to be updated. The Spring Boot CLI itself uses the Apache 2.0 license. The binary distribution include a number of jars that are released under the EPL license.

**Comment by sgustafsson** [comment]
OK, so then the EPL 1.0 refers to the following jars in the \lib\spring-boot-cli-1.3.3.RELEASE.jar\lib folder of the binary dsitribution http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.3.3.RELEASE/spring-boot-cli-1.3.3.RELEASE-bin.zip ?

aether-connector-basic-1.0.2.v20150114.jar
aether-util-1.0.2.v20150114.jar
aether-spi-1.0.2.v20150114.jar
aether-api-1.0.2.v20150114.jar
aether-transport-http-1.0.2.v20150114.jar
aether-transport-file-1.0.2.v20150114.jar
aether-impl-1.0.2.v20150114.jar
