### ISSUE TITLE
Extract database type from JDBC URL and forward to Hibernate

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#7708]
It looks like that I have to configure `spring.jpa.database` explicitly when I use `spring.datasource.url`. The latter is a common approach when e.g. moving from embedded H2/HSQL to a persistent local one. It would be cool if Boot would derive the value to use for the former based on the JDBC URL configured similar to what it does for the JDBC driver class.

**Comment by snicoll** [comment]
Funny that our documentation states "auto-detected by default". That's quite misleading!

**Comment by chris-denglere** [comment]
Hey guys,

I'm new to the project on github, but have used STS some previously. Would this enhancement be a good place for me to start contributing? Thanks!

**Comment by snicoll** [comment]
Closing in favor of PR #7796
