### ISSUE TITLE
Custom test slice @DataMongoTest - issue scanning repository beans

### ISSUE THREAD

**Issue by saljuama** [spring-projects/spring-boot#7713]
After reading [Custom test slice with Spring Boot 1.4](https://spring.io/blog/2016/08/30/custom-test-slice-with-spring-boot-1-4) article, I've decided to create my own custom slice, but for Spring Data MongoDB repositories. I've created this simple [demo project](https://github.com/saljuama/demo-data-mongodb-test), and once I get it to work properly then had plans to further extend it and also turn it to a custom Spring Boot starter (Spring Boot is so awesome!). Or if you consider it good enough, make a PR out of it and contribute.

But i ran into the issue that I cannot figure out how to get the scanning for repository beans right. When i debug the [test](https://github.com/saljuama/demo-data-mongodb-test/blob/master/src/test/java/org/springframework/boot/test/autoconfigure/mongo/sample/BookRepositoryTest.java), I've noticed that in my [TypeExcludeFilter implementation](https://github.com/saljuama/demo-data-mongodb-test/blob/master/src/main/java/org/springframework/boot/test/autoconfigure/mongo/DataMongoTypeExcludeFilter.java), in the deafultInclude method, when it reaches the [BookRepository](https://github.com/saljuama/demo-data-mongodb-test/blob/master/src/main/java/org/springframework/boot/test/autoconfigure/mongo/sample/BookRepository.java) interface it returns true, but at the end it does not get injected in the test application context.

My guess is because it is just the interface and not the repository bean that spring data generates. Or i could have messed something up with the auto configurations. I struggled quite a bit debugging and looking around in other custom test slice implementations to figure it out, but without any luck.

The question would be, how do i get the repository bean to get scanned? In any case, any help, input or feedback would be really appreciated.

Thanks in advance.

**Comment by philwebb** [comment]
I think the problem is that you've only imported `MongoAutoConfiguration` and you'll additionally need `MongoDataAutoConfiguration` and `MongoRepositoriesAutoConfiguration`. We split the auto-configuration up so that people can still get Mongo support even if they don't use Spring Data.

Try updating your `spring.factories` file to this:

```properties
org.springframework.boot.test.autoconfigure.mongo.AutoconfigureDataMongo=\
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
  org.springframework.boot.test.autoconfigure.mongo.FongoAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
org.springframework.boot.test.autoconfigure.mongo.AutoConfigureTestMongoTemplate=\
  org.springframework.boot.test.autoconfigure.mongo.TestMongoTemplateAutoConfiguration
```

**Comment by philwebb** [comment]
Oh and we'd be very interested in a contribution once you're ready 👍

**Comment by snicoll** [comment]
@philwebb we have one already #7600 

@saljuama can you please look at that PR and check it does what you expect? If a feature is missing, please comment on that PR. Thanks!

**Comment by michael-simons** [comment]
@saljuama In case you want to try with 1.4, I also setup a standalone version, as we needed it as well in our projects: https://github.com/michael-simons/datamongotest-autoconfigure-spring-boot If something is missing, let me know.

**Comment by saljuama** [comment]
Hey, thanks everyone for the fast responses. 

@philwebb it works like a charm, that was the missing piece of the puzzle, thanks a lot!

@snicoll thanks for pointing that one out, i need to improve my search skills, completely missed that one.

@michael-simons I will test it out, and come back to you! :+1:
