### ISSUE TITLE
Update to Spring 4.2.9.RELEASE on 1.3.x

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-boot#7725]
The Spring Framework 4.2.9.RELEASE has been released at yesterday.
I hope it will be reflected into 1.3.x line.

Thanks.

**Comment by philwebb** [comment]
Thanks for the PR but we're not really planning any more releases from the 1.3.x branch. I should have really closed the milestone by now.

If you want to upgrade specific projects you can override the `spring.version` property in your build.
