### ISSUE TITLE
Add Elapsed Time to Health Actuator

### ISSUE THREAD

**Issue by marweck** [spring-projects/spring-boot#7727]
Hi Spring Boot team.

Have some spring-boot apps in production. Sometimes I would like to check which part of my infrastructure is causing me retention.

Sometimes, it's the application server, sometimes is the communication between app server and the database.

**Suggested improvement**: add to the `/health` actuator the elapsed time to gather each dependency status (disk, db, mongodb, redis, etc).

**Comment by joshiste** [comment]
Imho writing a gauge metric more reasonable. 
:+1:  can be exported to metric databases
:-1:  does not appear on the `/health` endpoint, but on `/metrics`.

**Comment by marweck** [comment]
It's fine by me to have a gauge metric per HealthIndicator.

**Comment by snicoll** [comment]
As I said already on Twitter, I don't like the idea to add that information to the health endpoint.

**Comment by snicoll** [comment]
We have discussed this and we're not keen on providing such information out-of-the-box. If the latency is important to you, it must be part of the health check so it looks like you should have a dedicated `HealthIndicator` for that.
