### ISSUE TITLE
InfinispanCacheStatisticsProvider only works for local cache

### ISSUE THREAD

**Issue by tbfky** [spring-projects/spring-boot#7728]
`InfinispanCacheStatisticsProvider`
does not work for any other caches than local caches because of `InfinispanCacheStatisticsProvider#getObjectName`

```java
ObjectName name = new ObjectName(
		"org.infinispan:component=Statistics,type=Cache,name=\"" + cache.getName()
				+ "(local)\",*");
```

As an example an Infinispan in in replication mode would require an object name such as

```
org.infinispan:component=Statistics,type=Cache,name="my-cache(repl_async)",*
```

Expected is that the `InfinispanCacheStatisticsProvider` can handle **any** configured cache in Infinispan regardless of mode (replicated, distributed etc).

**Comment by wilkinsona** [comment]
Boot's cache statistic providers have been superseded by [Micrometer's](https://micrometer.io) support for caching-related metrics.
