### ISSUE TITLE
Test Data from @Sql is not visible with XA manager

### ISSUE THREAD

**Issue by coreer** [spring-projects/spring-boot#7729]
Spring application is multitenant and use Atomikos as distributed transactions manager. Database servers are MySQl 5.7 ones.

I cannot reach my test data which I want to provide by `@Sql`. I even set `@Transactional(isolation = READ_UNCOMMITTED)` as on test method and on service method under test as well. But I cannot see this data in test:(

```java
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.core.Is.is;
import static org.springframework.transaction.annotation.Isolation.READ_UNCOMMITTED;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.SqlConfig;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.transaction.annotation.Transactional;


@RunWith(SpringRunner.class)
@SpringBootTest
public class MaterialGroupServiceIntegrationTests {

    @Autowired
    private MaterialGroupService materialGroupService;


    private static final String MATERIALGROUP_FOR_UPDATE_ID = "17d96645-e4f6-42b6-9831-3c39f9dd3fdf";
    private static final String MATERIALGROUP_FOR_UPDATE_NAME = "TestMeForUpdate";
    private static final String NEW_NAME = "test_group_updated";
    @Test
    @Transactional(isolation = READ_UNCOMMITTED)
    @Sql(
        statements = "INSERT INTO materials_groups (id, type, name) VALUES ('" + MATERIALGROUP_FOR_UPDATE_ID + "', 'Plastic', '" + MATERIALGROUP_FOR_UPDATE_NAME + "')",
        config = @SqlConfig(dataSource = XAConfig.MASTER_DATA_SOURCE_NAME)
    )
    public void updateMaterialTest() throws MaterialGroupNotFoundException {
        final MaterialGroupDTO forUpdate = materialGroupService.get(MATERIALGROUP_FOR_UPDATE_ID);
        assertThat(forUpdate.getName(), is(MATERIALGROUP_FOR_UPDATE_NAME));

        forUpdate.setName(NEW_NAME);

        MaterialGroupDTO updated = materialGroupService.update(forUpdate);
        assertThat(updated.getName(), is(NEW_NAME));
    }


}
```

Service under the test:

```java
import static org.springframework.transaction.annotation.Isolation.READ_UNCOMMITTED;

import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import lombok.extern.log4j.Log4j2;

@Log4j2
@Service
public class MaterialGroupServiceImpl implements MaterialGroupService {
    @Autowired
    private MaterialGroupRepository materialGroupRepository;
...
    @Override
    @Transactional(isolation = READ_UNCOMMITTED)
    public MaterialGroupDTO get(String id) throws MaterialGroupNotFoundException {
        MaterialGroup materialGroup = materialGroupRepository.findOne(id);
        if (materialGroup == null) {
            throw new MaterialGroupNotFoundException("Can't find material group with id= " + id);
        }
        return materialGroupDTOConverter.fromModelToDTO(materialGroup);
    }
    ....
```

I've checked if added row is visible after it was inserted by Spring test context. It really is. I set debug breakpoint in `org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript` and execute select request `SELECT count(*) as c FROM materials_groups` and count with that connection is really +1.

But this additional row isn't visible for service under test:(

**Comment by philwebb** [comment]
Are you able to provide a small project that replicates issue. Your setup sounds quite complicated so it might be hard to create a sample, but without one I'm not sure what the problem could be. You might also want to ask on stackoverflow.com in case someone has a similar issue.

**Comment by coreer** [comment]
Here you are https://github.com/coreer/multitenantxawithmysqlforspringtest.

**Comment by coreer** [comment]
One more detail. I can see test data if I remove @Transactional annotation on test method... But this is not a case.

**Comment by AlexanderChernov** [comment]
I faced with the same problem as well... Very actual for our project too.

**Comment by Kudr** [comment]
Hi! ++ Same for me

**Comment by nlyk** [comment]
Same for Spring Boot v1.5.1.RELEASE.
If rings any bells, the same stands for both scripts and statements in @Sql.
Also, when I set the TransactionMode to ISOLATED, I'm getting "Lock wait timeout exceeded; try restarting transaction" from MySQL while trying to delete the records in AFTER_TEST_METHOD created in BEFORE_TEST_METHOD.

**Comment by wilkinsona** [comment]
@coreer Thanks for the sample.

You are relying on read uncommitted in your tests but you are using a plain `JtaTransactionManager` that simply checks that custom isolation levels are permitted; it doesn't actually apply them. The javadoc for `applyIsolationLevel` states that it is "to be overridden in subclasses for specific JTA implementations, as alternative to overriding the full doJtaBegin method".

I think you either need to write a custom `JtaTransactionManager` subclass for Atomikos (AFAIK, Atomikos' Spring integration doesn't provide one) or you need to use Spring Framework's `IsolationLevelDataSourceAdapter`.

For reference, others have faced the same problem with Atomikos: http://fogbugz.atomikos.com/default.asp?community.6.3311.2.
