### ISSUE TITLE
CTRL-C doesn't stop running app in Windows

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#773]
http://stackoverflow.com/questions/23432651/terminating-mvn-spring-bootrun-doesnt-stop-tomcat

**Comment by EdwardBeckett** [comment]
Late to the game here... but if you set up spring boot to run as Maven goals in Intellij then you can simply use <kbd>CTRL</kbd>+<kbd>F5</kbd> to start and <kbd>CTRL</kbd>+<kbd>F2</kbd> to stop the boot app.. That's what I'm using...

**Comment by muldon** [comment]
late here too but using the version 1.3.0.BUILD-SNAPSHOT the problem still persists

**Comment by wilkinsona** [comment]
@muldon See the [comment above](https://github.com/spring-projects/spring-boot/issues/773#issuecomment-53725814). As far as we know, this has nothing to do with Spring Boot.

**Comment by muldon** [comment]
@wilkinsona you may be right. I tried again here. The results are:
Terminal: CTRL+C: terminates mvn + tomcat.
Eclipse: CTRL+C: terminates mvn but not tomcat/jetty.

**Comment by kirankumarpolusani** [comment]
For gradle users **gradle -stop**  will do for spring boot 1.4.x
