### ISSUE TITLE
Remove xml-apis managed dependency

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7731]
See https://github.com/spring-projects/spring-boot/issues/7554#issuecomment-268829448

**Comment by snicoll** [comment]
Unfortunately, Htmlunit extends _directly_ from a type provided by xml-apis in [`DomElement`](https://sourceforge.net/p/htmlunit/code/HEAD/tree/trunk/htmlunit/src/main/java/com/gargoylesoftware/htmlunit/html/DomElement.java#l73)

We should exclude xerces altogether here if we want to exclude `xml-apis` (if that kicks in, it really need xml-apis). Unfortunately, there's no much we can do at this point.

**Comment by wilkinsona** [comment]
Looks like HTMLUnit should work without this now as `DomElement` no longer implements `ElementTraversal`.

**Comment by cvienot** [comment]
Event though `DomElement` no longer relies on `ElementTraversal`, xerces cannot be excluded because of [HTMLParser](https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/html/HTMLParser.java#L42) used in spring boot tests.

**Comment by wilkinsona** [comment]
@cvienot I can't see the connection between your comment about Xerces and the `xml-apis` jar. The jar does not contain any Xerces classes, only APIs in the `javax.xml`, `org.w3c.dom`, and `org.xml.sax` packages.

**Comment by cvienot** [comment]
@wilkinsona i was talking of excluding xerces from htmlunit import. 

Htmlunit depends on xerces. If you don't exclude xerces along with xml-apis, spring framework [DefaultDocumentLoader](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/factory/xml/DefaultDocumentLoader.java#L91) picks up xerces DocumentBuilderFactoryImpl, and xerces parser is therefore used when parsing xml conf.

Xerces parser relies on xerces [ElementImpl](https://github.com/apache/xerces2-j/blob/trunk/src/org/apache/xerces/dom/ElementImpl.java)
 that implements ElementTraversal.

Test `SpringBootTestXmlConventionConfigurationTests` will fail on `ClassNotFoundException `(`org.w3c.dom.ElementTraversal`)

**Comment by wilkinsona** [comment]
Thanks for joining the dots. I don't think there's any need to exclude Xerces any more. Hibernate has upgraded to Dom4j 2 which does not depend on `xml-apis`. That leaves, as far as I can tell, HTMLUnit as the only dependency that pulls in `xml-apis` transitively. This means that the dependency management for it that was added to fix https://github.com/spring-projects/spring-boot/issues/7554 is no longer needed.

**Comment by wilkinsona** [comment]
Closing in favour of #15854.
