### ISSUE TITLE
"spring.datasource.name" seems be ignored

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#7736]
My configurations:
> spring.datasource.url=jdbc:postgresql://localhost:5432/x
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.name=abc

my code:
```java
@Configuration @ComponentScan @Import({PropertyPlaceholderAutoConfiguration.class,
	ConfigurationPropertiesAutoConfiguration.class,	DataSourceAutoConfiguration.class})
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);}
    
    @Bean   public M m(
    		@Qualifier("abc") // without qualifier it works!
    		DataSource ds) {
```

I expect that `spring.datasource.name` is a bean name and can be used to qualified injection. 
Is it a bug or my understaning is wrong?

1.4.2.RELEASE

**Comment by snicoll** [comment]
Your understanding is wrong. Spring Boot is only going to create a `DataSource` if none exists so it doesn't make sense to offer you to qualify it. That name is the name of the datasource itself (i.e. the name of the in-memory database), not the the name of bean wrapping it.

**Comment by snicoll** [comment]
Please consider asking such question on stackoverflow next time.
