### ISSUE TITLE
SecurityProperties is misleading when disabling basic authentication

### ISSUE THREAD

**Issue by rupert654** [spring-projects/spring-boot#7738]
`SecurityProperties` lets properties like the following:

    security.basic.enabled=false
    security.sessions=stateless

This configuration makes it look like sessions should be stateless, but basic authentication should be disabled. However, these properties are only every used within the `ApplicationWebSecurityConfigurerAdapter` within `SpringBootWebSecurityConfiguration`. This adapter is switched off completely if basic authentication if disabled so actually the properties that aren't namespaced under security.basic, are also disabled.

Please can a top level "enabled" property be added to SecurityProperties, and can this adapter only be disabled if this property is set to false? Additionally, the basic.enabled property should instead be used within the adapter to switch off only portions relevant to basic authentication.

**Comment by mbhave** [comment]
@rupert654 The `ApplicationWebSecurityConfigurerAdapter` secures everything except the ignored paths with HTTP Basic authentication. If `security.basic.enabled` is set to `false`, this means that you want to switch off security provided by this class. Could you explain a little more what you would like to achieve by adding another `enabled` property? If you want to add custom security, you can add your own `WebSecurityConfigurerAdapter`.

**Comment by rupert654** [comment]
@mbhave Without reading the source code, how can a person determine which of the properties under the  ["Security Properties" heading](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) are still applied when `security.basic.enabled` is set to false?

I would assume that it was just the 3 other properties prefixed by security.basic. Instead it is actually all of them, except for `security.ignored`. To me, this is surprising behaviour.

I think this could be made clearer by either namespacing all properties except for `security.ignored` under `security.basic`. Alternatively `security.basic.enabled` could be replaced with `security.enabled`.

Alternatively, it could be quite useful to make the provided security more configurable and allow basic auth to be disabled, without also disabling the rest of the configuration. In that case, a separate enabled property for disabling basic, or all, security configuration would be handy.

**Comment by mbhave** [comment]
@rupert654 Thanks for the feedback. We are going to revisit security in 2.0 and that'll be a good time to make it less confusing.

**Comment by wilkinsona** [comment]
This has been superseded by the [security simplifications in M4](https://spring.io/blog/2017/09/15/security-changes-in-spring-boot-2-0-m4).
