### ISSUE TITLE
gradle plugin is not updated at plugin portal

### ISSUE THREAD

**Issue by slamdev** [spring-projects/spring-boot#7746]
The **1.4.3.RELEASE** version of **org.springframework.boot** plugin is not available at gradle plugin portal at: https://plugins.gradle.org/plugin/org.springframework.boot

**Comment by philwebb** [comment]
We might need to update our release process if there's a manual step needed.

**Comment by snicoll** [comment]
OK we need to set a `gradle-plugin` property with value `org.springframework.boot:org.springframework.boot:spring-boot-gradle-plugin` on bintray[https://bintray.com/spring/jars/org.springframework.boot/1.4.3.RELEASE/]. I just did that and 1.4.3 should  show up soon.

I'll upgrade the release checklist with that extra step right now.

**Comment by snicoll** [comment]
Alright, that did the trick. Our fault, sorry about that. 1.4.3 is now the latest version.
