### ISSUE TITLE
`@JsonTest` not working

### ISSUE THREAD

**Issue by wonwoo** [spring-projects/spring-boot#7747]
Hey everybody, Spring boot version 1.4.3.RELEASE `@JsonTest` not working, 
but 1.4.0.M2 version is working

```java
@RunWith(SpringRunner.class)
@JsonTest
public class SpringWebApplicationTests {

	private JacksonTester<JsonTestObj> json;

	@Test
	public void jsonTest() {
		assertThat(this.json).isNotNull();
	}
}
```
`json` field is null..., Thanks in advance!

**Comment by snicoll** [comment]
Please check the documentation. We've decided post M2 to require a regular `@Autowired` for this. 

Also, keep in mind that a feature can be reworked in a milestone.
