### ISSUE TITLE
ServletResources are not found when using Devtools

### ISSUE THREAD

**Issue by felx** [spring-projects/spring-boot#7752]
since spring-boot version 1.4.3.RELEASE, the static content in /public directory is not served when spring-boot-devtools is loaded

**Comment by felx** [comment]
this problem appears since commit 918e122

**Comment by felx** [comment]
As a work around, you can downgrade spring-boot-devtools to version 1.4.2.RELEASE ; in your pom.xml :
e.g. : 
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<version>1.4.2.RELEASE</version>
			<scope>runtime</scope>
		</dependency>
```

**Comment by philwebb** [comment]
@felx I'm having trouble replicating this. I've tried updating our sample application and static resources from `/public` appear to be served fine. Do you have a sample application that shows the problem?

**Comment by jdubois** [comment]
Hey @philwebb I'll share a sample tomorrow

**Comment by jdubois** [comment]
@philwebb and a special repo just for you :-)

-> https://github.com/jdubois/sample-for-phil-webb

- The first commit works
- Then I upgraded to Spring Boot Devtools 1.4.3 with https://github.com/jdubois/sample-for-phil-webb/commit/87c1174ff8b8177bc6895af3d901426e350f5454 and it fails

-> to test, just run "./mvnw" to use to provided Maven wrapper, and go to http://127.0.0.1:8080 - you will get the working app with the first commit, and a 404 error with the second commit.

The configuration for `setDocumentRoot` is at https://github.com/jdubois/sample-for-phil-webb/blob/master/src/main/java/io/yolo/config/WebConfigurer.java#L89

**Comment by philwebb** [comment]
Thanks for the sample. The reason I couldn't replicate the issue was that it only happens when working with war packaging. I've got a fix that should be in shortly.
