### ISSUE TITLE
Spring Data JPA and Spring MVC integration is only working with URL Encoded Form media type and not JSON and XML

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-boot#7754]
According to [1](http://stackoverflow.com/questions/31768289/spring-data-jpa-how-to-update-a-model-elegantly), [2](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-modelattrib-method-args), and [3](http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.web.basic.domain-class-converter), given the following JPA entity, repository, and controller it should be possible to send a `PUT` request with the appropriate body to retrieve an entity by its ID, populate its properties, and save it in the database:

#### Person.java
```java
@Entity
@XmlRootElement(name = "person")
@XmlAccessorType(NONE)
public class Person {

    @Id
    @GeneratedValue
    private Long id;

    @XmlAttribute(name = "id")
    private Long externalId;

    @XmlAttribute(name = "first-name")
    private String firstName;

    @XmlAttribute(name = "last-name")
    private String lastName;

    @XmlAttribute(name = "dob")
    private String dateOfBirth;
}
```
#### PersonRepository.java
```java
@Repository
public interface PersonRepository extends CrudRepository<Person, Long> {

}
```

#### PersonController.java
```java
@RestController
@RequestMapping(
        path = "/persons"
)
public class PersonController {

    private final PersonRepository personRepository;

    @Autowired
    public PersonController(final PersonRepository personRepository) {
        this.personRepository = personRepository;
    }

    @PutMapping(value = "/{person}")
    public Person savePerson(@ModelAttribute Person person) {
        return personRepository.save(person);
    }
}
```

However, this only works with `application/x-www-form-urlencoded` requests. For XML and JSON requests, the entity is loaded from the repository but its values do not get updated.

A test case that reproduces the issue is available [here](https://github.com/behrangsa/howto-springdata/tree/spring-boot-bug-report).

**Comment by philwebb** [comment]
When working with JSON or XML Spring's `DataBinder` isn't used so this step in the stackoverflow answer won't work:

> 2. After the existing instance was obtained, request data will be bound to the existing object.

You can basically only use the technique described if the `DataBinder` can access to the actual properties of the entity (i.e. the data is either `application/x-www-form-urlencoded` or passed as request parameters).

**Comment by behrangsa** [comment]
@philwebb,

Is there an OOTB way to accomplish this? Basically:

* Load the entity
* Update its attributes
* Pass it to the handler method (to be saved by custom code)

This is a very common pattern. Ruby on Rails and [Grails](http://docs.grails.org/latest/guide/webServices.html#restControllersStepByStep) support this pattern out of the box.

If not, I was wondering how does the Spring community handle this scenario at the moment? Is it to use `BeanUtils.copyProperties`?

**Comment by snicoll** [comment]
@behrangsa we prefer to use this tracker for enhancement requests and bug reports. For general questions, please ask on stackoverflow.

**Comment by behrangsa** [comment]
@snicoll I have already asked this on [SO](https://stackoverflow.com/questions/41319350/how-to-write-a-restcontroller-to-update-a-jpa-entity-from-an-xml-request-the-sp).

Unfortunately SO has become a strange place. This has been discussed in quite a few places such as in [this Reddit thread](https://www.reddit.com/r/programming/comments/54f62f/the_decline_of_stack_overflow/) already. In the case of my question someone has marked my question as _not programming_ and someone has down-voted it too. 

Anyway, let's not diverge. My follow up question was merely to understand if Spring supports this feature or not and if not to raise a feature request.

**Comment by philwebb** [comment]
@behrangsa I don't believe that it's supported. A feature request should probably be directed at the Spring Data JIRA.
