### ISSUE TITLE
Dynamic SpringBootTest properties

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#7759]
There's currently means to assign a dynamic port to the Spring Boot Server under test. When doing micro-integration (side-effect) tests, we a dynamic endpoint for a dependent services. For example, I want to start a fake google service and have Spring Boot use the endpoint to that. Currently, it is not straightforward to wire in a dynamic property like "cloud.endpoint". Neither is it possible for `SpringBootTest` to pick extra ports: if `SpringBootTest` could pick other ports, then it could render these as properties, which the fake servers could use in the test.

like here's one idea..

```java
@SpringBootTest(bootstrapProperties = AssignGooglePort.class, ...)
--snip--

static class AssignGooglePort implements Something {
  @Override public void someCallback(ConfigurableApplicationContext context){
    int port = somePortPicker.pick();
    EnvironmentTestUtils.addEnvironment(context,
        "google.endpoint:http://host1:"+port
    );
  }
}

// then the test could read the bootstrapped property by injecting it
```

Regardless of the solution pattern, it would be great to have SpringBootTest collaborate with other services (which themselves may or may not be Spring Boot).

cc @denyska @marcingrzejszczak

https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/16#issuecomment-269242489

**Comment by philwebb** [comment]
Do you mean that you want an arbitrary random port to be assigned when the test starts that you can then inject later to use? Something that's a combination of `@TestPropertySource` and `SocketUtils.findAvailableTcpPort`?

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@RandomPortProperty("google.endpoint.port")
public class MyTest {

}

public class AppConfig {

    @Bean
    public GoogleService(@Value("${google.endpoint.port:1234}") int port) {
        return new GoogleService(port);
    }

}
```

i.e. Taking this code (that will run with the current release) and making it a bit easier to use:

```java
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.PortTest.RandomPortInitailizer;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.context.support.TestPropertySourceUtils;
import org.springframework.util.SocketUtils;

import static org.assertj.core.api.Assertions.assertThat;

@RunWith(SpringRunner.class)
@SpringBootTest
@ContextConfiguration(initializers = RandomPortInitailizer.class)
public class PortTest {

	@Autowired
	private SomeService service;

	@Test
	public void testName() throws Exception {
		System.out.println(this.service);
		assertThat(this.service.toString()).containsOnlyDigits();
	}

	@Configuration
	static class MyConfig {

		@Bean
		public SomeService someService(@Value("${my.random.port}") int port) {
			return new SomeService(port);
		}

	}

	static class SomeService {

		private final int port;

		public SomeService(int port) {
			this.port = port;
		}

		@Override
		public String toString() {
			return String.valueOf(this.port);
		}

	}

	public static class RandomPortInitailizer
			implements ApplicationContextInitializer<ConfigurableApplicationContext> {

		@Override
		public void initialize(ConfigurableApplicationContext applicationContext) {
			int randomPort = SocketUtils.findAvailableTcpPort();
			TestPropertySourceUtils.addInlinedPropertiesToEnvironment(applicationContext,
					"my.random.port=" + randomPort);
		}

	}

}
```

**Comment by adriancole** [comment]
thanks for the tips, this looks like it would do the trick! will try

**Comment by denyska** [comment]
Thanks for the tip, custom initializer will work for sure! How about adding 'tcpport' method to `RandomValuePropertySource` to make properties read `my.random.port=${random.tcpport}`?

**Comment by vanhove** [comment]
I tried this out with spring boot 1.5.2 and combining those 2 annotation don't work. The initializer is ignored.
@SpringBootTest
@ContextConfiguration(initializers = RandomPortInitailizer.class)

**Comment by wilkinsona** [comment]
> Neither is it possible for SpringBootTest to pick extra ports: if SpringBootTest could pick other ports, then it could render these as properties, which the fake servers could use in the test.

I don't think that anything other than the OS picking ports is a good idea. It creates flakey tests that fail intermittently when the port that was picked wasn't actually available. The only reliable way to pick a "random" port and to be sure that it will be available is for the service that will use that port to open a socket using port 0 which will cause the OS to allocate an ephemeral port.

**Comment by philwebb** [comment]
We've done this recently with Spring Boot 2.0. We use [Testcontainers](https://www.testcontainers.org/) to start a service on a defined port (inside the container). This then gets mapped to an ephemeral port on the host which we can grab from the instance of the test `@Rule`.

Here's [an example](https://github.com/spring-projects/spring-boot/blob/8dd1354d82be9bae236e3e8804c82f0987c42729/spring-boot-project/spring-boot-test-autoconfigure/src/test/java/org/springframework/boot/test/autoconfigure/data/redis/DataRedisTestIntegrationTests.java#L93) that uses [RedisContainer](https://github.com/spring-projects/spring-boot/blob/8dd1354d82be9bae236e3e8804c82f0987c42729/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/testcontainers/RedisContainer.java)

**Comment by philwebb** [comment]
Looking at the [example again](https://github.com/openzipkin/zipkin-gcp/pull/16/files) we don't think adding support for this directly in Boot is a good idea. We'd suggest changing `StackdriverMockServer` to start itself on port 0 (i.e. a random port) then expose the port it actually got as a getter for `TestRestTemplate` to use.
