### ISSUE TITLE
Add support for configuring fallbackPageable in PageableHandlerMethodArgumentResolver via application.properties

### ISSUE THREAD

**Issue by ssherwood** [spring-projects/spring-boot#7775]
Currently, I can't find an easy way to globally configure the default PageRequest size for a Spring Data Web project without manually overriding the default addArgumentResolvers (the default is hard coded in the `PageableHandlerMethodArgumentResolver` to 20).  This configuration seems like it would be well suited to being set via the `application.properties` instead.

FYI - there is a property defined for Spring Data REST `spring.data.rest.default-page-size` but this has no impact on a vanilla RestController GetMapping.

**Comment by philwebb** [comment]
`SpringDataWebAutoConfiguration` would need to change so that it no longer uses `@EnableSpringDataWebSupport` and instead invokes a version of `SpringDataWebConfigurationImportSelector` that can import a  subclass of `SpringDataWebConfiguration`/`HateoasAwareSpringDataWebConfiguration` and override `pageableResolver`.

**Comment by vpavic** [comment]
This is related to [DATACMNS-822](https://jira.spring.io/browse/DATACMNS-822) I've opened a while ago against Spring Data Commons - motivation was lack of support for easy customization of `PageableHandlerMethodArgumentResolver` and `SortHandlerMethodArgumentResolver` defaults.

I've proposed the solution (see vpavic/spring-data-commons@0473487) by introducing customizers that would allow to easily configure defaults but there hasn't been much feedback.

I still believe the change would have greater impact if it was made in Spring Data Commons but I can port this to Spring Boot if the approach is acceptable from Boot's perspective.

Thoughts @philwebb?

**Comment by ssherwood** [comment]
@vpavic I completely agree with your original comment about having the Pageable/Sortable handler being configured in a "manner that's completely agnostic to the presence of HATEOAS and can be reused across different projects".

From a Boot perspective I would hope to have the most common configuration options exposed as properties in the `application.properties` for ease of use and consistency (however I'm not sure how to resolve the existing presence of `spring.data.rest.default-page-size`).

**Comment by philwebb** [comment]
I'd rather have something in Spring Data that we can hook into if at all possible.

**Comment by vpavic** [comment]
I've created PR against Spring Data Commons: spring-projects/spring-data-commons#192.

**Comment by philwebb** [comment]
Nice. Thanks once again @vpavic!

**Comment by vpavic** [comment]
[DATACMNS-822](https://jira.spring.io/browse/DATACMNS-822) was resolved and will be available with Kay M4.

Users will be able to customize `PageableHandlerMethodArgumentResolver` and `SortHandlerMethodArgumentResolver` defaults by registering `PageableHandlerMethodArgumentResolverCustomizer` and `SortHandlerMethodArgumentResolverCustomizer` beans - see the examples in [SDC tests](https://github.com/spring-projects/spring-data-commons/blob/2eb830d68f36b7cc1772dd7f743ec09bb9396dd5/src/test/java/org/springframework/data/web/config/EnableSpringDataWebSupportIntegrationTests.java#L68-L88).

If Boot is willing to take this a step further by exposing configuration properties that would set up the customizers, I can provide the PR after the `master` picks up `Kay-BUILD-SNAPSHOT` again.

**Comment by wilkinsona** [comment]
@vpavic Thanks for the offer of a PR. As of today, we're building against Spring Data Kay snapshots. Do you have some time to take a look at this?

**Comment by vpavic** [comment]
Thanks for the update @wilkinsona - I'll take a look at this late this week or early next week.

**Comment by wilkinsona** [comment]
Closing in favour of #9339
