### ISSUE TITLE
TaskScheduler, waiting tasks to complete and programmatically registered tasks interference

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-boot#7779]
When I define `taskScheduler` bean with `setWaitForTasksToCompleteOnShutdown(true)` and `setAwaitTerminationSeconds(20)` and at the same time schedule some tasks using `SchedulingConfigurer` and it's `ScheduledTaskRegistrar`, then `taskScheduler` never shutdown gracefully because it's queue contains programmatically scheduled tasks (using `taskRegistrar`), but no one cancels these tasks before `taskScheduler` tries to shutdown.

```
@SpringBootApplication
@EnableScheduling
public class SchedulingBugDemoApplication implements SchedulingConfigurer {

	private static final Logger log = LoggerFactory.getLogger(SchedulingBugDemoApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(SchedulingBugDemoApplication.class, args);
	}

	@Bean
	public TaskScheduler taskScheduler() {
		ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
		scheduler.setThreadNamePrefix("myScheduler-");
		scheduler.setPoolSize(10);
		// block spring context stopping to allow SI pollers to complete
		// (to graceful shutdown still running tasks, without destroying beans used in these tasks)
		scheduler.setWaitForTasksToCompleteOnShutdown(true);
		scheduler.setAwaitTerminationSeconds(20);
		return scheduler;
	}

	@Override
	public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
		taskRegistrar.addTriggerTask(
				() -> work(),
				new CronTrigger("*/5 * * * * *"));

		// The second task sits in the scheduler queue and prevents scheduler to shutdown().
		// The task's cancellation lies in taskRegistrar's destroy() method, but no one
		// calls it until context bean destruction is in place. At the same time the context
		// waits for taskScheduler to terminate to continue beans destruction procedure.
		taskRegistrar.addTriggerTask(
				() -> work(),
				new CronTrigger("0 0 0 */1 * *"));
	}

	void work() {
		log.info("Working...");
	}

}
```

The second task sits in the scheduler queue and prevents scheduler to `shutdown()`.
The task's cancellation lies in `taskRegistrar`'s `destroy()` method, but no one calls it until context bean destruction is in place. At the same time the context waits for `taskScheduler` to terminate to continue beans destruction procedure.

When we use `@Scheduled` annotation, then this problem is not present because `ScheduledAnnotationBeanPostProcessor`'s `destroy()` method explicitly calls `ScheduledTaskRegistrar`'s `destroy()` method, which cancels all the scheduled tasks.

But when we register our tasks programmatically, no one calls `ScheduledTaskRegistrar`'s `destroy()` method before `TaskScheduler` tries to `shutdown()` and `awaitTermination()`.

Maybe we can force somehow to call `ScheduledTaskRegistrar`'s `destroy()` method before `TaskScheduler`'s `destroy()` method? Of course this can be done manually for example:
```
	private volatile ScheduledTaskRegistrar taskRegistrar;

	@Override
	public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
		this.taskRegistrar = taskRegistrar;
		// ...
	}

	@PreDestroy
	public void destroy() {
		taskRegistrar.destroy();
	}
```

This workaroud works because the `@Configuration` bean's `destory()` method called before `TaskScheduler`'s. But I don't know if it is guaranteed or not.

I can imagine many workarounds for this but will be better to somehow make it work out of the box, as the `@Scheduled` annotation works.

---------------
Best regards, Ruslan.

Spring boot version is 1.4.3.RELEASE.

**Comment by xak2000** [comment]
Added Minimal, Complete, and Verifiable example: [scheduling-bug-demo.zip](https://github.com/spring-projects/spring-boot/files/676521/scheduling-bug-demo.zip)

**Comment by snicoll** [comment]
Thanks for the sample but it looks like a Spring Framework issue to me. I am afraid I can't move this issue there for you. Can you please create a new issue at https://jira.spring.io/browse/SPR ?

Thank you, the sample in particular is much appreciated.

**Comment by xak2000** [comment]
Thanks, @snicoll! Created https://jira.spring.io/browse/SPR-15067

Sorry for wrong issue tracker. Often, when I face spring issues, I can't really figure out in what part of spring ecosystem the problem lies, so I can't know where to post the issue.

I not found any mention of `ScheduledTaskRegistrar` and how to programmatically schedule tasks in Spring's documentation.
The [documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/scheduling.html#scheduling-task-scheduler) explain the interfaces, but say nothing about how to bootstrap/shutdown the sheduler and tasks programmatically. The only place where I found it is [EnableScheduling javadoc](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/annotation/EnableScheduling.html). So I thought by annotation name (`@Enable` prefix) that maybe it is spring-boot's area. :)

**Comment by snicoll** [comment]
We don't have any scheduling auto-configuration at all in boot: try "scheduling" or "EnableScheduling" in [our doc](http://docs.spring.io/spring-boot/docs/1.3.4.RELEASE/reference/htmlsingle/). Let's have that discussion on the other issue please.
