### ISSUE TITLE
1.4.3 spring-boot-starter-web failed to support jackson message converter

### ISSUE THREAD

**Issue by dnwdi** [spring-projects/spring-boot#7785]
hi spring boot team:
  I got  error when I try to get a json response from a RestController, however, the same code works fine in 1.4.2. Here is my controller code:
```
@RestController
public class HomeController {
    @RequestMapping("/")
    public String index(){
        return "Hello world!";
    }
    @RequestMapping("/person")
    public Person getPerson(){
        return new Person("Max", 10, "15 street");
    }
}
```
Person is a pojo with both getters and setters.
stack prints:

```
 2016-12-29 20:47:00,285 [http-nio-8080-exec-1] ERROR  o.a.c.c.C.[.[.[/].[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: No converter found for return value of type: class com.netease.meta.Person] with root cause
 java.lang.IllegalArgumentException: No converter found for return value of type: class com.netease.meta.Person
         at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:187)
         at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:174)
         at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
```

I don't know why `producibleMediaTypes` size is 0, it should contains 'application/json', hope you can fix it:)

**Comment by philwebb** [comment]
Are you able to provide a small sample that shows the problem?

**Comment by dnwdi** [comment]
This is my demo application: [https://github.com/dnwdi/spring-boot](https://github.com/dnwdi/spring-boot)

**Comment by dnwdi** [comment]
I find the problem, when I use 1.4.2.RELEASE, the jackson.core lib 2.8.4 includes both jackson-core, jackson-databind and jackson-annotations 
![selection_032](https://cloud.githubusercontent.com/assets/3249589/21559140/456212b0-ce0c-11e6-8c51-3fc4565386df.PNG)
but when I use 1.4.3.RELEASE, the jackson.core lib 2.8.5 includes only one jackson-databind, no wonder it can't find the converter!
![selection_033](https://cloud.githubusercontent.com/assets/3249589/21559160/ab63d972-ce0c-11e6-8d1e-22cfe1633acd.PNG)
when I add the other two jackson libs, it works  well!

**Comment by kazuki43zoo** [comment]
Hi @dnwdi ,
I've tried the your demo application (https://github.com/dnwdi/spring-boot). It has been work without adding other jackson libs explicitly on pom.xml.

Probably, you can resolve this behavior to perform re-import of pom.xml on IDEA.

or you can try on command line as follow:

```
$ mvn clean -U spring-boot:run
...
```

```
$ curl http://localhost:8080/person
{"name":"Max","age":10,"address":"15 street"}
```

All work fine on my local machine.

Thanks.

**Comment by htynkn** [comment]
+1
I try that repo (https://github.com/dnwdi/spring-boot) too. It works in my local machine

<img width="1082" alt="screen shot 2016-12-30 at 12 42 23 pm" src="https://cloud.githubusercontent.com/assets/659135/21559778/7cdb124c-ce8d-11e6-820c-57ce78079d38.png">
<img width="357" alt="screen shot 2016-12-30 at 12 42 39 pm" src="https://cloud.githubusercontent.com/assets/659135/21559779/7d9f7646-ce8d-11e6-926d-af8b3f3e234a.png">

**Comment by dnwdi** [comment]
I use my company's maven repo and it's not update! Sorry to bother you guys:)

**Comment by snicoll** [comment]
@kazuki43zoo, @htynkn thanks a bunch for testing!
