### ISSUE TITLE
HAL browser is not secured by default

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7795]
I am not sure this is intended or not but this looks like an oversight. If you add the HAL browser, you can access it in 1.5.x the same way as in 1.4.x

To reproduce, use the spring-boot-sample-hypermedia (revision 1f3de10101d as I am going to fix it as part of #7637). I can access `/actuator` which list all the actuator endpoints. If I try to access one of those I get 401 as I don't have any security config.

If I add security and `management.security.enabled=false` then the `/actuator` is protected by Spring Security but the actuator endpoint are visible...

I guess `/actuator` should be 401 as well. But that means two properties are required if we want to bypass security when Spring Security is on the classpath.

**Comment by mbhave** [comment]
@snicoll I'm not totally convinced that this is a bug. There are a few actuator endpoints that are not sensitive by default and the `/actuator` is one of them. When `/actuator` is accessed, the list some non-sensitive endpoints also. By default, `/health` and `info` can be accessed. So if we `/actuator` returns a `401` we won't be able to access these.

**Comment by snicoll** [comment]
You're right @mbhave - I got confused while working on something related.
