### ISSUE TITLE
Document the types that will be contained in messages sent to the metrics writer channel

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#7798]
I think a way `MessageChannelMetricWriter` is currently implemented is way too cumbersome to use in a real life. Let me express this issue with MQTT, which should work OOB with Sprint INT MQTT as that transport is used for telemetry and Boot metrics are about sending this kind of info over the wire.

First issue is that user is left hanging what is the actual error as stacktrace is omitted.

```
2016-12-31 16:28:19.670  WARN 1193 --- [ask-scheduler-6] o.s.b.a.m.export.AbstractMetricExporter  : Could not write to MetricWriter: class org.springframework.messaging.MessageHandlingException: error occurred in message handler [mqttOutbound]; nested exception is java.lang.IllegalArgumentException: [Assertion failed] - this expression must be true
```

I had to hack/compile Boot locally to log full exception:

```
Caused by: java.lang.IllegalArgumentException: [Assertion failed] - this expression must be true
	at org.springframework.util.Assert.isTrue(Assert.java:86) ~[spring-core-5.0.0.BUILD-SNAPSHOT.jar!/:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.util.Assert.isTrue(Assert.java:98) ~[spring-core-5.0.0.BUILD-SNAPSHOT.jar!/:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.integration.mqtt.support.DefaultPahoMessageConverter.messageToMqttBytes(DefaultPahoMessageConverter.java:239) ~[spring-integration-mqtt-5.0.0.BUILD-SNAPSHOT.jar!/:5.0.0.BUILD-SNAPSHOT]
```

Well yes, `DefaultPahoMessageConverter` only support `String` or `byte[]` as a payload. Boot metrics are sending `Metric` or `Delta` into a channel and naturally things go south.

I don't think we should just send `Metric` or `Delta` and expect user to handle the mess with whatever `MessageChannel` and transport is in use. I don't exactly know what we should do to make end-user experience better but possibly something along a lines of converting Metric/Delta to json or something similar.

Message logged:
```
2016-12-31 16:52:00.996 DEBUG 1397 --- [ask-scheduler-4] o.s.i.m.outbound.MqttPahoMessageHandler  : mqttOutbound received message: GenericMessage [payload=Metric [name=gauge.iot.temperature.28-0315a24b98ff, value=23.4, timestamp=Sat Dec 31 16:52:00 UTC 2016], headers={metricName=gauge.iot.temperature.28-0315a24b98ff, id=8331af0c-9833-f509-a3f1-2fc0476bc892, timestamp=1483203120986}]
```

**Comment by jvalkeal** [comment]
Ping @artembilan @garyrussell as they may have some ideas about this.

**Comment by garyrussell** [comment]
@jvalkeal How are you hooking the writer up to the mqtt adapter? 

You can always insert an `ObjectToJsonTransformer` between the channel and the adapter.

**Comment by artembilan** [comment]
IMO that is why we have Spring Integration - to reach the best loosely coupling principle. That isn't a responsibility of metrics writer to worry about target wire protocol. And isn't MQTT adapter functionality to convert all the data to expected type. You always can place any kind of transformer in between (see Gary's comment above) and wire everything together via channels.

Although I agree that an error isn't so informative...
Would be glad to have some simple Boot app to investigate. Not clear why you had to hack Boot for that...

**Comment by jvalkeal** [comment]
@garyrussell I know that with a current state of this metrics stuff user need to provide fully constructed `MessageChannel` for boot's disposal which works with `Metric` and `Delta`. Hacking between channel and adapter is probably best way to do it. Maybe one solution to this would be to provide some OOB Spring Int implementations which works. MQTT is probably one of those what user would choose if using `MessageChannelMetricWriter`.

**Comment by jvalkeal** [comment]
@artembilan That was just because boot is eating stacktrace [AbstractMetricExporter.java#L95](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/export/AbstractMetricExporter.java#L95). I can probably give you sample next week as current sample needs rasperry pi :)

**Comment by garyrussell** [comment]
Yuck - it's our fault - useless assertion with no comment:

    		Assert.isTrue(payload instanceof byte[] || payload instanceof String);

I'll open a JIRA against SI for that, at least.

**Comment by jvalkeal** [comment]
ok, thx. I suppose error message nitpicking about payload type would have given me enough info about the error, I just first thought I had some connections issues to mqtt broker on rabbit.

Maybe I'll try to provide Spring Int MQTT impl to boot which user could then pick up to get used with metrics.

**Comment by artembilan** [comment]
Another trick would be to improve `MessageChannelMetricWriter` with `toJson` option like we have with the `FileSplitter`.
Which probably is a main premise of this ticket 😀

Yep! Next week is good. Happy New Year to you all!

**Comment by wilkinsona** [comment]
I agree with @garyrussell that the writer should make no assumptions about the consumer so converting to JSON by default would be inappropriate. It sounds like the integration issue has addressed the problem with the poor diagnostics.

The last piece in the puzzle is documentation. While the javadoc mentions the types, Boot's reference guide does not. We should add something [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-message-channel-integration) to correct that.

**Comment by wilkinsona** [comment]
Closed by https://github.com/spring-projects/spring-boot/commit/68fdd49a0b663e01f548a7b0995ecfabbdf9f9dc.
