### ISSUE TITLE
Pre-configure the javadoc gradle task to link against the spring api docs

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#7800]
I currently have the following setup:

```groovy
plugins {
    id "java"
    id "org.springframework.boot" version "1.4.3.RELEASE"
}

//...

javadoc.options.links "http://docs.spring.io/spring-boot/docs/1.4.3.RELEASE/api/"
javadoc.options.links "http://docs.spring.io/spring/docs/4.3.5.RELEASE/javadoc-api/"

//...
```

I think it would be great if the *Spring Boot* gradle plugin could pre-configure the `javadoc`-task to link against the javadocs of the *Spring*- and *Spring Boot* version I am using.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We need to strike a balance between usability and configuring too much. I think this is a bit too far towards the latter. Some users may not want to link at all, and others may want to link to our javadoc but hosted internally. Accommodating both of those options as well as your proposed default would over-complicate things.
