### ISSUE TITLE
Upgrade Spring HATEOAS to 0.23.0.RELEASE

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7810]
Unfortunately not as simple as #7807 since `HypermediaEndpointDocumentation` fails:

```
HypermediaEndpointDocumentation.metrics:62 JSON path "$._links.self.href" expected:<http://localhost:8080/metrics> but was:<http://localhost:8080/metrics/metrics>
```

**Comment by juergenzimmermann** [comment]
@philwebb there is HATEOAS **0.23.0.RELEASE**, e.g. http://central.maven.org/maven2/org/springframework/hateoas/spring-hateoas/0.23.0.RELEASE/

**Comment by wilkinsona** [comment]
And Spring Data Ingalls snapshots use 0.23.0.RELEASE so that's the version we should upgrade to

**Comment by philwebb** [comment]
The root problem was https://github.com/spring-projects/spring-hateoas/issues/527. The new releases appears to work fine.
