### ISSUE TITLE
Can't set tomcat connectionTimeout on TomcatEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by zxj19951029** [spring-projects/spring-boot#7811]
It not have a method to set tomcat connectionTimeout on spring boot

**Comment by snicoll** [comment]
There is a `server.connection-timeout` property you can set for that.

**Comment by zxj19951029** [comment]
Thank you! would you give me the  all of tomcat properties.Because it is missing on google and other Search Engines

**Comment by zxj19951029** [comment]
Just some maxThreads,But most timeout properties can't find on search engines;

**Comment by bclozel** [comment]
It's in the reference documentation: http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
