### ISSUE TITLE
TestRestTemplate.withBasicAuth(...) does not remove BasicAuthInterceptor if present

### ISSUE THREAD

**Issue by PeterSt66** [spring-projects/spring-boot#7812]
Following code in `TestRestTemplate` (starting at line 999) does not remove `BasicAuthorizationInterceptor`'s from result, return value of the method should be **_updatedInterceptors_** instead of **_interceptors_**.

```java
private List<ClientHttpRequestInterceptor> removeBasicAuthInterceptorIfPresent( 
			List<ClientHttpRequestInterceptor> interceptors) { 
		List<ClientHttpRequestInterceptor> updatedInterceptors = new ArrayList<ClientHttpRequestInterceptor>( 
 				interceptors); 
 		Iterator<ClientHttpRequestInterceptor> iterator = updatedInterceptors.iterator(); 
 		while (iterator.hasNext()) { 
 			if (iterator.next() instanceof BasicAuthorizationInterceptor) { 
 				iterator.remove(); 
 			} 
 		} 
 		return interceptors; 
 	} 
```
Link to Github:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/TestRestTemplate.java#L1009

**Comment by philwebb** [comment]
see #6732

**Comment by philwebb** [comment]
Things are a little more complicated that fixing the `removeBasicAuthInterceptorIfPresent` method. The constructor that sets the `BasicAuthorizationInterceptor` actually does it directly on the `ClientHttpRequestFactory` so the remove method actually never has any affect.
