### ISSUE TITLE
Incorrect factories order in ManagementContextConfigurationsImportSelector

### ISSUE THREAD

**Issue by michail-nikolaev** [spring-projects/spring-boot#7814]
Spring Boot 1.4.2.RELEASE

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/ManagementContextConfigurationsImportSelector.java#L50-L53

In this lines `List<String>` are sorted as `List<Class`>, so, all ordering-related annotations on `ManagementContextConfiguration`s just ignored.

**Comment by philwebb** [comment]
Good spot. Thanks for raising it.
