### ISSUE TITLE
ConditionalOnBean not working as expected when referencing other beans by name

### ISSUE THREAD

**Issue by javadd** [spring-projects/spring-boot#7815]
My expectation for the following code would be to print test_ing_internal, but it seams I can't reference the internal bean that way.

```
@Configuration
public class C1 {

    @Bean
    @ConditionalOnBean(name="internal")
    public Object buildMyObject2() {
        System.out.println("test_ing_internal");
        return null;
    }

    @Bean(name="internal")
    public Object buildMyObject() {
        return null;
    }
}
```

**Comment by snicoll** [comment]
@javadd please review the javadoc of `@ConditionalOnBean` . For this to map properly you need to make sure that the relevant beans have been first "imported". You're making a condition on something that is declared in the same configuration. Move it to a separate configuration and make sure to have it processed first.

Besides (again, check javadoc), this annotation is meant to be used on auto-configuration classes only.

**Comment by javadd** [comment]
The documentation is not clear
- should I use @Import ?
- why is the name attribute inside the ConditionalOnBean annotation?

**Comment by snicoll** [comment]
If you have general usage questions, ask them on StackOverflow. We're also on gitter if you want to chat.

**Comment by javadd** [comment]
I added another example with @Import and two configuration files. Same problem.

```
@Configuration
@Import(C2.class)
public class C1 {

    @Bean
    @ConditionalOnBean(name="external")
    public Object buildMyObject2() {
        System.out.println("test_ing_external");
        return null;
    }

}


@Configuration
public class C2 {
    @Bean(name="external")
    public Object buildMyObject() {
        return null;
    }
}
```

**Comment by philwebb** [comment]
@javadd The order that bean definitions are loaded is critical to `@ConditionalOnBean` and we don't recommend that you use it on regular configuration classes. See this section of the Javadoc:

>  The condition can only match the bean definitions that have been processed by the application context so far and, as such, it is strongly recommended to use this condition on auto-configuration classes only. If a candidate bean may be created by another auto-configuration, make sure that the one using this condition runs after.

If you've got any additional questions please ask them on stackoverflow.com.
