### ISSUE TITLE
TestRestTemplate doesn't take spring.data.rest.base-path in application.properties into account

### ISSUE THREAD

**Issue by Doogiemuc** [spring-projects/spring-boot#7816]
When you expose your Repositories via sprint-data-rest

AND

you change the REST base-path in `application.properties`

    spring.data.rest.base-path=/base/path

WHEN you then use an autoinjected TestRestTemplate, then it is configured for localhost and the correct 
port, but not for that base path:

```
@RunWith(SpringRunner.class)
@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class RestEndpointTests {
  @Autowired
  TestRestTemplate client;
 
  @Test
  public void testUriMapping() {
    URI uri = client.getRestTemplate().getUriTemplateHandler().expand("/dummy");
    System.out.println("URI /dummy maps to "+uri);
 
    // will print  "http://localhost:<port>/dummy"  
    // INSTEAD OF  "http://localhost:<port>/base/path/dummy"   as configured in application.properties
  }
}
```

# Expected behaviour

The autoinjected TestRestTemplate should automatically be configured with the base path from applicatin.properties

# Workaround

For now, you must manually configure the base path of your TestRestClient, for example like this:

```
@Component
public class RepositoryRestConfigurer extends RepositoryRestConfigurerAdapter {
  @Override
  public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
    config.setBasePath("/base/path");
  }
}
```

**Comment by wilkinsona** [comment]
The base path is specific to endpoints exposed via Spring Data REST and doesn't affected every endpoint in the application. As such, I don't think it's appropriate to apply the base path to the TestRestTemplate that is not tied to Spring Data REST.

**Comment by Doogiemuc** [comment]
TestRestTemplate is not tied to Spring Data REST ??!?!?!?!    What is its purpose then at all?     According to the doc  TestRestTempalte is a wrapper for a plain RestTemplate. And TestRestTemplate is pre configured for testing a REST backend.   But in that preconfiguration the base path is forgotten.

**Comment by martin-g** [comment]
@Doogiemuc What if your application uses Spring MVC for custom stuff and Data REST for Spring Data repositories ? It should be possible to test your custom endpoints too, right ?
