### ISSUE TITLE
Upgrade to Couchbase Cache Client 2.1.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7824]

**Comment by wilkinsona** [comment]
`withExpirationInMillis(int)` is deprecated in favour of `withExpiration(int)`. The latter configures the value in seconds whereas we currently document the `spring.cache.couchbase.expiration` property as being in milliseconds.

@snicoll What do you think we should do here?

**Comment by philwebb** [comment]
Changing the property unit will be painful. I'd suggest we just round up.
