### ISSUE TITLE
Generate commented profile configuration files

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#784]
It would be really helpful if Spring Boot generated pre-populated configuration files:

- for all available options
- with reasonable defaults enabled
- with additional available values commented out
- for each common profile (development, test, and production)

Basically, anything you have an opinion on (autoconfiguration for) should be in the file

So instead of having to find and dive into: <https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java>

I should instead have an application.yml for each profile with the following in it:

	spring:
	
	  #rabbitmq:
	     # RabbitAutoConfiguration JavaDoc:
	     # http://docs.spring.io/spring-boot/docs/1.0.2.RELEASE/api/org/springframework/boot/autoconfigure/amqp/RabbitAutoConfiguration.html

	     # Username to connect with (this is the RabbitMQ default)
	     #username: guest

	     # Password to connect with (this is the RabbitMQ default)
		 #password: guest
	
	     # <some useful information about what this configuration property does>
	     #dynamic: true
	     
		 # etc.

This way you are showing me where to put the configuration, what options are available, what their default values are and where to get more information.

Thanks, 
Adam & Brian

**Comment by snicoll** [comment]
This one hasn't moved for quite some time and I believe the meta-data support is far more superior than statically dumping keys that are subject to change according to the classpath.
