### ISSUE TITLE
Promote the use of multiple profiles as a core practice

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#785]
Spring Boot projects should be configured for `development`, `test` and `production` profiles out of the box with defaults for running the application:
- running the application from Gradle/Maven (e.g. `gradle bootRun`) should default to using the `development` profile
- running the tests from Gradle/Maven (e.g. `gradle test`) should default to using the `test` profile
- running the application from the command-line (e.g. `java -jar`) should default to using the `production` profile

Adding additional environments should be obvious - just add another `application-<environment>.yml` file to the config directory.

It would also be helpful if the use of multiple environments was elevated in the documentation  (make it chapter 2 of the reference guide, not 22) to further encourage their use.

**Comment by sfussenegger** [comment]
We used a similar approach for our internal libraries and projects that I described in #5301. 

We came to realize that the definition of production, development and testing tend to differ in projects and/or circumstances. So different project would need different behavior from libraries when developing.

We ended up creating some profiles that define a certain behavior. most notably a "standalone" profile that causes configuration to exclude external services like queues, RDBMS', REST services, AWS, metrics etc. We then compose production, development and testing out of these behaviors on a project-level using bootstrap configuration (`spring.profiles.include`). 

For instance, the "standalone" profile would be included into testing by default. We then create a "quickstart" profile that's composed of "development" and "standalone" to get up and running quickly - or at least fail with a helpful message if "standalone" isn't feasible.

**Comment by iNikem** [comment]
One simple thing to do is for `@SpringBootTest` to activate `test` profile. Then tests will behave the same way no matter being run from gradle or IDE.

**Comment by philwebb** [comment]
We're going to close this one because we don't think we can really recommend any solution that everyone will be happy with. Projects like JHipster do have defined profile support and these higher level projects do feel like the best place to solve this.
