### ISSUE TITLE
Reduce memory footprint of AsciiBytes.hashCode(int hash, String string)

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#7850]
Hey,

just noticed a small improvement when building hash codes with AsciiBytes.hashCode(int hash, String string). There is an unnecessary invocation of String.toCharArray() which copies the backing array of the string. Because we're just iterating over the chars here we could simply use String.charAt().

Benchmark | Mode | Cnt | Score | Error | Units
------------ | ------------- | ------------ | ------------- | ------------ | -------------
MyBenchmark.testNew | thrpt | 20 | 30120816,951 | ±  155853,632 | ops/s
MyBenchmark.testOld | thrpt | 20 | 22063573,907 | ± 2329741,929 | ops/s

Cheers,
Christoph

**Comment by philwebb** [comment]
Great stuff. Thanks!

**Comment by philwebb** [comment]
Closing in favor of PR #7851
