### ISSUE TITLE
Check SessionCondition redis deprecation outcome

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7858]

**Comment by snicoll** [comment]
Basically we can remove that code that choose redis by default and users will get a "choose your store type" error on startup. Something we can document in the release notes. It has been the case for any other store introduced in 1.4.x.

**Comment by philwebb** [comment]
@snicoll Can you throw a line into the release notes if you get a chance?

**Comment by snicoll** [comment]
@philwebb [done](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes/_compare/5b67a4b6c7f60e8c1e3105ad4eb0c6d454b0fedd...909752f16e5a160081110d39d5e202fb61b162c0). Thanks for the reminder.
