### ISSUE TITLE
Automatically ensure that spring-configuration-metadata.json is generated in build/main/resources when using Gradle

### ISSUE THREAD

**Issue by baron1405** [spring-projects/spring-boot#7861]
The Spring Boot Gradle Plugin (1.4.3) generates the spring-configuation-metadata.json file under the build/classes/main directory hierarchy. Since this is not a compile class file, it should be generated under the build/resources/main directory hierarchy. Besides being a more appropriate location for the file, placing it under resources will keep tools such as FindBugs from trying to open and analyze the file (which causes an IOException).

**Comment by wilkinsona** [comment]
> The Spring Boot Gradle Plugin (1.4.3) generates the spring-configuation-metadata.json file under the build/classes/main directory hierarchy

The Gradle plugin isn't involved. The metadata is generated by `spring-boot-configuration-processor` which hooks into javac via `META-INF/services/javax.annotation.processing.Processor`. When writing the output we use `javax.tools.StandardLocation.CLASS_OUTPUT`. The only other options is `SOURCE_OUTPUT`. Of the two, `CLASS_OUTPUT` is definitely the more appropriate. 

Without us moving away from `StandardLocation` and writing some Gradle-specific logic, you may just have to live with things as they are. Have you tried adding a task to your Gradle build to move the metadata after complication but before FindBugs runs?

**Comment by baron1405** [comment]
Thanks for the clarification of who does the file generation. I will look into some custom logic for now. Perhaps the Gradle plugin can be enhanced to move the file to the appropriate location so that others do not have to replicate that step.

**Comment by wilkinsona** [comment]
> BTW the reason this is coming up now is because the recent Gradle 3.3 release changed the way output is logged from worker processes such as those used to run FindBugs. In Gradle 3.3. you now see the scanning output from FindBugs along with any exceptions stacktrace generated due to scanning of non-class files. Pretty ugly and there does not appear to be a way to silence the output using any of the typical Gradle mechanisms.

Interesting. Thanks for explaining the background. Please note that Gradle 3.x isn't officially supported with Boot 1.4. We only started officially supporting Gradle 3 in Boot 1.5.

**Comment by philwebb** [comment]
@wilkinsona I'm guessing we can't do much more than add some documentation for this one?

**Comment by wilkinsona** [comment]
We could consider doing something smart in the plugin based on the configured output location for the main resources

**Comment by madorb** [comment]
Using `Gradle 3.3`, `Spring Boot 1.5.1` and `FindBugs 3.0.1` this issue ends up causing me the following error on every `gradle build`. Obviously I can work around it, but it would be great if *some* solution could be codified into the plugin

```
  Cannot open codebase filesystem:/path/to/myapp/build/classes/main/META-INF/spring-configuration-metadata.json
    java.io.IOException: Wrong magic bytes of 7b0a2020 for zip file /path/to/myapp/build/classes/main/META-INF/spring-configuration-metadata.json of 2278 bytes
```

**Comment by madorb** [comment]
Also, just as an FYI i am also generating build info via:

```
springBoot { 
    buildInfo()
}
```

so I can't use @baron1405's example as the `resources/META-INF` directory already exists so the move fails. In case it helps anyone else - I'm just copying the single file:

```
compileJava {
    doLast {
        file('build/classes/main/META-INF/spring-configuration-metadata.json').renameTo(file('build/resources/main/META-INF/spring-configuration-metadata.json'))
    }
}
```

**Comment by wilkinsona** [comment]
There's a [Gradle issue](https://github.com/gradle/gradle/issues/1094) tracking this problem. From that I've learned that Kotlin's module files can also trigger the problem.

I've come to the conclusion that we should attempt to fix this for a few reasons:

- It's not just our `spring-configuration-metadata.json` that triggers the problem
- Any fix we make may be made obsolete by a fix in Gradle or Findbugs
- While a bit ugly, the problem's benign
- Simple workarounds are available

**Comment by spencergibb** [comment]
s/we should attempt/we shouldn't attempt

**Comment by wilkinsona** [comment]
Oops. Thanks, @spencergibb

**Comment by spencergibb** [comment]
😜

**Comment by baev** [comment]
I guess you should use `build/resources/main` folder for generated resources anyway, isn't?
