### ISSUE TITLE
Provide auto-configuration for proxy-datasource and/or p6spy

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7863]
Background: https://vladmihalcea.com/2016/05/03/the-best-way-to-log-jdbc-statements

**Comment by cemo** [comment]
Would be cool for 1.5 :)

**Comment by wilkinsona** [comment]
This has been addressed by [a third-party starter](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator) maintained by @gavlyukovskiy.
