### ISSUE TITLE
ErrorAttributes should be autoconfigured in @WebMvcTest

### ISSUE THREAD

**Issue by jhyot** [spring-projects/spring-boot#7867]
I have a global exception handler in my Spring MVC REST app, that uses `ErrorAttributes`.
Simplified example:

```java
@RestControllerAdvice
public class GlobalControllerExceptionHandler {

    private final ErrorAttributes errorAttributes;

    @Autowired
    public GlobalControllerExceptionHandler(ErrorAttributes errorAttributes) {
        this.errorAttributes = errorAttributes;
    }

    @ExceptionHandler
    public ResponseEntity<Map<String, Object>> handle(Throwable throwable, WebRequest request) {
        return ResponseEntity
                .status(500)
                .body(errorAttributes.getErrorAttributes(request, false));
    }
}
```

The problem is in test code that uses `@WebMvcTest`.

The `@RestControllerAdvice` class gets registered, but `ErrorAttributes` does not, and so the Spring context startup fails. I have to configure it by hand for every test class.

In my opinion, my setup with a global ControllerAdvice using ErrorAttributes is not very unusual, and so I'm asking whether `ErrorAttributes` could be included in the default `@WebMvcTest` filters?

**Comment by philwebb** [comment]
Seems sensible to me.

**Comment by jhyot** [comment]
Super fast response, thanks!
