### ISSUE TITLE
Nested actuator paths always require authentication

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#7868]
With Spring Security on the classpath, even if the actuator endpoint is not sensitive, the nested paths are considered sensitive. To reproduce, set `endpoints.env.sensitive=false`. `/env` can be accessed without authentication but `/env/user` requires authentication.

**Comment by snicoll** [comment]
Closing in favour of PR #7881

**Comment by philwebb** [comment]
Actually let's keep the issue open since it has more info and it's not a true PR (i.e. I'll just merge it directly without the `--no-ff`.
