### ISSUE TITLE
Support for database migrations through Maven and Gradle

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#787]
There are options in the Java ecosystem for managing database schemas.  We think that Spring Boot should have an opinion and provide tooling for getting up and running quickly with a preferred database migration tool.

Ideally, this would include Gradle or Maven tasks for creating a new migration as well as performing them (create, migrate, rollback, drop, version, etc.)

Also, Spring Boot should give suggestions for how to roll out database migrations to a production system.

**Comment by ulfbiallas** [comment]
Hey @berlin-ab,
it's quite a while ago since you asked this, but I just had the same problem and solved it the way that I specify the datasource configuration only in the application.properties and then load it from Gradle:

```
flyway {
    Properties props = new Properties()
    props.load(new FileInputStream(file('src/main/resources/application.properties')))
    url = props.get('spring.datasource.url')
    user = props.get('spring.datasource.username')
    password = props.get('spring.datasource.password')
}
```

**Comment by wilkinsona** [comment]
We'd prefer to leave build time migrations to the build system via their plugins
