### ISSUE TITLE
runtime ordering: Hibernate tries to do validation before Flyway migrates the database

### ISSUE THREAD

**Issue by eepstein** [spring-projects/spring-boot#7874]
Scenario:

Using Spring Boot 1.4.3.RELEASE and its excellent JPA and Data support with Flyway (v 4.0.3) and Hibernate (v 5.x).  

Hibernate is used as the JPA implementation.  It is *not* being used to manage the database schema.  Rather, Flyway is being used to fill that need.  

What we want is to invoke hibernate's ddl validation at startup - especially in our integration test environment.  When configured normally (via an application.yml file) the validation tries to run before the Flyway migration has occurred.  So, unsurprisingly, it always fails.  

Setting the ddl-auto to "none" (as suggested in #894) is not a good option for us: we really do want "validate" as we want to ensure at this step that the schema and the JPA mappings are aligned.

**Comment by wilkinsona** [comment]
@eepstein Can you please provide a sample that illustrates the behaviour you've described?

**Comment by eepstein** [comment]
build.gradle:

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        jcenter({url "http://jcenter.bintray.com/"})
        mavenCentral()
    }

    dependencies {
        if (!project.hasProperty('env') || project.getProperty('env') == 'dev') {
            classpath "com.h2database:h2:1.4.193"
        }  else {
            classpath "org.postgresql:postgresql:9.4.1212"
        }
        // For some reason gradle is not finding the latest spring boot plugin only finds the prior release,
        // so reference it here as a dependency.
        sspath("org.springframework.boot:spring-boot-gradle-plugin:1.4.3.RELEASE")
    }
}

plugins {
    id "org.flywaydb.flyway" version "4.0.3"
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'maven-publish'

apply plugin: 'org.springframework.boot'

sourceCompatibility = 1.8
targetCompatibility = 1.8

group 'example'
version '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    jcenter()
    mavenCentral()
}

dependencies {
    compile group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compile group: 'org.postgresql', name: 'postgresql', version: "9.4.1212"
    compile group: 'org.projectlombok', name: 'lombok', version: "1.16.12"
    compile("org.springframework.boot:spring-boot-starter-data-jpa")

    testCompile group: 'org.springframework.boot', name: 'spring-boot-starter-test'
    testCompile group: 'com.h2database', name: 'h2', version: "1.4.193"
    testCompile group: 'org.flywaydb.flyway-test-extensions', name: 'flyway-spring-test', version: "4.0.1"

}

task wrapper(type: Wrapper) {
    gradleVersion = '3.3'
}


application-test.yml:

flyway:
  enabled: true
  schemas: foo

spring:
  main:
    banner-mode: "off"

  jpa:
    database: "H2"
    generate-ddl: false
    hibernate:
      ddl-auto: none     # validate happens too soon, before flyway has run  TODO : solve this
      use-new-id-generator-mappings: true


part of test class:

@RunWith(SpringRunner.class)
@ActiveProfiles({"test"})
@DataJpaTest //(showSql = false)
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextHierarchy({
    @ContextConfiguration(locations = "classpath:context/flywayContainerContext.xml")
    // , add more here as needed
})
@ComponentScan(basePackages = {"example.testing"})
@TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
                         TransactionalTestExecutionListener.class,
                         FlywayTestExecutionListener.class})
@FlywayTest
@Slf4j
@SuppressWarnings("SpringJavaAutowiringInspection")
public class FooTest {
...
}

**Comment by philwebb** [comment]
@eepstein Could you please share an actual project on GitHub that we can run. Thanks.

**Comment by eepstein** [comment]
i'll set one up...

**Comment by eepstein** [comment]
https://github.com/eepstein/spring-boot-data-example-1

**Comment by eepstein** [comment]
just to report back: i also tried (the above) by removing the @FlywayTest annotation (since that's from code that seems to be by BoxFuse/Flyway folks) and going with vanilla flyway=enabled with flyway core on the test classpath and letting Spring do it all... no dice.

**Comment by wilkinsona** [comment]
The key thing that you didn't mention is that you're using Flyway's test execution listener. That means that Boot has no control over the ordering of migrations versus Hibernate's initialisation. One way to fix the problem is to remove the use of the test execution listener, and instead rely on Boot's auto-configuration to configure and run Flyway at the right time. The changes to do so look like this:

```diff
diff --git a/src/test/java/testing/example/dao/AccountDaoTest.java b/src/test/java/testing/example/dao/AccountDaoTest.java
index 11d0984..494648c 100644
--- a/src/test/java/testing/example/dao/AccountDaoTest.java
+++ b/src/test/java/testing/example/dao/AccountDaoTest.java
@@ -1,5 +1,6 @@
 package testing.example.dao;

+import lombok.extern.slf4j.Slf4j;
 import org.flywaydb.test.annotation.FlywayTest;
 import org.flywaydb.test.junit.FlywayTestExecutionListener;
 import org.junit.Test;
@@ -7,16 +8,13 @@ import org.junit.runner.RunWith;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureTestDatabase;
 import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
-import org.springframework.context.annotation.ComponentScan;
 import org.springframework.test.context.ActiveProfiles;
 import org.springframework.test.context.ContextConfiguration;
-import org.springframework.test.context.ContextHierarchy;
 import org.springframework.test.context.TestExecutionListeners;
 import org.springframework.test.context.junit4.SpringRunner;
 import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
 import org.springframework.test.context.transaction.TransactionalTestExecutionListener;
-
-import lombok.extern.slf4j.Slf4j;
+import testing.example.TestApplication;
 import testing.example.domain.Account;

 // TODO : add tests that only run on Postgres
@@ -31,16 +29,12 @@ import testing.example.domain.Account;
 @ActiveProfiles({"test"})
 @DataJpaTest //(showSql = false)
 @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
-@ContextHierarchy({
-    @ContextConfiguration(locations = "classpath:context/flywayContainerContext.xml")
-    // , add more here as needed
-})
-@ComponentScan(basePackages = {"testing.example"})
 @TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
                          TransactionalTestExecutionListener.class,
                          FlywayTestExecutionListener.class})
 @FlywayTest
 @Slf4j
+@ContextConfiguration(classes = TestApplication.class)
 @SuppressWarnings("SpringJavaAutowiringInspection")
 public class AccountDaoTest {

diff --git a/src/test/resources/config/application-test.yml b/src/test/resources/config/application-test.yml
index 8520d4e..1cb2f1a 100644
--- a/src/test/resources/config/application-test.yml
+++ b/src/test/resources/config/application-test.yml
@@ -3,16 +3,19 @@ flyway:
   enabled: true
   schemas: tenant

+
 spring:
   main:
     banner-mode: "off"
-
   jpa:
     database: "H2"
     generate-ddl: false
     hibernate:
-      ddl-auto: validate     # validate happens too soon, before flyway has run  TODO : solve this
+      ddl-auto: validate
       use-new-id-generator-mappings: true
+  datasource:
+    tomcat:
+      url: jdbc:h2:mem:test;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS tenant

 logging:
   level.com.datavolo: info
```

**Comment by eepstein** [comment]
Well those changes do work.  So, first off, thank you.
Second, however, it looks like this is still using Flyway's test execution listener, in particular lines 41-44:

 @TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
                          TransactionalTestExecutionListener.class,
                          FlywayTestExecutionListener.class})
 @FlywayTest


So, that seems to be OK.  What seems to be needed is to have Spring provide the DataSource via its configuration and then Flyway knows to find it.  (The "tomcat" sub-element for datasource config was new to me.)

**Comment by wilkinsona** [comment]
> Second, however, it looks like this is still using Flyway's test execution listener, in particular lines 41-44

That was a mistake on my part. They aren't needed, and in fact have no effect. This will also work:

```diff
diff --git a/src/test/java/testing/example/dao/AccountDaoTest.java b/src/test/java/testing/example/dao/AccountDaoTest.java
index 11d0984..77b0264 100644
--- a/src/test/java/testing/example/dao/AccountDaoTest.java
+++ b/src/test/java/testing/example/dao/AccountDaoTest.java
@@ -1,22 +1,18 @@
 package testing.example.dao;

-import org.flywaydb.test.annotation.FlywayTest;
-import org.flywaydb.test.junit.FlywayTestExecutionListener;
+import lombok.extern.slf4j.Slf4j;
 import org.junit.Test;
 import org.junit.runner.RunWith;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureTestDatabase;
 import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
-import org.springframework.context.annotation.ComponentScan;
 import org.springframework.test.context.ActiveProfiles;
 import org.springframework.test.context.ContextConfiguration;
-import org.springframework.test.context.ContextHierarchy;
 import org.springframework.test.context.TestExecutionListeners;
 import org.springframework.test.context.junit4.SpringRunner;
 import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
 import org.springframework.test.context.transaction.TransactionalTestExecutionListener;
-
-import lombok.extern.slf4j.Slf4j;
+import testing.example.TestApplication;
 import testing.example.domain.Account;

 // TODO : add tests that only run on Postgres
@@ -31,16 +27,10 @@ import testing.example.domain.Account;
 @ActiveProfiles({"test"})
 @DataJpaTest //(showSql = false)
 @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
-@ContextHierarchy({
-    @ContextConfiguration(locations = "classpath:context/flywayContainerContext.xml")
-    // , add more here as needed
-})
-@ComponentScan(basePackages = {"testing.example"})
 @TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
-                         TransactionalTestExecutionListener.class,
-                         FlywayTestExecutionListener.class})
-@FlywayTest
+                         TransactionalTestExecutionListener.class})
 @Slf4j
+@ContextConfiguration(classes = TestApplication.class)
 @SuppressWarnings("SpringJavaAutowiringInspection")
 public class AccountDaoTest {
```

**Comment by eepstein** [comment]
ahem.
I'd a hunch that was the trouble.  Somehow my version without those hadn't worked.  I've completely removed the Flyway Spring test extensions from the project and things seem peachy. 
Thanks again.
