### ISSUE TITLE
endpoints.auditevents properties are bound to two different objects

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7875]
Currently `AuditEventsMvcEndpoint` and `AuditEventsJmxEndpoint` have the same `@ConfigurationProperties(prefix = "endpoints.auditevents")` annotation. We should consider if creating a dedicated property might be better.

**Comment by vpavic** [comment]
FWIW, the pattern of sharing the same `@ConfigurationProperties` annotation is present with multiple `Endpoint` implementation and their accompanying `MvcEndpoint`s:

```bash
$ grep -hr "@ConfigurationProperties(.*endpoints..*)" . | sort | uniq -d
@ConfigurationProperties(prefix = "endpoints.auditevents")
@ConfigurationProperties(prefix = "endpoints.env")
@ConfigurationProperties(prefix = "endpoints.health")
@ConfigurationProperties(prefix = "endpoints.loggers")
@ConfigurationProperties(prefix = "endpoints.metrics")
@ConfigurationProperties(prefix = "endpoints.shutdown")
```

**Comment by philwebb** [comment]
Thanks @vpavic. It does seem like a common pattern and we probably shouldn't change it for 1.5 after all. It also seem that having certain properties only apply to certain classes is also common. With that in mind, I think we should be fine leaving the `sensitive` property off the `AutditEventJmxEndpoint` class.
