### ISSUE TITLE
Configuration processor has a compiletime dependency on spring-core

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7882]
It should just be a test scope dependency.

**Comment by philwebb** [comment]
It's been there a while so lets take it on in 1.5

**Comment by snicoll** [comment]
wow! 😞

**Comment by snicoll** [comment]
@philwebb any reason why it's not fixed in `1.4.x` ?

**Comment by philwebb** [comment]
@snicoll In hindsight no, I'll reopen and backport.
