### ISSUE TITLE
Shade annotation processor

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7883]
It would be nice if the annotation processor was self contained.

**Comment by snicoll** [comment]
FYI this breaks out-of-the-box support in IntelliJ IDEA. Since this commit, I am not able to build in the IDE

> Error: java: java.lang.NoClassDefFoundError: org/json/JSONObject

**Comment by snicoll** [comment]
I've reverted and will investigate why IJ can't work with the shaded jar.

**Comment by snicoll** [comment]
This has been addressed in #10307
