### ISSUE TITLE
Support for thymeleaf-spring5 in Spring Boot 2.0

### ISSUE THREAD

**Issue by danielfernandez** [spring-projects/spring-boot#7885]
According to #7450, Spring Boot 2.0 will set its Thymeleaf dependency to the 3.0 branch by default (which is great, thanks!).

We have [just published](http://forum.thymeleaf.org/Thymeleaf-3-0-3-and-Spring-5-integration-JUST-PUBLISHED-td4030168.html) the first version of our new `thymeleaf-spring5` integration package for Spring 5, with version `3.0.3.M1`. It depends on Spring Framework version `5.0.0.M4` and our idea is to keep releasing *milestones* / *release candidates* until Spring `5.0.0.RELEASE` is published, in which moment we will turn our package into a stable `.RELEASE`.

Given Spring Boot 2.0 will be based on Spring 5, it would be great if you could adapt Boot to the new `thymeleaf-spring5` package.

Also, `thymeleaf-spring5` includes support for the new **Spring Web Reactive** module (or whatever new name you give it in the coming weeks 😃), so it would be awesome if the starter and the autoconfiguration infrastructure could be updated to autoconfigure a reactive web application based on Thymeleaf. It should be very similar to the process for Spring MVC. 

We have a couple of *sandbox* applications already that can be used as an example, see https://github.com/thymeleaf/thymeleafsandbox-stsm-reactive/blob/20170105/src/main/java/thymeleafsandbox/stsm/StsmReactiveWebConfig.java

And of course, I'll be more-than-happy to help you with the task, just contact me.

**Comment by wilkinsona** [comment]
9bba73a1a978b5883b7838a252e387d4dca0fbca moved us over to `thymeleaf-spring5` and we have #8124 open for the reactive side of things so I think we can close this issue now.
