### ISSUE TITLE
Test specific keys aren't documented

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7887]
The following keys are current included in the metadata with no documentation  (in particular no entry in the appendix):

```
# spring.test.mockmvc
spring.test.mockmvc.add-filters=true # 
spring.test.mockmvc.print= # 
spring.test.mockmvc.print-only-on-failure=true # 

# spring.test.restdocs
spring.test.restdocs.uri-host= # 
spring.test.restdocs.uri-port= # 
spring.test.restdocs.uri-scheme= # 
```

@philwebb Does that make sense that the user changes this in `application.properties`? All of them? If the answer is yes then we need to document them somehow. If the answer is no, we need to fix the meta-data.

**Comment by philwebb** [comment]
`spring.test.mockmvc.print` does at least. See #6444
