### ISSUE TITLE
Support Apache Commons in Spring Boot Starter

### ISSUE THREAD

**Issue by paragvk** [spring-projects/spring-boot#7889]
This is an enhancement request for Spring Boot Starter (start.spring.io)

Enhancement

It will be great to have options in [Spring Boot Starter](http://start.spring.io) for [Apache Commons](https://commons.apache.org/).  Instead of supporting the complete set, it can be kept minimal and useful to have support for core libraries like:

1. IO
2. LANG
3. BEANUTILS

**Comment by snicoll** [comment]
This isn't the tracker for Spring Initializr (please check https://github.com/spring-io/initializr).

Regardless, we don't have auto-configuration for those libraries so we won't have any "starter" for it (it doesn't match the concept properly).
