### ISSUE TITLE
Provide a default value for enums in the metadata

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7890]
We aren't able to detect  default values for enums (#7562) so we should write them manually.

Also we should make it clearer that it isn't supported in the reference doc.

**Comment by philwebb** [comment]
Shame we can't detect them.

**Comment by snicoll** [comment]
I agree. Maybe you can give that a try? I honestly see no way to detect it. Maybe we can get the raw value and then check if it's legit ? I don't think we can get the full type from there.

**Comment by snicoll** [comment]
I am a bit nervous to change this now as it may break tooling support. I've pushed a basic change [on this branch](https://github.com/snicoll/spring-boot/tree/gh-7890). Basically, if you rebuild and try to get some documentation on `management.info.git.mode` you should now see that `simple` is the default value. I've tested this on IJ and it works just fine but I'd need some feedback on STS and Netbeans before going any further.

**Comment by michael-simons** [comment]
Works in NetBeans 8.2 with NB-Spring Boot 1.3.1:

![defaultvalueforenum](https://cloud.githubusercontent.com/assets/526383/21987942/c35e8ca0-dc05-11e6-921d-94b1220a302f.png)

Thanks for considering NB :)

**Comment by philwebb** [comment]
I'll try with STS when I can.

**Comment by michael-simons** [comment]
Seems to work with STS

```
Spring Tool Suite 

Version: 3.8.3.RELEASE
Build Id: 201612191457
Platform: Eclipse Mars.2 (4.5.2)
```

<img width="1272" alt="sts" src="https://cloud.githubusercontent.com/assets/526383/22037859/3f484268-dcf9-11e6-92a4-09d2a43d4ce5.png">

**Comment by wilkinsona** [comment]
Oops, I tried with STS earlier today and then forgot to comment. Sorry. It worked for me too.

**Comment by snicoll** [comment]
I've added an extra tool to check for enums without a default value in the metadata. For the time being, I'll run it prior to the release.
