### ISSUE TITLE
TestRestTemplate does not resolve relative links with java.net.URI parameter

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#7891]
According to the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-working-with-random-ports), when using `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)` `TestRestTemplate` will resolve relative links to the running server.

This works when calling `TestRestTemplate` with a String parameter for the uri. When using the methods that take a `java.net.URI` I get `org.apache.http.ProtocolException: Target host is not specified`

**Comment by philwebb** [comment]
We use Spring's `UriTemplateHandler` so unfortunately I don't think there's an easy way to expand links that are passed in as `URIs`. Are you using URIs for any specific reason? Anything preventing you switching to the `String` version?

**Comment by shollander** [comment]
In my case I am using URIs because of cleaner construction (using UriComponentsBuilder). I have an easy workaround by calling uri.toString() so it's not a major issue for me. It just seems to be strange behavior from an API perspective. If it can't be fixed it should at least be documented somewhere.

**Comment by philwebb** [comment]
@shollander Yeah, totally agree. Thanks.

**Comment by anderius** [comment]
I have the same issue. I want to use `TestRestTemplate `to send a POST with some headers, and have to use `RequestEntity`, which only accepts `URI`.

Should `RequestEntity `have methods that accepts `String`, or should `TestRestTemplate  `perhaps accept headers etc?

**Comment by philwebb** [comment]
Nice, thanks @wilkinsona
