### ISSUE TITLE
spring.config.location does not override default application.properties

### ISSUE THREAD

**Issue by qibobo** [spring-projects/spring-boot#7894]
I packaged a spring-boot application with a default application.properties file in the war file. Then when I start the app I assign a config file use -Dspring.config.location. Both the two files contains the same field "filePath". I expect the value that assigned by spring.config.location will take precedence but not. It use the application.properties and cause the app starting failed. How could I use a custom config file to override the application.properties?

**Comment by snicoll** [comment]
Can you share a sample that demonstrates this? Are you sure the other file is loaded?

**Comment by qibobo** [comment]
In application.properties the content is as below:

#ssl
server.ssl.key-store=../test-certs/scheduler.jks
server.ssl.ca=../test-certs/autoscaler-ca.crt
server.ssl.key-alias=scheduler
server.ssl.key-store-password=123456
#server.ssl.key-password=123456
server.ssl.key-store-type=JKS

And the custom config file's:

#ssl
server.ssl.key-store=../../test-certs/scheduler.jks
server.ssl.ca=../../test-certs/autoscaler-ca.crt
server.ssl.key-alias=scheduler
server.ssl.key-store-password=123456
#server.ssl.key-password=123456
server.ssl.key-store-type=JKS

And the start error shows: nested exception is java.io.FileNotFoundException: ../test-certs/autoscaler-ca.crt (No such file or directory).

And when the app starting the message showed:
No active profile set, falling back to default profiles: default

Is it the problem?

**Comment by snicoll** [comment]
As I already told you, we can't guess based on the info you've provided (it should work). Please share a sample that we can run.

**Comment by qibobo** [comment]
@snicoll  when set "-Dspring.config.location", when the file is conf.properties , it works, while the file name is "conf" without the ".properties", it does not work. So the conf file must be a .properties file?

**Comment by snicoll** [comment]
No. `spring.config.location` allows you to specify path to any property you want [as described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files). If you have more questions, please ask them on stackoverflow.

**Comment by lyz19890927** [comment]
The file extension matters, it has to be '.properties' or '.yml', I can't find a way to get rid of the extension.
