### ISSUE TITLE
Internationalize one of spring boot security sample

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-projects/spring-boot#7899]
Can you please update one of spring-boot security sample to use internationalization just like below request

[SpringSecurityInternationalization Sample](https://github.com/spring-projects/spring-security/issues/1768)

Do we have something in spring-boot security which does i18n configuration automatically?

**Comment by snicoll** [comment]
If we have to explain that bits specifically, I am more in a favour of a guide.

**Comment by philwebb** [comment]
+1 We prefer to keep samples purely for our own integration tests. If you'd like to raise an issue or submit a pull-request you can [do it here](https://github.com/spring-guides/getting-started-guides).

Thanks.
