### ISSUE TITLE
Servlet filters instantiated twice

### ISSUE THREAD

**Issue by mpirmez** [spring-projects/spring-boot#7904]
When a spring-boot-starter-web is deployed as a war file the filters are instantiated twice, the first time as a spring component, with all dependencies resolved and the second time with no dependencies resolved. Both instances will be on the filter chain.

Follows a simple test case.

The application:

    @SpringBootApplication
    public class Application extends SpringBootServletInitializer {
        @Override
        protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
            return application.sources(Application.class);
        }
    }
    
    @RestController
    class GreetingController {
        @RequestMapping("/hello/{name}")
        String hello(@PathVariable String name) {
            return "Hello, " + name + "!";
        }
    }

The filter:

    @WebFilter("/*")
    @Component
    public class TestCaseFilter implements Filter {
        private final Logger logger = LoggerFactory.getLogger(getClass());
        @AutoWired private Application application;
    
        public void init(FilterConfig cfg) throws ServletException {
            logger.info("init {} {}", this, application);
        }
    
        public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException , ServletException{
            logger.info("doFilter {}", this);
            chain.doFilter(req, res);
        }
    
        public void destroy() {}
    }

The pom.xml file:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
    
        <groupId>br.com.snap</groupId>
        <artifactId>boot-web-testcase</artifactId>
        <packaging>war</packaging>
        <version>0.0.1-SNAPSHOT</version>
        <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>1.4.3.RELEASE</version>
        </parent>
        <properties>
            <java.version>1.8</java.version>
        </properties>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-tomcat</artifactId>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </project>

If you remove @Component and leave @WebFilter from the filter there will be a single instance, but with no dependencies autowired. If you leave @Component and remove @WebFilter there will be a single instance of the filter too, but you cannot specify the urlPatterns.

**Comment by wilkinsona** [comment]
This is working is designed. You should either use `@WebFilter` with `@ServletComponentScan`, or you should use `@Component` and use a `FilterRegistrationBean` to configure URL patterns etc.
