### ISSUE TITLE
Internal spring boot bug if wildfly libs is used

### ISSUE THREAD

**Issue by AndrewBryukhov** [spring-projects/spring-boot#7908]
Then spring boot used (without any spring annotations) as dependency for wildfly (10.1) client package project i get this message:

```
WARN: AMQ212052: Packet PACKET(SessionBindingQueryResponseMessage_V2)[type=-8, channelID=13, packetObject=SessionBindingQueryResponseMessage_V2, exists=true, queueNames=[jms.queue.testQueue], autoCreateJmsQueues=false] was answered out of sequence due to a previous server timeout and it's being ignored
java.lang.Exception: trace
```

To reproduce this bug (use archive test2.7z.zip from https://developer.jboss.org/message/967227#967227):
1. copy wildfly standalone-full.xml to wildfly (10.1) config dir (plus server.keystore in this directory too)
2. copy Server.ejb to wildfly deploy dir
3. start wildfly (standalone.bat -c standalone-full.xml)
4. run: maven clean compile packege exec:exec
result: no exceptrions, jms is work (spam on console)
5. Then uncomment pom.xml at for lines 15-19 (for enable spring boot dependency), rebuild project and you can see errors at work
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.4.2.RELEASE</version>
</parent>

With 1.4.3 problem is actual too.

**Comment by snicoll** [comment]
There is no need to cross-post the thread you've opened in the JBoss forum. It looks like that Spring Boot might bring dependency management for something that doesn't work for you but since you're not using it, I don't really know what we can do for you.

**Comment by AndrewBryukhov** [comment]
This is test case.
I'm using spring, but this bug is blocking capabilities for using.
