### ISSUE TITLE
Auto configure browser blacklist

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#7928]
We don't want to support older versions of some browsers (e.g. IE 6), but rather than have users try to use IE 6 and receive strange errors, we want to display a screen telling them they are using an unsupported browser. So I have made a custom `@Configuration` class registered in `META-INF/spring.factories` to register a servlet filter to either display a white-label error message, or alternatively redirect users to another URL where I can made a pretty error message. It works when `eu.bitwalker:UserAgentUtils` is on the classpath and some properties are set in `application.properties`

- `spring.blacklist.browsers=IE:(,9.0)`
- `spring.blacklist.supportedBrowsers=Some text for the whitelabel message`
- `spring.blacklist.redirect=/someURL`
- `spring.blacklist.forward=/someURL`
  - you can use a forward URL instead of a redirect to avoid an extra request
- `spring.blacklist.whitelabel=true`
  - by default a whitelabel is deplayed if no redirect or forward URL is provided
- `spring.blacklist.attribute=someAttribute`
  - adds a request attribute with the specified name set to true for subsequent filters and servlets if the browser is blacklisted

I have code that I can contribute if there is interest. I did just notice that UserAgentUtils is no longer being maintained, though, in favor of client side JavaScript detection mechanisms. So maybe this isn't terribly valuable.

**Comment by bclozel** [comment]
Indeed, with the sheer number of clients out there and the mess that `User-Agent` is, client side detection mechanism is probably the best, safest option for this.

Thanks!
