### ISSUE TITLE
Auto configure templated welcome page

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#7931]
It would be nice if Thymeleaf is being used to automatically resolve the root view (/) to `classpath:/templates/index.html`. This would only add a view controller mapping to `/` if there was actually a template at that location. 

This could theoretically be overridden to use a different template by specifying `spring.thymeleaf.view-root=alternate` which would resolve based upon `spring.thymeleaf.prefix` and `spring.thymeleaf.suffix` to (by default) `classpath:/templates/alternate.html`

I have some code that I can contribute if there is interest.

**Comment by wilkinsona** [comment]
That sounds like it could be a nice addition to our support for a static welcome page.

I assume that you'd like to be able to use Thymeleaf so that you can reuse some of your existing template infrastructure? Obviously, there'll be no opportunity to add things to the model if the redirect's happening automatically.

**Comment by philwebb** [comment]
@bbrouwer This sounds like a good idea. I guess you're struggling to finish the PR due to the eclipse issues that we've not yet fixed?

**Comment by bbrouwer** [comment]
Actually, I am having a delay getting my company to sign the contributor agreement. I expect it to be fine, it will just take a couple more weeks. I suppose I can create the pull request so we can talk more specifically about the code before that gets signed.

Add I am playing in the code, I am wondering if the same thing should be done for the other templating languages and not make this specific to only thymeleaf. What are your thoughts about that?

**Comment by wilkinsona** [comment]
> Add I am playing in the code, I am wondering if the same thing should be done for the other templating languages and not make this specific to only thymeleaf. What are your thoughts about that?

I think that makes sense. What you're proposing here is somewhat similar to our support for templated error pages and those work will all of the template engines that we support.

**Comment by izeye** [comment]
This looks resolved via #10545

**Comment by snicoll** [comment]
Indeed, thanks @izeye!
