### ISSUE TITLE
Auto configure Weblogic JTA transaction timeout

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#7932]
It would be useful to easily configure the `org.springframework.transaction.jta.WebLogicJtaTransactionManager` to specify the default timeout
```
spring.jta.weblogic.transaction-timeout=60
```
This would simplify app configuration if all I needed was to set this property.

I have code that I can contribute if there is interest.

**Comment by snicoll** [comment]
There is already a property for that: `spring.transaction.default-timeout`, see #7561

**Comment by bbrouwer** [comment]
Cool. I didn't notice that before. I will definitely use that.
