### ISSUE TITLE
Spring Boot AWS documentation could be improved

### ISSUE THREAD

**Issue by szantopeter** [spring-projects/spring-boot#7935]
The [Spring Boot documentation for AWS](https://exampledriven.wordpress.com/2017/01/09/spring-boot-aws-elastic-beanstalk-example/) contains only boxfuse, but not the native options like Elastic Beanstalk or CodeDeploy or OpsWorks. Spring Boot can be easily integrated with those services as well. I have a blog article about Spring Boot and Elastic Beanstalk here :

https://exampledriven.wordpress.com/2017/01/09/spring-boot-aws-elastic-beanstalk-example/

I am happy to write a shortened version into the spring guide. Let me know if I should make a PR.

**Comment by snicoll** [comment]
Yes please.

**Comment by szantopeter** [comment]
Here is the PR https://github.com/spring-projects/spring-boot/pull/7948

**Comment by snicoll** [comment]
Closing in favour of PR #7948
