### ISSUE TITLE
CassandraAutoConfiguration should allow configuring basic PoolingOptions.

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#7945]
I want to be able customize connection pooling options for the cassandra driver.
I like the `ClusterBuilderCustomizer` that will be in `1.5.0`, but would like to be able to easily set some *basic* connection pooling options via properties that are located next to other  cassandra properties.
In particular I am interested in setting `maxRequestsPerConnection`, `maxQueueSize` and `heartbeatIntervalInSeconds` as described here http://docs.datastax.com/en/developer/java-driver/3.1/manual/pooling/.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#7946)
