### ISSUE TITLE
Provide version/commit as detail in ApplicationHealthIndicator

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-boot#7947]
We have some strict requirements which endpoints we are allowed to expose. Therefore we are not able to expose the /info Endpoint from Actuator but we use the /health Endpoint.

To be able to see the version which is currently deployed we wrote our own `ApplicationHealthIndicator` which includes the version/commit as a detail.

Maybe this is useful for other as well and can be the default provided by boot. If that is the case I would create a PR, if not we stick to our solution with a custom Indicator.

P.S.: We also include the time the check was executed. Maybe this is worth another issue/PR?

**Comment by wilkinsona** [comment]
Thank you for the offer, but we don't want to provide two endpoints that provide access to overlapping information out of the box. Your approach of writing your own endpoint to expose precisely what you need is what we recommend.
