### ISSUE TITLE
Move /flyway and /liquibase endpoint to just one endpoint

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#7950]
Nowadays, spring-boot provides endpoints for `flyway` and `liquibase` with the same names. I think paths shouldn't be specific to the technology. My proposal is move these 2 endpoints under just one. E.g `/dbchangelog`

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I prefer the separate endpoints as the format of the responses is very different. If we were to combine the two into `/dbchangelog` then I think we'd also need to define a common response format. That doesn't sound worth it to me.

**Comment by eddumelendez** [comment]
Thanks for your reply @wilkinsona. That is a valid point 👍
