### ISSUE TITLE
AliasFor missing for `exclude` and `excludeName` on `@SpringBootApplication`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7951]

**Comment by wilkinsona** [comment]
Strictly speaking, `@AliasFor` isn't necessary as the attributes have the same name on `@SpringBootApplication` and `@EnableAutoConfiguration`.

Do we still want to add them so that it's explicit?

**Comment by snicoll** [comment]
@yanncebron was asking, I guess he wrote some kind of logic in IJ to detect those.

**Comment by YannCebron** [comment]
I was under the impression that @AliasFor also makes it more clear from a semantic POV. There is no strict technical requirement for this from IJ side.
