### ISSUE TITLE
Can we make ErrorAttributes methods take a WebRequest rather than RequestAttributes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7952]
We'd like to align `ErrorAttributes` and `ResponseEntityExceptionHandler`. Currently with `ErrorAttributes` there's no way to get headers etc. If we switched to a `WebRequest` we could probably get them.

**Comment by philwebb** [comment]
See also #7653

**Comment by imgx64** [comment]
This would also fix #6555.

**Comment by philwebb** [comment]
Thanks for adding the link @imgx64
