### ISSUE TITLE
Use spring-hateoas in 0.23.0.RELEASE

### ISSUE THREAD

**Issue by mle-enso** [spring-projects/spring-boot#7966]
Spring Boot in the 1.4.x lane still depends on spring-hateoas 0.20.0.RELEASE.
Could we get this upgraded to 0.23.0.RELEASE?
We really look forward to use HATEOAS with the composed annotations like @GetMapping which was fixed in https://github.com/spring-projects/spring-hateoas/issues/471

**Comment by snicoll** [comment]
We align the version with the Spring Data release train. We use `Ingalls` and `0.23.0.RELEASE` in `1.5.x`. RC1 is out and the final release is going to be released in a few weeks.
