### ISSUE TITLE
Add reactive Health support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7972]

**Comment by snicoll** [comment]
There is a base infrastructure in fa4480c that is ready to be merged but enabling it at the endpoint level brings a number of new challenges:

First We should probably create some sort of adapters for blocking health indicator (similar that what the endpoint invocation mechanism does to deport such invocation on a separate thread pool). This would make sure that the health indicators that have no "reactive" counter part are still present in the output.

It isn't 100% clear to me which strategy we should apply to register this new flavour. Surely we could create a `ReactiveHealthEndpoint` and a `ReactiveStatusEndpoint` with a `ReactiveHealthWebEndpointExtension` and a `ReactiveStatusWebEndpointExtension` but that looks a lot of boiler plate again. Another immediate problem is that we would have two `@Endpoint(id = "health")` annotated types so the annotation processor would duplicate the properties for `endpoints.health.*` (ditto for `endpoints.status.*`). We could fix the annotation processor (for instance to not register the source type to be the endpoint class as those properties aren't strictly defined there) but that would break the incremental compilation support that works out of the box now (if you change something in the definition of the endpoint, we figure it out and automatically update the relevant metadata). Also, if a default has to be changed, it feels weird that this default needs to be set for the regular and the reactive variant.

An alternative to this is to swap the web endpoint extension according to the target environment. This feels a lot more natural with the operation being overridden (including the method signature) in a single class. The only problem with this is consistency between `HealthIndicator` and `ReactiveHealthIndicator`: if both those classes do not return the same indicators, the outcome of the JMX operation and WEB operation would be different (as the JMX one definitely use the non reactive one in this model).

I am tempted to go with that last option and see how it goes.
