### ISSUE TITLE
EndpointMBeanExportAutoConfiguration required a single bean, but 3 were found

### ISSUE THREAD

**Issue by donovanmuller** [spring-projects/spring-boot#7977]
This is basically the same issue as https://github.com/spring-projects/spring-boot/issues/6529 (and similar to https://github.com/spring-projects/spring-boot/issues/6517) so I won't add much more to the conversation, except to say that this is still an issue.

Whether the problem is actually Boot related or Spring Data REST (https://jira.spring.io/browse/DATAREST-865) related is debatable but a simple Boot app (Spring Boot `1.4.3.RELEASE`) with the `spring-data-rest-hal-browser` dependency added (in my scenario) causes the "3 bean issue".

I have created a simple [sample app](https://github.com/donovanmuller/hal-of-a-problem) to demonstrate the issue (in reference to https://github.com/spring-projects/spring-boot/issues/6529#issuecomment-239851873): https://github.com/donovanmuller/hal-of-a-problem

As a side note, I do not extend `RepositoryRestConfigurerAdapter`. Simply adding `spring-data-rest-hal-browser` dependency and using `@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)` is enough to cause the issue.

**Comment by donovanmuller** [comment]
The offending class is [RepositoryRestMvcConfiguration](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java) in [`spring-data-rest-webmvc`](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc).

Two `ObjectMapper` beans are defined:

* [`ObjectMapper objectMapper()`](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java#L443)
* [`ObjectMapper halObjectMapper()`](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java#L507)

**Comment by snicoll** [comment]
Sorry but I don't think there is anything we could/should do in Boot to fix this. I've created [DATAREST-981](https://jira.spring.io/browse/DATAREST-981) as we believe that Spring Data REST shouldn't expose those `ObjectMappers` in the first place.
