### ISSUE TITLE
Remove spring-loaded support and suggest devtools

### ISSUE THREAD

**Issue by sarneeh** [spring-projects/spring-boot#7978]
So I've been trying to make the current spring-boot version working with the newest spring-loaded but after few hours of trying I'm giving up :)

Current version of spring-boot docs: http://docs.spring.io/autorepo/docs/spring-boot/current/reference/htmlsingle/#howto-reload-springloaded-gradle-and-intellij-idea shows an example which is not working (for me at least). It doesn't work either when i bump spring-loaded to the newest version.

And already preceding your questions:
- Yes, I've tried running my app with VM args: `-javaagent:/path/to/spring-loaded.jar -noverify`
- Yes, I've been recompiling my classes
- Yes, I've been trying to run my app via `gradle bootRun`
- Yes, I've been trying to run my app via IntelliJ

My build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.4.3.RELEASE'
        classpath 'org.springframework:springloaded:1.2.6.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    jcenter()
}

dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web:1.4.3.RELEASE'

}

idea {
    module {
        inheritOutputDirs = false
        outputDir = file("$buildDir/classes/main/")
    }
}
```

So... Please tell me if either am i not understanding something or are the spring-boot docs misleading? :)

**Comment by wilkinsona** [comment]
You've said the Spring Loaded "is not working". How have you determined that it isn't working? A small sample and a set of instructions that describe the changes you're making would be very helpful.

**Comment by sarneeh** [comment]
@wilkinsona Yeah, sorry. I thought that You could say that im doing something wrong already by this `build.gradle`. I'll prepare a sample with steps to reproduct my problems but I'll need few days for this because I don't have time in this moment :)

**Comment by montao** [comment]
I created a [similar project](https://github.com/montao/spring-boot-loaded) that is easy to verify it works. I just tried again cloning + running my boilerplate project. The reason I created it was to make it easy create a new project. You are welcome to try if it can help you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sarneeh** [comment]
@spring-issuemaster Sure! I'll provide some example in this week. Sorry, I'm kinda busy recently and forgot about this issue.

**Comment by sarneeh** [comment]
So here's an example project with the current spring-boot and spring-loaded version: https://github.com/sarneeh/spring-boot-loaded-example. The spring context reload does not work for me here.

Steps to reproduce:
1. Clone the repo
2. Run `./gradlew bootRun`
3. Change the `@RequestMapping` in `ExampleController` to i.e. `@RequestMapping("/spring")`
4. Recompile the class
5. Go to http://localhost:8080/spring OR watch the console - nothing works, nothing happens

**Comment by snicoll** [comment]
Sorry but I did exactly that (except that your controller is `/example` and it worked for me. I added a 2 in the text, compiled in IJ and when I refreshed the browser I got "example text2".

What am I missing?

**Comment by sarneeh** [comment]
Yes, the method signature does work for me also (sorry, didn't mention that). But it does not work on any spring annotations. That's why I asked for changing the `@RequestMapping` in the steps to reproduce my problem :)

Quoting spring-boot reference:

> Spring Loaded goes a little further in that it can reload class definitions with changes in the method signatures. With some customization it can force an ApplicationContext to refresh itself.

This is the main issue for me here. When I downgrade the spring-boot version to 1.2.x it works with refreshing the spring context.

**Comment by snicoll** [comment]
Then it has nothing to do with Spring Boot. Please raise an issue in [the Spring Loaded project](https://github.com/spring-projects/spring-loaded/issues)

**Comment by sarneeh** [comment]
Allright then. But IMO it would be nice that spring-boot documentation would not be misleading while providing the information and examples for a hot-swapping feature. I lost some time thinking that I'm doing something wrong because I assumed that what's in the official docs of the current stable version of spring-boot is working properly :) A note or anything that will tell that it may not work with the current version would be already awesome :)

Thanks! I'll report this issue to spring-loaded.

**Comment by philwebb** [comment]
Referenced issue https://github.com/spring-projects/spring-loaded/issues/192
