### ISSUE TITLE
Update the maven-git-commit-id-plugin to the latest version 

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-projects/spring-boot#7980]
Now we use older version which is affected by security issue: ktoso/maven-git-commit-id-plugin#240

Please update to 2.2.1.

**Comment by snicoll** [comment]
Confused, we're already using 2.2.1. In the meantime 2.2.2 is out so let's update to that version.

**Comment by mrumpf** [comment]
The issue is in Spring Boot 1.3.x. We have not yet upgraded to Spring Boot 1.4 and Spring Cloud Camden. So the question is whether you want to include the fix in a Service Release for Spring Boot 1.3

**Comment by wilkinsona** [comment]
@mrumpf We do not. 1.3.x is dormant. Even if it were not, we wouldn't upgrade to a new minor version of a plugin in a maintenance release. If you are using 1.3.x and are affected by the problem in the plugin, you should override its version.

**Comment by tjuchniewicz** [comment]
@wilkinsona The problem is that this new minor version of maven-git-commit-id-plugin fixes serious security bug...
See https://github.com/ktoso/maven-git-commit-id-plugin/issues/240

**Comment by wilkinsona** [comment]
We understand that but it doesn't change anything. As I said above, you should override the version if you are affected.

**Comment by chessracer** [comment]
Due to this update, and some changed behavior in the maven-git-commit-id plugin between the latest official release (v2.1.9), and the current tag (v2.2.2), we've had to workaround an issue whereby ${git.commit.id.abbrev} was no longer exposed to the build, unless we set the plugin configuration parameter generateGitPropertiesFile to false, eg:
```      
           <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <configuration>
                    <generateGitPropertiesFile>false</generateGitPropertiesFile>
                </configuration>
            </plugin>
```
reference https://github.com/ktoso/maven-git-commit-id-plugin/issues/275 for some more context

**Comment by snicoll** [comment]
@chessracer this issue is closed and there's not much we can do here. We'll upgrade to `2.2.3` when it's available. I've created #8806

**Comment by chessracer** [comment]
Thanks @snicoll.  Not a problem due to the workaround.
