### ISSUE TITLE
SpringBootRepositoryRestConfigurer may override a user's programmatic configuration

### ISSUE THREAD

**Issue by andrzejsliwa** [spring-projects/spring-boot#7981]
I switched my version of spring boot from 1.4.3 to 1.5.0.RC and looks like spring data rest ignoring RepositoryDetectionStrategy:

i have defined repository:
```java
public interface UserRepository extends JpaRepository<User, Long> {
    Optional<User> findOneByUsername(String username);
}
```
and configuration:
```java
@Configuration
public class SpringRestConfiguration extends RepositoryRestConfigurerAdapter {
    @Override
    public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        config.setRepositoryDetectionStrategy(RepositoryDetectionStrategy.RepositoryDetectionStrategies.ANNOTATED);
    }
}
```

I verified that configuration was called and switched but looks like was ignored:

1.4.3
```json
{
"_links": {
"profile": {
"href": "http://localhost:8080/api/profile"
}
}
}
```
1.5.0.RC
```json
{
"_links": {
"users": {
"href": "http://localhost:8080/api/users{?page,size,sort}",
"templated": true
},
"profile": {
"href": "http://localhost:8080/api/profile"
}
}
}
```

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem you're seeing?

**Comment by andrzejsliwa** [comment]
btw: i think strategy ANNOTATED could be default one, opening all repositories to the world by default its not safe

**Comment by andrzejsliwa** [comment]
@wilkinsona sure, here you have: https://github.com/andrzejsliwa/problem_with_repository_detection_strategy

**Comment by wilkinsona** [comment]
Thank you. This is a side-effect of us adding a configuration property in 1.5 for setting the detection strategy. Our code that sets it is running after yours so it's overriding your programmatic configuration. You can avoid that problem by replacing `SpringRestConfiguration` with an entry in `application.properties`:

```
spring.data.rest.detection-strategy=annotated
```

We should probably consider adding an order to our configurer so that you can order yours to run before or after it depending on your needs.

**Comment by andrzejsliwa** [comment]
and what about opening all repositories (even not annotated)  by default?  It's not safe in my opinion to make it as default.  For example security starter    is securing/closing app by default in case of rest interface and because of lack of default scoping - all data available on outside

**Comment by andrzejsliwa** [comment]
> We should probably consider adding an order to our configurer so that you can order yours to run before or after it depending on your needs.

Would be great! Thx

**Comment by wilkinsona** [comment]
> and what about opening all repositories (even not annotated) by default?

We're using the same default as Spring Data REST and I think we should continue to do so. If you think the default should be changed please open a JIRA ticket against Spring Data REST.

**Comment by andrzejsliwa** [comment]
@wilkinsona @snicoll 
would be great also to add information about `spring.data.rest.detection-strategy=...`

to documentation http://docs.spring.io/spring-data/rest/docs/current/reference/html/

**Comment by snicoll** [comment]
@andrzejsliwa this is unrelated to this change. We've documented the property in the appendix. As for the feature itself, this is something to ask the data rest team if they haven't done so yet.
