### ISSUE TITLE
Spring Boot 1.5 RC1 - Missing UserInfoRestTemplateFactory bean on Linux systems only (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by johndeverall** [spring-projects/spring-boot#7987]
We are having the following issue on linux systems only. We have reproduced it on several systems running Ubuntu 16.04 but also redhat I think.

This issue does not occur on Windows platforms. I realise this is not much to go on without a test case but I thought the OS specific nature of it might give enough of a clue. 

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled. 23:23:35.351 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter -   *************************** APPLICATION FAILED TO START ***************************  Description:  Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoRestTemplateFactory' that could not be found. 	- Bean method 'userInfoRestTemplateFactory' not loaded because @ConditionalOnMissingBean (types: org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration; SearchStrategy: all) found bean 'org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration'   Action:  Consider revisiting the conditions above or defining a bean of type 'org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoRestTemplateFactory' in your configuration.

```

Any more required info please do not hesitate to ask. Also, any tips on how I might solve it are more than welcome!

**Comment by snicoll** [comment]
I am afraid there's not much we can do with that. You may want to check that no artifact got corrupted on the Linux boxes (if you're building the fat jar locally). If you run the app in debug mode, the auto-config will show up and you'll be able to trace why that beam wasn't provided. 

If that doesn't help, I am afraid we'll need a test case.

**Comment by johndeverall** [comment]
It's definitely not a corrupt jar. We've replicated on more than three separate systems in different countries downloading their dependencies straight from central. We'll run in debug mode to look at the auto-config and then put together a test case if that doesn't help. Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by johndeverall** [comment]
I haven't had the opportunity to try a test case yet but just wanted to leave a note to say that this still occurs with spring-boot 1.5.2. We're primarily developing on windows systems at the moment so this seldom affects us (it's Linux specific).

**Comment by philwebb** [comment]
Unfortunately without a sample application I have a feeling that this is going to be very hard to track down. If you're able to turn on debug logging and attach the full output, that might give us some clues.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
