### ISSUE TITLE
Document recommendations for structuring configuration classes when using sliced tests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7999]
When using test slices it becomes important not to litter the application's main class with `@Enable…` annotations that are specific to a particular area of its functionality. The main class is typically the one that's used when using `@DataJpaTest`, `@JdbcTest` etc so it's important to keep it clean and only enable things that are applicable to the application as a whole. If this isn't done things may fail as the slicing will filter out things upon which something that's been switched on by `@Enable…` depends.

**Comment by snicoll** [comment]
Another example is custom `@ComponentScan` instructions.

**Comment by wilkinsona** [comment]
Has #10709 taken care of this, @snicoll?

**Comment by snicoll** [comment]
@wilkinsona ah I missed that, sorry. I just added a small note so I don't know if that's what we had in mind for this: https://github.com/spring-projects/spring-boot/commit/42fe8c1f389f327ec8fe30f0399a32a9eed79ebe

Perhaps we want a dedicated section or something?

**Comment by wilkinsona** [comment]
Yeah, I think we probably do. Let's keep this open.
