### ISSUE TITLE
why use "spring-boot-samples" in 	spring-boot/spring-boot-samples/spring-boot-sample-web-jsp/pom.xml?

### ISSUE THREAD

**Issue by nethub** [spring-projects/spring-boot#8003]
in "spring-boot/spring-boot-samples/spring-boot-sample-web-jsp/pom.xml" why use  below artifactId pls?
it will get error when execute in DOS: mvn spring-boot:run

```
	<parent>
		<!-- Your own application should inherit from spring-boot-starter-parent -->
		<groupId>org.springframework.boot</groupId>
		<artifactId>**spring-boot-samples**</artifactId>
		<version>1.4.3.RELEASE</version>
	</parent>
```

The correct should be below. right?

```
	<parent>
		<!-- Your own application should inherit from spring-boot-starter-parent -->
		<groupId>org.springframework.boot</groupId>
		<artifactId>**spring-boot-starter-parent**</artifactId>
		<version>1.4.3.RELEASE</version>
	</parent>
```

**Comment by snicoll** [comment]
No. Rather than describing what you think is a solution, can you please describe the problem you're having? That samples works fine for me.

**Comment by philwebb** [comment]
For various technical reasons we can't have our own sample extend from `spring-boot-starter-parent`.
