### ISSUE TITLE
Tie the versions in the docs to those defined in spring-boot-dependencies

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8006]
We sometimes reference versions in the documentation that should match those defined in `spring-boot-dependencies` but it's a manual process to keep them in sync. We should see if there's a way to keep them in sync automatically. One possibility would be a custom Asciidoctor extension that exposes all of the version properties from `spring-boot-dependencies` as Asciidoctor attributes that could then be referenced, for example `{{spring.version}}`.

**Comment by philwebb** [comment]
We [already set some](https://github.com/spring-projects/spring-boot/blob/f7f764ffe14fb7e6e8151084191e8bab42eae858/spring-boot-docs/pom.xml#L1008-L1018) so it should be pretty easy to add the ones we're missing.

**Comment by snicoll** [comment]
Closing in favour of PR #10774

**Comment by snicoll** [comment]
Oops that one is more general purpose, reopening

**Comment by wilkinsona** [comment]
#18000 has taken care of this.
