### ISSUE TITLE
Remove module layout in favour of pluggable custom layouts

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8008]

**Comment by philwebb** [comment]
I have a feeling it's currently being used by @spencergibb or @mbogoevici somewhere in cloud land.

**Comment by wilkinsona** [comment]
IIRC, it was added for XD. I think that means that it's no longer needed.

**Comment by wilkinsona** [comment]
If we're going to do this, it'd be nice to deprecate it in 1.5
