### ISSUE TITLE
Sql features documentation has broken link

### ISSUE THREAD

**Issue by jakobfaerch** [spring-projects/spring-boot#8015]
On
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html

There's a starred blockquote with the following text:
"Check also <<the ‘How-to’ section,howto.adoc#howto-configure-a-datasource] for more advanced examples,"

Which seems like a non expanded link.

**Comment by snicoll** [comment]
Thanks but this has already been fixed in the snapshot https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/boot-features-sql.html
