### ISSUE TITLE
Request Header filtering in WebRequestTraceFilter not case insensitive

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#8019]
Http header field names are case insensitive and this line does not take that into account: https://github.com/spring-projects/spring-boot/blob/782ded9c8c362f9b7ed3c31c1c687dc3655df6b0/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/WebRequestTraceFilter.java#L167-L167

**Comment by wilkinsona** [comment]
Fixed in e73c6bb2e291cd6c19e486c79f3753a8d00636d6.
