### ISSUE TITLE
1.4.x Release notes for metrics properties incorrect

### ISSUE THREAD

**Issue by jayanderson** [spring-projects/spring-boot#8021]
The release notes for the 1.4.x grouped endpoint metrics uses the wrong name for the 'grouped' setting. Here are the docs: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#metricsfilter-improvements.

```
endpoints.metrics.filter.gauge-submissions=grouped
endpoints.metrics.filter.counter-submissions=grouped,merged
```

The correct name for `grouped` is `per_http_method` (and similar variants). It appears to have been this way since the feature was created. It tripped me up when I tried to use it until I dug in further.

**Comment by bclozel** [comment]
I've just fixed the wiki page.
Thanks!
