### ISSUE TITLE
JSP in Jar-Deployment Breaks in Spring Boot 1.4.x

### ISSUE THREAD

**Issue by ngpeijiun** [spring-projects/spring-boot#8022]
The unintentional support for JSP in Jar-deployment breaks in Spring Boot 1.4.x. The same setup works in Spring Boot 1.3.8.

This is actually not a documented Spring Boot feature, but rather a gross hack that @ghillert [blogged about](http://hillert.blogspot.co.uk/2016/03/spring-boot-with-jsp-in-executable-jar.html) as stated by @wilkinsona in #6067. However, it is IMO the best thing that we have at the moment, until an official and better crafted JSP feature released in the future, to support JSP in Spring Boot JAR deployment.

Moreover, it is actually a little not consistent because this gross hack still works in Spring Boot 1.4.x if the project is to **run** or **debug** within IntelliJ.

I hope that this issue will be attended properly either as a fallback option for JSP applications until better future Spring Boot release, or as a fix from the inconsistently perspective (where debug and binary run produces different behaviors).

References:

1. #1131
2. #6067
3. [ghillert hack](https://github.com/ghillert/spring-boot-jsp-demo)

**Comment by wilkinsona** [comment]
As you've noted JSPs in executable JARs are not supported. If you want to use JSPs, please use an executable WAR. It's a far simpler solution than the `META-INF/resources` hack.

**Comment by h143570** [comment]
Actually the "bug" was introduced in 1.4.3.RELEASE; all previous one still works.

**Comment by ngpeijiun** [comment]
It was sad that this request is rejected.

Executable WAR can't seem to be able to run in IntelliJ. Any special settings we need to change in IntelliJ to run or debug it?

**Comment by wilkinsona** [comment]
That's a [bug in IDEA](https://youtrack.jetbrains.com/issue/IDEA-107048). The issue contains details of what to change to avoid the problem.
