### ISSUE TITLE
Deprecate and remove exceptionIfInvalid from ConfigurationProperties

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8027]
Now that we're moving towards requiring `@Validated` on a `@ConfigurationProperties` class, I think we should deprecate (in 1.5) and then remove (in 2.0) the `exceptionIfInvalid` attribute.

Enabling validation via `@Validated` but then not failing when the configuration is invalid doesn't seem like a good idea to me. It requires clients to deal with invalid configuration so you might as well have not validated in the first place.

**Comment by philwebb** [comment]
+1, it seems like an odd halfway at the moment.
