### ISSUE TITLE
Improve FailureAnalyzer for embedded datasource

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8029]
The `FailureAnalyzer` for the embedded datasource is too focused on the embedded use case (that is the fallback to a proper configuration to a production database). 

Say that you start an app with JPA and MySQL, this is what you get

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).
```

The link between MySQL and the embedded database isn't obvious at all actually. The action mentions "database settings" but the description doesn't. Perhaps we could be smarter and look in the environment? 

If that exception is thrown, it means we've tried to auto-configure the `DataSource`. We can therefore safely assume that no `spring.datasource.url` was specified. Perhaps we should mention that in the description? 

Actually, describing that we've tried to create an embedded database because no settings to configuration the database were found would be a good first start IMO.

**Comment by snicoll** [comment]
Closing in favour of PR #11953

**Comment by ff-yzheng** [comment]
I am very new about Spring, but I got the following error:
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to auto-configure a DataSource: 'spring.datasource.url' is not specified and no embedded datasource could be auto-configured.

Reason: Failed to determine a suitable driver class


is there any workaround here , like put configuration in application.properieties? Thank you for your help.

**Comment by snicoll** [comment]
@ff-yzheng this issue is closed and we don't use the tracker for questions. Feel free to ask on StackOverflow or come chat with us [on Gitter](https://gitter.im/spring-projects/spring-boot)
