### ISSUE TITLE
Upgrade to Spring Integration 4.3.7.RELEASE

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#8032]
This should be considered a blocker for boot 1.4.4.

There is a severe performance/memory leak problem with Spring Integration 4.3.6 on Spring Framework 4.3.5.

This is fixed by a patch to SF (only - not SI change needed).

So, while we could build SI 4.3.7 now, we really have to set its SF dependency to 4.3.6 so our non-boot users get the SF fix transitively.

So, we will plan on releasing SI 4.3.7 between SF 4.3.6 and Boot 1.4.4 (which are currently scheduled for the same day).

**Comment by snicoll** [comment]
Don't worry @garyrussell we'll figure something out. I'll get in touch with you once 4.3.6 is out. Thanks!
