### ISSUE TITLE
MetricExportAutoConfiguration contains EnableScheduling annotation

### ISSUE THREAD

**Issue by mzakes** [spring-projects/spring-boot#8040]
Hi,

the `MetricExportAutoConfiguration.class` in actuate project contains an `@EnableScheduling` annotation. This causes that ScheduledAnnotationBeanPostProcessor is always fired by default if actuator is on the classpath and all the methods  annotated `@Scheduled` are loaded.

This can cause a lot of pain. Could you please update the documentation or rewrite that class?

**Comment by snicoll** [comment]
This duplicates #7307 (there is a property you can set if you don't  want that to happen but let's turn this one into a documentation change.

**Comment by wilkinsona** [comment]
I've opened #8041 so that we can consider reworking `MetricExportAutoConfiguration` in the future.

**Comment by mzakes** [comment]
@snicoll. Of course that you can set this property to false. But if it's active the whole application inherits scheduling. For people that don't dig into the project it can be a surprise that during tests their `@Scheduled` method is executed but they removed `@EnableScheduling` annotation in the test configuration class.

**Comment by nimmortal** [comment]
Unfortunately this is real issue, because it takes some time to understand why scheduled tasks are performed in tests.

**Comment by snicoll** [comment]
@nimmortal this issue is quite old and Spring Boot 2.x does not have `@EnableScheduling` anymore. If you have more questions, please ask them on StackOverflow.
