### ISSUE TITLE
Use random port with Embedded mongo if nothing is configured

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8044]
At the moment, you can set `spring.data.mongodb.port=0` _only_ when you use the embedded feature to use a random port. If you set this to 0 and the embedded mongo doesn't kick in you'll get an exception.

Arguably, using a random port could be the default. So if the user hasn't configured anything (they're relying on the default provided by spring boot) we could switch the port to 0 only when we're sure the embedded support is kicking in. This should really help introducing a `@DataMongoTest`

**Comment by Marek00Malik** [comment]
I can still see this being an issue on the new RC1. 
I have this when trying to run tests on an Embedded MongoDb, class annotated with @DataMongoTest and no configuration for mongo. Spring Boot will try to setup a connection to embedded mongo db on a random port but the actual embedded mongo instance is on the default port. 
Only by setting directly a port the embedded instance and the connection will be pointing to the same port. 

Shouldn't the annotation set the embedded instance to one similar random port like it is done for the connection ?

**Comment by philwebb** [comment]
@Marek00Malik Could you please raise a new issue and attach a sample application that shows the problem.
