### ISSUE TITLE
Optimize startup time SpringCacheAnnotationParser

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8056]
Looking at the PetClinc it appears that `SpringCacheAnnotationParser` might be a hotspot. It searches every method in the app for `@Cache...` annotations. Not sure if there's much we can do, it might be a Spring issue. It seems a little related to the performance of `AnnotatedElementUtils`.

**Comment by philwebb** [comment]
![screen shot 2017-01-21 at 7 11 57 am](https://cloud.githubusercontent.com/assets/519772/22175420/4d597cb6-dfa9-11e6-8631-f1c2df64281a.png)

**Comment by philwebb** [comment]
@jhoeller Can you see anything obvious that could be done to improve the annotation processing performance. I wonder if calling `isAnnotated` first and perhaps somehow caching to save on meta-annotation recursion?

**Comment by snicoll** [comment]
@philwebb I am confused, `SpringCacheAnnotationParser` is in Spring Framework isn't it?

**Comment by philwebb** [comment]
@snicoll Yes, I have a feeling that this will ultimately be something we can't fix in Boot.

**Comment by philwebb** [comment]
This is a known issue (also with `EventListener`) and we're investigating various options in Spring Framework see https://github.com/spring-projects/spring-framework/issues/22175
