### ISSUE TITLE
Provide TestRestTemplateExtensions for Kotlin projects

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#8062]
As discussed in #5537, it would be nice for Spring Boot 2.0 to provide `TestRestTemplateExtensions` in order to bring the same kind of `RestTemplate` improvements Spring Framework 5.0 provides with [RestOperationsExtensions](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/kotlin/org/springframework/web/client/RestOperationsExtensions.kt) to `TestRestTemplate`.

**Comment by philwebb** [comment]
Closing in favor of PR #11039
