### ISSUE TITLE
Introduce "server.servlet" prefix for servlet specific properties

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#8066]
This change would break the current arrangement with `ServerProperties` and nest all Servlet specific keys under a `servlet` prefix.

Current key | New key
------------ | -------------
server.address | 
server.compression | 
server.connection-timeout | 
server.context-parameters.* | server.servet.context-parameters.*
server.context-path | server.servlet.context-path
server.display-name | 
server.max-http-header-size |
server.max-http-post-size |
server.error.[...] | *should we move this to an "mvc" namespace?*
server.jetty.[...] |
server.jsp-servlet.[...] | server.servlet.jsp.[...]
server.port | 
server.session.tracking-mode | **warning**: type `javax.servlet.SessionTrackingMode`
server.server-header | 
server.servlet-path | server.servlet.path
server.use-forward-headers |
server.session.[...] |
server.ssl.[...] |
server.tomcat.[...] |
server.undertow.[...] | 

Servlet specific properties should not apply when an application is deployed on a reactive runtime (even if it's a servlet container); in that case, we could silently ignore those or fail hard at startup.

New runtimes will be introduced, such as RxNetty and Reactor Netty (both based on netty). Configuration keys should be added as well.

Relates to #3659 and #4818

**Comment by snicoll** [comment]
`jsp-servlet` always bugged me, can we go with `spring.servlet.jsp` please?

**Comment by bclozel** [comment]
In that case, it would look like:

* server.servlet.jsp.class-name
* server.servlet.jsp.init-parameters.*= # Init parameters used to configure the JSP servlet
* server.servlet.jsp..registered

**Comment by snicoll** [comment]
See also #3016
