### ISSUE TITLE
Introduce a new Maven property and use it as groupId for jOOQ dependencies 

### ISSUE THREAD

**Issue by DiabolusExMachina** [spring-projects/spring-boot#8067]
Hi, 

The jOOQ-Framework uses a different groupId for each edition. For example the opensource groupId is `org.jooq`, the professional is `org.jooq.pro`

It would make thinks a lot easier for us if it would be possible to overwrite the group Id in our maven config. We use the spring-boot-starter-parent as parent for our projects.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, I don't like the idea of making the group ID configurable as it would provide an inconsistent experience. For example, it would have no effect upon `spring-boot-starter-jooq`.

**Comment by DiabolusExMachina** [comment]
Would it maybe be possible to use a maven classifier for the spring-boot-starter-jooq? And instead of making a property for the full groupdId use just the last part. 

so spring-boot-starter-parent :
 
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.jooq${jooq.edition}</groupId>
      <artifactId>jooq</artifactId>
    </dependency>
...
   <dependency>
    <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-jooq</artifactId>
    <classifier>${jooq.edition}</classifier>
  </dependency
 </dependencies>
</dependencyManagement>
```

and in custom project:

`<jooq.edition>pro</jooq.edition>`

**Comment by wilkinsona** [comment]
No, I don't think so. Sorry. We only reference artifacts in our poms that are in Maven Central. We don't want to diverge from that or get into the business of having two different variants of the same starter.

**Comment by DiabolusExMachina** [comment]
OK, too bad
