### ISSUE TITLE
Please support autoconfiguration of multiple data sources

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-boot#808]
It is not uncommon for projects to need to access more than one data source. It would be very useful for the application.properties file to support the ability to define more than one data source. For example:

```
spring:
    datasource:
        <data-source-qualifier #1>:
            primary: true
            driverName:
            url: 
            username: 
            password::
        <data-source-qualifier #2>:
            driverName:
            url
            username
            password:
```

**Comment by MurugananthamSDC** [comment]
How about the Application.properties

**Comment by dsyer** [comment]
How about what about it? If you have a usage question please put it on stackoverflow. If there is an issue please add a new one instead of commenting on an old one.
