### ISSUE TITLE
bootRepackage up-to-date checks should work when configured inside the model block

### ISSUE THREAD

**Issue by mkobit** [spring-projects/spring-boot#8099]
Spring Boot Gradle plugin `1.4.2.RELEASE` does not correctly do `UP-TO-DATE` checks when configured in the `model` block.

I expect that when `bootRepackage` is configured with the `model` that the second execution is `UP-TO-DATE`.

#### `UP-TO-DATE` when outside `model`

```groovy
plugins {
  id 'org.springframework.boot' version '1.4.2.RELEASE'
}

bootRepackage {
  classifier = 'myclassifier'
  mainClass = 'MainClass`
}
```

Running `./gradlew build` with Gradle 3.3 results in the first build succeeding, second build skips tasks with `UP-TO-DATE`.

#### `UP-TO-DATE` when inside `model`

```groovy
plugins {
  id 'org.springframework.boot' version '1.4.2.RELEASE'
}

model {
  bootRepackage {
    classifier = 'myclassifier'
    mainClass = 'MainClass`
  }
}
```

Running `./gradlew build` with Gradle 3.3 results both `bootRepackage` executing.

**Comment by wilkinsona** [comment]
This is strongly related to #5861 although appears to be a quirk we hadn't seen before. We'll tackle it as part of the Gradle plugin rewrite that's planned for 2.0.

**Comment by wilkinsona** [comment]
I can't reproduce this. The second example fails for me with Gradle 3.3 (and other versions too):

```
> The following model rules could not be applied due to unbound inputs and/or subjects:

    bootRepackage { ... } @ build.gradle line 6, column 3
      subject:
        - bootRepackage Object [*]

  [*] - indicates that a model item could not be found for the path or type.
```

`bootRepackage` is going to be replaced in #5861 with `bootJar` and `bootWar` tasks that are subclasses of Gradle's `Jar` and `War` tasks respectively so this should already have been taken care of.

@mkobit that said, it would be nice to have a sample that can reproduce the problem you were seeing so that I can verify that it doesn't happen with the new tasks.

**Comment by mkobit** [comment]
My mistake when posting the issue, as I stripped too much out of the code example.

It should contain `tasks` in the `model`, like:

```groovy
model { 
  tasks {
    bootRepackage {
      classifier = 'myclassifier'
      mainClass = 'MainClass`
    }
  }
}
```

If you'd like a full reproducible case I can do that too, just let me know.
