### ISSUE TITLE
AbstractEmbeddedServletContainerFactory.getExplodedWarFileDocumentRoot() doesn't work on Windows

### ISSUE THREAD

**Issue by bturner** [spring-projects/spring-boot#8100]
I'm using Spring Boot 1.4.3.RELEASE, but the same code exists unchanged on the master branch.

In [`AbstractEmbeddedServletContainerFactory.getExplodedWarFileDocumentRoot()`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/AbstractEmbeddedServletContainerFactory.java#L90-L95) is the following check:

```java
		if (file != null && file.exists()
				&& file.getAbsolutePath().contains("/WEB-INF/")) {
			String path = file.getAbsolutePath();
			path = path.substring(0, path.indexOf("/WEB-INF/"));
			return new File(path);
		}
```

If I unzip a Spring Boot "thick war" and run `java org.springframework.boot.loader.WarLauncher` ([as described here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#executable-jar-exploded-archives)), it works on Linux (where / is the file separator) but fails on Windows because the path contains "\\WEB-INF\\" instead.

**Comment by philwebb** [comment]
@bturner Thanks for the detailed analysis!

**Comment by bturner** [comment]
@philwebb @wilkinsona Thanks for the quick turnaround! I'm curious, though... Is there any chance this fix could be backported onto the 1.5.x line? If it doesn't make 1.5.0.RELEASE that's totally understandable, but if at all possible I'd love to not have to wait for 2.0.0 to get this fix. I'm happy to raise a pull request myself for this, if that's what's preferred.

**Comment by philwebb** [comment]
@bturner The bug was fixed in 1.4.4 and was forward merged. So it'll be in the upcoming 1.4.4 & 1.5.0 releases. It'll also be in 2.0.0.M1 when that's released.

**Comment by bturner** [comment]
@philwebb Ah, thanks! Sorry, GitHub showed it on master but nothing else, so I wasn't sure where it was applied. I should have checked locally.

**Comment by philwebb** [comment]
Yeah, I find the GitHub single commit view confusing as well. Some details about what it actually shows are documented here: https://github.com/blog/1451-branch-and-tag-labels-for-commit-pages

**Comment by snicoll** [comment]
@bturner I usually click on the issue link to see in which milestone it got added.
