### ISSUE TITLE
Rework excludes code in AutoConfigurationImportSelector

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8104]
When the new configuration work is complete we can probably rework the custom logic that was introduced in f8ded6de633aee8cba00722d98f912eaf1bde22d

**Comment by nestaone** [comment]
Hi,
We just upgraded from 1.4.4 to 1.5.1.
It seems that in 1.4.4, blank spaces were trimmed from the exclude class list. It's not the case anymore in 1.5.1? (resulting in a no match obvs...)

**Comment by wilkinsona** [comment]
@nestaone This issue is open and targeted at 2.0 so won't have affected 1.5.1. Can you please open a separate issue, ideally providing a sample that reproduces the problem you're seeing?

**Comment by nestaone** [comment]
@wilkinsona Sure, #8220

**Comment by mbhave** [comment]
@philwebb Is this issue relevant still? [This](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/AutoConfigurationImportSelector.java#L216-L223) is what it looks like at the moment.

**Comment by philwebb** [comment]
Thanks @mbhave. Looks like you got to this in commit 69ab2e462e7eaf0158cd3f96644c8fb46c5f5e9a.
