### ISSUE TITLE
Use of Tomcat as server in a Spring Web Reactive application triggers @OnWebApplicationCondition

### ISSUE THREAD

**Issue by danielfernandez** [spring-projects/spring-boot#8118]
In the current state of Spring Boot `2.0.0.BUILD-SNAPSHOT`, the `@OnWebApplicationCondition` annotation is matched `true` for Spring Web Reactive applications that use Tomcat as an embedded server.

The reason is [this code](https://github.com/spring-projects/spring-boot/blob/1df3fb6ecb04048630c1617cb7c465db3407d993/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L279-L286) in `SpringApplication`:

```java
private boolean deduceWebEnvironment() {
	for (String className : WEB_ENVIRONMENT_CLASSES) {
		if (!ClassUtils.isPresent(className, null)) {
			return false;
		}
	}
	return true;
}
```

Which deduces whether the application is web or not based on the presence of [two classes](https://github.com/spring-projects/spring-boot/blob/1df3fb6ecb04048630c1617cb7c465db3407d993/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L176-L177):

```java
private static final String[] WEB_ENVIRONMENT_CLASSES = { 
		"javax.servlet.Servlet",
		"org.springframework.web.context.ConfigurableWebApplicationContext" };
```

The problem is, the `tomcat-embed-core` jar actually *does* include `javax.servlet.Servlet`. So the `ConditionContext` used for evaluating the condition ends up having as an `environment` an object of type `StandardServletEnvironment`, which is one of the conditions used by `@OnWebApplicationCondition` for determining this is a (Spring Web MVC) web application, as seen in [this piece of code](https://github.com/spring-projects/spring-boot/blob/1df3fb6ecb04048630c1617cb7c465db3407d993/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnWebApplicationCondition.java#L72-L75):

```java
if (context.getEnvironment() instanceof StandardServletEnvironment) {
	return ConditionOutcome
			.match(message.foundExactly("StandardServletEnvironment"));
}
```

I'm not sure if activating `@OnWebApplicationCondition` for Spring Web Reactive applications is actually the desired result –they are web applications after all–, but I doubt it given there are Servlet-bound autoconfigured beans that depend on this condition, like the `ResourceUrlEncodingFilter` being configured in `ThymeleafAutoConfiguration`, as can be seen [here](https://github.com/spring-projects/spring-boot/blob/1df3fb6ecb04048630c1617cb7c465db3407d993/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafAutoConfiguration.java#L248-L259). And which currently makes startup fail every time a Spring Web Reactive application with Thymeleaf is run on Tomcat.

**Comment by bclozel** [comment]
I think #8017 and #8077 should fix part of this.
But we're missing `@OnReactiveWebApplication` (or some other name), so we could tackle this in this issue.

**Comment by snicoll** [comment]
Perhaps we need a `OnWebApplicationType` or something and the type of the application would be provided by the enum (that would match the enum in `SpringApplication`).
