### ISSUE TITLE
In Uploading Files guide <pre> tag with id="code-block-2" and id="code-block-6" are duplicate.

### ISSUE THREAD

**Issue by mirmohammad** [spring-projects/spring-boot#8122]
In the page [UploadingFiles](https://spring.io/guides/gs/uploading-files/) the "pre" tag with

**id="code-block-2"**

has conflict with

**id="code-block-6"**

You can check [here](https://github.com/spring-guides/gs-uploading-files/blob/master/complete/src/main/java/hello/Application.java) that the second one is correct.

**Comment by wilkinsona** [comment]
Thanks, but getting started guides are not managed in this repository. This is the correct repository: https://github.com/spring-guides/gs-uploading-files. Could you open an issue there please?
