### ISSUE TITLE
Spring-boot upgrade from 1.4.0 -> 1.4.4: NoSuchMethodError on RootBeanDefinion

### ISSUE THREAD

**Issue by marckamerbeek** [spring-projects/spring-boot#8133]
While upgrading from spring-boot 1.4.0 -> 1.4.4 I ran into this problem while running tests:

`java.lang.NoSuchMethodError: org.springframework.beans.factory.support.RootBeanDefinition.setTargetType(Lorg/springframework/core/ResolvableType;)V
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.createBeanDefinition(MockitoPostProcessor.java:208)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.registerMock(MockitoPostProcessor.java:187)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.register(MockitoPostProcessor.java:178)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:148)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:135)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	...
`

I'm running a unittest with a MockBean. If I see this code in MockitoPostProcessor:
`
private RootBeanDefinition createBeanDefinition(MockDefinition mockDefinition) {
		RootBeanDefinition definition = new RootBeanDefinition(
				mockDefinition.getTypeToMock().resolve());
		definition.setTargetType(mockDefinition.getTypeToMock()); <-------------- This one!
		definition.setFactoryBeanName(BEAN_NAME);
		definition.setFactoryMethodName("createMock");
		definition.getConstructorArgumentValues().addIndexedArgumentValue(0,
				mockDefinition);
		if (mockDefinition.getQualifier() != null) {
			mockDefinition.getQualifier().applyTo(definition);
		}
		return definition;
	}
`

On line 208 of the MockitoPostProcessor the method setTargetType expects an Class object and not a ResolvableType.

Could this be a runtime dependency problem? It should raise an error compile time.

I see a new version of spring-boot-starter-web (1.4.4) with a spring-beans version 4.3.2. RootBeanDefinion version 4.3.2 does not have the method setTargetType(ResolvableType resolvableType) while version 4.3.4 has it. Maybe forgotten to update version of spring-beans to 4.3.4?

Regards,

Marc

**Comment by snicoll** [comment]
It looks like you are overriding the spring framework yourself. Please don't do that. That method was added in a recent version of Spring Framework.

**Comment by marckamerbeek** [comment]
Hi Snicoll,

Thanks for your response. I think I have to make myself more clear. The provided spring-beans (4.3.2) lib in spring-boot-starter-web 1.4.4 is missing the RootBeanDefinition.setTargetType(ResolvableType resolvableType) method. I have overridden the spring-beans dependency in my project to 4.3.4 and now its working. Please check MockitoPostProcessor line 208 in spring-boot-test 1.4.4.  

I attached the dependency tree of my project. 
[depencency-tree.txt](https://github.com/spring-projects/spring-boot/files/738826/depencency-tree.txt)

**Comment by snicoll** [comment]
That's the whole point I am trying to make, `spring-boot-starter-web` 1.4.4 does _NOT_ bring Spring Framework 4.3.2 but rather 4.3.6. There is an override of the framework version in your own project (which is why this issue is flagged as invalid). If you have more question about your build, please ask them on stackoverflow.

**Comment by marckamerbeek** [comment]
Ok. Got your point. Thank you very much for your support. I'll stick with Spring boot 1.4.0 since Spring Cloud CAMDEN overrides several dependencies to version 4.3.2. I thought Spring Cloud CAMDEN was compatible with Spring Boot 1.4.x. but it doesn't work.

**Comment by spencergibb** [comment]
Camden was built and tested with 1.4.

**Comment by marckamerbeek** [comment]
Spring boot 1.4.4 does not work in combination with Spring Cloud Camden in my project. In the dependency tree I added above you can see it uses the 4.3.2 (instead of 4.3.6) in many places.  All the dependencies with 4.3.2 version comes from Cloud Camden. Do I need to override them all?

**Comment by spencergibb** [comment]
Spring Cloud doesn't explicitly set the version of Spring. It relies on spring boot for that. That being said, depending on how your project imports dependencies, there could be problems. If you could provide a project to look at, I'd be happy to.
