### ISSUE TITLE
Support canonical form for SystemEnvironment properties

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#8138]

**Comment by spencergibb** [comment]
What does 'canonical form' mean?

**Comment by mbhave** [comment]
@spencergibb We're re-doing the way configuration properties work when it comes to relaxed binding. Properties from all the different property sources will be referenced only using the "canonical" form which is the lowercased version of the original property separated in dots. Here's the first version of the rules we have for the canonical properties: https://github.com/spring-projects/spring-boot/wiki/Canonical-properties (subject to changes).

**Comment by spencergibb** [comment]
Thanks @mbhave!

**Comment by snicoll** [comment]
for the record, I am challenging the term "canonical" in #8139 as I believe that we already have a canonical format (that's the format we use in the meta-data)

**Comment by snicoll** [comment]
Isn't that a duplicate of #8139 anyway?

**Comment by wilkinsona** [comment]
@snicoll I don't think so. There are some unique aspects to dealing with environment variables

**Comment by mbhave** [comment]
Encapsulated in #4910
