### ISSUE TITLE
Unable to run application due missing asset.notNull method

### ISSUE THREAD

**Issue by yeta-io** [spring-projects/spring-boot#8140]
Bug report

Application built with spring boot version 2.0.0-BUILD-SNAPSHOT cannot start due missing Assert.notNull(single argument) method

```
java.lang.NoSuchMethodError: org.springframework.util.Assert.notNull(Ljava/lang/Object;)V
	at org.springframework.boot.bind.PropertiesConfigurationFactory.<init>(PropertiesConfigurationFactory.java:92) ~[spring-boot-2.0.0.BUILD-20170130.202942-338.jar:2.0.0.BUILD-SNAPSHOT]
```

**Comment by spencergibb** [comment]
It's an intentional change
https://github.com/spring-projects/spring-framework/commit/1b2dc3638f90508dbc98dcd8a518153fb0db62d0

**Comment by spencergibb** [comment]
A boot update is coming shortly.

**Comment by yeta-io** [comment]
Such major code changes better to publish with backward compatibility.

**Comment by yeta-io** [comment]
If it possible to push a quick fix that adds old method (with deprecation warning)? Without it I can't run any project that uses latest spring boot.

**Comment by bclozel** [comment]
As Spencer pointed out, this change was committed in Spring Framework only a couple of hours ago. Thanks for working with our SNAPSHOTs, please bear with us while we're fixing this across the Spring portfolio.

You can voice your opinion on the related Framework issue here: [SPR-15196](https://jira.spring.io/browse/SPR-15196).

**Comment by spencergibb** [comment]
@yeta-io spring 5 is making breaking changes. There are going to be incompatibilities.

**Comment by philwebb** [comment]
@yeta-io Unless you're developing features for Spring Boot itself we wouldn't recommend using SNAPSHOT versions. You should only be using `.RELEASE` versions for production.

**Comment by yeta-io** [comment]
I agree that snapshot versions are not stable, but I don't like that such trivial change breaks too much things.
I just propose to release such changes with api deprecation warning.

**Comment by bclozel** [comment]
@yeta-io This API is marked as deprecated already on the Spring Framework 4.x generation.
Breaking changes may happen with major releases, which is the case with Spring Framework 5.0.

**Comment by jiaangyu** [comment]
> It's an intentional change
> [spring-projects/spring-framework@1b2dc36](https://github.com/spring-projects/spring-framework/commit/1b2dc3638f90508dbc98dcd8a518153fb0db62d0

hello, excuse me How should this problem be solved? Do I need to upgrade the version?

**Comment by wilkinsona** [comment]
@jiaangyu Unless you are using old Spring Boot 2.0.0 snapshots, you should not have the problem described in this issue.
