### ISSUE TITLE
Allow access to line numbers and source Resource from YAML property source

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8142]
It would be super nice if we could report on the actual source (file and line number) for a property that comes from a YAML file.

**Comment by spencergibb** [comment]
That would be sweet!

**Comment by snicoll** [comment]
@philwebb is there a reason why there is a separate issue for YAML? Do we consider the .properties case solved?

**Comment by wilkinsona** [comment]
FWIW, I'd expect separate issues as they're (largely) two separate problems as we'll need properties and YAML parsers that can give us line number information.

There's an [open pull request](https://bitbucket.org/asomov/snakeyaml/pull-requests/8/loadwithnodes-keeps-a-mapping-between/diff) for SnakeYAML to add what we'd need.
