### ISSUE TITLE
org.json:json changed after updating to 1.5.1

### ISSUE THREAD

**Issue by shahbour** [spring-projects/spring-boot#8151]
After updating one of our projects to 1.5.1 we noticed that the dependency `org.json:json:20140107` has changed to `com.vaadin.external.google:android-json:0.0.20131108.vaadin1` coming from `spring-boot-configuration-processor dependency` 

The new version is older and thus miss some features that broke our code .

**Comment by snicoll** [comment]
Sorry but you shouldn't be relying on that. For all that matters, we intended to shade the JSON dependency in that project. If you need JSON in your own project, you shouldn't be relying on what that particular dependency brings.
