### ISSUE TITLE
Spring Boot 1.5.1 deprecation warning with Gradle 3.3, sub-module, and springBoot classifier

### ISSUE THREAD

**Issue by bamapookie** [spring-projects/spring-boot#8154]
I am getting this with Spring Boot 1.5.1 and Gradle 3.3.  Note there has to be a sub-module (even if it is empty) and a classifier in the springBoot task.

*build.gradle*
```
buildscript {
    ext {
        springBootVersion = '1.5.1.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'org.springframework.boot', name: 'spring-boot-gradle-plugin', version: springBootVersion
    }
}
apply plugin: 'org.springframework.boot'
repositories {
    mavenCentral()
}
dependencies {
    compile project(':sub') // Important!  Needed to reproduce the bug!
}
springBoot {
    classifier = 'boot' // Important!  Needed to reproduce the bug!
}
allprojects {
    apply plugin: 'java'
}
task wrapper(type: Wrapper) {
    gradleVersion = '3.3'
    distributionType = Wrapper.DistributionType.ALL
}
```

*settings.gradle*
```
include 'sub'
```

Empty sub/build.settings file.

Running `./gradlew clean` will invoke the error.

**Comment by wilkinsona** [comment]
I'm not sure there's much we can do about this. The call to the deprecated API is being made by Gradle:

```
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
        at org.gradle.api.internal.artifacts.dependencies.AbstractModuleDependency.getConfiguration(AbstractModuleDependency.java:56)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getConfiguration(Unknown Source)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibrariesForFileDependencies(ProjectLibraries.java:132)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibraries(ProjectLibraries.java:113)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.doWithLibraries(ProjectLibraries.java:90)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.addLibraryDependencies(RepackagePluginFeatures.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.setupInputOutputs(RepackagePluginFeatures.java:151)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:136)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:114)
```

Note that we're calling ProjectDependency.getConfiguration(), the implementation of which is calling `ModuleDependency.getConfiguration` which is deprecated.

**Comment by wilkinsona** [comment]
@eriwen If you have a moment, your input would be much appreciated here

**Comment by eriwen** [comment]
@wilkinsona Acknowledged. I've raised this with the team and I expect we'll get back to you with guidance in the next few days.

**Comment by eriwen** [comment]
@wilkinsona This looks very similar to #8120. You say you're calling `ProjectDependency.getConfiguration()`. Is there any reason you can't replace that with `.getTargetConfiguration()`? 

The nebula-dependency-recommender-plugin had this same issue and resolved it [thusly](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/commit/08f18360bad7b5e6c2971e7d7717d98001c18f21#diff-f6d49aabb8efe40a937ed8597b0b28a4).

Additional information available at https://github.com/gradle/gradle/issues/1311

Let me know if that does not solve your need.

**Comment by wilkinsona** [comment]
@eriwen Unless I've missed it, `getTargetConfiguration()` doesn't exist in Gradle 2.9 which is the minimum version the we support. I guess we could resort to reflection but I'd prefer it if that wasn't necessary.

**Comment by pkubowicz** [comment]
@wilkinsona Could you backport this fix to Spring Boot 1.4? I am not able to update to Spring Boot 1.5 because I am forced to stay with an older release of Spring Data. Gradle team does not fix bugs in versions older than current, so I have to update it to avoid being exposed to bugs. As result, I cannot use Gradle 2 as it has broken Maven support (https://issues.gradle.org/browse/GRADLE-3496). Maven is broken again in 3.5 (https://github.com/gradle/gradle/issues/1811). I would like to use Gradle 4.0 as it promises an important fix to Maven publishing, but this issue breaks Gradle.

I understand Gradle >2 is not officially supported in Spring Boot 1.4, but backporting this fix does not seem to be complicated or risky, and enables users to at least try to use Gradle 4+.

**Comment by eriwen** [comment]
Note that we will have Gradle 3.5.1 early next week which fixes
gradle/gradle#1811

**Comment by wilkinsona** [comment]
@pkubowicz I am rather reluctant to introduce the use of reflection in 1.4 to attempt to support something that we have already stated that we do not support. It's very difficult to justify the risk (and there is always some risk).

> https://issues.gradle.org/browse/GRADLE-3496

That issues claims to be fixed in 2.14.1. Is that not an option for you?

**Comment by pkubowicz** [comment]
Generally, I don't like the idea that a single library is able to force me to choose which build tool should I use. For me it's more natural that build dependencies and project dependencies are completely independent. I would welcome a possibility that you can use the most current Spring Boot Gradle plugin with the Spring Boot JAR version overridden to an older release.

**Comment by wilkinsona** [comment]
> Generally, I don't like the idea that a single library is able to force me to choose which build tool should I use.

I don't believe we're forcing you. You are free to ignore the deprecation warning if you wish.

>  I would welcome a possibility that you can use the most current Spring Boot Gradle plugin with the Spring Boot JAR version overridden to an older release

That's already possible, although not recommended, with 2.0 snapshots.
