### ISSUE TITLE
SpringBoot 1.5.1 - /public no longer public

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#8155]
With security enabled, it was necessary to add folders that are under /resource/pubic as shown in the snippet below.
Previous version was 1.4.3 - and everything under public was available .

Switching between versions (no other code changes) yields consitent reproducability

```` 
// only needed in 1.5.1:
				.authorizeRequests()
					.antMatchers( "/css/**" , "/js/**", "/images/**" )
					.permitAll()
````

**Comment by wilkinsona** [comment]
@peterdnight Sorry, I don't really understand your description of the problem. Can you provide some more context, please? I'm assuming that code is from a `WebSecurityConfigurerAdapter` subclass. What order does it have? What else does it do? Can you please provide a complete example that works with 1.4.3 and fails with 1.5.1?

**Comment by peterdnight** [comment]
Clarifications:
1. SpringSecurity is being used. Snippet is standard spring HttpSecurity builder.
2. By default: items stored in /src/main/resources/public are NOT  protected in SpringBoot 1.4.2 and all earlier releases.
3. Start up any secured boot application - user your browser to try and grab an image file placed inside /public.

**Comment by philwebb** [comment]
@peterdnight Are you able to upload a sample application to GitHub so we can see exactly what you mean?

Number 3 in your list above (putting a resource in `/resources/public/sample.png`) is particularly confusing since the matcher in your original report uses `/images/**`.

A sample will definitely be the best way to ensure we're not talking at cross purposes.

**Comment by peterdnight** [comment]
that is the way spring security works. Ant-matchers work on resolved urls, not on locations within the jar.

**Comment by philwebb** [comment]
@peterdnight Right, but `src/main/resources/public/sample.png` is mapped to `http://localhost:8080/sample.png` where as your matcher is looking at the URL `/images/**`.

Please provide a sample, I think it will be quicker in the long run.

**Comment by peterdnight** [comment]
the antmatcher workaround was for my scenarios.... for sample.png reproduce scenario - antmatcher would also be  /sample.png

sorry for the confusion

**Comment by philwebb** [comment]
@peterdnight I believe that that's the expected behavior and it appears to happen with 1.4 as well. By default, the following patterns are ignored `"/css/**", "/js/**", "/images/**", "/webjars/**", "/**/favicon.ico"` so if you ask for `/sample.png` you'll get redirected to login.

To proceed further with this issue we will need a sample that clearly shows the problem.

**Comment by peterdnight** [comment]
drop the file into /public/images. Get the login page.

I definitely understand your hesitation to reproduce - but this is the best i can do.

**Comment by philwebb** [comment]
> I definitely understand your hesitation to reproduce

It's not that I'm hesitant to reproduce, I've tried but so far I can't find any differences between 1.4 and 1.5.

 > but this is the best i can do

Without a sample application I don't think we can continue. If you have some time in the future please upload something please do and we'll take another look

**Comment by peterdnight** [comment]
I dug a little deeper. Summarized:  adding @EnableWebSecurity  disables the registration of /images, /css, /js, 

1.  This appears in 1.4.x, it does not appear in 1.5.1when @EnableWebSecurity  is added
````
2017-02-01 11:13:15.067  INFO 8664 --- [  restartedMain] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: OrRequestMatcher [requestMatchers=[An
t [pattern='/css/**'], Ant [pattern='/js/**'], Ant [pattern='/images/**'], Ant [pattern='/webjars/**'], Ant [pattern='/**/favicon.ico'], Ant [pattern='/error']]
], []

````

2.  Using the spring managed project:
-  https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-secure

- Key to reproduce: adding to SampleWebSecureApplication:
@EnableWebSecurity 

- this appears to disable registration of the public resources. Eg starting without @EnableWebSecurity shows the /images, /css registration, starting with - this is gone.

3. Hitting: http://localhost.cisco.com:8080/css/bootstrap.min.css with @EnableWebSecurity  included redirects to login page. Removing it - and it resolves/behaves correctly

**Comment by wilkinsona** [comment]
This is the same problem as #8172.
