### ISSUE TITLE
Problem with Eclipse formatter

### ISSUE THREAD

**Issue by bbrouwer** [spring-projects/spring-boot#8156]
I have followed the contributor instructions on getting Eclipse setup using the .setup file so I can contribute back to spring-boot. Now, every time I edit a .java file, I am greeted with this error:

```
A save participant caused problems.
  The save participant 'Code Clean Up' caused an exception: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/String;)J. See the error log for details.
```

When I check the project properties for the java formatting, I get the error `The currently displayed page contains invalid values.` 

This is Eclipse Mars.2 on Windows 7 with JDK 1.8_0_112

**Comment by bbrouwer** [comment]
Here are some logs from Eclipse.

[logs.zip](https://github.com/spring-projects/spring-boot/files/743059/logs.zip)

**Comment by philwebb** [comment]
That's an interesting error, it doesn't appear to be related to any of the plugins that we've added. The 'Code Clean Up' action is a standard part of Eclipse.

Have you tried Neon? I recently upgraded and things have generally been fine for me (but I'm on OSX).

**Comment by bbrouwer** [comment]
The log says the error occurred here:
```
at org.springframework.ide.eclipse.jdt.formatter.internal.DefaultCodeFormatter.tokenizeSource(DefaultCodeFormatter.java:343)
```
which is this code in DefaultCodeFormatter:
```
Scanner scanner = new Scanner(true, false, false/* nls */, CompilerOptions.versionToJdkLevel(this.sourceLevel),
				null/* taskTags */, null/* taskPriorities */, false/* taskCaseSensitive */);
```
The instructions say to use Eclipse Mars. I did try to install Neon, but the Oomph installer gave me the following errors:
[setupLogs.zip](https://github.com/spring-projects/spring-boot/files/743099/setupLogs.zip)

**Comment by philwebb** [comment]
Thanks, I didn't see that in the logs.

**Comment by bbrouwer** [comment]
Is there a recommended path for me to proceed? Right now, it looks like nothing is formatting in Eclipse, which I'm sure will make for a poor pull request.

**Comment by philwebb** [comment]
You can remove the custom formatter plugin and we can format up the PR when it comes in. We usually reformat stuff anyway in some form or another.

**Comment by bbrouwer** [comment]
For a solution, I am fine with fixing it on Mars, or better yet, getting the .setup file to work with Neon and then changing the doc to reference Neon instead.

**Comment by wilkinsona** [comment]
I have a local .setup file that almost works with Oxygen. The last piece in the puzzle is https://github.com/philwebb/m2eclipse-maveneclipse/pull/3. The formatter already seems to work fine with Oxygen (although it's been working fine with me in Mars, too, so that may not mean us much).

**Comment by wilkinsona** [comment]
We've [dropped](https://github.com/spring-projects/spring-boot/commit/1f8bc391ced808ba98e40d7d619763e71d22ccaf) the use of the custom formatter.
