### ISSUE TITLE
in Neo4j, common relation(property node) can't be loaded under depth=1,  but the relationship node in relation entity are loaded recursively. 

### ISSUE THREAD

**Issue by gaurence** [spring-projects/spring-boot#8158]
I am using the spring boot for neo4j, always meet a doubt(maybe issue) for relationship node loading. the scenario as follows:

```
@NodeEntity
class Teacher{
	@Relationship(type = "HAS_SCHOOLLOCATION", direction = Relationship.OUTGOING)
	SchoolLocation schoolLocation;// 
....set/and get
}

@NodeEntity
public class SchoolLocation  {
	@GraphId
	Long id;
	private String name;
	private String address;
	private Long longitude;
	private Long latitude;
	@Relationship(type = "HAS_SCHOOLLOCATION", direction = Relationship.INCOMING)
	List<Teacher> teacher;
//...set/get
}
```

I create a `Teacher` with location and saved it . in Neo4j console , the data is there . but when i use session `loadall`, the schoollocation always null

```
session.loadAll(Teacher.class, filters, depth);// depth=1.
```

and actually another issus is if depth equal 1, if the Teacher is another friend(teacher), (TEACHER_RELATION_ENTITY), the friend teacher will be load recursively.

The issue block few days, please help ,thank you.
note: i updated the release to 1.5.1.realse,issue still there.
Best Regards,
Michael

**Comment by philwebb** [comment]
I'm afraid that this doesn't sound like a Spring Boot bug. Spring Boot simply configures Spring Data and Neo4J. You're best bet is to ask a question on stackoverflow.com.

**Comment by gaurence** [comment]
thank you!
