### ISSUE TITLE
Gradle project dependencies broken with spring-boot 1.4.0 and higher

### ISSUE THREAD

**Issue by dkesler** [spring-projects/spring-boot#8160]
It appears that starting with the spring boot 1.4.0.RELEASE plugin, in multi-project builds, project dependencies on other projects that use the spring-boot plugin have broken.  Specifically, if you have a `dependency` project and a `dependent` project which depends on `dependency`, both using the spring-boot plugin, then under certain conditions, the `dependent` project will be unable to use classes built in the `dependency` project.  It appears that the error happens when a build is run from the root of the gradle project on the entire project.  If a build is run from within the `dependent` project, or is run as `./gradlew :dependent:build`, the build works fine.

I've put up a sample project displaying the issue here:  https://github.com/dkesler/gradle-spring-boot-bug

samples.sh shows some example commands, some of which work, some of which dont.  The project is set up for gradle 2.14.1.  Spring-boot 1.3.6.RELEASE works whether or not the spring-boot plugin has been applied to the `dependency` project.  Spring-boot 1.5.1.RELEASE only works if the spring-boot plugin is not applied to `dependency` or if only `dependent` is built.  

I've also tested 1.4.0.RELEASE and seen the same behavior as 1.5.1.RELEASE.

I've also tested 1.5.1.RELEASE with gradle 3.3 and seen the same behavior.  (I can't test 1.3.6.RELEASE with gradle 3.3 since I get a completely unrelated error trying to use those versions together).

Let me know if you need any more information.

**Comment by wilkinsona** [comment]
This is due to the change in the layout of a repackage fat jar in 1.4. The [documentation describes](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-an-additional-executable-jar) what you should do.

**Comment by dkesler** [comment]
Ah, I read the release notes talking about the layout change, but i didn't realize the project dependency actually used the repackaged jar and the notes didn't state that it would break project dependencies.  (Maybe because they weren't intended to be used that way to begin with, but they used to).  

FWIW, It's kind of tough to get from the symptoms of the problem to that particular segment of the documentation.  I'm not sure if there's a better way of tying them together.

Thanks for the help and quick response.
