### ISSUE TITLE
Bad dependency

### ISSUE THREAD

**Issue by dimarassin** [spring-projects/spring-boot#8166]
**org.springframework.boot:spring-boot-configuration-processor:1.5.0.RELEASE** has unresolved dependency on **org.springframework.boot:spring-boot-test-support:1.5.0.RELEASE** which cause the build to fail

**Comment by snicoll** [comment]
This is a known issue (#8136) and the reason why `1.5.1.RELEASE` was released right the way. Please upgrade (see [the announcement](https://spring.io/blog/2017/01/30/spring-boot-1-5-1-released))

**Comment by dimarassin** [comment]
cool, thanks!
