### ISSUE TITLE
@DataMongoTest bug with Eureka and Actuator

### ISSUE THREAD

**Issue by JMesens** [spring-projects/spring-boot#8170]
Spring Boot version: 1.5.1

Bug:
Application doesn't start

    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

Reproduce:
Put these on the classpath:
````
org.springframework.cloud:spring-cloud-starter-eureka
org.springframework.boot:spring-boot-starter-data-mongodb
org.springframework.boot:spring-boot-starter-actuator
de.flapdoodle.embed:de.flapdoodle.embed.mongo
````
Decorate the application

    @EnableEurekaClient

Make a test with the @DataMongoTest like:

````
@DataMongoTest
@RunWith(SpringRunner.class)
public class MongoTest {

    @Test
    public void contextLoads() {
    }
}
````

**Comment by wilkinsona** [comment]
You are trying to use a test slice, where only specific beans are registered, yet by placing `@EnableEurekaClient` on your main application class you've made your whole application require Eureka Client. If you want to test a specific slice, then you need to structure your configuration accordingly. Specifically, you should move `@EnableEurekaClient` to a more specialised configuration class.

We have #7999 to improve the documentation.
