### ISSUE TITLE
Embedded LDAP server schema validation options

### ISSUE THREAD

**Issue by mouellet** [spring-projects/spring-boot#8171]
Quote from UnboundID LDAP SDK for Java Documentation:
> It provides the option to use a schema for data validation and to perform the most accurate matching. By default, it will use a default schema populated with a number of standard attribute types and object classes from various RFCs and IETF drafts, but you can configure it to use a custom schema, or you can disable schema validation altogether. 

We need a way to deactivate the schema validation or provide a custom one. This can be achieved by calling `InMemoryDirectoryServerConfig.setSchema(Schema schema)`, passing `null` deactivates the validation.

Using configuration properties would be a good option, `spring.ldap.embedded.validation.enabled` and `spring.ldap.embedded.validation.schema` to specify a custom schema file location.

**Comment by snicoll** [comment]
Closing in favour of PR #8195 

@mouellet if you intend to submit a PR right the way, there is no need for a separate issue. Thanks!
