### ISSUE TITLE
JavaScript not running anymore after update to Spring Boot 1.5.1

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#8172]
I have a working Spring Boot 1.4.3 application I want to update to 1.5.1. After the update, it looks like no CSS is loaded. The chrome dev tools show:

"Refused to execute script from 'http://localhost:8080/webjars/jquery/jquery.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

![image](https://cloud.githubusercontent.com/assets/1115823/22523489/e5e7e584-e8bf-11e6-8404-136e6b2241a7.png)

I am using Spring Security and Webjars. Is there anything changed in 1.5.1 that could explain this behaviour ?

**Comment by wilkinsona** [comment]
Sounds like your webjars are secured so the browser's being served an HTML error page rather than the JavaScript. It's impossible to say why that's happening without some more information. Can you provide a sample that reproduces the problem?

**Comment by wimdeblauwe** [comment]
Would it help to give my security config?

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Autowired
    private UserDetailsService userDetailsService;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailsService)
            .passwordEncoder(passwordEncoder);
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
            .antMatchers("/", "/home").permitAll()
            .antMatchers("/management/health", "/management/info").permitAll()
            .antMatchers("/management/**").hasRole(UserRole.ADMIN.name())
            .anyRequest().authenticated()
            .and()
            .formLogin().loginPage("/login")
            .permitAll()
            .and()
            .logout().permitAll();
    }
}
```

**Comment by wilkinsona** [comment]
A little.

We've changed how the ignored paths are auto-configured in 1.5. In 1.4, the Actuator would always configure ignored paths even if you'd used `@EnableWebSecurity` which should have indicated that you want to take complete control of your application's web security. In 1.5, the Actuator now just contributes an `IgnoredRequestCustomizer` that will be used by the security auto-configuration to customise ignored paths.

Your use of `@EnableWebSecurity` is switching this auto-configuration off so you need to configure the ignored paths yourself or remove `@EnableWebSecurity` if you want your configuration to be additive.

**Comment by wilkinsona** [comment]
Can you try one of the two suggestions above and let us know if it fixes your problem?

**Comment by wimdeblauwe** [comment]
Removing `@EnableWebSecurity` seems to fix it. No idea why I have added it in the first place.

**Comment by wilkinsona** [comment]
Reopening to remind me to update the release notes

**Comment by wilkinsona** [comment]
I've updated the release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#ignored-paths-and-enablewebsecurity

**Comment by AleixAlcover** [comment]
I'm facing a similar problem after migrating from 1.5 to 2.0, but the difference is that my web app is accessed by several domains. With the main one, everything works smoothly, but not with the secondary ones, that arise this error in the browser:

> **Refused to execute script from '' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled**

What makes different a secondary domain, is that with a HandelInterceptor I control that they just can access its directory. For example; maindomain.com/1/ works fine but secondarydomain.com/1/ doesn't work.

I have placed this question in Stackoverflow with more detailed information and some code:
[https://stackoverflow.com/questions/49742053/spring-boot-2-0-0-static-resources-with-different-domains-for-the-same-app](https://stackoverflow.com/questions/49742053/spring-boot-2-0-0-static-resources-with-different-domains-for-the-same-app)

Thanks in advance for any help.

**Comment by lguan2** [comment]
@AleixAlcover Did you resolve it? I have the same issue.

**Comment by AleixAlcover** [comment]
@lguan2 No I didn't, and no one has answered to my question.

**Comment by lguan2** [comment]
@AleixAlcover I just solved the problem on my side. I found that after migrating to 2.0.1, all static resource requests go to my interceptor. After excluding the static resource path in the intercepter registration, it works for me. Not sure if this can help you.

**Comment by AleixAlcover** [comment]
@lguan2 I have just migrated to 2.0.3 and your solution has worked fine for me. Thank you.

**Comment by gotoark** [comment]
> @AleixAlcover I just solved the problem on my side. I found that after migrating to 2.0.1, all static resource requests go to my interceptor. After excluding the static resource path in the intercepter registration, it works for me. Not sure if this can help you. How can i  do that in Spring boot 2.0.6.?

**Comment by AleixAlcover** [comment]
That's what I did, and works fine for me with the 2.0.4 version:

@Configuration
public class MyAppConfigurer implements WebMvcConfigurer{
...
@Override
public void addInterceptors(InterceptorRegistry registry) {
...
    registry.addInterceptor(rootDomainInterceptor())
            .excludePathPatterns("/js/**", "/css/**", "/images/**", "/webjars/**");
}

**Comment by hendisantika** [comment]
I have that issue. 
My bootstrap navbar doesn't show.

Can You help me @AleixAlcover ?
Thanks

**Comment by AleixAlcover** [comment]
@hendisantika , please check the code from my previous post. The rootDomainInterceptor() is an implementation of  **HandlerInterceptor**, where I deal with the different domains (DNS) accessing the app. What does the code, is to exclude the paths of all static resources from that HandlerInterceptor. I guess in your case, you have to exclude the paths where are located the different components of bootstrap.

**Comment by hendisantika** [comment]
Would You please check my repository @AleixAlcover --> [here](https://github.com/hendisantika/SpringBoot-Thymeleaf-Template)

I can't see any solutions for my case.

Thanks

**Comment by snicoll** [comment]
Please move that discussion off the issue tracker. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by hendisantika** [comment]
OK. Sorry for that @snicoll .
