### ISSUE TITLE
@Validated - Default member variable values not filled

### ISSUE THREAD

**Issue by derTobsch** [spring-projects/spring-boot#8173]
Spring Boot 1.5.1/1.4.4

I tried the @Validated annotation as explained in the changelog of spring boot 1.5.1. I tried it with both version 1.4.4 and 1.5.1 and get the same exception. So before @Validated will be mandatory I wanted to share my experiences.

> @ConfigurationProperties validation
> 
> If you have @ConfigurationProperties classes that use JSR-303 constraint annotations, you should now additionally annotate them with @Validated. Existing validation will currently continue to work, however, a warning will be logged. In the future, classes without @Validated will not be validated at all.

I started a project with own spring boot starters and everything was fine until I started to use the @Validated annotation. Since then the `PropertiesConfigurationFactory` in line 348 contains errors on validating my ConfigurationProperties because every member variables are "empty". Strings are null and ints are 0.  `dataBinder->bindingResult->target` in the `PropertiesConfigurationFactory` contains only the default values of the types.
This seems to be some bug with cglib? It feels like that the proxy is not correctly instantiated or the validation is to early?
I tried to reproduce this with a small sample project but I could not recreate it.

Maybe you got some idea, what it could be. Maybe something with aop and cglib?

```java
@Validated
@ConfigurationProperties("coffeenet.logging.file")
public class CoffeeNetLoggingFileProperties {

    @NotBlank(message = "Please provide a file where your logs will be written e.g. logs/app.log")
    private String file = "logs/app.log";

    @NotBlank(message = "Please provide a file name pattern with a date pattern e.g. logs/app-%d{yyyy-MM-dd}.log")
    private String fileNamePattern = "logs/app-%d{yyyy-MM-dd}.log";

    @Min(value = 1, message = "Only positive integers are allowed for the maximum amount of history files.")
    @NotNull(message = "Please provide a maximum amount of history files you want to keep.")
    private int maxHistory = 30;

// getters and setters
```
Will be injected into a AutoConfiguration and exposed as bean through @EnableConfigurationProperties on the class level of the AutoConfiguration.

With the output
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target coffee.synyx.autoconfigure.logging.CoffeeNetLoggingFileProperties@1548b9a4 failed:

    Property: coffeenet.logging.file.fileNamePattern
    Value: null
    Reason: Please provide a file name pattern with a date pattern e.g. logs/app-%d{yyyy-MM-dd}.log

    Property: coffeenet.logging.file.file
    Value: null
    Reason: Please provide a file where your logs will be written e.g. logs/app.log

    Property: coffeenet.logging.file.maxHistory
    Value: 0
    Reason: Only positive integers are allowed for the maximum amount of history files.


Action:

Update your application's configuration
```

**Comment by wilkinsona** [comment]
@derTobsch Thanks for the analysis

> This seems to be some bug with cglib? It feels like that the proxy is not correctly instantiated or the validation is to early?

This is interesting. What makes you think that CGLib is involved?

By default a proxy will not be created for a configuration properties bean. I deliberately did something daft and added `@EnableAsync(proxyTargetClass=true)` to a main configuration class and added `@Async` to a getter on a configuration properties class to force it to be proxied. I didn't have any problems with validation. This is what I'd expect as `AbstractAdvisingBeanPostProcessor` creates the proxy in `postProcessAfterInitialization` whereas configuration property binding and validation is done in `postProcessBeforeInitialization`.

> I tried to reproduce this with a small sample project but I could not recreate it.

Unfortunately, I think we're going to need a sample (it needn't be small) as it's not obvious how you're getting into a situation where a configuration properties bean has been proxied before it's being validated.

**Comment by derTobsch** [comment]
> This is interesting. What makes you think that CGLib is involved?

because when I debug into the code at `PropertiesConfigurationFactory` the `dataBinder->bindingResult->target`, which should be the my ConfigurationProperty class is of `coffee.synyx.autoconfigure.logging.CoffeeNetLoggingFileProperties$$EnhancerBySpringCGLIB$$5ae1eaca@6128` and there a several properties called `GLIB$CALLBACK_1` to `GLIB$CALLBACK_$n` and `CGLIB$BOUND` is false.

I debugged into `postProcessAfterInitialization` and when one of my ConfigurationProperties comes along with @Validated the if conditions `isEligible(bean, beanName)` and `!proxyFactory.isProxyTargetClass()` are both true and it runs into

```java
		if (isEligible(bean, beanName)) {
			ProxyFactory proxyFactory = prepareProxyFactory(bean, beanName);
			if (!proxyFactory.isProxyTargetClass()) {
				evaluateProxyInterfaces(bean.getClass(), proxyFactory);
			}
			proxyFactory.addAdvisor(this.advisor);
			customizeProxyFactory(proxyFactory);
			return proxyFactory.getProxy(getProxyClassLoader());
		}
```

 The return statement in line 90 returns

```
{coffee.synyx.autoconfigure.web.CoffeeNetWebProperties$$EnhancerBySpringCGLIB$$8b0e1d06@7591} "coffee.synyx.autoconfigure.web.CoffeeNetWebProperties@553da911"
 CGLIB$BOUND = false
 CGLIB$CALLBACK_0 = {org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor@7603} 
 CGLIB$CALLBACK_1 = {org.springframework.aop.framework.CglibAopProxy$StaticUnadvisedInterceptor@7604} 
 CGLIB$CALLBACK_2 = {org.springframework.aop.framework.CglibAopProxy$SerializableNoOp@7605} 
 CGLIB$CALLBACK_3 = {org.springframework.aop.framework.CglibAopProxy$StaticDispatcher@7606} 
 CGLIB$CALLBACK_4 = {org.springframework.aop.framework.CglibAopProxy$AdvisedDispatcher@7607} 
 CGLIB$CALLBACK_5 = {org.springframework.aop.framework.CglibAopProxy$EqualsInterceptor@7608} 
 CGLIB$CALLBACK_6 = {org.springframework.aop.framework.CglibAopProxy$HashCodeInterceptor@7609} 
 profileServiceName = null
 logoutPath = null
```
The `logoutPath` and the `profileServiceName` has default values.

```java
@Validated
@ConfigurationProperties("coffeenet.web")
public class CoffeeNetWebProperties {

    @NotEmpty
    private String profileServiceName = "profile";

    @NotEmpty
    private String logoutPath = "/logout";

//getters and setters
```
I am not familiar with the cglib and how spring works with it, so I hope I could give you some information. I see what I can do to create starters or open source ours to have a sample project. When you need further information just ask and I see what I can do for you :)

I hope I can provide a sample project.

**Comment by wilkinsona** [comment]
@derTobsch Thanks. That aligns with what I attempted to describe above and with what I am seeing. The key thing is that the proxying happens in `postProcessAfterInitialization` when the validation should already have occurred during `postProcessBeforeInitialization`. I don't understand why that's apparently not the case and I think I'll need to see a sample to get to the bottom of it.

**Comment by OrangeDog** [comment]
I think I've got the same thing, here's the logging that I get:
```
[ERROR] [main] 16:37:59.482 PropertiesConfigurationFactory - Properties configuration failed validation
[ERROR] [main] 16:37:59.482 PropertiesConfigurationFactory - Field error in object 'myconfig' on field 'key': rejected value [null]; codes [NotNull.myconfig.key,NotNull.key,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [myconfig.key,key]; arguments []; default message [key]]; default message [may not be null]
[WARN] [main] 16:37:59.483 AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myConfig': Could not bind properties to MyConfig (prefix=myconfig, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
[ERROR] [main] 16:38:01.721 LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target MyConfig(key=xxxxxxxxxxxxxxxxxxxx) failed:

    Property: myconfig.key
    Value: null
    Reason: may not be null
```
Note the inconsistent reporting of whether the property was `null` or not.

I tried extracting an interface from the class and injecting with that, but it got worse:
```
[ERROR] [main] 16:32:51.301 SpringApplication - Application startup failed
java.lang.NullPointerException: null
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$ValidatedLocalValidatorFactoryBean.supports(ConfigurationPropertiesBindingPostProcessor.java:423)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.determineValidator(ConfigurationPropertiesBindingPostProcessor.java:353)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:314)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296)
    at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:100)
    at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:88)
    at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:120)
    at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:49)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
    at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.afterSingletonsInstantiated(ConfigurationPropertiesRebinderAutoConfiguration.java:79)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
    at com.example.Application.main(Application.java:39)
```
AFAIKT it was the `getPackage()` call that returned `null`, because the type was `com.sun.proxy.$Proxy149`.

In my case, `@ConfigurationProperties` is not on the class, but on the `@Bean` method.
Before changing anything there are also multiple warnings for the same class, both with and without class proxies:
```
The @ConfigurationProperties bean class MyClass contains validation constraints but had not been annotated with @Validated.
The @ConfigurationProperties bean class MyClass$$EnhancerBySpringCGLIB$$b1b6728e contains validation constraints but had not been annotated with @Validated.
```

**Comment by wilkinsona** [comment]
> I think the proxy is added because I already have a BeanValidationPostProcessor adding MethodValidationInterceptor advice.

Could you share some code that does that please?

**Comment by OrangeDog** [comment]
> Could you share some code that does that please?
```
@Bean
public BeanValidationPostProcessor beanValidationPostProcessor(ValidatorFactory factory) {
    BeanValidationPostProcessor bean = new BeanValidationPostProcessor();
    bean.setValidatorFactory(factory);
    return bean;
}
```
It seems I was mistaken. I removed that bean but `MyConfig` is still proxied when it gets bound.
The `ProxyFactory` is
```
org.springframework.aop.framework.ProxyFactory: 0 interfaces []; 1 advisors [org.springframework.aop.support.DefaultPointcutAdvisor: pointcut [AnnotationMatchingPointcut: org.springframework.aop.support.annotation.AnnotationClassFilter: interface org.springframework.validation.annotation.Validated, MethodMatcher.TRUE]; advice [org.springframework.validation.beanvalidation.MethodValidationInterceptor@17752474]]; targetSource [SingletonTargetSource for target object [com.example.MyConfig@5d489be4]]; proxyTargetClass=true; optimize=false; opaque=false; exposeProxy=false; frozen=false
```
I'm looking to see if there's anything else I did to add that advice.

**Comment by derTobsch** [comment]
The latest version 1.5.2.BUILD-SNAPSHOT does not fix the bug.

<pre>
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target CoffeeNetLoggingFileProperties{enabled=null, file='logs/app.log', fileNamePattern='logs/app-%d{yyyy-MM-dd}.log', pattern='%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%t] %-40.40logger{39} : %m%n%wEx', maxHistory=30} failed:

    Property: coffeenet.logging.file.fileNamePattern
    Value: null
    Reason: Please provide a file name pattern with a date pattern e.g. logs/app-%d{yyyy-MM-dd}.log

    Property: coffeenet.logging.file.maxHistory
    Value: 0
    Reason: Only positive integers are allowed for the maximum amount of history files.

    Property: coffeenet.logging.file.pattern
    Value: null
    Reason: Please provide a log patter for your logs.

    Property: coffeenet.logging.file.file
    Value: null
    Reason: Please provide a file where your logs will be written e.g. logs/app.log


Action:

Update your application's configuration
</pre>

**Comment by wilkinsona** [comment]
@derTobsch That doesn't look like you're getting the bug tracked in #8277, but also looks like my guess that the two may be related was wrong. As I've said above, I can't reproduce the very early proxying of the `@ConfigurationProperties` bean and we're going to need a sample that reproduces the problem.  [Your comment](https://github.com/spring-projects/spring-boot/issues/8277#issuecomment-279662007) on the other issue suggests you may have made some progress in that regard.

**Comment by derTobsch** [comment]
I also think this two are not related. I made a sample project that recreated the bug in #8277 and I tried to reproduce this bug with it but nothing worked as I thought. I hoped that it would be easier to recreate the bug with the results from #8277, because I have not much time these days to debug the code. I will let you know when I have a example project. Sorry that it will take some time.

**Comment by snicoll** [comment]
I think I've found a way to reproduce the error, see https://github.com/spring-projects/spring-boot-issues/commit/261b90ec896999964286bac870fc14a4f5c5e18e

**Comment by snicoll** [comment]
@OrangeDog looking at your report, it is not the same as this one. Could you please create a separate issue with a sample. If you can, please test with `1.5.2.BUILD-SNAPSHOT` first.

**Comment by derTobsch** [comment]
@snicoll that is the bug. Thanks! I also can not recreate the issue with 1.4.. I tried it with my starters and with your code and everything worked. So I think that was my fault.

**Comment by snicoll** [comment]
Alright so Spring Boot does bind that stuff has part of the `BeanPostProcessor` contract which gives us the raw object. For some reason, Spring Cloud calls the binding again as part of its "rebinder" feature. Unfortunately it does so on the proxy if there is one. 

The good news is that it's calling our code so we might be able to do something about it. 

über-ping @dsyer

**Comment by snicoll** [comment]
Definitely a Spring Cloud issue (see https://github.com/spring-cloud/spring-cloud-commons/issues/177). Not sure how we should address it at this point.

**Comment by snicoll** [comment]
OK so I've done a bit of research. Our BPP is processing the bean in the  `postProcessBeforeInitialization` phase and it has `Ordered.HIGHEST_PRECEDENCE + 1`.

I've tried to configure `MethodValidationPostProcessor` with order `HIGHEST_PRECEDENCE` (`ProxyProcessorSupport` are `LOWEST_PRECEDENCE` by default so that's already _very_ unusual). Even with that setup, our BPP gets the raw bean as the creation of the proxy happens in `postProcessAfterInitialization`. 

I am sorry but there is nothing I can do here and I am not keen to add code to unwrap a proxy because Spring Cloud is calling our BPP directly outside of its contract. This will have to be handled by the issue I've raised.

**Comment by derTobsch** [comment]
Thanks @snicoll for your help! I am happy that you could recreate the bug. For now I will not use the @Validated annotations until spring cloud will fix that :)

**Comment by OrangeDog** [comment]
> it is not the same as this one

Are you sure @snicoll? The descriptions seem to match up exactly: the properties are all null, because the bean has been proxied by spring-cloud before it got to the validation.

**Comment by snicoll** [comment]
> Are you sure @snicoll?

Pretty much, your stacktrace there has a `NullPointerException` which is quite different from what I've seen so far. If you are convinced that this is the same issue based on the analysis above, I am cool with that.

**Comment by OrangeDog** [comment]
@snicoll that was just because I tried to work around it by changing the type of the proxy. The route cause is the same.
If you're happy that throwing code should never be given a proxy in the first place, then there's no more to do but wait for the spring-cloud fix.
