### ISSUE TITLE
Create caches using @Cacheable (not `spring.cache.cache-names`) for JSR107

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8183]
Ideally I don't think I'd even want to have to provide `spring.cache.cache-names` because I already listed all the caches in my `@Cacheable` annotations. It works like that with the default in-memory cache, but not with a JSR-107 provider.

**Comment by snicoll** [comment]
we do [create them with a default cache config](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.java#L92-L97). Can you show concretly what the problem is?

**Comment by dsyer** [comment]
This petclinic issue sums it up: https://github.com/spring-projects/spring-petclinic/issues/227. You have to put ehcache dependency back into pom to see that.

**Comment by snicoll** [comment]
The caches are created and something fishy is happening either in ehcache or petclinic as far as I can see. Let's investigate on that side then.

**Comment by dsyer** [comment]
UPDATE: the problem with the PetClinic is cause by poor implementation of the enitities (they aren't properlry `Serializable`). But I'd still like to create the caches from the annotations if possible.

**Comment by snicoll** [comment]
That's the behaviour of the JSR-107 spec so we can't create one on the fly. I am not keen to offer that option (and regardless, this is a core framework topic).
