### ISSUE TITLE
Spring Boot 1.5.1 + Spring MVC + Java 6  = Maven missing Jackson BOM 2.6.x

### ISSUE THREAD

**Issue by lucamartellucci** [spring-projects/spring-boot#8192]
Hi,
I've found a problem using Spring Boot 1.5.1, Spring MVC and Java 6.
I've followed the official documentation that describes how to setup the pom.xml to get spring boot working with java 6. The doc is here: http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#howto-use-java-6

When I downgrade the Jackson dependency to 2.6.x i got a maven build exception because the jackson-bom-2.6.x is missing in maven central. The bom is missing because it does't exist! the first available jackson-bom starts from version 2.7.8 as shown here: https://github.com/FasterXML/jackson-bom/releases 

The issue was introduced by this pull request: https://github.com/spring-projects/spring-boot/pull/7436

To reproduce the issue do:

1. download the spring boot sample app from here: https://github.com/spring-guides/gs-serving-web-content;
2. edit the **complete/pom.xml** changing the properties with the following:  
```
<properties>
    <java.version>1.6</java.version>
    <tomcat.version>7.0.59</tomcat.version>
    <jackson.version>2.6.7</jackson.version>
</properties>
```
3. go under the **complete/** directory and launch a maven build to get the error:

```
[INFO] Scanning for projects...
Downloading: http://devbe03:8081/repository/maven-public/com/fasterxml/jackson/jackson-bom/2.6.7/jackson-bom-2.6.7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.fasterxml.jackson:jackson-bom:pom:2.6.7 in Nexus (http://devbe03:8081/repository/maven-public/) @ org.springframework.boot:spring-boot-dependencies:1.5.1.RELEASE, /home/luca/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.1.RELEASE/spring-boot-dependencies-1.5.1.RELEASE.pom, line 621, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.springframework:gs-serving-web-content:0.1.0 (/home/luca/projects/gs-serving-web-content/complete/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact com.fasterxml.jackson:jackson-bom:pom:2.6.7 in Nexus (http://devbe03:8081/repository/maven-public/) @ org.springframework.boot:spring-boot-dependencies:1.5.1.RELEASE, /home/luca/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.1.RELEASE/spring-boot-dependencies-1.5.1.RELEASE.pom, line 621, column 16 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by philwebb** [comment]
Unfortunately the only way to deal with this is to directly declare the Jackson modules that you want in your `<dependencyManagement>` section. We should update the documentation to make the clear.
