### ISSUE TITLE
Spring Security and OAuth2

### ISSUE THREAD

**Issue by raxim1** [spring-projects/spring-boot#8193]
Question

Spring Boot 1.4.3

What was the purpose of the spring coders of the OAuth2 authentication? How my solution should have been done in the coders "intended" way. I'm writing it down as it's a very repetitive task, what i have done. A sample application might have been created on it.

Bug report

1, Everybody is expecting that the ResourceServerConfigurer does not override the WebSecurityConfigurerAdapter, and it sucks.
One forum did mention that if we add @Order(1) to ResourceServerConfigurer and  @Order(2) to WebSecurityConfigurerAdapter solves some problem, but that forum overlooked the problem, as the last one override the previous one. From WebSecurityConfigurerAdapter i have filtered out the "/oauth/**" targets, and from the ResourceServerConfigurer i have filtered out the "basic login path" with permitAll()
I think that was a sensible way, i have seen loads of non-working example for it on hundreds of forums.
2, My solution was to change the WebSecurityConfigurerAdapter and add two filters in it at the end.
(a) http.addFilterAt(new BasicAuthenticationFilter(clientDetailsAuthenticationManager),BasicAuthenticationFilter.class);
(b) http.addFilterAfter(oAuth2AuthenticationProcessingFilter, UsernamePasswordAuthenticationFilter.class);
3, Setting prefix was not working:
public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
endpoints.prefix("oper");
}
//my expectation was that i can authorize under /oper/oauth/authorize, but it remained /oauth/authorize
3, My junit test is very proper using csrf and session cookies. (I have a jpa based repository for that)
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = AppConfig.class)
@WebMvcTest(OAuth2ControllerTest.class)
@Transactional
@Rollback(true)

I have saved a clientDetails to a table before the test.
(grantTypes = "refresh_token", "authorization_code")
I have logged in with my user, i have called /oauth/authorize after that /oauth/token with "code".
I have not allowed any "password" mechanism, as it's not standard in webbrowser.

Concerns:
(a) When i called the /oauth/token url with the two (grantTypes = "refresh_token", "authorization_code") at first, it threw me an "invalid refresh_token". I think it should have been more error_prune on that, as you can pass a list of grant_types.
(b) I had to override the BasicAuthenticationFilter, as it used an AuthenticationManager which tends to login "username/password" and not "client_id/client_secret". Following the tutorial mentioned below, i have no idea where is the functionality where you can get the "access_token" with "code" calling the "/oauth/token" not with "token". You need to authenticate with basic auth somehow using "client_id/client_secret".
(c) Overriding the BasicAuthenticationFilter was not that simple, as i had to use a mysterious @Order(-2) at the beginning of the WebSecurityConfigurerAdapter. Defining @Order(SecurityProperties.BASIC_AUTH_ORDER) does not do anything, at least nothing reasonable.
(d) MockMvc does not store cookies and attributes to pass forward into the chains of call, i had to do it myself.

4, Using @EnableOAuth2Sso
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoRestTemplateFactory' available

5, To use @EnableWebSecurity, i had to create the following class. (which is a nightmare to do, as it's empty, should have been automatically defined)
public class SecurityWebAppInitializer extends AbstractSecurityWebApplicationInitializer {
}

6, To configure Tymeleaf in the junit test is a nightmare
Not using the WEB-INF folder (I had to copy under src/main/resources folder). At the top of that i have added some extra
@Bean
    public LiteDeviceDelegatingViewResolver liteDeviceAwareViewResolver() {
to differentiate between tablet/mobile and notebook.

7, Spring authoconfigure would be usefull, but very slow. Even if it's not set, i have expected that the application.properties will be used, but it's ignored as a whole. (so even for a database configuration i need manual work, with some property loader, which was not straightforward)

8, I would have liked to see some enums for constants used as parameters, at least to get to know which parameters i can send. (GrantType, OAuth2Utils etc)

9, If i'm getting response back in json, why i cannot send the parameters in json?

10, If there is some exception in the backend, It's very hard to figure out what was the reason by MockMvc, you can check the status, but most of the time no error message or exception is populated.

I had to intensively debug the spring source code to achieve my goals. The most time-consuming task in my development process to fine tune the spring. It's a useful tool, but the configuration should have been straight forward. All the 10 section contains something which can be improved, as i think everyone are facing with the same.

Enhancement

My aim was very standard, and looked at each of forums i haven't got real answers. I would have liked to create a proper OAuth2 provider, which is included in a server where normal spring login also accepted,
and create junit test for the whole? I have read through all the documents and forums and tutorials about 2 days. (more than 12 hours a day), and i haven't got answers, neither on stackoverflow, nor on any other forums. I have followed the https://spring.io/blog/2015/02/03/sso-with-oauth2-angular-js-and-spring-security-part-v tutorial also. I have debugged the spring source code itself to figure out things, but it was very confusing after a decade ex-tense java experience also, i thought it's a mess, and when i'm just thinking to configure anything in spring, i just don't dare to do it.

**Comment by wilkinsona** [comment]
You have described things as a nightmare twice and said that you think the code's a mess. That's entirely subjective and not at all constructive. We're more than happy to accept constructive criticism and improve things where we can but raising an issue like this isn't the way to do it.

Where I can identify some problems that you're having, very few appear to be related to Spring Boot itself, and most seem to come from a misunderstanding of how various components work. May I suggest reading the Spring Security documentation, particularly the [documentation on how ordering affects `WebSecurityConfigurerAdapter` beans](http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#multiple-httpsecurity), and the [documentation for Spring Security OAuth](https://projects.spring.io/spring-security-oauth/docs/oauth2.html) which also links to several sample applications.

**Comment by raxim1** [comment]
Sorry for the bad comments, as i have read various recources and it was a
very accurate feedback also, and it was a very-very constructive critics.
I have read the Spring Security OAuth documentation, what you have attached
partially.

The main problem, what i see is that the configuration is too complex, and
you can misconfigure easily,
and many of the feature hasn't really simplified to use in a junit test.
(There are several section in the content)

You have closed my issue, but most of them would be a very good
improvement, as everybody are facing with the same problems, and everybody
are asking the same questions.
I have read hundreds of forums, and that was my feeling.

I have seen not-up-to-date spring boot tutorial also, and it was the first
result from Google search.

Issues:
1, The  documentation on how ordering affects WebSecurityConfigurerAdapter
 beans
<http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#multiple-httpsecurity>
i
have verified that it's somehow working combined
with ResourceServerConfigurer, what i would like to use in some cases, and
what a forum suggested. The filters list does not have the
OAuth2AuthenticationProcessingFilter.
2, I definitely cannot Override the BasicAuthFilter without using
@Order(-2), have you any idea on that? httpBasic() at the end can cause
this problem, if it's missed out?
3, Prefix not working also while configuring OAuth2.

Thanks for your reply on the above 3 issues.

I cannot spend a month on this repetitive configuration, and i think nobody
can. Maybe i don't understand some sort of things, but we can admit, that
it's very-very difficult, and the chance to misconfigure something is very
high?
