### ISSUE TITLE
update spring-boot-starter-velocity version

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#8207]
Spring boot is now 1.5.1 version, but I can't find spring-boot-starter-velocity 1.5.1 version.

**Comment by snicoll** [comment]
Velocity support was deprecated in 1.4, we've removed it in 1.5 [see the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#deprecations-from-spring-boot-14)

**Comment by softliumin** [comment]
Why?

**Comment by bclozel** [comment]
Support has been removed from Spring Framework.

**Comment by bclozel** [comment]
@liyazhou You'll find more info on that in [SPR-13795](https://jira.spring.io/browse/SPR-13795).
Note that we support Thymeleaf, which ships its own Spring support.
