### ISSUE TITLE
DefaultTokenServices - OAuth2 - issue - enhancement

### ISSUE THREAD

**Issue by raxim1** [spring-projects/spring-boot#8209]
Question

I think i have found a bug, when i have created my own TokenService.

Bug report

Regarding to DefaultTokenServices i have cloned it, and changed the following lines.

around line 136:
Original version:

Authentication user = new PreAuthenticatedAuthenticationToken(authentication.getUserAuthentication(), "", authentication.getAuthorities());
            user = authenticationManager.authenticate(user);
            Object details = authentication.getDetails();
            authentication = new OAuth2Authentication(authentication.getOAuth2Request(), user);
            authentication.setDetails(details);

The main problem was that the authentication.getUserAuthentication() was already a PreAuthenticatedAuthenticationToken, so it wrapped up an existing one.

I have passed some specific "details" also, which should have been taken care of on "login", but the PreAuthenticatedAuthenticationToken has ignored it completely, as you can see from the original code.

Specific details was not an ip address, it was something else. The same user can have multiple profiles in my system, and can switch between them.

Enhancement

My enhancement is:

around line 136:
        if (this.authenticationManager != null && !authentication.isClientOnly()) {
            // The client has already been authenticated, but the user authentication might be old now, so give it a
            // chance to re-authenticate.
            Authentication userAuthentication = authenticationManager.authenticate(authentication.getUserAuthentication());
            authentication = new OAuth2Authentication(authentication.getOAuth2Request(), userAuthentication);
            authentication.setDetails(authentication.getDetails());
        }

**Comment by wilkinsona** [comment]
`DefaultTokenServices` is not part of Spring Boot. It's part of [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth). Unfortunately GitHub doesn't suppprt moving issues. If you'd like to pursue this please open a new issue against the correct project.

**Comment by raxim1** [comment]
I have done it https://github.com/spring-projects/spring-security-oauth/issues/972

Why i'm putting this comment here, because the google is heavily indexing this page, so anybody else can read it. When you are googling for "spring issue" - this github page is the first one in the list.
