### ISSUE TITLE
Unable to disable security using application.properties in 1.5.1

### ISSUE THREAD

**Issue by mrin9** [spring-projects/spring-boot#8210]
**Spring Security with SpringBoot.**

I use to enable/disable security using the `security.ignored=/**` configuration in application.properties file. It works in SpringBoot 1.4.3  but isnt working after I upgrade to 1.5.1

If I rollback to 1.4.3 it starts working again, so i am guessing my code has nothing to do with it.

**Comment by snicoll** [comment]
@mrin9 please read the release notes for 1.5, [and this section in particular](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#actuator-security)

**Comment by mrin9** [comment]
Thanks for pointing out the release notes, I did tried with setting `management.security.enabled` to `false` but nothing changed. I am still not able to disable the security using the application.properties

the release notes talks the changes to the security of management endpoints not the application end point.

below is sample of my application.properties file 
```
server.contextPath=/
server.port=9119

#Temporary disable security to enable it remove this
security.ignored=/**
management.security.enabled=false
security.basic.enabled=false
```

**Comment by snicoll** [comment]
@mrin9 please share a sample that reproduces the problem and we'll reopen this issue for investigation.

**Comment by mrin9** [comment]
@snicoll here you go [Spring Security Sample](https://github.com/mrin9/SpringBoot_Sample)

There is nothing special in the app. Just added spring security SpringBoot 1.5.1 app
now if you try to visit `localhost:8080/secure` you get a HTTP error code `403-Forbidden`

checkout my `config/application.properties` file where I added possible params to disable security

**Comment by snicoll** [comment]
I am not sure I understand why that kicks-in if you have your own security config but it does so with 1.4 and I can see that.

See #7106

@mbhave do you have an idea? If you look at that sample, careful as the config is in an unusual locartion (`config`  at the root).

Also `SpringBootWebSecurityConfiguration` has a static `getIgnored` method that is no longer used. Seems fishy. Thanks!

**Comment by snicoll** [comment]
Duplicates #6137 - You are relying on a wrong behaviour of the actuator. If I remove the actuator in your sample with 1.4 it exhibits the same behaviour as with 1.5. 

If you configure the security yourself, you can't expect Spring Boot to still apply that part of the configuration. This was an issue in 1.4 that we fixed in 1.5

**Comment by mrin9** [comment]
@snicoll ok so the use case I am after is, where we have a SpringBoot boot app. The app sometimes run outside a organization firewall where we want all the security applied. The same app runs also inside the firewall where we dont want to apply any security. Some of the Test environment and Demo environment also needs to drop the security.
So is my understanding correct that it is not possible without changing the code and just by using `application.properties` anymore ?

isnt that a common use case ? or do you have any other way of achieving the same without recompiling it for various environments ?

**Comment by mbhave** [comment]
@mrin9 If your application has custom security configuration, Spring boot will back off and not apply it's configuration. If what you're trying to achieve, is different configurations in different environments, you can use profiles. For example, you can add your `WebSecurityConfigurerAdapter` only if a certain profile is active and enable that profile on environments that you want the application to be secure.

**Comment by akrevenya** [comment]
@mbhave What would be the viable option to fix this regression if application endpoints require security but actuator endpoints does not? I have put some sample app [here](https://github.com/akrevenya/springboot-issue-8210) that demonstrates the issue I just mentioned. Am I missing something that can be done without deliberately changing actuator mappings in web security configuration to permitAll? Any thoughts? Thank you.

**Comment by akrevenya** [comment]
Looks like #8646 answers my question.
