### ISSUE TITLE
The spring boot aop default configuration have a problem

### ISSUE THREAD

**Issue by lijunyong** [spring-projects/spring-boot#8211]
I don't set spring.aop.proxy-target-class=true,when use default configuration,the AopAutoConfiguration$CglibAutoProxyConfiguration.class ConditionalOnProperty is true,return false then continue process,but the AopAutoConfiguration$JdkDynamicAutoProxyConfiguration conditional is false

the spring boot version is 1.3.2.release

![image](https://cloud.githubusercontent.com/assets/14291793/22677861/08de24ca-ed31-11e6-83c2-d367b8e67666.png)

![image](https://cloud.githubusercontent.com/assets/14291793/22677873/12873c8c-ed31-11e6-89eb-1645f3997fe8.png)

```
@Configuration
@ConditionalOnClass({ EnableAspectJAutoProxy.class, Aspect.class, Advice.class })
@ConditionalOnProperty(prefix = "spring.aop", name = "auto", havingValue = "true", matchIfMissing = true)
public class AopAutoConfiguration {

	@Configuration
	@EnableAspectJAutoProxy(proxyTargetClass = false)
	@ConditionalOnProperty(prefix = "spring.aop", name = "proxy-target-class", havingValue = "false", matchIfMissing = true)
	public static class JdkDynamicAutoProxyConfiguration {
	}

	@Configuration
	@EnableAspectJAutoProxy(proxyTargetClass = true)
	@ConditionalOnProperty(prefix = "spring.aop", name = "proxy-target-class", havingValue = "true", matchIfMissing = false)
	public static class CglibAutoProxyConfiguration {
	}

}
```  
```
ConfigurationClassParser.processConfigurationClass
if (this.conditionEvaluator.shouldSkip(configClass.getMetadata(), ConfigurationPhase.PARSE_CONFIGURATION)) {
			return;
		}
```

**Comment by snicoll** [comment]
Sorry, I am not following, rather than describing what you think is a problem, could you please describe what you're trying to achieve?
