### ISSUE TITLE
Document how to use Mockito 2 with Spring Boot 1.5

### ISSUE THREAD

**Issue by edysli** [spring-projects/spring-boot#8217]
@snicoll wrote in #7770
> this issue is closed. Mockito 2 support (with an override) will be available in 1.5 and we'll switch the default as of 2.0 (as the milestone states)

Now that Spring Boot 1.5.1 is released, is this "override" already documented somewhere? I couldn't find any mention of Mockito 2 in the [reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/). Please document it or direct people at the right place.

**Comment by snicoll** [comment]
There's nothing to document about the override. You can [override the version like you can do for any other dependency](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions). Boot will detect the version in the classpath and adapt accordingly (there's nothing to do on your end).

What am I missing?

**Comment by edysli** [comment]
It would be nice to know we can safely override Mockito v1 with v2. I just spotted a mention of Mockito 2 in your [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes), though it isn't really obvious.

**Comment by snicoll** [comment]
Fair enough. I can see we do that for Hibernate so we could have the same kind of tip for Mockito.

**Comment by edysli** [comment]
Thanks! :smile:
