### ISSUE TITLE
TestRestTemplate could issue a warning if a transaction is running on executions

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#8233]
When users run real integration tests using the port-based webEnvironment modes in `@SpringBootTest` the test context framework's default transaction behavior doesn't apply as the server is actually a separate process. Users unaware of that might still accidentally try to use `@Transactional` on tests and not realize the transactions are not rolled back properly.

As the interaction with the servers run that way is usually driven by `TestRestTemplate`, the template could issue a warning about a running transaction as that indicates the test running with transactions that are not working as expected.

Related to #8232.

**Comment by wilkinsona** [comment]
> the test context framework's default transaction behavior doesn't apply as the server is actually a separate process

The server isn't a separate process; it's running in the same process as the test. The crucial difference is that if you're using `TestRestTemplate` then you're making HTTP requests to the server. This means that two threads are involved: one for the client that's sending the request and one for the server that's processing the request. The test framework is only managing a transaction on the client thread.

**Comment by philwebb** [comment]
I wonder if there's any way to make the experience consistent. Somehow propagate the test `@Transaction` logic to the server.

**Comment by snicoll** [comment]
Yikes. Why would you ever want to do that?

**Comment by snicoll** [comment]
We've discussed this on the call and I am not keen to add a warning for the simple reason that the chance of a false positive is too high. There are also a ton of other ways to misuse transactions and we don't generate a warning for those either. We've updated the documentation and I am happy to fine tune it or make it more visible if necessary.
