### ISSUE TITLE
Placeholders in values of spring.profiles.active/include properties are no longer resolved using the Environment in Spring Boot 1.5

### ISSUE THREAD

**Issue by GreyTeardrop** [spring-projects/spring-boot#8234]
Hi!

We're using Spring profiles to configure environment-specific properties for our Spring Boot-based application. To decouple application CLI from Spring a little bit we've used to configure `spring.profiles.active` based on property named `env`, e.g., we have line below in `application.properties`
```application.properties
spring.profiles.active=${env:default}
```
and populate `env` either via command line or via system environment variable.

That used to work in Spring Boot prior to 1.5 as placeholders in `spring.profile.*` properties were resolved against existing `Environment`, but doesn't seem to work after [change to spring.profiles properties logic](https://github.com/spring-projects/spring-boot/commit/919d0c617227bff1bfd58ed57d9d5080c82f6ac1) as placeholders are now resolved only against `PropertySources` that just holds a single properties/YAML file.

Is it possible to change that and use `PropertySources` from `Environment` for placeholders in `spring.profiles.active`/`spring.profiles.include`?

**Comment by wilkinsona** [comment]
@GreyTeardrop Thanks for the analysis. It made tracking down the cause of the problem much quicker.

**Comment by avarabyeu** [comment]
@wilkinsona In 1.5.2 profiles became active, but additional configuration sources (like application-{profile_name}.yaml) are still not resolved.

**Comment by wilkinsona** [comment]
@avarabyeu This issue is closed and what you have described works for me with 1.5.2.RELEASE. If you'd like us to investigate please open a new issue with a small sample that reproduces the problem.

**Comment by zhaitao** [comment]
We just found this issue too and resolved by upgrading to 1.5.2.RELEASE. Thanks.
