### ISSUE TITLE
Auto-generate the "Common application properties" appendix

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#8237]
Given the size of the properties appendix, consider adding anchors between property sets, to make it easier to navigate to technology-based properties... 

- from the ToC
- as a hyperlink when answering StackOverflow questions etc

Something like...

```
--- a/spring-boot-docs/src/main/asciidoc/appendix-application-properties.adoc
+++ b/spring-boot-docs/src/main/asciidoc/appendix-application-properties.adoc
@@ -13,7 +13,10 @@ your own properties.
 WARNING: This sample file is meant as a guide only. Do **not** copy/paste the entire
 content into your application; rather pick only the properties that you need.
 
+=== Properties
 
+[[appendix-props-core]]
+==== Core Properties
 [source,properties,indent=0,subs="verbatim,attributes,macros"]
 ----
        # ===================================================================

... 

@@ -923,7 +926,12 @@ content into your application; rather pick only the properties that you need.
        spring.kafka.ssl.truststore-location= # Location of the trust store file.
        spring.kafka.ssl.truststore-password= # Store password for the trust store file.
        spring.kafka.template.default-topic= # Default topic to which messages will be sent.
+----
 
+[[appendix-props-rabbit]]
+==== RabbitMQ Properties
+[source,properties,indent=0,subs="verbatim,attributes,macros"]
+----
        # RABBIT ({sc-spring-boot-autoconfigure}/amqp/RabbitProperties.{sc-ext}[RabbitProperties])
        spring.rabbitmq.addresses= # Comma-separated list of addresses to which the client should connect.
        spring.rabbitmq.cache.channel.checkout-timeout= # Number of milliseconds to wait to obtain a channel if the cache size has

...
```

We then get a ToC entry, as well as an anchor which can be copied to the clipboard.

<img width="332" alt="screen shot 2017-02-08 at 12 28 24 pm" src="https://cloud.githubusercontent.com/assets/483832/22749251/a1b04632-edfa-11e6-8904-4a4985816c65.png">

**Comment by garyrussell** [comment]
I am willing to submit a PR if this passes triage.

http://stackoverflow.com/questions/42118570/set-heartbeat-property-on-rabbitmq-autoconfig-connectionfactory-bean/42118917#42118917

**Comment by wilkinsona** [comment]
Thanks for the offer of a PR, @garyrussell. I am firmly in favour of doing this, but I think we should do it as part of automating the generation of the appendix. I believe @snicoll already has quite a bit of code that we could use to do that.

**Comment by snicoll** [comment]
I do. I think what is blocking me to move forward is the style that we want for the generated format. If we want to keep the raw properties list, I can make that happen.

**Comment by wilkinsona** [comment]
I like the format that @garyrussell seems to be proposing. Auto-generating the name for each section may be a little tricky.

**Comment by garyrussell** [comment]
Ping - this is way past its first birthday - it's really a pain having one monolithic appendix for all these properties.

I can't count the number of times I have had to answer an SO question with a link to the appendix and having to say "scroll down to X".

>Auto-generating the name for each section may be a little tricky.

A name is not really necessary; just an anchor between each set of properties.

It might also be nice to have a link to the appropriate section from the corresponding main section, but simply adding the anchors would be a huge step forwards.

Thanks.

**Comment by wilkinsona** [comment]
> A name is not really necessary; just an anchor between each set of properties.

I'm not sure if it's possible to get Asciidoctor to add anchors to HTML output when there's nothing in the source to hang them off. We normally get the anchors as a side-effect of having a new section. If we have new sections, then they'll need to be named. Anyway, that'll only be a little tricky. I certainly don't think it's insurmountable.

I'm going to put this one on the backlog so it's considered for 2.1. I'll see if I can convince Stéphane when he returns from his time off.

**Comment by snicoll** [comment]
Apache Camel has done something similar, there is some context [in this comment](https://issues.apache.org/jira/browse/CAMEL-12756?focusedCommentId=16596653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16596653)
