### ISSUE TITLE
spring boot - tomcat - glassfish deployment

### ISSUE THREAD

**Issue by raxim1** [spring-projects/spring-boot#8241]
Question

I have seen it already soled on some forum, but the latest spring-boot (1.4.3.RELEASE) hasn't got it.

Bug report

1, spring boot deployment is failing on tomcat 7 because of the
<groupId>org.apache.tomcat.embed</groupId>
 <artifactId>tomcat-embed-websocket</artifactId>
 dependency should be provided.
2, On Glassfish 4.1.1 (the latest one) server spring boot has got a problem with jboss logging.
I had to replace Glassfish library with a new jboss-logging.jar - 3.3.0 Final

Enhancement

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.tomcat.embed</groupId>
                    <artifactId>tomcat-embed-websocket</artifactId>
                </exclusion>
            </exclusions>
</dependency>
<dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
            <scope>provided</scope>
</dependency>

Please change the spring-boot-starter-web to make the dependency provided, as it causes deployment problem on both server.

**Comment by wilkinsona** [comment]
@raxim1 Please read the documentation before opening issues: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file

**Comment by raxim1** [comment]
I have used the following:
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.tomcat.embed</groupId>
                    <artifactId>tomcat-embed-websocket</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>

Is the link viable? I have used  <artifactId>spring-boot-starter-web</artifactId>,
maybe it's maven basic, but does it override the inherited spring-boot-starter-tomcat, if i'm following the document, and using my
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
also. Or this one should be provided? Can you simplify it for me please, as it's quite confusing.

As many document mentioned in an exclusion way to be able to use embedded jetty.

            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.4.0.v20161208</version>
            </plugin>

**Comment by raxim1** [comment]
I have used 

<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>

through

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
</dependency>

One of your document which is explaining the exclusion of spring-boot-starter-tomcat
to replace with  spring-boot-starter-jetty is wrong.

I have tested that to make the  spring-boot-starter-web provided is enough, with the 
spring-boot-starter-tomcat exclusion.

Your document example shows:

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <scope>provided</scope>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>

which is wrong, as it should be:

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

It took me a lot of time.

**Comment by raxim1** [comment]
[comment_spring_boot.txt](https://github.com/spring-projects/spring-boot/files/764318/comment_spring_boot.txt)

**Comment by wilkinsona** [comment]
> Sometimes is formatted, sometimes is not readable.

You need to use triple back ticks. See https://guides.github.com/features/mastering-markdown for details.

> One of your document is wrong

It isn't wrong. It's showing you how to use embedded Jetty instead of embedded Tomcat. The container dependencies only need to be marked as provided if you are building a war file that you want to deploy to a container as [described here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file).

**Comment by raxim1** [comment]
I can agree with that, but you need to accept that it's in totally different places in the document, and most of the time we are creating wars not jars, at least a comment needs to link to your solution.
