### ISSUE TITLE
Undertow embedded servlet container ignores SSL server.ssl.key-alias

### ISSUE THREAD

**Issue by spazbob** [spring-projects/spring-boot#8245]
Spring Boot 1.2.5.RELEASE built with Jdk: 1.8.0_112

When setting up Spring Boot with HTTPS and the Undertow embedded container, it seems to ignore the value specified in application.properties for `server.ssl.key-alias`. Despite the below configuration, Chrome Developer Tools reports the cert in use is one of three certs in the keystore other than localhost.

```
# Embedded container configuration
server.port = 8443
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=mypassword
server.ssl.key-alias=localhost
server.ssl.key-password=keypassword
```

The Tomcat and Jetty seem to have code to select the correct key based on alias (see the `configureSsl()` method in the below files). I couldn't from a quick look see any equivalent code in the Undertow factory. The key-alias parameter is documented in Spring Boot so I would expect it to work for all embedded containers.

[UndertowEmbeddedServletContainerFactory](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/undertow/UndertowEmbeddedServletContainerFactory.java)

[TomcatEmbeddedServletContainerFactory](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/tomcat/TomcatEmbeddedServletContainerFactory.java)

```java
	/**
	 * Configure Tomcat's {@link AbstractHttp11JsseProtocol} for SSL.
	 * @param protocol the protocol
	 * @param ssl the ssl details
	 */
	protected void configureSsl(AbstractHttp11JsseProtocol<?> protocol, Ssl ssl) {
		protocol.setSSLEnabled(true);
		protocol.setSslProtocol(ssl.getProtocol());
		configureSslClientAuth(protocol, ssl);
		protocol.setKeystorePass(ssl.getKeyStorePassword());
		protocol.setKeyPass(ssl.getKeyPassword());
		protocol.setKeyAlias(ssl.getKeyAlias());
```

[JettyEmbeddedServletContainerFactory](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/jetty/JettyEmbeddedServletContainerFactory.java)

```java
	/**
	 * Configure the SSL connection.
	 * @param factory the Jetty {@link SslContextFactory}.
	 * @param ssl the ssl details.
	 */
	protected void configureSsl(SslContextFactory factory, Ssl ssl) {
		factory.setProtocol(ssl.getProtocol());
		configureSslClientAuth(factory, ssl);
		configureSslPasswords(factory, ssl);
		factory.setCertAlias(ssl.getKeyAlias());
```

**Comment by wilkinsona** [comment]
The lack of key alias support for Undertow exists in the latest versions, but did you really mean `1.2.5.RELEASE` above? It's 18 months old now. Any change that we can make to address this will be in 1.4.x at best.

**Comment by spazbob** [comment]
Even though from what I could see in the code the same problem existed in the master branch, I did discover this issue in `1.2.5.RELEASE` so stated this in case I was missing something. I have no expectation of this being fixed in old branches.
