### ISSUE TITLE
RestTamplate improvement?

### ISSUE THREAD

**Issue by celiovasconcelos** [spring-projects/spring-boot#8246]
`RestTamplate` should throw a `HttpStatusCodeException` when the server returns `302 Found` of a `POST` method. Since POST request body does not survive redirecting.

Otherwise, the developer needs to hande both `ResponseEntity` and `Exceptions` every time.

Or something like `YouMightLostInformationException` instead of `HttpStatusCodeException`.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but `RestTemplate` is part of Spring Framework rather than Spring Boot. You may want to open a [JIRA ticket instead](https://jira.spring.io/browse/SPR).
