### ISSUE TITLE
Sliced tests doesn't reuse cached contexts when testing with Spock's spock.lang.* annotations.

### ISSUE THREAD

**Issue by erling** [spring-projects/spring-boot#8251]
Spock's `spock.lang.*` annotations to a specification makes each spec appear to be different:

```java
@spock.lang.Ignore
static class FirstSpockAnnotatedTestClass {}

@spock.lang.Stepwise
static class SecondSpockAnnotatedTestClass {}
```
Only partially solved by [issue 7524](https://github.com/spring-projects/spring-boot/issues/7524).

Added PR: https://github.com/spring-projects/spring-boot/pull/8252/files

**Comment by snicoll** [comment]
Closing in favour of PR #8252 (@erling no need for a separate issue if you intend to submit a PR right the way).
