### ISSUE TITLE
Statsd server gets no metric report when using spring boot metrics API and Dropwizard implementation

### ISSUE THREAD

**Issue by ZhuzhuDing** [spring-projects/spring-boot#8254]
I'm doing it as below: 

- Use CounterService as metrics repository api just as official reference:
```java
    @Component
    public class ComponentUseSpringBootMetrics {

	    @Autowired
	    private CounterService counterService;

	    @Scheduled(fixedRate = 5000)
	    public void increment() {
		    counterService.increment("meter.springboot.counter");
	    }
    }
```

- Import Dropwizard metrics in build.gradle

```groovy
buildscript {
	ext {
		springBootVersion = '1.5.1.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

jar {
	baseName = 'spring_boot_metrics_study'
	version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

dependencies {

	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.boot:spring-boot-starter-actuator')
	
        // remove this library then it works
	compile group: 'io.dropwizard.metrics', name: 'metrics-core', version: '3.1.2'	
	compile group: 'com.timgroup', name: 'java-statsd-client', version: '3.1.0'
	
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

- Add statsd property in application.properties
```
spring.metrics.export.statsd.host=localhost
```

The result is statsd server won't get any report when using spring boot metrics API and Dropwizard implementation.

**If I remove Dropwizard metric dependency, just use default implementation then it works.**

Do I miss anything or is it a bug?

**Comment by ZhuzhuDing** [comment]
I think the reason is that MetricsDropwizardAutoConfiguration doesn't have any Bean defined as @ExportMetricReader.  Then a default MetricReader will be initialised.

**Comment by wilkinsona** [comment]
When you add Dropwizard to the classpath, I believe the assumption is that you want metrics to be sent into Dropwizard. This is done automatically by `DropwizardMetricServices` that sends gauges and counters to a `com.codahale.metrics.MetricRegistry`.

What was your goal when you added the `io.dropwizard.metrics:metrics-core` dependency?

**Comment by ZhuzhuDing** [comment]
We want to use Spring boot API and Dropwizard metric as implementation, and report to Statsd server all by auto configuration. But it won't work.
When an extra configuration as above is added, the problem gone.

Through debug, I can see the CounterService instance is type of DropwizardMetricServices, but the exporter won't get a reader.  Thus Statsd server won't get any report.

I guess the reason is MetricsDropwizardAutoConfiguration doesn't have any Bean defined as @ExportMetricReader, but overrides the bean definition in MetricRepositoryAutoConfiguration .So no MetricReader is defined under this circumstance.

**Comment by OrangeDog** [comment]
> When you add Dropwizard to the classpath
It should be noted that it can also come from transitive dependencies (such as via `spring-boot-starter-data-cassandra`), as it's a very popular instrumentation library. It's surprising that this disables existing redis and statsd exports.

**Comment by psoares** [comment]
I tried to exclude that transitive dependency from spring-starter-data-cassandra because my project uses it. Unfortunately the build then complains about not having it. I solved the issue for now by excluding the MetricsDropwizardAutoConfiguration in application.yml, like this:

```
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.MetricsDropwizardAutoConfiguration
```

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
