### ISSUE TITLE
externalized Profile-specific properties not finding application.properties but application.yml

### ISSUE THREAD

**Issue by rubentrancoso** [spring-projects/spring-boot#8256]
Using a simple spring boot 1.5.1 stater 

add an application.properties in main/resources
and an application-dev.properties in config/ folder under the project's root path.

The Class to load the properties has just a @Configuration annotation and the fields are taken using @Value("${some.propety}") annotation.

When running the spring-boot jar with --spring.profile.active=dev  it's complaining that it cannot resolve the ${some.property} when it´s available only on the config/application-development. (as the override feature should work according to what is stated in the spring boot docs).

BUT, when I simply change the properties files to YML format it works as expected.

After struggling a bit with looks like this is a bug or an undocumented feature :) that is not clearly stated in the document.

**Comment by wilkinsona** [comment]
Your profile name (`dev`) and file name (`application-development.properties`) don't match. Is that just a typo? I suspect so as you also mention `application-dev.properties`. If it is, please provide a sample that illustrates the behaviour you have described with steps required to reproduce the problem.

**Comment by rubentrancoso** [comment]
When trying to reproduce the error in a sample project became clear that it was my mistake. Anyway, it's working as expected. Probably a typo.
