### ISSUE TITLE
When I install the spring boot gradle plugin and run the `run` or `bootRun` task, then Spring Loaded should be loaded and allow me to perform hot-reloading.

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#827]
When I start my application using gradle, and then I go make a change, I should see the change made in the output of my application automatically.

```
$ gradle run
```

or 

```
$ gradle bootRun
```

**Comment by snicoll** [comment]
I believe that Devtools in Spring Boot 1.3 is addressing this concern.
