### ISSUE TITLE
Disabling banner in application.yml cause application failed to start up

### ISSUE THREAD

**Issue by rashidi** [spring-projects/spring-boot#8270]
I applied the following configurations in application.yml:

```
spring:
  main:
    banner-mode: off
```

And found the application failed to start. Here is the [sample application](https://github.com/rashidi/boot-banner-disabled-error).

Cheers!

**Comment by wilkinsona** [comment]
As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-banner) you need to quote off to avoid YAML turning into false.
