### ISSUE TITLE
Fix documentation for spring boot sample cache

### ISSUE THREAD

**Issue by skhurana333** [spring-projects/spring-boot#8272]
The documentation at https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache , states below for each JSR implementation

Run sample cache application using Hazelcast with $mvn spring-boot:run -Pinfinispan

It has 'HazelCast' for each.

**Comment by snicoll** [comment]
Good catch, thanks!
