### ISSUE TITLE
v1.5 requires @Validated annotation on @ConfigurationProperties, which creates JDK proxy if class implements interface

### ISSUE THREAD

**Issue by mdvorak** [spring-projects/spring-boot#8277]
Since Spring Boot v1.5, configuration property beans are required to be annotated with `@Validated` in order to be validated. This works great, until the class implements an interface.

**Cause**
Beans annotated with `@Validated` are post-processed using `MethodValidationPostProcessor`, which is defined as `@ConditionalOnMissingBean` in class `ValidationAutoConfiguration`, which is automatically included with `@EnableAutoConfiguration`. 
`MethodValidationPostProcessor` is never created with `setProxyTargetClass`. Therefore, it creates JDK dynamic proxy from the instance, which in return fails dependency injection.

**Steps to reproduce**
```java
public interface MyInterface {
    String getFoo();
}

@Validated
@ConfigurationProperties
public class MyProperties implements MyInterface {
    private String foo;

    @Override
    public String getFoo() { return foo; }
    public void setFoo(String foo) { this.foo = foo; }
}

@SpringBootApplication
@EnableConfigurationProperties(MyProperties.class)
public class MyApplication {

    // This fails, since MyProperties is JDK proxy with only MyInterface implementation
    @Autowired
    private MyProperties properties;

    // ... main etc
}
```

This produces a misleading error
```
Description:
The bean 'foo.MyProperties' could not be injected as a 'foo.MyProperties'
because it is a JDK dynamic proxy that implements:
	foo.MyInterface

Action:
Consider injecting the bean as one of its interfaces or forcing
the use of CGLib-based proxies by setting proxyTargetClass=true
on @EnableAsync and/or @EnableCaching.
```

**Solution**
This behaves exactly as it is supposed to. Its side-effect of adding `@Validated` to property class. The problem lies in Spring Boot autoconfig, where is no nice way of telling Spring to set `MethodValidationPostProcessor.proxyTargetClass=true`.

Some possible solutions:
1. Make `MethodValidationPostProcessor.proxyTargetClass=true` by default, if possible.
2. Add configurable property like `spring.validation.proxy-target-class`
3. Read existing `spring.aop.proxy-target-class` value. I'm not sure what consequences this might have.

And last but not least, it should be documented, both in docs and in error message. Took me while of debugging to find what processor causes this behavior (and I know my way around Spring).

**Workaround**
Use that `@ConditionalOnMissingBean`, and declare your own `MethodValidationPostProcessor` bean:
```java
@Bean
public MethodValidationPostProcessor methodValidationPostProcessor(Validator validator) {
    MethodValidationPostProcessor processor = new MethodValidationPostProcessor();
    processor.setValidator(validator);
    processor.setProxyTargetClass(true);
    return processor;
}
```
It's however bit ugly, and feels like replacing inner workings of Spring Boot, which might easily break in future versions.

**Comment by mdvorak** [comment]
The issue is also documented here https://jira.spring.io/browse/SPR-12827, it is however different use-case.

**Comment by wilkinsona** [comment]
See also #8173. I wonder if implementing an interface on the `@ConfigurationProperties` class was the missing piece in recreating it.

**Comment by snicoll** [comment]
@wilkinsona I don't see the link between the two since that one was introduced in 1.5 only. @mdvorak thanks for reporting it, that one was pretty nasty!

**Comment by derTobsch** [comment]
It feels familiar, cause I extend extend from `EurekaInstanceConfigBean`, which implements `CloudEurekaInstanceConfig` and `EnvironmentAware`, and override some Methods in our @ConfigurationProperties. Maybe that could be something? I also extend `ResourceServerProperties` and `AuthorizationCodeResourceDetails`.

Again I tried to reproduce it in a sample project but know I only get the bug of this issue.

**Comment by snicoll** [comment]
@derTobsch this issue is fixed. Try `1.5.2.BUILD-SNAPSHOT`

**Comment by mdvorak** [comment]
That was quick, thanks a lot!
I've tested latest snapshot on my project and it works.

**Comment by derTobsch** [comment]
@snicoll I am on it, but the build, even locally, seems to take some time. :-) I will write my respond in #8173
