### ISSUE TITLE
Create Actuator Endpoint To Manage Active Spring-Sessions

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-boot#8278]
Hello,

I'd like to see all the users that are currently using my website (i.e. all the active sessions) and I think it would be very useful if there was an actuator endpoint to do that (like `/management/session`). A `GET` request (like `/management/session`) would list the sessions or a single session (`/management/session/123424345387201few23123`), and a `DELETE` request will kill the session with the given id (`/management/session/123424345387201few23123`). The information can be easily retrieved from the spring-session repository abstraction.

**Comment by wilkinsona** [comment]
Looks like a duplicate of #5730 to me

**Comment by ptahchiev** [comment]
It is .. I looked a lot and couldn't find it - thanks @wilkinsona
