### ISSUE TITLE
@Validated annotation doesn't work with @NotNull annotated properties loaded via spring cloud config

### ISSUE THREAD

**Issue by explorer566** [spring-projects/spring-boot#8279]
I wrote a little application in order to make my first experience with spring cloud config.

I have a simple property class:

```java
@Component
@Validated
@ConfigurationProperties(prefix = "app")
public class ApplicationProperties {

    @NotNull
    private String message = "Hello world";
    
    public String getMessage() {
        return message;
    }
    
     public void setMessage(String message) {
        this.message = message;
    }
}
```

If the application reads the "message" property from a cloud config server where it is defined in a property file I get a validation exception saying that the "message" property should not be null.
If I omit the @Validated annotation everything works fine.

**Comment by explorer566** [comment]
I used Spring-Boot 1.5.1.RELEASE and Spring Cloud Config 1.2.2.RELEASE

**Comment by snicoll** [comment]
Can you please attach the full stacktrace?

**Comment by explorer566** [comment]
Done.
[Stacktrace.txt](https://github.com/spring-projects/spring-boot/files/771366/Stacktrace.txt)

**Comment by snicoll** [comment]
There is no stacktrace there/ You can run the app in debug mode (`--debug`) and you should get the stacktrace of the validation that led to the "application failed to start" thing.

**Comment by explorer566** [comment]
Here you are.

[Stacktrace.txt](https://github.com/spring-projects/spring-boot/files/771392/Stacktrace.txt)

**Comment by explorer566** [comment]
Without the @Validated annotation the log looks as follows.

[Log_without_Validated.txt](https://github.com/spring-projects/spring-boot/files/771405/Log_without_Validated.txt)

**Comment by snicoll** [comment]
ping @dsyer @spencergibb - Either we broke the `rebinder` thing in Spring Cloud or that code wasn't prepared for the `@Validated` change we've introduced.

**Comment by snicoll** [comment]
duplicates #8173

**Comment by wdyun** [comment]
@Validated in controller and must important inject bean
 @Bean
    MethodValidationPostProcessor methodValidationPostProcessor() {
        return new MethodValidationPostProcessor();
    }
