### ISSUE TITLE
Allow for @Table annotations to use configuration parameters

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#829]
For example:

@Table(schema="${myApp.schemaName}")
 
We have multiple applications which use the same database schema in production, but need to use different schemas in development. The @Table annotation provided by hibernate-jpa accepts a schema, or can use a default schema from application.properties, but there isn't an easy way to configure these schemas dynamically. Schemas are fixed at compile time.

**Comment by lacivert** [comment]
@berlin-ab This may be some old issue and may not be suitable for you but have you tried AbstractRoutingDataSource ? I had a similar problem; many schemas with same tables. So I needed this kind of solution and I see that it works. Check it if you still need it

**Comment by trisberg** [comment]
@dsyer AFAIK as long as the schemas are within the same Oracle database they should all be part of the same local transaction. It gets tricky if you access data located in different databases. Then you would need a database link to connect the two databases and Oracle would create a distributed transaction behind the scenes.

**Comment by philwebb** [comment]
This issue is quite old now, so I'm guessing some kind of solution was found. I don't think we want to add changes to Hibernates annotation processing directly in Boot, it seems like quite an edge case and it's likely to cause maintenance headaches.

**Comment by madorb** [comment]
Just FYI, i'm still looking to find some solution for this. Oracle really makes this unnecessarily difficult. 

In say, mysql i can specify the database i want to connect to in the jdbc url. In oracle the equivalent to that database is a schema, which i cannot define in the connection url. My applicaiton needs to connect to two logical databases app1, app2. I'm not doing any joinging or anything between them, just two different sources of data. 

Since the schemas are different per environment e.g. schemaADev, schemaATest, schemaBDev, schemaBTest... that leaves me with no clear option to enable the functionality i need.

**Comment by mknutty** [comment]
Here is a real world usecase.
I am running into this issue. My customer has a single database install, with multiple databases for all environments in the same database. I think it is a licensing issue. Why not MySQL or Postgres? .NET. 

So, i have 4 datasources per enviroment. With Hikaricp that is 40 connections per enviroment (aka accept/prod). They freaked out.  SQL server allows you do connect to one database but refer to another by fully qualified names - [dbname].['user'].[table].   

Anyway, my solution is to reduce number of connections by setting the max to a low number :(  I am going to try to get them to set up another server and seperate prod from accept.

**Comment by madorb** [comment]
@wilkinsona This was closed due to age, but IMO there is still no simple solution for it (presently, i have to create two separate datasources and set the default schema property for each when building the LocalContainerEntitymanagerFactoryBean). 

As it's closed but only referend as due to age... is it reasonable for me to open a new ticket for this issue? I don't want to waste the team's time if it's actually a  "Won't Fix".

Thanks!

**Comment by madorb** [comment]
Oops meant @philwebb as he is the one who closed it.

**Comment by snicoll** [comment]
@madorb the actual reason for closing it is 
> I don't think we want to add changes to Hibernates annotation processing directly in Boot

That reason hasn't changed.

**Comment by mknutty** [comment]
yeah, i know it was closed and the reasoning for not doing it in boot and i
agree.  But, I was just googling for a solution, came across this and
figured i would provide a real world reason just in case it was ever
revisited.

**Comment by SyedHamzah** [comment]
Not sure if i am too late to this discussion. But did anybody find a solution?
My scenario is a multi tenant system where user/tenant data has to be kept in one base schema, therefore i need to configure these two tables with base schema only. Unfortunately i cannot keep base schema name harcoded, but rather fetch from application properties.

**Comment by penrique** [comment]
No solution for this?

**Comment by PhanNN** [comment]
https://dzone.com/articles/hibernate-dynamic-table-routin

It might helps?

**Comment by rajlokeshkumar** [comment]
has any one got any solution on this ,I am looking solution for this badly ,can any one let me know how you handled the scenario.
I have single database connection
I have tables from multiple schema's 
Schema names are different for different environment 
When the environment is changed i do not want to go and touch java code.

Any way of achieving it

**Comment by isneezy** [comment]
@rajlokeshkumar i dont know if this solves you problem but I've solved this problem by using hibernate interceptor.
```java
public class PrimaveraSchemaInterceptor extends EmptyInterceptor {

    public static String PRIMARY_DB;
    public static String SECONDARY_DB;

    @Override
    public String onPrepareStatement(String sql) {
        sql = sql.replace("PRIMARY_DB", PRIMARY_DB)
                .replace("SECONDARY_DB", SECONDARY_DB);
        return sql;
    }
}
```
https://stackoverflow.com/a/25293683/4815174

**Comment by dhananjaybakore** [comment]
This should work, while creating an entity manager for your custom data source , set the hibernate properties:
``` java 
  @Value("{$youSchema}")
   private String schema;  
    
   @Bean
    public LocalContainerEntityManagerFactoryBean coreEntityManagerFactory( DataSource coreDataSource){
        LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
        factory.setPackagesToScan("you.dao.package");
        factory.setDataSource(coreDataSource);
        Properties hibernateProperties = new Properties();
        hibernateProperties.put("hibernate.default_schema", schema);
        factory.setJpaProperties(hibernateProperties);
        factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
        return factory;
    }```

**Comment by zistheman12** [comment]
I found you can accomplish a dynamic schema configuration for multiple schemas by overriding the physical naming strategy.  

Let's say you have two entities like this which are configured for two different schemas -
```java
@Entity
@Table(name="TABLE1", schema="schema1")
public class FooEntity implements Serializable {
    ...
}

@Entity
@Table(name="TABLE2", schema="schema2")
public class BarEntity implements Serializable {
    ...
}
```

First create a configuration in your application.yml file:
```yml
multischema:
  config:
    schema1: FIRSTSCHEMA
    schema2: SECONDSCHEMA
```
Bind it to a ConfigurationProperties bean
```java
@Component
@ConfigurationProperties("multischema")
public class MultiSchemaConfigurationProperties {

    private Map<String,String> config;

    public void setConfig(Map<String,String> config) {
        this.config = config;
    }

    public Map<String,String> getConfig() {
        return config;
    }

}
```
Create a custom physical naming strategy which injects MultiSchemaConfigurationProperties and extends the Spring Boot default for your version.  In this case I'm using Spring Boot 2.6.4 which uses CamelCaseToUnderscoresNamingStrategy.
```java
@Component
public class MultiSchemaPhysicalNamingStrategy extends CamelCaseToUnderscoresNamingStrategy {

    private final MultiSchemaConfigurationProperties schemaConfiguration;

    public MultiSchemaPhysicalNamingStrategy(MultiSchemaConfigurationProperties schemaConfiguration) {
        this.schemaConfiguration = schemaConfiguration;
    }

    @Override
    public Identifier toPhysicalSchemaName(Identifier name, JdbcEnvironment jdbcEnvironment) {
        if(name != null) {
            Identifier identifier = super.getIdentifier(schemaConfiguration.getConfig()
                    .get(name.getText()), name.isQuoted(), jdbcEnvironment);
            return super.toPhysicalSchemaName(identifier, jdbcEnvironment);
        }
        return name;
    }

}
```
Override the physical naming strategy used by Spring Boot as per the documentation https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-access.configure-hibernate-naming-strategy
```yml
spring.jpa.hibernate.naming.physical-strategy=your.package.name.MultiSchemaPhysicalNamingStrategy
```
When the application starts up Hibernate will invoke the custom physical naming strategy to apply the physical naming rule for your schema using the provided configuration in application.yml.  

So "schema1" in FooEntity will be replaced by the value "FIRSTSCHEMA" and "schema2" in BarEntity will be replaced by the value "SECONDSCHEMA".
