### ISSUE TITLE
Consider adding SI-Kafka 2.1.0 to the managed dependency set of Spring Boot 1.5.x

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-boot#8290]
Currently, Spring Boot 1.5.x has introduced Spring Kafka support and it subsequently manages dependencies for Spring Kafka and the Kafka client.

However, when using Spring Boot 1.5.x with Spring Cloud Camden (and Kafka), this results in errors like https://github.com/spring-cloud/spring-cloud-release/issues/70#issuecomment-279639254 (and a few others). The reason is that the additional dependency on spring-integration-kafka is not managed by Spring Boot, and is left to the original, as set by the Spring Cloud (and subsequently Spring Cloud Stream). 

While it is possible to ensure that newer versions of Spring Cloud (i.e. Dalston) will bring in a dependency set that is consistent with Spring Boot, this change would ensure full backward compatibility with older Spring Cloud versions (i.e. Camden). I understand that Boot shouldn't manage a dependency that it doesn't use directly, but Spring Integration Kafka is a bit of an exception (as the other SI extensions that are in a similar situation - Rabbit, JMS) are already managed by Spring Boot (as being part of the SI project themselves).

**Comment by wilkinsona** [comment]
@mbogoevici Shouldn't whatever cares about the version of Spring Integration Kafka that is used be the thing that provides dependency management for it?

**Comment by mbogoevici** [comment]
@wilkinsona That's generally the case (it is a possible workaround), but this is a scenario that has arisen since the introduction of Spring Kafka in Spring 1.5. Any attempt to upgrade Spring Boot in an application that uses Spring Cloud/Spring Cloud Stream + Camden + Kafka basically needs to be followed by an upgrade of the library. Camden unfortunately predates Boot 1.5 so we can't upgrade things there. A release notes or warning should be possible, too but this would help make for a smoother transition (also it's not inconsistent with other libraries). 

Looking at it, the dependency is managed in Spring IO (so possibly the right solution would be to rely on that), but Boot and Initializr seem to be independent of it.

**Comment by wilkinsona** [comment]
Sorry, but we don't want to introduce dependency management for something that we don't depend upon and particularly not in a maintenance release. As you've noted, there is dependency management for Spring Integration Kafka in the IO Platform which is the place where we pick up the other projects that Boot doesn't depend upon. I think this'll need to be handled one way or another in Spring Cloud.
