### ISSUE TITLE
Allow Session filter's order and dispatcher types to be configured via the environment

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8301]

**Comment by wilkinsona** [comment]
Having just spent a bit of time looking at Session's reactive support, there's no equivalent of the servlet filter order and servlet filter dispatcher types there. Instead a custom `WebSessionManager` is plugged into a WebFlux `HttpHandler` and that's pretty much it. In short, the properties proposed here are Servlet-specific.

We already have similar properties for configuring the security filter:

```
security.filter-order
security.filter-dispatcher-types
```

I don't think we want to follow that precedent as it leaves the servlet specific properties as siblings of all the other properties.

I wonder if this is sufficient to distinguish the properties as Servlet-specific:

```
spring.session.filter.order
spring.session.filter.dispatcher-types
```

Or do we need to go a step further:

```
spring.session.servlet.filter-order
spring.session.servlet.dispatcher-types
```

Or even:

```
spring.session.servlet.filter.order
spring.session.servlet.filter.dispatcher-types
```

**Comment by snicoll** [comment]
Whenever I do this, I always have a look at the appendix to find a pattern.  We do have `server.servlet` so `spring.session.servlet` fits nicely. I'd be in favour of the second proposal, I am not sure the extra namespace is warranted.

**Comment by vpavic** [comment]
I'm also in favor of `spring.session.servlet`. It clearly communicates that the containing properties apply to Spring Session's Servlet API integration.

**Comment by wilkinsona** [comment]
Thanks, both. `spring.session.servlet.filter-order` and `spring.session.servlet.filter-dispatcher-types` it is then.

**Comment by zhanhb** [comment]
Maybe it's better to named as `spring.session.filter`
