### ISSUE TITLE
Remove unused method from SpringBootWebSecurityConfiguration

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#8305]
https://github.com/spring-projects/spring-boot/blob/4b9cba351b9f73de7f31fbdc5a03427c47a55528/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SpringBootWebSecurityConfiguration.java#L145-L145

**Comment by snicoll** [comment]
Good catch, @mbhave! I've noticed it as well but forgot to create the issue.
