### ISSUE TITLE
ConfigurationProperties bean generates warnings even though it is annotated properly

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#8307]
Spring Boot 1.5.1 requires that configuration properties beans be annotated with `@Validated` (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#configurationproperties-validation). 

I have a ConfigurationProperties bean that is annotated with `@Validated` yet I still get the following warning:
```
The @ConfigurationProperties bean class com.something.MyProp$$$EnhancerBySrpingCGLIB$$54ccee contains validation constraints but has not been annotated with @Validated.
```

It appears that `ConfigurationPropertiesBindingPostProcessor:420` does not see the `@Validated` annotation on my class because of the cglib proxy that Spring created around it.

**Comment by wilkinsona** [comment]
Are you using Spring Cloud?

**Comment by shollander** [comment]
Yes, I am using Spring Cloud.

**Comment by wilkinsona** [comment]
Thanks. Unfortunately, there's [a bug](https://github.com/spring-cloud/spring-cloud-commons/issues/177) in Spring Cloud which means that it's calling `ConfigurationPropertiesBindingPostProcessor` outside of the usual `BeanPostProcessor` contract. You'll need to stop using `@Validated` until the Spring Cloud issue is fixed. If you're interesting, there's some more background information in #8173.
