### ISSUE TITLE
Autoconfigure an SFL4J-Logger for injection

### ISSUE THREAD

**Issue by thogaw** [spring-projects/spring-boot#8310]
Hi,

it would be quite cool/helpful if it would be possible out of the box to inject a logger into spring-beans.

With introduction of "InjectionPoint" its not a big job....

Probably something like this:
```java
@Configuration
class Slf4JConfiguration {

	@Bean
	@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
	Logger logger(InjectionPoint injectionPoint) {
		MethodParameter param = injectionPoint.getMethodParameter();
		Field field = injectionPoint.getField();
		if(param!=null) {
			return LoggerFactory.getLogger(param.getContainingClass());
		} else if(field !=null) {
			return LoggerFactory.getLogger(field.getDeclaringClass());
		} else {
			throw new RuntimeException("Could not create logger prototype.");
		}
	}

}
```
We have an internal Autoconfiguration/Starter module which provide the functionality, but I think this could/should be provided by the spring-boot logger autoconfiguration.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we've already considered this and decided that we don't want to do it. Please see #8106 for details
