### ISSUE TITLE
@SpringBootTest with WebEnvironment and @ContextHierarchy tries to start multiple webapps

### ISSUE THREAD

**Issue by andriusvelykis** [spring-projects/spring-boot#8311]
Hi,

This seems to be related to #8000: I am trying to migrate a test that uses `@ContextHierarchy` and `@WebIntegrationTest` to Spring Boot 1.5.1 and `@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)`.

However, I am getting context loading issues as it seems that multiple spring boot web applications are being started. To reproduce with a minimal example, I tried editing `SpringBootTestContextHierarchyTests` as created within #8000 :

```java
package org.springframework.boot.test.context;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.AbstractSpringBootTestEmbeddedWebEnvironmentTests.AbstractConfig;
import org.springframework.boot.test.context.SpringBootTestWebEnvironmentContextHierarchyTests.ChildConfiguration;
import org.springframework.boot.test.context.SpringBootTestWebEnvironmentContextHierarchyTests.ParentConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ContextHierarchy;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ContextHierarchy({
        @ContextConfiguration(classes = ParentConfiguration.class),
        @ContextConfiguration(classes = ChildConfiguration.class)})
@DirtiesContext
@RunWith(SpringRunner.class)
public class SpringBootTestWebEnvironmentContextHierarchyTests {

    @Test
    public void contextLoads() {  }

    @Configuration
    static class ParentConfiguration {
        @Bean
        MyBean myBean() {
            return new MyBean();
        }
    }

    @Configuration
    @EnableWebMvc
    static class ChildConfiguration extends AbstractConfig {
        ChildConfiguration(MyBean myBean) { }
    }

    static class MyBean {  }
}
```

This fails with the following message:

> org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.

The loader seems to expect `ParentConfiguration` to provide Web config beans as well. If I do that, i.e. make `static class ParentConfiguration extends AbstractConfig` as above, the test fails when a second embedded Tomcat instance is attempted at the same defined port.

Similar issues occur with RANDOM_PORT or MOCK web configurations, which, while not failing, do start up two web apps and two Tomcat instances (for the random port).

Is this an expected functionality? If so, what would be the best way to migrate web integration tests that use `@ContextHierarchy`?

**Comment by wilkinsona** [comment]
We're missing the implicit disabling of the web environment for any contexts with a child. That's normally done by `SpringApplicationBuilder`.

When building a merged context configuration, I can't see any easy way in the test framework to detect that the configuration will have a child. @sbrannen When dealing with a context hierarchy, how would you recommend that a bootstrapper detect that we're dealing with the context configuration for anything other than the bottom of the hierarchy?

**Comment by stojsavljevic** [comment]
@andriusvelykis as a workaround, can you split your test in two classes like this: https://github.com/stojsavljevic/multi-ctx/blob/master/multi-ctx-app-builder/src/test/java/com/alex/demo/ctx/ChildFirstCtxControllerTests.java
So, you define parent context configuration in separate class with `WebEnvironment.NONE`.

**Comment by philwebb** [comment]
We might be able to do something in `SpringBootTestContextBootstrapper.processMergedContextConfiguration` so that the `WebMergedContextConfiguration` is only used for one of the contexts.

**Comment by wilkinsona** [comment]
@philwebb That was my feeling too, but I couldn't figure out an easy way to figure out what part of the hierarchy we're working with. I was hoping @sbrannen could help hence my question to him above.

**Comment by philwebb** [comment]
I think I've got a fix for this. @andriusvelykis if you get a chance please try the latest 1.5.3 SNAPSHOT.
