### ISSUE TITLE
compileTestJava error on Spring Boot 1.5.1.RELEASE Gradle multi project

### ISSUE THREAD

**Issue by adolfogarci** [spring-projects/spring-boot#8312]
I have a gradle multi project (project_A, project_B, project_commons). with the structure:

```
rootProject.name = 'project'

include ':project_A'
include ':project_B'
include ':project_commons'
```

project_A and project_B apply gradle spring-boot plugin on version 1.5.1 but not project_commons (which refactors all common functionality needed for A and B).

project_A and project_B define a compile dependency on project_commons in their build.gradle files:

```
dependencies {
	compile project(':project_commons')
}
```

When I execute "gradlew build" I get an error on :project_A:compileTestJava because it cannot resolve code from project_commons. But if I execute a "gradlew test" there's no problem at all. Neither does a two step execution "gradlew build -x test" "gradlew test"

I've seen that one of the differences is that performing a build executes :project_A:bootRepackage prior to test compilation so I'm guessing there must be a problem with the classpath.

The only solution I've found is to add this line in build.gradle for project_A and project_B:

`testCompile project(':project_commons').sourceSets.main.output`

but I don't know why do I have to point to the actual code to make it work.

**Comment by wilkinsona** [comment]
Can you please provide a small sample the reproduces the behaviour you've described?

**Comment by adolfogarci** [comment]
Sure, let me create a sample and I'll post it. Thanks!

**Comment by adolfogarci** [comment]
Hi @wilkinsona, while trying to reproduce the error in a sample code I saw the problem was due to a configuration that was changing the compilation behaviour. Sorry for the inconvenience.
