### ISSUE TITLE
It should be easier to set which profile is active when running `gradle` tasks

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#832]
When I run: 

```
$ gradle bootRun -Pspring.profiles.active=dev

or

$ gradle bootRun -Dspring.profiles.active=dev
```

... my application does not start in the dev @Profile, and it should.

Here's my example project:

https://github.com/berlin-ab/springbootblog/tree/blog/profiles

**Comment by mhoudg** [comment]
I set spring profile in a shell variable as [was mentioned here](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-set-active-spring-profiles), this is simple enough for me.

```
SPRING_PROFILES_ACTIVE=dev gradle clean bootRun
```

**Comment by JamesMcMahon** [comment]
While the shell variable solution is great it still feels like this something missing from Spring boot, especially given it's close parity with Rails.

**Comment by jklap** [comment]
Would be nice if you could set the profile in build.gradle

**Comment by vjm** [comment]
adding `bootRun.systemProperties = System.properties` to your gradle will respect `gradle bootRun -Dspring.profiles.active=dev`.

**Comment by wilkinsona** [comment]
#1176 will address this

**Comment by mjustin** [comment]
I really like @jklap 's suggestion, which is different than this request (and the ticket it was closed as a duplicate of):

> Would be nice if you could set the profile in build.gradle cleanly such as
> 
> ```
> bootRun {
>   profile: development
> }
> ```

Is that worth creating a separate issue for?

**Comment by wilkinsona** [comment]
@mjustin Yes, a separate issue would be better for that as it's rather different to setting active profiles via the command line which is what's covered here and by #1176.

**Comment by kabmamadi** [comment]
Hello.
I couldn't make it work with -Dspring.profiles.active=dev.
So I directly added the profile in my environment: export SPRING_PROFILES_ACTIVE=test
And it works.

**Comment by marlonklc** [comment]
> When I run:
> 
> ```
> $ gradle bootRun -Pspring.profiles.active=dev
> 
> or
> 
> $ gradle bootRun -Dspring.profiles.active=dev
> ```
> 
> ... my application does not start in the dev @Profile, and it should.
> 
> Here's my example project:
> 
> https://github.com/berlin-ab/springbootblog/tree/blog/profiles

The best way that a found was:
`./gradlew bootRun --args='--spring.profiles.active=local'`

just specificy what profile do you want and be happy.

I hope that it works to another person.

Cheers!
