### ISSUE TITLE
http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/ is down

### ISSUE THREAD

**Issue by amitkin** [spring-projects/spring-boot#8323]
Failed to get resource: HEAD. [HTTP HTTP/1.1 502 Bad Gateway: http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-20160728.175440-590.pom]
Resource missing. [HTTP GET: http://repo.spring.io/milestone/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP HEAD: http://repo.spring.io/milestone/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.pom]
Resource missing. [HTTP HEAD: http://repo.spring.io/milestone/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.jar]
Resource missing. [HTTP GET: http://repo.spring.io/release/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP HEAD: http://repo.spring.io/release/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.pom]
Failed to get resource: HEAD. [HTTP HTTP/1.1 502 Bad Gateway: http://repo.spring.io/release/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.jar]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/1.4.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.4.0.BUILD-SNAPSHOT.jar]
Pa

**Comment by snicoll** [comment]
We are aware, please follow [@springops](https://twitter.com/springops/status/832604427945123841) for updates.
