### ISSUE TITLE
different result by adding RestartApplicationListener of devtools dependency

### ISSUE THREAD

**Issue by ielts0909** [spring-projects/spring-boot#8328]
if the project depend on RestartApplicationListener of devtools，it will set an resource loader  on applicationContext when spring prepare:

```java
	private void prepare(GenericApplicationContext applicationContext) {
		applicationContext.setResourceLoader(
				new ClassLoaderFilesResourcePatternResolver(this.classLoaderFiles));
	}
```
so it will change the result of selection by resource loader:

```java
	/**
	 * This implementation delegates to this context's ResourceLoader if set,
	 * falling back to the default superclass behavior else.
	 * @see #setResourceLoader
	 */
	@Override
	public Resource getResource(String location) {
		if (this.resourceLoader != null) {
			return this.resourceLoader.getResource(location);
		}
		return super.getResource(location);
	}

```

when i project contain the handler such as ResourceHttpRequestHandler in servlet environment

```xml
    <bean id="assetsHandler" class="org.springframework.web.servlet.resource.ResourceHttpRequestHandler">
        <property name="locations" value="/WEB-INF/${costa.server.name}/assets/"/>
    </bean>
```

the locations loader would lead two different result：

![image](https://cloud.githubusercontent.com/assets/1970191/23100529/937d4d04-f6be-11e6-99b1-c291d7ce54c2.png)

in this picture, cause the resources loader is null, it will use default result loader which can find assets on servlet environment

but, when we has a dependency of devtools starter, we cannot find the assets on servlet environment.(it will load file by ClassLoaderFilesResourcePatternResolver to find web resource)

![image](https://cloud.githubusercontent.com/assets/1970191/23100625/1537ed20-f6c1-11e6-9234-97363514f626.png)

**Comment by wilkinsona** [comment]
Duplicates #7752
