### ISSUE TITLE
Support for nested archives in other jars with PropertiesLauncher

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8334]
In addition to the work in #7221 I would like to add a new feature, which is to include nested archives in other jars than the "main" one. E.g. to launch a Spring Cloud Stream app with a kafka binder:

```
$ java -Dloader.path='jar:file:../kafka/target/kafka-0.0.1-SNAPSHOT.jar!/lib' -jar target/demo-0.0.1-SNAPSHOT.jar
```

Spring Cloud Dataflow and Zipkin have shown an interest in this kind of pattern. It looks pretty useful.

**Comment by wilkinsona** [comment]
Considering this to be an addition to #7221 is the right way to look at it. I think it'd be a mistake to add new features to PropertiesLauncher without first tightening up its contract.
