### ISSUE TITLE
AutoConfigureTestDatabase doesn't work on a superclass

### ISSUE THREAD

**Issue by dmitrysenkovich** [spring-projects/spring-boot#8338]
Hi everyone,
I'm writing E2E tests using JUnit. It was needed to make them run in parallel but I couldn't make it work parallelizing methods. So I refactored in the way there is one test per class and one base class with all the common fields and methods being used by every test. So the only class I wanted to be annotated is this base class. I'm using `@RunWith(SpringRunner.class)` and `@DataJpaTest`. To replace `H2` datasource with `Oracle` datasource I'm using `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`. But the only way I managed to make it work is adding this annotation on every test. It doesn't work on my base class for tests.
I was expecting it to work as all the other annotations but now I have to copy paste it. Please tell me if I'm doing something in a wrong way. Thank you!

**Comment by wilkinsona** [comment]
@dmitrysenkovich I can't reproduce the behaviour that you've described. I'm also confused about why you are trying to replace H2 with Oracle and why you're using `NONE` to trigger that replacement. Can you please provide a small sample that illustrates what you're trying to do and the behaviour that you've described?

**Comment by dmitrysenkovich** [comment]
@wilkinsona I need to test the app and related services (and the database as well) are working. So I can't use any mocks or test databases. I'm using `@AutoConfigureTestDatabase` because I found it affects datasource being choosed. Of course, I can provide a sample. Where would you like me to place it? BTW, thanks for such a quick response.

**Comment by wilkinsona** [comment]
> Of course, I can provide a sample. Where would you like me to place it? BTW, thanks for such a quick response.

Thank you. A repository on GitHub would be ideal, or you could attach a zip to this issue.

**Comment by dmitrysenkovich** [comment]
@wilkinsona Here is the [sample](https://github.com/dmitrysenkovich/SpringBootH2TestIssue/tree/h2). See `h2 `and `mysql `branches.

**Comment by wilkinsona** [comment]
Thanks for the sample. It works fine for me with 1.4.2.RELEASE or later. I believe that's due to [this change](https://github.com/spring-projects/spring-boot/pull/7326).

**Comment by prakashbalaji** [comment]
Looks like this is broken in spring boot 1.5.3 AutoConfigureTestDatabase is moved from orm.jpa package to jdbc package and using the one inside jdbc package in base class fails while the one inside orm.jpa works correctly.

**Comment by wilkinsona** [comment]
@prakashbalaji This should work as both variants of the annotation have the `@Inherited` annotation. Can you please provide a sample that illustrates the behaviour you're seeing and we can re-open this issue if necessary.
