### ISSUE TITLE
Why spring-boot-starter-velocity is 1.4.4.RELEASE instead of the latest 1.5.1.RELEASE

### ISSUE THREAD

**Issue by Caratacus** [spring-projects/spring-boot#8343]
Why spring-boot-starter-velocity is 1.4.4.RELEASE instead of the latest 1.5.1.RELEASE

[Maven Repository](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-boot-starter-velocity%22
)

![image](https://cloud.githubusercontent.com/assets/20453060/23157212/27992430-f855-11e6-800a-97a5aeddd5db.png)

**Comment by Caratacus** [comment]
I need to upgrade the version, but i use 1.4.4.RELEASE spring-boot-starter-velocity with 1.5.5.RELEASE spring-boot-starter-parent error

**Comment by snicoll** [comment]
Because it's deprecated and we've removed it in 1.5. See the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#deprecations-in-spring-boot-14)

Also, we don't use the tracker for questions, please use stackoverflow or gitter for that.
