### ISSUE TITLE
Create a public API to bind a ConfigurationProperties object

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8344]
From https://github.com/spring-cloud/spring-cloud-commons/issues/177

> if you need a public API to bind a ConfigurationProperties object, please ask for it and do not call our BPP directly.

Yes please.

**Comment by dsyer** [comment]
Maybe we should think about #2182 as well.

**Comment by snicoll** [comment]
So I've started to work on that (438fbfb) and I broke `@ConfigurationPropertiesBinding` and I don't know why. It looks like retrieving beans by type with a qualifier programmatically is harder than I thought. I'll check with @jhoeller when I get a chance.
