### ISSUE TITLE
Upgrade PostgreSQL JDBC dependency to version 42.0.0

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-boot#8351]
The PosgtreSQL JDBC team has upgraded their version policy for the JDBC driver Spring Boot should match, FAQ and details below.

https://jdbc.postgresql.org/documentation/faq.html#version-change

The PostgreSQL JDBC 

1.1. Why the versioning change from 9.4.xxxx to 42.x.x?

We have three issues we are trying to address here.

a) We do not want to be tied to the server release schedule.

Previously the version was based on the server release to declare some kind of compatibility, from 9.4.xxxx this was no longer the case and the increments was just in the last 4 digits, this leads us to the second issue.

b) Avoid confusion as to which version to use with which server version.

The naming scheme previously has 9.4 in it which leads people to believe it is for server version 9.4 only, when in fact it support PostgreSQL 8.2 and higher. That means that some users looking for PostgreSQL 9.5 were asking what is the version to use, and some users that still use PostgreSQL 8.4 were using the JDBC driver 8.4 Build 703.

The driver is version agnostic for the most point so there is no reason to tie it to a specific server version. Unless you have unusual requirements (running old applications or JVMs), this is the driver you should be using.

c) The previous version policy don't leave room for differentiate from bug fixes releases and feature releases.

The new version policy will allow us to use more or less Semantic Versioning, and have a more clear understanding of the versions.

1.2. Why the number 42?

42 was more or less chosen at random. But it is large enough to avoid any future conflicts with the server. Given current server project policies, server version 42 should come out in 2049, plus or minus a bit.

Some say that "The answer to the ultimate question of life, the universe and everything is 42."

1.3. What is not the 42.0.0 release?

This release is not a rewrite of the driver, is not using a new architecture, nor is using something special, it's the continuation of the same driver following a better versioning policy.

**Comment by snicoll** [comment]
Duplicates #8994
