### ISSUE TITLE
Issues hot reloading (or live reloading) templates from jar dependencies

### ISSUE THREAD

**Issue by duncan-at-hiveit** [spring-projects/spring-boot#8353]
Hi there,

I'm trying to successfully put together a Gradle project that has some Thymeleaf templates that are shared between web modules.  I'm then trying to get bootRun with devtools to successfully pick up changes to the shared templates without too much hassle for the developers on the project.

I'm running into problems when these shared templates are updated in that they tend not to be reusable after they've been updated.  I have created a test case for this at https://github.com/duncan-at-hiveit/spring-boot-devtools-dependency-issue (see "bootRun template reloading issue" section in the README).

The shared templates live in a module that is packaged as a jar, and the web modules are dependant on that project via a "compile project" Gradle dependency, which in turn makes the application when run with bootRun dependant on the jar file in the shared templates module's build/lib folder.

The issue is that when making a change to a template in the shared module and performing a ./gradlew shared-module:jar, the next time that template is viewed in the actual web module, more often that not you receive an error like:

org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="shared-page", line 3 - column 41] with root cause
org.xml.sax.SAXParseException: Premature end of file.

Sometimes the error differs.  Variants are:

* org.thymeleaf.exceptions.TemplateInputException: Error resolving template "shared-page", template might not exist or might not be accessible by any of the configured Template Resolvers
* org.xml.sax.SAXParseException: The element type "html" must be terminated by the matching end-tag "</html>"
* org.thymeleaf.exceptions.TemplateInputException: Exception parsing document] with root cause java.util.zip.ZipException: invalid code lengths set

It seems as though it's capturing the jar part-way through rebuilding or something, but I'm not 100% sure on this.

As I say, I have created a test case for this at https://github.com/duncan-at-hiveit/spring-boot-devtools-dependency-issue (see "bootRun template reloading issue" section in the README).

Any help would be greatly appreciated.
Many thanks,
Duncan

**Comment by snicoll** [comment]
That's not answering your question but why are you using gradle to start your app. You do realize that if you starter your app from your IDE none of this would matter, right?

**Comment by duncan-at-hiveit** [comment]
Hi Stephane,

Thanks for the reply, and it's a legitimate enough question.  Hopefully here I can explain a bit about the constraints I have.  Perhaps based on those you may have some clever idea :)

We have a Docker-based environment with various containers for APIs, web modules and SSO.  Originally we had hoped to keep this as live-like as possible and the web modules would be using "java -jar" to run their various services.

To support the devs in this environment we would be using remote hot reloads with spring-boot-devtools.  Unfortunately, due to the limitations we faced with https://github.com/spring-projects/spring-boot/issues/8321, we were forced to abandon this path and attempt to use bootRun instead which wasn't ideal but looked like a possible alternative approach.

So the limitation is that the web modules are within Docker containers, where bootRun is the Entrypoint for each container's image, and therefore we can't switch to starting things up in the IDE very easily.  To run with the IDE, we'd probably need to be looking at breaking the containerization and architecture of the solution, and create a lot of special-case configuration for development environments.

Having said all of this, if you've had any experience of people with this setup before and any alternative approaches that they might have taken, I'd be very interested in hearing about it.

Hope that's helped to clarify the constraints I have right now,
Many thanks again,
Duncan

**Comment by wilkinsona** [comment]
DevTools isn't intended to be used in the way that you've tried. As it says in the documentation, "any entry on the classpath that points to a folder will be monitored for changes". The "folder" part of that sentence is crucial. The setup in your `bootRun`-based example is asking DevTools to monitor a jar file which it doesn't support.

Your setup is sufficiently complicated that it falls outside of DevTools' scope. In such cases we generally recommend the use of JRebel instead.

**Comment by duncan-at-hiveit** [comment]
Hi Andy,

That's all the clarification I need, thanks very much for your help and
everyone else's.

Cheers,
Duncan

**Comment by duncan-at-hiveit** [comment]
Actually just one question for clarification if you don't mind?  I can see
what you're saying about the importance of the word "folderr" in that part
of the documentation, but I guess I thought that the ability to decide
which jars would trigger a restart in spring-devtools.properties suggested
that devtools also monitored the jar dependencies as well as build folders?

Thanks,
Duncan

**Comment by snicoll** [comment]
No it does not.
