### ISSUE TITLE
Bug report: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1

### ISSUE THREAD

**Issue by durianskh** [spring-projects/spring-boot#8366]
# parent pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.durian.test</groupId>
    <artifactId>multi</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <modules>
        <module>module-a</module>
        <module>module-b</module>
    </modules>
    <packaging>pom</packaging>

    <name>multi</name>
    <description>multi parent project</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.1.RELEASE</version>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

# module-a pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.durian.test</groupId>
        <artifactId>multi</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>module-a</artifactId>
    <packaging>jar</packaging>

    <name>module-a</name>
    <description>Demo project for Spring Boot</description>

</project>

# modula-b pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.durian.test</groupId>
        <artifactId>multi</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>module-b</artifactId>
    <packaging>jar</packaging>

    <name>module-b</name>
    <description>Demo project for Spring Boot</description>

    <dependencies>
        <dependency>
            <groupId>me.durian.test</groupId>
            <artifactId>module-a</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

</project>

# projct module-a
module-a has a class: me.multi.module.a.model.Teacher
`
public class Teacher {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
`

# project module-b
module-b has a controller: me.multi.module.b.controller.TeacherController
`
@RestController
public class TeacherController {

    @RequestMapping(value = "/greeting/{name}", method = RequestMethod.GET)
    public Teacher t(@PathVariable("name") String name) {
        Teacher teacher = new Teacher();
        teacher.setName(name);
        return teacher;
    }
}
`

# maven package
run comman in the parent folder:
`
mvn clean package
`
 
error info:
`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project module-b: Compilation failure: Compilation failure:
[ERROR] /Users/durianskh/Work/TestWorksapce/multi/module-b/src/main/java/me/multi/module/b/controller/TeacherController.java:[3,31] package me.multi.module.a.model does not exist
`

# my solution:
## first solution
do not use <version>1.5.1.RELEASE</version>, use: 1.3.7. RELEASE, like this:  <version> 1.3.7. RELEASE</version>

## second solution
move this code in the parent pom.xml: 

<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

to the module-b pom

**Comment by snicoll** [comment]
This isn't an bug. [Please read the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#executable-jar-layout) and [configure your project accordingly](http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/repackage-classifier.html)

**Comment by durianskh** [comment]
thx
