### ISSUE TITLE
Spring Boot use as dependency use case Enhancement

### ISSUE THREAD

**Issue by lievertz** [spring-projects/spring-boot#8384]
Enhancement

This is in reference to the solution for issue https://github.com/spring-projects/spring-boot/issues/6792.

I would like to suggest a use case that isn't considered by the proposed solution, which I am presently experiencing. In this case, I, as one who is going to utilize the fat-jar-project as a dependency, do not own the primary use of the project, which requires the fat jar format.

The proposed solution requires that the fat jar file name be changed, however owing to architectural guidelines, this is unacceptable in my case--the fat jar file needs to match a role name exactly. On the other hand, I, as one who is specifying the dependency name, could easily change what dependency I refer to in my project. I suggest two possible/non-exclusive solutions for my use case:
- Allow the `<classifier>` tag to change the regular jar name instead of the fat jar name.
- Provide (or maybe this exists, but if so I couldn't find it) a command line argument to build a regular jar from a project otherwise configured to produce a fat jar.

**Comment by wilkinsona** [comment]
> Provide (or maybe this exists, but if so I couldn't find it) a command line argument to build a regular jar from a project otherwise configured to produce a fat jar.

I believe you could do that by declaring Spring Boot's Maven plugin in a profile

**Comment by lievertz** [comment]
That is a good point... my concern there is that is a bigger ask since then I would need the upstream fat jar project to move to always building with a profile, if I understand correctly. To the extent that this accomplishes the technical feat, I wouldn't fault you to call that the solution or mark this as invalid. And indeed, if it were already configured as you suggest in a profile (or even better with the non-boot-dependent parts in a child project), this would clearly be the way to go.

From an organizational perspective, my goal would be to be able to consume the upstream fat jar project as a dependency with minimal or no changes to their project code and process. Speaking practically, my workaround for this issue right now is to hack their pom in a pre-build script in Jenkins, and I'll probably keep doing that rather than asking them to switch to a profile. So, I think there's still a valid use case here, but I can see how you might disagree.

**Comment by wilkinsona** [comment]
I definitely don't think your use case is invalid, but I do think that asking Spring Boot to solve it within your particular organisational constraints probably is. I don't want Spring Boot to reinvent the wheel for something that it's already possible to achieve by using a build profile or a slightly different module structure.
