### ISSUE TITLE
spring-boot-test-support reported as missing when running maven site goal

### ISSUE THREAD

**Issue by Catchwa** [spring-projects/spring-boot#8387]
When I run the maven site goal for a spring boot project like so:
`mvn site`
I receive two error messages relating to the "Dependency Management" report.

Based on [this](https://jira.exoplatform.org/browse/CRASH-247), I think that the first one will be resolved via #7006

The second one (and the intent of this issue) is because the Maven site plugin is trying to fetch https://repo.spring.io/libs-release/org/springframework/boot/spring-boot-test-support/1.5.1.RELEASE/spring-boot-test-support-1.5.1.RELEASE.pom - which doesn't exist

I've attached a minimal [pom.xml](https://github.com/spring-projects/spring-boot/files/795270/pom.xml.txt) that demonstrates the issue, and the full maven [output](https://github.com/spring-projects/spring-boot/files/795273/output.txt) from my machine.

My system info is as follows:

> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:11:47+10:30)
> Java version: 1.8.0_112, vendor: Oracle Corporation
> Java home: C:\Program Files\Java\jdk1.8.0_112\jre
> Default locale: en_AU, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by snicoll** [comment]
Duplicates #8165
