### ISSUE TITLE
spring-boot-starter-undertow is broken after Spring Boot V1.3.4

### ISSUE THREAD

**Issue by cloudxxx8** [spring-projects/spring-boot#8388]
## Summary

I followed the official instruction to use Undertow instead of Tomcat:
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html

In the latest Spring Boot 1.3 (1.3.8), the error always occurs when the application starts up.

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
```

I've verified it on different version, and found out it works fine before V1.3.3 and it is broken after V1.3.4.

## Recreate Steps

1. Create a new Spring Starter Project and check web feature with Spring Boot V1.3.8
2. Modify pom.xml to exclude spring-boot-starter-tomcat and add spring-boot-starter-undertowv (please see the attachement) [undertow-test.zip](https://github.com/spring-projects/spring-boot/files/795542/undertow-test.zip)
3. Run the Spring Boot Application
4. Verify the error occurs [error.zip](https://github.com/spring-projects/spring-boot/files/795548/error.zip)
5. Change the Spring Boot version to 1.3.3, and run the application again
6. Verify the application starts correctly

**Comment by snicoll** [comment]
Your local maven cache is corrupted. While downloading the undertow support for 1.3.8, a jar wasn't created properly and the VM can't open it and can load the requested class.

That sample works perfectly fine on my box. You should try to run `mvn dependency:purge-local-repository` to attempt to download them again. If that doesn't work, delete the artifacts for 1.3.8 for your local repo and try to download them again.
