### ISSUE TITLE
Add a possibility to reset CaptureOutput

### ISSUE THREAD

**Issue by SchulteMarkus** [spring-projects/spring-boot#8390]
Hi there,

I am using [OutputCapture](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/rule/OutputCapture.java) as part of my integration tests.
I am testing the spring-boot application as suggested in [boot-features-testing-spring-boot-applications](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications).
After my application is booted in my integration-test, I am using [HtmlUnit](http://htmlunit.sourceforge.net/) for making HTTP calls against the running application.
I am testing a multi-step form, so I am performing several HTTP calls. Each of which produces a lot of logging, which I can access by using OutputCapture.

When doing my second HTTP call against the application, I want to access the logs produced only by/after this call. Right now, OutputCapture keeps increasing, so the first log line(s) (produced by the first HTTP call) is kept forever.
On this point, I would be very happy to have a kind of "reset"-method in OutputCapture. I would use this after having done my first HTTP call.

By the way, I have decided to use a workaround in my project:

    class ResetableOutputCapture extends org.springframework.boot.test.rule.OutputCapture {
      public void reset() {
        super.releaseOutput();
        super.captureOutput();
      }
    }

**Comment by philwebb** [comment]
That would seem like a nice addition. I've marked this one as `ideal-for-contribution`.

**Comment by snicoll** [comment]
Closing in favour of PR #8490
