### ISSUE TITLE
Allow to force the use of reactive in integration tests when both servlet and reactive are available

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8393]
Right now if we have both reactive and servlet we can use `WebApplicationType` on `SpringApplication` to force a reactive environment (or to bypass the check altogether).

There's no such thing for `@SpringBootTest` and we're the first affected by that issue. If we want to write an integration test in `@SpringBootTest` there is no way to test the reactive side of things without this change.

@bclozel and I brainstormed and we conclude that the only way would be to have an additional signal (a single annotation?). We tried to add an extra option in `@SpringBootTest` alongside `webEnvironment` and it didn't work well since everything is nicely derived from that.

We need to move on so my goal is that check if `spring.main.web-application-type` is set in a `@TestPropertySource` and if it's set use that. That will at least allow us to write the integration tests we need.

**Comment by edeandrea** [comment]
FWIW - finding this issue was very helpful. We have an internal framework that sits on top of Spring Boot and support both Servlet & Reactive, so we have to also write tests which support both "sides".

**Comment by snicoll** [comment]
@edeandrea thanks but [that is also documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-web-app-type)

**Comment by bclozel** [comment]
After discussing that again with @snicoll , we feel like this is more of a corner case and that surfacing that at that level of the API doesn't feel right. I'm closing this for now and we can reopen if we get more reports about similar issues.

**Comment by edeandrea** [comment]
As long as `spring.main.web-application-type=reactive` remains then I would agree that is all that we need.
