### ISSUE TITLE
Allow setting of `fileDateFormat` field on `AccessLogValve` property via `server.tomcat.accesslog.fileDateFormat`

### ISSUE THREAD

**Issue by eileenh** [spring-projects/spring-boot#8396]
I am trying to configure my AWS application to use Enhanced Health. In order to do this, I need to write an access log with particular properties described by Amazon [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-serverlogs.html). The relevant requirements are:
- Name logs using the following format: `application.log.$year-$month-$day-$hour`
- Rotate logs once per hour

My Spring application uses Tomcat, and I believe in order to support the above I need to be able to set the **fileDateFormat** property on the AccessLogValve described [here](https://tomcat.apache.org/tomcat-5.5-doc/config/valve.html#Access_Log_Valve). It does not appear to be possible right now. Some of the other Tomcat `AccessLogValve` properties are configurable via [Spring application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) under server.tomcat.accesslog.*, but not **fileDateFormat**.

I saw request #7456 had been implemented for the **buffered** property, and was hoping somebody could add this property as well. 

It might be worth considering adding any other missing ones, also.

**Comment by philwebb** [comment]
You should be able to customize that using a `EmbeddedServletContainerCustomizer` bean. If you cast the `container` to a `TomcatEmbeddedServletContainerFactory` you can either add or access the `Valve` instances. You'll need to `@Order` your customizer so that it happens after `ServerProperties` (or you could ignore add the valve entirely yourself and ignore what `ServerProperties` does).

**Comment by philwebb** [comment]
Adding `fileDateFormat` support also shouldn't be too difficult if you'd like to have a go at submitting a PR?

**Comment by snicoll** [comment]
Closing in favour of PR #8474
