### ISSUE TITLE
Environment variables not picked up by application.properties in 1.5.1.RELEASE

### ISSUE THREAD

**Issue by maciejp** [spring-projects/spring-boot#8398]
I wanted to upgrade from Spring Boot 1.4.4.RELEASE to 1.5.1.RELEASE but setting the active profile using an environment variable does not work on the new version.
My application properties:

`spring:
  profiles:
    active: ${MY_ENV_VARIABLE}`

MY_ENV_VARIABLE is set to dev.

Logs for 1.5.1.RELEASE

> 2017-02-24 11:04:53.528 DEBUG 12172 --- [                main] z.l.p.p.MyApplication : Running with Spring Boot v1.5.1.RELEASE, Spring v4.3.6.RELEASE
2017-02-24 11:04:53.528  INFO 12172 --- [                main] z.l.p.p.MyApplication : The following profiles are active: ${MY_ENV_VARIABLE}

Logs for 1.4.4.RELEASE

> 2017-02-24 11:06:12.605 DEBUG 5368 --- [                main] z.l.p.p.MyApplication : Running with Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE
2017-02-24 11:06:12.606  INFO 5368 --- [                main] z.l.p.p.MyApplication  : The following profiles are active: DEV

Is that a bug or am I doing something wrong?

**Comment by snicoll** [comment]
Duplicates #8234
