### ISSUE TITLE
Consider using Hazelcast first if JCache is present

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8408]
Since we have a general auto-configuration for Hazelcast (that will create a `HazelcastInstance` regardless of the use of caching) and that most users actually will want to use the same infrastructure for caching, it feels weird that when we add the cache api we switch to the JCache provider all the sudden.

At the moment, we can't hook the existing hazelcast instance into such standard JCache bootstrap setup so it would be probably wise to prefer the native implementation.

I'd like this to happen in 1.5 still...

**Comment by philwebb** [comment]
Sounds sensible to me. Main question I have is will it break anything? I imagine it will be transparent, but it seems somewhat risky for 1.5.x

**Comment by snicoll** [comment]
1.5 is broken at the moment anyway so yes it will change behaviour but for the better IMO

See https://github.com/hazelcast/hazelcast/issues/9958 (I just want to double check it's not crazy)

**Comment by snicoll** [comment]
I think I've found a way to fix #8275 so that would work if the instance name is provided. It looks like they might also fix the URI location in 3.9 so all in all, I am not sure we're in a hurry to change this. Let's reconsider if that issue arises again.
