### ISSUE TITLE
Upgrade log4j to 2.8

### ISSUE THREAD

**Issue by akiraly** [spring-projects/spring-boot#8413]
Spring Boot currently uses 2.7. The latest stable is 2.8.

**Comment by roberthunt** [comment]
You can manually override the version of any of the curated Spring Boot dependencies:
http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#using-boot-dependency-management

If you're using Maven it's just a case of adding this to your pom:
```
<properties>
  <log4j2.version>2.8</log4j2.version>
</properties>
```

**Comment by wilkinsona** [comment]
Duplicates #8854.
