### ISSUE TITLE
spring boot detects jersy auto-configuration,although the jersy not used

### ISSUE THREAD

**Issue by IbrahimAl-Zreqat** [spring-projects/spring-boot#8419]
I'm working on spring boot 1.3.7 project, that used spring 4.2.7 version, I finished the project and tried to deploy it on jboss server and the log shows the following: 

> [ServerService Thread Pool -- 133] [INFO ] [servlet:313] - Spring WebApplicationInitializers detected on classpath :[org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration$JerseyWebApplicationInitializer@647be13a, com.myproject.BaseConfig]

The base configuration is in the BaseConfig class which annotated with @SpringBootApplication annotation, I tried to exclude the JerseyAutoConfiguration and JerseyWebApplicationInitializer classes, but unfortunately not working.

**Comment by wilkinsona** [comment]
I don't think you can be using Spring Framework 4.2.7 as 4.2.6 and later no longer log the initializer class names. See #5778 for details.

**Comment by IbrahimAl-Zreqat** [comment]
ok, thanks @wilkinsona

**Comment by arathim** [comment]
i have the same issue. SpringServletContainerInitializer.onStartup shows there are 2  WebApplicationInitializers. I tried excluding JerseyAutoConfiguration class using spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration
in application.properties. But it still gets executed. Iam using spring boot 2.1.1 with spring-web (5.1.3). Could you tell me how can I exclude JerseyAutoConfiguration?

**Comment by snicoll** [comment]
@arathim please don't ask questions, especially on closed issues. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. It is a bit unclear what you're asking here. If you believe you've found a bug, please create a separate issue with a sample we can clone or download and run ourselves. Questions have to be asked on StrackOverflow or you can chat with the community on Gitter.
