### ISSUE TITLE
Please provide Swagger support via starter module

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#842]
To document REST api's Swagger is a neat library. There is also also a specific https://github.com/martypitt/swagger-springmvc library for integration with Spring.
There are also blog entries where people have setup Swagger successfully with Spring Boot like http://www.leveluplunch.com/blog/2014/04/16/spring-boot-swagger-springmvc-configuration/.

Anyway I think it would be nice if Spring Boot would provider a starter module to setup Swagger automatically within a Spring Boot setup. Off course it should be disable (like the actuator) via application properties.

This issue is to see if more people are interested in this.

**Comment by khoubyari** [comment]
+1 for the idea of a swagger starter module for spring boot

**Comment by olivergierke** [comment]
-1 for reasons already known and widely exposed on the interwebs…

**Comment by philwebb** [comment]
I'm afraid I'm currently -1 on this as well and prefer the approach taken in [Spring RestDocs](https://github.com/spring-projects/spring-restdocs).

**Comment by snicoll** [comment]
-1 here as well.

**Comment by dsyer** [comment]
I might as well repeat what I said above. I would be happy to see swagger support, but only as an option when there is clearly a better choice.

**Comment by marceloverdijk** [comment]
I've also taken Spring RestDocs approach which is very nice.
Although I think for other cases Swagger might be useful. Probably a swagger starter can be developed by the community.
Fair enough to close this issue I think.

**Comment by Aloren** [comment]
Hi guys! 
Were there any changes regarding this topic or `spring-boot-starter-swagger` is still not desired in Spring Boot project?

**Comment by wilkinsona** [comment]
Nothing has changed from our perspective.

For users who like the Swagger approach, Springfox remains the recommended choice. If auto-configuration was to be offered, I think the Springfox project would be the best place for it. That said, looking at its [quick start](http://springfox.github.io/springfox/docs/current/#springfox-spring-mvc-and-spring-boot), there does not appear to be much that could be auto-configured without the end result being programming by properties.
