### ISSUE TITLE
Document 'fast' profile in contributing readme

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8424]
It's possible that checkstyle is putting contributors off. We could leave it as something that only we do and have local builds and Travis be more lenient.

**Comment by rajadilipkolli** [comment]
+1

**Comment by philwebb** [comment]
We discussed this a little on our call and we're in general agreement that the checkstyle rules generally save us work so we'd like to keep them. We will update the contributing instructions to show how the `fast` profile can be used if they're causing problems.
