### ISSUE TITLE
Property sources order in actuator /env endpoint

### ISSUE THREAD

**Issue by iNikem** [spring-projects/spring-boot#8437]
I was under expression that the order of property sources as reported by Actuator /env endpoint corresponds to the actual order of property lookup. But in reality it seems to be random.

It would be tremendously easier to understand what is the actual configuration of the running Spring Boot application if one could just scan /env endpoint report from top to bottom to understand the actual value of any given property.

**Comment by snicoll** [comment]
What makes you think to order is random? What you're asking is exactly what is intended.

**Comment by snicoll** [comment]
That's rather vague. Can you share a sample that reproduces the problem?

**Comment by iNikem** [comment]
Hm. In sample freshly created project the order is indeed as expected. It seems that our old project somehow disturbs the force around Spring Boot.
