### ISSUE TITLE
Spring profiles don't read custom environment variables for Spring Boot version > 1.4.4

### ISSUE THREAD

**Issue by wnuq** [spring-projects/spring-boot#8442]
Below property don't read environment variable  after change Spring Boot version from 1.4.X to 1.5.X

spring.profiles.active=${MY_ENV:local}

Now I can use only set spring.profiles.active environment variable or -D option. (but it's not solution)

**Comment by wilkinsona** [comment]
Duplicates #8234. Please take a moment to search existing issues before opening a new one.
