### ISSUE TITLE
Sending Undertow access logs directly to Logstash

### ISSUE THREAD

**Issue by medzin** [spring-projects/spring-boot#8445]
I would like to send Undertow access logs (enabled by `server.undertow.accesslog.enabled` property) directly to Logstash. Current implementation of `UndertowEmbeddedServletContainerFactory` does not allow to change internally used `AccessLogReceiver` from `DefaultAccessLogReceiver` to any other implementation, that will allow me to do something with these logs. Is there any chance for such functionality, or some workaround for this problem (parsing logs file and sending them to Logstash is not an option)?

**Comment by wilkinsona** [comment]
For this sort of use case, rather than trying to use the `server.undertow.accesslog.*` configuration properties, I would configure the access log programatically using an `UndertowDeploymentInfoCustomizer`.

**Comment by alexmora81** [comment]
I have the same use case and I can't find any references to using `UndertowDeploymentInfoCustomizer` did anyone here figured out how to do this?
