### ISSUE TITLE
Enhance spring-boot-actuator with Graphite support

### ISSUE THREAD

**Issue by marksailes** [spring-projects/spring-boot#8456]
I'm using Spring Actuator to produce and manage the metrics my application produces. I would like this to be collected into Graphite so they can be examined alongside other applications.

As far as I can see there is no direct support for this. From examples I can find online some people seem to be doing this using the DropWizard integrations.

To solve this problem myself I wrote an implementation of MetricWriter which takes the prefix, host and port and writes the metrics over a socket connection. I'd be more than happy to contribute this.

**Comment by philwebb** [comment]
We're certainly interested, however, at some point in Boot 2.0 we'll be revisiting quite a bit of the actuator code. It might be worth waiting until that work has been completed.

**Comment by marksailes** [comment]
Hi, @philwebb I'm happy to prepare what I have and send it over, then you can decide whether to take it now or not. But I'm also happy to help refactor it for whatever changes are made in Boot 2.0 as well.

I've use Spring a lot in my career it would be nice to contribute back now I'm in a position to do so, even if it's in a small way.

**Comment by philwebb** [comment]
@marksailes If you have something working already and you'd like to submit a pull-request then that would be great! Just don't worry too much if it's not 100% polished because we're likely to need to change it anyway. We also might not be able to give feedback that quickly (since we're still working on the reactive web support at the moment).

**Comment by marksailes** [comment]
Great :)

**Comment by snicoll** [comment]
Closing in favour of the PR #8475
