### ISSUE TITLE
spring-boot-starter-remote-shell conflicts with lombok

### ISSUE THREAD

**Issue by aniketbhatnagar** [spring-projects/spring-boot#8457]
If both lombok and spring-boot-starter-remote-shell are present in classpath (for example as maven dependencies), then the compilation of project may fail as lambook transformations are never applied.

**Comment by wilkinsona** [comment]
It works fine for me with 1.4.4.RELEASE. Can you please provide a sample the reproduces the problem?

**Comment by aniketbhatnagar** [comment]
I tried created a sample project but couldn't exactly reproduce the issue but I think I might have found the root cause. It seems like spring-boot-starter-remote-shell pulls in older version of spring through transitive dependencies. I have created a sample project -  https://github.com/aniketbhatnagar/spring-remote-lombok that proves that it pulls in older version of spring and a exclusion workaround that fixes it. I even tried exclusion in my project and lombok issues went away

**Comment by wilkinsona** [comment]
We recommend that you use Spring Boot's dependency management, either by using `spring-boot-starter-parent` as your pom's parent or by importing  `spring-boot-dependencies` into your pom's dependency management. You've chosen not to do that so it's up to you to manage the dependencies and ensure that you're using the correct versions of all of your direct and transitive dependencies.
