### ISSUE TITLE
Reconsider use of `/tmp` by TomcatEmbeddedServletContainerFactory

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8459]
Originally raised in #5009 the `/tmp` folder can get cleared out mid-flight. [This comment](https://github.com/spring-projects/spring-boot/issues/5009#issuecomment-281521469) makes a compelling case for using `/var/cache` (although I'm not sure if that's technically feasible).

**Comment by wilkinsona** [comment]
I don't think that `/var/cache` is an appropriate location. The FHS says that "the application must always be able to recover from manual deletion of these files" which is not the case.

I actually think that `/tmp` is reasonable. The FHS says:

- Programs must not assume that any files or directories in /tmp are preserved between invocations of the program.
- Although data stored in /tmp may be deleted in a site-specific manner, it is recommended that files and directories located in /tmp be deleted whenever the system is booted.

We don't require the files to be preserved between invocations and things will work fine if the recommendation for when to delete files is followed.

**Comment by philwebb** [comment]
OK, thanks @wildcart for the suggestion but this doesn't seem like an option we can use.
