### ISSUE TITLE
spring-boot-actuator health reports solr down

### ISSUE THREAD

**Issue by afaulconbridge** [spring-projects/spring-boot#8463]
Using 2.0.0.BUILD-SNAPSHOT and the health endpoint of spring-boot-actuator for solr queries a URL of `/solr/admin/ping` when it should use `/solr/<corename>/admin/ping`. This results in a 404 error and a "down" status, even though solr is actually running fine. This was tested with solr 6.3.0

This may be related to https://jira.spring.io/browse/DATASOLR-364 but it would be nice for it to be enhanced for multi-core cases anyway. One way this could be done is below, using a `SolrClientFactory` instead of a `SolrClient` and then iterating over all the cores that have been registered:

```
package org.springframework.boot.actuate.health;

import org.apache.solr.client.solrj.SolrClient;
import org.springframework.data.solr.server.SolrClientFactory;

public class SolrHealthIndicator extends AbstractHealthIndicator {

	private final SolrClientFactory solrClientFactory;

	public SolrHealthIndicator(SolrClientFactory solrClientFactory) {
		this.solrClientFactory = solrClientFactory;
	}

	@Override
	protected void doHealthCheck(Health.Builder builder) throws Exception {
		for (String core : this.solrClientFactory.getCores()) {
			SolrClient client = this.solrClientFactory.getSolrClient(core);
			Object status = client.ping().getResponse().get("status");
			builder.withDetail(core, status);
		}
                builder.up();
	}
}
```

**Comment by wilkinsona** [comment]
I don't think this is related to DATASOLR-364 as Spring Boot 1.4.x also appears to be affected. It uses Spring Data Solr 2.0.x and, AFAIK, DATASOLR-364 only affects 2.1.x and later.

With Solr running locally, adding the actuator and starter-web dependencies to the Data Solr sample is sufficient to reproduce the problem:

```
$ http localhost:8080/health
HTTP/1.1 503
Connection: close
Content-Type: application/json;charset=UTF-8
Date: Thu, 02 Mar 2017 13:21:40 GMT
Transfer-Encoding: chunked
X-Application-Context: application

{
    "diskSpace": {
        "free": 102770819072,
        "status": "UP",
        "threshold": 10485760,
        "total": 499046809600
    },
    "solr": {
        "error": "org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://127.0.0.1:8983/solr: Expected mime type application/octet-stream but got text/html. <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /solr/admin/ping. Reason:\n<pre>    Not Found</pre></p>\n</body>\n</html>\n",
        "status": "DOWN"
    },
    "status": "DOWN"
}
```

**Comment by mkaranta** [comment]
Could this bug be the reason I've been seeing the following, despite not using or configuring solr in my project?
```
{"status":"DOWN","diskSpace":{"status":"UP","total":16767832064,"free":10446864384,"threshold":10485760},"solr":{"status":"DOWN","error":"org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://127.0.0.1:8983/solr"}}
```

**Comment by snicoll** [comment]
We really need to provide a default `schema.xml` for the sample that we have. It looks like the default ping implementation expects a core named `admin` so we can't really on that anymore indeed.
