### ISSUE TITLE
Make sure @EnableResourceServer triggers the autoconfig for a resource server with the new jwk support

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8468]
`ResourceServerCondition` has some magic config combinations that it looks for when it wants to try and decide whether yo activate the autoconfig for a resource server. There are some new features there in the `security.oauth2.jwk.*` keys sets stuff, so we need to add those keys to the condition. Or rethink how the condition works (we could make it an explicit opt out instead of an implicit opt in).

**Comment by philwebb** [comment]
Did [this commit](https://github.com/spring-projects/spring-boot/commit/67810abd9e58cfab42cb0ecb17c9834a674ac2ba) not update that condition?

**Comment by dsyer** [comment]
Could be duplicated or coevered alread in #8317. I didn't see that before. Maybe we should close this and just put a comment in there.

**Comment by dsyer** [comment]
@philwebb I didn't see that code. I guess I didn't get that snapshot build yet locally.

**Comment by philwebb** [comment]
@dsyer It's been in 9 days, was there some other reason?

**Comment by dsyer** [comment]
I'm confused now. I can see that code in snapshots. I was trying 1.4, 1.5.1 and 1.5.2 all in the same app. I probably just got mixed up.
