### ISSUE TITLE
Disabling the security flag, the `/beans` endpoint is returning an empty array.

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8473]
Noticed my Mark F in 1.5.1

**Comment by wilkinsona** [comment]
Is he sure that's what triggers it. Sounds a lot like #8146.

**Comment by wilkinsona** [comment]
Having read the description of the problem on Slack, I'm pretty sure this is a duplicate.

**Comment by markfisher** [comment]
Yes, it is a duplicate. I tried running the same app via `java -jar` and the `/beans` endpoint worked as expected. Thanks!
