### ISSUE TITLE
setRegisterErrorPageFilter(false) not disable ErrorPageFilter

### ISSUE THREAD

**Issue by mnhock** [spring-projects/spring-boot#8477]
If I disable the ErrorPageFilter registration with this configuration, the ErrorPageFilter will be loaded nevertheless.

The configuration:
```
public class Application extends SpringBootServletInitializer {

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        setRegisterErrorPageFilter(false);
      ...
    }   
}
```

The Filter will be loaded through this code in SpringBootServletInitializer even the configuration above.

```
@Configuration
static class ErrorPageFilterConfiguration {
	@Bean
	public ErrorPageFilter errorPageFilter() {
		return new ErrorPageFilter();
	}
}
```
The only way for me to disable the filter is with this configuration:
```
@Bean
public FilterRegistrationBean disableSpringBootErrorFilter(ErrorPageFilter filter) {
        FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
        filterRegistrationBean.setFilter(filter);
        filterRegistrationBean.setEnabled(false);
        return filterRegistrationBean;
}
```

I think it should work without this explicit FilterRegistrationBean configuration.

**Comment by wilkinsona** [comment]
This problem was introduced in [this commit](https://github.com/spring-projects/spring-boot/commit/1464425d64ffcbf8824d13d0f66ddf6ce7689eb2).
