### ISSUE TITLE
@AuthenticationPrincipal null after update to Spring Boot 1.5.1

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#8478]
I have a working Spring Boot application using version 1.4.2. I now try to upgrade it to Spring Boot 1.5.2, but I am having issues in my `@RestController` classes that `@AuthenticationPrincipal` is now suddenly `null`.

I am combining form login with oauth2.

I debugged in `AuthenticationPrincipalArgumentResolver` and I see that with Spring 1.4.2 the `authentication` variable has an object of type `org.springframework.security.oauth2.provider.OAuth2Authentication` with the principal my custom `UserDetails` object. 

However, the same code with Spring 1.5.1 gives me an `anonymousUser` String as `principal`.

I do have `@EnableWebSecurity` with Spring 1.4.2, but I removed that with the upgrade to 1.5.1.

My websecurity class has something like this:

```
    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
            // api security is handled elsewhere (See OAuth2ServerConfiguration)
            .antMatchers("/api/**", "/oauth/**")
            .permitAll()
            // end api security
            .antMatchers("/", "/home").permitAll()
            .antMatchers("/management/health", "/management/info").permitAll()
            .antMatchers("/management/**").hasRole(UserRole.ADMIN.name())
            .anyRequest().authenticated()
            .and()
            .formLogin().loginPage("/login")
            .permitAll()
            .and()
            .logout().permitAll();
    }
```
So it allows all api calls to be handled by the OAuth2 config.

The oauth config has this:

```
        @Override
        public void configure(HttpSecurity http) throws Exception {
            http
                    .antMatcher("/api/**")
                    .authorizeRequests()
                    .anyRequest()
                    .authenticated();
        }
```

So any request that is not for the api will be considered authenticated from oauth2 view and the form login will be used for that.

Any change in Spring Boot 1.5.1 that would explain this change in behaviour?

**Comment by wilkinsona** [comment]
Have you read the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter)?

**Comment by wimdeblauwe** [comment]
Yes, but seems I missed that part :-)

Adding this line to my `application.properties` fixes it:

```
security.oauth2.resource.filter-order=3
```

**Comment by wimdeblauwe** [comment]
The release note does not state why the order was changed? Is is bad idea to have it like this or why was the default changed?

**Comment by wilkinsona** [comment]
Please see #5072 for the rationale for the change.
