### ISSUE TITLE
PropertiesLauncher cannot be used to run a jar with an alternative layout

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8480]
Simply changing the nested libs and classes from `BOOT-INF/lib` and `BOOT-INF/classes` should be an easy target for `PropertiesLauncher` but it can't be used to run such a jar at the moment because it only works for nested jars, not nested classes, so I'd like to fix that. There is a special (common) case where the classes are actually in the root of the archive, and I think I'd like to support that too, but that could be a secondary goal.

**Comment by wilkinsona** [comment]
> There is a special (common) case where the classes are actually in the root of the archive,

History has taught us that that's not a good idea. You either end up with classes on the classpath twice or you have to use an unconventional delegation model which breaks Java agents among other things. We shouldn't do anything that encourages such arrangements.

Also, it may we'll be too late for 1.5.2 at this stage so I'm removing the milestone.

**Comment by philwebb** [comment]
Closing in favor of PR #8486
