### ISSUE TITLE
Spring Boot 1.5.1 cannot inject classes named `validator`

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-projects/spring-boot#8481]
After upgrading to Spring Boot 1.5.1 my application fails to start claiming that a bean cannot be found.
The bean in question is a simple class named `Validator`, marked as `@Component`.

MWE demonstrating the issue:
```java
package com.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

@SpringBootApplication
public class ValdemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(ValdemoApplication.class, args);
    }
}

@Component
class Validator {
}

@Component
class Foo {

    @Autowired
    private Validator validator;

}
```

The code shown will run fine on Spring Boot 1.4.3, but will fail to start on 1.5.1.
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field validator in com.example.Foo required a bean of type 'com.example.Validator' that could not be found.
```

**Comment by snicoll** [comment]
That exact same app works for me. Even if that is minimal, please provide the URL to a repo or a zip of something we can run.

**Comment by KamikaZeeFu** [comment]
The issue seems to occur when `spring-boot-starter-web` is on the classpath.
See https://github.com/KamikaZeeFu/Boot-8481

**Comment by snicoll** [comment]
There is a `ValidationAutoConfiguration` that exists in 1.5 now. It creates a `Validator` bean with that name. Because no bean of type `javax.validation.Validator` exists, it creates one and override your bean definition.

This is a problem that you can have with basically anything the auto-configuration provides.

**Comment by snicoll** [comment]
Given that `validator` is really a generic name, I'll change the name in the auto-config. Namespacing the auto-configuration bean is something we expect to do in 2.0
