### ISSUE TITLE
ConfigurationProperties metadata: no generics for java.util.List

### ISSUE THREAD

**Issue by GoGoris** [spring-projects/spring-boot#8487]
I found a problem when generating the metadata for a List field in a ConfigurationProperties file. When I use a List-field there is no generic in the metadata file. However for Map or Set fields there is metadata available. This gives a warning in IntelliJ and breaks code completion.

```java
@Validated
@ConfigurationProperties(prefix = "security.oauth2")
public class ClientDetailsProperties {

	@NestedConfigurationProperty
	private List<AutoApprovedClientDetails> clients;

	@Nonnull @NotEmpty(message = "At least one client is needed in security.oauth2.clients")
	public List<AutoApprovedClientDetails> getClients() {
		return clients;
	}

```
List:
``` json
      "sourceType": "....config.properties.ClientDetailsProperties",
      "name": "security.oauth2.clients",
      "sourceMethod": "getClients()",
      "type": "java.util.List"
```

Map:
```json
    {
      "sourceType": "...config.properties.RoleMappingProperties",
      "name": "security.reverse-mapping",
      "type": "java.util.Map<java.lang.String,org.springframework.security.core.GrantedAuthority>"
    }
```

Boot version: 1.5.2.RELEASE

**Comment by snicoll** [comment]
Spring Boot itself has plenty of field of type `List` and they all expose a generic information. Can you please share a sample that reproduces the problem?

**Comment by GoGoris** [comment]
Sorry I am trying to create a List of objects and I can't find this in the spring metadata files. Is it even possible to put a List of nested objects in the metadata? I can't find how to do it.

**Comment by snicoll** [comment]
You are reporting an issue I can't reproduce. So please provide a link to a sample I can run to reproduce the problem.

**Comment by GoGoris** [comment]
OK I discovered that the error highlighting is a known issue in IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-151708

Howver the generic issue stays, here is a sample project: https://github.com/GoGoris/boot-list-properties
This is my metadata if I compile the project with maven:
```json
{
  "hints": [],
  "groups": [
    {
      "sourceType": "test.ClientDetailsProperties",
      "name": "security.oauth2",
      "type": "test.ClientDetailsProperties"
    },
    {
      "sourceType": "test.ClientDetailsProperties",
      "name": "security.oauth2.clients",
      "sourceMethod": "getClients()",
      "type": "java.util.List"
    }
  ],
  "properties": []
}
```

**Comment by philwebb** [comment]
@GoGoris 

You need to remove the `@NestedConfigurationProperty` annotation. It's only needed if you're referring to a top-level class that you want to appear nested.

Once the annotation has gone you'll get:

```json
{
  "hints": [],
  "groups": [
    {
      "sourceType": "test.ClientDetailsProperties",
      "name": "security.oauth2",
      "type": "test.ClientDetailsProperties"
    }
  ],
  "properties": [
    {
      "sourceType": "test.ClientDetailsProperties",
      "name": "security.oauth2.clients",
      "type": "java.util.List<org.springframework.security.oauth2.provider.client.BaseClientDetails>"
    }
  ]
}
```

**Comment by GoGoris** [comment]
Thank you for your time. Sorry I thought that I tried without the annotation.

**Comment by philwebb** [comment]
@GoGoris No problem, it's an easy one to miss and the result isn't all that obvious.

**Comment by ASaunin** [comment]
Why don't to add a feature to configure multiple clients from application.yml? 
@philwebb what do you think about it?
