### ISSUE TITLE
@Scheduled annotation does not work in test if bean is annotated with @SpyBean

### ISSUE THREAD

**Issue by dome313** [spring-projects/spring-boot#8489]
The Spring boot configuration I'm using is 
```
@SpringBootApplication
@EnableScheduling
public class Application {
  public static void main(final String[] args) { SpringApplication.run(Application.class, args);}
}
```

In configuration there's a bean
```
@Component
public class MyBeanWithScheduledAnnotation {
  @Scheduled(fixedRateString = '#{fixedRate}')
  public void myJob() {
    ....
  }
}
```
If I use this bean with `@SpyBean` in my `SpringBootTest`, the scheduled job does not execute. The test code looks like this:
```
@RunWith(SpringRunner.class)
@SpringBootTest
public class Test

@SpyBean
MyBeanWithScheduledAnnotation bean
...
```
pom.xml contains only two dependencies `spring-boot-starter-web` and `spring-boot-starter-test`

**Comment by wilkinsona** [comment]
The underlying problem here is that `ScheduledAnnotationBeanPostProcessor` is called to post-process `MyBeanWithScheduledAnnotation` with the Mockito-created proxy. `AopUtils.getTargetClass(Object)` returns the proxy class and, as a result, the `@Scheduled`-annotated method isn't found.

It is intentional that the spy is created first (see #5837 and https://github.com/spring-projects/spring-boot/commit/cdfbf28099b30621a118ebf2ec4988364295b610) so I'm not sure what we can do here. Any ideas, @philwebb?

@dome313 As an aside, why do you want to spy on a scheduled bean? It seems like an unusual thing to be trying to do.

**Comment by philwebb** [comment]
I can't think of an easy way to fix this. I'm a little surprised that `ScheduledAnnotationBeanPostProcessor` doesn't pick up inherited `@Scheduled` methods.

**Comment by philwebb** [comment]
@jhoeller is not picking up inherited `@Scheduled` methods an intentional design decision? I imagine we've got something like this:

```java
public class MyBeanWithScheduledAnnotation {
    
    @Scheduled(fixedRateString = '#{fixedRate}')
    public void myJob() {
        ....
    }
}

public class MockitoCGLIBProxy extends MyBeanWithScheduledAnnotation {

    public void myJob() {
        // spy logic
        realBean.myJob();
        // spy logic
    }

}
```

**Comment by dome313** [comment]
@wilkinsona my test case scenario is following: there's a storage bean which can do manual and auto (with Scheduled annotation) save. In the test case I want to verify that the records are saved and if autoSave method was actually called or not, that's why I'm using Spy. Class is like:
```
@Component
public class StorageBean {
  public void manualSave() {
   ....
  }

  @Scheduled(fixedRateString = '#{fixedRate}')
  public void autoSave() {
    ....
  }
}
```
and then in test
```
verifyZeroInteractions(storageBean).autoSave()
// or
verify(storageBean).autoSave()
```
I know that are different approaches to test such functionality, this is just where I spotted the issue.

**Comment by philwebb** [comment]
Unfortunately I don't think there's an easy way for us to fix this. I'm going to close it for now and suggest that you test in a different way.
