### ISSUE TITLE
[spring-boot-dependencies] Provide e.g. spring-boot.version for Spring Cloud

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#8493]
The bom file `spring-cloud-starter-parent` is using `spring-boot-starter-parent` as ist parent. The latest release train of _Spring Cloud_ is `Dalston.M1` which uses version `1.5.0.RC1` of `spring-boot-starter-parent`: https://github.com/spring-cloud/spring-cloud-release/blob/vDalston.M1/spring-cloud-starter-parent/pom.xml#L8
When `spring-boot-starter-parent` has a property like `spring-boot.version` and all `<dependency>` declarations are using this property instead of a hard-coded version, then it would be possible to easily upgrade _Spring Boot_ inside _Spring Cloud_.

**Comment by spencergibb** [comment]
If you use spring-cloud-dependencies rather than the parent, you can upgrade the version of Spring Boot independently.

**Comment by philwebb** [comment]
As mentioned by @spencergibb, you should use the BOM. I think if you generate your project from start.spring.io then this is what you'll get.

**Comment by philwebb** [comment]
FWIW we've discussed using a property in the past but it causes some other issues.

**Comment by wilkinsona** [comment]
See #7048
