### ISSUE TITLE
Upgrade log4j2 from 2.7 to 2.8.1 (and perhaps use its BOM file)

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#8494]
log4j2 2.7 was released on Oct 2nd 2016. Version 2.8.1 was released on March 2nd 2017. It would be fine if you could upgrade log4j in `spring-boot-dependencies`.
Maybe log4j's `BOM` file could help for the dependency Management.

**Comment by philwebb** [comment]
We already use the BOM. See https://github.com/spring-projects/spring-boot/blob/3cdc81c351caafe164fc1bfefa0517073f175a97/spring-boot-dependencies/pom.xml#L1258-L1264.

We only do maintenance upgrades within a Boot release (so we won't jump to Log4J 2.8 in Boot 1.5). You can override the property yourself.
