### ISSUE TITLE
Add a .editorconfig to improve the formatting of the code on GitHub

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8497]
GitHub supports [EditorConfig](http://editorconfig.org) and looks for a `.editorconfig` file in the root of the repository. We can use it to, for example, configure the tab width to 4.

**Comment by wilkinsona** [comment]
It's branch-specific so I think we should add it to (at least) 1.4.x, 1.5.x, and master

**Comment by philwebb** [comment]
> The .editorconfig we've added[1] breaks thing for me in IJ, I had to disable its support. The most obvious issue so far is that json is not using tabs and is not indented using 4 chars. Do we want to use tabs in json? And 4 chars?

**Comment by philwebb** [comment]
Let's try tweaking it to just `.java` files.

**Comment by vpavic** [comment]
This broke continuation indents in IntelliJ for me. Using `continuation_indent_size` (which appears to be [a non-standard property](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#ideas-for-domain-specific-properties)) fixes the things:

```diff
diff --git a/.editorconfig b/.editorconfig
index 176815b35..26c1be094 100644
--- a/.editorconfig
+++ b/.editorconfig
@@ -3,7 +3,9 @@ root=true
 [*.java]
 indent_style = tab
 indent_size = 4
+continuation_indent_size = 8
 
 [*.xml]
 indent_style = tab
 indent_size = 4
+continuation_indent_size = 8
```

**Comment by snicoll** [comment]
Thanks @vpavic I've disabled the support in IJ on my side. Perhaps we should reconsider adding that file at all?

Ping team.

**Comment by philwebb** [comment]
I'd like to keep it if possible, lets try with those non-standard additions for a while. Long term the plan is still to try and unify the auto-formatting plugins.
