### ISSUE TITLE
Unable to set server.tomcat.max-http-post-size to -1 ("off")

### ISSUE THREAD

**Issue by stefan-huettemann** [spring-projects/spring-boot#8508]
Version: 1.5.1-Release

In `ServerProperties#customizeTomcat()` (see: spring-boot-autoconfigure-1.5.1.RELEASE-sources.jar!/org/springframework/boot/autoconfigure/web/ServerProperties.java:837) 

the statement

`if (this.maxHttpPostSize > 0) {
				customizeMaxHttpPostSize(factory, this.maxHttpPostSize);
			}`

prevents `maxHttpPostSize` to be set to a value `< 0`. 

But in tomcats sources of `Request#parseParts()` as well as in the documentation for `maxPostSize` [see https://tomcat.apache.org/tomcat-8.5-doc/config/http.html](https://tomcat.apache.org/tomcat-8.5-doc/config/http.html) it is stated that:

> The limit can be disabled by setting this attribute to a value less than zero.

IMHO this should be corrected in spring-boots auto-configuration.

Best Regards
-Stefan

**Comment by philwebb** [comment]
Thanks for pointing that out. I guess we can change that line to `if (this.maxHttpPostSize != 0)` and things should work. We also need to find a good way to test it.

**Comment by stefan-huettemann** [comment]
Based on commit cd316e7 (master 484c72c does not seem to compile :-o)  I could provide a patch file for `spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/ServerPropertiesTests.java` adding a test for setting the configuration to `server.tomcat.max-http-post-size=-1`

(An integration test would be to switch off the max post size by setting `server.tomcat.max-http-post-size=-1` and then `POST`a  request having a form parameter larger than 2MB.)

Let me know if you want to have the patch file (and how to provide it).

**Comment by snicoll** [comment]
Closing in favour of PR #8829
