### ISSUE TITLE
EnvironmentMvcEndpoint throws exception for unresolvable properties

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#8510]
The `EnvironmentMvcEndpoint` throws an exception for unresolvable properties instead of printing their _unresolved_ value.

Suppose the following `application.properties`:
```
my.foo = ${my.bar}
```

A call to the endpoint `/env` shows the `applicationConfig` entry with the properties unresolved:
```
"applicationConfig: [classpath:/application.properties]": {
   "my.foo": "${my.bar}"
}
```

However, a call to `/env/my.*` throws an exception complaining about `${my.bar}` being unresolvable.
This behaviour is annoying when the environment contains some properties that are not used in a given setup (think about `feature.enabled=false` with an incomplete configuration set for the feature _feature_).

Note: tested with SpringBoot `1.3.8.RELEASE` and `1.4.4.RELEASE`

**Comment by wilkinsona** [comment]
See also #8282

**Comment by philwebb** [comment]
Not sure if it's useful, but `RelaxedPropertyResolver.ignoringUnresolvableNestedPlaceholders` might help when it comes to fixing this.

**Comment by brenuart** [comment]
Yes it will - but will then be applicable to the entire Environment - which may not be desired.
I tried to modify the `EnvironmentMvcEndpoint` to make use of such property resolver instead of delegating to the Environment for property resolution. But I'm not sure it is the way to go...
