### ISSUE TITLE
Provide support for Kotlin KClass parameter in SpringApplication.run()

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#8511]
It would be nice to support natively Kotlin `KClass` parameter to allow writing `SpringApplication.run(FooApplication::class, *args)` in Spring Boot 2.0.

I could be implemented using classpath detection, would avoid `java.lang.IllegalArgumentException: Invalid source type class kotlin.reflect.jvm.internal.KClassImpl` error that Kotlin users get by default and would provide more idomatic Kotlin code than the current `SpringApplication.run(FooApplication::class.java, *args)`.

**Comment by philwebb** [comment]
Kotlin support would align nicely with Spring 5.0

**Comment by sdeleuze** [comment]
I have started to work on this.

**Comment by sdeleuze** [comment]
[Pull request](https://github.com/spring-projects/spring-boot/pull/10511) submitted.

**Comment by snicoll** [comment]
Closing in favour of PR #10511
