### ISSUE TITLE
HibernateJpaAutoConfiguration broken for Embedded Databases (1.5.2)

### ISSUE THREAD

**Issue by slackerjack1943** [spring-projects/spring-boot#8514]
Something in SpringBootStarter 1.5.2 has broken auto configuration for embedded databases.   

Setup a minimal project using spring-boot-starter-data-jpa and spring-boot-starter-web.  Use HSQLDB as the database.  Boot up the application.   

Using Spring Boot Starter 1.5.1, the application boots up fine and the database functions normally.

Update to `spring-boot-starter` 1.5.2, and the application fails to load with the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration required a bean of type 'javax.sql.DataSource' that could not be found.
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required class 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType'
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required class 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType'_
```

See attached zip for sample code.
[microservicesBoot.zip](https://github.com/spring-projects/spring-boot/files/822720/microservicesBoot.zip)

**Comment by philwebb** [comment]
I'm unable to get the attach sample application to fail in the way that you describe. It builds and appears to start fine for me. Could there be something environment specific causing problems? Does running the app with `--debug` show anything helpful?

**Comment by slackerjack1943** [comment]
Here's debug logs for 1.5.1 and 1.5.2.   I will take a look at them side by side too see if anything sticks out.

[debug_logs_1.5.1.txt](https://github.com/spring-projects/spring-boot/files/822886/debug_logs_1.5.1.txt)
[debug_logs_1.5.2.txt](https://github.com/spring-projects/spring-boot/files/822887/debug_logs_1.5.2.txt)

**Comment by slackerjack1943** [comment]
Don't really know how to read these tea leaves.  It looks like it does not EnableAutoConfigure at all, and subsequently does not even attempt a DataSourceAutoconfiguration step.

It's a fresh install of SpringToolSuite on Windows 7.  Will see if I can reproduce on Ubuntu.

![151_152_visual_diff_datasource](https://cloud.githubusercontent.com/assets/7049507/23637316/f7dc0592-02a8-11e7-801f-bac0fca5b759.png)
![151_152_visual_diff_enableautoconfig](https://cloud.githubusercontent.com/assets/7049507/23637319/fb751202-02a8-11e7-81c7-f8e880bc7eeb.png)

**Comment by philwebb** [comment]
This line is suspicious:

```
   DataSourceAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType' (OnClassCondition)
```

It's saying that `org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType` from `spring-jdbc` is either missing or the jar is corrupt.

Try `mvn dependency:purge-local-repository` just in case you've got a corrupted jar.

**Comment by slackerjack1943** [comment]
Boom.  That was the problem.

Thanks for your help!
