### ISSUE TITLE
Upgrade to HtmlUnit 2.25

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8515]
See [SPR-15319](https://jira.spring.io/browse/SPR-15319). It looks like we won't be able to apply this in the 1.5.x line unless Spring Framework introduces some reflection hackery.

**Comment by jhoeller** [comment]
We're tolerating HtmlUnit 2.25 in 4.3.x now. However, it might take a while for 4.3.8 to be released.

Note that we **require** HtmlUnit 2.25+ in master, so it'll be mandatory as 5.0 RC1.

**Comment by wilkinsona** [comment]
Selenium's HTMLUnit driver also needs to be upgraded to keep the versions in sync
