### ISSUE TITLE
spring.profiles.active in application.properties file not working

### ISSUE THREAD

**Issue by khannedy** [spring-projects/spring-boot#8519]
I don't know this is bug or not

I create simple web with start.spring.io

and add 

spring.profiles.active=production

in application.properties

when I run using mvn spring-boot:run the active profile is dev, not production

and when I compile to jar file, and after run, still active profile is dev, not production

I'm using spring boot 1.5.1.RELEASE version

**Comment by snicoll** [comment]
I don't think this is a bug. It works for on a sample app and we don't enable `dev`anywhere so you must have something locally that's overriding the value to dev. If you still need help, please consider going on stackoverflow or gitter.
