### ISSUE TITLE
Update SampleIntegrationTests to run tests against packaged CLI

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#852]
`SampleIntegrationTests` currently runs the samples using the classpath in the IDE or in Maven. This classpath is subtly different to the classpath that's available when using the packaged CLI. This can cause problems. For example template.groovy currently fails when run with the CLI, even though the test that runs it currently passes. Updating the tests to use `CommandLineInvoker` will run them against the packaged CLI and flush out any such classpath issues.

**Comment by tkopczynski** [comment]
@wilkinsona I just had a look at this and I'm able to prepare a PR which updates those tests that do not create a process that waits (like a web server for example).
As far as I can see, handling these additional cases would require changing `CommandLineInvoker` so that I would be able to kill this server, wait for starting up, etc.. I don't know if that's an option taking into account that this task is rather a low priority one.

**Comment by wilkinsona** [comment]
@tkopczynski Thanks very much

> As far as I can see, handling these additional cases would require changing CommandLineInvoker so that I would be able to kill this server, wait for starting up, etc.. I don't know if that's an option taking into account that this task is rather a low priority one.

That's definitely an option and makes sense to me. I think `Invocation` would need a `destroy()` method and something to await the application being started. You could implement the latter by looping and checking the output for `Started application in`, failing after a timeout period.

**Comment by tkopczynski** [comment]
@wilkinsona Great, I'll push my implementation into this direction.
Unfortunately, I need to give this some more thought. It's a bit more complex than it seemed at first glance. The problem I'm facing right now is that `CommandLineInvoker` basically calls `bash` process which ends up calling `java` as a child process. In case of server processes which don't exit by themselves, destroying the parent `bash` process doesn't kill the child one. So, the `java` process stays there forever. Currently, I don't see any clean and straightforward way of destroying this dangling process but I'll try to propose something.
