### ISSUE TITLE
Investigate behaviour and configuration of org.apache.catalina.mapper.Mapper

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8522]
A discussion on Gitter with @ezraroi and @regevbr identified a possible problem with `org.apache.catalina.mapper.Mapper`: it appears to look up a web resource for every request and then cache the result. That seems rather inefficient and unnecessary.

An initial investigation suggests that there might be a problem with how the `Mapper` is configured. It doesn't seem to be aware of the fact that the `DispatcherServlet` is mapped to `/` for example. This could be a side-effect of `MapperListener` not being aware of the servlet being added to the context for some reason.

**Comment by dsyer** [comment]
@paulc4 pointed out that the `request.servletPath` looks a bit odd in a Spring Boot app (it's what you would expect to be in the `pathInfo` since the servlet is mapped to "/*").

**Comment by wilkinsona** [comment]
It looks to me like the `Mapper` is configured correctly (I was wrong above). The dispatcher servlet mapped to `/` is considered to be the default servlet which means it goes looking for resources to see if it needs to redirect to a folder:

```java
// Rule 7 -- Default servlet
        if (mappingData.wrapper == null && !checkJspWelcomeFiles) {
            if (contextVersion.defaultWrapper != null) {
                mappingData.wrapper = contextVersion.defaultWrapper.object;
                mappingData.requestPath.setChars
                    (path.getBuffer(), path.getStart(), path.getLength());
                mappingData.wrapperPath.setChars
                    (path.getBuffer(), path.getStart(), path.getLength());
                mappingData.matchType = MappingMatch.DEFAULT;
            }
            // Redirection to a folder
            char[] buf = path.getBuffer();
            if (contextVersion.resources != null && buf[pathEnd -1 ] != '/') {
                String pathStr = path.toString();
                WebResource file;
                // Handle context root
                if (pathStr.length() == 0) {
                    file = contextVersion.resources.getResource("/");
                } else {
                    file = contextVersion.resources.getResource(pathStr);
                }
                if (file != null && file.isDirectory() &&
                        contextVersion.object.getMapperDirectoryRedirectEnabled()) {
                    // Note: this mutates the path: do not do any processing
                    // after this (since we set the redirectPath, there
                    // shouldn't be any)
                    path.setOffset(pathOffset);
                    path.append('/');
                    mappingData.redirectPath.setChars
                        (path.getBuffer(), path.getStart(), path.getLength());
                } else {
                    mappingData.requestPath.setString(pathStr);
                    mappingData.wrapperPath.setString(pathStr);
                }
            }
        }
```

The resource look up is avoided if the dispatcher servlet's mapped to `/*` but then other things don't behave as intended.

**Comment by psingarakannan** [comment]
I'm facing a similar issue. Every request lookup a resource and cache the result. That lookup is taking 50% of the total time. Is there a way to get rid of this issue?
Why do we need to lookup for every request?

**Comment by wilkinsona** [comment]
@psingarakannan It is Tomcat looking up the resource and it's out of Spring Boot's control, unfortunately.

Looking more closely at the code in my [comment above](
https://github.com/spring-projects/spring-boot/issues/8522#issuecomment-287423267), I think it may be possible to make an optimisation in Tomcat. 

If `contextVersion.object.getMapperDirectoryRedirectEnabled()` returns `false` is doesn't matter what `contextVersion.resources.getResource` returned. I think the code could be rewritten to check the `getMapperDirectoryRedirectEnabled()` returns `true` before it calls `getResource()`. Directory redirect is, I believe, disabled by default so it would avoid the resource look up when it looks like it isn't needed.

@markt-asf Does that make sense? If you think it does and that a change in Tomcat could be made, I'll open an issue.

**Comment by markt-asf** [comment]
@wilkinsona That makes sense to me. Please go ahead and open an issue.

**Comment by wilkinsona** [comment]
Thanks, Mark. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=62968.

I'm going to close this one as I don't think there's anything we can do in Spring Boot. We'll pick up a version of Tomcat that contains the optimisation in due course.
