### ISSUE TITLE
Restructure embedded web server packages

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8532]

**Comment by philwebb** [comment]
See also #8303

**Comment by garyrussell** [comment]
Is there a doco issue to reflect this change (didn't see one from a quick search). For example [here](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#howto-discover-the-http-port-at-runtime) references `EmbeddedServletContainerInitializedEvent` when it's now `ServletWebServerInitializedEvent`.

**Comment by wilkinsona** [comment]
Thanks for spotting this, @garyrussell. There isn't a separate documentation issue as far as I know so I've reopened this one.

**Comment by philwebb** [comment]
Thanks. I forgot about the documentation.

**Comment by snicoll** [comment]
@philwebb I can see a bunch of existing classes that were moved got their `@since` tag changed to `2.0.0`. Do you really meant to do that? I understand it is a new location but it makes extermely difficult for someone to know when a feature was introduced. For instance, we advertize `@LocalServerPort` is a 2.0 feature now. It isn't...

**Comment by philwebb** [comment]
@snicoll We should discuss this on the next call I guess. It was intentional, my thinking being that if someone is referring to a specific class in a third party library they should know when it was introduced. The concept of `@LocalServerPort` may have existed before 2.0 but the `org.springframework.boot.web.server.LocalServerPort` class did not.

**Comment by wilkinsona** [comment]
FWIW, the updated `@since` tags make sense to me.

**Comment by philwebb** [comment]
We discussed on the call and decided they make sense. We just need to be careful going forward that we apply them consistently.

**Comment by michael-simons** [comment]
@bclozel I have a fixed version of the docs I could provide as a PR. You may want to have a quick look before working on that.
