### ISSUE TITLE
Devtools does not wait for all changes to complete before restarting the app

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#8542]
Something @snicoll and I noticed while rehearsing a demo.

Here's how to reproduce that issue:

1. Run a Boot application with devtools and the `-noverify` JVM flag (more on that later) in your favorite IDE
2. Make several changes, that imply several classes scheduled for rebuilding; in our demo, we were doing that by checking out a different commit with many new classes
3. Hit the "Rebuild" button
4. The application should fail in an unexpected manner, for example complaining about a missing bean whereas it's properly defined in your application, and was even before the current change being applied

This description is rather vague, but digging into this seems to point to the following:
1. The IDE is busy indexing things and rebuilding the app
2. As soon as the first change on the classpath is noticed, devtools kicks in and stops/fast-restarts the application
3. Because the `-noverify` flag is enabled, the application starts *really* fast, before the IDE has a chance to complete the actual build
4. The actual error symptom is not yet clear, and we're not sure if it's an IDE issue, a devtools issue, or both

Disabling the `-noverify` flag (making the restart slower) or making smaller changes (making the build faster) seem to good workarounds, and applying big chunks of changes is probably not the typical use case.

But it looks like we could improve the devtools behavior by making sure that all changes are properly applied before creating the new classloader and restarting the application.
After the first detected change, we could wait for a fixed amount of time and re-check for newer changes - if we detect newer changes, this indicates that the build is still going and that we shouldn't trigger the restart right away.

This is a hard one to reproduce, but @snicoll and I can assist with our [demo project and some guidance](https://github.com/snicoll-demos/cfp-example) if necessary.

**Comment by philwebb** [comment]
There are a couple of constants defined in `FileSystemWatcher` that might need tweaking. Specifically `DEFAULT_QUIET_PERIOD` is the amount of time the watcher needs without seeing changes before triggering the reload.

**Comment by bclozel** [comment]
Never got to reproduce this in a consistent manner; I'm closing this for now.
