### ISSUE TITLE
Add support for `TestRestTemplate` and Webflux

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8543]
I wanted to migrate an app from Spring 4 MVC to SPpring 5 MVC and then Webflux, and use the same tests as much as possible. I found that `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)` and `@LocalServerPort` worked fine, but I had to configure my own `TestRestTemplate`, so it would be nice to have that autowired and get rid of the `@LocalServerPort`. I know I can use `WebTestClient` but `TestRestTemplate` has everything I need and it works with older versions too.

**Comment by dsyer** [comment]
It actually works already (that's a feature of `@SpringBootTest`).

**Comment by snicoll** [comment]
Actually we also need to test that.

**Comment by snicoll** [comment]
@dsyer I am confused about your last comment. Why do you want us to update the javadoc of `@WebFluxTest` for something that `@SpringBootTest` provides. This isn't the same thing at all.

**Comment by dsyer** [comment]
I didn't know that a `TestRestTemplate` was already available. It seems like a "web" feature, so I was trying to find out about it by reading up on `@WebFluxTest` and `@WebMvcTest`. Maybe the javadocs for those could just briefly remind the reader that there are web features already in `@SpringBootTest`?

**Comment by snicoll** [comment]
I don't think so. Both those annotations are meant to mock the server so if you're looking there for a `RestTemplate` that's the issue I guess. The javadoc of `@SpringBootTest` states:

> Registers a TestRestTemplate bean for use in web tests that are using a fully running web server.

**Comment by snicoll** [comment]
We need to test this (see comment above)
