### ISSUE TITLE
Manage Netty dependencies

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#8553]
Now that reactor/reactor-netty#28 is resolved, we can reconsider the number of managed dependencies for Netty and reduce their number.

Since many projects might depend on `netty-all`, we might want to keep that dependency as managed even if we don't depend on it directly.

Also, those changes should be shortly reflected in the BOM, see reactor/reactor#640

**Comment by wilkinsona** [comment]
Sorry, not sure how I missed this one when it was opened.

Generally speaking, when we only use parts of a library, having dependency management for other parts of it is a good thing. With partial dependency management, there's a risk that a user will end up with a mixture of versions on their application's class path. I would actually be in favour of going in the opposite direction to https://github.com/spring-projects/spring-boot/commit/117310924ee45125ed9dec3a71b73716b374c553 and adding dependency management for all of the Netty modules that are released together.

**Comment by bclozel** [comment]
I just saw that Netty is now releasing a `netty-bom` artifact - but I don't know if it's the right choice here as it has `netty-parent` as parent, which itself has `org.sonatype.oss:oss-parent` as parent.

Should we list all dependencies manually or try to leverage that BOM?

**Comment by snicoll** [comment]
Nope, we can't use it. The `parent` has [a `dependencyManagement` section](https://github.com/netty/netty/blob/4.1/pom.xml#L299) for the "internal stuff" which completely defeats the purpose of having a bom. I'll report that to them.

**Comment by bclozel** [comment]
Thanks @snicoll , FYI here's the [original issue](https://github.com/netty/netty/issues/5994).

**Comment by bclozel** [comment]
The Netty BOM looks good now, so I'll list all dependencies first and we'll use that BOM when 4.1.10.Final is out, in #9021

**Comment by johnou** [comment]
@bclozel 4.1.10.Final is out.

**Comment by snicoll** [comment]
@johnou this issue is closed and so is #9050
