### ISSUE TITLE
Version bump of Kotlin to 1.1

### ISSUE THREAD

**Issue by spinfooser** [spring-projects/spring-boot#8555]
Backwards compatibility between Kotlin 1.0.X and 1.1 means that you cannot run both in the same application (including JARs that are pulled in). 

Since Spring specifies the use of Kotlin 1.0.6, it downloads that instead of the latest version. This clashes when you specify your project as 1.1 compatible and produces the following error message when gradle builds:

```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
   /Users/<username>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.0/96a07041a11a09cf578892932d7511e1e11e3b6c/kotlin-stdlib-1.1.0.jar (version 1.1)
   /Users/<username>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.6/3d499d3b7768f88c4796e5a1e357933e11a8936d/kotlin-reflect-1.0.6.jar (version 1.0)
```

I don't anticipate any issues with making this change. 

See here for more info: http://kotlinlang.org/docs/reference/compatibility.html

**Comment by wilkinsona** [comment]
Spring Boot doesn't have any dependency management for Kotlin so there's nothing for us to bump. The IO Platform does have such dependency management and there's already an issue open for it to upgrade to 1.1: https://github.com/spring-io/platform/issues/543.
