### ISSUE TITLE
Audit events MVC endpoint returns all events by default

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#8560]
If audit events MVC endpoint is invoked without any request parameters it will return all events stored in an underlying `AuditEventRepository`. By default with `InMemoryAuditEventRepository` this is up to 4000 events however if one uses custom `AuditEventRepository` this can result in a huge (and not particularly useful) payload being returned.

IMO `after` request parameter should be required (as it was in originally proposed in #6579 but changed in a post merge polish commit) so if one really wants to retrieve all the events it should be done by providing an adequate value for `after` request parameter.

However if this indeed is the desired behavior then the Actuator docs should be updated to clarify the endpoint can be invoked without any parameters (docs are currently describing endpoint as originally proposed in #6579).

**Comment by snicoll** [comment]
Closing in favour of PR #9002
