### ISSUE TITLE
New validation of ResourceServerProperties breaks OAuth2Sso Application with multiple providers (1.5.2)

### ISSUE THREAD

**Issue by julmuell** [spring-projects/spring-boot#8565]
After migrating to 1.5.2 i've encountered a issue with my OAuth2 setup. The bootstraping of the application fails because the validation of the ResourceServerProperties fails. In my setup i have no `security.oauth2.client` and no `security.oauth2.resource` => OAuth2AutoConfiguration -(defines)-> ResourceServerProperties without any corresponding .yml-properties. Therefore the validation fails with `Missing tokenInfoUri and userInfoUri and there is no JWT verifier key`. In the past this setup worked because the validation has first checked if there is any value for `clientId` (which is not the case).

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerProperties@325bb9a6 failed:

    Property: security.oauth2.resource.tokenInfoUri
    Value: null
    Reason: Missing tokenInfoUri and userInfoUri and there is no JWT verifier key
```

***Example application***

https://github.com/julmuell/tut-spring-boot-oauth2/tree/master/github

***Workaround***

```
security:
  oauth2:
    resource:
      userInfoUri: BUGFIX
```

**Comment by mbhave** [comment]
This looks like a bug although I wonder if we should not create `ResourceServerProperties` in the first place if there are no properties under `security.oauth2`, instead changing the logic in the validator.
