### ISSUE TITLE
50x errors should show the root cause in the top header.

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#857]
Currently, we need to search through a long backtrace to determine what caused the exception.  The reason should be included in the top level message.
### Above the fold

![screen shot 2014-05-13 at 12 25 06 pm](https://cloud.githubusercontent.com/assets/87432/2960293/83618dc6-dabb-11e3-96cc-ab3304ea3037.png)
### Below the fold

![screen shot 2014-05-13 at 12 25 18 pm](https://cloud.githubusercontent.com/assets/87432/2960266/3f01fa58-dabb-11e3-96e7-bf58fa1dc901.png)

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
