### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by paulc4** [spring-projects/spring-boot#8574]
*Section: 24. Externalized Configuration*

3. @SpringBootTest#properties annotation attribute on your tests.

The hyperlink for `@SpringBootTest#properties`  is broken - this link does not exist:

http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/api/spring-boot-test/src/main/java/org/springframework/boot/test/context/SpringBootTest.html

**Comment by snicoll** [comment]
See #4901
