### ISSUE TITLE
Unexpected # in PDF documentation

### ISSUE THREAD

**Issue by paulc4** [spring-projects/spring-boot#8575]
**Section: 20.2 Automatic restart**

_Triggering a restart_

As DevTools monitors classpath resources, the only way to trigger a restart is to update the classpath. The way in which you cause the classpath to be updated depends on the IDE that you are using. In Eclipse, saving a modified file will cause the classpath to be updated and trigger a restart. In IntelliJ IDEA, building the project (Build # Make Project) will have the same effect.

----

Looking in `using-spring-boot.adoc`, the # was originally `->`

I've seen the same issue when creating our training documentation --  Asciidoc/Docbook parsers convert characters they doesn't recognize to #.

If you find the solution, please let me know! :)

**Comment by snicoll** [comment]
It would have helped to mention that this issue only happens with the PDF version.

**Comment by snicoll** [comment]
@philwebb given that issue is PDF only, I wonder if we shouldn't duplicate this one in favour of #7447

**Comment by philwebb** [comment]
We'll see how easy it is to fix. Since the 1.5.x documentation will be around for a while I'd like to do something.

**Comment by wilkinsona** [comment]
The underlying problem is that Courier doesn't have a glyph for `→`. This warning is logged during generation of the PDF:

```
WARNING: Glyph "→" (0x2192, arrowright) not available in font "Courier".
```
