### ISSUE TITLE
Parse Platform equivalent for Spring Boot required..

### ISSUE THREAD

**Issue by ahmeddini** [spring-projects/spring-boot#8577]
Hello my fellow developers..

My name is Ahmed Dini from London, UK, and I have been a Java Technologies developer for  over 10 years.  I believe many of you agree with me that the best developer framework we have been introduced recently is by far Spring Boot. You would especially appreciate more if you have worked with Spring Framework before Spring  Boot has been introduced.  

Recently, my team has been assigned to develop a project that required a  NodeJS Backend with Document Database support  (insisted by the customer) that should serve clients of different platforms (Android, iOS, Windows, Web Application).  So the idea was to design the backend as RESTFul API and as well as being client agnostic. Furthermore, an admin webapp to dynamically change system configurations was part of the requirement.  

So my team started with our routine R&D for the new project. As all the member of the team were Java developers and not NodeJS developers, we had many assumptions about NodeJS such as Single Threaded vs Multi-threaded. But, after an extensive research, our Multi-threading fear has been over-come.  So, we started the search with  GitHub's NodeJS existing projects hoping we could find something similar to Spring Boot for NodeJS, we found loads of Frameworks and modules that are similar, but to our surprise, we found a framework (technically not a Framework, but a multi-purpose platform (with pre-configured backend connection with MongoDB, and Client SDKs for all common platforms like Android, iOS, Windows, Web JavaScript).  Basically, to our understanding this platform is equivalent, A backend webapp with Spring Boot connected to MongoDB, with all the Spring Boot Sample projects converted into one common backend that support all the common functionalities and APIs that apps support like, getConfigurations, register user, login, App API key verification, other default security, photo upload, and many more. And a common client SDK for all Android app.

The Platform for NodeJS that I am referring to is  [Parse Platform](https://parseplatform.github.io/).  
This Platform has recently been opensourced by Facebook, previously was a hosted platform. 

My team has loved the platform, even thought it hasn't picked up very well as there is not large developer community.

The reason why I decided to share this with my fellow Spring Boot lovers, is to learn from this platform and develop something similar to Parse Server.  Individually, we have used Spring Boot and developed features like Login, Session validation, configuration dashboards, so if we get together and turn the Spring Boot sample applications as one massive backend and supporting SDKs and a admin configurations backend dashboard, we can make developer lives easy and make application pretty quick.  Spring Boot has already done most of the work for us, we just need to hooks its sample SDKs and implement all common APIs and backend functionalities. 

Parse Platform assisted us to  make  a feature full app with in a week, something that would have not been not possible if we had to mix and match SDK without limited NodeJS knowledge, write backend APIs manually!  We didn't even have to deal with MongoDB collection design, directly from Android and iOS we had been able to Create the POJOs that represent database Collections that would be saved to MongoDB and use SDK functions to save them, read them.

If Anyone would like to support my team, we can start gitHub Spring Boot based platform similar to the Facebook's NodeJS Parse Platform.

Please comment, recommend ways we can achieve this and show your interest of this initiative.

Regards, 
Ahmed Dini

**Comment by wilkinsona** [comment]
Sorry, but Spring Boot's GitHub issues isn't the right place to have this discussion.
