### ISSUE TITLE
spring-boot-features.adoc has a non-working example

### ISSUE THREAD

**Issue by lexandro** [spring-projects/spring-boot#8580]
In the spring-boot-features.adoc documentation the Single Sign On section has a demo code that couldn't compile, because it refers to a non-existing method:
```java	
@Override
public void init(WebSecurity web) {
	web.ignore("/");
}
```

The the `WebSecurity.ignore(String ...)` method is not existing.

I replaced in my code with 

```java	
@Override
public void init(WebSecurity web) {
	web.ignoring().antMatchers("/");
}
```

and it worked. Pls let me know if I'm wrong or should I submit a PR to fix it.

**Comment by wilkinsona** [comment]
@lexandro You are correct and a pull request would be most welcome. We've slowly been moving to including actual, compiled source files to avoid this sort of problem. You can see an example of that in [this commit](https://github.com/spring-projects/spring-boot/commit/041da3b6cd82d2e0d02734aa4e847e024c2636aa).

**Comment by snicoll** [comment]
Closing in favour of PR #8594
