### ISSUE TITLE
spring-security-oauth2 integration not working in 1.5.2

### ISSUE THREAD

**Issue by YouYII** [spring-projects/spring-boot#8581]
https://github.com/YouYII/spring-boot-oauth2-server-demo

If use spring-boot 1.5.2
>$ curl http://localhost:8080/private -G -d access_token=f6ebde29-be2e-45db-9aeb-1013bf8e5d
> {"timestamp":1489332300530,"status":403,"error":"Forbidden","message":"Access Denied","path":"/private"}

just change spring-boot version 1.5.2 to 1.4.3

> {"error":"invalid_token","error_description":"Invalid access token: f6ebde29-be2e-45db-9aeb-1013bf8e5d"}

**Comment by wilkinsona** [comment]
As [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter) you need to configure the order of the resource filter.
