### ISSUE TITLE
Consider splitting Redis connection factory and `RedisTemplate` related configs

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#8583]
Currently the entire Redis auto-configuration is conditional on presence of Jedis. If one uses Lettuce and provides `LettuceConnectionFactory` bean it would be nice if Boot would configure `RedisTemplate` and `StringRedisTemplate` just like it does with Jedis.

I'm aware of Lettuce first-class support proposed in #5311 is scheduled for Boot 2.0 however the situation described above would benefit Boot 1.x users as well.

Thoughts? I understand this is not a trivial change however if you'd consider it acceptable for 1.5 I'd put together a PR.

**Comment by philwebb** [comment]
My gut instinct is that this would be quite a large change to sneak into `1.5.x`. I'd be interested in what others think, but my initial feeling is that we should leave `1.5.x` as it is and instead focus on splitting things up for `2.0.0`.

**Comment by snicoll** [comment]
I agree. We do have plans to support Lettuce so that would be a change we'll have to make anyway.

**Comment by philwebb** [comment]
Having discussed this a bit we feel like the change will be too large for the maintenance release. We'll take this on in 2.0 as part of #5311.

**Comment by vpavic** [comment]
This was resolved via #5311. I guess that means the milestone should be adjusted to `2.0.0.M1`.
