### ISSUE TITLE
Clarify the effect that management.context-path has on endpoint paths

### ISSUE THREAD

**Issue by jzampieron** [spring-projects/spring-boot#8586]
In Spring Boot 1.5.2, there is support for remapping one of the actuator health end points.

As the documentation states: 

> For example, to change the location of the /health endpoint to /ping/me you can set endpoints.health.path=/ping/me.

This is an imprecise statement. What that actually does is change the end point path mapping relative to `management.context-path`. 

i.e., if `management.context-path=/foo` it would change `/foo/health` to `/foo/ping/me`, which is not obvious and not clear from the documentation.

Suggestion:

What it should do is honor a leading `/` as meaning an absolute path (relative to the base of the servlet context). 

i.e. if `management.context-path=/foo` and `endpoints.health.path=/ping/me` then the mapping goes to `/ping/me`. Similarly for `endpoints.health.path=ping/me` would map to `/foo/ping/me`.

**Comment by wilkinsona** [comment]
> This is an imprecise statement. What that actually does is change the end point path mapping relative to management.context-path.

The introduction to the section that you've quoted says that "sometimes it is useful to group all management endpoints under a single path" when describing the purpose of the context path property. We can update the wording in the later paragraph to reinforce that it's relative to the configured context path.

> What it should do is honor a leading / as meaning an absolute path (relative to the base of the servlet context).

All of the endpoints are handled by a handler mapping (EndpointHandlerMapping) that's configured with the management context path as its prefix. This means that, unfortunately, your suggestion isn't possible without some fairly significant changes. I don't think the benefit outweighs the additional complexity that it would introduce so we'll clarify the documentation.
