### ISSUE TITLE
Embedded servlet container integration tests are failing on Windows

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8590]

**Comment by philwebb** [comment]
703d403f7d5cdca9008d43441f0a10df37a29304 has fixed this and [the build is green again](https://build.spring.io/browse/BOOT-WIN-857).

**Comment by philwebb** [comment]
My mistake, it was commit 2ddcf0e8315d91497051f33146b3f58f1cf2ee8b.

**Comment by wilkinsona** [comment]
Oops. Thanks for linking things together.
