### ISSUE TITLE
Properties with null values appear in the report from the /configprops endpoint

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8604]
I'm not sure if this is intentional, but [this line of code](https://github.com/spring-projects/spring-boot/blob/v1.5.2.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/ConfigurationPropertiesReportEndpoint.java#L174) makes me think it isn't:

```java
mapper.configure(SerializationFeature.WRITE_NULL_MAP_VALUES, false);
```

The tests don't tell me anything as they all pass with or without this line. @dsyer can you recall what your intent was when you added this?

This came up as `SerializationFeature.WRITE_NULL_MAP_VALUES` is deprecated in Jackson 2.9. If the intent was to omit properties with `null` values then we can use this instead:

```java
mapper.setSerializationInclusion(Include.NON_NULL);
```

If the intent was something else, then we need to figure out what to do as part of upgrading to Jackson 2.9.

**Comment by philwebb** [comment]
Looks like that was introduced in commit 6ad626de491fe36df67d74ef17baf63d4125e10a referencing issues #1921 and #1746. Not that that helps much!
