### ISSUE TITLE
Add @DataCouchbaseTest support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8606]
For completeness it would be nice if we had a complete set of test annotations for Spring Data. See #8544

**Comment by alexsderkach** [comment]
The are 2 ways to achieve this:
- CouchbaseMock (Doesn't support N1QL)
- Launch Couchbase TestContainers (Requires Docker Machine & pulls testcontainers dependency)

Approve which way to go (I prefer first one), and I will implement this task.

**Comment by philwebb** [comment]
I don't have detailed knowledge of Couchbase but the first option certainly seems like it would have fewer moving parts.

**Comment by wilkinsona** [comment]
I don't either, but I too prefer the first option as requiring Docker Machine feels a bit too much to me.

**Comment by snicoll** [comment]
That seems incompatible with the concept of slicing/unit test as well. So +1 for the first option.

**Comment by alexsderkach** [comment]
Blocked, until https://github.com/spring-projects/spring-data-couchbase/pull/153 is merged.

**Comment by mp911de** [comment]
spring-projects/spring-data-couchbase#153 is fixed now.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#11146).
