### ISSUE TITLE
Add @DataCassandraTest support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8607]
For completeness it would be nice if we had a complete set of test annotations for Spring Data. See #8544

**Comment by Razi007** [comment]
I want to work on it.I am going through code base to understand for now.Also can i get some advice or mentorship.Or is there any irc channel or mailing list where i can collaborate with spring-boot community.

**Comment by snicoll** [comment]
@Razi007 we have [a gitter channel](https://gitter.im/spring-projects/spring-boot).

**Comment by Razi007** [comment]
can i pick this task as beginner in spring-boot code base

**Comment by snicoll** [comment]
@Razi007 please use the Gitter channel if you have questions.

**Comment by izeye** [comment]
Based on https://github.com/spring-projects/spring-boot/pull/13033#issuecomment-400430466 , it looks this can be closed.

**Comment by wilkinsona** [comment]
Thanks, @izeye. I'll label this one as blocked for now. We'd still like to add support, but cannot do so without a project for Cassandra that's similar to [Embedded Mongo](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo).

**Comment by wilkinsona** [comment]
On second thoughts (prompted by @snicoll), let's close this one as an Embedded Mongo-like project becoming sufficiently established for us to depend upon it is out of our control. We can re-open this issue should it happen.

**Comment by vpavic** [comment]
Couldn't you simply use Testcontainers here? IMO that's a good for _embedding_ pretty much anything that's available as a Docker container.
