### ISSUE TITLE
Review ServerProperties and document keys that only work in certain environments

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8624]
Currently `ServerProperties` contains quite a mix of things. We'll need to refactor it to get cleaner reactive/servlet concerns.

**Comment by philwebb** [comment]
We can probably also unify some of `DefaultServletWebServerFactoryCustomizer` and `DefaultReactiveWebServerFactoryCustomizer`

**Comment by wilkinsona** [comment]
The current arrangement requires us to allow `org.springframework.boot.web.servlet.server` to be imported into `org.springframework.boot.autoconfigure.web` as `org.springframework.boot.web.servlet.server.Jsp` is used by `ServerProperties`.

As part of fixing this we should update Checkstyle's import controls to lock that back down.

**Comment by snicoll** [comment]
IMO this one is related to #4818 - We need `server` to clearly define the scope of things. I am not a big fan of `common`. We had a similar problem with the Kafka support and ended up duplicating keys with a base class (perhaps that's what you meant?)

The first step would list exactly which properties are related to what. Duplicating `tomcat`, `jetty` and `undertow` is probably going to be quite of a problem if there are reactive/servlet specific deps in there.

Regardless, I don't really see that happening in 2.0 anymore. Perhaps moving that to 2.1 with a way to transparently handle the old location would be an option?

**Comment by snicoll** [comment]
We've review this issue and we've explored a few options that would guide users towards which environment is supported for a given key. Unfortunately, none of those options are satisfactory. It really feels like #4818 and we believe documenting the keys that are limited to certain environments is a more pragmatic approach to this issue.

This can be a simple extension of the key description. Perhaps doing this work will give us improvement ideas for the metadata format that we can implement in a future feature release.

**Comment by bclozel** [comment]
Looking at the current properties arrangement, it seems that:

* `server.display-name` is only applied to Servlet environments, and should move to the `server.servlet` namespace
* `server.tomcat.redirect-context-root`, `server.tomcat.use-relative-redirects` and `server.tomcat.additional-tld-skip-patterns` are only applied to Servlet environments; I don't think we really need to move those under a `server.tomcat.servlet` namespace...
