### ISSUE TITLE
Support error conventions with WebFlux

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8625]
We'll need to review `ErrorProperties` and look at the `ErrorController` classes to see if we can provide WebFlux alternatives. Ideally the `/static/404.html` conventions should just work.

**Comment by naivefun** [comment]
@philwebb How can I return specific http status on error?

Previously we have @ResponseStatus with runtime exception, but now either reactor exception or throw other annotated exception from operations only trigger 500 without body response on controller level. Any tricks not documented? Thanks.

**Comment by snicoll** [comment]
@naivefun please use Gitter or Stackoverflow for questions.

**Comment by bclozel** [comment]
See [SPR-15812|https://jira.spring.io/browse/SPR-15812].
