### ISSUE TITLE
Add reactive HttpEncodingAutoConfiguration support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8627]
`HttpEncodingAutoConfiguration` is currently servlet specific. We probably want a webflux version.

**Comment by philwebb** [comment]
This might not be an issue since webflux is utf-8 by default and there is no filter.

**Comment by philwebb** [comment]
@bclozel any insight on this? can we close it?

**Comment by surol** [comment]
What about static resources encoding? E.g. `text/html` files has no charset set.

**Comment by bclozel** [comment]
@philwebb Indeed WebFlux is using UTF-8 by default and so is HTML5 for both content and [form submissions](https://www.w3.org/TR/html5/forms.html#selecting-a-form-submission-encoding).

I don't see any reason to add anything there.

@surol I don't understand how this is linked to this particular issue. You can declare the encoding of your HTML document inside the document itself.
