### ISSUE TITLE
Actuator 1.5.2 documentation not clear about how management.security.enabled plays together with Spring Security

### ISSUE THREAD

**Issue by adammichalik** [spring-projects/spring-boot#8646]
The Spring Boot 1.5 release notes ([actuator security](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#actuator-security) and [ignored paths](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#ignored-paths-and-enablewebsecurity)) give a pretty good explanation on how `management.security.enabled` works in a project with and without Spring Security. However, this is not that clear in [the documentation](http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/html/production-ready-monitoring.html). There are a few bugs submitted since Spring Boot 1.5 release (eg. #8255, #8210, #8070) where people (myself included) misunderstood how `management.security.enabled` plays together with Spring Security. It would help to have a clear section in the documentation incorporating the information from the release notes in one place. These fragments seem to me most lacking in the documentation:

> If your [...] application has custom security configuration and you wish to have open access to your sensitive endpoints, you will need to explicitly configure that in your security configuration. If [your application] doesn’t have dependency on Spring Security and you wish to retain open access to your sensitive endpoints you’ll need to set `management.security.enabled` to false.

> using `@EnableWebSecurity` will switch off all auto-configuration of web security thereby allowing you to take complete control.

Alternatively, a table similar to this would help, too (hopefully I got it right):

| `management.security.enabled` | Spring Security | Actuator endpoints secured |
|--|--|--|
| true | not present | yes | 
| false | not present | no |
| true | present, no custom configuration / no `@EnableWebSecurity` | yes |
| false | present, no custom configuration/ no `@EnableWebSecurity` | no |
| * | present, custom configuration / `@EnableWebSecurity` | depends on your custom configuration |

**Comment by drndos** [comment]
There is also an issue where if you use annotation `@EnableWebSecurity`, your configuration in application.yml/properties "security.ignored=/health" gets actually ignored and health endpoints requires authentification unless you specify exclude in Java config file. (I have management.security.enabled=false)  When I remove annotation `@EnableWebSecurity` everything works fine. Web security works as it should, also excludes in my application.yml work just fine.

**Comment by edgarvonk** [comment]
> health endpoints requires authentification unless you specify exclude in Java config file

Hi guys, I know this issue is closed but we would be greatly helped if maybe some could explain to us how exactly we could do this in our custom WebSecurityConfigurerAdapter. Our situation is that we have a custom configuration with @EnableWebSecurity but do not want to have any security on our management endpoints (so in effect would like to have management.security.enabled=false).

**Comment by snicoll** [comment]
@edgarvonk we don't use the tracker to deal with questions. Please join us on Gitter or ask on stackoverflow.
