### ISSUE TITLE
r :java.lang.NoClassDefFoundError: org/springframework/data/redis/serializer/RedisSerializer

### ISSUE THREAD

**Issue by fengjinli** [spring-projects/spring-boot#8652]
Bug report

when i run this project[spring-boot-sample-session-redis],but the console print this error :java.lang.NoClassDefFoundError: org/springframework/data/redis/serializer/RedisSerializer

**Comment by wilkinsona** [comment]
Sounds like you have a corrupted download of the `spring-data-redis` jar. Try clearing out your Maven cache and building again.
