### ISSUE TITLE
Add elapsed time to the Trace Actuator output

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#8654]
Currently, the trace actuator output does not include the elapsed time taken to service the request.  This information is useful when rendering the response to users for diagnostics. This data should be added to the trace response.

**Comment by philwebb** [comment]
Look at the Apache HTTPD Log line to see what it calls it.

**Comment by philwebb** [comment]
This is a request from the Apps Manager team.

**Comment by nebhale** [comment]
[Common Log Format](https://en.wikipedia.org/wiki/Common_Log_Format) and I guess it doesn't appear to have an elapsed time in it.  That frees you decide what to call it.

**Comment by wilkinsona** [comment]
I suggest `time-taken`: https://www.w3.org/TR/WD-logfile.html

**Comment by wilkinsona** [comment]
`%D`: https://httpd.apache.org/docs/trunk/mod/mod_log_config.html

**Comment by nebhale** [comment]
Seems to be common and understandable.  Fine by me.

**Comment by mbhave** [comment]
@wilkinsona how about `timeTaken` to make it consistent with all the other ones that are camel-case such as `authType`, `remoteAddress` etc?

**Comment by wilkinsona** [comment]
@madhura Being consistent sounds good to me

**Comment by shakuzen** [comment]
The unit of measure for `timeTaken` is not apparent (from the name) nor documented (in the JavaDoc or Spring Boot documentation).
The common log format uses seconds, while the Apache module uses microseconds, but I can see from the implementation that this `timeTaken` is milliseconds.

I think it would be good to either use a name that makes the units apparent, or if not, this info should be easy to find. WDYT?

**Comment by mbhave** [comment]
@shakuzen that's a fair point. We can add it to the documentation.
