### ISSUE TITLE
security.require_ssl=true has no effect with when using EnableResourceServer annotation

### ISSUE THREAD

**Issue by thomasturrell** [spring-projects/spring-boot#8655]
**Bug report**

In Spring Boot 1.5.2.RELEASE if the EnableResourceServer annotation is used then security.require_ssl=true has no effect.

I expected that a request to http://localhost:8080/ would be redirected to https://localhost:443/.

However the Actuator endpoints behave as I expect.  So a request to http://localhost:8080/health redirects to https://localhost:443/health.

Please see my [example project](https://github.com/thomasturrell/ideal-tribble.git).

**Enhancement Request**

The load balancer I use only supports http and does not follow redirects so the health check fails when security.require_ssl=true. Since unauthenticated requests to the health check only return the status would it be possible for it to ignore the security.require_ssl setting for unauthenticated requests?

I apologise for combining a Bug report and a Enhancement request, however they seem related since if this is bug is confirmed and fixed I am going to have to manually change the behaviour of the health check.

Thank you for all your hard work on Spring Boot.

**Comment by mbhave** [comment]
@thomasturrell When `@EnableResourceServer` is added, it adds a `WebSecurityConfigurerAdapter` that has a higher precedence than the `WebsecurityConfigurerAdapter` that configures ssl, which is why you don't see that redirect. Have you tried extending the `ResourceServerConfigurerAdapter` and overriding the `configure` method with `http.requiresChannel().anyRequest().requiresSecure()`, for requests that you would want ssl for?

**Comment by thomasturrell** [comment]
@mbhave Thank you for your suggestion I will set `security.require_ssl=false` so that the health check is available via HTTP and then as you suggested I will extend the `ResourceServerConfigurerAdapter` and override the `configure` method with `http.requiresChannel().anyRequest().requiresSecure()` to force HTTPS on the other requests.

However I wish there was an easy way to configure this behaviour in using a property value since anyone that implements a resource server should force SSL for all requests.  Maybe the properties `security.oauth2.require_ssl` and `endpoints.require_ssl` could exist? Or perhaps a property that lets me list of endpoints to exclude from forcing SSL (the documentation hint that this is possible).

Essentially I think that `security.require_ssl=true` I misleading because it's not honored when `@EnableResourceServer` is used.  Even if it isn't a bug then I believe that the behaviour should be documented or a warning should go in the log.

**Comment by mbhave** [comment]
@thomasturrell I agree that the property is misleading. The current property name `security.require-ssl` sort of implies that it applies to all types of security, whereas it only applies to basic auth security provided by Boot. https://github.com/spring-projects/spring-boot/issues/8757. If we move it under the `basic` namespace, we can consider adding `security.oauth2.require_ssl`.

**Comment by mbhave** [comment]
Closing since Spring Boot provides OAuth support via Spring Security and `security.require_ssl` doesn't exist anymore.
