### ISSUE TITLE
Consider flipping the default for management.add-application-context-header to false

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#8656]
As this header exposes some internal information like application name, port number and active profiles it should be enabled only on demand.

**Comment by tlefevre** [comment]
Why was this closed? It seems like a legit concern. The presence of this header easily discloses that the application responding is a spring boot application.

**Comment by snicoll** [comment]
@tlefevre this issue was closed in `2.0.0.M1` as implemented see 20f201b.

**Comment by tlefevre** [comment]
Ah, my apologies!
