### ISSUE TITLE
Drop ConfigurationProperties.ignoreNestedProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8657]
We don't have any classes that use `ConfigurationProperties.ignoreNestedProperties` and I can't think of a good reason to add it to the updated binder.

**Comment by philwebb** [comment]
we'll do this

**Comment by wilkinsona** [comment]
As spotted by @mbhave, we can drop `IgnoreNestedPropertiesBindHandler` and `IgnoreNestedPropertiesBindHandlerTests` now too
