### ISSUE TITLE
logging setup on application.properties failed to work

### ISSUE THREAD

**Issue by fansgit** [spring-projects/spring-boot#8674]
[Logging](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-log-levels) setup `logging.level.root=OFF` on `application.properties` couldn't stop logging below, but putting `<root level="OFF"/>` on `logback.xml` had effect.

```xml
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.2.RELEASE</version>
	<relativePath />
</parent>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-logging</artifactId>
	</dependency>
</dependencies>
```

```java
@SpringBootApplication
public class DemoApplication {
        public static void main(String[] args) {
                SpringApplication.run(DemoApplication.class, args);
        }
}
```

**Comment by philwebb** [comment]
> couldn't stop logging below

Below what? I'm sorry but I'm not sure I'm following you.

Could you please provide a sample application that shows what you mean?

**Comment by fansgit** [comment]
@philwebb Sorry, just added the sample code above.

**Comment by philwebb** [comment]
I'm having trouble replicating this. I update `SampleSimpleApplication` in our samples folder with property and didn't see any logging.

Can you share a complete project that shows the problem please?

**Comment by fansgit** [comment]
Project structure:
```text
src/main/java
  DemoApplication.java
src/main/resources
  application.properties (or logback.xml)
src/test/java
  DemoApplicationTest.java
```
```java
@RunWith(SpringRunner.class)
@SpringBootApplication
public class DemoApplicationTests {
	@Test
	public void contextLoads() {
	}
}
```
```text
$ mvn clean spring-boot:run
=> logging stopped after disabling it on either application.properties or logback.xml.
$ mvn clean test
=> logging stopped after disabling it on logback.xml, but didn't on application.properties. 
```

**Comment by philwebb** [comment]
You made no mention of tests in your original report and the attached code doesn't show me what your test is doing. Logging defaults may well not change in tests (depending on how they are written)

**Comment by fansgit** [comment]
Sorry, my original report was really misleading. The last update of mine corresponded to what you commented above. 

> Logging defaults may well not change in tests (depending on how they are written)

Could you elaborate it?

**Comment by philwebb** [comment]
Sure, the default for logback is to output debug logging. If you customize with `logback.xml` file, then logback can obviously respect that. With Spring Boot, we have a `LogbackLoggingSystem` class that's responsible for setting the log levels. When you run a `SpringApplication` the logging system is initialized and the `application.properties` are used to set the levels.

If you write a unit test, you might not trigger that piece of code. Se it really depends on what type of test you are writing, and if you're using the `@SpringBootTest` annotation.

Without seeing the contents of `DemoApplicationTest` it's impossible to tell what's going on, but I suspect this isn't a bug.

**Comment by fansgit** [comment]
```text
pom.xml
src/main/java
  DemoApplication.java
src/main/resources
  application.properties
src/test/java
  DemoApplicationTests.java
```

```xml
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.2.RELEASE</version>
	<relativePath />
</parent>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-logging</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
```

```java
@SpringBootApplication
public class DemoApplication {
        public static void main(String[] args) {
                SpringApplication.run(DemoApplication.class, args);
        }
}
```



```text
logging.level.root=ERROR
logging.level.org.springframework=OFF
logging.level.com.me=DEBUG
logging.pattern.console=[%-5p] Hello %m%n
```
```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class DemoApplicationTests {
	@Test
	public void contextLoads() {
                LoggerFactory.getLogger(DemoApplicationTests.class)
				.debug("world!");
	}
}
```
```text
$ mvn clean test
[DEBUG] Hello world!
```

*Hint: In any case the application class must be present, as it flags "powered by Spring Boot".*
