### ISSUE TITLE
Replace use of arg.hashCode when generating property source name

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8680]
As noted in #8661 we currently use an array hashcode for the added command line arguments. There doesn't seem to be a great reason to do that and we could probably just switch to a fixed name.

```java
composite.addPropertySource(new SimpleCommandLinePropertySource(
						name + "-" + args.hashCode(), args));
```

**Comment by SuhanKoh** [comment]
@philwebb Can I take a stab at this? Would a time stamp works better?
