### ISSUE TITLE
Spring Boot Reference: Embedded servlet containers

### ISSUE THREAD

**Issue by Abrasha** [spring-projects/spring-boot#8684]
The table with embedded servlets seems to be broken.

Link: [getting-started-system-requirements-servlet-containers](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#getting-started-system-requirements-servlet-containers)

Link to the broken file: [getting-started.adoc](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/getting-started.adoc)

See screenshot:

![screen shot 2017-03-21 at 3 33 01 pm](https://cloud.githubusercontent.com/assets/11317222/24149580/b1eb4bde-0e4b-11e7-9f56-a38433d7d0b5.png)

**Comment by philwebb** [comment]
Thanks. It looks like things are fine on 1.5.x so we must have messed master up some how.

**Comment by philwebb** [comment]
Closing in favor of PR #8688
