### ISSUE TITLE
Run Specific Health Checks

### ISSUE THREAD

**Issue by pioto** [spring-projects/spring-boot#8685]
With many monitoring tools, the best granularity I can get is "something is broken", using the current health check actuator -- many tools won't show the resulting JSON, and just monitor the HTTP status code.

Additionally, if my monitoring system detects that some part of the system is unhealthy, it's possible that additional failures could go unnoticed, because there would be no additional alarms for my "/health" check.

For both of these reasons, I'd like to suggest adding support for querying the health of specific health indicator; for example:

`GET /health`:
```json
{"status": "UP", "mail":{"status": "UP", "location": "localhost:25"}, "db": {"status": "UP", "database": "MySQL", "hello": 1}}
```

`GET /health/mail`:
```json
{"status": "UP", "location": "localhost:25"}
```

`GET /health/db`:
```json
{"status": "UP", "database": "MySQL", "hello": 1}
```

This may prove to be a more straightforward solution to the requirements of #3441 & #2652 as well.

**Comment by philwebb** [comment]
Thanks for the suggestion.

**Comment by snicoll** [comment]
Fixed by https://github.com/spring-projects/spring-boot/commit/b51b997b70bbb7ffc5b2291fd6309acb55dd3f31
