### ISSUE TITLE
Yaml with special maven resource delimiter will get parsing error during devtools automatic restart

### ISSUE THREAD

**Issue by simonwg** [spring-projects/spring-boot#8689]
**Issue**
With latest Spring Boot v1.5.2:
If the application.yml file contains special maven resource delimiter "@", during automatic restart through devtools, the parsing error will occurs.

e.g.
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 30, column 26:
            myProp: @myPropValue@
                             ^

**Comment by wilkinsona** [comment]
Duplicates #8438

**Comment by fy-kenny** [comment]
You cloud try like this
https://github.com/yaml/yaml/issues/51
