### ISSUE TITLE
Fast Restart will not respect the changing of maven resource delimiter for YAML configuration file

### ISSUE THREAD

**Issue by simonwg** [spring-projects/spring-boot#8691]
**Issue**
This is the follow up of the issues
[https://github.com/spring-projects/spring-boot/issues/8438](https://github.com/spring-projects/spring-boot/issues/8438)
[https://github.com/spring-projects/spring-boot/issues/8689](https://github.com/spring-projects/spring-boot/issues/8689)
regarding to change the maven resource delimiter to remedy the parsing error of YAML file.

I found that if I changed the maven resource delimiter to some valid characters, the lookup will failed after Fast Restart.

e.g.
In my pom.xml, I add the following to change the default resource delimiter.
`<resource.delimiter>QQQ</resource.delimiter>`

In my application.yml, 
```
app:
   myProperty: QQQmyPropertyValueQQQ

```
The `QQQmyPropertyValueQQQ` is correctly substituted to the property value in pom.xml during startup. However, if I _touch_ the application.yml to trigger the fast restart, the `QQQmyPropertyValueQQQ` lookup will fail. It will retain the value `QQQmyPropertyValueQQQ` and not substituted.

**Comment by wilkinsona** [comment]
I don't think this has anything to do with changing the delimiter. If you don't involve your build system in the change then nothing is going to perform the filtering. This is already being discussed in #5136

**Comment by fy-kenny** [comment]
I solved issue like this
https://github.com/yaml/yaml/issues/51
