### ISSUE TITLE
Bug with managing log levels for more than 3 packages.

### ISSUE THREAD

**Issue by kolianovich** [spring-projects/spring-boot#8701]
Hello!

I try to manage log levels as follows:

logging:
  level:
    com.mycompany.package: DEBUG

It works fine. All loggers inside "package" directory write DEBUG and INFO output.

logging:
  level:
    com.mycompany.package.package2: DEBUG

But in this case if there are more than 3 package levels for classes inside "package2" directory DEBUG output doesn't work, only INFO.

Spring-boot version is 1.4.2.RELEASE.

**Comment by wilkinsona** [comment]
I'm not 100% sure that I understand your description of the problem. To avoid any confusion can you please provide a small sample that reproduces the problem?

**Comment by kolianovich** [comment]
OK. I use yaml file for logging configuration. And for example I have the next configuration:
```
logging:
  level:
    com.mycompany.testpackage: DEBUG
```
Inside "testpackage" I have class "TestClass":
```
package com.mycompany.testpackage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

TestClass {
    private static final Logger LOGGER = LoggerFactory.getLogger(TestClass.class.getName());
    public void testMethod()  {
            LOGGER.debug("testMethod was invoked")
    }
}
```
When I invoke testMethod the string "testMethod was invoked" is logged in the output. All is OK.

But if I change the configuration as follows:
```
logging:
  level:
    com.mycompany.testpackage.nexttestpackage: DEBUG
```
and move TestClass to the nexttestpackage, in this case when I invoke testMethod nothing is logged in the output. I tried a lot of variation and it looks like spring-boot has problems with logging for fourth or more packages.

**Comment by wilkinsona** [comment]
> I tried a lot of variation and it looks like spring-boot has problems with logging for fourth or more packages

It works fine for me with any package depth.

Can you please provide a complete sample, i.e. something that we can unzip or clone and then run? Piecing things together from a comment here isn't a reliable way to reproduce a problem.

**Comment by kolianovich** [comment]
I tried to simplfy my project and I undestood the problem. It is not because of spring-boot. I am very sorry. Please, close the ticket.
