### ISSUE TITLE
spring-boot-devtools executes SHUTDOWN on HSQLDB running as a separate server

### ISSUE THREAD

**Issue by slauth** [spring-projects/spring-boot#8702]
Using Spring Boot 1.3.8.RELEASE with `spring-boot-devtools` and a standalone HSQL in server-mode. A `SHUTDOWN` is sent to the database server whenever the application context is refreshed. After that, the database is not accessible any longer.

**Comment by wilkinsona** [comment]
Can you please provide a small, complete example that illustrates the problem?

**Comment by slauth** [comment]
I have assembled a minimal application that shows the problem: [demo.zip](https://github.com/spring-projects/spring-boot/files/864159/demo.zip)

1. Start HSQL in standalone/server-mode: `java -cp hsqldb-2.3.3.jar org.hsqldb.server.Server --database.0 file:dbname --dbname.0 dbname`

1. Start `DemoApplication` ([/health](http://localhost:8080/health) will show `"status": "UP"`)

1. Make some arbitrary change to trigger `spring-boot-devtools`

1. [/health](http://localhost:8080/health) will show `"status": "DOWN"` (log will contain `java.net.ConnectException: Connection refused: connect`, HSQL prints `Initiating shutdown sequence... Shutdown sequence completed` in terminal)

**Comment by wilkinsona** [comment]
Thank you.

The problem is that Devtools isn't distinguishing between an in-memory HSQLDB instance and one that's running in a separate process. Until a fix is available, you should be able to work around the current behaviour by excluding `DevToolsDataSourceAutoConfiguration` on `@SpringBootApplication`.

**Comment by slauth** [comment]
OK, thanks for the quick reply and the workaround. I guess this concerns other DBMS (H2, Derby) as well.
