### ISSUE TITLE
LaunchedURLClassLoader does not provide signers information

### ISSUE THREAD

**Issue by stovocor** [spring-projects/spring-boot#8704]
Dear Spring Boot team,

our application jar is signed during the build process with a JKS key. It contains another jar in BOOT-INF/lib called mylib.jar which is signed with the same key.

When we retrieve the signers of any class in org/springframework/boot/loader, the signers are returned as expected. However, for every class loaded from mylib.jar, the signers are null.

Is there a way to retain the signers for jars in BOOT-INF/lib?

We are using Spring Boot v1.5.1.RELEASE.

**Comment by wilkinsona** [comment]
Unfortunately, this appears to be caused by a bug/limitation in the JDK. When the class is found, `sun.misc.URLClassPath$Loader` [returns a `sun.misc.Resource` subclass](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/misc/URLClassPath.java#l549) that doesn't override `getCodeSigners()`. As a result, the `CodeSource` for the class has no code signers and `Class.getSigners()` returns `null`.

**Comment by wilkinsona** [comment]
The problem can be reproduced with a pure `URLClassLoader`. The behaviour varies depending on whether it's a `jar:file` URL or a `file:` URL that points to the jar file:

This will output `null`:

```java
URLClassLoader jarFileLoader = new URLClassLoader(
        new URL[] { new URL("jar:file:src/test/resources/nested-jars/signed-app.jar!/") },
        null);
System.out.println(jarFileLoader.loadClass("demo.Application").getSigners());
```

This will output the signers:

```java
URLClassLoader fileLoader = new URLClassLoader(
        new URL[] { new URL("file:src/test/resources/nested-jars/signed-app.jar") },
        null);
System.out.println(Arrays.toString(fileLoader.loadClass("demo.Application").getSigners()));
```

@stovocor Sorry, but I don't think there's anything we can do about this in Spring Boot. If you'd like to pursue it I think your best course of action would be to open a JDK bug.

**Comment by stovocor** [comment]
Thank you very much for the quick response, @wilkinsona 

Your analysis helped us to find a workaround: We instruct Spring Boot to unpack our signed jar during the startup process as explained in [84.6 Extract specific libraries when an executable jar runs](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html)

```
springBoot  {
    requiresUnpack = ['org.jruby:jruby-complete']
}
```
