### ISSUE TITLE
logging.level.root throws NPE with log4j2

### ISSUE THREAD

**Issue by lwshuo** [spring-projects/spring-boot#8705]
[LoggingRebinder](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/logging/LoggingRebinder.java) treats root as `null`:

```java
private void setLogLevel(LoggingSystem system, Environment environment, String name,
		String level) {
	try {
		if (name.equalsIgnoreCase("root")) {
			name = null;
		}
		level = environment.resolvePlaceholders(level);
		system.setLogLevel(name, LogLevel.valueOf(level.toUpperCase()));
	}
	catch (RuntimeException ex) {
		this.logger.error("Cannot set level: " + level + " for '" + name + "'");
	}
}
```

in `Log4j2LoggingSystem`, it expects a "" for root and doesn't take care of null. `LogbackLoggingSystem` does take care of null, can we please be consistent on this?

```java
public void setLogLevel(String loggerName, LogLevel logLevel) {
	Level level = LEVELS.convertSystemToNative(logLevel);
	LoggerConfig loggerConfig = getLoggerConfig(loggerName);
	if (loggerConfig == null) {
		loggerConfig = new LoggerConfig(loggerName, level, true);
		getLoggerContext().getConfiguration().addLogger(loggerName, loggerConfig);
	}
	else {
		loggerConfig.setLevel(level);
	}
	getLoggerContext().updateLoggers();
}
```

**Comment by philwebb** [comment]
I thought that both `LogbackLoggingSystem` and `Log4J2LoggingSystem` treated `null` as the root logger. The code for `LogbackLoggingSystem` is [here](https://github.com/spring-projects/spring-boot/blob/dfe26aace8ee01d53d59553273d055c330c7099b/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L265) and for `Log4J2LoggingSystem` it's [here](https://github.com/spring-projects/spring-boot/blob/dfe26aace8ee01d53d59553273d055c330c7099b/spring-boot/src/main/java/org/springframework/boot/logging/log4j2/Log4J2LoggingSystem.java#L258).

Can you please provide a stacktrace of the NPE that you're seeing and if possible a test case or sample application that reproduces it?

**Comment by lwshuo** [comment]
I just https://github.com/spring-projects/spring-boot/issues/4808 , it's fixed already! sorry about that
