### ISSUE TITLE
logging.config=classpath:log4j2-dev.xml 无效

### ISSUE THREAD

**Issue by yanlichong** [spring-projects/spring-boot#8709]
logging.config=classpath:log4j2-dev.xml
spring boot log4j2 多环境指定配置文件路径失效

24-Mar-2017 17:34:33.572 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ERROR StatusLogger No Log4j context configuration provided. This is very unusual.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

**Comment by wilkinsona** [comment]
Duplicates #4809.
