### ISSUE TITLE
Remove remaining optional usage of org.json:json

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8710]
We still have an optional dependency on `org.json:json` as it's used by `JsonJsonParser` (one of several `JsonParser` implementations that we provide. I think it's probably more trouble that it's worth (see #8706, for example).

I think we should remove our use of `org.json:json` and either update `JsonJsonParser` to use one of the clean room implementations, or just get rid of it entirely.

**Comment by wilkinsona** [comment]
Alternative implementations:

- https://github.com/tdunning/open-json
- https://github.com/openjson/openjson

**Comment by philwebb** [comment]
I'd be in favor of dropping the `JsonJsonParser` but we still have a dependency on `JSONAssert` which uses:

```
            <groupId>com.vaadin.external.google</groupId>
            <artifactId>android-json</artifactId>
            <version>0.0.20131108.vaadin1</version>
```

So I'm not sure removing our managed dependency would fix #8706

**Comment by wilkinsona** [comment]
On closer inspection I don't think it would either. I'd misread the problem as being due to our dependency management pulling in a version of `org.json:json` that's too old.

**Comment by wilkinsona** [comment]
We've decided to drop `JsonJsonParser`
