### ISSUE TITLE
Actuator's non-GET behaviour not REST conform

### ISSUE THREAD

**Issue by cburgmer** [spring-projects/spring-boot#8754]
We have configured the /health actuator and exposed the API via swagger. The latter now shows all possible request methods to be available, GET, POST, DELETE, OPTIONS... Probing those shows that the request method seems transparent to the implementation, as 200 with the actual payload is returned in all cases.

This brings about two issues:

- Swagger documentation is diluted and does not correctly document intent (might take this up independently with them).
- Expectations might not match what the actuators expose. From a security concern you'll have to look twice to make sure that a "reader interface" is *not* open to manipulation (made worse by Swagger reporting the endpoint is open as mentioned above).

**Comment by wilkinsona** [comment]
With 1.5, posting to `/health` results in:

```json
{"timestamp":"2017-03-27T10:20:30.004+0000","status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/health"}
```

This is due to the changes made for #7967. What version of Boot are you using?

**Comment by cburgmer** [comment]
1.4.2 indeed. I'll try upgrading and will report back. Thanks for the quick reply.

**Comment by cburgmer** [comment]
Thanks, works like a charm. Sorry for the noise.
