### ISSUE TITLE
Add support for actuator kafka client metrics.

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-projects/spring-boot#8756]
As a user of Spring Kafka, I need access to kafka client metrics via the spring boot actuator endpoint. This data is likely to be accessible via `org.springframework.kafka.core.KafkaOperations` `metrics()` method.

**Comment by azimovMichael** [comment]
I would like to use this issue as my first contribution to the project. 
Do you mean you want the kafka metrics exposed in the /metrics endpoint?

**Comment by wilkinsona** [comment]
@azimovMichael Yes, I believe that's what @PedroAlvarado meant when they said "via the spring boot actuator endpoint". Providing a `PublicMetrics` implementation for Kafka should be sufficient to have the metrics appear in both the HTTP and JMX metrics endpoints.

**Comment by philwebb** [comment]
Closing in favor of PR #9047
