### ISSUE TITLE
Consider if we want spring.profiles to accept a comma list

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8759]
We're planning for a new binding logic to be quite strict around lists so that we don't accidentally merge different sources in an add way. The current [prototype](https://github.com/philwebb/spring-boot/tree/env_conversion_hacking) handles this in the `Binder` by looking for `[n]` indexed items and limiting the source.

During testing it became obvious that some of our tests that set `spring.profile` need to change. Where as previously you could do:

```
spring.profile=foo
```

You now need to do

```
spring.profile[0]=foo
```

It's a little unfortunate to push this logic onto the user, perhaps we should update the binder so that List/Collection binding can optionally also work with a comma separated list.

**Comment by philwebb** [comment]
There doesn't seem to be any reason not to do this now we completely control the binder. See https://github.com/philwebb/spring-boot/commit/998c06d5f0f41d142b4e49cbc91ff60e43c0ea03

**Comment by mbhave** [comment]
[Test case](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/CollectionBinderTests.java#L209) to prove this works.
