### ISSUE TITLE
Provide a REPL shell with the Application loaded.

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#876]
We want to be able to start up a groovy command line shell, so that we can quickly get feedback from our application.  For example:

```
$ gradle bootConsole
> context.getBean("userRepository").findOne("123").getName()
=> "John Smith"
```

This kind of REPL would be really valuable to have for development and debugging purposes.

We've been experimenting with `groovysh` and have tried to load a Groovysh with our application as the context.  There probably is a better way to do this.

```
Application.main(args);
Binding binding = new Binding();
binding.setVariable("context", Application.context);

new org.codehaus.groovy.tools.shell.Groovysh(
   binding, 
   new IO()
);

```

**Comment by cbornet** [comment]
You can do something similar with scala's console:
```shell
$ mvn scala:console

scala> import com.mycompany.myapp.StandardApp
import com.mycompany.myapp.StandardApp

scala> StandardApp.main(Array[String]())
2016-09-19 18:33:10.464  INFO 7373 --- [           main] com.mycompany.myapp.StandardApp          : Starting StandardApp on vagrant-ubuntu-trusty-64 with PID 7373 (/home/user/standard/target/classes started by user in /home/user/standard)
2016-09-19 18:33:10.478 DEBUG 7373 --- [           main] com.mycompany.myapp.StandardApp          : Running with Spring Boot v1.4.0.RELEASE, Spring v4.3.2.RELEASE
... app starts

scala> StandardApp.context.getBean("userRepository").asInstanceOf[com.mycompany.myapp.repository.UserRepository].findAll()
Hibernate: select user0_.id as id1_5_, user0_.created_by as created_2_5_, user0_.created_date as created_3_5_, user0_.last_modified_by as last_mod4_5_, user0_.last_modified_date as last_mod5_5_, user0_.activated as activate6_5_, user0_.activation_key as activati7_5_, user0_.email as email8_5_, user0_.first_name as first_na9_5_, user0_.lang_key as lang_ke10_5_, user0_.last_name as last_na11_5_, user0_.login as login12_5_, user0_.password_hash as passwor13_5_, user0_.reset_date as reset_d14_5_, user0_.reset_key as reset_k15_5_ from jhi_user user0_
res9: java.util.List[com.mycompany.myapp.domain.User] = [User{login='system', firstName='System', lastName='System', email='system@localhost', activated='true', langKey='en', activationKey='null'}, User{login='anonymoususer', firstName='Anonymous', lastName='User', email='anonymous@localhost', activated='true', langKey='en', activationKey='null'}, User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', activated='true', langKey='en', activationKey='null'}, User{login='user', firstName='User', lastName='User', email='user@localhost', activated='true', langKey='en', activationKey='null'}]

**Comment by evmin** [comment]
I think this issue might become a bit more critical due to upcoming Remote Shell deprecation https://github.com/spring-projects/spring-boot/issues/7006.

Also relates to https://github.com/spring-projects/spring-boot/issues/7445

Critical for application frameworks relying on dynamic changes from the admin personnel.

**Comment by philwebb** [comment]
After some discussion we've decided this is something we don't want to put in the core of the project. If anyone wants to take this on outside of Spring Boot we'll happily add any extension points that are needed.

**Comment by mrsarm** [comment]
Is it actually removed the support in the new version 5 of Spring and Spring Boot 2 the Remote Shell?

Too disappointed to hear that.

Meanwhile, for those that use the previous versions of Spring, I made a "plugin" that allows to access and invoke your bean objects through the Groovy repl whithin the Remote Shell: https://github.com/grayshirts/spring-ctx-groovy

It's so simple like this: `ctx.App.myUserService.getById(100123)`. Take a look how it works:

![spring-ctx-groovy](https://raw.githubusercontent.com/grayshirts/spring-ctx-groovy/master/static/spring-ctx-groovy-session.gif)

**Comment by martin-g** [comment]
This is cool!

**Comment by mrsarm** [comment]
@martin-g don't forget to give a star to the project if it's useful for you :-)
