### ISSUE TITLE
Getting metrics and loggers by name fails with a 406 if the name ends with an extension known to PathExtensionContentNegotiationStrategy

### ISSUE THREAD

**Issue by igreenfield** [spring-projects/spring-boot#8765]
When you try to get data about the level of the logger with the name: "com.aaa.cab" I get 406 response.

Request:
```
URL: GET http://localhost:8080/loggers/com.aaa.cab
```

Response:
```json
{
  "timestamp": 1490705058981,
  "status": 406,
  "error": "Not Acceptable",
  "exception": "org.springframework.web.HttpMediaTypeNotAcceptableException",
  "message": "Not Acceptable",
  "path": "/customerservice/manage/loggers/com.nds.cab"
}
```

**Comment by yairogen** [comment]
👍

**Comment by wilkinsona** [comment]
I think this problem's always been lurking if you had an unfortunately named logger. It's now more likely to occur as Spring MVC has [expanded the list of file extensions](https://github.com/spring-projects/spring-framework/commit/f0a43e5d5c506a2ffec5654dac6886e23d940dda) for which it has a mime type. @igreenfield What version of Boot are you using?

I guess we need to turn off the use of `PathExtensionContentNegotiationStrategy` for the loggers endpoint, or at least make `HeaderContentNegotiationStrategy` go first.

**Comment by igreenfield** [comment]
spring-boot: 1.5.2.RELEASE

This is not the Logger name it is part of the package name of the logger....

**Comment by wilkinsona** [comment]
The metrics endpoint is also affected if the metric name ends in something that's known to `PathExtensionContentNegotiationStrategy`.

**Comment by wilkinsona** [comment]
Following some help from @rstoyanchev, I have a fix for this in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-8765). It introduces some new public API so I'd like some more eyes on it before it's merged please.

**Comment by rstoyanchev** [comment]
@wilkinsona, if the wrapping + conditional use of the path extension strategy could be made package private it would make things much simpler while still keeping the door open to such a public mechanism, possibly even as part of the Spring Framework, or even to finding a different way of achieving the same. 

The AbstractEndpointHandlerMapping would set a request attribute to indicate the current request is for an actuator endpoint. The web auto-config wraps any PathExtensionContentNegotiationStrategy and checks for that attribute.

**Comment by wilkinsona** [comment]
Thanks, Rossen. I did consider an approach like that but rejected it as I didn't want to introduce a conceptual cycle between `spring-boot-autoconfigure` and `spring-boot-actuator`. There is, of course, the possibility that a conceptual cycle is preferable to new public API. Thanks for taking a look.

**Comment by rstoyanchev** [comment]
No the cycle wouldn't be preferable indeed. Still I wonder... The new public API does put a good face on what is arguably an underlying limitation (the ability to vary content negotiation by URL). Could another option be for autoconfigure to advertise a request attribute takes care of disabling path extension checks?

**Comment by philwebb** [comment]
@rstoyanchev Are you suggesting a framework change to `PathExtensionContentNegotiationStrategy` so that it can be selectively ignored based on a request attribute?

Alternatively if we don't want framework changes we could possibly limit the new approach to just the `PathExtensionContentNegotiationStrategy`.

**Comment by rstoyanchev** [comment]
@philwebb, I don't have any good ideas for framework support based on this use case alone. I was rather looking for a workaround with no public API footprint to leave options for further changes if more use cases do come up. 

I realize that detecting a request attribute (in Boot) doesn't completely fit this criteria, it's just the most reasonable trade-off I can think of. `AbstractEndpointHandlerMapping` setting a request attribute to advertise the request is for an actuator mapping seems more broadly useful. The web auto-config detecting that (by text? to avoid the circular dependency) would be the actual workaround that could possibly be undone in the future.

**Comment by philwebb** [comment]
@wilkinsona I've gone with a simplified version of your commit that's limited just to `PathExtensionContentNegotiationStrategy`.
