### ISSUE TITLE
PropertiesLauncher and -Dloader.path not loading jar

### ISSUE THREAD

**Issue by jglesner** [spring-projects/spring-boot#8772]
Hello,

I'm trying to use PropertiesLauncher with no success.  I have a Spring Boot application, built with the ZIP layout.  here is a snippet from my manifest: 
```
Manifest-Version: 1.0
Implementation-Version: 0.0.3-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: jglesner
Spring-Boot-Version: 1.4.4.RELEASE
Implementation-Vendor: Pivotal Software, Inc.
Main-Class: org.springframework.boot.loader.PropertiesLauncher
```

I have a second JAR, which I've built using the MODULE layout, and placed in a lib/ folder in the same directory as the Spring Boot Application. It only has one class in it and a beans.xml file. I haven't tried to access that class directly, because I don't see the Spring Boot application loading the external JAR when I run the Spring Boot app using: 

`java -verbose -Dloader.path=lib -jar myspringbootapplication.jar`

I'm not receiving any errors. 

Ideally, I would like to import that beans.xml file in the external jar as a resource via my Spring Boot spring-config.xml configuration and load the one class in the external jar as a bean.  

Any guidance would be appreciated.

**Comment by wilkinsona** [comment]
Can you please provide a small sample the illustrates the problem?

**Comment by jglesner** [comment]
I'm unable to share my current source because its proprietary, but I could create two new projects (if necessary, albeit that's a bit more work than I was hoping for).  Is there any other way to debug this?  What should I be looking for in the startup to know that the conditions are right for this to work? 

Based on my examination of the situation, it appears that the PropertiesLauncher is getting loaded, but it doesn't make an attempt to add the external jar. I've even renamed the lib/ folder to see if it was scanning for that folder, and didn't receive an error.  I've tried using the LOADER_PATH environment variable as well, to no avail.   

I'm on a Mac running OS X Yosemite (10.10.5), java version "1.8.0_101", Spring Boot v1.4.4.RELEASE, and Spring v4.3.6.RELEASE.

**Comment by wilkinsona** [comment]
> Is there any other way to debug this? 

Yes, you could step through in a debugger and see what `PropertiesLauncher` is doing.

> I've even renamed the lib/ folder to see if it was scanning for that folder, and didn't receive an error

IIRC, you won't get an error of a directory on the loader path doesn't exist.

Sorry, but trying to second guess what you're doing or why something isn't behaving as you expect is more work than we have time for. If you'd like us to spend time investigating in any more detail then please spend some time making it as easy as you can for us to do so by providing a small sample that illustrates the behaviour you're seeing.

**Comment by jglesner** [comment]
Understood. I'm building an example to duplicate the behavior.  Will have that for you soon.

**Comment by jglesner** [comment]
In building the example, I resolved the issue.  Thank you for your willingness to help!

**Comment by cprepos** [comment]
What was the solution?

**Comment by logemann** [comment]
that would be nice to know. I have a working example with loading files via:
-Dloader.path=file:/my.jar
but i am unable to add a whole folder to search for jar files like:
-Dloader.path=file:/myfolder/
