### ISSUE TITLE
GitProperties#getShortCommitId length not configurable

### ISSUE THREAD

**Issue by ptamarit** [spring-projects/spring-boot#8773]
Currently, the method `GitProperties#getShortCommitId` shortens the hash to the hardcoded length of 7.

Maybe this is too short?
[According to this article](https://blog.cuviper.com/2013/11/10/how-short-can-git-abbreviate/), 12 characters is foolproof for the Linux kernel, so maybe this would be a better default.

Another thing a bit weird is that `GitProperties#getShortCommitId` shortens the full hash (property key `git.commit.id`), while git-commit-id-plugin already provides a shortened hash (property key `git.commit.id.abbrev`). The default length that git-commit-id-plugin uses is also 7, but it can be configured via the `abbrevLength` configuration.

I think the following would be the best solution:
* Configure `abbrevLength` to 12 in spring-boot-starter-parent.
* Use `git.commit.id.abbrev` instead of `git.commit.id` in `GitProperties#getShortCommitId`.
* I think this would let users override the length in their own POM.

I can create a PR if you want (not sure against which branch it should be though).

PS: [This SO question](http://stackoverflow.com/questions/32275497/overriding-git-commit-id-plugin-defaults-in-spring-boot) seems to be related to the customization problem.

PPS: [Related article](https://github.com/blog/2288-git-2-11-has-been-released) mentionned by @wilkinsona on Gitter.

**Comment by snicoll** [comment]
> Another thing a bit weird is that GitProperties#getShortCommitId shortens the full hash (property key git.commit.id), while git-commit-id-plugin already provides a shortened hash

Maven is not the only build system that we support and the Gradle plugin did not use to expose that property. I can see that it does now even if it's not configurable.

Regardless, you are right, we should look for the property and shorten the hash ourselves only if it does not exist. Github uses 7 characters so I see no reason to change our default at this point but that change would allow you to tune it if you're using Maven.

If you're willing to provide a PR, please go ahead. You can do it against `master` and we'll figure out how to merge it. Thanks!

**Comment by snicoll** [comment]
Closing in favour of the PR #8781
