### ISSUE TITLE
Consider exposing ClassPathExclusions

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#8775]
`ClassPathExclusions` looks generally useful for testing auto-configurations when developing them.

It would be good to move it to some test module like `spring-boot-test` or `spring-boot-test-autoconfigure` and expose it.

For example, Spring Cloud is already using a copy of it: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/test/java/org/springframework/cloud/ClassPathExclusions.java

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We've discussed this a few times and decided that we don't want to make it public for a couple of reasons:

1. It's been implemented specifically to meet our needs and isn't designed for general use
2. We need the ability to make breaking changes at any time
