### ISSUE TITLE
LoggersMvcEndpoint add the ability to delete logger configuration.

### ISSUE THREAD

**Issue by igreenfield** [spring-projects/spring-boot#8776]
After I add new logging configuration I can't remove it without restarting the component.

**Comment by yairogen** [comment]
👍

**Comment by philwebb** [comment]
@igreenfield @yairogen Are you specifically looking for loggers to get deleted, or do you just want a HTTP DELETE to set the logger level to `OFF`?

**Comment by igreenfield** [comment]
@philwebb Not setting to off, delete it from the configuration.
setting to off will prevent it from writing logs, remove recover the default configuration: inheritance from parent logger.

**Comment by igreenfield** [comment]
@philwebb This is the change: [Add_delete_logger_configuration.patch](https://github.com/spring-projects/spring-boot/files/901687/Add_delete_logger_configuration.txt)

**Comment by wilkinsona** [comment]
@igreenfield Could you turn that patch into a pull request please? Ideally against the master branch

**Comment by igreenfield** [comment]
create PR #8830

**Comment by igreenfield** [comment]
@wilkinsona PR #8830

**Comment by snicoll** [comment]
Closing in favour of PR #8830
