### ISSUE TITLE
Investigate auto-configuration for Spring Vault

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8779]
Spring Cloud Vault will be part of Spring Cloud Dalston and provides Boot integration for Spring Vault. However, it's only using Spring Cloud so that it can use the bootstrap context to add its property sources to the environment.

After chatting with @mp911de, it would seem to make sense to look at providing auto-configuration for Spring Vault in Spring Boot and contributing its property sources via an environment post-processor. Spring Cloud Vault would then perhaps become redundant or could build on top of the support in Boot.

**Comment by spencergibb** [comment]
> providing auto-configuration for Spring Vault in Spring Boot

Makes sense.

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
