### ISSUE TITLE
JacksonAutoConfiguration doesn't apply without spring mvc

### ISSUE THREAD

**Issue by chanjarster** [spring-projects/spring-boot#8783]
I'm working on a spring boot application which is not a web application. It runs standalone on a machine and does not need to handle any http requests. So simply speaking, it's not a spring mvc application.

Then problem is: this application needs a jackson ObjectMapper which JacksonAutoConfiguration provides, but it doesn't work.

I dive into the  JacksonAutoConfiguration source code and found that JacksonAutoConfiguration @ConditionalOnClass Jackson2ObjectMapperBuilder which is included in spring-web project.

So if I want JacksonAutoConfiguration to work I must include spring-web, but that's not what I want, and I'm afraid if I do that will cause some problems.

Is there any solution or workaround to make JacksonAutoConfiguration works without depending on spring-web or spring-mvc, and meanwhile keep the feature such as @JsonComponent and Jackson2ObjectMapperBuilderCustomizer?

**Comment by wilkinsona** [comment]
The title of the issue is incorrect as spring-web and spring-mvc are separate modules and only the former is required. It contains web-related classes for both client-side and server-side applications. Your fear that adding a dependency on spring-web will cause problems is, as far as I know, unfounded. Please try adding the necessary dependency.

**Comment by jhoeller** [comment]
A note from the core Spring Framework perspective:

`spring-web` is indeed a common module not just for server-side web applications but also for client-side web consumers (e.g. `RestTemplate` users) and web-related protocols and payload types. It should be seen as a web-oriented companion of `spring-core` and `spring-context`. While it certainly contains stuff that you won't be using in your scenario, that doesn't hurt and isn't different from unused stuff in other modules.

The `spring-webmvc` module on the other hand contains our Servlet-based dispatcher framework (a.k.a. "Spring MVC"), and `spring-webflux` (new in 5.0) serves as the home of our reactive HTTP dispatcher framework. Those are certainly more specifically purposed modules and therefore out of place in your scenario. FWIW, both of them depend on common functionality in `spring-web`, as one would expect.

**Comment by chanjarster** [comment]
@wilkinsona @jhoeller Thank you for explanation!
