### ISSUE TITLE
Support for Cloud Foundry .profile files in build repackagers

### ISSUE THREAD

**Issue by youngm** [spring-projects/spring-boot#8790]
# Enhancement

With Spring boot 1.4 and the refactor of the maven plugin to support `LayoutFactory` all my Spring Boot apps that deploy to CloudFoundry and use a `.profile` file have broken. https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile

It would be great if spring boot either:
a. Provided a layout factory like the old one that put `src/main/resources` in the root of the executable jar.
b. Added repackager config that allowed for a set of files to be put into the root of the produced executable jar.

Thoughts?

**Comment by wilkinsona** [comment]
Duplicates #6626
