### ISSUE TITLE
default basic authentication user is generated despite of configuring AuthenticationManagerBuilder 

### ISSUE THREAD

**Issue by alecharp** [spring-projects/spring-boot#8792]
Hi,

even if I configured an `inMemoryAuthentication` in my `WebSecurityConfigurerAdapter` implementation, I can still see the default user's password printed on the log. But it's unusable.

I found few tickets with the same issue in the tracker, but they were supposed to be solved in `1.2.3.RELEASE`. Here I'm using `1.5.2.RELEASE` and I'm facing this.

Here is the application code:

```
@SpringBootApplication
public class SpringBootErrorApplication {
	public static void main(String[] args) {
		SpringApplication.run(SpringBootErrorApplication.class, args);
	}

	@RestController
	public static class PingAPI {
		@GetMapping(value = "/api/ping")
		public String ping() { return "pong"; }
	}

	@Configuration
	@EnableWebSecurity
	public static class SecurityConfig extends WebSecurityConfigurerAdapter {
		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http.httpBasic();
		}

		@Override
		protected void configure(AuthenticationManagerBuilder auth) throws Exception {
			auth.inMemoryAuthentication()
				.withUser("foo").password("bar").roles("ADMIN", "USER");
		}
	}
}
```

With this, you can do a `curl -u foo:bar :8080/api/ping` and get a correct response. But if you do a `curl -u user :8080/api/ping` and use the password printed in the startup logs, you get a `401`.

Please tell me I'm missing something in the configuration. I tried using `@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)` on the `SecurityConfig` but it's not helping. I also tried to set `security.basic.enabled=false` in my `application.properties` but it's still the same.

The problem is not that the default user is not usable, the problem is that the default user is created despite of having my own "user base".

Thanks in advance.

**Comment by snicoll** [comment]
I don't remember the details just yet but that configuration that uses `@EnableWebSecurity` looks fishy to me. If all you want is to redefine the authentication manager, the following will do:

```java
        @Configuration
	static class SecurityConfig extends GlobalAuthenticationConfigurerAdapter {

		@Override
		public void init(AuthenticationManagerBuilder auth) throws Exception {
			auth.inMemoryAuthentication()
					.withUser("foo").password("bar").roles("ADMIN", "USER");
		}
	}
```

That doesn't create a default user as you would expect. The [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security) has an explicit paragraph about all that (search for `@EnableWebSecurity`).

Having said that, it's still worth investigating why we're ending in this inconsistent state.

**Comment by mbhave** [comment]
@snicoll @alecharp The default user creation can be turned off by overriding the `authenticationManagerBean` method from the `WebSecurityConfigurerAdapter`. Your security config would look something like this
```
@Configuration
	@EnableWebSecurity
	public static class SecurityConfig extends WebSecurityConfigurerAdapter {
		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http.httpBasic();
		}

		@Override
		protected void configure(AuthenticationManagerBuilder auth) throws Exception {
			auth.inMemoryAuthentication()
				.withUser("foo").password("bar").roles("ADMIN", "USER");
		}
               
                @Override
		@Bean
		public AuthenticationManager authenticationManagerBean() throws Exception {
			return super.authenticationManagerBean();
		}
	}
```
See #3292
