### ISSUE TITLE
infinite loop in spring controller

### ISSUE THREAD

**Issue by peter-ponzel** [spring-projects/spring-boot#8797]
Hello,

I was looking for a way to read the full path that was requested when using a RequestMapping with /**.
There was an approach on stackoverflow that used `HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE` 
while trying that I came across an interesting issue and wanted to report it.
Here is what I used/did:

pom.xml:
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.2.RELEASE</version>
	<relativePath/>
</parent>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-hateoas</artifactId>
	</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<optional>true</optional>
</dependency>
```
controller
```
@Controller
@RequestMapping("/foo")
@Slf4j
public class FooController {
	/** works like a charm */
	@RequestMapping(value = "/ok/**", method = RequestMethod.GET)
	public void ok(final HttpServletResponse response, final HttpServletRequest request) throws Exception {
		final String paths = (String) request.getAttribute(HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE);
		log.debug("{}", paths);
	}
	/** indefinite loop */
	@RequestMapping(value = "/not-ok/**", method = RequestMethod.GET)
	public void notOk(final HttpServletRequest request) throws Exception {
		final String paths = (String) request.getAttribute(HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE);
		log.debug("{}", paths);
	}
}
```
You can also get rid of this issue with providing a response, for instance `return ResponseEntity.ok(paths);`

**Comment by dsyer** [comment]
This isn't really a Spring Boot question/problem though is it (it's just Spring MVC)? Also it's not quite clear what makes you think there's an infinite loop. Maybe include a bit more detail if you post to Spring JIRA.

Also note you don't need to use the request API to get the attributes (you can put `@RequestAttribute` on a method parameter).

**Comment by peter-ponzel** [comment]
Thank you for the information about `@RequestAttribute`, I will look into it.
Sorry I should have post the log output as well.

Log entry for calling `localhost:8080/foo/ok/foo/bar`:
`/foo/ok/foo/bar`

Log entry for calling `localhost:8080/foo/not-ok/foo/bar`:
```
/documents/not-ok/foo/bar
/documents/not-ok/foo/documents/not-ok/foo/bar
/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/bar
/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/documents/not-ok/foo/bar
```
I cut of the log because it just keeps on growing. 

Best Regards,
Peter
