### ISSUE TITLE
Improve CounterService operations 

### ISSUE THREAD

**Issue by jtuberville** [spring-projects/spring-boot#8800]
While reviewing some projects new to me today, I saw several cases of `CounterService` being in a for loop in order to have counters on batch processes. I was wondering if it had been discussed to allow `increment` and `decrement` in values other than one?
```java
void increment(String metricName, long value);
void decrement(String metricName, long value);
```
Since internally `Delta` already has this concept it does not seem challenging to extend the service interface itself. Any thoughts @dsyer or others?

Joshua

**Comment by dsyer** [comment]
We intentionally wanted to keep `CounterService` a simple as possible, but some changes are planned in 2.0, so it's a good time to have the discussion about opening it up. 

In the mean time, you can use `CounterBuffers` if you want access to an efficient incrementer with an explicit value. `Delta` is expensive if you do it a lot, so it's best not to use it explicitly if you can help it, but if you want to avoid being tied to the buffers implementation you can use `MetricWriter`.

**Comment by jtuberville** [comment]
Thanks @dsyer those are new to me. I can not find any write ups. Would we create a @PublicMetrics service that contains the CounterBuffers we want to use?

**Comment by dsyer** [comment]
It depends what you want to happen. There is already an instance of `CounterBuffers` you can autowire (but beware the deprecation that might be coming), and it is already part of the public metrics.

**Comment by jtuberville** [comment]
I will still vote for overloading the increment/decrement methods for easier implementation of batch oriented metrics

**Comment by wilkinsona** [comment]
This has been superseded by the planned move to [Micrometer](http://micrometer.io)-based metrics (#9970)
