### ISSUE TITLE
Boot metrics endpoint does not update the sendRate (exponential decay function) when refreshed

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-projects/spring-boot#8803]
Boot version : 1.5.2

The ChannelMetrics interface of Spring integration, defines the sendRate as an exponential moving average that should decay over time. 

When invoking the boot metrics endpoint, that value does not change (in a scenario where there's no messages being published to the channel).

Recently there was a fix from the SI team : https://github.com/spring-projects/spring-integration/commit/fac04aeecee8ab8d46ad23ff4406d3a30e64ad3c that would disable caching of metrics.

Trying to run a boot app with forced updated version of SI to the latest snapshot, still yield the same cached values.

Consumers of this value downstream would now rely on stale information being propagated.

**Comment by dsyer** [comment]
I don't immediately see how this can be fixed in spring boot (the data come directly from a public API aim spring integration), but please send a PR if it can.

**Comment by garyrussell** [comment]
@viniciusccarvalho I tested that fix with a boot app and it worked ok for me - I just tested again - are you sure you override the version ok?

**Comment by viniciusccarvalho** [comment]
I've forced the update of spring-integration-core, spring-integration-amqp, spring-integration-jmx to 4.3.9

I did not build locally however, I was pulling from libs-snapshot repository.

**Comment by viniciusccarvalho** [comment]
Yeah, never mind , even running with U, maven was just caching 4.3.9 with an older build.
