### ISSUE TITLE
Unable to bind nested properties with value from a non-enumerable property source 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#8804]
Failing test case: https://github.com/mbhave/spring-boot/blob/7ddefad796218a0c371aa5a16fcde4c0c61d5964/spring-boot/src/test/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessorTests.java#L361

**Comment by philwebb** [comment]
This test also fails in 1.5.x but we're probably not going to be able to fix it until 2.0

**Comment by mbhave** [comment]
@philwebb This works in 2.0 but is limited to "non-relaxed" resolution of properties for non-enumerable sources. For eg: `foo.bar.baz` will bind but not `foo.BAR.baz`.
