### ISSUE TITLE
Spring-Data-Cassandra Guava issue

### ISSUE THREAD

**Issue by MALPI** [spring-projects/spring-boot#8809]
Consider upgrading datastax driver for spring-data-cassandra to `3.2.0`.

There are two reasons:

1. 2.0.0.BUILD-SNAPSHOT currently raises exception because of incompatibility with guava:

```
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	... 139 common frames omitted
```
Which got solved with the [new release](https://www.datastax.com/dev/blog/datastax-java-driver-3-2-0-released):

> This release is the first one to provide full compatibility with recent Guava versions up to 21.0 inclusive. By default, the driver now uses version 19.0, but any version from 16.0.1 to 21.0 can be used.

2. There were major performance improvements:

> According to our internal benchmarks, this version is also noticeably faster than any previous version in the 3.x series thanks to a few performance improvements, among which the performance boost in a core component of the driver. Users are strongly encouraged to migrate to 3.2.0 as soon as possible to benefit from these.

**Comment by philwebb** [comment]
We're currently aligned with the [master branch of Spring Data Cassandra](https://github.com/spring-projects/spring-data-cassandra/blob/550c1c3da1b1e295b627274970849ea5d2469bd1/pom.xml#L94) which uses 3.1.x.

@mp911de Any plans to upgrade?

**Comment by MALPI** [comment]
@philwebb @mp911de From my point of view it could also be worth to upgrade the master.

**Comment by mp911de** [comment]
We plan to ensure Datastax driver 3.2.0 compatibility for Spring Data Cassandra 1.5.x and upgrading to the latest driver for Spring Data Cassandra 2.0.

We created a ticket to upgrade to Datastax driver 3.2.0 (https://jira.spring.io/browse/DATACASS-424). We weren't able to include the change in our yesterday's release (2.0.0 M2).

**Comment by mp911de** [comment]
Spring Data Cassandra 2.0.x is upgraded to Datastax driver 3.2.0. It remains compatible with driver versions back to 3.0.x.

**Comment by wilkinsona** [comment]
We have upgraded to 3.2.0 in https://github.com/spring-projects/spring-boot/issues/8953
