### ISSUE TITLE
Enhancement: Skip scanning xercesImpl/xml-apis jars with Tomcat

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-boot#8810]
Running Spring Boot 1.5.2 with the embedded Tomcat 8.5.x on Oracle Java 8, I see the following in the logs:

```bash
2017-04-04 17:18:18,934 WARN [org.apache.tomcat.util.scan.StandardJarScanner] - <Failed to scan [file:/Users/Misagh/.m2/repository/xalan/xalan/2.7.2/xml-apis.jar] from
 classloader hierarchy>
java.io.FileNotFoundException: /Users/Misagh/.m2/repository/xalan/xalan/2.7.2/xml-apis.jar (No such file or directory)

...
2017-04-04 17:18:18,934 WARN [org.apache.tomcat.util.scan.StandardJarScanner] - <Failed to scan [file:/Users/Misagh/.m2/repository/xalan/xalan/2.7.2/xercesImpl.jar] from
 classloader hierarchy>
java.io.FileNotFoundException: /Users/Misagh/.m2/repository/xalan/xalan/2.7.2/xercesImpl.jar (No such file or directory)
```

- Should the two JARs listed above, `xml-apis.jar` and `xercesImpl.jar`, be also excluded from scans and listed in `TldSkipPatterns`?
- If so, could I submit a pull request that provides that change?

**Comment by mmoayyed** [comment]
Going to close; Further investigation shows that patterns are available already:


```
        patterns.add("xercesImpl-*.jar");
        ...
        patterns.add("xml-apis-*.jar");
```

**Comment by snicoll** [comment]
@mmoayyed could you please join us on gitter when you have questions like that? That would reduce the noise on the tracker. Thanks!

**Comment by sura2k** [comment]
@snicoll I got a similar error. Would you be able to give a comment about this....whether my workaround would be OK or is there anything I should do to fix it?

Spring Boot `2.1.1.RELEASE` with apache-batik 1.9

Very first log line:
`The Class-Path manifest attribute in C:\Users\ray\.m2\repository\xalan\xalan\2.7.0\xalan-2.7.0.jar referenced one or more files that do not exist: file:/C:/Users/ray/.m2/repository/xalan/xalan/2.7.0/xercesImpl.jar,file:/C:/Users/ray/.m2/repository/xalan/xalan/2.7.0/xml-apis.jar,file:/C:/Users/ray/.m2/repository/xalan/xalan/2.7.0/serializer.jar`

And there are file not found exceptions for all 3 jars stated in the initial log.
Ex:
`java.io.FileNotFoundException: C:\Users\ray\.m2\repository\xalan\xalan\2.7.0\xercesImpl.jar (The system cannot find the file specified)`

No exceptions will throw if the following property is added to the `application.properties`, but the warning is still there.

`server.tomcat.additional-tld-skip-patterns=xercesImpl.jar,xml-apis.jar,serializer.jar,xml-apis.jar`

In `TldSkipPatterns`, those 3 are marked with `-*.jar`. What if they were without `-`, but just `*.jar` ?

**Comment by wilkinsona** [comment]
@sura2k That message is coming from DevTools and is unrelated to TLD scanning. The message is really indicating a problem with Xalan's jar and is probably benign. We've improved things in 2.2 (https://github.com/spring-projects/spring-boot/issues/16883) so that the message is logged rather than being output directly to `System.out`. That will allow you to tune your logging configuration to silence it if you wish to do so.

**Comment by sura2k** [comment]
@wilkinsona thats sounds good. 
But still I have to use this `server.tomcat.additional-tld-skip-patterns` right?

**Comment by wilkinsona** [comment]
Yes, if you want those jars to be skipped during TLD scanning, you will need to configure the appropriate patterns.
