### ISSUE TITLE
Gradle build doesn't produce executable jars (Spring Boot 2.0)

### ISSUE THREAD

**Issue by christianschaible** [spring-projects/spring-boot#8823]
Generating a new spring boot app with spring initializr having the following parameters creates an executable jar (~15MB) which can be compiled by running "mvn clean package" and started by running 'java -jar xxx.jar':
- Maven
- Spring Boot 2.0.0.BUILD-SNAPSHOT
- Reactive Web (spring-boot-starter-webflux)

Generating the same for gradle creates a jar file with file size of ~1KB ("./gradlew clean build") which is not executable on the command line.

It seems that the jar isn't assembled correctly. Nevertheless it's possible to start the application within IntelliJ (2017.1) as a Java-Application.

Adding a "bootJar" task to make it executable has no effect (probably because the jar file isn't packaged properly).

As a developer i would expect that generating the project with spring initializr creates the same jar file independently of the selected build framework.

**Comment by wilkinsona** [comment]
What do you mean when you say:

> Adding a "bootJar" task to make it executable has no effect

The plugin should configure a `bootJar` task for you automatically, i.e. there should be no need to add one. If you want to build the executable jar then you need to run the `bootJar` task and `build` won't do that by default. What happens if you run `./gradlew clean bootJar`?

**Comment by christianschaible** [comment]
Hi Andy. Thank you for your fast feedback. You're right. It's my fault. I just executed "./gradlew clean build" and it created a non executable jar file. Executing "./gradlew clean bootJar" creates the expected executable jar file.

**Comment by wilkinsona** [comment]
I don't think your expectation was unreasonable. Having `build` run `bootJar` was something that I'd hoped to managed to do in the new version of the plugin, but I haven't figured out a satisfactory way to do it by default. I've opened #8824 in order to give it some more thought.
