### ISSUE TITLE
HystrixMetricsStreamServlet not loaded

### ISSUE THREAD

**Issue by jpuzzler** [spring-projects/spring-boot#8826]
Hi Spring team

Question

Trying to simply publish the `/hystrix.stream`endpoint and following the [spring boot hystrix documentation](http://projects.spring.io/spring-cloud/spring-cloud.html#_hystrix_metrics_stream) I noticed that the servlet isn't instantiated at all. I had to add the following to achieve that 

```java
    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
        return new ServletRegistrationBean(new HystrixMetricsStreamServlet(), "/hystrix.stream");
    }
```

I think that the Actuator project should include a Configuration class for that.

Thanks

**Comment by wilkinsona** [comment]
Actuator doesn't know anything about Hystrix. This is a request for Spring Cloud Netflix: https://github.com/spring-cloud/spring-cloud-netflix
