### ISSUE TITLE
Relaxed binding upper case / underscore issue

### ISSUE THREAD

**Issue by qw3ry** [spring-projects/spring-boot#8828]
I have a variable called `partnerID`.
To have a consistent naming in the properties-file I'd like to use `prefix.partner_id` as property name. 

From what I understand (according to the spring boot manual, section 24.7.2) this should work, even though I am using the underscore notation and additionally capitalize arbitrarily. 

Other properties in the same file are bound as expexted. If I change `prefix.partner_id` to either `prefix.partner_i_d` or `prefix.partnerID` this works fine. 
Therefore I'd expect `partner_id` to work as well. 

I am using spring boot 1.5.2.RELEASE.

**Comment by wilkinsona** [comment]
This is working as (currently) designed. Please see #4910 and #5330 for further details.
