### ISSUE TITLE
gradle bootRepackage not found

### ISSUE THREAD

**Issue by mdevgithub** [spring-projects/spring-boot#8832]
Gradle bootRepackage task is not present anymore. We use spring boot 2.0.0.BUILD-SNAPSHOT with the new gradle wrapper 3.4.1 and it looks like this task is removed. 

Running gradlew bootRepackage throws the error:
Task 'bootRepackage' not found in root project 

This can be reproduced by just using Spring Initializr and create a gradle spring boot 2 project and run the command.

**Comment by wilkinsona** [comment]
That's by design. Please see the recent [blog post](https://spring.io/blog/2017/04/05/spring-boot-s-new-gradle-plugin) and the latest snapshot documentation.
