### ISSUE TITLE
spring.freemarker.template-loader-path cannot be set as a List

### ISSUE THREAD

**Issue by cxiaolng** [spring-projects/spring-boot#8842]
Hi,
I'm using spring boot 1.5.2.RELEASE in my project classpath.
And i use freemarker templates to render my view.
```
spring:
  freemarker:
    request-context-attribute: request
    cache: false
    template-loader-path:
      - classpath:/templates/view/
      - classpath:/webapp/view/

```
Above is the configuration of freemarker template
But its not work.
i debug the source code,and found out the reason about why it's not work.

```
public class FreeMarkerTemplateAvailabilityProvider implements TemplateAvailabilityProvider {
	@Override
	public boolean isTemplateAvailable(String view, Environment environment,
			ClassLoader classLoader, ResourceLoader resourceLoader) {
		if (ClassUtils.isPresent("freemarker.template.Configuration", classLoader)) {
			RelaxedPropertyResolver resolver = new RelaxedPropertyResolver(environment,
					"spring.freemarker.");
			String loaderPath = resolver.getProperty("template-loader-path",
					FreeMarkerProperties.DEFAULT_TEMPLATE_LOADER_PATH);
			String prefix = resolver.getProperty("prefix",
					FreeMarkerProperties.DEFAULT_PREFIX);
			String suffix = resolver.getProperty("suffix",
					FreeMarkerProperties.DEFAULT_SUFFIX);
			return resourceLoader.getResource(loaderPath + prefix + view + suffix)
					.exists();
		}
		return false;
	}
}
```
above is the provider of freemarker template's  source code.

```

resolver.getProperty("template-loader-path",
					FreeMarkerProperties.DEFAULT_TEMPLATE_LOADER_PATH);

```
resover will get the property that named template-loader-path from RelaxedPropertyResolver, 
but the property key-value were  'spring.freemarker.template-loader-path[0]=classpath:/templates/view/','spring.freemarker.template-loader-path[1]=classpath:/webapp/view/'  in my debug variables

so, loaderPath  will be set by default value of FreeMarkerProperties.DEFAULT_TEMPLATE_LOADER_PATH;

now i had to change the configuration to a string , so i think it's an issues

**Comment by herau** [comment]
@snicoll If i want to make a PR for this issue, i have to start from the 1.4.x branch ?

**Comment by snicoll** [comment]
Not really Aurélien. The property type is an array of String so that yaml config should work. All lists are represented like that in the doc (there is no other choice with the properties format anyway).
