### ISSUE TITLE
Upgrade to Javax Mail 1.6.0-rc1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8850]

**Comment by rajadilipkolli** [comment]
@wilkinsona Just asking if 1.6.0 Final release is not released by the time Spring-boot 2.0 is out , would we still go with Release candidate?

**Comment by philwebb** [comment]
@rajadileepkolli No, we'd roll back the change. Release versions of Boot will only rely on release versions of other libs.
