### ISSUE TITLE
Autoconfiguration support for Hazelcast IMDG & Jet

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#8863]
Hazelcast consists of four options - an In-Memory Data Grid client and server, and a Jet client and server.

IMDG server works ideally. If there is an `hazelcast.xml` file then a *server* `HazelcastInstance` bean is constructed.

IMDG client is being improved by https://github.com/spring-projects/spring-boot/pull/7469. Ideally there is a `hazelcast-client.xml` file then a *client* `HazelcastInstance` bean is constructed.

This could be extended to include Jet

If there is a `hazelcast.xml` file and Jet classes, then a *server* `JetInstance` bean can be constructed and a *server* `HazelcastInstance` bean taken from inside Jet.

If there is a `hazelcast-client.xml` file and Jet classes, then a *client* `JetInstance` bean can be constructed and a *client* `HazelcastInstance` bean taken from inside Jet.

Sample project https://github.com/neilstevenson/spring-boot-autoconfigure-test shows how they are currently built using Spring Boot 1.5.2.
Ideally, all the `MyConfiguration` classes can be removed in favour of autoconfiguration.

**Comment by neilstevenson** [comment]
The end goal here should be at most one `HazelcastInstance` bean and at most one `JetInstance` bean

Three rules might cover it:

1.  If Jet classes exist, build a Jet client if there is a `hazelcast-client.xml` file or build a Jet server if there is a `hazelcast.xml` file.

2. If the `JetInstance` exists, the `HazelcastInstance` can be extracted from it. 
When the `JetInstance` is a Jet client, the embedded `IMDGInstance` is always an IMDG client.
When the `JetInstance` is a Jet server, the embedded `IMDGInstance` is always an IMDG server.

3. In no Jet classes  are found, build a Imdg client if there is a `hazelcast-client.xml` file or build a Imdg server if there is a `hazelcast.xml` file.

**Comment by philwebb** [comment]
See also #7469

**Comment by vpavic** [comment]
IMO Spring Boot should not jump into this just yet as Hazelcast Jet is still a fresh project standing at version `0.3.1` ATM.

Project's [milestones page](https://github.com/hazelcast/hazelcast-jet/milestones) offers some insight, with `0.4` already introducing a significant change by shading Hazelcasts JARs (both server and client) into Jet itself (see hazelcast/hazelcast-jet#367). I guess more changes like that are likely until the project reaches a stable `1.0` release.

Other than that, Hazelcast Jet seems to target a similar space as [Spring Cloud Data Flow](http://cloud.spring.io/spring-cloud-dataflow/) which makes me wonder if Spring Boot is natural place for Jet integration (also see [the list of Jet's artifacts](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.hazelcast.jet%22)).

**Comment by snicoll** [comment]
@vpavic thank you for your feedback, much appreciated. I was about to write the same thing but without all those references!

@philwebb 2.0.0.M1 isn't the right milestone for this. We absolutely need support for the `hazelcast-client` and @vpavic did most of the work already anyway. But we can revisit our auto-config later, even in a future release.

**Comment by neilstevenson** [comment]
I'll have a go at fixing this myself

**Comment by neilstevenson** [comment]
Fix ready, https://github.com/spring-projects/spring-boot/pull/13312

**Comment by neilstevenson** [comment]
@snicoll  Updated as request, a single commit PR to master - https://github.com/spring-projects/spring-boot/pull/13317

**Comment by neilstevenson** [comment]
Seems to have test failures, but the project as a whole doesn't compile on Mac 10.13

**Comment by neilstevenson** [comment]
Found the reason - https://github.com/spring-projects/spring-boot/issues/13326, environmental. Will work around.

**Comment by philwebb** [comment]
Closing in favor of PR #13317
