### ISSUE TITLE
Create new ConfigurationProperties Binder

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8868]
A general placeholder for the new configuration properties binder work.

**Comment by mbhave** [comment]
- [ ] _ in system env maps to empty prefix
- [ ] String to Resource conversion
- [ ] Nested validation with @NotNull
- [ ] No setter for ResourceServerProperties clientId 
- [ ] Exception, error messages and failure analyzer
- [ ] Map Binder key values should be preserved
- [ ] HikariDataSourceConfigurationTests.testDataSourceGenericPropertiesOverridden
- [ ] XADataSourceAutoConfigurationTests.createFromClass

**Comment by philwebb** [comment]
The `String` -> `Resource` conversion was previously handled by `ResourceEditor`. We need to consider if we should support `PropertyEditorRegistry` and `BeanUtils.findEditorByConvention(requiredType)`

**Comment by mbhave** [comment]
Nested properties will only be validated if there is a bound value or they have an `@Valid` annotation.

**Comment by snicoll** [comment]
Wondering if #6911 can be fixed differently with the new implementation.
