### ISSUE TITLE
Gradle plugin forces to use outdated version of dependencies

### ISSUE THREAD

**Issue by ghostbuster91** [spring-projects/spring-boot#8870]
Hi, I am using spring boot gradle plugin version `1.5.2.RELEASE`.
I am trying to use mockito-kotlin in test in version `1.4.0`, which internally uses mockito-core version `2.7.21`.
Unfortunately after I apply `org.springframework.boot` plugin it downgrades mockito-core version to `1.10.19` which it should not do IMO. 

The workaround is quite easy:
Just specify your dependency explicit eg. 
`testCompile (group: 'com.nhaarman', name: 'mockito-kotlin', version: '1.4.0')`

Here is sscce:
https://github.com/ghostbuster91/spring-boot-gradle-plugin-issue-sscce/blob/master/build.gradle

**Comment by wilkinsona** [comment]
This is working as designed. Spring Boot is built and tested against specific versions of various dependencies, and those versions are used by default thanks to its dependency management for both Maven and Gradle. If you want to use another version, you can explicitly declare the dependency with a version (as you have done) or you can [override the dependency management](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions). The latter is the preferred approach.
