### ISSUE TITLE
Elasticsearch Client not autoconfigured in 1.5.2 

### ISSUE THREAD

**Issue by mknutty** [spring-projects/spring-boot#8893]
When including Spring Data Elasticsearch Starter and "autowiring" org.elasticsearch.client.Client (via annotation or constructor), the following is logged:
"...required a bean of type 'org.elasticsearch.client.Client' that could not be found.
	- Bean method 'elasticsearchClient' not loaded because @ConditionalOnClass did not find required classes 'org.springframework.data.elasticsearch.client.TransportClientFactoryBean', 'org.springframework.data.elasticsearch.client.NodeClientFactoryBean'"

To test this, create a spring boot app with Spring Data Elasticsearch and Autowire the Client class in the Application Class.

**Comment by mknutty** [comment]
This does work in 1.5.1.

**Comment by snicoll** [comment]
@mknutty my best guess is the a jar got corrupted when you upgraded to `1.5.2` and the VM can't open the classes. A sample app works for me. If you can still reproduce after clearing your maven cache, please attach a sample that we can run ourselves.

**Comment by mknutty** [comment]
Thx!. I will try. I did create another project but i didnt try another machine.

**Comment by mknutty** [comment]
That was it. I needed to delete repo\org\springframework\data\spring-data-elasticsearch\2.1.1.RELEASE
