### ISSUE TITLE
Support testing Redis connections in JedisPoolConfig

### ISSUE THREAD

**Issue by jwbennet** [spring-projects/spring-boot#8894]
It would be really useful if the generation of the `JedisPoolConfig` in `RedisAutoConfiguration.RedisConnectionConfiguration#jedisPoolConfig` would allow for a few more boolean properties to configure how connections in the pool are tested before/after use:

* `testOnBorrow`
* `testOnConnect`
* `testOnReturn`
* `testWhileIdle`

I think all that would be involved would be adding properties for these to the `RedisProperties` class and then update the `jedisPoolConfig` method to use them appropriately.  I would be happy to submit a PR to do that if it would be worthwhile.

**Comment by philwebb** [comment]
They seem like worthwhile additions and a PR would be most welcome.

**Comment by jwbennet** [comment]
Great! I was out at a conference this week but I'll get something worked up and submitted over the weekend.  I was hoping this change could make it into 1.5.x if possible.  Would I submit the PR against master and that branch or just master?

**Comment by philwebb** [comment]
Just the 1.5.x branch please. I think a small enhancement like this makes sense on 1.5.x and we'll forward merge it to master to there's no need for a second PR.

**Comment by jwbennet** [comment]
I missed referencing this issue in my commit message, but I submitted #8975 to correct this issue.

**Comment by philwebb** [comment]
Closing in favor of PR #8975

**Comment by snicoll** [comment]
As the PR has been declined (see comments for more details) reopening to see how that can be addressed differently.

**Comment by snicoll** [comment]
As of #9510 there is a `JedisClientConfigurationBuilderCustomizer` that you can implement to set those properties and override things that were auto-configured. I've added a note in the documentation about this.
