### ISSUE TITLE
Missing spring.datasource.xa.* keys in the appendix

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#8895]
Spring boot version: 1.5.2.RELEASE

In appendix A of the documentation, there is a section spring.datasource.* properties. These are mapped to [DataSourceProperties](https://github.com/spring-projects/spring-boot/tree/v1.5.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceProperties.java) and [DataSourceAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/v1.5.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration.java).

I believe that the documentation here is not complete, as the DataSourceProperties also has an inner class called Xa, which allows for setting provider-specific properties. The documentation should be updated to reflect the possibility to use this Xa inner class for properties. Or am I unknowingly mistaken perhaps?

**Comment by snicoll** [comment]
Funny, I was reviewing that yesterday and was about to improve it. Thanks for creating an issue for me ;-)
