### ISSUE TITLE
Confusing cmd line argument processing in multi-context Spring boot app

### ISSUE THREAD

**Issue by lukas-krecan-lt** [spring-projects/spring-boot#8898]
If you have Spring Boot project with multiple contexts like this
    
```java
    new SpringApplicationBuilder()
        .parent(RootCtx.class)
        .child(Child1.class)
        .sibling(Child2.class)
        .run(args);
```

command line arguments (`args`) are applied only in last Spring context `Child2.class`. For example if you specify `--spring.config.location` command line argument it gets used only in part of the app which is surprising and leads to hours of debugging. It would be nice to 

1. Mention it in JavaDoc of child or sibling method
2. Allow specifying args before child contexts are created

**Comment by philwebb** [comment]
Just looking at the `SpringApplicationBuilder` and it appears that the arguments should be applied to the parent as well. The javadoc states:

>  The parent is run first with the same arguments if has not yet been started.

There's a `configureAsChildIfNecessary` which should start the parent with the same args.

Do you have a sample application that you can share that shows the problem?

**Comment by lukas-krecan-lt** [comment]
The trouble is in the sibling method. Which says "_Create a sibling application (one with the same parent). A side effect of calling this method is that the current application (and its parent) are started._" So when I call sibling, it starts parent but arguments are set in "run" method which has not been called yet.

**Comment by lukas-krecan-lt** [comment]
If you wish, I can prepare test app.

**Comment by philwebb** [comment]
My mistake, I was just looking at the `.parent`, `.run` methods.
