### ISSUE TITLE
Could not build Spring Boot on Windows10 (Error 0x80010135: Path too long)

### ISSUE THREAD

**Issue by mattcsully** [spring-projects/spring-boot#8901]

**Comment by mattcsully** [comment]
This does not support Windows 10.  Spring Boot ERRORS Windows Error 0x80010135: Path too long
EmbeddedServletContainerJarDevelopmentIntegrationTests.java
EmbeddedServletContainerPackagingIntegrationTests.java
EmbeddedServletContainerWarDevelopmentIntegrationTests.java
EmbeddedServletContainerWarPackagingIntegrationTests.java
DependencyManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFailsToResolve.gradle

**Comment by philwebb** [comment]
Are you trying to build the project? What's the root checkout directory that you're using? We've previously had Windows CI builds that passed so I'm wondering if this is something specific to your environment.

**Comment by mattcsully** [comment]
root checkout was https://github.com/spring-projects/spring-boot/
Thanks

**Comment by SolaKun** [comment]
```
In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters.
```
You can disable it in some ways.

**Comment by mattcsully** [comment]
Thanks SolaKun.  the LongPathsEnabled is already set to 1
I tries a one letter directory work around and now get the 5 errors and 3 warnings I guess others experience:
Using kotlin incremental compilation
:spring-web:compileJava
C:\s\spring-web\src\main\java\org\springframework\http\codec\DecoderHttpMessageReader.java:93: warning: [deprecation] mapError(Function<? super Throwable,? extends Throwable>) in Flux has been deprecated
                                .mapError(this::mapError);
                                ^
  where T is a type-variable:
    T extends Object declared in class Flux
C:\s\spring-web\src\main\java\org\springframework\http\codec\DecoderHttpMessageReader.java:103: warning: [deprecation] mapError(Function<Throwable,? extends Throwable>) in Mono has been deprecated
                                .mapError(this::mapError);
                                ^
  where T is a type-variable:
    T extends Object declared in class Mono
error: warnings found and -Werror specified
C:\s\spring-web\src\main\java\org\springframework\http\codec\EncoderHttpMessageWriter.java:102: warning: [deprecation] mapError(Function<? super Throwable,? extends Throwable>) in Flux has been deprecated
                                .mapError(this::mapError);
                                ^
  where T is a type-variable:
    T extends Object declared in class Flux
C:\s\spring-web\src\main\java\org\springframework\http\server\reactive\ReactorHttpHandlerAdapter.java:60: error: cannot find symbol
                                .switchOnError(ex -> {
                                ^
  symbol:   method switchOnError((ex)->{ lo[...](); })
  location: class Mono<Void>
C:\s\spring-web\src\main\java\org\springframework\http\server\reactive\RxNettyHttpHandlerAdapter.java:69: error: cannot find symbol
                                .switchOnError(ex -> {
                                ^
  symbol:   method switchOnError((ex)->{ lo[...](); })
  location: class Mono<Void>
C:\s\spring-web\src\main\java\org\springframework\web\server\adapter\HttpWebHandlerAdapter.java:79: error: cannot find symbol
                                .switchOnError(ex -> {
                                ^
  symbol:   method switchOnError((ex)->{ if[...](); })
  location: class Mono<Void>
C:\s\spring-web\src\main\java\org\springframework\web\server\handler\ExceptionHandlingWebHandler.java:102: error: cannot find symbol
                        completion = completion.switchOnError(ex -> handler.handle(exchange, ex));
                                               ^
  symbol:   method switchOnError((ex)->hand[...], ex))
  location: variable completion of type Mono<Void>
5 errors
3 warnings
:spring-web:compileJava FAILED
:spring-web:copyMainKotlinClasses SKIPPED

**Comment by snicoll** [comment]
@mattcsully can we please focus? That's the build of the Spring Framework.

**Comment by mattcsully** [comment]
Yes, building the Spring Framework is what I had been attempting.

**Comment by snicoll** [comment]
This is the spring boot tracker. Your original issue is about building Spring Boot. That's what I meant by focus.

**Comment by whench18** [comment]
hello if there is any problem or issue that involves a path too long case, I suggest you try our long path tool, this will solve your problem and will make it all easy for you. thanks.

**Comment by philwebb** [comment]
I'm closing this issue since it seems you're trying to build Spring Framework and not Spring Boot. If you're having trouble build Spring Boot, please provide details of the exact OS version, local checkout path and the commands that you typed.
