### ISSUE TITLE
Unhandled reactor.core.Exception OverflowException: Queue is full?!

### ISSUE THREAD

**Issue by georgi-staykov** [spring-projects/spring-boot#8908]
While I'm playing around with the new reactive features in Spring Boot v2.0.0.BUILD-SNAPSHOT  I have noticed that when I multiple time force close the connection to endpoint like this:
```
    @GetMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE, value = "/events")
    public Flux<Event> getEvents()
    {
        return Flux.from(new Publisher<Event>() {
            @Override
            public void subscribe(Subscriber<? super Event> subscriber) {
                while (true) {
                    try {
                        new Thread().sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    subscriber.onNext(new Event(1, new Date()));
                }
            }
        });
    }
```
Spring throws: "reactor.core.Exceptions$BubblingException: reactor.core.Exceptions$OverflowException: Queue is full?!"   and after that when I call the endpoint again it freeze.  Here I've created a repo https://github.com/georgi-staykov/reactive-demo  where you can find example code and video that shows the bug.

**Comment by philwebb** [comment]
It's likely that we'll need help with this one from either the WebFlux team or the Reactor team. /cc @bclozel @rstoyanchev @smaldini.

**Comment by snicoll** [comment]
That's definitely a non Spring Boot issue anyway and that blocking code is "unusual". Please join the `#reactor` room on gitter if you have question about using flux and mono. You can also create a new thread on stackoverflow.

**Comment by georgi-staykov** [comment]
I don't know where the bug is ( spring or reactor)  and what is "unusual" but the fact is that the endpoint (that spring exposes) is freezing which is not acceptable in any circumstances in my opinion.

**Comment by snicoll** [comment]
I don't know either but it's not in spring boot and freezing a thread in such environment is just wrong.

**Comment by georgi-staykov** [comment]
Ok this is just sample where I'm simulating work with thread sleep. I've reproduced the problem with he following code too:
```
@GetMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE, value = "/events")
    public Flux<Event> getEvents()
    {
        return Flux.from(new Publisher<Event>() {
            @Override
            public void subscribe(Subscriber<? super Event> subscriber) {
                while (true) {
                    subscriber.onNext(new Event(1, new Date()));
                }
            }
        });
    }
```

**Comment by rstoyanchev** [comment]
There are many problems with this sample. To start it's not a Reactive Streams compliant since it calls onNext before calling onSubscribe and completely ignores back-pressure by pushing items without a corresponding request for items from the Subscriber (i.e. the server). It also blocks the current thread which will quickly kill your server (with a few concurrent users) that's running event.

The whole point of using Reactor `Flux` is that you don't have to implement `Publisher` from scratch. Use `Flux#create` or for this scenario use `Flux#interval`.
