### ISSUE TITLE
Refine SpringApplication get/set sources 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8910]
The current logic is a little confusing and will be hard to implement with our new binder. Calling `get` returns the existing sources (from the constructor), calling `set` adds to the collection rather than replaces it. I think it would be better if `getSources()/setSources()` were used for additional sources and we change the constructor use to mean primary sources (that can't change).

**Comment by snicoll** [comment]
Does that mean the existing binder does handle it "properly"? If so, maybe others are relying on that feature right now in custom `ConfigurationProperties`.

**Comment by philwebb** [comment]
It's a very much an edge case I think.
