### ISSUE TITLE
Starter for testing reactive web applications

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#8914]
I think it would come in handy if there was a `spring-boot-starter-[webflux|reactive]-test` (or alike), including the `io.projectreactor.addons:reactor-test`

**Comment by philwebb** [comment]
We should consider this when we get closes to RC. A starter with just one dependency is a bit light, but on the other hand, it does help with discoverability.

**Comment by snicoll** [comment]
And start.spring.io should flip the switch based on the application nature. I have no idea how I'll do that but we should if we pursue this.

**Comment by joshiste** [comment]
>it does help with discoverability.
That was what I had in mind. The moment I filed thist issues, was the moment when I've had to look up the right jar myself.

**Comment by snicoll** [comment]
Reactor-test is automatically included when a project is generated on start.soring.io with webflux. This is not perfect but I wonder if that's not good enough for now?

**Comment by hantsy** [comment]
I found my issues( https://github.com/spring-projects/spring-boot/issues/10368 ) was closed due it is duplicated with this one.

But I think it is a little different. The `io.projectreactor.addons:reactor-test` does not include https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/http/client/HttpClient.java which is from `reactor-netty`.  

If I do not use Spring Boot, I have added `reactor-netty` or `reactor-test` into test scope explicitly, but `WebTestClient` is part of `spring-test`, why not add the dependency to `spring-test`.

(PS: I took some time to accept `WebTestClient`, why it is not `TestWebClient`, there are several `Test` prefix fixtures in `spring-test`, `WebTestClient` is an exception）

**Comment by bclozel** [comment]
`spring-test` provides many features on top of other testing libraries.
Look at the [list of optional dependencies there](https://github.com/spring-projects/spring-framework/blob/master/spring-test/spring-test.gradle), I'm sure you wouldn't like to have all of those on your classpath by default.

**Comment by hantsy** [comment]
@bclozel OK, understood it. Skip my issues, I added it explicitly now. Thanks.

**Comment by bclozel** [comment]
Now that Spring WebFlux is well integrated with Spring Boot, we don't feel the need to create a specific test starter for this use case and start.spring.io is the best place for now to add the reactor-test dependency.
