### ISSUE TITLE
Remove ConfigurationPropertiesBindingPostProcessor @Autowired setters

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8918]
`ConfigurationPropertiesBindingPostProcessor` has some unusual autowired setters that are "self injected". The `getDefaultConversionService` calls `applicationContext.getAutowireCapableBeanFactory().autowireBean(this)` to inject them.

Interestingly they don't work if called in `afterPropertiesSet` which makes me a little suspicious that things aren't working more by luck than design.

We'll probably need to revisit `ConfigurationPropertiesBindingPostProcessor` again anyway to support interface based properties.

**Comment by snicoll** [comment]
See also #8344

**Comment by snicoll** [comment]
Actually, Duplicate of #8344
