### ISSUE TITLE
Mistake in Gradle plugin devtools documentation

### ISSUE THREAD

**Issue by emersonf** [spring-projects/spring-boot#8921]
In [4.3.2](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/gradle-plugin/reference/#packaging-executable-configuring-excluding-devtools),

> If you want to include Devtools in your archive set the excludeDevtools property to true:

should read

> If you want to include Devtools in your archive set the excludeDevtools property to *false*:

**Comment by snicoll** [comment]
Good catch, thanks for reporting it!
