### ISSUE TITLE
Add support for reactive Spring Data Couchbase

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#8925]
Spring Data Kay M2 announces support for reactive repositories to Couchbase

**Comment by philwebb** [comment]
Do we need a new starter or is the reactive support just not part of the existing Spring Data Couchbase JAR?

**Comment by snicoll** [comment]
@philwebb we have starter for the data reactive effort already (see mongodb). The starter needs to bring the right driver and should pull reactor as well.

**Comment by philwebb** [comment]
Closing in favor of PR #10812
