### ISSUE TITLE
LOG_FILE_IS_UNDEFINED log file is being created in boot 1.5.2

### ISSUE THREAD

**Issue by pksinghus** [spring-projects/spring-boot#8931]
Adding a dependency on **spring-cloud-starter-feign** in a spring boot project results in an additional log file being generated with the name "LOG_FILE_IS_UNDEFINED".

Remove the following dependency and the file is no longer generated -

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
            <version>1.3.0.RELEASE</version>
        </dependency>

Spring boot version is 1.5.2.RELEASE

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath/> 
	</parent>

Sample project is attached.
[app.zip](https://github.com/spring-projects/spring-boot/files/930732/app.zip)

**Comment by snicoll** [comment]
Can you please create an issue in the [Spring Cloud Netflix issue tracker](https://github.com/spring-cloud/spring-cloud-netflix/issues) please? Feign isn't handled here. We can take it here if it turns out to be a core (boot) issue.
