### ISSUE TITLE
Cannot use ddl-auto=validate with Hibernate and Flyway

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#894]
Hibernate wants to validate the `DataSource` before the migrations are executed.

**Comment by fedecz** [comment]
Hi there, I'm having the same issue. Hibernate DDL validation comes before the flyway migration. Has this been solved? I see the issue is closed already, but I do not see any comment about the solution. Is there any workaround?
Cheers

Fede

**Comment by philwebb** [comment]
@fedecz this specific issue was solved some time ago. Are you using the latest 1.2.x version of Spring Boot? Perhaps you've found an edge case that we haven't covered. If so, please open a new issue. Ideally with a sample project that replicates the problem.

**Comment by piotrturski** [comment]
@fedecz i used a workaround and wrote about it here: http://blog.piotrturski.net/2014/05/spring-boot-dependson-is-not-enough.html

**Comment by fedecz** [comment]
Thanks for the comments, I've finally managed to solve it based on the comment by @piotrturski.
Thank you all!

Fede

**Comment by eepstein** [comment]
Using 1.4.3.RELEASE of spring boot I see these annotations in the 
org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration class:

@AutoConfigureAfter({ DataSourceAutoConfiguration.class,
		HibernateJpaAutoConfiguration.class })

A first step would seem to be to change that to:

@AutoConfigureAfter({ DataSourceAutoConfiguration.class })

Yes?

**Comment by snicoll** [comment]
@eepstein this issue is closed. If you believe you've found a bug, raise another issue (Not sure I get your feedback, this is like that since the very beginning. Do not mix configuration order and runtime order).

**Comment by eepstein** [comment]
So, two parts:

1. I may have mixed up runtime order and configuration order.

2. Overall it's still an issue: at runtime Hibernate tries to do the validation before Flyway had a chance to migrate the database, so the validation fails.  The proposed work-arounds on this page haven't worked.  So... I'd say. in my experience, it is still an issue.

Thanks!

**Comment by dsyer** [comment]
If you believe there is an issue, please open a new ticket. Comments on old, closed issues, where clearly work was done to address the problem is just noise.

**Comment by eepstein** [comment]
I see.  Will do.
