### ISSUE TITLE
Investigate rocker

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8940]
Looks like an interesting templating engine: https://github.com/fizzed/rocker

**Comment by rajadilipkolli** [comment]
+1 very interesting

**Comment by volyx** [comment]
+1

**Comment by raderio** [comment]
It's like in Play framework!

**Comment by checat** [comment]
Will it fit Spring Boot's ModelAndView? I assume, not very well. Roker expects typed positional parameters to a compiled templates, where Model provides Map-like container for data.
Of course, rocker template could be called directly from controller.

**Comment by bendem** [comment]
> Will it fit Spring Boot's ModelAndView? I think, not very well. Roker expects typed positional parameters to a compiled template, where Model provides Map-like container for data.

Actually, it supports both, see [this link](https://github.com/fizzed/rocker#flavor-2-dynamic-interface-dynamic-rendering).

> Of course, rocker template could be called directly from controller.

That's what I've been doing, it's actually very easy to return the `RockerModel` and register an `HttpMessageConverter` to do the job (example [here](https://gist.github.com/bendem/8675b7ca856cdab6c208ff6528850f7f)).

**Comment by raderio** [comment]
https://github.com/linux-china/rocker-template-demo

**Comment by nishantraut** [comment]
Hi @philwebb Can i add rocker template example under spring-boot-sample-rocker-template, can you guide on this. Thanks

**Comment by nishantraut** [comment]
Hi @philwebb Someone already experimented https://github.com/linux-china/rocker-template-demo
Please let me know any further improvement is needed.

**Comment by danielmenezesbr** [comment]
I created a fork ([template-benchmark fork](https://github.com/danielmenezesbr/template-benchmark/tree/update-frameworks)) with updated popular Java template engines:

 * Rocker 1.2.0
 * Pebble 3.0.6
 * Mustache ([spullara](https://github.com/spullara/mustache.java) implementation) 0.9.5
 * Freemarker 2.3.28
 * Velocity 2.0
 * Thymeleaf 3.0.11.RELEASE
 * Trimou 2.5.0.Final
 * Groovy Template 2.5.4
 * Mustache ([samskivert](https://github.com/samskivert/jmustachet) implementation) 1.14

Result:
![image](https://raw.githubusercontent.com/danielmenezesbr/template-benchmark/update-frameworks/results.png)

**Comment by wagnerluis1982** [comment]
Hi, I'm wondering about what the goals behind this issue. Are they not already reached? If not, what is missing?

**Comment by philwebb** [comment]
@wagnerluis1982 I don't think anything has really been looked at yet. I raised the issue a couple of years ago just as a templating technology that we should keep our eye on to see how many people adopt it. In hindsight, I'm not sure that we should continue with this one. I've put it on hold for now and we'll discuss it as a team.

**Comment by philwebb** [comment]
After some discussion we feel like it would be better for a external project to exist for Rocker Spring support. If such a project existed, we could consider auto-configuration support in Spring Boot.
