### ISSUE TITLE
Cache the result of Spring Boot initialization to speed up Cloud execution

### ISSUE THREAD

**Issue by ludoch** [spring-projects/spring-boot#8942]
On my (speedy MacBook), starting a simple SpringBoot application can take  5 seconds or more (see this log)
Start:
[INFO] 2017-04-19 16:53:50.794  INFO 1801 --- [           main] o.s.boot.SpringApplication               : 
...
end:
[INFO] 2017-04-19 16:53:55.412  INFO 1801 --- [           main] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'appengine-spring-boot': initialization completed in 23 ms

I am an engineer working for Google App Engine, and the new Java8 Standard App Engine Runtime can now support out of the box SpringBoot Applications with access to the App Engine APIs and the Google Cloud APIs!
Using a Mac for development is fast enough. But when a customer will deploy the Spring Boot Application to the Google Cloud App Engine environment, they will prefer fast boot of the instances running in the Cloud. To put things in perspective, the simplest instance for App Engine is a F1 which is more or less 600+MHz and 128Mb of Ram (yes, less than your phone, but we can scale 1000s and more of them for a single application/version).
The App Engine runtime by design has a boot limit of 60 seconds, so if the app cannot respond in less than 60 seconds, it is considered unhealthy. Some customers will hit this 60 seconds boot time with SpringBoot initialization.

For Java EE Servlet 3.1 annotations, the App Engine team worked with Jetty Webtide to deliver an efficient prescan process for Servlet/Filter annotations, and we are using this optimization in our local SDK to pre stage completely resolved Web Apps.
You can see the performance improvement we got with this step in a blog : https://webtide.com/jetty-9-quick-start/
and this is giving a great performance gain for our customers.

I am wondering if it would be possible to have a similar mechanism for SpringBoot:
1/ the developer would run locally the application
2/ The application would store in an area (inside the Web App?) the result of the SpringBoot initialization (which includes the cached information from a lot of Jars scanning)
3/ SpringBoot would have a way to use the pre calculated information
4/ Google App Engine Tooling would provide a way to configure at deployment time to the Google Cloud a pre-wired SpringBoot Application that would boot much faster in the the Cloud and would scale to a massive number of instances (from 0 to millions).

Maybe the idea has been looked at before, and pointers would be welcome.
Thanks!

**Comment by ludoch** [comment]
Also, for the record, the App Engine team did a whitepaper (in 2012, so maybe completely obsolete now) for optimizing Spring Framework for App Engine Applications:

https://cloud.google.com/appengine/articles/spring_optimization

If there are better articles on the subject, we can try to see how they can be applied to the App Engine specific context of a massively scalable system of very small/lightweight instances.

**Comment by snicoll** [comment]
It looks like you have determined that something (classpath scanning?) is taking a significant amount of time in the 5 sec that you are referencing. Do you actually have some details about this? 

We had a look to classpath scanning and startup optimization in general as part of Spring Framework 5 and that work determined that classpath scanning is very fast already and creating a pre-computed list of candidates does not radically speed things up globally.

I have plans to integrate that work in Spring Boot as well but I'd like to know more first. I know classpath scanning is an issue in the previous version of GAE (re: your whitepaper). Have you done some tests with the current version of the platform?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
