### ISSUE TITLE
Look at unifying WebFluxAnnotationAutoConfiguration and WebMvcAnnotationAutoConfiguration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8945]
Copy/Paste code that could perhaps be extract. For example the ValidatorPostProcessor

**Comment by mbhave** [comment]
@philwebb have the names changed? couldn't find these.

**Comment by philwebb** [comment]
Yeah, I think 9981ae687499e13449a6447a4a9c170af218f93c did one (not sure about the other). Try `WebMvcAutoConfiguration` and `WebFluxAutoConfiguration`

**Comment by mbhave** [comment]
Thanks. The `ResourceChainCustomizerConfiguration` might be a good candidate.

**Comment by mbhave** [comment]
actually I'm not sure if there is any duplication anymore.

**Comment by snicoll** [comment]
I agree, I think we're fine now.
