### ISSUE TITLE
Unify versions used in integration tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8947]
The loader and maven plugin `/it` folders have `pom.xml` files pulling in old dependencies. This triggers a fresh download each time. It would be nice if we could use the versions from the dependencies pom somehow so that they don't drift and only the local `/.m2` folder is used.

**Comment by snicoll** [comment]
Actually this is way worse since master build with Spring Framework 4.1 something for some tests. I am trying to get a build with JDK9 and it took me a while before I figure out where that was coming from
