### ISSUE TITLE
Cache-control headers within the controller are ignored with spring security

### ISSUE THREAD

**Issue by czubin** [spring-projects/spring-boot#8949]
Bug report:

Since spring boot 1.5 the 'Cache-control' headers can no longer be set within a controller.
Using ResponseEntity.cacheControl().

The test and code below works under spring boot 1.4.5.

Security configuration:
```java
@Configuration
@EnableWebSecurity
public class SpringSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
    }
}
```

Controller: 
```java
@Controller
public class ResourceEndpoint {
    @GetMapping("/users/{name}")
    public ResponseEntity<UserDto> getUser(@PathVariable String name) {
        return ResponseEntity
          .ok()
          .cacheControl(CacheControl.maxAge(60, TimeUnit.SECONDS))
          .body(new UserDto(name));
    }
}
```

Test:
```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = AppRunner.class)
public class ResourceEndpointIntegrationTest {
    @Test
    public void givenServiceEndpoint_whenGetRequestForUser_shouldResponseWithCacheControlMaxAge() {
        given().when().get(getBaseUrl() + "/users/Michael").then().contentType(ContentType.JSON).and().statusCode(200).and().header("Cache-Control", "max-age=60");
    }
    private String getBaseUrl() {
        return String.format("http://localhost:%d", serverPort);
    }
}
```

**Comment by mbhave** [comment]
@czubin This seems to be happening because of this change in Spring Security. https://github.com/spring-projects/spring-security/commit/57d7ad05f9c8a3e177a97cbde5aa094f8179941f. Previously, as can be seen in this commit, https://github.com/spring-projects/spring-security/commit/242b831f20c11171975c1e2bdd50c9ae1cdbf445, Spring Security would only write the Cache-Control header if it was not set. 

@philwebb This doesn't seem like a Boot issue,  but more like something for Spring Security or Spring MVC. WDYT?

**Comment by wilkinsona** [comment]
I think this should have been fixed by https://github.com/spring-projects/spring-security/commit/168f4b8f70941ea1bc58656b4b54af284f4f0a82 which is in Spring Security 4.2.2 (the default version in Boot 1.5.2).

@czubin What version of Spring Security are you using?

**Comment by czubin** [comment]
@wilkinsona We are currently using the latest(1.5.2).

It seems to me that previously the headers were written after completion of the filterchain. Which caused problems with users who flushed the response.

I'm going to use a workaround as specified in https://github.com/spring-projects/spring-security/issues/2953

**Comment by philwebb** [comment]
We think this duplicates #4199 so I'll close the issue for now. If you can create a sample that reproduces it with Spring Security 4.2.2 and Boot 1.5.3 please attach it and we'll re-open.

**Comment by czubin** [comment]
@philwebb Okay, I'll make an issue with spring-security project. 1.5.3 has the same regression.

**Comment by philwebb** [comment]
@czubin Thanks, can you paste a link to the issue that you create here so that we have a future breadcrumb trail.

**Comment by czubin** [comment]
Made a new ticket https://github.com/spring-projects/spring-security/issues/4307
