### ISSUE TITLE
Warn entry with Web MVC or WebFlux validator

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8951]
Any app where the validation auto-configuration kicks in now has an additional warning

```
o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'mvcValidatorAliasPostProcessor' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
```

**Comment by wilkinsona** [comment]
This is a tricky one and the warning message is misleading. `mvcValidatorAliasPostProcessor` is already static and, as far as I can tell, this warning will always be generated if a `BeanDefinitionRegistryPostProcessor` is configured via a `@Bean` method irrespective of it being `static` or not. ``PostProcessorRegistrationDelegate` creates the singleton on line 100 and then makes the call the triggers the warning from `ConfigurationClassPostProcessor` later in the same method (line 125).

The other `BeanDefinitionRegistryPostProcessor` implementations that we have are added to the context via an `ApplicationContextInitializer` and a call to `addBeanFactoryPostProcessor` but that's not a (simple at least) option here as we need the registration to be conditional.

**Comment by philwebb** [comment]
Thanks for the hint @jhoeller. I went with an `@Import` in the end. The result is better than the post processor.
