### ISSUE TITLE
Current Spring Boot Gradle plugin documentation points to not available plugin version

### ISSUE THREAD

**Issue by pioterj** [spring-projects/spring-boot#8952]
Instructions at http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-including-the-gradle-plugin don't work because version 1.5.3 of the plugin is not published on Gradle Plugin Portal yet. The latest published version is 1.5.2. See https://plugins.gradle.org/plugin/org.springframework.boot.

**Comment by wilkinsona** [comment]
Thanks, but you caught things in an intermediate state will the 1.5.3 release was being staged. It failed final testing so it hasn't been promoted to external repositories, Maven Central, etc. The docs should point to 1.5.2 again now.
