### ISSUE TITLE
JsonAutoDetect cannot be resolved to a type when upgrading to Spring Boot 1.5.x

### ISSUE THREAD

**Issue by Rankel** [spring-projects/spring-boot#8963]
Hello,

I'm not sure if I'm at the right place to ask this, I can't upgrade to version to 1.5 or more because it says "JsonAutoDetect cannot be resolved to a type" when i use this annotation.

It does the same thing for `@JsonIgnoreProperties` and `@JsonCreator`.

**Comment by philwebb** [comment]
That sounds like you're either missing the `jackson-annotations` jar or you have a corrupt copy in your local Maven/Gradle cache. If you're using Maven try `mvn dependency:purge-local-repository` to clear out any corrupt jars and `mvn dependency:tree` to check you're actually pulling the in jackson dependency.

I'll close this one for now, but if you think it's a genuine bug please provide a sample application that shows the issue.
