### ISSUE TITLE
JSR validator bean missing if a custom Spring Validator bean is present

### ISSUE THREAD

**Issue by oyvindhorneland** [spring-projects/spring-boot#8976]
This problem occurred after upgrade from Spring Boot 1.5.2 to 1.5.3. 

I have some custom Spring validator beans for Spring Data REST while also relying on standard JSR validator in other parts of the application. 

After upgrading from Spring Boot 1.5.2 to 1.5.3 there is no longer a JSR validator bean present.

Error:
```
Bean method 'defaultValidator' in 'DefaultValidatorConfiguration' not loaded because @ConditionalOnMissingBean (types: javax.validation.Validator,org.springframework.validation.Validator; SearchStrategy: all) found beans 'beforeSaveUserValidator', 'beforeCreateGroupValidator', 'beforeCreateUserValidator'
```

Debug auto configuration:
```
DefaultValidatorConfiguration#defaultValidator:
      Did not match:
         - @ConditionalOnMissingBean (types: javax.validation.Validator,org.springframework.validation.Validator; SearchStrategy: all) found beans 'beforeSaveUserValidator', 'beforeCreateGroupValidator', 'beforeCreateUserValidator' (OnBeanCondition)
```

https://github.com/spring-projects/spring-boot/commit/c9561f031c591ca55e028ca66250511c5e62002a changed this behaviour since it does not provide a validator if a Spring validator is present.

Not sure if this is should be considered a bug and I can easily work around this problem and provide this bean myself, but perhaps Spring Boot could create a JSR validator if not present?

**Comment by oyvindhorneland** [comment]
Also the Spring validators for Spring Data REST only supports a specific class. Perhaps Spring Boot autoconfiguration should check if a LocalValidatorFactoryBean bean is present and create if missing?

**Comment by philwebb** [comment]
Thanks for the report. We missed the user-case where a Spring Validator is present but it doesn't implement JSR 303 validation.

Can you share the your validator bean definitions? I'm curious which classes you used.

> Also the Spring validators for Spring Data REST only supports a specific class. Perhaps Spring Boot autoconfiguration should check if a LocalValidatorFactoryBean bean is present and create if missing?

Can you point me at the part of Spring Data that does this?

**Comment by oyvindhorneland** [comment]
An example validator bean looks like this: https://gist.github.com/oyvindhorneland/c16d727e96ab7facb195fd3ab39a5c7b

The bean definition must be manually provided, as documented in http://docs.spring.io/spring-data/rest/docs/2.6.3.RELEASE/reference/html/#validation. They are invoked from https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-core/src/main/java/org/springframework/data/rest/core/event/ValidatingRepositoryEventListener.java.

Official samples for registering these validators seem to be lacking and https://github.com/spring-projects/spring-data-examples/issues/150 requests such a sample, however I found the guide in http://www.baeldung.com/spring-data-rest-validators helpful.

**Comment by oyvindhorneland** [comment]
Superb! Thank you!

**Comment by snicoll** [comment]
@oyvindhorneland a new `1.5.4.BUILD-SNAPSHOT` with the fix is available. Would you be so kind to test it on your project please? 

If you need instructions to add the necessary snapshot repo, you can create an empty app from start.spring.io. Thanks!

**Comment by oyvindhorneland** [comment]
@snicoll 1.5.4-BUILD-SNAPSHOT works well and fixes this issue. One less bean to manage 👍

**Comment by asaarnak** [comment]
After update from 1.5.3 to 1.5.4 and autoconfig error.
Using @Qualifier("beanValidatorFactory") fixes this, but is it expected?
```stacktrace 
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'javax.validation.Validator' available: more than one 'primary' bean found among candidates: [beanValidatorFactory, defaultValidator]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determinePrimaryCandidate(DefaultListableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determineAutowireCandidate(DefaultListableBeanFactory.java:1333)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1113)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 66 more
```

**Comment by snicoll** [comment]
@asaarnak this issue is closed. If you believe you've found an issue, please create a separate issue with a sample that reproduces the problem. Thanks!

**Comment by asaarnak** [comment]
@snicoll Finally i had time to take a look at this issue and managed to workaround it.
We were returning `javax.validation.ValidationFactory` as bean type so the following condition created new bean `defaultValidator`. 
```
@ConditionalOnMissingBean(type = { "javax.validation.Validator", "org.springframework.validation.Validator" })
```
The fix was to return the LocalValidatorFactoryBean type instead of ValidatorFactory.
`@Bean public LocalValidatorFactoryBean beanValidatorFactory()`
