### ISSUE TITLE
Support multiple Flyway beans in the initializer

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#8978]
I am trying to set an autoconfiguration-based application where each module can provide its own Spring beans and the like. I want to use Flyway to manage database migrations, but each Flyway instance sees the entire landscape of migrations as a single history. Spring Boot's Flyway autoconfiguration is happy to let the user supply a bean of type `Flyway` and will inject it into the `FlywayMigrationInitializer`, but it only supports one such bean.

Since there are a number of use cases for having multiple `Flyway` beans, I suggest modifying the `FlywayMigrationInitializer` class to take a `Collection<Flyway>` instead of a singleton, for-eaching the beans. In the baseline case of a single `Flyway` object, it will behave exactly as it currently does, but in the case where the user provides multiple beans, multiple migrations (of whichever varieties) should Just Work.

**Comment by wilkinsona** [comment]
Providing your own `Flyway` bean will switch off the auto-configuration of `FlywayMigrationInitializer`. As a result, changing `FlywayMigationInitializer` to accept a `Collection<Flyway>` won't really have any effect as, when it's auto-configured, there will only ever be exactly one `Flyway` bean.

Have a misunderstood your proposal?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by chrylis** [comment]
I'd missed the additional `@ConditionalOnMissingBean` on the containing configuration class.

In this case, I suggest also considering not disabling the entire autoconfiguration based on a single `Flyway` bean. Replicating the initializer is tedious but doable, but the configuration class that ensures ordering with the `EntityManagerFactory` is a gotcha that is likely to produce heisenbugs, and it is *always* the case that the migration should happen before JPA initialization. Therefore, it seems that moving the condition to only the `Flyway` bean would provide more affordance while not causing any problems I can see. (This would be analogous to the `DataSourceAutoConfiguration`, where your own `DataSource` still gets initializer and similar treatment.)

**Comment by philwebb** [comment]
It feels like we'd be adding a lot of complexity to the auto-configuration to support this. Just looking at the ordering issue, we have a `FlywayJpaDependencyConfiguration` class that ensures the ordering. This class currently works on the bean name, if we have multiple `Flyway` beans then we'd need to rethink this strategy.

We'll happily consider any proposals here, but my gut instinct is we'd be adding a lot of complexity for a slightly unusual case. I'd suggest starting out by replicating our auto-configuration and seeing which bits need to change to support what you need. Perhaps we can just create a few utility classes so it's easy to build these more complex configurations.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
