### ISSUE TITLE
CachePublicMetrics does not support TransactionAwareCacheDecorator

### ISSUE THREAD

**Issue by altery** [spring-projects/spring-boot#8984]
`CacheManager`s that extend from `AbstractTransactionSupportingCacheManager`, for example `JCacheCacheManager`, support transaction awareness by wrapping the `Cache` in a `TransactionAwareCacheDecorator`. If enabled, the cache statistics provided by the Spring Boot Actuator project cease to work.

The problem is, that `CachePublicMetrics#getCacheStatistics` search for a suitable `CacheStatisticsProvider` by comparing the runtime type of the `Cache` against the generic type of all registered `CacheStatisticsProvider`s. This, of course, doesn't work if the Cache is wrapped in a completely different type.

As a workaround, I added a new `AbstractJmxCacheStatisticsProvider<TransactionAwareCacheDecorator>` that contains the same implementation as `JCacheCacheStatisticsProvider` (because we use `JCacheCache`s).

We use Spring Boot 1.4.1, but I quickly checked the latest version on Github, and there doesn't seem to be any changes in this area.

I guess `CachePublicMetrics#getCacheStatistics` should first unwrap `TransactionAwareCacheDecorator` before trying to lookup a stats provider.

**Comment by snicoll** [comment]
@altery it's not that easy unfortunately. `TransactionAwareCacheDecorator` does not provide access to the `Cache` it wraps.

**Comment by altery** [comment]
Yes, without using reflection it would require a change in spring-context-support first. Maybe raise a issue there?

**Comment by altery** [comment]
Thanks!
