### ISSUE TITLE
Remove Spring Security commons-logging exclude

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8985]
When https://github.com/spring-projects/spring-security/issues/4308 is fixed we can remove our workaround.

**Comment by philwebb** [comment]
Reopening because I think there might be a spring jar that we should now exclude

**Comment by wilkinsona** [comment]
@philwebb I guess you're referring to the new `spring-icl` jar? AFAIK, we don't need to exclude it as the rules it uses for delegating to an actual logging backend are not the same as Commons Logging's.

**Comment by philwebb** [comment]
@wilkinsona I think you're correct.
