### ISSUE TITLE
spring.jackson.date-format Property Not Working as Documented

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#9004]
According to the [Current SpringBoot Reference Guide](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) if I set the `spring.jackson.date-format` property, it will: `Date format string or a fully-qualified date format class name. For instance 'yyyy-MM-dd HH:mm:ss'`. 

However, it doesn't work this way with Spring Boot 1.5.3.

To demonstrate, starting with this class:

```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.Instant;

@SpringBootApplication
public class DemoApplication {
  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }
}

@RestController
class NowController{

  @GetMapping("/now")
  Instant getNow(){
    return Instant.now();
  }
  
}
```

and this `build.gradle`:

```
buildscript {
    ext {
        springBootVersion = '1.5.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

I get the following:
```
$ http localhost:8080/now
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Tue, 25 Apr 2017 22:31:33 GMT
Transfer-Encoding: chunked

{
    "epochSecond": 1493159493,
    "nano": 767000000
}
```

If I then add the two jackson datatype dependencies, such that my `build.gradle` is now:

```
buildscript {
    ext {
        springBootVersion = '1.5.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('com.fasterxml.jackson.datatype:jackson-datatype-jdk8')
    compile('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

I then get:

```
http localhost:8080/now
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Tue, 25 Apr 2017 22:34:21 GMT
Transfer-Encoding: chunked

1493159661.843
```

And then if I add a `src/main/resources/application.properties` like this:

```
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
```

I then get:

```
http localhost:8080/now
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Tue, 25 Apr 2017 22:36:29 GMT
Transfer-Encoding: chunked

"2017-04-25T22:36:29.370Z"
```

That's much nicer, but notice that it's not actually what's been defined. Why did Spring Boot change the output, but to something other than expected?

To test this further, supposed I change `src/main/resources/application.properties` to this:

```
spring.jackson.date-format=dd.MM.yyyy
```

I still get the same as the last test:

```
http localhost:8080/now
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Tue, 25 Apr 2017 22:37:58 GMT
Transfer-Encoding: chunked

"2017-04-25T22:37:58.319Z"
```

Is there something I'm missing or is `spring.jackson.date-format` not working as documented?

**Comment by wilkinsona** [comment]
`spring.jackson.date-format` maps down to `setDateFormat` on the auto-configured `ObjectMapper`. Calling that setter does two things for serialization:

1. Disables `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS`
2. Configures the formatting of `Date` instances

The change in the output (from a number to a timestamp) that you have observed is due to 1. The fact that your `Instant` isn't formatted as you expect is because it is an `Instant` rather than a `Date` and Jackson uses separate configuration for `Instant` serialization. I may have missed something, but, as far as I can tell, `Instant` serialisation doesn't provide (easy) global configuration of its format. Instead it has a strong preference for ISO-8601 formatting. However, I do know that you can use `@JsonFormat` to locally override the formatting.
