### ISSUE TITLE
Incomplete Jetty dependency management can lead to a mixture of versions being used

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9010]
http://stackoverflow.com/questions/43639508/nosuchmethoderror-org-eclipse-jetty-websocket-server-websocketserverfactory-in/43642662#43642662

**Comment by snicoll** [comment]
@wilkinsona isn't that a duplicate of #9009 ?

**Comment by wilkinsona** [comment]
This issue is Jetty and #9009 is Jersey

**Comment by wilkinsona** [comment]
`jetty-monitor` doesn't exist in Jetty 9.4 so we need to drop the dependency management for it.
