### ISSUE TITLE
Add PropertyMapper utility

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9018]
We do this a lot:

```java
if (properties.getFilename() != null) {
    log.setFilename(properties.getFilename());
}
```

With Java 8 we could do:

```java
CopyProperty.whenNotNull(properties::getFilename, log::setFilename);
```

Where `whenNotNull` takes a `Supplier<T>` and a `Consumer<T>`.

Not sure about the names but you get the idea.

**Comment by HanSol0611** [comment]
Is it correct that whenNotNull define a new class function and use it?
