### ISSUE TITLE
Log each web request:  DEBUG = too much,  INFO = too little

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#902]
Logging for web-mvc controller requests or static files should appears with the HTTP method and path.  This will make debugging easier in production and development environments.

```
<logger name="org.springframework.web" level="INFO"/>
```

INFO = 3 log lines with no useful information
DEBUG = 30 log lines, with little useful information

Expectation:

```
[time] GET /foobar?some=params
[time] Handled by FoobarController => someMethod(...)
```

**Comment by berlin-ab** [comment]
@philwebb I think this is a good candidate for spring-boot-devtools. I've found myself implementing a hack of AbstractRequestLoggingFilter for development debugging of requests/responses for each SB project I've been on. I don't really like the solution I come up with each time, and wish there were something better out of the box.

My use case is starting up the SB app, opening my front-end app (web or mobile), and seeing the request parameters/body in the log, and the response body with its status code. This helps me quickly debug that I'm sending the right params, and that Spring is parsing them correctly. The response output helps me to understand the actual output my client should expect. The response status code is important, but the response body is also very important.

**Comment by snicoll** [comment]
How about sharing what you've done so far and we can see what we can do to integrate it? I am more in the camp of implementing a feature that can be controlled via properties and have Devtools switch that on for you. That's how we implemented the H2 console support and this proved to be quite effective. 

Looking for your PR then!

**Comment by haydonryan** [comment]
we had a request from a customer who is passing GPS data into applications via the URL - if we could have a way to redact parts of those logs.  Could be worth investigating a regex redactor?

**Comment by dsyer** [comment]
That sounds crazy to me (and not at all related to this issue, which is about dev time).

**Comment by wilkinsona** [comment]
Logback already has support for regex-based filtering of log events. Alternatively, if you really wanted to implement redaction you could use a custom layout. Neither belongs in Spring Boot, though.

**Comment by wilkinsona** [comment]
This doesn't seem to have really gone anywhere and we still believe that this would be better tackled outside of Spring Boot where it could benefit all Spring users.

**Comment by rstoyanchev** [comment]
This can only be addressed properly in the Spring Framework, so I've created [SPR-16898](https://jira.spring.io/browse/SPR-16898).
