### ISSUE TITLE
Document the new binder stuff

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9025]
Technical docs on the wiki for downstream projects would be useful.

**Comment by mbhave** [comment]
See also #9136.

**Comment by snicoll** [comment]
As the changes are quite significant, it would be nice if we could get an update on the doc for the next milestone.

**Comment by mbhave** [comment]
@snicoll do you mean docs in addition to the wiki page?

**Comment by mbhave** [comment]
Oh I misunderstood what you were saying. Yes, the existing doc needs an update. Thanks for pointing that out!
