### ISSUE TITLE
The same class is loaded by different classloaders when deserializing authentication from the DB

### ISSUE THREAD

**Issue by ryvo** [spring-projects/spring-boot#9030]
I implemented OAUTH2 authorization server. I use JPA to store/fetch OAuth2Authentication into/from the database (Hibernate, PostgreSQL) as a part of access token. 

`OAuth2Authentication` contains `userAuthentication` which contains principal which is my own class `MyUser` which implements `UserDetails`. When I fetch the authentication from the database and test `authentication.getPrincipal() instanceof MyUser` it evaluates as false. 

The class name of the principal is the same - `MyUser` - but it has differend ID. I checked class loaders and found out that class `MyUser` is loaded by `RestartClassLoader` but class of `MyUser` instance deserialized from the database is loaded by `Launcher$AppClassLoader`.

I removed `spring-boot-devtools` from my project but it still happens. The problem occurs if I run the app as Spring Boot app. If I run the app as WAR on Tomcat both classes are loaded by the same class loader.

I'm using spring-boot-starter-parent version 1.5.2.RELEASE. I have similar older project using version 1.3.1.RELEASE so I checked it and this Spring Boot version loads both classes with the same class loader so it works without a problem.

**Comment by wilkinsona** [comment]
Without DevTools,there should only be a single class loader involved, and RestartClassLoader definitely will not be involved. Can you please provide a small sample project that demonstrates the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by iKrushYou** [comment]
I am having this EXACT same issue. I will try and put together a project that can demo the issue. I have one more layer of complexity, though. This issue only started happening after implementing spring session with redis
