### ISSUE TITLE
Spring AMQP AutoConfiguration - new Container Type

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#9041]
Add support for choosing the listener container type, together with any additional properties needed.

**Comment by garyrussell** [comment]
I don't have assignment rights - please assign to me.

**Comment by snicoll** [comment]
Closing in favour of PR #9055

@garyrussell we don't need an issue if you intend to submit a PR. Thanks!

**Comment by garyrussell** [comment]
@snicoll I wasn't sure when I would get to the task so I thought it better to create an issue so we didn't lose it.

Are you aware that this would have auto-closed when the per is merged (because I added resolves... to the commit comment).

**Comment by snicoll** [comment]
I am aware but we don't want two issues to describe the same thing. That's why we close it ourselves when a PR is submitted (and accepted).
