### ISSUE TITLE
The jsp files in src/main/webapp can't be auto reload

### ISSUE THREAD

**Issue by mcheung63** [spring-projects/spring-boot#9044]
The jsp files in `src/main/webapp` can't be auto reload, but the css files can. So every time i need to restart spring boot for development.
thanks

**Comment by philwebb** [comment]
I'm not too sure how the JSP compiler deals with changed files. It looks like  `org.apache.jasper.Options.getModificationTestInterval()` should be used to check if files have changed. The default value is 4 seconds, if you wait that long do you see changes?

Perhaps there's some way we can tell the JSP engine that all templates need to be recompiled.

**Comment by mcheung63** [comment]
i tried to wait 5 mins, still fail

Thanks
From Peter

Phil Webb <notifications@github.com<mailto:notifications@github.com>> 於 2017年5月2日 上午2:52 寫道：


I'm not too sure how the JSP compiler deals with changed files. It looks like org.apache.jasper.Options.getModificationTestInterval() should be used to check if files have changed. The default value is 4 seconds, if you wait that long do you see changes?

Perhaps there's some way we can tell the JSP engine that all templates need to be recompiled.

**Comment by wilkinsona** [comment]
@mcheung63 Are you using DevTools or have you configured the JSP servlet to enable development mode? Can you please provide a sample that reproduces the problem? We also need to know which IDE you are using an the exact steps you are taking to update the JSP

**Comment by mcheung63** [comment]
i am using netbeans with jrebel, i found out jrebel can't reload the jsp if i run the project using maven goal "spring-boot:run". See this video https://www.youtube.com/watch?v=K4jz4OnShXQ


But i fixed the problem, please see http://peter.kingofcoders.com/?p=2311


thanks for your helps


________________________________
