### ISSUE TITLE
Spring Boot running data.sql before creating entities in presence of schema.sql

### ISSUE THREAD

**Issue by ConsciousObserver** [spring-projects/spring-boot#9048]
I'm trying to insert some rows in my entities for testing on developer machine using `H2` Database. I'm using `data.sql` for this.

It works fine, entities are created and then `data.sql` is run to insert data in the tables produced by the entities.

However I need to create some other tables for which there are no entity classes, so I'm using `schema.sql` for those. Here's the issue, as soon as I add `schema.sql` to the project, Spring Boot runs  `data.sql` before creating entities, which ends in `Table not found exception`.

It works fine if I replace `data.sql` with `import.sql`, it's run after the entities are created.

However `h2` configuration is supposed to run only when testing, for that I have a maven profile which activates a `spring.datasource.platform = h2`, to load `schema-h2.sql` and `data-h2.sql`. `import.sql` doesn't work with the platform.

So the issue is that `data.sql` is being run before entities are created only when `schema.sql` is present.

Here's the Github repository for reproducing the issue

**Without any platform**

[https://github.com/ConsciousObserver/SpringBootSchemaSqlIssue.git](https://github.com/ConsciousObserver/SpringBootSchemaSqlIssue.git)

**With h2 platform** (It's another branch `platform-h2` in the above repository)

[https://github.com/ConsciousObserver/SpringBootSchemaSqlIssue/tree/platform-h2](https://github.com/ConsciousObserver/SpringBootSchemaSqlIssue/tree/platform-h2)

**Stackoverflow**

[http://stackoverflow.com/questions/43692115/spring-boot-running-data-sql-before-creating-entities-in-presence-of-schema-sql](http://stackoverflow.com/questions/43692115/spring-boot-running-data-sql-before-creating-entities-in-presence-of-schema-sql)

Thanks

**Comment by ConsciousObserver** [comment]
Are you also using `schema.sql` with `data.sql` ?

**Comment by philwebb** [comment]
Currently the `schema.sql` file is taken to bean that the entire database definition is being created by that file. It would be nice if we could change `DataSourceInitializer` so that the `schema.sql` file doesn't immediately trigger initialization. The ideal order is:

With hibernate:
* Run schema.sql
* Initialize Hibernate and allow it to create entity tables
* Run data.sql

Without hibernate:
* Run schema.sql
* Run data.sql

This are of the code is unfortunately quite difficult to change without causing side effects. I don't think we'll be able to do anything in the 1.5.x line.

I'd suggest you either try manually adding the create table commands for the entities in `schema.sql` or trying flyway for data population.

**Comment by adenix** [comment]
I was using both `schema.sql` and `data.sql`. My fix can be to just remove the `schema.sql` since I just had it there with a dummy command in case a team member needed to do manual schema updates.

**Comment by ConsciousObserver** [comment]
For now I have renamed the `data-h2.sql` to `sample_data_h2.sql` and I'm loading it using [ScriptUtils](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/datasource/init/ScriptUtils.html) in [@PostConstruct](http://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html) method of a bean with conditional [@Profile](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Profile.html)

```
@Configuration
@Profile("h2_in_memory")
public class InMemoryConfig {
	private final String SAMPLE_DATA = "classpath:sample_data_h2.sql";
	
	@Autowired
	private DataSource datasource;
	
	@PostConstruct
	public void loadIfInMemory() throws Exception {
		Resource resource = webApplicationContext.getResource(SAMPLE_DATA);
		ScriptUtils.executeSqlScript(datasource.getConnection(), resource);
	}
}
```

**Comment by akanurlanopop** [comment]
@ConsciousObserver, I changed `schema.sql` to this:
`create table USER_DETAILS(id int(10), name varchar(10));`
and database initialization worked as it was intended.

Due to log information script files execution order is correct:
```
2017-07-15 03:39:26.417  INFO 72712 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/path/to/project/SpringBootSchemaSqlIssue/target/classes/schema.sql]
2017-07-15 03:39:26.426  INFO 72712 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/path/to/project/SpringBootSchemaSqlIssue/target/classes/schema.sql] in 9 ms.
2017-07-15 03:39:28.420  INFO 72712 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/path/to/project/SpringBootSchemaSqlIssue/target/classes/data.sql]
2017-07-15 03:39:28.432  INFO 72712 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/path/to/project/SpringBootSchemaSqlIssue/target/classes/data.sql] in 12 ms.
```

Could you try it and give a response about results?

**Comment by ConsciousObserver** [comment]
@akanurlanopop , Thanks for response.

`USER_DETAILS` table is to be created by the `com.test.UserDetails` entity class.

I don't want to make an entry for it inside `schema.sql` as it can be generated by the JPA. That is normal behavior, however this doesn't work if I add custom tables (without JPA entities) to the `schema.sql`.

I hope it make things clearer.
I want to generate the tables which have JPA entities and use schema to create some extra tables.

If you make an entry of `USER_DETAILS` inside `schema.sql` then `com.test.UserDetails` entity won't be generating this table and If I make any changes to that entity, I would have to modify `schema.sql` as well.

**Comment by snicoll** [comment]
It looks like this issue would be addressed with what I am trying to do in #9528

**Comment by snicoll** [comment]
There is a sample using Eclipselink at https://github.com/srinivasnagesh/spring-data

**Comment by snicoll** [comment]
The current behaviour is intended (see #1115) so I am not sure that if we can fix it.

**Comment by wilkinsona** [comment]
It doesn't look like we can, at least not without dragging Hibernate into the Spring Security-triggered part of the initialisation, similar to what would happen if someone tried to use a JPA-based user details service.
