### ISSUE TITLE
SpringApplicationBuilder.setSources no longer works with bound sources

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9053]
The change in #8910 beans that `SpringApplicationBuilder.setSources` is replaced by bound sources. It's more likely that the build is looking to change the primary sources.

**Comment by spencergibb** [comment]
This is where it manifest itself https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L157-L175
