### ISSUE TITLE
Reduce InMemoryAuditEventRepository default capacity

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9056]
Profiling shows that `InMemoryAuditEventRepository` is a little on the large side. Reducing the default capacity should help a little

**Comment by vpavic** [comment]
@philwebb Somewhat related, would you consider adding alternative implementations of `AuditEventRepository` to Spring Boot so the users could have out of the box alternatives to `InMemoryAuditEventRepository`? Similarly like with `MetricWriter` for example.

I've got a `JdbcOperations` based implementation and could contribute it after a bit of polishing.

**Comment by philwebb** [comment]
@vpavic Absolutely, but we're expecting a lot of the actuator code to change in 2.0 so it might be worth holding off for a while.

**Comment by vpavic** [comment]
Great, will make that into a PR then, after the dust around Actuator settles a bit.
