### ISSUE TITLE
java.lang.noclassdeffounderror com/fasterxml/jackson/core/versioned Exception on using pring-boot-starter-actuator

### ISSUE THREAD

**Issue by srinivaschannakeshava** [spring-projects/spring-boot#9064]
Hello ,
I am gettin gthis exception on upgrading my project from spring-boot 1.5.2 to 1.5.3 . On removing the actuator dependency its working fine but with actuator it fails with the above exception.

Thank you 
Regards,
Srinivas

**Comment by snicoll** [comment]
Your cache is probably corrupted. Run `mvn dependency:purge-local-repository` or clear your Gradle cache. If that doesn't help, please share a sample that reproduces the problem.
