### ISSUE TITLE
SpringBootPluginExtension.LayoutType is package private so is unusable in GSK

### ISSUE THREAD

**Issue by JLLeitschuh** [spring-projects/spring-boot#9067]
Bug report

`SpringBootPluginExtension.LayoutType` is package private so `SpringBootPluginExtension::setLayout` can not be called in [Gradle Script Kotlin](https://github.com/gradle/gradle-script-kotlin) as kotlin is a strongly typed language.

**Comment by philwebb** [comment]
Thanks, we'll fix this in 1.5.x. 

Have you tried the 2.0.0.BUILD-SNAPSHOT yet? We've reworked the Gradle plugin quite a bit and I'd be interested to know if it works with GSK.

**Comment by JLLeitschuh** [comment]
No, I haven't tried the new snapshot. We have a lot of software and technology in flux right now.
I'm going to have a second crack at setting up spring boot on another piece of software in a few months and I'll give it a shot then.

**Comment by JLLeitschuh** [comment]
Where can I find the documentation for 2.0.0? Has the DSL changed a lot?

**Comment by wilkinsona** [comment]
@JLLeitschuh The documentation (API and reference) is available [here](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/gradle-plugin/). The DSL is (for now at least) at lot simpler in 2.0.
