### ISSUE TITLE
document of spring.http.multipart.file-size-threshold is confused or mistake ?

### ISSUE THREAD

**Issue by icanfly** [spring-projects/spring-boot#9073]
http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/MultipartProperties.html

as above link. document of spring.http.multipart.file-size-threshold is:

> file-size-threshold specifies the size threshold after which files will be written to disk. Default is 0, which means that the file will be written to disk immediately.

But, In practice, file-size-threshold=0 means that the file never written to disk immediately. it will be written to memory cache stream always.

In my practice, Jetty will never write the file to disk, as I have seen the source code from it.

Please confirm that the description of the document is correct. Thanks.

**Comment by wilkinsona** [comment]
This is somewhat complicated as the behaviour with a value of zero varies by container:

- Tomcat will write to disk immediately
- Jetty will never write to disk
- Undertow [ignores the file size threshold entirely](https://github.com/undertow-io/undertow/blob/1.4.14.Final/servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java#L84)

So the javadoc is right if you're using Tomcat, but wrong if you're using Jetty or Undertow.

**Comment by icanfly** [comment]
@wilkinsona  It seems a bit misleading, I am according to this configuration, I use jetty, and lead to memory overflow, and finally by checking the jetty code clear the cause of the error

**Comment by snicoll** [comment]
@icanfly Andy just gave a statement of the situation and this issue is open so we're going to do something about it.

**Comment by wilkinsona** [comment]
Having a default that varies by container feels like a bad idea to me. I think we should consider changing the default.

**Comment by wilkinsona** [comment]
We're going to fix the docs in 1.4.x and, in the interests of aligning with the Servlet spec, leave the default as zero.
