### ISSUE TITLE
Invalid mail.smtp.connecttimeout key in the documentation

### ISSUE THREAD

**Issue by glyoder** [spring-projects/spring-boot#9082]
Using Spring Boot 1.5.1.RELEASE, and spring-boot-starter-mail.

When I set the following application.properties and connect to an invalid host, the connection does not timeout as expected within 1 second, but eventually the Java connection fails.

```
spring.mail.properties.mail.smtp.connecttimeout=1000
spring.mail.properties.mail.smtp.timeout=1000
spring.mail.properties.mail.smtp.writetimeout=1000
```

Here's an example -- I expected the project to run and timeout immediately instead of hanging until a java connection error is thrown.

https://github.com/glyoder/email-problem

**Comment by glyoder** [comment]
It's a documentation problem:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-email.html

Should be spring.mail.properties.mail.smtp.connectiontimeout, not spring.mail.properties.mail.smtp.connecttimeout.

**Comment by snicoll** [comment]
See #8213
