### ISSUE TITLE
[Question] autoconfigure application name with custom spring boot starter for logging and tracing

### ISSUE THREAD

**Issue by saljuama** [spring-projects/spring-boot#9083]
Hi, I'm working on a custom spring boot starter, with the purpose of providing an auto configuration for all the spring boot applications that we have in our distributed system, so this way, everytime some configuration in that regards needs to be changed, it can be done in one place, and all the applications get the updated config when they update the dependency to the new version.

My take on this was to include a `logback.xml` file in the `src/main/resources` folder of the autoconfigure module of the starter, and yes, when an application imports the starter, it uses the original config file. 

The problem i'm having is, since the starter also provides an auto configuration if Spring Cloud Sleuth is in the classpath, when the `EnvironmentPostProcessor` updates the level pattern with the [app name, traceId, spanId, exported] tuple, the app name that appears is `bootstrap` instead of the name defined with the `spring.application.name` in the `application.yml` file of the application using the starter. 

My first take on this was to replace in the pattern `${LOG_LEVEL_PATTERN:-%5p}` with just `%5p` and then add somewhere else in the pattern the tracing info with `[%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]`, and use a filter to put in the `MDC` the application name by autowiring with `@Value("${spring.application.name}")` and just realized, its a filter, it will only work with incoming requests, but thats it, everything else that happens without request won't include the application name in the logs.

My second take was to include a `ApplicationContextInitializer` to add the content of the `spring.application.name` into the `MDC` and then remove it from the filter, but then, on the startup logs it appeared the application name, but on the HTTP requests it didn't. 

I still haven't tried to use asynchronous communication yet on the applications, and that is also an scenario i need to have covered too, but will make a demo project including async communication with Spring Cloud Stream, and will publish it to GitHub and provide the link as soon as it is there if it is of any help.

So the question is, since i'm kind of stuck and don't know where else to look, what would be the best approach to to get the application name defined in the `application.yml` to be injected for the logs to include it, in all the scenarios? 

Thanks in advance!

**Comment by philwebb** [comment]
Thanks for getting in touch, but we prefer to use our issue tracker only for enhancements or bugs. Probably the best place to ask a question like this is [Gitter](https://gitter.im/spring-projects/spring-boot).

Your problem covers a lot of different projects so it's going to be hard to offer much advice. I'm not familiar with the inner workings of Spring Cloud Sleuth but perhaps you could adapt their `EnvironmentPostProcessor` somehow.

@marcingrzejszczak may be able to offer some advice or point you at a better place to ask.

**Comment by saljuama** [comment]
fair enough :) and even though not the answer i was looking for, at least points me in a direction!

**Comment by thibwa** [comment]
@saljuama Hi ! 

Do you find a way to do that ? 
I'm doing the same with the help of Sentry with mdctags=X-B3-TraceId,X-B3-SpanId
Since SpringBoot 2.0.0 and Spring Cloud Finchley.M7 I can't find a way to do the same.

Any help will be useful :)

Thanks

**Comment by saljuama** [comment]
Hi @thibwa, at the end I recall I did achieve it, after bringing the topic in Gitter. 

Unfortunately, I no longer have access to that code, as I'm no longer part of the organization I was with at the time of the issue, and can't share the results. 
And also, it was done with Spring Boot 1.4.x and Spring Cloud Camden RC, and I didn't follow the changes since then. 

My recommendation would be for you to ask in Gitter, I received great support there and good pointers to fulfill what I wanted to achieve.
