### ISSUE TITLE
Remove testing support from the CLI

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9087]
The testing support in the CLI is proving to be more trouble than it's worth. Our recommendation is that, once an app gets to the stage of requiring a test suite, it should be converted to a Maven or Gradle project. This makes it easy to version, publish, deploy etc using the vast ecosystems of the two build systems. See gh-9043 for further background.

**Comment by StephenOTT** [comment]
@wilkinsona would be good if a note was added to the docs about the removal of this.  There are many examples on the web that discuss the `spring test` command.
