### ISSUE TITLE
Add auto setup for logging via logstash

### ISSUE THREAD

**Issue by djgeary** [spring-projects/spring-boot#9090]
The existing `org.springframework.boot.logging.logback.DefaultLogbackConfiguration` sets up a console logger appender and (if a log filename is present) a file logging appender 

Logstash is a popular open source logging mechanism (particularly in cloud environments). The default configuration (or auto configuration / logstash starter?) could be enhanced to add a logstash appender if the dependency net.logstash.logback:logstash-logback-encoder is present and a logging.logstash.host property is defined.

Optionally other properties of the LogstashSocketAppender could be configuarable if properties are present such as port and custom fields.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, the logging system is configured too early for it to support auto-configuration and I don't think it would be wise to complicate it by introducing a logging system-specific equivalent.

If you want to use Logstash I would recommend configuring as you normally would in `logback.xml` or `logback-spring.xml`. Using the latter will allow you to [configure the Logstash appender via Spring's environment](http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#_environment_properties).
