### ISSUE TITLE
StatsdMetricWriter should not send double values to statsd

### ISSUE THREAD

**Issue by kgarlikowski** [spring-projects/spring-boot#9092]
According to the documentation of `StatsdMetricWriter`:
```java
/**
 * A {@link MetricWriter} that pushes data to statsd. Statsd has the concept of counters
 * and gauges, but only supports gauges with data type Long, so values will be truncated
 * towards zero. Metrics whose name contains "timer." (but not "gauge." or "counter.")
 * will be treated as execution times (in statsd terms). Anything incremented is treated
 * as a counter, and anything with a snapshot value in {@link #set(Metric)} is treated as
 * a gauge.
 *
 * @author Dave Syer
 * @author Odín del Río
 * @since 1.3.0
 */
```

it seems that the implementation does not really follow it. 

The code 

```java
this.client.gauge(name, value.getValue().doubleValue());
```

and the tests provided 

StatsdMetricWriterTest:
```java
@Test
public void setDoubleMetric() throws Exception {
	this.writer.set(new Metric<Double>("gauge.foo", 3.7));
	this.server.waitForMessage();
	// Doubles are truncated
	assertThat(this.server.messagesReceived().get(0)).isEqualTo("me.gauge.foo:3.7|g");
}
```

suggest that double values are reported to statsd. It causes issues as the statsd protocol defines integers as the only proper values it should consume.

**Comment by philwebb** [comment]
It's a little confusing.

The [spec](https://github.com/b/statsd_spec#metric-types--formats) states:

> The protocol allows for both integer and floating point values. Most implementations store values internally as a IEEE 754 double precision float, but many implementations and graphing systems only support integer values.

The `StatsDClient` API takes `long` or `double` so it's not totally clear if we should truncate values to `long` or update the documentation.

**Comment by philwebb** [comment]
@dsyer @jkschneider any insights?

**Comment by jkschneider** [comment]
@kgarlikowski Seems like it depends on the variant of statsd you are using. [Etsy lists](https://github.com/etsy/statsd/wiki) a whole lot of different servers and clients, which may have slightly different requirements.

I'm keen to get this support right in [spring-metrics](https://github.com/spring-projects/spring-metrics). Which statsd backend are you using?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
