### ISSUE TITLE
Failure to find io.projectreactor:reactor-bom:pom:Bismuth-M1

### ISSUE THREAD

**Issue by tfe2012** [spring-projects/spring-boot#9096]
Try to use

spring-boot-starter-parent 2.0.0.BUILD-SNAPSHOT

And I get this error:

Plugin org.springframework.boot:spring-boot-maven-plugin:2.0.0.BUILD-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.springframework.boot:spring-boot-maven-plugin:jar:2.0.0.BUILD-SNAPSHOT: Failure to find io.projectreactor:reactor-bom:pom:Bismuth-M1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by snicoll** [comment]
You need the milestones repository and the snapshot repository if you use the snapshot.  Create an empty app from start.spring.io if you need directions for your build system.

**Comment by tfe2012** [comment]
Thx, it's works
