### ISSUE TITLE
Does bootRun task actually call a processResources task ?

### ISSUE THREAD

**Issue by highdali** [spring-projects/spring-boot#9105]
I want to preprocess resources when bootRun task is running.
I guess `bootRun` task does not call `processResources` task.
I attached custom task what pre-processes resources next to `processResources` task.
According to the [doc](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-running-applications), When I set `addResources` option `false`, bootRun should call a `processResources` task. But it seems to call nothing. It just copies resources into `build...` directory.
I updated sample [here](https://github.com/highdali/bootrun-with-resources/tree/test).
I want to use the point that `bootRun` should call a `processResources` task without continuous build of gradle.

**Comment by bclozel** [comment]
@highdali Why did you close this issue?

**Comment by highdali** [comment]
@wilkinsona said [here](https://github.com/spring-projects/spring-boot/issues/1739)

> This is by design.

If i want solve this issue, i have to use 3rd party plugin like watcher maybe.
OR
continuous build of gradle.

**Comment by bclozel** [comment]
Ah I see, thanks!
