### ISSUE TITLE
Consider changing metrics to be multi-dimensional

### ISSUE THREAD

**Issue by cskinfill** [spring-projects/spring-boot#9106]
The current metrics support in spring boot actuator only allow for a string name and a value.  But if we use a metrics database like influxdb or others, its cumbersome to write a transformer that can unravel the metric name into a `measurement`, `tag`, `field` structure.  It seems easier to support this mult-dimensional structure when the metric is created, and then provide a way to flatten it for graphite, statsd, etc., then try and go the other way.

Something perhaps like `GaugeService.submit(String metric, double value, Map<String, String> tags)` and then update `Metric` to store the tags.

Thoughts?

**Comment by spencergibb** [comment]
Duplicate of #8130?

**Comment by cskinfill** [comment]
yeah, looks like it is.  sorry, i thought i searched for duplicates somehow completely missed #8130
