### ISSUE TITLE
when use jsp view template , dependencies tomcat-embed-jasper, some three party library path incorrect

### ISSUE THREAD

**Issue by FanError** [spring-projects/spring-boot#9107]
run app, console will throw error:

[ost-startStop-1] o.a.tomcat.util.scan.StandardJarScanner  : Failed to scan [file:/C:/Users/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna-platform/4.3.0/112d185ecfff7a3e6c33a114c566f9bf6f832244/lib/jna.jar] from classloader hierarchy

java.io.FileNotFoundException: C:\Users\Xuz\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna-platform\4.3.0\112d185ecfff7a3e6c33a114c566f9bf6f832244\lib\jna.jar 

remove these line everything will work fine, but can't use jsp view template

compile('org.apache.tomcat.embed:tomcat-embed-jasper')
compile("org.springframework.boot:spring-boot-starter-tomcat")
compile("javax.servlet:javax.servlet-api")

attachment file 'build.gradle' is minimum test environment can reproduce this problem
[build.gradle.txt](https://github.com/spring-projects/spring-boot/files/978039/build.gradle.txt)

**Comment by snicoll** [comment]
That jar is probably corrupted. Clean your gradle cache and it should work. If it doesn't please attach a complete sample we can run ourselves to reproduces the problem.

**Comment by FanError** [comment]
after clean gradle cache problem seem still exists.
1. manually delete Windows: %USER_HOME%.gradle/caches
2. execute gradle clean
3. run app again

can't upload zip file, please rename JPG to ZIP format

![demo zip](https://cloud.githubusercontent.com/assets/10175987/25736127/8a56f1fc-31a2-11e7-9a80-6487b101da3c.jpg)

**Comment by snicoll** [comment]
Looks like #8623 but that doesn't fail the app as defined there. I hit your `/oshi/test` and I got 123.

So, what is the problem?

**Comment by FanError** [comment]
oops, I test again, now just one "small" problem.

when every time start app, console will throw FileNotFoundException

[ost-startStop-1] o.a.tomcat.util.scan.StandardJarScanner  : Failed to scan [file:/C:/Users/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna-platform/4.3.0/112d185ecfff7a3e6c33a114c566f9bf6f832244/lib/jna.jar] from classloader hierarchy

java.io.FileNotFoundException: C:\Users\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna-platform\4.3.0\112d185ecfff7a3e6c33a114c566f9bf6f832244\lib\jna.jar
