### ISSUE TITLE
Introduce spring.rabbitmq.listener.simple

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9108]
In 2.0, we'll support two different RabbitMQ listener types (simple and direct) as defined in #9055. In preparation of this work, `spring.rabbitmq.listener.*` should be deprecated in favour of `spring.rabbitmq.listener.simple` (both keys should work to help users migrate).

**Comment by youzipi** [comment]
the `simple` config can not work 
on `springboot-1.5.10.release` and related default amqp `spring-rabbit-1.7.6.RELEASE`
doesn't `deprecated` should support current version code?
or I need to do some extra work in rabbitmq's code Config?

**Comment by wilkinsona** [comment]
It should work in 1.5.4 and later. If you believe you have found a bug, please open a new issue with a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) that reproduces the problem.
