### ISSUE TITLE
Support @NestedConfigurationProperty at targets other than field

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9109]
`@NestedConfigurationProperty` can't be set in the getter. If a nested property is deprecated, the field is usually removed (to remap to the new namespace). There should be a way to specify that annotation at getter level

If a nested property is deprecated all its keys should be flagged as deprecated automatically as well.

**Comment by pkostrzewa** [comment]
I can take a look at this with some guidance.

Are you asking to extend `NestedConfigurationProperty's` target with `ElementType.METHOD`?

Additionally, should configuration processor check whether a method annotated with `NestedConfigurationProperty` is actually a getter?

**Comment by regulskimichal** [comment]
Also, this could be useful in case of using `@ConstructorBinding`. Right now, there is no way of telling Spring Boot to create metadata for a POJO injected via constructor.

**Comment by wilkinsona** [comment]
Closing in favor of #38844.
