### ISSUE TITLE
EnableConfigurationPropertiesImportSelector is deprecated with no obvious replacement

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9111]
`EnableConfigurationPropertiesImportSelector` is deprecated and there is nothing in the javadoc that mentions what the replacement will be.

**Comment by wilkinsona** [comment]
Looks like an accident to me. It was deprecated in https://github.com/spring-projects/spring-boot/commit/b10e2f3a051ec1de1fb17ae08e42c1f0c0c9687c.
