### ISSUE TITLE
the spring-"boot" project is a joke.,that's what I think and using.

### ISSUE THREAD

**Issue by alaxcc** [spring-projects/spring-boot#9118]
Spring boot is a big trouble, worse than spring- *. Spring boot's original intention is to  start a project faster as bootstrap, but the fact is the opposite, after next step and next step, when running the result Is wrong. 

The equivalent of the shortestings of spring- *, spring boot a little less, on the contrary, the packaging more precise, so that the problem did not know why the operation failed.

maybe  a project package of spring-* with configured,integreted is better than spring-boot project.

it's more stable and  faster to copy exists spring-* configure files than "start with spring-boot".

if you can't provider a ready to use framework,don't be named as *boot，ok？

the spring-"boot" project is a joke.

**Comment by philwebb** [comment]
I'm guessing that English isn't your first language, so you might not be aware of how rude your tone is, but this is no way to report an issue on an open source project. I'm all for constructive feedback, but other than you think "the project is a joke", I'm not sure what actual problem you've encountered.

Perhaps you can try again with a few more details, or attach a sample project that shows the problems that you encountered?

You are of course also free to use any of the other Spring projects without Spring Boot, join a different technology community, or start your own open source project if you feel that would be better.

**Comment by alaxcc** [comment]
why don't make it easy to use?

download default bundle from start.spring.io and run,it's can't see anything,without simple format log.  

if you want support integrate from start,why not contains some example configure or files,pages?

likes add web dependency,should contains example controller and jsp files,maybe include cache operation class.

add JPA dependency,you should contains example database,orm,to show best properties.

and so on other denpendencies.

Make it easy to use,and make it easy to bootstrap running.


Yes,english not my first language,sorry for rude.

**Comment by wilkinsona** [comment]
The Spring Boot project has a policy of no automatic code generation so what you have proposed is out of scope. Thank you for the suggestion though. If you are looking for something that does more than start.spring.io to help you get started, you could take a look at [JHipster](https://jhipster.github.io) which is a sophisticated generator for Spring Boot (and Angular) projects.

**Comment by alaxcc** [comment]
Thanks for recommend.
I have see and try JHipster,and it's too heavy to bootstrap.
Sping  should provide some solution scaffold likes appFuse,that's truly spring-boot.

**Comment by geoand** [comment]
For application scaffolding, you can also look at Spring Roo (of which 2.0 is in the makings).

I must say however that if your goal was to get feedback about how to scaffold a Spring project, the means you used to achieve it are questionable to say the least.

**Comment by sivaprasadreddy** [comment]
@alaxcc, Looks like you misunderstood the goal of SpringBoot. SpringBoot is not for code generation but for automatic configuration with sensible defaults without requiring the developers to write boilerplate configuration.

If you are looking for code generation one approach that comes to my mind is create maven archetypes with all the configurations (properties, JavaConfig etc) for particular tech stack that you would be using most commonly. This is what I did few years ago (before SpringBoot) https://github.com/sivaprasadreddy/maven-archetype-templates.

BTW, your comment is very rude. We shouldn't forget that we are leveraging some peoples thousands of hard work for FREE. If we don't like something we can give constructive feedback.

Thanks a lot SpringBoot team for providing such an awesome framework which makes my life as a software developer a lot easier.

**Comment by martin-g** [comment]
Spring Boot is open source but it is not developed for free! It's developers are paid by their employer, Pivotal, to work on it.
But this is not an excuse for @alaxcc for his tone and demands!

**Comment by sivaprasadreddy** [comment]
That is true. Spring team might be getting paid by Pivotal, but as consumers we(most of us) are using it for free.

**Comment by alaxcc** [comment]
I don't have any demands.

I just complain that spring-boot named boot ,but can't start quickly.@martin-g

**Comment by Nasruddin** [comment]
@alaxcc you can't start quickly? You must be joking mate. It's is one of the best tool available to get up and running with microservices. 
If you are angry or want to troll Spring Boot team, better do it on social media. Here we post issues or help others fixing issues. :-)
