### ISSUE TITLE
What is mean 'Making static classpath resources reloadable'

### ISSUE THREAD

**Issue by highdali** [spring-projects/spring-boot#9125]
As described in the [documenation](http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-running-applications), making static classpath resources reloadable equals to

```
bootRun {
    addResources = true
}
```

Though I set `addResources` option `false`(So i don't want to make resources reloadable), boot doesn't use `processResources` output. It always uses `src/main/resources` directly.(grab them and put them onto `build` directory.)

> Making static classpath resources reloadable means 
that bootRun does not use the output of the processResources task, i.e., 
when invoked using bootRun, 
your application will use the resources in their unprocessed form.

This description seems to be wrong.
Documentation needs to be fixed.

**Comment by wilkinsona** [comment]
@highdali Can you please provide a small sample that reproduces the problem along with precise steps to reproduce the behaviour you have described?

**Comment by snicoll** [comment]
> Though I set addResources option false(

Also, you don't have to do that since it's the default value.

**Comment by highdali** [comment]
@snicoll I just specify what i would like to.

**Comment by highdali** [comment]
@wilkinsona 
I uploaded the [sample](https://github.com/highdali/springboot-addresources-sample)
It's not different with springboot boilerplate.
When I set `addResources` option `false`(Resources are not watched), We can get resources reloadable through custom task(copies the resources into `build` directory) what is attatched next to `processResources`. 

First run of app, `processResources` seems to be called correctly.
```
⇒  ./gradlew bootRun
:compileJava
:processResources
:printHello
**It's dummy. But i would like to process resources here**
:classes
:findMainClass
:bootRun
```
You regard dummy task as a custom task(pre-processes resources).
At least, processResources should be called in some way or other. 
For now, any resources are not watched(addResources set `false`), `processResources` are never called.

How i can trigger a custom task ?

We can implement `reload` by copying the resources into `build` directory manually. You can do this. Grab any resources and put them into `build`.

What about `addResources` set `true` ?
Now boot doesn't use `processResources` output. In other words, boot doesn't watch `build` directory. boot just watches `src` directory. If i modify files in `src/main/resources...`, It seems to be reloaded.

**Comment by wilkinsona** [comment]
Ok, I think I understand what you want to do now. You want to use DevTools and, as you change files in `src/main/resources` you want those resources to be preprocessed and for your application to use the updated output of that preprocessing.

As you've seen, we have an [issue open to do that in Maven](https://github.com/spring-projects/spring-boot/issues/5136). As you've noted above, you can already do it today using Gradle's continuous build support which is our recommended solution to your problem. You've said above that you think using Gradle's continuous build is unnatural, but this is exactly the sort of thing for which it's intended. It's documentation that you liked to above specifically mentions resource preprocessing:

> Continuous build is in no way coupled to compilation. It works for all types of tasks. For example, the processResources task copies and processes the files from src/main/resources for inclusion in the built JAR. As such, a change to any file in this directory will also initiate a build.
