### ISSUE TITLE
Reintroduce RelaxedPropertySources in a deprecated form

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9131]
It would help Spring Cloud with migration. We may still remove them before GA.

**Comment by philwebb** [comment]
Actually, before we reintroduce this. What areas are broken in Spring Cloud? Perhaps we can help with the migration so we can have a clean break in M1?

**Comment by dsyer** [comment]
Spring Cloud Commons is a big red splodge at the minute. I'll try and fix as much as I can and we can see if that can be turned into a working build. After that we'll have to see what the knock on effect is for everything else (it all depends on Commons).

**Comment by wilkinsona** [comment]
Given that Finchley has been released on top of M2, I don't think we need this. We can re-open if that turns out not to be the case for some reason.
