### ISSUE TITLE
Latest spring-boot-gradle-plugin breaks Gradle maven-publish plugin

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#9135]
After upgrading to Boot 1.5.3, all our projects are now failing with the following error message:

> Error:Cannot configure the 'publishing' extension after it has been accessed.

There is some discussion about this error [here](https://discuss.gradle.org/t/apply-maven-publish-plugin-from-init-script/2460) and on [SO](http://stackoverflow.com/questions/36079404/errorcannot-configure-the-publishing-extension-after-it-has-been-accessed). Part of the problem is that the Gradle team is "incubating" the publishing plugin for the last 3-4 years. That said, the previous versions of Spring Boot plugin didn't trigger this error and now it does, leaving us dead in the water.

Here's a Gradle file that can be used to reproduce this issue.
```
buildscript {
	ext {
		springBootVersion = '1.5.3.RELEASE'
	}
	repositories {
		jcenter()
	}
	dependencies {
		classpath(
				"org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
		)
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


ext {
	springCloudVersion = 'Dalston.RELEASE'
	artifactoryUrl = 'http://doesnotexist'
}

dependencies {
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

apply plugin: 'maven-publish'

project.publishing.publications {
	mavenJava(MavenPublication) {
		from components.java
	}
}

def isSnapshot = project.version.toString().toLowerCase().contains('snapshot')
logger.info("Publishing project version: ${project.version}")
def artifactoryUrl = "${artifactoryUrl}/${isSnapshot ? 'libs-snapshot-local' : 'libs-release-local'}"

project.publishing.repositories {
	maven {
		credentials {
			username "whatever"
			password "shhh"
		}
		url "${artifactoryUrl}"
	}
}
```

**Comment by asarkar** [comment]
For what it's worth, I found a workaround. if the publishing section is enclosed in an `afterEvaluate`, and put after the boot plugin in the build file, it works. But the question remains, what changed between the previous version of the Boot plugin and the latest one?

**Comment by wilkinsona** [comment]
This is due to a change in the dependency management plugin that's described [in this issue](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/170).

**Comment by asarkar** [comment]
@wilkinsona Thanks for your response. It should be documented [here](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-publishing-artifacts-to-a-maven-repository). Two people created bugs within a couple of weeks (one is me), that cost both you and them time, apart from the initial investigation time that's not so apparent in the bugs.

**Comment by wilkinsona** [comment]
That's a fair point. Would you like to contribute a change to the documentation, @asarkar?

**Comment by asarkar** [comment]
Not soon, but may be in a couple of weeks.

**Comment by asarkar** [comment]
@wilkinsona This turned out to be a far more severe issue than just having to add `afterEvaluate`. Putting the publish config is `afterEvaluate` in `allProjects` is causing submodules of a multimodule project **not** being published. Only the parent is published.
