### ISSUE TITLE
Default Atomikos properties are ignored, at least spring.jta.atomikos.properties.threaded-two-phase-commit=true

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#9141]
MyApp.java

```
package my.app;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApp {
	public static void main(String[] args) throws Exception {
		SpringApplication.run(MyApp.class, args);
	}
}
```

application.properties
```
spring.datasource.url=jdbc:postgresql://localhost:5432/abc
spring.datasource.username=user
spring.datasource.password=password
```

pom.xml

```
<project >
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.3.RELEASE</version>
	</parent>
	<artifactId>delete-me4</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jta-atomikos</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
	</dependencies>
</project>
```

When I start application, I get **com.atomikos.icatch.threaded_2pc = false:**

> 2017-05-09 13:38:45.633  INFO 11436 --- [           main] c.a.i.c.i.AbstractUserTransactionService : USING core version: 3.9.3
2017-05-09 13:38:45.633  INFO 11436 --- [           main] c.a.i.c.i.AbstractUserTransactionService : USING com.atomikos.icatch.automatic_resource_registration = true
2017-05-09 13:38:45.633  INFO 11436 --- [           main] c.a.i.c.i.AbstractUserTransactionService : USING com.atomikos.icatch.client_demarcation = false
2017-05-09 13:38:45.633  INFO 11436 --- [           main] c.a.i.c.i.AbstractUserTransactionService : USING com.atomikos.icatch.threaded_2pc = false

According to http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties I expect **com.atomikos.icatch.threaded_2pc = true:**

If I modify `appliaction.properties` and append line 4 `spring.jta.atomikos.properties.threaded-two-phase-commit=true` I got

> 2017-05-09 13:51:08.344  INFO 2244 --- [           main] c.a.i.c.i.AbstractUserTransactionService : USING com.atomikos.icatch.serial_jta_transactions = true

But I should **NOT** add line 4 because it is a default

**Comment by philwebb** [comment]
It looks like the current design is a bit funky. We update items in the `this.values` map only when the setter is called. I'm guessing the is the property is missing the Atomkos default must be different from ours.

We should certainly improve the way that the properties are populated, but perhaps we should also change the `threaded-two-phase-commit` default to `false`. I'm worried that we might fix the bug, then break applications when people upgrade.

**Comment by snicoll** [comment]
So I did a review of all the config and all default values are still accurate _but this one_ whose default has changed to `false` since Atomikos 3.7. Since users are effectively using this in 1.5.x I'd be in favour of changing the value so that it's explicit the new default is false.

We need a way to test our stuff so that our defaults do not deviate again.
