### ISSUE TITLE
Tidy up the generics on PathBasedTemplateAvailabilityProvider and its subclasses

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9148]
This isn't entirely straightforward. The easiest approach requires making the various `TemplateAvailabilityProperties` subclasses public but I'm not sure we want to do that. If we do, Eclipse's (Mars.2 at least) import organisation struggles as it removes an import that is needed. That means we either have to qualify a class name rather than using an import for it (ugly) or correct Eclipse's mistake whenever imports are organised (annoying).

**Comment by wilkinsona** [comment]
@philwebb Took care of this in 9127c48fb5cef79c5bfed8e02df0284c7915cad6.

**Comment by philwebb** [comment]
Although I didn't do a great job :) What's that `properties1` variable all about? I'll polish that up.
