### ISSUE TITLE
CRaSH compatible startup script

### ISSUE THREAD

**Issue by idcmp** [spring-projects/spring-boot#915]
I've added CRaSH to my spring-boot enabled app and have exposed some domain-specific commands through it ("connect", "login", etc..). 

Now, I would like to be able to replace the hard-coded startup I have in my app ( connect(...); login(...); ) with a CRaSH script (which would then make use of the domain-specific commands I've added).

It would be fantastic if the -starter-remote-shell automatically ran a startup script after the application context was initialized.

**Comment by wilkinsona** [comment]
Support for the remote shell is going to be remove in 2.0 (#7006).
