### ISSUE TITLE
Properties binding changed for Properties

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#9152]
Taking a simple boot app
```
@SpringBootApplication
public class DemoApplication implements CommandLineRunner {

    @Bean
    @ConfigurationProperties("myprops")
    public MyProps myprops() {
        return new MyProps();
    }

    @Autowired
    private MyProps myprops;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("XXX " + myprops.getEnvironment());
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    public static class MyProps {
        private Properties environment;

        public Properties getEnvironment() {
            return environment;
        }

        public void setEnvironment(Properties environment) {
            this.environment = environment;
        }
    }
}
```

with boot 2.x I get, where key is String and value is a Map.
```
XXX {foo={bar=1}}
```
with boot 1.5.x I get where key and value seem to be Strings
```
XXX {foo.bar=1}
```
Think it's same issue with `Map<String,Object>` and `Properties`. Can we restore old behaviour as as this is causing some downstream projects to fail.

**Comment by mbhave** [comment]
As @wilkinsona pointed out, `Properties` can be treated as `Map<String, String>`. For `Map<String, Object>` surrounding the key with `[]` should work.

**Comment by jvalkeal** [comment]
`Map<String,Object>` was something what @dsyer pointed out but not sure what that `Object` should actually be. Didn't try what behaviour with that used to be, but as `Properties` is supposed to be `String` as key/value, it'd be good if that special case is handled.

**Comment by wilkinsona** [comment]
Dots in key names have always been problematic. See https://github.com/spring-projects/spring-boot/issues/8326 for an example.

**Comment by privettoli** [comment]
Hi @wilkinsona, 

On our current 1.5.13 project we have white space keys like:
```yml
some-parent:
  ." ": "Some value for white space key"
```
Dot is required because RelaxedDataBinder.BeanPath#splitPath(String):List<PathNode> filters out blank values using StringUtils.hasText(String):boolean.

Should we change the way how we define such properties to prevent them from breaking when we update to Boot 2? Or what is the designed way to declare white space keys?

**Comment by wilkinsona** [comment]
I don't think we've ever purposefully supported white space keys and suspect it only ever worked by accident. The value of them isn't clear to me at the moment as we couldn't bind them to a setter. I guess they could be used to populate a Map, though. If you'd like us to take a more detailed look, can you please open a new issue with a small sample that works with Spring Boot 1.5 and fails with Spring Boot 2.0?
