### ISSUE TITLE
ConfigurationProperties not rebindable at runtime

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#9160]
This is a problem for Spring Cloud Context (with `@RefreshScope` in particular). At first I thought it was because the `ConfigurationPropertiesBindingPostProcessor` doesn't use the ambient `Environment`, so if it changes there's a chance it made a copy of something and hasn't updated it. 

Here's a test that fails with Spring Boot 2.0.0 and passes with 1.5.3:

```java
@RunWith(SpringRunner.class)
@SpringBootTest("test.name=Andy")
public class RefreshApplicationTests {

	@Autowired
	private TestProperties properties;
	@Autowired
	private ConfigurationPropertiesBindingPostProcessor processor;
	@Autowired
	private ConfigurableEnvironment environment;

	@Test
	public void liveRebind() {
		assertThat(properties.getName()).isEqualTo("Andy");
		EnvironmentTestUtils.addEnvironment(environment, "test.name=Dave");
		assertThat(properties.getName()).isEqualTo("Andy");
		processor.postProcessBeforeInitialization(properties, "testProperties");
		assertThat(properties.getName()).isEqualTo("Dave");
	}

	@ConfigurationProperties("test")
	@TestConfiguration
	public static class TestProperties {
		private String name;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}

}
```

**Comment by dsyer** [comment]
More data: break points tell me that the setter *is* called twice in 2.0.0, but with the wrong value. Might be related to #9137 and the fact that the `Environment` is not re-used in the second call (my first hypothesis above), but that doesn't explain why the test works without the `@Aspect`.

**Comment by dsyer** [comment]
UPDATED: the aspect isn't the problem. Old redundant content from description:

The problem actually also shows up for `@RefreshScope` in combination with `@ConfigurationProperties` so I think it's actually more to do with the fact that the bean is a proxy. Maybe the post processor should be able to detect that and do something different (unpack the proxy and bind to the target for instance)? Or maybe it can be fixed by giving the post processor a lower order or something (might cause issues elsewhere).

**Comment by dsyer** [comment]
Here's a hack to fix the test. Do this before calling `postProcessBeforeInitialization()`:

```
		ReflectionTestUtils.setField(processor, "binder", null);
		processor.afterPropertiesSet();
```

**Comment by philwebb** [comment]
I think I probably changed this logic whilst trying to improve performance. My assumption was that using the same binder would be fine because all that stuff happens so early.

**Comment by dsyer** [comment]
Our build is still broken. I can fix it with a different reflection hack (setting "propertySources" to null, instead of the "binder"). Really we need to address it through a proper public API that we test in Spring Boot (see #8344).

**Comment by philwebb** [comment]
I'll target #8344 to M2 and we'll see if we can't come up with something better. I'm worried that when we add support for immutable configuration properties we're going to get more issues.
