### ISSUE TITLE
spring-boot-configuration-processor does not detect defaultValue

### ISSUE THREAD

**Issue by bluebilt** [spring-projects/spring-boot#9164]
Default values specified in an `@ConfigurationProperties` class are not detected by the spring-boot-configuration-processor

INPUT: 
@ConfigurationProperties class containing

```java
String bug = "This-Should-Be-Shown"
```

OUTPUT to target/classes/META-INF/spring-configuration-metadata.json

```java
"properties": [
    {
      "sourceType": "com.example.ExampleProperties",
      "name": "configuration.properties.bug",
      "type": "java.lang.String"
    }
  ]
```

as you can see the "defaultValue" attribute is not there.

Tested with spring-boot 1.5.3 on java 1.8.0_131 on OS X 10.11.6

**Comment by wilkinsona** [comment]
@bluebilt Are you using Eclipse or at least Eclipse's compiler? If so then this is a duplicate of https://github.com/spring-projects/spring-boot/issues/2289.

**Comment by bluebilt** [comment]
Confirmed, when running maven from the command the defaultValue field is included. Apologies!
