### ISSUE TITLE
Apply codecs auto-configuration to webflux server and webclient

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#9166]
For Spring MVC, the `HttpMessageConvertersAutoConfiguration` configures the appropriate message converters for the server and the client (`RestTemplate`).

We should do the same for WebFlux, using `ServerCodecConfigurer` and `ClientCodecConfigurer`.

**Comment by snicoll** [comment]
Interesting convo in #9485

**Comment by alimate** [comment]
Probably the same issue https://stackoverflow.com/questions/44579870/configure-jackson-to-use-snake-case-globally-in-spring-boot-2-0-0-m1/44585365#44585365

**Comment by bclozel** [comment]
Some changes are required in Framework to consistently apply codec configuration on both client and server sides, see [SPR-15682](https://jira.spring.io/browse/SPR-15682).

**Comment by bjornharvold** [comment]
Apologies, I am looking everywhere in the Spring Boot documentation and I cannot find any reference to how to get the WebTestClient to pick up my custom objectMapper. I am using Spring Boot 2 and my custom object mapper is not being used. Is there specific configuration required?

I am assuming this ticket fixed it somehow.

Cheers

**Comment by bclozel** [comment]
If you inject a `WebTestClient` in your tests, it should be customized with codecs automatically.
If your application declares an `ObjectMapper` beans, it should override the opinion provided by Spring Boot and be picked up in the HTTP message conversion and client codecs configuration.

If it's not the case, please create a new issue with a small repro project I can take a look at.

Thanks!

**Comment by bjornharvold** [comment]
Hi @bclozel 

I did what I saw in the other ticket that started this and added:

@Bean
    Jackson2JsonEncoder jackson2JsonEncoder() {
        return new Jackson2JsonEncoder(objectMapper());
    }

    @Bean
    Jackson2JsonDecoder jackson2JsonDecoder() {
        return new Jackson2JsonDecoder(objectMapper());
    }

    @Bean
    WebFluxConfigurer webFluxConfigurer(Jackson2JsonEncoder encoder, Jackson2JsonDecoder decoder) {
        return new WebFluxConfigurer() {
            @Override
            public void configureHttpMessageCodecs(ServerCodecConfigurer configurer) {
                configurer.defaultCodecs().jackson2JsonEncoder(encoder);
                configurer.defaultCodecs().jackson2JsonDecoder(decoder);
            }
        };
    }

to my mock setup.
