### ISSUE TITLE
Replace SpringApplication.run(Object) with type safe variants

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9170]
The `SpringApplication.run(Object)` API isn't very friendly for Ceylon and it isn't typesafe so the IDE can't help with suggestions. See [this twitter conversation for background](https://twitter.com/1ovthafew/status/862769242495647744).

In 2.0 we can replace it with overloaded versions and possibly consider dropping some of the more exotic versions.

**Comment by wilkinsona** [comment]
I wonder if we should add the new methods in 1.5.x and deprecate `SpringApplication.run(Object)`?

**Comment by philwebb** [comment]
@wilkinsona After digging into this a bit I think we can simply the API quite a bit. If we make `run` take `Class<?>` arguments, and `getSources()` take `String` arguments most people can probably still do what they need.

I doubt the `Resource` and `Pacakge` variants are used that often so we can probably just drop those. I'm tempted to try this in M1 and see who complains.

**Comment by gavinking** [comment]
Thanks, this looks perfect!
