### ISSUE TITLE
Consider if ContainerType.SIMPLE should be the default in RabbitProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9173]
See comment [here](https://github.com/spring-projects/spring-boot/pull/9055#discussion_r115894132).

It's not clear to me if we should change the value or update the Javadoc.

**Comment by garyrussell** [comment]
Unfortunately, it's not black and white - each container has certain pros and cons. I feel that changing the container type without the user explicitly choosing  to do so could cause unexpected problems for users. 

I prefer that the user explicitly opt-in to using the new container. [Documentation here](http://docs.spring.io/spring-amqp/docs/2.0.0.BUILD-SNAPSHOT/reference/html/_reference.html#choose-container).

**Comment by snicoll** [comment]
@garyrussell what puzzles me is that I think I've seen the term "legacy" to refer to the simple container. Is it reasonable that 2.0 default to something that's legacy? Are you going to remove it in a future release?

**Comment by garyrussell** [comment]
Perhaps legacy was a poor choice of words; I simply wanted to convey that simple refers to the old, existing, container. There are no plans to remove it.

Perhaps we should change the enum javadocs (in `RabbitProperties`) to:

```
 +		/**
 +		 * SimpleMessageListenerContainer - container where the RabbitMQ consumer
 +		 * dispatches messages to an invoker thread.
 +		 */
 +		SIMPLE,
```

(i.e. just drop the word legacy).

BTW, the reason I repeated the above comment on the PR as well is so the original poster of the comment would get a notification.

**Comment by wilkinsona** [comment]
Done. Thanks for the suggestion, @garyrussell
