### ISSUE TITLE
Incorrect metadata for spring.jpa.database-platform

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-boot#9180]
spring.jpa.database-platform should indicate to user that he is supposed to use JPA's provider dialect

As of now, it is:

> Name of the target database to operate on, auto-detected by default. Can be alternatively set using the "Database" enum.

Control assist also uses the same values as for spring.jpa.database but in UPPERCASE.

Spring Boot version = 1.5.2.RELEASE

**Comment by snicoll** [comment]
That's an IJ issue. I've reported [IDEA-172778](https://youtrack.jetbrains.com/issue/IDEA-172778)
