### ISSUE TITLE
Dependencies: consider removing lombok from dependencyManagement

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#9215]
`spring-boot-dependencies` currently fixes the version of lombok.

However, _lombok_ is used at compile time only and should not be considered as a requirement for application built on Spring Boot.

People working with Eclipse (and probably IntelliJ as well) are required to have the same version of lombok both in their Eclipse installation AND in their workspace projects. They usually end up in fixing the version in their project and override what is specified in SpringBoot dependencies pom. This override is causing useless Maven (and Eclipse) warnings during build.

**Comment by wilkinsona** [comment]
AFAIK, IntelliJ IDEA isn't affected and we also need the Lombok dependency management in support for start.spring.io (see #4598 and spring-io/initializr#154 for details).

You can override a version without warnings by setting the `lombok.version` property in your pom.
