### ISSUE TITLE
Add a failure analyzer for Hibernate bootstrap failure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9219]
"org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set" is quite frequent and confuse newcomers a lot. Most of the  time this error hides a database error setup. If Hibernate 5.2 has still the same behaviour it would be worth adding a failure analyzer to it.

**Comment by philwebb** [comment]
Duplicates 1573
