### ISSUE TITLE
expose unconditional classes in auto-config endpoint

### ISSUE THREAD

**Issue by rokii** [spring-projects/spring-boot#9226]
Question

In runtime, there is no way to know all auto-configurations activated.  Unconditional ones are helpful for  monitor and troubleshooting when third party starters are imported.
From debug level , positive/negative/exclusion/unconditional  can be listed in the console during startup.

Enhancement

In runtime, unconditional auto-configurations  are exposed from endpoint /autoconfig

**Comment by wilkinsona** [comment]
Thank you @rokii. There's no need to open an issue and a pull request for the same change so I'll close this one
