### ISSUE TITLE
Upgrade Mockito from 2.7.22 to 2.8.9

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#9228]
Mockito 2.8.9 is available at http://jcenter.bintray.com/org/mockito/mockito-core

**Comment by wilkinsona** [comment]
Thanks, but we use Maven Central for our dependencies rather than JCenter. We'll upgrade to 2.8.x as part of your semi-automated upgrade process as and when it becomes available in Central.
