### ISSUE TITLE
Default converters for JSR310

### ISSUE THREAD

**Issue by adammichalik** [spring-projects/spring-boot#9237]
I find myself adding a custom `StringToDurationConverter` in yet another project for the purpose of binding properties from application.yml to property beans. Wouldn't it be worth handling String to JSR310 types out of the box in Spring Boot?

Probably related to #6222 - as per @jhoeller's [comment](https://github.com/spring-projects/spring-boot/issues/6222#issuecomment-230882261):

> As for further JSR-310 support at the DefaultConversionService level, note that we have convention-based support for class-contained valueOf/of/from methods there, actually aligned with JSR-310 by design. However, for the purposes above, Duration just has a parse(CharSequence) method. We could extend our convention there to find such parse methods for String input as well, which would take us a long way... probably with no specific converters to be added for JSR-310 at all.

**Comment by philwebb** [comment]
Are you talking specifically about binding from `application.yml` to `@ConfigurationProperties` beans? If so, I think adding the additional converter should be relatively easy for us to do (it might even be in 2.0.M1 already). If you're talking about `@Value` then things get more tricky.

**Comment by adammichalik** [comment]
As far as I'm concerned, binding to `@ConfigurationProperties` beans is quite enough. BTW - I noticed Spring Data Commons has a [full set of JSR310 converters](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/Jsr310Converters.java) if it helps with anything.

**Comment by philwebb** [comment]
@jhoeller Should [these](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/Jsr310Converters.java) converters be part of `org.springframework.format.datetime.standard.DateTimeConverters`? It would seem like a shame for us to duplicate them.

**Comment by jhoeller** [comment]
`DefaultFormattingConversionService` registers a `DurationFormatter` and a `PeriodFormatter` since 4.2.4, next to the converters in `DateTimeConverters`. What would we gain by adding equivalent converters to `DateTimeConverters`? Isn't this working already with a `DefaultFormattingConversionService` overall? Are there specific cases that we're missing there?

We could nevertheless add a basic `parse(CharSequence)` convention to `ObjectToObjectConverter ` but the only difference for `Duration` and `Period` is that it would be handled by a plain `DefaultConversionService` as well then. If there is enough interest in this for simple configuration scenarios where `DefaultFormattingConversionService` isn't needed otherwise, I'm happy to consider it.

**Comment by adammichalik** [comment]
I'm on Spring Boot 1.5.3 and Spring 4.3.8. I do have `DefaultFormattingConversionService` on the classpath and the code in `org.springframework.format.datetime.standard.DateTimeFormatterRegistrar#registerFormatters` 

````java
registry.addFormatterForFieldType(Duration.class, new DurationFormatter());
````

gets executed. However, having a setup like this:

````java
@Component
@ConfigurationProperties("my-app.schedule")
@Getter
@Setter
class ScheduleProperties {
    private Duration delay;
}
````

````
my-app:
  schedule:
    delay: PT1M
````

results in an error:

````
Field error in object 'my-app.schedule' on field 'delay': rejected value [PT1M]; codes [typeMismatch.my-app.schedule.delay,typeMismatch.delay,typeMismatch.java.time.Duration,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [my-app.schedule.delay,delay]; arguments []; default message [delay]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.Duration' for property 'delay'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'java.time.Duration' for property 'delay': no matching editors or conversion strategy found]
````

The error is thrown **after** `org.springframework.format.datetime.standard.DateTimeFormatterRegistrar#registerFormatters` has run.

The error goes away if I explicitly register a

````java
    @Bean
    @ConfigurationPropertiesBinding
    public StringToDurationConverter stringToDurationConverter() {
        return new StringToDurationConverter();
    }
````

Perhaps the `DefaultFormattingConversionService` is not used in this case?

**Comment by philwebb** [comment]
Thanks @jhoeller I somehow missed those. @olivergierke Should `Jsr310Converters` be removed from Spring Data then? Or is there some reason a different set of converters is needed?

**Comment by philwebb** [comment]
@adammichalik It makes sense that this doesn't work with 1.5. We'll add a test to make sure this works in 2.0.

**Comment by adammichalik** [comment]
@philwebb fair enough, I'm happy to wait for it. Thanks!
