### ISSUE TITLE
Add response time to health indicators

### ISSUE THREAD

**Issue by michaelkuechler** [spring-projects/spring-boot#9238]
I recently ran to a situation where my `org.springframework.boot.actuate.endpoint.HealthEndpoint` became slow. debugging the application, I found that just one of the many indicators (that are pulled in without much further do on my side!) actually had a problem. yet the exact instance was hard to identify because there is no easy way to take the timings of each individual indicator.

for such cases it might proof helpful if there were an easy pluggable (or even default) feature that allows me to see individual response times of each indicator. this can be as simple as following little addition to `org.springframework.boot.actuate.endpoint.HealthEndpoint.CompositeHealthIndicator#health` (though there might be cleaner options that won't pollute the scope of `CompositeHealthIndicator`)
```
@Override
public Health health() {
	long start = System.currentTimeMillis();
	Map<String, Health> healths = new LinkedHashMap<>();
	for (Map.Entry<String, HealthIndicator> entry : this.indicators.entrySet()) {
		long start1 = System.currentTimeMillis();
		Health health = entry.getValue().health();
		healths.put(entry.getKey(), withDetail(health, "responseTimeMs", System.currentTimeMillis() - start1));
	}
	Health aggregate = this.healthAggregator.aggregate(healths);
	return withDetail(aggregate,"responseTimeMs", System.currentTimeMillis() - start);
}

/** @see Health.Builder#withDetail(java.lang.String, java.lang.Object) */
private static Health withDetail(Health health, String key, Object value) {
	Health.Builder builder = new Health.Builder(health.getStatus(), health.getDetails());
	builder.withDetail(key, value);
	return builder.build();
}
```

**Comment by philwebb** [comment]
After a little more consideration we've decided that directly recording the response time in the health indicator itself might not be the best approach. Probably a better solution would be to use Micrometer to directly monitor the underlying infrastructure that the heath endpoints are monitoring.
