### ISSUE TITLE
Executable jar issue

### ISSUE THREAD

**Issue by dwen77** [spring-projects/spring-boot#9241]
Currently, I am using spring boot 1.5.3.RELEASE and I have a problem regarding the executable jar.  I am running a executable jar as the linux service and the spring boot application has the mysql database configuration in application.properties. The command `service appname start` shows the application is started with the PID. In reality, the application is failed to start since the misconfigured mysql datasource information (db user does not exist). From the user's perspective, it gives the misleading information when running the command `service appname start`. I guess it is related to the do_start method in launch.script. It only checks the PID file to determine if the application is start successfully or not and should check the application log file to see if application is really started. 

In order to reproduce it, just make any spring boot application which contains mysql database configuration in application.properties and put a non-existing username. Start the application by command `service appname start` and see the output of the command and the log of the application.

**Comment by wilkinsona** [comment]
This is working as designed. The `start` command starts the application and checks that it has written its PID file successfully. It does not wait for the application to complete starting up as this could take an unknown amount of time and it would be impossible to distinguish between an application that has hung during startup and one that is simply taking a long time to start.

You can use the `status` command to check if the application is running. It checks for the presence of the PID file, reads the PID from the file, and checks that a process with that PID is running. If it doesn't find the file, or doesn't find a process with the required PID it will report that the service is stopped.

**Comment by dwen77** [comment]
@wilkinsona, very good and clear explanations, thanks!
