### ISSUE TITLE
Converting a Web environment to a Standard environment drops modifications made to the Web environment's property resolver

### ISSUE THREAD

**Issue by ethanrubinson** [spring-projects/spring-boot#9246]
Spring-boot version: All? Found on 1.5.3 and reproduced again on 2.0.0.BUILD-SNAPSHOT

## Demo

https://github.com/EthanRubinson/SpringBootEnvConversionBugDemo

## Summary

When a web environment is converted to a standard environment ([here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L495-L506)) only the active profiles and the property sources are copied to the new environment. Any modifications that may have been made to the original environment's propertyResolver (the conversion-service, placeholder-prefix, value-separator, or any other modifiable characteristic exposed via ConfigurablePropertyResolver.class) are not copied over.

This is a problem if a component is listening on the ApplicationEnvironmentPreparedEvent and then sets a custom ConversionService. Immediately after all of these listeners are executed ([here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L360)), the web environment is converted to a standard environment and the changes are dropped ([here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L364)).

**Comment by philwebb** [comment]
Thanks for the detailed analysis.

**Comment by EthanRubinson** [comment]
Happy to contribute! Also, on Spring Boot 1.5.x the property to put in the application.properties file is `spring.main.web-environment=false`

**Comment by snicoll** [comment]
@ethanrubinson happy to review a PR so fire away!

**Comment by philwebb** [comment]
It might be worth extracting that conversion code to a small package private utility class. That way we can write some focused tests to check things get copied correctly.

It's annoying that we can't detect the type of context we need early. Unfortunately we need to call the environment post processor to load the config files. This could set the `spring.main.web-environment` property, which means we need to change it.

One other option we could investigate is to create a `StandardEnvironment` then try to decorate it later to be a `ConfigurableWebEnvironment`.

**Comment by ethanrubinson** [comment]
@philwebb I agree, I'm working on a PR now which extracts the environment conversion code into a utility class.

**Comment by philwebb** [comment]
@ethanrubinson I think it's best just to fix your use-case for now. The reflection approach seems a bit too hacky to me.

**Comment by ethanrubinson** [comment]
@philwebb I'll submit both. The reflection case is *very* hacky... it hurts just coding it haha.

**Comment by ethanrubinson** [comment]
^ That PR is the one with reflection which copies over as much of the original environment's configuration as possible

**Comment by ethanrubinson** [comment]
^ That one is the simple fix for just the conversion service.

**Comment by philwebb** [comment]
Thanks
