### ISSUE TITLE
Default Hibernate auto-DDL to "none" with embedded database when Flyway or Liquibase is detected

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#9262]
I spent a while chasing my tail because in my unit test Boot was having Hibernate drop and recreate my tables, with semantic errors in the schema. While I understand the motivation for using create-drop as the default with an embedded database, I suggest that if practical this should be disabled and defaulted to "none" if Flyway or Liquibase is active, as the user has clearly signaled an intention to manually control the database schema.

**Comment by snicoll** [comment]
@chrylis there are two requests here really:

1. Stop switching ddl-auto to `create-drop` when an embedded database is detected, _and_
2. Set ddl-auto to `none` when Flyway/Liquibase is detected

I think 1 is interesting (even though I don't know yet how to implement it). 2. is a different story and I don't think we should do that.

**Comment by andersonkyle** [comment]
Hi @snicoll

Can you elaborate as to why you don't agree with # 2?  

My thinking aligns with @chrylis on this issue, when Flyway/Liquibase is present, ddl-auto should be `none`.

Thanks!

**Comment by snicoll** [comment]
@andersonkyle It depends what you mean by "when Flyway is detected". First of all you want to be sure that's flyway has ran and that's not easy. Then if you want, for whatever reason, that hibernate validates your schema (using `validate`), Spring Boot would override the settings behind your back to `none`. 

Perhaps it would be acceptable if the value isn't set at all. We need to check first how reliably we can check if flyway has ran. In any case, there are two feature requests in this issue and I'd advise we focus on the first one.

**Comment by snicoll** [comment]
I've something in 8d42852 that looks promising and convoluted. We need to break the cycle between flyway/liquibase and JPA so I had to introduce a strategy interface in Spring Boot. I still need to figure out what to do with our own initialization feature (We should probably default to none if a schema is set or something). All in all, I am not sure yet I want to merge this.
