### ISSUE TITLE
InternalResourceViewResolver not being added to context automatically.

### ISSUE THREAD

**Issue by pemmasanikrishna** [spring-projects/spring-boot#9267]
I'm using Spring Boot 1.5.3.RELEASE. As per the docs , InternalResourceViewResolver with bean id ‘defaultViewResolver’ should be added along with other view resolvers when `@AutoConfigureWebMvc` is used, so that I can configure spring.mvc.view.prefix and spring.mvc.view.suffix in the external properties file. But when I do `dispatcherServlet.getWebApplicationContext().getBean(ViewResolver.class);`
I got an exception stating "org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.servlet.ViewResolver' available: expected single matching bean but found 2: mvcViewResolver,beanNameViewResolver" . So from this I can understand that only 2 beans mentioned in the exception are being initialized.

**Comment by wilkinsona** [comment]
A Spring Boot 1.5.3 application, both when running its main method and when running an `@AutoConfigureWebMvc`-annotated test,  gives me four `ViewResolver` beans:

```
beanNameViewResolver=org.springframework.web.servlet.view.BeanNameViewResolver@6ac4944a, 
mvcViewResolver=org.springframework.web.servlet.view.ViewResolverComposite@5a772895,
defaultViewResolver=org.springframework.web.servlet.view.InternalResourceViewResolver@39fc6b2c,
viewResolver=org.springframework.web.servlet.view.ContentNegotiatingViewResolver@704b2127
```

Can you please provide a small sample that reproduces the behaviour you are seeing?

**Comment by pemmasanikrishna** [comment]
Below snippet is my config, and after configuring `spring.mvc.view.suffix` in application.properties file, and returning a string from the controller, the dispatcher is complaining that its not able to find a view with the string that i'm returning. So, I have autowired dispatcherServlet and ` dispatcherServlet.getWebApplicationContext().getBean(ViewResolver.class);` executed this line got exception stating only 2 view resolvers are initialized, where as there should be 4.
`
@SpringBootApplication
@AutoConfigureWebMvc
public class FaultTrackerBootApplication extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(FaultTrackerBootApplication.class);
	}

	public static void main(String[] args) {
		SpringApplication.run(FaultTrackerBootApplication.class, args);
	}
}`

**Comment by wilkinsona** [comment]
As described in its javadoc, `@AutoConfigurationWebMvc` is for Spring MVC-based tests. As such it should be used on your test class rather than your main application class. You should remove it from your `Application` class as it won't be having any effect.

As I indicated above, I cannot reproduce your problem. Can you please provide a complete, small sample (something that we can `git clone` and unzip), rather than trying to piece things together from issue comments?

**Comment by pemmasanikrishna** [comment]
Its working fine now just after removing all the annotations except @SpringBootApplication and reimporting the application into STS. Not able to replicate it. And now it started taking value from ` spring.mvc.view.suffix `

**Comment by wilkinsona** [comment]
Thank for letting us know
