### ISSUE TITLE
Logback configuration is reinitialized when parent is a cloud-context bootstrap and the child is a boot-context one

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#9269]
Hi

I'm facing an issue about logback reinitialisation. In my logback I have a File Appender with a name containing a timestamp `yyyyMMddHHmm`. As my logback is not in my application classpath I point it out with `logging.conf` key. 

Some times (most of time when my batch application is launched at the end of minute unit (e.g at 15:00:50, 12:32:55 ... ) my application create two files

`my-report-20170518150000.report` which is empty
`my-report-20170518150100.report` which is populated with my logs.

My application is a spring-boot application with a spring-cloud-netflix feign client used to call a remote application.

I noticed that 2 contexts are created . The parent one initalized by spring-cloud bootstrap (http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_spring_cloud_context_application_context_services) and the spring-boot one. Each context uses `LoggingSystem` feature (I didn't disable it). So when the parent is created at 11:14:55 and the child is created at 11:15:01 I get 2 files from my file appender. By the way the last one is only used.

Is this issue is related on this one :https://github.com/spring-projects/spring-boot/issues/6688?

For now is to disable `LoggingSystem`. I thought disable bootstrap context (`spring.cloud.bootstrap.enabled=false`) but It prevent, If I understand, the use of cloud features.

Do you have any idea ?

Thanks for your help

**Comment by philwebb** [comment]
It sounds like there are a lot of moving parts here and it's not clear if this is a bug or not. Are you able to create a minimal sample that shows the problem?

**Comment by wilkinsona** [comment]
This is standard behaviour for a Spring Cloud application that's using the bootstrap context. It [deliberately reinitialises the logging system](https://github.com/spring-cloud/spring-cloud-commons/blob/01cca0275a57adfb930698c819417e26c75f2158/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L115-L140) so as to pick up any logging configuration that's appeared from, for example, a config server.

Disabling the logging system will avoid the problem you're seeing, at the cost of reducing the ways in which logging can be configured. I can't think of a better alternative at the moment as what's happening is really a side-effect of what Spring Cloud is doing.

**Comment by RaphC** [comment]
Thank you for your responses.
