### ISSUE TITLE
Actuator health endpoint is "full content" for anonymous user when security.enabled is false and health.sensitive is true

### ISSUE THREAD

**Issue by andreiepure** [spring-projects/spring-boot#9273]
### Summary

The [Spring Boot Actuator documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html) specifies that when management.security.enabled is false and endpoints.health.sensitive is true, the /health endpoint should return "status only".

### Actual Behavior

When I set in application.properties:
```
management.security.enabled=false
endpoints.health.sensitive=true
```
and I access the /health endpoint, I get full content for anonymous authentication.

```

    {
        "status": "UP",
        "diskSpace":
        {
            "status": "UP",
            "total": 64315453440,
            "free": 33504604160,
            "threshold": 10485760
        },
        "db":
        {
            "status": "UP",
            "database": "MySQL",
            "hello": 1
        }
    }
```

### Expected Behavior
For the above setting, when accessing the endpoint as an anonymous user, I should get only

```
    {
        "status": "UP"
    }

```

### Configuration

Spring Boot 1.5.2.RELEASE (spring-security-web 4.2.2.RELEASE).
REST endpoint access with Firefox 53 and [RestClient ](http://restclient.net/) addon

```
server.ssl.enabled=true
server.ssl.client-auth=want
```
(but when testing, I didn't present any certificate, so it was one-way SSL)

Note: this was initially reported on Spring-Security issue [4329 ](https://github.com/spring-projects/spring-security/issues/4329)by mistake, which was closed in favor of this report.

**Comment by mbhave** [comment]
@andreiepure This looks like a bug in the documentation. If `endpoints.health.sensitive` is set to `true`, unauthenticated requests to the `/health` endpoint are not allowed. Once authenticated, the content returned depends on whether the authenticated user has the right role or not. If `management.security.enabled` is set to `false`, full health details are exposed.
