### ISSUE TITLE
@ConditionalOnExpression  operator list 

### ISSUE THREAD

**Issue by cuisongliu** [spring-projects/spring-boot#9274]
example:

```spring.datasource.druid.aop-types```   properties is a list .the following on annotation means the list contains value of 'name'. 

     @ConditionalOnExpression("'${spring.datasource.druid.aop-types}'.contains('name')")

But, that no effect.

**Comment by philwebb** [comment]
The `@ConditionalOnExpression` annotation just evaluates SPeL expressions. It's not aware of binding concerns so it won't know how to convert `aop-types` to a list. It also won't support relaxed binding (so it you happen to use `spring.datasource.druid.aopTypes` in your properties this won't work).

I'd suggest writing your own `Condition` implementation.
