### ISSUE TITLE
Jackson: different JSON representation for java.util.Date and JODA DateTime

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#9276]
`ISO8601` date format is used when Jackson is configured to serialise dates as _text_. However `java.util.Date` and `org.joda.time.DateTime` have slightly different text representation as shown below:

```
java.util.Date           1970-01-01T01:00:00.000+0100
org.joda.time.DateTime   1970-01-01T01:00:00.000+01:00
```

A workaround is to explicitly set the desired format as follows:
```
spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
```

That same format will be used in both cases.

Note: JODA's format is causing issues on some platforms like Android and/or iOS.
Note2: tested on SpringBoot `1.4.6.RELEASE`

**Comment by wilkinsona** [comment]
This is Jackson's standard behaviour:

```java
ObjectMapper mapper = new ObjectMapper()
		.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
		.registerModule(new JodaModule());
DateTime dateTime = new DateTime(2017, 5, 22, 12, 00, DateTimeZone.UTC);
System.out.println(mapper.writeValueAsString(dateTime));
System.out.println(mapper.writeValueAsString(dateTime.toDate()));
```

Produces:

```
"2017-05-22T12:00:00.000Z"
"2017-05-22T12:00:00.000+0000"
```
