### ISSUE TITLE
Setting MODE in conf file fails on CentOS (AWS AMI)

### ISSUE THREAD

**Issue by Glamdring** [spring-projects/spring-boot#9294]
I am trying to run an executable jar (with /etc/init.d as pointed here https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-script-customization-conf-file)

I tried to use a conf file and set the MODE. However, if the mode is set in the properties file, the comparisons in the bash script (prefixed to the jar) do not work. I didn't have time to investigate why, but when you output say: echo "${MODE}.foo" instead of "service.foo" it outputs fooice. I'm not a bash guru, so I don't immediately know why that is the case.

Even if you set it to "auto" in the conf file, the comparisons don't work - if output, the mode appears empty.

(by "comparisons don't work", I mean the once that are supposed to set the action from "run" to "start")

**Comment by wilkinsona** [comment]
Can you please provide an example `.conf` file that triggers the problem you've described?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Glamdring** [comment]
The original .conf file that caused the exception is lost, but it contained a single line:

MODE=auto

**Comment by wilkinsona** [comment]
The mode's default value is `auto` so, if `${MODE}` is empty, then you must have set it to an empty value. I would guess that you had a space in your `.conf` file, something like

```
MODE= auto
```

You described the `.conf` file as a properties file above. Please note that it isn't a properties file. It's a script that is loaded by the launch script using the [source command](https://bash.cyberciti.biz/guide/Source_command).

**Comment by Glamdring** [comment]
@wilkinsona yes, sorry for not using the agreed terminology. And no, I didn't have a space. I also tried setting an environment variable instead of using the .conf file, with the same result.
Did you actually test it, or assumed it's "invalid" because I used the incorrect terminology? Also, I didn't say it's empty - I said the comparison doesn't work. Also, I said it doesn't work when set to service either.

And this "instead of "service.foo" it outputs fooice" - means it's been interpreted somehow strangely, rather than being empty.

Please someone test it on CentOS

**Comment by wilkinsona** [comment]
> Did you actually test it

Yes, of course. I've tested it on Linux cents 2.6.32-573.el6.x86 64

> Also, I didn't say it's empty

I believe that you did: " if output, the mode appears empty"

Given the little information that you have provided I have done my best to help you and to suggest a possible reason for the problem that you're experiencing. In the absence of any further information, particularly concrete steps to follow to reproduce the problem, I can't justify spending any more time on this. Sorry.

**Comment by Glamdring** [comment]
@wilkinsona 
Okay, than a suggestion - validate the input. Check if the value is among the allowed values,and if not, fail. Currently it assumes "run", as the if-condition about service or auto is false.

That would solve it, and other similar problems (like whitespaces etc.). 

If it works on CentOS, it might be Amazon AMI issue in particular (my distro: 4.9.20-11.31.amzn1.x86_64)

I got my problem solved, as just not setting a value works. Just trying to help. And these are all the steps - simply setting the variable in a conf file doesn't work as expected :)
