### ISSUE TITLE
Consider adding `jackson-datatype-jsr310` to Web starter

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#9297]
In a similar fashion like #9229, it would be nice if Web starter would pull in `jackson-datatype-jsr310` module.

In addition, perhaps a case could be made for other modules that are a part of [`jackson-modules-java8`](https://github.com/FasterXML/jackson-modules-java8).

**Comment by snicoll** [comment]
There are more than one starter where Jackson is provided. I guess `spring-boot-starter-jackson` is a bit weird, the alternative is that we should include in the `data-rest` and `webflux` starters (perhaps `jersey` as well?). 

A dedicated starter would make #400 much easier to implement in a customization though.

**Comment by philwebb** [comment]
I think a starter makes sense, we don't want to duplicate the same dependencies all over the shop Perhaps we should call it something more general like `spring-boot-starter-json`?

**Comment by snicoll** [comment]
>  dedicated starter would make #400 much easier to implement in a customization though.

I take it back. This would be a transitive dependency of a starter chosen on the initializr so that wouldn't change anything.

**Comment by snicoll** [comment]
That change breaks the glassfish integration test

**Comment by snicoll** [comment]
Follow-up on that issue on #9391
