### ISSUE TITLE
Log context path at startup

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#9299]
When starting a web application, there is a nice log message stating which port your server is running on:
`2017-05-24 09:32:50,586 - INFO : MESSAGE=[Jetty started on port(s) 7000 (http/1.1)] TID=[main] CLASS=[org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer]`

I've run into several occassions though where the context path is also relevant to know. Since you can set it with Spring Boot via server.contextpath, I was thinking it might be a good idea to print this out as well to give developers a more complete picture of where their application is running.

Is this something that could be done in Spring Boot, or would that need to be suggested at the Jetty team?

**Comment by philwebb** [comment]
I'm pretty sure that message is generated directly by us so it should be possible to add context paths (as long as we can find that information from the server).

**Comment by snicoll** [comment]
Closing in favour of PR #10544
