### ISSUE TITLE
Allow customization of resolving strategy of externalized configuration files

### ISSUE THREAD

**Issue by davidkron** [spring-projects/spring-boot#9300]
Currently, the main process of searching and resolving configuration files is done in the private class `Loader` inside `ConfigFileApplicationListener`. As this class is private, there is no way to extend or override it so we could implement advanced configuration file resolving strategies.

I think it would be useful to pull the methods `getSearchLocations` and `getSearchNames` out of the `Loader` class and abstract them with some kind of config loading strategy, with the current implementation as the default. With this, configuration file resolving could be easily customized, if needed.

**Real-life scenario**
In my company, we have existing deployment policies concerning the format and location of externalized configuration files. As we do not only create Spring Boot applications and we have had good experiences with our policies, we do not want to alter them. 

The format of our configuration structure looks like this:
```
/path/to/configuration/app1/config.properties
/path/to/configuration/app1/middleware.properties
/path/to/configuration/app1/...
/path/to/configuration/app2/config.properties
/path/to/configuration/app3/config.properties
```

On our production machines, we would set the system variable `spring.config.location` to `/path/to/configuration/` and `spring.config.name` to `config`. When we want to deploy multiple applications (packaged as WAR) on the same servlet container, the configuration loading strategy from Spring Boot doesn't work anymore, because all applications running inside the same JVM get the same `spring.config.location`. It would search for configuration files inside `/path/to/configuration/`. But we would like to get Spring Boot to search in an additional sub-folder (= application name) inside the configuration folder.

I know that we could set `spring.config.name` to a per-application value. But if you work in an environment with existing naming policies and conventions, this is definitely not an option. And speaking for my personal preferences, putting configuration files of multiple applications together in a single folder is, at least to me, not really a good style.

Maybe this scenario is already possible with Spring Boot. If so, I'm sorry for opening this issue. But I did not find anything related to this in the documentation. And by directly inspecting the Spring Boot code, I also couldn't find a solution.

**Comment by wilkinsona** [comment]
Why have you restricted yourself to using a System property for the configuration of `spring.config.location`? As you've observed, that makes it JVM-wide which can be problematic when deploying multiple applications in the same container. 

I would recommend that you set `spring.config.location` while building your `SpringApplication` instance (so either in its `main` method or in its `SpringBootServletInitializer` subclass using `SpringApplicationBuilder.properties(String...)` or similar. Does that not meet your needs?

**Comment by davidkron** [comment]
I actually like that `spring.config.location` can be set from the outside (system properties) and doesn't require hard-coding inside the application. So specifying the configuration location is not the concern of the developer but the server administrator. So I would like to still use this feature. But I think this wouldn't work anymore, if I configured the location with `SpringApplicationBuilder.properties(String...)`?

I tried to set `spring.config.location` to something like `"${spring.config.location}/app/"` in `SpringApplicationBuilder`, with the idea in mind, that it would take the system property and append it with the application suffix. But according to the documentation, the system properties have higher priority than default properties, so this didn't work.

**Comment by wilkinsona** [comment]
If you want the root location of the configuration to be externalised with a JVM-wide value, then I'd use a system property for that. Each app can then customise its `spring.config.location` relative to the root location. Something like this:

```java
new SpringApplicationBuilder(YourApplication.class)
        .properties("spring.config.location:${your.config.root}/your-app")
        .run(args);
```

**Comment by davidkron** [comment]
Ok, this sounds like a solution that could work. I will try to implement it that way.
