### ISSUE TITLE
The DevTools does not work for kotlin.

### ISSUE THREAD

**Issue by Jackson8Zhang** [spring-projects/spring-boot#9312]
The DevTools does not work.
Spring boot 2.0.0.M1 for kotlin.

**Comment by wilkinsona** [comment]
It works fine for me with Spring Boot 2.0.0.M1 and IntelliJ IDEA. If you'd like us to spend some time trying to help you, you're going to have to spend some time describing your setup and how you have determined that it does not work.

**Comment by Jackson8Zhang** [comment]
@wilkinsona
![11-2](https://cloud.githubusercontent.com/assets/25034767/26432601/73415240-412f-11e7-83f9-9b66c1a43b69.png)

The server is restarted, but content has not changed.

**Comment by philwebb** [comment]
@Jackson8Zhang That's not really enough information I'm afraid. Please provide a small sample project that we can download and run along with the exact settings and the steps that we need to follow.

**Comment by Jackson8Zhang** [comment]
@philwebb 
![11-3](https://cloud.githubusercontent.com/assets/25034767/26432907/b690b84a-4131-11e7-83c0-d9f04b949372.png)
This is my configuration.Run it for Intellij idea.

**Comment by Jackson8Zhang** [comment]
@philwebb 
If the browser does not restart, the content is not changed, forced to refresh also doesn't work.After the restart the browser, the content changed

**Comment by wilkinsona** [comment]
@Jackson8Zhang That sounds like a browser issue, rather than anything to do with Spring Boot or Kotlin. If you'd like us to spend any more time on this please provide what Phil asked for above.

**Comment by Jackson8Zhang** [comment]
@wilkinsona Sorry. I don't know. Please close the issue.

**Comment by jrempel1** [comment]
I'm experiencing same issue. M4 using spring boot project.
