### ISSUE TITLE
Add support for AMQP 1.0 Messaging using JMS

### ISSUE THREAD

**Issue by tabish121** [spring-projects/spring-boot#9313]
In order to support quick starts for those wishing to use ISO AMQP v1.0 clients a new auto-configure and starter could be added that utilizes the Qpid JMS project which allows for JMS style messaging mapped onto the AMQP v1.0 protocol.

This would allow a fast path for those looking to communicate with various messaging systems that support AMQP v1.0 such as the Qpid Java and C++ brokers, ActiveMQ, ActiveMQ Artemis, Azure ServiceBus etc using the ISO stand AMQP v1.0 protocol with a familiar JMS experience mapped on top.  To make this possible the Qpid JMS client library can be used.  This library implements all of the current AMQP v1.0 to JMS mappings and has been tested against a variety of messaging brokers.

**Comment by wilkinsona** [comment]
Duplicates #9315
