### ISSUE TITLE
Spring Boot 1.5 Actuator Endpoint Security vs Docs

### ISSUE THREAD

**Issue by bplies-IAS** [spring-projects/spring-boot#9314]
After upgrading 1.4.1 to 1.5.3 the /health endpoint stopped allowing summarized responses to unauthenticated users in accordance with the table at the bottom of https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html#production-ready-health-access-restrictions

Before

| management.security.enabled | endpoints.health.sensitive | Unauthenticated | Authenticated |
| --- | --- | --- | --- |
| false |  false | Full content |  Full content |
| false |  true |  Status only |  Full content |
| true | false | Status only |  Full content |
| true | true |  No content | Full content |

After

| management.security.enabled | endpoints.health.sensitive | Unauthenticated | Authenticated |
| --- | --- | --- | --- |
|false|  false| Full content|  Full content|
|false|  true|  **Full content**|  Full content|
|true| false| Status only |  Full content|
|true| true|  No content| Full content|

**Comment by philwebb** [comment]
This was an intentional change. See [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#actuator-security) of the release notes.

**Comment by bplies-IAS** [comment]
Yes I'm aware of the release notes.  The docs reflect the older expectation then.

**Comment by philwebb** [comment]
Oh OK, I misunderstood the report. Thanks.

**Comment by bplies-IAS** [comment]
Given how the expectations are laid out in a convenient "truth table" of sorts, this could easily be codified into unit tests that assert the stated behavior.

**Comment by mbhave** [comment]
Duplicate of #9273. 

The `endpoints.health.sensitive` flag is used only when the `management.security.enabled` flag is set to `true`. It determines whether unauthenticated access are allowed to view the status or just get an error. 
The `management.security.enabled` is used to expose all the actuators without authentication thereby removing the need to further check for the `sensitive` flag and display full health details(consistent with the other actuator endpoints).
