### ISSUE TITLE
Rework build and release process

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9316]
Out current build is quite complex due to the bamboo release process. We should try to simplify it, work out a way to do direct releases and try to pipeline it.

**Comment by philwebb** [comment]
Things we'd like to do:

- [ ] Support timestamped SNAPSHOT versions in published POMs
- [ ] Make our published POMs simpler (use maven-flatten-plugin)

**Comment by philwebb** [comment]
Things to port:
- [ ] #10021

**Comment by vpavic** [comment]
Regarding the release process, I recently noticed that  Boot `2.0.0.M4` (which was released on Sep 15th) wasn't published to SDKMAN so I wonder if something about that part of the process can be addressed here as well?

**Comment by wilkinsona** [comment]
While we haven't been consistent here, the rule is that we only publish releases (and not milestones and release candidates) to SDKMAN.

**Comment by vpavic** [comment]
I see, thanks for the info, I wasn't aware of that.
