### ISSUE TITLE
Ensure that Boot applications built with Maven use the `-parameters` compiler flag by default

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#9323]
In #9297 we're considering adding jackson modules to our web starter. One of those modules, the [parameter-names](https://github.com/FasterXML/jackson-modules-java8/tree/master/parameter-names) one, is only useful if the JDK compiler has the `-parameters` option set.

This issue is about checking the various places where this option should be set.

**Comment by snicoll** [comment]
So the best we can do now [MCOMPILER-298](https://issues.apache.org/jira/browse/MCOMPILER-298) is fixed is wait for the next release of the `maven-compiler-plugin` and add the `parameters` flag to it.

**Comment by philwebb** [comment]
This is super nice when combined with Jackson Java 8 support.

**Comment by snicoll** [comment]
The vote for the `maven-compiler-plugin` 3.6.2 release [has started](http://maven.40175.n5.nabble.com/VOTE-Apache-Maven-Compiler-3-6-2-td5911534.html)
