### ISSUE TITLE
"Started Application in x seconds" a bit confusing

### ISSUE THREAD

**Issue by ben3000** [spring-projects/spring-boot#9325]
The output by my Spring Boot (currently 1.4.1) application upon successful completion is:

`Started Application in x seconds (JVM running for y seconds)`

Users at my site who use my command-line tools find this confusing because it seems to them that the application finished as soon as it started. (Candidly, I did a double-take when I first used a Spring Boot that output this line). I'd like to see this output changed to something like:

`Application completed in x seconds (JVM ran for y seconds)`

**Comment by wilkinsona** [comment]
IMO, the log output is entirely accurate at the moment.

The `Started …` log output is produced once the application context has been refreshed and any registered `SpringApplicationRunListener`s have been notified that the run method has finished. The application is still alive at this point, and may continue to be alive indefinitely so it would be inaccurate if it said `Application completed …` at this time.

The application will stay alive if there are any non-daemon threads (as happens in, for example, a web application), or the JVM will begin to exit and the application context will be closed. Only once that close processing has been finished would it be reasonable to consider the application to have completed.

If you do not want the log message to appear you can disable it. Either by setting `spring.main.log-startup-info: false` or by calling `setLogStartupInfo` on `SpringApplication`.
