### ISSUE TITLE
Console will print "Using default security password ..." if base package name don't start with "com.***"

### ISSUE THREAD

**Issue by Acris** [spring-projects/spring-boot#9326]
Hello,
I am meet a strange bug and I need some help for this.
(Sorry for my bad English,I'll try to describe it as complete as possible)

Spring Boot version: 1.5.3.RELEASE
JDK version: 1.8.0_131
IDE: Intellij IDEA
Maven version: 3.5.0
OS: Windows 10 Pro x64 version 1703

This the sample project for this issue is here: https://github.com/Acris/spring-boot-security-issue-9326

This project has two modules, the `uw-auth-server` is a spring security module, and I writed a `WebSecurityConfig` to implement my own authentication logic, which in here: https://github.com/Acris/spring-boot-security-issue-9326/blob/master/uw-auth-server/src/main/java/uw/auth/server/config/WebSecurityConfig.java
And the `uw-auth-server-demo` is a demo module and it's depend on `uw-auth-server`.

Now I'll tell you how to reproduce this bug. By default, the `uw-auth-server` base package name is `uw.auth.server`. After you get code from my repo, you should run `mvn install` in `uw-auth-server` module, when finished, run `mvn install` in `uw-auth-server-demo` . Then start  `uw-auth-server-demo`, you will see a message in console: "Using default security password: 1e8133c5-0ac6-4aeb-9c05-d0e80e9ce352" 

**BUT**, if you rename the package name in `uw-auth-server`, for example, if I rename `uw.auth.server` to `com.auth.server`, and run `mvn install` in `uw-auth-server` again, and in `uw-auth-server-demo` module, re-import `UserAuthenticationService` in `com.reorz.security.UserAuthenticationServiceImpl` with correct package name, and start  `uw-auth-server-demo` again, you will see the message like "Using default security password: 1e8133c5-0ac6-4aeb-9c05-d0e80e9ce352" is disappered.

---

**I don't know why different package name have different behavior.**
Theoretically, I already use my own Authentication Provider, so the console shouldn't show the "Using default security password: ...." message. 
I debugged it, I found if `uw-auth-server`'s base package name start with `uxx.xxx`, `DefaultInMemoryUserDetailsManagerConfigurer.configure()` will be invoked, which in `org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration`. If the base package name start with `cxx.xxx`, this method will not be invoked.

Such a strange bug, I don't change any code  except the package name. 
Thank you.

**Comment by wilkinsona** [comment]
Thanks for the sample that reproduces the problem.

You've written some of your own auto-configuration (`SecurityAutoConfig`) but haven't ordered it (using `@AutoConfigureBefore` or `@AutoConfigureAfter`). That means that you haven't said whether it should run before or after Spring Boot's security auto-configuration. The default ordering for auto-configuration is alphabetical using the fully-qualified class name. This is why you see the order change when you rename the package from `uw.*` to `com.*`. The former is after `org.springframework.boot.*` whereas the former is before it.

**Comment by wilkinsona** [comment]
On an unrelated note, I noticed that you're using `@ComponentScan` in an auto-configuration class. I would recommend that you do not do that as it can lead to an auto-configuration picked up components unintentionally. You can use `@Import` to import other configuration classes explicitly instead.

**Comment by Acris** [comment]
Hi Wilkinson,
Thank you very much for your answer, I resolved it by added `@AutoConfigureBefore(SecurityAutoConfiguration.class)` annotation.
👍
