### ISSUE TITLE
@ConfigurationProperties nested properties not populated

### ISSUE THREAD

**Issue by muka** [spring-projects/spring-boot#9327]
Hi
I am using a class with `@ConfigurationProperties` from a YML file. It get loaded fine but some nested property does not get parsed.

For example this YML has a "username" field
- https://github.com/raptorbox/raptor/blob/v4/config/raptor.yml#L56

The corresponding class is 
- https://github.com/raptorbox/raptor/blob/v4/raptor-models/src/main/java/org/createnet/raptor/models/configuration/BrokerLocalUser.java#L29

At runtime I get NPE on both `username` and `password` but roles are available. Same happens for the `artemis` property. 

May be the case that such nested strings get somehow skipped?

Thanks

**Comment by wilkinsona** [comment]
@muka Can you please put together a small sample that illustrates the problem?

**Comment by muka** [comment]
Thank you
I prepared this  https://github.com/muka/boot-issue-9327

I noticed this happens using a bean for `PropertySourcesPlaceholderConfigurer` so the issue may reside there instead. 

It is reproducible, removing the above bean and loading from and expected location eg. `application.yml` it works 

Thank you

**Comment by wilkinsona** [comment]
Binding of configuration properties doesn't use `PropertySourcesPlaceHolderConfigurer` and its properties and a source, it uses the `ApplicationContext`'s `Environment`.

If you want to use a configuration file other that `application.yml` you have a couple of options:

- Set `spring.config.name` so that the `Environment` is populated using the custom file
- Use an `EnvironmentPostProcessor` to add a `PropertySource` to the `Environment`

**Comment by muka** [comment]
Thank you for your feedback,
I implemented the `EnvironmentPostProcessor` but still only **some** property remain null while other are set. 

Seems there is a pattern where primitive values remain null if there are subclasses at the same level.
If there are only primitive values, they get populated correctly

I used this sample as it fit my use-case https://stackoverflow.com/questions/37888231/how-to-manage-spring-cloud-bootstrap-properties-in-a-shared-library

**Comment by wilkinsona** [comment]
> Seems there is a pattern where primitive values remain null if there are subclasses at the same level.

That shouldn't be the case. Assuming I have understood your description correctly, we have that arrangement in several places in Spring Boot's own code and it works fine. Perhaps you can update your sample and we can take another look?

**Comment by muka** [comment]
I assume indeed I am doing it wrong.. but I spent pretty much time on that issue and cannot find a good reason for it in documentation or online references

I updated the sample repo  https://github.com/muka/boot-issue-9327

Thank you

**Comment by wilkinsona** [comment]
You need to provide a setter for the `artemis` property

**Comment by muka** [comment]
Oh no, it was that simple! Thank you very much for your support
