### ISSUE TITLE
None of my properties are found - wrong application.properties loaded

### ISSUE THREAD

**Issue by patrickjamesbarry** [spring-projects/spring-boot#9329]
<spring.boot.version>1.5.3.RELEASE</spring.boot.version>
<jersey.version>2.25.1</jersey.version>

We are using spring-boot-starter-jersey.  We have a library/dependency that we are having to repackage, so Jersey can scan the resources inside of it.  The problem I ran into was that the dependency had an application.properties in it.  When I ran our spring-boot service, none of our properties were resolving. This is because spring-boot was loading the application.properties file found in the dependency jar, before the actual service's application.properties.  I confirmed this by printing out

```
try {
           Enumeration<URL> urls=  
           Thread.currentThread().getContextClassLoader().getResources("application.properties");
           System.out.println("Found these files: " + Collections.list(urls));
        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Our plugin config**
```
 <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <requiresUnpack>
                                <dependency>
                                    <groupId>com.my.stuff</groupId>
                                    <artifactId>dependency-common</artifactId>
                                </dependency>
                            </requiresUnpack>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

```
My work-around was removing the application.properties file from the dependency because I luckily did not need. However, this seemed like a problem to me that might impact others.

**Comment by wilkinsona** [comment]
This is the [expected and documented behaviour](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files). By default, `application.properties` is loaded from (among other locations) the root of the class path.

**Comment by patrickjamesbarry** [comment]
So what is the expected behaviour when this file exists in the root of the jar you are repackaging, and the actual project that you are in?

**Comment by wilkinsona** [comment]
The expected behaviour is that it loads a single `application.properties` file from the class path. If there are multiple such files on the class path then the first one that is found will win (the standard behaviour for class path-based resource loading).
