### ISSUE TITLE
Spring executable jar built with gradle giving  bad interpreter: Text file busy error on Centos 7

### ISSUE THREAD

**Issue by Dannybrown2710** [spring-projects/spring-boot#9334]
I am facing an issue in running the executable jar on Centos7.
My build.gradle looks like this

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

springBoot {
    executable = true
}

jar {
    baseName = 'ONAPP'
    version =  '0.1.0'
      manifest {
        attributes 'Main-Class': 'com.ota.Application'
    }
     from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

bootRepackage {
	mainClass='com.ota.Application'
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-data-rest")
    compile("org.springframework.boot:spring-boot-starter-data-mongodb")
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

**Comment by wilkinsona** [comment]
Can you please explain why you think this is a problem with Spring Boot? The error would suggest that a process has the jar open for writing at the same time as you are trying to execute it

**Comment by Dannybrown2710** [comment]
Actually I just created the jar with this configuration, copied it via ftp and tried to run it and received this error. There is no such process that has opened jar for writing.

**Comment by wilkinsona** [comment]
>  There is no such process that has opened jar for writing.

The FTP server must have opened the file for writing. Have you verified that it has closed it before trying to execute it? You can use `lsof` to check what processes have a particular file open.

**Comment by Dannybrown2710** [comment]
Yes Wilkinsona, I have verified everything. I have done all possible stuff, but still receiving the same error.

**Comment by wilkinsona** [comment]
Can you please provide precise and detailed steps to reproduce the problem?

**Comment by Dannybrown2710** [comment]
Ok sure, would send all the possible code snippets in some while.

**Comment by Dannybrown2710** [comment]
# **This is my build.gradle**

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

springBoot {
    executable = true
}

jar {
    baseName = 'OTA'
    version =  '0.1.0'
      manifest {
        attributes 'Main-Class': 'com.ota.Application'
    }
     from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

bootRepackage {
	mainClass='com.ota.Application'
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-data-rest")
    compile("org.springframework.boot:spring-boot-starter-data-mongodb")
    testCompile('org.springframework.boot:spring-boot-starter-test')
}

I built my application with this.
Created FTP with server and pasted this file in a directory
Then ran the command
sudo ln -s /mm/ota.jar /etc/init.d/ota

then started my application , received the above error
