### ISSUE TITLE
RabbitMQ Retry Configuration Utility

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#9337]
Consider exposing `RabbitAutoConfiguration.RabbitTemplateConfiguration.createRetryTemplate()` for reuse.

It could be a `@Bean` but it might be preferable to make it a top-level `static` utility method in `RabbitAutoConfiguration` (or elsewhere).

That way, it could be used when programmatically creating a `RabbitTemplate`, or when overriding the auto configured `RabbitTemplate` `@Bean`.

The specific use case is [here](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/69) in spring-cloud-stream where we need to programmatically create the template, but wish to utilize boot's retry properties.

Of course, we can use the properties directly, but having this as a bean or utility method would avoid code duplication.

I raised this as an issue rather than submitting a PR because I need guidance from the Boot team for their preferred direction.

cc/ @snicoll

**Comment by snicoll** [comment]
Though one. You could argue that the `RabbitTemplate` could also be customized isn't it? What if you want all boot's default for the `RabbitTemplate` but XYZ? 

If that's a valid use case (it's probably going to be quite a lot of code), I'd go with the `RabbitTemplateBuilder` approach (see `RestTemplateBuilder` for an example of what we've done for consistency).

Would your issue be solved by creating the `RabbitTemplate` itself? I'd like to avoid a `createRetryTemplate` on the builder.



You could argue that for pretty much everything (why not offer the same thing for the `RabbitTemplate` itself?)

**Comment by garyrussell** [comment]
OK; not a big deal; it's not a lot of code to duplicate; feel free to close this.

I don't think a builder would help since the spring cloud binder needs to create a `RabbitTemplate` or a subclass `BatchRabbitTemplate` depending on its configuration. I don't think the batch subclass is a common enough use case to warrant the effort of adding boot config properties for it.
