### ISSUE TITLE
Upgrade to mariadb java client 1.6.0

### ISSUE THREAD

**Issue by mapkuff** [spring-projects/spring-boot#9338]
Spring Boot Dependency version 1.5.3.Release is related to mariadb-java-client 1.5.9 which is buggy.

https://jira.mariadb.org/browse/CONJ-448

**Comment by mapkuff** [comment]
for more information for mariadb-java-client
1.5.7 work fine
1.5.8 is buggy
1.5.9 is buggy
1.6.0 TBD

**Comment by wilkinsona** [comment]
We can't upgrade to 1.6 in Spring Boot 1.5.x as isn't appropriate to pick up a new minor version of the driver in a maintenance release of Spring Boot. 1.6.0 contains [new functionality back-ported from 2.0](https://mariadb.com/kb/en/mariadb/mariadb-connector-j-160-release-notes/). If you want to use 1.6 (or 2.0) with Spring Boot 1.5.x, you should override the `mariadb.version` property.

Spring about 2.0 has already upgraded to 2.0.1 of the MariaDB driver.

**Comment by mapkuff** [comment]
@wilkinsona 
What do you think if we change spring boot 1.5.x dependency to mariadb-java-client 1.5.7 because 1.5.8 and 1.5.9 is buggy.

but 1.5.7  may contains other bug also. :(

**Comment by wilkinsona** [comment]
Downgrading isn't really a good option either. People may be relying on fixes in 1.5.8 and 1.5.9 while not being affected by the problems that you have seen. Downgrading would make things worse for those people. If it's appropriate for your specific situation, then you can override the version as described above. 

Unfortunately, I think sticking with 1.5.9 is our best option. You may want to lobby for a 1.5.10 release of the driver. That would allow Boot to upgrade in 1.5.x.
