### ISSUE TITLE
SpringBootTest doesn't resolve property files annotated @ContextConfiguration with prefix

### ISSUE THREAD

**Issue by quadrat137** [spring-projects/spring-boot#9357]
I've got a test 

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {CalculatorClientConnectionConfig.class})
@TestPropertySource(
        properties = {
                "client.calculator.baseUrl=localhost"
        }
)
public class CalculatorRestClientImplTest {
        @Autowired
        private CalculatorClientConnectionConfig connectionConfig;
....
}
```
And 
```java
@Data
@Component
@ConfigurationProperties(prefix = "client.calculator")
public class CalculatorClientConnectionConfig {
    private String baseUrl;    
}
```
When test starts, `baseUrl == null`
But if i remove `@ContextConfiguration` and add `@Value` upon `baseUrl`, like this
```java
@Data
@Component
public class CalculatorClientConnectionConfig {
    @Value("${client.calculator.base-url}")
    private String baseUrl;    
}
```
everything works fine
I don't get whether is it a bug or i am missing something, can you please help?

**Comment by philwebb** [comment]
Could you please provide a complete sample application that shows the problem (either link to a git project or attach a zip). I think both `@TestPropertySource` and `@SpringBootTest(properties=...)` should work.

**Comment by quadrat137** [comment]
I've made something like my project, which, i think, i'm not supposed to share
https://github.com/quadrat137/spring_config_dunno
The same behavour though, see CalculatorClientTest

**Comment by snicoll** [comment]
`@SpringBootTest(classes)` is meant to define the sources for the context. If you set this attribute, the mechanism that [looks up for your `SpringBootApplication` is disabled[(http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-config). 

Your `CalculatorClientTest` simply does not run with any Spring Boot auto-configuration at all. It's a plain context with two source for beans. If you add `Application.class` to the list your test will pass. 

If you want to add an extra source in the context (and still detect the spring boot application automatically like `TestPropertie` does, simply use `@Import` on your test class.

**Comment by quadrat137** [comment]
But why then 
```
@Value("${client.calculator.base-url}")
    private String baseUrl2;
```
is resolved?

**Comment by snicoll** [comment]
it's a feature of Spring Framework not Spring Boot.
