### ISSUE TITLE
Add a runtime dependency on javax.annotation:javax.annotation-api for those using Java 9

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9366]
When running on Java 9, `javax.annotation` isn't visible by default as it's in a separate module. It can be made visible by using `--add-module java.se.ee` but this can cause problems with `javax.transaction`, a subset of which is in the `java.se.ee` module.

The symptom of `javax.annotation` not being on the class path is that `@PostConstruct` methods are not called. We use it quite a lot in our own auto-configuration so I think we should consider adding javax.annotation:javax.annotation-api to `spring-boot-starter` or similar.

A complication here is that `tomcat-embed-core` contains `@PostConstruct` (and various other `javax.annotation` packages so we'd end up with duplicate copies of the same classes in the web and tomcat starters. We already have a similar problem with `javax.persistence` when Tomcat and JPA are used together.

**Comment by philwebb** [comment]
Errgh. That Tomcat thing is a bit of pain. I wonder if they would be interested in offering a version of the embedded jar that doesn't contain any `javax.*` packages?

**Comment by snicoll** [comment]
@markt-asf do you think the Tomcat team would be interested by that? (see Phil's comment above). Thanks!

**Comment by markt-asf** [comment]
That is unlikely given that that would mean not shipping the Servlet API. (and JASPIC, JSP and WebSocket APIs)
Not packaging the annotations in the core embedded JAR and depending on the standard JAR is more likely.

**Comment by snicoll** [comment]
@markt-asf that would work as well. Do you want me to create an issue in bz for this?

**Comment by markt-asf** [comment]
Please.

**Comment by snicoll** [comment]
Thanks Mark, I've created https://bz.apache.org/bugzilla/show_bug.cgi?id=61439

**Comment by snicoll** [comment]
@wilkinsona Shouldn't we wait to fix #10133 first?

**Comment by wilkinsona** [comment]
We could wait, but I don't think we have to. #10133 will just help us tidy things up a bit.
