### ISSUE TITLE
Whitelabel Error Page  This application has no explicit mapping for /error, so you are seeing this as a fallback.  Wed May 31 23:17:56 IST 2017 There was an unexpected error (type=Not Found, status=404).

### ISSUE THREAD

**Issue by nitinpawar283** [spring-projects/spring-boot#9371]

**Comment by wilkinsona** [comment]
Given the lack of description, I'm guessing this was opened in error. 

> Whitelabel Error Page This application has no explicit mapping for /error, so you are seeing this as a fallback. Wed May 31 23:17:56 IST 2017 There was an unexpected error (type=Not Found, status=404).

This is the default content of a 404 response when a page isn't found for the request's URL.

**Comment by sassoura** [comment]
make sure you are requestiong the right URl. For example if in your Restcontroller you have defined this : @RequestMapping("/")
	    public String index() {
	        return "Greetings from Spring Boot!";
	    }

your URL must be like "http://localhost:8080/" because of the @RequestMapping("/")

I hope this was helpful

**Comment by varun-vijayarao** [comment]
ive got the same error. i'm trying to display a greeting on my localhost. the codes are
 greetingcontroller:
package com.example.Mydemo;

import java.util.concurrent.atomic.AtomicLong;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

public class GreetingController {

	private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @RequestMapping("/greeting")
    public Greeting greeting(@RequestParam(value="name", defaultValue="World") String name) {
        return new Greeting(counter.incrementAndGet(),
                            String.format(template, name));
    }
	
}


greeting:
   package com.example.Mydemo;

public class Greeting {


	    private final long id;
	    private final String content;

	    public Greeting(long id, String content) {
	        this.id = id;
	        this.content = content;
	    }

	    public long getId() {
	        return id;
	    }

	    public String getContent() {
	        return content;
	    }
	}


my pom is 

          <?xml version="1.0" encoding="UTF-8"?>

-<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">

<modelVersion>4.0.0</modelVersion>

<groupId>com.example</groupId>

<artifactId>Mydemo</artifactId>

<version>0.0.1-SNAPSHOT</version>

<packaging>jar</packaging>

<name>Mydemo</name>

<description>Demo project for Spring Boot</description>


-<parent>

<groupId>org.springframework.boot</groupId>

<artifactId>spring-boot-starter-parent</artifactId>

<version>1.5.9.RELEASE</version>

<relativePath/>




</parent>


-<properties>

<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

<java.version>1.8</java.version>

</properties>


-<dependencies>


-<dependency>

<groupId>org.springframework.boot</groupId>

<artifactId>spring-boot-starter-web</artifactId>

</dependency>


-<dependency>

<groupId>org.springframework.boot</groupId>

<artifactId>spring-boot-starter-test</artifactId>

<scope>test</scope>

</dependency>

</dependencies>


-<build>


-<plugins>


-<plugin>

<groupId>org.springframework.boot</groupId>

<artifactId>spring-boot-maven-plugin</artifactId>

</plugin>

</plugins>

</build>

</project>

**Comment by snicoll** [comment]
@varun-vijayarao we don't use the tracker for questions. Please ask on StackOverflow or join us on Gitter.

**Comment by Pramod-Gupta** [comment]
make sure we have to specify the package where SpringApplication.run(DemoApplication.class, args) available.Then it is working fine

**Comment by kvh44** [comment]
I have found the problem.  When you execute the generated jar file of spring boot. You need to execute the command out of the folder target like this " mvn clean package && java -jar target/mmm-0.0.1-SNAPSHOT.jar
 ". Otherwise it can't find the folder WEB-INF which located in "/src/main/webapp/".

**Comment by kvh44** [comment]
I have found the problem.  When you execute the generated jar file of spring boot. You need to execute the command out of the folder target like this 

" mvn clean package && java -jar target/mmm-0.0.1-SNAPSHOT.jar". 

Otherwise it can't find the folder WEB-INF which located in "/src/main/webapp/".

**Comment by wilkinsona** [comment]
@kvh44 Thanks for trying to help, but if you are building a jar file you shouldn't be using `src/main/webapp`. There's a [note](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-static-content) about this in the documentation:

> Do not use the `src/main/webapp` directory if your application is packaged as a jar. Although this directory is a common standard, it works only with war packaging, and it is silently ignored by most build tools if you generate a jar.

**Comment by BynuLorenz** [comment]
@kvh44 Thank you for your solution. took me days to figure it out.

**Comment by davidecherubini** [comment]
@kvh44 I'm new to programming and I encountered the same problem mentioned above, when I run the application via SpringBoot. 
Where should I write that line out of the destination?

**Comment by jmdopereiro** [comment]
I got this problem in all examples of https://spring.io/guides/tutorials/spring-security-and-angular-js

**Comment by Alpiniatechnologies** [comment]
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Aug 04 21:50:06 IST 2021
There was an unexpected error (type=Not Found, status=404).



this my error
please solve

**Comment by snicoll** [comment]
@Alpiniatechnologies please ask questions on StackOverflow.

**Comment by sudhirkum455** [comment]
Please amount withdrawal

**Comment by b99887766** [comment]
https://apinft.slotomania.com/recur-gateway/auth/redirect/recur/login/?appId=4&userId=user_id&sessionToken=session_token&redirectType=recur
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Jan 28 12:55:26 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by pankajkumarsingh123** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Aug 01 10:38:46 IST 2023
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by Aohkne** [comment]
Try: File → Invalid Cache → Invalid and restart
Sometimes it's a cache error
