### ISSUE TITLE
Spring Boot Gradle plugin 2.0.0.BUILD-SHANPSHOT & 2.0.0.M1 missing bootRepackage task

### ISSUE THREAD

**Issue by ranajyotic** [spring-projects/spring-boot#9376]
Spring Boot Gradle plugin missing the bootRepackage task. I have a which works with 1.5.3. But I want to upgrade it to 2.0.0 because of Spring 5.

`buildscript {
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'org.springframework.boot'

bootRepackage.enabled = false`

The above script works with 1.5.3 but with 2.0.0 I get the error below
`FAILURE: Build failed with an exception.

* Where:
Build file 'E:\LDSS_Source\lsp-core-new\db\build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':db'.
> Could not get unknown property 'bootRepackage' for project ':db' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by wilkinsona** [comment]
This change is [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#building-executable-jars-and-wars)
