### ISSUE TITLE
Update to Spring AMQP 1.7.3

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#9383]
Boot 1.5.4

**Comment by wilkinsona** [comment]
Thanks, Gary. We have a semi-automated process that takes care of this for us (opening upgrade issues, changing the versions in spring-boot-dependencies, committing changes with an appropriate message, etc). We run it before each release so, generally speaking, there's no need to open this sort of issue as the automated tooling is quicker.

**Comment by garyrussell** [comment]
Interesting; good to know; given the tightness of the release schedules `SF->our stuff->boot` I would be concerned that our stuff might be missed if we have a glitch of some kind getting the release built.

Or, does the automated too consult the release calendar somehow?

**Comment by wilkinsona** [comment]
> Interesting; good to know; given the tightness of the release schedules SF->our stuff->boot I would be concerned that our stuff might be missed 

Ok, let's re-open these just to be sure. We can always close them as duplicates once the tool's done its thing.

**Comment by snicoll** [comment]
I also think that's the right call for these as the process usually runs a day ahead of the release and some bits may not have been released. @garyrussell no need to provide a PR for those though, it's a one line change and we're happy to do it.
