### ISSUE TITLE
Consider replacing `tomcat-jdbc` with `HikariCP` in JDBC starter

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#9392]
HikariCP was recently made _default JDBC connection pool_ in Boot in #6013.

However, with JDBC starter still pulling in `tomcat-jdbc` it is a bit questionable what _default_ actually means in practice. Users still need to add `HikariCP` dependency manually on top of Data JPA or JDBC starters.

IMO it should be considered to update JDBC starter in Boot 2.0 to pull in `HikariCP` instead of `tomcat-jdbc`.

**Comment by wilkinsona** [comment]
Whoops, that should have been done in #6013.

**Comment by snicoll** [comment]
Oh well, thanks @vpavic, good catch!
