### ISSUE TITLE
Copy folder to jar file generated by bootRepackage task

### ISSUE THREAD

**Issue by jonhkr** [spring-projects/spring-boot#9396]
Hello,
I'm deploying my application to AWS EBS and I need to copy a folder to the root of my application's jar file.

I tried copying the folder in the jar task but looks like bootRepackage is recreating the jar file, so the folder is removed from the root of the jar and written into the `BOOT-INF/classes/` folder.

Is there any way to write the folder in the jar in `bootRepackage` task?

**Comment by wilkinsona** [comment]
Duplicates #6626
