### ISSUE TITLE
Repackaging a jar or war may corrupt non-Latin characters in entry names

### ISSUE THREAD

**Issue by Artgit** [spring-projects/spring-boot#9405]
I faced a following issue with Spring Boot, Maven and non-latin characters on OpenSuse: https://stackoverflow.com/questions/44352414/maven-and-non-latin-characters-in-file-names

What am I doing wrong and how to fix it ?

**Comment by wilkinsona** [comment]
It looks like Boot's repackaging of the war has mangled the file names. As a workaround, if you only  want to deploy your war to Tomcat (or any other container), you could simply remove Spring Boot's Maven plugin from your pom.

**Comment by Artgit** [comment]
Thanks. I have removed Spring Boot's Maven plugin and now unzip(console command) on the WAR file is working fine but Tomcat still deploy the files with an issue.

**Comment by wilkinsona** [comment]
> but Tomcat still deploy the files with an issue.

Things are out of Boot's control at that point. You'll need to raise that part of the problem with the Tomcat team.

**Comment by wilkinsona** [comment]
Interestingly, if you extract that repackaged war with `jar -xf`, the non-Latin characters are not corrupted. It appears that `JarOutputStream` writes the non-Latin characters out in such a way that the JVM can read them back in again correctly, but other tools cannot.

Looking at what Maven and Gradle do, they both do not use `JarOutputStream`. Maven uses [ZipArchiveOutputStream](https://git-wip-us.apache.org/repos/asf?p=commons-compress.git;a=blob;f=src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java;h=63aeba723613a3d4568b8ac8911d6b3d1fe528d4;hb=HEAD) and Gradle uses Ant's [ZipOutputStream](http://ant.apache.org/manual/api/index.html?org/apache/tools/zip/ZipOutputStream.html). I guess that we will have to switch to something similar.

**Comment by philwebb** [comment]
From the JavaDoc it looks like both the Ant and Commons Compress originated from the same source.
