### ISSUE TITLE
Configure influxdb in spring-boot 

### ISSUE THREAD

**Issue by anarwal27** [spring-projects/spring-boot#9406]
I am working on including monitoring for my spring-boot application with influxdb, earlier there was no option provided by spring, but recently I saw that functionality has been included as a part PR mentioned in spring-projects/spring-boot#9066 is it ready to be used or still work needs to be done? If it is, is there any example available which shows how to implement it?

**Comment by snicoll** [comment]
Duplicates #9397

**Comment by anarwal27** [comment]
@snicoll Documentation as a part of #9397 is all that needs to be done for configuring and setting up metrics reporting with influxdb or still is it work in progress?

**Comment by wilkinsona** [comment]
@anarwal27 I see you also posted about this on Gitter. Please don't cross-post as it's likely to waste people's time. Gitter is a much better place for a discussion like this; we prefer to keep GitHub issues purely for bugs and enhancements.
