### ISSUE TITLE
PropertiesLauncher displays wrong banner

### ISSUE THREAD

**Issue by nqngo22** [spring-projects/spring-boot#9412]
Hi,
If I use `PropertiesLauncher` to load library files externally, and if one of these libraries have a `banner.txt` in the root of its classpath, then that banner will be displayed rather than my application's banner. I am using spring boot 1.5.3

I've attach a sample executable jar along with an external lib folder and the source code. In the lib folder, the classmate-1.3.3.jar has a banner.txt in the root of its classpath. When I execute the jar, that banner is displayed rather than the banner of my application.

How can I display my application's banner?
[springbootissue.zip](https://github.com/spring-projects/spring-boot/files/1053839/springbootissue.zip)

**Comment by philwebb** [comment]
Try adding `banner.location=springbootbanner.txt` to your `application.properties` so the Spring looks for a different file.

**Comment by nqngo22** [comment]
Thank you, that appears to have solved the issue, but is there another solution that does not require modifying the properties file? Also, do you know why this happens when the libraries are loaded from an external folder?

**Comment by wilkinsona** [comment]
The banner is loaded using the classpath and, as with anything on the classpath, ordering is important. The first one that's found is the one that's used.
