### ISSUE TITLE
Where can I find the backlog item to contribute ?

### ISSUE THREAD

**Issue by ishara** [spring-projects/spring-boot#9413]
Question

I just want to contribute some development task in my free time. where can I find the backlog item or task to contribute ?

Thank you.

**Comment by philwebb** [comment]
Thanks for offering to contribute. For questions like this it's best to ask on Gitter in the future.

Issues tagged with [`status: ideal-for-contribution`](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) would be a good place to start.
