### ISSUE TITLE
 Upgrade to Maven Surefire/Failsafe Plugin 2.20.1+

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9414]
See #6299  for our first attempt. It looks like a memory leak that we may need to report to the surefire team.

**Comment by shakuzen** [comment]
I'm not sure if the cause is the same, but [SUREFIRE-1382](https://issues.apache.org/jira/browse/SUREFIRE-1382) was found and recently fixed in surefire. It should be in the upcoming version `2.20.1` (and in `2.21-SNAPSHOT` already).

**Comment by wilkinsona** [comment]
Thanks, @shakuzen. That does sound pretty similar.

**Comment by SebastianDietrich** [comment]
please upgrade as well maven-failsafe-plugin (has traditionally the same version as surefire)

**Comment by wilkinsona** [comment]
There's no release date set for 2.20.1 and there are still 3 open issues. Moving to M4.

**Comment by wilkinsona** [comment]
Good news: 2.20.1 is out. Bad news: JUnit 5 isn't compatible with it. See [this issue](https://github.com/junit-team/junit5/issues/809#issuecomment-330488537) for details. We'll need to update our Junit 5 sample to downgrade Surefire to 2.19.1 as part of this.
