### ISSUE TITLE
DEBUG o.s.w.s.v.v.VelocityConfigurer - Cannot resolve resource loader path [classpath:/templates/] to [java.io.File]: using SpringResourceLoader

### ISSUE THREAD

**Issue by davis1214** [spring-projects/spring-boot#9415]
**When startup a spring-boot application on type of jar, error occurs as follows. But it run fines when execute ` mvn clean spring-boot:run` . **  

### spring-boot version 
```
<platform-bom.version>2.0.7.RELEASE</platform-bom.version>
<spring-boot.version>1.4.6.RELEASE</spring-boot.version>
```
### plugin
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                </configuration>
            </plugin>
```

### Errors while run ```java -jar target/shopd.jar```
```
17:20:52.355 [main] DEBUG o.s.w.s.v.v.VelocityConfigurer - Cannot resolve resource loader path [classpath:/templates/] to [java.io.File]: using SpringResourceLoader
java.io.FileNotFoundException: class path resource [templates/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/Administrator/Documents/development/shopd/target/shopd.jar!/BOOT-INF/classes!/templates/
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215)
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
        at org.springframework.ui.velocity.VelocityEngineFactory.initVelocityResourceLoader(VelocityEngineFactory.java:290)
        at org.springframework.ui.velocity.VelocityEngineFactory.createVelocityEngine(VelocityEngineFactory.java:235)
        at org.springframework.web.servlet.view.velocity.VelocityConfigurer.afterPropertiesSet(VelocityConfigurer.java:121)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapab
```

**Comment by wilkinsona** [comment]
Our [Velocity web sample](https://github.com/spring-projects/spring-boot/tree/1.4.x/spring-boot-samples/spring-boot-sample-web-velocity) works fine when executed as a jar so it's not clear what's causing your problem. If you'd like us to investigate further, please provide a small sample that reproduces it. Something that we can download and unzip, or `git clone` would be ideal.

**Comment by davis1214** [comment]
https://github.com/davis1214/shop_doc

**Comment by davis1214** [comment]
Thanks for your help. A branch of my codes were commited to GITHUB ,which could get via ```https://github.com/davis1214/shop_doc```

**Comment by wilkinsona** [comment]
This is working as designed. From `initVelocityResourceLoader` in `VelocityEngineFactory`:

```
// Try to load via the file system, fall back to SpringResourceLoader
// (for hot detection of template changes, if possible).
```

When run with `java -jar` the templates are in the jar file and, therefore, cannot be loaded via the file system. As a result it will fall back to using `SpringResourceLoader` to load them straight from the jar.

**Comment by davis1214** [comment]
Thanks. It would be ok while add configuration ```spring.velocity.preferFileSystemAccess= false
```

**Comment by wilkinsona** [comment]
>  It would be ok while add configuration spring.velocity.preferFileSystemAccess= false

That would certainly get rid of the debug log message, but would disable hot detection of template changes which is useful at development time. I would recommend not enabling debug logging instead.
