### ISSUE TITLE
OAuth2ClientIdCondition  always true

### ISSUE THREAD

**Issue by martinei** [spring-projects/spring-boot#9435]
It appears, that OAuth2ClientIdCondition always returns a 'ConditionOutcome.match'.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2RestOperationsConfiguration.java#L156

**Comment by mvitz** [comment]
Seems to be introduced with https://github.com/spring-projects/spring-boot/commit/7396ccfe04994c97b45b2e52d49bb0754575118f

**Comment by wilkinsona** [comment]
Well spotted. Thank you. @martinei, to help us understand the impact, can you please describe the problem that you're seeing as a result of this?

**Comment by martinei** [comment]
Well. I am trying to use `spring-security-oauth2` and have a very custom configuration / setup (Trying to avoid server side state).  I'am now searching for a workaround to completly disable the Configurations in OAuth2RestOperationsConfiguration

**Comment by martinei** [comment]
For the records: I worked around with
`@EnableAutoConfiguration(exclude = OAuth2AutoConfiguration.class)`

**Comment by alwaysastudent** [comment]
Well this fix breaks the existing clients and is not backward compatible. I wish the `security.oauth2.client.client-id` has been defaulted to `${spring.application.name}` if absent instead of silently not configuring the OAuth2RestOperationsConfiguration

At least this has to be called out in the docs.

**Comment by snicoll** [comment]
@alwaysastudent actually [it is](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-authorization-server). I am afraid you were relying on a faulty behaviour before. As far as as I can see, the doc is now in par with what the auto-config does.

**Comment by alwaysastudent** [comment]
@snicoll My applications are all resource servers enabled by `EnableResourceServer` and not authorization servers. And resource servers also rely on the  `OAuth2RestOperationsConfiguration` 

With this fix, I have to explicitly define the `security.oauth2.client.client-id` for my resource servers as well.

**Comment by mbhave** [comment]
@alwaysastudent I see. And are your applications validating the token offline due to which you don't need a client id to be specified?

**Comment by alwaysastudent** [comment]
Yes, they are based on JWTs and relay the same to downstream services as well.

**Comment by mbhave** [comment]
@alwaysastudent I think you're right and this can be an issue for certain resource servers. But before I reopen it, is it possible for you to provide a small sample that reproduces the issue?

**Comment by tomcooperca** [comment]
For anyone struggling with this issue while attempting to implement `OAuth2FeignRequestInterceptor` (which doesn't `security.oauth2.*` properties), this SA post worked for me on 1.5.13.RELEASE: https://stackoverflow.com/questions/29696671/how-to-overwrite-spring-cloud-oauth2-client-autoconfiguration
