### ISSUE TITLE
Enhancement/Adjust the file type e.g. from jar to sh

### ISSUE THREAD

**Issue by mdeknowis** [spring-projects/spring-boot#9437]
Some maven repositories check the file content, if it is matching to the file extension.

E.g. the Nexus Repositry Manager does it:
`ERROR: Failed to deploy artifacts: Could not transfer artifact xxx:yyy:jar:exec-linux:1.2.3-20170608.111607-3 from/to snapshots (http://zzz/): Failed to transfer file: http://zzzz/-exec-linux.jar. Return code is: 400, ReasonPhrase: Detected content type [application/x-sh], but expected [application/java-archive]: zzz-exec-linux.jar.`

So it would be nice, if you could adjust the type/extension like this:
```xml
<configuration>
    <classifier>exec-linux</classifier>
    <type>sh</type>
</configuration>
```

Current workaround is to use another plugin:
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <classifier>exec</classifier>
    </configuration>
    <executions>
        <execution>
            <id>exec-linux</id>
            <goals>
                <goal>repackage</goal>
            </goals>
            <configuration>
                <classifier>exec-linux</classifier>
                <executable>true</executable>
                <attach>false</attach>
            </configuration>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>attach-artifacts</id>
            <phase>package</phase>
            <goals>
                <goal>attach-artifact</goal>
            </goals>
            <configuration>
                <artifacts>
                    <artifact>
                        <file>target\myartifact-exec-linux.jar</file>
                        <type>sh</type>
                        <classifier>exec-linux</classifier>
                    </artifact>
                </artifacts>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I think there's a risk that this will lead to people creating a broken pom. If they don't set a `classifier` but do set the `type` you'd be left with a pom file that's using `jar` packaging but that doesn't actually produce a `.jar` artifact.

Given that the `attach-artifact` goal of the Build Helper plugin allows you to do what you want already, I think it's better to use it. The alternative would be for us to reinvent the wheel, and possibly rather poorly.

**Comment by thatsk** [comment]
i am also facing same issue .

**Comment by thatsk** [comment]
E.g. the Nexus Repositry Manager does it:
ERROR: Failed to deploy artifacts: Could not transfer artifact xxx:yyy:jar:exec-linux:1.2.3-20170608.111607-3 from/to snapshots (http://zzz/): Failed to transfer file: http://zzzz/-exec-linux.jar. Return code is: 400, ReasonPhrase: Detected content type [application/x-sh], but expected [application/java-archive]: zzz-exec-linux.jar

**Comment by wilkinsona** [comment]
@thatsk And I recommend the same solution: use the build helper plugin to attach an artifact
