### ISSUE TITLE
@ExceptionHandler not applicable with exceptions thrown by @FeignedClient

### ISSUE THREAD

**Issue by leafblight** [spring-projects/spring-boot#9450]
Hi!

I'm working on an API that is dependent on a lot of other APIs providing information from a search query, it's basically a reference api with quick information from the other APIs.

Some of these APIs are provided by other organizations and teams and, as is the case with a lot of microservices, they have a tendency to fail sometimes for various reasons.

I'm trying to handle the connections to these APIs by building search queries with FeignedClient annotation... and it works really good!
however, when any of the APIs I'm connecting to fails , things are supposed to continue working without the consumer really knowing what happens (i.e. no crashes), with a silent mail sent to  developers and/or others.

This is something that could be achieved very nicely with @ExceptionHandler: catch specific error, tell developer about it so they can investigate and then continue on, pretend nothing wrong happened, consumer just needs the information it can get..

Of course, however, I realize quite a while into tampering with this that these two annotations are not compatible, I need to resort back to the archaic use of catching  Exceptions in a try catch directly in the api connection code, which means I need to have try catch cases where I capture the exception and then handle it, which means a lot of redundant code (and breaking of the code's flow with try catches).

So my question amounts to: is there a reason the two annotations are no compatible and, if not, could they possibly be compatible in the future?

**Comment by spencergibb** [comment]
`@FeignClient` is from spring-cloud-netflix, not part of spring-boot.

**Comment by wilkinsona** [comment]
And `ExceptionHandler` is part of Spring Framework
