### ISSUE TITLE
Health cache of the health endpoint is not thread safe

### ISSUE THREAD

**Issue by utkuozdemir** [spring-projects/spring-boot#9454]
In `HealthMvcEndpoint` class of Spring Boot Actuator, there is a cache mechanism that returns a cached health result if it has been requested in less than `endpoints.health.time-to-live` milliseconds ago. For this, class keeps the last access time and the cached health object on instance variables. However, even though those fields can be read/written by multiple http threads in the same time, there is no locking mechanism, neither these fields are `volatile` or atomic references. This can lead to stale reads and visibility issues.

**Comment by wilkinsona** [comment]
Closing in favour of #9455. @utkuozdemir Thanks for reporting this. If you intend to open a PR, there's no need to open an issue as well.

**Comment by wilkinsona** [comment]
Given that we want to fix this in a different way in 1.5 we need this issue after all
