### ISSUE TITLE
Spring Boot 1.5.3 - Receiving error while running the command 'mvn spring-boot:run' command

### ISSUE THREAD

**Issue by kiran-vadla** [spring-projects/spring-boot#9456]
Hi Team, 

We have recently upgraded Spring Boot in our project to Spring Boot 1.5.3 . It is a maven project . When I run maven command 'mvn spring-boot:run' , I receive an error similar to the following

```
'[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) on project <xyx>: An exception occurred while running. null: InvocationTargetException: org/springframework/boot/SpringApplication: org.springframework.boot.SpringApplication -> [Help 1]'
```

and before we receive this error , we receive a warning as follows : 

Warning Details : 
```
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at ......SpringBootApp.main(SpringBootApp.java:24)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

List of the softwares with their as follows : 

Maven : 3.3.9
Java : 1.7
Spring Boot : 1.5.3

WAR file that is generated contains spring-boot-1.5.3.RELEASE.jar file and I am able to launch SpringBootApplication inside eclipse and able to integrate the WAR with client code and bring up the application . 

Not sure if it is a bug in Spring Boot 1.5.3 or If I am missing something ? Please  provide your inputs as soon as possible. 

Thanks,
@kiran-vadla

**Comment by snicoll** [comment]
That sounds like a classical jar corruption to me. Please clean your maven cache (`mvn dependency:purge-local-repository`) and try again.  If that doesn't work, please share a sample that reproduces the issue.

**Comment by kiran-vadla** [comment]
Hi @snicoll , 

I have tried cleaning maven cache with 'mvn dependency:purge-local-repository' but without luck . To reproduce the issue , please execute the instructions below 

1. git clone --recursive https://github.com/oasp/oasp4j.git
2. cd oasp4j
3. git checkout develop-2.4.0
4. Execute 'mvn clean install' 
5. cd samples/server
6. Execute 'mvn spring-boot:run'

Thanks,
@kiran-vadla

**Comment by snicoll** [comment]
@kiran-vadla that project is large and I am afraid I don't have the time to dig into all the details. I can see that the dependency management of the `server` module doesn't have any spring boot dependency at all so that error is not surprising (spring boot isn't on the classpath).

If you'd like us to investigate what you think is a problem is spring boot please provide a minimal sample that works with the version you were using before and breaks with 1.5.3.

**Comment by kiran-vadla** [comment]
@snicoll , We have found the problem. When we add the version for the artifact 'spring-boot-starter-tomcat' explicitly as follows in oasp4j/samples/core/pom.xml and run 'mvn spring-boot:run' from oasp4j/samples/server after building samples project (i.e, after running 'mvn clean install'), it works . Not sure why the version is not taken from Spring-Boot BOM ? 

**************************************************************************************************************
  <profiles>
    <profile>
      <id>embedded</id>
      <activation>
       <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <version>1.5.3.RELEASE</version>
        </dependency>
      </dependencies>
    </profile>
  </profiles>

**************************************************************************************************************

Thanks,
@kiran-vadla

**Comment by snicoll** [comment]
I had a quick look to your project and the dependency structure is rather involved. Sorry but there is nothing that tells me there is a regression in Spring Boot (I still don't know what other version worked and if it works without changing anything). We don't use the tracker for questions so join us on Gitter if you want to chat more about your particular application. Thanks

**Comment by paramothers** [comment]
I faced the same issue. 
 I changed in Pom.xml file from 1.5.10.RELEASE  to 1.3.5.RELEASE as below, it works fine
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
		<relativePath /> 
	</parent>

**Comment by paramothers** [comment]
**I faced the same issue**, and i resolved like this
I changed in Pom.xml file from 1.5.10.RELEASE to 1.3.5.RELEASE as below, it works fine

` <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
		<relativePath /> 
	</parent>`
