### ISSUE TITLE
DefaulLogbackConfiguration does not use CONSOLE_LOG_PATTERN from system Properties

### ISSUE THREAD

**Issue by rotilho** [spring-projects/spring-boot#9483]
`DefaultLogbackConfiguration` doesn't not use `CONSOLE_LOG_PATTERN` from system properties.

How to reproduce
Create a simple application and start it with system property `CONSOLE_LOG_PATTERN`.

Expected result
`DefaultLogbackConfiguration` should use `CONSOLE_LOG_PATTERN` instead of default one hard-coded

Current result
`DefaultLogbackConfiguration` uses hard-coded `CONSOLE_LOG_PATTERN` 

More information: `LoggingSystemProperties` by default set `CONSOLE_LOG_PATTERN`  with `logging.pattern.console` if it's missing so `DefaultLogbackConfiguration`  could use this property instead.

Spring boot 1.5.3 ~ 1.5.4

**Comment by philwebb** [comment]
The `CONSOLE_LOG_PATTERN` system properties is configured from the contents of `logging.pattern.console` so that it's available to the logging framework. It was never really the intention that `CONSOLE_LOG_PATTERN` should be used as a system environment variable.

What's your use-case where you need to set the logging pattern in a system environment variable?

**Comment by rotilho** [comment]
I have a base docker image which have CONSOLE_LOG_PATTERN by default configured.

Not sure if it's working as designed. This documentation at least says that  CONSOLE_LOG_PATTERN 
 is system property alias for logging.pattern.console https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

**Comment by philwebb** [comment]
It's perhaps not that clear in the docs. It's trying to say that `logging.pattern.console' is mapped to a Java system environment so that it can be picked up my logging configuration.

Why do you need to change the logging format for your application? Does it need to be configurable at all?

**Comment by rotilho** [comment]
I got it.
