### ISSUE TITLE
Support loading logging.config from the classpath

### ISSUE THREAD

**Issue by rodlogic** [spring-projects/spring-boot#9491]
I want to provide two spring-XXXX.xml files embedded in the JAR selected by setting logging.config. However, as soon as I set logging.config spring-boot assumes it is a URL and opens it using new URL().

I would like to load the logback-XXXX.xml from the JAR using classpath:logback-WAR.xml.

I am using SpringBoot 1.5.1.

**Comment by wilkinsona** [comment]
> However, as soon as I set logging.config spring-boot assumes it is a URL and opens it using new URL().

I don't believe that's the case. For example, [LogbackLoggingSystem uses ResourceUtils](https://github.com/spring-projects/spring-boot/blob/v1.5.4.RELEASE/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L145-L146) to turn the location into a URL. `ResourceUtils` supports `classpath:` URLs.

If you'd like us to investigate further, please provide a small sample that illustrates the behaviour you have described.

**Comment by rodlogic** [comment]
Humm, you are right! I messed up the file names.
