### ISSUE TITLE
Remove test-jar artifacts

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9493]
The test-jar artifacts are difficult to remove using the standard Maven deploy plugin. With the addition of the `spring-boot-test-support` project many of the internal test utilities could move.

**Comment by snicoll** [comment]
@philwebb is the duplication of `OutputCapture` expected here? Also the `rule` looks like a dumping ground now so perhaps we should rather restructure the package for stuff that are "general" and things that are data specific? I mean to move other data-related rules (like `RedisTestServer`). Do we want them all there?

**Comment by philwebb** [comment]
Unfortunately we need to duplicate `OutputCapture` because we need to use it in `spring-boot` (and we can't depend on `spring-boot-test` there).

I agree about the `rule` package needing some love. The good news is that this stuff is 100% internal so we can refactor it as we see fit.
