### ISSUE TITLE
InfluxDb. Add support for SSL in InfluxDbAutoconfiguration

### ISSUE THREAD

**Issue by Dichotomia** [spring-projects/spring-boot#9502]
We could use `InfluxDBFactory.connect(url, userName, password, builder)` instead of `InfluxDBFactory.connect(url, userName, password)`.

**Comment by snicoll** [comment]
If you're using it with SSL, please expand the description to explain what you're doing currently.

**Comment by Dichotomia** [comment]
Currently (with spring boot 1.5.4) we use https to secure the data sent to our influxDB database.

The code :

final SSLSocketFactory sslSocketFactory = ....
final okhttp3.OkHttpClient.Builder builder = new okhttp3.OkHttpClient.Builder().sslSocketFactory(sslSocketFactory);
....
final InfluxDB influxDB = InfluxDBFactory.connect(url, userName, password, builder)....
For spring boot 2.0, we plan to use influxDbAutoconfiguration if it enables to use https.

**Comment by Dichotomia** [comment]
Suggestion in pseudo code : 
If (Bean okhttp3.OkHttpClient.Builder is present){ 
final InfluxDB influxDB = InfluxDBFactory.connect(url, userName, password, builder)
}else{
final InfluxDB influxDB = InfluxDBFactory.connect(url, userName, password)
}

**Comment by wilkinsona** [comment]
It looks to me like @eddumelendez has taken care of this in #9669.
