### ISSUE TITLE
SslStoreProvider implementation in SpringBoot forces Two-Way SSL only

### ISSUE THREAD

**Issue by oazmon** [spring-projects/spring-boot#9507]
I believe due to an oversight, it is not possible to use a custom SslStoreProvider technique to just fetch a Keystore and leave the TrustStore `null`. The code in `SslStoreProviderUrlStreamHandlerFactory` does not accomodate the valid case where `sslStoreProvider.getTrustStore()` returns null.

It this bug report is accepted, I will perform a pull request and submit.

**Comment by snicoll** [comment]
Closing in favour of PR #9508

@oazmon if you intend to submit a PR, an issue isn't needed. Thanks!
