### ISSUE TITLE
Context isn't cached when MockBean using

### ISSUE THREAD

**Issue by opavlov24** [spring-projects/spring-boot#9511]
When I use MockBean with SpringBootTest annotation, spring context is not cached. I've created a sample project to demonstrate it. See https://github.com/opavlov24/mockbean-context-sample .

**Comment by snicoll** [comment]
There is nothing wrong with the sample that you share. When you use `@MockBean` in the second test, you are effectively modifying the context so it is normal that we create another one. 

In the first test `DummyServiceToMock` is the actual bean found by classpath scanning. In the second test that bean is a mock. This can't happen if the context is cached since the application context has to modify it.

**Comment by CalamarBicefalo** [comment]
I have always wondered about why this is the default behaviour. I understand the thinking behind but truth is, Spring knows what got cached (and what was there before).

It should be feasible to reuse the cache and restore it to its original state.

With large application this is a massive performance hit. And I end up avoiding MockBean altogether precisely for this reason.

Couldn't this be an improvement perhaps? Am I missing something here?

**Comment by wilkinsona** [comment]
It's not as simple as that. The cache is provided by Spring Framework's testing framework and it's application contexts that are cached. It's almost impossible to take a running application context and replace a "normal" bean with a mocked bean or the reverse. Any given bean may have been injected in numerous places, including into final fields which we can't change.

**Comment by CalamarBicefalo** [comment]
First of all thanks for the context @wilkinsona. I understand it is not exactly a trivial issue, but I would like to discuss about the feasibility of a few solutions (and maybe I could PR it).

What if when the runner creates the AppCtx beans that are meant to be mocked were proxied with a BFPP? The proxy could hold a reference to the original one. Every time a test demands a Mock on that one, the listener in the test runner could toggle the mock on.

Of course, for this to work, we would need to know all beans that need to be mocked while starting up the AppCtx. I am not sure if we can get that info from the testRunner, using reflection and brute force or using spring's baseScanPackage.

Maybe this makes no sense at all, but even if it doesn't I'd love to know why.

**Comment by wilkinsona** [comment]
> Of course, for this to work, we would need to know all beans that need to be mocked while starting up the AppCtx.

That's certainly a big part of the problem, and I don't know how we can get that information reliably for all the different test frameworks that people may use.

> Maybe this makes no sense at all, but even if it doesn't I'd love to know why.

I think it might make some sense and I'm certainly not ready to declare that it doesn't make sense. Proxying things can introduce its own set of problems and I'm not sure if @philwebb tried that approach when he wrote the mock bean support and found that it didn't work. I suspect that some prototyping may be necessary to determine the feasibility of a different approach. If you have the time and inclination to do that, we'd love to hear about it in a separate issue or pull request.

**Comment by philwebb** [comment]
The problem with the proxy approach is that you don't know which beans might be mocked until you run the test. For example you might have the following config:

```java
@Configuration
public class MyConfig {

    @Bean
    public BeanA beanA() {
        ...
    }

    @Bean
    public BeanB beanB() {
        ...
    }
}

One test might use `@Mock BeanA` and a second test might use `@Mock BeanB`. It's not possible to know when the first test runs that a second test will later need `BeanB` to be a mock.
