### ISSUE TITLE
Running executable jar does not properly handle space or asterisk in RUN_ARGS

### ISSUE THREAD

**Issue by guangjunli** [spring-projects/spring-boot#9514]
Suppose in the app.conf file, RUN_ARGS includes this entry:

`--device.poll.cron=0 0/15 * * * *`

The asterisk will trigger a file name match (globing). It does not help even if asterisk is quoted/escaped as then the backslash would be included in what's passed on to the cron trigger. 

The space (' ') also cause the problem that only the first component in the cron expression will be passed, therefore trigger a syntax error at server startup. Since not able to localize the effect of changing the shell IFS to get around this issue, now resorting to converting the space to '_' and converting it back in Java code.

If the executable jar startup allows such flexibility, please point me to where I can try.

**Comment by wilkinsona** [comment]
[Shellcheck](https://www.shellcheck.net) doesn't report any quoting/globbing problems with the launch script. The conf file is a script that's `source`d by the main launch script. If `*` is triggering globbing to occur, it sounds to me like you may be missing some appropriate quoting/escaping. I have no way of telling, though, as you haven't shared your `app.conf` file. Perhaps you can share a sample that reproduces the problem?

**Comment by guangjunli** [comment]
Thanks @wilkinsona . From what I can tell, the main launch script sources the conf file, but then it uses `printf` to feed what's set in conf file to the java process, so RUN_ARGS is split (with space as the field separator) into individual arguments. In this process, the space inside cron expression is treated as any other space, therefore the cron expression is not passed to Java as a single argument. I could not find a way to escape the spaces inside the cron expression because 'printf' is used (there is no reevaluation of the arguments by the shell).

Escaping the `*` with `\*` to prevent globing won't work in the end because, while it prevents globing itself, `\*` will be literally passed as part of the cron expression, again because of `printf` usage I think. I tried the workaround of turning globing off inside app.conf. :)

This is a briefer version of the app.conf, having a shorter RUN_ARGS:

> #MODE
> 
> #USE_START_STOP_DAEMON
> 
> #PID_FOLDER
> 
> LOG_FOLDER=/var/log/app
> 
> #CONF_FOLDER
> 
> #LOG_FILENAME
> 
> #APP_NAME
> 
> RUN_ARGS='--server.port=8001 \
> --device.poll.cron=0 0/15 * * * *
> '
> 
> JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
> 
> JAVA_OPTS='-Dlogging.path=/var/log/app -server -Xms512m -Xmx512m'
> 
> #JARFILE
> 
> #DEBUG
> 
> #STOP_WAIT_TIME
> 

I'll try to build a demo app asap.

**Comment by guangjunli** [comment]
@wilkinsona I have the app that reproduces this, but how do I upload it so you can run it?

**Comment by wilkinsona** [comment]
You can attach a zip to an issue. Alternatively, we can clone a repository on GitHub .

I've done a bit of exploration and I think that quoting `${RUN_ARGS}` may fix the problem:

```
arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar "$jarfile" $RUN_ARGS "$@")
```

You could try that in your app using a [custom launch script](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-script-customization).

**Comment by guangjunli** [comment]
Thanks @wilkinsona . I thought the `$"RUN_ARGS` was not quoted for a reason. If it's quoted then it will be passed to Java process as a single argument (as opposed to multiple arguments when unquoted), I'll experiment with it. I appreciate your quick responses.

**Comment by guangjunli** [comment]
[cron_config_demo.zip](https://github.com/spring-projects/spring-boot/files/1075344/cron_config_demo.zip)

@wilkinsona I just saw how to upload file :). the app.conf is also included. If you run it with app.conf then you see the issues (both globing and splitting within the cron expression, as app.conf has debug on). I'll try the custom launch with quoting RUN_ARGS next. Thanks.

**Comment by wilkinsona** [comment]
Thanks for the sample.

With `RUN_ARGS` declared as an array in `app.conf`:

```
RUN_ARGS=('--device.poll.cron=0/10 * * * * *' 'alpha' 'bravo charlie')
```

And this in the launch script:

```
"${RUN_ARGS[@]}"
```

The application is started with three separate arguments as desired:

```
--device.poll.cron=0/10 * * * * *
alpha
bravo charlie
```

It also works fine if there's a single entry in `RUN_ARGS`:

```
RUN_ARGS="--device.poll.cron=0/10 * * * * *"
```

However, it will break anyone who was previously passing in multiple space-separated arguments. I think the solution to this is to detect if `RUN_ARGS` is an array. Unfortunately, that would appear to be far from trivial to do, particularly in a portable manner.

**Comment by guangjunli** [comment]
Thanks very much @wilkinsona . we'll try as you suggested.

**Comment by ksperling** [comment]
@wilkinsona I'm using the following approach in my custom wrapper script:

```
function is_array() { # name
  [[ "$(declare -p "$1" 2>/dev/null)" =~ ^declare\ -a\  ]]
}
function split_words() { # name string
  read -r -d '' -a "$1" <<<"$2"
}
...
is_array JAVA_OPTS || split_words JAVA_OPTS "$JAVA_OPTS" # support array or string
```

This works in Bash 3 and up.

**Comment by wilkinsona** [comment]
@ksperling Very interesting. Thank you.

**Comment by wilkinsona** [comment]
Thanks for the report, but we've decided that we don't want to introduce the complexity of array detection for everyone. Our recommended solution is that those affected use a custom script that suits their needs.
