### ISSUE TITLE
Support per-response-status response time gauge for HTTP requests

### ISSUE THREAD

**Issue by ajainy** [spring-projects/spring-boot#9517]
Ref: [Metrics Filter class](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/MetricsFilter.java#L193),  

**Problem statement:**
When recording and visualizing gauge response times, I want to know, if last response time is for which http status code. It is quite possible, gauge response time is wildly different if it 200 or some other error like 404 or 500. 

**Recommendation**
As linked above, we should add _status_ field as part of metric name for gauge. 

This is enhancement request. If acknowledged, I can do PR.

**Comment by wilkinsona** [comment]
If the response status is included as part of the metric name, you'll no longer be able to see the time for the last response irrespective of its status. That sounds like a step backwards to me. I think additional gauges with the status in their name may be better.

That said, I'm not sure that I like the idea of adding any more complexity to `MetricsFilter`. We already have support for combined or per HTTP method gauges and counters and adding per response status gauges to that starts to get quite complex. Would we also want to support per HTTP method and per response status gauges, for example?

We need to revisit the metrics filter in 2.0 as part of our reactive web story. We also need to think about improving its capabilities when using Jersey. As part of that work I think it would be interesting to remove a lot of logic from the filter and plug the logic into it instead. We could allow applications to make their own contributions to this logic where they could record whatever counters and gauges they like.

**Comment by ajainy** [comment]
> If the response status is included as part of the metric name, you'll no longer be able to see the time for the last response irrespective of its status. That sounds like a step backwards to me. I think additional gauges with the status in their name may be better.

I am trying to understand this statement. I am assuming, status will be another DOT separated field. 
Hence output might look like `gauge.response.GET.200.xyz` or `gauge.response.GET.500.xyz`

**Comment by ajainy** [comment]
Apart from this, is there any work around? Can I totally turn OFF metric filter and how i can write custom filter for this?

**Comment by wilkinsona** [comment]
> I am trying to understand this statement

I am proposing that `gauge.response.xyz` is kept and that `gauge.response.200.xyz`, `gauge.response.500.xyz` are added.

> Can I totally turn OFF metric filter

Yes: `endpoints.metrics.filter.enabled=false`

> how i can write custom filter for this

I'd use the existing filter code (that you already linked to above) as inspiration.

**Comment by wilkinsona** [comment]
We decided that we don't want to support this. Rather than using a gauge for response times, a timer is far more useful as you can then see the performance over a period of time rather than a one-off snapshot. Please see #4405 and #9555 for that change.

We may still consider the pluggability that I [talked about above](https://github.com/spring-projects/spring-boot/issues/9517#issuecomment-308546555). That'll be looked at as part of the general metrics overhaul in 2.0.
