### ISSUE TITLE
actuator does not respond to requests when using Spring Boot version 2.0.0.M1

### ISSUE THREAD

**Issue by lnhrdt** [spring-projects/spring-boot#9518]
Steps to reproduce:

Using Spring Initializr, create a new Java, Gradle Project, version 2.0.0.M1, with Web and Actuator dependencies. Run the app.

```
curl -i localhost:8080/health
HTTP/1.1 404
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 14 Jun 2017 20:43:27 GMT

{"timestamp":1497473007112,"status":404,"error":"Not Found","message":"No message available","path":"/health"}
```

Edit the build.gradle file and change the Boot version to 1.5.4.RELEASE. Run the app.

```
curl -i localhost:8080/health
HTTP/1.1 200
X-Application-Context: application
Content-Type: application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 14 Jun 2017 20:45:51 GMT

{"status":"UP"}
```

**Comment by spencergibb** [comment]
Actuator endpoints moved in 2.0.0, so you need to check `/application/health`.

**Comment by wilkinsona** [comment]
Thanks again, @spencergibb.

@lnhrdt This change is [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#actuator-default-mapping).

**Comment by lnhrdt** [comment]
That was it!

The larger issue is we were referencing the "current" docs, rather than specifically the 2.0.0.M1 docs. Thanks @spencergibb and @wilkinsona!
