### ISSUE TITLE
Deprecate JsonContent.assertThat to discourage use

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9519]
It's easy to write `json.read(...).assertThat` rather than `assertThat(json.read)...`. We could deprecate that method do discourage used.

**Comment by philwebb** [comment]
Closing in favor of PR #9678

**Comment by izeye** [comment]
@philwebb Not closed 😄

**Comment by wilkinsona** [comment]
Thanks, @izeye
