### ISSUE TITLE
RedisTestServer assume Jedis is available

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9524]
Now that we support both Jedis and Lettuce we should be able to use Jedis or Lettuce. Right now Jedis is assumed.

**Comment by snicoll** [comment]
@mp911de I've started to look into it and thought it was straightforward but a shutdown on a `LettuceConnectionFactory` takes 1 min or something (so 1 min+ per test when Redis is running on my machine) and the test never ends because some daemon threads are still running. Can you help me trace down how I can fix that? (I've pushed some code in my fork that I've used to test this)

**Comment by mp911de** [comment]
That's a bug in `LettuceConnectionFactory` when used without `LettuceClientConfiguration`. I filed https://jira.spring.io/browse/DATAREDIS-656. Either set `LettuceConnectionFactory.shutdownTimeout(…)` or use `LettuceClientConfiguration` for now.
