### ISSUE TITLE
Add support for Tomcat 9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9531]
Tomcat 9 is required to run on Java 9. This is mostly transparent except for the accept-count property. In Tomcat 8, it is called `setBacklog` on `AbstractProtocol`. On Tomcat 9, it's called `setAcceptCount` on the same class.

Because we want to be able to run the build with Java9, we'll have to go the reflective route for both use cases so that we can build with both Tomcat 8 and Tomcat 9.

**Comment by snicoll** [comment]
Maybe the Tomcat might consider backporting those properties? I've created an issue on their side for that: https://bz.apache.org/bugzilla/show_bug.cgi?id=61195

**Comment by philwebb** [comment]
Looks like Tomcat backported to 8.5.x for 8.5.16 onward

**Comment by snicoll** [comment]
They did so I'll reflect that as soon as we upgrade to Tomcat 8.5.16 (#9611)

**Comment by snicoll** [comment]
Duplicate of #9611
