### ISSUE TITLE
There is an error in reference doc!

### ISSUE THREAD

**Issue by huotaihe** [spring-projects/spring-boot#9535]
In chapter 27.1.9 Error Handling

The "public" should be ”static“ in the directory tree！

src/
 +- main/
     +- java/
     |   + <source code>
     +- resources/
         +- public/
             +- error/
             |   +- 404.html
             +- <other public assets>

**Comment by wilkinsona** [comment]
Thanks, but `public` and `static` are both [valid locations](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content) for static resources.
