### ISSUE TITLE
Revisit Lettuce pooling and shutdown timeout configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9538]
We're using a deprecated API at the moment as it's our only option. That's going to change when @mp911de revisits Lettuce pooling. We should revisit our configuration once that's happened.

**Comment by wilkinsona** [comment]
@mp911de It looks to me like you haven't revisited pooling yet and we still can't configure the shutdown timeout while using a pool yet. Is that correct?

**Comment by mp911de** [comment]
Yes (for both questions). I created [DATAREDIS-667](https://jira.spring.io/browse/DATAREDIS-667) to track our pooling efforts.

**Comment by wilkinsona** [comment]
The DATAREDIS issue has been fixed in Kay RC 3 and we have lots more deprecation warnings now. I think we should fix this in M4 rather than ignoring those warnings till M5.
