### ISSUE TITLE
Provide easier multiproject spring loaded support for gradle

### ISSUE THREAD

**Issue by mxab** [spring-projects/spring-boot#954]
Hi,
it looks like at the moment bootRun needs to be restarted everytime I change something in a project dependency and run `gradle classes` as it includes only the jar output of the project.
I don't have the problem when I start it with STS since the classpath consists of all the bin folder of the project.

As a workarround I use this at the moment (1.1.0 SNAPSHOT)

```
...
apply plugin: 'spring-boot'

dependency { compile project(":my-lib") }
...
bootRun {
    classpath = classpath + project(":my-lib").sourceSets.main.output   
    classpath = classpath - files(project(":my-lib").tasks.jar)

}
```

**Comment by snicoll** [comment]
superseded by devtools
