### ISSUE TITLE
DiskSpaceHealthIndicator should use File.getUsableSpace instead of File.getFreeSpace

### ISSUE THREAD

**Issue by iNikem** [spring-projects/spring-boot#9540]
Current indicator is most probably too optimistic at least for Linux filesystem. `File.getFreeSpace` does not take into account e.g. space reserved for a root account. `File.getUsableSpace` correctly does this and so provides more accurate picture of available disk space.

**Comment by htynkn** [comment]
Use `getUsableSpace` is more make sense to me. The only concern in here is do we need highlight this in our document?

**Comment by wilkinsona** [comment]
I don't think there's any need to mention it in the documentation. The use of `getFreeSpace()` isn't mentioned and moving to `getUsableSpace()` is really just a bug fix that makes the indicator more accurate.

**Comment by wilkinsona** [comment]
Closing in favour of the pull request from @htynkn (#9544)
