### ISSUE TITLE
Unable to customise AccessTokenConverter with jwk.key-set-uri (but can with jwt.key-uri)

### ISSUE THREAD

**Issue by nealeu** [spring-projects/spring-boot#9551]
With services such as Auth0 and Okta, I want to be able to provide a key set URI, and use a custom UserAuthenticationConverter (specifically we're stuffed if "user_name" is not provided as expected by DefaultAccessTokenConverter implementation).

I should be able to configure this by implementing JwtAccessTokenConverterConfigurer, but this is only auto-detected in ResourceServerTokenServicesConfiguration if jwt.key-uri or jwt.key-value, are set).

Can you please provide support in Spring Boot for customising when using jwk.key-set-uri.

Thanks.

**Comment by mbhave** [comment]
sounds reasonable to me. We probably need to change [this](https://github.com/spring-projects/spring-boot/blob/9480e09c21d484cdc31fcd248e9a2d111a7d4b87/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L238-L238) to be applicable for both `jwt` and `jwk` configurations.

**Comment by nealeu** [comment]
Thanks Madhura.
Yes. That was my thinking.  My workaround involved cloning a few closed JWK related classes in Spring Security OAuth, so it'll need support at that end.  [This gist](https://gist.github.com/nealeu/74c2843888cc2910115d14a6e090da12) shows what's currently needed (and also depends on [this PR ](https://github.com/spring-projects/spring-security-oauth/pull/1087) that @jgrandja just merged)

**Comment by wilkinsona** [comment]
The code in question has been dropped in Spring Boot 2.0 in favour of the OAuth support that's coming in Spring Security 5.x.
