### ISSUE TITLE
Gradle Plugin produces warning when running with Gradle 4.0

### ISSUE THREAD

**Issue by wfhartford** [spring-projects/spring-boot#9559]
In Gradle 4.0, the structure of the build directory changed so that each compiler task uses a different output directory. This necessitated the deprecation of the `SourceSetOutput.classesDir` property because there are multiple classes directories. Uses of this property should be replaced by `SourceSetOutputs.classesDirs`. API Documentation is [here](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html#org.gradle.api.tasks.SourceSetOutput:classesDir).

Version 1.5.4.RELEASE produces the following warning at the beginning of a build:
> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

Attached [getClassesDirStack.txt](https://github.com/spring-projects/spring-boot/files/1088650/getClassesDirStack.txt) includes the full stack trace. This issue should be reproducible in any spring boot application using gradle by upgrading to gradle version 4.0.

**Comment by rajadilipkolli** [comment]
She #9516

**Comment by rajadilipkolli** [comment]
See #9516

**Comment by wilkinsona** [comment]
As [stated in the documentation](http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#getting-started-system-requirements) 1.5.x only support Gradle 2 (2.9+) and 3.

We might be able to add a reflective hack to take care of the warning, but I'd prefer that Gradle didn't generate such warnings for code from a plugin in the first place (see https://github.com/gradle/gradle/issues/1311 and https://github.com/gradle/gradle/issues/1372).

**Comment by wilkinsona** [comment]
I've added a reflective hack in https://github.com/spring-projects/spring-boot/commit/e6a3ca5da6c58e8e6beb72624a1dfc1c41b121cf. Please note that Gradle 4.x isn't officially supported in Boot 1.5. It may work, but there may also come a point where that's not the case and there will be nothing we can do about it. We've been bitten in the past by trying to support too many major versions of Gradle at the same time and supporting 2.x and 3.x is the focus of 1.5.
