### ISSUE TITLE
Unable to proxy interface-implementing method: afterPropertiesSet in WebServiceGatewaySupport

### ISSUE THREAD

**Issue by identigral** [spring-projects/spring-boot#9575]
This is very similar to #8974 but the conclusion of #8974 (`@RefreshScope` annotation) doesn't apply to me

I have two subclasses of `WebServiceGatewaySupport` , FooClient and BarClient. Both of them override `initGateway()` and add a debug statement inside overridden `initGateway()`.  In my `@Configuration` class I create a `@Bean` of FooClient and BarClient. 

When running a JUnit integration test in STS with `@SpringBootTest` and SpringRunner via Run As..> JUnit, I see this warning in the log:

> 2017-06-21 23:35:39.177 DEBUG 4896 --- [           main] c.t.t.m.r.a.FooClient: Initializing FooClient with service at http://some.host/foo
> 2017-06-21 23:35:39.179  WARN 4896 --- [           main] o.s.aop.framework.CglibAopProxy          : Unable to proxy interface-implementing method [public final void org.springframework.ws.client.core.support.WebServiceGatewaySupport.afterPropertiesSet() throws java.lang.Exception] because it is marked as final: Consider using interface-based JDK proxies instead!
> 2017-06-21 23:35:39.198 DEBUG 4896 --- [           main] .m.r.a.BarClient : Initializing BarClient with service at http://some.host/bar

Note that only 1 instance of this warning is printed in the log but I am constructing 2 beans. The other interesting item is that `initGateway()` is called from `afterProperiesSet()`. My debug statement inside `initGateway()` in my subclasses does show up twice (once for each bean) in the log.  If I correctly understood #8974, the warning tells me that `afterPropertiesSet()` will not be invoked yet the debug messages say otherwise. Last but not least, I am overriding `initGateway` per docs and the warning based on `afterPropertiesSet` in `WebServiceGatewaySupport` is a tangent..so doubly confusing.

Unlike #8974 , I don't have any annotations that might cause the proxies to get involved, at least not that I am aware of. This is 1.5.4.RELEASE.

**Comment by snicoll** [comment]
Thanks for the detailed description but we'll need a sample that we can run ourselves. Can you please share that?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
