### ISSUE TITLE
Document that UNKNOWN status does not contribute to the overall application status

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#9580]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_writing_custom_healthindicators

The documentation mentions the UNKNOWN status but does not mention what influence it has on the HTTP response code.
Please add a short note that UNKNOWN does not contribute to the overall status and essentially gets ignored.

**Comment by wilkinsona** [comment]
I think the documentation would benefit from two things:

1. An explanation of how status aggregration is performed
2. The default HTTP status mappings for the built-in statuses

**Comment by snicoll** [comment]
@mrumpf that's not what I've experienced btw. If one of the nested health is `UNKNOWN` the main status is `UNKNOWN` so it's not ignored as you seem to indicate. Can you double check you have not a customization on your end that leads to this?

**Comment by mrumpf** [comment]
Thanks for the clarification. I did not look into the code before, so because the aggretion rules had not been describes in the documentation and most of our health indicators returned UP, it seemed as if the UNKNOWN was simply ignored. Now with the description the behavior gets pretty clear without having to look into the code.
