### ISSUE TITLE
launch.script doesn't seem to be included with distribution archive

### ISSUE THREAD

**Issue by UnsungHero97** [spring-projects/spring-boot#9587]
Gradle v4.0
Spring Boot v2.0.0.M2

I'm trying to package an executable jar with the gradle plugin for distribution, and I'm struggling to understand how to configure the launch / startup script. From the docs:

https://docs.spring.io/spring-boot/docs/2.0.0.M2/gradle-plugin/reference/html/#packaging-executable-configuring-launch-script

```
bootJar {
  classifier = 'boot'
  launchScript {
    included = true
    properties 'initInfoShortDescription': 'Hello', 'initInfoDescription': 'Hello'
  }
}
```

After running `build` and extracting the distribution from the tar/zip, the script in `bin` looks a lot like Gradle's `unixStartScript`:

https://github.com/gradle/gradle/blob/v4.0.0/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

... and not at all like Spring Boot's `launch.script`:

https://github.com/spring-projects/spring-boot/blob/v2.0.0.M2/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script

Further, the property values I passed in for `initInfoShortDescription` and `initInfoDescription` are nowhere to be found.

Am I missing something? What else do I need to do to configure Spring Boot's launch / startup script correctly?

**Comment by wilkinsona** [comment]
The launch script is entirely separate to the start scripts that are created when the application plugin is applied. In fact, both applying the application plugin and including the launched script in the jar doesn't really make much sense.

As hopefully suggested by the fact that it's a configuration option on BootJar, the launch script is prepended to the jar file such that the jar itself can be executed directly. Please see the [Gradle plugin documentation](http://docs.spring.io/spring-boot/docs/2.0.0.M2/gradle-plugin/reference/html/#packaging-executable-configuring-launch-script) and [main reference guide](http://docs.spring.io/spring-boot/docs/2.0.0.M2/reference/htmlsingle/#deployment-install) for further details.
