### ISSUE TITLE
Spring Boot 2.0.0.M2 Starter Webflux Default Locale not resolved

### ISSUE THREAD

**Issue by dharrigan** [spring-projects/spring-boot#9588]
Hi,

% java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Spring Boot 2.0.0.M2
Thymeleaf 3.0.6
Thymeleaf-Spring5 3.0.7-SNAPSHOT

I have a very simple Spring Boot 2.0.0.M2 application that resolves a Thymeleaf template. I've noticed that if I switch to spring-boot-starter-webflux, then the default locale does not appear to be resolved, resulting in an error when Thymeleaf is invoked. This does not happen if I use spring-boot-starter-webmvc.

```
@SpringBootApplication
public class Hello {
    public static void main(final String[] args) {
        SpringApplication.run(Hello.class, args);
    }
}
```

This controller results in the error below:

```
 @Controller
 public class SimpleController {
    @GetMapping
    public Mono<String> get(final Model model) {
        model.addAttribute("name", "Success");
        return Mono.just("index");
    }
 }
```

`curl http://localhost:8080`

```
2017-06-24 08:13:08.043  INFO 5629 --- [           main] online.harrigan.Hello                    : Started Hello in 2.43 seconds (JVM running for 3.248)
2017-06-24 08:13:11.765 ERROR 5629 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : Failed to handle request

java.lang.IllegalArgumentException: Property 'locale' is required
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveView.renderFragmentInternal(ThymeleafReactiveView.java:304) ~[thymeleaf-spring5-3.0.7-SNAPSHOT.jar:3.0.7-SNAPSHOT]
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveView.renderInternal(ThymeleafReactiveView.java:289) ~[thymeleaf-spring5-3.0.7-SNAPSHOT.jar:3.0.7-SNAPSHOT]
	at org.springframework.web.reactive.result.view.AbstractView.lambda$render$0(AbstractView.java:183) ~[spring-webflux-5.0.0.RC2.jar:5.0.0.RC2]
```

Note that if I pass in the Accept-Language to curl, it works correctly (or if I access the endpoint via a browser) - so it's not due to webflux misunderstanding that is is an API (Rest) call.

If I swap back to a non-reactive implementation (replacing spring-boot-starter-webflux with spring-boot-starter-webmvc and removing the mono call), it works:

```
@Controller
public class SimpleController {

    @GetMapping
    public String get(final Model model) {
        model.addAttribute("name", "Success");
        return "index";
    }
}
```

`curl http://localhost:8080`

```
curl -v http://localhost:8080
* Rebuilt URL to: http://localhost:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 
< Content-Type: text/html;charset=UTF-8
< Content-Language: en-GB
< Transfer-Encoding: chunked
< Date: Sat, 24 Jun 2017 07:25:54 GMT
< 
<!DOCTYPE HTML>
<html>
<body>
Hello <span>Success</span>!
</body>
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
</html>%
```

**Comment by sdeleuze** [comment]
@dharrigan Could you please create this issue on https://jira.spring.io/browse/SPR and give me the link to it? I will have a look.

**Comment by bclozel** [comment]
Locale resolution was introduced in Spring Framework 5.0.0.RC2 with [SPR-15036](https://jira.spring.io/browse/SPR-15036). Judging from your report, it's not yet clear if this has something to do with Spring Framework or Thymeleaf itself.

When creating that issue in Spring Framework, could you also provide a snippet of your thymeleaf template? Thanks

**Comment by dharrigan** [comment]
@sdeleuze thank you. ticket has been created: https://jira.spring.io/browse/SPR-15705.

I can send you my tiny project if you wish. I'll also reach out to Daniel at Thymeleaf.

-=david=-
