### ISSUE TITLE
Upgrade to a version of Spring Security OAuth that's compatible with Spring Security 5

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#9589]
I tried to use Spring Boot 2.0.0.M2, add `spring-security-oauth2` and `spring-security-jwt` in projects, and used the Spring Boot shipped version. 

When I started the application, and got the following error info. it seems Spring Security 5.0 removed `org/springframework/security/crypto/codec/Base64`.  Spring Boot has to update the **spring-security-oauth2** in 2.0.0 and make sure it is aligned with Spring Security 5.0

>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [com/hantsylabs/sample/springmicroservice/auth/OAuth2AuthorizationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/crypto/codec/Base64

**Comment by wilkinsona** [comment]
This needs to be 2.2.0 snapshots now. Per @rwinch "this will be out on or more likely before July 13th".
