### ISSUE TITLE
bug in launch.script which might cause other process to being killed

### ISSUE THREAD

**Issue by bacher09** [spring-projects/spring-boot#9596]
[isRunning](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L90)  function in launch.script have insufficient checks. It isn't checks that process that going to be killed (during stopping) is still process of same application and because of that it might kill other application.

For example under some circumstances spring-boot application might be killed, but pid file will continue to have this pid. Then some other applications might use this pid and when someone will call stop or restart -  launch.script will try to kill this application. Probability that another application will use same pid until someone will call restart or stop is low but it still possible. 

isRunning function, should check not only that process exists, it also should ensure that process is same application. For example, it possible to create extra environment variable that contains random data. In that case, to ensure that process is still same application it would be enough to check that process still have same environment variable with same value. Such workaround have it's own issues, since application might change environment variables.

**Comment by wilkinsona** [comment]
> It isn't checks that process that going to be killed (during stopping) is still process of same application and because of that it might kill other application.

I believe that it's guaranteed that PIDs will be allocated sequentially and will only wrap and start reusing PIDs when they reach their upper limit. So, unless you're running near to the maximum number of processes such that reuse is likely to occur quickly, I think this is fairly unlikely to happen.

> it also should ensure that process is same application

Thank you for the suggestion. Unfortunately, I don't believe that there's a way to do this that's sufficiently portable for it to be included in the standard launch script. If the problem remains a concern for you then I would recommend using a custom script.

**Comment by bacher09** [comment]
I filled this issue because I already have seen this behavior couple times. Server crashed, and after crash script killed another process.

**Comment by wilkinsona** [comment]
That's unfortunate, but it doesn't really change the situation. As I said above, unless you have a proposal for a way to reliably identify that the process listed in the pid is the right process, there's not much we can do. We need something that is, at the very least, portable across the various standard Linux distributions.

**Comment by bacher09** [comment]
Actually checking environment is very portable way across all linux distributions, since all distributions have [/proc](http://man7.org/linux/man-pages/man5/proc.5.html) folder and environment can be found as `/proc/$pid/eviron` . ps utility is using /proc filesystem for listing processes and it have very stable API. But It isn't portable across other *nix systems, like FreeBSD or OpenBSD. However, FreeBSD have linux compatible [/proc](https://www.freebsd.org/cgi/man.cgi?linprocfs(5)) filesystem which is made for running linux applications, but it isn't enabled by default.

Moreover, I think there should be other ways to make such checks.

**Comment by wilkinsona** [comment]
> Actually checking environment is very portable way across all linux distributions

You said yourself above that checking the environment may not be reliable.

> Moreover, I think there should be other ways to make such checks

There may well be. If you'd like to propose something, then please open a pull request and we can consider merging it. However, I would note that the sort of checking that you're proposing doesn't seem to be something that's particularly common. For example, I've just experimented with Apache HTTPD and it will kill whatever process is listed in the pid file. For us to merge something, we'd have to be close to certain that it works as advertised. I think a check that claims to reliably identify the correct process but fails to do so in some circumstances would be worse than not performing a check at all.

**Comment by bacher09** [comment]
What linux distribution you used for this test ? For example debian scripts is using [start-stop-daemon](https://anonscm.debian.org/cgit/dpkg/dpkg.git/tree/utils/start-stop-daemon.c#n1940), which checks process executable file and other options (like process owner, parent, etc), but those checks depends on init script itself. Also I checked apache init script in ubuntu 14 lts, it checks process name in addition to PID. This probably still not sufficient check, but better then nothing.

Also, there is another scenario which increases probability of this bug. For example if you system is running in some virtual machine (let suppose aws) and you made server snapshot. Snapshot will contain pid file. And if you will create new VM from this snapshot it might kill another process during boot.

**Comment by wilkinsona** [comment]
I tested with `apachetcl` in Ubuntu 15.10. A pull request is still welcome.
