### ISSUE TITLE
org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer why not public

### ISSUE THREAD

**Issue by lanmolsz** [spring-projects/spring-boot#9601]
it is not public, so `@ConditionalOnMissingBean` does not work, and I can not create an aop object based on it.

**Comment by snicoll** [comment]
We don't use the tracker for questions. Please join us on Gitter if you want to chat.

**Comment by snicoll** [comment]
You do have a point that `@ConditionalOnMissingBean` is useless though. Let's remove that.

**Comment by snicoll** [comment]
On a second though, there are other things related to this that I intend to fix in #9528 so let's duplicate this one.

**Comment by lanmolsz** [comment]
I added a multi-tenant support on the basis of spring-boot. I used aop to create a proxy object for the datasource.
```java
public class MultiTenantDatasource implements javax.sql.DataSource{
    private Map<String,DataSource> datasources = new HashMap<>();
    
    public  Connection getConnection() throws SQLException{
        return datasources.get(TenantContext.currentTenantId).getConnection();
    }
    ///....
}
```
I would like to use aop to enhance DataSourceInitializer,Traverse these tenants and call the DataSourceInitializer's init method.This can be very compatible with spring-boot, and will not conflict with Spring's logic, but this requires DataSourceInitializer is public.

**Comment by snicoll** [comment]
No it won't and that's why the class is not public. Thanks for sharing your use case though. Please watch #9528
