### ISSUE TITLE
Upgrade plugin versions

### ISSUE THREAD

**Issue by SebastianDietrich** [spring-projects/spring-boot#9613]
Please upgrade maven-plugin versions:   
- maven-clean-plugin.version 2.6.1 --> 3.0.0
- build-helper-maven-plugin.version 1.10 --> 3.0.0
- maven-compiler-plugin.version 3.1 --> 3.3 (higher versions don't run with eclipse)
- maven-assembly-plugin.version 2.6 --> 3.0.0
- maven-surefire-plugin.version 2.18.1 --> 2.20
- maven-failsafe-plugin.version 2.18.1 --> 2.20

**Comment by wilkinsona** [comment]
I'd prefer to consider and, if appropriate, upgrade each plugin separately. To that end, can you please open a separate issue for each of these? Please note that we already have one for upgrading Surefire (#9414)

**Comment by snicoll** [comment]
We do have one for the assembly plugin as well.

**Comment by SebastianDietrich** [comment]
See #9618, #9619, #9620

**Comment by philwebb** [comment]
I've targeted most of these to M4 because I we're working on some general build restructuring.
