### ISSUE TITLE
Error creating proxy classes with Objenesis on Google App Engine standard / Java 8

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-boot#9615]
Hi, 

I'm beta testing [Google App Engine standard](https://cloud.google.com/appengine/docs/java/) + Java 8, and I've stumbled upon a new error when upgrading to :

 * Spring Boot 1.5.4
 * Google App Engine SDK 1.9.54

You will find the [complete startup logs here](https://github.com/spring-projects/spring-boot/files/1105331/appengine-devserver-startup-logs.txt), but here are the interesting bits :

    [INFO] Caused by: 
    [INFO] org.springframework.aop.framework.AopConfigException: Unable to instantiate proxy using Objenesis, and regular proxy instantiation via default constructor fails as well; nested exception is java.lang.InstantiationException: org.springframework.boot.autoconfigure.web.HttpMessageConverters$$EnhancerBySpringCGLIB$$3ba87c15
    [INFO] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:76)
    [INFO] 	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:201)
    [INFO] 	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
    
    ...
    
    [INFO] Caused by: 
    [INFO] java.lang.NoSuchMethodException: org.springframework.boot.autoconfigure.web.HttpMessageConverters$$EnhancerBySpringCGLIB$$3ba87c15.<init>()
    [INFO] 	at java.lang.Class.getConstructor0(Class.java:3082)
    [INFO] 	at java.lang.Class.newInstance(Class.java:412)
    [INFO] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:73)
    [INFO] 	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:201)
    [INFO] 	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)

Here is a sample application that I use to share issues with the Google team : 
https://github.com/michaeltecourt/appengine-spring-boot

The problem is really easy to replicate, you can start the app engine development server with `mvn appengine:devserver`. It launches a Jetty server customized by Google's folks and deploys the WAR.  
As you can see an exception ocurs during the application startup, and the server returns 503 for every requests.  
I suspected some good old dependency version conflict but Google's @ludoch talked about a bug fix in Objenesis that may have not been integrated in Spring Boot yet.

I found the issue in another more complex project, the same exception also occurs with every `@Component` that does not have a default constructor, even when the all-args constructor is annotated with `@Autowired` : 

    [INFO] Caused by: 
    [INFO] org.springframework.aop.framework.AopConfigException: Unable to instantiate proxy using Objenesis, and regular proxy instantiation via default constructor fails as well; nested exception is java.lang.InstantiationException: com.gleamfootball.service.game.datastore.PlayDatastoreRepository$$EnhancerBySpringCGLIB$$6a00cd1f
    [INFO] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:76)
    ...
    [INFO] Caused by: 
    [INFO] java.lang.InstantiationException: com.gleamfootball.service.game.datastore.PlayDatastoreRepository$$EnhancerBySpringCGLIB$$6a00cd1f
    [INFO] 	at java.lang.Class.newInstance(Class.java:427)
    [INFO] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:73)
    [INFO] 	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:201)
    [INFO] 	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
    [INFO] 	at org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.postProcessAfterInitialization(AbstractAdvisingBeanPostProcessor.java:90)

For info, the application starts without any issue as an executable WAR with Spring Boot's embedded jetty, as you can see by running this [Spring Boot test](https://github.com/michaeltecourt/appengine-spring-boot/blob/master/src/test/java/com/github/michaeltecourt/appengine/server/SampleSpringBootApplicationTest.java) in the sample app.

**Comment by snicoll** [comment]
Thanks but the issue has [already been reported](https://jira.spring.io/browse/SPR-15600) and an upgrade of Objenesis is in progress that we will integrate in due course so there is no need to create a duplicate.

**Comment by michaeltecourt** [comment]
oh I couldn't find a GitHub issue, forgot about Spring framework's old issue tracker

**Comment by snicoll** [comment]
Or you guys could synchronize maybe? I know a few folks at Google were working on this (see the history of the JIRA issue for more details). Thanks!

**Comment by michaeltecourt** [comment]
yeah I was told by a Googler to "synchronize" by checking the tracker for an existing issue, but I didn't check the right one so I took the time to give feedback here, my bad.

**Comment by snicoll** [comment]
@michaeltecourt not at all, that was a superb description by the way!
