### ISSUE TITLE
Upgrade to maven-compiler-plugin 3.6.1

### ISSUE THREAD

**Issue by SebastianDietrich** [spring-projects/spring-boot#9620]
Please upgrade maven-compiler-plugin.version 3.1 --> 3.3 (higher versions don't run with eclipse)

**Comment by snicoll** [comment]
What is the issue for the Eclipse problem?

**Comment by SebastianDietrich** [comment]
see https://github.com/tesla/m2eclipse-mavenarchiver/issues/9 (same for compiler, jar, war plugin)

**Comment by wilkinsona** [comment]
@SebastianDietrich Thanks for the link. The conclusion seems to be that the problem's resolved in Neon.1 and m2e 1.17.2.201609252051. Does your experience not agree with that?

**Comment by SebastianDietrich** [comment]
You are probably right - I am using Neon.0. Had no time to try updates or Oxygen

**Comment by SebastianDietrich** [comment]
I can confirm that 3.6.1 works with Eclipse Oxygen 4.7.0
