### ISSUE TITLE
Enforce Java (and Maven?) versions in spring-boot-starter-parent

### ISSUE THREAD

**Issue by rupert654** [spring-projects/spring-boot#9626]
`spring-boot-parent` uses `maven-enforcer-plugin` to force a minimum Java version on the compiler. This gives a more helpful error message when building the project.

Perhaps `spring-boot-starter-parent` should also enforce the minimum Java version using this plugin?

Given that the minimum version of Java is being bumped to 8, in Spring Boot 2.0.0, this seems like an ideal point to introduce the change.

The docs state that there is a minimum version of Maven supported as well (3.2). Perhaps the parent should enforce this as well?

Happy to open a PR if you think this is a good idea.

**Comment by snicoll** [comment]
I am not keen to add such a check by default. Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
This seemed like quite a good idea to me. @snicoll, can you please explain why you're not keen on it?

**Comment by snicoll** [comment]
Obviously knowing upfront that your environnement has an issue is a good thing.

The reason why I am not too keen about it is that those checks will run at every build including the gazillion of projects out there that are perfectly fine. Seems like a bit nuclear to me from that perspective.

**Comment by wilkinsona** [comment]
> The reason why I am not too keen about it is that those checks will run at every build including the gazillion of projects out there that are perfectly fine.

That's a price that's paid for any check like this. Given your objection, I'm guessing that in this particular case you feel that the check is prohibitively slow?

**Comment by snicoll** [comment]
>  I'm guessing that in this particular case you feel that the check is prohibitively slow?

Yes but that's more of a feeling so I need to look into it indeed. Thanks!

**Comment by philwebb** [comment]
I'm not sure the enforcer rule is really necessary if you use our starter parent. We're going to default the `java.version` to `1.8` anyway, so the compiler should be already configured. I'm guessing if you try to compile `1.8` code with a `1.6` JDK then things will fail.

If this is only protecting someone settings a `<java.version>1.6</java.version>` property in their POM, then I'm not sure it's worth it.

**Comment by wilkinsona** [comment]
It'd also give a clearer failure message if a too old version of Maven is used. That feels like it could be quite useful as I can imagine the cause of any problems not being very obvious

**Comment by rupert654** [comment]
@philwebb

My apologies in advance if my limited understanding is not correct but I'm following through the docs for javac: http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html

Setting "java.version" in the pom, essentially sets both the source and target of javac to the same version.

Setting the "target" of javac will produce bytecode, that will produce an error at runtime, if you run on a JVM of an earlier version. So setting the "target" to 1.4 will produce an error if you run on a JVM of 1.3. This is helpful but gives you no error at compile time and no error if you compile with a JDK later than the target.

Setting the "source" of javac will produce an error at compile time, if you use a language feature not available in this version. So setting the "source" to 1.4 will produce an error if you use generics, even if you compile with a JDK of 1.5 or later.

However, "source" does **not** protect you from using classes introduced in later versions of the standard library. For example, if you compile with JDK 1.8 and set the source and target to 1.7, but use class introduced in Java 1.8 your code, then you will get no warning that there is a problem until somebody tries to run your code on 1.7. If you want a warning then you either must compile with JDK 1.7, or change the "bootclasspath" of javac so that it matches 1.7.

In the case of Spring Boot 2.0.0, this would only be an issue when Java 1.9 came out. The enforcer warning would prevent you from accidentally making this mistake if you used any classes introduced in Java 1.9, when you needed to target 1.8.

**Comment by wilkinsona** [comment]
> The enforcer warning would prevent you from accidentally making this mistake

How does it do that? I thought you needed to use something like Animal Sniffer to avoid using classes that were available in the JDK you're compiling against but are not available in the one that you're targeting.

**Comment by rupert654** [comment]
I think it just matches the version. So if you have enforced 1.8, then 1.9 will fail regardless of whether you have or have not used classes available only in 1.9.

If you want to use classes available in 1.9, then you must explicitly make that decision by bumping the version number. Therefore, you can't do so unintentionally (or at least you will know about it at the next build if you do).

**Comment by wilkinsona** [comment]
We plan to support Java 9 in Boot 2.0 so locking things down to 8 isn't really an option. The enforcer plugin does [support version ranges](http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html), however. We could enforce 1.8 and later.

I still think there's some merit in enforcing the minimum version of Maven that we support, however that's only a concern of Spring Boot's Maven plugin and you could be using our parent but not using our plugin. In other words, it's something that the plugin should enforce itself.

**Comment by philwebb** [comment]
Given the issues documented above I don't think we should try to enforce the version (but thanks for the suggestion).
