### ISSUE TITLE
Infinispan Jcache cannot load config file defined by spring.cache.jcache.config property

### ISSUE THREAD

**Issue by beihaifeiwu** [spring-projects/spring-boot#9631]
```properties
spring.cache.jcache.provider=org.infinispan.jcache.embedded.JCachingProvider
spring.cache.jcache.config=classpath:infinispan.xml
```

org.infinispan.jcache.embedded.JCacheManager:
```java
   private ConfigurationBuilderHolder getConfigurationBuilderHolder(
         ClassLoader classLoader) {
      try {
         FileLookup fileLookup = FileLookupFactory.newInstance();
         InputStream configurationStream = getURI().isAbsolute()
               ? fileLookup.lookupFileStrict(getURI(), classLoader)
               : fileLookup.lookupFileStrict(getURI().toString(), classLoader);
         return new ParserRegistry(classLoader).parse(configurationStream);
      } catch (FileNotFoundException e) {
         // No such file, lets use default CBH
         return new ConfigurationBuilderHolder(classLoader);
      }
   }
```

org.infinispan.commons.util.AbstractFileLookup:
```java
   @Override
   public InputStream lookupFileStrict(URI uri, ClassLoader cl) throws FileNotFoundException {
      String scheme = uri.getScheme();
      switch (scheme) {
         case "file":
            return new FileInputStream(new File(uri.getPath()));
         case "jar":
            String uriAsString = uri.toString();
            String fileName = uriAsString.substring(uriAsString.lastIndexOf(":") + 1);
            return new FileInputStream(new File(fileName));
         default:
            InputStream streamToBeReturned = getAsInputStreamFromClassLoader(uri.toString(), cl);
            if(streamToBeReturned == null) {
               throw log.unableToLoadFileUsingScheme(scheme);
            }
            return streamToBeReturned;
      }
   }
```

When use spring boot maven plugin package the project, the lib under BOOT-INF contains the jar files, but infinispan cannot retrieve it from the uri, Is this a bug or something ?

**Comment by snicoll** [comment]
> infinispan cannot retrieve it from the uri, Is this a bug or something ?

Given the debugging session you've performed already, it's pretty clear whatever exception happens is happening in Infinispan so please report the issue in their tracker.  I'd suggest to provide a sample rather than code snippet, it's very hard to reason about a flow looking at code snippets.

**Comment by fb64** [comment]
Same issue for me with spring-boot 2 / jcache / infinispan 9.2.0, but i found a workaround : 
https://gist.github.com/fb64/0c35271e3a2f023ece33c18bba6223f8
it's a bit late but i hope it could be usefull

**Comment by snicoll** [comment]
@fb64 thanks for sharing this. Perhaps you could share that with the infinispan team as well?

**Comment by fb64** [comment]
Done !
https://issues.jboss.org/browse/ISPN-9001
https://github.com/fb64/sb2-infinispan-bug
