### ISSUE TITLE
do not allow the user to call /error directly 

### ISSUE THREAD

**Issue by saschaszott** [spring-projects/spring-boot#964]
Hi folks,

maybe I've missed something, but the current implementation of `BasicErrorController` (method `errorHtml`) do not prevent the user from calling `/error` directly in his browser. This allows the user to see the rendered error page in an unintended context. 

Would it be better to add a pre-check and redirect the user to the application's main entry point (which needs to be defined somewhere) if

 `request.getAttribute(RequestDispatcher.ERROR_STATUS_CODE)`

returns `null`?

Best regards,
Sascha

**Comment by rafis** [comment]
Does it the same in Spring Boot 2.x?
