### ISSUE TITLE
Why are we mapping properties with different names when logging in Spring Boot?

### ISSUE THREAD

**Issue by shaileshaag** [spring-projects/spring-boot#9644]
I already asked this on [StackOverflow](https://stackoverflow.com/questions/44829211/why-are-we-mapping-properties-with-different-names-when-logging-in-spring-boot?noredirect=1#comment76647992_44829211) and recommendation was to ask it on GitHub, so, here I am:

This is with reference to [Spring Boot - Logging](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html#howto-configure-logback-for-logging) documentation. Why are we mapping the property logging.path to logger variable LOG_PATH and logging.file to logger variable LOG_FILE?

This actually leads to confusion to developers who see one variable name while defining it and another name while consuming it.

**Comment by snicoll** [comment]
Unfortunately, that's not a good recommendation as we don't use the tracker for questions. Let's continue the discussion there.
