### ISSUE TITLE
Use more specific AssertJ MapAssert for return of JsonContentAssert#extractingJsonPathMapValue

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#9650]
The method [`JsonContentAssert#extractingJsonPathMap`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/json/JsonContentAssert.java#L969) returns `AbstractMapAssert`. However, the call to AssertJ returns `MapAssert`. 

This causes compiler warnings like:

```
uses unchecked or unsafe operations
```

With `Xlint` it shows:

```
unchecked generic array creation for varargs parameter of type java.util.Map.Entry<? extends java.lang.Object,? extends java.lang.Object>[]
```

The more specific `MapAssert` has final methods annotated with `@SafeVarargs` which won't show the warning.

As an alternative there can be spring boot `MapAssert` that will extend from the AssertJ `AbstractMapAssert` that will make the methods as final and annotated them with `@SafeVarargs`.

The reason why AssertJ has those `Abstract` assert classes that are not annotated is for the support of soft assertions (that are done by using proxies).

See https://github.com/joel-costigliola/assertj-core/issues/1017 for more information as well.

**Comment by philwebb** [comment]
Thanks for the details analysis. I'll close this one favor of PR #9675
