### ISSUE TITLE
Allow the TTL of Tomcat's resource cache to be configured via the environment

### ISSUE THREAD

**Issue by bohrqiu** [spring-projects/spring-boot#9670]
All http request served by tomcat will `validateResource`,when StandardRoot has too many resouces(`org.apache.catalina.webresources.StandardRoot#allResources`),the performance is slow. spring-boot 1.5.1 has the problem，allResources contains all classpath library. thanks committers ,this have been fixed at spring-boot 1.5.4.

![wechatimg33](https://user-images.githubusercontent.com/1333657/27786148-9c94be96-6012-11e7-8a88-f498d822d801.jpeg)

but when app run in fatjar or war，resource can't be change anymore,tomcat `org.apache.catalina.webresources.Cache#ttl` is too short(default is 5 second).

in my case ,i had set the cache as follows:

	 ((TomcatEmbeddedServletContainerFactory)factory).addContextLifecycleListeners(
              event -> {
                if (event.getType().equals(Lifecycle.CONFIGURE_START_EVENT)) {
                  ((StandardContext) event.getLifecycle())
                      .getResources()
                      .setCacheTtl(100l * 24 * 60 * 60 * 1000);//set cache ttl 100 days
                }
              });

can there be have some default strategy for this?

**Comment by philwebb** [comment]
I'm not sure that we can safely make the assumption that because someone is running a fat war, the Tomcat resources won't change. The `WebResourceRoot` interface is quite general and can cover resources from a variety of different sources. I'm also not keen to deviate from the Tomcat defaults.

Are you seeing any practical problems with the default timeout? Are there performance issues?

My initial reaction is that we shouldn't change the defaults, but perhaps we could make things easier to configure.

**Comment by bohrqiu** [comment]
yes,We've had performance issues at spring-boot 1.5.1，cause of spring-boot add all classpath jar to tomcat resouces(org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.StoreMergedWebXmlListener#onStart L826).

    		TomcatResources.get(context).addClasspathResources();


and at spring-boot 1.5.4,TomcatEmbeddedServletContainerFactory L228

  
  
 TomcatResources.get(context).addResourceJars(TomcatEmbeddedServletContainerFactory.this.getUrlsOfJarsWithMetaInfResources());

when cache is expired,all jar will be check if contain the resouce.If there have  easy configure property will be  better.

**Comment by philwebb** [comment]
We'll look at adding a property to make this easier to configure.
