### ISSUE TITLE
Spring-Webflux HttpClient is not respecting http.nonProxyHosts

### ISSUE THREAD

**Issue by mehmetsalgar** [spring-projects/spring-boot#9676]
In Spring-Webflux 2.0.0.M2 it seems netty HttpClient is not respecting the http.nonProxyHosts and try to call the localhost via proxy server

**Comment by bclozel** [comment]
I'm not even aware of Netty / Reactor Netty supporting JDK style `http.*` environment variables. As far as I know, those libraries don't use the HTTP stack in `java.net`.

You'll find an opened issue about [client proxy support in Netty here](https://github.com/netty/netty/issues/1133). Reactor Netty has its own support with `HttpClientOptions` and `ClientProxyOptions`.

You can create your `WebClient` instance by providing a customized `ReactorClientHttpConnector` (with your own `HttpClientOptions`).

If you're using the `HttpClient` directly, you should create an issue on [the reactor-netty project](https://github.com/reactor/reactor-netty).

**Comment by mehmetsalgar** [comment]
I am using this code to create 'org.springframework.web.reactive.function.client.WebClient'

private WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(options -> options.preferNative(false))).build();

and options does not have any possibility to pass 'nonProxyHosts', you mean this Reactor-Netty problem I can contact with them but this does not change the fact that Webflux is at moment not able use 'nonProxyHosts' concept.

**Comment by bclozel** [comment]
`WebClient` consistently wraps other HTTP clients - for now, only reactor-netty is supported. So yes, this feature should be discussed in the reactor-netty tracker.

You could compare `WebClient` and `RestTemplate` - when it comes to options like this, we're relying on the underlying client configuration.
