### ISSUE TITLE
Automatically register apple touch icons

### ISSUE THREAD

**Issue by Glamdring** [spring-projects/spring-boot#9680]
In the `FaviconConfiguration`, I think it would be useful to add all the apple-specific touch-icons (e.g. `apple-touch-icon.png`, `apple-touch-icon-precomposed.png`, etc.). It's a bit stupid that apple devices to request these non-standard icons, but I guess they are de-facto standard now, so it's good to resolve them against `favicon.png` instead of failing to locate them.

**Comment by marti1125** [comment]
@philwebb I want to work on this :D

**Comment by OrangeDog** [comment]
If people want to take advantage of these Apple features, they can easily add these resources themselves.
This shouldn't be done automatically, as it changes the behaviour of these devices.

A web server on the internet is going to receive loads of requests fro random resources that don't exist.
It's just a fact of life that people need to accept.

**Comment by Glamdring** [comment]
Is it that easy, though? I struggled a bit to find the proper alignment of the stars to get it working :) What is the canonical way to do it?

**Comment by wilkinsona** [comment]
I don't think it makes sense to do this. [Apple's documentation](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) recommends adding `<link>` elements to your HTML referencing the files. Those files should then be placed in the root of one your app's static resource locations, for example `src/main/resources/static`.

**Comment by Glamdring** [comment]
@wilkinsona you can say that about the regular favicon as well :)

**Comment by wilkinsona** [comment]
Not really. A browser loads a favicon by convention from a specific location, whereas the touch icons are loaded from a location that you've configured in the `<link>` elements of your HTML document's header.

**Comment by Glamdring** [comment]
Well, from what I see in my logs, apple devices request the icon even though it is not in a <link> tag. 
It's obviously wrong to do that, but it happens
