### ISSUE TITLE
Stop defaulting spring.session.store-type to Redis

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9682]
Historically, and then for backward compatibility reason, `spring.session.store-type` defaults to Redis if it's available. Now that Spring Session ships with several stores support we should stop doing that.

cc @rwinch @vpavic

**Comment by vpavic** [comment]
@snicoll Wasn't this already handled in #7858?

**Comment by snicoll** [comment]
Yep. I forgot I already did it.
