### ISSUE TITLE
Improve Startup of Spring Integration Test 

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-boot#9685]
Enhancement

It would be really useful to provide a native mechanism to tell spring boot test to mark all beans in the context as "lazy". This can substantially speed up running an individual integration test, as you only have to wait for the initialization of beans that have actually been injected into the test. Even if this were an "opt-in" strategy, I think a lot of people would find it useful.

We solved this problem, in our environment, by adding a BeanFactoryPostProcessor that marks all beans within the application context as "lazy". We add this processor only in our testing context and we have seen anywhere between a 10 and 20 seconds improvement in startup of individual tests. This also improves overall runtime when tests use mock beans or dirty the context, a subsequent test will start more quickly when the new application context is initialized.

This strategy works in a majority of cases except when using one of Spring's DSLs (like spring integration). The problem with these is that the flows are not directly referenced by any class, but the beans they create ARE. We had two work arounds for this use case: You can `@Autowire` the flows within a test to insure your beans are created or you can add a list of class exclusions to the post processor.

I think there might be a more elegant way to do this but this is the post-processor we are using today:

```java
/**
 * This post processor will mark all beans in the context as "lazy", meaning they will be loaded "on-demand".
 * This can substantially speed up running a single integration test, as it will ONLY initialize the beans references
 * by that test. This strategy works in a majority of cases except when using one of Spring's DSLs (like spring integration).
 * In those cases, those integration flows indirectly create additional beans that may be needed as dependencies in 
 * specific tests. This class can be initialized with a set of exclusion classes, such that beans that are are assignable
 * to one of the classes in the exclusion list will NOT be lazy initialized.
 * 
 * <pre>
 * Example:
 * 
 * {@code
 *	@Bean
 *	public BeanFactoryPostProcessor lazyBeanPostProcessor() {
 *		return new ServiceTestLazyBeanFactoryPostProcessor();
 *	}
 *
 *	static private class ServiceTestLazyBeanFactoryPostProcessor extends LazyInitBeanFactoryPostProcessor {
 *		public ServiceTestLazyBeanFactoryPostProcessor() {
 *			super(new Class<?>[] {IntegrationFlow.class});
 *		}	
 *	}
 * 
 * </pre>
 */
public class LazyInitBeanFactoryPostProcessor implements BeanFactoryPostProcessor {

	private Class<?>[] exclusionList;
	
	public LazyInitBeanFactoryPostProcessor() {
	}

	public LazyInitBeanFactoryPostProcessor(Class<?>[] exclusionList) {
		this.exclusionList = exclusionList;
	}
	
	@Override
	public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
		
		//Iterate over all bean, mark them as lazy if they are not in the exclusion list.
		for (String beanName : beanFactory.getBeanDefinitionNames()) {
			if (isLazy(beanName, beanFactory)) {
	       		BeanDefinition definition = beanFactory.getBeanDefinition(beanName);
	       		definition.setLazyInit(true);
			}
		}
	}
	
	private boolean isLazy(String beanName, ConfigurableListableBeanFactory beanFactory) {
		if (exclusionList == null || exclusionList.length == 0) {
			return true;
		}
		for (Class<?> clazz : exclusionList) {
			if (beanFactory.isTypeMatch(beanName,clazz)) {
				return false;
			} 
		} 
		return true;		
	}
}
``` 

Then within our Test: 

```java
@SpringBootTest(webEnvironment=WebEnvironment.NONE)
public abstract class BaseServiceTest extends BaseTest {

	@TestConfiguration	
	protected static class ServiceTestConfiguration {
		
		@Bean
		public BeanFactoryPostProcessor lazyBeanPostProcessor() {
			return new ServiceTestLazyBeanFactoryPostProcessor();
		}
		

		static private class ServiceTestLazyBeanFactoryPostProcessor extends LazyInitBeanFactoryPostProcessor {	
			public ServiceTestLazyBeanFactoryPostProcessor() {
				super(new Class<?>[] {IntegrationFlow.class});
			}	
		}
	}

```

**Comment by philwebb** [comment]
This is an interesting idea but I do worry that it might cause unexpected side effects. I generally prefer the test slice annotation approach as it limits what is _actually_ loaded rather than what _could_ be loaded.

I guess this approach works quite well if you're repeatedly running a single test from your IDE, and it happens to be a tests that doesn't need a type of bean that's slow to run. If you're running multiple tests during a regular build then Spring Tests's context caching should mean that the context is only loaded once anyway.

@tkvangorder What sort of improvements have you seen using this technique? Do you have a feel for which of your beans are slow to start? Have you found context caching not to help that much?

I'll flag this for team attention, but I'm afraid I'm somewhat reluctant to promote this approach unless someone can persuade me that there are major benefits.

**Comment by tkvangorder** [comment]
We have a fairly large monolithic application and we are moving our unit testing over to use the Spring Boot Test annotations. Our longer term goal is move these tests over to use the slices, but we are not there yet.

This specific solution was needed to speed up the execution of a single test, which required the entire application context for a project to be initialized prior to running the test.

We do benefit from the context caching when running a suite of tests, however, if a test dirties the context, we again have to wait for the entire context to be reinitialized. (Using @MockBean appears to dirty the context, which has made us reluctant to adopt MockBean across our tests.)

What we do have : 

A data access project that has a large set of DAOs + Mybatis Mappers for relational data access. In that same project, we also have several DAOs that use Mongo and in our integration tests, we are using the embedded Mongo test infrastructure. 

All of our integration tests currently extend the same test base class and that one class sets up a single context with all DAOs, Mybatis mappers, and the embedded mongo infrastructure. Running each test, we end up having to initialize the entire context just to then exercise a single DAO. Before we introduced the lazy loading, the application context was taking 12 seconds to initialize, after introducing the lazy loading this dropped to 4 seconds. This is a large "win" for our devs, as they are not sitting around quite as long.

In our service layer, it gets worse. The service layer's integration test initializes all of the beans from the data access project and then adds service objects, Spring Integration flows (in our tests the "out" channels  simply map to loggers). This context has 880+ beans and takes about 35 seconds to load. We take that hit if we are running one test or if we are running a suite of tests. After we introduced lazying loading in this layer, simple tests (with a single service bean injected into them) were only taking 10 seconds to initialize the context.

I had/have the same concerns you have: If we lazy load everything, what items are failing startup during the test that really shouldnt? (Beans that start up thread pools and listeners, beans that are not directly referenced but create additional beans like in the spring integration DSL, beans that gracefully shutdown infrastructure (like embedded mongo)) 

It was not as bad as I thought to sweep our tests to get them running. The flows were really the only blocker and once we excluded them everything seemed to work pretty well. We turn "off" all spring cloud infrastructure, rabbitmq, caching, etc in our test profile, so we havent run into any issues (that I know of) with something not shutting down properly. 

I can say that we have all 5000+ tests now working and we have sped up the code/test cycle around single tests quite a bit. 

A couple ideas that I had : 

- Have a marker annotation that could be used to say "not a candidate for lazy loading". This might be tough, as each auto-configured configuration would need to be examined to find those candidate and add the marker to them. Bleh.

- Have an annotation that enables lazy loading and provide an attribute to that annotation with a list of classes that should be excluded from lazy loading. 

Or the third option.....this is just too specific to our environment and you can tell me to "kick rocks" 8)

**Comment by wilkinsona** [comment]
> I'll flag this for team attention, but I'm afraid I'm somewhat reluctant to promote this approach unless someone can persuade me that there are major benefits.

I agree with, @philwebb. I'd prefer to promote the use of slicing and/or profiles to control the beans that are or are not part of the context. I think that adding another option in Boot to make everything `@Lazy` will lead to confusion as it won't be obvious which approach people should use.

I'm further convinced that we should do anything specifically for this in Boot by the fact that it can be done relatively easily used a BFPP that can then be tailored to suit an individual project's needs.

**Comment by philwebb** [comment]
Thanks for the suggestion, but I think we'll close this for now due to the comments above.

**Comment by tkvangorder** [comment]
Makes sense to me, at the very least others can use my example if they run into a similar issue. Thanks for looking into it.

**Comment by dsyer** [comment]
I think this might be worth a second look. It's a very simple idea, but Bill says it works well for his app. It shaves more than 20% off the startup time of Petclinic even (which is a pretty simple app). The tests in Petclinic use slices though, so you don't gain much really in practice for that app. But for large, slow apps where integration tests are the norm, it could be quite a big deal.
