### ISSUE TITLE
Very simple: add all of the relevant functionality from Apache Tomcat 7 Maven Plugin

### ISSUE THREAD

**Issue by alan-czajkowski** [spring-projects/spring-boot#9687]
I would like to migrate my project from using the Apache Tomcat 7 Maven Plugin (version 2.3-SNAPSHOT) to using the Spring Boot Maven Plugin but there's quite a few important features lacking that are preventing me from doing so:

Required Enhancements:
---

- being able to set the ```path```, ```charset```, ```uriEncoding```, ```port``` and System Properties for the ```run``` goal
```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <path>/</path>
    <charset>UTF-8</charset>
    <uriEncoding>UTF-8</uriEncoding>
    <port>8888</port>
    <systemProperties>
      <example.value.1>alpha</example.value.1>
      <example.value.2>beta</example.value.2>
    </systemProperties>
  </configuration>
</plugin>
```
Example: https://tomcat.apache.org/maven-plugin-2.2/tomcat7-maven-plugin/run-mojo.html
Example: https://tomcat.apache.org/maven-plugin-2.2/tomcat6-maven-plugin/examples/add-system-properties.html

- being able to set an additional artifact to the build output *as well as* being able to set the artifact type (e.g. JAR)
```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <finalName>${project.build.finalName}</finalName>
    <attachClassifier>exec</attachClassifier>
    <artifactType>jar</artifactType>
  </configuration>
</plugin>
```

- being able to pass configuration to the container (e.g. Tomcat) on runtime to the executable JAR/WAR to set container settings:
```
$ java -DsystemProperty=value -jar artifact-1.0-exec.jar -httpPort=8080 -uriEncoding=UTF-8
```
Example: https://tomcat.apache.org/maven-plugin-2.2/executable-war-jar.html

**Comment by wilkinsona** [comment]
> being able to set the path, charset, uriEncoding, port and System Properties for the run goal

You can use the run goal's [`arguments`](http://docs.spring.io/spring-boot/docs/current/maven-plugin/run-mojo.html#arguments) and [`jvmArguments`](http://docs.spring.io/spring-boot/docs/current/maven-plugin/run-mojo.html#jvmArguments) to pass command line and JVM arguments to the application that's being run. The allows you to set any of [Spring Boot's configuration properties](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix) which, I believe, cover all of the properties that you have listed.

> being able to set an additional artifact to the build output as well as being able to set the artifact type (e.g. JAR)

Can you expand a little on what you'd like to achieve here please? I don't understand the example

> being able to pass configuration to the container (e.g. Tomcat) on runtime to the executable JAR/WAR to set container settings:

I'm not sure what this has to do with the Maven plugin. It looks like you're talking about running an executable jar. You can set any of the properties that I linked to above when you run an executable jar or war, for example:

```
java -Dserver.port=8080  your-app.jar --server.tomcat.uri-encoding=UTF-8
```

**Comment by alan-czajkowski** [comment]
@wilkinsona thanks for the information, this is very helpful

- for a Maven WAR project, when creating the executable artifact, the plugin allows you to either override the final WAR artifact (and only end up with one artifact), or lets you create a supplementary artifact by giving it a classifier, by my additional request is to allow the additional artifact with the custom classifier to *also* be able to change the file extension (artifact type) from .war to .jar

Notes from trying to implement ```<arguments>``` and ```<jvmArguments>```:

- it is way too easy to create a NPE with ```mvn spring-boot:run``` by just doing this:
```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <arguments>
      <argument></argument>
    </arguments>
  </configuration>
</plugin>
```

- ```<jvmArguments>``` needs to be a list in XML, it's much too easy to break ```mvn spring-boot:run``` with bad values

**Comment by wilkinsona** [comment]
> to also be able to change the file extension (artifact type) from .war to .jar

Sorry, but I don't think we should let people do that. The artifact is a war file (code in WEB-INF/classes, dependencies in WEB-INF/lib) so naming it .jar doesn't make much sense to me.

> it is way too easy to create a NPE with mvn spring-boot:run

This sounds like a usability bug. Please open a new issue describing exactly how to trigger the NPE. A small sample project would be ideal.

> <jvmArguments> needs to be a list in XML

I'm not sure why it isn't a list. Unless @snicoll says otherwise, please open a separate issue and we can consider changing it.

I'm going to close this issue as the main requested enhancement is not necessary.

**Comment by snicoll** [comment]
> I'm not sure why it isn't a list.

I am not sure either and 2.0 sounds a good time to fix that. @alan-czajkowski, can you please open a separate issue?
