### ISSUE TITLE
Add XMLUnit as a managed dependency and possibly to the test starter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9695]
It might be nice to add this by default. See #9691 for an example of the current problems when using `xml()` in Mock MVC.

**Comment by andrew-j-cohen** [comment]
Hi @philwebb,

This is my first contribution to the project. I was looking for an appropriate place to add a unit test for this, but I'm not sure where that would be or if its even warranted. Any feedback you have is most welcome. As a long time avid user of spring boot, I'm looking forward to more contributions in the future.

Thanks!
-Andrew

**Comment by snicoll** [comment]
Duplicate of #9709
