### ISSUE TITLE
Spring boot actuator, log exceptions encountered during health check in debug

### ISSUE THREAD

**Issue by harmen-renkema** [spring-projects/spring-boot#9710]
When a health indicator encounters an exception, the health status is considered DOWN.

It would be very helpful in a debugging scenario to also log the exception if the logger is set to debug.

**Comment by snicoll** [comment]
Duplicates #9110 unless I am missing something?

**Comment by harmen-renkema** [comment]
You're correct. Sorry about that. Prior to opening this issue I did search for existing open issues. I guess it would be a good idea to include closed issues in my search next time.
