### ISSUE TITLE
Maven plugin (spring-boot:run) should take list for JVM arguments

### ISSUE THREAD

**Issue by alan-czajkowski** [spring-projects/spring-boot#9714]
Problem: It is too easy to break ```spring-boot:run``` by passing in garbage in the ```<jvmArguments>``` configuration. Currently it looks like this (not a list):
```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <jvmArguments>any kind of garbage</jvmArguments>
  </configuration>
</plugin>
```

Solution: The Maven plugin should allow passing in Java (JVM) system properties via some kind of list definition in XML. 

Example solution:
```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <jvmArguments>
      <options>
        <option>-Xms512m</option>
        <option>-Xmx1024m</option>
      </options>
      <systemProperties>
        <systemProperty>systemProperty1=value1</systemProperty>
        <systemProperty>systemProperty2=value2</systemProperty>
      </systemProperties>
    </jvmArguments>
  </configuration>
</plugin>
```
where each ```<option>``` is passed in as-is to the JVM, and each ```<systemProperty>``` is pre-pended with a  ```-D```:
```bash
-Xms512m -Xmx1024m -DsystemProperty1=value1 -DsystemProperty2=value2
```

**Comment by andrew-j-cohen** [comment]
I think that's a good idea. Just one suggestion - to eliminate the possibility of someone forgetting the "=" in the system property, perhaps systemProperty can look something like this:

```xml
<systemProperty>
    <key>systemProperty1</key>
    <value>value1</value>
<systemProperty>
```
I'm happy to work on a PR for this.

**Comment by snicoll** [comment]
I would go with what other plugins are doing. A quick look at a well know plugin in Maven land [got me this](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#systemPropertyVariables) and [an example](http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html).

**Comment by alan-czajkowski** [comment]
@andrew-j-cohen @snicoll I agree that this is the best solution *aesthetically*:
```
<systemProperties>
  <systemProperty>
    <key>systemProperty1</key>
    <value>value1</value>
  </systemProperty>
</systemProperties>
```
but consider the case of system properties that have a key but no value, example:
```
-DpropertyWithNoValue -DpropertyWithValue=value
```
the XML would look something like this:
```
<systemProperties>
  <systemProperty>
    <key>propertyWithNoValue</key>
    <value></value>
  </systemProperty>
  <systemProperty>
    <key>propertyWithValue</key>
    <value>value</value>
  </systemProperty>
</systemProperties>
```
How would this render?
```
-DpropertyWithNoValue= -DpropertyWithValue=value
```
with a dangling equals sign on the first property?

I still think this is the best option to cover *all* possible scenarios:
```
<systemProperties>
  <systemProperty>propertyWithNoValue</systemProperty>
  <systemProperty>propertyWithValue=value</systemProperty>
  </systemProperties>
```

**Comment by alan-czajkowski** [comment]
FYI: don't forget that system property values can have spaces in them so you will have to pass them in *safely* as JVM arguments.
Example:
```xml
<systemProperties>
  <systemProperty>propertyWithNoValue</systemProperty>
  <systemProperty>propertyWithValue=value</systemProperty>
  <systemProperty>propertyWithValueContainingSpace=value has space</systemProperty>
</systemProperties>
```
should render *safely*, the equivalent of:
```bash
"-DpropertyWithNoValue" "-DpropertyWithValue=value" "-DpropertyWithValueContainingSpace=value has space"
```

**Comment by andrew-j-cohen** [comment]
@alan-czajkowski @snicoll Thank you both for your feedback. I will work on these improvements.

**Comment by wilkinsona** [comment]
@andrew-j-cohen Thanks. To avoid potentially wasted effort, I'd wait a bit till we've agreed on the format. FWIW, in the interests of consistency, I agree with @snicoll on following Surefire's lead.

**Comment by andrew-j-cohen** [comment]
I've done a bit more research and I concur with following Surefire's approach with respect to splitting out system properties from arbitrary JVM options (i.e., the "argLine" option). Note that the Surefire plugin does not prevent the user from putting in garbage (or making a typo) in the "argLine" property. However, Alan's suggested structured format for arbitrary JVM options wouldn't necessarily prevent someone from putting an invalid JVM argument in there either, so I don't think there is much to be gained with that more verbose format. Thoughts?

**Comment by wilkinsona** [comment]
@andrew-j-cohen Thanks for doing some additional research. Agreed that the more verbose format does provide much benefit. Unless @snicoll objects, let's go with a Surefire-inspired approach.

**Comment by alan-czajkowski** [comment]
@andrew-j-cohen the verbose format for JVM option is necessary because of the requirement to pass in *each* JVM option *safely* to the JVM.

Consider:
```xml
<argLine>-Xms512m -Xmx1024m followed by garbage</argLine>
```
What does this mean? What is the consequence of this? This is an important question. Because you don't care that there is garbage, what you care about is what is a *distinct* option and what is not. Does this mean:
```bash
$ java "-Xms512m -Xmx1024m followed by garbage" -jar ...
```
or does this mean:
```bash
$ java "-Xms512m" "-Xmx1024m" "followed" "by" "garbage" -jar ...
```
because these 2 results above mean 2 *very* different things to the JVM.
Note that you don't care whether garbage is passed in, you simply care that it is passed in *correctly* and *safely*. The only way to achieve *correctness* and *safety* is through something like:
```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <jvmArguments>
      <options>
        <option>-Xms512m</option>
        <option>-Xmx1024m</option>
      </options>
      <systemProperties>
        ...
      </systemProperties>
    </jvmArguments>
  </configuration>
</plugin>
```

The example below cannot achieve *correctness*, and can only achieve *limited safety*
```xml
<argLine>-Xms512m -Xmx1024m followed by garbage</argLine>
```

**Comment by vadeg** [comment]
What do you think about
```
<systemProperties>
    <propertyWithValue>value1</propertyWithValue>
    <propertyWithNoValue/>
    <propertyWithValueContainingSpace>value containing space</propertyWithValueContainingSpace>    
</systemProperties>
```
instead of
```
<systemProperties>
    <systemProperty>propertyWithNoValue</systemProperty>
    <systemProperty>propertyWithValue=value</systemProperty>
    <systemProperty>propertyWithValueContainingSpace=value has space</systemProperty>
</systemProperties>
```
?

**Comment by alan-czajkowski** [comment]
@vadeg i'm not a fan of "listing" elements like that in XML, my preference is that element lists should be clean looking whereby the top-level element is the plural word of what the list is, and each element is the singular word, example:

```
<apples>
  <apple>red</apple>
  <apple>green</apple>
  <apple>yellow</apple>
</apple>
```

even Spring uses this approach!
https://www.tutorialspoint.com/spring/spring_injecting_collection.htm

**Comment by vadeg** [comment]
@alan-czajkowski i understand your point and it make sense. From my opinion is that user should guess that `systemProperty` is not just a system property, but it can be system property with value if you separate them with `=`. Also, nothing stops someone to write 
```
<systemProperties>
  <systemProperty>property1=</systemProperty>
</systemProperties>
```
what may render like this
```
-Dproperty1= 
```
I think XML notations already has strict rules how to separate keys from values. Tag name is a key, tag value is a value. Instead of injecting one more `key-value` notation inside XML I would use existing one. 

I think the most closest Spring example you mentioned is an example with map because it also has a key and value. 
```
<property name = "addressMap">
         <map>
            <entry key = "1" value = "INDIA"/>
            <entry key = "2" value = "Pakistan"/>
            <entry key = "3" value = "USA"/>
            <entry key = "4" value = "USA"/>
         </map>
      </property>
``` 
One more option can be like this:
```
<systemProperties>
  <systemProperty>
    <key>propertyWithNoValue</key>
  </systemProperty>
  <systemProperty>
    <key>propertyWithValue</key>
    <value>value</value>
  </systemProperty>
</systemProperties>
```
`value` is an optional tag. If it does not exist that mean property has no value.

**Comment by alan-czajkowski** [comment]
as long as there's an elegant way to render both of these cases:
```
-DsomePropertyWithNoValue
```
and
```
-DsomePropertyWithAnEmptyValue=
```
then I'm happy

**Comment by snicoll** [comment]
Closing in favour of PR #9714
