### ISSUE TITLE
Replace calls to FileSystemUtils with NIO equivalents

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9720]
[SPR-15748](https://jira.spring.io/browse/SPR-15748) has deprecated `FileSystemUtils` so we now have lots of deprecation warnings

**Comment by jhoeller** [comment]
We can also discuss un-deprecating `FileSystemUtils` for the time being if Boot is heavily using it... The only thing I do not want to do is to evolve it any further, in particular not provide an NIO equivalent in core.

**Comment by snicoll** [comment]
As discussed with @jhoeller he's going to restore `FileSystemUtils` with updated NIO equivalent features.
