### ISSUE TITLE
Spring boot actuator does not handle InteractiveAuthenticationSuccessEvent events

### ISSUE THREAD

**Issue by adeptues** [spring-projects/spring-boot#9722]
An InteractiveAuthenticationSuccessEvent is issued by an AbstractAuthenticationProcessingFilter which is ignored by the actuator AuthenticationAuditListener due to the strict type check for AuthenticationSuccessEvent.

This didn't happen in previous versions of spring boot we are currently using 1.3.8

**Comment by wilkinsona** [comment]
See #4355 which introduced the stricter type check

**Comment by adeptues** [comment]
Application only sends  a single InteractiveAuthenticationSuccessEvent which is issued by the spring web AbstractAuthenticationProcessingFilter. So how do i get it to publish the stricter event type?

**Comment by wilkinsona** [comment]
@adeptues Sorry, perhaps I've created some confusion. I just wanted to reference #4355 is it's the issue where the change that you have noticed was made. I can't comment on what should be happening in your case or what change you possibility need to make as I know very little about what you're doing. Perhaps you can share a minimal sample project that illustrates the problem and we can take things from there?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
