### ISSUE TITLE
Relaxed binding in 2.0.0.x - PERSON_FIRST_NAME does not bind to propery: Person#firstName

### ISSUE THREAD

**Issue by dorongold** [spring-projects/spring-boot#9723]
Relaxed binding of properties does no longer work as [documented](http://docs.spring.io/spring-boot/docs/2.0.0.M2/reference/htmlsingle/#boot-features-external-config-relaxed-binding).

For example:
Having the following `@ConfigurationProperties` bean:
```java
@Component
@ConfigurationProperties(prefix = "person")
public class OwnerProperties {

    private String firstName;

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
}
```
If the application is given the following environment variable: `PERSON_FIRST_NAME=from env`
It does not bind to `firstName`.

This problem only happens in spring-boot versions 2.0.0.x
In version 1.5.4.RELEASE the same environment variable does bind to `firstName`.

**Comment by snicoll** [comment]
Duplicates #9025

The documentation is indeed outdated, the wiki [has a page on the binding changes in 2.0](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#environment-variables)

**Comment by dorongold** [comment]
Right. I know see in the wiki:

> The _ delimiter must not be used within a property name. i.e. database-platform must be written as DATABASEPLATFORM and not DATABASE_PLATFORM. 

This means the env variable should be PERSON_FIRSTNAME instead of PERSON_FIRST_NAME (which works in the latest spring boot 1.5.x)
