### ISSUE TITLE
additional-spring-configuration-metadata.json is not being merged when building with Gradle 4

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-boot#9732]
Set up the simplest possible app according to the documentation wrt generating spring configuration metadata along with `additional-spring-configuration-metadata.json` for those additional "hints" to be merged into the main metadata file. It does not seem to work.

https://github.com/dima767/additional-config-metadata-not-working

Try `./gradlew clean build` or `./gradlew clean bootRun`

This is Boot `1.5.4` and Gradle `4.0`

/cc @mmoayyed

**Comment by snicoll** [comment]
For the record, this project does work with Gradle 3.x as far as I can see (and we don't support Gradle 4 officially in the 1.5.x line). I wonder if that's a regression in Gradle 4. Perhaps @wilkinsona knows?

**Comment by dima767** [comment]
Ah, OK, let me try with Gradle 3
		

		
	





On Wed, Jul 12, 2017 at 11:49 AM -0400, "Stéphane Nicoll" <notifications@github.com> wrote:












For the record, this project does work with Gradle 3.x as far as I can see (and we don't support Gradle 4 officially in the 1.5.x line). I wonder if that's a regression in Gradle 4. Perhaps @wilkinsona knows?

**Comment by wilkinsona** [comment]
The problem's caused by Gradle changing the output location of classes in Gradle 4. The output location of resources has not changed which means that we fail to find the additional metadata file relative to the classes location.

In Gradle < 4 the layout is like this:

```
app/build/
├── classes
│   └── main
│       └── com
│           └── example
│               └── SomeClass.class
├── resources
│   └── main
│       └── META-INF
│           └── additional-spring-configuration-metadata.json
└── tmp
    └── compileJava
```

With Gradle 4 it now looks like this:

```
app/build/
├── classes
│   └── java
│       └── main
│           └── com
│               └── example
│                   └── SomeClass.class
├── resources
│   └── main
│       └── META-INF
│           └── additional-spring-configuration-metadata.json
└── tmp
    └── compileJava
```

Note the new `java` directory beneath `build/classes`

**Comment by dima767** [comment]
From Gradle `4.0.1` release notes:

```
In projects that use multiple JVM languages (Java and Scala, Groovy and other languages) in separate source directories (e.g., src/main/groovy and src/main/java), Gradle now uses separate output directories for each language.

To return to the old behavior, explicitly set the classes directory:

// Change the output directory for the main source set back to the old path
sourceSets.main.output.classesDir = new File(buildDir, "classes/main")
```

**Comment by mmoayyed** [comment]
Besides the workaround, is this something we can help to fix by the way? To not return to the old behavior and simply make this work with Gradle 4 as is? If so, what might be a good starting point to review and track changes?

**Comment by wilkinsona** [comment]
We can, and I think should, fix this in 1.5.x. There's a low-risk fix that can be applied: look for the resources folder one directory higher up if we don't find it where we're currently looking.

There are actually some other problems with the current situation, but they're more complex and harder to fix. I'll open a separate issue for those as they'll have to wait for 2.0.

**Comment by mmoayyed** [comment]
Great, thanks. I'll put together a pull request.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/9755 for the trickier problems.

@mmoayyed Thanks very much. Just in case you haven't already spotted where the fix needs to be made, it's in [`MetadataStore`](https://github.com/spring-projects/spring-boot/blob/v1.5.4.RELEASE/spring-boot-tools/spring-boot-configuration-processor/src/main/java/org/springframework/boot/configurationprocessor/MetadataStore.java#L117-L123).

**Comment by mmoayyed** [comment]
Managed to get this working and tested it. First draft at https://github.com/spring-projects/spring-boot/pull/9758
