### ISSUE TITLE
spring.data.mongodb.password get cleared after the first use

### ISSUE THREAD

**Issue by abtinzo** [spring-projects/spring-boot#9733]
I started using spring-boot framework with mongodb for a RESTful API and I came up with this problem that I have no idea how to solve or maybe a fix should be implemented.

So I'm setting spring.data.mongodb.password in my application.properties and I realized this is the same password (and other properties) that is used for embedded mongo client (for testing purposes) that is created when you start your spring-boot application. The problem is when I'm trying to get the credential and make a mongo client from these properties I realize that the password (from MongoProperties) is set to 0 and thus the authentication will be failed! This problem is coming from the clearPassword() method that is called after first embedded mongo instantiation.

I couldn't fine work around to stop this password clearing process without a code fix

**Comment by snicoll** [comment]
Why are you trying to create a `MongoClient` if the auto-configuration creates one for you? I assume you do so programmatically, right? Those properties are meant to be used by the auto-configuration, if you need to create your own infrastructure I'd advise to create your own keys for this as well. 

Having said that, I never quite understood why we were clearing the password but I have a feeling @dsyer might.

**Comment by dsyer** [comment]
The password is stored as a `char[]` so there's a chance that nulling it out will make it unreadable to bad guys who managed to obtain a heap dump of your process. It's kind of best practice to do that, but in this case it's quite likely that the password is stored as a `String` elsewhere (or else how did it get bound to `@ConfigurationProperties`?), so it's more of a gesture really than anything else.

**Comment by snicoll** [comment]
Agreed and I think that's removed on `master`. Still I don't really understand why @abtinzo creates their own `MongoClient` with the settings of the auto-configuration. Let's see what they have to say about that.

**Comment by abtinzo** [comment]
Thanks for the feedbacks @snicoll and @dsyer 
I'm using different mongo connections (but with the same credentials) and that's why I'm creating those MongoClients in the code. I was thinking, instead of creating another properties file I would use the mongo credentials already exists in application.properties (like username, password, database name and etc) but I faced that problem of nulling the password out after first instantiation!
I know I can create a totally different properties file for my custom mongo settings and etc. but as those properties would be redundant I thought having them all in one application.properties would be a good idea.

To give you some idea what I'm doing as an example:
`MongoDatabase db1 = mongoDB.getMongoConnection(properties.getHost(), properties.getDatabase(), properties.getPort());`
This is something I use for getting a database based on those MongoProperties stored on application.properties, and
`MongoDatabase db2 = mongoDB.getMongoConnection(ip, database,port);`
and this is another line of code for getting some other databases based on user defined properties (ip, database, port)!

**Comment by snicoll** [comment]
This issue is now outdated as we don't clear that password as of #8230
