### ISSUE TITLE
initInfoDefaultStart and initInfoDefaultStop not written

### ISSUE THREAD

**Issue by schrotti12** [spring-projects/spring-boot#9735]
We use the following statements in our main Gradle script but the values for default start and stop are not written into the jar file.
```
springBoot {
		
    // Set values for variable placeholders in the default launch script.
    // see: https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html
    embeddedLaunchScriptProperties =
        [
         initInfoDefaultStart: "3 5",
         initInfoDefaultStop: "0 1 2 6"
        ]
}
```

In the jar file the values are 

```
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
```

**Comment by wilkinsona** [comment]
It works for me with Spring Boot 1.5.4:

```
$ more build/libs/gh-9735-0.0.1-SNAPSHOT.jar
#!/bin/bash
#
#    .   ____          _            __ _ _
#   /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
#  ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
#   \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
#    '  |____| .__|_| |_|_| |_\__, | / / / /
#   =========|_|==============|___/=/_/_/_/
#   :: Spring Boot Startup Script ::
#

### BEGIN INIT INFO
# Provides:          spring-boot-application
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
…
```

If you'd like us to investigate further, please provide a small sample that reproduces the problem.

**Comment by schrotti12** [comment]
Thank you very much for the really fast response. At the moment we are using version "1.4.3.RELEASE". I tried to update the version but this will take some time. It seems, that the issue is already resolved with a more current version of SpringBoot. I forgot to check the version first, sorry. I'll try to use a more recent version of SpringBoot and ask again, if the issue still exists at that point.
Thank you!

**Comment by wilkinsona** [comment]
The support for configuring `initInfoDefaultStart` and `initInfoDefaultStop` is new in 1.5: https://github.com/spring-projects/spring-boot/pull/7902
