### ISSUE TITLE
Tomcat 8.5.15: bad jaxb performance in comparison with Tomcat 8.0.32

### ISSUE THREAD

**Issue by pfournea** [spring-projects/spring-boot#9750]
Hello,

We have a microservice transforming json input to xml output. Jaxb 2.0 is used to create the xml. After an upgrade from version 1.3.3 to 1.5.4 we noticed bad performance. `Jaxb2RootElementHttpMessageConverter` is used to transform the java bean to an xml. Jackson is used to transform the json input into a pojo. With a profiler we noticed that following call's were causing the bad performance: `JAXBContext.newInstance(<some class>)` & `SchemaFactory.newInstance(<some schema string>)`. Both are searching for classes on the classpath.

Could this be related to #9670 ?

The solution was forcing spring boot to use tomcat 8.0.32 instead of tomcat 8.5.15

Regards,

Peter

**Comment by wilkinsona** [comment]
I doubt that 9670 is related. It's concerned with Tomcat serving static resources. Tomcat's web resource caching has no effect on `JAXBContext.newInstance()` or `SchemaFactory.newInstance()` searching for classes on the classpath.

Given that things improve when you move to Tomcat 8.0.32, it's not clear why you think this a problem in Spring Boot itself. Perhaps you can share your profiling report or, even better, a small sample that can be used to reproduce the problem?

**Comment by pfournea** [comment]
I'm not suggesting that this is caused by spring boot. it's definitely a tomcat issue. But upgrading the spring boot version also triggers an new tomcat version ;-)
On important think I forgot to mention: bad performance only occurs when running as a fat jar. gradlew bootRun is fine!
[Snapshots.zip](https://github.com/spring-projects/spring-boot/files/1145351/Snapshots.zip)

In the zip file 2 yourkit snapshots. I'll make a sample application

**Comment by wilkinsona** [comment]
Thanks for the snapshots. Unfortunately, they don't tell me anything more than you've already explained. It would be useful to be able to see the calls made by SchemaFactory.newInstance(). I'm guessing that you may have had YourKit configured to filter out JDK classes?

I'll take a look at the sample if you can provide one, but it looks like this is going to need to be handled by the Tomcat team.

**Comment by pfournea** [comment]
Hi!

I've made an example. check [this repo](https://github.com/pfournea/springboot_tomcat). All information should be included in the readme file. 

Thanks in advance!

Regards

Peter

**Comment by wilkinsona** [comment]
Sorry, I was mistaken before. Tomcat's resource abstraction is involved here, however it's not the cache TTL that's the problem.

A [change](https://svn.apache.org/viewvc?view=revision&revision=1731080) was made in Tomcat to reduce the memory footprint. A side-effect of this is that every time the scheduled background processing occurs, each `AbstractArchiveResourceSet` nulls out the map of its jar file's entries. As a result, the first attempt to create a new `SchemaFactory` instance after background processing runs takes longer as Tomcat needs to re-read each jar file in the application. Your application has more dependencies than most (128 jars in `WEB-INF/lib`) so it also suffers more than most.

Unfortunately, there's nothing we can do about this in Spring Boot. I'd recommend posting on the Tomcat users list to discuss your problem or you could consider opening a performance regression bug. If you do the latter, I'd recommend providing the simplest possible application that reproduces the problem. Even if you keep all of your current sample's dependencies, the vast majority of the code is not needed.

**Comment by markt-asf** [comment]
I'd recommend joining the discussion on https://bz.apache.org/bugzilla/show_bug.cgi?id=60963

**Comment by markt-asf** [comment]
Should be fixed in https://svn.apache.org/viewvc?view=revision&revision=1802404

**Comment by wilkinsona** [comment]
Thank you, @markt-asf

**Comment by pfournea** [comment]
@wilkinsona  @markt-asf thank you both!

Regards,

Peter
