### ISSUE TITLE
Log4j 2.6.2 error with Spring boot 1.5.2

### ISSUE THREAD

**Issue by duggu9** [spring-projects/spring-boot#9753]
Hi,

I am developing a application on Spring boot 1.5.2 version. When I am trying to using Log4j 2.6.2, I am getting error as below. It is working fine with Log4j 2.7.

Can someone let me know what could be the reason and a fix for this issue. Thanks.

"Exception in thread "main" java.lang.AbstractMethodError: org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(Lorg/apache/logging/log4j/core/config/ConfigurationSource;)Lorg/apache/logging/log4j/core/config/Configuration;"

**Comment by wilkinsona** [comment]
You can't use Log4j 2.6 with Spring Boot 1.5. 1.5 requires Log4j 2.7
