### ISSUE TITLE
Actuator not working with latest Spring Boot - 2.0.0 M2

### ISSUE THREAD

**Issue by MazenAtaya** [spring-projects/spring-boot#9757]
Go to start.spring.io, create a new spring boot application with Web and Actuator dependencies and then run the application. You will not get any info when you hit localhost:8080/health or  localhost:8080/info.

IDE: Intellij
Build tool: Gradle or Maven
JDK: 1.8

I would be happy to provide more information.

**Comment by mbhave** [comment]
@MazenAtaya The default context-path for the actuator endpoints has been changed to `/application` in 2.0. Are you using the 2.0 snapshots? If so, you will be able to access the actuators at `localhost:8080/application/health`

**Comment by wilkinsona** [comment]
@MazenAtaya I think @mbhave as solved your problem. The default mapping [changed in M1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M1-Release-Notes#actuator-default-mapping) and the title of the issue suggests you're using M2

**Comment by MazenAtaya** [comment]
That makes sense. Thanks!
