### ISSUE TITLE
Better support to externalize application.properties for container deployed war

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#976]
Spring boot is great to generate jars with embedded tomcat but I find it very lacking for deploying to existing application servers (for example tomcat).

The problem is how to externalize the application.properties file: the only viable option I found is to start tomcat with an option similar to:
-Dspring.config.location=file:/usr/local/myapp/application.properties

But this works for just _one_ spring boot application: how may I have more than one if I use several spring boot apps on my container?

The usual way to externalize configs is to pass them to the webapp via JNDI, so, my ideal would be to define an environment of this kind:
  <Environment name="spring.properties.path" value="/my/app.properties" type="java.lang.String" />
automatically picked up by the webapp.

Is this possible to with the actual spring boot version or be implemented in the future?

**Comment by moradaniel** [comment]
You can also try this:

    public class Application extends SpringBootServletInitializer {

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder springApplicationBuilder) {
        return springApplicationBuilder
                .sources(Application.class)
                .properties(getProperties());
    }

    public static void main(String[] args) {

        SpringApplicationBuilder springApplicationBuilder = new SpringApplicationBuilder(Application.class)
                .sources(Application.class)
                .properties(getProperties())
                .run(args);
    }

      static Properties getProperties() {
         Properties props = new Properties();
         props.put("spring.config.location", "classpath:myapp1/");
         return props;
       }

**Comment by nickgrealy** [comment]
Hi @dsyer, sorry to post on a closed issue... I just wanted to know if it's possible to directly configure [an individual application.properties property value using JNDI](http://stackoverflow.com/questions/36998579/spring-boot-setting-application-properties-using-jndi)?

e.g. Use the following JNDI environment resource to configure `my.custom.property: foo` from `application.yml`
```
java:comp/env/my.custom.property = bar
```
Thanks!

**Comment by dsyer** [comment]
@nickgrealy I think that's how it works (it's documented in the Spring Boot user guide), but I'm not sure I understand the foo/bar bit. Did you try it and it doesn't work?

**Comment by devnewton** [comment]
Is there any working sample showing how to set application.properties values (not whole file) with external tomcat?
