### ISSUE TITLE
Could not able to catch ApplicationFailedEvent.

### ISSUE THREAD

**Issue by RahulK17** [spring-projects/spring-boot#9768]
I am using spring boot 1.5.2.RELEASE version.following is my code snippet.

```java
@Component
public class AppStatusEvent {
	private static final Logger LOGGER = LoggerFactory.getLogger(AppStatusEvent.class);

	@EventListener
	public void applicationStartedEvent(ApplicationReadyEvent readyEvent) {

		
		LOGGER.info("Application Ready Event****" + readyEvent.toString());

	}

	@EventListener
	public void applicationFailedEvent(ApplicationFailedEvent appFailed) {
		
		LOGGER.info("Application Failed Event****"+appFailed.getException());
	}

	@EventListener
	public void applicationStopedEvent(ContextClosedEvent closedcontext) {
		
		LOGGER.info("Application Closed Event****");

	}
}
```

By execute this code i can able to catch Application ready event and Context close event.
To catch failed event  i had removed one property key in application.properties file and started spring boot application. In console i am getting could not resolve place holder  error message.
before this error message I am not getting  failed event exception .

**Comment by wilkinsona** [comment]
I suspect this is an ordering problem, but it's impossible to say with the information you've provided. My guess is that `AppStatusEvent` isn't called with the `ApplicationFailedEvent` because it hasn't been created and registered by the time the failure occurs.

If you'd like us to spend some more time investigating, please take the time to provide a complete, minimal sample that reproduces the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
