### ISSUE TITLE
Server port not resolved properly

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#9770]
Using value `server.port=8081` in environment variables is not resolved properly. While you don't normally use dots in env variables, we use that format in SCDF with `ProcessBuilder`. This used to work with boot 1.5 but now breaks with 2.x snapshots. https://github.com/spring-cloud/spring-cloud-deployer-local/issues/62

It's easy to demonstrate this by checking what gets resolved to Spring `@Value` vs. Boot's `ServerProperties`.

```
@Value("${server.port}")
private String serverPort;

@Autowired
private ServerProperties serverProperties;

@Override
public void run(String... arg0) throws Exception {
	System.out.println("XXXX1 " + serverPort);
	System.out.println("XXXX2 " + serverProperties.getPort());
}
```
Passing in port using different ways. In first example default port `8080` is used and in other two correct port `8081` is used with tomcat.
```
env "server.port=8081" java -jar target/demo1-0.0.1-SNAPSHOT.jar
XXXX1 8081
XXXX2 null

env "SERVER_PORT=8081" java -jar target/demo1-0.0.1-SNAPSHOT.jar
XXXX1 8081
XXXX2 8081

java -jar target/demo1-0.0.1-SNAPSHOT.jar --server.port=8081
XXXX1 8081
XXXX2 8081
```

**Comment by wilkinsona** [comment]
This is working as designed. 2.0 doesn't support `.` separators in environment variables. The per-property source binding rules are [documented in table 24.2](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-relaxed-binding).

I would recommend that SCDF moves to a conventional format for environment variables, particularly as there's no guarantee that an OS will support the use of `.`.
