### ISSUE TITLE
Unable to Run Spring Boot 2.0.0.M2 using java 9

### ISSUE THREAD

**Issue by reflexdemon** [spring-projects/spring-boot#9787]
Spring Boot 2.0.0.M2 upgrade using java 9 not working.

Bug report

I was trying to compile and run spring boot 2.0.0.M2 and java 9 to test the application. Compilation passed and to my surprise Application also started. But it failed while testing. I have a miniature version of the problem put in a sample application and wish to link it with this issue. Need help in getting the application running.

The problem with example can be found on the below link.
Problem Statement: https://github.com/reflexdemon/spring-java9/issues/1

Sample Application to test: https://github.com/reflexdemon/spring-java9

**Comment by snicoll** [comment]
Your project does not work with Java8 either. The controller is in a separate package space than your `@SpringBootAppllication`.

Also, even though that sample works fine once fixed,  Java 9 is [not officially supported yet](https://github.com/spring-projects/spring-boot/labels/theme%3A%20java9)
