### ISSUE TITLE
mvn spring-boot:run ignores resource filtering

### ISSUE THREAD

**Issue by slavus** [spring-projects/spring-boot#980]
Hi,
When you run 

```
mvn spring-boot:run -P dev
```

it ignores maven resource filtering. I have application.properties file with following entry

```
spring.profiles.active = ${active.profiles}
```

In my pom.xml I have

```
    <profile>
      <id>dev</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <properties>
        <active.profiles>dev</active.profiles>
      </properties>
    </profile>
```

When i do classic mvn package evertyhing works as expected 
application.properties becomes:

```
spring.profiles.active = dev
```

When I run Application class from eclipse with profile set in m2e plugin, everything also works as expected. 

Any ideas why mvn spring-boot:run -P dev ignores resource filtering. ?

**Comment by hantsy** [comment]
I encountered this same problem here, in Spring Boot 1.3.0.M2. 

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <addResources>false</addResources>
                </configuration>
            </plugin>

I still got the `Mark invalid` error reported by resources plugin when run `mvn spring-boot:run` in command line.

**Comment by jfsoul** [comment]
Thought I'd share in case anyone else lands here like I did.  I got the suggested workaround involving the `folders` attribute of the plugin working.  

In my case I wanted to keep certain resources outside `src/main/resources`, allow hot reloading of said resources and apply filtering to the application.properties file under `src/main/resources`.  Specifically the following plugin config worked for me:

```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
            <addResources>false</addResources>
            <folders>
                <folder>src/main/public</folder>
            </folders>
        </configuration>
</plugin>
```

**Comment by gilfernandes** [comment]
I have used jfsoul's solution for this problem under Spring Boot 1.2.4.RELEASE and it worked fine.
Now I a moved to Spring 1.3.0.RELEASE and this stopped working: resource filtering no longer seems to work.
Has anyone experienced this problem in Spring 1.3.0.RELEASE ?

**Comment by snicoll** [comment]
Have you [read the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering) by any chance? Are you using the parent and the `${}` notation (instead of `@@`)?

**Comment by gilfernandes** [comment]
Cool, I have tried what you suggested and it works fine with Spring Boot 1.3.0.RELEASE . The entry in my application.properties file looks like this:

`spring.profiles.active=@profiles.active@`

Many thanks for pointing this out.

**Comment by jlheard** [comment]
Thanks the @foo@ helped me too.

**Comment by jjayaraman** [comment]
Thanks for the answer @foo@...... I was breaking my head.....

**Comment by VIIgit** [comment]
It was so hard to find the solution, @foo@ is working. Why is it, that spring boot is not just using ${foo} as described on so many maven examples?

**Comment by snicoll** [comment]
@VIIgit this issue is closed so it's not a great place for questions (that should go on stackoverflow anyway). There is a comment (https://github.com/spring-projects/spring-boot/issues/980#issuecomment-158873315) in this very issue that links to the release notes.
