### ISSUE TITLE
Nested map binds to null in @ConfigurationProperties

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#9801]
It's this line [here](https://github.com/spring-projects/spring-boot/blob/56169156211ee7037773e7ac04d39db93cb45ee8/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L303). Test case:
https://github.com/spring-projects/spring-boot-issues/tree/master/gh-9801.

The original problem we had in Spring Cloud Config was probably a poor design (we didn't need infinite depth in that case), but if you needed to configure a tree of arbitrary depth, this "feature" would prevent you from doing so (and give you a big head scratcher about why it was failing).

**Comment by mbhave** [comment]
Reopening because it broke other things.
