### ISSUE TITLE
/health endpoint security with custom AuthenticationToken object does not work.

### ISSUE THREAD

**Issue by MarosPataky** [spring-projects/spring-boot#9805]
I am working on a spring boot app with both spring-actuator and spring-security as dependencies (using spring-boot-starters and spring boot version 1.5.3.RELEASE).

I am trying to implement custom JWT authentication filter, which populates SecuirtyContext.

I would like to secure actuator endpoints by specifing `management.security.roles property`, while maintaining the feature of /health endpoint to display current status to unauthenticated user.

The issue is that when I set the `management.security.enabled=true`, the actuator security expects the user to be authenticated using `org.springframework.security.authentication.UsernamePasswordAuthenticationToken`, but I am using custom object based on` PreAuthenticatedAuthenticationToken`.

Is there any way to make it work with custom authentication filter? The only solution I could come up with is to configure http securit on /health endpoint, but that prevents unauthenticated user to access it.

If required, I can prepare a sample app demonstrating the issue later on.

**Comment by mbhave** [comment]
@MarosPataky It would be great if you could provide a small sample that reproduces the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
