### ISSUE TITLE
spring-boot-features.adoc has a non-working example

### ISSUE THREAD

**Issue by utsman** [spring-projects/spring-boot#9820]
In the spring-boot-features.adoc documentation the 27.1.11 CORS support section has a demo code that couldn't compile.

```
public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurer() {
```

I replaced WebMvcConfigurer to WebMvcConfigurerAdapter

```
public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
```
and it worked.
I submit a PR to fix it.

**Comment by wilkinsona** [comment]
This will compile successfully. `WebMvcConfigurer` uses Java 8's default methods in Spring Framework 5. The adapter is no longer needed and, therefore, no longer exists.

The 1.5 docs continue to use the adapter: http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#boot-features-cors
