### ISSUE TITLE
Upgrade to Spring Data Ingalls SR5-1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9834]

**Comment by wilkinsona** [comment]
False alarm. The release isn't in Central yet.

**Comment by wilkinsona** [comment]
The SR5 bom contains dependency management for a snapshot which breaks Boot's release build. We  need to upgrade to SR6 now instead.

**Comment by snicoll** [comment]
Actually, only the bom was busted so @olivergierke released `SR5-1`.
