### ISSUE TITLE
CLI classes are not @ComponentScannable

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#984]
Spring only scans  .class files and we don't have them available (unless you "spring jar" them up), so you can't `@ComponentScan` a class that is compiled during "spring run" or "spring test". It's not so much of a problem for "spring run" because all the compiled classes are considered as sources for the `SpringApplication`, but for "spring test" it's a pain because you have to manually glue them all together (e.g. with an `@Import`).

**Comment by wilkinsona** [comment]
We do not intend to make any enhancements to the CLI
