### ISSUE TITLE
Move Jolokia out of the endpoint infrastructure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9843]
The current Jolokia MVC endpoint is not really an endpoint in Actuator 1.x and it's even less one with the extended design in Actuator 2.x

In the end, our support is about exposing a Servlet. We already do that for the H2 console and we should align our support for Jolokia.

It has several impacts:

* The configuration should move from `endpoints.jolokia.*` to `management.jolokia.*` to make it clear that it's no longer an endpoint
* `endpoints.disabled=true` will no longer have an effect
* For consistency, it should be made available at `/application/jolokia` or whatever the context path is configured to
* We need to register that in the context that the actuator uses so that it ends up on the right context if `management.port` is set

**Comment by joshiste** [comment]
Will the servlet be running on the `management.port` (and the `managment.context.path`)?

**Comment by wilkinsona** [comment]
@joshiste Yes, it will. Are you using our Jolokia support in Spring Boot Admin?

**Comment by joshiste** [comment]
yep I do :)
