### ISSUE TITLE
Auto-configure Spring Session's reactive support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9850]
Here's a first pass at the basics: https://github.com/wilkinsona/spring-boot/tree/gh-9850

**Comment by wilkinsona** [comment]
This looks unlikely to make M5. Spring Session Data MongoDB is the only repository with reactive support at the moment (AFAIK) and it's lacking some configuration options. I've opened https://github.com/spring-projects/spring-session-data-mongodb/issues/11.

**Comment by gregturn** [comment]
Spring Session MongoDB has resolved your request via https://github.com/spring-projects/spring-session-data-mongodb/commit/ed655da8284e48abb6987770d7f69ea29f7edead

**Comment by vpavic** [comment]
@wilkinsona Reactive Redis support will be available with Spring Session 2.0.0.M5.
