### ISSUE TITLE
Move spring-boot web.client package to spring-web

### ISSUE THREAD

**Issue by jmcshane** [spring-projects/spring-boot#9860]
The three classes in this package have uses outside of just spring boot projects. The customizer interface, the builder, and the template handler all have no dependencies on other boot packages, and would be a good addition to the spring-web project itself. Then, the auto-configuration would remain within the spring-boot project to provide the automatic customization of the `RestTemplate`.

Would there be any resistance to this move? Is there a specific reason that these classes are present in the spring-boot project rather than spring-web?

**Comment by wilkinsona** [comment]
>  all have no dependencies on other boot packages

That applies to several other packages in `spring-boot`. We obviously have to draw the line somewhere between what goes in Spring Framework and what goes in Spring Boot. It's obviously subjective but I, and I believe the rest of the Boot team, feel we've got that right at the moment.

> Would there be any resistance to this move? Is there a specific reason that these classes are present in the spring-boot project rather than spring-web?

Yes, I think there would. The three classes that you mention all feel like Spring Boot to me. They take a more opinionated view of `RestTemplate` while, thanks to the customiser, allowing those opinions to be overridden quite easily. Even if we wanted the code to move, there's no guarantee that the Framework team would agree, particularly not this late in the 5.0 release cycle.

If you want to use those classes outside of a Spring Boot application, then I would recommend using the `spring-boot` module as a library.
