### ISSUE TITLE
Clarify descriptions of type and value attributes on ConditionalOn(Missing)Bean

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9863]
The descriptions currently say "The condition matches when any of the classes specified is contained in the ApplicationContext" or "The condition matches when each class specified is missing in the ApplicationContext". The classes aren't contained or missing, it's beans that are instances of those classes that are contained or missing.

**Comment by snicoll** [comment]
Sorry for the noise, I made a typo in the issue number

**Comment by philwebb** [comment]
Closing in favor of PR #14681
