### ISSUE TITLE
spring boot loader JarURLConnection getLastModified always return 0

### ISSUE THREAD

**Issue by flym** [spring-projects/spring-boot#9867]
When I use spring boot war (with tomcat embed) run, when new war deploy(which jsp changed), but tomcat not generate new jsp.java or jsp.class.

as the issue https://bz.apache.org/bugzilla/show_bug.cgi?id=61125
said,it use `url.getLastModified` to judge.

but in spring boot war, it finally use `JarURLConnection.getLastModified` method to get the new modified time. i debug the program find it always return 0.

i open a new project, use the code bellow 

```
URL url = new URL("jar:file:d:/xx.war!/WEB-INF/views/main.jsp");
long x = url.openConnection().getLastModified();
```

it return right time. 
i think it should use the jarEntry.getLastModifiedTime(or getTime).

spring boot loader version: 1.5.3.RELEASE (i find 1.5.5 the same code)

**Comment by wilkinsona** [comment]
This is the same problem as #9484, but for a different property

**Comment by YashchenkoN** [comment]
I'd like to contribute this issue

**Comment by wilkinsona** [comment]
Duplicate of #9893
