### ISSUE TITLE
Would be great to add an example of custom implementation for Mongo

### ISSUE THREAD

**Issue by TehBakker** [spring-projects/spring-boot#9868]
Enhancement

Was reading through Springboot MongoDb documentation and thought that for 7.6.1. Adding custom behavior to single repositories it would be great to actually give an example of custom implemention instead of "    // Your custom implementation " in the code example.

Regards

**Comment by snicoll** [comment]
You were reading the documentation of Spring Data. Their issue tracker is [here](https://jira.spring.io/browse/DATAMONGO)

**Comment by TehBakker** [comment]
Thanks, sorry for the hassle.
