### ISSUE TITLE
Consider providing separate `@ConditionalOn…` annotations that reference Class that can only be used on types

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9870]
We learned some lessons during the course of 1.x about attributes on some of our `@ConditionalOn…` annotations where we offer a `Class` attribute that's only safe for use when the annotation is on a class (rather than a `@Bean` method). Going a step further than warning people in the javadoc, we could provide separate annotations so that an annotation with a `Class` attribute can only be used on a type.

Something like `@ConditionalOnClass(com.example.Foo.class)` and `@ConditionalOnClassNamed("com.example.Foo")`

**Comment by kingbbode** [comment]
i support this.

```java
@Target({ ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnClassCondition.class)
public @interface ConditionalOnClass {

	Class<?>[] value() default {};

	String[] name() default {};

}
```

```
@Target({ ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnClassCondition.class)
public @interface ConditionalOnClassNamed{

	String[] name() default {};

}
```

**Comment by wilkinsona** [comment]
We've decided this will cause too much pain for the gain that it'll bring.
