### ISSUE TITLE
DependencyManagementPluginAction in Gradle Spring Plugin 

### ISSUE THREAD

**Issue by instilled** [spring-projects/spring-boot#9876]
Hi, 

Applying the Spring Boot Gradle plugin configures the DependencyManagementPlugin to import the BOM matching the plugin version by default, see  [DependencyManagementPluginAction.java#L36](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/DependencyManagementPluginAction.java#L36).
Usually this is just fine. But for some cases, e.g. if one wants to apply the latest (possibly non-released) version of the plugin but stick to an official Spring Boot release, automatically configuring the DependencyManagementPlugin may lead to issues when resolving dependencies.

Providing an option in Spring Boot's Gradle plugin to disable autoconfiguration of the DependencyManagementPlugin solves the problem. 

Do you think this is a feature that could be added to the current/a future release cycle?

Cheers, 
Fabio

PS: Kudos for the improved Gradle plugin. It really solves many of the pain points of previus versions.

**Comment by wilkinsona** [comment]
It's an interesting suggestion, but we don't want to encourage/support using one version of Spring Boot's Gradle plugin with a different version of Spring Boot. The two are maintained, versioned, and released together as they are intended to be used together.
