### ISSUE TITLE
Reproducible archives support in spring-boot 1.5.x

### ISSUE THREAD

**Issue by bfg** [spring-projects/spring-boot#9879]
Commit d015714 introduced reproducible archives support for gradle spring-boot plugin. Gradle supports creation of reproducible archives [since v3.4](https://docs.gradle.org/3.4/release-notes.html#initial-support-for-reproducible-archives).

Sadly, this extension is only available in `master` and `v2.0.0.M1`, but everybody could benefit from it in `v1.5.x` as well - `start.spring.io` creates sample project with gradle `v3.5.1`.

I've tried to apply that patch on 1.5.x just to realize that spring-boot plugin has been rewritten - would it be difficult to implement such feature on `1.5.x` version of plugin?

References:
* https://docs.gradle.org/3.4/release-notes.html#initial-support-for-reproducible-archives
* https://docs.gradle.org/3.5.1/userguide/working_with_files.html#sec:reproducible_archives

**Comment by wilkinsona** [comment]
> would it be difficult to implement such feature on 1.5.x version of plugin?

Yes. Unfortunately it would be prohibitively difficult, not least because the API is new in Gradle 3.4 and Spring Boot 1.5 supports Gradle 2.x.

Sorry, but you'll have to wait for Boot 2.0 for this functionality.

**Comment by bfg** [comment]
Thank you very much for your answer :+1:
