### ISSUE TITLE
Publish the Spring Boot Gradle Plugin

### ISSUE THREAD

**Issue by thetric** [spring-projects/spring-boot#9881]
The new Spring Boot version 1.5.6 has been [published](https://spring.io/blog/2017/07/27/spring-boot-1-5-6-available-now), but the [Gradle plugin](https://plugins.gradle.org/plugin/org.springframework.boot) hasn't been updated. Could you upload a new plugin version to plugins.gradle.org, please?

Edit: I'm using the new plugin mechanism:

```gradle
plugins {
  id "org.springframework.boot" version "1.5.6.RELEASE"
}
```

**Comment by wilkinsona** [comment]
The Gradle team are working on it. Unfortunately it's out of our hands.

**Comment by wilkinsona** [comment]
I've updated the [blog post](https://spring.io/blog/2017/07/27/spring-boot-1-5-6-available-now) so that people know what's going on.
