### ISSUE TITLE
Port configuration not picked up in custom namespaced management server properties

### ISSUE THREAD

**Issue by punycode** [spring-projects/spring-boot#9883]
When using custom configuration property class instead of `ManagementServerProperties` and using a custom namespace, the configuration for a separate management port is not picked up, serving the endpoints at the main server port instead.

**Comment by snicoll** [comment]
That's expected, just like if you decide to create a `my.server.port` it won't have any effect on the port that the embedded server uses for the app. Can we take a step back and discuss why you are doing this?

**Comment by punycode** [comment]
For a customer project, we are writing some custom starters, based on the existing ones. Since we wanted to establish an identity for this custom starter platform, we are aggregating a lot of configuration under own namespaces, including our extensions to management features.

From the actual Spring Boot source code (https://github.com/spring-projects/spring-boot/blob/v1.5.6.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointWebMvcAutoConfiguration.java#L368) we understood, that it actually is intended to work, since the if block there would only ever be regarded for custom property classes where port is set in a different way.

**Comment by snicoll** [comment]
I fail to see what makes you believe it would work. That line you referenced is just below something that reads `management.port`. 

I don't think this is reasonable to expect core Spring Boot features to be relocated to custom namespaces. I'd like to see what the rest of the team thinks.

**Comment by punycode** [comment]
The if block will only ever be entered for a custom property class and `management.port` being unset and tries to get the port from exactly this property class. 

```java
Integer managementPort = getPortProperty(environment, "management.");
if (managementPort == null && hasCustomBeanDefinition(beanFactory, ManagementServerProperties.class, ManagementServerPropertiesAutoConfiguration.class)) {
    managementPort = getTemporaryBean(beanFactory, ManagementServerProperties.class).getPort();
}
```

It seems that at this point in the Spring Boot container initialisation beans annotated with `@ConfigurationProperties` are not properly processed by whatever is doing the Spring Boot relaxed property binding.

**Comment by wilkinsona** [comment]
@punycode It sounds to me like you have misinterpreted the intention of that logic. It was [added](https://github.com/spring-projects/spring-boot/commit/b2fcd77d935125a77957a875beb5962d898df73d) to remove the need to create a temporary context when determining the correct port.

If you want to use a different property to configure `management.port` then I think there may be better ways to do it. For example, you could explore adding a property source to the environment that aliases your custom property to the `management.port` property.
