### ISSUE TITLE
Prevent the management context path from being set to / unless a separate management port is configured

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9898]

**Comment by philwebb** [comment]
I think we should do this on `ManagementProperties` as well. I think the current fix wont stop Jersey etc.

**Comment by wilkinsona** [comment]
The fix was implemented before the Actuator endpoint rewrite was merged. The check is now done [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/ManagementContextAutoConfiguration.java#L97-L104) and should take effect for MVC, WebFlux and Jersey.

**Comment by wilkinsona** [comment]
We've decided against do this so we're going to revert the change entirely.
