### ISSUE TITLE
Remote restart in devtools disregards application.properties and other resources

### ISSUE THREAD

**Issue by haizz** [spring-projects/spring-boot#9900]
I've encountered this with basic Spring Boot (2.0.0.M3) app (in Kotlin):

```kotlin
package devtoolstest

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class Application {
}

fun main(args: Array<String>) {
    val url = Application::class.java.getResource("/application.properties")
    println("!!!!!!!!!!!! $url")
    SpringApplication.run(Application::class.java, *args)
}
```

1. Build the jar with `./gradlew bootJar`.
2. Run it with `java -jar ...` command.
3. `getResource()` returns valid URI.
3. Trigger restart with RemoteSpringApplication.
4. `getResource()` returns null and all properties from `application.properties` (like `server.port`) revert to defaults (like making Jetty server start on the wrong port).

It works though in cases when RemoteSpringApplication reports `Remote server has changed, triggering LiveReload`, but I'm not sure on which conditions does that happen.

**Comment by wilkinsona** [comment]
@haizz What are you doing in step 4 to trigger the restart? I also wonder if this is specific to Kotlin. Could you try the same in Java please?

**Comment by haizz** [comment]
Here's my Kotlin project, it's easy to build it with gradle: https://github.com/haizz/spring-devtoolstest
Will try with Java later.

Step 4 is basically doing trivial modification in Controller class and then doing `./gradlew build` while RemoteSpringApplication is running.

Gradle task to start RemoteSpringApplication:

```groovy
task springRemoteRun(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    main = "org.springframework.boot.devtools.RemoteSpringApplication"
    args "http://localhost:8001"
}
```

The Jar is built with spring-boot-gradle-plugin, maybe it has something to do with it.

**Comment by haizz** [comment]
Having the same problem with pure Java project: https://github.com/haizz/devtoolstest-java

**Comment by philwebb** [comment]
@haizz Can you provide the exact steps needed to replicate this. Please also tell us some more about your environment, what OS? what IDE? etc.

**Comment by haizz** [comment]
@philwebb Environment is just command line + Gradle, no IDE.
```
~/workspace/devtoolstest-java$ ./gradlew --version

------------------------------------------------------------
Gradle 3.5-rc-2
------------------------------------------------------------

Build time:   2017-03-27 15:56:23 UTC
Revision:     ec63970cd167993d3dcda346a1d00a286a23b1c9

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.12.5 x86_64
```

How to reproduce:

1. Checkout the test project (https://github.com/haizz/devtoolstest-java), cd into root project directory.
2. Build the project: `./gradlew build`
3. Start the app and leave it running: `java -jar ./build/libs/devtoolstest-java-1.0-SNAPSHOT.jar`
4. Start RemoteSpringApplication In the 2nd terminal window: `./gradlew springRemoteRun`
5. Modify code in `src/main/java/devtoolstest/Application.java`
6. Rebuild the project In the 3rd terminal window: `./gradlew build`
7. See the problem in the output of step 3 after restart: null for getResource(), Jetty on port 8080 while the application.properties has `server.port=8001`.

**Comment by wilkinsona** [comment]
The problem occurs due to a combination of these two steps:

> 3. Start the app and leave it running: java -jar ./build/libs/devtoolstest-java-1.0-SNAPSHOT.jar
> 6. Rebuild the project In the 3rd terminal window: ./gradlew build

In step 3, you're running the jar straight from where Gradle builds it. In step 6 you're causing Gradle to rebuild this jar, ripping it out from underneath the running JVM and replacing it. All bets are off at this point.

There are two ways you can avoid the problem:

1. In step 3 you could copy the built jar from build/libs and run the copy
2. In step 6 you could run `compileJava` rather than `build` to avoid the jar being rewritten
