### ISSUE TITLE
Simplify Actuator's hypermedia

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9901]
We just want a single endpoint that provides HAL links to all the enabled endpoints

**Comment by mbhave** [comment]
[This one](https://github.com/spring-projects/spring-boot/blob/d8f827d2249696a346bc11adf4ccacf61eeb888d/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cloudfoundry/CloudFoundryDiscoveryMvcEndpoint.java#L50-L50) does something similar.
