### ISSUE TITLE
Remove regressions test for older Mockito versions

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9904]
Mocikto 2 is the minimum for Spring Boot 2 so we should remove the regressions tests for older Mockito versions. Besides, Mockito only works with Java 9 as of Mockito 2.5.

**Comment by TimvdLippe** [comment]
> Mockito only works with Java 9 as of Mockito 2.5

Mockito 2 should support all the way down to Java 6. Mockito 3 will target 8 and up. Could you clarify where you found this information?

**Comment by snicoll** [comment]
Sorry that sentence was misleading. We have tests using Java9 and they didn't pass up to Mockito 2.4. Then they started passing as of 2.5. It doesn't mean anything for Java 6, 7 and 8.

**Comment by TimvdLippe** [comment]
Oh yes that is correct. We bumped ByteBuddy which is now also Java 9 compatible. Glad that got fixed! :tada:
