### ISSUE TITLE
Spring Boot 2 and OAuth2/JWT configuration

### ISSUE THREAD

**Issue by Artgit** [spring-projects/spring-boot#9906]
Could you please take a look into my Spring Boot 2 and OAuth2/JWT configuration https://stackoverflow.com/questions/45391264/spring-boot-2-and-oauth2-jwt-configuration

Right now I unable to port my application to Spring Boot 2 because of this issue.

**Comment by philwebb** [comment]
Let's leave this one on stackoverflow rather than cross-posting here. We're expecting to overhaul security before we release 2.0 final so you might be as well to wait until that has happened before trying to migrate your application.

**Comment by Artgit** [comment]
sure, what is ~ ETA of Spring Boot 2.0 final ?
