### ISSUE TITLE
Issue with @EnableResourceServer and injection of context

### ISSUE THREAD

**Issue by stephanecot** [spring-projects/spring-boot#9908]
Bug report

I have upgraded to the new Spring boot 1.5.6 ( with Spring Cloud Dalston.SR2).
Before, in Spring Boot 1.5.4, I had this bean in my @EnableResourceServer Config

    @Bean
    public RequestInterceptor oauth2FeignRequestInterceptor(OAuth2ClientContext oauth2ClientContext, OAuth2ProtectedResourceDetails resource){
        return new OAuth2FeignRequestInterceptor(oauth2ClientContext, resource);
    }

With Spring boot 1.5.6, I had an error in injection of Oauth2ClientContext and OAuth2ProtectedResourceDetails ==> no beans found for injection !
In my config I have:

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          xxxxx
          -----END PUBLIC KEY-----

Something has changed in this new version or is there a bug somewhere ?

**Comment by wilkinsona** [comment]
You need to provide a client ID.Previously some beans were auto-configured without one but, we believe, they were useless. This was due to a bug in the condition. Please see #9435 for details.

**Comment by stephanecot** [comment]
Ok a clientId, but which one ?
How, it's working if I had several clientId on my app ?
I get my token from a ui server with an @EnableOauth2SSo on my case.

**Comment by wilkinsona** [comment]
Whichever one you want to be set on the auto-configured resource details. You can specify it using `security.oauth2.client.client-id`
