### ISSUE TITLE
Spring multipart size validation failed to validate -1

### ISSUE THREAD

**Issue by XPLOT1ON** [spring-projects/spring-boot#9909]
The regex validation in `appication.properties` for `spring.http.multipart.max-file-size` and `spring.http.multipart.max-request-size` is incorrect. It did not cover the case where the value can be **-1**. The properties file is giving me invalid value (At least in Intellij).

I am using SpringBoot 1.5.4-RELEASE and IntelliJ IDEA Ultimate 2017.2.

Workaround, just ignore the validation and run program.

**Comment by snicoll** [comment]
That regex validation is not in Spring Boot. Please report that issue in the [IntelliJ IDEA tracker](https://youtrack.jetbrains.com/issues)
