### ISSUE TITLE
Executable jar results in error when using relative imports in XSD

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#9917]
While upgrading an application to the latest version of Spring Boot (1.5.6.RELEASE), I got an error when running the application as the executable jar. After analysis, it seems like there is an issue introduced in the spring-boot-maven-plugin from 1.4.2.RELEASE on.

The application is hosting a webservice, and as such creates an `org.springframework.xml.xsd.commons.CommonsXsdSchemaCollection`, with a `ClasspathResources` pointing to an xsd. This XSD has an import of another XSD using a relative path.

I have attached a sample application that reproduces the problem. The only change needed to (not) show the issue is change the `spring-boot-maven-plugin` to `1.4.1.RELEASE` (working) or a new version (not working).

Please be aware that the issue doesn't occur when running from an IDE/spring-boot:run; it only happens when running an executable JAR.

I looked in the `JarURLConnection` commit history for the 1.4.2.RELEASE, but I couldn't find anything obvious standing out that could cause this.

[relative_import.zip](https://github.com/spring-projects/spring-boot/files/1187716/relative_import.zip)

**Comment by wilkinsona** [comment]
I believe this duplicates #7581. See [this comment](https://github.com/spring-projects/spring-boot/issues/7581#issuecomment-265515992) for an explanation of the change.

Can you please try with a shaded jar (rather than a Spring Boot fat jar) and see if it fails then as well?

**Comment by hoeckxer** [comment]
Thanks for the reply.

I modified the pom of the sample application as per the comment you referred to, and updated the application to directly create the CommonsXsdSchemaCollection:

`public class App
{
	public static void main( String[] args )
	{
//		SpringApplication.run(App.class, args);
		new App().schemaCollection();
		System.out.println("Done");
	}

	@Bean
	public CommonsXsdSchemaCollection schemaCollection() {
		CommonsXsdSchemaCollection schemaCollection = new CommonsXsdSchemaCollection(new ClassPathResource("xsd/folderA/a.xsd"));
		schemaCollection.setUriResolver(new DefaultURIResolver());
		schemaCollection.setInline(true);
		return schemaCollection;
	}
}`

When I run this application after packaging it as a jar, it prints Done without throwing an exception. I would've expected it to throw an exception?

**Comment by wilkinsona** [comment]
> and updated the application to directly create the CommonsXsdSchemaCollection

Why did you make this update? To be a useful comparison the only change should be in the jar's packaging.

**Comment by hoeckxer** [comment]
I initially tried that, but that resulted in an error from the packaged jar:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [relative_import.App]; nested exception is java.lang.IllegalArgumentException: No auto configuration cl
asses found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:545) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at relative_import.App.main(App.java:15) [sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:277) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:153) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:95) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:537) ~[sample-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        ... 14 common frames omitted
```

Hence I figured I'd give it a try the way I did, but apparantly that wasn't what you were after. The pom file after editing (the spring-boot-maven-plugin is commented out, or does that need to be enabled as well?):

```
    <build>
        <plugins>
            <!--<plugin>-->
                <!--<groupId>org.springframework.boot</groupId>-->
                <!--<artifactId>spring-boot-maven-plugin</artifactId>-->
                <!--&lt;!&ndash; It still works in this version &ndash;&gt;-->
                <!--<version>1.4.2.RELEASE</version>-->
                <!--&lt;!&ndash;<version>1.5.2.RELEASE</version>&ndash;&gt;-->
                <!--<executions>-->
                    <!--<execution>-->
                        <!--<goals>-->
                            <!--<goal>repackage</goal>-->
                        <!--</goals>-->
                    <!--</execution>-->
                <!--</executions>-->
            <!--</plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <configuration>
                    <transformers>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <mainClass>relative_import.App</mainClass>
                        </transformer>
                    </transformers>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by philwebb** [comment]
@hoeckxer You should remove the `spring-boot-maven` plugin and just use the shade plugin. If you use `spring-boot-starter-parent` then you can inherit all the required configuration. If you're not using our parent, take a look [at this section of the POM](https://github.com/spring-projects/spring-boot/blob/37bef961ea52e03b48e08c9bc865acb69400621d/spring-boot-starters/spring-boot-starter-parent/pom.xml#L171-L221) for the configuration.

**Comment by hoeckxer** [comment]
@philwebb thanks for the reply. In the sample provided, I was indeed not using the spring-boot-starter-parent (client site mandates a parent pom to make it work in this environment), so I missed the pluginManagement in the spring-boot-starter-parent. Took Andy's referenced comment and only put in the shade-plugin, which resulted in the error provided earlier.

Using the spring-boot-starter-parent, it is indeed now working by using the following pom (snippet)

  ```
  <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.2.RELEASE</version>
    </parent>

    <groupId>relative_import</groupId>
    <artifactId>sample</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>sample</name>

    <properties>
        <start-class>relative_import.App</start-class>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

I do wonder what we'll be missing when using the shade plugin, as I'm sure the spring boot loader provides additional functionality besides the repackaging (after all, why bother creating it all if it doesn't do more than the shade plugin)?

**Comment by wilkinsona** [comment]
Thank you, @hoeckxer.

> Using the spring-boot-starter-parent, it is indeed now working by using the following pom (snippet)

In that case, you've found a bug. A fat jar and a shaded jar should work in the same way. Can you please share your updated sample and we'll take a look?

**Comment by hoeckxer** [comment]
@wilkinsona I've attached 2 sample projects:
* [relative_import_with_parent.zip](https://github.com/spring-projects/spring-boot/files/1190111/relative_import_with_parent.zip), which contains a pom that makes use of the spring-boot-starter-parent. This sample works when I package it as a jar and then execute it
* [relative_import_without_parent.zip](https://github.com/spring-projects/spring-boot/files/1190115/relative_import_without_parent.zip), which contains a pom that doesn't use the spring-boot-starter-parent, but instead defines the shade plugin itself.

I noticed that in the spring-boot-starter-parent, additional configuration is done for the shade plugin:
```
					<executions>
						<execution>
							<phase>package</phase>
							<goals>
								<goal>shade</goal>
							</goals>
							<configuration>
								<transformers>
									<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
										<resource>META-INF/spring.handlers</resource>
									</transformer>
									<transformer implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
										<resource>META-INF/spring.factories</resource>
									</transformer>
									<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
										<resource>META-INF/spring.schemas</resource>
									</transformer>
									<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
									<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
										<mainClass>${start-class}</mainClass>
									</transformer>
								</transformers>
							</configuration>
						</execution>
					</executions>
```

I expect this is required to make it a properly executable jar.

Please also note the the last question in my previous comment was probably overlooked, but for which an answer would still be great:

> I do wonder what we'll be missing when using the shade plugin, as I'm sure the spring boot loader provides additional functionality besides the repackaging (after all, why bother creating it all if it doesn't do more than the shade plugin)?

**Comment by wilkinsona** [comment]
The benefits of nested jars over the Shade plugin's approach are [described in the documentation](http://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#executable-jar-nested-jars):

> A shaded jar simply packages all classes, from all jars, into a single 'uber jar'. The problem with shaded jars is that it becomes hard to see which libraries you are actually using in your application. It can also be problematic if the same filename is used (but with different content) in multiple jars. Spring Boot takes a different approach and allows you to actually nest jars directly.

You've seen some of these problems here. For example `PropertiesMergingResourceTransformer` is required with the Shade plugin to combine all the `spring.factories` files into one.

**Comment by hoeckxer** [comment]
thanks @wilkinsona, I overlooked that part in the documentation!
