### ISSUE TITLE
The spring-boot 2.0.0.M3 app runs no more in a kotlin maven based project (kapt + @ConfigurationProperties)

### ISSUE THREAD

**Issue by jtonic** [spring-projects/spring-boot#9933]
Hi,

Recently I updated my maven kotlin spring-boot project to use the latest milestone version 2.0.0.M3
and noticed that kapt goal of the kotlin plugin works no more. Kapt goal is for APT. And it seems to be smth related to spring boot and APT.

**_@ConfigurationProperties(prefix = "client")_**
class ClientProperties(var name: String? = null)

@SpringBootApplication
**_@EnableConfigurationProperties(ServerPropertiesJava::class, ClientProperties::class)_**
class SpringBootKtApplication {...}

**_application.yaml_**
client:
  name: My client

**_pom.xml_**
[https://github.com/jtonic/springbootkt/blob/master/pom.xml](url)
Look especially for the kotlin plugin configuration kapt execution (spring boot configuration processor)
 
**_Test_**
[https://github.com/jtonic/springbootkt/blob/master/src/test/kotlin/jtonic/tmp/springbootkt/SpringBootKtApplicationTestsJUnit.kt](url)

**_The exception (excerpt)_**
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'init' defined in jtonic.tmp.springbootkt.SpringBootKtApplication: Unsatisfied dependency expressed through method 'init' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'client-jtonic.tmp.springbootkt.ClientProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: **_## Failed to instantiate [jtonic.tmp.springbootkt.ClientProperties]: No corresponding Kotlin constructor found_**

The application is on github: [https://github.com/jtonic/springbootkt](url)

When I downgraded the springboot version to the previous one the project ran smoothly.

**Comment by wilkinsona** [comment]
I don't think this has anything to do with Spring Boot. The same problem occurs with M2 if I override the Spring Framework version to RC3 (the same version as is used in Spring Boot M3). If you'd like to pursue these, please open a [Spring Framework JIRA ticket](https://jira.spring.io/browse/SPR). A couple of things to consider before you do that:

1. You're using Kotlin 1.2 M1. I'm not sure that Spring Framework support 1.2 yet; RC3 was built against 1.1.x.
2. Your sample is rather complicated (many dependencies, use of Spring Cloud etc) and I had to make a few changes to get it to build (the pom was broken). Please consider reducing it down to the minimum that's required to reproduce the problem.
