### ISSUE TITLE
@EnableWebMvc and Jackson properties

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#9941]
In application.properties
spring.jackson.property-naming-strategy=SNAKE_CASE

Everething works perfectly. But after I add @EnableWebMvc Jackson use camel case

**Comment by wilkinsona** [comment]
As [described in the documentation](http://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#howto-customize-the-responsebody-rendering), when you use `@EnableWebMvc` you are indicating that you will take complete control over Spring MVC's configuration. That includes configuring how it uses Jackson to render responses.

**Comment by raderio** [comment]
Thanks.
