### ISSUE TITLE
Polish JarFileRemoteApplicationLauncher once SPR-15846 has been fixed

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9942]
We should be able to remove the double `isDirectory()` check once `FileSystemUtils.deleteRecursively(Path)` has been fixed so that it doesn't always return `false`.

**Comment by philwebb** [comment]
`FileSystemUtils` was deprecated (at one point](https://github.com/spring-projects/spring-framework/commit/3714e7b044d1651280e2e6bbcc23123aa8b846d8#diff-ae10b55fcd56ae7b053605131449f245). I guess that decision has been revisited? If so we can also revert a57e6495dd6a2c904f5b2b154ba7ff55e07a4e7e when we fix this.
