### ISSUE TITLE
PropertySourcesPropertyValues reads only encrypted properties when reading a list of objects

### ISSUE THREAD

**Issue by sergiuo** [spring-projects/spring-boot#9943]
Product Version
 spring boot versions 1.4.0-1.5.6, didn't try 2.x
Steps:
 1. create a yaml configuration file with a list of objects each containing both encrypted and unencrypted properties
 2. define a corresponding bean, try to initialize it from yaml file using ConfigurationProperties

Observed:
 only encrypted properties are set, unencrypted are ignored

Debug info:
 PropertySourcesPropertyValues first adds the encrypted value. When the next unencrypted property comes in
 org.springframework.boot.bind.PropertySourcesPropertyValues#putIfAbsent
 the existing collectionOwner is "SystemEnvironmentPropertySource [name='decrypted']" and the "collectionOwner <> source".

Code:
```
@Component
@ConfigurationProperties(prefix = "Root.Config")
public class TestConfig {
    private List<Server> servers = new ArrayList<GraphServer>();

    public List<Server> getServers() {
        return servers;
    }

    public void setServers(List<Server> servers) {
        this.servers = servers;
    }
}
```

yaml:
```
---
Root:
  Conf:
    Servers:
    - Url: "htpt://server1"
      Username: "username"
      Password: "{cipher}AQB6LulUNRD4Sj5fGWv.............="


```

**Comment by wilkinsona** [comment]
I think you've opened this issue in the wrong place. Spring Boot doesn't include any support for encrypted properties.

**Comment by sergiuo** [comment]
Well, looks like "spring-cloud-context" and "spring boot" have different visions on how this should work. All decrypted properties are added as a new PropertySource:
org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer#initialize

I understand why by default spring boot doesn't combine lists from different sources, but in some cases this approach may be very painful. If I want to change a property of an item from a list of 50 items I have to rewrite the config for all 50 items.

Is it possible to add an option to suppress the "same source" check?

**Comment by wilkinsona** [comment]
Sorry, it wasn't clear to me that your problem was about combining lists of configuration properties from different sources. I thought it was specific to property encryption. What I now understand your problem to be is a duplicate of #9137.
