### ISSUE TITLE
Sync debug mode change in Reactor Core 3.1.0-BS

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-boot#9949]
Reactor 3.1.0 Snapshot has changed [the following line](https://github.com/spring-projects/spring-boot/blob/91ac9440ffa76939f0ef7d64a0d9f508225de1e9/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/reactor/core/ReactorCoreAutoConfiguration.java#L43)

Replace by 
```java
Hooks.onOperatorDebug();
```

**Comment by wilkinsona** [comment]
I think this can go in M5 as we're sticking with Spring Framework RC3 and Reactor Bismuth M3 for M4.
