### ISSUE TITLE
Expand Hibernate's dependency management to cover all core modules

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-boot#9950]
I'm using hibernate-spatial in my projects and a many people do too.
However, I must version it manually as Spring Boot doesn't version it like other hibernate artifacts.
Yet I'd like it to be version-synced with hibernate for maximum compatibility.

Could you add hibernate-spatial to Spring Boot's dependencyManagement ?

**Comment by wilkinsona** [comment]
Seems reasonable to me. It's part of the [core ORM now](https://github.com/hibernate/hibernate-orm). There are other modules that we should add while we're at it.

**Comment by vpavic** [comment]
@wilkinsona It appears that `hibernate-spatial` isn't among modules added to dependency management in c4aba91.

**Comment by wilkinsona** [comment]
Good grief. Thanks, @vpavic
