### ISSUE TITLE
Undertow does not support JSPs

### ISSUE THREAD

**Issue by duanxg** [spring-projects/spring-boot#9952]
[Undertow does not support JSPs.](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html)

Spingboot consider making undertow support jsp?

**Comment by wilkinsona** [comment]
The Boot team aren't huge fans of JSP and we recommend the use of other, more modern view technologies. As such, we can't justify the cost of adding support for JSPs to our existing support for embedded Undertow. That said, it should be possible to configure this yourself using an `UndertowDeploymentInfoCustomizer`. Others have blogged about what's necessary I believe.

**Comment by duanxg** [comment]
Ok,thanks!
