### ISSUE TITLE
Add support for configuring Netty's request decoding limits (initial line length, header size, and chunk size)

### ISSUE THREAD

**Issue by PKUliwp** [spring-projects/spring-boot#9955]
I use reactor netty in my spring boot project. I get 404 when I request a long URI (request header is about 5KB, <8KB), like this:

http://myhost/live/filter?ids=...&a=...&b=..&c=...

I reproduce this error in this very simple project. You can find it:

https://github.com/PKUliwp/URI-test
 
I try to use jetty and undertow, and they are ok for same request. But I still want to use netty. I think there is a way to config this property, though I find nothing from reference. I want to know how to config the embedded netty to let my server work when it meets long URI.

**Comment by wilkinsona** [comment]
Thanks for the sample. Improving this will require an enhancement to Reactor Netty. To that end I've opened https://github.com/reactor/reactor-netty/issues/150.

**Comment by wilkinsona** [comment]
The underlying Reactor Netty issue has not yet been fixed so this needs to be pushed back.

**Comment by philwebb** [comment]
Looks like this was backported to 0.7 https://github.com/reactor/reactor-netty/pull/263

**Comment by bclozel** [comment]
We've added a `NettyServerCustomizer` interface in #10418.
Since new options were added on Reactor Netty's `HttpServerOptions.Builder`, you can use this infrastructure to change those options.

Here's an example:

```java
@Configuration
public class ServerConfiguration {
	
  @Bean
  public NettyServerCustomizer serverCustomizer() {
    return options -> options.maxInitialLineLength(LINE_LENGTH).initialBufferSize(BUFFER_SIZE);
  }
}
```

Spring Boot 2.0.RC1 depends on Reactor Netty 0.7.3, which contains those changes. No further changes are required in Spring Boot for now.
