### ISSUE TITLE
Truncated Description of UsernamePasswordAuthenticationToken Constructor

### ISSUE THREAD

**Issue by txwizard** [spring-projects/spring-boot#9957]
This is what I believe is a documentation erratum. The [description of the second constructor](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/authentication/UsernamePasswordAuthenticationToken.html) overload of the `UsernamePasswordAuthenticationToken` object is as follows.

> This constructor should only be used by AuthenticationManager or AuthenticationProvider implementations that are satisfied with producing a trusted (i.e.

What happened to the rest of the text?

**Comment by philwebb** [comment]
Thanks for the report. It's the Javadoc processor chopping things off at the first `.`. The full description is [here](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/authentication/UsernamePasswordAuthenticationToken.html#UsernamePasswordAuthenticationToken-java.lang.Object-java.lang.Object-java.util.Collection-) but we should rework the text to make the summary better.

**Comment by wilkinsona** [comment]
@txwizard This needs to be addressed in Spring Security. Unfortunately, we can't move issues between repositories on GitHub. Can you please open a [Spring Security issue](https://github.com/spring-projects/spring-security/issues/new)?
