### ISSUE TITLE
Fetch @column name values from application.properties

### ISSUE THREAD

**Issue by shwetasm** [spring-projects/spring-boot#9961]
I have two data-source profiles for my project (setup with Spring-boot, JPA Repositories, QueryDsl, Hibernate, existing Oracle DB) and I want to pass column names to @Entity class based on which profile is selected.
@column(name=.....)
private String name;

**Comment by wilkinsona** [comment]
Thanks for the suggestion but this is a duplicate of #829. I don't think anything's changed since that issue was closed in terms of the difficulty of implementing this and how brittle it would be.
