### ISSUE TITLE
`spring.profiles.active` from JNDI and context-param are added to active profiles instead of overriding them

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#9972]
When running a Spring Boot application as a WAR in a servlet container (Tested in Tomcat and WebSphere Liberty), `spring.profiles.active` property set using JNDI or context-param are added to active profiles instead of overriding them.

For example, here's a web.xml that sets both JNDI and context-param:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
	version="3.1">
	<display-name>demo</display-name>

	<context-param>
		<param-name>spring.profiles.active</param-name>
		<param-value>from-context-param</param-value>
	</context-param>

	<!-- sets JNDI -->
	<env-entry>
		<env-entry-name>spring.profiles.active</env-entry-name>
		<env-entry-type>java.lang.String</env-entry-type>
		<env-entry-value>from-jndi</env-entry-value>
	</env-entry>

</web-app>
```

With the above, the following profiles become active: `from-context-param,from-jndi`

To reproduce, add the above to `src/main/webapp/WEB-INF/web.xml` in a Spring Boot application packaged as WAR then run it in a servlet container.

Also, I did more tests by setting `spring.profiles.active` from different sources and observing the active profiles. The results were quite inconsistent:

(`X` means I set `spring.profiles.active` in the property source. `1`/`2` means the profile was active and the number is its order in the active profiles)

|context-param|JNDI|system property|environment property|application.properties|
|-|-|-|-|-|
|X1|X2|X|X|X|
|X1|X2|X||X|
|X1|X2||X|X|
|X1|X2|||X|
|X1||X2|X|X|
|X1||X2||X|
|X1|||X2|X|
|X1||||X|
||X2|X1|X|X|
||X2|X1||X|
||X2||X1|X|
||X2|||X1|
|||X1|X|X|
|||X1||X|
||||X1|X|
|||||X1|

**Comment by wilkinsona** [comment]
What version of Spring Boot are you using?

**Comment by imgx64** [comment]
I tried 1.5.6.RELEASE and 2.0.0.BUILD-SNAPSHOT . Same behavior.

**Comment by wilkinsona** [comment]
The problem occurs because the environment's view of the `spring.profiles.active` property changes during application initialisation. When the active profiles are first queried, the context param property source is still a stub so its contents cannot be seen. At this point, the active profile is retrieved from the JNDI property source and, therefore, is `from-jndi`. Later, when the `ApplicationEnvironmentPreparedEvent` is published, the stub is replaced with a full-blown property source and its contents are now visible. At this point, the active profile is now `from-context-param`. This change in the value of the `spring.profiles.active` property leads to both profiles being active, rather than `from-context-param` winning (which it should as its property source has the higher precedence).

**Comment by wilkinsona** [comment]
Prior to https://github.com/spring-projects/spring-boot/issues/6801 this wouldn't have worked at all as the servlet context-based initialisation of the environment's property sources didn't happen until `prepareRefresh`. It looks like we need to try and find a way of performing that servlet context-based initialisation even earlier.

**Comment by wilkinsona** [comment]
Here's a work around:

```java
package com.example.demo;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;

import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.support.SpringBootServletInitializer;
import org.springframework.web.context.support.StandardServletEnvironment;

public class ServletInitializer extends SpringBootServletInitializer {

	private ServletContext servletContext;

	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		this.servletContext = servletContext;
		super.onStartup(servletContext);
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		StandardServletEnvironment environment = new StandardServletEnvironment();
		environment.initPropertySources(this.servletContext, null);
		return application.sources(Gh9972Application.class).environment(environment);
	}

}
```

Creating the `StandardServletEnvironment` and initialising its property sources up front ensures that the servlet context param property source takes precedence over the JNDI property source from the very beginning as it's never seen in its stubbed form.
