### ISSUE TITLE
BinderTests is failing when building master 2.0.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by bjornlindstrom** [spring-projects/spring-boot#9975]
When I run `mvn clean install` on master the Spring Boot module fails with the following error:

```
Failed tests:
  BinderTests.bindWhenHasMalformedDateShouldThrowException Expected test to throw exception with cause an instance of org.springframework.core.convert.ConversionFailedException
```

It looks like the test fails because the date is valid ("2014-04-01") but it needs to be malformed for the exception to be thrown.

Version: 2.0.0.BUILD-SNAPSHOT

**Comment by wilkinsona** [comment]
I think this test may be accidentally relying on being run with a certain locale or locales. It passes for me and on CI. On my machine (`en_GB` locale) it ends up calling this:

```
LocalDate.parse("2014-04-01", DateTimeFormatter.ofLocalizedDateTime(FormatStyle.SHORT));
```

Which fails as expected. 

What locale are you running the tests in?

**Comment by bjornlindstrom** [comment]
Yes you are right, when I just add Locale.setDefault(Locale.ENGLISH); the test it passes. My default locale is sv_SE.
