### ISSUE TITLE
spring-boot-sample-web-mustache 3 tests failure

### ISSUE THREAD

**Issue by biaocy** [spring-projects/spring-boot#9977]
Hi, I'm a newbie in spring boot.
I want to try out spring boot and mustache today, so I clone this project [spring-boot-sample-web-mustache](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-mustache), run this command ```mvn spring-boot:run```, everything was fine. Until I access ```localhost:8080```, it suppose to return the content within ```welcome.mustache``` file, but actually it return a 404 "Whitelable Error Page". So I import the project into ecplise and run junit test, found 3 tests failure ```testMustacheTemplate(), testMustacheErrorTemplate(), test507Template()```.
Then I do some research, and analyze dependency tree, and found that override ```jmustache``` version to ```1.12``` can fix this issue, tests all past, ```welcome.mustache``` was return. I don't know what's the underlying cause. Appreciate your help.

**Comment by wilkinsona** [comment]
I can't reproduce this. I would guess that Maven corrupted the Mustache jar when it was downloaded. Overriding the version then caused Maven to download a different Mustache jar which wasn't corrupted so it appeared to resolve the problem. Try removing the override and running `mvn dependency:purge-local-repository spring-boot:run`. This will force Maven to download the sample's dependencies again. I would then expect `localhost:8080` to work.

**Comment by biaocy** [comment]
Wow! It really work. Thank you very much!

**Comment by 4val0v** [comment]
I have a similar problem, it works if I change the file extension _*.mustache_ to _*.html_
How to make it work with the _*.mustache_ extension

**Comment by snicoll** [comment]
@4val0v this issue is closed and we don't use the tracker for questions. Please ask on Stackoverflow or join us on Gitter.

**Comment by 4val0v** [comment]
@snicoll 
Add "spring.mustache.suffix=.mustache" to application.properties
Default .html - [MustacheProperties.java](https://github.com/dsyer/spring-boot-mustache/blob/master/src/main/java/org/springframework/boot/mustache/autoconfigure/MustacheProperties.java)
![Spring boot MustacheProperties](https://i.imgur.com/FCbzUPc.png)
