### ISSUE TITLE
Overhaul the trace repository and trace endpoint

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9980]
`TraceRepository` is currently very loosely typed. You can add `Map<String, Object>` to it and get back `Trace` instances (a `Trace` just contains the map and a timestamp). In other words there are no constraints beyond `String` keys on what can be added to the repository. As a result, you have no way of knowing what keys might appear in a particular `Trace` instance's map and what type/structure the values will have. The trace endpoint currently serialises each `Trace` to JSON so clients of the endpoint are affected here too.

The only built-in component that adds entries to the trace repository is `WebRequestTraceFilter` which adds entries describing a Servlet-based HTTP requests to the repository. To avoid clients of both the repository and the endpoint from having to deal with pretty much anything I think we need to restrict, to some extent at least, what a `Trace` can contain. I think we should consider making it HTTP specific and figure out what parts we can support with Servlets, what parts we can support with WebFlux, and what parts we can support with both.

**Comment by wilkinsona** [comment]
We need to decide if we have time to tackle this in 2.0. If we don't we should temporarily drop the feature entirely, rather than limping along with something that we know is a bit broken.

**Comment by philwebb** [comment]
I think we should try to make this work in 2.0. The CF integration uses it so ideally we should have both WebMVC and WebFlux. At a push I'd say we could just support the existing servlet implementation and just remove/refine the `TraceRepository` interface.

**Comment by snicoll** [comment]
I think 2.0 is a good time to tighten the contract. Perhaps we could rename that to `HttpTrace` to make it more consistent?

**Comment by wilkinsona** [comment]
The errors functionality that was added in https://github.com/spring-projects/spring-boot/pull/3948 doesn't appear to work and I'm not sure that it ever has. If I make a request to an endpoint that throws an exception and returns a 500, this is the resulting trace in 1.5.x:

```
    {
        "info": {
            "contextPath": "",
            "headers": {
                "request": {
                    "accept": "*/*",
                    "accept-encoding": "gzip, deflate",
                    "connection": "keep-alive",
                    "host": "localhost:8080",
                    "user-agent": "HTTPie/0.9.3"
                },
                "response": {
                    "X-Application-Context": "application",
                    "status": "500"
                }
            },
            "method": "GET",
            "parameters": {},
            "path": "/foo",
            "remoteAddress": "0:0:0:0:0:0:0:1"
        },
        "timestamp": "2018-01-23T12:51:27.260+0000"
    }
```

Note that there's no `error` entry in the `info` map.

The error entry is supposed to be created using `ErrorAttributes`. This adds a reasonable amount of complexity as it introduces an extra dependency to the class that's performing the tracing. Given that it currently doesn't work and no one has complained, I am going to take the opportunity as part of this overhaul to remove that complexity.
