### ISSUE TITLE
spring.application.name in bootstrap.yml has no effect for logback.xml

### ISSUE THREAD

**Issue by xmlking** [spring-projects/spring-boot#9982]
Bug report: 
Env: Spring Boot 2.0.0.M3 , Mac , kotlin

I am setting  following property in `bootstrap.yml`  so that I can use it in my logback.xml file for adding customField to `LogstashLayout`, but there is no effect.  it is coming as `appName_IS_UNDEFINED`
```yml
spring:
  application:
    name: myapp1
``` 
```xml
<configuration>
    <springProperty name="appName" source="spring.application.name"  />
    ...
</configuration>
```
if i set above property in `application.yml` it works properly. 

Ask:
I should be able to set spring.application.name in bootstrap.yml instead of only in application.yml

**Comment by wilkinsona** [comment]
I think this needs to be raised against Spring Cloud. The behaviour that I see is that `spring.application.name` configured in `bootstrap.yml` is available to the bootstrap context but not to the application's main context. Spring Cloud is responsible for creating the context hierarchy and it appears to set up the hierarchy too late for configuration in `bootstrap.yml` to be used to in the logging configuration of the main application. Specifically, `org.springframework.boot.builder.ParentContextApplicationContextInitializer.initialize(ConfigurableApplicationContext)` is called after `SpringPropertyAction` attempts to retrieve `spring.application.name` from the environment.
