### ISSUE TITLE
Move JaxbAnnotationIntrospector customizer from JerseyAutoConfiguration to JacksonAutoConfiguration/Jackson2ObjectMapperBuilder

### ISSUE THREAD

**Issue by masooh** [spring-projects/spring-boot#9985]
The `JerseyAutoConfiguration` adds the `JaxbAnnotationIntrospector` (via `JacksonResourceConfigCustomizer`) to the `ObjectMapper`. If you want to use the xml annotations for jackson (e.g. `@XmlJavaTypeAdapter`) but don't use a jersey `ResourceConfig`, then you need to copy/reimplement the customizer (see my comment on #9807). This happens if you use jersey as jax-rs client library or webmvc only.
In my opinion this customization belongs to the other jackson customizing configuration classes, `JacksonAutoConfiguration/Jackson2ObjectMapperBuilder`.

**Comment by wilkinsona** [comment]
The changes to `JerseyAutoConfiguration` to register the `JaxbAnnotationIntrospector` were necessary as Jersey registers it by default and we had inadvertently switched that off by configuring Jersey to use the auto-configured `ObjectMapper` (https://github.com/spring-projects/spring-boot/issues/6310). In other words, our auto-configuration of the introspected was deliberately made Jersey-specific.

We could consider broadening it to any application with `jackson-module-jaxb-annotations` on the classpath. Note that I don't think there's any need to copy the customiser. All you need is four lines of code:

```java
@Bean
public JaxbAnnotationModule jaxbAnnotationModule() {
    return new JaxbAnnotationModule();
}
```

This should work as any Jackson modules that are beans are automatically registered with the auto-configured `ObjectMapper`. Can you give it a try and let us know if it works as hoped please?

**Comment by leonard84** [comment]
@wilkinsona why doesn't the `JerseyAutoConfiguration` code use this approach then?

IMHO it would be a good idea to add it to the auto discovery of well known modules.

**Comment by wilkinsona** [comment]
@leonard84 I can't recall the reason unfortunately, assuming there was one. I'd still like confirmation from @masooh that it works for their use case.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
