### ISSUE TITLE
Missing javax-websocket-client-impl in boot-dependencies

### ISSUE THREAD

**Issue by blasd** [spring-projects/spring-boot#9988]
Hello,

The boot-dependencies bom provides a version for javax-websocket-server-impl but not for javax-websocket-client-impl

**Comment by wilkinsona** [comment]
Duplicate of #9989. @blasd If you intend to open a pull request straight away, there's no need for a separate issue as well.

**Comment by wilkinsona** [comment]
Duplicate of #9989
